### ISSUE TITLE
Feature Request - DotNetCoreInstaller should detect already installed versions

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-tasks#10009]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreInstaller

## Environment
- Server - Azure Pipelines using hosted agents

## Issue Description

The hosted agents already come with [several versions of .NET Core SDK installed](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#net-core). It would be nice if the DotNetCoreInstaller task could determine if there is _already_ the appropriate version on the agent - not just in the hosted tool cache - and skip installation and path modification if it's already there. This would allow better portability of the pipeline YAML - have the installer task do work if needed, but quickly end and take up no additional time if you don't need that.

I think you could reasonably easily do that by executing `dotnet --list-sdks` - if it fails to call `dotnet`, install needs to happen; if it fails to find the version requested, install needs to happen; but if it works and finds the version already, no work required.

**Comment by hiyadav** [comment]
Hey @tillig 

I see that this would help in saving time, but sometimes exclusivity of a version is required for some customers. As you might know that .Net Core has a roll forward mechanism which picks a newer version at the time of build/run. In certain cases such behaviour is undesirable, hence we choose to install the version irrespective of it being present in the machine.

What you are suggesting is the tool installer to ensure the version is present and usable, but not provide an exclusive environment. As the exclusivity is also a required ask, I am not sure if we can merge the two or provide both experiences (exclusive version present vs ensuring version is present).

**Comment by hiyadav** [comment]
Hey @tillig,

You're right about global.json and its use. We can't however change the current behaviour as it might break customers, we can try providing a way to get what your ask is.

We shall consider it in our planning and will update once its in the action plan.

**Comment by hiyadav** [comment]
Considering it in enhancement and tracking the ask using this bug : #10405 
Hence closing this bug
