### ISSUE TITLE
VSTest task: Cannot run "Test Plan" based tests when the assembly name does not contain the word "test"

### ISSUE THREAD

**Issue by gasparnagy** [Microsoft/azure-pipelines-tasks#10006]
I have an MsTest test project where the test assembly name does not contain the word "test".

I have created automated test cases in a static test suite and associated the test methods to the test cases.

I have added a VSTest task and configured the test plan, test suite and test configuration. 

The build fails on the hosted VS2017 pool, the build fails with:

```
The slice of type 'Execution' is 'Aborted' because of the error : Microsoft.VisualStudio.TestService.VstestAdapter.TestsNotFoundException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
```

In the log, there was a line that looks wrong (it only searches for dll-s with the word "test"):
```
Source filter: **\*test*.dll,!**\*TestAdapter.dll,!**\obj\**
```

However, I could not find any way to change this source filter setting. There is a setting like that for assembly-based testing, but this is not available for test plan based testing. (Only the search folder).

Changing the assembly name to incluse the word "test" fixes the problem.

Is there a way to change the "source filter" setting?

**Comment by gasparnagy** [comment]
I have figured it out: you need to change the task to "Assembly-based" and change the source filter (maybe Save?) and then switch back to "Test Plan based". The source filter setting will not be visible, but it remembers the setting...

**Comment by kaadhina** [comment]
Hi @gasparnagy I'm unable to repro this issue. Can you please share debug logs from the build where the failure occurred?
Are you using on-prem server? If so , which version?

**Comment by gasparnagy** [comment]
It was on hosted Azure DevOps... I have tried to reproduce it with a brand new project but could not. So this might have been some special situation where the source filter setting get stuck. 

This is a build where it has happened and see the attached log files, but since the problem seemed to be a one-time only, we can close the ticket from my point of view.

https://gasparnagy.visualstudio.com/SpecSync4TFS%20Demo/_build/results?buildId=336 
[logs_336.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3057467/logs_336.zip)

**Comment by kaadhina** [comment]
Thanks for clarifying. Do let us know if it happens again.

**Comment by ferdinand-valderrama-bcs** [comment]
> I have an MsTest test project where the test assembly name does not contain the word "test".
> 
> I have created automated test cases in a static test suite and associated the test methods to the test cases.
> 
> I have added a VSTest task and configured the test plan, test suite and test configuration.
> 
> The build fails on the hosted VS2017 pool, the build fails with:
> 
> ```
> The slice of type 'Execution' is 'Aborted' because of the error : Microsoft.VisualStudio.TestService.VstestAdapter.TestsNotFoundException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
> ```
> 
> In the log, there was a line that looks wrong (it only searches for dll-s with the word "test"):
> 
> ```
> Source filter: **\*test*.dll,!**\*TestAdapter.dll,!**\obj\**
> ```
> 
> However, I could not find any way to change this source filter setting. There is a setting like that for assembly-based testing, but this is not available for test plan based testing. (Only the search folder).
> 
> Changing the assembly name to incluse the word "test" fixes the problem.
> 
> Is there a way to change the "source filter" setting?

@gasparnagy Hi! Sorry for some dumb question, I'm also encountering the same error, you mentioned here that you change the assembly name to include the word test, where did you do that? Was it in the pipeline setting?

**Comment by gasparnagy** [comment]
@ferdinand-valderrama-bcs By changing the assembly name I meant changing the project properties of the test project in Visual Studio. But for this particular issue my comment [here](https://github.com/microsoft/azure-pipelines-tasks/issues/10006#issuecomment-479011625) was a much easier solution.
