### ISSUE TITLE
Spaces in repository path causes azure-pipelines-tasks build failure

### ISSUE THREAD

**Issue by Banner-Keith** [microsoft/azure-pipelines-tasks#10013]
This is not related to builds or tasks on Azure DevOps. This is related to attempting to contribute to this repository.

I am using vscode and I'm on Windows 10.

I have discovered that if you put this repo in a path with a space and then run `npm run build` the build will fail. This is due to paths not being surrounded by quotes for example on: [Line 173 in make-util.js](https://github.com/Microsoft/azure-pipelines-tasks/blob/0ab6301bae6cb89baed88478eca7786ccf0a8cff/make-util.js#L173). I am planning on opening a pull request with my fixes to this problem and anywhere else I find failures.

Errors:
```
tsc --outDir C:\Git Repositories\GitHub\azure-pipelines-tasks\_build\Tasks\Common\securefiles-common --rootDir C:\Git Repositories\GitHub\azure-pipelines-tasks\Tasks\Common\securefiles-common
,error TS6053: File 'Repositories/GitHub/azure-pipelines-tasks/Tasks/Common/securefiles-common.ts' not found.
error TS6053: File 'Repositories/GitHub/azure-pipelines-tasks/_build/Tasks/Common/securefiles-common.ts' not found.
,
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Agent.Tasks@0.5.0 build: `node make.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Agent.Tasks@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Banner-Keith** [comment]
@DavidStaheli This looks like an area where you would be a good expert. Please let me know if this cannot be fixed for whatever reason. I'll try to get a PR up right away so you can review my changes.

**Comment by Banner-Keith** [comment]
It looks like I don't have permissions to create a branch to do my PR.

**Comment by salvmd** [comment]
Removed "Area: Artifacts" label since it's not an issue with the Artifacts build tasks.
@bryanmacfarlane, could you help us route this to the appropriate team? For future reference, should I use the "route" label for these cases?

**Comment by Banner-Keith** [comment]
I started working in this repository again today and encountered this problem again. Can we get some traction on this? It's a very easy fix with minimal impact.

All I did to fix it was change  [Line 173 in make-util.js](https://github.com/Microsoft/azure-pipelines-tasks/blob/0ab6301bae6cb89baed88478eca7786ccf0a8cff/make-util.js#L173) from `run('tsc --outDir ' + outDir + ' --rootDir ' + taskPath);` to `run('tsc --outDir "' + outDir + '" --rootDir "' + taskPath + '"');`

**Comment by damccorm** [comment]
Hey @Banner-Keith sorry for the slow response - I can look at making this change, but would also love a PR fixing that if you're up for it - thoughts?

**Comment by Banner-Keith** [comment]
@damccorm Thanks for the reply. I'd be happy to get a PR out there. I don't seem to have permissions to create a branch on this repository. Could you let me know the best way to proceed so I can get my PR out there?

**Comment by damccorm** [comment]
Sure, the best path is to fork the repository, make your changes in the fork's master branch, and then create a PR from that fork. When you make your updates, there should be a "Create PR" button on your fork's github page right below the commits banner

![image](https://user-images.githubusercontent.com/42773683/69262363-5e640c80-0b91-11ea-9daa-5b0eb5cf5292.png)
