### ISSUE TITLE
PublishTestResults reports incorrect test titles for .trx produced by mocha-trx-reporter

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/azure-pipelines-tasks#10024]
**Bug**  

**Task Name**: PublishTestResults@2

## Environment
- Server - https://devdiv.visualstudio.com
- Build - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2554821

## Issue Description
We have VSCode unit tests that use mocha. The test runner reports the results with mocha-trx-reporter@3.2.0, saves the results to a .trx file, and then PublishTestResults@2 task publishes the results from the .trx file to the run.

All test names in the `Tests` tab of the run are wrong for all the tests. All tests have the same "<Embeddable /> binds Editor.code to state.code" name.
The trx file is fine though. I could open it in VS and see the test names correct. It doesn't contain any "<Embeddable /> binds Editor.code to state.code" string at all.

### Task logs
[log_25_2554821.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3040539/log_25_2554821.zip)

### Error logs
I didn't see any error in the build logs

**Comment by puagarwa** [comment]
Hi, I take a look at trx and it seems not generated correctly, infact I looked at the trx generator source code and it always set classname and name of test as none which is not correct. I have opened an [issue ](https://github.com/Infragistics/mocha-trx-reporter/issues/14)on their repo

    <UnitTest id="87d9cb5f-41cf-4242-aebe-a4a997816610" name="Extensibility API getApiAsync - calling package not detected">
      <Execution id="a1e49339-813f-4cec-9a45-d9b3b2e78920"/>
      <TestMethod codeBase="out/test/api.test.js" **className="none" name="none"/**>
    </UnitTest>

**Comment by puagarwa** [comment]
Also, our recommendation is use industry standard schema that we support (Junit) and that most test tools, including Mocha support as well, TRX is a proprietary format that we don’t want customers to create on their own

**Comment by puagarwa** [comment]
Also, our recommendation is use industry standard schema that we support (Junit) and that most test tools, including Mocha support as well, TRX is a proprietary format that we don’t want customers to create on their own. please use Junit and use PTR task for publishing , let us know if there is any issue.

**Comment by IlyaBiryukov** [comment]
Ok. Thanks for opening the issue on mocha-trx-reporter
