### ISSUE TITLE
VsTestV2 cannot disable uploading test attachments

### ISSUE THREAD

**Issue by victorguo** [microsoft/azure-pipelines-tasks#10020]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - Account name: quest-mpm
        - Team project name: UCA
        - Build definition name: UCA-UnitTests

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
        - OS: Windows Server 2012 R2
        - Agent version: 2.149.2

## Issue Description

In the VsTestV2 task, I have opt-out of the option "Upload test attachments". However, it keeps uploading the test attachments, like result.trx.

![image](https://user-images.githubusercontent.com/199334/55489481-90594a80-5664-11e9-8746-0febe0d9adec.png)

![image](https://user-images.githubusercontent.com/199334/55489388-6869e700-5664-11e9-8212-5610d8c39d57.png)

### Task logs

[logs_63955.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3039308/logs_63955.zip)

**Comment by cltshivash** [comment]
@victorguo Is there a reason to opt out of attachments upload ?

**Comment by victorguo** [comment]
> @victorguo Is there a reason to opt out of attachments upload ?

@cltshivash Yes. Sometimes the attachments could be huge but our upload bandwidth is small. It takes a long time to upload and the attachments are not useful for us.

**Comment by cltshivash** [comment]
@victorguo What are these attachments and can the creation be turned off ? 

Context : We are looking at removing this option altogether.

**Comment by victorguo** [comment]
@cltshivash The attachments are the test result .trx files. That brings up another issue - we have no way to disable it. VsTestV2 always comes with a /logger:"trx".

Sometimes the .trx files are as large as 50 MB and our upload bandwidth is so small that it simply cannot take it.

**Comment by kaadhina** [comment]
Closing this as won't fix since we are planning to remove the option altogether. To reduce the trx size, you may consider running tests in smaller  batches so the bandwidth does not get choked in one go. You can do this by choosing this option
![image](https://user-images.githubusercontent.com/11773114/60583019-8b14b480-9da7-11e9-9f2a-6d11f1cf9419.png)
