### ISSUE TITLE
VSTestV2 Task - Test Plan Configuration - Test results not associated to the correct configuration

### ISSUE THREAD

**Issue by acgritt** [Microsoft/azure-pipelines-tasks#10038]
*Type*: Bug
**Enter Task Name**: VSTestV2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV2

## Environment
- Server
    - Azure Pipelines
- Agent
    - Hosted

## Issue Description

![Capture](https://user-images.githubusercontent.com/10471937/55554569-b7d20680-56a8-11e9-9bf7-133529d24ff6.PNG)

When setting the task to use **Test Plan** and then selecting the appropriate **Test Plan**, **Test Suite** and **Test Configuration** the tests are run as expected but the results are not associated to the selected **Test Configuration** when viewed in the Test Plan results page. Looking at the code for the task itself I could not find any reference to the usage of the **Test Configuration** beyond when it reads the input value.

![Capture - Results](https://user-images.githubusercontent.com/10471937/55554776-3cbd2000-56a9-11e9-9c68-6a72fd5ee410.PNG)

In the above example the test results are all associated with the "QA" configuration when the settings are set for the "Dev Env" configuration. The one thing I did notice is that the ID of the QA configuration is 8 while the Dev Env is 12 so my assumption is that since it isn't using the ID it is just being assigned to the first configuration associated with the tests.

**Comment by kaadhina** [comment]
Hi @acgritt , can you please share debug logs from the pipeline? (set variable system.debug = true)

**Comment by acgritt** [comment]
@kaadhina Attached is the log from the test task.
[tasklog_15.log](https://github.com/Microsoft/azure-pipelines-tasks/files/3054146/tasklog_15.log)

**Comment by kaadhina** [comment]
This is a bug. We will get this fixed soon.
Thank you for reporting and sorry for the inconvenience caused.

**Comment by ChuckOp** [comment]
We're experiencing this issue as well.  It's impacting our reporting and we've paused migration from TFS to VSTS as a result.  Let me know if we can provide any information.  We'll be looking for the fix.

**Comment by kaadhina** [comment]
This has now been fixed and deployed. Thanks.
