### ISSUE TITLE
zip deploy a set of files into a virtual directory or physical directory in azure app service

### ISSUE THREAD

**Issue by melborp** [Microsoft/azure-pipelines-tasks#10035]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure App Service Deploy

## Environment
- Server - Azure Pipelines 
- Agent - Hosted 

## Issue Description

How would you deploy a zip / set of files into a virtual directory in azure app service?

We have virtual directory on a different path than site/wwwroot, where would like to unzip or run from zip the content. That path site/somefolder is mapped to virtual directory in azure app service (some.azurewebsites.net/somefolder ).  

I cant seem to find a way to configure zip deployment or run from zip for a virtual directory and be able tp deploy content to in using the  Azure App Service Deploy task. 

Task has virtual application support, but doesnt work for virtual directories.

**Comment by vincentdass** [comment]
@melborp , it is a feature request to Azure App Service. Can you please post your query [here](https://github.com/projectkudu/kudu/issues)?
