### ISSUE TITLE
unable to push 'latest' via Azure DevOps

### ISSUE THREAD

**Issue by ModestasK** [Microsoft/azure-pipelines-tasks#10032]
this is basically a continueation on #8378

This still is not solved issue. Here is my setup:
First - it created a tagged image (with some version)
> steps:
> - task: Docker@0
>   displayName: 'Push an image'
>   inputs:
>     azureSubscription: 'mysubscription'
>     azureContainerRegistry: '{"loginServer":"myregistry.azurecr.io", "id" : "/subscriptions/xxxx/resourceGroups/Docker/providers/Microsoft.ContainerRegistry/registries/MyRegistry"}'
>     action: 'Push an image'

Second - it should push same image with tag 'latest'

> steps:
> - task: Docker@0
>   displayName: 'Push an image latest'
>   inputs:
>     azureSubscription: 'mysubscription'
>     azureContainerRegistry: '{"loginServer":"myregistry.azurecr.io", "id" : "/subscriptions/xxxx/resourceGroups/Docker/providers/Microsoft.ContainerRegistry/registries/MyRegistry"}'
>     action: 'Push an image'
>     imageName: '$(Build.Repository.Name)'

The outcome of this is that the version taged image gets pushed - all fine. But when it tries to push the 'latest' one - it fails. So the log from a successful push:

 > [command]/usr/bin/docker push myregistry.azurecr.io/xxxxx/some-image:64
> The push refers to repository [myregistry.azurecr.io/xxxxx/some-image]
> 70c8b8e7e24f: Preparing
> 645950f22c02: Preparing
> de8422436a21: Preparing
> ba700d8b1a79: Preparing
> 0824c77a3610: Preparing
> 5dacd731af1b: Preparing
> 5dacd731af1b: Waiting
> ba700d8b1a79: Layer already exists
> 0824c77a3610: Layer already exists
> de8422436a21: Layer already exists
> 5dacd731af1b: Layer already exists
> 645950f22c02: Pushed
> 70c8b8e7e24f: Pushed
> 64: digest: sha256:5aa4eb8b297a324b49252821e2d1df9afbc25d4ee4582082efd0aa8520ef7696 size: 1581

the failed one:

> [command]/usr/bin/docker push myregistry.azurecr.io/xxxxx/some-image:latest
> The push refers to repository [myregistry.azurecr.io/xxxxx/some-image]
> tag does not exist: myregistry.azurecr.io/xxxxx/some-image:latest
> ##[error]tag does not exist: myregistry.azurecr.io/xxxxx/some-image:latest
> ##[error]/usr/bin/docker failed with return code: 1

Initially I thought that this is somewhat related to my private registry, but if I try to push the same version built image from my local PC setting the tag to 'latest' - it works fine.

**Comment by ds-ms** [comment]
@ModestasK did you try by adding `includeLatestTag: true` to your inputs?

**Comment by ModestasK** [comment]
Yeah, Tried putting that into both tasks. meaning where image name is $(Build.Repository.Name):$(Build.BuildId) and $(Build.Repository.Name) - makes no difference - it just does not allow pusing the image with 'latest' tag. You can also see that in the log where it executes this:

> [command]/usr/bin/docker push myregistry.azurecr.io/xxxxx/some-image:64
> The push refers to repository [myregistry.azurecr.io/xxxxx/some-image]

result - success.
And excuting this:

> [command]/usr/bin/docker push myregistry.azurecr.io/xxxxx/some-image:latest
> The push refers to repository [myregistry.azurecr.io/xxxxx/some-image]

result - fails.

**Comment by ds-ms** [comment]
Can you add logs when it's building the image as well? Just to verify if it's building an image with latest

**Comment by ModestasK** [comment]
Checked the box to step where image name is $(Build.Repository.Name):$(Build.BuildId). Result:

> [command]/usr/bin/docker push myregistry.azurecr.io/xxx/my-image:71
> The push refers to repository [myregistry.azurecr.io/xxx/my-image]
> d473a19d525c: Preparing
> f05bc26c242b: Preparing
> de8422436a21: Preparing
> ba700d8b1a79: Preparing
> 0824c77a3610: Preparing
> 5dacd731af1b: Preparing
> 5dacd731af1b: Waiting
> de8422436a21: Layer already exists
> 0824c77a3610: Layer already exists
> ba700d8b1a79: Layer already exists
> 5dacd731af1b: Layer already exists
> f05bc26c242b: Pushed
> d473a19d525c: Pushed
> 71: digest: sha256:8fe02a2fc0ac129fca8b0448b4bd1a03cab9714852166d43d5187ee9a5b5a61d size: 1581
> [command]/usr/bin/docker push myregistry.azurecr.io/xxx/my-image:latest
> The push refers to repository [myregistry.azurecr.io/xxx/my-image]
> tag does not exist: myregistry.azurecr.io/xxx/my-image:latest
> ##[error]tag does not exist: myregistry.azurecr.io/xxx/my-image:latest
> ##[error]/usr/bin/docker failed with return code: 1

**Comment by ModestasK** [comment]
Log from task with image name $(Build.Repository.Name):

> 
> [command]/usr/bin/docker push myregistry.azurecr.io/xxx/my-image:latest
> The push refers to repository [myregistry.azurecr.io/xxx/my-image.feed]
> tag does not exist: myregistry.azurecr.io/xxx/my-image:latest
> ##[error]tag does not exist: myregistry.azurecr.io/xxx/my-image:latest
> ##[error]/usr/bin/docker failed with return code: 1
>

**Comment by ds-ms** [comment]
@ModestasK Could you attach the task config (YAML) for your `docker build`?
You need to add `includeLatestTag: true` to your build step as well. That would tag your image with `latest` tag. 
Then, with `includeLatestTag: true` enabled in your push step, docker would be able to find an image with `latest` tag on that machine to push to the registry.

**Comment by ModestasK** [comment]
> steps:
> - task: Docker@0
>   displayName: 'Push an image latest'
>   inputs:
>     azureSubscription: 'xxxxxx'
>     action: 'Push an image'
>     imageName: '$(Build.Repository.Name)'
>     includeLatestTag: true

**Comment by ModestasK** [comment]
argh... that worked. You were right from the beginning. I was mixing the build step with the publish step. Though I think it would be quiet nice i you could add tooltip or additional message to publishing task 'include latest' checkbox, that if you check this you should also make sure that build task also has this checked.
Thanks a lot Deepak!
I think we can close this

**Comment by cpolzer** [comment]
the option "includeLatestTag: true" is gone in yml pipelines. Would it be possible that this gets some more attention in the docs?
