### ISSUE TITLE
NuGet task not respecting Bypass Proxy settings

### ISSUE THREAD

**Issue by jeffpriz** [microsoft/azure-pipelines-tasks#10048]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGet

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    TFS On-Prem
    - If using TFS on-premises, provide the version: 16.131.28226.3
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Private
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 2.125.1
--

## Issue Description
we are attempting to utilize the NuGet task to publish a NuGet package to our TFS on-prem NuGet Feed.  The Task fails with an ECONNRESET issue.  Doing some digging, the Call to TFS from the Build Agent is being routed through our Proxy server, even though the Build Agent machine (Windows Server) is configured to Bypass proxy for internal addresses including the TFS Server.  I've also Added a NO_PROXY environment variable, but the calls still route through the Proxy.

I need to get the task to respect the Bypass proxy settings

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
[6_NuGet push.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/3049163/6_NuGet.push.txt)

[Insert error from the logs here for a quick overview]

**Comment by tkrick** [comment]
bypass proxy support in our tasks got better in January this year. That means it is available right now in Azure Dev Ops, but not on-premises Server product. Unfortunately that means those changes won't be seen until the 2019.1 release. Until then you may have other options like using a nuget custom command (but then you have to manage other things like creds).

**Comment by elbatk** [comment]
Closing this as @tkrick 's comment above explains the current status and we haven't heard back, please feel free to reach back out if you're still having issues.
