### ISSUE TITLE
failed to download "stable/datadog"

### ISSUE THREAD

**Issue by Sahasrara** [microsoft/azure-pipelines-tasks#10040]
**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: helm deploy  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- Agent - Hosted or Private: 
Hosted    
    - If using Hosted agent, provide agent queue name:
Don't know where that is

## Issue Description

[command]/usr/local/bin/helm upgrade --install --recreate-pods --values /home/vsts/work/1/s/datadog/stg-values.yml --set datadog.apiKey=*** --wait datadog stable/datadog
Error: failed to download "stable/datadog" (hint: running `helm repo update` may help)
##[error]Error: failed to download "stable/datadog" (hint: running `helm repo update` may help)

**Comment by ds-ms** [comment]
@Sahasrara the issue is: the local repository is not initialized. 
If you run a `helm init --client-only` before running your upgrade or install step, it should work out for you.

**Comment by ds-ms** [comment]
Doing that by default for hosted images now: https://github.com/microsoft/azure-pipelines-image-generation/pull/976
