### ISSUE TITLE
Help needed with a picklist

### ISSUE THREAD

**Issue by kripajoym** [Microsoft/azure-pipelines-tasks#10055]
1.Autocomplete.
EditableOptions is set true, still it should **not** allow me to enter and save any value other than the dropdown values

2.Need to restrict the user to enter the value from picklist only.
dataSourceBindings will return values ["abc","def","ghi","jkl"]
Since EditableOptions is set true, when I type  "a" the list should show me only elements starting with "a", or the element which is starting with "a" (Autocomplete)

How can i implement both? 

`input
        "name": "applications",
        "type": "pickList",
        "label": "Application",
        "required": true,
         "properties": {
          "EditableOptions": "True"
         },
        "helpMarkDown": "The application"

"dataSourceBindings": [
      {
        "target": "applications",
        "endpointId": "$(abcd)",
        "endpointURL":"{{endpoint.url}}/joy/tests?$orderby=Name",
        "resultselector":"jsonpath:$.[*]",
        "resultTemplate":"{ \"Value\" : \"{{{Id}}}\", \"DisplayValue\" : \"{{{Name}}}\" }"`

**Comment by bryanmacfarlane** [comment]
Not an issue with a task in this repo.  If I'm mistaken, please log a new issue and fill out the template
