### ISSUE TITLE
Azure PowerShell version required for Azure SQL Database Deployment task

### ISSUE THREAD

**Issue by guylevy** [Microsoft/azure-pipelines-tasks#10065]
*Question*: 

**Azure SQL Database Deployment**:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1

## Environment
- Server - TFS on-premises 2018.3

- Agent - Private,
    -  OS: Win Server 2016
    - agent version: 2.136.1

## Issue Description
The task documentation mentions a specific (rather old) version of Azure PowerShell (Installer v1.3.0) - [see here](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlAzureDacpacDeploymentV1/README.md#azure-powershell)

Does the task work with more recent versions of Azure PowerShell? specifically, does it work with 5.x?

**Comment by ArieHein** [comment]
Azure Powershell is not Powershell (per se)
Powershell has versions 2.0, 3.0, 4.0, 5.0, 5,X, 6.X and soon 7.0
Azure Powershell has a different versioning schema
https://github.com/Azure/azure-powershell/releases

Powershell:
https://github.com/powershell/powershell

Azure Powershell:
https://github.com/Azure/azure-powershell

**Comment by Ajay-MS** [comment]
@guylevy 

Yes, task works with the recent version of the Azure PS task.

**Comment by guylevy** [comment]
> @guylevy
> 
> Yes, task works with the recent version of the Azure PS.

thanks, that is what I also observed just yesterday. Maybe the documentation should be updated as it was the reason for my confusion and for creating this issue.

**Comment by Ajay-MS** [comment]
@guylevy 

Thanks for confirmation. Closing this issue.
