### ISSUE TITLE
Npm taks: Report warnings

### ISSUE THREAD

**Issue by olaeld** [microsoft/azure-pipelines-tasks#10064]
When Npm reports warnings, can we please have them show up in the Azure Pipelines job log?

For example: "Npm install" reports the following warning:
npm WARN deprecated print.js@1.0.18: WARNING: This project has been renamed to print-js. Install using npm print-js instead.

But I have to click on the job task to read the log to see that there is a warning.

Type: Feature
Task Name: Npm

The '.NET Build' task shows warnings, but not the 'npm install' task. 
![image](https://user-images.githubusercontent.com/189315/55787248-26063700-5ab6-11e9-90fc-4817dc1d06cc.png)

**Comment by salvmd** [comment]
@elbatk FYI for triage

**Comment by elbatk** [comment]
Hi @olaeld , we're looking to change our pipelines tasks in the near future. As part of that change we'll be doing an overhaul of how our tasks are used, so we won't be making any improvements to the current tasks but we'll consider this feedback in the redesign, thanks!

**Comment by rmorrin** [comment]
@elbatk Is there any timeframe for when these changes are due? Or perhaps a workaround of achieving this using the current npm tasks?

We have a number of code quality npm tasks that report warnings (tslint etc) which would be useful to surface here.

**Comment by Styxxy** [comment]
> Hi @olaeld , we're looking to change our pipelines tasks in the near future. As part of that change we'll be doing an overhaul of how our tasks are used, so we won't be making any improvements to the current tasks but we'll consider this feedback in the redesign, thanks!

Do you have information on this "overhaul"? What should we be using now to have those warnings surfaced into Azure Pipelines run?
