### ISSUE TITLE
Combine existing tasks?

### ISSUE THREAD

**Issue by JamieMagee** [Microsoft/azure-pipelines-tasks#10082]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

## Issue Description

Is it possible to combine existing tasks in a custom task?

We have a lot of repositories that all have the same, or similar, `.azure-pipelines.yml`. However, our standard build has evolved over time, such that we now have multiple repositories that are not in line with our standard build process.

It's possible, but time consuming, to update these all manually. This got me wondering if it was possible to refer to a 'facade task', which is really multiple tasks. This would allow that one task definition to be updated, and all builds that make use of it will automatically get the updated task definition.

**Comment by joshmgross** [comment]
Hey @JamieMagee sounds like you might benefit from using YAML templates: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

**Comment by JamieMagee** [comment]
Yes, that's exactly what I'm looking for! Specifically [Using other repositories](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories)

Thanks!
