### ISSUE TITLE
IoT Edge create deployment return success when IoT Hub quota exceeded

### ISSUE THREAD

**Issue by shizn** [microsoft/azure-pipelines-tasks#10088]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: IoT Edge  

## Environment
Azure DevOps. 

## Issue Description
Create deployment task.
While IoT Hub deployment quota exceeded, the task still returns success.

**Comment by shizn** [comment]
https://github.com/Azure/azure-iot-cli-extension/issues/72

**Comment by blackchoey** [comment]
This is currently blocked by Azure/azure-iot-cli-extension#72. No changes required from Azure Pipelines task side.
