### ISSUE TITLE
Confusing message in docs for deploying webapp

### ISSUE THREAD

**Issue by PhilPeters304** [microsoft/azure-pipelines-tasks#10080]
https://github.com/Microsoft/azure-pipelines-tasks/blob/984ca40b9dd3b9279e91936ebb52f72626e8d0f2/Tasks/AzureRmWebAppDeploymentV4/task.json#L437

The message on this line is confusing. I think a rebrand of Azure DevOps has created a mis-match.. user supplied variables are now called pipeline variables which are not excluded. System (provided) variables are exluded

**Comment by Ajay-MS** [comment]
@PhilPeters304 

Based on your conversation with @N-Usha on issue https://github.com/microsoft/azure-pipelines-tasks/pull/10089, I am closing this issue. 

Feel free to reopen if you still feel this issue relevant.
