### ISSUE TITLE
IISWebAppDeploymentOnMachineGroupV0 Removes comments, changes order

### ISSUE THREAD

**Issue by jachin84** [microsoft/azure-pipelines-tasks#10087]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: IISWebAppDeploymentOnMachineGroupV0

## Issue Description
When performing variable substitution in IISWebAppDeploymentOnMachineGroupV0 the resulting xml file has the comments stripped out and the order of the elements is changed. This makes it challenging to troubleshoot the resulting xml file as it looks wildly different than the original.

Is this the intended behavior? I would expect variable substitution to leave comments and the original order of elements intact.

**Comment by Ajay-MS** [comment]
@jachin84 

Yes I agree with you that our current behaviour ignores the current comment during substitution. 

But order of the elements we are not impacting. Also, I am not able to repro it.

Can you please share some same xml file in which order is getting impacted after substitution.

**Comment by Ajay-MS** [comment]
@jachin84 

Regarding the ignorance comment behaviour this item is already in our backlogs but it could take time as we are not planning to invest here right now and will pick it after some time. 

XML order impact issue I am not able to Repro. 

So, Closing this issue. Feel free to reopen with Sample XML and debug logs in case you see order impacting issue further or you have any other question.
