### ISSUE TITLE
PublishCodeCoverageResults ignores reports

### ISSUE THREAD

**Issue by IOrlandoni** [Microsoft/azure-pipelines-tasks#10094]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResults

## Environment

- Server: Azure DevOps
    - Account name: mobiglobalsolutions
    - Team project name: Couponing Platform
    - Build definition name: OpenMobiFeeder
    - Build ID: 3491
    - Build #: 2019.04.11.3491

- Agent: Hosted
    - Queue name: Hosted VS2017

## Issue Description

"Publish code coverage results" ignores .htm files found in reports directory.

As you can see in the task logs below, `reportDirectory` is set to `D:\a\1\s\TestResults\Coverage\Reports` and the following files exist:
- `D:\a\1\s\TestResults\Coverage\Reports\index.htm`
- `D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.MsmqHandler_MsmqHandler.htm`
- `D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.Processor_Processor.htm`
- `D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.Processor_TransactionNameValueCollection.htm`
- `D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.UcsMainHandler_UcsMainHandler.htm`

However, they are not uploaded as part of the code coverage artifact and, therefore, not shown on the code coverage tab of the build.

Last (known) working version was 1.148.0, as found in build 3476 of the same commit, of the same repository, with the same .yml file on the same build definition.

### Task logs
    ##[debug]Evaluating condition for step: 'Publish coverage report'
    ##[debug]Evaluating: SucceededNode()
    ##[debug]Evaluating SucceededNode:
    ##[debug]=> True
    ##[debug]Result: True
    ##[section]Starting: Publish coverage report
    ==============================================================================
    Task         : Publish Code Coverage Results
    Description  : Publish Cobertura or JaCoCo code coverage results from a build
    Version      : 1.150.2
    Author       : Microsoft Corporation
    Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=626485)
    ==============================================================================
    ##[debug]agent.TempDirectory=D:\a\_temp
    ##[debug]loading inputs and endpoints
    ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
    ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
    ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
    ##[debug]loading INPUT_CODECOVERAGETOOL
    ##[debug]loading INPUT_FAILIFCOVERAGEEMPTY
    ##[debug]loading INPUT_REPORTDIRECTORY
    ##[debug]loading INPUT_SUMMARYFILELOCATION
    ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
    ##[debug]loaded 8
    ##[debug]Agent.ProxyUrl=undefined
    ##[debug]Agent.CAInfo=undefined
    ##[debug]Agent.ClientCert=undefined
    ##[debug]Agent.SkipCertValidation=undefined
    ##[debug]agent.workFolder=D:\a
    ##[debug]loading inputs and endpoints
    ##[debug]loaded 0
    ##[debug]check path : D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.150.2\task.json
    ##[debug]adding resource file: D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.150.2\task.json
    ##[debug]system.culture=en-US
    ##[debug]codeCoverageTool=cobertura
    ##[debug]summaryFileLocation=D:\a\1\s\TestResults\Coverage\**\Cobertura.xml
    ##[debug]reportDirectory=D:\a\1\s\TestResults\Coverage\Reports
    ##[debug]additionalCodeCoverageFiles=null
    ##[debug]failIfCoverageEmpty=false
    ##[debug]System.DefaultWorkingDirectory=D:\a\1\s
    ##[debug]disable.coverage.autogenerate=undefined
    ##[debug]defaultRoot: 'D:\a\1\s'
    ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
    ##[debug]findOptions.followSpecifiedSymbolicLink: 'false'
    ##[debug]findOptions.followSymbolicLinks: 'false'
    ##[debug]matchOptions.debug: 'false'
    ##[debug]matchOptions.nobrace: 'true'
    ##[debug]matchOptions.noglobstar: 'false'
    ##[debug]matchOptions.dot: 'true'
    ##[debug]matchOptions.noext: 'false'
    ##[debug]matchOptions.nocase: 'true'
    ##[debug]matchOptions.nonull: 'false'
    ##[debug]matchOptions.matchBase: 'false'
    ##[debug]matchOptions.nocomment: 'false'
    ##[debug]matchOptions.nonegate: 'false'
    ##[debug]matchOptions.flipNegate: 'false'
    ##[debug]pattern: 'D:\a\1\s\TestResults\Coverage\**\Cobertura.xml'
    ##[debug]findPath: 'D:\a\1\s\TestResults\Coverage'
    ##[debug]statOnly: 'false'
    ##[debug]findPath: 'D:\a\1\s\TestResults\Coverage'
    ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
    ##[debug]findOptions.followSpecifiedSymbolicLink: 'false'
    ##[debug]findOptions.followSymbolicLinks: 'false'
    ##[debug]  D:\a\1\s\TestResults\Coverage (directory)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports (directory)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports\Cobertura.xml (file)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports\index.htm (file)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.MsmqHandler_MsmqHandler.htm (file)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.Processor_Processor.htm (file)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.Processor_TransactionNameValueCollection.htm (file)
    ##[debug]  D:\a\1\s\TestResults\Coverage\Reports\Mobi724.OpenMobiFeeder.UcsMainHandler_UcsMainHandler.htm (file)
    ##[debug]8 results
    ##[debug]found 8 paths
    ##[debug]applying include pattern
    ##[debug]1 matches
    ##[debug]1 final results
    ##[debug]Found 1 result(s) matching pattern: D:\a\1\s\TestResults\Coverage\**\Cobertura.xml
    ##[debug]Resolved summary file: D:\a\1\s\TestResults\Coverage\Reports\Cobertura.xml
    Reading code coverage summary from 'D:\a\1\s\TestResults\Coverage\Reports\Cobertura.xml'
    ##[debug]Processed: ##vso[codecoverage.publish codecoveragetool=cobertura;summaryfile=D:\a\1\s\TestResults\Coverage\Reports\Cobertura.xml;]
    ##[section]Async Command Start: Publish code coverage
    Publishing coverage summary data to TFS server.
     Lines- 0 of 158 covered.
     Branches- 0 of 126 covered.
    Modifying Cobertura Index file
    Publishing code coverage files to TFS server.
    Uploading 1 files
    ##[debug]File: 'C:\Users\VssAdministrator\AppData\Local\Temp\Code Coverage Report_3491\summary3491\Cobertura.xml' took 282 milliseconds to finish upload
    ##[debug]Detail upload trace for file: Code Coverage Report_3491/summary3491/Cobertura.xml
    ##[debug]File 'Code Coverage Report_3491/summary3491/Cobertura.xml' will be uploaded in one chunk.
    ##[debug]Attempt '1' for uploading chunk '1' of file 'Code Coverage Report_3491/summary3491/Cobertura.xml'.
    ##[debug]Generate new HttpRequest for uploading file 'Code Coverage Report_3491/summary3491/Cobertura.xml', chunk '1' of '1'.
    ##[debug]Start uploading file 'Code Coverage Report_3491/summary3491/Cobertura.xml' to server, chunk '1'.
    ##[debug]Finished upload chunk '1' of file 'Code Coverage Report_3491/summary3491/Cobertura.xml', elapsed 245 (ms), response code 'Created'.
    File upload succeed.
    Published 'C:\Users\VssAdministrator\AppData\Local\Temp\Code Coverage Report_3491' as artifact 'Code Coverage Report_3491'
    ##[section]Async Command End: Publish code coverage
    ##[section]Finishing: Publish coverage report

**Comment by IOrlandoni** [comment]
This was done intentionally for #9704.

You can no longer provide your own reports and you have to let task auto generate them from a 'Cobertura' (case sensitive) summary file.

**Comment by nickwilliams-codynamic** [comment]
Are there no plans to add the previous functionality back? I can't really understand why this would have been removed.

There is now no way to produce the test coverage reports as part of a Docker build, which was our use case for that feature.

**Comment by alarobric** [comment]
Am I in limbo between this feature being removed and the new one implemented then?
I have a working Cobertura xml log but can't use the html report. Instead I keep seeing this error in the build Code Coverage tab.

Code coverage report cannot be rendered as report HTML was not found. Please verify that "Report Directory" containing an HTML report was specified when publishing code coverage.

Is there any way to see whether the latest release has rolled out to my organization yet?

**Comment by IOrlandoni** [comment]
@alarobric If you're already generating a cobertura type summary, you can call the "publish code coverage results" task using 'Cobertura' as codeCoverageTool (note the upper-case C, it's case sensitive) and the task will automatically generate reports and publish them, from your summary.

Check #9704 & #9962 to see where this is going...

**Comment by alarobric** [comment]
It turns out I was missing the upper-case C. I think there's a minor bug there, as I didn't get a warning that it was an unsupported setting (which I did when set to 'custom' later. But clearly it wasn't working right either.
Anyway, thanks for that, working now and looks pretty good.

**Comment by cforce** [comment]
Actually this dotnet tools is used under the covers to create the reports
https://github.com/danielpalme/ReportGenerator/
The question is, is it enough to in .net runtime to your worker pool where you run the CI jobs.
