### ISSUE TITLE
task.setvariable does an implied create, is there a task.deletevariable to allow for explicit variable removal

### ISSUE THREAD

**Issue by gtalton** [Microsoft/azure-pipelines-tasks#10095]
I am currently seeing an issue where a variable is created in a called template, persists into the calling of a subsequent instance of the same template. It would be nice if I could explicitly delete a variable upon exit of the template. Is this possible? I have tried deleting the variable from within Powershell however that doesn't seem to delete the variable in the next invocation of a following Powershell task.

**Comment by damccorm** [comment]
I believe can just call `setvariable` again and set the variable to an empty string (it works like environment variables).

**Comment by damccorm** [comment]
I'm going to close, just let me know if you'd like me to reopen.

**Comment by MatejKafka-MSFT** [comment]
This doesn't seem to match my experience – calling `Write-Host "##vso[task.setvariable variable=VAR]"` sets the env var in following steps to an empty string.

Is it possibly related to a [breaking change in .NET 9](https://github.com/dotnet/docs/issues/41471) where empty string passed to `Environment.SetEnvironmentVariable(...)` no longer deletes the env var, but sets it to an empty string?
