### ISSUE TITLE
Secret Value of SAS Token cannot be used in VSTS Release pipeline custom powershell task

### ISSUE THREAD

**Issue by Saugat168** [Microsoft/azure-pipelines-tasks#10096]
This is very close to the issue: 4310 , though that never confirms if there is a way out or is it simply a limitation.

https://github.com/Microsoft/azure-pipelines-tasks/issues/4310

I have a SAS token which is set in previous Release task and then the Create Resource Group Task uses that SAS token to create the resource group. However, when I try to use the same SAS Token in a powershell task, if I just use in the parameters section of the PowerShell Task
-SecretArgument '$(SASToken)'

And then print it in the powershell script I get: ***
If I use , in the parameters section of the PowerShell Task
-SecretArgument $(SASToken)

And then print it out in the script, it errors out saying it contains"&" (the special characters that SAS token has), but I can see the half truncated value of $SASToken in the failed release log in clear text.

I have also used single quotes but that also masks it as ***. Is there a way to get this value in the powershell script?

Strangely , this SAS token works (without quotes) in the "Deploy Resource Group Task" when it's passed in the override parameter section (as many tutorials show).

I have run out of ideas to use it in the PowerShell task. Is this a bug in VSTS Release pipeline that secrets with special characters can't be used?

**Comment by bergmeister** [comment]
@Saugat168 They have added an environment variables section to the task that might solve your problem
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#arguments

**Comment by Saugat168** [comment]
@bergmeister Thanks for getting back. Yes, I did try that before raising the issue here. But I get blank. Actually, I found this as well 
[https://stackoverflow.com/questions/45593094/how-do-i-use-a-secret-variable-in-a-vsts-release-task](url) The user did raise a bug here : 
[https://developercommunity.visualstudio.com/content/problem/94475/secret-variable-in-variable-not-group-not-availabl.html]()

But it seems to have been closed saying can't be reproduced, but that is probably exactly what's happening in my case.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@bergmeister && @kmkumaran && @chperich Any update on this issue?

**Comment by chperich** [comment]
@Saugat168: VSTS masks out all the secret values from logs. That is the reason you see "***" when you print the secret value instead of its original content. You can still use the secret value though. That is, if you pass it as an input to any command expecting a SASToken, you should see the command succeeding.

**Comment by chperich** [comment]
@Saugat168: I have closed this issue as its not a bug. Please try to use the SAS token and see if it works for you. If you still run in to issues, feel free to re-open.
