### ISSUE TITLE
Cannot find module 'azure-arm-rest/azure-arm-endpoint'

### ISSUE THREAD

**Issue by yijiamicrosoft** [Microsoft/azure-pipelines-tasks#10097]
Hello,

I'm trying to develop a custom task that integrate with our service Azure AppConfiguration. And I followed AzureKeyVaultV1 example to build the task. However, when I just my task, with ```node index.js```, it shows the error ```##vso[task.issue type=error;]Unhandled: Cannot find module 'azure-arm-rest/azure-arm-endpoint'```. Then, I found that package ```azure-arm-rest``` doesn't have any compiled ```.js``` files or ```.d.ts``` files. Should I compile it by myself?

**Comment by bryanmacfarlane** [comment]
Yes, you need to compile it.  A task is a self contained fully built and realized package.
