### ISSUE TITLE
npm task not showing color from chalk

### ISSUE THREAD

**Issue by justinmwarner** [Microsoft/azure-pipelines-tasks#10108]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NpmV1

list here (V# not needed):  V1
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: o365exchange, Weve_DA/, 790

## Issue Description

We're looking into using the npm package "concurrently". This library uses chalk to output in color. I'm wondering why the colors do not show up for our task?

### Task logs

N/A

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Not an error.

**Comment by salvmd** [comment]
@bryanmacfarlane, could you help me route this to a more appropriate team? I don't think the question here is specific to the npm task since this is about displaying colors for commands in the UI. The npm task adds support for authentication and then runs npm commands using azure-pipelines-task-lib/toolrunner (https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts), which I believe is where the output of the tool (in this case npm) is handled.

**Comment by bryanmacfarlane** [comment]
The issue is with npm and that's covered by artifacts.  You can talk to @yaananth if you want to see why the artifact task isn't round tripped colors correctly.

**Comment by yaananth** [comment]
Thanks for sending me the log offline.
Here are the colors we support:
fg colors - 30 (black), 31 (red), 32 (green), 33 (yellow), 34 (blue), 35 (magenta), 36 (cyan), 37 (white), 90 (grey)
bg colors - 40 (black), 41 (red), 42 (green), 43 (yellow), 44 (blue), 45 (magenta), 46 (cyan), 47 (white)


It’s using ESC[94m …. ESC[39m
Which isn’t in our range for support. 

We will add that, thanks for the report!

If you would like to track, you can post this here https://developercommunity.visualstudio.com/content/idea/post.html?space=21

But this is now on our radar and will add support soon.

**Comment by johnnyreilly** [comment]
Hey @yaananth!

As far as I can tell, Azure Pipelines doesn't support colors if you're using a package like chalk.  There was mention of support being added - but as far as I can tell it hasn't been.  Do you know if this is still planned?  (Or if I'm doing it wrong!)

**Comment by yaananth** [comment]
👋  sorry I am not on this and not actively working, you might have to open new issue to get some attention 🙇

**Comment by josundt** [comment]
@justinmwarner  `chalk` enables color output only when it terminal color support is verified through chalk's `supports-color` package dependency. The check has up till now unfortunately returned `false` when running in an Azure DevOps pipeline.

I made a PR to `supports-color` today to ensure 16 color support is allowed when Azure Pipelines environment is detected through the inspection of environment variables.

https://github.com/chalk/supports-color/pull/126

Hopefully a new release of `chalk` will arrive quite soon with the Azure DevOps pipelines support.
