### ISSUE TITLE
PATH include wrong $JAVA_HOME/bin when using jdkVersionOption: '1.11'

### ISSUE THREAD

**Issue by vorburger** [Microsoft/azure-pipelines-tasks#10103]
**Question, Bug, or Feature?**  *Type*: Bug

**Enter Task Name**: MavenV3

## Environment
- Server - Azure Pipelines https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=964
- Agent - Hosted or Private: ?
    
## Issue Description

see https://github.com/quarkusio/quarkus/issues/2012 for full background, but the TL;DR is that [when you specify `jdkVersionOption: '1.11'`](https://github.com/quarkusio/quarkus/blob/c68434ef25c7efa0750ba89953ebbf38b4c424ab/azure-pipelines.yml#L73), then you would expect that `Runtime.exec("java")` from some test gives you Java 11 - but it does not, you get a Java 8... :sob: 

You should prepend `$JAVA_HOME/bin` to `PATH`, but AFTER you set that `JAVA_HOME` in function of the `jdkVersionOption` - do you see what I mean? (I could not find where the script which does this kind of thing is here.)

**Comment by joshmgross** [comment]
Hey @vorburger, are you saying that your maven tests are failing after you build using Java 11 because the tests use Java 8?

**Comment by vorburger** [comment]
> maven tests are failing after you build using Java 11 because the tests use Java 8?

No, a test launched an external `java` process, without specifying a directory, so it uses whatever `java` is first found on `PATH`. And that seems to always be a Java 8, even when you want when you specify `jdkVersionOption: '1.11'`.

It's not really strictly related to tests. You just need to set `PATH` correctly, as described above. 

Does this make sense?

**Comment by joshmgross** [comment]
Hey @vorburger, this is as designed. The Maven task only sets up the java version for the maven process itself, not for the entire pipeline.

If you want to set the java version for an entire pipeline, then setting up the PATH as you described is a valid solution.
