### ISSUE TITLE
UWP app does not show checkbox when installed through build artifact

### ISSUE THREAD

**Issue by coderlife14** [microsoft/azure-pipelines-tasks#10138]
**Question, Bug, or Feature?**  
*Type*: Question
## Environment
- Server - Azure Pipelines
- Agent - Hosted: 
    - If using Hosted agent, provide agent queue name: Hosted VS2017
## Issue Description
I have a Xamarin forms UWP mobile app. I have created a build definition in AzureDevOps to create a package for UWP app installation. The build succeeds and a package is created. When I install the app and open it, a checkbox is not available in the user interface. So I created package locally through visual studio 2017 and installed the app using this package. When I run the app, I can see the checkbox in the user interface. I don't know why the checkbox disappears whenever I install the app using the package generated by AzureDevOps build.

[Include task name(s), screenshots and any other relevant details]
https://photos.app.goo.gl/NxARwL9TxWWmniq79

### Task logs
https://drive.google.com/file/d/1nS3MpOa9b09uiZZyMYRLTZyTKULL5rye/view?usp=sharing

**Comment by coderlife14** [comment]
@bryanmacfarlane , Do we have any suggestions on this issue? I really need to understand where did I
 go wrong with this?

**Comment by coderlife14** [comment]
@bryanmacfarlane any updated on this?

**Comment by moswald** [comment]
When you build locally, what version of the UWP runtime gets pulled in? It's possible (likely) that the Hosted VS2017 image hasn't been updated to include the same/newer SDKs.

**Comment by moswald** [comment]
You should also consider using the newer `Hosted 2019` pool.

**Comment by moswald** [comment]
@coderlife14 Is this still an issue? Did you try using `Hosted 2019` instead?
