### ISSUE TITLE
Publish code coverage task not able to load coverage data from cobertura.xml

### ISSUE THREAD

**Issue by michaelmdeng** [Microsoft/azure-pipelines-tasks#10149]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Publish Code Coverage

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        Account: Office
        Team Project: OneNote

- Agent - Hosted or Private: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: Linux 

## Issue Description

Not sure if this is a dupe of [Issue 9865](https://github.com/Microsoft/azure-pipelines-tasks/issues/9865) or not...

Publish code coverage task is not reading the cobertura.xml file I have generated. I am generating code coverage for my Scala project using scoverage in a cobertura-compatible format.

The task uploads the file, but issues the warning:

##[warning]No coverage data found. Check the build errors/warnings for more details.

Here is the attached cobertura.xml file (with format renamed):

[cobertura.xml.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/3091295/cobertura.xml.txt)

From the xml itself, it looks like the xml is using the expected http://cobertura.sourceforge.net/xml/coverage-04.dtd schema.

### Task logs

And here are the debug logs from the specific Publish Coverage task:

[log_14_1978394.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3091293/log_14_1978394.zip)

**Comment by IOrlandoni** [comment]
Try setting a build variable called `disable.coverage.autogenerate` to `true`. They introduced some breaking changes to the task in a non-backwards compatible way. 

More info here: #10094, #9704 & #9962.

**Comment by michaelmdeng** [comment]
Works now, thank you!
