### ISSUE TITLE
Nuget task tries to push .snupkg packages twice

### ISSUE THREAD

**Issue by trwalke** [microsoft/azure-pipelines-tasks#10140]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGet

## Environment
account name: trwalke, 
team project name: Identity Division IDDP (https://identitydivision.visualstudio.com/IDDP)
 build definition name/build number: .NET MSAL V3 Release/ [release Id=13717](https://identitydivision.visualstudio.com/IDDP/_releaseProgress?_a=release-pipeline-progress&releaseId=13717)

- Agent - Hosted or Private: 
    - Hosted agent on "Hosted VS2017"

## Issue Description

We are trying to us the nuget task to push our nuget packages and symbols via the .snupkg. The task is able to successfully upload the .nupkg and the .snupkg packages. However, it tries to upload the .snupkg again after it has already been uploaded resulting in an error. 
We are using nuget version 5.0.0.5923 via the nuget tool installer.

We are simply pointing the nuget task to a folder that contains both .nupkg and the .snupkg packages
### Task logs

[ReleaseLogs_13717.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3086852/ReleaseLogs_13717.zip)

"Nuget Push" logs

### Error logs

> The nuget command failed with exit code(1) and error(Response status code does not indicate success: 409 (It looks like there is another copy of this symbols package pending validation(s). Please wait for the validation(s) to finish before trying to replace the symbols package.).)

**Comment by trwalke** [comment]
The task documentation says we can use the "Index Sources & Publish Symbols task" for pushing symbols but that task doesnt seem to support .snupkgs.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops

**Comment by trwalke** [comment]
any updates on this?

**Comment by salvmd** [comment]
Apologies for the slow response. Please try excluding the .snupkg file using the search pattern in the task input (the field called "Path to NuGet package(s) to publish"). From the logs, it looks like you are setting it to "C:\Nuget\*.*nupkg", which will also match .snupkg files; please try removing the second wildcard character. The .snupkg is already automatically pushed by nuget.exe when the .nupkg is pushed; this behavior is mentioned in the [third item in these docs](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package).

The task runs nuget.exe push on every file matched by the search pattern. In this case, what's happening is that it's matching both files, running nuget.exe push on the .nupkg (which will also upload the .snupkg), then running it on the .snupkg, and failing.
