### ISSUE TITLE
VSTest should retain TestResults or give an option not to publish

### ISSUE THREAD

**Issue by puttagunta** [Microsoft/azure-pipelines-tasks#10157]
**Feature**  
*Type*: VSTest 2.* is removing the TestResults folder after publishing the results. This is inhibiting the option of using trx files in the subsequent tasks.

**Task Name**: VSTest 2.*

- Agent - Private:
    - Microsoft Windows Server 2016
    - Agent version: 2.149.2

## Issue Description
We have a stage in release that runs Integration Tests. We have tasks following the VSTest task to use .trx files generated out of the vs test task. Because the Test Results folder getting deleted, we cannot get those files. It would be helpful to give the task user, the control whether to publish test results or not? or not deleting test results as part of the task execution.

**Comment by kaadhina** [comment]
Hi, thank you for the feedback.
Reusing the trx from the results directory in agent is not something the task supports and not planned for future either.
If the file needs to be used by a subsequent task, you will have to download from server from test run attachments.
