### ISSUE TITLE
Cannot use the CopyFilesOverSSH task to deploy to Solaris 11

### ISSUE THREAD

**Issue by egoicovici** [microsoft/azure-pipelines-tasks#10175]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CopyFilesOverSSH

## Environment
- Server - Azure Pipelines

- Agent - Private running on Windows OS, agent version 2.148.1

## Issue Description

I cannot use the **Copy Files over SSH** Azure DevOps task inside a release pipeline to deploy artifacts to Solaris 11.4 servers via SSH. I have successfully used this Azure DevOps task to deploy files to Solaris 10. But when using it against Solaris 11, the task freezes indefinitely without any debug information (when System.Debug variable is set to true inside the release pipeline).

After further investigations on this issue, it seems that this problem occurs only when SSH server identifies itself with a banner string that ends with whitespaces. This problem has been fixed in [this commit](https://github.com/mscdex/ssh2-streams/commit/09c5884eccd702eb0723b319966c8018d9e06fde) inside the ssh2-streams javascript library on which the Copy Files Over SSH task depends to. This changeset has been incorporated in **ssh2-streams v0.1.20** .  But the Copy Files Over SSH Azure DevOps task currently uses [scp2](https://github.com/spmjs/node-scp2) version 0.5.0 which depends on [ssh2](https://github.com/mscdex/ssh2) version 0.5.4 which uses ssh2-streams version 0.1.15, therefore this bug is present.

The [scp2](https://github.com/spmjs/node-scp2) javascript library is not actively maintained thus there were no recent releases, but if you take a look on its repository, its dependency to the **ssh2** library has been updated from version 0.5.4 to version 0.6.0, and the **ssh2 v0.6.0** depends on **ssh2-streams v0.2.0** , thus includes the bugfix for the problem described above.

On the other hand the **[SSH Deployment Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops)** depends on ssh2 v0.8.2 javascript library, thus I can successfully use this Azure DevOps task to remotely run commands on a given Solaris 11.4 server. Thus the reported problem occurs only for the **Copy Files Over SSH** task.

**Comment by egoicovici** [comment]
The SSH server used is OpenSSH v7.5, which is the default version that come with Solaris 11.4, thus this bug can be reproduced by connecting via SSH to any Solaris 11.4 server.

**Comment by stephenmichaelf** [comment]
There is a PR out to address this here: https://github.com/microsoft/azure-pipelines-tasks/pull/11488
