### ISSUE TITLE
Parallel jobs inside stage

### ISSUE THREAD

**Issue by ladislas** [microsoft/azure-pipelines-tasks#10186]
Hi there! 

Is it possible to parallelize `jobs` inside a `stage`?

Thanks a lot!
Best,  
-- Ladislas

**Comment by ladislas** [comment]
anyone?

**Comment by ArieHein** [comment]
yes, on the agent bar, under execution plan. use multi-configuration, and under multipliers use a comma-separated list. I just create a variable, put the list in its value, and then in the tasks within the job, I call the variable, it will be replaced by the values in the list for every execution.

I do recommend setting a limit as to the number of agents to use , so say your list has 4 items, the number of agents will dictate the number of executions at the same time.

**Comment by ladislas** [comment]
thanks @ArieHein 

I was able to achieve it by using `dependsOn: []` for my `job`.
