### ISSUE TITLE
Why test assemblies are not filtering in VSTS azure build pipeline despite putting test assembly patterns?

### ISSUE THREAD

**Issue by deepakmhr** [microsoft/azure-pipelines-tasks#10189]
Here are my test assembly patterns (configuration)

```
**\$(BuildConfiguration)\*test*.dll
!**\obj\**  
!**\$(BuildConfiguration)\*Integration*
```

After triggering the build, here is the log where integration test assembly is also there (this file must be filtered and should be here)

```
2019-04-23T13:10:33.6689787Z C:\VSTSAgent\A1\_work\1\s\myapp\myapp.Services.Test\bin\Release\myapp.Services.Test.dll
2019-04-23T13:10:33.6690018Z C:\VSTSAgent\A1\_work\1\s\myapp\myapp.Services.Integration.Test\bin\Release\myapp.Services.Integration.Test.dll
```

Because of this integration test cases are also running and I want to run only unit test cases
**Enter Task Name**: Visual Studio Test

## Environment
- Server - Azure Pipelines

**Comment by prawalagarwal** [comment]
@deepakmhr can you attach complete logs with system.debug set as true in your build?

**Comment by deepakmhr** [comment]
I've found the solution and posted the same here
https://stackoverflow.com/questions/55814336/why-test-assemblies-are-not-filtering-in-vsts-azure-build-pipeline-despite-putti/55860340#55860340
