### ISSUE TITLE
Publish Code Coverage Results task is not copying HTML files to report artifact

### ISSUE THREAD

**Issue by EricAlvarez292** [microsoft/azure-pipelines-tasks#10191]
## Issue Description
Re-creating this issue [9389](https://github.com/Microsoft/azure-pipelines-tasks/issues/9389)
*Type*: Bug
[PublishCodeCoverageResultsV1](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1)
## Environment
Hosted macOS High Sierra
## Issue Description
Publish Code Coverage Results task is not copying HTML files to report artifact
### Task logs
Previous version 1.148.0 (success):
[success-published.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/3110439/success-published.txt)

After update to 1.150.3 (failed):
[failed-published.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/3110441/failed-published.txt)

@karanjitsingh

**Comment by ruvyas** [comment]
Hi guys, any update on this issue? I am using Pester to publish JaCoCo format and it doesn't create any HTML/CSS/Js files.

This is the output I get from the task below: 

```##[section]Starting: PublishCodeCoverageResults
==============================================================================
Task         : Publish Code Coverage Results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.151.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=626485)
==============================================================================
Reading code coverage summary from 'd:\a\1\s\build\.logs\1.0.2726branch.jacoco.xml'
##[section]Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Instruction- 121 of 477 covered.
 Line- 88 of 359 covered.
 Method- 14 of 41 covered.
 Class- 2 of 4 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 3 files
File upload succeed.
Published 'd:\a\1\s\build\.logs' as artifact 'Code Coverage Report_72726'
##[section]Async Command End: Publish code coverage
##[section]Finishing: PublishCodeCoverageResults

**Comment by rdjaxn** [comment]
I am having a similar issue with a PowerShell project using the Pester task to generate code coverage in JaCoCo format.

When I use JaCoCo as the codeCoverageTool property, I get the same results as @ruvyas above. If I switch to use cobertura, it generates the html and associated files in the Artifacts folder, but is not published.

In the log I get the following Warnings when using Cobertura:

 File 'Invoke-MainProcess.psm1' does not exist (any more).
  Writing report file 'Templates_s_Templates_Invoke_MainProcess.htm'
 Creating summary
  Writing report file 'd:\a\_temp\cchtml\index.htm'
Report generation took 0.8 seconds
Generated code coverage html report: d:\a\_temp\cchtml
**##[warning]Ignoring coverage report directory with Html content as we are auto-generating Html content**
Reading code coverage summary from 'd:\a\1\s\Tests\CodeCoverage_DEVBuild.91.xml'
**##[warning]No coverage data found. Check the build errors/warnings for more details.**
##[section]Async Command Start: Publish code coverage
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 30 files
File upload succeed.
Published 'd:\a\_temp\cchtml' as artifact 'Code Coverage Report_91'
##[section]Async Command End: Publish code coverage
##[section]Finishing: Publish Code Coverage

**Comment by karanjitsingh** [comment]
@ruvyas, @rdjaxn this is a known issue in publish code coverage for jacoco. We've identified the problem and working on a fix.

**Comment by chaholl** [comment]
Still seeing this problem in 1.155:
```

============================================================================== |  
-- | --
  | Task         : Publish code coverage results |  
  | Description  : Publish Cobertura or JaCoCo code coverage results from a build |  
  | Version      : 1.155.0 |  
  | Author       : Microsoft Corporation |  
  | Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results |  
  | ============================================================================== |  
  | Reading code coverage summary from '/home/vsts/work/1/s/target/site/jacoco/jacoco.xml' |  
  | Async Command Start: Publish code coverage |  
  | Publishing coverage summary data to TFS server. |  
  | Instruction- 1667 of 3026 covered. |  
  | Branch- 74 of 182 covered. |  
  | Line- 350 of 492 covered. |  
  | Complexity- 142 of 326 covered. |  
  | Method- 117 of 235 covered. |  
  | Class- 26 of 29 covered. |  
  | Modifying Cobertura Index file |  
  | Publishing code coverage files to TFS server. |  
  | Uploading 1 files |  
  | File upload succeed. |  
  | Published '/tmp/Code Coverage Report_128472' as artifact 'Code Coverage Report_128472'

```
Any updates or workaround?

**Comment by ZClifton-21** [comment]
It is still the same at the current moment and no workarounds have been found yet.

**Comment by gabriel-a** [comment]
Could you try to add pathToSources? I had the same problem running pester test with jaCoCo code coverage.
This solved the issue in the publish yml:
` - task: PublishCodeCoverageResults@1
        inputs:
            codeCoverageTool: 'jaCoCo'
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/Tests/JaCoCoCodeCoverage.xml'
            pathToSources: '$(System.DefaultWorkingDirectory)'
            failIfCoverageEmpty: false`

As for pester test:
`
Write-Output "Calling Pester test script $TestScript"
$outCoverageFile = "$PSScriptRoot\JaCoCoCodeCoverage.xml";
$outFile = "$PSScriptRoot\TEST-Pester.xml"

$RootFolder = "$PSScriptRoot\.."
Write-Output "RootFolder $RootFolder"
$NotTestFiles = Get-ChildItem -Path $RootFolder -include *.ps1, *.psm1 -Exclude *.Tests.ps1 -Recurse |
        Select-object -ExpandProperty Fullname
Write-Output "Files included in CodeCoverage $NotTestFiles"

$result = Invoke-Pester -Script $RootFolder -CodeCoverage $NotTestFiles -CodeCoverageOutputFile $outCoverageFile -OutputFile $outFile -OutputFormat NUnitXml -PassThru
if ($result.failedCount -ne 0) {
    Write-Error "Pester returned errors"
}
`

Also make sure you have the latest Pester installed in the modules. This did allow the code coverage to be visible on Azure devops.

**Comment by pgeschwill** [comment]
@gabriel-a 

I can confirm that adding the pathToSources input in the yml solved the issue on my end.

However, I found it pretty confusing that the ReportGenerator only runs if the path is specified. It would be nice to have more descriptive log output from Azure DevOps.

**Comment by nishantms** [comment]
Requirement to specify the source path, if the format is jacoco, is already clarified, in the input variable description.
![PCCv1](https://user-images.githubusercontent.com/63423133/86007157-a5be4f80-ba34-11ea-9bf0-654d28c0c407.PNG)

If there is still some issue , please feel to comment on this issue.
