### ISSUE TITLE
Facing error wile deploying "SQL Server Database Deploy" task in release pipeline.

### ISSUE THREAD

**Issue by nikbhadane** [microsoft/azure-pipelines-tasks#10195]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SQL Server Database Deploy 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlDacpacDeploymentOnMachineGroupV0/README.md

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
Using the 'SQL Server Database Deploy' we are deploying the database schema. In sql file section it is mentioned that "Wildcards can be used. For example, **/*.sql for sql file present in all sub folders.". 
The same wildcard we have used in sql file section i.e "**/*.sql" but it is throwing error like.
"##[error]Exception calling "GetDirectoryName" with "1" argument(s): "The path is not of a legal form."" 
[Insert error from the logs here for a quick overview]

**Comment by Ajay-MS** [comment]
@nikbhadane 

I have tried out task with following regex for the path
```
E:/TaskResources/SQL/temp/*.sql
```
or
```
E:\TaskResources\SQL\temp\*.sql
```

I have following observations: 
#### Single file matching regex present at the provided location
Task runs successfully.

#### Multiple file matching regex present at the provided location
Then task fails with following error: 
```
Found more than one file to deploy with search pattern E:\TaskResources\SQL\temp\*.sql. There can be only one.
```

#### No file matching regex present at the provided location
```
No files were found to deploy with search pattern E:\TaskResources\SQL\temp\*.sql
```

Can you please share complete logs so that I can understand your scenario and figure out the cause of the failure.

**Comment by nikbhadane** [comment]
Hey @Ajay-MS,
Consider the condition, what if I want to execute multiple SQL files.
As per task details they have mentioned **"Wildcards can be used. For example,** ** **/*.sql for SQL file present in all subfolders."**
I am looking for the solution to execute SQL files as per above their comment.
And yes I am also getting the same error.
` Found more than one file to deploy with search pattern`

And thanks for the reply.

**Comment by olivesandtrees** [comment]
I realize that this is closed, but I didn't see a good response to @nikbhadane .  Are wild cards not supported if there are multiple SQL scripts in the same folder?  It would be nice to be able to deploy multiple SQL scripts in the same folder without listing the path of each script separately.

**Comment by preeti-mahajan** [comment]
The wildcard "** /*.sql" does not work, but prefixing the regex with the location of working directory or simply putting "$(System.DefaultWorkingDirectory)\**\*.sql" executes the sql command in the order how the scripts are packaged.

**Comment by mbellas-tkxs** [comment]
Same issue, this would be nice to have.
