### ISSUE TITLE
Publish code coverage not shown for Jacoco

### ISSUE THREAD

**Issue by guillermomartinez-accenture** [microsoft/azure-pipelines-tasks#10205]
I want to Publish my Jacoco code coverage in TFS with the plugin Publish Code Coverage Results.

This functionality was working correctly, but since short time ago it's not working anymore.
When going to Code Coverage tab on the build it shows the message: "Code coverage report cannot be rendered as report HTML was not found. Please verify that “Report Directory” containing an HTML report was specified when publishing code coverage."

I'm specifying the .xml file, the .html, and the .exec. But the code coverage is not reflected in that tab (although the build recognises the % of covered code).

**Comment by karanjitsingh** [comment]
@guillermomartinez-accenture, could you provide your build logs for us to investigate?

**Comment by guillermomartinez-accenture** [comment]
Hi @karanjitsingh, the plugin log seems to be correct
[8.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3201558/8.txt)
but when I go to the Code Coverage tab I got the message: 
> "Code coverage report cannot be rendered as report HTML was not found. Please verify that "Report Directory" containing an HTML report was specified when publishing code coverage."

The Jacoco report is created properly, and with previous plugin version it was reported correctly.

**Comment by ShreyasRmsft** [comment]
@guillermomartinez-accenture are you still facing this issue?

**Comment by ShreyasRmsft** [comment]
Please let us know and we will re-open this.
