### ISSUE TITLE
DotNetCoreInstaller uses a deprecated releases.json and can't install .NET Core 3.0 Preview 4

### ISSUE THREAD

**Issue by dagood** [Microsoft/azure-pipelines-tasks#10213]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: DotNetCoreInstaller

## Environment

Unknown

## Issue Description

I'm filing this issue on @minhhieugma's behalf based on https://github.com/dotnet/core/issues/2632.

> Could not fetch download information for version 3.0.100-preview4 in Devops CI
> 
> ![image](https://user-images.githubusercontent.com/9654744/56648875-489b7100-66ae-11e9-8388-85b3257a6891.png)

This appears to be caused by the task using a deprecated file:

https://github.com/Microsoft/azure-pipelines-tasks/blob/e239620b93b1d2c6339893cc86b0d51d6bf2ee88/Tasks/DotNetCoreInstallerV0/releasesfetcher.ts#L148

Announcement post about deprecation: https://github.com/dotnet/announcements/issues/87, discussion: https://github.com/dotnet/core/issues/1986.

More context in https://github.com/dotnet/core/issues/2632.

### Task logs

Unfortunately I only have the screenshot.
`##[error]Failed to download package for installation`

**Comment by anuragc617** [comment]
@dagood We have rolled out the newer version of dotNetCore SDK Installer task i.e 2.*(preview). It uses https://github.com/dotnet/core/blob/master/release-notes/releases-index.json to get all the releases. You can use this task to install dotNetCore SDK. In this task, if you specify the version as 2.x it will install the latest version of the channel excluding preview versions, to include the preview versions check Include Preview Versions.

**Comment by anuragc617** [comment]
Closing it, for now, feel free to open if you find any issue.

**Comment by dagood** [comment]
> It uses https://github.com/dotnet/core/blob/master/release-notes/releases-index.json to get all the releases.

If so, that's a bug--that endpoint is out of date. It doesn't include 3.0 Preview 5. https://github.com/dotnet/announcements/issues/87

I don't have permissions to reopen.

**Comment by dagood** [comment]
Reopened as https://github.com/Microsoft/azure-pipelines-tasks/issues/10260.
