### ISSUE TITLE
JSON parsing error on Windows Agent based on value of PackerBuild task Template parameters

### ISSUE THREAD

**Issue by maniSbindra** [Microsoft/azure-pipelines-tasks#10224]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PackerBuild  

## Environment
- Azure Pipelines?
    

- Agent - Both Hosted and Private Windows Agents

## Issue Description
On Windows Agents, In the Packer Build task when passing Template parameters (Custom Packer Template) which include a file path like $(build.artifactstagingdirectory), An error regarding JSON Parsing is thrown.

Sample Template Parameters
```
{
    "image_name": "$(MANAGED_IMAGE_NAME_PREFIX)-$(Build.BuildNumber)",
    "packagepath": "$(build.artifactstagingdirectory)" ,
    "resource_group": "$(RESOURCEGROUP)",
    "location": "$(LOCATION)"
}
```
 
Error 
```
Parsing custom template parameters json.
##[error]Error happened while initializing task: SyntaxError: Unexpected token a in JSON at position 333.
```

On Hosted and Private Ubuntu Agents no error is thrown. 

To work around this on windows agents we need to replace back slash with double back slash as shown in the powershell script below, after which the task works fine
```
$mpath = $env:BUILD_ARTIFACTSTAGINGDIRECTORY -replace "\\","\\\\"
```

### Task logs

```
Parsing custom template parameters json.
##[error]Error happened while initializing task: SyntaxError: Unexpected token a in JSON at position 333.
```

**Comment by anuragc617** [comment]
Hi @maniSbindra, this is expected behavior as per the design of the task. For special characters, the user has to escape them by using the escape character('\). We can't do much here.

**Comment by maniSbindra** [comment]
Thanks. However this works fine on Ubuntu Agent. Since the behaviour differs on the windows agent as compared to the Ubuntu agent can this be added to tooltip.
