### ISSUE TITLE
Update Npm to use latest node-api

### ISSUE THREAD

**Issue by stephenmichaelf** [microsoft/azure-pipelines-tasks#10222]
The npm task has had some intermittent failures calling in to the location service:

##[error]Error: Error: Failed to find api location for area: npm id: D9B75B07-F1D9-4A67-AAA6-A4D9E66B3352

I think this is due to networking issues.

We added resiliency to the azure-devops-node-api when calling the location service to allow retries. This is in 7.2.0.

It looks like this is being called through packaging-common from what I can tell so the update should be to update the dependency in the common module. We will then have to update all tasks that depend on packaging-common.

It looks like it's also safe to remove the vso-node-api reference in package.json

**Comment by stephenmichaelf** [comment]
@zjrunner @jotaylo Could you take care of this? Thanks!

**Comment by zjrunner** [comment]
Tracked in AZDEVOPS #1486640

**Comment by aasim** [comment]
Fixed and deployed to production.
