### ISSUE TITLE
On Windows Agents AZ CLI task executes only the first az command in an inline script

### ISSUE THREAD

**Issue by maniSbindra** [Microsoft/azure-pipelines-tasks#10223]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure CLI (1.150.0)

## Environment
- Azure Pipelines

- Agent - Hosted or Private: 
    
    - Hosted Windows (VS 2017) Agents and Private Windows Agents

    - Windows Server Data Center version: (2019) 

## Issue Description

On Windows Agents AZ CLI task executes only the first az command in an inline script. Consider the following AZ CLI Task inline script
```
echo "0##"
az -h
echo "1##"
az -h
echo "2##"
az -h
echo "3##"
```

On the Windows Agents after the first az command none of the echo or az commands are executed, so only output of first echo and az command are visible in the logs. On Hosted and Private Ubuntu Agents outputs of all the 4 echo statements and az commands are visible.

### Task logs

[Windows-Agent_logs.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/3116900/Windows-Agent_logs.txt)
[Linux-Agent-Logs.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/3116899/Linux-Agent-Logs.txt)

**Comment by anuragc617** [comment]
On windows, you have to add "call" in the beginning of the az commands. Ex:- "call az ...", can you try this?

**Comment by anuragc617** [comment]
Closing this, feel free to open if you find any issue.

**Comment by maniSbindra** [comment]
Thanks. Since the behaviour differs on the windows agent as compared to the Ubuntu agent can this be added to tooltip.

**Comment by sachinma** [comment]
@maniSbindra this looks like a good suggestion. Reopening the issue to track it

**Comment by anuragc617** [comment]
@maniSbindra The usage has already been explained in the task helpMarkDown. See image.
![image](https://user-images.githubusercontent.com/44864882/57125974-0a3a3c00-6da9-11e9-97b2-2e06f94c38c1.png)

**Comment by maniSbindra** [comment]
Thank you, this is good. I am closing the issue.
