### ISSUE TITLE
Azure ClI not finding `az` with self hosted agent(Ubuntu)

### ISSUE THREAD

**Issue by Srikanthshetty** [Microsoft/azure-pipelines-tasks#10232]
**Bug**  
When using Azure CLI for AZ acr command giving following error
" Script failed with error: Error: Failed which: Not found azure: null"

**Task Name**: Azure CLI  

## Environment
- Server - Azure DevOps using self hosted Agent running in Azure VM 
Azure Devops Account Name : https://dev.azure.com/HdproServices
Project Name : One Process Inventory
Build Name : AKS_PL
Build Number : 20190425.49
- Agent -  Private Agent: 
    
OS : Ubuntu 18
 

## Issue Description

Azure CLI task giving the following error 
Using Azure Resource manager as service connection , it is working fine for  docker build and push.

![Error](https://user-images.githubusercontent.com/19268128/56770090-19096900-6781-11e9-964c-2b9e563aca2b.PNG)

Logs :
[logs_106.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3118986/logs_106.zip)

**Comment by anuragc617** [comment]
@Srikanthshetty This task expects az to be installed on the agent machine. The error indicates that az is not present on the machine. Can you first install the Azure CLI on your machine and try again?

**Comment by anuragc617** [comment]
Closing this issue, feel free to open if not resolved.

**Comment by Srikanthshetty** [comment]
Hi Anurag, i installed azure cli in the hosted agent following is the Azure CLI version

azure-cli                         2.0.63

Still i am getting same error.

**Comment by anuragc617** [comment]
Can you run the task with system.debug=true and share the logs? Also, what is the command that you are running in Azure CLI task ?

**Comment by Srikanthshetty** [comment]
Hi Anurag , 

Restart Host agent server did resolve the issue.

**Comment by mavrick202** [comment]
Wonderfull...!!! Restart fixed it..!!:)
