### ISSUE TITLE
Why would i use an agentless job

### ISSUE THREAD

**Issue by akash3456** [microsoft/azure-pipelines-tasks#10246]
in the visual designer there is an option to use a agentless job why would i use this feature in what given context would be great please? 

Thanks

**Comment by joshmgross** [comment]
@akash3456 This page might give some information: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/server-phases?view=azure-devops&tabs=yaml

**Comment by bansalaseem** [comment]
It is very useful for tasks which dont require any compute. For example: - manual intervention task.

**Comment by acds** [comment]
@joshmgross your link above is broken...

**Comment by joshmgross** [comment]
@acds I've updated the link to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#server-jobs

**Comment by andrewducker** [comment]
Are "agentless jobs" the same as "server jobs"?  It's not clear from the documentation.  If they are, then maybe the UI should say "server jobs"?
