### ISSUE TITLE
DockerCompose build-arg

### ISSUE THREAD

**Issue by nesherhh** [microsoft/azure-pipelines-tasks#10240]
How do I pass build-arg in DockerCompose Task?

**Comment by dabasnidhi** [comment]
You can pass the build arguments for docker compose command in the following format-
build --build-arg key-value. (Refer to [link](https://docs.docker.com/compose/reference/build/))
Example as in picture below-
![image](https://user-images.githubusercontent.com/12389221/58471876-86366280-8162-11e9-9ab9-302c058776d7.png)
