### ISSUE TITLE
lerna bootstrapping fails with npm task due to invalid registry url when using azure artifacts

### ISSUE THREAD

**Issue by jbockle** [microsoft/azure-pipelines-tasks#10242]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NPM

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  ** omitted due to company policy **

- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version:  ** windows server 2012 r2

## Issue Description

Using the npm task with Azure Artifacts private registry (registry selected by choosing 'Registry I select here' from task options).  When using a monorepo with lerna, lerna has a bootstrapping task that runs npm install task for each package-however on build agents, it automatically uses npm ci instead.  npm ci reads package-lock.json or npm-shrinkwrap.json instead of package.json.  The registry url specified by the task points to it's id (guid), instead of the name which the Azure Artifacts instructs end-users to use.  This results in lerna bootstrapping to fail in my case.  If I update the .npmrc to use the id with guid and run lerna clean then lerna bootstrap locally to update the package-lock.json 'resolved' properties, the build succeeds since the registry url matches.

### Task logs

** logs omitted due to company policy **

**Comment by aasim** [comment]
Hi @jbockle - Are you still experiencing this issue? We have deployed fixes to this code since June, where we preserve the user's selection of Guid or names. Can you retry your pipeline and let me know if this is working as expected. If not, let us know here and we can diagnose this issue further.

**Comment by abelkbil** [comment]
i do see the same issue

**Comment by jbockle** [comment]
i just tested and it is working fine for me now

```
##[section]Starting: Npm
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.158.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
[command]/usr/local/bin/npm --version
6.12.0
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
[command]/usr/local/bin/npm config list
; cli configs
metrics-registry = "https://pkgs.dev.azure.com/jbockle/_packaging/test/npm/registry/"
scope = ""
user-agent = "npm/6.12.0 node/v12.13.0 linux x64"

; environment configs
userconfig = "/home/vsts/work/1/npm/30.npmrc"

; project config /home/vsts/work/1/s/.npmrc
always-auth = true
registry = "https://pkgs.dev.azure.com/jbockle/_packaging/test/npm/registry/"

; userconfig /home/vsts/work/1/npm/30.npmrc

; node bin location = /usr/local/bin/node
; cwd = /home/vsts/work/1/s
; HOME = /home/vsts
; "npm config ls -l" to show all defaults.

[command]/usr/local/bin/npm run bootstrap

> root@ bootstrap /home/vsts/work/1/s
lerna notice cli v3.19.0
> lerna bootstrap

lerna info ci enabled
lerna info Bootstrapping 1 package
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 1 package
```
