### ISSUE TITLE
Azure DevOps - Not able to run an inline Powershell in "Azure App Service Deploy's" post deployment action

### ISSUE THREAD

**Issue by nikhil2007rock** [microsoft/azure-pipelines-tasks#10247]
I am looking to rename a file after deploying a package to the Azure Website. To do so, I understand that while deploying into an Azure Web app using the "Azure App Service Deploy" task, it has a Post Deployment action with which we can run an inline script that will execute on the app service itself - https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4

I've tried to execute a simple copy powershell command and it throws an error

> [error]Error: EISDIR: illegal operation on a directory, read

Copy commands that I've tried :
```
Copy-Item ".\config\config.js" ".\config\<websiteName>.js" -Force
```

**Comment by vincentdass** [comment]
@nikhil2007rock , thanks for reaching out.
I assume the deployment is done using `Run From Package` method. Can you verify if there is an app setting `WEBSITE_RUN_FROM_PACKAGE` set to value `1` for the web app?

If so, try changing the deployment mechanism to `Zip Deploy`
![image](https://user-images.githubusercontent.com/20121508/56876593-29ae2d80-6a66-11e9-8e89-cee170d364c1.png)

**Comment by nikhil2007rock** [comment]
@vincentdass  : The `WEBSITE_RUN_FROM_PACKAGE` is set to `1`. Next, the "Select deployment method" was unchecked previously. I've changed it to explicitly use Zip deploy method and tried. I get the same error.

![image](https://user-images.githubusercontent.com/5222165/56877390-46992f80-6a6b-11e9-99d2-64533dfcaa72.png)

**Comment by vincentdass** [comment]
@nikhil2007rock , Can you use `xcopy` command to copy the file instead of PowerShell commandlet?

**Comment by nikhil2007rock** [comment]
@vincentdass, I tried to not use Powershell and so to serve my original purpose, I used the below command to rename the deployed file and still I get the same error. Actually, I would want to use the value saved in the library (key : AppURLForAppJS) associated to this release stage I am trying to deploy to.

`ren ".\config\config.js" "rm.js"`

**Comment by vincentdass** [comment]
@nikhil2007rock , Can you please share the release logs to `RM_CUSTOMER_QUERIES [at] Microsoft [dot] com`?

**Comment by nikhil2007rock** [comment]
@vincentdass : Sent! I've mentioned the issue ID in the subject.

**Comment by nikhil2007rock** [comment]
@vincentdass , thanks for solving this for me. The problem was with the File transformation step.

**Comment by vincentdass** [comment]
@nikhil2007rock , glad to know you are unblocked :)
