### ISSUE TITLE
[SF update manifest task] It should be possible to choose a branch while comparing version against previous build

### ISSUE THREAD

**Issue by bishal-pdMSFT** [microsoft/azure-pipelines-tasks#10253]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Feature

**Enter Task Name**: Service fabric update manifest task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Both

- Agent - Hosted or Private: 
    
Both

## Issue Description

Update manifest task compares current package files against package for last successful build. But a build can be triggered for more than one branch and hence in such cases, we might be comparing against a build with a different baseline.
It would be better to add support for specifying branch to detect previous build. More details in this [thread](https://github.com/Microsoft/azure-pipelines-tasks/issues/7549#issuecomment-440150544)

**Comment by narcis-pv** [comment]
There is also another possible conflict of names when having the “download artifact” set to false.

The agent temp folder used and it is shared between build and release definitions.

I suggest the PkgArtifactName in temp folder should be composed of:

BuildDefinitionName_BranchName_ArtifactName.zip

Change would be in Get-VstsBuild.psm1 around line 70.
