### ISSUE TITLE
Azure Powershell - support AZ CLI without having to pass credentials for az login

### ISSUE THREAD

**Issue by jkewley** [microsoft/azure-pipelines-tasks#10263]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Azure Powershell

## Environment
- Server - Azure Pipelines 
- Agent - Hosted 

## Issue Description

I am using the Powershell task to build out large server environments based on parameterized source files. I chose Powershell to do the heavy lifting of building out hashtables containing server and environmental names which follow our naming stnadards, but I was asked to use the Azure CLI to do the actual deployment. Because of this I need to provide service principal information as parameters to the PS task so I can call `az login` when I'm ready to deploy.

It would be nice to have the CLI connection pre-authenticated with the service connection credentials to make my task more secure, especially since the CLI task currently only supports batch files.

I could generate a batch file from within Powershell, but I have looping logic written in PS that looks for active deployments in a resource group to avoid deployment clashes, and that logic is written in Powershell.

Thanks for the consideration.

**Comment by paulirwin** [comment]
Or an alternative, allow the Azure CLI task to use Powershell instead of batch scripts.

**Comment by nshenoy** [comment]
Having the Azure CLI task support Powershell would be hugely beneficial. I prefer using the azure-cli over Powershell's Az Cmdlets, but I would love to use Powershell scripting semantics for parameterization and parsing/manipulation of azure-cli output results.

**Comment by adamrushuk** [comment]
This feature would be awesome. Learning Batch/CMD scripting in 2019 is frustrating.

**Comment by sebastianrogers** [comment]
Absolutely, writing I'm using my father's bash manuals written in 1992, and its painful.

**Comment by bishal-pdMSFT** [comment]
Az CLI @2 version task support PS and PS core scripts. Do try it out.
