### ISSUE TITLE
New version of use dotnet breaks the build

### ISSUE THREAD

**Issue by Barsonax** [Microsoft/azure-pipelines-tasks#10261]
Use dotnet 2.0.2 is breaking my build:
https://dev.azure.com/Barsonax/Singularity/_build/results?buildId=160

It was working fine before with 2.0.0:
https://dev.azure.com/Barsonax/Singularity/_build/results?buildId=159

I suspect some paths were changed. You can see this if you go to line 26 of the NUKE build task. The NUKE build is still working fine locally.

**Comment by anuragc617** [comment]
Hi @Barsonax, we have updated the path where we install the dotNet to support some features, we are also updating the system PATH environment variable. But we would really want to understand how it is impacting your build, what dependency the NUKE build task has on the dotNet PATH. Ideally, you should not have any dependency on the dotNet installation path. If you really looking for a workaround, then you can use the older version 0.* of "use dotnet" task it still uses the old path.

**Comment by Barsonax** [comment]
Thanks for the workaround. Iam gonna test it.

Indeed if tooling is not supposed to depend on the path ike that it might be a bug in NUKE.

**Comment by anuragc617** [comment]
@Barsonax The name of the task to use is "DotNetCoreInstallerV0".

**Comment by Barsonax** [comment]
Seems to fix it: https://dev.azure.com/Barsonax/Singularity/_build/results?buildId=174

**Comment by anuragc617** [comment]
@Barsonax Thanks for confirming. I was thinking more about it, it may not be the issue with the Nuke build. Perhaps, Nuke build would also require an older version of dotNet Core. Can you please try the latest task "UseDotNetV2" with input "performMultiLevelLookup=true"? That should also work.

**Comment by Barsonax** [comment]
Jup that works as well: https://dev.azure.com/Barsonax/Singularity/_build/results?buildId=176

**Comment by anuragc617** [comment]
Thanks @Barsonax for trying the second solution as well, closing it.
