### ISSUE TITLE
Azure Powershell v4 - limited to v1.0.0 only?

### ISSUE THREAD

**Issue by LeeFramp** [Microsoft/azure-pipelines-tasks#10273]
I'm trying to use the below az.sql cmdlet in my Azure Powershell v4 task:
Get-AzSqlDatabaseBackupShortTermRetentionPolicy

The task fails because the cmdlet is not available:
"The term 'Get-AzSqlDatabaseBackupShortTermRetentionPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

If I run get-command in my local environment, this cmdlet is listed with version 1.9.0
If I run get-command within the Azure Powershell v4 task, this cmdlet is not listed, only v1.0.0.

Is it possible to update the az module to latest version in Azure Powershell task?

**Comment by 20shivangi** [comment]
@LeeFramp Are you using hosted agent or private agent to run the task?

**Comment by LeeFramp** [comment]
I'm using hosted agent and have tried VS2017 and VS2019 versions.

**Comment by 20shivangi** [comment]
version 1.6.0 is being rolled out. It will take two to three weeks to deployed.
