### ISSUE TITLE
AzurePowerShellV4 Cannot read property 'retrieveSecret' of undefined

### ISSUE THREAD

**Issue by toutougabi** [Microsoft/azure-pipelines-tasks#10280]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShellV4 version 4.0.5  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account : vt-dev
Project Name : visionintel
Build Number: 20190501.22

- Agent - Hosted or Private: 
    
    - Hosted Ubuntu 

## Issue Description

Yesterday Azure Pipeline was using AzurePowerShell version 4.0.3 which was working fine, during last night, the switch was made to 4.0.5 and now the AzurePowerShellV4 is completely broken with the following error : Cannot read property 'retrieveSecret' of undefined

### Task logs

Cannot read property 'retrieveSecret' of undefined

there are no other logs

**Comment by asranja** [comment]
We have hotfixed the issue in the version 4.0.6 of the task. Please redeploy your release to get the updated version of task.

**Comment by FrankTheTank9** [comment]
I confirm my new builds use 4.0.6 and this has fixed the issue.

Thanks

**Comment by zamzowd** [comment]
@asranja Could I ask what the fix for this was?  I'm getting the same logged failure on my new custom task.

**Comment by kmkumaran** [comment]
#10291 #10292 - Fixes for the issue.
@zamzowd  - the issue starting showing up as we moved to new version of tasklib. We have reverted it for now.
