### ISSUE TITLE
InstallSSHKey - "Permission denied (publickey)" after successfully installed ssh key

### ISSUE THREAD

**Issue by hieuhlc** [microsoft/azure-pipelines-tasks#10289]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: InstallSSHKey@0

## Environment
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: `Hosted Ubuntu 1604`

## Issue Description

After successfully installed ssh key, executing script to verify identity showed error: `Permission denied (publickey)` due to `no such identity: /home/vsts/.ssh/id_rsa: No such file or directory`

### Task logs
Successfully installed SSH key log:
[log_4_149.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3136818/log_4_149.zip)

Failed github identity verification `ssh -vvvT git@github.com` script log:
[log_8_149.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3136819/log_8_149.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

**Comment by yacaovsnc** [comment]
From the log, it says that the key is installed here:
2019-05-02T04:22:34.5758404Z ##[debug]Adding the SSH key to the agent /home/vsts/work/_temp/id_rsa

Since you are using a cmd task to run ssh, please use "-i" option to specify the key location.

**Comment by hieuhlc** [comment]
@yacaovsnc I want to add ssh key to the agent machine because my project has some dependencies in our private github repo. In that case I think I need to change ssh config `IdentityFile`. Is it possible?

**Comment by sbolotovms** [comment]
Any update on this one? I'm running into identical issues on following Microsoft hosted agents' platforms: `ubuntu 16.04` and `macOS 10.13`.
I tried running `find / -name id_rsa` command on both but it finds nothing. Neither `_temp` nor `.ssh` folders contain installed SSH key. Attached logs for `macOS-10.13` agent specification.
[log_4_24629006.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3557680/log_4_24629006.zip)
[log_9_24632200.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3557681/log_9_24632200.zip)

**Comment by sbolotovms** [comment]
@hieuhlc have you been able to find a workaround?
@yacaovsnc do you have any update on it?

**Comment by yacaovsnc** [comment]
@sbolotovms your `find` is not returning due to permission issues.  If you enable debug log, it should tell you where the file is installed to.  Then you should be able to specify that file with `-i` option from ssh?

**Comment by sbolotovms** [comment]
@yacaovsnc you can see from the log here that at the end of the task secure file is removed, not in post-execute of the task, thus rendering the key unusable.
[log_4_24655580.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3561283/log_4_24655580.zip)

**Comment by yacaovsnc** [comment]
Ah, I see @sbolotovms .  So the key isn't installed under `$HOME/.ssh`?  Can do you do a `ls -all` on `$HOME/.ssh`?

**Comment by sbolotovms** [comment]
@yacaovsnc yes, I've done `ls -a on ~/.ssh`, it only contains `known_hosts` file (in one of the logs above). `ls -a work/_temp` also yields no `id_rsa` nor `id_rsa.pub` files.

**Comment by yacaovsnc** [comment]
@sbolotovms sorry for sending you down the wrong path!  It seems like in order to secure the file, we never leave it on disk - instead we store it in the ssh-agent process, so there is no way for any task to steal the file.  

I just tried using that ssh private key to clone a private github repo, and was able to.  So it seems the key is installed correctly.  I had to make sure I properly added the public key and the known host entry.  

I followed this [answer](https://stackoverflow.com/a/13364116) to generate the `known_hosts` file.  After that, everything worked fine.

**Comment by yacaovsnc** [comment]
My task settings (showing partially for obvious reasons):
![image](https://user-images.githubusercontent.com/10119737/64051372-de597800-cb48-11e9-8022-9bc1c8bb5e47.png)

**Comment by sbolotovms** [comment]
Thanks a lot @yacaovsnc! I resolved the issue, turns out `Known Hosts Entry` only accepts one entry for this particular key. I tried to stuff 2 entries and it was processed incorrectly.
I wonder if @hieuhlc might have the same issue.

**Comment by yacaovsnc** [comment]
Not a bug.  Use one entry in known hosts entry per task.

**Comment by symbiogenesis** [comment]
I saw this error and it turned out that I needed to include a passphrase for the key.

Solved it by adding the **sshPassphrase** parameter to the InstallSSHKey task, and passing in the passphrase via a variable
