### ISSUE TITLE
customer logger does not work with Visual Studio Task

### ISSUE THREAD

**Issue by shenhong1000** [microsoft/azure-pipelines-tasks#10285]
I can execute below runner with runsettings containing customer logger without any issue. However when configuring in Visual Stuido Task (VS 2017), I think the logger dll is discovered/loaded properly (since It will throw "not found xxx..." if I don't drop the logger dll), however it does not executed after test execution completed.

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" Platform.Sdk.exe /Tests:Platform.Sdk.MultiSelectOptionSetSdkTests.VerifyCRUDonLocalMultiselectPickList /Settings:cds.runsettings

<RunSettings>
    <LoggerRunSettings>
        <Loggers>
            <Logger uri="logger://Microsoft/crm/cap/adxlogger/v1"
                    friendlyName="ADXLogger 1.0" />           
        </Loggers>
    </LoggerRunSettings>
</RunSettings>

https://dynamicscrm.visualstudio.com/OneCRM/_releaseProgress?_a=release-pipeline-progress&releaseId=925715

**Comment by karanjitsingh** [comment]
@shenhong1000 , distributed runs does not support other console options. You can specify your logger using run settings, https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0016-Loggers-Information-From-RunSettings.md#specifying-a-logger
