### ISSUE TITLE
NodeTool does not work on ARM 

### ISSUE THREAD

**Issue by timfish** [microsoft/azure-pipelines-tasks#10295]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NodeTool

## Environment
- Server - Azure Pipelines
- Agent - Private - Raspberry Pi 3b+

## Issue Description
```shell
##[section]Starting: Install Node.js
==============================================================================
Task         : Node.js Tool Installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH.
Version      : 0.149.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
##[error]Unable to find Node version '8.x' for platform linux and architecture arm.
##[section]Finishing: Install Node.js
```

This is because `os.arch()` equals `arm` but valid downloads are one of `linux-arm64, linux-armv6l, linux-armv7l`.

**Comment by damccorm** [comment]
@stephenmichaelf could you take a look? I think we just need to special case this one.

**Comment by timfish** [comment]
I've prepared a PR to fix this!

**Comment by timfish** [comment]
This is still an issue

**Comment by timfish** [comment]
This isn't fixed. This PR never got merged but would have fixed it:
https://github.com/microsoft/azure-pipelines-tasks/pull/13873
