### ISSUE TITLE
Unable to build windows generated service fabric on linux

### ISSUE THREAD

**Issue by jfalameda** [microsoft/azure-pipelines-tasks#10293]
Hi,

I ported a windows generated service fabric cluster into linux. I basically changed all the targets to linux-x64 and I also created a install and build and restore scripts (imitating how the yeoman scripts do it) to build and deploy my service using sfctl.

I tried to compile the project using the out of the box build SF linux pipeline in DevOPs. But I keep getting this error.

```
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
```

I woud be great to add extra information about how to solve this issue.

**Comment by anuragc617** [comment]
Hi @jfalameda, some of the tasks used in out of the box build SF pipeline are not supported on Linux, those tasks are supported only on windows as they are written in PowerShell. You can build your service by invoking your install, build and restore scripts from bash tasks like bash task, command line task.

**Comment by jfalameda** [comment]
Hi,

How am I supposed then to update the manifests versions when files change
and such? Does it mean I need to write it in bash? Can I build a linux SF
package form a windows pipeline?

Thanks.

Kind Regards,
/ José.

**Comment by anuragc617** [comment]
Hey @jfalameda, "ServiceFabricUpdateManifests" is the task that is used to update the version of the manifest but this task is also supported on Windows only. That means you have to write your scripts to update the manifests version. I don't think that you can use windows pipeline to build a Linux SF because of platform dependency.

**Comment by jfalameda** [comment]
Thanks. I create a feature request to add support for Linux pipelines. I believe this can be easily accomplished using python.

**Comment by jalajmsft** [comment]
Thank you for contributing and enhancing the experience. The task compares the latest build with the previous one depending upon the configuration, and if there exist a change the version is updated. You can see the working of the task [here](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricUpdateManifestsV2).

**Comment by sachinma** [comment]
@jfalameda did the above information help you? Let us know if you need any more details
