### ISSUE TITLE
GithubRelease@0: Endpoint auth data not present

### ISSUE THREAD

**Issue by BotellaA** [microsoft/azure-pipelines-tasks#10294]
I would like to use the task `GithubRelease@0` on Azure Pipelines, Hosted Ubuntu 1604. I created a Github connection using the Azure UI. I got this error: `Error: Invalid GitHub service endpoint`.

Here is my yml and debug log:
```
  - task: GithubRelease@0
    inputs:
      githubConnection: GeodeToken
      repositoryName: XXX
      action: edit
      tag: XXX
```

```
##[debug]Evaluating condition for step: 'GitHubRelease'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: GitHubRelease
==============================================================================
Task         : GitHub Release
Description  : Create, edit, or delete a GitHub release.
Version      : 0.151.1
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/AA3aeiw)
==============================================================================
##[debug]agent.TempDirectory=/Users/vsts/agent/2.150.3/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_GITHUBCONNECTION
##[debug]loading INPUT_REPOSITORYNAME
##[debug]loading INPUT_ACTION
##[debug]loading INPUT_TARGET
##[debug]loading INPUT_TAGSOURCE
##[debug]loading INPUT_TAG
##[debug]loading INPUT_RELEASENOTESSOURCE
##[debug]loading INPUT_RELEASENOTESFILE
##[debug]loading INPUT_ASSETS
##[debug]loading INPUT_ASSETUPLOADMODE
##[debug]loading INPUT_ISDRAFT
##[debug]loading INPUT_ISPRERELEASE
##[debug]loading INPUT_ADDCHANGELOG
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_GITHUB-TOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 18
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]agent.proxyurl=undefined
##[debug]VSTS_ARM_REST_IGNORE_SSL_ERRORS=undefined
##[debug]AZURE_HTTP_USER_AGENT=VSTS_7bcd5acc-5cbb-465c-85c7-314662156749_build_1_0
##[debug]Setting resource path to /Users/vsts/agent/2.150.3/work/_tasks/GitHubRelease_7b5a6198-adf8-4b16-9939-7addf85708b2/0.151.1/task.json
##[debug]check path : /Users/vsts/agent/2.150.3/work/_tasks/GitHubRelease_7b5a6198-adf8-4b16-9939-7addf85708b2/0.151.1/task.json
##[debug]adding resource file: /Users/vsts/agent/2.150.3/work/_tasks/GitHubRelease_7b5a6198-adf8-4b16-9939-7addf85708b2/0.151.1/task.json
##[debug]system.culture=en-US
##[debug]gitHubConnection=02fca1fc-7627-4efd-8f21-73a5f1d82e54
##[debug]task result: Failed
##[error]Endpoint auth data not present: 02fca1fc-7627-4efd-8f21-73a5f1d82e54
##[debug]Processed: ##vso[task.issue type=error;]Endpoint auth data not present: 02fca1fc-7627-4efd-8f21-73a5f1d82e54
##[debug]Processed: ##vso[task.complete result=Failed;]Endpoint auth data not present: 02fca1fc-7627-4efd-8f21-73a5f1d82e54
02fca1fc-7627-4efd-8f21-73a5f1d82e54 exists false
##[debug]02fca1fc-7627-4efd-8f21-73a5f1d82e54 exists false
##[debug]task result: Failed
##[error]Error: Invalid GitHub service endpoint: 02fca1fc-7627-4efd-8f21-73a5f1d82e54.
##[debug]Processed: ##vso[task.issue type=error;]Error: Invalid GitHub service endpoint: 02fca1fc-7627-4efd-8f21-73a5f1d82e54.
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Invalid GitHub service endpoint: 02fca1fc-7627-4efd-8f21-73a5f1d82e54.
##[section]Finishing: GitHubRelease
```
Link: https://dev.azure.com/GeodeSolutions/Geode/_build/results?buildId=183&view=logs&jobId=8ddd0bd4-8e24-5c83-a24c-dc6a31dfd012&taskId=21e303b6-5826-5bb1-89bc-ccf92cf3752e&lineStart=48&lineEnd=49&colStart=1&colEnd=1

I tried different Github connections (OAuth and Personnal Token) but same error. 

Thanks for your help.

**Comment by BotellaA** [comment]
Any update? It seems to affect multiple users.

**Comment by mdmdakbar** [comment]
Thanks @BotellaA for reporting the issue. Looking into it.

**Comment by mdmdakbar** [comment]
@BotellaA @pragmatrix Did you recently updated the service endpoint?

We are not able to reproduce this issue at our end. Could you please create a new service endpoint and try again?

If issue persists, please reach out to us at RM_Customer_Queries@microsoft.com, which is for internal query management. Thanks

**Comment by BotellaA** [comment]
@mdmdakbar I created a new service endpoint and same error. Is this task able to work with private repositories?

**Comment by pragmatrix** [comment]
@mdmdakbar I removed all connections, removed the GitHub App, readded it, reconnected everything, and the same error appeared: 

https://dev.azure.com/pragmatrix-github/rust-skia/_build/results?buildId=935

All GitHub connection endpoints are OAuth based and were successfully authorized. I've queued a diagnostic build here:

https://dev.azure.com/pragmatrix-github/rust-skia/_build/results?buildId=939

**Comment by akbarmdmd** [comment]
Thanks @BotellaA for sharing your Yaml. It helped to debug the issue.

Yaml task input seems to be case sensitive. For GitHub connection input please specify git**H**ubConnection (capital H).

@pragmatrix Can you also check if your Yaml connection input takes care of case sensitivity or not?

Documentation link: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops.

Please write to us in case you still face the issue. Thanks

**Comment by pragmatrix** [comment]
That seems to fix it, thank you for the help! And please adjust the casing in all the examples on the documentation page, too.

**Comment by BotellaA** [comment]
@akbarmdmd Thanks ! It works. However, the examples in the documentation do not have an H. That is the reason of my mistake.
