### ISSUE TITLE
Allow the names of Secure Files in the download step to be parameterised.

### ISSUE THREAD

**Issue by Burnsy2023** [microsoft/azure-pipelines-tasks#10306]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Download Secure File
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadSecureFileV1

## Issue Description
A the moment, the secure file download step only allows you to select a file from a list when using the GUI to create a release pipeline. We have several files that we'd like to parameterise within this step so that the right file is used for a particular deployment. All we'd like to do is put a variable in the 'secure file' field rather than have it only as a drop down selection.

This would be less of a problem when yaml releases arrives, but in the interim, this hopefully small change would be really useful.

**Comment by sphanley** [comment]
This appears to be a duplicate of #6885.
