### ISSUE TITLE
NuGet pack task doesn't include dependencies when using PackageReference

### ISSUE THREAD

**Issue by satbai** [microsoft/azure-pipelines-tasks#10301]
Repro steps:
1. Create a project that references other NuGet packages using [PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) in the project file.
2. Use the v2.* NuGet task pack command to pack the project. 
3. Add a NuGet push task to push the package to a feed.
4. View the pushed package in the feed. You should be able to see the referenced packages as dependencies but they're not there.

Notes:
- This does not repro with projects that reference packages using the [package.config](https://docs.microsoft.com/en-us/nuget/reference/packages-config) file instead of PackageReference.
- Originally reported in [Developer Community](https://developercommunity.visualstudio.com/content/problem/443391/build-step-nuget-pack-not-including-referenced-pac.html)

**Comment by Rzpeg** [comment]
@satbai The problem lies in nuget.exe itself. look: https://github.com/NuGet/Home/issues/5979

The workaround that works for me is to patch nuspec with a powershell script, manually. This version supports only 1st level dependencies though.

```

Get-ChildItem -recurse | 
    where {$_.extension -eq ".nuspec"} |
    Foreach-Object {
        $PathToCsproj = $_.DirectoryName + "\" + $_.BaseName + ".csproj"
        $PathToNuSpec = $_.DirectoryName + "\" + $_.BaseName + ".nuspec"
        $csproj = [xml](Get-Content $PathToCsproj)
        $packageDependency = $csproj.Project.ItemGroup.PackageReference | Where-Object { $null -ne $_ }
        $nuspec = [xml](Get-Content $PathToNuSpec)

        $dep = $nuspec.CreateElement('dependencies', $nuspec.package.metadata.NamespaceURI)

        $packageDependency | ForEach-Object {
          $onedependency = $dep.AppendChild($nuspec.CreateElement('dependency', $nuspec.package.metadata.NamespaceURI))
          $onedependency.SetAttribute('id', $_.Include)
          $onedependency.SetAttribute('version', $_.Version)
        }

        $nuspec.package.metadata.AppendChild($dep)

        $nuspec.Save($PathToNuSpec)
    }
```

**Comment by edufur** [comment]
That workaround will not work for me as I have nested dependencies. What is being done to resolve this issue?

**Comment by satbai** [comment]
Looks like this bug should be part of [this NuGet issue](https://github.com/NuGet/Home/issues/6285) that bundles various issues with NuGet pack. @rrelyea, do you know if the nuget pack issues are being worked on yet?

**Comment by Rzpeg** [comment]
@edufur You could modify the script to process nested dependencies, just share it later, please.
I guess, nothing is being done to resolve this issue.
