### ISSUE TITLE
Using two value files in helm install

### ISSUE THREAD

**Issue by xinofekuator** [microsoft/azure-pipelines-tasks#10309]
In Azure Devops I am trying using the `Package and deploy Helm charts` task for performing a `helm install`
and override the default values.yaml with several yaml files seems not supported.

Right now only one file can be added in the `Value File` text box. However, help support passing several yaml files with options `-f` or `--values` as specified in the documentation https://helm.sh/docs/helm/#helm-install

**Comment by ds-ms** [comment]
@xinofekuator The usage can be extended in the `arguments` section. 
You can apply more than one file to that chart by using: `-f <path to values.yml>` in your arguments section. 
If you want to apply `file1` and `file2` in that order. You should give the path to `file1` in the `Value File` text box and `-f <path to file2>` in your arguments section.
