### ISSUE TITLE
XCode@5 only passes teamId when signingOption = auto

### ISSUE THREAD

**Issue by leonidumanskiy** [microsoft/azure-pipelines-tasks#10312]
**Problem:**
Currently, XCode@5 task only passes teamId parameter only when signingOption is set to `auto`. This is incorrect and does not cover all use cases.

**Example use case:**
xcode project is generated (i.e. by Unity3d) and does have provisioning profile / teamId set. Provisioning profile can be set by doing "manual" signing. However passing provisioning profile without teamId would result in the following error:

_error: Signing for "Unity-iPhone" requires a development team. Select a development team in the build settings editor that matches the selected profile "iPhone Distribution Ad Hoc". (in target 'Unity-iPhone')_

**Resolution:**
Allow to pass teamId with any signingOption.

**Comment by arturmiz** [comment]
Hi, I just want to let you know this is still an issue. Lost lots of time until I came across this issue...
