### ISSUE TITLE
NuGetToolInstallerV1 uses unknown IP to download

### ISSUE THREAD

**Issue by oleksabor** [microsoft/azure-pipelines-tasks#10316]
## Required Information

**Question, Bug, or Feature?**  
*Type*: question

**Enter Task Name**: NuGetToolInstaller  

## Environment

Azure Pipelines: 
*account* quipu-cwnet
*team project* tools
*build definition* DirectClientDataSync
*build number* 20190506.1

Agent - Private: 
* Windows Server 2012R2 version 6.3 build 9600
* agent: 2.150.3

## Issue Description

I'm using NuGetToolInstallerV1 to download nuget in the YAML script like below:
````
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
````
hosted agent is running behind the company proxy. The problem is that NuGetToolInstaller uses unknown IP that is not allowed in the proxy white list. I've asked to allow access to the `152.199.19.160` but request was rejected as `this is unknown IP`. We have allowed all Microsoft networks IPs ranges in the proxy, however 152.199.19.160 does not belong to MS networks.

It would be nice to have NuGet tool downloading link that is hosted in the MS network.
Why non MS IP is used in the NuGet tool installer task?
Is it possible to configure installer task to use well known url to download ?

#3756 script can be used as the workaround.

## Troubleshooting
NugetInstallerTool tries to download Nuget from unknown IP

### Error logs

````
##[section]Starting: Use NuGet 4.4.1
==============================================================================
Task         : NuGet Tool Installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
Version      : 1.150.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=852538)
==============================================================================
ERR:connect ECONNREFUSED 152.199.19.160:443
##[section]Finishing: Use NuGet 4.4.1
````
[logs_1090.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3147018/logs_1090.zip)

**Comment by magleaso** [comment]
Could you flip System.Debug to True and run this again? That should help me trace the network call that's causing the issue

**Comment by oleksabor** [comment]
Please find attached full log

````
##[debug]checking cache: E:\buildagent\network\_work\_tool\NuGet\4.4.1\x64
##[debug]not found
##[debug]Agent.Version=2.150.3
##[debug]Agent.ToolsDirectory=E:\buildagent\network\_work\_tool
##[debug]evaluating 0 versions
##[debug]match not found
##[debug]Querying versions list
##[debug]Agent.ProxyUrl=undefined
ERR:connect ECONNREFUSED 152.199.19.160:443
````

I'd like to note that proxy is not configured for agent since all Microsoft IPs are allowed to be connected directly on hosted agent. Git can download source code without any problem e.g. 

[logs_1164.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3181260/logs_1164.zip)
computer

**Comment by magleaso** [comment]
This IP address belongs to nuget.org which is a Microsoft website. You should allow connections to this website and associated IPs if you need to download the NuGet client.

**Comment by oleksabor** [comment]
Thank you very much for information
