### ISSUE TITLE
powershell.exe: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index.

### ISSUE THREAD

**Issue by ohadschn** [microsoft/azure-pipelines-tasks#10319]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `PowerShellV2`

## Environment
- Server - Azure Pipelines 
  - Account name: `msazure`
   - Team project name: `One`
   - Build definition name: `PSAF.Deployment`
   - Build: https://msazure.visualstudio.com/One/_build/results?buildId=21959637 (debug+diagnostics enabled)

- Agent - Private: 
    - `Windows Server 2019 Datacenter (10.0.17763.0)`
    - PowerShell `5.1.17763.316` 
    - Agent `2.150.3`

## Issue Description

Our logs sporadically contain:
```
##[debug]Error record:
##[debug]powershell.exe : Index was out of range. Must be non-negative and less than the size of the collection.
##[debug]At line:1 char:1
##[debug]+ & 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe' --% -No ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (Index was out o...the collection.:String) [], RemoteException
##[debug]    + FullyQualifiedErrorId : NativeCommandError
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at Invoke-Tool, C:\AzDoWrk\AGENT01\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.148.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1: line 107
##[debug]at <ScriptBlock>, C:\AzDoWrk\AGENT01\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.148.0\powershell.ps1: line 98
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RemoteException: Index was out of range. Must be non-negative and less than the size of the collection.
##[error]Index was out of range. Must be non-negative and less than the size of the collection.
##[debug]Processed: ##vso[task.logissue type=error]Index was out of range. Must be non-negative and less than the size of the collection.
##[debug]Error record:
##[debug]Parameter name: index
##[debug]
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at Invoke-Tool, C:\AzDoWrk\AGENT01\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.148.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1: line 107
##[debug]at <ScriptBlock>, C:\AzDoWrk\AGENT01\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.148.0\powershell.ps1: line 98
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RemoteException: Parameter name: index
##[debug]
##[error]Parameter name: index
##[debug]Processed: ##vso[task.logissue type=error]Parameter name: index%0D%0A```
```

It looks like your code ends up calling something like `Invoke-Expression "& 'powershell.exe' --% -NoProfile..."`. In fact we had the exact same code and got the exact same error. To this day we don't know exactly why (we suspect something in the standard process streams), but we were able to work around it by replacing `Invoke-Expression "& 'powershell.exe' ...` with `Start-Job ...`  (which basically starts `powershell.exe` under the covers).

**Comment by damccorm** [comment]
This looks like it is probably an environment specific/powershell bug. Given that, I'm pretty hesitant to change how we do this since there are some subtle differences between `Invoke-Expression` and `Start-Job` and I'm not 100% certain that wouldn't break other people.

**Comment by ohadschn** [comment]
That's fair, but in order to unblock people who face this, perhaps you could enable some switch that uses `Start-Job` instead?

**Comment by damccorm** [comment]
My instinct is that we probably shouldn't do that. Any time we add an option like this it has to live until we major version the task (which rarely happens). As a policy, we don't add options for individual customers to avoid bloat.

If you feel like you really need this, you can always install a custom version of the task that behaves like you desire.

**Comment by ohadschn** [comment]
Actually I can't, it's on msazure where I'm not an admin and the admins will never agree to this...
I wonder if an upgrade to PowerShell 6 will solve this, but we may never know as these systems are on a deprecation path :)

**Comment by damccorm** [comment]
Not totally sure what you mean there, but I'm not sure if the PowerShell upgrade would solve the issue or not.

Concerning not having admin access, you could also go the route of starting the job from a command line script.

I think I'm going to close here since this seems like a no-op on our end, let me know if you disagree/we should reopen

**Comment by ohadschn** [comment]
Pretty sure starting `powershell.exe` from the commandline task had its own problems, but none of these are my problems anymore, so no objection from me to closing this.
