### ISSUE TITLE
VsTestV2: Running test using "Path to custom test adapters" returns "Could not find extensions: C:\SeleniumWebDrivers\ChromeDriver"

### ISSUE THREAD

**Issue by ralucapredacegeka** [microsoft/azure-pipelines-tasks#10317]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VsTestV2  

## Environment
- Server - Azure Pipelines   
https://dev.azure.com/cegekadsa/DynamicsEmpire/_releaseProgress?_a=release-environment-logs&releaseId=9065&environmentId=24231
- Agent - Hosted VS2017

## Issue Description
We want to run our UI tests on Microsoft-hosted agents using the Selenium web drivers that are pre-installed on the agents.
We have set "Path to custom test adapters" = $(ChromeWebDriver) in our release.
![image](https://user-images.githubusercontent.com/20595902/57221660-b4fc6580-7008-11e9-844d-3802db50e62f.png)

However, when we run the tests the following warning is returned: 
![image](https://user-images.githubusercontent.com/20595902/57221766-fdb41e80-7008-11e9-89bc-ff24223ca775.png)

To make sure this is not caused by something in our code, we have created a new test project based on the steps described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops) and ran the TheBingSearchTest test with the same result.

### Task logs
[tasklog_11 (1).log](https://github.com/Microsoft/azure-pipelines-tasks/files/3147628/tasklog_11.1.log)

### Error logs
 ##[warning]RunMessage : Could not find extensions: C:\SeleniumWebDrivers\ChromeDriver

**Comment by karanjitsingh** [comment]
@ralucapredacegeka, i think you're confusing vstest adapter with SeleniumChromeDriver. SeleniumChromeDriver is not a test adapter extension. Please refer https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops

**Comment by ralucapredacegeka** [comment]
Hi @karanjitsingh ,

Indeed I can see my mistake now. 
Still, we want to use the Selenium web driver that is installed on the Hosted 2017 agents when running the tests. Based on the info found here: https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops#decide-how-you-will-deploy-and-test-your-app

_When using the Microsoft-hosted agent, you should use the **Selenium web drivers that are pre-installed on the Windows agents** (agents named Hosted VS 20xx) because they are compatible with the browser versions installed on the Microsoft-hosted agent images. The paths to the folders containing these drivers can be obtained from the environment variables named IEWebDriver (Internet Explorer), ChromeWebDriver (Google Chrome), and GeckoWebDriver (Firefox)._ 

Could you maybe give a tip on how to achieve this? 


Thanks,
Raluca
