### ISSUE TITLE
NET Core SDK Installer and Visual Studio Build tasks conflict with each other

### ISSUE THREAD

**Issue by andyfisher100** [microsoft/azure-pipelines-tasks#10325]
*Type*: Bug

**Task Name**: Visual Studio Build

## Environment
- Server - Azure Pipelines
- Agent: Private
- OS: Windows 10 1803    
- Agent Version: 2.150.3

## Issue Description
We have a pipeline that currently uses the .NET Core SDK Installer task to install SDK version "2.1.503" which corresponds to runtime version 2.1.7. this installs as expected.

Later in the pipeline the Visual Studio Build task is used to build a solution. The solution has both .Net framework and .Net Core projects. This task will fail as visual studio cant detect the version of .Net core that was task installed earlier in the pipeline. Visual studio will only find the version of .Net Core that was manually installed on the machine, in this case 2.1.9 and the following error is displayed

error : NETSDK1061: The project was restored using Microsoft.NETCore.App version 2.1.7, but with current settings, version 2.1.9 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection.

I dont think this would be an issue if the dotnet build task was used but i expected the visual studio build task could also be used with the sln file.

The project is a service fabric application.

**Comment by jalajmsft** [comment]
Thank you for describing the entire scenario. The 2.1.9 version is probably installed in global namespace and is taking precedence over the version installed via .Net Core SDK installer task. You can read about how multi-level lookup works within .NET [here](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md). 

Can you uncheck the option "Perform Multi Level Lookup" for .Net Core SDK Installer task for version 1.* or 2.*  and try, this would ensure the version specified by the task is used.

**Comment by andyfisher100** [comment]
Thanks for the response. I didn't realise there was 2 newer preview versions of the task. What you explained will be correct regarding the global and agent namespaces.

I changed our images to include multiple versions of the dotnet core SDK in the global namespace so it will take me a few days to prep for testing this alongside my day job. I will report back once tested

**Comment by jalajmsft** [comment]
Hi @andyfisher100 Did you get a chance to test this out?

**Comment by andyfisher100** [comment]
I did, it appeared to fix the issue, thanks!

How come both versions 1 and 2 of the task re both in preview? And when will they be out of preview?

**Comment by jalajmsft** [comment]
We will soon roll these versions out of the preview.

**Comment by jalajmsft** [comment]
Closing this. Feel free to reopen or open a new issue in case of you need any further help.

**Comment by jalajmsft** [comment]
Closing this. Feel free to reopen or open a new issue in case of you need any further help.
