### ISSUE TITLE
Write-Host in referenced scripts does not get passed through

### ISSUE THREAD

**Issue by epvanhouten** [microsoft/azure-pipelines-tasks#10320]
It appears that [line129](https://github.com/microsoft/azure-pipelines-tasks/blob/1728abf77c993571dd1a1753f52c34f3deece383/Tasks/AzurePowerShellV4/AzurePowerShell.ps1#L129) is gobbling Write-Host statements. This causes issues when attempting to set variables using ##[task.setvariable ...].

Special casing [System.Management.Automation.HostInformationMessage] to call Write-Host $_.Message may solve the narrow issue. Needing to do that for all the streams feels a bit dirty.

**Comment by arjgupta** [comment]
Hi @epvanhouten , can you share a sample script that we can use to reproduce this issue. Also tell, how are you trying to access the variable that you are setting using ##[task.setvariable]. Are you using Azure DevOps Services (previously VSTS ) or the Azure DevOps Server (previously Team Foundation Server and what version ??). What is the version PowerShell that you are using on the agent machine. Share the value of the $PSVersionTable variable.

**Comment by arjgupta** [comment]
@epvanhouten i am closing this issue. If you are still facing it, please reopen the issue and provide the requested details.
