### ISSUE TITLE
Support more protocols with IIS Web Application Management

### ISSUE THREAD

**Issue by likemike91** [microsoft/azure-pipelines-tasks#10322]
**Question, Bug, or Feature?**  
*Type*: Question, Feature

**Enter Task Name**: IISWebAppManagementOnMachineGroupV0 (IIS Web Application Management)

## Environment
Both TFS and Azure Pipelines

## Issue Description
For handling all scenarios supported by IIS the pipeline task should also support managing bindings for protocols like net.tcp, net.msmq and so on.
I had a short look on the implementation of the source code and think it should be possible to implement without much effort.
Unfortunately I cannot bypass the problem by using the "Additional appcmd.exe commands" since I cannot check whether the binding for a particular protocol, host, port does already exist or not and therefore commands like `set site /site.name "$(Webserver.WebsiteName)" -+bindings.[protocol='net.tcp',bindingInformation='808:*']` fail.

I probably try to implement it and send a PR but first want to gather some feedback on the idea in general.

**Comment by kmkumaran** [comment]
@likemike91 - Appreciate you contributing to the task. You are right that the same cannot be accomplished with additional arguments at this point. So please feel free to raise a PR with the protocol support.

**Comment by bwienefoet** [comment]
+1! This would be a great and usefull Feature. I need it for configuring a net.tcp Binding. The workaround is ok but it throws errors on redeploying

**Comment by kmkumaran** [comment]
@N-Usha - Can you review and triage the ask.
