### ISSUE TITLE
ARM optional parameters variables

### ISSUE THREAD

**Issue by UnoSD** [microsoft/azure-pipelines-tasks#10334]
*Type*: Question or feature

**Enter Task Name**: Azure Resource Group Deployment

## Environment
- Server - Azure Pipelines
    
## Issue Description

When using an ARM template with optional parameters (with defaultValue set), would be nice to be able to link those to a variable and if the variable is empty having the option to omit the parameter and use the default.

I would probably need to be an option per step or per single parameter as in some cases people may want to force it to be blank; although that could be achieved by empty double quotes "".

In the meanwhile, is there a workaround for this?

Thank you

**Comment by atyourservers** [comment]
If I understand you correctly, you could use the following as a variable then:

`"yourVariableName": "[if(empty(parameters('yourParameterName')), 'YourDefaultValue', parameters('yourParameterName'))]"`

**Comment by UnoSD** [comment]
@atyourservers yes, I thought about that, but in my case there are several parameters and it would make the ARM template quite massive and confusing. It does not feel right to change the template when it supports default parameters. I was wondering if there was a more elegant way for this.

**Comment by atyourservers** [comment]
The only other way I can think of is filtering the input which is sent to the template, so if a value is empty, don't send it to the template as parameter. That means that your scripting in front of the template will have to contain more logic.

(What is a massive template? We have a few of around 1000 lines. Most are half that size.)

**Comment by UnoSD** [comment]
Like a PowerShell script that removes the arguments where it is empty?

(Massive as in ~35 parameters that can be optional)

**Comment by dsfrederic** [comment]
Is it possible to set a defaultvalue for object parameters? So i don't have to add `appsettings: []` for every object in this array?

For example 
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "appservices": {
      "value": [
        {
          "name": "NAME"
          // "appsettings": []
        },
        {
          "name": "NAME",
          "appsettings": [
            {
              "name": "ASPNETCORE_ENVIRONMENT",
              "value": "Production"
            }
          ]
        }
      ]
    }
  }
}
```
