### ISSUE TITLE
NodeToolInstaller does not satisfy demands for Gulp

### ISSUE THREAD

**Issue by Skoucail** [microsoft/azure-pipelines-tasks#10333]
**Type**: Bug
**Task Name**: NodeToolV0, GulpV0, GulpV1   

## Environment
- Server - Azure DevOps 2019 Server
    - Version: 17.143.28621.4

- Agent: Private: 
    
    - OS: Windows Server 2016 Standard

    - Agent version: 2.144.2

## Issue Description

When using the Node tool installer (NodeToolV0) the Agent demands are not getting satisfied for the Gulp task (GulpV0/GulpV2) .
Adding npm to the satisfies list is already solved in https://github.com/microsoft/azure-pipelines-tasks/issues/9795.
But i believe there is a naming mismatch for Node.js ("Node" =/= "node.js").

From NodeToolV0 task.json:
`"satisfies": [
        "Node",
        "npm"
    ],`

From GulpV0/GulpV1 task.json:
`"demands": [
        "node.js"
    ],`

**Comment by damccorm** [comment]
This was fixed in https://github.com/microsoft/azure-pipelines-tasks/commit/b1ca02a94b456f61fdb9e1d01ec6633e52b1f40c, sorry we missed updating here
