### ISSUE TITLE
Azure File Copy TLS1.2

### ISSUE THREAD

**Issue by TheJayMann** [microsoft/azure-pipelines-tasks#10337]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureFileCopy

## Environment
- Server - TFS on-premises version 17.143.28621.4
    
- Agent - Private: Windows Server 2019 Agent version 2.144.2
    
## Issue Description

Azure File Copy task uses an agent built in version of AzCopy, and does not work when TLS1.0 and TLS1.1 are disabled.  Our company policy is to only allow TLS1.2 on our servers.  This prevents Azure File Copy task from working unless TLS1.0 and TLS1.1 are enabled.  I've been informed that later versions of AzCopy compiled for .NET Core uses TLS1.2 by default, but I'm unsure what needs to be done to ensure that the Azure File Copy task makes use of a different version of AzCopy than what comes with the agent.

**Comment by rajatagrawal-dev** [comment]
@TheJayMann AzCopy should work fine with TLS 1.2. [Refer this](https://github.com/MicrosoftDocs/azure-docs/issues/14042).

Can you send us the debug logs of your build/release? Add a variable "system.debug" in the variables section of your definition and set it's value to "true". This will give the debug logs.

**Comment by TheJayMann** [comment]
Looking further into this myself, I see that this task makes use of AzCopy version 7.3.  Based on assembly metadata, it is meant to run on .NET Framework 4.5, and I see no evidence of the tool selecting TLS 1.2 in it's code.  
This would mean that tool would by default use TLS 1.0 by default, and will fail if TLS 1.0 is not enabled by the OS.  I have needed to solve this myself in our network by either recompiling the code in .NET Framework 4.6 or later or .NET Core, or by modifying the web.config/app.config to override the runtime framework to .NET Framework 4.6 or later.

The error given when the task runs is 'The underlying connection was closed: An unexpected error occurred on a receive' which I have seen before and is caused by a client application running on a machine with TLS 1.0 and 1.1 disabled for clients attempting to connect while running with .NET Framework 4.5 or earlier, and has been fixed by using one of the methods mentioned above.  Also, I have also modified the OS settings for the build agent, enabling TLS 1.0 and TLS 1.1 for client, and the task works without issue and is able to successfully copy files to Azure Blob Storage.  Both of these suggest that the version of AzCopy included with the task will not work if TLS 1.0 and TLS 1.1 are disabled for client use on the OS using HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols.

**Comment by rajatagrawal-dev** [comment]
@TheJayMann Is TLS 1.2 enabled on your agent machine? You have to enable TLS 1.2 explicitly for .NET 4.5 by setting a couple registry entries which are specific to .NET. Once you have enabled TLS 1.2 and disabled TLS 1.0 and 1.1, AzCopy would automatically pick TLS 1.2.

Please check [this link](https://support.microsoft.com/en-us/help/3206898/enabling-iis-manager-and-web-deploy-after-disabling-ssl3-and-tls-1-0) to see which registry entries you need to set. Note that it depends on your OS and .NET framework versions. There is also an alternative to install a KB which is also specified in the above link. Also note that you may have to restart the machine after the above settings.

Let us know if this works for you.

**Comment by TheJayMann** [comment]
I will try the SchUseStrongCrypto setting and see if that works.  I hadn't seen this setting before, and various websites seem to suggest it will work.

However, the build machine is currently down after I restarted it, and I won't be able to get it back up until the operations team is available.

**Comment by TheJayMann** [comment]
Adding the SchUseStrongCrypto values fixed the problem.

**Comment by acjaju1459** [comment]
> Adding the SchUseStrongCrypto values fixed the problem.

I am using AZCOPY command in my powershell script to perform copy operation . The command working fine on TLS V 1.0 but when I changed to TLS version 1.2 . I was getting error and AZCOPY command is not working in powershell stating that TLS version is not supported to this storage account. Could yu please help me to fix the issue.
