### ISSUE TITLE
AzureFileCopyV3 Failing on cleanup

### ISSUE THREAD

**Issue by halfpeaw** [microsoft/azure-pipelines-tasks#10338]
## Note  
Azure File Copy appears to be failing on clean up.  This is a recent development and only appears to be happening about 25% of the time.

Here's the exact error: 
[error]Cannot bind parameter 'Context'. Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IStorageContext".

Here's an example of the failure
https://office.visualstudio.com/Crates/_build/results?buildId=2128115

### Error logs

[section]Starting: AzureBlob File Copy
==============================================================================
Task         : Azure File Copy
Description  : Copy files to Azure blob or VM(s)
Version      : 3.0.4
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/azurefilecopyreadme)
==============================================================================
Added TLS 1.2 in session.
[command]Import-Module -Name C:\Users\ovstsagt\Documents\WindowsPowerShell\Modules\Az.Accounts\1.5.2\Az.Accounts.psd1 -Global
[warning]Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide
[command]Clear-AzContext -Scope Process
[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
[command] Set-AzContext -SubscriptionId 6ead65f7-ced8-4f7f-8eff-20874e485546 -TenantId ***
[command]Import-Module -Name C:\Users\ovstsagt\Documents\WindowsPowerShell\Modules\Az.Resources\1.2.0\Az.Resources.psd1 -Global
[command]Import-Module -Name C:\Users\ovstsagt\Documents\WindowsPowerShell\Modules\Az.Storage\1.0.3\Az.Storage.psd1 -Global
[command]Import-Module -Name C:\Users\ovstsagt\Documents\WindowsPowerShell\Modules\Az.Compute\1.5.0\Az.Compute.psd1 -Global
[command]Import-Module -Name C:\Users\ovstsagt\Documents\WindowsPowerShell\Modules\Az.Network\1.3.0\Az.Network.psd1 -Global
Uploading files from source path: 'E:\_work\microsoft.office.warehouse.lenssdk.android\dpk\updates.dpk' to storage account: 'packageupdate' in container: 'microsoftofficewarehouselenssdkandroid' with blob prefix: '20190508.1'
[command] & "AzCopy\AzCopy.exe" /Source:"E:\_work\microsoft.office.warehouse.lenssdk.android\dpk" /Dest:"https://packageupdate.blob.core.windows.net/microsoftofficewarehouselenssdkandroid/20190508.1" /@:"E:\_work\_temp\685e0ff0-cf34-407f-82bd-d7a0c1cd4182" /XO /Y /SetContentType /Z:"AzCopy" /V:"AzCopy\AzCopyVerbose_c940c924-3353-413f-b1ce-3fb204cf9ee5.log" /S /Pattern:"updates.dpk"
[2019/05/08 21:14:43] Transfer summary:
-----------------
Total files transferred: 1
Transfer successfully:   1
Transfer skipped:        0
Transfer failed:         0
Elapsed time:            00.00:00:00
Uploaded files successfully from source path: 'E:\_work\microsoft.office.warehouse.lenssdk.android\dpk\updates.dpk' to storage account: 'packageupdate' in container: 'microsoftofficewarehouselenssdkandroid' with blob prefix: '20190508.1'
[command]Remove-AzureRmAccount -Scope Process
[warning]Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
[error]Cannot bind parameter 'Context'. Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IStorageContext".
[section]Finishing: AzureBlob File Copy

**Comment by rajatagrawal-dev** [comment]
@halfpeaw It seems that you have both `Az` and `AzureRM` powershell modules installed on some of your build agents. This is what is causing an issue. It is recommended to have only one of those installed. Check [this](https://github.com/Azure/azure-powershell#powershell-gallery).

Please uninstall one those modules completely from all your build agents and then try again. Let us know if you still face issue.
