### ISSUE TITLE
Azure PowerShell v4 task fails when using certificate credentials

### ISSUE THREAD

**Issue by cmielke** [microsoft/azure-pipelines-tasks#10335]
Type: Bug
Task Name: Azure PowerShell

## Environment
- Server - Azure Pipelines
    - Account Name: Emdat
    - Team Project Name: Emdat
    - Release Definition: _testing-az-cert-issues (Release-3)
    
- Agent - Private: 
    - OS: Windows Server 2019 Datacenter (running on an Azure VM)
    - Agent version: 2.150.3

## Issue Description
When using the Azure PowerShell task with a service connection that uses certificate-based authentication, I get the following error message: WARNING: can't open config file: /usr/local/ssl/openssl.cnf, and the task fails. **This only happens when my agent is running on an Azure VM. When running in an on-premise VM, I do not get the error.**

Here are specific steps to reproduce the issue:
- In Azure, create a new VM with Windows Server 2019 and install the Azure Pipelines deployment agent on it and install the Az PowerShell module.
- Create an Azure Resource Manager service connection using the full version of the service connection dialog as in the following screenshot. Make sure to use a Certificate instead of a Service principal key.
![image](https://user-images.githubusercontent.com/7267334/57386945-0f1d3800-717b-11e9-90b8-5af384523f9b.png)
- Create a release pipeline with a single stage 
- Add a Deployment Group phase that uses the same deployment group as the VM you created above.
- Add an Azure PowerShell task
- Configure the Azure PowerShell task for version 4.* (preview) and select the service connection you created previously. 
![image](https://user-images.githubusercontent.com/7267334/57387494-12fd8a00-717c-11e9-9d28-9f1e140798cc.png)
- Run the release and wait for the error message.

### Task logs
[tasklog_4.log](https://github.com/microsoft/azure-pipelines-tasks/files/3158344/tasklog_4.log)

### Error logs

2019-05-08T15:12:22.2280529Z ##[error]WARNING: can't open config file: /usr/local/ssl/openssl.cnf
2019-05-08T15:12:22.2881599Z ##[command]Disconnect-AzAccount -Scope Process -ErrorAction Stop
2019-05-08T15:12:22.3050491Z ##[warning]Run Connect-AzAccount to login.
2019-05-08T15:12:22.4337712Z ##[error]There was an error with the service principal used for the deployment.

**Comment by kmkumaran** [comment]
@cmielke - for the service connection that you have created, can you tell us what you see if you click on "verify"


![image](https://user-images.githubusercontent.com/11780076/57425708-ea3bca00-7239-11e9-972d-7eb382ebbcc1.png)

**Comment by cmielke** [comment]
It verifies successfully...
![image](https://user-images.githubusercontent.com/7267334/57470846-74425d80-724f-11e9-8ec1-f4f84562af7f.png)

**Comment by asranja** [comment]
@cmielke This should be a warning message. "WARNING: can't open config file: /usr/local/ssl/openssl.cnf" and not fail the release. 

Please set the variable "system.debug" to "true" and redeploy. Check if there are any additional errors mentioned in the log. If not, please share the debug logs to RM_CUSTOMER_QUERIES@microsoft dot com.

**Comment by cmielke** [comment]
The debug logs are already linked to my original message under the Task Logs section. Here is the link again: [logs](https://github.com/microsoft/azure-pipelines-tasks/files/3158344/tasklog_4.log). I will also email them to RM_CUSTOMER_QUERIES@microsoft dot com.

**Comment by cmielke** [comment]
I have some new information... I just spun up a Windows Server 2016 Azure VM and the task worked fine. I still get the same warning message, but it does not fail the task. So it is looking like this is a Windows Server 2019 issue, and not necessarily an Azure VM issue.

**Comment by Ajay-MS** [comment]
@cmielke  

Thanks for reporting this issue. I will try this scenario on Windows Server 2019 and will update you soon.

**Comment by Ajay-MS** [comment]
@cmielke 

We have identified the issue and fixing it from our end for Window Server 2019 server. Opened an internal bug for this. 

Meanwhile as a workaround in order to unblock you. 
1. Copy [Openssl.cnf](https://github.com/Ajay-MS/UtilityScripts/blob/master/Encryption/openssl.conf) file on agent machine.
2. Add a PowerShell task in release definition before  Azure PS task and add following script
```
$env:OPENSSL_CONF = "<Path where you copied>\openssl.cnf"
$env:RANDFILE=".rnd"
```

Closing this issue based on workaround. Feel free to reopen in case it doesn't help.

**Comment by cmielke** [comment]
Thank you Ajay! I will implement the workaround and let you know if I run into any issues.

**Comment by vincentdass** [comment]
@cmielke , does the workaround provided [here ](https://github.com/microsoft/azure-pipelines-tasks/issues/10335#issuecomment-493985667) worked for you?

**Comment by cmielke** [comment]
@vincentdass I apologize. I have not had a chance to try the workaround yet. We switched our agent back to Windows Server 2016 to get around the issue for now. I will try the suggested workaround today and let you know how it goes.

**Comment by cmielke** [comment]
The suggested workaround did not work. I am getting the same error:

![image](https://user-images.githubusercontent.com/7267334/58490715-4310cb00-8133-11e9-96ce-385497c7e8f9.png)

For now, I have switched my agents back to Windows Server 2016, and I am fine with that workaround until the internal bug is resolved.

**Comment by vincentdass** [comment]
@cmielke , Apologies.
Please add the following lines instead:
```
Write-Host '##vso[task.setvariable variable=OPENSSL_CONF;]<foler_path>\openssl.cnf'

Write-Host '##vso[task.setvariable variable=RANDFILE;].rnd'
```
Note: Please replace <folder_path> accordingly.
