### ISSUE TITLE
Broken symlink for helm/repository/cache/local-index.yml

### ISSUE THREAD

**Issue by majorvin** [microsoft/azure-pipelines-tasks#10346]
Using Ubuntu 1604

Intermittent. Sometimes it works and sometimes it doesn't. 

Job: "Unhandled: Failed find: ENOENT: no such file or directory, stat '/var/lib/waagent/custom-script/download/1/agent/_work/27/s/.helm/repository/cache/local-index.yaml'"

**Comment by ds-ms** [comment]
@majorvin could you give some more context? 
Perhaps, a snapshot of your pipeline configuration, or of just this step where it is failing.

**Comment by majorvin** [comment]
@ds-ms 
![image](https://user-images.githubusercontent.com/1380446/58961490-3c0f3b80-8777-11e9-897b-bfccf9f558ac.png)

**Comment by ds-ms** [comment]
@majorvin do you see any unusual logs in your `helm init`/`Install helm` step, whenever you see this intermittent issue?

**Comment by bansalaseem** [comment]
Closing because of no response from @majorvin. Please feel free to open it up if you have answer to above question of @ds-ms .
