### ISSUE TITLE
complete set JSON replacement doesn't work

### ISSUE THREAD

**Issue by nikhil2007rock** [microsoft/azure-pipelines-tasks#10347]
As suggested by @SumiranAgg in the issue #9338, I've tried the below but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/5222165/57373668-8de39680-71b6-11e9-8fbf-b8d2c61b37ca.png)

The level of the key is as follows
```
{
  "auth": {
             "key1":"value1",
             "key2":"value2",
             "endpoints": {
                              "http://contoso.com/": "12fbdc54-4ff7-48bc-bffa-35bd3ffcd2cf",
                              "https://ms.contoso.com/": "12fbdc53-4ff7-48bc-bffa-35bd3ffcd2cf"
             },
             "key4":"value4"
  }
}
```
I'm try to replace the whole endpoints with just the value --> {"https://www.my.website.name":  "12fbdc54-4ff7-48bc-bffa-30bd3gfcd2sf"}

_Originally posted by @nikhil2007rock in https://github.com/microsoft/azure-pipelines-tasks/pull/9338#issuecomment-490460678_

**Comment by SumiranAgg** [comment]
@nikhil2007rock How do you check if the changes have been made? The file changes in runtime, i.e. are you using the transformed file in following tasks?

For example this is what my pipeline looks like:
![image](https://user-images.githubusercontent.com/8316321/57505826-81c31a80-7317-11e9-9bbc-c33b741f8b05.png)
 Before transformation task, cmd task output:
![image](https://user-images.githubusercontent.com/8316321/57505864-ac14d800-7317-11e9-9601-dbc71a17dc06.png)
After transformation cmd task output:
![image](https://user-images.githubusercontent.com/8316321/57505890-c2bb2f00-7317-11e9-97ea-285111f4f654.png)

**Comment by nikhil2007rock** [comment]
@SumiranAgg , I check the result in the deployed web app and the transformation seemed to be unsuccessful. Next, I am trying to add only 1 value instead of the 2 values that are already present in the artifact. Is that supported?

**Comment by SumiranAgg** [comment]
What task are you using this updated package in? Is it App service deploy task? What is the package name you gave in file transform and in deploy task?

Yes single value substitution is supported as well. You could provide an array of values which will be substituted too.

**Comment by nikhil2007rock** [comment]
I've been using the app service deploy task only and the package name that I've given is "**/config.json". All the other values in that file gets transformed except endpoints.

Key : `auth.endpoints`
**Values that I tried**
Value1 : `{"https://URL": "someguid"}`
Value2 : `{"https://URL": "someguid", "https://app.powerbi.com": "https://analysis.windows.net/powerbi/api", "https://api.powerbi.com": "https://analysis.windows.net/powerbi/api"}`

The endpoints are supposed to be transformed in the signalled line in the below snap which is the debug log from the pipeline:
![image](https://user-images.githubusercontent.com/5222165/57508669-bf2ba600-731f-11e9-981a-e5706e733397.png)

**Comment by SumiranAgg** [comment]
What is the File transform task version? You can check it in logs:
![image](https://user-images.githubusercontent.com/8316321/57509487-fb600600-7321-11e9-82ca-8497dff70c9e.png)

**Comment by nikhil2007rock** [comment]
@SumiranAgg , As I told you, I am using App Service Deploy Task(version `4.3.24`) in which I'm using the in-built File and Transform task. I am not able to find the version of in-built File and Transform task in the App Service Deploy Task's debug logs.

**Comment by nikhil2007rock** [comment]
@SumiranAgg / @kmkumaran , I tried using the separate "File Transform" task to test like how you did and it worked. But the inbuilt "File Transform" task in "Deploy App Service Task" doesn't transform `{"x": "y"}` type of a value. Pls help to make it work ASAP.

**Comment by SumiranAgg** [comment]
@nikhil2007rock We have not added new file transform support in app service deploy task. Can you add new file transform task before deploy task? Also it is recommended to use new tasks to deploy to app service viz. Azure Web app, Azure function app, Azure web app container, azure function app container.

**Comment by nikhil2007rock** [comment]
@SumiranAgg , Thank you for your response. I've added this separate task to perform the file transform.

Next, we would love to see the new file transform support on the app service deploy task. Also, as an end user, I would still continue to use the "Deploy App Service Task" as 
1. it has the in-built capability of variable substitutions and file transformation &
2. the "Post deployment action" under this task is one important feature.

**Comment by kmkumaran** [comment]
+ @RoopeshNair to take note of the above feedbacks.

**Comment by SumiranAgg** [comment]
@nikhil2007rock Thanks for the feedback. We will take this into account while future enhancements.
Closing the issue as it is not blocking customer anymore.
