### ISSUE TITLE
Outputting `##[error]` in front of lines in the command line

### ISSUE THREAD

**Issue by alucardu** [microsoft/azure-pipelines-tasks#10345]
## Issue Description

Issue: Outputting `##[error]` in front of lines in the command line

During the Jest test step in my build:
![image](https://user-images.githubusercontent.com/779921/57455141-c3e25280-726a-11e9-868b-2125044eb066.png)

During the Yarn build step in my build:
![image](https://user-images.githubusercontent.com/779921/57455256-0c9a0b80-726b-11e9-9b67-d4b8652c0482.png)

I've changed my Agent to: vs2017-win2016 which resolves the issue.

![image](https://user-images.githubusercontent.com/779921/57472255-4ed44480-728d-11e9-8d0c-346f1cdad88f.png)

**Comment by corppeon** [comment]
We're seeing this logging issue too on our recently created private build agents using Windows 10 VM's - I think it's down to the Windows 10 version.

We don't see this on agents with winver 10.17134 (Apr 18 update)
We do see the issue on agents with winver 10.17763 (Oct 18 update)

**Comment by corppeon** [comment]
The red messages are from output written to stderr

**Comment by bryanmacfarlane** [comment]
I think this was an issue with an interim build of windows.  

@alucardu - does it still repro for you on the vs2019 hosted image?  I think a more recent build went out recently.

**Comment by damccorm** [comment]
@alucardu does this still repro for you? I'm going to close for now, please comment if its still an issue
