### ISSUE TITLE
Bug: File Transform task not working with secret variables

### ISSUE THREAD

**Issue by cannehag** [microsoft/azure-pipelines-tasks#10344]
**Enter Task Name**: File Transform

## Environment
- Azure Pipelines
- Agent - Hosted

## Issue Description

File Transform workes fine, but if the variable is a secret, it ends up as null in the transformed file.

**I just noticed that the same problem exists in the App Service Deploy task when using 'File Transforms & Variable Substitution Options'**

**Comment by cannehag** [comment]
Hi, any update on this issue ?

**Comment by vincentdass** [comment]
@cannehag , Are you referring to `XML` or `JSON` variable substitution?

**Comment by cannehag** [comment]
We are using JSON, I haven't tried if the same problem exists in XML also

**Comment by Ajay-MS** [comment]
@cannehag 

I have just tried JSON variable substitution and able to replace using secret variables. 

Can you share following items in order to understand your scenario :
1. Task Logs 
2. Sample JSON in which you are trying to substitute variable.
3. Variable defined in the release.

In there case difference between variable defined in release and variable in JSON file.

**Comment by cannehag** [comment]
@Ajay-MS Hi and thanks for the reply. I just did a new test according to your findings and there is a bug.
If the secret variable is scoped to 'Release', the transformation works. But if the secret variable is scope to a specific stage, the transformation ends up as **null**

**Comment by Ajay-MS** [comment]
@cannehag 

As per current behaviour, when you change the scope of any secret variable it's value get reset to null value and you again have to set the value of the that secret variable. I will discuss with team on ideology behind this behaviour. 

I can confirm it's not an issue specific to the task. 

Meanwhile, as a workaround whenever you change scope of variable please set value of secret variable again.

**Comment by cannehag** [comment]
@Ajay-MS Thanks, I can accept that it works that way. One thing I think you should mention to the team is that when you change the scope, the UI doesn't change so you have no idea that the value is removed. I should probably be highlighted the same way as when you add a new stage: you get an exclamation icon on the variable tab and the field is marked as error.

**Comment by Ajay-MS** [comment]
@cannehag  

I agree with your feedback, That should be excepted behaviour. I will surely mention it while having discussion with team.

**Comment by Ajay-MS** [comment]
@cannehag 

I had discussion with the team. Following are the outcome of the discussion
-  Any properties corresponding to secret variable changes then reset the variable value. ( Security concern) 
-  UI should give some indication that user have to reset it value. (We have opened an internal bug for this)

Thanks for valuable feedback on this issue. I am closing this thread. Please feel free to reopen if you feel any other related issue.
