### ISSUE TITLE
Azure App Service Deploy - Space in app setting key fails on release

### ISSUE THREAD

**Issue by SamWhitby** [microsoft/azure-pipelines-tasks#10357]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service Deploy (version 4)

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Under the "Application and Configuration Settings" if you specify an app setting with a space in the key the release fails with "Error: BadRequest - Parameter name cannot be empty." Wrapping the key in quotes also does not help.

Enter the value
![image](https://user-images.githubusercontent.com/3334161/57589587-f6e15a80-7578-11e9-8c29-4865846fb717.png)

produces this (which clearly wont work)
![image](https://user-images.githubusercontent.com/3334161/57589607-3c9e2300-7579-11e9-8199-120561e7dccf.png)

Wrapping the key in quotes also doesn't work
![image](https://user-images.githubusercontent.com/3334161/57589799-f9dd4a80-757a-11e9-81a1-6e04dd44f532.png)

you are presented this if you preview it
![image](https://user-images.githubusercontent.com/3334161/57589809-08c3fd00-757b-11e9-9822-e45e165c1066.png)

And throws this error on release (no quotes around key)

![image](https://user-images.githubusercontent.com/3334161/57589687-0f05a980-757a-11e9-9a14-3bb50d3344a5.png)

(with quotes around key)
![image](https://user-images.githubusercontent.com/3334161/57589733-67d54200-757a-11e9-8999-ee00c5d7a35d.png)

**Comment by eaarora-ms** [comment]
Solved in new task : https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureAppServiceSettingsV1
Closing this.
