### ISSUE TITLE
Azure PowerShell v4 task is not setting Azure Context in Linux 

### ISSUE THREAD

**Issue by olandese** [microsoft/azure-pipelines-tasks#10359]
I'm using V4 Preview of the Azure Powershell Taks on a Linux Agent.
My Service Principal endpoint has access to multiple subscriptions, when running on Linux the task does not set the Azure Context subscription according to the Endpoint select subscription.
It works using the same task on Windows with the same endpoint principal.

Digging in the source code I found the windows codebase of the task is calling Set-CurrentAzSubscription, this is not happening for the non-win codebase

**Comment by Ajay-MS** [comment]
@olandese 

I agree with you regarding this issue. We are fixing this issue and will update you once it will be fixed.

**Comment by 20shivangi** [comment]
It is resolved in PR : https://github.com/microsoft/azure-pipelines-tasks/pull/10371

**Comment by olandese** [comment]
When will be this available?

**Comment by Ajay-MS** [comment]
I will get deployment in approx 3 weeks.

**Comment by olandese** [comment]
Ok, thank you! how can I see when it's deployed? My code currently has a fix for this and I want to know when I can remove the workaround :)

**Comment by Ajay-MS** [comment]
@olandese - while executing Azure PS task version 4.*, in logs you will see version 4.0.10 or greater
