### ISSUE TITLE
DotNetCoreCLI task doesn't use the credential provider

### ISSUE THREAD

**Issue by safern** [microsoft/azure-pipelines-tasks#10377]
*Type*: Feature

**Task Name**: DotNetCoreCLI  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure Pipelines -> dnceng/internal/corefx-official

https://dev.azure.com/dnceng/internal/_build?definitionId=283

- Agent - Hosted or Private: 
    
    Any agent

## Issue Description

The DotNetCoreCLI task doesn't use credential provider forcing people to duplicate the feed as a RestoreSource in the csproj and adding a NuGet.config file with the same restore source so that the credential gets plumbed in, into the generated NuGet.config. We needed to do this in our builds because the credential provider is not used: 

https://github.com/dotnet/corefx/blob/d1912344d9f09d6d294aa555c6322ed35ec1cb28/eng/pipelines/corefx-base.yml#L134-L146

cc: @jmyersmsft @ViktorHofer

**Comment by infin8x** [comment]
Thanks for the feature request! As part of [this work](https://github.com/microsoft/azure-pipelines-yaml/blob/users/amullans/artifacts/design/artifacts-in-pipelines.md) we'll be making it possible to use the Credential Provider with a much wider range of NuGet operations and clients, including this scenario.

**Comment by aasim** [comment]
@satbai Can you verify if this works now for DotNetCoreCLIV2 task?

**Comment by satbai** [comment]
@aasim I don't think we have made any changes to the dotnet tasks to enable any cred providers. Can the [NuGet Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) task help with dotnet as well?
