### ISSUE TITLE
DownloadPackageV1 filter ** seems to skip files starting with .

### ISSUE THREAD

**Issue by LasseNisted** [microsoft/azure-pipelines-tasks#10374]
*Type*: Bug

**Enter Task Name**: DownloadPackageV1

## Environment
- Server - Azure Pipelines
- Agent - Hosted
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

For the `Download Package (Preview)` task (`DownloadPackageV1`) for a Universal package a `**` filter is the default:
![image](https://user-images.githubusercontent.com/16150076/57774762-aeae6d80-771b-11e9-97fd-af325dbdf6d4.png)

If the fetched universal package includes files with a '.' as prefix then they are not included in the result.

Clearing the filter results in no files being fetched. The UniversalPackage task seems to work since it does not supply a filter.

**Comment by magleaso** [comment]
This is by design. In order to match a dot file, you should specify `.*`
If you prefer `*` to match dot files without needing to prepend a dot, change dot=true as per [these docs](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/findingfiles.md#matchoptions)

**Comment by LasseNisted** [comment]
It is not clear from the docs and the UI how to insert "dot=true" in the "Files" UI widget. Additionally, it is not clear from the docs that the way to combine filters is with ";". I made it work with the filter: `**/.*;**`.

**Comment by magleaso** [comment]
Ah yes I apologize. I misunderstood the guidance, that documentation is for the task author to change the behavior of the files filter. I'm looking into what it would take to change the behavior of this task

**Comment by magleaso** [comment]
The fix for this is in production

**Comment by LasseNisted** [comment]
Both pipeline task and az cli confirmed to fetch dot-files when using the '**' pattern. Closing
