### ISSUE TITLE
Docker Task:  Remove Image

### ISSUE THREAD

**Issue by bitva77** [microsoft/azure-pipelines-tasks#10378]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  Feature

**Enter Task Name**:  Docker

## Environment
- Server - Azure Pipelines

- Agent - Private

## Issue Description

Is there a Docker task to cleanup/remove the built image?

The way our pipeline works is we build the image, tag the image, push the image and then logout.  Using a private build agent, this leaves images to fill up disk on the server.

I don't see a Docker Task to remove the image from the local build server.  Instead I'm looking at having to run a custom script to find and remove.  Is this correct or am I missing something?

Thanks!

**Comment by azooinmyluggage** [comment]
The task can be used to run a command like

- task: Docker@2
  displayName: 'container prune -f'
  inputs:
    command: 'container prune -f'

Are you trying to just delete the images built and pushed in a specific job? It will be great if you can share the script you are using right now. That will help me how to address the issue you are facing.

**Comment by azooinmyluggage** [comment]
Closing. Please let us know if you are blocked on this.

**Comment by nachiketrss** [comment]
@azooinmyluggage - Since this topic is regarding docker image, did you mean `image prune -f`?
