### ISSUE TITLE
Method ##vso[task.addattachment]value does not work correctly for files in utf-8.

### ISSUE THREAD

**Issue by sinistram** [microsoft/azure-pipelines-tasks#10375]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md
task.addattachment 

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 18

## Issue Description

Method task.addattachment does not work for utf-8. 

```
$outputFile = "$(System.DefaultWorkingDirectory)/test.md"
Add-Content $outputFile  "ТЕСТ"
Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=ТЕСТ;]$outputFile"

```

The result that I have got in summary is: "Ð¢ÐÐ¡Ð¢" while expected text is "ТЕСТ"

**Comment by damccorm** [comment]
What version of Windows are you running?

**Comment by sinistram** [comment]
> What version of Windows are you running?

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299

**Comment by damccorm** [comment]
Could you try setting `agent.retainDefaultEncoding` to true in your pipeline? It might function as a workaround here

**Comment by sinistram** [comment]
> Could you try setting `agent.retainDefaultEncoding` to true in your pipeline? It might function as a workaround here

![image](https://user-images.githubusercontent.com/8999567/58433635-ca712680-80c0-11e9-9860-1b95558ab2c1.png)

It does not help.

**Comment by damccorm** [comment]
@TingluoHuang any idea what could be causing this on the agent? Looks like this isn't related to the encoding bom changes I made.

**Comment by sinistram** [comment]
@TingluoHuang  any news?

**Comment by damccorm** [comment]
@sinistram are you able to confirm that its getting written to the file correctly? Are you able to reproduce this using something other than powershell (e.g. the cmdLine task)?

**Comment by damccorm** [comment]
@sinistram any updates?

**Comment by teh13th** [comment]
@damccorm I have same issue.
I tried various scenarios, below are the results.

### Powershell
**Code:**
```
Write-Host "Current encoding name: $([System.Text.Encoding]::Default.EncodingName)"
Write-Host "Current encoding code page: $([System.Text.Encoding]::Default.CodePage)"
$outputFile = "\\share\test1.md"
Add-Content $outputFile  "ТЕСТ"
Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=ТЕСТ1;]$outputFile"
```
**Output (agent.retainDefaultEncoding = _ANY_):**
```
2019-12-19T12:33:50.5479926Z Current encoding name: Cyrillic (Windows)
2019-12-19T12:33:50.5515646Z Current encoding code page: 1251
```
**Result (agent.retainDefaultEncoding = _ANY_):**
![image](https://user-images.githubusercontent.com/19591070/71174506-68535b00-2276-11ea-9679-5ec202efeda4.png)
File has _1251_ encoding. Release shows content like it _1252_ encoding.

### Windows Command Line
**Code:**
```
chcp
echo ТЕСТ > "\\share\test2.md"
echo ##vso[task.addattachment type=Distributedtask.Core.Summary;name=ТЕСТ2;]\\share\test2.md
```
**Output (agent.retainDefaultEncoding = _false_):**
```
2019-12-19T12:33:51.8535125Z Active code page: 65001
```
**Result (agent.retainDefaultEncoding = _false_):**
![image](https://user-images.githubusercontent.com/19591070/71174717-e9125700-2276-11ea-8dee-2dfa953434ad.png)
File has _UTF8 (65001)_ encoding. Release shows content like it _1252_ encoding.

**Output (agent.retainDefaultEncoding = _true_):**
```
2019-12-19T12:52:41.0493617Z Active code page: 866
```
**Result (agent.retainDefaultEncoding = _true_):**
![image](https://user-images.githubusercontent.com/19591070/71174734-f0d1fb80-2276-11ea-8bfb-8276c05c8245.png)
File has _866_ encoding. Release shows content like it _???_ encoding.

Files: [result.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3983670/result.zip)

**Comment by teh13th** [comment]
@damccorm I also tried to get uploaded file (for "_Powershell + agent.retainDefaultEncoding = true_" scenario) through [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/attachments/get%20release%20task%20attachment%20content).
It is identical to the file that we supplied to "##vso[task.addattachment" command. It is encoded in 1251.

**It looks like Azure DevOps Server reads the file when display it, as if it were encoded in 1252.**

Also, changing localization in web UI does not change anything.

**Comment by teh13th** [comment]
@damccorm any news?

**Comment by damccorm** [comment]
Sorry, was out on holiday so didn't see your last message til now. From your comment:

> I also tried to get uploaded file (for "Powershell + agent.retainDefaultEncoding = true" scenario) through API.
It is identical to the file that we supplied to "##vso[task.addattachment" command. It is encoded in 1251.
It looks like Azure DevOps Server reads the file when display it, as if it were encoded in 1252.

It sounds like this is a UI issue - I'm going to bring in the Build team (who has UI experts) to take a look

**Comment by totkeks** [comment]
@damccorm Any updates on this task? Just came across the same problem with utf8 file content like this `→`.

**Comment by sinistram** [comment]
@totkeks 
We write a ticket to azure devops support and they gave the patch with fix for our internal azure devops. Maybe you should try the same.

**Comment by totkeks** [comment]
Thanks @sinistram, but what do you mean with "internal azure devops"? You mean your team foundation server? or your azure devops organization, e.g. `dev.azure.com/<your-org-name>`?

**Comment by sinistram** [comment]
@totkeks Our TFS.

**Comment by zlweicoder** [comment]
any further feedback about this issue? we also met this issue.

**Comment by SM-Software** [comment]
I am trying the same and getting the same issue as mentioned above

**Comment by SM-Software** [comment]
Can anyone help us with further feedback here!!
Thanks in advance

**Comment by ChernenkoAV** [comment]
This worked for me. (tfs 2017)
Added the agent.retainDefaultEncoding variable to the agent variables page and set it to false.
In powershell scripts (+ I used psql):

$env:PGCLIENTENCODING = "UTF8"
$PSDefaultParameterValues['*:Encoding'] = 'utf8'
$OutputEncoding = New-Object System.Text.UTF8Encoding $False

And for writing to a file, he was reinsured

function addToFile([string] $fileName, [string] $text)
{
     $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
     [System.IO.File]::AppendAllText($fileName, $text, $Utf8NoBomEncoding)
}
