### ISSUE TITLE
FtpUpload fails intermittently with "Error: socket hang up"

### ISSUE THREAD

**Issue by montebhoover** [microsoft/azure-pipelines-tasks#10387]
## Issue Description
The FTP upload task is failing intermittently with a "socket hang up" error.  It errors on a different file each time it fails.  An example looks like:
```
2019-05-15T15:57:16.7006685Z ##[debug]task result: Failed
2019-05-15T15:57:16.7007873Z ##[error]upload failed: /site/wwwroot/_widget18.scss due to error: Error: socket hang up
```
(full debug log attached below)

Are there any best practice recommendations to reduce this?  Using v2 of the FtpUpload task, or uploading files zipped instead of loose?  

This looks related to #7927 (socket hang up in FtpUpload) and maybe #4241 (socket hang up in App Service Deploy), #8066 and #9892 (timeouts in FtpUpload). 

Thanks!

-----------------

*Type*: Bug

**Enter Task Name**: FtpUpload@1

## Environment
Azure Pipelines
Agent: Hosted, "windows-latest"

### Task logs
[log_8_155.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3185860/log_8_155.zip)

**Comment by yacaovsnc** [comment]
Version 2 of FtpUpload task has been released.  This version would auto retry for connection issues.  Please give that a try.

**Comment by montebhoover** [comment]
Thanks!

**Comment by mustafa-korkmaz** [comment]
solve my problem too.

**Comment by mustafa-korkmaz** [comment]
> Thanks!

solved my problem, too

**Comment by mustafa-korkmaz** [comment]
> Version 2 of FtpUpload task has been released. This version would auto retry for connection issues. Please give that a try.

solved my problem, too
