### ISSUE TITLE
Save All Variable group as a json file

### ISSUE THREAD

**Issue by Planche95** [microsoft/azure-pipelines-tasks#10381]
Hi,

I'm playing with Azure Pipelines, and i would like to save all variables from specific, linked variable group to json file. Is this is possible? The variables can grow over time, so I want to do something like:
- Get all for group variable name 
- Loop throught all of them and save as json file

**Comment by damccorm** [comment]
I don't think so. The pattern we follow is that variables within variable groups are treated like normal variables once they're in the task, so there's not anything linking them together.
