### ISSUE TITLE
Android signing step EPERM error on a Windows Server build Agent

### ISSUE THREAD

**Issue by borjapuerta** [microsoft/azure-pipelines-tasks#10390]
The Android signing step currently does not work when running on a build agent.
Although the configuration is fine (I attached a screenshot of it below), I only get the following error-message (debug mode on):

`2019-05-16T10:21:12.9271805Z ##[debug]  D:\Agent3Work\108\s\app\build\intermediates\signing_config (directory)
2019-05-16T10:21:12.9280716Z ##[debug]  D:\Agent3Work\108\s\app\build\intermediates\signing_config\debug (directory)
2019-05-16T10:21:12.9291362Z ##[debug]  D:\Agent3Work\108\s\app\build\intermediates\signing_config\debug\out (directory)
2019-05-16T10:21:12.9341136Z ##[debug]task result: Failed
2019-05-16T10:21:12.9417540Z ##[error]Error: Failed find: EPERM: operation not permitted, stat 'D:\Agent3Work\108\s\app\build\intermediates\signing_config\debug\out\signing-config.json'
2019-05-16T10:21:12.9430214Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Failed find: EPERM: operation not permitted, stat 'D:\Agent3Work\108\s\app\build\intermediates\signing_config\debug\out\signing-config.json'
2019-05-16T10:21:12.9448607Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed find: EPERM: operation not permitted, stat 'D:\Agent3Work\108\s\app\build\intermediates\signing_config\debug\out\signing-config.json'
2019-05-16T10:21:12.9717879Z ##[section]Finishing: Signing and aligning APK`

![image](https://user-images.githubusercontent.com/35364402/57846973-ab77b800-77d5-11e9-8b04-8b0ee098f270.png)

I am using TFS 2018 3.2 and I run the scripts of gradle build on a cmd console to keep the trace. The file that is not found is generated by the agent.

Any ideas?, what is wrong here?

**Comment by hamtiko** [comment]
Hi All,

I have same issue with my private windows agent. 

When I switched to 3rd version or starts using zipalign option I am always getting following error:
`
##[debug]task result: Failed
##[error]Error: Failed find: EPERM: operation not permitted, lstat 'C:\Users\****'
`

After some investigation I found that I can resolve error if I will permanently enter the location of zipalign and apksigner tools in the pipeline:

<img width="550" alt="Screen Shot 2019-08-05 at 19 25 05" src="https://user-images.githubusercontent.com/6923563/62475877-04446480-b7b7-11e9-9252-a381532898ef.png">

After looking to the task's source code I can assume that there is a problem with `findAndroidTool` function which is trying to find a absalute path for zipalign and apksigner tools:

`
const findAndroidTool = (tool: string): string => {
    const androidHome = tl.getVariable('ANDROID_HOME');
    if (!androidHome) {
        throw new Error(tl.loc('AndroidHomeNotSet'));
    }

    // add * in search as on Windows the tool may end with ".exe" or ".bat"
    const toolsList = tl.findMatch(tl.resolve(androidHome, 'build-tools'), tool + '*', null, { matchBase: true });

    if (!toolsList || toolsList.length === 0) {
        throw new Error(tl.loc('CouldNotFindToolInAndroidHome', tool, androidHome));
    }

    return toolsList[0];
};
`
Can someone help to understand what is the issue exactly, is it related to my private agent specifically or there is a bug in above script.

Thanks

**Comment by alexander-smolyakov** [comment]
Hello, @borjapuerta!

Regarding "EPERM: operation not permitted, stat" issue - this error may be triggered by many reasons, at this point, it's difficult to say what exactly triggers this error in your case without additional information. 

Could you please try the steps below?
1) Update your self-hosted agent (You can find instruction for deploying by [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devop)).

2) Check that the `ANDROID_HOME` variable contains a proper path to AndroidSDK. (it should be similar to `C:\Users\{UserName}\AppData\Local\Android\Sdk`).

3) Check permissions - maybe the agent doesn't have enough permission to work with the AndroidSDK folder.

Regarding the `findAndroidTool` function - this function checks that `ANDROID_HOME`  environment variable exists in the system. If it exists, the function takes a path to the folder that exists in variable, searches necessary tool, and returns a full system path for the found tool.  

If you still experience this issue after following these steps - could you please provide the YAML file of your pipeline and attach the capabilities list of your private agent? You can find the capabilities list in your organization settings on [Azure DevOps](https://dev.azure.com/).  The path is: `Settings / Agent pools / {Pool in wich your add your agent} / {Your private agent} and then click on Capabilities button)`.

**Comment by alexander-smolyakov** [comment]
Hello, @hamtiko!

> Can someone help to understand what is the issue exactly, is it related to my private agent specifically or there is a bug in above script?

Regarding the findAndroidTool function - this function checks that `ANDROID_HOME` environment variable exists in the system. If it exists, the function takes a path to the folder that exists in variable, searches necessary tool, and returns a full system path for the found tool, so it doesn't seem to be the issue here...

More likely this is a problem with your private agent. Could you please follow the same steps that I describe for @borjapuerta in the previous message?

**Comment by alexander-smolyakov** [comment]
Hello, @borjapuerta!

Closing now this issue due to a lack of response from you, please feel free to reopen it.
