### ISSUE TITLE
VsTest2 fails to use testAssemblyVer2

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/azure-pipelines-tasks#10397]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account name: tan.nguyen2@hallburton.com, 
Team project: https://dev.azure.com/HalliburtonSandBox/HCT-Romulus
Build: Services

- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016, Agent version 2.144.2

## Issue Description
Task: VSTest2
when I have testAssemblyVer2: '**\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**' 
the build didn't find any test, but when I remove the testAssemblyVer2 part, the build found all the tests.  
Also I was using multi-stage pipeline preview feature.
### Task logs

[buildlog.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3189027/buildlog.zip)

**Comment by prawalagarwal** [comment]
@tannguyen3 Please refer [this](https://github.com/microsoftdocs/vsts-docs/issues/1580) issue for resolution on this. We are in the process of fixing this. Please let us know if the issue is resolved on using YAML block for this input.

**Comment by prawalagarwal** [comment]
@tannguyen3 were you able to unblock your sceanrio?

**Comment by tannguyen3** [comment]
It works, thanks for your help.
