### ISSUE TITLE
Azure Powershell  v4 update ignores 'Latest installed version' setting

### ISSUE THREAD

**Issue by stephens336** [microsoft/azure-pipelines-tasks#10396]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure PowerShell

list here (V# not needed):  4
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure DevOps Services

- Agent - Hosted or Private:  Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017
## Issue Description
An update to v4 version of the task made 18 days ago added validation for the Azure Powershell Version that ignores the 'Latest installed version' setting.

Relevant commit:  https://github.com/microsoft/azure-pipelines-tasks/commit/d631201596e7bdb19fd819781d4ab3cf815e95b6

If Latest installed version is selected and I try to save the build definition, I get this error:
`The pipeline is not valid. Job Job_1: Step input 'CustomTargetAzurePs' with value '' does not satisfy 'isMatch(value, '^[0-9]+\.[0-9]+\.[0-9]+$','Multiline')': Enter valid Azure PowerShell Version`

If I change it to specify the version, then entering 1.0.0 works.

### Task logs
There is no task log.  The error occurs when saving a build definition.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

`The pipeline is not valid. Job Job_1: Step input 'CustomTargetAzurePs' with value '' does not satisfy 'isMatch(value, '^[0-9]+\.[0-9]+\.[0-9]+$','Multiline')': Enter valid Azure PowerShell Version`

**Comment by droessmj** [comment]
I can recreate and further confirm that manually specifying 1.0.0 as the preferred version results in an error of 
Deploy - VS2017: "Run Login-AzureRmAccount to login."

Specifying 2.0.0 as the preferred version results in "Could not find the modules: 'Az.Accounts' with Version: '2.0.0'. If the module was recently installed, retry after restarting the Azure Pipelines task agent." Which would be expected based on the tooltip for the task.

**Comment by 20shivangi** [comment]
It is resolved in this PR : https://github.com/microsoft/azure-pipelines-tasks/pull/10432
