### ISSUE TITLE
Azure File Copy and WinRM cannot complete the operation

### ISSUE THREAD

**Issue by asimnzr** [microsoft/azure-pipelines-tasks#10416]
Hi,

As part of Azure release pipeline, I am trying to Copy MSI installer to a VM using "Azure File Copy" task and getting below error during this process:

> The remote session query failed for syngis-train-01.northeurope.cloudapp.azure.com with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet.

Please note that WinRM service is running and is configured for remote management and exception to firewall settings is also added to inbound rules:
![image](https://user-images.githubusercontent.com/10372429/58003921-56041980-7afb-11e9-81fd-127b7fd45920.png)

Please note that first few steps (downloading MSI and uploading to temporary blob) are working fine - please refer attached log snapshot for details:
![image](https://user-images.githubusercontent.com/10372429/58002890-00c70880-7af9-11e9-8b12-ec149f6dd743.png)

Given below is more detail:

## Environment
- Server - Azure Pipelines 
- Agent - Hosted 2017

Please help.

**Comment by asimnzr** [comment]
I was able to get it working... Please close this issue!

**Comment by coin8086** [comment]
I have the same issue and I wonder how you got passed? @asimnzr #11158
