### ISSUE TITLE
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1 VsTest task failed. 

### ISSUE THREAD

**Issue by IbrahimUmar** [microsoft/azure-pipelines-tasks#10411]
Hi , I have migrated from tfs 2018 to Azure DevOps and getting this error after successful code build.Visual Studio 2017 is installed on Build Machine.

Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1VsTest task failed.
Thank You.
VSTEST is already added in USER CAPABILITIES.

here are logs:

Error: Invalid settings 'RunConfiguration'. Invalid value '.NETFramework,Version=v4.5.1' specified for 'TargetFrameworkVersion'.

##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.

##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1

##[warning]No results found to publish.

##[error]VsTest task failed.

##[section]Finishing: Test Assemblies **\release\*Test*.dll;-:**\obj\**

**Comment by ShreyasRmsft** [comment]
![image](https://user-images.githubusercontent.com/25194518/59016103-2e80b100-885e-11e9-829a-6a268dcdeaae.png)

**Comment by ShreyasRmsft** [comment]
Closing this due to no response. Please feel free to reopen the issue or create a new one with the requested details.
