### ISSUE TITLE
Docker@2 respository name broke with uppercase

### ISSUE THREAD

**Issue by YohskDista** [microsoft/azure-pipelines-tasks#10415]
Hello,

I was updating my Azure Pipeline with the new Docker@2 task and I get an issue with the repository name. I found a similar issue for the Docker@1 task and I think it is a regression. Here is the error message in the azure pipeline log :

***/ServerGateway:'0.1.0.0' -t ***/ServerGateway:'latest' d:\a\1\s\ServerGateway
invalid argument "***/ServerGateway:'0.1.0.0'" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
##[error]C:\Program Files\Docker\docker.exe failed with return code: 125
##[section]Finishing: Build and Push

Here is the link to the related issue #2988. Actually I put the repository name in a lower case variable, it works great but I would be able to use the `$(Build.Repository.Name)` variable like before.

Thank you for your help !

**Comment by ajinkya599** [comment]
Hey @YohskDista. Thanks for reporting this. We are fixing this in Docker@2 task.
In Docker@1, the `Force image name to follow Docker naming convention` checkbox (which is checked by default), solves the problem:

![image](https://user-images.githubusercontent.com/11447401/58531792-2ba01380-8201-11e9-8bbf-25efc30a1a55.png)

**Comment by YohskDista** [comment]
Hello @ajinkya599,
Yes I was using the version 1 before and it was working great. I was thinking to update to version 2 but due to this problem I came back to the previous version. I will wait until the problem is solved.

Thank you for your feedback ! Best regards
