### ISSUE TITLE
NpmAuthenticate should handle paths better

### ISSUE THREAD

**Issue by erik-am** [microsoft/azure-pipelines-tasks#10420]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: NpmAuthenticate  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

The `NpmAuthenticate` task includes an argument `workingFile`. It would be helpful if one could use (environment) variables in this path. Also `~` is not supported.

This snippet:
```yml
      - task: npmAuthenticate@0
        inputs:
          workingFile: ~/.npmrc
```

results in "The .npmrc file you selected at /home/vsts/work/1/s/~/.npmrc does not currently exist.", whereas I would expect the task to look for just `~/.npmrc`.
Trying to use `workingFile: $HOME/.npmrc` instead, yields `/home/vsts/work/1/s/$HOME/.npmrc`, where I would expect `$HOME/.npmrc`

**Comment by zarenner** [comment]
@ericsciple throughout pipelines do we intend to support ~ in inputs like this via the tasklib? We're just using tl.exists, nothing special here.

**Comment by ericsciple** [comment]
@vtbassmatt regarding the feedback.

`$HOME` and `~` are features of the bash shell interpreter.

`$()` is the [variable expansion](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#expansion-of-variables) syntax for Azure Pipelines task inputs. iirc it falls back to env vars (should be `5` in the list) - so `$(HOME)` should work.

**Comment by vtbassmatt** [comment]
Maybe we can doc this better somehow. I don't think the task-lib should be in the business of running shell expansions. It's mildly confusing that you can refer to env vars by using our variable syntax, especially when that syntax means something different in the shell.

**Comment by bryanmacfarlane** [comment]
I think it would be nice.  If it's done, it should probably be the agent that sets `HOME`.  tilda is interesting but the agent could resolve those as well.  But only if it's a file path input ...

**Comment by aasim** [comment]
Will work on getting the docs updated to be clear about using env vars and special chars in paths.
