### ISSUE TITLE
ArchiveFiles: empty files created

### ISSUE THREAD

**Issue by AhmedBM** [microsoft/azure-pipelines-tasks#10422]
**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: ArchiveFiles: empty files created

## Environment
Using Azure Pipelines
- Account name: mscodehub
- Team name: MicrosoftManagementPlatform-Core

Using the Hosted agent in the Hosted Ubuntu 1604 agent pool

## Issue Description

Pointing the _ArchiveFiles_ task on a directory with files only creates an archive with a "b" folder inside. Just for debugging purposes, i executed a bash script with "tree ." as the command with the same _workingFolder_ as the _ArchiveFiles_ _sourceFolder_ and all the files are clearly present, but the _ArchiveFiles_ task doesn't pick them up.

Attached logs
[logs_97217.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3199836/logs_97217.zip)

**Comment by thboop** [comment]
Hey @AhmedBM ,

Could you provide the following information:

- The yaml you are using

From what I see, your pipeline contains the following:

1. Copy Artifacts to Build.ArtifactStagingDirectory
2. Archive Files via a zip file from Build.BinariesDirectory to Build.ArtifactStagingDirectory 
3. Archive Files via a tar.gz file from Builds.BinariesDirectory to Build.ArtifactsStagingDirectory.
4. Publish the tar.gz file generated
5. Publish the zip file generated.

I don't see where you set up files to be in the Build.BinariesDirectory, where do files get populated into that folder?

**Comment by damccorm** [comment]
Closing since we didn't get a response on this. If this is still an issue feel free to comment with the info requested and we can reopen.
