### ISSUE TITLE
VS2019 - Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine

### ISSUE THREAD

**Issue by KaineVarley** [microsoft/azure-pipelines-tasks#10438]
## Required Information
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**
SqlAzureDacpacDeploymentV1

## Environment
**Server**
Azure Pipeline

- **Account Name:** tesgcloud
- **Team Project Name:** Accelerator
- **Release Definition Name:** TMS - DB - CA
- **Release Number:** #4446 (Release-4)

**Agent**
Hosted

- **Agent Queue Name:** Agent-01
- **Agent Host OS:** Windows Server 2016 Standard
- **Agent Version:** vsts-agent-win-x64-2.150.3

**Build Tools**
- **Name:** Visual Studio Build Tools 2019
- **Version:** 16.0.4
- **Workloads**
    - C++ build tools
    - .NET desktop build tools
    - Universal Windows Platform build tools
    - Web development build tools
    - Azure development build tools
    - Office/SharePoint build tools
    - **_Data storage and processing build tools_**
    - Mobile Development with .NET
    - Node.js build tools
    - .NET Core build tools
    - Visual Studio extension development

## Issue Description
This seems to have been an issue resolved in VS2017, see [#4362](https://github.com/Microsoft/azure-pipelines-tasks/issues/4362) and [#4338](https://github.com/microsoft/azure-pipelines-tasks/issues/4338), but looks to have persisted through to VS2019. 

The problem essentially is that the Azure SQL DACPAC Deployment step fails because it is unable to find the `SqlPackage.exe` file with the following error message:

> Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine `<Machine Name>`

Having logged into the build server, I can see that two instances of `SqlPackage.exe` exist:
- C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140\SqlPackage.exe
- C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\SqlPackage.exe

They are versioned `14.0.4009.3` and `15.0.4311.2` respectively.

### Task logs
[ReleaseLogs_2624.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3203440/ReleaseLogs_2624.zip)

### Error logs
(see: Task logs)

**Comment by Ajay-MS** [comment]
Thanks for raising this issue. We have to update detection logic for SQLPackage.exe in order to add support for VS2019.  I will raise PR for the same. 

Meanwhile install DacFx so that you will be unblocked on this issue
[Download DacFx](https://www.microsoft.com/en-us/download/details.aspx?id=58207&WT.mc_id=rss_alldownloads_extensions)

**Comment by Ajay-MS** [comment]
PR -https://github.com/microsoft/azure-pipelines-tasks/pull/10456

**Comment by KaineVarley** [comment]
Thank you.

**Comment by Ajay-MS** [comment]
PR merged it will be deployed in approx 3 weeks.

**Comment by niravlulla** [comment]
is this DacFx available via VS 2019 Extension -> Manage Extensions ?
