### ISSUE TITLE
architecture as an input for UseDotNet and DotNetCoreInstaller task 

### ISSUE THREAD

**Issue by directhex** [microsoft/azure-pipelines-tasks#10439]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreInstallerV0, DotNetCoreInstallerV1, UseDotNetV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
dnceng Azure Pipelines

- Agent - Hosted or Private: 
    
Private agent, agent 2.150.3, Ubuntu 16.04 ARM64

## Issue Description

get_machine_architecture contains the following:

https://github.com/microsoft/azure-pipelines-tasks/blob/08914a70defbdbe73b2bb87e8d0663bdbeb248e0/Tasks/UseDotNetV2/externals/get-os-distro.sh#L159-L178

This is... fundamentally not how `uname` should be used.

1. `uname` refers to the profile of the running kernel, not the executing environment. It can be a 100% mismatch, and that's valid and fine. The .NET Core environment which gets installed needs to match the executing environment, not the kernel.

Some examples:

```
(xenial-armhf)root@xam-softiron-16:/# uname -a
Linux xam-softiron-16 4.15.0-50-generic #54~16.04.1-Ubuntu SMP Wed May 8 15:55:41 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
(xenial-armhf)root@xam-softiron-16:/# file /bin/bash
/bin/bash: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib, for GNU/Linux 3.2.0, BuildID[sha1]=9a214a5bbfe98a862fd835fdcbfa1d9f8dabff0e, stripped
```

```
root@breakfast:/# uname -a
Linux breakfast 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@breakfast:/# file /bin/bash 
/bin/bash: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib, for GNU/Linux 3.2.0, BuildID[sha1]=d3d60e9d8193746d270cd74bcb2f5742ffc65d48, stripped
```

In both these cases, these are 64-bit kernels with 32-bit executing environments. There is no guarantee that 64-bit libraries are available to execute 64-bit code, and it is a 32-bit .NET Core which should be installed.

2. `armv7l` is not the only valid `uname` which requires a 32-bit .NET Core. 32-bit compatibility kernel profile on 64-bit ARM kernels will show `armv8l`:

```
$ uname -a
Linux xam-softiron-15 4.15.0-50-generic #54~16.04.1-Ubuntu SMP Wed May 8 15:55:41 UTC 2019 armv8l armv8l armv8l GNU/Linux
```

### Task logs

```
##[section]Starting: Install .NET Core 3.0 preview
==============================================================================
Task         : .NET Core SDK/Runtime Installer
Description  : Acquires a version of the .NET Core SDK/Runtime from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
Version      : 1.0.1
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/AA4ihfi)
==============================================================================
Tool to install: .NET Core sdk version 3.0.100-preview5-011568.
Found version 3.0.100-preview5-011568 in channel 3.0 for user specified version spec: 3.0.100-preview5-011568
Version 3.0.100-preview5-011568 was not found in cache.
Getting URL to download .NET Core sdk version: 3.0.100-preview5-011568.
Detecting OS platform to find correct download package for the OS.
[command]/home/builder/azdo32/_work/_tasks/DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6/1.0.1/externals/get-os-distro.sh
Primary:linux-x64
Legacy:ubuntu.16.04
Detected platform (Primary): linux-x64
Detected platform (Legacy): ubuntu.16.04
Downloading: https://download.visualstudio.microsoft.com/download/pr/7e4b403c-34b3-4b3e-807c-d064a7857fe8/95c738f08e163f27867e38c602a433a1/dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz
Extracting downloaded package /home/builder/azdo32/_work/_temp/2119e31e-d117-4d60-9b10-dd7df9c7a5c9.
Extracting archive
[command]/bin/tar xzC /home/builder/azdo32/_work/_temp/fdc4cfc2-fa4d-48bb-8b11-af48c7bec6c2 -f /home/builder/azdo32/_work/_temp/2119e31e-d117-4d60-9b10-dd7df9c7a5c9
Successfully installed .NET Core sdk version 3.0.100-preview5-011568.
Prepending PATH environment variable with directory: /home/builder/azdo32/_work/_tool/dotnet
Creating global tool path and pre-pending to PATH.
Prepending PATH environment variable with directory: /home/builder/.dotnet/tools
##[section]Finishing: Install .NET Core 3.0 preview
```

**Comment by jalajmsft** [comment]
Hi @directhex, thank you for describing the scenario in detail, we are investigating this issue. This behavior is a mimick of actual .Net way of SDK installation which can be found [here](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh). We are discussing about it with .Net team.

Meanwhile can you manually install the SDK on the machine from [here](https://github.com/dotnet/core/tree/master/release-notes) and let us know if it works for you. If you want to use a 32 bit 2.2.203 SDK version, download [this](https://download.visualstudio.microsoft.com/download/pr/e5573b57-df74-4b5b-8cd8-06973b66c3ac/b9ee29318ad2d87fa05adfaf74a8271c/dotnet-sdk-2.2.203-linux-arm.tar.gz).

**Comment by bash** [comment]
This is not stale and still an issue on Apple Silicon.

On a Mac Mini, `uname -m` returns `arm64` which is not recognized by `get-os-distro.sh`.
