### ISSUE TITLE
Error deploying from successful build

### ISSUE THREAD

**Issue by chris-stormideas** [microsoft/azure-pipelines-tasks#10443]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Release  

## Environment
- Server - Azure Pipelines
**Account Name**: Chris Canal
**Team Project Name**: Storm-Ideas
**build definition name**: Build and Publish images
**Build Numbers**: 
20190521.8
20190521.9
20190522.1
20190522.2

- Agent - Hosted or Private: 
Host (Hosted VS2017)

## Issue Description
Creating release from a successful build fails to deploy.

![Screenshot from 2019-05-21 22-27-39](https://user-images.githubusercontent.com/44848490/58145568-39a9cf00-7c18-11e9-83b8-a302cd795b01.png)

![Screenshot from 2019-05-21 22-45-58](https://user-images.githubusercontent.com/44848490/58146116-58a96080-7c1a-11e9-98c0-672f05a7e409.png)

![Screenshot from 2019-05-21 22-28-34](https://user-images.githubusercontent.com/44848490/58145634-75449900-7c18-11e9-965d-76f52c8ba389.png)

### Task logs
[Build 20190522.2-BuildAndPublish.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3205461/Build.20190522.2-BuildAndPublish.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Deploy Logs:

> Exception Message: Exception: Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.Artifacts.InvalidRequestException (type ReleaseManagementHandledException)
> Exception Stack Trace:    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.FailOrchestrationImplementation(Int32 releaseId, Int32 releaseStepId, Nullable`1 releaseDeployPhaseId, Action`3 rejectStep, Exception ex) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 243
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.FailOrchestration(Int32 releaseId, Int32 releaseStepId, Nullable`1 releaseDeployPhaseId, Exception ex) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 232
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.InvokeRunner(Release release, ReleaseEnvironmentStep deployStep, ReleaseEnvironment releaseEnvironment, DeployPhaseSnapshot snapshotToProcess, Func`5 runDeployPhase, Action`4 acceptStep, Action`3 rejectStep, Action`4 handleException) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 493
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.ProcessDeployPhasesImplementation(Release release, ReleaseEnvironmentStep deployStep, Func`5 runDeployPhase, Action`4 acceptStep, Action`3 rejectStep, Action`4 handleException) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 122
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.ProcessDeployPhases(Release release, ReleaseEnvironmentStep deployStep) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 70
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.OrchestratorServiceProcessorV2.ExecuteDeployStep(Release release, ReleaseEnvironmentStep releaseEnvironmentStep) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\OrchestratorServiceProcessorV2.cs:line 1149
> Inner Exception Details:
> Exception Message: VS402925: Build ID '20190522.2' is invalid. Make sure that the build ID is valid and try again. (type InvalidRequestException)
> Exception Stack Trace:    at Microsoft.VisualStudio.Services.ReleaseManagement.Artifact.Extensions.Build.BuildArtifact.TryParseBuildId(InputValue versionData, Boolean shouldThrow) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\ArtifactType\Build\BuildArtifact.cs:line 3302
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Artifact.Extensions.Build.BuildArtifact.GetArtifactConfigurationVariables(IVssRequestContext context, ArtifactSource artifactSource) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\ArtifactType\Build\BuildArtifact.cs:line 2401
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.GetArtifactVariables(Release release, IVssRequestContext requestContext) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 378
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.GetMergedReleaseVariables(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentSnapshotDelta deploymentDelta, Boolean includeArtifactVariables) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 581
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.GetAutomationEngineInput(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep step, Int32 t
> Exception: Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.Artifacts.InvalidRequestException

Agent Log:

> ##[Error 1]
> Exception Message: VS402925: Build ID '20190522.2' is invalid. Make sure that the build ID is valid and try again. (type InvalidRequestException)
> Exception Stack Trace:    at Microsoft.VisualStudio.Services.ReleaseManagement.Artifact.Extensions.Build.BuildArtifact.TryParseBuildId(InputValue versionData, Boolean shouldThrow) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\ArtifactType\Build\BuildArtifact.cs:line 3302
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Artifact.Extensions.Build.BuildArtifact.GetArtifactConfigurationVariables(IVssRequestContext context, ArtifactSource artifactSource) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\ArtifactType\Build\BuildArtifact.cs:line 2401
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.GetArtifactVariables(Release release, IVssRequestContext requestContext) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 378
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.GetMergedReleaseVariables(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentSnapshotDelta deploymentDelta, Boolean includeArtifactVariables) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 581
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.GetAutomationEngineInput(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep step, Int32 trialNumber, DeployPhaseSnapshot snapshotToProcess, ReleaseEnvironmentSnapshotDelta deploymentDelta) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 286
>    at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in D:\v2.0\P1\_work\13\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 190

**Comment by Lovakumar** [comment]
@chris-stormideas how are you creating releases from successful build. Is it manual create release dialog and typing in "20190521.8" into combo box? "20190521.8" is a build number but not build ID. You cannot create releases from "build number" but you create them using "build ID - which is an integer".

Recently we have made an enhancement to fail create release API request if the build ID is invalid. That will block you from creating releases if invalid build ID is passed.

You can find build ID of your build from URL parameters. For example: https://dev.azure.com/OrgName/ProjectName/_build/results?buildId=9636341&view=results, **9636341** is the build ID.

**Comment by chris-stormideas** [comment]
Hi @Lovakumar,

Nothing manual was performed, all initiated via the UI and the combo box values being auto selected.

**Comment by Lovakumar** [comment]
@chris-stormideas we have made couple of fixes in this area. Can you please check your scenario and let us know if it still repro-ing for you.

**Comment by Lovakumar** [comment]
@chris-stormideas we have made couple of fixes in this area. I am closing this issue for now. If it is still repro-ing for you, please reply back with repro details and we will re-activate this issue.
