### ISSUE TITLE
dotnet core publish and deploy

### ISSUE THREAD

**Issue by ZombieD** [microsoft/azure-pipelines-tasks#10455]
## Required Information

*Type*: Question

**Enter Task Name**: Command line 

## Environment
- Agent -  Private: Windows 10
## Issue Description

Hello!

I'm trying to publish and deploy a dotnet core project with command line task. I'm using the following command:
```
- script: |
      cd $(Agent.ToolsDirectory)/dotnet
      dotnet publish $(Build.Repository.LocalPath)/$(ProjectName)/$(ProjectName)
      /p:DeployOnBuild=true /p:PublishProfile=$(PublishProfilePath) /p:Password=$(PublishPassword) /p:Username=$(PublishUsername)
  displayName: 'Publish'
```
I tried with dotnet msbuild, with build configuration property but none of them works.

### Error logs

```
Date: 2019-05-22T11:22:16.951Z
  Hash: 3cef4648595c26d14619
  Time: 64650ms
  chunk {0} runtime.aab22d90fb4d2b33a506.js (runtime) 2.25 kB [entry] [rendered]
  chunk {1} common.ab544ad10d41e0f3351f.js (common) 9.97 kB  [rendered]
  chunk {2} es2015-polyfills.01deec5b2033b45aed7c.js (es2015-polyfills) 56.4 kB [initial] [rendered]
  chunk {3} main.c5d2060fdd6d69dbc65d.js (main) 1010 kB [initial] [rendered]
  chunk {4} polyfills.481858ef51fe27531859.js (polyfills) 41 kB [initial] [rendered]
  chunk {5} styles.b48a0a8d2e93459f6365.css (styles) 79.8 kB [initial] [rendered]
  chunk {6} 6.a57bc9d2a45568b73776.js () 104 kB  [rendered]
  chunk {7} 7.4f7ed73f6886d06f3c00.js () 18.4 kB  [rendered]
  chunk {8} 8.57287bd24417d5846191.js () 10.6 kB  [rendered]
  chunk {9} 9.36d3b2b6aa4023652e33.js () 849 bytes  [rendered]
  ProjectName -> C:\Users\ZombieD\Downloads\AzureDevopsAgent\_work\1\s\ProjectName\ProjectName\bin\Debug\netcoreapp2.1\publish\
A fájlnév, a könyvtárnév vagy a kötetcímke szintaxisa nem megfelelő.
```
The last sentence is in hungarian, and it's english meaning is 'The filename, directory name, or volume label syntax is incorrect'

**Comment by vinodkumar3** [comment]
@ZombieD 
Any specific reason to use command line task? You may use DotNetCoreCLI [task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2) for the same. For more info refer [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops).

**Comment by vinodkumar3** [comment]
Any updates?

**Comment by vinodkumar3** [comment]
Feel free to reopen if you still face the issue following the suggested approach.
