### ISSUE TITLE
Task deploy/release through Vsts pipeline

### ISSUE THREAD

**Issue by Yiming-Jia** [microsoft/azure-pipelines-tasks#10459]
Hello,

We're looking for a standing solution for task deploy through Vsts pipeline. Most of the team use Ev2 to deploy services. So we'd like to know if we need to use same way to deploy Vsts task for compliance reason. Also, if it support to use Ev2, do you have a ev2 extension to upload to martketplace? If we don't need to use Ev2 (means there is no compliance requirement), is there a typical way we could do it? 

Thanks,
Yiming

**Comment by sachinma** [comment]
To publish a task to a single organization, you can use [tfx cli ](https://www.npmjs.com/package/tfx-cli) with [upload ](https://www.npmjs.com/package/tfx-cli)command or you can use a [marketplace extension ](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks&targetId=690856c5-f060-436a-b8ba-8693b58cb991). Regarding the compliance requirement, you should consult your team and EV2 team to see if you need Ev2 and if they have an extension. Adding @shashban

**Comment by sachinma** [comment]
@Yiming-Jia does the above answer your query?

**Comment by Yiming-Jia** [comment]
Thanks for following up. We planned to try an Ev2 extension called `Shell Extension` which requires to mount the whole package as well as a deployment script into a compliance environment.
