### ISSUE TITLE
Build Machine Image task deletes template directory

### ISSUE THREAD

**Issue by tj-cappelletti** [microsoft/azure-pipelines-tasks#10458]
## Required Information
*Type*: Bug

**Enter Task Name**: `PackerBuild@1`

## Environment
**Azure Pipelines**
**Organziation**: webstorm
**Team Project**: DevOps
**Build Definition**:  Azure-Pipelines-Agents-Packer-Image-CI
**Build Number**:  310
**Agent Type**: Hosted VS2017

## Issue Description

I noticed that this issue has been logged a few times but it has come back.
#9092
#9289

I'm using the `PackerBuild@1` task in my `YAML` build file and point it to a custom template. After the task runs, I try to copy the template and associated files to the staging directory so I can put them as artifacts of the build. My copy task fails because the directory does not exist. I put a simple PowerShell script before and after the Packer task and found the directory was deleted. When I ran the build with `system.debug` set to `true` I found in the logs it was deleting the template directory. Please let me know if you need more details or any of the source code.

### Task logs

```
packer build completed.
##[debug]Cleaning-up directory D:\a\1\s\images\packer
##[debug]rm -rf D:\a\1\s\images\packer
##[debug]removing directory
##[debug]Cleaning-up directory C:\Users\VSSADM~1\AppData\Local\Temp\1558488527708
##[debug]rm -rf C:\Users\VSSADM~1\AppData\Local\Temp\1558488527708
##[debug]removing directory
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]
```
[Build Logs - All tasks](https://github.com/microsoft/azure-pipelines-tasks/files/3207620/logs_310.zip)

**Comment by jalajmsft** [comment]
Hi @tj-cappelletti thank you for describing the issue in detail and for sharing the build logs. The task version in the log for packer build task is 1.0.0. Unfortunately the issue was fixed in the later versions of the task. Can you try using the latest version 1.0.11 and check if it works.

**Comment by tj-cappelletti** [comment]
@jalajmsft How do you do that with the YAML file? I have it set to `PackerBuild@1`, shouldn't this use the latest version on the hosted agent?

**Comment by jalajmsft** [comment]
@tj-cappelletti  Yes you are correct `PackerBuild@1` should use the latest version of the task. We are doing a hot-fix, it will be available in couple of days. Thanks.

**Comment by jalajmsft** [comment]
@tj-cappelletti We have rolled out the fix for this, can you please re-try and check.

**Comment by sachinma** [comment]
Closing this issue. Please re-open if this still reproduces for you.
