### ISSUE TITLE
DotNetCoreCLI should not default to publishWebProjects or zipAfterPublish. 

### ISSUE THREAD

**Issue by lukeschlather** [microsoft/azure-pipelines-tasks#10469]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

Type: Feature

**DotNetCoreCLIV2**: 

## Issue Description

DotNetCoreCLI should not have publishWebProjects or zipAfterPublish defaulting to true. Both are extremely surprising as a first-time user. The former is outright broken for any projects that don't follow the web convention. (The error message is also extremely unhelpful.) The latter made me waste a couple hours wondering why I was doing a publish but my publish directory was missing.

Obviously this means bumping to version 3 but I think it would be a great change to make the task easier to use. (As it is, all of my publish commands have publishWebProjects: False.)

**Comment by jalajmsft** [comment]
Hi @lukeschlather Thank you for your valuable feedback, its unfortunate you faced those issues. We are working for a solution towards this and will update once the changes have been made.

**Comment by hiyadav** [comment]
Hi @lukeschlather 
We realize that the current web project detection logic has short comings and are thus working to enhance the current task to be able to better identify web projects. 

The new logic will work as a backup when existing logic can't find a web project. It would classify a project as web project if it is using  _Microsoft.NET.Sdk.Web_ as the required sdk for build. That would mean csproj file will contain this: 
<Project **_Sdk="Microsoft.NET.Sdk.Web"_**> 
</rest of the data here>
</Project>
It will be really helpful if you could let us know, if the new logic helps your case ? 

As you have already mentioned that, a new version of the task is required to change default input values, thus we will not be able to make changed in current version.

**Comment by sachinma** [comment]
Adding @pulkitaggarwl to consider this request. Also marking this as enhancement

**Comment by ggirard07** [comment]
@hiyadav regarding the new logic for "Web"project detection, it will still not detect Azure Functions App project...
Those use `Microsoft.NET.Sdk` by default but are definitively to be considered web project as main purpose is to be deployed on Azure!

**Comment by bishal-pdMSFT** [comment]
@hiyadav

**Comment by lukeschlather** [comment]
If it can accurately detect web projects that seems reasonable.

zipAfterPublish is still not helpful, I just got bitten by this again.

**Comment by chris-ray** [comment]
Just wanted to +1 @lukeschlather here. zipAfterPublish true by default? Ridiculous! My colleague and I just spend several hours over multiple days trying to figure out why a pipeline would succeed step-by-step identically on our machines but fail on azure pipeline. No log message anywhere that we could see about the zipping effect. A nuget pack searching for files in the directory failed with "Directory not found" That certainly couldn't be true, the previous step says it created publish directory and put files there... Powershell debug print Powershell debug print Powershell debug print... What... publish.zip?? What's that all abo............. omg...... zipAfterPublish true by default? Who thought of that!?

😄  Added another scar today.
