### ISSUE TITLE
Add 'delete slot' to task 'AzureAppServiceManage'

### ISSUE THREAD

**Issue by mguirao** [microsoft/azure-pipelines-tasks#10477]
## Information

*Type*: Feature

**Enter Task Name**: AzureAppServiceManage

## Description

Task AzureAppServiceManage is able to manage what is deployed on an App Service. I want to be able to delete a slot after doing a swap to production.

**Comment by ArieHein** [comment]
idea is not to remove the slot as that's your "last known working version" for prod for example (I dont use slots on other environments as its a cost issue. If you need to roll back you just swap it again (obviously by using slots, you have properly though about and implemented procedures to revert db changes for example).
Other then that being a simple powershell command if really needed.
