### ISSUE TITLE
Unable to find GitHub service connection in Download GitHub Release task in build pipeline

### ISSUE THREAD

**Issue by avais88786** [microsoft/azure-pipelines-tasks#10484]
Type: Question

Task: **_Download GitHub Release_**

## Environment
- Server - Azure Pipelines
       - Account name: dev.azure.com/avaisuddinmohammad 
       - Project Name : Ionic Angular
       - Build def. name: avais88786.ionic-scheduleme

- Agent - Hosted: 
       - Agent queue name : not sure :-/, it is Hosted VS2017 Agent pool though    

Question: Unable to see created Service Connections (from project settings) in Download Github Release task, its saying '_No existing service connections of the appropriate type could be found_' 
      
![image](https://user-images.githubusercontent.com/9274605/58375900-9d543500-7f55-11e9-95d7-cbada1aab65d.png)

Service connection(s) of type Github configured in project settings using OAuth and PAT and both configured to use '**Allow all pipelines to use this service connection**' :
![image](https://user-images.githubusercontent.com/9274605/58375909-e7d5b180-7f55-11e9-8b2f-3d72634f8a2c.png)

Is there something I am missing that I do not understand in the documentation?
Any help much appreciated.
Avais
p.s. Service connections are of type '**_GitHub_**'

**Comment by Lovakumar** [comment]
@avais88786 can you please check isReady value from https://dev.azure.com/avaisuddinmohammad/Ionic Angular/_apis/distributedtask/serviceendpoints/<ServiceConnectionId>

<ServiceConnectionId> is the GUID that appears in URL when you click service connection from service connections page.

Secondly, you will need to be in USE role of service connection in order to see the connection in drop down.

**Comment by EwanNoble** [comment]
Having the same issue here as well. Our existing service connections have worked fine with the old Github artifacts in release definitions but are not available for the Github Release artifact.

**Comment by avais88786** [comment]
> @avais88786 can you please check isReady value from https://dev.azure.com/avaisuddinmohammad/Ionic Angular/_apis/distributedtask/serviceendpoints/
> 
> is the GUID that appears in URL when you click service connection from service connections page.
> 
> Secondly, you will need to be in USE role of service connection in order to see the connection in drop down.

The Ids match. I havent tried login as user with 'User' role priveleges. Instead I moved the step to Release pipeline and can see the connection there. 

Thanks for the input and help.
