### ISSUE TITLE
Docker Compose Task in Azure DevOps "Couldn't connect to Docker daemon. You might need to start Docker for Windows" Hosted VS 2017

### ISSUE THREAD

**Issue by RoggerFabri** [microsoft/azure-pipelines-tasks#10493]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Docker Compose

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure Pipelines**

Account Name: **teamkyckr**
Team Project Name: **Kyckr-Main**
Build Definition Name: **API Pipeline**
Build Definition Number: **Release-853**

     
- Agent - Hosted or Private:  **Hosted**
    
Agent queue name: **VS2017**

## Issue Description

Task intermittently fails without clear logs. If triggered again, sometimes pass, sometimes fails again.

Message:

9-05-27T13:38:49.4197400Z Couldn't connect to Docker daemon. You might need to start Docker for Windows.
2019-05-27T13:38:49.6208502Z ##[error]Couldn't connect to Docker daemon. You might need to start Docker for Windows.
2019-05-27T13:38:49.6300049Z ##[error]C:\ProgramData\Chocolatey\bin\docker-compose.exe failed with return code: 1
2019-05-27T13:38:49.6390265Z ##[section]Finishing: Build container image

### Task logs

Attached.
[ReleaseLogs_3033.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3224177/ReleaseLogs_3033.zip)

**Comment by icfly2** [comment]
an azure devops I see the same error using the default docker compose task in the release pipelie. Any clue as to what is causing this?

**Comment by icfly2** [comment]
OK, so for me that was actually quite easy:
- make sure the subscription and registry info are correct
- make sure you run on the correct OS (For me that was changing from a hoster VS 2017 agent to and ubuntu agent)

**Comment by RoggerFabri** [comment]
@icifly2

> OK, so for me that was actually quite easy:
> 
> * make sure the subscription and registry info are correct
> * make sure you run on the correct OS (For me that was changing from a hoster VS 2017 agent to and ubuntu agent)

What do you mean by "make sure the subscription and registry info are correct"?

And when you say "make sure you run on the correct OS (For me that was changing from a hoster VS 2017 agent to and ubuntu agent)" looks like you're implying that VS2017 is not an incorrect agent, well, that's not the case, I work for customers that can't use ubuntu agent on this step.

**Comment by bansalaseem** [comment]
We have increased the timeout for docker daemon to start on hosted machines and that should have fixed this issue. Please reopen if you are still running into it.

**Comment by collinbarrett** [comment]
I am seeing this issue today on the hosted Ubuntu agent.

https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=1517
