### ISSUE TITLE
Update Service Fabric Manifests (Docker image settings) doesn't append digest

### ISSUE THREAD

**Issue by dzoech** [microsoft/azure-pipelines-tasks#10503]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricUpdateManifestsV2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ServiceFabricUpdateManifestsV2/Update-DockerImageSettings.psm1#L88

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    https://dev.azure.com/zoechbauer-df/AllReady/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=4
Build Definition Name: AllReady.MVC-Docker container-CI
Build Number: #20190528.7

- Agent - Hosted or Private: 
    Private
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
[2019-05-28 12:30:39Z INFO AgentProcess] Agent is built for Windows - win-x64.
[2019-05-28 12:30:39Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.17134 .
[2019-05-28 12:30:39Z INFO AgentProcess] Version: 2.138.6
[2019-05-28 12:30:39Z INFO AgentProcess] Commit: af817ee4564fbb9fdddc7e2986dafe7bfe3379cc

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Task: Update Service Fabric Manifests (Docker image settings)

The task doesn't append the digest when Image Names Path is not set. This occurs when a repository is set for the image name in the ServiceManifest, e.g.:
`
    <EntryPoint>
      <ContainerHost>
        <ImageName>allreadyacr.azurecr.io/allready.mvc</ImageName>
      </ContainerHost>
    </EntryPoint>
`

![image](https://user-images.githubusercontent.com/29693067/58478215-d1964400-8155-11e9-8596-ca837f95461a.png)

It seems that in the following script the full image name including the repo (allreadyacr.azurecr.io/allready.mvc) is used to select from the mapping. But the mapping index was set to only use the name (allready.mvc). Since I ran the task with system.debug = false, Write-Verbose didn't mentioned the error.

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ServiceFabricUpdateManifestsV2/Update-DockerImageSettings.psm1#L99

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

> ##[debug]Evaluating condition for step: 'Update Service Fabric Manifests (Docker image settings)'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Update Service Fabric Manifests (Docker image settings)
==============================================================================
Task         : Update Service Fabric Manifests
Description  : Automatically updates portions of the application and service manifests within a packaged Service Fabric application.
Version      : 2.4.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820529)
==============================================================================
##[debug]VstsTaskSdk 0.8.2 commit 
##[debug]Entering C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Update-Manifests.ps1.
##[debug]Loading resource strings from: C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\task.json
##[debug]Loaded 41 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 41 strings.
##[debug]Entering Find-VstsFiles.
##[debug] LiteralDirectory: 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2'
##[debug] LegacyPattern: '*.psm1'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\*.psm1'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'True'
##[debug] IncludeDirectories: 'False'
##[debug] Force: 'False'
##[debug]Paths: C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\
##[debug] Assert-SingleItem.psm1
##[debug] Find-FileChanges.psm1
##[debug] Get-VstsBuild.psm1
##[debug] Test-FileEqual.psm1
##[debug] Test-XmlEqual.psm1
##[debug] Update-ApplicationVersions.psm1
##[debug] Update-DockerImageSettings.psm1
##[debug] Update-PackageVersion.psm1
##[debug] Update-ServiceVersions.psm1
##[debug]Leaving Get-MatchingItems.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Assert-SingleItem.psm1'.
##[debug]Exporting function 'Assert-SingleItem'.
##[debug]Importing function 'Assert-SingleItem'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Find-FileChanges.psm1'.
##[debug]Exporting function 'Find-FileChanges'.
##[debug]Importing function 'Find-FileChanges'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Get-VstsBuild.psm1'.
##[debug]Exporting function 'Get-VstsBuild'.
##[debug]Importing function 'Get-VstsBuild'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Test-FileEqual.psm1'.
##[debug]Exporting function 'Test-FileEqual'.
##[debug]Importing function 'Test-FileEqual'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Test-XmlEqual.psm1'.
##[debug]Exporting function 'Test-XmlEqual'.
##[debug]Importing function 'Test-XmlEqual'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Update-ApplicationVersions.psm1'.
##[debug]Exporting function 'Update-ApplicationVersions'.
##[debug]Importing function 'Update-ApplicationVersions'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Update-DockerImageSettings.psm1'.
##[debug]Exporting function 'Update-DockerImageSettings'.
##[debug]Importing function 'Update-DockerImageSettings'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Update-PackageVersion.psm1'.
##[debug]Exporting function 'Update-PackageVersion'.
##[debug]Importing function 'Update-PackageVersion'.
##[debug]Loading module from path 'C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Update-ServiceVersions.psm1'.
##[debug]Exporting function 'Update-ServiceVersions'.
##[debug]Importing function 'Update-ServiceVersions'.
##[debug]Total found: 9
##[debug]Leaving Find-VstsFiles.
##[debug]INPUT_UPDATETYPE: 'Docker image settings'
##[debug]Entering Update-DockerImageSettings.
##[debug]INPUT_IMAGEDIGESTSPATH: 'C:\agent-vsts\_work\3\a\dockerImageDigests.txt'
##[debug]Entering Find-VstsFiles.
##[debug] LegacyPattern: 'C:\agent-vsts\_work\3\a\dockerImageDigests.txt'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'C:\agent-vsts\_work\3\a\dockerImageDigests.txt'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'True'
##[debug] IncludeDirectories: 'False'
##[debug] Force: 'False'
##[debug]Path: C:\agent-vsts\_work\3\a\dockerImageDigests.txt
##[debug]Leaving Get-MatchingItems.
##[debug]Total found: 1
##[debug]Leaving Find-VstsFiles.
##[debug]INPUT_APPLICATIONPACKAGEPATH: 'C:\agent-vsts\_work\3\a\applicationpackage'
##[debug]Entering Find-VstsFiles.
##[debug] LegacyPattern: 'C:\agent-vsts\_work\3\a\applicationpackage'
##[debug] IncludeDirectories: 'True'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'C:\agent-vsts\_work\3\a\applicationpackage'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'False'
##[debug] IncludeDirectories: 'True'
##[debug] Force: 'False'
##[debug]Path: C:\agent-vsts\_work\3\a\applicationpackage
##[debug]Leaving Get-MatchingItems.
##[debug]Total found: 1
##[debug]Leaving Find-VstsFiles.
##[debug]INPUT_IMAGENAMESPATH: 'C:\agent-vsts\_work\3\s'
##[debug]Entering Find-VstsFiles.
##[debug] LegacyPattern: 'C:\agent-vsts\_work\3\s'
##[debug]Entering Get-MatchingItems.
##[debug] IncludePatterns: 'C:\agent-vsts\_work\3\s'
##[debug] ExcludePatterns: ''
##[debug] IncludeFiles: 'True'
##[debug] IncludeDirectories: 'False'
##[debug] Force: 'False'
##[debug]No paths.
##[debug]Leaving Get-MatchingItems.
##[debug]Total found: 0
##[debug]Leaving Find-VstsFiles.
##[debug]No digest found for image 'allreadyacr.azurecr.io/allready.mvc'.
##[debug]Leaving Update-DockerImageSettings.
##[debug]Leaving C:\agent-vsts\_work\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.4.2\Update-Manifests.ps1.
##[section]Finishing: Update Service Fabric Manifests (Docker image settings)
`

**Comment by sachinma** [comment]
You are right that the current code assumes that the service manifest only contains the image name and not the container registry name. This was the behavior of VS tooling when generating the service manifest files. We will update the logic to work even if the full name is specified in the service manifest. In the meantime, can you update the service manifest to just contain the image name to unblock yourself

**Comment by vineetmimrot** [comment]
Fix will be available by next few weeks.
