### ISSUE TITLE
How can I install the win-x86 flavor of .NET runtime with the DotNetCoreInstaller@0 task?

### ISSUE THREAD

**Issue by clguiman** [microsoft/azure-pipelines-tasks#10505]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DotNetCoreInstaller

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    Azure Pipeline 

- Agent - Hosted or Private: 
    
    Private

## Issue Description

The .NET Core installer taks doesn't provide a way to specify the platform, so on windows it always picks win-x64. Is there a way I can tell the task to install win-x86?

### Task logs

> Tool to install: .NET Core sdk version 2.2.102.
>[command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta ->NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& >'E:\A\_work\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5->176b752bfea6\0.2.2\externals\get-os-platform.ps1'"
>Primary:win-x64
>Detected platform (Primary): win-x64

**Comment by sachinma** [comment]
@clguimanMSFT this should depend on the agent process. You can install 32 bit agent - and then the installation of the runtime will be 32 bit. This is currently not possible if the agent is 64 bit

**Comment by hiyadav** [comment]
@clguimanMSFT did you get unblocked with the information provided above by Sachin ?

**Comment by clguimanMSFT** [comment]
@hiyadav I was unblocked in the sense I didn't have to try out different configurations. 
Maybe it's a good idea to convert this into a feature request if you think it's worth having - it sure would have simplified my build definition.

**Comment by hiyadav** [comment]
@clguimanMSFT that's right, there can be an option in the task for architecture. We have added the tag enhancement, so we consider it in the future while planning updates/feature release in the task.

**Comment by bender2k14** [comment]
> ...this should depend on the agent process. You can install 32 bit agent - and then the installation of the runtime will be 32 bit. This is currently not possible if the agent is 64 bit

Are all the [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) 64-bit agents?

If I run `dotnet --info` when using the [pool](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool) with VM image label `windows-2019`, then the [RID](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) is `win10-x64`.

**Comment by hiyadav** [comment]
@bender2k14 
This looks to be the case. I'll try confirming that from the agent management team. 
It will take use sometime to pick up the feature work, so if you're blocked on this, you can try 
1. You can install the required version using this script, it takes architecture as an input. https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1 
2. setting up a private agent with the right OS requirements and the use the task on the agent to get appropriate version.

**Comment by bender2k14** [comment]
Thanks for the suggestions @hiyadav.

I am deploying to `win-x86`, but my (unit) tests work for any platform, so my work around was to remove the runtime identifier from the tests (which means the tests have to restore NuGet packages and build the code again...I was just trying to optimize the build by not repeating those steps).
