### ISSUE TITLE
DownloadPipelineArtifact latest should use latest successful

### ISSUE THREAD

**Issue by cannehag** [microsoft/azure-pipelines-tasks#10514]
**Bug**  
*Type*: DownloadPipelineArtifact should use latest successful build

**Enter Task Name**: here  DownloadPipelineArtifact

## Environment
- Azure Pipelines
    
- Agent - Hosted

## Issue Description

When using DownloadPipelineArtifact and buildVersionToDownload=latest, this task is using a current running build of the pipeline. I would suggest that it would pick the latest successful build, or at least have the option of selecting latestSuccessful as version. Right now, this task crashes if there is a running pipeline which still haven't produced an artifact

**Comment by wyrdfish** [comment]
I am having this issue also, the error is slightly misleading too "##[error]Could not find any pipeline artifacts in the build."

**Comment by fadnavistanmay** [comment]
Hi @cannehag , @wyrdfish - we have merged the change for this issue, and it should be fixed in the next agent version.

Thanks,
Tanmay

**Comment by fadnavistanmay** [comment]
Closing this issue. Confirmed the fix works. Feel free to reopen if you are still facing this. Thanls.
