### ISSUE TITLE
Support for PackerBuildV1 on Azure DevOps Server

### ISSUE THREAD

**Issue by PleaseStopAsking** [microsoft/azure-pipelines-tasks#10537]
Will the PackerBuildV1 task be supported in Azure DevOps Server in the near future? I have a hard requirement in the use of on-prem install and we currently utilize managed disks for all deployments so we "need" V1 to be able to use the task as managed disks are not supported in V0.

**Task Name**: PackerBuildV1

**Comment by sachinma** [comment]
This will be released in the Update 1 of the Server 2019. 

Also as FYI, you can choose to use [tfx cli](https://www.npmjs.com/package/tfx-cli) to add the task manually to your current server version. To build the task, you can clone the repo and build the task from releases/m153 branch by using "node make.js build --task PackerBuildV1" command.
