### ISSUE TITLE
Dynamic dependent pick list creation for task.json in TFS build task

### ISSUE THREAD

**Issue by imdkanikamahajan** [microsoft/azure-pipelines-tasks#10533]
I have two fields in my TFS build task:- 1) States and 2)Cities
I need to populate corresponding cites in drop-down list when a particular state is selected. What changes need to be done in task.json file to get this implemented?

**Comment by damccorm** [comment]
I don't think we enable this behavior right now, docs on this are here - https://github.com/Microsoft/azure-pipelines-extensions/blob/0437e1b000985d1151cd625cc19e77f3a26c2aa6/docs/authoring/endpoints/dataSources.md#parameters

I'm not 100% sure though, you might be better off logging an issue in that repo (I think they own this functionality)
