### ISSUE TITLE
Package and deploy helm tasks fails if Destination folder is not present.

### ISSUE THREAD

**Issue by jikuma** [microsoft/azure-pipelines-tasks#10538]
Task: Package and deploy Helm charts
Version: 0.*

Package and deploy helm tasks fails if the Destination folder is not present during the execution of package command. 
Tasks like download artifacts create a folder if it's not present, I think helm tasks should do the same.

**Comment by lindhe** [comment]
Do you get the error message "Error: stat /home/vsts/.helm/repository/local: no such file or directory"?

**Comment by bansalaseem** [comment]
@vithati can you please take it up?

**Comment by wu-yafeng** [comment]
> Do you get the error message "Error: stat /home/vsts/.helm/repository/local: no such file or directory"?

I get same error

**Comment by vithati** [comment]
Fixed the issue. https://github.com/microsoft/azure-pipelines-tasks/pull/11794
