### ISSUE TITLE
Feature request: CopyFilesV2 task option to copy files only if newer

### ISSUE THREAD

**Issue by ejjpi** [microsoft/azure-pipelines-tasks#10555]
## Required Information
**Question, Bug, or Feature?**  
*Type*:  Feature Request

**Enter Task Name**: CopyFilesV2

## Environment
- Server - Azure Pipelines

## Issue Description

Currently, when copying directories containing a huge amount of files, the CopyFiles task can take several minutes to complete. My request is to introduce a new option to optimize copy by verifying if file is newer (o by checksum?) in the target destination in order to reduce execution time and avoid unnecessary copying.
Is there any workaround available for the time being?

**Comment by moswald** [comment]
@ejjpi One workaround would be to use a powershell task and `xcopy /D`.

**Comment by ejjpi** [comment]
Good point @moswald, seems like /D parameter did the trick!
Although I still think an integrated option in the pipeline copy task would be a better solution.
