### ISSUE TITLE
"Requested feature is not available in resource group" while creating App Service using ARM.

### ISSUE THREAD

**Issue by alucardu** [microsoft/azure-pipelines-tasks#10558]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure Deployment:Create Or Update Resource Group action on Customers

## Environment
- Server - Azure Pipelines
      
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

I am trying to create a `App Service` through a ARM template:

      {
          "type": "Microsoft.Web/serverfarms",
          "apiVersion": "2016-09-01",
          "name": "embracecustomers",
          "location": "[resourceGroup().location]",
          "sku": {
              "name": "F1",
              "capacity": 1
          },
          "tags": {
              "displayName": "embracecustomers"
          },
          "properties": {
              "name": "embracecustomers"
          }
      },

### Task logs

    2019-06-01T12:39:06.6341267Z ##[error]BadRequest: {
    "Code": "BadRequest",
    "Message": "Requested feature is not available in resource group Customers. Please try using a different resource group or create a new one.",
    "Target": null,
    "Details": [
        {
        "Message": "Requested feature is not available in resource group Customers. Please try using a different resource group or create a new one."
        },
        {
        "Code": "BadRequest"
        },
        {
        "ErrorEntity": {
            "ExtendedCode": "59324",
            "MessageTemplate": "Requested feature is not available in resource group {0}. Please try using a different resource group or create a new one.",
            "Parameters": [
            "Customers"
            ],
            "Code": "BadRequest",
            "Message": "Requested feature is not available in resource group Customers. Please try using a different resource group or create a new one."
        }
        }
    ],
    "Innererror": null
    } undefined

I've tried different types of Agents. And my Customers resource group is also empty.

**Comment by sachinma** [comment]
@alucardu this error is coming from Azure App Service resource provider. I could find following link on searching: https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-intro#limitations. If this is not the case with you, it would be best to raise it on Azure App Service forums to understand the reason for this failure

**Comment by alucardu** [comment]
Thank you for the suggestion. Currently in trying to deploy a Windows app on a Windows agent and there are no other apps in the resource. I've created a free account to test the deployment of a small react app using ARM and it works there. So it looks like a setting in my other resource.

I am not the admin of the resource so maybe that's an issue.

**Comment by sachinma** [comment]
Can you create another resource group and try the deployment there? If you are not an admin on the resource group, could there be a Linux app in that resource group. Again, app service team will be able to help you if this doesn't help.
Also from Azure DevOps side, the choice of the agent would not matter. Both windows/Linux agents can deploy either a windows or Linux app service since the task is using ARM rest apis.

**Comment by sachinma** [comment]
Closing this issue as per above. Please follow up with the Azure team. Another way for you to validate the template is to use template deployment feature in Azure portal: https://portal.azure.com/#create/Microsoft.Template
