### ISSUE TITLE
ServiceFabricUpdateManifestsV2 does not update ImageOverrides with the correct docker settings

### ISSUE THREAD

**Issue by GregMialon** [microsoft/azure-pipelines-tasks#10556]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricUpdateManifestsV2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/7e2d65456791dd520f9840c656a8df292b2cd65a/Tasks/ServiceFabricUpdateManifestsV2/Update-DockerImageSettings.psm1#L86

## Environment
- Azure Pipelines

## Issue Description

Service Fabric allows overriding the Image Name depending on the target OS of the node being deployed - this is available by adding different images in the ImageOverrides node of the Application Manifest XML.

The current implementation of the ServiceFabricUpdateManifestsV2 updates the Image name in the ServiceManifest with the correct tag, however, it does not update the ImageOverrides

**Comment by bishal-pdMSFT** [comment]
@GregMialon this feature has not been asked by any other user till now. We are looking into this to see how we can support it.
I am trying to understand how you plan to use this feature in a build pipeline. A build will run on one OS and will create container image according to that. But if imageOverrides needs image for two different OS version (say 1709 and 1809), how will task update both the image names?
Do you have a sample build definition of how you plan to use this task if we added requested feature?

**Comment by vinodkumar3** [comment]
@GregMialon please provide requested info so that we can proceed further with requested feature.

**Comment by GregMialon** [comment]
@bishal-pdMSFT we do not yet have the build definition - but our plan was to build using multiple phases using different agent with the different OS
- Phase 1 - build image on agent with OS version 10.0.17763 (Windows Server Core 2019)
- Phase 2 - build image on agent with OS version 10.0.14393 (Windows Server Core 2016)
- Phase 3 - Update SF package by applying  the image override for each target OS version

One way we could achieve this is:
- Supporting a parameter that lets the task know if it is update the ImageOverride instead of the Image
- Support a parameter that lets the task know what OS version it is targeting
- Use the docker image digest (one file per build/phase above) to add the appropriate image name

This is just at a high level how I could see this working :)

**Comment by bishal-pdMSFT** [comment]
Phase 1 and Phase 2 will create and publish images but they will create their own image digest files. How will phase 3 access those files to update the manifest?

**Comment by GregMialon** [comment]
They would be pushed as artifact and downloaded at the beginning of Phase 3 onto the agent executing it. The task would be called once with the digest from phase 1 specifying the OS version targeted in phase 1, and a second time with the digest file from phase 2 specifying the OS version used in phase 2
