### ISSUE TITLE
.netcore project DOES NOT compiles in AzureDevOps with Hosted Ubuntu 1604 Agent But it does get compile with VS2019 Agent

### ISSUE THREAD

**Issue by Farzad-Jalali** [microsoft/azure-pipelines-tasks#10551]
## Required Information

I got an asp.netCore 2.1 WebApi which compile locally and on the cloud with the "hosted VS2019 agent"
But it doesn't get compile when I use Linux agent (Hosted Ubuntu 1604 Agent )

I want to deploy it to the linux server eventually, so I need to compile it for Linux.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Build (.net core)

 
## Environment
 Azure Pipelines 
Using a Hosted Ubuntu 1604 Agent 
    
  
 account name:
https://berryworldgroup.visualstudio.com/BerryWorld.Services.Mdm

Build definition:
https://berryworldgroup.visualstudio.com/BerryWorld.Services.Mdm/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=229&view=Tab_Tasks

**Failed Sample:
Hosted Ubuntu 1604**
https://berryworldgroup.visualstudio.com/BerryWorld.Services.Mdm/_build/results?buildId=12416&_a=summary

 **Successful: (but windows compile instead of Linux compile)
Hosted Windows 2019 with VS2019**
https://berryworldgroup.visualstudio.com/BerryWorld.Services.Mdm/_build%2Fresults?buildId=12414&_a=summary

## Issue Description

the same project that compiles on windows agent, doesn't get compile on Linux (Ubuntu) agent 
![image](https://user-images.githubusercontent.com/3695669/58708433-b32b8500-83af-11e9-878e-3ab6cad2e631.png)

### Task logs

logs with system.debug and diagnose set true
here is tall the logs:
[logs_12416.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3241413/logs_12416.zip)

 
### Error logs
CSC : error CS0016: Could not write to output file '/home/vsts/work/1/s/src/Berryworld.Services.Mdm.Api/bin/Release/netcoreapp2.1/BerryWorld.Services.Mdm.xml' -- 'Could not find a part of the path '/home/vsts/work/1/s/src/Berryworld.Services.Mdm.Api/bin/Release/netcoreapp2.1/BerryWorld.Services.Mdm.xml'.' [/home/vsts/work/1/s/src/Berryworld.Services.Mdm.Api/BerryWorld.Services.Mdm.Api.csproj]
    213 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.90
##[debug]Exit code 1 received from tool '/usr/bin/dotnet'
##[debug]STDIO streams have closed for tool '/usr/bin/dotnet'
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[debug]which '/usr/bin/dotnet'
##[debug]found: '/usr/bin/dotnet'
##[debug]which '/usr/bin/dotnet'
##[debug]found: '/usr/bin/dotnet'

![image](https://user-images.githubusercontent.com/3695669/58708929-ecb0c000-83b0-11e9-8972-ef3dbad3eaf8.png)

**Comment by joshmgross** [comment]
@Farzad-Jalali are you using one of the tasks or is this just using `dotnet` from the command line?

**Comment by Farzad-Jalali** [comment]
@joshmgross  - thanks for your message.
I'm using the build task, here are two screenshots , (the whole pipeline, and the details of the task that is failing)

![image](https://user-images.githubusercontent.com/3695669/58717783-e7a93c00-83c3-11e9-9005-7047360b4e62.png)

![image](https://user-images.githubusercontent.com/3695669/58717884-2a6b1400-83c4-11e9-9fec-2f47de0dcc62.png)

**Comment by ArieHein** [comment]
hmm What does it matter where you want to deploy it to eventually ?
.net core is .net core
its the same on Linux as it is on Windows as long as you stick to .net core namespaces

The differences between the agents is more to do with using tools you're more comfortable wit...if that's PowerShell, run it on a windows agent, if its python and bash and youre more comfortable using it on Linux machine, use Linux agent...

The only other difference is that not all steps work on all agents, the common ones do, so no fear.
IF there is a step you run on Windows agent it will use PowerShell underneath, if its a Linux agent it will run JavaScript.

I have found sometimes that the build itself runs faster on an ubuntu agent then a windows one, but its very dependent on the code.

**Comment by vinodkumar3** [comment]
Hi @Farzad-Jalali  
I'm agreed with @ArieHein, you may use any agent to generate built artifacts irrespective of the server on which you have to deploy. Go ahead with the Hosted Windows 2019 agent and let us know if it doesn't work (along with debug logs of failed task).

**Comment by vinodkumar3** [comment]
@Farzad-Jalali 
Feel free to reopen if artifacts generated by Hosted Windows 2019 agent doesn't work for you.
