### ISSUE TITLE
KubernetesV1 creating secret also runs extra command that generates error

### ISSUE THREAD

**Issue by Tra5is** [microsoft/azure-pipelines-tasks#10565]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesV1

## Environment
- Server - Azure Pipelines 

Error build
https://dev.azure.com/lgmdevops/Security/_build/results?buildId=33784&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3

Good build
https://dev.azure.com/lgmdevops/Security/_build/results?buildId=33792&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3

- Agent - Private: 
Windows 10 1903

## Issue Description

Documentation states the task should be used like this to create a secret:
    - task: Kubernetes@1
      displayName: secretType generic with literal values
      inputs:
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: $(azureResourceGroup)
        kubernetesCluster: $(kubernetesCluster)
        command: apply
        arguments: -f mhc-aks.yaml
        secretType: generic
        secretArguments: --from-literal=contoso=5678
        secretName: mysecretkey

Reviewing the output from the task shows that it is attempting to run a second command after creating the secret.

PS > \ProgramData\chocolatey\bin\kubectl.exe create secret generic signing-cert --from-file=./deploy/signingcert.pem
secret/signing-cert created
PS > \ProgramData\chocolatey\bin\kubectl.exe apply -o json
error: must specify one of -f and -k
##[error]C:\ProgramData\chocolatey\bin\kubectl.exe failed with return code: 1

Removing the 'command' allows the task to complete successfully. 

Perhaps we need a 'secret' command?

### Task logs

failed logs attached
[12_Create k8s signing cert secret.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3249601/12_Create.k8s.signing.cert.secret.txt)

**Comment by wiruzman** [comment]
This also happens when the command is apply. I tried different combinations with use configuration and  with file or inline script. Nothing is working. This bug has been stale since June 19. We are trying to deploy the secrets through the task. We cannot use a file for it, because it is a secret. 

Can you prioritize this one?

**Comment by span** [comment]
This is still an issue for the create command. I can confirm that removing the command entry in the yaml still executes the command, but only once and successfully.

**Comment by sheldonhull** [comment]
I ran into this today as well. Just wanted to create the secret but the final result after it did create errors due to this command.

**Comment by runerys** [comment]
I ran into this and peeked into the source code for a solution.

If you set `secretName`, it runs the "create secret" command.
If you ALSO set the command to "create", it runs this as well. 

Skipping the `command` task argument and only set `secretName` (plus the other secret arguments) worked for me.

Startup logic:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/src/kubernetes.ts#L60

The secret-module runs create secret:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/src/kubernetessecret.ts#L85
