### ISSUE TITLE
UseDotNet fails to install .NET Core runtime 1.0.11 on Ubuntu 16.04

### ISSUE THREAD

**Issue by AArnott** [microsoft/azure-pipelines-tasks#10560]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1340&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description

The agent already has .NET Core runtime 1.0.11 installed, but once I use `UseDotNet` once I need to install *all* the runtimes my pipeline requires. So I run UseDotNet to try to install 1.0.11 but it reports:

> ##[error]Download URL for .Net Core runtime version 1.0.11 could not be found for the following OS platforms (rid): linux-x64,ubuntu.16.04

Besides that it's preinstalled on the agent, more evidence that the download URL exists is that it is found on this page: https://dotnet.microsoft.com/download/dotnet-core/1.0
Specifically, the link it can't find is: https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-1.0.11-linux-ubuntu-16.04-x64-binaries

**Comment by vinodkumar3** [comment]
@AArnott 2.* version is in preview state and is breaking in this scenario. For the time being please use 0.* task version.
@hiyadav to take a look on the issue with 2.* task version.

**Comment by AArnott** [comment]
Thanks! I didn't realize `@2`was preview. I'll definitely try `@0`

**Comment by vinodkumar3** [comment]
Feel free to reopen the issue if 0.* version doesn't work.

**Comment by hiyadav** [comment]
Hey @AArnott 

We had done the fix to successfully get download url for 1.0.* versions, via this PR: #10265 . It should be available to you by next week.

The UseDotNet Task, installs the version at a location defaulted to "Agents.ToolsDirectory". When dotnet cli is invoked, it will be using the one installed via the task.
In linux, dotnet cli doesn't resolve all the installed versions on the system but only the versions which are installed at the path where dotnet cli is running. Hence, all the other pre-installed versions can't be accessed. For now you will have to install the versions required.
We are however looking at a way to enable users to just ensure that the given version is present.

**Comment by AArnott** [comment]
Thanks. I don't mind installing each version I need. It's good to have my yml file declarative of every dependency rather than assume the host agent has some pre-installed.

**Comment by AArnott** [comment]
So I tried `UseDotNet@0` and that fails for me because on Linux if I run it multiple times, only the last one "sticks", apparently because each version is installed in a unique directory and .NET Core will only explore one directory. `UseDotNet@2` may fix _that_ aspect, but since it can't find the .NET Core runtime/sdk to install (which this issue tracks) that doesn't work either.

Is there some way to get unblocked?

**Comment by AArnott** [comment]
I can't even allow the linux agent's preinstalled .NET Core versions work for me because of #10635.

**Comment by hiyadav** [comment]
Hey @AArnott,
Our deployment is in progress and the updated task shall reach you by week's end or monday.
Meanwhile you can use this script to download the version on linux agent. https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh

**Comment by AArnott** [comment]
Thanks. I suspect that's the same as the https://dot.net/v1/dotnet-install.sh script that [I started using yesterday](https://github.com/AArnott/Nerdbank.Streams/blob/3796430666841e72f133759ecc7d18ae7fd65066/azure-pipelines/install-dependencies.yml#L11-L31). I use `UseDotNet@2` for acquiring .NET Core 1.x on non-Linux, and the dotnet-install.sh script on Linux. Once your deployment is complete, I'll try removing my workaround and see if it works. 🤞

**Comment by hiyadav** [comment]
Hey @AArnott , can you verify if the scenario works for you now !

**Comment by AArnott** [comment]
It works! Thanks.
