### ISSUE TITLE
Azure Devops PSGallery pipeline hangs

### ISSUE THREAD

**Issue by apobekiaris** [microsoft/azure-pipelines-tasks#10578]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShellV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=2279

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Hosted VS2017
https://dev.azure.com/eXpandDevOps/eXpandFramework/_admin/_AgentQueue?_a=agents&queueId=3

## Issue Description

This super simple pipeline compiles a dotnet stand solution binary cmdlet and along and publish the powershell module to PSGallery. It worked fine for months and for no apparent reason since I did no changes it always hungs after these messages.

>VERBOSE: Performing the operation "Publish-Module" on target "Version '2.9.10' of module 'XpandPosh'".
WARNING: Tag list exceeded 4000 characters and may not be accepted by some Nuget feeds.

no idea why it complains about a 4000 chars limit. At least my ps module tag list is not even 100 chars. In addition if I run the same script from my local machine it publishes with no issues.

### Task logs

##[section]Starting: Release
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.148.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
Generating script.
Formatted command: . 'd:\a\1\s\Azure-pipeline.ps1' ***
========================== Starting Command Output ===========================
##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\db586680-6d81-412b-8c2f-f66b0ac93f2d.ps1'"

    Directory: D:\a\1\s\XpandPosh\Cmdlets

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         6/5/2019   9:06 AM                bin                                                                   

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for D:\a\1\s\XpandPosh\Cmdlets\src\XpandPosh.Cmdlets\XpandPosh.Cmdlets.csproj...
  Installing NuGet.Versioning 4.2.0.
  Installing NuGet.Frameworks 4.2.0.
  Installing NuGet.Packaging.Core.Types 4.2.0.
  Installing NuGet.Packaging.Core 4.2.0.
  Installing NuGet.Configuration 4.2.0.
  Installing MimeSharp 1.0.0.
  Installing System.Runtime.CompilerServices.Unsafe 4.5.2.
  Installing NuGet.Packaging 4.2.0.
  Installing Newtonsoft.Json 12.0.1.
  Installing PowerShellStandard.Library 5.1.0.
  Installing NuGet.Protocol.Core.Types 4.2.0.
  Installing DynamicExpressions 1.1.0.
  Installing PowerShellAsync 0.1.0.
  Installing NuGet.Common 4.2.0.
  Installing JetBrains.Annotations 2019.1.1.
  Installing System.Threading.Tasks.Extensions 4.5.2.
  Installing System.ValueTuple 4.4.0.
  Installing SmartFormat.NET 2.4.2.
  Installing Dynamitey 2.0.9.136.
  Installing NuGet.Protocol.Core.v3 4.2.0.
  Installing System.Reactive 4.1.3.
  Installing Octokit 0.32.0.
  Installing morelinq 3.1.0.
  Installing Fasterflect.Netstandard 1.0.9.
  Installing Enums.NET 2.3.2.
  Installing ImpromptuInterface 7.0.1.
  Generating MSBuild file D:\a\1\s\XpandPosh\Cmdlets\src\XpandPosh.Cmdlets\obj\XpandPosh.Cmdlets.csproj.nuget.g.props.
  Generating MSBuild file D:\a\1\s\XpandPosh\Cmdlets\src\XpandPosh.Cmdlets\obj\XpandPosh.Cmdlets.csproj.nuget.g.targets.
  Restore completed in 15.49 sec for D:\a\1\s\XpandPosh\Cmdlets\src\XpandPosh.Cmdlets\XpandPosh.Cmdlets.csproj.
  XpandPosh.Cmdlets -> D:\a\1\s\XpandPosh\Cmdlets\bin\XpandPosh.Cmdlets.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:14.61
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 
'False'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 
'False'; IsRegistered = 'True'.
VERBOSE: Publish Location:'https://www.powershellgallery.com/api/v2/package/'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.1 because it is not included in the list of permitted 
versions.
VERBOSE: Loading module from path 'D:\a\1\s\XpandPosh\Cmdlets\bin\XpandPosh.Cmdlets.dll'.
VERBOSE: Loading module from path 'D:\a\1\s\XpandPosh\XpandPosh.psm1'.
VERBOSE: Module 'XpandPosh' was found in 'D:\a\1\s\XpandPosh'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.1 because it is not included in the list of permitted 
versions.
VERBOSE: Loading module from path 
'C:\Users\VssAdministrator\AppData\Local\Temp\1038031364\XpandPosh\Cmdlets\bin\XpandPosh.Cmdlets.dll'.
VERBOSE: Loading module from path 'C:\Users\VssAdministrator\AppData\Local\Temp\1038031364\XpandPosh\XpandPosh.psm1'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 
'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/items/psscript' and 
PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 
'https://www.powershellgallery.com/api/v2/items/psscript/FindPackagesById()?id='XpandPosh'' for ''.
VERBOSE: Total package yield:'0' for the specified package 'XpandPosh'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 
'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='XpandPosh'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'XpandPosh'.
VERBOSE: Performing the operation "Publish-Module" on target "Version '2.9.10' of module 'XpandPosh'".
WARNING: Tag list exceeded 4000 characters and may not be accepted by some Nuget feeds.
##[error]The operation was canceled.
##[section]Finishing: Release

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by brent-robinson** [comment]
I'm also seeing my pipeline hanging when using `Publish-Module`. My pipeline running inside an Ubuntu 18.04 container on a hosted Ubuntu 16.04 agent. Interestingly when I move it outside the container it works.

**Comment by apobekiaris** [comment]
>when I move it outside the container it works
@brent-robinson how u did this?

**Comment by brent-robinson** [comment]
I was running inside a container job, similar to [this definition](https://github.com/brent-robinson/azure-devops-container-jobs-example/blob/master/azure-pipelines-6.yml). Once I switch to running on the agent instead of inside the container, it worked. Not sure if there were other factors.

**Comment by FISHMANPET** [comment]
I may have had something similar happen to me, in my case I was just using Publish-Module to publish to a filesystem repository within the build agent (so I get could get the nupkg file) and it would hang.  I obviously had to manually register my PSrepository, but then I also had to register it with nuget.exe:
```nuget.exe sources Add -Name LocalPSRepo -Source $env:BHBuildOutput```
I'm running in a MS hosted agent which I believe is a container so it could be a similiar situation to what @brent-robinson experienced.

So you could try `nuget.exe sources Add -Name PSGallery -source https://www.powershellgallery.com/api/v2` before you do your publish and see if that properly registers the repository?

**Comment by apobekiaris** [comment]
and the problem come back for me, psgallery is becoming untrustworthy source for distributing our work. Our clients depend on it and we cannot publish. Can someone have a look at this problem?

**Comment by apobekiaris** [comment]
>WARNING: Tag list exceeded 4000 characters and may not be accepted by some Nuget feeds.

and hangs

all my projects use this module and cannot build

**Comment by apobekiaris** [comment]
it looks that this is unrelated to devops at all, powershellget automatic tags all exported function and hangs when u go over 4000 characters can be avoided by `SkipAutomaticTags` on publish-module
