### ISSUE TITLE
Getting internal server error. Cannot use artifactory

### ISSUE THREAD

**Issue by estatic** [microsoft/azure-pipelines-tasks#10577]
Trying to access to dev.azure.com, getting:
![image (6)](https://user-images.githubusercontent.com/1957771/58955601-19941700-87a5-11e9-8c68-468cd1b24334.png)

Also, since yesterday we cannot sometimes install libraries from artifactory to databricks. Error is: artifact not found.

**Comment by joshmgross** [comment]
@estatic Are you using the Artifactory extension? (https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-artifactory-vsts-extension&ssr=false#overview)

If so, https://github.com/jfrog/artifactory-vsts-extension may be the right place for this issue.

This repository is for the built-in tasks for Azure DevOps, we don't do anything directly with Artifactory
