### ISSUE TITLE
UsePythonVersion task: py launcher not finding Python in Windows

### ISSUE THREAD

**Issue by altendky** [microsoft/azure-pipelines-tasks#10583]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UsePythonVersion

Despite Python version 3.7-32 being available:
`3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]`
https://dev.azure.com/altendky/romp-on/_build/results?buildId=5103&view=logs&jobId=9152c890-b13a-5dcf-02bc-20826ef06b61&taskId=75136766-7d34-5159-048a-2410619f087f&lineStart=16&lineEnd=16&colStart=1&colEnd=77

`py` reports it is not:
`Requested Python version (3.7-32) not installed`
https://dev.azure.com/altendky/romp-on/_build/results?buildId=5103&view=logs&jobId=9152c890-b13a-5dcf-02bc-20826ef06b61&taskId=7de5f011-ed58-5cb4-1e17-6bf68d774ea1&lineStart=14&lineEnd=14&colStart=1&colEnd=48

This worked previously.

**Comment by brcrista** [comment]
Thanks, this was a regression.  It's been fixed.

**Comment by altendky** [comment]
Thanks!
