### ISSUE TITLE
Project fails in private build, but succeeds on VS2017 hosted

### ISSUE THREAD

**Issue by btpence** [microsoft/azure-pipelines-tasks#10599]
*Type*: Bug?

**Enter Task Name**: Visual Studio Build

## Environment
Azure Pipelines
    
    
Account:  celestialsoftware
Project: Celestial
Build Celestial- Desktp
Build number: 20190606.43

- Agent - Hosted and Private
    
    - If using Hosted agent, provide agent queue name:
                          VS2017

    - If using private agent, provide the OS of the machine running the agent and the agent version:    
Windows 10, Agent 2.150.3

## Issue Description

Project builds correctly as hosted build, but not on private build.  On private built, it just seems to skip through the "Visual Studio Build" step.  No errors that I can find, just doesn't do anything.  I've check everything I know to check and can't figure this out.  Help!

Private pool:
![image](https://user-images.githubusercontent.com/44478307/59067301-de621880-8876-11e9-90f1-835fc88bed20.png)

Hosted pool:
![image](https://user-images.githubusercontent.com/44478307/59067397-284afe80-8877-11e9-8915-bf26830b6288.png)

### Task logs

[logs_83.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3263561/logs_83.zip)

**Comment by btpence** [comment]
I tested a private build on a second almost identical machine with success!
Both Windows 10 with Visual Studio 2017 Community, exact same build according to vswhere.

Clearly something environmental or privileged related, but what?

**Comment by azureDaveOps** [comment]
We would need logs to dig deeper, we were unable to reproduce.
