### ISSUE TITLE
build failed on Azure DevOps CI for Microsoft.Bcl.Build.Tasks.dll 

### ISSUE THREAD

**Issue by snehaljadhavgit** [microsoft/azure-pipelines-tasks#10602]
## Note  
Project build failed on Azure DevOps CI for Microsoft.Bcl.Build.Tasks.dll which builds successfully at local

This error I get while building an android and iOS source code on a pipeline. But it builds successfully local Visual Studio MAC. I have tried clean build and pushed the code again by restoring packages.
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: When I take a pull from TFS and builds the then it throws the same error. But after deleting the package folder and opening the solution again it builds fine. I'm using Eclipse for MAC to check-in the source code. 

## Environment
- Server - Azure Pipelines .
    
    - If using TFS on-premises, provide the version: TFS version is 14.134.0.201804261733.
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Hosted private Refer build number-20190607.9
   - Builds successfully on local Visual Studio for MAC

- Agent -Hosted private with VS2017
    ## Issue Description

## Troubleshooting
Tried deleting the package folder and checked in the source code. It gives missing package error for that.

### Error logs
Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(97,5): Error MSB4062: The "EnsureBindingRedirects" task could not be loaded from the assembly D:\a\3\s\ACI_GPS\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll. Could not load file or assembly 'file:///D:\a\3\s\ACI_GPS\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Process 'msbuild.exe' exited with code '1'

**Comment by damccorm** [comment]
Hi, this repo is for tasks issues - would you mind logging your issue here where it can get picked up by the appropriate team? https://developercommunity.visualstudio.com/spaces/21/index.html
