### ISSUE TITLE
Setup.exe installation

### ISSUE THREAD

**Issue by Naidul** [microsoft/azure-pipelines-tasks#10600]
Hi Team,
I am trying to install setup.exe using Powershell DSC. 
I tried with passing different Arguments like /s /v /q 

I am getting the following error:The return code -2147213312 was not expected. Configuration is likely not correct.

Please find the below configuration file :

Node ElevateServerSetUp
           {                         Archive ElevateServerSetUp
                    {
                        Path = "C:\elevate\ELV999-AGS\64-bit Package\Elevate_PS90_server_x64\Elevate_PS90server_x64.zip"
                        Destination = "C:\SetupFile"
                        Ensure = "Present"
                        Force = $True
                    } 
                       Package ElevateServerInstall
                    {
                    Name = "ELEVATE_PS 9.0 Server(x64)"
                    DependsOn = "[Archive]ElevateServerSetUp"
                    Ensure = "present"
                    ProductId = ""
                    Path = "C:\SetupFile\Elevate_PS90server_x64\setup.exe"
                    Arguments = "/quiet"
                    }
             }
  } 
 
Please help me to resolve the above issue..

Kind Regards,
Naidu

**Comment by chshrikh** [comment]
@Naidul could you please share more details like -

1) which task are you using to execute this DSC script
2) Is it possible for you to share the debug logs for your build/release. You can get this by setting the 'system.debug' variable with value as 'true' into your release/build definition
3) Have you tried to run this DSC script manually, did it work ?

**Comment by Naidul** [comment]
Here I am not using VSTS or anything else.I am using Azure Automation to run the configuration files.

**Comment by chshrikh** [comment]
@Naidul this is not the right forum for this question. Could you please post it to correct forum. Please see if below links helps you to find the correct forum -

1) https://github.com/azureautomation
2) https://github.com/PowerShell
