### ISSUE TITLE
Deploy using : sqlQuery -verbose option not work

### ISSUE THREAD

**Issue by rootbdfy** [microsoft/azure-pipelines-tasks#10614]
## Required Information

Hello, I try "deploy using : sqlQuery" runned on deployment group. When I use -Verbose option, I get error: " ##[error]The term '-Verbose' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

*Type*: Bug

## Environment
- Server Azure DevOps server
- Agent  Private: win2016, Agent.Version 2.1442
    
## Issue Description

[Include task name(s), screenshots and any other relevant details]
![изображение](https://user-images.githubusercontent.com/18612349/59243177-4b7b0280-8c17-11e9-8b94-fcd7ffeb979f.png)

### Task logs

##[error]The term '-Verbose' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

**Comment by 20shivangi** [comment]
@rootbdfy 
We are not able to reproduce the issue.
Please attach your debug logs here : RM_Customer_Queries@microsoft.com
