### ISSUE TITLE
can't set build variable and use it in the next task 

### ISSUE THREAD

**Issue by oleksabor** [microsoft/azure-pipelines-tasks#10626]
*Type*: Bug

**Enter Task Name**: powershell 

## Environment
- Server - Azure Pipelines
accountName: quipu-cwnet
teamProjectName: tools
buildDefinition/Number: DirectClientDataSync/azure-pipelines.yml #20190611.4

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted Windows 2019 with VS2019

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows server 2012 R2, 2.152.1

## Issue Description

Can't use build variable that has been set in the previous step. There is no variable value defined in the second step of the same job. This is for both hosted and private agents

First step output is 

> ##[debug]Processed: ##vso[task.setvariable variable=versionFromFile]0.7.3
> fv=0.7.3 versionFromFile=
> ##[debug]$LASTEXITCODE is not set.

but the second step fails to get `$versionFromFile` variable

### Task logs

[logs_1590.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3276860/logs_1590.zip)

## Troubleshooting

````
steps:
- powershell: |
   $fv = Get-Content versionFile
   Write-Host ("##vso[task.setvariable variable=versionFromFile]$fv")
   Write-Host ("fv=$fv versionFromFile=$versionFromFile")
  displayName: 'version from file'   
  
- powershell: |
   if ([string]::IsNullOrEmpty($versionFromFile)) { Throw New-Object System.ArgumentException([string]::Format("failed to read version")) }
````

### Error logs
````
failed to read version
At D:\a\_temp\8548ae07-0f82-4602-a993-e92e33ffae5f.ps1:2 char:50
+ ... romFile)) { Throw New-Object System.ArgumentException([string]::Forma ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : failed to read version
````

**Comment by JohannesDrexler** [comment]
There is a difference in how powershell variables and pipelinevariables are used. this `$versionFromFile` is a powershell variable and this `$(versionFromFile)` is a pipelinevariable (you need this in the second step).

**Comment by oleksabor** [comment]
Thank you for a hint, I've lost in variables

`if ([string]::IsNullOrEmpty($env:versionFromFile))` works properly. I can access to the `$(versionFromFile)` pipeline variable from the powershell using `$env:` prefix
