### ISSUE TITLE
##[error]System.IO.IOException: There is not enough space on the disk.

### ISSUE THREAD

**Issue by gercheq** [microsoft/azure-pipelines-tasks#10632]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  Copy Publish Artifact

  
 
## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://raklet-git.visualstudio.com/raklet-git/_build/results?buildId=2577

System.IO.IOException: There is not enough space on the disk.
--
  | System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'LocalPath' because it is null.
 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: https://raklet-git.visualstudio.com/raklet-git/_build/results?buildId=2577
 
## Issue Description

System.IO.IOException: There is not enough space on the disk.
--
  | System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'LocalPath' because it is null.
 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[section]Starting: Copy Publish Artifact: drop
==============================================================================
Task         : Copy and Publish Build Artifacts
Description  : [DEPRECATED] Use the Copy Files task and the Publish Build Artifacts task instead
Version      : 1.0.32
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613725)
==============================================================================
Preparing task execution handler.
Executing the powershell script: d:\a\_tasks\CopyPublishBuildArtifacts_1d341bb0-2106-458c-8422-d00bcea6512a\1.0.32\CopyPublishBuildArtifacts.ps1
**\Raklet.Crm.zip
**\Raklet.Backend.zip
**\Application.zip
**\Raklet.Login.zip
**\Raklet.Admin.zip
**\Deployment.Scripts\*.ps1
**\web*.config
**\Raklet.UI.Test\bin\**)
Preparing artifact content in staging folder d:\a\1\a...

Copying all files from d:\a\1\Raklet.Api.zip to d:\a\1\a\drop\Raklet.Api.zip
Copying all files from d:\a\1\Raklet.Crm.zip to d:\a\1\a\drop\Raklet.Crm.zip
Copying all files from d:\a\1\Raklet.Backend.zip to d:\a\1\a\drop\Raklet.Backend.zip
##[error]System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.TeamFoundation.DistributedTask.Task.Internal.Core.FileCopyHelper.CopyItem(String sourcePath, String targetPath, Boolean overwrite, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.DistributedTask.Task.Internal.CopyBuildArtifactCmdlet.ProcessRecord()
##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'LocalPath' because it is null.
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[error]PowerShell script completed with 2 errors.
##[section]Finishing: Copy Publish Artifact: drop

**Comment by damccorm** [comment]
Hi, this task has been deprecated and we're not pushing fixes to it. My recommendation would be to switch to use the copy files task and publish build artifacts task instead.

With that said, it seems like the issue you're running into is that you don't have enough space to do the copy you're trying. My recommendation there would be to use a larger private agent with more memory.
