### ISSUE TITLE
UseDotNet@2  `performMultilevelLookup: true` doesn't work on Linux or OSX

### ISSUE THREAD

**Issue by AArnott** [microsoft/azure-pipelines-tasks#10635]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: account: andrewarnott, team project: OSS, 

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: `Ubuntu 16.04` and `macOS 10.13`

## Issue Description

From [this build](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1383&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb) we see use of the `UseDotNet@2` task running on Windows, Mac, and Linux. Only Windows actually lists all the SDKs both preinstalled on the agent and installed with `UseDotNet` in the logs. The linux and mac agents only show the ones explicitly installed.

**Comment by hiyadav** [comment]
Hey @AArnott ,

Multi-Level lookup only works on Windows systems. This feature is not implemented in .Net Core for any other OS.

You will have to install all the required versions via task for Linux and OSX (mac).

**Comment by AArnott** [comment]
OK, thanks.
