### ISSUE TITLE
KubernetesManifest: container image substitution not fully correct

### ISSUE THREAD

**Issue by DJLemkes** [microsoft/azure-pipelines-tasks#10646]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: KubernetesManifest@0  

## Environment
- Server: Azure Pipelines
- Agent: Hosted, Ubuntu

## Issue Description

Container image substitution in manifest files contains bug that causes the match to be too greedy. Result is that unexpected images are being deployed. Example and proposed fix is provided in #10643 

### Task logs
None

## Troubleshooting
None

### Error logs
None

**Comment by ds-ms** [comment]
Closing this issue as the PR has been merged.
