### ISSUE TITLE
Support python3.8 in UsePythonVersionV0

### ISSUE THREAD

**Issue by ijl** [microsoft/azure-pipelines-tasks#10640]
## Required Information
**Question, Bug, or Feature?**  
*Type*: feature

**Enter Task Name**: UsePythonVersionV0  

## Environment
Hosted, all OS.

## Issue Description

`UsePythonVersionV0` supports up to Python 3.7, and Python 3.8 is now going through beta process for a release in October. This ticket is to request Python 3.8, either the final version, or preferably a pre-release. The latest release as I write is beta 1, which is feature-complete and suggested to be used for testing: https://www.python.org/downloads/release/python-380b1/

### Error logs
```
Version spec 3.8 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /opt/hostedtoolcache:
2.7.16 (x64)
3.4.8 (x64)
3.5.7 (x64)
3.6.8 (x64)
3.7.3 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
```

**Comment by madhurig** [comment]
Please follow this issue https://github.com/microsoft/azure-pipelines-image-generation/issues/905. The task will have support when the Hosted VMs start installing python 3.8.
