### ISSUE TITLE
Using path environment variables on windows image in bash task problematic

### ISSUE THREAD

**Issue by csuhj** [microsoft/azure-pipelines-tasks#10653]
Bug/Enhancement
Azure Pipelines, hosted agent

I am using a 'window-latest' vmImage for my hosted pipeline agent and trying to use the bash task to run some scripts.  However, when I use some of the predefined variables containing paths I ran into problems.  For example the `System.DefaultWorkingDirectory` variable returned something like `d:\a\s\1`, but then when used from within bash the backslashes got removed (as they were treated like escape chars) and I ended up with the path `d:as1`.

I ended up resorting to a sed script to convert the Windows path to a POSIX one:

```yaml
    - bash: |
        working_dir=$(echo "$(System.DefaultWorkingDirectory") | sed 's/\\/\//g' | sed 's|\([a-zA-Z]\):|/\1|')
        cd $working_dir/Subdir
        ./scripts/run_tests.sh
```

Would it be possible for the bash task to recognise env. vars that are paths and convert them to a POSIX-friendly version in this circumstance - to save the nasty regex?

**Comment by thboop** [comment]
Hey @csuhj ,

This is an enhancement we have been considering.

For your particular use case, you may be able to do:

```
- bash: |
  cd Subdir
  ./scripts/run_tests.sh
```

**Comment by anoff** [comment]
Please plan it :) Or at least add a note into the docs of the Bash task that it does not properly work with Path variables.
It took me quite a while to figure out it's not my own fault.

**Comment by magic2** [comment]
We use this approach:
```
AgentTempDir="$(Agent.TempDirectory)"
echo "AgentTempDir: $AgentTempDir. Normalize path according to the OS."
AgentTempDir=$(echo "$AgentTempDir" | sed -e 's|\\|\/|g' -e 's|^\([A-Za-z]\)\:/\(.*\)|/\L\1\E/\2|')
echo "Normalized AgentTempDir: $AgentTempDir"
```
It lets us to convert `d:\a\1\s` to `/d/a/1/s`, for example.

It of course doesn't help when the agent is a Windows one, and that "normalized" path must be used in some environment variable later on.

**Comment by martingalvan-nordic** [comment]
Why is this closed? This is an undocumented bug that still exists and hasn't been fixed yet.

**Comment by thomasnal** [comment]
The bug still exists in year 2023. Cannot create pipelines for win/lin/mac strategies without writing each individually. Shame.

**Comment by ericyew** [comment]
yes, this bug still exists. Can't reference $(Build.ArtifactStagingDirectory)\file.tgz correctly on windows agent.

**Comment by justdemon** [comment]
I encounter the same bug. This bug should not be closed.
