### ISSUE TITLE
PublishBuildArtifacts creates multiple artifacts

### ISSUE THREAD

**Issue by fdeschamps-rms** [microsoft/azure-pipelines-tasks#10667]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishBuildArtifacts  

## Environment
Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/fdeschamps/sdp/_build/results?buildId=1231&view=results

- Agent - Hosted: 
    Hosted Ubuntu 1604

## Issue Description
I currently have several pipelines that update a context json file that is passed between stages and jobs. The basic flow is that a job will update the json file, then invokes PublishBuildArtifacts to store it (calling DownloadBuildArtifacts at the beginning of each job). This flow used to work as i would expect (the same artifact is simply updated with the new json) but after a recent release the behavior changed and now i get a release object marked in the ui for each upload. Functionally the code still works as it did before (when i call DownloadBuildArtifacts only the latest one is present), but this makes the ui to be misleading (and prevents me from downloading any of the artifacts which is a bigger problem). 

In addition, the release pipeline appears to believe the fact there are multiple artifacts now, since all of them are now downloaded when i run a release. However, as before, only the latest one appears to be in use. 

I have attached a sample azure pipeline yaml file that reproduces the issue, as well as logs from the task that i ran and screenshots of the issues. 

[pipeline.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3295168/pipeline.zip)
[azure-pipelines.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3295174/azure-pipelines.txt)

**Comment by azureDaveOps** [comment]
The fix is in, we will be starting rollout to production this week.  Thanks for reporting the issue!
