### ISSUE TITLE
Download Build Artifact Timing Out

### ISSUE THREAD

**Issue by SJHarrison1992** [microsoft/azure-pipelines-tasks#10669]
Hello -

My Azure DevOps is hosted and my build agents are installed on a google cloud VM 
I've had this build working for over a year, but last week I noticed it started failing due to one of my 'Download Build Artifacts commands'

It's the same artifact that is causing the issue each time

Last week it was intermittent where some would be okay and others would fail, but this week it is always failing

The error shown is as follows;

`` artifacts-engine: unhandled rejection error: connect etimedout 13.107.6.175:443
unhandled: connect etimedout 13.107.6.175:443
unhandled: connect etimedout 13.107.6.175:443
artifacts-engine: unhandled: connect etimedout 13.107.6.175:443
exit code 7 returned from process: file name
'C:\VSTSBuildAgent\BuildAgent02\externals\node\bin\node.exe', arguments '"C:\VSTSBuildAgent\BuildAgent02\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.153.1\main.js"'. 

**Enter Task Name**: Download Build Artifact

## Environment

Azure Pipeline

Agent - Private Agent - Windows Server 2016

**Comment by gykuma** [comment]
Hi @SJHarrison1992 , we recently updated the task (version 0.153.3) with few fixes. Please let us know if the issue still exists for you.

**Comment by SJHarrison1992** [comment]
Issue appears to be fixed, thank you
