### ISSUE TITLE
Task to write build result to GitHub comment

### ISSUE THREAD

**Issue by datapythonista** [microsoft/azure-pipelines-tasks#10665]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: pandas-dev/pandas

- Agent - Hosted or Private: Hosted

## Issue Description

Once a PR is open, and after the CI runs, it would be nice to be able to post the result of the builds as a GitHub comment.

See for example here, how  the GitHub application `pep8speaks` posts a comment with the result of their validations: https://github.com/pandas-dev/pandas/pull/26894

Couldn't find a task for that, and it's not possible to write a custom script, since accessing the GitHub API directly would require an authentication token (PR builds can't access secret variables, so we can't store the token).

Is it possible to do this? Can it be implemented as a task?

**Comment by tarrenj** [comment]
I'm also looking for this.

**Comment by ds-ms** [comment]
You could use this task: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubCommentV0

**Comment by datapythonista** [comment]
> You could use this task: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubCommentV0

That task doesn't have documentation, so it's difficult to tell for sure. But the task is to write a github comment, and that's not the main issue, the main issue is to access the results of all the jobs in the build.

**Comment by ds-ms** [comment]
The task takes the contents as an input. You could draft the contents of the jobs using output variables, in most of the cases I presume.

**Comment by mloskot** [comment]
AFAIU, that task is available via Azure DevOps UI, see https://stackoverflow.com/a/66810491/151641
