### ISSUE TITLE
Add Yarn and YarnTool support

### ISSUE THREAD

**Issue by plisy** [microsoft/azure-pipelines-tasks#10675]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: YarnTool (new tool)

## Environment
Hosted

## Issue Description

YarnTool just like DotNetCoreInstaller or NodeTool to install Yarn (https://yarnpkg.com/en/) on build machines.

Additionally having a Yarn task that would work just like Npm task.

The reason for supporting Yarn is it's significantly more reliable on larger deployments within Azure DevOps and easier to manage in regards to lock files.

**Comment by damccorm** [comment]
Hi, I don't think we're going to do this at this time. Note that you can install yarn by running `npm install yarn -g`

I'm going to close since this is a no-op, please comment if you'd like me to reopen
