### ISSUE TITLE
##[error]Bash exited with code '1'.

### ISSUE THREAD

**Issue by texnokot** [microsoft/azure-pipelines-tasks#10680]
Created bash task to run the command with arguments and it runs successfully, but pipeline fails with the message:
`##[error]Bash exited with code '1'.`

Task is following:
`  - bash: anchore-cli --json --url $(anchorServer) --u $(anchorUser) --p $(anchorPassword) evaluate check $(acrRegistry)/$(imageRepository):$(tag) --detail > image-policy.json
      displayName: Scan for the policy violations and save the report image-policy.json
      continueOnError: true`

Task runs and produces report. However, pipeline fails with error randomly. Sometimes, it runs successfully, sometimes comes back with `##[error]Bash exited with code '1'.`
Agent is MS hosted agent Ubuntu.

**Comment by bryanmacfarlane** [comment]
That means that sometimes anchore-cli has a return code of 1.  the bash task simply reports the return code of the script that is run.

**Comment by geopayme** [comment]
This error continues to show up in the Trustwallet 

Check failure on line 160 in Build log
```

@azure-pipelines
azure-pipelines
/ trustwallet.assets

Build log #L160
Bash exited with code '1'.
```
`Test "blockchains" folder › Check Ethereum side-chain folders › Test chain ethereum folder

    Custom message:
      Expect asset at path /home/vsts/work/1/s/blockchains/ethereum/assets/0x76ACE4E080C49f04A6C2756C036d3627f6b1E69 in checksum

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

       98 | 
       99 |                     const checksum = isChecksum(address)
    > 100 |                     expect(checksum, `Expect asset at path ${assetPath} in checksum`).toBe(true)
          |                                                                                       ^
      101 |                     
      102 |                     const lowercase = isLowerCase(address)
      103 |                     if (lowercase) {

      at src/test/index.test.ts:100:87
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (src/test/index.test.ts:95:43)
`
