### ISSUE TITLE
File Transform Task (json) fails to transform all variables

### ISSUE THREAD

**Issue by chriswill** [microsoft/azure-pipelines-tasks#10687]
**Question, Bug, or Feature?**  
*Type*: Bug

**File Transform Task (preview)**
## Environment
- Server - Azure Pipelines (Release Task) to private release agent   

- Agent - Private
    
Windows 2012 R2
Agent.Sdk.dll version 2.150.0

## Issue Description

Currently I'm using the File Transform task to do JSON property substitution to my appsettings.json file.  I have 4 variables defined in the Release pipeline for two scopes (QA and PROD).

Three of the variables are found in appsettings.json and appropriately transformed.  The last variable (SystemSettings.SystemBaseUrl) is not found and not transformed.

Here are the properties as defined in DevOps:

![image](https://user-images.githubusercontent.com/216290/59701347-4c2d0f00-91aa-11e9-8f95-d80e23991221.png)

### Task logs

These are the debug logs from the File Transform task:

```
2019-06-18T15:14:35.4807074Z ##[debug]Applying JSON variable substitution for C:\azagent\A2\_work\_temp\temp_web_package_4700401938355474\appsettings.json
2019-06-18T15:14:35.4810031Z ##[debug]substituting value on key: DefaultConnection with (string) value: Data Source=GAINE-DBD;Initial Catalog=TASK_AGENT;MultipleActiveResultSets=True;Trusted_Connection=True;
2019-06-18T15:14:35.4810981Z ##[debug]substituting value on key: Path with (string) value: gaine-taska-qa.pfx
2019-06-18T15:14:35.4811289Z ##[debug]substituting value on key: Password with (string) value: ***
2019-06-18T15:14:35.4871994Z JSON variable substitution applied successfully.
2019-06-18T15:14:35.4878149Z ##[debug]Archiving C:\azagent\A2\_work\_temp\temp_web_package_4700401938355474 to Gaine.TaskAgent.zip
2019-06-18T15:14:41.3588744Z ##[debug]Successfully created archive Gaine.TaskAgent.zip
2019-06-18T15:14:41.3799207Z ##[section]Finishing: File Transform: 
```

My appsettings.json file:

```
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/common/",
    "Domain": "hidden",
    "TenantId": "hidden",
    "ClientId": "hidden",
    "ClientSecret": "hidden",
    "CallbackPath": "/signin-oidc"
  },
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=GAINE-DBP;Initial Catalog=TASK_AGENT;MultipleActiveResultSets=True;Trusted_Connection=True;"
  },
  "MailSettings": {
    "Server": "gaine-smtp",
    "Port": 25
  },
  "SystemSettings": {
    "SystemBaseUrl": "https://localhost:44309/",
    "CurrentTimeZone": "Pacific Standard Time",
    "FileWorkDirectory": "c:\\work",
    "CoreServicesClientPath": "C:\\MDX\\Client\\MDX.CoreServices.Client.exe"
  },
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:8080"
      },
      "Https": {
        "Url": "https://*:443"
      }
    },
    "Certificates": {
      "Default": {
        "Path": "",
        "Password": ""
      }
    } 
  },
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Error"
      }
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by vincentdass** [comment]
@chriswill , Built-in variables are excluded in JSON variable substitution.
![image](https://user-images.githubusercontent.com/20121508/60170106-7b382600-9825-11e9-93b5-dcfe109f1869.png)

We exclude such variables that has the same prefix as pre-defined variables.

**Comment by chriswill** [comment]
So, are you saying that because there are system variables that begin with SYSTEM_ I can't transform a variable that is named SYSTEMSETTINGS?

```
[SYSTEM_WORKFOLDER] --> [C:\azagent\A2\_work]
[SYSTEMSETTINGS_SYSTEMBASEURL] --> [https://gaine-taska-qa/]
```
I would not have expected these to be in conflict.

**Comment by vincentdass** [comment]
@chriswill , thanks for the info.
