### ISSUE TITLE
Download GitHub Release repository drop down not showing all available repositories

### ISSUE THREAD

**Issue by dalemorson** [microsoft/azure-pipelines-tasks#10685]
## Required Information
*Type*: Bug
**Enter Task Name**: Download GitHub Release (Preview) 
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadGitHubRelease

## Environment
- Azure Pipelines
- Download GitHub Release
- GitHub Release under Add an artifact source type

## Issue Description

The Download GitHub Release (Preview) task doesn't show the full list of repositories from GitHub in the Repository drop down. There seems to be a limit to the amount of repos that are returned in the list. This also happens when attempting to use the GitHub Release artifact for a pipeline. Using the task step I can manually type the "org-name/repo-name" but this doesn't work for the GitHub Release artifact source type in the Source (repository) drop down.

**Comment by dalemorson** [comment]
To add to this, the drop down is returning the first 100 repos only when there are over 378 repos in total that should be returned.

**Comment by dalemorson** [comment]
Any updates on this please?

**Comment by Lovakumar** [comment]
@dalemorson we are in the last leg of implementation. We will be able to ship in next 3 weeks time.

**Comment by dalemorson** [comment]
Hey @Lovakumar thank you for your reply that's great news! I use `dale.morson@outlook.com` to login to Azure DevOps and my organisation name is `dev.azure.com/AzDmLrn`. Let me know once I've got access to the early preview and test 👍

**Comment by dalemorson** [comment]
Hi @Lovakumar do you have any updates at all please? Did you add me to the preview? Thanks, Dale.

**Comment by Lovakumar** [comment]
@dalemorson I didn't add your account to preview yet. We are code complete and deployment is pending to be done. ETA is looking to be around 1 week more from now.

**Comment by Lovakumar** [comment]
@dalemorson we have enabled preview of GitHub repository picker on dev.azure.com/AzDmLrn for Download GitHub Release task. Can you please try and let us know your feedback.

**Comment by dalemorson** [comment]
Hi @Lovakumar thank you for enabling the preview. Looking better already, however, while I can now select the repositories I need any source repositories from the organisation I'm an administrator of has a greyed out Add button. If I select one of my repositories the Add button is blue. Attached screenshot:

![image](https://user-images.githubusercontent.com/46656789/62294409-c1a32500-b462-11e9-909b-ed40f92858db.png)

**Comment by sneha-vemula** [comment]
Hi @dalemorson, Thanks for the feedback. We have identified the issue and made a hotfix for resolving the same. We will keep you posted when the deployment reaches your account.

**Comment by dalemorson** [comment]
Thank you very much!

**Comment by sneha-vemula** [comment]
Hi @dalemorson, The hotfix we have made to address the above issue has been deployed for your account. Please try out and let us know if it solved the issue for you.

**Comment by dalemorson** [comment]
Hi @sneha-vemula thank you, I can confirm this has now been resolved! 👍 

![image](https://user-images.githubusercontent.com/46656789/62689625-14c92a80-b9c3-11e9-8eff-2562e4a1803b.png)
