### ISSUE TITLE
Sporadic testrun abortion due to "Blame Collector attachment not found in test results"

### ISSUE THREAD

**Issue by PeterESoft** [microsoft/azure-pipelines-tasks#10696]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Visual Studio Test (VsTest)

## Environment
- Server - Azure Pipelines
- Agent - Private (agent version: '2.141.1')

## Issue Description
Running our nightly UI tests is aborted round about every second run with the message: `Blame Collector attachment not found in test results. So it is not a test case abort issue. It's abort from test platform, might be during app domain tear down.`

As we have no idea what the "Blame Collector" is for and if and how we can deactivate/fix it, we need support from you how to get more information about it and how to solve it.

### Task logs
[stripped_tasklog.log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3305063/stripped_tasklog.log.txt)

I hope this stripped logs already help, please let me know which information will help you to help us

**Comment by kaadhina** [comment]
The blame collector is not actuallu active here and the message is misleading. We will fix the messaging. Thank you for that feedback.
What has happened here is that the test run aborted, probably because of an issue due to app domain tear down. You can try to disable app domain in the run using a runsettings such as 
<RunSettings>
    <RunConfiguration>
        <DisableAppDomain>False</DisableAppDomain>
    </RunConfiguration>
</RunSettings>

**Comment by PeterESoft** [comment]
Thanks for the hint. We tried to set DisableAppDomain = true and so far it seems to work, the tests were running several days without abortion.

**Comment by kaadhina** [comment]
Thank you for confirming. I'm closing this now. Feel free to re-open or open a new issue if u face further issues.
