### ISSUE TITLE
Problem when rerunning tests Hosted VS2017

### ISSUE THREAD

**Issue by mxavierciandt** [microsoft/azure-pipelines-tasks#10692]
## Issue Description
I've enabled the option "Rerun failed tests", after my test have runned there was one test that has failed. When the test tryed to rerun occurs some erros:

### Question, Bug, or Feature?
Type: Bug

Enter Task Name: Visual Studio Runner

![image](https://user-images.githubusercontent.com/51972378/59718168-ed8a8400-91ef-11e9-9864-0b4f5e66c3bd.png)

## Environment
Server - Azure Pipelines

## Error logs
Log Snippet

`##[error]The test source file "C:\Users\VssAdministrator\AppData\Local\Temp\Delete" provided was not found.`

## Additional Data

My pipeline configuration
![image](https://user-images.githubusercontent.com/51972378/59719935-f67d5480-91f3-11e9-9059-eb75d9752181.png)

Visual Studio Test Runner configuration
![image](https://user-images.githubusercontent.com/51972378/59719977-11e85f80-91f4-11e9-914a-5bfea31503fd.png)

**Comment by SadagopanRajaram** [comment]
@mxavierciandt - I am sorry for the inconvenience. 
Can you please set System.Debug to true and share the build logs?
Thanks
Sada

**Comment by karanjitsingh** [comment]
@mxavierciandt, closing this for now. Please come back to this thread with full logs and we can reopen the issue.
