### ISSUE TITLE
error on trigger sync for python based linux function app in eastus

### ISSUE THREAD

**Issue by SteveDevOps** [microsoft/azure-pipelines-tasks#10699]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  
smartnexus/SNX IoT Platform V1/platops-apim-splunk-release
/Release-14

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
 Hosted Ubuntu 1604

## Issue Description
Our Deploy Azure Function App task fails. We are deploying a python based linux function app in east us. But we can then go manually start function app via azure portal and it works fine.
error:
Error: Failed to sync triggers for function app 'prodiat-apim-splunk-func'. Error: Unauthorized - Encountered an error (Forbidden) from extensions API. (CODE: 400)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[tasklog_6.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3307771/tasklog_6.zip)

![screenshot-dev azure com-2019 06 19-16-21-42](https://user-images.githubusercontent.com/9933200/59797699-5c2e1700-92ae-11e9-8a14-345de5f666e4.png)

**Comment by vincentdass** [comment]
@SteveDevOps , Is the issue intermittent or consistent?

**Comment by SteveDevOps** [comment]
It is consistent. I've had to turn on allow error on the deploy task so that final function start step will occur. [screenshot](https://nimb.ws/MeUO5p)

**Comment by SteveDevOps** [comment]
I am seeing same errors on new linux funcs / python runtime in new subscription, new resource groups

**Comment by vincentdass** [comment]
@SteveDevOps , thanks for the info.
We have directed the issue to the App Service team. Will upate you once there is an response.

**Comment by SteveDevOps** [comment]
If I switch to an app service task, but specifying a linux function type for deployment.. I get a little more info around the error -- however I have tried to mitigate by hardcoding in both app settings mentioned. Additionally my vanilla function is setup with terraform (without code/package), then I'm trying to use azure devops to deploy. Here is error when using an app service task (specifying linux function): 

2019-07-15T15:20:31.4024214Z Updating App Service Application settings. Data: {"FUNCTIONS_WORKER_RUNTIME":"undefined-WEBSITES_ENABLE_APP_SERVICE_STORAGE","":"true"}
2019-07-15T15:20:32.8471046Z ##[error]Error: Failed to update App service 'myfunctionname-func' application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)
2019-07-15T15:20:33.2937520Z ##[warning]Error: Failed to update deployment history. Error: Site Unavailable (CODE: 503)

**Comment by SteveDevOps** [comment]
And to clarify, I have tried specifying:
-WEBSITES_ENABLE_APP_SERVICE_STORAGE true
As well as including it as part of setup via terraform ahead of time.

Also found this reference to problem with linux function apps: https://github.com/Azure/azure-functions-ux/issues/3195

**Comment by SteveDevOps** [comment]
figured out how to run with debug, here is output:

2019-07-15T15:44:36.7681626Z ##[debug]old value : python. new value: undefined-WEBSITES_ENABLE_APP_SERVICE_STORAGE
2019-07-15T15:44:36.7681889Z ##[debug]old value : undefined. new value: true
2019-07-15T15:44:36.7686027Z ##[debug][PUT]https://management.azure.com/subscriptions/0a0cfdee-8f61-4057-ad7b-dc024cced801/resourceGroups/platops_westus/providers/Microsoft.Web/sites/iat2-apimlogger-func/config/appsettings?api-version=2016-08-01
2019-07-15T15:44:37.2265225Z ##[debug]Deployment Failed with Error: Error: Failed to update App service 'iat2-apimlogger-func' application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)
2019-07-15T15:44:37.2265578Z ##[debug]task result: Failed

**Comment by SteveDevOps** [comment]
Any updates? still seeing this: Error: Unauthorized - Encountered an error (Forbidden) from extensions API. (CODE: 400)

different function, different region: west us. Trigger info (an eventhub connection string) is correct and referenced as app setting. Function runs fine on manual start/restart after deploy.

**Comment by vincentdass** [comment]
Please share the logs to `RM_customer_Queries [at] Microsoft [dot] com`

**Comment by SumiranAgg** [comment]
@SteveDevOps Are you still facing the issue?

**Comment by SteveDevOps** [comment]
Well, we changed our development efforts and switched to nodejs. We don't
have any issues with nodejs and its much more performant.

**Comment by 20shivangi** [comment]
Great!!
Thereby, closing this issue. Feel free to reopen if you face any issues.

**Comment by mikemutpo** [comment]
Please re-open. We also have this exact same issue.
