### ISSUE TITLE
Build Definition running on the wrong agent pool

### ISSUE THREAD

**Issue by ealsur** [microsoft/azure-pipelines-tasks#10700]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Build Definition / Agent Pool behavior

## Environment
- Server - Azure Pipelines
    
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=9032

- Agent - Hosted

Builds should be running in the "Hosted VS2017" agent pool but instead are running in "Azure Pipelines" agent pool
    

## Issue Description

Builds are configured to run on "Hosted VS2017" Agent pool:

![image](https://user-images.githubusercontent.com/1633401/59803069-436a3500-929f-11e9-8580-416a2f2a4d75.png)

But instead they are landing on a pool called "Azure Pipelines":

![image](https://user-images.githubusercontent.com/1633401/59803113-672d7b00-929f-11e9-9a0b-1f54ff2ef46e.png)

"Hosted VS2017" has 15 agents while "Azure Pipelines" has 1.

This is blocking our release cadence.

**Comment by kirankumarkolli** [comment]
Any update? This is a blocker.

**Comment by ArieHein** [comment]
when you set the agent in the 'Pipeline' scope usually any job under it would inherit, unless you broke the inheritance, so always check  the Phase (run on agent) as it might have a different value then you expect. If the inheritance is correct, the field for Agent Pool should be grayed out.

This allows you to have multiple phase on multiple agents and have a default pool set at the pipeline level but allowing for specific phase to run on other agents if they require specific ones

**Comment by ealsur** [comment]
@ArieHein Agent Pool in the phase is greyed out, pointing to the Hosted VS2017 pool, but it runs in the Azure Pipelines pool:

![image](https://user-images.githubusercontent.com/1633401/59858678-4a8d5380-9330-11e9-8fff-c93ec5982785.png)

**Comment by ealsur** [comment]
If I check the builds, they show that they go to the Hosted VS2017 pool, but they are picking an agent from the Azure Pipelines pool:

![image](https://user-images.githubusercontent.com/1633401/59858968-c5ef0500-9330-11e9-8e1b-f87fbe631a0b.png)

But the Hosted VS2017 pool has no Azure Pipelines agent:

![image](https://user-images.githubusercontent.com/1633401/59859053-ea4ae180-9330-11e9-8572-f98e60c485ca.png)

Looks like it's picking an agent from the wrong pool.

**Comment by ArieHein** [comment]
ah yes its he naming convention. The first agent name in the "vs 2017" agent pool is also called "hosted agent" same as the name in the hosted agent pool

**Comment by rsemenov** [comment]
@ealsur , there are 2 issues here. The fact that your pipeline is running on Azure Pipelines pool is expected as we are deprecating legacy hosted pools like "Hosted VS2017". Going forward we will have only one Azure Pipelines pool that will support an Agent Specification (VM Image) that you can specify in you build/release. You account is on ring 0 that was migrated to Azure Pipelines pool model last week. We are working on public release notes for this feature.

The second issue is that Azure Pipelines pool had only 1 agent and was not resized correctly. We mitigate this issue last week so please double check that the number of the Azure Pipelines pool agents is 16. We are still investigating what caused the resizing problem in the first place.

**Comment by moswald** [comment]
@rsemenov I assigned this to you, but it seems to be a non-tasks issue. Maybe close it and create a bug on our internal tracker?

**Comment by rsemenov** [comment]
Azure Pipelines pool rolled out to all accounts at this point. Closing.
