### ISSUE TITLE
Unable to use NPM tasks on DevOps Server

### ISSUE THREAD

**Issue by leoniDEV** [microsoft/azure-pipelines-tasks#10720]
## Required Information

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: *NpmV1*

## Environment
- Server - Azure Pipelines or TFS on-premises?
    **Azure DevOps Server 2019.0.1**

- Agent - Private:
  **Version**: 2.144.2, 2.150.3  and 2.153.2
  **OS**: Win-x64 Pro ver. 1903 build  18362.175
  

## Issue Description
The NPM task always fail with the error: 
`TypeError: Cannot read property 'toLowerCase' of null`

I'm not sure if this is an issue that I need to open in this repo or I need to go to Developer Community, to me it is not clear if the problem is in the task or is in DevOps Server, but the NPM tasks not working, the task fail with the same error every time for every commands.
The project build correctly locally and in Azure Pipeline Service (with the same pipeline), also even if I use a pswh task, with the appropriate npm command, instead of the Npm task, the build succeded

### Task logs
[log file](https://1drv.ms/u/s!AoPGkdb3ZCRBgowJQyfFPFBiOJf96w?e=NOfVpi)

### Error logs
`2019-06-20T20:29:08.2585198Z ##[debug]Unable to log NPM task telemetry. Err:( TypeError: Cannot read property 'toLowerCase' of null )`
`[...]`
`2019-06-20T20:29:08.2755962Z ##[error]TypeError: Cannot read property 'toLowerCase' of null`

**Comment by aasim** [comment]
Hi @leoniDEV - Can you provide me with the custom commands you're running? You can capture a screenshot of all the inputs (masking any sensitive information) and attach as well.

**Comment by leoniDEV** [comment]
investigating further I found that the problem is in the `.npmrc` file where there is a misconfiguration of the private registry, removing the second `repository=` the Npm task succeeded

**the npmrc**:
![npmrc](https://user-images.githubusercontent.com/11667486/60101672-78bdc980-975c-11e9-859a-5f9a091cde55.png)

What confused me is the fact that the project builds correctly using the same (misconfigured) `.npmrc` both locally and executing the npm commands through pwsh tasks, so I mistakenly assumed that the `.npmrc` file was correct and so I didn't check its correctness.

Maybe this inconsistency in the behaviours need to be addressed

**Comment by aasim** [comment]
I think the issue here might be that the custom command you entered has some fields missing, that is why I had asked you for a screenshot of the task configuration page.

Regarding the inconsistency, can you elaborate on what worked with the misconfigured .npmrc? I was wondering if you configured the push task to use private repositories from the dropdown instead of the .npmrc.

**Comment by leoniDEV** [comment]
The task fails also when try to use the predefined install command, not only with custom commands and the private registy isn't involved in any of the steps of the build pipeline  (I don't install nor push to that registry).
I don't have a push task in the pipeline, and none of my packages come from the private registry (anyway 
 I don't use the `npm install ` task, but I restore the dependencies passing a `pnpm install` command to a pwsh task).

Anyway I setup a simple [repro repository](https://dev.azure.com/antoniolandolfi/_git/NPMTaskRepro).
Here you can find 2 branches the [`master`](https://dev.azure.com/antoniolandolfi/NPMTaskRepro/_git/) branch with an `.npmrc` with a [misconfigured](https://dev.azure.com/antoniolandolfi/_git/NPMTaskRepro?path=%2F.npmrc&version=GBmaster) private registry and a [`fixedNpmrc`](https://dev.azure.com/antoniolandolfi/_git/NPMTaskRepro?version=GBfixedNpmrc) branch where the private registry is [correctly configured](https://dev.azure.com/antoniolandolfi/_git/NPMTaskRepro?path=%2F.npmrc&version=GBfixedNpmrc)
[The pipeline](https://dev.azure.com/antoniolandolfi/NPMTaskRepro/_build?definitionId=11&_a=summary) has 2 jobs one with a **npm task** and the other job has the `npm install` command passed to a **pwsh task**.
As you can see for the [**master branch**](https://dev.azure.com/antoniolandolfi/NPMTaskRepro/_build/results?buildId=120&view=results) the first job (with the npm task) fail and the second job (with the pwsh task) succeed, for the [**fixedNpmrc branch**](https://dev.azure.com/antoniolandolfi/NPMTaskRepro/_build/results?buildId=121&view=results) both jobs succeed

**Comment by aasim** [comment]
So, this is the reason for the discrepancy: the Npm task publishes telemetry at the end of each run. To get additional data about your npm configuration, it reads the .npmrc file and parses the urls in it to check if any were internal azure artifacts urls. It tried to parse the url from your incorrect npmrc file, and failed, that is the error you saw in the logs. I have made a fix to the task to make it more resilient to bad urls and have a PR out. It should get fixed in the next sprint.

https://github.com/microsoft/azure-pipelines-tasks/pull/10782

**Comment by aasim** [comment]
The fix has been committed in PR [10782](https://github.com/microsoft/azure-pipelines-tasks/pull/10782). It should be deployed with the next release of TFS.

**Comment by leoniDEV** [comment]
This issue seems fixed
