### ISSUE TITLE
[HelmInstaller] Failed to download Helm from location https://storage.googleapis.com/kubernetes-helm

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/azure-pipelines-tasks#10727]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmInstaller 

## Environment
- Server: Azure Pipelines

- Agent - Hosted: 

## Issue Description

According this new announcement on June 10 2019, the URL to download the Helm Client has changed: https://helm.sh/blog/get-helm-sh/ resulting since June 20 2019 to an error while trying to install/download a specific Helm version:
```
Failed to download Helm from location https://storage.googleapis.com/kubernetes-helm
```

**Comment by mathieu-benoit** [comment]
PR https://github.com/microsoft/azure-pipelines-tasks/pull/10729 to fix this

**Comment by bansalaseem** [comment]
Closing this issue as the above PR is merged.
