### ISSUE TITLE
Azure PowerShell Task | Unable to pass Json as Script Arguments to PowerShell Script

### ISSUE THREAD

**Issue by niragtibdewal** [microsoft/azure-pipelines-tasks#10730]
I have a requirement to pass Json string as a script argument to PowerShell for updating the App.config

Under the script argument, I did below 

-TenantConfiguration "$(TenantConfiguration)"

Where -TenantConfiguration is the Param name in PowerShell and $(TenantConfiguration) is environment variable which is Json. But in Powershell instead of passing the entire JSON, it is passed only "{"

Could you please point out what I am doing wrong here?

**Comment by vincentdass** [comment]
@niragtibdewal , The argument is malformed once the variable is substituted.
Consider your variable (TenantConfiguration ) value is `{"key": "value"}`
Once the variable is subtituted in the argument, it beomes `-TenantConfiguration "{"key": "value"}"`
So, Tenant configuration takes the first enclosed value in quotes. (i.e `"{"`)

Can you pass the argument is single quotes?
![image](https://user-images.githubusercontent.com/20121508/60698482-27a49700-9f0d-11e9-9940-21afa8c4087a.png)
![image](https://user-images.githubusercontent.com/20121508/60698486-2ecba500-9f0d-11e9-9393-ea925d16cd6b.png)
The above works well.
