### ISSUE TITLE
Deploy azure app service Error

### ISSUE THREAD

**Issue by sosamv** [microsoft/azure-pipelines-tasks#10735]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy

## Environment
    - Azure Pipelines
    - https://dev.azure.com/sigma-alimentos
    - bsite-nutrition.sigma-alimentos.com

- Agent - Hosted or Private: 
    
    - Hosted VS2017
    - Pipeline: webapp-nutrition-sigma-alimentos-com - CD

## Issue Description

Unable to deploy: Waiting for console output from an agent...
[tasklog_5.log](https://github.com/microsoft/azure-pipelines-tasks/files/3318539/tasklog_5.log)

## Troubleshooting
Created a new pipeline from azure portal.

### Error logs

Failed to deploy web package to App Service.
Error: Error: Failed to deploy web package to App Service. Error: Request timeout: /api/zipdeploy?isAsync=true&deployer=VSTS_ZIP_DEPLOY

**Comment by vincentdass** [comment]
@sosamv , The issue is related to Kudu Zip Deploy, please open the issue [here](https://github.com/projectkudu/kudu/issues).
