### ISSUE TITLE
Gulp failed with error: C:\npm\prefix\gulp.cmd failed with return code: 1

### ISSUE THREAD

**Issue by kuldip1490** [microsoft/azure-pipelines-tasks#10733]
##[section]Starting: gulp : Build
==============================================================================
Task         : Gulp
Description  : Node.js streaming task based build system
Version      : 0.141.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613721)
==============================================================================
[command]C:\npm\prefix\gulp.cmd Build --gulpfile d:\a\1\s\Alarms.UI\gulpfile.js
[‌15:33:12‌] [‌15:33:12‌] Task never defined: Build‌
[‌15:33:12‌] Using gulpfile d:\a\1\s\Alarms.UI\gulpfile.js‌
To list available tasks, try running: gulp --tasks
##[error]Gulp failed with error: C:\npm\prefix\gulp.cmd failed with return code: 1
##[section]Finishing: gulp : Build

SS : 1 
![1](https://user-images.githubusercontent.com/22524273/59959942-d7c1db00-94dd-11e9-9cbd-01701d66469b.png)

SS : 2
![2](https://user-images.githubusercontent.com/22524273/59959948-e7d9ba80-94dd-11e9-8211-539772b41cfc.png)

SS : 3
![5](https://user-images.githubusercontent.com/22524273/59959954-06d84c80-94de-11e9-97e7-dcc87c55f2f1.png)

SS : 4
![6](https://user-images.githubusercontent.com/22524273/59959960-16579580-94de-11e9-990b-ae922ece16f1.png)

SS : 5 Locally Working gulp file
![3](https://user-images.githubusercontent.com/22524273/59959966-35562780-94de-11e9-81e7-9c64b58a3807.png)

SS: 6 Package.json
![4](https://user-images.githubusercontent.com/22524273/59959971-4bfc7e80-94de-11e9-8ed6-48e5dfa5556f.png)

 Locally Node,NPM version

**- Node Version  : v10.15.3**
**- npm Version : 6.4.1**

**Comment by in8kavka** [comment]
I am facing the same issue. Is there any resolution to this?

**Comment by jlara005** [comment]
Same issue here. Works locally but not in Azure DevOps. Any fix for this?

**Comment by jlara005** [comment]
https://www.eliostruyf.com/how-to-let-the-warnings-not-fail-the-sharepoint-framework-build-process/

**Comment by omokoh** [comment]
Hi,

If you are still having this issue, please reopen it.

Thanks
