### ISSUE TITLE
"x commits to [branch] since this release" is missing if using GitHub Release task

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/azure-pipelines-tasks#10759]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GitHub Release  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubRelease

## Environment
- Server - Azure Pipelines?
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

account name: vscode-webdiag-extensions
team project name: VS Code WebDiag extensions
build definition name: vscode-react-native (under release pipeline)
build number: 106 (under release pipeline)

- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

Since we started to use Github Release task, releases page is missing "x commits to [branch] since this release" message as show below:

![image](https://user-images.githubusercontent.com/30265843/60174055-df082200-9818-11e9-9bbf-73c96dfc6d82.png)

I found [conversation of this problem](https://github.community/t5/How-to-use-Git-and-GitHub/quot-x-commits-to-branch-since-this-release-quot-is-missing-part/td-p/20042) and looks like GitHub Release task points to specific commit for releasing instead of pointing to the branch (master in our case). How can we get back this message?

**Comment by TheLayman** [comment]
@ruslan-bikkinin Cannot repro this issue. 
I've created a release using the task. After that, added a new commit to the same branch. 
The message "1 commit to master since this release" is showing up.
 
[Link to release](https://github.com/TheLayman/dnsproxy/releases/tag/rajarajas )

**Comment by TheLayman** [comment]
@ruslan-bikkinin If the issue is still repro-able, feel free to reopen this issue
