### ISSUE TITLE
Unable to Determine Identity

### ISSUE THREAD

**Issue by Venkatesh-Sugan** [microsoft/azure-pipelines-tasks#10757]
Unable to determine identity
Input to determineIdentity: {"cwd":"/Users/vsts/agent/2.150.3/work/1/s","unlockDefaultKeychain":false,"defaultKeychainPassword":"","p12":"/Users/vsts/agent/2.150.3/work/1/s/signing/ios/DEV/Developer Certificate.p12","p12pwd":"***"}
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
 I cannot get past this error. Here is the YAML for this build step:

steps:
- task: ms-vsclient.cordova-extension.cordovabuildtask.CordovaBuild@1
  displayName: 'Cordova Build ios'
  inputs:
    platform: ios
    configuration: Release
    antBuild: false
    p12: 'certificate/ios/DEV/Dev_Certificate.p12'
    p12pwd: '$(p12pwd)'
    provProfile: 'certificate/ios/DEV/DEV.mobileprovision'
    removeProfile: true
    windowsPhoneOnly: false
    windowsOnly: false
    targetEmulator: false

**Comment by damccorm** [comment]
Hi, it looks like you are using a 3rd party task. Unfortunately there's nothing we can do to help with 3rd party tasks since we don't control them - please reach out to the author for help with any issues.
