### ISSUE TITLE
PublishPipelineArtifact and 'publish' keyword in YAML

### ISSUE THREAD

**Issue by arek-avanade** [microsoft/azure-pipelines-tasks#10765]
*Type*: Question

**Enter Task Name**: PublishPipelineArtifact  

## Environment
- Server - Azure Pipelines

- Agent - Hosted MacOS (Mojave)

## Issue Description
Documentation (https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts) says we can use 'publish' keyword in YAML as a shortcut for the task. When I tried that however, I was getting the following error when triggering the build:
Unexpected value 'publish'

Is documentation ahead of actual feature being deployed to Azure Pipelines?

**Comment by bryanmacfarlane** [comment]
Perhaps - it does roll out across rings.  Does it work for you now?

**Comment by arek-avanade** [comment]
It works now, thanks
