### ISSUE TITLE
Is that possible to make pipeline timeout configurable when trigger it 

### ISSUE THREAD

**Issue by 928PJY** [microsoft/azure-pipelines-tasks#10768]
For now, I am using the yaml-style pipeline, and the timeout is set in the yaml file, can the timeout be configurable when I trigger the pipeline, which will overwrite the config in the yaml file?

**Comment by ericsciple** [comment]
@zachariahcox to help route

**Comment by zachariahcox** [comment]
Great question @928PJY , I apologize that this issue was lost for so long. 
Currently timeout is configurable via process parameters, the ${{}} syntax. 
We are currently rolling out a major enhancement to yaml process parameters that will make implementing pipelines like this a lot easier.
