### ISSUE TITLE
Package name transform no longer honoured in output APK name

### ISSUE THREAD

**Issue by Ryan-Palmer** [microsoft/azure-pipelines-tasks#10774]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Xamarin.Android

## Environment
- Server - Azure Pipelines
    
- Agent - HostedVS2017

## Issue Description

Since [this](https://github.com/microsoft/azure-pipelines-tasks/commit/0ab6301bae6cb89baed88478eca7786ccf0a8cff#diff-f4b5969cde39c68fa86c8e07ae0c961b) commit made its way into our build pipeline with version 1.151, all of our release pipelines failed because they could not find the dropped APK.

The reason for this (I think!) is that we have multiple build pipelines for the same app which use an msbuild task to change the name of the package in the Manifest depending on the build configuration (we have uat, staging and production versions which need to be installed side by side on a device).

Previously the dropped APK had the modified package name as its filename. Since the change it has the unmodified package name.

The change in the commit I linked to prevents a second build, but I believe the second build is what changed the APK name as it happened after our transform msbuild task.

With version 1.147 I can see an IncrementalClean line in the output logs which deletes the APK with the unmodified name. That is missing in 1.151.

If this is intended behaviour for the step, is there a way we can set the output APK name manually rather than have it inferred from the manifest?

Thanks for your help :)

**Comment by alexander-smolyakov** [comment]
Hello, @Ryan-Palmer!

Thanks for your patience! Is this issue still actual for you? 

If it's still actual, could you please run the pipeline again with the debug option set on and send logs? Also, it would be great if you are able to provide the YAML file for your pipeline.

**Comment by Ryan-Palmer** [comment]
Hi @alexander-smolyakov , I am no longer working at that company so I can't say for sure if it is still an issue. I have built apps with similar setups recently and had no problem so it may well have gone away. Perhaps https://github.com/PaulAxten might know if it is still happening for them?

**Comment by PaulAxten** [comment]
Thanks @Ryan-Palmer!

Hi @alexander-smolyakov,

Thanks for picking this one up. Yes, it is still an issue that we're facing. As Ryan says, all other aspects of the transform occur properly, including the package name, but the apk filename appears to be picked up before the package name is transformed.

I've attached the yaml and build log, please let me know if you need anything else.

[PRA6.1-Android-CreateAPK.yaml.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4616447/PRA6.1-Android-CreateAPK.yaml.txt)
[PRA6.1-Android-log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4616448/PRA6.1-Android-log.txt)

**Comment by sdobrodeev** [comment]
Hi @PaulAxten It would be nice to have the new feature to set the name of the APK manually. We can create feature request for it. If you want you can help with the design of this feature (briefly describe how this should work from your point of view)

**Comment by PaulAxten** [comment]
Hi @sdobrodeev, thanks for looking into this.

From our perspective, this feature comes from a desire to have a different APK filename for each build configuration, and for those build configurations to be controlled by a multi-configuration execution plan.

As long as we could use the build configuration variable in part of the filename, this would achieve our ends.

**Comment by sdobrodeev** [comment]
Closing the issue, created feature request: https://github.com/microsoft/azure-pipelines-tasks/issues/13009
