### ISSUE TITLE
Azure VM Scale Set Custom Script Extension Deployment

### ISSUE THREAD

**Issue by vinothinidharmaraj** [microsoft/azure-pipelines-tasks#10781]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure VM Scale Set Deployment Task

## Issue Description

We are using Azure VM Scale Set Deployment task with Action "Custom script extension" to deploy our application.  in our custom script we have couple of process that will be started when we do deployment. We noticed the process started under the system user, and our process supposed to create the windows job, due to some permission issue its not able to create the windows jobs. 

We would like to know is that possible to launch the custom script on the machine using administrator account?  I have tried self elevate  the scripts to run as administrator  but it didnt help.

**Comment by vineetmimrot** [comment]
Hey @vinothinidharmaraj ,
As a temporary solution, you can create another script which can use powershell command to execute your main script. For reference: https://blogs.technet.microsoft.com/benshy/2012/06/04/using-a-powershell-script-to-run-as-a-different-user-elevate-the-process/

Though we will add into our backlog to provide options to add credentials as input to the task to allow to run script as other user privilege.

**Comment by vineetmimrot** [comment]
@vinothinidharmaraj Are you able to resolve the issue with workaround provided?
