### ISSUE TITLE
Publish Code Coverage Results fails when a build is triggered from Github

### ISSUE THREAD

**Issue by meigaoms** [microsoft/azure-pipelines-tasks#10793]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  PublishCodeCoverageResultsV1 is successful when running in AzureDevOps, but fails when the pipeline is triggered from Github

**Enter Task Name**: PublishCodeCoverageResultsV1  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Hosted 

## Issue Description
PublishcodeCoverageResults task is sucessfull when run a manual build from AzureDevOps, but fails when a build is triggered from Github

yml script for test and code coverage:
  - script: |
        python3 -m pip install pytest
        python3 -m pip install pytest-cov
        python3 -m pytest --junitxml=junit/test-results.xml --cov=myproj --cov-report xml:coverage.xml
    displayName: "Test with Pytest"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
    displayName: "Publish test result"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage.xml'
    displayName: "Publish code coverage"

### Task logs
**log of failed build triggered from GitHub:

##[section]Starting: Publish code coverage
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.152.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
[command]/usr/bin/dotnet /home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.152.3/netcoreapp2.0/ReportGenerator.dll -reports:**/coverage.xml -targetdir:/home/vsts/work/_temp/cchtml -reporttypes:HtmlInline_AzurePipelines
Loading report '/home/vsts/work/1/s/coverage.xml' 1/1
 Preprocessing report
 Initiating parser for Cobertura
 <**removed some lines here**> 
 Creating summary
  Writing report file '/home/vsts/work/_temp/cchtml/index.htm'
Report generation took 0.5 seconds
Generated code coverage html report: /home/vsts/work/_temp/cchtml
Reading code coverage summary from '/home/vsts/work/1/s/coverage.xml'
##[section]Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 491 of 751 covered.
 Branches- 0 of 0 covered.
##[section]Async Command End: Publish code coverage
##[error]VSS045015: Requested resource 'Db59d37c7-fe3c-4738-b668-4facf2ae2e24' not found.
##[section]Finishing: Publish code coverage

**log of successful build triggered from AzureDevOps:

##[section]Starting: Publish code coverage
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.152.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
[command]/usr/bin/dotnet /home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.152.3/netcoreapp2.0/ReportGenerator.dll -reports:**/coverage.xml -targetdir:/home/vsts/work/_temp/cchtml -reporttypes:HtmlInline_AzurePipelines
Loading report '/home/vsts/work/1/s/coverage.xml' 1/1
 Preprocessing report
 Initiating parser for Cobertura
  <**removed some lines here**> 
 Creating summary
  Writing report file '/home/vsts/work/_temp/cchtml/index.htm'
Report generation took 0.6 seconds
Generated code coverage html report: /home/vsts/work/_temp/cchtml
Reading code coverage summary from '/home/vsts/work/1/s/coverage.xml'
##[section]Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 491 of 751 covered.
 Branches- 0 of 0 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 27 files
File upload succeed.
Published '/home/vsts/work/_temp/cchtml' as artifact 'Code Coverage Report_231'
##[section]Async Command End: Publish code coverage
##[section]Finishing: Publish code coverage

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by meigaoms** [comment]
I also tried yml file with different path: 
  - script: |
        # pytest --cov=benchml
        python3 -m pip install pytest
        python3 -m pip install pytest-cov
        python3 -m pytest --junitxml=junit/test-results.xml --cov=benchml --cov-report xml:coverage.xml
    displayName: "Test with Pytest"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

Build triggered from Github still complains about the same.

**Comment by karanjitsingh** [comment]
@meigaoms, it's possible permissions are not set properly for builds triggered from github and hence pcc task is not able to upload the report. Also for us to debug further could you post the full build logs.

**Comment by meigaoms** [comment]
Thanks! A guy from Azure pipelines helped me out already. Please close this
thread.
