### ISSUE TITLE
DotNetCoreCLI restore fails when reusing authenticated nuget.config from previous step

### ISSUE THREAD

**Issue by AArnott** [microsoft/azure-pipelines-tasks#10791]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `DotNetCoreCLI@2`

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2809853

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: OS: Windows, Agent  version: 2.153.2

## Issue Description

My pipeline YAML has two restore tasks, one right after the other:

```yml
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: src
    feedsToUse: config
    nugetConfigPath: nuget.config
  displayName: dotnet restore src

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: Tenets\PerfUnitTest
    feedsToUse: config
    nugetConfigPath: Tenets\PerfUnitTest\nuget.config
  displayName: dotnet restore Tenets\PerfUnitTest
```

The first one succeeds, which requires authenticating to feeds in the root level `nuget.config` file. 
The second one fails to find certain packages that would have come uniquely from the feeds specified in the nuget.config file for the second task invocation. In fact from the logs of the failed task I can clearly see that the list of feeds tried are only those listed in the root nuget.config file rather than the one I specified for that task.

I observe from the log that the same .config file path is used both times. Did the file not get regenerated for the second invocation?

First task invocation:
> [command]E:\A\_work\_tool\dotnet\dotnet.exe restore E:\A\_work\106\s\src --configfile E:\A\_work\106\Nuget\tempNuGet_2809853.config --verbosity Detailed

Second task invocation:
> [command]E:\A\_work\_tool\dotnet\dotnet.exe restore E:\A\_work\106\s\Tenets\PerfUnitTest --configfile E:\A\_work\106\Nuget\tempNuGet_2809853.config --verbosity Detailed

### Task logs

https://microsoft-my.sharepoint.com/:u:/p/andarno/EancIoEJx7dDj6WjOm0V2NABejTdp02toiyn4Bdhv1KEPg?e=7e8XiF

### Error logs

```
         Committing restore...
         Generating MSBuild file E:\A\_work\106\s\obj\PerfUnitTest\PerfUnitTest.csproj.nuget.g.props.
         Generating MSBuild file E:\A\_work\106\s\obj\PerfUnitTest\PerfUnitTest.csproj.nuget.g.targets.
         Writing assets file to disk. Path: E:\A\_work\106\s\obj\PerfUnitTest\project.assets.json
         Writing cache file to disk. Path: E:\A\_work\106\s\obj\PerfUnitTest\PerfUnitTest.csproj.nuget.cache
         Restore failed in 2.01 sec for E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest\PerfUnitTest.csproj.
         
         NuGet Config files used:
             E:\A\_work\106\Nuget\tempNuGet_2809853.config
         
         Feeds used:
             https://api.nuget.org/v3/index.json
             https://www.myget.org/F/applicationinsights/api/v3/index.json
             https://devdiv.pkgs.visualstudio.com/_packaging/vs-impl/nuget/v3/index.json
             https://devdiv.pkgs.visualstudio.com/_packaging/VSIDE-TestSigned-Release/nuget/v3/index.json
         
         Installed:
             12 package(s) to E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest\PerfUnitTest.csproj
       Done executing task "RestoreTask" -- FAILED.
     1>Done building target "Restore" in project "PerfUnitTest.sln" -- FAILED.
     1>Done Building Project "E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest.sln" (Restore target(s)) -- FAILED.

Build FAILED.

       "E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest.sln" (Restore target) (1) ->
       (Restore target) -> 
         E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest\PerfUnitTest.csproj : error NU1101: Unable to find package Microsoft.DotNet.xunit.performance. No packages exist with this id in source(s): appinsights, feed-feed-testsigned, feed-feed-vs-impl, nuget.org [E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest.sln]
         E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest\PerfUnitTest.csproj : error NU1101: Unable to find package Microsoft.DotNet.xunit.performance.runner.Windows.x64. No packages exist with this id in source(s): appinsights, feed-feed-testsigned, feed-feed-vs-impl, nuget.org [E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest.sln]
         E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest\PerfUnitTest.csproj : error NU1101: Unable to find package Microsoft.DotNet.xunit.performance.runner.Windows.x86. No packages exist with this id in source(s): appinsights, feed-feed-testsigned, feed-feed-vs-impl, nuget.org [E:\A\_work\106\s\Tenets\PerfUnitTest\PerfUnitTest.sln]

    0 Warning(s)
    3 Error(s)

```

**Comment by vineetmimrot** [comment]
Thanks for reporting the issue, we are working on it.

**Comment by aasim** [comment]
Hi - We have recently released the NuGetAuthenticate task that can be used in a pipeline to authenticate with Azure Artifacts and other NuGet repositories. The design philosophy behind this task is that we would authenticate all the repositories you describe in this task, and get out of the way leaving you fully in control of running your nuget or dotnet commands in the pipeline as you see fit.

You can read more about the NuGetAuthenticate task here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops. It also gives some examples on how to configure the task.

I think this task is a good fit for your use case, you can use the NuGetAuthenticate task to perform the authentication, and then use the regular `dotnet` restore commands that you're using.Let me know if you need any more help in setting this up.

Aasim

**Comment by AArnott** [comment]
Thanks. I've already [switched all my repos to that task](https://github.com/AArnott/Library.Template/commit/5ee62bfe3556f392e9e1bfddcf2b25fd640e2b9e) (or rather, the underlying cred provider).
