### ISSUE TITLE
Condition a build with information from the PR

### ISSUE THREAD

**Issue by Jonlondon** [microsoft/azure-pipelines-tasks#10794]
Type: Question

Hi,

Not an issue, just a feature / question / help.

I would like to request a small feature on the Azure DevOps pipeline (or maybe you can help me find a workaround).
When creating a PR, we can add a label. It could be great if this label was visible as an environment variable in the build triggered by this PR.

In fact, what I want to do is run a build based on a PR condition. I thought that the label could be a good element (I create the PR via a script to automate the cascading of several PR).

Regards.

**Comment by moswald** [comment]
Hi @Jonlondon it would be best if you could recreate this on the [Developer Community site](https://developercommunity.visualstudio.com/spaces/21/index.html). That said, if you are using yaml for your builds, there are [various control constructs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) that you might be able to use.

**Comment by bharathHexagon** [comment]
Hi @Jonlondon ,
Even I am looking for similar feature. Can you please update on whats the progress from your side?
Did you create this on Developer Community Site?

**Comment by edgariscoding** [comment]
I'm also interested in this scenario. We'd like to be able to specify that a PR is a hotfix via a label and then use that as a condition during the build
