### ISSUE TITLE
Node Tools Installer 502 Bad Gateway

### ISSUE THREAD

**Issue by rfcdejong** [microsoft/azure-pipelines-tasks#10807]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Node Tools Installer

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines
Hosted Agent

## Issue Description

Starting: Use Node 10.x |  
-- | --
  | ============================================================================== |  
  | Task         : Use Node.js ecosystem |  
  | Description  : Set up a Node.js environment and add it to the PATH, additionally providing proxy support |  
  | Version      : 1.0.5 |  
  | Author       : Microsoft Corporation |  
  | Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks |  
  | ============================================================================== |  
  | ##[error]<html> |  
  | <head><title>502 Bad Gateway</title></head> |  
  | <body bgcolor="white"> |  
  | <center><h1>502 Bad Gateway</h1></center> |  
  | <hr><center>cloudflare</center> |  
  | </body> |  
  | </html> |  
  |   |  
  | Finishing: Use Node 10.x

**Comment by bryanmacfarlane** [comment]
Not a task issue.  5xx and gateway errors come from service side - in this case, nodejs.org
