### ISSUE TITLE
Allow duplicate NuGet packages to be skipped in Azure DevOps Server

### ISSUE THREAD

**Issue by NeoXtreem** [microsoft/azure-pipelines-tasks#10800]
**Task Name**: NuGet push (NuGetPublisher)

## Environment
Azure DevOps Server 2019.0.1
Private agent OS: Windows Server 2019 with all updates

## Issue Description

With the 'Allow duplicates to be skipped' option selected for NuGet push task, a warning is displayed:

> The 'Allow duplicates to be skipped' option is currently only available on Azure Pipelines. If NuGet.exe encounters a conflict, the task will fail.

The task results in the following error that causes the task to fail indicating that the above warning applies:

> Response status code does not indicate success: 409 (Conflict - The feed already contains 'MyPackage X.Y.Z'. (DevOps Activity ID: 1A57312F-3C56-4E4D-9E78-73C7072A288F)).

Is this particular to Azure DevOps Server (rather than Azure DevOps Services)?  If so, does it need to be enabled, implemented or fixed so that it works with Azure DevOps Server?

**Comment by elbatk** [comment]
Hey @NeoXtreem , you are correct in that the "Skip Duplicates" functionality is only available in the hosted product (Azure DevOps Services). We don't currently have plans to make that available in this task for the on-prem product, so I'm going to close this but I'll give some information.

We are moving away from these tasks this quarter, to a new model where we give you authentication tasks that you run up front, and then we get out of your way and you can run the tools directly as you would from the command line (NuGet, dotnet, etc.). With that said, NuGet just released this built-in capability in 5.1, so you could get it by calling NuGet push directly (and not use the task). 

We are looking forward to getting these new auth tasks out as soon as possible so you don't rely on us updating our tasks to get the latest and greatest from other tools.
