### ISSUE TITLE
[Maven 3] Fail to deploy to azure feeds

### ISSUE THREAD

**Issue by tao-zhang** [microsoft/azure-pipelines-tasks#10802]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven 3  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - Azure Pipelines
    - MyCompany/MyCompany/Pipeline-Java(Edit: sorry I have to hide the real project because security requirement)
- Agent - Hosted or Private:     
    - Hosted agent, Hosted Ubuntu 1604

## Issue Description

We try to leverage the nice feature 'Authenticate built-in Maven feeds' for our java project, but it fails to authenticate with Azure feeds. After some tests, we found the following facts:

- POM1:
```
<profiles>
    <profile>
        <id>azure</id>
        <distributionManagement>
            <repository>
                <id>visualstudio-com-mycompany</id>
                <url>https://mycompany.pkgs.visualstudio.com/_packaging/one/maven/v1</url>
            </repository>
        </distributionManagement>
        <repositories>
            <repository>
                <id>visualstudio-com-mycompany</id>
                <url>https://mycompany.pkgs.visualstudio.com/_packaging/one/maven/v1</url>
            </repository>
        </repositories>
    </profile>
</profiles>
```
- POM2

```
<project>
    ......
    <distributionManagement>
        <repository>
            <id>visualstudio-com-mycompany</id>
            <url>https://mycompany.pkgs.visualstudio.com/_packaging/one/maven/v1</url>
        </repository>
    </distributionManagement>
    <repositories>
        <repository>
            <id>visualstudio-com-mycompany</id>
            <url>https://mycompany.pkgs.visualstudio.com/_packaging/one/maven/v1</url>
        </repository>
    </repositories>
    .....
</project>
```

You can see, the difference is if \<distributionManagement\> and \<repositories\> are defined in \<profile\> or not

- Run 'mvn deploy' locally, both cases work fine. Of course, we set the correct credentials in local setting.xml
- Build from Azure pipeline, POM1 throws 'Not authorized' error while POM2 runs successfully as expected.

### Error logs
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project helloworld: Failed to retrieve remote metadata helloworld:helloworld:1.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata helloworld:helloworld:1.0-SNAPSHOT/maven-metadata.xml from/to visualstudio-com-one (https://mycompany.pkgs.visualstudio.com/_packaging/one/maven/v1): Not authorized -> [Help 1] |  
-- | --
  | [ERROR] |  
  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. |  
  | [ERROR] Re-run Maven using the -X switch to enable full debug logging. |  
  | [ERROR] |  
  | [ERROR] For more information about the errors and possible solutions, please read the following articles: |  
  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException |  
  | /usr/share/apache-maven-3.6.1/bin/mvn failed with return code: 1 |  
  | Could not retrieve code analysis results - Maven run failed. |  
  | ##[error]Build failed.
```

**Comment by elbatk** [comment]
hey @tao-zhang , I see you're using the Maven task, and was wondering if you wanted to try our new [Maven Authenticate Task](https://docs.microsoft.com/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops) and see how it works for you? 

We are trying to transition from those heavy protocol tasks (like Maven, or NuGet) towards lighter-weight authentication tasks that handles auth for you and then lets you run whatever tooling or scripts you want like you could from the command line. 

Please let us know the behavior of the new tasks if you don't mind, and also the behavior you would expect, which it sounds like is that both of those examples would succeed?

**Comment by tao-zhang** [comment]
Hi @elbatk, thank you for your comment. I have a question after reading the task document, who adds the password inside <server> element? In the inputs, I don't see 'password' as an input.

**Comment by elbatk** [comment]
That password gets filled by the authentication task, and it uses the PAT from the build, the System.AccessToken I believe. @aasim could expand on this if I'm wrong :)

**Comment by aasim** [comment]
@tao-zhang @elbatk 
The password will be set by the authentication task, and it does use the PAT from the build.

**Comment by aasim** [comment]
@tao-zhang Let me know if you hit any issues while using the task, I can help you through your setup as well.

**Comment by tao-zhang** [comment]
@aasim I can understand the authentication task can use PAT for password. But for 'feeds outside your organization', for example, Nexus on premise, how does this task get password?

**Comment by aasim** [comment]
@elbatk You're correct, however they will have to setup a "Maven" "Service Connection" to be able to add to the maven authenticate task.

@tao-zhang Yes, for Nexus, you should be able to setup a "Service Connection" to add that password to your settings.xml file. For your case follow these steps.

1. Go to "Project Settings" > "Service Connections", and add a new service connection of type "Maven".
![image](https://user-images.githubusercontent.com/169527/65533781-23a46780-deb3-11e9-8999-78d3d1c22a7e.png)
2. Fill out the details for the service connection, making sure the repository id matches the repostiory id in your pom.xml
![image](https://user-images.githubusercontent.com/169527/65533897-5c444100-deb3-11e9-9137-baee30a4aadb.png)
3. In your "Maven Authenticate" task, select your service connection from the "Credentials for repositories outside this organization/collection" dropdown.
![image](https://user-images.githubusercontent.com/169527/65534078-a6c5bd80-deb3-11e9-960c-9c8195001337.png)

Once this is setup, the build agent will add the new Nexus connection to the settings.xml file with the password or auth token. You can read more about Service Connections [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-maven).

**Comment by aasim** [comment]
Hi @tao-zhang - let me know if that helped, or if you have any more questions.

Aasim

**Comment by tao-zhang** [comment]
Thank you a lot guys!

**Comment by aasim** [comment]
@tao-zhang glad it helped. We'd welcome any feedback on the documentation or on the new task. I am closing this issue as fixed.
