### ISSUE TITLE
DockerV2 - Existing Service Connection Endpoint in Azure DevOps Does Not Work with V2

### ISSUE THREAD

**Issue by denhsu** [microsoft/azure-pipelines-tasks#10811]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

With DockerV2, the existing service connection in Azure DevOps is not working anymore.  We have a service connection to a Azure Resource Group where it has contributor access to that resource group.  

With DockerV1, we can just use our existing service connection.  With DockerV2, it does not show up in the drop down anymore.  We have to create a  new docker registry service connection endpoint specifically for that azure container registry.  

Is it feature by designed or bug?

Thanks,
Dennis

**Question, Bug, or Feature?**  
*Type*: Bug or Question

**Enter Task Name**: DockerV2

list here (V# not needed):   V2
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Build: https://dev.azure.com/wcbbc/DevOps-Assessments/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=936

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:   Hosted Ubuntu 1604

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

Docker V1: use existing service connection
![image](https://user-images.githubusercontent.com/8570762/60555184-5c87d280-9cf0-11e9-8d36-2b2893aafd3e.png)

Docker V2:
![image](https://user-images.githubusercontent.com/8570762/60555202-70333900-9cf0-11e9-9cf0-16488df7ee3e.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by shashankbarsin** [comment]
@denhsu this was by design. This change was done to have all container related tasks - Docker, KubernetesManifest just accept one standard kind of service connection associated with container registries and have all Azure specific option folded under this service connection.
