### ISSUE TITLE
installing Azure Devops Server 2019 Update1 RC1 over Devops Server 2019.01 warns about  Azure File Copy task version

### ISSUE THREAD

**Issue by spashx** [microsoft/azure-pipelines-tasks#10814]
Installing Azure Devops Server 2019 Update1 RC1 over Devops Server 2019.01.
The last configuration wizard throw this warning:

`[2019-07-03 09:54:34Z][Warning] Updating an existing task Azure File Copy (eb72cb01-a7e5-427b-a8a1-1b31ccac8a43) with an older version 1.0.144. Please contact Task author to bump their task version, the service already had version 1.0.145 in record. Reference github repository's contributors to find Task author. (https://github.com/Microsoft/vsts-tasks).`

Does it mean the RC1 includes a older task version compared to the 2019.01 ?

**Comment by kmkumaran** [comment]
@spashx - Thanks for reporting. We also identified this issue and it is fixed with #10742 & #10751 . There is no functional issue with Azure file copy task, hence you can ignore this warning in 2019.01. The fix will be present in 2019 update 1 RC2.
