### ISSUE TITLE
Azure App Service Deploy fails behind proxy

### ISSUE THREAD

**Issue by TWJH** [microsoft/azure-pipelines-tasks#10815]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment

## Environment
- Server - Azure DevOps Server 2019
    
    - If using TFS on-premises, provide the version: 17.143.28621.4 (AzureDevOps2019)

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

   - Windows Server 2016 (version 1607)
   - Agent Version: 2.144.2

## Issue Description

Task: Azure App Service Deploy.
Version: 3.4.16.

When attempting to deploy to Azure app service from behind our corporate proxy, the task fails with the following error:

``` 
[error]Error: Failed to fetch App Service '*****' publishing credentials. Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80
```

The private agents I have running have all be configured following this guide https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows and are able to communicate through our proxy and download packages from nuget without issue as part of our build pipelines. It appears that the Azure App Service Deploy task is using node to communicate with Azure but node doesn't appear to have any knowledge of the proxy config that has been applied to the agent.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
[Release.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3354469/Release.zip)

**Comment by vincentdass** [comment]
@TWJH , Can you please share the debug logs for the release?
Also, the above error is thrown when it tries to hit the "management.azure.com" URL.
Is the above URL added in proxy list?
You can bypass the URL by following the steps [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows#specify-proxy-bypass-urls). This requires agent restart.

**Comment by TWJH** [comment]
@vincentdass , I have attached the worker logs, I assume that is the debug log you are referring to?

The only route out through to the internet from our corporate network is through the proxy server, so there is no way to bypass it by using the .proxybypass file.


[Worker_20190705-064752-utc.log](https://github.com/microsoft/azure-pipelines-tasks/files/3361462/Worker_20190705-064752-utc.log)

**Comment by vincentdass** [comment]
@TWJH , Please add a variable `system.debug` to `true` and rerun the release and share the release logs for that

**Comment by TWJH** [comment]
@vincentdass , Please see attached logs.

[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3391081/logs.zip)
[Worker_20190715-064513-utc.log](https://github.com/microsoft/azure-pipelines-tasks/files/3391091/Worker_20190715-064513-utc.log)

**Comment by vincentdass** [comment]
@TWJH , Can you check if you are able to ping the Application URL, SCM URL and `login.windows.net` and `management.azure.com`?
The above sites are hit by the taks at runtime.

**Comment by TWJH** [comment]
@vincentdass Yes I can ping all of the above listed endpoints.

**Comment by TWJH** [comment]
@vincentdass Are there any further updates to this issue please?

**Comment by RoshanKumarMicrosoft** [comment]
@vincentdass  can you please have a look into it ?

**Comment by MarkoMei** [comment]
As azure-pipeline-tasks uses typed-rest-client, this might give more details: https://github.com/microsoft/typed-rest-client/issues/163

**Comment by TWJH** [comment]
@vincentdass I have updated to DevOps server 2019 to "17.153.29207.5 (AzureDevOps2019.Update1) " and the problem still persists. Is there any update to this bug being resolved please?

```
2019-08-27T13:43:26.3513063Z ##[section]Starting: Deploy to staging slot
2019-08-27T13:43:26.4001448Z ==============================================================================
2019-08-27T13:43:26.4001635Z Task         : Azure App Service deploy
2019-08-27T13:43:26.4001862Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2019-08-27T13:43:26.4002015Z Version      : 3.4.29
2019-08-27T13:43:26.4002088Z Author       : Microsoft Corporation
2019-08-27T13:43:26.4002190Z Help         : [More information](https://aka.ms/azurermwebdeployreadme)
2019-08-27T13:43:26.4002284Z ==============================================================================
2019-08-27T13:43:28.1560454Z Got connection details for Azure App Service:'discoverdev'
2019-08-27T13:44:31.7412416Z ##[error]Error: Failed to fetch App Service 'discoverdev-staging' publishing credentials. Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80
2019-08-27T13:44:31.7488123Z ##[section]Finishing: Deploy to staging slot
```

**Comment by vincentdass** [comment]
@SumiranAgg , please look into this.

**Comment by TWJH** [comment]
@vincent1173 @SumiranAgg @RoshanKumarMicrosoft Hi, could you tell me if this bug being investigated at all please?

**Comment by eaarora-ms** [comment]
@TWJH  Are you still facing this issue?

**Comment by TWJH** [comment]
@eaarora-ms Yes I am.

**Comment by TWJH** [comment]
I have updated my DevOps server installation to 2019 1.1 (17.153.29522.3 (AzureDevOps2019.Update1.1)), updated the agents and the issue persists.

**Comment by SumiranAgg** [comment]
@TWJH Apologies for delay. Are you still seeing the issue?
Just FYI, we do pickup proxy settings from agent and handle it in task execution. Are you able to run other tasks (Working with some other azure resource) successfully?

**Comment by TWJH** [comment]
@SumiranAgg Hi, I have just tried again and get the following error:


`Error: Failed to fetch App Service 'discoverdev-staging' publishing credentials. Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80`

We have no other tasks running against azure. Only releasing to app services.

**Comment by 20shivangi** [comment]
@TWJH Please provide full debug logs by setting 'system.debug' to true in your pipeline.

**Comment by TWJH** [comment]
Hello. Is there any progress with fixing this issue please?

**Comment by TWJH** [comment]
After further investigation ​we had to remove the agent, then reinstall after adding the VSTS_HTTP_PROXY environment variable hack with the proxy details. The connectivity is then established successfully.

Please close this problem. Thank you for your help.
