### ISSUE TITLE
NodeTool doesn't retry for socket hangups

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-tasks#10810]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NodeToolV0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server : AzurePipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Dnceng

- Agent - Hosted or Private: 
    - Private (NetCorePublic-Pool)
    - If using private agent, provide the OS of the machine running the agent and the agent version:  Ubuntu 16.04 

## Issue Description
This line:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NodeToolV0/nodetool.ts#L136 

Seems to not successfully retry when facing intermittent connection issues:

Example builds: For example: https://dev.azure.com/dnceng/public/_build/results?buildId=248355

### Task logs
( See linked build)

### Error logs

```
##[section]Starting: Install Node 10.x
==============================================================================
Task         : Node.js tool installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
Version      : 0.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js
==============================================================================
##[error]socket hang up
##[section]Finishing: Install Node 10.x

```

**Comment by stephenmichaelf** [comment]
Retry code is here: https://github.com/microsoft/azure-pipelines-tool-lib/blob/e545bc7fbdc8d0f94afb90a9841f53c5c52050f0/tool.ts#L228

**Comment by MattGal** [comment]
@stephenmichaelf I saw that, yes.  Just to be sure I'm understood though, this issue is asking to have retries for the case where the socket hangs up and there is no HTTP response code.

**Comment by MattGal** [comment]
@stephenmichaelf is there any chance you'd take a look at my response?  Has been about a year.

**Comment by MattGal** [comment]
I would very much like this retry to be implemented, please don't stale-ify this issue github bot.

**Comment by MattGal** [comment]
The lack of response from anyone on azure-pipelines-tasks is frustrating, but I'll try here one last time.

**Comment by anatolybolshakov** [comment]
Hi @MattGal sorry for delay - probably we could just enhance this to make retry for cases when error is happening - let us take a look

**Comment by AnnaOpareva** [comment]
Hi @MattGal. The latest version of the NodeTool task (v 0.189.0) by default contains two retries for some of the "socket hang up" errors. Could you please share logs for the latest task version that contains this error with checked “Enable system diagnostics”? We need to understand if it is required to increase the number of retries and add an additional input to the task that will allow setting a custom number of retries or there are problems with the catching of any specific network errors, since "socket hang up" is a generic issue and there are several issues that could be hidden by it.

**Comment by MattGal** [comment]
@AnnaOpareva I haven't actually seen an instance of this in some time, so I think it's OK to close this given there is some form of retry added, and open a new issue if we do see it again.

**Comment by AnnaOpareva** [comment]
Hi @MattGal. In this way, I am closing this issue. Feel free to create a new one if you will see this issue again.
