### ISSUE TITLE
Nuget Push Timeout

### ISSUE THREAD

**Issue by panso13** [microsoft/azure-pipelines-tasks#10827]
Task "Nuget" command "Push".
Is it possible to add "Timeout" or "Arguments" input field to the task so that it will be possible to use it for big packages that takes more than 300 sec to upload? Field "Nuget Arguments" was available in the deprecated task "NuGet Publisher".

I know that I can use "custom" and provide any arguments and I already did it as an workaround, but after selecting "custom" we cannot use "Service connection" to external nuget server. Service connection is very helpful in our case - we have one server that is used from multiple build/release definitions, so no need to remember/change and expose apikey to this server. Sure, I can think about workaround again and keep apikey in "Library" even encrypted, but IMHO "ServiceConnection" and "TimeOut: in task Nuget Push will be very useful.

Thank you.

**Comment by JamieO53** [comment]
It will be very useful.

**Comment by tkrick** [comment]
Hey thanks for the enhancement idea. Our stance with respect to tasks is moving more where we invest less in the client wrapping tasks and more in the authenticate tasks (à la [Twine Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops) but for nuget.exe). Customers would then own calling the clients in their yml pipelines which would allow for this level of flexibility. We are actively working on nuget.exe authenticate task.

As a result, it is unlikely we will get to feature enhancements for existing tasks.

**Comment by aasim** [comment]
The Nuget Authenticate task has been released. You can find the documentation for it here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops.
