### ISSUE TITLE
Azure pipelines - upload a custom task? Is there a task repository?

### ISSUE THREAD

**Issue by drauch** [microsoft/azure-pipelines-tasks#10825]
It looks like Azure Pipelines comes with a preconfigured list of tasks which can be used to "generate " parts of YAML-based pipeline definitions.

Questions:

* Is there a way to add to this list of preconfigured tasks?
* Is there a way to include some kind of repository where more tasks are available?

We're a vendor and want to integrate into the major CI vendors, and we haven't found a way to integrate one of our steps (which is behind the scenes a PowerShell script call) into Azure Pipelines.

Best regards,
D.R.

**Comment by kmkumaran** [comment]
@drauch - Azure Pipelines offers extensibility where users can build their own extensions including tasks and integrate with. 
Refer this [link ](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops) to learn more about extensions and this [link ](https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops) to specifically know how to add custom tasks to the already existing tasks list.

**Comment by drauch** [comment]
Thank you, that answers my second question. My first question stands, is there a way to be included into the list of preconfigured tasks? Do you have to apply for it? Is there a selection process?

**Comment by kmkumaran** [comment]
All tasks shipping from this repo, are the in-built tasks. Typically this is a tight list and are supported by our engineering team. We can evaluate if there is any request for any specific task. For user managed tasks, our recommendation is to take the extension route.

**Comment by drauch** [comment]
OK, thank you for your information!
