### ISSUE TITLE
NuGet restore work different in VS and AD

### ISSUE THREAD

**Issue by FixRM** [microsoft/azure-pipelines-tasks#10824]
## Requred information
*Type*: Bug
**NuGetCommandV2**

## Environment
Azure Pipelines. Account: fixrm. Pipeline: LastSchedule CI
Hosted agent, default queue.
NuGet v 5.1.0

## Issue Description
Solution contains a project that was added as a folder (solution -> add -> existing website). This project use NuGet's and has packages.config. When I restore packages in VS, "pakages" folder is created for this website, but when I restore packages with AD NuGet task this folder is not created for some reasons.

This NuGets (spkl) contains build tools required to build solution locally as well as remotely. How can I get same results in both environments?

**Comment by aasim** [comment]
Hi - We have recently released the NuGetAuthenticate task that can be used in a pipeline to authenticate with Azure Artifacts and other NuGet repositories. The design philosophy behind this task is that we would authenticate all the repositories you describe in this task, and get out of the way leaving you fully in control of running your `nuget` or `dotnet` commands in the pipeline as you see fit.

You can read more about the NuGetAuthenticate task [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops). It also gives some examples on how to configure the task.

I think this task is a good fit for your use case, you can use the NuGetAuthenticate task to perform the authentication, and then use the same nuget command you use locally to run in the pipeline. Let me know if you need any more help in setting this up.

Aasim
