### ISSUE TITLE
Download Artifact task failing in getBuildApi with tunnel error

### ISSUE THREAD

**Issue by vladnega** [microsoft/azure-pipelines-tasks#10835]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadBuildArtifactsV0

## Environment
- Server - Azure Pipelines (YAML)
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/lloydslondon/Lloyds/_build/results?buildId=5669&view=results

- Agent - Hosted  
    - If using Hosted agent, provide agent queue name: Lloyds-Hosted

## Issue Description

When running a YAML pipeline, it always fails at the *Download Artifact* task from the deployment stage. Here is a link:
https://dev.azure.com/lloydslondon/Lloyds/_build/results?buildId=5669&view=logs&j=22e8b1b6-9aa9-5014-5ac4-2849544435ca&t=d7adc642-3bc9-5b30-700a-e6d1dc3c194b&l=136

### Task logs

Here are some truncated logs:
```
...

##[debug]Agent.ProxyUrl=http://proxy.***.net:8080 |  
##[debug]Agent.ProxyUsername=DOMAINNAME\user_name |  
##[debug]Agent.ProxyPassword=*** |  
##[debug]Agent.ProxyBypassList=undefined

...

TUNNEL: making CONNECT request |  
  | Error: in getBuildApi, so retrying => retries pending  : 4 |  
  | TUNNEL: tunneling socket could not be established, cause=socket hang up |  
  | Error: socket hang up |  
  | at createHangUpError (_http_client.js:253:15) |  
  | at Socket.socketOnEnd (_http_client.js:345:23) |  
  | at emitNone (events.js:91:20) |  
  | at Socket.emit (events.js:185:7) |  
  | at endReadableNT (_stream_readable.js:974:12) |  
  | at _combinedTickCallback (internal/process/next_tick.js:80:11) |  
  | at process._tickCallback (internal/process/next_tick.js:104:9)

...

##[error]Error: tunneling socket could not be established, cause=socket hang up
```

I prefer to send the full logs ZIP file via email and not post it here.

## Troubleshooting

**I have already identified the issue and I have the fix.** It is related to the version of the `tunnel` dependency. I will create a pull request shortly, but to the [azure-devops-node-api](https://github.com/microsoft/azure-devops-node-api) repo, as that's where the fix needs to go. I assume you will then change the version to your `azure-devops-node-api` dependency in the `DownloadBuildArtifactsV0` task.

### Error logs

```
Error: tunneling socket could not be established, cause=socket hang up
```

**Comment by vladnega** [comment]
Made a mistake, this is a privately hosted agent:

OS: Windows Server 2016 Standard
Agent Version: 2.149.2

**Comment by Lovakumar** [comment]
@vladnega Download Build Artifacts task doesn't work with proxy configurations. Please consider using Publish Pipeline Artifacts task and Download Pipeline Artifacts task in YAML pipelines.

**Comment by vladnega** [comment]
@Lovakumar after applying my fix, the *Download Artifact* worked using the proxy configurations.

**Comment by Lovakumar** [comment]
@vladnega that's great. Can you please raise a PR against the right repo.

**Comment by vladnega** [comment]
@Lovakumar sure, doing it now.

**Comment by Lovakumar** [comment]
@vladnega As per above comments, I am assuming you will be raising a PR to fix this.

**Comment by vladnega** [comment]
@Lovakumar I have raised [this](https://github.com/microsoft/azure-devops-node-api/pull/332) PR 25 days ago, but @damccorm didn't merge it.

**Comment by Lovakumar** [comment]
@omeshp can you please check if new tunnel version is resolving the issue. If yes, update task to take dependency on newer version of azure-devops-node-api.

**Comment by Lovakumar** [comment]
@omeshp  can you please check if new tunnel version is resolving the issue. If yes, update task to take dependency on newer version of azure-devops-node-api.

**Comment by pauldoom** [comment]
@Lovakumar and @omeshp - Adding this as a vote to please resolve ASAP.   This is a blocker for us using deployment stages, which means coding in ugly workarounds for many pipelines we are trying to port over to Azure Pipelines.

**Comment by Lovakumar** [comment]
@pauldoom if you are just onboarding to Azure Pipelines, can you please consider using Pipeline Artifacts instead Build artifacts. Our future investments will be in [Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=classic).
