### ISSUE TITLE
Spawning terminals for agent running on self hosted windows runner

### ISSUE THREAD

**Issue by shivamg7** [microsoft/azure-pipelines-tasks#10834]
Not sure if this is the appropriate forum to post this query

## Issue Description
Couldn't find any task for spawning a cmd terminal.
My use case is like this.
I would like to use my self hosted windows runner for running nightly UI tests.
My tech stack looks like this:
Django Rest framework
Postgres
Angular

I fetch latest commits from each of the repositories daily, bring the services up as I would on my
local system. 
I have another repository for running my UI tests using selenium on Chrome. This is the repository which has the pipeline which would trigger my agent.
Any kind of resources or advice would really help
Thanks.

**Comment by kaadhina** [comment]
There is a cmd task using which you can spawn your own test runners. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml

**Comment by wocar** [comment]
But you have to rerun the pipe every time to debug it. Might be easier if you could spawn a terminal instead
