### ISSUE TITLE
TFS Specific Test Context Information is absent

### ISSUE THREAD

**Issue by Amax165** [microsoft/azure-pipelines-tasks#10866]
While executing tests from a test plan and accessing Test Context the following entries do not exist:
**TestCaseID
TestConfigurationId
 **

The task is: **Visual Studio Test (version 2)**

## Environment
- Server - **Azure DevOps Server 17.143.28621.4**
- Agent - Private, version 2.144.2,
- Platform OS: Windows Server 2012 R2
- MSTest.TestFramework version 1.4.0
- MSTest.TestAdapter version 1.4.0

## Issue Description
The task is: **Visual Studio Test (version 2)**. The task is configured to run using Test Plan.
When Test Context Properties are accessed, only the following values are present:
TestRunDirectory
DeploymentDirectory
ResultsDirectory
TestRunResultsDirectory
TestResultsDirectory
TestDir
TestDeploymentDir
TestLogsDir
TestConfiguration

Those TFS Specific entries are not present:
**TestCaseID
TestConfigurationId**

Test Configuration ID can be obtained from Environment Variables as: **TE.TestPlanConfigId**

The issue is similar to:
https://github.com/microsoft/testfx/issues/541
https://github.com/microsoft/azure-pipelines-tasks/issues/9929

Although the entry **TCMTestPropertiesJSONFile**  also doesn't exist in the test context.

**Comment by kaadhina** [comment]
Hi, thank you for reporting this. This was a known bug and has since been fixed from Azure Devops Server 2019 onwards.

**Comment by Amax165** [comment]
We are using Azure DevOps 2019 and the bug is still reproducing.

**Comment by kaadhina** [comment]
The version mentioend above is Azure DevOps Server 17.143.28621.4
Can you please confirm you upgraded to 2019 now and still face this?

**Comment by Amax165** [comment]
Azure DevOps server 17.143.28621.4 is Azure Devops 2019.

**Comment by ChuckBuford** [comment]
We are having the same problem. 

All the details are the same, but we are using 17.143.28912.1 (AzureDevOps2019.0.1)

Has there been any movement on this bug for the past few months?

**Comment by Amax165** [comment]
> We are having the same problem.
> 
> All the details are the same, but we are using 17.143.28912.1 (AzureDevOps2019.0.1)
> 
> Has there been any movement on this bug for the past few months?

I am not aware of any progress regarding this bug.
