### ISSUE TITLE
Build solutions SSIS projects with password

### ISSUE THREAD

**Issue by onooka** [microsoft/azure-pipelines-tasks#10863]
Hi

I am using the task, and works very well (without password) !!!
But when I use this Task; solutions SSIS with password, example ProtectionLevel = EncryptAllWithPassword and the password. The build Pipeline show error.

While I am using PowerShell Task to solve the build.

It would be great if the Task accept the passwords !!!

![Build SSIS with password (1)](https://user-images.githubusercontent.com/41794338/60911009-cc91dd80-a247-11e9-8358-d9c29236a2f0.jpg)

![Build SSIS with password (2)](https://user-images.githubusercontent.com/41794338/60911019-d287be80-a247-11e9-91b1-59d7bd79d291.jpg)

Best regards
Ernesto Ono

**Comment by kmkumaran** [comment]
@onooka - It is not clear what the failure is. Can you also add the failure details so that it can be investigated accordingly.

**Comment by onooka** [comment]
This is the failure, the solutions has password

![Build SSIS with password (5)](https://user-images.githubusercontent.com/41794338/60974304-76787500-a2ef-11e9-9236-d8ecce411d41.jpg)


![Build SSIS with password (3)](https://user-images.githubusercontent.com/41794338/60974041-f9e59680-a2ee-11e9-99ea-e2e9e2f6207a.jpg)


![Build SSIS with password (4)](https://user-images.githubusercontent.com/41794338/60974053-fce08700-a2ee-11e9-8403-646ccb2baee0.jpg)


Best Regards
E.O.

**Comment by onooka** [comment]
This is the solution

[Proyecto_SSIS.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3377795/Proyecto_SSIS.zip)

Password: 123

Best regards
E.O.

**Comment by moswald** [comment]
Can you not include those parameters in the `MSBuild arguments` field? I would expect that to work fine.
