### ISSUE TITLE
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1

### ISSUE THREAD

**Issue by singhbibek** [microsoft/azure-pipelines-tasks#10878]
Hi,

I am using .Net Corfe 2.1 framework for my project and using Nunit + MOQ to do unit testing for it.
I have written approx 200 test cases, all test cases are passing in my local VS2017. But when i am building my solution using azure devops it's failing in Test task with 3 test cases and rest are passing. I debugged those failed test cases but all assert are passing don't know what wrong with azure devops test task.
I am using  NET Core  Task version 2.* ( also checked all existing versions ).

below is the test task result-

##[section]Starting: Test
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.154.6
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
[command]C:\windows\system32\chcp.com 65001
Active code page: 65001
[command]"C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\CustomerControllerAPITests\CustomerControllerAPITests.csproj --logger trx --results-directory d:\a\_temp --configuration Release --collect "Code coverage"
Build started, please wait...
C:\Program Files\dotnet\sdk\2.2.105\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.StaticFiles" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\CustomerControllerAPITests\CustomerControllerAPITests.csproj]
Build completed.

Test run for d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\CustomerControllerAPITests\bin\Release\netcoreapp2.1\CustomerControllerAPITests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Skipped  T20_CustomerGroup_WebAPI_005_Create_P_MR_CollidingCustomerGroupId
Skipped  T20_CustomerGroup_WebAPI_006_Create_P_MR_CollidingCustomerGroupName
Skipped  T20_CustomerGroup_WebAPI_007_Create_N_Req_customerGroupId
Skipped  T20_CustomerGroup_WebAPI_008_Create_N_Req_customerGroupName
Skipped  T20_CustomerGroup_WebAPI_009_Create_N_Req_createUserId
Skipped  T20_CustomerGroup_WebAPI_010_Create_N_Req_createDateime
Skipped  T20_CustomerGroup_WebAPI_016_Create_N_Pre_customerGroupId
Skipped  T20_CustomerGroup_WebAPI_017_Create_N_Pre_customerGroupName
Skipped  T20_CustomerGroup_WebAPI_019_Read_P_MinMax_GetWithCustomerGroupId_Max
Skipped  T20_CustomerGroup_WebAPI_020_Read_N_Pre_GetWithCustomerGroupId_NotExists
Skipped  T20_CustomerGroup_WebAPI_022_Read_P_MinMax_GetWithCustomerGroupName_Max
Skipped  T20_CustomerGroup_WebAPI_023_Read_N_Pre_GetWithCustomerGroupName_NotExists
Skipped  T20_CustomerGroup_WebAPI_028_Update_N_MR_CollidingCustomerGroupName
Skipped  T20_CustomerGroup_WebAPI_034_Update_N_Pre_customerGroupId
Skipped  T20_CustomerGroup_WebAPI_035_Update_N_Pre_customerGroupName
Skipped  T20_CustomerGroup_WebAPI_037_Delete_P_MinMax_Max
Skipped  T20_CustomerGroup_WebAPI_038_Delete_N_Pre_NotExists
Skipped  T20_Customer_WebAPI_005_Create_P_MR_CustomerID
Skipped  T20_Customer_WebAPI_006_Create_P_MR_CustomerName
Skipped  T20_Customer_WebAPI_019_Create_N_Pre_AlreadyExists
Skipped  T20_Customer_WebAPI_020_Create_N_Pre_CustomerStatusCode
Skipped  T20_Customer_WebAPI_021_Create_N_Pre_customerId
Skipped  T20_Customer_WebAPI_022_Create_N_Pre_salesTeamId
Skipped  T20_Customer_WebAPI_023_Create_N_Pre_financeTeamId
Skipped  T20_Customer_WebAPI_024_Create_N_Pre_productionTeamId
Skipped  T20_Customer_WebAPI_025_Create_N_Pre_careRatingCode
Skipped  T20_Customer_WebAPI_026_Create_N_Pre_createUserId
Skipped  T20_Customer_WebAPI_027_Create_N_Pre_lastUpdateUserId
Skipped  T20_Customer_WebAPI_043_Update_P_MR_CollidingCustomerName
Skipped  T20_Customer_WebAPI_044_Update_P_MR_CollidingCustomerTypeCode
Skipped  T20_Customer_WebAPI_050_Update_N_Pre_AlreadyExists
Skipped  T20_Customer_WebAPI_051_Update_N_Pre_CustomerStatusCode
Skipped  T20_Customer_WebAPI_052_Update_N_Pre_customerId
Skipped  T20_Customer_WebAPI_053_Update_N_Pre_salesTeamId
Skipped  T20_Customer_WebAPI_054_Update_N_Pre_financeTeamId
Skipped  T20_Customer_WebAPI_055_Update_N_Pre_productionTeamId
Skipped  T20_Customer_WebAPI_056_Update_N_Pre_careRatingCode
Skipped  T20_Customer_WebAPI_057_Update_N_Pre_createUserId
Skipped  T20_Customer_WebAPI_058_Update_N_Pre_lastUpdateUserId
Skipped  T20_Customer_WebAPI_059_Update_N_VR_customerStatusCode
Skipped  T20_Customer_WebAPI_064_Delete_P_MinMax_Min
Skipped  T20_Customer_WebAPI_065_Delete_P_MinMax_Max
M i c r o s o f t   ( R )   C o v e r a g e   C o l l e c t i o n   T o o l   V e r s i o n   1 5 . 0 . 3 0 3 1 9 . 3 0 0 5 
 
 
 C o p y r i g h t   ( c )   M i c r o s o f t   C o r p o r a t i o n .     A l l   r i g h t s   r e s e r v e d . 
 
 
 
 
 Skipped  T20_Customer_WebAPI_066_Delete_P_Cascading_Service
Skipped  T20_Customer_WebAPI_067_Delete_N_Pre_NotExists
Skipped  T20_ServiceAgreement_WebAPI_035_Read_N_MinMax_GetWithCustomerId_NotExists
Results File: d:\a\_temp\VssAdministrator_fv-az626_2019-07-11_08_28_47.trx

Attachments:
  d:\a\_temp\5d642dea-9ea8-4193-95c2-6c8d524c735f\VssAdministrator_fv-az626_2019-07-11.08_28_30.coverage

Total tests: 108. Passed: 63. Failed: 0. Skipped: 45.
Test Run Successful.
Test execution time: 15.3435 Seconds
[command]"C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.csproj --logger trx --results-directory d:\a\_temp --configuration Release --collect "Code coverage"
Build started, please wait...
C:\Program Files\dotnet\sdk\2.2.105\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.StaticFiles" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.csproj]
Build completed.

Test run for d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\bin\Release\netcoreapp2.1\ServiceAgreementControllerAPITests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   T20_ServiceAgreement_WebAPI_002_Create_P_MinMax_Max
Error Message:
   Expected: 201
  But was:  400

Stack Trace:
   at ServiceAgreementControllerAPITests.ServiceAgreementControllerAPITests.T20_ServiceAgreement_WebAPI_002_Create_P_MinMax_Max() in d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.cs:line 64

Failed   T20_ServiceAgreement_WebAPI_003_Create_P_DefaultValue_All
Error Message:
   Expected: 201
  But was:  400

Stack Trace:
   at ServiceAgreementControllerAPITests.ServiceAgreementControllerAPITests.T20_ServiceAgreement_WebAPI_003_Create_P_DefaultValue_All() in d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.cs:line 90

Failed   T20_ServiceAgreement_WebAPI_004_Create_P_DefaultValue_None
Error Message:
   Expected: 201
  But was:  400

Stack Trace:
   at ServiceAgreementControllerAPITests.ServiceAgreementControllerAPITests.T20_ServiceAgreement_WebAPI_004_Create_P_DefaultValue_None() in d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.cs:line 122

Skipped  T20_ServiceAgreement_WebAPI_005_Create_P_MR_CollidingServiceAgreementId
Skipped  T20_ServiceAgreement_WebAPI_006_Create_P_MR_CollidingServiceAgreementName
Skipped  T20_ServiceAgreement_WebAPI_007_Create_N_Req_serviceAgreementName
Skipped  T20_ServiceAgreement_WebAPI_008_Create_N_Req_serviceAgreementStartDate
Skipped  T20_ServiceAgreement_WebAPI_009_Create_N_Req_serviceAgreementEndDate
Skipped  T20_ServiceAgreement_WebAPI_010_Create_N_Req_isTrialInvoiced
Skipped  T20_ServiceAgreement_WebAPI_011_Create_N_Req_CustomerId
Skipped  T20_ServiceAgreement_WebAPI_012_Create_N_Req_briefCareRatingCode
Skipped  T20_ServiceAgreement_WebAPI_018_Create_N_Pre_AlreadyExists
Skipped  T20_ServiceAgreement_WebAPI_019_Create_N_Pre_NotExists_Ref_RefDB
Skipped  T20_ServiceAgreement_WebAPI_020_Create_N_Pre_NotExists_Ref_UserMgmgDB
Skipped  T20_ServiceAgreement_WebAPI_021_Create_N_Pre_NotExists_Ref_Customer
Skipped  T20_ServiceAgreement_WebAPI_022_Create_N_Pre_NotExists_Ref_TEAM
Skipped  T20_ServiceAgreement_WebAPI_023_Create_N_Pre_NotExists_Ref_TEAM
Skipped  T20_ServiceAgreement_WebAPI_024_Create_N_Pre_NotExists_Ref_TEAM
Skipped  T20_ServiceAgreement_WebAPI_025_Create_N_Pre_NotExists_Ref_CustomerBrief
Skipped  T20_ServiceAgreement_WebAPI_026_Create_N_Pre_NotExists_Ref_RefDB
Skipped  T20_ServiceAgreement_WebAPI_027_Create_N_Pre_NotExists_Ref_UserMgmtDB
Skipped  T20_ServiceAgreement_WebAPI_028_Create_N_Pre_NotExists_Ref_UserMgmtDB
Skipped  T20_ServiceAgreement_WebAPI_031_Create_N_VR_trialStartDate
Skipped  T20_ServiceAgreement_WebAPI_032_Create_N_VR_serviceAgreementStatusCode
Skipped  T20_ServiceAgreement_WebAPI_038_Create_N_VR_briefCareRatingCode
Skipped  T20_ServiceAgreement_WebAPI_040_Read_P_MinMax_GetWithServiceAgreementId_Max
Skipped  T20_ServiceAgreement_WebAPI_041_Read_N_Pre_GetWithServiceAgreementId_NotExists
Skipped  T20_ServiceAgreement_WebAPI_043_Read_P_MinMax_GetWithCustomerId_Max
Skipped  T20_ServiceAgreement_WebAPI_044_Read_N_Pre_GetWithCustomerId_NotExists
Skipped  T20_ServiceAgreement_WebAPI_046_Read_P_MinMax_GetWithServiceAgreementName_Max
Skipped  T20_ServiceAgreement_WebAPI_047_Read_N_Pre_GetWithServiceAgreementName_NotExists
Skipped  T20_ServiceAgreement_WebAPI_052_Update_N_MR_CollidingServiceAgreementName
Skipped  T20_ServiceAgreement_WebAPI_058_Update_N_Pre_AlreadyExists
Skipped  T20_ServiceAgreement_WebAPI_059_Update_N_Pre_NotExists_Ref_RefDB
Skipped  T20_ServiceAgreement_WebAPI_060_Update_N_Pre_NotExists_Ref_UserMgmgDB
Skipped  T20_ServiceAgreement_WebAPI_061_Update_N_Pre_NotExists_Ref_Customer
Skipped  T20_ServiceAgreement_WebAPI_062_Update_N_Pre_NotExists_Ref_TEAM
Skipped  T20_ServiceAgreement_WebAPI_063_Update_N_Pre_NotExists_Ref_TEAM
Skipped  T20_ServiceAgreement_WebAPI_064_Update_N_Pre_NotExists_Ref_TEAM
Skipped  T20_ServiceAgreement_WebAPI_065_Update_N_Pre_NotExists_Ref_CustomerBrief
Skipped  T20_ServiceAgreement_WebAPI_066_Update_N_Pre_NotExists_Ref_RefDB
Skipped  T20_ServiceAgreement_WebAPI_067_Update_N_Pre_NotExists_Ref_UserMgmtDB
Skipped  T20_ServiceAgreement_WebAPI_068_Update_N_Pre_NotExists_Ref_UserMgmtDB
Skipped  T20_ServiceAgreement_WebAPI_080_Delete_P_MinMax_Max
Skipped  T20_ServiceAgreement_WebAPI_081_Delete_P_Cascading_Service
Skipped  T20_ServiceAgreement_WebAPI_082_Delete_N_Pre_NotExists
M i c r o s o f t   ( R )   C o v e r a g e   C o l l e c t i o n   T o o l   V e r s i o n   1 5 . 0 . 3 0 3 1 9 . 3 0 0 5 
 
 
 C o p y r i g h t   ( c )   M i c r o s o f t   C o r p o r a t i o n .     A l l   r i g h t s   r e s e r v e d . 
 
 
 
 
 Results File: d:\a\_temp\VssAdministrator_fv-az626_2019-07-11_08_28_56.trx

Attachments:
  d:\a\_temp\85f0552a-d464-4f8e-887d-c706c43351e2\VssAdministrator_fv-az626_2019-07-11.08_28_50.coverage

Total tests: 84. Passed: 38. Failed: 3. Skipped: 43.
Test Run Failed.
Test execution time: 6.5812 Seconds
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
##[error]Dotnet command failed with non-zero exit code on the following projects : d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.csproj
##[section]Async Command Start: Publish test results
Publishing test results to test run '1135406'
Test results remaining: 108. Test run id: 1135406
Publishing test results to test run '1135408'
Test results remaining: 84. Test run id: 1135408
Published Test Run : https://kantarware.visualstudio.com/KM-StrategicInitiative-ProductionPlatformServices/_TestManagement/Runs?runId=1135406&_a=runCharts
Published Test Run : https://kantarware.visualstudio.com/KM-StrategicInitiative-ProductionPlatformServices/_TestManagement/Runs?runId=1135408&_a=runCharts
##[section]Async Command End: Publish test results
##[section]Finishing: Test

**Comment by vineetmimrot** [comment]
Hey @singhbibek ,
Thanks for taking time to report the issue. This issue seems to be related to dotnet version. Task is using 2.2.105 dotnet version and it might be different on your local system. You can try out either of two things.

1. Use DotnetCore installer task to install the dotnet sdk of the same version installed on your local machine. Then try running the test.
2. Run the following command (change the paths), to check whether tests are running fine locally with this command.
"C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\Kantar.Media.CustomerAdmin.Application\Tests\NunitTests\ServiceAgreementControllerAPITests\ServiceAgreementControllerAPITests.csproj --logger trx --results-directory d:\a_temp --configuration Release --collect "Code coverage"

Please revert back if it doesn't work, we will redirect the issue to dotnet team.

**Comment by singhbibek** [comment]
Hi @vineetmimrot 
Thanks for the response I have executed both the steps test cases are passing in local machine but still failing in the DevOps.
So, still no luck found.
Please redirect the issue to respective team.

**Comment by singhbibek** [comment]
Any updates, i am stuck there.

**Comment by singhsarab** [comment]
@singhbibek All these three tests are failing for the same reason it seems. The error is similar
Expected: 201
But was: 400

What is this value that we are asserting on? Can you please make sure this is not dependent on the environment ?

Can you please describe what is that we are trying to test using these tests ?

**Comment by singhsarab** [comment]
@singhbibek Gentle ping!

**Comment by ShreyasRmsft** [comment]
Closing due to no response. please Re-open with requested details.
