### ISSUE TITLE
Cache key file paths incorrectly presented in container jobs

### ISSUE THREAD

**Issue by willsmythe** [microsoft/azure-pipelines-tasks#10870]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta/Cache

## Environment

Hosted

### Summary

File paths shown in the log for the Cache/CacheBeta task are incorrectly shown in their "host path" form when running in a [container job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml).

Note: this is only *minor presentation issue*. There is no impact on the functionality of the Cache/CacheBeta task in container jobs.

### Details

The output log for the Cache/CacheBeta task shows the paths to the files whose content was hashed to produce the cache key. For example, for the following YAML:

```yaml
steps:
- task: Cache@0
  inputs:
    key: $(Build.SourcesDirectory)/package.json
    path: node_modules
```

The log output looks like this:

```
Information, Using the following fingerprint argument (/mnt/a/1/s/package.json) as a file.
```

In a non-container job, the path correctly reflects the full path to the file based on the user's understanding of the value of `$(Build.SourcesDirectory)`, which can be shown by adding a simple debugging script step:

```yaml
steps:
- bash: printenv | grep BUILD
```

The problem is ... in a container job, the path currently presented in the log is not the path to the file from the container's perspective, but is instead the path from the agent's perspective which is running outside the container on the host machine.

The solution might be to call `TranslateToContainerPath` when presenting the file path in the log.

### Task logs

NA

## Troubleshooting

NA

### Error logs

NA

**Comment by ruffsl** [comment]
> Note: this is only minor presentation issue. There is no impact on the functionality of the Cache/CacheBeta task in container jobs.

This confused me for a while. For my setup, I wasn't sure if the cache key file and path folder was bing found correctly using absolute paths, so when switching to relative paths to try and debug, it was strange to see the log expand to paths non-existent in the container but present on the agent host.

BTW, either relative paths or absolute paths inside the container, but outside the build folder supported by the key and path parameters? I can't seem to key nor glob on paths in the container filesystem.

<details>

``` yaml
steps:
- task: CacheBeta@0
  inputs:
    key: "
      \"$(Agent.OS)\" | \
      \"$(Agent.OSArchitecture)\" | \
      /opt/underlay_ws/checksum.txt"
    path: /bin/bash
```

https://ruffsl.visualstudio.com/navigation2/_build/results?buildId=88

```
##[section]Starting: Save Cache ccache
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key `"ccache" | "1" | "Linux" | "X64" | /opt/underlay_ws/checksum.txt`...
##[error]Could not find a part of the path '/opt/underlay_ws'.
##[section]Finishing: Save Cache ccache
```


---

``` yaml
steps:
- task: CacheBeta@0
  inputs:
    key: "
      \"$(Agent.OS)\" | \
      \"$(Agent.OSArchitecture)\" | \
      /bin/bash"
    path: /opt/underlay_ws/checksum.txt
```

https://ruffsl.visualstudio.com/navigation2/_build/results?buildId=89

```
##[section]Starting: Save Cache ccache
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key `"ccache" | "1" | "Linux" | "X64" | /bin/bash`...
File hashes summarized as `SqmbNYm4b6aVAKoPJUiMPblOwAiEGhl2DXibHMXRNjg=` from BASE64(SHA256(`
SHA256(../../../../../../../bin/bash)=[1113504]DA85596376BF384C14525C50CA010E9AB96952CB811B4ABE188C9EF1B75BFF9A`))
Resolved to `"ccache"|"1"|"Linux"|"X64"|SqmbNYm4b6aVAKoPJUiMPblOwAiEGhl2DXibHMXRNjg=`.
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `"ccache"|"1"|"Linux"|"X64"|SqmbNYm4b6aVAKoPJUiMPblOwAiEGhl2DXibHMXRNjg=`
Information, There is a cache miss.
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session a7f98c7e-baa0-49e3-9363-075b61e7075d
##[error]The path provided is invalid.
##[section]Finishing: Save Cache ccache
```

**Comment by fadnavistanmay** [comment]
@ruffsl - You don't have this issue in Windows, right?

**Comment by ruffsl** [comment]
> @ruffsl - You don't have this issue in Windows, right?

I don't have have a windows system to test this with, so I can't be sure.

Looking back at this again, perhaps it should be made explicit that caching only works for paths within the `/__w/` workspace? With how the agent is implemented now, I don't think its is capable of caching arbitrary paths external of the workspace mount point, yes? Its not using something like `docker cp` behind the scene, but instead just mapping the prefix of the workspace path to and from in and outside the container volume.

**Comment by fadnavistanmay** [comment]
Hi @ruffsl , yes. You are correct in terms of containers, that the paths under _w is visible to agent (reason because of the thread you referenced.) But if you are not using containers, any path should be a happy path for caching. 
I am working on the original issue of displaying the path in terms of container perspective (if there is a container).

**Comment by fadnavistanmay** [comment]
Actually, there is a possibility , *maybe* , that there are paths, other than _w which have been mapped 🤔

**Comment by fadnavistanmay** [comment]
@ruffsl - These 3 paths are mapped - https://github.com/microsoft/azure-pipelines-agent/blob/fe5a24a1d7e93724c4849295a8200804cf2ec301/src/Agent.Worker/Container/ContainerInfo.cs#L40

**Comment by ruffsl** [comment]
Thanks @fadnavistanmay , would there be a place in the docs to document the purpose/difference between `WellKnownDirectory.Tools`,  `WellKnownDirectory.Work` and `WellKnownDirectory.Root`?

**Comment by fadnavistanmay** [comment]
Yeah. We will update the docs - https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops with this information. Plus, we are updating the code to reflect the same. 
cc - @johnterickson 

Thanks.

**Comment by fadnavistanmay** [comment]
Hi @ruffsl , it looks like, we can mount more paths if required. @jtpetty - could you please chime in on the how part. Thanks.

**Comment by fadnavistanmay** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml

**Comment by johnterickson** [comment]
FYI I belive this is rolling out as part of agent 160.*

**Comment by fadnavistanmay** [comment]
This is releases as part of the agent 2.160.0 Thanks
