### ISSUE TITLE
IIS Web App Deploy (Choose Application Pool)

### ISSUE THREAD

**Issue by onooka** [microsoft/azure-pipelines-tasks#10873]
I would like to ask, the Task "IIS Web App Deploy" where Can I choose the Application Pool ???

Because if the Web Site is new, always the program choose the "DefaultAppPool" on Application Pool in IIS Manager (Windows Server), and not the new  releasing with the task "IIS Web App Manage"

Manually I have to select the correct AppPool.

![IIS Web App Deploy (1)](https://user-images.githubusercontent.com/41794338/61004165-f7a12d80-a32a-11e9-8a87-f29781fa71d3.jpg)

![IIS Web App Deploy (2)](https://user-images.githubusercontent.com/41794338/61004170-fb34b480-a32a-11e9-923d-d3a449859052.jpg)

![IIS Web App Deploy (3)](https://user-images.githubusercontent.com/41794338/61004181-01c32c00-a32b-11e9-8aed-91c0daad7d67.jpg)

![IIS Web App Deploy (4)](https://user-images.githubusercontent.com/41794338/61004188-0556b300-a32b-11e9-968f-c075e5724098.jpg)

![IIS Web App Deploy (5)](https://user-images.githubusercontent.com/41794338/61004197-0851a380-a32b-11e9-8858-57ef6346fdcc.jpg)

![IIS Web App Deploy (6)](https://user-images.githubusercontent.com/41794338/61004210-0daeee00-a32b-11e9-8758-cea9b4410e9d.jpg)

![IIS Web App Deploy (7)](https://user-images.githubusercontent.com/41794338/61004216-11427500-a32b-11e9-9172-aee1e9c01aa6.jpg)

![IIS Web App Deploy (8)](https://user-images.githubusercontent.com/41794338/61004220-156e9280-a32b-11e9-98c0-8a21c9c4c471.jpg)

Best regards
Ernesto Ono

**Comment by vincentdass** [comment]
If you want to set the application pool for a site, follow this:
![image](https://user-images.githubusercontent.com/20121508/61102805-17506700-a48d-11e9-9b5e-a69be0b03f10.png)

If you want to set the application pool for an application, follow this:
![image](https://user-images.githubusercontent.com/20121508/61102770-ecfea980-a48c-11e9-882b-18056670c990.png)

**Comment by onooka** [comment]
Thanks, It works Very Well !!!!

Only I have to specify the route "Physical path" the project

![Release (1)](https://user-images.githubusercontent.com/41794338/61158810-b2facb00-a4bf-11e9-9ad3-225804a52cbc.jpg)

![Release (2)](https://user-images.githubusercontent.com/41794338/61158818-b68e5200-a4bf-11e9-896a-575f791a3ff3.jpg)


Thanks and Best regards
Ernesto Ono

**Comment by stevecrisci2** [comment]
Seems you changed the Application Pool in IIS.  I would like to do this inside an Azure Release Pipeline without manually going into IIS.  Our Application Pool names are dynamic and I don't want everything going into the default app pool.

**Comment by kmkumaran** [comment]
Adding @vijayma
