### ISSUE TITLE
Release pipeline (ServerGate) : variables are not resolved in jsonpath function

### ISSUE THREAD

**Issue by mickael-caro-sonarsource** [microsoft/azure-pipelines-tasks#10875]
(Sorry, i redacted a little bit my initial question)

*Type*: Issue

## Environment
Azure DevOps Services - Release Pipeline (Server Gate)

## Issue Description

See investigation on my comment below to see the problem 

Variables in jsonpath are not resolved at runtime (using a custom serverGate on release pipelines)

Is that something thas is intended to work ? If no, is there a way to achieve this ? 

Thanks.

**Comment by mickael-caro-sonarsource** [comment]
Further investigations on my side, 

It appears that variables are not computed in jsonpath calls, whereas it might work on Azure DevOps Server (using framework dll and a tester

For example: 

jsonpath('$.value[0].variables.[\"$(build.buildNumber)\"].value')

$(build.buildNumber) is not resolved

Output stack : 

Evaluating: jsonpath('$..[''$(buildNumber)''].value')[0]
				Evaluating indexer:
				..Evaluating jsonpath:
				....Evaluating String:
				....=> '$..[''$(buildNumber)''].value'
				..=> Array
				..Evaluating Number:
				..=> 0
				=> Null
				=> Null
				Expanded: Null
				Result: ''

Can you help me ? 

Thanks.

**Comment by vithati** [comment]
@mickael-caro-sonarsource , I tried to repo the issue. I don't see any issue in expanding variables in jsonpath. Build varaibles like $(build.buildNumber) populated only if artifact present in release. If artifact not added, can you add artifact to release definition and trigger release.

**Comment by mickael-caro-sonarsource** [comment]
Hi, thank you for answering. I have an artifact link to the release pipeline, which exists, so normally it should be ok. 

What is the correct syntax to enclose the variable itself ? 

I tried with both double-single quotes as well as escaped double quotes, but none of them seem to work. 

Thanks.

**Comment by vithati** [comment]
@mickael-caro-sonarsource , Assume if your gate response is `{"280": "green"}` then `eq(jsonpath('$.$(build.buildNumber)')[0], 'green')` will pass the gate if triggered artifact build number is 280.

Below are some examples how varaibles are replaced if build number is 280. 
For expression, jsonpath('$.$(build.buildNumber)') -> jsonpath('$.280')
For expression, jsonpath('$."$(build.buildNumber)"') -> jsonpath('$."280"')
For expression, jsonpath('$.\"$(build.buildNumber)\"') -> jsonpath('$.\"280\"')

**Comment by mickael-caro-sonarsource** [comment]
Thanks. I tested again with the first one you provided but still not working, and i have no debug output as i had before, so there should be a parsing issue. 

For further context, i put a that json path in a 

"ExecutionOptions": {
            "OutputVariables": {
              "myVariable": "jsonpath('$..$(build.buildNumber).value')[0]"
            }
          }

section. Is that intended to work as well ?

**Comment by vithati** [comment]
@mickael-caro-sonarsource , Sorry I thought you are refering "RequestInputs" section expression. Environment variables like build.buildnumber expansion supported for  "RequestInputs" section expression.  Resolving variables using environment variables in "OutputVariables" expression not supported presently. I am fixing the issue. Fix will be available in 3 to 4 weeks.

**Comment by mickael-caro-sonarsource** [comment]
That's great, thanks !

**Comment by bansalaseem** [comment]
This is fixed in our latest code. So I am closing this issue.
