### ISSUE TITLE
DotNetCoreCLIV2 help text for searchPatternPack is inaccurate

### ISSUE THREAD

**Issue by ryanriv** [microsoft/azure-pipelines-tasks#10888]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines

## Issue Description

The help text for the pack command does not appear to accurately reflect the proper syntax for  a negative pattern in the "Path to csproj or nuspec file(s) to pack" field. The changes in this PR (https://github.com/microsoft/azure-pipelines-tasks/pull/4775/commits/73aa2283a99b4b24a5adfd8a1653d2aad97f46fb#diff-9a2780f8e204bc89ea8307b2f4d38575R241) look like they have the accurate syntax described for a negative pattern. I tested using `**/*.csproj;!**/*.Tests.csproj` rather than `**/*.csproj;-:**/*.Tests.csproj` with the pack command, and it works!

![image](https://user-images.githubusercontent.com/141190/61164376-73d17780-a4c9-11e9-8c8b-853edc009615.png)

**Comment by jmyersmsft** [comment]
@ryanriv Whoops, didn't see you already submitted a PR. I'll get yours merged in ASAP.
