### ISSUE TITLE
VSTestV2 support for Mac OS + Linux

### ISSUE THREAD

**Issue by gundermanc** [microsoft/azure-pipelines-tasks#10881]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Feature**  
VSTestV2 support for Mac OS + Linux

## Issue Description

Currently, running MSTest v2 tests on Mac requires installing the Microsoft.TestPlatform package and then manually invoking vstest.console from within. This seems to work well enough in practice.

Would it be possible to add support for Mac + Linux scenarios to the official VSTestV2 task for convenience?

**Comment by karanjitsingh** [comment]
@gundermanc, currently there is no plan for supporting VSTestV2 for Mac OS and Linux, however you can still use the dotnet task instead of manually using Microsoft.TestPlatform.

**Comment by g-macd** [comment]
Is there somewhere we can request this support, a User Voice or similar?

**Comment by gundermanc** [comment]
> however you can still use the dotnet task instead of manually using Microsoft.TestPlatform

Worth noting that I'm targeting .net472 via Mono on Mac OS for a VS Mac Extension. This doesn't appear to work on the hosted Macs because they aren't able to find the net472 reference assemblies. I'd assume the dotnet command isn't attempting to run with Mono?

**Comment by karanjitsingh** [comment]
> Is there somewhere we can request this support, a User Voice or similar?

@g-macd, I'll mark this as a possible enhancement since multiple people are asking for this.

**Comment by karanjitsingh** [comment]
> > however you can still use the dotnet task instead of manually using Microsoft.TestPlatform
> 
> Worth noting that I'm targeting .net472 via Mono on Mac OS for a VS Mac Extension. This doesn't appear to work on the hosted Macs because they aren't able to find the net472 reference assemblies. I'd assume the dotnet command isn't attempting to run with Mono?

Are you saying dotnet is not compiling for 471 on the mac? If so you should get in touch with dotnet team https://github.com/dotnet/cli
