### ISSUE TITLE
Azure CLI task documentation && instead of ||

### ISSUE THREAD

**Issue by Damag3d** [microsoft/azure-pipelines-tasks#10891]
I have noticed that in Azure Devops Pipeline editor Inline Script field tooltip suggests using II as a way to call multiple commands. || results in conditional exection as described here, so only first command is executed as described here: [Batch scripts](http://steve-jansen.github.io/guides/windows-batch-scripting/part-10-advanced-tricks.html)

**Comment by hiyadav** [comment]
@Damag3d thanks for reporting and making our product better! 
We have raised a PR for the same.
