### ISSUE TITLE
Allow Docker tasks to enable experimental features for manifest support

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-tasks#10899]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Docker

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

To publish multi-architecture Docker manifests, you need to enable the experimental features on the CLI. The current Docker tasks don't allow that to happen.

This is a challenge since you can use the Docker task to handle all the authentication, but then you can't easily modify that configuration (which includes the tokens, etc.). It forces you back into a manual handling of credentials.

Current workaround is to use a shell script like:

```sh
cat $DOCKER_CONFIG/config.json | jq '. + { "experimental": "enabled" }' > $DOCKER_CONFIG/experimental.json
mv -f $DOCKER_CONFIG/experimental.json $DOCKER_CONFIG/config.json
```

**Comment by skotlar** [comment]
How to run this script?  I get an error on permissions

**Comment by gigi81** [comment]
Anyone looking for a workaround, this is I think the best approach. All manifest commands (.ex create and push) will just work
```
variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
````
