### ISSUE TITLE
AzureAppServiceManage: support defined ping path and expected status code on slot swap

### ISSUE THREAD

**Issue by EwanNoble** [microsoft/azure-pipelines-tasks#10903]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureAppServiceManageV0

## Issue Description

App Services seem to have started using the app settings `WEBSITE_SWAP_WARMUP_PING_PATH` and `WEBSITE_SWAP_WARMUP_PING_STATUSES` to customise warmup behaviour, it would be useful for the Slot Swap mechanism within AzureAppServiceManage to use these when specified rather than using defaults.

**Comment by EwanNoble** [comment]
[Documentation on the app settings](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#specify-custom-warm-up)

**Comment by EwanNoble** [comment]
[Current ping mechanism](https://github.com/microsoft/azure-pipelines-tasks/blob/bca3acba94b4d469f664f72f2bf937cc7d2e72a1/Tasks/AzureAppServiceManageV0/operations/AzureAppServiceUtils.ts#L53-L71)

**Comment by ricohomewood** [comment]
Any update on support for this @niadak  @N-Usha ?

**Comment by ricohomewood** [comment]
Hello is there a planned eta on this limitation @chshrikh @nadesu ? thanks

**Comment by nadesu** [comment]
@N-Usha can you take the first stab at this request?

**Comment by N-Usha** [comment]
@ricohomewood / @EwanNoble  - Thanks for reaching out. Can you please help understand the ask here better... We understand that the mentioned App settings can be used to customize the warm-up behavior during slot swap. However these settings can also be manually applied on the App using our App service settings task. Could you please confirm if you have tried that option already and if you are facing any issues?

**Comment by EwanNoble** [comment]
> @ricohomewood / @EwanNoble - Thanks for reaching out. Can you please help understand the ask here better... We understand that the mentioned App settings can be used to customize the warm-up behavior during slot swap. However these settings can also be manually applied on the App using our App service settings task. Could you please confirm if you have tried that option already and if you are facing any issues?

Hi @N-Usha, there is no issue with specifying that app settings, that is fine and we are using those already. The issue is that when these settings are applied the Azure DevOps task is still pinging the root of the application here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureAppServiceManageV0/operations/AzureAppServiceUtils.ts#L53-L71

The ask is that IF these settings are applied to the service they should be used to ping the application rather than just hitting the root.

**Comment by N-Usha** [comment]
Fair ask @EwanNoble . May I ask if you have any workaround in place to accomplish this right now? Could you please help understand how are you blocked given that the task doesn't have this support?

**Comment by ricohomewood** [comment]
@N-Usha I can't speak for @EwanNoble  but in terms of blocking, i believe he mentioned above that the issue is that because the task warms up the root and not the custom ping path, you can end up with unintended cold starts on consumption plans for example.

It's also the case the Azure Platform already supports this, for example, if you had autoswap enabled, the azure backend will honor the setting and use the custom ping path to warm up.

**Comment by ricohomewood** [comment]
@N-Usha any update on this?

**Comment by N-Usha** [comment]
Thanks @ricohomewood... we will add this to our backlog. However unfortunately we cant commit any timelines to delivering this as our team is currently heads down in delivering feature asks which have higher customer impact and need. Hope you can understand. Thanks! @nadesu as FYI

**Comment by maxonweb** [comment]
Any update on this? This is a great feature but unfortunately not being utilised when deploying via DevOps tasks. I would very much love to see this fixed soon.

**Comment by michael-wilson-au** [comment]
@N-Usha  This has a big impact on us.  Automated DevOps deploys keep failing as the slot has not warmed up because it is pinging the root and not using the WEBSITE_SWAP_WARMUP_PING_PATH that we have specified and require it to use.

**Comment by jaysong88** [comment]
we are experiencing the same issue as well, it would be great to see this issue fixed.

**Comment by maxonweb** [comment]
Do not close please. We really want this feature to be working when doing deployments via Devops Pipelines Tasks.

**Comment by michael-wilson-au** [comment]
@N-Usha Is this item prioritized in the backlog? We are still waiting for a fix too.

**Comment by EwanNoble** [comment]
Not stale

**Comment by N-Usha** [comment]
@vijayma - Can you please help assign this to the right contact on your team? Thanks!

**Comment by anatolybolshakov** [comment]
Hi @N-Usha you can use [codeowners](https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS) page to assign it to the relevant team

**Comment by ricohomewood** [comment]
Did this get released?
