### ISSUE TITLE
Incorrect target in File Transform task and incorrect token in .ts file

### ISSUE THREAD

**Issue by NeoXtreem** [microsoft/azure-pipelines-tasks#10908]
**Task Name**: FileTransform

## Environment
Azure DevOps Server 2019.0.1
Private agent OS: Windows Server 2019 with all updates

## Issue Description

I installed the File Transform task to Azure DevOps Server using `tfx build tasks upload --task-path .\Tasks\FileTransformV1` from the repo root.  It was successful.

However, when the task runs, it reports this error:
```
##[error]File not found: 'C:\azagent\A1\_work\_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27\1.153.2\filetransform.**js**'
```

**filetransform.js** doesn't exist, but **filetransform.ts** does.  I found references to the former in **task.json** and **task.loc.json** and change them to the latter.  I then got the error shown below.

### Task logs
[tasklog_4.log](https://github.com/microsoft/azure-pipelines-tasks/files/3397874/tasklog_4.log)

### Error logs
```
C:\azagent\A1\_work\_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27\1.153.3\filetransform.ts:1
(function (exports, require, module, __filename, __dirname) { import tl = require('azure-pipelines-task-lib/task');
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
##[error]Exit code 1 returned from process: file name 'C:\azagent\A1\externals\node\bin\node.exe', arguments '"C:\azagent\A1\_work\_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27\1.153.3\filetransform.ts"'.
```

**Comment by SumiranAgg** [comment]
You first have to build the task before uploading. Use command:
node make.js build test --task FileTransformV1
from root of repo. Once build, delete and upload the task again.

**Comment by NeoXtreem** [comment]
> You first have to build the task before uploading. Use command:
> node make.js build test --task FileTransformV1
> from root of repo. Once build, delete and upload the task again.

@SumiranAgg Thanks for this - perhaps it could go in the [README.md](https://github.com/microsoft/azure-pipelines-tasks/blob/master/README.md) to assist others trying to install tasks. Currently, it only covers writing new tasks, and not how to install and use the existing tasks.

In any case, I did exactly as you suggested, and I'm still getting the same issue.  Building the task does not result in a **filetransform.js** file being generated, and this file is referred to in **task.json** and **task.loc.json**.  See my command log [here](https://github.com/microsoft/azure-pipelines-tasks/files/3400834/command.log.txt).

And the error I get refers (in the path) to the updated version:
```
File not found: 'C:\azagent\A1\_work\_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27\1.156.0\filetransform.js'
```

**Comment by SumiranAgg** [comment]
Awesome! I agree we should document it. Will get to it ASAP. Thanks!

**Comment by N-Usha** [comment]
Thanks for reaching out. We already have a documented guidance on how you could add a build or release custom task: https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops 
You could follow similar steps for adding built -in tasks as well. However for those built in tasks which are not shipped for a specific version of TFS/Azure devOps server, we recommend that you reach out to the product team beforehand to understand if there are dependencies (like agent version, other feature dependencies) that may have to be evaluated to ensure expected behavior of the tasks, post installation. Hope that helps.
