### ISSUE TITLE
Problem when published test result and code coverage at the same pipeline

### ISSUE THREAD

**Issue by tuliorezende** [microsoft/azure-pipelines-tasks#10924]
Hi,

In my pipeline, i configured tasks that publish test results and coverage (to generate a report).

When a publish test result and code coverage results (in different tasks), i can see test reports but i can't see code coverage report (i just can download).

Test Result
![image](https://user-images.githubusercontent.com/6129653/61382966-2025ac00-a884-11e9-9986-85bc36f06bef.png)

Code Coverage Result
![image](https://user-images.githubusercontent.com/6129653/61382997-33387c00-a884-11e9-8337-797055dfde98.png)

Pipeline Organization
![image](https://user-images.githubusercontent.com/6129653/61383483-2f592980-a885-11e9-9d8d-eb8d879cf60d.png)

#Publish Test Result# (Version: 2.*)
##[section]Starting: Publish Test Results
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.153.5
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
[command]d:\a\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.153.5\modules\TestResultsPublisher.exe @d:\a\_temp\deabad90-a894-11e9-953c-6fd5edba64e4.txt
No build level attachments to publish.
Publishing test results to test run '1002716'.
TestResults To Publish 72, Test run id:1002716
Test results publishing 72, remaining: 0. Test run id: 1002716
Published Test Run : https://tfsprodeus2su1.visualstudio.com/A6965d19d-96eb-4e17-8805-aaa54be34b04/InfoBots/_TestManagement/Runs?runId=1002716&_a=runCharts.
##[section]Finishing: Publish Test Results

#Code Coverage Test Result# (Version: 1.*)(I removed my project name for security reasons)
##[section]Starting: Publish Code Coverage Results
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.154.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
[command]"C:\Program Files\dotnet\dotnet.exe" d:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.154.0\netcoreapp2.0\ReportGenerator.dll -reports:d:\a\1\s\TestResults\Coverage\coverage.cobertura.xml -targetdir:d:\a\_temp\cchtml -reporttypes:HtmlInline_AzurePipelines
Loading report 'd:\a\1\s\TestResults\Coverage\coverage.cobertura.xml' 1/1
 Preprocessing report
 Initiating parser for Cobertura
  Current Assembly: <PROJECTNAME>.Extensions
  Current Assembly: <PROJECTNAME>.Models
  Current Assembly: <PROJECTNAME>.Services
  Current Assembly: <PROJECTNAME>.Tests
Coverage report parsing took 0.1 seconds
Initializing report builders for report types: HtmlInline_AzurePipelines
Analyzing 66 classes
 Creating report 1/66 (Assembly: <PROJECTNAME>.Extensions, Class: <PROJECTNAME>.Extensions.DateTimeExtensions)
  Writing report file '<PROJECTNAME>.Extensions_DateTimeExtensions.htm'
 Creating report 2/66 (Assembly: <PROJECTNAME>.Extensions, Class: <PROJECTNAME>.Extensions.DateTimeOffsetExtensions)
  Writing report file '<PROJECTNAME>.Extensions_DateTimeOffsetExtensions.htm'
 Creating report 3/66 (Assembly: <PROJECTNAME>.Extensions, Class: <PROJECTNAME>.Extensions.IntegerExtensions)
  Writing report file '<PROJECTNAME>.Extensions_IntegerExtensions.htm'
 Creating report 4/66 (Assembly: <PROJECTNAME>.Extensions, Class: <PROJECTNAME>.Extensions.StringExtensions)
  Writing report file '<PROJECTNAME>.Extensions_StringExtensions.htm'
 Creating report 5/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Blip.Schedule)
  Writing report file '<PROJECTNAME>.Models_Schedule.htm'
 Creating report 6/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.AffiliateBroadcaster)
  Writing report file '<PROJECTNAME>.Models_AffiliateBroadcaster.htm'
 Creating report 7/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.BaseResponse)
  Writing report file '<PROJECTNAME>.Models_BaseResponse.htm'
 Creating report 8/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.MoviesResponse)
  Writing report file '<PROJECTNAME>.Models_MoviesResponse.htm'
 Creating report 9/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.ProgramResponse)
  Writing report file '<PROJECTNAME>.Models_ProgramResponse.htm'
 Creating report 10/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.SoapOperaResponse)
  Writing report file '<PROJECTNAME>.Models_SoapOperaResponse.htm'
 Creating report 11/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.SoccerResponse)
  Writing report file '<PROJECTNAME>.Models_SoccerResponse.htm'
 Creating report 12/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Builder.Response.SportsResponse)
  Writing report file '<PROJECTNAME>.Models_SportsResponse.htm'
 Creating report 13/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Cache.Attraction)
  Writing report file '<PROJECTNAME>.Models_Attraction.htm'
 Creating report 14/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Cache.DataStore)
  Writing report file '<PROJECTNAME>.Models_DataStore.htm'
 Creating report 15/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.ContentProvider.Content)
  Writing report file '<PROJECTNAME>.Models_Content.htm'
 Creating report 16/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.ContentProvider.ContentProviderResponse)
  Writing report file '<PROJECTNAME>.Models_ContentProviderResponse.htm'
 Creating report 17/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Converters.DireitoCopiaConverter)
  Writing report file '<PROJECTNAME>.Models_DireitoCopiaConverter.htm'
 Creating report 18/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Converters.FluffyParseStringConverter)
  Writing report file '<PROJECTNAME>.Models_FluffyParseStringConverter.htm'
 Creating report 19/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Converters.PeriodicidadeConverter)
  Writing report file '<PROJECTNAME>.Models_PeriodicidadeConverter.htm'
 Creating report 20/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Converters.ProgramCategoryConverter)
  Writing report file '<PROJECTNAME>.Models_ProgramCategoryConverter.htm'
 Creating report 21/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Converters.PurpleParseStringConverter)
  Writing report file '<PROJECTNAME>.Models_PurpleParseStringConverter.htm'
 Creating report 22/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Converters.StatusConverter)
  Writing report file '<PROJECTNAME>.Models_StatusConverter.htm'
 Creating report 23/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Channel)
  Writing report file '<PROJECTNAME>.Models_Channel.htm'
 Creating report 24/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Classificacao)
  Writing report file '<PROJECTNAME>.Models_Classificacao.htm'
 Creating report 25/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Confronto)
  Writing report file '<PROJECTNAME>.Models_Confronto.htm'
 Creating report 26/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.CustomInfo)
  Writing report file '<PROJECTNAME>.Models_CustomInfo.htm'
 Creating report 27/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Entry)
  Writing report file '<PROJECTNAME>.Models_Entry.htm'
 Creating report 28/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.EntryRoot)
  Writing report file '<PROJECTNAME>.Models_EntryRoot.htm'
 Creating report 29/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Genero)
  Writing report file '<PROJECTNAME>.Models_Genero.htm'
 Creating report 30/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Graficos)
  Writing report file '<PROJECTNAME>.Models_Graficos.htm'
 Creating report 31/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Idioma)
  Writing report file '<PROJECTNAME>.Models_Idioma.htm'
 Creating report 32/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Idiomas)
  Writing report file '<PROJECTNAME>.Models_Idiomas.htm'
 Creating report 33/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Media)
  Writing report file '<PROJECTNAME>.Models_Media.htm'
 Creating report 34/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.MultipleProgramme)
  Writing report file '<PROJECTNAME>.Models_MultipleProgramme.htm'
 Creating report 35/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Next)
  Writing report file '<PROJECTNAME>.Models_Next.htm'
 Creating report 36/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Oponente)
  Writing report file '<PROJECTNAME>.Models_Oponente.htm'
 Creating report 37/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Program)
  Writing report file '<PROJECTNAME>.Models_Program.htm'
 Creating report 38/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Programme)
  Writing report file '<PROJECTNAME>.Models_Programme.htm'
 Creating report 39/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.Resumos)
  Writing report file '<PROJECTNAME>.Models_Resumos.htm'
 Creating report 40/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Globo.Response.SingleProgramme)
  Writing report file '<PROJECTNAME>.Models_SingleProgramme.htm'
 Creating report 41/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Google.UserLocationResponse)
  Writing report file '<PROJECTNAME>.Models_UserLocationResponse.htm'
 Creating report 42/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Settings.BlipSettings)
  Writing report file '<PROJECTNAME>.Models_BlipSettings.htm'
 Creating report 43/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Settings.CacheSettings)
  Writing report file '<PROJECTNAME>.Models_CacheSettings.htm'
 Creating report 44/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Settings.EntitiesSettings)
  Writing report file '<PROJECTNAME>.Models_EntitiesSettings.htm'
 Creating report 45/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.Settings.GloboSettings)
  Writing report file '<PROJECTNAME>.Models_GloboSettings.htm'
 Creating report 46/66 (Assembly: <PROJECTNAME>.Models, Class: <PROJECTNAME>.Models.SoundService)
  Writing report file '<PROJECTNAME>.Models_SoundService.htm'
 Creating report 47/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.DataSheet.AffiliatedTable)
  Writing report file '<PROJECTNAME>.Services_AffiliatedTable.htm'
 Creating report 48/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.DataSheet.FileReadDataService)
  Writing report file '<PROJECTNAME>.Services_FileReadDataService.htm'
 Creating report 49/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Exceptions.ExceptionMapper)
  Writing report file '<PROJECTNAME>.Services_ExceptionMapper.htm'
 Creating report 50/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Exceptions.NoContentException)
  Writing report file '<PROJECTNAME>.Services_NoContentException.htm'
 Creating report 51/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Facade.LocationFacade)
  Writing report file '<PROJECTNAME>.Services_LocationFacade.htm'
 Creating report 52/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Facade.MovieFacade)
  Writing report file '<PROJECTNAME>.Services_MovieFacade.htm'
 Creating report 53/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Facade.ProgramFacade)
  Writing report file '<PROJECTNAME>.Services_ProgramFacade.htm'
 Creating report 54/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Facade.SoapOperaFacade)
  Writing report file '<PROJECTNAME>.Services_SoapOperaFacade.htm'
 Creating report 55/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Facade.SoccerFacade)
  Writing report file '<PROJECTNAME>.Services_SoccerFacade.htm'
 Creating report 56/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Facade.SportFacade)
  Writing report file '<PROJECTNAME>.Services_SportFacade.htm'
 Creating report 57/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.BaseService)
  Writing report file '<PROJECTNAME>.Services_BaseService.htm'
 Creating report 58/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.ContentProviderService)
  Writing report file '<PROJECTNAME>.Services_ContentProviderService.htm'
 Creating report 59/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.DateService)
  Writing report file '<PROJECTNAME>.Services_DateService.htm'
 Creating report 60/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.MoviesService)
  Writing report file '<PROJECTNAME>.Services_MoviesService.htm'
 Creating report 61/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.ProgrammeService)
  Writing report file '<PROJECTNAME>.Services_ProgrammeService.htm'
 Creating report 62/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.RefreshMoviesService)
  Writing report file '<PROJECTNAME>.Services_RefreshMoviesService.htm'
 Creating report 63/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.SoapOperaService)
  Writing report file '<PROJECTNAME>.Services_SoapOperaService.htm'
 Creating report 64/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.SoccerService)
  Writing report file '<PROJECTNAME>.Services_SoccerService.htm'
 Creating report 65/66 (Assembly: <PROJECTNAME>.Services, Class: <PROJECTNAME>.Services.Service.SportsService)
  Writing report file '<PROJECTNAME>.Services_SportsService.htm'
 Creating report 66/66 (Assembly: <PROJECTNAME>.Tests, Class: AutoGeneratedProgram)
  Writing report file '<PROJECTNAME>.Tests_AutoGeneratedProgram.htm'
 Creating summary
  Writing report file 'd:\a\_temp\cchtml\index.htm'
Report generation took 0.5 seconds
Generated code coverage html report: d:\a\_temp\cchtml
##[warning]Ignoring coverage report directory with Html content as we are auto-generating Html content
Reading code coverage summary from 'd:\a\1\s\TestResults\Coverage\coverage.cobertura.xml'
##[section]Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 1037 of 1360 covered.
 Branches- 358 of 522 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 69 files
Total file: 69 ---- Processed file: 66 (95%)
File upload succeed.
Published 'd:\a\_temp\cchtml' as artifact 'Code Coverage Report_3423'
##[section]Async Command End: Publish code coverage
##[section]Finishing: Publish Code Coverage Results

#Test# Test Task (Version: 2.*) 

##[section]Starting: Test
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.154.6
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
[command]C:\windows\system32\chcp.com 65001
Active code page: 65001
[command]"C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\<PROJECTNAME>.Tests\<PROJECTNAME>.Tests.csproj --logger trx --results-directory d:\a\1\s --collect "Code Coverage" --settings ../Tests.runsettings --configuration release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=d:\a\1\s\TestResults\Coverage\ /p:Exclude=[xunit*]*
Test run for d:\a\1\s\<PROJECTNAME>.Tests\bin\release\netcoreapp2.2\<PROJECTNAME>.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
M i c r o s o f t   ( R )   C o v e r a g e   C o l l e c t i o n   T o o l   V e r s i o n   1 6 . 0 . 3 0 3 1 9 . 3 0 0 2 
 
 
 C o p y r i g h t   ( c )   M i c r o s o f t   C o r p o r a t i o n .     A l l   r i g h t s   r e s e r v e d . 
 
 
 
 
 Results File: d:\a\1\s\VssAdministrator_fv-az686_2019-07-17_13_14_46.trx

Attachments:
  d:\a\1\s\cc63e72f-d8d6-4397-b227-0da7a444bf97\VssAdministrator_fv-az686_2019-07-17.13_14_37.coverage

Total tests: 72. Passed: 72. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 16.2646 Seconds

Calculating coverage result...
C:\Users\VssAdministrator\.nuget\packages\coverlet.msbuild\2.6.0\build\netstandard2.0\coverlet.msbuild.targets(7,5): warning : [coverlet] Hits file:'C:\Users\VssAdministrator\AppData\Local\Temp\<PROJECTNAME>.Tests_5368986c-1fc4-408c-bf65-48d46edacb10' not found for module: '<PROJECTNAME>.Tests' [d:\a\1\s\<PROJECTNAME>.Tests\<PROJECTNAME>.Tests.csproj]
  Generating report 'd:\a\1\s\TestResults\Coverage\coverage.cobertura.xml'

+----------------------------------------+-------+--------+--------+
| Module                                 | Line  | Branch | Method |
+----------------------------------------+-------+--------+--------+
| <PROJECTNAME>.Extensions | 78.3% | 79.2%  | 73.7%  |
+----------------------------------------+-------+--------+--------+
| <PROJECTNAME>.Models     | 66.6% | 35.8%  | 80.5%  |
+----------------------------------------+-------+--------+--------+
| <PROJECTNAME>.Services   | 80.2% | 76.8%  | 81.9%  |
+----------------------------------------+-------+--------+--------+
| <PROJECTNAME>.Tests      | 0%    | 100%   | 0%     |
+----------------------------------------+-------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 76.2%  | 68.6%  | 80.2%  |
+---------+--------+--------+--------+
| Average | 19.05% | 17.15% | 20.05% |
+---------+--------+--------+--------+

##[section]Finishing: Test

Server - Azure Pipelines

**Comment by vagisha-nidhi** [comment]
@tuliorezende This is by design as we can't have both .coverage and html reporting together. You can download the html file and view the report.
We are trying the make the coverage experience better and will take this up according to our backlog.
Tagging @PBoraMSFT

**Comment by PBoraMSFT** [comment]
@tuliorezende - code coverage reporting has some limitations currently. We are working on addressing those and will provide a first-class web-based coverage reporting experience.

That said, I would like to understand your current pipeline setup a bit better. Can you elaborate on why you have separate steps for publishing test results and coverage? Are you not using the built-in functionality of the task to publish that data? 
![image](https://user-images.githubusercontent.com/23308203/64014105-f5936800-cb3e-11e9-9e43-aa66e73d70af.png)

**Comment by tuliorezende** [comment]
@PBoraMSFT I created pipeline without this option because i didn't see the tests and reports at the same time.

For a while, i will export the coverage to SonarQube application, but i think it will be good to have this report on the build results tabs, how like @vagisha-nidhi said.

**Comment by vagisha-nidhi** [comment]
@tuliorezende Great that you have a workaround for now. You can also give a shot to what @PBoraMSFT mentioned. At the same time we are working on addressing the gaps.
