### ISSUE TITLE
Unable to consume Build Artifact while Using AzureDevOps task

### ISSUE THREAD

**Issue by vishwavijayverma** [microsoft/azure-pipelines-tasks#10926]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: here  
Docker build with artifact
list here (V# not needed):  

## Environment
- Server - Azure Pipelines or TFS on-premises?
          Azure Pipelines
    
    
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name:
      Ubuntu
   

## Issue Description
I am building C+++ project with AzureDevops. I am sucessfully able to build artifact by source code and able to publish. My next requiment is to build docker image with artifactory and push to docker hub. I am unable to achieve this. Dockerimage is pushing to docker hub but comile binary is not there.

## PlineLine code.

variables:
  - name: ArtifactFeed
    value: https://pkgs.dev.azure.com/vijayverma782003/_packaging/vijayverma782003/nuget/v3/index.json
  - name: dockerRegistry
    value: docker.io/dockerid
  - name: buildImage
    value: test

       
trigger:
- master

jobs:
- job: gcctest
  pool:
   vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo apt-get update && sudo apt-get install libboost-all-dev
  - script: g++ -std=c++11 -I/usr/include/boost/asio -I/usr/include/boost -o binary.out main.cpp
          connection.cpp connection_manager.cpp mime_types.cpp reply.cpp request_handler.cpp request_parser.cpp server.cpp -lboost_system -lboost_thread -lpthread

  - powershell:
        $commitId= "$env:BUILD_SOURCEVERSION"

        $definitionName= "$env:BUILD_DEFINITIONNAME"

        $shortId= $commitId.Substring(1, 8)

        $buildName="$definitionName.$shortId"   

        Write-Host $buildName  
   
        Write-Output "$buildName">readme.txt
      

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '?(*.out|*.txt)'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: result

  -  task: DownloadPipelineArtifact@2
     inputs:
       artifact: 'result'
       path: $(Build.SourcesDirectory)/bin

  -  task: Docker@2
     displayName: Login to Docker Hub
     inputs:
       command: login
       containerRegistry: mytest

  - task: Docker@1
    displayName: 'Build using multi-stage'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'mytest'
      arguments: '--build-arg ARTIFACTS_ENDPOINT=$(ArtifactFeed)'

  -  task: Docker@2
     displayName: Push
     inputs:
       containerRegistry: 'mytest'
       repository: 'docker.io/***/azuretest'
       command: 'push'

      
DockerFile.
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y libboost-all-dev
COPY .  /app
EXPOSE 80
CMD /app/binary.out 0.0.0.0 80 .

**Comment by bansalaseem** [comment]
Are you able to have a docker image with the compiled binary outside of pipeline?

**Comment by vithati** [comment]
Closing the issue. Please reopen the issue if problem still exist.
