### ISSUE TITLE
[UseDotNet][DotNetCoreInstaller] Can't install SDK 2.2.205

### ISSUE THREAD

**Issue by amis92** [microsoft/azure-pipelines-tasks#10939]
*Type*: Bug

**Enter Task Name**: UseDotNet@2/DotNetCoreInstaller@1

## Environment
- Server - Azure Pipelines: https://dev.azure.com/warhub/wham/_build?definitionId=1
  - https://dev.azure.com/warhub/wham/_build/results?buildId=13
  - https://dev.azure.com/warhub/wham/_build/results?buildId=14
  - https://dev.azure.com/warhub/wham/_build/results?buildId=15
- Agent - Hosted: Hosted Windows 2019 with VS2019

## Issue Description

Trying to install .NET Core SDK v2.2.205. Fails, because the task inspects only the "newest" version of SDK for a given "release". Current release (v2.2.6) has the additional `sdks` element that contains newest sdks. This list is not inspected by the task code:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UseDotNetV2/versionfetcher.ts#L148-L161

Release Metadata: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.2/releases.json

### Error logs

```
##[section]Starting: DotNetCoreInstaller
==============================================================================
Task         : .NET Core sdk/runtime installer
Description  : Acquire a specific version of the .NET Core SDK from the internet or local cache and add it to the PATH
Version      : 1.0.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
==============================================================================
Tool to install: .NET Core sdk version 2.2.205.
No matching sdk version could be found for specified version: 2.2.205 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 2.2.205 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 2.2
No matching sdk version could be found for specified version: 2.2.205 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Searching for version in channel 2.1
No matching sdk version could be found for specified version: 2.2.205 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Searching for version in channel 2.0
No matching sdk version could be found for specified version: 2.2.205 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
##[error]sdk version matching: 2.2.205 could not be found
##[section]Finishing: DotNetCoreInstaller
```

**Comment by hiyadav** [comment]
The addition of "sdks" property in release object  is new and wasn't expected, hence the task looked in property "sdk". 
We shall work on this, meanwhile can you try to use DotNetCoreInstallerV1 task for downloading the version, or you can use this scripts here (linux/windows) to get unblocked: https://github.com/dotnet/cli/tree/master/scripts/obtain

**Comment by hiyadav** [comment]
This is fixed and will start rolling out, this week. It shall reach all customers by end of next week
