### ISSUE TITLE
VSTest Task Does Not Rerun Failed Tests Properly (GoogleTestAdapter)

### ISSUE THREAD

**Issue by tusharb86** [microsoft/azure-pipelines-tasks#10932]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest@2

## Environment
- Server - Azure Pipelines
    - Account Name: Microsoft
    - Team Project Name: Analog
    - Build Definition Name: SpatialServices-CI-BuddyBuild (20190627.5)

- Agent - Private: Windows Agent Version 2.153.2 (Package ES Lab E)

## Issue Description

We are using the VSTest@2 task to run a suite of tests built with the Google Test framework. When running the task with the `rerunFailedTests `option set to true, the task is unable to find the failing test when attempting to rerun it. It attempts to find the failing test 3 times (`rerunMaxAttempts`) and then gives up. The task is marked as Succeeded even though it shows "Test Run Failed". The rerun shows the following issue `No test matches the given testcase filter` 3 times (full error below and in attached zip file).

Also, it should be noted that we are using [GoogleTestAdapter](https://marketplace.visualstudio.com/items?itemName=ChristianSoltenborn.GoogleTestAdapter) version 0.16.1. The rerun options for the VSTest task are as follows:
`rerunFailedTests: True`
`rerunMaxAttempts: '3'`
`rerunType: 'basedOnTestFailurePercentage'`
`rerunFailedThreshold: '75'`

Please met know if there is any other information I can provide.

Thanks,
Tushar

### Error logs

2019-06-27T23:32:50.6076049Z Total tests: 98. Passed: 93. Failed: 1. Skipped: 4.
2019-06-27T23:32:50.6076908Z ##[error]Test Run Failed.
2019-06-27T23:32:50.6077371Z Test execution time: 3.1360 Minutes
2019-06-27T23:32:50.6312770Z **************** Completed test execution *********************
2019-06-27T23:32:50.6316117Z Test results files: C:\BA\_temp\TR_512310af-a64c-409d-a936-ef95de59f9e3\issblder_PKGES-LABE176_2019-06-27_23_29_46.trx
2019-06-27T23:32:51.4876094Z Created test run: 115859256
2019-06-27T23:32:51.4948978Z Publishing test results: 98
2019-06-27T23:32:51.4949449Z Publishing test results to test run '115859256'.
2019-06-27T23:32:51.4949680Z TestResults To Publish 98, Test run id:115859256
2019-06-27T23:32:51.4950077Z Test results publishing 98, remaining: 0. Test run id: 115859256
2019-06-27T23:32:51.8218387Z Published test results: 98
2019-06-27T23:32:51.8218582Z Publishing Attachments: 1
2019-06-27T23:32:53.1731967Z Failed tests: 1; Total tests: 98;
2019-06-27T23:32:53.3338707Z Total failed tests as return by TCM:1 
2019-06-27T23:32:53.3379822Z Found 1 filtered test case sources.
2019-06-27T23:32:53.3519598Z **************** Rerunning failed tests for Test run 115859256 *********************
2019-06-27T23:32:53.3520146Z Max attempts: 3; Current attempt: 1; Failed test cases threshold: 75; Failed test cases max limit: 0
2019-06-27T23:32:53.3520652Z [command]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\..\..\..\Extensions\TestPlatform\vstest.console.exe "@C:\Users\issblder\AppData\Local\Temp\tmp4E3C.tmp"
2019-06-27T23:32:55.8157798Z Microsoft (R) Test Execution Command Line Tool Version 15.9.1
2019-06-27T23:32:55.8158016Z Copyright (c) Microsoft Corporation.  All rights reserved.
2019-06-27T23:32:55.8171248Z vstest.console.exe "C:\BA\20\s\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe"
2019-06-27T23:32:55.8173584Z /Settings:"C:\BA\_temp\rezqdkiye3w.runsettings"
2019-06-27T23:32:55.8174728Z /Logger:"trx"
2019-06-27T23:32:55.8175207Z /TestAdapterPath:"C:\BA\20\s\SpatialServices\packages\GoogleTestAdapter.0.16.1"
2019-06-27T23:32:55.8175808Z /TestCaseFilter:"FullyQualifiedName=SpatialServicesApiTests.SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic"
2019-06-27T23:32:56.1101929Z Starting test execution, please wait...
2019-06-27T23:32:58.0233518Z Google Test Adapter: Test execution starting...
2019-06-27T23:33:00.1165170Z Found 98 tests in executable C:\BA\20\s\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe
2019-06-27T23:33:00.1526477Z Google Test execution completed, overall duration: 00:00:02.1674060.
2019-06-27T23:33:00.3187265Z No test matches the given testcase filter `FullyQualifiedName=SpatialServicesApiTests.SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic` in C:\BA\20\s\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe
2019-06-27T23:33:00.4482427Z Results File: C:\BA\_temp\TR_512310af-a64c-409d-a936-ef95de59f9e3\issblder_PKGES-LABE176_2019-06-27_23_33_00.trx

[log_120_16707792.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3403991/log_120_16707792.zip)

**Comment by singhsarab** [comment]
@tusharb86 Is the failing test same as the one being used during rerun?

FullyQualifiedName of failing test seems to be SpatialServicesApiTests.SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic

**Comment by tusharb86** [comment]
@singhsarab The FullyQualifiedName is wrong. The beginning of the name ("SpatialServicesApiTests.") is actually the name of the executable... The real name of the test is just "SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic"

**Comment by singhsarab** [comment]
@tusharb86 Interesting! that seems to be the issue here. Will have to debug to see what is the fullqualifiedname reported by the test adapter.

Can you try running locally which trx logger enabled and see what is the fullyqualifiedname in the trx file ?

**Comment by tusharb86** [comment]
@singhsarab What exactly should I be looking for in the TRX file? I don't see a field called "FullyQualifiedName" only "name". Here's an example from the TRX file for this test:
`<UnitTest name="SpatialAnchorRestClient_UseRealService/SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic/0 [true]" storage="g:\sdk1\spatialservices\bin\x64\release\spatialservicesapitests.exe" id="dd1ae5fb-8d91-c86e-a3c4-7e34f9af9a32">`

You'll see that there is no `SpatialServicesApiTests` in the test's name itself, only in the binary executable's name.

(Note that we've changed our tests since I first opened this issue and the test now has a parameter which is why there is a `/0 [true]` here).

**Comment by singhsarab** [comment]
@tusharb86 You can actually list the fullyqualifiednames using the /ListFullyQualifiedTests argument

**Comment by tusharb86** [comment]
Thanks @singhsarab! I did not know about that flag. I tried running with that and I get the following error:
`Target Path should be specified for listing FQDN tests!`

When I run with the "/lt" or "/ListTests" flag, everything works as expected and all test names are printed. Since the "/ListFullyQualifiedTests" flag does not work, does this point to an issue in the GoogleTestAdapter?

Here are the arguments and the full log:
```
vstest.console /logger:trx /platform:x64 /testadapterpath:G:\SDK1\SpatialServices\packages\GoogleTestAdapter.0.16.1 SpatialServicesApiTests.exe /ListFullyQualifiedTests
Microsoft (R) Test Execution Command Line Tool Version 15.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

No settings file provided through env variable GTA_FALLBACK_SETTINGS
Warning: Using default settings.
Google Test Adapter: Test discovery starting...
Found 359 tests in executable G:\SDK1\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe
Test discovery completed, overall duration: 00:00:11.2028399
Target Path should be specified for listing FQDN tests!
```

**Comment by singhsarab** [comment]
You'd have to give another argument for a file path to dump all the names. So your commandline would now look like:
vstest.console /logger:trx /platform:x64 /testadapterpath:G:\SDK1\SpatialServices\packages\GoogleTestAdapter.0.16.1 SpatialServicesApiTests.exe /ListFullyQualifiedTests /ListTestsTargetPath:Testsfile.txt

**Comment by tusharb86** [comment]
Thanks! (As a side note, it would be great to add these command line options to the documentation for [VSTest.Console.exe](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019) since they are not documented there)

I was able to list the fully qualified names for the tests and found that there is no `SpatialServicesApiTests` in the fully qualified test name either:
`SpatialAnchorRestClient_UseRealService/SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic/0`

I was also able to run the individual test with the following command line options:
```
vstest.console /logger:trx /platform:x64 /testadapterpath:G:\SDK1\SpatialServices\packages\GoogleTestAdapter.0.16.1 SpatialServicesApiTests.exe /TestCaseFilter:"FullyQualifiedName=SpatialAnchorRestClient_UseRealService/SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic/0"
Microsoft (R) Test Execution Command Line Tool Version 15.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No settings file provided through env variable GTA_FALLBACK_SETTINGS
Warning: Using default settings.
Google Test Adapter: Test execution starting...
Found 359 tests in executable G:\SDK1\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe
Running 1 tests...
Google Test execution completed, overall duration: 00:00:18.3061090.
Passed   SpatialAnchorRestClient_UseRealService/SpatialServicesRestClientWithServiceTests.CreateNeighborhoodAnchorAndSpatialAnchorBasic/0 [true]
Results File: G:\SDK1\SpatialServices\bin\x64\Release\TestResults\tushab_STUDIOMAGIC_2019-08-06_09_29_05.trx

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 19.9784 Seconds
```
Please let me know if you need any other information on my end. It would be great if you are able to setup a repro as well.

Thanks,
Tushar

**Comment by ShreyasRmsft** [comment]
@tusharb86 this is an issue with XUnit as well.

Basically XUnit as well as Google Test Adapter report the FQDN wrongly in the trx. When we use the same name to run the test again using the test case filter it does not work.

One option is to try and get to change the way these adapters behave but that's not an easy task.

We do however have a workaround where we use the translation layer in the vstestplatform to pass around testcaseref objects rather than perform invocations via command line. This ensures the tests get discovered since we forward the full objects to the adapter and not one piece of information.

Take a look at the github issue below for the workaround. We do hope to make the translation layer the default mode of execution in the vstest task in the future.

https://github.com/microsoft/azure-pipelines-tasks/issues/10709

**Comment by ShreyasRmsft** [comment]
Closing this due to no response, Please re-open if problem persists after attempting the workaround.

**Comment by tusharb86** [comment]
@ShreyasRmsft Sorry for the delay. The workaround does not work, unfortunately :-( I tried this a long while back and saw that batching wasn't working at all. The logs for those builds have expired, so I've kicked off new builds and will update when I have them.

Google Test Adapter is an open source project that we can contribute to directly. Also, we should file an issue for that project if the issue is in the adapter to track this.

**Comment by ShreyasRmsft** [comment]
@tusharb86 could you also provide me with a minimal sample repro on github? I can fiddle around and get more insights on what exactly is causing the mismatch. Thanks.

**Comment by tusharb86** [comment]
Thanks for reopening the issue @ShreyasRmsft! Unfortunately, I don't think I'll have time to come up with a minimal repro on GitHub for at least a week or so. Below are logs where I attempted to use the workaround suggested. Both attempts at batching tests produced similar results.

```
distributionBatchType: 'basedOnTestCases'
batchingBasedOnAgentsOption: 'customBatchSize'
customBatchSizeValue: '100'
```
And
```
distributionBatchType: 'basedOnAssembly'
```

Results:
```
IsValidServiceResponse: Received None command..Service Workflow is not active
Creating run for selected test assemblies with following parameters
SourceFilter: ThisWontBeUsed TestCaseFilter: 
Run title: Google *Tests.exe (with service) (non-gating) - Windows Release-x64
Build location: C:\BA\2584\s\SpatialServices\bin\x64\Release
Build Id: 17601396
Test run with Id 117123290 associated
Received the command : Start
TestExecutionHost.ProcessCommand. Start Command handled
Slice with id = 240681, of type = 'Discovery' received.
Count of test sources found: 2
=================================================================
Discovering tests from sources
Using new test platform for test execution
##[warning]DiscoveryMessage : Could not find extensions: C:\BA\2584\s\SpatialServices\packages\GoogleTestAdapter.0.16.1
##[warning]DiscoveryMessage : No test is available in C:\BA\2584\s\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe C:\BA\2584\s\SpatialServices\bin\x64\Release\SpatialServicesCoreTests.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Number of testcases discovered : 0
Discovered tests 0 from sources
=================================================================
##[error]The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: No test is available in C:\BA\2584\s\SpatialServices\bin\x64\Release\SpatialServicesApiTests.exe C:\BA\2584\s\SpatialServices\bin\x64\Release\SpatialServicesCoreTests.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

I should note that these results are very different from the results I got about a month or two back. It seems that the test adapter can't be found in these cases. Previously, the test distribution wasn't working at all - it showed many retry attempts at distributing the tests and then eventually failed out. Unfortunately, those builds have aged out and I don't have the logs any longer :(

**Comment by ShreyasRmsft** [comment]
@tusharb86 can you please provide the full zip file that you get when you click on "Download all logs"? 

Also please set system.debug = true

**Comment by ShreyasRmsft** [comment]
Please do re-open with the request information.

**Comment by anttix** [comment]
Similar issue has been reported for NUnit, the reporter of https://github.com/microsoft/azure-pipelines-tasks/issues/16187 has provided a minimal example of the issue.
