### ISSUE TITLE
how to add sequence provisioning in the task AzureVmssDeploymentTask

### ISSUE THREAD

**Issue by vinothinidharmaraj** [microsoft/azure-pipelines-tasks#10933]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature/Bug

**Enter Task Name**: AzureVmssDeploymentTask

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

## Issue Description

How do we add the extension sequence for the vm scale set?
In my scenario we have antimalware extension which supposed to run the before the custom script extension, when i trigger the deployment through the pipeline it works i add the antimalware extension and then will add the custom script extension task. 

Im facing issue when i reimage the vmss from the portal, it doesnt guarantee that the custom script runs after the antimalware.

Is there any provision to send the extension sequencing through the pipeline?

**Comment by hiyadav** [comment]
Extension sequencing for VM Scale set can be achieved via multiple method. Read [HERE](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-extension-sequencing)

You can try the Template one while creating the VM scale set for the first time. This might retain the sequence even when you try to reimage.

I would also advice you to ask the Azure VM/Compute team for how sequencing can be achieved. I am thus closing this issue, as it seem to be much of a knowledge ask from Azure VM/Compute team.
