### ISSUE TITLE
Improve directory enumeration logic for pipeline caching globbing

### ISSUE THREAD

**Issue by johnterickson** [microsoft/azure-pipelines-tasks#10937]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Pipeline Caching

## Environment
- Server - Azure Pipelines

There's lots of room for improvement in how we enumerate directories in FingerprintCreator:
https://github.com/microsoft/azure-pipelines-agent/blob/05bf184dce011212accb63388418f1d4ab410916/src/Agent.Plugins/PipelineCache/FingerprintCreator.cs#L95-L128

**Comment by herenhuang** [comment]
Update here: Currently now tracking this in the Artifacts backlog. No ETA as of right now but we can provide another update when there is one!

**Comment by EricMCornelius** [comment]
@herenhuang  Is there the possibility of controlling the cache content itself via globs in the "path"?

My understanding from the docs right now is that the fingerprinting accepts file patterns, but the actual path needs to be a directory.

This is an issue for NPM global installs, e.g., where all binaries are dumped into a single directory.

**Comment by nategreen** [comment]
+1 for globbing in the path. Would like to use it to cache Rush build info from each project's .rush/temp directory in my monrepo.
