### ISSUE TITLE
Xcpretty arguments and test run names in Xcode Task

### ISSUE THREAD

**Issue by Jon889** [microsoft/azure-pipelines-tasks#10948]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Xcode  

I've opened a PR the adds two optional inputs to the Xcode task.

* Setting the name of the test run when publishing the test results.
* Pass additional parameters to xcpretty
The reasons behind needing these changes:

* Currently the test run name is JUnit_TestResults_XXX this isn't helpful if you have multiple tests in the same build. At Tesco we have a nightly build that runs all the tests on iOS 12 and 11 each. Atm it's hard to distinguish which one is which. So it would be good to provide a custom name to disambiguate.
* it would be good to use a customer formatter (specifically https://github.com/Jon889/xcpretty-azure-pipelines-formatter) so that the output is a little friendlier for Azure Pipelines.

The contributing docs mention opening an issue as well.

**Comment by Jon889** [comment]
@madhurig Is it possible to get this looked at?

**Comment by barrcodes** [comment]
@madhurig @leantk How did #10947 go stale? These would be very appreciated features. xcpretty is nearly worthless if we can't supply additional arguments.

It seems more and more these days that to get the functionality I need out of Azure Pipelines, I need to write everything as command line scripts.
