### ISSUE TITLE
AzurePowerShellV4 task temp files not properly cleaned up

### ISSUE THREAD

**Issue by rreichel3** [microsoft/azure-pipelines-tasks#10941]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShellV4  

## Environment
- Server - Azure Pipelines or TFS on-premises? **Both**
    

- Agent - Hosted or Private: **Both**
    

## Issue Description
The AzurePowerShellV4 task has a small security bug where the script that is executed is not property cleaned up.  Though the risk is rather limited, it does have the potential for information leakage as the script will likely contain sensitive information. 

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by rajatagrawal-dev** [comment]
@rreichel3 AzurePowerShell task (any version) does not clean up the temp files. The temp files are created in the agent temp directory. The agent then itself cleans up the temp directory after job is completed.

Please check if you are experiencing the same behavior with the normal PowerShell task as well. Also, please let us know the agent version that you are on.

**Comment by rajatagrawal-dev** [comment]
Please reopen if the issue persists.

**Comment by rreichel3** [comment]
Can you please reopen this? It is an existing issue that has been verified and reported by @vtbassmatt

**Comment by rajatagrawal-dev** [comment]
Reopened. Apologies for closing it before. Somehow I missed the referenced PR.

**Comment by rajatagrawal-dev** [comment]
@rreichel3 I am unable to reproduce this. Also, it is not the job of the task to clear the agent temp directory. Agent clears it's temp directory itself.

**Comment by vtbassmatt** [comment]
The agent [will certainly try](https://github.com/microsoft/azure-pipelines-agent/blob/abb551d3d65573ffb2bc8e713d90be97bdf30048/src/Agent.Worker/JobRunner.cs#L351), but it would be a good practice to also delete known secrets. What if the agent crashes before it gets to the cleanup step?

**Comment by RoshanKumarMicrosoft** [comment]
@rajatagrawal-dev  can you please look into @vtbassmatt  suggestions.

**Comment by SumiranAgg** [comment]
@vtbassmatt The agent runs as a service and restarts even if it crashes. Any following job run will clean up temp directory.
This is by design so that not every task has the responsibility of cleaning up its temp files and its handled by the agent at job completion;
