### ISSUE TITLE
Provide DTAExecutionHost and TestResultsPublisher documentation & sources

### ISSUE THREAD

**Issue by JiriKovar** [microsoft/azure-pipelines-tasks#10950]
Please provide documentation, or ideally open source these tools. You are heavily using it for example for running tests and it seems that quite a lot of useful logic is in it, which we would like to be able to use in our custom tasks. 

Example: We need to publish test results where some tests were successful on rerun, meaning we have 2 *.trx files. The results are the same as from the VsTestV2 task (we even tried to use the exact results from the aforementioned task), but publishing them so that they correctly report reruns is beyond our capabilities as the standard approach through PublishTestResultsV2 cannot achieve that and neither TestPublisher from Node SDK can as it is merely a wrapper over 'results.publish' command, which seems quite limited. Any other effort is soiled, because we keep hitting the walls of these 2 magical black boxes. Honestly I'm 99% sure that the whole rerunning & correct test results reporting in VsTestV2 is handled by the DTAExecutionHost. So I want to know if and how the correct rerun test results reporting from the *.trx files could be achieved through TestResultsPublisher (which, looking at the DLLs, I'm afraid it won't), or whether DTAExecutionHost can be used to achieve this (which I hope it might).

This is not the first time I'm almost at the point of disassembling these tools just to learn something about them, which is why I created such a general request even though the example I used is quite specific and will be addressed separately. 

I have the support ticket open for the aforementioned example and am not sure if this is the correct channel to ask for this, but it is closely related to either this, or the SDK directly, so I decided to start here. Please feel free to direct me to better channel to place this request if there is any.

Thanks!

**Comment by Additi** [comment]
Hi,
It will be of great help if you can request for this feature @ https://developercommunity.visualstudio.com/content/idea/post.html?space=21 to help us prioritize it.

**Comment by Tigerstyle88** [comment]
I will test , any objections?
