### ISSUE TITLE
##[error]Failed to download or parse release-index.json with error: {}

### ISSUE THREAD

**Issue by danielcirket** [microsoft/azure-pipelines-tasks#10969]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  UseDotNet@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines

- Agent - Hosted or Private: 
Hosted Windows 2019 with VS2019

## Issue Description

Receive the following error downloading the .NETCore SDK: `##[error]Failed to download or parse release-index.json with error: {}`

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

 `##[error]Failed to download or parse release-index.json with error: {}`

## WORKAROUND (yaml configuration):

Before: 

```yaml
- task: UseDotNet@2
  displayName: 'Install .NETCore SDK'
  inputs:
    version: '2.2.301'
```

After:

```yaml
- task: UseDotNet@2
  displayName: 'Install .NETCore SDK'
  inputs:
    packageType: 'sdk'
    version: '2.2.301'
```

**Comment by danielcirket** [comment]
Potentially related / similar to: #10968

**Comment by hiyadav** [comment]
This seem to have been caused by some error introduced in the releases-index.json of dotnet/core repo.
You should be unblocked now. Do reopen if this occurs again.

**Comment by brysk** [comment]
I have just faced this issue in Azure Pipelines:

```
Starting: Use .NET Core sdk 2.2.301
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.0.25
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 2.2.301.
##[error]Failed to download or parse release-index.json with error: {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"151.101.184.133","port":443}
Finishing: Use .NET Core sdk 2.2.301
```

**Comment by mailtojkay** [comment]
I am getting this error in out Private agent, Hosted agents it is working fine.
##[section]Starting: Use .Net Core sdk 3.1.x
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.0.25
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 3.1.x.
##[error]Failed to download or parse release-index.json with error: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"raw.githubusercontent.com","host":"raw.githubusercontent.com","port":443}
##[section]Finishing: Use .Net Core sdk 3.1.x

**Comment by NArnott** [comment]
We're seeing it too.

**Comment by patkremer** [comment]
We are seeing it as well

**Comment by deckerbd** [comment]
It's most likely due to ongoing issues at GitHub right now, see https://www.githubstatus.com/

**Comment by PaulGauthier** [comment]
I'm pretty sure it was GitHub as deckerbd mentioned. It started when the github problem started and resolved when they resolved it.

**Comment by lukaszstarzak** [comment]
I just experienced this issue. I believe its still there. Please reopen

Task         : Use .NET Core
Version      : 2.165.2
Tool to install: .NET Core sdk version 3.x.
##[error]Failed to download or parse release-index.json with error: {}

**Comment by BjarniThor** [comment]
Just started experiencing this, azure devops server updated to current, using classic tasks but yaml looked like this.
```yaml
steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    installationPath: '$(Agent.ToolsDirectory)/dotnet'
```
Solved it by adding 'sdk' to installation path. Guess the cache must've gotten corrupted or similar since it's been working from cache for some weeks(4-5) now.

**Comment by medright** [comment]
We are seeing this too today, starting last night.

**Comment by amirxnz** [comment]
This is happening for us now too

**Comment by AmorimRob** [comment]
happening again

**Comment by JasminCebo** [comment]
This is now happening again

**Comment by darshanio** [comment]
happening again

**Comment by Afikoman** [comment]
Happening also to us for the first time.

**Comment by jaboc83** [comment]
Same here. Happening as of this morning first time for us.

**Comment by jozsefkovacs** [comment]
Happening on Self Hosted Agent.

**Comment by vincentDAO** [comment]
Same here. Happen on Azure Self Hosted Agent

**Comment by jkdmyrs** [comment]
Just wanted to note that the original post says the workaround is to add packageType: 'sdk' to the task's inputs... This exists already in my YAML configuration but the task is still failing.

**Comment by frankkilcommins** [comment]
This task fails based on Github dependencies. There's again an active Github availability issue. See https://www.githubstatus.com/

**Comment by bishal-pdMSFT** [comment]
+1 to @frankkilcommins above. This task uses a github file for detecting SDK download path. That file is unreachable due to GitHub's unavailability.

**Comment by amirxnz** [comment]
@bishal-pdMSFT Does it make sense to have this dependency on github? Or at least have some sort of fallback?

**Comment by javissimo** [comment]
@amirxnz agree. Pipelines aren't working at the moment.

**Comment by loning** [comment]
failed at the moment, https://dev.azure.com/AElfProject/AElf/_build/results?buildId=10133&view=logs&jobId=9784995b-f699-5f68-c70b-00631acf7dd7&j=55b94f1c-9d32-5114-bc90-83768ebbe0df&t=de9a9c50-b2e4-57b8-ae9e-eb45eb7476d0

**Comment by rochapablo** [comment]
+1

**Comment by PaulGauthier** [comment]
GitHub is having issues again. This happened yesterday as well and is disrupting development. @bishal-pdMSFT The workaround described in this ticket doesn't work. Should we start a different issue? All our .Net builds are failing and I know of no viable workaround.

**Comment by Alexbits** [comment]
Same...

**Comment by joneal** [comment]
We are seeing this issue now.

**Comment by doppelmoep** [comment]
+1

**Comment by slabarque** [comment]
+1

**Comment by tannerwatson** [comment]
+1

**Comment by ankit57** [comment]
Site says that fix has been deployed but I am still getting same error

**Comment by adamHarries87** [comment]
+1

**Comment by AlexCertsure** [comment]
+1

**Comment by AlexanderMartensHub** [comment]
+1

**Comment by rvhelden** [comment]
+1

**Comment by SergiyDivnych** [comment]
+1

**Comment by rohank-proarch** [comment]
+1

**Comment by GeromeRen** [comment]
+1

**Comment by mbrumpton** [comment]
+1

**Comment by staa99** [comment]
Same here. +1

**Comment by mimunoz** [comment]
+1

**Comment by ejszi** [comment]
+1

**Comment by MatthewDavidCampbell** [comment]
+!

**Comment by CoreyB26** [comment]
We are having this issue suddenly today as well...

**Comment by arek-avanade** [comment]
+1

**Comment by dnperfors** [comment]
Instead of '+1'-ing, I suggest a change in the UseDotnet task.

Why not caching the release list and use the old list when the new one can't be parsed or reached? A lot of the time the tools are cached anyways, so this might solve this issue for a lot of us.

**Comment by hichamveo** [comment]
+1. steel ave the same issue.

**Comment by boragursel** [comment]
+1

**Comment by AlexBeyd** [comment]
> Instead of '+1'-ing, I suggest a change in the UseDotnet task.
> 
> Why not caching the release list and use the old list when the new one can't be parsed or reached? A lot of the time the tools are cached anyways, so this might solve this issue for a lot of us.
> 
> cc @hiyadav, can this issue be opened again until it is really fixed?

Can you please elaborate how exactly to do this ?

**Comment by gmarbury** [comment]
I notice this is closed. The workaround does NOT work. Is there another open issue? By the way, I commented out UseDotNet@2 and it appears my pipeline succeeded.

**Comment by aldodfm** [comment]
+1

**Comment by celloist** [comment]
+1

**Comment by hichamveo** [comment]
Now it's working for me:
Before : 
![image](https://user-images.githubusercontent.com/5187841/80110319-d5f1f980-857e-11ea-808d-8c4c6c82540f.png)

now:

![image](https://user-images.githubusercontent.com/5187841/80110369-e4401580-857e-11ea-8ff2-9e8cf1751e75.png)

**Comment by bishal-pdMSFT** [comment]
Created a PR to use non-github url https://github.com/microsoft/azure-pipelines-tasks/pull/12741

**Comment by bishal-pdMSFT** [comment]
btw it looks like the issue is resolved

**Comment by Afikoman** [comment]
working again.

**Comment by dnperfors** [comment]
> > Instead of '+1'-ing, I suggest a change in the UseDotnet task.
> > Why not caching the release list and use the old list when the new one can't be parsed or reached? A lot of the time the tools are cached anyways, so this might solve this issue for a lot of us.
> > cc @hiyadav, can this issue be opened again until it is really fixed?
> 
> Can you please elaborate how exactly to do this ?

First of all I don't know the details of the task....

In my opinion the following steps should be taken when running this task:

1. Get the release list from github
1. Parse the release list
1. If successful, save the release list on the agent (tools directory, or the task directory, but this is where my knowledge of tasks lack)
1. if parse was not successful, get the previously saved list and parse it.
1. perform the rest of the tasks....

**Comment by AlexBeyd** [comment]
works now, the glitch is gone

**Comment by AlexBeyd** [comment]
seems to be working now. the glitch is gone

**Comment by rochapablo** [comment]
seems to be working now

**Comment by chenghuang-mdsol** [comment]
it recovered for me

**Comment by fleckert** [comment]
works for me

**Comment by obohaciak** [comment]
In addition to what @dnperfors suggested with caching the `releases-index.json` file, perhaps mirroring it in a few other locations could also help? I believe the file is currently fetched from https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json - when the task was not working, this URL would return HTTP 500.

(I just noticed that @bishal-pdMSFT opened PR #12741 to avoid GitHub issues)

**Comment by MkFelipe** [comment]
+1

**Comment by MkFelipe** [comment]
it recovered for me

**Comment by illegalnumbers** [comment]
I have seen this same issue.

**Comment by qin-guan** [comment]
just got the same issue today as well

**Comment by HasaMatej** [comment]
Seen today as well

**Comment by oecdGeneric** [comment]
Hello, 
I have a similar error, I'm working on an automated tests pipeline on Azure to run on a Windows Self Hosted agent, my build pipelines are working, in this new pipeline, I have: 
```
  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with NuGet'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'
      installationPath: '$(Agent.ToolsDirectory)/dotnet'

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'src/myProject.Test.Core/*.csproj'
      testRunTitle: 'myProject'
      arguments: '--collect "Code coverage"'
      publishTestResults: true

```

I have this error:  Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}
As you can see in the logs: 
```
##[debug]agent.proxyurl=http://proxy.myCie.com:443
##[debug]agent.proxyusername=undefined
##[debug]agent.proxypassword=undefined
##[debug]agent.proxybypasslist=["myCie.com,localhost,127.0.0.1","myCie.com","localhost","127.0.0.1"]
##[debug]agent.proxybypasslist=["myCie.com,localhost,127.0.0.1","myCie.com","localhost","127.0.0.1"]
##[debug]AZURE_HTTP_USER_AGENT=VSTS_xxx_build_173_0
Tool to install: .NET Core sdk version 3.1.101.
##[debug]task result: Failed
##[error]Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}
##[debug]Processed: ##vso[task.issue type=error;]Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}
##[section]Finishing: UseDotNet
```

I added the task "UseDotNet@2" because without it, I was having this: 
```
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build 
##[debug]Processed: ##vso[task.issue type=warning;].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) Use global.json using an older sdk version(<=3) to build 
##[debug]task result: Failed

```

I don't understand it as the build pipeline works,  it seems it can't reach the releases-index.json file but again, as DotNet Core 5 is installed on the server, I'm confused.

Would you be able to help understand this and propose a solution or workaround ?  Should I add a global.json file to the tests project ?

Thanks a lot for any help, 
Claude

**Comment by ClaudeVernier** [comment]
Hello, 
I have a similar error, I'm working on an automated tests pipeline on Azure to run on a Windows Self Hosted agent, my build pipelines are working, in this new pipeline, I have: 
```
  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with NuGet'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'
      installationPath: '$(Agent.ToolsDirectory)/dotnet'

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'src/myProject.Test.Core/*.csproj'
      testRunTitle: 'myProject'
      arguments: '--collect "Code coverage"'
      publishTestResults: true

```

I have this error:  **Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}**
As you can see in the logs: 
```
##[debug]agent.proxyurl=http://proxy.myCie.com:443
##[debug]agent.proxyusername=undefined
##[debug]agent.proxypassword=undefined
##[debug]agent.proxybypasslist=["myCie.com,localhost,127.0.0.1","myCie.com","localhost","127.0.0.1"]
##[debug]agent.proxybypasslist=["myCie.com,localhost,127.0.0.1","myCie.com","localhost","127.0.0.1"]
##[debug]AZURE_HTTP_USER_AGENT=VSTS_xxx_build_173_0
Tool to install: .NET Core sdk version 3.1.101.
##[debug]task result: Failed
##[error]Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}
##[debug]Processed: ##vso[task.issue type=error;]Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}
##[section]Finishing: UseDotNet
```

I added the task "UseDotNet@2" because without it, I was having this: 
```
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build 
##[debug]Processed: ##vso[task.issue type=warning;].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) Use global.json using an older sdk version(<=3) to build 
##[debug]task result: Failed

```

I don't understand it as the build pipeline works,  it seems it can't reach the releases-index.json file but again, as DotNet Core 5 is installed on the server, I'm confused.

Would you be able to help understand this and propose a solution or workaround ?  Should I add a global.json file to the tests project ?

Thanks a lot for any help, 
Claude

**Comment by marcelljung** [comment]
Hi,

I am getting error with that the agent cannot access the file on GitHub even though the link works in a browser.
I am following the guides from azure docs and it still throws this error:
##vso[task.issue type=error;]Failed to download the file. URL:

**Comment by Wouter-Vandenputte** [comment]
August 2021 and the issue still occurs. Thinking out of the box here, could it be that we (the world) are just going with to much servers to the same location? Because this error occurs sporadically with us (about 6 out of 10 times)

**Comment by wrakocy** [comment]
It's baaaaack. As of moments ago:

2021-12-29T17:55:36.2705467Z ##[section]Starting: Use .Net 6 SDK
2021-12-29T17:55:36.2806809Z ==============================================================================
2021-12-29T17:55:36.2807088Z Task         : Use .NET Core
2021-12-29T17:55:36.2807493Z Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
2021-12-29T17:55:36.2807908Z Version      : 2.195.1
2021-12-29T17:55:36.2808083Z Author       : Microsoft Corporation
2021-12-29T17:55:36.2808283Z Help         : https://aka.ms/AA4xgy0
2021-12-29T17:55:36.2808523Z ==============================================================================
2021-12-29T17:55:36.7154572Z Tool to install: .NET Core sdk version 6.0.x.
2021-12-29T17:55:37.1900929Z ##[error]Failed to download or parse releases-index.json with error: {}
2021-12-29T17:55:37.2042971Z ##[section]Finishing: Use .Net 6 SDK

**Comment by andyste1** [comment]
We've been encountering this problem over the last month or so. Azure DevOps 2019, "use dotnet" build task version "2.* (preview)", which I'm using to download SDK 6.0.301. 
It first happened over the course of a few days early in September, disappeared, then started happening again this week. It's intermittent, failing maybe 1 in 3 builds. The task fails with this error message:

##[error]Failed to download or parse release-index.json with error: {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"185.199.109.133","port":443}

I've opened a support case with MS but not getting very far, and I think it's reaching the stage where they want to pass the buck as being a network issue at our end. 

Any thoughts?

**Comment by DanielShikhar** [comment]
Hi all,
Did anybody find the fix for this issue?

I am facing the exact same issue and cant find a work around,
If any please suggest.

Thanks

**Comment by Phyzioio** [comment]
Anyone facing the same issue this week the original issue 10969 of this thread? 

##[error]Failed to download or parse releases-index.json with error: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}

This was working last Friday.

We are on Azure DevOps server 2022 update 1.1, "Use .NET Core sdk 6.0" build task version 2, which I'm using to download SDK 6.0.400.

**Comment by jfreal** [comment]
I'm getting the same error today.

**Comment by quicoli** [comment]
Happening today!!!!!!!!!!!!!!! 😫 NET 8

**Comment by AdamDiament** [comment]
Happening for me with .net 8 today

**Comment by AdamDiament** [comment]
If I simplify my UseDotNet@2 task down to 
```
    - task: UseDotNet@2
      displayName: 'Use .net8 for API' 
      inputs:
        version: '8.0.x'
```
From this
```
    - task: UseDotNet@2
      displayName: 'Use .net8 for API' 
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        instalationPath: $(Agent.ToolsDirectory)/dotnet
```
It fixes it, I'm not sure why

**Comment by smg-bg** [comment]
Happened to us, just like that out of the blue. Why?!?

**Comment by thatstatsguy** [comment]
@bishal-pdMSFT 

My team are observing the same issue intermittently.  Seems like you made a PR last time that resolved this issue. Perhaps it could be the same issue but for Net 8?

Attaching replication steps below

Error message
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/47271795/d8fe647a-cd43-432f-838f-ee5f16c13a49)

Task in pipeline

```
          
variables:
  - name: dotnet_version
    value: "8.x"

//other information in pipeline redacted
  - task: UseDotNet@2
    displayName: "Install correct .Net version"
    inputs:
       version: $(dotnet_version)
```

**Comment by dlatikaynen** [comment]
happened twice this week, my nightly build was affected again today

**Comment by jackheywood** [comment]
Happened to me this morning, re-running the pipeline without any changes fixed it

**Comment by kipusoep** [comment]
Happened to me twice this morning. It seems like the hosted agents have a lot of transient connection issues the last couple of months.

**Comment by candoumbe** [comment]
Happenned to me this morning ...
Is this still a transient error ?

**Comment by JimGeersinga** [comment]
Happening to our projects aswell

**Comment by sergei-lobanov** [comment]
Why this issue closed and no feedback at all? if from time to time this issue actual.
On our project its just started a few days ago, latest fail 3 hours ago.

**Comment by candoumbe** [comment]
like @sergei-lobanov said, I wish we had at least a way to circumvent the issue.
When it happens on a CI/CD pipeline, it rings all kind of bells and finding out it's due to a transient error is kind of deceptive

**Comment by dpenciucdhv** [comment]
This happens to me as well almost everytime for about 2 days now... :|

**Comment by leecow** [comment]
Hey folks, we recently added a "supported-os.json" field to releases-index.json. We didn't expect an additive change to be breaking, apologies for the trouble! 

https://github.com/dotnet/core/commit/559fd95b632ca20875552b29a67ff6b8ee4a3644

**Comment by kipusoep** [comment]
@leecow I don't think it's a parsing issue, but a connectivity issue instead.

**Comment by vienleidl** [comment]
> @leecow I don't think it's a parsing issue, but a connectivity issue instead.

That is caused by the connectivity of Azure DevOps. The 2nd time I tried and it worked again.
<img width="348" alt="image" src="https://github.com/user-attachments/assets/5918ed27-bf13-47ac-8ae2-df70c3c1717a">
