### ISSUE TITLE
CustomTasks: Execution handler for powershell 6 (Core)

### ISSUE THREAD

**Issue by Allendorf231** [microsoft/azure-pipelines-tasks#10977]
I want to migrate my PowerShell tasks to run under Linux, but there didnt find a way to tell the task.json to use PowershellCore, there is only Node…

How can i run customized Tasks under Linux using PowerShell? How does the PowershellV2 tasks handle this?

**Comment by damccorm** [comment]
Hi, we've decided not to add a powershellcore handler. With that said, you can demand that users provide powershellcore and exec it from a node task - see https://github.com/microsoft/azure-pipelines-task-lib/issues/537 for context and an example of how to do this (at the end)

**Comment by damccorm** [comment]
Closing since we're not going to take this, please follow up with any questions in https://github.com/microsoft/azure-pipelines-task-lib/issues/537
