### ISSUE TITLE
Azure SQL Database deployment AAD integrated

### ISSUE THREAD

**Issue by jdms754** [microsoft/azure-pipelines-tasks#10981]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure  SQL Database deployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account name: jdms754@gmail.com
Project name: Aad
Pipeline name: testPipe
Release name: Release-9

- Agent - Hosted or Private: Hosted

    - If using Hosted agent, provide agent queue name: Azure Pipelines

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I am using Azure SQL Database deployment task with AAD integrated authentication. I receive the following in the log: "Failed to reach SQL server jdms754.database.windows.net. One or more errors occurred." This is a test server and database I provisioned to troubleshoot the issue. The task completes successfully if I use sql authentication. The app registration used by Azure DevOps has a contained user in the target database and the user is a member of db_owner role. Is AAD integration supported for hosted agents?

### Task logs

[tasklog_7.log](https://github.com/microsoft/azure-pipelines-tasks/files/3423712/tasklog_7.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[error]One or more errors occurred.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

**Comment by Ajay-MS** [comment]
@jdms754 

AAD integrated authentication tries to login to SQL server with same user with which Agent is running. Since hosted agent user won't have permission on the SQL server because of security reasons.Hence it will fail. In other words, AAD integrated authencation is not supported for Hosted agent. 

Thought you can use `Active Directory - Password` authentication.

**Comment by jdms754** [comment]
@Ajay-MS Ok, thanks. I think this answers the question.

**Comment by ArieHein** [comment]
Create a Service principle in your AAD that is has ownership on the resource group where you azure sql is located. You them make sure he is also the sql server admin, and then use his name and credential in azure devops for creating a service endpoint, which you use in the task itself.

you can create a local user in the sql db that is dbo, and use that user and password as secret variables in your pipeline and add them in the db task or before that to set the connection string while injecting the user and password
