### ISSUE TITLE
Test run succeeds even though requested assembly not found

### ISSUE THREAD

**Issue by lygasch** [microsoft/azure-pipelines-tasks#10980]
Hello,
we are using Visual Studio Test v2 task for check-in tests. We specify assemblies in the "Test Files" property. One of these projects had misconfigured output path and was not found, but the test run ignored it / succeeded. From logs I see
Source filter: [contains the assembly name]
. . .
vstest.console.exe [cmd args does not contain the missing assembly]
It is important for the run to fail if a specified assembly is not found. It should not be silently ignored (or at least provide an option to have this behavior).

Seems related to these:
https://github.com/microsoft/azure-pipelines-tasks/issues/8114 https://github.com/microsoft/azure-pipelines-tasks/issues/4185

**Comment by ShreyasRmsft** [comment]
@lygasch we are working on addressing. please track this issue https://github.com/microsoft/azure-pipelines-tasks/issues/11328 for updates.

Closing is it will be addressed as part of the linked issue.
