### ISSUE TITLE
Custom pre-deployment conditions

### ISSUE THREAD

**Issue by drauch** [microsoft/azure-pipelines-tasks#10988]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

## Issue Description

Is it possible to create custom pre-deployment conditions somehow? As an extension probably? Is there sample code for the existing pre-deployment conditions?

Background: we want to ensure that the artifact is properly signed before releasing it to a production stage in our Azure DevOps release pipeline.

Best regards,
D.R.

**Comment by bansalaseem** [comment]
Does this help?

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops

**Comment by drauch** [comment]
I don't really see how the already existing gates could be used to check whether the input artifact of the release pipeline is signed by a trusted CA or not...is there a way to extend the existing gates somehow?

**Comment by vithati** [comment]
@drauch, you can write custom gate for your scenario.  https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/gates.md helps writing customer gate.  Refer some of the gate tasks for reference https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks

**Comment by drauch** [comment]
@vithati: In my scenario I'd perform some checks on the input artifact - is this a good idea? It looks like gates are retried again and again until they're fulfilled. If my check of the artifact fails, the gate is never going to open.

Is there a better way to implement such a behavior in Azure DevOps?

**Comment by vithati** [comment]
@drauch, If you keep 'Delay before evaluation' 0 it retries only for two times, you can try with gates and gates runs before deployment starts. We have feature [pipeline decorator](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops) in yaml pipeline this can be used for yaml pipelines, but this feature not available in release pipeline. It is in release pipeline backlog, it may take time to light up in releases.

**Comment by vithati** [comment]
@drauch , We have enabled decorator in release pipelines. If you want to be part of early adopter, let us    know you azuredevops account name. Decorator reference [doc](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops).

**Comment by drauch** [comment]
Hi! Is it possible to access the artifacts of a release pipeline in the decorator? We want to execute an action for each input artifact.

If this is possible, yes, please enable it for our test organization https://dev.azure.com/SignPathTestProjectOrganization/

Best regards,
D.R.

**Comment by madhuv-msft** [comment]
@drauch release decorators is available for your account _SignPathTestProjectOrganization_, please let us know if you have any feedback on this.

Document to author a task for decorators:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#author-a-pipeline-decorator

document for conditional injection:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#conditional-injection

variables available part of the conditional injection:
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch

more details on the decorator expression context:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops

to answer your last query on artifacts, yes they do available for these decorators while they are running [once conditional expression is true].
