### ISSUE TITLE
Issue with masking user ids

### ISSUE THREAD

**Issue by Damag3d** [microsoft/azure-pipelines-tasks#10983]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure PowerShell 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

## Issue Description
when you trying to output and process files based on TenantId, ClientId, AccountId - this is generally needed for SPA apps, output is heavily masked. You loose ability to debug the pipeline. I understand this is for security reasons, but why? You configure the pipeline, you authorize pipeline by supplying subscription authentication. Certificate files are unprotected lying on disk. Any NPM sh... can send this files anywhere. Why you need this stupid masking, instead of investing time into providing better ways to reuse important info?

## Troubleshooting
```
2019-07-23T21:04:23.5179477Z ***
2019-07-23T21:04:23.5179691Z 49dcaefb-cc3e-42fa-b96e-a7db716733c
2019-07-23T21:04:23.5179797Z ***
2019-07-23T21:04:23.5179861Z ffeef18d-5124-4560-ac6f-2e4c3c921c3
2019-07-23T21:04:23.5179952Z ***
2019-07-23T21:04:23.5180008Z 49dcaefb-cc3e-42fa-b96e-a7db716733c

```
Here is the code of inline script

```
$l=$aad.TenantDomain
Write-Host  $aad.TenantDomain
Write-Host $l.substring(0,$l.length-1)
$l = $ctx.Account.Id
Write-Host $ctx.Account.Id
Write-Host $l.substring(0,$l.length-1)
```

SARCASM: I understand usage of secure strings but why use it? Let's do this sh... guys? I lost about 12hrs debugging this nonsense, until I finally understood how it is implemented. And moreover, I can take Access Token and display it freely in the output. Really?

**Comment by bryanmacfarlane** [comment]
note https://opensource.microsoft.com/codeofconduct/

**Comment by bryanmacfarlane** [comment]
Setting type properly helps triage and get it traction sooner

**Comment by Damag3d** [comment]
> note https://opensource.microsoft.com/codeofconduct/

Got it. Sorry.

**Comment by bryanmacfarlane** [comment]
NP ;)

**Comment by bryanmacfarlane** [comment]
Cleaned up some comments.  @kmkumaran for action on this.

**Comment by RoshanKumarMicrosoft** [comment]
@rajatagrawal-dev  Can you please have a look into it.

**Comment by SumiranAgg** [comment]
If you have marked a variable as secret or are using service connection credentials in script, they are masked in logs. Is not done, anyone who has view access to your release/ build definition can use these credentials.
If you still have concerns please open an issue [here](https://github.com/microsoft/azure-pipelines-agent/issues), which is responsible for masking.
