### ISSUE TITLE
Download GitHub Release with private repo fails

### ISSUE THREAD

**Issue by kyrio-vstsadmin** [microsoft/azure-pipelines-tasks#10994]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Download GitHub Release

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Kyrio, PKI Portals, SunSpec-CI, 20190724.15

- Agent - Hosted
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description
GitHub Service Connection built out.   Download GitHub Release shows the connection and able to find the private repo.   Tried 'Write' and 'Admin' privileges to the private repo.
When the build process is ran, the steps says "Total Files: 0, Processed: 0, Skipped: 0, Failed: 0, Download time: 1.011 secs, Download size: 0Bytes" with no errors.
Same issue when changing 'Default Version' from 'Latest' to 'Specific Version'

[Include task name(s), screenshots and any other relevant details]

### Task logs
##[debug]Evaluating condition for step: 'Download GitHub Release'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Download GitHub Release
==============================================================================
Task         : Download GitHub Release
Description  : Downloads a GitHub Release from a repository
Version      : 0.154.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-github-release
==============================================================================
##[debug]agent.TempDirectory=/home/vsts/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_CONNECTION
##[debug]loading INPUT_USERREPOSITORY
##[debug]loading INPUT_DEFAULTVERSIONTYPE
##[debug]loading INPUT_VERSION
##[debug]loading INPUT_ITEMPATTERN
##[debug]loading INPUT_DOWNLOADPATH
##[debug]loading ENDPOINT_AUTH_58318dbf-956e-4b38-85f9-dc7a66383ff1
##[debug]loading ENDPOINT_AUTH_SCHEME_58318dbf-956e-4b38-85f9-dc7a66383ff1
##[debug]loading ENDPOINT_AUTH_PARAMETER_58318dbf-956e-4b38-85f9-dc7a66383ff1_CONFIGURATIONID
##[debug]loading ENDPOINT_AUTH_PARAMETER_58318dbf-956e-4b38-85f9-dc7a66383ff1_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loaded 13
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.154.0/node_modules/artifact-engine/lib.json
##[debug]adding resource file: /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.154.0/node_modules/artifact-engine/lib.json
##[debug]system.culture=en-US
##[debug]check path : /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.154.0/task.json
##[debug]adding resource file: /home/vsts/work/_tasks/DownloadGitHubRelease_263abc27-4582-4174-8789-af599697778e/0.154.0/task.json
##[debug]system.culture=en-US
##[debug]connection=58318dbf-956e-4b38-85f9-dc7a66383ff1
##[debug]userRepository=cablelabs/sunspec-testcerts
##[debug]defaultVersionType=specificVersion
##[debug]itemPattern=**
##[debug]downloadPath=/home/vsts/work/1/s/api/cert-gen
##[debug]version=18821898
##[debug]58318dbf-956e-4b38-85f9-dc7a66383ff1 auth param AccessToken = ***
##[debug]VSTS_HTTP_RETRY=undefined
Downloading assets of release 'v1.0' from: https://api.github.com/repos/cablelabs/sunspec-testcerts/releases/18821898/assets
##[debug]release.artifact.download.parallellimit=undefined
##[debug]System.Debug=true
##[debug]Nothing to process currently, respawing worker 2 after 1 sec.
##[debug]Nothing to process currently, respawing worker 3 after 1 sec.
##[debug]Nothing to process currently, respawing worker 4 after 1 sec.
##[debug]testing directory '/home/vsts/work/1/s/api/cert-gen'
##[debug]testing directory '/home/vsts/work/1/s/api'
##[debug]mkdir '/home/vsts/work/1/s/api/cert-gen'
##[debug]Enqueued 0 for processing.
##[debug]Nothing to process currently, respawing worker 1 after 1 sec.
##[debug]Nothing more to process, exiting worker 1.
##[debug]Nothing more to process, exiting worker 2.
##[debug]Nothing more to process, exiting worker 3.
##[debug]Nothing more to process, exiting worker 4.
Total Files: 0, Processed: 0, Skipped: 0, Failed: 0, Download time: 1.011 secs, Download size: 0Bytes
##[debug]SYSTEM.HOSTTYPE=build
##[debug]BUILD.DEFINITIONNAME=Sunspec-CI
##[debug]BUILD.BUILDID=5099
##[debug]SYSTEM.TEAMFOUNDATIONSERVERURI=https://kyrio.visualstudio.com/
##[debug]SYSTEM.TEAMPROJECT=PKI Portals
##[debug]BUILD.BUILDID=5099
##[debug]TASK.DISPLAYNAME=Download GitHub Release
##[debug]SYSTEM.JOBID=275f1d19-1bd8-5591-b06b-07d489ea915a
##[debug]AGENT.VERSION=2.154.3
##[debug]AGENT.OS=Linux
##[debug]AGENT.NAME=Hosted Agent
##[debug]Processed: ##vso[telemetry.publish area=artifact-engine;feature=performance]{"hostType":"build","definitionName":"[NonEmail:Sunspec-CI]","processId":"5099","processUrl":"https://kyrio.visualstudio.com/PKI Portals/_build?buildId=5099","taskDisplayName":"Download GitHub Release","jobid":"275f1d19-1bd8-5591-b06b-07d489ea915a","agentVersion":"2.154.3","agentOS":"Linux","agentName":"Hosted Agent","version":"0.1.26","location":"https://api.github.com/repos/cablelabs/sunspec-testcerts/releases/18821898/assets","total":1,"files":0,"processed":0,"skipped":0,"failed":0,"downloadTimeInSeconds":1.011,"downloadSizeInBytes":0,"fileSizeInBytes":0}
##[debug]Summary:
##[debug]--------------------------------------------------------------------------------------
##[debug]| File | Start Time                | Finish Time               | Duration   | STATE     |
##[debug]--------------------------------------------------------------------------------------
Successfully downloaded release assets to '/home/vsts/work/1/s/api/cert-gen'
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]
##[debug]Total Items: 1, Processed: 1, Processing: 0, Queued: 0, Skipped: 0, Failed: 0, Time elapsed: 5.006secs
##[section]Finishing: Download GitHub Release

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by chrisfowles** [comment]
Also hitting this issue.

**Comment by gykuma** [comment]
@kyrio-vstsadmin Can you please check if your [release assets](https://github.com/cablelabs/sunspec-testcerts/releases) has items other that `Source Code (zip)` and `Source Code (tar.gz)`? 

It seems the call to fetch assets didn't receive any asset (https://api.github.com/repos/cablelabs/sunspec-testcerts/releases/18821898/assets)

**Comment by gykuma** [comment]
@kyrio-vstsadmin I'm closing this issue for now, since there is no response. Please feel free to re-open in case you are still facing this issue.
