### ISSUE TITLE
AzureCLI: ##[error]Script failed with error: ERROR: command authoring error for 'account set': 'subscription' conflicting option string: --subscription

### ISSUE THREAD

**Issue by issacnitin** [microsoft/azure-pipelines-tasks#10995]
##[debug]Processed: ##vso[task.issue type=error;]Script failed with error: ERROR: command authoring error for 'account set': 'subscription' conflicting option string: --subscription%0A

![MicrosoftTeams-image](https://user-images.githubusercontent.com/4218887/61853412-7a082080-aed9-11e9-8e94-98296c632c34.png)

Debug logs
[7.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3430166/7.txt)

**Comment by hiyadav** [comment]
This is unexpected. Can you verify if the service connection is valid. To do so, you can go to 
Project Settings -> Service Connections -> Choose the Service Connection being used in the task -> Verify connection

Let me know if it is successfully validated.

Also can you let us know, what type of agent pool you were using, private or some hosted agent pool ?

**Comment by github2alfred** [comment]
i tried both private and hosted agent, same errors.

**Comment by hiyadav** [comment]
Okay, and is the service connection verified to be working.

**Comment by hiyadav** [comment]
This seems to be a problem with the specific version of az cli tool: 2.0.46, this is quite an old version released on nov 6, 18. The hosted ubuntu agent pools should have a much latest version 2.0.68. 
Can you try using a updated tool version, and see if it unblocks you ? Like 2.0.68 

FYI I could see some fixes regarding --subscription parameter in 2.0.48 version: https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#core-14

**Comment by hiyadav** [comment]
The probvlem was because 2.0.46 version (faulty) was being explicitly installed and thus casuing the issue. This was resolved by explicitly installing 2.0.49 or above version.

**Comment by github2alfred** [comment]
hi hiyadav,

SO solution is to edit this line :
pip install azure-cli==2.0.46

which is inside environment_setup/install_requirements.sh
