### ISSUE TITLE
[UseDotNetV2] Failed while getting version 2.2.108 from channel 2.2 with error: {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"52.241.88.84","port":443}

### ISSUE THREAD

**Issue by hiyadav** [microsoft/azure-pipelines-tasks#10999]
Tasks fails with connection timeout while fetching information/package from internet. There shall be retries for certain http response codes.

**Comment by bishal-pdMSFT** [comment]
We can take this up if there are reasonable number of such failures
