### ISSUE TITLE
PublishCodeCoverage Degraded Performance

### ISSUE THREAD

**Issue by scbedd** [microsoft/azure-pipelines-tasks#11008]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Question on degraded behavior, possibly bug

**Enter Task Name**: `PublishCodeCoverageResults@1`

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1

## Environment
Hosted Build Agents. MacOS, Windows, Linux
Account name: **dev**
Organization name: **azure-sdk**
Team project name: **public**
Build Definition Name [Link to Build Definition](https://dev.azure.com/azure-sdk/public/_build?definitionId=46&_a=summary)
Specific Build Number: [Example Failing Build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=74256)

Hosted Agent. Drawing from the public pool provided by the DevOps team for the `azure-sdk` org.

## Issue Description

We are seeing degraded behavior in the `publish code coverage to devops task`

We've started seeing pretty much all PRs (starting 7/25 10-am-ish) timing out due to unexpected increase in the `Publish Code Coverage to DevOps` task.

![image](https://user-images.githubusercontent.com/45376673/61913015-ac714800-aef0-11e9-85d5-825d7d8fd6d5.png)

However, on `internal` builds, we see this task running for about *1/3rd* the time this morning.

![image](https://user-images.githubusercontent.com/45376673/61913060-cdd23400-aef0-11e9-9c83-1e14f5f622af.png)

[Link to Example Internal Build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=73946)

We went from ~10 minutes to publish to >30 minutes this afternoon. I understand that there could be some noisy neighbor at play here. If there is something we need to do long term to avoid this situation, I'd be appreciative.

### Task logs

The below task logs were generated by [this build.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=74449) (system.debug=true)

[logs_74449.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3433836/logs_74449.zip)

This example build actually shows the behavior I'm talking about! MacOS finishes in 7 minutes. The rest run for an additional 20 or so before timing out.

### Error logs

There are no specific error logs here, we simply run till the default timeout of 60 minutes now.

**Comment by karanjitsingh** [comment]
@scbedd, upload seems to be super inefficient when there are thousands of small files being uploaded.

**Comment by scbedd** [comment]
Thanks for the update @karanjitsingh 

Also note that it's a single `.coverage` file being `coverage xml`-ed prior to being passed to the `PublishCodeCoverage` task. If I could minimize complexity by forcing it closer to a single upload I would.

**Comment by ShreyasRmsft** [comment]
This issue is of lower priority compared to other actions items we have and will be closing this unless there are further upvotes.
