### ISSUE TITLE
UseNodeV1 does not satisfy npm demand like NodeToolV0 did

### ISSUE THREAD

**Issue by hacst** [microsoft/azure-pipelines-tasks#11012]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseNode  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks
## Environment
- Azure DevOps Server 2019.1 RC2
- Agent - Hosted or Private: Private Ubuntu 16.04 based

## Issue Description

As UseNodeV1 has the same task ID as NodeToolV0 I assume it is meant to replace it. Trying to use it in combination with the npm task results in https://github.com/Microsoft/azure-pipelines-tasks/issues/9795 to re-occur. UseNodeV1 does not satisfy the npm demand.

**Comment by damccorm** [comment]
This has been fixed by https://github.com/microsoft/azure-pipelines-tasks/pull/11030
