### ISSUE TITLE
Allow "lint" command for HelmDeploy Task

### ISSUE THREAD

**Issue by RomanKreisel** [microsoft/azure-pipelines-tasks#11023]
*Type*: **Bug or Feature**
Enter Task Name: **HelmDeploy@0**  

## Environment
- Server - **Azure Pipelines**
- Agent - **Hosted Ubuntu**
## Issue Description
Currently "lint" is not an accepted command for the HelmDeploy Task, but it should be. It helps to lint the helm charts during build process already.

![image](https://user-images.githubusercontent.com/749910/62058405-adbcb080-b221-11e9-96a6-0b2497bcc684.png)

**Comment by vithati** [comment]
@RomanKreisel , Helm task 'command' input is editable and it supports arguments. You can type command and arguments, this file https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helmcommands/uinotimplementedcommands.ts takecares of execution. I see Pipeline UI is warning but you can ignore that. I will raise bug on pipeline UI.
