### ISSUE TITLE
Add logging command to upload pipeline artifacts.

### ISSUE THREAD

**Issue by guillaume86** [microsoft/azure-pipelines-tasks#11028]
*Type*: Feature

**Enter Task Name**: Logging commands

## Issue Description

The artifact.upload command is very slow compared to using pipeline artifacts steps. I guess it uses "legacy" build artifacts as opposed to pipeline artifacts and the optimisations that comes with them.

I would like to be able to use pipeline artifacts from logging commands for convenience (trigger artifacts upload directly from a MSBuild target in my case).

**Comment by mmitche** [comment]
This would be fantastic to get in. Otherwise we will have a hard time moving to pipeline artifacts

**Comment by guillaume86** [comment]
Any news on this issue?

**Comment by herenhuang** [comment]
Hey all, thanks for your patience here. 

This seems like a very valid ask in effectively using pipeline artifacts/easing the transition. We're now tracking this request on our backlog. I will provide an update here after we're able to review and prioritize this work.
