### ISSUE TITLE
AzureFileCopy@3 - multi-OS support?

### ISSUE THREAD

**Issue by jochenvw** [microsoft/azure-pipelines-tasks#11027]
I'm building a YML pipeline for publishing a static website to a storage account. I've been running on Ubuntu machines in the pool:
```
pool:
  vmImage: 'ubuntu-latest'
```
And have a couple of `BASH` tasks with some Linux specific ways to set variables and things. I've added the `AzureFileCopy@3` task and hit the following error message:
```
##[error]The current operating system is not capable of running this task. 
That typically means the task was written for Windows only. 
For example, written for Windows Desktop PowerShell.
```
I'll think of a workaround, but in the mean time: are you guys planning on making this task cross-OS compatible?

**Comment by rajatagrawal-dev** [comment]
@jochenvw This is in backlog.

@RoopeshNair / @kmkumaran  Is this planned any time soon?

**Comment by RoopeshNair** [comment]
No plans to take this up anytime soon. We are currently working on issue that are impacting broader set of customers. You can suggest this as a feature request on [Developer community](https://developercommunity.visualstudio.com/content/idea/post.html?space=21), it will help us to prioritize this appropriately. 
One option is to use az cli / bash step

We encourage contributions!
