### ISSUE TITLE
Documentation is needed on how to debug tests

### ISSUE THREAD

**Issue by Amoenus** [microsoft/azure-pipelines-tasks#11029]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Tests

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
   - Building and testing locally

#### User Story
As a contributor making changes to a task
I want to be able to run the tests locally with the debugger attached
So that I can more easily fix mistakes, don't rely on automated CI in the PR and improve the quality of my PR's prior I submit them for the public review.
#### Required action
Documentation is needed to explain how to run tests for a task with the debugger attached
### Task logs

N/A

## Troubleshooting
N/A

### Error logs

N/A

**Comment by damccorm** [comment]
I'd probably recommend using a 3rd party tool like [inspector](https://glebbahmutov.com/blog/debugging-mocha-using-inspector/) - this isn't part of our workflow though, so I don't think we're going to provide docs here, I'd rather rely on the 3rd party docs for doing this more generally
