### ISSUE TITLE
Multistage docker build and tag

### ISSUE THREAD

**Issue by anoff** [microsoft/azure-pipelines-tasks#11031]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question, Feature

**Enter Task Name**: Docker@2

## Environment
- Server - Azure Pipelines

- Agent - Hosted ubuntu-latest

## Issue Description

I would like to create a multistage yaml pipeline where I build an image in first stage and publish it with `tag=$(Build.BuildNumber)`.
After some testing with it I would like to publish the exact same image as `:latest`.
Is there a way to achieve this with the Docker task?

related (outdated) issue seems to be the request for `retag` https://github.com/microsoft/azure-pipelines-tasks/issues/6480

**Comment by santoror** [comment]
If the image is hosted in acr you can use the azure cli task and launch `az acr import`

**Comment by Anumita** [comment]
Something like this should solve your issue
steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: acrReg
    repository: anshenotest
    addPipelineData: false

- task: Docker@2
  displayName: tag
  inputs:
    containerRegistry: acrReg
    repository: anshenotest
    command: tag
    arguments: '<regName>.azurecr.io/anshenotest:$(Build.BuildId)  <regName>.azurecr.io/anshenotest:latest'

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: acrReg
    repository: anshenotest
    command: push
    tags: latest

**Comment by Anumita** [comment]
in the first step on building and pushing the first image, the image is stored on the agent, so on tagging and pushing in the second and third step you don't have to pull again

**Comment by anoff** [comment]
I want to run it in a multi-stage environment so there is no guarantee that the same agent will be used.
Would the 2nd and 3rd task still work if they were executed on a different node i.e. will there be an implicit pull if required?
