### ISSUE TITLE
AzureCLI task does not cancel when build is canceled

### ISSUE THREAD

**Issue by mhamilton723** [microsoft/azure-pipelines-tasks#11035]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://msazure.visualstudio.com/Cognitive%20Services/_build/results?buildId=23889987

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/6456637/62182127-80f0c200-b323-11e9-9e9c-57a24257aad5.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by hiyadav** [comment]
Hey @mhamilton723 
Thanks for reporting the issue you are facing.

Are you facing this issue consistently ? If yes, will you be able to share a repro.
Is the task otherwise completing successfully if the pipeline is not cancelled ? 

From first look it looks like the task/agent process hung and thus the task kept running.

**Comment by mhamilton723** [comment]
Hey @hiyadav 
i followed up on teams for ease of chat but heres a link to a build
https://msazure.visualstudio.com/Cognitive%20Services/_build/results?buildId=23900042
this is reliably reproable

**Comment by anuragc617** [comment]
Hi, @mhamilton723 this is not an error in Azure CLI task. This looks like an error in Azure CLI  'E2E' condition which comes out to be true even if you cancel your build and as a result, it isn't canceled. If you want to cancel this task on build cancel add "succeeded" condition.

**Comment by anuragc617** [comment]
Hi @mhamilton723, is the above solution working for you?

**Comment by anuragc617** [comment]
Hi @mhamilton723, I am closing this issue. If you any other questions feel free to ask.
