### ISSUE TITLE
[Feature Request] - KubernetesV1 - Don't force commands to use '-o' json/yaml

### ISSUE THREAD

**Issue by HenrikStanley** [microsoft/azure-pipelines-tasks#11051]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Kubernetes  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/866830aecf96e48e2610c8876ec1d27b0767644f/Tasks/KubernetesV1/src/kubernetescommand.ts

##  @Environment
Azure Pipelines
- Agent - Hosted

## Issue Description

The Kubernetes task will per default add `-o json` to the command unless `outputFormat` input variable is used to change it to yaml.

My issue is that, at times, you do not wish to see the output so verbose at all. For example, applying configmaps with JSON in them used for dashboards by Grafana, these becomes massive and pollutes the output. 

It would be nice to have the option to choose not to use any `-o` at all so all that remains is just the "applied" message.

As a side note, with this kind of usage, since the output steam becomes so big, we get warnings:

### Error logs

[warning]Output variable not set as kubectl command output exceeded the maximum supported length. Output length: 290661, Maximum supported length: 32766

**Comment by einko** [comment]
Any update for this?

**Comment by ds-ms** [comment]
If you set `outputFormat: ''` like this.. it won't add `-o` to the commands!
