### ISSUE TITLE
Azure IoT Edge Task's deployment step does not wait for the deployment to be applied

### ISSUE THREAD

**Issue by hiteshmadan** [microsoft/azure-pipelines-tasks#11053]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure IoT Edge V2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureIoTEdgeV2

## Environment
- Server - Azure Pipelines

- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://msazure.visualstudio.com/One/_build/results?buildId=23906046&_a=summary

- Agent - Hosted or Private: Hosted    
- If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description
I'm using the Azure IOT Edge V2 Task to deploy a module to an edge device, and then run tests against this deployed module.
Often times, the deploy task succeeds and the tests start before the deployment has fully completed.

The deploy task should have a way to wait for the device to actually process the deployment - i.e. wait for deploymentStatus for this deployment job to change to applied.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[iotedgetask.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3457893/iotedgetask.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by blackchoey** [comment]
This is not a bug. @hiteshmadan IoT Edge service handled deployment as 2 steps: first accept the deployment request, second apply the deployment to IoT Edge services asynchronously. What Azure IoT Edge do is the first step.
For the second step, it's hard to define the success criteria for it because different users could have their own definition of success according to their scenarios. You can have a smoke test script to check whether your IoT Edge solution started successfully in given time after deployment, which is very common in devops pipelines.

**Comment by hiteshmadan** [comment]
I'm not sure I fully understand the notion of it being hard to define/detect when a deployment succeeded.

The IoT Edge CLI has first class support for monitoring a deployment (link at the end). All thats needed imho is to expose that CLI command's parameters in the AzP Task for iot edge deployment?

cc the IoT Edge CLI PM in case he can clear any doubts you have: @gregman-msft

documentation on how to monitor an active deployment:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-monitor-cli#monitor-a-deployment

**Comment by blackchoey** [comment]
The Azure CLI command you mentioned just returns a series of metrics, you need to determine the status of deployment by yourself based on the returned metrics. So just invoking the command could not help resolve your problem.
