### ISSUE TITLE
Download "latest" build artifacts TFS 2018

### ISSUE THREAD

**Issue by jungopro** [microsoft/azure-pipelines-tasks#11056]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Download Build Artifacts  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version:  Version 16.131.28106.2
 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
```console
Agent.OS | Windows_NT
Agent.OSVersion | 6.3.9600
Agent.Version | 2.136.1
```

## Issue Description

Can't choose "latest" artifact to download. In **Azure DevOps, for Example:**
<img width="1176" alt="Screen Shot 2019-08-02 at 9 52 29" src="https://user-images.githubusercontent.com/22839439/62350409-53ff0380-b50b-11e9-8ea6-c6bb80768ed0.png">

But the same doesn't exist in TFS 2018. Even if I enter the word **latest** manually it doesn't work

<img width="881" alt="Screen Shot 2019-08-02 at 9 54 03" src="https://user-images.githubusercontent.com/22839439/62350485-84df3880-b50b-11e9-816d-a35e3fbcd4d2.png">

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Build with id NaN not found for build definition id 444

<img width="782" alt="Screen Shot 2019-08-02 at 9 55 34" src="https://user-images.githubusercontent.com/22839439/62350553-b5bf6d80-b50b-11e9-8099-3bfad7ea162e.png">

**Comment by jungopro** [comment]
Just to calrify - I want to run CI, then CD for that CI.
In the end of the first CD stage (_dev_) I want to trigger a CI for the next stage (_test_) and then download the artifacts from the build I triggerd in the next CD stage (_test_) and so on. 

**_Dev CI_** -> Trigger CD job for multiple environments -> **_Dev stage_** in CD uses **_Dev CI_** artifacts -> **_Dev stage_** in CD triggers **_TEST CI_** -> **_Test stage_** in CD starts after **_Dev Stage_** in CD and uses **_Test CI_** artifacts -> then prod cycle and so on...

**Comment by gykuma** [comment]
Hi @jungopro , The version of this task (0.131.2) shipped with TFS 2018 does not have the feature to select `Build Version To Download`. This feature was added in TFS 2019 with task version 0.142.2.

**Comment by Gitrathirad** [comment]
@gykuma - Would installing the task version 0.142.2. on TFS 2018 after removing task (0.131.2) break anything in future
