### ISSUE TITLE
HTTP 503 throttling on cache restore

### ISSUE THREAD

**Issue by willsmythe** [microsoft/azure-pipelines-tasks#11060]
(copied from #11046)

##  Required Information

*Type*: Bug
**Task Name**: CacheBeta

## Environment
- Azure Pipelines, multiple builds, provided below
- Hosted Agent multiple platforms:

It is a public project, you can access them from the URL.

### HTTP 503 throttling and eventually The HTTP request timed out when restoring cache

Build URL: https://dev.azure.com/cosmiafu/gugugu/_build/results?buildId=13
Job: macOS
Probable step causing the problem: Cache STACK_ROOT packages

**Comment by fadnavistanmay** [comment]
We have the fix released in agent 2.155.1 , added more retries. Closing the issue. Feel free to reopen. Thanks.

**Comment by Cosmius** [comment]
Sorry for that I do not have time to confirm that in these days, but thank you!
