### ISSUE TITLE
artifactignore file isn't ignored by default on publish pipeline artifact

### ISSUE THREAD

**Issue by hintbw** [microsoft/azure-pipelines-tasks#11069]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Feature**

**Enter Task Name**: **PublishPipelineArtifactV1**

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure Pipelines**
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  **healthcatalyst, CAP, DosRM-AzureAlerts**

- Agent - Hosted or Private: **Hosted**
    
    - If using Hosted agent, provide agent queue name: **ubuntu-latest**

## Issue Description

    The Publish pipeline artifact omits the .git folder by default, wouldn't it also be helpful to omit the .artifactignore file as well

**Comment by fadnavistanmay** [comment]
Hi @hintbw , it was discussed and was decided to not have this feature.
