### ISSUE TITLE
Azure Resource Group task: Deployment outputs removes quotes present in the Output JSON

### ISSUE THREAD

**Issue by N-Usha** [microsoft/azure-pipelines-tasks#11086]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Potential Bug: Prevent quotes from disappearing in ARM deployment output JSON in between Azure DevOps tasks

**Enter Task Name**: Azure Resource Group Deployment task - Azure Pipelines

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
 
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks/57388706#57388706
https://github.com/MicrosoftDocs/vsts-docs/issues/4463

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by N-Usha** [comment]
@bishal-pdMSFT - Please look into this

**Comment by liamfoneill** [comment]
Not quite sure if is the same issue but my Terraform Plan output is not what I expect where there should be double quotes (") - it outputs as &quot; instead: 
![image](https://user-images.githubusercontent.com/1243172/62771558-6641ea00-ba95-11e9-8e41-aebaca065580.png)

**Comment by anuragc617** [comment]
@liamfoneill looks different from this. Can you please open a new issue with more information?

**Comment by anuragc617** [comment]
Added information on how to use deployment outputs [here](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2#deployment-outputs). Closing this now.
