### ISSUE TITLE
VSTestV2: Rerun failed test doesn't use Batch option

### ISSUE THREAD

**Issue by XianghanWang** [microsoft/azure-pipelines-tasks#11089]
**Question, Bug, or Feature?**  
*Type*: Bug

## Environment
Azure Pipelines
Microsoft, DevDiv project

## Issue Description

VSTestV2 task

We set "Number of tests per batch" to 1. It works in normal test execution but not in rerun.
You can find a sample log from https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=406674&environmentId=1943114&_a=release-environment-logs. 

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ShreyasRmsft** [comment]
@XianghanWang this was consciously done as most customers fix the batch size/batch time based on the initial set of tests.

During re-run its generally a small subset of tests that run and the initially specified batch size might no longer be efficient.

**Comment by XianghanWang** [comment]
Thanks for the reply @ShreyasRmsft. I understand your point that in most case it is more efficient to just assign more tests to the run. 

But when a customer set a customized batch size, there must be a reason. Like our team set the batch size to 1 because our tests aren't stable when assign multiple tests to machine. We choose to use more time on automation lab execution instead of spend even more time on analyze the unstable tests manually.

We already provide the option to let customer choose what is best for them. It is great if we can keep using it in all places.

**Comment by ShreyasRmsft** [comment]
@PBoraMSFT to reply since this is a new ask.
