### ISSUE TITLE
Exception Message: The pipeline is not valid.

### ISSUE THREAD

**Issue by MaheshPesani** [microsoft/azure-pipelines-tasks#11088]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure PowerShell 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

We are setting Azure Subscription dynamically for the Azure PowerShell task. The $(ResourceGroup.Subscription) is an output variable from a preceding task. This was working fine on July 25th, 2019. But this week we started seeing the pipeline validation exception.
![image](https://user-images.githubusercontent.com/7193847/62655426-efd7a780-b92f-11e9-85f2-cc18592578ab.png)

Exception Message: The pipeline is not valid. Job Phase_1: Step AzurePowerShell input ConnectedServiceNameARM references service connection $(ResourceGroup.Subscription) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. (type PipelineValidationException)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
![image](https://user-images.githubusercontent.com/7193847/62656016-4beefb80-b931-11e9-8b29-cd912c41b358.png)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Exception Message: The pipeline is not valid. Job Phase_1: Step AzurePowerShell input ConnectedServiceNameARM references service connection $(ResourceGroup.Subscription) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. (type PipelineValidationException)
![image](https://user-images.githubusercontent.com/7193847/62655309-b0a95680-b92f-11e9-8173-c6b054778356.png)

**Comment by chshrikh** [comment]
@MaheshPesani could you please share the detailed logs, you can send it to RM_Customer_Queries[AT]microsoft[DOT]com.

**Comment by chshrikh** [comment]
@MaheshPesani  could you please confirm if you are using YML pipeline or regular Release definition

**Comment by ObsidianVoid** [comment]
@MaheshPesani Can you please share the account name, project name and definition name. Also, since when have you seen this error? Have there been any changes in the definition? 
You can send these details along with the full release logs to RM_Customer_Queries[AT]microsoft[DOT]com

**Comment by MaheshPesani** [comment]
> @MaheshPesani could you please confirm if you are using YML pipeline or regular Release definition

@chshrikh We are using a regular Release definition.

**Comment by ObsidianVoid** [comment]
The issue has been fixed and discussion closed over email.

**Comment by vinoddevopscloud99** [comment]
Whats the fix?

**Comment by ivan-sam** [comment]
I'm having the same issue using YAML pipeline and providing azure subscription name using variable group. Pipeline fails on compile time with error:

Step AzureResourceGroupDeployment input ConnectedServiceName references service connection $(lib-var-azure-subscription) which could not be found.

**Comment by MisinformedDNA** [comment]
@ivan-sam Did you find an answer? I'm stuck there now.

**Comment by JozoSlejko** [comment]
> The issue has been fixed after discussion over email.

What was the fix?

**Comment by MisinformedDNA** [comment]
I believe I read that azureSubscription/ConnectedServiceName/ConnectedServiceNameARM must be known at compile-time. And it appears that queued variables, as well as group variables, are not used at compile-time and, thus, not used in the evaluation.

So the workaround (as far as I can tell) is to use some combination of YAML-defined variables, parameters, variable templates, template conditions and/or environment variables (that are already set at compile time). I might be wrong on one (or more) of those, but the key thing is that they have to be determined early on in the process.

Seems to me that a var group is predefined and should be useable, but that does not appear to be the case. Hope this helps.

**Comment by krotofil** [comment]
Hello @ll,
I'm happy to bring this thread up again because I came across the same error. If I pass the variable groups into my template yaml, I can echo them, but an Azure Cli Task is not possible.
Can someone post a solution here?

**Comment by MisinformedDNA** [comment]
Try filing the issue in this repo. :)
