### ISSUE TITLE
DockerV2 build with AWS ECR Push

### ISSUE THREAD

**Issue by richardgavel** [microsoft/azure-pipelines-tasks#11080]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug?

**Enter Task Name**: Docker@2  

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
- Agent - Hosted or Private: Private (within AWS)

## Issue Description

I am using the Docker task to build and image and the ECRPushImage task to push the image up to AWS ECR (since the agent host is within AWS, it will use the creds of the host rather than needing to define a service connection). However, the Docker@2 build seems to only assign a tag to the image if part of a connection, which is not the case here. This means I don't know what source image name/tag to provide to the ECRPushImage, since all it results in is the SHA image ID.

**Comment by bansalaseem** [comment]
We have not tested the task without service connection flow. Do you want to debug it and raise a PR for it?

**Comment by ajinkya599** [comment]
Fixed the issue. The fix is being rolled out and should be available in a few days.
