### ISSUE TITLE
Add 'always overwrites' option for 'Extract Files' task.

### ISSUE THREAD

**Issue by gavinwa** [microsoft/azure-pipelines-tasks#11082]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

I hope 'Extract Files' task can provide the option that always overwrites.
Here is the task link: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Add 'always overwrites' option for 'Extract Files' task.

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The task was blocked and failed by replace option prompt.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Would you like to replace the existing file:
  Path:     F:\agent-3\_work\r1\a\ui-next\PaxHeader
  Size:     168 bytes (1 KiB)
  Modified: 2019-07-05 23:15:16
with the file from archive:
  Path:     PaxHeader
  Size:     55099 bytes (54 KiB)
  Modified: 2019-07-05 23:15:16
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
Archives with Errors: 1

**Comment by jmalak** [comment]
I think it is bugy implementation of ExtractFile task.
All of used utilities by default generate prompt if output file exists.
It is not handled anyway.
Existing implementation doesn't use any option to well define behaviour for existing output files.
By example if you use tar.gz format on Windows then it fail if output file exists.
Default behaviour of tar is to override output files, but on Windows behaviour is wrong.

**Comment by jmalak** [comment]
Wasting of time to write here anything.
