### ISSUE TITLE
This line leads to customer confusion...

### ISSUE THREAD

**Issue by ernani** [microsoft/azure-pipelines-tasks#11098]
https://github.com/microsoft/azure-pipelines-tasks/blob/db1a26a76be78d6a4d97144ebd861d08ae8a8c3e/Tasks/AzureResourceGroupDeploymentV2/task.json#L176

Please do consider renaming the label to **'Complete (will destroy existing resources)'** to allow the customers to be aware of the potential damage it may cause to existing resources.

Best Regards!

**Comment by anuragc617** [comment]
Hi @ernani https://docs.microsoft.com/en-us/azure/azure-resource-manager/deployment-modes describes more about it and link to this is already given in the [task.json](https://github.com/microsoft/azure-pipelines-tasks/blob/db1a26a76be78d6a4d97144ebd861d08ae8a8c3e/Tasks/AzureResourceGroupDeploymentV2/task.json#L173)

**Comment by ernani** [comment]
I would rename it just in case as some developers are experimenting with DevOps before knowing the impact of both modes and may cause a unrecoverable harm (that recently happened in a real customer case scenario).
