### ISSUE TITLE
AzureResourceGroupDeployment file path for "object" parameter in overrideParameters

### ISSUE THREAD

**Issue by damienpontifex** [microsoft/azure-pipelines-tasks#11090]
## Required Information

**Question, Bug, or Feature?**  Question, could be feature request if doesn't exist

**Enter Task Name**: AzureResourceGroupDeployment@2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines 
- Account name: pontifex
- Project: EvoqueRehab
- Build details: "Reporting CI" - build id = 947

- Agent - Hosted or Private: Hosted Ubuntu 1604

## Issue Description

I would like to use the Azure resource group deployment task where one of the parameters is read from a JSON file containing a JSON object. looking at `az group deployment create` I used to do it from the command line by `az group deployment create -g EvoqueGraphFunctions-dev --template-file azuredeploy.json --parameters logicAppDefinition=@Evoque.definition.json`

From yaml passing the input parameter of `overrideParameters: -logicAppDefinition @$(Pipeline.Workspace)/arm/Evoque.definition.json` I get the error

"There was an error while overriding 'logicAppDefinition' parameter because of 'SyntaxError: Unexpected token @ in JSON at position 0', make sure it follows JavaScript Object Notation (JSON)"

It's obviously not reading the file but thinking it's a JSON inline object. The file is a logic app definition so I'd like to be able to pass it in.

### Task logs

Checking if the following resource group exists: EvoqueGraphFunctions-dev.
Resource group exists: true.
Creating deployment parameters.
The detected encoding for file '/home/vsts/work/1/arm/azuredeploy.json' is 'utf-8'
There was an error while overriding 'logicAppDefinition' parameter because of 'SyntaxError: Unexpected token @ in JSON at position 0', make sure it follows JavaScript Object Notation (JSON)
Starting Deployment.
Deployment name is azuredeploy-20190808-042945-9c71
There were errors in your deployment. Error code: InvalidTemplate.
##[error]Deployment template validation failed: 'The provided value for the template parameter 'logicAppDefinition' at line '1' and column '255' is not valid.'.
##[error]Task failed while creating or updating the template deployment.

**Comment by anuragc617** [comment]
Hi @damienpontifex, thanks for reporting this. This feature is not yet supported in AzureResourceGroupDeployment task.

**Comment by damienpontifex** [comment]
Thanks @anuragc617 is it something that might be supported in the future? And hence keep this open to track a potential future feature?

**Comment by bishal-pdMSFT** [comment]
Agree with @damienpontifex , re-activating the issue and marking enhancement. But I am not sure when we will get to this as this is the first such request we have received.

**Comment by cconrado** [comment]
any update on this?

**Comment by cconrado** [comment]
@damienpontifex @bishal-pdMSFT any update on this?
