### ISSUE TITLE
DotNetCoreInstallerV0 task is using deprecated releases.json file that has been deleted.

### ISSUE THREAD

**Issue by alexperovich** [microsoft/azure-pipelines-tasks#11100]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreInstallerV0

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/mseng/Tools/_build/results?buildId=10147432&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: windows-2019-vs2019

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

This line https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreInstallerV0/releasesfetcher.ts#L148 is referencing a file that was planned to be deleted in March and was finally deleted less than an hour ago.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Tool to install: .NET Core sdk version 2.2.301.
\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'd:\a\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6\0.2.4\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Checking if a cached copy exists for this version...
The cache does not contain the requested version of .NET Core. Downloading and installing it now.
Getting URL to download .NET Core sdk version: 2.2.301.
##[error]Unexpected token : in JSON at position 3

**Comment by anuragc617** [comment]
Hi @alexperovichm the release.json file is still there. If you want you can use DotNetCoreInstallerV2 which is using new release file.

**Comment by MattGal** [comment]
@anuragc617 I can't seem to reopen this issue but you are mistaken, the file is "still there" because the absence of it broke the world and you still need to update.

This commit removed it: https://github.com/dotnet/core/commit/269b01957b05bf1a8b1b2f2d470810a2be7c4c15

And since we couldn't easily get Azure Pipelines Tasks to turn on a time, this commit puts it back:
https://github.com/dotnet/core/commit/cf7b530e11fb6bd669ddb60d4745e074a9360442

This announcement said it's going to be removed in March of 2019 (which has already long passed).  

The task very much still needs to be fixed.

@leecow FYI

**Comment by alexperovich** [comment]
@MattGal is correct, this needs to be re-opened.

**Comment by bishal-pdMSFT** [comment]
We were not aware that releases.json is going to be deleted. We knew that releases-index.json was the new one and hence we have released a new major version of task (2.*) which uses this new json file. Any new user would be using this version of task.

Coming to the mitigation for users already using older version of task, we still need to have releases.json. It is fine if it is not updated with new .Net Core versions, but it would great if it can be archived and not deleted so that we can keep using it. @leecow

**Comment by leecow** [comment]
@bishal-pdMSFT , having this file live and accessible is not the right thing to do as anyone depending on the file will be installing potentially vulnerable .NET Core assets. You could take ownership of the v1 file and archive for your purposes though I would suggest working out how to migrate everyone away from the old build task. 

Let me know when you expect to have a solution utilizing the new json and your thoughts on the obsolete file.

**Comment by bishal-pdMSFT** [comment]
@leecow would you elaborate more what do you mean by "potentially vulnerable"? All the version listed in releases.json is publicly released version. Someone can use it to install EOL/un-supported version, but I guess they same do the same even with new json files.
Let me discuss internally on whether we want to migrate users from v1 to v2 or to keep using archived obsolete releases.json.

**Comment by leecow** [comment]
Yes, a user can always install older versions through a number of avenues. I would like to get to a place where that's not enabled by this file to avoid the situation where someone could unknowingly install a vulnerable version by parsing the file and just installing the latest found.

**Comment by bishal-pdMSFT** [comment]
@leecow we have planned the work to remove dependency on deprecated releases.json. We plan to start it second half of next week. I will update you once we completely remove the dependency.
But this file needs to be present till that time. Requesting you to ensure that.

**Comment by leecow** [comment]
Thanks for the update @bishal-pdMSFT. The file will remain in place until you give the "all clear".

**Comment by leecow** [comment]
@bishal-pdMSFT, checking on progress for this task.

**Comment by bishal-pdMSFT** [comment]
@leecow we had made the changes and were ready to roll it out, but our changes had to be reverted at last moment due to some flakiness in system and we missed the train. We will be able to go with next train in about 3 weeks time. I will update you.

**Comment by vinodkumar3** [comment]
Changes has been deployed already via this [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/11183).
