### ISSUE TITLE
android support repository

### ISSUE THREAD

**Issue by SanathKumar123** [microsoft/azure-pipelines-tasks#11105]
Hey, guys when I run the build in my installed android studio it's showing

Could not find any version that matches com.android.support:appcompat-v7:29.+.
Versions that do not match:
  - 26.0.0-alpha1
  - 25.3.1
  - 25.3.0
  - 25.2.0
  - 25.1.1
  - + 50 more
Required by:
    project :app

Please install the Android Support Repository from the Android SDK Manager.

how should I fix it?

**Comment by abhi2801** [comment]
i am also facing the same issue
