### ISSUE TITLE
DockerV2 - Where did Run go?

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/azure-pipelines-tasks#11118]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DockerV2

## Environment
- Azure Pipelines
- Agent - Hosted

## Issue Description

DockerV0 & DockerV1 support running Docker images but it looks like v2 does not support this.

Is this coming or what was the reason why it was removed?

**Comment by shashankbarsin** [comment]
@tomkerkhove Docker@0 and Docker@1 had run command, but doing run using Docker task had no benefits when compared to doing run using docker script. For example, the login action works with Docker registry service connection and login credentials are cleaned up on the agent at the end of the job. 

As a result, we've only retained those actions where the task has benefits over and above running the equivalent commands in script.

For docker run, it's still possible to directly use docker binary on the agent by using script - 

```
- script: docker run <arguments>
```

**Comment by tomkerkhove** [comment]
That makes sense but is a bit confusing. Maybe good to improve the task description a bit then?

It still says it supports run:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerV2/task.json#L5


Anyhow, thanks for clarifying!
