### ISSUE TITLE
Can we restart DTAAgentExecutionService on remote machine using TFS Build Definition Continuous Integration

### ISSUE THREAD

**Issue by NagaLakshmiE** [microsoft/azure-pipelines-tasks#11110]
Our scheduled build definitions are not triggered(sometimes) at scheduled time and are failed at the first deployment step but these build definitions run fine if we restart the Test agent. 

Related to https://github.com/microsoft/azure-pipelines-tasks/issues/5279

**Comment by ShreyasRmsft** [comment]
What version of TFS are you using?

**Comment by NagaLakshmiE** [comment]
Hi ShreyasRmsft, 

I am using Version 15.105.25910.0

Thanks

**Comment by ShreyasRmsft** [comment]
@NagaLakshmiE we have actually been moving away from Run Functional test task and asking customers to move to VsTestV2 task.

Are you running your tests in build or release? The VsTestV2 task in TFS 2017 Update 3 has all the capabilities of the RFT task in release pipeline and in TFS 2018 all the capabilities in the build pipeline as well. In VsTestV2 we moved away from the model that made RFT unreliable and in the hosted service RFT has been deprecated already.
