### ISSUE TITLE
Can no longer execute Unit Tests on UNC Path

### ISSUE THREAD

**Issue by RichJeanes** [microsoft/azure-pipelines-tasks#11113]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VsTestV2
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure DevOps Server
    
    - If using TFS on-premises, provide the version: 
        17.143.28912.1 (AzureDevOps2019.0.1)

## Issue Description
Our organization just upgraded from TFS 2018 RTM on-prem to Azure DevOps Server which includes upgrading the VsTest task from v2.1.9 to 2.143.9 which can no longer use UNC paths in the Search Path parameter. I can find no documentation stating why this is not allowed nor when exactly this change was made. We have many in-house libraries that are used across many in-house applications creating a lot of dependencies that we check before deployment using Unit Test DLLs for each of our libraries stored on a file share.

Currently we have 18 Unit Test DLLs and this number will only grow as we continue development so copying all of the required test files for every application Release is not a very good solution for us (suggested solution given [here](https://github.com/microsoft/azure-pipelines-tasks/issues/6966#issuecomment-383210844) in response to this [question](https://github.com/microsoft/azure-pipelines-tasks/issues/6966#issuecomment-382992748)).

Is there a way for us to re-enable this capability or some other suitable solution for what we would like to do?

### Error logs
`##[error]Error: Path to test sources search folder cannot be a UNC path. Please provide a rooted path or a path relative to $(System.DefaultWorkingDirectory).`

**Comment by cltshivash** [comment]
@RichJeanes This feature is no longer supported. You will need to copy the files to the agent machine in a prior step.
