### ISSUE TITLE
Converting tasks to a task group - Guid errors

### ISSUE THREAD

**Issue by smgtreker** [microsoft/azure-pipelines-tasks#11117]
Hi, 

I am attempting to parameterize the Azure DevOps ARM template deployments with things like "
$(AzureResourceGroup)". I have found that this does work, but when trying to convert the tasks to a task group, I get errors around guids. Is there a suggested / recommended way of using the Azure tasks with variables for things like the subscription, resource group name, location, etc?

Thanks

**Comment by anuragc617** [comment]
Hi @smgtreker, which task does your task group contains? Can you please share the error logs and screenshots of your task group?  I tested parameterizing the subscription, resource group, and location and it is working as expected.

**Comment by anuragc617** [comment]
@smgtreker can you please share the logs?

**Comment by bishal-pdMSFT** [comment]
@smgtreker please share the logs as requested earlier

**Comment by smgtreker** [comment]
Hi,

Could you please point me to which logs you would like, or which section to retrieve the logs please?

Thanks,

Steve
________________________________

**Comment by bishal-pdMSFT** [comment]
@smgtreker logs/messages of error your are facing

> I have found that this does work, but when trying to convert the tasks to a task group, I get errors around guids. 

Also it would help to see the screenshot for the task group you are trying to create

**Comment by issacnitin** [comment]
@smgtreker closing this issue. If you have logs/errors to share please reactivate the issue.
