### ISSUE TITLE
Azure Devops Deploy Azure Function App throws 504 time out error

### ISSUE THREAD

**Issue by SrinathAka** [microsoft/azure-pipelines-tasks#11121]
Until yesterday i was able to deploy my code using Azure devops Task "Deploy Azure Function App" but it started throwing the below error
Failed to update App service 'BPPythonAzureFunc' application settings. Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)

i then added system.debug to true and i can see that it is failing at the point of updating application settings.The strange this is the code is still deployed and the function works as expected if i trigger the end point. Below are the logs from console

**019-08-14T09:02:42.8572945Z ##[debug][PUT]https://management.azure.com/subscriptions/29d8aad9-221b-4515-be64-61bfafde8bd8/resourceGroups/BPPythonAzureFunc/providers/Microsoft.Web/sites/BPPythonAzureFunc/config/appsettings?api-version=2016-08-01
2019-08-14T09:04:42.9650387Z ##[debug]Encountered a retriable status code: 504. Message: 'Gateway Timeout'.**

Please can you point me in the right direction as i was able to use the same task and was able to deploy successfully until i hit this error

**Comment by jparfianowicz** [comment]
The same here. Trying to update application settings from DevOps pipeline throws: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504). When updating manually through portal.azure.com there also is an error (but no details). Funny thing is the the settings are actually updated.

**Comment by lyona** [comment]
I'm also getting this. It was working yesterday

**Comment by vincentdass** [comment]
Apologies for the inconvenience. 
We identified the issue and working on the fix.

**Comment by shivaniseth** [comment]
> Apologies for the inconvenience.
> We identified the issue and working on the fix.

what's the fix ? how is it resolved?

**Comment by jparfianowicz** [comment]
It is still not fixed. It also breaks when deploying arm templates that have application settings defined. This actually breaks most of our pipelines. This is becoming a high priority issue.

**Comment by vincentdass** [comment]
@jparfianowicz , Is the issue still repro-ing?
The issue was fixed from App Service side. We have also reacted to it https://github.com/microsoft/azure-pipelines-tasks/pull/11147

**Comment by SrinathAka** [comment]
I can confirm this is now resolved finally

**Comment by SrinathAka** [comment]
This can be now closed
