### ISSUE TITLE
Deploy resource group with tags in Azure pipeline

### ISSUE THREAD

**Issue by sakshamagarwal** [microsoft/azure-pipelines-tasks#11122]
How do I deploy a resource group in azure pipelines with tags at resource group level. I am following the documentation here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops

**Comment by ArieHein** [comment]
You add another step after the resource group creation to add the tags

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags#powershell

**Comment by anuragc617** [comment]
Hi @sakshamagarwal, you can use Azure PowerShell or Azure CLI task to update the tags of the resource group.
Using Azure Powershell: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags
Using Azure CLI: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags

**Comment by anuragc617** [comment]
Closing this issue.

**Comment by weevil44** [comment]
I have required tags for Resource Groups.  The Resource Group creation fails because the required tags are missing so I can't update with Powershell after creation.  Is there any way to handle this?

**Comment by ArieHein** [comment]
You could have the tags already IN the ARM template, but its not very customizable.

You create an ARM template that will be in your repo, the template should have the section of the tags already existing. If the Tags section isnt in the ARM template before hand, your first step will be to inject the section into the ARM via json tasks or powershell scripts.

If the ARM template has the Tags section already in but uses "general" values as placeholders, your first step in the pipeline would be to inject values into the arm template via json tasks. After that you have the RG deploy task and use the changed ARM template in that task.

**Comment by RobHofmann** [comment]
https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create

You can simply use Azure CLI to create the resourcegroup with the desired tags.

My pipelines usually look something like this:
1. Create Resourcegroup with Azure CLI
2a. Either create resources with CLI
2b. Or create resources with ARM
3. Do app deploy or post infrastructure steps.

PS. You can not create a resourcegroup from ARM templates. Only resources inside a RG.
