### ISSUE TITLE
PublishBuildArtifacts@1 and AzureCLI@1 fail with ENOENT when run inside a container

### ISSUE THREAD

**Issue by achamayou** [microsoft/azure-pipelines-tasks#11137]
## Required Information

Type: Bug
Affected Tasks: PublishBuildArtifacts@1 and AzureCLI@1  

## Environment
- Server - Azure Pipelines
    - Account name: MSRC-CC, Project Name: CCF
      Link to build: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=375
    - Private Agent on Ubuntu 18.04 running version 2.155.1

## Issue Description

Tasks fail with:
```
##[error]Unhandled: ENOENT: no such file or directory, open '/__w/.taskkey'
```

### Task logs

```
##[section]Starting: Push Performance Data
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a Shell script when running on Linux agent or Batch script when running on Windows agent.
Version      : 1.155.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
##[error]Unhandled: ENOENT: no such file or directory, open '/__w/.taskkey'
##[section]Finishing: Push Performance Data


##[section]Starting: Publish cimetrics graphs as build artifact
==============================================================================
Task         : Publish build artifacts
Description  : Publish build artifacts to Azure Pipelines or a Windows file share
Version      : 1.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
##[error]Unhandled: ENOENT: no such file or directory, open '/__w/.taskkey'
##[section]Finishing: Publish cimetrics graphs as build artifact
```

## Troubleshooting

The problem is caused by the lack of a __w directory under the container. It is solved by mounting the agent workspace manually:

```
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx:latest
    options: -v /mnt/build:/__w/
```

Since .taskkey is already mounted by default during container initialisation, I believe the steps need to be adjusted to use that rather than rely on /__w. Alternatively, mounting /__w should happen automatically when using a container.

**Comment by achamayou** [comment]
@joshmgross, thanks for following up, please let me know if I can help with testing or by providing additional information.

**Comment by achamayou** [comment]
@joshmgross I've not done that before, is it this process? https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops

If so, that looks fairly involved, is there any way I can pick up build artifacts from #11203? I'm running this on custom agents, in case it helps (by which I mean I can easily drop files somewhere in the agent install).

**Comment by achamayou** [comment]
@joshmgross Thank you, I’ve installed the build of the extension you linked and I can confirm that it fixes the problem for us: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=582

**Comment by achamayou** [comment]
@joshmgross Is it safe to assume that when PublishBuildArtifactsV1 1.159 and later are released, my agents will pick them up automatically, or will I need to `tfs build tasks delete` the copy of PublishBuildArtifactsV1 I have now?

In any case, thank you for the super quick fix, it's much appreciated!

**Comment by achamayou** [comment]
@joshmgross excellent! :)

**Comment by vineetmimrot** [comment]
Hey @achamayou,
We have fixed the AzureCLI task. [Here](https://github.com/microsoft/azure-pipelines-tasks/blob/8c6ddd6003f122058147dc421b62fd0ccf75595d/AzureCLIV1.zip) is the update package. Please try it out and let us know the feedback.

**Comment by achamayou** [comment]
@vineetmimrot it works great: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=657

I've removed the workaround we had now, thank you for getting this fixed so quickly!

**Comment by bishal-pdMSFT** [comment]
Closing this issue as both tasks are fixed.
