### ISSUE TITLE
ExtractFiles failing in Release pipeline with ERROR: Can't allocate required memory!

### ISSUE THREAD

**Issue by raswinraaj** [microsoft/azure-pipelines-tasks#11135]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ExtractFilesV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
   
  
- Agent - Hosted or Private: 
    
    - Hosted Agent Queue Name : windows 2019

  
## Issue Description
ExtractFiles failing in Release pipeline with ERROR: Can't allocate required memory! in all the windows hosted agents (2019, 2017 etc). Also, getting one more error where it is failing to replace some codecoverage file without overwriting.

### Task logs
[extractfiles.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3508589/extractfiles.zip)

**Comment by damccorm** [comment]
Not sure how much we can do about this - it looks like you are indeed just running out of memory. I think the only real option here is to spin up a self-hosted agent with more memory. Any reason to think that we shouldn't be getting this error here?

**Comment by dominikfoldi** [comment]
We are having a self-hosted agent with tons of memory but getting the same error.
Our solution was to use a hosted Ubuntu agent, because the problem does not exist there.

**Comment by damccorm** [comment]
That's probably just a difference in how windows/linux tools are implemented then - from our side there's no difference in how we invoke them. Again I think there's not a whole lot we can do there.

**Comment by damccorm** [comment]
Closing since I don't think there's anything we can do from our end

**Comment by b926vb** [comment]
We are facing the same issue with this task in a deployment job. When will this be resolved?
