### ISSUE TITLE
PublishCodeCoverageV1 uses out-datet version of ReportGenerator

### ISSUE THREAD

**Issue by svrooij** [microsoft/azure-pipelines-tasks#11138]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResultsV1  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Smartersoft, Roostersync, Roostersync Core, Build 20190816.2

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The used dll for the report generator is out-datet. The task uses this [ReportGenerator](https://github.com/danielpalme/ReportGenerator). Locally I have installed the latest version, which is 4.2.15 and that has a ton of bugfixes on board. One of these is counting the correct number of lines if the coverage file consists of multiple dlls.

I cannot find a package file on how this dll below `PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.155.0/netcoreapp2.0/ReportGenerator.dll` got into the final task package, but it would be really nice if you guys could update it.

### Task logs

```text
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.155.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
[command]/usr/bin/dotnet /home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.155.0/netcoreapp2.0/ReportGenerator.dll -reports:/home/vsts/work/1/s/Coverage/coverage.cobertura.xml -targetdir:/home/vsts/work/_temp/cchtml -reporttypes:HtmlInline_AzurePipelines
Loading report '/home/vsts/work/1/s/Coverage/coverage.cobertura.xml' 1/1
```

### Screenshots from generated reports

<img width="255" alt="Azure report" src="https://user-images.githubusercontent.com/1292510/63182468-ebf40580-c052-11e9-96d4-36a9f51991c3.png">

<img width="233" alt="Local report" src="https://user-images.githubusercontent.com/1292510/63182488-fa422180-c052-11e9-944c-3f697da68101.png">

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

I don't thing you guys need any logs for this issue, do you?

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by vagisha-nidhi** [comment]
We have updated the Report Generator version to 4.2.20.
