### ISSUE TITLE
Azure Hybrid model: Build on Cloud + Self hosted agent for Deploy/Test

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11145]
Hi,

I am using Azure pipeline for my ASP.NET core application which is based on VS 2017 & .Net core 2.2.

My unit/integration tests are written in NUnit and have dependency on on-prem servers. Therefore, I am thinking of having the build done on Azure hosted VMs but deploy/test on self-hosted agents.

I have read and re-read the docs on self hosted agents, but can't quiet get on the detailed steps required to 
a. setup the machine (e.g. do I need VS 2017 on my self hosted box)
b. transfer the binaries from Azure build VM to on my self hosted box
c. invoke the unit tests and collect coverage etc
d. publish the test/coverage results (transfer from self hosted box to Azure VM)
e. archive the build along with test/coverage results.

Is there some documentation, hands-on lab, tutorial etc available for this hybrid model of using Azure DevOps?

Thanks

**Comment by PBoraMSFT** [comment]
@saxenark - I don't believe we have docs to show the hybrid usage. However, you can achieve what you are looking for by using multiple jobs in the pipeline:
1. A job to build - this job would use the hosted agents
2. A job to deploy and test - this job would use the self hosted agents

An example of multiple jobs to split build and test in separate jobs is mentioned in [this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops#run-tests-in-parallel-in-build-pipelines). 
This above doc was written to show test parallelism, but you can skip the parallelism part if you don't need that.

As for what software you need on self-hosted agents, if you plan to use it for build, you will need an appropriate installation of Visual Studio. If you only want to run tests, you can skip the Visual Studio requirement by using the [Visual Studio Test Platform Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops).

I am closing this issue as this is a doc question and not a product issue. For doc issues/questions, please use https://github.com/MicrosoftDocs/vsts-docs/

**Comment by saxenark** [comment]
Hi,

I have this stage which I define in my yaml for running tests on my self hosted agent. How do I specify in my yaml that this stage must run on my self hosted agent?

```
- stage: "AutomatedTesting"
  jobs:
  - job: "AutomatedTesting"
    pool:
      vmImage: 'vs2017-win2016'

```
Thanks,
Anubhav.

**Comment by PBoraMSFT** [comment]
@saxenark - Please refer the [YAML schema doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool)
