### ISSUE TITLE
Permission Error Publishing Code Coverage on Ubuntu

### ISSUE THREAD

**Issue by ardalis** [microsoft/azure-pipelines-tasks#11142]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResultsV1

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/Ardalis-Specification/Ardalis.Specification/_build/results?buildId=53
https://github.com/ardalis/Specification/blob/ardalis/integrationtests/azure-pipelines.yml

- Agent - Hosted
https://github.com/ardalis/Specification/blob/ardalis/integrationtests/azure-pipelines.yml
    
## Issue Description

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/782127/63226684-e578a180-c1aa-11e9-852c-c0d84a3737cb.png)

##[warning]Error occurred while publishing code coverage files. Error: Access to the path '/home/vsts/work/1/s/TestResults/coverage/summary53/Cobertura.xml' is denied.
##[section]Async Command End: Publish code coverage
##[error]Access to the path '/home/vsts/work/1/s/TestResults/coverage/summary53' is denied.

**Comment by ShreyasRmsft** [comment]
@ardalis this is not an issue with the publish code coverage task. I tried a simple commandline to list the permissions on the file and i get access denied. This issue is the right place to track this https://github.com/microsoft/azure-pipelines-tasks/issues/8762.
