### ISSUE TITLE
PublishTestResults@2 testRunTitle not applied on windows agents

### ISSUE THREAD

**Issue by MaceWindu** [microsoft/azure-pipelines-tasks#11141]
*Type*: Bug

**Enter Task Name**: PublishTestResults

## Environment
- Server - Azure Pipelines

- https://dev.azure.com/linq2db/linq2db/_build/results?buildId=997&view=ms.vss-test-web.build-test-results-tab

vmImage: 'windows-2019'

yml: https://github.com/linq2db/linq2db/blob/f3cd07aabf43045a581ad8a8a0a5f8fd1173221f/azure-pipelines.yml#L469

## Issue Description

`testRunTitle` parameter is ignored for windows agents and test results uploaded with generic name, infered from trx file name (?).
From task code I see that for windows it could use windows-specific code branch, so it could be the reason https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishTestResultsV2/publishtestresults.ts#L109

**Comment by sahitiyerramilli** [comment]
We tried testing this and the test results were uploaded with the same name as the test run title using the 2.158.0 version of the PublishTestResults task. Please double check with this version or higher and reopen the issue if the problem persists.
