### ISSUE TITLE
SqlAzureDacpacDeployment: can't control exported bacpac location

### ISSUE THREAD

**Issue by kevin-david** [microsoft/azure-pipelines-tasks#11157]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeployment  

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

- Agent - Hosted or Private: N/A, both

## Issue Description

When using the `export` `deploymentAction`, there's no way to control where the output file goes. It always goes to `GeneratedOutputFiles\myDatabase.bacpac` inside the source tree.

I tried supplying `/TargetFile:` but that resulted in a duplicate argument error:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\SqlPackage.exe" /Action:Export /TargetFile:"C:\agent\_work\3\s\GeneratedOutputFiles\myDatabase.bacpac" /SourceServerName:"myDatabase.database.windows.net" /SourceDatabaseName:"myDatabase" /SourceUser:"myDatabase" /SourcePassword:"********" /p:AllowIncompatiblePlatform=true /TargetFile:C:\agent\_work\_temp\\prod_backup.bacpac
```

I also tried using the `dacpacFile` or `bacpacFile` inputs, but that didn't change behavior either, and didn't result in errors - the most logical choice would probably be `bacpacFile` for the `export` `deploymentAction`.

The only workaround is to live with the default path and use the `SqlDeploymentOutputFile` output variable to determine where it lives and delete it afterward. Unfortunately, this makes it impossible to do cleanup at the beginning of a pipeline.

**Comment by Ajay-MS** [comment]
@kevin-david 

Yes, currently only default path is supported. I have marked it as an enhancement.
