### ISSUE TITLE
davpac release issue: SENSITIVITY CLASSIFICATION

### ISSUE THREAD

**Issue by ahughes257** [microsoft/azure-pipelines-tasks#11150]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
Azure SQL Database deployment

## Environment
- Azure Pipelines
     - account name, team project name, build definition name/build number: 
DeltServicesSolutions , delt_dw, _delt_dw-NuGet-DBArtifact-Build/20190819.2

- Agent: 
    - Azure Pipelines 
    - windows 2019

## Issue Description
error on release due to project containing; 
ADD SENSITIVITY CLASSIFICATION TO
    [schema].[table].[column]
    WITH (LABEL = 'Confidential', INFORMATION_TYPE = 'Financial'); 
when the above is removed from the project on relevant tables then the project release fine, using VS2019 and schema compare with project to instance the release is completed successfully. 

### Error logs
2019-08-19T12:08:34.4667927Z Initializing deployment (Start)
2019-08-19T12:08:36.9718681Z Initializing deployment (Failed)
2019-08-19T12:08:37.1238670Z ##[error]*** An error occurred during deployment plan generation. Deployment cannot continue.
2019-08-19T12:08:37.1284750Z ##[error]The Element or Annotation class SqlSimpleColumn does not contain the Property class SensitivityLabel.

2019-08-19T12:08:37.3326353Z ##[error]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting

**Comment by arjgupta** [comment]
Hi @ahughes257 , this seems like an issue with the dacpac file that you are using. I was able to search for the error message and found [this](https://docs.microsoft.com/en-us/sql/t-sql/statements/add-sensitivity-classification-transact-sql?view=azuresqldb-current) doc that might help. This is not a task issue.

**Comment by ahughes257** [comment]
Hey Arjun

Thank for the syntax page, I have already read and used this to deploy to
the database. The database project builds perfect locally and deployment is
also fine from visual studio to Azure SQL database.
The only place there is a problem with deployment is though the pipeline
release job...
I have simply removed the sensitivity classification as it doesn't work
with the release job. Again there is no problem with the visual studio
project or dacpac...

Kind regards
Aaron

**Comment by Ajay-MS** [comment]
Hello Aaron, 

Can you share your local deployment logs (in case deployment you have done is through Azure Dev Ops) or Path of SQLPackage.exe in case you have done using SQLPackage.exe directly? 

Also, Share debug complete logs for the failed release. Pass additional argument in task `/Diagnostics:true`. 

You can send logs at `RM_Customer_Queries@microsoft.com`

**Comment by eaarora-ms** [comment]
@ahughes257  Are you still facing this issue?

**Comment by ahughes257** [comment]
There was no build issue locally it only happens withing the build pipeline
therefore I have removed the classifications from the database project
completely due to the issue.

So I am unsure if this issue still exists or not. I would suggest that you
set up your own database project and test the classification key words work
within the build task.

Kind regards

Aaron
