### ISSUE TITLE
`##vso[task.complete]` not processed on ubuntu hosted agents

### ISSUE THREAD

**Issue by Cellule** [microsoft/azure-pipelines-tasks#11163]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: Bash/CmdLine

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - Account Name: MaintainX
      - Project Name: MaintainX
      - Build Definition: `MaintainX-CI (1)` id: `23`
      - Release Definition: `Deploy MaintainX AWS Services` id: `1`

- Agent - Hosted     
    - If using Hosted agent, provide agent queue name:
      - Agent pool: `Azure Pipelines` 
      - Agent Specification/OS: `ubuntu-16.04`

## Issue Description

`##vso[task.complete]` does not affect the task's result on ubuntu-16.04
I tried with `result=Failed` and `result=Canceled`.
It works with a Windows agent

![image](https://user-images.githubusercontent.com/4157103/63389295-435ae400-c379-11e9-857a-9c2b50a409d1.png)

![image](https://user-images.githubusercontent.com/4157103/63389311-51106980-c379-11e9-9bdf-326cd87923d2.png)

### Task logs

[logs_1245.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3522880/logs_1245.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
No Errors

**Comment by bryanmacfarlane** [comment]
# is a quote in linux.  did you try quoting it?

**Comment by Cellule** [comment]
hahaha .... too used to Windows development, thanks for pointing my beginner's mistake, it works now

**Comment by bryanmacfarlane** [comment]
awesome ;)
