### ISSUE TITLE
Add "Haxe tool installer" task

### ISSUE THREAD

**Issue by andyli** [microsoft/azure-pipelines-tasks#11168]
I'm from Haxe Foundation. I'm maintaining the [Haxe language support for TravisCI](https://docs.travis-ci.com/user/languages/haxe/), which we found very useful for the Haxe community. We have been slowly migrating to Azure Pipelines, so I would like to contribute a Haxe tool installer which basically does the same thing as the NodeTool/GoTool etc. I understand I can publish an extension to the marketplace, but I prefer having it here for better integration.

My questions: Would you accept a PR of adding a Haxe tool installer task? What else is needed to have it appear in Azure Pipelines? Am I correct to use "HaxeTool" for the new task?

**Comment by damccorm** [comment]
Hi - sorry for the slow response. In general, our recommendation is that you publish it as a 3rd party tool. We only have Microsoft built/maintained tasks in this repo, and I don't think we have the bandwidth to support this at this point.

I'd definitely encourage you to publish it though, it will be available on the marketplace where people can pick it up.

**Comment by damccorm** [comment]
I'm going to close since I think that answers your question, feel free to comment and I'll reopen!
