### ISSUE TITLE
`containerRegistry` parameter name is misleading

### ISSUE THREAD

**Issue by ericdrobinson** [microsoft/azure-pipelines-tasks#11176]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerV2

list here (V# not needed):  

- [Docker](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2)

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - **N/A**

- Agent - Hosted or Private: 
    
    - **N/A**

## Issue Description

The parameter name `containerRegistry` suggests that the name of the Azure Container Registry resource should be used directly (e.g. `<containerName>.azurecr.io`). This results in an error when attempting to run the Task in Pipelines.

I understand that the Service Connection requirement is called out in the **Task Inputs** table in the documentation, but it is extremely easy to miss, especially when you [mistakenly] believe you already understand what the parameter refers to.

Please consider deprecating the `containerRegistry` name and using something that indicates that a Pipelines [Service Connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg) is expected. One example might be `registryServiceConn`.

Theoretically, this should be aligned with the parameter name used in the [DockerCompose Task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerComposeV0). The equivalent parameter there [appears to be called](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose#other-container-registries) `dockerRegistryEndpoint`.

### Task logs

**N/A**

## Troubleshooting

**N/A**

### Error logs

**N/A**

## Errata

This issue was originally posted in the [Task Docs repository](https://github.com/MicrosoftDocs/vsts-docs/issues/5307) but was moved here by suggestion.

**Comment by shashankbarsin** [comment]
@ericdrobinson deprecating the input would result in breaking all the pipelines that are already using this task. We will instead consider improving the intellisense and validation options in the pipeline editor experience.

**Comment by shashankbarsin** [comment]
Removing the `containerRegistry` is not possible with Docker@2 as doing so would break the pipelines having Docker@2 task using this input. About adding another input as alias, it will lead to having 2 suggestions appear for selecting Docker registry service connection in the pipeline definition editor intellisense, which we want to avoid. So we will fix this issue when we release the next major version of a container builder task.

**Comment by ericdrobinson** [comment]
@shashankbarsin Let's break this down a bit:

>Removing the `containerRegistry` is not possible with Docker@2 as doing so would break the pipelines having Docker@2 task using this input.

I'm not advocating for the **removal** of the parameter. Simply that it be marked as **deprecated**.

>About adding another input as alias, it will lead to having 2 suggestions appear for selecting Docker registry service connection in the pipeline definition editor intellisense, which we want to avoid.

First off, I assume that you are referring to the [Azure Pipelines](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines) extension when you talk about "Definition Editor IntelliSense". Second, the editor _**should**_ be smart enough to do the following **for properties/features marked as "deprecated"**:

1. **Not** show the option in the IntelliSense autocomplete options (it would show the replacement, however).
1. Optionally report the deprecation as a warning.

The above is **_standard_** workflow for fixing this exact type of issue. The Azure Pipelines Language Server (which the VSCode Extension uses) is even built to support deprecation workflows: the schema supports a [`deprecationMessage`](https://github.com/microsoft/azure-pipelines-language-server/blob/71e27e59f2a363731720293d39d8fe6817c6933f/language-service/src/jsonSchema.ts#L46)) and an option for not suggesting the property via [`doNotSuggest`](https://github.com/microsoft/azure-pipelines-language-server/blob/71e27e59f2a363731720293d39d8fe6817c6933f/language-service/src/jsonSchema.ts#L47).

Unless I've missed something, it appears that the underlying VSCode Extension for Azure Pipelines **_should_** support deprecation in a way that sidesteps all of the issues you've raised (as I understand them).

Am I missing something here?
