### ISSUE TITLE
PublishTestResults: Renamed test case is displayed with old name in Test Run Explorer UI

### ISSUE THREAD

**Issue by HealthyJR** [microsoft/azure-pipelines-tasks#11182]
**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: PublishTestResultsV2

## Environment

- TFS on-premises Version 16.131.28601.4
- mstest NUnit2 test execution (with custom testadapter)
- Publishing TRX format with PublishTestResultsV2 task

## Issue Description

A test case which was executed (and published to TFS) in the past gets renamed and executed again.
Resulting TRX looks fine with new test case name. But once it was published to TFS the verdict of the test case is reported under its OLD name as if the name was never renamed.

Some kind of GUID/ID history mapping?

**Comment by suyash691** [comment]
Hey, can you provide me with the published trx(old and new ideally)?

**Comment by suyash691** [comment]
Hi, were you able to try get the trx's for the runs which are exhibiting this issue?
