### ISSUE TITLE
XML Variable Substitution removes comments

### ISSUE THREAD

**Issue by abalaranjan** [microsoft/azure-pipelines-tasks#11188]
<appSettings>
    <add key="VariableA" value="0" /> 
  </appSettings>

<appSettings>
    <add key="SendBankRejectEmailsToCustomers" value="new value"/>    
  </appSettings>

File Transform task after doing an xml variable substitution it removes the comments from the original file, is there a way to escape this?

**Comment by SumiranAgg** [comment]
Thanks for reporting. Fixed as per attached PR #11224

**Comment by SumiranAgg** [comment]
Thanks for bringing this up. We are working on the fix. Will update the thread once fix is available.
