### ISSUE TITLE
PowerShellOnTargetMachines fails with "Ampersand not allowed"

### ISSUE THREAD

**Issue by gschrader** [microsoft/azure-pipelines-tasks#11180]
The complete error message is, which is repeated until the task times out:

```
Ampersand not allowed. The & operator is reserved for future use; use "&" to pass ampersand as a string.
```

It doesn't seem to be related to the `InlineScript` as I've done just a simple `Write-Host` command just to test it.

It sounds similar to https://github.com/microsoft/azure-pipelines-tasks/issues/4310 but none of my variable names or values have an ampersand.

I've download the logs but it doesn't seem to log the command and I don't spot an ampersand.

My agent is running on Windows 2016 and the remote server is Windows 2008 running Powershell 2.0 which is old so maybe that is related to the problem.

I was able to start a remote session from the agent to the remote without an error.

I'm not sure where to go from here to figure out what my issue might be.

**Comment by gschrader** [comment]
I was able to workaround this issue using `Invoke-Command -ComputerName` on a regular powershell task. I'll leave this open though since it would be cleaner to use `PowerShellOnTargetMachines`.

**Comment by SumiranAgg** [comment]
Can you share debug logs for the task for further investigation.

**Comment by gschrader** [comment]
I've attached the task log file, if you need the agent and initialize log I'll probably have to go through and strip out any identifying information unless you have an email I can send it too.

[5_Test.log](https://github.com/microsoft/azure-pipelines-tasks/files/3560351/5_Test.log)

Thanks,
Glen

**Comment by SumiranAgg** [comment]
Can you set variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries@microsoft.com

**Comment by gschrader** [comment]
@SumiranAgg I just emailed the logs with the debug turned on.

**Comment by arjgupta** [comment]
Closing the issue. The task is trying to run a script remotely on a machine with powershell 2 installed. PowerShell 2 does not have the & operator which is used by the task to execute script on the remote machine. PowerShell 2 is marked deprecated. The recommendation is to move to PowerShell 3 or later or try to run custom PowerShell script and use the Invoke-Command cmdlet.
