### ISSUE TITLE
Delay Task fails without reason : Wait time 60m

### ISSUE THREAD

**Issue by sridharvenkat** [microsoft/azure-pipelines-tasks#11201]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DelayV1

## Environment
- Server - Azure Pipelines, 'windows-lastest'
- Account - Microsoft, Project - Hits Team, Repo - HITS, Pipeline - Nightly Merge - Master to Deliverables
- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name: Default Queue

## Issue Description

I am facing a error in delay task if the wait time is 60mins. This is in pipelines. The log doesn't provide what's the source of error. But if the wait time is reduced to 2mins the same task completes successfully.

**Delay Task Error with 60mins**  
![image](https://user-images.githubusercontent.com/10329929/63614927-08cf9200-c599-11e9-80cf-ab7c34c03a1a.png)

**Delay task success with 2mins**  
![image](https://user-images.githubusercontent.com/10329929/63615216-a4610280-c599-11e9-8ef9-5379b6eef74a.png)

### Task logs
Chapter 2 : The wait

Job information
Started: Today at 10:02 AM
Duration: 1h 0m 0s

Job preparation parameters
ContinueOnError: False
TimeoutInMinutes: 60
CancelTimeoutInMinutes: 65
Expand:
  MaxConcurrency: 0

Wait for 60 mins for the merge to verify policies

**Comment by ArieHein** [comment]
Default of the pipeline is usually 60min of execution. In the Build definition, at the Options tab, on the right side look for Build Job Timeout in minutes.

for testing it, since your first job is about 2m20 sec, put a delay of 58 min, it will fail in the delay as the total execution time is over 60min. Put a delay of 56 min it will work correctly (assuming step 1 doesn't take longer of course).

**Comment by sridharvenkat** [comment]
@ArieHein , Got it, Yes it does work with < 60 mins timeout. 2 things, 

- I am using a Yaml based pipeline so the 'Options' was not available. Also I don't see a timeout option on the entire pipeline, schema reference - [https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline), Is it possible to configure the timeout for whole pipeline?

- 2ndly, There was no proper error message saying the build timedout. Can it be improved?

**Comment by vtbassmatt** [comment]
See the entry [timeoutInMinutes](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job).
