### ISSUE TITLE
DockerRegistry name is converted to astericks

### ISSUE THREAD

**Issue by QuantumFractal** [microsoft/azure-pipelines-tasks#11206]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: docker

## Environment
- Server - Azure Pipelines
- Agent - Hosted
   
## Issue Description

Whenever I submit my pipeline, my private docker registry is being converted into "***" and breaking my builds.

### Task logs

```Generating script.
Script contents:
docker tag moll.dev:47 "blahblahblah.azurecr.io/moll.dev/pipeline"
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/fdb979e8-fc5f-4662-95e9-c0e6ff239597.sh
##[section]Finishing: Tag Image
```

A random string works fine. Whenever I use the string "molldevhub" it gets converted to stars. This should not be happening.

```Script contents:
docker tag moll.dev:47 "***"
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/c4b711c8-3396-46f8-a167-c68c6f392f6c.sh

```

Any ideas?

**Comment by ds-ms** [comment]
The `***` which you're seeing in the logs is just our masking logic of your sensitive information in logs. 
Is `molldevhub` declared as a secret anywhere? Or is `molldevhub.azurecr.io` your loginServer in the docker registry endpoint you're using? 

How is it breaking your builds btw? What's the error that you're seeing?

**Comment by ds-ms** [comment]
@QuantumFractal The redaction is most likely not causing any issue. Could you provide the debug logs? This would help us understand your problem better. 

@kevinhillinger This is not a newly introduced feature, it has been in the system for a long time. Also, it redacts only the secrets from your logs. I'm not sure if you can opt-out of the redaction.

**Comment by ds-ms** [comment]
Closing this issue; feel free to re-open it if you're still facing an issue. 
But, it's definitely not failing because of the redaction in the logs.
