### ISSUE TITLE
[AppCenterTest Task] Using the wrong command to run XCUITest against AppCenter

### ISSUE THREAD

**Issue by szuchunhung** [microsoft/azure-pipelines-tasks#11217]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AppCenterTest

## Environment
- Server - Azure Pipelines or TFS on-premises?    Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/geaviationdigital-dss/FlightPulse/_build/results?buildId=4736

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
2.155.1

## Issue Description

We're trying to setup an AppCenterTest task to execute tests against our iOS build as part of the pipeline. Locally, we've successfully gotten the AppCenter tests to work by following the documentation here: https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/xcuitest
When trying to use the AppCenterTask to run the same test, we realized the appcenter commands are done differently. Rather than specifying xcuitest and the --build-dir, the task references a manifest file and --app-path, but not --build-dir.
This is resulting in a error:

Validating application file... failed.
Error: EISDIR: illegal operation on a directory, read

[logs_4736.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3542026/logs_4736.zip)

**Comment by apacha** [comment]
Is anyone actually using AppCenter to run the XCode UI test and for deployment? If so, can anyone provide a complete YAML file. The documentation does not help at all.
