### ISSUE TITLE
Support glob for path

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azure-pipelines-tasks#11219]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: CacheBeta

## Environment
Azure pipelines 
https://dev.azure.com/ms/azuredatastudio/_build?definitionId=4&_a=summary
Account: ms
Project: azuredatatudio
Build definition: Microsoft.azuredatastudio

Host Agent Ubuntu 16.04

## Issue Description

Being able to pass glob file patterns as a path is useful for large projects with multiple cacheable directories.

**Comment by Phlogi** [comment]
Yes, especially to ignore certain directories. As of now permission denied errors cause the cache to not be saved.

**Comment by herenhuang** [comment]
Might be a good candidate for any community contributions? We (on the Artifacts team) are also now tracking this ask. Thanks for the feedback! :)

**Comment by GoMino** [comment]
+1 would be really usefull for mono repos which will have dependencies at the root level as well as at the sub repo levels as well (as referenced in https://github.com/microsoft/azure-pipelines-tasks/issues/11692)

**Comment by samuelkoppes** [comment]
Artifacts supports glob patterns in paths. https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

**Comment by planetmarshall** [comment]
The PR that implemented this feature was reverted. Can this issue be reopened?

**Comment by samskiter** [comment]
@mjroghelia  I noticed you had to revert the PR - is there any chance this could be revisited? @ethanis I believe you authored that PR...

**Comment by shahzadmajeed** [comment]
Hi,

Any status on this please? Is there currently a way to specify multiple directories to cache?

Thanks

**Comment by dinilimento** [comment]
Hi,

Would be great if you could implement this feature!

**Comment by kyle-rader-msft** [comment]
@johnterickson is this issue dead? I'm running into a need for this because I don't want to manage 2 cache tasks for the Rust Toolchain, which installs to 2 different temp directories. They should be under the same cache key and restored together.

**Comment by johnterickson** [comment]
Hey @kyle-rader-msft - "dead" is pretty final.   That said, I would say nobody is working on it.  There was a PR to support this (https://github.com/microsoft/azure-pipelines-agent/pull/2834) but it got reverted (https://github.com/microsoft/azure-pipelines-agent/pull/3163) and I don't think anyone has championed it since then.  The revert PR mentions some bugs around edge cases and IIRC it forgot to salt the fingerprint when it changed the fingerprint format.  If someone wants to champion this, I'm happy to re-open.
