### ISSUE TITLE
SqlAzureDacpacDeployment@1 : Cannot bind argument to parameter 'connectedServiceName' 

### ISSUE THREAD

**Issue by mikebollanddp** [microsoft/azure-pipelines-tasks#11227]
Providing all required fields for connection string

```# Deploys SQL commands
- task: SqlAzureDacpacDeployment@1
  displayName: 'Deploy SQL Scripts'
  inputs:
    authenticationType: 'connectionString'
    connectionString: 'myconnectionstring;'
    deployType: 'sqlTask'
    sqlFile: 'MyDatabase/dbo/test.sql'
```

throws

```
##[section]Starting: Deploy SQL Scripts
==============================================================================
Task         : Azure SQL Database deployment
Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
Version      : 1.156.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment
==============================================================================
##[error]Cannot bind argument to parameter 'connectedServiceName' because it is an empty string.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
##[section]Finishing: Deploy SQL Scripts
```
I believe the documentation is invalid or something is not working

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops

**Comment by SumiranAgg** [comment]
I agree the documentation is a bit confusing.

You actually have to provide "azureSubscription" or" azureClassicSubscription" so that we can talk to azure service.

@N-Usha Can you add a comment in YAML snippet calling out one ofthese inputs is mandatory.

**Comment by N-Usha** [comment]
Documentation already mentions that the fields are mandatory/Required:
- task: SqlAzureDacpacDeployment@1
  inputs:
    #azureConnectionType: 'ConnectedServiceNameARM' # Optional. Options: connectedServiceName, connectedServiceNameARM
    #azureClassicSubscription: # Required when azureConnectionType == ConnectedServiceName
    #azureSubscription: # Required when azureConnectionType == ConnectedServiceNameARM

@mikebollanddp  - Can you please confirm where did you get the YAML snippet that you pasted above?

**Comment by niadak** [comment]
Closing the issue as the Documentation is already updated

**Comment by dvasdekis** [comment]
If I click 'Create Pipeline' in DevOps, and use 'Azure SQL Database Deployment' template with the 'Active Directory - Integrated' authentication type, I get the below template which creates this issue:
```
- task: SqlAzureDacpacDeployment@1
  inputs:
    AuthenticationType: 'aadAuthenticationIntegrated'
    ServerName: 'synapse_od'
    DatabaseName: 'synapse_od'
    deployType: 'SqlTask'
    SqlFile: 'asd.sql'
    IpDetectionMethod: 'AutoDetect'
```
As you can see there's no #azureConnectionType:, #azureClassicSubscription or #azureSubscription entries
