### ISSUE TITLE
Add predefined variable for pull request source and target branch name

### ISSUE THREAD

**Issue by feroz-ahmmed** [microsoft/azure-pipelines-tasks#11225]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

There are already `System.PullRequest.SourceBranch` and `System.PullRequest.TargetBranch` available. Similar to `Build.SourceBranchName`, I also expect `System.PullRequest.SourceBranchName` and `System.PullRequest.TargetBranchName`.

**Comment by damccorm** [comment]
Hi, this repo is for tasks issues - would you mind logging your issue here where it can get picked up by the appropriate team? https://developercommunity.visualstudio.com/spaces/21/index.html
