### ISSUE TITLE
Feature request: Please add support powershell scripting in az cli task.

### ISSUE THREAD

**Issue by rerime** [microsoft/azure-pipelines-tasks#11240]
## Note  
Feature request: Please add support powershell scripting in az cli task.
It very usefull for some advanced logic.

For a list:  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV1

**Comment by issacnitin** [comment]
@rerime Thanks for the suggestion! We'll discuss this internally and will let you know ASAP

**Comment by bishal-pdMSFT** [comment]
@rerime this is already planned to be taken up soon.

**Comment by bishal-pdMSFT** [comment]
This is completed. We have released a new major version of Azure CLI task which can execute PS / PS Core script.
