### ISSUE TITLE
Gulp@1 doesn't respect projects in subfolders

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/azure-pipelines-tasks#11246]
## Required Information
**Type**: Bug 
**Enter Task Name**: Gulp@1 & Gulp@0

## Environment
- Azure Pipelines?
  - **account**: aconn
  - **project**: Voitanos.azure-pipelines-spfx-templates
- Agent - Hosted & Private: _(both)_
    - **Hosted**: Hosted Ubuntu 1604 / `ubuntu-latest`
    - **Private**: Ubuntu 16.04

## Issue Description

I'm creating reusable templates for a specific project type (SharePoint Framework). Most consumers of the templates ([such as this test project](https://github.com/Voitanos/azure-pipelines-spfx-templates-test)) will have their projects in the root repo. However, I've added another [project to my repo that contains the templates](https://github.com/Voitanos/azure-pipelines-spfx-templates). To support both scenarios, I support the consumer of the template to specify the `working_directory` as a path to the subfolder of the project if it is not in the root of the repo.

Task `Gulp@1` **does not** respect the `workingDirectory` or `gulpFile` input parameters to set the path to a subfolder in the repo; it always looks for the `gulpfile.js` in the root of the current repo.

Task `Gulp@0` **does** respect the `gulpFile` input parameter to set the path to a subfolder in the repo (_IOW, this works & is what I'm doing now_), but `workingDirectory` is not respected.

> See this thread in the DevOps forum where someone from MSFT confirms the issue: https://developercommunity.visualstudio.com/content/problem/716337/unable-to-set-workingdirectory-on-gulp.html

If you look at [the highlighted code in this specific commit](https://github.com/Voitanos/azure-pipelines-spfx-templates/blob/571ca8b9eab06c2ba086bc23a181130eb4fbd119/jobs/build.yml#L17-L30), you'll see two tasks: `script` & `Gulp@0`. This commit is working, but it shows how the `workingDirectory` folder on the `script` task is working as expected, CD'ing into the subfolder before executing the command. However, I can't do the same thing with `Gulp@*`, rather I have to explicitly set the path to the `gulpfile.js`

From my POV, on the `Gulp@1` task, the `workingDirectory` input property should cause the task to CD into the folder specified before running `gulp` or `gulpjs`, similar to how the `ShellScript` task works. As it's working now, `workingDirectory` is ignored in both v0 & v1 of the task & setting the `gulpFile` input property on v1 does not work. Further, the use of `workingDirectory` is not consistent in the `Gulp@*` tasks compared to other tasks.

**Comment by moswald** [comment]
@andrewconnell I'm not seeing what you're seeing, but I don't want to toss this back as "can't repro". Can you provide logs for a failing build? Run with system diagnostics enabled. Thanks!

**Comment by andrewconnell** [comment]
I can still repro it... did you notice the link to the public forum post where someone from MSFT was also able to repro it?

Here's a project that shows it in action: https://github.com/Voitanos/azure-pipelines-spfx-templates. It is a public repo that contains job templates for a specific type of dev. The sample in the project demonstrates the issue.

### Working sample using "Gulp@0" + workaround
The project within **./sample** contains the pipeline... the **master** branch uses the task **Gulp@0** without the `workingDirectory` property and building the path to the **gulpfile.js** using the `gulpFile` property as suggested for a workaround in the public forum referenced in my OP. 

You can see a working build from the **master** branch: https://dev.azure.com/aconn/Azure%20Pipelines%20SPFx%20Templates/_build/results?buildId=501&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76

### Repro sample using "Gulp@1" that doesn't work using the `workingDirectory` property
The same exact project, except it uses **Gulp@1** & the `workingDirectory` property. This fails as it doesn't incorporate the working directory. You'll find this in the branch **repro-gulp-task-build**. [This commit](https://github.com/Voitanos/azure-pipelines-spfx-templates/commit/7f23e9b23ae44829ec700a481654647d2a0b5583) shows what I changed from the working sample above.

You can see a breaking build from the **repro-gulp-task-build** branch (this has the diagnostic logging turned on... the immediate preceeding pipeline run is without diag logging turned on):  https://dev.azure.com/aconn/Azure%20Pipelines%20SPFx%20Templates/_build/results?buildId=568&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=412f6483-90be-5dc3-b7d8-26e9cdfda42a

**Comment by moswald** [comment]
If you look at the task source, you'll see that we [check for the existence of the gulpfile](https://github.com/microsoft/azure-pipelines-tasks/blob/7ae13519490aed705d3be3c51bb50588fb55c775/Tasks/GulpV1/gulptask.ts#L6) before we [set the current working directory](https://github.com/microsoft/azure-pipelines-tasks/blob/7ae13519490aed705d3be3c51bb50588fb55c775/Tasks/GulpV1/gulptask.ts#L10) based on the input parameter. The difference between your two pipelines is that you're [setting a full path to the gulpfile](https://github.com/Voitanos/azure-pipelines-spfx-templates/blob/191ca215409cf9a5a0f170ce66f99dacd1f6fbc0/jobs/build.yml#L41) for your `Gulp@0` pipeline, but [only relying on the working directory](https://github.com/Voitanos/azure-pipelines-spfx-templates/blob/d555f1deae6db54d356203db6bbd643be09976c5/jobs/build.yml#L41) in the `Gulp@1` pipeline. If you present the same options to the `Gulp@0` task, it will fail in the same way.

Technically this is a breaking change, but `Gulp@1` is still in preview and it's probably ok for me to fix this so that it sets the working folder first. I will talk to the primary maintainer on the Tasks repo and get back to you. --Also, while I'm here, it's annoying that the `gulpFile` input is "required" but we also provide a default value. Those are conflicting specifications in my view, and I'll fix that at the same time.

**Comment by andrewconnell** [comment]
Makes sense... thanks for looking into it. 

FWIW, when setting the `workingDirectory` parameter, I would expect the task would essentially  change the PWD => that folder before continuing to look for the **gulpfile.js**, similar to what the **Script** tag does (ex: [how I'm using it](https://github.com/Voitanos/azure-pipelines-spfx-templates/blob/191ca215409cf9a5a0f170ce66f99dacd1f6fbc0/jobs/build.yml#L23-L34))

Agreed on the requested part about the **gulpFile** parameter. A default value (where I suspect 99.999% of all projects use the name **gulpfile.js**) should make it optional.

**Comment by moswald** [comment]
No problem! Agreed, I'm going to change Gulp@1 to set the PWD before searching for the gulpfile. The fix will go out with our next round of deployments, which is about three weeks out.

**Comment by andrewconnell** [comment]
![](https://media.giphy.com/media/26ufq9mryvc5HI27m/giphy.gif)

**Comment by moswald** [comment]
Fixed with #11361.
