### ISSUE TITLE
[DotNetCoreCLIV2] Add vstest action to .NET Core CLI task

### ISSUE THREAD

**Issue by NenoLoje** [microsoft/azure-pipelines-tasks#11245]
The .NET Core CLI task supports a range of commands:

``` YAML
#command: 'build' # Options: build, push, pack, publish, restore, run, test, custom
```

... but not "**vstest**".

However, "vstest" is pretty common and vital these days:

* Using action="custom" works, but you need to know the arguments to create a .TRX files.
* It feels like a (dirty) workaround, as you need to take care yourself about storing and publishing the test results via a .TRX file
* Using the VSTest task as an alternative is not an option when running on a non-windows OS.

So: please add support for "**dotnet vstest**" like a first-class citizen (similar to "**dotnet test**").

Thanks,
--Neno

**Comment by issacnitin** [comment]
@NenoLoje Thanks for the suggestion! We'll discuss this internally and will let you know ASAP

**Comment by bishal-pdMSFT** [comment]
@NenoLoje couple of questions:
1. There is already a talk about [merging](https://github.com/microsoft/azure-pipelines-tasks/issues/11245) `dotnet test` and `dotnet vstest` commands.
2. VSTest task is an alternative on windows. Do folks really use `dotnet vstest` on non-windows?

**Comment by NenoLoje** [comment]
Hi @bishal-pdMSFT !

No idea how many people do actually use it - I would guess that it's not many. But the reasons are:
* It's not easily discoverable.
* They end up just using Windows machines and the VS Task because of that discoverability issue.

In the case here, I'd like to run integration and availability tests from a docker container under Linux and all I have is the binaries (so dotnet test) does not work.

--Neno

**Comment by NenoLoje** [comment]
@bishal-pdMSFT Any update on this one?
Will we ever see a built-in task that can run .NET Core tests under Linux (that knows how to publish results into Azure DevOps)? Thanks!

**Comment by bishal-pdMSFT** [comment]
Adding @phanikmmsft as he owns test related actions in the task and would have idea about what is the right approach for publishing vstest result.

**Comment by NenoLoje** [comment]
Ping - @phanikmmsft or @bishal-pdMSFT
