### ISSUE TITLE
Either make the Publish Code Coverage Results task error when added to a release or make it supported in a release

### ISSUE THREAD

**Issue by dparvin** [microsoft/azure-pipelines-tasks#11242]
## Required Information

Type: Feature (maybe Bug)

Enter Task Name: Publish Code Coverage Results

## Environment
I am using Azure Devops Server 2019 and I have agents installed locally all on Windows 10 (1903) that do the work.  My agents are all version 2.144.2.

## Issue Description

After spending days getting to the point where I could get a release pipeline to get the code coverage ready to publish to DevOps, I finally get an error from the task saying it does not work from a release pipeline.

I am requesting that you make the task so it will give an error when added to a release pipeline, or make it work in a release pipeline.  If it had told me that it would not work in release when I first added it to the pipeline, I would not have wasted all of the time it took to get to the point where it would tell me that it does not work there.

### Task logs

[tasklog_7.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3552778/tasklog_7.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

2019-08-28T19:39:29.4148865Z ##[debug]Reading XML file: C:\agent\_work\r4\a/drop/Build/Debug\Cobertura\Cobertura.xml
2019-08-28T19:39:29.7494218Z ##[debug]Converting XML file to JSON
2019-08-28T19:39:58.7554597Z ##[debug]Found 1 result(s) matching pattern: C:\agent\_work\r4\a\drop\Build\Debug\TestResults\output.xml
2019-08-28T19:39:58.7584842Z ##[error]codecoverage commands are not supported for Release flow. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)

**Comment by jattasNI** [comment]
This bit me too. Does anyone know if this is fixed in YAML-based Release pipelines? My current setup is the older configuration-based approach but if this works in YAML pipelines then it might spur me to switch.

**Comment by ankit-arora12** [comment]
Sorry for the inconvenience. We don't have any plans to support it in the release pipeline as of now. Have mentioned this in documentation so that it does not come as a surprise. Documentation will be released in a few days.
