### ISSUE TITLE
Invoke REST API success criteria expression not working on array result

### ISSUE THREAD

**Issue by antpuleo2586** [microsoft/azure-pipelines-tasks#11251]
**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: Invoke REST API  

## Environment
- Server - Azure Pipelines or TFS on-premises?
       
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/CorResilience/CorResilience/_build/results?buildId=869

## Issue Description

I'm trying to create an API call which checks the status in App Center of the build for a particular commit sha, parses the json and determine pass/fail based on whether the App Center app build succeeded or failed for that commit.

However, I cannot get the json path expression to evaluate; it always fails.

I'm doing this blindly as I can't see the output of my expressions; I just get whether it passed or failed in the logs.

The expression is:
```
eq(jsonpath('$[*].lastBuild[?(@.sourceVersion==variables[''System.PullRequest.SourceCommitId''])].result')[0], 'succeeded')
```

And the json looks like this:
```
[
  {
    "branch": {
      "name": "master",
      "commit": {
        "sha": "632c20fbca937970f38e0a07a65824ebdcf335be"
      }
    },
    "configured": true,
    "lastBuild": {
      "id": 30,
      "buildNumber": "30",
      "queueTime": "2019-08-28T14:26:12.3239973Z",
      "startTime": "2019-08-28T14:28:31.3509636Z",
      "finishTime": "2019-08-28T14:53:15.7195273Z",
      "lastChangedDate": "2019-08-28T14:53:16.123Z",
      "status": "completed",
      "result": "succeeded",
      "reason": "individualCI",
      "sourceBranch": "master",
      "sourceVersion": "632c20fbca937970f38e0a07a65824ebdcf335be",
      "tags": [
        "normal",
        "javascript",
        "tests",
        "xcode",
        "continuous",
        "testcloud",
        "distribution",
        "signed"
      ],
      "properties": {}
    },
    "trigger": "continuous"
  }
]
```

I have tried hardcoding in the commit sha:

```
eq(jsonpath('$[*].lastBuild[?(@.sourceVersion==''632c20fbca937970f38e0a07a65824ebdcf335be'')].result')[0], 'succeeded')
```
but it just won't evaluate to true, even though this looks like a valid json path, according to a stackoverflow answer by @jessehouwing:

https://stackoverflow.com/a/49614722/5608321

Can you please help?

### Task logs

[log_6_869.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3559718/log_6_869.zip)

**Comment by antpuleo2586** [comment]
Ok so I figured it out, painfully 😅 

There were two things wrong, the variable access and the json path access for arrays.

This works:

```
eq(jsonpath('$[?(@.lastBuild.sourceVersion==''$(System.PullRequest.SourceCommitId)'')].lastBuild.result')[0], 'succeeded')
```

Here, I have to actually query the root array, rather than use an `*`. Also, variable access works using the `$(Variable)` syntax.

It would be good if there was a little more in terms of documentation around this, as I spent more than a day figuring this out.

An array example like mine might be good to help others in a similar situation.


Thanks!

**Comment by vithati** [comment]
https://jessehouwing.net/vsts-release-create-complex-release-gate/ this tool help to validate expression. https://goessner.net/articles/JsonPath/index.html#e2 and https://jsonpath.com helps json expression format.

**Comment by antpuleo2586** [comment]
@vithati I already used the jsonpath.com site to evaluate, but syntax which is valid there didn't work on in the success criteria in azure, such as `$[*][.....]`.

I also already tried the tool you mentioned but it throws an `Object reference not set to an instance of an object.` error when the root is an array.

**Comment by jessehouwing** [comment]
I've since updated te gate Condition editor and it won't throw. But your expression doesn't seem to work correctly.
