### ISSUE TITLE
Enable download of artifact to custom directory

### ISSUE THREAD

**Issue by giggio** [microsoft/azure-pipelines-tasks#11268]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: `DownloadPipelineArtifactV2`

## Issue Description

Enable the `download` keyword from the yaml build to select a custom directory. In other words, expose the `targetPath` property of the `DownloadPipelineArtifactV2` on the `download` keyword.

This is extremelly important, as right now the default location is `Pipeline.Workspace`, which means that by default the downloaded artifacts survive between builds if you use a self hosted agent, which is really bad, and what's worse: you can't clean it up before the download happens.

**Comment by giggio** [comment]
Right now there isn't a good workaround, because of bug #11267 which affects `DownloadPipelineArtifactV2`.

**Comment by jahsu-MSFT** [comment]
@giggio If I'm understanding correctly, for "download" keyword, you should be able to specify artifact name, patterns, and target path. 

- download: string - the pipeline to download from (`current` or a resource id) or the word `none`
  artifact: string - the specific artifact; optional unless `path` specified
  patterns: string - minimatch patterns of files to grab from the artifact(s); defaults to **/*
  path: string - the destination path for where to download the artifact(s)

**Comment by giggio** [comment]
@jahsu-MSFT The path property is missing on Microsoft docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download

Which one is correct, the .md from the azure-pipelines-yaml repo, or the docs from Microsoft?

**Comment by jahsu-MSFT** [comment]
@giggio I see. The yaml doc is actually a design doc and currently the path input field is not implemented/exposed in the download yaml schema. We will be working on fixing this as soon as possible. Thanks,

**Comment by fadnavistanmay** [comment]
Adding @kasubram . It looks like we won't be adding the path variable to download keyword anytime soon because of the difference in behavior between download BA and download PA task.

**Comment by kernelcoredump** [comment]
I think this should be re-opened.  Surely the design docs of exposing the _path_ property on the download keyword/shortcut has not yet been (will never be?) implemented.  What is that behavior difference between BA and PA tasks that's preventing exposing this property in the keyword/shortcut?

What's more is that in _DownloadPipelineArtifactV1_, the default value is _$(System.ArtifactsDirectory)_
https://github.com/microsoft/azure-pipelines-tasks/blob/e2ae64da4dae95afec53e5a0c09ae14b284f7c89/Tasks/DownloadPipelineArtifactV1/task.json#L143
then in _DownloadPipelineArtifactV2_, it got switched to _$(Pipeline.Workspace)_
https://github.com/microsoft/azure-pipelines-tasks/blob/e2ae64da4dae95afec53e5a0c09ae14b284f7c89/Tasks/DownloadPipelineArtifactV2/task.json#L180

Or is there a mechanism to select which version of the task that a keyword/shortcut points to?

**Comment by VinceGall** [comment]
Interested in this feature too. In my pipeline I have a bunch of pipelines under resources, and they need to be placed in specific directories when downloaded.
As a work around I have a bash task to "manually" move the artifacts to the target directory. It works , but it's just bad code
