### ISSUE TITLE
The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1

### ISSUE THREAD

**Issue by ashutak84** [microsoft/azure-pipelines-tasks#11277]
I keep getting above error, i attaching the error logs and the YAML of my build definition.
Following are the set of tasks, 

[VSOErrorLog.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3573603/VSOErrorLog.zip)

![image](https://user-images.githubusercontent.com/349954/64241873-264e1580-cf22-11e9-8392-00a5f2e0b97c.png)

**Comment by issacnitin** [comment]
@ashutak84 
There are two scenarios in which this could happen:

1. You have "Feeds I select here" and do not have "Use packages from NuGet.org" ticked
2. You have "Feeds in my nuget.config" selected and your nuget.config file doesn't have a repository with package Microsoft.AspNetCore.AzureKeyVault.HostingStartup
![feeds](https://user-images.githubusercontent.com/4218887/64333229-bf992c80-cff3-11e9-8b2f-f72edc5abf04.PNG)


If you are in option 1, 
You should tick the option "Use packages from Nuget.org" in dotnet restore task.

In case of 2,
There seems to be an issue with https://ms-nuget.cloudapp.net/api/v2 repository in your nuget.config. You could try removing that and adding
`<add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />`
to your nuget.config instead, as that repository does have the package you need to restore. 


Please let us know if this resolved your issue.

Thanks,
Nitin

**Comment by issacnitin** [comment]
@ashutak84 Hope this resolved your issue. We're closing the ticket, please feel free to reopen if you face any issues.

**Comment by ashutak84** [comment]
Thanks, this has solved the problem, sorry for the late reply.
