### ISSUE TITLE
Version controlling Azure DevOps Release pipeline

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11272]
Hi,

I want to know how to version control my release pipeline in Azure DevOps, perhaps something similar to the build definitions which are version controlled via the .yml file.

Thanks,
A

**Comment by RoopeshNair** [comment]
yml file supports release/cd concepts as well. You can define the CD stages in the yml workflow.

**Comment by saxenark** [comment]
Can you please share the link to the documentation and how to create the release/cd pipeline in yml?

**Comment by RoopeshNair** [comment]
https://azure.microsoft.com/en-in/resources/videos/build-2019-yaml-release-pipelines-in-azure-devops/

**Comment by RoopeshNair** [comment]
Here is the schema reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

**Comment by ArieHein** [comment]
Any changes you do to a build / release definitions is already source controlled, both have a history tab that allows you to see differences and revert. If you want it yaml based then only fr build. Release doesn't support it unless its for K8S.

**Comment by RoopeshNair** [comment]
@ArieHein - YAML is for both Build and Release. It is not limited to K8S. The YAML schema supports all constructs that are required for Release as well. You can do multiple stages, fan-out to parallel stages, fan-in to a common stage, you can define approvals using environments. Use any deployment steps in it. The YAML pipeline can be defined only for CI or only for CD or both.

**Comment by saxenark** [comment]
@RoopeshNair : Does the release definition in yaml now support self hosted agents? I was told sometime back that it does not but unfortunately i can't find out that ticket. Please confirm

**Comment by RoopeshNair** [comment]
@saxenark  - YAML pipelines supports Microsoft hosted as well as self-hosted agents. To use hosted you  specify the `vmImage`, and for self-hosted you specify the pool name. Here is the [schema and examples](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#pool)

**Comment by ArieHein** [comment]
@RoopeshNair It doesn't support "Release" by it self. it supports a Build YAML  file that has release baked in the same file.
I can not create a yaml file under releases and point it to a potential release.yaml file.
correct me if I'm wrong ?
The can you actually say Release is supported ? I mean even without yaml file, I could have a build definition today in the UI that also does ALL the release functionality and deploy it to multiple environments, just have each env on a different job agent as if it was "stages".

**Comment by saxenark** [comment]
@RoopeshNair, @ArieHein 

All I want is to have my Release definitions in the yaml build for the build pipeline, so that I don't have to create Release definitions elsewhere and my yaml has steps from checkout all the way upto to deployment. Is this support available? If yes, is there a document that I can refer?

**Comment by RoopeshNair** [comment]
yes, you can create multiple stages in a single YAML file. One of the stage could build and rest can deploy to various environments. Here is the schema for [YAML pipeines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema). Here are some [samples](https://github.com/RoopeshNair/Sample-Yaml-Pipelines) YAMLs for multi-stage pipelines (CI + CD)

**Comment by hbensalem** [comment]
Is there any intention to add yaml support for release pipelines?

**Comment by ArieHein** [comment]
Not sure i follow. In classic you can have a build and release pipelines. In YAML is just called multi-stage pipeline where one file can do both or just 1 or the other but the OP was about how to version the pipeline itself, which if you're using YAML you already have as its stored in the repo thus enjoys history tracking and pull request process like all rest of the code does.

**Comment by Wind010** [comment]
You could export the release definition as json using the REST API and store it in source control.

https://learn.microsoft.com/en-us/rest/api/azure/devops/release/definitions/get?view=azure-devops-rest-6.0

The definitions could be recreated from the create API.
