### ISSUE TITLE
AzureCloudDeploy: Azure Deployment not found, but then cannot be created

### ISSUE THREAD

**Issue by christineLDavis** [microsoft/azure-pipelines-tasks#11289]
## Required Information

*Type*: Bug

**Enter Task Name**: Azure Cloud Deploy

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCloudPowerShellDeploymentV1

## Environment
- Server - Azure Pipelines
    - account name: macydrive
    - team project name: arttoremember_services
    - build definition: arttoremember-service-test cloud service
    - build numbers: 20190904.6

- Agent - Hosted
    - agent spec: vs2017-win2016
    - agent pool: Azure Pipelines

## Issue Description
When running the Azure Cloud Deploy task in Azure DevOps, there seems to be an issue with retrieving an existing deployment slot in a classic Azure Cloud Service. Thus, the task is only runnable the first time, when deploying a new slot. Subsequent executions throw the error: 
ConflictError: The specified deployment slot Production is occupied.

I believe the issue to be with line #104 in the powershell file:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCloudPowerShellDeploymentV1/Publish-AzureCloudDeployment.ps1

Based on the logs, it appears that $azureDeployment is coming back as null and always attempting to call New-AzureDeployment as opposed to Set-AzureDeployment.

Is it possible that there's something wrong with my config?
If it matters, the task did successfully create the deployment the first time, as you can see from the following screenshot:

![image](https://user-images.githubusercontent.com/49955268/64293951-b6e51f80-cf3b-11e9-959c-81569f52cd76.png)

### Task logs

[log_12_2089.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3576592/log_12_2089.zip)

### Error logs

[error]ConflictError: The specified deployment slot Production is occupied.
OperationID : '7ee752c0806c09e280f7fe3d7222f334'

**Comment by Ajay-MS** [comment]
As error mentioned that a deployment already exists then `Get-AzureDeployment` cmdlet shouldn't have returned `null`.

Can you please try the following steps :

- Run `Get-AzureDeployment` cmdlet with verbose and debug arguments
```
Get-AzureDeployment -ServiceName arttoremember-service-test -Slot Production -verbose -debug
```

- Delete the service once and retry the deployment multiple time.

**Comment by 20shivangi** [comment]
@christineLDavis Have you tried the comment mentioned above ?

**Comment by 20shivangi** [comment]
Feel free to reopen the issue, if you face any.
