### ISSUE TITLE
xcode archive: physical platform is "Ineligible destination"

### ISSUE THREAD

**Issue by sbolotovms** [microsoft/azure-pipelines-tasks#11288]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: xcode archive

## Environment
- Server - Azure Pipelines
- Agent: Hosted MacOs 10.14

## Issue Description

For CI build we're trying to perform `xcode archive` on the project but it fails since archive requires target platform to be non-simulator.

### Task logs

[log_25_24753660.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3576191/log_25_24753660.zip)

## Troubleshooting
"Enable system diagnostics" fails xcode task (which is another bug probably).

### Error logs

```
Ineligible destinations for the "PhoneFactor" scheme:
	{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
	{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }```

**Comment by max-lobanov** [comment]
Hi, @sbolotovms ,

Based on your logs, you use incorrect destination parameter: `-destination platform=iOS,name=Generic iOS Device`.
The correct one should be `-destination generic/platform=iOS` according to [the article](https://www.mokacoding.com/blog/xcodebuild-destination-options/).

Could you please try to specify the following settings to XCode task:
![Screen Shot 2019-09-10 at 9 43 28 AM](https://user-images.githubusercontent.com/16715858/64590126-7c520b80-d3af-11e9-86ab-ee39d55f3e39.png)

**Comment by leantk** [comment]
Closing out since we haven't heard anything back but please reopen if you are still seeing the issue
