### ISSUE TITLE
usedotnet error self signed certificate in certificate chain

### ISSUE THREAD

**Issue by oleksabor** [microsoft/azure-pipelines-tasks#11282]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: usedotnet

## Environment
- Server - Azure Pipelines    
quipu-cwnet 
MessageWare
build definitionId=90

- Agent - Private: 
    Windows Server2008, agent 2.155.1 

## Issue Description

I'm running private build agent behind the company proxy. The problem is that usedotnet@2 task fails with SELF_SIGNED_CERT_IN_CHAIN error. I suppose it is because of proxy replaces https certificate.

Please help me to understand what url is used to download `release-index.json` file ? There is no url value in the task log unfortunately. I'd like to ask admins to add this url to the exception list on the proxy.

### Error logs

```
##[debug]agent.proxyusername=undefined
##[debug]agent.proxypassword=undefined
##[debug]agent.proxybypasslist=["dev\\.azure\\.com"]
##[debug]agent.proxybypasslist=["dev\\.azure\\.com"]
##[debug]AZURE_HTTP_USER_AGENT=VSTS_1fc97ab3-71db-45c5-8ec5-0312838bdb11_build_90_0
Tool to install: .NET Core sdk version 2.2.203.
##[debug]task result: Failed
##[error]Failed to download or parse release-index.json with error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}
##[debug]Processed: ##vso[task.issue type=error;]Failed to download or parse release-index.json with error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}
##[debug]Processed: ##vso[task.complete result=Failed;]Failed to download or parse release-index.json with error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}
```

Regards

**Comment by issacnitin** [comment]
@oleksabor 

The URL we use for getting release-index.json is https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json
You may add that url to exceptions in the proxy. 

Thanks,
Nitin
