### ISSUE TITLE
Bug in FTP task with umlauts (also Powershell-task)

### ISSUE THREAD

**Issue by Headley76** [microsoft/azure-pipelines-tasks#11290]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: FTP upload Task V2

## Environment
- TFS on-premises: Azure DevOps Server 2019 Update 1 

- Agent - Private:  
    - Agent Version: 2.153.1
    - OS: Windows Server 2016
  
## Issue Description
If filenames or Folders containing german Umlauts, the copied file- and Foldernames are corrupted.

A workarount by trying upload the files with the PowerShell-Task was not working too. The PowerShell also has problems with umlauts.
![Clipboard_2019-09-05_08-23-53](https://user-images.githubusercontent.com/49632973/64317211-4380f380-cfb7-11e9-9778-775b4a5b4a7a.jpg)

**Comment by damccorm** [comment]
@Headley76 could you try setting a pipeline variable `agent.retainDefaultEncoding` to true and see if that fixes it?

**Comment by Headley76** [comment]
I tried it, but not successfully :-(

**Comment by jpricket** [comment]
I think the problem is the default codepage used in windows. I found this stackoverflow article that describes the problem: https://stackoverflow.com/questions/58948011/powershell-and-german-umlauts-in-git-branch-names
I will see if I can find a workaround for FTP and then post it here.

**Comment by alex-peck** [comment]
In your task input, set `enableUtf8: true`
I was able to recreate this issue and fix it locally with that setting.
