### ISSUE TITLE
CacheBeta task: provide a logging-command-style for caching

### ISSUE THREAD

**Issue by stan-sz** [microsoft/azure-pipelines-tasks#11302]
**Question, Bug, or Feature?**  
*Type*: Feature
**Enter Task Name**: CacheBeta

## Environment
- Server - Azure Pipelines

## Issue Description

Provide a logging-command-style wraper for the CacheBeta task, similar to https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash

There are existing scripts to restore and build dependencies for different project kinds and the actual hash key is known/computed in the script. If CacheBeta is available as an echo command to the agent, it would allow for taking advantage of caching by adding a single line of echo in the script. Otherwise, some script refactoring is needed to expose the key.

Something like:

`echo "##vso[task.cachebeta key=$(Agent.OS)|$(Build.SourcesDirectory)/yarn.lock;]$(Pipeline.Workspace)/.cache/yarn"`

Uploading artifacts provides these wrappers already.

**Comment by johnterickson** [comment]
Interesting!

**Comment by herenhuang** [comment]
Tracking this on the Artifacts backlog now. :)

**Comment by samuelkoppes** [comment]
We are unable to support this due to the asynchronous architecture of "##" outputs and cache look-ups.
