### ISSUE TITLE
Deployment Group is fine but Available pools is empty

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11301]
Hi,

I don't understand what it means to have a valid deployment group with 1 online deployment agent, but at the same time the Available pools is empty

Healthy Deployment Group:
![image](https://user-images.githubusercontent.com/2850526/64425943-e4ac9e80-d0ca-11e9-952e-fca48c08e862.png)

Empty "Available Pools"
![image](https://user-images.githubusercontent.com/2850526/64425841-96979b00-d0ca-11e9-9d7e-69efa43e4fc2.png)

I think this might be related to my earlier reported issue https://github.com/microsoft/azure-pipelines-tasks/issues/11300 but not sure

Please help.

Thanks,

**Comment by ArieHein** [comment]
It means there is one server/agent connected to the deploy group so when you release using the deployment pool job, it will reach one server.

Creating Deployment groups doesn't mean they are available for projects, you need to assign the deployment group to a project to then be able to see it from inside a specific project

**Comment by saxenark** [comment]
@ArieHein The deployment group is certainly available to the project as the screen shot captures it from the context of the project. What am I missing?

**Comment by SumiranAgg** [comment]
@saxenark There are two concepts here:
Deployment pool is an account level object
Deployment group is a project level object

Also a deployment group needs to be backed up by a pool.

Now to answer your question, "Available pools" tab lists deployment pools that are available to be shared in the current project. Once shared, a deployment group will be created, and a corresponding entry appears under "groups" tab. If all pools to which the current project has access, have already been shared, the "Available pools" tab will have no entries.

I hoe this helps. Closing the issue. please feel free to re-open if you need more information.

**Comment by saxenark** [comment]
Ok. I understand.

I have a deployment group like so for my project

![image](https://user-images.githubusercontent.com/2850526/64605261-5d6c6d00-d3e1-11e9-8bce-70cbe823738c.png)

The corresponding pool (at org level is)

![image](https://user-images.githubusercontent.com/2850526/64605316-7aa13b80-d3e1-11e9-9571-803730249a03.png)

What is the name of the pool that I need to specify in my build pipeline for having my release & CD definitions in yaml. I have tried with NCAOnPremWin2KDeploymentPool, NCA-NCAOnPremWin2KDeploymentPool, but both don't seem to work.

**Comment by niadak** [comment]
Deployment Groups are not yet supported in Yaml pipeline. We are working on this and the scenario will be supported soon.
Currently Deployment Group is supported in classic Release definition with Deployment Group job where you can select deployment group.

![image](https://user-images.githubusercontent.com/11937515/64610660-65caa500-d3ed-11e9-942a-e4a6f997143e.png)
