### ISSUE TITLE
Azure Monitor Alerts Task is now Failing for creating alerts

### ISSUE THREAD

**Issue by blueelvis** [microsoft/azure-pipelines-tasks#11307]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?** 
*Type*: Bug

**Enter Task Name**: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureMonitorAlertsV0/task.json

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

## Issue Description

```
Failed to update Azure metric alert rule 'Availability_PartsUnlimited-CD' Resource. Error: BadRequest - As part of classic alerts retirement, starting Sep 01, 2019, no new classic alerts can be created except on a few metrics listed here https://aka.ms/classic-aler.... All classic alerts including the exceptions listed will stop working after June 2020. It is strongly recommended to use new metric alerts. See https://aka.ms/create-metri.... (CODE: 400)
```

Trying this as part of this lab - https://azuredevopslabs.com/labs/vstsextend/releasegates/

**Comment by SumiranAgg** [comment]
Thanks for reporting. We will update the APIs and hotfix ASAP.

**Comment by mkoertgen** [comment]
Thanks for reporting. Facing the same issue.

**Comment by Joseluismantilla** [comment]
Hello @SumiranAgg and guys, I am facing the same issue and I'd like to know when will be available.

> Error: Failed to update Azure metric alert rule 'Availability_Insights - Test' Resource. Error: BadRequest - As part of classic alerts retirement, starting Sep 01, 2019, no new classic alerts can be created except on a few metrics listed here https://aka.ms/classic-alerts-exceptions. All classic alerts including the exceptions listed will stop working after June 2020. It is strongly recommended to use new metric alerts. See https://aka.ms/create-metric-alerts.  (CODE: 400)

The Alert rules is a field required and whatever option shows the previous error, so I had to disable the Azure Monitor Alerts in the pipeline release.

**Comment by sinclr4** [comment]
We too have this issue, are pipelines are designed to not progress unless gates pass

**Comment by 20shivangi** [comment]
@blueelvis We have marked this task deprecated . Use az Cli task to configure new alerts.

**Comment by danishsh** [comment]
> @blueelvis We have marked this task deprecated . Use az Cli task to configure new alerts.

Can you keep the document updated pls ? 
https://azuredevopslabs.com/labs/vstsextend/releasegates/

**Comment by inatale** [comment]
> @blueelvis We have marked this task deprecated . Use az Cli task to configure new alerts.
Also it is possible to create an alert manually in the portal (just for brevity and demo purpose). In the Application Insight instance create an alert (Failed requests) FailedRequests_PartsUnlimited-CD and setup all required parameters (as in the guide).
PS. Don't forget to disable Configure Application Insight Alert task (because we did it previously in the portal).
