### ISSUE TITLE
What does this branch graph mean?

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11308]
Hi,

What is the best way to interpret this git branch history graph? I have tried it a few ways but given what I know about the branches I have, it does not make much sense to me.

![image](https://user-images.githubusercontent.com/2850526/64533212-a1ec0000-d330-11e9-90f7-f2d512a374d3.png)

Also, based on this knowledge I want to know what branch has all the changes and which branches I can delete safely.

PS: If this is not the right forum for this issue, where can I ask?

Thanks,

**Comment by damccorm** [comment]
Hi, sorry for the slow response - would you mind opening this issue in https://developercommunity.visualstudio.com/spaces/21/index.html - that's the best place to ask non-task specific questions about Azure Devops since this repo is dedicated mostly to tasks
