### ISSUE TITLE
Release Analytics tab is empty

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11313]
Hi,

I have a build pipeline for  my ASP.Net core application on Azure DevOps that does 

Stage 1
Build on ubuntu vm on cloud

Stage 2
Run unit tests on my on-prem hosted agent

After this, I get the Test and Coverage related tabs under the build summary for each build 

![image](https://user-images.githubusercontent.com/2850526/64604563-03b77300-d3e0-11e9-8057-387969dcb57e.png)

So far so good.

I am using the Release pane for my continuous deployment and release. Once again I use my on-prem hosted agent as part of my continuous deployment of the CI builds. 

Under the Analytics tab for the Releases, I see that Test Pass Rate is empty
![image](https://user-images.githubusercontent.com/2850526/64604986-d15a4580-d3e0-11e9-9440-e1f239de8d6c.png)

When I navigate within, I get the following message
![image](https://user-images.githubusercontent.com/2850526/64604535-f69a8400-d3df-11e9-96ef-77756a607b94.png)

![image](https://user-images.githubusercontent.com/2850526/64604731-4c6f2c00-d3e0-11e9-8ba4-9dc91880ce4f.png)

It is confusing to me. How do I publish my build test results as part of the deployment & release so that the test status reflects that.

Or 

Is the Test run in the Release workflow related to the deployment tests (as against unit tests which run at build time)?

**Comment by Additi** [comment]
You can use the test runner of your choice that supports the results format you require. Supported results formats include CTest, JUnit (including PHPUnit), NUnit 2, NUnit 3, Visual Studio Test (TRX), and xUnit 2.
Please refer to the documentation here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml

**Comment by saxenark** [comment]
@Additi I understand this but after having done all my tests and publishing the test & code coverage successfully as part of my build pipeline, it is little bit annoying to see the message "We didn't find any test results". 

So, I still don't understand this well. Why can't the test results from the particular build being deployed & released be displayed here in the Analytics tab. Of course, I am missing something, but what is it?

**Comment by saxenark** [comment]
@Additi : As I have mentioned, my CD & Release pipeline uses on-prem hosted agent. It appears to me that CD YAML does not yet support on-prem hosted agents. So, I guess I can't show the test results from build pipeline in the Release->Analytics tabs just yet. Am I correct?

**Comment by TroySchmidt** [comment]
@saxenark Test results in the build is separate from the release.  Only tests run during the release stage and jobs will be shown in the release section.  The only exception is if you are using multi stage YAML then you will see the whole thing build, release, and test results in one Pipeline definition.
