### ISSUE TITLE
Have the PublishBuildArtifacts task fail (optionally) if no artfacts found

### ISSUE THREAD

**Issue by marcussonestedtbarium** [microsoft/azure-pipelines-tasks#11317]
## Required Information

**Type**: Feature request
**Task Name**: PublishBuildArtifacts

## Environment

- Azure Pipelines - Hosted Agent - 

## Issue Description

If there are no artifacts, only a warning is given.

It'd be nice to set it to get an error, with `errorOnNoArtifacts: true` or a similar flag,.

https://github.com/MicrosoftDocs/vsts-docs/issues/5542#issuecomment-530019219

### Task logs

```
Starting: Archive
==============================================================================
Task         : Publish build artifacts
Description  : Publish build artifacts to Azure Pipelines or a Windows file share
Version      : 1.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
##[warning]Directory '/home/vsts/work/1/a' is empty. Nothing will be added to build artifact 'My-Artfact-Name'.
Finishing: Archive
```

**Comment by marcussonestedtbarium** [comment]
It fails if the folder doesn't exist (which happens for cypress screenshots) so having this configurable either way would actually be quite nice.

**Comment by jogelin** [comment]
I have the same issue, sometimes my artifact folder doesn't exist but it is normal in my process.

@marcussonestedtbarium did solve this since ?
