### ISSUE TITLE
File Transform Task - Unable to apply transformation for the given package. Verify the following

### ISSUE THREAD

**Issue by tomaszmadeyski** [microsoft/azure-pipelines-tasks#11322]
*Type*: Bug

**Task Name**: File Transform Task

I have setup File Transform Task to apply my `web.config` transformations in my zip deployment package. It seems that it finds proper file but it's unable to apply transformation and giving no reason, just saying `Unable to apply transformation for the given package. Verify the following`:

```
(...)
2019-09-11T09:29:59.1195513Z ##[debug]791 results
2019-09-11T09:29:59.1195989Z ##[debug]found 791 paths
2019-09-11T09:29:59.1196201Z ##[debug]applying include pattern
2019-09-11T09:29:59.1196406Z ##[debug]adjustedPattern: 'd:\a\_temp\temp_web_package_3615878409563156\**\PackageTmp\Web.config'
2019-09-11T09:29:59.1385581Z ##[debug]1 matches
2019-09-11T09:29:59.1386440Z ##[debug]1 final results
2019-09-11T09:29:59.1479667Z ##[warning]Unable to apply transformation for the given package. Verify the following.
2019-09-11T09:29:59.1487199Z ##[debug]Processed: ##vso[task.issue type=warning;]Unable to apply transformation for the given package. Verify the following.
2019-09-11T09:29:59.1488004Z ##[debug]defaultRoot: 'd:\a\_temp\temp_web_package_3615878409563156'
2019-09-11T09:29:59.1488266Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2019-09-11T09:29:59.1488462Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2019-09-11T09:29:59.1488662Z ##[debug]findOptions.followSymbolicLinks: 'true'
(...)
``` 

This is my task configuration:
![image](https://user-images.githubusercontent.com/1555694/64687291-80069080-d48a-11e9-9202-3a9feffcd38b.png)

Any idea what might be the issue here?

**Comment by tomaszmadeyski** [comment]
I did some further investigation and I believe the issue in the code of [specialXdtTransformation](https://github.com/microsoft/azure-pipelines-tasks/blob/aacf9984665b206bc2266c6a83e5771f9d0c5416/Tasks/Common/webdeployment-common/xdttransformationutility.ts#L83).  

With my current issue the task is entering `for(var transformXmlFile in transformXmlFiles)` with empty `transformXmlFiles`.

What I did was:
1. Change `-transform` and `-xml` to exact paths, with no `*` in it, so it does not enter any of `indexOf('*')` conditions and it worked well. Thing is that it's hard to use exact path which is something like `Content/a/1/c/...`
2. Change `-transform` and `-xml` from `-transform **\Web.Dev.config -xml **\Web.config` to `-transform **\*.Dev.config -xml **\*.config` - it works well. 

**So it looks to like the issues is somewhere inside `ifs` checking for `*`.
`-transform **\Web.Dev.config -xml **\Web.config` does not work
`-transform **\*.Dev.config -xml **\*.config` works well**

**Comment by mwanchap** [comment]
For other confused Googlers like me landing on this page: if you're only doing a substitution rather than a transformation, and it's being applied successfully but you're still getting this weird error for no apparent reason, it's because there's a sneaky undocumented default transformation happening. Remove the default transformation by adding `xmlTransformationRules: ''` as pointed out by Nishant Dhungel [here](https://developercommunity.visualstudio.com/content/problem/896673/unexpected-error-from-file-transform-v2-task.html)

**Comment by bhuesemann** [comment]
> xmlTransformationRules: ''

Thanks for pointing this out! This saved me a bunch!

**Comment by mshephard** [comment]
> For other confused Googlers like me landing on this page: if you're only doing a substitution rather than a transformation, and it's being applied successfully but you're still getting this weird error for no apparent reason, it's because there's a sneaky undocumented default transformation happening. Remove the default transformation by adding `xmlTransformationRules: ''` as pointed out by Nishant Dhungel [here](https://developercommunity.visualstudio.com/content/problem/896673/unexpected-error-from-file-transform-v2-task.html)

You, sir, are a god-send.

**Comment by kieren-harvey-shell** [comment]
The default is now documented, but they should probably make specific mention of removing the rule by setting it to '' if you don't want transforms to run. e.g. if you just want the variable substitution.
