### ISSUE TITLE
Command-line task reports false success if STDIO left open

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-tasks#11334]
At https://dev.azure.com/polymorpheus/BetterRandom/_build/results?buildId=1080&view=logs&s=62add90f-9a1f-5845-6bfd-b54447f526dc&j=f43d4008-7a89-5683-a713-8042507c2c7e, the shell script exited with status 1 (otherwise there would have been log output from more Dieharder tests; see the source at https://github.com/Pr0methean/BetterRandom/blob/dce64e116c1287eb243cb6e4d6a9431297973618/dieharder.sh#L102), but the job was reported as successful. The following status message was triggered:
 The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.

The bug seems to be that when such children are left hanging, the exit status is suppressed.

**Comment by jtpetty** [comment]
@Pr0methean - I believe the issue is that you are | the output to tee. When you do this, the exit status is the exit status of 'tee', not of the command you are piping to.

```
$ false | tee foo.txt
$ echo $?
0
$ false
$ echo $?
1
```

**Comment by Pr0methean** [comment]
No, that's not the problem: dieharder exits with status 0 even when the tests fail. It's lines 99-103 that convert the output to an exit status.

**Comment by jtpetty** [comment]
@Pr0methean - ok, I see, you are right, I jumped too quickly at the 'tee'. Looking through the code, I can see where we print out the 
```
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.
```
message, but, to me, it looks like we continue to process the exit code.

Can you re-run the pipeline and and check the 'Enable system diagnostics' so we can maybe get a better idea of what is going on?

**Comment by Pr0methean** [comment]
Started a diagnostic run (https://dev.azure.com/polymorpheus/BetterRandom/_build/results?buildId=1113&view=results); logs should be available in a few hours.

**Comment by Pr0methean** [comment]
Here's the log: https://dev.azure.com/polymorpheus/BetterRandom/_build/results?buildId=1115&view=logs&s=62add90f-9a1f-5845-6bfd-b54447f526dc&j=f43d4008-7a89-5683-a713-8042507c2c7e

**Comment by jtpetty** [comment]
I think I see your issue, you have:

```
) 2>&1 < prng_out | tee ../dieharder.txt report_out) &
if [ "$(grep -q -m 1 'FAILED' report_out)" ]; then
  pkill dieharder
  pkill java
  exit 1
fi
```

I think what you really want is:

```
) 2>&1 < prng_out | tee ../dieharder.txt report_out) &&
if [ "$(grep -q -m 1 'FAILED' report_out)" ]; then
  pkill dieharder
  pkill java
  exit 1
fi
```

A single & runs the command in the background, your grep is going to run and not find anything since report_out doesn't have any content yet

**Comment by Pr0methean** [comment]
> I think I see your issue, you have:
> 
> ```
> ) 2>&1 < prng_out | tee ../dieharder.txt report_out) &
> if [ "$(grep -q -m 1 'FAILED' report_out)" ]; then
>   pkill dieharder
>   pkill java
>   exit 1
> fi
> ```
> 
> I think what you really want is:
> 
> ```
> ) 2>&1 < prng_out | tee ../dieharder.txt report_out) &&
> if [ "$(grep -q -m 1 'FAILED' report_out)" ]; then
>   pkill dieharder
>   pkill java
>   exit 1
> fi
> ```
> 
> A single & runs the command in the background, your grep is going to run and not find anything since report_out doesn't have any content yet

report_out is a named pipe, not a normal file. The intent is to run dieharder in the background (since otherwise we couldn't reuse prng_out -- also a named pipe -- or its contents from one Dieharder run to the next), but monitor its output in the main shell so that it can be failed fast.

**Comment by jtpetty** [comment]
Ok, having looked through a lot of the agent and task code, I am pretty confident that issue is in dieharder.sh script and not in the agent. The agent is getting an exit code of 0.

Is it possible that for this instance, there is a race condition and that the grep is executed before data is written to report_out and it thinks it's done?

Can you not just pipe the output directly to grep?

```
) 2>&1 < prng_out | tee ../dieharder.txt | $(grep -q -m 1 'FAILED' report_out)) ||\
(
  pkill dieharder
  pkill java
  exit 1
)
```

**Comment by Pr0methean** [comment]
@jtpetty I'll be testing that solution overnight. Thanks!

**Comment by jtpetty** [comment]
@Pr0methean - Looking at the issue you filed, it seems that the problem you were running into is with the ubuntu image the agent is running on and not with the agent code itself. Is that correct? And if so, can this issue be closed?

**Comment by Pr0methean** [comment]
Sounds right; https://github.com/microsoft/azure-pipelines-image-generation/issues/1386 is the same issue.

**Comment by glucaci** [comment]
Lately we have the same problem with a .NET Core Task. I reported this also in azure-pipelines-image-generation/1386 because I'm not sure where this fits.
```
Starting: dotnet tool restore
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/opt/hostedtoolcache/dotnet/dotnet tool restore --ignore-failed-sources --no-cache --verbosity normal

... restoring packages

Restore was successful.
The STDIO streams did not close within 10 seconds of the exit event from process '/opt/hostedtoolcache/dotnet/dotnet'. This may indicate a child process inherited the STDIO streams and has not yet exited.
```
and the task will remain blocked until build timeout expires.

**Comment by bneumann** [comment]
Same issue here. After running the tests my agent with 2.165.0 say:

> Test Run Successful.
Total tests: 46
     Passed: 46
 Total time: 8.4851 Seconds
[debug]Exit code 0 received from tool '/usr/bin/dotnet'
The STDIO streams did not close within 10 seconds of the exit event from process '/usr/bin/dotnet'. This may indicate a child process inherited the STDIO streams and has not yet exited.
[debug]The STDIO streams did not close within 10 seconds of the exit event from process '/usr/bin/dotnet'. This may indicate a child process inherited the STDIO streams and has not yet exited.

while the old agent with 2.158.0 seems to be good
> Test Run Successful.
Total tests: 46
     Passed: 46
 Total time: 7.7349 Seconds
##[debug]Exit code 0 received from tool '/usr/bin/dotnet'
##[debug]STDIO streams have closed for tool '/usr/bin/dotnet'

I am not even opening any STDIOs in the tests (at least I am not aware of). Starting the task with debug doesn't reveal any more information. This issues is NOT fixed

**Comment by bneumann** [comment]
Reopen please?

**Comment by Mahesh01260126** [comment]
I am facing the same issue. i don't want to kill java as other process are running on it.
Is there any other solution for it

**Comment by eriktack** [comment]
This is still happening, we see it frequently with the DotNetCoreCLI@2 yaml task. It writes "The STDIO streams did not close within 10 seconds of the e***it event from process 'C:\Program Files\dotnet\dotnet.e***e'. This may indicate a child process inherited the STDIO streams and has not yet e***ited." to the log and then does nothing until the job times out (after 60 minutes).

Please fix this.
