### ISSUE TITLE
Ownership transfer of a branch in Azure Repos

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11335]
Hi,

I have a branch for which I am the author. I want to transfer the ownership of this branch to another member in the team. How can I do this?

Thanks,

**Comment by damccorm** [comment]
Hi, sorry for the slow response - would you mind opening this issue in https://developercommunity.visualstudio.com/spaces/21/index.html - that's the best place to ask non-task specific questions about Azure Devops since this repo is dedicated mostly to tasks
