### ISSUE TITLE
Detached Head during pipeline build

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11330]
Hi,

I notice the following during the pipeline build stage for my git branch. I however get no 'HEAD DETACHED' error when I checkout the branch in my dev environment. Is this error significant or is it just something that is to be expected for all git based pipeline builds on Azure DevOps?

> Note: switching to 'd1be2f5491ae7fbb40fc7ec095c4be44b4120dc5'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at d1be2f5 Update azure-pipelines.yml for Azure Pipelines

Thanks,

**Comment by damccorm** [comment]
Hi, sorry for the slow response - would you mind opening this issue in https://developercommunity.visualstudio.com/spaces/21/index.html - that's the best place to ask non-task specific questions about Azure Devops since this repo is dedicated mostly to tasks
