### ISSUE TITLE
how can execute dll file via dotnet.exe

### ISSUE THREAD

**Issue by ricoisme** [microsoft/azure-pipelines-tasks#11333]
Hi

I just want to execute myapp.dll via dotnet.exe so type "myapp.dll" into custom command.
But I got error message as below:
No executable found matching command "dotnet-D:\myjob-vsts-agent\_work\125\s\BackgroundJobs\MigrationJob\bin\Release\netcoreapp2.2\MigrationJob.dll"
##[error]Error: The process 'D:\myjob-vsts-agent\_work\_tool\dotnet\dotnet.exe' failed with exit code 1
##[error]Dotnet command failed with non-zero exit code on the following projects ...

Thanks

**Comment by issacnitin** [comment]
@ricoisme Currently we donot have support to run the dll directly, You could use the Run command to build and run the project. Follow the screenshot below
![3](https://user-images.githubusercontent.com/4218887/64961322-d91f5b80-d8b2-11e9-8d4e-8c2689d2421e.PNG)

**Comment by ricoisme** [comment]
I knew it but I dont want to rebuild dotnet project.
I mean I had builded a solution include some dotnet projects. 
I hope support it in azure devops pipelines.

Thanks your replay.

**Comment by dikhakha** [comment]
@ricoisme You can run your dll in Azure Pipelines using **Command Line task**, run this command: `dotnet <path-to-dll>`. 
You could get the above error if you have not specified the path of dll correctly. Where is your dll located ?

**Comment by ricoisme** [comment]
@dikhakha 
It works for me. 

Thanks
