### ISSUE TITLE
vsts-npm-auth: Unable to authenticate when probing

### ISSUE THREAD

**Issue by elijah1210** [microsoft/azure-pipelines-tasks#11340]
Hi,

I am on Windows.

I am attempting to use vsts-npm-auth to handle authentication against an Azure feed.

.npmrc in my users profile
`registry=https://registry.npmjs.com`

The .npmrc file in my project (next to package.json)
```
registry=http://linktoregistry.com/npm/registry
always-auth=true
package-lock=false
```

When I run 
`vsts-npm-auth -config .npmrc -v detailed`, I receive the following.

```
vsts-npm-auth v0.37.0.0
-----------------------
Parameters:
  AuthenticationProviders=wia,federated
  Config=.npmrc
  Help=False
  NonInteractive=False
  TargetConfig=
  ExpirationMinutes=129600
  ReadOnly=False
  Force=False
  Verbosity=Detailed
INI (resolved): registry=https://registry.npmjs.com
INI (resolved): registry=http://linktoregistry.com/npm/registry
INI (resolved): always-auth=true
INI (resolved): package-lock=false
Probing 
http://linktoregistry.com/npm/registry
Probe response code: 401 Unauthorized
Credential type: Unknown.
Has valid credentials: False.
```

The authentication works just fine when I add the token to my user .npmrc manually, however, I do not want our users to do something like that every 90 days or so, either via a gulp task or an npm task when our developers are working on things locally.

Additionally, if I have the token in my user .npmrc, and add the -f flag to force re-authentication, I get the same probe response code and credential type.

**EDIT: If this is in the wrong place, please let me know and I will move it.**

**Comment by jotaylo** [comment]
Hi, this isn't really the right place for it, but there isn't a much better place, so I'll try to help here.
Are you trying to use this to authenticate to an on-premises install of TFS? vsts-npm-auth only works with the hosted version of Azure DevOps.

The probe makes an unauthenticated request to the registry, and then looks for the 'X-VSS-AuthorizationEndpoint' header in the response. `Credential type: Unknown` suggests that the response isn't returning that header, and as such is not a hosted Azure DevOps npm registry.

**Comment by elijah1210** [comment]
@jotaylo I have a sneaking suspicion that it's an on-premises install of TFS instead of a hosted version. Are there any other ways that I can verify? 

Something I noticed is that there when I click the connect to feed, it doesn't recommend vsts-npm-auth as a tool.

**Comment by jotaylo** [comment]
If it's a hosted version the uri will be either `https://[org].visualstudio.com` or `https://dev.azure.com/[org]`
(and yes, vsts-npm-auth only shows in connect-to-feed in the hosted version).

The connect-to-feed UI generates a 90 day token, but users can use the security dialog to generate a token that is valid for up to a year: see [Create a token that lasts longer than 90 days](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#set-up-authentication-on-your-dev-box)

**Comment by elijah1210** [comment]
Hmm... Okay, I am pretty comfortable saying that TFS is on premise. The URL follows this pattern https://{server}:8080/tfs/.

I guess I'll have to investigate using the tokens or some other method.

**Comment by jotaylo** [comment]
Yep, that's on premise. I'm sorry about that, unfortunately there are technical differences between how auth works between hosted and on-prem, and we're only able to get vsts-npm-auth working for the hosted instance at this time.
