### ISSUE TITLE
System.Nets.SocketException in Azure function app

### ISSUE THREAD

**Issue by ashutak84** [microsoft/azure-pipelines-tasks#11345]
## Note  
Deployed Azure function app via Azure Function App Deploy task in release. 

## Required Information

Azure function app run time error

**Question ?**  

Following error is coming up in telemetry when i try to deploy the function App from release task. I have attached the YAML, i have also attached the stack trace of the error. This is the common message which appears: "An attempt was made to access a socket in a way forbidden by its access permissions"

## Environment
- Server - Azure Pipelines?
  
## Issue Description

Azure function gets deployed in production but fails to start, 
Following error is coming up in telemetry i have attached the stack trace of the error. This is the common message which appears: "An attempt was made to access a socket in a way forbidden by its access permissions"

Please note: Above error happens when function app is released from VSO release pipeline, when i deploy the app manually from the Visual Studio 2017, the function app runs without any problem.
[FunctionApp-Yaml.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3613665/FunctionApp-Yaml.txt)
[CallStackFromTelemetry.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3613666/CallStackFromTelemetry.txt)

### Error logs

An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by SumiranAgg** [comment]
You might have reached socket limit. I cannot find any official documentation but please check out this blog fore more information https://blog.vjirovsky.cz/azure-functions-and-forbidden-socket-exception/

**Comment by ashutak84** [comment]
I have already googled that blog it didn't help solve the problem, i have already done the code changes as suggested by them and it works fine when publish it from Visual Studio, 
i did following thing:

1. Used VSO's release pipeline with release task Azure App Service Deploy and deployed the service in a very high S3 app service plan. Didn't work, kept giving me the above error.
2. I deployed from Visual Studio 2017 where i had developed this application. and around 8000+ messages were processed from the Service Bus without any problem. 

But for production i must fix the deployment from VSO release task, its processing the requests but keeps giving me the Socket error. Please help..

**Comment by arjgupta** [comment]
@ashutak84 can you please send the task debug logs to RM_Customer_Queries at microsoft dot com. are you using run from package. If yes, then please try to use zip deploy and see if you are able to deploy successfully.

**Comment by ashutak84** [comment]
I am using zip deploy, I found the problem, it was with my storage account
which u created newly but I still don't know what was the difference
between the storage accounts.

**Comment by ashutak84** [comment]
This problem was solved, i had kept one AzureWebJobsStorage value was "UseDevelopmentStorage = true" in the appsettings of the function app, when i modified to point to exact address. It solved the problem
