### ISSUE TITLE
NuGet push retry capability

### ISSUE THREAD

**Issue by dandrejvv** [microsoft/azure-pipelines-tasks#11347]
*Type*: Feature

NuGet

## Issue Description

When publishing Nuget packages to DevOps Artifacts, it sometimes fail with an internal error:

> POST (https://pkgs.dev.azure.com/inoxidev/_apis/packaging/e8f2f7f0-ea13-7409-b527-b509020cee08/nuget/packages) failed. ActivityId: 78a3b62f-4bab-45b1-94b3-13bd0dc27580, HTTP Status: InternalServerError, AFD Ref: Ref A: FB0C53FD8F0F4143BE76EDA6AF2B3DCC Ref B: DB3EDGE1610 Ref C: 2019-09-16T14:51:37Z
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__31.MoveNext()

It's not so much that I want to report that error as getting that resolved will take too long. I want to be able to set a retry action to try 2 more times at least so that it can publish all the artifacts that weren't published before to prevent me having to kick off another build, wait 30 minutes and hope it publishes this time.

So potentially one can have a property under the Control section of the Task where you can switch ON `retry on error` and specify the `maximum retry attempts` before it classifies the Task as a failure. This should work in conjunction with the `Allow duplicates to be skipped` so that we don't get errors because its trying to publish a package that's already published.

**Comment by sander1095** [comment]
Any updates? I have the same issue! 

My current ugly solution would be to copy the nuget push task twice and then write a custom condition to only run the tasks if the previous nuget push failed; essentially giving it X retries.

**Comment by edgarrs** [comment]
Adding retries is the right solution in this case

**Comment by dandrejvv** [comment]
Hi @edgarrs, I see the ticket it closed. What does this mean? That it will not be looked at? Or is it moved to somewhere else?
