### ISSUE TITLE
VSTest: Where to set TestExecution.EnableHydra

### ISSUE THREAD

**Issue by tsteenbakkers** [microsoft/azure-pipelines-tasks#11359]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VSTest

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV2

## Environment
- Server - Azure Pipelines or TFS on-premises? --> Azure Pipelines.
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016, Agent version 2.155.1

## Issue Description

We are making modifications to a copy of the VSTest Task to accomodate for usage of a custom TRXLogger. We found that in one part of the code inside runvstest.ts the following const is being assigned:

```
const enableHydra = await isFeatureFlagEnabled(tl.getVariable('System.TeamFoundationCollectionUri'),
        'TestExecution.EnableHydra', tl.getEndpointAuthorization('SystemVssConnection', true).parameters.AccessToken);
```

we verified that this flag was indeed on, but we would like to know where the control is for this setting in Azure Devops. We can not seem to find it at all. we would like to make sure that the `TestExecution.EnableHydra` is set to off so we do not have to shortcircuit the assertion later which decides which execution path to take.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ShreyasRmsft** [comment]
@tsteenbakkers the typescript code that you see in the task is legacy code and we will be moving away from it. The TestExecution.EnableHydra variable is the feature flag we are using to move customers away from the legacy code. It is fetched from the server is a temporary flag till we migrate all users after which both the flag as well as the legacy code will be deleted.

If what you want is a custom TrxLogger there are easier ways to achieve this. Let me know what it is you are trying to do and i should be able to help guide you.

**Comment by ShreyasRmsft** [comment]
Closed due to no response.

**Comment by gclpixel** [comment]
What is the expected value of 'EnableHydra' on non legacy code. 
On our system this flag is enabled unexpected.
Will this code 
`test.runNonDistributedTest();`
or this 
`localtest.startTest();`
the new prefered way?

**Comment by ShreyasRmsft** [comment]
test.runNonDistributedTest();

we will be deleting the legacy code (localtest.startTest()) soon
