### ISSUE TITLE
AzurePowerShellV4 does not prefer pwsh over powershell (despite code comment saying so) and there is no configuration option

### ISSUE THREAD

**Issue by bergmeister** [microsoft/azure-pipelines-tasks#11358]
## Required Information

*Type*: Bug

**Enter Task Name**: `AzurePowerShellV4`

## Environment

Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: `windows-2019`

## Issue Description

When being run on an image that has PowerShell Core (pwsh) installed and on the path, the `AzurePowerShellV4` task does not use it but uses Windows PowerShell (powershell).
The comment in the code says, that pwsh should be preferred
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzurePowerShellV4/azurepowershell.ts#L91

However, when being run on the  `windows-2019` image, it uses Windows PowerShell despite PowerShell Core being installed. It should either do what the comment states or similar to the `PowerShellV2`, there should be an optional parameter for it.
One can easily verify this by running `where.exe pwsh` first in the task to verify that `pwsh` is on the `PATH` and then `$PSVersionTable` will return a version number of 5.1.x, which is the version number of Windows PowerShell

**Comment by 20shivangi** [comment]
@bergmeister 
For now, the task AzurePowerShellV4 does not support powershell core in Windows. This support is recently added in this week. It will take at least 3-4 weeks to get deployed.

**Comment by bergmeister** [comment]
Thanks for the feedback. Sorry, I was not aware that this change was very recent and has not been deployed yet. :-)
