### ISSUE TITLE
CacheBeta: task: cache turns symlinks into real files breaking virtualenvs

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-tasks#11350]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheBetaV0

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: N/A
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: asottile, asottile, 7 -- https://github.com/asottile/azure-pipeline-templates/pull/25

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: linux hosted

    - If using private agent, provide the OS of the machine running the agent and the agent version: N/A

## Issue Description

The CacheBeta task is dereferencing symlinks when they should be stored verbatim.

This (for example) breaks the output of virtualenvs:

(expected output -- this is taken from my local machine)

```console
$ ls -al venv/bin/
total 4512
drwxr-xr-x 2 asottile asottile    4096 Aug 16 02:57 .
drwxr-xr-x 5 asottile asottile    4096 Jun 28 23:37 ..
-rw-r--r-- 1 asottile asottile    2116 Jun 28 23:37 activate
-rw-r--r-- 1 asottile asottile    1448 Jun 28 23:37 activate.csh
-rw-r--r-- 1 asottile asottile    3072 Jun 28 23:37 activate.fish
-rw-r--r-- 1 asottile asottile    1804 Jun 28 23:37 activate.ps1
-rw-r--r-- 1 asottile asottile    1512 Jun 28 23:37 activate_this.py
-rw-r--r-- 1 asottile asottile    1170 Jun 28 23:37 activate.xsh
-rwxr-xr-x 1 asottile asottile     259 Aug 16 02:57 black
-rwxr-xr-x 1 asottile asottile     260 Aug 16 02:57 blackd
-rwxr-xr-x 1 asottile asottile     269 Jun 28 23:37 easy_install
-rwxr-xr-x 1 asottile asottile     269 Jun 28 23:37 easy_install-3.6
-rwxr-xr-x 1 asottile asottile     250 Jun 28 23:37 identify-cli
-rwxr-xr-x 1 asottile asottile     245 Jun 28 23:37 nodeenv
-rwxr-xr-x 1 asottile asottile     251 Jun 28 23:37 pip
-rwxr-xr-x 1 asottile asottile     251 Jun 28 23:37 pip3
-rwxr-xr-x 1 asottile asottile     251 Jun 28 23:37 pip3.6
-rwxr-xr-x 1 asottile asottile     412 Jun 28 23:37 pre-commit
-rwxr-xr-x 1 asottile asottile     444 Jun 28 23:37 pre-commit-validate-config
-rwxr-xr-x 1 asottile asottile     448 Jun 28 23:37 pre-commit-validate-manifest
lrwxrwxrwx 1 asottile asottile       7 Jun 28 23:37 python -> python3
-rwxr-xr-x 1 asottile asottile 4522328 Jun 28 23:37 python3
lrwxrwxrwx 1 asottile asottile       7 Jun 28 23:37 python3.6 -> python3
-rwxr-xr-x 1 asottile asottile    2358 Jun 28 23:37 python-config
-rwxr-xr-x 1 asottile asottile     248 Jun 28 23:37 virtualenv
-rwxr-xr-x 1 asottile asottile     247 Jun 28 23:37 wheel
```

(output after restore from CacheBeta)

```console
ls -al $PRE_COMMIT_HOME/*/*/bin -al
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/37962ece-6fb7-45f0-8084-74a4de67836e.sh
/home/vsts/work/1/.pre-commit/repo3xua1rgt/py_env-python3.7/bin:
total 108
drwxr-xr-x 2 vsts docker  4096 Sep 17 05:54 .
drwxr-xr-x 5 vsts docker  4096 Sep 17 05:54 ..
-rw-r--r-- 1 vsts docker  2248 Sep 17 05:54 activate
-rw-r--r-- 1 vsts docker  1467 Sep 17 05:54 activate.csh
-rw-r--r-- 1 vsts docker  3132 Sep 17 05:54 activate.fish
-rw-r--r-- 1 vsts docker  1751 Sep 17 05:54 activate.ps1
-rw-r--r-- 1 vsts docker  1517 Sep 17 05:54 activate_this.py
-rw-r--r-- 1 vsts docker  1189 Sep 17 05:54 activate.xsh
-rw-r--r-- 1 vsts docker   284 Sep 17 05:54 dmypy
-rw-r--r-- 1 vsts docker   287 Sep 17 05:54 easy_install
-rw-r--r-- 1 vsts docker   287 Sep 17 05:54 easy_install-3.7
-rw-r--r-- 1 vsts docker   287 Sep 17 05:54 mypy
-rw-r--r-- 1 vsts docker   269 Sep 17 05:54 pip
-rw-r--r-- 1 vsts docker   269 Sep 17 05:54 pip3
-rw-r--r-- 1 vsts docker   269 Sep 17 05:54 pip3.7
-rw-r--r-- 1 vsts docker 11672 Sep 17 05:54 python
-rw-r--r-- 1 vsts docker 11672 Sep 17 05:54 python3
-rw-r--r-- 1 vsts docker 11672 Sep 17 05:54 python3.7
-rw-r--r-- 1 vsts docker  2377 Sep 17 05:54 python-config
-rw-r--r-- 1 vsts docker   268 Sep 17 05:54 stubgen
-rw-r--r-- 1 vsts docker   265 Sep 17 05:54 wheel
```

### Task logs

https://asottile.visualstudio.com/asottile/_build/results?buildId=1308

this contains the particular output from above

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

N/A see above

**Comment by johnterickson** [comment]
Rolling out via #10925
