### ISSUE TITLE
Xcode task: specifying Xcode version/path

### ISSUE THREAD

**Issue by grav** [microsoft/azure-pipelines-tasks#11362]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Xcode

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: hosted macOS

## Issue Description

When specifying `xcodeVersion: '10'`, version `10.2.1` is selected. It isn't possible to select `10.3` without specifying the path (using `xcodeDeveloperDir`). And there isn't any official list of installed Xcode versions, so it's trial and error.

**Comment by alombard** [comment]
+1 - A published list of Xcode versions would be amazing.

**Comment by alombard** [comment]
Found it!

https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md

**Comment by leantk** [comment]
This is the location for the most current Mac image
https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#xcode
