### ISSUE TITLE
dotnetcli test does not use vstsfeed parameter when restoring nuget packages

### ISSUE THREAD

**Issue by joalmeid** [microsoft/azure-pipelines-tasks#11365]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 
```
- task: DotNetCoreCLI@2
      displayName: 'Test Task test #1'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
        vstsFeed: '/c9b259bc-eed9-44de-ac14-7fb9f08f7fe7'
```

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Type**: Bug
**Enter Task Name**: DotNetCoreCLI

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Azure Pipelines
  - Account Name: IntertechTr 
  - Project: V2_GIT
  - Yaml pipeline: [boilerplate-stateless-CICD-docker.yaml](https://dev.azure.com/IntertechTr/V2_GIT/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=81&branch=474_Add_SonarQube_Configs)
  - Build number: [#2680](https://dev.azure.com/IntertechTr/V2_GIT/_build/results?buildId=2680&view=results)

- Self-Hosted Agent: 
  - Machine OS: Linux Ubuntu 16
  - Agent version: 2.155.1

## Issue Description
The DotNetCoreCLI is running command 'test', on a project relying on artifacts in Azure Artifacts.
Previous task of command 'restore' runs correctly (with the vstsfeed argument).
However the test command fails, even specifying vstsfeed arg.

### Task logs

```
/home/intertech/agent/_work/_tool/dotnet/dotnet test /home/intertech/agent/_work/30/s/src/boilerplate-stateless/boilerplate-stateless-project-template/test/Intertech.ApiName.IntegrationTests/Intertech.ApiName.IntegrationTests.csproj --logger trx --results-directory /home/intertech/agent/_work/_temp --configuration Release --collect Code coverage
/home/intertech/agent/_work/_tool/dotnet/sdk/2.2.402/NuGet.targets(123,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/IntertechTr/_packaging/nuget-hosted/nuget/v3/index.json. [/home/intertech/agent/_work/30/s/src/boilerplate-stateless/boilerplate-stateless-project-template/test/Intertech.ApiName.IntegrationTests/Intertech.ApiName.IntegrationTests.csproj]
/home/intertech/agent/_work/_tool/dotnet/sdk/2.2.402/NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/home/intertech/agent/_work/30/s/src/boilerplate-stateless/boilerplate-stateless-project-template/test/Intertech.ApiName.IntegrationTests/Intertech.ApiName.IntegrationTests.csproj]
##[debug]Exit code 1 received from tool '/home/intertech/agent/_work/_tool/dotnet/dotnet'
##[debug]STDIO streams have closed for tool '/home/intertech/agent/_work/_tool/dotnet/dotnet'
##[error]Error: The process '/home/intertech/agent/_work/_tool/dotnet/dotnet' failed with exit code 1
```

**Comment by shubham90** [comment]
@joalmeid Unfortunately, dotnet test command does not support vstsFeed parameter. Only dotnet nuget push and restore supports vstsFeed parameter. 
If you want to use an authenticated feed with dotnet test, I will recommend you to use [Nuget Authenticate task ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#dotnet) and then you will be able to use any dotnet script with the authenticated feed.

**Comment by dikhakha** [comment]
@joalmeid Please let me know if the above suggestion works for you.

**Comment by joalmeid** [comment]
@dikhakha, that was exactly our scenario - using authenticated feeds. We made sure restore would run correctly beforehand any test task.
We can close this issue.
