### ISSUE TITLE
Feature Request: Please support Multi-Agent testing for dotnet

### ISSUE THREAD

**Issue by Oblivious91** [microsoft/azure-pipelines-tasks#11367]
Hello Azure Pipeline Team,

The era of .NET Core is here and I would like to request for multi-agent testing for it be supported in the pipeline. I was told that this is currently only supported in Windows. 

My main motivation is to execute tests in a distributed fashion in the Azure Pipelines using linux machines.

Thanks!

Jorge

**Comment by joberume** [comment]
Resurfacing this so that it does not slip through the cracks....

**Comment by joberume** [comment]
@ShreyasRmsft can we get traction on this?

**Comment by ShreyasRmsft** [comment]
@joberume we pick up feature requests based on popular demand, as of now this is low priority in our backlog.

cc: @shashban
