### ISSUE TITLE
Not a issue but Want to publish the Automation Test Results executed in Azure Devops to team members through(Mail or Teams)

### ISSUE THREAD

**Issue by vishnuprakash9845** [microsoft/azure-pipelines-tasks#11372]
I have developed a testing framework for automating the UWP Application using appium.
Created the build pipeline to run the tests in VM in Azure Devops and able to see the Test Results and summary.

**But wanted this results to publish to my entire team of 12 members as soon as the Test Automation in the VM completes through Mail or Microsoft Teams**

Can anyone help me on this, if anyone feels any blog or reference would be useful for the above issue. I am reachable @ vishnuprakash9845@gmail.com

**Comment by kaadhina** [comment]
It is possible to set notifications for pipeline completion that will send out the report over email: https://docs.microsoft.com/en-us/azure/devops/notifications/?view=azure-devops

**Comment by vishnuprakash9845** [comment]
I Just went through the link, but could not find to send the below summary report through mail

![image](https://user-images.githubusercontent.com/24207575/65957131-ba4fc600-e469-11e9-8b7d-11aa4cc6ad73.png)

**Comment by Additi** [comment]
Hi Vishnu, 
We don't support notifications on the test task itself, however you can add a email notification task in your pipeline after the test task and configure it. This task will send out email notifications to the members you have added once the results are published from the test task. 
Thanks,
Aditi

**Comment by vishnuprakash9845** [comment]
Thank you Additi for the response, I will try to use the email notification task.

**Comment by Tuely** [comment]
Worth trying report generator -
ref this link Report Generator for SpecFlow 
https://marketplace.visualstudio.com/items?itemName=mmajcica.SpecFlowReportGenerator
after the html file generation, you can send an email notification with that attachment. worth trying. I am also in the middle of doing that's
