### ISSUE TITLE
Azure DevOps Services CI Build not started for long time

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11373]
Hi,

My CI build hasn't started now for almost an hour. The build details shows the following information.

![image](https://user-images.githubusercontent.com/2850526/65241154-82a75c80-db00-11e9-9069-234940288cb5.png)

Did I do anything incorrect, and how to recover from this? Should I continue waiting? How can I avoid this in future?

Because of this my other CI builds are also not progressing?
![image](https://user-images.githubusercontent.com/2850526/65241385-05301c00-db01-11e9-9075-334fca66b71d.png)

Thanks

**Comment by damccorm** [comment]
Hi, sorry for the slow response - would you mind opening this issue in https://developercommunity.visualstudio.com/spaces/21/index.html - that's the best place to ask non-task specific questions about Azure Devops since this repo is dedicated mostly to tasks
