### ISSUE TITLE
Better caching support for short-lived feature branches

### ISSUE THREAD

**Issue by johnterickson** [microsoft/azure-pipelines-tasks#11374]
Based on conversation with @lukeapage and @marcussonestedtbarium in https://github.com/microsoft/azure-pipelines-tasks/issues/11314, it sounds like Pipeline Caching doesn't really help folks who have short-lived feature branches because it's always a cache miss.

There are security concerns with interactions of caches across branches, but one possible solution we came up with was to all builds to opt-in to reading of another branch.  In these scenarios, the customers would want to configure their cache task in their feature branches (if not just everywhere) to be able to read from the cache from master.

Thinking out loud, @owenhuyn & @willsmythe - could we just special case that we always (edit: for non-fork-PRs?) read from the master scope?

**Comment by fadnavistanmay** [comment]
I think Owen is @owenhuynMSFT

**Comment by rbev** [comment]
I just noticed this behaviour during a bug-squashing sprint where almost every branch only had one commit. 
Providing a "read" branch to the restore step would be great, similar to how PR builds will read from the source/target caches.

**Comment by johnterickson** [comment]
Chatted with @owenhuyn  and this seems reasonable from a dev impl perspective.

**Comment by jabbera** [comment]
This feature is still useful for multi stage/job builds but would be infinitely more useful if we could always use master (or some other targeted branch) as a read only source.

On a side note: I need to move my build binaries/projects/etc from one stage of my pipeline to another, but they don’t need to actually be an end artifact of the pipeline. (I’ve got a testing matrix that runs across 5 different jobs.) The raw binaries can be discarded after the testing phase since my actual pipeline output is a nuget package. Even though the documentation recommends against this, it seems like a natural use for this, no? 

(Or I could be provided a task to remove artifacts?)

**Comment by johnterickson** [comment]
@jabbera FWIW the reason we recommend against it is that artifacts are tied directly to the build.  Pipeline Caching is scoped to a branch, so concurrent builds of the same branch could cross-talk.  There's possibly some hackery one could do by making the cache key unique to the build, but I've not thought it through.

**Comment by fadnavistanmay** [comment]
> @jabbera FWIW the reason we recommend against it is that artifacts are tied directly to the build. Pipeline Caching is scoped to a branch, so concurrent builds of the same branch could cross-talk. There's possibly some hackery one could do by making the cache key unique to the build, but I've not thought it through.

"There's possibly some hackery one could do by making the cache key unique to the build" -> include $(Build.BuildId) for this 💭

**Comment by jabbera** [comment]
Thanks. Makes total sense. Seems silly to have 400 megs are artifacts attached to my pipeline when I only need a dozen nuget packages totaling 900k. I was hoping you’d have the magic bullet.

**Comment by johnterickson** [comment]
@fadnavistanmay Can you close this when the "read from master" change lands?

**Comment by fadnavistanmay** [comment]
This should be released.

**Comment by elvirdolic** [comment]
What is the state about this change? is this read, how does it work? It's pity if the the yarn.lock was not changed that we always have a cache miss on a pull request. There is no benefit scoping this to the branch name ...

**Comment by christianduerselen** [comment]
@johnterickson @fadnavistanmay 
I would also second @elvirdolic that I didn't find enough documentation how the "read from main" feature for the Cache task is supposed to work. Does the branch have to have a specific name? Any changes to the caching key necessary? Is the cache only used for PRs?
At the moment running the same pipeline on a "dev/[name]" branch does not find an existing cache through the restore keys from the "main" branch.

I'm highly interested in a working solution for feature branches and readonly-access to a main-branch pipeline cache is absolutely sufficient for my need. My use case is a yocto sstate cache which can reduce pipeline time from 3h to 15 minutes so using any cache throughout branches is highly welcome.

**Comment by tmm1** [comment]
Is there a technique for sharing main cache from a feature branch?

EDIT: It appears to work automatically for main/master now, as you would expect. Presumably this behavior changed after the PR mentioned in https://github.com/microsoft/azure-pipelines-tasks/issues/16998#issuecomment-1309622582 was merged

Now I observe the following in logs:

```
Used scope: 5;6e5f871a-3792-4829-948c-7be032a91b32;refs/heads/main;tmm1/myrepo
Missed on the following scopes: 5;6e5f871a-3792-4829-948c-7be032a91b32;refs/heads/tmm1/test-branch;tmm1/myrepo, 5;6e5f871a-3792-4829-948c-7be032a91b32;refs/heads/master;tmm1/myrepo
```
