### ISSUE TITLE
Set a pipeline variable to true if scheduled build

### ISSUE THREAD

**Issue by saxenark** [microsoft/azure-pipelines-tasks#11379]
Hi,

I want to pass additional arguments to my batch file in case the Build.Reason is not 'IndividualCI' or 'BatchedCI'. For that I am trying to set a variable to true like so, which is incorrect, because it is not under condition statement.

`IsScheduledBuild: notin(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')`

So, how can I set a custom variable to true, if Build.Reason is a scheduled build (as against CI build)? Or, please suggest if there is an alternate way.

Essentially what I want to do it like so:

```
if (Build.Reason = CI Build)
{
    call MyBatchFile Args1 Args2
}
else
{
    call MyBatchFile Args1 Args2 Args3 Args4
}
```

**Comment by damccorm** [comment]
Hi, sorry for the slow response - would you mind opening this issue in https://developercommunity.visualstudio.com/spaces/21/index.html - that's the best place to ask non-task specific questions about Azure Devops since this repo is dedicated mostly to tasks
