### ISSUE TITLE
Option to cache build artifacts even if build job fails.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/azure-pipelines-tasks#11388]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: CacheBeta@0  

## Issue Description

Currently, cache post-job is skipped if the job status is not `Succeeded`.
It would be nice to have an option to cache intermediate build artifacts even if the job fails.  For example, object files cached by ccache can still be used even if there was a compilation error later in the build.

**Comment by johnterickson** [comment]
Hi @vadimcn - Thanks for providing feedback.  We wanted to err on the safe side initially.

**Comment by fadnavistanmay** [comment]
Hi @vadimcn - As John mentioned, we made a design decision to error out if the build fails, based on - since the build failed, the cache might be considered invalid. 
I think, we want to keep it that way as of now, hence closing this issue. 

We could re-open later if required. Thanks

**Comment by vadimcn** [comment]
Seems like it wouldn't be too hard to let people override the default, but okay, it's your build servers being hammered...  ¯\\\_(ツ)\_/¯

**Comment by ivailop** [comment]
In a perfect world all tests would pass all the time...
However, with complexity growing test failures are very common and sometime based on how critical they are and available resources to address them they may persist in the CI for a period of time. 
Does it mean in such scenarios caching (especially 3rd party dependencies) would not be possible?

**Comment by apobekiaris** [comment]
this is really counter productive should I reconstruct my cache every time until my step pass? or should I hack my way to it?

**Comment by atruskie** [comment]
I've blown out hundreds of gigabytes of GIT LFS data transfer because

- I didn't realise this was happening (the Post-job step has a green tick on it even if it was skipped!)
- and then even when I knew it was happening, I had no alternative and still needed to get my CI to pass

Please reconsider.

**Comment by moubry** [comment]
This design decision was unnecessarily user hostile in my opinion — if you're iterating on a pipeline to try to get a build passing you have to keep going through the SLOWEST possible steps in order to get to everything working, and there's no obvious workaround.
