### ISSUE TITLE
Using Azure AD Integrated auth throwing an error

### ISSUE THREAD

**Issue by jayatipathak** [microsoft/azure-pipelines-tasks#11389]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: Azure SQL Database deployment

## Environment
- Server - Azure Pipelines    
   MicrosoftIT | OneITVSO | Galena_Dev 
https://microsoftit.visualstudio.com/OneITVSO/_releaseProgress?releaseId=816908&environmentId=2645534&_a=release-task-editor 

- Agent - Hosted 

## Issue Description

Trying to use Azure AD integrated option to run the Azure SQL task and I am getting below error. Is there any prerequisite steps to have before using this Auth option.

## Troubleshooting
![image](https://user-images.githubusercontent.com/28723607/65381921-f2a81500-dcaf-11e9-9a9f-4e6cb8304f54.png)
### Error logs

[ReleaseLogs_816908.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3639315/ReleaseLogs_816908.zip)

**Comment by 20shivangi** [comment]
@jayatipathak 
We do not support Azure AD integration option in Hosted agent . You must use private agent for this option.

**Comment by 20shivangi** [comment]
Feel free to reopen the issue, if you face any.
