### ISSUE TITLE
AzureResourceGroupDeploymentV2 doesn't work with subscription level deployment template

### ISSUE THREAD

**Issue by IvanovOleg** [microsoft/azure-pipelines-tasks#11380]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
When I run AzureDevOps yaml pipeline and provide a subscription level ARM template that contains only resource group in the resource section, it fails trying to find that resource group on the resource group level instead of the subscription level.

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
NotFound: {
  "message": "No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/<my subscription id>/resourcegroups/<resource group name defined in the task>/providers/Microsoft.Resources/resourceGroups/<resource group name defined in the ARM template>?api-version=2018-05-01'."
}
```

[Insert error from the logs here for a quick overview]

**Comment by bishal-pdMSFT** [comment]
@vinodkumar3 this looks like a regression

**Comment by dikhakha** [comment]
@IvanovOleg Presently, AzureResourceGroupDeploymentV2 supports template deployment at Resource group level and not subscription level which is why you are seeing the above error. We plan to add support for this soon.

To unblock yourself, if you intend to create Azure Resource group in your Azure Pipeline, you can use [Azure CLI task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#yaml-snippet) to run [az command to create resource group](https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create). 

Please let me know if this helps !

**Comment by dikhakha** [comment]
@IvanovOleg Are you unblocked using suggested workaround ?

**Comment by IvanovOleg** [comment]
@dikhakha No, since that was just an example. Actually I need to deploy resources to multiple resource groups.

**Comment by dikhakha** [comment]
@IvanovOleg We are working on adding support for this scenario and it will be rolled out soon !

**Comment by IvanovOleg** [comment]
@dikhakha Thanks!
