### ISSUE TITLE
Azure AppService. Perform swap with preview fails

### ISSUE THREAD

**Issue by nilfdev** [microsoft/azure-pipelines-tasks#11384]
## Note  
It is not possible to perform swap from staging environment to production environment

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Required Information

*Type*: Bug

**Enter Task Name**: 
Swap Slots

## Environment
- Server - Azure Pipelines
    
## Issue Description

We use azure devops portal with configured pipeline. There are 2 tasks: 
- deploy to slot 
-swap slots
we are working long time but couple of days ago we faced with the issue that is not possible to perform swap anymore: 

Error: Conflict - Cannot modify this site because another operation is in progress. Details: Id: f98f19e2-fda0-47d5-8703-241c85d1aa01, OperationName: SwapSiteSlots, CreatedTime: 9/20/2019 11:04:18 AM, WebSystemName: websites, SubscriptionName: 000000000-1739-4b9f-bdbb-44be09dc35a2, WebspaceName: platform-WestEuropewebspace, SiteName:  platform-api, SlotName: staging, ServerFarmName: , GeoOperationId: (null) (CODE: 409)

![image](https://user-images.githubusercontent.com/15476934/65322990-87bfe680-dba8-11e9-9b25-90add64044c9.png)

manual swap via portal gives detailed error: 
![image](https://user-images.githubusercontent.com/15476934/65323175-f56c1280-dba8-11e9-8801-2a36cf1a9ca9.png)

**Comment by sugarjig** [comment]
I have also run into the same issue. I deploy the app to a staging slot using the "Azure App Service deploy" task, then try to use the "Azure App Service manage" task with the "Start Swap with Preview" action. I get the same error: `Error: Conflict - Cannot modify this site because another operation is in progress.`.

**Comment by chperich** [comment]
This must have been an intermittent issue with Azure app service which is resolved now. ([link](https://developercommunity.visualstudio.com/content/problem/467024/devops-portal-is-showing-slot-swap-as-failed-even.html)).
