### ISSUE TITLE
Custom name parallel tests

### ISSUE THREAD

**Issue by apobekiaris** [microsoft/azure-pipelines-tasks#11386]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VsTest  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=3445

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I am on a parallel test execution per assembly and I would like to custom name the Test1, Test2, etc using the related assembly name.

![image](https://user-images.githubusercontent.com/159464/65343133-f74fc900-dbdc-11e9-87d7-88616ed4e3a3.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by kaadhina** [comment]
Thank your feedback. The name is based on the phase name configured in the pipeline and not from the test task (which is just one of the many tasks potentially present in the phase) Today there isn't a way to let the pipeline know which of those tasks and for that task to custom configure this based on how the task behaves and unfortunately this is not high on our priority right now.
