### ISSUE TITLE
AppCenterDistribute: Possibly wrong hardcoded link

### ISSUE THREAD

**Issue by adriansuhov** [microsoft/azure-pipelines-tasks#11424]
Hi,

I tried to use this task but I got 404 error. Looking into debug info, i can see that from the pipeline the link i got is this:
`https://appcenter.ms/orgs/XYZ/apps/XYZ/release_uploads`
XYZ - hidden by me
And indeed, when accessing the above link from the browser, i got a 404 error. However, getting to the link via the web page, i'm getting to this link:
`https://appcenter.ms/orgs/XYZ/apps/XYZ/distribute/releases`

So we have **release_uploads** vs **distribute/releases**.
Is it possible that the link has changed in the last few months in App Center and the azure task wasn't updated meanwhile? The hardcoded code is here:
https://github.com/microsoft/azure-pipelines-tasks/blob/699a04b379aeb120a55debd49cb355ee408566a6/Tasks/AppCenterDistributeV3/appcenterdistribute.ts#L97

Thank you!

**Comment by pr0gg3r** [comment]
Same problem here...

**Comment by Capellio** [comment]
Same problem...

**Comment by paulw11** [comment]
I have this too.  Does anyone know if it is possible to fork this repo and then use the fork in the Azure DevOps environment - It looks like a trivial fix, but I can't see Microsoft addressing this any time soon

**Comment by MohamadMousheimish** [comment]
Same problem here, any solution?

**Comment by paulw11** [comment]
I found in my case I had an extra `/apps/` between the organisation name and the app name; the URL you see when you are in appcenter.ms is `orgid/apps/appid` but the slug needs to be `orgid/appid`

**Comment by yojanmorales** [comment]
Hey there!
Any solution?

**Comment by paulw11** [comment]
Did you check the value you have entered carefully as per my previous comment. This task works for me

**Comment by yojanmorales** [comment]
> Did you check the value you have entered carefully as per my previous comment. This task works for me

Works fine, thanks a lot

**Comment by Capellio** [comment]
> I found in my case I had an extra `/apps/` between the organisation name and the app name; the URL you see when you are in appcenter.ms is `orgid/apps/appid` but the slug needs to be `orgid/appid`

This is the answer
