### ISSUE TITLE
xUnit InlineData theories are not run when using parallel strategy (DTAExecutionHost)

### ISSUE THREAD

**Issue by bogdancucosel** [microsoft/azure-pipelines-tasks#11421]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest

## Environment
Azure Pipelines: uipath, Orchestrator, CI/506187: 

- Agent - Hosted: Windows Server 2016

## Issue Description

We have tests written in xUnit that use InlineData attribute in order to test different use cases.
We run the tests using the parallel strategy for jobs.
In the vstest execution logs we can see all test variants being discovered, but only the first variant is being run and reported.

For example, we can see them being discoverd:

`DiscoveryMessage : [xUnit.net 00:00:06.73] UiPath.Orchestrator.Web.Tests: Discovered test case 'UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit(robotType: Attended)' (ID = '18ab8dd645897913c5822fac1ca6db43eaada5f9', VS FQN = 'UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit')
DiscoveryMessage : [xUnit.net 00:00:06.73] UiPath.Orchestrator.Web.Tests: Discovered test case 'UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit(robotType: Development)' (ID = '9bb2388a04bd999bff42d337646ea8977e4c6bb6', VS FQN = 'UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit')
DiscoveryMessage : [xUnit.net 00:00:06.73] UiPath.Orchestrator.Web.Tests: Discovered test case 'UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit(robotType: StudioX)' (ID = '7f91e3265f99298d27071d517ffff3146bec54fb', VS FQN = 'UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit')
`

But only one is executed:

`Passed    UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit    UiPath.Orchestrator.Web.Tests.Licensing.LicensingTests.CreateConcurrentRobotOverTheLimit(robotType: Attended)
`

**Comment by bogdancucosel** [comment]
This did not happen for vstest.console.exe. we have older builds that were running these tests. But since last friday , all tests are being run with DTAExecutionHost

**Comment by kaadhina** [comment]
please share the full debug logs  for us to look into

**Comment by ShreyasRmsft** [comment]
@bogdancucosel closing this due to no response, please re-open with the full zip debug logs or a sample repro project on github and we can take a look. Thanks.
