### ISSUE TITLE
Visual Studio Test Platform Installer became slower due to change in nuget.org behaviour

### ISSUE THREAD

**Issue by mahalex** [microsoft/azure-pipelines-tasks#11425]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  VisualStudioTestPlatformInstaller

## Environment
- Server - Azure DevOps Server v2019.1

- Agent - Private, Windows Server 2012r2

## Issue Description

Since several days ago, "Visual Studio Test Platform Installer" task takes much longer time than previously. Logs show that this task calls
`nuget.exe list Microsoft.TestPlatform -NonInteractive -Source https://api.nuget.org/v3/index.json`
which gets a list of almost 20000 packages (most of them are by "NugetTestAccount", with names like `635273018963274013UploadAndDownLoadPackageWithMinClientVersion 1.0.0`, etc.).
Previously, the same request only returned 8 packages:
```
Microsoft.TestPlatform 16.3.0
Microsoft.TestPlatform.Build 16.3.0
Microsoft.TestPlatform.CLI 16.3.0
Microsoft.TestPlatform.Extensions.TrxLogger 16.1.0
Microsoft.TestPlatform.ObjectModel 16.3.0
Microsoft.TestPlatform.Portable 16.3.0
Microsoft.TestPlatform.TestHost 16.3.0
Microsoft.TestPlatform.TranslationLayer 16.3.0
```
As a result, what took 11 seconds now takes more than 9 minutes.
I guess this is related to the change in nuget.org's treatment of search queries.

**Comment by ShreyasRmsft** [comment]
@mahalex this was fixed in a later version. Take a look at the code here https://github.com/microsoft/azure-pipelines-tasks/blob/e6388b144537d1d80a468fbf39ccb47d2ca1c75c/Tasks/VsTestPlatformToolInstallerV1/nugetpackageversionhelper.ts#L19

Initially in the older versions we were looking for the package by name and I changed it to look for the package by Id  which should solve this issue.

If there is an update available to AzureDevopsServer that's one way to get this, otherwise you can get the latest source code from here, build the task and upload it. The docs for doing so are part of the repo's readme.

**Comment by mahalex** [comment]
@ShreyasRmsft thank you for the informative answer!
Unfortunately, this won't work for us, since we're not always using the default package source. We have our own locally hosted package source, and I can see from the code you posted that in this case it will still use lookup by name. I guess it makes sense, since the task has no way of knowing if the package source supports the "packageid:" search term. It seems that our only option then is to change the build definition to use the specific version of `Microsoft.TestPlatform` instead of the latest one.

**Comment by ShreyasRmsft** [comment]
@mahalex true. I guess it shouldn't be too much of an effort to manually update the version once in a while. However you could make a copy of the task and publish it to your account with a few code changes suited to quickly finding the latest version published to your custom feed. Assuming the solution of manually updating is too much of an overhead.

**Comment by mahalex** [comment]
@ShreyasRmsft right, thanks again!
