### ISSUE TITLE
Xcode Task: Provisioning profiles not included in ExportOptions.plist when exportOptions set to 'specify'

### ISSUE THREAD

**Issue by ChrisPearce** [microsoft/azure-pipelines-tasks#11438]
https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Xcode

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/XcodeV5

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted macOS
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The provisioning profiles are only included in the generated ExportOptions.plist file when exportOptions is set to 'auto'.

The provisioning profiles should also be included in the generated ExportOptions.plist when exportOptions is set to 'specify'

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ChrisPearce** [comment]
Is this issue still being investigated?

**Comment by nzcodarnoc** [comment]
Is this issue still being investigated?
