### ISSUE TITLE
Cryptic error when attempting to publish symbols to on-premises TFS

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#11435]
## Required Information

**Type**: **Bug**
**Enter Task Name**: **Index Sources & Publish Symbols**

## Environment
- Server - TFS on-premises?
    
    - If using TFS on-premises, provide the version: 17.143.28912.1

- Agent - Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Capability name | Capability value
-- | --
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.131.0

## Issue Description

Running the task results in the described error. Looking at the task code, the following execution flow emerges:

1. The code reaches https://github.com/microsoft/azure-pipelines-tasks/blob/c5de8d6beb30280eae54e6f0c2a17bb59ad98d92/Tasks/PublishSymbolsV2/PublishSymbols.ps1#L175-L177 and discovers that there is no account name, no PAT and Aad is not used. 
1. So, the code executes https://github.com/microsoft/azure-pipelines-tasks/blob/c5de8d6beb30280eae54e6f0c2a17bb59ad98d92/Tasks/PublishSymbolsV2/PublishSymbols.ps1#L19-L20, sending an unauthenticated request to the on-premises Azure DevOps server.

This is strange. I would expect it at least to pass `-UseDefaultCredentials`. As it is now, the request is aborted, which is totally expected.

In effect, it makes it impossible to publish symbols to the on premises Azure DevOps server.

### Task logs

[log_6_588891.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3655069/log_6_588891.zip)

### Error logs

`TF400813: Resource not available for anonymous access. Client authentication required. - Azure DevOps Server`

**Comment by gnimor** [comment]
I see the same issue on our on-premises instance

**Comment by johnterickson** [comment]
@MarkKharitonov  @gnimor 
Are these new builds that you are having trouble setting up or existing builds that were working break? If so, what was the change that triggered the failure?

**Comment by johnterickson** [comment]
FYI this is expected
```
2019-09-25T20:20:57.9148414Z ##[debug]ARTIFACTSERVICES_SYMBOL_ACCOUNTNAME (empty)
2019-09-25T20:20:57.9212102Z ##[debug]ARTIFACTSERVICES_SYMBOL_PAT (empty)
2019-09-25T20:20:57.9257497Z ##[debug]ARTIFACTSERVICES_SYMBOL_USEAAD (empty)
```

Those are only for overriding the default of token provided to the build agent:
```
            $Endpoint = Get-VstsEndPoint -Name "SystemVssConnection"
            [string]$PersonalAccessToken = $Endpoint.Auth.Parameters.AccessToken
```

It looks like the location service used to allow for anonymous access and now doesn't?
e.g. in hosted this doesn't require auth: https://buildcanary.visualstudio.com//_apis/servicedefinitions/locationservice2/951917ac-a960-4999-8464-e3f0aa25b381
```
{"serviceType":"LocationService2","identifier":"951917ac-a960-4999-8464-e3f0aa25b381","displayName":"SPS Location Service","relativeToSetting":"fullyQualified","description":"","serviceOwner":"00000000-0000-0000-0000-000000000000","locationMappings":[{"accessMappingMoniker":"HostGuidAccessMapping","location":"https://app.vssps.visualstudio.com/A54d02617-2ebd-42b0-b1e2-257059c4c03d/"}],"toolId":"Framework","parentServiceType":"LocationService2","parentIdentifier":"a5ca35eb-148e-4ccd-bbb3-d31576d75958","properties":{}}
```

**Comment by MarkKharitonov** [comment]
Well, the anonymous does not work for on-premise. However, I do not understand why even try anonymous. If there is no account name, no token and no AAD, then it must be an on-premise installation. If so, the `-UseDefaultCredentials` makes much more sense, then `-UseBasicParsing`.

**Comment by gnimor** [comment]
Hmm, any idea for fix or a workaround. Currently it is not possible with an On-Premises setup to publish the symbols to the server? This is really a show stopper because we do not want to use a file share for storing the symbols.

**Comment by SamGrantham** [comment]
After I tested replacing -UseBasicParsing with -UseDefaultCredentials in a test environment there is an additional error downstream of this...

https://stackoverflow.com/questions/52066165/tfs-2018-update-2-failure-using-vsts-symbol-server

>“A symbol server is available with Package Management in **VSTS** and works best with Visual >Studio 2017.4 and newer. **Team Foundation Server users and users without the Package >Management extension can publish symbols to a file share using this task.”**


The official documentation link is here: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops#q-is-this-available-in-tfs

The authorization error is not expected but it also does not change the behavior of the task. I also noticed that the task itself does call this out, though the documentation link it refers to is broken:
 
![task note](https://user-images.githubusercontent.com/36972300/74953883-e0014b80-53c7-11ea-8714-249e5c2ffbc5.png)

It's possible I'm wrong I am wrong, but it seems as thought if you want to use **this** task to publish to the server you need to be on Azure DevOps Service.

**Comment by MarkKharitonov** [comment]
We use a file share. The on-prem Azure DevOps Server is a bastard brother of the hosted. Those customer who made the mistake of going with TFS **before** the hosted version was even born are now screwed up capitally. The hosted version is constantly updated with goodies, while we get the bugs. This is a source of great frustration.

**Comment by MarkKharitonov** [comment]
Is there any progress on this bug? Should I open a Microsoft Support case to attract attention? Or maybe spam my entire organisation begging for developers to upvote this issue? Can the poor folks stuck with on-prem get some loving finally?

**Comment by petrciml** [comment]
I see the same issue on our on-premises instance too

**Comment by lg2de** [comment]
I faced this problem on on-premises too.
Is there any work-around?

**Comment by JunielKatarn** [comment]
Same issue here.
Is there at least a workaround?

**Comment by JunielKatarn** [comment]
@arunkm You seem like the maintainer of this feature.
Can you please comment?

**Comment by jharlanhorn** [comment]
We also have the same issue with our 2019 on prem and it is deeply frustrating and unfortunate.

**Comment by Mobrockers** [comment]
@arunkm @johnterickson  ping

**Comment by johnterickson** [comment]
This "symbol server on-prem" is marked as closed on the feature request section of developer community. https://developercommunity.visualstudio.com/idea/365919/tfs-symbol-server.html

I'll leave this issue open as an ask to have a clearer error and docs.

**Comment by Mobrockers** [comment]
> This "symbol server on-prem" is marked as closed on the feature request section of developer community. https://developercommunity.visualstudio.com/idea/365919/tfs-symbol-server.html
> 
> I'll leave this issue open as an ask to have a clearer error and docs.

Well if this is not actually supported on azure devops server I would expect that the built-in task for it doesn't actually give you the option to try this. Not just that the error message is non-cryptic.

It would also be great to have some more 'official;  confirmation that this is not supposed to work because for your one developer community ticket that is closed as won't fix I have at least one other developer community ticket that is closed as Fix released for example.

I also pinged azure devops about this on twitter and they said this was being looked into so it could be resolved: https://twitter.com/AzureDevOps/status/1352008338914111488

**Comment by hangy** [comment]
> Well if this is not actually supported on azure devops server I would expect that the built-in task for it doesn't actually give you the option to try this.

Agreed. But Azure DevOps Server 2020 also let's you add some pipeline artifacts related tasks, that only work in Azure DevOps Service, and when you create a new YAML pipeline from the templates, most of them use something like `pool: ubuntu-latest`, ie. they'd only work in the cloud version. There seems to be more than one thing that Azu DevOps Server 2020 should allow us to try, because it should know that the variant is only available in Azure DevOps Services.

**Comment by JunielKatarn** [comment]
This issue doesn't seem to be resolved. Why was it closed?

**Comment by GregoryOtt** [comment]
@MarkKharitonov can you reopen this issue as no answer has been provided?

**Comment by MarkKharitonov** [comment]
I do not have the reopen button. It is to create it from scratch. I would not bother, they seem to ignore our issues anyway...
