### ISSUE TITLE
Post-deploy task for AzureRmWebAppDeploymentV4 does not work with WEBSITE_RUN_FROM_PACKAGE=1 setting

### ISSUE THREAD

**Issue by ustun** [microsoft/azure-pipelines-tasks#11440]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4  

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Devops

- Agent - Hosted or Private: Private / Ubuntu

## Issue Description

When deploying to App Service, we want to run some post-deployment scripts. We are using the WEBSITE_RUN_FROM_PACKAGE=1 flag for faster delivery. However, when we enable that, even though our app works, the app zip is not mounted to /home/www/siteroot in Postdeploy stage. 

I verified this by running ls in /home/www/siteroot folder as part of the postdeploy script and the only file there seems to a `hostingstart.html` file.

### Task logs

```
2019-09-26T19:10:25.6226058Z Successfully deployed web package to App Service.
2019-09-26T19:10:25.8910039Z Updating App Service Application settings. Data: {"SCM_COMMAND_IDLE_TIMEOUT":"1800"}
2019-09-26T19:10:26.5686845Z Updated App Service Application settings and Kudu Application settings.
2019-09-26T19:10:27.1152526Z Executing given script on Kudu service.
2019-09-26T19:10:27.8793087Z Standard output from script: 
2019-09-26T19:10:27.8793258Z hostingstart.html (Output of `ls`)
2019-09-26T19:10:27.8793373Z /home/site/wwwroot (Output of `pwd`, to ensure we are in the right folder)

```

**Comment by ustun** [comment]
I think the issue lies in Kudu, because as an alternative, I tried to run our post-deploy script with Kudu's REST API, however was not able to do that since the filesystem observed with Kudu is as if WEBSITE_RUN_FROM_PACKAGE=1 is not in effect.

See https://github.com/projectkudu/kudu/issues/3041 on Kudu repo.

**Comment by SumiranAgg** [comment]
Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.
Reference doc: https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package

**Comment by ustun** [comment]
Thanks for the response @SumiranAgg 

In this case, I'm not trying to write anything, I just want to read the contents so that I can execute some scripts that write to the db hosted on Azure MySQL. The issue is the output of `ls` shows as if the .zip file is not mounted to wwwroot.

Do you have any ideas what might be wrong? Kudu seems to see things from a different lens from App Service when that flag is set.

**Comment by SumiranAgg** [comment]
@ustun I am closing this thread, as you have already taken it up on kudu GitHub issues, which is the right place for the same.
Please feel free to re-open if required.
