### ISSUE TITLE
How to tell which tests failed when scaled to multiple agents

### ISSUE THREAD

**Issue by apobekiaris** [microsoft/azure-pipelines-tasks#11445]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=3566

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

After I scaled my tests to multiple agents it is not possible to tell which one failed.
https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=3566

all agents fail even if only one has the failed tests and at the end of the log there is this message.
```
Please use this link to analyze the test run : https://dev.azure.com/***DevOps/***Framework/_TestManagement/Runs#_a=resultQuery&runId=1000664&queryPath=Recent+Run%2FRun1000664
```

I do not understand why it has to hide with asterisk parts of this link but even if I manually update it to :

https://dev.azure.com/eXpandDevOps/eXpandFramework/_TestManagement/Runs#_a=resultQuery&runId=1000664&queryPath=Recent+Run%2FRun1000664

I get a 404 page not found error.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by kaadhina** [comment]
Hi, the task (on all agents) fail based on the test run passing/failing. You can find the reporting under the tests tab.
![image](https://user-images.githubusercontent.com/11773114/65953727-2f1f0200-e462-11e9-8514-c2870f3baee0.png)
It will have a detailed report of what tests passed and what failed
![image](https://user-images.githubusercontent.com/11773114/65953770-42ca6880-e462-11e9-8fbf-88404fb07995.png)
