### ISSUE TITLE
PublishBuildArtifacts task - Robocopy: Additional File copy parameters are not applied

### ISSUE THREAD

**Issue by JustinSchneiderPBI** [microsoft/azure-pipelines-tasks#11451]
*Type*: Bug

**Enter Task Name**: 
PublishBuildArtifacts

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishBuildArtifactsV1

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
PowerBI.visualstudio.com\Power Query
any build. Example build:
https://powerbi.visualstudio.com/Power%20Query/_build/results?buildId=1311989

- Agent- Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Win 8\8.1

## Issue Description

We had a problem with overwrite recently, where 2 different build definitions incorrectly pointed to the same share. This caused a significant amount of duplicated work for a number of people, so the followups are rather important. In addition to correcting the destinations, we're preventing future misconfigurations by blocking overwrite of files. I added additional file copy parameters to exclude files that are either newer or older or different and to apply readonly setting in windows: /XC /XO /XN /A:+R. However, these settings were not applied. Please fix this.

### Task logs
##[section]Starting: Publish build
==============================================================================
Task         : Publish build artifacts
Description  : Publish build artifacts to Azure Pipelines or a Windows file share
Version      : 1.158.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
##[command]robocopy.exe /E /COPY:DA /NP /R:3 /MT:8 "F:\Agent\_work\70\s\bin\x86\Release" "\\BIES-PQO2-FS01\TFS\Official\CloudSigned-OneMSI-RS\rs1msi\20190926.1.DRAFT\Win32\Release" "*"

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows                              
-------------------------------------------------------------------------------

  Started : Thursday, September 26, 2019 11:24:50 PM
   Source : F:\Agent\_work\70\s\bin\x86\Release\
     Dest : \\BIES-PQO2-FS01\TFS\Official\CloudSigned-OneMSI-RS\rs1msi\20190926.1.DRAFT\Win32\Release\

    Files : *
	    
  Options : /S /E /DCOPY:DA /COPY:DAT /NP /MT:8 /R:3 /W:30 

------------------------------------------------------------------------------

	  *EXTRA File 		     353	\\BIES-PQO2-FS01\TFS\Official\CloudSigned-OneMSI-RS\rs1msi\20190926.1.DRAFT\Win32\Release\C...
	    New File  		  766335	F:\Agent\_work\70\s\bin\x86\Release\C...
	    Newer     		    3072	F:\Agent\_work\70\s\bin\x86\Release\Bin...
	    Newer     		    3072	F:\Agent\_work\70\s\bin\x86\Release\Bin...
	    Newer     		    3106	F:\Agent\_work\70\s\bin\x86\Release\Bin...
	    Newer     		    3106	F:\Agent\_work\70\s\bin\x86\Release\Bin...
	    Newer     		    3018	F:\Agent\_work\70\s\bin\x86\Release\Bin...
	    Newer     		    3018	F:\Agent\_work\70\s\bin\x86\Release\Bin...

## Troubleshooting
None, there's no error, just ignored options

### Error logs

N\A

**Comment by radujipa** [comment]
Has there been any progress here and timeline to fix?

I am encountering the same issue where '/xf' is not being applied.

**Comment by pr-hasomed** [comment]
Not an additional parameter, but the default "/E" in the parameter list is also not documented...

**Comment by BenVillalobos** [comment]
+1 on not being able to pass args to robocopy.

**Comment by Kamiljen** [comment]
Another +1 on not being able to pass args to robocopy

**Comment by ChristoWolf** [comment]
Same for me, options seem to be ignored.

**Comment by DavidUrting** [comment]
Also an issue for me, I would like to exclude a specific directory with the **/XD option**.

**Comment by JustinSchneiderPBI** [comment]
Thanks, anatolybolshakov. Any luck?

**Comment by amsga** [comment]
Encountered the same problem on Azure DevOps Server 2020.1.1

**Comment by ChristoWolf** [comment]
Not sure why the bot closes this as completed, seeing there wasn't an actual implementation.
Can this please be reopened?

**Comment by JustinSchneiderPBI** [comment]
The bot happened to pick a week I was on vacation to mark as stale and close. Many people are clearly interested in a fix for this issue. Please re-open this so others don't need to work around it or re-file the issue.
