### ISSUE TITLE
iot edge deploy Additional properties are not allowed 

### ISSUE THREAD

**Issue by baywet** [microsoft/azure-pipelines-tasks#11450]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdge  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: senseai, DataPipeline, Agent 1114 (and 1102 for the one that was working before)

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 16
## Issue Description

Azure IoT Edge deployment task fails with error message `Additional properties are not allowed `

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
Can't provide error logs as they expose secrets, however I was able to narrow down the issue in the azure cli iot edge extension and created an issue over there as well https://github.com/Azure/azure-iot-cli-extension/issues/100
The goal of this issue is to provide visibility for people using the tasks as well as to coordinate follow up when the issue is resolved in the extension

**Comment by blackchoey** [comment]
Hi @baywet thanks for reporting this issue. The task will use the latest version of Azure CLI IoT extension to do deployment. So no further changes is required to the IoT Edge task.
I saw Azure CLI IoT extension already released a new version that resolves https://github.com/Azure/azure-iot-cli-extension/issues/100. Could you let us know whether you still met errors in the IoT Edge task?

**Comment by baywet** [comment]
hi @blackchoey 
Thanks for the follow up.
I spent some time testing this again. The CLI extension has the issue fixed. However the task doesn't seem to leverage the latest version of the cli extension.
new build id 1159

**Comment by baywet** [comment]
disregard the last comment, my test was flaky, running it again and keeping you updated

**Comment by baywet** [comment]
confirmed, the problem was fixed with cli extension 0.8.3, no action needed for the task. Thanks!
