### ISSUE TITLE
Build can't find variable because it is not defined

### ISSUE THREAD

**Issue by sturlath** [microsoft/azure-pipelines-tasks#11469]
I have the following code in my Script.PostDeployment.sq (DatabaseProject)

`SELECT @solutionDir = REPLACE('$(SolutionPath)','MySoulution.sln','');`

There I'm getting the absolute path to the solution (and using it in another place).

This **works like a charm** when I publish locally. But when I run azure build it fails and I get the following error

`SCRIPT.POSTDEPLOYMENT.SQL(17,32,17,32): Build error SQL72008: Variable SolutionPath is not defined.`

$(SolutionPath) was the only [macro](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=vs-2019) I could get to work locally and now I can't find out what I could swap it out with.

Any ideas?

**Comment by sturlath** [comment]
This is still a problem so I created a [question on StackOverflow](https://stackoverflow.com/questions/58183392/azure-devops-build-cant-find-variable-because-it-is-not-defined). Unfortunately no one has answered that one either...

**Comment by robbileifss** [comment]
Hi,
I'm having the same problem here

**Comment by sturlath** [comment]
Did I post this to a wrong chanel? Is there a better place for this? I can't seem to find a "Visual Studio database project" repository on Github to post this to.

**Comment by damccorm** [comment]
Hi, sorry for the slow response - would you mind opening this issue in https://developercommunity.visualstudio.com/spaces/21/index.html - that's the best place to ask non-task specific questions about Azure Devops since this repo is dedicated mostly to tasks
