### ISSUE TITLE
AdditionalArgumentsForBlobCopy to set Cache-Control property

### ISSUE THREAD

**Issue by skamoda** [microsoft/azure-pipelines-tasks#11466]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure file copy

## Environment
- Server - Azure Pipelines

- Agent - Hosted VS2017

## Issue Description
I know there was a question in related issue: #2395. 
But I would like to ask what should be given in `Optional Arguments (for uploading files to blob)` or `additionalArgumentsForBlobCopy` to set `Cache-Control` (for example to `no-cache`)

**Comment by arjgupta** [comment]
Hi @skamoda , we use azcopy tool to copy files to blob. The additional arguments input is arguments that are passed to azcopy to modify it's behaviour. The [az copy github repo](https://github.com/Azure/azure-storage-azcopy) will be the right place to answer your query.

**Comment by skamoda** [comment]
Thanks for reply
According to documentation and example I pass `--cache-control=no-cache` but I get errors like that:
`[ERROR] The syntax of the command is incorrect. The option "--cache-control=no-cache" is not recognized.`

**Comment by dpolivy** [comment]
The current task is using the legacy AzCopy v8, which does not support. AzCopy v10 does, however, but it seems the task is not planning on updating to support it. There's a separate issue tracking that #9157, you may want to voice your support there.
