### ISSUE TITLE
DotNetCoreCLIV2 - Custom command, path needs to be absolute

### ISSUE THREAD

**Issue by kiwidave72** [microsoft/azure-pipelines-tasks#11460]
Im having issues with the passing the path of the .dll that i want to run.
based on my testing the only way i can get the dotnet to run is to pass the complete full path of the .dll or dotnet cannot find the file.
is there a work around for this as i dont want full path names in my pipelines.

**Comment by dikhakha** [comment]
@kiwidave72 Can you elaborate on your scenario ? Suggested way to run dotnet application is to use dotNetCore task with command build, followed by run command where you can pass path/pattern to your csproj. If you are directly trying to run an existing application dll without any build process then you need to provide absolute path to the dll like dotnet <path_to_dll>

**Comment by hbunjes** [comment]
We have a similar issue since version 2.158.0 (shown in header of tasks) with the tests. Before, the parameter "-s" for "dotnet test" points to the solution folder and no longer to the folder where the csproj is located at. With version 2.156.2 it was working.

**Comment by kiwidave72** [comment]
> @kiwidave72 Can you elaborate on your scenario ? Suggested way to run dotnet application is to use dotNetCore task with command build, followed by run command where you can pass path/pattern to your csproj. If you are directly trying to run an existing application dll without any build process then you need to provide absolute path to the dll like dotnet <path_to_dll>

I have a .net 3.0 core console app that i use in the pipeline.

my "Custom command" is something like the following:
C:\Users\buildagentadmin\agent\_work\r1\a\_Pipeline\Tools\ProductHelper\AzureFileSync.Console\bin\Release\netcoreapp2.1\AzureFileSync.Console.dll

And when i try using variables from the pipeline 'dotnet' errors and cant find the dll.

**Comment by dikhakha** [comment]
@kiwidave72 You can use pipeline variables in your custom command. Example: $(System.DefaultWorkingDirectory)\<artifact alias>\<path to dll>. Can you please share the logs for the instance when you tried to use pipeline variables ?

**Comment by dikhakha** [comment]
@hbunjes Can you share the debug logs for both successful and failed scenarios ?

**Comment by tejasd1990** [comment]
Hi @hbunjes , can you shared the logs as asked earlier?

**Comment by vinodkumar3** [comment]
@kiwidave72 @hbunjes 
If you are still facing this scenario, feel free to reopen this issue item along with debug logs. To generate debug logs, set this variable "system.debug: true" before executing your pipeline.
