### ISSUE TITLE
Variable endpoint is not working

### ISSUE THREAD

**Issue by ANTPro** [microsoft/azure-pipelines-tasks#11470]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug
**Enter Task Name**: SshV0

## Environment
- Server - Azure Pipelines 
- Agent - Private: Linux

## Issue Description

1. Nobug:
```
variables:
Server: $[dependencies.Name.outputs['SetVariableJob.Server']] #Value = Server1
- task: SSH@0
  inputs:
  sshEndpoint: '${Server}' #Value = Server1
  runOptions: inline
  inline: 'echo ${Server}' #Value = Server1
```
2. Bug:
```
variables:
Server: $[dependencies.Name.outputs['SetVariableJob.Server']] #Value = Server2
- task: SSH@0
  inputs:
  sshEndpoint: '${Server}' #Value = Server1
  runOptions: inline
  inline: 'echo ${Server}' #Value = Server2
```

## Troubleshooting
This is not task bug. Bug in Azure DevOps(bad setting parameter).

**Comment by ANTPro** [comment]
[Ex info](https://github.com/MicrosoftDocs/vsts-docs/issues/5790)

**Comment by anatolybolshakov** [comment]
@jankytay at the moment you can't use variables as a value of service connection. This limitation is not related to the task itself - if you want to use variables anyway here, could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?
