### ISSUE TITLE
VSTestV2 shows settings file content in logs and fails with relative paths in settings file

### ISSUE THREAD

**Issue by lopeg** [microsoft/azure-pipelines-tasks#11479]
## Note  
After update from 2.157.3 to 2.157.4 two changes took place:
- Task started exposing settings file content (which contains sensitive data) to log output.
   There was no output in 2.157.3
- Relative paths in settings file are concatinated to %APPDATA%\Local\Temp
  Earlier IT was concatenated to %Build.SourcesDirectory%

## Required Information
**Question, Bug, or Feature?**:  Bug
**Enter Task Name**: VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV2

## Environment
Azure Pipelines: 
https://dev.azure.com/FalckGlobalIT/FAN%20BI/_build/results?buildId=14094&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b

Agent:
Private
Agent.OS: Windows_NT
Agent.OSVersion: 10.0.14393
Agent version: 2.155.1

## Issue Description

After update from 2.157.3 to 2.157.4 two changes took place:
- Task started exposing settings file content (which usually contains sensitive data) to log output.
   There was no output in 2.157.3
- Relative paths in settings file are concatinated to %APPDATA%\Local\Temp
  Earlier IT was concatenated to %Build.SourcesDirectory%

**Comment by aatif912** [comment]
I am facing the same issue from couple of days. Appreciate if someone can have a look on this. Thanks !

**Comment by aatif912** [comment]
I am also facing the same issue from couple of days. Appreciate if someone can have a look on this. Thanks in advance !

**Comment by kaadhina** [comment]
Hi can you please share full debug logs from before and after the behaviour change?

**Comment by lopeg** [comment]
@kaadhina hello
Unfortunately i have no debug logs "from before" as i can not revert to old version and had no runs with debugs
Please fine attached logs: "before_debug_false.log" and "after_debug_true.log"
[after_debug_true.log](https://github.com/microsoft/azure-pipelines-tasks/files/3685832/after_debug_true.log)
[before_debug_false.log](https://github.com/microsoft/azure-pipelines-tasks/files/3685833/before_debug_false.log)

As you can see in "after_debug_true.log"  in line 655 new task outputs all settings to logs[](url)

**Comment by ShreyasRmsft** [comment]
@lopeg you will need to create your the params you want to mask as secret variables. (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#secret-variables)

If this is done the agent will mask these values when logging them. You can put dummy placeholder values in the runsettings and use the override test run params input in the task to override them at run time.

**Comment by lopeg** [comment]
@ShreyasRmsft imho, this sounds like workaround
I am already using securefiles - native azureDevops functionality - to keep whole content.
And it worked smoothly, untill task started posting the whole content of config file to  logs.
i think, this should be fixed, but not using workaround with secrets overriding content from secret file

**Comment by ShreyasRmsft** [comment]
The reason we log the settings file is that there are a lot of issues that have come up where we needed the settings file and the updations we do to it to be logged to get the RCA.

But i hear your concern and i will make the change to not log the values of the params we are overriding. Please do use the workaround until i can make the changes and release a new task version.

Thank you for reporting this.

**Comment by lopeg** [comment]
Variable "debug" exists for this purpose. 
Can you fix it please, to expose settings file content only if debug us true, but not every normal run?
Thank you

**Comment by ShreyasRmsft** [comment]
Will do.  If you notice the test run params section of runsettings are not logged as part of the printed runsettings already. Where you are seeing the values get displayed is in the log line that says overriding parameter with value ....

I will let you know as soon as the fix is out.

**Comment by ShreyasRmsft** [comment]
This has been fixed in task version 2.159.x and rollout has started and should reach all accounts in a few days. Please re-open if the issue still persists for you after getting the task version 2.159.x
