### ISSUE TITLE
PublishTestResults doesn't publish with release 1.0.43 on 9/13 and 9/25

### ISSUE THREAD

**Issue by lhfiedler** [microsoft/azure-pipelines-tasks#11471]
Our builds stopped publishing our trx test results on 9/13 (1.0.43) with the updates to PublishTestResults.  9/25 update didn't work either. We are seeing the warning:
##[warning]Failed to publish test results: The given path's format is not supported.

When diffing the updates to the PublishTestResults.ps1 changes wih 1.0.43, I imagine it has to do with these changes:

        # There's a Null reference exception introduced in the agent 2.138 until 2.138.4 and hot fixed in 2.138.5.
        # Hence falling back to Scripts to pulblish test results. If Agent version falls between 2.138 .. 2.138.4
        if (!$agentVersion -or (($agentVersion -ge [version]"2.138") -and ($agentVersion -le [version]"2.138.4"))) {
            $switchToPowerShell = "true";
        }

...
Various switches around this new boolean:

                if ($switchToPowerShell -ieq "true") {
                    Publish-TestResults -TestRunner $testRunner -TestResultsFiles $matchingTestResultsFiles -MergeResults $mergeResults -Platform $platform -Configuration $configuration -Context $distributedTaskContext -PublishRunLevelAttachments $publishResultsOption
                }
                else {
                    Write-Host "##vso[results.publish type=$testRunner;mergeResults=$mergeResults;publishRunAttachments=$publishResultsOption;resultFiles=$matchingTestResultsFiles;platform=$platform;config=$configuration;testRunSystem=$testRunSystem;]"
                }

Output of task below:

#[section]Starting: Publish Test Results c:/deployment/TestResults**/*.trx
==============================================================================
Task         : Publish test results
Description  : Publish test results to Azure Pipelines
Version      : 1.0.44
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?LinkID=613742)
==============================================================================
Preparing task execution handler.
Executing the powershell script: C:\agent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.44\PublishTestResults.ps1
##[warning]Failed to publish test results: The given path's format is not supported.

##[section]Async Command Start: Publish test results
##[section]Async Command End: Publish test results
##[section]Finishing: Publish Test Results c:/deployment/TestResults**/*.trx

**Comment by lhfiedler** [comment]
I enabled system.debug=true to get some more output.  Are the spaces in the trx filenames now throwing it off with it using Agent Command mode?

##[debug]Find-Files -SearchPattern c:\deployment\TestResults**\*.trx
##[debug]FindFiles.FindMatchingFiles(rootFolder = , matchPattern = c:\deployment\TestResults**\*.trx, includeFiles = True, includeFolders = False
##[debug]FindFiles.GetMatchingItems(includePatterns.Count = 1, excludePatterns.Count = 0, includeFiles = True, includeFolders = False
##[debug]FindFiles.GetMatchingItems - Found: c:\deployment\TestResults\test_BVT1 2019-09-30 23_41_29.trx
##[debug]FindFiles.GetMatchingItems - Found: c:\deployment\TestResults\test_BVT1 2019-10-01 00_48_04.trx
##[debug]FindFiles.FindMatchingFiles - Found 2 matches
##[debug]matchingTestResultsFiles = c:\deployment\TestResults\test_BVT1 2019-09-30 23_41_29.trx c:\deployment\TestResults\test_BVT1 2019-10-01 00_48_04.trx
##[debug]Invoke - Get-TaskVariable cmdlet
##[debug]Invoke - Get-TaskVariable cmdlet
##[debug]Agent Version: 2.134.2
##[debug]Using Agent Command to publish test results
##[debug]Calling Publish-TestResults
##[debug]Reading test results from file 'c:\deployment\TestResults\test_BVT1 2019-09-30 23_41_29.trx c:\deployment\TestResults\test_BVT1 2019-10-01 00_48_04.trx'
##[warning]Failed to publish test results: The given path's format is not supported.
##[debug]Processed: ##vso[results.publish type=VSTest;mergeResults=False;publishRunAttachments=True;resultFiles=c:\deployment\TestResults\test_BVT1 2019-09-30 23_41_29.trx c:\deployment\TestResults\test_BVT1 2019-10-01 00_48_04.trx;platform=;config=;testRunSystem=VSTS - PTR;runTitle=CompAnalytics BVTs;]

**Comment by navin22** [comment]
@lhfiedler I am able to repro it, and yes it started breaking after moving to agent command to publish the test results.

Can you please use the newer task version ? If there are any blockers, please let us know.

In case if you are still wanted to use the V1 - Add a variable to your pipeline/build like below
UsePowerShellScripts=true
