### ISSUE TITLE
Azure Pipelines: Not possible to select service connection when using ".NET Core Function App to Windows on Azure" task

### ISSUE THREAD

**Issue by sylwiaboguska** [microsoft/azure-pipelines-tasks#11486]
Hi,

I have noticed that, when building pipeline in Azure Pipelines using ".NET Core Function App to Windows on Azure" task, it is not possible to select service connection, only subscription. This creates problems because the user needs to have "Owner" or "User Access Administrator" permissions on the Subscription to be able to authorize the connection. Is there a plan to add Service Connection option to this task in the future?

Thanks,
Sylwia

**Comment by chperich** [comment]
@sylwiaboguska: Unfortunately we don't have a plan to support showing service connections yet. But we will evaluate this request and add it to our backlog if there is value in supporting it. 

Please find the template for ".NET Core Function App to Windows on Azure" [here](https://github.com/microsoft/azure-pipelines-yaml/blob/master/templates/asp.net-core-functionapp-to-windows-on-azure.yml). For now, you can manually edit the subscription inputs to point to appropriate service connection.
