### ISSUE TITLE
Older versions of the test platform and no tests were found

### ISSUE THREAD

**Issue by gertvdh** [microsoft/azure-pipelines-tasks#11485]
originated from 

https://developercommunity.visualstudio.com/content/problem/690316/vstest-task-behavior-change.html
and https://developercommunity.visualstudio.com/content/problem/754407/visual-studio-test-tasks-fails-when-no-tests-to-ex.html

When you are using an older version of the test platform, in our case visual studio 2015, the vs test task fails when no tests are detected. It used to just log it and continue. In our case we cannot move to a newer version since the test tools for our platform (Dynamics Finance and Operations) are only supported on Visual studio 2015 for now.

So we would love the same behaviour back in place for older versions of the test platform.

**Comment by kaadhina** [comment]
This was an intended change but based on feedback we are considering making a change in behaviour. We are already tracking this in our backlog. But please do note that we pick items from backlog based on priority.

**Comment by gertvdh** [comment]
I did not know DevOps is doing breaking changes without announcing them? This breaks 20 of our build definitions or so,  very dissappointed with that.

**Comment by kaadhina** [comment]
Hi, my understanding is that this is not a blocking issue. The test are not discovered and the task fails as opposed to passing. Tests not being discovered for a task configured to run tests is unexpected and hence is being treated as failure.

**Comment by gertvdh** [comment]
I understand why this is done, but it used to not fail, and now it does, that is a breaking change I would believe

**Comment by gertvdh** [comment]
As a workaround we added 1 test and set them to inactive

**Comment by ShreyasRmsft** [comment]
@gertvdh we have made a fix to ensure that using an older version of the testplatform will not cause a failure when no tests are discovered. This should get deployed to all accounts in a couple of days

**Comment by gertvdh** [comment]
Thanks for that!
