### ISSUE TITLE
DownloadPackagesV1 may report success, even if the download fails

### ISSUE THREAD

**Issue by phil-hodgson** [microsoft/azure-pipelines-tasks#11489]
## Required Information
**Question, Bug, or Feature?**  Bug
*Type*: Error handling
**Enter Task Name**: DownloadPackagesV1

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

## Issue Description
Customer reported that in a build, the actual download failed with a message "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to extract package with error Error: Could not find the End of Central Directory Record", _but_ the task still completed without error.

The task needs to handle, and correctly report errors in the download promise.

Additionally, add some debug logging before and after the `download`/`process` calls

**Comment by andschwa** [comment]
Just chiming in that I saw this on 1/2/2020 too:

> (node:8376) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Fetching package metadata using url ... Get failed with error Error: 404: null

It obviously failed, but the task "completed successfully."

**Comment by brandonmcclure** [comment]
I am seeing this as well today for the following error:

`(node:9820) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to download package file from **** got the following error: Error: 400: Bad Request`
