### ISSUE TITLE
KubernetesManifest task failing on canary deployment with Helm chart

### ISSUE THREAD

**Issue by yelob** [microsoft/azure-pipelines-tasks#11498]
**Note**
https://github.com/microsoft/azure-pipelines-tasks/blob/86a104c469fb62fb3e14915414f58d939973a8ed/Tasks/KubernetesManifestV0/src/utils/CanaryDeploymentHelper.ts#L54

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest@0 
**Environment**: 
Server: Azure Pipelines
Agent: Hosted

**Issue Description**
While testing the KubernetesManifest@0 task with a Helm chart, I was getting an error that was hard to trace down:

`##[error]Cannot read property 'metadata' of null`

As part of my Helm chart, I have an ingress.yaml with the following condition at the top:

`{{- if .Values.ingress.enabled -}}`

In my test application, I had this set to false, so the ingress itself was not rendered into the chart. However, Helm stills renders a section in the baked manifest like so:

```
<snip deployment manifest>
---
# Source: /path/to/ingress.yaml
```

This is still a valid manifest and deploys correctly via kubectl, but the code above failed because this "empty" definition does not have any metadata.

**Comment by shigupt202** [comment]
@yelob There have been some code changes in the task since the issue was raised. Can you please try to execute the pipeline again, because I am not facing any such issue.

**Comment by yelob** [comment]
This error still occurs for me.

**Comment by shigupt202** [comment]
@yelob I'm sorry, I was testing it with the latest code which is not deployed yet. Please wait for a few more days for the new deployment with the changes to rollout. If you want an immediate fix or a timeline by which the new deployment will be rolled out to your ring, you can share your account information on RM_Customer_Queries@microsoft.com.
