### ISSUE TITLE
npmAuthentication task fail randomly

### ISSUE THREAD

**Issue by memao** [microsoft/azure-pipelines-tasks#11490]
Type: Bug
Task Name: NPM Authenticate
Server: Azure Pipelines
Agent: Hosted windows 2019

The authentication for a registry outside of our org goes wrong randomly.

On azure hosted agents, we are using npm authentication task and npm service connection to do the authentication. Normally, if things goes right, this step would find the correct username and password for the feed. However, randomly, this step gets back a authToken. The npm ci step get 401 for that feed when this happens.

The .npmrc file usually get:
//pkgs.dev.azure.com/xxx/_packaging/xxx/npm/registry/:username=VssToken
//pkgs.dev.azure.com/xxx/_packaging/xxx/npm/registry/:_password=***
//pkgs.dev.azure.com/xxx/_packaging/xxxx/npm/registry/:email=VssEmail
//pkgs.dev.azure.com/xxx/_packaging/xxx/npm/registry/:always-auth=true

Randomly we get this instead
//pkgs.dev.azure.com/xxx/_packaging/xxx/npm/registry/:_authToken=***
//pkgs.dev.azure.com/xxx/_packaging/xxx/npm/registry/:always-auth=true

When the above is listed in the .npmrc, the npm ci step after that shows error: "npm http fetch GET 401" for the feed we try to reach.

Why does this happen? How do I fix it?

**Comment by zleight1** [comment]
We’re seeing this as well, it seems to happen randomly when providing PAT credentials but using the repos .npmrc.

**Comment by edgarrs** [comment]
@memao , @zleight1 are you still seeing this issue?

**Comment by zleight1** [comment]
> @memao , @zleight1 are you still seeing this issue?

I haven't recently, but we added npmrc tokens to the agent home directories themselves because this was happening sometimes.

We're working on auto-scaling agents, so for these I will not put a token in ~/ and see if it happens with them.

**Comment by herenhuang** [comment]
Good to know. Closing this for now. Please reopen if more issues pop up!
