### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by gpomykala** [microsoft/azure-pipelines-tasks#11508]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadSecureFileV1 / InstallSSHKeyV0   

## Environment
- TFS on-premises
    
    - If using TFS on-premises, provide the version: 

About Azure DevOps Server
Version Dev17.M153.3

- Agent - Hosted or Private: 
private Linux agent running Azure Pipelines agent v2.158
    
## Issue Description

Both tasks fail with infamous 'unable to get local issuer certificate'. server certificate is added to system-wide cert store - agent does not complain when connecting to the queue nor git complains when fetching sources.
I established that the source of an error is NodeJS bundled with Azure pipelines agent. 
For some reason it does not fetch system-wide SSL certificates, it seems to use cert store bundled with NodeJS only. 
It does not help that Azure Pipelines agent is bundled with NodeJS v6.10.3 - some additional SSL/TLS related configuration options were introduced in 6.11 and more recently in NodeJS v7 and above.

I found few workarounds that do work, but nothing that could last.

1. export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/etc/ssl/certs and run agent interactively with ./run.sh. This option still did not work for agent configured as service despite adding exports above to user profile

2. add the following at the beginning of bin/AgentService.js:
process.env.NODE_EXTRA_CA_CERTS='/etc/ssl/certs/ca-certificates.crt';
process.env.SSL_CERT_DIR='/etc/ssl/certs';

This will only last as long the agent will not be updated / reinstalled from server.

I am looking for a proper fix.

### Task logs
```
##[debug]Evaluating condition for step: 'Install an SSH key for tfsa'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Install an SSH key for tfsa
==============================================================================
Task         : Install SSH key
Description  : Install an SSH key prior to a build or deployment
Version      : 0.151.2
Author       : Microsoft Corporation
Help         : [More information](https://go.microsoft.com/fwlink/?linkid=875267)
==============================================================================
##[debug]agent.TempDirectory=/home/tfs-build-agent/agent2/_work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_HOSTNAME
##[debug]loading INPUT_SSHPUBLICKEY
##[debug]loading INPUT_SSHKEYSECUREFILE
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECUREFILE_TICKET_7e2886f1-72fd-4665-9534-59f2641a1447
##[debug]loaded 7
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]sshPublicKey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQ7dWn3DIdrnB5gam7mqu1h+WwcJEggXSzBL/vO61xynyqfG+v8Kzs/N1yMCTQqeUzbU6LqJImljfsrOoXNtM168vCG73WP+g+7pvziRPpLB5WKZlD8qV9wSZZYpxnd+rYI+5ZP84cS8PmimjXAaGKOEbI335rBboAdIpUNvoefJrGmb7+YzUozW3zQMcKLc0YoRc4GTYnZCh3B7AW8i4VTVE5gEXmYincY124uaNy2fOAXOtH2kQck1zGpdu8aasVeLqxhCx6hWPFHabsaJ2f4LCIKxNKmsHTDLrTR0PIB0D9U940h4TPYAyrqi9CByNcauaibUxykvu+UUnSDJ2V plmabaj@tfsa.abb.com
##[debug]hostName=|1|RyX1HGab+gSa29Q99VApWbD5XPE=|ROzy+vq75uqQc+p9/MWisspu3xw= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9ZeVJ4ejjhE5QgjIz1iB8imXEsYpbVEzVJ2JEEtpG6nahg3mN8CEyv0gtSGt9HoPtiAMPieIcvGLVGmCEfOGJ3utifFrJAysVp2h1zlnt7ttwpF+X+Di30+XUZy7goyBUx2ZnICNKM+aPByQAPs2ohR8hXX0ErM/KsfjrCJ2rOQrkdRmI6OPr+HMudrHiUU7EfhW9zlj10pY1JIJfmuqR/h90zFNYxedkxUJnDh72RuelT+EvN9Y8bY/7KZt61FHYQmx8iE459ULdnXoRr0BhgZ2oH8m+bUlJYDmFpcQ2Dy5BYBqO3WNUyb75uYDU4wLOYXHzgigVoYQc5xsS/6Q/ |1|d/9td4eq+52WDdMl271Y02P+po0=|jtBAGpjXEvJCX6wMAd+aZEl9GYI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9ZeVJ4ejjhE5QgjIz1iB8imXEsYpbVEzVJ2JEEtpG6nahg3mN8CEyv0gtSGt9HoPtiAMPieIcvGLVGmCEfOGJ3utifFrJAysVp2h1zlnt7ttwpF+X+Di30+XUZy7goyBUx2ZnICNKM+aPByQAPs2ohR8hXX0ErM/KsfjrCJ2rOQrkdRmI6OPr+HMudrHiUU7EfhW9zlj10pY1JIJfmuqR/h90zFNYxedkxUJnDh72RuelT+EvN9Y8bY/7KZt61FHYQmx8iE459ULdnXoRr0BhgZ2oH8m+bUlJYDmFpcQ2Dy5BYBqO3WNUyb75uYDU4wLOYXHzgigVoYQc5xsS/6Q/ |1|VJWwLf/mldc2naUNSJdVuR+MwxCob5qZVR8MgT+jfiU= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9ZeVJ4ejjhE5QgjIz1iB8imXEsYpbVEzVJ2JEEtpG6nahg3mN8CEyv0gtSGt9HoPtiAMPieIcvGLVGmCEfOGJ3utifFrJAysVp2h1zlnt7ttwpF+X+Di30+XUZy7goyBUx2ZnICNKM+aPByQAPs2ohR8hXX0ErM/KsfjrCJ2rOQrkdRmI6OPr+HMudrHiUU7EfhW9zlj10pY1JIJfmuqR/h90zFNYxedkxUJnDh72RuelT+EvN9Y8bY/7KZt61FHYQmx8iE459ULdnXoRr0BhgZ2oH8m+bUlJYDmFpcQ2Dy5BYBqO3WNUyb75uYDU4wLOYXHzgigVoYQc5xsS/6Q/
##[debug]sshPassphrase=null
##[debug]check path : /home/tfs-build-agent/agent2/_work/_tasks/InstallSSHKey_5c9af2eb-5fc5-42dc-9b91-dc234a8c4400/0.151.2/task.json
##[debug]adding resource file: /home/tfs-build-agent/agent2/_work/_tasks/InstallSSHKey_5c9af2eb-5fc5-42dc-9b91-dc234a8c4400/0.151.2/task.json
##[debug]system.culture=en-US
##[debug]sshKeySecureFile=7e2886f1-72fd-4665-9534-59f2641a1447
##[debug]System.TeamFoundationCollectionUri=https://tfsb.abb.com/tfs/EPBP/
##[debug]SYSTEMVSSCONNECTION auth param ACCESSTOKEN = ***
##[debug]Agent.ProxyUrl=undefined
##[debug]secure file name for id 7e2886f1-72fd-4665-9534-59f2641a1447 = id_rsa_tfsa
##[debug]Agent.TempDirectory=/home/tfs-build-agent/agent2/_work/_temp
##[debug]Absolute path for pathSegments: /home/tfs-build-agent/agent2/_work/_temp,id_rsa_tfsa = /home/tfs-build-agent/agent2/_work/_temp/id_rsa_tfsa
##[debug]Downloading secure file contents to: /home/tfs-build-agent/agent2/_work/_temp/id_rsa_tfsa
##[debug]task result: Failed
##[error]Error: unable to get local issuer certificate
##[debug]Processed: ##vso[task.issue type=error;]Error: unable to get local issuer certificate
##[debug]Processed: ##vso[task.complete result=Failed;]Error: unable to get local issuer certificate
##[debug]secure file name for id 7e2886f1-72fd-4665-9534-59f2641a1447 = id_rsa_tfsa
##[debug]Agent.TempDirectory=/home/tfs-build-agent/agent2/_work/_temp
##[debug]Absolute path for pathSegments: /home/tfs-build-agent/agent2/_work/_temp,id_rsa_tfsa = /home/tfs-build-agent/agent2/_work/_temp/id_rsa_tfsa
##[debug]Deleting secure file at: /home/tfs-build-agent/agent2/_work/_temp/id_rsa_tfsa
##[debug]rm -rf /home/tfs-build-agent/agent2/_work/_temp/id_rsa_tfsa
##[debug]removing file
##[debug]End
```
### Error logs
```
##[error]Error: unable to get local issuer certificate
```

**Comment by janis-veinbergs** [comment]
Is there an option to runa pre-job task without writing a custom task? In that case, environment variables could be set up, CA file downloaded, etc.

In my case git required custom cert too. By default, job checks out source in a pre-job, however if there is `checkout` task then it does not. So I manually specified `checkout` and just before that, a `PowerShell` task to make git config changes. But yeah, I cannot do this with `DownloadSecureFile` task.

**Comment by rakol-ms** [comment]
@gpomykala Have you considered defining NODE_EXTRA_CA_CERTS and SSL_CERT_DIR as pipeline variables? They are exposed as environment variables during run time

**Comment by gpomykala** [comment]
Hello,
Thanks for a suggestion. Although the workaround might work it is not really suitable in any scenario bigger than 1 agent / 1 pipeline:
* NODE_EXTRA_CA_CERTS and SSL_CERT_DIR belongs to agent configuration rather than pipeline configurations
* there may be multiple pipelines using same agent - it is not feasible to set those on every pipeline
* there may be multiple agents linked to a single pipeline and they may require different values of NODE_EXTRA_CA_CERTS and SSL_CERT_DIR therefore setting these variables in a pipeline would be not effective

I believe it belongs to the agent configuration and could be part of agent installation wizard

**Comment by rakol-ms** [comment]
@gpomykala Your arguements are valid. I have tried another way for this issue. I found that all you need is to set NODE_EXTRA_CA_CERTS value in environment. I have added a bash task with inline script
 `echo "##vso[task.setvariable variable=NODE_EXTRA_CA_CERTS]$(Agent.CAInfo)"`
before the key vault task. This will set the variable to whatever CA cert the agent is configured with. Though this means you will be editing multiple pipelines, multiple agents configured with multiple CA will be supported

**Comment by gpomykala** [comment]
Thanks, that looks promising, i will check the script above

**Comment by alexander-smolyakov** [comment]
Hello, @gpomykala!

Could you please update your private agent to the latest version and run the pipeline again?

You also can use [Node.js Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) task to install the latest version of the node.js in your agent.

If the issue still remains could you please attach new logs for DownloadSecureFileV1 and  InstallSSHKeyV0 tasks running in debug mode.

**Comment by alexander-smolyakov** [comment]
Hello, @gpomykala!

Closing now this issue due to a lack of reproducible information, please feel free to reopen it.

**Comment by dmakvh** [comment]
this can be easily reproduced on Azure DevOps server 2019.1.1 behind a firewall, the server needs to have a corporate certificate _(hence : not available via WAN)_ signed by a corporate CA **(also not available / reachable via WAN, CA certificate not shipped with any browser but installed on each client machine)**. Its definitely a bug.
**Using NODE_EXTRA_CA_CERTS works, though** ...

**Comment by InternetPseudonym** [comment]
lorem ipsum sit dolor amet.

**Comment by anatolybolshakov** [comment]
Hi everyone, reopened this to investigate further

**Comment by nadcraker** [comment]
I am getting this error even though I am using ` NODE_EXTRA_CA_CERTS: 'C:\Certs\MYCORPROOT.pem'`

Here is my log:

```
(node:2388) Warning: Ignoring extra certs from `C:\Certs\MYCORPROOT.pem`, load failed: error:02001003:system library:fopen:No such process

##[debug]Attempt failed. Number of tries left: 2
##[debug]unable to get local issuer certificate
##[debug]Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)
```

**Comment by janis-veinbergs** [comment]
@nadcraker maybe agent user has no permissions to access that file, huh?

**Comment by janis-veinbergs** [comment]
While this is being sorted out, I've found excellent script that generates .pem file for NODE consumption from Windows Trusted Root Certificate Store: [Azure DevOps Server pipeline build fails when using self-signed SSL certificate with "unable to get local issuer certificate" during NuGet restore](https://stackoverflow.com/questions/56855546/azure-devops-server-pipeline-build-fails-when-using-self-signed-ssl-certificate)

Credit to SO [alifen](https://stackoverflow.com/users/4511447/alifen)

```powershell
# If running in a pipeline then use the Agent Home directory,
# otherwise use the machine temp folder which is useful for testing
if ($env:AGENT_HOMEDIRECTORY -ne $null) { $TargetFolder = $env:AGENT_HOMEDIRECTORY }
else { $TargetFolder = [System.Environment]::GetEnvironmentVariable('TEMP','Machine') }

# Loop through each CA in the machine store
Get-ChildItem -Path Cert:\LocalMachine\CA | ForEach-Object {

    # Convert cert's bytes to Base64-encoded text and add begin/end markers
    $Cert = "-----BEGIN CERTIFICATE-----`n"
    $Cert+= $([System.Convert]::ToBase64String($_.export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert),'InsertLineBreaks'))
    $Cert+= "`n-----END CERTIFICATE-----`n"

    # Append cert to chain
    $Chain+= $Cert
}

# Build target path
$CertFile = "$TargetFolder\TrustedRootCAs.pem"

# Write to file system
$Chain | Out-File $CertFile -Force -Encoding ASCII

# Clean-up
$Chain = $null

# Let Node (running later in the pipeline) know from where to read certs
Write-Host "##vso[task.setvariable variable=NODE.EXTRA.CA.CERTS]$CertFile"
```

**Comment by anatolybolshakov** [comment]
@gpomykala thanks for reporting! Let us take a look at it as possible enhancement - we could probably just use NODE_EXTRA_CA_CERTS variable to set up as Agent.CAInfo value (or consider any other ways of resolution here).
