### ISSUE TITLE
Intermittently VsTest Task fails to execute tests

### ISSUE THREAD

**Issue by himajan** [microsoft/azure-pipelines-tasks#11501]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.157.4

## Environment
- Server - Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Team project Name: OneCRM
Build Definition Name: CDS-PRv3-RollingBuild
Build Definition Id: 7021

Link to Failure build: https://dynamicscrm.visualstudio.com/OneCRM/_build/results?buildId=5352687

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Agent OS: Windows_NT
Agent Version: 2.158.0

## Issue Description

Task Name: Run OData Integration Tests on VM
![image](https://user-images.githubusercontent.com/56146857/66183587-4579b900-e62e-11e9-86c2-700a84a4c43f.png)

### Task logs
[logs_5352687_ReducedTo10MB.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3689097/logs_5352687_ReducedTo10MB.zip)
 The full build pipeline logs zip file size is ~28MB, so I could not upload the zip file. Let me know if there is away I can upload this file if you need this for analyzing the issue.
### Error logs

[Insert error from the logs here for a quick overview]

=================================================================
##[debug]DiscoverTests.PerformDiscovery : Test Discovery completed.
##[debug]PERF WARNING: DiscoverTests.PerformDiscovery: took 3273.9647 ms
##[debug]Discovery.Run : Discovery run completed.
##[debug]Discovery.Run : Cleanup invoked.
##[debug]Cleanup.Cleanup : Creating new cleanup instance.
##[debug]Cleanup.Run : Initialize cleanup
##[debug]Processed: ##vso[task.uploadfile]C:\Agents\BuildAgent\_workap\_temp\Slice-953174_o4eydd.diaglog
##[debug]Processed: ##vso[task.uploadfile]C:\Agents\BuildAgent\_workap\_temp\Slice-953174_o4eydd.host.19-10-04_01-17-05_90642_7.diaglog
##[debug]Processed: ##vso[task.uploadfile]C:\Agents\BuildAgent\_workap\_temp\TraceLogs-953174_o4eydd.diag
##[debug]Cleanup.Run : Cleanup finished
##[debug]ExecutionStateResolver.SetNextPhase : Current Phase: Discovery
##[debug]ExecutionStateResolver.SetNextPhase: ExecutionStateResolver.SetNextPhase : Slice aborted
##[error]The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: No test is available in C:\Agents\BuildAgent\_workap\1\s\bin\debug\Microsoft.Crm.Extensibility.IntegrationTests.ODataV4\Microsoft.Crm.Extensibility.IntegrationTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
##[debug]Processed: ##vso[task.logissue type=error;]The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: No test is available in C:\Agents\BuildAgent\_workap\1\s\bin\debug\Microsoft.Crm.Extensibility.IntegrationTests.ODataV4\Microsoft.Crm.Extensibility.IntegrationTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
##[debug]ExecutionStateResolver.SetNextPhase : Next Phase: SliceFetch
##[debug]TestExecutionHost.Execute: Current Phase SliceFetch
##[debug]VstestAdapter.ExecuteAsync : Starting Execution
##[debug]VstestAdapter.ExecuteAsync : Returning
##[debug]TestExecutionServiceListener.Start invoked
Received the command : Stop
TestExecutionHost.ProcessCommand. Stop Command handled

**Comment by ShreyasRmsft** [comment]
Taking a look

**Comment by ShreyasRmsft** [comment]
Download the full zip logs for this release.

in there you will see a file **_23_Slice-953174_o4eydd.host.19-10-04_01-17-05_90642_7.diaglog_**

You will see an issue with loading xunit runner. Please ensure the dependent xunit dlls are placed correctly.

TpTrace Warning: 0 : 9536, 3, 2019/10/04, 01:17:07.250, 1607218297178, testhost.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'xunit.runner.utility.net452, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
File name: 'xunit.runner.utility.net452, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'

**Comment by ShreyasRmsft** [comment]
This is a setup issue and not a task issue.
