### ISSUE TITLE
Azure Resource Group Deployment task: fill param values with Key vault secrets WITHOUT using the overwrite section

### ISSUE THREAD

**Issue by roybongers-oce** [microsoft/azure-pipelines-tasks#11511]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: **Azure Resource Group Deployment V2**  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: **17.143.28621.4**
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: **Private**
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: **OS: 10.0.14393 / Agent: 2.133.3**

## Issue Description
Azure Resource Group Deployment: secrets downloaded with Key Vault secrets task(s) do NOT overwrite "$(paramValue)" in parameter files UNLESS the overwrite section is used. This way Continuous Deployment cannot be enabled; because after checking in a new param or param value the overwrite section has to be cleared and the overwrite button pushed = manual actions. What should work is that $(paramValue) should be read directly from the param file without these manual actions... Can this be done / implemented somehow? This would be very much appreciated!

![1](https://user-images.githubusercontent.com/47175087/66256999-40367e80-e794-11e9-83b4-b53d1d7b8d95.png)
![2](https://user-images.githubusercontent.com/47175087/66257000-40367e80-e794-11e9-9b79-6ffffb91edb3.png)
![3](https://user-images.githubusercontent.com/47175087/66257082-13cf3200-e795-11e9-829a-0f1ffc11bb60.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tejasd1990** [comment]
Hi @roybongers-oce ,
The ARG task current does not support this ask. The parameter values from the parameters file are read as literal values and they are not interpreted as variables.

**Comment by roybongers-oce** [comment]
Hi,

That’s what we know indeed but question is (on which term) can you make this work (for us)?
Again, we need this very much for continuous delivery of Canon (Commercial Production Printing) cloud solutions to our customers…

Can you please let us know?

Thanks very much in advance.


With kind regards,

Roy Bongers
Cloud Architect / DevOps Engineer | Canon CPP

+31 6 25659426
+31 77 359 2658
roy.bongers@oce.com<mailto:roy.bongers@oce.com>



[Océ]<https://www.oce.com>      Océ-Technologies B.V.
P.O. Box 101, 5900 MA Venlo
Sint Urbanusweg 43, 5914 CA Venlo
The Netherlands  |  www.oce.com<https://www.oce.com>
Trade register: 12002662

This message and attachment(s) are intended solely for use by the addressee and may contain information that is privileged, confidential or otherwise exempt from disclosure under applicable law. If you are not the intended recipient or agent thereof responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by telephone or with a 'reply' message and delete the message and its attachment(s), if any, from your system(s). Thank you for your co-operation.

**Comment by roybongers-oce** [comment]
Hmm that would be disappointing.
We tried other ways like using local appSetting.json files but that have some other disadvantages.
So it would really help to have this as an option in the task that when enabled to retrieve only $() values directly from the parameter files without using the overwrite field to enable CD.



[Océ]<https://www.oce.com>      Océ-Technologies B.V.
P.O. Box 101, 5900 MA Venlo
Sint Urbanusweg 43, 5914 CA Venlo
The Netherlands  |  www.oce.com<https://www.oce.com>
Trade register: 12002662

This message and attachment(s) are intended solely for use by the addressee and may contain information that is privileged, confidential or otherwise exempt from disclosure under applicable law. If you are not the intended recipient or agent thereof responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by telephone or with a 'reply' message and delete the message and its attachment(s), if any, from your system(s). Thank you for your co-operation.

**Comment by tejasd1990** [comment]
Hi @roybongers-oce, I will close this issue now.
