### ISSUE TITLE
TaskCompleted in Events

### ISSUE THREAD

**Issue by annguyen281** [microsoft/azure-pipelines-tasks#11510]
Hello all,

I would like to have question about "TaskCompleted" in Events

TaskCompleted - Raise this event when task is completed (indicates success/failure). Here is how an example of the event section.
 `
{
       "TaskStarted":
       {
          "Timeout": "00:05:00"
       },
       "TaskCompleted":
       {
          "Timeout": "00:07:00"
       }
    }
`
Beside "Timeout", what options I can use?

Thank you very much

**Comment by damccorm** [comment]
This is an issue with [server tasks docs](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/servertaskauthoring.md#execution-section), repathing to Release to take a look

**Comment by ds-ms** [comment]
Closing this stale issue
