### ISSUE TITLE
NuGet Command - allowPackageConflicts still surfaces conflict error

### ISSUE THREAD

**Issue by adibradfield** [microsoft/azure-pipelines-tasks#11512]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetCommandV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    Azure Pipelines:
https://adrianbradfield.visualstudio.com/MongoDelta/_build/results?buildId=138&view=results

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-latest

## Issue Description

Task name: "Push NuGet Package"
Source for pipeline: https://github.com/adibradfield/MongoDelta/blob/master/azure-pipelines/release-pipeline.yml
Source for NuGet push template: https://github.com/adibradfield/MongoDelta/blob/master/azure-pipelines/templates/release-nuget-steps.yml

### Task logs

[logs_139.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3695022/logs_139.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

The nuget command failed with exit code(1) and error(Response status code does not indicate success: 409 (A package with ID 'MongoDelta.AspNetCore3' and version '1.0.0' already exists and cannot be modified.). System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (A package with ID 'MongoDelta.AspNetCore3' and version '1.0.0' already exists and cannot be modified.)

**Comment by jmyersmsft** [comment]
We are beginning the process of deprecating the NuGetCommand task in favor of using the new NuGetAuthenticate task to set up authentication + a script task to run NuGet however you like, including using the -SkipDuplicate switch added in version 5.1

We may still fix the NuGetCommand task, but it is a lower priority than other fixes in flight at this time.

**Comment by herenhuang** [comment]
Hi @adibradfield - were you able to try out the NugetAuthenticate task mentioned above? Are you still hitting this same issue?

**Comment by herenhuang** [comment]
Just send us a comment if you're still having this issue and we'll reopen the ticket to track this exact issue.
