### ISSUE TITLE
Image Digest file

### ISSUE THREAD

**Issue by ravindra2010** [microsoft/azure-pipelines-tasks#11516]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: docker build&push 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

We need image digest file as output of docker push command as we were getting in Docker V1. These are required for the my service fabric application please add the image digest feature in docker v2 as well
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ds-ms** [comment]
@sonayak this seems like a good enhancement, can you check with the PMs as to why this was missed; if there's no specific reason I think we should go ahead and add this 😃

**Comment by sonayak** [comment]
@ravindra2010 : In DockerV2, we have tried to limit the number of inputs to the task to simplify it. So we have not provided the support for image digest files. But image digest is written to the output. Can you share the details of how you are using the image digest? We will find out what can be done to support the use case.

**Comment by sonayak** [comment]
@ravindra2010 : Closing the issue for now. Please feel free to reopen with the details asked in the previous comment.
