### ISSUE TITLE
Python Twine Upload Authenticate problem when feed name contains dot.

### ISSUE THREAD

**Issue by FernanOrtega** [microsoft/azure-pipelines-tasks#11521]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: Python Twine Authenticate v0/v1 (I checked both versions)

## Environment
Azure Pipelines

## Issue Description
If a seed artifact contains a dot, for instance, "My.Feed", the task "Python Twine Upload Authenticate" will create the ".pypirc" as follows:

```
[distutils]
index-servers=My.Feed
[My\.Feed]
repository=https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed/pypi/upload
username=build
password=***
```

This involves that the execution of "twine upload -r My.Feed --config-file $(PYPIRC_PATH) dist/*" fails since it cannot found the "My.Feed" section in the .pypirc file.

## Troubleshooting
The solution was using this command after the execution of the task:

```
sed -i -e 's/\\//g' $(PYPIRC_PATH)
```

### Error logs

```
2019-10-07T17:05:21.5496516Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/<hidden-info>.sh
2019-10-07T17:05:21.9224804Z InvalidConfiguration: Missing 'My.Feed' section from the configuration file
2019-10-07T17:05:21.9226042Z or not a complete URL in --repository-url.
2019-10-07T17:05:21.9227166Z Maybe you have a out-dated '/home/vsts/work/_temp/twineAuthenticate/oswDqH/.pypirc' format?
2019-10-07T17:05:21.9227404Z more info: https://docs.python.org/distutils/packageindex.html#pypirc
```

**Comment by tkrick** [comment]
Hi @FernanOrtega thanks for reporting this. @shubham90 can you confirm? 

of course renaming the feed is a mitigation for you, but we'll look at getting this fixed.

**Comment by shubham90** [comment]
The ini [parser](https://github.com/npm/ini) that we use treats dots in keys as separate sections and adds a '\' while encoding it in ini format.
We can do a string search for '\.' and replace it with '.' but that can be a risky change and has the potential to have some unintended consequences. I am not in favor of fixing this immediately because of the risk. We can revisit this if we hear more of such issues. @tkrick let me know if you agree.
A quick workaround is to use a command line task right after auth task and replace '\.' with '.'.

**Comment by tkrick** [comment]
@shubham90 i'm a bit hesitant to have our tasks replace wack-. with . since there may be places where wack-. is expected in the ini content. Maybe if we only searched in the ini headers.

**Comment by thomasnal** [comment]
Has this been fixed?  We still encounter this error.  In our situation, there is no permission to change the feed name, so we are stuck.  So disappointing.

**Comment by bothzoli** [comment]
hiya!
i'm also facing this issue. it's quite frustrating as i spent hours of checking what could be the issue.
any thoughts on @tkrick 's idea of only doing the replace in headers?
if not than a simple warning or some documentation about this limitation would be helpful.
i'm also happy to contribute either to fix or to extend documentation.
what are your thoughts?

**Comment by aasim** [comment]
Fixed in PR [16182](https://github.com/microsoft/azure-pipelines-tasks/pull/16182)
