### ISSUE TITLE
Windows job w/ caching enabled is slow w/ endless logs

### ISSUE THREAD

**Issue by mikescar** [microsoft/azure-pipelines-tasks#11529]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta@0

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines - private org but PM/email for details.

- Agent - Hosted or Private: 
    
Azure Pipelines 5 windows-latest

## Issue Description

Very slow upload in Post-Job cache operation. This matches behavior for cache downloads that often is slower than building from scratch. 

At 2.9GB, the below represents a conda install of medium complexity. Other builds with caches of 450MB take 1min30sec for downloading after a cache hit.

Logs filled with lines like the below, but each Uploaded * MB progress message shows progress, so unsure of conflict.

```
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodeus21.vsblob.visualstudio.com/A6997e070-a1ae-4956-a412-4d8c1d4b33cc/_apis/dedup/nodes/301A458CAF609E502B174D38C7EA21BB9481D916ACD011D4D1EA8683AE0AFC2202 attempt 1/6 failed with StatusCode Conflict, IsRetryableResponse False
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodeus21.vsblob.visualstudio.com/A6997e070-a1ae-4956-a412-4d8c1d4b33cc/_apis/dedup/nodes/CB72FCA65002FE8B4FFB0026F2B4D022664EA065D9C7C558C33E93E5AF75A46B02 attempt 1/6 failed with StatusCode Conflict, IsRetryableResponse False
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodeus21.vsblob.visualstudio.com/A6997e070-a1ae-4956-a412-4d8c1d4b33cc/_apis/dedup/nodes/9C46158BE299508B7806A734CE0A821DD5AA9F63FEE0C3FA68716A1D13CDF31A02 attempt 1/6 failed with StatusCode Conflict, IsRetryableResponse False
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodeus21.vsblob.visualstudio.com/A6997e070-a1ae-4956-a412-4d8c1d4b33cc/_apis/dedup/nodes/9725CCDF2DF3F947CAA4A8B61C74C5D710F1D5F3A8D35D6BB9C6B32F981DB55D02 attempt 1/6 failed with StatusCode Conflict, IsRetryableResponse False
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodeus21.vsblob.visualstudio.com/A6997e070-a1ae-4956-a412-4d8c1d4b33cc/_apis/dedup/nodes/C76611EB1BBA7DD5FEDE88966533138432B6FA084F7A07F0CE7A30B0F184206502 attempt 1/6 failed with StatusCode Conflict, IsRetryableResponse False
Information, Uploaded 584.9 MB out of 2,906.6 MB.
```

### Task logs

PM for details

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

none - all info

(Thanks all!!!)

**Comment by johnterickson** [comment]
Hi @mikescar  - Sorry for the delay - we didn't get this routed in time.  Are any of these public projects you can point to?

**Comment by mikescar** [comment]
Hi @johnterickson Sorry, no they were all our org's private pipeline. We ended up conditionally building windows a lot less, because it was slow anyway. Has upload/download speed improved with caching? Thanks!

**Comment by johnterickson** [comment]
@mikescar We are rolling out TARing of the directory contents which can help when there are many small files.  How many files make up the 450MB?

**Comment by fadnavistanmay** [comment]
Hi @mikescar - you should see some improvement in the agent version 2.160.0 . Plus, we have updated the code to curb the logs output. Let us know if that helped. 

Thanks.

**Comment by fadnavistanmay** [comment]
Hello, I am closing this issue. Please feel free to re-open in case it still persists.

Thanks.
