### ISSUE TITLE
Nuget pack for .net standard not updating version(build number) in .csproj file

### ISSUE THREAD

**Issue by ramesh580** [microsoft/azure-pipelines-tasks#11522]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

I have created a pipeline for a (.net standard 1.1)solution. This pipeline is to build and release a new nuget package for this solution. I have created the task like, NuGet restore, version .net core assemblies, visual studio build, NuGet pack and NuGet push (image is attached).

In the Nuget pack, set the automatic package versioning as 'Use an environment variable' and an Environment variable as "Build.BuildNumber". Under options set the build number format as 1.0.0$(rev:.r).

When I execute this build, it gets success and a new Nuget package is generated and published to a feed whereas the version still remains 1.0.0.0 in .csproj. I used version .net core assemblies to update the version in .csproj.This task log showing version is updated but it's not. Attached log for this task.
<img width="919" alt="Task structure" src="https://user-images.githubusercontent.com/36506448/66387683-14103d00-e9e2-11e9-8371-55aa4ae00b65.png">
<img width="1440" alt="version  net core assemblies log" src="https://user-images.githubusercontent.com/36506448/66387684-14103d00-e9e2-11e9-9844-c33d0eccd746.png">

**Comment by jmyersmsft** [comment]
The task is operating as designed. NuGet does not alter csproj files when packing.
