### ISSUE TITLE
Issue with script task setting environment variables

### ISSUE THREAD

**Issue by praveendath92** [microsoft/azure-pipelines-tasks#11537]
Entering this information will route you directly to the right team and expedite traction.

**Bug**
**Enter Task Name**: script  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Private:  Ubuntu 16.04

## Issue Description
When using the `script` built in task to set an environment variable, we are getting an extra `'` added 
to the environment variable if we use the `set -ux` flags.

The below code sets `$ANDROID_SERIAL` to `emulator-5554'` (notice the extra ' at the end)
```
parameters:
  deviceId: 'emulator-5554'

steps:
- script: |
      set -ux
      echo '##vso[task.setvariable variable=ANDROID_SERIAL]${{ parameters.deviceId }}'
```

The below code sets `$ANDROID_SERIAL` to `emulator-5554` (notice no extra ' at the end)
```
parameters:
  deviceId: 'emulator-5554'

steps:
- script: |
      echo '##vso[task.setvariable variable=ANDROID_SERIAL]${{ parameters.deviceId }}'
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment]
This is the same issue as https://github.com/microsoft/azure-pipelines-tasks/issues/10331 - see discussion there.
