### ISSUE TITLE
DotNetCoreCli 'Build' fails for Floating Version in PackageReference for a package in Azure Artifact Feed

### ISSUE THREAD

**Issue by keithdv** [microsoft/azure-pipelines-tasks#11539]
I cannot get a floating version "1.*" for a package in a private Azure Artifact feed to work for the azure pipeline build. Works in Visual Studio.

**csProj file:**

    <PackageReference Include="MyPackage.Logging" Version="1.*" />

**Yaml:**

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '2a167ba8-8dc2-4ecf-8505-f73255a75371'
    includeNuGetOrg: true
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**\*.csproj'
    arguments: '--configuration Release /p:Version=$(GitVersion.NuGetVersion)'
    versioningScheme: byBuildNumber

Build step reports:

D:\a\1\s\MyProject.Logging.Web\MyProject.Logging.Web.csproj : error NU1101: Unable to find package MyPackage.Logging. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
  Restore failed in 412.09 ms for D:\a\1\s\MyProject.Logging.Web\MyProject.Logging.Web.csproj.

The restore project successfully restores the 1.1.10 version package. Then the build fails.

I have tried restoring with NuGet (Nuget.exe) step. Specifying feedsToUse and vstsFeed in the 'build' step but these don't seem to have an affect; only the 'restore' step. I cannot get the build to see the packages that have already been restored or use my Azure Artifact feed.

Please help!

**Comment by jmyersmsft** [comment]
`dotnet build` also runs a restore. Try adding `--no-restore` to the arguments in your 'Build' step.

**Comment by keithdv** [comment]
That worked, thanks!
Seems like if it doing a restore the vstsFeed setting should be honored.
