### ISSUE TITLE
Add option to fail Publish Test Results task when test result file is not found

### ISSUE THREAD

**Issue by bandersongit** [microsoft/azure-pipelines-tasks#11544]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishTestResults@2  

## Environment
- Server - Azure Pipelines

## Issue Description

I imagine it is a common pattern to have a test task (with continueOnError: true) followed by a publish task. I've run into the issue a couple times where we will have our test task fail due to setup issues (e.g. not test failures), but the junit output file will not be published. The PublishTestResults task will warn it cannot find the file, but it will not fail the task. I find myself relying heavily on `failTaskOnFailedTests: true`, and wish that I could make this task fail if no output files are found.

### Task logs

For our build setup see [here](https://dev.azure.com/reason-native/reason-native/_build/results?buildId=665). This particular log actually brings up another issue, where failing when the output cannot be parsed would also be nice. I don't think we have a log with the issue I described at the moment, but both things have occurred.

**Comment by Additi** [comment]
Hi @bandersongit ,

Thank you for suggesting the feature. We have added this to our backlog. Will update you as and when we pick it up.

Thanks,
Aditi

**Comment by jrsearles** [comment]
Hi - is this something you would accept a contribution on? This would be incredibly useful for me and looking at the code it seems like it would be fairly straightforward to implement.

**Comment by bormm** [comment]
So you (Microsoft) will close this, because you (MS) have done nothing since a year for this small change but big affect issue?
@Additi Is there something you can do?

**Comment by cawoodm** [comment]
The option `failTaskOnFailedTests` seems to be there now but it doesn't do anything. We have a test step (with `continueOnError: true`) which has failing tests (the test step is green) and the `PublishTestResults@2` step is also green so you never know your build failed. If you switch `continueOnError: false` (or off) then you never get to the `PublishTestResults` step.

This could be a known issue #11934
