### ISSUE TITLE
Pipeline tasks are failing to find matching file pattern

### ISSUE THREAD

**Issue by vinodkumar3** [microsoft/azure-pipelines-tasks#11541]
Pipeline tasks (ARM Deployment, AzureCLI, Azure Powershell etc.) are failing to find matching file pattern when the YML template utilizes deployment job functionality.

Error: Could not find any file matching the template file pattern

Sample failure yml:

stages:
\- stage: Deploy_In_Dev
  jobs:
  \- deployment: test
    pool:
      vmImage: 'vs2017-win2016'
    environment: 'test_env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              filePath: 'test.ps1'

**Comment by vinodkumar3** [comment]
@azureDaveOps  @damccorm 
Can you please assign this bug to right owners.

**Comment by damccorm** [comment]
@vinodkumar3 I'm a little confused - it looks like you're the one who has done the most work on this task - https://github.com/microsoft/azure-pipelines-tasks/commits/master/Tasks/AzureResourceManagerTemplateDeploymentV3. It also never got added to https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS so I don't know who to route it to (other than you)

**Comment by vinodkumar3** [comment]
@damccorm 
Its not a task issue, rather an issue with YML Pipelines platform, precisely with the deployment job.
Updated the issue Description.
Added @chshrikh,  the concerned person for the functionality.

**Comment by arjgupta** [comment]
@vinodkumar3 this is happening because for deployment job you need to explicitly checkout the repo which contains the said file. You need to add a `-checkout : self` task before your task execution in order for the pipeline to sync the repo to your private agent.
