### ISSUE TITLE
Install Apple Certificate task failed

### ISSUE THREAD

**Issue by BrightRan** [microsoft/azure-pipelines-tasks#11548]
Install Apple Certificate task failed with the following error:
**Error: Unable to find the certificate SHA1 hash and common name (CN). Verify that the certificate is a valid P12.**
This issue occurs on Install Apple Certificate V2.
More details please reference the ticket linked here: https://developercommunity.visualstudio.com/content/problem/769699/install-apple-certificate-fails-after-updating-sdk.html

**Comment by leantk** [comment]
Closing as a duplicate to this open issue: https://github.com/microsoft/azure-pipelines-tasks/issues/11852
