### ISSUE TITLE
Need to help to create customized task in Azure Devops pipeline 

### ISSUE THREAD

**Issue by Surajshindeselenium** [microsoft/azure-pipelines-tasks#11547]
We are creating customized task plugin for automation testing tool and facing issue while creating task.json file. it will be helpful if i get sample code for task which is used for automation testing tool. 

Thanks in advance.

**Comment by damccorm** [comment]
Hi, we have docs on creating custom tasks here - https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops&viewFallbackFrom=vsts

Additionally, you can take a look at any of the tasks in this repo for sample code. If that doesn't get you the help you need, please open an issue in https://github.com/MicrosoftDocs/vsts-docs
