### ISSUE TITLE
DockerV2: Add option to not set metadata labels

### ISSUE THREAD

**Issue by DanielHabenicht** [microsoft/azure-pipelines-tasks#11551]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature
**Enter Task Name**: DockerV2
**Step**: buildAndPush 

## Environment
- Server: Azure Pipelines or TFS on-premises
- Agent: Hosted or Private

## Issue Description

If building for production I don't need the labels added by the DockerV2 Task. 
But it is executed nevertheless. 

I propose an option to not set the labels. 

This would also speed up the build because setting one label takes around 2 seconds which is way to much if you are just building an Nginx image and copying some artefacts.

**Comment by vithati** [comment]
@DanielHabenicht , You can uncheck "Add pipeline metadata to image(s)" to not set the labels. 
![image](https://user-images.githubusercontent.com/19663618/66729739-f7a15400-ee6a-11e9-8966-23668259c1c7.png)

In YAML, you can set 'addPipelineData' task argument as false to not set the labels.

**Comment by DanielHabenicht** [comment]
Thanks for the info, but this is not documented.  :)
So this issues is now about documenting this.

**Comment by vithati** [comment]
@DanielHabenicht , I have opened internal workitem to update document.
