### ISSUE TITLE
Cannot use variables in input section

### ISSUE THREAD

**Issue by sasanmcp** [microsoft/azure-pipelines-tasks#11555]
This is what I have in my YAML:

- task: AzureResourceManagerTemplateDeployment@3
 displayName: 'Azure Deployment Run Arm Template'
  inputs:
    ConnectedServiceName: $(dev_ConnectedServiceName)
    subscriptionName: $(dev_subscriptionID)
    resourceGroupName: $(dev_resourceGroupName)
    location: $(dev_location)
    csmFile: '$(System.ArtifactsDirectory)/drop/Infrastructure/ARM/deploy.json'
    csmParametersFile: '$(System.ArtifactsDirectory)/drop/Infrastructure/ARM/deploy-param.json'
    overrideParameters: '-servicePrincipalClientId $(AKSSPNClientID) -servicePrincipalClientSecret $(dev_AKSSPNClientSecret) -namePrefix $(namePrefix)'
  enabled: true

when I create $(dev_ConnectedServiceName), $(dev_subscriptionID), $(dev_resourceGroupName) and  $(dev_location) as variables in **stage** , pipeline fails. when I define them as pipeline variables then it goes through. variables I put in csmFile,csmParametersFile and overrideParameters always go through no matter where I define them.

why can't I use stage variables and have to use pipeline variables here?

**Comment by tejasd1990** [comment]
Hi @sasanmcp ,
I was not able to repro this. Can you share the entire YAML file which fails with the variables defined in stage scope, so that we can investigate further?

**Comment by sasanmcp** [comment]
[azure-pipelines.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3730472/azure-pipelines.zip)

see attached. also this is the error I got while variables were defined in the YAML. define this dev_ConnectedServiceName as a pipeline variable rather than a YAML variable, and this problem goes away:
![image](https://user-images.githubusercontent.com/40803351/66852275-72cd3d80-ef31-11e9-81aa-1f75ded1ce90.png)

**Comment by tejasd1990** [comment]
Hi @sasanmcp 
I don't see the variables defined in the yaml file you attached. 
I have attached a yaml file where I have defined the variables in the stage and it is working for me.

[testsample.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3732191/testsample.zip)

**Comment by sasanmcp** [comment]
try using a variable in
**ConnectedServiceName**
and it will fail. using variables in other part of the Task is good in my trials as well.

**Comment by tejasd1990** [comment]
Try using an expression like _"ConnectedServiceName: ${{ variables.ConnectedServiceName_1 }}"_ .
The documentation says that expressions like these are evaluated at compile time. 

I suspect what caused this issue is that service connection values are required at compile time, whereas variable substitution happens at runtime, since variable values can change for each run.

**Comment by sasanmcp** [comment]
actually this trick worked. I don't know what the difference between ConnectedServiceName and other inputs of this task is, but others didn't need expression like {{}} however this one did.

thanks for the trick.

**Comment by tejasd1990** [comment]
Even I couldn't find any documentation which points to this particular thing, but that is what I suspect based on the execution result. Glad that you are unblocked, I will close this issue.

**Comment by sasanmcp** [comment]
perhaps something your development team can take a look at.

**Comment by tejasd1990** [comment]
The repo for yaml related issues is https://github.com/microsoft/azure-pipelines-yaml. I have raised this [issue](https://github.com/microsoft/azure-pipelines-yaml/issues/363), you can track it there.
