### ISSUE TITLE
Add python package details/provenance to Azure Artifacts for twine upload

### ISSUE THREAD

**Issue by silvanbrummen** [microsoft/azure-pipelines-tasks#11567]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: TwinePublish

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Private agent running on Windows 10

## Issue Description

Hi,

This feature request/suggestion is related to Azure Pipelines and Azure Artifacts. 

Currently we have an Azure Artifacts feed for generic packages, and a secondary feed specifically for Python packages. 

Upon uploading an Artifact through the 'Universal Package' method, it adds metadata of the commit number and a link to the pipeline build. See below image,

![c2](https://user-images.githubusercontent.com/46493049/66845498-64eadd00-ef70-11e9-8cb9-5b8113303b24.png)

However, this metadata, commit number and link to the build do not appear when our Azure pipeline creates a python package and uploads it with twine (https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml#tips-and-faqs) to the Artifacts, as can be seen in below image,

![p2](https://user-images.githubusercontent.com/46493049/66845506-6a482780-ef70-11e9-9cc4-89d621dcf1d4.png)

Could it be possible to create a task which uploads the python package and additionally adds relevant metadata such as the commit number, the commit number/hash in the repo and a link to the build? Perhaps by creating a specific TwinePublish task?

Thanks in advance,

Sil van Brummen

**Comment by tkrick** [comment]
@silvanbrummen  I believe that we will have universal (claims based) provenance very soon meaning any publish coming from any build task even ones we don't own should see provenance info (via the Twine Authenticate flows). Stay tuned. @jotaylo feel free to let us know as you roll out more universal provenance.

**Comment by silvanbrummen** [comment]
@tkrick Thanks for the reply, that sounds exactly like what we would need :)
