### ISSUE TITLE
Missing an argument for parameter 'pass'. Specify a parameter of type 'System.String' and try again.

### ISSUE THREAD

**Issue by Ashish-Jovial** [microsoft/azure-pipelines-tasks#11565]
Hi All,

I have username and pass variables in my variables, as i am creating credential using following command, i am getting this exception, please help me.

param (
    [Parameter(Mandatory = $true)]
    [string]
    $AzureADServicePrincipal,

	[string]
	$servicePrincipalKey,

	[string]
	$userName,

	[string]
	$pass,

	[string]
	$subscriptionID
)

$password = ConvertTo-SecureString -String $pass -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential($userName,$password)
Login-AzureRmAccount -Credential $cred
Select-AzureRmSubscription -SubscriptionId $subscriptionID

**Comment by chshrikh** [comment]
@Ashish-Jovial this repo is used to track issues related to azure devops tasks. Closing for now, in case you are using azure devops please share the detailed error logs.
