### ISSUE TITLE
Extract Task fails intermittently with 7z on Windows 2016

### ISSUE THREAD

**Issue by Jetski5822** [microsoft/azure-pipelines-tasks#11576]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ExtractFilesV1

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016

## Issue Description

When deploying assets, to a windows server, we keep having issues extracting 7z files. This is intermittent, sometimes those files work, and other times different 7z files will fail.

This always works with Zip files, only 7z is the issue.

![image](https://user-images.githubusercontent.com/619530/66997591-ad1e1280-f0ca-11e9-9539-98ee762d0bad.png)

### Task logs

[tasklog_12.log](https://github.com/microsoft/azure-pipelines-tasks/files/3738504/tasklog_12.log)

**Comment by damccorm** [comment]
This looks like an issue with the interaction between the 7z tool and the artifacts on your machine - I don't think there's anything we can do on our side here unfortunately. I'd recommend verifying that you can manually extract some of the 7z files, I'm guessing they're somehow corrupted or not extractable by 7z

**Comment by damccorm** [comment]
I'm going to close since I don't think there's anything we can do here, please comment if you think it should be reopened.
