### ISSUE TITLE
AzurePowerShellV4 Task has no Working Directory argument

### ISSUE THREAD

**Issue by mic-max** [microsoft/azure-pipelines-tasks#11579]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzurePowerShellV4

## Environment
- Server - Azure Pipelines

**Comment by 20shivangi** [comment]
@mic-max It is under Advanced options. Please check.

**Comment by mic-max** [comment]
No it isn't, at least not for me. I don't know if the advanced options can be hidden for some reason? I'd like to see this added though, most other (command line) tasks have it. Thanks

**Comment by chshrikh** [comment]
Please refer this
![image](https://user-images.githubusercontent.com/11972852/67175780-106ab600-f3e5-11e9-9f67-49d65b7d3812.png)

**Comment by 20shivangi** [comment]
@mic-max Any update on this ?

**Comment by 20shivangi** [comment]
Closing the issue. Feel free to reopen, if face any.
