### ISSUE TITLE
Make GitHub tasks working with GitHub Enterprise

### ISSUE THREAD

**Issue by glaenzesch** [microsoft/azure-pipelines-tasks#11570]
## Required Information

*Type*: Feature

**Enter Task Name**: GitHubRelease & DownloadGitHubRelease  

## Environment
- Server 
    -  Azure Devops Server 2019.1

- Agent 
    -  Private: OS: Win10, W2K12, W2K16 Version 2.153.1

## Issue Description

The current release tasks are working with a GitHub service connection. Can someone make them working with a GitHub Enterprise service connection too? This would be a awesome feature and would help to get Azure DevOps Server and GHE comes closer.

**Comment by Lovakumar** [comment]
Adding @ashokirla to add this feature to backlog. GHE support makes lot of sense w.r.t Azure DevOps Server.

**Comment by michaelschneiderdaimler** [comment]
is there any "task porting guide" from github to github enterprise? then the community could help :)

**Comment by glaenzesch** [comment]
Hey @Lovakumar,
any news on this topic so far?

**Comment by brvaland** [comment]
Any update on this issue?

**Comment by glaenzesch** [comment]
Same request #13409

**Comment by cristian-rincon** [comment]
Hi, any updates from this issue so far?

**Comment by justinokay** [comment]
Bumping this thread. I would also like to see this. Strange that the FOSS alternative is more supported than the paid product.

**Comment by Jon889** [comment]
@Lovakumar Any update?
