### ISSUE TITLE
Maven@3 task setting mavenVersionOption=path doesn't work

### ISSUE THREAD

**Issue by ata18** [microsoft/azure-pipelines-tasks#11583]
The documentation for this task says that one could set `mavenVersionOption` to `path` to specify a custom maven installation path.
```
 #mavenVersionOption: 'Default' # Options: default, path
```

But this doesn't work. Looking at the source code, it appears to be a case sensitive comparison that is causing the issue. Could we have a case insensitive check for all the arguments or update the document to make it clear?
```
if (mavenVersionSelection == 'Path') {
    // The path to Maven has been explicitly specified
    tl.debug('Using Maven path from user input');
    var mavenPath = tl.getPathInput('mavenPath', true, true);
    mvnExec = path.join(mavenPath, 'bin', 'mvn');

    // Set the M2_HOME variable to a custom Maven installation path?
    if (tl.getBoolInput('mavenSetM2Home')) {
        tl.setVariable('M2_HOME', mavenPath);
    }
}
```

**Comment by salvmd** [comment]
@leantk (per https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS), could you help us route this to the team that owns the Maven task?

**Comment by leantk** [comment]
@salvmd that would be me. I've assigned it to myself and will look into the suggestions above
