### ISSUE TITLE
Docker task + ACR connection creates invalid repo/tag

### ISSUE THREAD

**Issue by derhally** [microsoft/azure-pipelines-tasks#11581]
*Type*: Bug

**Enter Task Name**: Docker

## Environment
- Server - Azure Pipelines 

- Agent - Hosted: ubuntu-latest

## Issue Description

When using the *Docker* task with an Azure Registry connection to build a docker image, the image is tagged with the pattern "***/imagename"

This is not a valid image name and docker tag command will not even accept it, but for whatever reason docker build does.   

If I try to publish the same image to different repositories it will fail because I can't retag the image.

Here is docker tag rejecting the repo/tag format

```
Generating script.
Script contents:
docker tag ***/atlas-build:14122 atlas-build:14122
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/d4440105-e66d-45ea-9a51-9f60c6da2a64.sh
Error parsing reference: "***/atlas-build:14122" is not a valid repository/tag: invalid reference format
```

### Task logs

Here is the buildAndPush log

/usr/bin/docker build -f /home/vsts/work/1/s/docker/atlas-build/Dockerfile  -t ***/atlas-build:14122 -t ***/atlas-build:latest /home/vsts/work/1/s/docker/atlas-build

**Comment by vithati** [comment]
@derhally, it is not related to "***". Logs will show *** for secret values.  Looks like your ACR name has invalid character that docker now allowing. Can you try to tag one of image with "your ACR name/test" on your local machine with docker and see it is working or not.

**Comment by derhally** [comment]
My docker registry connection to ACR is using a subscription and the registry is called wellsky.  The service connection name is wellsky_cr.   I'm able to tag an image as wellsky_cr/foo:232.

Also I forgot to mention that when I ran "docker images" as a script task in the build pipeline, the image shows up as "***/foo"

**Comment by vithati** [comment]
@derhally , What is your ACR login server name? you can check in azure portal. Can you try to tag image with your loginservername/image.
![image](https://user-images.githubusercontent.com/19663618/67097474-d24c7700-f1d7-11e9-867b-bcb596ecbcfb.png)

**Comment by derhally** [comment]
the login server is basic characters, nothing special.  I can tag with the loginserver/image just fine.

**Comment by vithati** [comment]
@derhally , can you share docker task log with debug enabled (set system.debug variable with value true in variables section).

**Comment by derhally** [comment]
Here you go.   I've redacted some information.

[log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3744204/log.txt)

**Comment by vithati** [comment]
@derhally, In logs I don't see any failures build log. can you share task log which is failing. Are you using docker task for tagging or are you using script for tagging? if you are using script, are you specifying  "docker tag ***/atlas-build:14122 atlas-build:14122" or docker tag <acr login server>/atlas-build:14122 atlas-build:14122?

**Comment by derhally** [comment]
@vithati that was the log from the Docker task that is building and publishing to ACR.   It succeeds, but if I want to publish the or retag the image built by that task in subsequent task then I run into a problem.    

"docker images" lists the image as "***/atlas-build"  

I can't retag "***/atlas-build" because it complains about the invalid repo.

what is "***"  and how do we refer to that image?

**Comment by vithati** [comment]
@derhally, *** here is your acr login server name ex.. wellsky.azurecr.io. you should not use '***' as acr name for tagging.

**Comment by derhally** [comment]
Ok.  I tested that and that works.
