### ISSUE TITLE
MavenAuthenticateV0 artifactsFeeds values for Azure DevOps Pipelines

### ISSUE THREAD

**Issue by jlanawalt** [microsoft/azure-pipelines-tasks#11591]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MavenAuthenticate@0

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenAuthenticateV0

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Autoliv, aam-it_business_systems-team, autoliv-erp-common/20191017.1 (bfdbe14b)

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

When you create a new MavenAuthenticate task using the GUI tool and select an Azure DevOps Artifacts feed (Maven) to connect to, it uses FeedName for artifactsFeeds.

The value in artifactsFeeds is put into the settings > servers > server > id field of settings.xml.

This differs from the dev-azure-com-my_org-feedname repository/server id generated by the Connect to feed tool in Azure DevOps Artifacts so the authenticate fails and the build fails if you rely on artifacts in that feed.

It would be better if the MavenAuthenticate task setup tool was consistent with the Connect to feed tool in generating the Maven repository/server id for Azure DevOps Artifacts. I suggest having the new tool use the existing format because that's probably what's already in the pom.xml. 

The documentation does clearly give an example showing how the artifactFeeds values are mapped to the repository/server id, but the example also uses feed names like MyFeedInOrg1 instead of dev-azure-com-org-myfeedinorg1.

It would also be helpful if the documentation contained a full example of the mvn shell commands to match the default Maven build template, that way the intent of the user scripting the Maven steps would be more clear.

### Task logs

[ERROR] Failed to execute goal on project autoliv-erp-common: Could not resolve dependencies for project org:output-jar-name: Failed to collect dependencies at org-jar-in-feed:version: Failed to read artifact descriptor for org-jar-in-feed:version: Could not transfer artifact org-jar-in-feed:version from/to repository-id (https://pkgs.dev.azure.com/Autoliv/_packaging/Feed_Name/maven/v1): Not authorized -> [Help 1]

## Troubleshooting
Verified content of settings.xml using echo in script.

**Comment by aasim** [comment]
This fix has now been deployed. Both the MavenAuthenticate task and the connect to feed ui have the same behavior now0.
