### ISSUE TITLE
DockerInstaller does not work on ARM agent

### ISSUE THREAD

**Issue by winromulus** [microsoft/azure-pipelines-tasks#11596]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerInstallerV0

## Environment
- Server - Azure Pipelines
- Agent - Private
    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu 18.04 - ARM

## Issue Description

The DockerInstallerV0 task is limited to downloading Docker for x86_x64 only. It should detect ARM as well and pull the installer since the Docker installer repository does support it. (see https://download.docker.com/linux/static/stable/armhf/)

### Task logs
```
Starting: Install Docker 19.03.3
==============================================================================
Task         : Docker CLI installer
Description  : Install Docker CLI on agent machine.
Version      : 0.1.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/docker-installer
==============================================================================
Downloading: https://download.docker.com/linux/static/stable/x86_64/docker-19.03.3.tgz
Extracting archive
/bin/tar xzC /azp/agent/_work/_temp/e7230437-0424-43f9-83e3-98c5df742c52 -f /azp/agent/_work/_temp/docker-42a9ffc4-bc74-44fa-9712-556023b90681.tgz
Caching tool: docker-stable 19.3.3 arm
Prepending PATH environment variable with directory: /azp/agent/_work/_tool/docker-stable/19.3.3/arm
Verifying docker installation...
/azp/agent/_work/_tool/docker-stable/19.3.3/arm/docker --version
/azp/agent/_work/_tool/docker-stable/19.3.3/arm/docker: 1: /azp/agent/_work/_tool/docker-stable/19.3.3/arm/docker: Syntax error: Unterminated quoted string
##[error]Error: The process '/azp/agent/_work/_tool/docker-stable/19.3.3/arm/docker' failed with exit code 2
Finishing: Install Docker 19.03.3


```

**Comment by drmathias** [comment]
Would be really nice to have this fixed to be able to use Azure to set up CD to ARM devices like Raspberry Pi. This limitation is a massive turn off for me when it comes to Azure pipelines.

**Comment by vithati** [comment]
@drmathias , Sorry for inconvenience.  Can you please use script to download required tool and append tool path to PATH variable, till this issue is fixed.

**Comment by winromulus** [comment]
@vithati a question on this, why was this marked as an enhancement and not a bug? It clearly fails when pulling the tool for ARM due to a bug in the code (actually a hardcoded value).

**Comment by winromulus** [comment]
@sonayak - sorry, but I couldn't find the following information so I'm asking here:
How can I get this new version running in Devops?

**Comment by ds-ms** [comment]
It would take roughly about 3 weeks to reach all the rings in production.
