### ISSUE TITLE
HelmInstaller install wrong version

### ISSUE THREAD

**Issue by DanielHabenicht** [microsoft/azure-pipelines-tasks#11608]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmInstallerV0

## Environment
- Server - Azure Pipelines 
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/T-Systems-MMS/phonebook/_releaseProgress?_a=release-environment-logs&releaseId=116&environmentId=178

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description
The specified Verion in the Task: `Install Helm 2.14.2` is 2.14.2 but Helm Version 2.15.0 is installed from cache. 

Why??? Few days ago it was working as expected. 

### Task logs

Failing Task: 
https://dev.azure.com/T-Systems-MMS/phonebook/_releaseProgress?_a=release-environment-logs&releaseId=116&environmentId=178

Working Task:
https://dev.azure.com/T-Systems-MMS/phonebook/_releaseProgress?_a=release-environment-logs&releaseId=114&environmentId=174

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

![image](https://user-images.githubusercontent.com/13590797/67241730-42ffc780-f454-11e9-949e-3c1d57033cc7.png)
![image](https://user-images.githubusercontent.com/13590797/67241762-514de380-f454-11e9-82b4-452ba2414227.png)

**Comment by DanielHabenicht** [comment]
Well ok, seems like the checkmark overrides the setting... Very unintuitive. 

So I am proposing to show the version input only if the checkbox is not set.

**Comment by DanielHabenicht** [comment]
ok, the 1.0-preview has it implemented.

**Comment by DanielHabenicht** [comment]
When will you release the "official"  version of the task? @chshrikh

**Comment by chshrikh** [comment]
@vithati please check this
