### ISSUE TITLE
Task.SetVariable not working with underscores

### ISSUE THREAD

**Issue by robkott** [microsoft/azure-pipelines-tasks#11604]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Powershell

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipeline

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: vs2017-win2016

## Issue Description

Task 1 is an inline Powershell Script:
$major=1
$minor=2
$release=3
$revision=4

Write-Host "##vso[task.setvariable variable=Major;isOutput=true]$major"
Write-Host "##vso[task.setvariable variable=Minor;isOutput=true]$minor"
Write-Host "##vso[task.setvariable variable=Release;isOutput=true]$release"
Write-Host "##vso[task.setvariable variable=Revision;isOutput=true]$revision"
Write-Host "##vso[task.setvariable variable=Full;isOutput=true]$major.$minor.$release.$revision"
Write-Host "##vso[task.setvariable variable=FullU;isOutput=true]$major_$minor_$release_$revision"

Output Variable Reference name is BuildVersion

Task 2 is an inline Powershell Script:
Write-Host "$(BuildVersion.Full)"
Write-Host "$(BuildVersion.FullU)"

I was expecting the output to be:
1.2.3.4
1_2_3_4

Instead, the output is:
1.2.3.4
4

**Comment by molinch** [comment]
Same issue if you have double quotes, they get removed.
As a workaround, is there a way to escape special characters?

If it's not possible to escape characters, a suggestion could be to provide the value as a base64 string. Like we can provide a secret, it could be possible to provide a base64 encoded string.

**Comment by damccorm** [comment]
Hey @robkott sorry for the slow response - the reason this isn't working is that powershell accepts _ as part of a variable name. So its trying to read the above as `$(major_)$(minor_)$(release_)$(revision)`. Just saying `Write-Host "##vso[task.setvariable variable=FullU;isOutput=true]1_2_3_4"` works fine. See my repro here - https://dev.azure.com/damccorm-repros/setVariable/_build/results?buildId=241&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

@molinch You should be able to add quotes without issue - e.g. `Write-Host '##vso[task.setvariable variable=FullU;isOutput=true]1_2_3_4"'` works without problem. We do reserve some characters, see our task-lib for how to escape/unescape those - https://github.com/microsoft/azure-pipelines-task-lib/blob/f2c40a3884f54bce5ec4531174ad5b1a721d0727/node/taskcommand.ts#L105

**Comment by damccorm** [comment]
I'm going to close since this doesn't seem like a bug, please comment if you have further issues and we can reopen

**Comment by robkott** [comment]
So the 1, 2, 3, 4 are just place holders for this bug. In my actual script, they are computed values. 

I was able to make it work using this:
`Write-Host "##vso[task.setvariable variable=FullU;isOutput=true]$($major)_$($minor)_$($release)_$($revision)"`
