### ISSUE TITLE
Consider using permalinks when linking ARM templates

### ISSUE THREAD

**Issue by howlowck** [microsoft/azure-pipelines-tasks#11605]
## Note  
There are Azure Pipeline Tasks, specifically AzureResourceGroupDeployment, that instruct people, through its info tooltip, to copy and paste a ARM template GitHub link into their Pipeline task.  The example it provides is a `raw.githubusercontent.com` link that links to its master branch of arm template starter repo. This recommended practice will inevitably lead to broken pipelines when the ARM template changes in that repo.

The better approach is to instruct people to use a permalink of the file which includes the commit hash.  

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug/Feature

**Enter Task Name**: AzureResourceGroupDeploymentV2

list here (V# not needed):  
* [link to **AzureResourceGroupDeploymentV2** task tooltip message](https://github.com/microsoft/azure-pipelines-tasks/blob/bd01bcccc87f93cfad78dbe76902afe708e9610c/Tasks/AzureResourceGroupDeploymentV2/task.json#L121)
* [link to **AzureResourceManagerTemplateDeploymentV3** task tooltip message](https://github.com/microsoft/azure-pipelines-tasks/blob/bd01bcccc87f93cfad78dbe76902afe708e9610c/Tasks/AzureResourceManagerTemplateDeploymentV3/task.json#L141)

![image](https://user-images.githubusercontent.com/338265/67295489-d06f0600-f4ac-11e9-98ab-2481fe66831b.png)

**Comment by tejasd1990** [comment]
Thanks @howlowck for the suggestion. We will look into this and update.

**Comment by vinodkumar3** [comment]
@howlowck 
Thanks for the suggestion. I think the recommendations are inline to support the functionality of Continuous Integration and their triggers. Permalink will make users to update their pipeline after every new commit in selected file/repo.
