### ISSUE TITLE
Deploy to IoT Edge devices - Error

### ISSUE THREAD

**Issue by ToriParla** [microsoft/azure-pipelines-tasks#11641]
I'm getting an error while using the pipeline - task "Deploy to IoT Edge devices":

**error: the following arguments are required: --deployment-id/-d**

I see in the source code of the task,
(https://github.com/microsoft/azure-pipelines-tasks/blob/5214488bfc43a27f3faeb4589536af2bff387b39/Tasks/AzureIoTEdgeV2/deployimage.ts), that the az command is not generated with the --deployment-id option.

My result command is:
az iot edge deployment create --config-id XXXX t --hub-name XXXX --content /tmp/deployment_1571928916110.json --target-condition deviceId='XXXX' --priority 10 --output none

**Comment by PatricioVidal** [comment]
I am getting the same behavior. I was working fine yesterday.

**Comment by shaeussler** [comment]
I have the same error today.

**Comment by scoenen** [comment]
Same.  First noticed 10/24/19 at 10:45 CDT.

**Comment by DoychinDoychev** [comment]
Same thing started happening to me.
```
Starting: Azure IoT Edge - Deploy to IoT Edge devices
==============================================================================
Task         : Azure IoT Edge
Description  : Build and deploy an Azure IoT Edge image
Version      : 2.3.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
==============================================================================
Start deploying...
Deployment task is running in build pipeline? true
/home/vsts/work/1/s/config/deployment.json
Checking if the following file is a valid json: /home/vsts/work/1/s/config/deployment.json
Valid
Normalized deployment id is: deploymentid
/usr/bin/az iot edge deployment create --config-id deploymentid --hub-name AP-DEV --content /tmp/deployment_1572171765487.json --target-condition tags.environment='DEV' --priority 0 --output none
ERROR: az iot edge deployment create: error: the following arguments are required: --deployment-id/-d
usage: az iot edge deployment create [-h] [--verbose] [--debug]
                                     [--output {json,jsonc,table,tsv,yaml,none}]
                                     [--query JMESPATH]
                                     [--subscription _SUBSCRIPTION]
                                     --deployment-id CONFIG_ID --content
                                     CONTENT [--hub-name HUB_NAME]
                                     [--target-condition TARGET_CONDITION]
                                     [--priority PRIORITY] [--labels LABELS]
                                     [--resource-group RESOURCE_GROUP_NAME]
                                     [--login LOGIN]
##[error]Error: Error: The process '/usr/bin/az' failed with exit code 2
Finishing: Azure IoT Edge - Deploy to IoT Edge devices
```
Notice line /usr/bin/az iot edge deployment create `--config-id deploymentid` how the deployment id is passed as `--config-id` argument. I think this is where it is failing

**Comment by DoychinDoychev** [comment]
@navin22 @damccorm @vithati @vtbassmatt @asranja 
Guys, we really need this pipeline task working. Can you provide any updates on the issue, please

**Comment by shaeussler** [comment]
Use Azure CLI Task:

echo "Adding azure-cli-iot extension"
az extension add --name azure-cli-iot-ext
echo "Deleting old deployment"
az iot edge deployment delete --deployment-id $deployment_name --hub-name $hub_name
echo "Creating new deployment"
az iot edge deployment create --content iot-deployment-configuration.json --deployment-id $deployment_name --hub-name $hub_name --priority 0 --target-condition '*'

**Comment by ToriParla** [comment]
The task just worked a few minutes ago. Thanks
