### ISSUE TITLE
Vm Related Actions with V3 of ARM Deployment Task

### ISSUE THREAD

**Issue by elangelo** [microsoft/azure-pipelines-tasks#11654]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureResourceManagerTemplateDeploymentV3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The readme of V3 of the Azure Resource Manager Template Deployment mentions 'Removed all the VM related actions'
I'm wondering what i'm supposed to use instead then? Restarting of vm's is fine, i can do that with azure powershell. I'm mostly wondering about the deployment group agent installation

**Comment by bishal-pdMSFT** [comment]
@elangelo the V3 version will not have support for VM related operations. You should keep using V2 version of task if you want to use VM related functionality.
We will be creating a separate task for VM related functionality, but for the time you should use v2.
