### ISSUE TITLE
Download Secure File task: Can not set secure file by File Name by using GUI on Release pipeline

### ISSUE THREAD

**Issue by idubnori** [microsoft/azure-pipelines-tasks#11658]
## Required Information

Even if set a secure file **name** by UI, it is converted to GUID and registered. Should be configurable by GUID or file name.
Documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops#yaml-snippet

If the GUID is set, updating the secure file will change its GUID, so all release pipeline settings must be changed by manually.
Related issues: https://github.com/MicrosoftDocs/vsts-docs/issues/791#issuecomment-392486216
MicrosoftDocs/vsts-docs#791

*Type*: Feature, Bug
**Enter Task Name**: Download Secure File task

## Environment
- Server - Azure Pipelines, **On Release Pipeline**
- Agent - Private: 

## Issue Description
![image](https://user-images.githubusercontent.com/22805312/67828458-d735f280-fb16-11e9-890d-cfb48be65ae0.png)

**Comment by IanKemp** [comment]
Please can this be addressed! It's such a massive pain to have to go through EVERY PIPELINE that uses a file to update it when a new version of the file is uploaded!

**Comment by lbalceda** [comment]
Please!

**Comment by DanBradbury** [comment]
much pain. must bump.

**Comment by chinloyal** [comment]
Definitely a big problem

**Comment by movergan** [comment]
+1

**Comment by Grace-Dmello** [comment]
+1

**Comment by carterkraft** [comment]
+1

**Comment by DanBradbury** [comment]
+1

**Comment by keall-kja** [comment]
+1

**Comment by DanBradbury** [comment]
Any information from Microsoft team care to respond before this just becomes a +1 train?

@egor-bryzgalov ? first person I saw in Closed issues that was on Microsoft team

**Comment by anatolybolshakov** [comment]
Hi everyone, could usage of security file name be an option to resolve issue in this case? Are there any concerns about not using it?

**Comment by lbalceda** [comment]
@anatolybolshakov could you elaborate on that ? I think the issue is that we cannot use the file name

**Comment by anatolybolshakov** [comment]
Hi @lbalceda @idubnori could you please create ticket on https://developercommunity.visualstudio.com/search?space=21? This looks like an issue related to secure files and how they are handled - I guess it's possible to apply fix, but it requires additional check specifically about security implications and backward compatibility. There is nothing we could do on tasks side at the moment.
Please also note that this issue is not actual for yaml pipelines.

**Comment by anatolybolshakov** [comment]
@idubnori @lbalceda let me close this one here at the moment since it requires changes not only related to pipeline tasks side.

**Comment by IanKemp** [comment]
@anatolybolshakov this has already been reported at https://developercommunity.visualstudio.com/t/Unable-to-overwrite-secure-file-in-Azure/1181160?space=21 and closed as "not a bug" which is bulls**t. This is an obvious defect in DevOps and I don't particularly care if it's only in the non-YAML pipeline or your only priority is closing bug reports that "aren't your responsibility", you don't get to make this issue go away by closing it.
