### ISSUE TITLE
Question: is UseDotNet@2 able to get daily builds of dotnet SDK version 5?

### ISSUE THREAD

**Issue by heng-liu** [microsoft/azure-pipelines-tasks#11663]
May I know the list of SDK versions are supported for installation by this "UseDotNet@2" task? Is it able to add some version into the list, if the version we need is not yet supported?

We need to use some features only in .netcore 5.0 , so we need to install .NET SDK 5.0 in our build. It will be great if more version of SDK is supported by UseDotNet@2

**Comment by bishal-pdMSFT** [comment]
The supported SDKs is fetched from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
.Net Core 5.0 is not available in this list. @leecow is 5.0 going to be added to the release json?

**Comment by leecow** [comment]
Yes, it will be added when the first public preview is released. Same patter we have used for every channel.

**Comment by vinodkumar3** [comment]
@heng-liu stay tuned till first public preview version of .Net Core 5.0 get released. Closing this as nothing to be done as of now.

**Comment by heng-liu** [comment]
Thanks!
May I know how did you make the "PATH" environment variable persistent ? So the following tasks can see the change of "PATH".
Do you add it to profile or something else? Thanks!
