### ISSUE TITLE
VSTest2 Reruns and code analysis issues

### ISSUE THREAD

**Issue by dilandau2001** [microsoft/azure-pipelines-tasks#11660]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest2
Version      : 2.153.9

## Environment
Server: Azure Devops Server On Premise Update 1 RC2.

Agent: Self Hosted agent in a private machine.
Multiple agents with mixed versions: 2.124.0 and 2.153.1. All having similar results.

## Issue Description

We recently update our TFS on premise server from TFS 2018 to AzureDevops Server Update 1 RC2.
Our VSTest task is starting to behave very differently from what it worked before.
There are multiple differences.

We have configure test retry ("rerun failed tests"). It appears to be very handy for flacky tests.
When a rerun is executed the code analysis that is finally published only shows the coverage of the tests that did the rerun or a small subset of tests thus giving a very low coverage result.

I read in other topic that if a .runsettings is configured then it was not necessary to check the "Enable code coverage" checkbox in the task, but if I do it then there is no code analysis summary published at all. 

Also in the resulted codecoverage we can see dlls that were supposingly excluded by the runsettings.

Finally we miss the code coverage tab that appear in TFS 2018 on the web when a build finishes. Now this tab does not appear and there is no direct link to download code coverage results.

And at the end of the task codecoverage file and trx are deleted so we cannot feed them to following SonarQ tasks.

### Task logs
[log_12_9068.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3788649/log_12_9068.zip)
[log_12_9060.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3788650/log_12_9060.zip)

**Comment by ShreyasRmsft** [comment]
@dilandau2001 these were a couple of known gaps that were present that we have addressed in the latest hosted version of AzureDevOps and will be included in future OnPrem releases.

The coverage getting overridden is something that cannot be avoided in AzureDevops Server Update 1 RC2. You will have to disable re-run flaky tests.

As for providing a runsettings file with the coverage settings that should be possible. Could you please disable re-run and try?

**Comment by dilandau2001** [comment]
Hi.

we are providing a coverage file either with rerun and without it.

They key point is selecting the checkbox "Code coverage enabled".
If we unselect it the codecoverage is not published.
If we select it runsettings are ignored.

**Comment by ShreyasRmsft** [comment]
Okay. Please provide the full logs zip obtained by clicking "download all logs" with system.debug = true with the following input combinations

1) Rerun on and coverage on using the tick box
2) Rerun on and coverage on without the tick box and with the runsettings
3) Rerun off and coverage on using the tick box
4) Rerun off and coverage on without the tick box and with the runsettings

**Comment by ShreyasRmsft** [comment]
@dilandau2001 any updates here?

**Comment by dilandau2001** [comment]
Yes, I haven't forget this. But as this is not my main task it would take sometime.
I don't think I will be able to provide all combinations at once, but I will be doing each one on my spare time. I think I will be able to provide case 1, by the end of today

**Comment by dilandau2001** [comment]
First case:

[Case 1 - RerunOn_CodeAnalysisOn_WithNoRunSettings.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3835161/Case.1.-.RerunOn_CodeAnalysisOn_WithNoRunSettings.zip)

**Comment by ShreyasRmsft** [comment]
I see that test distribution is turned on.

2019-11-12T06:55:13.5382948Z ##[debug]distributionBatchType=basedOnTestCases
2019-11-12T06:55:13.5383237Z ##[debug]batchingBasedOnAgentsOption=customBatchSize

And that you have selected a custom batch size. Is this intentional? May i know why you have this option set?

**Comment by dilandau2001** [comment]
Nothing special. This setting was left behind after many tests trying to avoid the use of rerun option.
As we are now using rerun, we forgot to remove this.
Also we identified that giving a batch size was also better in terms of reducing the number of test conflicts, but worst in case of time.

**Comment by ShreyasRmsft** [comment]
@dilandau2001 turning off custom batching and re-run should solve the coverage reporting issue for you.

**Comment by ShreyasRmsft** [comment]
Once you are unblocked by making these changes we can maybe make a cloned definition and get to the RCA of what is going wrong when you have these options enabled on your current Azure DevOps onprem version

**Comment by dilandau2001** [comment]
This is the case 2. 
Unfortunatelly I was not able to reproduce my main issue. And it is publishing coverage in all my latest tries. There is some configuration combination I had in the past that reproduced the issue more consistently.
[Case 2 - RerunOn_CodeAnalysisOff_WithRunSettings.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3845311/Case.2.-.RerunOn_CodeAnalysisOff_WithRunSettings.zip)

Anyway, during the preparation of this second set of tries we found that there are cases were the Vstest2 ends with successfull even with failed test. 

![image](https://user-images.githubusercontent.com/12834469/68838531-12135b00-06bf-11ea-84b3-9def11ae25fb.png)

It seems, the combination for this to happen is, rerun activated, and lots of failed test (the rerun threshold is passed.) Not sure if the "automatic batch size" influence on this though.
Here is the log:

[Case 2 - RerunOn_CodeAnalysisOff_WithRunSettings_SuccessWithFails.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3845312/Case.2.-.RerunOn_CodeAnalysisOff_WithRunSettings_SuccessWithFails.zip)

**Comment by ShreyasRmsft** [comment]
Note: we do not support re-running of NUnit and XUnit data driven tests today due to naming convention issues.

In this case those failed data driven tests will not get re-run potentially leading to this state.

**Comment by ShreyasRmsft** [comment]
The re-run shortcomings are something we are planning on addressing in the later releases.

**Comment by dilandau2001** [comment]
> @dilandau2001 turning off custom batching and re-run should solve the coverage reporting issue for you.

Having or not a custom batching size seems no difference in terms of coverage publishing.

Having rerun activated is the one that really make difference. With it on, Coverage results varies a lot, and also (in the past) sometimes coverage was not published at all. Unable to currently reproduce it.

The thing is we have some "flacky" tests that usually fail and rerun speeds up this blocking points.

Our current solution is to run 2 agents in pararell, one focusing on build and the other focusing on coverage. The one for coverage is just used for reportings and it is not taken into account to block a pull request. The one for coverage does not use reruns, so it usually fails. And the one for the pull request make use of reruns.

Good to know this is addressed soon.

**Comment by dilandau2001** [comment]
> Note: we do not support re-running of NUnit and XUnit data driven tests or tests with custom display names containing special characters (which seems to be case having taken a look at the logs.) today due to naming convention issues.
> 
> In this case those failed data driven tests will not get re-run potentially leading to this state.

Interesting. didn't know about that.
Although I am surprised we are using special characters unless "_" is a special character. is it?

**Comment by ShreyasRmsft** [comment]
one such sample test, it has a plus (+) in the name

MyCompany.MyProject.Vsm.WebApi.IntegrationTests.Controllers.PtzReservationControllerTests+ClosePtzConnection.WhenCloseIsCalledWithAnUnknownPtzConnectionId_ThenBadRequestExpected

**Comment by dilandau2001** [comment]
Hi.
In our unit test file format we create a new class per function to test.

class Unitestclass()
{
      classs FunctionToTest()
      {
              [Fact]
              public void Test()
              {
              }
      }
}

during vstest phase, those test are translated in the log as 
Unitestclass+FunctionToTest.Test()

That is something that the vstest is doing by itself. Anyway, I don't think that is the issue, as most of our test follow that format and most of them are being rerun with no problems.

**Comment by ShreyasRmsft** [comment]
@dilandau2001 sorry got busy the last few days, will get back to this in a bit. Apologies again.

**Comment by ShreyasRmsft** [comment]
I will need to testplatform diag files present in the build logs zip to confirm what the names of tests returned by the testplatform and the adapter are. Could you please upload the full zip for this scenario Case 2 - RerunOn_CodeAnalysisOff_WithRunSettings_SuccessWithFails.zip

**Comment by dilandau2001** [comment]
After some more investigation you are right.

Those xunit test that make use of [Theory] attribute won't be found during rerun slice and so they are considered correct even though they are not, completelly missleading build results.

This is because the name of the test is not scaping the "(" and ")" that the theory introduces to test names. (Those that just include the + character works fine)

This means that we cannot use rerun feature in our solution until those type of tests are supported, which is very sad because rerun is a very handy feature for all other tests.

**Comment by ShreyasRmsft** [comment]
I can understand your position. We have it in our backlog to see if we can some how workaround this limitation from our end. But we don't have an exact estimate of when we will be picking it up.

**Comment by dilandau2001** [comment]
Ok.
We will stop using rerun in the meantime.
Thanks for the feedback.

**Comment by ShreyasRmsft** [comment]
Just a thought, you could split your tests into 2 runs and enabled re-run on the ones which are not data driven.
