### ISSUE TITLE
Update Report Generator to 4.3.3

### ISSUE THREAD

**Issue by Galad** [microsoft/azure-pipelines-tasks#11666]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResults

## Environment
- Server - Azure Pipelines

## Issue Description

Current version of ReportGenerator has a bug that prevents to publish a code coverage report in the Cobertura format when it contains number with an exponenet (`8.123E-05`). See https://github.com/danielpalme/ReportGenerator/issues/291
This is fixed in version 4.3.3 of ReportGenerator.

**Comment by nishantms** [comment]
Report Generator version is updated and fix will be available in M172 update.

**Comment by IvanAlekseev** [comment]
Hi @nishantms. I can't find any mention of that in release notes for M172 - https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-172-update
And I still see this in coverage report 
```
Generated by: ReportGenerator 4.3.2.0
```

**Comment by nishantms** [comment]
@IvanAlekseev 
It is not mentioned in the release notes as it is used internally  by the "Publish code coverage results" Task.
i tried to repo , however i am seeing the correct version 

![Annotation 2020-07-16 140533 PNG](https://user-images.githubusercontent.com/63423133/87649152-b2011700-c76d-11ea-8678-aa8740ea0472.jpg)

Can you please help me with your usecase

**Comment by IvanAlekseev** [comment]
@nishantms just run it today and see correct version now. Thanks

**Comment by nishantms** [comment]
@Galad / @IvanAlekseev : Thats Great, I am going ahead and close this issue now
