### ISSUE TITLE
provide a way to lock edge module images after successful push to Azure Container Registry

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-tasks#11662]
We use gitversion to generate build number during build of iot edge modules and this same build number is assigned to the image tag. Sometimes, an incorrect configuration for gitversion.yml causes the same build number to be generated for a different commit. By default, **Azure Container Registry** allows the same image tag to be re-used by a new image hash, essentially the same image is updated. To prevent this situation from happening, it would be good to provide a Lock image after push checkbox in the **Azure Iot Edge** task when action is **push module images** . This will prevent future builds that generate duplicate tags from being able to overwrite existing images. I thought locking a repo would do the trick but as it turns out, it also prevents me from being able to push a new image with new tag onto that repo. There does not seem to be an option specified at the repo level to be able to prevent existing tags from being updated. It is very tedious to lock images after the fact since it can only be done one tag at a time per repo.

**Comment by blackchoey** [comment]
Hi @tristanbarcelon 
To prevent pushing to an existing image, you can refer following documents:
For Azure Container Registry: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock
For Docker Hub: https://docs.docker.com/ee/dtr/user/manage-images/prevent-tags-from-being-overwritten/
The goal of Azure IoT Edge push module images task is to help you push all images for your IoT Edge solution. Since different container registry has different ways to manage the policies to images, it would be better to prevent pushing to an existing image through each container registry's setting independently.

**Comment by tristanbarcelon** [comment]
Hi @blackchoey ,

I used the same commands from the link you provided to lock specific images in Azure Container registry. Unfortunately, I had to issue these commands after the build pipeline has already completed and not during. It uses the Azure Iot Edge azdo task below.

![image](https://user-images.githubusercontent.com/5810165/68146036-17c1b180-ff05-11e9-8232-81f407c8ebc3.png)

This task already has all the information about:
- container registry name
- azure subscription
- all the container images that were just built and how to push them based on the **Container registry type**. 

Given everything that it already knows, wouldn't it be possible to enable the ability to lock images when type = Azure Container Registry?

The alternative for me would be to write a script that would run after the Azure Iot Edge publish step and:

- parse the deployment.template.json and to find all the repo names and tags
- issue `az acr repository update --name <registryname> --image <myrepo>/<myimage>:<tag> --write-enabled false` command for each and every image that was just uploaded

**Comment by blackchoey** [comment]
@tristanbarcelon The Azure CLI task will do the login and set subscription steps for you. You just need to select the Azure Subscription connection that stores your image. No need to store the subscription info as variables in your pipeline.
In the meanwhile, it's better to have the lock images task as a separate step so you can compose each kind of tasks according to your actual requirement. Providing image locking feature with enough flexibility in the push task will make the task too complicated. We expect the task do one thing and do it well.

**Comment by tristanbarcelon** [comment]
Hi @blackchoey, is there an easy method for finding all the container images that have just been built and pushed by the Azure Iot Edge tasks without writing code that knows how to parse deployment.template.json? Most of our container images have an image property defined as a variable: ${MODULES.<module_name>.amd64}. I would prefer to call the [acr api for locking images](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock#lock-an-image-by-tag) while looping through the images that have just been pushed.

**Comment by blackchoey** [comment]
You don't need to parse the deployment.template.json. The image tag is defined in the `repository` property in module.json of each module, the task will expand the environment variables in `repository` property and append the platform as postfix.
