### ISSUE TITLE
AzurePowershell Task - Cannot Find ../profile.ps1

### ISSUE THREAD

**Issue by grik001** [microsoft/azure-pipelines-tasks#11678]
Hi,

When attempting to execute the Azure PowerShell task on Azure DevOps I keep getting the below error.

**Could not find a part of the path 'C:\Users\VssAdministrator\Documents\WindowsPowerShell\profile.ps1'.**

Is this a known issue?

**Comment by niadak** [comment]
@grik001 , This is not a known issue. Can you please share the debug logs for the failed task?

**Comment by eaarora-ms** [comment]
@grik001  Can you please share pipeline logs with system.debug set as true?

**Comment by 20shivangi** [comment]
@grik001 Please share the debug logs with system.debug set as true in your pipeline.

**Comment by eaarora-ms** [comment]
Closing due to no response from the customer. Please comment if you want to re-open.
