### ISSUE TITLE
How to pass secrets to a script run by the AzurePowerShell task?

### ISSUE THREAD

**Issue by joseharriaga** [microsoft/azure-pipelines-tasks#11695]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzurePowerShell

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: Both 
    
## Issue Description

The docs about [Logging commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands) say:
"Secret variables are not passed into tasks as environment variables and must instead be passed as inputs."

However, the docs on [Variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables) say:
"It is recommended that you use the script's environment in order to pass secrets to the script. Operating systems often log commands for the processes that they run, and you would not want the log to include a secret that you passed in as an input."

So I'm a little bit confused about the proper way to use secrets, specifically in the case of the AzurePowerShell task. If I understand correctly, the former doc is saying: "You should pass secrets as inputs to your tasks", but then the latter doc is saying: "In the specific case of a PowerShell task, when you need to pass secrets to the scripts, do not pass them as parameters. You should map the secrets as environment variables and use these instead." Am I interpreting the docs correctly?

If so, what is then the appropriate way to pass secrets to the script that will be run by an AzurePowerShell task given that this task does not have an "env" parameter like the PowerShell task does?

**Comment by chperich** [comment]
@joseharriaga: Both the docs were essentially trying to highlight the point that if you have a secret variable, it is not going to be available as an environment variable like other non secret variables.

There are other ways in which secrets can be consumed. Like, passing it as part of inputs, or consuming it as $(MySecret) as part of your script, or adding an explicit mapping to make it available as part of your environment variables.

PowerShell task documentation is pointing out that the first option of passing secrets as inputs might not be a good idea as it might show up in operating system logs. Instead you can use the other 2 approaches. 

- you should be able to refer to $(MySecret) as part of your script. (or)
- Add an mapping:
```
  env:
      MY_MAPPED_ENV_VAR: $(mySecret)
```
And use **$env:MY_MAPPED_ENV_VAR** wherever you intend to use the secret.

**Comment by chperich** [comment]
Closed this Chaitanya ji.
