### ISSUE TITLE
"Complete Swap" does not generate a deployment record

### ISSUE THREAD

**Issue by ntwentyfive** [microsoft/azure-pipelines-tasks#11702]
Using the task to perform a slot swap updates the deployment record on the app service, and changes the deployment type to "SlotSwap".  However, using the task to _complete_ a previously previewed swap does not update the deployment record in the app.

I think the code just needs to update the cases for deployment updates at the end, but it's not clear to me if this has more far-reaching implications.
`try {
        switch(action) {
            case "Swap Slots": {
                if(appServiceSourceSlotUtils && appServiceTargetSlotUtils && updateDeploymentStatus) {
                    let sourceSlotKuduService = await appServiceSourceSlotUtils.getKuduService();
                    let targetSlotKuduService = await appServiceTargetSlotUtils.getKuduService();`

**Comment by eaarora-ms** [comment]
@ntwentyfive  Sorry for the delay. I will look into it and update you soon.
