### ISSUE TITLE
Powershell v2 task inline option is limited to 5000 characters and temporary file is not deleted after execution

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-tasks#11701]
Is there a specific reason for limiting inline powershell to 5000 chars and for $filePath to not be deleted in the finally block upon completion.

**Comment by damccorm** [comment]
Which version of the powershell task are you using?

> limiting inline powershell to 5000 chars

We don't do this from our side IIRC. If there is a limit, I'm guessing it comes from the agent. I know inputs get put in as env variables, so it might have to do with the size of the environment block. If that's a blocker, I'd recommend just checking in the script.

> for $filePath to not be deleted in the finally block upon completion.

Not totally sure what you're asking here - we don't inject anything into the script you're running, so we don't have a finally block. With that said, no variables we set will be persisted to future steps.

**Comment by tristanbarcelon** [comment]
Hi @damccorm . I'm using Powershell v2 task and I think it's [line 74](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/task.json) which enforces this limit.

With regards to the deletion of $filePath, I suppose I should have mentioned that I'm referring to our privately hosted agents and not the ones in Azure. There appears to be a finally block in [powershell.ps1](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/powershell.ps1) but I was hoping for the $filePath to be deleted to avoid proliferation of tens of thousands of [guid].ps1 files in agent's temp directory.

**Comment by damccorm** [comment]
> I'm using Powershell v2 task and I think it's line 74 which enforces the 5000 char limit.

Whoops, so it does. Asked around, it looks like this limit was basically put in place because performance starts to degrade on our side when variables get too large. I don't think its strictly necessary that its _exactly_ 5000, but that we found that was a good limit for the vast majority of use cases.

Is there any reason you can't use checked in scripts?

> There appears to be a finally block in powershell.ps1 but I was hoping for the $filePath to be deleted to avoid proliferation of tens of thousands of [guid].ps1 files in agent's temp directory over time.

The tempDirectory [should be cleaned by the agent between each run](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables) - is this not the behavior you're seeing?

**Comment by tristanbarcelon** [comment]
Hi @damccorm . I wouldn't mind using scripts checked into source. However, the task will only be able to access scripts in the same repo as the code being built at that time. It would be troublesome to copy the same scripts to each and every repo that needs it. Likewise, we're staying away from git submodules at this time so that too is not a viable option. In the meantime, any powershell script we have that exceeds 5k chars requires me to use this [inlinepowershelltask](https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Build-InlinePowershell) to overcome limitations. While this works, it litters my $ENV:TEMP my tens of thousands of temp files. I've filed a [PR and code has been merged](https://github.com/XpiritBV/Vsts-Build-Task-InlinePowershell/issues/17) but the version in marketplace has not been updated yet.

I was mistaken with the behavior of these temporary ps1 files. It turns out they are clean up after each and every run even though it's not specified in the finally block. You can ignore this part.

**Comment by damccorm** [comment]
@tristanbarcelon I think right now this is something we're hesitant to increase for the reasons I mentioned above.

> the task will only be able to access scripts in the same repo as the code being built at that time. It would be troublesome to copy the same scripts to each and every repo that needs it.

I'm a little confused here - won't you currently need to copy the same scripts to each pipeline that uses them? I'm not sure I understand why one is more burdensome than the other.

**Comment by tristanbarcelon** [comment]
Hi @damccorm. We have one build definition/pipeline per git repo. With at least 60+ git repos in one team project, it'd be too cumbersome too cumbersome to copy these scripts and their subsequent updates to all of them. This is why we separate these scripts into task groups that are referenced in each repo's build pipeline. Script fixes are made in the task group one time and the next build will immediately use the updated version.

**Comment by damccorm** [comment]
Huh, that's an interesting use case. We're looking into making some of these sorts of use cases easier, so hopefully we will have a better solution soon.

One thing that would work here is having a dedicated repo for your scripts. So then, your inline script could look something like:
```
if (Test-Path myRepo) {
   git checkout myRepo
}
myRepo\myPowershellScript.ps1
```

**Comment by tristanbarcelon** [comment]
Would that work if a build is occurring for RepoA? I'm thinking out loud here because at that point in time, Build.SourcesDirectory variable for that build agent would reflect root of RepoA that was just cloned or pulled. Do you have an updated guide on how I might create custom tasks and publish them into our azure devops account?

So far, I've gathered this:

- https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md
- https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops

I'm not able to find documentation on how to publish these task so they are visible in our azure devops organization/team project. tfx-cli looks like it's been deprecated too. Do you know what toolchain I'd need to publish custom tasks/extensions?

**Comment by damccorm** [comment]
> Would that work if a build is occurring for RepoA? I'm thinking out loud here because at that point in time, Build.SourcesDirectory variable for that build agent would reflect root of RepoA that was just cloned or pulled.

I'm not sure I follow - what is RepoA in this scenario? Doing a normal git checkout in a script shouldn't change any of your pipeline variables

> Do you have an updated guide on how I might create custom tasks and publish them into our azure devops account?

This is for node, but the walkthrough is more or less the same for powershell, you just need to change your task.json to [target powershell](https://github.com/microsoft/azure-pipelines-tasks/blob/bf54869d9a6a9bca6a8896ed9e37fe9d3d367abe/Tasks/AzurePowerShellV4/task.json#L169) instead of node, and obviously it would use a powershell script instead of node.

> tfx-cli looks like it's been deprecated too. Do you know what toolchain I'd need to publish custom tasks/extensions?

tfx-cli is still alive and well - it got commits and got published as recently as yesterday - https://www.npmjs.com/package/tfx-cli

**Comment by tristanbarcelon** [comment]
Hi @damccorm , if i create a repo with 2 or more custom tasks and want to bundle them as part of an extension, what should the folder structure look like? Likewise, what do I need (in terms of permissions, marketplace account, etc) to make these custom tasks visible in our azure devops organization? Should I be using `tfx extension share` or `tfx extension publish` account?

**Comment by damccorm** [comment]
Hey, sorry - just saw this! Would you mind asking this in the tfx-cli's repo here - https://github.com/Microsoft/tfs-cli? They'd be better equipped to answer these questions.

**Comment by tristanbarcelon** [comment]
@damccorm , thanks for the feedback. I'll post the tfx-cli question over to another repo. I do have another question related to writing custom tasks specifically targeting powershell core. Is my only option at this point copying much of the code that's in the [powershellv2 task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PowerShellV2)? Is there another execution besides Powershell3 and Node at this point for custom tasks? I have a need to support custom tasks on linux where each task contains more lines of code than can be stored in the existing powershellv2 task via the inline option. What are my options at this point since I'm not really familiar with node.

**Comment by damccorm** [comment]
@tristanbarcelon we don't have another execution handler, our recommendation is to use Node for cross-platform tasks. If you want to use powershell core, you should just be able to exec it using node (similar to the powershell task that you pointed out)
