### ISSUE TITLE
Using Keyvault sercrets doesnt work with embedded variables

### ISSUE THREAD

**Issue by GlamTam** [microsoft/azure-pipelines-tasks#11716]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: Azure Key Vault - download azure key vault secrets

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

cannot fetch a key vault secret when using embbed variables like $(foo$(bar)).

where $(bar) is a pipeline variable 'dev' and $(foo$(bar)) resolves to a secret in the keyvault.

The resolving of the variables works, however still the following error pops up:

2019-11-08T10:15:37.9451108Z ##[error]Cannot process argument transformation on parameter 'AzureAdObjectId'. Cannot convert value ""$(foo-dev)"" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

2019-11-08T10:15:37.9451108Z ##[error]Cannot process argument transformation on parameter 'AzureAdObjectId'. Cannot convert value ""$(foo-dev)"" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."

**Comment by vithati** [comment]
@GlamTam , Can you elaborate more?  From error I see $(foo-dev) variable not declared in release. Expanding variables inside another variable will not work. $(foo($bar)) will expand to $(foo-dev) if bar value is '-dev', event you declared 'foo-dev' in variables it will not expand $(foo-dev).

**Comment by GlamTam** [comment]
hi vihait, I want variable $(foo($bar)) to expand to $(foo-dev), since 'foo-dev' is the name of a secret in the keyvault. Using the 'get keyvault secrets' tasks I want to replace the variable $(foo-dev) with the value of the secret with the name foo-dev in the keyvault. However, currently the variable expansion from $(foo($bar)) to $(foo-dev) works, but the lookup in the keyvault fails. I would like to see the flow as follows:  $(foo($bar)) is expanded to $(foo-dev) by pipeline variable, afterwhich $(foo-dev) is replaced by the corresponding value of the keyvault secret with the same name 'foo-dev'.

**Comment by vithati** [comment]
@GlamTam , Expanding variables inside another variable will not work, it is same for keyvault secrets.
