### ISSUE TITLE
What is the expected cadence of updating the AZ Modules referenced in AzurePowerShellV4 task?

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/azure-pipelines-tasks#11713]
**Type**: Questions

**Enter Task Name**: AzurePowerShellV4 

What is the expected cadence of updating the AZ Modules referenced in AzurePowerShellV4 task?

Also would it be worthwhile having a parameter for define the AZ Module version?

**Comment by 20shivangi** [comment]
@bradwillis 
Presently the latest Az version we are supporting is 2.6.0 in AzurePowerShell4. We usually update the Az modules whenever there is some major change in Az module version. We will soon add support of latest version of Az module i.e. 3.0.0 in task

**Comment by 20shivangi** [comment]
Closing this issue.

**Comment by brwilkinson** [comment]
@20shivangi  @bradwillis 

I'll keep an eye out for the 3.0.0 update.

I am waiting on AZ 2.8.0 or greater so that I can use zero length copy loops in my deployment templates.
