### ISSUE TITLE
How to Persist the Response of an HttpRequestChain GET Request to Output Variable

### ISSUE THREAD

**Issue by Dejulia489** [microsoft/azure-pipelines-tasks#11720]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: InvokeRestApi

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: life-pacificlife, DevOps, releaseId 6294

- Agent - Hosted or Private:  ServerGate
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

Is it possible to store the response of an http get request made by the HttpRequestChain of a serverGate task to a variable? I am able to persist a single string but I am unable to store the json object because a of TypeCastException. Is there a way to convert the json to a string? 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by Dejulia489** [comment]
Forcing the request headers to text/plain still returns a JSON object. What is making the http requests on the server side?

**Comment by nishubansal** [comment]
Can you share details about your use case? What do you want to do with string?

As of now we don't have direct method to convert JSON to string. Although Using HttpRequestChain handler we have written some tasks where we are passing object from 1 request to another.

[Task using HttpRequestChain](https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentlessJobVariableToReleaseVariable/task.json)

**Comment by Dejulia489** [comment]
This is what I was looking for, do you know if there methods available to server gate tasks are documented anywhere? 

jsonpath()
addFieldToJsonAndSerialize()
addObjectToJsonAndSerialize()

**Comment by Dejulia489** [comment]
Is the EndpointUrl scoped to a different group of variables...

variables['myVariableName'] will return the correct value in the execution options, but when I add this same expression in the EndpointUrl it returns thr following error. 

` Variable with name variables['myVariableName could not be found for the given service connection.`

**Comment by ObsidianVoid** [comment]
@Dejulia489 Apologies for the long delay in response. In case you are still blocked by this issue, using "$(myVariableName)" instead of "variables['myVariableName']" should work. Let me know if you need any further assistance.

**Comment by Dejulia489** [comment]
Because the variable name was dynamic I was unable to use $(myVariableName). I had to use an output variable to set the dynamic variable's value to an output variable. 

Any documentation you may have would be very helpful. 

Thanks!

**Comment by ObsidianVoid** [comment]
Can you please help me understand your scenario. By dynamic variable, are you referring to output variables section of the execution options? It sounds similar to what is done in line 406 here:
https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/ServiceNow/Src/Tasks/CreateAndQueryChangeRequest/CreateAndQueryChangeRequestV2/task.json

It would be helpful if you could share some code snippets.

**Comment by Dejulia489** [comment]
> This is what I was looking for, do you know if there methods available to server gate tasks are documented anywhere?
> 
> jsonpath()
> addFieldToJsonAndSerialize()
> addObjectToJsonAndSerialize()

Following up. Is this documented anywhere?
