### ISSUE TITLE
npm task - support scoped registries

### ISSUE THREAD

**Issue by jderose9** [microsoft/azure-pipelines-tasks#11724]
**Question, Bug, or Feature?**  
Feature (bug?)

**Enter Task Name**:  NpmV1

## Environment
- Server - Azure Pipelines
    
## Issue Description
I do not wish to use the upstream feeds of the Azure Artifacts feed. I don't care about or want to configure the other registries that consumers of my package want to use in their application.

Instead, I would like to be able to create a scoped registry to get only the packages from my organizations scope from the Artifacts feed.

If I create a scoped registry in an .npmrc for my organization's artifact feed when consuming a package from the feed, the npm task authentication from "Registry I select here" doesn't work. It instead replaces the default public registry with the azure feed.

Additionally, when publishing, the authentication doesn't work if I assign my Artifacts feed in my publishConfig registry url in my package.json rather than replacing the default registry via the .npmrc.

Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/..., Basic realm="https://pkgsprodcus1.pkgs.visualstudio.com/", TFS-Federated

**Comment by aasim** [comment]
Hi @jderose9 - Are you using the on-prem or the hosted product? 

Aasim

**Comment by jderose9** [comment]
@aasim I am using the hosted product (Azure DevOps Services).

**Comment by zleight1** [comment]
We are using on premise, and the ability to use scoping would really help. We recently had to switch to calling npm from a command line because of issues with the artifact manager registries upstream sources.

**Comment by jmyersmsft** [comment]
We as a team are in the process of deprecating our "kitchen sink" packaging tasks in favor of the 
"npm Authenticate" task and a script you write yourself. My recommendation is therefore:

1. Make sure your scoped registries are configured in a .npmrc that you have checked in to your repo (don't put passwords or other authentication material there!)
2. Use the "npm Authenticate" task to augment that .npmrc with credentials. This should work fine with scoped registries
3. Use a script task (command line, PowerShell, etc.) to call npm

We don't have support for publishConfig, but if the registry exactly matches one of those listed in the .npmrc it should still work with "npm Authenticate".
