### ISSUE TITLE
NPM Install failing to download node-saas (404)

### ISSUE THREAD

**Issue by RickBlouch** [microsoft/azure-pipelines-tasks#11722]
## Required Information
Npm install started failing yesterday with a 404 trying to download node-saas.  No changes made to our code or Task configuration.

**Enter Task Name**: NpmV0

## Environment
Azure Pipelines

organization name: HealthPay24
team project name: HealthPay24
build definition name: HP24 Build - Dev
build number: 20191109.1  (All builds have been failing since yesterday for this reason)

- Agent - Hosted: 
    
Agent Queue Name:  Hosted VS2017

## Issue Description

Npm version 0.  the task is issuing the Install command.

### Task logs

Task         : npm
Description  : Run an npm command
Version      : 0.2.27
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)

[command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" config list"
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.12.0 node/v12.13.0 win32 x64"

; environment configs
cache = "C:\\npm\\cache"
prefix = "C:\\npm\\prefix"

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\a\1\s\Source\HealthPay24\src\HP24.ProviderPortal
; HOME = C:\Users\VssAdministrator
; "npm config ls -l" to show all defaults.

[command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install"

> node-sass@4.10.0 install D:\a\1\s\Source\HealthPay24\src\HP24.ProviderPortal\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node": 

HTTP error 404 Not Found

### Additional Information

The last working build (build number: 20191107.6) was using this node-saas version: https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-64_binding.node

**Comment by mintyfusion** [comment]
Guys, the build system is broken and no action has been taken. What is the ETA?

**Comment by ponkumarpandian** [comment]
I am also facing the same issue. Please let us know any workaround?

**Comment by RickBlouch** [comment]
If this is blocking for anyone, until they fix it, you can use the "Node.js tool installer" task and have it target a prior version of Node.

**Comment by bcbuddy** [comment]
OK good so it's not just me. Our build started failing as well with this exact error.

**Comment by StephenLarkin** [comment]
I think that this is actually something on node-sass's end. I've been seeing this issue cropping up occasionally as well. It seems to happen whenever a new version of node-sass is released. The reason that I think it might be something that node-sass is doing is that it just happened to one of our new starters when they first tried to clone an older version of our repo.

It's something that I've been meaning to bring up with them for the past week.

**Comment by salvmd** [comment]
Redirecting since this is an issue related to the version of node shipped in the agents and not Artifacts.

**Comment by desaiprerak** [comment]
hi, Is there any progress on the issue fix? This is getting escalated now

**Comment by edgarrs** [comment]
This is a specific issue with the npm package node-sass.
