### ISSUE TITLE
SqlAzureDacpacDeploymentV1 - Improper credential parameter handling

### ISSUE THREAD

**Issue by DanniJuhl** [microsoft/azure-pipelines-tasks#11723]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- Agent - Hosted or Private: 
    Hosted
    windows-2019, vs2017-win2016
## Issue Description
I am unable to execute Sql Scripts against an Azure Sql Database. 

It appears as though when using the task to execute sql scripts, may it be SqlFiles or inline, the functions Run-InlineSql & Run-SqlFiles doesn't have null handling on -sqlUserName, -sqlPassword & -connectionString, meaning it can ever execute, as it's not possible in the GUI to provide both a connectionstring and credentials at the same time, leaving the opposite of the selected as null values.

In the attached logs, line 485 you can see the parameters -sqlUserName and -sqlPassword are empty, as the powershell parameters are null. 

As the issue originates when executing the two mentioned functions, we could resolve it relatively easy by creating an if statement in the switch $taskNameSelector (DeploySqlAzure.ps1 line 132), based on $authenticationType. 

### Task logs
Attached as file [SqlAzureDacpacDeployment_LogOutput_Plaintext.log](https://github.com/microsoft/azure-pipelines-tasks/files/3827719/SqlAzureDacpacDeployment_LogOutput_Plaintext.log)

### Error logs
```
2019-11-09T19:26:41.3157557Z ##[debug]Failed to reach SQL server {AzureSqlServerName}.database.windows.net. One or more errors occurred.
2019-11-09T19:26:41.3258498Z ##[debug]Error Message : System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: One or more errors occurred.
```

As the errors aren't really pushed into DevOps, I decided to pull this task down, and execute the commands directly on my computer. That gave me a bit more information, as seen below. 
```
Run-InlineSql : Missing an argument for parameter 'sqlUsername'. Specify a parameter of type 'System.String' and try again.
```

**Comment by Ajay-MS** [comment]
@DanniJuhl  

I am unable to repro the issue from my end. Can you please share the email Id so that we can have a call to better understand the scenario.

**Comment by DanniJuhl** [comment]
@Ajay-MS - You can catch me on daju (at) inspari dot dk

For good measures, here's the repro steps: 

1. Use Azure SQL Database Deployment task in release pipeline
2. Connect to Azure through Service Connection
3. Use Active Directory - Password authentication type
4. Specify server, database, login and password (parameters in my case)
5. Set Deploy Type to SQL Script File
6. Reference .sql file from artifact
7. Firewall is set to autoDetect & rule deletion afterwards. 

Expected result: Script executed against the database specified. 
Result: Described in initial issue.

**Comment by eaarora-ms** [comment]
@DanniJuhl  Closing this after syncing offline. Great to see you unblocked now.
