### ISSUE TITLE
Windows machine file copy task v1 error on new build server

### ISSUE THREAD

**Issue by siromega** [microsoft/azure-pipelines-tasks#11749]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Windows Machine File Copy v1

## Environment
- Server - Azure DevOps (cloud)
- Agent - Private (on-prem agent) Windows Server 2016 standard

## Issue Description
Moving agents to a new server. Installed the new agent on the server, but now Windows machine file copy task v1 tasks are failing on the new server at the end of the file copy process. Error message is as follows: 
[error]System.Management.Automation.RemoteException: The 'Get-LocalizedString' command was found in the module 'Microsoft.TeamFoundation.DistributedTask.Task.Common', but the module could not be loaded. For more information, run 'Import-Module Microsoft.TeamFoundation.DistributedTask.Task.Common'

When I ran the import module command on the server I got the error "Import-Module : The specified module 'Microsoft.TeamFoundation.DistributedTask.Task.Common' was not loaded because no valid module file was found in any module directory.". However this happened on both servers where this task worked, and on servers where it didn't work. 

## Troubleshooting
Rebooting the server did not fix the issue.
Task v1 works on existing build agents. 
Changing the version to v2 and it worked on the new servers, but we have 100s of build pipelines that use this task so it would be a lot of work to change all of them to use v2 of this task. 

I would be happy to email any more information needed (unredacted logs, Azure DevOps tenant, etc.).

**Comment by eaarora-ms** [comment]
@siromega Hi, can you please share the complete pipeline logs with system.debug set as true?

**Comment by siromega** [comment]
I have prepared the log files, I need a secure (non-public) way to send them. Thank you.

**Comment by eaarora-ms** [comment]
@siromega  You can mail me at eaarora@microsoft.com

**Comment by eaarora-ms** [comment]
> I have prepared the log files, I need a secure (non-public) way to send them. Thank you.

Received logs. I will get back to you with a solution.

**Comment by eaarora-ms** [comment]
@siromega We would recommend you to move to Azure File Copy V3 and check if you're still facing the issue.

**Comment by siromega** [comment]
WindowsMachineFileCopyV2 works. However, as stated in the description above, we have 1300+ build pipelines and many (most?) of them use v1. It would be a lot of time spent for staff to change all their build pipelines. 

Beyond that, it seems we'd have to update our "PowerShell on Target Machines" tasks from v1 to v2 as well since on our new agents the v1 of that task doesn't seem to work either (the error was "The 'Get-ParsedSessionVariables' command was found in the module Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs', but the module could not be loaded. For more information, run 'Import-Module Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs'.").

**Comment by eaarora-ms** [comment]
@siromega  Actually the 'Get-LocalizedString' command is related to the agent and not to the task. You've mentioned using a new agent that does not support PowerShell on Target Machines V1. So to solve the issue you either need to switch to the latest version of the task or the previous version of the agent.

**Comment by siromega** [comment]
What previous version of the agent would support this task? 1.x? An early 2.x version?

**Comment by eaarora-ms** [comment]
@siromega  Can you share the logs of the previous successful pipeline? We can deduce the agent version from that.

**Comment by siromega** [comment]
I looked at the two releases, run on two different agents, and have the following: 

Old agent:  Current agent version: '2.140.2' (works)
New agent: Current agent version: '2.160.0' (task doesn't work)

HOWEVER, I installed the 2.140.2 version of the agent on the new server, using and still got the same errors I had with 2.160.0. So I have one computer with Agent 2.140.2 and it works, and one computer with the same version of the agent that doesn't work. I'm pretty sure its not Windows 2016 server vs Windows 10 Enterprise issue. The only thought I have is that, at one point, the old computer ran older versions of the agents, and whatever pre-reqs the v1 tasks require are installed, but the new agent installs don't have those pre-reqs and those tasks break.

**Comment by eaarora-ms** [comment]
@siromega  Hi just tried the task with Task Version - 1.0.46 and agent version - 2.161.0 and it is working successfully. I am assuming there is some issue with the agent configuration. Just to rule out this issue can you once try to configure a new agent and a fresh machine and try out the same scenario again?
Let us know the updates.

**Comment by siromega** [comment]
I installed it on another 2016 Server we have... and it seems to work. So I'm unsure as to why it is not working on this specific machine. Is there any help or advice you can provide on this? The two servers should be identically configured, have nearly identical software installed, etc.

**Comment by eaarora-ms** [comment]
@siromega  The error lies with the configuration of the agent. Deleting the agent folder and configuring it again should fix the problem (as we already tried on a new machine). Please let us know if any additional help is required from our side.

**Comment by eaarora-ms** [comment]
Closing this. Please comment to re-open if you're still facing the issue.
