### ISSUE TITLE
Docker V2 needs docker registry connection(Security issue)

### ISSUE THREAD

**Issue by Jyoti492** [microsoft/azure-pipelines-tasks#11741]
Hi Team,

There is a design on docker v2 task to push images to ACR you ll need to have the Docker Registry Service Connection but this Service Connection is not using an existing app registration rather it needs an access to create a new app registration which needs a global admin access. Can we please use the existing one because giving rights to the service principal to create an app registration on fly is not secure.

**Comment by Jyoti492** [comment]
Any update about this ?

**Comment by ds-ms** [comment]
@Jyoti492 Wouldn't this mitigate your problem right now? 

https://github.com/microsoft/azure-pipelines-tasks/issues/11084#issuecomment-553265363

**Comment by Jyoti492** [comment]
I am able to connect the ACR via Service Connection only on hosted agents and on our private agents it fails with the error as below although the ACR is open for all networks.
The push refers to repository [mcpsharedreg.azurecr.io/coesd/aab-base-deploy-helm]
Get ***v2/: read tcp 10.232.61.203:43262->52.236.186.80:443: read: connection reset by peer
##[debug]Exit code 1 received from tool '/bin/docker'
##[debug]STDIO streams have closed for tool '/bin/docker'
##[error]Get ***v2/: read tcp 10.232.61.203:43262->52.236.186.80:443: read: connection reset by peer

**Comment by ds-ms** [comment]
@Jyoti492 where are you seeing this error?

**Comment by vithati** [comment]
@Jyoti492 , closing the issue. please reopen issue if you are still facing the issue.
