### ISSUE TITLE
Cache task ignores the .artifactignore file

### ISSUE THREAD

**Issue by lukka** [microsoft/azure-pipelines-tasks#11759]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache

## Environment
Azure Pipelines
    
    

- Agent - Hosted or Private:  Hosted
    

## Issue Description

Cache task ignore the .artifactignore file when creating the cached set of files.

e.g.: 
this build did not exclude any file when creating the cache:

https://dev.azure.com/CppBuild/CppBuildTasks/_build/results?buildId=2881&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=e25532b4-f6bc-4056-8513-07e3e816ef7f

**Comment by johnterickson** [comment]
Hi @lukka - Thanks for reminding us of this.  For now, you can fall back to old behavior by setting the variable `AZP_CACHING_CONTENT_FORMAT` to `Files`.

**Comment by fadnavistanmay** [comment]
I think we should work on the glob pattern for input path - https://github.com/microsoft/azure-pipelines-tasks/issues/11219 , which will encompass the functionality that .artifactignore provides.

**Comment by fadnavistanmay** [comment]
Hi @lukka - We are going to track this here - https://github.com/microsoft/azure-pipelines-tasks/issues/11219 - support for globing for caching task.

Thanks.
