### ISSUE TITLE
Delete Files Task - Content-field does not support exlude pattern

### ISSUE THREAD

**Issue by tjarkschwartau** [microsoft/azure-pipelines-tasks#11767]
*Type*: Bug

**Enter Task Name**: Delete Files Task

## Environment
- Server - Azure Pipelines

## Issue Description

When using exclude pattern in 'contents' field of 'Delete files task' they do not work.
Files in folder:
web.dev.php
web.test.php
web.prod.php

Using pattern to delete all except 'web.dev.php':
web.*.php
!web.dev.php

Delete files task will delete all files.
Using this pattern in an online minimatch tester it works as expected.

**Comment by damccorm** [comment]
I think you want:
```
web.!(dev).php
!(web.dev.php)
```

These are just the filenames, but when we do the matching, they get appended as part of the whole path. So in the above case, what we are actually trying to match is:

```
path/to/your/repo/web.*.php
path/to/your/repo/!web.dev.php
```

and the match doesn't work in that context. The pattern I shared should do the job though.

**Comment by damccorm** [comment]
I'm going to close since I think this is working as expected, please feel free to comment if you disagree
