### ISSUE TITLE
dotnet restore fails with "GSSAPI operation failed with error" when running on Linux againts Azure DevOps Server

### ISSUE THREAD

**Issue by michaeljurek** [microsoft/azure-pipelines-tasks#11768]
When running .NET Core task in "dotnet restore" mode the task is not able to authenticate againts on-prem Azure DevOps Server for restoring artifacts. Server uses Windows Authentication and is not able to negotiate a protocol with client. See:
[https://stackoverflow.com/questions/58184148/docker-with-dotnet-restore-causes-error-gssapi-operation-failed-an-unsupporte](https://stackoverflow.com/questions/58184148/docker-with-dotnet-restore-causes-error-gssapi-operation-failed-an-unsupporte)

[https://github.com/dotnet/corefx/issues/34369](https://github.com/dotnet/corefx/issues/34369)

This has been fixed by Nuget.Client team, see [https://github.com/NuGet/NuGet.Client/pull/2297](https://github.com/NuGet/NuGet.Client/pull/2297)

However, dotnet restore task does not use this new capability and 100% fails on Linux machine (and sometimes it fails on non-domain joined Windows machines as well).

**Comment by jotaylo** [comment]
Our advice going forward is to use the [NuGetAuthenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#dotnet) task, followed by dotnet restore (or dotnet build directly). This task uses the new credential provider, which bypasses NuGet/dotnet's NTML behaviour.

**Comment by michaeljurek** [comment]
Will the NuGetAuthenticate task work for on-premises Azure Devops Server? Will it work on all suporteds OSes? With which Azure Devops Server will it be included?
Thanks,
Michael

**Comment by bishal-pdMSFT** [comment]
@jotaylo, as a workaround, would using "NuGet tool installer" task to installer required version of Nuget.exe work?

**Comment by michaeljurek** [comment]
@jotaylo It will not work. New version of NuGet comes with "ValidAuthenticationTypes feature" that can possibly solve my problem but the Pipeline task is not using it.

**Comment by jotaylo** [comment]
@bishal-pdMSFT Yes, because there are breaking changes between various versions of NuGet.exe, we don't update the version of NuGet.exe distributed with the NuGetCommand task. Using the NuGetToolInstaller task to select the version of nuget to use is the recommendation.

@michaeljurek NuGetAuthenticate will work for on-premises Azure Devops Server and on all supported OSes. I believe it will be available as part of the next release, however I have reports that some users have already installed the NuGetAuthenticate task via tfx into their existing Azure Devops Server instance.

**Comment by bishal-pdMSFT** [comment]
> @bishal-pdMSFT Yes, because there are breaking changes between various versions of NuGet.exe, we don't update the version of NuGet.exe distributed with the NuGetCommand task. Using the NuGetToolInstaller task to select the version of nuget to use is the recommendation.

@michaeljurek does this work around work for you?

**Comment by michaeljurek** [comment]
@bishal-pdMSFT It will not work. New version of NuGet comes with "ValidAuthenticationTypes feature" that can possibly solve my problem but the Pipeline task is not using it.

**Comment by edgarrs** [comment]
This will be fixed for Azure DevOps Server 2020
