### ISSUE TITLE
issue with donet publish task 

### ISSUE THREAD

**Issue by reshmaparate** [microsoft/azure-pipelines-tasks#11779]
Bug
dotnet publish task

We are using Azure Pipelines.

Error Logs:
********************************************************************
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node
  Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node": 
  
  HTTP error 404 Not Found
********************************************************************

Resolution:
The above mentioned URL https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node is returning 404 Not found error, when I am browsing it.
The correct URL to download the binary should be as follows according to my last successful build is:

 https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-64_binding.node

**Comment by anuj-shukla** [comment]
I'm also facing the same issue with VS 2017  hosted agent.

**Comment by damccorm** [comment]
Hi @reshmaparate  - could you be a little more specific with the task causing this? Is it the DotNetCoreCLI? Would also be helpful to have a repro if you're able to share one.

**Comment by anuj-shukla** [comment]
In my case it is related to version of  @angular/cdk which is internally using node-sass. Upgrading @angular/cdk helped in resolving the issue.

Also, It seems MS has upgraded the build agent VS 2017 for node which caused the earlier working builds to stop working.

**Comment by reshmaparate** [comment]
@damccorm 
Yes, it is DotNetCoreCLI. 

In Azure Devops build pipelines, I am facing this issue in dotnet publish task, which is based on DotnetCoreCLI , executing the publish command for dotnet builds.
While publishing, the task is trying to restore the node-saas version 4.9.3 from URL https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node , which is not available. If we browse the URL manually also, it is giving error 404(Page not found).
Last time when this task was succeeded, it was downloading the binaries from URL: https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-64_binding.node , which is available when we browse it.
My issue is I want to point that URL to the old URL only, which is available for downloading the binaries from. Can you please give me the suggestion on how to do this?

**Comment by damccorm** [comment]
@anuj-shukla that sounds like it might be a different issue - would you mind filing image specific issues in https://github.com/microsoft/azure-pipelines-image-generation?

Adding release tag so that they can take a look at the dotnetcorecli issue

**Comment by jalajmsft** [comment]
@reshmaparate can you please attach yaml file for your pipeline and build logs to understand the issue better.

**Comment by jalajmsft** [comment]
Hey @reshmaparate, Are you still blocked on this? If yes, can you please re-run the pipeline by setting the variable "System.debug" with value "true"  and share logs and YAML file for your pipeline.

**Comment by issacnitin** [comment]
@reshmaparate We're closing the issue, please feel free to reopen the issue with the logs if you're facing this again.
