### ISSUE TITLE
Azure DevOps Pipeline much slower than CircleCI and GitHub Actions

### ISSUE THREAD

**Issue by jperl** [microsoft/azure-pipelines-tasks#11775]
Getting a response from theinternet docker service is very slow in comparison to github actions and circleci.

https://dev.azure.com/perljonathan/qawolf/_build/results?buildId=54&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5

[Azure](https://dev.azure.com/perljonathan/qawolf/_build/results?buildId=54&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5) 4m 27s
```
PASS .qawolf/tests/login.test.js (101.24s)
PASS .qawolf/tests/select.test.js (70.939s)
PASS .qawolf/tests/scroll.test.js (58.037s)
```

![video](https://user-images.githubusercontent.com/1136652/68889160-9bd02200-06d9-11ea-8dbf-9045cfcb011f.gif)

[GitHub Actions](https://github.com/qawolf/examples/runs/303525454) 35s
```
PASS .qawolf/tests/login.test.js (13.99s)
PASS .qawolf/tests/select.test.js (5.421s)
PASS .qawolf/tests/scroll.test.js
```

![video](https://user-images.githubusercontent.com/1136652/68889233-c02bfe80-06d9-11ea-82c0-a0eec8d0b289.gif)

[CircleCI](https://circleci.com/gh/qawolf/examples/62?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 34s
```
 PASS  .qawolf/tests/login.test.js (13.385s)
 PASS  .qawolf/tests/select.test.js
 PASS  .qawolf/tests/scroll.test.js
```

![circle_video](https://user-images.githubusercontent.com/1136652/68889198-adb1c500-06d9-11ea-95d0-145fccae4ad4.gif)

All of them have video artifacts where you can watch the first request taking a very long time on Azure vs others.

**Comment by ds-ms** [comment]
I apologise for the delayed response. Do you still see this significant delay?
