### ISSUE TITLE
KubernetesManifestV0 support deployment to multiple namespaces

### ISSUE THREAD

**Issue by IvanovOleg** [microsoft/azure-pipelines-tasks#11785]
**Question, Bug, or Feature?**  
Feature

**Enter Task Name**: KubernetesManifest

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
It would be great to add a support of multiple namespaces in the yaml files. F.e if namespace is not set in the task configuration, it uses the one from yaml files and default as a default namespace if it is not set in task or yaml.

### Task logs
error: the namespace from the provided object "kube-system" does not match the namespace "default".

### Error logs
error: the namespace from the provided object "kube-system" does not match the namespace "default".

**Comment by shashankbarsin** [comment]
The Azure option of K8s service connection is designed in such a way that it'll create ServiceAccount and RoleBinding objects to only allow the service account to operate on a specific namespace. The task interface is designed accordingly to align with this mapping between namespace and service connections. Do not want to support multiple namespaces within the task as a result.

To deploy the same manifests to to multiple namespaces, the recommended approach is having multiple Kubernetes Manifest task based steps in the job - where each step deploys to one of the many namespaces

**Comment by mmisztal1980** [comment]
Consider a helm chart such as the jetstack's cert-manager, which creates k8s objects both in a target namespace, as well as kube-system when rbac/webhooks are enabled. This means that it's impossible to deploy that chart using a combination of `helm template` and `KubernetesManifest@0` - do you have a better solution for that case?

**Comment by chrisjaimon2012** [comment]
@shashankbarsin k8s deployments via a manifest are often quite elaborate, they involve namespaces for cert-manager like @mmisztal1980 mentioned, or API gateways or roles in the kube-system namespace
Splitting up the task and the yaml files wrt to namespace to support this use-case of azure devops task, doesn't make sense and renders the task quite unusable
You mentioned that the service connection the task uses is mapped only to a particular namespace, and that's the limitation faced here
- Can we not create Service accounts and role binding to multiple namespace (ClusterRole?)
- Will the cluster admin credentials not suffice for access into all namespaces?
