### ISSUE TITLE
"Download build artifacts" task "Matching pattern" is case-sensitive on Windows

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-tasks#11786]
**Type**: Bug

**Enter Task Name**: Download build artifacts 

## Environment
- Server - Azure Pipelines
- Agent - Private, Windows Server 2019, 2.160.0.
    
## Issue Description

The "Matching pattern" of "Download build artifacts" task is case-sensitive on Windows.

**Comment by gykuma** [comment]
@avivanoff This behavior is by design. We allow users to publish artifacts with same name but different casing. Since, users can select a particular artifact for download, we need to honor the pattern's casing regardless of agent OS.

**Comment by avivanoff** [comment]
@gykuma, how do you expect Windows users, who are used to decades of case-insensitive file system names, deal with this? Does it say anywhere in documentation that we now have to pay attention to file casing?

**Comment by gykuma** [comment]
@avivanoff, I understand this can be a problem. However, making the pattern match case-insensitive will cause compat issues. Also, this task is no more actively maintained.

Can you please give a try to the new [Publish Pipeline Artifacts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) for publishing the artifact and [Download Pipeline Artifacts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops) for downloading those artifacts.

**Comment by avivanoff** [comment]
@gykuma, if you are saying that artifact names are case-sensitive, you may want to look into [this](https://developercommunity.visualstudio.com/content/problem/830077/changing-pipeline-artifact-name-to-the-one-that-di.html) issue.

**Comment by avivanoff** [comment]
@gykuma, unfortunately, [Download Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops) task [does not work with UNC shares](https://github.com/microsoft/azure-pipelines-tasks/issues/11804).
