### ISSUE TITLE
Azure Devops - Add a kubernetes service connection Secret error message

### ISSUE THREAD

**Issue by mehmetaltuntas** [microsoft/azure-pipelines-tasks#11795]
Hi, 
I have added a secret which was taken out from GCP command shell and pasted into the textbox and here is the error.
3225 character.
Error: The string must have at least one character. Parameter name: endpoint.Authorization.Parameters[apitoken]
Screenshot attached. Cannot fix it. 
![Capture](https://user-images.githubusercontent.com/322457/69124826-a8e57a80-0af8-11ea-966a-3143e372ed18.PNG)

**Comment by mehmetaltuntas** [comment]
Apparently the MS website does not contain the same UI fields

https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-kuber

**Comment by shigupt202** [comment]
@mehmetaltuntas Can you share the secret yaml file that you are using here to ensure that the crt and token fields are not NULL?

**Comment by shigupt202** [comment]
You can mask out the crt and token fields.

**Comment by mehmetaltuntas** [comment]
Sorry I do not have it anymore. However, I can assure you that the crt and token fields were populated. 
Besides, the secret field only was longer than 300 characters.

**Comment by shigupt202** [comment]
@mehmetaltuntas I am able to create a service connection with a secret generated from the GCP shell. Please try it one more time and if you face the same problem again, reopen the issue.

**Comment by mehmetaltuntas** [comment]
> @mehmetaltuntas I am able to create a service connection with a secret generated from the GCP shell. Please try it one more time and if you face the same problem again, reopen the issue.

Can you copy a samlle secret over here pls?

**Comment by shigupt202** [comment]
Here's the secret that I got from the GCP shell. (I've stripped the crt and token fields)
apiVersion: v1
data:
  ca.crt: LS0tL...NBVEUtLS0tLQo=
  namespace: ZGVmYXVsdA==
  token: ZXlKaG...TBuUVRTekE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 72cedd29-1028-11ea-933e-42010a800097
  creationTimestamp: "2019-11-26T08:40:50Z"
  name: default-token-btm8l
  namespace: default
  resourceVersion: "277"
  selfLink: /api/v1/namespaces/default/secrets/default-token-btm8l
  uid: 72deb48d-1028-11ea-933e-42010a800097
type: kubernetes.io/service-account-token

**Comment by MOlechowski** [comment]
Had the same problem when generating secret from cloud shell on web I believe it must do something with text white spaces or something related to encoding. When you use secret generated from your local terminal everything works fine.

**Comment by martindr** [comment]
I had the same issue and resolved it by ensuring that the ca.crt and token values were in single lines. (Copying and pasting from the web shell breaks those values into separate lines)
