### ISSUE TITLE
Pipeline variable works in one stage but not the other

### ISSUE THREAD

**Issue by gneely-credera** [microsoft/azure-pipelines-tasks#11792]
## Required Information

**Type**: Bug

**Enter Task Name**: AzureResourceGroupDeployment@2 

## Environment
- Server - Azure Pipelines 
    
    - Acct: locumtenensdotcom1
    - Team Project Name: clinician portal
    - Build Def Name: Release Pipeline
    - Release-75

- Agent - Hosted
    
    - Agent Version: 2.160.1
    - Agent Machine Name: fv-az433

## Issue Description

We are using an ARM Template to deploy an Azure SQL Elastic Pool with a default admin password.  In the dev stage, the pool deploys without issue using a variable group to store the secured password and parameter overrides to insert it into the ARM Template.  In the UAT stage, if the same variable is supplied, or the correct variable (uat var instead of dev var), the deploy fails, stating that the password does not meet the complexity requirements.  If instead the password is overridden in plain text in the override params field, the template works without issue.

### Examples
These overrides fail:
<img width="326" alt="fail1" src="https://user-images.githubusercontent.com/55994115/69103148-d6abc000-0a21-11ea-9a48-8ee65e17f068.png">

<img width="494" alt="fail2" src="https://user-images.githubusercontent.com/55994115/69103153-df03fb00-0a21-11ea-96e5-fe316fb74c6a.png">

While this works:

<img width="504" alt="works" src="https://user-images.githubusercontent.com/55994115/69103171-e7f4cc80-0a21-11ea-8789-d4566b644902.png">

All variable values meet the complexity requirements, and the dev variable *works* in the dev stage.

### Task logs

Debug logging doesn't help, but is attached for completion.
[tasklog_15 (1).zip](https://github.com/microsoft/azure-pipelines-tasks/files/3861184/tasklog_15.1.zip)

## Troubleshooting
We have attempted to wrap the variable overrides in quotations, but that didn't help.  We have tried re-implementing the task from scratch, no joy.

**Comment by jalajmsft** [comment]
Hey @gneely-credera from the logs it seems like there is no variable defined by  **_uat-sql-server-admin-password_**. I am referring to this line in the attached logs 

> `2019-11-18T22:37:43.6323703Z ##[debug]overrideParameters=-administratorLoginPassword $(uat-sql-server-admin-password)`


Usually, the variables are substituted by their respective values in the logs, unless the variable is not defined in the pipeline. `**Note:** Please mark your passwords as 'secret variable' to avoid it getting logged as plain text.`

Let me know if you are still facing this.

**Comment by gneely-credera** [comment]
Howdy @jalajmsft !

Here's the variable in the Library:
![image](https://user-images.githubusercontent.com/55994115/69441330-c0468280-0d07-11ea-8cc7-f9e33814afd6.png)

Additionally, in my troubleshooting above, I get a similar issue running a dev version of that variable (dev-sql-server-admin-password), even though that dev variable works successfully in the development environment deployment tasks.

**Comment by jalajmsft** [comment]
Hey @gneely-credera did you link Library variable group to Release Pipeline variable group? If that is done can you please also check for stage wise linking to variable group? You can read more about variable group [here ](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=classic)

Let me know if you are still facing this.

**Comment by gneely-credera** [comment]
Howdy @jalajmsft, thanks for pointing out the stagewise linking!  We had only given the values scope for our dev and QA stages, not UAT.  Thanks so much for your help!
