### ISSUE TITLE
Npm Task fail to install packages

### ISSUE THREAD

**Issue by gpad** [microsoft/azure-pipelines-tasks#11811]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: Npm@1  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

MAHOUT manpremo manpremo.manpremo-web  #20191120.5

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

Pool: Azure Pipelines
Image: Ubuntu16
Queued: Today at 12:32 PM [manage parallel jobs]
Agent: Hosted Agent
Started: Today at 12:33 PM
Duration: 40s

## Issue Description

[Include task name(s), screenshots and any other relevant details]

Executing npm install fails using the committed package.json

### Task logs
```
12953 verbose stack Error: spawn EPERM
12953 verbose stack     at ChildProcess.spawn (internal/child_process.js:366:11)
12953 verbose stack     at Object.spawn (child_process.js:551:9)
12953 verbose stack     at promiseRetry (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24)
12953 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
12954 verbose cwd /__w/1/s
12955 verbose Linux 4.15.0-1061-azure
12956 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
12957 verbose node v10.17.0
12958 verbose npm  v6.11.3
12959 error code EPERM
12960 error syscall spawn
12961 error errno EPERM
12962 error Error: spawn EPERM
12962 error     at ChildProcess.spawn (internal/child_process.js:366:11)
12962 error     at Object.spawn (child_process.js:551:9)
12962 error     at promiseRetry (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24)
12962 error     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
12962 error  { Error: spawn EPERM
12962 error     at ChildProcess.spawn (internal/child_process.js:366:11)
12962 error     at Object.spawn (child_process.js:551:9)
12962 error     at promiseRetry (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24)
12962 error     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
12962 error   cause:
12962 error    { Error: spawn EPERM
12962 error        at ChildProcess.spawn (internal/child_process.js:366:11)
12962 error        at Object.spawn (child_process.js:551:9)
12962 error        at promiseRetry (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24)
12962 error        at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 errno: 'EPERM', code: 'EPERM', syscall: 'spawn' },
12962 error   stack:
12962 error    'Error: spawn EPERM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at Object.spawn (child_process.js:551:9)\n    at promiseRetry (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:216:24)\n    at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24',
12962 error   errno: 'EPERM',
12962 error   code: 'EPERM',
12962 error   syscall: 'spawn',
12962 error   parent: 's' }
12963 error The operation was rejected by your operating system.
12963 error It is likely you do not have the permissions to access this file as the current user
12963 error
12963 error If you believe this might be a permissions issue, please double-check the
12963 error permissions of the file and its containing directories, or try running
12963 error the command again as root/Administrator.
12964 verbose exit [ 1, true ]

```
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
[package.json.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3868983/package.json.zip)

[Insert error from the logs here for a quick overview]

**Comment by gpad** [comment]
Just to give you some information I have discovered that the issue is caused by the presence in the `pacakage.json` of a package defined in git `"react-edit-inline": "bynhanpham/ReactInlineEdit"` this is legal entry and should be managed by this task ...

**Comment by johnterickson** [comment]
@gpad Did you see this when running `npm install` directly?

**Comment by gpad** [comment]
Yes

**Comment by jmyersmsft** [comment]
Looks like npm/cli#476
