### ISSUE TITLE
Node exited with code 130 from cmdline task

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-tasks#11836]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CmdLine (2.151.2)

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Azure Pipelines
Account name : dnceng
Project : public
build def name: ".NET Core Toolset CI"
Link to build : https://dev.azure.com/dnceng/public/_build/results?buildId=413027&view=results

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Ubuntu16

## Issue Description

Crashed mid run with uncommon exit code 130: build is linked above.
`##[error]Exit code 130 returned from process: file name '/home/vsts/agents/2.159.2/externals/node/bin/node', arguments '"/home/vsts/work/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/2.151.2/cmdline.js"'.
`

### Task logs

Not available ; issue does not readily reproduce and this was a hosted agent.

### Error logs

Not available ; issue does not readily reproduce and this was a hosted agent.

**Comment by damccorm** [comment]
Exit code 130 means SIGINT. That's also consistent with the other error we see here:

![image](https://user-images.githubusercontent.com/42773683/69460040-1e438c00-0d41-11ea-9ac9-68c6ee560002.png)

It looks like for some reason the agent was killed mid-run. @stbeam it looks like this was a hosted agent - any reason it would've sent a cancellation to the agent?

**Comment by damccorm** [comment]
Closing since I believe we've addressed this with your account and its not really a tasks issue.
