### ISSUE TITLE
msBuild version 16 required for xamarin.iOS build

### ISSUE THREAD

**Issue by CasperNaudts** [microsoft/azure-pipelines-tasks#11837]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Feature

**Enter Task Name**: XamariniOSV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Azure Pipelines
    account: **project-pvl**
    team project: **Backend**
    build defenition: **Backend-Xamarin.iOS-CI/#20191123.5**

- Agent - Hosted: 
    macOS-10.14

## Issue Description

When trying to build our xamarin app I run into the isue that our nuget dependancy Fody requires msBuild 16 but the default is 15. For our android version I was able to solve this issue by specifying the msBuild versioin. Unfortionatly I was not able to find this option in the iOS build task.

The code of the iOS project builds perfectly on our macOS mashine with visualstudio and msBuild 16.

When I tried building with the msBuild task with version 16 I got the error that the iOS SDK was not installed. 

Did I miss the option for msBuild version 16 or is there an other work arround?

### Task logs

[Backend-Xamarin.iOS-CI.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3882354/Backend-Xamarin.iOS-CI.zip)
[logs_286.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3882344/logs_286.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

/Users/runner/.nuget/packages/fody/6.0.0/build/Fody.targets(38,5): error : Fody is only supported on MSBuild 16 and above. Current version: 15. [/Users/runner/runners/2.160.1/work/1/s/Signawel.Mobile/Signawel.Mobile/Signawel.Mobile.csproj]

**Comment by CasperNaudts** [comment]
@leantk any updates on this?

**Comment by Ryan-Palmer** [comment]
+1, I have hit this too.

**Comment by Ryan-Palmer** [comment]
I'm facing similar issues, just playing with Boots to try to install the required bits https://devblogs.microsoft.com/xamarin/boots-xamarin-ci/

**Comment by Ryan-Palmer** [comment]
I was able to get around this.
1.) Install the Boots extension https://devblogs.microsoft.com/xamarin/boots-xamarin-ci/

2.) Add the step to your build before the nuget restore with this InstallerURI:
https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.156.macos10.xamarin.universal.pkg

3.) Set the new Mono path using a Bash script with the following:
```
SYMLINK=6_6_0_156
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
```

**Comment by CasperNaudts** [comment]
@Ryan-Palmer This solved the issue thanks.

**Comment by Ryan-Palmer** [comment]
It turns out you don't need the bash script btw, Boots sets the new Mono path for you.

If you want to see how to update Xamarin.iOS and point at a newer XCode, see my issue here (turned out I had a rogue space char...) 
https://github.com/microsoft/azure-pipelines-image-generation/issues/1441
