### ISSUE TITLE
ERROR: When trying to pull from docker hub. Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by mousiefasil** [microsoft/azure-pipelines-tasks#11830]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines
Agent-Hosted ubuntu-latest

## Issue Description

During docker build and push, when an image needs to be pulled from docker hub, e.g. nginx:latest, the following error is thrown.
![image](https://user-images.githubusercontent.com/36261187/69419474-ceeb6480-0d1c-11ea-823b-2aebd2c8f75c.png)

I was able to mitigate this by adding an additional bash task, where I pull the the required image beforehand. But this more or less a manual fix and cannot be used as a general solution in my opinion. 

If requested, I could provide a minimal example azure-pipeline.yaml.

Thanks in advance.

**Comment by vithati** [comment]
@mousiefasil, Which task are you using to pull the images? Can you provide azure-pipeline.yml file if possible?

**Comment by mousiefasil** [comment]
Hi,
i attached two azure-pipeline.yml files, the first one will result in the above error, while second will succeed due to the workaround. 

[azure-pipeline.error.yml.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4015431/azure-pipeline.error.yml.txt)

[azure-pipeline.success.yml.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4015430/azure-pipeline.success.yml.txt)

[Dockerfile.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4015432/Dockerfile.txt)

**Comment by shigupt202** [comment]
@mousiefasil Are you using Microsoft-hosted agent or self-hosted agent?

**Comment by mousiefasil** [comment]
@shigupt202 i am using a Microsoft-hosted agent.

**Comment by shigupt202** [comment]
@mousiefasil Is the issue intermittent, or does it happen every time you run the pipeline? Also, can you enable system.debug in your pipeline and share the logs to RM_Customer_Queries@microsoft.com?

**Comment by mousiefasil** [comment]
@shigupt202 
I performed the pipeline only with the docker buildandpush task and it is working now and the build is successful. I think the issue can be closed :+1:
