### ISSUE TITLE
[DownloadPipelineArtifact@2] Unclear error `Input string was not in a correct format`

### ISSUE THREAD

**Issue by sharno** [microsoft/azure-pipelines-tasks#11835]
## Required Information

*Type*: Bug/Feature

**Enter Task Name**: DownloadPipelineArtifact

## Issue Description

Using this task, I get an error `Input string was not in a correct format` which doesn't indicate which field exactly is wrong, I tried changing the pipelineId to be with quotes (not sure where should I get the pipelineId from too) but it doesn't solve it.

I would prefer if there was a clearer error message about what's wrong in my configuration. To be able to solve this error.

```yaml
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '284k8d13-4263-4e3e-bca1-bf4744fb3dc6'
    pipelineId: 1819
    artifactName: 'bin_Linux'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'master'
    targetPath: '$(Pipeline.Workspace)'
```
(I changed the IDs in this snippet to not expose certain data)

### Task logs

```
##[debug]Evaluating condition for step: 'DownloadPipelineArtifact'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: DownloadPipelineArtifact
==============================================================================
Task         : Download Pipeline Artifacts
Description  : Download build and pipeline artifacts
Version      : 2.1.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
==============================================================================
##[error]Input string was not in a correct format.
##[debug]Processed: ##vso[task.logissue type=error;]Input string was not in a correct format.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.GetPipelineIdAsync(AgentTaskPluginExecutionContext context, String pipelineDefinition, String pipelineVersionToDownload, String project, String[] tagFilters, String branchName)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: DownloadPipelineArtifact

```

**Comment by fadnavistanmay** [comment]
@jahsu-MSFT

**Comment by jahsu-MSFT** [comment]
@sharno Thanks for the feedback. From looking at your yaml schema, I think the pipelineId there is redundant since you already selected to use the "latest from branch". 
The pipeline should work by using the below schema - 

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '284k8d13-4263-4e3e-bca1-bf4744fb3dc6'
    artifactName: 'bin_Linux'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'master'
    targetPath: '$(Pipeline.Workspace)'

**Comment by sharno** [comment]
@jahsu-MSFT 
Thanks for your reply
I found out that `pipelineId` should actually be just `pipeline` and this worked correctly

seems like the documentation is contradicting between the examples and the YAML snippet:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops

**Comment by jahsu-MSFT** [comment]
Thanks for the update. @sharno  and sorry I deleted the previous reply since it's not exactly correct.
 There are actually pipeline input field and pipelineId input field. The old name for the "pipeline" input field was "definition". We are going to update the documentation to avoid confusion. And we'll also be improving our error messages. 
Thanks,

**Comment by sharno** [comment]
@jahsu-MSFT No worries, thanks for taking care of the issue
