### ISSUE TITLE
[DownloadPackage] Support variant of tar gz compressed files

### ISSUE THREAD

**Issue by brunoborges** [microsoft/azure-pipelines-tasks#11843]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPackage

## Issue Description

The function `extract()` checks the file extension for `tgz`, but often files are named `tar.gz`.

https://github.com/microsoft/azure-pipelines-tasks/blob/a8fd5bc0e8aefec098d20ad37f264a64bc9ed21a/Tasks/DownloadPackageV1/packagefile.ts#L39-L50

Related issue: #11842

**Comment by edgarrs** [comment]
This is low priority
