### ISSUE TITLE
[DownloadPackage] Won't Extract Unless Nuget/NPM package type

### ISSUE THREAD

**Issue by brunoborges** [microsoft/azure-pipelines-tasks#11842]
## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPackage

## Issue Description

This task supports extracting `zip`, `nupkg` and `tgz` files as per the `extract()` function:

https://github.com/microsoft/azure-pipelines-tasks/blob/a8fd5bc0e8aefec098d20ad37f264a64bc9ed21a/Tasks/DownloadPackageV1/packagefile.ts#L39-L50

But the property `extract` will be flipped back to false if the `packageType` is different than `npm` or `nuget` as per this code:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadPackageV1/main.ts#L25

Meaning that while the task supports extracting zip/tgz files, it won't support doing that for universal packages.

**Comment by aasim** [comment]
Hi @brunoborges - This code is only used for extracting NuGet and Npm packages, so its by design that it doesn't support Universal packages. The download and extraction for universal packages is handled by a separate library as seen [here](https://github.com/microsoft/azure-pipelines-tasks/blob/a8fd5bc0e8aefec098d20ad37f264a64bc9ed21a/Tasks/DownloadPackageV1/main.ts#L42).

What is the exact problem you are facing?

**Comment by brunoborges** [comment]
It is not extracting, or if it is then I can't seem to find where it is being put. Is there a way to expand the log/verbosity of this task?

**Comment by aasim** [comment]
Yes, can you run the task with the pipeline variable System.debug set to true. That will show you verbose logging.

**Comment by aasim** [comment]
If you need your files to go to a specific directory you can specify the directory name using the downloadPath parameter as shown [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops#download-a-nuget-package-from-an-organization-scoped-feed-and-extract-to-destination-directory)

**Comment by herenhuang** [comment]
@brunoborges - are you still having this issue? Let us know so we can reopen the issue if it still exists.
