### ISSUE TITLE
Only up to 10 warnings logged from a ShellScript task are displayed in the build summary

### ISSUE THREAD

**Issue by samkearney** [microsoft/azure-pipelines-tasks#11841]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: ShellScript

## Environment
- Server - Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - Org: ETCLabs
        - Project: RDMnet
        - Build number: 20191125.7

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

In this build: https://dev.azure.com/ETCLabs/RDMnet/_build/results?buildId=572&view=results
Stage "Build and Test RDMnet"
Job "Documentation Deploy"
Step "Generate and Push Documentation"

This ShellScript task uses the command line logging syntax to log 365 warnings. Only 10 of the warnings from this step are displayed in the summary view. I see no indication anywhere in the UI that this step produced more than 10 warnings, unless I look at the raw log. Is this expected?

### Task logs

Attached.
[logs_572.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3888217/logs_572.zip)

**Comment by damccorm** [comment]
Yeah, that's expected. We only render the first 10 in the UI and flag the total number as well (373 in this case)

**Comment by samkearney** [comment]
Thanks @damccorm. I've played around with this a little more and gathered some more info.

When I have the "multi-stage pipelines" view (ostensibly the "new" UI) turned on, there is no indication anywhere in the UI of the total number of warnings. I have to manually inspect the build logs to find out.

![image](https://user-images.githubusercontent.com/5142299/69762718-1a48ad00-1139-11ea-8117-4fd4807550c1.png)

![image](https://user-images.githubusercontent.com/5142299/69762839-6f84be80-1139-11ea-9005-58c715545de2.png)

![image](https://user-images.githubusercontent.com/5142299/69762922-a9ee5b80-1139-11ea-9153-44c45f96912d.png)

**When I turn multi-stage pipelines view off**, I do get the total warnings number correctly in the overall build summary, but not in the individual step descriptions:

![image](https://user-images.githubusercontent.com/5142299/69763073-06517b00-113a-11ea-8bdc-869f8a337557.png)

![image](https://user-images.githubusercontent.com/5142299/69763132-33059280-113a-11ea-9c62-28924d6b89e1.png)

So if the expected behavior is to accurately display the total number of warnings, but only show up to 10 in detail, it looks like things might not entirely be behaving as expected. **Multi-stage view is supposed to be the "new" UI but appears to be worse in this regard** - I can find no indication anywhere in that view of the correct total number of warnings.

**Comment by damccorm** [comment]
Repathing to build to take a look at the UI - it seems like we're correctly reporting the warnings, but maxing them out at 10 in some spots.

**Comment by samkearney** [comment]
Just wanted to chime back in to say that the warnings display on the multi-stage pipelines UI is much nicer now! Thank you for the work! 😄

**Comment by damccorm** [comment]
Thanks for the positive feedback, happy to help!
