### ISSUE TITLE
workingDirectory not respected for Azure PowerShell task

### ISSUE THREAD

**Issue by stilren** [microsoft/azure-pipelines-tasks#11859]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShellV4

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

## Issue Description

Setting the WorkingDirectory in the UI will not cause the script to be executed from that directory

Create the following task
steps:
- task: AzurePowerShell@4
  displayName: Dir
  inputs:
    azureSubscription: 'My subscription'
    ScriptType: InlineScript
    Inline: dir
    azurePowerShellVersion: LatestVersion
    workingDirectory: '$(System.DefaultWorkingDirectory)/mydirectory

The concents of mydirectory will not be listed

**Comment by eaarora-ms** [comment]
@stilren  I am not sure if I understand your question perfectly. However, from what I could understand running dir from your 'mydirectory' should list the contents of that directory and not the directory itself. If this did not solve it can you share the exact expected v/s real output logs here? Thanks!

**Comment by stilren** [comment]
Yeah sorry if that was unclear - I am expecting the contents of the directory to be displayed but its not

**Comment by eaarora-ms** [comment]
@stilren  I am sorry but I am not able to repro the issue. The contents of the directory are getting listed. Can you please share the directory structure and pipeline logs with system.debug set as true.

**Comment by eaarora-ms** [comment]
@stilren  Can you please confirm if you're still facing the issue?

**Comment by eaarora-ms** [comment]
Please comment to re-open if you're still facing the issue.

**Comment by kristianpinke** [comment]
Hello,

I am experiencing the same behavior with the PowerShell task. Setting "Working Directory" under Advanced is not applied.
Maybe worth to note, that my path contains '[' and ']', e.g. '$(System.DefaultWorkingDirectory)\_CompanyApp-UWP [Release-Experimental-E2E]\drop\CompanyApp_$(Build.BuildNumber)'_Test\'.
There is no error in the console output, only that directory is set to 'C:\' and not to the specified under Working Directory.

**Comment by 20shivangi** [comment]
@stilren Please use the latest version of AzurePowerShell task i.e. V5, and check if the working directory works for you there

**Comment by 20shivangi** [comment]
@kristianpinke @stilren Let me know if you got unblocked using latest version of AzurePowerShell

**Comment by 20shivangi** [comment]
@kristianpinke @stilren Can anyone of you please let me know, if you got unblocked or not ?

**Comment by kristianpinke** [comment]
@20shivangi Hello, I am sorry but I cannot try it out. I realized that this thread is about the "Azure PowerShell" task. In my case, the problem occurs with the "PowerShell" task. In that task, the newest version is 2.*
I am not able to use "Azure PowerShell" tasks as I do not have a proper Azure subscription and I am only part of the DevOps team in my organization.
Would it be possible to fix the same for the "PowerShell" task?

**Comment by 20shivangi** [comment]
@kristianpinke Our team does not own PowerShell task, you can raise it as a separate github issue.

**Comment by 20shivangi** [comment]
Closing this issue. Feel free to reopen if you are facing the issue. We will be happy to help you

**Comment by jvilalta** [comment]
For those reading this thread as I did. WorkingDirectory did NOT work in V4, but it DOES work on V5.
