### ISSUE TITLE
The Kubernetes task should support all the kubectl commands 

### ISSUE THREAD

**Issue by adrianbumbas** [microsoft/azure-pipelines-tasks#11867]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Kubernetes@1  

## Environment
- Server - Azure Pipelines
 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted or Private: N/A
   

## Issue Description

The `Kubernetes@1` task should allow any command, one use cases that is missing is support for `kubectl rollout undo deployment`. 

Also forcing it at the YAML level doesn't work.

**Comment by ds-ms** [comment]
Did you try adding `rollout` to the command and `undo deployment` to the args and try?

**Comment by adrianbumbas** [comment]
I tried this

```
command: rollout
arguments: 'undo deployment XXX'
```

which produces the following output:

```
/usr/bin/kubectl rollout -n default undo deployment 'XXX'
Error from server (NotFound): deployments.extensions "'XXX'" not found
```

But if I run the same command on the cloud shell it works.

**Comment by ds-ms** [comment]
Could you try this `deployment/XXX` instead. 
The task doesn't add quotes to `XXX` explicitly though, it would have if you args had them. 

And also remove the `'` from the args
```yaml
command: rollout
arguments: undo deployment XXX
```

**Comment by adrianbumbas** [comment]
This works:

```
command: rollout
arguments: undo deployment/XXX
```

Removing the quotes from around deployment also helped.
