### ISSUE TITLE
 pipeline is failing with error 403 No valid crumb was included in the request.

### ISSUE THREAD

**Issue by Lijo2019** [microsoft/azure-pipelines-tasks#11876]
Hi,
When I integrated Jenkins through azure devops, and executed the pipeline, the pipeline is failing with below error
Job creation failed.
HttpResponse.statusCode=403
HttpResponse.statusMessage=No valid crumb was included in the request

Jenkins Version  used is 2.190.3

Here i tried below options
1. disabling CSFR Protection.
2. Enable  proxy compatibility, but same error i got while building pipeline.

YAML snippet  which we used for Jenkins queue job

task: JenkinsQueueJob@2
    displayName: 'Queue Jenkins job: Project_test'
    inputs:
       serverEndpoint: 'abc_cd_ef'
       jobName: 'Project_test'
       isParameterizedJob: true
       jobParameters: 
                       foldername=$(Agent.Name)
                       filename=${{ parameters.filename }}

Please let me know how to resolve this issue as we are stuck with this error for the last couple of days.

**Comment by dansemedo** [comment]
+1

**Comment by srikcgaa2** [comment]
One observation made when comparing another instance that is still working with different version of Jenkins is that the crumb value length seems to have doubled.  Could that be causing an incompatibility with Azure task?

**Comment by Lijo2019** [comment]
One update on above issue, after downgraded  to Jenkins version 2.164.3 and TFS plugin 5.142.0 , i was able to build my pipeline successfully. Even though it is  a bug in Jenkins, later point of time it will come as an issue. So this issue needs to be fixed.Please let me know if any thoughts.

**Comment by tareks** [comment]
+1 

Can confirm that I ran into 403s queuing a Jenkins job on a server running 2.190.1. Running against Jenkins 2.164.3 instead seems to work fine. Error message (without system.debug) is:
```
Job creation failed.
HttpResponse.statusCode=403
HttpResponse.statusMessage=Forbidden
```

Any ETA on when this is expected to be fixed or what the release/fix schedule is like for these ADO tasks?

**Comment by itlpdgmatt** [comment]
+1

**Comment by tareks** [comment]
This appears to be a result of security changes in Jenkins and how the same sessionid associated with the crumb request must be carried on with any following requests using that crumb. 

Details: https://jenkins.io/doc/upgrade-guide/2.176/#upgrading-to-jenkins-lts-2-176-3

I'm looking at what changes can be made to get this working again with minor changes and will report back if I can find anything useful.

Alternatively, perhaps V3 of the task can allow the option to use API tokens instead?

**Comment by tareks** [comment]
Update: Note if you're still struggling with this, it appears that you can just replace the password in the service connection with a generate token associated with that account. 

Ref: https://wiki.jenkins.io/display/JENKINS/Remote+access+API

Tested to work against jenkins v2.204.5.

**Comment by Lijo2019** [comment]
Update:Using Jenkins version 2.230 and TFS plugin 5.157 i was able to build pipeline in azure devops. During this process got an error 

Job creation failed.
HttpResponse.statusCode=403
HttpResponse.statusMessage=Forbidden 

To solve above issue tried solution suggested by "tareks commented on 18 Mar". It worked and i was able to build my pipeline successfully.

**Comment by babukotha** [comment]
In the Azure DevOps - project settings - Jenkins service connection. Please use the Jenkins API token which is generated under -your user, configure section - API token. 

After that Azure Devops pipeline was success without this error.

**Comment by minj1992** [comment]
> In the Azure DevOps - project settings - Jenkins service connection. Please use the Jenkins API token which is generated under -your user, configure section - API token.
> 
> After that Azure Devops pipeline was success without this error.

OMG  after spending  lots of time i did it and found your solution very lately in this forum . anyway nice work :)
