### ISSUE TITLE
Windows Machine File Copy - why are admin credentials required for this task?

### ISSUE THREAD

**Issue by ccerghed** [microsoft/azure-pipelines-tasks#11877]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Windows Machine File Copy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Our admin accounts are locked down, making it a bit difficult to find the proper AD account that has the necessary login permissions.  Why can this task not use the same ID that the agent is running under, which in our environment is already part of the Administrators group on every Windows machine that we deploy to?

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Deploy web application (SCIIQD11) - Failed
Copy files to \\SCIIQD11\D$\APPS\Tomcat\webapps\identityiq failed
2 errors
Failed to Create PSDrive with Destination: '\\SCIIQD11\D$\APPS\Tomcat\webapps\identityiq', ErrorMessage: 'An extended error has occurred'
An extended error has occurred
Deploy web application (SCIIQD12) - Failed
Copy files to \\SCIIQD12\D$\APPS\Tomcat\webapps\identityiq failed
2 errors
Failed to Create PSDrive with Destination: '\\SCIIQD12\D$\APPS\Tomcat\webapps\identityiq', ErrorMessage: 'An extended error has occurred'
An extended error has occurred

**Comment by arjgupta** [comment]
Marking this as an enhancement. "use the same set of credentials with which the agent is running"

**Comment by ccerghed** [comment]
@arjgupta Are there any plans to release the new enhancement?
