### ISSUE TITLE
[Publish Test Results] JUnit <testcase> with multiple <errors> only displays the first one

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/azure-pipelines-tasks#11888]
This is a **Bug report**  (similar to #7659 but not the same)

Task Name: **PublishTestResults@2**

## Issue Description
In the Docs [Publish Test Results task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml) a link to [junit (xsd)](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) is added as a supported result format.
![image](https://user-images.githubusercontent.com/6558089/70131921-6d63b800-1683-11ea-8a70-d6737a8fb107.png)

Given this xml file:
<details>
<summary>junit-errors-minimal-example.xml</summary>
<pre style="display:block; font-family:monospace; margin: 1em 0; white-space: pre;">

```xml
<?xml version='1.0' encoding='utf-8'?>
<testsuite errors="3" failures="0" hostname="host" name="errors" tests="3" time="1" timestamp="2019-12-03T12:42:31.883752">
	<testcase classname="Cppcheck error" name="myfolder\myfile.cpp" time="1">
		<error file="myfolder\myfile.cpp" line="0" message="message one" type=""/>
		<error file="myfolder\myfile.cpp" line="816" message="message two" type=""/>
	</testcase>
	<testcase classname="Cppcheck error" name="myfolder\myfile.h" time="1">
		<error file="myfolder\myfile.h" line="158" message="message three" type=""/>
	</testcase>
	<testcase classname="Cppcheck error" name="Cppcheck error" time="1">
		<error file="" line="0" message="message four" type=""/>
	</testcase>
</testsuite>
```

</pre>
</details>

It seems to have no validation errors, checked with the following tool.
```
xmllint.exe junit.xsd junit-errors-minimal-example.xml --noout
```

</pre>
</details>

**The problem is**: In the [tests tab](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops)  `message two` does not appear, only the first error for a given test case is shown.

**Comment by sahitiyerramilli** [comment]
Hey,

Multiple errors for the same test case is not supported according to the supported result format. Please let us know in case any further clarification is needed.

**Comment by FrancescElies** [comment]
In the Docs a link to [junit (xsd)](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) mentioned and `xlint` does not find validation errors.

Could this be mentioned in the docs?

**Comment by sahitiyerramilli** [comment]
Hey,

We'll contact and the repo owners and see if that can be changed. We'll keep you updated.

**Comment by suyash691** [comment]
It is updated in the xsd repository to reflect appropriately. I am closing the thread here
