### ISSUE TITLE
Invalid global.json is definitely valid

### ISSUE THREAD

**Issue by bmarder** [microsoft/azure-pipelines-tasks#11898]
## Issue Description

Azure devops throws an error about failing to parse global.json . By simply moving the location of the file to a parent folder, it then works.

### Error logs

> The global.json at path: 'C:\VSTSWorkRoot\11\s\src\Path\global.json' has the wrong format. For information about global.json, visit here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json. Error while trying to read: SyntaxError: Unexpected token ﻿ in JSON at position 0

**Comment by damccorm** [comment]
Could you share a yaml snippet? And maybe a repro if you're able to? Is this in one of our tasks?

**Comment by damccorm** [comment]
Closing due to lack of info. Please comment if you'd like this issue to be reopened.

**Comment by smichtch** [comment]
Also ran into this (and #13881 seems to be same), re-saving the file with UTF8 or ASCII encoding gets rid of the error.
Seems like UseDotNet task doesn't like the BOM character at the beginning of the file.
