### ISSUE TITLE
Connect-AzureRmAccount must be run in Azure CLI task

### ISSUE THREAD

**Issue by kyleherzog** [microsoft/azure-pipelines-tasks#11899]
**Question, Bug, or Feature?**  
*Type*: Question/Feature

**Enter Task Name**: AzureCLIV2

## Environment
- Server - Azure Pipelines 
- Agent - Private: Windows Server 2019, Current agent version: '2.154.3'
    
## Issue Description

I am trying to run a powershell script using the Azure CLI task v2.0(preview). In my script, I call Get-AzureRmAppServicePlan.  This gives me an error "Get-AzureRmAppServicePlan : No account found in the context. Please login using Connect-AzureRmAccount."

This is my first attempt at running this script using the Azure CLI.  I can run the powershell script using the Azure Powershell task but I don't have to call Connect-AzureRmAccount in that task.  

1. To get things going for now, is there an example of how to call Connect-AzureRmAccount in this task?
2. Longer term, it feels like the task should automatically login and make the connection.

**Comment by jalajmsft** [comment]
Hey @kyleherzog 

Azure PowerShell is a set of cmdlets installed on the PowerShell command line. Azure PowerShell tasks do the required setup before executing the script.

Azure CLI task provides just the shells to execute the az scripts. To use additional functionality(cmdlets/libraries) depending on the shell should be taken care of explicitly.

To use Azure PowerShell cmdlets, it is recommended to use the Azure PowerShell task to avoid the hassle of set up.

**Comment by jalajmsft** [comment]
Thanks for raising this issue @kyleherzog. We haven't heard much from the community on this. We would like to collect more information to proceed with this.

Closing this, feel free to re-open for further queries.
