### ISSUE TITLE
VS Test parallel execution - Anticipated execution time is always unknown.

### ISSUE THREAD

**Issue by ioananicu** [microsoft/azure-pipelines-tasks#11905]
[ReleaseLogs_10867.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3955808/ReleaseLogs_10867.zip)
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug /Question

**Enter Task Name**: Visual Studio Test

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted 

## Issue Description

We have about 500 coded UI tests running on 6 agents in parallel. The batch size is configured to take into account the running time, but it does not work. The batches always contain the same number of tests and there is usually one agent that takes considerably longer to execute.

### Task logs
```
2019-12-05T00:56:07.3046041Z [RunStatistics]This execution slice with id '5402', received '88' testcases to execute out of which '87' is discovered.
2019-12-05T00:56:07.3046407Z [RunStatistics] Could not find a base definition run to get a history of execution times.
2019-12-05T00:56:07.3046733Z [RunStatistics] Anticipated execution time of current slice is unknown. This might be because the test cases are either new or failed in the previous run.
```

Note: There are maybe 1 or 2 new tests, all the rest are executed and have execution times when we check the test results.

```
2019-12-05T03:22:07.7815695Z Publishing test results to test run '1080116'.
2019-12-05T03:22:07.7869054Z TestResults To Publish 87, Test run id:1080116
2019-12-05T03:22:07.7972811Z Test results publishing 87, remaining: 0. Test run id: 1080116
2019-12-05T03:22:09.9091011Z Published test case results: 87
2019-12-05T03:22:10.3513479Z [RunStatistics] Total anticipated execution time: unknown Total actual execution time: 8731300.7922
```

I was unable to find relevant information online about how that _base definition run_ is done. or why the _Anticipated execution time_ is always unknown.

**Comment by vagisha-nidhi** [comment]
@ioananicu Can you please set variable `system.debug = true` and share with us the full zip logs?

**Comment by ioananicu** [comment]
@vagisha-nidhi Hi. I have updated the original post with the log info for that task, I have set the variable but it will take another day to get the debuglogs. I will attach those when I get them. Do you need the logs for the whole stage or is that task enough?

**Comment by ShreyasRmsft** [comment]
We'd need it for the entire build. Please upload the full zip that you obtain by clicking on download all logs. There are additional platform logs that can only be obtained this way and we need those.

**Comment by ioananicu** [comment]
@ShreyasRmsft Hi, I have attached the build logs from which i removed other non relevant stages. Please let me know if you require anything else. Thank you

**Comment by vagisha-nidhi** [comment]
We are still unable to repro your scenario. Can you please provide a sample repro? You can remove most of the tests and even production code if needed. 
The base definition run is picked from a previous release/build which contained tests. The running time of passed tests of that build is taken as the anticipated running time of a test. From the logs it seems like it is unable to fetch a previous successful release which contains tests run in it. Can you verify that there exists an already successful release as well? Please provide a scaled down repro if possible.

**Comment by li-dawei** [comment]
Hi. We have the same problem too - a bunch of UI tests running across 3 self-hosted agents that isn't getting time sliced properly. Same error message across each run '[RunStatistics] Anticipated execution time of current slice is unknown. This might be because the test cases are either new or failed in the previous run.' The same tests have been running repeatedly for months. Happy to provide logs too if needed.

**Comment by vagisha-nidhi** [comment]
Hi @li-dawei Can you provide the logs aas well as the dummy mstest project you created that caused the error. It would be great if we can get a repro of the project and the pipeline run.

**Comment by li-dawei** [comment]
@vagisha-nidhi Would it be OK to send you some of the things via email?

**Comment by ShreyasRmsft** [comment]
@li-dawei yes you can send it to devops_tools@microsoft.com

Any and all details you can provide will help as we have been unable to reproduce this issue at our end despite all our efforts. It seems like a small segment of customers are facing this and a consistent repro would go a long way in helping us fix this as soon as possible.

**Comment by ioananicu** [comment]
Not sure if this helps, but I created a tiny test plan to see if maybe having a fully successful run might help. I am having the same results sadly. Also, when I go to the test plan I can see past execution times for every test (including failures) 

![image](https://user-images.githubusercontent.com/58558196/70916222-f97ec380-2023-11ea-87f1-3c4a0a721152.png)

**Comment by li-dawei** [comment]
@ShreyasRmsft @vagisha-nidhi Sent to above email but got bounced: "The group sadadirs only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."

**Comment by vagisha-nidhi** [comment]
@li-dawei @ioananicu We were able to get a repro with us and have an RCA. Both these issues are happening in release. So we look at previous releases to determine the past execution times of tests. But  any previous release is only considered if all it's environments status is either Succeeded, Rejected or PartiallySucceded. (https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/environmentstatus). If any of the enviroments in your previous release is not in any of these status, that release is not considered as a baseline release to get anticipated execution time for time based slicing. This is done to ensure that we have all the tests run and their execution times so that we can get the most accurate timing for the slicing.
We created a repro based on this here https://dev.azure.com/AlekhyaTLS/Test1/_release?_a=releases&view=mine&definitionId=2 where the in the previous release one of the enviroments is in NotStarted status.
Can you check if your previous releases have any of the environments not in either of the 3 statuses mentioned? If yes, you can get those environments running as a workaround. Meanwhile, we'll check if we can fix this.

**Comment by ioananicu** [comment]
Hi, this is how our pipeline looks like:

![image](https://user-images.githubusercontent.com/58558196/70971824-76ed1700-20aa-11ea-9a28-4a63fb66fd6a.png)

We only run the tests on the CI environment, and indeed have 7 stages (representing different environents) that are only deployed when needed. 

I have created a release with only one stage to see if I can get the execution time to work.

**Comment by li-dawei** [comment]
Hi @vagisha-nidhi. I can indeed confirm after removing all other unexecuted stages (leaving just the test) in our release pipeline, the time slicing is now working. This sounds like a bug so looking forward for a fix.

In the meantime, I am not 100% certain what the proposed workaround is? Much like the scenario described by @ioananicu, we have various stages after the testing, and 99% of releases never run to completion. Is there a way to force set the status of a release without actually running a stage?

**Comment by vagisha-nidhi** [comment]
@li-dawei Thanks for confirming the issue. We'll mark this as a bug for now internally. 
There's no way you can force a status for a release environment. 
cc: @PBoraMSFT

**Comment by ioananicu** [comment]
Are there any updates on this issue? Will it be fixed or should we just forget about this feature?

**Comment by hvinett** [comment]
@ioananicu, we are picking very limited issues on priority. we will inform you after we resolve the issue.

**Comment by prasad-sunkara** [comment]
Have the same issue. Would like to see it resolved soon.

**Comment by ioananicu** [comment]
@prasad-sunkara Any updates on this item? I understand that an internal bug was created for this in the past. 
Should we wait for a fix or maybe its better to look into alternative ways of parallelizing our execution?
Is it worth keeping this thread open?

**Comment by gitsobotka** [comment]
Is this still an issue? Experiencing this behavior. Please fix this or document it in tasks behavior.
