### ISSUE TITLE
[Object reference not set to an instance of an object] when run Initialize containers task on azure devops pipeline

### ISSUE THREAD

**Issue by fernandoseguim** [microsoft/azure-pipelines-tasks#11902]
**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: Initialize containers*

## Environment
- Azure Pipelines
  
- Agent - Hosted

## Issue Description
When we use the container service in the Azure pipeline, the error "Object reference not defined for an instance of an object" occurs when it should initialize the container.

### Task logs

```
Starting: Initialize containers
/usr/local/bin/docker version --format '{{.Server.APIVersion}}'
'1.38'
Docker daemon API version: '1.38'
/usr/local/bin/docker version --format '{{.Client.APIVersion}}'
'1.38'
Docker client API version: '1.38'
/usr/local/bin/docker ps --all --quiet --no-trunc --filter "label=98a93d"
/usr/local/bin/docker network prune --force --filter "label=98a93d"
/usr/local/bin/docker pull amazon/dynamodb-local
Using default tag: latest
latest: Pulling from amazon/dynamodb-local
Digest: sha256:cbe14c530c08997a38da04efe3778242f5544e0cdb7e9002fbbc3682f2421c0c
Status: Image is up to date for amazon/dynamodb-local:latest
##[error]Object reference not set to an instance of an object.
Finishing: Initialize containers

```

**Comment by jtpetty** [comment]
@fernandoseguim - Can you confirm which version of the agent you are running? Is it possible for you to rerun with diagnostics turned on and send us that information?

**Comment by fernandoseguim** [comment]
Hi @jtpetty, sorry, I said my agents are hosted, but I was wrong. We use private agents in version ubuntu-16.04-docker-18.06.1-ce. I run the pipeline with diagnostics turned on. You need see what files?

**Comment by jtpetty** [comment]
@fernandoseguim - can you send me the contents of the _diag/ directory from the agent that is showing this issue? If there are too many logs there, I just need the Agent*.log and Worker*.log that show the issue.

**Comment by fernandoseguim** [comment]
@jtpetty these are [logs](https://acesso2-my.sharepoint.com/:f:/g/personal/fseguim_acesso_com/Es1eR-UIwtFIrkYaUhTD5WwBPF04K8c9IvQWgaRfRVLVeg?e=m4aDSw)

**Comment by jtpetty** [comment]
@fernandoseguim - I believe we may have already fixed this bug in the agent version 2.162.0. We have just started rolling out this fix, but if you are using a private agent, you could manually upgrade to this version and see if that fixes your issue.

**Comment by jtpetty** [comment]
closing this as this issue was resolved with a bug fix in the agent

**Comment by leonheess** [comment]
What kind of useless error is that anyway??
