### ISSUE TITLE
Add-AzMetricAlertRuleV2 Fails in Azure DevOps with Agent "vs2017-win2016"

### ISSUE THREAD

**Issue by techsaau** [microsoft/azure-pipelines-tasks#11917]
Command "Add-AzMetricAlertRuleV2" is using object **<System.Collections.Generic.List`1[Microsoft.Azure.Commands.Insights.OutputClasses.IPSMultiMetricCriteria]>** for condition parameter in Az module. But "**Microsoft.Azure.Commands.Insights**" namespace was used in AzureRM.Insights. When I use Azure Powershell Task in DevOps (under agent "vs2017-win2016"), it gives error:

**Cannot find type [System.Collections.Generic.List[Microsoft.Azure.Commands.Insights.OutputClasses.IPSMultiMetricCriteria]]: verify that the assembly containing this type is loaded.**

How can I fix this asap?

Azure PowerShell Task
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops

Initial request
[https://github.com/MicrosoftDocs/vsts-docs/issues/6569](url)

**Comment by techsaau** [comment]
can somebody help here?

**Comment by asranja** [comment]
@techsaau I was able to successfully add an alert rule using the following cmdlets:

```
$condition = New-AzMetricAlertRuleV2Criteria -MetricName "Percentage CPU" -MetricNameSpace "Microsoft.Compute/virtualMachines" -TimeAggregation Average -Operator GreaterThan -Threshold 5
$ag = Get-AzActionGroup -Name testactiongroup -ResourceGroupName testrg
$AGAlertObject = New-Object Microsoft.Azure.Management.Monitor.Management.Models.ActivityLogAlertActionGroup
$AGAlertObject.ActionGroupId = $ag.Id 

Add-AzMetricAlertRuleV2 -Name TestRule -ResourceGroupName testrg -WindowSize 0:5 -Frequency 0:5 -TargetResourceScope "/subscriptions/00000000-0000-0000-0000-0000000/resourceGroups/testrg/providers/Microsoft.Compute/virtualMachines/testvm" -TargetResourceType "Microsoft.Compute/virtualMachines" -TargetResourceRegion "southeastasia" -Description "This is description" -Severity 4 -Condition $condition -ActionGroup $AGAlertObject
```

Are you passing the Microsoft.Azure.Commands.Insights object into the condition parameter ? 

Please try out the above approach and let me know if it works out for you.

**Comment by techsaau** [comment]
@asranja Thanks for your response. 
For single condition, it is working fine for me as well. But it gives error for multiple alert conditions.

$alert.Metrics = @{<<Multiple alert conditions>>}
$AlertCondition = New-Object "System.Collections.Generic.List``1[Microsoft.Azure.Commands.Insights.OutputClasses.IPSMultiMetricCriteria]"
    foreach ($Metric in $alert.Metrics) {
        $AlertCriteria = New-AzMetricAlertRuleV2Criteria -MetricName $Metric.Name -MetricNameSpace $alert.NameSpace `
                        -TimeAggregation $Metric.TimeAggregation -Operator $Metric.Operator -Threshold $Metric.Threshold
        $AlertCondition.Add($AlertCriteria)
    }

It is working fine in my local system. So no issue with code.

**Comment by asranja** [comment]
@techsaau  The type **[System.Collections.Generic.List[Microsoft.Azure.Commands.Insights.OutputClasses.IPSMultiMetricCriteria]]** was introduced in a later version of Az.Monitor which is not currently installed on the hosted agent and hence you are facing this issue. The current version of Az.Monitor on hosted agent is 1.2.2

While we figure out the next steps, can you try this instead and see if it fits your requirements:
```
Import-Module Az.Monitor
$a = New-Object System.Collections.Generic.List[Microsoft.Azure.Commands.Insights.OutputClasses.PSMetricCriteria]
```
Refer to the [commit](https://github.com/Azure/azure-powershell/pull/9763/commits/8ee23c5f165bc60d552df5f619aa7130e3e1055c) for type change details.

**Comment by techsaau** [comment]
@asranja  workaround is working as expected.
Thanks for your help.

**Comment by asranja** [comment]
Closing the issue. We will track the update with an internal work item.
