### ISSUE TITLE
[Azure Devops k8s manifest task] Rollout deployment timeout setting

### ISSUE THREAD

**Issue by mo-saeed** [microsoft/azure-pipelines-tasks#11914]
Hello,

Currently our pipeline fails due to timeout in the deploy step of KubernetesManifest task.

when running kubectl rollout status command:

##[error]error: deployment "XXXX" exceeded its progress deadline
Is there any way to have a setting to increase the timeout, I think it's 2 minutes by default.

**Comment by shigupt202** [comment]
@mo-saeed The default timeout is 10 minutes. You can, however, set `progressDeadlineSeconds` to desired timeout value in the spec of your deployment manifest file.

**Comment by hdiass** [comment]
Nice one!
