### ISSUE TITLE
docker command failed with "unauthorized: authentication required" after changing resource group in ACR

### ISSUE THREAD

**Issue by xerothermic** [microsoft/azure-pipelines-tasks#11910]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Server - Azure Pipelines: BluebirdSW
- Agent - Hosted or Private: Private (ubuntu 18.04), agent ver: 2.160.1

## Issue Description
We have a working azure pipeline that will fetch base image from ACR and push new image back to ACR. Yesterday, we moved the ACR under a different resource group, and many authentication failed. We than move the ACR back to original resource group and created a new service connection to ACR from Azure pipeline, but when trying to fetch or push images to ACR, it error out with "unauthorized: authentication required"

How may we reset so authentication can work again?

**Comment by ajinkya599** [comment]
Hi @xerothermic, we will need some info to understand the problem:
- Are you using script or Docker task for pull/push ? If it is Docker task, what version of the task are you using ?
- What is the service connection type that you are using ? Can you share a screenshot showing your service connection ?
- Can you share a snippet of your pipeline yaml ?

**Comment by xerothermic** [comment]
Hi @ajinkya599,

For some reason, I created a new service connection to ACR, and it's able to authenticate in pipeline now. I'll close this request now.

**Comment by ajinkya599** [comment]
@xerothermic - Thanks for sharing the update.
