### ISSUE TITLE
Visual Studio Test v 2.* fails if no test sources found (used to work a few days ago with just a warning)

### ISSUE THREAD

**Issue by gonzaloluna** [microsoft/azure-pipelines-tasks#11911]
I have a generic task group for some of my projects in which some of them have tests and others don't.
Now every time I try to build a project with no tests assemblies the build task fails.

Previously the task would give me a warning, which was OK for me.

Is this something you've just changed in the latest version? can you put it back? or just add an option to not fail the task?

##[debug]Agent.Version=2.155.1
##[debug]Release.ReleaseUri=undefined
##[debug]Release.ReleaseId=undefined
##[debug]Build.BuildUri=vstfs:///Build/Build/2383
##[debug]Build.Buildid=2383
##[debug]telemetry area: TestExecution feature: TestExecutionTask data: {"builduri":"vstfs:///Build/Build/2383","buildid":"2383","state":"completed"}
##[debug]Processed: ##vso[telemetry.publish area=TestExecution;feature=TestExecutionTask;]{"builduri":"vstfs:///Build/Build/2383","buildid":"2383","state":"completed"}
##[error]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '*test*.dll,!*TestAdapter.dll,!\obj**'
##[debug]Processed: ##vso[task.issue type=error;]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '*test*.dll,!*TestAdapter.dll,!\obj**'
##[debug]task result: Failed
##[error]VsTest task failed.
##[debug]Processed: ##vso[task.issue type=error;]VsTest task failed.
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]VsTest task failed.
Finishing: VsTest - testAssemblies

**Comment by ShreyasRmsft** [comment]
This has been hotfixed. Please re-open if you are still facing the issues with task version 2.161.4 or higher. Thanks

**Comment by logdog16** [comment]
Hello, I'm also running into this issue @ShreyasRmsft and can't get 2.161.4 to download. I keep getting 2.161.2 (which errors out with no tests selected) even after using a VisualStudioTestPlatformInstaller job to try and update to latest. Any tips on how to get v2.161.4 to download as part of my job?

**Comment by ShreyasRmsft** [comment]
@logdog16 the roll-out was pending for one ring of accounts, give it a shot now.

**Comment by logdog16** [comment]
There we go! Our hosted agents picked up the change overnight and our builds started working again this morning. Thank you :)

**Comment by vagisha-nidhi** [comment]
Closing the issue since this is resolved. Thanks.
