### ISSUE TITLE
Kubectl: Release variables in K8s Service connection

### ISSUE THREAD

**Issue by luca-esse** [microsoft/azure-pipelines-tasks#11920]
*Type*: Bug

**Task Name**: KubernetesV1

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesV1

## Environment
- Server - Azure Release Pipelines

- Agent - Hosted: 
    
    - Agent queue name: Azure Pipelines (Default)

## Issue Description

Our kubectl task has the following k8s service connection: "miranda-aks-$(Release.EnvironmentName)" and it stopped working since yesterday.
When we try to deploy a stage of our release pipeline the following error appears immediatly:
_Something went wrong preparing the stage for deployment. Please redeploy the stage._

## Troubleshooting
If we change the service connection to a fixed string like "miranda-aks-dev" or if we use a custom variable like "miranda-aks-$(SomeVarName)" it works as expected. 
**The problems seems to occur only when using the predefined release variables**.

## Screenshots
![image](https://user-images.githubusercontent.com/16616566/70318099-84d7a800-181f-11ea-87e2-041322ec1a9f.png)

![image](https://user-images.githubusercontent.com/16616566/70318130-9faa1c80-181f-11ea-9ace-370cc7f9dd98.png)

**Comment by luca-esse** [comment]
Hello,
Our relase ppipeline is working again, it looks like the problem has been fixed.
Any idea on the root cause of the problem?

**Comment by vithati** [comment]
@luca-esse, Sorry for the inconvenience. We have rollbacked the changes which causing the issue.
