### ISSUE TITLE
The term 'Get-AzureRmOperationalInsightsWorkspace' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by sanoraya** [microsoft/azure-pipelines-tasks#11928]
Hi, I am using Azure Powershell task in my pipeline to enable Log Analytics in Logic Apps. 
The script runs well from command line but fails in Azure PowerShell Task with "The term 'Get-AzureRmOperationalInsightsWorkspace' is not recognized as the name of a cmdlet"
Not sure if it's me doing something wrong or it's a bug.
[ReleaseLogs_382.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3934431/ReleaseLogs_382.zip)

**Comment by asranja** [comment]
Azure PowerShell V4 task supports only Az version of the cmdlets by default. So in your case you should use **Get-AzOperationalInsightsWorkspace**.

However, if you still want to use AzureRm based cmdlets, run '**Enable-AzureRmAlias**' in the script before using AzureRm cmdlets.

**Comment by sanoraya** [comment]
Thank you, that helped!
