### ISSUE TITLE
KubernetesManifestV0 :: Container image substitution not working if you have a "-" before the image: tag

### ISSUE THREAD

**Issue by sindrunas** [microsoft/azure-pipelines-tasks#11921]
The following code is a valid kubernetes yaml, but if you write it this way container image substituion will not work.
Example: 

    spec:
      containers:
      - image: your image

**Comment by sindrunas** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/11924/commits/cba4170f5dd7dd9bbf71ef9fe518e9b71d5613ab

**Comment by vithati** [comment]
@sindrunas , This issue will be fixed with this change, https://github.com/microsoft/azure-pipelines-tasks/pull/11883
