### ISSUE TITLE
AppCenterDistributeV3 should truncate release notes

### ISSUE THREAD

**Issue by evkhramkov** [microsoft/azure-pipelines-tasks#11922]
*Type*: Bug

**Enter Task Name**: AppCenterDistributeV3  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AppCenterDistributeV3

## Issue Description

Distribution step should truncate release notes which exceeds 5000 characters limit instead of failing build

**Comment by matt-aitken** [comment]
We get this happening a lot when merging branches, very frustrating. Would be great if this could be fixed.
