### ISSUE TITLE
Universal Packages task should link to documentation

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-tasks#11933]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Universal Packages

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/UniversalPackagesV0

## Issue Description
When setting up the Universal Packages task, the "About this task" link goes to [a blog article](https://aka.ms/universalpackagesannounce), instead of [the task documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops).

![image](https://user-images.githubusercontent.com/1784452/70449138-1d139e00-1a67-11ea-8667-7ebd072dba06.png)

**Comment by shadargee1982** [comment]
This should be fixed with v. 0.174.1 of UniversalPackages task
