### ISSUE TITLE
[Feature request] KubernetesManifestV0 task: configmap, timeout

### ISSUE THREAD

**Issue by t03apt** [microsoft/azure-pipelines-tasks#11937]
## Feature request for KubernetesManifestV0 task
Please add support to KubernetesManifestV0 for
- creating a configmap 
- setting a timeout for checking the success of the deployment

**Comment by shashankbarsin** [comment]
Right now you can have ConfigMap in the input manifest files and they'll be deployed by KubernetesManifest task. We have a item in our backlog to add versioning ability for the ConfigMaps deployed using the task.

Being able to specify timeout limit for checking success of deployment is a small addition to add. Will do that right away and roll out the changes this sprint.

**Comment by vithati** [comment]
@t03apt , We have added timeout for status check https://github.com/microsoft/azure-pipelines-tasks/issues/12010 in task. and this fix will be deployed in couple of weeks.  "Create config map" added in backlog, we will address that soon. Hence closing the issue.
