### ISSUE TITLE
gulp version in that task

### ISSUE THREAD

**Issue by nickgsoft** [microsoft/azure-pipelines-tasks#11938]
while using ulp taks in the azure devops, getting below error. looks like we needs to change the gulp version in the Azure devops task, but do not have any option to change the gulp version. please assist if there is a way and how should i utilize that?

##[section]Starting: gulp CI-Build
==============================================================================
Task         : Gulp
Description  : Node.js streaming task based build system
Version      : 0.141.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613721)
==============================================================================
[command]C:\npm\prefix\gulp.cmd CI-Build --gulpfile D:\a\1\s\gulpfile.js
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (D:\a\1\s\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\a\1\s\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\a\1\s\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
##[error]Gulp failed with error: C:\npm\prefix\gulp.cmd failed with return code: 1
##[section]Finishing: gulp CI-Build

https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by jmyersmsft** [comment]
I don't personally have much knowledge of gulp or the gulp task, but it's likely the task uses whatever `gulp` binary is on the PATH, so it's likely the following command will update to the latest:

```
npm install --global gulp-cli
```

**Comment by herenhuang** [comment]
@nickgsoft - are you still having troubles here? Please reopen if it's still an issue.
