### ISSUE TITLE
Hide the substituted values in the FileTransform(V2) task

### ISSUE THREAD

**Issue by pasasorin** [microsoft/azure-pipelines-tasks#11930]
*Type*: Feature

**Enter Task Name**: FileTransform(V2) 

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/FileTransformV2

## Environment
- Server - both Azure Pipelines and Azure DevOps Server
- Agent - doesn't matter
## Issue Description

When running the task for JSON substitution, it displays in the logs the values that it has replaced.
Can you add an option to hide/obfuscate the values, since sometimes we use the task to replace sensitive/secret values? 

Example of the task logs:
Substituting value on key value with (string) value: mysecret1
Substituting value on key value with (string) value: mysecret2

should be:
Substituting value on key value with (string) value: ****
Substituting value on key value with (string) value: ****

**Comment by asranja** [comment]
For substituting secret values, the recommended approach is to mark the variable as a secret variable. This will automatically hide the value from the logs.

**Comment by pasasorin** [comment]
I was thinking to get the secret values from a Secure File from Library. But I guess I can read them from the file and pass them in the pipeline using the "issecure=true" option, like:
   write-host  ("##vso[task.setvariable variable=$Name;issecret=true]$Value")
Thank you for the reply, you can close this request.
Sorin
