### ISSUE TITLE
AzureAppServiceSettingsV1 slot fails to populate

### ISSUE THREAD

**Issue by Debbus72** [microsoft/azure-pipelines-tasks#11948]
*Type*: Bug
**Enter Task Name**: AzureAppServiceSettings
## Environment
- Server - Azure Pipelines
- Agent - Private

## Issue Description
I'm testing the AzureAppServiceSettingsV1-preview task. 
There is a problem within the editor. The Slot-entry will not populate the list. It shows 'No Results Found.'

### Task logs
Not a task log, but when I open the developer-tools it shows the following message:
```
statusCode: "forbidden"
errorMessage: "Failed to query service connection API: 'https://management.azure.com/subscriptions/.../resourceGroups/providers/Microsoft.Web/sites/.../slots?api-version=2018-11-01'. Status Code: 'Forbidden', Response from server: '{"error":{"code":"AuthorizationFailed","message":"The client '...' with object id '...' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/Microsoft.Web/.../read' over scope '/subscriptions/.../resourceGroups/providers/Microsoft.Web/sites/.../slots' or the scope is invalid. If access was recently granted, please refresh your credentials."}}'"
```

This is strange, because other tasks in the pipeline can query the slots. In the developertools, I can see that the following data is posted: 
```
{
    "serviceEndpointDetails": null,
    "dataSourceDetails": {
        "dataSourceName": "AzureRMWebAppSlotsId",
        "resourceUrl": "",
        "parameters": {
            "appName": " <removed> ",
            "resourceGroupName": " <removed> ",
            "ConnectedServiceName": " <removed> ",
            "WebAppName": " <removed> ",
            "ResourceGroupName": " <removed> "
        }
    },
    "resultTransformationDetails": {
        "resultTemplate": "{\"Value\":\"{{{ #extractResource slots}}}\",\"DisplayValue\":\"{{{ #extractResource slots}}}\"}"
    }
}
```

The difference with the calls from the tasks that succeed, is that there are extra properties `appName` and `resourceGroupName`, but I do not know if that is the problem.

**Comment by asranja** [comment]
We recently fixed an issue related to slots which is currently undergoing deployment. 

The url **_https://management.azure.com/subscriptions/.../resourceGroups/providers/Microsoft.Web/sites/.../slots?api-version=2018-11-01_** does not have resource group name in it. This could be causing the issue for you.

**Comment by Roshan-Kumar-Microsoft** [comment]
@Debbus72  We had already fixed this issue. Are you still facing this issue ?

**Comment by Debbus72** [comment]
For me the problem still exists.
However, it looks like our organisation is still on Azure DevOps sprint 161, but I do not know if that is a problem. How can I check that I use the latest version of the task? (the task still show `1.* (preview)`)

**Comment by eaarora-ms** [comment]
@Debbus72  Can you confirm the full task version from the pipeline logs?

**Comment by Debbus72** [comment]
```
2020-01-09T06:43:26.4156524Z ##[section]Starting: Azure App Service Settings: Test
2020-01-09T06:43:26.4769139Z ==============================================================================
2020-01-09T06:43:26.4769325Z Task         : Azure App Service Settings
2020-01-09T06:43:26.4769404Z Description  : Update/Add App settings an Azure Web App for Linux or Windows
2020-01-09T06:43:26.4769483Z Version      : 1.158.3
2020-01-09T06:43:26.4769544Z Author       : Microsoft Corporation
2020-01-09T06:43:26.4769598Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2020-01-09T06:43:26.4769677Z ==============================================================================
2020-01-09T06:43:29.1526738Z Got service connection details for Azure App Service:'Test'
2020-01-09T06:43:29.1736850Z Updating App Service Application settings. Data: {"key1":"valueabcd","key2":"valueefgh"}
2020-01-09T06:43:29.6450829Z Updated App Service Application settings and Kudu Application settings.
2020-01-09T06:43:30.4649433Z ##[section]Finishing: Azure App Service Settings: Test
```

**Comment by eaarora-ms** [comment]
@Debbus72  Yes this is the previous version of the task. I am assuming due to the Holiday season the deployment was not done in your account. Please wait for a few more days. Thanks!

**Comment by Debbus72** [comment]
We finally got the update yesterday (Azure DevOps sprint 162) and now it works!
Thank you.
