### ISSUE TITLE
AzureAppServiceSettingsV1 incorrect log line

### ISSUE THREAD

**Issue by Debbus72** [microsoft/azure-pipelines-tasks#11947]
*Type*: Bug
**Enter Task Name**: AzureAppServiceSettings
## Environment
- Server - Azure Pipelines
- Agent - Private

## Issue Description
I'm testing the AzureAppServiceSettingsV1-preview task. 
There is a small problem with the log, that shows a `Data %s` where it should not.

### Task logs
```
Updating App Service Connection Strings. Data: { <removed> }
Updated App Service Connection Strings. Data: %s
```

The last log-line should not show 'Data: %s' on the end.

**Comment by asranja** [comment]
Thanks for pointing this out. We will fix this in the upcoming release.
