### ISSUE TITLE
AzureFunctionApp@1 incorrectly reports success

### ISSUE THREAD

**Issue by M0ns1gn0r** [microsoft/azure-pipelines-tasks#11940]
**Question, Bug, or Feature?**: Bug

**Enter Task Name**: AzureFunctionApp@1

## Environment
- Server - Azure Pipelines
- Agent - Hosted ubuntu-latest

## Issue Description

Although the deployment of my function fails due to problems connecting with AppInsights, the task itself succeeds. The function app is not working after deployment, the site contains the file FAILED TO INITIALIZE RUN FROM PACKAGE.txt.

**Expected behavior**: the deployment task should fail.

### Task logs

```
##[debug][PUT]https://management.azure.com/subscriptions/.../resourceGroups/cp-test/providers/microsoft.insights/components/cp-test/Annotations?api-version=2015-05-01
##[debug]addReleaseAnnotation. Data : {"statusCode":404,"statusMessage":"Not Found","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"153","content-type":"application/json; charset=utf-8","expires":"-1","x-content-type-options":"nosniff","request-context":"appId=cid-v1:920e14b1-13f3-461a-a4bb-b4fe6f1a4525","access-control-expose-headers":"Request-Context","strict-transport-security":"max-age=31536000; includeSubDomains","x-ms-ratelimit-remaining-subscription-writes":"1199","server":"Microsoft-IIS/10.0","x-ms-request-id":"4d06217a-318c-44d8-99d4-f9be9a897d5c","x-ms-correlation-request-id":"4d06217a-318c-44d8-99d4-f9be9a897d5c","x-ms-routing-request-id":"SOUTHCENTRALUS:20191209T153700Z:4d06217a-318c-44d8-99d4-f9be9a897d5c","date":"Mon, 09 Dec 2019 15:36:59 GMT","connection":"close"},"body":{"code":"NotFound","message":"Not Found","innererror":{"diagnosticcontext":"a5a6fd35-fc61-45b9-a3b1-4a29b9a8a1ff","time":"2019-12-09T15:37:00.2252213Z"}}}
Failed to add release annotation. Error: Failed to update Application Insights 'cp-test' Resource. Error: NotFound - Not Found (CODE: 404)
##[debug][POST]https://management.azure.com/subscriptions/.../resourceGroups/cp-visits-test/providers/Microsoft.Web/sites/cp-visits-test/publishxml?api-version=2016-08-01
##[debug]Could not parse response: {}
##[debug]Response: undefined
...
##[debug]Deployment Succeded
```

**Comment by Roshan-Kumar-Microsoft** [comment]
@M0ns1gn0r  This is expected behavior As addReleaseAnnotation is for traceability purpose so even it fail we are not failing the deployment.

**Comment by M0ns1gn0r** [comment]
@Roshan-Kumar-Microsoft that cannot be expected behavior because as I wrote the function app _**is not working**_ after deployment,

**Comment by SumiranAgg** [comment]
@M0ns1gn0r The failure you see in the logs is for when we try to put some meta data for the purpose of traceability. Failing here is irrelevant to the deployment operation hence we do not fail the task.

For deployment to function app we do an appsetting WEBSITE_RUN_FROM_PACKAGE in your app service and them make a rest call to kudu (zipdeploy). If the response to this call is not 200 we fail the task. The error you see is a runtime failure, mostly attributed to some issue with the package. Does the package work locally? You can checkout this [link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference) on how to dev and test locally.

**Comment by M0ns1gn0r** [comment]
Thank you for the answer. If kudu answers 200 and creates FAILED TO INITIALIZE RUN FROM PACKAGE.txt that's surely another problem (though a problem, still). I guess this issue can be closed as honestly I don't remember how I worked around this issue.
