### ISSUE TITLE
Inconsistent error messages between NuGetAuthenticate@0 and DotNetCoreCLI@2 to access a private nuget feed

### ISSUE THREAD

**Issue by christopheblin** [microsoft/azure-pipelines-tasks#11959]
**Question, Bug, or Feature?**   Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Azure Pipelines : account = infologic-sante ; project = AIS - GIS ; pipeline = AIS-GIS Tests

- Agent - Hosted (whatever the queue)

## Issue Description
Here is the yaml:

    variables: 
      NuGet.ForceEnableCredentialProvider: true
      NuGet.ForceEnableCredentialProviderV2: false
    jobs:
    - job: Build_and_test 
      steps:
      - task: NuGetAuthenticate@0
        inputs:
          forceReinstallCredentialProvider: true
      - task: DotNetCoreCLI@2
        displayName: "Xxxxxx.sln"
        inputs:
          command: 'test'
          workingDirectory: 'Xxxxxx'
          feedsToUse: 'select'
          vstsFeed: 'AIS - GIS/AisGis'
          includeNuGetOrg: true
          
### Task logs

Relevant parts 

NugetAuthenticate says:

    Setting up the credential provider to use the identity 'AIS - GIS Build Service (infologic-sante)' for feeds in your organization/collection starting with:
      https://infologic-sante.pkgs.visualstudio.com/
      https://pkgs.dev.azure.com/infologic-sante/

DotNetCoreCLI@2 then says:

    C:\Program Files\dotnet\sdk\3.0.101\NuGet.targets(123,5): error : Problem starting the plugin 'C:\Users\VssAdministrator\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. Plugin 'CredentialProvider.Microsoft' failed within 5.957 seconds with exit code -1. [d:\a\1\s\Xxx\Xxx.sln]
    C:\Program Files\dotnet\sdk\3.0.101\NuGet.targets(123,5): error : Unable to load the service index for source https://infologic-sante.pkgs.visualstudio.com/xxx/_packaging/AisGis/nuget/v3/index.json. [d:\a\1\s\Xxx\Xxx.sln]
    C:\Program Files\dotnet\sdk\3.0.101\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [d:\a\1\s\Xxx\Xxx.sln]

Note that I've obviously tried without the variables, without the NugetAuthenticate task and without  forceReinstallCredentialProvider...

To me, it seems that the DotNetCoreCli@2 does not reuse the same credentials from NugetAuthenticate (but I may be wrong, this happen very often ;))

It seems related to https://github.com/microsoft/azure-pipelines-tasks/issues/10377 but I am not sure either

**Comment by christopheblin** [comment]
I should add that, with the same account / project (so with the same build agent), I can push nugets to the feed thanks to "nuget push" via NuGetCommand@2

**Comment by shubham90** [comment]
@christopheblin Nuget Authenticate task is meant to be used only with cmd/poweshell scripts. The dotnetCoreCLIV2 and NugetCommandV2 tasks have their own auth process. So, I would suggest using nuget authenticate task with a cmd line script to do 'dotnet test'. You can refer to some examples [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#dotnet).

Also, I don't think you need to set the variables(NuGet.ForceEnableCredentialProvider: true, NuGet.ForceEnableCredentialProviderV2: false)  NugetAuthenticate task only works with credential provider v2 and it needs nuget 4.8 and above, you do not need these variables. You are using dotnet 3.0.100 which also works with cred provider v2, so it should be fine.

**Comment by christopheblin** [comment]
@shubham90 are you saying that this should work without NugetAuthenticate ?

Because, I've also tried that (only DotNetCoreCLI@2) but then the error is a bit different and says:

    d:\a\1\s\xxx\xxx\xxx.csproj : error NU1101: Unable to find package XXX. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org [d:\a\1\s\xxx\xxx.sln]

To me, it seems that without NugetAuthenticate, DotNetCoreCLI does not even tries to authenticate to the private feed ...

**Comment by christopheblin** [comment]
Workaround : add an explicit dotnet restore task and specify `arguments: '--no-restore'` for the dotnet test task

See https://stackoverflow.com/a/59317254/1545567 and https://github.com/MicrosoftDocs/vsts-docs/issues/6666

**Comment by shubham90** [comment]
Ah, I missed that it's a test command. Test command does not support feedsToUse OR vstsFeed and therefore it does not do auth. For restore/publish it should auth without NuGet Authenticate task. 

You can still use Nuget Authenticate with a cmdline task for the test command. The authenticate task provides more options because users can do anything from the cmdline script and not worry about auth.

**Comment by bishal-pdMSFT** [comment]
@shubham90 I know that @elbatk has mentioned earlier (in other threads) that Nuget Authenticate task is the new preferred approach for authenticating to Nuget feed. But I was not aware that this does not work well with .Net Core CLI task. Is there any reason why so? Is there a plan to add the support because if I understand correctly there are shortcoming in authentication logic in .Net Core task which Nuget Authenticate task solves.
Will Nuget Authenticate task work well for commands in .Net core task other than restore or publish? For example, there are customer who want to use a custom command to install a tool from Nuget feed.

**Comment by chucker** [comment]
> Nuget Authenticate task is meant to be used only with cmd/poweshell scripts. The dotnetCoreCLIV2 and NugetCommandV2 tasks have their own auth process.

This seems to be contradicted by [the FAQ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#how-is-this-task-different-than-the-nugetcommand-and-dotnetcorecli-tasks):

> How is this task different than the NuGetCommand and DotNetCoreCLI tasks?
>
> [..] The NuGetCommand and DotNetCoreCLI tasks require using the task to restore or push packages, as authentication to Azure Artifacts is only configured within the lifetime of the task. [..]
>
> The NuGetAuthenticate task is the recommended way to use authenticated feeds within a pipeline.

That seems to suggest that dotnetCoreCLIV2 and NugetCommandV2 in fact expect NuGetAuthenticate to be run (where applicable).

**Comment by christopheblin** [comment]
The underlying issue is still not fixed : dotnet CLI test task is not 100% compliant with nuget options...

The workaround is to "split" the test task in 2 tasks (workaround provided by a MS employee at https://stackoverflow.com/a/59317254/1545567, see below).

This is now documented at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#why-is-my-build-publish-or-test-step-failing-to-restore-packages

Workaround:
```
steps:
- task: DotNetCoreCLI@2
  displayName: "My restore task."
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    feedRestore: 'ProjectName/FeedName' #Using ProjectName/FeedName if it's project scoped feed.
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: "My test task."
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--no-restore'
```
