### ISSUE TITLE
Azure Key Vault Task set pipeline variable name for a secret

### ISSUE THREAD

**Issue by mamutmk5** [microsoft/azure-pipelines-tasks#11951]
*Type*: Feature
**Enter Task Name**: Azure Key Vault

## Environment
- Server - Azure Pipelines 
- Pipeline - Task groups or release pipeline 
- Agent - Hosted

## Issue Description
I want to use a Azure Key Vault Task followed by any other task at a task group in multiple stages from a release pipeline with different secrets for the stage of release pipeline.
The secret is selectet over an pipeline variable but the secret variable is name after the secret.
I haven't found a way to pass the secret from different secret variables to the same variable in the next task.
So i request a way in the Azure Key Vault Task to set for a secret the pipeline variable name, in exampel like the envieroment variables for Command line Task.

**Comment by mamutmk5** [comment]
Are there any it updates for it?

**Comment by rohit-batra** [comment]
@mamutmk5  Can you please explain a bit more, if possible with examples ? I am afraid i am not able to understand this completely.  cc  @shashban

**Comment by mamutmk5** [comment]
> 
> 
> @mamutmk5 Can you please explain a bit more, if possible with examples ? I am afraid i am not able to understand this completely. cc @shashban

Azure Key Vault was like:
host_enviorment_password_stage_1
host_enviorment_password_stage_2
....
host_enviorment_password_stage_n

The pland task group hade a paramter stage with the vaules stage_1 to stage_n.
In the task grup where pland a task who say get the kay for host_enviorment_password_${stage} from Azure Key Vault to the Stage Variable enviorment_password.
And then use the Stage Variable enviorment_password for exampel to login to mount an SMB File share copy some files and unmout it or do other stuff with the Stage Variable enviorment_password.
