### ISSUE TITLE
Instructs the pipeline it's ok to save cache on partial builds?

### ISSUE THREAD

**Issue by nulltoken** [microsoft/azure-pipelines-tasks#11950]
Hello,

It looks like the cache is only persisted on "Successful" builds (cf. https://github.com/microsoft/azure-pipelines-agent/blob/0533383fe43ae079cd1d8f38342bbd465e7c2c4e/src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs#L27-L30).

Some of our tasks fail on non critical steps (`yarn outdated` for instance) and are decorated with the "continueOnError" marker. We use this to warn the user that the build passed but some work still has to be done.

How open would you be to add an opt-in option to allow cache saving on "Partially succeeded" builds?

**Comment by roy-shantanu** [comment]
any update on this? I would very much like to have this feature

**Comment by fadnavistanmay** [comment]
Hello,

We have decided to only allow caching for successful builds.

Thanks.

**Comment by anorborg** [comment]
Hello, just wanted to throw another use-case out there for consideration of that feature; namely flakey tests. Being able to compile binaries and cash them based on the commit id and rerun a failed build/stage due to a flakey test without running the full build again necessarily.

**Comment by qxg** [comment]
@fadnavistanmay could you share the reason behind the decision? At least you should give the control to end users.
