### ISSUE TITLE
KubernetesManifest error with smi trafficSplitMethod and Istio

### ISSUE THREAD

**Issue by yelob** [microsoft/azure-pipelines-tasks#11953]
*Type*: Bug

**Enter Task Name**: KubernetesManifest

## Issue Description

If you try to use smi as the trafficSplitMethod, the KubernetesManifest task attempts to use the TrafficSplit kind defined by the SMI spec with version "v1alpha1". However, if you install the latest CRDs from the spec for Istio (https://github.com/deislabs/smi-adapter-istio), they are on version "v1alpha2", so these calls fail. The workaround is to look in the history of the repo and install the older v1alpha1 version.

### Error logs

```##[error]error: unable to recognize "/home/vsts/work/_temp/TrafficSplit_audit-service_1575913349889": no matches for kind "TrafficSplit" in version "split.smi-spec.io/v1alpha1"```

**Comment by ds-ms** [comment]
This issue is being addressed in #11906

**Comment by vithati** [comment]
@yelob , We have checked-in changes. Fix will be deployed in couple of weeks.
