### ISSUE TITLE
SCVMM task: Where to report issues?

### ISSUE THREAD

**Issue by NenoLoje** [microsoft/azure-pipelines-tasks#11960]
The [SCVMM integration](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.scvmmapp) tasks don't seem to be part of this repo.

Are they in a different repo or **where would be the best place to report issues?**

Thanks,
--Neno

**Comment by chshrikh** [comment]
you can ask [here](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.scvmmapp&ssr=false#qna)
