### ISSUE TITLE
Issue: AppCenterDistributeTask: Include Collaborators (default) Group in a list of Group Ids

### ISSUE THREAD

**Issue by barrcodes** [microsoft/azure-pipelines-tasks#11961]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AppCenterDistribute

## Environment
- Server - Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - For security reasons, account info can be provided privately

- Agent - Hosted or Private: 
    
    - Not 100% on this, I don't manage the agents. Probably one of the Azure Pipelines agents

## Issue Description

This task allows either:
- a list of comma or semicolon delimited group ids
- an empty string, which specifies "default"

However, I have a situation where I would like to specify, say, the QA group (which has a numeric id specified in App Center group settings) as well as the default "Collaborators" group (which does not specify an id).

I am uncertain how to define the default Collaborators group in this list, since it does not define an ID in group settings.

**Comment by terenceyan** [comment]
I've ran into this exact same problem. It's unclear from the documentation how to do this without uploading two separate build. But it can be done via the web interface, so it can be done?
