### ISSUE TITLE
There is no documentation about how to develop custom flaky tests detection methods

### ISSUE THREAD

**Issue by ligurio** [microsoft/azure-pipelines-tasks#11967]
## Note  

Article in [Azure documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops) describes custom flaky tests detection methods. There is a [similar question](https://developercommunity.visualstudio.com/content/problem/722029/how-to-implement-custom-flaky-test-detection-in-az.html) without answer on forum. But there are no details about developing such custom methods. Please enhance documentation or share information here.

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Comment by damccorm** [comment]
Hey @ligurio - this seems like its probably a better question for our docs repo - https://github.com/MicrosoftDocs/vsts-docs/issues. I'm going to close here, would you mind filing a bug there?

**Comment by ligurio** [comment]
Done - https://github.com/MicrosoftDocs/vsts-docs/issues/6700
