### ISSUE TITLE
Azure Dev-Ops Build is failing at step "restore bower package" since batchscript 1.1.8

### ISSUE THREAD

**Issue by Chaouki-Tiouassiouine** [microsoft/azure-pipelines-tasks#11978]
## Environment
- Server - Azure Pipelines - Azure Dev-Ops
- Batch script 1.1.8 during build

## Issue Description

Since the release of 1.18 Batch script, I am having trouble building my project in Azure Dev-Ops it is failing at step "Restore Bower Packages". Nothing has changed in the directory of Bower..

## Error logs

> ##[debug]Evaluating condition for step: 'Restore Bower Packages'
> ##[debug]Evaluating: succeeded()
> ##[debug]Evaluating succeeded:
> ##[debug]=> True
> ##[debug]Result: True
> ##[section]Starting: Restore Bower Packages
> ==============================================================================
> Task         : Batch script
> Description  : Run a Windows command or batch script and optionally allow it to change the environment
> Version      : 1.1.8
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/batch-script
> ==============================================================================
> ##[debug]tf vc resolvePath $\ECM_Infoportaal\branches\ReleaseCandidate\Infoportaal\ProRail.Infoportaal /loginType:OAuth /login:.,*** /noprompt
> ##[debug]d:\a\36\s\Infoportaal\ProRail.Infoportaal
> ##[debug]Working directory: 'd:\a\36\s\Infoportaal\ProRail.Infoportaal'
> ##[debug]Fail on standard error: 'False'
> ##[debug]Modify environment: 'False'
> ##[debug]C:\windows\system32\cmd.exe /c "C:\NPM\prefix\bower.cmd install"
> ##[command]C:\NPM\prefix\bower.cmd install
> 'C:\NPM\prefix\bower.cmd' is not recognized as an internal or external command,
> operable program or batch file.
> ##[error]Process completed with exit code 1.
> ##[debug]System.Exception: Process completed with exit code 1.
>    at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.ProcessHandler.RunAsync()
>    at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
>    at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
> ##[section]Finishing: Restore Bower Packages

**Comment by CKenrick** [comment]
I'm running into the same issue and haven't changed anything to the build pipeline since my last successful build.

**Comment by damccorm** [comment]
Hey @Chaouki-Tiouassiouine and @CKenrick sorry this slipped through the cracks - are you still experiencing this issue?
