### ISSUE TITLE
PublishTestResult: Publishing of test attachment fails for paths provided inside a container

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/azure-pipelines-tasks#11976]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults

## Environment
- Server - Azure Pipelines
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=10870&view=results

- Agent: Hosted
Linux 16.04

Used job: https://github.com/unoplatform/uno/blob/9e8ae0453d54f197cacac1731fedecf48a31221e/build/ci/.azure-devops-wasm-uitests.yml#L9

## Issue Description

When test results contain attachments, the paths used to publish the results do not take into account the path mapping provided to the container.

This makes all the attachments publish operations fail.

### Task logs
```
##[warning]File at /__w/1/a/screenshots/wasm-automated/RunRuntimeTests_SamplesApp_Samples_UnitTests_UnitTestsPage.png was not found
##[warning]Skipping attachment as it is not available on disk: /__w/1/a/screenshots/wasm-automated/RunRuntimeTests_SamplesApp_Samples_UnitTests_UnitTestsPage.png.
```

Note that the files really are available, as they are published through the `PublishBuildArtifacts` task.

**Comment by sahitiyerramilli** [comment]
Hey,
Sorry for the late reply. The build in the link you provided for the pipeline expired. Can you please provide us the correct link so that we can investigate further.

**Comment by jeromelaban** [comment]
No worries, here's a recent build: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=11368&view=results

**Comment by navin22** [comment]
@joaomoreno can you please try providing the searchFolder input. 
Similar issue #10072

**Comment by navin22** [comment]
@jeromelaban 
Currently people copy the results from containers to the agent machine or some shared folder and then try to run the Publish Test Results task from there. Or add a specific searchFolder input. Hope this helps. 

Let us know if you are still blocked.

**Comment by jeromelaban** [comment]
At this point, using `searchFolder` is a valid workaround, thank you!
