### ISSUE TITLE
Documentation on deploying a Container registry image to Kubernetes service

### ISSUE THREAD

**Issue by jeanpoelie** [microsoft/azure-pipelines-tasks#11971]
I am trying to find documentation on deploying a Container image to kubernetes services.
I hope to be able to use `Deploy to Kubernetes` but this tells me that the artifact should be a .yml and not a container repository.

**Comment by damccorm** [comment]
Hey @jeanpoelie  - this seems like its probably a better question for our docs repo - https://github.com/MicrosoftDocs/vsts-docs/issues. I'm going to close here, would you mind filing a bug there?

**Comment by jeanpoelie** [comment]
I agree, should have gone there immediatly!
