### ISSUE TITLE
Error: Endpoint auth data not present in Azure Resource Group Deployment task

### ISSUE THREAD

**Issue by cmielke** [microsoft/azure-pipelines-tasks#11984]
## Required Information

*Type*: Bug

**Enter Task Name**: Azure Resource Group Deployment

## Environment
- Server - Azure Pipelines 
    - account name: Emdat 
    - team project name: Emdat 
    - release definition name/number: _test_azure_cli (Release-21)

- Agent - Hosted: 
    - agent queue name: Azure Pipelines
    - agent specification: windows-2019

## Issue Description

When running the Azure Resource Group Deployment Task (v2 or v3-preview) with a Service Connection that is configured to use **certificate-based authentication**, I am getting the following error:
![image](https://user-images.githubusercontent.com/7267334/70942153-a866d380-2013-11ea-9326-8fa67bf74865.png)

This is a screenshot of the last success at 10:50 AM (Central Time). Notice the version of the task was v2.157.7:
![image](https://user-images.githubusercontent.com/7267334/70942497-67bb8a00-2014-11ea-9fc7-c02df7853da5.png)

The next release at 11:21 AM (Central Time) failed with the error. Notice that it was running v2.161.8 of the task:
![image](https://user-images.githubusercontent.com/7267334/70942570-8faaed80-2014-11ea-97c7-11506695bdd9.png)

Note that the task works fine if I use a Service Connection that is configured for secret-based authentication. This is our short term workaround. In the long run, I would like to use certificate-based authentication.

### Task logs

[ReleaseLogs_10178.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3970109/ReleaseLogs_10178.zip)

### Error logs

2019-12-16T20:48:26.7350586Z ##[error]Error: Task failed while initializing. Error: Endpoint auth data not present: b344ceed-dc46-4ca2-9d7a-3d6bd5b6ab88

**Comment by agupta-au** [comment]
We're experiencing this too and is impacting our release planning.

Any known workarounds? We don't have an option to fall back to shared secret

**Comment by vineetmimrot** [comment]
Thanks @cmielke & @agupta-au for reporting the issue, we will try to unblock you at earliest.

**Comment by mrsmitty** [comment]
I have a client that's also currently being impacted by this. @bishal-pdMSFT let me know if you require info from their ADO Org and pipelines.

**Comment by bishal-pdMSFT** [comment]
Ack. From preliminary investigation we seem to have identified the root cause. We will update once the fix is done and is starting rollout.

**Comment by segraef** [comment]
Same issue here but with self-hosted agents in connection with assigned managed identities in Azure.

![image](https://user-images.githubusercontent.com/19261257/71004000-bbe07000-20e1-11ea-8b9e-8eefea3aef06.png)

`Current agent version: '2.160.1'`

**Comment by IkePCampbell** [comment]
Same issue as @segraef, self-hosted agent with connection with assigned managed identity
![image](https://user-images.githubusercontent.com/39805870/71014281-51b2d580-20b7-11ea-916d-5190b3ebfd5e.png)
Current agent version: '3.1.9'

**Comment by segraef** [comment]
@IkePCampbell just fyi the mentioned version is the version of the ARM template deployment task, your agent version ca be seen at the agent pool or once the agent spins up in your pipeline.

![image](https://user-images.githubusercontent.com/19261257/71015027-36fe5200-20f3-11ea-8236-08df60f2d8c1.png)

**Comment by IkePCampbell** [comment]
@segraef Oh thank you! My bad, then my version is '2.163.1'

**Comment by agupta-au** [comment]
We've been recommended to use the v3.* (preview) version of the task. Will report back with findings once the build pipelines have been modified.

**Comment by cmielke** [comment]
I get the same error on v3.1.9 of the task.
![image](https://user-images.githubusercontent.com/7267334/71043214-83499200-20f3-11ea-8ec2-eecb778bfa98.png)

**Comment by agupta-au** [comment]
Same issue here!

> I get the same error on v3.1.9 of the task.
> ![image](https://user-images.githubusercontent.com/7267334/71043214-83499200-20f3-11ea-8ec2-eecb778bfa98.png)

**Comment by SupporterMan** [comment]
I have a customer also has this issue and they are unable to use Service Principal Key authorization in Service Connection to unblock them because they have many service principals, which will let them do lots of work to change their service connections.
Now they are blocked and all the pipelines using the service connection are unable to be executed.

Could you please provide an ETA about this?

**Comment by MarkAtAgilliance** [comment]
Also with 2.161.**8**.  We too are using MSI / self hosted build server.
![image](https://user-images.githubusercontent.com/35114634/71061897-097ace00-211e-11ea-9685-33a5ccef8ccb.png)

**Comment by vineetmimrot** [comment]
@All, the issue has been hotfixed. Let us know if you face any issues.

**Comment by IkePCampbell** [comment]
@vineetmimrot are there any settings we need to change?

**Comment by MarkAtAgilliance** [comment]
This hotfix succeeded for me.  Thank you :-) .

**Comment by cmielke** [comment]
It looks like the hotfix has resolved the issue for me. Thank you for the quick turnaround.

**Comment by agupta-au** [comment]
The issue is NOT resolved for us:

![image](https://user-images.githubusercontent.com/17844726/71127197-b64c6c80-223e-11ea-8762-cab599c737f1.png)

**Comment by agupta-au** [comment]
> It looks like the hotfix has resolved the issue for me. Thank you for the quick turnaround.

What version of the task do your logs show?

**Comment by cmielke** [comment]
> > It looks like the hotfix has resolved the issue for me. Thank you for the quick turnaround.
> 
> What version of the task do your logs show?

I am seeing v2.162.2
![image](https://user-images.githubusercontent.com/7267334/71133787-71362500-21c1-11ea-99b2-3082dba302e7.png)

**Comment by agupta-au** [comment]
2.162.1 for us.

**Comment by MarkAtAgilliance** [comment]
2.161.9 (which was successful).

**Comment by agupta-au** [comment]
Thanks @cmielke and @MarkAtAgilliance 

I guess our tenant just hasn't been upgraded as yet.

**Comment by agupta-au** [comment]
@vineetmimrot 

On 2.162.1 version of the Task (does not address issue), we are now using Service Principal Key for one of the deployments that is due for a release. We're now seeing a a multitude of warnings that were not present before in the Deploy pipelines. All of the warnings are _exactly_ the same: `##[warning]Can\'t find loc string for key: CorrelationIdForARM`

Anyone know if there's a way we can force our tenant to use the new version of the task?

**Comment by vineetmimrot** [comment]
@agupta-au can you please check now. The task is upgraded to 2.162.2.
