### ISSUE TITLE
[UseDotNet@2] which is the correct url to fetch the supported SDKs

### ISSUE THREAD

**Issue by juwens** [microsoft/azure-pipelines-tasks#11982]
`The supported SDKs is fetched from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json`

_Originally posted by @bishal-pdMSFT in https://github.com/microsoft/azure-pipelines-tasks/issues/11663#issuecomment-548228440_

According to his post it's: `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json`

But the url in the master-branch is: `https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases-index.json`

Source: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UseDotNetV2/versionfetcher.ts#L297

--

So i ask myself which is the currently correct url. And do we need to adjust the code?

**Comment by bishal-pdMSFT** [comment]
@juwens both the urls should be pointing to same content. @leecow is there a recommended one amongst the two urls?
