### ISSUE TITLE
DockerV2 buildAndPush command lacks arguments field

### ISSUE THREAD

**Issue by rakkhin** [microsoft/azure-pipelines-tasks#11981]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerV2

Title says it all. Both separate commands build and push for DockerV2 have arguments field but combined command buildAndPush lacks it, which makes it kind of useless in scenarios where you use Dockerfile ARGs to specify some values at build time. Not a big issue but an issue nonetheless.

**Comment by vithati** [comment]
@rakkhin , "BuildAndPush" command does both build and push. it is difficult to decide arguments belongs to which command. And this command is common scenarios where you don't need any parameters. This task supports "build" and "push" commands with arguments please use those commands if you want to specify arguments.
