### ISSUE TITLE
PublishPipelineArtifact should allow preserving symlinks

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/azure-pipelines-tasks#11980]
## Required Information
**Question, Bug, or Feature?** Bug/Feature

**Enter Task Name**: PublishPipelineArtifact

## Environment
- Server - Azure Pipelines
- Agent - Hosted 

## Issue Description
Publishing a directory with `PublishPipelineArtifact` that contains a symlink (to another file in under that target directory) does not preserve the symlink file. Instead the symlink is followed and a copy of the original file is included in the artifact instead.

This makes round tripping directories of artifacts using `PublishPipelineArtifact` and `DownloadPipelineArtifact` not possible if symlinks exist. If the file is particularly large in size, you end up with a bloated artifact as well!

**Comment by guillermomartinez-accenture** [comment]
@jahsu-MSFT may you inform what's the resolution of this request?

**Comment by jahsu-MSFT** [comment]
> @jahsu-MSFT may you inform what's the resolution of this request?

Adding @fadnavistanmay who's maintaining the PublishPipelineArtifact task - can you please help answer @guillermomartinez-accenture's inquiry?

**Comment by lvlie** [comment]
Should this be reopened? I'm facing the exact same issue. Have to resort to cleaning out the artifact before publish (strip out symlinks and duplicate stuff) or tar first (but dont want to need to untar before release, as its a big artifact). Both are not valid options imho and this really is a bug that should be fixed.

**Comment by tknerr** [comment]
Very same issue here - is there a workaround for that?

**Comment by jhakulin** [comment]
Is there a workaround or fix?

**Comment by csesek** [comment]
any updates ?

**Comment by tadavid-cae** [comment]
please reopen!!!!

**Comment by matthew-thomas** [comment]
This issue is also impacting me @jahsu-MSFT

**Comment by vishnugovind** [comment]
Is this issue fixed?

**Comment by PawanBagga27** [comment]
Getting Same issue. Please reopen the ticket.

**Comment by vishnugovind** [comment]
I think the only temporary solution is to zip up the artifact before publishing

**Comment by PawanBagga27** [comment]
Thanks Vishnu For your Response. However tried this way but while doing unzip artifact again same 
Error : -> Unable to load symbolic/hard linked file. Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.

As symbolic links will again look for actual pointed files which is not present. Is there any way to retain only symbolic links instead of they look for actual pointed files.

**Comment by vishnugovind** [comment]
Have you tried using a tar instead of zip? I think it should preserve symlinks. Also, it might be a OS platform/file system dependent

**Comment by wojtekmaj** [comment]
@jahsu-MSFT Would you please consider reopening it? It appears it has been closed by mistake or there has been a regression and multiple people are experiencing this problem. TIA!
