### ISSUE TITLE
PublishTestResultsV2: Introduce option to reduce logging verbosity

### ISSUE THREAD

**Issue by rmetzger** [microsoft/azure-pipelines-tasks#11993]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishTestResultsV2  

## Issue Description
As you can see in [this example](https://dev.azure.com/rmetzger/Flink/_build/results?buildId=3585&view=logs&j=821169f2-253d-577e-fcd2-77ed3c3937d9&t=428c25e8-0840-52a2-5aac-e4f460b57078), our builds are "polluted" with ~800 log messages from the `PublishTestResultsV2` task.
It would be nice to have a config flag to reduce the verbosity.
Example log messages: 
```
Only single test suite found, parsing its information.
Timestamp is not available for one or more testsuites. Total run duration is being calculated as the sum of time durations of detected testsuites.
```

The problem is that we are publishing the test results after the main build tasks. Engineers trying to debug build failures always need to reverse-scroll over the `PublishTestResultsV2` log messages.

**Comment by navin22** [comment]
This has been fixed in the latest release. Once this is rolled out will update you on this.
