### ISSUE TITLE
Expose -Timeout parameter for NugetCommandV2 task

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-tasks#11998]
## Task Affected

**Type**: Feature or Question

**Enter Task Name**: NugetCommandV2

## Environment
- Server - Azure Pipelines
    
    - can provide additional account, team project, build definition names using non-public means

- Agent - Hosted or Private: 

    - Private agent version 2.159.2 running on Windows 2016 Server

## Issue Description

Our connection to Azure Devops is throttled during busy periods and as a result, transfer rate is roughly 350KB/s causing our large Nuget packages to time out during publish to Azure Devops feeds. Is there a way to increase timeout to a value longer than the default 300 seconds? I looked at using custom command but I lose the Azure Devops feed picklist. How can I push one or more nuget packages in the staging artifact directory while specifying a timeout option and pushing to a specific Azure Devops feed from my build definition using the custom command type for this task? Modifying the task by exposing an optional Timeout input parameter with default value of 300 when command = push should fix this issue for me.

**Comment by jmyersmsft** [comment]
We as a team are in the process of deprecating our "kitchen sink" packaging tasks in favor of the "NuGet Authenticate" task and a script task you write yourself. My recommendation is therefore to use a script to just run `nuget push` directly with whatever options you like.

**Comment by tristanbarcelon** [comment]
Hi @jmyersmsft thank you for your feedback. I just looked at the nuget authenticate task and it doesn't seem to support azure devops feeds. When I select nuget feeds, I'm only seeing our internally-hosted nuget endpoints. This is the use case we are having issues with at the moment. We have no network issues pushing packages to internally-hosted nuget repos, only with repos that exist outside our network. Is there a plan to support azure devops nuget feeds? Are there workarounds you could suggest that utilize powershell or powershell core-based tasks?

**Comment by jmyersmsft** [comment]
Feeds in the same Azure DevOps organization as the build are handled automatically.

**Comment by tristanbarcelon** [comment]
Are you saying that I can skip the PAT textbox for such feeds?

**Comment by tristanbarcelon** [comment]
If I do write a custom task together in powershell that would perform the equivalent of nuget push with additional options, how can I reliably access the path to nuget.exe installed by Nuget Tool Installer task? Is there a convention for accessing "external tools" installed by pipelines agent?

**Comment by jmyersmsft** [comment]
The NuGet Authenticate task always sets up the credential provider to respond with the build's access token for any feeds in the same org. No service connection is required

I believe the NuGet Installer task will add the location of nuget.exe to the PATH in subsequent tasks, so just `nuget whatever blah blah blah` should work.

**Comment by jmyersmsft** [comment]
The NuGet Authenticate task automatically installs the credential provider if necessary

**Comment by tristanbarcelon** [comment]
Thanks @jmyersmsft . I will try this out and let you know how it goes.
