### ISSUE TITLE
Shell Task variables not propagated to following tasks?

### ISSUE THREAD

**Issue by andreacassioli** [microsoft/azure-pipelines-tasks#12009]
Hi,
I am sourcing variables from a text file in a shell task in a release pipeline using bash `source`.

The variables are correctly available in that shell tasks, but in the next, a replacement task, those variables are no more defined.

How could this be done? Notice that I do not know how many variables and their name, I would like to only rely on the text file (it is coming from my git repo).

**Comment by maxim-lobanov** [comment]
Hi, I think it is expected.
You should use something like `echo "##vso[task.setvariable variable=VarName]hello world"` to propagate variable to the next tasks.
Please see this [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cshell#set-a-job-scoped-variable-from-a-script-1) for reference.

**Comment by damccorm** [comment]
Closing since this is not an issue with tasks and Maxim is correct
