### ISSUE TITLE
DotNetCoreCLI restore command does not support Azure artifacts views

### ISSUE THREAD

**Issue by horihel** [microsoft/azure-pipelines-tasks#12005]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLIV2

## Issue Description

vstsFeed format is projectID/feedID
If you want to select a view in Azure Artifacts you'd need projectID/feedID@viewID

but this results in invalid XML in Nuget.config, eventually resulting in dotnet restore returning
``The '@' character, hexadecimal value 0x40, cannot be included in a name``

reason is that the task puts anything after the "/" into Feed.Name, because it expects only a GUID.

As far as I can see there is no possibility (currently) to use feedsToUse: 'select' and select a view in Azure Artifacts. You can only select the complete feed.

**Comment by DavidJFowler** [comment]
Hi @bishal-pdMSFT  Any response to this?

**Comment by horihel** [comment]
Just an update:
If you use feed: config this will also fail if you use the nuget.config XML as provided by azure artifacts web interface.

you need to remove the '@' from 'key' to make it work properly.

**Comment by bishal-pdMSFT** [comment]
Adding @shubham90 as this is related to nuget feeds

**Comment by shubham90** [comment]
Thanks @bishal-pdMSFT, Adding @phil-hodgson as he is the owner of this task
