### ISSUE TITLE
Unable to see attachments added to Test Case Results that have a 'Standard_Console_Output'.log

### ISSUE THREAD

**Issue by Konnor5092** [microsoft/azure-pipelines-tasks#12008]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: **Visual Studio Test (version 2)**

## Environment
- Server - Azure Pipelines or TFS on-premises?

**Azure Pipelines**
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

**Account name:** mattyoc.visualstudio.com
**Project name:** NewAttachmentsTest
**Build definition:** NewAttachmentsTest-ASP.NET-CI

- Agent - Hosted or Private: 
    
**Azure Pipelines -> windows-2019**

## Issue Description

When running a 'Visual Studio Test' task that outputs a 'Standard_Console_Output.log' (e.g. Console.WriteLine statements in your tests), you are unable to see any other attachments linked to that test case that were added via the azure devops api.

You can see that when you have this log file attached, the last api call made when browsing the test case is 'testlog?type=1' and 'Events'

![image](https://user-images.githubusercontent.com/18048889/71086430-d5d98b80-2191-11ea-8d2f-7548dc70932f.png)

Compare this to browsing a test case without a log file attached...

![image](https://user-images.githubusercontent.com/18048889/71086647-4c768900-2192-11ea-94d7-acaafb1fbe7d.png)

You can see the 'attachments' api call is made. Without this call being made in the first example above, any attachments you add via the api (e.g. POST https://mattyoc.visualstudio.com/NewAttachmentsTest/_apis/test/Runs/1000016/Results/100000/attachments?api-version=5.0-preview.1) are not displayed.

To replicate, setup a MSTest project that contains a few console.writeline statements like [here](https://github.com/Konnor5092/NewAttachmentsTest/blob/master/NUnitTestProject1/UnitTestProjectFramework/UnitTest1.cs) and add it to a build or release pipeline with the 'Visual Studio Test' task. Or you can clone my example project [here](https://github.com/Konnor5092/NewAttachmentsTest/blob/master/NUnitTestProject1/UnitTestProjectFramework/UnitTest1.cs)

Assuming you have access, you can browse the actual test case where the attachments aren't showing [here](https://mattyoc.visualstudio.com/NewAttachmentsTest/_testManagement/runs?runId=1000016&_a=resultSummary&resultId=100000)

Video replication is [here](https://streamable.com/7k6m3)

Note the 'Upload test attachments' option on the task makes no difference as to whether these log files are attached at runtime. I wouldn't mind this as a workaround but there is nothing to prevent them being added automatically. 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by navin22** [comment]
Hi @Konnor5092 we have compat issue here, and we are working on it. Let you guys know once it's fixed.

**Comment by navin22** [comment]
@Konnor5092 Please check if this issue is fixed now? I am closing this as the fix rolled out to all the regions. Please reopen if you still face the problem.

**Comment by Konnor5092** [comment]
@navin22 All sorted. Many thanks.

**Comment by necipblackkite** [comment]
We are facing with the same issue.

**Comment by neciptomurcuk-biz** [comment]
We are facing with the same issue again.
