### ISSUE TITLE
NuGetCommand - NuGet restore does not expose the PackageSaveMode command line parameter

### ISSUE THREAD

**Issue by tusharb86** [microsoft/azure-pipelines-tasks#12006]
## Required Information

*Type*: Feature or Question

**Enter Task Name**: NuGetCommand

## Environment
- Server - Azure Pipelines
    - Microsoft, Analog

## Issue Description

The NuGetCommand is missing functionality to set the `PackageSaveMode` command line parameter for `nuget restore` commands. Our team would like to set this parameter to `nuspec` to so that the .nupkg files are not saved after install. This saves a great deal of disk space which we are quite low on already with our dependencies and build.

Here is a link to the command line parameters for [`nuget restore`](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-restore) and here is the description of the parameter:

`PackageSaveMode | Specifies the types of files to save after package installation: one of nuspec, nupkg, or nuspec;nupkg.`

**Comment by herenhuang** [comment]
Hey @tusharb86 - we suggest using the [NugetAuthenticate task ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops)moving forward, and scripting for whatever else functionality you require. Let us know if you have any issues with it!
