### ISSUE TITLE
Fix table width in documentation

### ISSUE THREAD

**Issue by rerime** [microsoft/azure-pipelines-tasks#12017]
## BUG
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md

Please fix table width
![image](https://user-images.githubusercontent.com/7099570/71260013-e4b76e00-234a-11ea-9b9a-365def5984fe.png)

**Comment by damccorm** [comment]
Hey @rerime - could you be a little more specific on what is wrong with the table width? Its horizontally scrollable, it seems fine to me

**Comment by vtbassmatt** [comment]
That doc is no longer canonical for logging commands. See the official doc here: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash
