### ISSUE TITLE
VSTest is using deprecated task execution handler 

### ISSUE THREAD

**Issue by nasminou** [microsoft/azure-pipelines-tasks#12014]
**Question, Bug, or Feature?**  
*Type*: Bug I guess - deprecated code

**Enter Task Name**: VSTest  

## Environment
- Server - Azure Pipelines
- Agent - Hosted
    - If using Hosted agent, provide agent queue name: Pool: Hosted VS2017

## Issue Description
VSTest is using deprecated task execution handler.

See below the step yaml definition
```
  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
        **\*Rest*.dll
        !**\*TestAdapter.dll
        !**\obj\**
        **\*Test*.dll
      searchFolder: ...< path to test project folder> ... 
      pathtoCustomTestAdapters: Trunk/iPhone/packages/NUnitTestAdapter.2.1.1/tools
```

### Task logs

```
[section]Starting: VsTest - testAssemblies
==============================================================================
Task         : Visual Studio Test
Description  : Run tests with Visual Studio test runner
Version      : 1.0.96
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
[warning]Task 'VSTest' (1.0.96) is using deprecated task execution handler. 
The task should use the supported task-lib: https://aka.ms/tasklib
Preparing task execution handler.
Executing the powershell script: 
D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.96\VSTest.ps1
```

**Comment by ShreyasRmsft** [comment]
@nasminou please use major version 2 of the VsTest task.

Major version 1 is no longer recommended.

**Comment by nasminou** [comment]
Could you please tell me where I went wrong in using the v1 instead of v2 of the VsTest task? I thought ```VSTest@2``` meant that I was using version 2.

I can see that in the logs, the tasks says that it is version 1.0.96. But I can't find any documentation explaining how to select the version 2 of VsTest. 

I've also tried to create a new pipeline with a test task and the code is similar to the one I'm using in my normal pipeline and copied above.

Any help would be appreciated.

**Comment by ShreyasRmsft** [comment]
@nasminou maybe you pasted the wrong logs?

![image](https://user-images.githubusercontent.com/25194518/71652834-9b095300-2d4e-11ea-9d4c-6a3b667e08ce.png)
This does seem to indicate that you have selected major version 2
