### ISSUE TITLE
Azure CLI Task throws an error and doesnt do work but task completes succesfully 

### ISSUE THREAD

**Issue by alexatnext** [microsoft/azure-pipelines-tasks#12029]
Hi, when using the Azure CLI task i am getting the below error:

==============================================================================
Task : Azure CLI
Description : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/Powershell Core/Batch script when running on Windows agent.
Version : 2.0.4
Author : Microsoft Corporation
Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
(node:8400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'cleanUp' of undefined

This doesnt execute my script but does complete successfully.

**Comment by vineetmimrot** [comment]
@alexatnext Thanks for reporting the issue. We will start working on this soon.

**Comment by vineetmimrot** [comment]
@alexatnext  can you please send debug logs. You should set **System.Debug** variable with its value **true** in release definition.

**Comment by alexatnext** [comment]
Hello,

I could however i have diagnosed the issue to being when 'scriptType' variable is not set in yaml, is this sufficient information to reproduce? Therefore this is kind of user error, although i would still say the task should error if it doesnt have all required parameters?

Thanks,

Alex

**Comment by hiyadav** [comment]
We have made a fix for floating a proper error message when required inputs are missing
