### ISSUE TITLE
tfs:feed returns wrong endpointurl

### ISSUE THREAD

**Issue by renevanosnabrugge** [microsoft/azure-pipelines-tasks#12025]
Bug in TaskLib

**Enter Task Name**: TaskLib

## Environment
- Azure Pipelines on all agents

## Issue Description

I am using the endpoint tfs:feed in my extension https://github.com/renevanosnabrugge/vsts-promotepackage-task. The task uses gets the endpointurl to a feed, That endpoint url I also use in getting packages and release views. 
Since the introduction of Project Scoped feeds, the task does not return the project scoped feeds. I feel that the endpointurl should reflect the projectID as well.

https://github.com/microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/tfs-vsts-endpoints.md

Th issue of "my task"
renevanosnabrugge/vsts-promotepackage-task#38

**Comment by damccorm** [comment]
The task-lib is just pulling this from the environment, I believe this gets populated by the artifacts team and sent to the agent - routing to artifacts to take the first look. FWIW its not clear to me that this is behaving incorrectly, I'll defer to the artifacts team on that though

**Comment by jmyersmsft** [comment]
Organization-scoped feeds still exist, so we need the organization-level URL. Please see our built-in tasks in this repo for the way we handle the project vs collection issue.
