### ISSUE TITLE
Cannot set multiple docker tags from an output variable

### ISSUE THREAD

**Issue by autarch** [microsoft/azure-pipelines-tasks#12032]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug/Question

**Enter Task Name**: Docker@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

The fact that the Docker task takes tags as a *newline*-separated list makes
it very difficult to set these tags as an output variable (and maybe impossible).

For example, I can't do something like this:

```bash
TAGS=$( cat tags_file )
echo "##vso[task.setVariable variable=base_image_tags;isOutput=true]$BASE_IMAGE_TAGS"
```

AFAICT whatever part of the pipelines system handles these `##vso` log lines simply ignores everything after the first line of output. That makes sense, of course, since none of the lines after the first have the proper prefix.

All of this would be _greatly_ simplified if the tags could be accepted with a different delimiter like `|` or `,`.

I think I've found a workaround for my case, but it only works because I know I'll always have exactly 1 or 2 tags. If my tag list could be an arbitrary length I don't think there would be any viable solution.

**Comment by ds-ms** [comment]
This has been fixed here: https://github.com/microsoft/azure-pipelines-tasks/pull/12765
