### ISSUE TITLE
Cache@2: Inability to discard tar output (-v flag)

### ISSUE THREAD

**Issue by toqueteos** [microsoft/azure-pipelines-tasks#12046]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: `Cache@2` [link](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheV2)

## Environment
- Server - Azure Pipelines [link](https://dev.azure.com/payvision/Warriors/_build/results?buildId=334370&view=logs&j=0b109914-fd3b-548c-e58c-f9d47cb04f5f&t=e8109a5d-54b1-57e5-952c-9dec9387f8ee)
- Agent - Hosted `ubuntu-18.04`

## Issue Description

![image](https://user-images.githubusercontent.com/699969/71513431-a0702480-289a-11ea-925d-ff516efd1e7a.png)

As you can see in the attached image, `system.debug=true` shows the underlying command (`tar` with `-v`).

There is no way for `Cache@2` task users to omit the log of all files inside the cached blob. This for JS projects tends to be a never ending list of things inside `node_modules`

**Could you please provide a flag, checkbox or something to skip the output?** That's a bazillion log lines that would be skipped and potentially a nice speedup in the task execution time.

**Comment by toqueteos** [comment]
This issue might be related to #8496

**Comment by fadnavistanmay** [comment]
Hi,

Since we only show the output when system.debug=true, we have decided to keep the functionality as is.
