### ISSUE TITLE
ServiceFabricDeploy task fails with error "Every node service should not has affinity."

### ISSUE THREAD

**Issue by zendu** [microsoft/azure-pipelines-tasks#12048]
**Question**  
Mysterious error:

Every node service should not has affinity.
FileName: ApplicationManifest.xml

**Enter Task Name**: ServiceFabricDeployV1 (Service Fabric application deployment)

## Environment
- Server - Azure Pipelines
- Agent - Private

Agent.OS | Windows_NT
Agent.OSArchitecture | X64
Agent.OSVersion | 10.0.14393
Agent.Version | 2.163.1

**Comment by hiyadav** [comment]
Hey, can you explain the error in more detail. Would help us greatly if you can share debug logs of the task.

**Comment by zendu** [comment]
It's a release pipeline, so there are no debug logs. This is the only error line in the log. I opened issue because there is no additional detail.

**Comment by hiyadav** [comment]
@zendu by the looks of it, this error seems to be coming from Service Fabric Cluster itself and not something the task is generating. 

Is there some extra information available in Cluster's dashboard ? If no, i would suggest to open a query on Service Fabric team...

**Comment by bishal-pdMSFT** [comment]
@zendu this could be related to some problematic service affinity defined in ApplicationManifest.xml. https://github.com/Huachao/azure-content/blob/master/articles/service-fabric/service-fabric-resource-balancer-service-description.md#service-affinity

**Comment by hiyadav** [comment]
@zendu I'm closing this issue assuming you will be able to unearth the problem from Service Fabric cluster logs and by Bishal's pointer. You can open again if otherwise

**Comment by zendu** [comment]
Apparently, I had 2 applications on service fabric; both with instance count -1 and one had affinity configured. These are, of course, conflicting settings. But the error message threw me off.
