### ISSUE TITLE
Code coverage report in Azure DevOps

### ISSUE THREAD

**Issue by mariopena77** [microsoft/azure-pipelines-tasks#12052]
## Required Information
*Type*: Bug
**Enter Task Name**: Publish code coverage results (PublishCodeCoverageResultsV1)

## Environment
- Server: Azure Pipelines

- Agent - Hosted or Private: Not sure
    
## Issue Description

I've seen this issue in others threads, but still have the problem, and I've seen in some of them that the feature is in the backlog, I'm a little bit confused.

I want to see a code coverage report in my pipeline. The Code Coverage tab is created, but all I see is a link to download the .coverage file:

![image](https://user-images.githubusercontent.com/40646294/71601061-d40fb080-2b1f-11ea-843f-969604ffbb90.png)

I have these tasks in the pipeline:

![image](https://user-images.githubusercontent.com/40646294/71601134-23ee7780-2b20-11ea-8a9f-16f643774eea.png)

This is the configuration for each one of the showed tasks:

dotnet test:
![image](https://user-images.githubusercontent.com/40646294/71601159-4bdddb00-2b20-11ea-92ff-3dc159242c87.png)

ReportGenerator:
![image](https://user-images.githubusercontent.com/40646294/71601176-5ef0ab00-2b20-11ea-93ac-8bb3b7421583.png)

Publish code coverage results:
![image](https://user-images.githubusercontent.com/40646294/71601194-7465d500-2b20-11ea-9324-365b5f8f9151.png)

After the execution of the pipeline, I can see the .html file in the artifact explorer:
![image](https://user-images.githubusercontent.com/40646294/71601465-88f69d00-2b21-11ea-9e88-72f084b69f8a.png)

### Task logs
Logs of the Publish code coverage reuslts task:
![image](https://user-images.githubusercontent.com/40646294/71601336-0372ed00-2b21-11ea-8c61-aae9592dd0e0.png)

Thanks in advance!

**Comment by anshii03** [comment]
@mariopena77 For html view , we are soon going to roll out this view:

![image](https://user-images.githubusercontent.com/9054199/71873467-40546a80-3145-11ea-8c51-96b42eb9a17f.png)

![image](https://user-images.githubusercontent.com/9054199/71873676-c83a7480-3145-11ea-8667-53d2f6822e2e.png)

If you are interested in this , we will enable this on your account in couple of days.
You can try this and give us further feedback.

**Comment by anshii03** [comment]
@mariopena77  Currently , we don't support .coverage format to parse in report generator.

**Comment by mariopena77** [comment]
Thanks @anshii03 , I'll try converting to xml format :)
