### ISSUE TITLE
Warnings "Can't find loc string for key: Info_ResolvedToolFromCache" and "Can't find loc string for key: Info_UsingVersion"

### ISSUE THREAD

**Issue by henry-padilla** [microsoft/azure-pipelines-tasks#12051]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Question

**Enter Task Name**: NuGetInstaller@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - Account name: wkaxcess
    - Team project name: Axcess
    - Build definition name/build number: buildId=127788

- Agent - Hosted
    
    - windows-2019

## Issue Description
I am getting the following warnings when I use this task:
##[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache
##[warning]Can\'t find loc string for key: Info_UsingVersion

### Task logs

[logs_127788.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4010327/logs_127788.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

2019-12-30T15:42:03.3041067Z ##[section]Starting: NuGet restore **/*.sln
2019-12-30T15:42:03.3164181Z ==============================================================================
2019-12-30T15:42:03.3164258Z Task         : NuGet Installer
2019-12-30T15:42:03.3164292Z Description  : Installs or restores missing NuGet packages
2019-12-30T15:42:03.3164326Z Version      : 0.144.0
2019-12-30T15:42:03.3164399Z Author       : Microsoft Corporation
2019-12-30T15:42:03.3164431Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
2019-12-30T15:42:03.3164465Z ==============================================================================
2019-12-30T15:42:04.3920812Z SYSTEMVSSCONNECTION exists true
2019-12-30T15:42:04.6242920Z SYSTEMVSSCONNECTION exists true
2019-12-30T15:42:04.7095888Z [command]C:\windows\system32\chcp.com 65001
2019-12-30T15:42:04.7205499Z Active code page: 65001
2019-12-30T15:42:06.1532558Z Caching tool: NuGet 4.0.0 x64
2019-12-30T15:42:06.1636694Z Found tool in cache: NuGet 4.0.0 x64
2019-12-30T15:42:06.1902902Z ##[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache
2019-12-30T15:42:06.1911894Z Info_ResolvedToolFromCache 4.0.0
2019-12-30T15:42:06.1912453Z ##[warning]Can\'t find loc string for key: Info_UsingVersion
2019-12-30T15:42:06.1912812Z Info_UsingVersion 4.0.0
2019-12-30T15:42:06.1914350Z Found tool in cache: NuGet 4.0.0 x64
2019-12-30T15:42:06.2324780Z Detected NuGet version 4.0.0.2283 / 4.0.0
2019-12-30T15:42:06.2334786Z SYSTEMVSSCONNECTION exists true

**Comment by smg-bg** [comment]
Any updates about this? We are getting the same warnings on an agent installed on Windows machine.

**Comment by doormalena** [comment]
Same issue here on the [DownloadPackage](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-package) task.

```
==============================================================================
Task         : Download package
Description  : Download a package from a package management feed in Azure Artifacts
Version      : 1.164.0
Author       : ms-vscs-rm
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-package
==============================================================================
SYSTEMVSSCONNECTION exists true
Found tool in cache: artifacttool 0.2.128 x64
##[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache
Downloading package: <package_name>, version: * using feed id: <id>, project: null
```

**Comment by FrancescElies** [comment]
Could this be related/similar to #11588?

**Comment by FrancescElies** [comment]
It seems to me very similar to me [task.loc.json](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadPackageV1/task.loc.json) has no `Info_ResolvedToolFromCache`

![image](https://user-images.githubusercontent.com/6558089/76834200-054d7200-682d-11ea-8a5e-90ab43acb8fb.png)

**Comment by lindhe** [comment]
I've got the same issue. Did you do something to make it work?

**Comment by erikthysell** [comment]
Same issue here... I get
##[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache
##[warning]Can\'t find loc string for key: Info_UsingVersion
##[warning]Can\'t find loc string for key: Info_UsingToolPath

when running this task:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0.103'
  inputs:
    packageType: 'sdk'
    version: '5.0.103'
    includePreviewVersions: true

**Comment by dmcweeney** [comment]
Still happening with the NugetInstaller task on windows-latest hosted agent!

```
- task: NuGetInstaller@0
  displayName: 'Install nuget packages'
  inputs:
    solution: '**/*.sln'
    restoreMode: 'restore'
    nuGetVersion: '4.0.0.2283'
    verbosity: Detailed
```

```
Active code page: 65001
Caching tool: NuGet 4.0.0 x64
Found tool in cache: NuGet 4.0.0 x64
##[warning]Can't find loc string for key: Info_ResolvedToolFromCache
Info_ResolvedToolFromCache 4.0.0
##[warning]Can't find loc string for key: Info_UsingVersion
Info_UsingVersion 4.0.0
Found tool in cache: NuGet 4.0.0 x64
Detected NuGet version 4.0.0.2283 / 4.0.0
```

Is this still not fixed or do I need to do something different?

**Comment by dbhaigh** [comment]
I'm having a similar problem with the NPM@1 task - the version number has recently incremented from 1.238.3 to 1.241.1, and when it did?  I started getting these warnings "##[warning]Can't find loc string for key: Info_GotAndMaskAuth" showing up

I believe they are related to "SYSTEMVSSCONNECTION exists true" which immediately precedes each warning in the log

Should I be concerned about these warnings?  Or are they just noise? And is there any way of setting the version number back to 1.238.3?  That version didn't generate these warnings

Cheers

-=A=-

.

**Comment by inri13666** [comment]
same issue

**Comment by jmyersmsft** [comment]
Please open a new issue for new issues. While similar, these new warnings are unrelated to this ticket. The warnings themselves are harmless (aside from appearing in your logs, of course). They most likely indicate that we misspelled the name of a message we intended to display. Based on the name, I think the message is likely only informational.

**Comment by jmyersmsft** [comment]
Filed #20120 for the new issue

**Comment by Aaqibshaikh20** [comment]
**##[warning]Can't find loc string for key: Info_GotAndMaskAuth**   how to reslove this issue. When I run my cicd pipeline then I got this error again and again. Anyone can help me how to resolve this issue.
