### ISSUE TITLE
Does not update all files correctly on zip Azure App Service deploy   

### ISSUE THREAD

**Issue by goriunov** [microsoft/azure-pipelines-tasks#12056]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy   

list here (V# not needed): 4 and 3 (tested both)
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

## Issue Description

Currently we have Azure App Service deploy step where we deploy zip file with whole Node.js application including `node_modules` on Windows Web App, we have noticed that sometimes it does not update/deploy some files correctly (not sure reasons), after deploy if i navigate through kudu in to the node_modules i see the last update date for files is 26/10/1985, 20:15:00 (not sure if that related) and some files are not updated to the latest zipped version. So it is possible to get situation where `package.json` in one if the `node_modules` has been updated but actual execution files are not, which could cause allot of issues especially with patch releases as there is no way to verify it without going in to kudu.

I have confirmed that zip file contains correct node_modules so it is not and issue with build or zip.

**Comment by Roshan-Kumar-Microsoft** [comment]
@goriunov Can you please share the debug log to RM_Customer_Queries@microsoft.com

**Comment by eaarora-ms** [comment]
@goriunov  Can you confirm if you are using ms deploy or zip deploy for the task?

**Comment by goriunov** [comment]
@eaarora-ms sorry for late reply, `Deployment method` specified as `Zip Deploy`.

**Comment by eaarora-ms** [comment]
@goriunov If you are still facing this issue, can you please set the variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries at microsoft dot com

**Comment by eaarora-ms** [comment]
@goriunov  Please share the debug logs to help us identify the problem. Thanks!

**Comment by eaarora-ms** [comment]
Closing due to no response from the customer. Please comment to re-open.

**Comment by FrancescoBonizzi** [comment]
Same problem here.
