### ISSUE TITLE
Issue with code coverage and multi-module project build in Azure DevOps

### ISSUE THREAD

**Issue by sheikahamed** [microsoft/azure-pipelines-tasks#12067]
In Azure Devops Maven build pipeline, while building multi-module java project, the build was successful. However, the Jacoco code coverage is failing with below error,

 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project VstsReport: An Ant BuildException has occured: Unable to read execution data file /vsts/agent/_work/8/s/CCReport43F6D5EF/jacoco.exec
2020-01-02T22:17:12.5100407Z [ERROR] around Ant part ...<report>... @ 8:11 in /vsts/agent/_work/8/s/target/antrun/build-main.xml: /vsts/agent/_work/8/s/CCReport43F6D5EF/jacoco.exec (No such file or directory)

Azure pipeline yml file has the following task parameters,

 - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'
      options: '--settings settings.xml'
      **codeCoverageToolOption: JaCoCo
      codeCoverageSourceDirectories: epubcheck-service/src/main,epubcheck-service/src/test
      codeCoverageClassFilesDirectories: epubcheck-service/target/classes,epubcheck-service/target/test-classes**
      sonarQubeRunAnalysis: true

If I comment the codeCoverage parameters then the Maven build task completes successfully. Only when I add the codeCoverage parameters on a multi-module project, I am getting the above-mentioned error. 

Can somebody who used Azure DevOps pipeline for building Java maven build and Jacoco code coverage tool help me?

**Comment by P1ll3P4ll3** [comment]
Hello,
same problem here.

I´m also using the Jacoco Maven Plugin to generate the reports in a multi-module project. 3 different reports are generated: Unit Tests, Integration Tests and the third one that aggregates all of them.

So as a workaround I tried to use the Publish Code Coverage Task. This works but it is not possible to specify multiple source directories for the multi-module project for the Publish Coverage Results task.

Thanks and best regards,
Philippe

**Comment by P1ll3P4ll3** [comment]
I solved the issue by specifying exclusions, class and source folder.

**Comment by tsaibabu4u** [comment]
> I solved the issue by specifying exclusions, class and source folder.

can you be more specific about exclusion ? what code snippet added ?

**Comment by P1ll3P4ll3** [comment]
This is the statement codeCoverageClassFilter: '' for the Maven Task.

codeCoverageClassFilter: '-:**/xyz/*+:**/abc/*'

You can specify inclusions with +: and exclusions with -:

If you select the Maven task out of your build pipeline, this is described there.

**Comment by PriGitPro** [comment]
I encountered similar issue with Gradle task, managed to do a workaround by putting .exec in 'CCReport43F6D5EF' directory which seems to be hardcoded but there is no way to configure it perhaps.

**Comment by Xoib** [comment]
@PriGitPro in your case it is possible. But when using the Maven task itself and enabling Jacoco, it is not possible.
Any other idea to fix this hard coded CCReport43F6D5EF path?

**Comment by tsaibabu4u** [comment]
in my case, I did this way

plugin in pom.xml

<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${jacoco.version}</version>
				<executions>
					<execution>
						<id>pre-unit-test</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					
					<execution>
						<id>post-unit-test</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							
							<dataFile>target/jacoco.exec</dataFile>
							
							<outputDirectory>target/jacoco-ut</outputDirectory>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<systemPropertyVariables>
						<jacoco-agent.destfile>target/jacoco.exec</jacoco-agent.destfile>
					</systemPropertyVariables>
				</configuration>
			</plugin>

and in maven plugin just added this one

codeCoverageClassFilesDirectories: module1/target/classes,module2/target/classes

and I am able to see the results in azure UI

**Comment by Xoib** [comment]
Hello @tsaibabu4u ; Would it be possible to connect with me?

**Comment by tsaibabu4u** [comment]
> Hello @tsaibabu4u ; Would it be possible to connect with me?
> I tried your solution but I still get the exact same error with the hard coded path :
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project VstsReport: An Ant BuildException has occured: Unable to read execution data file /home/vsts/work/1/s/CCReport43F6D5EF/jacoco.exec
> [ERROR] around Ant part ...<report>... @ 8:11 in /home/vsts/work/1/s/target/antrun/build-main.xml: /home/vsts/work/1/s/CCReport43F6D5EF/jacoco.exec (No such file or directory)
> ```

Interesting... Sure . Let me know how to connect and when .

**Comment by Xoib** [comment]
> > Hello @tsaibabu4u ; Would it be possible to connect with me?
> > I tried your solution but I still get the exact same error with the hard coded path :
> > ```
> > [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project VstsReport: An Ant BuildException has occured: Unable to read execution data file /home/vsts/work/1/s/CCReport43F6D5EF/jacoco.exec
> > [ERROR] around Ant part ...<report>... @ 8:11 in /home/vsts/work/1/s/target/antrun/build-main.xml: /home/vsts/work/1/s/CCReport43F6D5EF/jacoco.exec (No such file or directory)
> > ```
> 
> Interesting... Sure . Let me know how to connect and when .

Well we can't private message here and your nickname doesn't match on twitter. Can you PM me @Xoib anywhere so we can go from there?

**Comment by ArunKaarthick** [comment]
Hi...I am facing a similar issue as like this: /vsts/agent/_work/8/s/target/antrun/build-main.xml: /vsts/agent/_work/8/s/CCReport43F6D5EF/jacoco.exec (No such file or directory)......
kindly let me know whether any solution has been provided for it

**Comment by Xoib** [comment]
> 
> 
> Hi...I am facing a similar issue as like this: /vsts/agent/_work/8/s/target/antrun/build-main.xml: /vsts/agent/_work/8/s/CCReport43F6D5EF/jacoco.exec (No such file or directory)......
> kindly let me know whether any solution has been provided for it

Hi @ArunKaarthick , I am in the same situation. I was hopping for @tsaibabu4u to contact me so we can work things out directly.

**Comment by kiranallari** [comment]
I am also facing same issue. though we provide coverage path it always searches in hard coded folder.
I resolved it by putting hard coded path in pom.xml. It is a workaround.		<sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/CCReport43F6D5EF/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>

**Comment by deepaleekhare31** [comment]
Hello @tsaibabu4u ,
i tried your solution, but i'm getting the below error:
**Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project VstsReport: An Ant BuildException has occured: Unable to read execution data file /home/azadmin/myagent/_work/1/s/CCReport43F6D5EF/jacoco.exec
2020-08-06T12:33:46.2947704Z [ERROR] around Ant part ...<report>... @ 8:11 in /home/azadmin/myagent/_work/1/s/target/antrun/build-main.xml: /home/azadmin/myagent/_work/1/s/CCReport43F6D5EF/jacoco.exec (No such file or directory)**

Let me know your solution.

**Comment by mudit000** [comment]
i am also facing same issue

2020-08-13T07:33:09.7295185Z [INFO] ------------------------------------------------------------------------
2020-08-13T07:33:09.7799700Z Reading code coverage summary from '/home/vsts/work/1/s/<>/CCReport43F6D5EF/jacoco.xml'
2020-08-13T07:33:10.3093538Z ##[error]Build failed.

**Comment by zziga** [comment]
The Maven task injects stuff into pom.xml for jacoco 'prepare-agent' goal. For jacoco 'report' goal, it will generate another pom.xml, on the fly, triggering report generation via ant. 

The enriched pom.xml, adds 'append' and sets path to CCReport43F6D5EF, auto-generated pom.xml and resulting ant xml we can _cat_ in separate task (script).

@sheikahamed Good starting point is a maven project without any jacoco configuration in pom.xml. Just `codeCoverageToolOption: JaCoCo` and no other `codeCoverage*` settings. Adding any jacoco configuration into the pom.xml can easily mislead you.

**Comment by DaniilShmelev** [comment]
Hello @sheikahamed, could you please provide your pom.xml?

**Comment by DaniilShmelev** [comment]
The customer seems to be inactive, so I'm going to try to give everyone the best solution I could find.
@zziga's last response is correct: maven injects jacoco configuration into pom.xml, which means you mustn't do it yourself. This behavior doesn't seem to be documented anywhere, so I'm going to prepare some documentation changes for MS docs regarding this task.

**Comment by zziga** [comment]
@DaniilShmelev Many thanks for the follow up! 

Maybe also worth mentioning in here or in a separate issue: 
- **codeCoverageToolOption: JaCoCo** also injects **clean** to task **goals**. That is documented. But unfortunately mandatory. While it is safer choice, it does not allow reuse of already existing ./target directory. Pipelines with multiple maven tasks can end up compile, test, package _twice_. 
- JaCoCo version is pre-defined to older 0.8.4 and can not be overwritten - I've missed that in documentation. 
- Coverage report won't display JaCoCo graphs. There's an issue with rendering of red/green bar gifs from ../jacoco-resources/redbar.gif in the iframe with the report, which is crucial for visual representation of coverage.

**Comment by DaniilShmelev** [comment]
Good points @zziga, do you mind opening a new issue?

**Comment by marcoadasilvaa** [comment]
+1

**Comment by hhovhann** [comment]
> codeCoverageClassFilesDirectories

I think in azure you can see the UI even without pom.xml changes because there is a built-in 0.8.4. version.
Can you confirm that your UI is also including all resources icons properly or you have broken icons as well?
