### ISSUE TITLE
HelmDeploy should support Helm v3

### ISSUE THREAD

**Issue by jheyduk** [microsoft/azure-pipelines-tasks#12068]
*Type*: Bug

**Enter Task Name**: HelmDeploy

## Issue Description

HelmDeploy-Task not working with helm v3.0.x

### Error logs

/workspace/_tool/helm/3.0.2/x64/linux-amd64/helm install --namespace cidocs --name cidocs --wait /workspace/13/drop/cidocs-1033.tgz
Error: unknown flag: --name
##[error]Error: unknown flag: --name

**Comment by jheyduk** [comment]
workaround: use `helm upgrade --install`

**Comment by shigupt202** [comment]
The issue has been fixed in this PR: [https://github.com/microsoft/azure-pipelines-tasks/pull/12080](url)
