### ISSUE TITLE
VSTestV2 Outdated documentation

### ISSUE THREAD

**Issue by JeremyCaney** [microsoft/azure-pipelines-tasks#12075]
## Required Information
**Type**: *Bug*
**Enter Task Name**: `VSTest`

## Environment
- Server - Azure Pipelines
- Agent - Hosted 

## Issue Description

The information icon for the _Other console options_ currently points to:

[`https://aka.ms/vstestotherconsoleoptions`](https://aka.ms/vstestotherconsoleoptions)

Which redirects to the documentation for **Visual Studio 14.0**:

[`https://docs.microsoft.com/en-us/previous-versions/jj155796(v=vs.140)?redirectedfrom=MSDN`](https://docs.microsoft.com/en-us/previous-versions/jj155796(v=vs.140)?redirectedfrom=MSDN)

Which appropriately warns readers:

>  We're no longer updating this content regularly. Check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported.

The latest link for this documentation is at:

[`https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019`](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019)

Preferably, the `vstestotherconsoleoptions` short-link should be updated directly in case any other projects are using it. At minimum, though, the `resources.resjson` files on the `VSTestV2` task should be updated to include the correct link.

**Comment by JeremyCaney** [comment]
**Note:** My original report included references to the documentation for the `/Framework:` parameter, as I was under the incorrect impression that this was required to test **.NET Core** assemblies. And while the documentation for that parameter, specifically, does not provide information on how to target a **.NET Core** assembly, it turns out that requirement was an off-target effect of a bug in my own configuration. As such, I've removed those references. That said, regardless, the documentation still links to outdated information, so that should probably be updated.

**Comment by ShreyasRmsft** [comment]
@JeremyCaney thanks for reporting this. We will take this up soon.

**Comment by PBoraMSFT** [comment]
@JeremyCaney - this is fixed.
