### ISSUE TITLE
Command Line Task running an executable kills the agent in the middle of the output

### ISSUE THREAD

**Issue by alexleonovhs1** [microsoft/azure-pipelines-tasks#12077]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CmdLine

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/henryscheinone/Conversions/_build/results?buildId=37545&view=results

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10 Pro 1909, agent 2.164.0 (previous agent versions also had this problem)

## Issue Description

There is a step in the pipeline that runs an executable built earlier in the pipeline. It is a simple `<executable name> <single parameter>` and has a specific working directory. 

The run always starts okay, and you can start seeing the output, but then at some point (sometimes, 30 sec, sometimes a minute - different every time) the output stops and the agent dies. Then the pipeline waits for ~10 minutes and fails due to the agent not communicating with the server.

The agent runs as a service. I have switched it to interactive mode to see if it outputs anything interesting, but it simply quits back to command line.

The executable can be run manually from the command line and always finishes successfully. It does not require any interactive input.

### Task logs

- _diag logs attached
- also, attached a task output sample (from _pages) - which stops mid-line

[agent.dies.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4024333/agent.dies.zip)

**Comment by jtpetty** [comment]
@alexleonovhs1 - Looking at the logs you sent, the Agent.log is from after the agent is restarted. Do you have the agent log from the instance of the agent that ran when the worker crashed?

Is it possible that the binary that is being run is consuming a lot of memory and something is auto killing that process on your private agent?

**Comment by alexleonovhs1** [comment]
@jtpetty here's the log from the previous run; will restart the thing again and watch for the memory now

[Agent_20200106-000452-utc.log](https://github.com/microsoft/azure-pipelines-tasks/files/4027694/Agent_20200106-000452-utc.log)

**Comment by alexleonovhs1** [comment]
@jtpetty no visible spikes of memory or CPU usage: was up to ~40MB mem and 10% CPU, with plenty free on the host

**Comment by jtpetty** [comment]
@alexleonovhs1 - Looking at the logs, it looks like something external to the agent is killing the agent process tree.

Is it always the 'Run the conversion' step that gets killed?

Is there anything in the system log on the machine?

**Comment by alexleonovhs1** [comment]
> Is it always the 'Run the conversion' step that gets killed?

Yes.

> Is there anything in the system log on the machine?

Here you go:

# Application Log

Two consecutive records:
- VstsAgentService, 2020-01-06 20:36:01Z: Running job: AUExactToAscend
- VstsAgentService, Service started successfully.

# System Log

- The Azure Pipelines Agent (henryscheinone.Conversions Pool.AKDCONVERSIONS_01) service terminated unexpectedly.  It has done this 4 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service.

# Security Log

_Cannot see anything meaningful; the only line that might be interesting is below_

- A privileged service was called. 

```Service:
	Server:	Security
	Service Name:	-

Process:
	Process ID:	0x3cc8
	Process Name:	C:\Windows\System32\wbem\WmiPrvSE.exe

Service Request Information:
	Privileges:		SeProfileSingleProcessPrivilege
```

**Comment by alexleonovhs1** [comment]
@jtpetty I'll try https://docs.microsoft.com/en-nz/archive/blogs/supportingwindows/what-killed-my-process to see if it yields anything interesting

**Comment by alexleonovhs1** [comment]
@jtpetty it was an antivirus gone rogue; let me run the pipeline again and see if all is fine

**Comment by alexleonovhs1** [comment]
Thank you very much for your help and pointing me in the right direction!

If anyone stumbles upon a similar problem, this also helped: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit?redirectedfrom=MSDN

**Comment by jtpetty** [comment]
@alexleonovhs1 - Awesome! I am glad you were able to track down the issue. Thank you for sharing your approach!
