### ISSUE TITLE
Styling is omitted in Code Coverage preview even though it is included in the published report

### ISSUE THREAD

**Issue by boyanio** [microsoft/azure-pipelines-tasks#12071]
## Required Information
 
*Type*: Bug
**Enter Task Name**: PublishCodeCoverageResults@1

## Environment
- Server - Azure Pipelines
- Agent - Private
  - Linux

## Issue Description

We are generating a HTML code coverage report and publishing it using the PublishCodeCoverageResults@1task. The publishing itself works fine and the report can be downloaded from the build artifacts. However, having the `Multi-stage pipelines feature` enabled on the code coverage tab, the styling is missing.

![image](https://user-images.githubusercontent.com/980463/71712461-fa7a6800-2e0d-11ea-97c6-6f4e767bd158.png)

If I download the report from the build artifacts and open the `index.html` file, it looks much better

![image](https://user-images.githubusercontent.com/980463/71712509-2d246080-2e0e-11ea-8628-65c105996031.png)

**Comment by ShreyasRmsft** [comment]
The server strips all css and javascript from the uploaded html reports before rendering them. You need to provide a jacoco or cobertura report file (not html) to the publish code coverage task and it internally uses report generator to generate an html report without css or js and by only using inline styles.
