### ISSUE TITLE
Function app is not listing when i used the Service connection type "Publish profile based authentication"

### ISSUE THREAD

**Issue by anoopk-kr** [microsoft/azure-pipelines-tasks#12076]
I have created a Service connection of type "Publish profile based authentication" for deploying my App into Function app. 

When adding the task into my pilne, it no more list the App name  when i select this connection type. 

I am able to get the app listed when i use the service connection type "Azurerm resource manager with service principle based". Does this plugin has any such limitations due to which the app is not listed with the service connection type "Publish profile based"? Please advise

**Comment by chperich** [comment]
@anoopk-kr : Service connection of type "Publish profile based authentication" does not have enough permissions to be able to list out the App names. That was primarily meant to be used in a YAML based work flow.

You can either choose to use a service connection of type"AzureRM resource manager" (or) switch to YAML based pipeline if you intend to use service connection of type "Publish profile based authentication".
