### ISSUE TITLE
Portable PDB support?

### ISSUE THREAD

**Issue by Sean-Driscoll** [microsoft/azure-pipelines-tasks#12074]
Does the [Index Sources & Publish Symbols task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops) publishing to Azure Artifacts/DevOps support portable PDBs?

Recent answers from @fadnavistanmay [here](https://github.com/microsoft/azure-pipelines-tasks/issues/6119#issuecomment-524441635) and @mitchdenny [here](https://github.com/microsoft/azure-pipelines-tasks/issues/5039#issuecomment-462229144) seem to indicate yes. But I've seen people continue to report issues.

**Comment by mitchdenny** [comment]
The way to do this is to disable indexing of the symbols in the task, and instead use [source link](https://github.com/dotnet/sourcelink) to do the indexing of sources during the build itself. Then the task just uploads the PDBs as they are. The task will produce a warning.

That is how I've made it work in the past ... YMMV.

**Comment by Sean-Driscoll** [comment]
Thanks @mitchdenny! So to confirm, that task _should_ work for publishing full or portable PDBs to the Azure Artifacts symbol server?

**Comment by mitchdenny** [comment]
Correct. The task does two things. It indexes symbols, and publishes symbols. If it can't index the symbols (because it doesn't understand portable PDBs) it can still upload them.

**Comment by Sean-Driscoll** [comment]
My concern over whether portable PDBs are supported comes from the github doc [here](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md#tools-that-require-windows-pdbs), which indicates Microsoft symbol server does not support portable PDBs, which I assumed included the Azure DevOps symbol server, as well as SymStore...but I couldn't find definitive answers on whether that is true or not.

**Comment by mitchdenny** [comment]
Do these instructions work for you?

https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/setting-up-github-sourcelinking?view=azure-devops

(note that it uses the designer based task interface, but there is a equivalent for YAML).

**Comment by Sean-Driscoll** [comment]
For the purposes of that article the instructions look fine. But, I'm not using GitHub in any way. In general, any up-to-date info is great though so I appreciate the effort. 

Regarding my original question, I believe you provided an answer. The answer was yes, the Azure DevOps integrated symbol server supports portable PDBs. If you also happen to know whether SymStore supports portable PDBs, or maybe the article [here](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md#tools-that-require-windows-pdbs) just has out-of-date information, that would be helpful to know too. Otherwise, feel free to close this out. Thanks!

**Comment by fadnavistanmay** [comment]
Thanks Mitch for the insights. Sean, I am closing this issue, as Mitch has provided instructions to publish portable PDBs. I am not sure of whether SymStore support them or not.
