### ISSUE TITLE
Allow enableXmlTransform to be set via parameter

### ISSUE THREAD

**Issue by ravensorb** [microsoft/azure-pipelines-tasks#12088]
It looks like v2 hard coded the xml transform to true, could it be updated to allow it to be set via a parameter again?

https://github.com/microsoft/azure-pipelines-tasks/blob/dcae2fa419269dd52099f5691d341164fb39ce87/Tasks/FileTransformV2/filetransform.ts#L13

**Comment by eaarora-ms** [comment]
Hi @ravensorb  
No, we are not planning to update the xml transform flag to be set via a parameter again.

**Comment by eaarora-ms** [comment]
Closing this. Please let us know if you need any help wrt the usage of the task.
