### ISSUE TITLE
gulp issue with the Node which throws  ReferenceError: primordials is not defined in Azure Devops pipeline

### ISSUE THREAD

**Issue by path2webdev** [microsoft/azure-pipelines-tasks#12086]
While building the Build pipeline in the Azure Devops  the following error occurs during the command for the Gulp- deploy 

![image](https://user-images.githubusercontent.com/40358473/71866398-080b5700-315a-11ea-8c1b-cd898925ae5f.png)

**Comment by jmyersmsft** [comment]
This appears to be a mismatch between Node and Gulp versions: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by herenhuang** [comment]
Hey @path2webdev - did the response above from the team help?

**Comment by omokoh** [comment]
Hi ,
If you are still having this issue, please reopen it.

Thanks
