### ISSUE TITLE
Consider adding authorization on SQL server using Service Connection

### ISSUE THREAD

**Issue by philly86** [microsoft/azure-pipelines-tasks#12083]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: SqlAzureDacpacDeployment

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

In my organization we're using Dacpac to create not only database structure but also map SQL users with AAD groups. As such operations can be [performed only with AAD accounts](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure?tabs=azure-powershell#create-contained-database-users-in-your-database-mapped-to-azure-ad-identities), we're looking for an option to make our CD pipeline task to authorize on Azure SQL server using an AD account. For a number of reasons putting account password to variables or setting up an own agent and using 'Active Directory - Integrated' auth method are not viable for us.

My suggestion would be to leverage /AccessToken feature of SQLPackage and extent SqlAzureDacpacDeployment task with ability to authenticate on target SQL server as service principal used in Azure Devops service connection.

This should be relatively simple using methods ADAL as shown in [this example](https://blogs.technet.microsoft.com/stefan_stranger/2018/06/06/connect-to-azure-sql-database-by-obtaining-a-token-from-azure-active-directory-aad/)
The same, of course, can be done in a custom Powershell script ran in AzurePowershell task, but in such case it would be required to pass service principal password to the script as a variable, which is a considerable security weakening compared to obtaining the password inside the task using Get-VstsEndpoint

**Comment by jabbera** [comment]
I can't believe this isn't a thing!

**Comment by NickDarvey** [comment]
This would be a great enhancement. I really don't want to have to keep my database password in my pipeline variables, it'd be much better to be able to use the existing service principal.

**Comment by ekbrothers** [comment]
We need this as well.

**Comment by Baddog240Z** [comment]
I agree that support for Azure AD Integrated authentication should be added. Hosted Agents already use Azure AD Identities in order to connect to the target tenant/subscription so that they can publish to Web App Services, and that same Azure AD identity could be given permissions to connect to SQL Azure. The fact that this Task doesn't support it means that all the effort we go through to set up and use Azure AD Integrated auth to make things nice and secure is thwarted because this Pipeline Task needs hard-coded credentials.

**Comment by 7even7** [comment]
I'm researching our options to create environment specific permissions to our dev/test/prod SQL databases (including ASQLDBs and ASQLDW:s). 
Ideally I'd like to have parameterized post scripts in our database projects that would handle the permissions with AD groups. 

The inability to do this is really a feature breaking thing for dacpac deployments. 

The work arounds are all bad
* Using username / password
* Custom scripts with Oauth2 tokens and SID-compiling
* Manual steps per environment

**Comment by NickDarvey** [comment]
Are there any updates on this?

**Comment by KuehneThomas** [comment]
Any updates?

**Comment by kcaswick** [comment]
Still need this you silly bot, if anything more so the more people move to more secure authentication.

**Comment by barsipos** [comment]
Please consider doing this, really needed.

**Comment by kpotterams** [comment]
Silly bots, staleness is for non-issues :P
