### ISSUE TITLE
AzureCLI unable to set subscription when multiple are available 

### ISSUE THREAD

**Issue by jvassbo** [microsoft/azure-pipelines-tasks#12098]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI

## Environment
- Server - Azure Pipelines
- Agent - Hosted ubuntu-latest

## Issue Description

When using a Service Connection that has a Service Principal with access to multiple subscriptions, the task fails with `ERROR: The subscription of 'undefined' doesn't exist in cloud 'AzureCloud'.`

### Task logs

![image](https://user-images.githubusercontent.com/190038/71973092-51b57980-320e-11ea-8b22-c3d25819cdc5.png)

```
Starting: AzureCLI
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerSheell Core/Batch script when running on Windows agent.
Version      : 2.0.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
WARNING: You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
azure-cli                         2.0.77 *

command-modules-nspkg              2.0.3
core                              2.0.77 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/vsts/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Nov 22 2019, 05:32:22) 
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal


Setting active cloud to: AzureCloud
/usr/bin/az cloud set -n AzureCloud
/usr/bin/az login --service-principal -u *** -p *** --tenant ***
[
   list of subscriptions (redacted)
]
/usr/bin/az account set --subscription undefined
ERROR: The subscription of 'undefined' doesn't exist in cloud 'AzureCloud'.
##[error]Error Code: [1]
##[error]Error: Error in setting up subscription
##[error]Script failed with error: ERROR: The subscription of 'undefined' doesn't exist in cloud 'AzureCloud'.

/usr/bin/az account clear
Finishing: AzureCLI
```

**Comment by hiyadav** [comment]
Hey @jvassbo , 

it looks like the AzureRM Service connection being used in the task, is missing subscription name. Can you verify if this is the case ?

**Comment by jvassbo** [comment]
Hi @hiyadav,

Our service connection is scoped on ManagementGroup level, so no - no defined subscription

**Comment by hiyadav** [comment]
That is probably the reason of the error. To set the subscription the task, derives the subscription name from the service endpoint (assumed to be scoped to subscription) being used in the task.
Work around for now would be to using subscription based/scoped endpoint.

To be able to solve this can you tell us if you are using yaml pipeline ? or were you able to add the endpoint from old editor with UX ?

**Comment by jvassbo** [comment]
We are using yaml pipeline.

This service connection needs to be scoped on this level for our functional requirements, so the workaround is not going to work for us, unfortunately.

**Comment by jvassbo** [comment]
I stand corrected, the workaround _did_ work - even though our script does things outside of the scoped subscription.
Which makes me wonder, what excatly is the scope of a service connection in DevOps..?

Not sure if this should still be considered a bug, or if AzureCLI task just has a prerequisite that the used service connection is scoped on a subscription? (feel free to close the issue if so)

**Comment by hiyadav** [comment]
If the Azure SPN used to create the ARM service principal in ADO, has permission/role over all/many  subscriptions, then the command over those subscriptions are bound to succeed. 

Azure CLI task needs to set a current subscription after log-in. This is required as otherwise, all commands will run on a subscription which is enabled/checked by default for the user.

However, I realize that the task can compromise setting subscription when the information is not available. @jalajmsft @pulkitaggarwl  to consider this. 
Hence, marking it as enhancement.

**Comment by hiyadav** [comment]
We have tried to improve on the error message as well in this PR #12054

**Comment by hiyadav** [comment]
Hey @jvassbo 

We're closing this, as for now subscription remains a requirement of the task, and have recently put try catch blocks to surface the requirement to the end user. 

We might later remove this when we start supporting management endpoints in the task.

Thanks for reporting the issue :)

**Comment by jhonnatanpb** [comment]
Hi @jvassbo  
How you manage to create the service connection for multiple susbscriptions?
In Azure devops, when I create a service connection, I can just select one subscription, so, if I'm using the AzureCLI task, I just can select that service connection, and if my script is trying to access two subscriptions, it only can access the one selecte in the service connection, fails for the other one.
But according to your logs, your service connection can access several susbscriptions.
Thanks
