### ISSUE TITLE
Docker host endpoint unusable with Docker V2 task

### ISSUE THREAD

**Issue by jorrit** [microsoft/azure-pipelines-tasks#12100]
**Question, Bug, or Feature?**: Question

**Task Name**: DockerV2

## Environment
- Server - DevOps 2019 on premise

- Agent - Private agent on Windows Server 2016, v 2.153.1

## Issue Description

In V1 of the Docker task it was possible to set the Docker host connection. This setting was not ported to V2. How am I going to utilize the Docker host service endpoints in V2 of the docker task? I want to use certificates to connect to the docker host.

**Comment by vithati** [comment]
This is not supported in DockerV2 task. Please use V1 task.

**Comment by jorrit** [comment]
Do you know why that is? It seems that Docker Host endpoints no longer have any purpose when using only the latest versions of tasks. I don't want to rely on an outdated task, whenever possible.
