### ISSUE TITLE
Incorrect logs associated with test failures

### ISSUE THREAD

**Issue by mryachanin** [microsoft/azure-pipelines-tasks#12107]
## Required Information
**Type**: Bug
**Enter Task Name**: VSTestV2

## Environment
**Server**: Azure Pipelines
**Account Name**: Not sure. This is the domain: skype.visualstudio.com
**Team Project Name**: SCC
**Build Definition Id**: 2431
**Agent**: Private
**Agent OS**: 10.0.18362
**Agent Version**: 2.163.1

## Issue Description
Sometimes, the console output attached to failed tests doesn't match with the test that failed.

It is not consistent between builds (doesn't always happen) and is not consistent within builds (some have correct output and some have incorrect output).

I know the output is incorrect because the test name is logged at the end of each test run.

This issue was discovered when we started seeing logs with all success metrics for failed tests.

The impact of this issue is the inability to debug failed tests.

This is one such build: https://skype.visualstudio.com/SCC/_build/results?buildId=25332813&view=ms.vss-test-web.build-test-results-tab&runId=35790602&resultId=100545&paneView=attachments

The test “TestReplayThread_TeamDoesNotExist_Exists_ReplayMessageBefore" has the output of test “TestReplayReplyChain_ReplayReplyThenPost_VersionSameAsId_Success”.

The test “TestReplayMessage_ThreadDoesNotExistMessageReplay_Success” has the output of test “GetGenericTeamThread_ByMemberNotOnTeam_Fails”.

----

Somewhat related, sometimes we don't get any console output at all attached to failed tests.
Here is an example of that: https://skype.visualstudio.com/SCC/_build/results?buildId=25317819&view=ms.vss-test-web.build-test-results-tab&runId=35743224&resultId=100514&paneView=attachments

The logs should not have been rotated out in this case. It has happened multiple times and the logs are missing on test failures less than a day old.

**Comment by ShreyasRmsft** [comment]
```
 <MSTest>
    <Parallelize>
      <Workers>2</Workers>
      <Scope>ClassLevel</Scope>
    </Parallelize>
  </MSTest>
```

You have enabled parallelization in Mstest. This causes stdout stream to be shared between multiple threads causing the test output to be jumbled.

Use [TestContext.WriteLine](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext.writeline?view=mstest-net-1.2.0) to correctly map output to tests when running them in parallel.
