### ISSUE TITLE
Build artifact uploads timing out

### ISSUE THREAD

**Issue by josh-endries** [microsoft/azure-pipelines-tasks#12102]
## Required Information

**Type**: Bug
**Enter Task Name**: Publish build artifacts 
**Environment**: Azure Pipelines
**Agent**: Hosted (windows-2019)

## Issue Description

Our build artifact uploads are timing out frequently. It started rarely about half way through December, but lately it is about 50% of the time. It looks like the step makes a few attempts and then times out. Re-running the pipeline, even immediately, frequently works.

Our step in the pipeline definition actually has Timeout set to zero, though that doesn't seem to apply to this. It would be nice to be able to configure the delay between attempts and number of attempts.

It's not a public project but I can provide details via another method. Here are some example lines:

```
Fail to upload '...' due to 'Blob is incomplete (missing block). Blob: ..., Expected Offset: 0, Actual Offset: 8388608'.
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: ..., Expected Offset: 0, Actual Offset: 8388608 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: ..., Expected Offset: 0, Actual Offset: 8388608
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.UploadAsync(IAsyncCommandContext context, Int32 uploaderId, CancellationToken token)
```

```
Chunk '4' attempt '1' of file '...' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: ..., Expected Offset: 0, Actual Offset: 12582912 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: ..., Expected Offset: 0, Actual Offset: 12582912
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
Backoff 9.883 seconds before attempt '2' chunk '4' of file '...'.
```

```
Start retry 1 failed files upload.
Uploading '...' (25%)
Uploading '...' (50%)
Uploading '...' (75%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Fail to upload '...' due to 'Blob is incomplete (missing block). Blob: ..., Expected Offset: 0, Actual Offset: 12582912'.
```

**Comment by leantk** [comment]
We are currently pushing customers that are using the older Build Artifact tasks to start using our new Pipeline Artifact tasks. The Pipeline Artifact tasks are backed by a new pipeline artifact service that is better equipped for handling artifacts than the older build artifact service. I would encourage you to try moving to those tasks and see if that solves your issue. You can see documentation on how to change and more info on the new tasks here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#migrating-from-build-artifacts

If you still see the same issue, please let me know

**Comment by josh-endries** [comment]
Sadly it's not a drop-in replacement, it errors out for us (duplicate artifact for multiplier variables), so it looks like we will need to modify all our build and release pipelines to use the new one (almost all of them have multipliers). We have something like 100 pipelines, so that will take a while to change and test. Tomorrow I will try to get it working and see how much work it would be to migrate.

It would be much preferable that the existing one (which isn't currently deprecated) work reliably, like it seemed to do until last month. All that seems to need to be done is increase the timeout/delay or number of retries, since rerunning the step immediately after it fails works virtually every time. Making it configurable would be nice but probably isn't really necessary.

**Comment by rokonec** [comment]
@leantk We would like to escalate priority of this issue. 

Recently it got worse. With increasing activity and builds rate related to .NET 5 activity it starts to be quite bothersome for [dotnet org](https://github.com/dotnet). 

See #dotnet/core-eng#10458

**Comment by leantk** [comment]
@rokonec I don't have permissions to see that issue. Could get some examples of this happening? 

CC: @edglas1 this another example of a team that can't move from build artifacts to pipeline artifacts easily but would benefit from their updated artifacts service

**Comment by rokonec** [comment]
In runtime-official its failing with message ' after retry' at these builds of last 1000:
|Build|Kind|Timeline Record|
|---|---|---|
|[773847](https://dev.azure.com/dnceng/internal/_build/results?buildId=773847)|Rolling|Publish intermediate unsigned artifacts|
|[773847](https://dev.azure.com/dnceng/internal/_build/results?buildId=773847)|Rolling|Publish intermediate unsigned artifacts|
|[773477](https://dev.azure.com/dnceng/internal/_build/results?buildId=773477)|Rolling|Publish intermediate unsigned artifacts|
|[772427](https://dev.azure.com/dnceng/internal/_build/results?buildId=772427)|Rolling|Publish intermediate unsigned artifacts|
|[772309](https://dev.azure.com/dnceng/internal/_build/results?buildId=772309)|Rolling|Publish Logs|
|[767918](https://dev.azure.com/dnceng/internal/_build/results?buildId=767918)|Rolling|Publish intermediate unsigned artifacts|
|[766721](https://dev.azure.com/dnceng/internal/_build/results?buildId=766721)|Rolling|Publish intermediate unsigned artifacts|
|[766721](https://dev.azure.com/dnceng/internal/_build/results?buildId=766721)|Rolling|Publish intermediate unsigned artifacts|
|[762828](https://dev.azure.com/dnceng/internal/_build/results?buildId=762828)|Rolling|Publish intermediate unsigned artifacts|
|[762520](https://dev.azure.com/dnceng/internal/_build/results?buildId=762520)|Rolling|Publish intermediate unsigned artifacts|
|[762520](https://dev.azure.com/dnceng/internal/_build/results?buildId=762520)|Rolling|Publish intermediate unsigned artifacts|
|[762274](https://dev.azure.com/dnceng/internal/_build/results?buildId=762274)|Rolling|Publish intermediate unsigned artifacts|
|[761559](https://dev.azure.com/dnceng/internal/_build/results?buildId=761559)|Rolling|Publish Logs|
|[761559](https://dev.azure.com/dnceng/internal/_build/results?buildId=761559)|Rolling|Publish Logs|
|[761559](https://dev.azure.com/dnceng/internal/_build/results?buildId=761559)|Rolling|Publish Logs|
|[761077](https://dev.azure.com/dnceng/internal/_build/results?buildId=761077)|Rolling|Publish intermediate unsigned artifacts|
|[761077](https://dev.azure.com/dnceng/internal/_build/results?buildId=761077)|Rolling|Publish intermediate unsigned artifacts|
|[758966](https://dev.azure.com/dnceng/internal/_build/results?buildId=758966)|Rolling|Publish intermediate unsigned artifacts|
|[758966](https://dev.azure.com/dnceng/internal/_build/results?buildId=758966)|Rolling|Publish intermediate unsigned artifacts|
|[757304](https://dev.azure.com/dnceng/internal/_build/results?buildId=757304)|Rolling|Publish Logs|
|[756740](https://dev.azure.com/dnceng/internal/_build/results?buildId=756740)|Rolling|Publish Logs|
|[756405](https://dev.azure.com/dnceng/internal/_build/results?buildId=756405)|Rolling|Publish intermediate unsigned artifacts|
|[756405](https://dev.azure.com/dnceng/internal/_build/results?buildId=756405)|Rolling|Publish intermediate unsigned artifacts|
|[755263](https://dev.azure.com/dnceng/internal/_build/results?buildId=755263)|Rolling|Publish Logs|
|[753862](https://dev.azure.com/dnceng/internal/_build/results?buildId=753862)|Rolling|Publish Logs|
|[753804](https://dev.azure.com/dnceng/internal/_build/results?buildId=753804)|Rolling|Publish Logs|
|[753685](https://dev.azure.com/dnceng/internal/_build/results?buildId=753685)|Rolling|Publish intermediate unsigned artifacts|
|[753064](https://dev.azure.com/dnceng/internal/_build/results?buildId=753064)|Rolling|Publish Logs|
|[752453](https://dev.azure.com/dnceng/internal/_build/results?buildId=752453)|Rolling|Publish Logs|
|[752332](https://dev.azure.com/dnceng/internal/_build/results?buildId=752332)|Rolling|Publish intermediate unsigned artifacts|
|[751440](https://dev.azure.com/dnceng/internal/_build/results?buildId=751440)|Rolling|Publish intermediate unsigned artifacts|
|[751440](https://dev.azure.com/dnceng/internal/_build/results?buildId=751440)|Rolling|Publish intermediate unsigned artifacts|
|[749788](https://dev.azure.com/dnceng/internal/_build/results?buildId=749788)|Rolling|Publish intermediate unsigned artifacts|
|[749788](https://dev.azure.com/dnceng/internal/_build/results?buildId=749788)|Rolling|Publish intermediate unsigned artifacts|
|[745595](https://dev.azure.com/dnceng/internal/_build/results?buildId=745595)|Rolling|Publish intermediate unsigned artifacts|
|[743815](https://dev.azure.com/dnceng/internal/_build/results?buildId=743815)|Rolling|Publish intermediate unsigned artifacts|
|[743815](https://dev.azure.com/dnceng/internal/_build/results?buildId=743815)|Rolling|Publish intermediate unsigned artifacts|
|[743271](https://dev.azure.com/dnceng/internal/_build/results?buildId=743271)|Rolling|Publish Logs|
|[743271](https://dev.azure.com/dnceng/internal/_build/results?buildId=743271)|Rolling|Publish Logs|
|[740857](https://dev.azure.com/dnceng/internal/_build/results?buildId=740857)|Rolling|Publish intermediate unsigned artifacts|
|[740857](https://dev.azure.com/dnceng/internal/_build/results?buildId=740857)|Rolling|Publish intermediate unsigned artifacts|
|[740664](https://dev.azure.com/dnceng/internal/_build/results?buildId=740664)|Rolling|Publish intermediate unsigned artifacts|
|[740664](https://dev.azure.com/dnceng/internal/_build/results?buildId=740664)|Rolling|Publish intermediate unsigned artifacts|
|[739507](https://dev.azure.com/dnceng/internal/_build/results?buildId=739507)|Rolling|Publish intermediate unsigned artifacts|
|[739507](https://dev.azure.com/dnceng/internal/_build/results?buildId=739507)|Rolling|Publish intermediate unsigned artifacts|
|[739239](https://dev.azure.com/dnceng/internal/_build/results?buildId=739239)|Rolling|Publish intermediate unsigned artifacts|
|[739239](https://dev.azure.com/dnceng/internal/_build/results?buildId=739239)|Rolling|Publish intermediate unsigned artifacts|
|[737998](https://dev.azure.com/dnceng/internal/_build/results?buildId=737998)|Rolling|Publish Logs|

**Comment by rokonec** [comment]
The responsible team realized, that this particular issue has been most probably caused by two build legs concurrently uploading same package.
So this issue is no longer critical for us. I still consider it a bug though, that it is allowed to concurrently upload package. Especially concurrent chunk upload sounds scary if there is no final SHA verification.
