### ISSUE TITLE
Disconnect-AzureAndClearContext detects Az-library incorrectly

### ISSUE THREAD

**Issue by HQJaTu** [microsoft/azure-pipelines-tasks#12115]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: Common, all Azure

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/Common/VstsAzureHelpers_/Utility.ps1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: v2.160.1

## Issue Description

On a self-hosted machine where both Az and AzureRm -libraries are installed, function `Disconnect-AzureAndClearContext` detects the library being used with a code:
```
if (Get-Module Az.Accounts -ListAvailable)
```

When running AzureRm, the obvious problem is, that library _Az.Accounts_ is **available**. It just isn't loaded at the time of the test. Dropping the `-ListAvailable` will tell if given library has been loaded and is being used.

### Task logs

```
2020T.7423129Z VERBOSE: Import: 'Microsoft.Azure.Management.KeyVault.dll'
2020T.7436733Z VERBOSE: Loading module from path 'C:\Program 
2020T.7440681Z VERBOSE: Files\WindowsPowerShell\Modules\AzureRM.KeyVault\5.2.1\Microsoft.Azure.Management.KeyVault.dll'.
2020T.7555428Z VERBOSE: Importing function 'CmdletHasMember'.
2020T.7563172Z VERBOSE: Importing function 'Disconnect-AzureAndClearContext'.
2020T.7571424Z VERBOSE: Importing function 'Initialize-AzModule'.
2020T.7579904Z VERBOSE: Importing function 'Initialize-Azure'.
2020T.7587272Z VERBOSE: Importing function 'Initialize-AzureRMModule'.
2020T.7595198Z VERBOSE: Importing function 'Remove-EndpointSecrets'.
2020T.7697450Z VERBOSE: Trying to disconnect from Azure and clear context at process scope
2020T.7774736Z VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted 
2020T.7775335Z versions.
2020T.7792506Z VERBOSE: Populating RepositorySourceLocation property for module Az.Accounts.
2020T.7809174Z VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.7.0\Az.Accounts.psm1'.
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by 20shivangi** [comment]
@HQJaTu 
Please share the full debug logs by setting system.debug variable to true in your pipeline

**Comment by HQJaTu** [comment]
I'm closing this ticket.

How Deployment Agent handles both PowerShell Core and Az-library detection is a royal mess of spaghetti and needs to be rewritten. One cannot assume the current PowerShell3-handler can be used to detect libraries existing both in PowerShell 5.x and PowerShell Core. To clarify this mess, a new handler needs to be added for PowerShell Core. At the time of writing, most use cases don't require using PowerShell 5.x nor AzureRm. However, there exists plenty of code for both.

Doing this refactoring would allow simplifying the obsoleted AzureRm-library detection which needs to stay at AzurePowerShellV3 task.
