### ISSUE TITLE
Gate Http Request Chain Body Syntax

### ISSUE THREAD

**Issue by Dejulia489** [microsoft/azure-pipelines-tasks#12126]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: All Gates

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
 life-pacificlife, Databases, definition id 104

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
There is a syntax available in the gate but I am unable to find the documentation for it. 

For example the following in in the body of a call. It does work for formating the time but I am unable to identify the method/function to get the current time.
{{#if scheduleendtime}},\"u_end_date\": \"{{#if scheduleendtime}}{{toDateTimeFormat '$(scheduleendtime)' 'yyyy-MM-dd HH:mm:ss UTC'}}{{/if}}\"{{/if}}

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ObsidianVoid** [comment]
@Dejulia489 Apologies for the delay in response. There is no available method to get the current UTC time. The snippet posted above takes the time value in an input field from the user. Optionally, you can use the stage level pre-defined variable "$(Release.Deployment.StartTime)".

**Comment by Dejulia489** [comment]
No worries, thanks for getting back to me.  I noticed there are methods to format time 'toDateTimeFormat'. What other methods are available, is it documented?

Thanks

**Comment by ObsidianVoid** [comment]
There is no documentation available. If there is a specific functionality you looking for, let me know and i'll see if there is anything that can help.

**Comment by Dejulia489** [comment]
Documentation would be nice. Closing this issue.
