### ISSUE TITLE
Does AzureIoTEdgeV2 clean up intermediate images after each and every build?

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-tasks#12138]
## Required Information

*Type*: Question

*Task Name**: AzureIoTEdgeV2
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureIoTEdgeV2

## Environment
- Server - Azure Pipelines
   account name, team project, build definition, and build number can be provided in private

- private agent: 
   Ubuntu 18.04.3 running agent 2.159.2

## Issue Description
There are lots of dangling intermediate images left behind on the server and we have to periodically disable build agent temporarily from the pool and run a docker prune job to free up space taken up by intermediate images. My understanding is that this task relies on the presence of [iotedgedev toolchain](https://github.com/Azure/iotedgedev) and based on what I can see on the [build options parser](https://github.com/Azure/iotedgedev/blob/master/iotedgedev/buildoptionsparser.py) that it does support the --rm parameter. However, based on the behavior I'm observing, it appears to not be using the --rm parameter on docker build.

**Comment by blackchoey** [comment]
@tristanbarcelon The default value of `--rm` option is `true` according to docker build [document](https://docs.docker.com/engine/reference/commandline/build/). So docker will remove the intermediate containers after a successful build by default.
Can you run docker build command manually and see whether the intermediate container will be removed after build success?

**Comment by tristanbarcelon** [comment]
Hi @blackchoey , I'll run docker build directly against one of the edge modules to verify this behavior. We have a build server dedicated solely for building iotedge projects and I had to delete 86GB of dangling images back almost 3 months ago and more recently had to do it again. To be clear, these dangling images have repository and tag equal to `<none>` when running docker image ls.
