### ISSUE TITLE
Warning MSB4126: The specified solution configuration "AZURE-TEST|x64" is invalid.

### ISSUE THREAD

**Issue by MrDoctorJ** [microsoft/azure-pipelines-tasks#12146]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Build Solution

## Environment
Account name: nucor.visualstudio.com
Team project name: NSARWeb

- Agent - Hosted or Private: 
    Private agent
    OS: Windows Server 2016 version 1607
    Agent Version: 2.144.2

## Issue Description

Building solution throws the following warning: 
```##[warning]C:\agent\_work\6\s\NSAR API.sln.metaproj(0,0): Warning MSB4126: The specified solution configuration "AZURE-TEST|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.```

The build completes just fine but still throws the warning. I don't get the warning when building in Visual Studio locally. 
Configuration manager in Visual Studio: 
![image](https://user-images.githubusercontent.com/8164589/72380319-c7bc5380-36da-11ea-8a58-76f495590483.png)

Settings within the build: 
![image](https://user-images.githubusercontent.com/8164589/72380377-e3275e80-36da-11ea-9d8d-e0fe37caeb56.png)

Variable for `$(BuildPlatform)`: 
![image](https://user-images.githubusercontent.com/8164589/72380404-f2a6a780-36da-11ea-901e-74e559ca1e56.png)

We also have a `web.AZURE-TEST.config` xml transform. 

Based on all of that, I would think that `AZURE-TEST|x64` is a valid build configuration. Can anyone help me get rid of this build warning? 

### Task logs

[log_10_7908.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4061347/log_10_7908.zip)

### Error logs

`##[warning]C:\agent\_work\6\s\NSAR API.sln.metaproj(0,0): Warning MSB4126: The specified solution configuration "AZURE-TEST|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.`

**Comment by dfoulk** [comment]
I would also like to know why I get this error when building with a valid build configuration. I am using the "ASP.NET Core (.NET Framework)" pipeline template.

```
##[warning]D:\a\1\s\Chi.Data.sln.metaproj(0,0): Warning MSB4126: The specified solution configuration "test|any cpu" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.
```
![Test-Build-Configuration](https://user-images.githubusercontent.com/26492393/74966810-aa129600-53cc-11ea-82e7-e162c9a7dd6b.png)

The only configuration changes that I've made to this pipeline is a fix for an error/bug (see [this post](https://developercommunity.visualstudio.com/comments/804578/view.html)) and I added a NuGet package feed (DevOps Artifacts) to the "NuGet restore" task. It's hard to imagine that either of these changes is responsible for this, though.

Thanks in advance!

**Comment by M198** [comment]
Shut up
________________________________

**Comment by dfoulk** [comment]
> Shut up
> […](#)
> ________________________________ From: Derek Foulk <notifications@github.com> Sent: Thursday, February 20, 2020 11:41 AM To: microsoft/azure-pipelines-tasks <azure-pipelines-tasks@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [microsoft/azure-pipelines-tasks] Warning MSB4126: The specified solution configuration "AZURE-TEST|x64" is invalid. (#12146) I would also like to know why I get this error when building with a valid build configuration. I am using the "ASP.NET Core (.NET Framework)" pipeline template. ##[warning]D:\a\1\s\Chi.Data.sln.metaproj(0,0): Warning MSB4126: The specified solution configuration "test|any cpu" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [Test-Build-Configuration]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F26492393%2F74966810-aa129600-53cc-11ea-82e7-e162c9a7dd6b.png&data=02%7C01%7C%7Cccd1dcddd9864cf0259f08d7b6348dec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637178209137655906&sdata=0Owjam%2Bn33ILdH03MNCemDeF5sKcNJF1aDFuHXaVXTM%3D&reserved=0> The only configuration changes that I've made to this pipeline is a fix for an error/bug (see this post<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcomments%2F804578%2Fview.html&data=02%7C01%7C%7Cccd1dcddd9864cf0259f08d7b6348dec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637178209137655906&sdata=DzrVgRw9gZcOwqe22VnQUatSiwgwYYZe47kJ7OaH2Kw%3D&reserved=0>) and I added a NuGet package feed (DevOps Artifacts) to the "NuGet restore" task. It's hard to imagine that either of these changes is responsible for this, though. Thanks in advance! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure-pipelines-tasks%2Fissues%2F12146%3Femail_source%3Dnotifications%26email_token%3DALUUZL4XGBCEOFQTWCPCCMDRD3FHBA5CNFSM4KGZGRT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMPSYZA%23issuecomment-589245540&data=02%7C01%7C%7Cccd1dcddd9864cf0259f08d7b6348dec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637178209137655906&sdata=Nc0LuRGdRQPi2uOKCfYnhq7SKdTbg5kRQPAQchpup4k%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALUUZLZ4JSCTJRRZE2FHEYLRD3FHBANCNFSM4KGZGRTQ&data=02%7C01%7C%7Cccd1dcddd9864cf0259f08d7b6348dec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637178209137665901&sdata=PeuxLjkYkjKt9Xdu%2FSrbMRG8kSCNfuvlgPRziAp%2FcT8%3D&reserved=0>.

Heh?

**Comment by dfoulk** [comment]
Is this the intended functionality? We have to use Release and/or Debug configurations, else receive warnings?
