### ISSUE TITLE
VSTest task fails with error: System.ArgumentException: parsing "^(?!\.)(?=.)[TP-23] Smoke Tests\.dll$" - [x-y] range in reverse order.

### ISSUE THREAD

**Issue by Roman-Rostovtsev** [microsoft/azure-pipelines-tasks#12149]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest

## Environment
- Server - Azure Pipelines
    
https://dev.azure.com/nsq20040061/VSTestExperiment/_build/results?buildId=3&view=results

- Agent - Private:  OS Windows 8.1, agent version: '2.163.1'
    
## Issue Description
VSTest task in Test Plan mode fails with the strange error

> ##[error]An exception occurred while executing the task. So the task is not executed. System.AggregateException: One or more errors occurred. ---> System.ArgumentException: parsing "^(?!\.)(?=.)[TP-23] Smoke Tests\.dll$" - [x-y] range in reverse order.

if automated test storage of test case contains square bracket characters in filename.

### Task logs

You can find here: https://dev.azure.com/nsq20040061/VSTestExperiment/_build/results?buildId=3&view=results

**Comment by ShreyasRmsft** [comment]
@Roman-Rostovtsev this seems like a corner case issue since the minimatch C# library we use has this issue. Please do workaroud this by renaming the dll for now. There's no easy way to fix this since the fix will need to be made in the library we use which is a third part one.

**Comment by ShreyasRmsft** [comment]
```
##[error]An exception occurred while executing the task. So the task is not executed. System.AggregateException: One or more errors occurred. ---> System.ArgumentException: parsing "^(?!\.)(?=.)[TP-23] Smoke Tests\.dll$" - [x-y] range in reverse order.
   at System.Text.RegularExpressions.RegexParser.ScanCharClass(Boolean caseInsensitive, Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at Minimatch.Minimatcher.MagicItem.<>c__DisplayClass0.<.ctor>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Minimatch.Minimatcher.MagicItem.Match(String input, Options options)
   at Minimatch.Minimatcher.MatchOne(IList`1 file, IList`1 pattern, Boolean partial)
   at Minimatch.Minimatcher.MatchOne(IList`1 file, IList`1 pattern, Boolean partial)
   at Minimatch.Minimatcher.Match(String input, Boolean partial)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.VisualStudio.TestService.VstestAdapter.MiniMatchSourceFilter.FilterSources()
   at Microsoft.VisualStudio.TestService.VstestAdapter.DiscoverTests.PerformDiscovery(TestAutomationRunSlice sliceDetails, IAddTestCasesToTcmRunHandler addTestCasesToTcmRunHandler, ExecutionStateContext stateModelContext)

```

You can raise the issue with the owner and if they fix it we will definitely update the version in our task.

**Comment by nehsharmMS** [comment]
@Roman-Rostovtsev ,any update on what Shreyas suggested? If you are still facing the issue, can you please enable debug logging (System.Debug) and provide the entire logs zip?

Checkout how to troubleshoot failures and collect debug logs: [https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting].

**Comment by Roman-Rostovtsev** [comment]
Sorry, I did not understand, why more logs are needed, if ShreyasRmsft has already detected the source of the issue. Of course, if an assembly name does not contain [], the issue does not occur. I don't know whether [] presence is very critical, since it is a bug from our customers

**Comment by ShreyasRmsft** [comment]
@Roman-Rostovtsev we wanted to confirm if it was the Assembly that contained these special chars or your folder path? And which are the exact special characters that are present. The logs will give us all these details. Please do attach them here for us to try and get a local repro to confirm my suspicions. 

Also the build you shared has expired and we need logs with system.debug = true.

**Comment by Roman-Rostovtsev** [comment]
Ok, I've just ran the build again with enabled diagnostics. You can find it here:
https://dev.azure.com/nsq20040061/VSTestExperiment/_build/results?buildId=11&view=results
[] characters are contained both in the test storage filename and folder:
"c:\vstestAgent_for_nsq20040061\_work\1\s\UnitTests\[TP-23] Smoke Tests\[TP-23] Smoke Tests\bin\Debug\[TP-23] Smoke Tests.dll"
I've also created another build where test storage file is copied to another folder without [] characters ("c:\vstestAgent_for_nsq20040061\_work\3\s\Built\[TP-23] Smoke Tests.dll") and I've got the similar error: 
https://dev.azure.com/nsq20040061/VSTestExperiment/_build/results?buildId=12&view=results

**Comment by nehsharmMS** [comment]
@Roman-Rostovtsev,

It is confirmed that issue is caused by special character "[]" present in dll filename. Since, Same filename is used further as pattern, Mini-match is throwing error. Resolution as you already know is to not use characters that are special to [Mini-Match](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops).
