### ISSUE TITLE
VsTest task with the "Test plan" option selected tries to run tests in obj/ directories

### ISSUE THREAD

**Issue by vaindil** [microsoft/azure-pipelines-tasks#12144]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: Bug

**Enter Task Name**: VsTest

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Can provide privately

- Agent - Hosted or Private: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10, agent 2.163.1

## Issue Description
When "Select tests using" is set to "Test plan", the test runner is not excluding `obj/` directories from testing, so it attempts to run tests twice. The run of the project that's in the obj folder is understandably failing because files are missing.

### Task logs
Can provide privately

### Error logs
> Unable to find C:\fakepath\MyProject\obj\Debug\netcoreapp2.1\MyProject.deps.json. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk".

**Comment by nehsharmMS** [comment]
Hi Steven,

We are looking into the issue. Please provide the entire logs zip with system.debug set to true.

MailTo : devops_tools AT microsoft DOT com

**Comment by sulabh-msft** [comment]
@vaindil 

Can you please enable debug logging (System.Debug)  and provide the entire logs zip?

Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by vaindil** [comment]
I'm sorry, I'm on vacation until next Tuesday. I will be able to send the logs then.

**Comment by nehsharmMS** [comment]
@vaindil

We have made fix for the issue which will be available in task version greater 2.165.0. You can find PR [here](https://github.com/microsoft/azure-pipelines-tasks/pull/12194).

**Comment by ShreyasRmsft** [comment]
@vaindil this is fixed and is getting rolled out. Let us know if you are facing this issue even after getting 2.165.0 version of the task.
