### ISSUE TITLE
AzureWebAppV1 - Documented parameters missing from task

### ISSUE THREAD

**Issue by Zhaph** [microsoft/azure-pipelines-tasks#12145]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureWebAppV1

## Environment
- Server - Azure Pipelines 
   
    - HugoAndCat - Alta - Alta CI - 0.0.0.3 

- Agent - Hosted or Private: Hosted
   
    - If using Hosted agent, provide agent queue name: Ubuntu-Latest

## Issue Description

The `readme` states that I can pass parameters such as "Remove Additional Files at Destination" or "Exclude Files from the App_Data Folder" however these parameters are missing from the `taskparameters.ts` file.

With these (and the other listed parameters) missing, the YAML version of this task is significantly behind the "Classic" version of the task from the Release pipelines flow.

As it stands, I have no way to leave environment specific/generated files on a given server using the YAML deployments, and will have to revert back to "Classic" deployments separate from my CI build pipeline.

**Comment by eaarora-ms** [comment]
@Zhaph  Hi, we are extremely sorry for the confusion. We have completely removed msdeploy from the new tasks. It is neither supported in YAML not classic deployments. I will update the readme right away. 
Thank you for pointing this out.

**Comment by Zhaph** [comment]
Cheers for the update @eaarora-ms

However I see my confusion - I should have been using the `AzureRmWebAppDeployment` task, (documented as "Azure App Service Deploy") rather than this one ("Azure Web App" task).

**Comment by eaarora-ms** [comment]
@Zhaph  Yes AzureRmWebAppDeployment still supports webdeploy.
