### ISSUE TITLE
VS Test Task - Run Only Impacted Tests

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/azure-pipelines-tasks#12152]
## Note  
How to validate whether Run Only Impacted tests option is working fine or not..

The logs keep showing me this in the VS Test Task (Total files changed = 0) and it runs some sub-set of tests...

![image](https://user-images.githubusercontent.com/28302399/72453045-82585e80-378c-11ea-832b-c8b27d6c791c.png)

But I ran a simple PS script to get Git commit changes and can clearly see a cs file being changed.. 

![image](https://user-images.githubusercontent.com/28302399/72453148-a0be5a00-378c-11ea-90d4-2afee7262616.png)

in another run, there is only a FE change but still I see logs similar to above.. as I expect it to just skip running any tests... (VS Test task is only for running our BE tests)... I am also including this variable to ensure any *.js files are being ignored... 

![image](https://user-images.githubusercontent.com/28302399/72453471-1fb39280-378d-11ea-8478-63cda03eff91.png)

Anyone able to implement Run Only Impacted Tests option successfully?? Please suggest if I am missing any configuration. Thanks,

**Comment by ShreyasRmsft** [comment]
This was a regression in test platform version 16.5.0-preview-20200110-02 which was patched in the new test platform version 16.5.0-preview-20200116-01 and should no longer be occurring.

**Comment by nreddipalle** [comment]
@ShreyasRmsft How can I ensure I am running the latest version.. I am seeing only version 1 and version 2 for VS Test Task..

**Comment by ShreyasRmsft** [comment]
This is not the version of the vstest task but the vstest platform https://www.nuget.org/packages/Microsoft.TestPlatform
