### ISSUE TITLE
How to pass secrets to a script run by the AzurePowerShell task?

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/azure-pipelines-tasks#12153]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzurePowerShell

## Environment
- Server - Azure Pipelines 

- Agent - Hosted 

## Issue Description

This is a repeat question, since the answer provided to the previous issue (#11695) was not correct and that issue is closed.

What is the appropriate way to pass secrets to the script that will be run by an AzurePowerShell task given that this task does not have an "env" parameter like the PowerShell task does?

**Comment by arjgupta** [comment]
@pschaeflein , you can follow the documentation available [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables). If you are using YAML, you will have to define the secrets in the pipeline editor and then consume them using the $(var) notation.

**Comment by arjgupta** [comment]
Closing this issue. Please feel free to reopen if you need more clarity.
