### ISSUE TITLE
AzurePowerShell Task Exit Code Handling Not Working on Windows

### ISSUE THREAD

**Issue by jschwellnus92** [microsoft/azure-pipelines-tasks#12157]
Hi Folks!

I recently setup a Self-hosted Agent on Server 2019 using Visual Studio 2019 and PowerShell Core. I noticed that my AzurePowerShell tasks were behaving strangely after I moved my workload to the self-hosted agent from a Microsoft-hosted Ubuntu agent.

The AzurePowerShell task is not handling exit codes properly and is always reporting the task as successful even when the PowerShell script/inline returns a non-zero exit code. I was able to replicate this same behaviour on the Microsoft-hosted Windows 2019 agents. The Ubuntu agents are handling error codes correctly.

Here is a repro pipeline, just change the vmImage between Windows/Ubuntu for testing:
https://pastebin.com/raw/0brNDiBV

Here is a screenshot of the above repro code being ran on Windows latest:
<img width="313" alt="win2019-aps" src="https://user-images.githubusercontent.com/39755231/72495036-a2595200-3860-11ea-89a6-66319d161a38.png">

Here is a screenshot of the same repro code being ran on Ubuntu latest:
<img width="312" alt="ubuntu-aps" src="https://user-images.githubusercontent.com/39755231/72495035-a2595200-3860-11ea-953f-1a26442564b3.png">

**Comment by 20shivangi** [comment]
@jschwellnus92 We are able to figure out the issue, will fix it as soon as possible.

**Comment by 20shivangi** [comment]
@jschwellnus92 We have merged the PR : https://github.com/microsoft/azure-pipelines-tasks/pull/12288 to resolve this issue. It will get deployed within 6-8 weeks.
