### ISSUE TITLE
Return a more meaningful error message to Github when a ShellScript step fails

### ISSUE THREAD

**Issue by tomduncalf** [microsoft/azure-pipelines-tasks#12162]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: ShellScript

## Environment

Azure Pipelines

- Agent - Hosted or Private: 

Hosted, MacOS

## Issue Description

When a shell script step fails, the error message returned to the Github plugin just says:
`Bash exited with code '1'.`. Is there a way to return a more meaningful error message, to avoid developers having to go to the Azure logs every time?

**Comment by damccorm** [comment]
Hey @tomduncalf sorry for the slow response here. I believe this has been fixed in the most recent version of the task (it was renamed to Bash, so its BashV3), our recommendation would be to upgrade to that version.

**Comment by tomduncalf** [comment]
Great, I will give that a go, thanks @damccorm

**Comment by anatolybolshakov** [comment]
Hi @tomduncalf, have you tried it with last version of task, is it working for you?

**Comment by tomduncalf** [comment]
I'm afraid I've not had a chance to test this yet @anatolybolshakov. Please feel free to close and I will comment or open a new issue if there are any problems

**Comment by anatolybolshakov** [comment]
Ok, thanks! I'm closing it at the moment, please feel free to reopen it if issue still exists.
