### ISSUE TITLE
Unable to install new Az (Az.Search) module

### ISSUE THREAD

**Issue by stilren** [microsoft/azure-pipelines-tasks#12163]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Powershell@4

## Environment
- Server - Azure Pipelines

- Agent - Hosted
    
## Issue Description

Trying to run commands from the Az.Search module. It is not present in the powershell@4 task and I am unable to install and use the module

Running this code:
`Install-Module -Name Az.Search -Scope CurrentUser -Force -AllowClobber
Import-Module Az.Search
Get-AzSearchAdminKeyPair -ResourceGroupName "test" -ServiceName "test"`

will cause the error message:
The 'Get-AzSearchAdminKeyPair' command was found in the module 'Az.Search', but the module could not be loaded. For more information, run 'Import-Module Az.Search'.

**Comment by 20shivangi** [comment]
@stilren Az.Storage has been added in az module version 4.6.0 which is present in Hosted agent. Can you please try to run the AzurePowerShell task (V4/V5 version) with option latest version on Hosted agent ?

**Comment by 20shivangi** [comment]
@stilren The AzurePowerShell task with latest version of Az module on hosted agent will definitely solve your problem.
 I am closing this issue. However, if you find the issue again with latest version, please feel free to reopen this. We will surely help you.
