### ISSUE TITLE
DockerInstaller Should allow customised URL

### ISSUE THREAD

**Issue by riveryc** [microsoft/azure-pipelines-tasks#12168]
it's currently using "https://download.docker.com/%s/static/%s/x86_64/docker-%s%s" in https://github.com/microsoft/azure-pipelines-tasks/blob/1eff99f26be6cbb5cb77e1a702fdbdaad5555100/Tasks/DockerInstallerV0/src/utils.ts#L71

As customer may run this in non-internet environment and need this to be downloaded from a proxy url, such as Artifactory generic remote repository, which will use exactly same path to resolve the correct version of the package.

Can we have this URL customisable is possible?

Thanks
River

**Comment by ajinkya599** [comment]
There has been no customer ask for such a feature. If there is a good set of customers asking for this feature, we can evaluate this.
