### ISSUE TITLE
The Go task failed with an error: Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/go/1.13.3/x64/bin/go'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/go/1.13.3/x64/bin/go ENOENT

### ISSUE THREAD

**Issue by kwontae** [microsoft/azure-pipelines-tasks#12172]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: here  
go get
list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://microsoftit.visualstudio.com/OneITVSO/_build/results?buildId=3311063
takwo@microsoft.com, OneITVSO, E36-EHT-EPISPE-GoKpi, 20200118.1

- Agent - Hosted or Private: 
    Hosted
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Ubuntu 1604
## Issue Description

[Include task name(s), screenshots and any other relevant details]
It was working before the 1/1/2020...
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
```
##[section]Starting: go get
==============================================================================
Task         : Go
Description  : Get, build, or test a Go application, or run a custom Go command
Version      : 0.3.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/go
==============================================================================
[command]/opt/hostedtoolcache/go/1.13.3/x64/bin/go get -v -t -d all
##[error]The Go task failed with an error: Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/go/1.13.3/x64/bin/go'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/go/1.13.3/x64/bin/go ENOENT
##[section]Finishing: go get
```
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tejasd1990** [comment]
Hi @kwontae , Can you set _system.debug_ to _true_ in the build and send the complete build logs so that we can debug this?

**Comment by kwontae** [comment]
@tejasd1990 I totally forgot I can cut an internal ticket. Already being investigated by RM azure integration team. Sorry!

**Comment by izpavlovich** [comment]
This bug seems to be closed but I am seeing similar issue right now. Any information when the fix is going to be rolled out?

**Comment by kwontae** [comment]
@izpavlovich Something weird must've happened with our vscode settings because it removed all the `$` in our azure pipeline manifest and got committed with other commit. We used variables to define our `workingDirectory` and because it wasn't able to get the working directory, it couldn't locate the go executable. I would look into your azure pipeline and see if the working directory is being set to where your go is being installed.

**Comment by a8ree** [comment]
Also seeing this issue today

**Comment by xtez** [comment]
> @tejasd1990 I totally forgot I can cut an internal ticket. Already being investigated by RM azure integration team. Sorry!

Issue persists, reopening will help users to track the progress.

```
2020-12-24T23:12:21.0649124Z ##[section]Starting: Go Unit Testing
2020-12-24T23:12:21.0659997Z ==============================================================================
2020-12-24T23:12:21.0660341Z Task         : Go
2020-12-24T23:12:21.0660829Z Description  : Get, build, or test a Go application, or run a custom Go command
2020-12-24T23:12:21.0661128Z Version      : 0.3.2
2020-12-24T23:12:21.0661390Z Author       : Microsoft Corporation
2020-12-24T23:12:21.0661727Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/go
2020-12-24T23:12:21.0662129Z ==============================================================================
2020-12-24T23:12:21.2117838Z [command]/usr/bin/go test -v -cover
2020-12-24T23:12:21.2405140Z ##[error]The Go task failed with an error: Error: There was an error when attempting to execute the process '/usr/bin/go'. This may indicate the process failed to start. Error: spawn /usr/bin/go ENOENT
2020-12-24T23:12:21.2426441Z ##[section]Finishing: Go Unit Testing
```
