### ISSUE TITLE
Null credentials for Azure Container Registry?

### ISSUE THREAD

**Issue by MrCaracara** [microsoft/azure-pipelines-tasks#12177]
I have been experimenting with Azure DevOps to see if it would be the best fit for CI/CD in my department. However, I have encountered problems deploying containers to an Azure Web App.

I have a container in Azure Container Registry. Using the Azure CLI, as well as the Azure Portal, I am able to deploy said container to the Azure Web App without issues. The problem arises when the AzureRmWebAppDeploymentV4 task is executed from DevOps. This copies the reference to the new version of the app but seems to change the way authentication works, and whenever I navigate to the app's address I get an error and the log writes:

`ERROR - DockerApiException: Docker API responded with status code=InternalServerError, response={"message":"Get https://<my-registry>.azurecr.io/v2/<my-container>/manifests/<version>: unauthorized: authentication required"}`

The variables with the credentials remain unchained in the Web App service, but it seems like somehow the authentication mode is changed by this task.

Even though I lack knowledge of how these tasks work, I have been looking at the code, and I have found this line, which clearly shows that the way the credentials are handled has changed at some point.
https://github.com/microsoft/azure-pipelines-tasks/blob/c721a57e2e07dc4b6c3525848477eb8b34d8b95c/Tasks/AzureRmWebAppDeploymentV4/operations/ContainerBasedDeploymentUtility.ts#L191

My current workaround involves using the older AzureWebAppContainerV1 task (which is buried in the list available from the DevOps interface, unlike AzureRmWebAppDeploymentV4 which is recommended from the beginning). But this also requires deploying manually at least once, in order to set the variables that contain the credentials for the registry (DOCKER_REGISTRY_SERVER_USERNAME & PASSWORD). This is not the ideal approach.

**Comment by eaarora-ms** [comment]
> My current workaround involves using the older AzureWebAppContainerV1 task (which is buried in the list available from the DevOps interface, unlike AzureRmWebAppDeploymentV4 which is recommended from the beginning). 

@MrCaracara Hi, although AzureWebAppContainerV1 is buried in the list available from the DevOps interface as you said it is the recommended task to use as we are deprecating AzureRmWebAppDeploymentV4 due to its large set of use-cases. AzureWebAppContainerV1  is a relatively new task and will continue to have more enhancements. 

> But this also requires deploying manually at least once, in order to set the variables that contain the credentials for the registry (DOCKER_REGISTRY_SERVER_USERNAME & PASSWORD)

Please allow me some time to check this and get back to you.

**Comment by chperich** [comment]
@MrCaracara: Can you please set variable system.debug to true and share the diagnostic logs with us, so that we can debug the issue better.

**Comment by SumiranAgg** [comment]
Closing the issue due to lack of information required for debugging. Please feel free to re-open if required.
