### ISSUE TITLE
SqlAzureDacpacDeployment fails parsing complex passwords when connecting to Azure SQL

### ISSUE THREAD

**Issue by othierie** [microsoft/azure-pipelines-tasks#12180]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeployment  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  

Azure Pipelines - cannot provide more information

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Agent: Hosted, vmImage: 'vs2017-win2016'

## Issue Description

When using a complex password, SqlAzureDacpacDeployment fails to connect my Azure Sql server.
The issue was resolved using a more simple password, using only characters (as well a as A), numbers and a !. When using the complex password in other services, eg Azure Data Studio, everything works just fine.

example of complex passwords that failed:
r_9$#WHr$M63]k$r$M
+m+BH$C{3h;T@f\L
k9U`53{C8TaXKa.BmBET5y3Z5.t]>.7t?3]'Z@j[CH^~6{Ep<?'mAee8[gWA.p)b

error retrieved in azure devops
##[error]Login failed for user 'user-name'.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

### Task logs
2020-01-16T13:46:59.2149293Z ##[section]Starting: SqlAzureDacpacDeployment
2020-01-16T13:46:59.2236176Z ==============================================================================
2020-01-16T13:46:59.2236283Z Task         : Azure SQL Database deployment
2020-01-16T13:46:59.2236351Z Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
2020-01-16T13:46:59.2236430Z Version      : 1.156.1
2020-01-16T13:46:59.2236492Z Author       : Microsoft Corporation
2020-01-16T13:46:59.2236655Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment
2020-01-16T13:46:59.2236752Z ==============================================================================
2020-01-16T13:47:22.5217550Z Temporary inline SQL file: C:\Users\VssAdministrator\AppData\Local\Temp\tmp25D4.tmp
2020-01-16T13:47:22.5345179Z Invoke-Sqlcmd -connectionString "**********"  -Inputfile "C:\Users\VssAdministrator\AppData\Local\Temp\tmp25D4.tmp" 
2020-01-16T13:47:35.1122894Z Sql file: D:\a\1\project\SQL\prod\sql-file.sql
2020-01-16T13:47:35.1144099Z Invoke-Sqlcmd -connectionString "**********"  -Inputfile "D:\a\1\s\SQL\project\sql-file.sql" 
2020-01-16T13:47:35.5387816Z ##[error]Login failed for user 'user-name'.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
2020-01-16T13:47:35.6959464Z ##[section]Finishing: SqlAzureDacpacDeployment
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
##[error]Login failed for user 'user-name'.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
[Insert error from the logs here for a quick overview]

**Comment by chperich** [comment]
@othierie : Can you specify the authentication type you are using? Is it connection string or something else? If you are using, connection string, as a work around you can try switching to SQL server authentication. 

Can you set system.debug variable to true, create a release and share the verbose logs with us? You can also add "/Diagnostics:true" in the additional arguments.

**Comment by M198** [comment]
Suck my fat black duck bitch
________________________________

**Comment by CodedBeard** [comment]
I just ran into the same issue. When using the connection string method, a password containing special characters resulted in a failed login, even though the same connection string works fine when used from other systems. Swithching the password to not contain any special characters resolved the issue.

**Comment by 20shivangi** [comment]
@othierie I am unable to reproduce the issue. I also tried with complex passwords that you gave.

**Comment by othierie** [comment]
@20shivangi  that is weird, I used the default (automatic) agent for the pipeline, the password was passed as variable in azure devops. Dit you pass it as well as a variable?

**Comment by 20shivangi** [comment]
@othierie I used connection string as the method and passed password in the string only

**Comment by 20shivangi** [comment]
@othierie Please use the connection string and pass complex password in the string only, let me know if it works. It is working for me

**Comment by 20shivangi** [comment]
@othierie Any update here ?

**Comment by othierie** [comment]
@20shivangi 

I will try it later today and come back to you

**Comment by 20shivangi** [comment]
@othierie Please let me know if any update is there

**Comment by othierie** [comment]
@20shivangi 

I did the following tests:
-	 created two different sql servers in North Europe Location:
o	temp-test
o	testdiamond
-	created two times the Adventureworks sample data base (2GB – Basic)
o	temp-test/temp
o	testdiamond/temp
-	passwords used
o	k9U`53{C8TaXKa.BmBET5y3Z5.t]>.7t?3]'Z@j[CH^~6{Ep<?'mAee8[gWA.p)b
o	+m+BH$C{3h;T@f\L
-	In the template I used the ADO.net connection string and changed the {your_password} with the passwords stated above

Result: jobs are failing atm of connecting to the database:
Run 1 temp-test/temp
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: '############'
    AuthenticationType: 'connectionString'
    ConnectionString: 'Server=tcp:temp-test.database.windows.net,1433;Initial Catalog=temp;Persist Security Info=False;User ID=adminadmin;Password=k9U`53{C8TaXKa.BmBET5y3Z5.t]>.7t?3]''Z@j[CH^~6{Ep<?''mAee8[gWA.p)b;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.SourcesDirectory)/AdventureWorks/bin/AdventureWorks.dacpac'
    IpDetectionMethod: 'AutoDetect'


##[error]System.Management.Automation.RuntimeException: No resource found with serverName tcp:temp-test, serverType Microsoft.Sql/servers in subscription #################. Specify the correct serverName/serverType and try again.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

Run 2 testdiamond/temp
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: '##############'
    AuthenticationType: 'connectionString'
    ConnectionString: 'Server=tcp:testdiamond.database.windows.net,1433;Initial Catalog=temp;Persist Security Info=False;User ID=adminadmin;Password=+m+BH$C{3h;T@f\L;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.SourcesDirectory)/AdventureWorks/bin/AdventureWorks.dacpac'
    IpDetectionMethod: 'AutoDetect'

##[error]*** Error parsing connection string: Keyword not supported: 't@f\l;multipleactiveresultsets'.. 
##[error]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting- 


Run 3: same as run 2, but used {password} instead of the password. This failed as well


The production pipeline with a simple password is running fine.

**Comment by othierie** [comment]
@20shivangi 

I did the following tests:
-	 created two different sql servers in North Europe Location:
o	temp-test
o	testdiamond
-	created two times the Adventureworks sample data base (2GB – Basic)
o	temp-test/temp
o	testdiamond/temp
-	passwords used
o	k9U`53{C8TaXKa.BmBET5y3Z5.t]>.7t?3]'Z@j[CH^~6{Ep<?'mAee8[gWA.p)b
o	+m+BH$C{3h;T@f\L
-	In the template I used the ADO.net connection string and changed the {your_password} with the passwords stated above

Result: jobs are failing atm of connecting to the database:
Run 1 temp-test/temp
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: '############'
    AuthenticationType: 'connectionString'
    ConnectionString: 'Server=tcp:temp-test.database.windows.net,1433;Initial Catalog=temp;Persist Security Info=False;User ID=adminadmin;Password=k9U`53{C8TaXKa.BmBET5y3Z5.t]>.7t?3]''Z@j[CH^~6{Ep<?''mAee8[gWA.p)b;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.SourcesDirectory)/AdventureWorks/bin/AdventureWorks.dacpac'
    IpDetectionMethod: 'AutoDetect'


##[error]System.Management.Automation.RuntimeException: No resource found with serverName tcp:temp-test, serverType Microsoft.Sql/servers in subscription #################. Specify the correct serverName/serverType and try again.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

Run 2 testdiamond/temp
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: '##############'
    AuthenticationType: 'connectionString'
    ConnectionString: 'Server=tcp:testdiamond.database.windows.net,1433;Initial Catalog=temp;Persist Security Info=False;User ID=adminadmin;Password=+m+BH$C{3h;T@f\L;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.SourcesDirectory)/AdventureWorks/bin/AdventureWorks.dacpac'
    IpDetectionMethod: 'AutoDetect'

##[error]*** Error parsing connection string: Keyword not supported: 't@f\l;multipleactiveresultsets'.. 
##[error]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting- 


Run 3: same as run 2, but used {password} instead of the password. This failed as well


The production pipeline with a simple password is running fine.

**Comment by 20shivangi** [comment]
@othierie Which agent are you using : hosted agent or private one? If it is private one, can you please tell the version the sql package that you are using.

**Comment by othierie** [comment]
@20shivangi We are using the pool Azure pipelines so we don't have a private agent. as Image we used

```
pool: 
    vmImage: 'vs2017-win2016'
```

**Comment by ifehri177** [comment]
Hello, i am also facing the same issue with special characters in variable (SAS token, composed of @ = & characters.
I have yet to find a workaround, let me know if anyone has ! 
PS: shouldnt a system automatically parse a string?

**Comment by ruankr** [comment]
We've moved away from using most special characters as have also seen this issue. Another issue is that the passwords are being displayed in clear text in the logs, even if locked. Surely this shouldn't be the case?

**Comment by AmrutaKawade** [comment]
We have fixed this issue https://github.com/microsoft/azure-pipelines-tasks/pull/13728. it will be deployed within 2 weeks.
