### ISSUE TITLE
CocoaPods does not handle proxy configuration

### ISSUE THREAD

**Issue by Tarig0** [microsoft/azure-pipelines-tasks#12187]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: CocoaPods

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: OSX 10.14.4

## Issue Description

Agent is configured to run behind a proxy but the Cocoapods task is not proxy aware

### Task logs
```
Starting: Install Cocoa Pods
==============================================================================
Task         : CocoaPods
Description  : Install CocoaPods dependencies for Swift and Objective-C Cocoa projects
Version      : 0.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/cocoapods
==============================================================================
(node:32007) Warning: Use Cipheriv for counter mode of aes-256-ctr
/usr/local/bin/pod --version
1.8.4
/usr/local/bin/pod install
Analyzing dependencies
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
##[error]The process '/usr/local/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/bin/pod' failed with exit code 1
Finishing: Install Cocoa Pods
```
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by jerobarraco** [comment]
is still an issue

**Comment by anatolybolshakov** [comment]
Hi @Tarig0 @jerobarraco we are working on more prioritized issues at the moment, but going to get back to this one once be able to.

**Comment by kirill-ivlev** [comment]
Hi @Tarig0 @jerobarraco,
Those changes were merged and released could you please check, now this task should correctly handle proxy configuration.
Please let us know if you face issues

**Comment by jerobarraco** [comment]
Thanks @kirill-ivlev  That's good news :) Sorry but i'm not working on that project (or company) anymore.
