### ISSUE TITLE
npm install fails ENOENT: no such file or directory (.staging directory)

### ISSUE THREAD

**Issue by flopes89** [microsoft/azure-pipelines-tasks#12195]
## Required Information
*Type*: Bug
**Enter Task Name**: npmV1

## Environment
- Server - Azure Pipelines 
    
- Agent - Hosted: Azure Pipeline / Hosted ubuntu 18.04

## Issue Description

npm install fails on every build

### Error logs

[tasklog.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4103619/tasklog.txt)

**Comment by flopes89** [comment]
When deleting the `package-lock.json` the build works reliably without error. But that can hardly be the desired workaround as it completely defeats the purpose of having a lock file.

**Comment by christerengman** [comment]
I've been directed to this issue by Microsoft support (issue 119121024001007) but I'm not sure it's related:

1. `npm ci`
1. `npm ci --production`
1. `DeleteFiles@1` fails with: `Unhandled: Failed find: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/node_modules/.bin/_mocha'`

This started as Microsoft introduced Azure Functions v3 with support for Node 12, so with started pinpointing Node/npm versions using `NodeTool@0`:

* Disabled = Default = 12.13.1/6.13.2 - Failed
* ~10 = 10.18.1/6.13.4 - Failed
* 10.17.0 = 10.17.0 /6.11.3 - OK!

Haven't investigated Node 12 versions yet...

**Comment by stephenmichaelf** [comment]
This seems to be an NPM issue not a task issue:

https://github.com/WordPress/gutenberg/issues/9474

https://stackoverflow.com/questions/38143558/npm-install-resulting-in-enoent-no-such-file-or-directory

@flopes89 Can you try the suggested solutions and let me know? Also, was this working before and randomly started failing?

@christerengman I am not sure if it's related, it doesn't seem to be at this moment but I am still investigating.

**Comment by flopes89** [comment]
The *"solutions"* in anything I found online are not actually solutions

- `npm init` doesn't solve the problem inside azure
- *Delete package-lock.json* works but is a very weak workaround as the package-lock.json is an important file that shouldn't need to be deleted
- `rm -rf node_modules && npm cache clean --force` also doesn't work
- If you follow the other threads you can see that none of this solves the underlying problem, which is still undetected by anyone

It was working before, yes. Now it fails every time. I have now resorted to locking down versions inside the `package.json` but that defeats the purpose of having a lock file.

I agree that this is not an issue isolated to Azure DevOps pipelines, but even within the npm project this issue is completely unsolved.

**Comment by christerengman** [comment]
After troubleshooting with @stephenmichaelf we fixed our problem using `npm prune --production` instead of `npm ci --production`. Reason probably being that `ci` is asynchronous while `prune` is synchronous. Don't know if it helps you @flopes89 but might be valuable information for you and anyone else. :)

Thank you @stephenmichaelf !

**Comment by flopes89** [comment]
@christerengman I'll sure give it a try

**Comment by kolya182** [comment]
Having the same issue here https://dev.azure.com/TrustWallet/Assets/_build/results?buildId=19868&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997 `package.json` and `package-lock.json` are checked in repo.
Tried: `npm install` via Task and `-script`, `npm ci`,  node 10.x, 11.x, 12.x

**Comment by leoskyrocker** [comment]
@christerengman Aren't `npm ci` and `npm prune` doing completely different things? `npm ci` installs versioned packages in `package-lock.json` to node_modules while `npm prune` removes packages from node_modules?

**Comment by cmcnicholas** [comment]
any fix for this, we are also experiencing the problem?

**Comment by coreyperkins** [comment]
Experiencing the same issue. Everytime I try to use a Microsoft product....grr....

**Comment by PaulVrugt** [comment]
same issue here.....every once in a while it fails

**Comment by deanilvincent** [comment]
same issue using this sample `azure-pipelines.yml`
it fails in the `npm install` line. it says, `##[error]Error: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/WebUi/angular`
```
variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: WebUi/angular

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: WebUi/angular

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'WebUi/angular/dist'
```

**Comment by acaravia** [comment]
I'm having same issue different error (see below). It works if I delete package-lock.json but as of yesterday my builds started building different so I decided to include package-lock.json again to see if it would resolve it but this came up.

error code EINTEGRITY
error sha1-zsDyXALIIS7WvG3n7w54QAmEhs0= integrity checksum failed when using sha1: wanted sha1-zsDyXALIIS7WvG3n7w54QAmEhs0= but got sha512-ZUEcjQIMvD1I/nXBDWZY5szciMk83aWvDtyUonD8QMEuvPAiX1ViZH9IgrSJAtOlr3bdm3O6wlWKHUHSBS7F+Q== sha1-Cp0zDcOS+rDj13WkI1i7zUOrpNk=

**Comment by Zanatta99** [comment]
Hi guys, I find a solution, in you pipeline you have to add the task 'Node.js tool installer' after CocoaPods install task and the build we'll be successful.

**Comment by snpdev** [comment]
Same problem today. I had no problem running my pipeline on May 4, 2020. Interestingly, I specify Azure Pipelines Image `ubuntu-18.04` but the pipeline actually uses `ubuntu-16.04`. I'll try again later.

**Phase 1**
```
Pool: Azure Pipelines
Image: ubuntu-16.04
Agent: Hosted Agent
```

**The error in task Build an image**
```
##[error]Unhandled: Failed find: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/docroot/sites/default/files'
```

**Comment by gethari** [comment]
Hi Team, We are facing this randomly on our VSTS hosted agent today.  This is the final error message we get

```
19681 error code ENOENT
19682 error syscall spawn git
19683 error path git
19684 error errno ENOENT
19685 error enoent Error while executing:
19685 error enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
19685 error enoent
19685 error enoent
19685 error enoent spawn git ENOENT
19686 error enoent This is related to npm not being able to find a file.
19687 verbose exit [ 1, true ]

##[debug]Agent.BuildDirectory=C:\agent\_work\2
##[debug]rm -rf C:\agent\_work\2\npm
##[debug]removing directory
##[debug]task result: Failed
##[error]Error: Npm failed with return code: 1

```

**Comment by gethari** [comment]
HOLY SHIT, After 2 hours of reading various threads back and forth [this answer](https://stackoverflow.com/a/18020195/8368871) fixed my issue.

**Comment by himanshush13** [comment]
@gethari  did you only add .npmignore file only ? because that doesn't solve my issue. The error is same.

**Comment by gethari** [comment]
> @gethari did you only add .npmignore file only ? because that doesn't solve my issue. The error is same.

@himanshush13 It did resolve the issue for time being for one or two days. Today we are facing this issue again ! 😟

**Comment by gethari** [comment]
## UPDATE 

I don't know if this is the right solution. I downgraded Angular CLI to `8.3.23` and it did resolved my issue, and also we were using a build step called `NODE` we removed it and installed node directly on the server

**Comment by omokoh** [comment]
Hi,

Are you still experiencing this issue?

Thanks

**Comment by OMO-NOSA** [comment]
@omokoh  Sure. i am currently experiencing same issue from my end.

**Comment by PaulVrugt** [comment]
Updating to npm 7 solved the issue for me

**Comment by ssensegar** [comment]
> Updating to npm 7 solved the issue for me

Same for me as well.

**Comment by alexweininger** [comment]
Experiencing this issue as well. @ssensegar or @PaulVrugt what exact version of npm 7? And were you installing that in your dev environment or somehow forcing the pipeline agent to use npm 7?

**Comment by PaulVrugt** [comment]
@alexweininger installing npm7 locally doesn't make sense since the error occurs in the pipeline. You can install npm7 during the pipeline process by using the following task before any npm command:
```

  - task: Npm@1
    displayName: 'Install npm 7'
    inputs:
      command: 'custom'
      workingDir: $(Build.Repository.LocalPath)
      verbose: false
      customCommand: 'i -g npm@next-7'
```

**Comment by alexweininger** [comment]
@PaulVrugt Thanks, I just tried adding that to my .yml and that task fails with the following error:

```
941 verbose stack Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/abbrev'
942 verbose cwd /home/vsts/work/1/s
943 verbose Linux 5.4.0-1032-azure
944 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "npm@next-7"
945 verbose node v14.15.1
946 verbose npm  v6.14.9
947 error code EACCES
948 error syscall access
949 error path /usr/local/lib/node_modules/npm/node_modules/abbrev
950 error errno -13
951 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/abbrev'
951 error  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/abbrev'] {
951 error   errno: -13,
951 error   code: 'EACCES',
951 error   syscall: 'access',
951 error   path: '/usr/local/lib/node_modules/npm/node_modules/abbrev'
951 error }
```

I'm not sure what's happening here.

**Comment by lndr27** [comment]
I'm facing the same issue. The problem seems to happen randomly.

I've tried adding a step to clear npm cache forcefully, but it didn't help.

Deleting ```package.lock.json``` does help, but I don't think it's an acceptable solution.

**Comment by henrycity** [comment]
> I'm facing the same issue. The problem seems to happen randomly.
> 
> I've tried adding a step to clear npm cache forcefully, but it didn't help.
> 
> Deleting `package.lock.json` does help, but I don't think it's an acceptable solution.

Have you found out how to fix it? I have the same issue as well.

**Comment by dcorns** [comment]
If you notice that along with the problem that you get this error: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it! Then this link may help you.[https://stackoverflow.com/questions/64813775/is-there-any-way-to-fix-package-lock-json-lockfileversion-so-npm-uses-a-specific](url)

**Comment by songpr** [comment]
> After troubleshooting with @stephenmichaelf we fixed our problem using `npm prune --production` instead of `npm ci --production`. Reason probably being that `ci` is asynchronous while `prune` is synchronous. Don't know if it helps you @flopes89 but might be valuable information for you and anyone else. :)
> 
> Thank you @stephenmichaelf !

Thanks for your solution `npm prune --production` is work for me too.
We use npm prune after 

- `npm install`
- run test
- publish test case
- `npm prune --production`, to left only production module
