### ISSUE TITLE
kubectl inserts configMap key of the configMap filename and value of entire configMap content as a string 

### ISSUE THREAD

**Issue by Morgma** [microsoft/azure-pipelines-tasks#12206]
*Type*: Bug

**Task Name**: kubectl

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesV1

## Environment
- Azure Pipe Lines Release
    
- Agent - Hosted:
     - agent queue name: Ubuntu-18.04

Specifying that the task use the _latest_ version of kubectl and with parameters for the configMap file name and path:
![image](https://user-images.githubusercontent.com/887392/73104003-ff858100-3eba-11ea-9380-42e19c11acc1.png)

I find that in AKS, the configMap actually has one additional key:value - the key being the configmap filename (e.g. configmap.yaml) and the value being the full json string of the configmap itself. 

I wouldn't care, but this actually breaks IIS Windows container images because the Service Monitor does not like that value being stuck in an environment variable, so you get something like:

```
Service 'w3svc' has been stopped
APPCMD failed with error code XXX
Failed to update IIS configuration
```
The pod will fail to initialize until the erroneous configMap value is removed and the environment variables refresh on the pod's next restart attempt.

There are not any errors from the pipeline task or k8s - everything appears to be syntactically correct; so this may just be a consequence for Windows nodes, but I imagine it's bad form to insert additional values into the configMap or at offer some other means of preventing it.

**Comment by ds-ms** [comment]
Closing stale issue. Feel free to reopen if the problem still persists.

**Comment by span** [comment]
This is still an issue.

It seems to be a problem with how the `useConfigurationFile` property is interpreted.

I thought I could use a yaml file with a configmap but that results in the whole configmap as a string mapped to the filename. After reading up on `create configmap` I realize it is not applicable on `yaml` files with a `ConfigMap` definition. All the examples a k8s.io uses property files.

When having a `yaml` file the correct command would be `apply -f <filename>`.

Perhaps filename could be restricted to help usage.

**Comment by shigupt202** [comment]
@span There are multiple ways to create config maps in Kubernetes, and in some of these methods files are used in different ways. This might have created some confusion as you have correctly explained above.
With one of the methods (which is shown in the image in issue description), a config map with file name as the key and content as the value gets created. So, the content of the file is supposed to be key value pairs and not a kubernetes resource definition of kind config map. More information about this method can be found [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-the-key-to-use-when-creating-a-configmap-from-a-file).
If you already have a manifest file of kind config map, then all you need to do is run `kubectl apply -f <config file path>`on the file. 
All these methods are explained clearly along with examples in the Kubernetes documentation. Adding the [doc reference](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) here in case some one else faces similar confusion in future.
@span I'm not very sure what the confusion is with `useConfigurationFile`. If you think we need better explanation for it in our documentation, you can open a new issue raising this concern. 😄

**Comment by StephanZaat** [comment]
@shigupt202 The main confusion comes from the expectation vs. the documentation.
I was also hoping to replace my inline environment variables in my manifest files with a configmap file with parameters that is idempotent.
The current ADO Pipeline task only supports --from-file instead of --from-env-file as far as I can tell.
The --from-file option puts the entire content of the supplied file as-is in the Data field in the configmap. 
The --from-env-file option parses the parameters in the content and transforms it to individual fields in the Data field in the configmap. That is my preferred approach. But perhaps I have to invest my time in Kustomization.

The problem with `kubectl apply -f <config file path>` is that it can only be run once. Subsequently an error is given that the configMap already exists. That does not work in an idempotent pipeline. An override function would be great. The ConfigMaps task in Azure seems to have that function (checkbox), but with the --from-file option this is not very useful.

**Comment by shigupt202** [comment]
@StephanZaat That sounds like a fair point. However, we cannot change the behaviour of Configmap file as that would break back compat. But we can consider adding a new input to support `--from-env-file` if this is something that a lot of users want.
@anraghun Do you think we can do something about the documentation? We can probably mention that underneath this will be running `--from-file` which means the content of the file will be used as value.

**Comment by anraghun** [comment]
@StephanZaat I've called out in the documentation that the task will use `--from-file` for clarity.

**Comment by StephanZaat** [comment]
@shigupt202 I understand you cannot change the behaviour. I believe I've tried all the options of the kubectl task, but is there another solution to solve my use case?
At this point I am tempted to work with kubectl delete configmap / kubectl create configmap, which is not great.

**Comment by shigupt202** [comment]
@StephanZaat You can use `create` command of Kubernetes task and give the other parameters in `arguments` input of the task, something like this:
![image](https://user-images.githubusercontent.com/57620559/98155813-ddfefe80-1efc-11eb-9099-e2e74103354b.png)

**Comment by StephanZaat** [comment]
Yes, that would work, but does not make it idempotent in a pipeline.
So I'll need to do a delete / create anyway in 2 tasks, which I believe is the same functionality as this Force option:
![image](https://user-images.githubusercontent.com/15195218/98233180-edaf2f00-1f5e-11eb-9f9d-3e48500c32e9.png)

The common workaround does not seem to work within a ADO task:
`kubectl create secret generic my-secret --from-literal=foo=bar --dry-run -o yaml | kubectl apply -f -`
