### ISSUE TITLE
FTP Upload task v2 fails with 550 The system cannot find the path specified.

### ISSUE THREAD

**Issue by kjng** [microsoft/azure-pipelines-tasks#12204]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: FtpUploadV2

## Environment
- Server - Azure Pipelines

- Agent - Hosted VS2017

## Issue Description

When using the FTP Upload task v2, the task connects and uploads 1 file, but throws a 550 error and fails before the entire upload completes. This occurs on both FTP and FTPS.

### Error logs

> 2020-01-24T15:49:23.3436977Z connected: 220 Microsoft FTP Service
> 2020-01-24T15:49:23.3751430Z removing remote directory contents: site/wwwroot
> 2020-01-24T15:49:23.3835804Z ##[warning]FTPError: 550 The system cannot find the path specified.
> 2020-01-24T15:49:24.3820092Z connecting to: waws-prod-blu-027.ftp.azurewebsites.windows.net:21
> 2020-01-24T15:49:24.4556085Z connected: 220 Microsoft FTP Service
> 2020-01-24T15:49:24.5248063Z files uploaded: 0, directories processed: 1, total: 1, remaining: 41, remote directory successfully created/verified: site/wwwroot
> 2020-01-24T15:49:24.5322203Z ##[warning]FTPError: 550 The system cannot find the path specified.
> 2020-01-24T15:49:25.5452688Z connecting to: waws-prod-blu-027.ftp.azurewebsites.windows.net:21
> 2020-01-24T15:49:25.5705959Z connected: 220 Microsoft FTP Service
> 2020-01-24T15:49:25.5772668Z File: site/wwwroot/filename.txt Type: upload Transferred: 0
> 2020-01-24T15:49:25.5784120Z File: site/wwwroot/filename.txt Type: upload Transferred: 26751
> 2020-01-24T15:49:25.5828922Z files uploaded: 1, directories processed: 1, total: 2, remaining: 40, successfully uploaded: D:\a\r1\a\filename.txt to: site/wwwroot/filename.txt
> 2020-01-24T15:49:25.6053917Z files uploaded: 1, directories processed: 2, total: 3, remaining: 39, remote directory successfully created/verified: site/wwwroot/assets
> 2020-01-24T15:49:25.6416557Z files uploaded: 1, directories processed: 3, total: 4, remaining: 38, remote directory successfully created/verified: site/wwwroot/assets/images
> 2020-01-24T15:49:25.6484090Z ##[warning]FTPError: 550 The system cannot find the path specified.
> 2020-01-24T15:49:26.6547171Z connecting to: waws-prod-blu-027.ftp.azurewebsites.windows.net:21
> 2020-01-24T15:49:26.6773996Z connected: 220 Microsoft FTP Service
> 2020-01-24T15:49:26.6840416Z ##[warning]FTPError: 550 The system cannot find the path specified.
> 2020-01-24T15:49:27.6936983Z connecting to: waws-prod-blu-027.ftp.azurewebsites.windows.net:21
> 2020-01-24T15:49:27.7161000Z connected: 220 Microsoft FTP Service
> 2020-01-24T15:49:27.7235810Z ##[warning]FTPError: 550 The system cannot find the path specified.
> 2020-01-24T15:49:28.7348560Z connecting to: waws-prod-blu-027.ftp.azurewebsites.windows.net:21
> 2020-01-24T15:49:28.7551626Z connected: 220 Microsoft FTP Service
> 2020-01-24T15:49:28.7556094Z ##[error]FTPError: 550 The system cannot find the path specified.
> 2020-01-24T15:49:28.7556819Z 
> 2020-01-24T15:49:28.7557191Z host: waws-prod-blu-027.ftp.azurewebsites.windows.net
> 2020-01-24T15:49:28.7557339Z path: site/wwwroot
> 2020-01-24T15:49:28.7557486Z files uploaded: 1
> 2020-01-24T15:49:28.7557615Z directories processed: 3
> 2020-01-24T15:49:28.7557772Z unprocessed files & directories: 38
> 2020-01-24T15:49:28.7558310Z ##[error]Ftp Upload failed
> 2020-01-24T15:49:28.7582497Z disconnecting from: waws-prod-blu-027.ftp.azurewebsites.windows.net

**Comment by Turnerj** [comment]
This might be a long shot but I recently had the same issue (550s and 553s) which led to half my website being deployed as well as some weird nesting of my remote directory folder within itself. I fixed it by changing my remote directory to have a slash at the beginning. I didn't need it previously - something has changed since September 18th last year - the date of my last successful release.

**Comment by vivekbm1** [comment]
@Turnerj - Can you please share the format of the address that worked for you? I seem to be having these issues persistently and I am unable to make any progress.

**Comment by Turnerj** [comment]
Not sure if this helps @vivekbm1 - this screenshot is the revision history for my release pipeline. Left before, right after - the after is what I had where it started working. (Note: I also went up in FTP task version from v1 to v2)

![image](https://user-images.githubusercontent.com/904226/90015158-5e8bd580-dce7-11ea-8a56-8949fc775bd4.png)

I can't show you what it looks like via the UI as I've since stopped deploying via FTP.

**Comment by jrpacheco** [comment]
I have been going through the same problem. Some files and folders in the build were not going to my FTP server.
I added a bar before the destination folder and everything was resolved.

![image](https://user-images.githubusercontent.com/6079514/102648178-f2225680-415e-11eb-8478-8a7e1ac5917a.png)

**Comment by marceloaugusto80** [comment]
> I have been going through the same problem. Some files and folders in the build were not going to my FTP server.
> I added a bar before the destination folder and everything was resolved.
> 
> ![image](https://user-images.githubusercontent.com/6079514/102648178-f2225680-415e-11eb-8478-8a7e1ac5917a.png)

we were also having issues with the ftp task returning code 550 and making a mess with the folder structure.

the solution provided by @jrpacheco solved the problem.

thanks, brother.

![azure-pipeline](https://user-images.githubusercontent.com/36957419/117598543-66fe2900-b11e-11eb-845f-f674313b627f.jpg)
