### ISSUE TITLE
[k8s] Kubectl pass file to exec

### ISSUE THREAD

**Issue by patsadow2** [microsoft/azure-pipelines-tasks#12217]
Hello, 

Is it possible to pass somehow file to kubectl exec ?

I need to make something like: 

cat mssql.json | kubectl exec -i my-cluster-kafka-0 -- curl -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://my-connect-cluster-connect-api:8083/connectors -d @-

I am not sure how should i handle it ?

When i use -d azure pipeline trim it in wrong

![image](https://user-images.githubusercontent.com/19226186/73171319-c9394300-4100-11ea-947d-2e35bd492e68.png)

**Comment by shigupt202** [comment]
@patsadow2 Which task are you using to execute this command?

**Comment by shigupt202** [comment]
Closing stale issue. Feel free to reopen the issue if the problem persists.
