### ISSUE TITLE
Bash script task seems to be using PowerShell executables all of a sudden

### ISSUE THREAD

**Issue by bddckr** [microsoft/azure-pipelines-tasks#12221]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: bash

## Environment
- Agent - Hosted, running all jobs on `windows-latest`.

## Issue Description

Running a `find` command in a `bash` task has been working fine as part of a weekly run (Monday, 00:00 UTC) until this Monday morning.

Instead of bash's `find` being used it looks like PowerShell's `find.exe` is used now as we're getting this error message with the failed `find` bash script run now:
```
FIND: Parameter format not correct
```
AFAIK this means `find.exe` has been used. Previously this worked without issues, so I assume something in the PATH changed so now `find` somehow gets routed to `find.exe`, **even though this is running in a `bash` script task**.

### Task logs

```
Starting: Run tool
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.159.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
find "d:\a\1\s/artifacts/build/bin/Release" -iname "something.dll" -exec dotnet {} "d:\a\1\s/src/something/somethingelse" \;
"C:\Program Files\Git\usr\bin\bash.exe" --noprofile --norc -c pwd
/d/a/_temp

========================== Starting Command Output ===========================
"C:\Program Files\Git\usr\bin\bash.exe" --noprofile --norc /d/a/_temp/a6e0c270-13b5-4d1e-960f-4accfdfee2a7.sh
FIND: Parameter format not correct

##[error]Bash exited with code '2'.
Finishing: Run tool
```

**Comment by bddckr** [comment]
I just switched to use `ubuntu-latest` (with no other changes to the pipeline as it was already cross-platform thankfully), which resolves this issue for us.

**Comment by jtpetty** [comment]
This is actually a known bug with the hosted windows agent. The issue is https://github.com/actions/virtual-environments/issues/263

**Comment by bddckr** [comment]
@jtpetty Thanks for the quick follow-up.

Just to confirm: The linked issue is also the reason we're getting this on Azure Pipelines? The linked repo is for GitHub Actions, though I understand the two services share a bunch of things under the hood.

**Comment by jtpetty** [comment]
@bddckr - Yes, GitHub Actions and Azure Pipelines are sharing the same hosted images now and that is being developed under actions/virtual-environments.
