### ISSUE TITLE
File transform Task: Readme.md for Version 2 task was not updated.

### ISSUE THREAD

**Issue by majorimi** [microsoft/azure-pipelines-tasks#12234]
File transform: Readme file for Version 2 task was not updated. It shows V1 configs and settings. Which makes hard to use this Task. Here is the link: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/FileTransformV2/README.md

**Comment by eaarora-ms** [comment]
It's updated now. Thanks for pointing this out.

**Comment by majorimi** [comment]
Ok thanks for the update.
