### ISSUE TITLE
PublishCodeCoverageResults is it possible to sort results?

### ISSUE THREAD

**Issue by shelbypereira** [microsoft/azure-pipelines-tasks#12259]
## Required Information
*Type*: Feature/Question
**Enter Task Name**: PublishCodeCoverageResults

## Environment

- Server - Azure Pipelines
## Issue Description
Generally wen I use code coverage I would like to quickly identify the lines that are not covered so I like to sort by % lines uncovered per class or namespace descending.  On my computer I use the reportgenerator tool to accomplish this.  On Devops PublishCodeCoverageResults sorts the results alphabetically,  which is not very useful especially for larger projects with many classes.

It would be useful to have some sort options for this tasks or alternatively be able to sort directly on the outputted page (similar to what the reportgenerator tool does locally).

**Comment by nehacodes** [comment]
@shelbypereira This is a valid ask and this enhancement will be in our backlog.
