### ISSUE TITLE
MSBuild/PowerShell Task Errors, Code -65536, Exception thrown from System.Management.Automation.Runspaces.InitialSessionState

### ISSUE THREAD

**Issue by iwsummers14** [microsoft/azure-pipelines-tasks#12269]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MSBuild, PowerShell

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
              On-Premises
    - If using TFS on-premises, provide the version: 
              17.153.29522.3 (AzureDevOps2019.Update1.1)
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
                N/A

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
             Windows 10, agent versions 2.153.1, 2.163.1
## Issue Description

[Include task name(s), screenshots and any other relevant details]

Failures happening with no discernible pattern when running tasks MSBuild and PowerShell.
This issue started after we upgraded agents from 2.136.1 to v 2.153.1 and 2.163.1. Issue is happening on both 2.153.1 and 2.163.1.   Affecting an agent pool that runs in interactive (auto-login) mode.

Error thrown is an exception with System.Management.Automation.Runspaces.InitialSessionState.
Oddly it appears to write to console like a char array:

W i n d o w s P o w e r S h e l l t e r m i n a t e d w i t h t h e f o l l o w i n g e r r o r : 

 T h e t y p e i n i t i a l i z e r f o r ' S y s t e m . M a n a g e m e n t . A u t o m a t i o n . R u n s p a c e s . I n i t i a l S e s s i o n S t a t e ' t h r e w a n e x c e p t i o n .

This affects MSBuild tasks primarily; but also PowerShell script tasks that we have in our environment as well.  Not limited to any one job, we are seeing it come up on Build and Release pipelines across multiple jobs, but definitely more frequently on Build pipelines.

We found this issue which had been closed, and disabled our antivirus policy; however, uninstalling antivirus completely is not an option.  https://github.com/Microsoft/azure-pipelines-tasks/issues/8988
AV provider is Carbon Black.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Windows PowerShell terminated with the following error: 
The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
Process completed with exit code -65536 and had 1 error(s) written to the error stream.

**Full error:**
```
Exit code -65536 returned from process: 
file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', 
arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command 
". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\MSBuild.ps1'''))"'.
```
```
Exit code -65536 returned from process: 
file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', 
arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command 
". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\MSBuild.ps1'''))"'.
```

**Excerpt from diagnostic log:**
```
[2020-01-31 13:49:19Z ERR  StepsRunner] Caught exception from step: Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: 
Exit code -65536 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\MSBuild.ps1'''))"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

**Comment by iwsummers14** [comment]
[Worker_20200131-134624-utc.log](https://github.com/microsoft/azure-pipelines-tasks/files/4139999/Worker_20200131-134624-utc.log)

Full Diagnostic log (from agent/_diag) that was excerpted above

**Comment by iwsummers14** [comment]
On the machines suffering from this issue I have run the following commands to verify system file integrity:

dism.exe /Online /Cleanup-Image /RestoreHealth
sfc /scannow

**Comment by iwsummers14** [comment]
[logs_48151.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4160490/logs_48151.zip)

**Comment by iwsummers14** [comment]
Closing because pattern was finally isolated.  After updating agent from 2.136.1 to 2.153.1,  any build with the configuration value directly set to "Any CPU" in the TFS Configuration field would eventually experience this error.  Once the "Any CPU" value is placed in a variable, such as $(BuildPlatform), and referenced for the configuration, this error stops occurring.

Importantly, this did not happen on every run, but once it did happen, would happen over and over again until the system was restarted.  The error would also happen on other PowerShell tasks that were not MSbuild, VSBuild, or custom PowerShell.

**Comment by box57l** [comment]
@iwsummers14 I am experiencing the exact same issues with with a powershell script task, running agent versions 2.153.1 or 2.170.1. Can you detail exactly what your workaround was?

**Comment by iwsummers14** [comment]
@box57l  Our issues are still occurring but at WAY less frequency after I stored all build argument values in build variables.  The issue still occurs on maybe 1-2% of our builds, and I have a custom API that I set up to requeue builds. I send build failures to my API with a webhook and a controller parses the error text from the payload.

Look at your build definitions, and anywhere you are specifying values, particularly values with spaces, put that value into a build variable and reference the variable instead.  For me, the bulk of the errors came from MSBuild or VSBuild tasks, on the  Configuration value, where "Any CPU" was typed into the field. Moving this value to a variable was the first step. For complex custom PowerShell tasks with multiple parameters, I placed the entire argument list into a build variable and passed that instead.

**Comment by aricamf** [comment]
This issue was still reproducible with 2.175.2   It failed very often when running powershell task in the release/build pipeline of azure devops.

**Comment by iwsummers14** [comment]
@aricamf I experienced it up until 2.181.0. Since updating to 2.181.0, I have not had any recurrence of this error.

**Comment by AJH16** [comment]
We get these issues on 2.194.  Also using Carbon Black.

**Comment by MANMOHAN1998** [comment]
Windows PowerShell terminated with the following error:
 The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.

how to resolve this error please help.
