### ISSUE TITLE
AzureCLI doesn't respect the powerShellIgnoreLASTEXITCODE argument

### ISSUE THREAD

**Issue by kbattocchi** [microsoft/azure-pipelines-tasks#12266]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI

## Issue Description

According to the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops), AzureCLI is supposed to support an argument `powerShellIgnoreLASTEXITCODE` which defaults to false, so that the last error code from the script should be returned as the script's exit code.  However, this doesn't happen.

I believe that this is because `getInput` is used instead of `getBoolInput` here:

https://github.com/microsoft/azure-pipelines-tasks/blob/9ecd46f69ce48ef68fef9ef6020c2363fdeb05ee/Tasks/AzureCLIV2/src/Utility.ts#L59

As a result, for the time being it is possible to work around this by using `''` instead of `false` (which will be passed through directly as a falsy string) for the time being; however it means that the default value of `false` is actually treated as the truthy string `"false"` and so the default behavior is not as described in the docs.

**Comment by jalajmsft** [comment]
Hey @kbattocchi thank you for reporting this issue. We will have a look and get back to you.

**Comment by jalajmsft** [comment]
This is fixed and will be deployed to all rings by next week.

Closing this for now. Feel free to re-open for further queries.
