### ISSUE TITLE
Mix of agent operating systems makes "Azure App Service Deploy" task fail

### ISSUE THREAD

**Issue by danielstocker** [microsoft/azure-pipelines-tasks#12272]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines or TFS on-premises?
    *Azure Pipelines*
    - If using TFS on-premises, provide the version: 
          N/A
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
         Account Name: *dasto*
         Project Name: *Demo Project*
         Build Definition Name: *Windows Build*
         Build Number: 20200201.1
         Release Definition Name: *Linux Release*
         Release Number: 77

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:
      vs2017-win2016 -> for build
      ubuntu-18.04 -> for release

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
       N/A

## Issue Description

When mixing agent operating system between build and release phases then the Azure App Service Deploy task completes successfully, but the deployment doesn't actually work. 

Task Output: 
![image](https://user-images.githubusercontent.com/9444698/73596895-a4890500-451e-11ea-8e6f-9acf678787bc.png)

Post Deploy: 
![image](https://user-images.githubusercontent.com/9444698/73596890-88856380-451e-11ea-997d-dd11a53b3d56.png)

### Task logs

https://logstorda.blob.core.windows.net/stor/ReleaseLogs_77.zip

## Troubleshooting
No failure as per description - see logs above

### Error logs
as above

**Comment by danielstocker** [comment]
I believe the task should fail in this scenario, but not sure if this is easy to implement

**Comment by eaarora-ms** [comment]
@danielstocker  I am afraid I do not understand what you're trying to say here:
1. The build and release pipelines have the same functionality overall (the difference being in the build and release variable names).
2. From the info you've provided, I can deduce that you're executing two different pipelines (build and release) with two different agents. But why is it supposed to fail?  The two pipelines are independent of each other.

To understand the issue better can you please also upload the build pipeline?

**Comment by danielstocker** [comment]
Hi @eaarora-ms 

Sorry for not being very clear. Here are the build logs as well:
https://logstorda.blob.core.windows.net/stor/logs_783.zip

I understand point (1) and can also confirm the behaviour in a build with multiple phases that run on different agent types and/or a YAML multi-stage pipeline with stages that use different agent types. 

Let me try and explain the core issue that I am noticing in a different way. 

The following steps end up deploying the web app correctly
- Build the web package using a windows agent
- Use a windows agent to deploy the web package using AzureRmWebAppDeploymentV4

If both steps are performed on a Linux agent they also work. 

If the steps are performed on different operating systems (for example in this case: build on Windows but deploy on Linux) then the AzureRmWebAppDeploymentV4 task completes successfully (like in my example) but the web app does not actually deploy. If I navigate to it, it still shows the "getting started" page. 

I would expect to see an ASP.NET core sample page (demo solution I'm using) rather than the "Getting Started" page. 

This is why I feel like running this task if the web package comes from an agent of a different operating system should fail as the deployment result isn't successful.

**Comment by eaarora-ms** [comment]
@danielstocker Web packages created using MSBuild task (with default arguments) have a nested folder structure that can only be deployed correctly by Web Deploy. If Run From Package is used for the above packages, the web package would be copied without honoring the nested folder structure and can cause runtime issues. That is why it is not supposed to fail however is not able to deploy the package correctly.

So if you want to have a windows agent for both build and release you can set 'Agent.OS' as 'Windows_NT' in Demands under the Agent Job section in the pipeline. 

Please let us know if you've any further questions.

**Comment by eaarora-ms** [comment]
Wiki link: https://github.com/Microsoft/azure-pipelines-tasks/wiki/Migrating-from-Web-Deploy-to-Run-From-Package-deployment-mechanism
