### ISSUE TITLE
FileTransformV2: Reporting Error even though variable value successfully replaced

### ISSUE THREAD

**Issue by MattEvansA45** [microsoft/azure-pipelines-tasks#12277]
## Type
- Bug

## Task Name
- FileTransformV2   

## Environment
- Server - Azure Pipelines 
- Agent - Hosted Windows 2019 with VS2019
    
## Issue Description
We are trying to replace a connectionstring value in the appsettings.json file in our project with a variable value.
We have defined a pipeline variable with the correct naming ie ConnectionStrings.DB and the value we wish to replace it with

The File transform task is configured in our pipeline as follows
```
- task: FileTransform@2
  inputs:
    folderPath: '$(Build.ArtifactStagingDirectory)\MetadataManager.FunctionalTests'
    jsonTargetFiles: 'appsettings.json'
```
the pipeline runs successfully and the variable value is successfully changed in the file but the task reports the following error
```
**##[error]Unable to apply transformation for the given package - Changes are already present in the package.**
Applying JSON variable substitution for appsettings.json
Applying JSON variable substitution for d:\a\1\a\MetadataManager.FunctionalTests\appsettings.json
Substituting value on key DB with (string) value: Server=<nameremoved>;Database=<nameremoved>;Trusted_Connection=true;
JSON variable substitution applied successfully.
##[section]Finishing: FileTransform
```
![image](https://user-images.githubusercontent.com/41288088/73644514-7239ed80-466d-11ea-9dc9-e69cc9fbefd4.png)

This seems a strange error to report as the task completes successfully and the value has been successfully replaced in the appsettings.json file.

Also it appears the documentation for FileTransformV2   is not up to date as the settings available do not match the documentation
```
documentation:
#fileType: # Optional. Options: xml, json
#targetFiles: # Optional
actual:
#jsonTargetFiles
#xmlTargetFiles

```

**Comment by eaarora-ms** [comment]
@MattEvansA45 can you please set the variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries at microsoft dot com

**Comment by eaarora-ms** [comment]
Also thanks for pointing out the documentation error, we will fix this.

**Comment by eaarora-ms** [comment]
@MattEvansA45 Hi, sorry for the confusion. File transformation 2 has new changes where the task fails when the changes are already present in the package. Here you might have given the XML transformation rules but the changes would have already been present and hence the error. The task completes successfully for JSON variable substitution.

I do understand this needs an enhancement because it is failing the task however can you please confirm if your deployment is getting blocked by this so that we can decide the priority of the issue? Thanks.

**Comment by eaarora-ms** [comment]
This is by design and If you want to get unblocked you can remove the XML Transformation rules and try re-deploying the pipeline again.
