### ISSUE TITLE
`Azure SQL Database deployment` task continues when there is an error if you pass the `--verbose` argument

### ISSUE THREAD

**Issue by ChristopherHaws** [microsoft/azure-pipelines-tasks#12283]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug
**Enter Task Name**: Azure SQL Database deployment

## Environment
- Server - Azure Pipelines
- Agent - Hosted and Private

## Issue Description

`Azure SQL Database deployment` task continues when there is an error if you pass the `--verbose` argument in the `Additional Invoke-Sqlcmd Arguments` field.

**Comment by chperich** [comment]
Thanks for reporting this issue. We are able to repro this on our end. We will roll out a fix shortly.

**Comment by SumiranAgg** [comment]
We have merged the [fix](https://github.com/microsoft/azure-pipelines-tasks/commit/3ebee401e9838788f0faae53e8b32c08af894806). The fix will be rolled out in next sprint. If this is blocking issue, follow below steps to upload task manually to your account:
1. clone repo to local
2. execute below commands in cmd
npm install -g tfx-cli
node c:/azure-pipelines-tasks/make.js build test --task SqlAzureDacpacDeploymentV1
tfx login --service-url "<account-url>" --token <pat>
tfx build tasks upload --task-path <build-path like C:/azure-pipelines-tasks/_build/Tasks/SqlAzureDacpacDeploymentV1
