### ISSUE TITLE
Change DotNetCoreCLI verbosityRestore defaultValue to Normal

### ISSUE THREAD

**Issue by aarondandy** [microsoft/azure-pipelines-tasks#12297]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLIV2 

## Environment
- Server - Azure Pipelines:
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

The default verbosity when creating a `dotnet restore` task is set to Detailed instead of Normal which causes a lot of output that I rarely need. It produces quite a lot of output which is not very helpful to me, making it a bit more difficult to read the logs if I just want to know "what" is going on vs "why". Additionally I don't have a way to reliably time this but it seems that it can add 10% to the runtime of the task. Can the default verbosity for this task be changed to `Normal` instead of `Detailed` to provide some of us with a better user experience and to possibly reduce our build times some? I would like to change it to Detailed when needed.

The fix for this appears to be as simple as changing the default value in the task.json file. I would be happy to make a PR for it but I am unable to properly contribute until #11136 is resolved.

https://github.com/microsoft/azure-pipelines-tasks/blob/150d937cf55ccf6672dc8255d422fede4c5ad020/Tasks/DotNetCoreCLIV2/task.json#L265

**Comment by aarondandy** [comment]
I made a PR for it anyway. The bots will sort it out in the end 😉

**Comment by aarondandy** [comment]
After looking at the docs, it seems that Minimal is the default used by the tool and may make a better default for the tool.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#options

**Comment by bishal-pdMSFT** [comment]
For CI pipeline normal may be better middle path as it might offer more insights and save people from re-running failed release with updated verbosity.

**Comment by aarondandy** [comment]
OK, that is a fair compromise. Normal isn't all that more noisy than Minimal. I also doubt anybody will be broken by the difference either way, and if they are they can manually configure it.
