### ISSUE TITLE
AzureResourceGroupDeployment@2 - csmParametersFile doesn't accept several files

### ISSUE THREAD

**Issue by aelmanaa** [microsoft/azure-pipelines-tasks#12293]
Hello,

tried to pass several parameter files to csmParametersFile but this was rejected with the following error message:

##[error]Error: Could not find any file matching the template file pattern

would it be possible to support several files in csmParametersFile? As workaround , I had to use AzureCLI@2

**Comment by aelmanaa** [comment]
@bishal-pdMSFT  Hello BIshal, I see that the issue has been closed. does it mean that it has been fixed?

**Comment by amansahni1** [comment]
@bishal-pdMSFT  Has this been resolved? Can we now pass multiple parameter files using csmParametersFile?
