### ISSUE TITLE
Error while automated test cases using VS and Selenium : Microsoft.TeamFoundation.DistributedTask.Task.TestExecution.NoTestPointsException: No automated test cases were found matching the specified test plan, test suites, test configuration. Ensure that right values were specified and try again. 

### ISSUE THREAD

**Issue by madgudi** [microsoft/azure-pipelines-tasks#12294]
## Note  
I have automated test cases using VS and Selenium and trying to run automated testcases from testplan, and this is the error i am getting: Microsoft.TeamFoundation.DistributedTask.Task.TestExecution.NoTestPointsException: No automated test cases were found matching the specified test plan, test suites, test configuration. Ensure that right values were specified and try again. 

![pipelinesettings](https://user-images.githubusercontent.com/32178325/73781906-f52e7700-4745-11ea-8342-bdc4204e9967.PNG)

**Comment by madgudi** [comment]
I have two test cases in that test plan. I have the status as Automated and both are associated to the automated test case in our solution. 
![AssociatedAutomation](https://user-images.githubusercontent.com/32178325/73782620-3ffcbe80-4747-11ea-9add-f1043c6c2d3a.PNG)

**Comment by ShreyasRmsft** [comment]
Can you provide full zip logs with system.debug = true?

Also from the logs check the test point, test suite and configuration id the names are getting translated to and verify if they exist and that the build agent is configured with the necessary permissions to access them.
