### ISSUE TITLE
ErrorActionPreference and FailOnStandardError does not work for AzurePowerShell@5

### ISSUE THREAD

**Issue by frankkrupp** [microsoft/azure-pipelines-tasks#12291]
AzurePowerShell@5 always returns success, even if I return "exit -1" 

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'MySubscription'
    ScriptType: 'InlineScript'
    Inline: 'Write-Error "Test Error"'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
    errorActionPreference: stop

Note: It behaves as expected with old version AzurePowerShell@4

**Comment by 20shivangi** [comment]
@frankkrupp The issue has been fixed in AzurePowerShellV5. It will take 6-8 weeks to get deployed. Thank you for your patience.

**Comment by 20shivangi** [comment]
Please wait for 6-8 weeks for the task to get deployed. Thereby, closing the issue.
