### ISSUE TITLE
Info helper for Startup Command is wrong for .NET Core

### ISSUE THREAD

**Issue by timheuer** [microsoft/azure-pipelines-tasks#12295]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 

- [ ] AzureFunctionAppV1; 
- [ ] AzureWebAppV1; 
- [ ] AzureWebAppContainer; 
- [ ] AzureFunctionAppContainer; 
- [ ] AzureRmWebAppDeployment

## Environment
- Server - Azure Pipelines

## Issue Description
The info tip helper for Startup Command for .NET Core projects suggest 'dotnet run' 
![image](https://user-images.githubusercontent.com/4821/73797418-d2f82180-4764-11ea-86ae-ead39c648681.png)

which shouldn't be used in production and instead should be recommended to use dotnet exec

**Comment by vineetmimrot** [comment]
@timheuer We have shown both the option, i.e. `dotnet run ` and `dotnet dll-file-path`. It is as per the user which to use. Also, as per text in the tip helper, we haven't recommended which one to use.

Also, I am unable to find any documentation of `dotnet exec`. This [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore30) doesn't list this command. Also, there is an internal [Github issue](https://github.com/dotnet/sdk/issues/5573), which asks for showing `dotnet exec` in documentation.

**Comment by timheuer** [comment]
@vineetmimrot the problem is that dotnet run shouldn't be used in this context.  It is a build task-related and requires the SDK.  In a pipeline environment we shouldn't be showing that.

**Comment by issacnitin** [comment]
@timheuer I believe the task you're referring to is a deploy task, not a .NET Core build task. ```dotnet run``` makes sense for a deploy task, as once the deployment is completed, there could be some more things that need to be done in the web app/function app. This scenario is facilitated using the startup command.

**Comment by timheuer** [comment]
@issacnitin the task is a deploy task but these map the to app settings for app service. Startup command is what tells the app service what is effectively the entry point. `dotnet run` is a build task and isn’t best practice. It shouldn’t be recommended unless you can identify the scenario here where a build is required. 

/cc @shanselman

**Comment by shanselman** [comment]
Right. `dotnet run` is only in the SDK and is only used when building un-built software. When you go `dotnet foo.dll` you're really going `dotnet exec foo.dll` for the built software

**Comment by issacnitin** [comment]
@shanselman @timheuer Understood. You're right, it doesn't make sense to run .NET build on a web app. Adding @pulkitaggarwl to confirm - Shall we remove ```dotnet run```? Should we add ```dotnet exec```?

**Comment by timheuer** [comment]
PR is attached to issue.

**Comment by issacnitin** [comment]
@timheuer  I've raised a PR on top of your changes, as some more changes were required 
https://github.com/microsoft/azure-pipelines-tasks/pull/12389

We'll roll out the changes ASAP

**Comment by issacnitin** [comment]
@timheuer Please review the PR #12389 . If ```dotnet foo.dll```  does the same thing as ```dotnet exec foo.dll```, should we let users be aware of ```dotnet exec``` command? It's not a listed command in ```dotnet help``` either, and could confuse users.

**Comment by timheuer** [comment]
@issacnitin good point in the doc for exec. I’ll raise an issue on the docs to get that added.

**Comment by issacnitin** [comment]
@timheuer Awesome! I've merged the PR, will roll out the fix soon

**Comment by issacnitin** [comment]
Closing, as issue is fixed
