### ISSUE TITLE
Feature Request: Task to cancel a build

### ISSUE THREAD

**Issue by Cellule** [microsoft/azure-pipelines-tasks#12299]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**:   _NYI_

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Ubuntu 16

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

This request comes from a recent change where some agent variables are becoming read-only, thus removing the ability to cancel a build (not fail, but cancel).
See my initial question on the matter here: https://github.com/microsoft/azure-pipelines-yaml/issues/439

My goal is to run various checks and depending on the result cancel the build because I don't need to run the rest of the tasks.
My main use-case is to check for files changes in various folder and cancel the build to save time/resources/agents.
Currently, my solution is to execute the following
```
  echo "##vso[task.setvariable variable=agent.jobstatus;]canceled"
  echo "##vso[task.complete result=Canceled;]DONE"
```
However, these variables will become read-only soon.

What I'm asking is a way, any way really, to cancel a build after running some code/script/task.
The simplest would be a task that cancels simply cancels the build and I could control execution with a custom condition using a variable that I would set myself.

Having official support to cancel a build would also make it much easier for people to find the mechanism to do so.
I know I searched for years, while I was working at Microsoft, for a way to cancel a build until I found this solution.

Ideally, those variables wouldn't become read-only and I wouldn't have to change anything, but I figured this request was out-of-scope for this repo.

<details>
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
</details>

**Comment by damccorm** [comment]
Hey @Cellule - I followed up in https://github.com/microsoft/azure-pipelines-yaml/issues/439

I'm going to close here since if we do something like this, it almost certainly wouldn't be a custom task - we'd probably be more likely to expose a primitive on the agent (similar to what you're doing with `echo "##vso[task.setvariable variable=agent.jobstatus;]canceled"`).

I'm not sure we should be doing this, but https://github.com/microsoft/azure-pipelines-yaml/issues/439 is probably the right thing for that discussion
