### ISSUE TITLE
Error on Batch Script Task

### ISSUE THREAD

**Issue by AlexTheBold** [microsoft/azure-pipelines-tasks#12308]
Hi,
I have a problem when I launch a batch file in witch I have the command 'exit /b 1' which return an error status. In some case the error is not detected by the batch script task.

I join the log on an Azure DevOps agent 
[logs_50.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4166169/logs_50.zip)

and my batch file :
``` MSDOS
@ECHO OFF
setlocal ENABLEDELAYEDEXPANSION
IF /i !TF_BUILD!. EQU TRUE. (
  ECHO Error case with xcopy
  xcopy "FakeSource" "FakeDirectory"
  IF ERRORLEVEL 1 ( 
    REM This Exit quit the batch file but Batch script task does not detect error
    exit /b 1
  )
) ELSE (
  ECHO simple Error case
  REM This Exit quit the batch file and Batch script task detect error
  exit /b 1
)
endlocal
```

**Comment by damccorm** [comment]
@AlexTheBold are you still running into this issue - I can't repro - https://dev.azure.com/damccorm-repros/batchRepro/_build/results?buildId=452&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=a906a9ce-f93f-5f1d-5af2-9fc83cef8d25

**Comment by AlexTheBold** [comment]
Hello Danny
Yes I still have this problem.
It appends only if the xcopy command is in a if instruction.

This is my batch file :
@ECHO OFF

setlocal ENABLEDELAYEDEXPANSION

IF /i !TF_BUILD!. EQU TRUE. (
  ECHO Error case with xcopy
  xcopy "FakeSource" "FakeDirectory"
  IF ERRORLEVEL 1 (
    exit /b 1
  )
  ECHO No error detected 1
) ELSE (
  ECHO simple Error case
  exit /b 1
)

ECHO No error detected 2
rem endlocal
ECHO No error detected 3



Cordialement,

Alex PAJON
Responsable Développement

[EIC]<http://www.eic.fr/>
[http://www.eic.fr/images/2016-site_eic.gif]<http://www.eic.fr/>
[Coordonnées]
[EIC]<https://www.facebook.com/agiris.eic>[EIC]<https://twitter.com/agiris_eic>
[EIC]<https://www.youtube.com/user/LogicielsEIC>[EIC]<https://www.linkedin.com/company/eic_2>
[EIC]<http://www.eic.fr/>
recommande les logiciels
[AGIRIS]<http://www.agiris.fr/Ressources/Pages/Accueil.aspx>

Ce message peut contenir des informations confidentielles et/ou sensibles. Si vous n'êtes pas le destinataire (ou que vous avez reçu ce message par erreur), merci d'en informer l'expéditeur immédiatement et de détruire ce message. Toute copie non autorisée, divulgation ou distribution du contenu de ce mail est strictement interdite

ü Adoptez l’éco-attitude, n’imprimez cet email que si nécessaire. Pensez également au réflexe dématérialisation, et optez pour notre solution d'avenir DEMAT'EXPERT...


De : Danny McCormick <notifications@github.com>
Envoyé : mardi 25 février 2020 20:54
À : microsoft/azure-pipelines-tasks <azure-pipelines-tasks@noreply.github.com>
Cc : Alex PAJON <Alex.PAJON@eic.fr>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/azure-pipelines-tasks] Error on Batch Script Task (#12308)


@AlexTheBold<https://github.com/AlexTheBold> are you still running into this issue - I can't repro - https://dev.azure.com/damccorm-repros/batchRepro/_build/results?buildId=452&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=a906a9ce-f93f-5f1d-5af2-9fc83cef8d25

**Comment by damccorm** [comment]
@AlexTheBold it doesn't repro even if I copy that exact script - https://dev.azure.com/damccorm-repros/batchRepro/_build/results?buildId=489&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=a906a9ce-f93f-5f1d-5af2-9fc83cef8d25 - any chance you can share a public AzureDevOps project with your repro?

**Comment by AlexTheBold** [comment]
Hi Danny,
It’s the first time I do a public project on Azure Devops.
Please, tell me if it doesn’t work.
The utl the project is https://dev.azure.com/apajon/Test

I try with a pipeline based on the same yml that you use, but I still have no error.

Cordialement,

Alex PAJON
Responsable Développement

[EIC]<http://www.eic.fr/>
[http://www.eic.fr/images/2016-site_eic.gif]<http://www.eic.fr/>
[Coordonnées]
[EIC]<https://www.facebook.com/agiris.eic>[EIC]<https://twitter.com/agiris_eic>
[EIC]<https://www.youtube.com/user/LogicielsEIC>[EIC]<https://www.linkedin.com/company/eic_2>
[EIC]<http://www.eic.fr/>
recommande les logiciels
[AGIRIS]<http://www.agiris.fr/Ressources/Pages/Accueil.aspx>

Ce message peut contenir des informations confidentielles et/ou sensibles. Si vous n'êtes pas le destinataire (ou que vous avez reçu ce message par erreur), merci d'en informer l'expéditeur immédiatement et de détruire ce message. Toute copie non autorisée, divulgation ou distribution du contenu de ce mail est strictement interdite

ü Adoptez l’éco-attitude, n’imprimez cet email que si nécessaire. Pensez également au réflexe dématérialisation, et optez pour notre solution d'avenir DEMAT'EXPERT...


De : Danny McCormick <notifications@github.com>
Envoyé : lundi 9 mars 2020 19:39
À : microsoft/azure-pipelines-tasks <azure-pipelines-tasks@noreply.github.com>
Cc : Alex PAJON <Alex.PAJON@eic.fr>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/azure-pipelines-tasks] Error on Batch Script Task (#12308)


@AlexTheBold<https://github.com/AlexTheBold> it doesn't repro even if I copy that exact script - https://dev.azure.com/damccorm-repros/batchRepro/_build/results?buildId=489&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=a906a9ce-f93f-5f1d-5af2-9fc83cef8d25 - any chance you can share a public AzureDevOps project with your repro?

**Comment by damccorm** [comment]
@AlexTheBold I think this is due to a quirk in how batch scripts execute `exit /b`. I got a minimal repro:

```
IF /i TRUE. EQU TRUE. (
  exit /b 1
  ECHO test
)
```

From where its called, this passes and **the batch script process returns code 0**. So our wrapper around the script actually processes the exit code correctly.

If you do this instead:

```
IF /i TRUE. EQU TRUE. (
  exit /b 1
)
```

or this:

```
IF /i TRUE. EQU TRUE. (
  exit 1
  ECHO test
)
``` 

or even this:

```
exit /b 1
ECHO test
```

the batch script returns error code 1 and we fail correctly.

So the minimal repro here is `exit /b 1` inside an if statement followed by a statement that would return an error code of 0.

I'm not 100% sure exactly why batch scripts behave this way, but that seems to be an issue with batch itself, not with how we're processing it on our end. It looks like `exit /b` is known to behave kinda weirdly around how it exits from subprocesses - https://stackoverflow.com/questions/2881483/exit-b-0-does-not-work - so my best guess here is that its related to that. From our end, though, we are correctly handling the exit codes, I don't think there's anything we can do to fix this since we don't control the batch executable.

I'd recommend switching to just use `exit 1` instead of `exit /b 1` as a workaround
