### ISSUE TITLE
Release pipeline downloads all parent directory items when artifact when directory does not exist

### ISSUE THREAD

**Issue by NicholasDenaro** [microsoft/azure-pipelines-tasks#12306]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadFileshareArtifacts@1

## Environment
- Server - Azure Pipelines

Agent - Private
OS: Windows Server 2012 R2
Agent Version: 2.164.7

## Issue Description
The DownloadFileshareArtifacts@1 task fails to find the artifact folder on the network share (in our case it seems to be a network hiccup), and instead goes to the parent directory and downloads everything inside. There are quite a lot of artifacts stored here (~60gb), so it fills up the disk space on the agent.

### Task logs
```
2020-02-06T06:13:50.0905635Z Downloading artifact [artifact] from: [path]
2020-02-06T06:14:11.9990681Z Directory '[artifact-path]' does not exist. Falling back to parent directory: [artifact-path-parent-directory]
2020-02-06T06:14:12.0141688Z Unable to read directory [artifact-path-parent-directory]. Error: Error: ETIMEDOUT: connection timed out, scandir '[artifact-path-parent-directory]'
2020-02-06T06:14:12.0148162Z Retrying download of [artifact-name], retry count: 1
2020-02-06T06:14:22.2390062Z Downloading [artifact-path-parent-directory-first-item] to [agent-artifact-directory]
```

**Comment by TMattes** [comment]
I ask you to re-open this, because your fix causes unwanted behaviour: if I decide I want a specific version of my artifact / artifact from a specific build, and this artifact is not found, then I want the pipeline to fail and not to take something else out of the parent directory. Furthermore, I never want it to download everything inside the parent directory. What "fix" should this be? Please think over it and fix it - this 'fall-back' is a mess!

**Comment by anatolybolshakov** [comment]
Hi @TMattes reopened it at the moment since there are some points to investigate.

**Comment by TMattes** [comment]
Please see also issue #14587

**Comment by TMattes** [comment]
Hello, @anatolybolshakov 
still, there is no action on this one. Please don't let it be closed again, we are stll waiting for a solution....

**Comment by anatolybolshakov** [comment]
@Lovakumar could you please take a look?

**Comment by tapika** [comment]
Any progress on this one ?

Would prefer that whole task would just fail if there is no directory, as most of time parent folders contains a lot more stuff.

Maybe make it configurable - allowToUseParentFolder: true/false, with default false (or true if you want to be backwards compatible).

**Comment by TMattes** [comment]
Stale again? Seriously? :(

**Comment by wiciok** [comment]
Not stale, still relevant.

**Comment by TMattes** [comment]
@anatolybolshakov, @Lovakumar 
Why is there no action on this one? This is still a very heavy and annoying bug! Everytime, build artifacts are gone due to retention, this bug paralyses our build servers by consuming the whole storage! Please work on this issue!

**Comment by TMattes** [comment]
No action at all, and then closed? Really? Please re-open.
