### ISSUE TITLE
MSTest task doesn't show output from Inconclusive tests

### ISSUE THREAD

**Issue by osolo** [microsoft/azure-pipelines-tasks#12302]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest

## Environment
- Server - Azure Pipelines hosted

## Issue Description

"Inconclusive" tests (tests that fail using `Assert.Inconclusive()`) show no useful information in the logs.  

The only indication that something is wrong is that ! appears next to the test name in the log.  However, neither the failure message nor anything logged via the `TestContext` are visible anywhere.

**Comment by nehsharmMS** [comment]
@osolo, Could you please provide trx file to clearly understand the issue.

**Comment by osolo** [comment]
@nehsharmMS I set up a complete repo with code and a pipeline which demonstrates this problem.  Please see https://dev.azure.com/ozsolomo/Test/_build/results?buildId=7&view=results

**Comment by nehsharmMS** [comment]
@osolo, This appears to be an issue with single agent test execution. Issue is reported to concerned team. As workaround, you can use distributed execution mode.

![image](https://user-images.githubusercontent.com/60141664/74153861-7babf280-4c37-11ea-9e24-b26ba72b34f7.png)

**Comment by osolo** [comment]
@nehsharmMS thank you for the workaround. 

There is still an issue after switching to distributed execution mode.  The tests that fail inconclusively don't show messages logged to the `TestContext`.   I updated the repo above to show this.  In the [new run](https://dev.azure.com/ozsolomo/Test/_build/results?buildId=9&view=ms.vss-test-web.build-test-results-tab), you can see that a failing test (`TestMethod3` in this case) will add the messages from the test context under "Attachments", however the inconclusive test (`TestMethod2`) does not.

I'm also concerned that the inconclusive tests leave the VSTest task with a green checkmark (ideally, the task would be yellow).  Is this a bug or a feature request?

Lastly, it would be nice if the default test filter on the Tests tab would automatically include "Others" if there are inconclusive tests.

**Comment by ShreyasRmsft** [comment]
Could you open a separate request for the enhancement around keeping the task status yellow for inconclusive tests? Let's use this to track the issue with the stack trace not showing up.

**Comment by Additi** [comment]
@nehsharmMS I think we should take this up since it's a flow break. Let's add this to our backlog and see when can we pick this up.

**Comment by nehsharmMS** [comment]
@Additi, sure. 

@osolo , Thanks for suggesting the enhancements and as mentioned by shreyas, please open separate request for enhancement.

**Comment by singhsarab** [comment]
@osolo The Inconclusive tests are treated the same as skipped tests.

The behavior for not reporting them as failed and failing the task is by design currently. It is based on the precedence set by the test platform (https://github.com/microsoft/vstest) and the test framework (https://github.com/microsoft/testfx)

What is the behavior when you run the tests locally on your machine using the vstest.console runner?
You can generate the trx result file (using --logger:trx option) and then compare it what is being shown in the pipeline UI.

**Comment by osolo** [comment]
@ShreyasRmsft I filed #12336 .

@singhsarab You are right that Visual Studio treats these like skipped tests, but that's totally broken.  I have already [filed a bug](https://developercommunity.visualstudio.com/content/problem/907934/test-explorer-incorrectly-handles-inconclusive-tes.html) for that as well.  I hope they will take _your_ lead and handle inconclusive tests in a sane way.

**Comment by singhsarab** [comment]
@osolo The VSTest task underneath uses the same test platform. If you want to suggest a change you can file an issue in the repo for the test platform like I mentioned in my previous comment.
