### ISSUE TITLE
Azure App Service Settings: SlotSetting not working

### ISSUE THREAD

**Issue by JonnyMattsson** [microsoft/azure-pipelines-tasks#12305]
It seems the slotSetting is not used when setting application settings 
If I set an application setting like this the settings is created but it is not set as a deployment slot setting. 
{
    "name": "WEBJOBS_STOPPED",
    "value": "1",
    "slotSetting": true
   },

**Comment by eaarora-ms** [comment]
@JonnyMattsson  I am not able to repro the issue from my end. Please make sure you're following the following things:

1. Task used is Azure App Service Settings V1 (since this is the only task that supports setting slotsetting to true.

2. Your format is correct, i.e.

```
[
   {
    "name": "key1",
    "value": "valueabcd",
    "slotSetting": false
   },
   {
    "name": "key2",
    "value": "valueefgh",
    "slotSetting": true
   }
]
```

If you still have this issue can you please set the variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries at microsoft dot com. We will also need your yaml file to repro the issue. Thanks.

**Comment by eaarora-ms** [comment]
@JonnyMattsson  Can you please confirm if you're still facing this issue?

**Comment by JonnyMattsson** [comment]
Hi!

Its still not working. We are using the only existing version(1.* Preview)
The log is actually a little bit weird. We set about 20 appsettings and 3 connectionstrings. All of them are set with 'slotsetting: true'. In the logs the slotsetting is not there anymore. It looks like this:

{"WEBJOBS_STOPPED":"1","APPINSIGHTS_INSTRUMENTATIONKEY":"XXXXXX"," ....

For the connection string the slotsetting is in the log but its still not added in azure. It looks like this:

"SignalR":{"value":"XXXXXX","type":"Custom","slotSetting":true

Things that could differ from your setup is that most of our values comes from variables and we are adding the settings to deployment slots(both production and a custom slot). 
Could you try with that?

**Comment by eaarora-ms** [comment]
Can you please set the variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries at microsoft dot com. Thanks.

**Comment by JonnyMattsson** [comment]
I have sent you an email with the logs.

**Comment by eaarora-ms** [comment]
> It looks like this: {"WEBJOBS_STOPPED":"1","APPINSIGHTS_INSTRUMENTATIONKEY":"XXXXXX"," ....

@JonnyMattsson  The debug logs here are set up such that it states only the variable name and value. That does not mean that it is not updating the slot settings.  We have different logs for updating slot settings which reads like : 
'Slot setting updated for key : WEBJOBS_STOPPED_NOT'

which I cannot find in your logs. I am trying to repro it by the way you've mentioned. Please allow me some time to get back to you.

**Comment by eaarora-ms** [comment]
@JonnyMattsson  Hi, still not able to repro. We can set up a call but can you try one last thing. Can you call this REST API to check if your slot settings are actually updated or not?

https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listslotconfigurationnames

You can share the response by replying to the same email you sent earlier.

**Comment by eaarora-ms** [comment]
Still not able to repro the issue. 

@JonnyMattsson  We can set up a call sometime but before that can you please try one last thing. Can you please share the response of the following REST API:

https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listslotconfigurationnames

You can share the response by replying to the same email id as above.

Also, in your logs, I can see that you've mentioned changing settings for 'stage' slot. Can you please re-check if you're checking the correct slot on the portal.
Thanks!

**Comment by Suhas-Chandrashekar** [comment]
Hi @eaarora-ms , Am still facing the same issue. I am using ARM template to create the function Apps.
"name": "APPINSIGHTS_INSTRUMENTATIONKEY",
 "value": "[reference(concat('Microsoft.insights/components/', variables('ApplicationinsightsName'))).InstrumentationKey]",
"slotSetting": true

The Deployment slot settings are not enabled after the execution. Could you please help?
