### ISSUE TITLE
PublishTestResults: Publishing test results fails because no file PTR_TEST_RUNSUMMARY.json

### ISSUE THREAD

**Issue by metaalbakker** [microsoft/azure-pipelines-tasks#12300]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: PublishTestResults

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows, agent.version: 2.164.7

## Issue Description

Running tests with protractor using npm, which outputs a testresults file in vstest testresults xml format. Trying to publish the test results gives the warning that the ptr_test_runsummary.json file is not found. When is this file supposed to be created/used from my azure pipeline?

### Task logs

[ReleaseLogs_10908.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4158116/ReleaseLogs_10908.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[##[debug]Unable to publish the test run summary to evidencestore, error details:Error: ENOENT: no such file or directory, open 'C:\Agent_AD1\_work\_temp\PTR_TEST_RUNSUMMARY.json']

**Comment by navin22** [comment]
@metaalbakker can you please give some more details on this issue?
1. How does the pipeline configured, can you please share the task yaml?
2. And also please share the task logs with pipeline variable set to system.debug = true.?
3. Is it blocking the publishing the results or is the debug statement is worrying ?

**Comment by metaalbakker** [comment]
I included the yml of the publish test results task and the full logs of the Release Pipeline with system.debug = true;

It seems there are tests published, but when viewing the tests in the release pipeline afterwards, there are no test results visible, that's why the statement was worrying to me.
This has been the case since the testruns on the 30th of januari, but it seems that our test agents were also a bit behind, so due to the hard check on test agent version, the task didn't seem to publish any more since then. Although the task kept returning as succeeded

![image](https://user-images.githubusercontent.com/26539196/74410112-98fbdf00-4e38-11ea-9400-65cca7b429cc.png)


[ReleaseLogs_10999.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4196923/ReleaseLogs_10999.zip)

[publishtestresults.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4196924/publishtestresults.zip)

**Comment by aee11** [comment]
I've also been encountering this since 2.164.3, but it worked fine in 2.162.2

**Comment by navin22** [comment]
@metaalbakker and @aee11 
This debug statement actually don't have any impact on the publishing feature. 
This was a new feature done to publish test run summary to another system. If there are no test results to publish, there won't be anything to publish Hence the debug statement. 
To avoid confusion. I will go through it to consider if I can avoid this statement and have better logging statement.

**Comment by metaalbakker** [comment]
@navin22 @aee11 
Problem is that when I downgrade the task to version 1, testresults are published are again, because the results are there as indicated by the logs.
![image](https://user-images.githubusercontent.com/26539196/74650623-67f61400-5182-11ea-882a-95d19964e2fc.png)

**Comment by aee11** [comment]
@navin22 Below is the full debug log. The TestResultPublisher executable doesn't seem to indicate any further errors, besides the error code.

```
##[debug]found: 'C:\devopsAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe'
##[debug]System.TeamFoundationCollectionUri=<collection url redacted>
##[debug]SystemVssConnection auth param AccessToken = ***
##[debug]System.TeamProject=<project name redacted>
##[debug]System.PullRequest.TargetBranch=undefined
##[debug]Build.RequestedFor=<redacted>
##[debug]Build.BuildId=14230
##[debug]Build.BuildUri=vstfs:///Build/Build/14230
##[debug]Release.ReleaseUri=undefined
##[debug]Release.EnvironmentUri=undefined
##[debug]System.PhaseName=Test
##[debug]System.PhaseAttempt=1
##[debug]System.StageName=__default
##[debug]System.StageAttempt=1
##[debug]System.JobName=WindowsSQLite
##[debug]System.JobAttempt=1
##[debug]System.JobIdentifier=Test.WindowsSQLite
##[debug]Agent.TempDirectory=C:\devopsAgent\_work\_temp
##[debug]agent.proxyurl=undefined
##[debug]agent.proxyusername=undefined
##[debug]agent.proxypassword=undefined
##[debug]agent.proxybypasslist=undefined
##[debug]Agent.TempDirectory=C:\devopsAgent\_work\_temp
##[debug]C:\devopsAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe arg: ["@C:\\devopsAgent\\_work\\_temp\\918c17b0-4ec6-11ea-8dfa-e33f683a9f87.txt"]
##[debug]exec tool: C:\devopsAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe
##[debug]arguments:
##[debug]   @C:\devopsAgent\_work\_temp\918c17b0-4ec6-11ea-8dfa-e33f683a9f87.txt
C:\devopsAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe @C:\devopsAgent\_work\_temp\918c17b0-4ec6-11ea-8dfa-e33f683a9f87.txt
##[debug]Exit code 2148734720 received from tool 'C:\devopsAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe'
##[debug]STDIO streams have closed for tool 'C:\devopsAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe'
##[debug]Exit code of TestResultsPublisher: 2148734720
##[debug]Agent.Version=2.164.8
##[debug]Agent.TempDirectory=C:\devopsAgent\_work\_temp
##[debug]Unable to publish the test run summary to evidencestore, error details:Error: ENOENT: no such file or directory, open 'C:\devopsAgent\_work\_temp\PTR_TEST_RUNSUMMARY.json'
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]
##[debug]Release.ReleaseUri=undefined
##[debug]Release.ReleaseId=undefined
##[debug]Build.BuildUri=vstfs:///Build/Build/14230
##[debug]Build.Buildid=14230
##[debug]Processed: ##vso[telemetry.publish area=TestExecution;feature=PublishTestResultsTask]{"builduri":"vstfs:///Build/Build/14230","buildid":"14230","osType":"Windows_NT","testRunner":"JUnit","failTaskOnFailedTests":"true","mergeResultsUserPreference":"true","config":"sqlite","platform":"Windows","testResultsFilesCount":90,"dotnetVersion":"","subFeature":"publishTestResultsTaskConsolidatedCiEvent"}
Finishing: Publish test results
```

**Comment by navin22** [comment]
@metaalbakker or @aee11 
Can I get the results files, if possible to mimic the scenario ? Is it happening in all the pipelines or some particular pipeline?

**Comment by metaalbakker** [comment]
Here is an example results file. It happens in multiple pipelines, but they all output the same kind of results file as this one.

[testresults.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4225397/testresults.zip)

**Comment by suyash691** [comment]
Can you please let us know what is the .NET framework version installed on the build agent machine?

If the .NET framework version installed on the machine is 4.6.1 or less than that then can you please try upgrading the .Net framework version to 4.6.2.
Exit code - 2148734720 usually refers to .net being outdated

**Comment by suyash691** [comment]
@metaalbakker Did the issue get fixed with .Net version upgrade?

**Comment by metaalbakker** [comment]
> @metaalbakker Did the issue get fixed with .Net version upgrade?

I had a version < 4.7.2 installed and indeed installing 4.7.2 seems to have fixed the issue of results not being uploaded, thanks!

**Comment by suyash691** [comment]
Closing the issue
