### ISSUE TITLE
kubectl command output is somehow disrupted

### ISSUE THREAD

**Issue by MirKml** [microsoft/azure-pipelines-tasks#12307]
## Required Information

*Type*: Bug

**Enter Task Name**: kubectl

## Environment
- Server - Azure Pipelines
- Agent - Private: OS Ubuntu 18.04

## Issue Description

We need to catch output of kubectl get so we setup the kubectl task and set output variable.
But content of the output variable is somehow disrupted. There are some commas and
content of the output variable is different then the result of the original of kubectl command.

Original command is `kubectl get deployment` output is

![image](https://user-images.githubusercontent.com/21239658/73950026-87c44700-48fb-11ea-9a3d-467b1decc320.png)

but captured output in output variable is

![image](https://user-images.githubusercontent.com/21239658/73950255-e4276680-48fb-11ea-8901-2e951f9adce4.png)

As you can see, there are some commas, spaces in many places.

It breaks the possibility parse the kubectl get command output in subsequent tasks.

**Comment by ds-ms** [comment]
@MirKml which task are you using this output variable with, I was unable to reproduce this issue.
What's the `kubectl` version on your private agent?

**Comment by MirKml** [comment]
I used kubectl azure task v.1 with exact kubectl command line version 1.14.10 on ubuntu on premise agent.
Problem is somewhere in capturing output code of the task I think.

**Comment by MirKml** [comment]
Let me know if you cannot still reproduce. I can try to setup pipeline - then you can see pipeline logs in azure (on our private account).

**Comment by ds-ms** [comment]
@MirKml Let me try it with any older version of `kubectl`. The task blindly pipes the output of the command directly to the output variable. 

For mitigation you could use `-o json` and parse it as a JSON object instead.

**Comment by MirKml** [comment]
It's necessary to use this exact kubectl version - or 1.14.x, because it's required for the destination kubernetes cluster/server. Cluster and client version must be on mostly same version.

JSON output is problematic, because it's very huge, kubectl get with json output generates huge list of deployments/services - each service has lots of details, and task said it's exceed limit of maximal text output size for the I think it was 64k.

**Comment by ds-ms** [comment]
@MirKml you can use `--jsonpath` to get the specific details you're looking for in a format you desire. 

Documentation: https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by ds-ms** [comment]
Closing stale issue, re-open if the problem still persists.
