### ISSUE TITLE
Are there plans to add Test Impact Analysis support for .Net Core?

### ISSUE THREAD

**Issue by oatsoda** [microsoft/azure-pipelines-tasks#12315]
https://devblogs.microsoft.com/devops/accelerated-continuous-testing-with-test-impact-analysis-part-1/

As stated, .Net Core is not supported.  Are there plans to do so?

**Comment by bishal-pdMSFT** [comment]
@phanikmmsft do you own test inpact analysis?

**Comment by phanikmmsft** [comment]
@bishal-pdMSFT   - yes, we own this, and not currently working on support for this 

@PBoraMSFT - to comment further on roadmap for this 
@ShreyasRmsft  - fyi

**Comment by PBoraMSFT** [comment]
@oatsoda - no, this is not on the roadmap.

**Comment by Steve887** [comment]
@PBoraMSFT @phanikmmsft 
Has the thinking on this changed? Seems like a pretty significant shortcoming in upgrading to .Net Core/.Net 6.

Otherwise, is there any other way to enable Test Impact Analysis for these projects?

**Comment by cfarmermike** [comment]
any updates on this for .net 6?

**Comment by Xriuk** [comment]
> Since there is no more "Core" -- only .NET (v6.0 now), I would think that Microsoft's flagship test impact tool should work against Microsoft's flagship software framework.

Wild that this is "not on the roadmap" yet

**Comment by oatsoda** [comment]
Any update on whether this is something to be considered? Given most teams are operating in a more continuous delivery manner, this could be saving tons of CPU and time!
