### ISSUE TITLE
VsTestV2 fails in rerun of failed tests when TestCaseFilter parameter is already added

### ISSUE THREAD

**Issue by MauriRojas** [microsoft/azure-pipelines-tasks#12311]
**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines 

- Agent - Private: OS, Windows. Agent version 2.163.1

## Issue Description

We are using the `TestCaseFilter` parameter in the "Other console options" of the task. We enabled the "Rerun failed tests" also and when a test fails, the rerun operation fails with the message `The parameter "/TestCaseFilter" should be provided only once`.  It looks like the new filter (the one with the fully qualified name of the failing test) is not added to the already existing filter, resulting in the `TestCaseFilter` added twice.

The expected behavior should be that is possible to use the `TestCaseFilter` parameter along with the "Rerun failed tests" option enabled.

Thanks for your time.

### Task logs

```
 **************** Rerunning failed tests for Test run 1630956 *********************
Max attempts: 5; Current attempt: 4; Failed test cases threshold: 75; Failed test cases max limit: 0
[command]E:\Agent02\_work\_tool\VsTest\16.5.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@E:\Agent02\_work\_temp\tdynm1jhogc.tmp"
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe /TestCaseFilter:"FullyQualifiedName=NAME.OF.FAILING.TEST"
"E:\Agent02\_work\r175\a\MyArtifact\web\TESTS\MYTESTS.dll"
/Settings:"E:\Agent02\_work\_temp\kznkzkc0zf4.tmp.runsettings"
/Logger:"trx"
/TestAdapterPath:"E:\Agent02\_work\r175\a\MyArtifact\web\TESTS"
/Diag:"E:\Agent02\_work\_temp\Attempt-5_2fmws5.diag"
/TestCaseFilter:"TestCategory=MyCategory|TestCategory=MyCategory2"
##[error]The parameter "/TestCaseFilter" should be provided only once.
##[debug]Processed: ##vso[task.logissue type=error;]The parameter "/TestCaseFilter" should be provided only once.
##[debug]Exited vstest.console.exe with code 1.
##[debug]PERF: ExecuteVsTestPhase.InvokeVSTest: took 344.3336 ms
Vstest.console.exe exited with code 1.
**************** Completed test execution *********************
```

**Comment by ShreyasRmsft** [comment]
@MauriRojas please do not use the OtherConsoleOptions for this. It is an unregulated field meant for advanced users and we do not parse the inputs provided. It is a use-at-your-own-risk field.

I suggest you use the well defined TestCaseFilter input field in the task for achieving the same. Thanks.

![image](https://user-images.githubusercontent.com/25194518/74136020-5d340000-4c13-11ea-9209-2f97e33e5fd9.png)

**Comment by MauriRojas** [comment]
Hi @ShreyasRmsft, thanks for your answer. Using the `Test filter criteria` enabled us to use the Rerun option. After this we unchecked the _Flaky tests included in test pass percentage_ option in the project settings, to avoid flaky tests to make fail the pipeline.
![image](https://user-images.githubusercontent.com/31770211/74194965-0ccf9900-4c39-11ea-9a96-3d023618a93e.png)

However, seems that we are experiencing issue#[6104](https://github.com/MicrosoftDocs/vsts-docs/issues/6104).

**Comment by ShreyasRmsft** [comment]
This feature is being rolled out for the vstest task (to not fail if all the failures are flaky tests) and will be done ring by ring until it is enabled for all the accounts.

**Comment by MauriRojas** [comment]
Hi @ShreyasRmsft, that is great news. Thanks for your help on this.
