### ISSUE TITLE
KubernetesManifestV0 Error: unknown flag: --timeout

### ISSUE THREAD

**Issue by t03apt** [microsoft/azure-pipelines-tasks#12310]
Is there a way to specify kubectl version for the KubernetesManifestV0 task?

Since one of the updates was rolled out I am getting this error:
```
==============================================================================
Task         : Deploy to Kubernetes
Description  : Use Kubernetes manifest files to deploy to clusters or even bake the manifest files to be used for deployments using Helm charts
Version      : 0.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest

...

C:\hostedtoolcache\windows\kubectl\1.11.2\x64\kubectl.exe rollout status StatefulSet/my-service --timeout 0s --namespace default
Error: unknown flag: --timeout

##[error]Error: Error: unknown flag: --timeout
```

Same deployment worked with 0.162.2.

**Comment by t03apt** [comment]
Same deployment worked with 0.162.2.

**Comment by vithati** [comment]
KubernetesManifestV0 don't automatically update the kubectl version. If kubetctl version is old then you need to use Kubernetes@1 task.

**Comment by t03apt** [comment]
What version KubernetesManifestV0 use if there is no Kubernetes@1 task called before?

**Comment by vithati** [comment]
@t03apt , are you using hosted agent or private agent. if we are using ubutu hosted agent then current kubectl version it has 1.17.2. Running Kubernetes@1 before KubernetesManifestV0 is based on your k8s  server version. If your k8s server not compatible with kubectl (1.17.2 on hosted agent) then you need to run Kubernetes@1 before KubernetesManifestV0.

**Comment by t03apt** [comment]
I see. Thanks for the details!
