### ISSUE TITLE
Yaml task edit xml app.config

### ISSUE THREAD

**Issue by florea-g** [microsoft/azure-pipelines-tasks#12313]
Helllo,

I have this log but the file hasn't been updated.
Can you help me please?
```
Initiated variable substitution in config file : ---Path---To--The-Folder\App.config
Processing substitution for xml node : appSettings
Updating value for key= ElasticSearchUris with token value: CONFIG_FILE_SETTINGS_TOKEN(ElasticSearchUris)
Processing substitution for xml node : connectionStrings
Processing substitution for xml node : configSections
Config file : ---Path---To--The-Folder\App.config updated.
XML variable substitution applied successfully.
```

**Comment by chshrikh** [comment]
@florea-g please provide the task and its version details

**Comment by eaarora-ms** [comment]
@florea-g  Can you please set the variable "System.debug" with value "true". Redeploy and share logs at RM_Customer_Queries at microsoft dot com? We will also need your yaml file to repro the issue. Thanks.

**Comment by florea-g** [comment]
Hello thanks for your help. I have finaly find the problem. I was using two jobs and i didn't knew that each job does a git checkout and each time my files were replaced.
So i didn't find how to do this in a chain of job without doing a checkout each time.

**Comment by eaarora-ms** [comment]
@florea-g You cannot perform the job without doing a checkout each time.

**Comment by florea-g** [comment]
ok thanks for your help. I appreciate .
