### ISSUE TITLE
SQL Deploy task: Error in bulk upload when using "Execute withing a transaction"

### ISSUE THREAD

**Issue by Master-Oliveira** [microsoft/azure-pipelines-tasks#12323]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlDacpacDeploymentOnMachineGroup

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlDacpacDeploymentOnMachineGroupV0

## Environment
- Server - Azure Pipelines
      
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows Server 2016 

## Issue Description

When option "Execute within a transaction" is selected, the script fails with exception: "Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.2.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.)."

This happens because the agent is not running in the same server as SQL Server, and it cannot access the SQL Scripts to bulk upload. I've tried to put the original sql scripts into a shared folder, but when the task creates the separate sql files (the ones starting with 1.1, 1.2, 1.e etc ... ) the task tries to bulk upload from a local drive and it fails.

Not sure if i need to configure something differently, or if i need to run the agent in the SQL Server.

To reproduce:
Setup deploy agent to run into a different machine than SQL Server

1 - Deploy .net core and in build, create migration scripts
2 - Create release with sql deploy and select the sql script generated in build
3 - Select execute within a transaction

### Task logs
[tasklog_9.log](https://github.com/microsoft/azure-pipelines-tasks/files/4180366/tasklog_9.log)

### Error logs

2020-02-05T11:42:53.0571797Z ##[section]Starting: Deploy SharedDatabase
2020-02-05T11:42:53.0811376Z ==============================================================================
2020-02-05T11:42:53.0812068Z Task         : SQL Server database deploy
2020-02-05T11:42:53.0812285Z Description  : Deploy a SQL Server database using DACPAC or SQL scripts
2020-02-05T11:42:53.0812383Z Version      : 0.3.20
2020-02-05T11:42:53.0812469Z Author       : Microsoft Corporation
2020-02-05T11:42:53.0812597Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-dacpac-deployment-on-machine-group
2020-02-05T11:42:53.0812703Z ==============================================================================
2020-02-05T11:42:58.4694241Z ##[error]Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.1.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.2.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.3.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.4.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.5.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.6.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.7.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.8.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.9.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Cannot bulk load because the file "C:\azagent\A1\_work\r1\a\batchdir\1.10.apply-migrations-shareddb.sql" could not be opened. Operating system error code 3(The system cannot find the path specified.).
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Trying to load file in ASCII format
Completed adding files in temporary table
Acquiring applock if specified
@SPID=56
Completed acquiring applock if specified
Begin executing scripts
Completing Script execution: 2020-02-05 11:42:58.063 
 Msg 50000, Level 16, State 1, Procedure , Line 1.
2020-02-05T11:42:58.5303575Z ##[section]Finishing: Deploy SharedDatabase

**Comment by toddmillernyc** [comment]
I'm also having this issue, after I found this post, I turned off the "execute within a transaction " option, and the SQL deploy is working.

**Comment by Master-Oliveira** [comment]
Just to add that this issue was opened following a post in https://developercommunity.visualstudio.com/content/problem/907309/error-operating-system-error-code-null-when-using.html?childToView=913921#comment-913921

**Comment by arjgupta** [comment]
@Master-Oliveira  you are trying to run a Deployment Group based task on a machine which is not your sql server. This is not the correct way to use a Deployment Group based task. You should configure the sql server against a deployment group and then run this task. You can read more [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/howto-webdeploy-iis-deploygroups?view=azure-devops)
