### ISSUE TITLE
Typo in ARM deployment task text

### ISSUE THREAD

**Issue by juunas11** [microsoft/azure-pipelines-tasks#12324]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ARM template deployment / AzureResourceManagerTemplateDeploymentV3 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Cannot provide this now

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-2019

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Typo in https://github.com/microsoft/azure-pipelines-tasks/blob/7bf2391069f629f64fc18f4258995565283ce37b/Tasks/AzureResourceManagerTemplateDeploymentV3/Strings/resources.resjson/en-US/resources.resjson#L84:

> ARM Service Conection deployment scope - %s

Should be:

> ARM Service Connection deployment scope - %s

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by vineetmimrot** [comment]
fixed the issue. Thanks for reporting.
