### ISSUE TITLE
dotnet tool install doesn't work

### ISSUE THREAD

**Issue by mswilson4040** [microsoft/azure-pipelines-tasks#12326]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: .NET Core  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
I am trying to run `dotnet tool install swashbuckle.aspnetcore.cli --version 5.0.0` in a pipeline and it fails every time with the below message:

> "C:\Users\VssAdministrator\AppData\Local\Temp\yrcstfiw.a2b\restore.csproj" (Restore target) (1) ->
>                    (Restore target) -> 
>                      C:\Program Files\dotnet\sdk\3.1.101\NuGet.targets(123,5): error : Unable to load the service index for source https://<private-feed-url>/index.json. [C:\Users\VssAdministrator\AppData\Local\Temp\yrcstfiw.a2b\restore.csproj]
>                    C:\Program Files\dotnet\sdk\3.1.101\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\VssAdministrator\AppData\Local\Temp\yrcstfiw.a2b\restore.csproj]

I am trying to get it to just use nuget.org as the tool i'm after isn't private. It's public. But, no matter what I do, Azure Pipelines only wants to recognize my private feed as the source instead of allowing nuget.org.

The strange thing to me is that all the other pipeline tasks that's restoring nuget packages works without issue.

I have tried using `--add-source`:

`dotnet tool install swashbuckle.aspnetcore.cli --version 5.0.0 --add-source https://api.nuget.org/v3/index.json --verbosity diag` but I get the exact same error

Here's my full yaml task:
```
- task: DotNetCoreCLI@2
    displayName: 'Install Swashbuckle CLI'
    inputs:
      command: custom
      custom: tool
      arguments: 'install swashbuckle.aspnetcore.cli --version 5.0.0 --add-source https://api.nuget.org/v3/index.json --verbosity diag'
```

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by issacnitin** [comment]
@mswilson4040 Thanks for reporting the issue. Could you try setting the parameter for DotNetCoreCLI@2 ```includeNuGetOrg``` to true in your YAML pipeline? 
More information on how to write YAML pipeline here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

**Comment by issacnitin** [comment]
@mswilson4040 Any update on the suggestion?

**Comment by mswilson4040** [comment]
@issacnitin Sorry about the delay. Yes, that does the trick. Thanks!

**Comment by issacnitin** [comment]
Awesome. Thanks! Closing the issue.
