### ISSUE TITLE
ServiceFabricUpdateManifestsV2: Unrecognized artifact type 'PipelineArtifact'

### ISSUE THREAD

**Issue by smdonoghue** [microsoft/azure-pipelines-tasks#12322]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: ServiceFabricUpdateManifestsV2 

https://github.com/microsoft/azure-pipelines-tasks/blob/7e2d65456791dd520f9840c656a8df292b2cd65a/Tasks/ServiceFabricUpdateManifestsV2/Get-VstsBuild.psm1#L111

## Environment
 - Azure Pipelines

## Issue Description

When attempting to update Service Fabric manifests within a build pipeline, during the retrieval of the previous build artifact for comparison we receive warning messages indicating:

```
##[warning]Failed to communicate with Azure Pipelines: Unrecognized artifact type 'PipelineArtifact'
##[warning]Could not find previous build to compare against.
```
The task then proceeds to update the version of every service due to this issue, which isn't ideal.

We have recently moved to using the **Publish Pipeline Artifacts** over the older **Publish Build Artifacts** so I'm guessing it's just a case that this task does not yet support the newer artifact type.

Is this something we could look to support moving forwards?

![image](https://user-images.githubusercontent.com/2563987/74143532-e424b080-4bf2-11ea-9880-d03a8dd308ed.png)
_Image 1: Task setup_

![image](https://user-images.githubusercontent.com/2563987/74143549-eab32800-4bf2-11ea-9f32-929d36601bd8.png)
_Image 2: Build log warning messages_

**Comment by anuragc617** [comment]
@smdonoghue thanks for reporting this. Currently we don't support  artifact type 'PipelineArtifact', we have added this enhancement in our backlog.
