### ISSUE TITLE
XML Variable Substitution should have option to replace special characters

### ISSUE THREAD

**Issue by Sjark** [microsoft/azure-pipelines-tasks#12320]
**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Enter Task Name**: IISWebAppDeploymentOnMachineGroup@0

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - Azure Pipelines

- Agent - Hosted or Private: 
    - Private
      - Agent version: 2.164.7

## Issue Description

When using `xmlVariableSubstitution`: `true` on task: `IISWebAppDeploymentOnMachineGroup@0`, invalid xml characters won't be escaped. This will leave you with invalid xml if you have any variables containing characters like `&`.

Either those characters should be escaped by default, or there should at least be a configuration option to have them replaced.

`&` should be replaced by `&amp;` etc.

The way to work around this problem at the moment is to save the variable with the value already escaped, but this does not work well if the same variable should be replaced in another file that does not need escaping (json etc).

It seems like this task did escape illegal xml characters before, but it was considered a bug and therefore removed. Ref: #4001

**Comment by SumiranAgg** [comment]
@Sjark As you can see in the issue before, when the xml contains connectionstring with special characters, we need to leave the special characters as is. Hence, we decided not to escape special characters anymore.

We can probably introduce an explicit option that allows user to opt-in explicitly if he wants to escape special characters. @N-Usha What do you think about this?

**Comment by Sjark** [comment]
An opt-in possibility would be nice, cause right now, you have to escape characters yourself in the environment variable, and the variable won't work if used in other config files besides xml.

**Comment by SumiranAgg** [comment]
@N-Usha Has added this to our backlog. We will prioritize it appropriately. I will be marking this as enhancement. Please thumbs-up the issue to build up demand.

**Comment by aarondandy** [comment]
Can you explain why unescaped values are required for the connection string elements? I read the comment that the deleted user left in the linked thread but it is still XML and XML with unescaped values is invalid as I understand it.

**Comment by aarondandy** [comment]
As a workaround, I created my own task using https://www.npmjs.com/package/xmldom which performs variable replacements for my .config files. Because it seems like others are running into the same issue as me I will look into publishing the task.

**Comment by aarondandy** [comment]
I published my workaround for this issue: https://marketplace.visualstudio.com/items?itemName=rezStream.appcfg-settings
