### ISSUE TITLE
Question: Azure SQL Database deployment SQL DACPAC Deploy Report Difference As Error

### ISSUE THREAD

**Issue by lgoncerzewicz** [microsoft/azure-pipelines-tasks#12332]
**Question, Bug, or Feature?**
Type: Question
Enter Task Name: 
Azure SQL Database deployment

**Environment**
Server - Azure Pipelines

**Issue Description**
The idea is to use SQL DACPAC File / Deploy Report to validate changes to the database.
I would like the pipeline run to fail if ANY schema differences are detected.
Is there any parameter I can set to achieve that? Or could you suggest an alternative approach?

**Comment by chperich** [comment]
Have you tried using setting BlockWhenDriftDetected flag? 

You can pass  /p:BlockWhenDriftDetected=true as part of additional arguments.
