### ISSUE TITLE
Feature Request: Inconclusive Tests Should Affect the VSTest Task State

### ISSUE THREAD

**Issue by osolo** [microsoft/azure-pipelines-tasks#12336]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: VSTest

## Issue Description

When a test fails with `Assert.Inconclusive()`, the `VSTest` task still succeeds (green checkmark).  This is detrimental because users don't know that there is a problem with the test.

At the very least, the task would fail with a warning (similar to what you get when a task fails and you chose "continue on error").

Ideally, if would be configurable (i.e. allow the use to choose what happens with inconclusive tests: fail outright, fail as warning, ignore).

See also: #12302 
See also: [Visual Studio bug](https://developercommunity.visualstudio.com/content/problem/907934/test-explorer-incorrectly-handles-inconclusive-tes.html)

**Comment by jez9999** [comment]
I agree this should be fixed 100%.  On Azure DevOps, this same problem occurs - an Inconclusive test is treated like a skipped test, and the error message passed to the Inconclusive call is simply dropped.  I passed the error message for a reason - I want it displayed in the test results!

The only thing it does right is that an Inconclusive test doesn't cause the test run to fail, which is desirable.  However, it should not count as "not run".  It clearly has been run.

**Comment by osolo** [comment]
This is still a problem.
