### ISSUE TITLE
DownloadPackage doesn't support latest version

### ISSUE THREAD

**Issue by evertonmc** [microsoft/azure-pipelines-tasks#12333]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DownloadPackage

- Server - Azure Pipelines or TFS on-premises?
Azure DevOps Server 2019.1.1

## Issue Description

DownloadPackage doesn't support selecting the latest package at runtime

**Comment by lucianiz** [comment]
DownloadPackage doesn't support latest version for universal packages.
There is a check 
```
  if (packageType === "upack") {
            return await downloadUniversalPackage(downloadPath, feed.projectId, feed.feedId, packageId, version, filesPattern);
        }
```

that is done before checking if version = "latest", this causes "latest" version to work for all package types except universal packages, we are using universal packages only, we really need this feature, currently I'm doing workarounds for linux but we now have windows deployments that would require duplicating the workarounds for all windows piplines.

@herenhuang  would it be possible to re-open this issue?
