### ISSUE TITLE
Azure Devops - Deploy to AKS - PublishPipelineArtifact Task - Path does not exist: /home/vsts/work/1/s/manifests/

### ISSUE THREAD

**Issue by nchauhan5** [microsoft/azure-pipelines-tasks#12345]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: PublishPipelineArtifact

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

2020-02-12T00:26:45.4361569Z ##[section]Starting: PublishPipelineArtifact
2020-02-12T00:26:45.4364730Z ==============================================================================
2020-02-12T00:26:45.4364839Z Task         : Publish pipeline artifact
2020-02-12T00:26:45.4364946Z Description  : Publish a local directory or file as a named artifact for the current pipeline
2020-02-12T00:26:45.4365050Z Version      : 0.140.0
2020-02-12T00:26:45.4365124Z Author       : Microsoft Corporation
2020-02-12T00:26:45.4365227Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
2020-02-12T00:26:45.4365345Z ==============================================================================
2020-02-12T00:26:45.8949570Z ##[error]Path does not exist: /home/vsts/work/1/s/manifests
2020-02-12T00:26:45.9031990Z ##[section]Finishing: PublishPipelineArtifact

**Comment by fadnavistanmay** [comment]
Are you trying to run inside a container? Not all the paths are mapped to the host machine. - https://github.com/microsoft/azure-pipelines-agent/blob/8c665282fe47910294e6f3b10565e3301320990f/src/Microsoft.VisualStudio.Services.Agent/HostContext.cs#L459

**Comment by fadnavistanmay** [comment]
Could you please try with one of the paths which are mapped and let us know if that works. Feel free to re-open if this doesn't solve your issue.

**Comment by sven5** [comment]
What's the solution here? I got this error after setting up a new pipeline with using the DevOps default template. 
I wonder why it doesn't work from scratch. ❓

**Comment by ainomc** [comment]
> @fadnavistanmay
> What's the solution here? I got this error after setting up a new pipeline with using the DevOps default template.
> I wonder why it doesn't work from scratch. ❓

Did you find a solution?

**Comment by billbarni** [comment]
Any solution to this?
