### ISSUE TITLE
UseDotNet@2 is not cross platform when proxy is configured

### ISSUE THREAD

**Issue by jsblock78** [microsoft/azure-pipelines-tasks#12343]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Private Agent, Ubuntu 18.04 LTS, 2.164.7

## Issue Description

The UseDotNet@2 task runs into issues when running under Linux with a proxy configured. It appears the task is attempting to execute NuGet.exe. Is this possible?

### From: Tasks/UseDotNetV2/nugetinstaller.ts
```
        // Set proxy url

        let nuget = tl.tool(nugetPath);

        nuget.arg('config');

        nuget.arg('-set');

        nuget.arg('http_proxy=' + proxyConfig.proxyUrl);

        nuget.exec({} as trm.IExecOptions);
```

### Task logs

```

Tool to install: .NET Core sdk version 2.2.x.

Found version 2.2.402 in channel 2.2 for user specified version spec: 2.2.x

Version: 2.2.402 was found in cache.

Creating global tool path and pre-pending to PATH.

Installing NuGet version 4.4.1

Found tool in cache: NuGet 4.4.1 x64

##[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache

Info_ResolvedToolFromCache 4.4.1

##[warning]Can\'t find loc string for key: Info_UsingVersion

Info_UsingVersion 4.4.1

Found tool in cache: NuGet 4.4.1 x64

##[warning]Can\'t find loc string for key: Info_UsingToolPath

Info_UsingToolPath /home/buildadmin/regshared2-1/_work/_tool/NuGet/4.4.1/x64

Prepending PATH environment variable with directory: /home/buildadmin/regshared2-1/_work/_tool/NuGet/4.4.1/x64

Setting up proxy configuration for NuGet.

##[error]Failed while installing NuGet version. Error: 4.4.1 Parameter 'toolPath' cannot be null or empty.
```

**Comment by vineetmimrot** [comment]
@jsblock78 Thanks for reporting the issue, we will try to resolve your query soon.

**Comment by anuragc617** [comment]
@jsblock78 Are you still facing this issue? If this is still happening, can you verify that the nuget is installed using which command?

**Comment by jsblock78** [comment]
@anuragc617 Does calling nuget.exe natively from Linux prompt actually work? That is what this task appears to be doing.

I was under the impression that nuget.exe only worked through mono.

**Comment by jsblock78** [comment]
I think the real solution here, is modifying the NuGet.config file using cross platform xml library (maybe even .net?).

Ultimately, the task is attempting to add a line (or lines) to an XML configuration file - by calling 'nuget.exe config'. Proxy configuration could be added dirctly via XML?

**Comment by anuragc617** [comment]
Looks like it`s a nuget tool installer issue @damccorm for futher assistance.

**Comment by damccorm** [comment]
Moving to artifacts who owns this. @anuragc617 for future reference you should be able to determine which team owns the task from https://github.com/microsoft/azure-pipelines-tasks/blob/master/issue-rules.yml

**Comment by edgarrs** [comment]
This is the dot net core tool installer task not the nuget installer. @bishal-pdMSFT, can you  please take a look at this?

**Comment by vineetmimrot** [comment]
Since the core duty of UseDotNetV2 to install the dotnet sdk and not setting up proxy, we have suppressed the nuget proxy setup error.

**Comment by AGreat1** [comment]
Hi! Wild guess here, but maybe this is because the tool is looked up as 'nuget', but in the tool folder it is in the 'NuGet' folder, and Linux is case-sensitive with file names?

**Comment by jsblock78** [comment]
> Hi! Wild guess here, but maybe this is because the tool is looked up as 'nuget', but in the tool folder it is in the 'NuGet' folder, and Linux is case-sensitive with file names?

Not sure it would make any difference. nuget.exe is a windows binary. As far as I know (at least when this defect was created) the nuget tool is not cross platform.
