### ISSUE TITLE
Azure Functions Core Tools Install task should install from CDN feed

### ISSUE THREAD

**Issue by ankitkumarr** [microsoft/azure-pipelines-tasks#12342]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Azure Functions Core Tools Install task installs from the Github release (https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/func-tools-common/functoolsutility.ts#L22). We would ideally like for it to be installed from our official tooling feed - https://functionscdn.azureedge.net/public/cli-feed-v3.json
The task would have to parse the JSON and pick the correct entry for the latest version.

While we try to make sure every github release of azure-functions-core-tools has artifacts, we have had cases when we have missed artifacts, and the install task seems to break.

**Enter Task Name**:  FuncToolsInstallerV0  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/FuncToolsInstallerV0/

**Comment by vithati** [comment]
@ajinkya599 , can you check this.

**Comment by ntodorov** [comment]
Hi @damccorm,
If you check https://github.com/microsoft/azure-pipelines-tasks/issues/12417 it is more of criticle bug, than enhancement, right?
We like users cannot get up and down versions or failing pipelines, if we use the "latest" option.

**Comment by ajinkya599** [comment]
Hi @ankitkumarr. Currently, we [query](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/func-tools-common/functoolsutility.ts#L38) for the latest GitHub release to figure out the latest version, which is a clean way to do so. `cli-feed-v3.json` doesn't have a latest version in the response.

Secondly, the FuncToolsInstallerV0 task can be run on any OS platform. `cli-feed-v3.json` doesn't seem to have binaries for Linux and macOS.

Ideally, the releases should have the right artifacts or there should be some other source which provides the latest version and binaries for all OS platforms.

**Comment by ankitkumarr** [comment]
Hi @ajinkya599, apologies for the delay here.

The `cli-feed-v3.json` has `tags` for each major version, which should be set as a property of the task I think (v2 or v3). The major version tag points to the latest release number, ex `2.47.1` for that version. The JSON with key `2.47.1` would then have `"standaloneCli"` key which has links for all supported environment and architecture binaries.

Though, I understand that this may be cumbersome, and we are thinking of having a more stable `latest` link. I will share when we do, so we can update the task then. Thanks!

Additionally, recently we added a new binary in the payload `gozip`. This binary needs to have executable permissions. Would it be possible to have something along `chmod a+x /usr/local/bin/azure-functions-cli/gozip` added for linux base environments? For reference -- https://github.com/Azure/azure-functions-core-tools/issues/1899

**Comment by ankitkumarr** [comment]
@ajinkya599, thanks for picking this up.

I think, at the least, if we add executable permissions to `gozip` similar to how we do with `func` here https://github.com/microsoft/azure-pipelines-tasks/blob/82c84a6fecd67c54375da64e11d66b3aab8641eb/Tasks/Common/func-tools-common/functoolsutility.ts#L76, it should fix the ongoing issue of being unable to publish.

**Comment by ankitkumarr** [comment]
@ajinkya599, Just wanted to check if there's plans to fix this. Right now, there's 3 major versions of Azure Functions Core Tools targeting 3 major versions of Functions. The "latest" tag in Github release could be either of these versions. This means that you could get either of these 3 versions when you download the way the DevOps task does now. This is a major issue as the 3 versions are drastically different in what languages they support and what runtimes they publish for. Here's an example of how this broke the task recently (it was trying to dowload v1) -- https://github.com/Azure/azure-functions-core-tools/issues/2279

I understand that we could ensure that the `latest` is always consistent, but having a dependency on Github releases and the file name format in the artifacts will continue to cause such issues.

We should be using the CDN feed as that will always be deterministic and our partners (VS, VS Code) also rely on that.

**Comment by ajinkya599** [comment]
@ankitkumarr Apologies for the delay in picking this up. I need some help to understand the right changes to make this task stable. In my understanding, there are two changes that are required. I have some questions regarding the same:

1. **Make `.../azure-functions-cli/gozip` executable in Linux env.** 
- _This is required only for Linux, nothing to be done for Windows/MacOs?_ 
- _Will this binary always exist, or is it only with the new releases?_
2. **Obtain download URL from [cli-feed-v3.json]( https://functionscdn.azureedge.net/public/cli-feed-v3.json).** 
- _It seems for newer versions, the release has `standaloneCli` property that gives `downloadLink` based on OS and architecture. But with older versions, this property seems to be missing. Can you help define the right behaviour for choosing the download URL?_
- _Currently, we look for either `latest` or a valid `semver` version (ex. `2.18.4` or `v2.18.4`). Should we add special case handling for `v1`, `v2`, `v3` and pick the corresponding release? If we want to support other possible tags as well (ex. `v2-prerelease`), then we will need to come-up with a more general solution._

**Comment by ds-ms** [comment]
Closing this stale issue. Feel free to reopen if the problem still persists
