### ISSUE TITLE
HelmInstaller@v1 and "latest"

### ISSUE THREAD

**Issue by shoorik** [microsoft/azure-pipelines-tasks#12356]
Currently if you specify helmVersionToInstall="latest" or don't specify helmVersionToInstall at all (defaults to latest), the task defaults to fetching whatever is at https://api.github.com/repos/helm/helm/releases/latest. 

Unfortunately that API is meant to only indicate which release was pushed to github last, NOT the typical meaning of "latest recommended". Today, version 3.1.0 was released, showed up on latest for a few hours, and then 2.13.6 was released, forcing our pipelines to install 2.13.6 and try to deploy charts designed for helm 3.x, which are incompatible with helm 2.x

Perhaps this is an enhancement: specify a major version `helmVersiontoInstall="3.x"` to indicate that the user would like to use latest version on the 3 major and have HelmInstaller (kubernetes-common-v2/helmutility.ts in getStableHelmVersion) crawl all the releases at https://api.github.com/repos/helm/helm/releases to find the largest release of that major.

Theoretically work on Helm 2 is winding down, but it's unlikely that work on it stops altogether and it would be very frustrating to have to decide between pinning to very specific version of helm 3 or suffer occasional pipeline breaks whenever 2 is patched. 

Plus, one could imagine helm 4 arriving.

**Comment by petrformanek** [comment]
Yep we are facing this issue today.
Please fix as @shoorik suggests.

**Comment by vithati** [comment]
This is smillar to #12369 . We will track this through #12369  issue hence closing the issue.

**Comment by sudolibre** [comment]
@vithati #12369 turned out to be a different issue. Please see the following for how helm pulls the latest version: https://github.com/helm/helm/issues/7597#issuecomment-586424552

**Comment by shoorik** [comment]
@vithati perhaps this package can be used to assist with the enhancement: https://docs.npmjs.com/misc/semver

**Comment by eyeats** [comment]
This is breaking one of our pipelines, is anyone looking into this issue?

**Comment by shoorik** [comment]
@eyeats Not to my knowledge. For now the workaround has been to explicitly request version 3.1.0:

```
- task: HelmInstaller@1
   inputs:
     helmVersionToInstall: '3.1.0'
```
You'll have to keep an eye on https://github.com/helm/helm/releases yourself and upgrade to whatever the latest version you're comfortable with.

(That's if you're wanting to stick with using this task, the alternative is to hand roll a bash task to find the version you need automatically and install it.)
