### ISSUE TITLE
Azure App Service Deployment task not responding to completed job

### ISSUE THREAD

**Issue by ADringer** [microsoft/azure-pipelines-tasks#12351]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service Deployment 

## Environment
- Server - Azure Pipelines

## Issue Description

When running the following job:

```
jobs:
- deployment: productcomparison_web     
  environment: 'popup'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none
        - download: current
          artifact: productcomparison.web
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: AzureRM
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: webAppLinux
            WebAppName: $(webAppName)
            packageForLinux: $(Pipeline.Workspace)/productcomparison.web/ProductComparison.Web.Spa.zip
```

The output shows that the deployment task completed:

```
Successfully updated deployment History at https://mee-productcomparison-apatx.scm.azurewebsites.net/api/deployments/40491581589842752
##[debug]Active DeploymentId :40491581589842752
##[debug][POST]https://management.azure.com/subscriptions/0545ac5f-6ba8-4965-a154-34d38d661bfd/resourceGroups/popup-apatx/providers/Microsoft.Web/sites/mysite/publishxml?api-version=2016-08-01
##[debug]Could not parse response: {}
##[debug]Response: undefined
##[debug]Correlation ID from ARM api call response : bb70a2e6-d459-4849-abc4-4d77edd2485a
App Service Application URL: https://mysite.azurewebsites.net
##[debug]set AppServiceApplicationUrl=https://mysite.azurewebsites.net
##[debug]Processed: ##vso[task.setvariable variable=AppServiceApplicationUrl;issecret=false;]https://mysite.azurewebsites.net
##[debug]ZIP DEPLOY - Performing post zip-deploy operation: 5160f996d3c548949c878652479d628d => 40491581589842752
##[debug]setting affinity cookie ["ARRAffinity=83b234b4461469d671f8a72ba323eeb3a8b17cbc4df9958c37cd0e6fdb5b41cc;Path=/;HttpOnly;Domain=mysite.scm.azurewebsites.net"]
##[debug][GET]https://$mee-productcomparison-apatx:***@mysite.scm.azurewebsites.net/api/vfs/site/deployments/5160f996d3c548949c878652479d628d/manifest
##[debug]Could not parse response: {}
##[debug]Response: undefined
##[debug]getFileContent. Status code: 200 - OK
##[debug]AGENT.TEMPDIRECTORY=/home/vsts/work/_temp
##[debug]setting affinity cookie ["ARRAffinity=83b234b4461469d671f8a72ba323eeb3a8b17cbc4df9958c37cd0e6fdb5b41cc;Path=/;HttpOnly;Domain=mysite.scm.azurewebsites.net"]
##[debug][PUT]https://$mee-productcomparison-apatx:***@mysite.scm.azurewebsites.net/api/vfs/site/deployments/40491581589842752/manifest
##[debug]uploadFile. Data: {"statusCode":201,"statusMessage":"Created","headers":{"last-modified":"Thu, 13 Feb 2020 10:30:52 GMT","etag":"\"1018d7cc6fb0d708\"","server":"Kestrel","date":"Thu, 13 Feb 2020 10:30:51 GMT","connection":"close","content-length":"0"}}
##[debug]ZIP DEPLOY - Performed post-zipdeploy operation.
##[debug]Deployment Succeded
```

However the actual job doesn't report it as being finished, it just continues in the state or 'running'. 

This was working previously, and is happening to all our yaml releases.

**Comment by chshrikh** [comment]
@ADringer you are seeing your task got completed but deployment job does not finished, it still shows as in-progress ?

**Comment by ADringer** [comment]
@chshrikh other way round. The web app does get deployed, I can browse to it but the DevOps task doesn't finish, that stays running

**Comment by ADringer** [comment]
Bit more detail, I've found the AzureRmWebAppDeployment@4 task quite flakey the past few days. Rerunning the same pipeline has resulted in the deployment succeeding, failing, or deploying but the task not completing.

For now I've resorted to using `az webapp deployment source config-zip` instead as this seems to be a bit more reliable.

**Comment by ADringer** [comment]
Actually that still doesn't consistently deploy the app. Sometimes it works, sometimes it fails with 'An unknown error has occurred. Check the diagnostic log for details.' but can't see any error in the logs, or sometimes just takes forever till it times out. Thinking the issue could be Kudu related?

**Comment by SumiranAgg** [comment]
@ADringer Are you still seeing this issue?

**Comment by ADringer** [comment]
Not anymore, it seemed unstable for about a week but now has resolved itself. Might have been an issue with Kudu?

**Comment by SumiranAgg** [comment]
Yes seems like it was an issue with app service or kudu. Good to know it is resolved now. I am closing the issue for now. Please feel free to re-open if required.
