### ISSUE TITLE
DacPac Logs Misleading

### ISSUE THREAD

**Issue by Prithvitm** [microsoft/azure-pipelines-tasks#12357]
I have a dacpac script that adds two columns to an existing table and adds those two columns into included fields of an existing non clustered index. 

Since, the number of columns in the table are 60 million, hence the creation of non clustered is expected to take time. After 60 seconds (which is the CommandTimeout value in DacPacOptions), the creation of non clustered index is timing out, which is expected. But along with that error,  the logs also says a runtime error: the Column was not found in the target table while creating non clustered index. This is misleading and needs a fix.

**02-06-2020   18:39:36** | DacEvent:   Altering [My].[Table]...
-- | --
**02-06-2020   18:39:36** | DacEvent:   Creating   [My].[Table].[IX_NonClusteredIndex]...
**02-06-2020   18:40:36** | DacEvent:   Execution Timeout Expired. The timeout period elapsed prior to completion of   the operation or the server is not     responding.
**02-06-2020   18:40:39** | DacEvent:   .Net SqlClient Data Provider: Msg 1911, Level 16, State 1, Line 1 Column name   'NewColA' does not exist in the target table or view
**02-06-2020   18:40:39** | DacEvent:   Script execution error. The executed script: CREATE NONCLUSTERED INDEX   [IX_NonClusteredIndex] ON   [My].[Table]([ConSysId] ASC, [OldColA] ASC,   [OldColB] ASC) INCLUDE([OldColC], [OldColD],   [NewColA], [NewColB]) WHERE [OldCoA] IS NOT NULL ON   [PS_Uniqueidentifier] ([ConSysId]);
**02-06-2020   18:40:39** | DacEvent:   An error occurred while the batch was being executed.

**Comment by chshrikh** [comment]
@Prithvitm could you please share more details like which task you are using, if possible share the release/build logs.

**Comment by Prithvitm** [comment]
I have used 150.4573.2 version of Microsoft.SqlServer.DacFx.x64 dll.

**Comment by Prithvitm** [comment]
To get rid of error "Timeout Expired" during dac-pac deployment, use latest version of DacFx library (i used 150.4573.2 version) and set "LongRunningCommandTimeout" configuration value in DacDeployOptions to a higher value.

**Comment by chshrikh** [comment]
@Prithvitm I am assuming the error you reported was not in context with AzureDevOps task. If you have any issue relate to azuredevops task please feel free to reopen this
