### ISSUE TITLE
Visual Studio Test Task doesn't set env variable of current attempt when rerunning failed tests

### ISSUE THREAD

**Issue by nvborisenko** [microsoft/azure-pipelines-tasks#12352]
When running unit tests, VSTest task sets some list of environment variables like `TE.RerunFailedTests` or `DTA.RerunFailedTestCasesMaxLimit` or `TE.RerunMaxAttempts`. These environment variables are also available for test, that's useful.

When task reruns failed tests, in console output we see:
```
2020-02-12T16:01:37.6663270Z **************** Rerunning failed tests for Test run 1000048 *********************
2020-02-12T16:01:37.6663989Z Max attempts: 3; Current attempt: 1; Failed test cases threshold: 30; Failed test cases max limit: 0
```

All this information is available via environment variables, but not for `Current attempt: 1`.

It would be nice if Task/DTAHost will set environment variable. Then test would see this variable and apply additional business logic, or something else.

Screenshot of task configuration:
![image](https://user-images.githubusercontent.com/22616990/74428097-6ae2c300-4e69-11ea-9eea-49399d2b0866.png)

**Comment by ShreyasRmsft** [comment]
@nvborisenko ideally the tests should be isolate and not be aware of logic of how they are being run. But nevertheless we will tag this is as an enhancement and review/pick it up based on priority.

**Comment by nvborisenko** [comment]
Simpler real use case: let's say I have `HmlLogger`, this logger produces html report at the end of tests execution.

I executed 100 tests, got 2 failed. I see it in `MyReport_1.html`.
Azure is rerunning 2 failed tests, and I am getting `MyReport_2.html` which contains only 2 tests. This fact is confusing me, where are my 100 tests?!.

If `HtmlLogger` had ability to understand whether 2 tests had run in "rerun session", it would append report to an existing html file instead of creating new one. It allows me to open report and see all my 100 tests, where 2 tests were executed several times.

**Comment by ShreyasRmsft** [comment]
@nvborisenko why not use the in-built reporting experience we have? It does precisely this. Is there some other gap in our current reporting experience that is preventing you from using it?

**Comment by nvborisenko** [comment]
Built-in reporting mechanism is not kind of real-time reporting. I have many UI tests, and let's say total duration of execution is several days. The final report becomes available after all tests are executed. I would like to start tests analysis as soon as the first test passes, in parallel of others tests execution like http://reportportal.io does.

**Comment by ShreyasRmsft** [comment]
Turn on custom batching in the vstest task under advanced execution settings with a small batch size, you should get real time reporting.

**Comment by nvborisenko** [comment]
Thanks for the tips. I expect DTA (which is not open sourced?.) will be more friendly to custom Loggers.

**Comment by ShreyasRmsft** [comment]
Nope it is not open source today. Depends on the logger and what functionality you are looking for. This suggestion was purely to get continuous reporting since that was a requirement on your end.

**Comment by PBoraMSFT** [comment]
@nvborisenko - thank you for outlining your scenario. We have added this to the backlog, but it is not top of the priority stack at this time, so I do not have an ETA to share.

**Comment by nvborisenko** [comment]
Not a problem, thank you and will glad to see it as resolved. Hope it's easy fix.

**Comment by nvborisenko** [comment]
Still awaiting it to be implemented.

**Comment by nishantms** [comment]
@shashban : can you please help with this

**Comment by nvborisenko** [comment]
Still awaiting it to be implemented.

**Comment by nvborisenko** [comment]
Still awaiting it to be implemented.

**Comment by nvborisenko** [comment]
Closed without attention.
