### ISSUE TITLE
DownloadPipelineArtifact should log the full pathname(s) of all the files it creates

### ISSUE THREAD

**Issue by zackw** [microsoft/azure-pipelines-tasks#12368]
**Question, Bug, or Feature?**  Feature

**Enter Task Name**: DownloadPipelineArtifact

## Environment

- Server - Azure Pipelines
    - account: zackw0744
    - I'm not sure what "team project name", "build definition name", and "build number" mean, but a build log that illustrates what I'm asking for is <https://dev.azure.com/zackw0744/objconv/_build/results?buildId=85>
    
- Agent - Hosted or Private:  Hosted.

## Issue Description

The logs from a `DownloadPipelineArtifact@2` task do not include the pathnames of the files created (on the agent) by the task.  This makes it hard to troubleshoot subsequent build steps that fail because the downloaded files aren't where the author of `azure-pipelines.yml` thought they would be.

For example: from the above build log, this task failed because a downloaded artifact wasn't in the expected place:

https://dev.azure.com/zackw0744/15f121ad-d0c1-4aae-ad9f-58e0ea42201e/_apis/build/builds/85/logs/28

The matching download task is

https://dev.azure.com/zackw0744/15f121ad-d0c1-4aae-ad9f-58e0ea42201e/_apis/build/builds/85/logs/22

and, as you can see, it does not print out where it actually put the artifact.

Please make `DownloadPipelineArtifact@2` log the full pathname of each file it creates on the agent.

**Comment by herenhuang** [comment]
Hey Zack, 

Thanks for this suggestion. We're tracking this feature request on our backlog now to have additional logging with the DownloadPipelineArtifact task. I'm going to close this issue for now. :)

**Comment by abatishchev** [comment]
+1. Right now running the pipeline with diagnostic logs on adds nothing to the output of DownloadPipelineArtifact.

**Comment by Timo-Weike** [comment]
+1 would also appreciate it if this would be implemented.

**Comment by abatishchev** [comment]
@damccorm please reopen. The fact this issue hasn't been addressed for whooping 180 days is a good reason to escalate and prioritize, not the other way around and close it.

**Comment by anatolybolshakov** [comment]
Hi @abatishchev I reopened it since it's still actual.
