### ISSUE TITLE
Incorrect documentation link in BashV3?

### ISSUE THREAD

**Issue by dy-lan** [microsoft/azure-pipelines-tasks#12363]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: BashV3

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/BashV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: N/A

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Documentation links to different task name. This [line](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/BashV3/Strings/resources.resjson/en-US/resources.resjson#L3) includes a link to https://go.microsoft.com/fwlink/?LinkID=613738, which links to a `Shell Script task`, not the `Bash task` found [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops). Which doc should be linked to `BashV3`? In Azure DevOps, when I search for 'bash', the bash task shows up as an option. But when I search 'shell script', a task with that name does not show up. The [ShellScriptV2](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/ShellScriptV2) task has been committed to more recently than BashV3. Are these actually two separate tasks, or is the ShellScriptV2 supposed to be replacing BashV3?

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by jtpetty** [comment]
@damccorm - Can you take a look at this?

**Comment by anton-erofeev** [comment]
Hi, @dy-lan !
They’re the same task, BashV3 is a newer version and we recommend using it instead of ShellScriptV2. 
Thank you for your participation, the link was really wrong, this is fixed in this PR https://github.com/microsoft/azure-pipelines-tasks/pull/13047
Updated link: [go.microsoft.com/fwlink/?linkid=2132213](https://go.microsoft.com/fwlink/?linkid=2132213)

**Comment by anton-erofeev** [comment]
Hi @dy-lan,
These changes were deployed in the latest release
