### ISSUE TITLE
Xcode Pipeline Task: Support for Xcode 11

### ISSUE THREAD

**Issue by ingo-1492** [microsoft/azure-pipelines-tasks#12373]
pls support Xcode 11 in pipeline tasks (@6)

![Screenshot 2020-02-18 at 11 13 59](https://user-images.githubusercontent.com/61186186/74726530-ebc20600-523f-11ea-9050-ed1dca636cc9.png)

**Comment by maxim-lobanov** [comment]
Hi @ingo-1492 , As a temporary solution, you can choose specify option `Specify path` and [use this link](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md) to find the list of installed Xcode versions
