### ISSUE TITLE
Support for packer -var-file

### ISSUE THREAD

**Issue by mbrancato** [microsoft/azure-pipelines-tasks#12378]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PackerBuild

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

- Agent - Hosted or Private:  Hosted
 
## Issue Description

It would be nice if we could pass a variables file (e.g. vars.json) to packer that lives in the main source so as to keep fewer modifications to the pipeline code. If we are setting component versions in these variables, that means we need to edit the pipeline code.

**Comment by NK74** [comment]
No replies since 19 february 👍
