### ISSUE TITLE
Overwriting readonly task variable 'agent.jobstatus'

### ISSUE THREAD

**Issue by doggy8088** [microsoft/azure-pipelines-tasks#12371]
## Required Information

**Question, Bug, or Feature?**  
Question

**Enter Task Name**: `Shell Exec`

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version:  `N/A`
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: `willh`, `ngcli-docker`, `Build GA Versions`/`20200218.3`.

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: `ubuntu-18.04`

    - If using private agent, provide the OS of the machine running the agent and the agent version: `N/A`

## Issue Description

I'm trying to cancel build with a condition in one of my Shell Exec task. I tried this:

```sh
echo "##vso[task.setvariable variable=agent.jobstatus;]canceled"
echo "##vso[task.complete result=Canceled;]DONE"
```

It works. But I also got this:

```log
##[warning]Overwriting readonly task variable 'agent.jobstatus'. This behavior will be disabled in the future. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
```

I'm worried that this solution might be broken someday. What else I can do in my purpose?

### Task logs

```log
##[section]Starting: Build GA Releases
==============================================================================
Task         : Shell Exec
Description  : Execute shell commands without creating a shell file
Version      : 0.2.0
Author       : Tsuyoshi Ushio
Help         : Replace with markdown to show in help
==============================================================================
[command]/bin/bash ./.tempexecution.sh
(node:3119) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3119) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3119) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3119) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3119) Warning: Use Cipheriv for counter mode of aes-256-ctr

##[warning]Overwriting readonly task variable 'agent.jobstatus'. This behavior will be disabled in the future. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
##[section]Finishing: Build GA Releases
```

## Troubleshooting
N/A

### Error logs
N/A

**Comment by damccorm** [comment]
Hey @doggy8088 - since cancelled means "cancelled by the user" we don't support a way of doing this from within your pipeline steps. The correct way to implement this pattern is to do your check, set a variable (if single-job) or output variable (if the answer affects multiple jobs), and check that variable in the condition for subsequent tasks. Something like:

```yaml
steps:
- script: |
    # compute "should I continue" somehow
    echo ##vso[task.setVariable variable=continue]true
- task: foo@1
  condition: and(succeeded(), eq(variables.continue, 'true'))
- task: bar@1
  condition: and(succeeded(), eq(variables.continue, 'true'))
```

See https://github.com/microsoft/azure-pipelines-yaml/issues/439 for more conversation on this. I'm going to close here, I'd recommend following up in that issue if you have any further questions
