### ISSUE TITLE
Timeout for job queued or waiting for an agent - self-hosted agent

### ISSUE THREAD

**Issue by linuxandunix** [microsoft/azure-pipelines-tasks#12370]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: bash task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://abilityplatform.visualstudio.com/, Ability Platform

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu 18.04, 2.164.1

## Issue Description

I want to know if there is an option to set timeout for jobs queued or waiting for an agent(self-hosted agent).
As per [(https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml ]
)
"The timeout period begins when the job starts running. It does not include the time the job is queued or is waiting for an agent."

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by vtbassmatt** [comment]
There is not. Please feel free to file a feature request on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) and describe your scenario. Thanks!

**Comment by subhajitm** [comment]
Its been more than 2 years now. Has this feature been added?

**Comment by ocomes** [comment]
No news?
