### ISSUE TITLE
HelmInstaller behind a corporate proxy

### ISSUE THREAD

**Issue by ibacci** [microsoft/azure-pipelines-tasks#12375]
**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: HelmInstaller@1

## Issue Description

We have the agent running in our private network, and configured to use out company proxy. The agent is configured to use our proxy (it installs and correcty connect using proxy). 
The HelmInstaller seems to not use the proxy, if I curl from the machine https://get.helm.sh/helm-v3.1.0-linux-amd64.zip the file is downloaded correctly, but the agent task does not work, as it is not using the proxy. 
Is the proxy correcty enabled in this task?

**Comment by vithati** [comment]
Task uses helm release locations directly to download. https://github.com/microsoft/azure-pipelines-tasks/blob/6b16ac5f867aa62d7e60f36f1b56568183865ad5/Tasks/Common/utility-common-v2/helmutility.ts#L51. Try using script task to download helm if task not working.

**Comment by dirien** [comment]
What is the sense of this task? Why not extend it to honor the proxy?

we are also running with a corporate proxy here, so it is more common and the task could reflect this.

**Comment by dnperfors** [comment]
@dirien, A work around for this is setting the `http_proxy` and `https_proxy` environment variables (and possibly the `no_proxy` variable as well) this will cause the task to go through the proxy,
