### ISSUE TITLE
Please create a download version of this

### ISSUE THREAD

**Issue by netdragonboberb** [microsoft/azure-pipelines-tasks#12384]
This is great, but please Microsoft also create a scp download version of this. Using Task "Download Secure file" with sshpass and scp is inscure. The only alternative[ "SFTP / SSH](https://marketplace.visualstudio.com/items?itemName=adacta.azdevopsSFTP)" is Windows-only and I can't get it to work, but if it or this one can be adapted as a Microsoft-provided task (and cross-plaform) that would be great.

**Comment by damccorm** [comment]
Hey @netdragonboberb I don't think we're going to invest in this from our end at this point. I'd recommend reaching out to the owners of the task you linked to directly here- https://github.com/Adacta/Azure-DevOps-SFTP-SSH-download/issues
