### ISSUE TITLE
GoTool: Verify checkums of downloaded files

### ISSUE THREAD

**Issue by fdcds** [microsoft/azure-pipelines-tasks#12393]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature
**Enter Task Name**: GoTool  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

GoToolV0 does not appear to verify the downloaded files. I would expect it compare the file's checksum with an expected checksum and bail out if the two do not match.

**Comment by ret394** [comment]
>  I would expect it compare the file's checksum with an expected checksum and bail out if the two do not match.

to add, please make it optional.

thanks. have a nice day. keep up the good work.

[ret394](https://github.com/ret394)
