### ISSUE TITLE
Task Container Structure Test cannot publish test results

### ISSUE THREAD

**Issue by balfa666** [microsoft/azure-pipelines-tasks#12396]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Container Structure Test

## Environment
- Server - Azure Pipelines ?
    - https://dev.azure.com/investpsp/Datahub/_build?definitionId=94&_a=summary

- Agent - Hosted or Private: 
    
    - Azure Pipelines
    - Image: ubuntu-latest

## Issue Description

The task does not seem to be able to publish test results. I have the following warning in the execution.

##[warning]Failed to publish test run data: System.ArgumentException: Unknown test runner
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestDataPublisher.ParseTestResultsFile(TestRunContext runContext, List`1 testResultFiles)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestDataPublisher.PublishAsync(TestRunContext runContext, List`1 testResultFiles, PublishOptions publishOptions, CancellationToken cancellationToken)

**Comment by daniel-taniel** [comment]
I'm also experiencing this issue. Exact same environment and error message as balfa666

**Comment by ssaarinen** [comment]
This is still happening. Any workarounds or ideas what might be causing it?

**Comment by GuidoK1** [comment]
I am also experiencing this issue: #18728 . Any help or workarounds?
