### ISSUE TITLE
Shared Image Gallery Destination Version Variable not passing through

### ISSUE THREAD

**Issue by dapolloxp** [microsoft/azure-pipelines-tasks#12403]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://dev.azure.com/apolinarorg2/ContainerRegistryPush/_build

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Mac Catalina

## Issue Description

[Include task name(s), screenshots and any other relevant details]

When using the Packer Task, I am not able to pass the Managed Image Version. The variables never makes it into the Packer File. For example, if I pass in a variable from the pipeline that sets this value: "image_version": "{{user `build_version`}}", it never makes it to the packer image. If I run this locally on my machine, it works perfectly fine.

"shared_image_gallery_destination": {
      "resource_group": "{{user `managed_image_resource_group_name`}}",
      "gallery_name": "GalleryName",
      "image_name": "CentOS7",
      "image_version": "{{user `build_version`}}",
      "replication_regions": ["eastus2"]
   },

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by adriandiver** [comment]
Any news regarding this issue?
