### ISSUE TITLE
Kubectl: Failure when using release variables in K8s Service connection 

### ISSUE THREAD

**Issue by luca-esse** [microsoft/azure-pipelines-tasks#12400]
*Type*: Bug

**Task Name**: KubernetesV1

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesV1

## Environment
- Server - Azure Release Pipelines

- Agent - Hosted: 
    
    - Agent queue name: Azure Pipelines (Default)

## Issue Description

This issue is similar to the bug #11920 that i've previously reported.

When we try to save a new/existing release pipeline with the following k8s service connection: "miranda-aks-$(Release.EnvironmentName)", the following error appears:

_VS402913: The release pipeline cannot be saved because the stage 'alpha' references a service connection that cannot be found, or that you do not have permission to access. Details: 'Task 'kubectl create configmap' is using service connection '00000000-0000-0000-0000-000000000000',Task 'kubectl create secret' is using service connection '00000000-0000-0000-0000-000000000000',Task 'kubectl apply' is using service connection '00000000-0000-0000-0000-000000000000''_

## Troubleshooting
When setting the service connection to a fixed string like "miranda-aks-alpha" or with custom variable like "miranda-aks-$(SomeVarName)", the pipeline can be saved as expected. 

The problem seems to occur when using the predefined release variable.
The existing pipelines with this configuration are working as expected so it seems to be a validation problem.

## Screenshots
![image](https://user-images.githubusercontent.com/16616566/75022150-db0acd80-5495-11ea-8607-975b50870167.png)
![image](https://user-images.githubusercontent.com/16616566/75022189-eb22ad00-5495-11ea-93c6-1d9645feb588.png)

**Comment by ds-ms** [comment]
@josh-01 to take a look

**Comment by Josh-01** [comment]
Hi @luca-esse ,

A code change to fix a security flaw is why now it throws an error for 'save' when predefined variables like 'Release.EnvironmentName' are used in Service Connection name
Predefined variables are not resolved during save of RD, but later when the release is created and run.
Instead you could use **Stage** variables for this purpose, which are resolved during RD 'save/update'. 

Please let me know if any doubts/questions.

Thanks!

**Comment by Josh-01** [comment]
Closing issue. Kindly reopen if issue persists.

**Comment by mwc360** [comment]
I am having the same issue but I am using an **environmentCode** library variable that is linked from my key vault. The service connection has access to the key vault. I'm guessing this is because the KV isn't pinged upon save/update so it can't validate the RD. When the library variable isn't linked it works fine.
