### ISSUE TITLE
ServiceFabricDeploy should support dynamic application names

### ISSUE THREAD

**Issue by henry-padilla** [microsoft/azure-pipelines-tasks#12402]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeploy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricDeployV1

## Environment
- Server - Azure Pipelines
Account: WKAxcess    
Team Project: Axcess
Deffinition: 2379

- Agent - Hosted
Hosted Windows 2019 with VS2019

## Issue Description

Service fabric can create dynamic applications (based on "root" applications) but there is no way to update them.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anuragc617** [comment]
Hi @henry-padilla, sorry I don't get it. Can you explain a bit more about the bug, also can you provide logs??

**Comment by padillah** [comment]
I cannot provide logs for something the task doesn't do.

We have a Service Fabric Application that we copy to create several dynamic Applications. There is currently no way to update those dynamic applications.

Given an application "AppRoot" if you deploy that to Service Fabric you will have an ApplicationType "AppRootType" and an application "AppRoot". If I use "AppRoot" to create a new application called "AppRoot-001" and "AppRoot-002" those will run fine.
But when I upgrade "AppRoot" to version 1.5 it doesn't upgrade "AppRoot-001" nor "AppRoot-002". The best I can do is to remove those and have the system recreate them. But if they are doing work I can't just remove them.

Does that help?
