### ISSUE TITLE
Add support for helm3 bake engine in KubernetesManifest

### ISSUE THREAD

**Issue by celambert** [microsoft/azure-pipelines-tasks#12405]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: KubernetesManifest  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesManifestV0

## Environment
Azure Pipelines

- Agent - Hosted or Private: 
Hosted

## Issue Description
Add support for Helm3 as bake engine.

### Task logs
Currently, the task only allows for Helm2 as bake engine
```
export async function bake(ignoreSslErrors?: boolean) {
    const renderType = tl.getInput('renderType', true);
    let renderEngine: RenderEngine;
    switch (renderType) {
        case 'helm2':
            renderEngine = new HelmRenderEngine();
            break;
        case 'kompose':
            renderEngine = new KomposeRenderEngine();
            break;
        case 'kustomize':
            renderEngine = new KustomizeRenderEngine();
            break;
        default:
            throw Error(tl.loc('UnknownRenderType'));
    }
    await renderEngine.bake();
}
```

Ideally, we can specify as we do in the HelmInstallerV1 the version of Helm and an option to check for the latest version. This an issue with charts with apiVersion v2 as helm breaks between version. Other tasks support helm3 but this one needs to be updated.

**Comment by syedhassaanahmed** [comment]
+1 to Helm 3 support. We really don't want to use Tiller which Helm 2 forces us to.

**Comment by ds-ms** [comment]
There's a PR out for this. https://github.com/microsoft/azure-pipelines-tasks/pull/12560

Closing this as it's a duplicate issue. Tracking it here: https://github.com/microsoft/azure-pipelines-tasks/issues/12511
