### ISSUE TITLE
No Azure Container Registry service connection settings in Azure Web App for Containers task in Azure DevOps Release Pipeline

### ISSUE THREAD

**Issue by KumareshBabuNS** [microsoft/azure-pipelines-tasks#12419]
I have multi-container application. I have pushed the docker images to ACR through Azure Build Pipeline. From the release pipeline, I'm using Azure Web App for Containers task to deploy my application on the app service. I'm facing unauthorized permission issue while pulling the images from Azure Container Registry. I didn't find option to provide the service connection for ACR in this task. Can anybody help me on this?

**Comment by JerryWang20** [comment]
is the issue resloved?

**Comment by xsurfer** [comment]
Hi, is there any resolution for this? I created a Service Connection using CLI but it is not visible to any pipelines.
