### ISSUE TITLE
Publish Test Results: Failing to publish test results for JUnit .xml files

### ISSUE THREAD

**Issue by dschrock42** [microsoft/azure-pipelines-tasks#12421]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: mitek, Steel Framing Systems - DesignSuite, Design (1), #20200226.5 Update azure-pipelines-1.yml for Azure Pipelines

https://mitek.visualstudio.com/Steel%20Framing%20Systems%20-%20DesignSuite/_build/results?buildId=7797&view=results

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      Private
 Windows Server 2012 R2
 Agent Version: 2.165

## Issue Description

Publish Test Results task is failing to publish a JUnit XML Result file from Test Complete.  This was working fine in version 2.162.2 but fials in the version now being used 2.164.3.  I have tracked it down to the change made in commit 3b68a25b536927850b1efa61c4d09272e504c994.  It looks like we are not getting a PTR_TEST_RUNSUMMARY.json file in the temp directory and hence the method looking for that file fails, which results in the tests not getting published.  

  
![image](https://user-images.githubusercontent.com/61506970/75354843-dca80d00-586a-11ea-9f68-78636b81fad2.png)

JUnit Results File:
[Can873_Results.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4256343/Can873_Results.zip)

### Task logs

[logs_7797.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4256318/logs_7797.zip)

## Troubleshooting

Manually reverted to a previous version and it works fine.                  

Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

![image](https://user-images.githubusercontent.com/61506970/75355504-d8302400-586b-11ea-9597-444cfaefb29e.png)

**Comment by suyash691** [comment]
Can you please let us know what is the .NET framework version installed on the build agent machine?

If the .NET framework version installed on the machine is 4.6.1 or less than that then can you please try upgrading the .Net framework version to 4.6.2.

**Comment by dschrock42** [comment]
My installed .net version was 4.5.1.  I did an upgrade of .net and it does appear that that was the issue.  The task is now working properly.  So, it looks like it was just an issue with the installed .net version.

Thanks,
Dave Schrock
