### ISSUE TITLE
Can't publish test results: 'Could not load file or assembly...'

### ISSUE THREAD

**Issue by kodmis** [microsoft/azure-pipelines-tasks#12420]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
devopsfs , MES, QFS_CI, QFS_CI_development_20200226.2
https://dev.azure.com/devopsfs/MES/_build/results?buildId=4729&view=logs&j=9ff06774-4118-58a1-197e-51b036c0a1fb&t=41c39b71-4bc7-59bb-0803-d027243b02e1    

- Agent - Hosted or Private: 
Private   
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows Server 2016 Version 1607
agent version '2.165.0' 

## Issue Description

Can't publish test results with task :
``` yml
- task: PublishTestResults@2
  displayName: 'Публикация результатов тестов из junit/*.xml'
  inputs:
    testResultsFiles: 'junit/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    condition: succeededOrFailed()
```
because of error: 
`Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.`

### Task logs
[logs_4729.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4255777/logs_4729.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[warning]Failed to publish test run data:  Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by navin22** [comment]
Hi @kodmis,
What's the .net version installed on the agent machine? Can we upgraded it to the latest version ([link](https://dotnet.microsoft.com/download/dotnet-framework))?

**Comment by kodmis** [comment]
``` cmd
>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\CDF
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0

>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client\1033"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client\1033
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    Release    REG_DWORD    0x60632
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.6.01586

>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    Release    REG_DWORD    0x60632
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.6.01586

>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0\Client"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0\Client
    Install    REG_DWORD    0x1
    Version    REG_SZ    4.0.0.0
```
Installing the latest version of .NET Framework is difficult due to approvals. Is the latest version really necessary to fix this error?

**Comment by navin22** [comment]
As many nuget packages are not supporting the .net 4.5 we had to upgrade it to the 4.6 or higher.
This was changed in [some of the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#check-prerequisites) as well now.

It's necessary to get rid of this error.

**Comment by kodmis** [comment]
But there is already 4.6.2 version. [Look ](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed):
``` cmd
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033
    Release    REG_DWORD    0x60632
```
0x60632 = 394 802
release 394 802 does mean .NET Framework 4.6.2

And at last week at same machine test results published successfully:
```
2020-02-21T13:55:01.2770930Z ==============================================================================
2020-02-21T13:55:01.2771190Z Task         : Publish Test Results
2020-02-21T13:55:01.2771404Z Description  : Publish test results to Azure Pipelines
2020-02-21T13:55:01.2771606Z Version      : 2.164.3
2020-02-21T13:55:01.2771975Z Author       : Microsoft Corporation
2020-02-21T13:55:01.2772245Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
2020-02-21T13:55:01.2772552Z ==============================================================================
2020-02-21T13:55:02.0875332Z [command]C:\ProgramData\AgentWork\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.164.3\modules\TestResultsPublisher.exe @C:\ProgramData\AgentWork\_temp\c1842930-54b1-11ea-977a-e92fa81b0d6d.txt
2020-02-21T13:55:14.1313201Z No build level attachments to publish.
2020-02-21T13:55:15.4445542Z Result Attachments will be stored in LogStore
2020-02-21T13:55:15.7133456Z Run Attachments will be stored in LogStore
2020-02-21T13:55:17.1297018Z Publishing test results to test run '1008316'.
2020-02-21T13:55:17.1312510Z TestResults To Publish 14, Test run id:1008316
2020-02-21T13:55:17.1359713Z Test results publishing 14, remaining: 0. Test run id: 1008316
2020-02-21T13:55:20.8737985Z Published Test Run : https://dev.azure.com/devopsfs/MES/_TestManagement/Runs?runId=1008316&_a=runCharts.
2020-02-21T13:55:22.6461814Z ##[error]There are one or more test failures detected in result files. Detailed summary of published test results can be viewed in the Tests tab.
2020-02-21T13:55:22.6989530Z ##[section]Async Command Start: PublishTestResultsToEvidenceStore
2020-02-21T13:55:22.6989908Z ##[section]Async Command End: PublishTestResultsToEvidenceStore
```

**Comment by navin22** [comment]
@kodmis : Sorry for the confusion. I quickly tested 4.7.2 or higher works. 4.7.2 is the first and fully net standard 2.0 compliant one. 

Sorry for the inconvenience, we shouldn't have updated the dependency in the minor version changes. Will update the documents as well.

**Comment by navin22** [comment]
@kodmis 
We have fixed the task to use the older libraries, and deployed the hotfix. Can you please confirm if the issue has been fixed by re running your pipeline?

**Comment by HasseEllsater** [comment]
@kodmis @navin22 Hi, we have had this problem since yesterday, we have now been able to run our builds again, the hotfix seems OK, thanks

**Comment by navin22** [comment]
Thanks for the confirmation, I will be closing this issue.
