### ISSUE TITLE
Use InvokeRestApi Task to Invoke Azure DevOps Services REST API

### ISSUE THREAD

**Issue by lmmarsano** [microsoft/azure-pipelines-tasks#12437]
## Required Information
**Question, Bug, or Feature?**  
*Type*: feature
**Enter Task Name**: Invoke REST API
list here (V# not needed):
- https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/InvokeRestApiV1

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: how?

## Issue Description

You already give us [System.AccessToken](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken).
We can invoke your service's REST methods using `curl` or PowerShell's `Invoke-RestMethod` from a script task/step.
Can we do the same with InvokeRestApi Task?
If not, then why not?

**Comment by Liero** [comment]
I think this issue has been incorrectly mentioned in the PR. The PR seems to be unrelated and this issue should be reopenned
