### ISSUE TITLE
DownloadPipelineArtifact@2 not able to exclude folder

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azure-pipelines-tasks#12439]
I followed the folder exclusion sample documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops#doubleexcl_examples

and here is my task YAML:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    targetPath: '$(Build.SourcesDirectory)\.build'
    artifactName: drop
    itemPattern: |
      **
      !darwin/**

**but from the task log we can tell the darwin folder is not getting excluded:**

![Screen Shot 2020-02-27 at 10 04 58 AM](https://user-images.githubusercontent.com/13777222/75472669-b2c51800-5948-11ea-8df9-262b41ea9450.png)

**i also experimented using \ as separator, but no luck.**
![Screen Shot 2020-02-27 at 10 06 22 AM](https://user-images.githubusercontent.com/13777222/75472767-dbe5a880-5948-11ea-802e-e713f96cfb21.png)

**Comment by alanrenmsft** [comment]
I experimented inclusion pattern after being blocked by the exclusion pattern. it seems i have specify the artifact name in the pattern. e.g. drop/win32-x64/**. 
drop is the artifact name. is this expected?

**Comment by fadnavistanmay** [comment]
Hi,

Yes, since the artifact is of type FCS - you have to specify the artifact name before the pattern.

Thanks.
