### ISSUE TITLE
NuGetCommand: Failed find: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Saibamen** [microsoft/azure-pipelines-tasks#12436]
## Required Information

I have 134k files in one directory and now I cannot run NugetCommand.
It was working before adding 64k new files.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetCommand

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

NuGetCommand
```
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
```

It was working before adding 64k new files into git repo.

### Task logs

[logs_5386.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4262699/logs_5386.zip)

### Error logs

```
##[debug]  d:\a\1\s\X\X.Logic.IntegrationTestsFull\.TestIntegrationData (directory)
##[debug]  d:\a\1\s\X\X.IntegrationTestsFull\.TestIntegrationData\Data_VB6_Output (directory)
##[error]Error: Failed find: Maximum call stack size exceeded
##[debug]Processed: ##vso[task.issue type=error;]Error: Failed find: Maximum call stack size exceeded
##[debug]task result: Failed
##[error]Packages failed to restore
##[debug]Processed: ##vso[task.issue type=error;]Packages failed to restore
##[debug]Processed: ##vso[task.complete result=Failed;]Packages failed to restore
Finishing: NuGetCommand
```

**Comment by Saibamen** [comment]
Ping? Any news or workarounds?

**Comment by Saibamen** [comment]
Root cause: Search pattern like `**/X/**/*.sln`

I changed this to `X/*.sln`, but it still searching in deeper directories like `X/A/B`, bug https://github.com/microsoft/azure-pipelines-task-lib/issues/623

Workaround for this was to archive files needed for tests, use `ExtractFiles` task and then in use explicit path for csproj file to build (without asterisk)

**Comment by herenhuang** [comment]
Hey there, the NugetCommand is quite ~bloated~ so we suggest you use the new [NugetAuthenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops), and script to isolate using either our task or nuget.exe. 
 
Let us know how it goes, going to close this for now.
