### ISSUE TITLE
Allow HelmDeploy task to use deployment environment as Service Connection

### ISSUE THREAD

**Issue by fazdamoa** [microsoft/azure-pipelines-tasks#12466]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: HelmDeploy

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

HelmDeploy doesn't support using the current deployment environment to connect to AKS.

In a deployment job, Kubectl can use the environment to connect to AKS and deploy resources. HelmDeploy task still requires connectionType, Subscription etc to be specified. Running without connection details specified gives me:

`Error: Input required: kubernetesCluster`

Can we get cluster connection information integrated into environment like the Kubectl task?

**Comment by kyschouv** [comment]
I'd love to see this integrated as well. It's blocking our adoption of this. Is there any workaround for this?

**Comment by fazdamoa** [comment]
Yeah when you create the environment, it actually creates service connections per namespace. So you can put the namespace service connection directly into this task. It works, but is more manual as it has a random number attached to the name. This issue was created because it isn't consistent with kubectl task.

**Comment by ds-ms** [comment]
@chshrikh could you take a look at this issue? This seems to be an issue with the replacement logic of the service endpoint substitution in the deployment job.

**Comment by chshrikh** [comment]
@ds-ms what is inuput type for HelmDeploy ? For Kubctl we have logic to replace the input of type serviceconnection
