### ISSUE TITLE
Failed to download or parse release-index.json with error: {"code":"ECONNRESET","path":null,"host":"raw.githubusercontent.com","port":443}

### ISSUE THREAD

**Issue by GSonofNun** [microsoft/azure-pipelines-tasks#12462]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

Task: **UseDotNet@2**

## Environment
- Server - **TFS on-premises**
    
    - Version: **Dev17.M153.2**
    
- Agent - **Private**
    
    - OS version: Windows 10: 1809, Build: 17763.1039
    - Agent version: unknown

## Issue Description

UseDotNet sometimes fails with the following Log:
```
##[section]Starting: UseDotNet
==============================================================================
Task         : Use dotnet
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.0.5
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 3.1.x.
##[error]Failed to download or parse release-index.json with error: {"code":"ECONNRESET","path":null,"host":"raw.githubusercontent.com","port":443}
##[section]Finishing: UseDotNet
```

The YAML for the task:
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
```

There was a similar issue with a similar error message that was closed last year: https://github.com/microsoft/azure-pipelines-tasks/issues/10969

**Comment by anuragc617** [comment]
@GSonofNun error code ECONNRESET means that the TCP connection is abruptly closed by the server. So it doesn't look like a task issue. Are you consistently hitting this issue? Can you please retry this?

**Comment by GSonofNun** [comment]
It wasn't happening consistently, and I'd have to look back through our build logs to see if it has happened since.

**Comment by GSonofNun** [comment]
I just checked my logs for the last couple days and it hasn't failed for that reason since, so I'll mark this as closed. Thanks for your help.

**Comment by GSonofNun** [comment]
Sorry, I actually just had this happen again.

**Comment by GSonofNun** [comment]
And if you're saying this is just a connection issue with my server, I can accept that and re-close this. :)

**Comment by anuragc617** [comment]
Hi @GSonofNun, is your agent running behind a proxy? For me its look like a proxy issue and you would have to bypass the  raw.githubusercontent.com to let the task download releases-index.json.
You can follow [this ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&viewFallbackFrom=vsts&tabs=windows )to set up agent behind proxy.

Also, can you share logs with system.debug variable set to true for more information?

**Comment by anuragc617** [comment]
@GSonofNun have you made any progress here??

**Comment by GSonofNun** [comment]
I apologize. I haven't been allocated time to investigate this. Should I just close this if it is an issue on our end?

**Comment by anuragc617** [comment]
@GSonofNun you can close it if the above solution works for you.

**Comment by anuragc617** [comment]
Closing this issue for now, feel free to comment/open.

**Comment by ViktorHofer** [comment]
Can we please re-open the issue? We just hit this in dotnet/runtime: https://github.com/dotnet/runtime/issues/44595. Ideally there would be a way to retry the task if the connection abruptly fails?
