### ISSUE TITLE
How to compile and build vsix file locally 

### ISSUE THREAD

**Issue by Farzad-Jalali** [microsoft/azure-pipelines-tasks#12469]
## Required Information
I have some ideas for a new task, but I need to compile your tasks locally and build something on top of them. (it's easier this way)

I tried the other sample but look like that one is using a handler which is deprecated
basically I like to know how to compile and build the tasks locally (generating *.VSIX file)

I'm trying the below command but it doesn't work:
`tfx extension create --manifest-globs vss-extension.json
`

*Type*: Question

**Enter Task Name**:  all of them (but I have to pick one , I would go for PowershellV2)

## Environment
My local machine
I have installed all of requierment from here:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops

### Task logs
I haven't get there?

**Comment by damccorm** [comment]
Hey, sorry for the slow response - you should be able to build the tasks by following the instructions [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md#build-and-test), that will put them in the `_build` directory. Note that this might not be exactly what you're looking for though, there are some differences in how we publish in the box (firstparty) tasks and marketplace tasks
