### ISSUE TITLE
WebDeploy IIS - MSDeploy to a different path

### ISSUE THREAD

**Issue by ZetaPR** [microsoft/azure-pipelines-tasks#12476]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  Question

**Enter Task Name**: IISWebAppDeploymentOnMachineGroupV0

## Environment
- Server - Azure Pipelines or TFS on-premises?
   
       IIS Version 10.0.17763.1

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  Azure Pipelines Task: IIS web app deploy Task vers. 0.*
 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
     Microsoft Windows Server 2019
     Agent Version 2.165.0
## Issue Description

I am trying to deploy a PHP Symfony backend application. 
The scaffolding of the project is very limited and I have the 'public' folder inside the deployment folder.
How can I change where the deploy is being produced physically?

Using IIS Web app deploy you may add Additional Paremeters but if I try to set -dest for changing the path it states thar is already there.
If I leave the task do its thing, it is just deploying everything inside the Physical Path provided in the Site settings, where I have set '../SiteName/public' so everything is being deployed inside this public folder, having the real public folder inside and making the application to fail working

Task YAML
steps:
- task: IISWebAppDeploymentOnMachineGroup@0
  displayName: Deploy
  inputs:
    WebSiteName: 'SiteName'
    Package: '$(System.DefaultWorkingDirectory)/Website/Website'
    RemoveAdditionalFilesFlag: true
    AdditionalArguments: '-dest:path="C:\inetpub\wwwroot\SiteName"'

### Task logs

2020-03-04T13:40:14.6465470Z ##[error]Failed to deploy web package to IIS website.
2020-03-04T13:40:14.6477945Z ##[error]Error: Argument '-dest' may only be specified once.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by SumiranAgg** [comment]
@ZetaPR What do you mean by setting physical path in site settings. Do you mean path mappigs in azure portal.

By default the task deploys to app service root. For virtual application we provide an explicit task input which you may provide. You have to preset it in you app settings->path mappings before you can use it.

**Comment by SumiranAgg** [comment]
Closing the issue. Please feel free to re-open if you are still seeing the issue.
