### ISSUE TITLE
AzureFunctionApp@1 Reports Success, But Function is Not Showing Up in Azure Portal

### ISSUE THREAD

**Issue by KSiig** [microsoft/azure-pipelines-tasks#12474]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionApp@1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - **If using Azure Pipelines, provide the account name, team project name, build definition name/build number:** cybot, Infrastructure, #20200304.1

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-latest

## Issue Description

Snippet from pipeline:

```
- task: AzureFunctionApp@1
  displayName: 'Deploy to Azure Functions'
  inputs:
    azureSubscription: '$(azureSubscription-prod)'
    appType: functionApp
    appName: $(functionAppName-prod)
    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

```
I'm using the above config to publish my function to Azure. Everything seems to work, it's even showing a successful deployment in the app settings for the function app. However, when I try to look at the function, it's not showing up.

I've tried publishing the function through Visual Studio, which works just as expected, so it's not the function app that's the problem.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]
[logs_10384.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4287090/logs_10384.zip)

From deployment log:
```json
[
  {
    "log_time": "2020-03-04T10:53:07.1518526Z",
    "id": "6a0f2e5b-28a5-4c8d-8a23-582a6b989aa7",
    "message": "Updating submodules.",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-03-04T10:53:07.3862384Z",
    "id": "dfddd6b3-a9d5-41ed-9511-205148569e63",
    "message": "Preparing deployment for commit id 'b8f3450f19'.",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-03-04T10:53:08.0897722Z",
    "id": "721c4642-ba21-4e93-bca8-fc6c778afb68",
    "message": "Skipping build. Project type: Run-From-Zip",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-03-04T10:53:08.292898Z",
    "id": "a82c6f88-9ca2-4f63-ad78-0e3fe6b41e0c",
    "message": "Skipping post build. Project type: Run-From-Zip",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-03-04T10:53:08.4804212Z",
    "id": "54e73939-9d1c-428c-a89b-b5e02ad086d1",
    "message": "Triggering recycle (preview mode disabled).",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-03-04T10:53:11.2744705Z",
    "id": "28845174-8e41-44ed-9980-1e8e868283a8",
    "message": "Syncing 0 function triggers with payload size 2 bytes successful.",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-03-04T10:53:11.5088803Z",
    "id": "04f7e7d5-43d7-4de6-aafc-e33904a66b01",
    "message": "Deployment successful.",
    "type": 0,
    "details_url": null
  }
]
```

**Comment by SumiranAgg** [comment]
@KSiig Are the new functions not visible in azure portal?
Access scm site for your app service. You package gets deployed under home/site/wwwroot. Can you compare the content after deployment via visual studio and post deployment via task. Please share your observations.

**Comment by KSiig** [comment]
Yes the functions are not visible in Azure Portal.

I went into the SCM site, and I think I found the problem. When deploying the from Visual Studio, it's the contents from [projectFolder]/bin/Debug/netcoreapp3.1, and puts it into wwwroot, which is how I think it's supposed to be, and the functions are working.

When deploying via Azure Pipelines, it puts the entire git repository into wwwroot. So technically it has uploaded the files, it's just uploading too many.

**Comment by KSiig** [comment]
Sorry about that, turns out it was my fault in the end. I'm still quite new to Pipelines, and forgot that it isn't this task that packages the zip. I changed the `rootFolderOrFile` variable in my ArchiveFiles action, to point at the `$(System.DefaultWorkingDirectory)/bin/Debug/netcoreapp3.1` directory instead of just `$(System.DefaultWorkingDirectory)`, and that solved the issue.

**Comment by Arun7even** [comment]
I am facing the same issue in puthon function app. Any help would be much appreciated

**Comment by kmkumaran** [comment]
@nadesu , @chshrikh for follow up

**Comment by amit-avit** [comment]
@Arun7even is this issue still valid for you?

**Comment by cyberpion-yotam** [comment]
Getting this issue when deploying from bitbucket.

**Comment by technokarthyk** [comment]
hi i'm facing an issue in my github actions workflow, both build and deploy got success without an error but while i check on azure portal my function app(which is created by github) is not displaying i dont know how to resolve this can anyone help me
