### ISSUE TITLE
Java is downloaded to inner folder but expected in the root

### ISSUE THREAD

**Issue by SDLionas** [microsoft/azure-pipelines-tasks#12478]
## Required Information
*Type*: Bug
**Enter Task Name**: JavaToolInstallerV0  
## Environment
Azure Pipelines
## Issue Description
I set my Java tool installer like this:
![Capture](https://user-images.githubusercontent.com/47793467/75898565-3d55bd80-5e08-11ea-90c5-ba9247db49b4.JPG).

Take a look that path inside the container has folders: "JDK/13.0.2/jdk-13.0.2.zip"

When I run the task, it ends up with result

> Downloaded 'JDK/13.0.2/jdk-13.0.2.zip' to 'd:\work\2\s\java\JDK\13.0.2\jdk-13.0.2.zip'
Total Files: 5290, Processed: 1, Skipped: 5289, Failed: 0, Download time: 8.03secs
##[error]ENOENT: no such file or directory, stat 'd:\work\2\s\java\jdk-13.0.2.zip'
##[error]ENOENT: no such file or directory, stat 'd:\work\2\s\java\jdk-13.0.2.zip'

Take a look that it downloaded to a sub folder **JDK\13.0.2**, but then tries to look for the zip file in the root.

**Comment by anton-erofeev** [comment]
Closed as duplicate https://github.com/microsoft/azure-pipelines-tasks/issues/10683
