### ISSUE TITLE
API rate limit exceeded in github

### ISSUE THREAD

**Issue by iMacX** [microsoft/azure-pipelines-tasks#12487]
## Required Information

**Question, Bug, or Feature?**  Question

**Enter Task Name**: HelmInstaller@1  

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/HelmInstallerV1

- Private Agent on os X Mojave, agent version: '2.165.0'
    
## Issue Description

The task can't donwload last version of helm because of the rate limit api of 60 request per hour for github, which we raised.

https://developer.github.com/v3/#rate-limiting

Error message is the following

> HTTP/1.1 403 Forbidden
> Date: Tue, 20 Aug 2013 14:50:41 GMT
> Status: 403 Forbidden
> X-RateLimit-Limit: 60
> X-RateLimit-Remaining: 0
> X-RateLimit-Reset: 1377013266
> {
>    "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
>    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
> }

### Task logs

==============================
Task         : Helm tool installer
Description  : Install Helm on an agent machine
Version      : 1.165.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/helm-installer
=====================================
Downloading: https://api.github.com/repos/helm/helm/releases/latest
**##[warning]Can\'t find loc string for key: HelmLatestNotKnown
##[warning]HelmLatestNotKnown https://api.github.com/repos/helm/helm/releases/latest Error: Unexpected HTTP response: 403**
    at Object.<anonymous> (/vsts-agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.165.1/node_modules/vsts-task-tool-lib/tool.js:197:36)
    at next (native)
    at fulfilled (/vsts-agent/_work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.165.1/node_modules/vsts-task-tool-lib/tool.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7) v2.14.1
Downloading: https://get.helm.sh/helm-v2.14.1-darwin-amd64.zip
Extracting archive
/usr/bin/unzip /vsts-agent/_work/_temp/helm-v2.14.1-d7dee782-a238-4cc4-b9a8-fa0713f12516.zip
Archive:  /vsts-agent/_work/_temp/helm-v2.14.1-d7dee782-a238-4cc4-b9a8-fa0713f12516.zip
   creating: darwin-amd64/
  inflating: darwin-amd64/LICENSE    
  inflating: darwin-amd64/helm       
  inflating: darwin-amd64/README.md  
  inflating: darwin-amd64/tiller     
Caching tool: helm 2.14.1 x64
Prepending PATH environment variable with directory: /vsts-agent/_work/_tool/helm/2.14.1/x64/darwin-amd64
Verifying helm installation...
/vsts-agent/_work/_tool/helm/2.14.1/x64/darwin-amd64/helm init --client-only
$HELM_HOME has been configured at /Users/vsts/.helm.
Not installing Tiller due to 'client-only' flag having been set
Finishing: HelmInstaller

In order to increase the rate limit form 60 to 5000 request per hour, we can pass our app's client ID and secret before the endpoint route, or pass the token aswell.

> curl -u my_client_id:my_client_secret https://api.github.com/user/repos
> HTTP/1.1 200 OK
> Date: Mon, 01 Jul 2013 17:27:06 GMT
> Status: 200 OK
> X-RateLimit-Limit: **5000**
> X-RateLimit-Remaining: **4966**
> X-RateLimit-Reset: 1372700873

So my first question is: how to pass those parameters to the HelmInstaller@1 task ? Or what is the procedure to workaround this issue?
Second question: The problem is that the version pf helm that is downloaded is helm 2 instead of helm3. How to force the download of helm 3 instead of 2 when limit is reached?

Thank for your help as our workflow, when running fully, raised that limit every time.

**Comment by ds-ms** [comment]
> So my first question is: how to pass those parameters to the HelmInstaller@1 task ? Or what is the procedure to workaround this issue?

Answer:
The task makes an anonymous REST call to fetch the latest version, this can be avoided if you already know the version you want to install. So, if you provide set the version value to something like `v3.1.2` or something; the REST call to `api.github.com` would be skipped and would download the specific version you desire. 

There isn't any provision for you to supply creds to the anonymous GitHub API calls which are being made, yet. 
One more workaround could be where you avoid the usage of `HelmInstaller` task and have some scripts running locally on your agent's VM to keep updating the helm installation of the box to latest, periodically. If you ensure that it's added to the environment paths; the tasks will pick it up from there. 

> Second question: The problem is that the version pf helm that is downloaded is helm 2 instead of helm3. How to force the download of helm 3 instead of 2 when limit is reached?

Answer:
> > if you provide set the version value to something like `v3.1.2` or something; the REST call to `api.github.com` would be skipped and would download the specific version you desire. 

If you resolve to `latest` which is the default value; the task would always make a call to `api.github.com` to fetch the version.

PS: You wouldn't notice this issue in a Hosted Agent Pool because you're assigned a new VM for each run.
