### ISSUE TITLE
Testcomplete With Azure DevOps- Rerun does not show logs.

### ISSUE THREAD

**Issue by HomelessPenguin** [microsoft/azure-pipelines-tasks#12496]
Hi.
I am getting this error message when I check the re-run on failure checkbox.

Error occurred while publishing test results : System.Exception: No tests were discovered while attempting to rerun failed tests. This is likely to happen if these tests are xunit or nunit datadriven/parameterized tests or tests with custom display names with spaces or special characters which are not supported with rerun. Please reach out to us at https://github.com/microsoft/azure-pipelines-tasks/issues if you are hitting this for tests other than the ones mentioned before.

**Comment by ShreyasRmsft** [comment]
Please provide full zip logs with system.debug = true. Also what kind of tests are you running? Are they xunit/nunit/specflow tests?

**Comment by HomelessPenguin** [comment]
Hi Shreyas,
I am running testcomplete tests. They execute once and I get the logs for that run, when it tries to re-run the failed items and publish those logs thats where I get the error I've posted in the initial post.
Please check and let me know if the logs attached are sufficient.
[ReleaseLogs_717.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4311059/ReleaseLogs_717.zip)

**Comment by hvinett** [comment]
Hey @HomelessPenguin ,
cna you provide logs by setting system.debug = true ?

**Comment by ShreyasRmsft** [comment]
@HomelessPenguin we do not support re-run for tests that contain special characters in their fully qualified name. The reason for this is that vstest.console has a limitation when it comes to parsing these names when we pass them as a filter for re-run.

2020-03-09T15:09:06.7189364Z No test matches the given testcase filter `FullyQualifiedName=FASTRegressionSuite.testitem:fieldviewv2\\confirmations_reports` in C:\agent02\r1\a\_Field View automation Package\FieldViewAutomation\FASTRegressionSuite.pjs
