### ISSUE TITLE
'NuGet Authenticate' not working with 'dotnet tool install'

### ISSUE THREAD

**Issue by yhvicey** [microsoft/azure-pipelines-tasks#12494]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGet Authenticate, .NET Core

## Environment

- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines, account `msasg`, project `Shared Data`, release definition id: 279 (Already reverted, you can check release id 39209)

- Agent - Hosted or Private: 

Hosted agent, agent queue 'Azure Pipelines, vs2017-win2016'
   
## Issue Description

`dotnet tool install <pkg name> --add-source <internal source>` will fail due to Auth error (401) when trying to install an tool package from NuGet feeds within same Azure DevOps account/project, even after `NuGet Authenticate` task is added & executed before this step.

**Comment by anuragc617** [comment]
@yhvicey yes this is expected. To fix this issue add an explicit dotnet restore task and specify arguments: '--no-restore' for the dotnet tool install. For explaination you can refer this [doc  ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#why-is-my-build-publish-or-test-step-failing-to-restore-packages).

**Comment by yhvicey** [comment]
Do I need to add the internal feed globally, before running `dotnet restore`?

**Comment by anuragc617** [comment]
@yhvicey you need to add the feed reference in nuget.config file. You can take the reference of this [doc](https://docs.microsoft.com/en-gb/azure/devops/artifacts/nuget/publish?view=azure-devops) for any other information related to this

**Comment by yhvicey** [comment]
Looks like `dotnet restore` requires a project file, which does not suit our case (run some internal tool package without any project file). I'll stick to authenticate nuget feed using PAT but still really appreciate your information, thanks!
