### ISSUE TITLE
IIS Web Application Management

### ISSUE THREAD

**Issue by fthkucuk** [microsoft/azure-pipelines-tasks#12490]
Hi,

I got an error iis web manage task cause apppool already stopped so I tried to additional appcmd.exe commands for use exit 0 or set errorlevel=0 but it didn't work. I tried something else like capture2 but I didn't see this command in log (You can see Capture 3). It seems to don't work additional arguments for web application management tasks. I'm using Azure DevOps Server 2019 Update 1

![Capture3](https://user-images.githubusercontent.com/46280608/76023018-632eaf80-5f39-11ea-9d93-12025ed14e25.PNG)
![Capture2](https://user-images.githubusercontent.com/46280608/76023019-645fdc80-5f39-11ea-8fb1-366d9fc0f95d.PNG)
![Capture](https://user-images.githubusercontent.com/46280608/76022810-ebf91b80-5f38-11ea-893d-32a5759c6e81.PNG)

**Comment by SumiranAgg** [comment]
@fthkucuk The issue is happening because appcmd.exe throws an error if the app pool you are trying to stop is already stopped. Ideally we should check the status of the app pool before executing the command. This is an enhancement. For now you can mark this task to continue on error to avoid failing the pipeline.

**Comment by ssinfod** [comment]
I think this enhancement should be implemented. 
The task should offer an option to check if the pool is already stopped.

**Comment by rschindhelm-haba** [comment]
I agree that the task should not return an error if the application pool is already in the stopped state.
The "continue on error" option would proceed even if there actually is an actual error, e.g. wrong application pool name, and could be more harmful then helpful.

**Comment by ldsenow** [comment]
Can we reopen this issue? 

We see warning sometimes after deployment. I am worried about the "continue on error" option one day will cause false positive.

**Comment by brs713** [comment]
Sooooo... the desired behavior is stopping the app pool.  If the result is that the app pool is stopped, so no change takes place, that's not an error.  If the outcome is the same as the desired behavior, then returning an error code is a bug.  Fix your bug.

 If you make a DELETE API call and the resource doesn't exist, there's debate over returning a 404 or a 200, but no sane person would return a 500.
 
 Return an exit 0 or a warning, but in no way is returning a stopped app pool for a request to stop an app pool an error.
 
 This is not an enhancement; this is a bugfix.

**Comment by farinha** [comment]
> As a simple workaround for the original issue, you can start the apppool before stopping it.
> 
> Starting an apppool which is already running does not generate an error.

This supports the point @brs713 is making. When the desired outcome has already been achieved and no change needs to take place... that's not an error. If anything it could be a warning, but definitely not an error.

Found [this issue](https://github.com/microsoft/azure-pipelines-extensions/issues/573) that deals with the same behavior but for the "App Command on Target Machine" task. It seems to have been [dealt with](https://github.com/microsoft/azure-pipelines-extensions/pull/615) a long time ago.
A brief look at the [latest version](https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppMgmt/IISWebAppMgmtV3/AppCmdOnTargetMachines.ps1) of the task shows that it's still following that same logic:
```powershell
if ((($appPoolState -like "Started") -and $action -like "start") -or (($appPoolState -like "Stopped") -and $action -like "stop")) {
    Write-verbose "Application pool '$appPoolName' is already in state of the action '$action'. Hence skipping the operation."
    return
}
```
Should something similar be done in this "IIS Web Application Management" task?

**Comment by dominikcip** [comment]
this one should be re-opened. This is definitely issue which needs to be solved

**Comment by jrayga** [comment]
This ticket should be reopened. Silently continuing on error is risky—especially if the error code is something like 500.30,

That kind of failure should be surfaced immediately.
