### ISSUE TITLE
Publish Code Coverage Results. Error: Incorrect Format

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/azure-pipelines-tasks#12492]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Publish Code Coverage Results
## Environment
- Server - Azure Pipelines or TFS on-premises? Azure pipelines. Please email me for exact details (see below). 
- Agent - Hosted or Private: Hosted

## Issue Description
Task is not able to publish code coverage. "Error during reading report 'E:\A\_work\27\s\server\combinedcoverageoutput\cobertura-coverage.xml' (Size: 1.4MB): Input string was not in a correct format."

I'm unsure about why it's showing this error--the format looks correct to me. I need help determining exactly what part of the file has incorrect format

### Task logs
Unable to post logs in public repo due to sensitive information. Please email me (see below). 

### Error logs
Unable to post logs in public repo due to sensitive information. Please email me (see below). 

Please email me at ragulat@microsoft for more details.

**Comment by hvinett** [comment]
@RaymonGulati1 ,
Can you check your cobertura-coverage.xml is working correctly with report generator tool that is actually executing the task. Most likely the issues seems to be with report generator tool if i am not mistaken.
you can find report generator dll by running agent on your machine and configure the pipeline with the default agent. after the run you can see the report generator dll in publishcodecoverage  task

**Comment by ShreyasRmsft** [comment]
Closing due to no response please re-open with the requested data.
