### ISSUE TITLE
Make accesible scopes for pipeline cache configurable

### ISSUE THREAD

**Issue by rsheptolut** [microsoft/azure-pipelines-tasks#12503]
## Required Information

**Question, Bug, or Feature?**  
*Type*: `Feature`

**Enter Task Name**: `CacheV2`

## Environment
- Server - `Azure Pipelines`:
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: `gmp-vc`, `Turbo`, `Build Turbo`

- Agent - `Hosted`: 
    
    - If using Hosted agent, provide agent queue name: `Azure Pipelines\windows-2019`

## Issue Description

Could you please add one more input to the task that allows you to specify which branches it's ok to access cache entires from? Or maybe there's a better way to control this? For example, allow naming your scope key yourself (for me would be one key for all branches). Something like this has been previously suggested [here](https://github.com/microsoft/azure-pipelines-tasks/issues/11374) and was implemented as `master`-only feature.

That feature landed recently and is also neat. Now builds on the `develop` branch should get read-only access to `master`-scoped caches. This allows the `develop` branch to reuse cached packages or entire built sub-apps. I also like the default behavior that makes other scopes inaccessible by default.

But, I find myself frequently needing to use this feature the other way around. It would be neat if in the `CacheV2` task we could configure which branches to allow this current task to peer into. Our relatively normal use case: we have the `Dev`, `QA` and `Prod` environments in Azure. We also have 3 main branches in git that track those precisely: `develop`, `staging` and `master`. This allows us to always know what's live, easily reproduce errors locally, etc. As soon as you push new code to `develop`, a build happens and hopefully reuses some cache entries for packages and maybe sub-apps that haven't changed at all, and then deploys the built app to the `Dev` env. To promote this to `QA` or `Prod` we simply fast-forward or merge `develop` into `staging` or `master`. But there, `staging` and `master` don't have a way to access cache entries of `develop` (although it's exactly the same source code, same commit even!). And if they don't have their own entires from previous builds - any tasks that's "new" to those branches would have to be processed for real, instead of using the cache entires already available from `develop`. This makes them run for that much longer, so sometimes we opt for manually doing the deployment through `Releases` from that single build, and then the branches don't actually show what's live. Or I'd push all branches, and then cancel 2 out of 3 builds, having also to remember to deploy to other 2 envs manually in the future. Advice on our workflow accepted, but it's mainly here to illustrate the need for added configurability.

### Task logs
`N/A`

## Troubleshooting
`N/A`

### Error logs

`N/A`

**Comment by JasonElkin** [comment]
+1 including the ability to choose to use the same cache across multiple pipelines.

At the moment I have a number of pipelines that only run on master (either because I'm not using any other pipelines or because I need to use different pipelines on other branches). In this instance it makes sense that master should be able to write to its own pipeline cache and/or be able to read the cache from another pipeline where the cache would be useful.

**Comment by blueelvis** [comment]
+1

I just realized this is the case and our PR CI pipeline is taking way long even though the cache key is not changed across runs. This is really required. I am not sure why this was the case. Kind of blows away the entire concept of caching (And in many cases, direct downloads from the source is way faster than downloading from the cache!)

**Comment by planetmarshall** [comment]
+1 The default operation doesn't support the Gitflow model where short lived feature branches are forked and merged back into a develop branch, rather than master which is purely for releases.

**Comment by rsheptolut** [comment]
Any movement on this? This is still relevant and would help speed up our pipelines. I'm fine with the current behavior as default, but it'd be good to have this configurable.

**Comment by pb6** [comment]
I would like to cache things like gradle OWASP dependency check plugin/db, which is used as templated tasks in multiple pipelines for different apps. I would expect all pipelines to share the same cache. Inability to control this is quite shortsighted.

Currently we get different scopes in different pipelines, and thus no caching.
553;o229ccae-8570-41ze-886b-fa2da5c359dd;refs/heads/develop;df19414a-dd48-4de6-a36f-a80747f060a1
540;o229ccae-8570-41ze-886b-fa2da5c359dd;refs/heads/develop;a196c3b8-64bb-4e3f-91df-a441df675aef

**Comment by omexus** [comment]
we use short-lived branches a lot so this would be really useful

**Comment by rsheptolut** [comment]
@johnterickson Hope you're doing well, sorry to be a bother but is there maybe a way to enable this by now? Any chance of enabling this in the future? We have many branches, and them all using the same scope (even if scoped to just one pipeline) would speed stuff up immensely for us I think. Making this completely configurable with a warning of what this can impact would be ideal - pretty sure it's just a string key somewhere.

**Comment by hjimenez-ni** [comment]
Hi @johnterickson! I think this is definitely something that would make things much more efficient in our use case too. Currently, we are using the same template to implement 2 different pipelines. It would be great if we could share the scope of one pipeline with the other one. Is there any feature definition and/or timeline defined for this request?

**Comment by rsheptolut** [comment]
@johnterickson Hi! Any updates on this topic for the community at all? Can you assist with routing this issue to someone else perhaps?
