### ISSUE TITLE
IIS web app deploy fails for .net core 2.2 with ERROR_FILE_IN_USE

### ISSUE THREAD

**Issue by lsprado** [microsoft/azure-pipelines-tasks#12501]
Hi,
I'm using IIS web app deploy task in a step of continuous integration on Azure DevOps Services.
I configure a deployment group with 5 internal servers (on-premisse)

Sometimes the release execution result this error:

> Failed to deploy web package to IIS website.
> Error Code: ERROR_FILE_IN_USE
> More Information: The file 'AutoMapper.dll' is in use.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
> Error count: 1.
> Error: The process 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' failed with exit code 4294967295
> 

I already configure the option "Take App Offline" but not worked

Can you help me about this issue?
There is a way to force stopping and restarting the app?

Thank you
Leandro Prado

**Comment by lsprado** [comment]
Hi Folks,
Any update about this issue? 

Thank you
Leandro Prado

**Comment by SumiranAgg** [comment]
@lsprado Can you share debug logs of the failed task. Set "System.debug" variable as true in your pipelines and redeploy. Share generated logs.

**Comment by 20shivangi** [comment]
Closing this issue. Please feel free to reopen if facing it by attaching debug logs.
