### ISSUE TITLE
AzureCLIV2 does not have Az PowerShell cmdlets

### ISSUE THREAD

**Issue by crgarcia12** [microsoft/azure-pipelines-tasks#12507]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureCLIV2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
**https://dev.azure.com/crgarcia/crgar-aks-securecluster/_build/results?buildId=69&view=results**

    - If using Hosted agent, provide agent queue name:
**pool:  vmImage: 'ubuntu-latest'**

## Issue Description

[Include task name(s), screenshots and any other relevant details]
When running a PS script in PSCore using the PowerShell Az module, it does not work:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'crgar Internal Subscription(930c11b0-5e6d-458f-b9e3-f3dda0734110)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Import-Module ./DeployLandingZone/deployment.psm1 -Verbose -Force 
      # Here it calls Select-AzSubscription
      New-SecureAksLandingZone -Verbose
    useGlobalConfig: true

Error:
The term 'Select-AzSubscription' is not recognized as the name of a cmdlet, function, script file, or operable program.

https://dev.azure.com/crgarcia/crgar-aks-securecluster/_build/results?buildId=62&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=c5958238-e176-5f5e-fbd6-97d2d6242272&l=61

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by dastewa** [comment]
Is there a way to get AzureCLI@2 to use Az modules?

**Comment by bishal-pdMSFT** [comment]
I don't think this is the intention of Azure CLI task. If you want to use Az powershell modules, please use Azure PowerShell task.
