### ISSUE TITLE
Azure Devops Server ".Net Core SDK Installer" task fails

### ISSUE THREAD

**Issue by stavroskasidis** [microsoft/azure-pipelines-tasks#12509]
Redirected issue from https://github.com/dotnet/core/issues/4376

Hello, I am trying to use the core sdk installer task on Azure Devops Server to install the latest sdk on the agent, however the following error occurs. It seems to me that it is looking for a json file in this repo that does not exist or is invalid.

![image](https://user-images.githubusercontent.com/12549761/76294179-0b86a000-62bb-11ea-857f-ae2aff97b229.png)

![image](https://user-images.githubusercontent.com/12549761/76294097-e4c86980-62ba-11ea-9ae5-227d2268e3ec.png)

**Comment by anuragc617** [comment]
Hi @stavroskasidis, you are using older version of .NetCoreSdkInstaller. You should start using UseDotNetV2 to fix this issue.

**Comment by stavroskasidis** [comment]
We are using Azure Devops Server 
![image](https://user-images.githubusercontent.com/12549761/76599897-90b5c300-650e-11ea-9fac-d78ebe1df77f.png)

Are you saying that upgrading the Devops Server and choosing version 2 of the task will solve this issue ?

**Comment by anuragc617** [comment]
@stavroskasidis  yes you should update to the latest AzureDevOps Server and use UseDotNetV2 task.

**Comment by stavroskasidis** [comment]
Thank you. We will do that and I will reopen this issue if necessary

**Comment by myyalcintas** [comment]
> Thank you. We will do that and I will reopen this issue if necessary

Did you solve the issue with following updates?

**Comment by stavroskasidis** [comment]
Yes the issue is resolved. Thank you
