### ISSUE TITLE
Universal Packages broken: artifact tool cannot be downloaded

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-pipelines-tasks#12515]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Universal Packages

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted or Private: Hosted, macOS

## Issue Description

```
==============================================================================
Task         : Universal packages
Description  : Download or publish Universal Packages
Version      : 0.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
SYSTEMVSSCONNECTION exists true
Downloading: https://08wvsblobprodsu6weus73.vsblob.vsassets.io/artifacttool/artifacttool-osx-x64-Release_0.2.128.zip?sv=2017-04-17&sr=b&sig=aPe6Q3vkn0lJ3sD9hz8aWu32qTA8Q5uKLCesIcnFn48%3D&spr=https&se=2020-03-11T03%3A38%3A48Z&sp=r&P1=1583897628&P2=11&P3=2&P4=NQ6azifpIbfI9lhTj2DErFqHfH2fQRx7i6lOkFIjN70%3d
##[error]Failed to get artifact tool. undefined
```

The server seems to be down, at least when trying manually in the browser.

**Comment by jmyersmsft** [comment]
@letmaik Is this still occurring for you? I don't see any other reports of this failure.

**Comment by letmaik** [comment]
No, but can this be made more robust?

**Comment by mmuffins** [comment]
The issue occurs for us occasionally, the last time being about two hours ago on a hosted windows-2019 agent, with agent version 2.168.2, image version 20200430.2 and task version  0.168.0.
It's not the biggest problem since just rerunning the stage fixes the issue, but it's annoying as it fails a build, kicking off notifications, prompting manual intervention.

**Comment by mongrelion** [comment]
We are experiencing the same issue with an even more recent version of the task:

```
2020-05-15T07:06:50.7347228Z ==============================================================================
2020-05-15T07:06:50.7347582Z Task         : Universal packages
2020-05-15T07:06:50.7347902Z Description  : Download or publish Universal Packages
2020-05-15T07:06:50.7348178Z Version      : 0.168.0
2020-05-15T07:06:50.7348447Z Author       : Microsoft Corporation
2020-05-15T07:06:50.7348776Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2020-05-15T07:06:50.7349167Z ==============================================================================
2020-05-15T07:06:51.0165537Z SYSTEMVSSCONNECTION exists true
2020-05-15T07:06:51.2058697Z Downloading: https://08wvsblobprodsu6weus73.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.128.zip?sv=2019-02-02&sr=b&sig=d6fJ5i80C6hWFltUQhmNFCPudWPhVU63fnWIvp3C6RU%3D&spr=https&se=2020-05-15T08%3A06%3A51Z&sp=r&P1=1589529711&P2=11&P3=2&P4=FXy4hFbWy%2bgJqDh%2bGLml3dvG3PG7jooUcLdQOI%2bnV5U%3d
2020-05-15T07:06:51.8719435Z ##[error]Failed to get artifact tool. undefined
```

We're running this job in one of Microsoft's public pools using the `ubunt-latest` image.
```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az709'
Current agent version: '2.168.2'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200430.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200430.1/images/linux/Ubuntu1804-README.md
Current image version: '20200430.1'
Agent running as: 'vsts'
```

Restarting the job fixes the problem but this is a flickering scenario that takes the stability away from our pipeline.

Any ideas on how to work around this issue other than having to manually rerun the pipeline whenever we get this error?

**Comment by johnterickson** [comment]
@jmyersmsft Does the task have retries on this?

**Comment by satbai** [comment]
We should add more logging so it's easier to determine which call exactly fails in this try catch block: https://github.com/microsoft/azure-pipelines-tasks/blob/35d4ec2cd6c5143041830c9f5f786c3dbd4e8962/Tasks/UniversalPackagesV0/universalmain.ts#L35

It's either pkgLocationUtils.getBlobstoreUriFromBaseServiceUri or artifactToolUtilities.getArtifactToolFromService. 

Anyway, we should add retries here.

**Comment by satbai** [comment]
If any of you seeing this could turn the system.debug pipeline variable to true and send the logs next time you see this error, that would be helpful. Thanks!

**Comment by satbai** [comment]
Looking a little more carefully here, the "Downloading" log is coming from here, which already has retries:
https://github.com/microsoft/azure-pipelines-tasks/blob/35d4ec2cd6c5143041830c9f5f786c3dbd4e8962/Tasks/Common/packaging-common/universal/ArtifactToolUtilities.ts#L85
And since we can see "Downloading" in the log only once, I think we can assume that it was actually successful. No retries were made. Which then means that the error happened in the lines after. If my assumption is correct, the error would be thrown in extractZip() or toollib.cacheDir(), but debug logs would probably show us more. I'm currently trying to get a repro with debug logs but if anyone has them handy, please share.

**Comment by herenhuang** [comment]
We've made some changes to add retries and logging, to be released in the next few sprints. Please keep an eye out for those. If in a few weeks you all are still experience issues, please provide debug logs when you reopen it so we can do some more debugging.
