### ISSUE TITLE
Xcode 11 not supported but required by ITMS-90725: SDK Version Issue 

### ISSUE THREAD

**Issue by dzak83** [microsoft/azure-pipelines-tasks#12523]
Hi,
It looks like Apple will require XCode 11 to build the packages we submit to the store starting April:

> ITMS-90725: SDK Version Issue - This app was built with the iOS 12.1 SDK. Starting April 2020, all iOS apps submitted to the App Store must be built with the iOS 13 SDK or later, included in Xcode 11 or later. 

XCode task 5.* (latest) however only supports XCode 10. Is there someone working on it right now? Is there a work around?

XCode task: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops

**Comment by azakariaMSFT** [comment]
This affects a number of projects on my team as well, Please treat it with priority
