### ISSUE TITLE
Appcenter release task: Use Cipheriv for counter mode of aes-256-ctr  and build fails to complete with not found error - Task Version: 3.159.0  

### ISSUE THREAD

**Issue by vravindranath** [microsoft/azure-pipelines-tasks#12521]
When we try to release the app to appcenter via release task - The task fails to complete with 'not found error'. Please help me understand the issue here till now we had release working and we had previously done successful releases. 

**Enter Task Name**: Appcenter distribute task -Android Store.  

- Agent - Hosted: vs2019
    
## Issue Description
Appcenter distribute tasks fails as per the attached log.

### Task logs

Task         : App Center distribute
Description  : Distribute app builds to testers and users via Visual Studio App Center
Version      : 3.159.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute

(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1236) Warning: Use Cipheriv for counter mode of aes-256-ctr
##[error]"{\"message\":\"Not found. Context ID: 5485d4fb-7ac0-42dd-8eea-089590675539\",\"statusCode\":404,\"code\":\"Not Found\"}"
http response code: 404
##[section]Finishing: Android - Store

**Comment by vravindranath** [comment]
Also Can you also provide some thoughts on the Use Cipheriv warnings.

**Comment by oliverdolgener** [comment]
We're facing the exact same error which prevents us from building our app. It only happens on Android.

**Comment by oliverdolgener** [comment]
We solved the problem by removing the distribution group, saving and re-adding the distribution group. After that the build completed successfully.

**Comment by vravindranath** [comment]
@oliverdolgener We are able to build the app successfully. The release task fails to deploy to intune. I tried to create a new distribution group and change the Groupid for the release task. But no luck here. it doesn't work for me.

**Comment by carstenhag** [comment]
Same thing is happening for us -- We have 10+ jobs in our pipeline, mostly old ones and 3 recently added ones (from 1 weeks ago).

Only the recent ones are failing to deploy on AppCenter, despite the Slug etc being correct.

**Comment by carstenhag** [comment]
Hello, could someone please provide an update for this? Thanks in advance!

**Comment by carstenhag** [comment]
@vravindranath Could you perhaps remove the warning part of the title, so that is more clear that the build fails?

**Comment by carstenhag** [comment]
Also reported this on the Developer Community 😢 
https://developercommunity.visualstudio.com/content/problem/972613/appcenter-release-task-fails-with-not-found-error.html

**Comment by vravindranath** [comment]
Do you have intune linked with Appcenter? @carstenhag

**Comment by carstenhag** [comment]
@vravindranath No, I had to look up what that is :D. Just checked the pipeline and the AppCenter entry, didn't see Intune mentioned anywhere.

**Comment by carstenhag** [comment]
Alright, I ran the pipeline 15min ago, and now all three new apps got build and deployed to AppCenter. Seems like it was a backend issue which was resolved. @vravindranath can you also try again? Hopefully it's resolved for you aswell! 👍

**Comment by leantk** [comment]
This looks to be assigned incorrectly so reassigning

**Comment by carstenhag** [comment]
Bump. Not stale.

**Comment by nichojo89** [comment]
Bump

**Comment by AdamDiament** [comment]
Bump

**Comment by annieEllenberger** [comment]
Not stale. Running into this and don't have the option of "deleting and re-creating the distribution group" as this should work for the default "Contributors" group!

**Comment by cchhllooee** [comment]
Hey has anyone found a fix when the deleting and re-creating the distribution group didn't work?

**Comment by tendolukwago** [comment]
Also seeing this issue. Not stale. Very ripe, in fact.

**Comment by JkPersson** [comment]
Any news on this issue? It has been 1½ years now.

**Comment by kek-Sec** [comment]
This issue is still open and def not stale
