### ISSUE TITLE
.Net Standard Build tasks failing with NugetVersion error

### ISSUE THREAD

**Issue by MortLupus** [microsoft/azure-pipelines-tasks#12528]
*Type*: Bug

**Enter Task Name**: .NetCoreCLIv2

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2
V2.166.1

## Environment
- Server - Azure Pipelines
       
    - account name: domacom
    - team project name: Platform
    - build definition name/build number: DC.API.Common_20200313.2

- Agent - Hosted: 
    
    -  VS2017

## Issue Description
During the .Net Build step for .Net Standard projects the following error is displayed:
Error MSB4184: The expression """.NuGetVersion" cannot be evaluated. Method 'System.String.NuGetVersion' not found.

![image](https://user-images.githubusercontent.com/1504936/76583790-50fed380-652e-11ea-84c6-f22292e68562.png)

### Task logs
[logs_15105.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4327572/logs_15105.zip)

**Comment by anuragc617** [comment]
@MortLupus This seems like a dependency issue in your csproj and not a task issue. Feel free to open if case you need any other help related to task.

**Comment by MortLupus** [comment]
@anuragc617 I don't beleive that is true. This issue is happening to all my. Net standard projects for the last two days even previous builds that worked are now failing if I rerun them.

**Comment by MortLupus** [comment]
I should also add I have not actually changed any pipeline settings or the .csproj file since the last successful builds to the current failing builds.
