### ISSUE TITLE
NugetCommand does not use Azure Credential Provider for Linux

### ISSUE THREAD

**Issue by schultetwin1** [microsoft/azure-pipelines-tasks#12520]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NugetCommand

## Environment
- Server - Azure Pipelines

## Issue Description

When using the NugetCommand task on a Linux agent, a warning is spit out by nuget.

> WARNING: The credential plugin model used by '/home/vsts/work/_tasks/NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b/2.164.0/CredentialProvider/CredentialProvider.TeamBuild.exe' is deprecated. Please contact the provider of the plugin for an alternative. More information about the recommended plugin model can be found at 'https://aka.ms/nuget-cross-platform-authentication-plugin'.

We are also seeing this old plugin crash sometimes, providing instability to our builds.

Therefore we'd like to update to the new plugin model. It looks like some logic was added to the NugetCommand task to use the next version of the credential plugin, but it's Windows only (#8367).

One option would be to integrate with the recently added= task [NugetAuthenticate](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NuGetAuthenticateV0). The NugetCommand task currently does not use the plugin setup by the NuGetAuthenticate task.

**Comment by schultetwin1** [comment]
The fix to this issue will be blocked by #12524

**Comment by jmyersmsft** [comment]
The NuGetAuthenticate task is intended to be used with a script task instead of the NuGetCommand task, so we just set up authentication and get out of the way and you can call nuget.exe however you want

**Comment by schultetwin1** [comment]
Ah, gotcha, thanks for the explanation. In that case, this issue is not blocked by #12524 but is still an issue all the same.

**Comment by herenhuang** [comment]
Hey @schultetwin1 - are you able to use NugetAuthenticate and script instead of NugetCommand? That is our recommended path moving forward.

**Comment by schultetwin1** [comment]
Hi @herenhuang, definitely! Currently we use NugetAuthenticate and a script instead of NugetCommand.

I had this issue open to point out that if you run NugetAuthenticate to install the Azure Credential Provider plugin, and then use NugetCommand, NugetCommand will not use that plugin.

Up to you guys how you want to proceed.

**Comment by herenhuang** [comment]
Got it! We've got it in our bug log. And to confirm, this isn't currently blocking right?

**Comment by schultetwin1** [comment]
Thank you!!

>  And to confirm, this isn't currently blocking right?

That is correct. This isn't currently blocking.
