### ISSUE TITLE
Callback for Http Request Chaining in Server Task

### ISSUE THREAD

**Issue by bhavanakonchada** [microsoft/azure-pipelines-tasks#12536]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Custom task mimicking Azure Policy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

This Q is related to a Server Task

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I am trying to accomplish a custom requirement using Http Request Chaining server task.
* In the first call of the chain, I request for a bearer token for a service bus resource.
   Parse the response of first call - and extract bearer token into an output variable.
* In the second call, I use the bearer token to post a message to service bus.

Once the posted message is picked by another engine, then starts the long running operation. I want to callback to the ADO server once the long running operation is complete.

My questions are:
1. How can I hide the "bearer token" received as response to first call in the chain. It shows up in the logs.

2. How can I call back the server after my long running process has completed, to mark the task completed or failed ? The documentation is not clear about the call back or " wait for completion" operation for Http Request Chaining. I tried borrowing pieces from Invoke REST API task, where Wait for Completion works, but its not working in Http Request Chaining. The task simply completes as succeeded.

Here is a screenshot of my custom task execution:
![image](https://user-images.githubusercontent.com/8509708/76693189-5e938680-661e-11ea-97b8-76025410e556.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by bhavanakonchada** [comment]
Can someone please help me on this ?

**Comment by Josh-01** [comment]
Hi,

The 'waitForCompletion' option is currently not available for HttpChainRequest task by design.
You could raise it as a feature request, which we could look at in coming sprint.

For hiding the variable could you please try the following :
Add 'access_token' or the bearer token variable as an environment variable and set it as secret : 
value as $(<variableName that needs to be hidden in response>)

- Thanks

**Comment by Josh-01** [comment]
Hi @bhavanakonchada , was this issue resolved for you ?

**Comment by bhavanakonchada** [comment]
Hi @Josh-01 ,

Please let me know of the process to raise a feature request for "waitForCompletion" in Http Chaining task. We are waiting for this feature.

**Comment by Josh-01** [comment]
Hi @bhavanakonchada ,
You can raise a new feature request on the Developer Community portal : https://developercommunity.visualstudio.com/spaces/21/index.html for this.

Thanks.

**Comment by bhavanakonchada** [comment]
Hi @Josh-01,

I have created a new feature request: https://developercommunity.visualstudio.com/idea/1063478/waitforcompletion-in-httpchainrequest-server-task.html

Please keep me posted on this one.

Thanks a lot for your support!
