### ISSUE TITLE
AzureFileCopy Optional Arguments not clear

### ISSUE THREAD

**Issue by harre096** [microsoft/azure-pipelines-tasks#12534]
**Question**  
*Type*: Documentation

**Enter Task Name**: AzureFileCopy

## Issue Description
Documentation say the following regarding flags.
    Blob Destination: Supported additional arguments for copy to blob are /BlobType:, /Pattern:, /L, /Z, /XN, /A, /IA:, /XA:, /NC:, /DestType: and /SetContentType.
What do these one letter abbreviations mean? Where can I find full descriptions of how the options work?

**Comment by 20shivangi** [comment]
@harre096 Here is the documentation : https://docs.microsoft.com/en-us/previous-versions/azure/storage/storage-use-azcopy
