### ISSUE TITLE
Azure Resource Group Deployment Task - Override Template Parameter issue

### ISSUE THREAD

**Issue by SanjayJanardhan-89** [microsoft/azure-pipelines-tasks#12539]
Hi,

In the Azure Data Factory Pipeline I have created, it expects one of the ADF Pipeline Parameter such as database name. 
So in Azure DevOps I was trying CI/CD, I was trying to override it using the "Override Template Parameters" in the Azure resource group deployment

Azure Data Factory Pipeline Name : 01-Initial
Parameter Name in the Azure Data Factory Pipeline : DatabaseName

-01-Initial 01-Initial Pipeline_properties_01-Initial_parameters_DatabaseName "AdventureWorksDev"  

2020-03-16T02:59:11.0536155Z Creating deployment parameters.
2020-03-16T02:59:11.0542949Z The detected encoding for file 'D:\a\r1\a\_DF\DFNP\ARMTemplateForFactory.json' is 'utf-8'
2020-03-16T02:59:11.0549557Z The detected encoding for file 'D:\a\r1\a\_DataFactory\DFNP\ARMTemplateParametersForFactory.json' is 'utf-8'
2020-03-16T02:59:11.0551078Z There was an error while overriding '' parameter because of 'TypeError: Cannot read property 'type' of undefined', make sure it follows JavaScript Object Notation (JSON)

**Comment by vineetmimrot** [comment]
@SanjayJanardhan-89 Can you tell what are you passing in the override parameter input field.

**Comment by SanjayJanardhan-89** [comment]
@vineetmimrot 
I am passing below parameters in the Override Parameter Input field-

-factoryName "DataFactoryNP" 
-01-Initial 01-Initial Pipeline_properties_01-Initial_parameters_DatabaseName "AdventureWorksDev"

**Comment by SanjayJanardhan-89** [comment]
In this case -
 "01-Initial" is the actual Azure DataFactory pipeline name we are trying to pass the DatabaseName

**Comment by vineetmimrot** [comment]
Can you make 01-Initial => "01-Initial"
Also Try passing all in single line:

-factoryName "DataFactoryNP" -01-Initial "01-Initial" Pipeline_properties_01-Initial_parameters_DatabaseName "AdventureWorksDev"

**Comment by SanjayJanardhan-89** [comment]
Hi Guess, I sent you wrongly formatted one, below is the correct string, please let me know if you would like me to make any changes for this -

-factoryName "FCTDataFactoryNP" -01-Initial Pipeline_properties_01-Initial_parameters_AzureDatabaseName "AdventureWorksDev"

**Comment by vineetmimrot** [comment]
For the second parameter: -01-Initial Pipeline_properties_01-Initial_parameters_AzureDatabaseName
Why is there a space in it? Can you make the parameters without space?

**Comment by SanjayJanardhan-89** [comment]
01-Initial is the Azure Data Factory Pipeline Name, and it expects a Paramter AzureDatabaseName. That how its generated. Please let me know if you would like to remove space and try.

**Comment by vineetmimrot** [comment]
The override parameter works as <key, value> pair.
Are you able to make it work locally while passing the override parameter in az-CLI or az Powershell?? We don't have idea of how to pass parameters generated for Azure Data Factory. Please check the doc of the Azure Data Factory. The ARG task just passes the parameters to the ARM API and doesn't do any modifications.

**Comment by SanjayJanardhan-89** [comment]
Hi, I have not tried using az-CLI or az Powershell. Not sure how to try that.
My intention is to send a dynamic value to Azure Data Factory Pipeline. 
In my case I guess its taking <K1, K2, K3>. Can you please let me know if there is any other way to find alternative to handle in Azure Devops ?

**Comment by vineetmimrot** [comment]
Please reach out to Azure Datafactory team, they will help you out. Thanks.
