### ISSUE TITLE
dotnet restore failed unable to load the service index for source from collection feed

### ISSUE THREAD

**Issue by artem-voropaev** [microsoft/azure-pipelines-tasks#12538]
Hello, we have a problem restoring nuget via dotnet restore task, error is "unable to load the service index for source from collection <collection feed url>.
LogFile in attachment
[logs_38236.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4337443/logs_38236.zip)

**Comment by jmyersmsft** [comment]
Try adding the NuGet Authenticate task and then using a script task to run dotnet restore instead of using the dotnet core task. On-premises TFS and NuGet have some unfortunate technical limitations when used together, and the NuGet Authenticate task flow might be set up better for that scenario.

**Comment by jmyersmsft** [comment]
Ah, forgot that task doesn't exist yet in the currently-released version of the on-premises product: https://github.com/microsoft/azure-pipelines-tasks/issues/12471#issuecomment-594810802

**Comment by jmyersmsft** [comment]
To be clear, that comment has instructions for installing the new task into your existing TFS instance

**Comment by rantalaja** [comment]
Hi,
I've installed NuGet Authenticate task, how is that script task to run dotnet restore supposed to be used? If I'll just run dotnet restore it'll end up with this:

C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets(123,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action.

**Comment by jmyersmsft** [comment]
It should Just Work. If you run add `--verbosity normal` or `--verbosity detailed` to your dotnet restore command line, you should get more information about the credential acquisition process, which may help figure out why it's not.

**Comment by rantalaja** [comment]
This is output with --verbosity detailed. Does that NuGet Authenticate task authenticate to all internal repositories since when using script task to run dotnet restore, there's no option to choose NuGet repository?

"C:\agent_work\38\s\XXX\XXX.sln" (Restore target) (1) ->  (Restore target) ->          c:\agent_work\_tool\dotnet\sdk\3.1.200\NuGet.targets(124,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\agent_work\38\s\XXX\XXX.sln]

"C:\agent_work\38\s\XXX\XXX.sln" (Restore target) (1) -> (Restore target) -> 
         c:\agent_work\_tool\dotnet\sdk\3.1.200\NuGet.targets(124,5): error : Unable to load the service index for source http://XXX/tfs/XXX/_packaging/nuget-common/nuget/v3/index.json. [C:\agent_work\38\s\XXX\XXX.sln]
       c:\agent_work\_tool\dotnet\sdk\3.1.200\NuGet.targets(124,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\agent_work\38\s\XXX\XXX.sln]

**Comment by jmyersmsft** [comment]
Sorry this fell on the floor. There should be additional output from the credential provider before those lines. I will need to see that output as well. If there is no additional output, try setting the build variable NUGET_CREDENTIALPROVIDER_LOG_PATH to an absolute path (the directory must exist, but the file doesn't need to). The artifacts-credprovider will log at maximum verbosity. Another possible thing to try would be to enable the option in the NuGetAuthenticate task to always reinstall the credential provider, in case there's an old version of it lying around on the build agent's disk.

**Comment by fidelflorian** [comment]
Azure DevOps pipeline, NuGet restore error: Unable to load the service index for source
Solution:
Please login project B->Project setting->Settings->please disable the option Limit job authorization scope to current project
