### ISSUE TITLE
Environment variable containing the exit code should be set to make the Helm diff plugin useful

### ISSUE THREAD

**Issue by bada09089** [microsoft/azure-pipelines-tasks#12532]
*Type*: Feature

**Enter Task Name**: HelmDeploy@0  

## Issue Description
We want to check a release difference before we upgrade it. For this purpose we installed the [helm diff plugin](https://github.com/databus23/helm-diff) and executed it with the HelmDeploy@0 - Task. Depending on the exit code, we could skip the upgrade if no changes have been made (exit code 0), or wait for approval in case of changes (exit code 2). 

To achieve this we would have to process the exit code. Therefore it would be nice to set an environment variable like "HELM_LAST_EXITCODE" which should contain the exit code of the execution. 
Similar things have been done for the Terraform extension here: https://github.com/charleszipp/azure-pipelines-tasks-terraform/pull/74

Additionally if Helm diff runs with the --detailed-exitcode parameter, exit code 2 means that new resources or changes are available, so it would be nice not to fail the Helm-task.

**Comment by shigupt202** [comment]
@bada09089 I've raised a PR to add an output variable for helm exit code. Regarding you second ask, not failing the task depending on the exit code of a particular helm command does not seem to be a good idea, mainly because it's a very specific scenario and there are other ways to do it. You can set `continueOnError` to true and then take further steps depending upon the exit code.

**Comment by bada09089** [comment]
Hi @shigupt202, lots of thanks for adding the output variable.
The problem with "continueOnError" is that in chase of changes the entire pipeline is marked as "Partially succeeded". 
Would it be possible to handle it like the terraform module is doing it (https://github.com/charleszipp/azure-pipelines-tasks-terraform/commit/8c68c17309feae961410015e18fbbe0fa5a31a16)? So to detect if "helm diff" is executed with the "--detailed-exitcode" argument and therefore not fail the Helm Task on exit code 2.
