### ISSUE TITLE
JenkinsQueueJobV2 fails with no useful error message when incorrect Jenkins build parameters are provided

### ISSUE THREAD

**Issue by eogas** [microsoft/azure-pipelines-tasks#12543]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JenkinsQueueJobV2

## Environment
- Server - Azure DevOps Server (Dev17.M153.5)
- Agent - Private (Windows Server 2012 R2, Agent.Version 2.153.1)

## Issue Description
Some teammates and I triaged this issue today. We were trying to trigger a Jenkins job using the JenkinsQueueJobV2 task, and it was returning a 400 error with no additional info (even with debug output enabled):

![image](https://user-images.githubusercontent.com/143012/76891161-e8319700-685e-11ea-9ce5-b598d20997ab.png)

Reproducing the call in postman showed us the actual error. We had an incorrectly specified parameter that the job wasn't expecting:

![image](https://user-images.githubusercontent.com/143012/76891658-be2ca480-685f-11ea-9df2-e37f5a2b1476.png)

It seems that the body of the error response is being lost, and no info is being passed on to the logs in Azure DevOps. The error message coming back in postman pointed us straight to the problem, but it's a bummer to have to re-craft this request by hand. It would be great if this response was included in the logs of the pipeline.

I would consider this a bug, because the task is clearly trying to write something to the log, but it just ends up writing `undefined`.

**Comment by egor-bryzgalov** [comment]
Closing this issue since the fix is deployed. Feel free to reopen it.
