### ISSUE TITLE
Use .Net Core task cannot find version 3.1.102

### ISSUE THREAD

**Issue by jeroenlandheer** [microsoft/azure-pipelines-tasks#12540]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: here  
Use .Net Core

list here (V# not needed):  
Version 2.

## Environment
- Server - Azure DevOps Server

- Agent - Private
OS: Windows Server 2016
Version: 2.153.1

## Issue Description
The SDK version 3.1.102 cannot be found by this task while it is still available online.

### Task logs

```
Tool to install: .NET Core sdk version 3.1.102.
No matching sdk version could be found for specified version: 3.1.102 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 3.1.102 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 3.1
No matching sdk version could be found for specified version: 3.1.102 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Searching for version in channel 3.0
No matching sdk version could be found for specified version: 3.1.102 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
```

## Troubleshooting
Since version 3.1.200 just got released I think it might have something to do with that.

**Comment by dnperfors** [comment]
We now have the problem with version 3.1.200 as well...

**Comment by tejasd1990** [comment]
Hi @jeroenlandheer, are you still facing this issue?
