### ISSUE TITLE
service-hooks: queuing order?

### ISSUE THREAD

**Issue by bitsofinfo** [microsoft/azure-pipelines-tasks#12552]
Noticing that service hooks for a configured repo, are queued up, but the events are emitted out of order? Is this expected?

**Comment by bitsofinfo** [comment]
https://stackoverflow.com/questions/60776743/azure-service-hooks-webhooks-queuing-git-operations-out-of-order

**Comment by bitsofinfo** [comment]
@ewah

**Comment by damccorm** [comment]
Hey @bitsofinfo this doesn't look like a tasks specific issue which is what this repo is for, would you mind opening up a ticket here - https://developercommunity.visualstudio.com/spaces/21/index.html
