### ISSUE TITLE
.NET Core build task not honoring project dependencies on Hosted windows-2019

### ISSUE THREAD

**Issue by groogiam** [microsoft/azure-pipelines-tasks#12563]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: >.NET Core build  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines
https://apppotion.visualstudio.com/
App Potion
App Potion V2 CI Build
#20200322.12

Hosted windows-2019

Issue does not manifest on private pipeline (Windows 10 1909 with Visual Studio 2019)

## Issue Description

The project dependency order is not being honored for some reason on hosted windows-2019 image. This same build works fine on private images but for some reason it builds solution projects out of order on this image causing build errors. 

### Task logs
[4_Build.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4366090/4_Build.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
The server project references the sandbox. The sandbox project is being built before the sandbox has completed causing a build error.

`src\AppPotion.Server\Build\BuildResources.resx(0,0): Error MSB3103: Invalid Resx file. System.IO.FileNotFoundException: Could not find file 'D:\a\1\s\src\AppPotion.Sandbox\bin\AppPotion.Sandbox.1.0.0.nupkg'.`

**Comment by vineetmimrot** [comment]
@groogiam Are you able to build this project locally on SDK 3.x? If yes, then please file the bug on dotnet repo. The issue is related to dotnet tool not the task.

**Comment by vineetmimrot** [comment]
If your private build is using SDK 2.X, then better use UseDotnet task to install the 2.X SDK before the build task, to make it run successfully.
