### ISSUE TITLE
DotNetCoreCli Custom Command Fails With EF 

### ISSUE THREAD

**Issue by stevenfowler16** [microsoft/azure-pipelines-tasks#12568]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLIV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Devops Server
    
    - If using TFS on-premises, provide the version:  Dev17.M153.5
   
- Agent - Hosted or Private: Private
 
    - If using private agent, provide the OS of the machine running the agent and the agent version:  
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
Agent Version:           2.153.1

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Quotes are appended using the custom command option and ef migrations will not be recognized as a command.

Here is testing showing cmd.exe not working with quotes then working without quotes. 
![image](https://user-images.githubusercontent.com/12255820/77349719-d2feb180-6d11-11ea-8684-5142e172d44c.png)

Powershell doesn't care and runs either way
![image](https://user-images.githubusercontent.com/12255820/77349579-9af76e80-6d11-11ea-800b-dbdf691e97a4.png)

Here is the command that is outputted from the logs. 
"C:\Program Files\dotnet\dotnet.exe" "ef migrations --project projectlocation script --idempotent -v"
Could not execute because the specified command or file was not found.

I can have this command run in a different spot but I was trying to keep my references for the dotnet executable similar and this task seemed like a good spot to make that happen. I'm fairly new so I could be missing something simple. 

I can confirm that there is no quotes in the YAML file as well. 
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by vineetmimrot** [comment]
Have a look at this
https://github.com/microsoft/azure-pipelines-tasks/issues/12548

**Comment by vineetmimrot** [comment]
Please re-open it if you face any issues.
