### ISSUE TITLE
Broken link in VSTest v2 Task to https://aka.ms/paralleltestexecution

### ISSUE THREAD

**Issue by SabotageAndi** [microsoft/azure-pipelines-tasks#12567]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTest

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted
    
## Issue Description

In the VSTest task is a link to https://aka.ms/paralleltestexecution which resolves to https://docs.microsoft.com/en-us/archive/blogs/devops2016/10/10/parallel-test-execution. But this blogpost isn't available anymore.

Task:
![image](https://user-images.githubusercontent.com/859801/77324668-67b7de00-6d17-11ea-9be5-2135846f34f7.png)

404
![image](https://user-images.githubusercontent.com/859801/77324777-8d44e780-6d17-11ea-8bcc-e56be0ae5210.png)

Link in resources: https://github.com/microsoft/azure-pipelines-tasks/blob/91c78025f96435f93745d96bc64ca8352e29894c/Tasks/VsTestV2/Strings/resources.resjson/en-US/resources.resjson#L45

**Comment by PBoraMSFT** [comment]
The link is fixed.
