### ISSUE TITLE
Artifact name is used for multiple purposes which is counter-intuitive

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/azure-pipelines-tasks#1256]
I created a multi-configuration build which has "BuildConfiguration" as multiplier. This variable contains "Release, Release BSO" which results in two builds being triggered when this job is queued. A problem arises with the "Publish Build Artifact" step. One of the properties of this step is "Artifact name" which is used two-fold:
- as a name for the artifact (as you can see in the "artifact" tab in the build result view)
- as a folder name appended to the "Path" property for the drop location

Because the "Artifact name" is appended to the drop location, we can't use something like "assemblyArtifact" because our drop location has a strict naming policy (/builds/development/<productname>/<versionTag>). To work around this problem (or "feature" as you may call it :) ), we used a variable $(VersionTag) as "Artifact name".

All worked like a charm, until we checked the "multi-configuration" switch. In that case, the complete build is triggered twice, one time for each "BuildConfiguration". The "Publish Build Artifact" will fail, because the "Artifact name" should be unique and it isn't, because $(VersionTag) is the same for each BuildConfiguration.

To work around this problem we used another bug (or maybe another feature). If the "Artifact name" contains a \ , everything before this \ is ignored in the final path for the drop location. We altered the "Artifact name" to "$(BuildConfiguration)\$(VersionTag)". This way the name is unique as name for the artifact and the path for the drop location stays the same.

This feels really awkward, there should be a better way to solve this. Maybe I'm missing something here, or using a task which was not meant to be used like this.

Can anyone tell me if I'm on the wrong path here, or this tasks needs some rework?

**Comment by chrisrpatterson** [comment]
To goal of the multi-configuration option is to enable scenarios such as building release and debug bits for your application.  In that case I would expect you would generate two different artifacts, 1 for each configuration.  You would then end up with something like /builds/development/artifact-release and /builds/development/artifact-debug

Can you give me a description if your multi-configuration scenario if it is not to generate different binaries?

**Comment by tomkuijsten** [comment]
I do create different binaries. The problem is that my distinction of drop folder isn't the last folder, it's somewhere else in the path. The "last" folder should have the same name, no matter what configuration, eg:


> \\\\server\builds\development\product1 (debug)\v1.0.0.0
> \\\\server\builds\development\product1 (release)\v1.0.0.0

If I want this setup, the artifact name should be "v1.0.0.0" in both configurations.

I hope this helps to clarify the problem, let me know if it isn't :)

**Comment by chrisrpatterson** [comment]
In your target location for your artifact in the publish artifacts task you should be able to input something like \\sever\builds\development\project1 ($(BuildConfiguration))\ and then have your artifact name be v1.0.0.0. It seems that would cover the scenario you are laying out.

**Comment by tomkuijsten** [comment]
No that won't work. When I do a multi-configuration build with Debug and Release (which both have v1.0.0.0) the build will fail with the message that the artifact name should be unique.

**Comment by cwisking** [comment]
Hey guys, was a solution ever found for this?

**Comment by tomkuijsten** [comment]
As far as I know. If I take a look at the labels, I don't think its on a roadmap yet.

**Comment by moswald** [comment]
@cwisking, @tomkuijsten I don't know when it was added, but this works now. Both with the preview Publish Pipeline Artifact task and the stable Publish Build Artifact. Now the whole artifact path is used to establish uniqueness.

![image](https://user-images.githubusercontent.com/85051/52588440-1b0a8f80-2e02-11e9-8bb7-f6e9b474426b.png)
