### ISSUE TITLE
NodeTool - Cache node binaries "locally"

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azure-pipelines-tasks#12569]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: NodeTool

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- Agent - Hosted or Private: 
    Hosted

## Issue Description

Would it be possible to cache the node binaries "locally" (somewhere inside the azure pipelines system) so that the task isn't required to reach out to nodejs.org each time it downloads the binary? My team regularly gets tar unexpected eof errors during this task, seemingly because of the flakiness of the node CDN. There's an open issue for github actions to do something similar.
https://github.com/actions/setup-node/issues/77

**Comment by PedroLamas** [comment]
I'm currently seeing this recurrently on one of our builds while using the "ubuntu-16.04" image with the following:

```yaml
task: NodeTool@0
inputs:
  versionSpec: '12.x'
displayName: 'Install Node.js 12.x'
```

It gets stuck on that step for 4 minutes and sometimes even times out...
