### ISSUE TITLE
dataRowInfo and resultType is not included in the TRX file. How to include these attributes in TRX file?

### ISSUE THREAD

**Issue by vishnuprakash9845** [microsoft/azure-pipelines-tasks#12561]
### I am trying to parse the TRX and generate the report to team members, but while parsing i am facing small problem in identifying DataDriven and Non-DataDriven  Test cases. Following are the steps i followed 

Step-1: I created one solution(MS Test Unit framework) which have combination of DataDriven and Non-DataDriven tests.
Step-2: I integrated to Azure Devops by creating the pipeline to run these tests. So when i trigger the build pipeline Tests are getting executed and TRX file is getting generated.
Step-3: But the attributes like dataRowInfo and resultType are missing in TRX file which will indicate whether tests are DataDriven are not. 

Attached the Devops Visual Studio Task settings
![Build_Pipeline_Settings](https://user-images.githubusercontent.com/24207575/77245438-a2047b00-6c44-11ea-9774-9238a2654554.jpg)

Please let me know, how to get the attributes dataRowInfo and resultType in the TRX file.

Thank you.

**Comment by ShreyasRmsft** [comment]
@vishnuprakash9845 

> dataRowInfo and resultType are missing in TRX file which will indicate whether tests are DataDriven

The trx schema does not have these attributes. May I know why you are parsing the trx file yourself and not using the [inhouse test reporting](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops) solution present in AzureDevOps?

**Comment by vishnuprakash9845** [comment]
> @vishnuprakash9845
> 
> > dataRowInfo and resultType are missing in TRX file which will indicate whether tests are DataDriven
> 
> The trx schema does not have these attributes and it is not possible today to get these in the trx. May I know why you are parsing the trx file yourself and not using the [inhouse test reporting](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops) solution present in AzureDevOps?

Thank you Shreyas for the reply,

I am parsing the TRX because, I need to send the daily report to team about the Test Results. In Devops after tests got executed, under summary tab we can see the graph and details(Passed,Failed). But we cannot sent this summary tab details in mail to team members. 

Correct me if i am wrong, using  inhouse test reporting we cannot sent report in mail to others right? 

One small help is there any reporting tasks available to generate reports out of the trx file or in devops.

**Comment by ShreyasRmsft** [comment]
The default inbuilt email notification for build complete ought to have test summary in it.

https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops

![image](https://user-images.githubusercontent.com/25194518/77310408-4ad5d780-6d24-11ea-9e6d-cffd68769143.png)

You'll get an email similar to the above image?

**Comment by vishnuprakash9845** [comment]
> The default inbuilt email notification for build complete ought to have test summary in it.
> 
> https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops
> 
> ![image](https://user-images.githubusercontent.com/25194518/77310408-4ad5d780-6d24-11ea-9e6d-cffd68769143.png)
> 
> You'll get an email similar to the above image. With a link to the build.

Ok once again thank you.

But the above link just send notification to team members, again they need to open the link and see. But one small issue is Only people with devops access can only view the detailed info about the test results.(In mycase other team members and clients can be given our project access due to security and privacy) 


**But I am planning to send the Automation summary report in mail to the required people in the below format.** 
![image](https://user-images.githubusercontent.com/24207575/77315958-85dd0880-6d2e-11ea-8144-57a4003885d3.png)

**Attachment html will contain the detailed info about the failures, but table will tell the overall summary.**

![image](https://user-images.githubusercontent.com/24207575/77316035-a2794080-6d2e-11ea-91ad-de999b81011c.png)

**Shreays, is there any way to include missing attributes in the TRX schema .**

**Comment by ShreyasRmsft** [comment]
@vishnuprakash9845 the trx's schema cannot be changed. I'm afraid what you are asking isn't possible.
