### ISSUE TITLE
DownloadPipelineArtifact@2 does not sets output variable BuildNummer

### ISSUE THREAD

**Issue by LaszloMoldovan** [microsoft/azure-pipelines-tasks#12578]
## Required Information

The DownloadPipelineArtifact@2 does not sets output variable BuildNummer.
Instead of it sets the environment variable BuildNummer
I could see this by running the pipeline with diagnostics enabled

2020-03-25T08:28:28.4521394Z Download from the specified build: #1787
2020-03-25T08:28:28.4543651Z ##[debug]Processed: ##vso[task.setvariable variable=BuildNumber;issecret=False;]1787
2020-03-25T08:28:28.4544474Z Download artifact to:

Would have expected an isOutput in the ##vso… 

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPipelineArtifact@2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines or TFS on-premises?
  Azure Pipeline
    l a s z l o . m o l d o v a n @ u n i t 4 . c o m
    U4ERP
    U4ERP.Devops
    1962

    
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
             Pool: Azure Pipelines
             Image: windows-latest
            Agent: Azure Pipelines 2
## Issue Description
Task name: DownloadStampArtifacts1 / DisplayName: Download artifacts
![image](https://user-images.githubusercontent.com/62642357/77519197-673a5700-6e7f-11ea-8337-8d2c439380a1.png)

![image](https://user-images.githubusercontent.com/62642357/77519023-0ca0fb00-6e7f-11ea-89e9-ac89f15471ce.png)
![image](https://user-images.githubusercontent.com/62642357/77519155-496cf200-6e7f-11ea-8974-27e30039f6ef.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
[logs_1962.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4379912/logs_1962.zip)

Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
2020-03-25T08:28:28.4521394Z Download from the specified build: #1787
2020-03-25T08:28:28.4543651Z ##[debug]Processed: ##vso[task.setvariable variable=BuildNumber;issecret=False;]1787
2020-03-25T08:28:28.4544474Z Download artifact to: D:\a\1\s\U4ERP
2020-03-25T08:28:28.9882294Z ##[debug]Dedup parallelism: 192

-----------------------------------------------------
2020-03-25T08:28:58.2402588Z ##[debug] Converted to bool: False
2020-03-25T08:28:58.2414532Z ##[debug]INPUT_SCRIPT: 'echo "$(DownloadStampArtifacts1.BuildNumber)" echo "1787"'
2020-03-25T08:28:58.2415821Z ##[debug]INPUT_WORKINGDIRECTORY: 'D:\a\1\s'

**Comment by jahsu-MSFT** [comment]
Thanks for reporting. @fadnavistanmay is working on setting BuildNumber output variable and has a PR out for this. He will look into the issue.

**Comment by avivanoff** [comment]
Same as https://github.com/microsoft/azure-pipelines-tasks/issues/11784.

**Comment by fadnavistanmay** [comment]
This was released.
