### ISSUE TITLE
Wildcard Versions do not work for UniversalPackages download task

### ISSUE THREAD

**Issue by olialth** [microsoft/azure-pipelines-tasks#12572]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UniversalPackages@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
Account: Daimler-mic
Project: EvAnalytics

- Agent - Hosted or Private: 
    
Hosted Agent ubuntu 18.04

## Issue Description

Problem is that when downloading artifacts, an asterisk cannot be specified as version. (*)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Downloading package: systemtest, version: 1.* using feed id: evanalytics-azurefunctions, project: EvAnalytics
/opt/hostedtoolcache/ArtifactTool/0.2.128/x64/artifacttool universal download --feed evanalytics-azurefunctions --service https://dev.azure.com/daimler-mic/ --package-name systemtest --package-version 1.* --path /home/vsts/work/1/s/functionAppPackage --patvar UNIVERSAL_DOWNLOAD_PAT --verbosity None --project EvAnalytics
{"@t":"2020-03-24T14:32:59.3233782Z","@m":"ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 079db612-f264-44fe-9213-204a8da2811d","@i":"ac56d3a5","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-03-24 14:32:59.323Z"}
{"@t":"2020-03-24T14:33:00.6221105Z","@m":"Did not find any versions of 'systemtest' that matched the pattern '1.*'","@i":"d7e31381","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2020-03-24 14:33:00.622Z"}
##[error]Error: An unexpected error occurred while trying to download the package. Exit code(18) and error({"@t":"2020-03-24T14:32:59.3233782Z","@m":"ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 079db612-f264-44fe-9213-204a8da2811d","@i":"ac56d3a5","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-03-24 14:32:59.323Z"}
{"@t":"2020-03-24T14:33:00.6221105Z","@m":"Did not find any versions of 'systemtest' that matched the pattern '1.*'","@i":"d7e31381","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2020-03-24 14:33:00.622Z"})

**Comment by magleaso** [comment]
What is the behavior you expect to see here? This looks like a feature request to me

**Comment by olialth** [comment]
No, actually it is a bug. Because the documentation states it should work:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops


It should be according to the documentation:
Select the package version or use a variable containing the version to download. This entry can also be a wildcard expression such as * to get the highest version, 1.* to get the highest version with major version 1, or 1.2.* to get the highest patch release with major version 1 and minor version 2.

**Comment by olialth** [comment]
Would you agree?

**Comment by magleaso** [comment]
Yes, can you provide a full log please?

**Comment by olialth** [comment]
Sure, please see attached... 
[failurelog_downloadtask.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4377637/failurelog_downloadtask.txt)

**Comment by magleaso** [comment]
I'll see if I can repro this locally

**Comment by olialth** [comment]
Thanks!

**Comment by magleaso** [comment]
Wildcard matching is working on my build, can you provide a screenshot of the versions of this package on your feed?

**Comment by olialth** [comment]
Version      : 0.166.0

**Comment by olialth** [comment]
![image](https://user-images.githubusercontent.com/17128545/77517269-20972d80-6e7c-11ea-8e2e-aada5e2f4f1e.png)

**Comment by magleaso** [comment]
Can I get your yaml for the task as well?

**Comment by olialth** [comment]
```
- task: UniversalPackages@0
              inputs:
                command: 'download'
                downloadDirectory: '$(System.DefaultWorkingDirectory)/functionAppPackage'
                feedsToUse: 'internal'
                vstsFeed: 'EvAnalytics/evanalytics-azurefunctions'
                vstsFeedPackage: 'systemtest'
                vstsPackageVersion: '*'
```

**Comment by magleaso** [comment]
One odd thing I'm noticing is your YAML specifies '*' but the text logs show '1.*'. Was this log produced with that YAML exactly?

**Comment by magleaso** [comment]
I believe this is the same as [[Bug] Universal Package Version Wildcard doesn't support SemVer 2.0 meta information](https://github.com/Azure/azure-devops-cli-extension/issues/852). Something is catching this more informative exception message and rethrowing a more generic one. I will look into what it would take for us to support wildcard working on pre-release and making the exception message correct in this case.

**Comment by slawekww** [comment]
Is it any news to fix this issue?
It really blocks migration to YAML pipeline as Azure artifacts cannot be used as YAML pipeline resources and UniversalPackages task could download only fixed version.

**Comment by magleaso** [comment]
I wasn't very clear about it, but the wildcards do work. They do not match pre-release versions (versions with a dash in the version number). Matching pre-release can be tricky because they are so much less structured than the first 3 version segments. Pre-release matching is unlikely to be prioritized in the near term. In the case of the person who originally created this ticket, I would advise using build metadata to store the information that is currently in the pre-release string (use the '+' character) and promote versions to a release view if you want to indicate some versions as released

**Comment by slawekww** [comment]
I cannot find automatic/programmatic promotion of Azure Artifacts universal packages from pre-release to release outside Azure.
If it is API for it, could it be used with PAT?

Let's assume that I have external CI system outside Azure and push my artifacts to Azure Artifacts.
It works great to get them and trigger Release pipelines using those artifacts: once release pipeline is started it computes exact/fixed version of universal artifacts.

For YAML pipeline, I cannot define Universal artifact as resource. Only method is to use UniveralPackages task but unfortunately it does not support widecard for pre-release versions.
For me it sounds like not consequence in design: it should be special filter parameter to distinguish 'pre-release' or 'release' and use version for it.

To say more, 'az cli' command should support to get all versions of artifacts and promote artifacts.
All is about automation and user friendly interface.

BTW, I've found undocumented API to get versions of artifacts:
https://feeds.dev.azure.com/${ORGANIZATION}/_apis/packaging/Feeds/${FEEDNAME}/packages?api-version=5.1-preview.1
It does not work from Azure DevOps if ServiceConnection has no enough privileges to access this API.

**Comment by magleaso** [comment]
That get packages API is documented here: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact%20%20details/get%20packages?view=azure-devops-rest-5.1

The API for promoting a UPack package is here: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/universal/update%20package%20version?view=azure-devops-rest-5.1
Set 'views' in the body of the request to promote to the specified views

**Comment by slawekww** [comment]
@magleaso Thank you! It allows to manage my use case and get list of universal artifacts even if they are not promoted to 'release'. 
Anyway it would be good to support those APIs from 'az cli' command in future.

**Comment by hansmbakker** [comment]
Please upvote for wildcards for pre-releases at https://developercommunity.visualstudio.com/t/Support-wildcards-for-prereleases-when-i/1645572
