### ISSUE TITLE
File transform task displays error when used on JSON

### ISSUE THREAD

**Issue by miroelk** [microsoft/azure-pipelines-tasks#12576]
*Type*: Bug
**Task Name**: File transform

## Environment
- Agent:
Private self-hosted agent: v 2.165.2
OS: Windows Server 2016 (version 1607)

## Issue Description

Task displays error when transforming JSON file, but finishes sucessfully.
![fileTransformTask](https://user-images.githubusercontent.com/62104255/77477208-48ef3f80-6e1c-11ea-8635-eedb895f979e.png)

### Task logs
**snippet from logs:**
##[debug]applying include pattern
##[debug]adjustedPattern: 'C:\BuildAgents\hefaistos\_work\16\s\**\*.config'
##[debug]0 matches
##[debug]0 final results
##[error]Unable to apply transformation for the given package - Changes are already present in the package.
##[debug]Processed: ##vso[task.issue type=error;]Unable to apply transformation for the given package - Changes are already present in the package.
##[debug]system.accessToken=***

**Task definition:**
![fileTransformTask-pipeline](https://user-images.githubusercontent.com/62104255/77478030-9fa94900-6e1d-11ea-8725-938a8e934bb5.png)

Solution doesn't contain XML .config files - configuration is stored in JSON files.

The error is misleading because the transformation was successful.

**Comment by eaarora-ms** [comment]
@miroelk File transformation and variable substitution are two separate features of the task. Here the task says it has failed transformation. Please clear out the transformation rules in the task to get rid of this error.
