### ISSUE TITLE
Function App deploy with slot swap behaves strange

### ISSUE THREAD

**Issue by SandraBosic** [microsoft/azure-pipelines-tasks#12571]
We encountered the following issue:

We have a Release pipeline in Azure DevOps for deploying a Function App to a slot. A stage for deploying consists of two tasks: 
- "Azure Functions" task for deploying to function app  
- "Azure App Service manage" task for swapping slots

After stage is run for the first time everything is as should be: Functions are deployed and slots are swapped. On the second run, logs on Azure Devops show that everything is 
done successfully, but the real state on Function App is following: Production slot is empty and stage slot has functions. Logs on DevOps show that everything was succesfully, 
but deployment logs on Azure portal show that only swap is done (which seems to be correct). Logs on Advanced Tools (Kudu) -> Tools -> Diagnostic dump also show that there were more swap then deploy operations.

The further runs of the stage acts randomly (sometimes works correctly, sometimes only swap is done, at least according to diagnostic dump logs).

**Comment by eaarora-ms** [comment]
@SandraBosic  Can you please check if it has auto-swap enabled? and the workflow is configured to swap again?
Reference: https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#configure-auto-swap

**Comment by SandraBosic** [comment]
It is disabled. All settings are default.

**Comment by SandraBosic** [comment]
Also, in Advanced "Tools (Kudu) -> Deployment" logs: 
- for source slot there are one "Deployment" and two "Swap" operations logged.  
- for target(production) slot there are also one "Deployment" and tow "Swap" operations logged.

According to operation times it looks like the following happened:
(after first deployment)
- Deployment to source slot
- Slot swap
(after second deployment)
- Deployment to target(production) slot
- Slot swap

And the result on function app after this is: target slot empty, and source slot has functions. If logs are correct, the problem is that second time a deployment is run, functions are deployed to target instead of to source slot.

**Comment by 20shivangi** [comment]
@SandraBosic Please send us the debug logs by setting system variable sytem.debug to true in your pipeline.

**Comment by 20shivangi** [comment]
@SandraBosic Any update ?

**Comment by 20shivangi** [comment]
Closing it, feel free to reopen it if facing this issue and attach the debug logs also
