### ISSUE TITLE
Docker-Compose logging to variable

### ISSUE THREAD

**Issue by devedse** [microsoft/azure-pipelines-tasks#12579]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature/Question

**Enter Task Name**: Docker-Compose

list here (V# not needed):  0
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipeline
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
      N/A

- Agent - Hosted or Private: 
    Hosted agent
    - If using Hosted agent, provide agent queue name:
      N/A
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      N/A

## Issue Description

I'm trying to build a script that is able to cache images even on a Hosted Agent. Something similar to this:
https://github.com/marketplace/actions/build-docker-images-using-cache
and
https://testdriven.io/blog/faster-ci-builds-with-docker-cache/

However for this to nicely integrate into Azure DevOps I would like to be able to read out the created identifiers per stage.
This can be done quite easily by reading through the log file. E.g.:

![image](https://user-images.githubusercontent.com/2350015/77541494-0756a700-6ea5-11ea-8228-78530f1b7eec.png)

In the image above I want to get the Id so that I can execute a docker tag afterwards and tag this specific image as something like devemazegenerator-stages:0

So my main question would be, if it's possible to somehow storage all logging to a variable during a docker-compose build or docker build.

### Regarding directly targeting a stage instead

So in regards to directly targeting a stage instead, like for example calling:
```
docker build . --stage build
```

I first thought about using this, but the issue here is that you're basically doing a docker build twice. I would like to be able to kick-off docker-compose, have all variables / configuration setup there and then afterwards pick-up the stages that I want to push to the registry.

Next to that, it currently seems to be impossible to target an unnamed stage. See: https://forums.docker.com/t/docker-build-first-stage-in-multi-stage-pipeline/91167

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by devedse** [comment]
Dear @chshrikh , I saw you assigned @ajinkya599  on this. Is there already an update on this?

I've currently finished my implementation for Docker caching for Docker itself but would also like to include Docker Compose.

https://github.com/devedse/DeveDockerCaching

**Comment by devedse** [comment]
An update:

I implemented this myself in this PR: #12622

Can this be merged?

**Comment by ds-ms** [comment]
Can you not use the `arguments` input and pipe those logs to a file you desire?

**Comment by devedse** [comment]
Not sure, I didn't expect you could do that.  I'll try tomorrow. 

I still think this way is better and also follows the same flow as the DockerV2 task.

**Comment by devedse** [comment]
I'm still running into one issue when trying to store the log output to a file. For some reason the first line in the log is missing.

Expected log:

```
building coolimage.test
Step 1/20 blahblah
```

Actual log:

```
Step 1/20 blahblah
```

Does anyone have an idea on why this could be?

When I look at the log in VSTS I can see that the output is complete. But when I open the log file only this line is missing.

When I execute the build for a docker file with 2 items, I can see in the log in Azure DevOps that it states `Building ...` twice. But both of them are missing in the log I created form the STDOUT.

I'm really confused 😕

**Comment by devedse** [comment]
Another update, I just found out that apparently the lines `Building ....` are being written to STDERR. I've created a bug report for that:

https://github.com/docker/compose/issues/7346

**Comment by ds-ms** [comment]
>@ds-ms, how would you pipe the output to an environment variable that can be used in a follow up task? I've been reading through the documentation but what I've only found is this:

If you want to share the contents within a job, you could simply pipe the logs to a file. And use that file path in your scripts within the job.

I checked with @azooinmyluggage, I'll take your PR forward; it seems like a good addition. :)
