### ISSUE TITLE
Error: At least one project reference required to create an endpoint.

### ISSUE THREAD

**Issue by stephenmichaelf** [microsoft/azure-pipelines-tasks#12581]
Using Azure PowerShell 2.*, 3.*, or 4.* if I choose an `Azure Subscription` and try to Authorize, I get:

`Error: At least one project reference required to create an endpoint.`

![image](https://user-images.githubusercontent.com/450490/77595805-8f05db00-6ed0-11ea-9e44-cbae862f945e.png)

It looks like the issue was also raised [here](https://developercommunity.visualstudio.com/content/problem/954203/pipeline-create-release-subscription-authorize-err.html) and they were given a workaround but the issue was not fixed.

Can someone take a look? Thanks!

**Comment by stephenmichaelf** [comment]
@20shivangi Could you take a look at this?

**Comment by 20shivangi** [comment]
@stephenmichaelf Can you please tell me what pipeline are you using or can you give sample Yaml?

**Comment by stephenmichaelf** [comment]
@20shivangi 

![image](https://user-images.githubusercontent.com/450490/77639792-aaec9980-6f2f-11ea-946b-8c936f63f80c.png)

Currently, it doesn't work in the `Set Azure Firewall Rule` step but the bug appears to happen no matter where I add the task.

Are you able to recreate it?

**Comment by chshrikh** [comment]
@stephenmichaelf  thanks for details, @ankitk94 to check this issue

**Comment by iashishmittal** [comment]
@stephenmichaelf : can to try the scenario again after clearing the cache?

If you again face same issue then to unblock yourself, you can go to service connections hub and create required service connection for your azure subscription and use it in your release definition.
 
let me know if you face the same issue again and not able to unblock yourself.

**Comment by stephenmichaelf** [comment]
Clearing the cache worked, thanks!
