### ISSUE TITLE
UseDotNet task can't install nightlies

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/azure-pipelines-tasks#12590]
The UseDotNet task cannot install nightlies of .NET Core because they're not in the releases json. They are available via the blob endpoint by convention.

It required using the DotNetCoreInstaller@0 task for this to work. The v1 task also did not work.

This makes it quite hard for devs to try using the nightly SDK releases. Please add a fallback to the naming convention as in the original task.

**Comment by clairernovotny** [comment]
This is still needed.

**Comment by DamianEdwards** [comment]
Just want to add to @clairernovotny's voice here. This is needed and right now it's extremely difficult to discover how to achieve this.

**Comment by sandyarmstrong** [comment]
I'd also still like to have this.
