### ISSUE TITLE
Can't upload snupkg using NugetCommand

### ISSUE THREAD

**Issue by MariusVolkhart** [microsoft/azure-pipelines-tasks#12595]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NugetCommand  

## Environment
- Server - Azure Pipelines

https://dev.azure.com/MariusVolkhart/Nopen.NET/_build/results?buildId=71&view=results

## Issue Description

`snupkg` failes to publish due to an outdated version of nuget. From the logs: `Snupkg upload failed. Please use latest NuGet clients (v 4.9.0 or above) and a V3 endpoint to push Symbol packages`.

The build logs indicate: `Detected NuGet version 4.1.0.2450 / 4.1.0`

**Comment by MariusVolkhart** [comment]
Workaround: Upgrade the nuget version manually. It isn't intuitive, nor is it easy to find the separate task, but it exists. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops

**Comment by magleaso** [comment]
Yes, the NuGet Tool Installer is the recommended way to upgrade the NuGet version
