### ISSUE TITLE
Publish Test Results - link to "Published Test Run" broken by "." postfix

### ISSUE THREAD

**Issue by PaszkoKaminski** [microsoft/azure-pipelines-tasks#12603]
Bug,
In Task "Publish Test Results" Console output has link to test runs and it is ending with "." which is not part of link. This is causing link to fail and page is redirecting to "/_TestManagement/Runs?runId=3456076&_a=runQuery"

Starting: Publish test results
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.166.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
/usr/bin/dotnet --version
3.1.101
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
Async Command Start: Publish test results
Publishing test results to test run '3456076'.
TestResults To Publish 9, Test run id:3456076
Test results publishing 9, remaining: 0. Test run id: 3456076
Published Test Run : https://trolololo/_TestManagement/Runs?runId=3456076&_a=runCharts**.**
Async Command End: Publish test results
Finishing: Publish test results

**Comment by PaszkoKaminski** [comment]
It looks like it was fixed in 2.167.0
Thank you

**Comment by PaszkoKaminski** [comment]
I have just updated from 2.167.0 to 2.171.0 and this problem is back.
Again link:
"Published Test Run : https://dev.azure.com/msi-cie/*/_TestManagement/Runs?runId=6138888&_a=runCharts." and it had a '.' in the end. Link is not working correctly

**Comment by upadhyayap** [comment]
@PaszkoKaminski I see the "." is getting appended in the url but instead I can perfectly access the test run with exact same url from the log.

**Comment by Arwinder4** [comment]
@PaszkoKaminski can you please confirm whether it's fixed or not?

**Comment by PaszkoKaminski** [comment]
I have no control over the versions the system uses. Currently I'm still working on version 2.171.0
As soon as the administrator changes the version and I can check it, I will let you know.

**Comment by PaszkoKaminski** [comment]
OK. Version is still 2.171.0 but the problem is gone. I have two build to compare 
10 lis 2020 at 12:52 CET Have this problem 
10 lis 2020 at 21:08 CET Problem is gone. 
Version of task is not changed.
