### ISSUE TITLE
Unable to use /AccessToken with Azure Dacpac Deployment task anymore

### ISSUE THREAD

**Issue by scraver1** [microsoft/azure-pipelines-tasks#12607]
## Required Information

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1  

## Environment
- Server - Azure Pipelines    

- Agent - Hosted: 
    
    - vs2017-win2016

## Issue Description
My team has been testing out using the Azure Dacpac Deployoment task with /AccessToken: passed in as an "Additional SqlPackage.exe Argument" using a token grabbed via a previous Azure Powershell step in our release pipeline. Up through March 12, 2020 this worked fine, however today I picked this work back up after a few weeks of working on a different part of our deployment flow, and it no longer works. I don't see any changes to this task over this timeframe, and the only difference I can see is a minor bump in the Visual Studio version that is deployed to the vs2017-win2016 agents (was 15.9.28307.1033, is now 15.9.28307.1064, which was released on 3/10/2020). Was there a change in behavior with sqlpackage.exe between these two patch releases, or is there something else going on here?

**Comment by 20shivangi** [comment]
@scraver1 Please attach the successful and failure debug logs by setting system variable system.debug to true in your pipeline.

**Comment by 20shivangi** [comment]
@scraver1 Any update ?

**Comment by scraver1** [comment]
tasklog_10.log is the more or less successful run. It doesn't complete, because this is when we figured out we were going to need to scale our DB up to comlete the publish within the free tier timeout limit with MS hosted agents. The publish get's cut off by the system, but you can see it connect with the AccessToken and start the publish. In tasklog_12 it just fails trying to connect. Also, sorry for taking a bit to get back to you, this account is tied to my work email, which I don't generally check on the weekends.

[tasklog_10.log](https://github.com/microsoft/azure-pipelines-tasks/files/4438507/tasklog_10.log)
[tasklog_12.log](https://github.com/microsoft/azure-pipelines-tasks/files/4438572/tasklog_12.log)

**Comment by 20shivangi** [comment]
@scraver1 

Error message from the failure logs : 
```
*** A project which specifies SQL Server 2008 as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12.
```

You need to change the target platform for your DACPAC to `SQL Database v12`

**Comment by scraver1** [comment]
It's the exact same DACPAC I used in the successful run. If that's what's causing the problem, than the flag to allow incompatible platforms isn't working. But I still believe it's the token auth that's not working anymore, because that same error message is in the run that actually started the deploy but was timed out by the free tier time limit.

**Comment by scraver1** [comment]
Any updates?

**Comment by AmrutaKawade** [comment]
are you still facing issue?

**Comment by 20shivangi** [comment]
Closing this issue since there is no response from a long time.
Please feel free to re-open if you face some issue.

**Comment by scraver1** [comment]
After several months with no response to this, we found a different (much uglier and harder to maintain) way to handle this. So I have no idea if this is still an issue.

**Comment by scraver1** [comment]
Also, closing an issue after only a week with no response, when it's been open for over FOUR months, especially with a United States federal holiday yesterday, is a bit absurd.

**Comment by nadesu** [comment]
Hi @scraver1 - My apologies for not being able to revert on this issue for last few months. Pls reopen the issue if its still relevant and reproducible, we will prioritise to troubleshoot/fix it.
