### ISSUE TITLE
How to store secrets in Azure Key Vault if the app settings name to transform contains periods

### ISSUE THREAD

**Issue by saciervo** [microsoft/azure-pipelines-tasks#12601]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**AzureKeyVault, FileTransform**

## Environment
Azure Pipelines

## Issue Description

I want to JSON transform the appsettings,json inside the pipeline with an Azure KeyVault secret. I already found out that for colons ":" you have to use double dashes "--" in the secret name. But I can't figure out what to use for periods "." because periods are also not allowed for secrets.

The problem applies for FileTransform task and also for the AzureRmWebAppDeployment task.

![image](https://user-images.githubusercontent.com/707898/77886432-22d8fd80-7269-11ea-9ce5-e759708a813f.png)

**Comment by 20shivangi** [comment]
@prativen the customer wants to store a secret in azure key vault to be used in file transform but does not know in which format to store it if the secret contains a '.' character. Can you please guide him?

**Comment by saciervo** [comment]
Hi @prativen 

After looking through [the FileTransform docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic) it seems that it the task itself does support configuration names containing '.' characters.

> If a variable name includes periods ("."), the transformation will attempt to locate the item within the hierarchy

So I ended up saving the secret value into a variable as a workaround

`
##vso[task.setvariable variable=OrchardCore.OrchardCore.Media.Azure.ConnectionString]$(KeyVaultSecretValue)"`

For the moment this works for me, but I would love to see some options to do this in one step. I also found [this interesting class](https://github.com/aspnet/Configuration/blob/master/src/Config.AzureKeyVault/DefaultKeyVaultSecretManager.cs), so at least in C# you could replace this implementation with one's own logic.

**Comment by 20shivangi** [comment]
@saciervo Is your problem solved now, can we close it ?

**Comment by 20shivangi** [comment]
Closing this one, feel free to reopen if face any issue

**Comment by saciervo** [comment]
@20shivangi Well, the problem persists... Variable names with "." are not supported in FileTransform if they come from AzureKeyVault. It's just not urgent for us anymore because of the said workaround.

To really solve it, I'd suggest the following change to the AzureKeyVault task:
As already noted, the AzureKeyVault task today converts "--" to ":". It does this to be able to use it afterwards in the FileTransform task to traverse down the config hierarchy. Instead, it actually should convert "--" to "." and then save the value as a pipeline variable. Since FileTransform reads the variables and supports both ":" and "." to traverse down, the problem would be solved.
