### ISSUE TITLE
AzurePowershell@4 truncating error message

### ISSUE THREAD

**Issue by haripraghash** [microsoft/azure-pipelines-tasks#12619]
*Type*: Bug

**Enter Task Name**: AzurePowershell@4

- Server - Azure Pipelines 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Account Name - haripraghash
Project name - securityanalysis

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name:
ubuntu-latest

## Issue Description
AzurePowershellTask@4 is truncating error logs. It becomes difficult to understand what the issue is
[log1.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4425567/log1.txt)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by 20shivangi** [comment]
@haripraghash Is the same thing happening on private agent when running the task on windows instead of ubuntu ?

**Comment by haripraghash** [comment]
> @haripraghash Is the same thing happening on private agent when running the task on windows instead of ubuntu ?

I have not tried it in a private agent pool as I have not stood up one

**Comment by 20shivangi** [comment]
@haripraghash This error can't come in hosted agent as modules are already presented in it. Can you have some private agent on windows and check again as I am unable to repro the issue.

**Comment by 20shivangi** [comment]
@haripraghash I tried the scenario in hosted ubuntu agent and the complete error is shown in the red line.

**Comment by 20shivangi** [comment]
Closing it, please feel free to reopen if you have any other query
