### ISSUE TITLE
Azure Blob File copy fails to upload to $web container

### ISSUE THREAD

**Issue by chandanch** [microsoft/azure-pipelines-tasks#12618]
AzCopy Job fails to upload files to container with name $web. Below are the details:
![image](https://user-images.githubusercontent.com/8663552/78332833-63f14a80-75a6-11ea-8a0f-16b2ce1887e5.png)

**Error Log:**

![image](https://user-images.githubusercontent.com/8663552/78332872-723f6680-75a6-11ea-9594-5a44ce600362.png)

**Comment by 20shivangi** [comment]
@chandanch Have you given required permissions i.e. storage blob contributor/ storage blob owner to your SPN ?
Please check this doc once : https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#option-1-use-azure-active-directory

**Comment by 20shivangi** [comment]
@chandanch Any update here?

**Comment by 20shivangi** [comment]
Closing it, please feel free to reopen if you have any other query
