### ISSUE TITLE
kubectl kustomize

### ISSUE THREAD

**Issue by bitva77** [microsoft/azure-pipelines-tasks#12616]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: kubectl

## Environment
- Server - Azure Pipelines
       
- Agent - Both
    
## Issue Description

`kubectl kustomize` is not supported.  While you can try to use it, the kubectl task adds a `-o` parameter for output (either json or yaml) and this is not compatible with `kubectl kustomize`

It would be great to have output of `kubectl kustomize` prior to running something like `kubectl apply -k`

**Comment by ds-ms** [comment]
The Kubernetes task takes an advanced input called `Output Format`, which you can find in the `Advanced` section.
![image](https://user-images.githubusercontent.com/25762922/78814908-184b0080-79ed-11ea-9bf2-1dde2b70b207.png)

It defaults to `json`, but if you set it to an empty string. The `-o` doesn't get appended. Which should work in your case.
