### ISSUE TITLE
The "File Transformation Task" needs to be renamed to include "And Pipeline Variable Substitution"

### ISSUE THREAD

**Issue by StingyJack** [microsoft/azure-pipelines-tasks#12624]
I just spent several hours of time trying to figure out how the resulting deployed web.config file for an application is getting a value for a connection string that is not specified in the web.config, the web.<thatenvironment>.config, or any other file in the project. 

It was only after copying the build definition json to a text editor and searching did I find that there was a pipeline variable that was the potential source, but it took a while longer (more reading) to realize that while the "File Transformation Task" does perform that intended service, it does something else - replaces content in those files with pipeline variables. 

* The naming for the task is misleading in one of the worst ways - an unrelated or nonsense name that does not describe the functionality of the task would be a safer choice than the one it has now that very specifically describes only half of the total functionality (and you cant even opt out of the unsaid half)
* The documentation is slightly misleading as it does not mention that the variables its discussing are pipeline variables until a teeny little blue "Note" after the examples.  
* The log messages that are emitted reinforce that like its name implies, this task is yet another XDT task. It doesnt state what variables its using or what values, or that its even using pipeline variables and not environment or other variables.

**Comment by eaarora-ms** [comment]
@StingyJack  Most of the points you've highlighted are mentioned in the doc here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic

However, we will keep your suggestion in mind. Thankyou for your contribution.

**Comment by StingyJack** [comment]
@github-actions - please have your configurer use a stale age that is longer than the time it takes to add new features from customer requests. AFAIK that takes _years_

**Comment by StingyJack** [comment]
naming things like this properly is not hard

**Comment by StingyJack** [comment]
necrobump
