### ISSUE TITLE
Repository Build Pipelines - Why it's needed to test using Node 6?

### ISSUE THREAD

**Issue by dedreira** [microsoft/azure-pipelines-tasks#12629]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: All

list here (V# not needed):  
****

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
I'm seeing all this repository builds (Build & Test on Windows, MacOS and Linux) fail in the step "Test with Node 6"

Anyone know why it's needed to run the tests with that version of Node?.

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment]
Hey @dedreria we test with Node 6 because that's what our build agents are running. We've considered doing some work to upgrade to Node 12, but there are some incompatibilities between the versions that would make that a breaking change so we've put a hold on that for now.

**Comment by dedreira** [comment]
Ok @damccorm  thanks for the quick answer!
