### ISSUE TITLE
Azure Datawarehouse Dacpac deploy fails on drop column with statistics 

### ISSUE THREAD

**Issue by sachenko-igor** [microsoft/azure-pipelines-tasks#12633]
Azure Datawarehouse Dacpac deploy fails on drop column with statistics 

ALTER TABLE [table] DROP COLUMN [column] 

Error: The statistics 'Stat_00dd6142d62642978298220397379ee1' is dependent on column 'column'.
ALTER TABLE DROP COLUMN column failed because one or more objects access this column.

Bug
Azure Data Warehouse

**Comment by 20shivangi** [comment]
The issue has been raised here: https://msdata.visualstudio.com/Azure%20SQL%20Data%20Warehouse/_workitems/edit/712297

Thereby, closing this one.

**Comment by ranouran** [comment]
I looked at this and it is working as expected, if the statistics is auto generated it won't stop dropping the column and if it's user created the statistics also lives in the project so you need to remove the column and statistics from the project before publishing it.

@sachenko-igor please let me know if you are doing something different.

**Comment by sachenko-igor** [comment]
Hi

Yes, I did the same

Issue is related to auto-generated statistics.



ср, 22 апр. 2020 г. в 01:58, Rashad Nourani <notifications@github.com>:

**Comment by ranouran** [comment]
@sachenko-igor this seems more like an issue on your instance, please open a support ticket for this issue.

**Comment by PeterDowdy** [comment]
This is happening to me, too.
