### ISSUE TITLE
visibleRule should support c# or javascript like expressions

### ISSUE THREAD

**Issue by cveld** [microsoft/azure-pipelines-tasks#12649]
When defining task input parameters in a task.json file, one can specify when an input parameter should be visible through the `visibleRule` property. 

Currently you can only do so much with it. It does not support parentheses and it does not support a mix of `&&` and `||' operators.

Ideally one would be able to write something like:
`Action = New || (Action = Update && UpdateAccessTier = true)`

Now we are forced to split the input parameter into two input parameters.

**Comment by Automobileservices4** [comment]
#12649

**Comment by damccorm** [comment]
Hi, this looks like an issue with the service, not with one of the tasks in this repo. Please file this at https://developercommunity.visualstudio.com/spaces/21/index.html
