### ISSUE TITLE
[DockerV2] Build task - tagging for multiple private repositories

### ISSUE THREAD

**Issue by eegeeZA** [microsoft/azure-pipelines-tasks#12642]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Docker

## Environment

Azure Pipelines

## Issue Description

The `build` command does not allow specifying a fully-qualified name for a tag. The referenced code always concatenates the image name with the provided tag.

https://github.com/microsoft/azure-pipelines-tasks/blob/24c7840dfe47ecef918971406749123d41b7aa2d/Tasks/DockerV2/dockerbuild.ts#L52

In order to create tags for multiple private repositories, I can think of the following solutions:
* Allow multiple combinations of (`containerRegistry`+`repository`) combos.
* If the list of tag names contains a colon (`:`) then use the name as is. This allows extra qualified tags but means having the registry name in outside the service connection.
* _(my current workaround)_ Running an extra `build` command with the exact same parameters and relying on Docker's cache to create the same image with a new name.
* Adding a standalone `tag` command with a private registry input and a private registry output.

**Comment by eegeeZA** [comment]
I stumbled on a new workaround that mostly solves my issue.
Caveat: the `repository` and _all_ the `tags` must be the same for both registries.

Steps:
1. `login` to the first ACR
1. `login` to the second ACR
1. `build` with arguments and remember to include all tags (exclude `containerRegistry`)
1. `push` with the same tags specified in `build` (exclude `containerRegistry`)

**Comment by ds-ms** [comment]
cc: @ganeshrockz to take a look

**Comment by Ganeshrockz** [comment]
@eegeeZA  The current behaviour is by design that we had and we dont intend to change it in the near future.You can add the different tag/repo combinations with the docker tag command in the subsequent steps.For different registries you can use multiple logins like you have suggested as a workaround.
