### ISSUE TITLE
NuGet restore - Unexpected token =

### ISSUE THREAD

**Issue by setzuiro** [microsoft/azure-pipelines-tasks#12648]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGet restore - Unexpected token =

## Environment
- Server - Azure Pipelines
    I'm not exactly sure, but I think this is Azure Pipelines
    - Account Name: Agility PR Solutions
    - Team Project Name: agilitypr
    - Build Number: 10416
 
- Agent - Hosted or Private: 
    The build definition's agent pool suggests that it's using a private agent.
    - Agent: Private
    - Agent OS: Windows_NT
    - Agent OS Version: 10.0.14393
    - Agent Version: 2.115.0

## Issue Description

It would appear that any changesets we check-in, fails at the nuget restore step with the error "##[error]Unhandled: Unexpected token ="
![image](https://user-images.githubusercontent.com/3298564/78700203-19880a80-78d3-11ea-90fd-6b0142f112d4.png)

Checks-in were successful previous day and no configuration changes were applied.

### Task logs
I've enabled the "system.debug" = true; I think these are the logs.
[nuget_restore_task_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4446357/nuget_restore_task_log.txt)

### Error logs

[nuget_restore_pipeline_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4446133/nuget_restore_pipeline_log.txt)

EDIT 1: added task logs with "system.dbug" enabled.
EDIT 2: updated agent details; discovered pipes were using default (private) agent pool, not Azure Pipelines.

**Comment by apluche** [comment]
@setzuiro, could you set the environment variable "system.debug" = true, run the pipeline again and send the more detailed log? This will allow us to more accurately debug the issue.

A possible way to unblock you would be to add the Nuget Tool Installer Task in your pipeline before the Nuget Command task. Here is a link to the docs for the task: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops . 

Please let me know if this workaround works for you. More detailed logs of the failure would be much appreciated.

**Comment by setzuiro** [comment]
@apluche, thanks for the suggestion. I've enabled the system.debug and added the logs to the original post. Let me know if additional logs are required.

I've added the Nuget Tool Installer Task to my pipeline before my NuGet Restore task but I unfortunately still get the same error.

**Comment by apluche** [comment]
Thanks for the quick turnaround and the logs.
Are you using the VS 2019 hosted agent?

**Comment by setzuiro** [comment]
@apluche Thanks for the quick responses, really appreciate it.
I realized that the pipeline builds were configured to use what appears to be private agents; so I've update the original post. Apologies for the misinformation and lack of better understanding on the matter.

1. According to the System capabilities of the agent pool, these are the configurations; appears to be VS 2015? We're using VS 2017 to push the check-in through TFS.
![image](https://user-images.githubusercontent.com/3298564/78710164-dc2b7900-78e2-11ea-934b-b8fb6821a8f2.png)
2. First occurrence of task failing started at approx 2:39 p.m UTC today.

I'll investigate and try to figure out how to apply your suggestion for the nuget authenticate task.

Thanks

**Comment by apluche** [comment]
Hi @setzuiro,

1. Those agents are VS 2015 agents. You can update the agents to VS 2019 agents using the upgrade agents button in Project Settings -> Agent Pools panel. This may fix the original issue as it sounds like a script incompatability.
2. We pushed out a new version of the task this morning and the version in the logs indicates that you are using the new version. 

Please let me know if updating the agents or using the nuget authenticate task unblocks you!

**Comment by setzuiro** [comment]
Hi @apluche,

Thanks so much for the continued efforts. I have added the Nuget Authenticate task to run before the Nuget Restore and that has indeed unblocked us for the time being.

Unfortunately, when we try to update the agents, we can see a successful request being made in the network panel, but there's no feedback otherwise and the agents aren't updated.

We'll proceed with the nuget authentiate task as a workaround for the time being, but I think it'd be better to update the agents too.

Please advise, and thank you very much!

**Comment by apluche** [comment]
Hi @setzuiro ,

Please look at this documentation to see how to update the agents: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#agent-version-and-upgrades .

Additionally, the Nuget Authenticate task is meant to be used without then using the nuget restore task. You can run a script and invoke nuget directly once you have run the Authenticate task.

Based on this, you can take out the Nuget Authenticate task and try again. We have been releasing new versions of the task in response to a livesite issue - which is likely to have fixed your issue.

Please let me know if you are unblocked.

**Comment by setzuiro** [comment]
Hi @apluche,

Thanks for your continued efforts.
As you suggested, I have removed the Nuget Authenticate task and retried with success.

The tasks are now working in their original states again and we have been unblocked.
Thanks again, appreciated the assistance and quick turn around.

I'll close the issue now.
