### ISSUE TITLE
stdout/err does not appear for custom npm scripts that time out

### ISSUE THREAD

**Issue by connor4312** [microsoft/azure-pipelines-tasks#12650]
#  Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: *Bug*

**Enter Task Name**: Npm

## Environment

All 

## Issue Description

Long running custom npm tasks that time out omit any stdio. For [example](https://dev.azure.com/vscode/VS%20Code%20debug%20adapters/_build/results?buildId=40533&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b7b7a6e6-b49b-50ea-fca3-f91483add993))

```
- task: Npm@1
  displayName: npm test
  inputs:
    command: custom
    verbose: false
    customCommand: test
  timeoutInMinutes: 15
```

Just glacing at the code, this may be because it gets invoked like so

https://github.com/microsoft/azure-pipelines-tasks/blob/5d72a51fbb03c190167bb8e9d02ddc4461d316ba/Tasks/NpmV1/npmcustom.ts#L29

Which calls through to

https://github.com/microsoft/azure-pipelines-task-lib/blob/62c92b5236c900500752862a13378ae3deac84e5/node/toolrunner.ts#L893-L902

This appears to cause tasks that timeout not to show any stdio, which makes debugging difficult. I don't think it's safe to assume that npm scripts are short-running and suitable for execSync.

### Task logs

https://dev.azure.com/vscode/VS%20Code%20debug%20adapters/_build/results?buildId=40538&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b7b7a6e6-b49b-50ea-fca3-f91483add993

**Comment by apluche** [comment]
Hi @connor4312,

The logging occurring all at once is a known bug in the task - the printing synchronously is expected. We realize that this is not a pleasant experience - there are issues with printing the logs asynchronously which has lead to the task behaving the way it does. 

We have a new task that will be more useful for you. Please consider moving to the npm authenticate task (docs here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops).  The task will do the authentication for you and you will subsequently be able to run npm directly.

Please let me know if this helps with your issue or if you have any questions or concerns.

**Comment by connor4312** [comment]
Yea I worked around this by using the `CmdLine`. If it's a known bug, maybe there could be documentation for that somewhere? Or is there a way to have the npm task dump its buffered stdio when a timeout happens? I spent quite a while thinking it was some bug in Azure Pipelines itself and doing research before checking the source code of the npm task and finding this.

**Comment by apluche** [comment]
Hi @connor4312 ,

I took a look at our documentation and I didn't see anything anywhere about this bug being documented (other than old github issues). I will file a bug to have the documentation updated although I do not know where the best place would be. I'll ping our PM so we can figure out where the best place to put that would be. 

As far as I know, there isn't a way to get the task to dump the stdio when a timeout happens. I can file a bug for this but unfortunately, it isn't likely to get picked up any time soon.

**Comment by connor4312** [comment]
Okay, thanks!
