### ISSUE TITLE
Nuget Tool Installer version 0.167.4 is failing

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-tasks#12654]
## Required Information

Nuget Tool Installer version 0.167.4 is failing with message **ERR:Invalid Version: null**

**Bug**  
*Type*: Unexpected error

**Enter Task Name**: Nuget Tool Installer

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NuGetToolInstallerV0

## Environment
- Server - Azure Pipelines
- I can provide the account name, team project name, build definition name/build number in a private message
- Agent is private running on Windows Server 1803 Server Core with Agent 2.159.2

## Issue Description

Nuget Tool Installer 0.167.4 started failing inexplicably after it was updated to 0.167.4. Previous builds using version 0.165.0 worked just fine as of 13 hours ago.

## Troubleshooting

Switched to Nuget Tool Installer 1.167.4 and updated nuget version being installed from 4.7.1 to 5.5.1 and our builds no longer receive this error even though both v0 and v1 have the same change from [pull request 12635](https://github.com/microsoft/azure-pipelines-tasks/pull/12635) 20 hrs ago.

![image](https://user-images.githubusercontent.com/5810165/78734154-7c9a9100-7915-11ea-8965-231752e5d61a.png)

**Comment by chris-cubhub** [comment]
0.167.3 was also working as of 3 hours ago. We're getting the same error and builds are failing.

**Comment by Enoch-Ye** [comment]
We are also facing the same issue, is there any way that we could mitigate this?

**Comment by chris-cubhub** [comment]
Possible solution here. Looks like Nuget 4.4.1 is no longer supported for that pipeline task. The files changed in the pull request indicate 5.4.0. I updated my step include the latest 5.4.0 and my build is proceeding.

![image](https://user-images.githubusercontent.com/51138279/78737755-eb77ea00-7915-11ea-8ed3-42260b764898.png)

![image](https://user-images.githubusercontent.com/51138279/78737808-0d716c80-7916-11ea-9da7-f728c906b62b.png)

![image](https://user-images.githubusercontent.com/51138279/78737925-4b6e9080-7916-11ea-852c-c99cf010ae22.png)

**Comment by johnterickson** [comment]
https://status.dev.azure.com/_event/183168284

**Comment by faldeland** [comment]
I had same issue. Modified pipeline to use NuGet 5.5.1 and it seems to be working.

**Comment by johnterickson** [comment]
This should be resolved with 0.167.5.
