### ISSUE TITLE
Test task doesn't seem to find all tests

### ISSUE THREAD

**Issue by chriswill** [microsoft/azure-pipelines-tasks#12663]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines
Account name: gainesolutions
Team project name: MDX
Build definition: ODS-Next

- Agent - Hosted    

## Issue Description

This is regarding the Test task step for a net core test process.  We are using a yaml build and our filespec is set to 

```
"projects: '**/*tests/*.csproj'"
```

There are 4 projects that I believe would match this filespec, but only 2 are run during the test step.

Under debug, task finds:

```
##[debug]  d:\a\1\s\tests\ODS.Common.Test\ODS.Common.Test.csproj (file)
##[debug]  d:\a\1\s\tests\Ods.Data.Tests\Ods.Data.Tests.csproj (file)
##[debug]  d:\a\1\s\tests\ODS.Service.Test\ODS.Service.Test.csproj (file)
##[debug]  d:\a\1\s\tests\OdsCoreTests\Ods.Core.Tests.csproj (file)

##[debug]applying include pattern
##[debug]adjustedPattern: 'd:\a\1\s\**/*tests/*.csproj'
##[debug]2 matches
##[debug]2 final results
```

Task ends up executing:
```
##[debug]C:\Program Files\dotnet\dotnet.exe arg: d:\a\1\s\tests\Ods.Data.Tests\Ods.Data.Tests.csproj

##[debug]C:\Program Files\dotnet\dotnet.exe arg: d:\a\1\s\tests\OdsCoreTests\Ods.Core.Tests.csproj
```
Task can't find:
```
##[debug]  d:\a\1\s\tests\ODS.Service.Test\ODS.Service.Test.csproj (file)
##[debug]  d:\a\1\s\tests\ODS.Common.Test\ODS.Common.Test.csproj (file)
```
### Task logs

Available at https://gainestorage.blob.core.windows.net/public/log_10_9011.zip

**Comment by bishal-pdMSFT** [comment]
That is because you are specifying `*tests` in pattern but two csproj contain just `test.` substring

**Comment by chriswill** [comment]
Thanks @bishal-pdMSFT
