### ISSUE TITLE
Private Azure DevOps agent on Windows 

### ISSUE THREAD

**Issue by catalinad90** [microsoft/azure-pipelines-tasks#12669]
I have private agents installed on Azure VMs from WEU region. These were running fine last week, but this week the builds are failing when performing the checkout from TFVC repository. The error generated with debugger can be found below. 

Private agent version: 2.165.2
Windows OS version: Windows Server 2016

### Error logs
Without debugger:
tf vc get /version:18704 /recursive /overwrite T:\_work_build\1\s /loginType:OAuth /login:.,*** /noprompt
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc get /version:18704 /recursive /overwrite T:\_work_build\1\s /loginType:OAuth /login:.,*** /noprompt'.

With debugger:
##[debug]STDOUT/STDERR stream read finished.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Exited process 8668 with exit code 1
##[debug]Finished process 8668 with exit code 1, and elapsed time 00:29:09.6566921.
##[error]Exit code 1 returned from process: file name 'tf', arguments 'vc get /version:18704 /recursive /overwrite T:\_work_build\1\s /loginType:OAuth /login:.,*** /noprompt'.
##[debug]Processed: ##vso[task.logissue type=error;]Exit code 1 returned from process: file name 'tf', arguments 'vc get /version:18704 /recursive /overwrite T:\_work_build\1\s /loginType:OAuth /login:.,*** /noprompt'.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.TfsVCCliManager.RunCommandAsync(FormatFlags formatFlags, Boolean quiet, String[] args)
   at Agent.Plugins.Repository.TFCliManager.GetAsync(String localPath, Boolean quiet)
   at Agent.Plugins.Repository.TfsVCSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)

Also, I have another agent installed on a different Azure VM, but on a different region SEA. This one works fine without any issues.

Thank you,
Catalina

**Comment by catalinad90** [comment]
Also, want to mention that the agents run as a service and that I tried reinstalling the agents, restarting the agents, but nothing helped.

**Comment by damccorm** [comment]
Hi, this looks like an issue with the agent, not a task. Would you mind filing it at https://github.com/microsoft/azure-pipelines-agent/issues
