### ISSUE TITLE
PublishTestResults@2 also publishes the VS coverage hyperlink, making it impossible to publish Cobertura report with PublishCodeCoverageResults@1 task. 

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#12670]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults@2 and/or PublishCodeCoverageResults@1

 - https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1
 - https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishTestResultsV2

## Environment
- Server - **TFS on-premises**
    
    - If using TFS on-premises, provide the version: **Dev17.M153.3**

- Agent - **Private**

 name | value
   -- | --
 Agent.Version | 2.153.1
 Agent.OS | Windows_NT
 Agent.OSArchitecture | X64
 Agent.OSVersion | 10.0.14393

## Issue Description

When running DotNetCoreCLI@2 with the **test** command and **--collect "Code coverage"** the VS coverage binary report is generated. I then convert it to Cobertura report and publish it using the guidelines in https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#collect-code-coverage, i.e. I do the following steps:

1. Convert the binary VS coverage report to XML
1. Install reportgenerator tool
1. Run reportgenerator tool to convert the XML VS coverage result to Cobertura report
1. Publish the test results (PublishTestResults@2)
1. Publish the Cobertura coverage result (PublishCodeCoverageResults@1)

However, the Code Coverage page only shows the hyperlink to the VS binary coverage file, which is completely useless to us.

### Task logs

[logs_754278.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4457807/logs_754278.zip)

### Snapshots
This is what we get:
![image](https://user-images.githubusercontent.com/489792/79000910-81309680-7b1b-11ea-972b-c7e96de604a6.png)
We find it useless. Disabling the Publish Test Results task yields the correct coverage page:
![image](https://user-images.githubusercontent.com/489792/79001667-e5a02580-7b1c-11ea-8af5-88ba12e71e09.png)
But, of course, the Tests page is now empty:
![image](https://user-images.githubusercontent.com/489792/79001721-fbade600-7b1c-11ea-9edc-4f757ad5294a.png)

**Comment by MarkKharitonov** [comment]
I found the workaround, please see my answer to https://stackoverflow.com/questions/61143454/how-to-publish-cobertura-coverage-report-from-the-vs-coverage-produced-by-dotnet

**Comment by singhsarab** [comment]
@MarkKharitonov This seems by design for now. We are working on the new experience.
Thanks for sharing the workaround.
