### ISSUE TITLE
Change location of an upload summary

### ISSUE THREAD

**Issue by huntantr** [microsoft/azure-pipelines-tasks#12684]
## Required Information
*Type*: Question

**Enter Task Name**: task.uploadsummary

## Environment
- Server - TFS2018.3.2 Patch 9

- Agent - Private: 
    Windows 2016
    Agent Version: 2.136.1

## Issue Description

Is it possible to control the location of where the uploaded summary appears in the build summary? Currently it shows up below the under the "Work items linked to associated changes" section. Would be better if this could show up above the "Test Results" section in the second column. It would make it more visible to users.

**Comment by damccorm** [comment]
Hey @huntantr this looks like a general ui question and not a question about a specific task - please open this at https://developercommunity.visualstudio.com/spaces/21/index.html so it gets routed to the right place
