### ISSUE TITLE
DownloadPipelineArtifact@2.3 breaks builds on pool

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/azure-pipelines-tasks#12681]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DownloadPipelineArtifact  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadPipelineArtifact

## Environment
- Server - Azure Pipelines, DevDiv, Concord, Build and Publish VsDbg or VsDbg-UI Build 12348

- Agent - Private on macOS with agent 2.161.0
## Issue Description
Version 2.3 of DownloadPipelineArtifact broke our builds since we need to build with agent 2.161.0.   and we can not update our pool. 

**Is there a way to specify DownloadPipelineArtifact Version 2.2?**

### Error logs

The pool doesn't allow agent updates. Agent version 2.164.1 is required and no agents with that version are registered. An administrator can alter this by visiting the pool's Settings page at the organization level.

**Comment by fadnavistanmay** [comment]
Hi @WardenGnaw - Could you ask the administrator to upgrade the agent version. If not, you can move to V1, but not to V2.2 iirc.

**Comment by WardenGnaw** [comment]
Unfortunately we can not upgrade the agent version. We will use the V1 workaround for now. 

Can there be a way to specify `2.2`? If specified at `@2` use the latest minor + patch version, if specified `@2.2` then use the highest patch version. 

This may be an issue for the [pipeline agent](https://github.com/microsoft/azure-pipelines-agent) since `TaskAgentHttpClient.GetTaskContentZipAsync(Guid, TaskVersion, Object, CancellationToken)` can take a TaskVersion which could specify Major/Minor/Patch.

**Comment by fadnavistanmay** [comment]
Tagging @stephenmichaelf and @damccorm . Guys, is there a way to specify a patch version to run a task?

**Comment by damccorm** [comment]
There's not, we only support pinning to major versions - if you absolutely need this you can upload your own version of the task using the [tfx-cli](https://www.npmjs.com/package/tfx-cli)

**Comment by WardenGnaw** [comment]
We will use V1 for now.
