### ISSUE TITLE
No option to change the api-version inside Pre-deployment gates for Query Azure Monitor alerts.

### ISSUE THREAD

**Issue by ksingh3** [microsoft/azure-pipelines-tasks#12683]
*Type*: Bug

## Environment
- Server - Azure Pipelines  
    
    Account: conduent-lcs
    Project: Invoice_Analytics
    Release pipeline: Monitoring Release

- Agent - Hosted  

## Issue Description
Query Azure Monitor alerts gate is using the api version 2018-05-05, Please add an option to accept api-version parameter as input inside pre-deployment gate(Query Azure Monitor alerts) .

I was trying to use a pre-deployment gate(Query Azure Monitor alerts) in release pipeline. Also I am trying to fetch the alerts since last 30d, but the api version 2018-05-05 is not populating the result. But if I have the api version to 2019-03-01 all alerts are shown.

### Step to get the api version 2019-03-01.
Page: https://docs.microsoft.com/en-us/rest/api/monitor/alertsmanagement/alerts/getall 
only mentions the available version is 2018-05-05. But If I click on  Try It with wrong api-version.
I got all the available Api versions.

![image](https://user-images.githubusercontent.com/29065474/79222040-7a37ba00-7e74-11ea-8681-f8662495e415.png)

Following are the versions available.  
```
"{\"error\":{\"code\":\"InvalidResourceType\",\"message\":\"The resource type 'alerts' could not be found in the namespace 'Microsoft.AlertsManagement' for api version '2019-03-02'. The supported api-versions are '2017-11-15-privatepreview,2018-05-05-preview,2018-05-05,2018-11-02-privatepreview,2019-03-01-preview,2019-03-01,2019-05-05-preview'.\"}}"
```

### Following api manual hit responded with results (api-version=2019-03-01) 
https://management.azure.com//subscriptions/XXXXXXX/providers/Microsoft.AlertsManagement/alerts?api-version=2019-03-01&targetResourceGroup=xxxxxxx-eastus2&monitorCondition=Fired,Resolved&timeRange=30d&alertState=Acknowledged,New&severity=Sev0,Sev1,Sev2,Sev3,Sev4

### Task logs  
No results for api-version=2018-05-05 
```
Task         : Query Azure Monitor alerts
Description  : Observe the configured Azure Monitor rules for active alerts
Version      : 1.157.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-monitor
2020-04-14T11:13:52.6332244Z GET https://management.azure.com//subscriptions/xxxxxxxxx/providers/Microsoft.AlertsManagement/alerts?api-version=2018-05-05&targetResourceGroup=xxxxxx-eastus2&monitorCondition=Fired,Resolved&timeRange=30d&alertState=Acknowledged,New&severity=Sev0,Sev1,Sev2,Sev3,Sev4
				Response Code: OK
				Response: {"value":[]}
```

**Comment by ksingh3** [comment]
Hi,  Request you to please update if this is being worked on.

**Comment by ksingh3** [comment]
@chshrikh, @Vijay-train  Request you to update that it is being looked into ?

**Comment by eaarora-ms** [comment]
@ds-ms  @vithati  Could you please look into this issue? Thanks.

**Comment by ds-ms** [comment]
@ksingh3 did you try to use `v1` version of the gate to do it?

**Comment by ksingh3** [comment]
Yes, I ran this with both the versions 0 and 1.

**Comment by ksingh3** [comment]
Any Updates?

**Comment by ksingh3** [comment]
@eaarora-ms Any updates please?
