### ISSUE TITLE
With a TFS on-prem shared deployment group, web apps are being overwritten, how can one best debug this?

### ISSUE THREAD

**Issue by dhazel** [microsoft/azure-pipelines-tasks#12686]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: [IISWebAppDeploymentOnMachineGroupV0](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/IISWebAppDeploymentOnMachineGroupV0)  

## Environment
- Server - TFS on-premises
    
    - Version: 2018.2

- Agent - Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
        - Agent version: `2.131.0`
        - Machine OS: Windows Server 2012 R2 Standard

### The Context

I have an [on-prem TFS (Azure DevOps) server (version 2018.2)](https://docs.microsoft.com/en-us/azure/devops/user-guide/provide-feedback?view=azure-devops#azure-devops-server) with a single [deployment agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops#deploy-agents-to-a-deployment-group) installed.

This agent is in a [shared deployment group](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops#share-a-deployment-group) and is used to deploy multiple IIS web applications, each application residing in its own project and release pipeline.

The release pipelines all use an identical flow, running the [IIS Web App Deployment](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/IISWebAppDeploymentOnMachineGroupV0/README.md) module to deploy each application.

In the [deployment parameters](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/IISWebAppDeploymentOnMachineGroupV0/README.md#parameters-of-the-task) each application has its own, unique `virtual application` specified.

### The Problem

When one application is deployed, it correctly deploys to its unique virtual application, *but* all other virtual applications that the agent is configured to deploy *even in other release pipelines* get overwritten by the one application.

### What I have tried

1. Verified that each `virtual application` parameter is, in fact, unique in the configs
2. Verified that the release deployment logs for any given deployment do not mention any *extra* deployment paths. This is particularly perplexing, because the logs *say* that the operation correctly deploys to *only one* virtual application.
3. Check for any strange IIS logs on the target server

### The Question

What are the best next steps for debugging an Azure DevOps issue like this? This is an *on-prem* server, so I have a higher level of access than if this were cloud hosted.

I am thinking perhaps:

1. Check the agent version and update it to latest?
2. Could there be *other* logs with valuable info? On the target server? On the DevOps server?

### Task logs

```
2020-04-14T19:52:59.1856587Z ##[section]Starting: IIS Web App Deploy
2020-04-14T19:52:59.1860865Z ==============================================================================
2020-04-14T19:52:59.1861069Z Task         : IIS Web App Deploy
2020-04-14T19:52:59.1861232Z Description  : Deploy a Website or Web Application using WebDeploy
2020-04-14T19:52:59.1861507Z Version      : 0.0.35
2020-04-14T19:52:59.1861651Z Author       : Microsoft Corporation
2020-04-14T19:52:59.1861819Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=866789)
2020-04-14T19:52:59.1862014Z ==============================================================================
2020-04-14T19:53:00.0063184Z [command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='C:\vstsagent\A1\_work\r1\a\Draft Forms-ASP.NET Core-CI\drop\Development\DraftForms.External.Ui.zip' -dest:contentPath='Default Web Site/Dev/DOR/External/DraftForms'
2020-04-14T19:53:00.9870109Z Total changes: 0 (0 added, 0 deleted, 0 updated, 0 parameters changed, 0 bytes copied)
2020-04-14T19:53:01.0147329Z ##[section]Finishing: IIS Web App Deploy

```

### Error logs

None

**Comment by chshrikh** [comment]
not sure we got your issue, but when the release is getting exacted it runs on all targets registered with DG, if you want to run it on specific target you need to use the tag filtering.  Coming to your issue, when you are saying it gets overridden, have you tried to filter the targets as per your need

**Comment by dhazel** [comment]
Thanks Chaitanya. I solved the problem. I will write up my process here and close the issue. 

# Solution
The problem was not with the deployment module, but rather I had mis-configured the [IIS management module](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/IISWebAppManagementOnMachineGroupV0) that ran immediately preceding each deployment module. Each management module had the same `physical path` parameter value set for each virtual application, which caused each deploy to overwrite any previous deploy.

# Debugging Process
When writing up this issue, ironically, there was a [link to instructions for troubleshooting AzureDevops](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops), so I started following that document.

1. I [turned on verbose logging on the deployment agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#configure-verbose-logs) by adding the `system.debug` variable to the release pipeline and setting it to `true`.
    * From this I could see that there were, in fact, no other virtual applications being deployed to
2. I checked the additional agent logs on the target server under the agent install directory in a directory titled `_diag`.
    * This showed that everything was working correctly
3. Still not convinced, [I looked at the source code](https://github.com/microsoft/azure-pipelines-tasks/blob/469f022c8afa18a9035a3a70f4086a35779cb436/Tasks/Common/webdeployment-common/deployusingmsdeploy.ts#L26) and found that all the module is doing is running MsDeploy.
    * This got me wondering if all the deployments were going to the same physical location
4. Then I looked at my config for the [IIS management module](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/IISWebAppManagementOnMachineGroupV0) and noticed that I had set identical physical paths for each virtual application.
5. I tested the hypothesis by setting a different physical path for each application, and, *yay*, the applications no longer overwrote each other!
