### ISSUE TITLE
AutoIt and Command Line

### ISSUE THREAD

**Issue by mohanviswan** [microsoft/azure-pipelines-tasks#12687]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Command line

## Issue Description

My requirement is to create an installer through AutoIT scripts (AutoIT is an open source alternative to InstallShield). Since Azure pipelines does not have an inbuilt task for AutoIt, I have checked in all the binaries required for compiling a AutoIT script.

I created a command line task to run the AutoIT exe compiler with the script as argument. The problem I am facing is the script never completes. If I run the same script in my local system, it completes in 1-2 seconds and creates the installer. But running in a task in an azure pipeline, the task just hangs and never completes.

This is my script:
@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
      
START /WAIT $(Build.SourcesDirectory)\Deploy\Kit\AutoIt\Aut2Exe\Aut2exe.exe /In $(Build.SourcesDirectory)\Deploy\Kit\temp.au3 /Out $(Build.ArtifactStagingDirectory)\Kit\Kit.exe
      
ENDLOCAL

Any help is appreciated. Thanks.

I have tried the same with Powershell and the same issue happens there too.

### Task logs

##[debug]Evaluating condition for step: 'Build Kit'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Build Kit
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
##[debug]VstsTaskSdk 0.9.0 commit 6c48b16164b9a1c9548776ad2062dad5cd543352
##[debug]Entering D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.164.0\cmdline.ps1.
##[debug]Loading resource strings from: D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.164.0\task.json
##[debug]Loaded 6 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.164.0\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 6 strings.
##[debug]INPUT_FAILONSTDERR: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_SCRIPT: '@ECHO OFF
##[debug]SETLOCAL ENABLEDELAYEDEXPANSION
##[debug]
##[debug]START /WAIT D:\a\1\s\Deploy\Kit\AutoIt\Aut2Exe\Aut2exe.exe /In D:\a\1\s\Deploy\Kit\temp.au3 /Out D:\a\1\a\Kit\Kit.exe
##[debug]
##[debug]ENDLOCAL'
##[debug]INPUT_WORKINGDIRECTORY: 'D:\a\1\s'
##[debug]Asserting container path exists: 'D:\a\1\s'
Generating script.
##[debug]AGENT_VERSION: '2.165.2'
##[debug]AGENT_TEMPDIRECTORY: 'D:\a\_temp'
##[debug]Asserting container path exists: 'D:\a\_temp'
##[debug]Asserting leaf path exists: 'C:\windows\system32\cmd.exe'
========================== Starting Command Output ===========================
##[debug]Entering Invoke-VstsTool.
##[debug] Arguments: '/D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\73d459bd-84a8-4156-999c-d512c300af83.cmd""'
##[debug] FileName: 'C:\windows\system32\cmd.exe'
##[debug] WorkingDirectory: 'D:\a\1\s'
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\73d459bd-84a8-4156-999c-d512c300af83.cmd""

**Comment by jtpetty** [comment]
@damccorm - Do you mind taking a peak at this?

**Comment by damccorm** [comment]
Hey @mohanviswan can you share the script you're using by chance?

**Comment by mohanviswan** [comment]
The actual installer script is about 750 lines long. But I tried this with a simple script of displaying a message box.

The script is as follows:

`MsgBox (0,"","Hello")`

I am facing the same issue even with this simple script.
Thanks for looking into this.

**Comment by damccorm** [comment]
I think the underlying issue here is that you're creating a new process and never completing it. Our agent waits for all processes in the process tree to exit before moving on to the next step, so your script would need to terminate any subprocesses before moving on

**Comment by mohanviswan** [comment]
How is it different from running the same script in a cmd window in my local machine. Because running the same command in my local works. The script gets compiled by Aut2exe and my installer gets generated.

I'll check if it creates any subprocess while creating the installer.

**Comment by damccorm** [comment]
Your local cmd doesn't wait on all subprocesses to complete

**Comment by damccorm** [comment]
We do that so that we can guarantee that a task doesn't complete before finishing any work a future step or job might depend on, and for security purposes and so that stale processes aren't left around for future builds (among other reasons)

**Comment by mohanviswan** [comment]
Oh. That makes sense. I have posted the same problem in the AutoIt forums too. I'll mention this there and see if there is a way to close those sub-processes from within the script.

Thanks for the investigation. I'll post back here if I find any solution.

**Comment by damccorm** [comment]
Closing since we've provided all the help we can from our end.
