### ISSUE TITLE
Download pipeline artifact breaks folder structure when downloading pipeline artifact

### ISSUE THREAD

**Issue by leinoaa** [microsoft/azure-pipelines-tasks#12682]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  DownloadPipelineArtifact@2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Private Windows agent, agent version 2.165.0

## Issue Description

If you are downloading a pipeline artifact (from another pipeline) and the name of the artifact is used in the folder structure of the artifact, it can cause the following issues.

Folder level removed, file renamed:

Solutions/ThisIsAnArtifactName/url.runsettings
-> Solutions/ThisIsAnurl.runsettings

Folder level removed:
Solutions/ThisIsAnArtifactName/Obj/...
-> Solutions/ThisIsAnObj/...

So it seems that the 'artifact name' is deleted from the folder structure, which may result in lost folder-levels or changed folder names and changed file names. And the breaking only happens for only the folder that has similarities with the artifact name, rest of the folders stay as they should. Also if you check the built artifact, there the folder structure is correct. So the copying breaks it.

### Task logs

No logs, just observed functionality from the result.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

No logs, just observed functionality from the result.

**Comment by joshmurari** [comment]
This issue is still present and needs to be reopened.

**Comment by abatishchev** [comment]
@leinoaa please see if you can reopen the issue.

**Comment by leinoaa** [comment]
FYI, as the latest even shows, opened new issue #16522.
