### ISSUE TITLE
Operation returned an invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by zeeshanmcp12** [microsoft/azure-pipelines-tasks#12699]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Question**

**Enter Task Name**: **AzurePowershellV3**
(App Settings Update)

## Environment
**Azure Pipelines**

- Agent - Hosted or Private: 
**Hosted**
**Current agent version: '2.166.2'**

## Issue Description

Our release is failing on appsettings update task. The error is "Operation returned an invalid status code 'BadRequest'".

Our project is based on the AzurePowerShellV3 task in https://github.com/Microsoft/azure-pipelines-tasks

I've tried to follow the assistance provided in [this](https://github.com/Azure/azure-powershell/issues/10100) issue but it didn't help.

![image](https://user-images.githubusercontent.com/26859762/79379032-b0aa2d80-7f77-11ea-8403-6ec650bc4db0.png)

### Task logs
[tasks_log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4483299/tasks_log.zip)

## Troubleshooting
As per suggestion in [this](https://github.com/Azure/azure-powershell/issues/11374) question, I've updated the AzureRM to Az module in my task but no luck.

**Comment by chshrikh** [comment]
@zeeshanmcp12 as per attached logs you are not using azurepowershell task, you are using "Set AppService Application Settings"

**Comment by zeeshanmcp12** [comment]
@chshrikh Thank you for your prompt response. our custom task "Set AppService Application Settings" is based on azurepowershell task which we modified a little as per our need.
For example "Update application settings on an app service". Any pipeline variable (including secret variables) prefixed with AppSettingPrefix will get added/updated as an application setting in the appservice.

I would be very thankful if you can please assist about where actually the issue is.

Let me know if you required any further information, and tell me any location also where I can upload ps script file.

**Comment by chshrikh** [comment]
@zeeshanmcp12 we will not able to debug any issue for task on which we dont have context, you may need to debug at your end.
1) Try to run the task business logic locally by providing same inputs
2) You may try running it with your own local agent, this will also help you to debug it easily.
