### ISSUE TITLE
No output variable for the helm task

### ISSUE THREAD

**Issue by pieterv-icloud-com** [microsoft/azure-pipelines-tasks#12696]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: HelmDeployV0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

We want to be able to issue a helm ls -o json command using the helm task, we then want to manipulate the output in subsequents steps. Unfortunately the helm task does not produce any output variables so that the data returned can be manipulated. We have created a PR to resolve this. The helm task will now populate a helmOutput variable with the output of the command.

**Comment by ds-ms** [comment]
Duplicate issue: https://github.com/microsoft/azure-pipelines-tasks/issues/12532
