### ISSUE TITLE
dear god, it was working happily and it has stopped working, why!?

### ISSUE THREAD

**Issue by evmimagina** [microsoft/azure-pipelines-tasks#12709]
Hi,

This issue I'm opening is quite critical, as I have an scenario were everything was working fine and it has stopped working, just few weeks of difference.

In my opinion, this is a BUG

I have an "Azure CLI 1.0" Task, executing the following inline script;

![image](https://user-images.githubusercontent.com/56918327/79495472-e9eca700-8024-11ea-8a4b-7fa9aa11ebb3.png)

Yep! as simple as those two lines.

The task working fine around a month ago;

![image](https://user-images.githubusercontent.com/56918327/79495563-1274a100-8025-11ea-83ff-ea8e518903d9.png)

But now it doesn't…

![image](https://user-images.githubusercontent.com/56918327/79495590-1c969f80-8025-11ea-9103-6433ea54859e.png)

The only difference I can tell is related to the Azure CLI version being use to run the task.

The error message is this;

![image](https://user-images.githubusercontent.com/56918327/79495618-27e9cb00-8025-11ea-87fb-dd94a6aa6a39.png)

Could someone help me ASAP?, I have the developers without being able to keep working just because I can't Connect AKS to ACR as I used to do....

Thanks in advance and best regards,

**Comment by issacnitin** [comment]
@evmimagina Apologies for the late response. This is an issue with Azure CLI tool itself, and not with the task "AzureCLI" used in Azure DevOps. The two teams are de-coupled as of now 🤒 . Please open a ticket at https://github.com/Azure/azure-cli/issues , they'll be able to help you with what has changed in `az aks` command that is causing the failure.

**Comment by issacnitin** [comment]
@evmimagina Hope you were able to get in touch with Azure CLI team. We're closing the issue, please feel free to reopen if you have any queries or concerns regarding this
