### ISSUE TITLE
vsts-npm-auth expires after 1 day. 

### ISSUE THREAD

**Issue by akshaybheda** [microsoft/azure-pipelines-tasks#12703]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: vsts-npm-auth

The vsts-npm-auth is expiring after 1 day. Tried ` vsts-npm-auth -c %userprofile%\.npmrc -E 129600` But in the https://xxx.visualstudio.com/_usersSettings/tokens, The validity is 1 day and it also expires in one day. Have to create token daily. 
Version v0.37.0.0

**Comment by akshaybheda** [comment]
![image](https://user-images.githubusercontent.com/22575879/79416780-16c19f80-7fce-11ea-874a-910fc7bac73c.png)

**Comment by zachary-edwards** [comment]
I am experiencing the same issue

**Comment by UnleashMayhem** [comment]
Me as well

**Comment by anirban1987** [comment]
Me too.

**Comment by AmeyaSatone** [comment]
I am also facing the same issue.

**Comment by akshaybheda** [comment]
https://developercommunity.visualstudio.com/content/problem/1008037/vsts-npm-auth-expires-after-1-day.html

**Comment by herenhuang** [comment]
Pasting the solution from the DevCommunity link here: 

We've pushed a new version of vsts-npm-auth that should mitigate session token expiry problems. Please use vsts-npm-auth v.0.41.0 or greater.

Closing this issue! :)
