### ISSUE TITLE
Azure hosted agent to perform PS task with AzCopy to static web container

### ISSUE THREAD

**Issue by charleswooprudential** [microsoft/azure-pipelines-tasks#12700]
The azcopy.exe located in c:\program files (x86)\microsoft sdks\azure\azcopy is v6.2 which does not support copy blob to static web container $web.

What would be the workaround for this?

**Comment by chshrikh** [comment]
have you tried using latest AzureFileCopy task ?

**Comment by charleswooprudential** [comment]
With several restrictions, I would only obtain sas token but not a service principal to acquire storage account access key and other tasks (which I would like to know what would be the requirement of priviledges of this service principal).
I have successfully downloaded the ver10.4 to hosted agent and use it for blob copy.
I would like to know if there would be other options.

**Comment by chshrikh** [comment]
@charleswooprudential sorry for delay, in case you are still looking for details on azcopy task, @20shivangi can help you here

**Comment by 20shivangi** [comment]
Our AzureFileCopyV4 task uses azcopy.exe with version 10.3 which supports copying of files to azure blob and azure VM.
You can refer to this repo for parameters : https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4

**Comment by 20shivangi** [comment]
Closing this issue. Please feel free to reopen if you are facing some issue.
