### ISSUE TITLE
Dac deployment to "include new columns into existing non clustered index" actually deleted the index

### ISSUE THREAD

**Issue by Prithvitm** [microsoft/azure-pipelines-tasks#12705]
Recently we added new included columns into an existing non clustered index..
 
The dac deploy script initially had a command to drop this index and had the next command to re-create the index again. Since the table size was huge, the re-create index operation timed-out. But we also saw that the old index is no longer present and the index itself got deleted.
 
The expectation is that, if dac is unable to add new included columns into an existing non clustered index.. then it should not delete the existing index itself. Could you please help on the root cause and fix this issue ?

Below was the create command used (as said earlier, there was a command to drop the index before this statement, in the dac diff script, fyi):

CREATE NONCLUSTERED INDEX [IX_CEntity_ConSysId_AHash]
 ON [g].[CwlEntity]([CSystemId] ASC, [SEntityIdHash] ASC)
 INCLUDE([SEntityId], [LItemId], [CIdentifiedDateTime], [CIngestedDateTime], [IContainer], [PId], [CHash], [SPropertiesHash], [AHash])
 ON [PS_Uniqueidentifier] ([CSystemId]);

**Comment by chshrikh** [comment]
@Prithvitm which task are you referring to ?

**Comment by chshrikh** [comment]
@Prithvitm please let us know details on this if you are still facing issue
