### ISSUE TITLE
DotNetCoreCLI@2 breaks when the projects is given a path starting with the dot

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#12717]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - **TFS on-premises**
    
    - If using TFS on-premises, provide the version: **Dev17.M153.3**

- Agent - **Private**

 name | value
   -- | --
 Agent.Version | 2.153.1
 Agent.OS | Windows_NT
 Agent.OSArchitecture | X64
 Agent.OSVersion | 10.0.14393

## Issue Description

I have the following yaml template reused by many projects:
```
parameters:
  BuildConfiguration: Debug
  projects: ['*.sln']
  workingDirectory: '.'

steps:
- ${{ each project in parameters.projects }}:
  - task: DotNetCoreCLI@2
    displayName: Build ${{ project }}
    inputs:
      command: 'build'
      projects: ${{ parameters.workingDirectory }}\${{ project }}
      arguments: '-c ${{ parameters.BuildConfiguration }}'
```
When the workingDirectory is omitted, '.' is used. But the task breaks in this case:
```
##[debug]adjustedPattern: 'd:\_wf\06\20\s\.\*.sln'
##[debug]0 matches
##[debug]0 final results
##[debug]task result: Failed
##[error]Project file(s) matching the specified pattern were not found.
```
This template parameter is a new addition, I added it because we have some projects that have not been moved out of the one big monolithic repo, but it seems that the straightforward approach does not work, forcing me to do ugly hacks.

### Task logs

[Build 1.0.20108.6-Build.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4494550/Build.1.0.20108.6-Build.zip)

### Error logs

```
##[debug]  d:\_wf\06\20\s\DBScriptSplit\Mono.Options.cs (file)
##[debug]  d:\_wf\06\20\s\DBScriptSplit\Program.cs (file)
##[debug]  d:\_wf\06\20\s\DbScriptSplit.sln (file)
##[debug]  d:\_wf\06\20\s\Directory.Build.props (file)
##[debug]  d:\_wf\06\20\s\Directory.Build.targets (file)
##[debug]  d:\_wf\06\20\s\Directory.Build.Template.props (file)
##[debug]  d:\_wf\06\20\s\nuget.config (file)
##[debug]194 results
##[debug]found 194 paths
##[debug]applying include pattern
##[debug]adjustedPattern: 'd:\_wf\06\20\s\.\*.sln'
##[debug]0 matches
##[debug]0 final results
##[debug]task result: Failed
##[error]Project file(s) matching the specified pattern were not found.
##[debug]Processed: ##vso[task.issue type=error;]Project file(s) matching the specified pattern were not found.
##[debug]Processed: ##vso[task.complete result=Failed;]Project file(s) matching the specified pattern were not found.
##[section]Finishing: Build *.sln
```

**Comment by tejasd1990** [comment]
Hi @MarkKharitonov, the _projects_ input is used to locate the projects via minimatch pattern search, not path search. Also, I think the _${{ each project in parameters.projects }}_ will not expand the pattern, that will have to be done via a script. I guess you don't need a _${{ each}}_ expression, you can just give _**/*.sln_ or _**/*.csproj_ as the value for the _projects_ input

**Comment by MarkKharitonov** [comment]
Ideally passing `**/*.sln` would work. The reality is that this approach does not work when the solutions must be built in a certain order. That is why we cannot utilise this form.

The proper semantics for the projects field should be **either** minimatch **or** path. Otherwise, how are you going to handle the issue of order? Except by requesting the users of the task to rename their solutions. Which is not a good requirement to ask.

**Comment by issacnitin** [comment]
@MarkKharitonov I am able to reproduce this issue. You have two options here:
1. You can specify the build order for your project in Visual Studio IDE and use ```**/*.sln```
2. You can specify ```workingDirectory``` parameter for the task itself, rather than making it part of the project path 
Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

Let us know if this works out for you

**Comment by MarkKharitonov** [comment]
@issacnitin I am sorry, I do not understand your item (1). Can you elaborate what do you mean exactly? As far as I know VS IDE lets me establish order between projects, not solutions.
As for the item (2), please have a look at https://github.com/microsoft/azure-pipelines-tasks/issues/10996
The task ignores workingDirectory for build and some other targets.

**Comment by issacnitin** [comment]
@MarkKharitonov Yes, VS IDE will let you establish order between projects. I understand you need to establish an order between solution files as well. I am able to reproduce the issue that workingDirectory is not being honored for ```build```. Apologies for the inconvenience, we'll be working on it actively and rolling out the fix as soon as possible. Thanks

**Comment by MarkKharitonov** [comment]
Great, looking forward...

**Comment by anuragc617** [comment]
Closing this issue as the DotNetCoreCLI@2 projects path should be minimatch pattern and working directory input is used for running the dotnet command. The working directory help text has also been update for the same.
