### ISSUE TITLE
DotNetCoreCLI@2 cannot use variable for vstsFeed

### ISSUE THREAD

**Issue by temelj** [microsoft/azure-pipelines-tasks#12726]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: When restoring packages, must specify vstsFeed guid, cannot use variable `${feed}`

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

## Issue Description

I would like to set a global variable for the feed guid that can be re-used in multiple places if required. But the current flow doesn't support this.

**Comment by tejasd1990** [comment]
Hi @temelj, I tried to repro this issue, but it worked for me. 
You will have to use the variable as $(feed), not ${feed}. Refer [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax) for variable syntax and how to use them in pipelines. 
Note that you will need to give the feed in the format _"projectId/feedId"_, or _"projectName/feedId"_

**Comment by temelj** [comment]
Hi @tejasd1990 ,
I apologies, good pickup! I've checked it in my pipeline and it works as documented. Thanks.
