### ISSUE TITLE
vsts-npm-auth is throwing "task was canceled" exception

### ISSUE THREAD

**Issue by Sukesh-Gundoji** [microsoft/azure-pipelines-tasks#12729]
Hi team, can you anyone help me why I am getting below issue while I was trying get the latest crendentials.

![image](https://user-images.githubusercontent.com/60191746/79848075-37c72d80-83de-11ea-872f-fca630c82fe6.png)

**Comment by kraay** [comment]
Getting the same issue.
Any updates?

**Comment by herenhuang** [comment]
Hey there, is this a reproducible issue? Can you provide some more details please?

**Comment by omokoh** [comment]
Hi,
If you still experiencing this issue, please reopen it.
Thanks

**Comment by atulsingh7890** [comment]
I am experiencing this recently, the only difference that i have between the scenario where it was working was the Connection Speed. When the connection Speed is high it does not fail, and when connection speed is low it fails with Task Cancelled. 

i am suspecting some Timeout is happening in Slow Connection. Is there any timeout config we can specify ?
