### ISSUE TITLE
[featureRequest] AzureResourceGroupDeploymentV2 - add tags upon resource group creation

### ISSUE THREAD

**Issue by mjazwiecki** [microsoft/azure-pipelines-tasks#12720]
Hi,

As for now, there is no way to add tags upon creation of resource group using AzureResourceGroupDeploymentV2 task. Only way is to add another step and add tags using PS/az cli.

related: https://github.com/microsoft/azure-pipelines-tasks/issues/11122

**Comment by vinodkumar3** [comment]
ARM Template support adding tags along with resource creation. Please follow https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-add-tags?tabs=azure-powershell#add-tags

**Comment by mjazwiecki** [comment]
@vinodkumar3  that is correct - but for me this is yet another workaround.

**Comment by vinodkumar3** [comment]
Agreed. We are taking this request as an enhancement to the task and will prioritize accordingly.

**Comment by mjazwiecki** [comment]
any info on a progress?

**Comment by bjh1977** [comment]
It is silly that tags can't be applied to the resource group using this step. A lot of organisations, including mine, have deny policies which prevent resource groups from being created without certain tags, which renders this task useless, and also necessitates extra steps to be added up front.

**Comment by bgawale** [comment]
can someone confirm - is there any update on this?
