### ISSUE TITLE
Task for updating changeset using in "get sources" step?

### ISSUE THREAD

**Issue by huntantr** [microsoft/azure-pipelines-tasks#12736]
## Required Information
*Type*: Question, but maybe a Feature request

## Environment
- Server - TFS2019 on-premise
    version: Dev17.M153.5

- Agent - Private: 
    Windows 10 Pro v1903
    Agent: 2.153..1

## Issue Description
During the build process during the "Get" step, the "tf vc get /version:_changeset_ ..." command selects the changeset somehow. Is there a task that can update this to a newer changeset for use in the next phase?
I have a scenario where I need to update and checkin a file for use through the process, but this changeset is then not picked up by the build until the next build run.
Ideally I would like to be able to create this changeset in phase 1, then in phase 2 use that changeset not the one the build started with.
This would then allow it to show up in the build summary as an associated changeset.

This would be similar to along the lines of what the build.updatebuildnumber task does for the build number.

**Comment by damccorm** [comment]
We don't allow you to do this (for a number of reasons including some security and rerunnability implications). The recommended path would be to write a custom script to pull the latest version in the second phase

**Comment by huntantr** [comment]
@damccorm, I tried that without much success. What command should I be running, as the one I tried didn't pull in the changeset added in phase 1?
I even tried using 2 different agents.

**Comment by damccorm** [comment]
I'd recommend checking out the file you checked in to the remote provider, so it would just be a tfvc checkout command.

**Comment by huntantr** [comment]
I have tried this and it gets the source for the new changeset, but the issue still remains in that the build summary does not reflect the newly added changeset. The only way for it to appear is in the next build, which does not help when it is the "final" build for a product.
