### ISSUE TITLE
Docker@2 'build' command: path argument provided to docker cli is different than when using 'build&Push' command 

### ISSUE THREAD

**Issue by farlop** [microsoft/azure-pipelines-tasks#12732]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Docker@2  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure DevOps Server 2019 

- Agent - Hosted or Private:    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Ubuntu 18.04
Agent 2.158.0

## Issue Description
Running pipeline for a VS project in a sollution with projects. After switching from 'build&push' to two different steps 'build' and 'push', the build command fails not finding the source code, since PATH is different

## Error message
`##[error]COPY failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder759961552/Services/Catalog/Catalog.API/Catalog.API.csproj: no such file or directory
`

### Task logs
Command logged when using 'buildAndPush':
`[command]/snap/bin/docker build -f /home/xxx/agents/A/_work/5/s/Services/Catalog/Catalog.API/Dockerfile [labels and tags removed] /home/xxx/agents/A/_work/5/s` 

Command loggend when using 'build'

`[command]/snap/bin/docker build -f /home/xxx/agents/A/_work/5/s/Services/Catalog/Catalog.API/Dockerfile [labels and tags removed] --pull /home/xxx/agents/A/_work/5/s/Services/Catalog/Catalog.API`

**Comment by ds-ms** [comment]
@rgsubh to take a look.

**Comment by rgsubh** [comment]
@farlop could you please share a snapshot of your "azure-pipelines.yml" which shows the two separate steps build and push. And also could you please confirm of this fails in the pipeline tasks or a generic docker build failure. Thanks!

**Comment by rgsubh** [comment]
Closing stale issue. Please feel free to reopen if you are still facing this.
