### ISSUE TITLE
Bash@3 task is writing to the standard error stream for Docker image not found locally

### ISSUE THREAD

**Issue by HemantManglani** [microsoft/azure-pipelines-tasks#12738]
**Bug:**  Bash wrote one or more lines to the standard error stream for Docker image not found locally
**Task Name**: Bash@3
## Issue Description
Bash wrote one or more lines to the standard error stream for Docker image not found locally

![image](https://user-images.githubusercontent.com/25983765/80041361-9fe15500-853f-11ea-94c0-1d14941fa1f2.png)

### Error logs
##[error]Bash wrote one or more lines to the standard error stream.
##[error]Unable to find image 'justb4/jmeter:latest' locally
##[error]latest: Pulling from justb4/jmeter
##[error]89d9c30c1d48: Pulling fs layer
##[error]aecaabf9f08f: Pulling fs layer
##[error]1da6aa19b0c9: Pulling fs layer
##[error]1da6aa19b0c9: Verifying Checksum
##[error]1da6aa19b0c9: Download complete
##[error]89d9c30c1d48: Verifying Checksum
##[error]89d9c30c1d48: Download complete
##[error]89d9c30c1d48: Pull complete
##[error]Additional writes to stderr truncated

**Comment by ds-ms** [comment]
I suppose you're using docker-compose? https://github.com/microsoft/azure-pipelines-tasks/pull/12622#issuecomment-611519015

**Comment by HemantManglani** [comment]
I'm trying to pull and run a Docker image from the hub (not composing my own Docker image).
#12622 looks slightly different.

Following run command results in pulling an image from Docker Hub:
sudo docker run --name ${NAME} -i -v ${WORK_DIR}:${WORK_DIR} -w ${WORK_DIR} ${IMAGE} $@

Trying to pull image: justb4/jmeter:latest

Also logs don't indicate any error on those steps; but for some reason Bash task is writing those lines to the standard error stream.

Log:
2020-04-22T01:51:45.9112852Z Unable to find image 'justb4/jmeter:latest' locally
2020-04-22T01:51:48.3352485Z latest: Pulling from justb4/jmeter
2020-04-22T01:51:48.3366671Z 89d9c30c1d48: Pulling fs layer
2020-04-22T01:51:48.3369070Z aecaabf9f08f: Pulling fs layer
2020-04-22T01:51:48.3370673Z 1da6aa19b0c9: Pulling fs layer
2020-04-22T01:51:49.2234838Z 1da6aa19b0c9: Verifying Checksum
2020-04-22T01:51:49.2235742Z 1da6aa19b0c9: Download complete
2020-04-22T01:51:49.2490122Z 89d9c30c1d48: Verifying Checksum
2020-04-22T01:51:49.2491041Z 89d9c30c1d48: Download complete
2020-04-22T01:51:49.4139004Z 89d9c30c1d48: Pull complete
2020-04-22T01:51:49.8379092Z aecaabf9f08f: Verifying Checksum
2020-04-22T01:51:49.8380662Z aecaabf9f08f: Download complete
2020-04-22T01:51:51.7042469Z aecaabf9f08f: Pull complete
2020-04-22T01:51:51.7417122Z 1da6aa19b0c9: Pull complete

**Comment by nevvermind** [comment]
I don't think this is a problem with the task.

Docker is probably using `stderr` to print those messages.
But the task is [reading off `stderr`](https://github.com/microsoft/azure-pipelines-tasks/blob/baa378be8750419dc77cc11db6f4517560801a03/Tasks/BashV3/bash.ts#L147), and assuming everything that gets pushed there is an error, which [is not entirely true](https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout), but there's isn't much you can do.

Maybe you can control `docker run`'s behavior, but telling it _not_ to print to `stderr` [here](https://docs.docker.com/engine/reference/commandline/run/#attach-to-stdinstdoutstderr--a) or [here](https://docs.docker.com/engine/reference/run/#foreground).

**Comment by ds-ms** [comment]
These special handlings are done by the docker task(s). But the bash task is expected to work this way. i.e. stderr be considered as stderr

**Comment by wujenny15** [comment]
I changed the "failOnSterr:false"  then I do not have this error
