### ISSUE TITLE
Case-sentitive Updates to Azure SQL DB is not Reflecting

### ISSUE THREAD

**Issue by Surendra-thota1640** [microsoft/azure-pipelines-tasks#12739]
we are using Azure SQL database deployment Task  through DACPAC  in azure Devops for our DB changes , we are getting a strange issue , we have updated the schema name from Stage to stage  , the repo files have the change and DACPAC model file have the change but the change is not reflecting in destination server .Please let us know if we need to set any particular setting at deployment level.
NOTE : If we delete the schema from the destination server then in next release it is updating with correct Case sensitive name .

**Comment by chshrikh** [comment]
you may set "sytsem.debug" variable with true value and generate the detailed logs for execution, with detailed logs you may see what is getting deployed with what name and cross check it on azure portal.

**Comment by eaarora-ms** [comment]
Hi, @Surendra-thota1640  Please provide an update on whether you were able to figure out what is getting deployed by setting "system.debug" as true in pipeline variables.

**Comment by eaarora-ms** [comment]
@Surendra-thota1640  I am closing the issue. Please feel free to comment to re-open If you're still facing the same issue.
