### ISSUE TITLE
Helm Installer with 'latest' pulls in most recent release and not most latest

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/azure-pipelines-tasks#12731]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  Bug

**Enter Task Name**: HelmInstaller

## Environment
- Server - Azure Pipelines or TFS on-premises?
  - Azure Pipelines

## Issue Description

Helm Installer with 'latest' pulls in most recent release on GitHub (i.e. 2.16.2) and not the most latest in terms of features (3.1.2).

I would have expected to pull in 3.1.2 but was 2.16.2 since they have released a patch for 2.16.

Is this the intended behavior? If so, how do we require it to pull latest version for 3.x?

### Task logs

```
==============================================================================
Task         : Helm tool installer
Description  : Install Helm on an agent machine
Version      : 1.166.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-installer-tsg
==============================================================================
Downloading: https://api.github.com/repos/helm/helm/releases/latest
Downloading: https://get.helm.sh/helm-v2.16.6-linux-amd64.zip
Extracting archive
/usr/bin/unzip /home/vsts/work/_temp/helm-v2.16.6-b0fa93a6-35b4-4b96-91bd-e40b613840e5.zip
Archive:  /home/vsts/work/_temp/helm-v2.16.6-b0fa93a6-35b4-4b96-91bd-e40b613840e5.zip
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

None.

**Comment by shigupt202** [comment]
@tomkerkhove Sorry for the inconvenience. This issue has already been addressed in this [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/12592/files). The deployment with this fix is in progress and should reach out to all the customers within few days.
