### ISSUE TITLE
Release Definition Visual Studio Test task v2.* does not find test assemblies

### ISSUE THREAD

**Issue by annthom01** [microsoft/azure-pipelines-tasks#12740]
I have a release definition with Test Run selection. But when I try to execute test case from test plan, I am getting the following error.
No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.

I have tried to set the Search Folder to the path where the test assemblies are. Still no luck. 

![image](https://user-images.githubusercontent.com/64204425/80098634-38290b00-853b-11ea-8cd9-440d74cb964f.png)

2020-04-23T12:09:34.2297274Z ##[error]ExecutionTaskStateModel.ExecuteTask: Recived error while executing task: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.
2020-04-23T12:09:34.2297274Z ##[debug]Processed: ##vso[task.logissue type=error;]ExecutionTaskStateModel.ExecuteTask: Recived error while executing task: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct.

**Comment by annthom01** [comment]
i have added VSTest task in the build definition and the build is success.
![image](https://user-images.githubusercontent.com/64204425/80121401-40dd0980-855a-11ea-87a2-bf949a0d92f1.png)


If I select Test Assembly in Release definiton the test run wont triger.

![image](https://user-images.githubusercontent.com/64204425/80121613-87326880-855a-11ea-8b40-89bf628b14da.png)

![image](https://user-images.githubusercontent.com/64204425/80121673-9b766580-855a-11ea-9190-04e42d76dde7.png)

If I select Test Run, the release definition is not getting the test assemblies.
I am not able to find whats wrong.

**Comment by ismail4u** [comment]
Any update on this , i am also facing similar issue >

**Comment by annthom01** [comment]
> Any update on this , i am also facing similar issue >

No, I still have the issue. I think vstest is not identifying codedui test cases.

**Comment by singhsarab** [comment]
@annthom01 Are you sure that the test assemblies are present in the given location ?
Build definition usually would have the test assemblies as they are built as part of the build definition.
For releases, you need to make sure the test assemblies are part of the artifacts, which get downloaded on the release agents.

What agents are you using to run the tests? Are these private agents or hosted agents ?

**Comment by singhsarab** [comment]
It would be great if you could share the diagnostic logs with us. set system.debug = true to enable the diagnostic logs.

**Comment by annthom01** [comment]
yes, the test assemblies are in the location. I infact hardcoded the test assemblies path to search for also.

**Comment by singhsarab** [comment]
@annthom01 Thanks for your note. Please share with us the diagnostic logs and also please answer all the questions I have asked above.

**Comment by annthom01** [comment]
Hi,
As I mentioned in my problem, when I select Test Assemblies the test run is not triggered. I have to select Test Plan to get the test run triggered.

This is the message I get when I select Test Assemblies.

![image](https://user-images.githubusercontent.com/64204425/81292155-1a7a9c00-9039-11ea-87f0-784fc4fcf89d.png)

**Comment by singhsarab** [comment]
@annthom01 Can you please share the diagnotics logs for us to look further into this issue?

**Comment by hvinett** [comment]
@annthom01 any updates on this?

**Comment by ShreyasRmsft** [comment]
@annthom01 you can run the tests from the test plan hub if "test assemblies" option is selected. You'll have to queue the release manually and that is what @singhsarab is asking you to try.

Also please re-open the issue after trying the above suggestion and also as request please provide full zip logs for both cases with system.debug set to true.
