### ISSUE TITLE
AzureFileCopy@4 requires more permission than it needs.

### ISSUE THREAD

**Issue by BrianMouncer** [microsoft/azure-pipelines-tasks#12747]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopy@4  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://msasg.visualstudio.com/DefaultCollection/Skyman/_build/results?buildId=11661105&view=logs&j=572904f9-79b1-51c4-99c0-531b4ffd4297&t=8b2ab2ed-9d5d-5ad9-6e9b-829c0a025cd8

- Agent - Hosted or Private: 
    Hosted
    - If using Hosted agent, provide agent queue name:

Pool: Hosted Windows 2019 with VS2019
Agent: Hosted Agent
Started: Today at 1:07 PM
Duration: 7m 48s

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I am trying to setup a task to publish form files form the build to our azure blob storage.
I can use Azure CLI and the DevOps extention to copy the file fine from a standalone container, so i know the Service Principle and Service Connection can work.

How ever the AzureFileCopy task is returning errors.  at first it was requireing write access the resource group, when it does not need it.  even after I grand write access to the resource group, it still errors.  I do not want to grant full access to the subscription, so I am blocked at this point and can not proceed.

### Task logs

current issue: https://msasg.visualstudio.com/DefaultCollection/Skyman/_build/results?buildId=11661105&view=logs&j=572904f9-79b1-51c4-99c0-531b4ffd4297&t=8b2ab2ed-9d5d-5ad9-6e9b-829c0a025cd8

Previous issue about needing write access to Resource Group.

https://msasg.visualstudio.com/DefaultCollection/Skyman/_build/results?buildId=11658445&view=logs&j=572904f9-79b1-51c4-99c0-531b4ffd4297&t=8b2ab2ed-9d5d-5ad9-6e9b-829c0a025cd8

https://msasg.visualstudio.com/DefaultCollection/Skyman/_build/results?buildId=11632784&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=aa93901e-8a99-59e9-9b6c-e5da919f37b9

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by 20shivangi** [comment]
@BrianMouncer AzureFileCopyV4 uses azcopy.exe with latest version and it requires permission of Storage blob contributor and storage blob owner on your SPN.
Please refer to this doc : https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#option-1-use-azure-active-directory

**Comment by 20shivangi** [comment]
Closing this issue, feel free to reopen if facing further issue
