### ISSUE TITLE
Question: Does this still exist task.json documentation.md?

### ISSUE THREAD

**Issue by NancyChong** [microsoft/azure-pipelines-tasks#12749]
In a old pull request I found there used to be a task.json documentation.md that described how groups worked in task.json. Does this documentation still exists now since I can't find it anymore?

https://github.com/Microsoft/azure-pipelines-tasks/pull/1066/files

I'm trying to figure out how to group things and wonder if you use groups that all the inputs should be grouped or how the grouped items will appear (will it be below the non grouped inputs)

**Comment by damccorm** [comment]
There are some docs here - https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops - and a schema here - https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops.

If neither of those meet your needs, please file an issue at https://github.com/MicrosoftDocs/azure-devops-docs/issues - that repo is dedicated for docs issue, while this repo is more meant for questions/issues about specific tasks
