### ISSUE TITLE
AzureAppServiceSettings invalid json in windows but valid in linux

### ISSUE THREAD

**Issue by Codebytes** [microsoft/azure-pipelines-tasks#12744]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureAppServiceSettings

list here (V# not needed):  1.163.4
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Org:chrisnewsig
Team Proj: TrunkVsGitFlow
pipeline: basicNode
Build# :#20200423.13

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: fv-az137

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I am trying to deploy a node app to both a windows and linux azure web app.
I'm using the same AzureAppServiceSettings in both, the linux webapp succeeds and the windows webapp gives me a json error
![image](https://user-images.githubusercontent.com/47988/80114573-bdb7b580-8551-11ea-9ac0-fb72f2289bff.png)
![image](https://user-images.githubusercontent.com/47988/80114616-c6a88700-8551-11ea-9068-eacd86ce36f2.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
previous failure
[logs_152.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4523332/logs_152.zip)

failure with debug logging on
[logs_153.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4523351/logs_153.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
Starting: AzureAppServiceSettings
==============================================================================
Task         : Azure App Service Settings
Description  : Update/Add App settings an Azure Web App for Linux or Windows
Version      : 1.163.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
Got service connection details for Azure App Service:'cayers-win-node-test''
Trying to update App Service Application settings. Data: {"WELCOME_TO":"THE_CIRCUS_OF_VALUE","REACT_APP_NAME":"GARBAGE"}
##[error]Error: Application Settings object is not a valid JSON.
Finishing: AzureAppServiceSettings

**Comment by Codebytes** [comment]
I just tried this through the gui "classic" release using the depoy azure web app task:
![image](https://user-images.githubusercontent.com/47988/80116057-80ecbe00-8553-11ea-8de9-4b09ca5ce37f.png)

it was successful and the json looks similar
![image](https://user-images.githubusercontent.com/47988/80116008-703c4800-8553-11ea-8a4c-a641d2eea89f.png)

**Comment by chshrikh** [comment]
1.163.4 is old task, thanks for confirming it is working with Azure App service deploy V4.

**Comment by Codebytes** [comment]
So am I not supposed to be able to use this task in yaml ?
You closed it with very little context on how I am supposed to resolve AzureAppServiceSettings
This doc is from 4/6/2020.  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops#example
And that example wasn't working for me. 
The only difference I see is:
AzureAppServiceSettings@0
vs
AzureAppServiceSettings@1
but yaml editor gives me a warning with AzureAppServiceSettings@0 and the job fails with
  | A task is missing. The pipeline references a task called 'AzureAppServiceSettings' with version '0'. This indicates that the specific task version can not be found. (job 'Deploy', step ''.)20200424.2 |

**Comment by jaime-olivares** [comment]
Same happening for me. Doesn't work for a windows instance.
It is throwing an exception although the json is exactly as the README.

````
Starting: AzureAppServiceSettings
==============================================================================
Task         : Azure App Service Settings
Description  : Update/Add App settings an Azure Web App for Linux or Windows
Version      : 1.163.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
Got service connection details for Azure App Service:'myapp'
Trying to update App Service Application settings. Data: {"X_GATEWAY":"asdfasfd","X_SERVICES":"dummy"}
##[error]Error: Application Settings object is not a valid JSON.
Finishing: AzureAppServiceSettings
````

Why is this issue closed? Is there an alternative task?
