### ISSUE TITLE
UseDotNetV2 doesn't allow rollForward in global.json

### ISSUE THREAD

**Issue by pharring** [microsoft/azure-pipelines-tasks#12750]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: UseDotNetV2

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted Windows-2019
    
## Issue Description

I'm using the UseDotNetV2 task with "Use Global.json" set to true. My global.json is at the root of the repo and the contents are:
```json
{
  "sdk": {
    "version": "3.1.200",
    "rollForward": "latestFeature"
  }
}
```

The "rollForward" property is what I'm adding so that we can use any SDK in the 3.1.x family, newer than 3.1.200. It works fine in Visual Studio 2019.

See https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#globaljson-schema

However, when I tried building in Azure Dev Ops, the UseDotNetV2 task failed with:

```
[error]The global.json at path: 'E:\A\_work\267\s\.git\logs\refs\remotes\origin\dev\pharring\global.json' has the wrong format. For information about global.json, visit here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json. Error while trying to read: SyntaxError: Unexpected number in JSON at position 1
```

It seems like the UseDotNetV2 task doesn't understand the (new?) schema.

### Task logs

[logs_3670856.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4525973/logs_3670856.zip)

### Error logs

```
[error]The global.json at path: 'E:\A\_work\267\s\.git\logs\refs\remotes\origin\dev\pharring\global.json' has the wrong format. For information about global.json, visit here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json. Error while trying to read: SyntaxError: Unexpected number in JSON at position 1
```

**Comment by tejasd1990** [comment]
Hi @pharring, I was not able to repro this issue and the global.json contents you have given worked for me. I suspect some unwanted invisible characters in the file is the reason for the json parse error. Can you share the global.json file you are using in your task?

**Comment by pharring** [comment]
My apologies. This isn't due to the rollForward property after all. The problem was that I'd named the branch "dev/pharring/global.json". When UseDotNetTaskV2 searched recursively for global.json it found a file under the (hidden) .git folder and tried to parse it. Arguably a different bug, but not the one I'm reporting here and easy to work around (rename the branch).

Once again, sorry for the interruption.
