### ISSUE TITLE
Question: AzureFileCopy set different destination filename

### ISSUE THREAD

**Issue by galadril** [microsoft/azure-pipelines-tasks#12760]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureFileCopy

## Environment
- Server - Azure Pipelines
- Agent - Private: 
    
## Issue Description

Is there an option or variabele on the Azure File Copy task to specify a different output filename??

**Comment by aksm-ms** [comment]
No, there is no option to specify different filename after copy to destination folder.

**Comment by aksm-ms** [comment]
Closing this issue, feel free to reopen if you have further queries
