### ISSUE TITLE
vsts-npm-auth needs reauth every day

### ISSUE THREAD

**Issue by akshaybheda** [microsoft/azure-pipelines-tasks#12769]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

## Required Information

The vsts-npm-auth is expiring after 1 day. Tried vsts-npm-auth -c %userprofile%\.npmrc -E 129600 But in the https://xxx.visualstudio.com/_usersSettings/tokens, The validity is 1 day and it also expires in one day. Have to create token daily.
Version v0.37.0.0

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: vsts-npm-auth

**Comment by akshaybheda** [comment]
![image](https://user-images.githubusercontent.com/22575879/80339132-9b88a500-887b-11ea-8027-7283f2226169.png)

**Comment by akshaybheda** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/12703

**Comment by herenhuang** [comment]
Pasting the solution from the DevCommunity link here:

We've pushed a new version of vsts-npm-auth that should mitigate session token expiry problems. Please use vsts-npm-auth v.0.41.0 or greater.

Closing this issue, tho pls reopen if that doesn't fix the problem.
