### ISSUE TITLE
GitActions - Even though file exist, giving no such file or directory error

### ISSUE THREAD

**Issue by saikiran-karumuri-jdas** [microsoft/azure-pipelines-tasks#12778]
Below is the code i`m using to deploy the arm template. and giving "no such file or directory error"

but when i did "ls" its showing the files.

GitActions code:
 - name: list all
        run: ls /home/runner/work/sai-git-actions/sai-git-actions/Templates
      - name: Azure Login
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
              az account show
              az group deployment create --resource-group saiapim --template-file /home/runner/work/sai-git-actions/sai-git-actions/Templates/saiapiservice-products.template.json --parameters /home/runner/work/sai-git-actions/sai-git-actions/Templates/saiapiservice-parameters.json
              az group deployment create --resource-group saiapim --template-file /home/runner/work/sai-git-actions/sai-git-actions/Templates/DevopsKit.api.template.json --parameters /home/runner/work/sai-git-actions/sai-git-actions/Templates/saiapiservice-parameters.json
  

output:

 list all0s
test.json
Run ls /home/runner/work/sai-git-actions/sai-git-actions/Templates
DevopsKit.api.template.json
saiapiservice-parameters.json
saiapiservice-products.template.json
test.json
  Azure Login13s
  Azure CLI script44s

Run azure/CLI@v1
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.0.72
***

ERROR: [Errno 2] No such file or directory: '/home/runner/work/sai-git-actions/sai-git-actions/Templates/saiapiservice-products.template.json'
##[error]Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1588041558027_CONTAINER

**Comment by tejasd1990** [comment]
Hi @saikiran-karumuri-jdas,
If you are using [checkout](https://github.com/actions/checkout#checkout-v2) action, you can use the _$GITHUB_WORKSPACE_ environment variable.
The[Azure CLI](https://github.com/marketplace/actions/azure-cli-action#note) action executes the script inside a container. As the document says,
_"GITHUB_WORKSPACE directory in host is mapped to working directory inside container"_

So using absolute agent paths won't work for you, you should use the environment variable

**Comment by damccorm** [comment]
Hey @saikiran-karumuri-jdas - this repo is for Azure Pipelines tasks issues, not GitHub Actions. If you have an issue with actions please file it in one of the actions repos (e.g. checkout - https://github.com/actions/checkout#checkout-v2). Actions is a different product and doesn't use our tasks
