### ISSUE TITLE
Looking for service principal authentication support

### ISSUE THREAD

**Issue by ygizhitsa** [microsoft/azure-pipelines-tasks#12776]
## Note  
Feature - Service Principal authentication support 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Feature**  
*Type*: Future to support Service Principal authentication

**Enter Task Name**: Add Service Principal logic

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:

**Comment by damccorm** [comment]
Hey @ygizhitsa this repo is mostly for issues/support around existing tasks. To request a new task, please file an issue here - https://developercommunity.visualstudio.com/spaces/21/index.html
