### ISSUE TITLE
tar: Wrote only 8192 of 10240 bytes

### ISSUE THREAD

**Issue by Lemmih** [microsoft/azure-pipelines-tasks#12784]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/lemmih0612/reanimate/_build/results?buildId=595&view=logs&j=3cd902e3-15ce-5f1c-e3e1-2294b8812c43&t=867dc55d-71aa-583f-f01c-ca199bdfa239

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines 8 / Linux stack-nightly

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

The post-job fails for Cache@2. Creating the tar archive fails with error message:

    tar: 0a087c283c344254afef0f53b2ecde70_archive.tar: Wrote only 8192 of 10240 bytes

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

I'm not sure how to do that.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

```
Starting: Cache stack root
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - Linux         [string]
 - ubuntu-latest [string]
 - $(STACK_YAML) [string]
 - stack-root    [string]
 - Linux         [string]
 - version4      [string]
Resolved to: Linux|ubuntu-latest|$(STACK_YAML)|stack-root|Linux|version4
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session c93c276f-68d2-482d-ab48-b5a13f3ef9d4
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `Linux|ubuntu-latest|$(STACK_YAML)|stack-root|Linux|version4`
Information, There is a cache miss.
tar: 0a087c283c344254afef0f53b2ecde70_archive.tar: Wrote only 8192 of 10240 bytes
tar: Error is not recoverable: exiting now
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session c93c276f-68d2-482d-ab48-b5a13f3ef9d4
##[error]Process returned non-zero exit code: 2
Finishing: Cache stack root
```

**Comment by johnterickson** [comment]
For debug logs, follow these instructions: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by Lemmih** [comment]
And then what? How do I attach the logs to this issue?

**Comment by Lemmih** [comment]
[logs_595.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4549495/logs_595.zip)

Ah, I see.

**Comment by jayanta525** [comment]
Any solution to this?

**Comment by johnterickson** [comment]
Are you out of disk space?

**Comment by Lemmih** [comment]
> Are you out of disk space?

I'm using a hosted agent and it fails while saving a snapshot using the built-in caching job. Maybe azure is out of disk space or maybe I've hit a quota or something. I'm not sure how to tell.

**Comment by Lemmih** [comment]
I ran the pipeline again and the issue has gone away. Oh well.

**Comment by Bsode-levi** [comment]
确实是打包文件所属的盘内存空间不足了，我换了一个盘打包成功

**Comment by httran13** [comment]
Hello I need help, im having this same issue but unlike lemmih, my issue isn't going away.

The error is happening at the Post-Job where my cache fails during tar process.

```
Starting: Gradle Cache Load
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - gradle                   [string]
 - "Linux"                  [string]
 - android/build.gradle     [file] --> 50151698D5880B95DE6CC16102F9763B156EEFAE0B24967110D43B9867F63D96
 - android/app/build.gradle [file] --> 6B26307409CC3364A418C5A9496738B1D0CC7EB43C38FC04055915A5FDE31AFA
Resolved to: gradle|"Linux"|9M6iGrx9puyxQcv/qGv9HEm2lcwgLcTo+bJ4WQ98dd0=|TpqRHtxmlNZHwdTXI6cD7xFYoYT9P4E5wZXPCQDJg8I=
Using default max parallelism.
Max dedup parallelism: 192
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 93eb3a79-22c4-4bdb-a569-8ebbb980eba2
Hashtype: Dedup64K
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `gradle|"Linux"|9M6iGrx9puyxQcv/qGv9HEm2lcwgLcTo+bJ4WQ98dd0=|TpqRHtxmlNZHwdTXI6cD7xFYoYT9P4E5wZXPCQDJg8I=`
There is a cache miss.
tar: 99b6c4ebe2844a5b9f65abc4c0c5577d_archive.tar: Wrote only 4096 of 10240 bytes
tar: Error is not recoverable: exiting now
ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 93eb3a79-22c4-4bdb-a569-8ebbb980eba2
##[error]Process returned non-zero exit code: 2
Finishing: Gradle Cache Load
```

**Comment by MO-Lewis** [comment]
## You probably ran out of image space.

Just had this issue too, this was because my runner was running out of space.

I've got a 7.0GB `node_modules` folder (don't ask) due to needing to build react-native from source, and I wanted to cache the whole `node_modules` folder so I don't need to redo the source build. However, before the cache tried to save, I only had 6.3GB of space remaining.

Firstly, you should all check the size of the folder you're trying to cache. 

Try this snippet:
```
- script: |
       echo "SYSTEM SPACE:"
       sudo df -h 
       echo "CURRENT DIR SPACE:"
       sudo du -h --max-depth=1 ./
   displayName: Report remaining space
```

This will tell you how much space you've got left on the runner image, and then how much space your current working directory is using. If the folder you're trying to cache is greater than your remaining space, that's why this error is happening to you.

To free up space, I use a mix of turning off swap files, deleting unnecessary apt packages and deleting unnecessary Docker images. Here's a couple more snippets:

```
- script: |
       sudo swapoff -a
       sudo rm -f /swapfile
       sudo apt clean
       docker rmi $(docker image ls -aq)
       df -h
   displayName: Remove unneeded Docker images

- script: |
       sudo rm -rf /usr/share/dotnet /opt/ghc
   displayName: Free up some more space

- script: |
    sudo apt list --installed
    sudo apt-get install -y apt-transport-https
    sudo apt-get remove google-cloud-cli azure-cli microsoft-edge-stable dotnet-sdk-7.0 \
      dotnet-sdk-6.0 google-chrome-stable firefox powershell mysql-server-core-8.0 \
      linux-azure-6.2-headers-6.2.0-1012
  displayName: Clear unnecessary apt packages
```

You can remove more / less apt packages to your liking. I personally run a command to list them all and show how big those packages are. I then copy this logged info, insert it into Google Sheets, and sort the columns by package size. Then, start working your way down from the biggest packages until you've freed up enough space for your cache command to run.

```
- script: |
        dpkg-query -Wf '${Installed-Size}\t${Package}\n'
   displayName: List installed apt packages
```

All in all, the above saved me 11GB of space, but you can be more thorough than me by removing more apt packages.
