### ISSUE TITLE
Azure Powershell Task v.4.168.0 affect Enable-ContextAutoSave

### ISSUE THREAD

**Issue by KorKiak** [microsoft/azure-pipelines-tasks#12794]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure Powershell  

## Environment
- Server - Azure Pipelines
    
- Agent - Hosted

## Issue Description

In my script I have an Enable-AzContextAutoSave which always work fine. But recently all my new releases and redeployed releases (which succeeded before) were failed. My pipeline configurations were all the same, the script hasn't been touched, I just trigger the pipeline.
I did some investigation and found out that Get-AzContext in my script returned null, including every command that is using the context (e.g. Get-AzSubscription return error message said I have to run Connect-AzAccount).
After a while I realized that the tasks version have just changed from 4.167.0 to 4.168.0 and then the one that failed all my release is the Enable-AzContextAutoSave command.

So I had a look in your repo and found this:
https://github.com/microsoft/azure-pipelines-tasks/commit/e4127e0977a9fd22caf09a53b627bb1263765ba7

**Should there be any notice to the users before rolling out this change??** I understand that this might be a minor change, but it could affect users. I have to spent some times to find the cause of this out-of-nowhere issue and it affected my deployment timeline.

**Comment by chshrikh** [comment]
we will do internal investigation why it got regressed, could you please confirm if you have changed any PS version in task

**Comment by KorKiak** [comment]
I have not changed any configuration in my pipeline task. The task version changed from 4.167.0 to 4.168.0 by itself.

**Comment by 20shivangi** [comment]
@KorKiak The change was made due to security reasons. 
Earlier what was happening : if you have a pipeline with azurepowershell task on a agent and in the same pipeline you add another agent job with same agent and task powershell, it was saving az context as it was not scoped properly. So if you run some az command in powershell task, it was giving correct results which should not be the required behavior.

Due to this security reason, we are scoping the context only for the current process.

**Comment by KorKiak** [comment]
Thanks for your explaination! But can you please explain why the `Enable-AzContextAutoSave` command then ended up not saving anything to the context?
Will `Enable-AzContextAutoSave -Scope Process` work?
