### ISSUE TITLE
[PowershellV2] Powershell 7 errors not being captured correctly unless ErrorView set to NormalView

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azure-pipelines-tasks#12799]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Powershell

## Environment
Hosted (All forms, windows/linux/etc.)

## Issue Description

With Powershell 7, the default `$ErrorView` is now ConciseView. These errors are not being emitted to the log output. I suspect that the parsing of the errors is expecting a certain format/object and conciseview is returning a different object/format

## Troubleshooting

If you set $ErrorView='NormalView' at the top of your script, output is as expected when it was powershell 6.2 and the behavior of Windows Powershell

> azure-pipelines.yaml
> 
> ```yaml
> jobs:
>   - job: job1
>     pool:
>       vmImage: windows-latest
>     steps:
>       - pwsh: |
>           throw "test"
>         failOnStderr: true
>         errorActionPreference: stop
>         condition: always()
>         displayName: ConciseView
>       - pwsh: |
>           $ErrorView = "NormalView"
>           throw "test"
>         failOnStderr: true
>         errorActionPreference: stop
>         condition: always()
>         displayName: NormalView
>       - powershell: |
>           throw "test"
>         failOnStderr: true
>         errorActionPreference: stop
>         condition: always()
>         displayName: PowerShell 5
> ```
> 
> ![image](https://user-images.githubusercontent.com/18499079/76539075-2e11e800-6478-11ea-9629-c8484346ddf6.png)
> 
> ![image](https://user-images.githubusercontent.com/18499079/76539107-3833e680-6478-11ea-83ce-f661a36fe84a.png)
> 
> ![image](https://user-images.githubusercontent.com/18499079/76539137-4124b800-6478-11ea-9abf-b0df8a35ab22.png)

## Recommended Remdiation
Either fix the parsing so that conciseview errors come through correctly, or set NormalView in the script prior to running it.

## References
https://github.com/microsoft/azure-pipelines-agent/issues/2853

## Potentially Relevant Code
https://github.com/microsoft/azure-pipelines-tasks/blob/a9d4ce2a744d9389b3056f83682975cebd8b7937/Tasks/PowerShellV2/powershell.ts#L89
https://github.com/microsoft/azure-pipelines-tasks/blob/a9d4ce2a744d9389b3056f83682975cebd8b7937/Tasks/PowerShellV2/powershell.ps1#L102-L125

**Comment by krokofant** [comment]
@damccorm This will probably be properly fixed by PowerShell 7.0.1

Via this issue: https://github.com/PowerShell/PowerShell/issues/11827
