### ISSUE TITLE
Azure App Service Deploy - Cannot run Powershell script as post deployment script file.

### ISSUE THREAD

**Issue by v-vrusse** [microsoft/azure-pipelines-tasks#12791]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Feature

**Enter Task Name**: Azure App Service Deploy  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: MicrosoftIT, OneITVSO, Releases - Transportation Components

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
    vs2017-win2016

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
I wanted to run a post-deployment powershell script; however, I get an error.  Is it truly not supported?  If so, I would request that it be supported.

![image](https://user-images.githubusercontent.com/62967613/80550936-9a886e00-8976-11ea-958c-bc9eac852c42.png)

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
Error: Unable to run the script on Kudu Service. Error: Error: Invalid script file 'D:\a\r1\a\drop\drop\deployment\setEnvironment.ps1' provided. Valid extensions are .bat and .cmd for windows and .sh for linux

[Insert error from the logs here for a quick overview]

[tasklog_7.log](https://github.com/microsoft/azure-pipelines-tasks/files/4549218/tasklog_7.log)

**Comment by aksm-ms** [comment]
@v-vrusse can you please tell me which web app service type are you using?

**Comment by v-vrusse** [comment]
Web App on Windows

![image](https://user-images.githubusercontent.com/62967613/80607263-28ea0780-89ea-11ea-9c40-23755fa2bb5d.png)

**Comment by aksm-ms** [comment]
Currently only .bat and .cmd files are supported as post deployment scripts for non linux app service types.

**Comment by v-vrusse** [comment]
Is there a way to run a powershell script within the App Service using the Powershell task?
Or do I just need to give up on powershell and switch to a cmd file?

**Comment by aksm-ms** [comment]
Powershell task cannot be used to run script within App service.

**Comment by v-vrusse** [comment]
Thanks for the additional clarification.  Looks like I'm stuck with a cmd file.  Can we get support for powershell post deployment scripts in the future?

**Comment by aksm-ms** [comment]
Please create a bug, we will review it.
