### ISSUE TITLE
AzureAppServiceSettingsV1 reports wrong error-message when updating server-settings

### ISSUE THREAD

**Issue by Debbus72** [microsoft/azure-pipelines-tasks#12795]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureAppServiceSettings

## Environment
- Server - Azure Pipelines
- Agent - Private
- Task version: 1.163.4
   

## Issue Description

In the new task-version 1.163.4 there is a change that wraps 2 statements in a try-catch statement.
[source](https://github.com/microsoft/azure-pipelines-tasks/blob/a01f19014ac282b55124cf3faee6dcc835c52584/Tasks/AzureAppServiceSettingsV1/azurewebappsettings.ts#L60-L66) (note that there are 3 try-catches, for AppSettings, ConnectionStrings & GeneralSettings).
In the catch there is only 1 default error reported (ConfigSettingInvalidJSON), however this only applies to the first statement (`JSON.parse( "settings" )`). Whenever there is an error in the second statement (`appServiceUtility.updateAndMonitorAppSettings`) this is then also reported as "invalid json".

For detail: The issue that we ran into was that the setting on the server was "RemoteURL" where as the new configuration included the setting "RemoteUrl". Applying this resulted in a 409-Conflict because of inconsistent case-sensitivity. The error that we saw in our pipeline for that task was: "##[error]Error: Application Settings object is not a valid JSON."

So maybe there are actually two bugs. But I don't know if the inconsistent case-sensitivity is part of this task.

### Task logs

```
Starting: Set AppSettings to staging slot
==============================================================================
Task         : Azure App Service Settings
Description  : Update/Add App settings an Azure Web App for Linux or Windows
Version      : 1.163.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
Got service connection details for Azure App Service:'<<removed>>'
Trying to update App Service Application settings. Data: { <<removed>> }
##[error]Error: Application Settings object is not a valid JSON.
Finishing: Set AppSettings to staging slot
```

### Azure Activity log
```
{
  "Code": "Conflict",
  "Message": "Parameter with name RemoteUrl already exists.",
  "Target": null,
  "Details": [
    {
      "Message": "Parameter with name RemoteUrl already exists."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "01013",
        "MessageTemplate": "Parameter with name {0} already exists.",
        "Parameters": [
          "EventsApi:Url"
        ],
        "Code": "Conflict",
        "Message": "Parameter with name RemoteUrl already exists."
      }
    }
  ],
  "Innererror": null
}
```

**Comment by eaarora-ms** [comment]
@Debbus72 Thanks for reporting the issue. We will add it to our list of enhancements for the task.
