### ISSUE TITLE
GitHubComment task doesn't accept `Token` connection type

### ISSUE THREAD

**Issue by kohtenko** [microsoft/azure-pipelines-tasks#12806]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GitHubCommentV0  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubCommentV0

## Environment
- Server - Azure Pipelines
   N/A
- Agent - Private: 
    N/A

## Issue Description
The GitHubComment task doesn't accept `Token` type of connection, although it reads the `Token` scheme in its source code. I believe it's a matter of updating input parameters restriction.
[Include task name(s), screenshots and any other relevant details]
<img width="453" alt="Screen Shot 2020-04-30 at 3 47 19 PM" src="https://user-images.githubusercontent.com/800103/80752915-62aa3380-8afa-11ea-8d3c-cc0a58344ce7.png">

**Comment by alexmaslovtr** [comment]
Experiencing this as well

**Comment by kohtenko** [comment]
@ammohant @ds-ms can this be prioritised? This seems like an extremely simple fix. I'd suggest a PR myself, but I have no way of testing it

**Comment by kohtenko** [comment]
@ds-ms Any idea when this fix is going to be available to general public?

**Comment by kohtenko** [comment]
@ds-ms It's been three weeks now since the change was merged, but I still can't see it being deployed and available.
