### ISSUE TITLE
Recent builds failing frequently with VsTest CodeCoverage Shim Method not found

### ISSUE THREAD

**Issue by Adebeer** [microsoft/azure-pipelines-tasks#12808]
*Type*: BUG

**Enter Task Name**: VsTest 

## Environment
Server:  
Azure Pipelines

alsdevelopmentna.visualstudio.com/AngleNextGen%20Core%20Product%20Pipeline

Build: AnglePlus-Dev, 20200501.1
Pool: Azure Pipelines
Image: windows-2019
Agent: Hosted Agent

## Issue Description

Below error seem to have started few days ago - have to repeat builds 2-3 times WITHOUT changes until it succeeds. Occurs during VsTest code coverage shim process - unable to find method (probably reflection based).

[logs_62888.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4562122/logs_62888.zip)

### Error logs

```
##[error]An exception occurred while invoking executor 'executor://xunit/VsTestRunner2/netcoreapp': Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.546367543__coverage_runtime_method__26351_18082__(UInt64)'.
##[debug]Processed: ##vso[task.logissue type=error;]An exception occurred while invoking executor 'executor://xunit/VsTestRunner2/netcoreapp': Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.546367543__coverage_runtime_method__26351_18082__(UInt64)'.
Microsoft (R) Coverage Collection Tool Version 16.0.30319.200
```

**Comment by ShreyasRmsft** [comment]
Did the testplatform or Coverage Collection Tool Version change around the time you started noticing these issues?

**Comment by Adebeer** [comment]
@ShreyasRmsft 

I haven't noticed any differences in this version recently - the code coverage tool version was 16.0.30319.200 even mid last month.

Thanks for investigating

**Comment by Adebeer** [comment]
This issue is still occurring for me - any update on this?

**Comment by anshi03** [comment]
@Adebeer  Can you please share your pipeline or small demo project for this ?

**Comment by Adebeer** [comment]
@anshi03 
Here's a link to our pipeline [build](https://alsdevelopmentna.visualstudio.com/AngleNextGen%20Core%20Product%20Pipeline/_build/results?buildId=62850&view=results)

Not sure if it matters, but late last week (20th May) I upgraded some nuget packages - specifically, Microsoft.NET.Test.Sdk from 16.5.0 to 16.6.1 - I don't recall seeing it since then but we may simply not have pushed through enough builds.

**Comment by anshi03** [comment]
@Adebeer  As a wokaround for this issue , please set  adapther Paths in your Vstest Task to some dummy folder in your repo which does not have any dlls (any child folder also should not have dll).
Basically any folder with only code files or something like that.
![image](https://user-images.githubusercontent.com/32239255/83015866-b8f98c00-a03e-11ea-82af-b2148265c0f7.png)
