### ISSUE TITLE
Azure App Service Deploy - Add support for Powershell as post deployment script 

### ISSUE THREAD

**Issue by v-vrusse** [microsoft/azure-pipelines-tasks#12819]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service Deploy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: MicrosoftIT, OneITVSO, Releases - Transportation Components

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name  vs2017-win2016

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
Powershell has become one of if not the main scripting language on Windows and with Azure.  However as denoted in #12791, a Powershell script cannot be run as a post-deployment script using the Azure App Service Deploy task when deploying to a Windows-based Azure App Service.

I'm opening this issue to request that Powershell support be added to post-deployment scripts as @aksm-ms [requested.](https://github.com/microsoft/azure-pipelines-tasks/issues/12791#issuecomment-623248714)
[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by kmkumaran** [comment]
@nadesu , @chshrikh , @N-Usha for follow up

**Comment by justinpenguin45** [comment]
nothing - nice
