### ISSUE TITLE
App Center iOS Test Run fails: Unable to find test runner app

### ISSUE THREAD

**Issue by sethi-ishmeet** [microsoft/azure-pipelines-tasks#12814]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Xcode & App Center Test 

## Environment
- Server - Azure Pipelines 
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Account Name: ishmeet@simplifiedautomation.ca / Simplified Automation Inc.
Team Project Name: PET Mobile
Build Definition Name: PR Build - 2 / #20200503.20

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: macOS-10.15

## Issue Description
I have a Xcode build and test task. I created the Xcode build-for-testing task as recommended [here](https://docs.microsoft.com/en-us/appcenter/test-cloud/vsts-plugin#xcuitest) with Arguments `-derivedDataPath DerivedData` in Advanced section. 

![Screen Shot 2020-05-03 at 10 26 42 PM](https://user-images.githubusercontent.com/17765279/80920384-2b9f8080-8d8d-11ea-9f4d-9c17e0ff3130.png)

And in Prepare Tests section in App Center Test Task I have set the Build directory, again, as shown in the above URL. 
![Screen Shot 2020-05-03 at 10 27 49 PM](https://user-images.githubusercontent.com/17765279/80920408-538ee400-8d8d-11ea-88cb-08fdb7004d64.png)

When I run this task, I get the following error:
```
 Unable to find test runner app within /Users/runner/runners/2.166.4/work/1/s/DerivedData/Build/Products/Debug-iphoneos/
```

### Task logs
[App center Log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4570998/App.center.Log.txt)
[Xcode Build Log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4570999/Xcode.Build.Log.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by EzzhevNikita** [comment]
Hi, @sethi-ishmeet! Is this issue still actual for you?

**Comment by sethi-ishmeet** [comment]
@EzzhevNikita No, thank you. I don't remember how, but this is resolved for now.
