### ISSUE TITLE
AzureCLIV2 allow hiding 'az login' output

### ISSUE THREAD

**Issue by qetza** [microsoft/azure-pipelines-tasks#12831]
Currently when we use the AzureCLI v2 task it is doing automatically for us the `az login` command. This command returns an array of all the subscription the logged in user has access to.

Our service principal has access to hundreds of subscriptions and this is polluting our logs as we get almost 5000 lines of logs just for this output.

It would be great to have a parameter to disable `az login` output; if this parameter is set then when calling `az login` the parameter `-o none` would be added.

**Comment by georambo** [comment]
+1 this request.  There should be some way to llimit the output.

**Comment by oysteinje** [comment]
+1

**Comment by ransagy** [comment]
stale or not, i wonder if this can be looked at for a quick win. In the sea of other tasks in our pipelines, this is the only one that spams the log with zero control.

**Comment by amitaesthetic** [comment]
+1

**Comment by oscarare** [comment]
totally needed +1

**Comment by ilmax** [comment]
Love how DevOps team is ignoring this, they clearly don't use it themselves.

**Comment by ChrisPolewiak** [comment]
+1
