### ISSUE TITLE
Static Site deployment

### ISSUE THREAD

**Issue by baoduy** [microsoft/azure-pipelines-tasks#12836]
Hi, I got this issue when deploying a static site to Azure Storage. using version 3 or 4-Preview. it is fine with v2.

`##[error]Upload to container: '$web' in storage account: 'xxx' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.' For more info please refer to https://aka.ms/azurefilecopyreadme`

**Comment by chshrikh** [comment]
please provide detailed logs,

**Comment by eaarora-ms** [comment]
@baoduy  If you are still facing this issue, can you please set the variable "System.debug" with value "true". Redeploy and share pipeline zip logs here.

**Comment by eaarora-ms** [comment]
Also, can you try deploying via CLI as a workout:

> az storage blob upload-batch --account-name myaccount -s . -d $web

**Comment by baoduy** [comment]
@eaarora-ms sure let me try

**Comment by eaarora-ms** [comment]
@baoduy Sure, Please do let us know the results.

**Comment by eaarora-ms** [comment]
@baoduy Can you please let me know if you were able to try the workaround?

**Comment by eaarora-ms** [comment]
Closing due to no response from the customer. Please comment to re-open the issue.
