### ISSUE TITLE
Swap Slots Exceptions - Bad Request

### ISSUE THREAD

**Issue by alohaninja** [microsoft/azure-pipelines-tasks#12835]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Unable to Swap Slots - HTTP 400 Bad Request

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: tenant: azurecom, team project: ACOM, release id: 49840

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Win Server 2016, Agent Version: 2.165.2 

## Issue Description

> 2020-05-06T17:16:49.3531383Z ##[error]Error: Failed to swap App Service 'xxxx' slots - 'staging' and 'production'. Error: BadRequest - Cannot swap slots for site 'xxx' because the allocation of VM instances for 'staging' slot has changed during the swap process. Please retry the swap operation. (CODE: 400)

Retrying the operation eventually allowed it to succeed - but there is no retry support in Azure Pipelines to make this more resilient. Curious if anyone else has run into this issue before. Is this related to horizontal elastic scaling?

**Comment by damccorm** [comment]
Hey @alohaninja - is this an issue with a specific task? If so, could you provide the task you're seeing this behavior in? If not, please close here and open an issue at https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by alohaninja** [comment]
@damccorm  - yes this is a specific task (_[just followed this similar example](https://github.com/microsoft/azure-pipelines-tasks/issues/5566)_) - sorry for the confusion. 

**Task**: [Azure App Service](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureAppServiceManageV0/README.md)
![image](https://user-images.githubusercontent.com/26234626/81333999-33e01000-905a-11ea-87f5-5f038737f34b.png)

**Action**: Swap Slots
![image](https://user-images.githubusercontent.com/26234626/81333938-1c088c00-905a-11ea-9322-0b905d2cfc22.png)

**Comment by damccorm** [comment]
Thanks - I'll get it routed to the right team

**Comment by eaarora-ms** [comment]
@alohaninja Can you please let me know if you are facing this issue everytime you try to swap slot or it happened just once?

**Comment by alohaninja** [comment]
@eaarora-ms - this happens across multiple datcenters and is intermittent. It's happened several times this week so we figured we would post to see if others are experiencing this. 

 We swap numerous times per day using multi agent config task for global deploys - it's inconsistent but when it happens it makes for a painful user experience as our regions are serving up inconsistent versions. We are elastically scaling our app service instances horizontally based on RPS - suspect these two operations are colliding. 

Retrying the failed swap task fixes it - we should just add retrying logic (e.g.polly/exponential back-off) to this task as kicking it again seems to allow the swap request to succeed.

**Comment by eaarora-ms** [comment]
@alohaninja  Yes it might be possible that the two operations are colliding with each other since the retry operation is successful. We will add the retry logic as a feature request in our list of enhancements. Thanks for reporting this.

**Comment by jkonecki** [comment]
I'm runing into the same problem, but in my case it's happening every time I try to swap slots on different AppServices (although they use the same App Service Plan).

The same error appears when trying to swap though pipeliens (standard task) and also through the Portal.

![image](https://user-images.githubusercontent.com/1775247/82438039-54638d80-9a90-11ea-851f-fe40b5242ca8.png)

This started happening yesterday and I can reproduce it every time I swap.

**Comment by jkonecki** [comment]
I've stopped some of the slots - didn't help.
I've finally managed to swap after scaling App Service plan up from S1 to S2. 

@eaarora-ms please reclasify this issue as a bug. I'm happy to provide more info if needed.

**Comment by jkonecki** [comment]
The issue has now disappeared.

**Comment by Roshan-Kumar-Microsoft** [comment]
@jkonecki  Please let us know if you are still facing this issue .
