### ISSUE TITLE
Github not picking up jobs results

### ISSUE THREAD

**Issue by PhucNgo1711** [microsoft/azure-pipelines-tasks#12830]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

## Environment
- Server - Azure Pipelines
        
- Agent - Hosted and Private
   
## Issue Description

My repo PRs are not picking up the jobs results from Azure Pipelines. When the jobs have finished successfully on Azure, the CI/CD checks on the PRs still show that the jobs are still building.

I didn't get a chance to take a screenshot but will update this ticket the next time this happens.

**Comment by damccorm** [comment]
Hey @PhucNgo1711 this repo is for issues with specific tasks - since this is an issue with the larger service, please file it at https://developercommunity.visualstudio.com/spaces/21/index.html
