### ISSUE TITLE
Deploy jar to virtual application not using specified physical path

### ISSUE THREAD

**Issue by AltarBeastiful** [microsoft/azure-pipelines-tasks#12843]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4  

## Environment
- Azure Pipelines
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Agent machine name: 'WIN-3R7VL9VDHJQ'
Current agent version: '2.166.4'
Current image version: '20200430.2'
 ReleaseId=1544, TeamProjectId=a139cb74-e3ed-4b6b-8fce-e49dd5c510f8
## Issue Description
I've setup 2 virtual application on my azure webapp to host my spring boot backend on `/api` and serve my angular front-end on `/` from the same web app:
![image](https://user-images.githubusercontent.com/3317699/81329609-1da87300-909f-11ea-9a72-06fd79eb0a40.png)

I've setup deploy of the backend on the virtual application `/api` :

But when I launch the deploy, the jar gets installed to the root `site/wwwroot/` not `site/api/wwwroot`.
Is there something i'm missing in the configuration ? 
Note I'm using the generated web.config

## Troubleshooting
After deploy I still get my .jar in `site/wwwroot` along with the generated web.config
I was expecting it to be in `site/wwwroot/api`

**Comment by eaarora-ms** [comment]
@AltarBeastiful Can you please make sure you're giving virtual application name in the task and share your pipeline logs by setting "system.debug = true" in the pipeline variables.

**Comment by eaarora-ms** [comment]
@AltarBeastiful  Please provide us with the logs to help us debug the issue further.

**Comment by AltarBeastiful** [comment]
Fixed it by switching from deploying a single jar file to deploying a folder containing the jar and the web.config needed.

I guess that make sense as it won't have worked without the web.config
