### ISSUE TITLE
DownloadGitHubNugetPackageV1 fails to restore all NuGet packages, even though it shouldn't even be trying

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-tasks#12845]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadGitHubNugetPackageV1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadGitHubNugetPackageV1

## Environment
- Server - [Azure Pipelines](https://dev.azure.com/yellowcounter/Swashbuckle.AspNetCore.SwaggerUI.Standalone/_build/results?buildId=673&view=results)

- Agent - Hosted:  windows-latest

## Issue Description

When downloading a GitHub Package, it fails to download packages from NuGet.org.

```yaml
- task: DownloadGitHubNugetPackage@1
  inputs:
    packageName: 'MisinformedDNA/MisinformedDNA.Swashbuckle.AspNetCore.AzureFunctions'
    version: '2.0.2-prerelease'
    externalFeedCredentials: GitHubPackages
```

results in 

> info : Adding PackageReference for package '***.Swashbuckle.AspNetCore.AzureFunctions' into project 'd:\a\1\Nuget\dotnet\tempCsproj_672.csproj'.
> warn : --no-restore|-n flag was used. No compatibility check will be done and the added package reference will be unconditional.
> info : PackageReference for package '***.Swashbuckle.AspNetCore.AzureFunctions' version '2.0.2-prerelease' added to file 'd:\a\1\Nuget\dotnet\tempCsproj_672.csproj'.
> "C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\Nuget\dotnet\tempCsproj_672.csproj --configfile d:\a\1\Nuget\dotnet\nuget.config --no-cache --verbosity minimal
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : warning NU1603: ***.Swashbuckle.AspNetCore.AzureFunctions 2.0.2-prerelease depends on Microsoft.AspNetCore.Mvc.Core (>= 2.1.3) but Microsoft.AspNetCore.Mvc.Core 2.1.3 was not found. An approximate best match of Microsoft.AspNetCore.Mvc.Core 2.2.0 was resolved.
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Http. No packages exist with this id in source(s): github
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : error NU1101: Unable to find package Swashbuckle.AspNetCore.Swagger. No packages exist with this id in source(s): github
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : error NU1101: Unable to find package Swashbuckle.AspNetCore.SwaggerGen. No packages exist with this id in source(s): github
>   Restore failed in 22.69 sec for d:\a\1\Nuget\dotnet\tempCsproj_672.csproj.
> ##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
> ##[error]Package failed to restore
> 

So it says "--no-restore|-n flag was used", but then it appears to be trying a restore anyway, causing an error since the other packages are on nuget.org, not GitHub. Also, it says "No packages exist with this id in source(s): github", but I don't have a github source set up (at least in this latest attempt).

I've played around with NuGetAuthenticate, dotnet restore, nuget.config, etc, but I haven't been able to get anything to work.

Also note that the input `externalFeedCredentials` does not show up in the editor (but I determined that it needed to be a GitHub service connection):

![image](https://user-images.githubusercontent.com/1784452/81345031-664f3480-907d-11ea-9249-16cce939e63a.png)

### Task logs

[logs_673.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4595850/logs_673.zip)

### Error logs

> info : Adding PackageReference for package '***.Swashbuckle.AspNetCore.AzureFunctions' into project 'd:\a\1\Nuget\dotnet\tempCsproj_672.csproj'.
> warn : --no-restore|-n flag was used. No compatibility check will be done and the added package reference will be unconditional.
> info : PackageReference for package '***.Swashbuckle.AspNetCore.AzureFunctions' version '2.0.2-prerelease' added to file 'd:\a\1\Nuget\dotnet\tempCsproj_672.csproj'.
> "C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\Nuget\dotnet\tempCsproj_672.csproj --configfile d:\a\1\Nuget\dotnet\nuget.config --no-cache --verbosity minimal
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : warning NU1603: ***.Swashbuckle.AspNetCore.AzureFunctions 2.0.2-prerelease depends on Microsoft.AspNetCore.Mvc.Core (>= 2.1.3) but Microsoft.AspNetCore.Mvc.Core 2.1.3 was not found. An approximate best match of Microsoft.AspNetCore.Mvc.Core 2.2.0 was resolved.
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Http. No packages exist with this id in source(s): github
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : error NU1101: Unable to find package Swashbuckle.AspNetCore.Swagger. No packages exist with this id in source(s): github
> d:\a\1\Nuget\dotnet\tempCsproj_672.csproj : error NU1101: Unable to find package Swashbuckle.AspNetCore.SwaggerGen. No packages exist with this id in source(s): github
>   Restore failed in 22.69 sec for d:\a\1\Nuget\dotnet\tempCsproj_672.csproj.
> ##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
> ##[error]Package failed to restore

**Comment by romil07** [comment]
This task is not supposed to be used for packages from Nuget.org. It is meant for only packages that live in GitHub.
If you want to use packages from Nuget.org, use the generic Nuget task NuGetCommandV2.

Are you trying to use this as part of yaml pipeline?

**Comment by MisinformedDNA** [comment]
Right, I'm trying to install a package from GitHub, but it is trying to restore dependent packages that are _not_ on GitHub. 

And yes, this is part of a YAML pipeline. (YAML snippet, logs and build link are included in the OP.)
