### ISSUE TITLE
[UniversalPackages] Publish succeeds with 2 random guids

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#12847]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UniversalPackages  

## Environment
- Server - Azure Pipelines
https://dev.azure.com/devopsmkb/Multivers/_build/results?buildId=19708&view=results  

- Agent - Hosted 
```
Pool: Azure Pipelines
Image: windows-latest
Agent: Hosted Agent
Started: Today at 10:12 AM
Duration: 2m 1s
```

## Issue Description

Using the following YAML:
```
- task: UniversalPackages@0
  condition: and(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')), ne(variables.Build.Reason, 'PullRequest'))
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)\sme-resxsync\bin\Release'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '81dea1dd-cac5-4d61-81a3-b2e7ff0c64bf/7438584b-8726-4249-a331-a7b2745babe1'
    vstsFeedPackagePublish: 'sme-resxsync'
    versionOption: 'patch'
```

The Git repo with this pipeline was migrated from one account to another, the GUIDs above have no meaning in the new account. Project `81dea1dd-cac5-4d61-81a3-b2e7ff0c64bf` does not exist.
Feed `7438584b-8726-4249-a331-a7b2745babe1` does not exist.

I'd expect the build to fait on the missing target peed, but lo and behold:

The build succeeds without any issues and says it has published its packages somewhere. In the Project-level-feed with the name of the Project to be exact. The correct GUIDs for that feed are:

```
514f8a3e-5a1a-4502-b236-2c7abd5d0516/116c2548-4364-48b3-bf7b-70a619dd785
```

Expected outcome:

 * Build fails
 * No packages are published

Observed outcome:

 * Build succeeds
 * Packages are published to the wrong feed

### Task logs

```
Starting: UniversalPackages
==============================================================================
Task         : Universal packages
Description  : Download or publish Universal Packages
Version      : 0.168.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
SYSTEMVSSCONNECTION exists true
Found tool in cache: artifacttool 0.2.128 x64
SYSTEMVSSCONNECTION exists true
Publishing package: sme-resxsync, version: 0.0.1 using feed id: ff9c1e5c-2c23-7652-b3a8-55f5b2652ba0, project: Multivers
C:\hostedtoolcache\windows\artifacttool\0.2.128\x64\ArtifactTool.exe universal publish --feed ff9c1e5c-2c23-7652-b3a8-55f5b2652ba0 --service https://dev.azure.com/devopsmkb/ --package-name sme-resxsync --package-version 0.0.1 --path d:\a\1\s\sme-resxsync\bin\Release --patvar UNIVERSAL_PUBLISH_PAT --verbosity None --description "" --project Multivers
{"@t":"2020-05-08T08:14:55.5898022Z","@m":"ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 24e89241-0ab2-4adf-81e0-fc086814d16a","@i":"73e10d3a","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.589Z"}
{"@t":"2020-05-08T08:14:55.6790226Z","@m":"Ensuring that the package does not yet exist...","@i":"40e01e14","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.679Z"}
{"@t":"2020-05-08T08:14:55.7963714Z","@m":"Package does not yet exist","@i":"c781eca5","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.796Z"}
{"@t":"2020-05-08T08:14:55.7979494Z","@m":"Pushing content...","@i":"3aa40378","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.797Z"}
{"@t":"2020-05-08T08:14:55.8130177Z","@m":"DedupManifestArtifactClient will correlate http requests with X-TFS-Session 24e89241-0ab2-4adf-81e0-fc086814d16a","@i":"efc5a271","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.813Z"}
{"@t":"2020-05-08T08:14:55.8513935Z","@m":"61 files to be processed in 1 groups.","@i":"88bd2933","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.851Z"}
{"@t":"2020-05-08T08:14:55.9840454Z","@m":"61 out of 61 files processed","@i":"bb163468","ProcessedFiles":61,"TotalFiles":61,"EventId":{"Id":1,"Name":"ProcessingFiles"},"SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.984Z"}
{"@t":"2020-05-08T08:14:55.9866198Z","@m":"Processed 61 files from d:\\a\\1\\s\\sme-resxsync\\bin\\Release successfully.","@i":"cdd530db","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:55.986Z"}
{"@t":"2020-05-08T08:14:56.0379889Z","@m":"Uploading 61 files from: d:\\a\\1\\s\\sme-resxsync\\bin\\Release","@i":"a101c503","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.037Z"}
{"@t":"2020-05-08T08:14:56.0428752Z","@m":"Uploaded 0.0 MB out of 2.7 MB.","@i":"4fe48f75","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.042Z"}
{"@t":"2020-05-08T08:14:56.3587759Z","@m":"Uploaded 2.7 MB out of 2.7 MB.","@i":"62962987","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.358Z"}
{"@t":"2020-05-08T08:14:56.3588649Z","@m":"Upload completed.","@i":"f4adb1af","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.358Z"}
{"@t":"2020-05-08T08:14:56.3649965Z","@m":"\r\nUpload statistics:\r\nTotal Content: 2.7 MB\r\nPhysical Content Uploaded: 0.0 MB\r\nLogical Content Uploaded: 0.0 MB\r\nCompression Saved: 0.0 MB\r\nDeduplication Saved: 2.7 MB\r\nNumber of Chunks Uploaded: 1\r\n","@i":"28ad78c4","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.364Z"}
{"@t":"2020-05-08T08:14:56.3799297Z","@m":"Content pushed","@i":"a2f90a5e","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.379Z"}
{"@t":"2020-05-08T08:14:56.3828158Z","@m":"Adding package...","@i":"183e7e34","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:56.382Z"}
{"@t":"2020-05-08T08:14:57.6586669Z","@m":"Added package","@i":"81e6a149","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:57.658Z"}
{"@t":"2020-05-08T08:14:57.6812426Z","@m":"Success","@i":"1d9af52f","SourceContext":"ArtifactTool.Commands.UPackPublishCommand","UtcTimestamp":"2020-05-08 08:14:57.681Z"}
{"SuperRootId":"14EEC90CB71A99D2A6A013392DA1F721656E94339BA2353A8788191E048EE31A02","ManifestId":"3F2CB876F453D85A0AE041E2A413416A2A5ECF13E8E4E06FF538FD3F952AA38701","Description":"null"}
Finishing: UniversalPackages
```

**Comment by jmyersmsft** [comment]
I'm not sure how, but our logs indicate the only publishes with that package name actually did publish to the correct feed (116c2548-4364-48b3-bf7b-70a619dd785c in project 514f8a3e-5a1a-4502-b236-2c7abd5d0516)

**Comment by jessehouwing** [comment]
I don't know how either. The first few build must have failed, but clearly
didn't.

**Comment by jmyersmsft** [comment]
Was any of this done by "rename" or "move" actions, or is all the new stuff logically independent of all the old stuff?

**Comment by jessehouwing** [comment]
Git clone --mirror
Git push --mirror
Pipelines, new pipeline, point to get repo
Save & run

**Comment by jessehouwing** [comment]
The source account is

Unit4.visualstudio.com/SME

**Comment by jmyersmsft** [comment]
Could you try a few URLs for me in a web browser?
1. https://pkgsprodsu3weu.pkgs.visualstudio.com/A47f96b3c-3739-4d80-afc3-9271a07ce4de/Multivers/_packaging/ff9c1e5c-2c23-7652-b3a8-55f5b2652ba0/upack/packages/sme-resxsync/versions/0.0.1?intent=FetchMetadataOnly
1. https://pkgs.dev.azure.com/devopsmkb/Multivers/_packaging/ff9c1e5c-2c23-7652-b3a8-55f5b2652ba0/upack/packages/sme-resxsync/versions/0.0.1?intent=FetchMetadataOnly
1. https://pkgsprodsu3weu.pkgs.visualstudio.com/A47f96b3c-3739-4d80-afc3-9271a07ce4de/Multivers/_packaging/ff9c1e5c-2c23-7652-b3a8-55f5b2652ba0/nuget/v3/index.json
1. https://pkgsprodsu3weu.pkgs.visualstudio.com/A47f96b3c-3739-4d80-afc3-9271a07ce4de/Multivers/_packaging/116c2548-4364-48b3-bf7b-70a619dd785c/upack/packages/sme-resxsync/versions/0.0.1?intent=FetchMetadataOnly
1. https://pkgs.dev.azure.com/devopsmkb/Multivers/_packaging/116c2548-4364-48b3-bf7b-70a619dd785c/upack/packages/sme-resxsync/versions/0.0.1?intent=FetchMetadataOnly
1. https://pkgsprodsu3weu.pkgs.visualstudio.com/A47f96b3c-3739-4d80-afc3-9271a07ce4de/Multivers/_packaging/116c2548-4364-48b3-bf7b-70a619dd785c/nuget/v3/index.json
1. https://pkgsprodsu3weu.pkgs.visualstudio.com/A47f96b3c-3739-4d80-afc3-9271a07ce4de/Multivers/_packaging/5bfc4c54-3cf0-79c1-bbaa-dbfaebce6a44/upack/packages/sme-resxsync/versions/0.0.2?intent=FetchMetadataOnly
1. https://pkgs.dev.azure.com/devopsmkb/Multivers/_packaging/5bfc4c54-3cf0-79c1-bbaa-dbfaebce6a44/upack/packages/sme-resxsync/versions/0.0.1?intent=FetchMetadataOnly
1. https://pkgsprodsu3weu.pkgs.visualstudio.com/A47f96b3c-3739-4d80-afc3-9271a07ce4de/Multivers/_packaging/5bfc4c54-3cf0-79c1-bbaa-dbfaebce6a44/nuget/v3/index.json

I'd like to know whether the response looks like data or looks like an error, and for the index.json ones, if they succeed, the value of the @id property in the object containing "@type":"VssFeedId"

**Comment by jmyersmsft** [comment]
ok, nevermind on that. I think I know approximately what's going on. The wrong guids in the URLs are actually "provenance sessions" - fake feeds that just help us associate some metadata about the build with the upload. There's still a bug, but I think it's in the actual task where it attempts to resolve the GUIDs to names. Still don't know why *that*'s picking the wrong feed instead of failing, but I don't think anything is going to the wrong feed from the server's perspective

**Comment by jessehouwing** [comment]
So much fun with guids and resolving madness.
