### ISSUE TITLE
Powershell inline task throws 'Convert-FromJson' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by henry-padilla** [microsoft/azure-pipelines-tasks#12842]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/PowerShell

## Environment
- Server - Azure Pipelines
https://wkaxcess.visualstudio.com/Axcess/_build/results?buildId=154953&view=results

- Agent - Hosted
    Queue: 'windows-latest'
## Issue Description
I am trying to get the output from an ARM template. The variable gets set and I can write it out to the logs. 
When I try to convert it to json I get an error: 
Convert-FromJson : The term 'Convert-FromJson' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.

### Task logs

[logs_154953.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4594819/logs_154953.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment]
Hey @henry-padilla could you try adding `Import-Module Microsoft.PowerShell.Utility` to the start of your script - https://stackoverflow.com/questions/22256706/running-powershell-script-in-c-sharp-converttojson-error

**Comment by henry-padilla** [comment]
It's already there.
I even moved it to the second line (after $PSVersionTable) and it made no impact.

**Comment by damccorm** [comment]
Oh, I see the issue. The correct command is `ConvertFrom-Json`, not `Convert-FromJson`

**Comment by henry-padilla** [comment]
That can't be it.
Please don't let that be it.
Please, please, please, plea... crap.
That was it.

Please close this (and don't tell anyone. Just between you and me).

**Comment by damccorm** [comment]
Your secret is safe with me 😉

**Comment by phatcher** [comment]
Just did the same :blush:
