### ISSUE TITLE
Add a "hide all output" feature to Kubernetes@1 task

### ISSUE THREAD

**Issue by tony-box** [microsoft/azure-pipelines-tasks#12852]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Kubernetes@1

- Agent: Hosted
    
## Issue Description

Please include an additional option under the Advanced -> outputFormat to include "No output"

If you are creating a k8s secret, there is no way to hide the output from the ADO console as the default option is set to '-o json'. Can we please add another parameter option to hide all output?

**Comment by koushdey** [comment]
@tony-box: This feature will take time to roll out. As a work around you can try putting `outputFormat: ''` that should do the work until the feature rolls out.
