### ISSUE TITLE
Publish Test Results - not working on docker hosted agent

### ISSUE THREAD

**Issue by jjburr** [microsoft/azure-pipelines-tasks#12863]
**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: Publish Test Results Task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
- Agent - Hosted or Private: Private servercore:ltsc2019  v2.166.4

## Issue Description

When trying to upload NUnit test results on a docker hosted agent (built using the example here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops) the tasks exits without uploading the report file or showing any error.

When using a hosted agent the upload works fine

**Comment by navin22** [comment]
@jjburr Can you try passing the searchFolder input, like in issue https://github.com/microsoft/azure-pipelines-tasks/issues/10072

**Comment by jjburr** [comment]
Hi Narin

We are running with a search folder defined.

However no results are uploaded.

On 15/05/2020, at 10:26 PM, Navin <notifications@github.com> wrote:

﻿

This message originated from outside the company.






@jjburr<https://github.com/jjburr> Can you try passing the searchFolder input, like in issue #10072<https://github.com/microsoft/azure-pipelines-tasks/issues/10072>

**Comment by jjburr** [comment]
I should add that the task doesn’t fail, it exits without error in this case but also doesn’t upload the test results.

On 16/05/2020, at 4:44 PM, Joe Burrows <joe.burrows@cireson.com> wrote:

﻿
Hi Narin

We are running with a search folder defined.

However no results are uploaded.

On 15/05/2020, at 10:26 PM, Navin <notifications@github.com> wrote:

﻿

This message originated from outside the company.






@jjburr<https://github.com/jjburr> Can you try passing the searchFolder input, like in issue #10072<https://github.com/microsoft/azure-pipelines-tasks/issues/10072>

**Comment by navin22** [comment]
@jjburr Can you please share the debug logs ? In that we can see what folder the task is searching for. So  based on that we can take our task. If possible point me to your pipeline, so I can check the defn. and Logs.

**Comment by jjburr** [comment]
@navin22 

Here is the task (Which works on a normal agent just not on a docker agent)

![image](https://user-images.githubusercontent.com/31635161/83084048-f2cca000-a0db-11ea-9026-a1c9acc1a832.png)

Also ive attached the debug logs.
[debugLogs-publishresults.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4692496/debugLogs-publishresults.txt)

Also to confirm the results.xml does exist:
![2](https://user-images.githubusercontent.com/31635161/83084133-34f5e180-a0dc-11ea-9287-31aeeb02f60b.png)

**Comment by navin22** [comment]
@jjburr Looks like invoking an EXE in container is causing an issue. Before running the pipeline can you set this as pipeline variable "PublishTestResults.OverrideExeFlow = true" and then try your pipeline ?

**Comment by jjburr** [comment]
@navin22 that works as a workaround - will i have to set this on all pipelines that use docker agents?

**Comment by navin22** [comment]
@jjburr Yeah, please use this as a workaround for all pipelines using docker agents in windows.  Until we come up with permanent fix.

**Comment by upadhyayap** [comment]
Publish test results task is not fully supported on docker based agents. It can be used with the workaround mentioned. you can suggest about this feature in [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by suyash691** [comment]
Closing this issue as the workaround provided has solved the problem
