### ISSUE TITLE
Task Docker@2 : Feature request for supporting user provided labels for Docker Image build

### ISSUE THREAD

**Issue by prabdeb** [microsoft/azure-pipelines-tasks#12864]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Docker@2  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private: Hosted (ubuntu-18.04)

## Issue Description

Feature request for supporting user provided labels for Docker Image build. This will enable users to pass additional metadata to docker images in addition to the default labels attached during docker build

**Comment by ds-ms** [comment]
You can use the `arguments` input right? You'll have to use `build` and `push` separately to provide custom label info.

**Comment by prabdeb** [comment]
@ds-ms Yes, I mainly wanted to avoid having build and push separate

**Comment by sonayak** [comment]
@prabdeb Thanks for coding the feature. The code looks good. 
Sorry for the delayed response. We discussed about the ask internally. Docker build command has a lot of arguments. Supporting all as inputs will make the task very complex to use. Also the required ask can be fulfilled by build and push tasks.  So we don't want to add another input to the task for the time being. But if we find that a good number of users need the feature, then we will revisit our decision.
