### ISSUE TITLE
Docker task (build) does not add pipeline metadata labels to all images created using dockerfile

### ISSUE THREAD

**Issue by nachiketrss** [microsoft/azure-pipelines-tasks#12867]
## Required Information

**Bug**  
*Type*: Docker task (build) does not add pipeline metadata labels to all images created using dockerfile

**Enter Task Name**: Docker Task

## Environment
- Server - Azure Pipelines
- Agent - Hosted 

## Issue Description

Task documentation (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops) mentions "Metadata added as labels". Suppose the dockerfile contains steps to build more than 1 image, then the labels are only added to the final image.

**Comment by ds-ms** [comment]
@sonayak to check it out!

**Comment by sonayak** [comment]
@nachiketrss I am assuming that you are doing a multi-stage docker build. Docker command line tool does not provide the support to tag or label intermediate images. We can put tags and labels only on the final image. The intermediate images are supposed to be temporary images.
Can you explain your use case to understand this requirement?

**Comment by nachiketrss** [comment]
On a self-hosted agent once the docker build/push is completed (using the docker task), I wanted to prune the images created as part of the build. So I did docker image prune based on `buildnumber` filter only to realize that the intermediate image is not getting pruned.

**Comment by sonayak** [comment]
Thanks @nachiketrss for sharing the use case. As per solution specified in Docker forums for this specific problem, people are using custom LABELs in intermediate builds to help in pruning only those intermediate builds. They are putting the LABELs in Dockerfile. I am providing the links below for reference.
https://github.com/moby/moby/issues/34151#issuecomment-478802490
https://forums.docker.com/t/tag-intermediate-build-stages-multi-stage-build/34795
Please let us know if this solves the problem.
