### ISSUE TITLE
AndroidSigning@3: `zipalign` fails with libz.so.1 not found on Ubuntu

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [microsoft/azure-pipelines-tasks#12879]
## Required Information

**Question, Bug, or Feature?**
*Type*: Bug

**Enter Task Name**: AndroidSigning@3

## Environment
- Server - Azure Pipelines
- Agent - Hosted (image `Ubuntu-latest`)

## Issue Description

Here is the definition of the pipeline:
https://dev.azure.com/15509/Timetracker-project/_git/timetracker-client?version=GC8818861d040fdeb46b4c8d658abf84a005c74516&path=%2Fci%2Fazure-pipelines.yml

It works fine when using `macOS-latest` image.

### Task logs

https://dev.azure.com/15509/Timetracker-project/_build/results?buildId=51&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=3ae6d2b9-5d8d-5ffa-efaf-e046b3587947

With diagnostics enabled:
https://dev.azure.com/15509/Timetracker-project/_build/results?buildId=52&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=3ae6d2b9-5d8d-5ffa-efaf-e046b3587947

### Error logs

```
/usr/local/lib/android/sdk/build-tools/19.1.0/zipalign -v 4 /home/vsts/work/1/s/app/build/outputs/apk/release/app-release-unsigned.apk.unaligned /home/vsts/work/1/s/app/build/outputs/apk/release/app-release-unsigned.apk
/usr/local/lib/android/sdk/build-tools/19.1.0/zipalign: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
##[error]Error: The process '/usr/local/lib/android/sdk/build-tools/19.1.0/zipalign' failed with exit code 127
```

**Comment by egor-bryzgalov** [comment]
@WPMGPRoSToTeMa Thank you for the report!
Could you please try to add Bash task with this command to your pipeline:
`sudo apt-get -y install lib32z1`
It seems that this package is missing.

**Comment by WPMGPRoSToTeMa** [comment]
@egor-bryzgalov this helped, thank you. Here is a link to the successful build:
https://dev.azure.com/15509/Timetracker-project/_build/results?buildId=53&view=results

As I can see this bug was here for a long time, but no one reported about it:
`Let’s change the vmImage to a Mac one, this will fix a problem of path for the zipalign tool:`
https://damienaicheh.github.io/azure/devops/2019/06/13/how-to-build-and-sign-your-android-application-using-azure-devops-en.html
