### ISSUE TITLE
NuGetCommand@2 ignores vstsFeed argument when command is set to 'custom'

### ISSUE THREAD

**Issue by qwertylolman** [microsoft/azure-pipelines-tasks#12895]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetCommand@2  

## Environment
- Server - Azure Pipelines
- Agent - any hosted agent
 
## Issue Description
task ignores vstsFeed argument

- task: NuGetCommand@2
    displayName: 'Install Dotfuscator package'
    inputs:
      feedsToUse: 'select'
      vstsFeed: '$(NugetFeedToRestoreFrom)'
      command: 'custom'
      arguments: >
        install "$(DotfuscatorPackageName)"
        -OutputDirectory "$(DotfuscatorInstallFolder)"
        -x

### Task logs

SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
Detected NuGet version 5.5.1.6542 / 5.5.1+fd2f920875c33464efb4b5ac366d8b8a83239dc0.fd2f920875c33464efb4b5ac366d8b8a83239dc0
SYSTEMVSSCONNECTION exists true
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/runner/hostedtoolcache/NuGet/5.5.1/x64/nuget.exe install PreEmptive.Protection.Dotfuscator.Pro.Eval -OutputDirectory /Users/runner/runners/2.168.2/work/_temp/dotfuscator -x -NonInteractive
Feeds used:
Unable to find package 'PreEmptive.Protection.Dotfuscator.Pro.Eval'
  https://api.nuget.org/v3/index.json

Installing package 'PreEmptive.Protection.Dotfuscator.Pro.Eval' to '/Users/runner/runners/2.168.2/work/_temp/dotfuscator'.
  GET https://api.nuget.org/v3/registration5-gz-semver2/preemptive.protection.dotfuscator.pro.eval/index.json
  NotFound https://api.nuget.org/v3/registration5-gz-semver2/preemptive.protection.dotfuscator.pro.eval/index.json 93ms
##[error]The nuget command failed with exit code(1) and error(Unable to find package 'PreEmptive.Protection.Dotfuscator.Pro.Eval')
Finishing: Install Dotfuscator package

**Comment by magleaso** [comment]
When using YAML there's no clear indication of this, but the custom command means all inputs except "arguments" are ignored. The user passes arguments to the NuGet client without any assistance from the task. We are winding down support for this heavyweight task. We recommend moving to the [NuGet Authenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) and following this with a script to invoke the NuGet client, similar to what you're doing with the NuGet custom command here.
