### ISSUE TITLE
PublishTestResults@2 task encapsulates all the test results in a single test run

### ISSUE THREAD

**Issue by V-vltru** [microsoft/azure-pipelines-tasks#12894]
Hello,

Could anybody please help me with making "PublishTestResults" task upload test results correctly without merging them in a single test run? Some details are below.

I have several test runs which results I need to upload to ADO. They are stored in several *trx files. How can I upload these test results without merging them into one test suite? I need to have the same amount of test suites as a number of *trx files.

There are the tool parameters I applied for uploading:

- task: PublishTestResults@2

displayName: 'Publish Test Results **/*.trx'

inputs:

testResultsFormat: VSTest

testResultsFiles: '**/*.trx'

searchFolder: '$(ResultsFileSource)'

mergeTestResults: true

testRunTitle: '$(TestRunTitle)'

condition: succeeded()

When I change "mergeTestResults" parameter value on "false" - it still encapsulates all tests in a single test run.

Please let me know how I can use this task correctly. Feel free to reach me by mail (v-vltrun@microsoft.com) or by Microsoft Teams at any time you like.

Thanks!

**Comment by V-vltru** [comment]
Hello, I looked through the source code of PublishTestResults@2 task and found a constraint there which encapsulates all runs in one when the amount of .trx files is more than 100. But for the enterprise project I'm working on it is too few. We have about 500 ones. 

Is it possible somehow to get around this restriction? I would like to be added as a contributor and make this task better and more flexible.

Thank you.

**Comment by navin22** [comment]
@V-vltru I am closing this issue as you can use results.publish vso command to publish/create the runs way you need it.

**Comment by Johannesm299** [comment]
@navin22 how does the invocation of the results.publish vso command work? Similar to these https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md?

I tried it like so: `##vso[results.publish testResultsFormat=VSTest;testRunTitle=projectName]/path/to/project.trx` but that didn't work. So the vso command has different Parameters than the [Task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml#syntax)?
