### ISSUE TITLE
Docker task - Label keys depend on the agent config (azure pipeline agent vs self-hosted agent)

### ISSUE THREAD

**Issue by nachiketrss** [microsoft/azure-pipelines-tasks#12900]
**Question, Bug ?**  
*Type*: Docker task - Label keys depend on the agent config (azure pipeline agent vs self-hosted agent)

**Enter Task Name**: Docker task

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

Pipeline's docker task (build) automatically adds meta data to the docker image if the 'Add Pipeline metadata to image(s)' setting is enabled. However, the label key is not consistent and changes based on whether an azure pipeline agent or self hosted agent is used.

Self hosted agent adds labels starting with:
com.visualstudio.OrgName.image.build...... where OrgName is name of organization

Where as this documentation says (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops) azure pipelines agent adds labels starting with:
com.azure.dev.image....

When I tested I get the same label for both scenarios - so is the documentation wrong?

**Comment by ds-ms** [comment]
Do you have any examples?

**Comment by nachiketrss** [comment]
Please see below. I have also added to the original post.

Self hosted agent adds labels starting with:
com.visualstudio.OrgName.image.build...... where OrgName is name of organization

Where as this documentation says (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops) azure pipelines agent adds labels starting with:
com.azure.dev.image....

**Comment by ds-ms** [comment]
cc: @tauhid621 to take a look at this.

**Comment by ggirard07** [comment]
@tauhid621 Documentation is still not up-to-date... 

Also having variable keys to declare keys for metadata is just a nightmare for users. This is a really bad design!
In my case it looks like the suffix for the keys is based on the URL an end-user uses to queue the pipeline run, and not the one use to register the agent (if browser URL is pointing to https://dev.azure.com/org or https://org.visualstudio.com).

Either case/again, using a variable to define metadata KEYS is bad design!
