### ISSUE TITLE
AzureFunctionsApp@1 : deployment with 'Runtime Stack' value is breaking app service 

### ISSUE THREAD

**Issue by phwecker** [microsoft/azure-pipelines-tasks#12911]
Question, Bug, or Feature?
Type: Bug

Enter Task Name: AzureFunctionsApp@1 Task

Environment
Server - Azure Pipelines
Agent - Hosted

this is similar to issue described in #12514, which was closed (unfortunately "normal users" on github cannot re-open an issue), please merge back this one if required. 

### issue

when selecting a value from "Runtime Stack" in task, the resulting value seems to be invalid and the deployment actually renders the functions app broken, displaying "Runtime Stack: error" on the overview page of the app service. 

### effect

this has caused significant issues as the drop-down presented indicates that it can be freely chosen, but the deployment behaviour seems to fall back on a default runtime stack, rather than failing the task, **breaking a production deployment**. 

### desired behaviour

Also the dropdown only shows .NET and Javascript as the option, which is not the complete list of available environments. Either the user can be sure the list has all valid options for runtime environments available or it should be replaced by a text field to put in the runtime env manually. 

in any case, if an invalid value is provided, the task should fail, not render the resource broken.

**Comment by eaarora-ms** [comment]
Not able to repro the issue. It is working fine on my end.
@phwecker Please share your pipeline logs as zip after setting system.debug as true and redeploying the pipeline.

**Comment by asranja** [comment]
@phwecker Please share the logs as suggested by @eaarora-ms above if you are still facing this issue.

**Comment by phwecker** [comment]
seems it was a transient issue. the yaml code attribute of runtime stack generated now looks different than it did when the issue occured.
