### ISSUE TITLE
AzureCLI@V2: documentation should have examples

### ISSUE THREAD

**Issue by orktopus** [microsoft/azure-pipelines-tasks#12913]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureCLI@V2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I am looking at the azurecli@v2 task and the documentation isn't comprehensive. it would be great to have actual examples of how different script locations are specified, how arguments are password etc. Also, the parameters section should really use the actual parameter that the task takes. For example, "Script Arguments": should really be written as "arguments" as that is the parameter that the actual yaml will recognize.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by issacnitin** [comment]
@pulkitaggarwl Can help you with updating the doc for Azure CLI

**Comment by anuragc617** [comment]
@pulkitaggarwl can you have a look at this.

**Comment by v-abiss** [comment]
@kanika1894 I'll look into this issue

**Comment by tejasd1990** [comment]
Hi @v-abiss , do you have an update on this?
