### ISSUE TITLE
How can I use AzureAppServiceSettings to set an App Service/Function to "Always On"?

### ISSUE THREAD

**Issue by eegabeeva** [microsoft/azure-pipelines-tasks#12926]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureAppServiceSettings 

## Environment
- Server - Azure Pipelines
    - account name: vale-devops
    - team project name: Digital-Lab
    - build definition name: covid19-import-data
    - build number: 

- Agent - Hosted
    - agent queue name: vs2017-win2016

## Issue Description

How can I use AzureAppServiceSettings to set an App Service/Function to "Always On"?

**Comment by eaarora-ms** [comment]
Hi @eegabeeva  We have already mentioned the setting in our readme here : https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureAppServiceSettingsV1

```
General settings: Edit web app General settings following the syntax -key value. Value containing spaces should be enclosed in double quotes.

Example : [ { "alwaysOn": true, "webSocketsEnabled": false } ]
111
