### ISSUE TITLE
Gateway Timeout Error on Azure

### ISSUE THREAD

**Issue by vicky252046** [microsoft/azure-pipelines-tasks#12925]
Getting the below error while creating any resource on my Azure Portal. Please help
FYI : Its a free tier account
{
    "error": {
        "code": "GatewayTimeout",
        "message": "The gateway did not receive a response from 'Microsoft.Storage' within the specified time period."
    }
}

**Comment by damccorm** [comment]
Hey @vicky252046 is this an issue with a task? This seems like a more general Azure issue, not Azure DevOps (we're a different product). Could you open an issue with Azure Support https://support.microsoft.com/en-us/help/4026305/sql-contact-microsoft-azure-support?

If this is an issue with an Azure DevOps task, feel free to comment with the task name and we can reopen.
