### ISSUE TITLE
Using build logging commands for tag management

### ISSUE THREAD

**Issue by Chris113113** [microsoft/azure-pipelines-tasks#12928]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Powershell V2.0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

MSData / Vienna / MMS-Build

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Currently we use the Powershell task to scan modified files and add a tag to the build. This tag is then used to trigger Artifact-based tests for the associated PR.

This works great for including long-running tests that we don't want to run when non-impacted code has been touched.

What I would like to do is have a mechanism where if no tags are specified, then _all_ tests run. An easy way that I can think of to accomplish this would simply be to tag the build as 'UNKNOWN' if no other PR-related tags are present. However, I do not see a way to do this using the logging commands.

Currently we use:
       Write-Host "##vso[build.addbuildtag]$Tag"

I wanted to know if there's some way that we can retrieve the tags from within the build itself? I couldn't any documentation that answered this for me.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

NA

**Comment by zachariahcox** [comment]
@wnjenkin @jtpetty I think there's an API for this right?

**Comment by jtpetty** [comment]
@Chris113113 -  There is a REST API call to get the details for a build which should include the tags.

https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get?view=azure-devops-rest-5.1

**Comment by damccorm** [comment]
Closing since it seems like the question has been answered
