### ISSUE TITLE
Randomly getting "504 Gateway timeout" in Gradle task

### ISSUE THREAD

**Issue by freewheelnat** [microsoft/azure-pipelines-tasks#12932]
The last 7 days, we have been seeing about 50% failures of our builds, due to 504 Gateway Timeout.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle

## Environment
- Server: Azure Pipelines
thameswater
Fieldworks
Several pipelines affected: TW-Digital-Android-App-PR, TW-Digital-Android-App-QA, TW-Digital-Android-App-PR-UAT, TW-Digital-Android-App-Commit_Build
Example build ids (1 for each pipeline listed above): 40636, 40643, 39900, 40563

- Agent - Hosted or Private: 
   Pool: Azure Pipelines
   Image: MacOS-10.14 / MacOS-10.15 (some pipelines use one, some the other)
   Agent:  Azure Pipelines N / Hosted Agent (some pipelines use one, some the other)

## Issue Description

Random 504 Gateway timeout when downloading dependencies. This fails about 50% of our Android builds at the moment.

Note: Bintray has been showing green status last 7 days, so I don't think it's an issue on bintray side.

**Comment by freewheelnat** [comment]
Closing this as not seen the issue last 2 days, so it was probably an intermittent issue.

**Comment by adammeyer** [comment]
I've been seeing this over the past few days.  Can't get it to succeed today, always getting a 504.  Works fine on my network, just not in azure.

**Comment by freewheelnat** [comment]
We saw this again on Thursday 4th June, then it was fine again on Friday 5th June.

**Comment by Ragamabhilash** [comment]
I saw this on 20th Oct and again today, on 19th Nov.

**Comment by marcus-dias** [comment]
Hey, did you guys find a solution for this? I am currently facing the same issues.
