### ISSUE TITLE
JavaToolInstaller - usage of public libraries to Install

### ISSUE THREAD

**Issue by AlexandrKravchuk** [microsoft/azure-pipelines-tasks#12935]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: JavaToolInstaller  

Make the support of picking up the JDK archive from public libraries.

**Comment by FranzKohl** [comment]
Will this feature being taken care of or not? In any case, a comment from the feature owner would be appreciated.

**Comment by FranzKohl** [comment]
Six months w/o any human reaction from the dev team... at least a comment indicating any plan or progress would be appreciated. @damccorm - any chance to get feedback on this one?

**Comment by damccorm** [comment]
@anatolybolshakov thoughts on this one? If we want to pick it up, we could do something like Actions and pick up Zulu support - https://github.com/actions/setup-java/blob/main/src/distributions/zulu/installer.ts

**Comment by anatolybolshakov** [comment]
@damccorm yes it make sense, thanks 👍  probably we could just do something similar to this action.

**Comment by FranzKohl** [comment]
> If we want to pick it up, we could do something like Actions and pick up Zulu support - https://github.com/actions/setup-java/blob/main/src/distributions/zulu/installer.ts

@damccorm - Danny, this sounds reasonable to me. Just wondering if there is any plan or even progress on this one?

**Comment by FranzKohl** [comment]
@damccorm - Danny, is there any hope to get this ever realized?

**Comment by anatolybolshakov** [comment]
Hi @FranzKohl we are working on more prioritized items at the moment, but going to get back to this one as possible enhancement once be able to

**Comment by FranzKohl** [comment]
@damccorm & @anatolybolshakov 

Yesterday I found that the .NET Tool Installer (in Azure DevOps 2020.1) is even able to download the brand-new .NET 7 SDK... so it looks to me, that the team behind this tool installer did a good job. 

In that context I'm really sad to see, that after more than two years there still isn't a similar solution available for the Java Tool Installer. This will be my last note on this thread, I'm giving up, sorry.
