### ISSUE TITLE
UseDotNet fails to resolve older version dotnet 3.1.202 sdk package

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/azure-pipelines-tasks#12939]
## Required Information 

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet

## Environment
Azure Devops Server 2019.1.1

Private agent with version 2.153.1 on windows server 2016
## Issue Description
UseDotNet fails to install dotnet 3.1.202 since last night yet it is available in https://github.com/dotnet/core/blob/master/release-notes/releases-index.json

Changing to 3.1.x fixes the issue, but 3.1.202 should imo work since it's available in the feed.

### Task logs
```
==============================================================================
Task         : Use dotnet
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.0.7
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 3.1.202.
No matching sdk version could be found for specified version: 3.1.202 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 3.1.202 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 3.1
Searching for version in channel 3.0
##[error]sdk version matching: 3.1.202 could not be found
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
##[error]sdk version matching: 3.1.202 could not be found

**Comment by issacnitin** [comment]
@Mobrockers I'm not able to reproduce the issue with the latest version of the task. Since you're running Azure DevOps On-prem server, could you try updating the UseDotNetV2 task to the latest version?

For updating the task to latest version in On-Prem server, you can follow these steps:
1. Install node version >= 8, clone this repo
2. Run npm install
3. Run ```node make.js build --task UseDotNetV2``` from root of the repo
4. Install tfx-cli (https://github.com/Microsoft/tfs-cli)
5. Run ```tfx build tasks upload --task-path ./_build/Tasks/UseDotNetV2``` from root of the repo
6. Give the On-prem account URL and PAT Token 

Let us know if this works out

**Comment by Mobrockers** [comment]
If we manually update the task on-prem and there comes an azure devops server update, will the task be updated to the correct version or will we need to manually downgrade the task first before we do the upgrade to assure a correct upgrade path?

**Comment by issacnitin** [comment]
@Mobrockers If the server itself is updated, the task will be the latest version out of the server's package and the one you've installed.

**Comment by issacnitin** [comment]
Also, no need to manually downgrade the task 👍

**Comment by issacnitin** [comment]
@Mobrockers Did you get a chance to try updating the task?

**Comment by Mobrockers** [comment]
@issacnitin I'll discuss this with my team today and get back to you

**Comment by Mobrockers** [comment]
We have decided not to update for now since there is a workaround. I'll circle back after the azure devops 2020 update if the problem still exists.
