### ISSUE TITLE
Visual Studio Test deleting trx files and other artifacts on task completion rather than waiting until pipeline completes

### ISSUE THREAD

**Issue by chuck-hunter** [microsoft/azure-pipelines-tasks#12949]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Visual Studio Test

## Environment
If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  I can provide this information privately.

## Agent
Private, Windows 10 Pro, Agent Version 2.163.1

## Issue Description
The "Visual Studio Test" task deletes all trx files and artifacts from the agent machine upon completion of the task, preventing us from accessing the information with subsequent tasks, such as uploading test results or reporting them to slack.  The tooltip for the test results field indicates the TestResults directory is only cleaned at the beginning of the test run and at the end of the pipeline, not the end of the task.

**Comment by ShreyasRmsft** [comment]
@chuck-hunter are you using Azure Devops Server Onprem or the hosted Azure Devops Service? What version of the vstest task are you using?

Please provide the full zip logs with system.debug = true so that we can get all the info we need. The latest version of the task does not clean up the results at the of the task.

**Comment by ShreyasRmsft** [comment]
@chuck-hunter gentle ping.

**Comment by ShreyasRmsft** [comment]
Closing due to no response, please re-open with requested data.
