### ISSUE TITLE
AzureFunctionApp: Python remote build via requirements.txt

### ISSUE THREAD

**Issue by Marco-Santoni** [microsoft/azure-pipelines-tasks#12958]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureFunctionAppV1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFunctionAppV1

## Environment
- Server - Azure Pipelines 

- Agent - Hosted

## Issue Description

I'm trying to deploy a Python Function via AzureFunctionApp task. It is possible to deploy a Python Function via CLI and use the [remote build](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#remote-build) method. In this way, dependencies are obtained remotely based on the contents of the `requirements.txt` file. However, the AzureFunctionApp task [requires](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=python#build-your-app) to install all the dependencies locally and zip them with the code when deploying. This is achieved via:

```bash
pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
```

This way of deploying requires extra steps in the pipeline that do not add considerable value when we have simple PyPI dependencies. The task should allow to deploy just the definition of the dependencies in the `requirements.txt` file, without pip-installing them in a local target. This simple behaviour is already featured by the CLI:

```bash
func azure functionapp publish <APP_NAME>
```

**Comment by Marco-Santoni** [comment]
Comment to keep the issue open.

**Comment by kmkumaran** [comment]
@nadesu , @chshrikh , @N-Usha  for follow up
