### ISSUE TITLE
Error  in "Build using AppService-Build"

### ISSUE THREAD

**Issue by RajatDoshi** [microsoft/azure-pipelines-tasks#12967]
I am trying to deploy my web-app on azure but when I try to build and deploy my python web-app, I get the following error in the GitHub actions area. 

Build using AppService-Build4s
Error: Couldn't detect a version for the platform 'python' in the repo.
Run azure/appservice-build@v1
/usr/bin/docker run --name be76db05733f291aa64600801e34fd0af54828_771a97 --label be76db --workdir /github/workspace --rm -e pythonLocation -e INPUT_PLATFORM -e INPUT_SOURCE-DIRECTORY -e INPUT_PLATFORM-VERSION -e INPUT_OUTPUT-DIRECTORY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/sherrands/sherrands":"/github/workspace" be76db:05733f291aa64600801e34fd0af54828  "" "python" "" ""

No source directory was provided -- the root of the repository ('GITHUB_WORKSPACE' environment variable) will be built: '/github/workspace'
No output directory was provided
Platform provided: 'python'
No platform version provided -- Oryx will determine the version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 12  2472   12   301    0     0   1410      0  0:00:01 --:--:--  0:00:01  1406
100  2472  100  2472    0     0  11560      0 --:--:-- --:--:-- --:--:-- 11551

Running command 'oryx build /github/workspace --platform python --enable-dynamic-install'
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200312.2, Commit: d1cf6b4a89345b6a7d0dc25d0fbd67860862ee18, ReleaseTagName: 20200312.2
Build Operation ID: |p0TYuWkMiss=.ae6c35a8_
Repository Commit : d0479c7e116dba821ddc88240e54192678beb5c7

**Comment by asranja** [comment]
Please open an issue in the GitHub action repo for appservice-build action https://github.com/Azure/appservice-build.

This repo only deals with Azure Pipelines tasks.
