### ISSUE TITLE
AzureWebAppContainerV1 hidden param ends up being used

### ISSUE THREAD

**Issue by dazinator** [microsoft/azure-pipelines-tasks#12963]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureWebAppContainerV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines    
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
       - darrell.tunnell@uniun.io
       - https://dev.azure.com/uniun/Uniun
       - release: https://dev.azure.com/uniun/Uniun/_releaseProgress?_a=release-environment-logs&releaseId=767&environmentId=1456

- Agent - Hosted    
    - If using Hosted agent, provide agent queue name:
       - windows latest:
> Agent name: 'Hosted Agent'
2020-05-21T09:44:22.7790423Z Agent machine name: 'WIN-IP8NBLIKQOR'
2020-05-21T09:44:22.7790754Z Current agent version: '2.168.2'
2020-05-21T09:44:22.7809491Z Current image version: '20200517.1'
2020-05-21T09:44:22.7815809Z Agent running as: 'VssAdministrator'
2020-05-21T09:44:22.7824139Z Prepare release directory.
2020-05-21T09:44:22.7830742Z ReleaseId=767, TeamProjectId=6334dd50-2591-41b3-8764-746de9f071eb, ReleaseDefinitionName=Uniun Website

## Issue Description

Task Info:

> 2020-05-21T09:44:25.0695397Z ==============================================================================
2020-05-21T09:44:25.0696201Z Task         : Azure Web App for Containers
2020-05-21T09:44:25.0696794Z Description  : Deploy containers to Azure App Service
2020-05-21T09:44:25.0697175Z Version      : 1.163.5
2020-05-21T09:44:25.0697674Z Author       : Microsoft Corporation
2020-05-21T09:44:25.0698253Z Help         : https://aka.ms/azurewebappcontainertroubleshooting
2020-05-21T09:44:25.0698727Z ==============================================================================

**Problem**:
I am seeing my release pipeline fail during deployment, when executing this task.
However the error log looks odd, because it is trying to get authorization to a scope name, with a variable in the scope name: `$(env_resource_group)` and failing - and that variable happens to be one that used to be a variable in my pipeline (but is not any longer). 

![image](https://user-images.githubusercontent.com/3176632/82550753-f3eb5380-9b56-11ea-90a0-cb8b1370014d.png)

If I look at the yaml view of this task on the release pipeline - this shows the values I am executing it with:

```
variables:
  docker_registry_name: 'labdocker.azurecr.io'
  docker_image_repository_name: 'uniun/uniun'
  semver: '$(Build.BuildNumber)'

steps:
- task: AzureWebAppContainer@1
  displayName: 'Deploy docker image'
  inputs:
    azureSubscription: 'ARM Staging'
    appName: 'uniun-staging'
    containers: '$(docker_registry_name)/$(docker_image_repository_name):$(semver)'
```

So I am unsure as to why it still fails trying to access a scope with variable "$(env_resource_group)" reported in the scope name, which is ofcourse invalid.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

- If i run the release with `system.debug` true variable, do I need to sanitise the log output before upload here?

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

FYI This link had a lot of stuff which only related to yaml pipelines and was hard to tell how to do this for classic release pipelines, but I did eventually find mention of `system.debug` variable, but not sure how to sanitise logs. Would be great if there was a dedicated link for each scenario.

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by dazinator** [comment]
I think I have finally found the issue that has cost me about 6 hours of investigation.

![image](https://user-images.githubusercontent.com/3176632/82552489-1df24500-9b5a-11ea-902f-280372737705.png)
![image](https://user-images.githubusercontent.com/3176632/82552576-45e1a880-9b5a-11ea-8ce4-79930b7ee044.png)

If you untick that checkbox in the above screenshot, for some reason, the task when it executes still uses that value. I had unchecked the box but had left a variable in the UI. The UI disappears when you uncheck the box so I couldn't see this, nor in the yaml view:

![image](https://user-images.githubusercontent.com/3176632/82552697-85a89000-9b5a-11ea-8efa-0a10a9cab4d1.png)

The initial bug led me to believe my service connection, principal was wrong and didn't have access for some reason to that scope, so I ended up investigating that for ages before i noticed the actual scope name was seemingly based on a bad variable. I then spent hours looking at my task configuration, and on the UI, and YAML view it all looked good. This led me to believe the task was caching stuff somehow from previous excecutions. But no.. it just uses stores value and uses it even if the check box is unticked, and that's not obvious to see anywhere.

**Comment by 20shivangi** [comment]
@dazinator If you clear the value the value of resource group and then tick the checkbox, the issue must not occur. Have you checked this ?

**Comment by dazinator** [comment]
If I tick the box so the value shows, then clear it, then untick the box, so its hidden again (but now with no value assigned) then yes everything works as expected.

The issue comes if there is a value entered and you untick the checkbox - which hides the value so you no longer see it. The task still ends up using the value at runtime, but in the UI you have no indication that there is a value that is being used as it has been hidden. Therefore its now easy to see the problem. Hopefully that is clear?

**Comment by 20shivangi** [comment]
@dazinator So you can anyway have the variable declared in devops , the issue won't be there

**Comment by dazinator** [comment]
@20shivangi 
> So you can anyway have the variable declared in devops , the issue won't be there

Sorry - I don't understand that sentence!

**Comment by dazinator** [comment]
@20shivangi if you mean what I _think_ you mean - yes the issue will still be there even if the variable is still in devops - because if you look at the error shown in my screenshot in the issue description above:

![image](https://user-images.githubusercontent.com/3176632/92729796-c0813e80-f36a-11ea-9c29-13da2ef34e83.png)

The failure - is that the task still tries to access the resource group specified by the variable when it shouldn't be. Whether the value of the variable is provided by a devops variable, or entered directly - the problem is the same.

**Comment by 20shivangi** [comment]
@dazinator You can unblock yourself by clearing the value from resource group and then tick the checkbox. Meanwhile, we can look into the issue.

**Comment by AmrutaKawade** [comment]
This is fixed and will be deployed within 2 weeks.
