### ISSUE TITLE
Feature Request: Expose Github PullRequest Title

### ISSUE THREAD

**Issue by Jetski5822** [microsoft/azure-pipelines-tasks#12986]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Git  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/tesco-colleague/HRAM%20Upgrade

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 2016

## Issue Description

When raising a Pull Request in Github, I would like to be able to access the Pull Request title in Azure Pipelines Variables

![image](https://user-images.githubusercontent.com/619530/82733403-70bf2e80-9d0b-11ea-9406-c40ddde31031.png)

A similar request was made here: https://github.com/microsoft/azure-pipelines-tasks/issues/2147

**Comment by damccorm** [comment]
This looks like an issue with the service, not with tasks themselves - could you please open a ticket here - https://developercommunity.visualstudio.com/spaces/21/index.html? We're trying to reserve this repo for issues with individual tasks
