### ISSUE TITLE
Error publishing code coverage when running dotnet test task on solution with multiple test projects

### ISSUE THREAD

**Issue by danielp37** [microsoft/azure-pipelines-tasks#12985]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResultsV1 or PublishTestResultsV2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - TFS on-premises 2017 Version 15.117.27414.0
    
- Agent - Private: Windows 2012 R2 Agent Version 2.122.1

## Issue Description

We use the dotnet test task to run the tests associated with a .net core 3.1 solution.  There are multiple test projects in the solution. Here is an example of the command line that dotnet test is run with:

dotnet test Solution.sln --no-build --collect:"Code Coverage" --lo gger trx --results-directory D:\DevOpsAgentSvc\_work\2334\TestResults

We aren't using the default "Publish Test Results" option on the dotnet test task because we need the test results to be in a place where SonarQube and pick them up and use them.  

When this runs, it creates several TRX files.  They are named similar to this:

username_COMPUTERNAME_2020-05-22_13_24_08.trx 
username_COMPUTERNAME_2020-05-22_13_24_08[1].trx 
username_COMPUTERNAME_2020-05-22_13_24_08[2].trx 
username_COMPUTERNAME_2020-05-22_13_24_08[3].trx 
username_COMPUTERNAME_2020-05-22_13_24_10.trx

It ends up putting all of the .coverage files in directories:
username_COMPUTERNAME_2020-05-22_13_24_08\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06.coverage 
username_COMPUTERNAME_2020-05-22_13_24_08\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06[1].coverage 
username_COMPUTERNAME_2020-05-22_13_24_08\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06[2].coverage 
username_COMPUTERNAME_2020-05-22_13_24_08\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06[3].coverage
username_COMPUTERNAME_2020-05-22_13_24_10\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06.coverage

When the Publish Test Results task runs, I see the following warnings:

##[warning]Unable to archive the test results: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\DevOpsAgentSvc\_work\2334\TestResults\username_COMPUTERNAME_2020-05-22_13_24_08[1]\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06[1].coverage '.
##[warning]Unable to archive the test results: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\DevOpsAgentSvc\_work\2334\TestResults\username_COMPUTERNAME_2020-05-22_13_24_08[2]\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06[2].coverage '.
##[warning]Unable to archive the test results: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\DevOpsAgentSvc\_work\2334\TestResults\username_COMPUTERNAME_2020-05-22_13_24_08[3]\In\COMPUTERNAME\username_COMPUTERNAME_2020-05-22.13_24_06[3].coverage '.

This results in the coverage for that test assemblies with the warnings to not get uploaded to the server.

It appears that the logic for uploading the coverage files assumes that the coverage file will be in a subdirectory named after the name of the trx file when in reality, they are placed in subdirectory that matches the /TestRun/TestSettings/Deployment/@runDeploymentRoot of the trx file.  

The older vstest task and dotnet vstest tasks both combine all test assemblies into a single trx file and a single coverage file and therefore this wasn't an issue for those test results.  

Currently I'm thinking I'm going to need to create a workaround by running a script to create symbolic links from where the publish task is expecting the coverage files to where they actually are.

Are we doing something wrong here?

**Comment by hvinett** [comment]
Hey @danielp37 , Can you please provide the debug logs setting system.debug=true ?

**Comment by ShreyasRmsft** [comment]
@danielp37 can you please provide the full logs zip with system.debug set to true? Or maybe a sample github repo with a pipeline yml file so that we can get a quick repro?

**Comment by ShreyasRmsft** [comment]
Closing this due to no response, please re-open with the requested data.
