### ISSUE TITLE
Permissions in C:\Windows\system32\inetsrv\config

### ISSUE THREAD

**Issue by pontuskindh** [microsoft/azure-pipelines-tasks#12980]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: IIS Web Application Deployment
  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/IISWebAppDeploymentOnMachineGroupV0

## Issue Description
Getting the bellow error when running this task using a non administrative account. 
My question is regarding giving read access to the C:\Windows\system32\inetsrv\config folder for the local users group would be considered insecure for a production environment.

### Error logs

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='D:\Agents\azagent\A1\_work\r1\a\temp_web_package_29244155173395825.zip' -dest:contentPath='Sitename' -enableRule:AppOffline
Error: An error occurred when reading the IIS Configuration File 'MACHINE/REDIRECTION'. The identity performing the operation was 'User'.
Error: Filename: \\?\C:\Windows\system32\inetsrv\config\redirection.config
Error: Cannot read configuration file due to insufficient permissions

Error count: 1.

**Comment by arjgupta** [comment]
@pontuskindh for machine group based tasks we recommend running the agent as NT AUTHORITY\LOCAL SYSTEM.
