### ISSUE TITLE
XamarinAndroid: Ability to set output APK file name

### ISSUE THREAD

**Issue by sdobrodeev** [microsoft/azure-pipelines-tasks#13009]
**Question, Bug, or Feature?**
*Type*: Feature

**Enter Task Name**: XamarinAndroid

**Issue Description**
In some cases, the developer needs to specify the output APK file name, including using pipeline variables. It would be nice to add input to XamarinAndroid task for these purposes.

**Comment by PraveenKariyapperuma** [comment]
Any update on this?
