### ISSUE TITLE
PublishTestResults@2 with mergeTestResults results in 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by ChadNedzlek** [microsoft/azure-pipelines-tasks#13007]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishTestResults@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/dnceng/public/_build/results?buildId=660881&view=results

- Agent - Hosted or Private: 
    
    - Windows 10, I don't know the agent version

## Issue Description
Adding "mergeTestResults: true", so that I don't just get a bunch of "Xunit_7" runs in my test results tab seems to cause the task to crash internally..
When I run the following yaml...
```yaml
- task: PublishTestResults@2
  displayName: Publish Core Test Results
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/TestResults-*' 
    searchFolder: $(Build.ArtifactStagingDirectory)\TestResults
    testRunTitle: Basic Tests
    mergeTestResults: true
    buildConfiguration: $(_BuildConfig)
```
I get this result, with no tests published:
```
Starting: Publish Core Test Results
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.167.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
F:\workspace\_work\1\s\.dotnet\dotnet.exe --version
3.1.200
F:\workspace\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.167.1\modules\TestResultsPublisher.exe @F:\workspace\_work\_temp\83c9bc50-9fd8-11ea-b033-6bda6b88c9cf.txt
##[warning]Failed to parse result files:  One or more errors occurred.
Object reference not set to an instance of an object.
Finishing: Publish Core Test Results
```
### Task logs

I've tried this, and whenever I enter debug mode, even for the same exact commit, the bug goes away.  However, we can't just run all our builds in debug mode.  Here's an example of the build against the same commit, but with system.debug enabled. https://dev.azure.com/dnceng/public/_build/results?buildId=660988&view=logs&j=074323ca-ed16-5d66-87ac-2d9d4a30c602&t=16e27a66-ad46-516d-fe4d-92e1dbe633b2

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
Starting: Publish Core Test Results
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.167.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
F:\workspace\_work\1\s\.dotnet\dotnet.exe --version
3.1.200
F:\workspace\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.167.1\modules\TestResultsPublisher.exe @F:\workspace\_work\_temp\83c9bc50-9fd8-11ea-b033-6bda6b88c9cf.txt
##[warning]Failed to parse result files:  One or more errors occurred.
Object reference not set to an instance of an object.
Finishing: Publish Core Test Results
```

**Comment by ChadNedzlek** [comment]
I tried removing it, and now it's saying "Index was outside the bounds of the array."... I'm wondering if the task is just unpredictably crashing and the "mergeTestResults" has nothing to do with it.

I'm going to try rolling back to version 1 for now.

**Comment by ChadNedzlek** [comment]
This sounds like a dupe of https://github.com/microsoft/azure-pipelines-tasks/issues/13013

**Comment by upadhyayap** [comment]
@ChadNedzlek could you please share the trx file which you are trying to publish

**Comment by ChadNedzlek** [comment]
This was months ago. I have moved on long ago.
