### ISSUE TITLE
Allow to mark tests as flaky in PublishTestResults

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-pipelines-tasks#13008]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishTestResults

## Issue Description

According to https://github.com/MicrosoftDocs/azure-devops-docs/issues/6700#issuecomment-575300329, a test can only be marked as flaky in a programmatic way by using the REST API. This is a huge barrier and likely only a few very dedicated souls will ever do that.

Instead of using the REST API it would be much simpler if PublishTestResults would optionally accept some kind of newline separated file containing a list of flaky test names.

**Comment by navin22** [comment]
@letmaik You can actually mark and unmark test falky from the UI as well, from test tab in your pipeline. 
![image](https://user-images.githubusercontent.com/19592945/83383586-11e07000-a403-11ea-98b3-e240bb6e5cb7.png)

**Comment by letmaik** [comment]
I know, but I'm specifically looking for a solution where the set of flaky tests is declared as part of the repository content.
