### ISSUE TITLE
Unable to cancel run in experiment

### ISSUE THREAD

**Issue by RajarshiBhadra** [microsoft/azure-pipelines-tasks#13004]
I was trying out some features of the exp class but somehow a run got initiated which I am unable to cancel. How can I stop this process if the gui options are not available

![image](https://user-images.githubusercontent.com/8817352/82958971-523f8880-9fd4-11ea-8de8-4ec79b8e3874.png)

**Comment by damccorm** [comment]
Hi @RajarshiBhadra this doesn't look like an issue with an individual task - for issues with the service, please file a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html
