### ISSUE TITLE
AzureCLI@2 does not ignore the result of “az keyvault certificate delete” and "purge"

### ISSUE THREAD

**Issue by afarber** [microsoft/azure-pipelines-tasks#13001]
Hello dear Azure pipeline tasks developers!

In an Azure pipeline for nightly builds, I am performing the following steps:

- deploy a keyvault by an ARM template,
- then try to delete a self-signed cert in it,
- then import the cert again -
- and finally deploy a service fabric by another ARM template, using the cert by the thumbprint.

Here is an extract of the pipeline:

    # purge the self-signed cert from the Keyvault to avoid conflict; ignore failures (DOES NOT WORK?)
    - task: AzureCLI@2
      inputs:
        azureSubscription: '${{ parameters.ArmConnection }}'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        continueOnError: true
        failOnStandardError: false
        powerShellErrorActionPreference: 'silentlyContinue'
        inlineScript: |
          az keyvault certificate delete --vault-name $(KeyVaultName) --id 'https://$(KeyVaultName).vault.azure.net/certificates/my-self-signed-cert'
          az keyvault certificate purge --vault-name $(KeyVaultName) --id 'https://$(KeyVaultName).vault.azure.net/deletedcertificates/my-self-signed-cert'

    # import the self-signed certificate my-self-signed-cert into the Keyvault
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: '${{ parameters.ArmConnection }}'
        ScriptType: 'InlineScript'
        azurePowerShellVersion: '3.1.0'
        Inline: |
          $Pwd = ConvertTo-SecureString -String 'MyPassword' -Force -AsPlainText
          $Base64 = 'MIIKqQI__3000_CHARS_HERE____HP1ICAgfQ=='
          $Cert = Import-AzKeyVaultCertificate -VaultName $(KeyVaultName) -Name my-self-signed-cert -CertificateString $Base64 -Password $Pwd
          echo "##vso[task.setvariable variable=Thumbprint;isOutput=true]$Cert.Thumbprint"

At first the above code was working for, but then I have disabled *soft delete* feature in the ARM template for the keyvault:

    "properties": {
        "enableSoftDelete": false,
        "enabledForDeployment": true,
        "enabledForDiskEncryption": false,
        "enabledForTemplateDeployment": true,

Or maybe the trigger for my problem was just deleting the keyvault by hand... 

Anyway now I get the repeated pipeline errors:

![image](https://user-images.githubusercontent.com/1884458/82924071-1bd61f00-9f7c-11ea-8d4b-6163449e1782.png)

I wonder why is "az" failure not ignored, despite me setting `failOnStandardError: false` and `powerShellErrorActionPreference: 'silentlyContinue'`?

Also, I tried surrounding both "az" commands by a "try / catch", but the error is still there:

    ##[debug]which 'az'
    ##[debug]found: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
    ##[debug]scriptType=pscore
    ##[debug]scriptLocation=inlineScript
    ##[debug]scriptArguments=null
    ##[debug]powerShellErrorActionPreference=silentlyContinue
    ##[debug]Agent.Version=2.169.0
    ##[debug]Agent.TempDirectory=d:\a\_temp
    ##[debug]scriptPath=d:\a\1\s
    ##[debug]inlineScript=az keyvault certificate delete --vault-name my-nightly-my-keyvault --id 'https://my-nightly-my-keyvault.vault.azure.net/certificates/my-self-signed-cert'
     --vault-name my-nightly-my-keyvault --id 'https://my-nightly-my-keyvault.vault.azure.net/deletedcertificates/my-self-signed-cert'
    ##[debug]powerShellIgnoreLASTEXITCODE=false
    
    ...lines skipped...
        
    A certificate with (name/id) my-self-signed-cert was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182
    Operation "purge" is not enabled for this vault.
    ##[debug]$LASTEXITCODE: 1
    ##[debug]Exit code 1 received from tool 'C:\Program Files\PowerShell\7\pwsh.exe'
    ##[debug]STDIO streams have closed for tool 'C:\Program Files\PowerShell\7\pwsh.exe'
    ##[debug]task result: Failed
    ##[error]Script failed with exit code: 1
    ##[debug]Processed: ##vso[task.issue type=error;]Script failed with exit code: 1
    ##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with exit code: 1
    ##[debug]which 'az'
    ##[debug]found: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
    ##[debug]which 'az'
    ##[debug]found: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
    ##[debug]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg:  account clear
    ##[debug]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg:  account clear
    ##[debug]exec tool: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
    ##[debug]exec tool: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
    ##[debug]arguments:
    ##[debug]arguments:
    ##[debug]   account
    ##[debug]   account
    ##[debug]   clear
    ##[debug]   clear
    [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
    ##[section]Finishing: AzureCLI

*Type*: Question

**Enter Task Name**: AzureCLI@2

## Environment
- Server - Azure Pipelines:

https://vwac.visualstudio.com/Connected-Vehicle/_build/results?buildId=33344&view=logs&j=2b542855-fccb-5eff-1b5d-4f4093f69e6c&t=a4e85043-5258-5da0-1ece-d416c89a0969

**Comment by issacnitin** [comment]
@afarber  This is expected as script returns a non-zero exit code
Please refer to https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#ignore-last-exit-code
to understand how to ignore failure by the exit code and continue the pipeline. Thanks!

**Comment by issacnitin** [comment]
In case of Azure CLI task with powershell, you can set ```powerShellIgnoreLASTEXITCODE``` to true

**Comment by afarber** [comment]
This has helped, thank you
