### ISSUE TITLE
Self hosted Build Agent taking too much time to run Job successfully

### ISSUE THREAD

**Issue by fra-kuk** [microsoft/azure-pipelines-tasks#13000]
Our self-hosted build agent fails on publishing the test results to Azure DevOps (MS Cloud, not on-premise) sometimes.

We configured the agent according to the documentation on https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows by passing the proxy settings in the config.cmd.

We have the following task description:
![image](https://user-images.githubusercontent.com/51959685/83021117-c6584b80-a029-11ea-8871-df32a200d5d6.png)

In most cases the build **agent takes round about 15minutes** to run the "Publish Test Results **/junit*.xml" job. (Pipeline in Azure DevOps).
Since it **sometimes took less time (only 6 seconds)** i am thinking that something goes wrong in this task. Really shouldn't take that much time for this task.

Agent is running behind proxy server! Configured like described in here https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows

**Task returns following warning:** 

##[warning]Failed to upload file junit.xml to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed. ---> Microsoft.Azure.Storage.StorageException: Fehler beim Senden der Anforderung. ---> System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung. ---> System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (407) Proxyauthentifizierung erforderlich.

Sorry for the warning message being in German! Can try to get in English if necessary.

Does somebody know where the error/warning comes from? Grateful for any help, and sorry if this issue is not being created in perfection, i promise i will do better next time. I am learning!

For those who suggest using evironment variables - unfortunately this is not an option.
Thanks in advance!

**Comment by fra-kuk** [comment]
The firewall acts like a proxy. The running authentication mode is Active Directory SSO. Could that be a problem?

**Comment by navin22** [comment]
@fra-kuk 
The task retries if there are transfer exceptions. hence it will be taking long time. Can you check if your firewall settings are whitelisting the necessary URLs that's needed by agent, the list is in the below doc.
https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#additional-urls-for-signing-into-azure-devops-and-azure 

PTR task especially uses this https://*.vstmrblob.vsassets.io

**Comment by fra-kuk** [comment]
@navin22 Thanks for your comment! In fact, the problem was that there were some URLs that needed to be whitelisted. The firewall blocked them before.

It is working fine now.

**Comment by navin22** [comment]
Thanks for the confirmation!
