### ISSUE TITLE
CacheV2 should support multiple key files

### ISSUE THREAD

**Issue by gitfool** [microsoft/azure-pipelines-tasks#13016]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: CacheV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

CacheV2 currently does not support multiple key files. This was recently added to GitHub Actions via multiple arguments to the `hashFiles` function. See https://github.com/actions/cache/issues/143.

**Comment by johnterickson** [comment]
IIRC comma separating works. Do you see otherwise?

**Comment by gitfool** [comment]
@johnterickson Doh! I somehow missed this is [documented](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#key-input) too. Will give it a go, thanks!

**Comment by gitfool** [comment]
Indeed, this works as expected. 😸
