### ISSUE TITLE
Can "Passed on rerun" and "Not Impacted" test statuses be set independently of VsTest task?

### ISSUE THREAD

**Issue by mwelsh1118** [microsoft/azure-pipelines-tasks#13018]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VsTest/PublishTestResults

## Environment
- Server - Azure Pipelines or TFS on-premises?
    On-prem 16.131.27701.1

## Issue Description

We have complicated prerequisites for our unit tests. This prevents us from using the VsTest task (which is fine). We have built our own test distribution mechanism using Microsoft HPC. We would like to still keep track of which tests "passed on rerun" or were "not impacted" (we have this information, independent of the VsTest task). Can this be done by publishing a trx with a special unit test outcome? Or is there some other way we can manipulate the test results published to TFS?

As far as I can tell, the VsTest task uses TestSelector.exe to update the test results, which I'm assuming is where the passed-on-rerun/not-impacted data gets set. I don't know if TestSelector.exe is open-source, but I had trouble finding it.

**Comment by ShreyasRmsft** [comment]
You can look at the Rest API docs to manipulate the test run https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/update?view=azure-devops-rest-5.1

**Comment by ShreyasRmsft** [comment]
And no the testselector is not open source.

**Comment by suyash691** [comment]
@mwelsh1118 Do you need any further information? Or may I close this issue?

**Comment by mwelsh1118** [comment]
@suyash691 You may close it.
