### ISSUE TITLE
Use .NET Core does not set dotnet version to lower (2.2.xxx) after task was updated to Version : 2.169.1 

### ISSUE THREAD

**Issue by andrelvahter** [microsoft/azure-pipelines-tasks#13024]
*Type*: Bug

**Task Name**: 
Use .NET Core
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UseDotNetV2

## Environment
- Server - Azure Pipelines 
-  Azure DevOps : skype

## Issue Description

After the Use .NET Core task was updated to Version : 2.169.1 one of our user builds started to fail.
After some debugging we found that even if we use the "Use .NET Core" task and it says in logs.
Found version 2.2.402 in channel 2.2 for user specified version spec: 2.2.402
Version: 2.2.402 was found in cache.
Creating global tool path and pre-pending to PATH.

If we run a .Net Core version next it falls back to latest version found on the Agent.

##[debug]C:\windows\system32\cmd.exe /c "dotnet --version"
dotnet --version
3.1.300

**Comment by issacnitin** [comment]
@andrelvahter By default, UseDotNetV2 task installs dotnet tool to ```$(Agent.ToolsDirectory)/dotnet```
So you could reference it by $(Agent.ToolsDirectory)/dotnet --version
Another alternative is to use DotNetCoreCLI@2, this will by default select the dotnet version installed by UseDotnet task

Do let us know if this solves your issue

**Comment by andrelvahter** [comment]
@issacnitin 

Seems the dotnet.exe on the root level of 
$(Agent.ToolsDirectory)/dotnet 
is not updated 
![image](https://user-images.githubusercontent.com/12758987/83250513-e5351a00-a1b0-11ea-8f1c-0da34c7d6738.png)
The SDK itself is copied.
![image](https://user-images.githubusercontent.com/12758987/83250573-0269e880-a1b1-11ea-9db3-528f3f3e69e8.png)

So your solution sadly does not work :( 

With Prev. version of the task it probably changed the PATH variable, so you did not need to use the full path but just call dotnet.exe. A lot of engineers would need to alter they definition to use the full path ?

From the Task itself I would anticipate that the root dotnet.exe would be updated.
Agent log:
```

Found version 2.2.402 in channel 2.2 for user specified version spec: 2.2.402
##[debug]Processed: ##vso[telemetry.publish area=TaskDeploymentMethod;feature=UseDotNetV2]{"userVersion":"2.2.402", "resolvedVersion":"2.2.402"}
##[debug]isExplicit: 2.2.402
##[debug]explicit? true
Version: 2.2.402 was found in cache.
##[debug]Agent.Version=2.168.2
##[debug]Processed: ##vso[task.prependpath]D:\a\_work\_tool\dotnet
##[debug]set DOTNET_ROOT=D:\a\_work\_tool\dotnet
##[debug]Processed: ##vso[task.setvariable variable=DOTNET_ROOT;issecret=false;]D:\a\_work\_tool\dotnet
##[debug]set DOTNET_MULTILEVEL_LOOKUP=0
##[debug]Processed: ##vso[task.setvariable variable=DOTNET_MULTILEVEL_LOOKUP;issecret=false;]0
Creating global tool path and pre-pending to PATH.
##[debug]testing directory 'C:\Users\builder\.dotnet\tools'
##[debug]Agent.Version=2.168.2
##[debug]Processed: ##vso[task.prependpath]C:\Users\builder\.dotnet\tools
##[debug]Agent.ProxyUrl=undefined
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]



```

**Comment by issacnitin** [comment]
@andrelvahter That's surprising, I just tried installing version 2.2.402 and in another bash task, executed $(Agent.ToolsDirectory)/dotnet/dotnet.exe --version and got the version as 2.2.402 as well. The "File Version" might be in out of sync with the actual .NET version.

We cannot install tools globally, as agents will have access to only specific folders that are scoped down from the machine in which the agent is running. So the globally installed .NET versions are part of the agent image itself. You can find details about agent images here: https://github.com/actions/virtual-environments

As a workaround, for now, I still believe you can use $(Agent.ToolsDirectory)/dotnet/dotnet.exe. Do let us know if this works out

**Comment by andrelvahter** [comment]
@issacnitin 
Think it worked because you did not have a newer version already cached.
You can take a look at this pipeline .
https://skype.visualstudio.com/SBS/_build/results?buildId=31055087&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=00933dce-c782-5c03-4a85-76379ccfa50a

**Comment by bishal-pdMSFT** [comment]
@andrelvahter AFAIK `dotnet --version` will print the version of dotnet.exe cli. It does not mean that 2.2.402 SDK is not installed. You can run `dotnet --info` to list all installed SDK versions.

dotnet.exe is just a cli and it invokes appropriate version of SDK based on the global.json found in the project. Since you are specifically trying to use 2.2.402, I assume that you have specified this version in global.json in your project. If so, then during dotnet execution, this version only will be picked.

Also, AFAIK you do not need to specify full path `$(Agent.ToolsDirectory)/dotnet/dotnet.exe`, as the task adds this to PATH.

**Comment by issacnitin** [comment]
@andrelvahter You're right, the cached dotnet CLI is not being overridden when installing a new version using UseDotNetV2. Thanks for reporting the issue! 

As a workaround, you can change $(Agent.ToolsDirectory)/dotnet to say ```$(Agent.ToolsDirectory)/dotnet/2.2.402```. Another workaround is, as @bishal-pdMSFT mentioned, use a global.json with the version specified. As 2.2.402 is installed by default in the latest windows images, you can avoid the UseDotNetV2 task if you're running on a hosted agent.

@bishal-pdMSFT You're right that we're adding it to the path, but now the path has multiple values for dotnet CLI. In the case of Unix based OS, the first executable found is picked, in Windows, I believe it is the same, but not sure. But yes, if we're pre-pending to the path, trying to execute using ```dotnet.exe``` is worth the effort.

**Comment by andrelvahter** [comment]
Cool,
Ty for looking into it @issacnitin and @bishal-pdMSFT and for the hints and workarounds.
Now that we know the state we can take actions. 
All the best,
Andrel

**Comment by issacnitin** [comment]
Awesome! I'm closing the issue for now, please feel free to re-open in case of any queries or concerns regarding this. Thanks @andrelvahter

**Comment by rebecca-makar** [comment]
@issacnitin Is this going to be fixed?  `the cached dotnet CLI is not being overridden when installing a new version using UseDotNetV2. Thanks for reporting the issue!`

**Comment by issacnitin** [comment]
The behaviour is by task design. Using global.json in an environment with multiple versions of .NET SDK is standard practice, @bishal-pdMSFT can take a call if we should change this behaviour

**Comment by issacnitin** [comment]
@rebecca-makar Could you help us with the incentive to have this behaviour changed ?

**Comment by bishal-pdMSFT** [comment]
> the cached dotnet CLI is not being overridden when installing a new version using UseDotNetV2

This is not an issue. A cached version of dotnet.exe does not mean that it will use cached version of SDK. 
CLI != SDK

CLI will invoke correct version of SDK if it is specified in global.json.

**Comment by rebecca-makar** [comment]
ok, thank you!
