### ISSUE TITLE
AD Password written to log in Azure DACPAC task

### ISSUE THREAD

**Issue by Jeppeks1** [microsoft/azure-pipelines-tasks#13035]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeployment@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Azure Pipelines - Cannot provide more information

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Agent name: 'Hosted Agent'
Agent machine name: 'WIN-7QSOCHSU8FJ'
Current agent version: '2.168.2'
Current image version: '20200517.1'

## Issue Description

The following is relevant for at least deployType sqlTask and inlineSqlTask. When using AuthenticationType 'aadAuthenticationPassword' or 'aadAuthenticationIntegrated' the provided password is written in plaintext to the log output. Here is a sample of the output:

Sql file: D:\a\1\s\scripts\database-config\set-db-owner.sql
Invoke-Sqlcmd -connectionString "Data Source=myserver.database.windows.net; Initial Catalog=mydatabase; Authentication=Active Directory Password; UID=myuser@domain.com; PWD={ActualPassword}"  -Inputfile "D:\a\1\s\scripts\database-config\set-db-owner.sql"

When using a non-AD authentication mechanism this is not an issue, as the connection string is properly masked. The offending line is here:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1#L281 

A super simple fix involves starring out the connection string as was done with the other authentication mechanisms.

**Comment by asranja** [comment]
@Jeppeks1 It is recommended to use passwords as a secret variable so that it can be masked out in the log. 

If you enter the password as a secret variable here, it should automatically get masked in the Sql task's logs. Since we are constructing the connection string in the task for AuthenticationType 'aadAuthenticationPassword' or 'aadAuthenticationIntegrated', we have not masked the entire connection string.

**Comment by asranja** [comment]
Closing this. Please reopen if the above solution doesn't work out.
