### ISSUE TITLE
Build pipeline failing for Azure SQL ddl - sys.tables reference

### ISSUE THREAD

**Issue by chasdso** [microsoft/azure-pipelines-tasks#13037]
Our build is failing for our Azure SQL DDL (dacpac creation) due to a new view references sys.tables and child objects -

These are deployed and exist in our Azure SQL environment, but are not included in the source code ddl - is there a flag I can implement to ignore sys.tables and all child object references during the build process?

##[error]DDL\Reporting\Views\vw_ArchiveTables.sql(16,6): Error SQL71501: View: [Reporting].[vw_ArchiveTables] has an unresolved reference to object [sys].[tables].
6-f51e-57a1-6dd4-575fd75fc7ef&l=47

**Comment by mq-gif** [comment]
Hi, could you please share your solution?
