### ISSUE TITLE
Azure PowerShell Script Task: Please provide a valid tenant or a valid subscription

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-tasks#13038]
Hi All,

Azure PowerShell Script Task v3  - for AzureRM backward compatibility - is failing with `"Please provide a valid tenant or a valid subscription"` error.
There is no relation with the content of the inline or external script or the AzureRM version, similar result with 6.5, 6.7 and 6.13.x.

There is also no relation with the Service Connections:
The Task is working properly with same settings if I restart the ADO Agent service.

Have you any idea?

Regards,
Gabor

**Comment by asranja** [comment]
@iambernics Can you provide more specific details regarding the cmdlet which throws the error. 

Did the debug logs (run the pipeline with variable "system.debug" to "true") provide any more info ?

**Comment by iambernics** [comment]
@asranja 

**Reproducing**

0. AzureRM 6.7 is pre-installed on the Agent
1. Create a New Service Connection:
"Azure Resource Manager - Service Principal (recommended)"
2. The Registered app has Contributor permission on the Subscription (just for testing)
3. Add Azure PowerShell Script Task (select v3 for AzureRM support)
4. Inline script with blank content
5. Select the affected Subscription in the Task

Output with system.debug:

```
Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
 Select-AzureRMSubscription -SubscriptionId xxxxxx-zzzzzz-yyyy-tttt-uuuuuuu -TenantId 

```
The SubscriptionID is valid.
The TenantID is just three ***, I am not sure that this is the normal operation.


```
##[debug]Script stack trace:
##[debug]at Set-CurrentAzureRMSubscription, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.167.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 372
##[debug]at Initialize-AzureSubscription, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.167.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 248
##[debug]at Initialize-Azure, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.167.2\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1: line 58
##[debug]at <ScriptBlock>, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.167.2\AzurePowerShell.ps1: line 78
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.ArgumentException: Please provide a valid tenant or a valid subscription.
##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.SetCurrentContext(String subscriptionNameOrId, String tenantId, String name)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.<>c__DisplayClass37_1.<ExecuteCmdlet>b__2(AzureRmProfile profile, RMProfileClient client, String name)
##[debug]   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.ExecuteCmdlet()
##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
##[error]Please provide a valid tenant or a valid subscription.
```

**Comment by iambernics** [comment]
Update: The Task is working properly with same settings if I install the AZ (instead of the AzureRM) and choose the Task version 4.0
Root cause is not on the Azure DevOps service side.
