### ISSUE TITLE
Find an alternative for scp2 library

### ISSUE THREAD

**Issue by sdobrodeev** [microsoft/azure-pipelines-tasks#13048]
**Question, Bug, or Feature?**
*Type*: Feature

**Enter Task Name**: CopyFilesOverSSH

**Issue Description**
At this moment we have a dependency on the scp2 library (https://github.com/spmjs/node-scp2). This project does not have a maintainer and is not supported. It would be nice to find an alternative for this library and use it.

**Possible alternatives**

* Any-File (https://github.com/mcolomer/any-file)
* SSH2 SFTP Client (https://github.com/theophilusx/ssh2-sftp-client)

**Comment by vsd-codesode** [comment]
This alternative project have not got any activity in almost last one year. Can we confirm if this will be maintained in future?

**Comment by sdobrodeev** [comment]
> This alternative project have not got any activity in almost last one year. Can we confirm if this will be maintained in future?
Thank. I found a better library - https://github.com/theophilusx/ssh2-sftp-client

**Comment by sdobrodeev** [comment]
Found and used https://github.com/theophilusx/ssh2-sftp-client instead of scp2.
Created and merged the PR - https://github.com/microsoft/azure-pipelines-tasks/pull/13084
