### ISSUE TITLE
[InstallAppleProvisioningProfileV1] Not compatible with macOS (OSX) app signing anymore (". provisionprofile")

### ISSUE THREAD

**Issue by jmartarelli** [microsoft/azure-pipelines-tasks#13045]
<img width="1042" alt="Captura de Tela 2020-06-02 às 01 55 57" src="https://user-images.githubusercontent.com/13212627/83482889-c0be9380-a477-11ea-9e2f-b8630e8cba0f.png">
<img width="955" alt="Captura de Tela 2020-06-02 às 02 23 39" src="https://user-images.githubusercontent.com/13212627/83483086-3b87ae80-a478-11ea-81dd-27f951ecce28.png">

The extension validation added on this issue: https://github.com/microsoft/azure-pipelines-tasks/pull/12917 removed the capability of signing a MacOS app (Developer ID Application).

MacOS Provisioning Profile extension is ˜.provisionprofile˜. 
The ".mobileprovision" is used just for mobile apps... 
I cant find another way to sign my macOS app right now using Azure Devops.

.mobileprovision - iOS provisioning profile
.provisionprofile - OSX provisioning profile

**Comment by ruixi1994** [comment]
Our team faced the same issue. The macOS tasks started to fail after the check is added for mobile app only. May I ask whether it is viable to bring it back soon? And if yes how long it gonna take to make the fix? Thank you so much!

**Comment by Saccomani** [comment]
I have the same issue here

**Comment by mattleibow** [comment]
This ironically was fixed in 2018, but now un-fixed: https://github.com/microsoft/azure-pipelines-tasks/issues/8387

**Comment by mattleibow** [comment]
Did my first fix :) Hopefully I don't bring down all the regions of DevOps: https://github.com/microsoft/azure-pipelines-tasks/pull/13074

**Comment by nshenoy** [comment]
Our team is also blocked by this. Can we get @jmartarelli 's  fix fast-tracked?

**Comment by jmartarelli** [comment]
@tipa , @nshenoy 
There is a workaround for this. Instead of getting the certificate uploaded into azure, put it somewhere inside your source branch and configure the task to look into your source repository... (There is a combo box for this option selection)...
