### ISSUE TITLE
Is there any way in DockerV2 task to push multiple images by inputting a single image file lke in dockerv1 task?

### ISSUE THREAD

**Issue by arroyc** [microsoft/azure-pipelines-tasks#13069]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Feature

**Enter Task Name**: **Docker@2** command>>push

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure pipeline**
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **OryxLinux**

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Docker@2, push image
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Like in version 1 there was an way to push multiple images by providing a file as input.
- task: Docker@1
  displayName: push
  inputs:
    azureContainerRegistry: aeqeaaada
    command: push
    pushMultipleImages: true
    imageNamesPath: qasdads/asdasd

**Comment by sonayak** [comment]
@arroyc I think the same can be accomplished by using the task twice. Is there any specific reason to use one task to push 2 images? We have designed DockerV2 to be simple to use and would like to overload it with a lot of features like DockerV1. At the same time, if we discover any missed use cases which cannot be handled by the task, we will do the enhancement.
