### ISSUE TITLE
AppCenterDistribute@3 - release notes should be optional

### ISSUE THREAD

**Issue by Mikilll94** [microsoft/azure-pipelines-tasks#13065]
## Issue Description

In **AppCenterDistribute@3** task, release notes should be optional. On the App Center portal when you are uploading builds manually, you don't need to provide release notes.

![Screenshot 2020-06-04 at 22 30 20](https://user-images.githubusercontent.com/17653648/83807202-fc916d00-a6b2-11ea-8f4a-0ccc5e361087.png)

**Comment by josesimoes** [comment]
Still waiting for the implementation.

**Comment by josesimoes** [comment]
Still waiting

**Comment by josesimoes** [comment]
still waiting

**Comment by josesimoes** [comment]
still valid (and needed)
