### ISSUE TITLE
Powershell task in a Task Group: Inline scripts can't read task group parameters.

### ISSUE THREAD

**Issue by jkindwall** [microsoft/azure-pipelines-tasks#13066]
## Required Information

*Type*: Bug

**Enter Task Name**: Powershell (v2.*)

**Environment**: ADO Pipelines with GUI interface (non-YAML)

## Issue Description

I'm trying to use the Powershell task within a Task Group to write an inline script that takes the path/name of a test suite, and calls the ADO rest api to look up the id of the test suite (to be used in a later task).

I can access environment variables that are NOT task group parameters using the $env:<variable name> syntax.  As an example, the following works to establish the rest api url to call:

    $url = "$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI" +
        "$env:SYSTEM_TEAMPROJECTID" +
        "/_apis/testplan/Plans/34939/suites?asTreeView=True&api-version=5.1-preview.1"

I can also WRITE to a task group variable using the somewhat bizarre ##vso[task.setvariable… syntax.  So this works as well:

Write-Host "##vso[task.setvariable variable=testing.testSuite;]$suiteIds"

However, I can't for the life of me find a way to actually READ a task group parameter variable.  My task group parameter is named testingSuitePaths.  I have tried all of the following:

    Write-Host "$testingSuitePaths"  # Displays nothing
    Write-Host "$env:testingSuitePaths"  # Displays nothing
    Write-Host "$($env:testingSuitePaths)"  # Displays nothing and generates a new, unwanted task group parameter with the $env: prefix in the parameter name.

I also tried specifying a new environment variable in the list at the bottom of the task configuration as such:
Name | Value
---- | -----
MySuitePathVar | ${testingSuitePaths)

Which results in:

    Write-Host "$MySuitePathVar"  # Displays the literal string $(testingSuitePaths)

If I use V 1.* of the task, I can work around this by passing the task group parameter in as a command line argument to the script as such:

Arguments:

    -testingSuitePaths $(testingSuitePaths)

Inline Script:

    Param(
        [String] $testingSuitePaths
    )
    Write-Host "$testingSuitePaths" # This works!

However, I can't use V1.*, because it limits the inline script box to 500 characters which is way too short for the script I'm trying to use.

The following SO article seems to be describing the same issue, but claims the Bash task does not have this bug.  
https://stackoverflow.com/questions/55634090/powershell-task-wont-use-vsts-task-group-variables-but-does-why

So unless someone can help me here, I'm faced with completely rewriting my script in Bash (which I know next to nothing about) as the only viable workaround for something as simple as passing a variable into a script.

**Comment by Josh-01** [comment]
Hi @jkindwall ,
Could you please try this: Write-Host "$(testingSuitePaths)"  in your inline script, this should work .
Thanks!

**Comment by ropstah** [comment]
> Hi @jkindwall ,
> Could you please try this: Write-Host "$(testingSuitePaths)" in your inline script, this should work .
> Thanks!

@Josh-01 this does not work:

```
2021-04-02T18:35:25.9183350Z + Write-Host "$(testingSuitePaths)"
2021-04-02T18:35:25.9186859Z +               ~~~~~~~~~~~~~~~~~~~~
2021-04-02T18:35:25.9189591Z     + CategoryInfo          : ObjectNotFound: (testingSuitePaths:String) [], ParentContainsErrorRecordException
2021-04-02T18:35:25.9191886Z     + FullyQualifiedErrorId : CommandNotFoundException
2021-04-02T18:35:25.9299614Z 
```
