### ISSUE TITLE
Set PYTHONPATH in the pythonScript task

### ISSUE THREAD

**Issue by v-sijeff** [microsoft/azure-pipelines-tasks#13073]
**Question, Bug, or Feature?**  Feature

**Enter Task Name**: pythonScript 

list here (V# not needed):  0

## Environment  Azure Pipelines 

- Agent - Hosted or Private:  Hosted
   I don't know the agent name 
   

    
## Issue Description
I would like the ability to set the PYTHONPATH environment variable in the pythonScript task arguments.  My lead has a library he would like accessible from anywhere.  That's the use case.

## Troubleshooting
According to https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops there is no option to set PYTHONPATH, unless I am missing something.

**Comment by PHPirates** [comment]
@damccorm This is still an issue

**Comment by anatolybolshakov** [comment]
Hi @PHPirates reopening this one since it is still actual.

**Comment by pragasv** [comment]
@damccorm @PHPirates  this seems to be still exiting ? even trying to update the python path doesnt seem to be working.

**Comment by PHPirates** [comment]
@pragasv Yes. If you know some typescript you could try fixing this task, I think it's just an `exec` which needs to add an environment variable. Alternatively, depending on the environment in which you run the task, a plain script step will work fine and no need for this task.
