### ISSUE TITLE
Use environment resource service connection with helmDeploy

### ISSUE THREAD

**Issue by marchenm** [microsoft/azure-pipelines-tasks#13075]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: helmDeploy  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-16.04

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

When using a deployment job and a kubernetes environment resource, the `helmDeploy` task should use the service connection from the resource instead of requiring a service connection. This functionality is already present in the `KubernetesManifest` task. 

Having to specify a service connection makes the task a lot less versatile because service connections cant have variables. 

See: https://github.com/MicrosoftDocs/azure-devops-docs/issues/7548

**Comment by shigupt202** [comment]
@marchenm This feature has already been added in this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/12678. `HelmDeploy` task does use the service connection from the environment resource if a connection input is not given to it.
