### ISSUE TITLE
ServiceFabricDeploy@1 works for a self-signed cert with password, but fails for a DigiCert cert without password

### ISSUE THREAD

**Issue by afarber** [microsoft/azure-pipelines-tasks#13079]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeploy@1

## Environment
- Server - Azure Pipelines

https://dev.azure.com/vwac/Connected-Vehicle/_build/results?buildId=36632&view=results

https://dev.azure.com/vwac/Connected-Vehicle/_build/results?buildId=36633&view=results
 
- Agent - Hosted with vmImage: 'windows-latest'

## Issue Description

Hello, dear Azure pipeline tasks team.

I have an Azure pipeline, which works pretty well with a self-signed certificate:

It deploys (via ARM templates) Redis, CosmosDB, EventHub, Keyvault, then imports the self-signed certificate into the Keyvault, then deploys SF cluster and configures it with the certificate. 

Finally the pipeline deploys our team's application with the following task:

    - task: ServiceFabricDeploy@1
      displayName: 'Deploy SF app'
      inputs:
        applicationPackagePath: '$(Build.BinariesDirectory)\Release\Applications\CloudGateway\Pkg\release'
        serviceConnectionName: '${{ parameters.ServiceConnectionName }}'
        applicationParameterPath: '$(Build.BinariesDirectory)\Release\Applications\CloudGateway\ApplicationParameters\Cloud.xml'
        overwriteBehavior: 'SameAppTypeAndVersion'
        overridePublishProfileSettings: true
        upgradeMode: 'UnmonitoredAuto'
        FailureAction: 'Rollback'

It works well, for days and in 5 different pipelines (1 scheduled for nights, 3 manual and 1 used for our Pull Request builds).

My problem:

I am trying to switch from using a self-signed certificate to a real wildcard certificate issued by DigiCert.

And then the final [ServiceFabricDeploy@1](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricDeployV1) task fails with

> An error occurred attempting to import the certificate. Ensure that your service endpoint is configured properly with a correct certificate value and, if the certificate is password-protected, a valid password. Error message: Exception calling "Import" with "3" argument(s): "The specified network password is not correct.

![image](https://user-images.githubusercontent.com/1884458/83969956-275a0c00-a8d3-11ea-8ce4-d75cc3a5df13.png)

When I go to my resource group "ccg-test" and verify that everything is deployed properly, I can not find any problems.

The SF cluster is configured with the new DigiCert certificate:

![image](https://user-images.githubusercontent.com/1884458/83969968-350f9180-a8d3-11ea-8607-37aea509186b.png)

And I have updated the SF service connection with the new hostname, certificate thumbprint and base64-encoded certificate contents as well:

![image](https://user-images.githubusercontent.com/1884458/83969977-4062bd00-a8d3-11ea-8a8f-b69bd2d910f2.png)

The only difference I see to the self-signed certificate, which I was using before and for which the Service Fabric app deployment worked is that it had a password.

While the new DigiCert-issued certificate does not have a password.

Is that the reason why the error message mentions that the third argument is missing?

### Task logs

You can find the detailed pipeline logs here, I do not know how to download and zip them.

https://dev.azure.com/vwac/Connected-Vehicle/_build/results?buildId=36633&view=logs&j=2b542855-fccb-5eff-1b5d-4f4093f69e6c&t=fcc5202d-f00f-5023-8bc6-ecd502b11471

Here the failing SF app deployment task log: [error.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4742209/error.txt)

### Error logs

```
2020-06-07T12:11:09.9380742Z ##[section]Starting: Deploy SF app
2020-06-07T12:11:09.9476671Z ==============================================================================
2020-06-07T12:11:09.9477045Z Task         : Service Fabric application deployment
2020-06-07T12:11:09.9477385Z Description  : Deploy an Azure Service Fabric application to a cluster
2020-06-07T12:11:09.9477671Z Version      : 1.9.3
2020-06-07T12:11:09.9477906Z Author       : Microsoft Corporation
2020-06-07T12:11:09.9478258Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/service-fabric-deploy
2020-06-07T12:11:09.9478664Z ==============================================================================
2020-06-07T12:11:12.0547682Z Searching for path: D:\a\1\s
2020-06-07T12:11:17.6457848Z No items were found with search pattern D:\a\1\s.
2020-06-07T12:11:17.6486341Z Searching for path: D:\a\1\b\Release\Applications\CloudGateway\Pkg\release
2020-06-07T12:11:17.6793173Z Found path: D:\a\1\b\Release\Applications\CloudGateway\Pkg\release
2020-06-07T12:11:18.1665349Z Service fabric SDK version: 4.1.409.9590.
2020-06-07T12:11:18.3226593Z ##[error]An error occurred attempting to import the certificate. Ensure that your service endpoint is configured properly with a correct certificate value and, if the certificate is password-protected, a valid password. Error message: Exception calling "Import" with "3" argument(s): "The specified network password is not correct.
"
2020-06-07T12:11:18.3484487Z ##[section]Finishing: Deploy SF app
```

**Comment by issacnitin** [comment]
@afarber Can you try adding a Admin client certificate to SF cluster and use it in the service endpoint. Cluster certificates are for node-node security, so they cannot be used to connect to the cluster.

**Comment by issacnitin** [comment]
@afarber From service fabric side, you can simply get another DigiCert certificate and add it as Admin Client certificate. Using self-signed cert for SF cluster is not recommended for production use.

**Comment by anuragc617** [comment]
@afarber are you able to set up ServiceFabric? should be close this issue?

**Comment by afarber** [comment]
I am closing the issue, because we will switch to using [reverse proxy](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-setup) for the digicert certificate. 

Thank you for the responses
