### ISSUE TITLE
HelmDeploy@0 support multiple valueFiles

### ISSUE THREAD

**Issue by a-jackson** [microsoft/azure-pipelines-tasks#13082]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  Feature unless it's supposed to already do it

**Enter Task Name**: HelmDeploy@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

## Issue Description

I would like to be able to pass multiple files to the valueFile input of the task. Helm itself supports this with using --values multiple times but the task only allows 1 to be specified.

**Comment by ds-ms** [comment]
@shigupt202 this seems like a good enhacement. Perhaps we could use the same input with `\n` as a delimiter.
Then people can supply something like
```yaml
valuesFile: |
   values1.yml
   values2.yml
   values3.yml
```
and we can apply them in the same order. This would ensure back-compat as well. 

Thoughts?

**Comment by shigupt202** [comment]
Agreed. I'll add the support.

**Comment by nigel-psl** [comment]
Any idea why this change was reverted in #13292? 
This would be a really useful feature as Helm supports multiple values files but the task does not
