### ISSUE TITLE
AzureRMWebAppDeployment@4 - cannot find existing webapp, when working in multiple subscriptions 

### ISSUE THREAD

**Issue by pietersap** [microsoft/azure-pipelines-tasks#13095]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRMWebAppDeployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:

/

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

any (I tried switching to different hosted agents)

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

We are using this task to deploy code to a webapp. For this, we use the *azureSubscription* property, which points to an existing service connection in Azure Devops. This service connection  (and the underlying service principal) has access to TWO azure subscriptions (a dev and a prod subscription). 

We have a documentation webapp which will only be run in the production environment, not in the development subscription.

We have a pipeline that first deploys the webapp itself (in the production resource group, using the **same** service connection), and this works. Afterwards, when using the AzureRMWebAppDeployment task to upload the content, we get an error saying that the webapp does not exist. 

Further investigation shows that the AzureRMWebAppDeployment, using our service connection, only finds webapps in the development subscription, not in the production subscription, even though the service connection is supposed to have access to both. 

On first sight, it looks like the task simply only checks one of the subscriptions. There is no option to specify both the service connection **and** the subscription in the task, so we assumed that the task would be smart enough to look in all the subscriptions that the service connection has access to. It appears not.

Am I missing something? Our current "workaround" is to simply deploy our documentation webapp to the development subscription instead. 

Thank you

### Task logs

Resource 'XXXX' doesn't exist. Resource should exist before deployment.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by asranja** [comment]
> Further investigation shows that the AzureRMWebAppDeployment, using our service connection, only finds webapps in the development subscription, not in the production subscription, even though the service connection is supposed to have access to both.

As per design, the Azure RM service connection can be linked to only one subscription. Any task using this service connection will be able to access resources from the subscription associated with the service connection only. 

If you want to deploy apps in two different subscriptions, you can simply create two service connections (via manual flow), both pointing to the same Service Principal. Link each service connection with one subscription.
