### ISSUE TITLE
AzureFunctionV1 - escape JSON special characters in Body

### ISSUE THREAD

**Issue by wow-anton** [microsoft/azure-pipelines-tasks#13098]
**Question, Bug, or Feature?**  
Question

**Task Name**: AzureFunctionV1  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Question

Is there a way to escape JSON reserved characters from the `Body` input?

GIven the following `Body` input:
```json
{
  "user": "$(Release.RequestedFor)"
}
```
if variable `$(Release.RequestedFor) = "[myproject]\User 1"` the rendered `Body` becomes:
```json
{
  "user": "[myproject]\User 1"
}
```
This is invalid JSON because the `\` character needs to be escaped as `\\` and the request fails because the server cannot parse the JSON request. See error logs for sample output.

Any suggestions would be appreciated.

### Error logs
```
Response Code: 0
Response: An error was encountered while processing request. Exception: 
Exception Message: The remote server returned an error: (500) Internal Server Error. (type WebException)
```

**Comment by asranja** [comment]
Assigning right owner as per https://github.com/microsoft/azure-pipelines-tasks/blob/fb0a8a1ede81162b6e3c9d9b77842a3bec28113c/.github/CODEOWNERS

**Comment by Ganeshrockz** [comment]
@wow-anton This question is more aligned with the working of Server Tasks in Azure Devops.The `Release.RequestedFor` returns just the username of the person who triggered the release in my case. Are you explicitly overriding the environment variable in this case?Also we don't support escaping of characters within a substituted variable.As a workaround you may try something like this in the request body

```
{
"A":$(System.TeamProject)\\$(Release.RequestedFor)
}
```

**Comment by wow-anton** [comment]
Thanks @Ganeshrockz .

If you use an automation account to trigger the release you should see that the project prefix is added. The workaround you suggested won't work in that case.

Since escaping characters is not currently possible, could the implementation be updated to pass the body through a JSON sanitizer before sending the request? I.e. instead of using the unsanitized string directly?

**Comment by Ganeshrockz** [comment]
@wow-anton It might take some time to introduce this as a feature from our end.One quick workaround i see here is to have a separate stage/agent job that runs at the start of the release,  which contains a `Powershell` task that modifies the release variables via rest apis. You can consume the `Release.RequestedFor` variable and escape the `\` character in your inline script and update the release with the newly formed variable.This release variable can be consumed in the request body of your task directly.

You can look out for some similar examples here

https://stackoverflow.com/questions/59249440/set-azure-devops-release-pipeline-variable-using-rest-api
http://chamindac.blogspot.com/2018/08/setting-vsts-release-variable-values-at.html
https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/update%20release?view=azure-devops-rest-5.0

Please let me know if you face some difficulties here

**Comment by wow-anton** [comment]
Thanks for the suggestions @Ganeshrockz 

I've tried something similar but in my use case I want to encapsulate all the steps in a single task group. Unfortunately, you cannot mix `Powershell` and `AzureFunctionV1` because one is an agent job and the other is agentless.

I've worked around it by removing the problematic field.
