### ISSUE TITLE
How to execute a single shell command writing to stderr from PowerShell task?

### ISSUE THREAD

**Issue by djee-ms** [microsoft/azure-pipelines-tasks#13097]
We are trying to run a single shell command from a powershell script (inline or not, doesn't matter). Let's take npm pack as an example:

```yaml
- pwsh: |
    npm pack .
```

The `npm` command like most *nix-like commands is outputting user info on `stderr` and result on `stdout`; here this is particularly relevant because `npm pack` outputs the package name, which we need for the next task. Anyway in general we might want to pipe the output to some other command, while messages to `stderr` need to be logged to console so that they are visible to the pipeline maintainers for diagnosing purpose.

In bash this just works. Plain and simple. Just as expected. Always.

In cmd this almost work, aside from the fact capturing the result of a command requires an incredibly complex syntax compared to what it should be (`result = command`).

Now PowerShell. By default PowerShell has this nonsensical behavior (at least on Azure, because locally it's different of course) where writing to `stderr` generates an exception and fails the task. On top of that the Azure powershell task captures those errors and print some log messages with a `##[error]` prefix.

The task has a `failOnStderr` option. It has been broken for years, but it seems to behave better nowadays. We recently tried `failOnStderr: false` and indeed the task succeeds... after logging 315 error messages, which are randomly reformatted in the logs, and appear prominently on the front page for the given pipeline build, strongly suggesting to the user that something went awfully wrong (it didn't).

We tried:
- `Invoke-Expression`
- `${ }`
- `$ErrorActionPreference`
- `failOnStderr`
- `$LASTEXITCODE`
- `try{} catch{}` block
- Redirect to stdout `2>&1`, which for us doesn't work since we need the package name output of `npm pack`
- Redirect to file `2>err.txt`
- Any combination of the above one can think of.

Several Microsoft engineers across 2 teams spent 10+ hours writing at least 3 different variants, all of which currently used in production for lack of a better alternative, all of which partially broken, all of which randomly failing with minor command or pipeline changes.

I do not believe that this is the amount of work that should be required to write such a simple task.

So here's the simple question: how do we do this in PowerShell, with proper error handling?

```bash
PACKAGE=$(npm pack .)
```

**Comment by alexander-smolyakov** [comment]
Hello, @djee-ms!

Could you please provide information about the environment that you are using for the pipeline (cloud/on-premise solution) and version of the PowerShell task?

Regarding failOnStderr, as it was mentioned in the issue description it should work, but as written in task docs about this parameter: "If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream. Otherwise, the task will rely on the exit code to determine failure."

So using a combination of `errorActionPreference` and `failOnStderr` parameters will prevent PowerShell task from failing and finalizing pipeline as well.

About proper error handling in PowerShell - Azure DevOps provided logging commands that can be used for the PowerShell scripts to log any error/information at the necessary level.

I attached links with information about logging commands:
- [About logging commands on docs.microsoft.com](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell)
- [About task logging commands](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md#task-logging-commands)
- [Use a PowerShell script to customize your build pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops)

**Comment by djee-ms** [comment]
> Could you please provide information about the environment that you are using for the pipeline (cloud/on-premise solution) and version of the PowerShell task?

The release pipeline is [here](https://github.com/microsoft/MixedReality-WebRTC/blob/master/tools/ci/release-unity.yaml). The NPM packing is [here](https://github.com/microsoft/MixedReality-WebRTC/blob/ccae6a171ec72678e75f04a7d89ac7decd09c597/tools/ci/templates/jobs-unity-package.yaml#L148) and is already using `$ErrorActionPreference = "SilentlyContinue"`, which does **not** silence any Azure DevOps error. On successful completion we still have 1 error per `npm pack` info line.

> So using a combination of errorActionPreference and failOnStderr parameters will prevent PowerShell task from failing and finalizing pipeline as well.

This is what I hoped. None of the combination we tried worked. The best we could get is a pipeline that succeeds and does the right thing, but logs 250 errors which are not errors but simply NPM info messages. Which I why I am asking how it is supposed to work, and why it is so complex that tens of users have to ask for help? Not failing the task is only half of the problem when the build report makes it look like it completely failed. Which incidentally is poor UX; if there is an error then the build should fail, and if the build succeed then there should be no error. Having error messages and a green build makes little sense.

> About proper error handling in PowerShell - Azure DevOps provided logging commands that can be used for the PowerShell scripts to log any error/information at the necessary level.

The problem is not about logging more errors. The problem is about stopping this nonsensical behavior of PowerShell treating everything as errors, and Azure DevOps logging every one of those on the front page of the build report.

> I attached links with information about logging commands.

Thanks. "Several Microsoft engineers across 2 teams spent 10+ hours writing at least 3 different variants" means we already read all those links, which again are about adding more logging, when what we want is to stop false positive error logging.

**Comment by alexander-smolyakov** [comment]
@djee-ms, I created a simple pipeline to test PowerShell task behavior with `npm pack .` command. 

This pipeline covers three cases:
1. The script executed with no errors
2. The script executed with errors but ignoreLASTEXITCODE set true 
3. The script executed with errors but ignoreLASTEXITCODE set false

All works as expected -  NPM info messages and errors are being logged in logs as info and don't display on the pipeline main page. You can find a pipeline by the [link](https://v-alsmo.visualstudio.com/PowerShellTest/_build/results?buildId=426&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e0810b27-de1e-5f7f-0df7-1a1042e925c2).

Сould you please provide logs from your pipeline to make a farther investigation? Also, it will be great if you can provide a sample for reproducing described behavior.

**Comment by alexander-smolyakov** [comment]
@djee-ms, please let us know if this issue still actual

**Comment by djee-ms** [comment]
I emailed you the logs, the issue didn't change, we're still seeing hundreds of "errors" on the pipeline report tab (which are just npm info messages) even though npm does not report any error and the pipeline succeeds. This means the pipeline report tab shows first 150 errors, and if you scroll down the page enough then shows everything actually went fine and there was no problem.

**Comment by djee-ms** [comment]
Also you link doesn't work.

**Comment by alexander-smolyakov** [comment]
@djee-ms, I've got your email, thanks for providing logs!

> Also you link doesn't work.

It seems that the link is out of date. So you can find a new build by the [link](https://v-alsmo.visualstudio.com/PowerShellTest/_build/results?buildId=445&view=results).

**Comment by djee-ms** [comment]
Your pipeline and packing code are somewhat different from the one I posted originally. In particular we need to get back the name of the npm package so need to capture that, therefore our code is more complex. Maybe reproducing with it instead would show the error in your example. I'd also add at least 1 file in the package so it's not empty. And remove the other tasks that are failing, which are influencing the result of the pipeline and therefore making it diverge from what we have.

https://github.com/microsoft/MixedReality-WebRTC/blob/ccae6a171ec72678e75f04a7d89ac7decd09c597/tools/ci/templates/jobs-unity-package.yaml#L148

**Comment by alexander-smolyakov** [comment]
@djee-ms, I modified my pipeline but didn't manage to reproduce the described behavior. You can find a pipeline by the [link](https://dev.azure.com/v-alsmo/PowerShellTest/_build/results?buildId=482&view=results).

As I can see from the provided logs the "Publish" pipeline was executed on the private agent, could you please try to execute it on the MS-hosted agent and see if the issue still appears?

**Comment by alexander-smolyakov** [comment]
> could you please try to execute it on the MS-hosted agent and see if the issue still appears?

@djee-ms, did you able to check if this issue reproducible on MS-hosted agent?

**Comment by anatolybolshakov** [comment]
Hi @djee-ms is it still actual for you, were you able to reproduce it with ms hosted agent?

**Comment by anatolybolshakov** [comment]
Hi @djee-ms, I'm closing it currently due to inactivity, please feel free to reopen it if it still actual for you

**Comment by ralph-tice** [comment]
this is relatively high search result for "azure devops redirect stderr", adding resolution here instead of abandoning would be ideal

**Comment by anatolybolshakov** [comment]
Hi @ralph-tice could you please describe your case in more details and provide some repro steps/sample?
You can use errorActionPreference and failOnStderr task inputs - to control Powershell behavior regarding stderr.
