### ISSUE TITLE
CopyFilesOverSSH fails in KornShell (ksh)

### ISSUE THREAD

**Issue by johan-ejstrud** [microsoft/azure-pipelines-tasks#13108]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CopyFilesOverSSH

## Issue Description
CopyFilesOverSSH fails when copying to server running ksh:
```
==============================================================================
Task         : Copy files over SSH
Description  : Copy files or build artifacts to a remote machine over SSH
Version      : 0.170.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh
==============================================================================
Setting up SSH service connection to remote host 10.1.22.16.
Cleaning target folder /z/falcon/projstat/general/toolpool/bos_test/UserStory82468 on the remote machine
##[error]ksh: bash:  not found

##[error]Failed to clean the target folder on the remote machine. Command bash -c "rm -rf '/path/to/dir'/*" exited with code 1.
```
I guess it will fail for any *nix sever that runs a shell other than bash.

The bug was introduced in #12849 which explicitly added bash as the name of the *nix shell.

**Comment by johan-ejstrud** [comment]
Hey @egor-bryzgalov and @damccorm do you know if I can somehow revert to using version 0.169.2 of CopyFileOverSSH?

**Comment by damccorm** [comment]
@johan-ejstrud there's not a way to pin to older versions of a task. This should be fixed by https://github.com/microsoft/azure-pipelines-tasks/pull/13105/files

**Comment by johan-ejstrud** [comment]
Thanks @damccorm! I'll close this issue once #13105 is completed.
