### ISSUE TITLE
Upload File to service connection using multipart/form-data mine type

### ISSUE THREAD

**Issue by sensslen** [microsoft/azure-pipelines-tasks#13103]
## Required Information
*Type*: Question
**Enter Task Name**: Bash@3, cURLUploader@2

## Environment
- Server - Azure Pipelines 

## Issue Description
As mentioned here: https://github.com/microsoft/azure-pipelines-tasks/issues/3792 a Shell Task should be used when multipart upload is required. Unfortunately I have not found any information on how to use a Azure Service connection (as possible with cURLUploader) in a bash script task.

Could you please redirect me to resources on how to use such a connection or alternatively consider reopening https://github.com/microsoft/azure-pipelines-tasks/issues/3792?

**Comment by sensslen** [comment]
As mentioned in https://github.com/microsoft/azure-pipelines-tasks/issues/11645 the service connections are not accessible from a bash task. Could you please advise me on teh possibilities I have to be able to upload a File using multipart/form-data mine type?

**Comment by ekaterina-tatanova** [comment]
It's not possible to use a service connection in a Bash Script task. You may store your credentials as [variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) or use [variable groups](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml).

**Comment by ekaterina-tatanova** [comment]
@sensslen It's not possible to use a service connection in a Bash Script task. You may store your credentials as [variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) or use [variable groups.](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)

**Comment by ekaterina-tatanova** [comment]
Please ping if you have any questions.
