### ISSUE TITLE
Error on Pull Request creation

### ISSUE THREAD

**Issue by ranouf** [microsoft/azure-pipelines-tasks#13100]
When I try to create a Pull Request on azure Dev Ops, I get the error:

> Failed to create pull request: Unexpected token < in JSON at position 4

How to fix it? or to access to the log?

![image](https://user-images.githubusercontent.com/1764519/84339967-99e61880-ab6d-11ea-966c-ca2c6582af74.png)

**Comment by ranouf** [comment]
I needed to logout and login back.

So the issue is: A message somewhere should indicates to the user what to do in this situation

**Comment by damccorm** [comment]
Hi @ranouf this looks like an issue with Azure DevOps more generally, not with a specific task. This repo is for task issues, please file issues with the larger service at https://developercommunity.visualstudio.com/spaces/21/index.html
