### ISSUE TITLE
Azure Resource Group Deployment fails on resource group delete (classic view)

### ISSUE THREAD

**Issue by Jaffacakes82** [microsoft/azure-pipelines-tasks#13119]
**Bug**  
Azure Resource Group deployment task fails when trying to delete a resource group with error:

`##[error]Error: Task failed while initializing. Error: Location is required for deployment`

**NOTE:** we're using the classic editor to configure this task as opposed to the YAML editor. There is no way to set the 'location' parameter in the classic editor for the `delete resource group` action. I also see in the documentation that 'location' is only mandatory for the `create or update resource group` action

**Enter Task Name**: Azure Resource Group Deployment V3

## Environment
- Server - Azure Pipelines
- Agent - Private

**Comment by anuragc617** [comment]
@Jaffacakes82 thank you for reporting this I am able to reproduce on my end. We will try to fix this asap.

**Comment by Jaffacakes82** [comment]
Looks like this is fixed, thanks!
