### ISSUE TITLE
Azure SQL Database deployment task : Include token based authentication for dacpac deployment

### ISSUE THREAD

**Issue by syedhamjath** [microsoft/azure-pipelines-tasks#13117]
## Note  
Requesting new feature for Azure SQL Database deployment task, when AuthenticationType is set to aadAuthenticationIntegrated. DACPAC deployment work only if ARM service connection was having users id and password auth. It does not work if ARM Service connection is based on SPN. 

At present, we generate token for https://database.windows.net to deploy dacpac file by passing additional parameter to SqlPackage.exe. Is it possible to include this token generation internally if the service connection is based on SPN.

Reference link:  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlAzureDacpacDeploymentV1/task.json
https://github.com/microsoft/azure-pipelines-tasks/blob/3ebee401e9838788f0faae53e8b32c08af894806/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1
https://github.com/microsoft/azure-pipelines-tasks/blob/961d90a3b8d4390ea62066ff601a0c3fbc8ea538/Tasks/SqlAzureDacpacDeploymentV1/Utility.ps1

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Task Name**: Azure SQL Database deployment

Source Code (V1 not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines

## Issue Description
When AuthenticationType is set to aadAuthenticationIntegrated. DACPAC deployment work only if ARM service connection was having users id and password auth. It does not work if ARM Service connection is based on SPN.

**Comment by hangar18rip** [comment]
Hi, the pull request #13770 has been merge to solve this issue
