### ISSUE TITLE
Authentication Errors in AzureBlob Copy task in Release pipeline

### ISSUE THREAD

**Issue by chaseWillden** [microsoft/azure-pipelines-tasks#13115]
## Note  
We've had no changes to our release pipeline or resource manager in question, but started getting errors today. Examples of errors received (all are at different times, we've had three distinct error messages for 5 tries). Messages below. We're using Azure Blob File Copy in hosted Azure Devops, and using Azure Resource Manager for connection to Subscription.

For a list:  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV3
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV2

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Bug**  
*Type*: Getting the errors:
```
ExceptionMessage: ExceptionMessage: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. (in function: Get-AzRmResourceGroup) (in function: Get-AzRMStorageKeys) 
There was an error with the service principal used for the deployment.
Upload to container: '$web' in storage account: 'redacted' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.'
```

## Environment
- Server - Azure Pipelines

2020-06-12T21:36:31.2629700Z Agent name: 'Hosted Agent'
2020-06-12T21:36:31.2630100Z Agent machine name: 'fv-az170'
2020-06-12T21:36:31.2630393Z Current agent version: '2.170.1'
2020-06-12T21:36:31.3041928Z ##[group]Operating System
2020-06-12T21:36:31.3042746Z Microsoft Windows Server 2016
2020-06-12T21:36:31.3042946Z 10.0.14393
2020-06-12T21:36:31.3043169Z Datacenter
2020-06-12T21:36:31.3044355Z ##[endgroup]
2020-06-12T21:36:31.3044649Z ##[group]Virtual Environment
2020-06-12T21:36:31.3044970Z Environment: windows-2016
2020-06-12T21:36:31.3046191Z Version: 20200604.1

## Issue Description

Someone else posted it here: https://developercommunity.visualstudio.com/content/problem/1076987/authentication-errors-in-azureblob-copy-task-in-re.html

**Comment by ramanagarwal2005** [comment]
We also started getting same error with v2 and upgrading the version to v4 didn't resolve it either.

**Comment by saffiali** [comment]
any update about this? When this will be resolved?

**Comment by arnauddrain** [comment]
I solved this by adding the role **Storage Blob Data Owner** to the Application that was linked to Azure Devops.
I found this solution in this thread: https://stackoverflow.com/a/60628323/4925750
