### ISSUE TITLE
Azure Copy V4 fails to authenticate with blob storage account

### ISSUE THREAD

**Issue by poctob** [microsoft/azure-pipelines-tasks#13124]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopyV4

## Environment
- Server - Azure Pipelines 
oneitp, Sole Proprietor, Saturnus-Dev, 8919
  
- Agent - Hosted 
 vs2017-win2016

## Issue Description

V4 task fails to authenticate with Azure Blob Container.

Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42

RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
This request is not authorized to perform this operation using this permission.

Downgrading to V3 solves the issue.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
2020-06-15T14:08:55.1905504Z ===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
2020-06-15T14:08:55.1909175Z Description=This request is not authorized to perform this operation using this permission.
2020-06-15T14:08:55.1911386Z RequestId:5d67390f-801e-0094-3f1e-435a1c000000
2020-06-15T14:08:55.1912051Z Time:2020-06-15T14:08:55.1837881Z, Details: 
2020-06-15T14:08:55.1912455Z    Code: AuthorizationPermissionMismatch
2020-06-15T14:08:55.1912981Z    PUT https://<Redacted>?timeout=901
2020-06-15T14:08:55.1919093Z    Authorization: REDACTED
2020-06-15T14:08:55.1919769Z    Content-Length: [470]
2020-06-15T14:08:55.1920207Z    User-Agent: [TFS_useragent AzCopy/10.3.3 Azure-Storage/0.7 (go1.13; Windows_NT)]
2020-06-15T14:08:55.1920692Z    X-Ms-Blob-Cache-Control: []
2020-06-15T14:08:55.1921054Z    X-Ms-Blob-Content-Disposition: []
2020-06-15T14:08:55.1921434Z    X-Ms-Blob-Content-Encoding: []
2020-06-15T14:08:55.1921803Z    X-Ms-Blob-Content-Language: []
2020-06-15T14:08:55.1922163Z    X-Ms-Blob-Content-Md5: []
2020-06-15T14:08:55.1922547Z    X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
2020-06-15T14:08:55.1922959Z    X-Ms-Blob-Type: [BlockBlob]
2020-06-15T14:08:55.1923357Z    X-Ms-Client-Request-Id: [7e944f59-c1c6-45e3-5010-43836dd68c9a]
2020-06-15T14:08:55.1923767Z    X-Ms-Version: [2018-03-28]
2020-06-15T14:08:55.1924192Z    --------------------------------------------------------------------------------
2020-06-15T14:08:55.1924731Z    RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
2020-06-15T14:08:55.1925180Z    Content-Length: [279]
2020-06-15T14:08:55.1934012Z    Content-Type: [application/xml]
2020-06-15T14:08:55.1934463Z    Date: [Mon, 15 Jun 2020 14:08:55 GMT]
2020-06-15T14:08:55.1934901Z    Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
2020-06-15T14:08:55.1935325Z    X-Ms-Error-Code: [AuthorizationPermissionMismatch]
2020-06-15T14:08:55.1935980Z    X-Ms-Request-Id: [5d67390f-801e-0094-3f1e-435a1c000000]
2020-06-15T14:08:55.1937028Z    X-Ms-Version: [2018-03-28]

**Comment by jgierveld** [comment]
[This post by Brett McKenzie](https://brettmckenzie.net/2020/03/23/azure-pipelines-copy-files-task-authentication-failed/) provide a resolution.

**Comment by poctob** [comment]
> 
> 
> [This post by Brett McKenzie](https://brettmckenzie.net/2020/03/23/azure-pipelines-copy-files-task-authentication-failed/) provides a resolution.

@jgierveld Many thanks for the workaround, steps listed in the link do indeed fix the issue.

This is still a bug though, the task is broken out of the box under normal circumstances and the need for additional storage permissions is not documented anywhere.

**Comment by 20shivangi** [comment]
@poctob Regarding storage permissions , this has been mentioned in doc here :
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#option-1-use-azure-active-directory

Please have a look at it

**Comment by LanceMcCarthy** [comment]
It took me almost 2 days to find this workaround. I agree with @poctob that this needs to be mentioned in DevOps when you choose the Task or provide a v5 that has a fix.

**Comment by poctob** [comment]
> 
> 
> @poctob Regarding storage permissions , this has been mentioned in doc here :
> https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#option-1-use-azure-active-directory
> 
> Please have a look at it

@20shivangi  I appreciate pointing out the documentation. However, I don't think that it is clear on how it is applicable to DevOps Pipeline task. You have to realize that Azure Copy is using AzCopy under the wraps, find documentation for AzCopy, then you have to piece together the facts that your pipeline is a standalone AD security principal and needs necessary permissions for storage. What makes it even more confusing is that V3 works fine out of the box.

IMO, this information should be stated in task summary on Devops as @LanceMcCarthy  mentioned and/or on in the README on github.
Unfortunately, this is an ongoing issue with Azure and Microsoft in general, documentation is either missing, outdated or plain wrong. Please take ownership of your products.

**Comment by richardorchard** [comment]
i have been stuck on the same issue for the past few hours....  Would be good if it was easier.  Following through with the Brett McKenzie solution seems to have changed recently in the Azure portal.  I got a 404 when trying to visit the "manage service connection" roles....

**Comment by vvoinov** [comment]
Faced same issue and even following the workaround and documentation did not work for me - very likely am missing smth so have to start from scratch. I appreciate the effort of MS folks and understand that maintaining documentation and keep it in sync with the code implementation details is a significant challenge however it just looks "strange" from the end-user perspective - the service looks like an alpha version and brings frustration. 😞 Have ended up switching to V3 temporarily to make the push to Blob Storage working.

**Comment by alvipeo** [comment]
Do not assign **Storage Blob Data Contributor** on a Subscription level. You may have a security issue. If you work with blob container you can assign this role to DevOps Service Principal for Storage account or even blob container.

**Comment by rosecodym** [comment]
I have also been unable to get the linked workaround to work, and had to use version 3 of the task.

**Comment by AmrutaKawade** [comment]
Updated document

**Comment by Paul-Dempsey** [comment]
More than the task readme needs to be updated -- the [documentation for the AzCopy task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops) needs to be updated. In addition the changes described in the readme aren't correct: the link to Azure from the UI goes to the IAM page at subscription, but the role assignment must be made at the Storage IAM, or lower at the Container's IAM.

**Comment by stephajn** [comment]
Straight up just downgrading to V3 worked for me when I came up against this issue. From a customer point of view, I look at V4 as being a broken version of the task.

**Comment by GaziIntelligentMachines** [comment]
Can anyone provide me a link to how to downgrade to v3?

**Comment by LanceMcCarthy** [comment]
@GaziIntelligentMachines at the top of the task settings there is a drop-down select v3.

If you're using YAML pipelines, just change the v4 number to v3 (in the name of the task).
