### ISSUE TITLE
GitHubRelease changelog generation should have support for PRs too

### ISSUE THREAD

**Issue by josesimoes** [microsoft/azure-pipelines-tasks#13128]
## Required Information

**Feature**  
*Type*: The task should allow generating changelog from PRs.

**Enter Task Name**: GitHubRelease

## Environment
- N/A

## Issue Description
- Some projects are organized in a way that issues are tracked on a separate repo and the "code" projects on different one(s). In this case it's not possible for this task to generate a changelog.
My sugegstion is to allow it to use PRs just like if those were issues.

**Comment by raiyanalam** [comment]
Thanks for the feedback. It makes sense and I have taken a note of this. However, we haven't heard of similar requirements from other users. So, I will keep an eye on this to see if other users also are facing similar challenges and prioritize this based on the demand. Closing this issue for now.

**Comment by josesimoes** [comment]
Revisiting this! Any plans to make this happen? 😃
