### ISSUE TITLE
Azure SQL Database Deployment task using DACPAC fails if deploying full-text catalog/index with /p:IncludeTransactionalScripts=False

### ISSUE THREAD

**Issue by cmeeren** [microsoft/azure-pipelines-tasks#13133]
When using the "Azure SQL Database Deployment" task and deploying a DACPAC file that contains a full-text-index, and the deployment uses the `/p:IncludeTransactionalScripts=True` parameter, the deployment fails. I assume with this parameter the full-text catalog/index is created after everything else, which would explain the error. [This SO question/answer mentions the same.](https://stackoverflow.com/questions/48204621/deploy-a-dacpac-that-contains-a-fulltext-index-with-msdeploy) The error I get is:

```
Error SQL72014: .Net SqlClient Data Provider: Msg 7601, Level 16, State 2, Procedure <name of stored procedure>, Line 8 Cannot use a CONTAINS or FREETEXT predicate on table or indexed view '<name of table>' because it is not full-text indexed.
Error SQL72045: Script execution error.  The executed script:
<stored procedure definition that uses CONTAINSTABLE>
```

I realize this probably isn't the right place for this bug, since it seems to be an `SqlPackage.exe` bug, but I was unable to find a better place to post an issue.

**Comment by Roshan-Kumar-Microsoft** [comment]
Can you please ask this question from here https://feedback.azure.com/forums/908035-sql-server/ ?

**Comment by cmeeren** [comment]
Posted: https://feedback.azure.com/forums/908035-sql-server/suggestions/40832233-azure-sql-database-deployment-task-using-dacpac-fa
