### ISSUE TITLE
AzureResourceManagerTemplateDeploymentV3 cannot successfully run the generated YAML for a delete action

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-tasks#13148]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeploymentV3   

list here (V# not needed):  

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

The task cannot successfully run the generated YAML for a delete action. 

1. Fill in the required fields: 
![image](https://user-images.githubusercontent.com/1784452/85069538-eb982f80-b179-11ea-8a2b-93122782bbf3.png)
  - NOTE: Location is not asked for

2. Add to a YAML pipeline and run

EXPECTED: The task deletes the RG

ACTUAL: Error found in logs
> ##[error]Error: Task failed while initializing. Error: Location is required for deployment

## Troubleshooting
I took a look at [the code](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/models/TaskParameters.ts#L93-L119) and `this.action` is being used before it has been correctly set.

**Comment by anuragc617** [comment]
Closing this, as PR has been merged and the fix will be deployed to all rings in a week or so.
