### ISSUE TITLE
Searching for best practices

### ISSUE THREAD

**Issue by ClaudeVernier** [microsoft/azure-pipelines-tasks#13168]
## Required Information
*Type*: Question
**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines 
- Agent - Private: vsts-agent-win-x64-2.166.4

## Issue Description
Hello, 
I am sorry if this isn’t the best place to ask questions but I’m so confused, I don’t know where to go anymore.

My task seems simple:
- Developers used GitHub to create a DotNetCore command prompt application
- I was asked to use Azure Pipelines to get the code from GitHub to a self-hosted agent
- Build the project, zip the binaries and move the zip file to Azure artefact 
- Build an Azure Release to get the latest version and extract the files to an intranet server accessible from the agent.

As we have firewall constraints we have setup a feed with an upstream source and a feed for our artifacts

I couldn’t restore from a build command, I had to do a NuGet Restore first:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: '33706eec-…-b948878fd368'
    verbosityRestore:  'Detailed'
    includeNuGetOrg: false

Next, I built my project: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-o $(Build.BinariesDirectory) --configuration $(buildConfiguration)'
    feedsToUse: 'select'
    vstsFeed: '33706eec-…-b948878fd368'
    includeNuGetOrg: false

I simply wanted to push the zip file to my feed but I had first to add a nuget.config then I tried the below task: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/filename_$(Build.BuildId).zip'
    nuGetFeedType: 'internal'
    publishVstsFeed: '33706eec-…-add95b24fdfd'
    publishPackageMetadata: false

It requested a NuGet package file so I tried to create one with:
- task: CmdLine@2
  displayName: 'Build package'
  inputs:
    script: dotnet pack --no-build --no-restore $(solution) -o $(Build.BinariesDirectory) /p:OutputPath=$(Build.ArtifactStagingDirectory)

It failed as this file is missing: .runtimeconfig.json

Could you please help me to find the best way to achieve my goal?  It seems to me that I don’t need to create packages as if it was to be given to the world, I only need to push the file but maybe it was not meant for that or I don’t see the full picture.

If you could help me or point me in the right direction, that would be so great!!!!

Thanks a lot, 
Claude

**Comment by NinadKavimandan** [comment]
Hi,

Can you try this task instead for generating Nuget package file:

### Package a project
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'

Source: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#package
