### ISSUE TITLE
Azure SQL Database Deployment task - Server/DataBase/Login names need to support secrets

### ISSUE THREAD

**Issue by mcalnd70** [microsoft/azure-pipelines-tasks#13163]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure SQL Database Deployment

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines

- Agent - Hosted: windows-latest

## Issue Description

The fields passed into this task such as... 

_**_Azure SQL Server
Database
Login_**_

...should all allow the passing of a variable as a secret. These details are as security sensitive as the password for just about every organisation.

## [error]
**Server name '***' is not in the correct format. Use a fully qualified domain name format like 'yyy.database.windows.net'**

**Comment by ruankr** [comment]
The password is also being displayed in clear text, regardless if locked or not, in the logs. This should not be the case.

**Comment by AmrutaKawade** [comment]
Logging of password as clear text is fixed https://github.com/microsoft/azure-pipelines-tasks/pull/13728

**Comment by AmrutaKawade** [comment]
Passing of login, database and server as a secret is also supported

**Comment by mcalnd70** [comment]
@AmrutaKawade Please post a link to show this please, rather than just closing it - thanks

Last time I tried it back in June 2020 this was not supported, so what has changed?

**Comment by ruankr** [comment]
@AmrutaKawade I think this needs to be re-opened. We are using Task groups and Libraries and I can see the password in clear text every time. So I think this is only solved (maybe, haven't tried) for direct variables on the task. 

Variable (Library):
![image](https://user-images.githubusercontent.com/63055439/100195536-6286e080-2eef-11eb-9b8e-7430ca022215.png)

Then within the Task group we specify the variable name:
![image](https://user-images.githubusercontent.com/63055439/100195591-7f231880-2eef-11eb-8c84-2f5314f8c392.png)

But when it runs I see this (blacked out for obvious reasons):
![image](https://user-images.githubusercontent.com/63055439/100195683-9a8e2380-2eef-11eb-8d60-851c4947d8de.png)

Please can you try or advise?

**Comment by AmrutaKawade** [comment]
can you tell me minor version of task which you are seeing in this run?

**Comment by ruankr** [comment]
@AmrutaKawade  

2020-11-24T12:17:09.6386954Z ==============================================================================
2020-11-24T12:17:09.6387420Z Task         : Azure SQL Database deployment
2020-11-24T12:17:09.6387819Z Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
2020-11-24T12:17:09.6388174Z Version      : 1.171.5
2020-11-24T12:17:09.6388475Z Author       : Microsoft Corporation
2020-11-24T12:17:09.6388910Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment

**Comment by AmrutaKawade** [comment]
Fix is in 1.178.0 minor version. Here is PR https://github.com/microsoft/azure-pipelines-tasks/pull/13728 wait till next week it will be deployed to your org
