### ISSUE TITLE
File transform cannot replace variable called "build"

### ISSUE THREAD

**Issue by AdrienCulem** [microsoft/azure-pipelines-tasks#13165]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: File transform  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/FileTransform

## Environment
- Server - Azure Pipelines 

- Agent - windows-2019

## Issue Description

When building an electron.NET application, I want to transform some things in a file called "electron.manifest.json". 

Those values are located in the nested variable called build, here I want to change the "appId"

```

{
    "build": {
        "appId" : "valueHere"
    }
}

```

In my pipeline I define a variable called "build.appId" as recommended by the fileTransform's doc. 

In the task log, it does find the file and changes some other values (not nested in "build") but it seems to ignore those that are in "build".

![image](https://user-images.githubusercontent.com/14331639/85376149-a4be8700-b537-11ea-884a-8a79089d100c.png)

**Comment by AmrutaKawade** [comment]
Some predefined variables are not replaced in this task.

> Predefined or build Variables are skipped during variable substitution. Hence, variables having prefix among ['agent.', 'azure_http_user_agent', 'build.', 'common.', 'release.', 'system.', 'tf_'] are ignored during variable substitution.


https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/FileTransformV2
