### ISSUE TITLE
Add support for include/exclude paths on schedule trigger

### ISSUE THREAD

**Issue by juanmalm** [microsoft/azure-pipelines-tasks#13160]
Having schedules trigger on a repo with more than one VS solution would be good to have the ability to configure the trigger including/excluding repo paths.

Right now only filter by branches is supported:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml

**Comment by damccorm** [comment]
Hi, this doesn't look like an issue with a specific task. For general issues/questions about the service that don't have to do with a specific task, please open a ticket here - https://developercommunity.visualstudio.com/spaces/21/index.html
