### ISSUE TITLE
AzureCLIV1 with variable values containing %X

### ISSUE THREAD

**Issue by dazinator** [microsoft/azure-pipelines-tasks#13161]
## AzureCLIV1 

When a variable value used in the inline script, contains %X it results in weird output.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLIV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
        - uniun
        - uniun
            - Uniun Website : 0.12.3-2-master

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-latest

## Issue Description

I use this task in a classing Release pipeline with the following inline script:

```
az webapp config appsettings set --name foo --resource-group foo --slot-settings Foo="$(foo)" 
Bar="$(bar)"
```

There are two variables there (I actually use a lot more but I have shortened for brevity).

When the value of $(foo) contains %X I see weird output. So suppose the value of $(foo) is "Hi%X" I then see this as the final az cli call being made:

```
az webapp config appsettings set --name foo --resource-group foo --slot-settings Foo="HiOTHER VARIABLE VALUES HERE"
```

In this case the value I am setting is a password, so it does contain symbols and in this case it happens to contain %X which is breaking the script.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anuragc617** [comment]
@dazinator this is expected behavior, you need to escape any special character before passing input to task. We are working on doing the escaping in the task itself.

**Comment by dazinator** [comment]
@anuragc617 how do I escape the value? There is no mention of the necessity to escape values in the docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops

**Comment by anuragc617** [comment]
@dazinator AzureCLIV1 uses batch files, so to escape them you can follow esacping guidelines for batch. I found this [link ](https://www.robvanderwoude.com/escapechars.php) useful for escaping batch files. For escaping % you need to give %%. You can also use AzureCLIV2 that supports various scripting languages. There also you will need to escape based on the language selected

**Comment by dazinator** [comment]
@anuragc617 
Ok thanks.
I can work around this issue by escaping password values and such myself. Obviously not ideal, but if you are working on escaping variables automatically within the task itself then I guess I can close this - if there is an issue already tracking that work?

**Comment by anuragc617** [comment]
@dazinator sorry we are not currently working on it, as it may break the existing user's pipeline who are escapping the characters manually. Whenever we will do such work we will mention that in release notes.

Closing this for now.

**Comment by dazinator** [comment]
@anuragc617 
> sorry we are not currently working on it, as it may break the existing user's pipeline who are escapping the characters manually

You could add a checkbox option to the task to "enable escaping" of variables? So that escaping could be "opted into" - that way it wouldn't break any existing user's pipelines if the feature was introduced?

**Comment by dazinator** [comment]
Escaping is a real problem, becuase for things like strong generated usernames / passwords. urls and other variables, there are always control characters that will be interpreted in the script. As these variables change in DevOps, it's so easy to miss a control character, especially if you are not even aware of the issue, or which particular scripting lanuage all of the tasks that may utilise that variable are using.

**Comment by dazinator** [comment]
I'll create a new issue.
