### ISSUE TITLE
Sonar Code Coverage deprecated report path

### ISSUE THREAD

**Issue by DevonBritton** [microsoft/azure-pipelines-tasks#13179]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - TFS on-premises
    
    - Version: Azure DevOps 2019 1.1 Update 3

- Agent - Private
    
    - OS of the machine running the agent and the agent version: Linux (ubuntu 16.04) - Agent v2.141.1
--
## Issue Description

Sonarqube is reporting 0% code coverage on some projects. Our suspicion is that the build step is contributing to the issue as it is still referencing "sonar.jacoco.reportPaths" property for code coverage which has been deprecated and should be replaced with "sonar.coverage.jacoco.xmlReportPaths" and use the xml report instead of the exec report as per "https://community.sonarsource.com/t/coverage-test-data-importing-jacoco-coverage-report-in-xml-format/12151"

![image](https://user-images.githubusercontent.com/33623085/85701615-dd986080-b6dd-11ea-8cf2-d4a1ad129cc8.png)

While we have tried specifying the "sonar.coverage.xmlReportPaths" in the build step argument the log files clearly show the deprecated file also being used.

![image](https://user-images.githubusercontent.com/33623085/85701881-24865600-b6de-11ea-83fb-fe222b336239.png)

Kind Regards,
Devon Britton.

**Comment by hvinett** [comment]
hey @DevonBritton , can you provide a sample small project with pipeline setup and share it? that could be easy for us?

**Comment by DevonBritton** [comment]
> hey @DevonBritton , can you provide a sample small project with pipeline setup and share it? that could be easy for us?

Hi @hvinett .

I appreciate the response. I see this is being dealt with in the following PR so I think my issue can be closed or linked to that. 

https://github.com/microsoft/azure-pipelines-tasks/pull/12122

Kind Regards,
Devon Britton.

**Comment by hvinett** [comment]
@DevonBritton , yes https://github.com/microsoft/azure-pipelines-tasks/pull/12122 seems like the correct fix.  we are closing this issue from our side.
Thank you,
vineeth
