### ISSUE TITLE
Error trying to sync Azure Storage Account container via Azure DevOps

### ISSUE THREAD

**Issue by zjpiazza** [microsoft/azure-pipelines-tasks#13182]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure CLI  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
   Azure Pipelines
  

- Agent - Hosted or Private: 
    
    - Not sure where to find agent queue name
       

## Issue Description

Trying to upload build artifacts from my React application via release pipeline Azure CLI task. First I tried using the Azure Storage Copy task however that creates a subfolder "build" instead of placing those files in the root $web container. I really don't understand why I'm encountering so many problems trying to get this to work, I figured this is a fairly standard pipeline process?
Please enlighten me if I'm missing something

### Task logs

[tasklog_6.log](https://github.com/microsoft/azure-pipelines-tasks/files/4833409/tasklog_6.log)

### Error logs

2020-06-25T19:07:33.4259526Z error parsing the input given by the user. Failed with error service level URLs (https://videoeffects.blob.core.windows.net) are not supported in sync:

**Comment by kensington133** [comment]
Also having this issue on my Mac with a Vue project, but a colleague on a Windows machine is able to use the same command just fine.

My command: `az storage blob sync -c "$web" --account-name {account name} -s "/Users/benshort/Sites/site-name/dist"`

Windows command: `az storage blob sync -c $web --account-name {account name} -s "C:\Users\Name\Sites\site-name\dist"`

Had initial issues with `$web` and had to use quotes but then ran into this issue, any advice is greatly appreciated 😄

**Comment by anuragc617** [comment]
@zjpiazza Azure CLI does not modify or append path to your script. I tested az storage copy, it works fine. How are you generating the folder to copy, can you please share you script?

**Comment by anuragc617** [comment]
@kensington133 are you using Azure pipelines agent to run these commands?

**Comment by zjpiazza** [comment]
I ended up going with a different deployment method instead of using Azure storage accounts. I ended up figuring out my problem using "azure storage blob sync". I forget the exact command I use as I ended up deleting that release pipeline after changing deployment strategies.

**Comment by spanditcaa** [comment]
In case anyone else comes across this issue - a resolution for mac & linux is to single quote (') the container name.
```
az storage blob sync -c '$web' --account-name {account name} -s '/stuff'
```
