### ISSUE TITLE
[Feature Request] Support tenant level deployment on AzureResourceGroupDeploymentV3

### ISSUE THREAD

**Issue by yesoreyeram** [microsoft/azure-pipelines-tasks#13192]
Is it possible to do the tenant level deployment using AzureResourceGroupDeploymentV3 task ?

**Comment by anuragc617** [comment]
@pulkitaggarwl @bishal-pdMSFT please have a look at this ask?

**Comment by bishal-pdMSFT** [comment]
No, it is not possible currently and we do not have this item in near term.
