### ISSUE TITLE
cannot sync directory files to Azure Blob storage container

### ISSUE THREAD

**Issue by kcherewyk** [microsoft/azure-pipelines-tasks#13190]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure File Copy 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows agent version 2.170.1

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I am trying to use the sync feature in AzCopy 10.3.3 to sync an artifact directory to an Azure storage account static site container. however, when I add the sync command to the additional arguments field I get a "wrong number of arguments error". Is there a way to use the sync feature with  task? 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
2020-06-26T20:30:34.3094028Z Uploading files from source path: 'C:\Builds\_work\r2\a\_Documentation\site' to storage account: 'developerportalintwestus' in container: '$web' with blob prefix: ''
2020-06-26T20:30:34.3153436Z ##[command] & "AzCopy\AzCopy.exe" copy "C:\Builds\_work\r2\a\_Documentation\site" "https://developerportalintwestus.blob.core.windows.net/`$web"  sync
2020-06-26T20:30:34.3419982Z Error: wrong number of arguments, please refer to the help page on usage of this command
2020-06-26T20:30:34.3431663Z Usage:
2020-06-26T20:30:34.3432643Z   azcopy copy [source] [destination] [flags]
2020-06-26T20:30:34.3433843Z 
```
[Insert error from the logs here for a quick overview]

**Comment by arjgupta** [comment]
@kcherewyk from the logs of the Azure File Copy that you are executing you can see the exact azcopy command that is being run. You can try to copy this and run it on the command line. It should fail with a similar error. What might be happening is that we from task side also append some arguments to azcopy depending on the inputs given to the task and it is possible that you are specifying some additional arguments which might not be compatible causing azcopy to fail.

**Comment by kcherewyk** [comment]
I realize that the Copy command is being run in the task. I was trying to use the **Azcopy.exe sync** command that's available in the newer versions of Az copy, If that command is not available in this task, I guess this isn't a bug but a feature request.

**Comment by AmrutaKawade** [comment]
In Azure Copy Task only `azcopy copy` command is supported, not `azcopy sync`. there is no plan currently to support this. Latest version of AzCopy.exe is available on agents, you can use command line instead to perform this operation
