### ISSUE TITLE
“TypeError: Cannot read property ‘locationServiceData’ of null” on Azure DevOps

### ISSUE THREAD

**Issue by antoniovs1029** [microsoft/azure-pipelines-tasks#13200]
Hi,

I am having an error coming from the NuGetAuthenticate task in one of my team’s pipelines on Azure DevOps; it has only happened in 4 of our last 30 builds, so it doesn't seem to be a persistent problem. I am not sure if this is the right place to address this, but please let me know if you think I should contact someone else to address this problem.

I am a member of the ML.net team, and we have recently added a couple of steps to one of our pipelines to publish nugets to the following public feed:
https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=MachineLearning

The steps that we added are the following, and notice that one of them is the NuGetAuthenticate task
```
  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: machinelearning-dnceng-public-feed # To allow publishing to a feed of another organization

  - script: Tools\dotnetcli\dotnet msbuild build\publish.proj /t:PublishPackages /p:NuGetFeedUrl=$(_AzureDevopsFeedUrl) /p:NuGetApiKey=AzureArtifacts
    displayName: Publish Packages to AzureDevOps Feed
```
You can find our complete pipeline in here: https://github.com/dotnet/machinelearning/blob/36fab9b6806260e64e50992450a219e869c7f74a/build/vsts-ci.yml#L236

Problem is that in 4 of our last 30 builds, we have received the following error when the pipline runs the step of installing NuGetAuthenticate: **“TypeError: Cannot read property ‘locationServiceData’ of null”**, this happens even before publishing to the public feed. The output of the failed task is the following:
```
##[section]Starting: NuGetAuthenticate
==============================================================================
Task         : NuGet authenticate
Description  : Configure NuGet tools to authenticate with Azure Artifacts and other NuGet repositories. Requires NuGet >= 4.8.5385, dotnet >= 2.1.400, or MSBuild >= 15.8.166.59604
Version      : 0.159.0
Author       : Microsoft Corporation
Help         : https://aka.ms/NuGetAuthenticateTask
==============================================================================
Installing the Azure Artifacts Credential Provider (.NET Core) to 'C:\Users\dlab14\.nuget\plugins\netcore\CredentialProvider.Microsoft'. This credential provider is compatible with dotnet SDK 2.1.400 or later.
The credential provider is already installed. If there are package related authentication failures in later steps, consider setting this task's input 'forceReinstallCredentialProvider' to true to force reinstallation.

Installing the Azure Artifacts Credential Provider (.NET Framework) to 'C:\Users\dlab14\.nuget\plugins\netfx\CredentialProvider.Microsoft'. This credential provider is compatible with nuget.exe 4.8.0.5385 or later, and MSBuild 15.8.166.59604 or later.
The credential provider is already installed. If there are package related authentication failures in later steps, consider setting this task's input 'forceReinstallCredentialProvider' to true to force reinstallation.

1ea4b80d-53b6-4fde-9abb-4fe4930685a6 exists true
SYSTEMVSSCONNECTION exists true
##[error]TypeError: Cannot read property 'locationServiceData' of null
##[section]Finishing: NuGetAuthenticate
```

So I was requested to figure out why this is happening and to try to prevent this to happen in the future. Since it has happened only a couple of times, it doesn’t seem to be a persistent problem, butI would like to know if any of you recognizes this error and could give me pointers as to why this happens sometimes. Also I’ve noticed that right before the error occurs, the task actually suggests to set the task’s input “forceReinstallCredentialProvider” to true, but I would like to know if this would actually help to avoid the error.

Thanks

**Comment by herenhuang** [comment]
Moving to the Azure Pipelines repo to review.

**Comment by edgarrs** [comment]
Issue tracked in Azure Pipelines repo
