### ISSUE TITLE
Make powershell tasks support nuget credential provider in PowershellGet

### ISSUE THREAD

**Issue by dpurge** [microsoft/azure-pipelines-tasks#13215]
# Suggestion for a new feature

## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: 

- NuGetAuthenticate
- PowerShellOnTargetMachines
- PowerShell

## Environment

- Server - both Azure Pipelines and TFS on-premises
- Agent - both Hosted and Private

## Issue Description

Running NuGetAuthenticate during the build installs nuget credential provider which provides credentials necessary to access nuget feeds hosted in Azure Artifacts. It works for nuget.exe, dotnet.exe and Visual Studio. 

It does not work for PowershellGet, which is downloading Powershell modules from nuget feeds (Find-Module, Install-Module, Save-Module). If a company has its own custom modules, they could place them on unauthenticated feed (or use pre-authenticated url) and register it with Register-PsRepository and then install modules from that feed. Or they could use a feed that requires authentication which could be provided as a Credential parameter.

None of this works with Azure Artifacts, where you have to use personal access token. I have not found a way to use normal Powershell commands to install modules from PsRepository hosted in Azure Artifacts.

Can you make it so that we could use NuGetAuthenticate to set up credential provider for a private PsRepository feed in Azure Artifacts,  and later in PowerShell task we could use Install-Module cmdlet to install modules from that feed?

**Comment by jmyersmsft** [comment]
I believe it should work, actually, but you might have to add a task to upgrade PowerShellGet. Only newer versions of PSGet support the credential provider, and the version provided with Windows in the agent image may not be new enough.

**Comment by temelj** [comment]
Does it work behind a proxy? 😝

**Comment by phil-hodgson** [comment]
As far as aquiring credentials, it should. Whether subsequent PowerShellGet operations work behind a proxy is a question for a PowerShellGet forums.
