### ISSUE TITLE
Am facing an  error like  "application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)".  Can anyone please suggest.

### ISSUE THREAD

**Issue by hrushidevops** [microsoft/azure-pipelines-tasks#13212]
Hi All,
I have tried to pass "TriggerTime":0 */2 * * * * as environment variable  to azure function using Azure Devops. But,Am facing an  error like  "application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)".  Can anyone please suggest.

For workaround, updating "Trigger Time" manually at Config Tab in Azure Function. Please suggest permanent solution for this.

Thanks In Advance.

_Originally posted by @hrushidevops in https://github.com/microsoft/azure-pipelines-tasks/issues/7799#issuecomment-652268361_

**Comment by ds-ms** [comment]
Closing this stale issue. Feel free to reopen if the problem still persists
