### ISSUE TITLE
xcodebuild failed with return code: 65

### ISSUE THREAD

**Issue by lucascardosods** [microsoft/azure-pipelines-tasks#13210]
## Note  
I'm trying to build my project in azure pipelines, it was working but at some point stopped...
- The exactly same command in my Mac, with the same repo, is returning **BUILD SUCCESS.**
- I have tried every single profile from my apple developer account.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: # Build, test, and archive an Xcode workspace on macOS.  

## Environment
- Agent - Hosted or Private: 
    
 - Hosted macOS pool

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

**COMMAND**
/usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace /Users/runner/runners/2.170.1/work/1/s/X -scheme X clean build -UseModernBuildSystem=NO CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=X

**YML**
trigger:
- release

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '001.p12'
    keychain: 'temp'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '003.p12'
    keychain: 'temp'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '002.p12'
    keychain: 'temp'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'x-dev-p12.p12'
    keychain: 'temp'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'x.mobileprovision'
- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/x.xcworkspace'
    scheme: 'X'
    packageApp: true
    archivePath: 'output/ipa'
    signingOption: 'auto'
    teamId: 'x'
    args: '-UseModernBuildSystem=NO'

### Error logs

2020-06-21T02:46:20.2809510Z â–¸ Compiling Pods-x-dummy.m
2020-06-21T02:46:20.2857060Z â–¸ Compiling x
2020-06-21T02:46:20.2921050Z â–¸ Touching x
2020-06-21T02:46:20.2929000Z â–¸ Building x/x [Release]
2020-06-21T02:46:20.2930260Z â–¸ Check Dependencies
2020-06-21T02:46:20.4729030Z ** BUILD FAILED **
2020-06-21T02:46:20.4730640Z 
2020-06-21T02:46:20.4731150Z 
2020-06-21T02:46:20.4731460Z The following build commands failed:
2020-06-21T02:46:20.4731740Z 	Check dependencies
2020-06-21T02:46:20.4734530Z (1 failure)
2020-06-21T02:46:20.5125270Z ##[error]Error: /usr/bin/xcodebuild failed with return code: 65
2020-06-21T02:46:20.5543050Z ##[section]Finishing: Xcode

----

**Comment by alexander-prozorov** [comment]
Hello, @lucascardosods!

Generally, error 65 can indicate problems with the signing process. In some cases, this can be solved using the manual signing option. Provisioning profile id is required for manual signing.

```
signingOption: 'manual'
provisioningProfileUuid: ***
```

Could you please also provide the xcodebuild version you are using?

Information about xcode build and release task is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops
)

**Comment by alexander-prozorov** [comment]
Hello @lucascardosods,

сan you please confirm if this problem is still relevant?

**Comment by alexander-prozorov** [comment]
Closing stale issue. Feel free to reopen if the problem still persists.
