### ISSUE TITLE
NuGetCommandV2 - Won't restore both package.config and PackageReference must run two task to hit both

### ISSUE THREAD

**Issue by danagarcia** [microsoft/azure-pipelines-tasks#13217]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetCommandV2 - Won't restore both package.config and PackageReference must run two task to hit both package management models.

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: N/A
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: contact dangarc@microsoft.com for info

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name: N/A

    - If using private agent, provide the OS of the machine running the agent and the agent version: Win10, 2.169.1

## Issue Description

[Include task name(s), screenshots and any other relevant details]

I have a project with multiple solutions, some solutions utilize package.config others utilize PackageReference. When I attempt to run a restore command via NuGetCommand@2 using:

```
- task: NuGetCommand@2
  displayName: 'Restore NuGet Dependencies'
  inputs:
    restoreSolution: '**\*.sln'
    feedsToUse: 'config'
    command: 'restore'
```
it defaults to PackageReference and doesn't restore nuget dependencies within package.config files. To get around this I've added another NuGetCommand@2 task with the same inputs; however, I added `nugetConfigPath: 'nuget.config'` and added the necessary data within my nuget.config file to force a restore of package.config.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by jmyersmsft** [comment]
This would be an issue with nuget.exe itself, not the NuGetCommandV2 task. Consider filing an issue against NuGet itself at https://github.com/NuGet/Home/issues .
