### ISSUE TITLE
[question] where is the checkout task? Is checkout a task?

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/azure-pipelines-tasks#13222]
**Question, Bug, or Feature?**  
*Type*: Questions

**Enter Task Name**: checkout  

## Description
Like ~1.5 weeks ago we started started having some really weird checkout errors with lfs files, git just simply not replacing lfs pointer with their real contents.

I was hoping to be able to inspect the checkout task but I could not find it, could someone point me out where is it located

**Comment by damccorm** [comment]
Hey @FrancescElies the checkout task is a little odd in that it lives as a plugin on the agent. I'd recommending asking any questions in that repo - https://github.com/microsoft/azure-pipelines-agent/tree/master/src/Agent.Plugins
