### ISSUE TITLE
[Feature Request] Consider enabling MSDEPLOY_RENAME_LOCKED_FILES for on-premise apps

### ISSUE THREAD

**Issue by thurfir** [microsoft/azure-pipelines-tasks#13223]
Hi, would it be possible to add the Rename locked files option to the "IIS web app deploy" release task?

This option is currently only available for the Azure App Service deploy task.

**Comment by joseotavioq** [comment]
It would be nice if we have this feature!

**Comment by cetindogu** [comment]
Please add the Rename locked files option to the "IIS web app deploy" release task

**Comment by thurfir** [comment]
Up to prevent this issue being closed.

**Comment by cetindogu** [comment]
Please add the Rename locked files option to the "IIS web app deploy" release task

**Comment by thurfir** [comment]
Up to prevent this issue being closed.

**Comment by Banner-Keith** [comment]
Please reopen this issue. It has not been resolved.
