### ISSUE TITLE
[Azure File Copy] Microsoft.Rest.SerializationException: Unable to deserialize the response.

### ISSUE THREAD

**Issue by asranja** [microsoft/azure-pipelines-tasks#13225]
The Azure File Copy versions V2.171.1 and V3.171.1 could fail with the error:
**##[debug]Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "FileStorage" to type 'System.Nullable`1[Microsoft.Azure.Management.Storage.Models.Kind]'. Path '', line 1, position 19442. ---> System.ArgumentException: Requested value 'FileStorage' was not found.**

**Comment by asranja** [comment]
The current mitigation is to use Azure File Copy V4 of the task. 

To use V4, the Service Principal needs to also have **Storage Blob Data Contributor** permissions on the Storage account. This is because of AzCopy.exe logging in using the Service Principal Credentials in V4 task. More details on [Azure File Copy V4 task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops) and [roles](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#option-1-use-azure-active-directory).

AzureFileCopyV4 task is based on new Az modules as opposed to older AzureRm modules. V4 is the way going forward.

We are currently working on fixing versions 2 and 3 of the task.

**Comment by chshrikh** [comment]
@asranja did we started hot fix for this?

**Comment by AmrutaKawade** [comment]
This is been fixed. closing this issue
