### ISSUE TITLE
Azure App Service deploy task with "Take App Offline" feature and custom app_offline.htm

### ISSUE THREAD

**Issue by MursalovAltun** [microsoft/azure-pipelines-tasks#13231]
Bug

Task Name: Azure App Service deploy V3

Azure Pipelines:

1. Account name - 2bit
2. Team project name - 2payroll
3. Build name - dev
4. Build number - Release-1335

Agent - Hosted Agent

If we enable the Take App Offline feature it works as expected:
- generates App_Offline.htm
- removes App_Offline.htm after deployment

But the problem is that, when we provide custom app_offline.htm in root of our application it does not remove this file after deployment. And because of existence of app_offline.htm server always returns this html.

In the screenshot below, in Kudu diagnostic console we can see that the custom App_Offline.htm is exist and has not been removed after deployment.
![image](https://user-images.githubusercontent.com/49729625/86465151-2b4a4400-bd42-11ea-9e88-462c56809fbe.png)

### Error logs

There are no logs with failure. It just silently does not remove the custom app_offline.htm

**Comment by MursalovAltun** [comment]
The default app_offline.htm is totally useless for users and says nothing because it has empty <body> tag with title "Site Under Construction"

**Comment by arjgupta** [comment]
@MursalovAltun the task does not work with a custom app offline file. The task does not delete the custom app offline file because it is not aware about the custom app offline file. What you can do is the deploy the app to a slot and then post deployment you can perform a swap slot.

**Comment by lkosidlo** [comment]
Hi,
We used Post Deployment Action and Deployment script to remove that file after deployment 

![image](https://user-images.githubusercontent.com/15377352/214337396-e8465d1d-afd5-4463-8337-434c5684ff9c.png)
