### ISSUE TITLE
Azure CLI Pipeline Task mutliple files / variables files

### ISSUE THREAD

**Issue by keamas** [microsoft/azure-pipelines-tasks#13236]
​Hi, I m using a Release Pipeline with the Aure CLI Pipeline Task: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV2

I am using a separate variable.sh file

and a rg.sh where I have my az commands just as an example.

like:

variables.sh

```
LOCATION='westeurope'

RG_NAME='test'
```
rg.sh
```
#!/bin/bash 
#Load Variables File 

source variables.sh 
az group create --l $LOCATION --n $RG_NAME 
```
Is there any way to first load the variables.sh into the pipeline and than execute the az command script.

The other idea is to use the bash task called main.sh and execute the variable.sh first and than the rg.sh.

main.sh File

```
az login ...

./variables.sh

./rg.sh

```
What is the best way to work with this setup and multiple files? Can anyone help me here, please?

**Comment by bishal-pdMSFT** [comment]
Can you use main.sh file Azure CLI task without the first line of login
