### ISSUE TITLE
[Bug] npmAuthenticate@0 throws warning: Found and overrode credentials for the {org}.pkgs.visualstudio.com

### ISSUE THREAD

**Issue by ZhimaoLin** [microsoft/azure-pipelines-tasks#13241]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NpmAuthenticateV0  

## Environment
- Server: Azure Pipelines
- Agent: Hosted 

## Issue Description

I am using `NpmAuthenticateV0` to authenticate to my Azure Artifact Feed.
When I run `NpmAuthenticateV0` on my `.npmrc` file, it gives me the following warning:
```
##[warning]Found and overrode credentials for the {org}.pkgs.visualstudio.com registry in the selected .npmrc file. Remove credentials from the file and store them in an npm service connection instead (recommended), or remove the npm Authenticate task from your build to use credentials checked into an .npmrc.
```

It seems `NpmAuthenticateV0` authenticates twice for the same registry URL.

NpmAuthenticateV0 task:
```
- task: npmAuthenticate@0
  displayName: 'NPM Authenticate'
  inputs:
    workingFile: '.npmrc'
```

.npmrc (The URL of `registry` is the same as the URL of `@myscope:registry`)
```
registry=https://{org}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/ 
@myscope:registry=https://{org}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/
always-auth=true
```

## Expected Behavior

The warning should be suppressed since I was authenticating the same registry at the second time.

**Comment by sbley** [comment]
I can confirm this issue and would like to get it solved.

**Comment by devops-ninja2021** [comment]
Same issue here. We have one repo with multiple scopes.

**Comment by beatcracker** [comment]
Please re-open, the issue is still there if you have multiple scopes defined for single registry.

**Comment by zhenghao104** [comment]
Fix https://github.com/microsoft/azure-pipelines-tasks/pull/17743
