### ISSUE TITLE
Update warning message for out of support runtimes

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/azure-pipelines-tasks#13252]
*Type*: Bug

**Enter Task Name**: In mseng source, the loc files are under Localization/GitHub/**BuildTask**

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description
Two things.  1. There's a typo in this error message: "requied". 2. We are switching .net core to use "(out of support)" instead of EOL.  The work is already checked in for the VS setup UI for July releases.  Our work to update our website is still in progress.  This was guidance from design that EOL is typically used as "end of life" which besides being morbid, is less accurate than out of support.

".NET Core SDK/runtime 2.2 is now End of Line(EOL) and will be removed from all agents by end of March, 2020. If you're using 2.2 SDK/runtime, kindly upgrade to newer versions which are not EOL or use UseDotNet task to install the requied version."

### Task logs

![outofsupport](https://user-images.githubusercontent.com/12663534/87075145-c163eb80-c1d4-11ea-865a-5bff3986d65b.png)

**Comment by bishal-pdMSFT** [comment]
@tejasd1990 another issue related to versioning message

**Comment by bishal-pdMSFT** [comment]
We have changed 'end of line' to 'end of life' and fixed the other typo.
The .net core download page still uses 'end of life' so it seems to okay use same in task for now.
