### ISSUE TITLE
DownloadBuildArtifacts has incomplete downloads with no errors

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-tasks#13250]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: DownloadBuildArtifactsV0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Example build: See "Libraries Test Run release coreclr Windows_NT x64 Debug" in
https://dnceng.visualstudio.com/public/_build/results?buildId=722532&view=logs&j=694d544e-ff71-5faf-b01a-5137c04e57c6&t=e3fd78b8-f38c-5ce4-3c18-7a68a40fe399

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Private - Windows Server 2019

## Issue Description

```
Starting: Download Test Assets
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 0.167.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
==============================================================================
Downloading artifacts for build: 722532
Downloading items from container resource #/4554312/libraries_test_assets_Windows_NT_x64_Debug
Downloading artifact libraries_test_assets_Windows_NT_x64_Debug from: https://dev.azure.com/dnceng//_apis/resources/Containers/4554312?itemPath=libraries_test_assets_Windows_NT_x64_Debug&isShallow=true&api-version=4.1-preview.4
Downloading libraries_test_assets_Windows_NT_x64_Debug/libraries_test_assets_Windows_NT_x64_Debug.zip to F:\workspace\_work\1\s\__download__\libraries_test_assets_Windows_NT_x64_Debug\libraries_test_assets_Windows_NT_x64_Debug.zip
Downloaded libraries_test_assets_Windows_NT_x64_Debug/libraries_test_assets_Windows_NT_x64_Debug.zip to F:\workspace\_work\1\s\__download__\libraries_test_assets_Windows_NT_x64_Debug\libraries_test_assets_Windows_NT_x64_Debug.zip
Total Files: 1, Processed: 1, Skipped: 0, Failed: 0, Download time: 1819.658 secs, Download size: 199.113MB
Successfully downloaded artifacts to F:\workspace\_work\1\s/__download__
Finishing: Download Test Assets
```
... but the file at `https://dev.azure.com/dnceng/_apis/resources/Containers/4554312?itemPath=libraries_test_assets_Windows_NT_x64_Debug%2Flibraries_test_assets_Windows_NT_x64_Debug.zip` is 365 MB, so in the next step when it tries to unzip:

```

ERROR: Data Error : helix\tests\Windows_NT.AnyCPU.Debug\System.IO.Compression.ZipFile.Tests.zip
 
error: undefined;
##[error]Extraction failed for file: F:\workspace\_work\1\s\__download__\libraries_test_assets_Windows_NT_x64_Debug\libraries_test_assets_Windows_NT_x64_Debug.zip 
code: 2 

```

[Include task name(s), screenshots and any other relevant details]

### Task logs

See linked build.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by MattGal** [comment]
Another incidence: https://dev.azure.com/dnceng/public/_build/results?buildId=742988&view=logs&j=694d544e-ff71-5faf-b01a-5137c04e57c6&t=e3fd78b8-f38c-5ce4-3c18-7a68a40fe399

**Comment by MattGal** [comment]
Hi @romil07 and @ashokirla ... any progress on fixing this issue ?

Recent incidence:  https://github.com/dotnet/runtime/pull/44392/checks?check_run_id=1376226460

**Comment by danmosemsft** [comment]
Direct link for one above https://dev.azure.com/dnceng/public/_build/results?buildId=879840&view=logs&jobId=b62b1571-aad0-50ee-4a73-da3c82a85c95&j=b62b1571-aad0-50ee-4a73-da3c82a85c95&t=35455d84-638c-5332-d211-8e460f5d43ab&s=d654deb9-056d-50a2-1717-90c08683d50a

**Comment by zachariahcox** [comment]
in the json that comes back from the above preview API, we can see the file length is way higher than the actual downloaded bytes. 
From the related ICM, 177158735, Luke checked that the server actually sent all the bytes, so it's still likely that a networking problem is to blame here. 
Regardless, it seems reasonable to check that the downloaded bytes match the expected bytes and retry if it didn't work. 

{
count: 2,
value: [
{
containerId: 5674752,
scopeIdentifier: "9ee6d478-d288-47f7-aacc-f6e6d082ae6d",
path: "libraries_test_assets_windows_x64_Debug",
itemType: "folder",
status: "created",
dateCreated: "2020-12-01T15:07:37.92Z",
dateLastModified: "2020-12-01T15:07:37.92Z",
createdBy: "108d6ec7-54d3-4670-84e2-4ce39637fdca",
lastModifiedBy: "108d6ec7-54d3-4670-84e2-4ce39637fdca",
itemLocation: "https://dev.azure.com/dnceng/_apis/resources/Containers/5674752?itemPath=libraries_test_assets_windows_x64_Debug&metadata=True",
contentLocation: "https://dev.azure.com/dnceng/_apis/resources/Containers/5674752?itemPath=libraries_test_assets_windows_x64_Debug",
contentId: ""
},
{
containerId: 5674752,
scopeIdentifier: "9ee6d478-d288-47f7-aacc-f6e6d082ae6d",
path: "libraries_test_assets_windows_x64_Debug/libraries_test_assets_windows_x64_Debug.zip",
itemType: "file",
status: "created",
fileLength: 422216680,
fileEncoding: 1,
fileType: 1,
dateCreated: "2020-12-01T15:07:37.917Z",
dateLastModified: "2020-12-01T15:08:18.907Z",
createdBy: "108d6ec7-54d3-4670-84e2-4ce39637fdca",
lastModifiedBy: "108d6ec7-54d3-4670-84e2-4ce39637fdca",
itemLocation: "https://dev.azure.com/dnceng/_apis/resources/Containers/5674752?itemPath=libraries_test_assets_windows_x64_Debug%2Flibraries_test_assets_windows_x64_Debug.zip&metadata=True",
contentLocation: "https://dev.azure.com/dnceng/_apis/resources/Containers/5674752?itemPath=libraries_test_assets_windows_x64_Debug%2Flibraries_test_assets_windows_x64_Debug.zip",
fileId: -478404985,
contentId: ""
}
]
}

**Comment by alexander-smolyakov** [comment]
@MattGal, the [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14065) with the fix was merged. I'll let you know once the fix is deployed.

**Comment by MattGal** [comment]
@alexander-smolyakov Good news: I see it's getting used (https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/992064/logs/2063 ) 

Less good news:  the retry never returned and timed out almost 2 hours later:

```
2021-02-12T15:16:40.2119638Z Downloading CoreCLRProduct__Linux_musl_arm_release/CoreCLRProduct__Linux_musl_arm_release.tar.gz to /datadisks/disk1/workspace/_work/1/s/__download__/CoreCLRProduct__Linux_musl_arm_release/CoreCLRProduct__Linux_musl_arm_release.tar.gz
2021-02-12T15:17:09.5541543Z Retrying download of CoreCLRProduct__Linux_musl_arm_release/CoreCLRProduct__Linux_musl_arm_release.tar.gz, retry count: 1
2021-02-12T15:17:24.7464039Z Downloading CoreCLRProduct__Linux_musl_arm_release/CoreCLRProduct__Linux_musl_arm_release.tar.gz to /datadisks/disk1/workspace/_work/1/s/__download__/CoreCLRProduct__Linux_musl_arm_release/CoreCLRProduct__Linux_musl_arm_release.tar.gz
2021-02-12T17:15:00.4378458Z ##[error]The operation was canceled.
2021-02-12T17:15:00.4388524Z ##[section]Finishing: Download CoreCLR artifacts
```
Since a successful retry is hard to find (as it'd be a successful pipeline), this may just be a one-off, but letting you know that it's seemingly rolled out and it might be worth checking out to see if the changes could be involved in the timeout here.

**Comment by alexander-smolyakov** [comment]
@MattGal, thank you for the info, as I can see from the logs task version is 0.178.0, however, a task with the fix will have a 0.183.0 version. A release for the 183rd sprint will start this Friday.

**Comment by MattGal** [comment]
> @MattGal, thank you for the info, as I can see from the logs task version is 0.178.0, however, a task with the fix will have a 0.183.0 version. A release for the 183rd sprint will start this Friday.

Thanks for clarifying.  One follow-up question; does this mean there actually was already some retry logic before this change?  (had never seen evidence of a retry being attempted, just silent quitting)

**Comment by alexander-smolyakov** [comment]
> One follow-up question; does this mean there actually was already some retry logic before this change? (had never seen evidence of a retry being attempted, just silent quitting)

The `DownloadBuildArtifacts` task uses the [Artifact Engine](https://github.com/microsoft/azure-pipelines-extensions/tree/master/Extensions/ArtifactEngine) to download artifacts from Azure DevOps. As I can see from logs, this retry attempt was triggered by the engine itself, not the task. If this problem reappears, could you please create a separate ticket for it?

**Comment by MattGal** [comment]
Will do, thanks

**Comment by alexander-smolyakov** [comment]
A fix has been released for the `DownloadBuildArtifacts` task.
I am closing it at the moment, if the problem still appears, feel free to reopen it.

**Comment by WilliamRaphaWyde** [comment]
FYI we have been experiencing the same issue on our end today. It was working fine until yesteday, but it failed 3 times today for our daily build.

eg. https://dev.azure.com/mphasis-wyde/Wynsure%20Product/_build/results?buildId=3390&view=logs&j=c1abedab-6e8a-5acb-7f25-be4ece04f074&t=7727b2dc-7902-526f-78b7-45d9a2b1af14
