### ISSUE TITLE
Azure Key Vault and Task Groups

### ISSUE THREAD

**Issue by BillChirico** [microsoft/azure-pipelines-tasks#13254]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure Key Vault  

list here (V# not needed):  1.*

## Environment
- Server - Azure Pipelines

- Agent - Hosted (Task Group)

## Issue Description

For setting variables from this task within a task group they are not properly being set. It is automatically being picked up by the task group when defined in the variable format.

**Comment by ds-ms** [comment]
@tauhid621 to take a look 😃

**Comment by tauhid621** [comment]
@BillChirico I will take a look at this. Meanwhile a workaround will be to create a release variable with same secret name which can be set at release time and pass this variable as an input to the task group.

![Screenshot 2020-07-14 at 7 39 43 PM](https://user-images.githubusercontent.com/17411453/87435755-ccba7b00-c609-11ea-9d9e-2330b337b55a.png)

<img width="855" alt="143979-screenshot-2020-06-30-at-102752-am" src="https://user-images.githubusercontent.com/17411453/87435628-9f6dcd00-c609-11ea-95e5-77c5746ab75c.png">

**Comment by ds-ms** [comment]
Closing stale issue. Feel free to reopen if the problem still persisits.
