### ISSUE TITLE
HelmDeploy: helm get manifest does not use configured namespace

### ISSUE THREAD

**Issue by johngrimes** [microsoft/azure-pipelines-tasks#13256]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy

This task runs `helm get manifest [release name]` before finishing. This fails when the release is installed to a namespace, as the command does not seem to include the configured namespace.

## Environment

Azure Pipelines - team: aehrc, project: ontoserver, build: 20200710.12

## Issue Description

Task name: Install Helm chart

### Task logs

[logs_39.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4900525/logs_39.zip)

### Error logs

```
Starting: Install Helm chart
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.171.3
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
/usr/local/bin/helm upgrade --namespace atomio --install --set hostname=atomio.australiaeast.cloudapp.azure.com,image=ontoserver.azurecr.io/atomio:0.0.1-SNAPSHOT,storage=50Gi --wait --install atomio atomio
Release "atomio" has been upgraded. Happy Helming!
NAME: atomio
LAST DEPLOYED: Fri Jul 10 02:43:55 2020
NAMESPACE: atomio
STATUS: deployed
REVISION: 5
TEST SUITE: None
/usr/local/bin/helm get manifest atomio
Error: release: not found
Finishing: Install Helm chart
```

**Comment by ds-ms** [comment]
This issue has been addressed in this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/13219 

The rollout has started this week. cc: @shigupt202  to verify

**Comment by ds-ms** [comment]
Closing this duplicate issue. 

Ref: https://github.com/microsoft/azure-pipelines-tasks/issues/13197
