### ISSUE TITLE
False positive Warning instead of Info at compilation (Azure DevOps)

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/azure-pipelines-tasks#13253]
---
**Issue moved from dotnet/core#4926**
- Please respond to @tango-charly.

---

_From @tango-charly on Thursday, July 9, 2020 6:43:15 PM_

# False positive Warning instead of Info at compilation (Azure DevOps)

Hi, 

We have an issue with compilation warning in Azure Devops, I know it's related with Build Agent but idon't know where exactly i have to open this issue.

# General
![image](https://user-images.githubusercontent.com/8989885/87077651-72787f00-c1f1-11ea-84b8-b968d6775665.png)

All pipelines with quality check failed, even if dotnet core sdk/runtime versions are are updated in projects (> 2.2 / 3.1)

There is no way to correct this warning because there is no real issue (just presuming)... The only way we found is to update our yaml pipelines to every project to disable quality check. (Way too loooong...)

Have you any ideas to by pass/ignore this warning with the minimum effort ?

**Comment by tango-charly** [comment]
By the way, we are trying to filter warning to ignore this false positive.
But it's very difficult to understand the logic.
(Documentation : https://marketplace.visualstudio.com/items?itemName=mspremier.BuildQualityChecks#task-parameters)

We have a more "Filtered Warning" than "Total Warning"
![image](https://user-images.githubusercontent.com/8989885/87087445-1ae20f80-c201-11ea-8189-b7cd84708a34.png)

Filtered Warning seems to represent the scope of the search pattern (we have 57 rows in 2 steps). 
Maybe label should be more explicit / explain ?

Unfortunately, we have to resolve this problem with try/error method, statistics reports are highly impacted by the lack of documentation.

**Comment by tango-charly** [comment]
Corrected by 
- https://github.com/microsoft/azure-pipelines-tasks/pull/13286 
- https://github.com/microsoft/azure-pipelines-tasks/pull/13287
