### ISSUE TITLE
NpmAuthenticateV0 should write token to ~/.npmrc to works with NPX and match vsts-npm-auth

### ISSUE THREAD

**Issue by compulim** [microsoft/azure-pipelines-tasks#13265]
## Required Information

*Type*: bug

**Enter Task Name**: NpmAuthenticateV0

## Environment

Server: Azure Pipelines
Agent: Hosted (Windows 2016)

## Issue Description

When running "NPM authenticate", it write to the local `.npmrc` file (the file we pass as task argument). But `vsts-npm-auth` write to `~/.npmrc` by default.

Both case works for `npm install`. But `NpmAuthenticateV0` will fail when running `npx`.

I believe the auth token should be written to `~/.npmrc` to enable `npx`. And this also aligns with `vsts-npm-auth` behavior as well.

### Repro

1. Build an empty pipeline, source code repos can be empty
1. Add a command line task
   ```sh
   md test
   cd test
   echo registry=https://XXX.pkgs.visualstudio.com/_packaging/XXX/npm/registry/>.npmrc
   echo always-auth=true>>.npmrc
   ```
1. Add a NPM Authenticate task
   - Authenticate `test/.npmrc` file
1. Add another command line task
   ```sh
   cd test
   type .npmrc
   echo {}>package.json
   npx -p "p-defer" -c "echo Hello!"
   ```

### Expected result

In the second command line task, it will print the `.npmrc` file with the content:

```
registry=https://XXX.pkgs.visualstudio.com/_packaging/XXX/npm/registry/
always-auth=true

//XXX.pkgs.visualstudio.com/_packaging/XXX/npm/registry/:_authToken=***
```

We can verify the token is in `.npmrc`.

The next step is `npx -p p-defer -c "echo Hello!"`, which essentially means: install `p-defer` package then run `echo Hello!`. Any package is fine, I am just putting `p-defer` here because it install quickly with zero dependencies.

But when `npx` is being called, it will fail with E401:

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/12345678-1234-5678-abcd-12345678abcd, Basic realm="https://pkgsprodeus99.pkgs.visualstudio.com/", TFS-Federated

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JohnDoe\AppData\Roaming\npm-cache\_logs\2020-07-10T21_13_58_727Z-debug.log
Install for [ 'p-defer@latest' ] failed with code 1
```

This is because `npx` cannot get the auth token from the local `./.npmrc` file, but it was asked to authenticate against a custom registry. Thus, it end up with E401.

If the auth token is stored in `~./npmrc`, `npx` will run successfully because it can read from the auth token.

Note: the empty `package.json` is critical for the repro. If left out, `npx` will ignore the `./.npmrc` file.

### Task logs

I believe the expected result section above is sufficient.

### Error logs

I believe the expected result section above is sufficient.

**Comment by cwhitten** [comment]
When can we expect some engagement from the team on this issue?

**Comment by samuelkoppes** [comment]
Pending triage from the Artifacts team.

**Comment by phil-hodgson** [comment]
Adding credentials to the user .npmrc file is not something we'd do because multiple build agents may be running on the same machine. Consider using the `--userconfig` flag for npx to pass in the path to the local `.npmrc` file that does contain the credentials set by NpmAuthenticate.

**Comment by compulim** [comment]
I understand build agents may be a non-containerized machine shared by multiple build jobs.

I think it will be helpful to add an additional note in the documentation to call out `NpmAuthenticateV0` will not authenticate for NPX and additional workaround is needed with the `--userconfig` flag.

In our cases, `--userconfig` flag is not possible because `npx` is being executed by another package during their `postinstall`. Their usage is legitimate and very similar to package such as `node-sass`, which run `node-gyp` to prebuild native binaries. But in this case, it is using `npx` for the prebuild.
