### ISSUE TITLE
Fix Spelling in Deprecated .NET SDK Warning

### ISSUE THREAD

**Issue by mehalick** [microsoft/azure-pipelines-tasks#13270]
**Question, Bug, or Feature?**  
Bug

*Type*: 
Build

**Enter Task Name**: 
DotNetCoreCLIV2

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted 
    
## Issue Description

When initializing the task a warning is printed/logged regarding .NET Core SDK/runtime 2.2 and 3.0 deprecation and contains a spelling mistake. The word "required" is spelled as  "requied". The spelling mistake was not new but copied forward in #13220 @tejasd1990 

### Task logs

```
Starting: Restore Solution
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.171.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\windows\system32\chcp.com 65001
Active code page: 65001
##[warning].NET Core SDK/runtime 2.2 and 3.0 are now End of Line(EOL) and have been removed from all agents. If you're using these SDK/runtimes, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the requied version.
```

**Comment by stkevintan** [comment]
repro for me

**Comment by bishal-pdMSFT** [comment]
Fix has been merged
