### ISSUE TITLE
AzureCLI@2 task fails with Windows Server 2019 when we run "az rest" command to Logic App twice.

### ISSUE THREAD

**Issue by rikat-ms** [microsoft/azure-pipelines-tasks#13288]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent - Hosted or Private:  Both

## Issue Description

AzureCLI@2 task fails under specific conditions.

Conditions:
- Agent is running on **Windows Server 2019**. 
The issue can be reproduced on both Microsoft-hosted agent: "windows-latest" and Self-hosted agent on Windows Server 2019
- Run REST API for Logic App Workflows - Get API using "az rest" command **twice**.
- Logic App have been run at least once.

### Task logs

`az : Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.`
`At C:\Agent\_work\_temp\azureclitaskscript1594198065255_inlinescript.ps1:2 char:9`
`+ $val1 = az rest --method get -u $url`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo : NotSpecified: (Unable to encod... are discarded.:String) [], RemoteException`
`+ FullyQualifiedErrorId : NativeCommandError`

## Troubleshooting

Still investigating but confirmed below.

- The same script completes successfully with the other operating systems like Microsoft-hosted agent "vs2017-win2016" and Self-hosted agent running on Windows Server 2012 R2.
- The same script completes successfully if we run REST API once in the script.
- The same script completes successfully if we run the other type of REST API in the script.
- Adding chcp xxx command in the script didn't help.
- The same script completes successfully if we run it from PowerShell command window although the same message is returned for each command. (After I confirmed the issue was reproduced with Self-hosted agent on Windows Server 2019, I connected it using RDP and ran the same script. The error didn't occur. I couldn't reproduce the issue even though I ran chcp 65001, chcp 932 or chcp 1252 first.)

### Repro
Sample.zip contains YAML definition and Logic App definition.

[sample.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4918720/sample.zip)

**Comment by bishal-pdMSFT** [comment]
@rikat-ms we have seen similar issues with the task and the problem seems to be with Powershell version installed on hosted agents. Not sure whether same issue but can you try the workaround of specifying scriptType of pwsh

**Comment by rikat-ms** [comment]
@bishal-pdMSFT Thank you for your information. As you said, this issue seems to be caused by PowerShell because this issue also occurs using PowerShell task. (Sorry, I didn't write first.) I tried to run with pscore in scriptType (pwsh didn't exist for the scriptType) and it completed successfully. So, pscore can be workaround if we use Windows Server 2019. 
Meanwhile, I'll try to find more details why this issue occurs.

**Comment by vineetmimrot** [comment]
Closing it as the issue with powershell and customer is. unblocked.

**Comment by rikat-ms** [comment]
FYI: This issue was resolved by this update.

September 8, 2020—KB4570333 (OS Build 17763.1457)
https://support.microsoft.com/en-us/help/4570333/windows-10-update-kb4570333

The current Windows Server 2019 image for Microsoft-hosted agent seems to have this update. So, the issue won't occur unless users configure their self-hosted agent on Windows Server 2019 without this update.
