### ISSUE TITLE
AzureCLI task list public IPs no HTTP resource was found

### ISSUE THREAD

**Issue by dewolfs** [microsoft/azure-pipelines-tasks#13299]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureCLI@2 

## Environment
- Server - Azure Pipelines or TFS on-premises?
      
    - If using **Azure Pipelines**, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **ubuntu-latest**

## Issue Description

I want to list all the Azure public Ips in my Azure subscription using the task
```
              - task: AzureCLI@2
                displayName: 'Get public IPs'
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    PUBLIC_IP_NAME=$(az network public-ip list --query "[?starts_with(name,'k')].[name]" --output tsv)
                    echo "Public IP resource name is $PUBLIC_IP_NAME"
                    PUBLIC_IP_RESOURCE_GROUP=$(az network public-ip list --query "[?starts_with(name,'k')].[resourceGroup]" --output tsv)
                    echo "Public IP resource is stored in resourcegroup $PUBLIC_IP_RESOURCE_GROUP"
```

The pipeline fails with the following log:

Public IP resource name is 
Public IP resource is stored in RG 
Operation failed with status: 'Not Found'. Details: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/xxx-xx-x-x-xxx/resourceGroups/providers/Microsoft.Network/publicIPAddresses/?api-version=2020-05-01'.
##[error]Script failed with exit code: 1

When I check the available apiVersions in the Azure cloud shell, I get the following:
```
az provider show --namespace Microsoft.Network --query "resourceTypes[?resourceType=='publicIPAddresses'].apiVersions | [0]" --out table
```
Result
------------------
2020-05-01
2020-04-01

If I execute the same code in the Azure cloud shell it works:

```
x@Azure:~$ PUBLIC_IP_NAME=$(az network public-ip list --query "[?starts_with(name,'k')].[name]" --output tsv)
x@Azure:~$                     echo "Public IP resource name is $PUBLIC_IP_NAME"
Public IP resource name is k-a0c4b0021c0d1451ab58e51c4bff8649
x@Azure:~$                     PUBLIC_IP_RESOURCE_GROUP=$(az network public-ip list --query "[?starts_with(name,'k')].[resourceGroup]" --output tsv)
x@Azure:~$                     echo "Public IP resource is stored in resourcegroup $PUBLIC_IP_RESOURCE_GROUP"
Public IP resource is stored in resourcegroup rg01
```
This pipeline worked successfully last week with the same code.

**Comment by vineetmimrot** [comment]
Compare the version of AzCli in the pipeline and cloud shell. Provide debug logs by setting  system.debug variable and its value to true.

**Comment by dewolfs** [comment]
Version in pipeline
azure-cli                          2.9.1

Version in cloud shell
"azure-cli": "2.9.0"

I've run the pipeline now multiple times, issue seems to be resolved without changing anything my side.
Closing for now
