### ISSUE TITLE
PublishTestResult + NUnit3 report: publishing of test attachments with relative path not working

### ISSUE THREAD

**Issue by NilsEngelbach** [microsoft/azure-pipelines-tasks#13297]
Should it be possible to publish the test attachments with a relative path in Azure DevOps for NUnit3 reports?
 
The task is configured like this:
 
```yml
- task: PublishTestResult@2
   inputs:
     testResultsFormat: 'NUnit'
     testResultsFiles: 'tmp/report.xml'
     publishRunAttachments: true
```
The report looks like this:
 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<test-run>
    <test-suite type="Assembly" name="...">
        <-- ... -->
        <test-case name="..." result="Failed" duration="24.161">
            <failure>
                <message>
                    ...
                </message>
                <stack-trace>
                    ...
                </stack-trace>
            </failure>
            <attachments>
                <attachment>
                    <filePath>tmp/screenshots/errors/1.png</filePath>
                </attachment>
            </attachments>
        </test-case>
    </test-suite>
</test-run>
```

It seems that the file can not be found, even tough it is in the given location relative to $(System.DefaultWorkingDirectory):
```
##[warning]Skipping attachment as it is not available on disk: tmp/screenshots/errors/1.png
```

Is the search folder (default: $(System.DefaultWorkingDirectory)) not taken into consideration for attachments?
Should attachment path be absolute?
I also tried it on linux and windows build agents.
I can not find information about this in the docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#nunit-3

**Comment by suyash691** [comment]
You need to provide the absolute path in order to publish attachments via this method
