### ISSUE TITLE
[XamariniOSV2] Implement support of provisioning profile for app extension

### ISSUE THREAD

**Issue by alexander-smolyakov** [microsoft/azure-pipelines-tasks#13300]
## Required Information
**Question, Bug, or Feature?** 
*Type*: Feature

**Enter Task Name**: XamariniOS

## Issue Description
In the current implementation of the Xamarin iOS task, there is a limitation that users can provide only one provisioning profile. But to sign an application that contains an extension requires two provisioning profiles. One for applications and another for an extension.

**Comment by anatolybolshakov** [comment]
Reopening this since there's still no workaround for this issue.

**Comment by alexmartinezm** [comment]
Any updates on this?

**Comment by anatolybolshakov** [comment]
Hi @alexmartinezm sorry for delay - we are working on more prioritized issues at the moment, but will get back to this once be able to.

**Comment by thisisthekap** [comment]
Please reopen!

**Comment by xleon** [comment]
Please reopen

**Comment by thisisthekap** [comment]
This is not fixed. I am aware, that other things need to be taken care of first. But as this is not fixed: Please reopen it!
