### ISSUE TITLE
Docker Compose Task fails with "HNS failed with error : The parameter is incorrect."

### ISSUE THREAD

**Issue by veemvve** [microsoft/azure-pipelines-tasks#13303]
I'm trying to execute a docker-compose.yml which deploys Azure Docker Container Instances needed for Apache Airflow using Docker Compose task and ended up with below error, 

_Creating network "network_name_default" with the default driver
HNS failed with error : The parameter is incorrect. 
##[error]Creating network "msbizopsde-airflow_default" with the default driver
##[error]HNS failed with error : The parameter is incorrect._ 

**Task:**
steps:
- task: DockerCompose@0
  displayName: 'Run services'
  inputs:
    azureSubscription: abc
    azureContainerRegistry: '{"loginServer":"pqr", "id" : "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.ContainerRegistry/registries/zzz"}'
    dockerComposeFile: '.../docker-compose.yml'
    projectName: 'airflowpoc'
    action: 'Run services'

**Comment by ds-ms** [comment]
@rohit-batra could you take a look at this issue?

**Comment by rohit-batra** [comment]
@veemvve Is this still an issue ? Can you please share logs with system.debug set to true ? Also can you please share the docker-compose yml file. 
Also the whole Pipeline yml file would help as well.

**Comment by ds-ms** [comment]
Closing stale issue.
