### ISSUE TITLE
Replace DeleteFiles or use Specific Version

### ISSUE THREAD

**Issue by jeremysimmons** [microsoft/azure-pipelines-tasks#13307]
Type: Question
Task Name: DeleteFilesV1

## Environment
- Server - Azure Pipelines
account name: entcu
team project name: SI
build definition name: Olb
build number: maintegration-20200714.3-Release-3

- Agent 
Location: Private
OS: on Microsoft Windows [Version 10.0.14393]
Agent Version: bin.2.171.1

## Issue Description
The DeleteFiles task was affected by the update to the https://github.com/microsoft/azure-pipelines-task-lib/ which is mentioned 
https://github.com/microsoft/azure-pipelines-tasks/issues/12500

How can I lock a task at a specific version so that I can avoid using newer version with performance issues?

**Comment by jeremysimmons** [comment]
@mjroghelia any thoughts? is this a question for the microsoft/azure-pipelines-agent repo?

**Comment by mjroghelia** [comment]
@stephenmichaelf Can you advise here on whether this is or will be a task locking workaround?

**Comment by jeremysimmons** [comment]
@mjroghelia, @stephenmichaelf it's hard to understand how much of a crippling regression this is. 
This is occuring once for every server in our deployment and increasing the time from seconds to 5-10 minutes per server.

We were at > 90 minutes for a release to run fully vs now the < 10 minutes.

As a workaround, I added a shell script as a final task in my task-group to remove files from $(System.ArtifactsDirectory). so that there will be less (only directories) to Cleanup on the next build...

```
echo deleting $(System.ArtifactsDirectory)
PUSHD $(System.ArtifactsDirectory)
DEL /F/Q/S *.* > NUL
exit /b 0
```
