### ISSUE TITLE
Upgrade VstsTaskLib to 0.11.0 everywhere to fix fails on logging when any filenames contain [ or ]

### ISSUE THREAD

**Issue by japj** [microsoft/azure-pipelines-tasks#13309]
## Required Information

I recently ran into the same issue as microsoft/azure-pipelines-tasks#6314, but for the MSBuild task with:

- Azure DevOps Server Dev17.M153.5 (This is an Azure DevOps Server 2019 Update 1.1)
- Agent 2.153.1
- MSBuild task 1.151.1 (which seems to use vsts-task-lib 2.2.1 and VstsTaskSdk 0.8.2)

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MSBuild, and more

## Environment
- Azure DevOps Server
    
    - Dev17.M153.5 (This is an Azure DevOps Server 2019 Update 1.1)

- On Premise Agent
    
    - Agent 2.153.1,  MSBuild task 1.151.1

    - Windows 10

## Issue Description

Same issue as https://github.com/microsoft/azure-pipelines-tasks/issues/6314, but for the MSBuild task

It seems that the fix was done in the powershell VstsTaskSdk 0.10.1, but that never ended up in the release notes: https://github.com/microsoft/azure-pipelines-task-lib/issues/651

Since the MSBuild task, and others, still use older versions of the VstsTaskSdk, they still all have that issue

**Comment by japj** [comment]
The issue is still valid, but it is unclear to me who the product owner is for this (and why it’s not being picked up)

**Comment by japj** [comment]
@damccorm do you happen to know who owns the MSBuild task? This issue is still relevant since VstsTaskSdk has not been updated yet in the MSBuild task

**Comment by damccorm** [comment]
I added the appropriate team's label, its now on their backlog to address as appropriate

**Comment by anatolybolshakov** [comment]
Hi @japj we have already updated azure-pipelines-task-lib dependency for MSBuild task (which includes VstsTaskSdk dependency) - I think you just need to update Azure DevOps Server to receive last updates.

**Comment by japj** [comment]
@anatolybolshakov we have recently updated to AzureDevOps Server 2020.

With the server upgraded we now have:
- MSBuild Task 1.166.2
  - which (still) includes VstsTaskSdk 0.8.2

In which version of the server is this expected to be fixed?

**Comment by japj** [comment]
0.8.2 is still mentioned in https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MSBuildV1/make.json
so that might explain it

**Comment by japj** [comment]
please note there are several other make.json files containing a nuget external reference to an old version of the VstsTaskSdk

**Comment by anatolybolshakov** [comment]
@japj got it, I see thanks! Let me take a look.

**Comment by japj** [comment]
@anatolybolshakov any update on this?

**Comment by anatolybolshakov** [comment]
Hi @japj we are working on testing of these changes at the moment.

**Comment by anatolybolshakov** [comment]
@japj we merged related fix, will let you know once these changes are rolled out to production.

**Comment by japj** [comment]
@anatolybolshakov please note that we are on Azure DevOps Server (2020 atm). Is this fix target for inclusion in an Update 1 RC2? Or will it be in Update 2?

**Comment by anatolybolshakov** [comment]
@japj I can't say exactly at the moment, but this should be available in the next release.
As another option to get these changes quickly - you can build MSBuild task from source and upload it to your organization via [tfx-cli](https://www.npmjs.com/package/tfx-cli) tool.

**Comment by anatolybolshakov** [comment]
Hi @japj the fix for this version has been already rolled out for cloud, so I'm closing this at the moment - but it could take some time for this change to be rolled out for on-prem.
