### ISSUE TITLE
getting *** marks in pipeline tasks

### ISSUE THREAD

**Issue by sanjeevsharma-1** [microsoft/azure-pipelines-tasks#13314]
I'm trying to run a pipeline but not sure why the pipeline consists of **** marks in results page, it is trying to hide the values and I need the values for understanding the error or issues.
the issue comes in all the tasks and not any specific one.
![image](https://user-images.githubusercontent.com/68319188/87803649-6c794280-c870-11ea-93e3-bdc3e0d57d0a.png)

**Comment by damccorm** [comment]
Hi, this looks like a more general issue with a 3rd party task/secrets, not an issue with a task in this repo. Please direct more general issues to https://developercommunity.visualstudio.com/spaces/21/index.html
