### ISSUE TITLE
[SSH] sudo command doesn't work with runOptions=commands

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-tasks#13311]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SshV0

## Environment
- Server - Azure Pipelines or TFS on-premises?
   Any

- Agent - Hosted or Private: 
   Any

## Issue Description
Sudo command doesn't work properly with 'runOptions' as 'commands' - execution is being stucked - even if 'interactiveSession' is enabled

**Comment by anatolybolshakov** [comment]
Closed since fix was deployed

**Comment by karsten-kuepper** [comment]
I'm still having the same issue

**Comment by anatolybolshakov** [comment]
Hi @karsten-kuepper, I just marked it as deployed by mistake, but these changes are going to be rolled out. I returned back 'awaiting deployment' label, it will take about 3 weeks to be rolled out

**Comment by anatolybolshakov** [comment]
Hi @karsten-kuepper, changes were already rolled out - could you please verify that it works for you?
