### ISSUE TITLE
PublishBuildArtifacts with an artifact name of bin results in artifacts that can't be downloaded

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/azure-pipelines-tasks#13322]
We recently changed our build artifacts published by PublishBuildArtifacts to be called bin rather then drop. We noticed today that doing this caused us to be unable to download any individual artifacts. This can be seen in the following build.

https://dev.azure.com/ms/msquic/_build/results?buildId=95701&view=results

The following link is to one of the individual build artifacts, which should be downloadable, however it results in a not found error.

https://dev.azure.com/ms/_apis/resources/Containers/6999139/bin?itemPath=bin%2Fwindows%2Fx64_Release_schannel%2Fmsquic.lib

This did not occur while the name was `drop`, so it seems like a bug related to being named `bin`

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishBuildArtifacts 

## Environment
- Server - Azure Pipelines or TFS on-premises?

    Azure Pipelines. ms account, msquic project, CI build definition, build number 95701

   Hosted agent, all of them

**Comment by nibanks** [comment]
FYI, the impacted pipeline is used for a Windows OS component. [MsQuic](https://github.com/microsoft/msquic) is shipped as a part of Windows. This bug impacts our development and debugging experience, since we cannot download symbols for test failures. We'd greatly appreciate it if you could take a look at this ASAP.

**Comment by ThadHouse** [comment]
Any update on this? Its becoming a more and more painful issue, especially as we are still in active development and need access to the artifacts.

**Comment by ThadHouse** [comment]
Another ping for an update. This is still an issue causing pain for development.

**Comment by ThadHouse** [comment]
Is there any update on this? I can provide new build links that are up to date if that helps. This is still happening every build, and still extremely painful.

**Comment by alexander-smolyakov** [comment]
@ThadHouse, we will investigate this issue shortly. Could you please use a `drop` name for now to avoid this issue?

> I can provide new build links that are up to date if that helps.

It will be great since links in the issue description are outdate. Could you please also provide a logs and yaml file from the pipeline?

Thanks!

**Comment by ThadHouse** [comment]
Heres our pipeline yaml

https://github.com/microsoft/msquic/blob/main/.azure/azure-pipelines.ci.yml

And our builds are here
https://dev.azure.com/ms/msquic/_build?definitionId=347&_a=summary

Heres the latest one that still has the issue
https://dev.azure.com/ms/msquic/_build/results?buildId=110378&view=results

**Comment by sdobrodeev** [comment]
Created PR with updated documentation

**Comment by sdobrodeev** [comment]
Hi @ThadHouse. You cannot use "Bin", "App_Data" and other folder names reserved by IIS as an artifact name because this content is not served in response to Web requests. Please see  [ASP.NET Web Project Folder Structure](https://docs.microsoft.com/en-us/previous-versions/ex526337(v=vs.140)) for more details. The corresponding changes have already been made to the documentation

**Comment by ThadHouse** [comment]
@sdobrodeev Sounds good. Running into an issue though with trying to fix this. Our build scripts use PublishBuildArtifacts and DownloadBuildArtifacts. It depends on placing the files in a folder called artifacts/bin. If I change the publish name to artifacts, the artifacts bet placed in artifacts/artifacts. How can I change the name of the artifact, but still have download place the files in bin?

**Comment by anatolybolshakov** [comment]
@ThadHouse you can change browser settings to show Save dialog for any files being downloaded - it will allow to set any path for downloaded artifacts. Does it work for you?

**Comment by ThadHouse** [comment]
It's an issue with the tasks in pipelines, not with manually downloading. I came up with a hack solution that seems to work though.
