### ISSUE TITLE
The README's taskbanner.png should use the new Gradle logo

### ISSUE THREAD

**Issue by lacasseio** [microsoft/azure-pipelines-tasks#13324]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Documentation bug

**Enter Task Name**: README.md  

## Environment
N/A

## Issue Description

The logo in the taskbanner.png for Gradle is really old. It should use the newer one, see [their branding page](https://gradle.com/brand/).

**Comment by anatolybolshakov** [comment]
Reopening it since it still looks actual
