### ISSUE TITLE
Azure PowerShell task no longer persists Azure auth context when the task completes

### ISSUE THREAD

**Issue by deadlydog** [microsoft/azure-pipelines-tasks#13328]
**Type**: Bug

**Task Name**: AzurePowerShell

## Environment
Azure Pipelines
https://dev.azure.com/iqmetrix/RQ/_releaseProgress?_a=release-environment-logs&releaseId=24564&environmentId=104457

Hosted agent, using Azure Pipelines and ubuntu-18.04

## Issue Description

Prior to PR #13239 you could use the Azure PowerShell task to authenticate with your Azure subscription and establish a context, and then subsequent tasks in the pipeline would also be authenticated via that context. The PR changed the scope of the context, so now any pipelines relying on the context to already exist break, saying "Run Connect-AzAccount to login".

To reproduce this, use the Azure PowerShell task to authenticate with the Azure subscription, and then add a regular PowerShell task to your pipeline and have it access resources in the subscription, such as reading from Key Vault. This worked fine in v4.171.1 of the AzurePowerShell task, but no longer works in v4.173.0, and I believe the the mentioned PR is responsible for it.

Unfortunately Azure DevOps does not allow us to use previous versions of the task, so we can't rollback to the working version.

### Task logs

I've attached a zip with the log files. The tasks of interest are "3_Login to Azure.log" and "22_Retrieve AKV Secretes and Create Folder.log".

[ReleaseLogs_24564.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4956474/ReleaseLogs_24564.zip)

### Error logs
The task itself does not return any errors, it simply does not behave as it previously did. It used to leave the Azure context in tact, but now the context disappears once the Azure PowerShell task completes.

**Comment by chshrikh** [comment]
@20shivangi to address this

**Comment by deadlydog** [comment]
I'll mention that I understand PR #13239 increases security, but at the same time it introduces a breaking change that can break existing pipelines. Ideally the user would be able to choose the scope on the task UI; default it to the more secure `process` scope, but still allow it to use the previous user-scope behaviour so that users can get their pipelines back up and running quickly. Bumping the task version would be a good idea as well.

**Comment by 20shivangi** [comment]
@deadlydog Earlier we were using set-azcontext command in the scope of currentUser, due to which all the non-azureps tasks were able to use the Az context so we limited the context to the scope of process. But due to this, some pipelines started breaking where people were using az context created by azureps task.
So for now, we have reverted this change back. Our change has started being deployed,  it will reach all the rings in 2-3 days.
Please wait for sometime. Thanks for your patience.

**Comment by 20shivangi** [comment]
Closing it as the issue has been fixed, feel free to re-open if face any issue.
