### ISSUE TITLE
AzureResourceGroupDeploymentV2 Missing from ADO's Release Designer

### ISSUE THREAD

**Issue by jklaus** [microsoft/azure-pipelines-tasks#13327]
## Required Information

The Azure Resource Group Deployment Task is missing from ADO's release designer.  I can't even find it in the deprecated tasks lists. 

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeploymentV2 

Note: this issue seems to have started up May 17th.  See comments on original post on this prior closed bug. 
(The original bug was simply user error)
https://developercommunity.visualstudio.com/content/problem/791080/azure-resource-group-deployment-task-not-available.html

## Environment
Azure Devops - Releases

**Comment by jklaus** [comment]
After a little snooping I found the new task - This name change doesn't seem to be published anywhere.  Is it possible to alias the package, or at least publish such a name change?

**Comment by vineetmimrot** [comment]
@pulkitaggarwl Can you please check this regarding documentation.

**Comment by v-abiss** [comment]
@pulkitaggarwl I'll work on this issue

**Comment by porscheme** [comment]
Any update on this, when is the fix coming?

Any workaround in the meanwhile?

**Comment by bishal-pdMSFT** [comment]
@porscheme this is just a doc issue and the task exists in release editor (with an updated name)

**Comment by bishal-pdMSFT** [comment]
Closing stale issue. Please re-open if you still feel that this is an issue.
