### ISSUE TITLE
ServiceFabricDeploy@1 cannot deploy in parallel because it removes certificates

### ISSUE THREAD

**Issue by henry-padilla** [microsoft/azure-pipelines-tasks#13332]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeploy@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account: WKAxcess
Project: Axcess

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Private agent on Windows server 2019

## Issue Description
We are deploying to Service Fabric Clusters in two different regions. We have a pipeline with two different stages in it, one for each region. When we try to deploy to both regions at the same time we get errors that the certificate has been moved or is expired or is not installed. If we run them in series we do not get certificate errors.

After looking at the code I notice the task will just install the Certificate from the service connection. It will then remove the certificate. This is creating a race condition for the presence and access to the certificate.

The script should search for the thumbprint and, if it doesn't find the certificate, set a switch. Then, at the end, check if the cert was installed and only remove it if it was installed by this task.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
After looking at the code I notice the task will just install the Certificate from the service connection. It will then remove the certificate. This is creating a race condition for the presence and access to the certificate.

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by henry-padilla** [comment]
EDIT: After discussing with a friend I realize the above suggestion still won't work if the cert is not installed in the beginning.

A better approach would be to use semaphores as a use count and when the usage is zero, remove it (if it was installed be this task).

**Comment by bishal-pdMSFT** [comment]
@henry-padilla yes, the task has this limitation as it removes certificate at the end. It is recommended to use different agents to run parallel tasks which are using same certificate to connect to cluster.
The enhancement to add this support in task is in backlog but I don't think we will be able to prioritize anytime soon.
