### ISSUE TITLE
[DockerV2] Images randomly include broken dependencies

### ISSUE THREAD

**Issue by valters-tomsons** [microsoft/azure-pipelines-tasks#13339]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `Docker@2`
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Server - `Azure Pipelines`
- Agent - `Hosted`

## Issue Description

We have a docker task that builds an image from our repository and it seems that sometimes the final image has a corrupted dependency within it. The pipeline **exhibits no error messages**, so we find out it's broken only when the image is deployed and thing are not working.

Our current solution is to trigger the build again which often seems to create a correct image, with **exact same code.**

This is the difference from a working and non-working image with [container-diff](https://github.com/GoogleContainerTools/container-diff)

![thumbnail_image002](https://user-images.githubusercontent.com/4209639/88273042-46c1c280-cce2-11ea-9869-dab930531814.png)

### Task logs

Logs below were built against same code.

Log from a correct build -  [working_image.log](https://github.com/microsoft/azure-pipelines-tasks/files/4965138/working_image.log)

Log from incorrect build - [notworking_image.log](https://github.com/microsoft/azure-pipelines-tasks/files/4965139/notworking_image.log)

## Troubleshooting

Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

None

**Comment by Ganeshrockz** [comment]
@FaithLV Are you still facing the same issue consistently?

**Comment by FaithLV** [comment]
@Ganeshrockz Yes, tested building images today, still exhibits the same issue.
