### ISSUE TITLE
MSIX package deployment appsetting JSON variable substitution.

### ISSUE THREAD

**Issue by syedwajeehbukhari** [microsoft/azure-pipelines-tasks#13341]
Hello,

Please can someone direct me to steps on JSON variable substitution with MSIX package. I need to have different MSIX packages for different environments as the WPF projects appsettings.json file values change based on environments. I've tried the Release Pipeline "File Transform" task replacing zip with msix but no luck. Since I'm new to this MSIX stuff maybe i'm using the wrong approach?

![File Transform](https://user-images.githubusercontent.com/68697454/88296121-34ea1a80-ccf6-11ea-8cdd-f03661d23196.PNG)

**Comment by arjgupta** [comment]
@syedwajeehbukhari the File Transform task does not operate on MSIX package. You need to provide path to json or xml configuration files for the task to be able to work on.
