### ISSUE TITLE
Github download release tasks successfully sees tag and repos but downloads nothing

### ISSUE THREAD

**Issue by mtc-infra-team** [microsoft/azure-pipelines-tasks#13342]
Hi, 

using cloud azure-devops and the github download release. tried on both the gui and the yaml pipeline. 

When i try and download a tagged release the task will find the possible tags and completes successfully. but with the message:

```
Starting: Download GitHub Release
==============================================================================
Task         : Download GitHub Release
Description  : Downloads a GitHub Release from a repository
Version      : 0.160.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-github-release
==============================================================================
Downloading assets of release 'v2.2' from: https://api.github.com/repos/xxx/xxx/releases/28780998/assets
Total Files: 0, Processed: 0, Skipped: 0, Failed: 0, Download time: 1.006 secs, Download size: 0Bytes
Successfully downloaded release assets to 'd:\a\1\a'
Finishing: Download GitHub Release
```

**Comment by oseduardo** [comment]
Having the same problem.....

**Comment by bvdwalt** [comment]
I also have this probelm, I'm using a private GitHub repo, but I have the GitHub Connection set properly on the Download GitHub Release task in my Azure build Pipeline. 

Mine also just shows this:
Downloading assets of release 'v1.0.0' from: https://api.github.com/repos/***/***/releases/***/assets
Total Files: 0, Processed: 0, Skipped: 0, Failed: 0, Download time: 1.009 secs, Download size: 0Bytes
Successfully downloaded release assets to 'D:\a\1\s/...'

**Comment by Lucasjuv** [comment]
I have this problem too.

**Comment by bvdwalt** [comment]
I will check this again, but I am pretty sure it is still not downloading my asset.

**Comment by tzaroon** [comment]
Same issue. Waiting for it to resolve.

**Comment by MattBDev** [comment]
Same issue. In my situation it seems to stop processing at 30 assets and unfortunately for me the asset I need is listed beyond the 30. I am trying to download from goreleaser/goreleaser and there are 39 assets in the most recent release.

**Comment by Yousif-CS** [comment]
@MattBDev Hello Matt, have you been able to find a fix for this? I am facing the same problem currently.

**Comment by MattBDev** [comment]
> @MattBDev Hello Matt, have you been able to find a fix for this? I am facing the same problem currently.

Nope.

**Comment by craig-johnston** [comment]
The problem appears to be the code here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadGitHubReleaseV0/main.ts#L187
It does not support pagination and the default number of assets per page is 30 according to the documentation: https://docs.github.com/en/rest/releases/assets#list-release-assets
Supporting pagination looks difficult as the actual fetch and handling is in another package (ArtifactEngine) - https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/ArtifactEngine

A quick hack would be to up the limit to 100 by adding a per_page=100 query param to the URL.

**Comment by hdNguyenPTR** [comment]
Got the same issue here :(

**Comment by davesbrown** [comment]
same issue, only downloading 30 assests

**Comment by craig-johnston** [comment]
The download_count mentioned in the docs, is a per asset field. It represents the total number of downloads of that specific release asset.

> I've done some testing with the gh cli using "gh release download --pattern '*.7z' and showing the full count of my assets over 30+

My guess is that the "gh" CLI does pagination correctly or sets the per_page param high enough for your needs.

**Comment by nickchaperon** [comment]
I am encountering the same issue. Has this been resolved or any workaround found/suggested ..?
