### ISSUE TITLE
Prevent customers to specify exact version in UsePython / UseRuby tasks

### ISSUE THREAD

**Issue by maxim-lobanov** [microsoft/azure-pipelines-tasks#13351]
Hello from https://github.com/actions/virtual-environments.

## Problem  
Both UsePython and UseRuby tasks can't download and install versions on-flight. They just switches between versions pre-installed on image.
On image, we keep only the latest patch version for every major.minor pair.

### Example
Image contains Python 3.6.9. As soon as Python 3.6.10 is released, it will be added to image and will replace Python 3.6.9.
If customer specifies exact version `3.6.9` as task input, they will be **100% BROKEN**.
We should notify customers that they must not to specify exact version and preferred ways are `3` or `3.6`

### Proposed solution
I suggest to print warning if customer specifies version with 3 number like `3.6.9` to both tasks UsePython and UseRuby.
Also I suggest to update documentation for both tasks and add note about it: [UseRuby](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azure-devops) and [UsePython](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops)

UsePython issue could be potentially resolved by https://github.com/microsoft/azure-pipelines-tasks/issues/13319

EDIT: I think this check makes sense only for Hosted machines since if customer uses self-hosted, he may keep the same patch version forever

**Comment by leantk** [comment]
@anatolybolshakov I know we haven't transitioned the Python or Ruby tasks yet but could you take a look at this. I would think it shouldn't be too much work just checking for the version format

**Comment by anatolybolshakov** [comment]
@leantk yep sure 👍 Suggested changes look clear here

**Comment by anatolybolshakov** [comment]
Hi @maxim-lobanov related changes have been rolled out - so I'm closing it at the moment
