### ISSUE TITLE
PublishTestResultsV2 with failTaskOnFailedTests does not fail when tests host crashes

### ISSUE THREAD

**Issue by mllab-nl** [microsoft/azure-pipelines-tasks#13355]
## Required Information

PublishTestResultsV2 with failTaskOnFailedTests does not fail when tests host crashes
trx file result: 

```xml
...
<ResultSummary outcome="Failed">
    <Counters total="116" executed="116" passed="116" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    ...
    <RunInfos>
      <RunInfo computerName="vsts-agent2-z2gtz" outcome="Error" timestamp="2020-07-22T10:27:26.5179325+00:00">
        <Text>The active test run was aborted. Reason: Test host process crashed</Text>
      </RunInfo>
    </RunInfos>
....
  </ResultSummary>
....
```

Outcome:
Build is nice and green 

Expected outcome:
Build is failed  

Is there any workaround to publish test results and fail the build in this case ?

**Comment by mllab-nl** [comment]
IMHO it is a bug

**Comment by suyash691** [comment]
There is no workaround for this apologies.
We can investigate this but since this is a legacy behaviour (on which certain customers would've taken reliance on) we cannot simply change it
