### ISSUE TITLE
'AzureSignTool.exe' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by jozefizso** [microsoft/azure-pipelines-tasks#13361]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines?
    - https://dev.azure.com/netoffice/NetOffice/_build/results?buildId=867&view=logs&j=9eeabfde-0b68-5b48-1926-57b56b63f658&t=f675a0b0-bb7e-5e44-da2f-1025e4db31cf
    - https://dev.azure.com/netoffice/NetOffice/_build/results?buildId=869&view=logs&j=9eeabfde-0b68-5b48-1926-57b56b63f658&t=f675a0b0-bb7e-5e44-da2f-1025e4db31cf 

- Agent - Hosted

## Issue Description

I'm using **DotNetCoreCLI@2** task to install `azuresigntool` as global tool and I use it in a subsequent **CmdLine@2** as `AzureSignTool.exe`

This worked fine for several builds over several days. Right now, the command line task fails because the tool `AzureSignTool.exe` does not exists.

I noticed in the latest build this new line from the **DotNetCoreCLI@2** task:
`Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.`

### Task logs

Successful build: https://dev.azure.com/netoffice/NetOffice/_build/results?buildId=867&view=logs&j=9eeabfde-0b68-5b48-1926-57b56b63f658&t=f675a0b0-bb7e-5e44-da2f-1025e4db31cf

```
You can invoke the tool using the following command: azuresigntool
```

Failing build: https://dev.azure.com/netoffice/NetOffice/_build/results?buildId=869&view=logs&j=9eeabfde-0b68-5b48-1926-57b56b63f658&t=f675a0b0-bb7e-5e44-da2f-1025e4db31cf

```
Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.
```

I would expect that I can use the tool I install from one task in the subsequent task.

**Comment by jozefizso** [comment]
It randomly succeeded in a troubleshooting build: https://dev.azure.com/netoffice/NetOffice/_build/results?buildId=870&view=logs&j=9eeabfde-0b68-5b48-1926-57b56b63f658&t=f675a0b0-bb7e-5e44-da2f-1025e4db31cf

**Comment by vineetmimrot** [comment]
As I can check in your later pipeline builds, the signing is working fine.

**Comment by jozefizso** [comment]
As I reported, using tools from `dotnet install` fails randomly.

**Comment by jcuzzi** [comment]
I am running into this exact same issue today...

**Comment by vineetmimrot** [comment]
This issue is related to .NetCore SDK tool. Please open an issue in .netcore repo.
https://github.com/dotnet/core/issues

**Comment by bishal-pdMSFT** [comment]
@jozefizso @jcuzzi can you add a step after tool install to print the PATH environment variable and share the result

**Comment by jcuzzi** [comment]
@bishal-pdMSFT I only had this issue for a single day. It started working reliably without any changes in the pipeline the next day - I haven't had an issue since.

**Comment by bishal-pdMSFT** [comment]
That's good to hear. I am closing the issue. Please reactivate if needed.

**Comment by anti-matter** [comment]
This is still occurring randomly in our build pipeline and this issue should be re-opened.

**Comment by jozefizso** [comment]
Yes, it just randomly happened on our private pipeline build. Running the build again fixed the issue.

Build machines should have identical software so this does not break randomly.

**Comment by anti-matter** [comment]
How do we get this issue re-opened? It's happening often enough that multiple builds fail in a row.

**Comment by EDasilvaCorreia** [comment]
Having the same issue as well, I have to redeploy multiple times in order to get this to work which isn't ideal. any workarounds?

**Comment by drocx** [comment]
> Having the same issue as well, I have to redeploy multiple times in order to get this to work which isn't ideal. any workarounds?

Use the update command instead of install. It sounds weird, but it works.🎉

`dotnet tool update --global AzureSignTool`
