### ISSUE TITLE
Cannot Use Variables for Azure Subscription in Azure Powershell task

### ISSUE THREAD

**Issue by kzkz221** [microsoft/azure-pipelines-tasks#13368]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here
Trying to use a variable for Azure Subscription in Azure Powershell gave out an error message during release creation.

**Enter Task Name**: here  
Azure PowerShell 5.*

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Azure PowerShell 5.*
![image](https://user-images.githubusercontent.com/2589495/88772492-6f026300-d1b3-11ea-98c3-8c9f65d54dd0.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[tasklog_4.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4993441/tasklog_4.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
2020-07-29T07:24:06.8420268Z ##[error]Required: 'ECS Production Global CA Enterprise' service endpoint URL

**Comment by AmrutaKawade** [comment]
Hope your query got answered. Closing the issue. Thanks again for reaching out out to us.
