### ISSUE TITLE
Issue with NuGet Package Version number in Artifacts

### ISSUE THREAD

**Issue by ClaudeVernier** [microsoft/azure-pipelines-tasks#13374]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NuGetCommand@2

## Environment
- Server - Azure Pipelines
    - Claude VERNIER https://xxx.visualstudio.com/Development%20Unit/_build/results?buildId=6953&view=results

- Agent - Private: 
    - Windows 2.166.4 

## Issue Description

Working on Azure pipelines and a self hosted agent, I have an issue to set version number.
I have to publish an Artifact that contains a set of SQL files and a PS1 file.
Developper added a NUSPEC file in the folder I get from GitHub that contains this:
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>xxx</id>
    <version>1.0.14</version>
    ...
  </metadata>
</package>

It did worked once but since, I always get an error saying that Artifact 1.0.14 already exists.

I use this task to pack:
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: src/MigSQL.nuspec
    versioningScheme: byPrereleaseNumber
    packDestination: $(Build.SourcesDirectory)/src/
    publishVstsFeed: 'xxxx'
Once done, I zip the src folder to a file in artifacts folder and then I push to a feed.
My goal was to have a version like 1.0.14-$(Build.Id) but it was not working so I used byPreleasedNumber.
That created a file: MigSQL.1.0.0-CI-20200730-161055.nupkg
I was thinking it would use the latest as version number but no, still says that Artifact 1.0.14 already exists.
I saw several articles but none that I was able to put in place in my YAML.

**Comment by samuelkoppes** [comment]
We do not support republishing the same version of a package. To publish an updated version, you must increment the version number.
