### ISSUE TITLE
Cmake '"Visual Studio 16 2019" -A X64' is not working

### ISSUE THREAD

**Issue by larshg** [microsoft/azure-pipelines-tasks#13371]
**Question, Bug, or Feature?**  
*Type*: I see it as Bug.

**Enter Task Name**: Cmake
Generate VS build files using Cmake.  

## Environment
Azure piplines:
https://dev.azure.com/PointCloudLibrary/pcl

Github:
https://github.com/PointCloudLibrary/pcl

## Issue Description
CMake Error: Could not create named generator Visual

For some reason the string: '"Visual Studio 16 2019" -A X64' gets chopped.

Yaml file:
https://github.com/larshg/pcl/blob/master/.ci/azure-pipelines/azure-pipelines.yaml#L121-L145

### Task logs
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=17082&view=logs&j=6946a5b8-9e7f-5cb6-63a5-cc6c566891ea&t=3f38187f-3e30-5932-8134-6f978284ef0e

**Comment by alexander-prozorov** [comment]
Hello @larshg,

Thank you for the report.  Is this issue still relevant?

As I can see builds are running successfully now after changing GENERATOR property value to 'Visual Studio 15 2017 Win64'. The problems with the previous one could be related to the version of cmake, which is probably less than 3.1.

**Comment by larshg** [comment]
Hi  @alexander-prozorov 

Yes, it still seems so:
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=17283&view=logs&j=d487384d-eb63-5565-d344-b581c1518e4a&t=8ffb19e5-c9f7-5281-7f20-3cfc859d485a

See this for yaml file changes:
https://github.com/PointCloudLibrary/pcl/pull/4297/files#diff-a32e23151be9c3a4b1d7c3a994ae889f

There seems to be a change from VS 2017 to VS 2019 how to supply the architecture.
https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2016%202019.html

So it seems it require Cmake 3.14 at least?

It does work with VS 2017 as we are currently using this. But it seems this compatibility section is not present for VS 2019.

**Comment by larshg** [comment]
This is not a cmake task per se (after reading a bit more about it), but a script task that executes CMake commands - so this might not be the right repository for the issue?

**Comment by larshg** [comment]
Think I got it working now. We add additional qoutes here:
https://github.com/PointCloudLibrary/pcl/blob/3aaa1dad09cf1105bd3acd13a634f114627bcd54/.ci/azure-pipelines/build/windows.yaml#L24

Which somehow made the script looking for just "Visual" - however that can happen.

**Comment by alexander-prozorov** [comment]
@larshg thank you,

> So it seems it require Cmake 3.14 at least?

Yes, at least 3.14 version is required to use VS 2019 generator.

> Think I got it working now. We had additional qoutes here:
https://github.com/PointCloudLibrary/pcl/blob/3aaa1dad09cf1105bd3acd13a634f114627bcd54/.ci/azure-pipelines/build/windows.yaml#L24

Great. Yes, it looks like the quotes for the environment variable are superfluous here. 

Matrix values are also available to the job as usual variables:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#matrix

So can we consider the problem solved?

**Comment by larshg** [comment]
Yes.
