### ISSUE TITLE
NuGetAuthenticate task should honor DOTNET_CLI_HOME variable

### ISSUE THREAD

**Issue by alexperovich** [microsoft/azure-pipelines-tasks#13375]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Enter Task Name**: NuGetAuthenticate

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/dnceng

- Agent - Hosted or Private: Both, it happens on all agents
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The NuGetAuthenticate task doesn't honor the DOTNET_CLI_HOME environment variable. This variable is used by dotnet cli instead of HOME if it is defined, changing where dotnet cli loads nuget credential plugins from. This breaks authentication to private feeds because the NuGetAuthenticate task installed the credential provider into the HOME directory.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by jmyersmsft** [comment]
We should fix this, but as a workaround, you could obtain artifacts-credprovider separately and place it in the appropriate location under DOTNET_CLI_HOME.

The [install script](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1) isn't particularly long and demonstrates where to get it and what to extract where.

**Comment by herenhuang** [comment]
@alexperovich - were you able to try the workaround above?

**Comment by alexperovich** [comment]
no, we just chose to not set the variable at all.
