### ISSUE TITLE
WinRM - SQL Server DB Deployment : Why a Admin Login/Password is required?

### ISSUE THREAD

**Issue by joel-ld** [microsoft/azure-pipelines-tasks#13388]
## Required Information

Hello, I'm playing around with the Release Pipeline task : WinRM - SQL Server DB Deployment
I'm trying to deploy my SQL EF migration script to an On Prem SQL Server. In term of security into our departement, having a admin account on the Shared SQL server instance is kind on complex and unsecure... Since I cannot find the information on the documentation, i'm asking the question here.

**Question, Bug, or Feature?**  
I was wondering why we need the an admin account for executing an SQL script on a database when the SQL user account is already DB owner? Does the task do something else in background which require the admin rights?

**Enter Task Name**: WinRM - SQL Server DB Deploymen

## Environment
- Azure Devops Server on-prem

Thanks.

**Comment by AmrutaKawade** [comment]
Please find documentation [here](https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/SqlDacpacDeploy/SqlDacpacDeployV2/README.md) 

> The task runs on the automation agent machine, and connects to the target machine(s) using Windows Remote Management (WinRM), and launches a bootstrapping executable program (VisualStudioRemoteDeployer.exe) on the target machine(s), and the bootstrap executable invokes the PowerShell scripts to locate the sqlpackage.exe on the machine, and creates or updates the SQL Server database using sqlpackage.exe.


As the execution happens within the target machine(s), admin username and password is required for target machine not for SQL Server.
