### ISSUE TITLE
Code coverage is showing as 0% in SonarQube when using the Jacoco option in the MavenV3 task.

### ISSUE THREAD

**Issue by tlbonds2** [microsoft/azure-pipelines-tasks#13387]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Bug**  
*Type*: Bug

**Enter Task Name**: MavenV3

MavenV3:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
   - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Org:  MetLife-US
Project Name:  Dental
Build Definition Name:  DMA-PFR3-Release
Build Number:  1.37441

- Agent - Hosted or Private: 
    
    - Private, RedHat 7 OS, Agent version - 2.165.0

## Issue Description

It seems that the MavenV3 task was recently updated from version 3.171.0 to version 3.173.0.  After the update we can see that the code coverage is showing as 0% in SonarQube when using the Jacoco code coverage option in the task within Azure DevOps.  We can see in the commit history for the MavenV3 task that there were some updates for the code coverage report path and we are wondering if that is the source of the issue.  If we switch to the Cobertura option the code coverage appears properly in Sonar.  

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
To Troubleshoot the issue we tried installing the newest SonarQube plugins, specifically SonarJava and Jacoco.

### Error logs

There is no error in the logs, but the code coverage appears as 0%, where as previously it was approximately 50%.

**Comment by ekaterina-tatanova** [comment]
@tlbonds2 Do you still run into this issue?

**Comment by tlbonds2** [comment]
Hello, 
Yes we are still seeing the issue and we are wondering if the following commit caused the issue:
https://github.com/microsoft/azure-pipelines-tasks/commit/d176141b06c23aac345ff21c4d2fa74e3ef95956#diff-99ba5d31f4a9541e7aff1ae8d5e37cdf
When the MavenV3 task went from version v3.171.0 to 3.173.0, the Jacoco code coverage stopped being passed to Sonar and Sonar then reports 0% code coverage.  If we switch to the Cobertura option there is no issue.

Thanks, 
Tom

**Comment by ekaterina-tatanova** [comment]
@tlbonds2 Could you please provide your logs?

**Comment by ekaterina-tatanova** [comment]
@tlbonds2 As a workaround, could you please try to upload the patch from [attachments](https://github.com/microsoft/azure-pipelines-tasks/files/5194102/MavenV3.zip) using [tfx-cli](https://www.npmjs.com/package/tfx-cli). To do that you may use these [instructions](https://github.com/Microsoft/tfs-cli/blob/HEAD/docs/buildtasks.md#upload). This patch reverts changes made in the "Maven and Gradle tasks fixes" [commit](https://github.com/microsoft/azure-pipelines-tasks/commit/d176141b06c23aac345ff21c4d2fa74e3ef95956#diff-f3f6ab347eae90cd8a71f7f49033e323).

Upload command example:

`tfx build tasks upload -u https://<YOUR_ORGANISATION>.visualstudio.com/DefaultCollection -t <YOUR_PERSONAL_ACCESS_TOKEN> --task-path <PATH_TO_TASK>`

Please, let us know if it works for you or if you have any questions.

**Comment by tlbonds2** [comment]
Hi Ekaterina, 
Sure I will try it and let you know.  Thanks!
-Tom

**Comment by ekaterina-tatanova** [comment]
@tlbonds2 This issue is not reproducible for me. It works correctly. Could you please provide your logs? Does the patch help to resolve the issue?

**Comment by tlbonds2** [comment]
@ekaterina-tatanova 
Sorry for the wait.  Reverting the changes to the task did, in fact, resolve the issue.  Let me know your thoughts on next steps.
Thanks, 
Tom

**Comment by anatolybolshakov** [comment]
Hi @tlbonds2 we are going to add ability to control this new behavior by input, and specify it as disabled by default - created PR with related fix

**Comment by tlbonds2** [comment]
Thanks, @anatolybolshakov!  I will look out for the release.  Much appreciated.

**Comment by anatolybolshakov** [comment]
Hi @tlbonds2 the fix for this issue has been rolled out - I'm closing it at the moment, please feel free to reopen it if this is still actual for you
