### ISSUE TITLE
Azure devops push docker to private registry server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by l2999019** [microsoft/azure-pipelines-tasks#13383]
![image](https://user-images.githubusercontent.com/10385855/89174946-4d411b80-d5b9-11ea-829b-4678759fdc7d.png)

My docker registry  is the HTTP protocol

**Comment by ds-ms** [comment]
Did you supply `http://<your-ip>` in the docker registry connection which you've created?

**Comment by lpasquali** [comment]
I share this same issue, and in my case "http://" is explicitly written in the Service connection configuration

**Comment by ds-ms** [comment]
You may want to add a script in your pipeline to solve this. 
Documentation: https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry

Some inline script like:
```sh
echo '{  "insecure-registries" : ["myregistrydomain.com:5000"]}' > $(DOCKER_CONFIG)/daemon.json 
```

**Comment by ds-ms** [comment]
Closing stale issue; feel free to reopen if the problem still persists.

**Comment by amirabbas-ranjbar** [comment]
> Closing stale issue; feel free to reopen if the problem still persists.

I tried this solution and now I'm  getting other error which it says  


```
Encountered error(s) while parsing pipeline YAML:
/azure-pipelines.yml (Line: 18, Col: 1): Unexpected value 'echo '{  "insecure-registries"'
/azure-pipelines.yml: Input string was not in a correct format.
```

**Comment by amirabbas-ranjbar** [comment]
> > Closing stale issue; feel free to reopen if the problem still persists.
> 
> I tried this solution and now I'm getting other error which it says
> 
> ```
> Encountered error(s) while parsing pipeline YAML:
> /azure-pipelines.yml (Line: 18, Col: 1): Unexpected value 'echo '{  "insecure-registries"'
> /azure-pipelines.yml: Input string was not in a correct format.
>

it works with 
`'sudo echo {  "insecure-registries" : ["address:5000"]} > $(DOCKER_CONFIG)/daemon.json'`

but it returns permission error
