### ISSUE TITLE
SSH Task failing running inline script

### ISSUE THREAD

**Issue by junketer** [microsoft/azure-pipelines-tasks#13385]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: here  
SSH

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account : oagaviation
Team: Schedules
releaseId=3317

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

Schedules Deployment

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Agent version 2.1489.2
Windows Server 2008 R2 Standard

## Issue Description

Convert script files to contain Unix style line ends
![SSHTaskFailure](https://user-images.githubusercontent.com/3359834/89286372-ff282880-d649-11ea-8cbb-9ccd3e7b7992.JPG)

### Task logs

[tasklog_9 (2).log](https://github.com/microsoft/azure-pipelines-tasks/files/5021690/tasklog_9.2.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by junketer** [comment]
HI, any feedback on this? Is it accepted, or anyone got any idea on the issue?
Regards

**Comment by alexander-prozorov** [comment]
Hello, @junketer!

Could you please provide the Node.js version installed on the agent?

Thanks for the task logs. The error message says randomFillSync is missing, which could mean that the NodeJS version the agent is using is lower than 6.13.0.

Information about actual Node.js versions is [here](https://github.com/nodejs/Release).

**Comment by junketer** [comment]
Hi, node version is 10.14.1
[image: image.png]

**Comment by junketer** [comment]
Hi, I created a new agent on my laptop and it's Node.js version is 10.14.1 and the SSH task ran fine on that agent.
So suspect something else on the windows server where it is failing is the issue here

**Comment by alexander-prozorov** [comment]
Thank you. Could you please also provide the complete pipeline log from Windows Server 2008 agent?

**Comment by junketer** [comment]
[ReleaseLogs_3329.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5041866/ReleaseLogs_3329.zip)

**Comment by junketer** [comment]
[ReleaseLogs_3331.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5049539/ReleaseLogs_3331.zip)
Another full set of logs after agent server rebooted

**Comment by junketer** [comment]
Hi any more feedback/progress on this?
regards

**Comment by alexander-prozorov** [comment]
Hello @junketer,
Thank you for the complete logs. The version of the agent you are using includes only node.js 6. This problem can be solved by updating the agent to its actual state. You can use [this instructions](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#to-update-self-hosted-agents
)

**Comment by junketer** [comment]
Ok, when i look at the server, I see it has the version I reported installed, so I will talk to our operational engineers about what the agents run as as clearly it's not the same as when I am on it.
Thanks for the steer

**Comment by junketer** [comment]
Where do you see that version in the logs?

**Comment by alexander-prozorov** [comment]
Agent's version is available at the **Initialize job** step logs:

`Current agent version: '2.155.1'`

Internal agent's software versions can be found in the [externals.sh](https://github.com/microsoft/azure-pipelines-agent/blob/v2.155.1/src/Misc/externals.sh) script in the corresponding project branch

**Comment by junketer** [comment]
OK, so the issue isn't node per se, but an old agent version?
so i need to update the agent on the server and that should resolve?
Sorry, but that wasn't obvious in the comments made.
Regards

**Comment by junketer** [comment]
Thank you I re-read your comment and it makes sense to me now.
Have updated the agents and pipeline is good again
Many thanks for your support!
