### ISSUE TITLE
VSTS Test Task - Javascript Heap Out of Memory

### ISSUE THREAD

**Issue by alohaninja** [microsoft/azure-pipelines-tasks#13390]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTS Test Task - Javascript Heap Out of Memroy  

list here (V# not needed):  VSTest

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: azurecom, acom, Continuous Integration for Pull Requests, DefId 783

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name: Onyx Agents

    - If using private agent, provide the OS of the machine running the agent and the agent version: Win2016

## Issue Description
`node.exe` is failing to allocate enough memory to run the entire test suite.

- Related Issue: https://github.com/microsoft/azure-pipelines-tasks/issues/4734

### Task logs
```
2020-08-04T17:07:53.9741471Z FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2020-08-04T17:07:55.1016706Z ##[error]Exit code 3 returned from process: file name 'E:\onyx-agent-05\externals\node\bin\node.exe', arguments '"E:\onyx-agent-05\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\runvstest.js"'.
2020-08-04T17:07:55.1028325Z ##[section]Finishing: Run Acom and Acom Jobs Unit tests
```

**Comment by alohaninja** [comment]
# Patching Bug
[Increasing the memory limit for `node` globally seems to have fixed the bug](https://github.com/TrilonIO/aspnetcore-angular-universal/issues/736#issuecomment-517374967). Curious why this is happening or how to make this more discoverable for pipeline task consumers.

## Increasing NodeJS Runtime Memory
```
[Environment]::SetEnvironmentVariable("NODE_OPTIONS", "--max_old_space_size=16384", "Machine")
```

**Comment by v-binpan** [comment]
@alohaninja There is an similar scenario when using "**Azure App Service deploy**" task (**Version**: 4.171.0 ) to deploy NodeJs App service, the error message is shown as below:
 ##[debug]Processed: ##vso[telemetry.publish area=TaskDeploymentMethod;feature=AzureWebAppDeployment]{"deploymentMethod":"Zip Deploy"}
 ##[debug]WebConfigParameters is -Handler iisnode -NodeStartFile server.js -appType node
##[debug]Agent.TempDirectory=d:\a\_temp
 ##[debug]Agent.TempDirectory=d:\a\_temp
 ##[debug]extracting d:\a\r1\a\Drop\drop\***.zip to d:\a\_temp\temp_web_package_***
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by ShreyasRmsft** [comment]
Please provide entire logs zip obtained after setting system.debug = true and re-running the pipeline with this issue.
