### ISSUE TITLE
DownloadPackage@1 should have an option to download a specific maven snapshot version

### ISSUE THREAD

**Issue by satbai** [microsoft/azure-pipelines-tasks#13395]
**Question, Bug, or Feature?**  Feature
**Enter Task Name**: DownloadPackage@1

## Issue Description
Using DownloadPackage@1 task to download Maven snapshot versions, it would be great to be able to only download a specific snapshot version. Currently all snapshots are downloaded.

**Comment by satbai** [comment]
It is currently not desirable to add _package type specific_ behavior to a generic DownloadPackage task. As a workaround, a [MavenAuthenticate ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate) task should be used followed by a maven script task to download a desired snapshot version.

**Comment by magleaso** [comment]
+1 to not adding more to DownloadPackage task. Imo DownloadPackage has a few deficiencies in downloading that are unlikely to be fixed (have seen issues w/ corrupt downloads). It should be used to trigger a pipeline, but not to download artifacts

**Comment by samuelkoppes** [comment]
We do not plan to support downloading specific snapshots of Maven packages. Please see @satbai comment above.

**Comment by guicey** [comment]
> It is currently not desirable to add _package type specific_ behavior to a generic DownloadPackage task. As a workaround, a [MavenAuthenticate ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate) task should be used followed by a maven script task to download a desired snapshot version.

@samuelkoppes @satbai We currently run in an issue that space is running out on a vm because 25 snap versions of a multi package project are being downloaded by the DownloadPackage@1 task. Can you give more inside how to work around this issue?
