### ISSUE TITLE
IIS Web App Manage (On machine group) | Adding bindings should be a graceful operation

### ISSUE THREAD

**Issue by lostphenomenon** [microsoft/azure-pipelines-tasks#13398]
**WHEN** choosing the "Add binding" option in a "IIS web app manage" task
**IF** you have a binding that requires a certificate (https) and you have a thumbprint provided
**THEN** the first initial deployment will succeed
**THEN** all the consecutive ones will fail on the part where netsh is called in a similar manner:
`"netsh" http add sslcert ipport=0.0.0.0:443 certhash=*** appid={a78bae04-5ec5-4fc4-a879-c9fd8ba3ddb0} certstorename=MY`
**BECAUSE** the binding with the given certificate already exists

So currently you have to no if you are deploying a binding initially or not, and customize the deployment and only turn on/enable the add bindings part for the initial one or else it will fail.

I think it would be proper if given the error message _SSL Certificate add failed, Error: 183
Cannot create a file when that file already exists._ we shouldn't fail the task, and continue adding missing bindings if any or with execution of next task, but currently this fails a deployment.

**Comment by DenVifer** [comment]
I discovered the following strangeness.
In the Add-SslCert util (https://github.com/microsoft/azure-pipelines-extensions/blob/master/TaskModules/powershell/TaskModuleIISManageUtility/AppCmdOnTargetMachines.ps1) the following code looks incorrect.

`
$isItSameBinding = $result.Get(4).Contains([string]::Format("{0}:{1}", $hostname, $port))
`

...

`
$isItSameBinding = $result.Get(4).Contains([string]::Format("{0}:{1}", $ipAddress, $port))
`

...

`
$isItSameCert = $result.Get(5).ToLower().Contains($certhash.ToLower())
`

In my environment this checking always returns false. But if i replace $result.Get(4) to $result.Get(6) and $result.Get(5) to $result.Get(7), similar ps script works correctly.
And in fact i see that in the "netsh show sslcert" output needed data are located on lines 6 and 7, but not 4 and 5. Is it possible that the command output was changed?

**Comment by jepperip** [comment]
Was this fixed somehow? I have the same problem and its very annoying to have the task fail when the binding hasn't actually changed.
