### ISSUE TITLE
AzureCLI Variable escaping

### ISSUE THREAD

**Issue by dazinator** [microsoft/azure-pipelines-tasks#13397]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Arguably both

**Enter Task Name**: AzureCLIV1, AzureCLIV2 

## Environment
- Server - Azure Pipelines (Releases, classic)
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
UNIUN, UNIUN, Uniun Website, releaseId=1071&environmentId=2584

- Agent - **Hosted**:
    
    - If using Hosted agent, provide agent queue name: **win-latest**

## Issue Description

When using the AzureCLIV1 or V2 task in a classic Release pipeline,
If using variables in the "inline script"
The variables aren't escaped according to the scripting environment being used.
See: https://github.com/microsoft/azure-pipelines-tasks/issues/13161 for more detail.

This means, suppose you want to use a variable in the inline script, and it has been entered into devops and it may contain a special character (special as deemed by the scripting language used by the task, e.g batch script, powershell etc) - you have to create a second copy of that variable in devops, that is the "escaped" version of the same variable, and use that version in the inline script of this task. Otherwise the script will break.

This means you have to maintain two copies of such variables, and manually keep them in sync. This is not ideal. Is there a better way to solve this?

Perhaps you could add a "Escape variables?" option to the task, so that when this is checked, any variables uses in the inline script, will be escaped based on the rules of the target scripting language?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
See: https://github.com/microsoft/azure-pipelines-tasks/issues/13161 for more detail.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
See: https://github.com/microsoft/azure-pipelines-tasks/issues/13161 for more detail.

**Comment by dazinator** [comment]
For a concrete example of the particular difficulty I am getting into with variables and special chars:

https://github.com/Azure/azure-cli/issues/14693

**Comment by bishal-pdMSFT** [comment]
@dazinator we haven't heard this issue from multiple folks. I would like to hear more feedback before trying to fix this issue. I am keeping the issue open for sometime for more folks to report this.
