### ISSUE TITLE
AzureFunctionApp@1 - missing Additional Deployment Options

### ISSUE THREAD

**Issue by gidich** [microsoft/azure-pipelines-tasks#13402]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Add missing "Additional Deployment Options" to AzureFunctionApp@1  

## Environment
Azure Pipelines

## Issue Description

The documentation notes the ability to change deployment method by using Additional Deployment Options but this does not exist in the UI

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops

"To change the deployment option in designer task, expand Additional Deployment Options and enable Select deployment method to choose from additional package-based deployment options."

deploymentMethod: zipDeploy || runFromPackage

**Comment by AmrutaKawade** [comment]
![image](https://user-images.githubusercontent.com/65217380/90605798-7b129b00-e21c-11ea-913c-24b7ffa3ef3b.png)
this option is already available
