### ISSUE TITLE
GitHub Release on Azure Devops Server not compatible with GitHub Enterprise

### ISSUE THREAD

**Issue by totalgit74** [microsoft/azure-pipelines-tasks#13409]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: GitHub Release

## Environment
- Azure DevOps Server  Version Dev17.M153.5
- Agent - Private: 
    - Version 2.153.1 on Windows Server 2016 Standard 10.0.14393

## Issue Description

When attempting to use the GitHub Release task in Azure DevOps on premise installation with on-premise GitHub Enterprise I get the following error

`The pipeline is not valid. Job Job: Step GitHubRelease input gitHubConnection expects a service connection of type github but the provided service connection GitHub Enterprise is of type githubenterprise`

Request the functionality please be added to the task.

**Comment by totalgit74** [comment]
Same request in #11570

**Comment by glaenzesch** [comment]
@damccorm: Any updates on this issue? This would bring Azure DevOps Server and GitHub Enterprise closer together, Unfortunatelly not all allowed to use the cloud alternatives in an enterprise environment.

**Comment by jlamhp** [comment]
@damccorm +1 for this feature as well. please consider adding this when possible. issue is also seen with the cloud-based version of ADO.

**Comment by totalgit74** [comment]
There seems To be interest in this from those limited to on premise software yet little progress even though the requests get assigned

**Comment by totalgit74** [comment]
Bump

**Comment by totalgit74** [comment]
Bump

**Comment by FISHMANPET** [comment]
This is still needed

**Comment by cristian-rincon** [comment]
Hi, is there an update for this issue in 2023?

**Comment by cristian-rincon** [comment]
Is there any progress on this topic?

**Comment by FISHMANPET** [comment]
I'm still interested in this feature as well.

**Comment by hazzmatazz1** [comment]
I am interested in this feature as well, need to make comments on PRs within our GHES instance

**Comment by jlamhp** [comment]
I'm surprised that no change or comment has been made on this? Please take a look at this.

(Maybe we should open a new request?)

**Comment by Jon889** [comment]
@chshrikh @romil07 @damccorm Is there any update for this?
