### ISSUE TITLE
UseDotNet@2 not compatible with windows-2019 pool agents currently

### ISSUE THREAD

**Issue by jklaus** [microsoft/azure-pipelines-tasks#13419]
Currently UseDotNet@2 is downloading 3.1.401 which has a dependency on MSBuild 16.7, yet the agents only have 16.6.X.

**Comment by t-dedah** [comment]
@jklaus Fix for this will be deployed this week, where we will be able to add input for compatible Visual studio version and sdk version will be installed accordingly.

**Comment by tejasd1990** [comment]
Hi @jklaus , the feature to add input for visualstudio version has been rolled out in most regions. Can you check if you are able to get unblocked?

**Comment by tejasd1990** [comment]
Hi @jklaus , the rollout is complete, let us know if you are unblocked so that we can close this issue.
