### ISSUE TITLE
install jdk task

### ISSUE THREAD

**Issue by justintian** [microsoft/azure-pipelines-tasks#13411]
log is:, and java_home is not correct as I configed (C:\hostedtoolcache\windows\jdk8)
Retrieving the JDK from local path.
##[warning]Can't find loc string for key: ExtractingArchiveToPath
ExtractingArchiveToPath C:\hostedtoolcache\windows\jdk8\JAVA_HOME_8_x64_jdk1.8.0_231_zip
Creating destination folder: C:\hostedtoolcache\windows\jdk8\JAVA_HOME_8_x64_jdk1.8.0_231_zip
Extracting file: d:\a_temp\automation-buildresource\java\jdk1.8.0_231.zip

the succcess log should be :
Retrieving the JDK from local path.
Creating destination folder: C:\hostedtoolcache\windows\jdk8
Extracting file: d:\a_temp\automation-buildresource\java\jdk1.8.0_231.zip
d:\a_tasks\JavaToolInstaller_c0e0b74f-0931-47c7-ac27-7c5a19456a36\0.171.0\FileExtractor\7zip\7z.exe x -oC:\hostedtoolcache\windows\jdk8 d:\a_temp\automation-buildresource\java\jdk1.8.0_231.zip

**Comment by justintian** [comment]
log is:, and java_home is not correct as I configed (C:\hostedtoolcache\windows\jdk8)
Retrieving the JDK from local path.
##[warning]Can\'t find loc string for key: ExtractingArchiveToPath
ExtractingArchiveToPath C:\hostedtoolcache\windows\jdk8\JAVA_HOME_8_x64_jdk1.8.0_231_zip
Creating destination folder: C:\hostedtoolcache\windows\jdk8\JAVA_HOME_8_x64_jdk1.8.0_231_zip
Extracting file: d:\a\_temp\automation-buildresource\java\jdk1.8.0_231.zip


the succcess log should be :
Retrieving the JDK from local path.
Creating destination folder: C:\hostedtoolcache\windows\jdk8
Extracting file: d:\a\_temp\automation-buildresource\java\jdk1.8.0_231.zip
d:\a\_tasks\JavaToolInstaller_c0e0b74f-0931-47c7-ac27-7c5a19456a36\0.171.0\FileExtractor\7zip\7z.exe x -oC:\hostedtoolcache\windows\jdk8 d:\a\_temp\automation-buildresource\java\jdk1.8.0_231.zip

**Comment by anatolybolshakov** [comment]
Hi @justintian, thanks for heads up! We fixed this issue and going to roll out changes with next release

**Comment by egor-bryzgalov** [comment]
Closing this issue since the fix is deployed. Please feel free to reopen it.
