### ISSUE TITLE
'AzureSignTool.exe' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by anti-matter** [microsoft/azure-pipelines-tasks#13428]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI@2

## Issue Description

[Previous issue](https://github.com/microsoft/azure-pipelines-tasks/issues/13361#issue-666613881) was closed, but is still a major problem:

We are hitting this 100% in our environment today.

### Task logs

https://dev.azure.com/cloudflare-ps/1111-desktop/_build/results?buildId=2302&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3

**Comment by jozefizso** [comment]
This started to happen in our private Pipelines too.

**Comment by anti-matter** [comment]
[azure-pipelines.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5144242/azure-pipelines.zip)

@bishal-pdMSFT 
1. Attached
2. Attached
3. Hosted
4. Will reply with that in a bit

**Comment by anti-matter** [comment]
@bishal-pdMSFT 

[azuresigntooltask_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5144253/azuresigntooltask_log.txt)

1. Attached
2. Task:
`  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global azuresigntool'
    displayName: Install AzureSignTool`
3. Hosted
4. Will post as soon as I have it.

**Comment by anti-matter** [comment]
@bishal-pdMSFT 
Here is #4 from your request (the PATH environment). We just hit this several more times today!!

`2020-08-31T20:25:10.2947477Z C:\agents\2.174.1\externals\git\cmd;C:\Program Files\Mercurial\;C:\Program Files\MongoDB\Server\4.4\bin;C:\aliyun-cli;C:\ProgramData\kind;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.3.3\x64;C:\ProgramData\chocolatey\lib\ghc.8.10.2\tools\ghc-8.10.2\bin;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\R\R-4.0.2\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Rust\.cargo\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\hostedtoolcache\windows\go\1.14.7\x64\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\hostedtoolcache\windows\Ruby\2.5.8\x64\bin;C:\Program Files\Java\jdk8u265-b01\bin;C:\npm\prefix;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Docker;C:\Program Files\PowerShell\7\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\Program Files\TortoiseSVN\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\Program Files\CMake\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps
`

**Comment by anti-matter** [comment]
Any update on this? 10 days since I provided above information. We are hitting this failure regularly.

**Comment by tejasd1990** [comment]
Hi @anti-matter , I am investigating this, will update you

**Comment by tejasd1990** [comment]
@anti-matter can you share the logs(with system.debug set to true) of the dotnetcorecli task where you are installing the tool? The logs you have shared are of the task where you want to execute this tool

**Comment by anti-matter** [comment]
Hi @tejasd1990,

Sorry for the delay, I needed to wait until we got a failure w/ debug logs enabled. Attached here.
[install-sign-tool.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5220871/install-sign-tool.txt)

**Comment by tejasd1990** [comment]
Hi @anti-matter , no worries.
The logs say that
> Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.

This is a dotnet sdk issue, discussed [here](https://github.com/dotnet/sdk/issues/8999), and from what I see in the discussion, does not provide a clean solution. Restarting the agent after installing the dotnet sdk is not possible/feasible. 
You can workaround by adding the directories specified [here](https://github.com/dotnet/sdk/issues/8999) to the path environment variable, or giving the full path of the tool executable.

**Comment by tejasd1990** [comment]
Hi @anti-matter , ping!

**Comment by bishal-pdMSFT** [comment]
@anti-matter AFAIK if you are using UseDotNet@2 task then this error should not happen. It sets environment path for global tools.

**Comment by anti-matter** [comment]
Hi, I’m not familiar with that task. Here is our current task:

- task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global azuresigntool'
    displayName: Install AzureSignTool

Are you saying I should replace “DotNetCoreCLI@2” with “UseDotNet@2” ??

Thanks!
--Mike

Sent from Mail for Windows 10

**Comment by bishal-pdMSFT** [comment]
Closing stale issue. Please re-open if you are still facing this issue.

**Comment by CurlyBytes** [comment]
@bishal-pdMSFT  its not stale, there is a response, kindly reopen, experience of the same issue as well thanks

**Comment by bishal-pdMSFT** [comment]
Adding @naga-bandi and @v-abajaj as their team owns this task now
