### ISSUE TITLE
ExtractFiles incorrectly finds archives recursively

### ISSUE THREAD

**Issue by staywen56** [microsoft/azure-pipelines-tasks#13434]
## Required Information

*Type*: Bug

*Task Name*: ExtractFiles

## Environment

*Server*: Azure Pipelines
- Account name: wencorepo
- Team project name: Dependencies
- Build number: 34933
- Pipeline: libzmq (definitionId=20)

From log:
- Agent name: 'Azure Pipelines 2'
- Agent machine name: 'fv-az246'
- Current agent version: '2.173.0'
- Operating System: Ubuntu 18.04.4 LTS
- Virtual Environment: ubuntu-18.04 20200806.0
- Agent running as: 'vsts'

## Issue Description

The ExtractFiles task incorrectly extracts an archive (.tar.xz) that is nested under a subdirectory, even though we did not use a globstar (**) pattern in archiveFilePatterns.

It looks like `minimatch.match()` (extractfilestask.ts ln 87) is incorrectly matching files in subdirectories.
```js
var matched = minimatch.match(allFiles, parseResult.search, matchOptions);
```

This behavior occurs regardless of whether archiveFilePatterns is `'*.tar.xz'` or `'$(Build.SourcesDirectory)/*.tar.xz'`. It is a 100% repro.

I think it must be something about the minimatch version or its usage within Azure. I cannot reproduce the issue with a standalone copy of latest minimatch from npm.

Task definition:
```yaml
  - task: ExtractFiles@1
    displayName: Extract dependencies
    inputs:
      archiveFilePatterns: '$(Build.SourcesDirectory)/*.tar.xz'
      destinationFolder: '$(Build.SourcesDirectory)'
      cleanDestinationFolder: false
```

Pipeline details:
- Run: #20200812.4
- Job: Linux_owa4x
- Task: 'Extract dependencies'

### Task logs

Full debug log: [ExtractFiles-debug-log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5082526/ExtractFiles-debug-log.zip)

### Error logs

This part of the log illustrates the issue. Notice there is no globstar (**) but it still finds recursively:

```text
##[debug]using: 1 archiveFilePatterns: /home/vsts/work/1/s/*.tar.xz to search for archives.
##[debug]searching for archives, pattern[0]: /home/vsts/work/1/s/*.tar.xz
##[debug]normalizedPattern= /home/vsts/work/1/s/*.tar.xz
##[debug]parsePattern: /home/vsts/work/1/s/*.tar.xz
##[debug]makeAbsolute:/home/vsts/work/1/s/
Searching for: *.tar.xz under directory: /home/vsts/work/1/s/
##[debug]findPath: '/home/vsts/work/1/s/'
...
##[debug]11981 results
##[debug]Candidates found for match: 11981
##[debug]adding file: /home/vsts/work/1/s/depends/owasys_owa4x/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
##[debug]adding file: /home/vsts/work/1/s/libsodium-1.0.18-linux-owa4x.tar.xz
Found: 2 files to extract:
/home/vsts/work/1/s/depends/owasys_owa4x/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
/home/vsts/work/1/s/libsodium-1.0.18-linux-owa4x.tar.xz
```

See also full log: [ExtractFiles-debug-log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5082526/ExtractFiles-debug-log.zip)

**Comment by anatolybolshakov** [comment]
Hi @staywen56 the fix has been rolled out for this issue - I'm closing it at the moment, please feel free to reopen it if it's still actual for you
