### ISSUE TITLE
Syntax error in JSON for Azure IoT Edge "Push module images"

### ISSUE THREAD

**Issue by shoop** [microsoft/azure-pipelines-tasks#13442]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdgeV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

When trying to setup the "Push module images" action of the task, the `azureContainerRegistry` parameter needs to be specified as a valid JSON object. This is undocumented and leads to a very hard to debug error in the log, where the only failure is:

```##[error]SyntaxError: Unexpected token a in JSON at position 0```

After finding issue #13261 this helped me to find the root cause.

### Task logs

Can be provided on request but this is the relevant snippet, redacted:

```
2020-08-18T10:05:06.2062925Z Pushing module images...
2020-08-18T10:05:06.2065233Z ##[debug]containerregistrytype=Azure Container Registry
2020-08-18T10:05:06.2077212Z ##[debug]containerregistrytype=Azure Container Registry
2020-08-18T10:05:06.2078416Z ##[debug]azureSubscriptionEndpoint=<subscription_guid>
2020-08-18T10:05:06.2079480Z ##[debug]azureContainerRegistry=aregistryname.azurecr.io
2020-08-18T10:05:06.2100083Z ##[debug]task result: Failed
2020-08-18T10:05:06.2136264Z ##[error]SyntaxError: Unexpected token a in JSON at position 0
```

Note that the "unexpected token" is "a" which matches the first character of the name of the azureContainerRegistry.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

See Task logs above.

## Suggested fixes

After figuring out where the problem actually was, setting the `azureContainerRegistry` parameter correctly was done like this:

```
azureContainerRegistry: '{"loginServer":"$(azureContainerRegistry)", "id":"/subscriptions/<subscription_name>"}'
```

Please at least fix the documentation so that this is apparent. The current version at

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops#container-registry-types

strongly suggests that only the DNS name is enough.

Next up I don't see why this needs to be a JSON object including once again the subscription, seeing as that is specified as a separate parameter. Would be better to accept the DNS name in my opinion.

**Comment by blackchoey** [comment]
@marianan @konichi3 could you help on this?

**Comment by konichi3** [comment]
@shoop Thanks for reporting the issue. We have put this issue in our backlog.

**Comment by avagraw** [comment]
@shoop It seems like you were able to get around this issue. Wanted to make sure that you are no longer stuck on this?

We plan to make the required changes to the documentation, error message as well as the input format.

**Comment by shoop** [comment]
@avagraw Thank you for checking in, I'm not stuck on this. Glad to hear that this will be improved!

**Comment by shoter** [comment]
> 
> 
> @shoop It seems like you were able to get around this issue. Wanted to make sure that you are no longer stuck on this?
> 
> As of now, we are updating the document to prevent others from running into the same issue. We are also creating a backlog item to track the required code changes (error message and input format updates) to improve the user experience.

@avagraw When document is going to be updated? I was stuck on that too.

**Comment by marianan** [comment]
@shoter this section's yaml code has been updated per the feedback from this thread - https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops#push-module-images

In addition we found that this specific article [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops) is not complete and we recommend using [this one](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment-classic?view=iotedge-2020-11) instead until we resolve the content.
