### ISSUE TITLE
Question regarding VsTestV2 and test adapters

### ISSUE THREAD

**Issue by JoaBjo** [microsoft/azure-pipelines-tasks#13447]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VsTestV2

## Environment
    
Azure DevOps Server On-prem
Version Dev17.M153.3

Private Agent
Version 2.153.1
OS: Windows Server 2019

## Issue Description

My setting is that I've built & deployed my binaries (including tests) to the target server. The deploy works and every service is up and running. Now I'm trying to run my deployed integration tests. My issue is that I don't understand how you're supposed to configure VsTest so that the call to vstest.console.exe is as I want it to be.

My deployed tests are structured like this: 

```
Integration Tests
│
└───A
│   │  A.IntegrationTest.dll
│   │  Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
|   |  ...
│   
└───B
    │  B.IntegrationTest.dll
    |  Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
    |  ...
```
If I run vstest from command line every test runs as expected. vstest automatically finds the TestAdapter in the same folder as the test binary:
`vstest.console.exe .\A\A.Integration.Test.dll /Platform:x64 /Framework:net472`

But if I try to run the same test from the pipeline I can't get it to work.

![VsTest config](https://i.imgur.com/hAEayu8.png)

Please note that I have more than one test folder and later on I want to able to run all of them in the same task. Hence the Search folder is set the C:\Deploy\Integration Tests. But for now I only try to run tests in the A folder.

The issue as I see is that when leaving "Path to custom test adapters" empty the VsTest task actually still sets the property /TestAdapterPath in vstest.console.exe like this:

`vstest.console.exe .\A\A.Integration.Test.dll /Platform:x64 /Framework:net472 /TestAdapterPath:"D:\Deploy\Integration Tests\"`

and by doing this it puts vstest's ability to look for test adapters in the same folder as the test binaries out of play. I looked in the VsTest2 source code and verified that this is the intended behavior.

Is there any way to not set the /TestAdapterPath property when using the VsTest2 task? Or am I doing something fundamentally wrong here? How is it meant to work by design?

Thank you in advance!

**Comment by ShreyasRmsft** [comment]
@JoaBjo consider using the "dotnet" task where you have more control/flexibility over settings.

**Comment by JoaBjo** [comment]
> @JoaBjo consider using the "dotnet" task where you have more control/flexibility over customizing settings to your preference.

I definitely would I if I could! However, it's unfortunately not available when running a deployment group job. At least not in my version of Azure Dev Ops.

**Comment by ShreyasRmsft** [comment]
You can locally build the dotnet task after adding [one line to it](https://github.com/microsoft/azure-pipelines-tasks/blob/fec3b6b1c72fa8e3acc8356ba425697afc3a9ea0/Tasks/VsTestV2/task.json#L15) in this [file](https://github.com/microsoft/azure-pipelines-tasks/blob/fec3b6b1c72fa8e3acc8356ba425697afc3a9ea0/Tasks/DotNetCoreCLIV2/task.json#L15) and then change the name of the task to dotnet experimental or something and change the task guid and then build and publish it to your account.

How to guide for cloning the reop and build it locally https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md#build-a-specific-task-recommended and this for publishing the task https://www.donovanbrown.com/post/how-do-i-upload-a-custom-task-for-build

**Comment by ShreyasRmsft** [comment]
The design of the vstest task is the way it is because we do not expect to find more than one test adapter type/version for one test framwork.

The task assumes that all tests that belong to a particular test framework can be run using the highest version of a particular adapter found under the test adapter path.

**Comment by JoaBjo** [comment]
Thank you for the explanation and for the instructions for how to work around it if necessary.
