### ISSUE TITLE
Docker task - is Managed Identity supported?

### ISSUE THREAD

**Issue by rlevchenko** [microsoft/azure-pipelines-tasks#13452]
I'm using MI service connection to Azure, Docker v0 task and faced with some issues during the docker push execution. Briefly checked source code of Docker v0 task and haven't understood whether MI supported or not (not sharing my findings, I'm not a prof. developer..waiting for your response instead)

**Comment by ajinkya599** [comment]
Managed Identity based service connection is not supported in Docker task. The service connection needs to be based on [service principal](https://github.com/microsoft/azure-pipelines-tasks-common/blob/main/docker-common/registryauthenticationprovider/acrauthenticationtokenprovider.ts#L43) to work with Docker task.

**Comment by rlevchenko** [comment]
@ajinkya599 thanks. So, I understood the code correctly :) and already switched to SP
