### ISSUE TITLE
AzureFunctionApp if deploying to a slot with auto-swap which fails, task returns successful

### ISSUE THREAD

**Issue by ricohomewood** [microsoft/azure-pipelines-tasks#13457]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionAppV1 

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFunctionAppV1

## Environment
- Azure Pipelines 

- Agent - Hosted

## Issue Description

When you deploy to a function app `staging` slot that has auto-swap enabled, if that auto swap operation fails, the AzureFunctionAppV1 task either doesn't know or doesn't wait to see if auto-swap was successful and so the task returns green / successful event where a slot-swap failed. This should throw an error and stop the pipeline run if this errors.

## Troubleshooting
- configure a function app with a staging slot that has auto-swap enabled.
- configure the staging slot with the follow app settings based on a function called `healthcheck` that just returns 200:
`-WEBSITE_SWAP_WARMUP_PING_PATH /healthcheck -WEBSITE_SWAP_WARMUP_PING_STATUSES 500'`
The above `WEBSITE_SWAP_WARMUP_PING_STATUSES 500` will force a auto-swap to fail.
- Run a deployment to the `staging` slot using YAML or classic and observe the slots swap fail in Azure Activity Log initiated by the `SlotSwapJobProcessor` and also observe the pipeline task succeed and go green which is should not do.

**Comment by 20shivangi** [comment]
Is this still occuring ?

**Comment by ricohomewood** [comment]
@20shivangi Yes, well its the fact that this task knows nothing about autoswap if that has been configured on a slot that this task is deploying to.

We have now reverted to using the `AzureAppServiceManage@0` task now and turning autoswap off because we couldn't rely on the AzureFunctionApp task going green on the DevOps pipeline if the autoswap fails for whatever reason.

**Comment by 20shivangi** [comment]
@ricohomewood Sorry for the late response. Are you still facing the issue ?

**Comment by ricohomewood** [comment]
@20shivangi Yes indeed this still happens as a workaround we are no longer relying on the auto-swap feature and manually swapping using a different task.

**Comment by 20shivangi** [comment]
It is great that workaround is working for you. We will check and work on auto-swap

**Comment by AmrutaKawade** [comment]
since `auto-swap` is the feature provided by function apps. whenever you deploy to slot which has auto-swap enabled it will automatically swap app to destination slot.

since as task we just have info about target app where app needs to be deployed and not about slot where app will be swapped, its difficult for us to monitor that slot to check whether swap succeeded or not.

There are no APIs as well available currently to verify this.

Sorry to say but `AzureAppServiceManage@0` is the solution currently to solve such scenarios
