### ISSUE TITLE
UseDotNet@2 Unable to verify leaf signature

### ISSUE THREAD

**Issue by justindbaur** [microsoft/azure-pipelines-tasks#13467]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet@2  

## Environment
- Server - Azure Pipelines or TFS on-premises? TFS on-premises
    
    - If using TFS on-premises, provide the version: Azure DevOps Server 2019
 
- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2019 1809, Agent Version 2.153.1

## Issue Description

I am trying to use UseDotNet@2 to download/ensure I have the latest version of .NET Core on my server.  I have trying running the task for each of these options: 3.1.x, 3.1.301, and 3.1.401 but all three will give me this error: "Failed while getting version 3.1.301 from channel 3.1 with error: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}"

![Annotation 2020-08-24 165517](https://user-images.githubusercontent.com/19896123/91208269-f15d4480-e6d7-11ea-8002-b64f3f5f0838.png)

I have searched the error and it appears to be with Node.js and this hasn't been an issue on previous versions so that's what makes me think this is a bug.

### Task logs

[logs_191.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5125418/logs_191.zip)

**Comment by tejasd1990** [comment]
Hi @justindbaur , this looks like a certificate issue while getting the version with the channel. I could not repro it, so it will need further investigation. Is this issue intermittent, or persistent? Are you seeing this even now, or has it been resolved?

**Comment by tejasd1990** [comment]
Hi @justindbaur , gentle ping!

**Comment by justindbaur** [comment]
Hi @tejasd1990 , Sorry about that. I have now left the job where this was happening at and it doesn't happen at my new job.  I had a feeling it was on their end because I had quite a few issues with proxy and certificates issues there. It was probably on their end I was just hoping for some direction on what we had to do to fix it. But since I won't be able to help debug further I can close the issue.
