### ISSUE TITLE
DownloadBuildArtifactsV0 does not download the latest successful build 

### ISSUE THREAD

**Issue by lszomoru** [microsoft/azure-pipelines-tasks#13469]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadBuildArtifacts

## Environment
- Agent - Hosted or Private: Hosted
    - If using Hosted agent, provide agent queue name: windows-2019

## Issue Description
We have a multi stage pipeline that has a `pipeline` resource defined. We have manually kicked off this pipeline and after it has deployed to the first stage, we have noticed that the DownloadBuildArtifacts that is being injected into the pipeline has not downloaded the most recent successful build for the pipeline resource.

We have noticed that if when we run the pipeline, click on "Resources" in the panel, and click on the pipeline resource, the correct build is being selected by default. This does not seem to be the case when we run the pipeline but do not click on "Resources". 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by leantk** [comment]
@romil07 are you taking a look at this? Wasn't sure if this is an artifact issue we need to look at

**Comment by romil07** [comment]
@leantk I and harshini from my team looked at it but we couldn't repro this or find anything that could cause this issue.
This is pretty simple flow. We call the builds API from pipeline provider and just rely on what API returns. We tried finding the logs to see in the execution flow of that API but didn't find anything.
This issue is not a task issue is what I am saying. We can discuss if you feel the need.

**Comment by lszomoru** [comment]
This issue has been resolved. Thank for your help!
