### ISSUE TITLE
Publish Test Results XUnit - No Result Found to Publish

### ISSUE THREAD

**Issue by djfoz** [microsoft/azure-pipelines-tasks#13465]
*Type*: Bug

**Enter Task Name**: Publish Test Results

## Environment

- Running Azure Pipelines
- Private Agent, Windows 10, Agent Version 2.173.0

## Issue Description

Publish test result does not appear to publish xunit/vstest xml files. The task displays: 
2020-08-25T15:46:58.5873997Z No Result Found to Publish

This is being run as part of a release stage pipeline.

![image](https://user-images.githubusercontent.com/10595414/91198277-45762200-e6f4-11ea-8cb6-d7b52b9ec4e6.png)

This is xunit file that the task is attempting to read:

[outputxunit.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5124922/outputxunit.zip)

### Task logs

[TaskDebugLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5124912/TaskDebugLogs.zip)

### Error logs

2020-08-25T15:46:58.5873997Z No Result Found to Publish 'C:\agents\a1\_work\r1\a\outputxunit.xml'.
2020-08-25T15:46:58.7567390Z No build level attachments to publish.
2020-08-25T15:46:58.9916362Z Result Attachments will be stored in LogStore
2020-08-25T15:46:59.1063813Z Run Attachments will be stored in LogStore

**Comment by upadhyayap** [comment]
@djfoz Could you please confirm if the result file exists in the artifact?

**Comment by upadhyayap** [comment]
@djfoz I used the exact same xml file to publish test results and I could see that the tests are getting published.

**Comment by djfoz** [comment]
> @djfoz I used the exact same xml file to publish test results and I could see that the tests are getting published. The only difference is I selected JUnit as test result format in the publish test result task configuration. Could you please select "JUnit" as test result format and let me know if that works.

@upadhyayap I can confirm that works. Thank you.
