### ISSUE TITLE
WaitForCompletion Property stops Expression to be evaluated

### ISSUE THREAD

**Issue by ManuelGalindo** [microsoft/azure-pipelines-tasks#13474]
**Question, Bug, or Feature?**  
*Type*:  Question
Why if I user the proprty WaitForCompletion the Expression is not evaluated on a ServerGate Custom task?

**Enter Task Name**: Custom ServerGate task

## Environment
We created our own  Azure Pipeline task following https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops&viewFallbackFrom=vsts and we are getting a failure

- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
       Org: DevOpsTekExperts
       TP: Release ServerGate sample
       Release: MSSupport Test - Copy
       Release definitionId=2

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: windows-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

If I use WaitForCompletion Property the Expression Filter is not being evaluated

WaitForCompletion: - Specifies whether Azure Pipelines/TFS server should wait for task completed event from external service. Default value is false which means that Azure Pipelines/TFS server will invoke the URL and once the response received, then it assumes that task is complete. This input is optional.

https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/servertaskauthoring.md

### Task logs
This is working because the WaitForCompletion is not being used

2020-08-27T21:25:49.7472706Z POST https://REDACTED API
				Response Code: OK
				Response: {"REDACTED,"readyForProduction":true,REDACTED}
				Parsing expression: <eq(root['readyForProduction'], 'true')>
				eq
				(
				..root
				..[
				....'readyForProduction'
				..]
				..,
				..'true'
				)
				Evaluating: eq(root['readyForProduction'], 'true')
				Evaluating eq:
				..Evaluating indexer:
				....Evaluating root:
				....=> Object
				....Evaluating String:
				....=> 'readyForProduction'
				..=> True
				..Evaluating String:
				..=> 'true'
				..=> True
				=> True
				Expanded: eq(True, 'true')
				Result: True

## Troubleshooting
We have changed all the properties and the only working is this combination
Property set to False
![image](https://user-images.githubusercontent.com/25435961/91497843-4f2e8f80-e884-11ea-9bb2-924ba0106780.png)

Or do not use the property
![image](https://user-images.githubusercontent.com/25435961/91497961-7f762e00-e884-11ea-975d-b65b2380dfb5.png)

### Error logs

Here is when we use the property WaitForCompletion set to true, the Expression never gets evaluated

![image](https://user-images.githubusercontent.com/25435961/91498430-5ace8600-e885-11ea-89e3-b4f8c396ac24.png)

**Comment by damccorm** [comment]
Hi @ManuelGalindo - this looks like an issue with the service more generally, not with a specific task. This repo mostly holds issues with specific tasks, please file general issues at https://developercommunity.visualstudio.com/spaces/21/index.html - that way it will get the right eyes on it

**Comment by nitish-atomic** [comment]
Is it resolved till now??
