### ISSUE TITLE
AzureFileCopyTask@4 authentication fail

### ISSUE THREAD

**Issue by Tovli** [microsoft/azure-pipelines-tasks#13478]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopyTask@4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
dekelTFS, Shoplink

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name: windows-2019

## Issue Description
When working with the 4th version I get:
```INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42```

Moving to 3rd version solve the issue

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
```[error]Upload to container: '$web' in storage account: '*******' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.' For more info please refer to https://aka.ms/azurefilecopyreadme```

**Comment by AmrutaKawade** [comment]
can you run pipeline with system diagnostics on and share the logs?

**Comment by Tovli** [comment]
Can you please send me reference of how to do that? :)
Or just write me, of course

**Comment by AmrutaKawade** [comment]
![image](https://user-images.githubusercontent.com/65217380/91695877-6de69c00-eb8c-11ea-9fb0-22831c902752.png)
Click on Enable System Diagnostics checkbox

**Comment by Tovli** [comment]
And how do I get to this screen?

**Comment by AmrutaKawade** [comment]
this option comes when you click on run pipeline. Alternatively you can follow steps from [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#run-a-release-in-debug-mode)

**Comment by Tovli** [comment]
Do you have an email I can send the logs to?
I don't feel comfortable putting such sensitive information in a public location

**Comment by AmrutaKawade** [comment]
> Do you have an email I can send the logs to?
> I don't feel comfortable putting such sensitive information in a public location

Sure. Please send logs to amrutakawade@github.com

**Comment by Tovli** [comment]
Well, the classic issue of "problem solved when the expert is here" just happened and the release succeeded
I tried it multiple times now and it seems ok
So I think you can close this and I hope it won't regress :)
Thanks for assisting and the prompt response

**Comment by AmrutaKawade** [comment]
> Well, the classic issue of "problem solved when the expert is here" just happened and the release succeeded
> I tried it multiple times now and it seems ok
> So I think you can close this and I hope it won't regress :)
> Thanks for assisting and the prompt response

That's Great!!!
Closing this issue. 
Feel free to reopen if it regresses.
