### ISSUE TITLE
ExpiredServicePrincipal

### ISSUE THREAD

**Issue by zhenghao104** [microsoft/azure-pipelines-tasks#13480]
While creating a pull request to Azure Pipeline Canary, I got an warning that the Java task failed to localize the string correctly. It looks like there is an issue with the service principal while communicating with Azure to retrieve the JDK.

Warning/Error message: `##[warning]Resource file haven\'t set, can\'t find loc string for key: ExpiredServicePrincipal`

Failed location: Java 1.7 under VS2019

Azure Canary Pipeline: https://github.com/microsoft/azure-pipelines-canary

Pull request: https://github.com/microsoft/azure-pipelines-canary/pull/371/

Failed jobs location: https://buildcanary.visualstudio.com/CanaryBuilds/_build/results?buildId=1064529&view=logs&jobId=95c7feb2-b97d-5f94-1a0e-7d9b998f3687&j=953f69bb-7169-5b71-a4f4-e8815140d508&t=ca4a534d-d6aa-5e4d-04ca-162b517e7c83

Task definition: https://github.com/microsoft/azure-pipelines-tasks/blob/09dd8b21a2cebeaa5d882af0a6d5353d3f8494d8/Tasks/JavaToolInstallerV0/task.json#L177

**Comment by ekaterina-tatanova** [comment]
@zhenghao104 Used service principal was expired. Service connection was [changed](https://github.com/microsoft/azure-pipelines-canary/pull/355) 3 days ago. Could you please check if it works now?

**Comment by zhenghao104** [comment]
Solved, thanks!
