### ISSUE TITLE
Docker stop no longer works

### ISSUE THREAD

**Issue by roizentner** [microsoft/azure-pipelines-tasks#13482]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: Docker  

## Environment
- Server - Azure Pipelines

- Agent - Hosted (ubuntu-18.04)

## Issue Description

Ever since updating the Docker task to include start and stop commands, I can no longer stop my containers.
I am running an elasticsearch container during my pipeline using the name **elasticsearch_$(Build.BuildId)**.
Previously, I've used **docker stop elasticsearch_$(Build.BuildId)** to stop the container (I used the Docker task, typed "stop" in the command and "elasticsearch_$(Build.BuildId)" in the arguments.
Since the task was updated to v2.173.0, it started producing an error: **Unhandled: Input required: container**.
I moved "elasticsearch_$(Build.BuildId)" from arguments to the new container parameter and the error changed to **Unhandled: Container not found: elasticsearch_68172**.
I looked at the code and realized the author now requires the container id (even though the parameter help suggests it requires the name), so I extracted the container id and put it in an environment variable. This didn't work, as it now produces the error: **Unhandled: Container not found: 8d3c66ef5e9c**.

@alex-peck, can you assist?

**Comment by tiagospies** [comment]
I temporarily resolved this way:
![image](https://user-images.githubusercontent.com/10756130/92018533-a4a6e880-ed2b-11ea-88c9-e907289fe92c.png)
