### ISSUE TITLE
add rollout restart to kubectl task 

### ISSUE THREAD

**Issue by farshid3003** [microsoft/azure-pipelines-tasks#13481]
I want to run rollout restart on my EKS cluster on AWS but it does not have rollout command
is there any way to run this command ?

**Comment by ds-ms** [comment]
The command input of the `Kubectl` task is editable. You could add `rollout` to command and `restart <your-resource>` to arguments and try?

**Comment by ds-ms** [comment]
Closing stale issue. Feel free to reopen if your query isn't solved. :)
