### ISSUE TITLE
PublishSymbols fails after Windows Update

### ISSUE THREAD

**Issue by lg2de** [microsoft/azure-pipelines-tasks#13491]
## Required Information

**Question, Bug, or Feature?**: Bug
**Enter Task Name**: PublishSymbols

## Environment
- Azure DevOps Server (on-premises) Version Dev17.M153.5
- private Agent
  - on Windows Server 2019 Version 1809
  - agent version 2.170.0
  - 5 agents are identically configured to the same pool

## Issue Description

The builds using PublishSymbols task were running fine until installation Windows updates.
Now the step fails with `Encountered Win32 error '203' from method 'SymEnumSourceFiles'`.

- We are using V1 and V2 of Publish symbols.
- Last successful run around 5th august.
- Windows updates installed on 13th august: KB4570505, KB4565349, KB4566424

Similar issues exist but already closed without helpful information:
- #9139 => x64 version on x64 Windows is installed
- #13439 => self-closed after downgrade to Win2016

Please note, the waning on dbghelp.dll is very confusing because expected and actual path are identical!

### Task logs

[1_Initialize Job.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5155997/1_Initialize.Job.txt)
[14_Publish symbols.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5155986/14_Publish.symbols.txt)

### Error logs

```
##[warning]Library dbghelp.dll is already loaded from an unexpected path. Expected 'C:\build\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\dbghelp.dll'. Actual 'C:\build\_work\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\dbghelp.dll'.
##[error]Encountered Win32 error '203' from method 'SymEnumSourceFiles'.
```

**Comment by johnterickson** [comment]
@lg2de Are you running the 32-bit version of the agent or the 64-bit version of the agent? (For comparison to #9139)

**Comment by johnterickson** [comment]
@lg2de Also can you confirm that if you uninstall the KB, then this error goes away?

**Comment by isnits** [comment]
Hello,
The same issue here.
OS: Windows Server 2019 Standard Build 1809
Build agent: x64 version 2.153.1 installed on x64 OS
Tried with V1 and V2 Publish Symbols tasks
Mentioned updates are not installed in the system
Error:
[warning]Library dbghelp.dll is already loaded from an unexpected path. Expected 'C:\Builds\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\dbghelp.dll'. Actual 'C:\Builds\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.0.16\dbghelp.dll'.
##[error]Encountered Win32 error '203' from method 'SymEnumSourceFiles'.

**Comment by lg2de** [comment]
@johnterickson , initially I already noted that x64 is running.
I did not try to deinstall any windows update (KB?). This is the only change we noticed in the time range.

**Comment by M463** [comment]
I spend some serious time on this issue as well.
After failing to uninstall any of the mentioned KB (KB4570505, KB4565349, KB4566424) updates via wusa and experimenting with several versions of the task, I was eventually able to **fix the problem by removing McAfee antivirus** from the affected server.
It has been replaced with a competitors product but unfortunately I'm not allowed to share the name of the product here due to company policies.

**Comment by Zanadar** [comment]
I am also experiencing this issue... can anyone confirm that removing a particular windows update resolves the issue?
Doesn't seem like anything else changed on the system in question.

**Comment by gwill1010** [comment]
I have the exact same issue too.  Please respond.

**Comment by lg2de** [comment]
Disabling McAfee does not solve the problem.

**Comment by von-seydlitz** [comment]
Error still exists on Windows 2019 systems. Any Updates on this?

**Comment by dan-griffin** [comment]
We also have the same issue. Server 2019, x64 agent. Error on previous agent versions and latest 2.189.0. Last success publish was Jan 27. We didnt do another build until last week. Thats when the error started for us. Tried restarting service, restarting server, upgrading agent, etc.

**Comment by patcty** [comment]
We also have the same issue. Server 2019, x64 agent. I tried @M463 solution above (as we have Mcafee installed on our server as well) and have identified McAfee as the culprit. However we cannot replace it with any other products so anyone knows what exclusion needs to be in place?

**Comment by gbutler202** [comment]
We've been suffering with this issue as well. Server 2019, x64 agent, McAfee AV. We liaised with the AV vendor and with their help were able to identify in our case the Antimalware Scan Interface (AMSI) feature under On-Access Scan was the culprit. We tried OAS folder exclusions (to which we added the agent's base folder path) but that wasn't sufficient as the process touches bits of Powershell, .Net and system libs. Disabling AMSI or uninstalling AV protection entirely is what resolved it for us.

**Comment by Shahyads** [comment]
I have the same issue. As a workaround you can go to the task folder on the agent machine then open the file DbghelpFunctions.ps1 then for each DllImport attribute in the Add-Type statement , add the   full path to the "dbghelp.dll" 

For example
"E:\\\\agent1\\\\_work\\\\_tasks\\\\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\\\\2.234.0\\\\dbghelp.dll"

See the pull request https://github.com/microsoft/azure-pipelines-tasks/pull/21171
