### ISSUE TITLE
Unable to push image to ACR if basic authorization used

### ISSUE THREAD

**Issue by HardNorth** [microsoft/azure-pipelines-tasks#13490]
# Required Information
*Type*: Bug
**Enter Task Name**: Docker  

## Environment
- Server - Azure Pipelines
  - Account Name: Vadzim Hushchanskou
  - Team Project Name: Report Portal
  - Build definition: service-api
  - Build number: any, starting from build 21, e.g. 29

- Agent - Hosted: 
    - Agent Queue name: Azure Pipelines

## Issue Description
The Docker task unable to push a newly built image to an ACR if I use basic authorization, I'm getting this an `authentication required` error.

The command is: `/usr/bin/docker push reportportaldemo.azurecr.io/service-api:5.4.0-snapshot-build-29`

Here is my connection settings:
![Screen Shot 2020-09-01 at 2 27 15 PM](https://user-images.githubusercontent.com/4364466/91843943-4280b180-ec5f-11ea-9fd6-fe7fa802d967.png)

My pipeline YAML is open and located here:
https://github.com/reportportal/service-api/blob/stable-azure/.azure/pipelines/service-api.yml

### Task logs
[build_log.txt.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5155889/build_log.txt.zip)

## Troubleshooting
I found only one similar issue #10612, but lower-casing tags and repository URL gave me nothing.

### Error logs
```
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
##[error]unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by ds-ms** [comment]
cc: @ajinkya599 could you take a look

**Comment by ajinkya599** [comment]
@HardNorth Are you still facing this issue?

**Comment by HardNorth** [comment]
@ajinkya599 let me check on the next week. I'm on vacation now.
