### ISSUE TITLE
Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/6_12_0/bin/msbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.

### ISSUE THREAD

**Issue by Oshein123** [microsoft/azure-pipelines-tasks#13508]
Trying to run one xamarin code in visual studio app center.

logs :

"/Users/runner/work/1/s/iSmart.sln" (Rebuild target) (1) ->
"/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj" (Rebuild target) (11) ->
(CoreCompile target) -> 
  XFDependancyServiceStub.cs(8,44): error CS0246: The type or namespace name 'IXFDependencyService' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj]
  iSmart.ParkAndRide.Test/DeskControl.Test/BaseDeskControlTest.cs(32,23): error CS0246: The type or namespace name 'IXamarinFormsDevice' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj]
  iSmart.ParkAndRide.Test/DeskControl.Test/EnvironmentViewModelTest.cs(28,23): error CS0246: The type or namespace name 'IXamarinFormsDevice' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj]
  iSmart.ParkAndRide.Test/DeskControl.Test/LightingViewModelTest.cs(27,23): error CS0246: The type or namespace name 'IXamarinFormsDevice' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj]
  iSmart.ParkAndRide.Test/DeskControl.Test/OthersDeskControlViewModelTest.cs(28,23): error CS0246: The type or namespace name 'IXamarinFormsDevice' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj]
  iSmart.Test/NotificationSettingaViewModelTest.cs(17,16): error CS0122: 'NotificationSettingsViewModel' is inaccessible due to its protection level [/Users/runner/work/1/s/ISmart.UnitTest/ISmart.UnitTest.csproj]

    158 Warning(s)
    17 Error(s)

Time Elapsed 00:05:00.13
##[error]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/6_12_0/bin/msbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.

**Comment by sdobrodeev** [comment]
@Oshein123 Could you please provide minimum steps to reproduce - there may be a minimal test project that reproduces this behavior.

**Comment by hopegroup** [comment]
I am also having the same problem looking forward to help

**Comment by anatolybolshakov** [comment]
Hi @Oshein123 @hopegroup we can't reproduce this issue currently - could you please share some minimal project we could use to reproduce it on our side?

**Comment by anatolybolshakov** [comment]
Hi @Oshein123 @hopegroup is it still actual for you? Could you please provide some sample project - which we could use to reproduce? Since we can't reproduce it on our side currently

**Comment by thomaskellough** [comment]
I'm also having this same issue. I made sure to update AppCenter to the latest SDK/XCode version.
AppCenter SDK Version - Xamarin.iOS 14.6
AppCenter Xcode version - 12.3

My Local version for pushing into repository...
  Visual Studio - 8.8.4

  Xamarin.iOS
  Version: 14.6.0.15 (Visual Studio Community)
  Hash: 87a1b18d8
  Branch: d16-8
  Build date: 2020-11-16 21:39:41-0500

  Apple Developer Tools
  Xcode 12.3 (17715)
  Build 12C33


I'm also having the same issue for building android apps. Any solutions, yet?
