### ISSUE TITLE
SQLPackage Errors when using /AccessToken from Pipeline

### ISSUE THREAD

**Issue by dlm69** [microsoft/azure-pipelines-tasks#13510]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure SQL DacpacTask  

## Environment
- Server - Azure Pipelines 
- Agent - Hosted
    

## Issue Description

I am running a dacpac deployment uisng an access token (previous step) in the pipeline. The dacpac deployments seem to work where there are no post deployment scripts. The error SQL 72014 and 72045 seem to be a red herring as it only happens when using access token. 

Having tried locally to deploy the same dacpac I get the same error (using /at switch). Everything else being the same and deploying the same dacpac to the same database using SQL Admin user and password works as expected.

Any thoughts as to why an access token doesn't work in this instance. 

### Task logs

*** Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 8152, Level 16, State 30, Line 2 String or binary data would be truncated.
Error SQL72045: Script execution error.  The executed script:

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by 20shivangi** [comment]
@dlm69 Please attach the full debug logs here by setting variable system.debug to true in your pipeline/release.

**Comment by dlm69** [comment]
Apologies - We found the issue. It was not an access token error it was an offending sql script that was using SUSER_NAME and the colum was set to nvarchar(50). The service principal has more characters than that.

**Comment by 20shivangi** [comment]
Great!! closing it
