### ISSUE TITLE
Timeout parameters for ServiceFabricDeploy aren't documented

### ISSUE THREAD

**Issue by MartinDemberger** [microsoft/azure-pipelines-tasks#13512]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeploy 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

In task ServiceFabricDeploy the parameters for the timeouts aren't documented.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/service-fabric-deploy?view=azure-devops

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tejasd1990** [comment]
Hi @MartinDemberger , the document referred lists a number of timeout parameters like TimeoutSec, HealthCheckRetryTimeoutSec, UpgradeDomainTimeoutSec etc. Can you tell which specific parameters are you looking for?

**Comment by tejasd1990** [comment]
Hi @MartinDemberger , gentle ping!

**Comment by MartinDemberger** [comment]
Sorry for the late answer. A spam filter is a bad thing :-(

I don't know which parameter exactly I was looking for. I had timeouts on my publish very often and tried to reduce publish time and increase timeouts but don't know which one is the right one.

There are a lot of parameter which hasn't any description
* TimeoutSec
* HealthCheckRetryTimeoutSec
* HealthCheckWaitDurationSec
* HealthCheckStableDurationSec
* UpgradeDomainTimeoutSec
* UpgradeTimeoutSec

**Comment by tejasd1990** [comment]
@MartinDemberger , ok can you share the debug logs of the task where you are seeing the timeout? Also, which hosted agent are you using(windows/linux), and which version?

**Comment by tejasd1990** [comment]
Hi @MartinDemberger , ping!

**Comment by MartinDemberger** [comment]
Hi @tejasd1990,
I have changed a few of the timeout values and now it is running. The point is I don't know which of the parameter has which effect so it's only a guess.
It might help if there is a sentense for each parameter which describes it's effect (or a URL to another documentation).

I think there was a documentation for the parameters a few years ago but I wasn't able to find it.

**Comment by tejasd1990** [comment]
@MartinDemberger , the parameters are explained [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-parameters). Let me know if this helps. We will consider updating the task documentation.

**Comment by MartinDemberger** [comment]
Thank you very much. This was the information I was searching vor. Should I close this issue or should I keep it open to update the task documentation?

**Comment by tejasd1990** [comment]
Glad you are unblocked  . I will close this now, will inform if documentation is updated.
