### ISSUE TITLE
How to modify pipeline so that if any new dependency added to packaje.json it should create new cache for that one run.

### ISSUE THREAD

**Issue by harishpo** [microsoft/azure-pipelines-tasks#13522]
How to modify pipeline so that if any new dependency added to packaje.json it should create new cache for that one run.

**Comment by harishpo** [comment]
in my current project every week there will be some update in Packaje.json file, so at that time if my pipeline cache restores old cache , build will get faile.
So i am looking for solution how to create new cache every time when there is some change in package.json file .

**Comment by harishpo** [comment]
Please add this tag Area: PipelineCaching

**Comment by llehn** [comment]
Just add package.json as a key. Or, better yet, add yarn.lock or package-lock.json

````
          - task: Cache@2
            displayName: Load node modules from cache
            inputs:
              key: ' $(Agent.OS) | ${{service}} | project/yarn.lock'
              path: 'project/node_modules/'
