### ISSUE TITLE
Question: How to specify multiple so in nativeLibrariesPath

### ISSUE THREAD

**Issue by sakthiyuvaraj** [microsoft/azure-pipelines-tasks#13524]
Hi,

In the azure pipeline task AppCenterDistribute@3, I upload the native library symbols to app center to help symbolicate native crashes. Currently, we only upload ARM library symbols and want to specify ARM64 as well. 

How do I specify multiple paths in 'nativeLibrariesPath' parameter?

Thanks

**Comment by alexander-prozorov** [comment]
Hi @sakthiyuvaraj,

You can use a pattern with braces notation to specify multiple paths. Please try something this:

```
libraries/{ARM,ARM64}
```

**Comment by sakthiyuvaraj** [comment]
@alexander-prozorov, 

I tried:

nativeLibrariesPath: 'libpath\{ARM,ARM64}\ShipRelease\libControl.so'

But, it failed with

Cannot find any file based on C:\a\1\s\src\libpath\{ARM,ARM64}\ShipRelease\libControl.so 

Does braces notation work inside nativeLibrariesPath?

**Comment by alexander-prozorov** [comment]
Apparently, nobrace option is true by default, since no matchOptions are passed:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AppCenterDistributeV3/utils.ts#L158
