### ISSUE TITLE
All Azure App Service deploy Tasks Failing with "Not found resource file path"

### ISSUE THREAD

**Issue by lacomc** [microsoft/azure-pipelines-tasks#13537]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy (aka AzureRmWebAppDeploymentV4)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - account name: mseng
      - team project name: InternalTools
      - release definition names (task is in release, not build): SendVSFeedback2, VsfEmployeeWebsite, DevCom2
         - SendVSFeedback2 release numbers: Release-164, Release-165, Release-166, Release-167
        - VsfEmployeeWebsite release numbers: Release-169, Release-170, Release-171
        - DevCom2 release numbers: Release-125, Release-126

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:
        - Pool: Azure Pipelines
           - Agent: Azure Pipelines 17
           - Agent: Azure Pipelines 3
           - Agent: Azure Pipelines 2
           - Agent: Azure Pipelines 25
           - Agent: Azure Pipelines 20
       - Pool: VSEng-MicroBuildVS2019
           - Agent: DDMBLDW204

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

All of the Azure App Service deploy tasks in our release pipelines are failing since 9/10 at ~11:00am. We've tried changing the version of the task, but it doesn't help. Local deployment from Visual Studio works fine. The 3 builds associated with the releases all run as expected.

### Task logs
VsfEmployeeWebsite Logs
[tasklog_1.log](https://github.com/microsoft/azure-pipelines-tasks/files/5211837/tasklog_9.log)
[tasklog_2.log](https://github.com/microsoft/azure-pipelines-tasks/files/5211838/tasklog_9.1.log)
[tasklog_3.log](https://github.com/microsoft/azure-pipelines-tasks/files/5211839/tasklog_9.2.log)

SendVSFeedback2 Logs
[tasklog_4 (3).log](https://github.com/microsoft/azure-pipelines-tasks/files/5211841/tasklog_9.3.log)
[tasklog_5 (4).log](https://github.com/microsoft/azure-pipelines-tasks/files/5211844/tasklog_9.4.log)
[tasklog_6 (5).log](https://github.com/microsoft/azure-pipelines-tasks/files/5211845/tasklog_9.5.log)
[tasklog_7 (6).log](https://github.com/microsoft/azure-pipelines-tasks/files/5211847/tasklog_9.6.log)

DevCom2 Logs
[tasklog_8.log](https://github.com/microsoft/azure-pipelines-tasks/files/5211848/tasklog_8.log)
[tasklog_9 (1).log](https://github.com/microsoft/azure-pipelines-tasks/files/5211850/tasklog_8.1.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Error: Not found resource file path: E:\A\_work\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.175.1\node_modules\azure-pipelines-tasks-azure-arm-rest-v2\module.json

**Comment by lacomc** [comment]
This issue appears to have resolved itself over the weekend. We haven't made any changes to our pipelines. I'll leave the issue open in case there's more investigation that needs to be done, but the issue is resolved from a customer standpoint. Thanks!

**Comment by AmrutaKawade** [comment]
yes this was because of bad deployment which happened from our side. some files were missing in the package. we had identified this issue and released fix immediately. #13531
