### ISSUE TITLE
feat(HelmDeploy): allow overrideValues to be a set of key:value pair or array

### ISSUE THREAD

**Issue by damienwebdev** [microsoft/azure-pipelines-tasks#13530]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: `HelmDeploy`

## Environment
- Server -  or TFS on-premises?

Azure Pipelines

- Agent - Hosted or Private: 
Hosted

## Issue Description
As a developer, I'd really like it if my `overrideValues` path wasn't extremely long. It would be nice to be able to use an Array type, key: value, or a multi-line string. A simple CSV is extremely painful to look at and is highly error-prone.

**Comment by ds-ms** [comment]
That seems like a fair ask. 
cc: @shigupt202 could you check with our PMs about this? 

We have followed this convention in `KuberentesManifestV0` task. If you're aiming at `helm install` or `upgrade` alone, you could leverage the above mentioned task. A combination of `bake` + `deploy` action would achieve a similar deployment as to your `helm upgrade`. This task provides additional features as well like deployment strategy. You could check out this documentation for more details: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops
