### ISSUE TITLE
How this cache task will identify if package.json is updated ?  ? PipelineCaching

### ISSUE THREAD

**Issue by harishpo** [microsoft/azure-pipelines-tasks#13557]
How this cache task will identify if package.json is updated ?  ?

In my current project, packaje.json is getting updated very frequently, like at-least once in a week.

In this case, when i am adding cache task, and when it is restoring old packages from cache, build is getting failed.

I want to know is there any option were this cache task will check if any new update in package.json file and create new cache is there is any update to package.json file. 

Azure pipeline cache....

**Comment by harishpo** [comment]
Please add this tag to this issue  Area: PipelineCaching

**Comment by johnterickson** [comment]
Follow this example: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm

**Comment by johnterickson** [comment]
This is not a support forum. Please look at https://developercommunity.visualstudio.com/spaces/21/index.html
