### ISSUE TITLE
The PFX file you are trying to import requires either a different password or membership in an Active Directory principal to which it is protected

### ISSUE THREAD

**Issue by Purbasha** [microsoft/azure-pipelines-tasks#13553]
I am using Azure key vault task to download a certificate from KV and then install it in the build agent. I eventually want to execute some functional tests that need this certificate to authenticate.

This is my inline powershell after downloading the certificate in the previous task

param(
 [Parameter(Mandatory=$True)]
 [string]
 $firstpartypwd
)
$securePassword=ConvertTo-SecureString $firstpartypwd –asplaintext –force
$kvSecretBytes = [System.Convert]::FromBase64String("$(firstpartycert)")
$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($kvSecretBytes,'',[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
$protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $securePassword)
$pfxPath = [Environment]::GetFolderPath("Desktop") + "\<some cert>.pfx"
[System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)
Import-PfxCertificate -FilePath  $pfxPath -CertStoreLocation Cert:\LocalMachine\Root -Password $securePassword

I get this error:
The PFX file you are trying to import requires either a different password or membership in an Active Directory principal to which it is protected

Is any property missing on the downloaded certificate? Shall I change anything in the script to be able to install it on the hosted build agent?

**Comment by ds-ms** [comment]
Closing this stale issue. Feel free to reopen and tag me if the problem still persists. I'll help triaging it.
