### ISSUE TITLE
KubernetesManifest task failing with "Cannot find module 'typed-rest-client/HttpClient'"

### ISSUE THREAD

**Issue by yelob** [microsoft/azure-pipelines-tasks#13565]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesManifest

## Environment
- Server - Azure Pipelines
    
    I can provide the account name, team project name, build definition name/build number on request.

- Agent - Hosted Ubuntu-16.04 

## Issue Description

The task is failing with the following error:

##[error]Unhandled: Cannot find module 'typed-rest-client/HttpClient'

### Task logs

Debug task logs can be uploaded on request.

### Error logs

##[error]Unhandled: Cannot find module 'typed-rest-client/HttpClient'
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Cannot find module 'typed-rest-client/HttpClient'
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Cannot find module 'typed-rest-client/HttpClient'

**Comment by splitified** [comment]
Seems to be fixed by this #13564

**Comment by yelob** [comment]
ah, thank you! Searched a bunch and didn't see anything out there. 

I guess now I sit with broken pipelines until that fix is deployed :(

**Comment by splitified** [comment]
@yelob You can try this :
Dirty workaround :
```
 - pwsh: |
      npm install typed-rest-client --save
```

before using the failing task.
Found [here ](https://developercommunity.visualstudio.com/solutions/1187695/view.html)and tested, it works :p

**Comment by yelob** [comment]
I'll give a try, thanks!

**Comment by ds-ms** [comment]
This issue has been hotfixed.
