### ISSUE TITLE
Docker Task run container in V2

### ISSUE THREAD

**Issue by Vandersteen** [microsoft/azure-pipelines-tasks#13568]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Docker  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV1
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu 18.04

## Issue Description

[Include task name(s), screenshots and any other relevant details]

The `DockerV1` Task includes a docker run command, however, this one throws warnings like:

`2020-09-17T15:08:17.3821731Z (node:127969) Warning: Use Cipheriv for counter mode of aes-256-ctr`

On other tasks, it was simply upgrading to the newer version to resolve the issue. However, `DockerV2` does not provide a 'docker run' command. 

How could I solve this issue ?
I tried updating the agents, but this has no effect (on the V1 errors)

Is there a way to perform a `docker run` with the V2 package ?
Or will I have to resort to a bash script to do what I want to achieve without having warnings ?

**Comment by shigupt202** [comment]
@Vandersteen You can give run in the `command` input of DockerV2 task and remaining command parameters in the `arguments` input.
