### ISSUE TITLE
Publish test results is not working properly 

### ISSUE THREAD

**Issue by ashu16815** [microsoft/azure-pipelines-tasks#13578]
2020-09-19T10:24:17.3709790Z ##[warning]Failed to upload file Post_Del_APIs.postman_collection.xml to Blob Transfer exception with errorcode Unknown, exception message Microsoft.Azure.Storage.DataMovement.TransferException: The transfer failed.

We are getting above error for Publish Test Result task. PFA completed logs
[logsado.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5250910/logsado.txt)

Task definition : 
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/test-results.xml'
      inputs:
        testResultsFiles: '$(System.DefaultWorkingDirectory)/CICD_RM_Services/$(SERVICENAME)/test-results.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        failTaskOnFailedTests: true

**Comment by vivek425ster** [comment]
@ashu16815 Are you still able to reproduce this issue ? 
This seems to be connection issue. Might be an intermittent failure.
Which type of agent are you using in your pipeline?
If possible can you please share fiddler traces for more analysis ?

**Comment by suyash691** [comment]
@ashu16815 Can you please share the logs so that we can diagnose the issue?

**Comment by debben** [comment]
I'm getting the same error, but right after implementing an outbound firewall four our self-hosted agents. Our agents are able to talk to Azure Devops just fine for things like publish artifact steps, but publish build results appears to depend on other blob storage accounts and it's not documented what needs to be opened up.
