### ISSUE TITLE
azure devops nuget pack dependency version

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-tasks#13571]
Hi,

I'm not entirely convinced this is the right place to ask my question.

`    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack
        packagesToPack: '**\Database\**\*.nuspec;**\*.csproj;!**\*Host.csproj;!**\Tests\**;'
        packDestination: '$(build.ArtifactStagingDirectory)\nuget'
        includeReferencedProjects: true   
        versioningScheme: byEnvVar
        versionEnvVar: 'GitVersion.NuGetVersion'`

Looking at the logs Foo.nuspec creates a nupkg with a version like  1.1.0-feature0098.nupkg

Further in the logs another project Bar gets created with a version 1.1.0-feature0098.nupkg however this project has a dependency to Foo. 

From the logs it appears to be adding the dependency with a version 1.1.0-feature98.nupkg   "Note the dropped leading 0"

This causes problems as when consuming Foo it cannot find the dependency.

Any ideas what is causing this?

**Comment by omokoh** [comment]
Hey,

We would recommend you use nuget authenticate
See this link for more info
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops

**Comment by greengumby** [comment]
> Hey,
> 
> We would recommend you use nuget authenticate
> See this link for more info
> https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops

Hi,

How would that help?
