### ISSUE TITLE
DotNetCoreInstaller fails to install .NET 5.0 RC1

### ISSUE THREAD

**Issue by gitfool** [microsoft/azure-pipelines-tasks#13577]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreInstaller

## Environment
- Server - Azure Pipelines

  [gitfool/cake-docker/blob/master/.azure-pipelines.yml](https://github.com/gitfool/cake-docker/blob/master/.azure-pipelines.yml)

- Agent - Hosted:

  [gitfool/cake-docker/Pipelines/Build](https://dev.azure.com/gitfool/cake-docker/_build?definitionId=2)

## Issue Description

Build using DotNetCoreInstaller [fails to install](https://dev.azure.com/gitfool/cake-docker/_build/results?buildId=643&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=6d9aff2e-2021-571b-e4b1-a0f15b8c7b10&l=10) .NET 5.0 RC1. According to the [parameters of the task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreInstallerV1#parameters-of-the-task), I should be able to specify an exact preview version, which I did by specifying `5.0.100-rc.1.20452.10`.

FWIW, this works as expected with [GitHub Actions](https://github.com/gitfool/cake-docker/runs/1136922452?check_suite_focus=true#step:3:26) (using [actions/setup-dotnet](https://github.com/gitfool/cake-docker/blob/master/.github/workflows/build.yml#L27-L30)) and [GitLab CI](https://gitlab.com/gitfool/cake-docker/-/jobs/746545919#L124) (using [dotnet-install.sh](https://github.com/gitfool/cake-docker/blob/master/.gitlab-ci.yml#L25-L26)).

### Task logs

[logs_643.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5249113/logs_643.zip)

**Comment by tejasd1990** [comment]
Hi @gitfool , from the logs, I see you are using task version 1, can you use task version 2? This issue should not be faced with version 2.

**Comment by gitfool** [comment]
@tejasd1990 Thank you! Somehow I missed the switch to [`UseDotNetV2`](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/UseDotNetV2), which works as expected. 🎉
