### ISSUE TITLE
Zip Deploy doesn't overwrite all wwwroot contents as expected

### ISSUE THREAD

**Issue by diakonos** [microsoft/azure-pipelines-tasks#13585]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines

Account name: ok-devops
Team Project name: OK Grade
build definition name/build number:

- Agent - Hosted
    
Agent queue name: Azure Pipelines vs2017-win2016

## Issue Description

The contents of wwwroot are not being cleared as specified in the [Zip Deploy description](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4#zip-deploy).

> This option overwrites all existing contents in the wwwroot folder.

After deployment of our Node.js app, I noticed that old versions of our footer were being displayed. This was because I changed from using footer.js to footer/index.js, however imports of these files are identical. The footer.js file no longer exists in our repo, but it still exists in wwwroot. I used Azure's container SSH and navigated to the wwwroot folder and found that other old files that no longer exist in our project are still present. We are deploying using Azure Pipelines whenever we push to our Github repository. The pipeline logs show that Zip Deploy is being used, however it doesn't seem like all the contents of the wwwroot folder are being overwritten.

### Task logs

[deployLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5259540/deployLogs.zip)

### Error logs

N/A

**Comment by AmrutaKawade** [comment]
@diakonos I am not able to repro this issue. Are you still facing this issue?

**Comment by diakonos** [comment]
Yes, I am still experiencing this issue. It also happens when doing a zip deploy from VS Code with the Azure extension.

This logs if you're curious: [vscode_logs.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5455803/vscode_logs.txt)

**Comment by AmrutaKawade** [comment]
@diakonos I created zip which has structure like this
test
---1.txt
---2.txt

then I changed structure of this zip and again deployed
test
---src
------1.txt
---2.txt

Initial 1.txt from parent directory was removed with second deployment.
Can you share pipeline logs as well? set system.debug = true in variables and run pipeline.

**Comment by diakonos** [comment]
Here are the latest pipeline logs: [logs_49.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5456852/logs_49.zip)

**Comment by AmrutaKawade** [comment]
Zip deploy uses kudu apis to deploy package. there is open issue on kudu api for similar thing https://github.com/projectkudu/kudu/issues/3183. you can try Web deploy approach instead which will clean target directory before deployment

**Comment by diakonos** [comment]
Ok, I've commented on that issue and will look into an alternative deployment approach. Thanks!

**Comment by suwatch** [comment]
Thank for reporting.  Responded on https://github.com/projectkudu/kudu/issues/3183.

**Comment by qd-danh** [comment]
@diakonos wondering if you figured out an alternative deployment approach?  I'm seeing same behavior, where the files from the zip are not properly overwriting existing files in the wwwroot dir.

For me it's not about new and deleted files, it's not overwriting existing ones.

**Comment by diakonos** [comment]
> @diakonos wondering if you figured out an alternative deployment approach? I'm seeing same behavior, where the files from the zip are not properly overwriting existing files in the wwwroot dir.
> 
> For me it's not about new and deleted files, it's not overwriting existing ones.

Hi @qd-danh, yes I containerized my application with Docker and deploy Docker images now. Azure Pipelines builds the Docker image and pushes it to Azure Container Registry, and I deploy that on App Service.

**Comment by qd-danh** [comment]
> Hi @qd-danh, yes I containerized my application with Docker and deploy Docker images now. Azure Pipelines builds the Docker image and pushes it to Azure Container Registry, and I deploy that on App Service.

Thanks @diakonos. I may end up going the docker route as well. 

For anyone following along this thread, I **did** get it working by adding an application setting on the app service, thanks to [this thread](https://github.com/projectkudu/kudu/issues/2822#issuecomment-817757404) that wasn't exactly the same, but related enough.

`WEBSITE_RUN_FROM_PACKAGE = 1`

With that, all the files that are zip deployed using [azure/webapps-deploy](https://github.com/Azure/webapps-deploy) are properly overwritten / updated and the site reflects latest changes.
