### ISSUE TITLE
FileTransform task not replacing appsettings.json keys starting with "common"

### ISSUE THREAD

**Issue by ppanyukov** [microsoft/azure-pipelines-tasks#13587]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy, version 4

Probably this:

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines
- Agent - Hosted 
    
## Issue Description

We have `appsettings.json` like this:

```json
{
  "Common": {
    "Foo": {
      "Bar": {
        "Zoo": "REPLACEMENT_SHOULD_WORK_BUT_DOESNT"
      }
    }
  }
}
```

Then we have a var in Release defintion like this:

```
Common.Foo.Bar.Zoo = "some value"
```

When we run web app deploy, this value is not replaced.

When we change `Common` to something else, e.g. `TestCommon`, everything works. Must be something special about this `Common`.

---

EDIT: the docs here don't say anything about any special names like this. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic

**Comment by ppanyukov** [comment]
So, looking at the code... if this is the right place:

Any var starting with these will not get replaced:

```
'agent.', 'azure_http_user_agent', 'build.', 'common.', 'release.', 'system.', 'tf_'
```

https://github.com/microsoft/azure-pipelines-tasks/blob/6a1f5767d30aa2346589377ff4cbdabe199cef7c/Tasks/Common/webdeployment-common-v2/variableutility.ts#L4

These get filtered out later on here:

https://github.com/microsoft/azure-pipelines-tasks/blob/6a1f5767d30aa2346589377ff4cbdabe199cef7c/Tasks/Common/webdeployment-common-v2/jsonvariablesubstitutionutility.ts#L21

This is really unexpected. We certainly have `build.`, `release.` and `common` in our `appsettings.json` files.

**Comment by ppanyukov** [comment]
I can see why these are excluded but... This is not ideal. TBH this whole variable substitution is pretty scary as well. Someone can define a var group somewhere which by accident matches something in `appsettings.json` or some other json file.

In any case, these exceptions should be at least documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic

Other possible ways forward the way I see it:

* Remove these filter in json subst. Well, that's probably not gonna happen.
* Make v5 of the task which requires explicit list of var names for substitution + remove the filter. This will not only resolve the issue, but will make things much safer.

Any thoughts on these?

**Comment by jhitze** [comment]
I just ran into this after several hours of debugging. The ignored prefixes should at least be noted on the documentation.

**Comment by AmrutaKawade** [comment]
Document has been updated
