### ISSUE TITLE
Error adding secret in KeyVault via release pipeline

### ISSUE THREAD

**Issue by mayankmaheshwari18** [microsoft/azure-pipelines-tasks#13582]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information
I am trying to add a secret to KeyVault via release pipeline. When I set the variable as secret and run the release. It finds the value as null and throws error.

**Question, Bug, or Feature?**   Bug
*Type*: here

**Enter Task Name**: here  
AzureKeyVaultV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Alias: mamahesh
https://dev.azure.com/mseng/AzureDevOps/_release?definitionId=224&view=mine&_a=releases

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/16611785/93806806-5bc9bc00-fc67-11ea-8db9-5c2b8aae5527.png)
 PR for the script: https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps.ConfigChange/pullrequest/575086?_a=files
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tauhid621** [comment]
@mayankmaheshwari18 This does not look like an issue with AzureKeyVaultV1 task.

You are not assigning secret variable in right way.
Instead of "$CaptchaPrivateKey = $env:CaptchaPrivateKey", it should be $CaptchaPrivateKey = '$(CaptchaPrivateKey)'
