### ISSUE TITLE
azure-pipelines-tasks-azure-arm-rest-v2 - Part Name ".../OpenSSL License.txt" causes tfx create extension build break

### ISSUE THREAD

**Issue by trevors20** [microsoft/azure-pipelines-tasks#13608]
Question: Consuming "azure-pipelines-tasks-azure-arm-rest-v2" node library causes a build break when using "tfx create extension" to create azure task.

Would anyone know what I can do fix this?

Example:
tfx extension create --root <path>\_build --output-path <path>\_build --manifests <path>\_build\extension-manifest-bld.json --rev-version
TFS Cross Platform Command Line Interface v0.6.4
Copyright Microsoft Corporation
error: Error: Part Name '<path>/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/openssl/OpenSSL License.txt' is invalid. Please check the following:
error: 1. No whitespace or any of these characters: #^[]<>?
error: 2. Cannot end with a period.
error: 3. No percent-encoded / or \ characters. Additionally, % must be followed by two hex characters.

All I did was to add the line
    "azure-pipelines-tasks-azure-arm-rest-v2": "^1.0.4",

to my package.json file and I get the build break from tfx.
Thanks for any advice.

**Comment by trevors20** [comment]
I may have worked around this by renaming these files as part of my build steps before calling "tfx extension".  Instead of "OpenSSL License.txt" I rename the file to have an underscore "OpenSSL_License.txt".  Not pretty but, I believe it works.

**Comment by damccorm** [comment]
Per the readme, the common packages in this repo aren't supported for non-first party use - https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/README.md
