### ISSUE TITLE
Feature Request: Support Multiple Database Targets in Task SQL Database Deployment

### ISSUE THREAD

**Issue by kazoo60** [microsoft/azure-pipelines-tasks#13606]
This task works great for deploying to a single database.  It would be even more awesome if it could be enhanced to support deploying the same dacpac to multiple databases.  

I understand we could do this now using "Each" loops in YAML or a custom PS task but it would be great if this pre-built task could accept a comma delimited list of DB names - limiting the functionality to deploying to multiple targets on the same server.

Thanks for considering.

**Comment by aksm-ms** [comment]
@kazoo60 can you please send the exact task name used? there are 3 sql tasks available - SqlAzureDacpacDeploymentV1, SqlDacpacDeploymentOnMachineGroupV0, SqlServerDacpacDeployment

**Comment by kazoo60** [comment]
![image](https://user-images.githubusercontent.com/33428344/95101277-328d3f00-06ef-11eb-8e9a-64b9eea31e35.png)

I believe the tasks are:

SqlAzureDacpacDeploymentV1, and,
SqlServerDacpacDeployment

I am not sure where to access the technical names of the tasks but have attached a screen shot of how they appear in our release pipeline in VSTS.

Deploying to multiple databases on Azure is the higher priority for us.  We have about 45 client databases with identical schemas and so when we upgrade our solution, we would like to be able to push the same dacpac to all of them.

Thanks again for considering this request.

**Comment by StillBeta42** [comment]
Would like to reopen this issue for support to deploy a dacpac to multiple database names
