### ISSUE TITLE
HTTP ERROR 404 Not Found in Jenkins Queue Job

### ISSUE THREAD

**Issue by riteshmaddala** [microsoft/azure-pipelines-tasks#13616]
**Question, Bug, or Feature?**  
*Type*: Bug

## Environment
1. Azure DevOps
2. Jenkins is hosted Seperatly and we are accessing that using Load Balancer and Token-Based Authentication.
 
## Issue Description

When we try to Trigger Jenkins Job from Azure DevOps Pipeline, Job is getting triggered successfully but Azure DevOps Pipeline is hitting the wrong URL to get the Job ID.

Wrong URL which DevOps is hitting - /jenkins/login/queue/item/1711/api/json
**Correct URL Must be - /queue/item/1711/api/json**

### Error logs

`Jenkins job queued
Job progress tracking failed to read job queue
HttpResponse.statusCode=404
HttpResponse.statusMessage=Not Found
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/jenkins/login/queue/item/1711/api/json</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.27.v20200227</a><hr/>

</body>
</html>

##[error]Job progress tracking failed to read job queue
Finishing: Queue Jenkins job: DataIntegration_Perl_CodeReviewAutomation
`
For Reference and Tracking - https://developercommunity.visualstudio.com/content/problem/1202472/http-error-404-not-found-in-jenkins-queue-job.html

**Comment by sdobrodeev** [comment]
Hi @riteshmaddala. Unfortunately I could not reproduce the bug. Could you please provide the full log and build definition? This can be very useful for investigation.

**Comment by sdobrodeev** [comment]
@riteshmaddala This problem is still actual to you?

**Comment by sdobrodeev** [comment]
Closed due to inactivity. Please feel free to reopen it if the problem is still actual to you.

**Comment by nemrood** [comment]
Same problem here ! Please tell me what information you need in order to troubleshoot this. Thanks

**Comment by riteshmaddala** [comment]
> Same problem here ! Please tell me what information you need in order to troubleshoot this. Thanks

Hi,

I resolved this issue by updating the Jenkins configuration. Check the Load Balancing settings and make sure there is no extra endpoints which is not required.

For me it was https://hostname:port/**jenkins**

**/jenkins** was an extra parameter and I removed it and that resolved the issue.

Thanks

**Comment by anatolybolshakov** [comment]
@riteshmaddala thanks for info about this case 👍  please feel free to ask any further questions
