### ISSUE TITLE
PS not able connecting to Azure AD

### ISSUE THREAD

**Issue by eliassal** [microsoft/azure-pipelines-tasks#13627]
**Question**  
*Type*: I log to azure portal with my credentials, I am in global admins but when I issue  
` $AzureAdCred = Get-Credential`
`Connect-AzureAD -Credential $AzureAdCred`
I get 
```
Connect-AzureAD : One or more errors occurred.: unknown_user_type: Unknown User Type
At line:1 char:1
+ Connect-AzureAD -Credential $AzureAdCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

Connect-AzureAD : One or more errors occurred.
At line:1 char:1
+ Connect-AzureAD -Credential $AzureAdCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AggregateException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
```

**Comment by AmrutaKawade** [comment]
@eliassal Why do you want to connect to Azure Portal again. Azure Powershell Tasks already connects you to portal using service connection.

**Comment by eliassal** [comment]
I am confused with your response, I am trying to connect from powershell on my laptop not in the portal itself

**Comment by AmrutaKawade** [comment]
@eliassal This repo is for Azure DevOps Pipeline Tasks. 

To know more about Azure Devops Pipeline and Taks Refer : https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml 

If you are facing issues with [Poweshell Pipeline Task ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops) we can help you. 

For general powershell related issues you can create issue here https://github.com/Azure/azure-powershell
