### ISSUE TITLE
AndroidSigningV3 doesn't use latest available version of apksigner

### ISSUE THREAD

**Issue by Lubans** [microsoft/azure-pipelines-tasks#13637]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AndroidSigningV3

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AndroidSigningV3

## Environment
- Server - Azure Pipelines?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Corporate account

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **windows-latest**

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
AndroidSigningV3 task doesnt use latest available android build-tools.
In my case it used apksigner from 24.0.3 folder, however version 29.0.2 also available on same machine. 
As a result it was not possible to use some apksigner capabilities, for example --v3-signing-enabled option, which is not supported by older versions of apksigner.

With hardcoded apksigner path 
"apksignerLocation: 'C:/Program Files (x86)/Android/android-sdk/build-tools/29.0.2/apksigner.bat'", 
provided to AndroidSigningV3 task, it was possible to sign apk by using same commandline.

Most probably problem is that "findAndroidTool" function in androidsigning.ts returns first found subfolder in "build-tools" folder, but should return last found.

[Include task name(s), screenshots and any other relevant details]
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AndroidSigningV3/androidsigning.ts
![image](https://user-images.githubusercontent.com/3847417/94702833-e173f880-0346-11eb-97c0-8e3300db9aa4.png)
[SignerTaskLog.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5306432/SignerTaskLog.txt)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

![image](https://user-images.githubusercontent.com/3847417/94702833-e173f880-0346-11eb-97c0-8e3300db9aa4.png)

.................
2020-09-30T11:38:15.8488100Z 48628070 META-INF/proguard/androidx-annotations.pro (OK - compressed)
2020-09-30T11:38:15.8489280Z 48628294 META-INF/maven/com.google.guava/listenablefuture/pom.xml (OK - compressed)
2020-09-30T11:38:15.8490160Z 48629287 META-INF/maven/com.google.guava/listenablefuture/pom.properties (OK - compressed)
2020-09-30T11:38:15.8490530Z Verification succesful
2020-09-30T11:38:16.3047420Z [command]/Users/runner/Library/Android/sdk/build-tools/**24.0.3**/apksigner sign --ks /Users/runner/work/_temp/mobile-apk-sign-stag.keystore --ks-pass pass:*** --ks-key-alias corp dev --key-pass pass:*** --verbose --v3-signing-enabled true /Users/runner/work/1/a/droid/1601465616/com.myapp.apk
**2020-09-30T11:38:16.5614680Z Unsupported option: --v3-signing-enabled. See --help for supported options.**
2020-09-30T11:38:16.5730720Z ##[error]Error: The process '/Users/runner/Library/Android/sdk/build-tools/24.0.3/apksigner' failed with exit code 1
2020-09-30T11:38:16.5747800Z ##[section]Finishing: AndroidSigning

**Comment by carstenhag** [comment]
Hello there, @egor-bryzgalov can you please give us an eta on when this is released? I'm not seeing it atm. Thanks in advance!

**Comment by egor-bryzgalov** [comment]
Hi, @carstenhag 

It usually takes up to 3 weeks for sprint changes to be deployed. I'll keep you posted on the deployment status. Thank you!

**Comment by egor-bryzgalov** [comment]
Hi @carstenhag @Lubans 

The fix has been deployed. Please feel free to reopen this ticket if you have any issues.
