### ISSUE TITLE
[AzureRmWebAppDeploymentV4] Bad deployment and not seeing Function App Linux on list

### ISSUE THREAD

**Issue by BastienPerdriau** [microsoft/azure-pipelines-tasks#13649]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines or TFS on-premises? : Coporate account

- Agent - Hosted: windows-2019 / ubuntu-latest

## Issue Description

Using the AzureRmWebAppDeploymentV4 task, I have two strange behaviour: 
1. When selecting "App Service type" as "Function App on Linux", my function app created on Linux ASP is not available. The service connection is OK, I have all my others Web ou Function Apps (Linux or Windows) in the same RGs.
It's not that annoying, I can write it manually.
To be noted : When publishing from Visual Studio 2019, I can see and select my Function App after selecting "Azure Function App (Linux)"

2. The most annoying : When deploying my zip of my built project to my Function App, I noticed that it's not working and the Function App is somehow "transformed" to a Function App for Container.
From the task logs, I can see the following : 
`Trying to update App Service Configuration settings. Data: {"linuxFxVersion":"DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0","appCommandLine":""}`
And after the deployment, using the publishing Wizard of Visual Studio 2019, I can no longer see my Function App when selecting "Azure Function App (Linux)" but I can see it when selecting "Azure Function App Container".

**Comment by BastienPerdriau** [comment]
Hi there,

As a complement to my previous post, I noticed a strange behaviour when deploying to my Function App (Linux) with this task, it updates two properties on the JSON of my service (seen on resources.azure.com) :
- `kind` : from `functionapp,linux` to `functionapp,linux,container`
- Site property `LinuxFxVersion` value : from `dotnet|3.1` to `DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0`

For the latter, I tried to force set the property when deplying with the task parameter but I didn't work
Here is the configuration of the Azure DevOps task : 
![image](https://user-images.githubusercontent.com/5927529/95218430-8cc3f800-07f4-11eb-819b-4d990fa06e08.png)

Here is the log from the execution : 
```
2020-10-06T14:32:43.5453068Z Trying to update App Service Configuration settings. Data: {"linuxFxVersion":"DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0","appCommandLine":""}
2020-10-06T14:32:45.6896112Z Updated App Service Configuration settings.
2020-10-06T14:32:45.6904955Z Trying to update App Service Configuration settings. Data: {"linuxFxVersion:":"dotnet|3.1"}
2020-10-06T14:32:47.9279020Z Updated App Service Configuration settings.
```

**Comment by AmrutaKawade** [comment]
@BastienPerdriau for second issue check if runtime stack is selected. If yes try removing that value.
![image](https://user-images.githubusercontent.com/65217380/95329413-856c1f80-08c4-11eb-8726-a00dcfc16224.png)

**Comment by BastienPerdriau** [comment]
It seems to work better now. Not sure if it's related to removing that value (I had few other errors so I made some changes).
But it seems that the deployment task is no longer trying to force this setting : `{"linuxFxVersion":"DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0","appCommandLine":""}`.

**Comment by AmrutaKawade** [comment]
yes its because of runtimestack. we have observed similar issue before  #13427 we will investigate this further. we will track this issue with 13427. closing this issue.

**Comment by BastienPerdriau** [comment]
No problem for closing.

If I can suggest to take a look to the first issue I spoke about the missing function apps when selecting "Function App (Linux)" in the UI.
