### ISSUE TITLE
Need option for npmAuthenticate task to save token to environment variable

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/azure-pipelines-tasks#13646]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: npmAuthenticate@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I've been hitting a lot of issues with the npmAuthenticate task, where for security reasons the token should not be saved to disk. It would be useful to have a parameter to specify the token to be stored in an environment variable.

This would get around a whole host of issues regarding npm auth. For example, Rush, built by Sharepoint team requires the .npmrc files for publishing packages to be separate from the one used to install. The publish version must be named ".npmrc-publish", which fails in the npmAuthenticate task because there's a validation check that determines if the extension is exactly ".npmrc". As a workaround, I tried authenticating a temporary .npmrc file then renaming it. However, I've run into other issues such as when the CI system updates package versions before publishing, it commits the changes back to git -- sometimes the tokens added to .npmrc files get committed to the git repository which is dangerous and always a risk when there are tasks running in the pipeline that you may not directly control.

The preferred way to deal with .npmrc files is to store the authentication token in an environment variable, then reference that variable in the .npmrc. Having such an option would allow a wide range of more secure options for build pipelines.

**Comment by octogonz** [comment]
> The publish version must be named ".npmrc-publish", which fails in the npmAuthenticate task because there's a validation check that determines if the extension is exactly ".npmrc".

This problem is tracked by: https://github.com/microsoft/azure-pipelines-tasks/issues/11484
