### ISSUE TITLE
DotNetCoreCLI takes too long for some builds

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/azure-pipelines-tasks#13656]
ℹ We have been forwarded here from https://github.com/actions/virtual-environments/issues/1733

## Required Information

**Type**: Bug
**Name**: DotNetCoreCLI

## Environment
Azure Pipelies
For account name, team project name, build definition name/build number, see links in issue description.

## Issue Description

We are experiencing some random extra build times in DotNetCoreCLI@2:

Here I have two example builds that shows the problem:
- [This build](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=40898&view=logs&j=478d6457-175a-5a6d-2808-da0dbe793335&t=5647d006-93ac-5ad2-cb47-052317d432cb): unittest takes less than 1 minute.
- [This build](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=40887&view=logs&j=478d6457-175a-5a6d-2808-da0dbe793335&t=5647d006-93ac-5ad2-cb47-052317d432cb): unittest takes 30 minutes

Between this two commits there are no changes on that c# project, therefore if we are not wrong, something in the cloud must be going on.

### Error logs

None, the process seems to hang for a very long time, sometimes 30 min, sometim ~20min ....

**Comment by FrancescElies** [comment]
ℹ We have split the build step and the unittest step in two separate jobs.
Now we get timeouts all the time on the unittest, [example build](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=40948&view=logs&j=3428d4e5-30f9-5552-9c6f-c1033493e7bf&t=00d0dcbc-ee8c-5748-96b3-d027e915ef3d)

I hope this info helps, do you have any news on your side?

**Comment by FrancescElies** [comment]
Here [a build](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=40965&view=logs&j=014ad21f-16a3-5419-72e0-8239cd277932&t=46925b0f-877f-5ca8-0436-e8ac5276d2ed) with dotnet verbosity level diagnostic enabled.

**Comment by FrancescElies** [comment]
@damccorm are we sure this is an enhancement?

A step that used to take 49 seconds takes now 30 minutes, we will gladly work together to sort out this issue but I believe we need a input from your side to know if this is problem on our side or something is going on on the cloud.

**Comment by FrancescElies** [comment]
`¯\_(ツ)_/¯` Might be related to https://github.com/dotnet/sdk/issues/12281, https://github.com/dotnet/sdk/issues/1228, https://github.com/dotnet/sdk/issues/12445

**Comment by FrancescElies** [comment]
The problem seems to be related to the `dotnet test` command. Adding `--no-build` and explicitely building it beforehand brings down the job build time from ~20 min to ~5 min.

Workaround:
```diff
+  - task: DotNetCoreCLI@2
+    displayName: build 
+    inputs:
+      command: build
+      projects: 'myproject.csproj'
+      arguments: --configuration $(buildConfig) --verbosity $(dotnetVerbosity)
+
   - task: DotNetCoreCLI@2
     displayName: UnitTests 
     inputs:
       command: test
       projects: 'myproject.csproj'
-      arguments: --configuration $(buildConfig) --verbosity $(dotnetVerbosity)
+      arguments: --configuration $(buildConfig) --verbosity $(dotnetVerbosity) --no-build
       testRunTitle: UnitTests 

```

**Comment by anuragc617** [comment]
Adding @phanikmmsft to take a look at dotnet test

**Comment by FrancescElies** [comment]
@anuragc617 @phanikmmsft  any news on this?

**Comment by FrancescElies** [comment]
Since there is a workaround, I don't think anybody cares about this. Closing.
