### ISSUE TITLE
NetCore 3.1 Build Started Failing NuGet Package Restore All Of Sudden

### ISSUE THREAD

**Issue by vulegend** [microsoft/azure-pipelines-tasks#13659]
AzureDevops build pipeline started failing all of sudden at around 7 PM CEST today (10/5/2020) on all .net core publish tasks with the same reason : 

##[error]Packages failed to restore

It seems like it's failing to restore nuget packages. I've tried multiple pipelines as i thought it was somehow related to the new code (i did install some new packages) but even the projects that didn't have anything changed in weeks fail with the same issue.

**Comment by vulegend** [comment]
I assume it's related with the current artifact service issues : 

https://status.dev.azure.com/_event/208052886

**Comment by bishal-pdMSFT** [comment]
@vulegend the artifact issue referenced above seems to have been resolved. Has that resolved your issue as well?
If no, can you please provide more details:
1. Debug logs for the run
2. Pipeline details
3. Any details of nuget feed you are using

**Comment by anuragc617** [comment]
@vulegend is the issue resolved? If not, can you provide the details requested.

**Comment by anuragc617** [comment]
closing this as the Artifact issue has been resolved and the customers is not responding. @vulegend feel free to ping if you still face this issue.
