### ISSUE TITLE
Using existing tasks in custom created one

### ISSUE THREAD

**Issue by Talha-B** [microsoft/azure-pipelines-tasks#13652]
Hi,

I have a long winded build process consisting of many jobs and I was thinking to create a custom task which encapsulates all the different steps and to publish it as a private task to the marketplace for use within our organisation. With the idea being that this one task can be re-used across different projects, taking in the required input as params.

Is there any way to call some of the existing tasks provided by Microsoft as part of my new custom task? They don't seem to be published to the npm registry, so I'm assuming not?

Is there any way to accomplish what I want, without copying the source code from this repo, of each of the tasks that I require?

**Comment by egor-bryzgalov** [comment]
Hi, @Talha-B 
Unfortunately, what you want isn't directly supported.
You can either copy source code of tasks you need or use [yaml templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops) to make your pipeline definition more convenient to reuse.

**Comment by Talha-B** [comment]
Ah, I suspected as much.

Thanks,
Talha
