### ISSUE TITLE
How to authenticate an azure-sdk-for-node based workload against a service connection?

### ISSUE THREAD

**Issue by cveld** [microsoft/azure-pipelines-tasks#13651]
*Type*: Question

## Environment
- Server - Azure Pipelines 
- Agent - Hosted

## Issue Description

Is there a way to authenticate the azure sdk for node with an Azure service connection?
I have seen that there is an npm authenticate task. Is there something comparable?

I also raised a related ticket with the azure sdk for node repo:
https://github.com/Azure/azure-sdk-for-node/issues/5199

https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md
tells me this is the way to authenticate with a service principal:
```
let creds = new msRestNodeAuth.ApplicationTokenCredentials(process.env['CLIENT_ID'], process.env['DOMAIN'], process.env['APPLICATION_SECRET']);
```

Maybe there is a way to get an access token from the az cli or azure-powershell context?

**Comment by damccorm** [comment]
Hey @cveld - this looks like an issue with the service more generally, not with a specific task. This repo mostly holds issues with specific tasks, please file general issues at https://developercommunity.visualstudio.com/spaces/21/index.html - that way it will get the right eyes on it
