### ISSUE TITLE
Copy to $web container not working

### ISSUE THREAD

**Issue by bcouavoux** [microsoft/azure-pipelines-tasks#13669]
# Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopy@4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4

## Environment
- Server - Azure Pipelines 
    
- Agent - Private: 
Windows Server 2019
Agent Version 2.174.3

## Issue Description

When using the AzureFileCopy version 4, we cant copy a file to a container with '$' in his name. $web in our case. 
Pipeline :

    - task: AzureFileCopy@4
      inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)/Publish'
        azureSubscription: 'XXXXXX-WWWW-ZZZZZZ'
        Destination: 'AzureBlob'
        storage: 'testcontainer'
        ContainerName: '$web'

### Task logs

##[error]Container name '`$web' is invalid. Valid names start and end with a lower case letter or a number and has in between a lower case letter, number or dash with no consecutive dashes and is 3 through 63 characters long.

**Comment by AmrutaKawade** [comment]
This is the requirement from Azure Blob Storage only. Refer this https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names

**Comment by AmrutaKawade** [comment]
@bcouavoux I tried with version 4.175.3 and its not reproducible any more. Can you please confirm?

**Comment by bcouavoux** [comment]
Same problem with the 4.175.3 version :

![image](https://user-images.githubusercontent.com/52322253/96716459-5914d080-13a5-11eb-9437-b8987c465e9f.png)

**Comment by AmrutaKawade** [comment]
Sorry ignore my first comment. $web is valid name. I tried with $web container name only. But I checked on Hosted Agent which has latest Az and Azure RM modules. 

As you are using Private Agent Can you try installing latest AzureRM or Az module
https://www.powershellgallery.com/packages/AzureRM/6.13.1
https://www.powershellgallery.com/packages/Az/4.8.0

**Comment by bcouavoux** [comment]
Ha yes, the problem come from there .. We updated our Az module and that works well now.
Thanks, you can close the ticket.

**Comment by AmrutaKawade** [comment]
Thanks for confirming
