### ISSUE TITLE
support latest az module in Azure Powershell task

### ISSUE THREAD

**Issue by lidong6** [microsoft/azure-pipelines-tasks#13675]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: support latest az module in Azure Powershell task  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines, 
 account name: msasg
 team project name: Bing_Geospatial

- Agent - Hosted: Hosted VS2017 Queue
     

## Issue Description

Azure Powershell Task 5.0 only support az module 3.1.0, the latest az module is 4.7 + already.

**Comment by 20shivangi** [comment]
@lidong6 Hosted agent VS2017 already supports latest az module version i.e. 4.7.0 . Can you please check again. I am attaching a snippet of the same.

![image](https://user-images.githubusercontent.com/45754171/95553422-304b1d80-0a2c-11eb-9cbd-c9db0c9bae7c.png)

**Comment by 20shivangi** [comment]
@lidong6 Any update here ?

**Comment by 20shivangi** [comment]
Closing this issue since there is no response for last one week, feel free to reopen if you are facing. We will be happy to help you out.
