### ISSUE TITLE
Azure PowerShell script - encoding output problem

### ISSUE THREAD

**Issue by SebastianClaesson** [microsoft/azure-pipelines-tasks#13679]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure PowerShell script (part of a Azure DevOps Release Pipeline)
Same issue with running PowerShell or PowerShell Core.

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account name: itdigi
Team project name: infra-and-operations
It's a part of a release pipeline called "Azure Budgets - Test"

- Agent - Hosted or Private: 
    Hosted agent
    - If using Hosted agent, provide agent queue name:
Hosted agent name: WIN-H6MO5BKS61H

## Issue Description
The output from the -whatif switch on new-az<type>deployment is having encoding display problems in the logs.

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/34689432/95447861-b733c380-0962-11eb-853f-2d20be01c04f.png)

**Comment by AmrutaKawade** [comment]
@SebastianClaesson Are you facing this issue when running from powershell on your machine as well?

**Comment by AmrutaKawade** [comment]
This issue is not reproducible anymore. I will close this issue. Feel free to reopen if it still persists

![tempsnip](https://user-images.githubusercontent.com/65217380/97987164-d78b5c80-1e00-11eb-87fe-8110968581a5.png)
