### ISSUE TITLE
AzureWebAppContainerV1: AppSettings updated after App Service restart

### ISSUE THREAD

**Issue by sergeyzwezdin** [microsoft/azure-pipelines-tasks#13673]
*Type*: Bug
**Enter Task Name**: AzureWebAppContainerV1  

list here (V# not needed):  AzureWebAppContainer
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

While deploying test container to Azure App Services, I noticed that the service restarted right after deployment and then app settings changed. It seems that's wrong because of in this case App Service sometimes fails with error that Docker credentials are not found.

![image](https://user-images.githubusercontent.com/800755/95351443-a9d2f680-08da-11eb-946a-46dd2981607f.png)

What if put these lines before calling `deployWebAppImage`?

https://github.com/microsoft/azure-pipelines-tasks/blob/46cca412451ac4418d6332114fca8ef8c3095de1/Tasks/AzureWebAppContainerV1/azurermwebappdeploymentprovider.ts#L42-L45

**Comment by AmrutaKawade** [comment]
This is fixed and will be deployed within 2 weeks
