### ISSUE TITLE
Xamarin.iOS C# 8 not available

### ISSUE THREAD

**Issue by otebos** [microsoft/azure-pipelines-tasks#13672]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: XamariniOS  

## Environment
- Server - Azure Pipelines 
    - account name : kvaernertfs
    - team project name : WeCheck
    - build definition name/build number: Mobile.iOS.Multiple_CD / #20201006.2

- Agent - Hosted 
    - agent queue name: 
Image: macOS-10.15
Agent: Azure Pipelines 5
Agent machine name: 'Mac-1601983263405'

## Issue Description

Build fails with error
"error CS8370: Feature 'static local functions' is not available in C# 7.3. Please use language version 8.0 or greater."
whenever I use C# 8 feature.

What is strange - app is Xamarin.Forms and C# 8 usage is in common project but Android pipeline builds successfully .
Common project was test in .NET Standard 2.0 and 2.1 with the same errors.

What I found out is iOS uses Mono for compilation but Android uses regular MSBuild.
I installed .NET Core 3 SDK in iOS pipeline but I don't know how to tell Xamarin.iOS task to use it instead of Mono.
From googling it looks like Mono 6.12 do support C# 8...

There is parameter for XamariniOS task buildToolLocation but I don't know how to set it so it would use MSBuild like Android
build does.

## Pipeline
- job: iOSTest
  pool:
    vmImage: 'macOS-10.15'
    demands:
    - xcode
    - Xamarin.iOS

steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      includePreviewVersions: true

  - script: |
      sudo gem install fastlane
      echo 'Selecting Mono version...'
      /bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_0"
      /bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_12.app;sudo xcode-select --switch /Applications/Xcode_12.app/Contents/Developer"
    displayName: 'Install Mono .NET Runtime 6.12.0'
    enabled: true

- task: XamariniOS@2
    inputs:
      solutionFile: '**/*LeProject.iOS.csproj'
      configuration: '$(BuildConfiguration)'
      clean: true
      runNugetRestore: true
      buildForSimulator: false
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

### Error logs
 Using shared compilation with compiler from directory: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Roslyn
Controls/Views/LeView.xaml.cs(152,13): error CS8370: Feature 'static local functions' is not available in C# 7.3. Please use language version 8.0 or greater. [/Users/runner/work/1/s/LeDirectory/LeSharedProject.csproj]

##[error]Xamarin.iOS task failed with error Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.
Finishing: XamariniOS

**Comment by egor-bryzgalov** [comment]
Hi, @otebos 

Could you please try to add the following parameter to all project files and let us know whether it helps?
```
<PropertyGroup>
   <LangVersion>8.0</LangVersion>
</PropertyGroup>
```
or
```
<PropertyGroup>
   <LangVersion>latest</LangVersion>
</PropertyGroup>
```
We're looking forward to hearing from you! Thank you!

**Comment by otebos** [comment]
I forgot to mention - I stared with latest then changed to 8.0
In both cases issue is the same

**Comment by max-zaytsev** [comment]
Hi @otebos,
Did you upgrade all projects to use C#8.0? I wasn't able to repro this issue using `<LangVersion>8.0</LangVersion>`

Could you please provide a minimal reproducible project, as that would make it easier to find the root cause?

Thank you!

**Comment by otebos** [comment]
Hi,
yes all projects are using C# 8 via <LangVersion>8.0</LangVersion>
I also tried with default, newest and 9.0

I'll try to recreate issue on sample project

**Comment by max-zaytsev** [comment]
Hi @otebos, Do you still have problems with this? Have you recreated the issue on the sample project?

**Comment by max-zaytsev** [comment]
Hi @otebos, Is it still relevant for you? Have you had a chance to create a reproducible project for us?
