### ISSUE TITLE
Support xcode 12.0 on Hosted agent

### ISSUE THREAD

**Issue by psredzinski** [microsoft/azure-pipelines-tasks#13677]
**Feature**  
*Type*: Update

**Support xcode 12.0 on Agent Pools**

We've started using xcode 12.0 on our local development machines, but builds fail on Azure Pipeline, because it has only xcode 11.3.1 available.

![Zrzut ekranu 2020-10-8 o 09 11 35](https://user-images.githubusercontent.com/23390884/95426505-4b436200-0946-11eb-8401-9207c985f390.png)

When can we expect an update?

**Comment by eddy93** [comment]
yes please

**Comment by fichek** [comment]
It's been 22 days since Xcode 12 GM and 10 days since Xcode 12.0.1, any ETA on this?

**Comment by mathieumg** [comment]
Just managed to build using Xcode 12, make sure you are on 10.15 and you can specify the path:

<img width="1014" alt="Screen Shot 2020-10-14 at 2 44 35 PM" src="https://user-images.githubusercontent.com/1624812/96031874-ebf4be80-0e2b-11eb-9530-53eae1cae9c7.png">
<img width="1024" alt="Screen Shot 2020-10-14 at 2 44 46 PM" src="https://user-images.githubusercontent.com/1624812/96031876-ec8d5500-0e2b-11eb-9739-1d5af3cd83a5.png">

**Comment by fichek** [comment]
Just found the same thing along with the announcement that default Xcode will be changed to 12 on October 20th https://github.com/actions/virtual-environments/issues/1712

**Comment by fichek** [comment]
GitHub virtual environments which the pipelines use is going to default to Xcode 12 from October 20th https://github.com/actions/virtual-environments/issues/1712 but yeah as @mathieumg mentioned if you can specify a path manually even though Xcode 12 is not offered from the dropdown. Apparently 12.2 beta and 12.0 beta 6 are also installed https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

**Comment by max-zaytsev** [comment]
"Xcode 12" option is now available in xcodeVersion input:

![image](https://user-images.githubusercontent.com/16704239/113575324-890e0400-95d2-11eb-9cf8-9f1e791c2afe.png)
