### ISSUE TITLE
DownloadPipelineArtifacts does nothing for 10+ minutes then times out

### ISSUE THREAD

**Issue by Axemasta** [microsoft/azure-pipelines-tasks#13681]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Download Pipeline Artifact _(DownloadPipelineArtifact@2)_

## Environment

| Platform          | Azure Pipelines          |
|-------------------|--------------------------|
| Account Name      | a.duffell@senso.cloud    |
| Team Project Name | Senso.Client.Mobile      |
| Build Definition  | #20201008.4              |
| VM Image          | macos-latest             |
| Agent Name        | #was unable to find this |

## Issue Description

I was running the CI for my xamarin forms application, the pipeline has 2 stages:

- Stage 1: Run Tests, Build & Sign Apps, Publish Artifacts
- Stage 2: Download Artifacts, Publish To App Center For Alpha Release

Stage 1 completed successfully and Stage 2 begun. The iOS release task waited for around 15 minutes on the `DownloadPipelineArtifacts` task. Eventually the task timed out and it output the following error:
`##[error]The HTTP request timed out after 00:00:30.`

The pipeline history claimed the task took 1m 1s, but as the people sitting watching the pipeline run whilst eating my lunch I can confirm it took significantly longer. 
![The pipeline job](https://user-images.githubusercontent.com/33064621/95455290-8a34e000-0965-11eb-98da-f0c6a4d38bd2.png)

The task started and displayed the following:
```
Starting: DownloadPipelineArtifact
==============================================================================
Task         : Download Pipeline Artifacts
Description  : Download build and pipeline artifacts
Version      : 2.3.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
==============================================================================
Download from the specified build: #2302
Download artifact to: /Users/runner/work/1
```

It never progressed past this point until displaying the error, below is a screenshot of the full task output:
![Full Task Output](https://user-images.githubusercontent.com/33064621/95455452-cff1a880-0965-11eb-8ed5-5f2211fda26f.png)

once the task had timedout the 2nd task ran and released the android app. I simply reran the failed task and it succeeded. The pipeline artifact absolutely exists and I haven't encountered the issue on subsequent runs.

Thought I'd report because something definitely frozen somewhere in the pipeline and the system hasn't correctly reported this.

**Comment by MattGal** [comment]
+1, seen here: https://dev.azure.com/dnceng/public/_build/results?buildId=910780&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b

@zachariahcox FYI.
