### ISSUE TITLE
Test results folder Parameter stores incorrect Path

### ISSUE THREAD

**Issue by smsnyder-pai** [microsoft/azure-pipelines-tasks#13690]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Test Results Folder Parameter stores incorrect path  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Vistual Studio Test Task (UI version) has a variable called "Test Results Folder".  No matter the value (full or relative path) entered, the value stored in current working directory is wrong - it merges the name of two directories in its path into one incorrect directory.  For example, when this value is used: $(Common.TestResultsDirectory)\TestResults
it is stored as `F:\SOA-01_work\11\TestResults\TestResults`
when it should be: `F:\SOA-01\_work\11\TestResults\TestResults`

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

We get the following error when writing and then reading file from current dir in code: System.IO.DirectoryNotFoundException: Could not find a part of the path `F:\SOA-01_work\11\TestResults\...`

**Comment by smsnyder-pai** [comment]
There seems to be an issue when the backslash is immediately followed by an underscore in the filepath.

**Comment by hvinett** [comment]
hey @smsnyder-pai, I am unable to repro, for me it is working fine. when i gave 
TestReustsDirectory : $(Common.TestResultsDirectory)\TestResults
I am getting the following path as expected
```D:\vsts-agent-win-x64-2.166.4\_work\2\TestResults\TestResults\havineet_VINEETHL_2020-10-22_08_41_04.trx```
can you provide the vstest version and agent vesrion that you are using. If possible can you create a sample project and repro it and provide the build link here.

**Comment by hvinett** [comment]
hey @smsnyder-pai , closing this issue. If you still facing the problem, please feel free to reopen the issue

**Comment by nishantms** [comment]
Closing the issue, as didnt hear back from the customer
