### ISSUE TITLE
Don't bump UsePythonVersion default to 3.9 yet?

### ISSUE THREAD

**Issue by ihnorton** [microsoft/azure-pipelines-tasks#13708]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UsePythonVersion  

## Environment
- Server - Azure Pipelines or TFS on-premises? AZP
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: `TileDB-Inc`, [6609](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=6609&view=logs&j=ddb22062-4ff8-527b-ab2b-d0df282bef17&t=1358f115-abf2-540d-2238-48c2e2ecaabb&l=25)

## Issue Description

`UsePythonVersion` appears to now default to Python 3.9 in (at least) the linux images with un-pinned `versionSpec: '3.x'`. Many important packages do not have binary wheels available for Python 3.9 yet, for any platform (eg [numpy](https://pypi.org/project/numpy/#files), [scipy](https://pypi.org/project/scipy/#files), [cython](https://pypi.org/project/Cython/#files), [tensorflow](https://pypi.org/project/tensorflow/#files), [pandas](https://pypi.org/project/pandas/#files)).

Perhaps everyone *should* be pinning the `UsePythonVersion`, but bumping so quickly like this means that any CI setups using un-pinned python versions are going to do build-from-source for those dependencies above -- and will often fail due to missing build requirements.

Suggest that the default bump for `UsePythonVersion` to 3.9 should wait 1-2 more weeks while the ecosystem updates and stabilizes, and let people opt-in to 3.9 for now.

x-ref: https://github.com/actions/virtual-environments/issues/1740#issuecomment-708452336

**Comment by damccorm** [comment]
Hey @ihnorton - this is controlled by the image, not the task itself. I'm going to close here since https://github.com/actions/virtual-environments/issues/1740#issuecomment-708452336 is a more correct place for tracking this kind of issue
