### ISSUE TITLE
Option to disable image list command

### ISSUE THREAD

**Issue by efeerdogru** [microsoft/azure-pipelines-tasks#13701]
https://github.com/microsoft/azure-pipelines-tasks/blob/329d8c95657ec05371fcc3e3fd9b376a5c8c9903/Tasks/DockerV2/dockerpush.ts#L59

Hi,

We have a big repo, and every time this task runs, all images listed and logged.

A way to disable this printing would be very useful.

**Comment by ds-ms** [comment]
@anraghun could you take a look

**Comment by anraghun** [comment]
@efeerdogru This is under consideration but we'll wait for more requests for this.

**Comment by ds-ms** [comment]
Closing this stale issue, given that there aren't any other requests for this feature.
