### ISSUE TITLE
Azure DevOps Delete Files Error -  Failed find: ENOENT: no such file or directory, lstat 'C:\inetpub\wwwroot\xxxxx\App_Data\mediaIndexing\xxxxx.pdf'

### ISSUE THREAD

**Issue by nickgsoft** [microsoft/azure-pipelines-tasks#13716]
I am getting repeated errors lately on Delete Files task that it support to delete in few directory, but instead it throws error as below. By the way the file that it is complaining has no connection between what is specified in the "Delete Files" task. 

Any idea?

`2020-10-15T17:29:55.9455564Z ##[section]Starting: Pre-Deploy Cleanup
2020-10-15T17:29:55.9653790Z ==============================================================================
2020-10-15T17:29:55.9654026Z Task         : Delete files
2020-10-15T17:29:55.9654052Z Description  : Delete folders, or files matching a pattern
2020-10-15T17:29:55.9654091Z Version      : 1.176.0
2020-10-15T17:29:55.9654115Z Author       : Microsoft Corporation
2020-10-15T17:29:55.9654140Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/delete-files
2020-10-15T17:29:55.9654164Z ==============================================================================
2020-10-15T17:30:10.6674985Z ##[error]Unhandled: Failed find: ENOENT: no such file or directory, lstat 'C:\inetpub\wwwroot\xxxxx\App_Data\mediaIndexing\xxxxxx.pdf'
2020-10-15T17:30:10.8133334Z ##[section]Finishing: Pre-Deploy Cleanup
`

**Comment by nickgsoft** [comment]
Is there any way, i can enable the Audit log for this task to know what exactly it is deleting?

**Comment by anatolybolshakov** [comment]
Hi @nickgsoft could you please provide pattern which you use for 'Contents' input of Delete Files task and 'SourceFolder' input value?

**Comment by nickgsoft** [comment]
@anatolybolshakov 
![image](https://user-images.githubusercontent.com/12518671/96498926-5170f280-1212-11eb-89ea-bbf8423b1b33.png)
Attached is the content items.

**Comment by anatolybolshakov** [comment]
@nickgsoft thanks! I reproduced this issue as well. As a workaround - could you please try to remove brackets for excluded paths and move it to the end of patterns list?

**Comment by anatolybolshakov** [comment]
@nickgsoft btw the order of patterns mentioned also in docs - please see it [here](https://docs.microsoft.com/ru-ru/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops)

**Comment by nickgsoft** [comment]
@anatolybolshakov Thanks for the udpdate and i tried that sequencing approach as well. but no luck. How can i add Audit on what it is trying to process'? Log do not have enough details.

**Comment by anatolybolshakov** [comment]
@nickgsoft you can set 'System.Debug' variable to 'true' ([here](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#run-a-release-in-debug-mode) are some docs describing it) - to enable debug mode for classic editor or use 'Enable system diagnostics' flag to enable debug mode when running a yaml pipeline - it will show you how many files match every pattern in the list

**Comment by anatolybolshakov** [comment]
Hi @nickgsoft is it still actual for you? Did the ordering help?

**Comment by nickgsoft** [comment]
@anatolybolshakov  i am looking at details using system.debug helper and finding the cleanup job is cleaning stuff from the directory that is not mentioned in the content. looks little scary. i did applied the exclude condition at the end of the list by the way. so not sure what else to try.

**Comment by anatolybolshakov** [comment]
@nickgsoft could you please share your current Contents input value and directories which are being cleaned up, but not mentioned in Contents pattern?

**Comment by anatolybolshakov** [comment]
Hi @nickgsoft is it still actual for you?

**Comment by nickgsoft** [comment]
@anatolybolshakov  thanks for your help, but recently i have not came across such issue yet.

**Comment by anatolybolshakov** [comment]
@nickgsoft ok thanks! I'm closing it at the moment, please feel free to reopen if you will face with it again.
