### ISSUE TITLE
Incorrect prerequisites for developing tasks

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [microsoft/azure-pipelines-tasks#13711]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: CmdLineV2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CmdLineV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Ubuntu 18.04

## Issue Description

CmdLineV2: 
https://github.com/microsoft/azure-pipelines-tasks/blame/master/Tasks/CmdLineV2/task.json#L72 refers to Node14. However, the prerequisites documentation refers to Nod10 as the Production execution environment.
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#prerequisites

Is this line of code bug, or intended to be that that way and the custom tasks created must work both in Node10 and Node14?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by DaniilShmelev** [comment]
Hi @vairakkumar-vairaperumal, sorry for the delay: we faced with some issues due to Node14 migration, so it's reverted currently - I updated related docs as well.
