### ISSUE TITLE
Helm Lint - Error: unknown flag: --with-subcharts

### ISSUE THREAD

**Issue by rajurh** [microsoft/azure-pipelines-tasks#13718]
I am trying to use helm lint --with-subcharts for validating subcharts from the umbrella chart which works on directly on cmd but when I try with Helm task of Azure DevOps I get below error

![image](https://user-images.githubusercontent.com/15551296/96224908-c531b600-0fec-11eb-8618-9755f1b98285.png)

Code snippet in yaml
![image](https://user-images.githubusercontent.com/15551296/96224981-de3a6700-0fec-11eb-8b0e-5c2b2b7936fd.png)

I tried --with-subcharts with arguments command no luck.

**Comment by ds-ms** [comment]
Perhaps it's a version issue, try using a `HelmInstaller` task to fix the version (possibly the one in your CLI) of helm being used in your pipeline and try again.

**Comment by rajurh** [comment]
> Perhaps it's a version issue, try using a `HelmInstaller` task to fix the version (possibly the one in your CLI) of helm being used in your pipeline and try again.

Thanks yes it's with version. Using >= 3.2.1 is fixed
