### ISSUE TITLE
Could some please explain what's the significance of #regex inside task.json while querying packages/feeds?

### ISSUE THREAD

**Issue by armanik11** [microsoft/azure-pipelines-tasks#13717]
This is a question. Appreciate if someone could explain.

Reference: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadPackageV0/task.json

I came across this and was wondering what this means and how it works? What's the significance of using #regex here and how does it expand?

"endpointUrl": "{{endpoint.url}}/{{ **#regex ([a-fA-F0-9\-]+/)[a-fA-F0-9\-]+ feed }}_apis**/Packaging/Feeds/{{ **#regex [a-fA-F0-9\-]*/([a-fA-F0-9\-]+) feed }}**{{#if view}}@{{{view}}}{{/if}}/Packages?includeUrls=false"

Also I would like to know how many packages will it return and display in the Task input UI dropdown if there are thousands of packages in the feed. Is there a known limit like first 100 or something?

**Comment by jmyersmsft** [comment]
Please see my [answer](https://stackoverflow.com/a/64436451/6658931) to your StackOverflow question on the same topic.
