### ISSUE TITLE
Question: How can we define MSBuild 16.8 in NuGetCommad

### ISSUE THREAD

**Issue by justinasfour04** [microsoft/azure-pipelines-tasks#13715]
How can I get NuGetCommand to use MSBuild 16.8 as we are using dotnet 5.0. Can't seem to get it work, with vstsFeed set because the msBuild is pointing to 16.7 when we need 16.8. 

I would like to know if there is a way to define the VstsFeed and the MSBuild in order to restore private nuget packages for our needs.
*Type*: Question

**Enter Task Name**: NuGetCommand

### Error logs

Determining projects to restore...
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error : Problem starting the plugin 'C:\Users\VssAdministrator\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. Plugin 'CredentialProvider.Microsoft' failed within 5.031 seconds with exit code -1. [D:\a\1\s\src\dcbel.Mobile\src\dcbel.Mobile.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/ossiaco/_packaging/chorusdev/nuget/v3/index.json. [D:\a\1\s\src\dcbel.Mobile\src\dcbel.Mobile.csproj]
C:\hostedtoolcache\windows\dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [D:\a\1\s\src\dcbel.Mobile\src\dcbel.Mobile.csproj]

**Comment by jmyersmsft** [comment]
I recommend either switching to the DotNetCore task for restoring packages in .net 5 projects, or even better switching to the NuGet Authenticate task combined with a script task that runs `dotnet restore` directly according to your own requirements
