### ISSUE TITLE
How to run bash or any script if else condition in Azure yaml pipelines

### ISSUE THREAD

**Issue by crsreddy1447** [microsoft/azure-pipelines-tasks#13721]
Question: I have a Jenkins file 
nodejs('NodeJS_12.4) {
                    script{
                        if ("${path}"=="") {
                            sh "npm i"
                        }
                        else {
                            sh "cd ${path} && npm i"
                        }
                    }
                }
I am passing these using bash script in Azure pipeline as below
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      if ("$PATH"=="") { "npm i"}
      else { "cd ${PATH} && npm i"}
Then I am getting an error  like  
syntax error near unexpected token `{'
sh: line 1: `if ("$LAMBDA_PATH"=="") { "npm i"}'

## Environment
- Server - Azure Pipelines or TFS on-premises?

### Error logs
syntax error near unexpected token `{'
sh: line 1: `if ("$LAMBDA_PATH"=="") { "npm i"}'
Bash exited with code '2

**Comment by anatolybolshakov** [comment]
Hi @crsreddy1447 this doesn't seem to be a valid bash script - could you please take a look at some examples of conditional statements in bash here? https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_02.html#sect_07_02_01

**Comment by anatolybolshakov** [comment]
Hi @crsreddy1447 is this issue still actual for you?

**Comment by crsreddy1447** [comment]
No. You can close

**Comment by anatolybolshakov** [comment]
@crsreddy1447 ok, thanks! I'm closing it at the moment
