### ISSUE TITLE
Is it possible to enable a select all option in a pickList input inside task.json?

### ISSUE THREAD

**Issue by armanik11** [microsoft/azure-pipelines-tasks#13723]
For a pickList in a task input UI, is there an option to have a Select All option? Is there a property that can be used inside task.json for the input?

**Comment by egor-bryzgalov** [comment]
Hi, @armanik11 

Unfortunately, it's impossible to pick multiple options of pickList at the moment.
If you faced any issue with a specific task's inputs, could you please describe it so we can help you?
We're looking forward to hearing from you!

**Comment by armanik11** [comment]
Hi @egor-bryzgalov ,

I do see a way to do multiple select by using below properties in a pickList input. What I'm also looking for is a Select All option at the top.

 "properties": {
        "EditableOptions": "true",
        "MultiSelectFlatList": "True"
      },

Something like below:

![image](https://user-images.githubusercontent.com/31492646/96488331-aa309300-11f2-11eb-8ed2-52d471465c92.png)

**Comment by anatolybolshakov** [comment]
Hey @armanik11 it looks like some UI enhancement for task editor, so it's not related to a specific task. This repo mostly holds issues with specific tasks, please file general issues at https://developercommunity.visualstudio.com/spaces/21/index.html - that way it will get the right eyes on it

**Comment by anatolybolshakov** [comment]
@armanik11 I'm closing it currently - please let us know if you have any other issues
