### ISSUE TITLE
Add EditableOptions to WebAppKind input

### ISSUE THREAD

**Issue by LiquoriChris** [microsoft/azure-pipelines-tasks#13733]
Add `EditableOptions` to `WebAppKind` input on  `AzureRMWebAppDeploymentV4`  pipeline task.

**Comment by LiquoriChris** [comment]
Thank you for including this. Appreciate the help. 

Thanks,
Chris

**Comment by AmrutaKawade** [comment]
This is fixed and will be deployed within 2 weeks thanks for contribution
