### ISSUE TITLE
Visual Studio Test (V 2.*) Task: How to retrieve TestRunId when Test Selection uses Test Plan.

### ISSUE THREAD

**Issue by mailtopavanc** [microsoft/azure-pipelines-tasks#13754]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**:  Visual Studio Test V2

## Environment
 Azure Pipelines 
    
  
## Issue Description

Hi Team,

We are using Visual Studio Test (V 2.*) Task to execute Automated Tests under given Test plan. In Automated Test methods , we have custom logic to add more detail to Test Results using TestRunID. When we are executing from TestHub , we can see that $(test.RunId) is available. But we would like to get this when Test Selection uses Test Plan. 

RunId Available upfront during Select tests using as Test Run
![image](https://user-images.githubusercontent.com/73262825/96969299-206d1800-14c7-11eb-89c8-9825cc913b3a.png)

 
**Question:**
When Select tests using as TestPlan like below, TestRunId is getting created during this task execution internally and we don’t have any control. Actually we want to use that TestRunID in our Automated Test method implementations.
  **_Is there any way to pass on this TestRunID to associated TestMethods ducting execution._** 

![image](https://user-images.githubusercontent.com/73262825/96969324-2cf17080-14c7-11eb-8b30-8a1e0ffd5cc3.png)

**Comment by mailtopavanc** [comment]
Added more details to query along with screenshots.

**Comment by ShreyasRmsft** [comment]
@mailtopavanc are you on AzureDevOps services or Azure DevOps server (TFS onprem)?

**Comment by ShreyasRmsft** [comment]
Closing due to no reply

**Comment by QA-automation-engineer** [comment]
@ShreyasRmsft 
So, is it possible somehow to get TestRunId from VS test task when Test Selection uses Test Plan?
We are also interested in this topic.

We are using AzureDevOps services.
Thanks in advance.
