### ISSUE TITLE
When deploying a large webjob, the file that keeps the webjob stopped is deleted and the webjob is restarted before deployment is completed

### ISSUE THREAD

**Issue by Etiennepicard** [microsoft/azure-pipelines-tasks#13751]
## Required Information

*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines 
account name: Mediaclip
team project name: Hub
build definition name/build number: Not sure

- Agent - Private: 
OS of the machine running the agent: 4.8-windowsservercore-2009
Agent version: 2.175.2

## Issue Description

When deploying a large webjob (200mb+), the file that keeps the continuous webjob stopped( site\wwwroot\App_Data\jobs\continuous\{jobname}\disable.job ) is deleted during the deployment, which restarts the webjob before deployment is completed, which locks the rest of the files that need to be deployed. 
Note that the only setting that allowed us to make this work was "Exclude files from the App_Data folder", which isn't ideal since we may want to delete those files sometimes.

### Task logs

[ReleaseLogs_4247.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5416983/ReleaseLogs_4247.zip)

### Error logs

2020-10-21T14:50:15.0613342Z ##[error]Error: Error Code: ERROR_FILE_IN_USE
More Information: Web Deploy cannot modify the file 'Mediaclip.ClipProducer.ProductionServer.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.  Learn more at: https://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
Error count: 1.

Edit: Changed the path for the file that disables the continuous job to the correct one

**Comment by AmrutaKawade** [comment]
@Etiennepicard can you try using zip deploy option instead of web deploy

**Comment by AmrutaKawade** [comment]
@Etiennepicard Web Deploy cleans target before deploying. "Exclude files from the App_Data folder" is the right approach to make it work. If you want to delete App_Data contents as well try Zip Deploy option. ZipDeploy doesn't remove all files from destination but replaces changed files and deletes removed files of package
