### ISSUE TITLE
Why powershell inline script length is limited?

### ISSUE THREAD

**Issue by lg2de** [microsoft/azure-pipelines-tasks#13752]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: PowerShellV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
  - DevOps Server 2019

- Agent - Hosted or Private: 
    - Private hosted agent version 2.170.0 on Windows Server 2019

## Issue Description

In the past the PowerShell task has been changed several times to increase the max length for inline scripts, step by step.

Today I hit the max length, once again. :(

Why the script length is limited at all?
Can the limit be removed completely?

**Comment by DaniilShmelev** [comment]
Hello, this is a bit of an interesting issue for us as we didn't expect anybody to hit this limit. Do you have any concerns about using script from file?

**Comment by lg2de** [comment]
Yes, I'm using this task in a release pipeline.
Using a script requires to provide the script as artifact. But the script is only used in the pipeline.

**Comment by DaniilShmelev** [comment]
You don't have to provide it as an artifact, you can just use it from your repository :)

**Comment by lg2de** [comment]
The release pipeline does only have relation to artifacts. Do I need to manually clone the repository which is "behind" the artifact?

Anyway, having the script in the (one) repository, the release development will get more complicated. Changing the script needs full cycle of development (Pull Requests, etc.).

**Comment by DaniilShmelev** [comment]
Yes, my bad - since you are using release pipeline, you need to use artifacts to provide a large script file.
There are some limitations like environment variables size or job message size, so we can't get rid of the limit for this task input - please see [this](https://github.com/microsoft/azure-pipelines-tasks/issues/6509#issuecomment-368125022) for more info.

**Comment by lg2de** [comment]
This means there is no easy way to remove nor increase the limit.
We have to live with a work-around at the moment.

Mind my use-case, do you think there is any change with major rework of infrastructure?

**Comment by DaniilShmelev** [comment]
Unfortunately there's no easy way to resolve this limitation. We'll take this issue into account and try to resolve it when it's possible.

**Comment by DaniilShmelev** [comment]
Hello @lg2de, feel free to create a new issue if you encounter any other problems with this task. Have a nice day!
