### ISSUE TITLE
Build machine image failed because deploy script not found

### ISSUE THREAD

**Issue by KennyChen0909** [microsoft/azure-pipelines-tasks#13771]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Build machine image 
version 1.175.1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines- Org name: kennychan

- Agent - Hosted or Private: 
    Hosted Ubuntu 18.04

## Issue Description

1. I followed the blog provided here :https://devblogs.microsoft.com/devops/deploying-applications-to-azure-vm-scale-sets/
2. However, the task cannot find my customized deploy script"new-deploy-script.sh". 
3. Deployment package: $(System.DefaultWorkingDirectory)/_build-machine-image/drop 
4. Deploy script : $(System.DefaultWorkingDirectory)/_build-machine-image/drop/Deploy/ubuntu/new-deploy-script.sh

### Task logs
[ReleaseLogs_61.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5438877/ReleaseLogs_61.zip)

## Troubleshooting
See below key information provided by the task:

2020-10-26T11:25:54.5312726Z Resolved deploy script path: Deploy/ubuntu/new-deploy-script.sh.

2020-10-26T11:01:09.0729152Z ==> azure-arm: /tmp/script_5025.sh: 5: /tmp/script_5025.sh: /deployTemp/Deploy/ubuntu/new-deploy-script.sh: not found

Would like to know how to make this task find my deploy script? I can confirm it has been successfully downloaded in download artifact task. Appreciate your help.

**Comment by damccorm** [comment]
Hey @KennyChen0909 - this looks like a more general service question, not a problem with a specific task. This repo is for task issues, would you mind opening a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html? It will have a better chance of getting routed to the right person that way.
