### ISSUE TITLE
Error: 'subscriptionId' cannot be null

### ISSUE THREAD

**Issue by Paxilein** [microsoft/azure-pipelines-tasks#13779]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug?

**Enter Task Name**: AzureFunctionAppV1 and AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: not specific to our environment....

- Agent - Hosted
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

When using the two mentioned tasks to deploy a WebApp/FunctionApp we get the error: "'subscriptionId' cannot be null" when using a Management Group Service connection. Checking the code both tasks don't support the subscriptionId yet. Using the tasks with the normal Subscription Level Service connection works fine.

### Task logs

##[error]Error: 'subscriptionId' cannot be null.

### Error logs

##[error]Error: 'subscriptionId' cannot be null.

**Comment by AmrutaKawade** [comment]
Can you explain your scenario, why do you need management group service connection for these tasks?

**Comment by arjgupta** [comment]
@Paxilein management group service connection will not work for deploying to a web app. When creating managment group service connection you do not provide a subscription id but for deploying to resources like a web app, we need to have the subscription id.

**Comment by Paxilein** [comment]
@arjgupta Yes, that's why I opened the issue... To have that feature of adding the SubscriptionId to the Task, like other tasks already have...

@AmrutaKawade Well, my scenario is that my Azure-Access-Manager does give me the Management Group Service Connection and tells me to use it wherever possible...

**Comment by iamalexmang** [comment]
This issue SHOULD not be closed. Considering that more tasks receive this capability (of using a Management Group scoped service connection) by using the subscription Id parameter (e.g. the AzureCLI@2 etc., the AzureResourceManagerTemplateDeployment@3 task etc.), not having the ability of passing in a subscriptionId parameter makes this task less flexible and incompatible with the rest of the pipeline using Management Group scoped service conenctions.

**Comment by kekovski** [comment]
No Clue why this issue is closed. What is the constraint to not be able to use the AzureKeyVault task with a Management Group scoped service connection?

**Comment by pmooij** [comment]
> This issue SHOULD not be closed. Considering that more tasks receive this capability (of using a Management Group scoped service connection) by using the subscription Id parameter (e.g. the AzureCLI@2 etc., the AzureResourceManagerTemplateDeployment@3 task etc.), not having the ability of passing in a subscriptionId parameter makes this task less flexible and incompatible with the rest of the pipeline using Management Group scoped service conenctions.

running into the same error here, need to deploy function app through management group level service connection.
disappointing to see this issue is closed without resolution :(

**Comment by pmooij** [comment]
thanks for opening-up again @v-saikumart.
working around this issue now by using a command line deploy, but specifically deploying the app settings is a PITA.

would love to use AzureFunctionAppV1 / *vNext to do the trick with management group level service connections, 
like we used to do with subscription level service connections.

**Comment by jboeshart** [comment]
Seeing the same error when using an AzureKeyVault@2 task with a management group scoped service connection. Would be great if we could get the ability to specify a subscription ID as a parameter for tasks.

**Comment by CARLOSMECK** [comment]
The ability to use a service connection with a Management Group scope for tasks like AzureAppServiceManage would be reallyt good for flexibility and efficiency in managing deployments across different environments and subscriptions. The suggestion to enable the passing of a subscription ID parameter to these tasks, to make them compatible with Management Group scoped service connections, is a valid and necessary enhancement.

**Comment by msterin** [comment]
At the very least, some sane error message with a link to some explanation should be provided. It's how useless and misleading the current message is

**Comment by cstrempfer** [comment]
I had copied this issue, because it was closed and wasn't reopened at that time.

Let's continue this discussion in #14359

**Comment by Tni04** [comment]
I’ve spent some time investigating the source code of the azure-pipelines-task-lib and the AzureWebApp@1 task to understand why Management Group-scoped service connections fail.

### Technical Findings:
The root cause is that several tasks (like AzureWebApp@1) rely on the azure-pipelines-task-lib to retrieve endpoint data. Specifically, in [task.ts (line 476)](https://github.com/microsoft/azure-pipelines-task-lib/blob/f7430e942ba3f351d1756a505e5f6daabe8e1678/node/task.ts#L476), the library expects to find connection metadata mapped to environment variables using the pattern: ENDPOINT_DATA_\<CONNECTION_ID\>_\<KEY\>.

When a Service Connection is scoped to a Management Group, the SUBSCRIPTIONID key is missing from the endpoint object, causing providers like [AzureRmWebAppDeploymentProvider.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/3b9fcd4c3c6e9301da6caabc341609ad388df0cb/Tasks/AzureWebAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts#L51) to fail with the subscriptionId cannot be null error.

### Workaround:
Until native support for subscription selection is implemented for MG-scoped connections, you can manually inject the required metadata into the task's environment. By providing the expected environment variable, the task library will resolve the ID correctly.

Add the following to your task:

```YAML
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Your-MG-Scoped-Connection-Name'
    appName: 'your-app-name'
    # ... other inputs
  env:
    # Pattern: ENDPOINT_DATA_<SERVICE_CONNECTION_GUID>_SUBSCRIPTIONID
    ENDPOINT_DATA_00000000-0000-0000-0000-000000000000_SUBSCRIPTIONID: 'your-target-subscription-guid'
Note on IDs:
```

Service Connection GUID: You can find this in the URL of the Service Connection settings page (look for the resourceId parameter).

Subscription GUID: The ID of the specific subscription where the resource is located.

While this unblocks the pipeline, this is strictly a workaround. The official solution should be for the task to natively handle Management Group scopes by allowing a subscription ID input or resolving it dynamically without failing the endpoint validation.

**Comment by synalogik-jfrench** [comment]
> I’ve spent some time investigating the source code of the azure-pipelines-task-lib and the AzureWebApp@1 task to understand why Management Group-scoped service connections fail.
> 
> ### Technical Findings:
> The root cause is that several tasks (like AzureWebApp@1) rely on the azure-pipelines-task-lib to retrieve endpoint data. Specifically, in [task.ts (line 476)](https://github.com/microsoft/azure-pipelines-task-lib/blob/f7430e942ba3f351d1756a505e5f6daabe8e1678/node/task.ts#L476), the library expects to find connection metadata mapped to environment variables using the pattern: ENDPOINT_DATA_<CONNECTION_ID>_<KEY>.
> 
> When a Service Connection is scoped to a Management Group, the SUBSCRIPTIONID key is missing from the endpoint object, causing providers like [AzureRmWebAppDeploymentProvider.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/3b9fcd4c3c6e9301da6caabc341609ad388df0cb/Tasks/AzureWebAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts#L51) to fail with the subscriptionId cannot be null error.
> 
> ### Workaround:
> Until native support for subscription selection is implemented for MG-scoped connections, you can manually inject the required metadata into the task's environment. By providing the expected environment variable, the task library will resolve the ID correctly.
> 
> Add the following to your task:
> 
> - task: AzureWebApp@1
>   inputs:
>     azureSubscription: 'Your-MG-Scoped-Connection-Name'
>     appName: 'your-app-name'
>     # ... other inputs
>   env:
>     # Pattern: ENDPOINT_DATA_<SERVICE_CONNECTION_GUID>_SUBSCRIPTIONID
>     ENDPOINT_DATA_00000000-0000-0000-0000-000000000000_SUBSCRIPTIONID: 'your-target-subscription-guid'
> Note on IDs:
> Service Connection GUID: You can find this in the URL of the Service Connection settings page (look for the resourceId parameter).
> 
> Subscription GUID: The ID of the specific subscription where the resource is located.
> 
> While this unblocks the pipeline, this is strictly a workaround. The official solution should be for the task to natively handle Management Group scopes by allowing a subscription ID input or resolving it dynamically without failing the endpoint validation.

Sadly this doesn't appear to work using `AzureFunctionApp@2` with a flex consumption app.  The ID of the service connection was provided, though errors with `##[error]Error: 'subscriptionId' cannot be null` still
