### ISSUE TITLE
multiple provisioning profiles for Xcode task

### ISSUE THREAD

**Issue by Ahmadalsofi** [microsoft/azure-pipelines-tasks#13776]
Hi there,

Using multiple provisioning profiles
Currently, there's no support of multiple provisioning profiles for Xcode task (for example for iOS App Extension)

is it still not supported? if so is there's any way to work around this issue? 

Thanks

**Comment by max-zaytsev** [comment]
Hi @Ahmadalsofi,

Thank you for your question!
According to our [docs](https://github.com/MicrosoftDocs/azure-devops-docs-pr/blob/29b685ef645d5667133d18fc0669720e9093f39a/docs/pipelines/tasks/build/xcode.md), Xcode task doesn't yet support multiple provisioning profiles. Unfortunately, there is no workaround for this. We have a task in our backlog to add provisioning profiles support.

Thanks,
Max

**Comment by max-zaytsev** [comment]
Close the issue for now. @Ahmadalsofi if you still have questions feel free to reopen it.

**Comment by svarnik** [comment]
Hi. How you don't support multiple profiles, if another developer was able to make this on pipeline:
https://github.com/microsoft/azure-pipelines-tasks/issues/8811
