### ISSUE TITLE
Build machine image failed with conda: command not found

### ISSUE THREAD

**Issue by KennyChen0909** [microsoft/azure-pipelines-tasks#13773]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Build machine image 
version:1.175.1

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure pipeline

- Agent - Hoste or Private: 
Hosted Ubuntu 18.04
## Issue Description

I have a customer using this task to build a image needs miniconda with their deploy script. Check below partial deploy script:

```
#! /bin/bash

function setup_vm() {

    printf "***************************************************\n\t\t Setup VM \n***************************************************\n"

    echo ======= Updating packages ========

    sudo apt update --yes
}

function resolve_dependencies() {
    printf "***************************************************\n\t\t Resolve Dependencies \n***************************************************\n"

    echo ======= Installing conda =======
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p ~/miniconda
    rm ~/miniconda.sh
}

function setup_env() {
    printf "***************************************************\n\t\t Setup Up Environment \n***************************************************\n"
    echo ======== Init conda =======
    conda init

    echo ======== Creating conda env =======
    conda env create -f um-env.yaml

    echo ======== Activating conda env =======
    conda activate um-env
}


function check_last_step() {
    if [ $1 -ne 0 ]; then
        printf "Exiting early because the previous step has failed.\n"
        printf "***************************************************\n\t\t Deployment Failed. \n***************************************************\n"
        exit 2
    fi
}

setup_vm
check_last_step $?

resolve_dependencies
check_last_step $?

setup_env
check_last_step $?

```

The script failed when the task trying to execute conda init. It failed with this error in log(Build VM image):

2020-10-26T09:06:49.4029200Z ==> azure-arm: /deployTemp/s/deploy-script.sh: line 25: conda: command not found

### Task logs

[utf-8''ReleaseLogs_42.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5439566/utf-8.ReleaseLogs_42.zip)

## Troubleshooting

1. Same script can be successfully executed in bash task.
2. I tried to reproduce the issue but encounter a strange error which I posted here: https://github.com/microsoft/azure-pipelines-tasks/issues/13771

##Ask for help
Is it expected that this task won't accept conda command even though it has been successfully installed?

**Comment by KennyChen0909** [comment]
Any suggestions?

**Comment by damccorm** [comment]
Hey @KennyChen0909 - this looks like a more general service question, not a problem with a specific task. This repo is for task issues, would you mind opening a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html? It will have a better chance of getting routed to the right person that way.
