### ISSUE TITLE
Assertion failed: (timeout != -1) in Command line task on MacOS

### ISSUE THREAD

**Issue by pakrym** [microsoft/azure-pipelines-tasks#13785]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Command line
Version      : 2.176.1

## Environment
- Server - Azure Pipelines?
    https://dev.azure.com/azure-sdk/internal/_build/results?buildId=592585&view=logs&j=9cfc3b0b-53b1-524f-85ed-0ef4880bef82&t=277ae693-9b68-5ef5-d666-bb5a558e8cc2
	https://dev.azure.com/azure-sdk/internal/_build/results?buildId=584558&view=logs&j=9cfc3b0b-53b1-524f-85ed-0ef4880bef82&t=277ae693-9b68-5ef5-d666-bb5a558e8cc2&l=28553

- Agent - Hosted or Private: Hosted

```
Agent name: 'Azure Pipelines 30'
Agent machine name: 'Mac-1603813119026'
```

## Issue Description

Task invocation fails with 

```
Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 231.
##[error]Exit code 134 returned from process: file name '/Users/runner/runners/2.175.2/externals/node/bin/node', arguments '"/Users/runner/work/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/2.176.1/cmdline.js"'.
```

### Task logs

N/A, fails inconsistently but always on Mac OS.

**Comment by alexander-smolyakov** [comment]
Hi @pakrym, this issue related to Node v6. 

You can find a similar issue in the node repo by the following [link](https://github.com/nodejs/node/issues/34633).

We started working on migration to Node v14 so hopefully, this issue will be resolved with future updates.

So I'm closing it a the moment.

Thanks!

**Comment by jpivarski** [comment]
For the record, I've been seeing this, too. My only recourse is to restart failed jobs, because this is intermittent. (It especially happens in tests with long logs.)

Is there a PR I can watch to see how this is going?

**Comment by ryanrodemoyer** [comment]
Could this be a possible explanation for #13858 ?

**Comment by jpivarski** [comment]
That link points to something about Visual Studio. This was something that only affected MacOS, not Windows.

In my experience over the past week (seeing that my comment here was 9 days ago), it got worse for a few days—intermittent with a higher probability, sometimes even affecting the restarted job—then got much better. I haven't seen this issue in days.

@alexander-smolyakov thought it was related to the Node version, and the link he points to has this error message. Has the Node version been updated? If so, we've noticed!

**Comment by NaagAlgates** [comment]
I faced a similar issue yesterday and created a ticket: https://developercommunity2.visualstudio.com/t/azure-pipelines-for-ios-returned-exit-code-134-https://developercommunity2.visualstudio.com/t/azure-pipelines-for-ios-returned-exit-code-134-ass/1249827

and I was redirected to this ticket. But seems like the ticket is already closed, which is not.

**Comment by alexander-smolyakov** [comment]
>> @alexander-smolyakov thought it was related to the Node version, and the link he points to has this error message. Has the Node version been updated? If so, we've noticed!

Hey @jpivarski, a couple of tasks (`CmdLineV2` included) already migrated to Node 10 and these changes will be available in 2-3 weeks for all users. Here is a link to related PR for [CmdLineV2 migration](https://github.com/microsoft/azure-pipelines-tasks/pull/13803).


>> I faced a similar issue yesterday and created a ticket: https://developercommunity2.visualstudio.com/t/azure-pipelines-for-ios-returned-exit-code-134-https://developercommunity2.visualstudio.com/t/azure-pipelines-for-ios-returned-exit-code-134-ass/1249827
and I was redirected to this ticket. But seems like the ticket is already closed, which is not.

Hey @NaagAlgates, yes this exactly the same issue it may appear on different tasks because it related to Node 6 itself. As I can see in your case the problem was with `XcodeV5`, we already did a migration to Node 10 for this task, here is a link for [related PR](https://github.com/microsoft/azure-pipelines-tasks/pull/13777).

The updated version of the `XcodeV5` task will be available in 2-3 weeks.

Thanks!

**Comment by NaagAlgates** [comment]
Okay. Thank you.
