### ISSUE TITLE
AzureResourceManagerTemplateDeployment@3 does not support multiline strings in ARM templates

### ISSUE THREAD

**Issue by jakob327** [microsoft/azure-pipelines-tasks#13781]
## Required Information

**Question, Bug, or Feature?**  
*Type*:  Feature / Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

## Environment
- Server: Azure Pipelines

- Agent: Hosted

## Issue Description

Multiline strings in ARM templates are not supported when using AzureResourceManagerTemplateDeployment@3. The documentation of the arm-templates however states that they are valid: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#multi-line-strings

### Error logs

2020-10-27T10:09:10.3421559Z ##[error]Error: Ensure the Template file ( '/home/vsts/work/r1/**/arm-template.json' ) is valid. Task failed while parsing with following error: Unexpected token 
 in JSON at position 78426

**Comment by Jandev** [comment]
For others, who might stumble across this issue.
Our team has solved this by using the `concat` method.
```json
"secret": {
    "ssh_host_key": "[base64(concat('-----BEGIN OPENSSH PRIVATE KEY-----\n',
        'theReallyLong\n',
        'sshKeyNecessary\n',
        'ForThisService\n'))]"
}
```
It's not ideal, but a workable workaround.

**Comment by miqm** [comment]
I just spend 1h of trying to figure out what's wrong with my template... VSCode ARM Template syntax checker does not see any issue, while when deploying I'm getting invalid JSON format.

This does not work:
```
"varName": "[base64(concat('line1',
'\nLine2',
'\nLine3,
'\nLine4'))]",
```
Nor this:
```
"varName": "[base64('line1
Line2
Line3
Line4')]",
```
In both cases, VSCode does not see any problem with the template.

**Comment by alanta** [comment]
The easiest fix I found is to put the string on one line with `\n` for newlines:

```json
"varName": "[base64('line1\nLine2\nLine3\nLine4\n'))]"
```

I am able to deploy certs and keys to container instances with that format.
Note that VS Code doesn't think there is a problem because the template is in fact valid. Both Azure Powershell and Azure CLI will happily deploy templates with multi-line strings. Only the pipeline task has a problem with the JSON syntax.

**Comment by miqm** [comment]
The thing is, that azure cli also has a problem with this. Perhaps if you deploy through portal it will, but az cli also does some parsing before and also fails.

**Comment by hwride** [comment]
This issue I believe is not to do with having newlines in the values of strings, but being able to specify ARM template multi-line strings which helps with things like long if conditions. See: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#multi-line-strings

**Comment by bishal-pdMSFT** [comment]
We are not planning to fix this as 1) it is not a common scenario to use multi line text and 2) a reasonable [workaround](https://github.com/microsoft/azure-pipelines-tasks/issues/13781#issuecomment-720978175) exists.
