### ISSUE TITLE
AzureCLI task workingDirectory doesn't expand template parameters

### ISSUE THREAD

**Issue by andrejpk** [microsoft/azure-pipelines-tasks#13807]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: AzureCLI  

## Environment
- Server - Azure Pipelines
  
      
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account: clikz Project: Project Clikz Pipeline ref: adp-cli-extensions-ci-cd/20201029.29

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name: Ubuntu16

## Issue Description

The workingDirectory argument isn't expanding template parameters. It just comes in as a string literal and the task creates a folder with the '${{ parameter.whatever }}' in the sources folder. That's not what the Bash task does (it properly expands it). 

```
parameters:
- name: sourcePath 
  type: string

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: xxxxxxxxxxxxx
    workingDirectory: ${​​​​{​​​​ parameters.sourcePath }​​​​}​​​​
    scriptType: bash
    scriptLocation: inlineScript
    scriptArguments: '${{ parameters.sourcePath }}'
    inlineScript: |
      set -x    #echo script output
      echo ARG1:$1
      echo working folder:
      pwd
      echo sourcePath:
      cd $1 
      echo sourcePath after CD:
      pwd
```

output is:
```
ARG1:/home/vsts/work/1/cli_all
working folder:
/home/vsts/work/1/s/${​​​​{​​​​ parameters.sourcePath }​​​​}​​​​
sourcePath:
sourcePath after CD:
/home/vsts/work/1/cli_all

```

### Task logs

see above

**Comment by andrejpk** [comment]
cc @haroldwongms @prangadi

**Comment by anuragc617** [comment]
@andrejpk passing parameters to working directory within single quotes works. You are missing single quotes around ${{ parameters.sourcePath }}. Pass it as ->    workingDirectory: '${​​​​{​​​​ parameters.sourcePath }​​​​}​​​​'

**Comment by anuragc617** [comment]
@andrejpk have you tried the above solution??

**Comment by ddivanshu** [comment]
@andrejpk I copied your pipeline when expanded to yml, working directory is coming out to be 
 workingDirectory: ${â€‹â€‹â€‹â€‹{â€‹â€‹â€‹â€‹ parameters.sourcePath }â€‹â€‹â€‹â€‹}â€‹â€‹â€‹â€‹
may be this part was copied from some editor that was using non utf-8 text encoding. Can you just delete     workingDirectory: ${​​​​{​​​​ parameters.sourcePath }​​​​}​​​​ and retype instead of copying

**Comment by ddivanshu** [comment]
@andrejpk let me know if we are good to close on this.

**Comment by andrejpk** [comment]
Hey sorry, missed this notification.. I'll try it out this week!

**Comment by ddivanshu** [comment]
Closing this.Feel free to reopen if issue persists.
