### ISSUE TITLE
Cross project sharing of service connections - resource authorization issue

### ISSUE THREAD

**Issue by pkhabazi** [microsoft/azure-pipelines-tasks#13808]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: **AzurePowerShell**

## Environment
- Server - **Azure Pipelines**
    
- Agent - **Hosted**: 
    
    - If using Hosted agent, provide agent queue name: **ubuntu-latest**

## Issue Description

I am sharing an Azure Service connection with multiple Projects in Azure DevOps. On the Service connection I have enabled "Grant access permission to all pipelines".  All the new pipelines in the project where the Service connection is originally created can use the service connection without asking for authorization. However, every new pipeline from another project where the service connection is shared with needs to be authorized. I am having this issue with Azure PowerShell Task version 5 running latest version AZ modules on PWSH. 

I have also created an issue on [developercommunity ](https://developercommunity.visualstudio.com/content/problem/1239481/cross-project-sharing-of-service-connections-resou.html) because I don't know if this is caused by the Task or Azure DevOps in general.

**Comment by AmrutaKawade** [comment]
I am closing this issue as its not related to Task, and it will be tracked on [developercommunity](https://developercommunity.visualstudio.com/content/problem/1239481/cross-project-sharing-of-service-connections-resou.html)
