### ISSUE TITLE
isJacocoCoverageReportXML option missing from Azure DevOps MavenV3 task.

### ISSUE THREAD

**Issue by DevonBritton** [microsoft/azure-pipelines-tasks#13801]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Maven V3  

## Environment
- Server - Azure DevOps Server 2019 1.1 - Patch 3

- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Linux (ubuntu 16.04)

## Issue Description

I have the Code Coverage tool set to JaCoCo and have enabled SonarQube analysis but the boolean option for "isJacocoCoverageReportXML" is not visible or available. Is this change available in Azure DevOps on-prem yet?

![image](https://user-images.githubusercontent.com/33623085/97551299-1a010380-19d3-11eb-886a-ac6c3faf9c15.png)

Kind Regards,
DB

**Comment by anatolybolshakov** [comment]
Hi @DevonBritton for on-prem solution you need to update whole solution to receive last version of in-the-box tasks. As another option here - you can build Maven task and upload it manually using [tfx-cli](https://www.npmjs.com/package/tfx-cli)

**Comment by DevonBritton** [comment]
> Hi @DevonBritton for on-prem solution you need to update whole solution to receive last version of in-the-box tasks. As another option here - you can build Maven task and upload it manually using [tfx-cli](https://www.npmjs.com/package/tfx-cli)

Thanks @anatolybolshakov . I thought as much. There's an upgrade to Azure DevOps Server 2020 planned for December. I imagine that will fix the issue. 

Kind Regards,
DB

**Comment by anatolybolshakov** [comment]
@DevonBritton ok, let me close this issue at the moment - please feel free to reopen it when you'll be able to check it
