### ISSUE TITLE
Support access token authentication for SQL Server scripts

### ISSUE THREAD

**Issue by benjaminrhope** [microsoft/azure-pipelines-tasks#13802]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: SqlAzureDacpacDeploymentV1

## Environment

- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

We want to use this task to deploy a migration script to an Azure SQL database, but we have not been able to authenticate with managed identity. Our agent runs on a hosted environment, so we cannot use the 'Active Directory Integrated' authentication. Instead, we tried to pre-fetch the access token and pass it as an additional parameter. This works for dacpac deploy, but does not seem to work for SQL Server scripts.

For us to use this task, it would require that we could authenticate using the service connection as requested here: #12083 or that the task was extended to include access token authentication for SQL script.

## Additional info
According to the documentation, the `Invoke-Sqlcml` command must be invoked the following way when using access token: `Invoke-Sqlcmd -ServerInstance myserver.database.windows.net -Database mydb -AccessToken $access_token -query 'select * from Table1'`

**Comment by JonBSteer73** [comment]
Hi! Just wondering if a change to add this feature to SqlAzureDacpacDeploymentV1 task ever got completed? 

Looking at the task in my pipeline I can see it does attempt to use the -AccessToken property, but looking in the source code it appears that the SQLPS version of Invoke-Sqlcmd (which doesn't seem to allow AccessToken) is still being used.

I know I can get this working via custom powershell scripts but it would be brilliant if I could use this task.

Thanks!
