### ISSUE TITLE
Azure SQL BACPAC? task

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-tasks#13813]
Hi,

I noticed that the Azure SQL DACPAC task does not have the option to point to a BACPAC file. Disappointing as I'm sure I have a common requirement.

Essentially I wish to run a pipeline nightly that deploys a MSSQL backup "BACPAC" and than run's built DACPAC against that restored database to bring it up to date.

Once current run a series of integration tests.

Any ideas?

**Comment by AmrutaKawade** [comment]
**Export** and **Import** actions under Deployment Type "SQL Dacpac File" works with bacpac file

**Comment by PedroEss** [comment]
> **Export** and **Import** actions under Deployment Type "SQL Dacpac File" works with bacpac file

Shall you paste an example? I have not found any for import bacpac file through github actions without using powelshell.
