### ISSUE TITLE
PublishSymbols should support all agent OS's

### ISSUE THREAD

**Issue by AArnott** [microsoft/azure-pipelines-tasks#13821]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishSymbols 

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: [pipeline run](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=3832&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cbc6f77a-7572-5865-139a-6929f27c28a0). account: `andrewarnott`

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:
       ```
       Pool: Azure Pipelines
       Image: Ubuntu 16.04
       Agent: Azure Pipelines 4
       ```

## Issue Description

The `PublishSymbols` task fails on non-Windows agents:

```
Starting: Publish symbols to symbol server
==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : 2.172.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/index-sources-publish-symbols
==============================================================================
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
Finishing: Publish symbols to symbol server
```

For investigating crash dumps in our AzP test runs, we need symbols. The symbol server in AzDO promises to make acquiring the right symbols while investigating the DMP file easy, but only if the binaries were built on Windows. Please make this task work on non-Windows agents too.

**Comment by AArnott** [comment]
It would be great to hear if this aligns with the product team's backlog.

**Comment by Evangelink** [comment]
@AArnott looks like this was fixed
