### ISSUE TITLE
Using code-coverage option in maven-task uploads illegal pom-files to maven-repository (feed)

### ISSUE THREAD

**Issue by frochi42** [microsoft/azure-pipelines-tasks#13824]
**Question, Bug, or Feature?**  
*Type*: At first question. may be a bug.

**Enter Task Name**: Maven@3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
       - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Project riot, build https://dev.azure.com/bosch-riot/riot/_build?definitionId=65&_a=summary

- Agent - Hosted : 
    
    - If using Hosted agent, provide agent queue name: ???

## Issue Description

We are using the maven-task to build a project which provides a parent-pom ot other projects. (This other projects do not necessarily build within an azure pipeline). Additionally, we are using jacoco-code-coverage option for that parent project.
We noticed that the maven@3 task modifies the pom-files of our project in order to configure the jacoco-maven-plugin so that it is able to run within azure. So far so good.
But as we are executing the 'mvn deploy' all the artifacts are getting uploaded to the maven repository (azure feed), especially all the modified pom-files. These pom-files now contain settings only valid for that particular build on azure, thus all the other projects that use that project as parent are likely to fail. (And they do in our environment).
I think the maven task should revert the local changes before performing the upload.
Or are there other ideas to workaround?

**Comment by elFarto** [comment]
I've also just noticed that the Maven task modifies the pom.xml file. This causes the Cache@2 task to complain that the pom.xml file was modified during the run, in addition to the conflict with the exiting jacoco plugin entry.

It would be nice to have an option to keep the collection of the coverage, and skip the modification of the pom.xml.

**Comment by lamamakara** [comment]
@alexander-smolyakov I saw you removed bug label from this issue. 
I am having the same problem and its really looks like a bug.

**Comment by anatolybolshakov** [comment]
Hi @frochi42 @elFarto @lamamakara I changed label for this issue - since it sound more like some bug. We are going to handle this in the near time.

**Comment by DaniilShmelev** [comment]
Hi @frochi42 @elFarto @lamamakara!
We've added an option to restore original pom.xml file after maven task execution. It might take a few weeks for this change to be deployed

**Comment by frochi42** [comment]
Hi @DaniilShmelev ,
that's wonderful news, thank you.
I had a brief look over the changes, and I think there is an issue. Correct me if I'm wrong.
The restore-action is applied at the end of the maven-task. That means, if the maven goal is "maven deploy" (what is very common I guess if you have to push the result artifacts to a maven repo), it is too late if the pom-file is restored afterwards.

I fear one would have to do a two-step build. The first one would execute the normal building (with test-execution and coverage analysis, aka "maven install"), and the second one would do the upload ("mvn deploy -Dtest=skip). However, having the restore-step at the end of step 1 helps a lot. The drawback: the second maven-call will repeat many steps have been performed already in step 1.

**Comment by DaniilShmelev** [comment]
@frochi42, thanks for your feedback, I've completely missed that. We're going to explore our options here.

**Comment by Technolords** [comment]
I think the issue is somewhat more complicated, especially when used in combination of the maven release plugin. It appears, prior to actually invoking the first tasks which is part of the release:prepare, the pom.xml is already modified as explained by the parent. However, because the pom.xml is changed, the release process fails when it verifies for any modifications to the pom.xml. This breaks/blocks the release process using this plugin in combination with code coverage option
