### ISSUE TITLE
Unexpected change in case of Tag names in resourcegroup deployment

### ISSUE THREAD

**Issue by wembleyford** [microsoft/azure-pipelines-tasks#13822]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell@4  

## Environment
online dev.azure.com.

## Issue Description

I'm using a parameter.json and template.json file to deploy a resource group via the new-azSubscriptionDeployment cmdlet.
The deployment executes and succeeds, however, with one odd item of behaviour which does not occur when I run the same cmd with the same inputs, to the same azure subscription from with my laptop (Linux, Pwsh 7.0, Az. module 2.3.0).

Namely, when ran locally my tag's which are applied to the resource group are added as defined in the paramter.json

When ran in the devops pipeline, their case is changed to camel case. 

E.g. a tag named "ProjectCode" is created via pipelines, as "projectCode" whereas the same code produces a tag called "ProjectCode" when ran from my laptop.  

The values of the tags are not being changed, just their names.  I can't really see where this is occurring - if it's a function of the cmdlet, the environment the agent is running within or elsewhere. I haven't been able to find any useful documentation describing this behaviour. 

### Task logs
E.g. source parameter snippet:
```
 "resourceGroupTags": {
      "value": {
        "TechnicalOwner": "John Smith", }
}
```

But, pulling the deployingment info from azure gives:

```
.Get-AzDeployment -Name "deploymentname-123456"
...
Parameters              : 
                          Name                     Type                       Value     
                          =======================  =========================  ==========
                          resourceGroupTags        Object                     {
                            "technicalOwner": "John Smith",
```

It would be good to know what's causing this translation and how I can avoid it.

Apologies if this is the wrong place for this - as I said, I'm unsure as to what in the azure pipeline task environment is causing this - any pointers are gratefully received.

Thanks

**Comment by AmrutaKawade** [comment]
@wembleyford please run below command on your machine and check which Azure Powershell version is installed on your machine

`Get-InstalledModule -Name Az -AllVersions | Select-Object -Property Name, Version`

**Comment by wembleyford** [comment]
```
Name Version
---- -------
Az   4.4.0
Az   3.6.1
```

The version of new-azsubscriptionDeployment is comming from the 3.6.1 installation which provides az.resource 2.3.0

Thanks

**Comment by AmrutaKawade** [comment]
This issue is not related to Task and I am able to reproduce it with Az 4.8.0 on my laptop as well. May be some change in cmdlet. Instead of using latest powershell version (which is Az 4.8.0) you can use specific version 4.3.0 in the task. it will solve your problem. You can raise issue for Az 4.8.0 here https://github.com/Azure/azure-powershell
