### ISSUE TITLE
CommandLine Task added a debug line that breaks builds

### ISSUE THREAD

**Issue by kenotron** [microsoft/azure-pipelines-tasks#13839]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  CommandLine

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure Pipeline (office.vsts.com)

- Agent - Hosted or Private: 
    
Private 

## Issue Description

We were using this​:

```
node -e "process.stdout.write('##vso[task.setvariable variable=target_branch]refs/heads/master'.replace('refs/heads/','refs/remotes/origin/'))"
```

to write a target branch variable (which should EXIST really), but the commandline task update just broke our builds because it inserted:

`"##vso[task.debug]Exit code: 0"` at the end of that variable.

Feel free to contact me internally inside MSFT communication channels (kchau)

**Comment by max-zaytsev** [comment]
Hi @kenotron is this issue still actual for you? I just tried running the task using your code and got the correct result.

**Comment by max-zaytsev** [comment]
Hi @kenotron, is the issue still relevant for you?

**Comment by max-zaytsev** [comment]
Feel free to reopen this issue if it still happens to you.
