### ISSUE TITLE
Could not copy the links shown as potential solution for the failed run in pipelines

### ISSUE THREAD

**Issue by gkarthiks** [microsoft/azure-pipelines-tasks#13848]
**Question, Bug, or Feature?**  
*Type*: Feature

## Issue Description

On a failed run, the Azure Pipeline is displaying an error message and also displays a link to refer more. But the link is not copyable from the user interface. Attaching the screen print below.

![image](https://user-images.githubusercontent.com/30545166/98262094-3a205c00-1fab-11eb-9f8d-d32d5e8b187d.png)

**Comment by damccorm** [comment]
Hey @gkarthiks this looks like an issue with the service generally, not with a specific task. Would you mind opening an issue at https://developercommunity.visualstudio.com/spaces/21/index.html? That should ensure it gets the right eyes on it
