### ISSUE TITLE
BashV3: Unable to locate executable file: 'bash'

### ISSUE THREAD

**Issue by dzak83** [microsoft/azure-pipelines-tasks#13859]
*Type*: Bug

**Enter Task Name**: BashV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
## Issue Description

In the last few days our bash command stopped working. I am trying now bash task with hello world on Windows machine but I am getting the error:

Unable to locate executable file: 'bash'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/27939815/98426166-aacb8500-204c-11eb-8de2-4000f1ad89d9.png)

**Comment by anatolybolshakov** [comment]
Hi @dzak83 do you use self-hosted agent or ms hosted?

**Comment by dzak83** [comment]
I think we use self-hosted agents.

**Comment by anatolybolshakov** [comment]
@dzak83 could you please verify that it bash is reachable from command line - and specified in PATH?

**Comment by dzak83** [comment]
I don't have direct access to that machine. Will the task not install the environment when bash is not available?

**Comment by anatolybolshakov** [comment]
@dzak83 task is trying to extract path to bash from PATH environment variable - so it fails if it's not specified.

**Comment by dzak83** [comment]
Update: Turned out running regular command line + bash after upgrading to version 2.* solved the problem.

Thank you the your help with the investigation.
