### ISSUE TITLE
Is there a way to print out which files were downloaded with CacheV2

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/azure-pipelines-tasks#13869]
This morning, 11/9 we noticed that our cache tasks were no longer working correctly. They say all the archives were downloaded, but none of the files that should have been downloaded show up in the build tree. Trying to debug this, and not getting anywhere. Is there a way to have the task print out all the files that are downloaded from the cache?

**Comment by gbusch** [comment]
Could this be related to the issue that I describe in #13879?

**Comment by flts** [comment]
Same here, the Cache tasks report that they have found a cache based on the key and everything is downloaded. Once we want to use the files from the cache in a different task it reports that the folder/files are missing.
