### ISSUE TITLE
InstallSSHKey does not handle paths with spaces when no passphrase is used

### ISSUE THREAD

**Issue by js-hdl** [microsoft/azure-pipelines-tasks#13860]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: InstallSSHKey  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/InstallSSHKeyV0

## Environment
- Server - Azure Pipelines or TFS on-premises? On-Premise
    
    - If using TFS on-premises, provide the version: Azure DevOps Server version Dev17.M153.5; Task v0.151.2
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2019, Agent v2.153.1

## Issue Description

After setting up an InstallSSHKey task, the executed command does not properly quote the argument specifying the key file path. This only occurs if a private key passphrase is not set. Here is an excerpt from the pre-job Install SSH Key log:
```
[command]"C:\Azure Pipelines Agent\externals\Git\usr\bin\ssh-add.exe" C:\Azure Pipelines Agent\_work\_temp\TFS Key
C:\Azure: No such file or directory
Pipelines: No such file or directory
Agent\_work\_temp\TFS: No such file or directory
Key: No such file or directory
```

### Error logs

```
[command]"C:\Azure Pipelines Agent\externals\Git\usr\bin\ssh-add.exe" C:\Azure Pipelines Agent\_work\_temp\TFS Key
C:\Azure: No such file or directory
Pipelines: No such file or directory
Agent\_work\_temp\TFS: No such file or directory
Key: No such file or directory
```

**Comment by DaniilShmelev** [comment]
Hi @js-hdl!
We've implemented a fix, but it might take a few weeks to roll out. I'll update you on the progress.

**Comment by anatolybolshakov** [comment]
Hi @js-hdl we have rolled out the fix for this issue - let me close this since it was fixed, please feel free to reopen or ask any further questions if it's still actual for you.
