### ISSUE TITLE
Hi @LukaszGrela @android-dataticket could you please check that you're building app in release configuration? This error seems to be different from mentioned in this ticket and usually happens with apk built in debug configuration.

### ISSUE THREAD

**Issue by android-dataticket** [microsoft/azure-pipelines-tasks#13864]
Hi @LukaszGrela @android-dataticket could you please check that you're building app in release configuration? This error seems to be different from mentioned in this ticket and usually happens with apk built in debug configuration.

_Originally posted by @anatolybolshakov in https://github.com/microsoft/azure-pipelines-tasks/issues/10574#issuecomment-723989750_

I can confirm we are using assembleRelease and it is still failing

**Comment by LukaszGrela** [comment]
![image](https://user-images.githubusercontent.com/7643591/99392600-d7489200-28d3-11eb-85c4-c700d3b86fa6.png)
I use assembleRelease and it works, I have separate agent jobs on the pipeline  for a release (assembleRelease) and for a debug.
