### ISSUE TITLE
Cache@2 task ignores "path"

### ISSUE THREAD

**Issue by gbusch** [microsoft/azure-pipelines-tasks#13879]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2, Azure Pipelines

## Issue Description
Since 09. November, we experience issues with Cache@2 Task in Azure Pipelines.
We use it to cache Docker images, as described in the [Pipeline Caching documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images).

As we could find out now, (apparently beginning Monday, before that it worked), the pipeline ignores the property "path" in the cache-task.

Instead the cache artefact "cache.tar" is always copied into the pipeline-workspace, no matter what is defined as "path".

**Comment by biltongza** [comment]
Getting the same issue caching node_modules, the task is not respecting the path parameter anymore.

**Comment by kunliubrewing** [comment]
Same here since 10th November 2020

**Comment by denravonska** [comment]
Same here. One build succeeded 10th of November, now they fail.

> tar: .pip\r: Cannot stat: No such file or directory

With the path being passed to Cache is `$(Pipeline.Workspace)/.pip`.

**Comment by lindt** [comment]
is there a test case describing the expected behaviour? @johnterickson @nadesu

**Comment by gbusch** [comment]
For some time, only the "path" variable was ignored, but the cache.tar was still there, in the $(Pipeline.Workspace).
Since Friday, we cannot find the cache.tar at all, so the cache-task essentially becomes unusable.
Can you confirm that?
Stefan opened a ticket in the MS Developer Community as well: https://developercommunity.visualstudio.com/content/problem/1256842/pipeline-caching-is-broken.html?inRegister=true

**Comment by flts** [comment]
Same problem over here. The Cache tasks report that they have found a cache based on the key and everything is downloaded. Once we want to use the files from the cache in a different task it reports that the folder/files are missing.

**Comment by ThadHouse** [comment]
Is there any update to this? This have been broken for over 2 weeks with no response from the team.

**Comment by lindt** [comment]
@AmrutaKawade : Amruta. Could you support here somehow?

**Comment by fadnavistanmay** [comment]
Hi All, apologies for this. We did release an  agent version - 2.177.0 which broke the cache task. And we have reverted it with the patch 2.177.1 . Please use 2.177.1 agent and NOT 2.177.0 which has the breaking change.

Thanks

**Comment by ThadHouse** [comment]
@fadnavistanmay When will the AZP hosted machines update to this? We're noticing it on the AZP hosted machines.

**Comment by fadnavistanmay** [comment]
The AZP hosted machines should have upgraded with the newer version.

**Comment by fadnavistanmay** [comment]
@mjroghelia - the AZP hosted machines do get the agent update after a new patch release as well, right?

**Comment by lindt** [comment]
could confirm now that it is solves. Just had a call with @fadnavistanmay.

But due to the broken agent version there might be some broken cache artifacts. We needed to invalidate the cache written from 2.177.0 Agents (just by updating the key).

Guess the issue can be closed.
Also Path is working again. @gbusch

**Comment by johnterickson** [comment]
Apologies for the disruption @lindt .  It looks like our canary tests to protect against this were running, but we're wired up process-wise to block further deployment.
