### ISSUE TITLE
Update AzureFileCopy@4 to use AzCopy 10.6.0

### ISSUE THREAD

**Issue by shaneholder** [microsoft/azure-pipelines-tasks#13888]
Can AzureFileCopy@4 be updated to use AzCopy 10.6.0?  I believe that there is an issue in creating content-types when copying javascript files to Blob storage.  This issue seems to be resolved in at least 10.6 when I deploy from my local system.  Currently I'm needing to run 2 Copy commands to work around this issue.  The first copies all files then I copy the files specifying additional arguments.

--content-type application/javascript --include-pattern '*.js' --log-level=INFO  --recursive

I did notice that on windows-2019 image 10.7.0 is installed in the chocolatey directory.

**Comment by AmrutaKawade** [comment]
@N-Usha can you look into this enhancement request?

**Comment by timfish** [comment]
We have also found that `AzureFileCopy@4` does not copy JavaScript files with the correct content type which is a pain!

Does this require a major version bump to v5?

**Comment by AmrutaKawade** [comment]
version is updated 10.8. closing this enhancement
