### ISSUE TITLE
GitHub Release Task saying Repository is not valid for 'windows-toolkit/WindowsCommunityToolkit'

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/azure-pipelines-tasks#13882]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 

GitHub Release 1.*

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/dotnet/WindowsCommunityToolkit/_releaseDefinition?definitionId=1

- Agent - Hosted or Private: Don't know
    
## Issue Description
GitHub Release Task saying Repository is not valid when using '/' character

I searched for the repo I wanted here, using the provided search:

![image](https://user-images.githubusercontent.com/24302614/98881724-87834a00-243f-11eb-9b3d-d6fb82729a53.png)

Selecting it then shows it as invalid:

![image](https://user-images.githubusercontent.com/24302614/98881702-7cc8b500-243f-11eb-92e6-e9ffd82ec324.png)

If I flip the '/' to a '\' it stops complaining, but this seems wrong?

![image](https://user-images.githubusercontent.com/24302614/98881790-ac77bd00-243f-11eb-9bff-e49468c076cc.png)

If I add a letter or something it says it's invalid again, so it does seem to be validating? This is just confusing as all the docs point to the standard nomenclature of referring to org/repo with the '/' character.

I tried many other selections and they've worked fine, but as soon as I select 'windows-toolkit/WindowsCommunityToolkit' it gives me the error message, even though it's a valid repo: https://github.com/windows-toolkit/WindowsCommunityToolkit

**Comment by michael-hawker** [comment]
I was trying to use the OAuth authentication, I switched to a PAT and it seems to not be complaining???

**Comment by Ganeshrockz** [comment]
@michael-hawker We do have a validation check in place when you use an OAuth Connection. But I am not able to reproduce the same issue. Both forward and backward slashes worked fine for me. 

Are you facing the similar issue with all the other repositories? If not, what's so special about that one repo? Do you have specific details to share?

**Comment by Ganeshrockz** [comment]
Closing it as stale issue since the author didn't get back
