### ISSUE TITLE
No Option in Azure App Service Deploy Task (Linux) for .NET 5

### ISSUE THREAD

**Issue by lehne** [microsoft/azure-pipelines-tasks#13893]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service Deploy

## Environment
- Server - Azure Pipelines
  
## Issue Description

[Include task name(s), screenshots and any other relevant details]
The options that I have are:
![image](https://user-images.githubusercontent.com/4531382/99108129-e7e7c800-25b4-11eb-9f64-e565d09cc00e.png)

I need to be able to deploy to this:
![image](https://user-images.githubusercontent.com/4531382/99108198-fd5cf200-25b4-11eb-80bc-afe02ec64e49.png)

Right now, when I deploy I have to manually change it in Azure after deploy.

**Comment by johanclawson** [comment]
Any updates? This is a showstopper for us as well and we´re not able to change the stack after deploy (linux web app). Does it exist any workarounds like instead setting the linuxFxVersion in the configuration?

**Comment by AmrutaKawade** [comment]
@johanclawson we use https://docs.microsoft.com/en-us/rest/api/appservice/provider/getavailablestacks to list available runtime stack. and this version of .Net is not available in this API response currently. but you can manually type required runtimestack dropdown is editable.

**Comment by lehne** [comment]
@johanclawson it looks like DOTNETCORE|5.0 is indeed the right one. That works for me. I had tried DOTNET|5.0 and it did not work.

**Comment by johanclawson** [comment]
Thanks for the response! Strange, I don't think "DOTNETCORE|5.0" worked for me - but it could be that I possible misspelled it (doh).. Anyway what finally worked for me was setting the linuxFxVersion to "DOTNETCORE|5.0" in a seperate release step after publishing the app as a DOTNETCORE|3.1 app.

**Comment by AmrutaKawade** [comment]
Great to hear that you are unblocked now. Closing this issue

**Comment by skyfrk** [comment]
Why does `DOTNETCORE|5.0` work as `Runtime Stack`? Does the Azure Pipelines Task magically convert it to `DOTNET|5.0`?

According to the [docs](https://docs.microsoft.com/en-us/azure/app-service/overview#built-in-languages-and-frameworks) one can retrieve all available runtime stacks for an App Service (Linux) via `az webapp list-runtimes --linux`.

I ran given command and acccording to this result `DOTNETCORE|5.0` shouldn't be an option at all, right?

```json
[
  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "DOTNET|5.0",
  "NODE|14-lts",
  "NODE|12-lts",
  "NODE|10-lts",
  "NODE|10.1",
  "NODE|10.6",
  "NODE|10.14",
  "JAVA|8-jre8",
  "JAVA|11-java11",
  "TOMCAT|8.5-jre8",
  "TOMCAT|9.0-jre8",
  "TOMCAT|8.5-java11",
  "TOMCAT|9.0-java11",
  "JBOSSEAP|7.2-java8",
  "PHP|7.2",
  "PHP|7.3",
  "PHP|7.4",
  "PYTHON|3.8",
  "PYTHON|3.7",
  "PYTHON|3.6",
  "RUBY|2.5",
  "RUBY|2.6"
]
```
