### ISSUE TITLE
.xcresult file have zero code coverage

### ISSUE THREAD

**Issue by chinaysun** [microsoft/azure-pipelines-tasks#13897]
**Question, Bug, or Feature?**  
*Type*:  Question/Bug

**Enter Task Name**: Xcode@5

## Environment
Pool: Azure Pipelines
Image: macos-latest
Agent: Hosted Agent

Xcode 11.7

## Issue Description

The code coverage from the .xcresult file generated via the Xcode@5 is incorrect. 
The pipeline used to run well but recently start to occur this problem. Looks like it happens when try to merge new code to the dev branch after solved the `project.pbxproj` files conflicts.

It has been solved once, cherry pick the code and make a new branch to avoid `project.pbxproj` conflict happen. 

The unit test runs well on local machine and gives right code coverage. 
Using the samce  `xcodebuild` runs locally, it does not have the issue. Coverage is correct.

### Configuration

  - task: Xcode@5
    displayName: 'Xcode test'
    inputs:
      actions: 'test'
      configuration: 'Debug_${{ parameters.buildEnv }}'
      xcWorkspacePath: '$(Workspace)'
      scheme: 'Project_${{ parameters.buildEnv }}'
      xcodeVersion: 'specifyPath'
      xcodeDeveloperDir: '/Applications/Xcode_11.7.app'
      packageApp: false
      destinationPlatformOption: 'iOS'
      destinationSimulators: 'iPhone 11'
      args: '-enableCodeCoverage YES -derivedDataPath $(Build.BinariesDirectory)'

### Error logs

Task runs successfully, but exported artifacts (.xcresults) file does not have coverage.

**Comment by EzzhevNikita** [comment]
Hi @chinaysun, Could you please provide logs with enabled diagnostics for the pipeline run where this issue happens?

**Comment by chinaysun** [comment]
Hey @EzzhevNikita 

Thanks for reaching out. sorry for the late reply.

We eventually solved the problem by changing the Xcode version to 12.1.

Looks like there is some issue on running Xcode 11.7 on macOS 10.15 (which suppose to be the latest version).

**Comment by EzzhevNikita** [comment]
As this issue was resolved for you, I'm closing this ticket.
