### ISSUE TITLE
git clone does not work for Azure DevOps Dev17

### ISSUE THREAD

**Issue by kingwang-git** [microsoft/azure-pipelines-tasks#13904]
Hi,
Our DevOps is hosted on premise and the server version is Dev17.M153.5, which unfortunately does not support multiple repos in the YAML pipeline. While we are on the process of upgrading the Dev18, which may take months, we like to have the pipeline running for our project. So our pipeline is define as:

There are two repositories: **services** and **common**, which both are on the same DevOps project, and the yaml is on services repo:

steps:
  - checkout: self (Note: this is services repo and checkout call works fine) 
    clean: true
  - script:
      git clone http://<devops_url>/myproject/_git/common

The error from the run is:
Cloning into 'common'...
fatal: could not read **Username** for 'http://<devops_url>': terminal prompts disabled
##[error]Cmd.exe exited with code '128’

Our build agent pool and agents are all on premise. I suspect that this might be an agent config issue (connection server url and PAT used to connect back to the DevOps), but I am puzzled the first 'check self' works well, and I assume that internally the call is the 'git clone' as well.

Can someone shed a light on the issue above?

Thanks,
King

**Comment by damccorm** [comment]
Hey @kingwang-git this looks like an issue with the service, not a specific task. This repo is meant for issues/code for specific tasks, would you mind opening an issue at https://developercommunity.visualstudio.com/spaces/21/index.html - that will help get the right eyes on it.
