### ISSUE TITLE
YAML variable substitution

### ISSUE THREAD

**Issue by svrooij** [microsoft/azure-pipelines-tasks#13918]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: FileTransformV2

## Issue Description

It would be really nice if the FileTransform task would support variable substitution in YAML files. Like [this github action](https://github.com/microsoft/variable-substitution). also build by microsoft.

For some other use case we want to modify a yaml configfile based on some secrets and variables defined in the pipeline.

I already created an issue in the [issue tracker](https://github.com/microsoft/variable-substitution/issues/18) for the github action, but that wasn't the right place.

**Comment by svrooij** [comment]
This is still a vary much liked feature. Please don't close

**Comment by ben-burton** [comment]
This would be really useful for working with helm charts

**Comment by glloyd2010f** [comment]
Providing a bump on this to echo the point made by @ben-burton. Right now we are having to rely on the colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1 which doesn't seem to parse Key Vault secrets that well into files.

**Comment by anatolybolshakov** [comment]
Hi everyone, this repo is mostly for yaml templates; for in-the-box task - I would suggest to open a ticket in https://github.com/microsoft/azure-pipelines-tasks
