### ISSUE TITLE
Resource file has already set to /azure-pipelines-tasks-codecoverage-tools/module.json

### ISSUE THREAD

**Issue by aafnan10** [microsoft/azure-pipelines-tasks#13916]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
 Azure Pipelines

- Agent - Hosted or Private: 
    
Hosted VS2017

## Issue Description

 I'm getting warnings in all azure build pipelines on Gradle task regarding code coverage. Warning message which I'm getting is: 

`##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json`

### Task logs

[3_Build Automation Test.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5558459/3_Build.Automation.Test.txt)

### Error logs

`##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json`

**Comment by aafnan10** [comment]
Is there any updates on this issue. I'm still facing it.

**Comment by TheBishopOfSoho** [comment]
Im having this issue too, and for some reason Im seeing much longer build times which I assume is related as nothing else has changed from builds before this.

**Comment by aafnan10** [comment]
Yes, Gradle builds are taking longer time than expected.

**Comment by anatolybolshakov** [comment]
Hi @TheBishopOfSoho @aafnan10 could you please share your logs in debug mode?

**Comment by aafnan10** [comment]
[3_Build Automation Test.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5579327/3_Build.Automation.Test.txt)
Gradle build logs in debug mode.

**Comment by recintoit** [comment]
Hello, I also have experienced this.  A release pipeline was created on Monday and worked with no issue.  I ran it today and recieved the warning, but fails with error code exit 1.

**Comment by BrettThePark** [comment]
+1

**Comment by android-dataticket** [comment]
also getting 5 of these warnings each build now

**Comment by ludovicroland** [comment]
I am also facing this issue :)

**Comment by rforest42** [comment]
+ 1

**Comment by jiyoon-koo** [comment]
Same problem for me.
```
##[warning]Resource file has already set to: 
D:\a\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules
\azure-pipelines-tasks-artifacts-common\module.json
```

**Comment by lionerez1** [comment]
Same issue for me. It not only slow down the pipeline for me, the job also failing often and at retry passes..

**Comment by javi-additio** [comment]
Same issue for me.

`##[warning]Resource file has already set to: D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.178.0\node_modules\azure-pipelines-tasks-codecoverage-tools\module.json
##[warning]Resource file has already set to: D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.178.0\node_modules\azure-pipelines-tasks-codecoverage-tools\module.json
##[warning]Resource file has already set to: D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.178.0\node_modules\azure-pipelines-tasks-codecoverage-tools\module.json
##[warning]Resource file has already set to: D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.178.0\node_modules\azure-pipelines-tasks-codecoverage-tools\module.json
##[warning]Resource file has already set to: D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.178.0\node_modules\azure-pipelines-tasks-codecoverage-tools\module.json`

**Comment by adsurg** [comment]
+1

**Comment by sommmen** [comment]
Same issue here:

> Resource file has already set to: D:\a\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.1\node_modules\azure-pipelines-tasks-artifacts-common\module.json

`  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '${{ parameters.packagesToPack }}'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'NuGetPackageVersion'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Files'
      publishLocation: 'Container'`

**Comment by hensleyrob** [comment]
+1 to getting this error on the NuGet Authentication task.

**Comment by berndgoetz** [comment]
Same issues with with Gradle 6.7.1 build, Spring Boot 2.3.6:

##[warning]Resource file has already set to: /workspace/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /workspace/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /workspace/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /workspace/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /workspace/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json

**Comment by egor-bryzgalov** [comment]
This issue has been resolved for the Gradle task in 2.179 version. I'll let you know once the fix is available.

**Comment by Axemasta** [comment]
+1 Getting this warning from `NuGetAuthenticate@0`, Issue arose when I referenced a NuGet package from a private feed.

YAML:
```yaml
- task: NuGetAuthenticate@0
      inputs:
        nuGetServiceConnections: 'My Private Feed'
```

Warning:
```
##[warning]Resource file has already set to: /Users/runner/work/_tasks/NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b/0.179.1/node_modules/azure-pipelines-tasks-artifacts-common/module.json
```

Seeing massively increased build time, my build & test stage has gone from on average ~1m 30s to ~7m 0s

**Comment by jobertcodes** [comment]
+1 I'm getting these warnings when running a `Gradle` task:
```
pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'testCoverage'

```

**Comment by lukasztokarski-tomtom** [comment]
+1 for the gradle task I use
```
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
```
Gradle wrapper props set the desired gradle version:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

And the result is presented on the screenshot:
![AzurePipelineWarning](https://user-images.githubusercontent.com/72228632/104554872-2b09fa00-563d-11eb-9608-f4cb4728dbbf.png)

**Comment by egor-bryzgalov** [comment]
Hi!

**Comment by lukasztokarski-tomtom** [comment]
Hi @egor-bryzgalov ,

thank you for the update. 
How to bump up the version of that task used in my pipeline? In the logs of the initialization step I still can see: 
`Downloading task: Gradle (2.178.0)`

```
##[section]Starting: Initialize job
2021-01-14T07:54:30.4876060Z Agent name: 'Azure Pipelines 2'
2021-01-14T07:54:30.4876690Z Agent machine name: 'Mac-1610610577443'
2021-01-14T07:54:30.4877040Z Current agent version: '2.179.0'
2021-01-14T07:54:30.5742180Z ##[group]Operating System
2021-01-14T07:54:30.5742660Z Mac OS X
2021-01-14T07:54:30.5742890Z 10.15.7
2021-01-14T07:54:30.5743090Z 19H15
2021-01-14T07:54:30.5743300Z ##[endgroup]
2021-01-14T07:54:30.5743560Z ##[group]Virtual Environment
2021-01-14T07:54:30.5743850Z Environment: macos-10.15
2021-01-14T07:54:30.5744130Z Version: 20201212.1
2021-01-14T07:54:30.5744880Z Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20201212.1/images/macos/macos-10.15-Readme.md
2021-01-14T07:54:30.5745370Z ##[endgroup]
2021-01-14T07:54:30.5746760Z Current image version: '20201212.1'
2021-01-14T07:54:30.5748620Z Agent running as: 'runner'
2021-01-14T07:54:30.6630850Z Prepare build directory.
2021-01-14T07:54:30.8174090Z Set build variables.
2021-01-14T07:54:30.8217180Z Download all required tasks.
2021-01-14T07:54:30.8350320Z Downloading task: DownloadSecureFile (1.179.1)
2021-01-14T07:54:35.9031310Z Downloading task: Bash (3.179.0)
2021-01-14T07:54:37.9305530Z Downloading task: Gradle (2.178.0)
2021-01-14T07:54:41.7887210Z Downloading task: AppCenterDistribute (3.173.0)
(...)
```

**Comment by egor-bryzgalov** [comment]
@lukasztokarski-tomtom 
Do you use an on-premise Azure DevOps server?

**Comment by lukasztokarski-tomtom** [comment]
No, DevOps services.

**Comment by lukasztokarski-tomtom** [comment]
@egor-bryzgalov any hints from your side? 
Btw. today I have replace two `Bash@2` tasks with two `Gradle@2` task and the result is worrying:

1. Execution time is almost doubled
2. Instead of 5 aforementioned warnings I got 15 of those. It looks like 5 warnings per single gradle task.

My `Bash@2` tasks were executing just `./gradlew taskName`.

How could I start using the newly released version 2.180.0 of the Gradle task?

**Comment by egor-bryzgalov** [comment]
Hi @lukasztokarski-tomtom 

I'm sorry for the delay. We've faced some issues with the deployment. We are working on it now. The updated task is going to get available soon. I'll keep you posted.

**Comment by merric-rocketpartners** [comment]
We've had to remove all coverage reports here. Hard to deploy to prod when can't show leadership that services are covered.

**Comment by jenciso** [comment]
I noticed a new gradle task version (2.181) and the warning messages dissapeared, at least using 2.181 Agent version

![image](https://user-images.githubusercontent.com/2229964/105942711-888b4700-603e-11eb-962d-32a6f7d0a733.png)

**Comment by lukasztokarski-tomtom** [comment]
The same fix appeared on my side. No more warnings for Gradle Task. 
Thank you for fixing the problem!

**Comment by anatolybolshakov** [comment]
@lukasztokarski-tomtom sure!
We rolled out a fix for this issue at the moment - @aafnan10 @merric-rocketpartners @jenciso
Let me close this one - please let us know if it's still actual for you.
