### ISSUE TITLE
HelmDeploy not able to find chart using search pattern in yaml deploy stage

### ISSUE THREAD

**Issue by pierowman** [microsoft/azure-pipelines-tasks#13922]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadArtifact or HelmDeploy

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/pierowman/AKS/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=7&branch=master

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:   
Azure Pipelines
vmImageName: 'ubuntu-latest'

## Issue Description
HelmDeploy fails to find artifact by using the following pattern in chartpath in a yaml Deploy stage.
chartPath: '$(Pipeline.Workspace)/**/$(projectName)-*.tgz'
this is needed in order to dynamically find that artifact no matter what version it is.

Looking deeper:
The Download Artifacts task copies the artifact into the 
"[debug]downloadPath=/home/vsts/work/1/" directory which is equivalent to the value in $(Pipeline.Workspace).

This is expected according to documentation:
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#artifacts-in-release-and-deployment-jobs

HelmDeploy task allows a pattern to be set in the ChartPath but giving a pattern only searches the 
"[debug]findPath: '/home/vsts/work/1/s'" which is equivelent to $(System.DefaultWorkingDirectory) This is one directory down from the location Download Artifacts places the artifact.

This is also expected by documentation:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#upgrade-command

There seems to be a disconnect between what Download Artifact is doing and what HelmDeploy is doing.
IE: "/home/vsts/work/1/" artifact location != "/home/vsts/work/1/s" search directory

I have found two work arounds to this issue. 
1) create a copy task that copies the artifact from $(Pipeline.Workspace) into $(System.DefaultWorkingDirectory)
2) instead of naming my artifact "drop" merely name it "s" thereby forcing the artifact to land inside the $(System.DefaultWorkingDirectory)

both options require the chartpath to be:
chartPath: '$(System.DefaultWorkingDirectory)/**/$(projectName)-*.tgz'

Expected result would be that either pattern:
chartPath: '$(Pipeline.Workspace)/**/$(projectName)-*.tgz'
or
chartPath: '$(System.DefaultWorkingDirectory)/**/$(projectName)-*.tgz'

would work without needing the above workarounds

### Task logs

[logs_274.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5561701/logs_274.zip)

### Error logs

##[error]Can not resolve pattern in file path /home/vsts/work/1/**/sampleapp-*.tgz.

@ds-ms

**Comment by shigupt202** [comment]
@pierowman Can you please try with path `*/$(projectName)-*.tgz` or just `$(projectName)-*.tgz`?

**Comment by pierowman** [comment]
Both result in the same out come:

Download Artifact step
Downloaded drop/testapp-v0.2.0.tgz to /home/vsts/work/1/drop/testapp-v0.2.0.tgz

HelmDeploy step
chartPath: */$(projectName)-*.tgz

##[error]Can not resolve pattern in file path /home/vsts/work/1/s/*/testapp-*.tgz.



Download Artifact step
Downloaded drop/testapp-v0.2.0.tgz to /home/vsts/work/1/drop/testapp-v0.2.0.tgz

HelmDeploy step
chartPath: $(projectName)-*.tgz

##[error]Can not resolve pattern in file path /home/vsts/work/1/s/*/testapp-*.tgz.

**Comment by shigupt202** [comment]
This seems to be the expected behaviour as HelmDeploy task searches for the file patterns under `System.DefaultWorkingDirectory`. However, the artifacts are present one folder up. See [this](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/utils.ts#L41) for more information.
You can consider publishing the artifacts to `System.DefaultWorkingDirectory`, if you want to get rid of the extra step of copying from one folder to another.

**Comment by pierowman** [comment]
The Download artifact step is controlled by ADO and inserted automatically there is no configuration there that I'm aware of. 

As a work around I have named my drop folder 's' in the "PublishBuildArtifacts" step.

**Comment by shigupt202** [comment]
You can use `DownloadBuildArtifacts` to download the artifacts to desired location. Otherwise, copying the artifacts to `System.DefaultWorkingDirectory` also seems to be a valid workaround. 
We'll see if we can give an option to update the default working directory in task if this is something multiple customers would want. cc: @ds-ms
