### ISSUE TITLE
Tasks/KubernetesManifestV0 Fail on run

### ISSUE THREAD

**Issue by illay1994** [microsoft/azure-pipelines-tasks#13934]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Can't run task on linux

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - https://coopitdevelopment.visualstudio.com/coop-self-checkout/_build/results?buildId=101356&view=logs&j=67596015-9237-55f5-ce70-066616aaa2f5&t=9d4040ad-2019-5e4f-2b9d-cdd93c1d97e8

- Agent - Hosted 
    
    - ubuntu-latest

## Issue Description

Starting: Bake manifests
==============================================================================
Task         : Deploy to Kubernetes
Description  : Use Kubernetes manifest files to deploy to clusters or even bake the manifest files to be used for deployments using Helm charts
Version      : 0.178.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-k8s-manifest-tsg
==============================================================================
##[error]ENOENT: no such file or directory, chmod ''
Finishing: Bake manifests

**Comment by illay1994** [comment]
I think it is related to commit 
https://github.com/microsoft/azure-pipelines-tasks/commit/dd0d2b0d936fe44821f202e4fd34dd5fdf438b4d

**Comment by illay1994** [comment]
Look like fixed in PR 
https://github.com/microsoft/azure-pipelines-tasks/pull/13915
Please release to  prod

**Comment by ds-ms** [comment]
The release for this fix is in progress. 😄

**Comment by shigupt202** [comment]
The fix has been deployed.

**Comment by illay1994** [comment]
@ds-ms and @shigupt202 Thanks

**Comment by celambert** [comment]
We continue to see this issue on 0.178.0

```
##[debug]check path : /home/vsts/work/_tasks/KubernetesManifest_dee316a2-586f-4def-be79-488a1f503dfe/0.178.0/task.json
##[debug]adding resource file: /home/vsts/work/_tasks/KubernetesManifest_dee316a2-586f-4def-be79-488a1f503dfe/0.178.0/task.json
##[debug]system.culture=en-US
##[debug]check path : /home/vsts/work/_tasks/KubernetesManifest_dee316a2-586f-4def-be79-488a1f503dfe/0.178.0/node_modules/azure-pipelines-tasks-kubernetes-common-v2/module.json
##[debug]adding resource file: /home/vsts/work/_tasks/KubernetesManifest_dee316a2-586f-4def-be79-488a1f503dfe/0.178.0/node_modules/azure-pipelines-tasks-kubernetes-common-v2/module.json
##[debug]system.culture=en-US
##[debug]action=bake
##[debug]renderType=helm
##[debug]KUBECONFIG=
##[debug]task result: Failed
##[error]ENOENT: no such file or directory, chmod ''
##[debug]Processed: ##vso[task.issue type=error;]ENOENT: no such file or directory, chmod ''
##[debug]Processed: ##vso[task.complete result=Failed;]ENOENT: no such file or directory, chmod ''

```
