### ISSUE TITLE
PublishTestResults V2 task: What is the best way to report on retried tests

### ISSUE THREAD

**Issue by iansul** [microsoft/azure-pipelines-tasks#13945]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: 
PublishTestResultsV2

## Environment
Server

## Issue Description
I'm publishing a "hand-rolled" NUnit v2 results file, that my custom testing tool generates.

When a tests fails, after retry, the results file contains multiple \<failure\> elements under the \<test-case\> element, one for each failed attempt, but when I publish that NUnit result file I only see the first failure in the Azure Dev Ops UI in the Debug tab. What is the best way to see all of the failures? 

I see that the task is mostly a shell that calls an EXE, if there is a better place to post this question please let me know.

**Comment by vivek425ster** [comment]
@iansul This is the desired behaviour. We only get the first failure inside the testcase for displaying in the UI.
If you want more help, can you please share your xml file.

**Comment by suyash691** [comment]
@iansul Is the issue resolved for you?
