### ISSUE TITLE
HelmDeploy@0 requires connectionType defined when using envrionment resources that are not AKS

### ISSUE THREAD

**Issue by Justin-DynamicD** [microsoft/azure-pipelines-tasks#13947]
## Required Information

When using an en envrionment role that points to a generic kubernetes cluster (tested with AWS EKS), HelmDeploy@0 will require you to declare the `ConnectionType`.  According to all documentation, this should be unnesisary as the resource already contains this information.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy@0

## Environment
- Server - Azure Pipelines
    
    - https://dev.azure.com/itscocloud/TMS%20Flight
    - pipeline: TMS Flight Deploy
    - sample build number: #20201120.2

Actual error message:

```
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.178.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
##[error]Error: Input required: kubernetesServiceEndpoint
```

Same job after defining ConnectionType (note I did **NOT** define the endpoint, instead merely `connectionType` and set to `Kubernetes Service Connection`)

```
==============================================================================
Task         : Package and deploy Helm charts
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
Version      : 0.178.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-tsg
==============================================================================
/usr/local/bin/helm upgrade --namespace flight --install --values /azp/agent/_work/2/s/environments/dev/helm.yml --set image.tag=1.1.30 --wait main /azp/agent/_work/2/s/resources/flight
Release "main" has been upgraded. Happy Helming!
NAME: main
LAST DEPLOYED: Fri Nov 20 20:34:35 2020
NAMESPACE: flight
STATUS: deployed
REVISION: 3
/usr/bin/kubectl cluster-info
Kubernetes master is running at https://<redacted>/
CoreDNS is running at https://<redacted>
```

While this still works, the behavior deviates from documentaiton that states its unnessisary when using envrionment resources.

**Comment by shigupt202** [comment]
@Justin-DynamicD Can you please confirm whether you created a kubernetes resource in the environment and referred that in the pipeline, like this `<environment-name>.<resource-name>`?  Please share that part of the pipeline where you have specified the environment.

**Comment by shigupt202** [comment]
Closing stale issue. Feel free to reopen if more clarification is needed or the problem still exists.
