### ISSUE TITLE
DotNetCoreCLI dotnet pack task with /p:OutputPath

### ISSUE THREAD

**Issue by ankushbindlish2** [microsoft/azure-pipelines-tasks#13944]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  Question
*Type*: How to use OutputPath in the following yaml snippet ?

 - task: DotNetCoreCLI@2
            displayName: 'Services: Pack'
            inputs:
              command: 'pack'
              packagesToPack: '$(ServicesSolution)'
              packDirectory: '$(PackageOutput)'
              nobuild: true
              includesymbols: false
              versioningScheme: 'byBuildNumber'
              verbosityPack: 'Normal'
              **arguments: '/p:OutputPath=$(ServicesBuildOutput)'**

**Enter Task Name**: DotNetCoreCLI@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
Starting: Foundation: Pack (windows_build_container)
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\__t\dotnet\dotnet.exe pack C:\__w\1\s\src\Foundation.sln --output C:\__w\1\s\out\packages --no-build /p:Configuration=Release --verbosity Normal
Microsoft (R) Build Engine version 16.7.1+52cd83677 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/20/2020 5:25:42 PM.
     1>Project "C:\__w\1\s\src\Foundation.sln" on node 1 (pack target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Any CPU".
     1>Project "C:\__w\1\s\src\Foundation.sln" (1) is building "C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj" (2) on node 1 (pack target(s)).
     2>Project "C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj" (2) is building "C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj" (2:2) on node 1 (_GetBuildOutputFilesWithTfm target(s)).
     2>PrepareForBuild:
         Creating directory "bin\Release\netstandard2.0\".
     2>Done Building Project "C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj" (_GetBuildOutputFilesWithTfm target(s)).
     2>C:\__t\dotnet\sdk\3.1.404\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\bin\Release\netstandard2.0\StorageFiles.Foundation.Diagnostics.dll' to be packed was not found on disk. [C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj]
     2>Done Building Project "C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj" (pack target(s)) -- FAILED.
     1>Done Building Project "C:\__w\1\s\src\Foundation.sln" (pack target(s)) -- FAILED.

Build FAILED.

       "C:\__w\1\s\src\Foundation.sln" (pack target) (1) ->
       "C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj" (pack target) (2) ->
       (GenerateNuspec target) -> 
         C:\__t\dotnet\sdk\3.1.404\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5026: The file 'C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\bin\Release\netstandard2.0\StorageFiles.Foundation.Diagnostics.dll' to be packed was not found on disk. [C:\__w\1\s\src\Foundation\StorageFiles.Foundation.Diagnostics\StorageFiles.Foundation.Diagnostics.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.86
##[error]Error: The process 'C:\__t\dotnet\dotnet.exe' failed with exit code 1
##[error]An error occurred while trying to pack the files.
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
Finishing: Foundation: Pack (windows_build_container)

**Comment by armanik11** [comment]
I'm not quite sure but can you try this?

  arguments:         
            -OutputPath $(ServicesBuildOutput)
