### ISSUE TITLE
Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.1) SDK/Runtime along with 2.1.

### ISSUE THREAD

**Issue by algarciatech** [microsoft/azure-pipelines-tasks#13943]
![image](https://user-images.githubusercontent.com/74774814/99807312-41ad3c80-2b37-11eb-9a52-3da59adcb97c.png)

Hello, I am trying to make automatic deployments our portal is in .net core 2.2 but when I install it I get the following error

![image](https://user-images.githubusercontent.com/74774814/99807274-30fcc680-2b37-11eb-8ec9-43fd9ba499c1.png)

I have tried applying the global.json to apply that version but it has not worked either, the yml is this:

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  netversion: '2.2.402'

steps:

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 2.2.402'
  inputs:
    version: $(netversion)
    includePreviewVersions: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  inputs:
    command: restore   
    projects: '**/*.csproj'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'artefacto'
  condition: succeededOrFailed()

**Comment by anatolybolshakov** [comment]
Hi @algarciatech I'm closing it due to inactivity at the moment - please let us know if it still actual for you.
