### ISSUE TITLE
Question - resolving the serviceUri

### ISSUE THREAD

**Issue by temelj** [microsoft/azure-pipelines-tasks#13955]
I hope it is appropriate that I ask a very specific question.

I have looked at this function and observed (from our build pipeline for our organisation) that it always returns the older (legacy?) uri - https://tenant.visualstudio.com/ instead of the newer uri https;//dev.azure.com/tenant/

https://github.com/microsoft/azure-pipelines-tasks/blob/f596b2a08daf83574fea0861f7a4c76b3eda4fa7/Tasks/Common/packaging-common/locationUtilities.ts#L30

Is this known and expected behavior? 
The result from this resolving the older/legacy uri is that further in the pipeline it uses https://tenant.pkgs.visualstudio.com/ and https://tenant.pkgs.visualstudio.com/_apis/Location for certain pipeline tasks such as nuget restore.

**Comment by IanBFarrell** [comment]
I am running into a issue that may be related in Azure DevOps Tasks. When the npm task is run, some times it works and others it fails with a error of "##[error]TypeError: Cannot read property 'locationServiceData' of null" when I set system.debug to true, it gives me information about being unable to get packaging URIs (debug details below). Could this all be related?

##[debug]Acquiring Packaging endpoints...
##[debug]Successfully acquired the connection data
##[debug]Unable to get packaging URIs
##[debug]Cannot read property 'locationServiceData' of null
##[debug]TypeError: Cannot read property 'locationServiceData' of null
    at Object.<anonymous> (/opt/novapps/adb/agent-04-vx008817/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.179.1/node_modules/packaging-common/locationUtilities.js:96:50)
    at next (native)
    at fulfilled (/opt/novapps/adb/agent-04-vx008817/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.179.1/node_modules/packaging-common/locationUtilities.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
