### ISSUE TITLE
How to get a PR TargetBranch in YAML when using another pipeline as resource and trigger

### ISSUE THREAD

**Issue by radujipa** [microsoft/azure-pipelines-tasks#13968]
Hi!

I'm trying to figure out how to pass `System.PullRequest.TargetBranch` from one YAML pipeline to another when the first is triggered via a pull request. There doesn't seem to be any [pipeline resource variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#pipeline-resource-variables) for this.

Example:
 - [CI pipeline YAML](https://github.com/radujipa/azure-pipelines-experiments/blob/testing-prs/azure-pipelines-ci.yml#L23) and [build logs](https://dev.azure.com/radujipa/Azure%20Pipelines%20Experiments/_build/results?buildId=12&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=14)
 - [CD pipeline YAML](https://github.com/radujipa/azure-pipelines-experiments/blob/testing-prs/azure-pipelines-cd.yml#L31) and [build logs](https://dev.azure.com/radujipa/Azure%20Pipelines%20Experiments/_build/results?buildId=13&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=22)

If there isn't a straightforward way to do this, I think it'd be a useful feature to extend a [resource pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines) with. In the meantime, I'm interested in possible workarounds and would very much appreciate any help.

**Comment by damccorm** [comment]
Hey @radujipa this looks like an issue with the Azure Pipelines service, not a specific task. This repo mostly houses issue/code for the tasks themselves, could you please open a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html? That will help get the right eyes on it
