### ISSUE TITLE
Track additional environment variables for Java tasks

### ISSUE THREAD

**Issue by maxim-lobanov** [microsoft/azure-pipelines-tasks#13973]
## Note  
Currently, there are a bunch of tasks that you `javacommon` to publish telemetry:
- https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ANTV1/anttask.ts#L233
- https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/GradleV2/gradletask.ts#L152
- https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV2/maventask.ts#L114
- https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV3/maventask.ts#L117
- https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/XamarinAndroidV1/xamarinandroid.ts#L39

All these tasks use `publishJavaTelemetry` function from [java-common.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/java-common/java-common.ts#L147).
I see two issues with this function:
1) it is duplicate https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/utility-common-v2/telemetry.ts#L13
2) It doesn't publish additional environment variables

I suggest to get rid of `publishJavaTelemetry` and switch all tasks to `emitTelemetry`

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature 

## Environment
Azure Pipelines

**Comment by anatolybolshakov** [comment]
Reopened since it's still actual
