### ISSUE TITLE
Track "ImageOS" variable to telemetry

### ISSUE THREAD

**Issue by maxim-lobanov** [microsoft/azure-pipelines-tasks#13972]
## Note  
Some tasks track telemetry for inputs and usage.
They use different methods for that:
1) https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/artifacts-common/telemetry.ts#L10
2) https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/java-common/java-common.ts#L147
3) https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/utility-common-v2/telemetry.ts#L13
4) https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/utility-common/telemetry.ts#L13
5) https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/utility-common-v2/telemetry.ts

All these methods track a bunch of environment variables. I suggest adding one more environment variable `ImageOS`.
This variable is set only on Hosted images and contains detailed information about image like `ubuntu1604`, `ubuntu2004`, `macos1015`, `macos1014`. The current telemetry is a bit unclear because it is not clear what image telemetry come from.

How it is set on image level: https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/configure-environment.sh#L5

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Feature

**Task**: All tasks that publish telemetry

## Environment
- Azure Pipelines

**Comment by anatolybolshakov** [comment]
Reopened since it's still actual
