### ISSUE TITLE
Gradle v2 FindBugs plugin has been removed and deprecated in Gradle v6 or higher

### ISSUE THREAD

**Issue by SqueedWalz** [microsoft/azure-pipelines-tasks#13980]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle v2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - Pipeline: https://dev.azure.com/HM-GROUP/SOAM-Entrance/_build/results?buildId=195510&view=results

- Agent - Hosted: 
    - Ubuntu 16.04

## Issue Description

When running a gradle.build (Gradle version 6 or higher) with FindBugs plugin an error is thrown due to it has been deprecated and removed, replacement suggestion is SpotBugs plugin.

https://docs.gradle.org/current/userguide/upgrading_version_5.html, search for "FindBugs" and you will see the deprecated plugin information.

There is one more error (related to Jacoco) in the logs, which is tracked in this issue here, [Gradle v2 Jacoco code coverage is broken
#12593](https://github.com/microsoft/azure-pipelines-tasks/issues/12593).

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[logs.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5603259/logs.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
A problem occurred configuring root project 'projectName'.
Plugin with id 'findbugs' not found.
...
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'findbugs' not found.
...
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
```

**Comment by SqueedWalz** [comment]
@anatolybolshakov Any update about when this might be fixed and available?

**Comment by anatolybolshakov** [comment]
Hi @SqueedWalz currently we are working on more prioritized issues, we are planning to handle this in the near time.
Please feel free to contribute also here!

**Comment by daniel-walz** [comment]
Any update about when you might pick this one up?

**Comment by vladislav-ryzhov** [comment]
Hi @SqueedWalz
A fix for this issue has been added and will be available within 4 weeks.
I'll let you know when it's deployed.
Related PR: https://github.com/microsoft/azure-pipelines-tasks/pull/14625

**Comment by SqueedWalz** [comment]
> Hi @SqueedWalz
> A fix for this issue has been added and will be available within 4 weeks.
> I'll let you know when it's deployed.
> Related PR: #14625

Thanks :)

**Comment by vladislav-ryzhov** [comment]
Hi @SqueedWalz  we have rolled out related changes.

**Comment by vladislav-ryzhov** [comment]
Let me close it at the moment since it's resolved - please let us know if you have any further questions!

**Comment by SqueedWalz** [comment]
Thanks! Seems to work now
