### ISSUE TITLE
Bug: DotNetCoreCLI@2 task couldn't finish

### ISSUE THREAD

**Issue by ezavgorodniy** [microsoft/azure-pipelines-tasks#13982]
Our task is failing after timeout

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'ProjectName/src/**/*Tests/*.csproj'
    arguments: '--configuration Release --settings "$(Build.SourcesDirectory)/ProjectName/src/test.runsettings" --collect "Code coverage" --logger trx --filter "Category!=Integration&Category!=Functional&Category!=spec"'

After all of tests passed it's publishing the test result and then hanging on forever until timeout:

##[debug]Leaving PublishToNewTestRunPerTestResultFileAsync
##[debug]RESOURCE_URIS:
##[debug]Setting task variable METADATA_30c34cfb-5f18-4155-8c47-14ccea924944: {"name":"01e7cc7c-6719-4a49-88ff-9b37bcc6f734","resourceUris":[],"metadata":{"description":"","relatedUrls":[{"url":"https://ivanti.visualstudio.com/Uno/_build/results?buildId=617862","label":"pipeline-url"}],"humanReadableName":"Test Results from Publish Test Results utility","serializedPayload":"{\"testId\":\"PublishTestResults\",\"testTool\":\"VSTest\",\"testResultAttestation\":{\"total\":2328,\"failed\":0,\"passed\":2328,\"skipped\":0},\"testDurationSeconds\":0.0,\"testPassPercentage\":\"100\",\"relatedUrls\":[{\"url\":\"https://ivanti.visualstudio.com/Uno/_build/results?buildId=617862\",\"label\":\"pipeline-url\"}]}"}} 
##[debug]Re-evaluate condition on job cancellation for step: 'DotNetCoreCLI'.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.

**Comment by bishal-pdMSFT** [comment]
@phanikmmsft @ShreyasRmsft can you please look at this test command related issue

**Comment by ezavgorodniy** [comment]
Actually we found the problem. Problem with Mongo2Go runner wasn’t disposed, so we’ve just made our class IDisposable and clean up after ourselves. 

Sorry, was confused with messaging. Perhaps better messaging may help others in a future to troubleshoot this sort of issues
