### ISSUE TITLE
BUG-Deploy-azure

### ISSUE THREAD

**Issue by dasuma** [microsoft/azure-pipelines-tasks#13990]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:Error: Error: Resource xxxx doesn't exist.

**Enter Task Name**: webdeploy with workflow  webapps

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: zuama.azurecr.io
        username: ${{ secrets.acr_zuama_username }}
        password: ${{ secrets.acr_zuama_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile.velez" -t zuama.azurecr.io/velezlogme-img:${{ github.sha }}
        docker push zuama.azurecr.io/velezlogme-img:${{ github.sha }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with: 
        app-name: velez-logme
        app-settings-json: | 
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "zuama.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ secrets.acr_zuama_username }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ secrets.acr_zuama_password }}",
              "slotSetting": false
            }            
          ]
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: velez-logme
        images: zuama.azurecr.io/velezlogme-img:${{ github.sha }}

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

i have some webapps, with the same repository, i configured the webdeploy with work worflow, the firts time working when i add the second workflow, the first failed and it said that my webapps dont exist

![image](https://user-images.githubusercontent.com/7833341/100521122-b7d12500-316f-11eb-9b2f-92ff5ee72931.png)

![image](https://user-images.githubusercontent.com/7833341/100521103-9f610a80-316f-11eb-8ae0-7d6a1b45dce8.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Run Azure/appservice-settings@v1
Got service connection details for Azure App Service: velez-logme
***
Error: Error: Resource velez-logme doesn't exist.

**Comment by AmrutaKawade** [comment]
this is not right place to raise this issue. Can you raise issue on this repo https://github.com/Azure/appservice-settings? 

Also can you check if your RBAC (AZURE_CREDENTIALS) has proper access. https://github.com/Azure/appservice-settings#configure-github-secrets-with-azure-credentials-app-settings-and-connection-strings. 

Closing this issue. check above solution. if it doesn't work raise issue on above mentioned repo
