### ISSUE TITLE
AzureKeyVaultV1 does not retry in the event of transient network troubles

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-tasks#13998]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureKeyVault

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure pipelines.
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account: dnceng
Project: internal
Build Definition name: dotnet-runtime-internal
Build #: 899915

- Agent - Hosted or Private: 
    
    - Private.   Windows 10 20H1 Client

## Issue Description

All our stuff runs in Azure, and lately there have been various Azure blips and DNS issues.  The code that tries to access the key vault doesn't have any retries in it. leading to logging like:

```
Downloading secret value for: <SecretName>.
##[error]
<SecretName>: "getaddrinfo EAI_AGAIN login.windows.net login.windows.net:443"
```

### Error logs

Please feel free to contact me directly; cannot share on GitHub.  .  I can't provide logs for Azure DevOps builds using this task because it uses secrets.

The error looks like this:
```
Starting: Download secrets: <VaultName>
==============================================================================
Task         : Azure Key Vault
Description  : Download Azure Key Vault secrets
Version      : 1.175.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-key-vault
==============================================================================
SubscriptionId: 68672ab8-de0c-40f1-8d1b-ffb20bd62c0f.
Key vault name: <VaultName>.
Downloading secret value for: <SecretName>.
##[error]
<SecretName>: "getaddrinfo EAI_AGAIN login.windows.net login.windows.net:443"
Finishing: Download secrets: <VaultName>

```

**Comment by tauhid621** [comment]
Closing the issue.
PR : #14135
