### ISSUE TITLE
Display Detailed ARM template deployment tasks error messages within task execution output

### ISSUE THREAD

**Issue by glloyd2010f** [microsoft/azure-pipelines-tasks#13997]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: Feature

**Enter Task Name**: AzureResourceGroupDeploymentV2 and AzureResourceManagerTemplateDeploymentV3

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3

## Environment
- Server
  - Azure Pipelines

- Agent - Hosted or Private:
    - Private Agent (Windows and Linux)
      - Agent Version: Between 2.165.1 and 2.177.1

## Issue Description

As a pipeline developer for my company, I am looking for a way to get the direct export of ARM Template Deployment Error Messages within the pipeline output.

Based on my research we would be looking at constructing an "If" based task that would execute when a ARM Template fails to deploy, which would provide the Operation Details from the actual deployment.

The information I am looking to gather from the Azure Portal would be similar to the JSON below.

```
{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplate",
        "message": "Deployment template validation failed: 'The provided value for the template parameter 'parameterName' at line '21' and column '21' is not valid. Length of the value should be less than or equal to '13'. Please see https://aka.ms/arm-template/#parameters for usage details.'.",
        "additionalInfo": [
            {
                "type": "TemplateViolation",
                "info": {
                    "lineNumber": 21,
                    "linePosition": 21,
                    "path": "parameters.parameterName.maxLength"
                }
            }
        ]
    }
}
```

```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "NotFound",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourceNotFound\",\r\n    \"message\": \"The Resource 'Microsoft.AppConfiguration/configurationStores/resourceName' under resource group 'resourceGroupName' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"\r\n  }\r\n}"
            }
        ]
    }
}
```

Currently when we get errors like this (singular or multiple) they show up in Azure DevOps like the below.

```
##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
##[error]Details:
##[error]DeploymentFailed: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
```

I don't believe someone should have to access the Azure Portal to determine why their resource deployment failed. Having this information displayed would help create a simplified troubleshooting process.

I would propose either enabling this as the default action for failed deployed or a boolean that can be enabled for those that do not want the extra noise in their pipeline process. Additionally having this output to a pipeline variable would be extremely help as well.

### Task logs
n/a - feature request

## Troubleshooting
n/a - feature request

### Error logs
n/a - feature request

**Comment by bishal-pdMSFT** [comment]
@glloyd2010f the task should be printing the error in some level of details. user needs to go to Azure portal only if they need more inner details of error. Can you please attach the task logs?

**Comment by glloyd2010f** [comment]
@bishal-pdMSFT there are times where it will publish the error message, but it seems like that is limited to when there is only one error. What we are seeing on the run in the attached log is where there are multiple errors.

**Error Message**
![image](https://user-images.githubusercontent.com/36274646/102223276-7b613100-3eb2-11eb-9784-3c4062c1cf16.png)

**Deployment Log**
[armTemplateV3_DeploymentLog_MultipleErrors.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5696320/armTemplateV3_DeploymentLog_MultipleErrors.txt)

**Comment by glloyd2010f** [comment]
@bishal-pdMSFT any update on this?

**Comment by basilin** [comment]
any update on this ?

**Comment by dhtek** [comment]
+1 - Since I don't have access to the resource group, I can't view the errors myself and need to ask someone with access to retrieve them for me.

**Comment by michaelsamoilenko** [comment]
+1. It's very annoying since having generic message about deployment failure gives no clue and every time you had to locate relevant deployment failure in azure
