### ISSUE TITLE
Cache Task giving permissions error

### ISSUE THREAD

**Issue by ngarg-panw** [microsoft/azure-pipelines-tasks#14006]
**Question**  
*Type*: Release Pipeline

**Enter Task Name**: Cache Task  

## Environment
- Server - Azure Pipelines ?
    
## Issue Description
 In my extension, I am downloading an executable everytime a pipeline runs. So, to avoid that I thought of using the Cache task. I defined my task as follows:

`steps:
- task: Cache@2
  displayName: Cache
  inputs:
    key: 'twsictli | $(Agent.OS) '
    path: 'twistcli-scan'
    cacheHitVar: 'TWISTCLI_RETRIEVED'
  continueOnError: true`

And in my extension code I plan to check the value of 'TWISTCLI_RETRIEVED' to decide whether or not to download the executable. If its true, then no need to download.

But when the cache task executes, I am getting the following exception:
`2020-12-02T01:21:47.4794368Z ##[error]Access Denied: Microsoft.TeamFoundation.ServiceIdentity;52867c9c-da85-4427-87e5-f4ea13da51a4:Build:ac4ff7ab-7c76-49ef-b741-04be121ffb0b needs the following permission(s) on the resource $ to perform this action: Read pipeline cache entries
`
I couldn't find any related permissions. Pls suggest.

**Comment by johnterickson** [comment]
Is this on a release or not on Git? It looks like it can’t find the branch name.

**Comment by ngarg-panw** [comment]
Its on a release.
I have 2 task in that release, 
Cache and "Prisma Cloud Compute Scan" which is the. extension I am using. 
There is no git or repo involved.
<img width="1190" alt="Screen Shot 2020-12-02 at 9 28 09 AM" src="https://user-images.githubusercontent.com/54907685/100908779-bd38b300-3480-11eb-8404-edc518e44fdd.png">

**Comment by ngarg-panw** [comment]
Does the Cache Task need to be on a git. In my task, i am making an API call to download an artifact which i would like to reuse in the subsequent pipeline executions.Is this not the right way?

**Comment by sdipesh** [comment]
I am also facing similar issue. I am trying to create a release pipeline with only one Cache task having a path pointing to build pipeline drop folder. When I execute the release pipeline it is giving access denied error. Not able to find resolution. Please help.

![image](https://user-images.githubusercontent.com/40672740/101065434-27c21f80-3563-11eb-84ea-2248ae2591c7.png)
![image](https://user-images.githubusercontent.com/40672740/101065532-432d2a80-3563-11eb-8b35-5426e41f7f0c.png)

**Comment by sdipesh** [comment]
I found that cache task is not supported by classic release pipelines. Please ignore my query.

**Comment by ngarg-panw** [comment]
@sdipesh Can you pls elaborate more. What other type of release pipeline do I need to create to take advantage of cache task?

**Comment by sdipesh** [comment]
In Azure DevOps, you have to create a yml pipeline and use the cache task within the pipeline. It works in yml pipelines but not classic pipelines.

**Comment by ngarg-panw** [comment]
This makes sense. Thanks for your answer. I am unblocked.
