### ISSUE TITLE
Available Az module versions in Azure Powershell@4 task

### ISSUE THREAD

**Issue by wembleyford** [microsoft/azure-pipelines-tasks#14010]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzurePowershell@4  

## Environment

Azure devops Pipelines.
    
## Issue Description

There appears to be a bug in the az module that is only exposed when running in Azure Devops pipelines. 
See:  
https://github.com/Azure/azure-powershell/issues/13425

It has been suggested that this bug no longer occurs with the az module version 5.0 or 5.1.0. However, these do not appear to be available via the hosted MS service.

Furthermore the documentation, at 
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops

Suggests v, 3.5.0 is the highest available, though setting TargetAzurePs to 'latestVersion' appears to install 4.7.0

Attempting to select 5.0.0 or 5.1.0 gives me an invalid module error. Is there a way I can use the az module v 5.1.0 to alleviate this bug in in the module when running in Azure Pipelines?

Thanks

**Comment by nadesu** [comment]
@chshrikh - pls take a look

**Comment by chshrikh** [comment]
@wembleyford today hosted agent does not have support for 5.0.0 or 5.1.0 support, if you are blocked on this, you can opt to set-up your own agent for now.

Thanks for pointing out stale doc issue, we will update the doc.

**Comment by allantargino** [comment]
Hi all,
I faced the same situation. As per [this comment](https://github.com/microsoft/azure-pipelines-tasks/issues/14160#issuecomment-753782049) on #14160,  we don't need private agents and a simple step installing the desired version should be enough.

> For Linux:
> `Save-Module -Path /usr/share/az_5.3.0 -Name Az -RequiredVersion 5.3.0 -Force -ErrorAction Stop`
> For Windows:
> `Save-Module -Path $env:SystemDrive\Modules\az_5.3.0 -Name Az -RequiredVersion 5.3.0 -Force -ErrorAction Stop`

**Comment by AmrutaKawade** [comment]
@ninallam can you check this document update request?
