### ISSUE TITLE
Export a task to YAML is not working

### ISSUE THREAD

**Issue by NatGra** [microsoft/azure-pipelines-tasks#14036]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: confirmed with bash v3, helm v0, docker v1, .NET Core v2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

## Issue Description
When trying to export the YAML representation of a pipeline task via the Azure DevOps feature "**View YAML**"
<img width="239" alt="grafik" src="https://user-images.githubusercontent.com/10546494/101345621-9bc43680-3887-11eb-8bfd-e7f7e70f3970.png">

The error message apprears that this functionality has been moved to the three-dots-menu
<img width="515" alt="grafik" src="https://user-images.githubusercontent.com/10546494/101345668-ae3e7000-3887-11eb-99a4-6793a1f19591.png">

But this menu does not contain the related functionality
<img width="293" alt="grafik" src="https://user-images.githubusercontent.com/10546494/101345736-cb733e80-3887-11eb-9c81-53e60c7d1c48.png">

This seems to be related to these questions from the community:
- https://developercommunity.visualstudio.com/content/problem/1278749/in-release-pipelines-view-yaml-functionality-has-b.html
- https://developercommunity.visualstudio.com/content/problem/401239/import-yaml-generated-from-exporting-yaml-for-a-pi.html

**Comment by damccorm** [comment]
Hey @NatGra - this looks like an issue related to the service, not the tasks in this repo, so the developer community tickets are probably better for tracking. I'm going to close here, lets use those tickets as the source of truth for updates
