### ISSUE TITLE
Deployment for ARM templates (AzureResourceManagerTemplateDeployment) breaks when switched on HostedAgent from 3.176.0 to 3.179.0

### ISSUE THREAD

**Issue by JensSuessmeyer** [microsoft/azure-pipelines-tasks#14051]
When running a deployment through major version 3 in a MSFT Hosted Agent, execution is broken when apparantly versions changed from 3.176.0 to 3.179.0 for a deyployment of a template for ""type": "microsoft.insights/scheduledqueryrules",":

2020-12-08T07:00:19.3543526Z ##[error]The request content was invalid and could not be deserialized: 'Could not find member 'description' on object of type 'TemplateResource'. Path 'properties.template.resources[0].description', line 1, position 485.'.

When running the template with appropriate values locally in ISE, the execution runs successfully and objects are created.

The template type itself does not have the description under the mentioned hierarchy as a mandatory property (properties.template.resources[0].description):

https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/scheduledqueryrules

`{
  "name": "string",
  "type": "microsoft.insights/scheduledQueryRules",
  "apiVersion": "2018-04-16",
  "location": "string",
  "tags": {},
  "properties": {
    "description": "string",
    "enabled": "string",
(...)
`

**Comment by anatolybolshakov** [comment]
Hi @JensSuessmeyer this seems to be related to [last changes](https://github.com/microsoft/azure-pipelines-tasks/pull/13870/files) for AzureResourceManagerTemplateDeployment  task, not the agent.
@bishal-pdMSFT @anuragc617 could you take a look?

**Comment by bishal-pdMSFT** [comment]
@JensSuessmeyer can you please provide [debug ](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops) logs

**Comment by JensSuessmeyer** [comment]
Hi, 

I attached the debug log for the failing alert rule.

[AlertRuleLog.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5684390/AlertRuleLog.txt)

**Comment by kanika1894** [comment]
Hey @JensSuessmeyer ,
Can you please share the repective template? As I am facing difficulties to repro.

**Comment by JensSuessmeyer** [comment]
Hi, I attached the template.


[DTL_InternalAPI_500Errors.json.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5714971/DTL_InternalAPI_500Errors.json.txt)

**Comment by kanika1894** [comment]
I am able to repro the issue with the template, though faced no issues with another template.
To verify whether it's a template related issue, I cross-checked using az cli and face the same error.
![image](https://user-images.githubusercontent.com/58769601/102603392-ba101900-4148-11eb-9cf2-06db8964640b.png)
It seems that a fix is required on the template end.

**Comment by kanika1894** [comment]
As discussed with @JensSuessmeyer, as it was a template issue, closing this issue.

**Comment by JensSuessmeyer** [comment]
After swapping and validating the template again, execution worked. Probably not a problem of the execution engine but the template. Thanks @kanika1894 and @bishal-pdMSFT for the support!
