### ISSUE TITLE
Azure IoT Edge - Deploy to IoT Edge devices failed (if DTR is not accessible from cloud)

### ISSUE THREAD

**Issue by alaendle** [microsoft/azure-pipelines-tasks#14052]
## Required Information

*Type*: Question
**Enter Task Name**: Azure IoT Edge - Deploy to IoT Edge

## Environment
- Cloud Azure-DevOps
- Agent - Hosted

## Issue Description

Task fails if deployment manifest contains images that aren't available to the deployment agent, because they reside inside a private DTR that is only available within the enterprise network (and is not accessible from the public internet).

### Task logs

```
2020-12-09T12:53:58.1191315Z ##[section]Starting: Azure IoT Edge - Deploy to IoT Edge devices
2020-12-09T12:53:58.1504971Z ==============================================================================
2020-12-09T12:53:58.1505693Z Task         : Azure IoT Edge
2020-12-09T12:53:58.1506244Z Description  : Build and deploy an Azure IoT Edge image
2020-12-09T12:53:58.1506505Z Version      : 2.4.4
2020-12-09T12:53:58.1506982Z Author       : Microsoft Corporation
2020-12-09T12:53:58.1507556Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
2020-12-09T12:53:58.1507928Z ==============================================================================
2020-12-09T12:54:03.7578427Z Start deploying...
2020-12-09T12:54:03.7589065Z Deployment task is running in build pipeline? false
2020-12-09T12:54:03.7593054Z D:\a\r1\a\_xxx\deployment.json
2020-12-09T12:54:03.7593527Z Checking if the following file is a valid json: D:\a\r1\a\_xxx\deployment.json
2020-12-09T12:54:03.7597588Z Valid
2020-12-09T12:54:25.2008477Z ##[error]privateserver/privateimage:0.0.4-amd64 does not exist or the credential is not set correctly. Error: Get https://privateserver/v2/privateimage/manifests/0.0.4-amd64: dial tcp: privateserver: no such host
```

Any chance to use this task without publishing the modules to Azure CR? The only thing I want is that the deployment manifest is transfered it to the IoT-Hub 😉 - no further validations/actions are needed.

Thanks in advance - and please let me know if I was unclear or could contribute further information.

**Comment by ha-gg-i** [comment]
Hi Andreas,

you can set the environment variable named `SKIP_MODULE_IMAGE_VALIDATION=true` to skip the image validation.
So far I could not find this hint in the documentation. [Here](https://github.com/microsoft/azure-pipelines-tasks/blob/cc65d6bc9b9db7da933d6c80c7d50c32c454b062/Tasks/AzureIoTEdgeV2/deployimage.ts#L171) is the code line that checks if a check should be performed.

**Comment by alaendle** [comment]
Thanks @ha-gg-i for the hint - this seems to work; @nadesu if this is the official recommendation feel free to just close this issue - but maybe the `SKIP_MODULE_IMAGE_VALIDATION` could be mentioned somewhere in the documentation for the "Azure IoT Edge" task (at least I haven't found it in the documentation).

**Comment by 20shivangi** [comment]
Moving this issue to correct owner as mentioned [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS#L48). Please check if this issue can be closed.

**Comment by blackchoey** [comment]
@mariana Can you help take a look?
@20shivangi Can you remove me from the codeowners and assign @mariana as primary owner for better issue tracking?

**Comment by 20shivangi** [comment]
@blackchoey I am unable to assign this to @mariana
Can you assign this? I have removed you from this issue as an owner.

**Comment by blackchoey** [comment]
@20shivangi Sorry I can't, I have limited permission to this repo...

**Comment by 20shivangi** [comment]
@blackchoey Even I am unable to assign this issue to @mariana. I tried to assign to other persons who were mentioned as code owners, but unable to do the same. So, I just assigned this to you
Is there someone other to whom we can assign this?

**Comment by blackchoey** [comment]
@20shivangi  can you reach admin of this repo for help? I have no idea about why only me in the code owners can be assigned an issue.

**Comment by 20shivangi** [comment]
@alaendle Are you still facing this issue?
If not, I will close the issue. If yes, then we will see whom to assign this issue. Please let us know

**Comment by alaendle** [comment]
Hello @20shivangi, yes and no, the problem for sure is still present, but the workaround mentioned by the community seems to work.
So if the solution from @F-Joachim is the official solution/recommendation to solve my problem feel free to just close this issue - but maybe the SKIP_MODULE_IMAGE_VALIDATION could be mentioned somewhere in the documentation for the "Azure IoT Edge" task (at least I haven't found it in the documentation).

**Comment by chshrikh** [comment]
@blackchoey  can you please check this

**Comment by blackchoey** [comment]
@marianan can help
@chshrikh As mentioned before, please remove me from codeowners so issues can be routed correctly.

**Comment by marianan** [comment]
@alaendle thank you for reporting this issue, we have added it to our backlog for investigations and will follow up with any findings in this thread.

**Comment by cindydeng1998** [comment]
@alaendle Thank you for your feedback, the docs have been updated with the environment variable SKIP_MODULE_IMAGE_VALIDATION option. Please let us know if you run into any other issues
