### ISSUE TITLE
App Center distribute fails with a DatabaseError when marking the package as available

### ISSUE THREAD

**Issue by kawazoe** [microsoft/azure-pipelines-tasks#14053]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: App Center distribute v3.173

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
        https://dev.azure.com/HQCdevops/HQC/_releaseProgress?releaseId=3833

- Agent - Hosted 
    - If using Hosted agent, provide agent queue name: vs2017-win2016

## Issue Description

When the old release upload API got deprecated, we tried transitioning over to the App Center distribute task as we didn't knew that the downtime was generalized at the time. Since the transition, we keep on getting database errors when the package is flagged as available.

### Task logs

````
2020-12-09T14:38:31.0108382Z ##[debug]-- Mark package available.
2020-12-09T14:38:31.0109151Z ##[debug]---- url: https://api.appcenter.ms/v0.1/apps/FOO/BAR/releases/123/groups
2020-12-09T14:38:31.2666442Z ##[debug]---- {"code":"dependent_service_error","message":"Error: {\"error\":{\"code\":\"DatabaseError\",\"message\":\"Conversion failed when converting from a character string to uniqueidentifier.\"}}"}
2020-12-09T14:38:31.2668136Z ##[debug]---- http call status code: 500
2020-12-09T14:38:31.2680065Z ##[debug]task result: Failed
````

**Comment by kawazoe** [comment]
After a lot of fumbling around, our team figured out that while the previous API we were using required to pass the distribution group as names, the tasks needed the ids...

I will keep this bug opened as this should return a 400 with a validation error on the distribution group field.

**Comment by NaagAlgates** [comment]
I'm facing this error today. Is there any temporary solution until this is fixed?

**Comment by kawazoe** [comment]
@NaagAlgates There is nothing to fix. The bug is only opened because the error should be more clear to the user.

It happened because you are using distribution group names instead of their guid.

**Comment by NaagAlgates** [comment]
Yes. Thanks. You're right.
