### ISSUE TITLE
Different private registries as source and destination from within docker-compose (dockercompose) build task?

### ISSUE THREAD

**Issue by jeanfrancoislarente** [microsoft/azure-pipelines-tasks#14072]
## Required Information

*Type*: **Question, Feature**

**Enter Task Name**: dockercomposebuild  

list here (V# not needed):  DockerCompose

## Environment
- Server - Azure Pipelines 

- Agent - Private
   
## Issue Description

I can successfully use the DockerCompose Build task to build against a private registry, which I can pass into the task using my service connection (`azureContainerRegistry: $(container.registry)`) but my build process also refers to a second private registry for pulling/base images. I need to log into both registries but it seems that the task only supports one connection.

Is there a workaround to pull from a private registry to get source/base images but then push to a different private registry?

We've tried logging in with `az acr login -n` in a previous step but this also didn't work

**Comment by Ganeshrockz** [comment]
@jeanfrancoislarente You can have a `az cli` task that runs the `az acr import` command before your docker compose step. This helps in moving all images to a particular registry before docker compose. More information can be found here (https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az_acr_import)

**Comment by jeanfrancoislarente** [comment]
Ok I understand what you're saying, but I don't want to import all of the images that I need from one private registry to another just for building. I'm trying to use two private registries as a source and one private registry as a destination.

Some images would end up being:

_pseudo:_
```
services:

  myservice:
    image: private1.azurecr.io/my-final-tag
    build:
      args:
        BUILD_IMAGE: private2.azurecr.io/my-base:latest
        ASSET_IMAGE: private1.azurecr.io/my-asset:latest
```

As you can see the final tag (push) will be private 1 but I'm using both private 1 and private 2 as source images and I don't want to copy/store the image from private 2 to private 1 just to consume them.

**Comment by Ganeshrockz** [comment]
In that case, can you try creating an SPN in Azure and add the role assignments (for all the above mentioned registries) and create a ARM service connection in Azure Devops? Referencing this service connection in the docker compose task should solve your problem i guess.

**Comment by jeanfrancoislarente** [comment]
I solved it by pulling base/build images using powershell. That way I login to all relevant ACRs using `az acr login -n <name>`, pull all images and then docker-compose build already has the most up-to-date images locally.
