### ISSUE TITLE
NuGet Tool Installer Task - ERR:read ECONNRESET

### ISSUE THREAD

**Issue by gcedil** [microsoft/azure-pipelines-tasks#14085]
*Type*: Bug

**Enter Task Name**: NuGet Tool Installer

## Environment
- Server - Azure Pipelines

- Agent - Private: Windows OS

## Issue Description

The NuGet Tool Installer Task has started failing without any changes as of 12/14 with the following error - **ERR:read ECONNRESET**.

## Troubleshooting
Tried different versions.

### Error logs

Starting: Use NuGet 4.6.2
==============================================================================
Task         : NuGet tool installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
Version      : 0.179.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=852538)
==============================================================================
**ERR:read ECONNRESET
Finishing: Use NuGet 4.6.2**

**Comment by mike-thompson-h** [comment]
I am experiencing the same issue as well, but with version 5.9.1. An earlier version works, but I need a later version to run with .net 5.0

**Comment by mike-thompson-h** [comment]
@gcedil What Build agent is using this pipeline? This version of Nuget might need installing on that machine
