### ISSUE TITLE
Microsoft.IdentityModel.Clients.ActiveDirectory not loading on Azure DevOps PowerShell

### ISSUE THREAD

**Issue by delucaezequiel** [microsoft/azure-pipelines-tasks#14088]
Hi:

I am having some issue with Azure DevOps PowerShell when attempting to create a ClientCredential and or ClientAssertion. I have the following code which was working on the past for creating a ClientCredential based on the following variables:

- TenantId
- ClientID (SPN)
- Password (SPN Password)

```
$ResourceUrl = "https://database.windows.net/"
$AuthorityUrl = "https://login.microsoftonline.com/$($TenantId)"
$objClientCredential = [Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential]::new($ClientId, $Password)
$objAuthenticationContext = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext]::new($AuthorityUrl)
$objAuthenticationResult = $objAuthenticationContext.AcquireTokenAsync($ResourceUrl, $objClientCredential)
$objAuthenticationResult.Result.AccessToken

```
but recently this code stop working. It seems that the AzureAD module is not longer loading correctly. This only happens on Azure DevOps Powershell, on my machine it works fine (checked with Windows PowerShell and PowerShell 7.1) So far so now I attempted the following:

1. Run the code as shown above
**Breaks on:** $objClientCredential = [Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential]::new($ClientId, $Password)
**Error:** Unable to find type [Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential]

2. Install AzureAD before running the code
Install-Module -Name AzureAD -Force
Import-Module -Name AzureAD
**Breaks on: **$objClientCredential = [Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential]::new($ClientId, $Password)
**Error:** Unable to find type [Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential]

3. Import the dll Microsoft.IdentityModel.Clients.ActiveDirectory.dll from my machine
Add-Type -Path ".\libraries\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Doesn't break, however ClientCredential is not created it is returned as null

**Comment by ElMiguel123** [comment]
Same issue here; did you find a way to fix that ?

**Comment by delucaezequiel** [comment]
Hi:

An alternative that is working is use Get-MsalToken cmdlet as shown below:

```
$ClientSecret = ConvertTo-SecureString <secret> -AsPlainText
$AccessToken = (Get-MsalToken -ClientId $ClientID -ClientSecret $ClientSecret -TenantId $TenantID).accessToken
```
