### ISSUE TITLE
Allow installing Node.js version based on .nvmrc

### ISSUE THREAD

**Issue by plaa** [microsoft/azure-pipelines-tasks#14094]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Node.js Tool Installer  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Please add an option to install the Node.js version defined in `.nvmrc`.  This would be useful for fixing a particular version across development and build pipelines.  Currently when the Node version is upgraded, you need to go through all pipelines and update their configuration (and impossible if different branches require different versions).  For example App Center has the option of selecting a specific Node version or using `.nvmrc`.

**Comment by plaa** [comment]
I think this is still very relevant and I wouldn't believe it to be too
hard to do either.

**Comment by betopompolo** [comment]
up

**Comment by fowl2** [comment]
I had a go at this in PR #15615

**Comment by fowl2** [comment]
[Note that the GitHub actions version of this task already supports using a node version file](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file).

**Comment by anatolybolshakov** [comment]
@plaa @fowl2 thanks for reporting and contribution! We are currently working on more prioritized items at the moment, but will get back to this one once be able to.

**Comment by JaydenMaalouf** [comment]
Is there any timeline on this deployment?
It would be awesome to have!

**Comment by plaa** [comment]
Would still be useful.

**Comment by JaydenMaalouf** [comment]
> Would still be useful.

This has already been deployed and is working as expected on my end!

**Comment by dinbtechit** [comment]
@JaydenMaalouf How did you get it working? For some reason it does not get pick up the `.nvmrc` file..

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/17984781/cb468d4a-266c-476b-8fd2-da71bf1df74c)

**Comment by JaydenMaalouf** [comment]
> @JaydenMaalouf How did you get it working? For some reason, it does not pick up the version from `.nvmrc` during `appcenter-post-clone.sh` step.
> 
> 
> 
> ![image](https://github.com/microsoft/azure-pipelines-tasks/assets/17984781/cb468d4a-266c-476b-8fd2-da71bf1df74c)
> 
> 
> 
> .nvmrc
> 
> ```
> 
> v16.15.1
> 
> ```
> 
> 
> 
> From App Center logs:
> 
> The node version shows as `18.x`
> 
> ![image](https://github.com/microsoft/azure-pipelines-tasks/assets/17984781/eb1fe493-c08e-4e0f-b3b9-e59e24b9c542)
> 
> 
> 
> Even manually selecting the node version from the dropdown does not work.
> 
> 

Are you invoking the `NodeTools@0` step before attempting to run the script?

Simply calling
```yaml
- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'
    versionFilePath: '.nvmrc'
```

Then your node install should match the version defined in your .nvmrc

**Comment by dinbtechit** [comment]
> Are you invoking the NodeTools@0 step before attempting to run the script?

Simply calling before anything else (but after checkout):

- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'
    versionFilePath: '.nvmrc'
Should result in your node install matching the version defined in your .nvmrc


How invoke `NodeTools@0`.. I dont think I came across any documentation that mentions that. Are you able to point me to  the App Center documentation that refers about this NodeTools@0? Thanks! 🙏

**Comment by JaydenMaalouf** [comment]
> > Are you invoking the NodeTools@0 step before attempting to run the script?
> 
> 
> 
> > Simply calling before anything else (but after checkout):
> 
> 
> 
> > - task: NodeTool@0
> 
>   inputs:
> 
>     versionSource: 'fromFile'
> 
>     versionFilePath: '.nvmrc'
> 
> > Should result in your node install matching the version defined in your .nvmrc
> 
> 
> 
> 
> 
> How do you invoke `NodeTools@0` before running the post clone script... I dont think I came across any documentation that mentions that. Are you able to point me to  the App Center documentation that refers about this NodeTools@0? Thanks! 🙏

Either via your yaml file using the yaml I provided above or if you are using Releases, via the Node task in Azure DevOps with the appropriate parameters

**Comment by LuwkasLima** [comment]
Hi folks, I would like some guidance on this. I'm trying to make it standard for my team to adopt .nvmrc to ensure consistency between all our applications and also in our CICD pipelines using ADO.

We have implemented Node version enforcement for Web App Service deployments successfully using .nvmrc but I'm not able to do the same with AzureStaticWebApp@0. I do not want them to maintain .nvmrc and package.json configuration.

I've tried the workaround proposed above, adding NodeTool@0 prior to AzureStaticWebApp@0, but it ignores the installation of node v18 and uses v16 to build the Next static application.
<img width="450" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/5949986/ebde23f7-fa72-459f-9607-ea4a7c73fc29">


<img width="306" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/5949986/8893def1-7ffc-44cd-90de-9538bda5a165">

AzureStaticWebApp@0 deployment log:
<img width="313" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/5949986/422907de-5798-46ea-b961-6f6586bc996c">

**Comment by JaydenMaalouf** [comment]
> Hi folks, I would like some guidance on this. I'm trying to make it standard for my team to adopt .nvmrc to ensure consistency between all our applications and also in our CICD pipelines using ADO.
> 
> 
> 
> We have implemented Node version enforcement for Web App Service deployments successfully using .nvmrc but I'm not able to do the same with AzureStaticWebApp@0. I do not want them to maintain .nvmrc and package.json configuration.
> 
> 
> 
> I've tried the workaround proposed above, adding NodeTool@0 prior to AzureStaticWebApp@0, but it ignores the installation of node v18 and uses v16 to build the Next static application.
> 
> <img width="450" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/5949986/ebde23f7-fa72-459f-9607-ea4a7c73fc29">
> 
> 
> 
> 
> 
> <img width="306" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/5949986/8893def1-7ffc-44cd-90de-9538bda5a165">
> 
> 
> 
> AzureStaticWebApp@0 deployment log:
> 
> <img width="313" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/5949986/422907de-5798-46ea-b961-6f6586bc996c">
> 
> 

That sounds like your engine version is being specified in your `package.json`

Make sure to update that to match your nvmrc specification
```json
"engines": {
    "node": ">=18.0.0"
}
```

**Comment by vmohir** [comment]
I'm confused why it's not supported in [NodeTools@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-node-v1?view=azure-pipelines).
