### ISSUE TITLE
Web App Deployment hangs on zip extract

### ISSUE THREAD

**Issue by tbeswick96** [microsoft/azure-pipelines-tasks#14093]
## Required Information

*Type*: Bug
*Task*: AzureRmWebAppDeployment 4.179.0

## Environment
- Server - Azure Pipelines
  - codat/Codat - Release-174 - releaseId=23987 environmentId=84280

- Agent - Hosted
  - windows-2019

## Issue Description

During web deployment of a zipped artifact, the zip extraction causes the task to hang, due to asking
```
Would you like to replace the existing file:
	Path:     D:\a\_temp\temp_web_package_6079183468286993\Web.config
	Size:     718 bytes (1 KiB)
	Modified: 2020-12-17 11:19:38
with the file from archive:
	Path:     web.config
	Size:     493 bytes (1 KiB)
	Modified: 2020-12-17 11:20:33
```

This blocks the entire task from finishing.
This task was working yesterday with no problems, and the release pipeline has not changed.

These settings are used for the deployment:

![image](https://user-images.githubusercontent.com/11049179/102483824-34fc0580-405d-11eb-819e-adfd927a85ea.png)

We also have JSON variable substitution enabled for appsettings.json files

### Task logs

[tasklog_7.log](https://github.com/microsoft/azure-pipelines-tasks/files/5709084/tasklog_7.log)

**Comment by tbeswick96** [comment]
This turned out to be an error with two `web.config` files in the artifact.
The build pipeline is an ubuntu agent, and was packaging two files, `web.config` and `Web.config` with different casing.
When running the release on a windows agent, the unzip process did not allow both files even with the different casing.

Regardless of the root cause of the issue, is there anything that can be done to always overwrite the 7zip extraction, or to fail the task if it asks for it?

**Comment by AmrutaKawade** [comment]
Can you run build pipeline also on windows agent?

**Comment by AmrutaKawade** [comment]
Closing this issue due inactivity. Feel free to reopen if issue still persists
