### ISSUE TITLE
Exit code when no tests discovered/executed

### ISSUE THREAD

**Issue by Sanan07** [microsoft/azure-pipelines-tasks#14096]
Hi. 
I am from vstest team.

Recently we introduced new RunConfiguration parameter called TreatNoTestsAsError - [TreatNoTestsAsError](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
The idea here – if no tests were found during test execution, so vstest.console.exe returns non-zero code - if that parameter has value true.

I was testing today that logic in my testing pipeline and I saw that return code automatically setting to zero if there were not some flaky tests (see the attachment) Is it any new logic that you have in AzDo, because month ago when I tested the same scenario I did not see such behaviour (previous.png in attachements). 

Currently:
![no_tests](https://user-images.githubusercontent.com/8465726/102511115-af8e4a80-4088-11eb-9822-31da236dd514.PNG)
Previously:
![previous](https://user-images.githubusercontent.com/8465726/102511122-b1580e00-4088-11eb-9bea-efde14f303ba.PNG)

I expected my pipeline to fail, but it passed. Is it some new settings where we can change that option? Is it hard coded logic?

**Comment by Sanan07** [comment]
Hi. Has anyone looked at this issue?

**Comment by anatolybolshakov** [comment]
Hi @Sanan07 
This repo is for pipeline tasks mostly, but as I see this error comes from Azure DevOps side - could you please create ticket on https://developercommunity.visualstudio.com/ to get right eyes on it?

**Comment by Sanan07** [comment]
@anatolybolshakov Thank you for response. I created the one : [ticket](https://developercommunity.visualstudio.com/content/problem/1294096/exit-code-when-no-tests-discoveredexecuted.html).

This can be closed then.
