### ISSUE TITLE
Limited to 30 assets visible in DownloadGitHubReleaseV0

### ISSUE THREAD

**Issue by framinosona** [microsoft/azure-pipelines-tasks#14095]
When listing assets on [this line](https://github.com/microsoft/azure-pipelines-tasks/blob/eefd4d4842fddaa16dfb6c579f780338b8563f18/Tasks/DownloadGitHubReleaseV0/main.ts#L186) the "assets/" endpoint is used. 

https://github.com/microsoft/azure-pipelines-tasks/blob/eefd4d4842fddaa16dfb6c579f780338b8563f18/Tasks/DownloadGitHubReleaseV0/main.ts#L186

As per [this documentation](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-release-assets) there are "?page=" and "?per_page=" parameters available to go through multiple pages of results. 
Default value is per_page=30.

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-release-assets

That makes the task only download assets if they are in the first 30 assets of the release.

Note : Endpoint without the "/assets", https://api.github.com/repos/{owner}/{repo}/releases/{release_id}/, lists them all.

**Comment by janechu** [comment]
This is still an issue. I am running into it and unable to use the pipeline task for a release with 54 assets.
