### ISSUE TITLE
Azure App Service Deploy task does not offer .NET 5.0 in the Runtime Stack dropdown

### ISSUE THREAD

**Issue by obohaciak** [microsoft/azure-pipelines-tasks#14101]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4 (4.179.0)

## Environment
- Server - Azure Pipelines
  Account name: soliteacr
  Build definition: Nightly build (https://dev.azure.com/soliteacr/IRIS/_releaseDefinition?definitionId=1)
  Build number: Release-296 (releaseId 343)

- Agent - Hosted 
  Agent pool: Azure Pipelines
  Agent specification: ubuntu-18.04

## Issue Description

Azure App Service deploy task (AzureRmWebAppDeploymentV4) does not offer .NET 5 as an option in the Runtime Stack dropdown. Clicking on Refresh Runtime Stack does not help.

Now that .NET 5.0 is GA and supported by App Service in Azure, I would expect the option to set the runtime would be available, therefore I classified this as bug.

![image](https://user-images.githubusercontent.com/30824712/102602025-37c02e80-4121-11eb-9228-197c1181a3a7.png)

## Troubleshooting

As a workaround, do not select anything from the Runtime Stack dropdown, but enter "DOTNETCORE|5.0" directly. This is the LinuxFxVersion needed that I found in the App Service Configuration in Azure when displaying the Resource JSON. 

I think it should be enough to set it in the release pipeline, but it might also be necessary to set it in the App Service in Azure (through portal or ARM template) prior to running the release pipeline. I think the task first checks if the App Service runtime in Azure is already set to required value and only sets it explicitly if they differ.

**Comment by amit-avit** [comment]
The AzureRmWebAppDepolyment task uses the stacks api to fetch this list of runtimes:
{{{endpoint.url}}}/providers/Microsoft.Web/availableStacks?api-version=2016-03-01&osTypeSelected=Linux
We would need to notify the kudu team to update their api on their end.
@sanchitmehta can you please take a look.

**Comment by AmrutaKawade** [comment]
As mentioned earlier we use https://docs.microsoft.com/en-us/rest/api/appservice/provider/getavailablestacks api to list runtime stack. .Net 5.0 is currently not available in this API and appservice team is working on this to update this API.

till then you can directly enter runtime stack in dropdrown `DOTNETCORE|5.0`

As there is no fix required from task side I will close this issue.
