### ISSUE TITLE
Allow "scale" command in Kubectl task

### ISSUE THREAD

**Issue by giannisioannou-tomtom** [microsoft/azure-pipelines-tasks#14104]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Allow "scale" command in Kubectl task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

Reading the documentation at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops and the source code of the Kubectl task is seems that the "scale" command is not supported. Is it possible to implement?

**Comment by ds-ms** [comment]
Although it's not listed in the default values. The task does support all the commands. You can set the `command` input to `scale` and add the other required arguments in the `arguments` input. It will work out for you
