### ISSUE TITLE
New Location For Stable and Incubator Charts

### ISSUE THREAD

**Issue by kasunchandrasiri** [microsoft/azure-pipelines-tasks#14118]
**Question, Bug, or Feature?**  
Bug

## Issue Description
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden

## Troubleshooting
The new location for the stable repository is https://charts.helm.sh/stable and the new location for the incubator repository is https://charts.helm.sh/incubator. If you use charts in either of these old locations below you MUST update the repositories you use before November 13, 2020. The new locations are hosted using GitHub pages.

Name	Old Location	New Location
stable	https://kubernetes-charts.storage.googleapis.com	https://charts.helm.sh/stable
incubator	https://kubernetes-charts-incubator.storage.googleapis.com	https://charts.helm.sh/incubator

### Error logs

##[debug]Evaluating condition for step: 'Install Helm'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Install Helm
==============================================================================
Task         : Helm tool installer
Description  : Install Helm on an agent machine
Version      : 1.175.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-helm-installer-tsg
==============================================================================
##[debug]Using node path: /home/vsts/agents/2.179.0/externals/node/bin/node
##[debug]agent.TempDirectory=/home/vsts/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_HELMVERSIONTOINSTALL
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_CONTAINER_AUTHENTICATIONTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading SECRET_NUGET_FEED_PAT
##[debug]loading SECRET_CONTAINER_USERNAME
##[debug]loading SECRET_CONTAINER_PASSWORD
##[debug]loaded 9
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : /home/vsts/work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.175.1/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]adding resource file: /home/vsts/work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.175.1/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]system.culture=en-US
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : /home/vsts/work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.175.1/node_modules/azure-pipelines-tasks-kubernetes-common-v2/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]adding resource file: /home/vsts/work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.175.1/node_modules/azure-pipelines-tasks-kubernetes-common-v2/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]system.culture=en-US
##[debug]check path : /home/vsts/work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.175.1/task.json
##[debug]adding resource file: /home/vsts/work/_tasks/HelmInstaller_068d5909-43e6-48c5-9e01-7c8a94816220/1.175.1/task.json
##[debug]system.culture=en-US
##[debug]helmVersionToInstall=2.14.3
##[debug]cleaning: 2.14.3
Verifying helm installation...
##[debug]which 'helm'
##[debug]found: '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]which 'helm'
##[debug]found: '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]which '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]found: '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]which '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]found: '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm arg: init
##[debug]/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm arg: --client-only
##[debug]exec tool: /opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm
##[debug]arguments:
##[debug]   init
##[debug]   --client-only
/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm init --client-only
Creating /home/vsts/.helm 
Creating /home/vsts/.helm/repository 
Creating /home/vsts/.helm/repository/cache 
Creating /home/vsts/.helm/repository/local 
Creating /home/vsts/.helm/plugins 
Creating /home/vsts/.helm/starters 
Creating /home/vsts/.helm/cache/archive 
Creating /home/vsts/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
##[debug]Exit code 1 received from tool '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]STDIO streams have closed for tool '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm'
##[debug]task result: Failed
##[error]Error: The process '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm' failed with exit code 1
##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process '/opt/hostedtoolcache/helm/2.14.3/x64/linux-amd64/helm' failed with exit code 1
Finishing: Install Helm

**Comment by GiCManilaWerewolves** [comment]
Is there any actions required when we're using Microsoft Hosted Agents?

**Comment by aidenfry1** [comment]
Is there any way that we know to work around this while waiting for a fix for the pipeline?

**Comment by shashwath-m** [comment]
i think we need to upgrade helm version to 2.17.0 minimum to make this work

anything below helm version 2.14.0 will give the same error.

**Comment by aidenfry1** [comment]
Yes upgrade to 2.17.0 resolve for me. Thanks

**Comment by GiCManilaWerewolves** [comment]
Server should be upgraded as well else subsequent HelmDeploy task would fail with error like below

Error: incompatible versions client[v2.17.0] server[v2.16.5]
##[error]Error: UPGRADE FAILED: incompatible versions client[v2.17.0] server[v2.16.5]

**Comment by GiCManilaWerewolves** [comment]
Question: will this be fixed or are we forced to upgrade/update version?

**Comment by shashwath-m** [comment]
> Server should be upgraded as well else subsequent HelmDeploy task would fail with error like below
> 
> Error: incompatible versions client[v2.17.0] server[v2.16.5]
> ##[error]Error: UPGRADE FAILED: incompatible versions client[v2.17.0] server[v2.16.5]

Yes i forgot to mention about that. Thanks for pointing that

**Comment by shigupt202** [comment]
This has been fixed now. All the helm versions should work.
