### ISSUE TITLE
Tasks/VsTestV2 Keep TestSettings instead of deletion after the test run

### ISSUE THREAD

**Issue by soodputter** [microsoft/azure-pipelines-tasks#14127]
Task         : Visual Studio Test
Version      : 2.153.9
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================

There is some tooling dependent on TestSettings file available with the results. Since some updates this testsetting are deleted after the test run completes and breaking out tooling. 

##[debug]Done creating test settings. test settings Id : 162989
test settings id : 162989
##[debug]Deleted test settings with id : 162989

Is it possible to leave the testsettings file instead of deleting it?

**Comment by anshii03** [comment]
This is by design and vstest task works like this internally. Tagged this as enhancement .
