### ISSUE TITLE
GradleV2 fails with JaCoCo on multiproject build

### ISSUE THREAD

**Issue by gnegnegne** [microsoft/azure-pipelines-tasks#14130]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GradleV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines

- Agent - Hosted or Private: 
    
    - Self Hosted Agent on Windows 10, agent version 2.174.3

## Issue Description

Gradle task fails on multi project with JaCoCo enabled, error caused by set of a readonly property. The problem seems related to a missing fix from the https://github.com/microsoft/azure-pipelines-tasks/commit/c99aa3bc9b6d4d0cd8d0b12791d9a280b5e5dcfb

That commit didn't fix the line 24:
https://github.com/microsoft/azure-pipelines-tasks/blob/18cd04cd0aa1056a02b9408da8eec782d642b9b3/common-npm-packages/codecoverage-tools/codecoverageconstants.ts#L24

could you confirm that it is related @anatolybolshakov ?

### Task logs

>* What went wrong:
> Execution failed for task ':platform-app:jacocoTestReport'.
> Cannot set the value of read-only property 'classDirectories' for task ':platform-app:jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
> Task :platform-app:distZip
> Task :platform-app:shadowJar
> Task :platform-app:startShadowScripts
> Task :platform-app:shadowDistTar
> Task :platform-app:shadowDistZip
> Task :platform-app:assemble
> Task :platform-app:compileTestJava
> Task :platform-app:processTestResources NO-SOURCE
> Task :platform-app:testClasses
> Task :platform-app:test
> Task :platform-app:jacocoTestReport
FAILURE: Build failed with an exception. FAILED


* Where:
Build file 'C:\agent\_work\4\s\build.gradle' line: 24

* What went wrong:
Execution failed for task ':platform-app:jacocoTestReport'.
> Cannot set the value of read-only property 'classDirectories' for task ':platform-app:jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
21 actionable tasks: 18 executed, 3 up-to-date


* Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
```

**Comment by anatolybolshakov** [comment]
Hi @gnegnegne we have rolled out related changes - you can set 'gradle5xOrHigher' currently - to signalize that you use Gradle >= 5.x if there is JaCoCo code coverage enabled.

**Comment by anatolybolshakov** [comment]
Let me close it at the moment since it's resolved - please let us know if you have any further questions!
