### ISSUE TITLE
ARM template deployment v3 - Parameter overriding UI doesn't support Release.PrimaryArtifactSourceAlias in the path of source files

### ISSUE THREAD

**Issue by pacorreia** [microsoft/azure-pipelines-tasks#14131]
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeploymentV3 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Azure Pipelines  
 
    - Account Name: COFCOInternational
    - Team Project Name: Integration Platform
    - Build Definition Name: zema/adf-release

- Agent: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    - OS: Windows/Linux
    - Agent Version: 2.172.1

## Issue Description

The issue is not related to execution it happens at design time using the classic Release pipeline UI.

The affected task is: AzureResourceManagerTemplateDeploymentV3

The illustrate the way to reproduce the issue look at following screenshot:
![image](https://user-images.githubusercontent.com/54323159/103002839-8b6ab780-4527-11eb-86a3-cbf9c53122aa.png)

The happens when I use the variable `$(Release.PrimaryArtifactSourceAlias)` and then I try to use the UI to fill parameters as follows:
![image](https://user-images.githubusercontent.com/54323159/103002956-c8cf4500-4527-11eb-8825-86bb4dc922f5.png)

But then the tasks executes with success, so the issue is only related to this UI and not execution.

The expected behavior would be the UI to able to solve the System variable so it can access files and parse parameters.

### Task logs

I'm not providing logs as the issue is not related to it's execution but rather with it's setup UI.

## Troubleshooting
If I manually write the artifact alias, there's no issue.

### Error logs

Warning: Failed to download the template file from the given path '$(System.ArtifactsDirectory)/$(Release.PrimaryArtifactSourceAlias)/drop/ARMTemplateForFactory.json' with the following error: There is no such artifact '$(System.ArtifactsDirectory)' linked to this release pipeline.

**Comment by tiwarishub** [comment]
Hi @pacorreia, For override template parameter you need to select template and parameter file path using more option icon (...) and select the path  Or add the path using DEFAULT variables , then override template parameter option will parse the template parameters.

**Comment by pacorreia** [comment]
@tiwarishub I think you didn't get the entire picture on this issue

The fact is that, the UI is not able to solve the path to the template f and template parameter files when theri location are specified using variables as described earlier in this issue here's a screenshot of my issue description:

![image](https://user-images.githubusercontent.com/54323159/103356623-2d9b1a00-4aa9-11eb-9ad0-0d28783fe477.png)

**Comment by tiwarishub** [comment]
Hi @pacorreia, thanks for your response.
   Rendering of template params when path is mentioned with variables (not selected via more icon) , then only option is write to parameter template parameters to override in the textbox. Example``–storageName fabrikam``
Rendering of template parameter when path is mentioned with variables is not currently supported and it is per its design. 
Is there any specific reason why you want to use variables in template and parameter path ?

**Comment by pacorreia** [comment]
@tiwarishub actually, there's a reason for it, a convention inside company to prevent hard coded paths whenever possible.

For us makes sense to have generic paths instead of customs ones, also for some reusability.

Since this is by design I would like you to consider for a future improvement.

**Comment by bishal-pdMSFT** [comment]
@pacorreia 
1. Agree that a generic path makes it easier to keep things generic
2. But the root cause is not with ARM deploy task. At design time, the task uses functionality exposed by UI platform and that itself does not support any other variable except `$(System.DefaultWorkingDirectory)`
3. This limitation is by design as at design time many system variables do not exist (they only get alive during runtime). Enabling this feature will mean some very deep rooted changes which, in my honest opinion, is something the platform team will prioritize - especially given that I am not sure many such feedbacks have come in
