### ISSUE TITLE
VSTest task doesn't correctly escape TestCaseFilter argument

### ISSUE THREAD

**Issue by katiekloss** [microsoft/azure-pipelines-tasks#14145]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: [VSTest](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV2)

## Environment
- Server - Azure Pipelines; account amtrust, project AmTrust, [build task group 897c078e-2b5a-409e-96a2-0f9264f74a74](https://dev.azure.com/amtrust/Amtrust/_taskgroup/897c078e-2b5a-409e-96a2-0f9264f74a74)

- Agent - Hosted pool ["Build"](https://dev.azure.com/amtrust/Amtrust/_settings/agentqueues?queueId=10)

## Issue Description

The VSTest2 task builds the TestCaseFilter parameter incorrectly when the "Rerun failed tests" option is enabled. When failed tests are re-run, the task passes the TestCaseFilter parameter to vstest as:

`/TestCaseFilter:"FullyQualifiedName=CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation.Rules_CA_CADriverBase_DriverAgeMinimumValidation(CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation+DriverAgeMinimumValidationTestCaseData)"`

VSTest throws the error "An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Missing Operator '|' or '&'."

According to the [TestCaseFilter documentation](https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md), some characters need to be escaped. In this example, the task isn't escaping the parentheses in the method name. When I escape them like the following and run VSTest, it runs correctly:

`/TestCaseFilter:"FullyQualifiedName=CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation.Rules_CA_CADriverBase_DriverAgeMinimumValidation\(CPP.Tests.Rules_CA_CADriverBase_DriverAgeMinimumValidation+DriverAgeMinimumValidationTestCaseData\)"`

### Error logs
[VSTest Log](https://github.com/microsoft/azure-pipelines-tasks/files/5748479/vstestlog.txt)

**Comment by ShreyasRmsft** [comment]
@katiekloss as documented in the task [official docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#i-am-running-into-issues-when-running-data-driven-xunit-and-nunit-tests-with-some-of-the-task-options-are-there-known-limitations) some of the advanced features of the task are not supported for datadriven tests or tests with custom characters in their fully qualified names (of which data driven tests are a subset).

This is currently not on our roadmap to enhance at the moment. Closing this issue with the same message.
