### ISSUE TITLE
Feature: Playwright task

### ISSUE THREAD

**Issue by Meir017** [microsoft/azure-pipelines-tasks#14146]
*Type*: Feature

**Enter Task Name**: Playwright

## Environment
- Server - Azure Pipelines
  
## Issue Description

provide utility task to use for installing playwright when running in azure-pipelines
could be based on https://github.com/microsoft/playwright-github-action

**Comment by vtbassmatt** [comment]
I'll leave this open a while to see what other inputs we get. This is the first request I've seen for such a task, so there's not (yet) enough evidence to support building something out of the box.

**Comment by Meir017** [comment]
@pavelfeldman do you think this would be useful?

**Comment by qtpsudhakar** [comment]
This will be a good feature for Playwright to run in azure
