### ISSUE TITLE
GoTool: Unable to install go1.16beta1

### ISSUE THREAD

**Issue by e3b0c442** [microsoft/azure-pipelines-tasks#14159]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GoTool  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: n/a
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: e3b0c442, warp, #20210101.6

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: whichever the default is, OS ubuntu-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

When attempting to use GoToolV0 to install go1.16beta1, the caching step of the job fails due to not correctly indentifying the version number. I did notice that the`fixVersion()` function in gotool.ts may be related; if I input `1.16beta1` into the tool, the return is `1.16beta1.0` which does not match the Go version number.

### Task logs

```
Starting: GoTool
==============================================================================
Task         : Go tool installer
Description  : Find in cache or download a specific version of Go and add it to the PATH
Version      : 0.179.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/go-tool
==============================================================================
Downloading: https://storage.googleapis.com/golang/go1.16beta1.linux-amd64.tar.gz
Extracting archive
/bin/tar xzC /home/vsts/work/_temp/4f5aceff-4908-4706-950e-b630e7048d73 -f /home/vsts/work/_temp/1bbb602d-891b-4aea-9e07-7be9c3a6c498
Caching tool: go null x64
##[error]TypeError: Cannot read property 'trim' of null
Finishing: GoTool
```

## Troubleshooting

Attempted matrix builds with different versions of Go

### Error logs

`##[error]TypeError: Cannot read property 'trim' of null`

**Comment by tiwarishub** [comment]
Hi @e3b0c442, 
     The issue is happening because beta version  ``1.16beta1`` is not correct as per semantic versioning which is why it is failing here. And currently we support only semver. And this is bydesign.

**Comment by ashwinsangem** [comment]
@e3b0c442 Let me know if you have anything else associated with this issue.
