### ISSUE TITLE
No Login Output Flag

### ISSUE THREAD

**Issue by doittjdoughty** [microsoft/azure-pipelines-tasks#14156]
https://github.com/microsoft/azure-pipelines-tasks/blob/37b7beed4f89a64e51b2fcc8fe50eb6cc900e680/Tasks/AzureCLIV2/azureclitask.ts#L137

We have dozens of pipelines running over 100 Azure subscriptions and each time our pipelines run the AzureCLI@2 task is used to log into Azure all of our subscriptions are logged to the pipeline output. This means that the important pipeline content that we care about usually starts on line 1620. Can the line of code referenced here be updated with "--output none" as an option. Below is the sample step included in our pipelines:

          - task: AzureCLI@2
            displayName: 'The Task'
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              azureSubscription: $(azure_service_connection)
              addSpnToEnvironment: true
              inlineScript: |
                export ARM_ENVIRONMENT=$(arm_environment)
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_CLIENT_SECRET=$servicePrincipalKey
                export ARM_SUBSCRIPTION_ID=$(arm_subscription_id)
                export ARM_TENANT_ID=$tenantId

**Comment by doittjdoughty** [comment]
Hi @bishal-pdMSFT Any thoughts on this? It would be extremely helpful to organizations/enterprises with more than one Azure subscription to limit the login output to a few lines instead of thousands of lines.

**Comment by doittjdoughty** [comment]
@bishal-pdMSFT  any updates one this? Seems like a simple enough fix that would add a value to the login task.

**Comment by ashwinsangem** [comment]
@doittjdoughty, I will take a look and get back.

**Comment by doittjdoughty** [comment]
@ashwinsangem Awesome! Thank you!

**Comment by georambo** [comment]
@ashwinsangem , Hi 👋 .  Sorry to poke, but just wondering if any updates to this.  It is also very useful feature to our team.  The task works great, but the output is so verbose, it makes reviewing the logs very difficult for all jobs we use this for.  We have 100's of subscriptions that spam the logs.  Much appreciated.

**Comment by maxim-nyc3** [comment]
@ashwinsangem ,   
 Hi did you get a chance to look and modify this?

**Comment by doittjdoughty** [comment]
@ashwinsangem and @bishal-pdMSFT  any update on this? This would be a big help to our organization.

**Comment by doittjdoughty** [comment]
Awesome! Thank you @ashwinsangem.

**Comment by tejasd1990** [comment]
Hi @doittjdoughty @georambo @maxim-nyc3 ,
apart from command line options, cli configuration can also be set through [environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables). 
A workaround to fix this is to set the `AZURE_CORE_OUTPUT` environment variable to `none`(you can also set it to `table`, which prints 1 line per subscription). The task has an environment variables section which you can use. A side effect would be that your script output would also get suppressed. To avoid that, you can set the environment variable back to empty string(or any other value you want) at the beginning of your script. Let us know if this works.

**Comment by georambo** [comment]
Hi @tejasd1990  , it seems i have gotten that to work by setting var AZURE_CORE_OUTPUT=none in our pipeline, then as you said, setting back to empty string in our azure cli script.  I have concerns w/ this solution though, as it will be a global var, and suppress output for all azure commands?  so now anywhere we want output, we need to override this value?

it would be much nicer if we could just suppress the output for the login command, or as a flag of the task instead.  I also dont see ability to pass ENV variable just to the azure cli task from the docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops

**Comment by doittjdoughty** [comment]
@tejasd1990 I completely agree with @georambo. After reviewing the code it is a simple fix to add a var to hold a bool that can then be appended to the end of the login function that would suppress the output. We use a lot of azure cli calls in our pipelines and this means we have to constantly switch back and forth to view content.

**Comment by sopelt** [comment]
@bishal-pdMSFT I think this should be reopened and responded to as there have been multiple follow-ups/similar requests (e.g. https://github.com/microsoft/azure-pipelines-tasks/issues/15845 and https://github.com/microsoft/azure-pipelines-tasks/issues/15970 )

**Comment by piotr-gbyliczek** [comment]
I have attempted to create a change to facilitate this, please contribute as I'm not much of a developer, just a frustrated sysadmin: https://github.com/microsoft/azure-pipelines-tasks/pull/16701

**Comment by syedhamjath** [comment]
Please reopen this issues, there is no harm in reducing the log size.
