### ISSUE TITLE
Nuget Push to GitHub Packages fails with 401 Unauthorized

### ISSUE THREAD

**Issue by photomoose** [microsoft/azure-pipelines-tasks#14169]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
- NuGetCommandV2
- DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

When using a Nuget Service Connection, the Azure Pipeline tasks add the "--api-key" switch to the nuget command line, with a hardcoded value of "RequiredApiKey". In the past, this worked when pushing packages to GitHub Packages - however, it looks like a [recent change made in GitHub to support the ApiKey switch](https://github.blog/changelog/2020-10-29-nuget-supports-api-key-option/) causes these tasks to fail with a 401 Unauthorized error. 

### Task logs

```
/usr/bin/dotnet nuget push /home/vsts/work/1/a/packages/release/<package-name>.nupkg --source https://nuget.pkg.github.com/<owner> --api-key RequiredApiKey
Pushing <package-name>.nupkg to 'https://nuget.pkg.github.com/<owner>'...
  PUT https://nuget.pkg.github.com/<owner>/
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
  Unauthorized https://nuget.pkg.github.com/<owner>/ 810ms
error: Response status code does not indicate success: 401 (Unauthorized).
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by xuzhg** [comment]
I met the similar issue.

These days, I am testing to push nuget package to github using Azure pipeline nuget task.

I have the service connection using basic authentication with my PAT.


## 1) If I use the NuGet task as: 

![image](https://user-images.githubusercontent.com/9426627/111839649-549f0600-88b8-11eb-80a7-5b55e73e9c6d.png)

### **I got the following error:**


The nuget command failed with exit code(1) and error(Response status code does not indicate success: **401 (Unauthorized)**. System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized). at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at NuGet.Protocol.Core.Types.PackageUpdateResource.EnsureSuccessStatusCode(HttpResponseMessage response, Nullable`1 codeNotToThrow, ILogger logger) at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c__DisplayClass24_0.<PushPackageToServer>b__0(HttpResponseMessage response) at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__19`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__24.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushAll>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.PushRunner.<Run>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__36.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.CommandLine.Command.Execute() at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args))

## 2) I use the custom nuget as:

![image](https://user-images.githubusercontent.com/9426627/111839724-7d270000-88b8-11eb-8808-b6ad65ca5e22.png)

I got the error

![image](https://user-images.githubusercontent.com/9426627/111839823-a6e02700-88b8-11eb-80b6-7100a6419dd0.png)

**Comment by Daniel127** [comment]
Any news about this? I have the same problem using basic and apikey authentication.

**Comment by photomoose** [comment]
@Daniel127 I had to resort to using the dotnet CLI via an explicit script task instead:

```
          - script: dotnet nuget push --source https://nuget.pkg.github.com/<org-name>/index.json --api-key $(ApiKey) '$(Build.ArtifactStagingDirectory)/packages/release/*.nupkg'
            displayName: Publish Nuget Packages
```

**Comment by preston-scott-cruz** [comment]
I can't find this issue on the developer community.  Did they close it without migrating it?
