### ISSUE TITLE
Please upgrade Az module to 4.8.0 and above and Az.Accounts to 1.9.5 and above 

### ISSUE THREAD

**Issue by hannwang1** [microsoft/azure-pipelines-tasks#14160]
The latest Az module is 5.3.0 and Az.Accounts module is 2.2.2, but the Azure Powershell v5 task only has Az 3.1.0 which is almost one year old.  Many Azure Powershell cmdlet are not available in this old version.  For example, I need to create a pipeline to config Azure databricks,  the Az.Databricks module only work with Az.Accounts version >= 1.9.5.

Please upgrade Az module to latest released version.  Thanks. 

## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Azure Powershell 

list here (V# not needed):  Version 5
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by amit-avit** [comment]
There is already a plan to make the newer modules available.
Meanwhile as a workaround you can add a step before AzurePowerShell task to add a PowerShell Script task with inline script to download the required module:

For Linux:
`
Save-Module -Path /usr/share/az_5.3.0 -Name Az -RequiredVersion 5.3.0 -Force -ErrorAction Stop
`

For Windows:
`
Save-Module -Path C:\Modules\az_5.3.0 -Name Az -RequiredVersion 5.3.0 -Force -ErrorAction Stop
`

**Comment by allantargino** [comment]
It worked perfectly, thank you very much @amit-avit! I mentioned this thread in similar issues so people can relate it.

**Comment by amit-avit** [comment]
@allantargino now you wouldn't need to do `save-module` manually and directly specifying the module version in task will work as we have updated the task. Also in windows we are already bundling version 5.5.0 locally and in a few weeks time similarly newer version of modules will be made available locally in ubuntu as well.

**Comment by allantargino** [comment]
That's awesome news @amit-avit ! Thanks for it!
