### ISSUE TITLE
[DockerInstaller@0] fails to Download 20.10.0

### ISSUE THREAD

**Issue by juwens** [microsoft/azure-pipelines-tasks#14175]
## Required Information

*Type*: Bug

**Enter Task Name**: DockerInstaller@0

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerInstallerV0

## Environment
- Server - Azure Devops Server
- Version: Dev17.M153.3

- Agent - Private: 
- Windows
- 2.153.1

## Issue Description

DockerInstaller fails to download anything newer than `17.09.0-ce`.

The current Version of Docker engine is 20.10.0
The latest available Version for Docker to install with `DockerInstaller` is `17.09.0-ce`.
Docker Team seems to moved their Downloads to another server location.

|No current release at the hard-coded download folder:|
|--|
| ![image](https://user-images.githubusercontent.com/11560817/103619895-d080e780-4f32-11eb-925d-dadff15a86db.png) |

### Task logs

```
##[section]Starting: DockerInstaller
==============================================================================
Task         : Docker CLI installer
Description  : Install Docker CLI on agent machine.
Version      : 0.1.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/docker-installer
==============================================================================
Downloading: https://download.docker.com/win/static/stable/x86_64/docker-20.10.0.zip
##[error]Error: Failed to download Docker from location https://download.docker.com/win/static/stable/x86_64/docker-20.10.0.zip. Error Error: Unexpected HTTP response: 404
##[section]Finishing: DockerInstaller
```

**Comment by Ganeshrockz** [comment]
@juwens Looks like Docker has stopped supporting CLI packages for windows. So we can only support till version `17.09`

**Comment by Ganeshrockz** [comment]
This is the issue that we filed on docker (https://github.com/microsoft/azure-pipelines-tasks/issues/14072)

**Comment by Ganeshrockz** [comment]
Closing it as stale issue since the author didn't get back
