### ISSUE TITLE
Azure Pipelines Test Service comments are overridden

### ISSUE THREAD

**Issue by DhirajKhot** [microsoft/azure-pipelines-tasks#14192]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines 
Account name : Office

- Agent - Private: 
Agent OS : Windows
Agent version : 2.179.0
    
## Issue Description

We have configured to run two build pipelines on our Pull Requests - 
Project-ServiceFabricApplications-CI (runs only unit tests)
Project-ServiceFabricApplications-PRValidation (runs only integration tests)
In both the pipelines we are using Visual Studio Test tasks to run unit tests and integration tests.

We have enabled code coverage on Project-ServiceFabricApplications-CI to collect the code coverage from unit tests.
The code coverage has NOT been enabled on Project-ServiceFabricApplications-PRValidation as it is expected to run only integration tests.

We keep getting the diff coverage comments on the pull requests raised from Azure Pipelines Test Service. 

The issue here is we get correct diff coverage comment when the Project-ServiceFabricApplications-CI build completes. 
But the same comment is overridden with incorrect data when the Project-ServiceFabricApplications-PRValidation  (mostly zero coverage as coverage is not collected)

Expected - 
The diff coverage comment should be driven only by the build pipeline in which code coverage has been enabled. In this case it is Project-ServiceFabricApplications-CI
There should be no comment related to diff coverage for Project-ServiceFabricApplications-PRValidation build

**Comment by DhirajKhot** [comment]
Hey @phanikmmsft / @damccorm 
Can you provide any updates on this issue?

**Comment by anshii03** [comment]
@DhirajKhot Code coverage is enabled through run settings file which you are using in VSTest task for integration tests . Once you use right run settings without code coverage enabled , you will not get coverage comment for integration tests pipeline.

**Comment by nishantms** [comment]
@DhirajKhot For now closing this issue, please feel free to reopen the issue, if problem persist.
