### ISSUE TITLE
Unexpected Coverage Status check on the Pull Request from the build where code coverage is not enabled

### ISSUE THREAD

**Issue by DhirajKhot** [microsoft/azure-pipelines-tasks#14194]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines 
Account name : Office

- Agent - Private: 
Agent OS : Windows
Agent version : 2.179.0

## Issue Description
We have configured to run two build pipelines on our Pull Request -
Project-ServiceFabricApplications-CI (runs only unit tests)
Project-ServiceFabricApplications-PRValidation (runs only integration tests)
In both the pipelines we are using Visual Studio Test tasks to run unit tests and integration tests.

We have enabled code coverage on Project-ServiceFabricApplications-CI to collect the code coverage from unit tests.
The code coverage has NOT been enabled on Project-ServiceFabricApplications-PRValidation as it is expected to run only integration tests.

Given this scenario I was expecting the policy for Coverage status check applied to the Pull Request only for Project-ServiceFabricApplications-CI. 
But the issue is we are observing both the Coverage status check policies (one from Project-ServiceFabricApplications-CI and another from Project-ServiceFabricApplications-PRValidation) applied to the Pull Request.

Can you please help in this issue?

Expected - 
Only one policy for Coverage Status check (of Project-ServiceFabricApplications-CI) should be applied to the Pull Request

**Comment by DhirajKhot** [comment]
Hey @phanikmmsft
Can you provide any updates on this issue?

**Comment by ankit-arora12** [comment]
@DhirajKhot Can you please provide the pipeline and build logs(with system.debug set to true) where this issue is observed?

**Comment by anshii03** [comment]
@DhirajKhot  Are you still facing this issue ? If yes , please share pipeline and build logs . Else , we will close this from our end.

**Comment by anshii03** [comment]
@DhirajKhot  As discussed offline ,Issue is because code coverage is enabled through run settings file for second pipeline. Closing this from our end now.
