### ISSUE TITLE
Inconsistent results of Azure Pipelines Test Service comments for similar coverage

### ISSUE THREAD

**Issue by DhirajKhot** [microsoft/azure-pipelines-tasks#14193]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines 
Account name: Office

- Agent - Private: 
Agent OS: Windows
Agent version : 2.179.0

## Issue Description
We have configured the Visual Studio Test task in our build pipeline and enabled to code coverage option to collect the coverage data for the code.
As a result we are getting the comments on the Pull Requests for the diff coverage as expected. 

But we could observe some inconsistency in the results of the comments from the Azure Pipelines Test Service for the scenarios where either code coverage data was not found or no executable changes were present in the pull request.

Refer below two examples - 
 
![image](https://user-images.githubusercontent.com/20378231/103993019-f4eef500-51ba-11eb-930c-5ba11f087672.png)

![image](https://user-images.githubusercontent.com/20378231/103993071-06380180-51bb-11eb-8504-e3b46bfbc7c4.png)

Can you please look into this?

Expected - 
If there are no executable changes found or the code coverage data is not found, the Diff coverage check should succeed and should be consistent.

**Comment by DhirajKhot** [comment]
Hey @phanikmmsft / @damccorm 
Can you provide any updates on this issue?

**Comment by anshii03** [comment]
@DhirajKhot As discussed , you are generating coverage from your run settings file . Once you fix that , this issue will no longer be there . Can we go ahead and close this ?

**Comment by anshii03** [comment]
Closing this issue as there is no action item from our end.
