### ISSUE TITLE
Support wildcards within targetPath in PublishPipelineArtifact@1

### ISSUE THREAD

**Issue by xamadev** [microsoft/azure-pipelines-tasks#14207]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PublishPipelineArtifact@1

## Environment
- Azure Pipelines

## Issue Description

It would be nice to support wildcards in targetPath argument. E.g. for selecting a generated nuget file - `bin/Release/*.nupkg` or even `bin/**/*.nupkg`

**Comment by sreich** [comment]
this issue should be reopened. 3 years and this is still a surprising shortcoming in this pipeline task
