### ISSUE TITLE
CMDLineV2 task not failing when executed program terminates due to error

### ISSUE THREAD

**Issue by jackdeansmith** [microsoft/azure-pipelines-tasks#14219]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CMDLineV2

## Environment
- Server: Azure Pipelines
- Account Name: SkyDrive
- Team Project Name: CrossPlatform
- Build definition name: iOS Run xPlat Unit Tests
- Agent: Hosted Mac Internal Mojave

## Issue Description

This pipeline is used as a PR gate in our repo to ensure that checked in code passes our unit tests. It consists of a few steps that create a test binary, then this "Run unit tests" step that executes the test binary: 

![Screen Shot 2021-01-12 at 5 31 48 PM](https://user-images.githubusercontent.com/5905702/104394733-0e19dd80-54fc-11eb-8c66-aed03a213a7c.png)

We recently noticed that this task succeeds in cases where the test executable terminates due to an error. In this case, a segfault:
![Screen Shot 2021-01-12 at 5 42 24 PM](https://user-images.githubusercontent.com/5905702/104395408-8af98700-54fd-11eb-8976-f06d18710d98.png)

Because of this, code that does not pass our unit tests was allowed into our repo. 

## Minimal Repro
I created a minimal repro by creating a pipeline with three steps: 
1. Create an executable which exits with an error by segfaulting 
![Screen Shot 2021-01-12 at 5 48 17 PM](https://user-images.githubusercontent.com/5905702/104395812-6225c180-54fe-11eb-8b4c-70e788e94db7.png)

2. Run the executable via the CmdLineV2 Task
![Screen Shot 2021-01-12 at 5 48 50 PM](https://user-images.githubusercontent.com/5905702/104395831-6f42b080-54fe-11eb-837c-fa3d66d3645c.png)

3. Run the executable via the BashV3 Task
![Screen Shot 2021-01-12 at 5 49 11 PM](https://user-images.githubusercontent.com/5905702/104395850-7bc70900-54fe-11eb-9986-71edef562293.png)

When I run this pipeline, task 2 succeeds while task 3 fails. Note that the printed script contents are not the same, for the CmdLineV2 task, the script is prepended with `exec`.
![Screen Shot 2021-01-12 at 6 01 22 PM](https://user-images.githubusercontent.com/5905702/104396778-2ee43200-5500-11eb-9729-85ac4f46e191.png)
![Screen Shot 2021-01-12 at 6 01 36 PM](https://user-images.githubusercontent.com/5905702/104396804-386d9a00-5500-11eb-9148-48616f3bc869.png)

Based on this and the final few debug message, I believe this is related to this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/13573

### Task logs

Production unit test pipeline logs: 
[logs_8835843.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5805858/logs_8835843.zip)

Logs for minimal repro: 
[logs_8852883.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5805900/logs_8852883.zip)

**Comment by EzzhevNikita** [comment]
@jackdeansmith The fix for has been deployed. Could you please check if it works for you now?

**Comment by jackdeansmith** [comment]
@EzzhevNikita I just tried again and everything is working as expected. Thanks for getting to the bottom of this!
