### ISSUE TITLE
Python Twine Upload Authenticate problem when feed name contains dot

### ISSUE THREAD

**Issue by bothzoli** [microsoft/azure-pipelines-tasks#14220]
This issue is to reopen #11521 which is not yet fixed.

Last comment by @tkrick was that it may be dangerous to simply replace all `\.` with `.`, but maybe it could be done for ini headers.
Any thoughts on that solution? I'm happy to contribute resolving this if that is acceptable for you.
If not, could this limitation be mentioned in the task documentation as to avoid hours of needless hunting for why the pipeline is not working as expected? I'm also happy to contribute to that.
Thanks!

Please see the bug report from that issue below:

**Question, Bug, or Feature?**
Bug

**Enter Task Name**: Python Twine Authenticate v0/v1 (I checked both versions)
## Environment

Azure Pipelines
## Issue Description

If a seed artifact contains a dot, for instance, "My.Feed", the task "Python Twine Upload Authenticate" will create the ".pypirc" as follows:

```
[distutils]
index-servers=My.Feed
[My\.Feed]
repository=https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed/pypi/upload
username=build
password=***
```

**Comment by bothzoli** [comment]
The issue all boils down to how the npm dependency [ini](https://www.npmjs.com/package/ini) works.

When encoding an object in an ini format, the dots in the object keys (`My.Feed` in the above example) will be escaped.
I attempted to create a failing test for this, however tests use the same package to parse the ini files, which will remove the escapes from the section headers and thus hiding this bug.

There is a way to directly give section header names (based on the above example):

```javascript
const feedName = "My.Feed";
const feedURI = "https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed/pypi/upload";
const username = "build";
const password = "***";

const repository = new Repository(feedURI, username, password);
ini.encode(repository, { section: feedName });
```

This will create the correct format
```ini
[My.Feed]
repository=https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed/pypi/upload
username=build
password=***
```

However since the test uses `ini.parse` it will now fail, as the parse will interpret sections with dots as a hierarchy and parse the above ini file as such:
```json
{
    "My": {
        "Feed": {
            "repository": "https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed/pypi/upload",
            "username": "build",
            "password": "***"
        }
    }
}
```

Thus, I think that the tests should not use `ini.parse` for the resulting file but rather check the file contents directly.
This would reveal the bug, and the above mentioned encode overload (using the `section` option) can then be used to fix the issue.

In case you agree with the above I'm happy to help implementing this.

**Comment by ivanst0** [comment]
@aasim, @phil-hodgson
The solution suggested by @bothzoli seems reasonable. I don't think it makes sense to use npm [ini](https://www.npmjs.com/package/ini) package in the test, since the generated config file is later read by twine - it uses [configparser](https://docs.python.org/3/library/configparser.html) which is not compatible with the npm ini package (for one thing, configparser doesn't understand `\.` escape sequence; there might be other differences).
Would you be ok with implementing this solution?

**Comment by bothzoli** [comment]
I've also found this package: [config-ini-parser](https://www.npmjs.com/package/config-ini-parser), which does the job (see below).
although I don't know how it's LGPL-3.0 License is compatible with MIT.

```javascript
import { ConfigIniParser } from "config-ini-parser";
import { EOL } from 'os';

const configIniParser = new ConfigIniParser(EOL);

const distutils = 'distutils';
const sectionName1 = 'My.Feed1';
const sectionName2 = 'My.Feed2';
const sectionNames = [sectionName1, sectionName2];

configIniParser
    .addSection(distutils)
    .set(distutils, 'index-servers', `${EOL}    ${sectionNames.join(`${EOL}    `)}`)
    .addSection(sectionName1)
    .set(sectionName1, 'repository', 'https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed1/pypi/upload')
    .set(sectionName1, 'username', 'build')
    .set(sectionName1, 'password', '***')
    .addSection(sectionName2)
    .set(sectionName2, 'repository', 'https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed2/pypi/upload')
    .set(sectionName2, 'username', 'build')
    .set(sectionName2, 'password', '***');

const stringValue = configIniParser.stringify(EOL);

console.log(stringValue);
// Prints:
// [distutils]
// index-servers=
//     My.Feed1
//     My.Feed2
// 
// [My.Feed1]
// repository=https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed1/pypi/upload
// username=build
// password=***
// 
// [My.Feed2]
// repository=https://pkgs.dev.azure.com/myorganization/_packaging/My.Feed2/pypi/upload
// username=build
// password=***
```

**Comment by ivanst0** [comment]
It seems that using [config-ini-parser](https://www.npmjs.com/package/config-ini-parser) is not an option here, due to GPL license.

@bothzoli, would you be willing to submit a PR with the original fix you suggested (using [ini](https://www.npmjs.com/package/ini) package to generate .pypirc file and not using it in the test)?

**Comment by janlugt** [comment]
I spent 2.5 hours on this today, until I ran into this issue. Until this is solved, can it be mentioned as a known issue somewhere in the documentation? This is really hard to troubleshoot right now.

**Comment by bothzoli** [comment]
@ivanst0 sorry I didn't have much time lately, but I finally started looking into it today.
hopefully I'll be able to get the PR ready within a few days.

**Comment by bothzoli** [comment]
I created the PR, although I can see that a few things are still missing.
Please feel free to review though, I'll try to update the PR with the requirements ASAP.

**Comment by bothzoli** [comment]
the PR has been ready for quite some time now. I don't know when it's expected to get merged.
