### ISSUE TITLE
Setting baseUrl in the webrequest URI resource

### ISSUE THREAD

**Issue by Anne56njeri** [microsoft/azure-pipelines-tasks#14224]
**Question**  
Hey, we are from the App config team. We pulled some of the code from azure-arm-rest folder, in the azure-arm-common file, in the “_[getMSIAuthorizationToken()](https://github.com/microsoft/azure-pipelines-tasks/blob/f462aeacedf56ceeeacd3d29027471a59573eaee/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-common.ts#L112)” function when setting the “web request.uri” you set the[ resource](https://github.com/microsoft/azure-pipelines-tasks/blob/f462aeacedf56ceeeacd3d29027471a59573eaee/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-common.ts#L119) to base URL, isn’t it supposed to be set to “ activeDirectoryResourceId” instead?
**Enter Task Name**:  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-common.ts

**Comment by 20shivangi** [comment]
@Anne56njeri You want this change for which task ?
Also, if something is breaking for you with our present scenario ?

**Comment by Anne56njeri** [comment]
@20shivangi yes MSI doesn't seem to be working for us since in the[ _getMSIAuthorizationToken()](https://github.com/microsoft/azure-pipelines-tasks/blob/f462aeacedf56ceeeacd3d29027471a59573eaee/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-common.ts#L119) the resource is set to `baseUrl` this results in 401 error code. A customer who tried using MSI on a private agent added the MSI for the agent to the App Config resource. The release pipeline is a simple private agent job and the only task is the App Config task. After investigation, we realized that the token was being fetched successfully but it was a token for the wrong resource since the resource was set to baseUrl. I was wondering if the[ resource](https://github.com/microsoft/azure-pipelines-tasks/blob/f462aeacedf56ceeeacd3d29027471a59573eaee/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-common.ts#L119) in the `_getMSIAuthorizationToken` is supposed to be to `baseUrl` or `activeDirectoryResourceId` it seems to work with `activeDirectoryResourceId`

**Comment by 20shivangi** [comment]
Please share the logs once with setting system.debug to true in your pipeline/release.

**Comment by Anne56njeri** [comment]
Debug log 
```

##[debug]e1a44093-facf-4598-8de8-4273b9d29886 auth param tenantid = ***
##[debug]e1a44093-facf-4598-8de8-4273b9d29886=https://management.azure.com/
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 data environment = AzureCloud
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 auth scheme = ManagedServiceIdentity
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 data msiclientId = undefined
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 data activeDirectoryServiceEndpointResourceId = https://management.core.windows.net/
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 data AzureKeyVaultServiceEndpointResourceId = https://vault.azure.net
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 data AzureKeyVaultDnsSuffix = vault.azure.net
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 auth param authenticationType = undefined
##[debug]e1a44093-facf-4598-8de8-4273b9d29886 data EnableAdfsAuthentication = false
##[debug]{"subscriptionID":"27ecc5df-75fd-470a-8215-794d8e807911","subscriptionName":"Leap-Dev-Vendor shared sub","environmentAuthorityUrl":"https://login.windows.net/","tenantID":"***","url":"https://management.azure.com/","environment":"AzureCloud","scheme":"ManagedServiceIdentity","activeDirectoryResourceID":"https://management.azure.com/","azureKeyVaultServiceEndpointResourceId":"https://vault.azure.net","azureKeyVaultDnsSuffix":"vault.azure.net","isADFSEnabled":false,"applicationTokenCredentials":{"domain":"***","baseUrl":"https://management.azure.com/","authorityUrl":"https://login.windows.net/","activeDirectoryResourceId":"https://management.azure.com/","isAzureStackEnvironment":false,"scheme":0,"isADFSEnabled":false}}
##[debug]Tags=undefined
##[debug][GET]http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/
##[error]Failed operation for 'Mvc:Settings:Messages' with label ''. Status code: 401
##[debug]Processed: ##vso[task.issue type=error;]Failed operation for 'Mvc:Settings:Messages' with label ''. Status code: 401
##[error]Failed operation for 'Mvc:Settings:Breath' with label ''. Status code: 401
##[debug]Processed: ##vso[task.issue type=error;]Failed operation for 'Mvc:Settings:Breath' with label ''. Status code: 401
##[error]Failed operation for 'Mvc:Settings:Sentinel' with label ''. Status code: 401
##[debug]Processed: ##vso[task.issue type=error;]Failed operation for 'Mvc:Settings:Sentinel' with label ''. Status code: 401
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: Azure App Configuration: MvcMoviesConfig

```

**Comment by 20shivangi** [comment]
@Anne56njeri Is this the task `Azure App Service Settings` ?
Also, please attach the full debug logs once with setting system.debug to true in your pipeline/release so that we can what version is it and all

**Comment by Anne56njeri** [comment]
The task is Azure App Configuration Push Task

**Comment by Anne56njeri** [comment]
```

  uri: 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/',
  headers: { Metadata: true } }
##[debug][GET]http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/
##[error]Failed operation for 'Mvc:Settings:Messages' with label ''. Status code: 401
##[debug]Processed: ##vso[task.issue type=error;]Failed operation for 'Mvc:Settings:Messages' with label ''. Status code: 401
##[error]Failed operation for 'Mvc:Settings:Breath' with label ''. Status code: 401
##[debug]Processed: ##vso[task.issue type=error;]Failed operation for 'Mvc:Settings:Breath' with label ''. Status code: 401
##[error]Failed operation for 'Mvc:Settings:Sentinel' with label ''. Status code: 401
##[debug]Processed: ##vso[task.issue type=error;]Failed operation for 'Mvc:Settings:Sentinel' with label ''. Status code: 401
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: Azure App Configuration: MvcMoviesConfig

```

**Comment by 20shivangi** [comment]
@Anne56njeri Although the common module i.e. AzureRmDeploy-common is being used by some of our tasks, yet the extension `Azure App Configuration Task` is not owned by us.
We will check if this api is being used by our task , meanwhile you can also create issue on the team here : https://github.com/Azure/AppConfiguration for your ask

**Comment by Anne56njeri** [comment]
@20shivangi sorry I had mentioned, am from the Azure App configuration Team I work on the `Azure App configuration and Azure App configuration push task`, we've implemented the code available in your repo from the `azure-arm-rest` folder, that is why we were wondering if in the azure-arm-common file, in the “_getMSIAuthorizationToken()” function when setting the “web request. URI” you set the resource to base URL, isn’t it supposed to be set to “ activeDirectoryResourceId” instead?

**Comment by AmrutaKawade** [comment]
Hey @Anne56njeri 

Here is flow of calls for`_getMSIAuthorizationToken` method from `AzureWebAppContainerV1` task.

https://github.com/microsoft/azure-pipelines-tasks/blob/e451e599bb6d375d0215601a105b6c80ac9105b7/Tasks/AzureWebAppContainerV1/azurermwebappdeploymentprovider.ts#L27

https://github.com/microsoft/azure-pipelines-tasks/blob/fe056f1b6dc63c8dd296c45d2d8870702e57ab7f/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service.ts#L28

https://github.com/microsoft/azure-pipelines-tasks/blob/fe056f1b6dc63c8dd296c45d2d8870702e57ab7f/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service.ts#L93

https://github.com/microsoft/azure-pipelines-tasks/blob/fe056f1b6dc63c8dd296c45d2d8870702e57ab7f/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/AzureServiceClient.ts#L117

https://github.com/microsoft/azure-pipelines-tasks/blob/fe056f1b6dc63c8dd296c45d2d8870702e57ab7f/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-common.ts#L89




**this value of baseurl is coming from service connection used in task**

https://github.com/microsoft/azure-pipelines-tasks/blob/e451e599bb6d375d0215601a105b6c80ac9105b7/Tasks/AzureWebAppContainerV1/taskparameters.ts#L30

https://github.com/microsoft/azure-pipelines-tasks/blob/fe056f1b6dc63c8dd296c45d2d8870702e57ab7f/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-endpoint.ts#L93

and activeDirectoryResourceId and baseUrl has same value thats why its working for us. Please check your flow of task


https://github.com/microsoft/azure-pipelines-tasks/blob/fe056f1b6dc63c8dd296c45d2d8870702e57ab7f/Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-endpoint.ts#L90

**Comment by Anne56njeri** [comment]
Thank you @AmrutaKawade  let me check it out then get back.

**Comment by AmrutaKawade** [comment]
@Anne56njeri let us know if you need more info or can we close this issue?

**Comment by Anne56njeri** [comment]
@AmrutaKawade It makes sense, I think we can close the issue. Thank you for your response.
