### ISSUE TITLE
DotnetCoreCLI task should fail when no tests are found

### ISSUE THREAD

**Issue by EwanNoble** [microsoft/azure-pipelines-tasks#14232]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLI  

## Issue Description

After a project restructuring earlier today our pipelines stopped running tests and went unnoticed for longer than desired due to pipelines remaining green. Currently when `dotnet test` is run and no tests are found this is only logged as a warning: 
https://github.com/microsoft/azure-pipelines-tasks/blob/f462aeacedf56ceeeacd3d29027471a59573eaee/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L154

Ideally this should throw an error, or at least be configurable to do so.

### Task logs

`##[warning]Project file(s) matching the specified pattern were not found.`

**Comment by beatcracker** [comment]
> Ideally this should throw an error, or at least be configurable to do so.

I'd vote for configurable since, I, for one, use a single template for dozens of projects and not all of them have tests. Making this task fail when no tests are found would be a breaking change.
