### ISSUE TITLE
Courtesy push pipeline should notify on failures

### ISSUE THREAD

**Issue by damccorm** [microsoft/azure-pipelines-tasks#14231]
## Issue Description

This is related to #14230 - right now if our courtesy push pipeline fails, it does so silently. We should add an extra step to the pipeline that checks if it was a courtesy push run, only runs on failure, and notifies the team that it failed so that we can manually intervene. It could use our slack integration like we do here - https://github.com/microsoft/azure-pipelines-tasks/blob/f462aeacedf56ceeeacd3d29027471a59573eaee/ci/courtesy-push.yml#L57

I'm routing this to our ABTT team, I'm happy to help out on this one though, just ping me or tag me here if any questions pop up

**Comment by EzzhevNikita** [comment]
Created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14236)
