### ISSUE TITLE
typed-rest-client/HttpClient missing from ContainerStuctureTest task

### ISSUE THREAD

**Issue by ssaarinen** [microsoft/azure-pipelines-tasks#14247]
*Type*: Bug

**Enter Task Name**: ContainerStructureTestV0  

## Environment
- Azure Pipelines
- Agent - Hosted 

```    
pool:
  name: Hosted Ubuntu 1604
```

## Issue Description

Task fails:

```
Starting: Container Structure Test
==============================================================================
Task         : Container Structure Test
Description  : Uses container-structure-test (https://github.com/GoogleContainerTools/container-structure-test) to validate the structure of an image based on four categories of tests - command tests, file existence tests, file content tests and metadata tests
Version      : 0.179.0
Author       : Microsoft Corporation
Help         : https://aka.ms/containerstructuretest
==============================================================================
##[error]Unhandled: Cannot find module 'typed-rest-client/HttpClient'
Finishing: Container Structure Test
```

## Workaround
https://github.com/microsoft/azure-pipelines-tasks/issues/14247#issuecomment-768834565

**Comment by Ivanov-Alexander** [comment]
Same for me, as option you can try:


`-   script: |

            docker build -f ./Dockerfile -t some-service:$(Build.BuildNumber) .
            docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(System.DefaultWorkingDirectory)/image-tests.yml:/tests_config.yaml --name container-structure-test gcr.io/gcp-runtimes/container-structure-test:latest test --image some-service:$(Build.BuildNumber) --config tests_config.yaml --test-report output.json
            docker cp container-structure-test:/output.json $(System.DefaultWorkingDirectory)/container-structure-test-results.json
            docker rm -fv container-structure-test
            failedCount=$(cat container-structure-test-results.json | jq .Fail)
            cat container-structure-test-results.json | jq . ;
            if [[ $failedCount -gt 0 ]]
                then
                echo "##vso[task.logissue type=error]container-structure-tests failed.";
                exit 1;
            fi
        displayName: Run Container Structure Test`

**Comment by ssaarinen** [comment]
actually I used this as a workaround (found by others having similar issues):
```
- script: npm install typed-rest-client --save 
  displayName: Azure DevOps Patch Install missing packages for ContainerStructureTest

- task: ContainerStructureTest@0
  ...
```

Don't know if `--save` is actually needed on `npm install`

**Comment by Ivanov-Alexander** [comment]
@ssaarinen thx, much elegant solution

**Comment by ssaarinen** [comment]
this is still very much happening :/
