### ISSUE TITLE
Ubuntu 20.04 is not a selectable gallery image in Pipelines

### ISSUE THREAD

**Issue by JimmyBanks** [microsoft/azure-pipelines-tasks#14245]
Feature
*Type*: Release Build

**Enter Task Name**: PackerBuildV1

## Environment
Azure Pipelines

- Agent - Hosted or Private: Hosted

## Issue Description
Ubuntu 20.04 is not available in:
Releases->Tasks->Build Machine Image->Auto Generated Packer Template->Gallery Image

The Ubuntu version available to be selected as an image are 14.04.4, 16.04, and 18.04

Ubuntu 20.04 image is available elsewhere on Azure, I believe it should be added as a selectable option for machine images

**Comment by JimmyBanks** [comment]
@bishal-pdMSFT Hi Bishal, I was just wondering if there is a timeline for this packer update?

**Comment by t-dedah** [comment]
@JimmyBanks We are working on this fix.

**Comment by JimmyBanks** [comment]
@bishal-pdMSFT no, not ready to be closed, this has not been implemented. Still waiting on a reply from Bishal, after 6 months wait.

Hello Bishal how about a reply.
