### ISSUE TITLE
helm uninstall command is not available in HelmDeploy task

### ISSUE THREAD

**Issue by onlyutkarsh** [microsoft/azure-pipelines-tasks#14250]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Helm Deploy

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines

- Agent - Hosted or Private: 
    
    Private, RHEL 
    Current agent version: '2.177.1'

## Issue Description

In Helm 3, delete command has been renamed to uninstall as per the [docs](https://helm.sh/docs/helm/helm_delete/#helm-delete). But the Azure DevOps "Package and deploy Helm charts" task still shows delete command. Is there any plan to update the task to reflect new changes?
![image](https://user-images.githubusercontent.com/2685029/105161109-e97bc200-5b08-11eb-9cbd-6389c6779212.png)

**Comment by shigupt202** [comment]
Helm task supports both Helm 2 and Helm 3. I don't think removing `delete` would be possible at the moment. Can you try specifying uninstall explicitly in the Command field and remaining parameters in the arguments and then run the pipeline?

**Comment by onlyutkarsh** [comment]
Understand. It works but gives validation warning as there is list of valid values for `command` field. Would be good if `custom` option is added to the pickList, allowing us to execute custom commands.

https://github.com/microsoft/azure-pipelines-tasks/blob/e5a345be00dd924af015c62cb6c1437a375f8b00/Tasks/HelmDeployV0/task.json#L173-L186

![image](https://user-images.githubusercontent.com/2685029/105330572-5d31d380-5bca-11eb-94c9-aac17b9cf6d2.png)

**Comment by shigupt202** [comment]
Got it. We will add it to our backlog. In the mean time you can continue with the above approach. 
If possible, you can also raise a PR for this if you'd like a quick fix. I'll take it forward.

**Comment by onlyutkarsh** [comment]
yep.. will do. thanks for looking in to it. I will keep the issue open and link to this if I raise a PR if its okay?

**Comment by shigupt202** [comment]
Sure

**Comment by onlyutkarsh** [comment]
Tried to work on this, but hitting the issue mentioned https://github.com/microsoft/azure-pipelines-tasks/issues/11136. I see a PR related to that issue has been merged but I still cannot build the extension. **Any suggestions?**

After `npm install` I am trying to build the extension with command `node make.js build --task HelmDeployV0` but error I see is as below

```
$ node make.js build --task HelmDeployV0

> prepending PATH /Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/node_modules/.bin
tsc tool:
Version 2.3.4
/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/node_modules/.bin/tsc
npm tool:
6.14.8
/Users/utkarsh/.nvm/versions/node/v12.20.0/bin/npm

------------------------------------------------------------
Building: HelmDeployV0
------------------------------------------------------------

Building module /Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/Tasks/Common/utility-common-v2

> cd Tasks/Common/utility-common-v2

> npm install

> tsc --outDir "/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/_build/Tasks/Common/utility-common-v2" --rootDir "/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/Tasks/Common/utility-common-v2"

> cd ../../..

> copying module resources
copying *.ps1
copying *.psd1
copying *.psm1
copying *.sh
copying *.txt
copying icon.png
copying icon.svg
copying module.json
copying node_modules
copying package.json
copying Strings
copying task.json
copying task.loc.json
copying Tests

> getting module externals
Downloading file: https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip
/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/node_modules/sync-request/index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/node_modules/sync-request/index.js:77:11)
    at doRequest (/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/node_modules/sync-request/index.js:20:10)
    at downloadFile (/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/make-util.js:411:22)
    at downloadArchive (/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/make-util.js:451:27)
    at /Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/make-util.js:644:33
    at Array.forEach (<anonymous>)
    at getExternals (/Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/make-util.js:639:25)
    at /Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/make.js:235:25
    at Array.forEach (<anonymous>)
    at /Users/utkarsh/Documents/_DEV/GitHub/utkarshforks/azure-pipelines-tasks/make.js:203:20
```

**Comment by shigupt202** [comment]
Can you try updating the node version to `v10.16.3`? If that doesn't work, you can try to manually download this package as stated in the mentioned issue. If that also doesn't work, we will take it up.

**Comment by onlyutkarsh** [comment]
Great! Downgrading node to v10.16.3 worked. I have two approaches to support uninstall commands. Can you let me know what is the preference?

1) Change to `task.json` so that I add `uninstall` command to the list of supported commands.
   **Pros**: Removes validation warning shown above
   **Cons**: Works only for `uninstall` command

2) Add `custom` option to `command` field and add additional single line text field to capture any custom command. Then pass the command and arguments to helm cli using `helmcli.ts`. I have verified and it should work seamlessly with existing code.
   **Pros**: Should work for any command in the future
   **Cons**: I am not planning to support any UI for the commands.

BTW, without any of my changes, If I run L0 tests on the task, one test fails. Hope I can just ignore it. Let me know. 

![image](https://user-images.githubusercontent.com/2685029/105639636-5aa4d780-5e71-11eb-9727-772f00f9adab.png)

**Comment by shigupt202** [comment]
The custom command is supported even today. You can give any input to the command field, so I don't think it makes sense to add `custom` option. You can add `uninstall` command.
The L0's should have passed, otherwise the checks in your PR will fail. Can you pull latest master and check again?

**Comment by onlyutkarsh** [comment]
yeah, only issue with already supported custom command is that, YAML is getting validated by what's in the task.json "command" field. So any custom command user types which is not in the list of allowed values will give warning in YAML. I was trying to avoid that. Let me know if its okay for now and I will just commit the task.json file which has "uninstall" added to the list.

**Comment by shigupt202** [comment]
Sure, please go ahead with the change

**Comment by onlyutkarsh** [comment]
> The L0's should have passed, otherwise the checks in your PR will fail. Can you pull latest master and check again?

Got the latest from master, still a test fails for me. Can you please review the changes [here](https://github.com/microsoft/azure-pipelines-tasks/compare/master...utkarshforks:feature/add-uninstall-json) and see if I have made any mistake?

![image](https://user-images.githubusercontent.com/2685029/106355686-9288a080-62f1-11eb-82f9-0f0073444384.png)

**Comment by shigupt202** [comment]
I'm not able to see the details of the failed test. Can you please raise a PR, updating the versions in task.json and task.loc.json to 0.183.0? (It should probably be some platform dependencies issue. If the tests fail in the PR as well we'll debug it then.)

**Comment by onlyutkarsh** [comment]
hey @shigupt202 - not sure if notification triggered for you, but I raised a pr #14332 for this and tests seem to pass. do let me know if any changes required.

**Comment by shigupt202** [comment]
I didn't get notified for the change. Thanks for pointing it out. I'll review it.
