### ISSUE TITLE
Publish Build Artifact from Linux Agent

### ISSUE THREAD

**Issue by phenixita** [microsoft/azure-pipelines-tasks#14253]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Publish build artifacts

Hi team,
at the time of this writing the Publish build artifacts task only supports Windows agents when used in the file share mode. Is there any plan to support the scenario also for Linux agents?

![image](https://user-images.githubusercontent.com/17789308/105201155-d684e400-5b40-11eb-8f3e-68ea393b7e32.png)

**Comment by Valks** [comment]
Is there any feedback on this feature request?

While I see the bot has closed due to lack of activity it would be nice to find out if it's something been considered?

**Comment by anatolybolshakov** [comment]
Hi @Valks current implementation uses robocopy for file share as a target which is not supported on Linux - it will require some additional time to investigate acceptable solution for this platform.
We are working on more prioritized requests/features at the moment - so will be get back to this later to proceed on it further.
