### ISSUE TITLE
AzureResourceGroupDeployment@2 doesn't support multi-line strings

### ISSUE THREAD

**Issue by renenaplava** [microsoft/azure-pipelines-tasks#14268]
*Type*: bug

**Enter Task Name**: AzureResourceGroupDeployment  

## Environment
- Azure Pipelines
- Agent Info:
    
![image](https://user-images.githubusercontent.com/33029406/105489820-26d08300-5cb4-11eb-813c-c5b836f2a4cf.png)

## Issue Description

It seems like the **AzureResourceGroupDeployment** task doesn't handle correctly multi-lines in my ARM template. There is a user-defined function in my template. While this version is deployed without any problem 
![image](https://user-images.githubusercontent.com/33029406/105490617-50d67500-5cb5-11eb-92c6-058ebb5e8a5d.png)
the version when the value is split into multiple lines is failing:
![image](https://user-images.githubusercontent.com/33029406/105490741-84b19a80-5cb5-11eb-9a38-43bf4670d905.png)

According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#multi-line-strings) this should work. And actually, the ARM template is deployed successfully when the PowerShell is used. But when I'm trying to deploy it with use of Azure Resource Group Deployment Task, it fails:

> 2021-01-22T11:50:15.6031626Z Creating deployment parameters.

> 2021-01-22T11:50:15.6205264Z The detected encoding for file 'D:\a\1\s\infra\configuration\DailyProcessing\azuredeploy.json' is 'utf-8'

> 2021-01-22T11:50:15.6318501Z ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting

> 2021-01-22T11:50:15.6340620Z (node:1588) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

> 2021-01-22T11:50:15.6346063Z ##[error]Error: Ensure the Template file ( 'D:\a\1\s\infra\configuration\DailyProcessing\azuredeploy.json' ) is valid. Task failed while parsing with following error: Unexpected token in JSON at position 2127

> 2021-01-22T11:50:15.6449989Z ##[section]Finishing: DailyProcessing-ru (configuration)

FYI, here is the screenshot of my testing pipeline I'm using to deploy the ARM template as well:

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/33029406/105491786-2a193e00-5cb7-11eb-8968-935a4feaca9c.png)

### Error logs

> 2021-01-22T11:50:15.6318501Z ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting

> 2021-01-22T11:50:15.6340620Z (node:1588) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

> 2021-01-22T11:50:15.6346063Z ##[error]Error: Ensure the Template file ( 'D:\a\1\s\infra\configuration\DailyProcessing\azuredeploy.json' ) is valid. Task failed while parsing with following error: Unexpected token in JSON at position 2127

**Comment by hwride** [comment]
I can confirm I have seen this as well. Ensured the ARM template had a schema set to the latest value in case that had an effect (`https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#`).

This would be very useful to have, more complex statement are difficult maintain when they are all on a single line.

**Comment by PatrickMessierGoC** [comment]
I'm having a [similar issue with the ARM template deployment@3 task](https://developercommunity.visualstudio.com/content/problem/1321175/arm-deployment-task-fails-on-templates-with-multi.html). I originally thought it was an issue with Azure DevOps since I was running the ARM template successfully through Azure CLI.

**Comment by hwride** [comment]
Just commenting to say this is definitely still something we would find useful 👍
