### ISSUE TITLE
Add OS validation before deployment

### ISSUE THREAD

**Issue by aressler38** [microsoft/azure-pipelines-tasks#14272]
*Type*: Feature

**Enter Task Name**: AzureFunctionApp  

## Environment
Hosted AzureDevOps Agent.

## Issue Description

It would be good if the AzureFunctionApp task verified the host OS before deploying and provide a user-friendly error message if something is mismatched. For example, if you have a Windows app service setup, but you deploy using the "functionAppLinux" appType, then you get a confusing error message (see below). It looks like some of the code knows how to go get certain properties about the function app in Azure, so it should be able to verify if the app service host OS is Windows or Linux. A quick validation and proper error message would be helpful. 

The background is that I ran into this error when migrating function apps and consolidating app service plans. I didn't realize that updated ARM template to configure the app service plan was not set for Linux. The app service plan deployed fine, but it was Windows, so when I ran the deployment pipeline, I got an error that led me on a debugging hunt.

A simple error message like the following would be helpful: "The app to deploy specified {os} appType, but the host machine is running {hostOS}. Please verify your app service settings." 

### Error logs

Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
Generating deployment script for Web Site
Running deployment command...
Command: "C:\home\site\deployments\tools\deploy.cmd"
Handling Basic Web Site deployment.
Creating app_offline.htm
Error: Could not find file 'C:\home\site\wwwroot\host.json'.
KuduSync.NET from: 'C:\local\Temp\zipdeploy\extracted' to: 'C:\home\site\wwwroot'
Copying file: 'host.json'
Failed exitCode=1, command="kudusync" -v 50  -f "C:\local\Temp\zipdeploy\extracted" -t "C:\home\site\wwwroot" -n "C:\home\site\deployments\dd41704c933f4a71811c1e22b399b02f\manifest" -p "C:\Program Files (x86)\SiteExtensions\Kudu\91.21119.4922\bin\Scripts\firstDeploymentManifest" -i ".git;.hg;.deployment;deploy.cmd"
**An error has occurred during web site deployment.**
Error: Could not find file 'C:\home\site\wwwroot\host.json'.\r\nC:\Program Files (x86)\SiteExtensions\Kudu\91.21119.4922\bin\Scripts\starter.cmd "C:\home\site\deployments\tools\deploy.cmd"
##[error]Failed to deploy web package to App Service.
##[error]To debug further please check Kudu stack trace URL : [url]
##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by amit-avit** [comment]
We can't add any logic or validation in the task, we just pass on any returned errors that we get as is from the kudu rest api's. We return the stack trace url for you to further debug.
The task assistant while setting up yaml/release pipeline does show filtered out values to help in choosing the right values based on the subscription and app service type.
