### ISSUE TITLE
AzureFunctionAppContainer@1 ACR Authentication

### ISSUE THREAD

**Issue by ElvenSpellmaker** [microsoft/azure-pipelines-tasks#14277]
**Question, Bug, or Feature?**  
Question

**Enter Task Name**: AzureFunctionAppContainer@1

## Environment
 - Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: `windows-latest` currently.

## Issue Description

When using this task to try and deploy an image from an ACR it seems the container fails to start, the ACR has admin access enabled.

The task example shown here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-functionapp-containers?view=azure-devops
![image](https://user-images.githubusercontent.com/2286713/105021523-89214d80-5a40-11eb-8a6e-09601fe2c732.png)

It doesn't show adding any credentials for the ACR, and so I assume it should add the creds for you.

Is this something that needs to be manually added somehow, or added as a parameter under `configurationStrings` (but wouldn't that leak the password into the build)?

At what point in the process is the best place to add the variables if they're needed and not supplied by this task?

If so the documentation seems to need a clarification note saying the variables must be added as it points nowhere and uses an ACR as an example.

For now I'll just use:
```
    az webapp config container set `
          --resource-group "$(ResourceGroupName)" `
          --name "$(FunctionAppName)" `
          --docker-custom-image-name "$(FunctionImage)" `
          --docker-registry-server-url "https://$(DockerRegistryUrl)" `
          --docker-registry-server-user "$registryUsername" `
          --docker-registry-server-password "$registryPassword" `
          --enable-app-service-storage false `
          --slot Staging
```
instead of the task as the task doesn't support ACR authorisation.

(Although ARM keeps removing the variables which is painful, although another topic... 😬)

### Task logs
![image](https://user-images.githubusercontent.com/2286713/105022699-f8e40800-5a41-11eb-8ed1-afd599751496.png)

### Error logs
![image](https://user-images.githubusercontent.com/2286713/105023022-58421800-5a42-11eb-81f2-f3dbe6d164f8.png)

**Comment by cmendible** [comment]
Same thing is happening tome running `AzureWebAppContainer@1`

**Comment by ElvenSpellmaker** [comment]
It seems the underlying task looks for an ImageSource parameter but the wrapper tasks don't allow you to specify it

**Comment by 20shivangi** [comment]
@ElvenSpellmaker Please let me know if you find this helpful :https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/function-app-container?view=azure-devops&tabs=yaml#configure-registry-credentials-in-function-app
This doc mentions step on how to add your registry and image to pull the private image in function app

**Comment by 20shivangi** [comment]
@ElvenSpellmaker Have you checked the above doc ? Any update here ?

**Comment by 20shivangi** [comment]
There has been no response, so we are closing the issue. Please feel free to reopen in case of any queries.

**Comment by ElvenSpellmaker** [comment]
Of course the issue still exists, linking to some other documentation doesn't help the fact the original documentation doesn't state anything about credentials leaving people to believe the task should set them up for you...

**Comment by ElvenSpellmaker** [comment]
I know how to add credentials manually and did so before I opened the issue, but that doesn't answer the issue that either the task should set the credentials for you or allow you to pass them in to be set by the task.
