### ISSUE TITLE
PublishCodeCoverageResults@1 removes JavaScript on index.html page of coverage report 

### ISSUE THREAD

**Issue by RoykoSerhiy** [microsoft/azure-pipelines-tasks#14280]
## Required Information

Seems so that task is removing all JavaScript from index.html file of coverage report. After report coverage publishing in Code Coverage tab I see coverage information but I don`t see collapse buttons, grouping, and filter. When I'm doing report locally with the same params I have all JavaScript inside index.html and collapse buttons, grouping, and filter are visible. Is this are expected behavior and why this happens? Also what means "Modifying Cobertura Index file" in task log. (screenshots are attached). HTMLInline report type is used.

**Question, Bug, or Feature?**  
*Type*: **Question**

**Expected:**
![expected_ed](https://user-images.githubusercontent.com/10273500/105848384-8f3a9f80-5fe7-11eb-9df2-cc1dca8f2dd2.jpg)
**Actual:** 
![actual_ed](https://user-images.githubusercontent.com/10273500/105848415-9b266180-5fe7-11eb-875f-6ff90ae01c82.jpg)
**Logs:** 
![task-log](https://user-images.githubusercontent.com/10273500/105848477-b2654f00-5fe7-11eb-94cf-529dbe4d217b.JPG)

**Local report index.html file content:**
![local-index](https://user-images.githubusercontent.com/10273500/105849255-cbbacb00-5fe8-11eb-9f84-23fb0a9cec12.JPG)
**ADO Task report index.html file content:**
![task-index](https://user-images.githubusercontent.com/10273500/105849317-e2612200-5fe8-11eb-8923-09c5f3dfd2b9.JPG)

**Comment by ganesp** [comment]
@RoykoSerhiy You seem to be using report generator tool directly to generate the report.
If you are using Publish Code Coverage Results task then, it internally uses ReportGenerator 4.6.1.0 (https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishCodeCoverageResultsV1/make.json)

Also, this is also evident as you clarified that you are specifying the report type yourself, which Publish Code Coverage Results task does no expose -- rather it uses HtmlInline_AzurePipelines report type.

I recommend you to use Publish Code Coverage Results tasks directly and remove any usage of the ReportGenerator task from your pipeline completely.

Please let me know if you have further queries.

**Comment by RoykoSerhiy** [comment]
> @RoykoSerhiy You seem to be using report generator tool directly to generate the report.
> If you are using Publish Code Coverage Results task then, it internally uses ReportGenerator 4.6.1.0 (https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishCodeCoverageResultsV1/make.json)
> 
> Also, this is also evident as you clarified that you are specifying the report type yourself, which Publish Code Coverage Results task does no expose -- rather it uses HtmlInline_AzurePipelines report type.
> 
> I recommend you to use Publish Code Coverage Results tasks directly and remove any usage of the ReportGenerator task from your pipeline completely.
> 
> Please let me know if you have further queries.

I've tried remove report generator and use built-in ReportGenerator, but still see simple html table without filters, expands, icons, javascript and have HtmlInline_AzurePipelines report type:
![image](https://user-images.githubusercontent.com/10273500/111301967-7b143580-865b-11eb-844c-5f18a9e40ca2.png)

**Comment by ganesp** [comment]
> I've tried remove report generator and use built-in ReportGenerator, but still see simple html table without filters, expands, icons, javascript and have HtmlInline_AzurePipelines report type:

@RoykoSerhiy 
Can you please clarify what do you mean by built-in report generator here?
Are you using this task to publish code coverage results?
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops

**Comment by ganesp** [comment]
Not enough information to proceed further with the investigation.

**Comment by sj-net** [comment]
This task only does the basic report generating. There are some additional options that report generator is supporting. Is there any way to supply those options from this task to the report generator ?

**Comment by sj-net** [comment]
A temporary work around I had to do is 

1. Use report generator task or install it as global and generate a report that you want. Here you can use what ever options that you need.
2. In PublishCodeCoverageResults@1 task, add option for `reportDirectory` and ensure that points towards the directory that contains HTML files. 
3. Add a new variable to the variable section `  disable.coverage.autogenerate: 'true'`. This prevents the PublishCodeCoverageResults@1 task from generating  a new html report with it's own options.

Note: Unfortunately the JS related features like expand all , collapse all etc will be stripped down in your coverage tab.
