### ISSUE TITLE
DownloadPackage@1 ignores specified view

### ISSUE THREAD

**Issue by ChrisGibson1982** [microsoft/azure-pipelines-tasks#14285]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Type*: Bug

**Enter Task Name**: DownloadPackage@1 

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
Private Agent, Windows 2019, Pipelines agent 2.181.0

## Issue Description

DownloadPackage@1 ignores the view of the artifact.  It doesn't matter if you specify a version or latest

        - task: DownloadPackage@1
          displayName: Download Dev
          inputs:
            packageType: 'upack'
            feed: '/guid of feed'
            view: 'guid of view'
            definition: 'guid of package'
            version: '0.520.30'
            downloadPath: '$(System.ArtifactsDirectory)/dev'

        - task: DownloadPackage@1
          displayName: Download Dev
          inputs:
            packageType: 'upack'
            feed: '/guid of feed'
            view: 'guid of view'
            definition: 'guid of package'
            version: '*'
            downloadPath: '$(System.ArtifactsDirectory)/dev'

If I have version 0.520.30 which has the views "dev" and "tst".  I could specify that my download task uses the view "uat", but it will still download 0.520.30, if I specify it as the version.  If my latest package hasn't been promoted to the view "tst" or "uat" I can still download these versions even if I specify the "tst" or "uat" view in my task.

I would expect the view to stop me downloading any package that doesn't have that view specified, otherwise what's the point of it?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
No errors or failures, it's more odd behaviour

### Error logs

No error produced

**Comment by aasim** [comment]
Thanks @ChrisGibson1982 for reporting this, I have put out a fix which should go out in prod probably by next week. Let me know if you need any immediate assistance until then.

**Comment by ChrisGibson1982** [comment]
Thanks @aasim if you get a chance, please can you confirm when this has gone in

**Comment by ChrisGibson1982** [comment]
This now appears to be working.
