### ISSUE TITLE
%25 detected in ##vso command in some Tasks

### ISSUE THREAD

**Issue by ElvenSpellmaker** [microsoft/azure-pipelines-tasks#14302]
## Note  
```
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
```

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: 

 - AzureResourceManagerTemplateDeployment@3
 - FileTransform@2
EDIT: 
 - Docker@2
 - PublishTestResults@2
 - CopyFile@2
 - AzureRmWebAppDeployment@3
 - AzureCli@2 (with % in parameter or inline script)
 - AzureResourceGroupDeployment@2
 - Kubernetes@1
 - PythonScript@0
 - HelmDeploy@0

## Issue Description

As of today we've been getting warnings in Template deploys and in FileTransforms relating to the % encoding feature. The tasks seem to be emitting `##vso` commands which contain these characters and so clutter our build logs with warnings.

### Task logs

![image](https://user-images.githubusercontent.com/2286713/106165051-9518b800-6182-11eb-9e09-8c6ad518abfc.png)
![image](https://user-images.githubusercontent.com/2286713/106164967-7d413400-6182-11eb-9ccd-84cd1c959528.png)

**Comment by brunofitas** [comment]
I have the exact same issue on Docker@2. 
It started only a few hours ago


    jobs:
      - job: BuildAndPush
        displayName: Build and Push Image
        pool:
          vmImage: ubuntu-16.04
         steps:

          - task: Docker@2
             inputs:
             command: login
             containerRegistry: docker-service-connection

          - task: Docker@2
             displayName: Build and push image
             inputs:
              command: buildAndPush
              containerRegistry: docker-service-connection
              repository: ${{ parameters.imageRepository }}
              dockerfile: ${{ parameters.dockerfilePath }}
              tags: |
                ${{ parameters.tag1 }}
                ${{ parameters.tag2 }}


output: 

    ##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this 
    to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior 
    immediately. More information can be found at https://github.com/microsoft/azure-pipelines- 
    agent/blob/master/docs/design/percentEncoding.md

**Comment by ben790924** [comment]
I have the same issue. Also, release is not triggered after a new build is available. I am sure it was working but this time wasn't.

**Comment by bahadir-be** [comment]
Same issue!!

![Uploading image.png…]()

**Comment by weshaggard** [comment]
We have started hitting this with the PublishTestResults task as well:
```
==============================================================================
Task         : Publish Test Results
Description  : Publish test results to Azure Pipelines
Version      : 2.171.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
==============================================================================
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
```

These are coming from tasks that are build in this repo and so it seems like we need to get these all updated before we start blasting everyone's builds with these warnings.

**Comment by skipper09** [comment]
We are seeing this warning during our build when we push a Docker image to a container registry

**Comment by ElvenSpellmaker** [comment]
> Same issue!!
> 
> Uploading image.png…

Which tasks is this? Your image is broken.

**Comment by AjkayAlan** [comment]
Bumping, we get this with when using:
```
- task: CopyFiles@2
```

**Comment by PetrPospisil** [comment]
maybe related to this?
microsoft/azure-pipelines-agent#3204

it also happens to us
AzureCli@2 (with % in parameter or inline script)
AzureRmWebAppDeployment@3 (did not try to update to @4 yet)

**Comment by mmajcica** [comment]
Same here.

![image](https://user-images.githubusercontent.com/3026551/106353978-c31b0b00-62ee-11eb-9fc2-38812468c69f.png)

**Comment by ElvenSpellmaker** [comment]
Which commands? I'm trying to keep an updated list in my issue

**Comment by mmajcica** [comment]
> Which commands? I'm trying to keep an updated list in my issue

I get it by using AzureResourceGroupDeployment@2
Not sure what commands internally are used.

**Comment by talkwithsrinivas** [comment]
I see this too. But this is happening when the nuget security analysis job runs (This is injected by policy. So i do not control it).

__**Nuget Security Analysis (auto-injected by policy)
Starting: Nuget Security Analysis (auto-injected by policy)
==============================================================================
Task         : Nuget Security Analysis
Description  : A task to scan for vulnerabilities in nuget files.
Version      : 0.1.60
Author       : Microsoft Corporation
Help         : See https://aka.ms/nugetsecurityanalysis for more information. Please contact OpenSourceEngSupport@microsoft.com if you run into problems or have questions with this task.
==============================================================================
For more information please visit: https://aka.ms/nugetsecurityanalysis
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
Finishing: Nuget Security Analysis (auto-injected by policy)_**_

**Comment by cocowalla** [comment]
> (did not try to update to @4 yet)

Same with v4

**Comment by bahadir-be** [comment]
> 
> 
> > Same issue!!
> > Uploading image.png…
> 
> Which tasks is this? Your image is broken.
![image](https://user-images.githubusercontent.com/62173919/106462760-cd780900-6496-11eb-92db-7244def28d80.png)

**Comment by jensneubauer** [comment]
I'm getting the warning when calling set image in kubectl:

`[command]C:\ProgramData\Chocolatey\bin\kubectl.exe set -n frontend image xxx=yyy -n frontend -o json`

YAML:


```
steps:
- task: Kubernetes@1
  displayName: 'Set Image Frontend'
  inputs:
    kubernetesServiceEndpoint: 'endpoint'
    namespace: frontend
    command: set
    arguments: 'image xxx=yyy:$(Release.Artifacts._Frontend.BuildId) -n frontend'
```

**Comment by OldManLink** [comment]
We have been getting these warnings from the following tasks since Thursday, January 28th:
```
PythonScript@0
HelmDeploy@0
Docker@2
```

**Comment by garyverhaegen-da** [comment]
In our pipeline, in a Bash step, this code:
```
    echo "vso[task.setvariable variable=${{parameters.var_name}}]$TMP"
    echo "##vso[task.setvariable variable=${{parameters.var_name}}]$TMP"
```
producing this output:
```
vso[task.setvariable variable=bash-lib]/tmp/tmp.5WOqUnXaUk
```
triggers the warning, so I'm inclined to think the warning is triggered on _any_ `vso` command, regardless of whether it contains a `%`. From my experiments it seems to be triggered by the first `setvariable` of each job.

**Comment by dwivedipriyaranjan** [comment]
As per Microsoft documentation, you need to define 
jobs:
- job:
  variables:
  - name: DECODE_PERCENTS
    value: true
 
To avoid these issues.
For more details read this.
[Percent Encoding](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md#percent-encoding)

**Comment by ElvenSpellmaker** [comment]
This isn't a solution it's a workaround?

If the tasks aren't updated to compensate then tasks may break as they'll be opting into behaviour they don't expect.

It's 8 days into this issue and still no official response on this other than to force everyone to add a variable to potentially hundreds of builds.

**Comment by bahadir-be** [comment]
> 
> 
> This isn't a solution it's a workaround?
> 
> If the tasks aren't updated to compensate then tasks may break as they'll be opting into behaviour they don't expect.
> 
> It's 8 days into this issue and still no official response on this other than to force everyone to add a variable to potentially hundreds of builds.

+1 agree!!

**Comment by basithaf** [comment]
Based on https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md,

I think the ']' in the setVariable syntax decodes to '%5D' behind the scenes, so we see the warning about having a '%' character in our task(s) despite not explicitly having one. Based on that link, I think the only change is that if you wanted to add a '%' character to a ##vso command, you would need to use '%25' instead of just '%'.

**Comment by anatolybolshakov** [comment]
Hi everyone, there is another [PR](https://github.com/microsoft/azure-pipelines-agent/pull/3241) to fix this encoding issue - since there were a lot of false-positives for %25, it will be replaced to %VS_TS instead.

**Comment by garyverhaegen-da** [comment]
Based on a suggestion from @damccorm in #3241 I was able to make a minimal reproducible case for the `Bash` step issuing a spurious warning:

```
jobs:
- job: check_standard_change_label
  pool:
    vmImage: ubuntu-latest
  steps:
    - bash: |
        echo "hello"
        # there is a % hidden here
```
Here is the relevant part of the debug output for that build:
```
2021-02-08T18:27:12.0524701Z ##[debug]targetType=inline
2021-02-08T18:27:12.0525413Z ##[debug]script=echo "hello"
# there is a %25 hidden here
2021-02-08T18:27:12.0535915Z ##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
2021-02-08T18:27:12.0548969Z Generating script.
2021-02-08T18:27:12.0550041Z ##[debug]which 'bash'
2021-02-08T18:27:12.0550848Z ##[debug]found: '/usr/bin/bash'
```

So I suppose Bash can be added to the list above.

**Comment by robmaas** [comment]
It looks like that PR has been released to production a couple of days ago, warnings are gone in my configurations.
I think this issue can be closed.

**Comment by markwooff** [comment]
Can confirm on my end as well. Haven't seen the `##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md` messages that were showing up in our pipelines last week.

**Comment by spacejam101** [comment]
I'm still having this error even if the pr has been closed

**Comment by piraces** [comment]
I'm having the error in the task `.NET Core` when executing the `test` command (with the option `Publish test results and code coverage` enabled):
```
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.181.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
```

**Comment by damccorm** [comment]
Hey @piraces could you please try updating to the most recent version of the agent?

**Comment by piraces** [comment]
Sure! I will try and I will update here with the result

**Comment by piraces** [comment]
@damccorm Just tried with the latest version of the agent... Both tasks mentioned above (`UseDotNet@2` and `AzureCli@2`) works just as expected for me 😄
