### ISSUE TITLE
Kubectl task doesn't show runtime messages well.

### ISSUE THREAD

**Issue by v-lali** [microsoft/azure-pipelines-tasks#14316]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Kubernetes task

## Environment
- Server - Azure Pipelines.

- Agent - Hosted

## Issue Description

For those AKS created with AAD and RBAC enabled, it will have “To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AAAAAAAAA to authenticate.” Message asking for inputs.

It will pause our pipeline at Kubernetes task. But it's strange that there's no meaningful info/message displayed in the task window. It makes great effect on our troubleshooting steps.

### Task logs

![image](https://user-images.githubusercontent.com/46334689/106296014-1740d380-628c-11eb-83b1-901dce1e1859.png)

It was just stuck there without any message. Hopefully the logger of this task can also show the info like "To sign in, use a ..." immediately instead of just pausing at that point for several minutes.

**Comment by GrumpyRainbow** [comment]
@v-lali I'm running into this same issue.  Were you able to get around this problem?  If so, how'd you do it?  I've seen [this](https://github.com/MicrosoftDocs/azure-docs/issues/10326#issuecomment-537732948) mentioned, but it didn't seem to help my situation.

**Comment by wasfree** [comment]
With this Azure DevOps Tasks ist not working, you have to Use Kubelogin as mentioned in MS Documentation: https://docs.microsoft.com/en-us/azure/aks/managed-aad#non-interactive-sign-in-with-kubelogin

Here is how it should work:
```
- task: AzureCLI@2
  inputs:
    azureSubscription: 'NAME OF AZURE DEVOPS SERVICE CONNECTION'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials -n CLUSTERNAME -g CLUSTERRESOURCEGROUP
 
      # get kubelogin
      wget https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
      unzip kubelogin-linux-amd64.zip
      sudo mv bin/linux_amd64/kubelogin /usr/bin
      kubelogin convert-kubeconfig -l azurecli
 
      kubectl get nodes
``
