### ISSUE TITLE
PublishTestResults does not publish find pester 5 nunit or junit testresults

### ISSUE THREAD

**Issue by AlbanBarbosa1982** [microsoft/azure-pipelines-tasks#14319]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
bug?

PublishTestResults@2 does not find results of pester 5
**Enter Task Name**: here  
PublishTestResults@2
list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
azure pipeline
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
private hosted windows 2016 server
## Issue Description
jobs:
- job: testpipeline
  displayName: Testpipeline containing smoketests and integration tests
  pool:
    name: AGENTPOOLSPECIFICTOUS
  variables:
  - template: "../variables/SERVERNAMEBLABLA.yml"
  steps:

  - task: PowerShellOnTargetMachines@3
    displayName: 'Does the MSBuildDirectory exist?'
    inputs:
        Machines: '$(ReleaseServer)'
        UserName: '$(DeploymentUserName)'
        UserPassword: '$(DeploymentPassword)'
        ScriptType: FilePath
        ScriptPath: 'P:\drop\TestScripts\TestMSBuildDirectory.ps1'
        CommunicationProtocol: Http
        workingDirectory: P:\drop\TestScripts
  
  - task: PublishTestResults@2
    inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: testResults.xml
        searchFolder: P:\drop\TestScripts

The last task does not find the generated test result by powershell task. I also tried with '$(System.DefaultWorkingDirectory)'

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'true'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: 'testResults.xml'
##[debug]findPath: 'P:\drop\TestScripts\testResults.xml'
##[debug]statOnly: 'true'
##[debug]ENOENT
##[debug]found 0 paths
##[debug]applying include pattern
##[debug]adjustedPattern: 'P:\drop\TestScripts\testResults.xml'
##[debug]0 matches
##[debug]0 final results
##[debug]Detected 0 test result files
##[debug]which 'dotnet'
##[debug]not found
##[warning]No test result files matching testResults.xml were found.
##[debug]Processed: ##vso[task.issue type=warning;]No test result files matching testResults.xml were found.
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]
##[debug]Release.ReleaseUri=undefined
##[debug]Release.ReleaseId=undefined
##[debug]Build.BuildUri=vstfs:///Build/Build/514636
##[debug]Build.Buildid=514636
##[debug]Processed: ##vso[telemetry.publish area=TestExecution;feature=PublishTestResultsTask]{"builduri":"vstfs:///Build/Build/514636","buildid":"514636","osType":"Windows_NT","testRunner":"JUnit","failTaskOnFailedTests":"false","mergeResultsUserPreference":"false","config":null,"platform":null,"testResultsFilesCount":0,"dotnetVersion":"","noResultsFileFound":true,"subFeature":"publishTestResultsTaskConsolidatedCiEvent"}
Finishing: PublishTestResults

[Insert error from the logs here for a quick overview]

**Comment by AlbanBarbosa1982** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="1" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2021-02-02" time="08:22:39">
  <environment user="NPX9-AZDO-SYS_T" machine-name="TARGETSERVER" cwd="P:\drop\TestScripts" user-domain="AD" platform="Microsoft Windows Server 2016 Standard|C:\WINDOWS|\Device\Harddisk0\Partition1" nunit-version="2.5.8.0" os-version="10.0.14393" clr-version="4.0.30319.42000" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="TestFixture" name="Pester" executed="True" result="Success" success="True" time="1.1167" asserts="0" description="Pester">
    <results>
      <test-suite type="TestFixture" name="./TestMSBuildDirectory.tests.ps1" executed="True" result="Success" success="True" time="1.1167" asserts="0" description="./TestMSBuildDirectory.tests.ps1">
        <results>
          <test-suite type="TestFixture" name="MSBuild directory exists" executed="True" result="Success" success="True" time="0.9251" asserts="0" description="MSBuild directory exists">
            <results>
              <test-case description="The dir exists? " name="MSBuild directory exists.The dir exists? " time="0.2168" asserts="0" success="True" result="Success" executed="True" />
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>

**Comment by AlbanBarbosa1982** [comment]
Uploaded nunit output file now for pester 4.. also fails

**Comment by AlbanBarbosa1982** [comment]
Ok my problem is a little bit more tricky. We use MS build agents and private release agents which I need to unit test. We do not have accounts to access and MS build agents and release agents. Please assist

**Comment by AlbanBarbosa1982** [comment]
Ok after some fugly inline powershell to invoke-command on target server and then create outputfile on build agent in working dir i'm getting somewhere. Last hurdle is my xml junit/nunit does not pass the xml validation. Some help?

**Comment by chshrikh** [comment]
@navin22  @shailesh-sk please check this

**Comment by AlbanBarbosa1982** [comment]
I have working code now so this can be closed.
