### ISSUE TITLE
AzureFileCopy - set Content-Encoding

### ISSUE THREAD

**Issue by hkusulja** [microsoft/azure-pipelines-tasks#14329]
I am using latest cloud Azure DevOps - Release - Task Azure File Copy - version 4.*
to copy static files for web page to Azure Storage blob account container.
It also automatically sets correct content-type attribute in azure storage account.

However, attribute content-encoding is not set, and should be set for gzip, .br files

This is needed due to HTTP browser requirements, and CDN only pick-up data from Azure storage account with metadata.

**Comment by AmrutaKawade** [comment]
Our task internally uses azcopy.exe and automatically setting content-type is feature provided by azcopy

https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy#advanced

I am not sure whether content-encoding  can be set automatically with this exe. 

you can pass optional arguments though to set `--content-encoding` in the task
![image](https://user-images.githubusercontent.com/65217380/111757963-e9f2c800-88c1-11eb-8300-6b12682a80dc.png)

https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy#options

if you want to request feature in azcopy raise request here https://github.com/Azure/azure-storage-azcopy/issues

**Comment by AmrutaKawade** [comment]
Closing this issue. Do try above steps. Let me know if it doesn't work

**Comment by hkusulja** [comment]
The point is that AzCopy.exe knows automatically to set content-type, the same way it should support and set automatically content-enconding. So you are saying this is a feature request and currently not supported?

This is needed for example when DevOps pipeline/build and release/deploy , static web files to azure storage, which is behind CDN, , which needs to know if file is gzip, or brotli etc, and needs to be returned correctly from the origin.
Manually specify and putting is "too much work" , sorry.

Just confirm please that this is by design and should be a new feature request to support auto-setting the content-encoding ?

**Comment by AmrutaKawade** [comment]
yes its not supported currently please raise feature request here  https://github.com/Azure/azure-storage-azcopy/issues

**Comment by hkusulja** [comment]
opened - https://github.com/Azure/azure-storage-azcopy/issues/1415
