### ISSUE TITLE
Error on failure to discover tests

### ISSUE THREAD

**Issue by Bouke** [microsoft/azure-pipelines-tasks#14328]
## Required Information

**Question, Bug, or Feature?** 
*Type*: Bug

**Enter Task Name**: VSTest

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines (private)
- Agent - Hosted or Private: Hosted

## Issue Description

We just discovered that the VSTest task was **not executing any test**. The reason is unrelated and appears to be related to multi-targeting of test projects. The problem is that the build introducing this regression **did not fail**. I cannot comprehend the reasoning given in a [prior discussion](https://github.com/microsoft/azure-pipelines-tasks/issues/9045). It is an error when no tests could be executed, **it should just completely fail the build**. It is the job of the pipeline to have a correct default behaviour, and **ignoring errors is not a good default**. While I can understand the reasoning for not introducing backward incompatible changes, this is a moot point as one could increase the task's version. 

I'm aware of the "minimumExpectedTests" setting, but this is not an appropriate solution. It's not default behaviour, requires configuration and adjustments depending on the test suite. It works by people running into this very problem, adjusting that setting and at some point in the future the problem re-occurs and requires further fiddling with that setting.

![image](https://user-images.githubusercontent.com/235882/106763947-a147be00-6637-11eb-8915-656d5c7986ef.png)

### Task logs

> [MSTest][Discovery][D:\a\1\s\...\bin\x64\Debug\net48\X.dll] Failed to discover tests from assembly D:\a\1\s\Source\...\bin\x64\Debug\net48\X.dll. Reason:Could not load file or assembly 'X' or one of its dependencies. The system cannot find the file specified.
No test is available in D:\a\1\s\...\bin\x64\Debug\net48\X.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Microsoft (R) Coverage Collection Tool Version 16.0.30319.3002

**Comment by Bouke** [comment]
Another example of the task output (note that it is not even outputted as a warning!) that should simple fail the test task:

> No test is available in D:\a\1\s\X\bin\x64\Debug\net5.0\X.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

**Comment by Bouke** [comment]
Another example of the task output (note that it is not even outputted as a warning!) that should simply fail the test task:

> Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests
> An exception occurred in the driver while loading tests.
>    at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
>    at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
>    at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
>    at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
>    at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
>    at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 83
>    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 293
>    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 110
> InnerException: System.IO.FileNotFoundException: Could not load file or assembly 'nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
> File name: 'nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
>    at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
>    at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
>    at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> NUnit Adapter 3.17.0.0: Test execution complete

**Comment by ankit-arora12** [comment]
It looks like an issue with NUnit test. Please open this issue in Nunit repo.

**Comment by Bouke** [comment]
@ankit-arora12 this is NOT an issue with NUnit but with the test task and/or MSTest. Please reopen.

**Comment by ankit-arora12** [comment]
Hi, The issue is in NUnit test adapter, not NUnit runner. The NUnit test adapter is invoked from the [Test Platform](https://github.com/microsoft/vstest).
The Test Platform which is used internally by the VSTest Task has the contract which the NUnit Test Adapter needs to adhere to and send the appropriate termination signal to fail the execution which is not happening. 

As you can see from the stacktrace above `at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 83`, the NUnit adapter on failure should send the appropriate failure/termination signal to the Test Platform which we suspect is not happening.

VsTest task simply fails the pipeline if there are failed tests or the vstest.console.exe(Test Platform) return non-zero exit code. 

There is a small possibility that the issue could be in Test Platform as well but the vs test task merely fails based on the conditions specified above and is just the consumer of the Test Platform. In that case, https://github.com/microsoft/vstest/issues is the right place to file the issue. You can verify this by running vstest.console.exe from a PowerShell task to emulate what vstest task is doing.

Also, please send us the full logs with System.Debug set to true if you've further questions so that we've more data.

**Comment by Bouke** [comment]
This issue is afaik not resolved.

**Comment by Bouke** [comment]
This issue hasn’t been resolved.

**Comment by abofaliha** [comment]
I'm having the same issue. Any help would be appreciated

**Comment by Bouke** [comment]
This issue hasn’t been resolved.

**Comment by eocron** [comment]
Same issue, 3 years and still not fixed.
