### ISSUE TITLE
AzureFileCopy@4 requires read permission on resource group

### ISSUE THREAD

**Issue by lonevvolf** [microsoft/azure-pipelines-tasks#14327]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopy

## Environment
Azure Pipelines
Hosted Agent

## Issue Description

I cannot get the AzureFileCopy task to copy into Blob Storage without assigning Reader permission directly on the resource group.  If I remove this, it gives an error:
##[error]ExceptionMessage: ExceptionMessage: The client 'GUID' with object id 'GUID' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/read' over scope '/subscriptions/GUID/resourceGroups/RGNAME' or the scope is invalid. If access was recently granted, please refresh your credentials. (in function: Get-AzRmResourceGroup) (in function: Get-AzRMStorageKeys)

This requirement is not listed anywhere, and probably should not be required.

### Error logs

##[error]ExceptionMessage: ExceptionMessage: The client '<GUID>' with object id '<GUID>' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/read' over scope '/subscriptions/<GUID>/resourceGroups/<RGNAME>' or the scope is invalid. If access was recently granted, please refresh your credentials. (in function: Get-AzRmResourceGroup) (in function: Get-AzRMStorageKeys)

**Comment by 20shivangi** [comment]
@lonevvolf  I was unable to try out since I am the owner on the subscription so could not remove inherited roles. Can you please confirm once if this issue is happening for all versions of AzureFileCopy i.e 2,3 and 4 for you?

**Comment by 20shivangi** [comment]
@lonevvolf Alos, please specify the version of task also for which you raise the issue

**Comment by lonevvolf** [comment]
I can confirm the issue is present in versions 2, 3, and 4.

**Comment by 20shivangi** [comment]
@N-Usha We do need read permissions on RG for the call ' Get-AzRmResourceGroup' in the code . Can you please update the documentation of AzureFileCopy task for the same.

**Comment by lonevvolf** [comment]
This means that the account used for the action has read access to every resource in the RG, as the permission is inherited.  This seems like a security issue to me.

**Comment by lonevvolf** [comment]
Please reopen - this is waiting for a fix.
