### ISSUE TITLE
DockerCompose@0 - Add Compose CLI/ACI Support

### ISSUE THREAD

**Issue by Choonster** [microsoft/azure-pipelines-tasks#14323]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DockerCompose@0

## Description

We're currently trying to set up a pipeline to deploy a multi-container group to ACI using a **docker-compose.yml** file, but the `DockerCompose@0` task only supports the original [compose](https://github.com/docker/compose) tool (`docker-compose ...`) and not the newer [compose-cli](https://github.com/docker/compose-cli) tool (`docker compose ...`) that can deploy to ACI.

I tried setting the `dockerComposePath` input to a shell script that forwards its arguments to `docker compose`, but then I realised that the two commands expect their arguments in a different order: `docker-compose -f <file> up` vs. `docker compose up -f <file>`.

It would be helpful if the `DockerCompose@0` task supported compose-cli and ACI natively.

**Comment by Choonster** [comment]
This hasn't been implemented yet.

**Comment by Choonster** [comment]
This hasn't been implemented yet.

**Comment by zurgur** [comment]
is this being worked on?
