### ISSUE TITLE
AzurePowerShell5 Task fails when Managed Identity Service Connection is Scoped to Management Group

### ISSUE THREAD

**Issue by JPadster** [microsoft/azure-pipelines-tasks#14330]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell5

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure Pipelines. Other information is private within organisation.

- Agent - Hosted or Private: 
    Private
Windows Server 2016
## Issue Description

When using private build agents with a service connection of type Managed Instance scoped to Management Groups, the AzurePowerShell5 task fails with the error below.

### Task logs
##[error]Cannot bind argument to parameter 'SubscriptionId' because it is an empty string
##[error]PowerShell exited with code '1'

## Reproduce
Create private build agents (VMSS)- Windows Server 2016.
Set VMSS to use Managed Identity.
In ADO, create a service connection of type Azure Resource Manager > Managed Identity....cope it to Management Group.
In a pipeline...
- task: AzurePowerShell@5
  inputs:
    azureSubscription: MyManagedIdentitySvcConnection
    ScriptType: 'InlineScript'
    Inline: |
      set-azcontext my-azuresubscription-prod
    azurePowerShellVersion: 'LatestVersion'

### Error logs

##[error]Cannot bind argument to parameter 'SubscriptionId' because it is an empty string
##[error]PowerShell exited with code '1'

**Comment by 20shivangi** [comment]
@JPadster The PR : https://github.com/JPadster/azure-pipelines-tasks/pull/1 mentioned in this issue, resolve this issue for you ?

**Comment by JPadster** [comment]
@20shivangi @nadesu reverting this commit until more extensive testing can be completed. Please revert the commit.

**Comment by 20shivangi** [comment]
The issue has been fixed with [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14364)
It will take at least 3-4 weeks for the fix to get deploy. Please wait until fix reaches your account. Thanks for your patience.
