### ISSUE TITLE
VSTest ignores platform in runsettings and task options

### ISSUE THREAD

**Issue by msft-mw** [microsoft/azure-pipelines-tasks#14336]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted: Microsoft-hosted

## Issue Description

VsTestV2 ignores the platform setting in the defined `.runsettings` and then shows a platform mis-match error. Logs show that the `.runsettings` is detected:

```
Provided settings file:

<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <!-- Path relative to solution directory -->
    <ResultsDirectory>.\TestResults</ResultsDirectory>

    <!-- [x86] | x64  
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->
    <TargetPlatform>x64</TargetPlatform>
```

and that it is updated properly:

```
Updated Run Settings:
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <!-- Path relative to solution directory -->
    <ResultsDirectory>D:\a\_temp\.\TestResults\TestResults</ResultsDirectory>
    <!-- [x86] | x64  
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->
    <TargetPlatform>x64</TargetPlatform>
    <!-- Framework35 | [Framework40] | Framework45 -->
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
```

But then this error is in the logs:

> Test run detected DLL(s) which were built for different framework and platform versions. Following DLL(s) do not match current settings, which are .NETFramework,Version=v4.5 framework and X86 platform.

Tests still run and pass, but this error is confusing and only appears on the hosted build. I'm unable to repro the issue locally.

**Comment by msft-mw** [comment]
This is a closed source project, happy to provide log files privately if needed!

**Comment by nishantms** [comment]
@msft-mw can you please share the logs with system.debug set to true

**Comment by msft-mw** [comment]
Sorry, missed this. I will do it tomorrow, thanks!

**Comment by anshii03** [comment]
@msft-mw  As we didn't get any logs yet , we are closing this issue . Please reopen it if issue still persists .

**Comment by msft-mw** [comment]
@anshii03 the logs were sent on 3/10, subject line: `logs for issue 14336`.

Please let me know if I should resend or to a different alias. I have reopened as the issue is still occuring.
