### ISSUE TITLE
FuncToolsInstaller doesn't set +x on gozip 

### ISSUE THREAD

**Issue by qj0n** [microsoft/azure-pipelines-tasks#14342]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `FuncToolsInstaller`

## Environment
- Server
   - Azure Pipelines
   - Account name: speeron
   - project: PiccoloCloud2
   - Build ID: 2161
- Agent
   - Hosted `ubuntu-latest`

## Issue Description

According to Azure Functions Core Tools manuall installation instruction (https://github.com/Azure/azure-functions-core-tools) to install it, you have to run following command:
```bash
chmod +x func
chmod +x gozip
```

However, in the step code, only `func` is set to executable (Tasks/FuncToolsInstallerV0/src/utils.ts:78). This makes some func actions (like `func azure publish`) fail with error `Permission denied`. Running chmod manually in shell step fixes the problem.

I guess adding something like `fs.chmodSync(path.join(cachedToolpath, 'gozip' + getExecutableExtension()), '777')` should fix it.

### Error logs

```
/usr/bin/az account set --subscription 7ac581cd-b855-4438-953c-a5d6636ae0c8
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/azureclitaskscript1612512696662.ps1'
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Permission denied
```

**Comment by chshrikh** [comment]
@ajinkya599 to check this
