### ISSUE TITLE
Nodejs VSTS task packaging with tfx failed due to space in txt file name

### ISSUE THREAD

**Issue by Mrkisha** [microsoft/azure-pipelines-tasks#14348]
When I create a node vsts task and want to package it with `tfx` I get following error
![image](https://user-images.githubusercontent.com/1561303/107101355-4ff62500-6817-11eb-9732-3f31263e8e2a.png)

Temporary solution is to rename the file.
Then another file has same issue
![image](https://user-images.githubusercontent.com/1561303/107101489-cabf4000-6817-11eb-9020-d11598100be7.png)

But need long term solution.

**Comment by damccorm** [comment]
Hey @Mrkisha this looks like an issue with `tfx` not with a specific task in this repo. Please open an issue at https://developercommunity.visualstudio.com/spaces/21/index.html
