### ISSUE TITLE
File not found 2.157.3\runvstest.js after updating task on Azure DevOps Server Version Dev17.M153.3

### ISSUE THREAD

**Issue by mlop3s** [microsoft/azure-pipelines-tasks#14341]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
     - Server - TFS on-premises    
    - If using TFS on-premises, provide the version: 
   
DevOps Server Version: Dev17.M153.3

     - Agent - Private
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Our agent version right now is: 2.153.1

## Issue Description

We were having problems running coverage with Nunit and according to this:
 https://github.com/nunit/nunit3-vs-adapter/issues/519
We should update this vs test task.
Perhaps this is a documentation issue, as there is nothing written about whats required to install the new task and now our unit tests cannot be run as it searches for a js file. The new task uses typescript.

How can i downgrade the task version?

### Task logs

Starting: Run Unit Tests

Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.157.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest

[error]File not found: 'C:\agent_01\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.157.3\runvstest.js'
[section]Finishing: Run Unit Tests

We have installed the task by using
.\VsTest-2.157.3.ps1 -CollectionUrl http://ourAzure:8080/NxCollection/

And as workaround we had to rename the old task folder to 2.157.3 on every agent 👎 
We could not find any directions on how to revert the task to an older version. Nor could we find a 2.156.* ps1 installer.

**Comment by ankit-arora12** [comment]
We do not recommend manually downloading the task because there will be a client-server mismatch that causes undesirable behaviour when interacting with the server.

**Comment by fairmonk** [comment]
I have same issue after upgrading from **2.205.0** to **2.235.0**
I upgraded using 
1. git clone from https://github.com/microsoft/azure-pipelines-tasks.git
2. git checkout -b vstest22350 b0663cd1885036b7b6ecdb1762b00f2b0d455279
3. npm install -g tfx-cli
4. tfx login
5. tfx build tasks upload --task-path Local\Path\azure-pipelines-tasks\Tasks\VsTestV2

the task now fails with this error:
**##[error]File not found: 'E:\ADOAgent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.235.0\runvstest.js'**
I really need to downgrade back, how to do it ?

**Comment by fairmonk** [comment]
found a way to delete the task using "..\AppData\Roaming\npm\tfx.cmd build tasks delete --task-id ef087383-ee5e-42c7-9a53-ab56c98420f9" This removes the latest installed version, but keeps the previous ( old version ) untouched, unless run 2x times.
