### ISSUE TITLE
Web Config Generation in App service deploy task

### ISSUE THREAD

**Issue by AntonioNH** [microsoft/azure-pipelines-tasks#14358]
Hello,

I am using a pipeline with a deploy to app service task. To run this pipeline I am using a self-hosted agent, and I am using the feature to generate the web.config in the task, it is not in the repo. Under the File Transforms and variable substitutions tab, I am using the edit feature and providing the default parameters for java springboot apps. But I get the following error:

Error: Failed to generate web.config. Error: App type 'Java_SpringBoot' not supported in Web.config generation. Valid values for '-appType' are: 'python_Bottle', 'python_Django', 'python_Flask' and 'node'

I am guessing I have some outdated dependency needed to run this... Could you please help me figure out how this step is run, and what I might be missing? If I need some component instaled in a certain version?

Thank you :)

Document: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/README.md

**Comment by AntonioNH** [comment]
Hey again, found the issue.

 In the portal, if you you click on the button next to the "Generate web.config parameters for Python, Node.js, Go and Java apps" textbox and auto generate the parameters for the java_springboot framework, you will get the following: -appType Java_SpringBoot (among others)...

Looking at https://github.com/microsoft/azure-pipelines-tasks/blob/ea74f3f0b3fac2e071d445656feb2bbcacb149c9/Tasks/AzureRmWebAppDeploymentV3/webdeployment-common/webconfigutil.ts#L69 it doesn't do the matching with the java_springboot string because of the capital letters. The auto generated parameters should match with the ones they are being compared to. 

Plus the error message I got is outdated, as the java_springboot appType is not included in the supported apptypes of the error message, which was misleading for the troubleshooting. (defined here? https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/task.json).

Not sure if I should close the issue right away, just wanted to give the feedback, but feel free to close it whenever. Thank you 😀

**Comment by AmrutaKawade** [comment]
@AntonioNH Thanks for reporting this. If possible can you raise PR as well?

**Comment by AmrutaKawade** [comment]
@AntonioNH I am not able to repro this. even for camelCase of `-appType Java_SpringBoot`  its working

Can you share your value for this field?

![image](https://user-images.githubusercontent.com/65217380/112262366-8e468700-8c93-11eb-83e4-4ae70c460d45.png)

Nevertheless we need to change error message

**Comment by AmrutaKawade** [comment]
Closing this issue will track with this issue https://github.com/microsoft/azure-pipelines-tasks/issues/14630
