### ISSUE TITLE
updatedependency option for HelmDeploy@0 upgrade command

### ISSUE THREAD

**Issue by mateusz-kolecki** [microsoft/azure-pipelines-tasks#14362]
*Type*: Question

**Enter Task Name**: `HelmDeploy@0`

## Issue Description

Why `HelmDeploy@0` command `upgrade` does not offer `updatedependency` option? Is that some design decision or it was just simply forgotten for `upgrade` command?

I can see that the `install` command can receive this option and it is not clear to me why `upgrade` doesn't.

**Comment by shigupt202** [comment]
@mateusz-kolecki Helm provides the update dependency flag `--dep-up` along with install command, and not with upgrade command probably because building the chart directory makes sense before installing. That's why, this option is only available with install command.

**Comment by shigupt202** [comment]
Closing the issue. Feel free to reopen for any more clarification.

**Comment by solarist** [comment]
So because of [this bug](https://github.com/helm/helm/issues/10239) in Helm the `--dependency-update` flag does not work in `helm upgrade`. Can this issue be re-opened again?

**Comment by solarist** [comment]
So because of https://github.com/helm/helm/issues/10239 the `--dependency-update` flag does not work in `helm upgrade`. Can this issue be re-opened again?
