### ISSUE TITLE
npm task & Azure DevOps Artifacts - Issues with npm ci

### ISSUE THREAD

**Issue by beyerleinf** [microsoft/azure-pipelines-tasks#14375]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NpmV1

## Environment

Azure DevOps, hosted Agent
Account Name: balluffsmartreorderingsystem
Team Project: SRS
Build Definition: srs-frontend (BuildID 459 / "#srs-frontend_merge_20210210.2 Minor visual bugfixes")

## Issue Description

I'm currently experiencing a lot of issues while running `npm ci` during a build. I use Azure DevOps Artifacts with https://registry.npmjs.org/ as an upstream source as my package feed.

This is what the task looks like:

```yml
- task: Npm@1
  inputs:
    command: 'ci'
    customRegistry: 'useFeed'
    customFeed: '5a3835ce-ce36-4c31-826a-5d84d354802b'
  displayName: npm ci
```

### Error logs

These are the relevant lines in the error log.

```none
11501 silly extract rimraf@2.7.1 extracted to /home/vsts/work/1/s/node_modules/copy-concurrently/node_modules/rimraf (200ms)
11502 http fetch GET 200 https://pkgs.dev.azure.com/balluffsmartreorderingsystem/_packaging/5a3835ce-ce36-4c31-826a-5d84d354802b/npm/registry/@typescript-eslint%2feslint-plugin 32307ms
11503 silly tarball trying p-locate@3.0.0 by hash: sha512-x+12w/To+4GFfgJhBEpiDcLozRJGegY+Ei7/z0tSLkMmxGZNybVMSfWj9aJn8Z5Fc7dBUNJOOVgPv2H7IwulSQ==
11504 silly tarball no local data for p-locate@3.0.0. Extracting by manifest.
11505 verbose teardown shutting down workers.
11506 info teardown Done in 0s
11507 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...-eslint/eslint-plugin'
11507 verbose stack     at JSON.parse (<anonymous>)
11507 verbose stack     at parseJson (/opt/hostedtoolcache/node/12.20.1/x64/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11507 verbose stack     at /opt/hostedtoolcache/node/12.20.1/x64/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
11507 verbose stack     at runMicrotasks (<anonymous>)
11507 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
11508 verbose cwd /home/vsts/work/1/s
11509 verbose Linux 5.4.0-1039-azure
11510 verbose argv "/opt/hostedtoolcache/node/12.20.1/x64/bin/node" "/opt/hostedtoolcache/node/12.20.1/x64/bin/npm" "ci"
11511 verbose node v12.20.1
11512 verbose npm  v6.14.10
11513 error Unexpected end of JSON input while parsing near '...-eslint/eslint-plugin'
11514 verbose exit [ 1, true ]
```

I've also attached the complete log of the `npm ci` command.

[npm-ci-log-complete.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5958720/npm-ci-log-complete.txt)

**Comment by DevRCRun** [comment]
We are also finding that the Azure Artifacts registry for NPM whether for our own packages published from Azure Pipelines or mirrored public ones are completely missing the sha-512 hashes, only the "shasum" field is present. It looks like the 

`"integrity":"sha512-WD53jhgDQmtx/z1hbr2WB+i1f9oAgi9gXeerC6xwRynAP1Xh8W2KM8JCyZ3PslGX3zc9/w3Ic/m+hp1myBJ0jQ==",`

which should be before it Is being stripped completely.

https://developercommunity.visualstudio.com/content/problem/957522/npm-packages-from-azure-artifact-defaulting-to-sha.html

**Comment by aldodfm** [comment]
Same here,
what we setup npm task to:
        - task: Npm@1.179.1
          inputs:
            command: 'install'
            customRegistry: 'useFeed'
            customFeed: 'XXXXXXXXXXXXXXXXXX'

**Comment by GrillPhil** [comment]
Same here...

**Comment by abaiao-il** [comment]
Hello, 
I'm with the same problem, randomly that error appears. 
Any suggestion to solve it?

**Comment by ValdasDienas** [comment]
Hi Microsoft 
When this issue will be fixed

**Comment by beyerleinf** [comment]
Not currently using Azure DevOps Artifacts but this still seems to be an issue

**Comment by dunlapm** [comment]
Chiming in that this is still an issue

**Comment by DevRCRun** [comment]
It's still an issue. The thread I previously mentioned still hasn't had any useful response. Quite unbelievable.

If you're intentionally saving compute time by not having sha512 in azure artifact feeds for npm, just say so.
