### ISSUE TITLE
Request Az.Resources version 3.0.0 and above to deploy azure template spec

### ISSUE THREAD

**Issue by hannwang1** [microsoft/azure-pipelines-tasks#14378]
I need to deploy Azure Resource Manager template spec.  The cmdlet I need are in Az.Resources 3.0.0 and above which requires Az.Accounts 2.1.0 and above.  I see the Az.Accounts imported by Azure Powershell version 5 is already 2.2.4, but deploy still failed with error

"The term 'Get-AzTemplateSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Please upgrade Az.Resources module to latest released version. Thanks.

## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Azure Powershell

list here (V# not needed):  Version 5
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

I need to deploy Azure Resource Manager template spec.  The cmdlet I need are in Az.Resources 3.0.0 and above.  I see the Az.Accounts imported by Azure Powershell version 5 is already 2.2.4, but deploy still failed with error

The term 'Get-AzTemplateSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Please upgrade Az.Resources module to latest released version. Thanks.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by 20shivangi** [comment]
@hannwang1 On hosted agent, the latest version of az module corresponds to 4.7.0 where Az.Resources module version is 2.5.1 
Addition of latest az modules on hosted agent is in our backlog already.
Meanwhile  to unblock yourself, you can use private agent instead of hosted one, install the latest az module on your machine locally where Az.Resources version is 3.0.0 and then specify same version in your task in `specify version` block

**Comment by hannwang1** [comment]
Hi @20shivangi  we don't have private host.  When are you going to update the Az version.  Az 4.7.0 is more than 5 months old.  many releases will be blocked if you can only support 6 months old version.  Can you please provide a timeline when you are going to upgrade version? Or any other workaround I can use newer version in my task? Thanks.

**Comment by allantargino** [comment]
Hi all,
I faced the same situation. As per [this comment](https://github.com/microsoft/azure-pipelines-tasks/issues/14160#issuecomment-753782049) on #14160,  we don't need private agents and a simple step installing the desired version should be enough.

> For Linux:
> `Save-Module -Path /usr/share/az_5.3.0 -Name Az -RequiredVersion 5.3.0 -Force -ErrorAction Stop`
> For Windows:
> `Save-Module -Path $env:SystemDrive\Modules\az_5.3.0 -Name Az -RequiredVersion 5.3.0 -Force -ErrorAction Stop`
