### ISSUE TITLE
Docker Compose Environment variables do not bind when variable substitution is used in azure pipeline

### ISSUE THREAD

**Issue by Castone22** [microsoft/azure-pipelines-tasks#14381]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerCompose

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    Not at liberty to share publicly, can provide privately if asked.

- Agent - Hosted or Private: 
    - Both, Hosted 
    - Hosted Was
       Pool: Azure Pipelines
       Image: ubuntu-latest
## Issue Description

Variables defined in the scope of a docker compose do not evaluate or bind correctly.  In the below configuration, BUILD_ID should be bound from the scope of the host into the docker container as per Docker Composes' spec.
https://gist.github.com/Castone22/6f4160703a5f3f0c518ea3c640d3f2ab

Attempting to manually provide it as in the below configuration will also cause the same behavior
https://gist.github.com/Castone22/4105b26c749533a69451b0084ec23a30

Attempting to run either of the two following configurations with the compose plugin will cause the bash command outside the container to echo the build id, while the ones inside the composed containers will echo $BUILD_ID.

### Task logs

https://gist.github.com/Castone22/0af0557afb22501ab17986d0953d4de5

### Error logs

https://gist.github.com/Castone22/0af0557afb22501ab17986d0953d4de5#file-compose-step-log-L389
Should have echo'd the contents of BUILD_ID instead of the variable name

**Comment by Castone22** [comment]
May have relationship with https://github.com/microsoft/azure-pipelines-tasks/issues/13607

**Comment by Castone22** [comment]
Bump

**Comment by joelbernstein** [comment]
This seems to still be an issue. Is nobody at MS working on it?

**Comment by Castone22** [comment]
Bump, still an issue
