### ISSUE TITLE
Please update the 7z version used for the Extractfiles task to 16.04

### ISSUE THREAD

**Issue by etarzan** [microsoft/azure-pipelines-tasks#14380]
## Note  
We are using the extract files task in our Azure DevOps pipelines for extracting files from our preexisting exes and then re-bundling them using a .Net Solution. 
The newer versions of  our .exe files are not being unzipped by the task and we are ending up with an error that looks like the following Pipeline raw log:
```
2021-02-11T06:07:37.1207663Z code: 3221225477 
2021-02-11T06:07:37.1216885Z stdout:  
2021-02-11T06:07:37.1249282Z stderr:  
2021-02-11T06:07:37.1287734Z ##[error]Extraction failed for file: D:\a\1\s\WindowsAppVersion\***.exe 
code: 3221225477 
stdout:  
stderr:  
error: undefined;
2021-02-11T06:07:37.1300215Z error: undefined;
2021-02-11T06:07:37.1307391Z ##[section]Finishing: Extract files *** exe
```
Note: I have masked the name of our exe due to the proprietary nature of the tool. 

I tried doing an extraction using the version of 7zip from here : [https://www.7-zip.org/a/7z1604.exe](https://www.7-zip.org/a/7z1604.exe ) -- this works fine in all environments
However, the Azure pipelines extract files task uses a version of 7zip which is : [https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip](https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip ) -- this seems to be an obsolete version not even available in 7zip's official downloads page either
On downloading and trying the Azure pipelines' version of the file (refer the link above from vstsagenttools.blob.core.windows.net) on a local machine, I am able to observe the same error of the crashing console. -
<img width="696" alt="Screenshot 2021-02-11 at 5 34 44 PM" src="https://user-images.githubusercontent.com/721752/107634928-53166880-6c90-11eb-86b3-3a95788f96a6.png">

Please help upgrade this tool to a supported version i.e. 16.04 which does not exhibit this bug (The version which gets downloaded in the pipeline is 16.00 which is the buggy version)

**Comment by etarzan** [comment]
Please do leave a note/comment on the expected timelines for the resolution as we have significant customer interests tied to the outcome of the above-mentioned azure pipeline.

**Comment by rohankapoor** [comment]
Hi team, this one is critical to fix. Our DezOps pipelines for release have come to a halt. Looks like 7z version 16.04 doesn't have this problem. Possible to speed up the fix for this one?

**Comment by kavitha1991dhiman** [comment]
Hi Team,
Our pipelines in production require this fix for a quick resolution to the issue.
Looks like this needs to be prioritized to update to 7z version 16.04 in order to get us in shape.
Please do leave a comment on the expected time for the resolution.

**Comment by EzzhevNikita** [comment]
@etarzan We've started working on the fix of the fix. But unfortunately I didn't manage to find the case when this issue happens for you. 
It will be very helpful if you could provide me an example of .exe file which is causing an issue for you or may be some steps how I can generate an exe which couldn't be unpacked. You can send an example of exe to my email - v-niezz@microsoft.com

The fix will be available in the next release, the distribution of which begins from February 22, it is required 3 week to distribute fix to all organizations.

**Comment by EzzhevNikita** [comment]
@etarzan Task with the fix has been deployed. Could you please check if it works for you now?

**Comment by etarzan** [comment]
@EzzhevNikita This seems to be working now. Thanks for fixing this on priority!
