### ISSUE TITLE
GitHubRelease seems to use wrong endpoint for getting commits (404 Not Found)

### ISSUE THREAD

**Issue by LUC18fknU7P** [microsoft/azure-pipelines-tasks#14387]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GitHubRelease

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

GithubRelease@1 seems to be using a wrong GitHub API endpoint which results in a 404 error, which is pretty concealed in a confusing error message unless `System.Debug` is set to `true`

I also reproduced this locally with `curl`
I was only able to get a successful response if I used branch names e.g. `master` commit IDs did not work, `https://api.github.com/repos/<ORG>/<REPO>/commits/<COMMIT>` worked on the other hand
Note: I am using GitHub PAT tokens

### Task logs

```
Searching for tags associated with target commit: 31c67389855eb7b5a3bfd6571b2c5e5792055a75
##[debug]Get branch request: {"uri":"https://api.github.com/repos/<ORG>/<REPO>/branches/31c67389855eb7b5a3bfd6571b2c5e5792055a75","method":"GET","headers":{"Authorization":"token ***"}}
##[debug][GET]https://api.github.com/repos/<ORG>/<REPO>/branches/31c67389855eb7b5a3bfd6571b2c5e5792055a75
##[debug]Get branch response: {"statusCode":404,"statusMessage":"","headers":{"server":"GitHub.com","date":"Fri, 12 Feb 2021 15:02:55 GMT","content-type":"application/json; charset=utf-8","content-length":"110","x-oauth-scopes":"delete:packages, repo, workflow, write:packages","x-accepted-oauth-scopes":"","x-github-media-type":"github.v3; format=json","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4984","x-ratelimit-reset":"1613142733","x-ratelimit-used":"16","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset","access-control-allow-origin":"*","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-frame-options":"deny","x-content-type-options":"nosniff","x-xss-protection":"1; mode=block","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","content-security-policy":"default-src 'none'","vary":"Accept-Encoding, Accept, X-Requested-With","x-github-request-id":"0480:B700:E70765:FF5E5B:6026989F","connection":"close"},"body":{"message":"Branch not found","documentation_url":"https://docs.github.com/rest/reference/repos#get-a-branch"}}
##[debug]commit sha for target: 31c67389855eb7b5a3bfd6571b2c5e5792055a75
##[debug]Build.SourceVersion=31c67389855eb7b5a3bfd6571b2c5e5792055a75
##[debug]Build.SourceBranch=refs/tags/test-release-v2
##[warning]Release will not be created as the tags for the target commit do not match with the given tag pattern
##[debug]Processed: ##vso[task.issue type=warning;]Release will not be created as the tags for the target commit do not match with the given tag pattern
##[debug]No tag found
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]

```
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Found above in Task logs

**Comment by tero-dev** [comment]
https://github.com/microsoft/azure-pipelines-tasks/blob/ac62063fd69b95a49ab7a607336e1eb104927478/Tasks/GitHubReleaseV1/operations/Release.ts#L103-L114

This is the function that fails. 
It's a call to https://docs.github.com/en/rest/reference/repos#get-a-branch 
shouldn't https://docs.github.com/en/rest/reference/repos#get-a-commit be used for commits?

**Comment by LUC18fknU7P** [comment]
@AmrutaKawade Would it be possible for you to take over / take a look at this issue? It has been unresolved for almost a month now.

**Comment by AmrutaKawade** [comment]
@LUC18fknU7P Sorry this task is not owned by our team
@ammohant can you assign someone to this issue?

**Comment by tauhid621** [comment]
This is the expected behaviour. The 'target' input can be a commit or branchName. So the task checks if there is any branch with the provided target. In case the response is 200 we know that the target was a branch other wise target is considered as a commit.

https://github.com/microsoft/azure-pipelines-tasks/blob/3d006dc5d5d66a880c039f8ee50bdb319a89c69a/Tasks/GitHubReleaseV1/operations/Helper.ts#L76-L100


Closing the issue as this is an expected behaviour.
