### ISSUE TITLE
Azure File Copy V4 StorageContainerSasToken is invalid

### ISSUE THREAD

**Issue by s-leonard** [microsoft/azure-pipelines-tasks#14388]
The Sas token I get back from the AzureFileCopy@4 task doesn't enable be to retrieve any of the files I'm uploading. 

```
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'src/scripts/*'
    azureSubscription: 'azuresubscription'
    Destination: 'AzureBlob'
    storage: 'demo'
    ContainerName: 'democontainer'
    sasTokenTimeOutInMinutes: 60
    AdditionalArgumentsForBlobCopy: '--overwrite=true --check-length=false'

- script: | 
    echo $(AzureFileCopy.StorageContainerUri)
    echo "$(AzureFileCopy.StorageContainerSasToken)"

```
When I trying to view a file  I get the following error. 

```
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:aad1b63b-501e-0003-3353-01068d000000 Time:2021-02-12T15:28:54.7420940Z</Message>
<AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
</Error>
```

If I create a new Sas token in the portal and view a file it works fine.

**Comment by AmrutaKawade** [comment]
How are you trying to view file? I mean which command are you using?

**Comment by AmrutaKawade** [comment]
this issue doesn't look like related to task. We create container level SAS token.

If you create token manually outside of the task using [Powershell]((https://docs.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontainersastoken?view=azps-5.6.0) or on portal
![image](https://user-images.githubusercontent.com/65217380/111778949-7cec2c00-88db-11eb-8b78-49a8296f10ac.png)

that time also you will get similar error

**Comment by s-leonard** [comment]
On further investigation, the tokens seem to change when stored as variables in YAML pipelines on windows hosted agents. 

If I create a SAS token in the portal and store it as a variable it still doesn't work, but I can see from the log the variable gets encoded. There is definitely an issue here, but its not a bug with the Azure File Copy task. 

Thanks
