### ISSUE TITLE
SSH@0 logs inline scripts to console verbatim, causing any ##vso commands to be executed

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#14395]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Ssh

## Environment
- Server - Any
- Agent - Hosted or Private: Any

## Issue Description

```
- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'user@machine'
    runOptions: inline
    inline: |
     if [[ 3 -ne 0 ]]
     then
       echo "ALL GOOD!"
     else
      echo "##vso[task.logissue type=warning]Something is fishy..."
     fi
    failOnStdErr: false
```

will always log `warning: Something is fishy...` because the tasks outputs each command it parses to the console:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SshV0/ssh.ts#L107-L108

![image](https://user-images.githubusercontent.com/4173387/107973992-3b075780-6fb6-11eb-9195-ba234c9f5840.png)

Maybe it should escape `##vso` or use some method to output the data to the log in such a way that it won't trigger commands.

As reported here:
https://stackoverflow.com/questions/66210365/azure-dev-ops-warnings-inline-shell-script/66210699#66210699

## Workaround

```
HASHHASH="##"
echo "$HASHHASHvso[task.logissue type=warning]Something is fishy..."
```

**Comment by kuleshovilya** [comment]
Hello @jessehouwing . Tried reproducing same exact task you've provided with a fresh environment(selfhost agent on win VM, and centos vm target) and latest task version(0.189.0), worked fine. Please, try the latest task version as well. If that doesn't work, please compare re-open the issue. I'll close it for now.
