### ISSUE TITLE
Deployment Agent Group - Release Pipeline Bash Task

### ISSUE THREAD

**Issue by AnshumanTripathy** [microsoft/azure-pipelines-tasks#14391]
## Having issue with BASH Task - Deployment Group Agent.

Simple jboss server start in bash command

**_sh -x /apps/APPNAME/jboss-eap-7.1/bin/standalone.sh -b servername &_** 

Starts the server with the application deployed immediately kills the server as soon as the Bash Task is done. 
If I pass a wait, it waits for the command to start the server then somewhere in the middle the task is completed and the background task on the server is not running anymore. Why is it cleaning up this process after the task is executed?

Is it because the agents are installed with root access??

Please help the task is currently not working as it should.

**Comment by EzzhevNikita** [comment]
@AnshumanTripathy Could you please share the task log with enabled diagnostics. To turn it on you can follow this [instruction](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs).

**Comment by EzzhevNikita** [comment]
@AnshumanTripathy The Bash task itself doesn't clean background processes. Agent is cleaning the process after pipeline completing on the Finalize Job step. You can try to set _process.clean_ environment variable with _false_ value in your pipeline, after that agent will skip cleaning of extra processes.

**Comment by AnshumanTripathy** [comment]
@EzzhevNikita Since this is happening on Release Pipeline, which is not in yaml, when we pass this process.clean as a environment variable, is it passed as $(process.clean = false) ? Just trying to understand the syntax there.

**Comment by EzzhevNikita** [comment]
@AnshumanTripathy You need to set it on variables tab in your release pipeline configuration, like on the screenshot below:

![image](https://user-images.githubusercontent.com/23104121/108162034-55981880-70fd-11eb-9d67-cdb782874511.png)

**Comment by AnshumanTripathy** [comment]
That works. @EzzhevNikita

**Comment by EzzhevNikita** [comment]
@AnshumanTripathy Since this issue has been resolved for you, then I close this ticket.

**Comment by ohads-MSFT** [comment]
> [@AnshumanTripathy](https://github.com/AnshumanTripathy) The Bash task itself doesn't clean background processes. Agent is cleaning the process after pipeline completing on the Finalize Job step. You can try to set _process.clean_ environment variable with _false_ value in your pipeline, after that agent will skip cleaning of extra processes.

@EzzhevNikita is this statement also true today?
Also, do you happen to know whether it holds true for `pwsh`?
