### ISSUE TITLE
##[error]TypeError: Cannot read property 'updateAndMonitorAppSettings' of undefined

### ISSUE THREAD

**Issue by mssanjay** [microsoft/azure-pipelines-tasks#14394]
I have a task in my pipeline as below ..
  - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: MS-us-web-daps-api-1'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(System.ArtifactsDirectory)/drop/**/target/*.?(war|jar)'

I get the error ##[error]TypeError: Cannot read property 'updateAndMonitorAppSettings' of undefined

No other information is provided to understand the error better.

I dont know if this is a bug or a mis configuration or issue with permissions.. Appreciate any feedback on this.

Thanks
Sanjay

**Comment by AmrutaKawade** [comment]
can you try giving exact extension of package instead if this `?(war|jar)`?

**Comment by AmrutaKawade** [comment]
@mssanjay any update on this?

**Comment by AmrutaKawade** [comment]
Closing this issue. Do try above solution. Let me know if it doesn't work
