### ISSUE TITLE
Variable Transform in web.config inside system.web section. 

### ISSUE THREAD

**Issue by BansalVikrant** [microsoft/azure-pipelines-tasks#14403]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Variable transform inside system.web section is not working

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Build Pipeline: https://microsoft.visualstudio.com/Universal%20Store/_build?definitionId=62210&_a=summary
Run: https://microsoft.visualstudio.com/Universal%20Store/_build/results?buildId=31510184&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=7f2915c2-c599-545f-479d-55f858cc2762

## Issue Description

I want to variable substitute in my web.config. Variable is defined under configuraton->system.web -> machine key's decryptingkey and validationkey in my Azure build pipeline.

Please find Web.DevAzure.config https://microsoft.visualstudio.com/Universal%20Store/_git/SC.csBillingTools?path=%2Fprivate%2FBilling%2FAdmin.Service%2FWeb.DevAzure.config

I created a build pipeline using FIle Transform task. Please find a sample build pipeline (https://microsoft.visualstudio.com/Universal%20Store/_build?definitionId=62210&_a=summary)

and its latest run https://microsoft.visualstudio.com/Universal%20Store/_build/results?buildId=31510184&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=7f2915c2-c599-545f-479d-55f858cc2762

I have defined some variables in build pipeline : configuration.system.web.machinekey.decryptionKey and decryptionKey and machineKey.decryptionkey

It seems FIle transfrom is only look appsettings and configsections. It is not looking system.web

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by AmrutaKawade** [comment]
Currently only these sections are supported for variable substitution 
"applicationSettings", "appSettings", "connectionStrings", "configSections"
