### ISSUE TITLE
Web deploy tasks corrupting the file names which have specials characters

### ISSUE THREAD

**Issue by asranja** [microsoft/azure-pipelines-tasks#14414]
**[Tasks]**
Azure App Service Deploy
IIS Web App Deploy

**[Issue]**
On doing an IIS web deploy and the files in zip folder with Swedish characters in their names are getting corrupted
The file that is named
Pts.Master.Analys.Jämförelse.dll
now looks like this
Pts.Master.Analys.J├ñmf├Ârelse.dll

**[Cause]**
The zip package generated by MSBuild corrupts the file name during build. 7zip extracts this package if the file transform option is selected and does not handle any kind of encoding/decoding to convert back the corrupted file name.

**[Temporary Workarounds]**

- **Option1**
Provide the package as a folder path instead of zip path.

- **Option2**
Add a PowerShell Task (with below inline script) before the web deploy tasks to unzip and rezip the package

```powershell
Add a PowerShell task before the IIS Deploy steps and add the following inline script. Fill the packageZipPath variable with the exact path to the package zip
$packageZipPath="<Exact path to the package zip>"
$unzipPath="$(Agent.TempDirectory)/temp_unzipped_package/"

if (Test-Path $unzipPath) {
Write-Host "Cleaning path $unzipPath"
Remove-Item -Path "$unzipPath" -Recurse -Force 
}

Write-Host "Unzipping package $packageZipPath at location $unzipPath"
Expand-Archive -Path $packageZipPath -DestinationPath $unzipPath

Write-Host "Cleanup package zip $packageZipPath"
Remove-Item -Path $packageZipPath -Force

Write-Host "Re-zipping the package at path $packageZipPath"
Compress-Archive -Path "$unzipPath/*" $packageZipPath
```

**Comment by chshrikh** [comment]
team is working on the actual fix for this, meanwhile please refer to above workaround

**Comment by sandrosuter** [comment]
How do I find out when this is no longer necessary?
