### ISSUE TITLE
Unable to resolve job name in a custom server task in agentless job

### ISSUE THREAD

**Issue by bhavanakonchada** [microsoft/azure-pipelines-tasks#14429]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Custom Server Task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Here is the link to release definition: https://msit-test1.visualstudio.com/OneITVSO-Staging/_release?definitionId=228&_a=releases&view=mine

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
I have an agent job and an agentless job in my release definition.
Several details like job name, job id and job display name are getting populated for the agent job.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/8509708/108644133-9b890f80-7462-11eb-95e5-4342672c516f.png)

But for the agent job only job Id is getting populated, where as the job name and job display name are not getting populated.
I have tried system.jobname and system.jobdisplayname, none seems to be fetching me the job name.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/8509708/108644104-76949c80-7462-11eb-9e28-0cc6af827677.png)

I am looking for information on how to populate the job name of an agentless job.
For the release definition linked above, system.debug is set to true.

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment]
Hey @bhavanakonchada this repo is for our first party tasks, for custom task issues please open a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html
