### ISSUE TITLE
You may delete this as soon as it fullfilled its purpose to transport my rage.

### ISSUE THREAD

**Issue by GammaPsh** [microsoft/azure-pipelines-tasks#14432]
Your doku page states we can use Nuget.config with, feedsToUse: 'config', nugetConfigPath: 'D:\a\1\s\NuGet.config'
![image](https://user-images.githubusercontent.com/842165/108690145-4a2c5f00-74fa-11eb-9dd7-ab1a6ba027a8.png)

So this is the Yaml fragment:
![image](https://user-images.githubusercontent.com/842165/108690426-a68f7e80-74fa-11eb-8c52-be5869d5632d.png)

And what does the console tell us your task is dooing?
This shit here, some crappy temporary nuget.config that nobody adressed...
![image](https://user-images.githubusercontent.com/842165/108690647-e35b7580-74fa-11eb-85dd-b89db3dbe128.png)

MSBuild, Dotnet.exe and these Azure tasks here making use of them are a complete shitshow... Fucking Microsoft policy to support 10 years of legacy code in one tool so you never clean up anything an have a insane amout of combinations to get things to maybe work, or in 50% of the Time things not to work...

I always end up using a powershell script substituting your stupid untested tasks. Using Microsoft Tech so often feels like beeing part of a "dumb ways to die" comic series. Where hours of preparation just end in a funny way to mess it all up.
So next time you see your PO please tell him to go F Off with his 1000 stupid featurerequests and extra configuration options that nobody ever needs and never work. 
Build something consistent that actually does what the docu states, thx

**Comment by luanbon** [comment]
I am facing the same problem here, I can't restore packages using task DotNetCoreCLI@2 passing Nuget.Config as parameters, it's always using a temporary Nuget configuration. I am using raw dotnet commands instead of DotNetCoreCLI@2.

**Comment by luanbon** [comment]
I managed to get this working using '- task: NugetToolInstaller@1' before restore command !

**Comment by johnterickson** [comment]
>You can **either** choose to select a feed from Azure Artifacts and/or NuGet.org here [feedsToUse], **or** commit a NuGet.config file to your source code repository and set its path using the nugetConfigPath argument.

In case other come here for debugging, the documentation states that one should use either `feedsToUse` or `nugetConfigPath`.  The either/or means that one should not supply both.  Usually, it is best to commit a NuGet.config, so that devs building locally have the same flow as the CI machine.

I'm not sure about @luanbon 's case, but, generally speaking, using `NugetToolInstaller` and `NuGetAuthenticate` tasks are recommended so that is the right path.
