### ISSUE TITLE
[AzureKeyVaultV1] Azure Key Vault Task to retrieve a version of a Key Vault object

### ISSUE THREAD

**Issue by chirangaalwis** [microsoft/azure-pipelines-tasks#14436]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureKeyVaultV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines

- Agent - Hosted or Private:
Hosted

## Issue Description
Azure Key Vault allows versioning of the stored objects.

Is it possible to allow retrieving a defined version of the Key Vault object (e.g. a particular version of a Secret stored at the Key Vault) instead of the latest version?

## Suggested Approach
Allowing users to define the Secret identifier + version in the `Secrets filter` (e.g. `MySecret:<v1>`, `MySecondSecret:<v2>`)

**Comment by chshrikh** [comment]
@ds-ms please assign this appropriately

**Comment by chirangaalwis** [comment]
@ds-ms @chshrikh it would be ideal if we can look into this as this is an important, missing feature in this task, which is available in pretty much every client interacting with the Azure Key Vault.

**Comment by chirangaalwis** [comment]
This is not stale and requires attention.
