### ISSUE TITLE
can't push 2 docker images in 1 task after Feb 11

### ISSUE THREAD

**Issue by yuzsun** [microsoft/azure-pipelines-tasks#14446]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: DockerV1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/commits/master/Tasks/DockerV1

## Issue Description
we are using Azure DevOps Pipeline to push image to ACR:
1. we are unable to push 2 images with 1 AzureDevOps task now, but we are able to do that before Feb 11.
2. we are able to push 2 images with 2 AzureDevOps tasks now. 

is there product change around this time?

**Comment by shigupt202** [comment]
@yuzsun Could you share the yaml pipeline showing the task how you have specified two images?
We did make a change around that time.

**Comment by shigupt202** [comment]
Closing stale issue. Feel free to reopen if you're still facing the issue and can provide the requested information.
