### ISSUE TITLE
"%25" appearing in URLs output from logic app ARM templates via listCallbackURL function

### ISSUE THREAD

**Issue by John-Bosch** [microsoft/azure-pipelines-tasks#14444]
## Required Information

*Type*: Bug

**Enter Task Name**: Azure resource group deployment

## Environment
- Server - Azure Pipelines - [health-ndss/NDSSIntegrationInfrastructure](https://health-ndss.visualstudio.com/NDSSIntegrationInfrastructure)    

First Showing: [NDSSIntegration.Full-Build_dev.21014.1/PreProd/Attempt#1](https://health-ndss.visualstudio.com/NDSSIntegrationInfrastructure/_releaseProgress?_a=release-environment-logs&releaseId=772&environmentId=2685)
Debug: [NDSSIntegration.Full-Build_dev.21052.1/Dev](https://health-ndss.visualstudio.com/NDSSIntegrationInfrastructure/_releaseProgress?releaseId=789&_a=release-environment-logs&environmentId=2785)

- Agent - Hosted - Azure Pipelines
    
## Issue Description

A "%25" has appeared in the logic app URL where just a "%" is expected in the output variable when an ARM template representing a logic app is deployed via the "Azure resource group deployment" task.

The output of the Logic App ARM template output is set here;
![image](https://user-images.githubusercontent.com/5135377/108789401-4702a300-75ce-11eb-81e2-609be6ea0a9a.png)

The ARM template output is stored to a Dev Ops variable in the task here:
![image](https://user-images.githubusercontent.com/5135377/108789322-1cb0e580-75ce-11eb-962b-8c81847688c8.png)

A simple dump of the environment variables via a PowerShell task shows the Dev Ops variables with now incorrect URLs:
![image](https://user-images.githubusercontent.com/5135377/108789657-cbedbc80-75ce-11eb-8060-71f5875738d1.png)

These variables are later fed in to an API Management ARM template deployment that now fails. 

This issue appears to have started sometime between 2021-01-19 and and 2021-02-04. The earlier date was a deployment to our test environment that contains no errant "%25" characters. On the later date a deployment to pre-production **of the same release** does have the errant "%25" characters. 

I assume this is related to the recent change to the encoding of the "%" character in vso commands but, in this case, setting the "DECODE_PERCENTS" environment variable to either "true" or "false" appears to make no difference (I have tried both).

### Task logs

Debug logs of a reduced release with non-relevant tasks disabled;
[ReleaseLogs_790.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6026262/ReleaseLogs_790.zip)

**Comment by bishal-pdMSFT** [comment]
> I assume this is related to the recent change to the encoding of the "%" character in vso commands but, in this case, setting the "DECODE_PERCENTS" environment variable to either "true" or "false" appears to make no difference (I have tried both).

Yes @John-Bosch this is the result of agent behavior change. AFAIK this change is an intended one and "DECODE_PERCENTS" set to "true" should help you get back to working. Please see [here](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md)

Please ensure that you are setting job level variable and not a task level environment variable.

**Comment by John-Bosch** [comment]
Thanks for the response @bishal-pdMSFT. 

As I said in the piece you quoted, I have tried this with DECODE_PRECENTS both true and false. The DECODE_PERCENTS variable is defined as a pipeline variable so it should be available to the job. In fact, if you look in the attached logs, which are the "true" case, you can see that it is set in the 1_Initialize job.log, line 56. You can also see that in 5_ndss-dev-integration-la-api-cgm-freestyle-libre (Logic App Deploy).log, line 230 that the output variable is being set with a URL containing %25.

If this is now intended behaviour, then I can only assume that the "Convert arm output" steps or the "API Management Deployment" step should be un-escaping the URL. Either way, the changes have broken my pipeline and the recommended fix (setting DECODE_PERCENTS to true has not fixed the problem).

DECODE_PERCENTS = true logs;
[ReleaseLogs_791.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6032067/ReleaseLogs_791.zip)

**Comment by vineetmimrot** [comment]
@John-Bosch We have fixed and deployed this fix 3 weeks back. So we are closing this issue. Let us know if the issue still persists.
