### ISSUE TITLE
ERROR:device_event_log_impl.cc(211)] [13:31:52.640] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed

### ISSUE THREAD

**Issue by BartNetJS** [microsoft/azure-pipelines-tasks#14452]
## Required Information

**Bug**  

**Task Name**: AzureCLI@2

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      account : atlascopco-its
      team project: Hybrid Integration Platform
      build id=3267

- Agent - Hosted 
    - If using Hosted agent, provide agent queue name: "Azure Pipelines"

## Issue Description

At the end of the azurecli@2 task the error below is written to the console:

ERROR:device_event_log_impl.cc(211)] [13:31:52.640] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/4865355/108852159-88eb1380-75e5-11eb-9111-674438bb2e31.png)

**Comment by tejasd1990** [comment]
Hi @BartNetJS ,
is this issue intermittent or persistent? 
Also, can you share the debug logs of a failure instance so that we can investigate more?

**Comment by BartNetJS** [comment]
Hi @tejasd1990 ,

I haven't checked it anymore.
But the error 'task has timed out' and causing the task to fail is because of the other message 'The STDIO did not close....'
I have added a comment in this thread were more people have this issue:
https://github.com/microsoft/azure-pipelines-tasks/issues/13033

**Comment by tejasd1990** [comment]
@BartNetJS , can you try [this](https://github.com/microsoft/azure-pipelines-tasks/issues/13033#issuecomment-808017800)

**Comment by ddivanshu** [comment]
Closing this.
Feel free to reopen if issue persists.
