### ISSUE TITLE
Can not access variable group variables from a non inline powershell script

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [microsoft/azure-pipelines-tasks#14458]
Since it isn't possible to using dynamic variable group variables like the following:

```ps1

$key = "key-name"
$secret = $($key)

```
I have to resort to autogenerating a PowerShell script via a code generation. The resulting script that I generate works fine as an inline script but not as a FilePath script. What I was hoping was that I could run my code generation in one task and then run generated script in the next task. 

The problem that I am facing is that the variable group variables are inaccessible in that generated script. All the ways that I have seen to get around this require manual work which is tedious an error prone. So what I am currently left with is to manually run the code generation and copy and paste that result into the inline script which works but is far from ideal. 

As far as I can tell there is no way to accomplish this via the Classic interface. This could be a really nice feature for my use case if there was a way to access those variables from a non inline script otherwise if you are dealing with more then a few variables this is error prone. 

My guess is this is a context issue where DevOps has more control of the inline script and can inject in those values and that's probably why the dynamic access doesn't work either. Is there any plans to make this story better? Is there another forum that I can ask for this to become a feature?

REF: PowerShell Task 2.*

**Comment by anatolybolshakov** [comment]
Hi @jwyglendowski-precisionlender from FilePath script you can access variables as $env:VAR_NAME, where VAR_NAME is upper-cased variable name. Could you please check if it works for you?

**Comment by jwyglendowski-precisionlender** [comment]
@anatolybolshakov Since these are getting pulled from KeyVault in variable groups and the key names have dashes in them how would I access them using $env:VAR_NAME syntax? For example, The variable group variable name is `VAR-NAME` currently I do that like `"$(VAR-NAME)"` which only works inline. `$env:VAR-NAME` is not valid in PowerShell far as I know. Thanks.

**Comment by jwyglendowski-precisionlender** [comment]
FYI. I just created a quick pipeline and branch for testing purposes. Changing the dash to underscore as now affect.

**Comment by jwyglendowski-precisionlender** [comment]
It seems I am not alone in my issue. https://github.com/microsoft/azure-pipelines-tasks/issues/10525

**Comment by jwyglendowski-precisionlender** [comment]
The suggestion in https://github.com/microsoft/azure-pipelines-tasks/issues/10525 is far from ideal beyond a few variables plus it requires manual work where if there was an underlying api that could be called from the script built in then all I have to maintain is a template of the configurations keynames with my repo.

**Comment by jwyglendowski-precisionlender** [comment]
So from my perspective I am suppose to use Variable Groups instead of calling Key Vault directly because it's more secure. That's the constraint I have which I am fine with. It would seem that the limitation is PowerShell and Azures inability to sandbox and sanitize things that are not inline. Which leads me to have to manually run an aerogeneration script and copy and paste that into devops as inline. What I would suggest is that you add a feature for a secure PowerShell script that resides under Secure Files where I as the developer could upload my script to and reference in a build step and you do all the things you do with an inline script. From my perspective that would work to solve have to do a ton of manual work and I think that would bring a ton of value to DevOps.

**Comment by anatolybolshakov** [comment]
@jwyglendowski-precisionlender this sounds like a more wide feature which requires changes in the process of how variables are handled in yaml, this repo is mostly for pipeline tasks - could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by jwyglendowski-precisionlender** [comment]
@anatolybolshakov Thanks for getting back to me. I just opened up a ticket at the recommended link. As soon as I get the verified ticket I will link to it here.

**Comment by jwyglendowski-precisionlender** [comment]
Okay here is the [link ](https://developercommunity2.visualstudio.com/t/can-not-access-variable-group-variables-from-a-non/1353542)in case anyone else runs into this issue.

**Comment by anatolybolshakov** [comment]
@jwyglendowski-precisionlender let me close this one at the moment here since it's not related to Powershell task itself.
