### ISSUE TITLE
AzureRmWebAppDeploymentV4 does not copy all changed node_module files

### ISSUE THREAD

**Issue by danielfen** [microsoft/azure-pipelines-tasks#14470]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4

## Environment
Azure Pipelines
Private agent, OS = Windows_NT, agent version = 2.182.1

## Issue Description

When using the 'Azure App Service deploy task v4.*' to release a NodeJS project, it was found in one of our release builds that some changes to an internally managed dependency in 'node_modules' were not reflected in the running app. Investigation of the task logs revealed that these updated files were not copied over with all other updated files i.e. they were not listed amongst the messages '<timestamp> Info: Updating file (<file>).' as you would expect them to be. Investigating the affected deployed .js files in the node_modules folder also revealed that they did not contain the changes expected and present both in local builds and in the build artifact uploaded by our build pipeline to be used by the deploy task.

## Troubleshooting

A couple points were noted about the node_module files that may affect whether the task determines if they should be updated or not:
- All node_module files always have the same last modified date of `1985-10-26T08:15:00.000Z`. This is a feature of NPM.
- The affected files in the dependency had only minor changes made i.e. an adjustment of one number to another of the same number of digits. This resulted in the modified file having the same file size as the initially deployed file.

The task was configured with the following 'Additional deployment options'

- Deployment Method - Web Deploy (however was also reproduced using Zip Deploy)
- Take App Offline - Enabled
- Remove additional files at destination - Enabled
- Exclude files from the App_Data folder - Enabled
- Additional Arguments
  - -allowUntrusted:true

It may be possible to reproduce using two minimal NodeJS projects, one depending on the other, using npm.
- Build and deploy the main project, using 'npm install' to pull in the dependency.
- Make a minor change to the dependency such that the file size remains the same (it was first observed when the number '21' was changed to '34')
- Build and deploy the main project again, using 'npm install' to pull in the dependency. 

Edit: To add, we have worked around the issue by manually removing the node_modules folder from the deployed app service (via a Kudu console) and re-running the deployment. This allowed the task to re-upload all of then node_modules files, and the change to our dependency was applied.

**Comment by AmrutaKawade** [comment]
> A couple points were noted about the node_module files that may affect whether the task determines if they should be updated or not:

@danielfen there is no such logic in task which determines whether to update file or not

> It may be possible to reproduce using two minimal NodeJS projects, one depending on the other, using npm.
> 
> - Build and deploy the main project, using 'npm install' to pull in the dependency.
> - Make a minor change to the dependency such that the file size remains the same (it was first observed when the number '21' was changed to '34')
> - Build and deploy the main project again, using 'npm install' to pull in the dependency.

while doing minor change in dependency are you updating its minor version?
Can you try these steps locally? not deploy part just build with npm install and check whether locally if node_modules are updated

**Comment by danielfen** [comment]
Hi @AmrutaKawade,

Yes the minor version in our package.json is definitely updated. As noted in the issue description, we also checked our local build & also the build artifact uploaded by our build pipeline (the artifact which is then deployed through our release pipeline by the 'Azure App Service deploy task'), and confirmed that the expected changes are present in both of those.

We modified the affected deployed file (via a kudu console), which was not being updated with the one from the build artifact, to introduce a more significant change on the deployed file. We also tried removing the node_modules directory entirely from the kudu console. In both instances, re-running the release pipeline caused the task to upload the file from the build artifact as expected.

- In the case of simply modifying the file via the kudu console, when the release pipeline was re-run with the same build artifact the task logs output the following messages:
`2021-02-25T13:19:49.7861207Z Info: Updating file (<file which was not previously being updated>).
2021-02-25T13:19:49.7862569Z Info: Updating file (<web.config file>).
2021-02-25T13:19:49.8036744Z Total changes: 2 (0 added, 0 deleted, 2 updated, 0 parameters changed, 5178 bytes copied)`

- In the case of removing node_modules via the kudo console, when the release pipeline was re-run the task logs output the following messages for every node_modules file:
`<timestamp> Info: Adding file (<node_modules file>).`

We also noted that, when we run the release pipeline with a new build artifact (and so the compilation would change the last-modified date) we see messages
`<timestamp> Info: Updating file (<main application file>)`
for every compiled file from our main application. However we do not see these messages if we re-run the build pipeline with the same build artifact. When using the same build artifact, if there have been no changes via e.g. the kudiu console, instead, we get the message
`<timestamp> Total changes: 0 (0 added, 0 deleted, 0 updated, 0 parameters changed, 0 bytes copied)`

It is these observations which lead us to believe, somehow, the task (or process used by the task) is deciding whether to upload the file based on some properties that it may have changed.

**Comment by AmrutaKawade** [comment]
For zip deploy its known issue https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url#issues-and-investigation

As mentioned in above link can you set `SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME=1` in appSettings

**Comment by danielfen** [comment]
Thank you @AmrutaKawade, I can confirm that workaround has worked for ZIP deploy!

It unfortunately did not seem to have any effect when using Web Deploy however, are you aware of any similar solutions when using Web Deploy?

**Comment by AmrutaKawade** [comment]
@danielfen Sorry I am not aware of solution for Web Deploy. For web deploy we use `msdeploy.exe`. but i did not find any workaround using this.

**Comment by AmrutaKawade** [comment]
@danielfen I will close this issue since its resolved

**Comment by AmrutaKawade** [comment]
@danielfen you said you have enabled `Remove additional files at destination`  option. with this option it cleans target directory and fresh package gets deployed. This issue should not occur with this option. Can you set `system.debug=true` in variables and share logs.

**Comment by danielfen** [comment]
@AmrutaKawade please find attached the logs from when we were investigating the issue. Two log files are included:

- tasklog_9_1529.log demonstrates the deployment where we expected the files to be deployed where they were not. The files in question are in a directory called '<app>\node_modules\<app>-validators\lib\fieldValidators\'. All files in this directory had only a small change applied and ultimately none changed in filesize.

- tasklog_8_1532.log demonstrates re-deploying the exact same artifact after modifying one of the affected files via a Kudu console.

Both deployments were using Web Deploy with the configuration listed in the issue description. Hope this helps futher!

[14470_logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6129529/14470_logs.zip)

**Comment by danielfen** [comment]
Hi @AmrutaKawade, we would just like to confirm, did the logs provided previously give you everything you need, or is there any other information that might help?
