### ISSUE TITLE
Allow double-hop for PowerShell on target machines task

### ISSUE THREAD

**Issue by GregoryOtt** [microsoft/azure-pipelines-tasks#14472]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: PowerShell on target machines v3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: Version Dev18.M170.6 (18.170.30525.1)

- Agent - Hosted or Private: 
    
    - Private agent:
      - OS : Windows 2016 Std - 10.0.14393 N/A Build 14393
      - Agent Version : 2.170.1

## Issue Description

- When using PowerShell on target machines v3, double hop is not possible as it uses Invoke-Command. Invoke-Command requires to pass credentials to allow double hop (https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ps-remoting-second-hop?view=powershell-5.1#pass-credentials-inside-an-invoke-command-script-block)
- Using PowerShell on target machines v2, double hop is possible as it uses a specific deployer

### Sample script to reproduce

````PowerShell
whoami

[System.Reflection.Assembly]::LoadFrom("System.DirectoryServices.AccountManagement.dll")
$current = [System.DirectoryServices.AccountManagement.UserPrincipal]::Current

if($null -eq $current) { # In V3 UserPrincipal is $null
    Write-Warning "UserPrincipal is null" 
    throw "UserPrincipal is null"
}
else {
    Write-Verbose $current.SamAccountName -Verbose
}
````

### Task logs

see attached log file : [ReleaseLogs_5584.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6044354/ReleaseLogs_5584.zip)

### Error logs

![image](https://user-images.githubusercontent.com/4428998/109183827-a27b8f00-778e-11eb-8060-2218c2b023e4.png)

**Comment by GregoryOtt** [comment]
Issue still here.

**Comment by erwinkramer** [comment]
bump, still needed

**Comment by codeforhealth** [comment]
I'm also having this problem.

**Comment by erwinkramer** [comment]
Bumpp

**Comment by Nico-1705** [comment]
BumpBump :)

**Comment by erwinkramer** [comment]
@Nico-1705 I'm betting 2025 for an answer.

**Comment by dwarry** [comment]
This is working intermittently for us in some of our environments; in others, there have been no problems at all. We're probably going to downgrade our Powershell On Target Machines tasks to v2.* to be on the safe side, though.

**Comment by ebuter9292** [comment]
Also encountering this; sounds more like a bug than an enhancement to me, since V2 does support it.
