### ISSUE TITLE
checkout with fetchDepth: 1 gets all tags

### ISSUE THREAD

**Issue by yene** [microsoft/azure-pipelines-tasks#14490]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: checkout  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Azure Pipelines

## Issue Description

When using
```
  - checkout: self
    fetchDepth: 1
```
it does a `git fetch --tags ...` behind the scenes, which still takes a long time to get all the data.
Could fetching tag be an option to disable?

**Comment by damccorm** [comment]
Hey @yene - the checkout task is actually driven from our agent repo (a little surprising I know) - would you mind filing an issue at https://github.com/microsoft/azure-pipelines-agent? That way it gets the right eyes on it.
