### ISSUE TITLE
Release Annotation has wrong category

### ISSUE THREAD

**Issue by darklove0504** [microsoft/azure-pipelines-tasks#14496]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 

AzureRmWebAppDeployment
AzureFunctionApp
AzureFunctionAppContainer
AzureWebAppContainer
AzureWebApp

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

## Issue Description
All above deployment tasks are sending release annotations with Category set to "Text", which is incorrect. In Application Insights blade (Performance/Failures). We only consider "Deployment" annotations are about release. As the results, Annotations are not displayed in AI blades.

![image](https://user-images.githubusercontent.com/1635288/109565432-4e76f000-7a97-11eb-971b-28196a746bfe.png)

**Comment by AmrutaKawade** [comment]
This will be automatically deployed after 4 weeks. closing this issue
