### ISSUE TITLE
FunctionApp deploy step succeeds, azure thinks otherwise

### ISSUE THREAD

**Issue by tomkuijsten** [microsoft/azure-pipelines-tasks#14495]
## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionApp

## Environment
Azure Pipelines, account name: Longskip, team project name: Longship, build: Longship.Connect.Monitoring 0.1.0+29

Hosted agent, agent queue name: 'Hosted', image: windows-latest

## Issue Description
The last few weeks we have to redo a lot of deployments. In DevOps the deploy steps are successful, but when checking the "Deployment Center" of the function app, it has a "Failed" status.

### Task logs
The download zip log option is not available in my environment (might be due to fully yaml pipeline?). I copied the raw log and put it in a zip.

[AzureDeployLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6064206/AzureDeployLogs.zip)

### Error logs
The error found in the kudu logs on the Azure Function:

[{"log_time":"2021-03-01T19:56:09.4193388Z","id":"5b1c1401-a3dc-41ef-85ef-2abb46b89dfa","message":"An unknown error has occurred. Check the diagnostic log for details.","type":2,"details_url":null}]

And when digging deeper in the kudu logs I find this error:

<step title="Error occurred" date="2021-03-01T19:56:02.115" type="error" text="Thread was being aborted." stackTrace="   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\OperationManager.cs:line 47 (and a whole bunch of extra exception lines)

**Comment by AmrutaKawade** [comment]
hey there is bug from our side if you see logs from `scm.azurewebsites.net/api/zipdeploy?` in `POLL URL RESULT` you could see that deployment has been failed. still we are showing success. we will fix this. 

till then can you try zip deploy option instead of run from zip deploy

![image](https://user-images.githubusercontent.com/65217380/109660059-6b421f00-7b8e-11eb-95ae-d22295a24117.png)

**Comment by tomkuijsten** [comment]
@AmrutaKawade thanks for your answer. I think you mean "zip deploy instead of **Run From Package**" (all those name changes doesn't make it easier 😄 ).

What will you fix? The problem that the kudu error didn't show up in the deploy logs? That would be a step forward of course, but I still don't know WHY the deploy failed. The only error I found was the "Thread was being aborted", but no idea why and no idea when it will happen again.

**Comment by AmrutaKawade** [comment]
> @AmrutaKawade thanks for your answer. I think you mean "zip deploy instead of Run From Package" (all those name changes doesn't make it easier 😄 ).

Yes I meant Run From Package 😁 thanks for pointing out corrected previous comment.

Fix would be failing task.

when deployment completes, logs are written by Azure itself at this location `https://***.scm.azurewebsites.net/api/deployments/latest/log` its not written by task. we just print those logs in task.

**Comment by tomkuijsten** [comment]
For the people who find this issue in the future, the actual problem is explained in the linked kudu issue and solved.
