### ISSUE TITLE
ArchiveFilesV2 not replaceing existing archive if the replaceExistingArchive option is set

### ISSUE THREAD

**Issue by myanakiev** [microsoft/azure-pipelines-tasks#14515]
https://github.com/microsoft/azure-pipelines-tasks/blob/9244d42f479f31600c1dff0dc6ca8e05b2e9f85c/Tasks/ArchiveFilesV2/archivefiles.ts#L340

The code is only logging that the file should be deleted but the action is missing.

**Comment by myanakiev** [comment]
Adding the folowing code should resove the issue `tl.rmRF(archiveFile);`

**Comment by anatolybolshakov** [comment]
Hi @myanakiev thanks for contribution! We rolled out related changes - closing it at the moment.
