### ISSUE TITLE
Techniques for cross-platform task with executable

### ISSUE THREAD

**Issue by phatcher** [microsoft/azure-pipelines-tasks#14513]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: N/A

## Environment
- Agent - Hosted or Private:  Both
    - If using private agent, provide the OS of the machine running the agent and the agent version: Either

## Issue Description

I'm looking to write a custom task that wraps an executable, but I want it to be cross-platform.  Binaries exist for both Windows and Linux so I'm looking for some advice about how to structure such a project and know which executable version to invoke based on the the OS of the agent running the task.

**Comment by egor-bryzgalov** [comment]
Hi @phatcher 

You can use features provided by `azure-pipelines-task-lib` npm package which should be used to create a custom task.
A step-by-step guide about creating your own tasks you can find in [the reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops).
[Here](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/azure-pipelines-task-lib.md) you can find a full reference for the package's features.
[And here](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/samples/toolrunner.src) you can find an example of executing binary with a ToolRunner class provided by the package.
Is this information helpful for you?

**Comment by phatcher** [comment]
@egor-bryzgalov Thanks for the information, that should give me a good start,

**Comment by egor-bryzgalov** [comment]
@phatcher 
I'm closing this issue. Please feel free to reopen or ping me if you need any help!
