### ISSUE TITLE
AzureRmWebAppDeployment@4 removes the WEBSITE_RUN_FROM_PACKAGE appSetting

### ISSUE THREAD

**Issue by mariusGundersen** [microsoft/azure-pipelines-tasks#14522]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

When running the AzureRmWebAppDeployment task with ZipDeploy, it removes the appSetting WEBSITE_RUN_FROM_PACKAGE from the deployed app. I have set this appSetting through an infrastructure deployment, together with several other appSettings, so it's weird that it is being removed when I deploy the app. So now I'm forced to specify this appSetting two places, which seems weird, since I don't have to specify other appSettings both places.

**Comment by AmrutaKawade** [comment]
@mariusGundersen you can select RunFromPackage deployment option from task. this will add `WEBSITE_RUN_FROM_PACKAGE` setting automatically for you

![image](https://user-images.githubusercontent.com/65217380/109906693-faeae900-7cc6-11eb-9f3e-f85f66bdf179.png)
