### ISSUE TITLE
Azure Dev Ops to pick up latest DacFx build

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azure-pipelines-tasks#14528]
## Environment
- Server - Azure Pipelines or TFS on-premises?: Azure pipelines 
 

## Issue Description
https://portal.microsofticm.com/imp/v3/incidents/details/214811143/home
This ICM was created a few months back where customer was not able to use deploy dacpac file using Azure DevOps. The problem was identified within DacFx product code and has been fixed in the latest version. Since the customer was trying to use DevOps to deploy dacpac, request you to pick the latest DacFx build so that the issue resolves for them.

**Comment by chshrikh** [comment]
please provide the task details

**Comment by SakshiS-harma** [comment]
Can you please elaborate on what task details are required here?

**Comment by chshrikh** [comment]
the ICM mentioned is not having any detailed about Azure devops, I was looking for issue details with azure devops

**Comment by SakshiS-harma** [comment]
So the customer was originally using Azure devops to deploy dacpac file, but for the purpose of our investigation and to figure out if the issue is with DacFx product code, we ask our customers to use Sqlpackage. And that is the reason why the ICM doesn't have any information about Azure devops. 
We are just looking for Azure Devops to pick the latest DacFx build. 
What are the details required for Azure Devops?
