### ISSUE TITLE
Cache hashing file path in addition to contents

### ISSUE THREAD

**Issue by thejcannon** [microsoft/azure-pipelines-tasks#14530]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache@2

## Environment
- Server - Azure Pipelines

   - Account name: (I don't know, "ni" perhaps)
   - Team project name: DevCentral
   - Build definition name: nibuild-pipeline-systemtestd
   - Build number: 750764

- Agent - Hosted or Private: 
  
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10, 2.181.0

## Issue Description

Cache seemingly caching the path itself along with the file contents. on the same pipeline with the same contents I see:

Using the key: `key: '"$(Agent.OS)" | "E:\dev\_temp/.venv" | $(Shared.SourcesDirectory)/eng/pipeline/nibuild/requirements_build.txt'`

```
Resolving key:
 - "Windows_NT"                                       [string]
 - "E:\dev\_temp/.venv"                               [string]
 - E:\dev\_r\2/eng/pipeline/nibuild/requirements_b... [file] --> B621D982EBA100A39C1BE9E64C3B1E31D2D4F3EF89866B70D0CFDE81EF9C7224
Resolved to: "Windows_NT"|"E:\dev\_temp/.venv"|L2vhta/ErPtUpzARQuUuWTbBg4ZvFQqAKUIlUokRf1Q=
```

And in a separate job:

```
Resolving key:
 - "Windows_NT"                                       [string]
 - "E:\dev\_temp/.venv"                               [string]
 - E:\dev\_r\7/eng/pipeline/nibuild/requirements_b... [file] --> B621D982EBA100A39C1BE9E64C3B1E31D2D4F3EF89866B70D0CFDE81EF9C7224
Resolved to: "Windows_NT"|"E:\dev\_temp/.venv"|iY5bl5kjyQmdx0IZb295aSsGwP3uHziuOa2XfESiNTM=
```

so we end up with a cache miss even though the key shouldn't have changed. The only difference is the path to the requirements file is in a differently named directory on one job vs. another job.

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by johnterickson** [comment]
IIRC if you use a relative path in the cache key then it will hash the relative path (which is the same).

**Comment by thejcannon** [comment]
From the docs:

> Relative file paths or file patterns are resolved against $(System.DefaultWorkingDirectory)

I think I'm missing a piece here, this would only work if the path I'm pointing to was a subdirectory of whatever `$(System.DefaultWorkingDirectory)` is, right?

**Comment by johnterickson** [comment]
I'm not sure if the `..` operator is allowed or not - it's worth a shot.  At a high level, including the path of the file as part of the hash is intentional - if I move or rename a `cpp` file, the compiler should be re-run.  Although the absolute path of a file actually *does* matter in some scenarios (e.g. PDBs contain absolute paths of inputs), the task IIRC does allow some wiggle room by only hashing the relative path and not the resolved absolute path.

**Comment by thejcannon** [comment]
Should this information be included in the documentation? Seems pertinent.

**Comment by thejcannon** [comment]
We ended up copying the file somewhere consistent (as the original file is not relative to `$(System.DefaultWorkingDirectory)` and can change from run-to-run).

I'll leave the issue open since I believe this should be documented behavior.

Thanks for the speedy responses!

**Comment by johnterickson** [comment]
Thanks for following-up with the workaround you found @thejcannon !
