### ISSUE TITLE
Feature request: add `user:` keyword to change execution user in scripts 

### ISSUE THREAD

**Issue by Febbe** [microsoft/azure-pipelines-tasks#14535]
## Required Information

*Type*:  Question ^ Feature

**Enter Task Name**: Answer "how to change user" Question or add "change user" option.   

## Environment
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
 [none, xournalpp, #20210304.17 Bump macos1013 on CI](https://dev.azure.com/xournalpp/xournalpp/_build/results?buildId=11325&view=results)

## Issue Description

I want to build gtk+ on macOS with jhbuild without removing brew.
The Gnome Dev Team [suggests](https://wiki.gnome.org/Projects/GTK/OSX/Building) creating and switching the user to prepare a "clean" - environment.

This unfortunately seems like harder than I thought, creating a user was not a problem at all, but as soon I try to switch the user, a new shell (/etc/bash) is started and the pipeline waits for the termination, which will not happen.

May question or feature request, If that's not possible currently is:
What's the best way to change the user, but still be able to see the output in the pipeline report (a script executed with that user is not the solution, as it will be executed silent).

I would like to have the option user for the bash task, which will execute the bash as the provided user.

**Comment by sdobrodeev** [comment]
Hi @Febbe You can execute the build command via `sudo -b -u <user> <command>`. The -b (background) option tells sudo to run the given command in the background. Also we can use `sudo -u <user> <command>&` and then get a PID of sudo process via `$!` variable for example for use with `wait <PID>` call.

**Comment by Febbe** [comment]
I am not sure, If you understand me correct; I am trying to execute several commands in the other userspace.

Also, I want, that those are visible to the azure pipeline log. Isn't that the exact opposite of the `sudo -b`. What I can do, and what I probably have to do is to write several scripts, which are all executed by `sudo -i -u`. But this has the disadvantage, that I can't see the output.

**Comment by Febbe** [comment]
My preferred solution would be a `user` option: 
```
steps:
  - bash | 
      <code for other user>
    user: ${{ other_user }}
    displayName: "set up build for user ${{ other_user }}"
<...>
```

**Comment by Febbe** [comment]
Calling `sudo -u /etc/bash -x ...` or adding `set -x` to the script does the trick.

**Comment by Febbe** [comment]
I still consider this as a good feature.
