### ISSUE TITLE
clarification on the word 'phase'

### ISSUE THREAD

**Issue by gforceg** [microsoft/azure-pipelines-tasks#14549]
Hello,

I am getting ["the artifact not found errors: Please ensure you have published artifacts in any previous phases of the current build."](https://github.com/microsoft/azure-pipelines-tasks/blob/3da3b2409ea7bb3f950f99b009ec9df033486c42/Tasks/DownloadBuildArtifactsV0/Strings/resources.resjson/en-US/resources.resjson#L45) I just need some clarification on what  the previous phases includes. Does it include all jobs, tasks, and stages?

I haven't found the term "phase" anywhere in [the pipeline YAML schema.](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)

Thanks!

**Comment by anatolybolshakov** [comment]
Hi @gforceg yes, correct - this exact message means that specified artifact has not been generated before Download Build Artifacts task in the current build.

**Comment by anatolybolshakov** [comment]
@gforceg please let me know if you have any other questions 😃

**Comment by anatolybolshakov** [comment]
@gforceg I'm closing it at the moment - feel free to ask any further questions.
