### ISSUE TITLE
AzureRmWebAppDeploymentV4 DevOps Release task doesn't update clientAffinityEnabled/ARR Affinity on App Service being deployed to

### ISSUE THREAD

**Issue by seanmbills** [microsoft/azure-pipelines-tasks#14556]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4/Azure app service deploy (in DevOps)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: N/A
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Release definition name: STNS.SPMT.PMT.AdhocPayouts - Release
Release number: Release-102

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Universal Store NEX

## Issue Description

When trying to use the AzureRmWebAppDeploymentV4/Azure app service deploy devops task in an Azure DevOps release, we're trying to set the "ARR Affinity" flag for our app services to false using the release pipeline and for some reason can't get it to work. In our release we've tried two different ways:
1. using the "Azure App service deploy" task and including this flag: -clientAffinityEnabled false : in the "Configuration settings" section
2. Using the "Azure App service settings" task and adding this `[ { "clientAffinityEnabled": false } ]` to the "General settings" section

Neither of these have worked in so much as they don't actually change the flag on any of our services to false, regardless of which slot/region I deploy to.

**Comment by AmrutaKawade** [comment]
Though ARR Affinity settings are visible on general settings page of Portal, its not part of configuration setting update

Check this API, what all settings can be updated via configuration setting

https://docs.microsoft.com/en-us/rest/api/appservice/webapps/updateconfiguration

You need to update this setting on portal directly or can update via Azure CLI/Azure Powershell task

**Comment by AmrutaKawade** [comment]
Closing this issue let me know if you need any more info
