### ISSUE TITLE
Question: how does FileTransform access secret variables?

### ISSUE THREAD

**Issue by yene** [microsoft/azure-pipelines-tasks#14553]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: FileTransform  

## Environment
Azure Pipelines

## Issue Description

hi, I was reading through the FileTransform source code, but could not figure out how FileTransform gets access secret variables, declared in the Variable Groups.
Is it like this that if a Pipeline Task has the right scope it gets the secret variables as environment variable?

**Comment by AmrutaKawade** [comment]
yes all variables defined in variable group are saved as environment variables

**Comment by AmrutaKawade** [comment]
Do you need any more info or can we close it?
