### ISSUE TITLE
GradleV2 build task for android app gets stuck intermittently on app:build task

### ISSUE THREAD

**Issue by nishi1612** [microsoft/azure-pipelines-tasks#14561]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GradleV2  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines:
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: MacOS-10.14 and Internal-MacOS-10.14.

## Issue Description

We observing that app:build task of Gradle@2 gets intermittently stuck on Private Mac Agents. This happens intermittently with no pattern observed till now. Frequency is one or two times per week. We also run our code on self hosted Windows agent where we have never found this issue. 
Please let us know what would be the correct way to solve issue.

### Task logs

I have logs captured. As they are confidential it would be difficult to share over Github. Please let me know if there is a way to share logs using internal Microsoft channel.
The logs were shared previously on https://developercommunity2.visualstudio.com/ from where I was asked to share logs over github issue. This is the link to the issue which has logs marked with Internal Microsoft tags : https://developercommunity2.visualstudio.com/t/intermittently-build-on-mac-agent-gets-stuck-on-ap/1303803

## Troubleshooting
We have tried to increase timeout for the job from 2 hours to 6 hours in our pipeline. But we still observe failures on pipeline due to timeouts.
We have set following flags in code as well yet the issue persists : 
```
org.gradle.daemon=true
org.gradle.parallel=true
```

**Comment by anatolybolshakov** [comment]
Hi @nishi1612 could you please share agent logs for the last stuck? You can send them to my email: v-anbols@microsoft.com

**Comment by anatolybolshakov** [comment]
@nishi1612 does it happen for you for self-hosted and hosted agents?

**Comment by nishi1612** [comment]
Hi @anatolybolshakov ,

It happens always on hosted agents only. We do run our pipelines on self hosted agents and never found this issue there.
However, task getting stuck is found almost once a week on azure hosted agent.

I will share the logs with you over email.

Thanks,
Nishi Doshi

**Comment by anatolybolshakov** [comment]
Hi @nishi1612 sorry for delay - we observed several issues with MacOS pools which have been resolved - does this issue still happen for you?

**Comment by anatolybolshakov** [comment]
Hi @nishi1612 is this issue still actual for you?

**Comment by nishi1612** [comment]
Hi @anatolybolshakov ,

I haven't seen this issue in last 1 week. But I will keep observing the pipelines to know if the issue still exists or not.

**Comment by anatolybolshakov** [comment]
@nishi1612 got it, thanks! Let me close this one at the moment - please let us know if you will face with the issue again.
