### ISSUE TITLE
How to get the AZ_BATCH_TASK_WORKING_DIR in a custom task

### ISSUE THREAD

**Issue by blesuer** [microsoft/azure-pipelines-tasks#14565]
I am creating a custom pipeline task and need to get the working directory of the task. I understand that there is an environment variable called AZ_BATCH_TASK_WORKING_DIR. I have attempted to get it with %AZ_BATCH_TASK_WORKING_DIR% and $(System.DefaultWorkingDirectory) but neither appears to be correct. What is the correct way to access the value of an environment variable inside a custom task written in TypeScript.
Thanks

**Comment by anatolybolshakov** [comment]
Hi @blesuer, in a custom task you can get variable using getVariable method from 'azure-pipelines-task-lib/task' like below:

const tl = require("azure-pipelines-task-lib/task");
const varName = tl.getVariable('System.DefaultWorkingDirectory');

Please also see task-lib [docs](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/docs/azure-pipelines-task-lib.md#taskgetVariable) for more context.

**Comment by blesuer** [comment]
Thanks for your reply @anatolybolshakov . I used getVariable in my task to get the System.DefaultWorkingDirectory but it returns 'undefined'. Is that because I am running from PowerShell and have not from a Pipeline yet?
Thanks again

**Comment by anatolybolshakov** [comment]
@blesuer yes, it should work in a pipeline - you can try to upload task to some test organization via [tfx-cli](https://www.npmjs.com/package/tfx-cli) tool and check it.

**Comment by blesuer** [comment]
@anatolybolshakov that worked perfectly. Thanks
