### ISSUE TITLE
Add ability to specify feeds to use to NuGet tasks' custom command

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-tasks#14576]
In our pipelines we need the ability to run **nuget.exe install** command against specific feeds. Unfortunately, NuGet tasks's **custom** command does not allow this.

**Comment by avivanoff** [comment]
Looks like [NuGet Authenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) is the proper way to go.

**Comment by avivanoff** [comment]
@sdobrodeev, any updates?

**Comment by avivanoff** [comment]
Any updates?

**Comment by avivanoff** [comment]
Any updates? A simple "yes"/"no" would do.

**Comment by avivanoff** [comment]
ANy updates?

**Comment by jmyersmsft** [comment]
The NuGet Authenticate task is indeed the way to go. The NuGet task is soft-deprecated and we are no longer adding new features to it.
