### ISSUE TITLE
[Question] overrideParameters for ARM parameters "type": "object"

### ISSUE THREAD

**Issue by nekdima** [microsoft/azure-pipelines-tasks#14586]
Anyone idea on how to reference a parameter **object** from an ARM template in a pipeline task _overrideParameters_? 
Object example: 

azuredeploy.json **object** reference

```
"virtualMachines": {
            "type": "object",
            "metadata": {
                "description": "Object, containing a list of VM variables"
            }
        },
```

azuredeploy.parameters.json **object** reference

```
"virtualMachines": {
            "value": {
                "name": "vmname",
                "numberOfInstances": 2,
                "vmSize": "Standard_D2as_v4",
                "sku": "2016-datacenter-smalldisk-g2",
                "osDiskSize": "64",
                "diskSizeGB": "64",
                "osDiskSku": "Premium_LRS",
                "dataDiskSku": "Premium_LRS",
                "osPublisher": "MicrosoftWindowsServer",
                "osOffer": "WindowsServer",
                "ipConfigurationsName": "ipconfig1"
            }
        },
```

Usual  string / integer reference would look like: 
`overrideParameters: '-pipelineVariableName $(templateVariableName)'`

example:
`overrideParameters: '-virtualNetworkName $(virtualNetworkName)'`

Thx in advance!

**Comment by tejasd1990** [comment]
@nekdima ,
the syntax `$(templateVariableName)` used in the tasks' `overrideParameters` input is for pipeline variables, not arm template variables.
Does [this parameter naming](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-parameters?tabs=json) not achieve what you are looking for? Going by the examples from the document, you can use something like 
```
"resources": [
    {
      "type": "Microsoft.KeyVault/vaults",
      "apiVersion": "2019-09-01",
      "name": "[parameters('vaultName')]",
      ...
    }
  ]
```

or

```
"parameters": {
  "siteName": {
    "type": "string",
    "defaultValue": "[concat('site', uniqueString(resourceGroup().id))]"
  },
  "hostingPlanName": {
    "type": "string",
    "defaultValue": "[concat(parameters('siteName'),'-plan')]"
  }
}
```

**Comment by nekdima** [comment]
@tejasd1990 
Thank you for your reply. I'm actually already ARM-template parameter file. 
The idea of the above is to overwrite single parameters file depending on environment you deploy to.
So in the end I'll have multiple pipeline parameter files which will be overwriting defaults of ARM-parameter file AND pipeline variables depending on the stage.

**Comment by tejasd1990** [comment]
@nekdima ,
if you want multiple parameter files for multiple stages, a single [stagelevel variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) with different values for different stages should work as the `csmParametersFile`/`csmParametersFileLink` input, and you can set stagelevel values for override parameters as well.

**Comment by anuragc617** [comment]
@nekdima Does the above suggested workaround work for you?

**Comment by ddivanshu** [comment]
Closing this .
Feel free to reopen if issue occurs again.
