### ISSUE TITLE
ManualValidation timeout reject whole pipeline, resources approvals timeouts don't

### ISSUE THREAD

**Issue by MirKml** [microsoft/azure-pipelines-tasks#14584]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ManualValidation

## Issue Description

When ManualValidation task timeouts it rejects by default, then following tasks also fails and whole pipeline fails.

![image](https://user-images.githubusercontent.com/21239658/111037231-841ac200-8423-11eb-92ee-779209f46cd2.png)

It's problematic. Timeout doesn't mean in many cases, that something is wrong. Deployment - as it's used on screenshot - is on demand, and can be rerun later. So failed tasks and pipeline is misunderstood.

In comparison with Manual Approvals, timeout for approval means that following tasks are skipped and pipeline itself success.

![image](https://user-images.githubusercontent.com/21239658/111037466-5d10c000-8424-11eb-8613-0ea3b1c199a2.png)

ManualValidation and Manual Approvals are mostly used for same goal - add manual control into pipeline flow. I think same possibility in timeout reaction is desired.
I suggest third possibility for `ManualValidation.onTimeout` settings - 'skip'.

**Comment by MirKml** [comment]
I classified this one as bug, maybe can be reclassified as Feature - it's up to you Azure crew :wink:

**Comment by chshrikh** [comment]
@ds-ms to assign it appropriately

**Comment by MirKml** [comment]
No response from MS team yet.

**Comment by MirKml** [comment]
No response from MS team yet.

**Comment by UsmanMohammad** [comment]
There needs to be a better way for skipping a stage, manual validation step just causes it to register as a fail

**Comment by sheldonhull** [comment]
I found this also looking for a way to mark the pipeline as a skip, warning, or something other than a failure. 
I also can't find any mention of output variable that would allow me to just add a post timeout step to write a message to slack for "$(manualvalidation.Reason)" or such to put in timeout rather than decline. That might be a separate issue, but if the state was exposed as a variable output, then at least I could just use the `##vso` commands to mark as issue, skip, warning or whatever I wanted, as well as output to chat.

**Comment by MirKml** [comment]
still no response from MAS (message for removing stale label)

**Comment by dczlth** [comment]
Could we please have an update on this issue?

**Comment by travisterrell** [comment]
No response from MS still. Come on, guys.

**Comment by yefka** [comment]
Hi, we actually have the same problem.
After migrating from Release pipeline to YAML pipelines, we were using that to have a "manual" execution on the stage.
An alternative would be to have the ability to set the stage execution as "manual".

This is a discussion about this here :
https://developercommunity.visualstudio.com/t/Specify-manual-stages-in-multi-stage-YAM/629260#T-N10458007

**Comment by hqc01234** [comment]
Any update on this ?

**Comment by Alexamakans** [comment]
@merlynomsft I don't know who to mention for this, but could you reopen this issue so that it gets visibility, or mention somebody that can make that decision? I picked you because you seemed to be active in this repo recently.

**Comment by nguyenann13** [comment]
Would really like this implemented, it's annoying have to go in every time to discern an actual failure from a timeout.

**Comment by Kryptos-FR** [comment]
Any news?

**Comment by DaveOHenry** [comment]
This was closed without a solution, but there is a new issue here:
https://github.com/microsoft/azure-pipelines-tasks/issues/21103
