### ISSUE TITLE
Azure File Copy (v4) stopped working

### ISSUE THREAD

**Issue by ericlemes** [microsoft/azure-pipelines-tasks#14580]
## Required Information

**Bug**  
*Type*: Azure File Copy task stopped working in my production pipeline with no apparent changes to the environment. It seems to be having issue to download Azure File Copy on the target machine

**Enter Task Name**: Azure File Copy (v.4)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server: Azure DevOps
Account name: squk-central
Team: Code Metrics
Build definition: Release definition 7
Build id: release id 249

- Agent - Hosted or Private: 
Private agent. Windows 2016 - agent version 2.174.1
    
## Issue Description

Last week this task run with success, this week on a new deployment it stopped working. No changes have been made to the environment.

Analysing the logs, it gives an impression that the task remotely tries to download AzCopy on target machine, which is failing:

+ FullyQualifiedErrorId : Failed while downloading azcopy.exe from the URL with exception Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive.". Please download azcopy.exe 10.8.0 and set this extracted path in env:Path

After running the task, I observed that there is an empty C:\ADO_AzCopy10 folder created on the target machine.

This machine has registry settings enabled to only allow TLS 1.2 connection as company policy. In a previous issue, we added *.windows.net as exceptions on internet explorer.

### Task logs

Attached

[tasklog_7.log](https://github.com/microsoft/azure-pipelines-tasks/files/6129422/tasklog_7.log)

**Comment by chshrikh** [comment]
is it intermediate issue ?

**Comment by chshrikh** [comment]
sorry missed that logs are already attached, is there any proxy setting applied on target

**Comment by ericlemes** [comment]
@chshrikh, the issue is still blocking my production continuous release pipeline. There's no proxy settings applied to the target.

**Comment by AmrutaKawade** [comment]
Adding this before downloading azcopy zip on target VM, solved the problem

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by ericlemes** [comment]
@AmrutaKawade, can you let me know when this is deployed?

**Comment by AmrutaKawade** [comment]
> @AmrutaKawade, can you let me know when this is deployed?

I updated issue based on our yesterdays discussion. I haven't fixed it yet

**Comment by AmrutaKawade** [comment]
As task owner we can't take dependency on any particular version of tls. and since tls 1.0 and 1.1 is deprecated now you can disable tls in internet explorer options as mentioned here 

https://docs.microsoft.com/en-us/lifecycle/announcements/transport-layer-security-1x-disablement

https://warwick.ac.uk/services/its/servicessupport/web/sign-on/help/tls1-eol/ie/

Closing this issue as no fix from task is required
