### ISSUE TITLE
ExtractFiles not waiting for files to be actually created

### ISSUE THREAD

**Issue by oggy22** [microsoft/azure-pipelines-tasks#14601]
On our [pipeline](https://microsoft.visualstudio.com/Edge/_build?definitionId=39488&_a=summary) where we use ExtractFiles, it happens sometimes that the files are not created when the task finishes, but probably a bit later, and the task right after it fails before it can't find the files expected to be there after uncompression. I think I know why this happens. Namely, this returns a task:
https://github.com/microsoft/azure-pipelines-tasks/blob/6d606184245107304b7f5d2ce84a4265da6c5006/Tasks/ExtractFilesV1/extractfilestask.ts#L315
which should be waited on to ensure that all files are created, but it's not.

**Comment by tatyana-kostromskaya** [comment]
@oggy22 Could you please provide minimal reproducing steps for this issue as we don't have access to the pipeline?

**Comment by anatolybolshakov** [comment]
@oggy22 @tatyana-kostromskaya btw there is no asynchronous code in line: https://github.com/microsoft/azure-pipelines-tasks/blob/6d606184245107304b7f5d2ce84a4265da6c5006/Tasks/ExtractFilesV1/extractfilestask.ts#L315
So it does not seem to be issue with awaiting of asynchronous code result.

**Comment by tatyana-kostromskaya** [comment]
Hello, @oggy22 , do you have any updates here?

**Comment by tatyana-kostromskaya** [comment]
As we didn't get any response for 2 weeks, I closed this issue.
Feel free to reopen it in case of new reproes.
