### ISSUE TITLE
Allow task to work with bicep files as the template

### ISSUE THREAD

**Issue by brekus** [microsoft/azure-pipelines-tasks#14608]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: ARM Template Deployment 

## Environment
- Server - Azure Pipelines 

- Agent - Hosted 

## Issue Description

It would be great if this task can now allow using bicep files as the template file.  Understanding the fact the bicep CLI would need to be installed first which is already a preview task.

**Comment by anon65856** [comment]
Would love to see this too!

**Comment by allanlw** [comment]
Seems like the AzureCLI task is now 2.20 with auto bicep support so you can just use `az deployment group create` via that if you don't need the extra features of the ARM Template Deployment task

**Comment by mmajcica** [comment]
This would be a nice addition. I see this has been assigned, any idea when will something be available?

**Comment by djfr** [comment]
I've just tested the `AzurePowerShell@5` on `latestVertion` task and it doesn't have the Bicep CLI installed. It would be great to get it there 👍 

Alternatively, this marketplace task works well:
https://marketplace.visualstudio.com/items?itemName=piraces.bicep-tasks

**Comment by vermegi** [comment]
Having this ability directly in the AzureResourceManagerTemplateDeployment would be great. Currently AzureCLI or AzurePowerShell are the only options and for these user needs to know either CLI or PowerShell. AzureResourceManagerTemplateDeployment  task gives an easy way of running ARM deploy through simple config, which some users prefer.

**Comment by vermegi** [comment]
Culprit: https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureResourceManagerTemplateDeploymentV3/operations/Utils.ts#L184-L190

**Comment by anon65856** [comment]
@vermegi do you think this could get prioritised some how?

**Comment by johndowns** [comment]
Please keep this open.
