### ISSUE TITLE
Issue with 'IIS web app deploy' and 'App Service Deploy' in context of unzipping package zip with file transformation 

### ISSUE THREAD

**Issue by chshrikh** [microsoft/azure-pipelines-tasks#14607]
**Context**
Recently we got customer feedback where zip package built using msbuild corrupts the file names [having special characters](https://github.com/dotnet/msbuild/issues/6165).  There is an issue to deploy such zip packages using mentioned tasks with file transformation enabled.

**Details**
1. Post analysing the issue, we found that, if we make use of "Expand-Archive" cmdlet to unzip the zip, it is able to handle these special characters and deployment works smoothly. 
2. So we have updated the task logic to make use of "Expand-Archive" cmdlet for packages built using msbuild. 
3. For any other package built from other tools, we make use of 7 zip to unzip the package.
4. In case any one wants to make use of 7 zip forcefully for unzipping the zip, in pipeline add a new variable named - ADO_FORCE_USE_7ZIP and set its value as true.

**Comment by fenton-nick** [comment]
Hello,  I'm now receiving an "the term 'Expand-Archive' is not recognized" error from my IISWebAppDeploymentOnMachineGroup release task, Target machine has powershell v4.0 installed. Logs attached.

[tasklog_7.log](https://github.com/microsoft/azure-pipelines-tasks/files/6165376/tasklog_7.log)
