### ISSUE TITLE
Using PowerShell to unzip MSBuild Package Breaks Release

### ISSUE THREAD

**Issue by mark-mybaggage** [microsoft/azure-pipelines-tasks#14614]
I'm using IIS web app deploy to an ASP.Net application to multiple EC2 instances in AWS

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: IISWebAppDeploymentOnMachineGroupV0 (IIS web app deploy)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
Accountname: https://dev.azure.com/mybaggage
ProjectName: MyBaggageDev
Release definition name: Peek NIParcels
Link: https://dev.azure.com/mybaggage/MyBaggageDev/_releaseProgress?_a=release-environment-deployment-group-logs&releaseId=1488&environmentId=1488&deploymentGroupPhaseId=663

- Agent - Hosted
    
    - windows-2019

## Issue Description

Since version 0.184.0 (#14445) 2 of my release pipelines started to fail.  When executing the unzip command I received the following error:

Expand-Archive : The path 'C:\azagent\A3\_work\r3\a\_mybaggage.niparcels.master\drop\website.zip\' either does not
exist or is not a valid file system path.

The cause was that the file path was too long for some files.

![Screenshot 2021-03-18 at 08 35 40](https://user-images.githubusercontent.com/52959261/111596337-f80eee80-87c4-11eb-850a-a3fb29ee18d9.png)

I then went back to a release that succeeded and saw that a different method of extracting the zip file was used:

C:\azagent\A3\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.179.0\node_modules\webdeployment-common-v2\7zip\7z.exe x -oC:\azagent\A3\_work\_temp\temp_web_package_05200444646182323 C:\azagent\A3\_work\r3\a\_mybaggage.niparcels.master\$(Parameters.ArtifactName)\website.zip

This was version 0.179.0 of the IISWebAppDeploymentOnMachineGroupV0 task.

Looking at the PR (#14445), I saw that an environment variable could be used to force the older unzip process.  After setting this environment variable, my release pipleine completed successfully.

Is there a way to resolve the file path length issue with Powershell?  Or make the environment variable a permanent option?

### Error logs

[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6162506/logs.zip)

**Comment by chshrikh** [comment]
we will suggest to mark the environment variable as permanent option. We got customer feedback like 7 zip is creating issues for them and powershell unzip logic work fine for them, to ensure all scenarios should work fine, we have come up with this new solution. Appreciate your continuous feedback and support to improve the product.  

https://github.com/microsoft/azure-pipelines-tasks/issues/14607

**Comment by brunobritorj** [comment]
Hello all,

I have the same issue in the Windows 2016 hosted agent, it happens only in some pipeline releases.

My concern is that we can use this env variable to force old version (7zip) now, but I some moment this old version (maybe) won't be no longer supported.

Couldn't 7zip remains at default in the 0* version of the task and a newer version comes up with the new solution?

Thanks

**Comment by abergie** [comment]
Same issue, would be nice in future to bump Task version when introducing possible breaking changes like in #14445

**Comment by penihel** [comment]
#14595

**Comment by irontoby** [comment]
Why would the `ADO_FORCE_USE_7ZIP` workaround be an environment variable instead of just an input parameter to the task? Amazing that this change was introduced with no documentation and started breaking all of our deploys with no obvious way to fix it.

Can this be switched to a 3-way task parameter (7Zip, PowerShell, or AutoDetect) and have the AutoDetect improved for cases where the `Expand-Archive` command is not available? It should test whether the command exists and always use 7Zip if not.

This change really should have been tested more before being deployed with a breaking change in such an important and widely-used Task.

**Comment by javafun** [comment]
It seems breaking the `XML transformation` as well. See details [here](https://github.com/microsoft/azure-pipelines-tasks/issues/14634)

**Comment by chshrikh** [comment]
Sorry for the inconvenience caused.
We are working on fix which will solve both the issues 1) defaulting to existing 7 zip tooling and 2) Handling the special characters with msbuild packages.
Only customers who are facing issues with special character in msbuild need to update their pipelines and add a special variable "ADO_FORCE_USE_PSUNZIP" with value 'true', other customer does not need to update their pipeline, their scenario should work fine as it was working till last week. Even for customer who has added pipeline variable "ADO_FORCE_USE_7ZIP" or installed PS core, there should not be any change required, their scenario will continue to work without any pipeline / task update.
We are already in process of rolling out the new fix with 0.184.1 version of task. It will reach to all customer within next three days.
Thank you for support

**Comment by chshrikh** [comment]
The deployment of 0.184.1 has been completed, as stated with previous comment, existing pipeline should was as expected and defaulted to use 7 zip
