### ISSUE TITLE
Invalid typed array length error when deploying zip file with AzureRmWebAppDeploymentV4

### ISSUE THREAD

**Issue by bobharing** [microsoft/azure-pipelines-tasks#14612]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy (AzureRmWebAppDeploymentV4)

list here (V# not needed):
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Unless really necessary I would prefer not to answer.

- Agent - Private: 
    
    - OS Name: Microsoft Windows Server Datacenter
    - OS Version: 10.0.19041 N/A Build 19041
    - Agent version: 2.179.0

## Issue Description

When running the Azure App Service deploy task version 4.181.0 to deploy a zip file we encountered the following issue visible in the logs:
**RangeError: Invalid typed array length**
We are running the Azure App service deploy task with the following configurations:
- Deployment Method - Zip Deploy
- XML transformation - Enabled
- JSON variable substitution - **/*.json

### Task logs
[tasklog_13.log](https://github.com/microsoft/azure-pipelines-tasks/files/6159617/tasklog_13.log)

## Troubleshooting
We have had a successful release to the App Service before with a zip of 10MB, the release that is failing now is a zip of 314MB. According to the KUDU documentation found [here](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip) the max size allowed is 2048MB. When extracted the zip has a size of 809MB.

What is new with this zip is that we have included the node_modules folder as we would like to prevent running npm install on the app service directly as we already do this on a separate build pipeline.

I can only assume it's related to the size of the zip or the amount of files/folders. But I am unable to find more information regarding what are the limits regarding this in documentation. I have found a post in the developer community: https://developercommunity.visualstudio.com/t/app-service-deployment-results-in-rangeerror-inval/1296848 It was recently answered and another developer encountered a similar scenario, but I'm unable to piece what exactly is the size limit according to that answer.

**Comment by AmrutaKawade** [comment]
How are you zipping your files?

**Comment by Banzboy** [comment]
It gets created from the task DotNetCoreCLI@2 publish task.

**Comment by v-jkarri** [comment]
Please let us know whether you are still facing the issue.
