### ISSUE TITLE
Enable XML transformation and receive 'Parameters.ArtifactName' is not recognized as the name of a cmdlet 

### ISSUE THREAD

**Issue by javafun** [microsoft/azure-pipelines-tasks#14634]
## Note  
I'm using IIS web app deploy to an ASP.Net application to external IIS webserver hosted with a third party provider.

Everything works fine in the last 5 months, and it failed to deploy to our webserver 3 days ago. The only difference I can see is the `IISWebAppDeploymentOnMachineGroupV0 ` task has been silent upgraded from **0.179.0** to **0.184.0**, and the issue starts happening. 

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**:  IISWebAppDeploymentOnMachineGroupV0 (IIS web app deploy)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines         

- Agent - Hosted
    
    -   OS: Windows 2019 Agent: 2.184.0

## Issue Description

![image](https://user-images.githubusercontent.com/332991/111932557-c3c36700-8b11-11eb-924c-c5ed47f4d594.png)

### Task logs

Failure step log can be found below
[tasklog_5.log](https://github.com/microsoft/azure-pipelines-tasks/files/6179025/tasklog_5.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

![image](https://user-images.githubusercontent.com/332991/111932290-3d0e8a00-8b11-11eb-95a1-7de9f12a05be.png)

**Comment by chshrikh** [comment]
please share the pipeline detailed logs ( detailed logs can be obtain by setting sytem.debug variable with value true )

**Comment by mark-mybaggage** [comment]
I encountered the same issue following the update to 0.184.0.  In my case, it was an issue with my build pipline - essentially something that was always wrong, but 7zip (0.179.0) didn't complain about.

The screenshot shows the changes I made to correct this issue:

![build](https://user-images.githubusercontent.com/52959261/111953113-1551fe80-8ade-11eb-8c1f-c8ec89961b85.png)

When I looked at older Release logs, the file path my artifcates were saved to, included '$(Parameters.ArtifactName)' similar to your screenshot

Hope this helps.

**Comment by chshrikh** [comment]
@mark-mybaggage in case you add one pipeline variable "ADO_FORCE_USE_7ZIP" with value 'true', task will use 7 zip. Could you please try if this helps you to unblock your scenario

**Comment by mark-mybaggage** [comment]
@chshrikh, thanks.  I've done that and created #14614 to track the issue.

**Comment by chshrikh** [comment]
Sorry for the inconvenience caused.
We are working on fix which will solve both the issues 1) defaulting to existing 7 zip tooling and 2) Handling the special characters with msbuild packages.
Only customers who are facing issues with special character in msbuild need to update their pipelines and add a special variable "ADO_FORCE_USE_PSUNZIP" with value 'true', other customer does not need to update their pipeline, their scenario should work fine as it was working till last week. Even for customer who has added pipeline variable "ADO_FORCE_USE_7ZIP" or installed PS core, there should not be any change required, their scenario will continue to work without any pipeline / task update.
We are already in process of rolling out the new fix with 0.184.1 version of task. It will reach to all customer within next three days.
Thank you for support

**Comment by chshrikh** [comment]
The deployment of 0.184.1 has been completed, as stated with previous comment, existing pipeline should work as expected and defaulted to use 7 zip
