### ISSUE TITLE
SqlAzureDacpacDeploymentV1 - Service Principal Authentication Bug

### ISSUE THREAD

**Issue by jing-x** [microsoft/azure-pipelines-tasks#14632]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- Agent - Hosted or Private: 
    
    Hosted

## Issue Description

Unable to establish database connection with Service Principal authentication type.

**Comment by AmrutaKawade** [comment]
@jing-x 

what error are you getting? we already set `access_token` value to `$accessToken`

https://github.com/microsoft/azure-pipelines-tasks/blob/5b187c1e2ea3961fead03a521c67677cd9602e51/Tasks/SqlAzureDacpacDeploymentV1/DeploySqlAzure.ps1#L104

**Comment by AmrutaKawade** [comment]
Closing this issue this change is not required.
