### ISSUE TITLE
VSTest Test timesout after 60 minutes in ADO build pipeline but continues to run in release pipeline

### ISSUE THREAD

**Issue by loganwol** [microsoft/azure-pipelines-tasks#14644]
**Question, Bug, or Feature?**  Question
*Type*: Timeout

**Enter Task Name**: VSTest

I have a test library that has an MSTest method with DynamicData attribute that results in the actual number of tests run about 100. When I run this test in Azure Devops Build pipeline (through yml file), the VSTest task times out around 60 minutes every single time in the build pipeline.

When I tried the same test in a Release pipeline, the test continues to run for the 100 minutes that logically it was supposed to run. Can the task be made similar in both Build and Release pipelines?

The task is identical when compared between the two pipelines.

`
- task: VSTest@2
        displayName: 'VsTest - testAssemblies'
        timeoutInMinutes: 0
        inputs:
          testAssemblyVer2: |
           **\*AcceptanceTests*.dll
           !**\*TestAdapter.dll
           !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)\drop'
          vsTestVersion: toolsInstaller
          testFiltercriteria: $(testcasefilter)
`

**Comment by phanikmmsft** [comment]
@ganesp @ankit-arora12 pls check

**Comment by ankit-arora12** [comment]
@loganwol Please share full logs with System.Debug variable set to true.
