### ISSUE TITLE
VSTest Test fails midway, continues and then reports overall success

### ISSUE THREAD

**Issue by buckleyGI** [microsoft/azure-pipelines-tasks#14659]
**Question, Bug, or Feature?** Question
Type: Error handling

**Enter Task Name**: VSTest  2.170.1

Hi,

We are noticing that our test suite execution fails but that the job still succeeds.

`##[error]The active test run was aborted. Reason: Test host process crashed`

The above error is logged during the test execution.
At the end you see `##[error]Test Run Aborted.` but then it exits with a green success message.

Should we handle the error ourselves instead of the task? Is

 some custom logic in place here?

Thank you

![image](https://user-images.githubusercontent.com/2102864/112482611-890f3800-8d78-11eb-9aad-f66d5dd96473.png)

![image](https://user-images.githubusercontent.com/2102864/112482635-8f9daf80-8d78-11eb-8f9c-fd57d7c1d9dc.png)

Our reference https://dev.azure.com/selligentsim/ES/_build/results?buildId=211549&view=logs&j=2522bd19-13d3-5eb7-2f02-0e3255860ef2&t=47ce024d-8077-59c3-5959-faaa575df249&l=1877

**Comment by JoAlbahari** [comment]
We are also hitting this exact same issue. Do you think this is expected behavior? It should fail as soon as there is an error right.

**Comment by JoAlbahari** [comment]
One trick to mitigate the problem for now is to add a task in the end that checks for an expected number of tests and make it fail when there is a drop in the tests.

**Comment by buckleyGI** [comment]
**Environment**
Server: Azure DevOps
Account name: selligentsim
Team: Test

Agent - Hosted or Private:
Hosted. Current agent version: '2.165.0'

**Comment by ankit-arora12** [comment]
@buckleyGI Please share full logs zip with System.Debug variable set to true.

**Comment by ankit-arora12** [comment]
Closing this issue since there is no response.
