### ISSUE TITLE
Some ADO tasks hang at 100% forever until the job timesout

### ISSUE THREAD

**Issue by sudadwalms** [microsoft/azure-pipelines-tasks#14651]
Environment:
ADO online: https://dev.azure.com/Intentional

We are seeing that some of our long-running ADO tasks will remain in the 100% state until the job times out:
![image](https://user-images.githubusercontent.com/68205320/112388007-be9c1e80-8caf-11eb-8dbf-fcc0166fff82.png)

This has been observed with the dotnet test task and the jenkins queue job task

**Comment by chshrikh** [comment]
can you specify which tasks not working and which tasks works fine ?
