### ISSUE TITLE
How to create resources in Azure Portal using Devops CI/CD pipeline and ARM Template

### ISSUE THREAD

**Issue by SujeetKulkarnii** [microsoft/azure-pipelines-tasks#14654]
I am working on creating QnAMaker based bot and for this I have ARM template and PowerShell script used for creating and deploying resources on azure .
PowerShell script is being used to create knowledge base once all the resources are created .
This process works just fine when I am executing PowerShell script from local PowerShell tool
Now I want to do CI/CD for this deployment process .
Creating resources and deploying to azure through Pipeline is quite possible through Azure ARM deployment step but I am unable to execute PowerShell script post resources creation that is responsible for creating knowledge base based on recently created QnAMaker service 
Any help greatly appreciated

**Comment by anuragc617** [comment]
@SujeetKulkarnii you can use AzureResourceManagerTemplateDeploymentV3 task to create Azure resource using ARM templates. You can use deployment outputs to reference the output of ARM template in subsequent tasks. For powershell script, you can add PowerShell or Azure CLI task and run the script in it.

**Comment by anuragc617** [comment]
Closing this, please feel free to open an issue if you need more assistance.
