### ISSUE TITLE
Re-use previous Azure CLI task login session in subsequent CLI tasks

### ISSUE THREAD

**Issue by cbellee** [microsoft/azure-pipelines-tasks#14657]
**Question**
We are trying to optimize the execution speed of our DevOps pipeline as much as possible and are using multiple instances of the Azure CLI task (rather than multiple azure cli scripts in one task), as we want granular observability on the tasks (e.g. at a quick glance of a pipeline, they can see specifically which task has failed).

From an inspection of the Azure CLI Azure DevOps task log output, it looks as though the Azure CLI task logs into Azure (using az login) on each invocation of anAzure CLI task, rather than re-using an existing login from a previous Azure CLI Task. Is there anyway to login once in a Job and propagate/share that information with each subsequent Azure CLI task to speed things up?

## Environment
Azure Pipelines

- Agent - Hosted or Private: 
Hosted

**Comment by bishal-pdMSFT** [comment]
We do not have any plans for this enhancement.

You could try to use bash/PowerShell task run az cli commands directly to see if that works.
