### ISSUE TITLE
GithubRelease Non-deterministically Failing to Create Release

### ISSUE THREAD

**Issue by sei-eschwartz** [microsoft/azure-pipelines-tasks#14662]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug
**Enter Task Name**: GithubRelease@0

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: edmcman@gmail.com, seipharos/kaiju, #20210326.2 Create github issue templates

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: 

```
2021-03-26T13:47:05.5965930Z ##[section]Starting: Build_Kaiju ghidra91
2021-03-26T13:47:05.8825902Z ##[section]Starting: Initialize job
2021-03-26T13:47:05.8827378Z Agent name: 'Hosted Agent'
2021-03-26T13:47:05.8827797Z Agent machine name: 'fv-az129-885'
```

## Issue Description

GithubRelease is sometimes failing to make a release.  A tag is created, and a draft for the release.

Here is the draft:

![image](https://user-images.githubusercontent.com/50171988/112643141-6b92aa80-8e1a-11eb-9f56-528a8c5c65b1.png)

Here is the tag:

![image](https://user-images.githubusercontent.com/50171988/112643376-b14f7300-8e1a-11eb-815a-da8ca5e51aff.png)

Pipelines thinks the release was created successfully:

https://dev.azure.com/seipharos/kaiju/_build/results?buildId=423&view=logs&j=a014549a-c14a-51fc-73fc-58b6d15ae87d&t=f972d6ba-ced7-59df-83d0-c823e32b1fa0

### Task logs

TBD.  May not be easy because the problem is non-deterministic.

### Error logs

There is no error in the logs.

**Comment by sei-eschwartz** [comment]
Here are both successful and failing logs 
[logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6212353/logs.zip)

One interesting thing is that in `fail.log` the `browser_download_url` returned from github is `https://github.com/sei-eschwartz/kaiju/releases/download/untagged-c9e81e49199b7d215d62/ghidra_9.2.2_PUBLIC_20210326_kaiju.zip`.  In the ok log, the git tag appears instead of the `untagged-[...]` portion.

**Comment by sei-eschwartz** [comment]
Also, the release url listed in the failing log doesn't exist: https://api.github.com/repos/sei-eschwartz/kaiju/releases/40542873

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release"
}
```

Unclear if this is an azure bug or a bug in the github API.

**Comment by ihnorton** [comment]
> "message": "Not Found",

This can happen when the `gitHubConnection` is no longer authorized (#15220).  You can debug it manually with curl and reproduce, eg:

- get latest release ID: `curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/owner/repo/releases/latest
`
- change name of latest release (substitute the ID from above):

```
curl -X PATCH -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/<owner>/<repro>/releases/<release ID> -d '{"name": "NEW NAME TEST"}'

```

the second command should fail with `"message": "Not Found"`. If you add `-u <username>` and supply a valid github token, then it should succeed.

**Comment by sei-eschwartz** [comment]
@ihnorton I don't think that is the problem because the failure is non-deterministic.  An authorization problem seems like it should be deterministic :smile:
