### ISSUE TITLE
How to Update Tasks?

### ISSUE THREAD

**Issue by brunodefrancavalli** [microsoft/azure-pipelines-tasks#14669]
**Question**  
How do I update my tasks on Azure DevOps Server 2020. I cannot find these instructions anywhere. 
How do you build these tasks? I keep getting missing libraries when trying to use tsc.
Are there packages I can just apply to Azure DevOps Server 2020?

**Enter Task Name**: All tasks

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 18.170.31003.2
    
- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:  Should not matter for this question

**Comment by anatolybolshakov** [comment]
@brunodefrancavalli let me close this one at the moment since it looks resolved - but please feel free to ask any further questions.
