### ISSUE TITLE
AzureFunctionApp randomly fails to deploy the zip package

### ISSUE THREAD

**Issue by machielvisser** [microsoft/azure-pipelines-tasks#14667]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionApp   

## Environment
Azure Pipelines
Account name: Can be provided on request in a non public way.
Project: Can be provided on request in a non public way.
Build definition: Can be provided on request in a non public way.
Build number: 20210329.1
Agent: Hosted
Pool: Azure Pipelines

## Issue Description
The deploy of the zip randomly fails without a reason. This started somewhere in march, without any change in our pipeline on this aspect. We are now in the situation that almost every deployment requires 1 or more retries.

Can be provided on request in a non public way.

### Task logs
Debug logging is not possible as it is not possible to reproduce consistently.

**Comment by chshrikh** [comment]
1. Enable [system.debug](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug) with pipeline.
2. Post adding the variable into pipeline, next time when task fails, share the pipeline logs here

**Comment by machielvisser** [comment]
Hi Chaitanya, how can I share the logging without making company specific information public?

**Comment by chshrikh** [comment]
1. you can remove the PI data from logs and upload here OR
2. Create a [dev community ticket ](https://azure.microsoft.com/en-gb/support/devops/), there you can see option to share the logs privately

**Comment by machielvisser** [comment]
Hi Chaitanya, I will do 2, open een ticket in the dev community.

**Comment by AmrutaKawade** [comment]
@machielvisser can you add dev community issue link here as well?

**Comment by AmrutaKawade** [comment]
Closing this issue. since its raise on dev community
