### ISSUE TITLE
File Not Found (caching-docker.yml) - Caching Docker image

### ISSUE THREAD

**Issue by BaskaranSelvaraj** [microsoft/azure-pipelines-tasks#14672]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
   - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

## Issue Description

issue in the azure devops build pipeline - implementing the Caching Docker images. (https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images)

![image](https://user-images.githubusercontent.com/52482083/113141891-475b1300-91f8-11eb-80e2-f6c92f907dd9.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[cache issue.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6236434/cache.issue.txt)

### Error logs

Caching Docker image

Resolving key:
 - docker             [string]
 - "Linux"            [string]
 - **caching-docker.yml [file] (not found)**
**##[error]One or more errors occurred. (File not found: caching-docker.yml)**
Finishing: Caching Docker image

**Comment by ds-ms** [comment]
I don't think this has anything to do with Docker. The failure seems to be related to the Cache task.

Adding @johnterickson (Found from CODEOWNERS)

**Comment by BaskaranSelvaraj** [comment]
I figure it out the issue. we need to provide some valid physical fine from the  application source file so it will act a key for the cache task.
