### ISSUE TITLE
nodemon app.js stops execution of succeeding steps

### ISSUE THREAD

**Issue by DVGY** [microsoft/azure-pipelines-tasks#14670]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: `npm install`
                                   `npm run dev`  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Using Azure Pipelines,
    - account name: GYadav0882,
    -  team project name:  Cypress-Integration,
    -  Jobs in run #20210330.1: 

- Agent - 
- Agent name: 'Hosted Agent'
- Agent machine name: 'fv-az459-98'
- Agent running as: 'vsts

## Issue Description

![image](https://user-images.githubusercontent.com/46158826/113024205-1ea92e00-91a4-11eb-892b-fc6075495c98.png)
![image](https://user-images.githubusercontent.com/46158826/113024331-3ed8ed00-91a4-11eb-90c5-31e6161adefd.png)

I had to cancel the build in order to stop the zombie state

How can my nodejs server and still execute all the steps. I am trying to implement cypress testing

```
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: backend-api
      name: backend-api
      type: git

trigger:
- main
variables:
  uiSource: 'cra-web-app/build'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: backend-api


- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# npm run dev is stopping the azure pipeline, can't go beyong this script
- script: |
     pushd backend-api
     npm install
     npm run dev
     popd
  displayName: 'npm install and run backend in dev mode'

- checkout: self
- script: dir
  workingDirectory: '$(Agent.BuildDirectory)'
- script: | 
    pushd cra-web-app
    npm install
    npm run build
  displayName: 'npm install and build front end'  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiSource)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by EzzhevNikita** [comment]
@DVGY You need to start your backend and frontend servers as a background process.
You can do it by adding _&_ symbol at the end of the commands, it will look like this:
`npm run dev&`
`npm run build&`

**Comment by DVGY** [comment]
@EzzhevNikita Thanks

**Comment by EzzhevNikita** [comment]
Is it mean that the issue resolved for you?

**Comment by EzzhevNikita** [comment]
@DVGY  Is it still an actual issue for you or we could close that case?

**Comment by DVGY** [comment]
> @DVGY Is it still an actual issue for you or we could close that case?

Yes it solved
