### ISSUE TITLE
FileTransform json variable substitution substitutes the wrong value for numbers larger than 53 bits

### ISSUE THREAD

**Issue by tomupson** [microsoft/azure-pipelines-tasks#14686]
**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: FileTransform

## Environment
- Agent - Private
    
    - OS: Ubuntu 20.04.2

## Issue Description

When using FileTransform version 1 or 2, where the variable value is an integer greater than Javascript's Number.MAX_SAFE_INTEGER constant (2<sup>53</sup>-1), the wrong value is substituted.

For example, I am using the unsigned long value 488384686826192916 in one of my configs...

![image](https://user-images.githubusercontent.com/30987275/113510992-68ec2f80-9555-11eb-9501-f363599bb63d.png)

...and although the logs suggest the correct value is substituted...

_2021-04-03T00:37:19.1380646Z Substituting value on key ClientId with (number) value: 488384686826192916_

...the output configuration has the last two digits as 0.

![image](https://user-images.githubusercontent.com/30987275/113510659-c7b0a980-9553-11eb-8615-cb3fdbe84c3b.png)

Please let me know if any more information is required, and I will be happy to help

**Comment by AmrutaKawade** [comment]
@tomupson can you add your value in qoutes?

**Comment by tomupson** [comment]
Hi @AmrutaKawade. If I add quotes around the value in the source json (pre-substitution), it works, but only because the value is now being interpreted as a string instead of a number. This is fine for me since the json library I'm using for deserialisation supports quoted numbers, but if a number is absolutely required then this workaround is not suitable.

**Comment by tomupson** [comment]
Tested again on 2.198.0 and still an issue
