### ISSUE TITLE
CodeSignValidationInjected task on Linux/Hosted ‘bash\r’: No such file or directory\n."

### ISSUE THREAD

**Issue by swells** [microsoft/azure-pipelines-tasks#14684]
We notices this error/warning a few days ago with the `CodeSignValidationInjected` task on Linux/Hosted-ubuntu-16.04

> ‘bash\\r’: No such file or directory\n."

Not sure if this in some Windows-style "\r\n" line endings in the file `get-os-distro.sh` or something on my end, however these jobs have been running ok for a long while.  Please see below. Thank you.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  Bug

**Enter Task Name**:  CodeSignValidationInjected

## Environment
- Server - Azure Pipelines or TFS on-premises?
 
    - Server - Azure Pipelines
       - Account Name ==  sqlhelsinki
       - Team Project == aris
       - build definition name/build number ==  azdata-cli-artifacts (nightly build)  / 20210402.1

- Agent - Hosted or Private: 
    
    - Hosted ubuntu-16.04

## Issue Description
```
Installing dotnet dependencies...
Installing dotnet version 3.1.201
Tool to install: .NET Core sdk version 3.1.201.
Found version 3.1.201 in channel 3.1 for user specified version spec: 3.1.201
/usr/bin/env: ‘bash\r’: No such file or directory
Version 3.1.201 was not found in cache.
Getting URL to download .NET Core sdk version: 3.1.201.
Detecting OS platform to find correct download package for the OS.
/home/vsts/work/_tasks/CodeSignValidationInjected_8bc4f1c1-95b1-44d2-9f1a-df3e741decb9/1.149.0/node_modules/gdn-usedotnet/externals/get-os-distro.sh
Guardian experienced an unknown error during setup:
##[error]Failed while detecting machine OS platform with error: "Failed to get machine platform details. Error: /usr/bin/env: ‘bash\\r’: No such file or directory\n."
##[warning]Guardian failed to be initialized. Please email GuardianHelp@microsoft.com with either a link to this build or this task log included as an attachment. Please contact us so that we are aware of this warning in your pipeline. For more information, please see https://aka.ms/guardianhelp-0001-azdevops-initialization
Finishing: CodeSignValidationInjected
```

### Task logs

![image](https://user-images.githubusercontent.com/1356351/113437421-6a71f800-939b-11eb-9e7e-dff169473a7f.png)
[raw-logs.txt.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6250589/raw-logs.txt.zip)

### Error logs

```
Detecting OS platform to find correct download package for the OS.
/home/vsts/work/_tasks/CodeSignValidationInjected_8bc4f1c1-95b1-44d2-9f1a-df3e741decb9/1.149.0/node_modules/gdn-usedotnet/externals/get-os-distro.sh
Guardian experienced an unknown error during setup:
##[error]Failed while detecting machine OS platform with error: "Failed to get machine platform details. Error: /usr/bin/env: ‘bash\\r’: No such file or directory\n."
```

**Comment by damccorm** [comment]
Hey @swells this looks like an issue with a 3rd party task (in this case a Microsoft internal one), not an Azure DevOps first party task. Please reach out to the task owner for support
