### ISSUE TITLE
[feature] AzureResourceManagerTemplateDeployment@3 - need dry-run option (what-if)

### ISSUE THREAD

**Issue by ozbillwang** [microsoft/azure-pipelines-tasks#14690]
## Note  

feature requests

For a list:  

* AzureResourceManagerTemplateDeployment@3

## Required Information

need dry-run option (what-if) when deploy ARM template

Something like this:
```
if ${dryRun} ; then
  AZCLI="az deployment group what-if"
else
  AZCLI="az deployment group create"
fi
```
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: here  

list here (V# not needed):  

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure Pipelines
    
Not bug or issue, new feature requests only

- Agent - Hosted or Private: 
    
devops.azure.com

Not bug or issue, new feature requests only

## Issue Description

Not bug or issue, new feature requests only

I currently workaround it with `AzureCLI@2`

**Comment by ozbillwang** [comment]
Seems there is an option called `Validation only`, looks like the what-if (dry-run) feature. Let me test it.

**Comment by ozbillwang** [comment]
Another feature is missed in this task:

* workingDirectory

With that, I can nominate the working directory, where not always put the templates under root directory.

**Comment by jonsamwell** [comment]
This would be very useful

**Comment by liwilliamnz2020** [comment]
This would be quite helpful. Not sure if there's a plan to release this feature? Thanks.
