### ISSUE TITLE
In variable groups page, it should be possible to view a tabular format showing variable group and scope

### ISSUE THREAD

**Issue by lachlann562** [microsoft/azure-pipelines-tasks#14696]
I have a need to define multiple variable groups with different standard configurations:
GroupA: Var1=a, Var2=b, etc
GroupB: Var1=c, Var2=d, etc
GroupC: Var1=e, Var2=f, etc

However only 1 of these groups should be assigned to a given stage. I need a way to quickly visualize if the same "class" of variable group is linked multiple times. ie if GroupA is assigned then i don't want B or C. the current format only lets you visualize which stages a group is linked to, but i want the opposite, i need to know which groups are linked to a stage.

**Question, Bug, or Feature?**  
*Type*: Feature

## Environment
- Server - Azure Pipelines
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: dsgrandd/LNOS/LPS - Release - Latest

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

see example of conflicting variable groups
![image](https://user-images.githubusercontent.com/20322509/113773163-a4bcfb80-96f3-11eb-902e-01a902361c75.png)
![image](https://user-images.githubusercontent.com/20322509/113773193-af779080-96f3-11eb-9de0-d7fe6862f973.png)

### Task logs

N/A

## Troubleshooting
N/A

### Error logs

N/A

**Comment by anatolybolshakov** [comment]
Hi @lachlann562 this issue is more related to Azure DevOps, but this repo is for pipeline tasks - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?
It would be great also if you could leave link here to created ticket.
Let me close this issue here since it's not related to pipeline tasks.
