### ISSUE TITLE
Certificate issue when using Kubernetes serviceconnection with Kubernetes@1 Task

### ISSUE THREAD

**Issue by vyckou** [microsoft/azure-pipelines-tasks#14700]
*Type*: Bug

**Enter Task Name**: KubernetesV1

## Environment
- Server Azure DevOps 2020
    
- Agent - Private
    
## Issue Description

Kubernetes API endpoint certificate validity issue when running any type of Kubernetes task using Kubernetes Service Connection (ServiceAccount type)

When following kubectl commands to get the json representation for the kubernetes serviceaccount secret, we need to populate the service connection.
Kubernetes serviceaccount secret json generated by kubernetes representation "data" element carry the following attributes:
* ca.crt: base64 cert
* namespace: base64 kubernetes namespace name
* service-ca.crt: base64 cert
* token: base64 serviceaccount token

When pushing generated json to Azure DevOps, in order to create the service connection, you take
* token and make it as apitoken in the service connection
* service-ca.crt and make it as serviceAccountCertificate in the service connection

then in KubernetesV1 task
https://github.com/microsoft/azure-pipelines-tasks/blob/22489b4622ec725fbc3fc90f1f0ead3c494244c3/Tasks/KubernetesV1/src/clusters/generickubernetescluster.ts#L13. you are using kubectlutility.ts to create the kubeconfig dynamically
https://github.com/microsoft/azure-pipelines-tasks/blob/22489b4622ec725fbc3fc90f1f0ead3c494244c3/common-npm-packages/kubernetes-common-v2/kubectlutility.ts#L65

while forming 'certificate-authority-data' kubeconfig element you are taking 'serviceAccountCertificate', which ends up to be the service-ca.crt from the serviceAccount secret.

The problem is, that service-ca.crt not necessary carries the public certificate for the external Kubernetes API endpoint and by default it has the internal kubernetes public certificate. 

In our particular case, we are running Openshift and we have asked for an explanation regarding this  service-ca.crt element in ServiceAccount secretmap from RHEL that

>the secrets associated with the serviceaccount is primary meant to
 be used to communicate with the api on the internal side, api-int, and not to be used from the outside

For now, as a duktape workaround we are passing `--certificate-authority` additional argument in every single kubernetes task occurrence, to rewrite invalid certificate derived from service-ca.crt 

Maybe it would be possible to override the behaviour either in kubernetes task or make the kubernetes service connection certificate not hardcoded from service-ca.crt

**Comment by shigupt202** [comment]
@vyckou Did you try using Kubeconfig approach to create service connection, instead of service account? You can configure your kubeconfig with all the correct certificates and use it without having to pass it manually for each run.

**Comment by vyckou** [comment]
@shigupt202 np, later is better than never 😸 
You can choose kubeconfig, when you create the serviceConnection directly in Project settings, but if you are creating the Pipelines Environments, and want to add (create) Kubernetes resource via that path, you do not have an option to choose it as you are forced to go via serviceAccount path

**Comment by shigupt202** [comment]
That's right. It's possible only in case of service connections. 
But even if we expose an input for certificate-authority, you'd have to enter it manually in at least the login step for Kubernetes task. Instead of that, can you create a service connection with the right Kubeconfig and give that as an input to `kubernetesServiceEndpoint` in the same task? (So instead of relying on the connection provided by the environment, we'll be explicitly giving the right connection to the task) Let me know if this works for your scenario.

**Comment by vyckou** [comment]
Technically it is possible, but in such a scenario, if I am using environments - it gets disjointed, as the environment loses coupling with service connection

What comes to my mind is to make 
https://github.com/microsoft/azure-pipelines-tasks/blob/6a642b5be3cdee15bad13ea06d65f1397d0e3b00/Tasks/Common/utility-common-v2/kubectlutility.ts#L54
`"certificate-authority-data"` JSON field and
https://github.com/microsoft/azure-pipelines-tasks/blob/6a642b5be3cdee15bad13ea06d65f1397d0e3b00/Tasks/Common/utility-common-v2/kubectlutility.ts#L59

optional (it could be even true by default), as if it won't be populated, task (kubectl) would rely on the certificates, which are on the task running agent.
I do understand that in some scenarios it is working, but you cannot rely on that "certificate-authority-data" field always to get required certificates in place for K8s API

**Comment by shigupt202** [comment]
But I don't think it would be right to assume that the agent contains the certificates in all the scenarios. Service connections are meant to provide all kind of information required to communicate with an external entity, and that's why tasks are depending on them to extract all the information. If we assume that some parts of the kubeconfig will be fetched from the agent, it'll break a lot of existing pipelines.

**Comment by shigupt202** [comment]
Closing stale issue. Feel free to reopen if you have any more questions.
