### ISSUE TITLE
DownloadBuildArtifacts : Missing log : Downloading artifact ArtifactName from: ArtifactPath

### ISSUE THREAD

**Issue by rahulroy9202** [microsoft/azure-pipelines-tasks#14704]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadBuildArtifacts

## Issue Description

Task  Download Build Artifacts changed from Version : 0.178.0 to Version : 0.183.0 and removed a log line which was very helpful,

Version : 0.178.0
Downloading artifact ArtifactName from: ArtifactPath
![image](https://user-images.githubusercontent.com/3462467/114038993-fbffcf00-989f-11eb-9e02-bc114334e2c9.png)

Please refer to this comment
https://github.com/microsoft/azure-pipelines-tasks/commit/44e3baa329bf1e3e43e83e0dd1d4d25260ac57fd#r49266265

Line: console.log(tl.loc("DownloadArtifacts", artifact.name, artifactLocation));

After update to version : 0.183.0 this line is missing
It skips this line and goes to Downloading file X to Y

**Comment by rahulroy9202** [comment]
Hi @anatolybolshakov, when can I expect this to be deployed to Azure Devops/Pipelines. 
Is there anything I need to update on my end?

My environment is 
- Server - Azure Pipelines
- Agents - Private

Thank You

**Comment by EzzhevNikita** [comment]
Hi @rahulroy9202, these changes will be deployed during the next sprint which starts in two weeks. Deployment of the changes to all organizations usually takes about three weeks (until 17 of May). Tasks will be updated automatically, there no need to perform any additional steps from your side.

**Comment by rahulroy9202** [comment]
Hi @EzzhevNikita  I can confirm that the change has been deployed to our Project sometime last week.

**Comment by anatolybolshakov** [comment]
Closing this since changes has been already rolled out - feel free to ask any further questions.
