### ISSUE TITLE
AzurePowershell Task - Feature request addSpnToEnvironment functionality

### ISSUE THREAD

**Issue by NathanPrado** [microsoft/azure-pipelines-tasks#14717]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzurePowershell

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Private, Windows

## Issue Description
Is there any plan to add similar functionality to the `addSpnToEnvironment` input that is exposed by the `AzureCli` task for the `AzurePowershell` task?  Retrieving the Service Connection details would be beneficial in some cases for powershell scripts.

**Comment by michaelelleby** [comment]
This would be very much appreciated, because this would allow us to run the Terraform CLI inside Azure PowerShell tasks.
Terraform CLI requires either specified credentials or Azure CLI to authenticate with Azure and being able to login with Azure CLI inside a PowerShell script would solve this problem.

**Comment by NathanPrado** [comment]
Thanks @michaelelleby - Thank you, the workaround is OK but as you stated in previous (deleted) comments It would be nice to have consistency between tasks in order to run things like Terraform CLI in a consistent way.  The workaround requires the dev to create new ENV vars for Terraform auth, and you do not receive the current Subscription you are connected to as you would in the AzureCLI task for other script functions that might require it.  Additionally, I would have expected Azure* script tasks to provide similar functionality for consistency and not have the solution be "use another task with slightly similar functionality."  Bummed this was closed without much explanation but that's the way the pickle squirts.

**Comment by jikuja** [comment]
This really should be re-opened and re-evaluated for feature-parity with other tasks.
