### ISSUE TITLE
Add SkipDuplicate to NuGetCommand "push"

### ISSUE THREAD

**Issue by mattleibow** [microsoft/azure-pipelines-tasks#14718]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: NuGetCommand  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Even though I can do a custom push and pass in skip duplicates, this will be really nice for the push command because I am pushing to an Azure feed. I can use API keys and all that, but it will be really nice to just be able to push and skip.

**Comment by sandyarmstrong** [comment]
This would be very useful. In general these tasks should have options for every argument in the CLI.
