### ISSUE TITLE
"npm Authenticate (for task runners)" version '1' not available for classic pipelines

### ISSUE THREAD

**Issue by LodewijkSioen** [microsoft/azure-pipelines-tasks#14719]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: "npm Authenticate (for task runners)"

## Environment
- Azure Pipelines
- Private Agent (but doesn't matter for this issue)
    
## Issue Description

Issue #8672 was fixed in a new version of this task (version '1'). This version is not available for classic (non-yaml) pipelines. We are unable to move to yaml-pipelines as our code is in a subversion repository.

![afbeelding](https://user-images.githubusercontent.com/122718/114516805-09b9a980-9c3e-11eb-8cd6-15df3817c959.png)

**Comment by leviathanbadger** [comment]
Seems to me this straight-up doesn't work even when referenced from yaml:

![image](https://user-images.githubusercontent.com/3201149/127955062-a0b982b3-eb4d-47dd-ba3d-70206e2be849.png)

The task that generated that error (and yes, the service connection does exist):

![image](https://user-images.githubusercontent.com/3201149/127955157-9bc1aaa6-7efb-405b-8d24-9d9cdbafc8a8.png)
