### ISSUE TITLE
##[error]The deployment definition is invalid; TemplateLink RelativePath can only be used with api-version '2020-06-01' or later.

### ISSUE THREAD

**Issue by c4tachan** [microsoft/azure-pipelines-tasks#14724]
**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Enter Task Name**: ARM Template Deployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

## Issue Description

The relativePath property for Linked Templates is failing validation with an API error when I attempt to validate a collection of linked ARM templates in an ADO pipeline.

The exact error message is: ##[error]The deployment definition is invalid; TemplateLink RelativePath can only be used with api-version '2020-06-01' or later.

The resource code I'm attempting to deploy is as follows:
```
{
      "name": "LinkedServices",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2020-10-01",
      "properties": {
          "mode": "Incremental",
          "templateLink": {
              "relativePath": "LinkedServices/_LinkedServicesMaster.json",
              "contentVersion": "1.0.0.0"
          },
          "parameters": {
              "uriTemplate": {
                  "value": "[replace(variables('uriTemplate'), '{0}', 'LinkedServices/{0}')]"
              },
              "appName": {
                  "value": "[parameters('appName')]"
              },
              "location": {
                  "value": "[parameters('location')]"
              },
              "regionShortName": {
                  "value": "[parameters('regionShortName')]"
              },
              "environment": {
                  "value": "[variables('keyVaultEnvironment')]"
              },
              "adfName": {
                  "value": "[parameters('adfName')]"
              },
              "keyVaultName": {
                  "value": "[variables('keyvaultName')]"
              }
          }
      }
  }
```

**Comment by ngarimella** [comment]
Hitting this too.. pl provide an ETA. Thanks!

**Comment by monrax** [comment]
I have the same issue. In my case I get: `TemplateLink RelativePath can only be used with a Uri in api-version '2020-10-01' or later` and I'm using `"apiVersion": '2021-04-01'` —ETA please? Thanks

**Comment by c4tachan** [comment]
I realized that apparently there are two tickets relating to this (Including this ticket)

Here is a link to the other ticket: https://github.com/microsoft/azure-pipelines-tasks/issues/14890
