### ISSUE TITLE
ExtractFiles@1 task in Azure DevOps is failed with error 'locate executable file: 'unzip'

### ISSUE THREAD

**Issue by PavanGurram-DevOpsQA** [microsoft/azure-pipelines-tasks#14723]
Hi Team,

I have received the below error in my CI pipeline at ExtractFiles@1 task and the full error message is **"##[error]Unable to locate executable file: 'unzip'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable."**. I believe that this task should have the executable file already installed and should be able to unzip the file without having executable file installed explicitly. Please correct me if I'm wrong here as I'm new to Azure DevOps and kindly explain me the steps to resolve the issue. If I'm correct then please consider this as bug and fix it?

Please let me know for any more details from my end. Thanks.

![image](https://user-images.githubusercontent.com/36418052/114588303-705eb780-9c7e-11eb-8970-5f295b3ec2a1.png)

**Comment by anatolybolshakov** [comment]
Hi @PavanGurram-DevOpsQA ExtractFiles searches for unzip tool on agent machine - do you use self-hosted agent or ms hosted?

**Comment by EzzhevNikita** [comment]
Hi @PavanGurram-DevOpsQA, if you are using self-hosted agent, you need manually install unzip tool, since the task doesn't contain a bundled version of this tool.

**Comment by PavanGurram-DevOpsQA** [comment]
@anatolybolshakov / @EzzhevNikita  - I'm using self hosted agent so installed Unzip on it and used the task, it works fine now. Thanks for your response.
