### ISSUE TITLE
KubernetesV1 task: increase CPU count for docker container 

### ISSUE THREAD

**Issue by patotskiy** [microsoft/azure-pipelines-tasks#14731]
## Required Information

*Type*: Feature

**Enter Task Name**: KubernetesV1  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
pool: Azure Pipelines
vm-mage: ubuntu-latest

**Issue description**:
I have following configuration for task: 
   ```
 - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '${{ parameters.azKubernetes }}'
        namespace: 'my_namespace'
        command: 'run'
        arguments: >-
            --restart=Never
            --rm
            --attach
            ${{ parameters.arg_app_name }}
           --image="image_name"
```

How can I increase CPU cores count for this docker container?

**Comment by shigupt202** [comment]
You can specify the cpu count in your pod spec, or use the [limits](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands) flag in the arguments.

**Comment by patotskiy** [comment]
Hi @shigupt202 ,could you please explain how to do this?

**Comment by shigupt202** [comment]
Can you put all your arguments in a single string, in one line instead of separating them by newline? Also, if `limits` flag is deprecated, you can raise an issue on `kubectl` repo and ask their team about how to provide limits through commands. This is not something that the task can control.

**Comment by patotskiy** [comment]
@shigupt202 When I use local Kubernetes cluster (same version as on cloud), I see this property --limits, but on cloud this property doesn't present in --help output. Look like that Microsoft has own build of Kubernetes server version 1.19.7 version

**Comment by shigupt202** [comment]
The cluster you connect to are specified in your service connection. So, that cluster is owned by you. You can control the version, or maybe try with another cluster which has an old/same version of the API server.
You can also try changing the kubectl version so that it matches your local kubectl version. The task has an input for that. You can also use KubectlInstallerV0 task for this.

**Comment by patotskiy** [comment]
Version of Kubernetes Server and Kubernetes Client in cloud: 
==============================================================================
			Kubectl Client Version: v1.21.0
			Kubectl Server Version: v1.19.7
==============================================================================

Local version: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Version are same, but available commands are different. :-(

**Comment by shigupt202** [comment]
Can you please raise an issue on kubectl repo and mention this issue there? The problem seems to be out of the scope of this task.

**Comment by shigupt202** [comment]
Closing the issue. Feel free to reopen if there are any task specific concerns.
