### ISSUE TITLE
Packer V1 task fails to parse packer version since packer 1.7.1

### ISSUE THREAD

**Issue by nlighten** [microsoft/azure-pipelines-tasks#14756]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PackerBuild@1

## Environment
- Server:  Azure Pipelines
- Agent: Private, using latest ubuntu-20.04 from actions/virtual-environments 
    
## Issue Description
The latest virtual environment image uses packer 1.7.1 has a slightly different output logging of `packer --version` which is parsed incorrectly resulting in installation of (old) default packer version 1.2.4. See task logs.

Current workaround for us is to explicitly set `packerVersion` to `1.7.1`.

### Task logs
Output for packer version 1.7.0 where version is correctly parsed:

```
/usr/local/bin/packer --version
1.7.0
Current installed packer version is 1.7.0.
Running packer fix command
/usr/local/bin/packer fix -validate=false /agent/_work/1/s/virtual-environments/images/linux/ubuntu2004.json
```

Output for packer version 1.7.1 where version is incorrectly parsed to an empty string:

```
/usr/local/bin/packer --version
 Running in background, not using a TTY
1.7.1
Current installed packer version is .
Either packer is not installed or its version is less than 1.2.4. Version 1.2.4 will be downloaded and installed for running task.
Created staging directory for keeping packer binary and templates: /agent/_work/_temp/1618704287271.
Packer installer downloaded successfully at path: /agent/_work/_temp/1618704287271/packer.zip.
Packer extracted successfully at path: /agent/_work/_temp/1618704287271/packer/packer.
/agent/_work/_temp/1618704287271/packer/packer --version
1.2.4
Running packer fix command
/agent/_work/_temp/1618704287271/packer/packer fix -validate=false /agent/_work/1/s/virtual-environments/images/linux/ubuntu2004.json
```

Note the new `Running in background, not using a TTY` message that may interfere with the version parsing. It was introduced in https://github.com/hashicorp/packer/commit/c3e78d2c32338e82733aa6d9820dce32a6c2fac4

**Comment by bishal-pdMSFT** [comment]
Not stale
