### ISSUE TITLE
AzureFileCopy V4 CleanTarget

### ISSUE THREAD

**Issue by jonsamwell** [microsoft/azure-pipelines-tasks#14759]
AzureFileCopyV4 - https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFileCopyV4/README.md

The readme says that the target folder can be cleaned but there is no option for this on the devops UI when the destination type is an AzureBlob?  With AzCopy V10 files can be synced with a target to remove old files.  It would be great to be able to do this to avoid old resources persisting in storage

## Environment
- Server - Azure Pipelines
- Agent - Hosted

**Comment by deadlydog** [comment]
I would still love to see this implemented; would be great for Azure DevOps users. I guess the alternative is not use this task and manually run the AZ CLI in the pipeline instead...

**Comment by deadlydog** [comment]
Bump, in the hopes that this extension is still maintained.

**Comment by deadlydog** [comment]
Bump, as this would still be a great feature to have.
