### ISSUE TITLE
FileTransform json using variables in groups

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-tasks#14754]
Question/Bug?

FileTransform@1

## Environment
- Server - Azure Pipelines  
- Agent - Hosted  

## Issue Description

I am using the FileTransform task to replace a chunk of json from variable groups however when I substitute an array of values the transform seems to be escaping the string.

For instance when replace the value of "ReRoutes" in 

```
"ReRoutes": [
    {
      "DownstreamPathTemplate": "/identity",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "127.0.0.1",
          "Port": 8001
        }
      ],
      "UpstreamPathTemplate": "/identity",
      "UpstreamHttpMethod": ["Get"],
      "DangerousAcceptAnyServerCertificateValidator": true
    },
    {
      "DownstreamPathTemplate": "/apps/{app}/index.html",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "127.0.0.1",
          "Port": 8003
        }
      ],
      "UpstreamPathTemplate": "/{app}",
      "UpstreamHttpMethod": ["Get"]
    },
   
  ],
```

I get the following (note the \ and have snipped the result)

`"ReRoutes": "[     {       \"DownstreamPathTemplate\": \"/identity\",       \"DownstreamScheme\": \"https\",     `

I am using variable groups assigned to the pipeline stage.

**Comment by AmrutaKawade** [comment]
@greengumby are you assigning json value to `ReReoutes`?

**Comment by greengumby** [comment]
Yes @AmrutaKawade you can see from above it definitely is replacing the right element.

**Comment by greengumby** [comment]
I think the problem is due to the Json.Parse as the array does not conform?

**Comment by greengumby** [comment]
Sorted.. json did not actually conform to standard..
