### ISSUE TITLE
Build Xamarin.Forms iOS app with F# 5?

### ISSUE THREAD

**Issue by gaelian** [microsoft/azure-pipelines-tasks#14753]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: XamariniOS

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

I have a Xamarin.Forms app that I'm trying to build with an Azure DevOps pipeline. The app uses the Fabulous F# MVU framework for Xamarin.Forms and therefore needs F#.

The Android version of the app compiles fine, both locally and in the pipeline where I am able to use the "windows-2019" agent specification.

The iOS version of the app compiles fine locally where I am using Visual Studio 2019 and F# 5, but the build fails in the pipeline, complaining about a number of F# syntax errors. I think the reason for this is that the hosted Mac build agent (I've tried both macOS-10.14 and macOS-10.15) that I am using to build the iOS version of the app is compiling against F# 4.5 and not F# 5. I can see this output in the pipeline build log:

`Microsoft (R) F# Compiler version 10.2.3 for F# 4.5`

A sample syntax error would be:

`error FS1160: This token is reserved for future use`

The reserved token referred to is the `$` character being used to denote string interpolation in my source code. [I gather this language feature was added in F# 5](https://devblogs.microsoft.com/dotnet/f-5-update-for-august/#string-interpolation).

I have tried adding the "Use .NET Core" task to try and set the use of .NET 5.x, but the subsequent "Xamarin.iOS" build task does not seem to pick up on this.

I would prefer to keep using a hosted agent if I can. Is it possible to get the XamariniOS build task to use F# 5?

**Comment by maxim-lobanov** [comment]
@andy-mishechkin , Hosted macOS 10.15 images contain two versions of F#
1) Mono F#
```
$ which fsharpc
/Library/Frameworks/Mono.framework/Versions/Current/Commands/fsharpc
$ fsharpc --version
Microsoft (R) F# Compiler version 11.0.0.0 for F# 5.0
```
2) .NET F#
```bash
$ dotnet fsi
Microsoft (R) F# Compiler version 11.3.2.0 for F# 5.0
```

I am not sure how exactly XamarinIOS task works and why it still refers F# 4.5

**Comment by andy-mishechkin** [comment]
@gaelian,
would you please provide link to you pipeline definition or some logs, where you've got this error on macOS agent
Thank you

**Comment by gaelian** [comment]
Thanks for confirming what's installed on the MacOS 10.15 image. This got me looking further back in the pipeline and I noticed there was a script included (for only historical reasons now, from when we were using the MacOS 10.14 image with an older version of the app) that set the Xamarin SDK to version 6.8.0. Disabling this script allowed the default Xamarin SDK version (currently 6.12.7) on the MacOS 10.15 image to take over, and this seems to solve my F# version problem.

**Comment by andy-mishechkin** [comment]
Thank you for confirmation, @gaelian
I think we can close this ticket. If you'll impact with this issues again - feel free to reopen.
