### ISSUE TITLE
Add support for kubectl diff

### ISSUE THREAD

**Issue by johnmckenna** [microsoft/azure-pipelines-tasks#14768]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Kubernetes

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
 Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
    - task: Kubernetes@1
      displayName: kubectl diff server side
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: ${{ parameters.service_connection }}
        azureResourceGroup: ${{ parameters.rg }}
        kubernetesCluster: ${{ parameters.akscluster }}
        command: diff
        arguments: -f $(bake.manifestsBundle) --server-side=true

This task doesn't currently support the diff command and I was wondering if this could be added?  Thank you.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ds-ms** [comment]
The command section of the task is flexible, we added a generic handler for all the other commands (i.e. the ones not listed in task.json). 
Add the exact snippet of pipeline.yaml you added to the description; it'll work out for you.

**Comment by johnmckenna** [comment]
@ds-ms  thank you for your reply, I'm having trouble with this and kubelogin and was wondering if you could help, here's what I have:

    - task: AzureCLI@2
      displayName: Connect to AKS
      inputs:
        azureSubscription: ${{ parameters.service_connection }}
        scriptType: bash
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: |
          export KUBECONFIG=$(pwd)/kubeconfig
          echo '##vso[task.setvariable variable=kubeconfig]'$(echo $KUBECONFIG)
          az aks get-credentials --name ${{ parameters.location }}-${{ parameters.sub }}-${{ parameters.environment }}-aks-01 \
          --resource-group  ${{ parameters.location }}-${{ parameters.sub }}-${{ parameters.environment }}-aks-rg-01 --file $KUBECONFIG
          kubelogin convert-kubeconfig -l azurecli
    - task: Kubernetes@1
      displayName: kubectl diff client side
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: ${{ parameters.service_connection }}
        azureResourceGroup: ${{ parameters.location }}-${{ parameters.sub }}-${{ parameters.environment }}-aks-rg-01
        kubernetesCluster: ${{ parameters.location }}-${{ parameters.sub }}-${{ parameters.environment }}-aks-01
        command: diff
        arguments: -f $(bake.manifestsBundle)

But I get the error

##[error]Cannot download access profile/kube config file for the cluster....

Does this task work with kubelogin?  https://github.com/Azure/kubelogin

Thank you.

**Comment by johnmckenna** [comment]
@ds-ms  I have tested this, but I get the following error -o json is not suppoted for kubectl diff:

==============================================================================
Task         : Kubectl
Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
Version      : 1.181.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-kubectl-tsg
==============================================================================
Prepending PATH environment variable with directory: /usr/bin
==============================================================================
			Kubectl Client Version: v1.21.0
	Kubectl Server Version: Could not find kubectl server version
==============================================================================
/usr/bin/kubectl diff -f /agent/_work/_temp/baked-template-0fdd8515-bb68-4382-b5bb-77d54a32f330.yaml -o json
Error: unknown shorthand flag: 'o' in -o
See 'kubectl diff --help' for usage.
##[error]Error: unknown shorthand flag: 'o' in -o
##[error]See 'kubectl diff --help' for usage.

**Comment by johnmckenna** [comment]
@ds-ms I think adding diff to this line would work, is that right?  Thanks

https://github.com/microsoft/azure-pipelines-tasks/blob/c345a936435f9f21eb81f39065999f56322a67bd/Tasks/KubernetesV1/src/kubernetescommand.ts#L95

**Comment by johnmckenna** [comment]
I added a PR for this one, can someone help to review, please?  Sorry, I didn't seem to have permissions to add reviewers or set the label as mentioned in the https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md
I converted it to a draft to see if I could make changes, but I couldn't and now can't change it back from draft either, thanks!
