### ISSUE TITLE
Always getting "There was a concurrency exception." on first try of deploy

### ISSUE THREAD

**Issue by tomkuijsten** [microsoft/azure-pipelines-tasks#14766]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeploymentV3  

## Environment
- Server - Azure Pipelines
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account name: Longskip
Team project name: Longship
BuildId=2312

- Agent - Hosted
- If using Hosted agent, provide agent queue name: Azure Pipelines/Hosted Agent, vmImage:windows-latest

## Issue Description

Almost any time I do a deployment, the first try fails with a message (from azure portal) {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"There was a concurrency exception. Please try again."}]}

Second time almost always works.

### Task logs

Don't have the detailed logs yet, what I do have:

Starting Deployment.
Deployment name is azuredeploy-20210421-201459-eb6c
There were errors in your deployment. Error code: DeploymentFailed.
##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
##[error]Details:
##[error]undefined: There was a concurrency exception. Please try again.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
Finishing: Deploy resources

If you need more details, let me know.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
There was a concurrency exception. Please try again.

**Comment by tomkuijsten** [comment]
Anyone?

**Comment by NinadKavimandan** [comment]
Hi @tomkuijsten, apologies for the delayed response. Is this happening for only the first pipeline runs? Does the deployment succeed in subsequent runs? Is this observed when you deploy using az cli as well?

**Comment by tomkuijsten** [comment]
It always fails the first run, it always succeeds in the second. It's like this for weeks now, with multiple of our pipelines.

**Comment by NinadKavimandan** [comment]
Deploying with az cli will help us narrow down if the problem is with ARM deployment call or the task.

**Comment by tomkuijsten** [comment]
Ok, I'll test is asap.

**Comment by tomkuijsten** [comment]
Same result using CLI.

First time:

```
Deployment failed. Correlation ID: 3de85972-1365-46b8-80ac-47ca0ddc4b11. {
  "Code": "Conflict",
  "Message": "There was a concurrency exception. Please try again.",
  "Target": null,
  "Details": [
    {
      "Message": "There was a concurrency exception. Please try again."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "59406",
        "MessageTemplate": "There was a concurrency exception. Please try again.",
        "Parameters": [],
        "Code": "Conflict",
        "Message": "There was a concurrency exception. Please try again."
      }
    }
  ],
  "Innererror": null
}
```

Second time:

```
{\ Finished ..
  "id": "/subscriptions/myid/resourceGroups/somerg/providers/Microsoft.Resources/deployments/azureclitest1",
  "location": null,
  "name": "azureclitest1",
  "properties": {
    "correlationId": "3cb16555-2e85-4ecb-8eb7-d4183c4aaf4d",
 ....
```

**Comment by NinadKavimandan** [comment]
So we see the same behavior on az CLI as well.
Okay, will it be possible for you to share the arm template? Are there any dependencies between the resources being deployed? Do they need to be deployed in some particular order?

**Comment by tomkuijsten** [comment]
I'm ok with sharing the ARM, but can it be done in a "private" way?

**Comment by NinadKavimandan** [comment]
sure. Share it over email - ninadkavimandan@github.com

**Comment by tomkuijsten** [comment]
@NinadKavimandan received my mail?

**Comment by tomkuijsten** [comment]
And? Any progress?

**Comment by tomkuijsten** [comment]
Well I don't think this will be resolved, but I did find something that might be the problem. We use custom hostnames with certificates, but that's been done in a different step. I think that this might be the issue, my first step will not have this custom hostname and Azure will remove the custom host binding, and that might result in the conflict. Not sure yet, but something to check if you run into the same issue as me.

**Comment by roy-uijting** [comment]
+1

**Comment by tomkuijsten** [comment]
We solved the issue. So for people who end up on this topic, the solution was indeed related to hostname binding. The problem was that during ARM template validation, somehow it wanted to detach the certificate binding for the hostnames. We solved this by not setting the hostNames and enabledHostNames explicitly.
