### ISSUE TITLE
Update AzureMysqlDeployment to support TLS 1.2

### ISSUE THREAD

**Issue by winklevos** [microsoft/azure-pipelines-tasks#14761]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureMysqlDeployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Agent - Hosted: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Hosted VS2017

## Issue Description

[Include task name(s), screenshots and any other relevant details]

AzureMysqlDeployment will not connect to MySQL server requiring TLS 1.2

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

`ERROR 9002 (28000): TLS version used does not meet minimal requirements for this server. Please use a higher TLS version and retry.`

**Comment by chshrikh** [comment]
please provide the detailed logs

**Comment by chshrikh** [comment]
@winklevos if is possible for you to share the task execution detailed logs so that we can debug this further

**Comment by chshrikh** [comment]
in case issue still persists, please feel free to reopen with debug logs
