### ISSUE TITLE
DotnetCoreCLIV2 - Should set 'DOTNET_NOLOGO' to 1

### ISSUE THREAD

**Issue by Tiberriver256** [microsoft/azure-pipelines-tasks#14765]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI

## Environment
Applies to all environments

## Issue Description

The current implementation displays the following dotnet welcome message:

```
Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.202

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
```

This message can be hidden by setting the environment variable `DOTNET_NOLOGO` to `1`.

## Why is this an issue?

1. Clutters the logs needlessly
2. Performance. My experience has been that skipping this welcome message shaves around 10 seconds off of my build time which is pretty significant.

**Comment by ddivanshu** [comment]
@Tiberriver256  pls set DOTNET_NOLOGO to 1 in your azure pipeline variables. Above message will be hidden by that.

**Comment by Tiberriver256** [comment]
I am aware I can do this manually. My request here is to do it automatically. There is no reason to have it in headless CI/CD pipelines so let's have it off by default.

**Comment by ddivanshu** [comment]
Currently since these is already a workaround available (just setting a variable in the pipeline) , we are not prioritising it as of now.
Feel free to open any other issue if you face another problem with task.
