### ISSUE TITLE
Values are not being relplaced with key using Pipeline Variables in Web.Config

### ISSUE THREAD

**Issue by Shafi263** [microsoft/azure-pipelines-tasks#14763]
Hi,

I’ve been facing issue with pipeline variables and values have not been replaced in Web.config after Web App deployment task in Azure Releases.

Please find the attached screenshots for the same.

In web.config I’ve defined variables called 1. RedisHost 2. RedisAccesskey 3. RedisAppName and all these keys needed to be replace with respective values from Pipeline variable (As I have attached pipeline variable screenshot as well).

Can you please help me to solve this problem.

Regards,
Shafi
![img1](https://user-images.githubusercontent.com/68379393/115513585-d65fc600-a2a0-11eb-9238-6430a9150d27.PNG)
![img2](https://user-images.githubusercontent.com/68379393/115513610-dbbd1080-a2a0-11eb-880f-f689cc189993.png)

**Comment by Shafi263** [comment]
Hi Team,

Any update on above issue.

Regards,
Shafi

**Comment by chshrikh** [comment]
please provide more details on pipeline like which task are getting used to replace the variable, which task is getting used for deployment

**Comment by Shafi263** [comment]
Hi,

I'm using Web app Deployment task with XML variable substitiution to update values with respective keys in Web.config file.

**Comment by chshrikh** [comment]
are you seeing this as regression or you are trying get this work first time ?

**Comment by Shafi263** [comment]
Hi,

We were using Octopu deploy previoulsy for deployment activities. Now we have moved to Azure DevOps for CI/CD pipelines.

So this is first time I'm trying to do deployment activity through ADO and this is where I got stuck.

Please help me with alternate solution to update keys with respective values as  I have shown in Screenshots.

Regards,
Shafi

**Comment by AmrutaKawade** [comment]
@Shafi263 Refer this doc https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&viewFallbackFrom=vsts&tabs=Classic#xml-transformation

**Comment by Shafi263** [comment]
@AmrutaKawade I have already used above task (File transforms and variable substitution). But still defined variables have not been replaced with respective values in XML file (Web.config)

**Comment by AmrutaKawade** [comment]
`Variable substitution takes effect only on the applicationSettings, appSettings, connectionStrings, and configSections elements of configuration files.`

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#xml-variable-substitution


[xml-variable-substitution-example](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#xml-variable-substitution-example)

**Comment by Shafi263** [comment]
then how to perform variable substitution out side above mentioned sections in configuration files. Please suggest.

**Comment by chshrikh** [comment]
@Shafi263 unfortunately as per design of task the scenario you are asking is not supported. We will track this as enhancement request

**Comment by Shafi263** [comment]
@chshrikh Thanks for the update
