### ISSUE TITLE
In DockerV2 task is it possible to get input parameters entered in Container Registry and Container repository values as output variables 

### ISSUE THREAD

**Issue by sriramdasbalaji** [microsoft/azure-pipelines-tasks#14762]
Hi,

In DockerV2 task is it possible to get input parameters entered in Container Registry and Container repository values as output variables. We would like to make use of these values in another script after this task.

Thanks

**Comment by ds-ms** [comment]
You could try extracting those values from the DockerOutput though, right? 
We expose a path to the docker task's output. You could read that file and extract that information from the script. 

If you're pushing in your previous step, you could look for the `docker push` string in the output, I'm sure it'll have the container registry and repository information
