### ISSUE TITLE
Add support for exporting existing XCArchive folder to Xcode task 

### ISSUE THREAD

**Issue by timothy-volvo** [microsoft/azure-pipelines-tasks#14771]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Xcode  

## Issue Description

I would like to be able to use the Xcode task to export/sign existing XCArchive folders. Currently the task runs xcodebuild -archive before -exportArchive

The flow is as follows, in my Build Pipeline all unit test, etc are executed and the app archived for the different configurations (QA, UAT, AppStore, etc). The Build Pipeline then publishes the XCArchives as an Artifact. This would trigger a Release Pipeline, which exports/signs the IPA and distributes it to the AppStore/AppCenter/InTune through various stages and approvals. The Release Pipeline does not have access to the source code and I don't want to make the signing info accessible to the Build Pipeline.

Looking at the code, I see two ways to resolve the issue:

1) Update the task to not archive when packageApp=true. This would break existing setups, callers would simply have to add archive to their build actions. The task would also have to pass the -archivePath flag when set and archive is passed as an action

2) Add another flag called skipArchive and make the action parameter optional. This would maintain backwards compatibility, but make the code messier and the task parameters counter-intuitive.

**Comment by timothy-volvo** [comment]
Is there any way to re-open this ticket? It is still valid and the PR is still pending review.

cc: @anatolybolshakov, @andy-mishechkin, @vladislav-ryzhov, @max-zaytsev

**Comment by timothy-volvo** [comment]
@DenisRumyantsev, thanks. Do you know who I can get to look at #14777?

**Comment by max-zaytsev** [comment]
Hi @timothy-volvo Thanks for reporting!
We are currently working on more prioritized issues, but will get back to this one as soon as we can

**Comment by Sam-Spencer** [comment]
Would like to bump this, as our team is seeing lots of issues with Azure handling `xcodebuild`, especially with the archive process described above. Would love to see some improvements to this.

**Comment by timothy-volvo** [comment]
@DenisRumyantsev, can I get the stale tag removed. the issue / pr is still valid. It just needs a review

**Comment by timothy-volvo** [comment]
@DenisRumyantsev, can I get the stale tag removed. the issue / pr is still valid. It just needs a review
