### ISSUE TITLE
Java Tool Installer task is not respecting jdkDestinationDirectory

### ISSUE THREAD

**Issue by JacekMSFT** [microsoft/azure-pipelines-tasks#14778]
## Note  
Java Tool Installer task is not respecting jdkDestinationDirectory and always creates a folder inside it with name "JAVA_HOME_8_X64_".

For a given:
steps:
- task: JavaToolInstaller@0
  displayName: 'Use openjdk'
  inputs:
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: AndroidExternalTools/OpenJDK.zip
    jdkDestinationDirectory: 'C:\Program Files\Unity\Hub\Editor\2019.4.19f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK'

task will install java in the: 
JAVA_HOME is being set to: C:\Program Files\Unity\Hub\Editor\2019.4.19f1\Editor\Data\PlaybackEngines\AndroidPlayer\**OpenJDK\JAVA_HOME_8_X64_OpenJDK_zip**
instead of OpenJDK.

I don't see any other setting. We can't use it. Please advise, we need OpenJDK.zip to be extracted in the destination folder.

**Comment by EzzhevNikita** [comment]
We have released a fix for this issue, we have added an option (Create a directory for extracting) that allows disabling extracting directory creation.
