### ISSUE TITLE
DeleteFiles fails on NetApp SnapMirror Volume with "EISDIR: illegal operation on a directory, lstat"

### ISSUE THREAD

**Issue by japj** [microsoft/azure-pipelines-tasks#14789]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DeleteFiles

## Environment
- AzureDevOps Server Dev18.M170.8
- Private Agent:
  - Windows Server 2019
  - Agent 2.175.2
  - DeleteFiles task 1.166.2

## Issue Description

Artifacts of a build that are stored on a NetApp SnapMirror Volume are not correctly deleted by the DeleteFiles task.

We store our build artifacts on a NetApp SnapMirror Volume provided by our IT department. It seems that the DeleteFiles task fails while trying to cleanup the build artifacts from this NetApp SnapMirror Volume.

### Task logs

I can provide more detailed logs to a secure location if needed.

```
...
[2021-04-29 01:59:12Z VERB NodeHandler] Entering AddInputsToEnvironment
[2021-04-29 01:59:12Z VERB NodeHandler] Setting env 'INPUT_SOURCEFOLDER' to '\\server\Archive\project\branch\version'.
[2021-04-29 01:59:12Z VERB NodeHandler] Setting env 'INPUT_CONTENTS' to '.'.
[2021-04-29 01:59:12Z VERB NodeHandler] Setting env 'INPUT_REMOVESOURCEFOLDER' to 'true'.
[2021-04-29 01:59:12Z VERB NodeHandler] Setting env 'INPUT_BUILDCLEANUP' to 'true'.
...
[2021-04-29 01:59:12Z INFO ProcessInvokerWrapper] Starting process:
[2021-04-29 01:59:12Z INFO ProcessInvokerWrapper]   File name: 'C:\agent03\externals\node\bin\node.exe'
[2021-04-29 01:59:12Z INFO ProcessInvokerWrapper]   Arguments: '"C:\agent03\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.166.2\deletefiles.js"'
...
[2021-04-29 01:59:12Z VERB JobServerQueue] Enqueue web console line queue: ##[error]Unhandled: Failed find: EISDIR: illegal operation on a directory, lstat '\\server\Archive\project\branch'
...
[2021-04-29 01:59:12Z INFO StepsRunner] Step result: Failed
...
```

### Error logs
(edited this after some more testing, it seems to fail on all node versions tested. however it also has a chance at success it seems)

It seems the "find" function in tasks.js does a fs.realPathSync, so I did some manual tests with the node/node10/node14 versions from the agent external folder.

It seems the problem can be reproduced on node/node10/node14 binaries directly by calling 'fs.realPathSync' on the (SnapMirror Volume) input sourcefolder:

```js
> fs.realpathSync("\\\\server\\Archive\\project\\branch\\version")
Error: EISDIR: illegal operation on a directory, lstat '\\server\Archive\project\branch'
    at Error (native)
    at Object.fs.lstatSync (fs.js:1003:11)
    at Object.realpathSync (fs.js:1684:21)
    at repl:1:4
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```

If I run this on a parent folder (without SnapMirror Volume) on node/node10/node14 it seems to works ok:

```js
> fs.realpathSync("\\\\server\\Archive\\project")
'\\\\server\\Archive\\project'
```

It seems when I run this some more then there is actually a chance it will succeed too:
```js
C:\agent03\externals>node14\bin\node
Welcome to Node.js v14.11.0.
Type ".help" for more information.
> fs.realpathSync("\\\\server\\Archive\\project\\version")
'\\\\server\\Archive\\project\\version'
>
```

If I run this on node 14.16.0 (which we installed ourselves) it fails again with the same error

**Comment by japj** [comment]
@vladislav-ryzhov unfortunately after testing #14459 with a Windows Server 2019 agent I ran into this other issue

**Comment by japj** [comment]
it seems my initial assumption of it being tied to a certain nodejs version was not correct.
during retesting it failed on all node versions, but there is higher chance of success when re-running the `fs.realpathSync` call multiple times

**Comment by japj** [comment]
I am currently testing a workaround/fix in task.js:788 where I made the following modification:
```js
                    // get the realpath
                    var realPath_1 = fs.realpathSync(item.path);
```
to
```js
                    // get the realpath
                    var realPath_1 = "";
                    try {
                        realPath_1 = fs.realpathSync(item.path);
                    }
                    catch(err) {
                        // the initial call to fs.realpathSync can fail sometimes, retry once
                        realPath_1 = fs.realpathSync(item.path);
                    }
```

So far this seems a promising 'workaround' for the issue we are seeing (I was able to successfully delete 2 different builds)
I will test this during this weekend for verification of the normal retention mechanism and let you know the status on monday

**Comment by japj** [comment]
I can confirm this solution indeed fixed our problem

**Comment by DenisRumyantsev** [comment]
Hi @japj, we are currently investigating this issue, could you please share pipeline debug logs for the `DeleteFiles` step with the related error? You can send them to my email:  v-denisr@microsoft.com

Also, could you please try to build the latest version of the `DeleteFiles` task and upload it via the [tfx-cli](https://github.com/Microsoft/tfs-cli) tool into your AzureDevOps on-prem instance to see if the problem still actual? 

Here is an instruction on how to do this:
* create an Azure DevOps personal access token
* clone azure-pipelines-tasks repo
* Run next commands from the repo root using terminal:
  * `node make.js build --task DeleteFilesV1`
  * `npm install -g tfx-cli`
  * `tfx build tasks upload -u https://dev.azure.com/<organization> -t <token> --task_path _build/Tasks/DeleteFilesV1`

**Comment by japj** [comment]
@DenisRumyantsev I would gladly send full debug logging.

However there are some problems that prevent me from actually doing that for our existing pipeline:
- The DeleteTask is done by a job generated by the Azure DevOps Server based on retention schedule or delete action from the web ui. I have no control over its debug settings, so I cannot enable debug logging for this specific job
- Once the retention/delete action is triggered it seems the "download logs" of the build pipeline fails with "no logs to download". This is perhaps due to the logfiles being cleaned up as part of the build cleanup mechanism?

So unfortunately, I have no way to provide pipeline debug logs for this specific scenario in our existing pipelines.

Can you provide information on how to get the correct logging for this scenario in our existing pipeline? That would also help in future analysis that depend on the pipeline logging.

As an alternative, I can try to setup a separate pipeline with only a DeleteFiles task to showcase the issue outside of the build retention/deletion (but I would still like to know how to get the correct logging from our existing pipeline)

For testing the latest version of the `DeleteFiles` task, I will need to coordinate that with our IT department (due to potential production impact & security rights).

Note: we also expect to do testing with AzureDevOps Server 2020 Update 1 soon. Do you know if that contains the most recent version of the `DeleteTask`?

**Comment by japj** [comment]
@DenisRumyantsev please also note that I have a pullrequest for the azure-pipelines-task-lib that provides a fix/workaround of the issue. We have not seen any problems since deploying this fix locally (in the agent task cache on disk)

**Comment by DenisRumyantsev** [comment]
Hi @japj, we implemented retry logic for UNC-paths, now it awaits deployment.

**Comment by DenisRumyantsev** [comment]
@japj let me close this issue since the provided fix was deployed.
