### ISSUE TITLE
code for run this task condition

### ISSUE THREAD

**Issue by gotjaytoday** [microsoft/azure-pipelines-tasks#14780]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: PowerShell  

Is there a source code for 'Run this task condition'?

![image](https://user-images.githubusercontent.com/50682009/116159138-90da3900-a6a4-11eb-9126-29812d927120.png)

**Comment by andy-mishechkin** [comment]
Hello, @chshrikh
As far, as I understood - you try to add PowerShell task in classic editor.
"Run this task" this is a feature of Azure DevOps, not of PowerShell task. 
We have no access to Azure DevOps source code.

Thank you.
