### ISSUE TITLE
UseDotNet@2 task failed on 503, didn't retry appropriately

### ISSUE THREAD

**Issue by aaronla-ms** [microsoft/azure-pipelines-tasks#14793]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: unsure
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: unsure

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: unsure

    - If using private agent, provide the OS of the machine running the agent and the agent version: unsure

## Issue Description

UseDotNet@2 failed with a status code 503, after only 4 seconds. This task should be tolerant of brief transient downtime in all CDNs and other networking tasks.

Expected behavior: in transient error conditions, such as any 5xx error, 429, and so on, the installation script should perform appropriate retries with an appropriate level of backoff. Task completes successfully, but possibly taking a longer period of time than normal.

Actual behavior: task failed abruptly after only 4s of execution time.

E.g. for a 5xx error, would expect at least 2 retries with a fairly long backoff (30s, 60s). This should ensure that (a) it doesn't overload a service which is experiencing unexpected load spikes, and (b) give time for any failover to occur, improving the changes that the retry succeeds.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
Link to build: https://msazure.visualstudio.com/One/_build/results?buildId=42027812&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=fe5e975f-87c0-56a2-c70a-b252ebc107f3

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
Starting: 💻 Installing DotNetSdk (windows_build_container)
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.184.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Found version 3.1.407 in channel 3.1 for user specified version spec: 3.1.407
Getting URL to download .NET Core sdk version: 3.1.407.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'C:\__w\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.184.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Version 3.1.407 was not found in cache.
Downloading: https://download.visualstudio.microsoft.com/download/pr/095412cb-5d87-4049-9659-35d917835355/a889375c044572335acef05b19473f60/dotnet-sdk-3.1.407-win-x64.zip
##[error]Failed while installing version: 3.1.407 at path: C:\__t/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/095412cb-5d87-4049-9659-35d917835355/a889375c044572335acef05b19473f60/dotnet-sdk-3.1.407-win-x64.zip Error: Error: Unexpected HTTP response: 503
Finishing: 💻 Installing DotNetSdk (windows_build_container)
```

**Comment by ddivanshu** [comment]
@aaronla-ms This download url is of microsoft.com and should be pretty stable.Although we are retrying it 2 times , could you pls tell how frequently you are getting this issue.

**Comment by aaronla-ms** [comment]
@ddivanshu I believe we've seen it twice. The second time I hit it, we retried the job less than 5 minutes later and it worked. 

What's the delay you have between the 3 attempts? One common failure mode is for a networking stack to be reset -- all requests for a short (e.g. 1 second) interval just fail immediately. If you don't have backoff between your retries, that can cause all 3 attempts to get immediately exhausted, resulting in this sort of bug.

My general recommendation for folks writing web services is 5 attempts with exponential backoff between them, trying for a better part of a minute. This avoids a number of common failure modes. E.g. delay after first attempt: 1 second. Delay after second: 3 seconds. Delay after third: 10 seconds. Delay after fourth attempt: 30.

**Comment by ddivanshu** [comment]
@aaronla-ms Exponential backoff is definitely a good approach but since this issue is not reported much times, wont be taking this on priority.
Closing this as of now.Feel free to open if you experience this much frequently.
