### ISSUE TITLE
DotNetCoreCLIV2: invoke patch code coverage API call after coverage attachment upload

### ISSUE THREAD

**Issue by ganesp** [microsoft/azure-pipelines-tasks#14808]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLIV2

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
 Azure Pipelines

- Agent - Hosted or Private: 
  Not applicable

## Issue Description

The test command of this task has an option to collect code coverage. The task also publishes this code coverage data (attachments) to the AzureDevOps pipeline run. AzureDevOps pipelines support coverage merge/summary update which can be invoked while build is in progress, by calling PATCH code coverage API. This is helpful for customers using [Build Quality Checks](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md) task in the pipeline, as they can apply coverage policies/thresholds. 

Without the PATCH coverage API call from DotNetCoreCLIV2 task -- code coverage summary information is not available until the end of the pipeline run. In this case, Build Quality Checks task times out waiting for the coverage data.

To mitigate this problem, we disabled a feature flag (responsible for deciding the storage option in test service) so that the old attachment storage is used for uploading attachments. That flow supports triggering of coverage merge on attachment upload. And therefore PATCH coverage call is not needed. 

However, there are performance issues with that old attachment storage. 
Therefore, the right solution to this problem is to invoke PATCH code coverage call from DotNetCoreCLIV2 task (and enable back the latest storage option in test service)

## Proposal:
Call PATCH code coverage API (in Test Service) after attachments are published:
https://github.com/microsoft/azure-pipelines-tasks/blob/ea2446c1cd946fdba8bd7b416c48f5eafa9aa061/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L192 

### Task logs
Not applicable

## Troubleshooting
Not applicable

### Error logs
Not applicable

**Comment by ganesp** [comment]
@bishal-pdMSFT 
We are going to add this small change in the DotNetCoreCLIV2 task -- to add call to the PATCH code coverage API.
Please see the issue description on why we are doing this change and let me know if you have any feedback / concerns on the proposal.

//cc: @nadesu , @ankit-arora12

**Comment by bishal-pdMSFT** [comment]
@ganesp looks good to me considering that this change does not have impact outside test command. Is that correct assumption?

@tejasd1990 do you want to take a quick look as well?

**Comment by ganesp** [comment]
@bishal-pdMSFT Yes, no impact outside test command.

**Comment by hannahchan** [comment]
Can this issue be reopened? I think it's also incorrectly been marked as a feature.

**Comment by ricardoschroeder** [comment]
Could this also be a solution for this issue? https://github.com/microsoft/azure-pipelines-tasks/issues/14640
