### ISSUE TITLE
AzureFunctionAppV1 SAS token expires after 1 year, resulting in 503 response

### ISSUE THREAD

**Issue by mikemonteith** [microsoft/azure-pipelines-tasks#14837]
## Required Information

**Question, Bug, or Feature?**  
Question / Bug

**Enter Task Name**: AzureFunctionAppV1

## Issue Description

When using the AzureFunctionAppV1 task, a SAS token is generated with a 1 year expiry. This means that after 1 year, the function stops working (returning 503 response).
This functionality should at least be documented, or changed so that the sas token doesn't expire.

See code here: https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFunctionAppV1/deploymentProvider/ConsumptionWebAppDeploymentProvider.ts#L90

**Comment by TroyWitthoeft** [comment]
Can we either re-open this issue, or link to the solution, please? 

When the SAS token expires after one year, the function app can't communicate with Azure Storage account and critically fails in a silent way, and it's tough to diagnose.   

I'm listing symptoms here as it might help others.  

This function app url erroring with a 503 = `The service is unavailable.`
![image](https://user-images.githubusercontent.com/1102958/152362940-05152bc0-7b95-48af-9e42-de93d456ce2e.png)

You may also see the Azure portal function app listing the `Azure Functions runtime is unreachable`
![image](https://user-images.githubusercontent.com/1102958/152361038-cdfb9497-9227-4d9b-bf4f-94405943969f.png)

If you see this, check your function app configuration settings and look for the `WEBSITE_RUN_FROM_PACKAGE` value.  
It should have a url to the blob storage holding your function code / zip deploy.  

Example: `https://myfunctionappstorage.blob.core.windows.net/azure-pipelines-deploy/package_1611079499638.zip?st=2021-01-19T18%3A00%3A06Z&se=2022-01-19T18%3A05%3A06Z&sp=r&sv=2016-05-31&sr=b&sig=XXX[MySig]XXXX`

This url has the path to your zip deploy on the blob storage and a hardcoded end date for the SAS token set by the `se` or `signedExpiry` query parameter.  If the current date is after that, your function app will be unable to retrieve it's code from blob storage.

Browsing to that url (attempting to retrieve the zip file from blob storage) results in a 403 Unauthorized

`<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:6e651f4b-801e-005d-060c-19a4f7000000 Time:2022-02-03T14:41:39.6788649Z</Message>
<AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Tue, 19 Jan 2021 18:00:06 GMT] - Expiry [Wed, 19 Jan 2022 18:05:06 GMT] - Current [Thu, 03 Feb 2022 14:41:39 GMT]</AuthenticationErrorDetail>
</Error>`

![image](https://user-images.githubusercontent.com/1102958/152365226-193bef49-fc7d-41ed-9c0c-455f05b1a5d4.png)

The error message from blob storage calls out the expired signature.  

This just bit us on several microservices deployed to production.  MS support TrackingID#2201270040004924/#220124-04395

From what I can see in Azure DevOps, this task doesn't seem to have the option of setting an expiry date further into the future than one year?  Can we get this documented somewhere when using this task?  Or, can we propose a workaround on how to fix this?

As a customer, it's not a great experience to learn we know have a one-year ticking time bomb on all function apps deployed using this method.

**Comment by bartoruiz** [comment]
> We use this task frequently, it's amazing. But, we now have to review our fleet of Azure function deployed with this task to see if we have any one year bug ticking time bombs.

Agreed, someone need to address this issue. 
We already discover the "time bombs" the hard way... on a holiday -___-
