### ISSUE TITLE
NPM Task and npm v7 authentication issue

### ISSUE THREAD

**Issue by leepowelldev** [microsoft/azure-pipelines-tasks#14845]
Type: BUG
Task Name: NPM
Environment: Azure Pipelines
Org Name: asdjh8923 (for test purposes)
Build Number: 20210514.1
Agent: Hosted

Issue:
Currently Azure is accesible via two urls for legacy reasons - 

`https://ORG_NAME.visualstudio.com/PROJECT_NAME` 

and 

`https://dev.azure.com/ORG_NAME/PROJECT_NAME`

And depending on which url you use, when you visit the Artifacts section you are given different urls to connect to the registry:

First URL:
`registry=https://ORG_NAME.pkgs.visualstudio.com/_packaging/REPO_NAME/npm/registry/`

or

Second URL:
`registry=https://pkgs.dev.azure.com/ORG_NAME/_packaging/REPO_NAME/npm/registry/`

It seems that the NPM Task currently only generates an auth token for the first url, and in npm versions prior to v7 this was not a problem as npm used to send every token to every registry. With npm version 7, however, tokens are only sent to the exact registry that they were configured for. So now the registry has no proof of identity, and rejects the request. This is made clear by a member of the npm team here: https://github.com/npm/cli/issues/2508#issuecomment-839880711

So we now have an issue where developers are using either one url to connect to the registry for local  development, but then when we come to run it in the pipeline, the npm install task is failing due to not being able to authenicate against any urls in the `package-lock.json` which use the second url.

I have given the build number/org of a test account I setup to demo the issue... as you can see in the `Npm` step the task dynamically generates this auth token:

```
Starting: Npm
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
/opt/hostedtoolcache/node/14.16.1/x64/bin/npm --version
7.13.0
/opt/hostedtoolcache/node/14.16.1/x64/bin/npm config list
; "user" config from /home/vsts/work/1/npm/30.npmrc

//asdjh8923.pkgs.visualstudio.com/_packaging/31800f2a-70d9-4bb2-92db-c6826e5e5af6/npm/registry/:_authToken = (protected) <--- AUTH TOKEN
registry = "https://asdjh8923.pkgs.visualstudio.com/_packaging/31800f2a-70d9-4bb2-92db-c6826e5e5af6/npm/registry/" 

```

However, as I was using the second url to perform my local npm install the resolved urls in the `package-lock.json` file look like:

```
"resolved": "https://pkgs.dev.azure.com/asdjh8923/_packaging/asdjh8923/npm/registry/balanced-match/-/balanced-match-1.0.2.tgz",
```
Which indicates, that for this to be able to work, the NPM task also needs to generate a second auth token for `https://pkgs.dev.azure.com/asdjh8923/_packaging/asdjh8923/npm/registry/`

Fix:
The NPM task needs to create individual authentication tokens for each url for this to work.

**Comment by zhenyanghua** [comment]
@leepowelldev How do you configure the pipeline task so that it uses npm v7? We have difficulty to suggest the agent to using npm v7.

**Comment by zhenyanghua** [comment]
you could add another step in your pipeline to run `npm i -g npm@7`
