### ISSUE TITLE
publishing maven with gradle into artifacts suddenly started erroring out

### ISSUE THREAD

**Issue by nerijusk** [microsoft/azure-pipelines-tasks#14855]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle@2

## Environment
- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Ubuntu 18.04LTS, 2.186.1

## Issue Description

Publishing Maven into artifacts with gradle task started to produce errors, while nothing in our repos changed.
```
   > Could not PUT 'https://pkgs.dev.azure.com/ORG/PROJECT/_packaging/artifacts/maven/v1/com/REDACTED/commons/6.2.0-20210519.001-35ef620/commons-6.2.0-20210519.001-35ef620.pom'. Received status code 400 from server: Bad Request - System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()    at Microsoft.VisualStudio.Services.Maven.Server.Utilities.MavenPreprocessingXDocumentLoader.Load(Stream stream) in D:\v2.0\P1\_work\26\s\Packaging\Service\Maven\Server\Utilities\Mave (DevOps Activity ID: 8E2A4D89-FE6C-4D16-B5CB-1DAD581FD872)
```

### Task logs

Task log is available upon request in private. Won't post here as it might contain sensitive information.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
   > Could not PUT 'https://pkgs.dev.azure.com/ORG/PROJECT/_packaging/artifacts/maven/v1/com/REDACTED/commons/6.2.0-20210519.001-35ef620/commons-6.2.0-20210519.001-35ef620.pom'. Received status code 400 from server: Bad Request - System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()    at Microsoft.VisualStudio.Services.Maven.Server.Utilities.MavenPreprocessingXDocumentLoader.Load(Stream stream) in D:\v2.0\P1\_work\26\s\Packaging\Service\Maven\Server\Utilities\Mave (DevOps Activity ID: 8E2A4D89-FE6C-4D16-B5CB-1DAD581FD872)
```

**Comment by nerijusk** [comment]
A similar message is produced in another pipeline that also publishes maven artifacts:
```
      > Could not PUT 'https://pkgs.dev.azure.com/ORG/PROJECT/_packaging/artifacts/maven/v1/com/REDACTED/export-document-model/6.2.0-20210519.002-c588978/export-document-model-6.2.0-20210519.002-c588978.pom'. Received status code 400 from server: Bad Request - System.Xml.XmlException: Invalid character in the given encoding. Line 1, position 1.    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)    at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)    at System.Xml.XmlTextReaderImpl.ReadData()    at System.Xml.XmlTextReaderImpl.SwitchEncoding(Encoding newEncoding)    at System.Xml.XmlTex (DevOps Activity ID: F890A7BE-7A33-40A8-B62F-3CEAD5434357)
```

Please note, that exactly the same pipeline with exactly the same code had no errors a couple of days ago.

**Comment by nerijusk** [comment]
Oh, and the funniest thing is that the artifact actually appears in artifact feed! But the pipeline cannot continue and report a success, because of that error message.

**Comment by larsduelfer** [comment]
We experience the same issues since a couple of hours now.

**Comment by nerijusk** [comment]
Issue also reported in developer community: https://developercommunity.visualstudio.com/t/Unable-to-deploy-artifacts-using-maven-w/1426117

**Comment by nerijusk** [comment]
> i guess it's fixed

yep, the report in developer community also has a number of comments about fix.
