### ISSUE TITLE
Azure DevOps CI/CD, Release pipeline deployment directly to A slot causes error on slot web page "You do not have permission to view this directory or page."

### ISSUE THREAD

**Issue by sumer9999** [microsoft/azure-pipelines-tasks#14859]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
I created Azure DevOps build and release pipeline setup.
Then the released pipeline is publishing directly into a slot
Before release setup Slot sample website works fine.
After the release setup it shows error "You do not have permission to view this directory or page."
Even after disconnecting the pipeline and deleting the code and updating again(via FTP) and restarting the slot it shows same error.

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? 
      Azure Pipeline 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    -Email ID of account is romydayego@gmail.com

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by chshrikh** [comment]
could you please share the debug logs of pipeline execution

**Comment by sumer9999** [comment]
Sure , can you please tell what's context of this, which project etc?

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by chshrikh** [comment]
@sumer9999 this in context of above  issue you filed, where you are having issue with deployment to a slot

**Comment by sumer9999** [comment]
Thanks, when it was filled?
What is resource group name?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by chshrikh** [comment]
@sumer9999 I think there is disconnect, isnt this issue filed by you ? we are looking for more details in context of this issue

**Comment by sumer9999** [comment]
Yes, because I can't backtrack with only the issue id. We have multiple accounts with multiple projects.
Having some idea about that would help me understand.
Otherwise just ignore for me now.
Thanks and regards,
Sumer

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by chshrikh** [comment]
closing this as per above comment, feel free to file a new issue with required details like task name, task version, debug pipeline logs
