### ISSUE TITLE
PublishSymbols: Wrong path to source in URL with multi git repo build pipeline

### ISSUE THREAD

**Issue by VemundH** [microsoft/azure-pipelines-tasks#14852]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishSymbols  

## Environment
- Server - Azure Pipelines
- Agent - Private:
    - VMSS - Windows Server 2019
    - Agent version 2.185.1

## Issue Description

We have a build pipeline that includes multiple Azure DevOps git repositories as documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

We are using the PublishSymbolsV2 to index and publish symbols for one of the repositories.  
The problem: The task is using Build.SourcesDirectory internally. This behaves differently in single and multi repo builds.
We are ending up with URL like this: `https://abc.visualstudio.com/<project uuid>/_apis/git/repositories/<repo uuid>/items?api_version=1.0&versionType=commit&version=<commit id>&path=/repo1/src/somepath/somefile.cpp`. This is invalid and should instead be `https://abc.visualstudio.com/<project uuid>/_apis/git/repositories/<repo uuid>/items?api_version=1.0&versionType=commit&version=<commit id>&path=/src/somepath/somefile.cpp`
 
Task is configured like this:
```
    - task: PublishSymbols@2
      inputs:
        symbolsFolder: $(srcRepoBuildRootFolder)
        searchPattern: |
          x86/Release/bin/**/*.pdb
          x64/Release/bin/**/*.pdb
          build/Intermediate/**/*.pdb
          !**/vc1??.pdb
          !**/Test.*.pdb
          !**/*TestAdapter.dll
        indexSources: true
        publishSymbols: true
        symbolServerType: TeamServices
```

**Comment by MarkKharitonov** [comment]
I was about to open the same bug. Could thing I checked first. I second this - the task does not handle multi repo checkout. This is a crucial point for us. We use multi repo checkout extensively and it is frustrating that the source code is not indexed correctly.

I see the bug is ignored for almost 2 months now. Anyone to comment?

**Comment by MarkKharitonov** [comment]
Have just submitted a PR to fix the issue. I have no idea, though, how to test a task. I did test my changes offline and they seem to be correct. An ultimate test though would be running a build and checking the published symbols.

**Comment by MarkKharitonov** [comment]
Have just submitted a PR to fix the issue. I have no idea, though, how to test a task. I did test my changes offline and they seem to be correct. An ultimate test though would be running a build and checking the published symbols.
