### ISSUE TITLE
Unable to export the solution to $Build.ArtifactStagingDirectory via Powershell

### ISSUE THREAD

**Issue by Shikha1405** [microsoft/azure-pipelines-tasks#14851]
Unable to export the solution to $Build.ArtifactStagingDirectory via Powershell

How can i achieve this?

$SolutionFilePath= $env:BUILD_ARTIFACTSDIRECTORY$solutionName
Export-CrmSolution -conn $BuildConnection -SolutionName "$solutionName" -SolutionFilePath "$SolutionFilePath" -SolutionZipFileName "$solutionName.zip"

Also tried,
$SolutionFilePath= $(Build.ArtifactStagingDirectory)\$(Solution Name).zip
Export-CrmSolution -conn $BuildConnection -SolutionName "$solutionName" -SolutionFilePath "$SolutionFilePath" -SolutionZipFileName "$solutionName.zip"

Any idea?

**Comment by anatolybolshakov** [comment]
Hi @Shikha1405 did you miss slash between $(Build.ArtifactStagingDirectory) and solution name? Does the result path looks right for you in logs?
Build.ArtifactStagingDirectory variable value does not contain slash at the end by default.

**Comment by Shikha1405** [comment]
Hi @anatolybolshakov  - i checked my logs and after putting a slash 

$SolutionFilePath1= $env:BUILD_ARTIFACTSDIRECTORY\$solutionName

It prints as \solutionName, $env:BUILD_ARTIFACTSDIRECTORY variable is blank

**Comment by anatolybolshakov** [comment]
@Shikha1405 looks like $env:BUILD_ARTIFACTSDIRECTORY is invalid variable name - it should be $env:BUILD_ARTIFACTSTAGINGDIRECTORY

**Comment by Shikha1405** [comment]
Thanks @anatolybolshakov , it worked..
