### ISSUE TITLE
Add support for buiding Xamarin.Android via solution file

### ISSUE THREAD

**Issue by GalaxiaGuy** [microsoft/azure-pipelines-tasks#14862]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: XamarinAndroid

## Issue Description

`XamariniOSV2` supports building via a solution file. `XamarinAndroidV1` only supports building via a project file. This is a problem if the build depends on the solution (for example by using configuration mapping).

**Comment by anatolybolshakov** [comment]
Hi @GalaxiaGuy sorry for the delay - we are working on more prioritized issues at the moment, but will get back to this request once be able to.
