### ISSUE TITLE
CopyFile fails when dealing with files containing `[]`

### ISSUE THREAD

**Issue by Gimly** [microsoft/azure-pipelines-tasks#14876]
*Type*: Bug
**Enter Task Name**:  CopyFiles

## Environment

- Server: Azure Pipelines
   - Account name: gimly81
     Team project name: Test Project
     Build definition: Test Project
     Build number: 20210525.1

- Agent: Hosted
    - Agent queue name: ubuntu-latest

## Issue Description

When trying to copy files that contain square brackets (`[ ]`), we're experiencing a weird issue where the `CopyFile` task v. 2.186.1 fails with the error `Failed cp: cp: dest is not a directory (too many sources)`.

I could create a minimal reproduction of the issue by creating a folder with the three following files and use the CopyFile task to copy them in another folder.

* Test10.txt
* Test20.txt
* Test[12]0.txt

We have a combination of similar files in a project which was working fine with the version 2.184.0 of the task. It's a relatively recent change that made that issue appear.

My guess is that the file name `Test[12]0.txt` is used somewhere and considered as a regex which makes the `cp` command try to copy twice the same file.

I have created a public project that showcase a minimal reproduction of the issue:
https://gimly81.visualstudio.com/Test%20Project/_build/results?buildId=23&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=944b7e9c-00d2-5ab3-4f94-8de8fe321ef4

### Task logs

```
Starting: CopyFiles
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.186.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
found 3 files
cp: dest is not a directory (too many sources)
Copying /home/vsts/work/1/s/Demo/Test10.txt to /home/vsts/work/_temp/Test10.txt
Copying /home/vsts/work/1/s/Demo/Test20.txt to /home/vsts/work/_temp/Test20.txt
Copying /home/vsts/work/1/s/Demo/Test[12]0.txt to /home/vsts/work/_temp/Test[12]0.txt
##[error]Error: Failed cp: cp: dest is not a directory (too many sources)
Finishing: CopyFiles
```

**Comment by max-zaytsev** [comment]
Hi @Gimly, could you please rerun the build in your [test pipeline](https://gimly81.visualstudio.com/Test%20Project/_build/results?buildId=23&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=944b7e9c-00d2-5ab3-4f94-8de8fe321ef4) to see if the issue still persists? (I just tried to start the similar one and can't see the problem)

**Comment by max-zaytsev** [comment]
@Gimly, is this issue still actual for you?

**Comment by Gimly** [comment]
@max-zaytsev Sorry I hadn't seen your notification the first time. I just rerun my sample pipeline and I can gladly say that the issue is now fixed: https://gimly81.visualstudio.com/Test%20Project/_build/results?buildId=24&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=944b7e9c-00d2-5ab3-4f94-8de8fe321ef4.

Thanks!
