### ISSUE TITLE
copy files task fails when run across multiple agents

### ISSUE THREAD

**Issue by techtor** [microsoft/azure-pipelines-tasks#14892]
https://github.com/microsoft/azure-pipelines-tasks/blob/a1bfdc1cc5a04d6177fa607ced515c96b1455498/Tasks/CopyFilesV2/copyfiles.ts#L87

I've got a pipeline where I'm spreading a testing task across multiple agents. Once the testing is complete on a particular agent, we copy the results* to a share. In apparently non-deterministic fashion, we occasionally see an error when copying the files:

`2021-05-04T21:08:15.3559305Z ##[error]Error: Unable to create directory 'folderName'. EEXIST: file already exists, mkdir 'folderName'`

Is it possible to adjust the line linked above to continue if `mkdir` fails? Otherwise, I don't think we'll be able to confidently parallelize this task across multiple agents.

*Note that we have more to copy than just the pass/fail result and the associated logs. This helps us identify issues when the built-in ADO test results are insufficient for an investigation.

**Comment by anatolybolshakov** [comment]
Hi @techtor we have rolled out the fix for this issue -  there is a new input 'ignoreMakeDirErrors' added to the task - closing this at the moment, please feel free to ask any further questions.
