### ISSUE TITLE
AzureResourceManagerTemplateDeployment Needs to be updated to use the latest ARM API

### ISSUE THREAD

**Issue by c4tachan** [microsoft/azure-pipelines-tasks#14890]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment

## Environment
- Server - Azure Pipelines

- Agent - Hosted 

## Issue Description
The ARM API is out of date now.
![image](https://user-images.githubusercontent.com/2130211/119723445-7332f780-be3b-11eb-8677-2227c309220e.png)

### Task logs
N/A

### Error logs

`[error]The deployment definition is invalid; TemplateLink RelativePath can only be used with api-version '2020-06-01' or later.`

**Comment by tejasd1990** [comment]
@c4tachan,
can you share the arm template you are deploying? This looks like a template issue to me and not a task one.

**Comment by tejasd1990** [comment]
@c4tachan , ping!

**Comment by c4tachan** [comment]
sorry, I'll get you a sample template ASAP

**Comment by c4tachan** [comment]
```
"resources": [
        {
            "name": "LinkedServices",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-10-01",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    //"uri": "[replace(variables('uriTemplate'), '{0}', 'LinkedServices/_LinkedServicesMaster.json')]",
                    "relativePath": "LinkedServices/_LinkedServicesMaster.json",
                    "contentVersion": "1.0.0.0"
                },
                "parameters": {
                    "uriTemplate": {
                        "value": "[replace(variables('uriTemplate'), '{0}', 'LinkedServices/{0}')]"
                    },
                    "appName": {
                        "value": "[parameters('appName')]"
                    },
                    "location": {
                        "value": "[parameters('location')]"
                    },
                    "regionShortName": {
                        "value": "[parameters('regionShortName')]"
                    },
                    "environment": {
                        "value": "[variables('keyVaultEnvironment')]"
                    },
                    "adfName": {
                        "value": "[parameters('adfName')]"
                    },
                    "keyVaultName": {
                        "value": "[variables('keyvaultName')]"
                    }
                }
            }
        }
]
```

**Comment by c4tachan** [comment]
The problem is that we are using the new "relativePath" syntactic sugar added sometime in API 5.*

If we deploy this template using the powershell cmdlets it validates and deploys just fine as well.

**Comment by rishabhmicrosoft** [comment]
i got this resolved by using uri instead of relativePath 
"uri": "[uri(deployment().properties.templateLink.uri, 'appserviceplan.json')]",
