### ISSUE TITLE
Release Pipeline pulling DownloadBuildArtifact Task v1.188.0 | Failing 

### ISSUE THREAD

**Issue by codytipton-hpg** [microsoft/azure-pipelines-tasks#14902]
**Question, Bug, or Feature?**  
*Type*:  Question, potentially bug

**Enter Task Name**: DownloadBuildArtifact

## Environment
Azure Pipelines 

## Issue Description

![image](https://user-images.githubusercontent.com/52749096/119927512-2fc1b180-bf3f-11eb-9c58-088fc6f212c4.png)

Our release pipelines began failing today and the logs are marked by a new version of the download build artifact task, specifically v1.188.0.  Prior to today we were pulling, most recently, v0.186.3 and deploying successfully.

I'm not sure how we're picking up this version on the backend, since the task version is not configurable for Release pipelines, at least as far as I can see.

### Task logs

I'm unsure how to enable debug logging for **Release** pipelines.

### Other observations
I noticed this Open PR https://github.com/microsoft/azure-pipelines-tasks/pull/14560 defining a version 1.188.0 and suspect it may be relevant, though I'm unsure how we're pulling this (or similarly versioned) task.

**Comment by anatolybolshakov** [comment]
Hi @codytipton-hpg I can't reproduce it at the moment using yaml and release pipelines - do you still see this issue?

**Comment by codytipton-hpg** [comment]
Yes, we are still facing the issue.  I also updated the target agents (2.177.1).

When you test, is your DownloadBuildArtifacts Task for the release pulling version 1.188.0 as well?

As a note, for the associated builds producing the artifacts, we're using PublishBuildArtifacts Task v1

**Comment by codytipton-hpg** [comment]
@anatolybolshakov 

Update:  I found a workaround by using the Publish**Pipeline**Artifact Task in my builds.  Releases will thus use the DownloadPipelineArtifact task over the DownloadBuildArtifact Task, avoiding the issue.

Looking at [this issue comment](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2341#issuecomment-439483135) I see that the task is intended to replace Publish**Build**Artifacts anyway, so I will begin opening PR's to update the publish step.  Still, this does seem like breakage of functionality.  I'll defer to you for whether or not the issue should remain open.

**Comment by alex-peck** [comment]
This is caused by an out of date agent. When the new task is used, it should request your agents to automatically update. Is your system configured to block agent updates?

**Comment by codytipton-hpg** [comment]
> This is caused by an out of date agent. When the new task is used, it should request your agents to automatically update. Is your system configured to block agent updates?

At the time of the issue, updating the agent on both build server and the deployment target did not resolve.  Though I'm prepared to believe a later agent update resolves this issue, we've moved to PublishPipelineArtifact tasks and don't have a need to revert and retest PublishBuildArtifacts.
