### ISSUE TITLE
MavenAuthenticate@0 relies on NodeJS 6 which is blocked

### ISSUE THREAD

**Issue by milbrandt** [microsoft/azure-pipelines-tasks#14923]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MavenAuthenticate@0
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenAuthenticateV0

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      https://dev.azure.com/grinding/UGG/_build/results?buildId=95836

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    not relevant, but Windows Server, Agent 2.186.1
 

## Issue Description

task 'MavenAuthenticate' at version '0.177.1' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator.

![image](https://user-images.githubusercontent.com/26173245/120507171-db975100-c3c6-11eb-8046-070fd6b5a256.png)

In Azure Pipelines tasks containing NodeJS 6 execution handlers can be restricted.
![image](https://user-images.githubusercontent.com/26173245/120508024-a3dcd900-c3c7-11eb-9aaa-46f1fb062a7e.png)

### Task logs

Pipeline doesn't exen start.

### Error logs

See screenshots above.

**Comment by AnnaOpareva** [comment]
Hi @milbrandt 
We fixed this problem. Updated task version 0.194.0 will be deployed in the next 5 weeks. Feel free to ping us if you will have any problem with it.

**Comment by anatolybolshakov** [comment]
Hi @milbrandt the fix for this issue has been already rolled out - closing this at the moment. Please let us know if you have any other questions.
