### ISSUE TITLE
DotNetCoreCLI publish timeout 

### ISSUE THREAD

**Issue by ylr-research** [microsoft/azure-pipelines-tasks#14932]
I'm trying to publish a Blazor project with AOT [On] and I'm getting a timeout error. Below are the snapshots of task and result.

![image](https://user-images.githubusercontent.com/63487874/120830007-0f3fbb80-c52c-11eb-85de-8b3bf839990d.png)

![image](https://user-images.githubusercontent.com/63487874/120829869-e5869480-c52b-11eb-9cc2-8c8e9ca70f01.png)

**Comment by ylr-research** [comment]
I just increased the timeout threshold to 90 min. However, this takes to long to publish though.

**Comment by ylr-research** [comment]
Now it's not timing out but rather going out of memory

(_WasmBuildNative target) -> 
         EXEC : LLVM error : out of memory [my project's path]
         emcc : error : 'C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.12.Sdk.win-x64\6.0.0-preview.4.21220.1\tools\bin\wasm-ld.exe @C:\Users\VSSADM~1\AppData\Local\Temp\emscripten_c2hlbfgo.rsp' failed (3221225501) [my project's path]
         C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0-preview.4.21253.7\Sdk\WasmApp.targets(504,5): error MSB3073: The command "emcc "@D:\a\1\s\[my project's name]\Client\obj\Release\net6.0\wasm\emcc-link.rsp"" exited with code 1. [my project's path]

**Comment by ylr-research** [comment]
@chshrikh does the Release label means is to be fixed by Release?

**Comment by ylr-research** [comment]
Is there any update on this?

**Comment by ylr-research** [comment]
Is there any update?

**Comment by bishal-pdMSFT** [comment]
@ashwinsangem

**Comment by ashwinsangem** [comment]
@ylr-research, can you pass the complete logs with the system.debug flag on.
