### ISSUE TITLE
UseDotNet install task on Pipelines broken with msbuild.exe

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/azure-pipelines-tasks#14933]
Not sure when this started, but I’m getting errors that a .NET SDK isn’t being found (use InPrivate mode if you need, it’s a public pipeline):
https://dev.azure.com/clairernovotny/GitBuilds/_build/results?buildId=5041&view=logs&j=afbd19f9-04b8-5541-fe1c-f607ec1d72d6&t=436cf0bd-0259-53f3-c80f-06fba914ebdb
 
It’s installing a preview SDK, which I use for `dotnet publish` but there’s no global.json as you can see here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer.
 
MSBuild should just be using the stable .NET 5.0.300 SDK that ships with 16.10. Instead it’s not finding anything. The same build steps used to work.

I didn’t change anything on my end. I expect msbuild.exe to use the latest stable SDK on the box, as there’s no global.json that tells it to use preview versions. I expect dotnet publish to use the 6.0 version that I installed with the task, but it’s not getting that far.

**Comment by timheuer** [comment]
@maxim-lobanov can you help route?

**Comment by clairernovotny** [comment]
Ping? This is still happening.

**Comment by bishal-pdMSFT** [comment]
@ashwinsangem please take a look at this

**Comment by ashwinsangem** [comment]
@clairernovotny, I'm unable to access the build you mentioned to check the logs. Can you please pass me a fresh one?
