### ISSUE TITLE
DockerV2: Invalid base image name with multi-stage builds using COPY --from 

### ISSUE THREAD

**Issue by mouellet** [microsoft/azure-pipelines-tasks#14931]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerV2  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2

## Environment
- Server - Azure Pipelines
- Agent - Private

## Issue Description

Sample Dockerfile to reproduce this issue:

```
FROM golang:1.16 AS builder
...
FROM alpine:latest 
COPY --from=builder . .
```

The `COPY --from=builder` command is picked up  as `FROM` command resulting in an invalid base image name in this function:
https://github.com/microsoft/azure-pipelines-tasks/blob/14e609d787a7c29d12b4fe4cb275464dd0db5b19/common-npm-packages/docker-common-v2/containerimageutils.ts#L66

### Task logs

```
invalid reference format
```

**Comment by Oliver-Piorun** [comment]
Comments like `# Copy files from A to B` are also taken into account when trying to get the base image name. The current implementation seems to be very immature.

Greetings!

**Comment by sonic1981** [comment]
[Docker FROM seems very well defined](https://docs.docker.com/engine/reference/builder/#from). It's more than a little naive to just look for the word "from". A simple regex would fix this

**Comment by sonic1981** [comment]
Please don't close this issue. It is not fixed. I may look at providing a solution myself
