### ISSUE TITLE
What permissions are needed to use the Active Directory - password option?

### ISSUE THREAD

**Issue by michc-msft** [microsoft/azure-pipelines-tasks#14951]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure SQL Database deployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: internal account, please follow-up for these details.

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted on Azure Pipelines agents

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I am trying to enable the Active Directory-Password option on my Azure SQL Database deployment task in my release pipeline. I'm attempting to do this using an Azure AD App Registration. I am having failures in deploying, and I think it's because my AAD App doesn't have all of the permissions it needs. What permissions are needed in order for my AAD app to deploy a DACPAC to my Azure SQL Db?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by AmrutaKawade** [comment]
As discussed, try connecting to Azure SQL database with active directory password from SSMS. if you are able to connect then you should be able to connect from Task as well. for Task no additional permissions are required. 

Closing this issue.

**Comment by michc-msft** [comment]
I followed up with the SQL AAD team who confirmed the issue is not on their end. Would love support with this issue

**Comment by nadesu** [comment]
@AmrutaKawade - pls review this clarification

**Comment by AmrutaKawade** [comment]
can you pass `/Diagnostics:true` in additional arguments and run pipeline ?
it looks like auth is succeeding from your previously shared pipeline but while executing dacpac it failed

**Comment by chshrikh** [comment]
this is broader question, not exactly in context of  ADO, nothing actionable here.
