### ISSUE TITLE
Provide Java 16 build for the PreInstalled type in JavaToolInstaller

### ISSUE THREAD

**Issue by LadyCailin** [microsoft/azure-pipelines-tasks#14975]
**Question, Bug, or Feature?**  
Feature

**Enter Task Name**:  JavaToolInstaller

## Environment
Hosted

## Issue Description

JavaToolInstaller provides JDK 8 and JDK 11 by default. However, Java 16 is the latest version, and should also be supported by default, especially given that there's an [official Microsoft build of it](https://docs.microsoft.com/en-us/java/openjdk/download). Currently, in order to use JDK 16 in the build pipeline, one must host the jdk in an azure blob store, but for most people that's probably just going to be a standard build, and using one of the AdoptOpenJDK or Microsoft builds would be sufficient. This would make #14915 an easy fix as well, since it's just about getting rid of the warnings.

**Comment by anatolybolshakov** [comment]
Hi @LadyCailin this is related to JDK versions being pre-installed on hosted images and not related to the task itself - transferring this to https://github.com/actions/virtual-environments
