### ISSUE TITLE
Unexpected Behavior when linking KeyVault to Library Group Var

### ISSUE THREAD

**Issue by choukimasri** [microsoft/azure-pipelines-tasks#14971]
Hello !

We're having an issue using Variables from the Azure KeyVault Task in our powershell script.

Best Regards !

## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Task Name**: 
Azure Key Vault Task
  
## Environment
Azure Pipelines

- Agent - Hosted or Private: 
 Hosted windows-latest

## Issue Description
We created a Library Variable Group that streams our secrets from an Azure Keyvault,
AzureDevOps seems to be using this task in prejob mode to download the secrets before running following steps in the pipeline.
We're unable to access the value of any streamed secret from our KeyVault inside the next AzurePowerShell@5 task.

I tried to workaround the issue by trying:

- fetching with Get Variable (within the 2 Scopes) Failed
- $env:secret-name Failed
- $global:secret-name Failed
- using {} to fetch ${secret-name} Failed
- can't use () as $(secret-name) has hyphen and powershell can't escape it even with ` also failed
- using a='secret-name' and $b=$($a) also failed

Parameter Name | Effect | Description
-- | -- | --

RunAsPreJob | Make secrets available to whole job | (Required) Run the task before job execution begins. Exposes secrets to all tasks in the job, not just tasks that follow this one.Default value:&nbsp;false
-- | -- | --

# Expected-Behavoir
Secrets made available in following tasks

# Suggestions
- Map each secret from KeyVault to an $env:KeyVaultName.secret-name variable
- Add replace hyphens feature to task

Related to #10525 #14458

**Comment by choukimasri** [comment]
Any Updates ?

**Comment by spoelstraethan** [comment]
This issue has been mentioned before, but I didn't have time to submit a new issue, thanks for that! https://github.com/microsoft/azure-pipelines-tasks/issues/11854#issuecomment-898759584

A workaround is to run the AzureKeyVault@1 task yourself and set the `runAsPreJob` setting (available in AzureKeyVaultV1), to ensure that the task has fetched the secrets before any other steps attempt to run.


Unfortunately, it doesn't appear there is a way to force this setting on a keyvault backed variable group, and I'm not sure where the code lives that resolves the variable group values from keyvault.

**Comment by spoelstraethan** [comment]
What you may be running into is the fact that you need to map secret variables to utilize them in scripts/shell tasks, while other types of tasks might not require the explicit mapping.

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/key-vault-in-own-project?view=azure-devops&tabs=portal#query-and-use-secrets-in-your-pipeline

**Comment by choukimasri** [comment]
Yes, or inline the scripts, the objective of this issue is to solve once and for all, this problem,
in the task AzureKeyVault which is called by azure pipeline on job init, secrets must be set as env vars for scripts (this must be an option), or in subsequent calls to script tasks, the workaround to manage secrets manually in yaml is ugly and should be eventually fixed.

**Comment by spoelstraethan** [comment]
@choukimasri the AzureKeyVault secrets ARE set as environment variables, but they are set as SECRET variables, this is required so that they aren't logged or exposed.

Basically what happens in the AzureKeyVault task is they run `echo "##vso[task.setvariable $variable;isSecret=true]secretValue"` for each entry returned by the `secretFilter` supplied in the `AzureKeyVault` task (or in the case of a KeyVault backed variable group, the explicit list of secrets mapped to variables [still secret variables]).

Secret variables in Azure DevOps require explicit mapping via the `env:` block or similar in the YAML, because you wouldn't want your secrets automatically shared and visible to every future stage/job/step/script where someone could call `env` or `set` from a script and print out all the secret variables.

The two links I supplied outline the correct procedure to access these secret variables.

**Comment by choukimasri** [comment]
@spoelstraethan I don't see how's that is security related as they are mapped inline though, it's sufficient to run whatever script as inline to get them all replaced, also now the run as pre job param is now confusing as the secrets would not be mapped anyway unless explicitly specified, as it's called by Azure initially when fetching secrets, and documented to guarantee that the secrets are exposed in subsequent tasks.

**Comment by choukimasri** [comment]
@DenisRumyantsev  I'm commenting so the issue doesn't disappear in the wild, any updates ?
