### ISSUE TITLE
AzureFileCopy@4 - Incorrect content type when copy file to azure storage blob in pipeline

### ISSUE THREAD

**Issue by singara-velan** [microsoft/azure-pipelines-tasks#14970]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  AzureFileCopy@4 

## Environment
- Server - Azure Pipelines 

- Agent - Hosted
  Pool: Azure Pipelines
  Image: windows-latest
  Agent: Azure Pipelines 

## Issue Description

Using AzureFileCopy@4 to copy MS office files(docs. excel, ppt) content type been incorrectly set as "application/zip"

**Pipeline Task**
![image](https://user-images.githubusercontent.com/10954246/121838733-13798f00-cd0b-11eb-8806-fa58257e5d0a.png)

**Blob Content type**
![image](https://user-images.githubusercontent.com/10954246/121838426-643cb800-cd0a-11eb-95db-a86dae0a0101.png)
![image](https://user-images.githubusercontent.com/10954246/121838465-7dddff80-cd0a-11eb-8610-81e931f87d02.png)
![image](https://user-images.githubusercontent.com/10954246/121838507-964e1a00-cd0a-11eb-97b7-5ae9dfd52d59.png)

### Task logs
![image](https://user-images.githubusercontent.com/10954246/121838643-e331f080-cd0a-11eb-9a8e-0c31247347d7.png)

**Comment by AmrutaKawade** [comment]
Our task internally uses azcopy.exe and automatically setting content-type is feature provided by azcopy

https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy#advanced

we don not set content-type in task

**Comment by singara-velan** [comment]
> Our task internally uses azcopy.exe and automatically setting content-type is feature provided by azcopy
> 
> https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy#advanced
> 
> we don not set content-type in task

Is that means bug in azcopy itself?

Standalone azcopy in local pc, copying the file with correct content-type. When its been used with pipeline it is getting incorrect.

**Comment by v-nagarajku** [comment]
Fixed the issue with below ref:
https://github.com/microsoft/azure-pipelines-tasks/pull/15594
