### ISSUE TITLE
PublishBuildArtifacts: Not useable for single file copy

### ISSUE THREAD

**Issue by snewz** [microsoft/azure-pipelines-tasks#14984]
*Type*: Bug

## Environment

Azure DevOps Server version: Azure DevOps Server 2020 Update 1
PublishBuildArtifacts version: 1.158.3
Agent version: 2.187.2

## Issue Description

The help text of "Path to publish" in PublishBuildArtifacts task says: "The folder or file path to publish."

**Actual:** When specifying a single file in PublishBuildArtifacts all other subdirectories in source location are copied to destination.
**Expected:** Only the specified file is copied to destination.

**Steps to reproduce:**
1. Create a task:
![image](https://user-images.githubusercontent.com/1443173/122713995-e119e580-d266-11eb-9b14-2a7fe83c9e52.png)
2. Run the build

### Task logs

```log
==============================================================================
Task         : Publish build artifacts
Description  : Publish build artifacts to Azure Pipelines or a Windows file share
Version      : 1.158.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
robocopy.exe /E /COPY:DA /NP /R:3 "d:\SoDox\Project\0.0.0.1\latex" "\\SomeServer\Doxygen\ProjName\BuildNumber\API-Documentation.pdf" "refman.pdf"

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows                              
-------------------------------------------------------------------------------

  Started : Montag, 21. Juni 2021 07:00:42
   Source : d:\SoDox\Project\0.0.0.1\latex\
     Dest : \\SomeServer\Doxygen\ProjName\BuildNumber\API-Documentation.pdf\

    Files : refman.pdf
	    
  Options : /S /E /DCOPY:DA /COPY:DAT /NP /R:3 /W:30 

------------------------------------------------------------------------------

	                   1	d:\SoDox\Project\0.0.0.1\latex\
	    New File  		  702008	refman.pdf
	  New Dir          0	d:\SoDox\Project\0.0.0.1\latex\d0\
	  New Dir          0	d:\SoDox\Project\0.0.0.1\latex\d0\d00\
	  New Dir          0	d:\SoDox\Project\0.0.0.1\latex\d0\d01\
	  New Dir          0	d:\SoDox\Project\0.0.0.1\latex\d0\d02\
	  New Dir          0	d:\SoDox\Project\0.0.0.1\latex\d0\d03\
[...]
```

## Explanation

Due to the hardcoded `/E` option in [Invoke-Robocopy.ps1](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishBuildArtifactsV1/Invoke-Robocopy.ps1) single file copy is not performed as expected.

**Comment by anatolybolshakov** [comment]
Hey @snewz the related fix has been rolled out for this feature - closing this one at the moment. Please let us know if you have any further questions.

**Comment by snewz** [comment]
Thanks for the update and the fix :-)
