### ISSUE TITLE
AzureBlob File Copy partially failed (Copy failed on 30/304 files)

### ISSUE THREAD

**Issue by rgong-cfn** [microsoft/azure-pipelines-tasks#14981]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure File Copy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipeline; https://dev.azure.com/commonwealthbrandstudio/BrandStudio/_releaseProgress?_a=release-environment-logs&releaseId=2457&environmentId=2457

- Agent - Hosted or Private: 
    - Hosted Agent

## Issue Description

Build is successful. Release failed at AzureBlob File Copy step.  It's not a complete fail. 274 files completed transfer. but 30 files failed. This exact pipeline was successful until 6/16. 

Current AZcopy.exe version:  4.185.0  We have tried to downgrade it to v2, v3. Still not working

![azurefile Blob Copy](https://user-images.githubusercontent.com/69167933/122570245-8fc8e680-d019-11eb-8a0f-58b41fcb90c5.PNG)

### Task logs
[ReleaseLogs_2464.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6677375/ReleaseLogs_2464.zip)

### Error logs

![error](https://user-images.githubusercontent.com/69167933/122570956-3ca36380-d01a-11eb-9956-83de1221432f.PNG)

**Comment by masterjs** [comment]
I also have the same issue and error message this morning.
Guessing an issue with `4.185.0`. My files are also partially copied. The biggest are not, so it might be the pattern.
Hope this will be fixed soon!
JS

**Comment by tasha-rooney-ul** [comment]
We are seeing the same issue as well. The same 4 files, which are our largest files, consistently return the error below. Our largest file is only 181KB

`ERR: [P#0-T#1] UPLOADFAILED: <filename> : 000 : source modified during transfer.`

The difference with our pipeline is that the files are all successfully uploaded to our storage account, but the script thinks they're not when it first checks for success/error so it throws an error. Maybe it's a timeout issue?

**Comment by rawatmanish** [comment]
Same error in our pipelines also

**Comment by masterjs** [comment]
This morning it started working again. Since its still version `4.185.0` there was another issue elsewhere that was likely resolved.

**Comment by shermes** [comment]
I implemented a slightly different workaround based on the suggestion by @tasha-rooney-ul . I just replaced the AzureBlob file copy task with an Azure CLI task that ran azure blob upload. This is the command that worked for me. It ran faster than the AzureBlob file copy task as well.

`az storage blob upload-batch --account-name <STORAGE ACCOUNT NAME>  --auth-mode login  --destination ‘$web’ --source .`

Our build pipeline creates an artifact that is a folder with all of the assets to deploy in it. In order for that command to work, you have to set the Working Directory on the Azure CLI task to that same folder. It copies the contents of that folder and all of its subdirectories. This also assumes that you have given the service principal that the pipeline is running under sufficient rights to the storage account.

**Comment by AmrutaKawade** [comment]
Sorry for delayed response
@rgong-cfn @rawatmanish 
is it working now?

**Comment by jakwo** [comment]
I do have the same issue. The **same files** are always skipped. Those 6 files are the only ones above 5MB. I did not change anything. It just stopped working on the 6/18 - but worked immediately after again. 

But since last friday (6/25) it does not work anymore at all. Not with Version 3 and also not with Version 4. 

I will try the provided workaround though.

**Comment by masterjs** [comment]
On my side it started working again a few days then wasn't working yesterday (likely since Friday). Since it hit us twice, we completely changed our approach too and switched the method suggested by @shermes  and @tasha-rooney-ul . Now we have no more surprises and it works well.

**Comment by jakwo** [comment]
I used @shermes "workaround" which works just fine. Thanks!

**Comment by chshrikh** [comment]
closing this as scenario is working
