### ISSUE TITLE
cache restore not happening for sequential jobs in same pipeline

### ISSUE THREAD

**Issue by cforce** [microsoft/azure-pipelines-tasks#14980]
I can repeatable prove that running a sequence of 3 jobs where first and third  using maven caching under the same key, i don't find released artifacts produced in job 1 in restored cache of third job -  even although second job is between first and third and is taking at least 5 minutes - so enough time to let the cache state being finally committed on the storage blade.
So what is really the reliable definition for a minimum hit rate if its even not fulfilled on "same" pipeline for a dependent sequence of jobs.  For me it looks like there is even not at all a guarantee for job sequences they will the cache items produced before.

I would call it a bug.

**Comment by cforce** [comment]
please reopen, as its still a bug being present which noone has fixed

**Comment by anatolybolshakov** [comment]
Hi @cforce could you please share more details about this request? Do you use Maven Cache in your pipeline?

**Comment by cforce** [comment]
Yrs

**Comment by anatolybolshakov** [comment]
@cforce currently jobs are independent units of execution which could be picked up by separate agents - so there is no guarantee that they would be picked up by the same (and artifacts generated in file system will remain the same as well).
If you would need to keep them - you may probably locate all the tasks in one job, so it will be executed on one agent machine by one agent.
For more questions about Azure DevOps - you can open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.
Please let us know if you have any other questions regarding pipeline tasks - I'm closing this one at the moment.
