### ISSUE TITLE
XCode fails to export signing when using ".xcodeproj"

### ISSUE THREAD

**Issue by jloehr** [microsoft/azure-pipelines-tasks#14994]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: XCode

## Environment

- Server - Azure Pipelines

## Issue Description

We're building our Unity iOS Application with Azure DevOps. Previously Unity did generate an Xcode Workspace in the resulting XCode project. However with Unity 2020.3.12 it does not.

Up to now we were using `signingOption: 'default'` and default `xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'`, to use the signing from the generated XCode project.

Now with the lack of the generated `project.xcworkspace`, I changed `xcWorkspacePath` to `xcWorkspacePath: '**/*.xcodeproj'` to build using the XCode project instead. When it comes to generating the export list and signing there is the warning:

> ##[warning]The provisioning style was not found in a pbxProject file. Automatic signing will be used. If the project uses manual signing, auto-export may fail. As a workaround, `Export options` can be set to `Plist` or `Specify`.

... and the builds fails.

The issue seems to be in `xcodeutils.ts`
https://github.com/microsoft/azure-pipelines-tasks/blob/dab7489d02a3c563206ee489042c6639f41c7fdd/Tasks/XcodeV5/xcodeutils.ts#L145

It only searches and resolves the `.pbxproj` file if an `.xcworkspace` path is used, but not if you provide a `.xcodeproj`. In case it's relevant, for us the `.pbxproj` is directly in the XCodeProject folder.

## Temporary Workaround

Because the generated workspace is basically empty, I have added an additonal build step that just creates the `.xworkspace` before the XCode step (Simple `mkdir -p $(Build.SourcesDirectory)/Unity-iPhone.xcodeproj/project.xcworkspace`).
This seems to do the trick, so I can continue using `xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'`.

**Comment by kuleshovilya** [comment]
Hello @jloehr . The issue doesn't seem to be with the lack of xcworkspace, task can handle that. Moreover, the function that you've provided in the description is for converting old-styled workspace to a pbxproj. Seems, like an issue has something to do with the signing options and warning that you've provided tells exactly that. 
Can you please provide:
agent version and xcode version
You can provide them privately to v-ikuleshov@microsoft.com

For troubleshooting purposes, try generating new empty Unity Project and build it with pipeline, chances are it will work fine. Also, check build through xcode, what does it say in Signing&Capabilities, manually set to correct options and try to rebuild it with pipelines, that way we would be able to pinpoint the issue a little.

**Comment by kuleshovilya** [comment]
@jloehr Any update on the issue?

**Comment by kuleshovilya** [comment]
Alright, I'll close the issue for now. Please, check it when you can, and you can either send in message to this issue or ping me at my email v-ikuleshov@microsoft.com
