### ISSUE TITLE
ID Disabled in Azure active directory

### ISSUE THREAD

**Issue by harini312296** [microsoft/azure-pipelines-tasks#14996]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

One of our team mates has left the organisation and his id has been disabled and hence we are receiving id disabled error and we want to know where can i add my user id to download artifacts packages from git to our pipeline .

### Task logs

2021-06-24T17:05:24.1669934Z {"@t":"2021-06-24T17:05:23.9840943Z","@m":"An error occurred on the service. According to Azure Active Directory, your Identity sp824s@att.com is currently Disabled within the following Azure Active Directory: AT&T Services, Inc.. Please contact your AAD administrator to resolve this.  For more information please read https://go.microsoft.com/fwlink/?linkid=2007012","@i":"3a99e86c","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2021-06-24 17:05:23.984Z"}

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by Arniox** [comment]
I'm having the exact same issue. One of our team members left and it is throwing an identical error.
