### ISSUE TITLE
Bash: diff comand's returns invalid characters.

### ISSUE THREAD

**Issue by jpulipv** [microsoft/azure-pipelines-tasks#14992]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: BASH

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    - https://jcidata.visualstudio.com/DigitalVault

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
private agent - windows 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

when using diff command in the BASH task on a windows hosted agent, diff is returning invalid characters. 
![diff](https://user-images.githubusercontent.com/83298856/123116424-e6199900-d40e-11eb-8c88-0804c0feb085.PNG)

### Task logs
[tasklog_9.log](https://github.com/microsoft/azure-pipelines-tasks/files/6702679/tasklog_9.log)

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by kuleshovilya** [comment]
Hello @jpulipv , we couldn't reproduce the issue on other machines, so could you please provide a little more details on how we go about this: 
- what is the encoding on the compared files?
- can those files be read through your local instance bash at all?
- could we get examples of those files without any sensitive data on them for testing?
- can you try the same pipeline on other machine?
You can also contact me and send requested info on v-ikuleshov@microsoft.com

**Comment by kuleshovilya** [comment]
Also, make sure that your region settings are set like this, since behaviour in your example seems really like an issue with those  settings
![image](https://user-images.githubusercontent.com/87485027/128826605-bc92e912-6931-4f2e-9cbc-974d661a985c.png)

**Comment by kuleshovilya** [comment]
@jpulipv , any update on the issue?

**Comment by kuleshovilya** [comment]
@jpulipv , I'll close issue for now. You can reopen it or ping me at my email v-ikuleshov@microsoft.com
