### ISSUE TITLE
HelmDeploy overrideValues is not a multiline field

### ISSUE THREAD

**Issue by MrLuje** [microsoft/azure-pipelines-tasks#14991]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy

## Environment
- Server - Azure Pipelines 
- Agent - Hosted

## Issue Description

HelmDeploy > "Set Values" field states that we can either split values with comma or new lines
Unfortunatly, this field is not defined as multiline

![image](https://user-images.githubusercontent.com/632075/123071128-ad7cbe00-d414-11eb-873f-19bf52912762.png)

I guess "\n" would do the trick but it would be much better as a multiline field

**Comment by Heisenberg74** [comment]
Hi @MrLuje ,

As described in [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops), if you require a multiline value, you have to use the `valueFile` parameter 👍 

```
.... Please note that if you have a value which itself contains newlines, use the valueFile option, else the task will treat the newline as a delimiter....
```

**Comment by MrLuje** [comment]
Hi,

This is not about a multiline value, but multiple keys/values
We are setting several values through this field but it quickly becomes
hard to read with everything on the same line.

We are also using valueFile but when we have to temporarily override a
value, we are doing it through the "Set value" field

Example of "Set values" :

cron.command={"/bin/sh","-c","$(pre_start_cmd)dotnet
> /app/Pricing.Application.Console.dll Push FacialPrice &&
> $(cronjob_curl_cmd)"},cron.schedule=$(cron_schedule),resources.limits.memory="800Mi",resources.limits.cpu="400m",resources.requests.memory="200Mi",resources.requests.cpu="100m",application.environment=$(helm_label_environment)


From the quick help, I understand I should be able to pass values like this
:

cron.command={"/bin/sh","-c","$(pre_start_cmd)dotnet
> /app/Pricing.Application.Console.dll Push FacialPrice &&
> $(cronjob_curl_cmd)"}
> cron.schedule=$(cron_schedule)
> resources.limits.memory="800Mi"
> resources.limits.cpu="400m"
> resources.requests.memory="200Mi"
> resources.requests.cpu="100m"
> application.environment=$(helm_label_environment)


but as stated in the issue, this is not the case.
If it is not expected to use this field like this, please reword the quick
help as it is misleading :)

By the way, the task is not referencing the documentation link you provided
(it refers to https://go.microsoft.com/fwlink/?linkid=851275 which is home
page documentation), could it be corrected ?

[image: image.png]

Many thanks,

*Vincent*

**Comment by Kolossi** [comment]
Issue still occuring for me, and would like to know fix?

**Comment by knunery** [comment]
This issue is still occurring.
