### ISSUE TITLE
Project Administrator is not able to Complete the Pull Requests in Azure DevOps

### ISSUE THREAD

**Issue by kiranjunnuthula** [microsoft/azure-pipelines-tasks#15018]
## Note  
Project Administrator is not able to Complete the Pull Requests in Azure DevOps

One of Colleague is having Project Administrator access but he is not able to complete the pull requests which is created by developers. He is getting "Approve" button and he can approve but he is not getting the option to "Complete" the pull request. instead of "Complete" Option he is getting "Mark as Draft".

Please let me know which access we need to Give to his ID in order to get the permissions to completed the pull requests in Azure DevOps.

Thanks,
Kiran Junnuthula
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/55826988/124554247-64d0f600-de53-11eb-83d1-22ec9ae3417e.png)

**Comment by anatolybolshakov** [comment]
Hi @kiranjunnuthula this repo is mostly for pipeline tasks related questions - could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?
Let me close this one here since it's not related to pipeline tasks.
