### ISSUE TITLE
DownloadPackage Task Fails When Trying To Get Latest Version of a Package

### ISSUE THREAD

**Issue by asos-benhoward** [microsoft/azure-pipelines-tasks#15022]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPackage

## Environment
_Not sharing org name or project here!_

- Agent - Hosted

## Issue Description
This issue relates to pull request [12334](https://github.com/microsoft/azure-pipelines-tasks/pull/12334) - DownloadPackage to support latest version.

We have a feed which contains nearly 6000 packages.  I'm trying to use the DownloadPackage task with "latest" as the version.  The [`ResolveLatestVersion`](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/DownloadPackageV1/package.ts#L140) function appears to be using an undocumented querystring parameter that either does not exist, or does not work.  The `packageIdQuery` parameter is ignored and the top 1000 of __all__ packages in the feed are returned.  The package I'm trying to download happens to be the 1444th package in the list and so the function fails when it can't be found as it does not appear in the first 1000 packages.  I would have thought the correct uri would be [this one](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact%20%20details/get%20package?view=azure-devops-rest-6.0), as at this point the packageid is known (either br resolving from package name or because the id was passed in directly).

### Task logs

I'm not going to share logs here.

## To Replicate
- Create a feed with more than 1000 packages
- Call `_apis/Packaging/Feeds/[feedid]/Packages` and identify which packages are not in the response
- Try to download _the latest version_ one of those packages using the DownloadPackage@1 task

**Comment by asos-benhoward** [comment]
@evertonmc

**Comment by asos-benhoward** [comment]
This is still an issue

**Comment by bjh1977** [comment]
Still an issue

**Comment by bjh1977** [comment]
Still an issue
