### ISSUE TITLE
401 - Unauthorized Access with task DownloadBuildArtifact 

### ISSUE THREAD

**Issue by pollau** [microsoft/azure-pipelines-tasks#15024]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadBuildArtifact 

## Environment
- Server - Azure Pipelines or TFS on-premises?
    TFS on-premises
    - If using TFS on-premises, provide the version: Dev18.M170.6 

- Agent - Hosted or Private: 
 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      - Microsoft Windows Server 2012 R2 Standard
      - Agent version 2.170.1 

## Issue Description

I am unable to download artifact with the task DownloadBuildArtifact version 0.188.3. I am using the task PublishBuildArtifact@1 to publish the artifacts, the task is successful and the artifacts exist.
![image](https://user-images.githubusercontent.com/14982032/124781344-87573200-df6d-11eb-9cfa-c689ae2dc8cf.png)

The task DownloadBuildArtifact then return a error 401 for unauthorized access to the resource. 

I don't understand why this is happening since the other tasks are successful. 
I also don't have auth issues while downloading the artifact in the classical editor.
![image](https://user-images.githubusercontent.com/14982032/124782464-722ed300-df6e-11eb-9188-c8a262f5d207.png)

### Task logs
[2_Download Artifact.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6778292/2_Download.Artifact.txt)

### Custom logs
I added some custom log to get more info about the issue and I got this result
```
{ Error: Failed request: (statusCode) 401
    at WebClient.<anonymous> (C:\Shield_Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.210.0\node_modules\artifact-engine\Providers\webClient.js:56:23)
    at Generator.next (<anonymous>)
    at C:\Shield_Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.210.0\node_modules\artifact-engine\Providers\webClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Shield_Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.210.0\node_modules\artifact-engine\Providers\webClient.js:4:12)
    at WebClient.processResponse (C:\Shield_Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.210.0\node_modules\artifact-engine\Providers\webClient.js:50:16)
    at httpc.get.then (C:\Shield_Agent\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.210.0\node_modules\artifact-engine\Providers\webClient.js:35:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  statusCode: 401,
  result:
   '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>401 - Unauthorized: Access 
```is denied due to invalid credentials.</h2>\r\n  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n' }
##[debug]Error getting :Error: Failed request: (statusCode) 401

**Comment by anatolybolshakov** [comment]
Hi @pollau have it worked for you before?

**Comment by pollau** [comment]
> Hi @pollau have it worked for you before?

No, not with yaml pipeline
