### ISSUE TITLE
BUG: DotNetCoreCLI - XUnit [Theory] output misreporting test counts due to mishandling of [Theory] tests

### ISSUE THREAD

**Issue by davidfordaus** [microsoft/azure-pipelines-tasks#15030]
Related to this item marked as question when in reality it is a bug:
https://github.com/microsoft/azure-pipelines-tasks/issues/13842

**SUMMARY**
- The Bug relates to XUnit and any _Theory_ type tests that rely on data iteration (inline, iterator, etc).
- The reported Visual Studio test count is higher than the Azure test count as any "Theorem" test returns a count of one test rather than the correct count of one test per data line / data input to the theory
- There is no known workaround.  
-  It causes confusion when the local Visual Studio test runner reports N tests and Azure reports a different and lower number
- There is only complex workarounds or customer-side solutions including source code auto generation
- This issue only occurs in the newer YAML-based pipelines and the task as follows.  The older non-YAML pipelines don't have the problem

```
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '.'
    testRunTitle: 'Test'

```

It is causing us significant issue as we have many Theory type tests and literally have a tiny number of tests reported from Azure even though we have over 1600 tests via Theory data.

**Comment by davidfordaus** [comment]
Example:
![image](https://user-images.githubusercontent.com/602815/125229800-d6f57f00-e31a-11eb-83f7-800fa6b94c70.png)

Summary states 1 failed, 0 passed.  Screenshot clearly shows 1 passed and 1 failed.

**Comment by davidfordaus** [comment]
Further: the generic VSTest@2 also has the same issue:

```
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **DatabaseTest\**\*DatabaseTest*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
```

![image](https://user-images.githubusercontent.com/602815/125257903-31093b00-e341-11eb-81be-a8585379d8bb.png)

**Comment by thisismyself** [comment]
The issue is still happening, reopen the issue please.
In the output log I see 
```
Test Run Successful.
Total tests: 889
Passed: 889
```
while on the UI it shows me 750 tests only (and is reporting like this in output log as well):
```
Async Command Start: Publish test results
Publishing test results to test run '1000008'.
TestResults To Publish 750, Test run id:1000008
Test results publishing 750, remaining: 0. Test run id: 1000008
````
Meanwhile, in Visual Studio 2022, Test Explorer reports 875 tests. Yet another number :-/

**Comment by itayang** [comment]
Was this resolved?

I also noticed that there's a difference between VSTest@2 step and DotNetCoreCLI@2 in terms of numbers.
VSTest@2 recently (or when moving to VS2022 / more recent MSBuild) started counting theory inline data as a stand alone test (which is fine) but DotNetCoreCLI step (with test command) seems to have stayed behind.
