### ISSUE TITLE
Jenkins Queue Task queues must be fail when its # Finished: UNSTABLE #

### ISSUE THREAD

**Issue by maulikhdave9601672767** [microsoft/azure-pipelines-tasks#15031]
i m running Jenkins Queue Task queues  from azure devops.
im running my test in jenkin so i want to fail my Jenkins Queue Task whene ever 

jenkin has Unstable fail or gray result. it only must success if its success or my all test run success on jenkin job..

please let me know if i can provide more information

**Comment by kuleshovilya** [comment]
We've introduced a new flag for this job:
failOnUnstableResult (boolean) which you can set to a true, if you want the behaviour you've requested. 
It's already in the master, you can try it out.

**Comment by kuleshovilya** [comment]
The flag was deployed to ADO, you can test it now. Closing issue now.
