### ISSUE TITLE
AzureKeyVaultV1 still does not retry in the event of transient network troubles

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-tasks#15052]
(No need to read the below unless you want to.  This is the same issue as https://github.com/microsoft/azure-pipelines-tasks/issues/13998, it's [still reproducing in later builds](https://dev.azure.com/dnceng/internal/_build/results?buildId=1227295&view=logs&j=f6520c01-78a6-558b-586b-1352fca1b090&t=cffede2b-c410-53da-9ef3-30f83a24f708&l=14) but I am not allowed to reopen that issue)

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureKeyVault

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure pipelines.
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account: dnceng
Project: internal
Build Definition name: dotnet-runtime-internal
Build #: 899915

- Agent - Hosted or Private: 
    
    - Private.   Windows 10 20H1 Client

## Issue Description

All our stuff runs in Azure, and lately there have been various Azure blips and DNS issues.  The code that tries to access the key vault doesn't have any retries in it. leading to logging like:

```
Downloading secret value for: <SecretName>.
##[error]
<SecretName>: "getaddrinfo EAI_AGAIN login.windows.net login.windows.net:443"
```

### Error logs

Please feel free to contact me directly; cannot share on GitHub.  .  I can't provide logs for Azure DevOps builds using this task because it uses secrets.

The error looks like this:
```
Starting: Download secrets: <VaultName>
==============================================================================
Task         : Azure Key Vault
Description  : Download Azure Key Vault secrets
Version      : 1.175.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-key-vault
==============================================================================
SubscriptionId: 68672ab8-de0c-40f1-8d1b-ffb20bd62c0f.
Key vault name: <VaultName>.
Downloading secret value for: <SecretName>.
##[error]
<SecretName>: "getaddrinfo EAI_AGAIN login.windows.net login.windows.net:443"
Finishing: Download secrets: <VaultName>

```

**Comment by MattGal** [comment]
It's been 374 days with no comment from the azure-pipelines-tasks team.  @rohit-batra FYI.

**Comment by mmrazik** [comment]
Created https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1973203 to track it in ADO backlog

**Comment by netaques** [comment]
Hi @MattGal, I have just sent you an email to you microsoft address. It would be great if you could share the debug logs with me. Since [PR 14135](https://github.com/microsoft/azure-pipelines-tasks/pull/14135) has introduced the retry logic for several error codes, I am wondering what kind of http error you have been facing to.

**Comment by starkmsu** [comment]
This might be fixed after https://github.com/microsoft/azure-pipelines-tasks/pull/16922 is merged

**Comment by romanofski** [comment]
Hi, I was very much following this ticket here because we get hit quite often by this. The version made it down to us and unfortunately I still don't see a retry (redacted internal names):

```
==============================================================================
Task         : Azure Key Vault
Description  : Download Azure Key Vault secrets
Version      : 2.211.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-key-vault
==============================================================================
SubscriptionId: <sub-id>.
Key vault name: <vault-name>.
Downloading secrets using: https://<vault-name>.vault.azure.net/secrets?maxresults=25&api-version=2016-10-01.
##[error]Get secrets failed. Error: getaddrinfo EAI_AGAIN <vault-name>.vault.azure.net <vault-name>.vault.azure.net:443.
```

If I understand the code correctly, shouldn't the task already have retried before #16922 since we keep a list of `retriableErrorCodes`? 

Either way, is there a chance I could run this task in our pipeline with debug output to perhaps see more output? Thank you.
