### ISSUE TITLE
Azure DevOps “Required template check” not working

### ISSUE THREAD

**Issue by msrinivascharan** [microsoft/azure-pipelines-tasks#15055]
I am extending a template through repository resource in a yml pipeline (mainpipeline.yml), all working fine. project’s, repo folder structure details below.

My template is in OrgA -> proj1 -> repoX -> branch -> templates/set1/template1.yml (only one stage in this template with one job and 3 tasks)

My main pipeline is in OrgA -> proj2 -> repoY ->branch -> pipelines/mainpipeline.yml

Created service connection sc1 in OrgA -> proj2 to invoke templates from OrgA -> proj1 -> repoX

But the issue is, added required template check to enforce “mainpipeline.yml” extends “template1.yml" with help of steps provided by Microsoft documentation. check not working, it’s not restricting main pipeline to invoke other then the one added in the check, there is no pass or fail info.

**Comment by tatyana-kostromskaya** [comment]
This issue  is not related to the pipeline tasks, and this repo is mostly for pipeline tasks issues - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by msrinivascharan** [comment]
I solved this issue by adding step "- checkout: " in templates. Now, the the "Required template" check added to the service connection working fine, stopping main pipeline to invoke other then allowed templates.

**Comment by msrinivascharan** [comment]
thank you @tatyana-kostromskaya.
