### ISSUE TITLE
IIS Web App Manage task started to fails when deploying to one environment by work on another

### ISSUE THREAD

**Issue by rfigueroa2014** [microsoft/azure-pipelines-tasks#15054]
Are production deployment pipleline was working fine, but sudden stopped on IIS Web App Manage, takes.  But the QA stage of the release is still working fine.  Cannot figure out why it started to fail, as there have been no changes to config or target servers.

Below is a verbose log:

##[debug]Evaluating condition for step: 'IIS Web App Manage'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: IIS Web App Manage
==============================================================================
Task         : IIS web app manage
Description  : Create or update websites, web apps, virtual directories, or application pools
Version      : 0.5.15
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group
==============================================================================
##[debug]VstsTaskSdk 0.8.2 commit 
##[debug]Entering C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1.
##[debug]Loading resource strings from: C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\Task.json
##[debug]Loaded 8 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 8 strings.
##[debug]Loading module from path 'C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\TaskModuleIISManageUtility\TaskModuleIISManageUtility.psd1'.
##[debug]Loading module from path 'C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\TaskModuleIISManageUtility\TaskModuleIISManageUtility.psm1'.
##[debug]NonInteractive: False
##[debug]Entering script AppCmdOnTargetMachines.ps1
##[debug]Exporting function 'Invoke-Main'.
##[debug]Adding exceptions types.
##[debug]Importing function 'Invoke-Main'.
##[debug]INPUT_ENABLEIIS: 'false'
##[debug]INPUT_ACTIONIISWEBSITE: 'CreateOrUpdateWebsite'
##[debug]INPUT_WEBSITENAME: 'partnerapi'
##[debug]INPUT_STARTSTOPWEBSITENAME: 'partnerapi'
##[debug]INPUT_WEBSITEPHYSICALPATH: '%SystemDrive%\inetpub\wwwroot'
##[debug]INPUT_WEBSITEPHYSICALPATHAUTH: 'WebsiteUserPassThrough'
##[debug]INPUT_WEBSITEAUTHUSERNAME (empty)
##[debug]INPUT_WEBSITEAUTHUSERPASSWORD (empty)
##[debug]INPUT_ADDBINDING: 'True'
##[debug]INPUT_PROTOCOL: 'http'
##[debug]INPUT_IPADDRESS: 'All Unassigned'
##[debug]INPUT_PORT: '80'
##[debug]INPUT_SERVERNAMEINDICATION: 'false'
##[debug]INPUT_HOSTNAMEWITHOUTSNI (empty)
##[debug]INPUT_HOSTNAMEWITHHTTP (empty)
##[debug]INPUT_HOSTNAMEWITHSNI (empty)
##[debug]INPUT_SSLCERTTHUMBPRINT (empty)
##[debug]INPUT_BINDINGS: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"","sslThumbprint":"","sniFlag":false}]}'
##[debug]INPUT_CREATEORUPDATEAPPPOOLFORWEBSITE: 'false'
##[debug]INPUT_APPPOOLNAMEFORWEBSITE (empty)
##[debug]INPUT_DOTNETVERSIONFORWEBSITE: 'v4.0'
##[debug]INPUT_PIPELINEMODEFORWEBSITE: 'Integrated'
##[debug]INPUT_APPPOOLIDENTITYFORWEBSITE: 'ApplicationPoolIdentity'
##[debug]INPUT_APPPOOLUSERNAMEFORWEBSITE (empty)
##[debug]INPUT_APPPOOLPASSWORDFORWEBSITE (empty)
##[debug]INPUT_CONFIGUREAUTHENTICATIONFORWEBSITE: 'false'
##[debug]INPUT_ANONYMOUSAUTHENTICATIONFORWEBSITE: 'false'
##[debug]INPUT_BASICAUTHENTICATIONFORWEBSITE: 'false'
##[debug]INPUT_WINDOWSAUTHENTICATIONFORWEBSITE: 'true'
##[debug]INPUT_PARENTWEBSITENAMEFORVD: 'partnerapi'
##[debug]INPUT_VIRTUALPATHFORVD: '/'
##[debug]INPUT_PHYSICALPATHFORVD: '%SystemDrive%\inetpub\wwwroot'
##[debug]INPUT_VDPHYSICALPATHAUTH: 'VDUserPassThrough'
##[debug]INPUT_VDAUTHUSERNAME (empty)
##[debug]INPUT_VDAUTHUSERPASSWORD (empty)
##[debug]INPUT_PARENTWEBSITENAMEFORAPPLICATION: 'partnerapi'
##[debug]INPUT_VIRTUALPATHFORAPPLICATION: '/'
##[debug]INPUT_PHYSICALPATHFORAPPLICATION: 'D:\wwwroot\partnerapi'
##[debug]INPUT_APPLICATIONPHYSICALPATHAUTH: 'ApplicationWindowsAuth'
##[debug]INPUT_APPLICATIONAUTHUSERNAME: 'Administrator'
##[debug]INPUT_APPLICATIONAUTHUSERPASSWORD: 'M@ilR00m'
##[debug]INPUT_CREATEORUPDATEAPPPOOLFORAPPLICATION: 'true'
##[debug]INPUT_APPPOOLNAMEFORAPPLICATION: 'partnerapi'
##[debug]INPUT_DOTNETVERSIONFORAPPLICATION: 'v4.0'
##[debug]INPUT_PIPELINEMODEFORAPPLICATION: 'Integrated'
##[debug]INPUT_APPPOOLIDENTITYFORAPPLICATION: 'SpecificUser'
##[debug]INPUT_APPPOOLUSERNAMEFORAPPLICATION: 'Administrator'
##[debug]INPUT_APPPOOLPASSWORDFORAPPLICATION: 'M@ilR00m'
##[debug]INPUT_ACTIONIISAPPLICATIONPOOL: 'CreateOrUpdateAppPool'
##[debug]INPUT_APPPOOLNAME (empty)
##[debug]INPUT_STARTSTOPRECYCLEAPPPOOLNAME (empty)
##[debug]INPUT_DOTNETVERSION: 'v4.0'
##[debug]INPUT_PIPELINEMODE: 'Integrated'
##[debug]INPUT_APPPOOLIDENTITY: 'ApplicationPoolIdentity'
##[debug]INPUT_APPPOOLUSERNAME (empty)
##[debug]INPUT_APPPOOLPASSWORD (empty)
##[debug]INPUT_APPCMDCOMMANDS (empty)
##[debug]INPUT_IISDEPLOYMENTTYPE: 'IISWebApplication'
##[debug]Triming inputs for excess spaces, double quotes
##[debug]Initiating action 'create or update' application with user specified application pool.
##[debug]Entering Invoke-Main function
##[debug]ActionIISWebsite = 
##[debug]ActionIISApplicationPool = CreateOrUpdateAppPool
##[debug]CreateApplication = True
##[debug]CreateVirtualDirectory = 
##[debug]VirtualPath = /
##[debug]WebsiteName = partnerapi
##[debug]PhysicalPath = D:\wwwroot\partnerapi
##[debug]PhysicalPathAuth = ApplicationWindowsAuth
##[debug]AddBinding = 
##[debug]AppPoolName = partnerapi
##[debug]DotNetVersion = v4.0
##[debug]PipeLineMode = Integrated
##[debug]AppPoolIdentity = SpecificUser
##[debug]ConfigureAuthentication = 
##[debug]AnonymousAuthentication = 
##[debug]BasicAuthentication = 
##[debug]WindowsAuthentication = 
##[debug]AppCmdCommands = 
##[debug]Checking application pool exists. Running command : "C:\Windows\system32\inetsrv\appcmd.exe"  list apppool /name:"partnerapi"
##[debug]Entering Invoke-VstsTool.
##[debug] FileName: 'C:\Windows\system32\inetsrv\appcmd.exe'
##[debug] Arguments: ' list apppool /name:"partnerapi"'
##[command]"C:\Windows\system32\inetsrv\appcmd.exe"  list apppool /name:"partnerapi"
##[debug]Exit code: 0
##[debug]Leaving Invoke-VstsTool.
##[debug]Application Pool ("partnerapi") already exists
##[debug]Updating application pool properties. Running command : "C:\Windows\system32\inetsrv\appcmd.exe"  set apppool /apppool.name:"partnerapi" -managedRuntimeVersion:v4.0 -managedPipelineMode:Integrated -processModel.identityType:SpecificUser -processModel.userName:"Administrator" -processModel.password:"M@ilR00m"
##[debug]Entering Invoke-VstsTool.
##[debug] FileName: 'C:\Windows\system32\inetsrv\appcmd.exe'
##[debug] Arguments: ' set apppool /apppool.name:"partnerapi" -managedRuntimeVersion:v4.0 -managedPipelineMode:Integrated -processModel.identityType:SpecificUser -processModel.userName:"Administrator" -processModel.password:"M@ilR00m"'
##[debug] RequireExitCodeZero: 'True'
##[command]"C:\Windows\system32\inetsrv\appcmd.exe"  set apppool /apppool.name:"partnerapi" -managedRuntimeVersion:v4.0 -managedPipelineMode:Integrated -processModel.identityType:SpecificUser -processModel.userName:"Administrator" -processModel.password:"M@ilR00m"
APPPOOL object "partnerapi" changed
##[debug]Exit code: 0
##[debug]Leaving Invoke-VstsTool.
##[debug]Checking application exists. Running command : "C:\Windows\system32\inetsrv\appcmd.exe"  list app "partnerapi/"
##[debug]Entering Invoke-VstsTool.
##[debug] FileName: 'C:\Windows\system32\inetsrv\appcmd.exe'
##[debug] Arguments: ' list app "partnerapi/"'
##[command]"C:\Windows\system32\inetsrv\appcmd.exe"  list app "partnerapi/"
##[debug]Exit code: 0
##[debug]Leaving Invoke-VstsTool.
##[debug]Application ("partnerapi/") already exists
##[debug]Checking application physical path exists D:\wwwroot\partnerapi
##[debug]Updating application properties. Running command : "C:\Windows\system32\inetsrv\appcmd.exe"  set app /app.name:"partnerapi/" -applicationPool:"partnerapi" -[path='/'].physicalPath:"D:\wwwroot\partnerapi" -[path='/'].userName:"Administrator" -[path='/'].password:"M@ilR00m"
##[debug]Entering Invoke-VstsTool.
##[debug] FileName: 'C:\Windows\system32\inetsrv\appcmd.exe'
##[debug] Arguments: ' set app /app.name:"partnerapi/" -applicationPool:"partnerapi" -[path='/'].physicalPath:"D:\wwwroot\partnerapi" -[path='/'].userName:"Administrator" -[path='/'].password:"M@ilR00m"'
##[debug] RequireExitCodeZero: 'True'
##[command]"C:\Windows\system32\inetsrv\appcmd.exe"  set app /app.name:"partnerapi/" -applicationPool:"partnerapi" -[path='/'].physicalPath:"D:\wwwroot\partnerapi" -[path='/'].userName:"Administrator" -[path='/'].password:"M@ilR00m"
APP object "partnerapi/" changed
##[debug]Exit code: 0
##[debug]Leaving Invoke-VstsTool.
##[debug]Exiting Execute-Main function
##[debug]Leaving C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1.
##[error]Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1'''))"'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1'''))"'.
Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
Services.Agent.Worker.TaskRunner.RunAsync()
Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Finishing: IIS Web App Manage

**Comment by keitharowe** [comment]
@rfigueroa2014 there are plain text credentials in your post

**Comment by secretcoder** [comment]
It's powershell related. If you have powershell version 4.0 make sure to update to 5.1 as new azagent update doesn't work with 4.0.

Link below for instructions on update/upgrading

http://woshub.com/install-update-powershell-windows/
