### ISSUE TITLE
Can you use 'Download Build Artifacts' to download artifacts from a different collection?

### ISSUE THREAD

**Issue by nadcraker** [microsoft/azure-pipelines-tasks#15063]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Download Build Artifacts

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? On premise 
    
    - If using TFS on-premises, provide the version: 18.170.30910.2 (Azure DevOps Server 2020.0.1)
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016 1607. Agent version is 2.170.1

## Issue Description

I want to download artifacts produced by a build pipeline that is in another collection on the same server. I don't see how to do that. Is it possible?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anatolybolshakov** [comment]
Hi @nadcraker could you please create ticket on https://developercommunity.visualstudio.com/search?space=22 to get right eyes on it? This seems to be more related to server-side, rather than task itself.
Could you please also share the link to created ticket here for visibility?

**Comment by anatolybolshakov** [comment]
Let me close this ticket here since it's more to be server-side question
