### ISSUE TITLE
service endpoint retrieve username and password

### ISSUE THREAD

**Issue by pathakrohit08** [microsoft/azure-pipelines-tasks#15067]
I am building an azure-pipelines-extension I have a custom endpoint with basic authentication. I need to pass this endpoint credentials to my datasources.

this is my vss-manifest.json

         "dataSources": [
           {
            "name": "AccessToken",
            "endpointUrl": "$(endpoint.url)",
            "requestVerb": "Post",
            "requestContent": "username={{{endpoint.username}}}&password={{{endpoint.password}}}&grant_type=password",
            "resultSelector": "jsonpath:$.access_token",
            "headers": [
              {
                "name": "Content-Type",
                "value": "application/x-www-form-urlencoded"
              }
            ]
          }

However it doesnt seem like username is getting passed . When i replace the line "requestContent" with 

           "requestContent": "username=my_username&password=my_password&grant_type=password",

It works. 
What am i missing here ?

**Comment by tatyana-kostromskaya** [comment]
Hello, @pathakrohit08 , please take a look at this answer on developer community: https://developercommunity.visualstudio.com/t/Is-there-a-way-to-use-custom-endpoint-pa/61533?space=21&entry=problem&q=custom+endpoint&viewtype=all

Most likely it may help you to resolve you problem.

**Comment by pathakrohit08** [comment]
@tatyana-kostromskaya  Thank you i was able to make it work.
