### ISSUE TITLE
Azure File Copy Task 4.*: Update to AzCopy 10.11 to support custom file extension to content-type mappings

### ISSUE THREAD

**Issue by josundt** [microsoft/azure-pipelines-tasks#15070]
AzCopy 10.11 finally adds the capability to define your own file extension -> content-type mappings using a JSON file.
If the `AZCOPY_CONTENT_TYPE_MAP` environment variable is set to the path of a JSON file, the mappings defined in this file will take precedence over the mappings built into the operating system. 
https://github.com/Azure/azure-storage-azcopy/wiki/Custom-mime-mapping

With this new feature you finally get full control of the target blobs' Content-Type properties when AzCopy-ing.
I have been waiting for this AzCopy feature for more than 2.5 years (https://github.com/Azure/azure-storage-azcopy/issues/136#issuecomment-884693732)

Please update the pipeline task to use AzCopy >= 10.11 so that this can be utilized in the Azure File Copy task.

PS! This task would also resolve #14809

**Comment by rquackenbush** [comment]
Any hope of getting this in? Azure File Copy Task 4.* is still using `10.8.0` of `AzCopy`.

**Comment by v-nagarajku** [comment]
Fixed the issue with ref to the below:
 https://github.com/microsoft/azure-pipelines-tasks/pull/15594
