### ISSUE TITLE
How can I publish coverage data (.coverage files) to Azure DevOps Server 2020?

### ISSUE THREAD

**Issue by mwelsh1118** [microsoft/azure-pipelines-tasks#15092]
## Required Information
*Type*: Question

**Enter Task Name**: Publish Test Results  

## Environment
Azure DevOps Server 2020
Private agents hosted on Windows Server 2016

## Issue Description

According to the documentation for Publish Test Results:
"You can also use this task in a build pipeline to publish code coverage results produced when running tests to Azure Pipelines or TFS in order to obtain coverage reporting."

I have tested this by running vstest.console.exe with coverage enabled to produce a .trx that references a .coverage file. I then use the Publish Test Results task, pointing to the trx. I see the test results in my build, but below that it still shows the link for "Setup code coverage" indicating the coverage data was not uploaded.

We are particularly interested in [code coverage for pull requests](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops). Under the FAQ it mentions:
"This can be used if you publish code coverage using the Visual Studio Test task, the test verb of dotnet core task and the **TRX option of the publish test results task**."

What is the correct way to publish .coverage files?

I looked at the Publish Code Coverage Results task, but that only accepts JaCoCo or Cobertura results, meaning we would need to translate the .coverage into one of those formats first. Besides, it sounds like that would not work for the pull request functionality we want.

**Comment by shailesh-sk** [comment]
Adding @suyash691 , @ankit-arora12 and @nadesu for follow up and closure.

**Comment by ddaymn** [comment]
I see the same thing 

![image](https://user-images.githubusercontent.com/19540999/128405532-0e687429-ba2b-465d-98e5-fe50a3bdc573.png)

![image](https://user-images.githubusercontent.com/19540999/128405622-59d141f8-16a3-42b3-8efb-089570612a63.png)

Notice no artifacts

**Comment by ddaymn** [comment]
- task: VSTest@2
    inputs:
      platform: "${{parameters.buildPlatform}}"
      testSelector: testAssemblies
      testAssemblyVer2: |
        **\*Tests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      configuration: ${{parameters.buildConfiguration}}
      codeCoverageEnabled: true
      vsTestVersion: toolsInstaller

**Comment by mwelsh1118** [comment]
I understand the VSTest task will generate code coverage data, but we have a very large codebase and a heavily optimized build process; we can't use the out-of-the-box VSTest task because it is not performant.  What we want to do is publish the .trx/.coverage files after we run the tests ourselves. According to the documentation, "Publish Test Results" is the correct task for that.

**Comment by ddaymn** [comment]
> I understand the VSTest task will generate code coverage data, but we have a very large codebase and a heavily optimized build process; we can't use the out-of-the-box VSTest task because it is not performant. What we want to do is publish the .trx/.coverage files after we run the tests ourselves. According to the documentation, "Publish Test Results" is the correct task for that.

Ah I missed that you were talking about the publish test results.  But I think it will not work with the vstest task either.  I personally have not tried but have you taken a look at https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops-2020 to use VSTest?

**Comment by mwelsh1118** [comment]
Thanks. We are aware of the parallel testing support, but there are still a few things we do that don't fit this model. For instance, we set up and tear down dedicated databases before running certain tests. We also start testing before our entire codebase is compiled. By starting low-level assembly tests before high-level assemblies are compiled, we get a significant performance boost.

**Comment by nadesu** [comment]
@v-pkoneti / @v-vnomula - pls take a look

**Comment by v-vnomula** [comment]
@mwelsh1118 Please make sure that .coverage and .trx files are present in the same folder so that PublishTestResults task will take care of uploading .coverage file to blob.

**Comment by mwelsh1118** [comment]
@v-vnomula We are using xUnit, so we have .xml result files that we upload via PublishTestResults. Are you saying this only works with MS Test/.trx results?

**Comment by gioce90** [comment]
Hi, I have resolved this using two different pipelines as described here: https://github.com/microsoft/vstest/issues/981#issuecomment-1034093540 
In this way I can achieve full and diff coverage. I think is what you are searching for.

**Comment by johnyrocks2014** [comment]
@mwelsh1118 Did you ever find a solution to this? 

I just figured since .coverage files are generated by “dotnet test” that it would work seamlessly but boy was I wrong.

I got the “convert to xml” when using the publish code coverage task.

**Comment by mwelsh1118** [comment]
We came up with a custom solution based on the dotnet-coverage tool:
https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage
