### ISSUE TITLE
Feature: Share cache across branches in a pipeline

### ISSUE THREAD

**Issue by bharathns** [microsoft/azure-pipelines-tasks#15097]
Type: Feature

Enter Task Name: Cache (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache?view=azure-devops / https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheV2)

**Environment**
Azure Pipelines (yml)
iOS project build
**Issue Description**
We have a pipeline which run builds for a large number of pipelines. Each branch ends up building a lot of artifacts like Pods repeatedly. Now we can cache these unnecessary builds of pods but the Cache@2 task is a spoil sport because it scopes to **pipeline** & **target branch** 

  - task: Cache@2
    displayName: Cache
    inputs:
      key: 'PodCache | "${{ parameters.solution }}" | "$(Agent.OS)" | Podfile.lock'
 
      path: ./cache

The problem for us the scoping for **target branch** is unnecessary the pods do not change between branches much caching should be allowed to scoped for pipeline alone(or at-least the choice).

I am sure you might have many reasons to have "target branch" but imagine a scenario where we do not build the target branch in a give pipeline. The caching will be of no use in this scenario because target branch never builds in the pipeline all the PRs which have cached the builds while never be used.

Now there is another scenario instead of a PR if we build a branch alone we are able to use the cache for further rebuilds(I guess this in the documentation already).
**I think the users should be given a choice to scope the cache with the target branch or without it. This would help reuse the builds and build less which leads reduce use of resources and build time reduction.**

Please consider this request.

Please do correct me if I am wrong in anyway.
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

There is another mention of this issue: 
https://github.com/microsoft/azure-pipelines-tasks/issues/12901#issuecomment-703927397

**Comment by kumaakh** [comment]
A typical scenario that I face is that a pull request adds new packages, triggers a build and passed acceptance criterion. A this point the branches "cache" has new packages. 
Now when I accept the pull request ideally I'd like to reuse the cache from the pull request branch. 

I saw @johnterickson 's [comment](https://github.com/microsoft/azure-pipelines-tasks/issues/12901#issuecomment-628739689) that sharing cache's can lead to an attack vector. But that is not the case when the cache was built on another branch on the same repository with only permissioned contributors. It is a useful feature IMHO

**Comment by VillSkog** [comment]
I would absolutely like an update for that as well. In it's current state, the caching is absolutely useless for our setup with short lived branches. I would consider it a deal breaker for us at the moment.

**Comment by viveknum** [comment]
true, its a feature ie is useless

**Comment by VillSkog** [comment]
This is still a valid use case and should be added to make caching useful for teams using [trunk based development](https://trunkbaseddevelopment.com/) with short lived branches ..

**Comment by viveknum** [comment]
yes totally agree with you without sharing cache across branches, it makes no diff in building features branches

**Comment by stodirascu** [comment]
### Big upvote

Dependencies usually change rarely between PR's, and it's the perfect use-case to reuse them across branches. We can always disambiguate them using cache keys if we want to. 

Microsoft, why the ignore?

**Comment by stodirascu** [comment]
This paragraph seems particularly interesting:
> ...and a job building a PR has read access to the caches for the PR's target branch (for the same pipeline), but cannot write (create) caches in the target branch's scope.

Does this mean multiple PR's in different points in time against the same branch will have access to the target branch cache? 

Another side question is, who **can** write to the cache in the target branch scope, if the PR job has readonly access?

**Comment by VillSkog** [comment]
> Another side question is, who **can** write to the cache in the target branch scope, if the PR job has readonly access?

It does sound interesting indeed. I guess the cache could be over-written when the branch is merged only.

**Comment by joshwright10** [comment]
I thought that I didn't understand this pipeline caching feature until I realised that it was related to this. I would love to see this updated.

**Comment by youennmerel** [comment]
I agree with this feature request. We work with feature branches & PR, the current branch-scoped cache system is almost useless in this context.

**Comment by pklejnowski** [comment]
Any update od workaround how to handle it?

**Comment by zpoynton** [comment]
I too am bumping this. With multiple branches of the same code base, both NuGet and NPM packages won't change much. This should be an option

**Comment by obrhoff** [comment]
Another bump

**Comment by knopa** [comment]
At least ability to manage scope would be really usefull

**Comment by stefankaufmann** [comment]
+1

**Comment by kumaakh** [comment]
OK we are completing 2 yrs of this feature request and  ~20 upvotes. what is required to reopen it ?
Wont it be better if authors just mark it as "wont fix" ?

**Comment by Shohoo** [comment]
+1

**Comment by Mahamed-Belkheir** [comment]
This is still required, a lot of teams do trunk based development, and the lack of pipelines features are making us look into migrating off the platform, we're now looking at remote caching features which would make that migration easier to do in the future too.

**Comment by WieFel** [comment]
+1

**Comment by harrydobbs** [comment]
+1

**Comment by rstencel** [comment]
+1

**Comment by bvobart** [comment]
+1

Caching is now essentially useless unless your team does everything on one branch. Short-lived feature branches at the moment get little to no benefit from caching, until this finally gets implemented...

I'm tagging everyone who has touched the Cache task's code, in the hope that any of them still hold any authority in re-opening this issue, sharing their professional opinion and getting it implemented: @anatolybolshakov @EzzhevNikita @csigs @DaniilShmelev @kuleshovilya @rumyax 

Also tagging @johnterickson as he previously [commented](https://github.com/microsoft/azure-pipelines-tasks/issues/12901#issuecomment-628739689) on an older duplicate of this issue. Reiterating @kumaakh's comment about that comment that I wholeheartedly agree with:

> I saw @johnterickson 's https://github.com/microsoft/azure-pipelines-tasks/issues/12901#issuecomment-628739689 that sharing cache's can lead to an attack vector. But that is not the case when the cache was built on another branch on the same repository with only permissioned contributors. It is a useful feature IMHO

Would any contributor please care to elaborate what the holdup is regarding cache sharing across branches within the same repository? It's a 5 year old issue, can we please get it on a roadmap for implementation? Thanks!

**Comment by fibsifan** [comment]
Hello everybody who commented and upvoted after this issue was already closed: please note that there is also #22222 (which has little to no interaction and none of all the good arguments).
