### ISSUE TITLE
UseDotNet@2 Failed while getting version 5.0.x

### ISSUE THREAD

**Issue by abdullah248** [microsoft/azure-pipelines-tasks#15105]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  UseDotNet@2 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

UseDotNet@2 Failed while getting version 5.0.203 from channel 5.0 with error: {}

The task failed in a linux environment.

Yaml of task:
``` Yaml
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    useGlobalJson: true
```

Output of Task

```
Starting: Use .NET Core sdk
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.184.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
##[error]Failed while getting version 5.0.203 from channel 5.0 with error: {}
No matching sdk version could be found for specified version: 5.0.203 Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
Version 5.0.203 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 5.0
##[error]Failed while getting version 5.0.203 from channel 5.0 with error: {}
##[error]sdk version matching: 5.0.203 could not be found
Finishing: Use .NET Core sdk
```

We noticed this issue a few days ago initially and after re running the pipeline it usually succeeded on the second retry. We noticed that there was an announcement that this should be resolved https://github.com/dotnet/announcements/issues/192 4 days ago, but we were seeing this issue again in our pipelines as of yesterday.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by vineetmimrot** [comment]
Are you still getting this issue, with `5.0.x` we can get `5.0.400` sdk version installed via `usedotnet` task

**Comment by qcb111** [comment]
Hi, I'm still getting the same issue.
`useGlobalJson: true` gives this error. 
If I use `version: '5.0.x'` instead, then it works.

**Comment by bishal-pdMSFT** [comment]
@naga-bandi / @v-abajaj as new owners of the task

**Comment by VSJames** [comment]
I'm getting this issue too, I'd like to have a single global.json file to manage across many build tasks instead of specifying the version in the task parameters... However I can't match to the latest 7.0.x version as the logs seem to suggest no version of 7 is available? My global.json is:

```
{
    "sdk": {
        "version": "7.0.0",
        "rollForward": "latestFeature",
        "allowPrerelease": true
    }
}
```

and my UseDotNet task is

```
- task: UseDotNet@2
  displayName: 'Use correct .NET SDK'
  inputs:
    packageType: sdk
    useGlobalJson: true
    installationPath: $(Agent.ToolsDirectory)/dotnet
```

The logs state:

```
Version 7.0.0 could not be found in its channel, will now search in adjacent channels.
Searching for version in channel 7.0
##[error]sdk version matching: 7.0.0 could not be found
```

**Comment by ChristoWolf** [comment]
I'll also check again ASAP.

**Comment by ChristoWolf** [comment]
Bump.
