### ISSUE TITLE
PowerShell on Target Machines task on GitHub Actions. 

### ISSUE THREAD

**Issue by vinaysandela** [microsoft/azure-pipelines-tasks#15116]
Looking for similar task on GitHub Actions. 
PowerShell on Target Machines task
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines?view=azure-devops

Please suggest

**Comment by DaniilShmelev** [comment]
Hi @vinaysandela! This is a repo for Azure Pipelines tasks, we don't support Github Actions.
One of the members of Github Actions team responded that there is no official action for executing powershell on remote machines. You could try searching for community action [here](https://github.com/marketplace?type=actions&query=).
Also, I'd suggest looking towards running commands through ssh.
Hope this helps. Closing the issue as external.
