### ISSUE TITLE
AzureCLI service connection with multiple subscriptions doesn't select configured subscription

### ISSUE THREAD

**Issue by JoasE** [microsoft/azure-pipelines-tasks#15129]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLI

## Environment
- Server - Azure Pipelines
    - Account name: akzonobelpc
    - Team project name: Color-IT
    - Build definition name/build number: AkzoNobel.CustomerDataOnline.CustomerColors 20210806.6

- Agent - Hosted
    - agent queue name: Azure Pipelines

## Issue Description

Task: AzureCLI@2
Service Connection: Azure Resource Manager using service principal (manual)

I have a Azure Resource Manager using service principal (manual) service connection that has access to multiple subscriptions:
![image](https://user-images.githubusercontent.com/32096708/128511322-4c875a5f-823b-41a7-889f-87e475d77c9b.png)

When I use this in the AzureCLI@2 task, it selects the wrong subscription:
![image](https://user-images.githubusercontent.com/32096708/128511748-a6e1f3c6-89d4-4ac6-ab57-b23453cbd29a.png)
![image](https://user-images.githubusercontent.com/32096708/128511813-dd784c47-ff7d-4c8b-96f3-c647e3d3e4f9.png)

You can see it executes `account set --subscription 28` where it should execute `account set --subscription 3b`

The last line of the outut it the result of echo $(serviceConnection) which is the id of the service connection in the screenshot above.

### Task logs
[logs.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6945597/logs.txt)

**Comment by vineetmimrot** [comment]
@JoasE Can you please double-check whether you are using same SPN service endpoint that you have created in the Az CLI task?

**Comment by giulianisanches-inbev** [comment]
I'm having exactly this issue. Is it possible to reopen this bug ?
