### ISSUE TITLE
Deployment Task Stop Website powershell 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' successfully stopped site with Exit code 1

### ISSUE THREAD

**Issue by ChrisHout** [microsoft/azure-pipelines-tasks#15127]
One of the tasks in the deployment is 'Stop website'. It stops the website successfully, the problem is the exit code 1.
It worked before, only after a new antivirus-scanner this error occured every day. Not sure if this is related to this error.
On another server this steps works without an issue. This server also has the new antivirus -scanner installed.

##[section]Starting: Stop website
==============================================================================
Task         : IIS web app manage
Description  : Create or update websites, web apps, virtual directories, or application pools
Version      : 0.5.15
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group
==============================================================================
##[command]"C:\Windows\system32\inetsrv\appcmd.exe" stop site /site.name:"Production"
"Production" successfully stopped
##[error]Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\vstsagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\vstsagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.15\IISWebAppManagementOnMachineGroup.ps1'''))"'.
##[section]Finishing: Stop website

**Comment by DenisRumyantsev** [comment]
@nadesu, could you please take a look at this ticket since it relates to your area?

**Comment by nadesu** [comment]
@chshrikh - pls review this

**Comment by chshrikh** [comment]
@ChrisHout can you please share the detailed debug logs for task  / pipeline execution

**Comment by ChrisHout** [comment]
[tasklog_11.log](https://github.com/microsoft/azure-pipelines-tasks/files/6967023/tasklog_11.log)

This is the debug tasklog with some personal stuff removed.

**Comment by ChrisHout** [comment]
@DenisRumyantsev @nadesu @chshrikh

Do you need more information?

**Comment by AmrutaKawade** [comment]
@ChrisHout Can you set `system.debug = true` and share logs

**Comment by ChrisHout** [comment]
Hi guys, the problem is solved. On Server3 the script was running correct but on Server2 the result had an exit code 1.
So I checked the Powershell versions: 
Server2 - v3.6.9600.17415 (2014)
Server3 - v10.0.14409.1005 (2016)
I don't know why the error showed up because I didn't changed the script. After updating Server2 with the new Powershell version it finally worked again. Thanks for your time.

Regards,
Chris
