### ISSUE TITLE
PublishSymbolsV2 task - Doesn't Support TLS 1.2

### ISSUE THREAD

**Issue by JasonWhall** [microsoft/azure-pipelines-tasks#15139]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishSymbolsV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: N/A

    - If using private agent, provide the OS of the machine running the agent and the agent version: N/A

## Issue Description

Receiving the following message when TLS 1.0 and 1.1 is disabled on a windows agent:
```
Exception occurred: System.Net.WebException
##[error]The underlying connection was closed: An unexpected error occurred on a receive.
```

I believe this is caused by not setting `[Net.ServicePointManager]::SecurityProtocol` in the powershell script to allow use of TLS 1.2. There is no way to do this currently in this task.

**Comment by JasonWhall** [comment]
Not stale, still an issue.

**Comment by scp-mb** [comment]
The TLS 1.0 and 1.2 brownout today has highlighted this as still an issue.

@carl-tanner The changes have been approved back in December, are they being merged and a new version pushed any time soon?

**Comment by ocitrev** [comment]
This is now a blocking issue, Azure DevOps now requires TLS1.2 on all connections.

https://devblogs.microsoft.com/devops/deprecating-weak-cryptographic-standards-tls-1-0-and-1-1-in-azure-devops-services/

This is causing pipelines to fail.
Can we have a resolution as soon as possible ?

As a workaround, I used the PoweSshell script referenced here: https://github.com/microsoft/azure-devops-tls12 and applied the suggested mitigations.

**Comment by carl-tanner** [comment]
This should be deployed in symbol publish tasks >= 2.199.  I checked and 2.202 is currently deployed to production.  Can you verify the version of the publish task you are using?

**Comment by ocitrev** [comment]
I did update the agent to version 2.202.0 earlier today and I still got the error before I did the registry changes.

```
Starting: Publish symbols to \\<redacted>\symbols
==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : 2.202.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/index-sources-publish-symbols
==============================================================================
Found 626 files.
##[error]Exception calling "LocationForAccessMapping" with "3" argument(s): "TF400324: Team Foundation services are not available from server [https://dev.azure.com/<redacted>/.](https://dev.azure.com/<redacted>/)
Technical information (for administrator):
  The underlying connection was closed: An unexpected error occurred on a send."
```

**Comment by scp-mb** [comment]
@carl-tanner Also still seeing the same issue, agent version is `2.200.2` but the publish symbols task seems to be `2.198.0` on a run from a few hours ago

```
==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/index-sources-publish-symbols
==============================================================================
Found 6 files.
Symbol Request Name = <redacted>
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
##[error]The underlying connection was closed: An unexpected error occurred on a send.
```

**Comment by nuzolx** [comment]
@carl-tanner Same issue with agent version 2.204.0.

`
**==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : **2.203.0**
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/index-sources-publish-symbols
==============================================================================**

Found 1 files.
Skipping indexing.
Symbol Request Name = ####
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
##[error]The underlying connection was closed: An unexpected error occurred on a send.
`

**Comment by StevenDevooght** [comment]
PR https://github.com/microsoft/azure-pipelines-tasks/pull/15140 was supposed to fix this issue. However `Add-Tls12InSession` is never called. Is it possible that the following statements are missing?

```
Import-Module $PSScriptRoot/../TlsHelper_
Add-Tls12InSession
```

**Comment by v-kevinwong** [comment]
Seeing this issue with 2.210

**Comment by StevenDevooght** [comment]
We are still facing the same issue with version 2.210
```
==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : 2.210.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/index-sources-publish-symbols
==============================================================================
Found 2 files.
Unable to index one or more source files for symbols file 'E:\agent\_work\400\a\Release\net461\Infohos.ParserBuilder.pdb'.
Unable to index one or more source files for symbols file 'E:\agent\_work\400\a\Release\netstandard2.0\Infohos.ParserBuilder.pdb'.
Symbol Request Name = integraties/parserbuilder-ci/20221215.5/72826/ef65a9d8-5df8-4573-b9ff-c5cbf44323cf
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
Exception occurred: System.Net.WebException
```

**Comment by carl-tanner** [comment]
Please enable debug messages for your pipeline to include the actual error stacks.  It's unclear from the log what is failing to connect.

Also please include a way to reproduce the problem. A significant number of teams within Microsoft use this task on a daily basis and do not receive these errors. If you can provide instructions for how to set up a pipeline agent to reproduce this problem we can take a look.

There are instructions on learn.microsoft.com for enabling TLS1.2 as the default for processes running on windows. Is there a reason this doesn't work for you?

**Comment by StevenDevooght** [comment]
We switched our build to use the Microsoft hosted agents. I can confirm the the publish task works flawlessly. There must be something off with our in-house buildservers.

**Comment by tallalkazmi** [comment]
> > This is now a blocking issue, Azure DevOps now requires TLS1.2 on all connections.
> > https://devblogs.microsoft.com/devops/deprecating-weak-cryptographic-standards-tls-1-0-and-1-1-in-azure-devops-services/
> > This is causing pipelines to fail. Can we have a resolution as soon as possible ?
> > As a workaround, I used the PoweSshell script referenced here: https://github.com/microsoft/azure-devops-tls12 and applied the suggested mitigations.
> 
> For anyone landing here, still having the same issue, the solution above solves the issue.

I spent hours looking for a solution before I read this. Thanks for pointing out the solution.
