### ISSUE TITLE
VSTest resolving vsTestVersion 16.0 to VS2017

### ISSUE THREAD

**Issue by luizgrs** [microsoft/azure-pipelines-tasks#15134]
**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: VsTest

## Environment
- Server: Azure Pipelines
- Agent - Hosted or Private:  private (windows, 2.186.1)
    
## Issue Description

Task uses vstest.console.exe 15.9.1 from VS2017 Enterprise folder when `vsTestVersion` is 16.0.

Task uses vstest.console.exe  16.5.0 from VS2019 Build Tools folder when `vsTestVersion` is `latest`.

This build server has VS 2017 Enterprise and VS 2019 Build Tools installed.

vstest is preceded by a VSBuild task which takes the very same parameter and resolves to vs2019 for both values.

### Task logs

Task         : Visual Studio Test
Dersion      : 2.170.1

**vsTestVersion = 16.0**

##[debug]vsTestVersion=16.0
VisualStudio version selected for test execution : 16.0
##[debug]vsTestVersion=16.0
##[debug]which 'D:\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]found: 'D:\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]which 'D:\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]found: 'D:\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
Attempting to find vstest.console from a visual studio installation with version [15.0,17.0).
##[debug]D:\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe arg: -version [15.0,17.0) -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -property installationPath
##[debug]exec tool: D:\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe
##[debug]arguments:
##[debug]   -version
##[debug]   [15.0,17.0)
##[debug]   -latest
##[debug]   -products
##[debug]   *
##[debug]   -requires
##[debug]   Microsoft.VisualStudio.PackageGroup.TestTools.Core
##[debug]   -property
##[debug]   installationPath
##[debug]Visual Studio 15.0 or higher installed path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise

**vsTestVersion = 'latest'**

##[debug]vsTestVersion=latest
VisualStudio version selected for test execution : latest
##[debug]vsTestVersion=latest
##[debug]Searching for latest Visual Studio.
##[debug]which 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]found: 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]which 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]found: 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
##[debug]e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe arg: -version [16.0,17.0) -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -property installationPath
##[debug]exec tool: e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe
##[debug]arguments:
##[debug]   -version
##[debug]   [16.0,17.0)
##[debug]   -latest
##[debug]   -products
##[debug]   *
##[debug]   -requires
##[debug]   Microsoft.VisualStudio.PackageGroup.TestTools.Core
##[debug]   -property
##[debug]   installationPath
Attempting to find vstest.console from a visual studio build tools installation with version [16.0,17.0).
##[debug]which 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]found: 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]which 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]found: 'e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe'
##[debug]e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe arg: -version [16.0,17.0) -latest -products * -requires Microsoft.VisualStudio.Component.TestTools.BuildTools -property installationPath
##[debug]exec tool: e:\agent2\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\vswhere.exe
##[debug]arguments:
##[debug]   -version
##[debug]   [16.0,17.0)
##[debug]   -latest
##[debug]   -products
##[debug]   *
##[debug]   -requires
##[debug]   Microsoft.VisualStudio.Component.TestTools.BuildTools
##[debug]   -property
##[debug]   installationPath
##[debug]Build tools installed path: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

**Comment by adityashahms** [comment]
This bug will be fixed with this PR : https://github.com/microsoft/azure-pipelines-tasks/pull/17858
