### ISSUE TITLE
Azure DevOps Junit Tests results only shows first failure

### ISSUE THREAD

**Issue by ajannasch** [microsoft/azure-pipelines-tasks#15130]
*Question, Bug, or Feature?**  
*Type*: Question or Bug

**Enter Task Name**: Publish Test Results task
## Environment
  
    - TFS on-premises: Version 17.143.28621.4 (Azure DevOps2019)
  
    - Private Hosted Agent: Windows Server 2016

## Issue Description
TestCase results only show first failure in the Build - Tests UI view in  Azure DevOps, even though there are multiple failures in the same file.
Running Flake8 against our Python code. Convert the Flake8 results to a output.xml file. Convert the output.xml file into Flake8junit.xml
Here is an extract of the Flake8junit.xml file:

```
<testcase name=".\folder\folder\clustering\clustering.py">
		<failure file=".\folder\folder\clustering\clustering.py" line="30" col="22" message="W605 invalid escape sequence '\S'" type="flake8 W605">30:22 W605 invalid escape sequence '\S'</failure>
		<failure file=".\folder\folder\clustering\clustering.py" line="30" col="41" message="W605 invalid escape sequence '\S'" type="flake8 W605">30:41 W605 invalid escape sequence '\S'</failure>
		<failure file=".\folder\folder\clustering\clustering.py" line="87" col="56" message="E721 do not compare types, use 'isinstance()'" type="flake8 E721">87:56 E721 do not compare types, use 'isinstance()'</failure>
	</testcase>
```

Only the first failure is shown in the AzureDevOps Tests UI view.
![image](https://user-images.githubusercontent.com/1413047/128534908-93a7d26e-3933-45ed-bf03-9a1452ca1952.png)

Is there any way to make all failures for a testcase show in the UI?

**Comment by DenisRumyantsev** [comment]
@SadagopanRajaram, could you please take a look at this ticket since it relates to your area?
