### ISSUE TITLE
VSTestV2 codeCoverageEnabled parameter set to false has no effect if runsettings file has code coverage enabled

### ISSUE THREAD

**Issue by hollowdrutt** [microsoft/azure-pipelines-tasks#15153]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTestV2

## Environment
Azure Pipelines
Private Agent running on VM in Azure
OS: Windows Server 2016
Agent version: 2.187.2

## Issue Description

This is related to [Publishing code coverage results with VSTest task is slow or fails with timeout](https://github.com/microsoft/azure-pipelines-tasks/issues/14304). Since I still have the same problem I decided to disable publishing the code coverage but then I ran into the issue that the test task ignores the publishRunAttachments parameter, which is described in the issue [VSTest publishRunAttachments has no effect on what is published ](https://github.com/microsoft/azure-pipelines-tasks/issues/13798) which was closed without any response.
I then tried setting the parameter codeCoverageEnabled to false, but it also has no effect.

As can be seen in the log file, codeCoverageEnabled is set to false, but code coverage is then enabled for the test runner because of the runsettings file and the code coverage is published.

### Task logs

```
Starting: VSTest
==============================================================================
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.170.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
```
...
```
Run in parallel : false
Run in isolation : false
Path to custom adapters : null
Other console options : null
Code coverage enabled : false
Diagnostics enabled : false
SystemVssConnection exists true
Run the tests locally using vstest.console.exe
=======================================================
```
...
```
**************** Starting test execution *********************
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\agent\_work\_temp\l3omqgp4icm.tmp"
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe  
```
...
```
/Settings:"C:\agent\_work\_temp\0xsdgw1ox01.tmp.runsettings"
/EnableCodeCoverage
/Logger:"trx"
/TestAdapterPath:"C:\agent\_work\13\s
/Settings:"C:\agent\_work\_temp\0xsdgw1ox01.tmp.runsettings"
```
...
```
Results File: C:\agent\_work\_temp\TestResults\tests.trx
Attachments:
  C:\agent\_work\_temp\TestResults\tests.coverage
```
...
```
Published test results: 1096
Publishing Attachments: 2
Completed TestExecution Model...
```

**Comment by v-pkoneti** [comment]
Hi @hollowdrutt 

This is by design and you need to remove form run settings and disable from vstest task to stop code coverage.
