### ISSUE TITLE
Trigger Azure Devops Pipeline when a repository commit happens in Github

### ISSUE THREAD

**Issue by DineshNataraj** [microsoft/azure-pipelines-tasks#15158]
Hello Team,
I have my organization Github and using Azure Devops for pipeline. I need to build my Azure Devops pipeline if a new commit is happened, I need to trigger my Pipeline automatically.
I have used Pipeline->Triggers->Continuous Integration configuration and the build is not getting triggered automatically.
Could you please help to get my webhook enabled with Github and Azure Devops ?

**Comment by anatolybolshakov** [comment]
Hi @DineshNataraj could you please raise a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?
This repo is mostly for pipeline tasks - let me close this ticket here since it's not related to the tasks itself.
