### ISSUE TITLE
Is it PublishCodeCoverageResults@2 available at Azure DevOps with Microsoft-hosted agents?

### ISSUE THREAD

**Issue by berviantoleo** [microsoft/azure-pipelines-tasks#15160]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: PublishCodeCoverageResults

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
- Agent - Hosted
- Build Link: https://dev.azure.com/berviantoleo/Tweety/_build/results?buildId=3594&view=results

## Issue Description

I want to confirm, is it PublishCodeCoverageResults@2 available at Azure DevOps? Since I meet an error that said not found the task.

![image](https://user-images.githubusercontent.com/15927349/129531432-1c38fc50-9608-46f4-8ca0-f5d8ef8858e0.png)

Since I check [the documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops) start to mention the parameters that will be used for V2.

Another issue about the documentation was already raised [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues/11183).

* If the Task is not available yet, I will try to send PR for reverting the docs to V1 params.
* If the Task will be available, I will wait and send the PR to update into the V2 task.

### Error logs

![image](https://user-images.githubusercontent.com/15927349/129531432-1c38fc50-9608-46f4-8ca0-f5d8ef8858e0.png)

**Comment by DenisRumyantsev** [comment]
Hi @berviantoleo, currently, the PublishCodeCoverageResults@2 task (the second version) has not been published, so it is not available in Azure DevOps. Besides, there are no plans to publish it.

**Comment by DenisRumyantsev** [comment]
@berviantoleo, the documentation was updated, thanks! Please check it out [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops).

**Comment by berviantoleo** [comment]
Thanks. I think my issue can be closed now.

**Comment by simontom** [comment]
This doc statement makes no sense

![image](https://user-images.githubusercontent.com/1636523/142437320-7f2326d2-debe-49fd-b378-4e0b8b06155a.png)

**Comment by gioce90** [comment]
> This [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops) statement makes no sense
> 
> ![image](https://user-images.githubusercontent.com/1636523/142437320-7f2326d2-debe-49fd-b378-4e0b8b06155a.png)

Indeed, this makes no sense: from [Publish Code Coverage Results task - FAQ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#is-code-coverage-data-merged-when-multiple-files-are-provided-as-input-to-the-task-or-multiple-tasks-are-used-in-the-pipeline) :

> At present, the code coverage reporting functionality provided by this task is limited and it does not merge coverage data. If you provide multiple files as input to the task, only the first match is considered.

**Comment by sj-net** [comment]
Any plans to release V2 ? There is one bug in report generator and they have fixed in latest version. We are seeing wrong coverage because of this issue. 


https://github.com/danielpalme/ReportGenerator/issues/558

**Comment by sj-net** [comment]
A temporary work around I had to do is 

1. Use report generator task or install it as global and generate a report that you want. 
2. In PublishCodeCoverageResults@1 task, add option for `reportDirectory` and ensure that points towards the directory that contains HTML files. 

Note: Unfortunately the JS related features like expand all , collapse all etc will be stripped down in your coverage tab.

**Comment by vinayakmsft** [comment]
We have the new Publish Code Coverage V2 task live - https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines
