### ISSUE TITLE
Azure powershell task v5 with powershell core causes misbehavior for variables named $endpoint

### ISSUE THREAD

**Issue by microjay** [microsoft/azure-pipelines-tasks#15163]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure Powershell

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
skype, domoreexp, office, e.t.c

- Agent - Hosted or Private:  Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:  Windows 1809

## Issue Description

[Include task name(s), screenshots and any other relevant details] Azure Powershell  
![image](https://user-images.githubusercontent.com/44008079/129606852-030f4077-fc4a-4a58-9d4d-1b387f2f554c.png)
Azure powershell 5 task with powershell core enabled seems to have a reserved variable named $endpoint. This made scripts that we were manipulating in Azure powershell 3 before migrating to Az start to fail as the $endpoint instead of representing a traffic manager  endpoint was being cast to a string, This made the properties unavailable for manipulation and so referencing name property in script fails

![image](https://user-images.githubusercontent.com/44008079/129609609-d1207399-3e9b-43e5-9d7f-f7dea8f00bb5.png)

Script that generates the error(that worked before moving to powershell 5 with Az and powershell core  looks like)
$tm = Get-AzTrafficManagerProfile -Name $ProfileName -ResourceGroupName $ResourceGroupName
if (!$tm)
{
    Write-Error "Could not find Traffic Manager $ProfileName"
    exit 1
}

foreach ($endpoint in $tm.Endpoints)  # -> endpoint gets casted to type string here 
{
    if ($endpoint.Name -notlike "$DeploymentUnit-*")
    {
        Write-Output "Disabling $($endpoint.Name)"
        Disable-AzTrafficManagerEndpoint -Name $endpoint.Name -Type ExternalEndpoints -ProfileName $ProfileName -ResourceGroupName $ResourceGroupName -Force # ->$endpoint.Name is blank
    }
}

Script that works looks like
$tm = Get-AzTrafficManagerProfile -Name $ProfileName -ResourceGroupName $ResourceGroupName
if (!$tm)
{
    Write-Error "Could not find Traffic Manager $ProfileName"
    exit 1
}
foreach ($curEndpoint in $tm.Endpoints) # -> endpoint is correctly typed 
{
    if ($curEndpoint.Name -notlike "$DeploymentUnit-*")
    {
        Write-Output "Disabling $($curEndpoint.Name)"
        Disable-AzTrafficManagerEndpoint -Name $curEndpoint.Name -Type ExternalEndpoints -ProfileName $ProfileName -ResourceGroupName $ResourceGroupName -Force #-> $curEndpoint.Name resolves properly
    }
}
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by chshrikh** [comment]
1. can you try to run the script directly form PS promt where Azure PS 5 is available 
2. Can you share the detailed debug task logs

**Comment by PhilipsonJoseph** [comment]
@microjay The variable **endpoint** is used internally so it causing an error ,we missed to mention it in our documentation .Please use an different variable name. We will update the documentation soon .
