### ISSUE TITLE
Task folder structure in this repo, does not match MS documentation for multi-version tasks

### ISSUE THREAD

**Issue by msaxbury** [microsoft/azure-pipelines-tasks#15177]
The folder layout for multi-version tasks in this project, does not match the MS documentation at this link:

https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops-2020#multiple-versions-layout

**Comment by anatolybolshakov** [comment]
Hi @msaxbury there is a source code of in-the-bix tasks in this repo - although the docs your provided describe pipeline extension layout.
Please let us know if you have any further questions.

**Comment by msaxbury** [comment]
What is the difference between these "in-the-box tasks" and "pipeline extensions"?

**Comment by anatolybolshakov** [comment]
@msaxbury in-the-box tasks are default tasks being shipped with Azure DevOps. There is a different build process.
For more questions regarding building of custom tasks - I would suggest to create a ticket on https://developercommunity.visualstudio.com/search?space=21 for any related questions.
