### ISSUE TITLE
InstallSSHKeyV0 does not support loading SSH key from Azure Keyvault

### ISSUE THREAD

**Issue by jeahyoun** [microsoft/azure-pipelines-tasks#15172]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Feature

**Enter Task Name**: InstallSSHKeyV0

## Environment
- Server - Azure Pipelines

- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
         - Account: ceapex
         - Project: Engineering/docs-ui
         - Hosted Agent
         - Build Definition Name: docs-ui CI

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: docs-ui CI

## Issue Description

We have a requirement to manage SSH keys in Azure Keyvault. Managing keys this way makes key rotation easier to manage and allows for delegation to other teams. However, the InstallSSHKey task only seems to support loading the SSH key from secure files in Azure Devops.

It is currently not possible to use the Keyvault task in conjunction with the InstallSSHKey task, since the Keyvault task is designed to write secrets directly to task variables. The InstallSSHKey task cannot read a private key from a task variable.

Attempting to do this manually with scripts (pulling a Github private key from keyvault, formatting it correctly and writing to disk, generating a public key, and manually adding the private key with ssh-add, and adding an entry into known_hosts) results in an SSH publickey denied error when we attempt to open an SSH connection to the remote server.

### Task logs

Pull request is here: https://dev.azure.com/ceapex/Engineering/_git/docs-ui/pullrequest/255587

Zip file attached with build log, build definition file, and custom SSH install script (modified from the code in InstallSSHKey).

[devops-ssh-info.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7009167/devops-ssh-info.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
debug1: Will attempt key: /c/Users/VssAdministrator/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /c/Users/VssAdministrator/.ssh/id_rsa ED25519 SHA256:gcZv0U5pE4OLPF8LPvi1apCt9FhcFwBk2YLUsn9t3qQ
debug1: Server accepts key: /c/Users/VssAdministrator/.ssh/id_rsa ED25519 SHA256:gcZv0U5pE4OLPF8LPvi1apCt9FhcFwBk2YLUsn9t3qQ
debug1: read_passphrase: can't open /dev/tty: No such device or address
debug1: Trying private key: /c/Users/VssAdministrator/.ssh/id_dsa
debug1: Trying private key: /c/Users/VssAdministrator/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/VssAdministrator/.ssh/id_ecdsa_sk
debug1: Trying private key: /c/Users/VssAdministrator/.ssh/id_ed25519
debug1: Trying private key: /c/Users/VssAdministrator/.ssh/id_ed25519_sk
debug1: Trying private key: /c/Users/VssAdministrator/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).
##[error]Bash exited with code '255'.
```

**Comment by cbandera** [comment]
I can confirm the issue. I can reproduce the issue by using the InstallSSHKey@0 task with secret variables ([as recommended here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops#usage-and-best-practices)) in a pipeline.
- When the values are configured as secrets directly in the variable group inside the pipeline library then everything works fine
- When the variable group is linked to an azure key vault, I get different kinds of errors. E.g. 
`##[error]Could not get the base64 portion of the public SSH key.`

**Comment by cbandera** [comment]
This might also be a duplicate or at least related to #11854 and #14971

**Comment by cobbled-street** [comment]
I am not sure if this is still an issue, however there is a workaround. 
I also had the same issue because the InstallSSHKey@0 runs as a pre job, when the password was downloaded using a resource group with with key vault access,  it runs after the pre job, so the SSH has already run with no secret.

The answer is to use  the AzureKeyVault@2 task with RunAsPreJob: true,  to download the secrets.
This task will run and download the secrets as a pre job  before the  InstallSSHKey@0 task. if it is put higher in the YAML.

**Comment by stumt** [comment]
Would like to see support added to InstallSSHKey task to be able to load the key from a secret variable vs having to rely on the secure file. The secure file method is not easy to manage across multiple projects within an ADO organization.
