### ISSUE TITLE
SqlAzureDacpacDeploymentV1 doesn't allow to connect to a Synapse dedicated pool

### ISSUE THREAD

**Issue by ydaponte** [microsoft/azure-pipelines-tasks#15181]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account name: ysantos
Project name: edl
Build definition name: cd-edl-parking-sensor
Build number: #20210820.2

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-FSG8LJUQ620'
Current agent version: '2.190.0'

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

When writing a yml file to run on Az DevOps pipelines with the SqlAzureDacPacDeploymentV1 we are unable to run it with a server pointing to a Synapse dedicated pool due to a difference in the naming convention.
SQL DB DNS naming convention(*.database.windows.net) 
Synapse DNS naming convention(*.sql.azuresynapse.net)

When creating a Dacpac project in ssdt we are able to connect and run into synapse dedicated pool. There is no reason why the same should not be possible for Synapse dedicated pools. Just the naming convention needs to be accepted while writing the task.

### Task logs

##[debug]System.Management.Automation.RuntimeException: Server name '$(synapsesqldedendpoint)' is not in the correct format. Use a fully qualified domain name format like 'yyy.database.windows.net'Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

##[error]Server name '$(synapsesqldedendpoint)' is not in the correct format. Use a fully qualified domain name format like 'yyy.database.windows.net'Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

##[debug]Processed: ##vso[task.logissue type=error]**Server name '$(synapsesqldedendpoint)' is not in the correct format. Use a fully qualified domain name format like 'yyy.database.windows.net'**Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
##[debug]Processed: ##vso[task.complete result=Failed]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
##[error]Server name '$(synapsesqldedendpoint)' is not in the correct format. Use a fully qualified domain name format like 'yyy.database.windows.net'Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-

**Comment by PhilipsonJoseph** [comment]
@ydaponte  Could you please share the value for **synapsesqldedendpoint** variable. Also, Please provide a complete logs by enabling **System.debug**

**Comment by asaneh** [comment]
# ##11905 #15285 #16051 #16033
