### ISSUE TITLE
NuGet and package tasks - migrate to Node 10

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-tasks#15186]
We need to migrate following to Node 10 - since Node 6 will be removed soon from agent:
-  NuGetCommandV2
-  NuGetInstallerV0
-  NuGetPublisherV0
-  NuGetRestoreV0
-  NuGetToolInstallerV0
-  NuGetToolInstallerV1
- TwineAuthenticateV0
- TwineAuthenticateV1
- UniversalPackagesV0

Related parent issue - #15183

**Comment by anatolybolshakov** [comment]
@phil-hodgson @johnterickson @animania4ka could you please take a look?

**Comment by phil-hodgson** [comment]
Hi @anatolybolshakov. What are the changes required here? The parent item (#15183) doesn't give a lot of detail.

Are there any example PRs for other tasks that have already addressed the issue?

**Comment by anatolybolshakov** [comment]
@phil-hodgson yes, here are several examples of such changes:
https://github.com/microsoft/azure-pipelines-tasks/pull/14195
https://github.com/microsoft/azure-pipelines-tasks/pull/14141

The main requirement is to update task execution handler from "Node" to "Node10", and make task to be compatible with Node 10 - let me share details internally also - since we've already have some how-to page for it.

**Comment by azchohfi** [comment]
Any updates on this? We just started to get a warning in our builds, specifically about the NuGetToolInstallerV1 task.
