### ISSUE TITLE
AzureIoTEdgeV2 - migrate to Node 10

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-tasks#15184]
We need to migrate AzureIoTEdgeV2 to Node 10 - since Node 6 will be removed soon from agent.
Related parent issue - https://github.com/microsoft/azure-pipelines-tasks/issues/15183

**Comment by anatolybolshakov** [comment]
@marianan @mhshami01 could you please take a look?

**Comment by marianan** [comment]
thanks @anatolybolshakov , I added this work item to our backlog. When do you expect Node 6 support to be removed from the agent?

**Comment by anatolybolshakov** [comment]
@marianan thanks! We don't have exact timeline at the moment, but I would say that it could be during the next 1-2 months.

**Comment by cindydeng1998** [comment]
Hello @anatolybolshakov Here is the PR (https://github.com/microsoft/azure-pipelines-tasks/pull/15300) to approve this update, please let us know if there is anything else we need to do. Thanks!

**Comment by anatolybolshakov** [comment]
@cindydeng1998 thanks! Let us take a look

**Comment by cindydeng1998** [comment]
@anatolybolshakov do you know what the ETA is for publishing this update? Thanks!

**Comment by anatolybolshakov** [comment]
Hi @cindydeng1998 we are reviewing it at the moment, will complete it today or tomorrow - after that it should be rolled out with the next release.

**Comment by cindydeng1998** [comment]
@anatolybolshakov sorry to bother you again, but do we have an ETA on when the deployment will happen? In general, what is the release cadence for these kinds of updates for future reference? Thank you so much

**Comment by anatolybolshakov** [comment]
Closing since change for this task has been rolled out.
