### ISSUE TITLE
Script failed with error: Error: The process '/usr/bin/bash' failed because one or more lines were written to the STDERR stream

### ISSUE THREAD

**Issue by radulacatus** [microsoft/azure-pipelines-tasks#15180]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLIV1
(Version: 1.164.0)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
- Agent name: 'Hosted Agent'
- Agent machine name: 'fv-az86-569'
- Current agent version: '2.190.0'
- Ubuntu
- 20.04.2
- LTS
- Environment: ubuntu-20.04
- Version: 20210816.1
- Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210816.1/im
- Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F2021081
- 1.0.0.0-master-20210802-2
- Current image version: '20210816.1'
- Agent running as: 'vsts'

## Issue Description

Our pipelines started failing with the error: "Script failed with error: Error: The process '/usr/bin/bash' failed because one or more lines were written to the STDERR stream".

In the logs we see azure cli command started logging a Warning that was previously Info

We tried the same tasks/scripts on different machines and we pinpointed the issue on the latest image version of Ubuntu 20.04
**Version: 20210816.1**

### Task logs
az aks get-credentials  --resource-group <resource-group> --name <cluster-name> --overwrite-existing --admin

Output ubuntu-20.04 version 20210816.1
WARNING: Merged "<cluster-admin>" as current context in /home/vsts/.kube/config

Output ubuntu-20.04 version 20210810.1
Merged "<cluster-admin>" as current context in /home/vsts/.kube/config

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[error]Script failed with error: Error: The process '/usr/bin/bash' failed because one or more lines were written to the STDERR stream

**Comment by radulacatus** [comment]
Potential workarounds:
- Configure pipeline task not to fail task on STDERR
- Request an older version on Ubuntu
- Demand capability for the agent with a specific image version -> i am not sure that this is possible

**Comment by BogdanGeorge** [comment]
Seems to work fine if using:  `az aks get-credentials --resource-group --name **--only-show-errors** --overwrite-existing --admin`

**Comment by MFredX** [comment]
I was experiencing this too and as @radulacatus said configuring the pipeline task to not fail on Standard Error fixed it for me. 
My YAML pipeline step looked like this;

```  
    - task: ShellScript@2
        inputs:
          scriptPath: '.run.sh'
          failOnStandardError
        displayName: 'Configure App environment variables'`
```

**Comment by alisterlf** [comment]
I'm having the sabe issue with this task
![image](https://user-images.githubusercontent.com/764324/179633544-9585e7a6-7655-458a-9286-e1ae117018e2.png)

**Comment by roycrxtw** [comment]
The `failOnStandardError` flag could result in false positive errors when there is actually no error in the pipeline's result.
As confirmed by @radulacatus  and @MFredX, setting the `failOnStandardError` flag to false could solve this issue.

Turn on:
![Screenshot 2023-12-28 at 2 48 22 PM](https://github.com/microsoft/azure-pipelines-tasks/assets/24327629/571c72da-2062-476d-a85c-5a425d33bad2)


Turn off:
![Screenshot 2023-12-28 at 2 50 47 PM](https://github.com/microsoft/azure-pipelines-tasks/assets/24327629/2df5636b-91ba-4b8c-8b8e-a1827e6c23bf)
