### ISSUE TITLE
How to specify NPM version when using npm task

### ISSUE THREAD

**Issue by zhenyanghua** [microsoft/azure-pipelines-tasks#15192]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Question**

**Enter Task Name**: **Npm@1**

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - Azure Pipelines: https://dev.azure.com/mytech-platform/All%20Might/

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
      - Azure Pipelines
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I couldn't find a place to specify the npm version, we would like to use NPM v7 which has the support to `package-lock.json` v2. However, the agent that is assigned uses NPM V6, even though we use a node version that has the NPM V7 as the default version. 

![image](https://user-images.githubusercontent.com/6165894/130516013-48d555b1-f5b2-488a-ac86-721a4af7b72b.png)

As a walkaround, we current added one more `npm` task before the install process to upgrade npm to the v7, but since we are able to choose different node version, how could we set the pipeline so that it uses NPM v7 for the task with just configuration instead of upgrade script?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by MATEUSZROGALSKI** [comment]
IDK if this is still the case for you guys but you can specify `NODE` and `NPM` version using `env` section in your GH Actions.

```env:
  NODE_VERSION: '16.x'```
