### ISSUE TITLE
[Deployment, databases, and servers tasks] Update dependencies on "azure-pipelines-tasks-azure-arm-rest-v2" package to fix high vulnerability issues

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-tasks#15195]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
- AzureAppServiceManageV0
- AzureFileCopyV2
- AzureFileCopyV3
- AzureFileCopyV4
- AzureMonitorAlertsV0
- AzureMysqlDeploymentV1
- AzurePowerShellV4
- AzurePowerShellV5
- AzureRmWebAppDeploymentV3
- AzureRmWebAppDeploymentV4

## Issue Description

These tasks have dependency on "azure-pipelines-tasks-azure-arm-rest-v2" that has critical vulnerability in "typed-rest-client > underscore".

![image](https://user-images.githubusercontent.com/86476103/130602855-5536a8ca-84ae-487a-b7b4-90a15b449cbb.png)

Please update this dependency to latest version.
This vulnerability was fixed in [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15087).

### Error logs

To get error log for each task run `npm audit`

**Comment by tatyana-kostromskaya** [comment]
Hi, @nadesu could you please take a look?

**Comment by v-saikumart** [comment]
PR has been merged.
