### ISSUE TITLE
[Deployment, databases, and servers tasks] Update dependencies on "utility-common-v2" package to fix high vulnerability issues

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-tasks#15196]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
- AzureAppServiceManageV0
- AzurePowerShellV4
- AzurePowerShellV5
- AzureWebAppV1

## Issue Description

These tasks have dependency on "azure-pipelines-tasks-utility-common" that has critical vulnerability in "azure-pipelines-tool-lib > typed-rest-client > underscore".

![image](https://user-images.githubusercontent.com/86476103/130604773-8aeacca1-45a4-4ea3-b2dc-851de88ed834.png)

Please update this dependency to the latest version.
This vulnerability was fixed in [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15150/files).

### Error logs

To get error log for each task run `npm audit`

**Comment by tatyana-kostromskaya** [comment]
Hi, @nadesu could you please take a look?

**Comment by v-saikumart** [comment]
PR has been merged.
