### ISSUE TITLE
[Deployment, databases, and servers tasks] Update dependencies on "AzureRMDeploy-common" package to fix high vulnerability issues

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-tasks#15197]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
- AzureAppServiceSettingsV1
- AzureFunctionAppContainerV1
- AzureFunctionAppV1
- AzureWebAppContainerV1
- AzureWebAppV1

## Issue Description

These tasks have dependency on "azure-pipelines-tasks-azurermdeploycommon" that has critical vulnerability in "typed-rest-client > underscore".

![image](https://user-images.githubusercontent.com/86476103/130609101-ff9aadaf-5d7f-44c2-8dad-6863a25f5094.png)

Please update this dependency to latest version.
This vulnerability was fixed in [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15161).

### Error logs

To get error log for each task run `npm audit`

**Comment by tatyana-kostromskaya** [comment]
Hi, @nadesu could you please take a look?

**Comment by v-saikumart** [comment]
PR has been merged.
