### ISSUE TITLE
GithubRelease fails to create release.

### ISSUE THREAD

**Issue by DimitrisStaratzis** [microsoft/azure-pipelines-tasks#15220]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GithubRelease@0  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

dimitris.staratzis@tiledb.com, TileDB-Inc / CI / Pipelines / TileDB-Inc.TileDB-Spark / 20210812.3

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The GithubRelease task fails to create a release. The logs provide little information as to why this is happening.

### Task logs

[https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=14167&view=logs&j=f1af9539-69b6-54a3-0774-4e0103168c4d&t=8ac7cdcd-65ef-56b0-91bc-41828bf6b1fc](url)

**Comment by ihnorton** [comment]
The problem here was that we were using a `gitHubConnection` parameter in the `GithubRelease` task pointing to a connection created by an employee who left (GH user id no longer has push access to the repository).
