### ISSUE TITLE
AzurePowerShellV5 is missing ps_modules\VstsTaskSdk

### ISSUE THREAD

**Issue by fromthewoods** [microsoft/azure-pipelines-tasks#15221]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: question

**Enter Task Name**: AzurePowerShellV5

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using TFS on-premises, provide the version: Azure DevOps Server Version Dev18.M170.6

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016, 2.191.1

## Issue Description

We are trying to adopt the Az Module in our pipelines so we are new to this.

When using the AzurePowerShell@5 task we get an error at the start of the task.

### Task logs

```
##[debug]Evaluating condition for step: 'Az Pwsh Simple Test'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Az Pwsh Simple Test
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.176.3
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting
==============================================================================
##[error]File not found: 'D:\azdev\bld01\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.176.3\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
##[debug]System.IO.FileNotFoundException: File not found: 'D:\azdev\bld01\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.176.3\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
File name: 'D:\azdev\bld01\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.176.3\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.File(String fileName, String name)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

[logs_69046.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7048764/logs_69046.zip)

### Error logs

```
##[error]File not found: 'D:\azdev\bld01\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.176.3\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
##[debug]System.IO.FileNotFoundException: File not found: 'D:\azdev\bld01\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.176.3\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
File name: 'D:\azdev\bld01\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.176.3\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.File(String fileName, String name)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

**Comment by fromthewoods** [comment]
It looks like we might have caused this problem. Before we migrated this collection from TFS 2018 to Azure DevOps Server 2020, we experimented with manually uploading the AzurePowerShellv5 task. It looks like we forgot the include the ps_modules folder in the upload.

I'd like the AzurePowerShellv5 task to be in sync with what is being offered from Microsoft. To fix the task, I'm considering uploading another version of the task with the right dependencies. 

Can someone provide guidance on how to properly get this back to the way it should be?

**Comment by chshrikh** [comment]
can you please confirm if you are using latest agent version 2.191.1 ? If yes I think we can attempt to upload the latest version of V5 task ? 
The task version with your set-up is 5.176.3, the latest one which is available is 5.185.0. If you have test set-up to test the latest version, we can share the details how to upload the latest version of task.

**Comment by fromthewoods** [comment]
Yes we are running 2.191.1 agents now. Yes please share the detail on how to upload the latest version of the task!

**Comment by fromthewoods** [comment]
@chshrikh would you be able to help? 

> we can share the details how to upload the latest version of task.

**Comment by v-jkarri** [comment]
Please find the below steps to upload a task.

1. Download and extract the below zip folder.    
     [Tasks.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7151705/Tasks.zip)
2. Open command prompt and run **npm install -g tfx-cli** (Refer TFS CLI Installation)
3. run **tfx login**
4. Enter **Service URL** and **PAT** details 
5. run **tfx build tasks upload --task-path   .\Tasks\AzurePowerShellV5** (give extracted folder physical path )

**Comment by jessehouwing** [comment]
If you are running into a similar issue, check out: https://github.com/jessehouwing/azure-pipelines-tasks-zips
