### ISSUE TITLE
[HelmDeploy] show Kubernetes (deprecation) warnings in Azure DevOps pipeline warning list

### ISSUE THREAD

**Issue by mblaschke** [microsoft/azure-pipelines-tasks#15224]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Feature

**Enter Task Name**:  
HelmDeployV0

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - can deliver details via private message/email
 
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      - 
        Pool: private linux pool
        Image: ubuntu-18.04 based
        Agent version: 2.19.0

## Issue Description

Kubernetes (deprecation) warnings are not listed in Pipeline warnings, only yaml issues are listed

### Task logs

example warnings:
```
W0826 14:26:03.304183   41193 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0826 14:26:03.333142   41193 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0826 14:26:03.363226   41193 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0826 14:26:05.913588   41193 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0826 14:26:05.942834   41193 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0826 14:26:05.975225   41193 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```

## Troubleshooting
n/a

### Error logs
n/a

**Comment by ralfzen** [comment]
Even nicer would be, to have a tab for deprecations.
