### ISSUE TITLE
Pipeline output is accidentally masked

### ISSUE THREAD

**Issue by MirKml** [microsoft/azure-pipelines-tasks#15234]
## Required Information

*Type*: Bug

**Enter Task Name**: Bash

## Environment
- Server - Azure Pipelines
- Agent - Private

## Issue Description

We have some bash scripts for deployments into our on premise kubernetes. These scripts write some messages into stdout. One of these is cluster name, which is important for general overview if deployment works as expected, it isn't secret, it's just cluster name in our case it's 't-mobile'
But in the azure logs, cluster name is masked with *** see logs below, message

2021-08-30T15:35:02.3553927Z deploy config map permissions-frontend-dev-config cluster ***

I read your docs about masking secret variables and secrets at all but this isn't this case. Only what I found is that there is service connection with name "Kubernetes - T-Mobile'. There is no reason for masking only 't-mobile', or even service connection name at all.

Why is this word - 't-mobile' masked, do you mask each word from service connection?
Is some possibility how to show these information in logs? E.g. write string in special format, which is ignored for masking when you are processing logs -  e.g.  `<nomask>intentionally don't mask these string</nomask>`?

### Task logs

2021-08-30T15:35:02.2210119Z ==============================================================================
2021-08-30T15:35:02.2210495Z Task         : Bash
2021-08-30T15:35:02.2210844Z Description  : Run a Bash script on macOS, Linux, or Windows
2021-08-30T15:35:02.2211168Z Version      : 3.189.0
2021-08-30T15:35:02.2211478Z Author       : Microsoft Corporation
2021-08-30T15:35:02.2211910Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2021-08-30T15:35:02.2212405Z ==============================================================================
2021-08-30T15:35:02.3385348Z Generating script.
2021-08-30T15:35:02.3395821Z Formatted command: exec bash '/azp/agent/_work/r13/a/appMonorepoSource/permissions/deploy/deploy-rancher.sh'
2021-08-30T15:35:02.3405775Z ========================== Starting Command Output ===========================
2021-08-30T15:35:02.3417048Z [command]/bin/bash --noprofile --norc /azp/agent/_work/_temp/81a64c55-439b-41a4-9656-a0283a63c7e4.sh
2021-08-30T15:35:02.3553927Z deploy config map permissions-frontend-dev-config cluster ***
....
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

**Comment by max-zaytsev** [comment]
Hi @MirKml, we could not reproduce the issue. Could you provide more detailed steps to reproduce this?
Do you use any secret variables in your pipeline (or a variable group that can contain a secret variable)?

**Comment by MirKml** [comment]
It's perfectly reproducible in one of our devops pipelines in our payed subscription. I can write/send a link to pipeline log if necessary. As I said I read docs about masked secret variables, but only what I found is "Kubernetes - T-Mobile" for service connection. We print only "t-mobile" in our task. I think "t-mobile" string is also presented many times in kubeconfig which content is copy pasted into "Kubernetes - T-Mobile" service connection.

**Comment by max-zaytsev** [comment]
Hi @MirKml 
Azure Devops doesn't mask the service connection name (or its substring). But authentication parameters of service connections are masked. So if you have "t-mobile" string there, it should be masked. (Please check if you have this string in any authentication inputs of your connections and task that are used in the pipeline). 
Also, could you please tell us what type of authentication do you use for Kubernetes service connection? Is it kubeconfig?

**Comment by MirKml** [comment]
Yes kubernetes service connection is authenticated through kubeconfig directly copied into service connection settings.
It seems like this
```yaml
apiVersion: v1
kind: Config
clusters:
- name: "t-mobile"
  cluster:
    server: "https:/our.cluster.io"
    
users:
- name: "t-mobile"
  user:
    token: <some token>

contexts:
- name: "t-mobile"
  context:
    user: "t-mobile"
```

What is cause of masked "t-mobile" string? Cluster name, user name, or it doesn't matter, all "names" from kubeconfig are masked? I have a secret tip :-).

What about possibility `<nomask>t-mobile</nomask>` like output strings, which will be skipped for masking, it's something supported?

**Comment by max-zaytsev** [comment]
@MirKml sorry for the delay. In your case, "t-mobile" from the cluster context name is masked:

![image](https://user-images.githubusercontent.com/16704239/135113280-93bf7982-758a-4f75-8e6b-6f9e33c5e0c5.png)

Skipping masking is not supported yet. It sounds like a reasonable feature for Azure Pipelines, but this repo is mostly for task issues. Could you please create a feature request on https://developercommunity.visualstudio.com/report?space=21&entry=suggestion?
