### ISSUE TITLE
Support PyPy 3.7 installation by UsePythonVersion@0 tasks.

### ISSUE THREAD

**Issue by proofit404** [microsoft/azure-pipelines-tasks#15232]
To my understanding [UsePythonVersion@0](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version) task could only recognize `pypy3` as version 3.6 version of the interpretter.

Are there any plans to support more recent versions of the PyPy.

For example, `versionSpec: 'pypy3.7'`?

Best regards,
Artem.

**Comment by asottile** [comment]
this is supported by github actions which I believe uses the same images -- is this just a matter of making the `pypy3.6` / `pypy3.7` strings match the correct things?

**Comment by anatolybolshakov** [comment]
Hi @proofit404 @asottile @scbedd thanks for reporting and contribution! Let us take a look.

**Comment by DmitriiBobreshev** [comment]
Hi @proofit404 @asottile @scbedd, the PR was merging and now waiting for deployment, when these changes will be available for all customers I'll let you know
