### ISSUE TITLE
npm build command error for 7zip downlaod

### ISSUE THREAD

**Issue by dengyakui** [microsoft/azure-pipelines-tasks#15246]
## Note
using AzureDevOps try to build the repo, following:
1. npm install
2. npm run build    ----------------Error
3. npm run package
there is always an error when the make.js try to downlaod a 7zip file, but the file can download throw my chrome browser, and size is small,  about 800kb. want to know how to resolve the error??
### Error logs

![image](https://user-images.githubusercontent.com/3945919/131813542-34aac28b-42c1-4be5-a47c-3c0742d1d16c.png)

[Insert error from the logs here for a quick overview]

**Comment by anatolybolshakov** [comment]
Hi @dengyakui this may be related to the node version you use - you may need to install node 8 version (you can use [nvm](https://github.com/nvm-sh/nvm) for this) to make it work.
Another way to resolve this issue:
- Open node_modules\sync-request\index.js
- Set maxBuffer value for spawnSync method in doRequestWith - by applying changes like below:

![image](https://user-images.githubusercontent.com/8779682/132204421-d0857e31-c04f-44ad-8cd6-2a8a8767b81d.png)
- Run build command again

**Comment by anatolybolshakov** [comment]
Hi @dengyakui just as quick update - fix to this issue will require dropping of node 6 support - we need to complete migration to node 10 first to resolve this - leaving this open at the moment.

**Comment by magleaso** [comment]
@anatolybolshakov I'm still hitting this. Are we able to fix this now?
