### ISSUE TITLE
Maven build fail due to an API incompatibility while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile

### ISSUE THREAD

**Issue by maminetahiri** [microsoft/azure-pipelines-tasks#15265]
Here are the message error:

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile (scala-compile-first) on project spark-raw-prepared: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;

**Comment by anatolybolshakov** [comment]
Hi @maminetahiri there seems to be an issue with one of the maven plugin not related to the pipelines side - I would suggest to open an issue in [repo](https://github.com/davidB/scala-maven-plugin) for further help.

**Comment by maminetahiri** [comment]
Hello @anatolybolshakov, when i try to build my artifact localy it works but when i use azure devops (pipeline service) i have this kind of error. In the past my build worked well with azure devops so i don't know if there is some update ?

**Comment by anatolybolshakov** [comment]
@maminetahiri have you checked the difference between latest successful and failed runs? Was there some difference in task, or hosted image?
For images questions - you can post a question on https://github.com/actions/virtual-environments
Most likely it seems to be related to some tools update on image.

**Comment by maminetahiri** [comment]
@anatolybolshakov there is no difference in task between latest successful and failed runs. Maybe like you said there is some update on hosted image. I will ask question about the hosted images. Thanks.

**Comment by anatolybolshakov** [comment]
Let me close this one here - since it does not seem to be related to the task itself.
