### ISSUE TITLE
InvokeRestAPI task: Without being able to process the response, it is very limited.

### ISSUE THREAD

**Issue by woter1832** [microsoft/azure-pipelines-tasks#15260]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: InvokeRestAPI
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/InvokeRestApiV1

## Environment
NA. Server task - no agent needed.

## Issue Description

Your [documentation ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops#can-i-use-the-response-body-as-the-input-for-another-task)states we cannot use the response body as the input to another task.
![image](https://user-images.githubusercontent.com/68354513/132497535-353b0551-e287-4324-b0a2-65bce4bba030.png)
Considering the way one builds up the URI parameters by making calls to various endpoints, this is rather limiting in its useability.

It is nice that this is an agent-less (server) task, however, to be able to build up URIs, we must be able to process the response.

### Example:
I can use the PR API to create a PR, however, should I need to perform another operation on that PR, such as close, add approvers, add comments etc, those endpoints all need the PR's ID (`pullRequestId`). How does one get that, if one cannot process the response?

The only workaround is to use an Agent task with and code a shell (e.g. PowerShell - `Invoke-RestMethod`).

**Comment by hassanlatif** [comment]
Any update on this?

**Comment by woter1832** [comment]
@Microsoft, care to respond?

**Comment by hski-bayer** [comment]
+1. Require to get ability to use the response in subsequent pipeline steps.

**Comment by rodrigo-tsuru** [comment]
+1

**Comment by fvanheeswijk** [comment]
+1

**Comment by matthiasbrix** [comment]
+1

**Comment by symnatbay** [comment]
+1 very important

**Comment by cassdeckard** [comment]
+1
