### ISSUE TITLE
tasks need update for helm breaking changes

### ISSUE THREAD

**Issue by cfauchere** [microsoft/azure-pipelines-tasks#15288]
## Note  
helm introduced some breaking change
https://github.com/helm/helm/releases

## Required Information

BUG HelmDeploy@0

Build breaks at HelmDeploy@0 save when using latest version (HelmInstaller@1), because of breaking changes introduced by helm. 

## Environment

Azure Pipelines
account: UiPath
project: Orchestrator 
build name: CI-AspNetCore 
build id: 1909497

Hosted

## Issue Description

helm introduced breaking change in the tool. previous version 3.6.3 no problem.

![image](https://user-images.githubusercontent.com/12868340/133537247-2319f368-1384-4dd4-b301-40f2052d02a0.png)
![image](https://user-images.githubusercontent.com/12868340/133537311-098744cc-1d64-4861-b3e8-7daeaf4df520.png)

new version 3.7.0 broken
![image](https://user-images.githubusercontent.com/12868340/133537336-3f1b4b66-62f9-40ae-bc20-ee21281949b8.png)
![image](https://user-images.githubusercontent.com/12868340/133537347-f658fdd6-3f8e-4b6c-baf1-efaa75a10981.png)

**Comment by ItsKev** [comment]
Is anyone already on this or should I create PR for it?

Never worked on pipeline tasks before but would be happy to help because we need the `save` command to push our Helm charts to the ACR.
