### ISSUE TITLE
Task: Gradle is always failing

### ISSUE THREAD

**Issue by cicciolinamiranda** [microsoft/azure-pipelines-tasks#15290]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle is always failing 
  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- vmImage: ubuntu-latest
    
- Azure Pipeline for Android: Gradle@2 task running assembleRelease.

## Issue Description

Task name: Gradle@2
running: assembleRelease
Issue: It seems like it has having issue on downloading the dependencies which is not happening before.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
<img width="1367" alt="azure_issue" src="https://user-images.githubusercontent.com/17084421/133613035-76a0c65d-26ff-4058-8d1a-890fc85bb0f6.png">

Diagnostic log
[task_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7177727/task_log.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tatyana-kostromskaya** [comment]
@cicciolinamiranda could you please re-upload attached image and attach task logs?

**Comment by cicciolinamiranda** [comment]
> @cicciolinamiranda could you please re-upload attached image and attach task logs?

Hi @tatyana-kostromskaya , Done reuploading the screenshot and the full task log. This just happen today.

**Comment by cicciolinamiranda** [comment]
> ## Note
> Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo
> 
> For a list:
> https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks
> 
> If you have an issue or request for the Azure Pipelines service, use developer community instead:
> 
> https://developercommunity.visualstudio.com/spaces/21/index.html )
> 
> ## Required Information
> Entering this information will route you directly to the right team and expedite traction.
> 
> **Question, Bug, or Feature?**
> _Type_: Bug
> 
> **Enter Task Name**: Gradle is always failing
> 
> list here (V# not needed):
> https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks
> 
> ## Environment
> * vmImage: ubuntu-latest
>   
>   * If using TFS on-premises, provide the version:
>   * If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
> * Agent - Hosted or Private:
>   
>   * If using Hosted agent, provide agent queue name: ubuntu-latest
>   * If using private agent, provide the OS of the machine running the agent and the agent version:
> 
> ## Issue Description
> [Include task name(s), screenshots and any other relevant details]
> 
> ### Task logs
> [Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
> <img alt="azure_issue" width="1367" src="https://user-images.githubusercontent.com/17084421/133613035-76a0c65d-26ff-4058-8d1a-890fc85bb0f6.png">
> 
> Diagnostic log
> [task_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7177727/task_log.txt)
> 
> ## Troubleshooting
> Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
> 
> ### Error logs
> [Insert error from the logs here for a quick overview]

**Comment by anatolybolshakov** [comment]
Hi @cicciolinamiranda there is an error with reaching out to https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom - which is external to Azure Pipelines.
Do you use hosted or self-hosted agent?
Does it happen sporadically for you? I would suggest to reach out to Gradle support - to clarify why such connectivity issue could happen.

**Comment by cicciolinamiranda** [comment]
> Hi @cicciolinamiranda there is an error with reaching out to https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom - which is external to Azure Pipelines.
> Do you use hosted or self-hosted agent?
> Does it happen sporadically for you? I would suggest to reach out to Gradle support - to clarify why such connectivity issue could happen.

@anatolybolshakov i just tried it few minutes ago and its working fine. Closing this ticket now thank you
