### ISSUE TITLE
[NuGet tool installer] Certificate has expired

### ISSUE THREAD

**Issue by msftradford** [microsoft/azure-pipelines-tasks#15316]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NuGetToolInstaller

## Environment
- Server - Azure Pipelines       
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    **Project Name**: [Universal Store]
    **Build Definition Name/Build Number**: [ms.mrservices.anchorgraph]/[ms.mrservices.anchorgraph_master_2109.1901]
    
- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: 
    **Pool**: 'Universal Store'
    **Agent Name**: 'AZBLD2W125'
    **Agent Version**: '2.190.0'

## Issue Description

Failure to complete NuGet download with "ERR:certificate has expired"

### Task/Error log

> 2021-09-22T17:40:35.8323533Z ##[section]Starting: [DOWNLOAD NUGET] Use NuGet 5.x
> 2021-09-22T17:40:35.8486460Z ==============================================================================
> 2021-09-22T17:40:35.8486807Z Task         : NuGet tool installer
> 2021-09-22T17:40:35.8487285Z Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
> 2021-09-22T17:40:35.8487725Z Version      : 1.179.0
> 2021-09-22T17:40:35.8487957Z Author       : Microsoft Corporation
> 2021-09-22T17:40:35.8488300Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/nuget
> 2021-09-22T17:40:35.8488656Z ==============================================================================
> 2021-09-22T17:40:36.1526331Z You are using a query match on the version string. Behavior changes or breaking changes might occur as NuGet updates to a new version.
> **2021-09-22T17:40:36.2125716Z ERR:certificate has expired**
> 2021-09-22T17:40:36.2259518Z ##[section]Finishing: [DOWNLOAD NUGET] Use NuGet 5.x

**Comment by BrianMouncer** [comment]
We are seeing this in our pipelines as well.
It was intermittent yesterday, but is not an almost constant build failure.

**Comment by doughutchens** [comment]
Our team is seeing as well on nuget tool installer v1.  Nuget version: 5.10.0 and 5.11.1.  Failures are becoming more frequent in our pipelines.

**Comment by BrianMouncer** [comment]
I switched from nugettoolinstaller@0 to nugettoolinstaller@1 hoping the cert problem was only with the @0 yml task.
This may have improved things, but I see others are reporting the same cert issue with V2 task as well...

**Comment by jjavierdguezas** [comment]
This happened to us today with `NuGetToolInstaller@1`. When we ran the pipeline again everything went well, without changing anything

**Comment by BrianMouncer** [comment]
We are hitting this again this week.

Creating a new issue in the other GH home for this task, and cross linking it here.
https://github.com/microsoft/azure-pipelines-tool-lib/issues/133

Please let us know that you are looking into the issue.

Thanks.

**Comment by PascalTurbo** [comment]
@BrianMouncer @msftradford are you using Lets Encrypt certificate for your Azure DevOps Server? Or contacting a NuGet Server using Lets Encrypt certificate?

We are seeing this issues since tonight and think it is related to the Old Lets Encrypt root certificate.

**Comment by PascalTurbo** [comment]
I found an ugly workaround. Just set `NODE_TLS_REJECT_UNAUTHORIZED=0`
I've added it to runsvc.sh on the linux agent.
