### ISSUE TITLE
AzureAppServiceSettings@1: Is it possible to delete an app setting?

### ISSUE THREAD

**Issue by srmagura** [microsoft/azure-pipelines-tasks#15312]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureAppServiceSettings

## Environment
- Server - Azure Pipelines or TFS on-premises? 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: **Azure Pipelines**, rest of information is not relevant

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: **Windows**, agent version is not relevant

## Issue Description

Is it possible to delete an app setting using the AzureAppServiceSettings task? My application has an old unused setting that I would like to get rid of.

If it is possible, it would be good to add this to the documentation.

[Relevant documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops)

### Task logs

N/A

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

N/A

**Comment by samskiter** [comment]
+1 it's not clear if you can rely on the YML pipeline to be the source of truth

**Comment by robkendrick** [comment]
I just tested this via YAML and found that any AppSettings you include will be either added to what is already present or will update what was there previously. All other AppSettings remain.

From my `update.webapps.yaml`:
```
- ${{each instance in parameters.instances}}:
    - ${{each app in parameters.resourceNamePrefixes}}:
        - task: AzureCLI@2
          displayName: 'Pull ${{app}}${{instance}}api$(primarySuffix) AppSettings from $(parameterFileName).'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: pscore
            scriptLocation: inlineScript
            workingDirectory: "$(Pipeline.Workspace)\\drop\\"
            inlineScript: |
              $params = (Get-Content $(parameterFileName) | ConvertFrom-Json -Depth 100).parameters.appSettings.value.${{app}}
              $appSettingsUnmodded = $params.psobject.properties | Select name,value | ConvertTo-Json
              # The 'name' and 'value' fields must be lowercase!
              $appSettings = $appSettingsUnmodded.Replace('Name','name').Replace('Value','value')
              # Passing multiline strings does not seem to work. Convert it to a single-line string here.
              $oneLiner = ($appSettings).trim().replace("`r`n","")
              echo "##vso[task.setvariable variable=${{app}}AppSettings]$oneLiner"


        - task: AzureAppServiceSettings@1
          displayName: "Update ${{app}}${{instance}}api$(primarySuffix)'s AppSettings and ConnectionStrings."
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            appName: ${{app}}${{instance}}api$(primarySuffix)
            slotName: staging
            appSettings: |
              $(${{app}}AppSettings)
            connectionStrings: |
              [
                {
                  "name": "${{app}}db",
                  "value": "Server=tcp:$(dbRGTN)01sqls$(secondarySuffix).database.windows.net,1433;Database=${{app}}00db$(secondarySuffix);Authentication=Active Directory Default;Trusted_Connection=False;Encrypt=True;Connection Timeout=30",
                  "type": "SQLAzure",
                  "slotSetting": false
                }
              ]

```

Deployment log shows the update is successful:
```
Trying to update App Service Application settings. Data: {"ASPNETCORE_ENVIRONMENT":"RobTest","LOG4J_FORMAT_MSG_NO_LOOKUPS":true,"WEBSITE_USE_PLACEHOLDER":0}
Updated App Service Application settings and Kudu Application settings.
```

Despite the fact that only three AppSettings are included, the omitted AppSettings remain:
```
>_ az webapp config appsettings list -n $apiName -g $rgName -s staging --query "[].name"
[
  "ASPNETCORE_ENVIRONMENT",
  "AzureAdB2C:Instance",
  "AzureAdB2C:Domain",
  "AzureAdB2C:TenantId",
  "AzureAdB2C:ClientId",
  "AzureAdB2C:MetadataAddress",
  "AzureAdB2C:Audience",
  "AzureAdB2C:ClaimsIssuer",
  "SwaggerOAuth:AuthorizationUrl",
  "SwaggerOAuth:TokenUrl",
  "SwaggerOAuth:ApiScope",
  "SwaggerOAuth:OpenIdClientId",
  "LOG4J_FORMAT_MSG_NO_LOOKUPS",
  "WEBSITE_USE_PLACEHOLDER",
  "WEBSITE_ENABLE_SYNC_UPDATE_SITE"
]
```
