### ISSUE TITLE
Visual Studio Test does not publish test results for data driven tests even though tests are run successfully

### ISSUE THREAD

**Issue by nahush-hombali** [microsoft/azure-pipelines-tasks#15344]
## Note  
The Visual Studio Test task runs the tests successfully but does not publish the results on the test run after completion. This is observed only when the tests have the attribute 'DataSource' associated with it. 

## Required Information

We have Selenium tests created with MSTest v2. After migrating our tests from MSTest 2.2.3 to 2.2.7, the test results on the Azure DevOps server are not being published by the 'Visual Studio Test' task. The logs of the task show the tests being run and their appropriate status of Passed/Fail. But the same doesn't show up in the run summary of the test run. There is no failure logged either on the task logs.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Visual Studio Test

## Environment
- Server -  TFS on-premises
    
    - Version Azure DevOps Server 2020 Update 1.1
    
- Agent - Private: 
    
   - Agent OS -	Windows_NT
   - Agent Version - 2.181.2

## Issue Description

As described in the screenshot, the VS Test task executes the tests successfully and shows the individual test results of pass/fail in the task logs. But the result summary is not being reflected on the test runs. The outcome is being shown as unspecified. 

Note that the trx file shows the appropriate results same setup shows the results when the MSTest version is degraded to 2.2.3.

Task Logs: 
![image](https://user-images.githubusercontent.com/88318301/135035968-29d41b93-7d8f-4577-b542-ec92ddbeb946.png)

Test Run summary:
![image](https://user-images.githubusercontent.com/88318301/135036002-d67d8f60-1723-479a-9c90-ff6b02b153c8.png)

Test Result details:
![image](https://user-images.githubusercontent.com/88318301/135036063-7a26906e-5904-4a5f-b568-9a605c571eed.png)

**Comment by TroyWalshProf** [comment]
It think this is more an issue with MSTest V2 then it is with the test task.
See: https://github.com/microsoft/testfx/issues/1023

Note* The change in MSTest also breaks existing data driver test associations in Azure DevOps test cases.
