### ISSUE TITLE
Support Xamarin.Mac applications in the XamariniOS@2 task

### ISSUE THREAD

**Issue by Axemasta** [microsoft/azure-pipelines-tasks#15340]
## Required Information

**Question, Bug, or Feature?**  
*Type*:  Feature

**Enter Task Name**: [`XamariniOS@2`](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/XamariniOSV2)

## Issue Description

The build process for Xamarin.iOS & Xamarin.Mac is the same. Both MSBuild tasks require some information on configurations and need to be provided Apple certificates in order to sign the applications.

When using the xamarin ios task in a pipeline it sets the MSBuild platform to `iPhone` and there is no way to override this. See [here](https://github.com/microsoft/azure-pipelines-tasks/blob/6f2429cb09b4ed3c41adbfd62c9d74cca9263932/Tasks/XamariniOSV2/xamarinios.ts#L44) how the platform is passed to msbuild from the code.

When using the task for iOS the following msbuild command will be generated:
```
/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /Users/runner/work/1/s/src/ACME.sln 
    /p:Configuration=Release 
    /p:Platform=iPhone 
    /p:BuildIpa=true 
    /p:Codesignkey=Developer ID Application: ACME (00000000) 
    /p:CodesignProvision=00000000-0000-0000-0000-000000000000
```

Due to the task not supporting mac, a developer has to use the MSBuild task to build their macOS app. This is not as convenient as providing a task and adds an arbitrary barrier to entry.

The following `yml` will build the app successfully:
```yml
- task: MSBuild@1
  displayName: 'Build macOS'
  inputs:
    solution: '**/*.sln'
    configuration: 'Release'
    msbuildArguments: '/p:Codesignkey=\"$(APPLE_CERTIFICATE_SIGNING_IDENTITY)\" /p:CodesignProvision=\"$(APPLE_PROV_PROFILE_UUID)\"'
```

This will generate the following MSBuild command:
```
/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /Users/runner/work/1/s/src/ACME.sln 
    /p:Configuration=Release 
    /p:Codesignkey=\Developer ID Application: ACME (00000000) 
    /p:CodesignProvision=00000000-0000-0000-0000-000000000000
```

As you can see the command for both platforms is extremely similar and it would be beneficial for those few xamarin.mac developers if we had a task. The benefit for developers is maintaining the pipelines would be easier. I found when figuring out the msbuild inputs, the command line was incredibly flakey with how I formatted the msbuild arguments due to the fact that the code-sign variables can contain spaces. Wrapping this up in an official task would make this process more robust.

## Options

I foresee this could take a number of outcomes:
 - Update the task to accept mac as a platform, perhaps through a new parameter named `Platform` (default to `iOS`, add `macOS` as alternative value)
 - Create a new task named `XamarinMaciOS@1` which combines both
 - Create a new task named `XamarinMac@1` which just builds mac
 - I Fork the task and update it accordingly, making it available on the pipeline marketplace

I would rather have the official task support this functionality and would be happy to put in the work required to make the change.

**Comment by anatolybolshakov** [comment]
Hi @Axemasta sorry for the delay - we are currently working on more prioritized issues, but will get back to this feature request once be able to.

**Comment by Axemasta** [comment]
Clearly not many people are using xamarin mac & azure pipelines, can we add a flag such as `isMac` that we can set to prevent the platform flag `iPhone` from being sent to msbuild?
