### ISSUE TITLE
CacheV2 Task - Truncated file name ?

### ISSUE THREAD

**Issue by MattiZNX** [microsoft/azure-pipelines-tasks#15351]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: CacheV2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
- Agent - Hosted or Private: Hosted
   
## Issue Description

I think that the CacheV2 has some problem with long file names. In particular I noticed that during a NPM build with a specific configuration I have to different file name if I used the Cache Task (that recovered file from previous build) and from the standard NPM Install Task 

file name recovered from cache:  ea6f67ceee2f64303ef88f46027c09da6343fa6b449af43314b4a5e7de0ddea6abb03eea7af885e61261ce4134a937e8e35
file name from NPM Install:            ea6f67ceee2f64303ef88f46027c09da6343fa6b449af43314b4a5e7de0ddea6abb03eea7af885e61261ce4134a937e8e356f9ca4037cd8518d832142a21

I also attach a screenshot below :   

![image](https://user-images.githubusercontent.com/16720111/135269773-788d4a94-f2d0-4dc4-ba54-dd3d7cf628c2.png)

As you can see the NPM Install one has the same char as the cached one plus some chars

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
> action-board@1.0.0 build-prod D:\a\1\s
For more information, see https://angular.io/guide/browser-support
> node --max_old_space_size=12000 ./node_modules/@angular/cli/bin/ng build --configuration=production

- Generating browser application bundles (phase: setup)...
√ Browser application bundle generation complete.
- Copying assets...
√ Copying assets complete.
- Generating index html...
× Index html generation failed.
ENOENT: no such file or directory, open 'D:\a\1\s\node_modules\.cache\angular-build-fonts\content-v2\sha512\ac\e2\ea6f67ceee2f64303ef88f46027c09da6343fa6b449af43314b4a5e7de0ddea6abb03eea7af885e61261ce4134a937e8e356f9ca4037cd8518d832142a21'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! action-board@1.0.0 build-prod: `node --max_old_space_size=12000 ./node_modules/@angular/cli/bin/ng build --configuration=production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the action-board@1.0.0 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2021-09-27T12_31_45_371Z-debug.log
Found npm debug log, make sure the path matches with the one in npm's output: C:\npm\cache\_logs\2021-09-27T12_31_45_371Z-debug.log
0 info it worked if it ends with ok

[Insert error from the logs here for a quick overview]

**Comment by johnterickson** [comment]
What is your cache key format? Are you trying to share cache entries across OS?
We are just TARing and unTARing.  What happens when you directly tar/untar that folder?

**Comment by MattiZNX** [comment]
I'm currently setting up Cache Task from ADO Portal like this : 
![image](https://user-images.githubusercontent.com/16720111/135399389-a0449ece-fe4e-4920-b10b-d9f4a9f67aa1.png)

**Comment by MattiZNX** [comment]
I also tryed to pack and unpack files to see if is an archive process problem but with this pipeline 
![image](https://user-images.githubusercontent.com/16720111/135469987-cc2a2b25-8611-4a37-8bfc-9a3ccd9f4da1.png)

The 2 artifacts have the same lenght of file. So seems a problem of Cache Task code

**Comment by MattiZNX** [comment]
MY SOLUTION: if you simply archive the folder before caching the problem doesn't exist. Probably the TAR operation of cache task is done wrong (has some problem on long file names). 

Archieve files that you need to cache ---> cache TAR file ---> extract achieve on next pipeline if cache is hitted

In this way you can save build time. Also you download or upload less bytes if you manage zipped file during cache operation  with less dependency on connection speed of Azure pipeline hosted VMs
