### ISSUE TITLE
Remove 'id' from AzureIoTEdge task - action: 'Push module images'

### ISSUE THREAD

**Issue by Ioana37** [microsoft/azure-pipelines-tasks#15350]
**Question, Bug, or Feature?**  
*Type*: Feature/Question

**Enter Task Name**:  AzureIoTEdge - action: 'Push module images'

## Issue Description

Recently, the Azure IoT Edge task [page](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops) has been recently edited and the new example for how to use the AzureIoTEdge - Push module images task is as follows: 
![image](https://user-images.githubusercontent.com/69301842/135259026-c0b61ed8-4cfa-488a-8a9d-87ed5170e0be.png)

However, when auto-generating the task from the YAML editor in AzureDevOps, the 'azureContainerregistry' field contains also an 'id':
![image](https://user-images.githubusercontent.com/69301842/135259683-d8897e7b-2565-458e-bf7a-83e9589f8696.png)

We tested both variants in our pipelines and the 'id' is not needed for logging into the ACR and pushing the images.

Furthermore, after taking a quick look at the following class: https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureIoTEdgeV2/registrycredentialfactory.ts, the 'id' seems to not be used.

Could you please take a more closer look and if indeed it is needed, clarify in the docs what are its use cases and if it turns out that is not needed, remove from the auto-generated YAML task?

**Comment by mhshami01** [comment]
Tank you for reaching out. We have added this item to our backlog.

**Comment by marianan** [comment]
This has been resolved int he latest version of the CICD task. @Ioana37 let us know if the symptoms persist.
