### ISSUE TITLE
"Certificate has expired" on Nuget Restore

### ISSUE THREAD

**Issue by arp-mbender** [microsoft/azure-pipelines-tasks#15367]
We're using DevOps on-prem 2020 Update 1.1 (18.181.31626.1) with the agents being updated to v2.181.2, and since last Friday (2021-10-01) we're having trouble with the Nuget Restore and Publish steps. Specifically, they throw a `##[warning]certificate has expired` message. For the time being I want to focus on the Restore task (I suspect if this gets fixed then the Publish will be working too).

The problem is, I can only speculate which certificate is at fault here. I think it's the certificate for our on-prem DevOps itself, which is using Let's Encrypt. One of the CAs for Let's Encrypt has recently been updated, and this seems to cause all manner of issues now. 

I think the problem is with the list of certificate CAs Node.js is using "under the hood"; I know this because when I added the `NODE_TLS_REJECT_UNAUTHORISED=0` environmental flag the restore task worked. But, obviously, this is very unsecure. However, I'm not 100% if the problem is our DevOps' site certificate, since when I tried adding that via `NODE_EXTRA_CA_CERTS` environment flag the task still failed. Frustratingly, the entire message is just that:
`##[warning]certificate has expired` and I'm only guessing it's trying to reach our DevOps because the line before that is
`##[debug]Created webApi client for https://<our on-prem DevOps public URI>/; options: {"proxy":null,"allowRetries":true,"maxRetries":5,"ignoreSslError":false}
`

To be exact, this is the task in question:
```
Starting: Restore NuGet packages
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.179.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================

```
However no additional information is provided, and I know for a fact that our site is using a current and valid LE certificate. Any idea what's going on?

**Comment by anatolybolshakov** [comment]
Hi everyone! Seems like this should be resolved with PR https://github.com/microsoft/azure-pipelines-tasks/pull/16054
