### ISSUE TITLE
dotnet test fails with invalid format error for TestRunParameters.Parameter input param

### ISSUE THREAD

**Issue by sureshtadisetty** [microsoft/azure-pipelines-tasks#15376]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: dotnet test

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines: Office ADO account, OE project, ReleaseDefinition Id is 534 

- Agent - Hosted or Private: 
    
    - Hosted agent: Azure Pipelines

## Issue Description

Below dotnet test command is failing with invalid format for TestRunParameters.Parameter. Weird thing is I'm using exactly same format as suggested in error message.
Command:
dotnet test <dll-path> --logger "console;verbosity=detailed" --results-directory D:\a\r1\a --settings <runsettings-path> -- TestRunParameters.Parameter(name=\\\"OffKiteBatchKey\\\", value=\\\"***\\\")

Error message:
2021-10-06T11:47:15.2196371Z The test run parameter argument 'TestRunParameters.Parameter(name=\"OffKiteBatchKey\", value=\"***\")' is invalid. Please use the format below.
2021-10-06T11:47:15.2197431Z Format: TestRunParameters.Parameter(name=\"<name>\", value=\"<value>\")

**Comment by anatolybolshakov** [comment]
Hi @sureshtadisetty do you some specific build task or do you run the command via some script task in the pipeline?

**Comment by anatolybolshakov** [comment]
Hi @sureshtadisetty do you have any updates? Is this issue still actual for you?
