### ISSUE TITLE
AzureIoTEdge@2 failing with error "Unable to locate executable file: 'iotedgedev'' failed with exit code 1

### ISSUE THREAD

**Issue by somiyarawat** [microsoft/azure-pipelines-tasks#15395]
## Required Information

*Type*: Bug

**Enter Task Name**: AzureIoTEdge@2

## Environment
- Server - Azure Pipelines
- Agent - ubuntu-latest
- Agent - Hosted 
    
## Issue Description
From past two days AzureIoTedge@2 task is failing with error :

##[debug]ERROR: Could not find a version that satisfies the requirement iotedgedev==3.2.0 (from versions: 0.79.0, 0.80.0, 0.81.0, 0.82.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 2.0.0, 2.0.1, 2.0.2, 2.1.0)
ERROR: No matching distribution found for iotedgedev==3.2.0

##[debug]which 'iotedgedev'
##[debug]not found
##[debug]task result: Failed
##[error]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Processed: ##vso[task.issue type=error;]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Agent.Version=2.193.0

**Comment by marianan** [comment]
Ubuntu 20.04 defaults to python 3.8 which isn't yet supported by iotedgedev. Please see more details at https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-824290697. We are working on adding support for more recent python versions.

**Comment by marianan** [comment]
@somiyarawat could you confirm what is the Python version that you are using?

**Comment by GO3LIN** [comment]
@marianan The issue is still there, with Ubuntu20.04, have you updated iotedgedev for Python3.8 ?

I am having trouble understanding that the workarround is to manually install iotedgedev while it's not supported for python3.8 ?????

**Comment by marianan** [comment]
Hello @GO3LIN , iotedgedev does not support python 3.8 yet which is what triggers the issue on Ubuntu 20.04.

**Comment by adithyasai** [comment]
i am still facing this with Ubuntu 20.04. what can be the best workaround for that?

**Comment by marianan** [comment]
Thank you for reporting this issue. iotedgedev is not yet updated to support python 3.8. We recommend running it on Ubuntu 18.04 until the python support is upgraded for iotedgedev.
