### ISSUE TITLE
AppCenterDistributeV3 Deploying: keep getting "503 Service Temporarily Unavailable"

### ISSUE THREAD

**Issue by zoli13** [microsoft/azure-pipelines-tasks#15404]
**Issue**

We use App Center Distribute v3 Task in our VSTS, to upload our Xamarin builds to App Center for testing purpose.
Yesterday it suddenly stopped working, with error, and after 1 day, it still fails with this "temporary" error:

Agent version:
*2.153.1*

`Initialize job	succeeded <1s`
`Download Artifacts succeeded 41s`

`DEV Deploy 1 error 1s`
`"<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.15.10</center>\r\n</body>\r\n</html>\r\n"
http response code: 503`

`PROD Deploy skipped`
`TEST Deploy skipped`
`UAT Deploy skipped`
`Finalize Job succeeded`

**Error Details**

`2021-10-14T05:20:52.3781640Z ##[section]Starting: DEV Deploy   `
`2021-10-14T05:20:52.3967880Z`
`==============================================================================`
`2021-10-14T05:20:52.3968040Z Task         : App Center distribute`
`2021-10-14T05:20:52.3968080Z Description  : Distribute app builds to testers and users via Visual Studio App Center`
`2021-10-14T05:20:52.3968120Z Version      : 3.160.2`
`2021-10-14T05:20:52.3968160Z Author       : Microsoft Corporation`
`2021-10-14T05:20:52.3968200Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute`
`2021-10-14T05:20:52.3968240Z `
`==============================================================================`
`2021-10-14T05:20:54.0728310Z ##[error]"<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.15.10</center>\r\n</body>\r\n</html>\r\n"`
`http response code: 503`
`2021-10-14T05:20:54.0781960Z ##[section]Finishing: DEV Deploy`

**Additional info**
The tasks run on a Mac. 
Last time we used succecssfully was 3 days ago. 
Other tasks (nuget/build android/ios/etc) run fine, but the App Center distribute fails at step Deploying.
Since last successful run, the mac had a macOS update: macOS Catalina -> macOS Big Sur (latest)
Just mentioning this, as this is the only thing what has changed, no idea if any connection, but should not.

**YAML**
`steps:`
`- task: AppCenterDistribute@3`
`  displayName: 'DEV Deploy'`
`  inputs:`
`    serverEndpoint: appcenterM2`
`    appSlug: 'xxxxx/xxxxxx'`
`    appFile: '$(System.DefaultWorkingDirectory)/xxxxxx.iOS build/Ad-Hoc_DEV/Ad-Hoc/DEV/xxxxxx.iOS/bin/iPhone/Ad-Hoc/xxxx.ipa'`
`    symbolsIncludeParentDirectory: false`
`    releaseNotesInput: 'DEV - Ad-Hoc'`
`    isSilent: false`

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: 
AppCenterDistribute (V3 )

## Environment
- Server - TFS
- Ver:

**Comment by zoli13** [comment]
**Info**: it seems to affect multiple teams in our organization. Rumors are that it's due to new Win11 installations...

**Comment by johnborges** [comment]
> Having the same issue with on-premises server.
> 
> The issue is that task version is old, it says 3.160.2. Don't know how to update it, though. Task's name specifies only the major version: AppCenterDistribute@3.
> 
> [This extension](https://marketplace.visualstudio.com/items?itemName=MsAppCenter.app-center-distribute-v3&ssr=false#overview) is installed, but it haven't updated the task version.
> 
> Does anybody have any ideas on this?
@sergeyotro Shouldn't specifying AppCenterDistribute@3 just pull the latest 3.x.x?

**Comment by sergeyotro** [comment]
I was thinking the same, but in practice it didn't.
