### ISSUE TITLE
AzureResourceManagerTemplateDeployment output variables with double quotes

### ISSUE THREAD

**Issue by drewkg** [microsoft/azure-pipelines-tasks#15409]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Azure Pipelines
    Account - objectsinternational
    Project - KeithDrew.NET
    Build Definition - 56
- Agent - Hosted 
   
## Issue Description

[Include task name(s), screenshots and any other relevant details]
When using the AzureResourceManagerTemplateDeployment@4 task with output variables, the output variables value have a " in the value

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection:
        subscriptionId:
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'KeithDrew-$(Build.BuildId)'
        location: 'UK South'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/main.json'
        csmParametersFile: '$(Pipeline.Workspace)/azureDeploy.prod.parameters.json'
        overrideParameters: '-environment Ephemeral -ephemeralKey $(Build.BuildId).$(System.JobId).$(System.JobAttempt)'
        deploymentMode: 'Complete'
        deploymentName: 'KeithDrew.Net-$(Build.BuildId)'
        deploymentOutputs: 'KeithDrewNet'

This means when passing the variables to another task the output is something like '"keithdrewnet02de5928"', notice the extra " at the start and end of the value.

Some tasks can strip of the extra ",some cannot. For example 

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 
        appType: 'webApp'
        WebAppName: '$(KeithDrewNet.appServiceName.value)'
        packageForLinux: '$(Pipeline.Workspace)/Website.zip'
        DeploymentType: 'webDeploy'
        RemoveAdditionalFilesFlag: true

errors with 

##[error]Error: Resource '"keithdrewnet02de5928"' doesn't exist. Resource should exist before deployment

### Task logs

##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.environment.type;]"String"
Updated output variable 'KeithDrewNet.environment.type', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.environment.value;]"Ephemeral"
Updated output variable 'KeithDrewNet.environment.value', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.appServiceName.type;]"String"
Updated output variable 'KeithDrewNet.appServiceName.type', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.appServiceName.value;]"keithdrewnet02de5928"
Updated output variable 'KeithDrewNet.appServiceName.value', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.keyVaultName.type;]"String"
Updated output variable 'KeithDrewNet.keyVaultName.type', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.keyVaultName.value;]"keithdrewnet-02de5928-kv"
Updated output variable 'KeithDrewNet.keyVaultName.value', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.sqlServiceName.type;]"String"
Updated output variable 'KeithDrewNet.sqlServiceName.type', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.sqlServiceName.value;]"keithdrewnet-02de5928-sql"
Updated output variable 'KeithDrewNet.sqlServiceName.value', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.sqlDatabaseName.type;]"String"
Updated output variable 'KeithDrewNet.sqlDatabaseName.type', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet.sqlDatabaseName.value;]"keithdrew.net"
Updated output variable 'KeithDrewNet.sqlDatabaseName.value', which contains the outputs section of the current deployment object in string format.
##[debug]Processed: ##vso[task.setvariable variable=KeithDrewNet;]{"environment":{"type":"String","value":"Ephemeral"},"appServiceName":{"type":"String","value":"keithdrewnet02de5928"},"keyVaultName":{"type":"String","value":"keithdrewnet-02de5928-kv"},"sqlServiceName":{"type":"String","value":"keithdrewnet-02de5928-sql"},"sqlDatabaseName":{"type":"String","value":"keithdrew.net"}}

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by drewkg** [comment]
Please re open, as this is still an existing bug.  If you are not going to actually fix it at least have the decency to say Won't Fix!

**Comment by TomasMalecek** [comment]
My colleague came across the same behavior in AzureResourceManagerTemplateDeployment@3 of DevOps Server 2022 just yesterday. @v-jkarri, please reopen this issue.

**Comment by TomasMalecek** [comment]
This seems to be related: #16729 At least this comment certainly is: https://github.com/microsoft/azure-pipelines-tasks/issues/16729#issuecomment-1474782730

**Comment by RoystonS** [comment]
The output is JSON-stringified by default (according to the [documentation](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3#deployment-outputs)). Have you tried setting `useWithoutJSON` to `true` to prevent it from JSON-escaping the output?

**Comment by svrooij** [comment]
> I have no idea who would want to use `useWithoutJson: false`…. @TomasMalecek 

Because the resolution of my [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16283 ) took 12 months to be accepted and they wanted this for backwards compatibility… It makes absolutely no sense. Absolutely **no one** will be using that. I experimented with publishing my own versions of broken tasks to dev ops, that works quite well.
