### ISSUE TITLE
Passing Sensitive Pipeline Created Variables to AzureCLI@2 Task  

### ISSUE THREAD

**Issue by PatrickMessierGoC** [microsoft/azure-pipelines-tasks#15415]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureCLI@2

## Environment
Azure Pipelines
    
### Context
We have a use case where "sensitive" variables (ex.: username, database instance name, firewall rule names, etc.) are dynamically created as part of our Pull Request CI/CD Pipelines. We use AzureCLI@2 task to set up/configure some of the PR environment resources. 

[Documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) cleary states that secrets should NOT be created as part YAML pipelines but offer no alternative for dynamically created variable use case. 

Using KeyVaults and Pipeline variable groups are no option (since values are dynamic) and using pipeline variables direcly in the AzureCLI script as [suggested](https://github.com/microsoft/azure-pipelines-tasks/issues/9416#issuecomment-460991365) is not elegant as it prevents script reuse. Finally, using AzureCLI "arguments" is not an option either since corresponding values are echoed in clear text (unmasked) in the task's log. 

### Feature Requests

1. It would be great if AzureCLI@2 could support environment variable mapping (`env` argument) like [bash](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops) and [powershell](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops) task. This would allow us to pass sensitive variables to the AzureCLI script without them being echoed in the task's log.
2. Dreaming outloud here (!), another option would be to be able to dynamically create secret variables using a syntax like the following in a bash task.
 `echo "##vso[task.setvariable variable=${name};isOutput=${is_output};isSecret=true]${value}"`
Such variables would then be systematically masked in the pipeline task's log.
 
**Questions**

1. In the meantime, what are the existing options to pass dynamically created sensitive variables to an AzureCLI task?

Thanks.

**Comment by acatuttle** [comment]
Any progress on this? Support for environment variable mapping as suggested would also solve parsing issues that can be encountered when secret variables contain certain characters that are interpreted by PowerShell or Azure CLI.
