### ISSUE TITLE
AzureAppServiceManage Task - Stop standby slot

### ISSUE THREAD

**Issue by kamalsivalingam** [microsoft/azure-pipelines-tasks#15416]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureAppServiceManage@0  

**Question**  
How do i stop the standby slot after deploying and swapping the slot using AzureAppServiceManage task.
What is the "Action" parameter value to stop an app in a slot? Action parameter has a type "Stop Azure App Service". Could this be used along with slot parameter?

Here is the task from yml file which I tried and I get `Invalid Action selected error`
 - task: AzureAppServiceManage@0
                  condition: succeeded()
                  displayName: "Stop standby slot"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    Action: "Stop"
                    WebAppName: $(webAppName)
                    ResourceGroupName: $(resourceGroupName)
                    Slot: "standby"

**Comment by v-jkarri** [comment]
Please give "Stop Azure App Service" instead "Stop" for **Action** property and try to run pipeline. 

task: AzureAppServiceManage@0
condition: succeeded()
displayName: "Stop standby slot"
inputs:
azureSubscription: $(azureSubscription)
Action: "_**Stop Azure App Service**_"
WebAppName: $(webAppName)
ResourceGroupName: $(resourceGroupName)
Slot: "standby"
