### ISSUE TITLE
SqlAzureDacpacDeploymentV1: error when trying to run on Ubuntu 18.x agent

### ISSUE THREAD

**Issue by lfshr** [microsoft/azure-pipelines-tasks#15425]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-18.04

## Issue Description

Task yields the following error message on Ubuntu 18.x
> ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by v-jkarri** [comment]
Closing this issue as currently we are not supporting Ubuntu 18.X version.
