### ISSUE TITLE
PublishPipelineArtifact fails on "Rerun failed jobs"

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/azure-pipelines-tasks#15442]
It would be nice if this task was idempotent. Instead, it fails the second time it is run. That makes it impossible for a pipeline to succeed when choosing "Rerun failed jobs".

Repro: When for a failed pipeline I choose "Rerun failed jobs", the task fails with "##[error]Artifact <artifact_name> already exists for build nnnnn."

I suggest instead of erroring and failing, the task log a warning and succeed.

**Comment by anatolybolshakov** [comment]
Hi @BruceHaley this would be a possible breaking change for a customer who are waiting for exception in this case - but we could probably add some input to be able to set up such behavior.
Let us leave this as enhancement - we are working on more prioritized tickets at the moment, but will get back to this item once be able to.
