### ISSUE TITLE
Jenkins Queue Job v2 fails but the job is nevertheless queued

### ISSUE THREAD

**Issue by me21** [microsoft/azure-pipelines-tasks#15455]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question.

**Enter Task Name**: JenkinsQueueJob

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Azure Pipelines. Account name: azarubkin. Team project name: helloworld.

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:

Private agent. OS: Ubuntu 20.04. Agent version: 2.194.0.

## Issue Description

Every pipeline run is failing on JenkinsQueueJob stage. But Jenkins successfully queues and runs the job.
There is a bug in Jenkins issue tracker: https://issues.jenkins.io/browse/JENKINS-53869, so this maybe should be fixed on their side, but there has not been much activity recently. Is it possible to maybe add a parameter to JenkinsQueueJob in Azure pipelines to treat HTTP code 302 as success?

### Task logs

```
Starting: JenkinsQueueJob
==============================================================================
Task         : Jenkins queue job
Description  : Queue a job on a Jenkins server
Version      : 2.193.0
Author       : Microsoft
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/jenkins-queue-job
==============================================================================
Job creation failed.
HttpResponse.statusCode=302
HttpResponse.statusMessage=Found

Install the "Team Foundation Server Plug-in" for improved Jenkins integration
http://localhost:8080/pluginManager/available
##[error]Job creation failed.
Finishing: JenkinsQueueJob
```

**Comment by anatolybolshakov** [comment]
Hi @me21 sorry for the delay - we are currently working on more prioritized tickets, will get back to this request once be able to.

**Comment by denis-tikhomirov** [comment]
Hello @me21,
I have tried to repro the issue, but each start of JenkinsQueueJobV2 task returns code 201 after successful start of build in Jenkins.
Do you know any specific conditions to have repro of the issue? Could you please share info about used JenkinsQueueJobV2 task configuration (yaml) in Azure DevOps and job in Jenkins? Also would be great if you can provide logs of affected job started with marked "Enable system diagnostics" checkbox.

**Comment by denis-tikhomirov** [comment]
PR with workaround for this issue - https://github.com/microsoft/azure-pipelines-tasks/pull/16058
