### ISSUE TITLE
VSTestV2 task passes when tests encountered timeout

### ISSUE THREAD

**Issue by adrianvmsft** [microsoft/azure-pipelines-tasks#15467]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest@2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5396974&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7bfb7e0f-549d-5929-c603-6e8046613b9e

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: VSEngSS-MicroBuild2019-1ES

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
The timeout is specified via a run settings file:
```xml
<RunSettings>
  <!-- configuration elements -->
  <RunConfiguration>
    <!-- Specify timeout in milliseconds. A valid value should be greater than 0 -->
    <!-- 20 mins: 20 * 60 * 1000 = 1200000-->  
    <TestSessionTimeout>1200000</TestSessionTimeout>
  </RunConfiguration>
</RunSettings>
```
```yml
- task: VSTest@2
  inputs:
    testFiltercriteria: TestCategory!=FailsInCloud
    searchFolder: $(System.DefaultWorkingDirectory)\bin\
    runInParallel: true
    testAssemblyVer2: |
      $(BuildConfiguration)\**\*test.dll
      !**\obj\**
      !**\*Integration*.dll
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
    runSettingsFile: 'src\Test.runsettings'
    diagnosticsEnabled: true
    collectDumpOn: 'onAbortOnly' # Options: onAbortOnly, always, never
  displayName: Run Tests
  condition: and(succeeded(), ne(variables['SignType'], 'real'), ne(variables['SkipTests'], 'true'))
```
The test execution ran into a timeout issue, however the task was reported as passed. As I understand this correctly from the log, the value was reset because the test was considered flaky.
I found this post discussing a similar issue, however the suggestion was to turn off flaky test detection. That unfortunately is not possible in our case, because that would turn it off for the entire division.
https://stackoverflow.com/questions/66254101/visual-studio-test-task-errors-ignored-after-failed-tests-if-any-were-marked-as

Can we turn off flaky test detection for this task only in the Yml? I couldn't find anything in the task documentation:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops

### Task logs
```
##[error]Aborting test run: test run timeout of 1200000 milliseconds exceeded. 
##[debug]Processed: ##vso[task.logissue type=error;]Aborting test run: test run timeout of 1200000 milliseconds exceeded. 
Results File: D:\a\_work\_temp\TestResults\cloudtest_6de8f364c000000_2021-11-02_00_22_52.trx 
##[error]Test Run Aborted. 
##[debug]Processed: ##vso[task.logissue type=error;]Test Run Aborted. 
Total tests: Unknown 
Passed: 2304 
Skipped: 24 
Total time: 20.0012 Minutes 
##[debug]Exited vstest.console.exe with code 1. 
...
Execution Result Code 1 is non zero, checking for failed results 
##[debug]Feature Flag: TestExecution.UseNewRunSummaryAPIForSingleAgent Value is on 
##[debug]UseNewRunSummaryAPIForSingleAgent Feature Flag value True 
##[debug]Entering GetTestRunSummaryAsync 
##[debug]TestRunPublisher.GetTestRunSummaryAsync: Getting test run summary with run id: 28114598 using new summary api. Allow Retry: False 
##[debug]PERF: RetryHelper:ActionName System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryByOutcome>b__0(): took 45.6104 ms 
##[debug]Entering GetTestRunSummaryAsync 
##[debug]TestRunPublisher.GetTestRunSummaryAsync: Getting test run summary with run id: 28114598 using new summary api. Allow Retry: False 
##[debug]PERF: RetryHelper:ActionName System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryByOutcome>b__0(): took 30.9551 ms 
##[debug]Entering GetTestRunSummaryAsync 
##[debug]TestRunPublisher.GetTestRunSummaryAsync: Getting test run summary with run id: 28114598 using new summary api. Allow Retry: False 
##[debug]Leaving GetTestRunSummaryAsync 
##[debug]PERF: RetryHelper:ActionName System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestRunStatistic] <GetTestRunSummaryByOutcome>b__0(): took 30.1274 ms 
Failed tests if any were marked as flaky hence changing the exit code to 0
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by adrianvmsft** [comment]
I still think this issue should be revisited. Automatically ignoring test hangs is dangerous.

**Comment by puagarwa** [comment]
This issue should be revisited.
