### ISSUE TITLE
Array Transformations Are Incorrectly Escaped When Using Macro Predefined Variables in the Array  

### ISSUE THREAD

**Issue by bitwhipr** [microsoft/azure-pipelines-tasks#15476]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: FileTransform

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?  Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: hmb-egrants, egrants, eGrants.Alabama - PreProd 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2019 Standard

## Issue Description

[Include task name(s), screenshots and any other relevant details]

Name: Service Configuration Transform

**Description**: We are using the file transform task to transform a json configuration file. Within this configuration file we have an object array that represents a list of source paths. Using the transformation task, we are replacing the entire array with one declared in the variables section of the release pipeline. In one of the paths in the array, we are using the macro variables $(System.DefaultWorkingDirectory) and $(Release.PrimaryArtifactSourceAlias). The expansion of the variables works, however, it results in the object array becoming incorrectly escaped into a string instead of an actual array. I've included the array transformation variable value below and the result of the transformation.

Variable value: 

`[{"source":"$(System.DefaultWorkingDirectory)\\$(Release.PrimaryArtifactSourceAlias)\\drop\\Xml"}]`

Transformation result: 

`"[{\"source\":\"C:\\azagent\\A1\\_work\\r17\\a\\\\SomeArtifact\\\\drop\\\\Xml\"}]"`

**Possible Cause**:

I've noticed that when dealing with array transformations, you must escape backslashes (e.g. \\ ). This is unlike in a string transformation, where you can simply use an un-escaped backslash (e.g. \ ). This may be where the issue is coming from due to macro predefined variable paths getting expanded with an un-escaped backslash.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

- Used one macro variable in the array (e.g. [{"source":"$(System.DefaultWorkingDirectory)\\SomeArtifact\\drop\\Xml"}]), no change in behavior.
- Used un-escaped backslashes in the path (e.g. [{"source":"$(System.DefaultWorkingDirectory)\SomeArtifact\drop\Xml"}]), no change in behavior.
- Used hard coded path in the array with un-escaped backslashes (e.g. [{"source":"C:\azagent\A1\_work\r17\a\SomeArtifact\drop\Xml"}], no change in behavior.
- Used hard coded path in the array with escaped backslashes (e.g. [{"source":"C:\\azagent\\A1\\_work\\r17\\a\\SomeArtifact\\drop\\Xml"}], **works**.

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by KocamanFaruk** [comment]
Hello,

I have the same problem with file transform task. Is there any workaround?
