### ISSUE TITLE
Invoking Azure Function results in timeout even with callback

### ISSUE THREAD

**Issue by superkevin813** [microsoft/azure-pipelines-tasks#15470]
Release link: https://msdata.visualstudio.com/Vienna/_releaseProgress?_a=release-environment-logs&releaseId=350878&environmentId=1372251

I am using Call back pattern for azure function in Pre deployment gate.
The call back http request return following error:

**Status Code**: 500 Internal Server Error

**Header:**
X-TFS-ProcessId : b4a50dae-0ba7-4a92-b9cd-0b4343db9218
ActivityId : 3197bd8b-a388-4011-9160-d43ee6c4c2e3
X-TFS-Session: 3197bd8b-a388-4011-9160-d43ee6c4c2e3
X-VSS-SenderDeploymentId: f74dff37-2fb6-e5e9-ea77-6ea9785ace8f
X-VSS-UserData: a9ca44a6-9586-4bf3-bb99-a00766f68022:8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa

**Body:**
{
    "$id": "1",
    "innerException": null,
    "message": "The orchestration session 1143cd0456784d9397b70c0c87c02da7_ca8309bbacd74ebcb0ab444f0457b79f_ce9c9cdaade34f21b6f780874cc11f99 not found for hub Gates.",
    "typeName": "Microsoft.VisualStudio.Services.Orchestration.Server.OrchestrationSessionNotFoundException, Microsoft.VisualStudio.Services.Orchestration.Server, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "typeKey": "OrchestrationSessionNotFoundException",
    "errorCode": 0,
    "eventId": 3000
}

The Gate looks like still in pending status (Not failure soild red cross mark ) but log said:
2021-11-03T05:54:48.1981251Z POST https://releasepipelinefunctions.azurewebsites.net/api/Test?code=cgzCFV2TgCdRIsLbl5XSnvXU0d7Dbqv3CuzuUYvaZrbStaxe2PaHaw==&
				Response Code: 0
				Response: An error was encountered while processing request. Exception: 
Exception Message: The request timed out after 60 seconds as no response was received. (type TimeoutException)

**Is there any recent service issue on ADO side failing to keep track of pending task after timeout ?**

**Comment by anatolybolshakov** [comment]
Hi @superkevin813 this repo is mostly for pipeline tasks - please open a ticket on https://developercommunity.visualstudio.com/search?space=21 for DevOps related questions.

**Comment by anatolybolshakov** [comment]
Let me close this one here since it's not related to the pipeline tasks.

**Comment by tokleine** [comment]
@anatolybolshakov I have a similar issue. I am using YAML build pipeline that builds and the deploys my Python function app. After deployment I give the function a 2 minute delay and then do two calls, one that should give a 200 response but with a schema validation error message as response and a correct request that will invoke an machine learning pipeline. 

Incl other overhead times, there are more then 3 minutes between slot swapping and my function app requests. But it still fails with following error:

Request body: ... dummy body to trigger a BUSINESS_ERROR but still get a 200 response ...

				Response Code: 0
				Response: An error was encountered while processing request. Exception: 
Exception Message: The request timed out after 60 seconds as no response was received. (type TimeoutException)

What am I doing wrong?
