### ISSUE TITLE
Download Secure Files false positive

### ISSUE THREAD

**Issue by tweaty123** [microsoft/azure-pipelines-tasks#15479]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadSecureFileV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    capita-ccs/Mobile App/Pipelines/Mobile App Nightly/2021.11.05.01

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
    Pool: Azure Pipelines, Image: windows-2019, Agent: Hosted Agent

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Download Secure file was 'successful', but the content of the file, once inspected had been overwritten with: -
{
"$id": "1",
"innerException": null,
"message": "TF15004: The download request signature has expired.",
"typeName": "Microsoft.TeamFoundation.Framework.Server.DownloadTicketValidationException, Microsoft.TeamFoundation.Framework.Server",
"typeKey": "DownloadTicketValidationException",
"errorCode": 0,
"eventId": 4008
}

### Task logs

![image](https://user-images.githubusercontent.com/93766388/140490950-2f33e70c-f3ab-4bc6-bf86-a61491552b6c.png)

Starting: Download Dev Server Secrets
==============================================================================
Task         : Download Secure File
Description  : Downloads a secure file
Version      : 0.0.9
Author       : Matt Labrum
Help         : 
==============================================================================
Downloading secureFileId=83f6b069-e895-42c9-b51e-cc98a8647903 to destFile=D:\a\1\s\dev_server\build\server\mobilize-firebase.json
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5500) Warning: Use Cipheriv for counter mode of aes-256-ctr
Wrote secure file to D:\a\1\s\dev_server\build\server\mobilize-firebase.json
Finishing: Download Dev Server Secrets

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by KonstantinTyukalov** [comment]
Hi, @tweaty123! As I can see from providing logs you currently using the DownloadSecureFiles@0 task. This version is out of support, could you please try to use DownloadSecureFiles@1 and see if the issue still persists? 

To switch the version of the task you just need to change the major task version in the YAML definition of your pipeline:

instead of:
```yml
- task: DownloadSecureFile@0
```
type this:
```yml
- task: DownloadSecureFile@1
```

If you use classic editor, please just switch the task version in the task settings menu.

**Comment by tweaty123** [comment]
i'm afraid i don't see that option

![image](https://user-images.githubusercontent.com/93766388/146551956-2866f3ea-aef4-47a0-bf4a-603a5d38f6f2.png)

**Comment by tweaty123** [comment]
Good Evening,

I have moved to the Microsoft task and ensured that the task version is the latest.

Thank you for your help.

Kevin Tweats

**Comment by KonstantinTyukalov** [comment]
@tweaty123, thank you for the update.

Does this mean the issue was resolved after you switched to the Microsoft task? 

Also, could you please check your last reply on GitHub and edit it a bit if needed? I think that you might have left some information that could be sensitive.

**Comment by tweaty123** [comment]
@KonstantinTyukalov yes, the issue is now resolved, thank you.
