### ISSUE TITLE
AzureFunctionApp@1 has a bug in appSettings parsing

### ISSUE THREAD

**Issue by Yevhen-Mordak** [microsoft/azure-pipelines-tasks#15481]
## Required Information
The task AzureFunctionApp@1 has a bug in appSettings argument parsing. The trailing space is required after each line in appSettings for proper parsing.

*Type*: Bug
*Task Name*: AzureFunctionApp@1

## Environment
- Server - Azure Pipelines
- Agent - Hosted 

## Issue Description
the all marked trailing spaces are mandatory. 
![image](https://user-images.githubusercontent.com/26307890/140558634-22d2d7a6-d0ff-4866-9e87-7ca4c67631ba.png)

![image](https://user-images.githubusercontent.com/26307890/140559689-305b4b19-7e8e-4fb4-9b2a-d885282397e2.png)

Desired fix: new line is enough and trailing spaces have zero influence on how appSettings are parsed.

**Comment by v-ibshaik** [comment]
Hello Yevhen,

Its not trailing spaces. app settings is considered as single string and we need spaces between two settings. it is documented on official task doc: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops#arguments

**Comment by Yevhen-Mordak** [comment]
I know spaces are required. I just raise I'm the second person in a team who spent hours to figure out that. 

Can you please add '\n' as a valid separator same as the space? that would be great

**Comment by v-jkarri** [comment]
Issue has been fixed and it will take 30 to 45 days to deploy the fix in production.

**Comment by LouOtway** [comment]
This bug is back.
