### ISSUE TITLE
Bug: AppCenterDistribute completes OK when there was an error

### ISSUE THREAD

**Issue by guillermo-aguirre** [microsoft/azure-pipelines-tasks#15489]
*Type*: Bug
**Enter Task Name**: AppCenterDistribute

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

The AppCenter API sometimes returns a 404 error when sending the artifact, yet the AppCenterDistribute task completes with status OK even though it has not actually been deployed. The error is visible on the pipeline console:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): {"message":"Resource not found: /v0.1/apps/.... Correlation ID: fd3ada02-0d4c-4c9d-88f0-2a5f7831dceb","statusCode":404,"code":"Not Found"}
http response code: 404

**Comment by Kylar182** [comment]
Same here

**Comment by m1chal-z** [comment]
We also have this issue. Can we expect that this problem will be solved in near future?

**Comment by ninjaonsafari** [comment]
@Kylar182 @m1chal-z  have you found a fix for this?

**Comment by Kylar182** [comment]
I gave up when this happened and have been sadly doing manual builds. I'll look into it again.

**Comment by Nitishreddy787** [comment]
@guillermo-aguirre @Kylar182  @m1chal-z  @ninjaonsafari have you found a fix for this?

**Comment by Kylar182** [comment]
> @guillermo-aguirre @Kylar182 @m1chal-z @ninjaonsafari have you found a fix for this?

Yes, I stopped using AppCenter
