### ISSUE TITLE
Feature Request: [Pipeline Caching] Improve Self-hosted caching

### ISSUE THREAD

**Issue by thurfir** [microsoft/azure-pipelines-tasks#15497]
When running self-hosted build agents it takes almost the same time to download the cached data than it takes to run the actual process.

Can you please either:

- Add a local cache step to the job (remote cache -> local cache -> agent) 
or
 - Allow to store the cached data locally?

**Comment by thurfir** [comment]
Hi, this would still be an huge boon for our build times.

**Comment by sychare** [comment]
Shame this still isn't supported. Lots of network traffic for what could be an on-disk/local cache for self-hosted agents.

**Comment by kkalisz** [comment]
Any news on that? Or at least do we have some workarounds available?

**Comment by Borda** [comment]
this would be very usefull especially with respect to https://github.com/microsoft/azure-pipelines-agent/issues/4113

**Comment by benlongo** [comment]
This would be nice to have
