### ISSUE TITLE
How to get preview before run AzureResourceManagerTemplateDeployment@3 task in yaml Azure DevOps pipeline ?

### ISSUE THREAD

**Issue by Philippe85** [microsoft/azure-pipelines-tasks#15514]
In Azure DevOps pipeline in Yaml, I use the task "AzureResourceManagerTemplateDeployment@3" to deploy ARM Templates and create/update azure resources.
But I would want to get a Preview before run the real deployment.
How to do ?

The "Deployment Mode" argument could propose the "What if" deployment mode ?

Thanks

**Comment by Philippe85** [comment]
I don't understand this "stale" ! I never have answer on my question.
We need a "preview" mode as the "preview" on Terraform, to see the changes that will be done on Azure ressources, before to execute really the changes.

**Comment by mleneveut** [comment]
+1
