### ISSUE TITLE
Migrate CopyFiles task to Node 10

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-tasks#15516]
We need to migrate CopyFiles to Node 10.

**Comment by anatolybolshakov** [comment]
At the moment we are re-checking the issues we observed with migration previously - to make sure that they are not related to the migration itself.

**Comment by r-bird** [comment]
This would be awesome.
For example, the task `PipAuthenticate@1` generates this waring:
```
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
```

**Comment by guillermo-aguirre** [comment]
AppCenterDistribute@3 is also throwing the Node 6 warning. Is there a general issue to migrate all tasks that use Node 6 to Node 10 or should we create one per task?

**Comment by EzzhevNikita** [comment]
Due to the deployment freeze, there will be a delay with the rollout of the changes for this item. They will be deployed approximately at the end of January.
