### ISSUE TITLE
TwineAuthenticate throws warning about migrating from Node6 to Node10

### ISSUE THREAD

**Issue by K3UL** [microsoft/azure-pipelines-tasks#15519]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: **TwineAuthenticate@1**  

## Environment
- **Server - Azure Pipelines**

## Issue Description

When using the TwineAuthenticate@1 taks, I get the following warning : `##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

Note that the link included does not work, and just takes me to Bing search.

**Comment by namrog84** [comment]
The aka.ms/migrateTaskNode10 redirects to this page: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md

I am seeing the same bug/issue, and I think the task needs to be updated
