### ISSUE TITLE
`Maven@3` task now requires agent version -gt 2.181.2, breaking Azure DevOps Server 2020.1.1 default max of 2.181.2

### ISSUE THREAD

**Issue by scrthq** [microsoft/azure-pipelines-tasks#15529]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MavenV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: Azure DevOps Server 2020 Update 1.1
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: N/A

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: N/A

    - If using private agent, provide the OS of the machine running the agent and the agent version: amazon-linux-2 (RHEL based) @ agent 2.181.2

## Issue Description

Maven task now requires a minimum agent version greater than 2.181.2 unexpectedly, resulting in on-premises Azure DevOps Server pipelines breaking due to that version having a default maximum agent version of 2.181.2.

Forcing an upgrade to the latest agent version during agent host bootstrapping and blocking the downgrade is not a trivial option for us to pursue.

### Task logs

N/A - Task fails to start due to not having an agent available with the required capabilities.

## Troubleshooting
Attempted to update the agents in the pool using the native Update All Agents button in the interface, but agents are not able to be updated past 2.181.2.

### Error logs

`##[error]No agent found in pool linux which satisfies the specified demands: maven, Agent.Version -gtVersion 2.181.2`

**Comment by scrthq** [comment]
Worth noting that the Task.json for both MavenV2 and MavenV3 tasks still list the following: `"minimumAgentVersion": "1.89.0",`

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV2/task.json#L27
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV3/task.json#L27

**Comment by kuleshovilya** [comment]
@scrthq Agent seems fine, looks like a maven capabiliy issue. 
Are you sure that this capability is present in the agent settings?
![image](https://user-images.githubusercontent.com/87485027/143245730-e0091ca0-f96c-4f66-a0a4-2ae2a6e47aa1.png)

**Comment by kuleshovilya** [comment]
@scrthq Any update on the issue?

**Comment by kuleshovilya** [comment]
@scrthq I'll close the issue, for now, please feel free to reopen the ticket if something appears or ping me at v-ikuleshov@microsoft.com
