### ISSUE TITLE
VSTest - ##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

### ISSUE THREAD

**Issue by Bouke** [microsoft/azure-pipelines-tasks#15526]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  Bug
*Type*: Bug

**Enter Task Name**: VSTest@2

## Environment
Hosted Azure DevOps Pipeline.

## Issue Description

Each of our builds now produces the following warning:

> ##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

This has been happening for days now. We're failing the build on _any_ warning by the VSTest task, as the task has been unreliable in reporting issues itself. So _every_ build is now failing due to this. Why isn't this task updated yet, do the responsible teams at Microsoft not communicate with each other and proactively resolve deprecations?

**Comment by anatolybolshakov** [comment]
Hi @Bouke thanks for reporting! There seems to be a duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/15187
We are also going to disable Node 6 deprecation warnings in [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15493) and make sure that all in-the-box tasks will be migrated in time - so there is no need to worry about in-the-box tasks.
