### ISSUE TITLE
IIS Web App Manage issue with Windows Server 2022

### ISSUE THREAD

**Issue by geskill** [microsoft/azure-pipelines-tasks#15528]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug or redirect to appropriate development team

**Enter Task Name**: IIS web app manage  

**AppCmdOnTargetMachines.ps1**
```
function Add-SslCert
{
    ///.....

        $result = Invoke-VstsTool -Filename "netsh" -Arguments $showCertCmd
        $isItSameBinding = $result.Get(4).Contains([string]::Format("{0}:{1}", $hostname, $port))

    ///.....
}
```

On Windows Server 2022 `$result.Get(4)` will return an empty string. The correct result for Windows Server 2022 will be gathered by `$result.Get(6)`. 

Calling `netsh http show sslcert ipport=0.0.0.0:443` will return on Windows Server 2022
```
PS C:\Users\Administrator> netsh http show sslcert ipport=0.0.0.0:443

SSL Certificate bindings:
-------------------------



    IP:port                      : 0.0.0.0:443
    Certificate Hash             : f7eaa06813007460b6fb5ea52696d6fec15afXXX
    Application ID               : {4dc3e181-e14b-4a21-b022-59fc669b0XXX}
    Certificate Store Name       : WebHosting

```

Calling `netsh http show sslcert ipport=0.0.0.0:443` will return on Windows Server 2019
```
PS C:\Users\Administrator> netsh http show sslcert ipport=0.0.0.0:443

SSL Certificate bindings:
-------------------------

    IP:port                      : 0.0.0.0:443
    Certificate Hash             : f7eaa06813007460b6fb5ea52696d6fec15afXXX
    Application ID               : {4dc3e181-e14b-4a21-b022-59fc669b0XXX}
    Certificate Store Name       : WebHosting

```

**There are 2 more line breaks on Windows Server 2022!**

**Comment by v-ibshaik** [comment]
Hello ,

Can you please confirm Power shell Version?

Thanks.

**Comment by geskill** [comment]
Windows Server 2022
`> (Get-Host)`
```
Name             : ConsoleHost
Version          : 5.1.20348.320
InstanceId       : 5880cfc6-00f8-40e2-b4c0-15743563aXXX
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : fi-FI
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by v-ibshaik** [comment]
Hello geskill,

This issue is related to powershell. can you please raise the issue in following repo:
https://github.com/PowerShell/PowerShell/issues

Thanks.

**Comment by geskill** [comment]
My best guess is, that this is an issue of Netsh `show sslcert` command for http, because the same issue occours using CMD.

**Comment by v-ibshaik** [comment]
Hello geskill,

We have created the incident for this issue and working with support team. We will update the status once we get it from support team

Thanks.

**Comment by v-jkarri** [comment]
Hello Geskill, Support team is asking the below details. Can you please provide us.

1. Whether the netsh command is running in Azure VM or Windows PC?
2. Please help me with the screenshots of System info window, Windows version window, TPM status , DSREG logs.
Check your TPM stat. Open windows run and enter the command tpm.msc. In the resulting window, at the central pane under Status, make sure that "The TPM is ready for use" is mentioned. Please share that.
Please search for cmd from search tray and type dsregcmd/status. Kindly copy the contents in a notepad and share the file.

**Comment by geskill** [comment]
1. Dedicated Server from Hetzner running Windows Server 2019 with hyper-v. One virtual instance is Windows Server 2022.
2. The TPM is ready for use
```
Device name	integration
Processor	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
Installed RAM	29,3 GB
Device ID	FA6FFCFE-4B9B-4B4D-89E8-
Product ID	00453-60520-36961-
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows Server 2022 Standard
Version	21H2
Installed on	‎3.‎11.‎2021
OS build	20348.380


+----------------------------------------------------------------------+
| Device State                                                         |
+----------------------------------------------------------------------+

             AzureAdJoined : NO
          EnterpriseJoined : NO
              DomainJoined : NO
               Device Name : integration

+----------------------------------------------------------------------+
| User State                                                           |
+----------------------------------------------------------------------+

                    NgcSet : NO
           WorkplaceJoined : NO
             WamDefaultSet : NO

+----------------------------------------------------------------------+
| SSO State                                                            |
+----------------------------------------------------------------------+

                AzureAdPrt : NO
       AzureAdPrtAuthority : NO
             EnterprisePrt : NO
    EnterprisePrtAuthority : NO

+----------------------------------------------------------------------+
| IE Proxy Config for Current User                                     |
+----------------------------------------------------------------------+

      Auto Detect Settings : YES
    Auto-Configuration URL :
         Proxy Server List :
         Proxy Bypass List :

+----------------------------------------------------------------------+
| WinHttp Default Proxy Config                                         |
+----------------------------------------------------------------------+

               Access Type : DIRECT

+----------------------------------------------------------------------+
| Ngc Prerequisite Check                                               |
+----------------------------------------------------------------------+

            IsDeviceJoined : NO
             IsUserAzureAD : NO
             PolicyEnabled : NO
          PostLogonEnabled : YES
            DeviceEligible : NO
        SessionIsNotRemote : NO
            CertEnrollment : none
              PreReqResult : WillNotProvision

For more information, please visit https://www.microsoft.com/aadjerrors
```

**Comment by v-jkarri** [comment]
Hello Geskill, Support team is asking the below details of Windows Server 2022. Can you please provide us.

Kindly help us with the below information from the affected user's machine: 

Screenshots:
1) Click on search>type "access work or school">>open>>take a screenshot and attach it to the ticket.
2) Click on search and type TPM.MSC and get the screenshot for the status of TPM and attach it to the ticket.
3) Click on start and type WINVER and get the screenshot of the Windows version screen and attach it to the ticket. 

Logs:
1) System logs:-
a. Select the start button, type Msinfo32 and hit enter
b. This will open the "System Information" pop-up window.
c. Click File > Save and save it on the desktop.
d. Please ZIP the file and attach it on the ticket 

2) DSREGCMD Logs:-
a. Open Command Prompt as Admin
b. Run the command "dsregcmd /status > %USERPROFILE%\desktop\dsregcmdstatus.txt"
c. A file will be created on the user's desktop with the name dsregcmdstatus.txt
d. Attach the file on the ticket.

**Comment by geskill** [comment]
![2021-12-15 11_03_22-192 168 2 12 - Remotedesktopverbindung](https://user-images.githubusercontent.com/6826752/146166094-3233c142-8b04-4b92-a5cb-2107196cb18d.png)

![2021-12-15 11_03_40-192 168 2 12 - Remotedesktopverbindung](https://user-images.githubusercontent.com/6826752/146166090-a6a689a2-f730-453e-b4d4-1966b6aa2f3f.png)

[win-server-2022.nfo.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7718272/win-server-2022.nfo.zip)

[dsregcmdstatus.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7718271/dsregcmdstatus.txt)

**Comment by v-jkarri** [comment]
Thank you Geskill.

**Comment by v-jkarri** [comment]
Hi Geskill, 
Please find the response below from support team.
"please provide the access work or school screenshot from the user We need to know if the device is joined to MS domain or not "

**Comment by geskill** [comment]
i guess you find this information within the DSREG logs. The vm is not joined nor work or school account connected. It is a local account.

![2021-12-15 12_35_34-192 168 2 12 - Remotedesktopverbindung](https://user-images.githubusercontent.com/6826752/146179545-4b0cec31-4568-4fac-b2db-ae9bbde38cfe.png)

**Comment by v-jkarri** [comment]
Hi Gesklli, 

As discussed with support team, Can you please check with your local IT support team for the windows server 2022 issue as it's not related to MS device they can't support.

**Comment by geskill** [comment]
Two weeks ago, i implemented a workaround until this issue is fixed.
