### ISSUE TITLE
PipAuthenticate: uses Node 6 execution handler, which will be deprecated 

### ISSUE THREAD

**Issue by sonnehansen** [microsoft/azure-pipelines-tasks#15533]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: PipAuthenticate

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops#open-source

## Environment
- Server - Azure Pipelines (hosted)
    
## Issue Description
Warning that Node 6 will be deprecated. Similar to #15525 and mentioned in #15516 

```
Starting: Authenticate to Azure Artifacts PyPi (populates PIP_EXTRA_INDEX_URL)
==============================================================================
Task         : Python pip authenticate
Description  : Authentication task for the pip client used for installing Python distributions
Version      : 1.177.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/pip-authenticate
==============================================================================
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
Successfully added auth for 1 internal feeds and 0 external endpoint.
Finishing: Authenticate to Azure Artifacts PyPi (populates PIP_EXTRA_INDEX_URL)
```

**Comment by gjerokrsteski** [comment]
It's similar in my company. We use the task in many pipelines and are very happy if you provide an upgrade to Node10 - Best regards, Gjero

**Comment by anatolybolshakov** [comment]
Hi @gjerokrsteski @sonnehansen thanks for reporting!
We are going to disable Node 6 deprecation warnings in [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15493) and make sure that all in-the-box tasks will be migrated in time - so there is no need to worry about in-the-box tasks.
