### ISSUE TITLE
DISABLE_NODE6_DEPRECATION_WARNING does not suppress the annoying Node 6 execution handler warning

### ISSUE THREAD

**Issue by jozefizso** [microsoft/azure-pipelines-tasks#15539]
We have defined the `DISABLE_NODE6_DEPRECATION_WARNING=true` variable for our Azure Pipelines builds as described here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md

The variable has no effect and official tasks from Microsoft still generate the `##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.` warning.

**Comment by anatolybolshakov** [comment]
Hi @jozefizso this agent knob will be rolled out with the next agent release - we will let you know once it is available.

**Comment by anatolybolshakov** [comment]
Hi @jozefizso this knob has been rolled out, we also disabled this notification at the moment - so closing this item as resolved. Please let us know if you have any other questions.
