### ISSUE TITLE
JSON File transform of arrays doesn't always work

### ISSUE THREAD

**Issue by Roy-Foreman** [microsoft/azure-pipelines-tasks#15549]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: File Transfrom (version 1)

## Environment
- Server - TFS on-premises?
    
 -  version: Dev18.M170.6 
 - Agent: Private: 
 - OS: Windows 2016

## Issue Description

Variable transformation for an array that is a list of file paths is being trasnformed as a string. Other arrays with simple text are okay
for example
variable&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;value
appsetting.names  &emsp;&emsp;[ "name 1", "name 2" ] 
is correctly updated in the target json file as an array
[ "name 1", "name 2" ]

variable&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;value
appsetting.location&emsp;&emsp;[ "\\\\acd.com\\location1", "\\\\acd.com\\location2", "\\\\acd.com\\location3" ]
is incorrectly updated in the target json as a string 
"[\\"\\\\\\\\acd.com\\\\location1\\", \\"\\\\\\\\acd.com\\\\location2\\", \\"\\\\\\\\acd.com\\\\location3\\" ]"

when expected
[ "\\\\\\\\acd.com\\\\location1", "\\\\\\\\acd.com\\\\location2", "\\\\\\\\acd.com\\\\location3" ]

### Task logs

[VS issue.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7604927/VS.issue.zip)

**Comment by PhilipsonJoseph** [comment]
@Roy-Foreman  the `\` is considered as a escape character. Hence you need to add additional slash for every slash if it is needed on string. In your case you have to provide the variable value as `[ "\\\\acd.com\\location1", "\\\\acd.com\\location2", "\\\\acd.com\\location3" ]`

**Comment by Roy-Foreman** [comment]
When entering a normal string via CI/CD via Azure DevOps it is not required to escape these characters. However I will try out your suggestion to see if that resolves the issue.

Regards

Roy Foreman

**Comment by Roy-Foreman** [comment]
Ok, I tested your suggestion and it works.  So to clarify: When entering an object or array definition into a variable via Azure Dev Ops File Transform task, escape characters need to be escaped. When entering a string they do not as the transform escapes them whe applied.
