### ISSUE TITLE
AzurePowerShell error "Cannot read property 'retrieveSecret' of undefined"

### ISSUE THREAD

**Issue by JohnSchmeichel** [microsoft/azure-pipelines-tasks#15562]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell

## Environment
- Server - Azure Pipelines
    https://dev.azure.com/mseng, Domino, Validate Scripts (11869), build # 16467922

- Agent - Hosted or Private: Hosted
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

The Linux version of the AzurePowerShell task gives the error "Cannot read property 'retrieveSecret' of undefined". This started on the 193 or 195 version of the task, previous versions do not have this issue.

### Task logs

```
Starting: Azure PowerShell script: InlineScript
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.195.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting
==============================================================================
##[error]Cannot read property 'retrieveSecret' of undefined
Finishing: Azure PowerShell script: InlineScript
```

[logs_16472427.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7636251/logs_16472427.zip)

**Comment by glzbcrt** [comment]
Hello,

This issue is impacting all our pipelines. Please, provide a fix as soon as possible.

**Comment by d-daniel-de-sousa** [comment]
Hi,

This issue is impacting our deploy tasks. I tried to specify version, but doesnt work at all.

![image](https://user-images.githubusercontent.com/64017468/145422774-faef0eb9-7348-4a0e-811e-07029f350bed.png)

**Comment by v-saikumart** [comment]
@JohnSchmeichel  @glzbcrt @d-daniel-de-sousa Issue has been fixed and deployed the same. Please find below PR for reference.
https://github.com/microsoft/azure-pipelines-tasks/pull/15580

Thank you.
