### ISSUE TITLE
PowerShellOnTargetMachines fails using script block and user with a '$' character in username

### ISSUE THREAD

**Issue by jsblock78** [microsoft/azure-pipelines-tasks#15560]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShellOnTargetMachines

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  hp-ops, SFS , SDS Release, SDS_20211201.6, Promote to Dev, Attempt #4, Promote to Dev Run PowerShell on Target Machines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows10, 2.187.2

## Issue Description

When using credentials in the task that contain a dollarsign '$', they are not properly escaped when attempting to run the temporary file created by the task that has the contents of the script block. 

Issue is similar to this one:
https://github.com/microsoft/azure-pipelines-tasks/issues/4234

In the error below, you can see that it is supposed to execute the temporary file created by the task:
`C:\Users\$USERNAMEDOLLAR\AppData\Local\Temp\d8e3dd48-3dcb-41ac-b224-0f766c42a2b1.ps1`

but it actually attempts to execute:
`C:\Users\\AppData\Local\Temp\d8e3dd48-3dcb-41ac-b224-0f766c42a2b1.ps1`

because $USERNAMEDOLLAR is not escaped and is replaced with null as no variable by that name has been initialized.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2021-12-01T18:54:17.1265616Z ================================================ localhost ================================================
2021-12-01T18:54:17.1907428Z ##[command]& 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' -NoLogo -NoProfile -NonInteractive 
2021-12-01T18:54:17.1908822Z -ExecutionPolicy Unrestricted -Command ". 
2021-12-01T18:54:17.1909880Z 'C:\Users\$USERNAMEDOLLAR\AppData\Local\Temp\d8e3dd48-3dcb-41ac-b224-0f766c42a2b1.ps1'"
2021-12-01T18:54:17.1910455Z 
2021-12-01T18:54:17.2898788Z . : The term 'C:\Users\\AppData\Local\Temp\d8e3dd48-3dcb-41ac-b224-0f766c42a2b1.ps1' is not 
2021-12-01T18:54:17.2900013Z At line:1 char:1
2021-12-01T18:54:17.2900945Z + & 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' -NoLogo ...
2021-12-01T18:54:17.2902080Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-01T18:54:17.2903391Z     + CategoryInfo          : NotSpecified: (. : The term 'C...b1.ps1' is not :String) [], RemoteException
2021-12-01T18:54:17.2904622Z     + FullyQualifiedErrorId : NativeCommandError
2021-12-01T18:54:17.2905372Z  
2021-12-01T18:54:17.2905647Z 
2021-12-01T18:54:17.3416050Z recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
2021-12-01T18:54:17.3417065Z 
2021-12-01T18:54:17.4104204Z of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jsblock78** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/15563 will fix for $

I am sure there are other characters that could be problematic at this same line (allowed in a username or file path), such as hash mark or grave accent - but I ran into an immediate issue with $ - so that is all I addressed, sorry.

**Comment by v-ibshaik** [comment]
Hello Jeffrey,

I have verified the your code changes. Its working expected only.
Could you please update the task.json and  few checks are failing in PR please resolve it.

Thanks.

**Comment by jsblock78** [comment]
Hello @v-ibshaik,

Which task.json gets updated? The changes in the PR only modified the `Tasks/Common/RemoteDeployer/RunPowerShellScriptJob.ps1` file, used by the RemoteDeployer module, which appears to be used by `AzureFileCopy` and `PowerShellOnTargetMachine` tasks. Do both of those tasks get the task.json updated, or neither?

In regards to the checks, I see that two have passed - but it appears that the CI tasks have not run executed for my PR. I do not see any failures. I am not sure how to get these to execute. Is it possible that the `Build pull requests from forks of this repository` setting is not enabled in the following Pipelines: azure-pipelines-tasks.ci-linux, azure-pipelines-tasks.ci-macos, azure-pipelines-tasks.ci-windows

![image](https://user-images.githubusercontent.com/1936710/150991790-8ba6db6f-d604-4637-8724-9b965dbb070c.png)

**Comment by jsblock78** [comment]
@v-ibshaik I see that other users whose checks have passed have created a branch directly in this project instead of attempting a PR from a fork. Is this the route I should take? Do I have permissions to do so?

**Comment by v-ibshaik** [comment]
@jsblock78 Could you please update the task.json for following tasks and build again.
AzureFileCopyV2,AzureFileCopyV3,AzureFileCopyV4 andPowerShellOnTargetMachinesV3.

Thanks.

**Comment by jsblock78** [comment]
@v-ibshaik I have updated the tasks. Could you kick off the pipeline again so that the checks complete?

**Comment by v-ibshaik** [comment]
@jsblock78  PR got merged.
