### ISSUE TITLE
DotNetCore currently does not support using an encrypted Api Key #7160

### ISSUE THREAD

**Issue by woeterman94** [microsoft/azure-pipelines-tasks#15569]
Problem: can't push packages to nuget.org with dotnet nuget push task without exposing API key in build definition

**Environment**
Server - VSTS Online
Agent - Hosted 2017
**Error logs**
Using authentication information for the following URI: https://api.nuget.org/v3/index.json
Error: DotNetCore currently does not support using an encrypted Api Key.
Packages failed to publish

Reopening https://github.com/microsoft/azure-pipelines-tasks/issues/7160 as the issue is still here.

**Comment by cloudlene** [comment]
I'm trying to use the API Key using a Service Connection in Azure DevOps.  I've selected the said service connection in the NuGet server dropdown in the .Net core task (command nuget push).

I'm using .Net 6.0.x SDK.

I'm getting the error "DotNetCore does not support using an an encrypted key".  I am willing to use unencrypted environment variables.  The others' issue seems to be that they don't want to leave the key in plain text which I'm not doing.  

So, what am I missing?

**Comment by RomainHautefeuille** [comment]
The original post is misleading. You are experiencing the same error as all of us while trying to use a Service Connection configured with an API Key:

> DotNetCore does not support using an an encrypted key

I don't think you are missing anything in that regard: AFAIK this is just not supported yet.
Until the original issue is addressed, the [main workaround](https://github.com/microsoft/azure-pipelines-tasks/issues/7160#issuecomment-509044113) is to use a custom push task with variables for ServerUrl and APIKey.
The question now arises of how to hide the APIKey when using variables? And the answer is using [Variable Groups](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml).

**Comment by cloudlene** [comment]
Thank you @RomainHautefeuille for the clarification.
The below works equally well:

steps:
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Cloudlene on Nuget'

**Comment by RomainHautefeuille** [comment]
Indeed, but IIRC you can only use NuGetCommand@2 with a windows agent.

**Comment by cloudlene** [comment]
Nope.  I'm using a hosted agent pool (Azure Pipelines) with ubutu-latest as my agent.  Not using Windows.

**Comment by RomainHautefeuille** [comment]
You are correct. Not sure why I was thinking that, probably confusing with another task. Sounds like a good workaround then.
Still, I hope this will be fixed soon in DotNetCoreCLI@2, it doesn't feel right to be using nuget.exe directly and not the dotnet cli.

**Comment by cloudlene** [comment]
@RomainHautefeuille:  Yeah, if it's a self hosted agent, we may have to include a Nuget package installer task too (In addition to DotNet CLI installer task).
