### ISSUE TITLE
Install Apple Certificate fails with recently issued certificates because the azure pipeline image does not include new intermediate certificate

### ISSUE THREAD

**Issue by sandorfr** [microsoft/azure-pipelines-tasks#15577]
# Bug

**Enter Task Name**: InstallAppleCertificate  

## Environment
- Azure Pipelines 
 
## Issue Description

[As described on this page](https://developer.apple.com/de/support/expiration/), Apple has updated its intermediate certificate. It needs to be either downloaded and installed prior to attempting to install the certificates, or the macos pipeline needs to be updated to include it. 

### Task logs

Either way until this is done, attempting to install a Distribution certificate generated after the 4th of December, will fail with: 
```
unable to load certificate
4535426560:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
```

**Comment by EzzhevNikita** [comment]
Hey @sandorfr, I've looked into your issue. The WWDR certificate in agents with macOS already is updated, and it is expired in 2030 (update). I've managed to reproduce your problem, and It is related to the incorrect used certificate format. "InstallAppleCertificateV2" task accepts only '.p12' certificates. Could you please ensure that you are using the certificate in PKCS12 standard (.p12)? If it is not in this format you can convert it using this guide - https://stackoverflow.com/questions/45753212/convert-der-certificate-to-p12

**Comment by sandorfr** [comment]
Hello @EzzhevNikita  my certificate is indeed a .p12. Let me check, it's possible that in the 4 days, the image is now up to date.

**Comment by sandorfr** [comment]
@EzzhevNikita unfortunately it still fails with the same problem:

```
/usr/local/bin/openssl pkcs12 -in /Users/runner/work/_temp/AppleDistribution-CyprienAutexier-Expires2022.p12 -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
##[debug]success of first tool:true
unable to load certificate
4377382400:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
```

**Comment by EzzhevNikita** [comment]
Hey @sandorfr, As far as I see your logs haven't information related to certificate description ("-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----") and if it is the same certificate that you are trying to install in the pipeline, then I assume that certificate file may be corrupted. I've checked logs for a valid distribution certificate and the log contains the certificate section before the private key section. This problem may be due to some transfer errors. Could you please ensure that the certificate is correct and try to regenerate your certificate?

**Comment by Silvercast** [comment]
we actually have the same error. It works on our existing old pipelines but not on newly created ones

**Comment by golubev-ivan** [comment]
Hi @sandorfr, do you still need some help with this issue?

**Comment by golubev-ivan** [comment]
I'm closing this ticket due to inactivity, feel free to ping me if you still need any help.

**Comment by vincentcastagna** [comment]
@sandorfr any chance you share what you've done to fix this (if you did fix it) ? I'm also having this on CI, but not locally when using openssl.

**Comment by jnteisseire-wesoftit** [comment]
Same here, the .p12 seems correct, the openssl command succeeds on my machine but fails on the agent.
