### ISSUE TITLE
How i get to the Release Deploy Comments field ?

### ISSUE THREAD

**Issue by MichaelReitsma** [microsoft/azure-pipelines-tasks#15575]
I want to use the comments field that you can specify upon deployment.
I know how to refer to the Release desciption field like e.g Release.ReleaseDescription.
And these are described here: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch
However the comments field for the deployment action is not listed here.
Does anybody know this ?

**Comment by MichaelReitsma** [comment]
Nobody ?

**Comment by anatolybolshakov** [comment]
Hi @MichaelReitsma this repo is mostly for pipeline tasks support - I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 for Azure DevOps related questions to get right eyes on it.

**Comment by anatolybolshakov** [comment]
Closing this as external at the moment - please let us know if you have any other questions.
