### ISSUE TITLE
MSBuild 17.0/ VS2022/.Net 6 not supported

### ISSUE THREAD

**Issue by sharmav** [microsoft/azure-pipelines-tasks#15576]
Getting below error in Azure Run Roslyn Analyzer build task for Azure Devops build pipeline and pipeline run is failing:

**Cannot validate argument on parameter 'MSBuildToolsVersion'. The argument "17.0" does not belong to the set "Current,16.0,15.0,14.0" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.**

This above error is coming when I installed VS2022 and migrated my API project to .Net6.0. Looks like Azure Devops pipelines currently does not supports version 17.0 of MSBuild.exe.

Can someone pls help resolving above error so that build pipeline run can succeed?

Below is the screenshot of the build pipeline with Run Roslyn Analyzer build task selected
![BuildPipeline_dotnet6](https://user-images.githubusercontent.com/2240589/144704985-11d67c6e-c5b1-4c37-a2a3-449dcadb279f.jpg)
:

**Comment by anatolybolshakov** [comment]
Hi @sharmav "Run Roslyn Analyzers" is a part of Microsoft Security Code Analysis Extension, although this repo is for in-the-box Azure DevOps tasks. I would suggest to reach out to the owners of this extension for further support - since there seems to be some issue with the task itself.

**Comment by anatolybolshakov** [comment]
@sharmav I'm closing this at the moment as external - please let us know if you have any other questions.
