### ISSUE TITLE
Please add pull command to Docker@2 task

### ISSUE THREAD

**Issue by DominikaSorn** [microsoft/azure-pipelines-tasks#15574]
## Required Information
*Type*: Feature

**Enter Task Name**: Docker@2

list here (V# not needed):  V2
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

## Issue Description
I don't think that it needs any wide description :)
We've got push, build, login, logout, start, stop...
Can you please add pull?

I want to be able to pull an image from one ACR and push it to another without Bash :)

**Comment by ryanhatfield** [comment]
It doesn't pass validation when using the local JSON schema for pipeline tasks, but the `pull` and `tag` commands do work for me.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/12716395/154387189-a3b5689d-7627-4332-8261-ce9c6b32e064.png">

**Comment by rodrigolopes** [comment]
See this #16071
