### ISSUE TITLE
NodeJs6 execution handler deprecation in CopyFiles@2 Task version 2.190.1

### ISSUE THREAD

**Issue by YoshicoppensE61** [microsoft/azure-pipelines-tasks#15571]
Like a lot of tasks that used to spawn the following warning 

_This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler_

the CopyFiles@2 task for me now gave the following error

_The pipeline is not valid. Job Datafactory_Build: Step 'CopyFiles' references task 'CopyFiles' at version '2.190.1' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator._

The temporary 'fix' for this is in the Azure Devops Organization Settings (https://dev.azure.com/<organization_name>/_settings/pipelinessettings) turning off the "Disable NodeJs 6 Tasks", breaking our pipelines that make use of the CopyFiles tasks. Of course this is not a nice fix, the actual fix needs to happen in the CopyFiles@2 Task, which needs to upgade to use the Node 10 handler instead of 6, hence the creation of this issue.

As a reference the agent that is running this pipeline is actually using NodeJs 10, so there is nothing an update on our agent side would fix.

**Comment by anatolybolshakov** [comment]
Hi @YoshicoppensE61 this issue should be already resolved since CopyFiles task was migrated to Node 10 execution handler - please let us know if you still see this issue.

**Comment by anatolybolshakov** [comment]
Hi @YoshicoppensE61 do you have any updates?
