### ISSUE TITLE
PipAuthenticate uses old url format for azure pypi feeds

### ISSUE THREAD

**Issue by smasihemami** [microsoft/azure-pipelines-tasks#15586]
**Bug, or Feature?**  
*Type*: PipAuthenticate still uses the old format for azure feeds

**Enter Task Name**: PipAuthenticate

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/PipAuthenticateV1

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

According to this https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration, we should move away from using the old URL format which contains visualstudio.com to the one containing dev.azure.com
But PipAuthenticate still uses the old url format which prevents us to migrate to the new format.

**Comment by smasihemami** [comment]
@v-jkarri Would you please enlighten me on what is happening here?

**Comment by v-jkarri** [comment]
@smasihemami The task PipAuthenticate is not related to our environment team so I removed environment label and unassigned to nadesu. Please check the code owners for this task https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS in the link.

**Comment by smasihemami** [comment]
@phil-hodgson @aasim @satbai May I kindly ask for some information about this issue from you guys?
