### ISSUE TITLE
ServiceFabricDeployV1 doesn't work with new ServiceFabric structure

### ISSUE THREAD

**Issue by schamal2205** [microsoft/azure-pipelines-tasks#15595]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ServiceFabricDeployV1 

## Environment
Azure Pipelines
- Agent - Hosted or Private: 
Hosted Agend

## Issue Description
As described in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-startupservices-model there is a new Service Fabric Structure with `StatupServices.xml`. With this change the `Deploy-FabricApplication.ps1` was also adapted. 
Within `Deploy-FabricApplication.ps1` there a plenty new changes like: 
```powershell
.PARAMETER StartupServicesFile
Path to the file containing the startup services for debugging.

...

Param
(
    [String]
    $PublishProfileFile,

    [String]
    $StartupServicesFile,

...

    $publishProfile.StartupServiceParameterFile = [System.IO.Path]::Combine($PublishProfileFolder, $publishProfileXml.PublishProfile.StartupServiceParameterFile.Path)

...

if ($IsUpgrade)
{
    if ($StartupServicesFile)
    {
        $PublishParameters['StartupServicesFileMode'] = $true
    }

    $Action = "RegisterAndUpgrade"
    if ($DeployOnly)

...

  # Pass the path to the Startup Services File if it was provided
    if ($StartupServicesFile)
    {
        $PublishParameters['StartupServicesFilePath'] = $StartupServicesFile

        if (-not [string]::IsNullOrEmpty($publishProfile.StartupServiceParameterFile))
        {
            $PublishParameters['StartupServiceParameterFilePath'] = $publishProfile.StartupServiceParameterFile
        }
    }

```

These changes are currently not available in [Publish-NewServiceFabricApplication.ps1](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-NewServiceFabricApplication.ps1) and [Publish-UpgradedServiceFabricApplication.ps1](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-UpgradedServiceFabricApplication.ps1). 

Due to that fact the Services are not created during the deploy via Azure Pipelines and have to be created manually in the Service Fabric Explorer. 

As long as these changes are not available in that Task, the new Service Fabric Structure is unusable for our application.

**Comment by nforysinski** [comment]
This is a big problem as we migrate to the latest Service Fabric project files. We have found that if we manually establish the services, and then use upgrade tasks with package diff from then on, subsequent deployments works fine, but the initial creation does not setup the services and they have to be manually created.

**Comment by nforysinski** [comment]
I don't know if it changed with more recent versions of the SDK, but upgrades via package deploys no longer work and simply leave the services completely uncreated (which is an even bigger problem in stateful scenarios). Any idea on a timeline for a fix here? This basically makes moving to the new startup parameters impossible, or I have to deploy without using our typical release pipelines.

**Comment by ChangeTheCode** [comment]
is there any update or plan to create a new version of the task to support the new structure format?

**Comment by thomashuysmans** [comment]
Is there an update on this issue?

**Comment by kuriakose-thomas** [comment]
Is there any update on this issue?

**Comment by ChangeTheCode** [comment]
I am pretty sure this issue is still existing.

**Comment by wiliammbr** [comment]
The issue exists and it would be interesting to provide a way to package the Services with a Default Services conversion included
