### ISSUE TITLE
JenkinsQueueJob: jenkins job job creation failed with status code 400 bad request with exception message job xxx not found

### ISSUE THREAD

**Issue by MichaelMWW** [microsoft/azure-pipelines-tasks#15593]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: JenkinsQueueJobV2

## Environment
Azure Devops Server 2020

- Agent - Hosted or Private: Private

## Issue Description

 Jenkins Queue Job job creation failed with status code 400 bad request with exception message job xxx not found

### Task logs
2021-11-23T02:10:17.7730786Z Job creation failed.
2021-11-23T02:10:17.7744382Z HttpResponse.statusCode=400
2021-11-23T02:10:17.7746986Z HttpResponse.statusMessage=Bad Request
2021-11-23T02:10:17.7749369Z java.lang.IllegalArgumentException: Job: **xxx** not found
2021-11-23T02:10:17.7751354Z              at **hudson.plugins.tfs.TeamBuildEndpoint.getJob(TeamBuildEndpoint.java:269)**
2021-11-23T02:10:17.7754205Z              at hudson.plugins.tfs.TeamBuildEndpoint.innerDispatch(TeamBuildEndpoint.java:292)
2021-11-23T02:10:17.7757025Z              at hudson.plugins.tfs.TeamBuildEndpoint.dispatch(TeamBuildEndpoint.java:167)
2021-11-23T02:10:17.7758481Z              at hudson.plugins.tfs.TeamBuildEndpoint.doBuild(TeamBuildEndpoint.java:335)

## Troubleshooting
We can see job **xxx** in Jenkins configure dashboard, but not sure why the log says Job not found.
Find the source of method hudson.plugins.tfs.TeamBuildEndpoint.getJob on the top of the exception call stack as below. Please help to check about this issue.
https://github.com/jenkinsci/tfs-plugin/blob/master/tfs/src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java

**Comment by MichaelMWW** [comment]
BTW, some user has reported similar issue in issue https://github.com/microsoft/azure-pipelines-tasks/issues/3135, please refer the last question in the link.

**Comment by MichaelMWW** [comment]
@anatolybolshakov Is there any update?

**Comment by anatolybolshakov** [comment]
Hi @MichaelMWW I can't reproduce the issue - does it happen sporadically or constantly for you? Do you have some stable repro steps for this?

**Comment by MichaelMWW** [comment]
@anatolybolshakov Prerequisites and background as below.
Jenkins version: 2.298
Jenkins pipeline type: Multi-branch pipeline which uses Azure Repo git source
Jenkins TFS Plugin: Team Foundation Server Plug-in 5.157.1

Azure DevOps on-premises Server version: 2020 Update 1
Azure Repo default branch -> Branch Policies -> Build Validation to validate code by pre-merging and build pull requests changes.
Build Validation pipeline uses JenkinsQueueJob to trigger Jenkins multi-branch pipeline when a PullRequest to the default branch created.

**The yaml pipeline is like that:**
![image](https://user-images.githubusercontent.com/23291569/147309553-3207b3a6-a873-48a5-a34f-06db506a54e6.png)

Configured Build validation for main branch:
![image](https://user-images.githubusercontent.com/23291569/147309643-f370f1ec-bee1-416b-a036-a44f990f35c5.png)

**Comment by anatolybolshakov** [comment]
Hi @MichaelMWW thanks! I managed to reproduce it for Multi-branch pipeline - investigating this issue currently, will update you shortly once there are any results.

**Comment by anatolybolshakov** [comment]
@MichaelMWW could you please try to open  <jenkins-server->/team-build/build/<job-name> - does it return any error?

**Comment by anatolybolshakov** [comment]
@MichaelMWW Jenkins task uses < jenkins-server >/team-build/build endpoint to submit new job. This endpoint comes with https://github.com/jenkinsci/tfs-plugin - as I see there is an issue while reaching out to this endpoint for multibranch job at the moment, so it seems to be some issue on tfs-plugin side.

**Comment by MichaelMWW** [comment]
@anatolybolshakov Thanks for your update, so what's your suggested next actions, create an issue for Jenkins tfs plugin, I saw there is no place to create new issue for https://github.com/jenkinsci/tfs-plugin.

**Comment by anatolybolshakov** [comment]
@MichaelMWW yes, I see it too - let us clarify if there is someone we could reach out about it.

**Comment by anatolybolshakov** [comment]
Hi @MichaelMWW since this plugin is owned by Jenkins - as we've checked the better way to report this issue is to open a ticket on https://issues.jenkins.io/secure/Dashboard.jspa

**Comment by MichaelMWW** [comment]
@anatolybolshakov It seems that the Jenkins TFS plugin has no update for a long time. Regarding to below Jenkins queue job task official link, it mentioned argument isMultibranchJob and it supports this argument, but it failed on the scenario in this github issue, can we update this document to mentioned that to avoid confusion for our users?

Doc link:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/jenkins-queue-job?view=azure-devops#arguments

![image](https://user-images.githubusercontent.com/23291569/149302131-21ffd982-e3a7-4ac6-b666-6488feacfb0e.png)

**Comment by anatolybolshakov** [comment]
@MichaelMWW sure, let us take a look at the documentation update here also.
