### ISSUE TITLE
No tests were discovered while attempting to rerun failed tests.Rerun failed tests using NUnit 

### ISSUE THREAD

**Issue by chloeboss** [microsoft/azure-pipelines-tasks#15592]
## Description
Nunit test cases always pass on my local but it would failed sometime on Azure. 
I am trying to run tests on Release pipeline but there is always one or two test cases failed but not every time the same test cases. So i try  "Re-run" failed test case. And would have error message like this "Error occurred while publishing test results : System.Exception: No tests were discovered while attempting to rerun failed tests. This is likely to happen if these tests are xunit or nunit datadriven/parameterized tests or tests with custom display names with spaces or special characters which are not supported with rerun. Please reach out to us at https://github.com/microsoft/azure-pipelines-tasks/issues if you are hitting this for tests other than the ones mentioned before.
"

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

NUnit 3.12
VS Professional 2019 Version 16.4.2
.NET Core 3.0

Task: VS Test@2
Test platform version: Latest
Test filter criteria: TestCategory=smoke

steps:
- task: VSTest@2
  displayName: 'Run Api Smoke Tests with test.runsettings'
  inputs:
    testAssemblyVer2: '**\LMS.BankAccountChecker.Api.AutomationTests.dll'
    testFiltercriteria: 'TestCategory=smoke'
    runSettingsFile: '$(System.DefaultWorkingDirectory)/TestLibraries/test.runsettings'
    rerunFailedTests: true
  continueOnError: true

### Error code

Test Run Failed.
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Empty parenthesis ( ). Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
Test Run Failed.

Error occurred while publishing test results : System.Exception: No tests were discovered while attempting to rerun failed tests. This is likely to happen if these tests are xunit or nunit datadriven/parameterized tests or tests with custom display names with spaces or special characters which are not supported with rerun. Please reach out to us at https://github.com/microsoft/azure-pipelines-tasks/issues if you are hitting this for tests other than the ones mentioned before.

Error: The process 'D:\Build Agents\Jarvis\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.195.0\Modules\DTAExecutionHost.exe' failed with exit code 1
Vstest failed with error. Check logs for failures. There might be failed tests.

**Comment by mike9900** [comment]
This appears to be a similar issue to https://github.com/microsoft/azure-pipelines-tasks/issues/16187.

Are you using test cases or tests that include ( and or ) characters?

**Comment by Mayweather312** [comment]
Hi Could you resolve this issue? Pls let me know if u had

**Comment by mikejohnstonPremierinc** [comment]
This is still occurring for me

**Comment by mikejohnstonPremierinc** [comment]
Why was this closed? Has there been a fix?
