### ISSUE TITLE
Build failure: Could not use "nc"

### ISSUE THREAD

**Issue by casaper** [microsoft/azure-pipelines-tasks#15596]
Unfortunately, I seem to require a how-to to [contribute](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md#prerequisites-node-and-npm).

Or at least as of now, I'm completely unable to even build or understand the most basic parts of this project.

Here are some questions I have, leading to the build failure mentioned in the issue title:

## Requirements

It says what's the minimum Node requirement ("at least node 4.2"), but the Maximum is not stated.

Seeing that truly pre-historic minimum Node requirement and my failure running build, I have to guess there is a maximum?

The current LTS (16) is too new?

At least this is what I get when I do `npm run build` 
```sh
$ node -v
v16.13.1
$ npm -v
8.2.0
$ npm run build
# ... snip allot of not yet failing build stuff ....
copying task.json
copying task.loc.json
copying Tests

> getting module externals
Downloading file: https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip
Could not use "nc", falling back to slower node.js method for sync requests.
/home/kaspi/Projects/github/azure-pipelines-tasks/node_modules/sync-request/index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (/home/kaspi/Projects/github/azure-pipelines-tasks/node_modules/sync-request/index.js:77:11)
    at doRequest (/home/kaspi/Projects/github/azure-pipelines-tasks/node_modules/sync-request/index.js:20:10)
    at downloadFile (/home/kaspi/Projects/github/azure-pipelines-tasks/make-util.js:411:22)
    at downloadArchive (/home/kaspi/Projects/github/azure-pipelines-tasks/make-util.js:451:27)
    at /home/kaspi/Projects/github/azure-pipelines-tasks/make-util.js:644:33
    at Array.forEach (<anonymous>)
    at getExternals (/home/kaspi/Projects/github/azure-pipelines-tasks/make-util.js:639:25)
    at /home/kaspi/Projects/github/azure-pipelines-tasks/make.js:235:25
    at Array.forEach (<anonymous>)
    at /home/kaspi/Projects/github/azure-pipelines-tasks/make.js:203:20
```

At first, I thought it might be because I have an Apple Silicon machine.

But unfortunately it isn't the case, because I instantly tried the same with a Linux host and x86_64 -> nope, it ain't m1 ARM for this instance ... the error is exactly the same.

### Suggestion about node and NPM requirements

One of the first things I personally usually do in a project is to add `engines` and `engineStrict` to the package.json.

On one hand enforce working versions and on the other hand document them in a standard way:

```json
{
  // .... snip package json
  "engines": {
    "node": ">=4.2 <17",
    "npm": ">=5"
  },
  "engineStrict": true
}
```

This way, NPM will complain on NPM install when my versions don't fit the requirements.

Probably Node 16 is too new for this. Probably only you can tell me what version is correct.

## Where are the actual TypeScript sources?

The original reason to head to this repo here, was to find out if the Cache@2 task has any outputs.

Because I Intend to do stuff in my pipeline, if "Cache@2" occurs to have a cache miss.

But heading to the [documentation](https://docs.microsoft.com/bs-latn-ba/azure/devops/pipelines/tasks/utility/cache?view=azure-devops&viewFallbackFrom=tfs-2013) there seems to be no outputs, or if there are none are documented.

No worries... so let's head to the open source sources and have a look: [Tasks/CacheV2](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheV2)

I find only JSON files.

And [contribute](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md) tells me to refer to [Add a custom pipelines task extension](https://docs.microsoft.com/en-gb/azure/devops/extend/develop/add-build-task?view=azure-devops) in the AZ-DevOps docs.

But unfortunately I seem to be unable to make a reference of the two?

## So how would I find out

- Where the actual TypeScript sources of the cache task are?
- If they really do not produce any pipeline output?

And then decide if it would be worth the effort to contribute,   
or perhaps create my custom modified cache task as a private custom task?

I don't want to be a complainer, even if it probably reads like this.  
But I honestly am happy to get that RTFM if it points to the actual FM.
And it is intended as constructive, and I'm sorry if it doesn't come across like that.

Thanks in advance.

**Comment by DenisRumyantsev** [comment]
Hi @casaper.
The source code of some tasks used in pipelines is not located in this repository (with all other tasks).
They are located in the [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent) repository and are provided with it.
The Cache task is one of them. This can be determined by the [task.json](https://github.com/microsoft/azure-pipelines-tasks/blob/30803ec9858a709aaaac3767b771a685afb9f0a4/Tasks/CacheV2/task.json#L53-L62).
Here is [the source code](https://github.com/microsoft/azure-pipelines-agent/tree/master/src/Agent.Plugins/PipelineCache) of the Cache task (written in C#, not TypeScript).

**Comment by DenisRumyantsev** [comment]
@casaper there is a known issue with the `sync-request` node module.
It can be fixed by adding the `maxBuffer` property in the `options` argument in the `spawnSync` method.
node_modules/sync-request/index.js — the `doRequestWith` function, line 75:
```js
// use
var res = spawnSync(command, args, { input: req + '\r\n', maxBuffer: 1024 * 1024 * 1024 });

// instead of
var res = spawnSync(command, args, { input: req + '\r\n' });
```

Also, you can build only one task instead of all using the `--task` flag:
```
node make.js build --task <task>
```

**Comment by DenisRumyantsev** [comment]
Hi @casaper, do you have any additional questions about this issue?

**Comment by DenisRumyantsev** [comment]
Hi @casaper, let me close this issue for now. Feel free to reopen it if you get further questions about this issue.
