### ISSUE TITLE
[UsePythonVersionV0] Notify task users about Python 3.5 retirement on January, 24

### ISSUE THREAD

**Issue by miketimofeev** [microsoft/azure-pipelines-tasks#15608]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: UsePythonVersion

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Hey, folks 👋
Our team owns hosted images generation in the https://github.com/actions/virtual-environments repository. According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md) policy tools and versions will typically be removed 6 months after they are deprecated or have reached end-of-life. Python 3.5 has reached and of life more than a year ago and we would like to remove it from the image, however, lots of users (~17k builds a month) still use Python 3.5 judging by the task telemetry.
Could you create a warning notification for those Python 3.5 users that the version will be removed on January, 24?

### Task logs

N\A

## Troubleshooting
N\A

### Error logs

N\A

**Comment by EzzhevNikita** [comment]
Due to the deployment freeze, there will be a delay with the rollout of the changes for this item. The rollout of these changes will start on 2022-01-03.

**Comment by miketimofeev** [comment]
@EzzhevNikita no problem, thanks for the update!
