### ISSUE TITLE
Nuget restore keeps getting older Grpc packages in Xamarin projects

### ISSUE THREAD

**Issue by Dolphinsimon** [microsoft/azure-pipelines-tasks#15603]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: NuGetCommand

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

- Agent - Hosted

## Issue Description

In our local development machine, the Grpc packages have restored with correct version:
`          "Google.Protobuf": "3.19.1",
          "Grpc.Net.Client": "2.41.0",
          "Grpc.Net.Client.Web": "2.41.0",
          "Grpc.Tools": "2.42.0",`

In Azure Pipeline, the restored versions are:
`         "Google.Protobuf": "3.13.0",
          "Grpc.Net.Client": "2.33.1",
          "Grpc.Net.Client.Web": "2.33.1",
          "Grpc.Tools": "2.33.1",`

App.proj file:
`               <PackageReference Include="Google.Protobuf" Version="3.19.1" />
		<PackageReference Include="Grpc.Net.Client" Version="2.41.0" />
		<PackageReference Include="Grpc.Net.Client.Web" Version="2.41.0" />
		<PackageReference Include="Grpc.Tools" Version="2.42.0">`

We have met the same problem in Xamarin.Android on Windows and Xamarin.iOS on macOS.
### Task logs
` OK https://api.nuget.org/v3-flatcontainer/grpc.net.client/index.json 911ms
 OK https://api.nuget.org/v3-flatcontainer/grpc.net.client/2.33.1/grpc.net.client.2.33.1.nupkg 3ms `

### Error logs

I have uploaded the generated deps file for the project, we have used many packages, but only the grpc series packages were restored with incorrect versions. 
[App.deps.json--LocalDevelopment.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7711638/App.deps.json--LocalDevelopment.txt)
[App.deps.json--AzureDevOps.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7711639/App.deps.json--AzureDevOps.txt)

**Comment by jmyersmsft** [comment]
That is very, very strange. I can't see any reason why it would reach out to the network, get the list of versions, and then select a lower version than allowed by the dependency specification in the proj file. 

Perhaps have your pipeline write out the App.proj file just before the restore to double-check that it is as you expect (e.g. a PowerShell task with the script `Get-Content p:\ath\to\App.Proj`)?
More complete logs from the restore may help clarify as well.

**Comment by Dolphinsimon** [comment]
> That is very, very strange. I can't see any reason why it would reach out to the network, get the list of versions, and then select a lower version than allowed by the dependency specification in the proj file.
> 
> Perhaps have your pipeline write out the App.proj file just before the restore to double-check that it is as you expect (e.g. a PowerShell task with the script `Get-Content p:\ath\to\App.Proj`)? 
More complete logs from the restore may help clarify as well.
[NuGetRestoreLogs.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7721725/NuGetRestoreLogs.txt)

I have upload the full logs in NuGet restore task. You can see the grpc packages were restored with 2.33.1

**Comment by Dolphinsimon** [comment]
And before we moved to Azure Pipeline, we have met the same strange problem in AppCenter build process.

**Comment by jmyersmsft** [comment]
This sounds like an issue with the NuGet client or the Xamarin environment, whereas I can only really help with the Azure Artifacts service or tasks.

The only thing I can suggest is to replace your usage of the NuGet task with this pair of tasks:
* NuGet Authenticate
* A script task that runs whatever command you would use to restore packages for your build locally. If that would normally happen transparently in your actual build, just let it do so there.

**Comment by Dolphinsimon** [comment]
We have tried install grpc series packages directly on android and ios target projects. The ios and android projects were restored with the right version. The shared netstanard2.1 project always restored with outdated version. Very strange.
