### ISSUE TITLE
QUESTION: How does Node6 extension deprecation affect users with only privately-hosted Node6 agents?

### ISSUE THREAD

**Issue by bryceitoc9** [microsoft/azure-pipelines-tasks#15606]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

## Environment
- Server - Both
- Agent - Private, Pipelines Agents < 2.144.0 (first Node10 version)

## Issue Description

Following up on https://github.com/microsoft/azure-pipelines-tasks/issues/15493#issuecomment-982059189 ; how will users with self-hosted Node6 Pipeline Agents be affected if they automatically update to an extension with Node6 runtimes deprecated? Our telemetry indicates that we have some users who are on the current version of our extension but are exclusively using legacy agents, and as far as we can tell, we wouldn't be able to prevent these users from updating since Azure DevOps and TFS versions are detached from Pipeline Agent versions.

Will there be any easy ways for users to downgrade if they run into this scenario? We'll see if we can proactively notify users, but we don't want to break users' pipelines if we can help it.

Thanks in advance!

**Comment by bryceitoc9** [comment]
Did some manual testing; turns out that bumping the `task.json` `minimumAgentVersion` triggers updates for versions in the same major version, even on self-hosted Azure DevOps Server installations (with self-hosted Azure Pipelines Agents). Made a PR here to document this: https://github.com/microsoft/azure-pipelines-tasks/pull/15614

**Comment by alexander-smolyakov** [comment]
@bryceitoc9, thanks for the documentation update. Regarding the questions:

> How will users with self-hosted Node6 Pipeline Agents be affected if they automatically update to an extension with Node6 runtimes deprecated?

We are planning to completely deprecate the Node 6 execution handler. So the customers will not be able to run Node 6 pipelines tasks once the handler will be deprecated.

> Will there be any easy ways for users to downgrade if they run into this scenario?

If the customers use self-hosted agents then they will be able to use older versions of the agent if they use some tasks that use the Node 6 execution handler. At the moment we are working on migrating to Node 10 execution handler for all in-the-box tasks to make sure that all pipelines tasks from Default Collection will use Node 10 execution handler.
