### ISSUE TITLE
DownloadPackage@1 - Request to specify package-name case sensitivity

### ISSUE THREAD

**Issue by nigeleke** [microsoft/azure-pipelines-tasks#15611]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DownloadPackage@1 

## Environment
- Server - Azure Pipelines
- Agent - Hosted
    
## Issue Description

We have two artifact feeds - one for hot off the press development, one for formally released artifacts. A number of artifacts have been published to each feed whereby we've ended up with different cases being used for the artifact name, e.g. in the development feed it is "AnArtifact" and in the formal feed it is "anArtifact".

We have a pipeline which is required to run, sourcing packages to be downloaded from _either_ the development feed or the formal feed. The pipeline lists the packages, and performs DownloadPackage@1 in a loop for each. If the list contains "AnArtifact" then DownloadPackage@1 fails when the pipeline is invoked for the formal feed. If the list is amended to include "anArtifact" then the formal invocation succeeds, but the development one fails.

Azure DevOps does not allow renaming or complete deletion of the package, so we cannot recreate from scratch.

Within the Visual Studio development environment this case sensitivity is not an issue; the code references "AnArtifict" for the formal feed successfully.

This request is for DownloadPackage to either ignore case or provide an attribute like "caseSensitivePackageName: true/false".

**Comment by jmyersmsft** [comment]
Unfortunately, for technical reasons that's unlikely to happen. 

How are you using the downloaded package in your pipeline? We may be able to come up with a workaround.

**Comment by nigeleke** [comment]
It's just being downloaded in order to further package up in to a bespoke program...
I've "worked around" by having two case-sensitive lists in the pipeline - one for each artifact feed. I use one list or the other depending the triggering branch...
