### ISSUE TITLE
AzureFileCopy@4 requires access to the storage account key, despite documentation stating otherwise.

### ISSUE THREAD

**Issue by FurcyPin** [microsoft/azure-pipelines-tasks#15610]
## Required Information

*Type*: Bug

**Enter Task Name**: AzureFileCopy@4

## Environment
- Azure Pipelines

- Agent - Hosted : 
    - Agent name: 'Azure Pipelines 3'
  - Current agent version: '2.195.2'
  - ##[group]Operating System
  - Microsoft Windows Server 2016

## Issue Description

In the [official documentation of the Azure File Copy Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops) it is said that
> The task supports authentication based on Azure Active Directory. Authentication using a service principal and managed identity are available. For managed identities, only system-wide managed identity is supported.

[In the readme of the task AzureFileCopyV4](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4#prerequisite-for-the-task), it is said that 
> As this version of task uses AzCopy 10, service principal needs to have one of these `Storage Blob Data Contributor` or `Storage Blob Data Owner` roles assigned to access resources.

I have set up a service principal and given it the `Storage Blob Data Contributor` role on a storage account.
When I run the pipeline, I get the following error :

```
2021-12-15T15:14:09.3656926Z ##[error]ExceptionMessage: The client '<REDACTED_OBJECT_ID>' with object id '<REDACTED_OBJECT_ID>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/<REDACTED_SUBSCRIPTION_ID>/resourceGroups/<REDACTED_RESOURCE_GROUP_NAME>/providers/Microsoft.Storage/storageAccounts/<redacted_storage_account_name>' or the scope is invalid. If access was recently granted, please refresh your credentials. (in function: Get-AzRMStorageKeys)
```

If we look at the task's code, we clearly see that the function [`Get-AzRMStorageKeys`](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFileCopyV4/AzureUtilityRest.ps1#L3) is called by the function [`Get-AzureStorageKeyFromARM`](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFileCopyV4/AzureUtilityRest.ps1#L3), which is called in the middle of the file [`AzureFileCopy.ps1`](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFileCopyV4/AzureFileCopy.ps1#L103-L104
), without any particular logic to prevent calling it.

https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFileCopyV4/AzureFileCopy.ps1#L103-L104

**This means that, contrary to what the documentation seems to indicate, this pipeline task always requires the storage account key to connect to the storage account, instead of using only the `Storage Blob Data Contributor` which should be enough for az-copy.**

## Expected behavior

Authentication to a storage account using a storage account key is deprecated and should be replaced with Azure AD authentication, using the `Storage Blob Data Contributor` role. AzureFileCopy should support this more secure authentication method to upload files to a blob container. Or at least the documentation should not claim it does.

## Extra information

This subject has already been brought up by another user on the [developer community forum](https://developercommunity.visualstudio.com/t/azuredevops-service-connection-permissions-for-usi/1225871), without any real solution provided aside from "use Azure CLI task instead".

**Comment by v-saikumart** [comment]
@FurcyPin  Could you please assign "Storage Blob Data Owner"  role and confirm on same.

Thank you.

**Comment by FurcyPin** [comment]
@v-saikumart 

I just tried it, and I confirm that I get the same error, which is normal, as the role "Storage Blob Data Owner" does not inherit the right 'Microsoft.Storage/storageAccounts/listKeys/action' either.

**Comment by v-saikumart** [comment]
Hi @FurcyPin 

I believe that you have followed below steps.

i. Go to Service connections screen.
ii. Click Manage Service Principal which will redirect you to the Application Registration of the Service Principal. Copy the name.
iii. Go back and click Manage service connection roles which will redirect you to the IAM blade of the Azure Subscription. Here you need to assign a role to the service principal(Storage Blob Data Owner). Use name copied in previous step to search service principal.

Thank you.

**Comment by FurcyPin** [comment]
Hi @v-saikumart

Yes, I followed these steps. I also checked afterwards that the role was correctly set.
But as I said, the role Storage Blob Data Owner does not grant the right 'Microsoft.Storage/storageAccounts/listKeys/action',
which AzureFileCopy@4 tries to use.

**Comment by v-saikumart** [comment]
@FurcyPin  Could you please share full logs by keeping system.debug = true in pipeline.

Thank you.

**Comment by FurcyPin** [comment]
@v-saikumart There you go: https://gist.github.com/FurcyPin/bc2f93faa1e6791b85ee3e0888111a75

**Comment by v-saikumart** [comment]
@FurcyPin Thank you for the full logs.
As per the below mentioned logs, could you please verify Client secrets validity for SPN and confirm on same, as we have verified the task from our side and it is working as expected.

![image](https://user-images.githubusercontent.com/89189030/147352939-3a5f4a46-90f5-4687-84e3-b4075d85d07f.png)

**Comment by FurcyPin** [comment]
Hi @v-saikumart could you please be more specific ?

Let me summarize again:

- If I give the role `Storage Blob Data Contributor` and `Storage Blob Data Owner` to the service principal it fails with an error saying that it does not have authorization to perform action `Microsoft.Storage/storageAccounts/listKeys/action`.
- If I give the role `Contributor` or `Owner` to the service principal it does work.

What do you mean _exactly_ by "working as expected" ?

Are you implying either one of these two statements ?

A. The role `Storage Blob Data Owner` should be giving the authorization `Microsoft.Storage/storageAccounts/listKeys/action` to the service principal.
B. AzureBlobCopy@4's expected behaviour is to always require the authorization `Microsoft.Storage/storageAccounts/listKeys/action`.

**Comment by v-saikumart** [comment]
Hi @FurcyPin 
A. Service principal needs to have  **"Storage Blob Data Owner"** role assigned to access resources, in this case we are able to run the task successfully.
B. Could you please verify **Client secrets validity for SPN** and below mentioned API alone.

https://management.azure.com//subscriptions//<REDACTED_SUBSCRIPTION_ID>/resourceGroups/<REDACTED_RESOURCE_GROUP_NAME>/providers/Microsoft.Storage/storageAccounts/<redacted_storage_account_name>/listKeys?api-version=2015-06-15

Thank you.

**Comment by FurcyPin** [comment]
Hi @v-saikumart 

A. As I mentioned in the initial post, [the documentation](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4#prerequisite-for-the-task) says that the service principal needs to have one of `Storage Blob Data Contributor` or `Storage Blob Data Owner`. Is the documentation wrong, then ? 

Nevertheless I tried once again, and I confirm that this works :

![azure_works](https://user-images.githubusercontent.com/6087587/147505153-bf3b421c-cef3-454b-b934-90950d2f5b89.png)

While this does not (same error as before) :

![azure_not_works](https://user-images.githubusercontent.com/6087587/147505142-68343acc-fd0b-4635-a36e-51c703cb9940.png)

(I hid the service principal name for security reasons, but please trust me on this, it is the same one for all three roles, and it is the one that I am using in the pipeline)

I will try again tomorrow in case the right propagation took time to complete.

B. I'd love to verify "**Client secrets validity for SPN** and below mentioned API alone.", but I have no idea of how to do this. Please provide a detailed how-to procedure.

C. I still fail to see why you think that giving the ["Storage Blob Data Owner"] will solve things, [it does not give the `Microsoft.Storage/storageAccounts/listKeys/action`](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-owner) authorization. It would help me greatly if you could explain with more details why you think this is supposed to work.

D. Alternatively, if you are trying to reproduce the issue on your side and it indeed works well with the role **"Storage Blob Data Owner"**, could you please try to [prevent authorization with shared access key on your storage account](https://docs.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal) and confirm it still work on your side ?

Thanks.

**Comment by v-saikumart** [comment]
Hi @FurcyPin 

We need to provide "Contributor" or "Owner" and "Storage Blob Data Owner" then it does work. We will update the 
 [**readme of the task AzureFileCopyV4**](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV4#prerequisite-for-the-task).

Thank you.

**Comment by FurcyPin** [comment]
Hi @v-saikumart 

Thanks for your answer. In that case I believe that the "Contributor" or "Owner" role alone should suffice, as the Shared Access Key grants _full rights on the whole storage account_.

This is the reason why I would like to be able to disable it. Should I create another issue as Feature Request to ask for the compatibility of AzureFileCopy with storage accounts with disabled shared access key ?

Regards

**Comment by v-saikumart** [comment]
Hi @FurcyPin  
Along with "Contributor" or "Owner" role, we need to have "Storage Blob Data Owner" role as well.

Thank you.

**Comment by FurcyPin** [comment]
Hi @v-saikumart, thanks for your answer.

I might get this wrong, but from what I can see in the code, it looks like AzureFileCopy@4 behaves differently depending on whether it is writing on the blob or on the a VM.

While the block that copies on a VM seems to use `AzureFileCopyRemoteJob`, which does call azcopy, it looks like the block that performs the copy to blobs does not use it at all, but use the Write-Host command instead.

https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFileCopyV4/AzureFileCopy.ps1#L192-L207

Moreover, it looks like the Shared Access Key is mostly used to create the container if it does not exists.

https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/AzureFileCopyV4/AzureFileCopy.ps1#L126-L134

Again, this behavior is problematic, as it should be settable with an option "createContainerIfNotExists".
For instance, if I create a configuration container and make a typo when deploying to this container, I want the task to fail, not silently create another container (this exact scenario actually happened to me once and caused a production issue that would have been avoided had that option be set to False).

**Comment by ehanlon** [comment]
Any updates regarding timeline for the fix?

**Comment by PwshPally** [comment]
@ehanlon, Using AzureFileCopy@3 until AzureFileCopy@4 is fixed seems to be a workaround.

**Comment by kimjamia** [comment]
We've disabled key authentication and receive `##[error]Key based authentication is not permitted on this storage account.` when trying to use an account with Storage Blob Data Contributor access rights.

**Comment by seanix99** [comment]
Is there somenone working on the issue ?
If the StorageAccount is configured with allowSharedKeyAccess set to **false**, the task fails and still try to use the Storage Key to check if the container exists and try to create it.

So any updates regarding a timeline for a fix will be appreciate.

**Comment by craig-mclellen-e20** [comment]
This is also an issue for me. I'm wanting just to have RBAC permissions assigned to the service connections' service principal, while having the "Allow storage account key access" configuration setting in the storage account **disabled**. I don't want to have access keys floating around.

Any updates on this?

**Comment by itsvijayid** [comment]
I had come across this one as well and have raised with Microsoft as mentioned and worked on a work around utilising azure storage upload-batch as In [https://learn.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload-batch](url) 

Command : az storage blob upload-batch -d '$(ContainerName)' -s $sourceDirectory --account-name $storageAccountName --auth-mode login in 

AzureCLI@2 task Script type as 'ps'

Hope this helps

**Comment by fgarcia-cnb** [comment]
a bug for us too. we disable keys on storage accounts whenever possible. the task should be using Azure AD auth only, but it obviously does not since it errors out with "Key based authentication is not permitted on this storage account"

**Comment by sofia-valles** [comment]
We are also experiencing the same bug. Shared key access is disallowed by policy so if we set it to false we get the error "Key based authentication is not permitted on this storage account"

**Comment by sofia-valles** [comment]
@nadesu and @v-saikumart any updates on this please?

**Comment by syedhamjath** [comment]
Same issue here, key disabled so no SAS meaning task has to use MS Entra but it doesn't so I get the error message "Key based authentication is not permitted on this storage account."

I'm using below syntax,

      - task: AzureFileCopy@5
        name: CopyTask
        displayName: 'Copy deployment artifacts to the storage account'
        inputs:
          sourcePath: '$(Pipeline.Workspace)/upload'
          azureSubscription: '${{ parameters.rg_name }}'
          destination: AzureBlob
          storage: ${{ parameters.storage_account_name }}
          containerName: ${{ parameters.container_name }}
          cleanTargetBeforeCopy: true

**Comment by Devvox93** [comment]
It has come to my attention that AzureFileCopy@6 is released.
We're successfully using that one now with Managed Identity and disabled Access Keys.

Perhaps this issue can be closed (as v6 would probably solve the problem reported here).
Ref: https://github.com/microsoft/azure-pipelines-tasks/releases/tag/v237
