### ISSUE TITLE
AzureFunctionApp@1 task does not support azureSubscription as parameter or environment

### ISSUE THREAD

**Issue by seilorjr** [microsoft/azure-pipelines-tasks#15618]
# Required Information
The task need to support the azureSubscription as parameter or environment

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFunctionApp@1

## Environment
- Server - Azure Pipelines or TFS on-premises?
Using Azure Pipelines

- Agent - Hosted or Private: 
it does not work in both types of agents

## Issue Description
When I am using the azureSubscription  as parameter or environment as example
`  - task: AzureFunctionApp@1

    displayName: Deploy Azure Function $(appName)

    inputs:

      azureSubscription: ${{ parameters.azureSubscription}}

      appType: 'functionApp'

      appName: ${{ parameters.appName}}

      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

      slotName: ${{ parameters.slotName}}

      deploymentMethod: 'auto'`

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs
There was a resource authorization issue: "The pipeline is not valid. Job deploy_tu: Step input azureSubscription references service connection $(azureSubscription ) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."
[Insert error from the logs here for a quick overview]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/94986685/146555640-630d9704-9545-4f0c-861e-c105a83e2047.png">

**Comment by v-jkarri** [comment]
Hi Seilorjir,
Can you please provide service connection name for the "azureSubscription" parameter. Please find the sample YML code for the same. 
![Sample-YML](https://user-images.githubusercontent.com/87686529/146886430-e5d80384-9680-487b-b98e-66a66fd3e9c1.png)
We are closing this ticket. Please feel free to open if you are still facing the issue.

**Comment by v-jkarri** [comment]
@seilorjr can you please provide yml file along with the template to check this scenario?
