### ISSUE TITLE
Subscription error when running the az-login -t --allow-no-subscriptions

### ISSUE THREAD

**Issue by Arwin2001** [microsoft/azure-pipelines-tasks#15623]
## Required Information
I had my script running for a while, but later today when I run the command az-login with the --allow-no-subscriptions parameter. Now I'm get the error that there are no subscriptions. 

This is part of a script.

My PowerShell Code: 

+ $resourceManifest = "$PSScriptRoot\AppPermissionManifest.json"
    + $azureADAppdisplayName = "Veeam Backup Office 365 app"
      + Write-Host ""
        + az account clear
            + az login -t $CustomerTenantID --allow-no-subscriptions | Out-Null

            + $Json = az ad app create --display-name $azureADAppdisplayName --required-resource-accesses $resourceManifest 

        + $CreatedApp = $Json | ConvertFrom-Json 

### Error logs

az : WARNING: The default web browser has been opened at https://login.microsoftonline.com/TenantID/oauth2/v2.0/authorize. Please continue 
the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
At line:5 char:13
             az login -t $CustomerTenantID --allow-no-subscriptions |  ...
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : NotSpecified: (WARNING: The de...e-device-code`.:String) [], RemoteException
    FullyQualifiedErrorId : NativeCommandError
 
ERROR: No subscriptions found for ...@randomdomain.onmicrosoft.com.
az : ERROR: Failed to parse JSON: \AppPermissionManifest.json
At line:7 char:21
 ...     $Json = az ad app create --display-name $azureADAppdisplayName -- ...
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (ERROR: Failed t...onManifest.json:String) [], RemoteException
    FullyQualifiedErrorId : NativeCommandError
 
Error detail: Expecting value: line 1 column 1 (char 0)
The JSON may have been parsed by the shell. See https://docs.microsoft.com/cli/azure/use-cli-effectively#quoting-issues

**Comment by v-ibshaik** [comment]
Hello Arwin,

Could you please provide the Task details.

Thanks,
Ibrahim.
