### ISSUE TITLE
[AzureStaticWebAppV0] Ensure newest version of Docker image is used

### ISSUE THREAD

**Issue by anthonychu** [microsoft/azure-pipelines-tasks#15629]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureStaticWebAppV0  

## Issue Description

Add `--pull` here to ensure it's always checking for the newest version of the image and pulling if needed: https://github.com/microsoft/azure-pipelines-tasks/blob/862952f8fd95f49c8fefd457390fa2bfe2c9017f/Tasks/AzureStaticWebAppV0/launch-docker.sh

This is mainly affecting customers with self-hosted agents, where there might be an earlier version of the image from a previous pipeline run and it won't update when newer versions are available.

@miwebst @brhopcra

**Comment by tomaustin700** [comment]
@anthonychu Have submitted a PR with the change, I'm unsure how to test however so a little guidance with how to test locally would be appreciated. Thanks.
