### ISSUE TITLE
Use recent java LTS version in Gradle@2

### ISSUE THREAD

**Issue by nibexo** [microsoft/azure-pipelines-tasks#15647]
Feature
Type: Upgrade Gradle task to latest java version 17 LTS

Enter Task Name: Gradle@2 (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GradleV2)

Environment
Server - Azure Pipelines
Issue Description
The more updated jdkVersionOption used by task Gradle@2 is 11
(#jdkVersionOption: 'default' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6)

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops.

I'd like to use more recent LTS version 17 which was released 14 September 2021

**Comment by anatolybolshakov** [comment]
Hi @nibexo sorry for delay - we are currently working on more prioritized tickets, but will get back to this once be able to.
As a workaround - you can set up path to the JDK using jdkUserInputPath task input (you can find variables which keep paths to JDKs installed on hosted images in docs - for example, [here's the list ](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#java)of JDKs for windows 2022 image).

**Comment by nibexo** [comment]
@anatolybolshakov Thank you for your answer, however if adding latest version JDK LTS to task maven@3 is almost done, so adding it also to Gradle task shouldn't be big problem, or I'm wrong?

@alexander-smolyakov
