### ISSUE TITLE
Feature request: DockerV2 buildAndPush command should support arguments

### ISSUE THREAD

**Issue by cpdohert** [microsoft/azure-pipelines-tasks#15652]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DockerV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

Per the [Docker task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#build-and-push) documentation:

>Be aware that if you use value buildAndPush for the command parameter, then the arguments property will be ignored.

This is an...unusual lack of functionality.  `docker push` supports no meaningful options in this context; there's no reason not to allow the `arguments` property and simply pass it to the `build` phase of the `buildAndPush` command the same way as for the `build` command.  Since (apparently) the only way to build an image once and then push it to both Docker Hub and a private ACR is to use `buildAndPush`, not supporting build arguments in `buildAndPush` means any container that requires build arguments - such as any Rails app where you want to precompile your assets - has to be built using duplicated build steps or similar hack jobbery.

**Comment by ryanhatfield** [comment]
Is it overly difficult to use the `build` and `push` commands separately?
Can you give an example of how you'd like to pass arguments to the `buildAndPush` command? 
I'm curious to hear more about your Rails app and why dealing with precompiled assets is a hinderance.

From a previous [issue here](https://github.com/microsoft/azure-pipelines-tasks/issues/11981#issuecomment-568365337)
> "BuildAndPush" command does both build and push. it is difficult to decide arguments belongs to which command

If you open up the docker command on the CLI, the two commands `docker build` and `docker push` have two separate call signatures.
```
❯ docker build --help

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

Options:
      --add-host list           Add a custom host-to-IP mapping (host:ip)
      --build-arg list          Set build-time variables
      --cache-from strings      Images to consider as cache sources
      --disable-content-trust   Skip image verification (default true)
  -f, --file string             Name of the Dockerfile (Default is 'PATH/Dockerfile')
      --iidfile string          Write the image ID to the file
      --isolation string        Container isolation technology
      --label list              Set metadata for an image
      --network string          Set the networking mode for the RUN instructions during build (default "default")
      --no-cache                Do not use cache when building the image
  -o, --output stringArray      Output destination (format: type=local,dest=path)
      --platform string         Set platform if server is multi-platform capable
      --progress string         Set type of progress output (auto, plain, tty). Use plain to show container output (default "auto")
      --pull                    Always attempt to pull a newer version of the image
  -q, --quiet                   Suppress the build output and print image ID on success
      --secret stringArray      Secret file to expose to the build (only if BuildKit enabled): id=mysecret,src=/local/secret
      --ssh stringArray         SSH agent socket or keys to expose to the build (only if BuildKit enabled) (format: default|<id>[=<socket>|<key>[,<key>]])
  -t, --tag list                Name and optionally a tag in the 'name:tag' format
      --target string           Set the target build stage to build.
```

```
❯ docker push --help

Usage:  docker push [OPTIONS] NAME[:TAG]

Push an image or a repository to a registry

Options:
  -a, --all-tags                Push all tagged images in the repository
      --disable-content-trust   Skip image signing (default true)
  -q, --quiet                   Suppress verbose output
```

So at the very least, the DockerV2 task would need to invent parameter names for the `PATH | URL | -` or `NAME[:TAG]` inputs, and decide on a method of assembling the two commands, where for every scenario I've seen, using `build` and `push` commands separately tends to be more clear when creating pipeline tasks. Yes you will likely repeat some arguments, but that could be helped with a custom [pipeline template](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates).

If you'd like to suggest a usage of the `buildAndPush` command that allows arguments, while still passing the respective args to both commands, we could see how practical it is to implement.

**Comment by Socolin** [comment]
I'm looking for this too, could you re-open this ?

I want to add arguments  `arguments: --no-cache --pull` and for now, the  only solution is to double the size of my yml already hard to read with all the steps...  

I would really appreciate if it was possible with like `buildArguments` and `pushArguments`.
