### ISSUE TITLE
Issue #12815 persists 

### ISSUE THREAD

**Issue by franky920920** [microsoft/azure-pipelines-tasks#15651]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: CopyFilesOverSSH@0  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  franky920920, franky920920/nutcvr.root, 20211231.2

- Agent - Hosted or Private:  Hosted
    
    - If using Hosted agent, provide agent queue name: fv-az320-114

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Issue #12815 still persists. 

### Task logs
<img width="659" alt="Screen Shot 2021-12-31 at 10 32 07 PM" src="https://user-images.githubusercontent.com/11349917/147828415-b5e80b14-4ae1-453d-948e-619113d7d93d.png">

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anatolybolshakov** [comment]
Hi @franky920920 could you please share your pipeline/agent logs?

**Comment by franky920920** [comment]
@anatolybolshakov  I cannot repro this anymore. Closing this. Thanks!

**Comment by franky920920** [comment]
This happens again :D 
<img width="432" alt="Screen Shot 2022-03-24 at 1 13 37 PM" src="https://user-images.githubusercontent.com/11349917/159846906-44bcb012-6b7a-4e08-a391-117edeb698b9.png">

**Comment by franky920920** [comment]
Pipeline logs: [logs_399.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8338611/logs_399.zip)
cc: @anatolybolshakov

**Comment by anatolybolshakov** [comment]
Hi @franky920920 thanks! Could you please set up 'Agent.Diagnostic' pipeline variable to 'true', run pipeline in debug mode (you can either set it up via 'Enable system diagnostics' checkbox or set up 'System.Debug' pipeline variable as 'true' before run) and share the logs archive?
+ @tatyana-kostromskaya - this looks like another issue with agent sporadically being stuck we are working on at the moment.

**Comment by franky920920** [comment]
@anatolybolshakov Here you go!
[logs_402.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8346570/logs_402.zip)

note: It says there is an ETIMEDOUT error on sshClient. 😕

**Comment by anatolybolshakov** [comment]
@franky920920 hmm.. Seems like there is spontaneous  timeout error when sshclient is trying to close connection - probably due to some network connection issues.
Does it happen constantly or sporadically for you?

**Comment by franky920920** [comment]
@anatolybolshakov Constantly, and I am sure the ssh connection is stable and reachable to me.

**Comment by franky920920** [comment]
Hi @KonstantinTyukalov Only with MS-Hosted agent. Should I try this on a self-hosted agent?

**Comment by KonstantinTyukalov** [comment]
@franky920920 yes, could you please try it? It might be related with some network issues due virtualization. Just as a workaround
