### ISSUE TITLE
Build pipeline using older version of node always ? unable to change to new version

### ISSUE THREAD

**Issue by sathishreddy48** [microsoft/azure-pipelines-tasks#15660]
Use Node Task output 

Starting: Use Node 
==============================================================================
Task         : Node.js tool installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
Version      : 0.192.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js
==============================================================================
Found tool in cache: node 16.13.1 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/node/16.13.1/x64/bin
Finishing: Use Node 

# Npm run build task output

`Starting: npm build
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.187.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
/opt/hostedtoolcache/node/6.17.1/x64/bin/npm --version
3.10.10
/opt/hostedtoolcache/node/6.17.1/x64/bin/npm config list
npm info it worked if it ends with ok
npm verb cli [ '/opt/hostedtoolcache/node/6.17.1/x64/bin/node',
npm verb cli   '/opt/hostedtoolcache/node/6.17.1/x64/bin/npm',
npm verb cli   'config',
npm verb cli   'list' ]
npm info using npm@3.10.10
npm info using node@v6.17.1
npm verb exit [ 0, true ]
npm info ok 
; cli configs
user-agent = "npm/3.10.10 node/v6.17.1 linux x64"

; environment configs
loglevel = "verbose"
userconfig = "/home/vsts/work/1/npm/11107362.npmrc"

; userconfig /home/vsts/work/1/npm/11107362.npmrc
registry = "#####removed###"

; node bin location = /opt/hostedtoolcache/node/6.17.1/x64/bin/node
; cwd = /home/vsts/work/1/s
; HOME = /home/vsts
; "npm config ls -l" to show all defaults.

/opt/hostedtoolcache/node/6.17.1/x64/bin/npm run build
npm info it worked if it ends with ok

npm verb cli [ '/opt/hostedtoolcache/node/6.17.1/x64/bin/node',
`

**Comment by anatolybolshakov** [comment]
@phil-hodgson @aasim @satbai could you please take a look? Seems to be some possible issue with Npm task.

**Comment by jasric89** [comment]
I find this works for me with node to install a specific version

`  - task: NodeTool@0
      displayName: 'Install Node .js'
      inputs:
        versionSpec: '14.17.3' 
        force32bit: false # Optional
        checkLatest: false # Optional`
        
        I also dont use the npm task I find I have more control over npm when I do the task as a command like this: 
        
        `- script: |
        npm install -g @angular/cli@12.1.3
        npm install
        ng build --prod
      displayName: 'npm install and build' `
