### ISSUE TITLE
[PublishSymbols] Fails when running from release pipeline

### ISSUE THREAD

**Issue by dannyvv** [microsoft/azure-pipelines-tasks#15662]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishSymbols

## Environment
- Server - Azure Pipelines
- Agent - Any
    
## Issue Description

When using the [PublishSymbolsV2](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishSymbolsV2) task from a release pipeline (rather than a build pipeline) the tasks successfuly publishes the symbols, yet the task fails because it tries to associate the artifact to the current build.
In this release pipelines this fails with:
```
Unable to process command '##vso[artifact.associate artifacttype=SymbolRequest;artifactname=contoso/testing ci/20220104025/11482647/3380700c-b101-432b-be58-41a0ce5b664c]#https://contso.artifacts.visualstudio.com/_apis/Symbol/requests?requestName=contoso%2ftesting+ci%2f20220104025%2f11482647%2f3380700c-b101-432b-be58-41a0ce5b664c' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Associating server artifact is not supported in Release.
```
> (Anonymized names with contoso, I can provide internal links via private means if needed
![image](https://user-images.githubusercontent.com/11037542/148421531-42f6b7a2-731d-463e-ac06-9a6c7eab5684.png)

A sample instance can be found in this release: [release 906260 @ office/oc](https://office.visualstudio.com/OC/_releaseProgress?_a=release-environment-logs&releaseId=906260&environmentId=2460994#)

The root cause seems to be the call to [Write-VstsAssociateArtifact](https://github.com/microsoft/azure-pipelines-tasks/blob/928c03f5b4280c692ba0a3f984275180d8cdef7d/Tasks/PublishSymbolsV2/PublishSymbols.ps1#L229). I tried searching for it online, github, my local drive and on mseng but could not find it, only the [docs](https://github.com/microsoft/azure-pipelines-task-lib/blob/21dac986b4c7478eb2ed8ffbd60e4fad62904438/powershell/Docs/FullHelp/Write-VstsAssociateArtifact.md#L5)..

I believe skipping this call when the task is run under a release pipeline will address the issue.
I'd be happy to contribute a PR for this.

**Comment by dannyvv** [comment]
@carl-tanner: Let me know if you are okay with me contributing this...

**Comment by carl-tanner** [comment]
Let me check on what this does exactly.  I think this call may be responsible for setting the lifetime of the symbol (i.e. symbol is deleted when pipeline is deleted) so it may be important.

**Comment by dannyvv** [comment]
From the logs, the default is 10 years... I guess the linking takes care of the fact that it gets deleted when the build gets deleted...
