### ISSUE TITLE
Can not make pipelines work with management group

### ISSUE THREAD

**Issue by jasric89** [microsoft/azure-pipelines-tasks#15670]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    - 
https://dev.azure.com/NetSupportSoftware/NetSupport_DevOps

- Agent - Hosted or Private: N/A
    

## Issue Description

Can not make pipelines work with management group, this is on the back of issue: 14744. I was told to apply my service connection to multiple subscriptions. Yet when doing that, it doesn't work as you physically can not tie a service connection to multiple subscriptions. I have tried and it fails at seeing resources. 

### Task logs

Says can not find resource group

## Troubleshooting
Followed advice from ticket 14744, doesn't work. Tried also re-scoping to management group with new app registration doesn't work. 

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by jasric89** [comment]
Please can I get an update on this. Everytime you scope a Service connection to a management group and give it the relevant rights for example, contributor access. The pipeline fails to deploy into any subscription within that Management group. I have a ticket open with MS, where the only current trying but not tested solution is to some how pass in service connections into a yaml pipeline. Yet we are struggling to get this work. 

When really all that needs to happen is you need to fix the bug where you can not scope properly to a management group. With Azure Dev Pipelines and a service connection.

**Comment by anatolybolshakov** [comment]
Hi @jasric89 this repo is mostly for pipeline tasks related issues - for Azure DevOps related questions you can open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.

**Comment by cstrempfer** [comment]
Hi @anatolybolshakov, I do not agree with that. There are (very) few Pipeline Tasks that work with Service Connections on Management Groups. Therefore support for Management Groups has to be implemented into the Pipeline Tasks specifically.

**Comment by cstrempfer** [comment]
This is still a problem!

**Comment by jasric89** [comment]
Can you give me an update on when this will be fixed please?

**Comment by cstrempfer** [comment]
This is still a problem.

**Comment by jasric89** [comment]
Hi this is still a problem when will a fix be available?

**Comment by jasric89** [comment]
there is no point to keep closing this bug, it still doesn't work the fact I have to keep coming back here asking for an update is just disgraceful.
