### ISSUE TITLE
[BatchScriptV1, JenkinsQueueJobV2, VSBuildV1] Fix critical security issues 

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-tasks#15684]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
- BatchScriptV1
- JenkinsQueueJobV2
- VSBuildV1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

[Compliance build](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=16644541&view=results) started to report new critical security alerts since 12/08.

To reproduce this issue: run `npm audit`

BatchScriptV1, JenkinsQueueJobV2, VSBuildV1 tasks has bunches of critical issues. 

Audit logs attached.

### Task logs

[Audit logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7839350/Audit.logs.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by anatolybolshakov** [comment]
@tatyana-kostromskaya could you please check for DownloadBuildArtifactsV1 as well?

**Comment by tatyana-kostromskaya** [comment]
Created PR: https://github.com/microsoft/azure-pipelines-tasks/pull/15695
