### ISSUE TITLE
SqlAzureDacpacDeploymentV1 has dead link to SQL Server 2016 Feature Pack

### ISSUE THREAD

**Issue by kimjamia** [microsoft/azure-pipelines-tasks#15692]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1

## Issue Description

The [README](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SqlAzureDacpacDeploymentV1#automation-agent) suggests downloading Microsoft SQL Server 2016 Feature Pack for getting `Invoke-SqlCommand` on an agent server. However, the link is dead.
> For deploying SQL Server Scripts, Invoke-Sqlcmd cmdlet is used, and can be installed by the following -
> Download and install the following components of Microsoft SQL Server 2016 Feature Pack .

**Comment by PhilipsonJoseph** [comment]
@kimjamia  We have merged your PR. Hence closing this ticket
