### ISSUE TITLE
[codecoverage-tools common package] Fix critical security issues

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-tasks#15779]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: "codecoverage-tools" common package (./common-npm-packages/codecoverage-tool)

## Issue Description

"codecoverage-tools" common package has dependencies on npm packages which have critical security vulnerabilities or dependencies on other packages with security vulnerabilities.
We need to update version of packages in package.json or package-lock.json to fix it.

To see all existing errors please **use latest node version** and run `npm audit` in task folder.

### Task logs

[codecoverage-tools.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7879839/codecoverage-tools.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tatyana-kostromskaya** [comment]
Affected tasks: ANTV1, GradleV2, GradleV3, MavenV2, MavenV3, PublishCodeCoverageResult

**Comment by anatolybolshakov** [comment]
Closed since packages have been published.
