### ISSUE TITLE
[JavaToolInstallerV0] Fix critical security issue

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [microsoft/azure-pipelines-tasks#15777]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JavaToolInstallerV0

## Issue Description

JavaToolInstaller has dependencies on npm packages which have critical security vulnerabilities or dependencies on other packages with security vulnerabilities.
We need to update version of packages in package.json or package-lock.json to fix it.

To see all existing errors please **use latest node version** and run `npm audit` in task folder.

### Task logs

[JavaToolInstallerV0.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7879780/JavaToolInstallerV0.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tatyana-kostromskaya** [comment]
Depends on #15780

**Comment by anatolybolshakov** [comment]
Closing this one since changes has been already rolled out.
