### ISSUE TITLE
Unable to build a .NET 4.5 (Database Project) using VSBuild@1 on windows-2022 agent

### ISSUE THREAD

**Issue by woodman231** [microsoft/azure-pipelines-tasks#15799]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: VSBuild@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: windows-2022

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

We recently upgraded our code base from .NET 5 to .NET 6. We had troubles with the builds until we used windows-2022 (we were using windows-latest before, and noticed that it was using VS 2019), and specified version 17.0 for the VSBuild task. However, we have a database project in our solution which does produce a dacpac file that is used in a later release pipeline. That database project targets .NET 4.5. It seems that because .NET 4.5 SDK is not on the windows-2022 agent the build of that project fails and gives the following error:

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1217,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
I updated the VSBuild task to only compile the projects that were upgrade to .NET 6, and the build task works fine now. Hoping to find a way to use the windows-2022 agent to compile this database project without having to create an additional build and release pipelines for the SQL Database project. But that might be all I am left with being able to do.

I was looking into that UseDotNet@2 task, but it seems to only be able to install .net core sdks, and not .net framework sdks, though I could be wrong?

### Error logs

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1217,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

**Comment by woodman231** [comment]
Ok. I think I see that because 4.5 is technically end of life is probably why it is not on windows-2022. I was able to target the database project for 4.8, and that actually worked. Not sure for how long that will work. But it fixed it for now. This might help some one else out in the future though. Hopefully there are plans to allow these database projects to target higher .net frameworks in the future.

**Comment by hidegh** [comment]
Updating DB project to higher .NET framework is simple, just open the database *.sqlproj file and alter:
```xml
<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
```
