### ISSUE TITLE
Deploy to an Azure Cloud Service (Extended support)

### ISSUE THREAD

**Issue by SharePointRadi** [microsoft/azure-pipelines-tasks#15793]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureCloudPowerShellDeploymentV1

## Environment
Azure Pipelines, Microsoft-hosted agent.

## Issue Description
What is the current recommended way to deploy a VS Cloud Service project to the new ARM-based Cloud Service (extended support)?
Is there relevant documentation?
Azure Cloud Service (Classic) is not relevant to us as we have migrated.

**Comment by Munnwich** [comment]
Also interested in this.  I have tried a number of different ways to deploy to a Cloud Services (Extended Support) resource (post migration) and I cannot seem to figure it out. Please reach out if more details are necessary.

**Comment by SharePointRadi** [comment]
Hey guys, do you have an update on this question? It has been unanswered for a month and I would imagine you know the answer. Azure Cloud Service )extended support) has been GA since April 5th, 2021. (https://azure.microsoft.com/en-us/blog/cloud-services-extended-support-is-generally-available-migration-tool-in-preview/)

**Comment by b4icurmt** [comment]
We are also in this situation. We migrated to Cloud Service (Extended Support). But, there is no way to deploy the code.

**Comment by mattmunich** [comment]
Ultimately I wound up using powershell to deploy the extended support cloud services and I found this stackoverflow post extremely helpful:

SO: https://stackoverflow.com/a/71564689/4244666
Docs: https://docs.microsoft.com/en-us/azure/cloud-services-extended-support/deploy-powershell

**Comment by jckeme-rs** [comment]
bump

**Comment by rhythmnewt** [comment]
Still nothing? We have a dozen services that we can't migrate to extended support because of lack of supported deployment path.
