### ISSUE TITLE
AzureRmWebAppDeployment@v4 - Resource should exist before deployment

### ISSUE THREAD

**Issue by maikelvanhaaren** [microsoft/azure-pipelines-tasks#15806]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment@v4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: WIN-G3T17DG4R9D

## Issue Description

Since a couple of weeks we’re facing problems with deploying webapps to newly created resource groups. As part of our QA process we deploy a ARM template to a new resource group and then deploy web applications to the resources in the group (with the task AzureRmWebAppDeployment@4).

We regularly see those error messages: ##[error]Error: Resource '(...)' doesn't exist. Resource should exist before deployment.

The deployment of the resource group succeed. Next run of the pipeline succeed, most likely because of the resource group exists for some time at the moment of the deployment.

We tried to add a sleep time of 30 minutes after the ARM deployment and set retryCountOnTaskFailure to 10 to every web app deployment. It doesn’t make any change, we still see sometimes the error messages.

**Comment by v-saikumart** [comment]
Hi @maikelvanhaaren Could you please share logs by keeping system.debug = true in pipeline.

Thank you.

**Comment by maikelvanhaaren** [comment]
Our pipeline for the deployment of a feature to Azure looks like this:

![image](https://user-images.githubusercontent.com/18571666/150511704-d6fd38f6-c6f3-43cb-b2e4-a31759bc4871.png)

Context:
1. The building stage is responsible for building the apps and publish artifacts.
2. The stage deployment is responsible for the deployment of the code to a feature resource group in Azure:
1.1. `Infrastructure` runs for deployment of the ARM template to Azure. 
2.1. Then there is a sleep time of 20 minutes for giving background processes of Azure time (powershell: `Start-Sleep -s 1200`). Parallel running is the database migrations for seed data into the database. 
3.1. The jobs `Backend > Management`, `Backend > API`, `Frontend` and `Azure Function` runs parallel and are responsible for deploying the apps to Azure app service or Function. The deployments have `retryCountOnTaskFailure` set to 10.

I've attached the debug logs of the job `Infrastructure` and the `Backend > API` job. FYI: I've replaced all keys and other personal information with SECRET.

[1_Infrastructure.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7912620/1_Infrastructure.txt)
[1_Backend  API.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7912619/1_Backend.API.txt)

**Comment by maikelvanhaaren** [comment]
Any updates regarding this issue we encounter?

**Comment by v-saikumart** [comment]
Hi @maikelvanhaaren  
We are already tracking same issue on https://github.com/microsoft/azure-pipelines-tasks/issues/15532, so we are closing this.

Thank you.

**Comment by 0xUnicorn** [comment]
> Our pipeline for the deployment of a feature to Azure looks like this:
> 
> ![image](https://user-images.githubusercontent.com/18571666/150511704-d6fd38f6-c6f3-43cb-b2e4-a31759bc4871.png)
> 
> Context:
> 
> 1. The building stage is responsible for building the apps and publish artifacts.
> 2. The stage deployment is responsible for the deployment of the code to a feature resource group in Azure:
>    1.1. `Infrastructure` runs for deployment of the ARM template to Azure.
>    2.1. Then there is a sleep time of 20 minutes for giving background processes of Azure time (powershell: `Start-Sleep -s 1200`). Parallel running is the database migrations for seed data into the database.
>    3.1. The jobs `Backend > Management`, `Backend > API`, `Frontend` and `Azure Function` runs parallel and are responsible for deploying the apps to Azure app service or Function. The deployments have `retryCountOnTaskFailure` set to 10.
> 
> I've attached the debug logs of the job `Infrastructure` and the `Backend > API` job. FYI: I've replaced all keys and other personal information with SECRET.
> 
> [1_Infrastructure.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7912620/1_Infrastructure.txt) [1_Backend API.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7912619/1_Backend.API.txt)

@maikelvanhaaren - I'm curious, where do you find this view you have posted? I've never seen it before in DevOps GUI.
