### ISSUE TITLE
PowerShell Task option "Show warnings as Azure DevOps warnings" not working when raising warnings from a class

### ISSUE THREAD

**Issue by jayserdny** [microsoft/azure-pipelines-tasks#15801]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PowerShellV2

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

**Agent Name:** Azure Pipelines
**Agent Version:** 2.196.2
**Agent OS:** Microsoft Windows Server 2016

## Issue Description
When activating the following option 'Show warnings as Azure DevOps warnings' in PowerShell Task, it does not bubble up the raised warnings to the Pipeline when raising it from inside a class.

![image](https://user-images.githubusercontent.com/19354816/150215972-756c8af9-0db3-439a-a67e-c316ea271af6.png)

The following code does not raise the warning when the option is enabled:

```powershell
class TestClass {
     [void] Run() {
          Write-Warning "This is a test warning";
     }
}

[TestClass] $testClass = [TestClass]::new();
$testClass.Run();
```

The following output is returned:
![image](https://user-images.githubusercontent.com/19354816/150214277-a2e8006c-0b2b-4dfd-a92d-b0546cf318a9.png)

However, when the following code runs:
```powershell
function Run() {
     Write-Warning "This is a test warning";
}

Run
```
The warning is raised as expected:
![image](https://user-images.githubusercontent.com/19354816/150215658-e32e5ed1-5d16-4cec-af52-b700554ce119.png)

A workaround that I found is to use PowerShell Command **Write-Host** with Azure DevOps specific syntax to raise warnings:

```powershell
class Testing {
    [void] Run() {
        Write-Host "##vso[task.LogIssue type=warning;]This is a test warning"
    }
}
```
![image](https://user-images.githubusercontent.com/19354816/150215066-97c0ac2e-c25d-4559-9483-613888f03728.png)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
N/A

**Comment by petterssonmv** [comment]
I have the same problem. An install script raises a warning from within a powershell function using 
`        Write-Warning $msg`

This is not picked up by my devops classic build pipeline when Show Warnings as Azure Devops Warnings is Checked.
