### ISSUE TITLE
Code coverage doesn't work with Gradle Kotlin DSL

### ISSUE THREAD

**Issue by thorntonrp** [microsoft/azure-pipelines-tasks#15814]
Type: Bug
Task Name: Gradle

When using the Gradle task for Gradle projects that use the Kotlin DSL (build.gradle.kts), the code coverage feature doesn't work because it's looking for build.gradle instead of build.gradle.kts.

```
##[debug]Code Coverage data will be appeneded to build file: /agent/_work/2/s/JavaGradle/java-test-app/build.gradle
##[warning]Unable to append code coverage data: Error: File or folder doesn't exist: /agent/_work/2/s/JavaGradle/java-test-app/build.gradle
##[debug]Processed: ##vso[task.issue type=warning;]Unable to append code coverage data: Error: File or folder doesn't exist: /agent/_work/2/s/JavaGradle/java-test-app/build.gradle
##[warning]Failed to enable code coverage: Unable to append code coverage data: Error: File or folder doesn't exist: /agent/_work/2/s/JavaGradle/java-test-app/build.gradle
##[debug]Processed: ##vso[task.issue type=warning;]Failed to enable code coverage: Unable to append code coverage data: Error: File or folder doesn't exist: /agent/_work/2/s/JavaGradle/java-test-app/build.gradle
```

**Comment by anatolybolshakov** [comment]
Hi @thorntonrp there is no support for Kotlin DSL at the moment for the Gradle task - let us leave this as possible enhancement for this task. We are currently working on more prioritized tickets, but will get back to this request as soon as we will be able to.

**Comment by tonylook** [comment]
this issue is still present.

**Comment by JG9A** [comment]
@anatolybolshakov  there are tasks that let you define the build gradle script path. 

IMO this must get prioritization since the default DSL for gradle now is kotlin....

**Comment by JG9A** [comment]
@anatolybolshakov in addition:

> there is no support for Kotlin DSL at the moment for the Gradle task 

This is not correct -all is working with both ktolin and groovy but the coverage failed for kotlin so there is support for kotlin dsl just not for the coverage....
