### ISSUE TITLE
Failure to retrieve file from connected github repository when running AzureResourceManagerTemplateDeployment@3 - 404 Not Found

### ISSUE THREAD

**Issue by alexkhorton** [microsoft/azure-pipelines-tasks#15827]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

## Issue Description

I am trying to set up an azure pipeline for the first time. My source is hosted in a private github repository. When running AzureResourceManagerTemplateDeployment@3 I am seeing the following output:

ARM Service Connection deployment scope - Subscription
Checking if the following resource group exists: AzureCITest.
Resource group exists: true.
Creating deployment parameters.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Failed to download the file. URL: 'https://raw.githubusercontent.com/alexkhorton/ARM_CI_test/main/CreateWebApp/azuredeploy.json'. Error: 404: Not Found
Finishing: AzureResourceManagerTemplateDeployment

I have a service connection set up to my private github repository. I think the following facts indicate that the connection must exist and be set up correctly:

I was able to use a yml file from my github repository to setup my pipeline.
Github+ADO integration works - changes pushed to my repository trigger a new run of my build pipeline in AzureDevOps.
I am able to run the "checkout: self" step just fine in my yaml pipeline. I am able to observe my ARM template in the checked out files.
So, it seems like the connection is working just fine.

The issue then seems to be that the way that the file is being retrieved in the task AzureResourceManagerTemplateDeployment@3 is triggering a 404.

On a related note, when I obtain a link to the raw ARM template file contained in a private repository (as requested in step 7. Select the Raw button, the URL begins with https://raw.githubusercontent.com), the link is of the form https://raw.githubusercontent.com/<username>/<reponame>/main/<filepath>/?token=<accesstoken>

If I open this URL in my browser with the accesstoken present, the file opens fine. If I remove the accesstoken, I get a 404.

This lead me to the conclusion that some sort of authentication is not happening for whatever request is being triggered by AzureResourceManagerTemplateDeployment@3

### Task logs

[logs_34.zip](https://github.com/microsoft/azure-pipelines-tasks/files/7937582/logs_34.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Failed to download the file. URL: 'https://raw.githubusercontent.com/alexkhorton/ARM_CI_test/main/CreateWebApp/azuredeploy.json'. Error: 404: Not Found

**Comment by alexkhorton** [comment]
I forgot to note the environment information:

Environment
Server - Azure Pipelines or TFS on-premises?

If using Azure Pipelines, provide the account name, team project name, build definition name/build number:

Azure Pipelines.
Account name - alexkhorton
Project: ARM_Deployment_Test
Build Number: 20220125.29 
Buid Id: 33

Agent - Hosted or Private:

If using Hosted agent, provide agent queue name:

Hosted Agent
Agent Pool: Azure Pipelines

**Comment by alexkhorton** [comment]
My difficulties with this task started when I was going through the steps of a tutorial. I made an issue informing the tutorial owners as well: https://github.com/MicrosoftDocs/azure-docs/issues/86958

**Comment by mumian** [comment]
Adding @t-dedah, @bishal-pdMSFT, @NAGA-BANDI and @v-abajaj.

**Comment by alex-frankel** [comment]
@alexkhorton - has this every worked for you in the past or is this the first time you have tried this tutorial?

**Comment by grantomation** [comment]
Same error for me. First time that I have ever done the tutorial. Cheers

**Comment by sdvipeen** [comment]
Same issue for me. Trying to create my First Azure DevOps pipeline using "az pipelines create --name "First-Java.CI"". Doesn't accept my GitHub credentials and service connection. 
Error:
Unable to get the file content from the GitHub repository 'name/pipelines-java' for the source version/branch 'main' and file path 'azure-pipelines.yml'. Bad credentials

**Comment by KrazeyKami** [comment]
Is anyone gonna fix this issue? Still not resolved...
