### ISSUE TITLE
Old Node.js version fails post deployment script

### ISSUE THREAD

**Issue by ScarWar** [microsoft/azure-pipelines-tasks#15839]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines https://dev.azure.com/PhilosopherStone/Elmunasseq/_build/results?buildId=941

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Self Host Linux VM with Agent version 2.196.2

## Issue Description

node -v v0.10.40
npm -v 1.4.28

The node version of the task is `v0.10.40` npm version of the task is `1.4.28`. Our post-deployment task includes the installation of a node package is failing because the current version is too old.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "C:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "@nestjs/cli@7.5.1"
npm ERR! cwd C:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     C:\home\site\wwwroot\npm-debug.log
npm ERR! not ok code 0

2022-01-25T09:40:50.7114849Z ##[error]Error: Unable to run the script on Kudu Service. Error: Error: Executed script returned '1' as return code. Error: npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (C:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-named.js:260:10)
npm ERR!     at C:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-named.js:120:12
npm ERR!     at saved (C:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\npm-registry-client\lib\get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "C:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "@nestjs/cli@7.5.1"
npm ERR! cwd C:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     C:\home\site\wwwroot\npm-debug.log
npm ERR! not ok code 0
```

**Comment by sdevlin4698** [comment]
Having a similar issue, were you ever able to resolve this?

**Comment by ScarWar** [comment]
@sdevlin4698 Yes, after contacting a Microsoft technician, we used the post-deploy script to install the dependencies. Secondly, we found out that we had a bad configuration in our AppService, we needed to change `WEBSITE_NODE_DEFAULT_VERSION` to one of the valid runtime options. This can be found using this StackOverflow [post](https://stackoverflow.com/questions/45515421/which-versions-of-node-js-are-available-on-azure-web-sites)
