### ISSUE TITLE
gradle error 

### ISSUE THREAD

**Issue by MoeAbouAli** [microsoft/azure-pipelines-tasks#15858]
**Question, Bug, or Feature?**  
*Type*: The process '/Users/runner/work/1/s/gradlew' failed with exit code 1

**Enter Task Name**: error when running the pipeline in azure devops for android studio

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipeline
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by EzzhevNikita** [comment]
@MoeAbouAli Could you please share more details regarding this issue? Please attach logs for the Gradle task with enabled diagnostics.

**Comment by EzzhevNikita** [comment]
@MoeAbouAli Is it still an issue for you?
