### ISSUE TITLE
Cache@2 does not handle junction / symbolic link gracefully (caches and restores as folders/files) 

### ISSUE THREAD

**Issue by richshadman** [microsoft/azure-pipelines-tasks#15864]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/Cache

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

N/A / Private / Proprietary 

- Agent - Hosted or Private: 

Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

OS: Windows_NT / 10.0.17763
Agent: 2.195.0

## Issue Description

The Cache@2 task does not handle junctions/symlinks gracefully. Instead of recognizing them as junctions, it crawls the entire folder and caches everything as static folders/files.

We have a complex npm structure with workspaces, and those workspaces are referenced as packages by the root and by each other. npm handles this by creating symbolic links / junctions in order to handle the relative references to the other local packages.

Due to the size of our node_modules folders, simply caching the npm cache doesn't really save us any time. Because we are using private agents, we actually have instead set up a common npm cache for all the agents on a box which does help to shave a small fraction of the time for the install, but not much. The packages download reasonably quickly however reconstructing the node_modules folder takes a while even with all the modules cached globally. It therefore makes more sense for us to use the Cache task to cache the node_modules folder (using package lock as the key) and only run npm ci when there is a cache miss. 

Because of the fact that the Cache task does not handle symlinks/junctions well, it ends up caching old source code in the node_modules folders instead of restoring the symlink to the actual source location.

For now, we are working around this by deleting the specific workspace package folders in the node_modules and running a targeted npm install for the workspace packages.

Ideally, it would be nice to see one of two options to resolve this in the task:

1. The task should be able to recreate symlinks instead of blindly copying everything to the cache
2. If this isn't a valid option, the task should be able to support path exclusions so we could simply omit the symlink folders (we would still need to run the targeted npm install to restore the symlinks but at least bad data isn't getting cached).

### Task logs

N/A

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting

N/A

Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

N/A

[Insert error from the logs here for a quick overview]

**Comment by haveaguess** [comment]
I agree caching of NPM could be better (faster / smarter at restoring node_modules instead of rebuilding it every time), and we all seem to be trying to build it because we want faster development cycles. I'm going to do what @richshadman has suggested "run the targeted npm install to restore the symlinks"

**Comment by richshadman** [comment]
@johnterickson  or anyone really has there been a behavior change? it seems on 9/16 that this behavior changed with the cache task. It is now restoring symlinks which has ironically broken our current pipelines as it is caching our source code in workspaces and restoring it OVER the source code pulled from git.

**Comment by richshadman** [comment]
For now I'm going to change our pipeline logic to clear out the symlinks before the job finishes so it won't cache them at all. This avoids any behavior changes in the future, whether it is due to a change in cache task, or npm behavior with how it manages symlinks.

**Comment by johnterickson** [comment]
@richshadman we shell out to the environment's `tar` : https://github.com/microsoft/azure-pipelines-agent/blob/23233ae52ce8100bf293ff126ac37dc15d134664/src/Agent.Plugins/PipelineCache/TarUtils.cs#L168 so maybe that changed for you?

**Comment by richshadman** [comment]
The only thing that has changed on these servers are routing patching (windows updates) and Visual Studio updates. We did update VS in the past month. Is it possible this downstream dependency was updated with Visual Studio? We don't install a tar utility directly.
