### ISSUE TITLE
App service name is empty on Azure - Pipelines - Releases

### ISSUE THREAD

**Issue by kostukp96** [microsoft/azure-pipelines-tasks#15867]
After created new function app, i cant added this function to App Service name in release pipeline. Function app becomes available after midnight. If i choose other app task in release pipeline i can see my new function...
Can you help me with this issue ?

**Comment by adalfa** [comment]
@kostukp96  can you see if https://github.com/microsoft/azure-pipelines-tasks/issues/15532  apply to your case?
