### ISSUE TITLE
AndroidSigningV3 doesn't work correctly with conditions

### ISSUE THREAD

**Issue by jgoyvaerts** [microsoft/azure-pipelines-tasks#15879]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  Bug

**Enter Task Name**: AndroidSigning

## Environment
- Server - Azure Pipelines or TFS on-premises?

    
    - Azure Pipelines / macadam-development / MACDEV / build id: 19151 

- Agent - Hosted or Private: 

- Private / Windows Server / Agent version 2.188.3

## Issue Description

When using a condition on the AndroidSigning task, the condition is evaluated at the start of the job, to determine if the secret file should be downloaded in a pre-job. However, if the condition is only true later in the job (because of a variable being set by another task), the secret file isn't downloaded at the start of the script, resulting in an error when running the actual AndroidSigning task.

```
Failed to load signer "signer #1"
java.io.FileNotFoundException: 
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:352)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
##[error]Error: The process 'C:\AndroidSDK\build-tools\29.0.2\apksigner.bat' failed with exit code 2
```

When looking at the command executed, we can see the -ks argument is empty (rest of the command removed for clarity):
```
C:\Windows\system32\cmd.exe /D /S /C "C:\AndroidSDK\build-tools\29.0.2\apksigner.bat sign --ks "" 
```

When removing the condition from the AndroidSigning task, the pre-job successfully runs, downloads the secret file, and the AndroidSigning task doesn't throw an error.

**Comment by denis-tikhomirov** [comment]
@jgoyvaerts, Thanks for the issue-reporting in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.

**Comment by denis-tikhomirov** [comment]
@jgoyvaerts, could you please provide more info about "conditions" specified by you? Do you mean specifying of non-default mask for apkFiles field?
Also would be great if you can provide us pipeline yaml used by you to have repro of this issue and logs of build failed because of the issue (with enabled "Enable system diagnostics").

**Comment by jgoyvaerts** [comment]
@denis-tikhomirov 
The condition for AndroidSigning is fairly simple, it's just :
```condition: and(eq(variables['buildProd'], 'false'), succeeded())```

The variable buildProd is set in a different step, before the AndroidSigning task:
```
- task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        if [[ $(Build.SourceBranch) =~ "releases" ]]
        then
          buildProd=true
        else
          buildProd=false
        fi
        echo "##vso[task.setvariable variable=buildProd]$buildProd"

```

Because the condition is evaluated in the pre-job, buildProd is null, causing the pre-job of the AndroidSigning to fail and not download the secure file.

**Comment by denis-tikhomirov** [comment]
@jgoyvaerts, thank you for providing this info.
Azure Pipelines have feature to declare variables used in build/job outside of steps in build/job - [Set variables in pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline). And function [eq](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#eq) can compare branch name to expected value.
As example, provided example above can be declared by the feature by following way:

```
jobs:
- job: testJob
  variables:
  - name: buildProd
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/releases')]
  steps:
  - AndroidSigningV3
    ...
    condition: and(eq(variables['buildProd'], 'False'), succeeded())
```

**Comment by jgoyvaerts** [comment]
@denis-tikhomirov 
Thanks for providing this workaround, however this issue is still a bug, not an enhancement. While I can make the task work by moving the variable declaration upfront and changing the value eq() checks against, this doesn't always work in more complex flows (I simplified my example to explain the bug).

**Comment by denis-tikhomirov** [comment]
Downloading of secret file regardless of condition is not good idea, IMO, by 2 reasons:
- secret file must be downloaded only in cases when it's really required in accordance to security reason
- it produces unnecessary activity - downloading of file in all runs of task, regardless required this or now

I have created new one task for creation of docs about pre-jobs - https://github.com/microsoft/build-task-team/issues/2280. It will be published as soon as it's prepared.
