### ISSUE TITLE
add warning publishWebProjects required on publish

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/azure-pipelines-tasks#15874]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: feature

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines or TFS on-premises?  _Azure Pipelines_
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: can be provided if needed but I don't think it is

- Agent - Hosted or Private: _Hosted_
   
## Issue Description

Can a _WARN_ log message but outputted when `command: publish` is specified and `publishWebProjects` is not?  It took me a while to figure out why it was building all my projects & **not just the one** I specified and I'm not alone: [54 upvotes on this StackOverflow answer](https://stackoverflow.com/a/53395041/185123).

![image](https://user-images.githubusercontent.com/14079228/152362021-75b559b0-e07e-44af-b412-52709a5dae80.png)

Sidenote: and defaulting to `true`... feels wrong but that ship has already sailed 😢

### Task logs

not attached

### Error logs

n/a

**Comment by JimGorman17** [comment]
I strongly support this change. The exclusivity of the 'publishWebProjects' setting is poorly named and not well-documented.

**Comment by jkrntx** [comment]
This needs to be adjusted. Wasted far too much time today before I found the SO answer linked above.

**Comment by spottedmahn** [comment]
Hi @bishal-pdMSFT - any thoughts? 💭
