### ISSUE TITLE
PublishTestResults@2: SourceCode for TestResultsPublisher.exe

### ISSUE THREAD

**Issue by delixfe** [microsoft/azure-pipelines-tasks#15876]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: PublishTestResults

## Issue Description

Could you also open source TestResultsPublisher.exe and its dependencies?
That would enable us to better understand the parsing and mapping to the DevOps test results and eventually to improve it.

**Comment by delixfe** [comment]
@shailesh-sk The [Labeler workflow](https://github.com/microsoft/azure-pipelines-tasks/runs/5059958887?check_suite_focus=true) failed.
But it decided to assign the issue to you :)

```
Got issue 15876
Adding labels ["question","Area: TestManagement"]
Adding assignees ["shailesh-sk"]
Error: HttpError: Validation Failed
```

**Comment by zippy1981** [comment]
Can we please reopen this @shailesh-sk ? Even if the answer is no, can we get some consideration on the issue?

**Comment by drolevar** [comment]
@delixfe @shailesh-sk Could you please consider this?
