### ISSUE TITLE
Question:  When does a new version of a Task go live in Azure Pipelines?

### ISSUE THREAD

**Issue by nnellans** [microsoft/azure-pipelines-tasks#15886]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Question*:  I see that a new version of this Task, version 3.199.0 was committed 4 days ago.  However, when I use this Task in my Azure Pipeline, it still uses the old version 3.198.0.  When will Azure Pipelines start using the new version of this Task?

**Enter Task Name**:  AzureResourceManagerTemplateDeploymentV3

## Environment
- Azure Pipelines

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name:  Ubuntu-latest

**Comment by jsblock78** [comment]
According to [this page](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md), tasks get updated every 3 weeks for Azure DevOps, and quarterly for TFS.

**Comment by jsblock78** [comment]
Also: https://whatsprintis.it/

Currently it is week 3 of sprint 200.

**Comment by nnellans** [comment]
It has been well over 3 weeks now since the new version of the task was committed.  Is there something else that needs to happen for this new version of the task to go live?
