### ISSUE TITLE
Azure IoT Edge - Build module images - Error: iotedgedev installation failed, see detailed error in debug mode

### ISSUE THREAD

**Issue by DiogoCorreiaC** [microsoft/azure-pipelines-tasks#15905]
*Type*: Bug

**Enter Task Name**: Azure IoT Edge V2

## Environment
- Server - Azure Pipelines
- Agent - Hosted
   vs2017-win2016

## Issue Description

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    templateFilePath: '$(System.DefaultWorkingDirectory)/_ConnectedFactory_Edge/Modules/deployment.template.json'
    defaultPlatform: 'windows-amd64'

![image](https://user-images.githubusercontent.com/99394041/153379043-77d1773e-8da5-42b7-a174-65d9a066d147.png)

**Comment by LarsKemmann** [comment]
Is this connected with #16072?

**Comment by konichi3** [comment]
Hi @LarsKemmann 

Can you try to upgrade to Py3.8 or Py3.9?

**Comment by LarsKemmann** [comment]
I'm not using Python... Nowhere in my YAML is there a Python reference.

I just followed the CI/CD instructions for IoT Edge module development. My module is a C# (.NET 5/6) module.
________________________________

**Comment by konichi3** [comment]
There are two potential workaround that it may be worth trying.

1. Change the agent image to Ubuntu 20.0.4 ([source](https://github.com/microsoft/azure-pipelines-tasks/issues/13641))
or
2. Update cryptography agent version ([source](https://developercommunity.visualstudio.com/t/azure-iot-edge-2-preview-build-module-images-failu/586706))
