### ISSUE TITLE
[XamariniOS@2] Implement support for multiple provisioning profiles (specially for app extensions)

### ISSUE THREAD

**Issue by alexmartinezm** [microsoft/azure-pipelines-tasks#15904]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: XamariniOS@2

## Issue Description

In the current implementation of the Xamarin iOS task, there is a limitation that users can provide only one provisioning profile. But to sign an application that contains an extension requires two provisioning profiles. One for applications and another for an extension.

I have tried several workarounds as described in the issue [#10851](https://github.com/microsoft/azure-pipelines-tasks/issues/10851#issuecomment-658897518). This is a blocker for our company and there is a closed issue with this bug which had no feedback from the Microsoft team (see [#13300](https://github.com/microsoft/azure-pipelines-tasks/issues/13300)).

### Error logs

Getting the following error in the app extension:
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(1566,3): error : No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com./
```

**Comment by alexmartinezm** [comment]
Finally got it working by manually adding the provisioning profile name in the csproj and also specifying the full CodeSigningKey name (set from VS for Mac, didn't work from Windows).

However, this is an open issue with the Azure Pipeline task and should be fixed to prevent headaches.

Thanks.

**Comment by denis-tikhomirov** [comment]
Related ticket - https://github.com/microsoft/azure-pipelines-tasks/issues/13300.

**Comment by thisisthekap** [comment]
Please reopen!

**Comment by xleon** [comment]
This issue should be open as it is still a problem.
