### ISSUE TITLE
Feature: Generic Service Connection - Dynamic Auth Token

### ISSUE THREAD

**Issue by AdamCoulterOz** [microsoft/azure-pipelines-tasks#15925]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**:

Any task using the generic service connection, both agent and agent-less tasks

## Issue Description

Add ability to retrieve an access token for a given resource (e.g. Server URL) from an auth provider (e.g. `https://login.microsoftonline.com`) which is set as the password or token field for the generic service connection using another Service Connection (e.g. App, User, Managed, or even Generic). It would retrieve a new token every time a task uses the generic service connection.

**Comment by golubev-ivan** [comment]
Hi @AdamCoulterOz, this feature isn't related to tasks repository. Could you please submit the same issue to Microsoft developer community?

**Comment by AdamCoulterOz** [comment]
I have created it on the developer community ...

https://developercommunity.visualstudio.com/t/Generic-Service-Connection---Add-Dynamic/1671085
