### ISSUE TITLE
Download Secure Files false positive on downloading error string.

### ISSUE THREAD

**Issue by ChanceyC** [microsoft/azure-pipelines-tasks#15921]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadSecureFile@1

list here (V# not needed):    1.198.0
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks
<img width="506" alt="image" src="https://user-images.githubusercontent.com/94003254/153942608-3702390d-b2d3-4974-94e7-3c735be882db.png">

## Environment
- Server - Azure Pipelines or TFS on-premises? 

Azure pipeline
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

File downloaded is an error string , instead of expected file. Task is marked as successful

When downloading a file , sporadically a failure will occur (one in maybe 30 runs) , upon tracking it down the file has the text: `'{"$id":"1","innerException":null,"message":"TF15004: The download request signature has expired.","typeName":"Microsoft.TeamFoundation.Framework.Server.DownloadTicketValidationException, Microsoft.TeamFoundation.Framework.Server","typeKey":"DownloadTicketValidationException","errorCode":0,"eventId":4008}'`

Inside, instead of the normal expected text. 

This seems to be a duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/15479, however we are already using DownloadSecureFile@1. 

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadSecureFileV1/predownloadsecurefile.ts
The task itself expects the file to be present, and if so, is deemed a success. I think that the securefile-common (https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/securefiles-common/securefiles-common.ts), On line 50, where it writes to a pipe is responsible for this false-positive as it is writing the error output from the web-api call to the file, in the case that the [azure api](https://github.com/microsoft/azure-devops-node-api/blob/master/api/TaskAgentApiBase.ts#L5109) fails and is thereby fulfilling the task check that the file exists, where it should have failed.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ChanceyC** [comment]
It is also worth noting that sometimes the task will fail with the error ##[error]Error: connect ETIMEDOUT 13.107.42.20:443, which is expected. I think the difference is that the ETIMEDOUT is caught in the azure api and the promise is rejected , while the '{"$id":"1","innerException":null,"message":"TF15004: The download request signature has expired.","typeName":"Microsoft.TeamFoundation.Framework.Server.DownloadTicketValidationException, Microsoft.TeamFoundation.Framework.Server","typeKey":"DownloadTicketValidationException","errorCode":0,"eventId":4008}' is the direct promise return.

**Comment by CN120** [comment]
I am still seeing this error on recent versions of downloads

**Comment by adrastogi** [comment]
I'm seeing something similar to this in our build pipeline; the problem started a few days ago. The .pfx which should be getting downloaded from our library contains this output instead (the output seems potentially truncated):

`{"$id":"1","innerException":null,"message":"TF15004: The download request signature has expired.","typeName":"Microsoft.TeamFoundation.Framework.Server.DownloadTicketValidationException, Microsoft.Tea`

We're using `DownloadSecureFile@1`, version `1.247.1`. 

Is this a known issue? Is there something we need to change or update on our end? Our runs are currently blocked due to this.
