### ISSUE TITLE
CacheV2 fails to create hard links when untar'ing

### ISSUE THREAD

**Issue by ahaeber** [microsoft/azure-pipelines-tasks#15927]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private:  Hosted windows-2019
    
## Issue Description

This pipeline builds a CMake-style C++ application using Hunter (https://hunter.readthedocs.io/) for dependency management. It uses 2x CacheV2 tasks to cache the Hunter root folder (D:\a\1\h in the log below) and another external dependency.

It used to work fine, but now it has failed for the last builds with the same error as shown below.

### Task logs

Excerpt from log:
```
Entry found at fingerprint: `hunter|"Windows_NT"|OVYm6XF2Qrxyy/lKoSJc7ecKbrQcGzIrp8NuI+JRwr4=|5vyMrDIhpXmIhozVI5p0lwX2NNfY4iiZxU2/8PTZQr0=`

7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26


Extracting archive: 
Expected size to be downloaded: 1,124.7 MB
Downloaded 0.0 MB out of 1,124.7 MB (0%).
Downloaded 177.6 MB out of 1,124.7 MB (16%).
Downloaded 288.2 MB out of 1,124.7 MB (26%).
Downloaded 389.3 MB out of 1,124.7 MB (35%).
Downloaded 481.5 MB out of 1,124.7 MB (43%).
Downloaded 573.4 MB out of 1,124.7 MB (51%).
Downloaded 655.8 MB out of 1,124.7 MB (58%).
Downloaded 757.2 MB out of 1,124.7 MB (67%).
Downloaded 834.8 MB out of 1,124.7 MB (74%).
Downloaded 928.9 MB out of 1,124.7 MB (83%).
Downloaded 1,075.8 MB out of 1,124.7 MB (96%).
ERROR: Cannot create hard link : The system cannot find the file specified. : D:\a\1\h\_Base\b49fec6\25a3f7c\9acd169\Install\lib\libboost_atomic-mt-gd-x64.lib : D:\a\1\h\@LongHardLink
--
ERROR: Cannot set file attribute : The system cannot find the file specified. : D:\a\1\h\_Base\b49fec6\25a3f7c\9acd169\Install\lib\libboost_atomic-mt-gd-x64.lib
Path = 
Type = tar
ERROR: Cannot create hard link : The system cannot find the file specified. : D:\a\1\h\_Base\b49fec6\25a3f7c\9acd169\Install\lib\libboost_chrono-mt-gd-x64.lib : D:\a\1\h\@LongHardLink
Code Page = UTF-8
ERROR: Cannot set file attribute : The system cannot find the file specified. : D:\a\1\h\_Base\b49fec6\25a3f7c\9acd169\Install\lib\libboost_chrono-mt-gd-x64.lib
Characteristics = ASCII
ERROR: Cannot create hard link : The system cannot find the file specified. : D:\a\1\h\_Base\b49fec6\25a3f7c\9acd169\Install\lib\libboost_filesystem-mt-gd-x64.lib : D:\a\1\h\@LongHardLink
ERROR: Cannot set file attribute : The system cannot find the file specified. : D:\a\1\h\_Base\b49fec6\25a3f7c\9acd169\Install\lib\libboost_filesystem-mt-gd-x64.lib
```

**Comment by johnterickson** [comment]
What is `@LongHardLink`?  We're just invoking `tar` on the tarball we download, so maybe something about the source tree is odd in a way that `tar` can't handle it.

**Comment by ahaeber** [comment]
@johnterickson I don't have `@LongHardLink` locally. Actually, I don't see any hard links locally at all.

Not sure which version of tar you're using in the task, but I did find this piece of code in libarchive which looks to apply if the path becomes too long and would create similar hard links:
<https://fuchsia.googlesource.com/third_party/libarchive/+/refs/heads/upstream/master/libarchive/archive_write_set_format_pax.c#973>
```
if (linkpath != NULL) {
--
  | /* If link name is too long or has non-ASCII characters, add
  | * 'linkpath' to pax extended attrs. */
  | if (linkpath_length > 100 \|\| has_non_ASCII(linkpath)) {
  | add_pax_attr(&(pax->pax_header), "linkpath", linkpath);
  | if (linkpath_length > 100) {
  | if (hardlink != NULL)
  | archive_entry_set_hardlink(entry_main,
  | "././@LongHardLink");
  | else
  | archive_entry_set_symlink(entry_main,
  | "././@LongSymLink");
  | }
  | need_extension = 1;
  | }
  | }
```
However, I'm also a bit confused since this is executing on Windows and at <https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/PipelineCache/TarUtils.cs#L68> it says that 7-zip is used on Windows for tar and untar. 7zip does have something similar but it uses "@LongLink" instead of "@LongHardLink". So not sure what creates "@LongHardLink". See <https://github.com/kornelski/7z/blob/main/CPP/7zip/Archive/Tar/TarHeader.h> and notice that it defines kLongLink2 as "@LongLink"
```
  extern const char * const kLongLink;  //   = "././@LongLink";
  extern const char * const kLongLink2; //   = "@LongLink";
```

Btw, I found a similar issue (not related to Azure Pipelines) at https://github.com/concourse/fly/issues/31 which suggests to use `-x` for large archives.

**Comment by johnterickson** [comment]
On Window `7z` is used for `tar` extraction but `tar` is used for `tar` archiving: https://github.com/microsoft/azure-pipelines-agent/blob/cbb6efede9c8b92278f6ba1b7bb66c29706ef9ad/src/Agent.Plugins/PipelineCache/TarUtils.cs#L171

Isn't `-x` just `extract`? Am I missing something?

**Comment by ahaeber** [comment]
Sorry for the confusion, it appears that `-x` is an argument to concurse/fly in that issue and not tar.

I tried to re-run the build with a slightly different cache key, changing 'hunter' to 'hunterdep' in the front. It was built and cached ok. The next build got a cache miss, so it cached it again. Then, the third build got a cache hit but again fails to extract the cache archive.
