### ISSUE TITLE
AzureAppServiceSettings appsettings section, max length limited to 5000

### ISSUE THREAD

**Issue by bkvisiosign** [microsoft/azure-pipelines-tasks#15949]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureAppServiceSettings 

## Environment
Not relevant

## Issue Description

The AzureAppServiceSettings task allow only 5000 chars in the appsettings input field. We are hitting this limit, with no real way to extend it.

## Suggestion
Either increase the limit of appsettings input and/or allow a reference an external file (preferably on a blob storage)

**Comment by tedean66** [comment]
@bkvisiosign

**Comment by ionut-gheorghe** [comment]
I have the same problem, what's the alternative?
