### ISSUE TITLE
Unable to locate executable file: 'iotedgedev'

### ISSUE THREAD

**Issue by igorzdravkovic** [microsoft/azure-pipelines-tasks#15941]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureIoTEdgeV2

- Server - Azure Pipelines
- Agent - Hosted
vmImage windows-2019
agent version 2.198.3
AzureIoTEdge task version 2.199.0

## Issue Description

Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
[log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8092861/log.zip)

**Comment by marianan** [comment]
@igorzdravkovic thanks for reporting this issue. We will investigate and report findings here.

**Comment by arame** [comment]
Any news on this? I have the same problem.

**Comment by mathiash98** [comment]
I got the same issue but on following agents:
ubuntu-latest -> Ubuntu 20.04
windows-latest -> windows-2022

It is working on windows-2019 and ubuntu 18

And I have also noticed that the execution time of iotedgedev Generate Deployment Manifest has become slower and slower, I think it started around 30-60s build time, but on ubuntu 18 it increased to 6.5min. So I switched to windows-2019 which executes in 2.5-3min which is still veeeeery slow for just a json formater.

**Comment by mhshami01** [comment]
hello @igorzdravkovic, @arame, and @mathiash98.

The issue has been fixed with the latest task version 2.202.0

Thank you

**Comment by marianan** [comment]
Closing the issue, please update if the symptoms persist.
