### ISSUE TITLE
Device Guard blocking non-signed binaries when executing. System.IO.Abstractions.dll

### ISSUE THREAD

**Issue by sachip-msft** [microsoft/azure-pipelines-tasks#15946]
## Required Information
[VsTestV2] (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV2) and agent binaries are packaging unsigned dlls, This blocks execution of vstest task on our self-hosted windows agents which have device guard policies enforced.
Error: 
Error: Could not load file or assembly 'System.IO.Abstractions, Version=2.1.0.174, Culture=neutral, PublicKeyToken=96bf224d23c43e59' or one of its dependencies. Your organization used Device Guard to block this app.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Private: 
        - If using private agent, provide the OS of the machine running the agent and the agent version:  Windoes Server 2019, latest agent version

## Issue Description
Error: Could not load file or assembly 'System.IO.Abstractions, Version=2.1.0.174, Culture=neutral, PublicKeyToken=96bf224d23c43e59' or one of its dependencies. Your organization used Device Guard to block this app.

![image](https://user-images.githubusercontent.com/44178980/154737924-af54f03c-aca4-4477-a5b5-cc156f6e4473.png)

![image](https://user-images.githubusercontent.com/44178980/154738107-df0c210e-9cb8-448a-9ebb-dd66503d3cba.png)

https://user-images.githubusercontent.com/98756100/151817371-52d853b5-cf3a-4640-9bed-9685e3458fde.png

### Task logs

2022-01-28T13:30:23.7417720Z ##[error]TestExecution encountered unexpected failures System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.
2022-01-28T13:30:23.7426874Z ##[debug]Processed: ##vso[task.logissue type=error;]TestExecution encountered unexpected failures System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.
2022-01-28T13:30:23.7427621Z
2022-01-28T13:30:23.7428299Z 1) Could not load file or assembly 'System.IO.Abstractions, Version=2.1.0.174, Culture=neutral, PublicKeyToken=96bf224d23c43e59' or one of its dependencies. Your organization used Device Guard to block this app. Contact your support person for more info. (Exception from HRESULT: 0x800711C7)
2022-01-28T13:30:23.7429199Z
2022-01-28T13:30:23.7429557Z Resulting in: An exception occurred while trying to create an instance of type 'Microsoft.VisualStudio.TestService.AgentExecutionHost.JsonInputParser'.
2022-01-28T13:30:23.7429837Z
2022-01-28T13:30:23.7430125Z Resulting in: Cannot activate part 'Microsoft.VisualStudio.TestService.AgentExecutionHost.JsonInputParser'.
2022-01-28T13:30:23.7430848Z Element: Microsoft.VisualStudio.TestService.AgentExecutionHost.JsonInputParser -->

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

Those dlls are used by the azdo agent, and it’s tasks. The offending task is VSTest Azdo task (among others). 

![image](https://user-images.githubusercontent.com/44178980/154738355-558c9fed-2481-47ef-9c6c-47b09e6fb5d8.png)

The agent (on the left) shipment is correct. It re-signs the 3rd party dll with Microsoft 3rd party signature: 
(microsoft/azure-pipelines-agent: Azure Pipelines Agent 🚀 (github.com) this is where you can download it, and they would probably know where it is signed). 

If we look at the vstest task (on the right) we can see that the library does not have a digital signature, and so the target system cannot be sure about its integrity:

 

There are few other tasks in my deployment that were downloaded when running a very simple azdo pipeline, which need fixing as well: 

Get-ChildItem C:\w\a1\_work\_tasks -re | where name -like *.dll | Get-AuthenticodeSignature | where status -eq notsigned

    Directory: C:\w\a1\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.198.0\ps_modules\VstsTaskSdk

SignerCertificate                         Status                                                          Path
-----------------                         ------                                                          ----
                                          NotSigned                                                       Minimatch.dll

    Directory: C:\w\a1\_work\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.198.0\node_modules\azure-pipelines-tasks-utility-common\tools\7zip

SignerCertificate                         Status                                                          Path
-----------------                         ------                                                          ----
                                          NotSigned                                                       7z.dll

    Directory: C:\w\a1\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.198.0\Modules

SignerCertificate                         Status                                                          Path
-----------------                         ------                                                          ----
                                          NotSigned                                                       Ben.Demystifier.dll
                                          NotSigned                                                       Minimatch.dll
                                          NotSigned                                                       Polly.dll
                                          NotSigned                                                       System.IO.Abstractions.dll

    Directory: C:\w\a1\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.198.0\TestSelector

SignerCertificate                         Status                                                          Path
-----------------                         ------                                                          ----
                                          NotSigned                                                       Minimatch.dll
                                          NotSigned                                                       Newtonsoft.Json.dll

### Error logs

Error: Could not load file or assembly 'System.IO.Abstractions, Version=2.1.0.174, Culture=neutral, PublicKeyToken=96bf224d23c43e59' or one of its dependencies. Your organization used Device Guard to block this app.

**Comment by anatolybolshakov** [comment]
@AndreyIvanov42 could you please take a look?

**Comment by AndreyIvanov42** [comment]
Hi @sachip-msft 
At the moment, the signing and verification process is going at a higher level by using a zip archive with tasks. Therefore, there are no security concerns in the execution of the files themselves, which are included in this archive.
In order to add a signing step for unsigned VstsTaskSdk files, we will need time, because now our team doesn't own access to this package publishing process.

**Comment by ivan-marquez** [comment]
Hi @AndreyIvanov42, any updates regarding the VstsTaskSdk files signing step? Thanks!

**Comment by sachip-msft** [comment]
We need all files to be signed otherwise it does not execute in CI enforced environments.
