### ISSUE TITLE
Bash task has command failing with exit code 2 but the pipeline task doesn't fail

### ISSUE THREAD

**Issue by tomkivlin** [microsoft/azure-pipelines-tasks#15953]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug, maybe

**Enter Task Name**: BashV3

## Environment
- Server - Azure Pipelines or TFS on-premises?  Azure Pipelines

- Agent - Hosted or Private: Private (Ubuntu 20.04, agent version 2.182.1)

## Issue Description

I am using the BashV3 task, as follows (this is a snippet of a pipeline that uses two repositories):

```yaml
- bash: build/ado_scripts/build-docs.sh
  displayName: Build docs using sphinx-build
  workingDirectory: $(Build.Repository.LocalPath)/VodafoneOneCloud-dev
  env:
    PIPELINE_WORKSPACE: $(Pipeline.Workspace)
    AGENT_BUILDDIRECTORY: $(Agent.BuildDirectory)
```

As I understood it, if `failOnStderr` was set to `false` (as it is by default) then the task will fail if there is a non-zero exit code.

The script that is called includes the following lines:

```bash
make BUILDDIR="$AGENT_BUILDDIRECTORY" html
echo $?
```

The Makefile includes:

```make
SPHINXOPTS    = -W -n
SPHINXBUILD   = sphinx-build
SOURCEDIR     = .
#BUILDDIR      = /tmp

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

The logs for this task include the following, which shows the exit code of the sphinx-build command is `2` not `0`.  

```
2022-02-21T11:46:03.8283410Z Warning, treated as error:
2022-02-21T11:46:03.8284697Z /opt/azdo-agent/_work/16/s/VodafoneOneCloud-dev/CONTRIBUTING.md:16:'myst' reference target not found: #figures
2022-02-21T11:46:05.7496958Z make: *** [Makefile:20: html] Error 2
2022-02-21T11:46:05.7504042Z + echo 2
```

But the pipeline passes without failing.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[logs_879.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8109039/logs_879.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2022-02-21T11:46:03.8283410Z Warning, treated as error:
2022-02-21T11:46:03.8284697Z /opt/azdo-agent/_work/16/s/VodafoneOneCloud-dev/CONTRIBUTING.md:16:'myst' reference target not found: #figures
2022-02-21T11:46:05.7496958Z make: *** [Makefile:20: html] Error 2
2022-02-21T11:46:05.7504042Z + echo 2
```

**Comment by DaniilShmelev** [comment]
Hi @tomkivlin! Could you please run this script locally and ensure that it outputs anything into stderr, or exits with a non-zero exit code?
My guess here is that your script may only be logging these errors to stdout. I'm pretty sure that your script exits with code 0. The call to 'make' exits with code 2, but it doesn't affect the calling script.

**Comment by tomkivlin** [comment]
Ah yes, that's the issue - I'd assumed that the call to make would trigger the failure but you're right the calling script still exits with code 0.  Just need some logic round the make command, no problem.  Thanks again.
