### ISSUE TITLE
CmdLine setting env. variables with wrong name

### ISSUE THREAD

**Issue by vininew921** [microsoft/azure-pipelines-tasks#15965]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CmdLine

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Private 2.153.1

## Issue Description

Environment variable names are being set different than what is expected. If I have a variable named `SECRET` in a variable group, and I want to set an environment variable named `VUE_APP_SECRET`, it will instead be set with `SECRET` as its name.

Environment variable set in task:
![image](https://user-images.githubusercontent.com/56614071/155525870-269845af-0b42-4809-a548-0139e5762e40.png)

Expected result:
Set environment variable with name `VUE_APP_SECRET` and value `SECRET`

Expected result inside built app:
`NODE_ENV:"production",VUE_APP_SECRET:"SECRET"`

Actual result:
Environment variable is set with name `SECRET` and value `SECRET`

Actual result inside built app:
`NODE_ENV:"production",SECRET:"SECRET"`

**Comment by DaniilShmelev** [comment]
Thanks for the issue-reporting in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.

**Comment by golubev-ivan** [comment]
Hi @vininew921, I can't reproduce this issue. I see two environment variables (SECRET and VUE_APP_SECRET) with correct values after these actions. Are you still facing this problem?

**Comment by anatolybolshakov** [comment]
Hi @vininew921 do you have any updates?

**Comment by vininew921** [comment]
Hi, I'm no longer working on the project that had these issues, but to answer to @golubev-ivan, there shouldn't be a variable with the name `SECRET` created, that is just the value that should be set for the `VUE_APP_SECRET` variable, which is not created.
