### ISSUE TITLE
Run XamarinAndroid build task failed

### ISSUE THREAD

**Issue by Dolphinsimon** [microsoft/azure-pipelines-tasks#15960]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: XamarinAndroid  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines       

- Agent - Hosted

## Issue Description

Can not build Android project with XamarinAndroid task.

### Task logs

_AndroidAot:
  [mkbundle stderr] 
  [cc stderr] 'C:\Program' is not recognized as an internal or external command,
  [cc stderr] operable program or batch file.
  [cc stderr] 
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(729,5): Error XA5103: NDK C compiler exited with an error. Exit code 0
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(729,5): error XA5103: NDK C compiler exited with an error. Exit code 0 [D:\a\1\s\App.Android\App.Android.csproj]
Done Building Project "D:\a\1\s\App.Android\App.Android.csproj" (SignAndroidPackage;PackageForAndroid target(s)) -- FAILED.

Build FAILED.

**Comment by Dolphinsimon** [comment]
The same sources were built successfully with version 1.197.1. The latest version is 1.198.0

**Comment by DaniilShmelev** [comment]
Update from 1.197.1 to 1.198.0 only introduced localization changes: https://github.com/microsoft/azure-pipelines-tasks/pull/15633. Not sure how this could affect task behavior.
Could you please send a pipeline yaml with repro and the pipeline logs for both failing (1.198.0) and successful (1.197.1) cases?
You can send them to v-dshmelev@microsoft.com

**Comment by Dolphinsimon** [comment]
@DaniilShmelev I have sent the logs and yaml files.

**Comment by kkuepper** [comment]
we're experiencing the exact same problem

**Comment by iury-kc** [comment]
having the same error trying to debug platform.uno on android emulator

**Comment by DaniilShmelev** [comment]
Looks like an issue with virtual environment. Just to confirm, could you please pin your XamarinAndroid task version and try to run the pipeline again?
You can do it like this:
```yaml
- task: XamarinAndroid@1.197.1
```

**Comment by Dolphinsimon** [comment]
@DaniilShmelev I have tested with 1.197.1. You are right, it may be an issue with azure pipeline environment.

**Comment by Dolphinsimon** [comment]
Can you transfer this issue to azure pipeline team?

**Comment by Brayanhenaor** [comment]
I have the same issue

**Comment by kkuepper** [comment]
Is there a way to pin the task version with the classic pipelines? Or do we need to migrate to yaml for that?

**Comment by DaniilShmelev** [comment]
@kkuepper no, there is no way to pin the task version in classic pipelines. As we've checked, this failure is not related to task version - the issue seems to be on the side of the virtual image

**Comment by kkuepper** [comment]
Just to recap:
The issue does not occur if I pin the version of the task in yaml to 1.197.1. But it's not related the azure pipeline task itself. Instead it's introduced by the virtual environments team?
Do I understand this correctly? I also wouldn't mind to get some more technical details about what you learned in the process of finding that out.

**Comment by DaniilShmelev** [comment]
> Just to recap: The issue does not occur if I pin the version of the task in yaml to 1.197.1. But it's not related the azure pipeline task itself. Instead it's introduced by the virtual environments team? Do I understand this correctly? I also wouldn't mind to get some more technical details about what you learned in the process of finding that out.

@kkuepper Does the task fail for you on 1.198.0 but succeed on 1.197.1? If so, could you please share the logs for both cases? v-dshmelev@microsoft.com
Update from 197 to 198 only changed task localization, so it shouldn't have affected task behavior.

**Comment by kkuepper** [comment]
Oh. I see.
I misunderstood.

**Comment by kkuepper** [comment]
I was able to make the task run again by switching to the latest version of Android NDK.
By default, 21.4.7075529 is used and I switched it to 23.1.7779620 by passing `-p:AndroidNdkDirectory=$(ANDROID_NDK_LATEST_HOME)` in msbuildArguments

See [https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#android](Windows 2022 Readme) about which versions are available.

**Comment by EmilAlipiev** [comment]
Still the problem and using p:AndroidNdkDirectory=$(ANDROID_NDK_LATEST_HOME) in msbuildArguments doesnt fix the issue. I get another error MSBUILD : error MSB1008: Only one project can be specified if i set that. I have tried using between " double quotes but it didnt help.

**Comment by chaosifier** [comment]
I'm getting the same issue. Any updates?

**Comment by Dolphinsimon** [comment]
@EmilAlipiev @chaosifier This is not a bug with the task. It's about the virtual environment. The NDK version has been updated recently. Please check this [Android NDK 22 will be replaced in favor of 24, version 23 will be set as the default one on June, 6](https://github.com/actions/virtual-environments/issues/5595)

**Comment by kkuepper** [comment]
I think the problem we experience is best described in https://github.com/actions/virtual-environments/issues/5987 .
Basically, something on the build image makes it build against Android Api 16, which has to fail.

**Comment by soroshsabz** [comment]
related to https://github.com/xamarin/xamarin-android/issues/6808
