### ISSUE TITLE
Using dotnet workload install with custom feeds

### ISSUE THREAD

**Issue by AlexEyler** [microsoft/azure-pipelines-tasks#15963]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?** 
*Type*:  Bug

**Enter Task Name**: DotNetCoreCLIV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines (internal Microsoft)

## Issue Description

We've added support to build our WebAssembly project using AoT, which requires installing a couple workloads in dotnet 6:
* dotnet workload install macos
* dotnet workload install wasm-tools

Initially, I added this task to our pipeline:
```yml
- task: DotNetCoreCLI@2
    displayName: "dotnet workload install macos"
    inputs:
      command: 'custom'
      custom: 'workload'
      arguments: 'install macos'
```

This fails with the following error, though:
```
Failed to update the advertising manifest microsoft.net.sdk.android: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.sdk.ios: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.sdk.maui: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.workload.emscripten: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.sdk.tvos: Response status code does not indicate success: 401 (Unauthorized)..
Failed to update the advertising manifest microsoft.net.sdk.macos: Response status code does not indicate success: 401 (Unauthorized)..
Installing pack Microsoft.macOS.Sdk version 12.0.101-preview.9.31...
Workload installation failed. Rolling back installed packs...
Rolling back pack Microsoft.macOS.Sdk installation...
Workload installation failed: Response status code does not indicate success: 401 (Unauthorized).
```
Our pipeline uses an internal AzureDevOps feed that uses nuget.org as an upstream feed. Per company requirements we must use this feed, but it appears that we can't load the feed using the `custom` dotnet task.

I was able to workaround this issue by discovering the temp nuget.config created in the `dotnet restore` task (which we run earlier in the pipeline) and then passing it into the `dotnet custom` task:
```yml
  - powershell: |
      $dir = $env:AGENTBUILD_DIR
      if (-not $dir) {
        $dir = $env:AGENTTEMP_DIR
      }
      $tempFileName = "tempNuget_$($env:BUILDID).config"
      $nugetPath = Join-Path $dir "Nuget"
      $tempFileNugetPath = Join-Path $nugetPath $tempFileName
      Write-Host "##vso[task.setvariable variable=tempNugetConfig;]$tempFileNugetPath"
    env:
      AGENTBUILD_DIR: $(Agent.BuildDirectory)
      AGENTTEMP_DIR: $(Agent.TempDirectory)
      BUILDID: $(Build.BuildId)

  - task: DotNetCoreCLI@2
    displayName: "dotnet workload install macos"
    inputs:
      command: 'custom'
      custom: 'workload'
      arguments: 'install macos --configfile $(tempNugetConfig)'

  - task: DotNetCoreCLI@2
    displayName: "dotnet workload install wasm-tools"
    inputs:
      command: 'custom'
      custom: 'workload'
      arguments: 'install wasm-tools --configfile $(tempNugetConfig)'
```

Is there a different approach to support reading from internal nuget feeds for installing workloads in dotnet 6?

**Comment by AlexEyler** [comment]
Hi @bishal-pdMSFT - is there anything I can do to help get this tracked? It's caused us to have to do some pretty significant hacks in order to make our build pipelines work with workloads.

**Comment by frabe1579** [comment]
Same here, if I delete nuget.config (it contains my private repository and nuget.org), workload restore/install runs without problems.

**Comment by georgedobrin** [comment]
Anybody with a solution yet? I am experiencing the same issues
