### ISSUE TITLE
AzureRmWebAppDeployment fails due to missing permission to perform joinViaServiceEndpoint/action on subnet

### ISSUE THREAD

**Issue by mortenn** [microsoft/azure-pipelines-tasks#15961]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Private agent, current version, running on Windows 2019 VM in Azure

## Issue Description

During deployment, the build prints a warning and fails:
##[warning]Failed to update App Service configuration details. Error: Error: Failed to update App service 'web-...' configuration. Error: The client '5ef...0af' with object id '5ef...0af' has permission to perform action 'Microsoft.Web/sites/config/write' on scope '/subscriptions/3fe..e61/resourceGroups/rg-.../providers/Microsoft.Web/sites/web-.../config/web'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/3fe...e61/resourceGroups/rg-.../providers/Microsoft.Network/virtualNetworks/vnet-.../subnets/snet-...' or the linked scope(s) are invalid. (CODE: 403)

yaml for step:
```yaml
          - task: AzureRmWebAppDeployment@4
            inputs:
              azureSubscription: $(Subscription)
              ConnectionType: 'AzureRM'
              appType: 'webApp'
              WebAppName: $(AppServiceName)
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
```

The DevOps service principal has contributor access to the resource group of the webapp.

**Comment by v-nagarajku** [comment]
Hi @mortenn , Please limit the service principal access scope to the particular web app trying to deploy as contributor, which we are using in service connection. We have created the service principal and added the service connection with same service principal and provided contributor access to web app scope only. It is working fine.

**Comment by mortenn** [comment]
The error did not get logged this time, after I revoked the subscription level access, I am guessing it already did what it tried doing and no longer is trying to do it, thus not hitting the error anymore.

The app service is not working, though, but that is a different issue.
I am getting a "You do not have permission to view this directory or page." message when I open the page.
I've opened the console in the app service, but I appear unable to issue commands, as I just get a spinner and then a red text saying "Failed to execute the command" and a spinner that remains spinning forever.

Got any quick tips for me to figure that one out?

**Comment by mortenn** [comment]
Worked out why the app was not working, all good now.
Still not sure about the reason for the original error, though

**Comment by v-nagarajku** [comment]
Hi @mortenn, Is still issue persists or good to close the ticket?

**Comment by mortenn** [comment]
It's "fixed" for me, but I think it could still happen to someone else setting it up in the future, as the underlying issue should still be there by my reckoning.

I do not know what exactly the deployment did when it had the extra permissions, but it must have done something that made the error go away after revoking the extra permission.

**Comment by v-nagarajku** [comment]
Hi @mortenn, it could be a transient issue, since in our repro it was not occurred. We will go closure for this ticket post your confirmation.

**Comment by mortenn** [comment]
##[debug][PUT]https://management.azure.com/subscriptions/3febe310-a6e3-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/web?api-version=2018-02-01
##[debug]Correlation ID from ARM api call response : **c4eb52c8-5660-4d53-b7f1-4da4390d79c4**
##[debug]Processed: ##vso[task.logissue type=error;code=LinkedAuthorizationFailed;]

**Comment by mortenn** [comment]
It is a contributor on the app service

**Comment by mortenn** [comment]
I will make the change and test.

the subnet in the message is the subnet the devops build agent is running on, the app does not itself have anything to do with that vnet.

**Comment by mortenn** [comment]
Same error after giving the service principal contributor access to the ASP og the web app.

**Comment by mortenn** [comment]
Granting the service principal contributor access to the subnet makes the error go away.

Before:
```
##[debug]updating SCM Type to VSTS-RM
##[debug][PUT]https://management.azure.com/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/web?api-version=2018-02-01
##[debug]Correlation ID from ARM api call response : 49de124d-828d-441b-9a0b-b5fea8e2ec4a
##[debug]Processed: ##vso[task.logissue type=error;code=LinkedAuthorizationFailed;]
##[warning]Failed to update App Service configuration details. Error: Error: Failed to update App service 'web-REDACTED-app-tf' configuration. Error: The client '5efbad40-REDACTED' with object id '5efbad40-REDACTED' has permission to perform action 'Microsoft.Web/sites/config/write' on scope '/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/web'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-network-prod/providers/Microsoft.Network/virtualNetworks/vnet-REDACTED-tools-prod/subnets/snet-vm-REDACTED-build-prod' or the linked scope(s) are invalid. (CODE: 403)
##[debug]Processed: ##vso[task.issue type=warning;]Failed to update App Service configuration details. Error: Error: Failed to update App service 'web-REDACTED-app-tf' configuration. Error: The client '5efbad40-REDACTED' with object id '5efbad40-REDACTED' has permission to perform action 'Microsoft.Web/sites/config/write' on scope '/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/web'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-network-prod/providers/Microsoft.Network/virtualNetworks/vnet-REDACTED-tools-prod/subnets/snet-vm-REDACTED-build-prod' or the linked scope(s) are invalid. (CODE: 403)
```

After:
```
##[debug]updated SCM Type to VSTS-RM
##[debug]Updating metadata with latest pipeline details
##[debug]system.teamfoundationCollectionUri=https://dev.azure.com/REDACTED/
##[debug]system.teamprojectId=dc67cf0a-REDACTED
##[debug]release.definitionId=undefined
##[debug]system.collectionId=8b78ac58-REDACTED
##[debug]system.definitionId=7
##[debug][POST]https://management.azure.com/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/metadata/list?api-version=2016-08-01
##[debug]Correlation ID from ARM api call response : 12c21217-4c60-4046-859d-2d1469f77a08
##[debug][POST]https://management.azure.com/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/metadata/list?api-version=2016-08-01
##[debug]Correlation ID from ARM api call response : e61dbe9e-2959-44cb-bbf0-cdbc406ccd03
##[debug][PUT]https://management.azure.com/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/config/metadata?api-version=2016-08-01
##[debug]Correlation ID from ARM api call response : f2aa8d94-caa7-42c1-b121-872e90395ba9
##[debug]Updated metadata with latest pipeline details
```

**Comment by mortenn** [comment]
The deployment task appears to be setting up deployment center on the app service at 
https://portal.azure.com/#@REDACTED.onmicrosoft.com/resource/subscriptions/3febe310-REDACTED/resourceGroups/rg-REDACTED-app-tf/providers/Microsoft.Web/sites/web-REDACTED-app-tf/vstscd

The page displays this error message, btw;
`We were unable to connect to the Azure Pipeline that is connected to this Web App. This could mean it has been removed from the Azure Dev Ops Portal. If this has happened, you can disconnect this pipeline and set up a new deployment pipeline.`

Could this be related to the app service being connected to a private subnet?
It probably doesn't matter much, but an error is an error.

**Comment by mortenn** [comment]
I tried setting up the deployment center connection manually, but the organization the repo/pipeline belongs to is not available to me in the dropdown, even though my user does have access to the organization.

**Comment by osekodk** [comment]
I'm experiencing the exact same behaviour.

**Comment by tonnesen-ncqa** [comment]
> We are using the pipeline task [AzureRmWebAppDeployment](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines) to deploy an app service via a self-hosted agent from Azure DevOps.
> 
> At the end of the AzureRmWebAppDeployment task ([source](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/ContainerWebAppDeploymentProvider.ts#L23)) there is an attempt to to set the scmType to "VSTSRM" in case it is empty ([source](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts#L22)). This triggers the PUT request to /config/web that ultimately fails and produces the warning described above.
> 
> Our workaround was to set the scmType of the app service preemptively:
> 
> ```
> az webapp config set -g ... -n ... --generic-configurations "{\`"scmType\`": \`"VSTSRM\`"}"
> ```
> 
> Afterwards, new deployments did not produce the warning anymore.

@LexLuengas - I appreciate you digging into the source of the action and posting this fix! This affects almost all of my yaml CD pipelines in ADO, including tasks "AzureWebAppContainer@1" and "AzureRmWebAppDeployment@4."

My formatting for the command was a bit different, so I thought I would share.
```cli
az webapp config set -g "<rg>" -n "<appName>" --generic-configurations "{\"scmType\": \"VSTSRM\"}"
```

In the future, I will add this to my bicep templates. Microsoft, please fix these tasks.

**Comment by mortenn** [comment]
I opened #19709 to try and get some attention on this issue that should be fairly trivial to fix - even if they just add a better error message

**Comment by pietersap** [comment]
We have encountered the same problem, our setup was as follows:

- the pipeline runs on a self-hosted build agent inside a subnet of our private VNET.
- the appservice had IP restrictions, allowing traffic from certain sources only and denying traffic from other sources. Amonst others, there was a rule that allowed traffic coming from the subnet of our build agents (aka there is a service endpoint for this subnet).
- the IP restrictions were only applied to the main site, and not to the "advanced tool site"

In our builds, we saw the same warning:

```
##[warning]Failed to update App Service configuration details. Error: Error: Failed to update App service 'XXXXX' configuration. Error: The client 'XXXXX' with object id 'XXXXX' has permission to perform action 'Microsoft.Web/sites/slots/config/write' on scope '/subscriptions/XXXXX/resourceGroups/XXXXX/providers/Microsoft.Web/sites/XXXX/slots/XXXX/config/web'; however, it does not have permission to perform action(s) 'Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Network/virtualNetworks/OUR-DEVOPS-SUBNET-CONTAINING-BUILD-AGENTS' (respectively) or the linked scope(s) are invalid. (CODE: 403)
```

From the message, I deduce that the AzureRmAppServiceDeployment attempts to setup the service endpoint for the subnet that it is running in, which it cannot do because it does not have permission to do so. 

in the build summary, we see a red error messagings saying "no message found for this issue", but the pipeline succeeds without a problem.

To get rid of the warning, we enabled the same IP restrictions (including allowing the build agents subnet) to the "advanced tool site". This is also a security improvement, making the advanced SCM tool site ("kudu") and the console unavailable to unwanted clients, just like the main site. In the portal, this is a checkbox "use main site rules". The reasoning behind this solution, is that the pipeline no longer needs to link a service endpoint for the advanced tool site during the deploy because it's already there

**Comment by pietersap** [comment]
We have encountered the same problem, our setup was as follows:

- the pipeline runs on a self-hosted build agent inside a subnet of our private VNET.
- the appservice had IP restrictions, allowing traffic from certain sources only and denying traffic from other sources. Amonst others, there was a rule that allowed traffic coming from the subnet of our build agents (aka there is a service endpoint for this subnet).
- the IP restrictions were only applied to the main site, and not to the "advanced tool site". 


It's weird that we get this issue when the advanced tool site has no restrictions at all (effectively accepting deploys from anywhere, if I understand correctly). For other appservices that have no IP restrictions at all, there is no such issue

**Comment by pietersap** [comment]
> We are using the pipeline task [AzureRmWebAppDeployment](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines) to deploy an app service via a self-hosted agent from Azure DevOps.
> 
> At the end of the AzureRmWebAppDeployment task ([source](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/ContainerWebAppDeploymentProvider.ts#L23)) there is an attempt to to set the scmType to "VSTSRM" in case it is empty ([source](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts#L22)). This triggers the PUT request to /config/web that ultimately fails and produces the warning described above.
> 
> Our workaround was to set the scmType of the app service preemptively:
> 
> ```
> az webapp config set -g ... -n ... --generic-configurations "{\`"scmType\`": \`"VSTSRM\`"}"
> ```
> 
> Afterwards, new deployments did not produce the warning anymore.

Thanks! it looks to me that the same thing can be achieved using the ["ConfigurationSettings" parameter of the AzureRmWebAppDeployment task itself:](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines)

```
- task: AzureRmWebAppDeployment
  inputs:
     # hiding other inputs...
    ConfigurationSettings: -scmType VSTSRM
```

Since I enabled this, the issue has been solved.
