### ISSUE TITLE
Azure CLI Task is emitting a lot of log output

### ISSUE THREAD

**Issue by jhueppauff** [microsoft/azure-pipelines-tasks#15970]
*Type*: Question (maybe a feature request)

**Enter Task Name**: AzureCLI

## Environment
Azure Pipelines - affects all accounts

- Agent - Hosted or Private: 
    
Hosted agent and private agent

## Issue Description

I am using the AzureCLI Task in a pipeline to build bicep files. 

    - task: AzureCLI@2  
      displayName: 'Build bicep artifact' 
      inputs: 
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file $(Build.SourcesDirectory)/templates/keyvault.bicep'

The task emits an unnecessary amount of output which makes it harder to catch the important and "real" log output.

As far as I can tell it runs az --version which takes about 20 lines and then it prints out every subscription it seems to have access to. Which in my case adds 60 lines of output.

The only output the inline script produces (when everything goes right) is 0.

It feels a bit wrong to print out so much unnecessary information and it makes it hard to catch the important stuff.
Is there any option to reduce the amount of log output?

**Comment by TripleMalahat** [comment]
I agree entirely. I came looking for info on this behaviour as well. I found this closed issue from last year: https://github.com/microsoft/azure-pipelines-tasks/issues/14156. It has a not-ideal workaround in it but no fix. Any chance this behaviour could be revisited? My environment have over 100 subscriptions in it so this makes the logs for each AzureCLI@2 task an absolute mess.

**Comment by piotr-gbyliczek** [comment]
I've come across this issue too and attempted to change the code to facilitate hiding extra output: https://github.com/microsoft/azure-pipelines-tasks/pull/16701.

**Comment by syedhamjath** [comment]
There is no harm in reducing the log size to make everyone life less difficult.
