### ISSUE TITLE
Azure App Service Deployment missing task to deploy Web App For Containers (Windows)

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/azure-pipelines-tasks#15971]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Azure App Service Deployment 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 

- Agent - Hosted 
    

## Issue Description

There is no option to deploy for Web App for containers (Windows), only linux one is available

**Comment by AKSNewbie** [comment]
Great to see i am not the only one that has spotted this. I have tried setting up this task in YAML and Classic but it only seems to work when using a Linux Container deployed to the App Service. I have found nothing in the documentation/Prerequisites that states this task is only for Linux containers.
