### ISSUE TITLE
WinRM HTTPS sample link not working

### ISSUE THREAD

**Issue by dennischavez789** [microsoft/azure-pipelines-tasks#15976]
Hi,
I'm getting a 404 page not found with clicking on the "sample template" link under the "Setting up a virtual machine for WinRM HTTPS using Azure Templates:" paragraph.

Here is the link to the page: https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2
Here is the "sample template" link that is not working: https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-winrm-windows

**Comment by DenisRumyantsev** [comment]
Hi @dennischavez789, thanks for reporting this issue. We can not start working on it and fix broken link right now, but we will be back as soon as we can.
