### ISSUE TITLE
When migrating to Node10, what does "The following fs functions all have incompatibilities" really mean?

### ISSUE THREAD

**Issue by johnsimons** [microsoft/azure-pipelines-tasks#15987]
Question regarding migration to Node10.

According to https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md#fs-module, it mentions  "The following fs functions all have incompatibilities".

So does this mean we should not use those APIs? What is the recommended migration for these?

Regards
John

**Comment by anatolybolshakov** [comment]
Hi @johnsimons this means that there could be some behavioral/API changes for these nodejs methods while switching from node 6 to node 10 - so if you use them in your task, or there are some dependencies which use it - we suggest to make additional testing/check tests coverage to make sure that it works as expected.
