### ISSUE TITLE
Run PowerShell task using AzPipelines VSC extension

### ISSUE THREAD

**Issue by WilliamAntonRohm** [microsoft/azure-pipelines-tasks#15982]
Copied here from:  https://github.com/MicrosoftDocs/azure-devops-docs/issues/12014

per comment:  https://github.com/MicrosoftDocs/azure-devops-docs/issues/12014#issuecomment-1057018514

**Comment by anatolybolshakov** [comment]
Hi @Ayanmullick could you please describe your issue in more details? Do you use PowerShell or AzurePowerShell pipeline task?

**Comment by Ayanmullick** [comment]
Hi @anatolybolshakov

I was unable to contact you thru Teams.  I'm using the [AzPowerShell pipeline task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops). Is there a way to  the pipeline task from VSC using the [AzPipeline extension](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines)?

**Comment by anatolybolshakov** [comment]
Hi @Ayanmullick sorry, I have some access issues at the moment - as I know there is know way to run it using this extension.
You can also ask more questions about this extension in https://github.com/Microsoft/azure-pipelines-vscode.

**Comment by Ayanmullick** [comment]
@anatolybolshakov, Is there a way to manage module dependencies for AzPowerShell tasks [like one can in AzFunctions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#dependency-management)?

**Comment by anatolybolshakov** [comment]
cc @rvairavelu as the owner of AzurePowershell task - do you know maybe the answer to this one?

**Comment by WilliamAntonRohm** [comment]
#assign:@anatolybolshakov

**Comment by rvairavelu** [comment]
@v-nagarajku can you please check on this?
