### ISSUE TITLE
Migrating to Node10 and ES2018

### ISSUE THREAD

**Issue by johnsimons** [microsoft/azure-pipelines-tasks#15991]
I am in the process of migrating my tasks to Node 10, and I've updated the target to ES2018 (as per [doc regarding compatibility of Node10](https://node.green)), but it doesn't seem to work.
I use the `"extends": "@tsconfig/node10/tsconfig.json"` in my tsconfig.json file.

According to https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops&viewFallbackFrom=vsts#create-tsconfigjson-compiler-options, it seems even with Node10 we still need to target ES6, is this right?

The error I am getting is
```
##[error]TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
```

I don't really know how to get more information about this error, is there any flags I can enable to get more diagnostics?

**Comment by johnsimons** [comment]
I figure out the issue with `Callback must be a function`.

But I still would like to know if I am going to run into any issues if I target `ES2018`?

**Comment by DenisRumyantsev** [comment]
Hi @johnsimons, we can not start working on your question right now, but we will be back as soon as we can.

**Comment by johnsimons** [comment]
@DenisRumyantsev, I am targetting ES2018, and as fast as I can see everything works fine.

**Comment by DenisRumyantsev** [comment]
@johnsimons, thanks for update. Since everything works correctly, could this issue be closed?

**Comment by johnsimons** [comment]
@DenisRumyantsev I guess you can close the issue, but IMO it would still be nice to have some kind of official answer regarding ES2018 vs ES6?
