### ISSUE TITLE
Deprecating specific versions of a task

### ISSUE THREAD

**Issue by johnsimons** [microsoft/azure-pipelines-tasks#15992]
Is there a way to deprecate specific versions of a task?
In other words I want my users to migrate to the new versions of the task, what would be the best way to achieve this?

**Comment by DenisRumyantsev** [comment]
Hi @johnsimons, task can be marked as `deprecated` via the appropriate property in the `task.json` file.
The related documentation about tasks deprecation can be found [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/deprecatedtasks.md).

**Comment by johnsimons** [comment]
@DenisRumyantsev I have read that documentation but to me just marking a task with the `deprecated` property is not very visible, so I ended up changing the display name of the task:
![image](https://user-images.githubusercontent.com/122651/157777717-01868d8f-624b-46fa-9a20-abf60426d755.png)
And also added a warning:
![image](https://user-images.githubusercontent.com/122651/157787292-1716bbb3-8b71-4a33-b0e3-856e8682435f.png)

Much more visible than the little flag.

**Comment by DenisRumyantsev** [comment]
Hi @johnsimons, do you have any additional questions?

**Comment by johnsimons** [comment]
Nope, all good, thank you
