### ISSUE TITLE
CopyFilesOverSSH cleanTargetFolder does not delete hidden files

### ISSUE THREAD

**Issue by boubou191911** [microsoft/azure-pipelines-tasks#15994]
**Feature?**  
*Type*: CopyFilesOverSSH cleanTargetFolder does not delete hidden files

**Enter Task Name**: CopyFilesOverSSHV0

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CopyFilesOverSSHV0

## Environment
- Server
- Agent Private: 
    
## Issue Description

When using the CopyFilesOverSSH task with the cleanTargetFolder, the hidden files in the target folder are not clean on linux.
On linux the task performs the command 'rm -rf *' which does delete regular files but not hidden ones starting with '.'.
In my opinion or the file pattern must be adapted to include hidden files, or this is done on purpose and must be documented.

Br.

**Comment by DenisRumyantsev** [comment]
Hi @boubou191911, we can not start working on this issue right now, but we will be back as soon as we can.
