### ISSUE TITLE
AzureRMWebAppDeployment and  AzureFunctionApp `appSettings` behaviour

### ISSUE THREAD

**Issue by cosminstirbu** [microsoft/azure-pipelines-tasks#16025]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: `AzureRMWebAppDeployment` and  `AzureFunctionApp`

## Issue Description

It seems both `AzureRMWebAppDeployment` and  `AzureFunctionApp` are appending the key-value pairs passed in to `appSettings` instead of becoming the new "source of truth". Basically this leads to old configuration settings being kept around making the configuration section cluttered.

Is there some sort of flag we could opt in to specify that whatever `appSettings` contains will be reflected in the portal as well and the values that were previously there are removed?

Thank you,
Cosmin

**Comment by cosminstirbu** [comment]
Any news on this?

**Comment by FinVamp1** [comment]
Hi, reviewing this for Azure Functions and will think about this for AzureRMWebAppDeployment as well. Can you confirm if this is the behaviour you would like to see? 

1. The AppSettings section contains a key-value pair like this. "TestValueA:MyValueA".
2. A edit of the pipeline occurs and this section now contains ""TestValueB:MyValueB" only.
3. The portal now shows TestValueA and TestValueB.

The preferred behaviour would be that TestValueA is removed  and only TestValueB is shown in the portal?

Is that a fair summary? 

I think the concern would be is that if we start to remove the app settings then we may break and existing app.

Would your workflow allow for this in code reviews?

**Comment by cosminstirbu** [comment]
Hi,

Your summary is correct, that's the behavior we'd like to see.
Related to your concern about breaking existing apps, I am suggesting introducing some sort of additional parameter that we can use to opt in into this behavior. In our particular case, it wouldn't be breaking even if the new behavior would be enabled by default, not sure for other customers though.

On top of this, we should also account for "special" app settings such as DIAGNOSTICS_AZUREBLOBCONTAINERSASURL or DIAGNOSTICS_AZUREBLOBRETENTIONINDAYS which are set out of the box for App Services by enabling App Service logs. These shouldn't be removed if we don't send them explicitly as part of the `appSettings` parameter.
Not sure anything in particular needs to be done for these special type app settings though, I would expect this behavior to be baked in already.

**Comment by cosminstirbu** [comment]
I have explored this area a little more in details, and based on my research currently the only way to fully replace all settings is [Web Apps - Update Application Settings ](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/update-application-settings).

The Powershell cmdlet and az cli do merge & add.

The full replace done by the REST API call, removes even "built-in" app settings, such as `AzureWebJobsStorage`, `DIAGNOSTICS_AZUREBLOBCONTAINERSASURL`, `DIAGNOSTICS_AZUREBLOBRETENTIONINDAYS`, etc.

Given all this, I'd suggest that the two tasks `AzureRMWebAppDeployment` and `AzureFunctionApp` should also take as parameters a list of settings that shouldn't be removed. This means that under the hood, if the tasks use the REST API, it should first read existing settings, copy the ones that shouldn't be removed to the new settings, and then use the REST API to do a full replace that includes the "built-in" settings passed in the tasks.

I'm fully aware that this is a lot of complexity, so I can understand if the effort doesn't worth it.

Ideally, if the "built-in" settings would be independent of the settings required by the application logic then this wouldn't be an issue.

The main goal here is to avoid having the application settings be cluttered with settings that are not being used any longer.

**Comment by FinVamp1** [comment]
Hello, @cosminstirbu I think there is high risk for this introducing a break change to apps and also adding a level of complexity to the task that would be hard to maintain. In the future we hope to be able to move deployment settings into a separate config store from the App Settings to make this easier. For now I am going to close this as not planned.
