### ISSUE TITLE
Azure Powershell Automation Runbook Error: Select-AzureRMSubscription: Index was out of range. Must be non-negative and less than the size of the collection

### ISSUE THREAD

**Issue by riiikawang** [microsoft/azure-pipelines-tasks#16030]
Question, Bug, or Feature?
Type: Bug

## Environment

Azure China  - Azure Automation Powershell Runbook

## Issue Description

Below error happened randomly when executing azure powershell runbook to start virtual machines:
![image](https://user-images.githubusercontent.com/77219080/158551433-b5d3e624-7f39-4913-873e-58eb7cb8ab18.png)

Runbook Content:
$cred = Get-Automationpscredential -Name xxx
Add-AzureRmAccount -Credential $cred -EnvironmentName AzureChinaCloud
Select-AzureRmSubscription -SubscriptionName "xxx"
Start-AzureRmVM -ResourceGroupName rgname -Name vmname

The same runbook worked on multiple VMs, but randomly some VMs couldn't be started although runbooks are completed successfully. 

## Troubleshooting
1. Confirmed no issues with automation runbook itself.
2. Checked powershell module, found the version of multiple AzureRM modules is quite old:
![image](https://user-images.githubusercontent.com/77219080/158552699-5c2b370e-94b2-4655-8ee2-2885fc0bb337.png)

Would like to check if the random error is related to old Powershell module, pls help, thanks.

**Comment by anatolybolshakov** [comment]
Hi @riiikawang this repo is mostly for pipelines tasks, although this question is more about Azure - I would suggest to reach out to the Azure support using options described here - https://azure.microsoft.com/en-us/support/options/

**Comment by riiikawang** [comment]
@anatolybolshakov thanks. As Azure Automation runs very well I guess no any issues with Azure service, the error details directly point to a powershell error, so I suppose even without any Azure service the powershell commmands would be failed as well randomly.

**Comment by anatolybolshakov** [comment]
@riiikawang as I understand Azure Automation Powershell Runbook is not related to the [Azure DevOps](https://azure.microsoft.com/en-us/services/devops/), so the support options above should help you to reach out to the right teams to take a look 😃

**Comment by anatolybolshakov** [comment]
@riiikawang please ping if you have any other questions.
