### ISSUE TITLE
PowerShellV2 ErrorActionPreference

### ISSUE THREAD

**Issue by awdavies90** [microsoft/azure-pipelines-tasks#16048]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShellV2 

## Environment
- Server - Azure Devops Server
    - Version: Version 17.143.28621.4

## Issue Description

The PowerShellV2 task has an option for setting the ErrorActionPreference of a script. This is great but I've noticed that the task adds the `$ErrorActionPreference = '{selectedOption}'` at the beginning of your chosen script or inline script, regardless of whether the script already contains a line where the `$ErrorActionPreference` is set.

If the $ErrorActionPreference is explicitly being set in a script then it should be honoured and the PSV2 task should not prefix the script itself.

I've also noticed that if a script contains a param block and is used inline, the error action preference line is added above the `param` block which causes the script to fail. With this in mind it would be good to either have the option to not specify an ErrorActionPreference within the task or for the preference line to only be added if the script does not contain one already.

P.S. I'm aware that if the above change(s) are made, as I'm currently using on-prem AzDO I'll still have the problem. That's fine, I just wanted to bring it to your attention.

**Comment by golubev-ivan** [comment]
Hello @awdavies90, I've investigated your issue. You can set ErrorActionPreference as Default in the task settings and this line will not be added to the ps script.

**Comment by awdavies90** [comment]
![image](https://user-images.githubusercontent.com/21106005/160619388-b195dd65-6918-4e24-bcc5-e2fb6494c3f8.png)
Is this something that can only be done through yaml? There's doesn't seem to be an option for it in the classic view (E.g. A task group).

**Comment by golubev-ivan** [comment]
Most likely, your version of Azure DevOps Server doesn't include the fix for this task. I think in future versions of the ADO server this feature will be added. Related PR with the fix: https://github.com/microsoft/azure-pipelines-tasks/pull/15069

**Comment by anatolybolshakov** [comment]
Hi @awdavies90 please ping if you have any questions. You can probably build task by yourself and upload it via [tfx-cli](https://www.npmjs.com/package/tfx-cli ) to your local server, although this is not supported. These task changes will be released with one of the next releases of on-prem server.

**Comment by DenisRumyantsev** [comment]
Hi @awdavies90, let me close this issue for now. Feel free to reopen it if you have any additional questions about the PowerShell task. For now, you can upload it to your local server via tfx-cli, as was mentioned
