### ISSUE TITLE
[GoTool] Make the Go download URL configurable

### ISSUE THREAD

**Issue by dagood** [microsoft/azure-pipelines-tasks#16045]
## Required Information

*Type*: Feature
**Task Name**: GoTool

## Environment
- Azure Pipelines, any version used in Microsoft internal builds
- Agent - any

## Issue Description

My team is building Go for internal use at Microsoft, but we don't have a good way for people who use the `GoTool@0` task to switch over from the official build of Go to our build of Go. I think all we need is a way to configure the base URL rather than hard coding it:

https://github.com/microsoft/azure-pipelines-tasks/blob/7893ce00533588b4413dc2f194ba2eade69340d9/Tasks/GoToolV0/gotool.ts#L96-L98

URLs for our builds will be something like `https://aka.ms/golang/release/%s`.

We don't want to change the *default* base URL: Azure Pipelines users outside Microsoft should continue to get the official Go binaries. (Our build of Go is only intended for use within Microsoft to meet supply chain and FIPS requirements. For more info, the Microsoft build of Go is maintained at https://github.com/microsoft/go.)

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by dagood** [comment]
Commenting to prevent closure as stale. Issue is awaiting a response from repo maintainers.

**Comment by dagood** [comment]
Commenting to prevent closure as stale. Issue is awaiting a response from repo maintainers.

**Comment by shueybubbles** [comment]
I think it will also need a modification to the cache logic to use the source URL in the key
