### ISSUE TITLE
unable to create pdf from multiple html files in python inside ADO pipeline.

### ISSUE THREAD

**Issue by aryans31** [microsoft/azure-pipelines-tasks#16064]
[](https://sap.stackenterprise.co/images/a/ed0f4bfe-9b30-40fe-ab81-ef57816f9384.png)unable to create pdf from multiple html files in python inside ADO pipeline, but if I pass one single file then the report is being generated.

inside bash:
```
sudo apt-get update --fix-missing
sudo apt-get install -y wkhtmltopdf
```

Python script:
```
frontPage =  os.path.join(fileName, 'frontPage.html')
index = os.path.join(fileName, 'index.html')
```

```
// providing 1 file
pdfkit.from_file([fileName],"report.pdf") //works perfectly fine

// providing multiple files
pdfkit.from_file([frontPage, index],"report1.pdf") //showing error 
```

error:
but for single HTML file, report is being created in artifacts.and the path of the HTML files are correct.

![image](https://user-images.githubusercontent.com/58971587/159662843-5fe6a35e-4d17-4c72-83ed-6d73fbdb0fd4.png)

**Comment by golubev-ivan** [comment]
Hello @aryans31, I have investigated your issue. The problem is related to the incorrect installation of the `wkhtmltox` package. To correctly install this package, you should use the following commands:
```
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
sudo apt install ./wkhtmltox_0.12.6-1.bionic_amd64.deb
```
*Instead of the above package version, you can use the one you need from https://wkhtmltopdf.org/downloads.html

**Comment by aryans31** [comment]
> wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
> sudo apt install ./wkhtmltox_0.12.6-1.bionic_amd64.deb

ThankYou @golubev-ivan :)
