### ISSUE TITLE
DownloadBuildArtifacts' latestFromBranch uses the latest completed by time, not by branch history 

### ISSUE THREAD

**Issue by luiszun** [microsoft/azure-pipelines-tasks#16063]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadBuildArtifactsV0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Internal

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:  Windows_NT 10.0.17763, Agent 2.200.2

## Issue Description

DownloadBuildArtifacts' latestFromBranch fetches the latest build artifact that finished successfully by time, even though there are newer (branch history-wise) finished, successful jobs.

Essentially: I can complete a PR now, which triggers a CI run that will publish artifacts build upon completion. Now, a bunch of PRs may complete and trigger their own CI jobs, and they will finish and publish. Then my first PR completes and publishes, when using DownloadBuildArtifacts and latestFromBranch it will download the bits from the first CI run, only because it was the last to finish. There's no explicit documentation to whether latestFromBranch refers to latest in finish time, or latest in branch' history, but the name implies it refers to latest in branch's history.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by luiszun** [comment]
```
	export enum BuildQueryOrder {
	    /**
	     * Order by finish time ascending.
	     */
	    FinishTimeAscending = 2,
	    /**
	     * Order by finish time descending.
	     */
	    FinishTimeDescending = 3,
	}
```

The problem lies there. Perhaps there are other options for getBuilds. However I only see interfaces, I assume the rest is  not open source, but maybe there are other values for BuildQueryOrder?

**Comment by b3go** [comment]
just ran into this issue. We are downloading and republishing some artifacts to save build time if nothing has changed. Unfortunately the latest by completition time is picked up for all subsequent pipeline runs which is older branch/code wise. Any Idea how to come around this issue?

**Comment by luiszun** [comment]
I worked around by passing a versioning variable and keeping track of versioning info via published packages. But it is completely ridiculous and incredible that this has been open and known for over a year
