### ISSUE TITLE
# Batch script
# Run a Windows command or batch script and optionally allow it to change the environment
- task: BatchScript@1
  inputs:
    filename: 
    #arguments: # Optional
    #modifyEnvironment: False # Optional
    #workingFolder: # Optional
    #failOnStandardError: false # Optional

### ISSUE THREAD

**Issue by mahdi21174** [microsoft/azure-pipelines-tasks#16073]

**Comment by mahdi21174** [comment]
# Batch script
# Run a Windows command or batch script and optionally allow it to change the environment
- task: BatchScript@1
  inputs:
    filename: 
    #arguments: # Optional
    #modifyEnvironment: False # Optional
    #workingFolder: # Optional
    #failOnStandardError: false # Optional

**Comment by max-zaytsev** [comment]
Hi @mahdi21174, Could you please provide more details about your issue?

**Comment by anatolybolshakov** [comment]
Hi @mahdi21174 do you have any updates?

**Comment by max-zaytsev** [comment]
Closing this. @mahdi21174 let us know if it's still relevant for you.
