### ISSUE TITLE
Xcode 13.3 

### ISSUE THREAD

**Issue by 3a4oT** [microsoft/azure-pipelines-tasks#16080]
Hello is there ETA for Xcode 13.3 (and I guess macOS 12 Monterey)?

**Comment by neoswallow** [comment]
Fill out the form for the private beta test on the link at https://github.com/actions/virtual-environments/issues/3649#issuecomment-1087979762.
Public ETA is way off.
No ETA is given for private beta yet either but shouldn't be too long as it's started for GitHub Actions.
