### ISSUE TITLE
PowerShellOnTargetMachines@3 writes ugly amount of machinename lines

### ISSUE THREAD

**Issue by RicardoLans** [microsoft/azure-pipelines-tasks#16086]
Required Information
---
Question, Bug, or Feature?
Question/Feature

Enter Task Name:
PowerShellOnTargetMachines@3

Environment
---
Azure Pipelines

Issue Description
---
https://github.com/microsoft/azure-pipelines-tasks/blob/438eb1ed55d1f6b481eb5c20dcf516fb91ecebcc/Tasks/Common/RemoteDeployer/JobHelper.ps1#L123

Based on above link provided, the execution of remote scripts is writing a message on output window every 5 seconds just saying computerName. 
For short running scripts this is fine, but we use some scripts taking 5-30min to finish, we seeing around 60-360 Write-Host lines that are exactly the same.
Is there any possibility you change linked Write-Host line to Write-Verbose or something.
It makes no sense at all to show that information during script execution.
If I want to know such information I would set the task/release to show debug/verbose information.

Steps to reproduce
---
Make inline script that runs for like 5min before it finishes.

**Comment by RicardoLans** [comment]
Really? Nobody even cares to look at this?

**Comment by MattJeanes** [comment]
This is still valid

**Comment by MattJeanes** [comment]
Still valid :)

**Comment by RicardoLans** [comment]
Still an issue
