### ISSUE TITLE
PublishPipelineArtifact fails if artifact contains a symbolic link

### ISSUE THREAD

**Issue by atindall9041** [microsoft/azure-pipelines-tasks#16137]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: Bug

**Enter Task Name**: PublishPipelineArtifactV0

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishPipelineArtifactV0

## Environment
- Server: Azure Pipelines

- Agent - Hosted
- Agent queue name: OneBranch Pipelines   

## Issue Description

Hi, I'm seeing an error when trying to run the PublishPipelineArtifact task (version 0.141.0) on an artifact which contains a symlink.

Here's the error message:

##[error]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
##[debug]Processed: ##vso[task.logissue type=error;]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, Boolean shouldPreserveSymbolicLink, Boolean shouldPreservePermissionValue, PageItem pageItem, CancellationToken cancellationToken)

I think this is a duplicate of https://developercommunity.visualstudio.com/t/PublishPipelineArtifact1----errorUn/1102572?space=21&q=symlink&viewtype=all, but that issue says the problem was fixed in agent version 2.160.0, and we're running agent version 2.202.0. We're using Linux agents.

Do you know if this issue can be fixed, or if there is a workaround?

### Task logs

[publishartifacts-tasklog.txt](https://github.com/microsoft/azure-pipelines-tasks/files/8474000/publishartifacts-tasklog.txt)

### Error logs

##[error]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
##[debug]Processed: ##vso[task.logissue type=error;]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, Boolean shouldPreserveSymbolicLink, Boolean shouldPreservePermissionValue, PageItem pageItem, CancellationToken cancellationToken)

**Comment by atindall9041** [comment]
Hi, this problem is still affecting us. Do you have any updates?
Thanks!

**Comment by annatindall** [comment]
We've worked around this in our repository, but the bug is still there.
