### ISSUE TITLE
DownloadPackage "undefined" when downloading .tar since 1.202.0

### ISSUE THREAD

**Issue by kaijday** [microsoft/azure-pipelines-tasks#16144]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: **DownloadPackage**

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? **Azure Pipelines**
OpenGI Digital ebroker-loveyourmiles 193

- Agent - Hosted or Private: **Private / Linux (CentOS 7)**

## Issue Description

**Since Azure Pipelines started using DownloadPackage 1.202.0, download a .tar from Azure Artifacts results in a directory with "undefined" and not the expected contents. This was previous working fine on version 1.198.0**

File not found. Read files with wildcard
Processing: 1 files.
PROCESS: ./loveyourmiles_conf-20220413.4.tar
Unpacking TAR archive
tar: This does not look like a tar archive
tar: gradle.properties: Not found in archive
tar: deploy.gradle: Not found in archive
tar: Exiting with failure status due to previous errors

Task:
**- task: DownloadPackage@1
  displayName: 'TEST FILE Download'
  inputs:
    packageType: maven
    feed: '57a8bb14-3f97-4cf4-a721-220f6118569b'
    definition: 'opengi.ebroker.opengitraining:opengitraining_conf'
    version: '20220413.12'
    files: '*.tar'
    downloadPath: '$(System.ArtifactsDirectory)'**

### Task logs

Attached
[logs_1978.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8481443/logs_1978.zip

**Comment by jpolmanstater** [comment]
Got the same error. Managed to get the 1.198 version from another server. Using that one in our private marketplace.

**Comment by mrhcongc** [comment]
Also getting this error for all files downloaded. Their file size are all 9 and contents are "undefined".

**Comment by rajeevs84** [comment]
Same problem. All artifacts are size 9 and "undefined"

**Comment by niklev** [comment]
same problem!

**Comment by jiaw37** [comment]
As a temporary workaround for build pipelines you can lock the version of a task with ` - task: DownloadPackage@1.198.0`

**Comment by SahithKesireddy9** [comment]
Microsoft Azure DevOps team released 1.202.4 (Download Package) version to remediate this issue.

**Comment by rtsketo** [comment]
Did you guys find a solution to this?

**Comment by jpolmanstater** [comment]
nope, still using the 1.198 version
