### ISSUE TITLE
console.log might reveal secrets 

### ISSUE THREAD

**Issue by phelje** [microsoft/azure-pipelines-tasks#16153]
https://github.com/microsoft/azure-pipelines-tasks/blob/334051d1e2cc122732629fe95b8be2ab3c7b64f7/Tasks/AzurePowerShellV5/azurepowershell.ts#L92

Should only log if debug is enabled, when using this PS task in Linux environment it reveals all the parameters used, if any of the parameters is a secret from another step it gets in the log... not god!

**Comment by AndreyIvanov42** [comment]
Hi @phelje  thanks for reporting! We'll look what we can do.
