### ISSUE TITLE
HelmDeploy@0 Set values doesn't work with lists/arrays

### ISSUE THREAD

**Issue by perosb** [microsoft/azure-pipelines-tasks#16151]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy  

## Environment
Azure Pipelines with hosted agents. Tried both windows-latest and ubuntu-latest

## Issue Description

When using the HelmDeploy task, you _must_ have quotes around lists/arrays or it will be treated as a single value.
The task seems to remove quotes around values.

![image](https://user-images.githubusercontent.com/982752/163332031-174a10d3-7e72-4f3e-833b-d8b63fd3bc59.png)

```
##[debug]exec tool: C:\hostedtoolcache\windows\helm\3.8.2\x64\windows-amd64\helm.exe
##[debug]arguments:
##[debug]   upgrade
##[debug]   --debug
##[debug]   --namespace
##[debug]   ingress-basic
##[debug]   --install
##[debug]   --values
##[debug]   D:\a\1\s\solution\k8s\specs\ingress-nginx\internal-ingress.yaml
##[debug]   --set
##[debug]   controller.service.loadBalancerSourceRanges={173\.245\.48\.0/20\,103\.21\.244\.0/22}
##[debug]   --wait
##[debug]   --dry-run
##[debug]   ingress-nginx
##[debug]   ingress-nginx/ingress-nginx
C:\hostedtoolcache\windows\helm\3.8.2\x64\windows-amd64\helm.exe upgrade --debug --namespace ingress-basic --install --values D:\a\1\s\solution\k8s\specs\ingress-nginx\internal-ingress.yaml --set controller.service.loadBalancerSourceRanges={173\.245\.48\.0/20\,103\.21\.244\.0/22} --wait --dry-run ingress-nginx ingress-nginx/ingress-nginx

...... snippet...
  service:
    internal:
    loadBalancerSourceRanges:
    - 173.245.48.0/20,103.21.244.0/22
```

The expected result would be
```
    loadBalancerSourceRanges:
    - 173.245.48.0/20
    - 103.21.244.0/22
```

This can be done by quoting the {}:
```
--set controller.service.loadBalancerSourceRanges="{173\.245\.48\.0/20\,103\.21\.244\.0/22}"
```

Another test case that works locally but not within the pipeline/task, even without quotes:
```
/opt/hostedtoolcache/helm/3.5.4/x64/linux-amd64/helm upgrade --debug --namespace ingress-basic --install --values /home/vsts/work/1/s/solution/k8s/specs/ingress-nginx/internal-ingress.yaml --set controller.service.loadBalancerSourceRanges={this\,works\,fine\,locally} --wait --dry-run ingress-nginx ingress-nginx/ingress-nginx

    internal:
    loadBalancerSourceRanges:
    - this,works,fine,locally
```

Locally:
```
09:37 $ helm upgrade --debug --namespace ingress-basic --install --values internal-ingress.yaml --set controller.service.loadBalancerSourceRanges={this\,works\,fine\,locally} --wait --dry-run ingress-nginx ingress-nginx/ingress-nginx

    internal:
    loadBalancerSourceRanges:
    - this
    - works
    - fine
    - locally
```

**Comment by sergeyzwezdin** [comment]
Anyone take care on this?

**Comment by grigi** [comment]
Similar if trying to use the new `--set-json` parameter.
In a regular shell you'd pass `--set-json 'app.foo=[{"name":"one","path":"test1"},{"name":"two","path":"test2"}]'` and it would work.
I tried all kinds of escaping, but could not get it to work.
It appears that every parameter is split by string and passed as a whole argument, so eveyhthing is implicitly double-quoted. Also, double quotes are mangled in some way as even using `\"` would give me weird results.
e.g.:
`--set-json app.foo=[{\"name\":\"one\"}]`
would give me an error that `[{\name":"one"}]` is invalid json.
