### ISSUE TITLE
Intermittent ModuleNotFoundDuringParse error when using Send-MailKitMessage within a PowerShell script in our pipelines

### ISSUE THREAD

**Issue by edgariscoding** [microsoft/azure-pipelines-tasks#16163]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell  

list here (V# not needed):  PowerShellV2
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: CiraConnect, CiraConnect, Release Definition Id 6

- Agent - Hosted or Private: Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016 Datacenter, Agent Version 2.186.1

## Issue Description

Pipeline task name: Run Changeling Script

Every so often, one of our tasks fails for no apparent reason. Nothing has changed in the configuration for the pipeline, for the task, or for our source code. Yet every few weeks a PowerShell script we use to send an email will throw an exception and fail over and over again. Then suddenly a day or so later, it will start working again and will continue working for a few weeks until it fails again.

In this scenario, the error is:

![Screen Shot 2022-04-18 at 12 22 55 PM](https://user-images.githubusercontent.com/12093243/163847077-5c4668e3-0e31-411c-a988-1b94d2f041a7.png)

Again, this has been working fine for weeks. It just started giving this error this morning.

### Task logs

[tasklog_23_sanitized.log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8507107/tasklog_23_sanitized.log.zip)

### Error logs

```
2022-04-18T17:02:20.1520323Z At E:\azagent\A1\_work\r1\a\script.ps1:1 char:1
2022-04-18T17:02:20.1521067Z + using module Send-MailKitMessage
2022-04-18T17:02:20.1521618Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-04-18T17:02:20.1522143Z Could not find the module 'Send-MailKitMessage'.
2022-04-18T17:02:20.1522878Z     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx 
2022-04-18T17:02:20.1523460Z    ception
2022-04-18T17:02:20.1524011Z     + FullyQualifiedErrorId : ModuleNotFoundDuringParse
```

**Comment by SvetlanaMaliugina** [comment]
Hi @edgariscoding! Thanks for reporting! Could you please provide us minimal reproducible steps (for example: some sample project)?

**Comment by edgariscoding** [comment]
@SvetlanaMaliugina I ended up solving this issue, or I guess getting around it, by using an Azure hosted agent to run the script. I was originally running it on a self hosted agent and it seems the issue was due to some missing packages and because Send-MailKitMessage required powershell 7
