### ISSUE TITLE
Question: Why does DotNetCoreInstaller@1 marked as deprecated?

### ISSUE THREAD

**Issue by ddprince-yaksa** [microsoft/azure-pipelines-tasks#16175]
Hi, 

I was building a pipeline when VS Code brought to my attention that the task DotNetCoreInstaller@1 is marked as deprecated. I then tried to look for alternatives or suggestions, but even under the documentation, I can't find any information regarding its deprecation: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops.

I feel like it's a mistake, because I'm even currently seeing pull requests for the second version of the same tool, which seems not be released yet. 

Can anyone explain? 

Thank you,
David

**Comment by VivekRajagopal** [comment]
Hey David I came across the same error in VS Code. Switched to [`UseDotNet@2`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) and no error :)

**Comment by ddprince-yaksa** [comment]
Oh, I should have thought it was as simple as that eheh! Thanks!
