### ISSUE TITLE
Cache@2 after cache restore `dotnet build` is not seeing restored packages

### ISSUE THREAD

**Issue by msmolka** [microsoft/azure-pipelines-tasks#16194]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug/Question

**Enter Task Name**: Cache@2

## Environment
- Server - Azure Pipelines

## Issue Description
Cache is properly set and restored. Cache configured based on:
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops#cache-nuget-packages

```
Entry found at fingerprint: `nuget|"Windows_NT"|HeFtMIuVZwr4C8Cctefu8cfghtWrl9oGb15Mv7b3AsU=`
```

Then `dotnet build` is run and task is failing with private feed resources not found

```
error NU1101: Unable to find package AppConfig. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

**Comment by johnterickson** [comment]
Add some directory listing steps to your workflow to see if those files are getting restored.

**Comment by msmolka** [comment]
There is something wrong with documentation or with paths. I'm using windows machine as build.
when I'm using this link:
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops#cache-nuget-packages

`NUGET_PACKAGES: ''`

The empty path is not working.

when I'm using this example:
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget

`NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages`

it is finally working. But I had to invalidate cache created by wrong config.
A bit confusing.
