### ISSUE TITLE
Azure Pipelines Archive Task With Missing File Produces Vague Error

### ISSUE THREAD

**Issue by TanayParikh** [microsoft/azure-pipelines-tasks#16202]
I think I have an update on this bug. The ENOENT occurred in a feature branch when the file/folder did not exist. In which case, this is a valid error.

My only suggestion would be to possibly change the "spawnSync" / ENOENT error message so that it mentions "File not found" or "folder not found".

_Originally posted by @tinytone in https://github.com/microsoft/azure-pipelines-tasks/issues/8418#issuecomment-634573156_

**Comment by Kozlov-Igor** [comment]
Hi @TanayParikh  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by TanayParikh** [comment]
Refreshing
