### ISSUE TITLE
VSTS Agents self hosted on a Mac

### ISSUE THREAD

**Issue by dmccolloughOneGas** [microsoft/azure-pipelines-tasks#16273]
Question, I would like to run my self hosted Mac build agents as a daemon on my Mac mini so that I don't have to login to the Mac using the service account.

I have them running as launchd services, they work perfectly if I login to the Mac mini using our service account. This presents a problem if the server reboots for something, we are mostly working from home, so if it reboots and the build agents don't start. Somebody has to drive into the office and login and get them running.

Yes I know we can configure the mini to automatically login, however our security team would prefer to not do this.

So is it possible to get the build agent running as a launchd service to run as a daemon ?
If so, any specific documentation that somebody could provide would be greatly appreciated.

**Comment by Kozlov-Igor** [comment]
Hi @dmccolloughOneGas! This repo is related to Azure Pipeline Tasks, if you want to ask a question about agent please create issue on https://github.com/microsoft/azure-pipelines-agent.  But check it out first. Perhaps this documentation will be useful in your case -  https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#automatic-login-and-lock.
