### ISSUE TITLE
Universal Package does not create new package if a similar name already exists

### ISSUE THREAD

**Issue by bertschronja** [microsoft/azure-pipelines-tasks#16326]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Universal packages

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/bosch-ciam/skid/_build/results?buildId=196263&view=logs&j=b3812022-0a90-52bf-5e32-d6630aef4c89&t=eb1f1b6f-37ca-50ff-46df-ab0b0d3cff20

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: 439

## Issue Description

[Include task name(s), screenshots and any other relevant details]

![image](https://user-images.githubusercontent.com/50523149/168781613-956fbc38-73e7-44a0-ac60-d823165e6c52.png)

The task is not able to upload a package to the given feed. As stated here the issue might be that a package with a similar name already exists: https://github.com/microsoft/azure-pipelines-tasks/issues/13983

Name of existing package: 1.0.0-ciamauthn-xxx
Name of package to be uploaded: 1.0.0

### Task logs

Downloading: https://08wvsblobprodsu6weus73.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.236.zip?sv=2019-07-07&sr=b&sig=Isa3jrUguKGKouWwDuoGndT87Lc7gXlbxp1%2FF1DjQ2g%3D&spr=https&se=2022-05-17T10%3A30%3A10Z&sp=r&P1=1652783110&P2=11&P3=2&P4=WcY9fEaKFdedgIVj7pz%2fOKnDkGm3xb61gNrxAMwMCDs%3d
Caching tool: ArtifactTool 0.2.236 x64
##[error]Error: Failed to get package versions
##[error]Packages failed to publish

## Troubleshooting
[log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/8707172/log.txt)

### Error logs

Downloading: https://08wvsblobprodsu6weus73.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.236.zip?sv=2019-07-07&sr=b&sig=Isa3jrUguKGKouWwDuoGndT87Lc7gXlbxp1%2FF1DjQ2g%3D&spr=https&se=2022-05-17T10%3A30%3A10Z&sp=r&P1=1652783110&P2=11&P3=2&P4=WcY9fEaKFdedgIVj7pz%2fOKnDkGm3xb61gNrxAMwMCDs%3d
Caching tool: ArtifactTool 0.2.236 x64
##[error]Error: Failed to get package versions
##[error]Packages failed to publish

**Comment by Henning-R** [comment]
This issue also exists in Found tool in cache: artifacttool 0.2.239 x64.

**Comment by bertsch-ronja-office** [comment]
This issue is still there.

**Comment by Yatoom** [comment]
I just had the same issue.

There was a `demo_config` in the artifact feed. Then I tried to publish a new artifact called `config` and the error (`Failed to get package versions`) kept coming up until I changed the artifact name to `main_config`.

I was using `ArtifactTool 0.2.266 x64`.
