### ISSUE TITLE
No matching tcm test case result found issue.

### ISSUE THREAD

**Issue by jongrey** [microsoft/azure-pipelines-tasks#16341]
Agent: Virtual machine scale set INF-TA-VMSS2
Task: Visual Studio Test
Version: 2.203.0
Test Platform: Visual Studio 2019

Issue: Since last week, all new tests and tests with updated namespace/class name/test name exceeding 150 symbols cause a warning message to be posted in the test run log, and such tests are not included in the test result dashboard (marked as "Others" but not displayed when "Others" filter is applied). Existing tests with complete names exceeding 150 symbols are run and reported successfully. It seems that the issue is triggered after re-associating the test to the Azure DevOps work item.

Example of the warning message: 
##[warning]TcmTestResultPublisher.ConvertResults : No matching tcm test case result found for test case result given by agent to publisher. Skipping test case : CD.Solution.Tests.Legacy.NewScenarios.Messaging.Import.EmailAddressNotValidatedBeforeImport.Test_Import_ImportContactsFromExcelFile_EmailsAreNotvalidated_46917

![image](https://user-images.githubusercontent.com/5725128/169277027-188eb6d0-93ab-4aa5-959b-7273d9ef7d11.png)
![image](https://user-images.githubusercontent.com/5725128/169277821-f0d46937-9a63-4aa6-9e72-c1908575e758.png)

**Comment by robmaas** [comment]
Yes, having the same issue in `windows-latest` in a `VSTest@2` task.

**Comment by daweedz** [comment]
We have had the same issue using v17.2 (latest stable)

**Comment by Nidolai** [comment]
Experiencing the same issue using v17.2.0.

**Comment by daweedz** [comment]
We tried to use 17.1, 17.0, 16.11.0 as explicit versions to try if that would not show those warnings anymore in our pipelines but to no avail :(

**Comment by jongrey** [comment]
It seems that the issue is reproduced only for tasks with "Test selection type" = Test Assembly, and "Test filter criteria" = Test Category.

![image](https://user-images.githubusercontent.com/5725128/169521787-50dc2074-ba6e-4bee-8284-7dae08e3e892.png)

When "Test selection type" = Test Plan, or "Test filter criteria" = Test Name, the issue is not reproduced.

**Comment by daweedz** [comment]
> It seems that the issue is reproduced only for tasks with "Test selection type" = Test Assembly, and "Test filter criteria" = Test Category.
> 
> ![image](https://user-images.githubusercontent.com/5725128/169521787-50dc2074-ba6e-4bee-8284-7dae08e3e892.png)
> 
> When "Test selection type" = Test Plan, or "Test filter criteria" = Test Name, the issue is not reproduced.

Interesting since that is exactly what we use as well.

**Comment by Krishnajbang** [comment]
Facing this issue with newly added tests only. Older tests run fine.

**Comment by daweedz** [comment]
Entered this ticket as well:
https://developercommunity.visualstudio.com/t/TcmTestResultPublisherConvertResults-:/10050168?space=21&entry=problem

**Comment by jongrey** [comment]
This issue has been fixed (see the above link).
