### ISSUE TITLE
Publish Test Results task doesnt upload attachments from Junit xml file

### ISSUE THREAD

**Issue by puagarwa** [microsoft/azure-pipelines-tasks#16349]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Publish Test Results task

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: NA

- Agent - Hosted or Private: Hosted 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Publish Test Results Task doesnt support attachments like image, video available in junit xml file, instead it just upload Standard_Console_Output.log which shows the name of image file.
[[ATTACHMENT|..\test-results\todo-persistence-Persistence-should-persist-its-data-firefox-on-ubuntu\test-failed-1.png]]

xml file content which is acceptable in other CI like gitlab and jenkins, hence its a feature ask.
<system-out>

[[ATTACHMENT|..\test-results\todo-persistence-Persistence-should-persist-its-data-chromium-on-ubuntu\test-failed-1.png]]

</system-out>  

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by puagarwa** [comment]
Not really, no traction.

**Comment by chris-strudel** [comment]
This issue seriously needs to be reopened.

**Comment by rra-topdev** [comment]
This is still an issue today.
