### ISSUE TITLE
AzurePowerShellV5 task - Error: "ForEach-Object: Cannot bind argument to parameter 'Path' because it is an empty string."

### ISSUE THREAD

**Issue by nil-ventx** [microsoft/azure-pipelines-tasks#16353]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell

## Environment

We are using a self-hosted pipeline agent VM in Azure.
The OS is Linux (ubuntu 20.04) with the agent version 2.202.1

## Issue Description

I can not run AzurePowerShell tasks with the pipeline agent VM. It will fail each time with the provided error message. I have installed PowerShell (V. 7.2.4) and the `Az` PowerShell module (V 7.5.0). The path of the installed `Az` module is `/usr/local/share/powershell/Modules/Az/7.5.0/Az.psd1`. The pipeline will also fail if I use a totally different script or even inline code for the AzurePowerShell task. So it seems that the error isn't related to the executed PowerShell script. Unfortunately the logs don't give me any useful information where exactly the error is happening. I have debugged this error for hours but couldn't find any fix or useful information on the internet. Could you help me with that?

### Task logs

[Log_AzurePowerShellTask.txt](https://github.com/microsoft/azure-pipelines-tasks/files/8756768/Log_AzurePowerShellTask.txt)

### Error logs

ForEach-Object: Cannot bind argument to parameter 'Path' because it is an empty string.
##[debug]Exit code 1 
received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed;]PowerShell exited with code '1'.

**Comment by nil-ventx** [comment]
The agent was running as root user. This caused the problem.
Fix: Run the agent as the agent user. The problem will be resolved.

**Comment by eltimmo** [comment]
I started having this issue as well, you can install the service as a user like this

[DevOps agent install](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#install)

```sudo ./svc.sh install [username]```
