### ISSUE TITLE
PublishTestResults@2 does not process all nunit tests results

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/azure-pipelines-tasks#16365]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `PublishTestResults@2`

## Environment    
Azure pipelines: https://dev.azure.com/uno-platform/Uno%20Platform/_build?definitionId=5
Agent: **Hosted**

## Issue Description

Given an nunit results file, the uploaded tests and visible in the test results explorer fail to include some tests found in the results file.

Here's the file imported: [TestResult-original.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8773801/TestResult-original.zip)

The test named `AutoSuggestBox_Reason` is present in the XML file, is accounted for in the "tests count" (`TestResults To Publish 661`), but does not appear in the pipeline tests tab (even with passed tests filter checked), nor in the **Published Test Run** (see below for a retained example).

The pipeline is using NUnit 3.12.0.

### Task logs

https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=47390&view=logs&j=c98e01d2-1868-5681-1445-b304c2a1f490&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=65258fd5-25f7-5690-02a1-ca755f8d5692&l=17

Published Test Run : https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=1831678&_a=runCharts

**Comment by msackton** [comment]
We are seeing the same issue. Our Azure Pipelines are in a private team so I'm not sure if pasted links here will be helpful. In our case, we are using our own tool to collect test results from a UI test run and convert it to NUnit3 format. We then have an Azure Pipelines test task that uploads the results. The attached ZIP results file is generated, and contains 187 tests of which 2 are failures. The Azure Test Result shows only 178 tests though:
![image](https://user-images.githubusercontent.com/440782/170357061-47f2295f-08fe-4dac-90e8-759b7ac5b8f1.png)

However the test result publish task shows:

> `2022-05-24T16:45:21.4429677Z ##[section]Starting: Publish Test Results
> 2022-05-24T16:45:21.4526008Z ==============================================================================
> 2022-05-24T16:45:21.4526456Z Task         : Publish Test Results
> 2022-05-24T16:45:21.4526814Z Description  : Publish test results to Azure Pipelines
> 2022-05-24T16:45:21.4527092Z Version      : 2.203.0
> 2022-05-24T16:45:21.4527293Z Author       : Microsoft Corporation
> 2022-05-24T16:45:21.4527590Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results
> 2022-05-24T16:45:21.4527956Z ==============================================================================
> 2022-05-24T16:45:21.6825058Z [command]"C:\Program Files\dotnet\dotnet.exe" --version
> 2022-05-24T16:45:25.9462092Z 5.0.408
> 2022-05-24T16:45:25.9519783Z [command]D:\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.203.0\modules\TestResultsPublisher.exe @D:\_temp\e961f290-db80-11ec-abb9-b73356adae49.txt
> 2022-05-24T16:45:28.0815900Z No build level attachments to publish.
> 2022-05-24T16:45:28.4622745Z Result Attachments will be stored in LogStore
> 2022-05-24T16:45:28.4994377Z Run Attachments will be stored in LogStore
> 2022-05-24T16:45:28.7998971Z Publishing test results to test run '36562'.
> 2022-05-24T16:45:28.8017969Z TestResults To Publish 187, Test run id:36562
> 2022-05-24T16:45:28.8066257Z Test results publishing 187, remaining: 0. Test run id: 36562
> 2022-05-24T16:45:32.4106055Z Published Test Run : https://dev.azure.com/EscherGroup/Riposte%20Core/_TestManagement/Runs?runId=36562&_a=runCharts
> 2022-05-24T16:45:32.6646083Z ##[section]Async Command Start: PublishTestResultsToEvidenceStore
> 2022-05-24T16:45:32.6646562Z ##[section]Async Command End: PublishTestResultsToEvidenceStore
> 2022-05-24T16:45:32.6647516Z ##[section]Finishing: Publish Test Results`

[NunitFile.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8774186/NunitFile.zip)

**Comment by EGTomKies** [comment]
We have hit a similar issue.   In the attached .xml, there are two tests: 

Having set a multi-line message for an alert, the text on each line should be center-aligned.
and
Having set a multi-line message for a confirmation, the text on each line should be center-aligned.

Neither of which appear in the ADO test filter.   

We also noticed, that there are some passed tests missing as well.   If we compare the number at the top of tests results page vs the number of passes that appear if we filter just for passed tests, the numbers don't add up.  

[UITest.Results.xml.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8774221/UITest.Results.xml.zip)

Numerical disparity pictured:

![2022-05-25 16_07_45-](https://user-images.githubusercontent.com/55757738/170358420-e8b5524c-b3be-495a-b618-adf039ca169b.png)

**Comment by msackton** [comment]
Just adding, EGTomKies and I work for the same company.

Here is another example: https://dev.azure.com/EscherGroup/Riposte%20Core/_build/results?buildId=23152&view=results

In this other example, the pipeline is running on a Microsoft hosted agent (windows-2019), and the pipeline is configured to fail on failed tests. This step actually works correctly:

> TestResults To Publish 9168, Test run id:36234
> Test results publishing 1000, remaining: 8168. Test run id: 36234
> Test results publishing 1000, remaining: 7168. Test run id: 36234
> Test results publishing 1000, remaining: 6168. Test run id: 36234
> Test results publishing 1000, remaining: 5168. Test run id: 36234
> Test results publishing 1000, remaining: 4168. Test run id: 36234
> Test results publishing 1000, remaining: 3168. Test run id: 36234
> Test results publishing 1000, remaining: 2168. Test run id: 36234
> Test results publishing 1000, remaining: 1168. Test run id: 36234
> Test results publishing 1000, remaining: 168. Test run id: 36234
> Test results publishing 168, remaining: 0. Test run id: 36234
> Published Test Run : https://dev.azure.com/EscherGroup/Riposte%20Core/_TestManagement/Runs?runId=36234&_a=runCharts
> ##[error]There are one or more test failures detected in result files. Detailed summary of published test results can be viewed in the Tests tab.

However, the actual test run data shows zero failures:
![image](https://user-images.githubusercontent.com/440782/170359681-3da68b96-c841-4b3f-8a64-3b1dcdf77466.png)

**Comment by msackton** [comment]
I did some more investigation this afternoon on this issue, and it doesn't appear to be related to the publish test results task itself. I logged a Azure DevOps issue here: https://developercommunity.visualstudio.com/t/Azure-Dev-Ops-Test-Results-Tab-Does-Not/10053688?space=21

It appears that it depends on the project you are running in and it doesn't recreate in a fresh project, which strongly suggests a service/database layer issue, not a parsing issue.

**Comment by jeromelaban** [comment]
This was fixed.
