### ISSUE TITLE
Docker Compose Default Project Name Parameter Bug

### ISSUE THREAD

**Issue by Dejulia489** [microsoft/azure-pipelines-tasks#16361]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerCompose@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted (Eventually) & Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

DockerCompose@0 projectName parameter default value will only work if the repository name is lowercase with Docker version 2.5.0
```
        {
            "name": "projectName",
            "type": "string",
            "label": "Project Name",
            "defaultValue": "$(Build.Repository.Name)",
            "helpMarkDown": "Project name used for default naming of images and containers."
        }, 
```

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[error]The process 'C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe' failed with exit code 15

**Comment by Dejulia489** [comment]
If you are working in yaml you can pass the following syntax to set the repository name to all lowercase. 

```
steps:
- task: DockerCompose@0
  inputs:
    projectName: ${{ lower(variables['Build.Repository.Name']) }}
```

**Comment by lakeman** [comment]
Yes you can work around this issue in a pipeline. But you shouldn't have to.
Can the default behaviour change to lower case, *and* stripping out other illegal characters?

In my case, no output from docker-compose was even captured in the build log. So it took half a day of debugging to understand the problem.
