### ISSUE TITLE
PowerShell on Target Machines reports error but succeeds

### ISSUE THREAD

**Issue by chvollm** [microsoft/azure-pipelines-tasks#16360]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShellOnTargetMachines

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: Azure DevOps Server 2020

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2019, Agent 2.181.2

## Issue Description

When using Option „-ProxyAccessType NoProxyServer“, the task reports an error but succeeds. 

### Task logs

Will add later.

## Troubleshooting
Without the option the Task fails, adding the option helps but still reports an error although the task succeeds. 

### Error logs

„##[error]The remote session query failed for [machine] with the following error message: The WinRM client cannot process the request. The proxy access type is incorrect. Use one of the proxy access type flags; the flags cannot be combined. Change the invalid proxy access type and try the request again.”

**Comment by bcanturk-eng** [comment]
Hello, any updates on this, does this task actually support proxy?
