### ISSUE TITLE
Azure App Service Deployment from vscode fails with Cannot read properties of undefined (reading 'createClient')

### ISSUE THREAD

**Issue by chartsNgraphs** [microsoft/azure-pipelines-tasks#16408]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    Hosted

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I have a node.js app (react web app) that I have previously done several successful deployments with, up to and including several minutes before I started receiving errors. 
Now, ANY AND ALL deployments fail in about 0.5 - 3 seconds with the error "Cannot read properties of undefined (reading 'createClient')". There are no build logs to view, as the build never even starts. The deployment does not even reach Azure, and will not show in Deployment Center of the target app. 

There is no information, logs, or anything else to indicate what is going wrong. I can build with npm run build without any issues at all. 

### Error logs

There are no logs - the deployment never even reaches Azure. It IMMEDIATELY fails in vscode with the error:
Cannot read properties of undefined (reading 'createClient')
source: Azure Extension

**Comment by jeremiasjaymez** [comment]
As a workaround you can go to to the resource (subscription, App Services, [your app service], rigth click and then click 'deploy to Web app'. That worked for me after having that error.
