### ISSUE TITLE
AzureCLI@2  ERROR: unrecognized arguments: 

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-tasks#16440]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: task: AzureCLI@2 (2.198.0)
 
## Environment
- Server - Azure Pipelines 
- Agent - Hosted (vmImage: ubuntu-latest, agent version: '2.204.0')

## Issue Description

I am attempting to download all contents from a container in Azure storage to the local working directory.
Running the following command produces a strange error. 
Note: Tried with and without quotes different download locations 

 `task: AzureCLI@2
    displayName: 'Azure CLI '
    inputs:
      azureSubscription: 'Azure Datamine'
      scriptLocation: inlineScript
      scriptType: pscore
      inlineScript: |     
        az --version
        az account show
        az storage blob download-batch -d '"$(System.ArtifactsDirectory)/blobfiles"' --pattern * -s '"$(containername)"'  --account-key '"$(accountkey)"' --account-name '"$(accountname)"' `

Error:
The script fails with exit code 1 and seems to echo out the files in my work/source folder

ERROR: unrecognized arguments: Source XXXX.yml YYYY.md

**Comment by vmapetr** [comment]
@rohit-batra could you please take a look?
