### ISSUE TITLE
KubernetesV1 outputs duplicate logs when running Kubectl logs

### ISSUE THREAD

**Issue by Romanx** [microsoft/azure-pipelines-tasks#16474]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesV1

## Environment
- Server - Azure Pipelines
- Agent - Private: Windows_NT

## Issue Description
When running a command the output is always output with a `console.log` prefixed with `commandOutput` when running kubectl log this causes the output to be duplicated since the command outputs results and then they're output from this line below
https://github.com/microsoft/azure-pipelines-tasks/blob/d883a26183ff56b5f43750f0e9a2ceae65ca4e9f/Tasks/KubernetesV1/src/kubernetes.ts#L139-L142

This seems to exist to parse the output so an option to disable any post processing of the command output would be good. It suggests that `outputFormat: ""` in the task definition does this however this happens lower:
https://github.com/microsoft/azure-pipelines-tasks/blob/d883a26183ff56b5f43750f0e9a2ceae65ca4e9f/Tasks/KubernetesV1/src/kubernetes.ts#L151-L154

### Task logs
```
2022-06-20T14:06:59.5701307Z {"@t":"2022-06-20T14:06:50.1015445Z","@m":"" }
2022-06-20T14:06:59.5704398Z commandOutput{"@t":"2022-06-20T13:01:11.7505202Z","@m":""}
2022-06-20T14:06:59.5705844Z {"@t":"2022-06-20T13:01:11.7683022Z","@m":"" }
```

**Comment by strowk** [comment]
Just got this too. Looks pretty wasteful - everything outputs twice, Microsoft why no fix? :)

**Comment by strowk** [comment]
The second place which passes stdout through is this (approximately): 
https://github.com/microsoft/azure-pipelines-task-lib/blob/5f76bee724ad65d0186392fd2407dfd119fa4332/node/toolrunner.ts#L877

> Output will be streamed to the live console.

This is comment on ToolRunner#exec , which appears to be called from here:
https://github.com/microsoft/azure-pipelines-tasks/blob/d883a26183ff56b5f43750f0e9a2ceae65ca4e9f/Tasks/KubernetesV1/src/clusterconnection.ts#L117

This means that line `console.log("commandOutput" + result); ` linked above is essentially unnecessary duplicate.. Could someone reopen this issue and remove that line?
