### ISSUE TITLE
UseDotNetV2 Agent Tools Directory Structure for Non-Internet-Connected Agents

### ISSUE THREAD

**Issue by MDendura** [microsoft/azure-pipelines-tasks#16472]
## Required Information
**Type**: Question
**Task Name**: UseDotNet

## Environment
- Server - TFS on-premise (Azure DevOps Server 2020 Update 1.1)

- Agent - Private (Windows 10.0.17763 x64, Agent v2.181.2) 
    
## Issue Description

I have several non-internet connected Windows Servers for use as build agents and wish to pre-populate the `_tool` directory with version 5 and 6 of the .NET SDK to ensure they can correctly be picked up by any agent trying to run a given build pipeline. The servers cannot be given internet access due to corporate security policy.

Having looked at the code for the `UseDotNet` task here and [`azure-pipelines-tool/tool.ts`](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/tool.ts) I cannot easily figure out what the correct structure should be to ensure the agent views the .NET SDK as being already cached and doesn't attempt to download it from the internet which will fail.

I can see the following structure for NuGet in the `_tool` directory:
```
...\_tool\<version>\<architecture>.complete
...\_tool\<version>\<architecture>\nuget.exe
```

I have tried to replicate it for the .NET 5 SDK (v5.0.408) by downloading the ZIP from the location referred to in the [releases JSON](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json), but have had no success:
```
...\_tool\dotnet\5.0.408\x64.complete
...\_tool\dotnet\5.0.408\x64\dotnet-sdk-5.0.408-win-x64.zip
```

The task definition is as follows:
```yaml
- task: UseDotNet@2
  displayName: 'Use .NET 5 SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.408'
    performMultiLevelLookup: true
```

Unfortunately the Agent doesn't see the .NET SDK as being in the cache, attempts to download it from the internet and fails. I have also tried the following variations:
- Use `win-x64` for the architecture instead of `x64` to match the ZIP name
- Extract the contents of the ZIP inside the `x64` or `win-x64` directory
- Try with and without `performMultiLevelLookup`

Questions:
- What should the correct directory/file layout be?
- Would it also be possible to have this added to the documentation in case others are also trying to use agents in disconnected environments?

**Comment by hedasp** [comment]
Hi @MDendura, did you ever figure this one out? 
Have the same issue now, with performMultiLevelLookup not honoring the default locations on offline servers, and nothing added to cache.
