### ISSUE TITLE
App Center Test failing to upload files

### ISSUE THREAD

**Issue by JayasreeAdukkadkam** [microsoft/azure-pipelines-tasks#16497]
Bug
Type: Task failing when it previously worked

Enter Task Name: App Center Test

Environment
Server - Azure Pipelines

Agent - Hosted

If using Hosted agent, provide agent queue name:  **Windows-latest**

**Issue Description**

App Center test failing with below error :  

\ Uploading files... Response status code: 502
Body: {"message":"internal error","err_message":"error: activity_name: graph router, exception: ESOCKETTIMEDOUT, current_request_url: /v0.1/apps/ABB-Ability-WFM/WFM-FieldWorker-Tablet/test_runs/002baf4b-f861-4930-97a8-30e62693e757/hashes/batch, api_path: v0.1/apps/{owner_name}/{app_name}/test_runs/{test_run_id}/hashes/batch, beacon: test, code: ESOCKETTIMEDOUT. Correlation ID: 634af1fe-105e-41a9-bafb-168ac5dce372"}
Uploading files... failed.
Error: internal error
Further error details: For help, please send both the reported error above and the following environment information to us by going to [https://appcenter.ms/apps](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fappcenter.ms%2Fapps&data=05%7C01%7Cjayasree.adukkadkam%40hitachienergy.com%7Ccb56b2fc248643fba12808da580c3ba5%7C7831e6d9dc6c4cd19ec61dc2b4133195%7C0%7C0%7C637919106832773445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z2SS93b%2BcWtVLWYt1kNV6O8iMkWflLrdBx7NQR3nlLY%3D&reserved=0) and opening a support ticket (using the help menu in the upper right corner of the screen)
Environment: win32
App Upload Id: ABB-Ability-WFM/WFM-FieldWorker-Tablet
Timestamp: 1655861225507
Operation: RunAppiumTestsCommand
Exit Code: 3

Note :  It may be related to  https://github.com/microsoft/azure-pipelines-tasks/pull/16288  and https://github.com/microsoft/azure-pipelines-tasks/issues/16484

Here is the screenshot of my tasks  ( **Also tried with appcenter-cli@1.1.15 and appcenter-cli@1.2.2   and different versions of Node js , no luck** )

![image](https://user-images.githubusercontent.com/44651236/176034244-adfd8922-53df-4708-a09b-230024259312.png)

![image](https://user-images.githubusercontent.com/44651236/176034557-ce807290-a905-4375-98c9-586e0a10ff4e.png)

![image](https://user-images.githubusercontent.com/44651236/176038710-cae23209-bf49-4407-906d-2734f09c6faf.png)

**Comment by danyansun** [comment]
got same problem, is anyone fixing this problem?

**Comment by lexya** [comment]
Got the same problem!!! : (

**Comment by Saccomani** [comment]
Same here!
