### ISSUE TITLE
AzurePowershell@5 requires the Az module when given explicit version, but does not when the latest is requested. In any case the latest version is imported always.

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#16505]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowershell@5

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/8c190dc05cd7e13575a16e3a25f069f5dfed8452/Tasks/Common/VstsAzureHelpers_/InitializeAzModuleFunctions.ps1#L34-L49

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: Azure DevOps Server 2020 Update 1.1

- Agent - Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      - Agent.OS = Windows_NT
      - Agent.Version = 2.181.2

## Issue Description
When the desired version is passed the task expects the `Az` module installed on the machine. But when the latest version is requested it does not require it.

This is inconsistent and wrong behaviour. We install Az.XYZ modules we need individually, because we do not need many. Installing the Az module takes ages to complete. Our pipeline works fine as long as the latest version is requested. But when we tried to downgrade to some older version of Az.Accounts our pipeline failed.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
##[error]Could not find the modules: 'Az.Accounts' with Version: '2.7.6'. If the module was recently installed, retry after restarting the Azure Pipelines task agent.
```

**Comment by MarkKharitonov** [comment]
Another thing. I want to use Az.Accounts 2.7.6. With the current implementation of the task I cannot, because there is no Az version 2.7.6.

In general the code is supposed to behave the same whether we given it explicit version or just ask for the latest.

**Comment by MarkKharitonov** [comment]
This is even worse than I thought. The original code always returns the latest version of the installed `Az.Accounts` module, regardless of what we are asking for.
Indeed, consider the loop:
```
    $modules = Get-Module -Name $moduleName -ListAvailable
    foreach ($moduleVal in $modules) {
        # $moduleVal.Path will have value like /usr/local/share/powershell/Modules/Az.Accounts/1.2.1/Az.Accounts.psd1
        $azModulePath = Split-Path (Split-Path (Split-Path $moduleVal.Path -Parent) -Parent) -Parent
        $azModulePath = $azModulePath + "/Az/*"
        $azModuleVersion = split-path -path $azModulePath -Leaf -Resolve
        if($azModuleVersion -eq $targetAzurePs) {
            $module = $moduleVal
            break
        }   
    }
```
Suppose we have the following modules:
- Az\1
- Az.Accounts\1
- Az.Accounts\2

Also, suppose `Get-Module -Name $moduleName -ListAvailable` returns the modules in the following order:
1. Az.Accounts version 2
2. Az.Accounts version 1

We are providing `$targetAzurePs = 1` the if condition in the loop is going to be satisfied on the very first iteration with Az.Accounts version 2, because indeed there is Az/1 in there. The condition in the loop totally disregards the version of `$moduleVal`.

TBH, I do not understand how this code could have possible passed any testing.

**Comment by svrooij** [comment]
Thanks for closing

**Comment by Kiranksk** [comment]
- Getting same error, Unable to use task version 5.236.4
- Using the self hosted Ubuntu 20.04 Linux agent
- Installed pwsh - 7.4.1
- installed Az.Accounts - 2.12.4
