### ISSUE TITLE
AzureFileCopy@5 - A task is missing. The pipeline references a task called 'AzureFileCopy' with version '5' (...)

### ISSUE THREAD

**Issue by pjmvp** [microsoft/azure-pipelines-tasks#16521]
When trying to use `AzureFileCopy@5` I get an error message saying:

> `A task is missing. The pipeline references a task called 'AzureFileCopy' with version '5'. This indicates that the specific task version can not be found.`

Does this mean this task version (5) isn't available in Azure DevOps yet? 

Where could one get an overview of what is and is not available?

Asking, since  `AzureFileCopy@4` gives me the following warning:

> ##[warning]Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide

**Comment by yuriolisa** [comment]
I'm facing the same issue.

**Comment by yuriolisa** [comment]
@PhilipsonJoseph, could you please take a look?
