### ISSUE TITLE
Deployment history not updated

### ISSUE THREAD

**Issue by SamWhitby** [microsoft/azure-pipelines-tasks#16548]
*Type*: Bug

**Enter Task Name**: [AzureRmWebAppDeploymentV4](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4)

## Environment
- Agent - Hosted: 
Current agent version: '2.204.0'
Current image version: '20220619.1'

## Issue Description

The task AzureRMWebAppDeployment@4 is no longer updating the deployment history on an app service when deploying to it. I am seeing this working correctly in the version 4.198.0 and not working in the version 4.205.13

Example of how the task is being called

            - task: AzureRMWebAppDeployment@4
              displayName: Deploy to app service
              inputs:
                appType: webApp
                ConnectedServiceName: ${{ parameters.serviceConnection }}
                WebAppName: ${{ parameters.appServiceName }}
                Package: $(PIPELINE.WORKSPACE)/Build/drop/**/*.zip

### Task logs
version 4.198.0  - working correctly
![image](https://user-images.githubusercontent.com/3334161/177668371-8428ead9-3999-41d0-99c7-122ec139b794.png)
![image](https://user-images.githubusercontent.com/3334161/177668238-94b0a927-eb28-40c1-b511-7b895adf5922.png)

version 4.205.13  - skipping deployment history
![image](https://user-images.githubusercontent.com/3334161/177668824-12c40cb6-c409-4616-8bda-4eb071ab798a.png)
![image](https://user-images.githubusercontent.com/3334161/177668717-6b727d31-b43f-4b76-bc2d-664a3d13a250.png)

**Comment by SamWhitby** [comment]
This seem to be the offending pr https://github.com/microsoft/azure-pipelines-tasks/pull/16141

Specifically this line https://github.com/microsoft/azure-pipelines-tasks/commit/b1539a15241a4b59bf1b11d45f27f957fe41d060?diff=unified#diff-43df8eccd1d002e8a9aa7e15c4de987b6729a5889bd07f1d5c57f4c311cb657eR31

It looks like the intention was to update the deployment history at the same time as the deployment however it is now not updating the deployment history at all.

@v-nagarajku, any ideas?

**Comment by akyamada-ms** [comment]
This issue is also present in version 4.212.0.
I have confirmed that the history is successfully updated in version 4.209.0.
Could you please check and fix this issue?

**Comment by v-nagarajku** [comment]
@akyamada-ms 
There was an issue with 4.212.0 - the deployment history was blocked due to some improvements, but this issue might have caused regression. We have reverted the task version to 4.209.0 However the fix has been done and the new deployment will be rolled out in 214 deployments.

**Comment by v-hsakamoto** [comment]
Thank you for your rollback response.
Can you tell us the date and time the rollback to 4.209.0 took place?

**Comment by v-nagarajku** [comment]
> @v-nagarajku Thank you for your rollback response. Can you tell us the date and time the rollback to 4.209.0 took place?

It was rolled back on 11/21/2022.

**Comment by ksista-ahc** [comment]
@v-nagarajku I still see issue when using this task _AzureRmWebAppDeploymentV4_
Is the issue resolved?

**Comment by v-nagarajku** [comment]
@ksista-ahc - The issue has already been resolved.

**Comment by tomaeda** [comment]
Hello @v-nagarajku 
I saw the same issue with Task version 4.213.0. This version is used in my organization for now.
I also believe this is a version prior to 4.214.0 that you fixed.

Can you please check if this issue still exists in 4.213.0?
Also, do you know when 4.214.0 will be used that the issue is fixed?

**Comment by tomaeda** [comment]
@v-nagarajku 
I saw that the code you added in 4.212.0 is still in 4.213.0.
So I think 4.213.0 has not solved this issue yet.

When will 4.214.0 be roll out in Azure DevOps?
Please let me know when it will be deployed to organizations in Asia pacific.

**Comment by vienleidl** [comment]
The issue has been solved in 4.214.0 version.
![image](https://user-images.githubusercontent.com/97711647/213603831-40de40fb-7a1f-46ff-846e-1910e642078d.png)
