### ISSUE TITLE
Cannot read properties of undefined reading 'portalURL'

### ISSUE THREAD

**Issue by BloggingKIng** [microsoft/azure-pipelines-tasks#16549]
Deployed my django app on azure and got a notice DEPLOYMENT SUCCESSFUL but than it returned the following error

10:39:00: Deployment to "LiveCricketScores" completed.
10:39:20: "LiveCricketScores" reported a critical error: Exception
10:39:24: Error: Cannot read properties of undefined (reading 'portalUrl')

**Comment by DmitriiBobreshev** [comment]
Hello @BloggingKIng, thank you for questing, could you please clarify information about the following issue:
- What Task returns this error 
- Which version of an agent are you using
- Is it a Self-hosted agent or MS-Hosted

Also, it would be helpful if you can provide logs of your pipeline or part of it.

**Comment by BloggingKIng** [comment]
HI @DmitriiBobreshev,
THIS ERROR IS RETURNED WHEN I try to deploy using VSCode to app services!
Other types of deployments also don't work!
Here are complete question details at stackoverflow:
[https://stackoverflow.com/questions/72902297/deploying-a-django-app-on-azure-no-module-named-django](https://stackoverflow.com/questions/72902297/deploying-a-django-app-on-azure-no-module-named-django)

**Comment by MichaelParionaAlfaro** [comment]
Buenas tardes, 
Tengo el problema VSCode al subir a azure no funciona

Los registros de aplicaciones contienen errores o advertencias
ModuleNotFoundError: No module named 'pandas'
Exception

**Comment by BloggingKIng** [comment]
@MichaelParionaAlfaro First of All, please use English (I had to use google translate to translate spanish) and yes have you added '**Pandas**' to your **requirements.txt file**. Also make sure that requirements.txt is in the root of your project!

**Comment by MichaelParionaAlfaro** [comment]
Thank you very much, I have carried out the procedure you indicated, the problem still persists, can you help me remotely?

**Comment by BloggingKIng** [comment]
Sorry, I can't help you remotely because first of all I am not an Azure expert. The thing you can do is to OPEN A NEW ISSUE ON GITHUB or Just contact Azure Support on Twitter!

**Comment by MichaelParionaAlfaro** [comment]
thank you very much friend,  i will contact azure support

**Comment by gvsakhil** [comment]
> Solved the issue by adding
> 
> ENABLE_ORYX_BUILD = true
> 
> in application settings

Cool working thanks dude

**Comment by Tushar-Beladiya** [comment]
> Solved the issue by adding
> 
> ENABLE_ORYX_BUILD = true
> 
> in application settings

Thanks man! Its working for me :+1:
