### ISSUE TITLE
Existing closed issue (12151) needs to be re-opened 

### ISSUE THREAD

**Issue by vaughanh1** [microsoft/azure-pipelines-tasks#16567]
This issue is still occurring.
All details and logs are contained in the existing issue, found here:
https://github.com/microsoft/azure-pipelines-tasks/issues/12151

Please let me know if you need more information, thanks.

**Comment by TimotyTimm** [comment]
looks like it was fixed
https://developercommunity.visualstudio.com/t/Azure-DevOps:-Issue-with-Visual-Studio-T/10089391

**Comment by vaughanh1** [comment]
As per comment from @TimotyTimm I can confirm it now works. Thanks
