### ISSUE TITLE
Why is there a 5000 character limit in AzureAppServiceSettingsV1?

### ISSUE THREAD

**Issue by tjanuario** [microsoft/azure-pipelines-tasks#16588]
There is a limit of 5000 characters in the multiline settings boxes (appSetting, generalSettings, connectionStrings) in the AzureAppServiceSettingsV1 task.  A single app setting is allowed up to 10,000 characters in app service so this values seems somewhat arbitrary.  Is there a reason that this was set to this limit?

This can be seen in 
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureAppServiceSettingsV1/task.json
lines 87, 101, 115 as
"maxLength": "5000"

This results in needing to make multiple settings tasks to handle app settings which should be able to be in a single task.

**Comment by ionut-gheorghe** [comment]
Same here, I have a lot of settings

![image](https://user-images.githubusercontent.com/54311614/222191906-e2ab0ea1-f73e-4402-b37d-1b5ab08c3faa.png)

**Comment by TomasLiutvinas** [comment]
> Same here, I have a lot of settings
> 
> ![image](https://user-images.githubusercontent.com/54311614/222191906-e2ab0ea1-f73e-4402-b37d-1b5ab08c3faa.png)

Do you have a solution for this limit?:D
