### ISSUE TITLE
FTP Upload task v2 fails with 550 The directory is not empty.

### ISSUE THREAD

**Issue by Hasnni** [microsoft/azure-pipelines-tasks#16601]
FTP Upload task fails with an "Access Denied" error when release the contents of an Azure Web Site Using FTP. This always happens when i push Code From VS got error during release.
But when i manually click after release Failed on  Deploy release successfully deploy on Azure App Service.
I am using SelfHosted Agent in private Azure VM and Azure App Service is also on VN And Private Endpoint.
VM & Azure Service App both on Same Private Virtual Network. 

![ftp Error](https://user-images.githubusercontent.com/16034072/179492174-e131dd1d-09a1-46d8-a65e-d088a8537929.png)
![FTPUpload](https://user-images.githubusercontent.com/16034072/179492708-91076cd4-b1c5-4ef5-95a3-3c9e0e9597e6.png)

using .Net Core Enviroment.

**Comment by KonstantinTyukalov** [comment]
Hi @Hasnni, thank you for reporting!
Could you provide some additional information:
- Full pipeline logs in debug mode. This can be done using the following documentation - https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops
- Agent diagnostic logs
- As I see in the logs provided, the FTP server sends that the remote directory may contain hidden files - https://forums.techguy.org/threads/ftp-error-550-cannot-remove-directory-directory-not-empty.673692
http://knowledge.3essentials.com/web-hosting/article/1092/FTP-error----550-The-directory-is-not-empty.html
Could you check if the directory contains hidden files?

If you are concerned about security, you can send the logs to my email: v-ktyukalov@microsoft.com
Thank you

**Comment by Hasnni** [comment]
@KonstantinTyukalov  i sent you file in email few days ago i hope you managed time to see it.

**Comment by KonstantinTyukalov** [comment]
@Hasnni thank you, I emailed back, please check

**Comment by Hasnni** [comment]
> 

@KonstantinTyukalov  Thank you so much i got your email and send back to you all logs files which is required to you.
Thank you so much for helping

**Comment by Hasnni** [comment]
Hi @KonstantinTyukalov 
i sent you again all requested logs files per email around start of august, i am wondering if you manage time to see them because i am still struggling with this issue, i also read some where that we can't do automate via FTP Upload.
