### ISSUE TITLE
CopyFiles@2: the flag: `overWrite` is not working as expected

### ISSUE THREAD

**Issue by amininama** [microsoft/azure-pipelines-tasks#16608]
*Type*: Bug

**Task Name**: [CopyFiles@2](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/copyfiles.ts)

## Environment
- Server: Azure Pipelines
    - account name: quadinfoqii
    - team project name: QII Source Code  
    - build definition name/build number: QMOSNET-GIT-Azure/#20220719.6

- Agent: Private 
    - OS: Windows Server 2019 Standard
    - agent version: 2.196.2

## Issue Description
We're trying to use task: `CopyFiles@2` to copy one directory from the agent's file system to another machine. The agent has access to the target machine's file system and files/directories get copied without any issues. The problem is, based on the provided documentation [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml), When setting the `overWrite` option to `false`, We expect the task to fail upon discovery of existing files in the target directory.
This text is provided in the Notes section of the task's documentation:
```
If a matched file already exists in the target, the task will report failure unless Overwrite is set to true.
```
This is how we're trying to use the task:
```
  - task: CopyFiles@2
    displayName: 'Save Release to Local Repo'
    inputs:
      SourceFolder: '$(temporaryBuildFolder)/$(releaseTitle)'
      Contents: '**'
      TargetFolder: '$(artifactsRepositoryAddress)/$(releaseTitle)'
      overWrite: false
      ignoreMakeDirErrors: false
```
Upon executing the pipeline, the following lines are logged for this task:
```
Starting: Save Release to Repository
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
found 1077 files
```
And for each of those 1077 files, a line with the following format is logged (obviously, the `${file_name}` is different on each line):
```
File C:\${SOURCE_DIR}\${FILE_NAME}.xxx already exist at \\${TARGET_MACHINE}\${REPO_DIR}\${FILE_NAME}.xxx
```

I checked the code for task: CopyFiles@2 [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/copyfiles.ts). There's a conflict between what's been mentioned in the documents and what's been implemented. Please take a look at line:190. 
The code just logs the message (that we can see above) and continues without throwing a new error. If you think the implemented behavior makes more sense, please update the documents. Otherwise, I think this can be a fast fix (a new Error should be thrown after the logging that message on line: 190).

**Comment by KonstantinTyukalov** [comment]
Hi @amininama thank you for reporting! Let us check

**Comment by vmapetr** [comment]
Hi @amininama! The current behavior is expected and changing it may be a breaking change - we will update the documentation to make task behavior more explicit. Thanks!

**Comment by vmapetr** [comment]
Hi @amininama! The documentation is updated to accord with the current behavior. I'm going to close this issue, please feel free to reopen it if you have any concerns.
