### ISSUE TITLE
Second ManualValidation task in same stage is unreachable

### ISSUE THREAD

**Issue by GaTechThomas** [microsoft/azure-pipelines-tasks#16619]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ManualValidation

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: I'd prefer not to provide this info in a public forum.

- Agent - Hosted or Private: Agentless

## Issue Description

Scenario:

- Multi-stage yaml pipeline that has pre-stage validation and post-stage validation, both via the ManualValidation task. 

Steps:

1. Run the pipeline
2. The pipeline shows the Review button for the first ManualValidation job in the stage. Click that Review button.
3. The ManualValidation Reject/Resume dialog pops up. Click Resume.
4. Allow the second job in the stage to complete
5. The pipeline shows the Review button for the second ManualValidation job in the stage. Click that Review button.
6. The ManualValidation dialog pops up, but no Reject/Resume buttons exist. The dialog only shows the results of the first ManualValidation.

The only way we've found to move forward is to cancel the stage and then re-run failed jobs (which is problematic in several ways, including metrics, change management, and audit). Everything seems to run as expected from there.

### Task logs

(Will provide privately as needed.)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

No error - just stuck.

**Comment by osmansonmez** [comment]
We see the same bug in our pipelines. Why azure devops team doesnt fix this bug.

**Comment by KevinRossUWV** [comment]
I've also run into this problem. Only way to have multiple ManualValidation tasks working if you have no approval configured on your environment for this stage.

**Comment by GaTechThomas** [comment]
Still need a fix please.

**Comment by GaTechThomas** [comment]
Does this mean that it's fixed, or just closed without repair?

**Comment by GaTechThomas** [comment]
I got an email indicating that sandra-bee responded today, but somehow the response isn't here.

To answer their question, no I never got further follow-up to resolve this issue.
