### ISSUE TITLE
How to stop Nuget from outputting a dll & exe file in the package?

### ISSUE THREAD

**Issue by OldManMeta** [microsoft/azure-pipelines-tasks#16628]
Hello,

When a .net project with an output of console app is used to also generate a nuget package, the package output contains both a dll and exe file, which in turn breaks the package management inside of VS. I'm on latest VS2022 LTS Enterprise, and this is still the case.

This issue has been around for years, and continues to not be fixed by various teams. 

Is there a switch in a csproj file or in the devops nuget task (pack etc) that would force only the dll to be produced as part of the package?

Many thanks,

**Comment by OldManMeta** [comment]
After additional research, it looks like the only way to modify this is to create a manual nuspec file and exclude the exe 

Surely this could be added to the task item? If it is already, I do not see it.

Thanks

**Comment by jmyersmsft** [comment]
This would be a feature request for the NuGet Client team at https://github.com/NuGet/Home. Workarounds such as you suggest are not within the scope of the NuGet task for Azure Pipelines, sorry.

**Comment by OldManMeta** [comment]
How is this a "workaround" @jmyersmsft ? 

This is part of the functionality of nuget - the ability to exclude a file of type from a package.

What is the "scope" of the Nuget task for Azure Pipelines?
