### ISSUE TITLE
Research Item for Azure Function App Artifact Validation.

### ISSUE THREAD

**Issue by FinVamp1** [microsoft/azure-pipelines-tasks#16635]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureFunctionAppv1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

Check if we have a way to check the artifact directory structure when deploying Azure Functions Apps.

**Comment by kulkarnisonia16** [comment]
As discussed, we should try to handle it as part of post deploy steps.
