### ISSUE TITLE
Cannot use UsePythonVersion@0

### ISSUE THREAD

**Issue by ashotkhachatryan** [microsoft/azure-pipelines-tasks#16649]
Cannot use UsePythonVersion@0

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          addToPath: false

Downloading: https://github.com/actions/python-versions/releases/download/3.7.9-109486/python-3.7.9-win32-x64.zip
Extracting archive
##[error]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Unable to locate executable file: 'tar'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
##[error]Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in F:\@AzureAgent1\_work\_tool:

**Comment by ashotkhachatryan** [comment]
The error is misleading - Failed to download Python from the Github Actions python registry

It actually was able to download it. For some reason it tries to extract the archive using tar even thought the file extension is .zipo

**Comment by DenisRumyantsev** [comment]
Hi, @ashotkhachatryan, I did not manage to reproduce your issue.
Could you provide pipeline debug logs (when the `System.Debug` pipeline variable is set to `true`) to investigate this issue?
Also, which agent are you using? Self-hosted or MS-hosted?
If the agent is self-hosted, what platform is the agent running on?
If the agent is MS-hosted, which image are you using?

**Comment by DenisRumyantsev** [comment]
Hi, @ashotkhachatryan, any updates?
Could you provide the logs and answer the questions above?

**Comment by ashotkhachatryan** [comment]
Hi @DenisRumyantsev, sorry for late reply.
I can't reproduce the issue anymore so most probably there was something wrong in our end.
