### ISSUE TITLE
Support multiple parameter files

### ISSUE THREAD

**Issue by Dylan-Prins** [microsoft/azure-pipelines-tasks#16663]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Support multiple parameter files

## Issue Description

It would be great if the parameter wildcards would support injecting multiple parameter files instead of erroring out.
Or maybe even fill in the folder, so all parameter files beneath would be injected.

**Comment by max-zaytsev** [comment]
Hi @Dylan-Prins, this repo is mostly for pipeline tasks support. If it's not related to the specific task, I would suggest opening a ticket on https://developercommunity.visualstudio.com/search?space=21 for Azure DevOps related questions\feedbacks to get the right eyes on it.
