### ISSUE TITLE
Publish To Azure Service Bus task - contentType issue

### ISSUE THREAD

**Issue by zspasojevic** [microsoft/azure-pipelines-tasks#16685]
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: Publish To Azure Service Bus 

## Issue Description

When using Publish To Azure Service Bus task, the message body JSON is not recognized on the service bus topic side. Instead, it's contentType is shown as System.String and has a weird - @string3http://schemas.microsoft.com/2003/10/Serialization/� - appended to the beginning of the content. This corrupts the message data causing a deserialization error in service bus topic trigger azure function code.

![Screenshot_4](https://user-images.githubusercontent.com/43961181/182627691-08b585cc-966c-4562-b7bd-f04f05acb1c6.png)

![Screenshot_3](https://user-images.githubusercontent.com/43961181/182627724-22e60227-a543-4881-a2f7-59b528c77bb0.png)

There is no option to send any kind of header or service bus message broker property from the tasks itself.

**Comment by u821171** [comment]
hi any fix for this?

**Comment by Pr4v33n23** [comment]
Hi, 

even i'm facing the same issue, any traction on this ?

**Comment by Gahmah** [comment]
Same here, need fix

**Comment by voloszad** [comment]
No updates so far?

**Comment by Grayson-Wang** [comment]
Can someone provide updates?

**Comment by zspasojevic** [comment]
This issue is fixed now, they're just not providing any updates here. 
There is this new checkbox in the devOps task that should be unselected when sending messages to SB:

![image](https://user-images.githubusercontent.com/43961181/231105273-91ff3907-53f7-4cae-8da1-93c9ef4a72f6.png)

After that the JSON body will be received on the service bus topic as expected.
