### ISSUE TITLE
parallel has no gain in PublishBuildArtifacts 

### ISSUE THREAD

**Issue by mszhanyi** [microsoft/azure-pipelines-tasks#16688]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: here  
PublishBuildArtifacts

## Environment
Azure pipeline

I tried setting the parallel is True, but it looks no obvious gain.    
it takes 5m14s for 8 threads(default)
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=711877&view=logs&j=b10b9c15-d3e5-50d7-20d6-8335e7bc7a53&t=3a09c1ea-8c5c-5420-2a99-3b278e99a30f

it takes 5m24s for single thread
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=712508&view=logs&j=b10b9c15-d3e5-50d7-20d6-8335e7bc7a53&t=3a09c1ea-8c5c-5420-2a99-3b278e99a30f

- Agent
- Linux
- Standard D8ds v5

**Comment by LiliaSabitova** [comment]
Hi @mszhanyi thanks for reporting! 
Yes, as far as I've checked - there is a bug in this task.
We will get back to this issue soon after finishing with more prioritized issues.

**Comment by LiliaSabitova** [comment]
Hi @mszhanyi,

The fact is that parallel publishing in this task is only possible if Artifact publish location is a File Share (not Azure Pipelines).
Moreover, this task is deprecated. We recommend that you use the [Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops) task instead.

**Comment by mszhanyi** [comment]
Thanks. [The document](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) should be improved

**Comment by LiliaSabitova** [comment]
@mszhanyi the information is available [on the page of the PublishBuildArtifacts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops).

**Comment by LiliaSabitova** [comment]
Hi @mszhanyi, do you have any other questions regarding this issue?

**Comment by mszhanyi** [comment]
> Hi @mszhanyi, do you have any other questions regarding this issue?

No. it could be closed. thank you!
