### ISSUE TITLE
Bug: InstallSSHKey task intermittent issue loading private key from secure file

### ISSUE THREAD

**Issue by luckeyca** [microsoft/azure-pipelines-tasks#16691]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  

Bug

**Enter Task Name**:

InstallSSHKey@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure Pipelines

- Agent - Hosted or Private: 
    
   Hosted agent ubuntu-22.04

## Issue Description

With the pipeline task as below, it fails INTERMITTENTLY. with error in the task log section below

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(AZUREDEVOPS_KNOWN_HOSTS)
    sshPublicKey: $(SSH_PUBLIC_KEY_REPO_READONLY)
    sshKeySecureFile: 'SSH_PRIVATE_KEY_REPO_READONLY'

### Task logs

Starting: InstallSSHKey

Task         : Install SSH key
Description  : Install an SSH key prior to a build or deployment
Version      : 0.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-ssh-key

/usr/bin/ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXC2h2q7/agent.2221; export SSH_AUTH_SOCK;
SSH_AGENT_PID=2222; export SSH_AGENT_PID;
echo Agent pid 2222;
/usr/bin/ssh-add -L
The agent has no identities.
/usr/bin/ssh-add /home/vsts/work/_temp/SSH_PRIVATE_KEY_REPO_READONLY
**Error loading key "/home/vsts/work/_temp/SSH_PRIVATE_KEY_REPO_READONLY": error in libcrypto**
/usr/bin/ssh-add
Finishing: InstallSSHKey

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by LiliaSabitova** [comment]
Hi @luckeyca thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
