### ISSUE TITLE
Custom ADO Pipeline Task - Create File and Publish as Artifact

### ISSUE THREAD

**Issue by mzhukovs** [microsoft/azure-pipelines-tasks#16698]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: custom

## Environment
- Server - Azure Pipelines
- Agent - Hosted
    
## Issue Description

I am writing a custom Azure DevOps pipeline task for the first time. The task produces a file - I would like this file to be published as a pipeline artifact by the task. Simply saving the file to Build.ArtifactStagingDirectory /  Pipeline.Workspace does not publish it (i.e. it would not appear in the job's published artifacts in Azure DevOps).

My question is , is it possible to publish this newly created file , if so, any existing example you could point me to?

Alternatively, as users of this custom task would almost always want this to be the case: how could I setup the task to automatically commit the file it generates to the current repo branch (without triggering another build due to it)?

Please let me know what is the best approach - any guidance would be much appreciated.

**Comment by LiliaSabitova** [comment]
Hi @mzhukovs, you can do this in two steps in your pipeline: produce a file and then use the existing publish artifact task to publish the file.
Or if you're willing to write your own task, then you can refer to exisiting PublishBuildArtifacts task's logic from this open source repository.

**Comment by mzhukovs** [comment]
Hi @LiliaSabitova , yes I am trying to package this within the custom task I am writing, thanks I will take a look at the example you reference above.
