### ISSUE TITLE
Feature: InstallSSHKey@0 support azure repos required configuration alias settings.

### ISSUE THREAD

**Issue by luckeyca** [microsoft/azure-pipelines-tasks#16692]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature / Limitation

**Enter Task Name**: here  

list here (V# not needed):   InstallSSHKey@0
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
 
Azure Pipelines

- Agent - Hosted or Private: 
    
   Hosted ubuntu-22.04

## Issue Description

For git clone over ssh to Azure Repos to work, azure repos requires the following two rsa algorithm settings in $HOME/.ssh/config which the installsshkey task does not support

Host ssh.dev.azure.com
        **HostkeyAlgorithms +ssh-rsa
        PubkeyAcceptedAlgorithms +ssh-rsa**  

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by LiliaSabitova** [comment]
Hi @luckeyca thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
