### ISSUE TITLE
Azure Pipeline fails using node v18.x

### ISSUE THREAD

**Issue by ashitaagrwl** [microsoft/azure-pipelines-tasks#16694]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: Install nodejs

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    Team Project -Brooklyn
    Pipeline name- Brooklyn-BrowserExtensions
    AgentPool -Brooklyn-1ES-general

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
    Brooklyn-1ES-general

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I was getting  the follwoing error in build pipeline"npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead." where the agent pool  with windows-2022 image contains npm v8.11.0 which has this error. I tried to use node v18.7.0 which caused another error in build pipeline causing the task to fail. Kindly refer to this teams channel[ post]([https://teams.microsoft.com/l/message/19:7c56ede040c1440cb2029ceaf6c681f3@thread.tacv2/1659691622846?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=32d444ca-9d5f-477a-a65b-363785e0aa82&parentMessageId=1659691622846&teamName=1ES%20Hosted%20Pools&channelName=General&createdTime=1659691622846]) on more information.
You may also refer to this build where I have made the following changes: https://dev.azure.com/msmmx/Brooklyn/_build/results?buildId=12248&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=5fd232ee-0bcd-5c4f-9e6b-7e96853085e6

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
https://dev.azure.com/msmmx/29090835-24e0-4b2a-b338-8e3e533c46cf/_apis/build/builds/12248/logs/22

[Insert error from the logs here for a quick overview]

**Comment by LiliaSabitova** [comment]
Hi @ashitaagrwl  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by LiliaSabitova** [comment]
Hi @ashitaagrwl, we do not support node 18.
But could you please try using --location=global parameter instead of deprecated ones?

**Comment by LiliaSabitova** [comment]
Hi @ashitaagrwl, do you have any other questions regarding this issue?

**Comment by LiliaSabitova** [comment]
Hi @ashitaagrwl, could you please advise whether this issue is still relevant for you?

**Comment by LiliaSabitova** [comment]
Hi @ashitaagrwl, please let me know if this issue is still relevant for you?

**Comment by LiliaSabitova** [comment]
Hi @ashitaagrwl closing this one as inactive - feel free to ask any other questions or let us know if it's still relevant for you.
