### ISSUE TITLE
Using CopyFiles with CleanTargetFolder fails if the target folder does not exist

### ISSUE THREAD

**Issue by tydunkel** [microsoft/azure-pipelines-tasks#16706]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  CopyFilesV2

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: DevDiv, DevDiv, https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6535057&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=c961bbc5-e1d7-56a7-1309-8966a4feaaf3&s=6884a131-87da-5381-61f3-d7acc3b91d76

- Agent - Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:  Windows Server 2019, Current agent version: '2.206.1'

## Issue Description

[This PR](https://github.com/microsoft/azure-pipelines-tasks/commit/01d574828dc7a618089f0909fe723a06cd4e33a2) seems to have regressed using the CopyFilesV2 task with CleanTargetFolder: true when the folder doesn't exist. I believe [this change](https://github.com/microsoft/azure-pipelines-tasks/blob/01d574828dc7a618089f0909fe723a06cd4e33a2/Tasks/CopyFilesV2/copyfiles.ts#L123) is the cause since the function call switched from ignoring ENOENT to throwing.

Turning off CleanTargetFolder resolves the issue.

### Task logs

```
Starting: Copy localization files
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.208.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
found 878 files
Cleaning target folder: D:\a\_work\1\a\loc
##[warning]Entry "D:\a\_work\1\a\loc" does not exist
##[error]Error: Entry "D:\a\_work\1\a\loc" does not exist
Finishing: Copy localization files
```

**Comment by tydunkel** [comment]
Note: 2.200.0 was working for us yesterday, and today it seems that 2.208.0 is being used, so I do believe the linked PR is the root cause since the version bumped from 2.200.0 -> 2.208.0 in that PR.

Successful run:
```
Starting: Copy localization files
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
found 878 files
Cleaning target folder: D:\a\_work\1\a\loc
...
```

**Comment by delmyers** [comment]
Thanks for working on this so quickly. Wondering about an ETA on this fix, since many of our builds are currently failing due to it.

**Comment by DenisRumyantsev** [comment]
@delmyers we are going to roll out the rollback today.
@tydunkel thank you for your pull request with the fix. We will review and merge it before the next release of the tasks.

**Comment by tydunkel** [comment]
Confirmed this morning that 2.208.1 is pulled which contains the revert.

**Comment by DenisRumyantsev** [comment]
@tydunkel, let me close this issue since your PR with the fix was merged
