### ISSUE TITLE
Unable to locate executable file: 'mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

### ISSUE THREAD

**Issue by bhanukotturi** [microsoft/azure-pipelines-tasks#16735]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by kirill-ivlev** [comment]
Hi @bhanukotturi thank you for reporting your issue!

Regarding error code, most likely, you have no "mvn" tool listed in your system's PATH environment variables.
Please check if this command is available from your command prompt.

Also, if you still face this issue, we will need the required information listed in the template, please fill it out and we can continue our investigation on that.

**Comment by kirill-ivlev** [comment]
Hi @bhanukotturi 

We have no heard any updates on this issue during past 4 weeks.
I will close this issue due to inactivity.
Please, feel free to re-open it if this issue is still exist.
