### ISSUE TITLE
Azure-Pipeline throws [warning]Failed to publish test results: Could not find a part of the path '/integration/test-output.xml'

### ISSUE THREAD

**Issue by priyankapashte** [microsoft/azure-pipelines-tasks#16766]
We are running pytests using the following command via azure-pipeline:

python3 -m pytest -s --doctest-modules --junitxml=qa_integration_cli.xml --cov=. --cov-report=xml ./ArtifactsManagerCLI.py --no-coverage-upload \
During the pipeline run, we see that Azure pipeline is trying to publish test results even before the test-output.xml file is created. Any idea to bypass the "Failed to publish test results" warning?

*** Run Integration test (CLI)

============================= test session starts ==============================

platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0

rootdir: /integration

plugins: env-0.6.2, azurepipelines-1.0.3, nunit-1.0.1, cov-3.0.0

- Downloading CLI from: https://buildout-resource-manager--14913077.blackrock-203de42d.northcentralusstage.azurecontainerapps.io/api/tools/cli?platform=LinuxX64

Updating Configuration

- CLI Version: build: 14913077 Linux x64 Portable

- Service URL: https://buildout-resource-manager--14913077.blackrock-203de42d.northcentralusstage.azurecontainerapps.io/

collected 11 items

##[warning]Failed to publish test results: Could not find a part of the path '/integration/test-output.xml'.

Skipping uploading of coverage data.

------------ generated Nunit xml file: /integration/test-output.xml ------------

----------- generated xml file: /integration/qa_integration_cli.xml ------------

**Comment by ChristianStadelmann** [comment]
This issue is not stale.

**Comment by Gabe-Kelly01** [comment]
Issue is still occurring, can we reopen this?
