### ISSUE TITLE
ARM Deployment Task - Error when spaces in template path for bicep files

### ISSUE THREAD

**Issue by GMedlin** [microsoft/azure-pipelines-tasks#16789]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ARM template deployment

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: garett.medlin@warburgpincus.com, Deal Data Mart Team, Automation Account Build

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines, windows-latest

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

ARM Template deployment fails for bicep files when the path includes spaces. The same task succeeds for an ARM template json file. I've tried enclosing the Template file path argument in single quotes, double quotes, and using a variable for it. I am currently using an Azure PowerShell task instead as a workaround using New-AzResourceGroupDeployment.

### Task logs

[ReleaseLogs_170.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9409696/ReleaseLogs_170.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[tasklog_6.log](https://github.com/microsoft/azure-pipelines-tasks/files/9409714/tasklog_6.log)

**Comment by Eonasdan** [comment]
I just came across this issue as well. What's a timeframe for fixing this?

**Comment by jerchap** [comment]
My workaround for the time being was to change the source artifact name in my release pipeline, as this is where the spaces where occurring, because of the git repo name.

**Comment by trolleyboy** [comment]
Also seeing this issue (finally getting around to playing with Bicep). 
`Error: Command failed: az bicep build --file <path to file>` 
Seems Az CLI isn't passed the file path wrapped in quotes.

**Comment by GMedlin** [comment]
I've just continued to use the Azure PowerShell task and the New-AzResourceGroupDeployment cmdlet rather than the rather than the ARM Template Deploymne task.

**Comment by DaleyKD** [comment]
+1, please. Everything was working fine when I used a JSON ARM Template. Decided to try Bicep today and everything blew up.

**Comment by Eonasdan** [comment]
@DaleyKD if you're just getting into ARM conversion, I'd suggest you look at Pulumi or the Terraform CDK. It will take some effort to learn but blows bicep out of the water.

**Comment by fmms** [comment]
This tasks is still relevant it even has a PR… #19382

**Comment by venkymanda** [comment]
Yeah , its an issue I hope MS team will fix by merging my PR .

**Comment by PolkageistHS** [comment]
> Yeah , its an issue I hope MS team will fix by merging my PR .

Looks like your PR has a merge conflict.  Any chance you can fix it so it can get pushed?  Would like this to get fixed so I can use the task instead of powershell gimmicks

**Comment by thommaa** [comment]
Updated PR existing here with test cases implemented https://github.com/microsoft/azure-pipelines-tasks/pull/20048
