### ISSUE TITLE
Parameters.xml being ignored by File Transform

### ISSUE THREAD

**Issue by misterbee180** [microsoft/azure-pipelines-tasks#16782]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: FileTransform

## Environment
Azure Pipelines
Hosted

## Issue Description
FileTransform V1 & 2
While trying to target parameters.xml in a deployment package the following message is returned: "Skipped Updating file:[Filename]"
![image](https://user-images.githubusercontent.com/5283412/185961670-d9f30f3e-58b8-4918-a594-9530f87005d2.png)
As shown, the files are being found but ignored. 

Here are the file the contents:
![image](https://user-images.githubusercontent.com/5283412/185962191-8a349d97-c159-4ca7-bce9-caba4adc2cae.png)

Here is my configured task:
![image](https://user-images.githubusercontent.com/5283412/185962699-5900eb90-3f15-4655-bc0a-72c1a552613a.png)

Here is my associated variable I'd like it replaced with configured in the release pipeline:
![image](https://user-images.githubusercontent.com/5283412/185962479-837e2cee-63c6-4524-aa5c-2dbce4afa144.png)

### Task logs
See previous image

**Comment by arshadsurti** [comment]
I have the same issue, looks like any keys/names that have "." are being ignored, I guess could work around by removing the "." ?
