### ISSUE TITLE
SqlAzureDacpacDeployment not AutoDetecting and adding Firewall Rule

### ISSUE THREAD

**Issue by centreboard** [microsoft/azure-pipelines-tasks#16803]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeployment 

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/BarnettWaddingham/Data%20Analytics/_build/results?buildId=4348

- Agent - Hosted: 
    - If using Hosted agent, provide agent queue name: `Azure Pipelines`

## Issue Description
Using SqlAzureDacpacDeployment with AutoDetect firewall rule, to deploy to an Azure SQL which does **NOT** allow `All azure services`, but does allow adding firewall rules.
```
- task: SqlAzureDacpacDeployment@1
              inputs:
                AuthenticationType: servicePrincipal
                ServerName: $(sqlServer).database.windows.net
                DatabaseName: $(databaseName)
                deployType: DacpacTask
                DeploymentAction: Publish
                IpDetectionMethod: AutoDetect
                ...
```
This worked up to yesterday (Wednesday 24th Aug), but has failed every time today.
It only succeeded when  we temporarily allowed `All azure services` to connect.

There is no sign of an Firewall rule being added / deleted by the Service Prinicipal in the Activity Log when viewing the SQL Server in the Azure Portal since yesterday.

I believe the error message returned by Azure SQL was being parsed in `Get-AgentIPRange` to detect the IP address of the build agent
https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1#L348-L353
https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1#L379-L392

Previously Azure SQL would return an error message similar to this, containing the agent IP address and `sp_set_firewall_rule`
> ##[error]Cannot open server 'xxx' requested by the login. Client with IP address '20.254.162.64' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.

Message returned now appears to be
> Database 'yyy' on server 'xxx' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '3D01E575-9E0B-4F86-9937-D9D1FC44B127'

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

> ##[debug]Fetching Access Token
##[debug]POST https://login.windows.net/e79933b8-eb95-495f-865d-f37c004b9ad2/oauth2/token with -1-byte payload
##[debug]received 1506-byte response of content type application/json; charset=utf-8
##[debug]Reaching SqlServer to check connection by running Invoke-SqlCmd
##[debug]Run-InlineSql -authenticationType servicePrincipal -serverName xxxx.database.windows.net -databaseName yyyy -sqlUserName  -sqlPassword  -sqlInline "select getdate()" -connectionString  -ErrorVariable errors -ConnectionTimeout 120 | Out-String
Temporary inline SQL file: C:\Users\VssAdministrator\AppData\Local\Temp\tmp45AB.tmp
Invoke-Sqlcmd -AccessToken "**********" -ServerInstance "xxxx.database.windows.net" -Database "yyyy"  -Inputfile "C:\Users\VssAdministrator\AppData\Local\Temp\tmp45AB.tmp" 
##[debug]Removing File C:\Users\VssAdministrator\AppData\Local\Temp\tmp45AB.tmp
##[debug]Failed to reach SQL server xxxx.database.windows.net. Database 'yyyy' on server 'xxxx' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '7BEFD455-098B-4566-A2E2-9609A3168D41'.
##[debug]Error Message : System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Database 'yyyy' on server 'xxxx' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '7BEFD455-098B-4566-A2E2-9609A3168D41'.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]Message To Parse: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Database 'yyyy' on server 'xxxx' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '7BEFD455-098B-4566-A2E2-9609A3168D41'.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]
##[debug]Sql configured firewall wait time is invalid. So, setting it to defaul : 10
##[debug]Sql firewall configured wait time : 10

**Comment by Annapriya-APJ** [comment]
Facing the same issue. For some time now, the IP is not gotten whitelisted automatically even if we have the parameter set ipDetectionMethod: 'AutoDetect'

Error: ##[error]Cannot open server 'xxxxxx' requested by the login. Client with IP address 'xx.xxx.xxx.xx' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.

**Comment by jsayce** [comment]
Also having this issue. I've just switched from `AuthenticationType: server` to `AuthenticationType: servicePrincipal` and IP whitelisting is now failing.

**Comment by WolleES** [comment]
We have the same issue since some weeks.
We could fix it with Service Endpoints but they are working only inside the region.
https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview
Or you can fix it with service tags

**Comment by bmeijwaard** [comment]
The way we `fixed` it is by adding the IP address of the build agent at the start of the deploy and removing it again when done all as steps of the pipeline.

**Comment by WolleES** [comment]
I got the information from the Azure Support that the AutoDetection is no more working for Self Hosted Agents.
We found out that this is still working
task: SqlAzureDacpacDeployment@1
	IpDetectionMethod: '**IPAddressRange**' # no more AutoDetection
	StartIpAddress: '0.0.0.0'
	EndIpAddress: '0.0.0.0'
	DeleteFirewallRule: true # is default
