### ISSUE TITLE
Running XCODE build Natively

### ISSUE THREAD

**Issue by sabareeshkkanan** [microsoft/azure-pipelines-tasks#16805]
## Required Information

When Xcode build task is run on the Apple M1 machine it is using Rosetta to run the build instead of running natively. PLease provide an option to configure or some alternatives

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Xcode  

## Environment
- Server - Azure Pipelines 

- Agent - Private:

**Comment by SabareeshGC** [comment]
Any update
