### ISSUE TITLE
Yaml DownloadPipelineArtifact@2 fails to find tagged build

### ISSUE THREAD

**Issue by mikerains** [microsoft/azure-pipelines-tasks#16811]
**Question, Bug, or Feature?**  
Question
**Enter Task Name**: DownloadPipelineArtifact@2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadPipelineArtifactV2

## Environment
- Server - Azure Pipelines <strike>or TFS on-premises?</strike>
        
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account name: michaelrains
team project name: 'M7Computers'
build definition name: 'TestConsoleApp' (definitionId=56)
build number: 387

https://dev.azure.com/michaelrains/M7Computers/_build/results?buildId=387&view=results

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: ubuntu-latest

## Issue Description

Intent is to use DownloadPipelineArtifact@2 to find latest previous run that is tagged with a value 'spocktagx', for the same pipeline, latestFromBranch.
````
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Upload and Tag Stuff
  jobs:
  - job: maker
    steps:
    - task: PublishPipelineArtifact@1
      name: SpockUpload
      inputs:
        path: '$(Pipeline.Workspace)'
        artifactType: 'pipeline'
        artifactName: 'WorkspaceFolderCopy'

    - bash: |
        echo "##vso[build.addbuildtag]spocktagx"
        echo "tagged"

- stage: read
  displayName: Download and list 
  dependsOn: build # stage-to-stage dependency so we should find our own run.  Comment out build stage and find previous tagged
  jobs:
  - job: reader
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: M7Computers
        pipeline: $(System.DefinitionId)
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/main'
        tags: 'spocktagx' # a previous run tagged the build as 'spocktagx'; can be seen in Pipeline portal filtering on tag 'spocktagx' 
        path: $(Pipeline.Workspace)/downloadtest4

    - bash: |
        ls -l $(Pipeline.Workspace)
        ls -lR $(Pipeline.Workspace)/downloadtest4

````

1. It has worked once for tag 'spocktag', but the same code, using a different tag, experiences ##[error]No builds currently exist in the pipeline definition supplied.

You can see evidence of when it first ran and was able to find previous build tagged 'spocktag' by looking at this build: https://dev.azure.com/michaelrains/M7Computers/_build/results?buildId=302&view=results
In that build the log shows DownloadPipelineArtifact@2 downloaded 9 files from build # 297, and the bash step afterwords shows the expected files appearing, ie:
````
ls -lR $(Pipeline.Workspace)/downloadtest2

/home/vsts/work/1/downloadtest2/WorkspaceFolderCopy:
total 16
drwxr-xr-x 2 vsts docker 4096 Aug 26 12:46 TestResults
drwxr-xr-x 2 vsts docker 4096 Aug 26 12:46 a
drwxr-xr-x 2 vsts docker 4096 Aug 26 12:46 b
drwxr-xr-x 3 vsts docker 4096 Aug 26 12:46 s
. . .
/home/vsts/work/1/downloadtest2/WorkspaceFolderCopy/s:
total 16
-rw-r--r-- 1 vsts docker  985 Aug 26 12:46 README.md
drwxr-xr-x 2 vsts docker 4096 Aug 26 12:46 TestConsoleApp
-rw-r--r-- 1 vsts docker 1147 Aug 26 12:46 TestConsoleApp.sln
-rw-r--r-- 1 vsts docker 1710 Aug 26 12:46 azure-pipelines.yml

````

2. It is almost as if the API to find the build based on tag only works with the first tag ever created (ie: 'spocktag') for a team project or maybe for the whole Organization.  
3. DownloadPipelineArtifact@2 is able to download the artifact if I code it with a runVersion: 'specific' and runId: 316.  RunId 316 is tagged 'spocktagx' and has published artifacts.  But it cannot find this build by use of tags: 'spocktagx'

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
[michaelrains_logs_396.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9436296/michaelrains_logs_396.zip)

````
[Insert error from the logs here for a quick overview]
##[debug]Evaluating condition for step: 'DownloadPipelineArtifact'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: DownloadPipelineArtifact
==============================================================================
Task         : Download Pipeline Artifacts
Description  : Download build and pipeline artifacts
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
==============================================================================
##[debug]TargetPath: /home/vsts/work/1/downloadtest4
##[debug]ArtifactName: 
##[debug]BuildResult: Succeeded
##[debug]Run: Specific
##[debug]ProjectId: 3f4f54f5-260b-4917-8dad-f91e132edf73
##[debug]PipelineVersionToDownload: latestFromBranch
##[error]No builds currently exist in the pipeline definition supplied.
##[debug]Processed: ##vso[task.logissue type=error;]No builds currently exist in the pipeline definition supplied.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.GetPipelineIdAsync(AgentTaskPluginExecutionContext context, String pipelineDefinition, String pipelineVersionToDownload, String project, String[] tagFilters, BuildResult resultFilter, String branchName, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
````

**Comment by mikerains** [comment]
I am finding something.  If I explicitly add 
````
allowFailed: true
````

then the DownloadPipelineArtifacts@2 that uses latestFromBranch and tags: 'spocktagx' IS ABLE TO FIND THE BUILD AND DOWNLOAD THE ARTIFACTS.

So, I think what is going on is:
 - the pipeline which created the artifact has 2 stages: Stage1 creates and uploads artifacts, Stage 2: attempts to download artifact
 - when Stage 1 succeeds, but stage 2 fails, the entire build is now considered FAILED.
 - all the successive attempts to download the artifact fail with the error "No builds currently exist in the pipeline definition supplied" because the builds that created the artifacts are FAILED builds.
 - adding the DownloadPipelineArtifact@2 input "allowFailedBuilds: true" allows the Download to succeed.

**Comment by mikerains** [comment]
This might be the same issue as discussed in https://github.com/microsoft/azure-pipelines-tasks/issues/13101

I added a comment to that issue referencing this issue 16811.

**Comment by viv3k1** [comment]
I am not able to find this even with allowed failed true.
I am using this in the same pipeline, I don't want to build again, should be able to release it whenever required .
at build stage
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        artifactName: ${{ parameters.artifactName }}
        targetPath: '$(build.artifactstagingdirectory)'

    - task: PowerShell@2
      displayName: 'Set artifact tag'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[build.addbuildtag]test_tag"

at deploy stage

            - task: DownloadPipelineArtifact@2
              displayName:
              inputs:
                buildType: "specific"
                path: "$(Pipeline.Workspace)/${{ parameters.artifactName }}"
                artifact: ${{ parameters.artifactName }}
                pipeline: $(System.DefinitionId)
                project: $(System.TeamProjectId)
                buildVersionToDownload: "latest"
                allowPartiallySucceededBuilds: true
                tags: "test_tag"
                branchName: "$(Build.SourceBranch)"
                allowFailed: true
              continueOnError: true
              
              
From my understanding :
When I set the latest from the branch I was expecting the latest artifact object, which I have previously built in older run
and now I should be able to download it and release it without having to build it this time.
but  azure looks for the current pipeline's run build stage and is not able to find the tagged artifact
