### ISSUE TITLE
FileTransform Task Fails to update JSON array parameters.

### ISSUE THREAD

**Issue by UL-ChrisGlew** [microsoft/azure-pipelines-tasks#16827]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: FileTransform

## Environment
   
Azure Pipelines

## Issue Description

Pipeline downloaded the latest version of FileTransform (v1.208.0) - the task will now fail to update JSON array parameters, when previously this was working fine.

### Task logs

Not sure how to enable debug logging on a Release pipeline, but what shows currently is:

2022-09-01T13:16:39.5204312Z ##[section]Starting: [Redacted]
2022-09-01T13:16:39.5470896Z ==============================================================================
2022-09-01T13:16:39.5471153Z Task         : File transform
2022-09-01T13:16:39.5471384Z Description  : Replace tokens with variable values in XML or JSON configuration files
2022-09-01T13:16:39.5471608Z Version      : 1.208.0
2022-09-01T13:16:39.5471958Z Author       : Microsoft Corporation
2022-09-01T13:16:39.5472240Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/file-transform
2022-09-01T13:16:39.5472509Z ==============================================================================
2022-09-01T13:16:39.9392128Z ##[warning]Resource file haven't been set, can't find loc string for key: JSONvariableSubstitution
2022-09-01T13:16:39.9394537Z JSONvariableSubstitution **appsettings.json
2022-09-01T13:16:39.9586599Z ##[warning]Resource file haven't been set, can't find loc string for key: JSONvariableSubstitution
2022-09-01T13:16:39.9588729Z JSONvariableSubstitution [Redacted]\appsettings.json
2022-09-01T13:16:39.9694878Z ##[warning]Resource file haven't been set, can't find loc string for key: JSONvariablesubstitutionappliedsuccessfully
2022-09-01T13:16:39.9695927Z JSONvariablesubstitutionappliedsuccessfully
2022-09-01T13:16:39.9782381Z ##[section]Finishing: [Redacted]

**Comment by UL-ChrisGlew** [comment]
Might be related to #16821. This is breaking a lot of pipelines for us and there is no real workaround.

**Comment by tgrabus** [comment]
Have the same issue with xml configs
![image](https://user-images.githubusercontent.com/9088646/187929758-831ec130-8335-439c-a584-917fa01e58b4.png)

**Comment by DotNetHacker** [comment]
Our team has the exact same issue it seems. Our Azure releases are dead-in-the-water because JSON variable substitution does not seem to work as expected after this change. We first observed this issue today @ 8AM eastern time.

Any workarounds yet?

**Comment by AndySmithSC** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/16821 is the similar issue.  From the look of it the workaround seems to be specifying an older version of the FileTransfrom:

task: FileTransform@1.206.0

Haven't confirmed that yet in our yaml, but might be worth looking at the comments in the other bug

**Comment by DanielEMoore** [comment]
all my release pipelines broke from this i tried the "task: FileTransform@1.206.0" but getting error with starting the pipeline now.
![image](https://user-images.githubusercontent.com/7445821/187956302-65d1e4f2-e3f3-404f-af9b-e2c3ee86e516.png)

**Comment by AndySmithSC** [comment]
I would suggest looking at the history log of your previous successful deployment, perhaps you were using a different version? So in our previous successful deployment, in the FileTransform Task we had this line:

C:\azagent\A2_work_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27\1.206.0\c...

So for us 1.206.0 should work. As I say though we haven't tested this workaround ourselves yet

**Comment by DanielEMoore** [comment]
'I did this workaround and copy pasted the 1.206.0 into 1.208.0. It worked sort of hacky but gets my release pipelines up and running.
https://github.com/microsoft/azure-pipelines-tasks/issues/16821#issuecomment-1234306919

**Comment by sberthu** [comment]
same issue for me but not only for arrays. All my json transformation fails.
I am in v1.208 and I have rename the folder to 1.206 and my release works.
But the task does not throw any error and I guesss my deploy was fine... but not.

**Comment by KyloByte** [comment]
The "- task: FileTransform@1.206.0" override was working for me for about an hour and now I am getting the same as above 
"Invalid step task reference FileTransform@1.206.0" something has changed that broke this workaround.

**Comment by traderhut** [comment]
We are dead in the water for ALL our deployments, as pretty much everything is using this.

I don't see an option to select a previous version (i.E. 1.206) from the drop down of versions..

**Comment by traderhut** [comment]
Has anyone cloned the Repo, rolled it back to 1.206, and then created a new file transform extension from it, so we can have a stable version?  I need exactly 0% new changes over, say the next 20 years for this tool.  It did what it needed to do, and there were no features that I needed to be added.    Its value is that it was stable.   I tried the 2.x version but that is apparently a breaking change.

**Comment by AndySmithSC** [comment]
> Has anyone cloned the Repo, rolled it back to 1.206, and then created a new file transform extension from it, so we can have a stable version? I need exactly 0% new changes over, say the next 20 years for this tool. It did what it needed to do, and there were no features that I needed to be added. Its value is that it was stable. I tried the 2.x version but that is apparently a breaking change.

I think the workaround at the moment is using 1.0.206 in place of 1.0.208, so by adding this to the yaml you are effectively copying 206 to 208:

- powershell: |
   $v208="$(Agent.WorkFolder)/_tasks/FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27/1.208.0"
   $v206 ="$(Agent.WorkFolder)/_tasks/FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27/1.206.0"
   if(Test-Path $v208){
    rm -r $v208
   }
   
  copy  $v206 $v208 -r
  displayName: 'PowerShell Fix for FileTransform Issue'

**Comment by pixelnix** [comment]
+1 for this being an urgent, production-impacting issue

**Comment by traderhut** [comment]
It appears that they deleted 1.208, and it is now using 1.206 (as of a minute or two ago)

**Comment by jarodsmk** [comment]
Also having this issue, I came across [this post](https://stackoverflow.com/questions/72046252/azure-devops-file-transform-task-not-catching-issues-with-transform) mentioning FileTransform@2 works. I'm a little against using preview features in prod for obvious reasons, but...

Desperate times

**Comment by jarodsmk** [comment]
There's also a [discussion posted](https://developercommunity.visualstudio.com/t/File-transform-task-failing-to-transform/10137353?space=21&entry=problem&viewtype=all) on the VS Dev Community

**Comment by pixelnix** [comment]
Our release pipelines with File Transform are working again and the task version was updated to 1.211.0

**Comment by traderhut** [comment]
Be aware though, that it now echos ALL values that it substitutes, including Secrets.  Thankfully, although this would normally be a gaping security hole, it is reduced by the logging system, which hopefully has no problems converting secrets to ***.    Now, if you think this is a new 'feature' that you didn't want, well, that is Microsoft for you.

Also, I have not tested what it does if it fails in any fashion, still don't know if it properly returns an error code and aborts.

We have moved away from this for everything that we could, the one that we still use it for is updating inside of a .zip file, which would have required more steps to handle.

**Comment by Jacob-Kizzee** [comment]
A possible solution:

[This documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops) from Microsoft shows a different Variable setup than previous versions.  Replace the colons ":" with periods "."

Originally I had "Path:To:My:JSON:Variable" as the Variable name...

Needs to be replaced with "Path.To.My.JSON.Variable" and the hierarchy search/find will work.
