### ISSUE TITLE
Is there a way to run only failed test cases in azure devpos?

### ISSUE THREAD

**Issue by rehamkotb** [microsoft/azure-pipelines-tasks#16820]
I Have category with some of test cases for ex(2 test cases, 1 test case passed & the second one failed) I need to run only the failed test case when run this release for the second time

when I enabled "re-run" opting in test assemblies, both test cases run but I need to rnu only failed test case

I there a way in Azure devops allows me to run only failed test cases?

**Comment by rehamkotb** [comment]
@DmitriiBobreshev 
**This is the configured pipeline** 
![image](https://user-images.githubusercontent.com/49946343/187413308-f986895a-7ae5-4bb5-be28-37cc050e76d1.png)

 **And these tasks used for testing**
I've enabled the re-run failed tests option, but it didn't meet our goal 
**as we need to run only failed test cases (from previous build)  when run the build pipeline
we don't need to run all test cases (passed & failed) again, I need to select the failed test cases & try to run them all**  

![image](https://user-images.githubusercontent.com/49946343/187413706-48042ac7-62a2-4f7c-acb6-593e13a57ffe.png)

**Comment by DmitriiBobreshev** [comment]
@rehamkotb Thank you for providing the info! Unfortunately, our team are not codeowners of [VsTestV1 Task](https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS#L412) so my knowledge in this case very limited, but maybe @rasunkar could help you?

**Comment by rehamkotb** [comment]
@DmitriiBobreshev I was thinking about workaround to solve this issue, if there is a middleware in azure makes me update the database with the test results  of pipeline. and then take these failed cases & re-run it for next release . I don't know if it possible or not?

**Comment by aaronportier** [comment]
Is this still being looked into? I currently use DotNet Test to run my tests and it takes on average 3-4 hours for the tests to run in that task. It would be awesome to re-run the tests that failed as we use real devices that have some problems outside of the app and would probably re-run with a pass. I have seen Powershell scripts but I would rather use another way. The other option is trying to write an argument in DotNet Test that filters failed tests and run those after but I can not figure that out.

**Comment by rehamkotb** [comment]
@aaronportier there was a work around I figured out may can help you 

**Solution**:
**Through Azure side**
	•	Create new stage with separate Tasks
	•	Replace VS Test task with the below Command line which run only failed test cases stored in text file 
nunit3-console.exe C:\"path_of_failed_test_cases_FailedTestCases.txt"

**Through Server side**
	•	Install “NUnit.Console-3.15.2.msi” on server
	•	Add Nunit path in System enviroments
“C:\Program Files (x86)\NUnit.org\nunit-console”

**Comment by aaronportier** [comment]
Thank you for your reply. Can I add the same argument to DotNet test? I am
not using Visual Studio test.
