### ISSUE TITLE
Resource file haven't been set, can't find loc string for key

### ISSUE THREAD

**Issue by raphael-heilbuth** [microsoft/azure-pipelines-tasks#16821]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: FileTransform

## Environment
Azure Pipelines
Hosted

## Issue Description

[warning]Resource file haven't been set, can't find loc string for key: JSONvariableSubstitution
[warning]Resource file haven't been set, can't find loc string for key: JSONvariablesubstitutionappliedsuccessfully

In version 1.206.0 work

![Captura de tela 2022-08-30 103917](https://user-images.githubusercontent.com/70953533/187452507-054b53a1-ddfe-4e23-9836-7ce96d45faa9.jpg)

![Captura de tela 2022-08-30 103942](https://user-images.githubusercontent.com/70953533/187452541-08514f28-1a5a-4394-8fbc-302ef6ff5f58.jpg)

In version 1.208.0 not work

![Captura de tela 2022-08-30 103829](https://user-images.githubusercontent.com/70953533/187452601-d3fcdb95-ab8c-44ab-8238-2bfff39bcc93.jpg)

![Captura de tela 2022-08-30 103604](https://user-images.githubusercontent.com/70953533/187451433-dfa35d29-93ed-4409-a8b7-19c78e3d81f2.jpg)

### Task logs

See previous image

**Comment by yuriisant** [comment]
I got exactly the same problem

**Comment by seantleonard** [comment]
My project is experiencing this too with all filetransform tasks. This is breaking all pipelines that depend on this. The last successful runs that I had were with File transform task v 1.206.0

**Comment by yuriisant** [comment]
Does anyone know if it is possible to configure the task version back?

**Comment by viamus** [comment]
For the time been i changed my pipeline to use **FileTransform@2** to recover my environment from a deployment without proper settings transformation.

**Comment by sidobill** [comment]
we had that, replacing 1.206 content to 1.208 as a workaround

**Comment by wojciechowskiamoneycorp** [comment]
@nadesu can we have ETA of the fix. 
This bug is breaking all our release pipelines.

**Comment by kmcoulson** [comment]
@nadesu Likewise this is breaking our pipelines. Could we get an ETA or a workaround please?

**Comment by gurisingh** [comment]
Same here. It's breaking our pipelines. Can we have a fix or workaround please.

**Comment by chowarth** [comment]
Also having the same issue with our pipelines 😭

**Comment by kmcoulson** [comment]
My colleague has raised this on the developer community also: https://developercommunity.visualstudio.com/t/File-transform-task-failing-to-transform/10137353?space=21&entry=problem

**Comment by nicksimmonds-lmk** [comment]
Same here.  All our pipelines are broken.

**Comment by Compufreak345** [comment]
It feels wrong to use an undocumented V2 as a workaround. I'd propose to fix this over 2 year old issue after fixing the bug 🤷‍♀️
https://github.com/MicrosoftDocs/azure-devops-docs/issues/8871

**Comment by chao-master** [comment]
We haven't gotten any success using v2 as a work around.

**Comment by sidobill** [comment]
> @nadesu Likewise this is breaking our pipelines. Could we get an ETA or a workaround please?

replacing folder content, worked for us

**Comment by gurisingh** [comment]
I ended up using a powershell script as a work around to manually change the required properties in my appsettings.json file.

```
 - powershell: |
	  $pathToJson = "$(System.DefaultWorkingDirectory)\src\Api\appsettings.json"
	  $appsettingsFile = Get-Content $pathToJson | ConvertFrom-Json

	  $appsettingsFile.ConnectionStrings.DatabaseConnectionString = "$(DatabaseConnectionString)"

	  $appsettingsFile | ConvertTo-Json | set-content $pathToJson
    displayName: Transform appSettings.json
```

**Comment by UL-ChrisGlew** [comment]
> > > @nadesu Likewise this is breaking our pipelines. Could we get an ETA or a workaround please?
> > 
> > 
> > replacing folder content, worked for us
> 
> What exactly do you mean by that?
> 
> I did try to use the v2, but it throws me this error:
> 
> ```
> ##[error]Error: Cannot perform XML transformations on a non-Windows platform.
> ```
> 
> Using this configuration:
> 
> ```
>             - task: FileTransform@2
>               displayName: 'Inject appsettings configuration'
>               inputs:
>                 folderPath: '$(System.ArtifactsDirectory)/drop/code'
>                 fileType: json
>                 jsonTargetFiles: |
>                   **/appsettings.json
> ```
> 
> Not sure what kind of XML transformation it is trying to do here, but the workaround does not help on our linux build agent 🤷‍♀️

I think what they mean is on the release agent, go to where the tasks are stored (mine was at C:\azagent\A3\_work\_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27). Then copy (and overwrite) the contents of the FileTransform '1.206.0' folder into the '1.208.0' folder to basically 'revert' the task back.

I've just tried doing the same thing and, for now at least, everything appears to be working okay.

**Comment by tgspn** [comment]
My workaround was like @sidobill said, but I created a pipeline to do that with this task:

```
steps:
- powershell: |
   $v208="$(Agent.WorkFolder)/_tasks/FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27/1.208.0"
   $v206 ="$(Agent.WorkFolder)/_tasks/FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27/1.206.0"
   if(Test-Path $v208){
    rm -r $v208
   }
   
   copy  $v206 $v208 -r
  displayName: 'PowerShell Script'
```

**Comment by chowarth** [comment]
@tgspn I tried what you've done but get an error saying that it can't find the `1.206` folder `/Users/runner/work/_tasks/FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27/1.206.0`.

This makes sense as only `1.208` will be installed when the YAML is run :/

**Comment by wojciechowskiamoneycorp** [comment]
Workaround with providing full version of the task doesn't work when the release pipeline was created via UI

**Comment by a-m-shaw** [comment]
For anyone else who is stuck with a UI-created pipeline or task group and is tempted to bypass the UI and use the API, whilst an updated version specification does appear to stick in the definition, attempting to actually _use_ the pipeline then results in the error `Tasks with versions 'Transform application configuration:1.206.0' are not valid for deploy job 'Build agent group phase' in stage xxx`.

**Comment by sdb-dev** [comment]
@nadesu Can you please update us on the situation? Can this version be rolled back?

**Comment by blakesparkes** [comment]
Same issue here.  Same pipelines succeeded on 8/31 all started failing on 9/1.

**Comment by blakesparkes** [comment]
For those who built their pipeline with the UI: I've had success with a workaround.   

Change the File Transform task version to 2.* (preview).  
I emptied the Xml Transformation rules textbox.  

I don't recommend this as a permanent solution until version 2.* is fully released, but in a pinch, it may help you.

**Comment by davidhprotective** [comment]
Having the same issue. Changing task version to 2 does not work because it doesn't support json fileType. And specifying full version 1.206.0 gives complaint saying string does not match pattern of "^Powershell@2$"

**Comment by captainhook** [comment]
> EDIT:
> Specifying the full task version to force back to `1.206` worked:
> `- task: FileTransform@1.206.0`

How have you done this?
When I add it to the yml file, it shows this error: `String does not match the pattern of "^PowerShell@2$".`

Thanks

**Comment by chowarth** [comment]
> > EDIT:
> > Specifying the full task version to force back to `1.206` worked:
> > `- task: FileTransform@1.206.0`
> 
> How have you done this?
> When I add it to the yml file, it shows this error: `String does not match the pattern of "^PowerShell@2$".`
> 
> Thanks

@captainhook all we did was change the task version as above, that line was taken straight from the yaml file.

**Comment by captainhook** [comment]
> > > EDIT:
> > > Specifying the full task version to force back to `1.206` worked:
> > > `- task: FileTransform@1.206.0`
> > 
> > 
> > How have you done this?
> > When I add it to the yml file, it shows this error: `String does not match the pattern of "^PowerShell@2$".`
> > Thanks
> 
> @captainhook all we did was change the task version as above, that line was taken straight from the yaml file.

I tried exactly that and the pipeline won't run, error being: `Invalid step task reference FileTransform@1.206.0`

Very odd.

**Comment by FredericoHenrique** [comment]
We are still having the problem as the solutions don't work.

**Comment by wlkrt0** [comment]
We are still experiencing this issue. v2 preview workaround is working for our JSON substitution.

**Comment by richglezriv** [comment]
All our pipelines (api/ui) broke because of the change, this worked for us:
on linux agent we upgraded to version 2
- task: FileTransform@2
  inputs:
     folderPath: '$(System.DefaultWorkingDirectory)/folder_path'
     xmlTransformationRules:
     jsonTargetFiles: '**/the_file.json'
  displayName: 'File transform'

on windows agent we downgraded to the prev working version
- task: FileTransform@1.206.0
    displayName: 'File Transform'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)/folder_path'
      fileType: 'xml'
      targetFiles: 'app.config'

Hope this helps

**Comment by pixelnix** [comment]
+1 for this being a very urgent, production-impacting issue. Release Pipelines using this task are broken and cannot be reverted to 1.206 as we don't have control over the yaml definitions.

**Comment by tsangcomputing** [comment]
> 

![image](https://user-images.githubusercontent.com/74463522/188439961-5c164d0b-9841-474f-bec0-cb4f6b0cfc19.png)
Looks like MS have reverted back to 1.2.06.0 today

**Comment by nichollsc81** [comment]
@tsangcomputing this does not appear to be global though-  we're seeing a mix of .206 and .208 being pulled across our DevOps Orgs for new releases urrently

**Comment by nicksimmonds-lmk** [comment]
We're still seeing .208 on our pipelines.

**Comment by joerizza-tylertech** [comment]
We are still seeing this issue, it is breaking our deployments

**Comment by a-m-shaw** [comment]
We are also still seeing this issue and are now seeing much the same from the 2.* preview (2.206, to be specific) which we had briefly succeeded in using as a workaround. As such we are now completely dead in the water without either writing our own task plugin or manually scripting replacements, neither of which is an appealing proposition for the number of release pipelines that we have.

**Comment by nichollsc81** [comment]
@joerizza-tylertech @a-m-shaw we're seeing this exclusively on non-MS hosted agents - possible hacky workaround is to delete the cached file transform task from each deployment group VM. Depending on org scale, that may or may not get you out of a bind. Once the pipeline fails to detect the cached .208 task, it will download the .206 task. A better solution from MS might been to have rebuild the .206 task so that it incremented past .208, detected there was a 'newer' version, and downloaded the non-FUBAR version.

**Comment by a-m-shaw** [comment]
@nichollsc81 We tried manually removing 1.208 and found it got re-downloaded.

**Comment by swoopgrandchamp** [comment]
Same problem here. Deleted the cached folder, but still downloaded 1.208.

**Comment by deanmadden** [comment]
Is this going to be fixed or reverted? Please can we have some communication as this is an urgent problem.

**Comment by seantleonard** [comment]
Looks like some sort of update was committed https://github.com/microsoft/azure-pipelines-tasks/commit/fc020cf271c20e7e89a3f0a2d9dea271047456e7

@v-nagarajku can you provide any updates here?

**Comment by v-nagarajku** [comment]
@seantleonard , rolled out 1.211.0 that should work fine as like 1.206.0

**Comment by sbparsons** [comment]
Has this raised it's ugly head again?

Day 1: version 4.221.103 worked flawlessly
Day 2: version 4.223.0 fails with the same message as above...

I tested with a package that was currently deployed and working. I changed absolutely nothing. The redeployment of the exact same package now shows the warnings, and no variables have been substituted.

It's broken all our pipelines.

**Comment by onarres** [comment]
The trick is to send an empty string into `xmlTransformationRules`

example:
```
  - task: FileTransform@2
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/Foo'
              xmlTransformationRules: ''
              jsonTargetFiles: |
                appsettings.json
```
