### ISSUE TITLE
AzureResourceManagerTemplateDeployment - What-If

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/azure-pipelines-tasks#16837]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureResourceManagerTemplateDeployment

## Issue Description

It would be fantastic if this task supported the "what-if" option

**Comment by nnellans** [comment]
Anxiously awaiting this option as well.
