### ISSUE TITLE
Nunit | I want to set the value of priority to be dynamic

### ISSUE THREAD

**Issue by rehamkotb** [microsoft/azure-pipelines-tasks#16839]
I am using Nunit and I've to set a priority for each test case, but I need the value of priority to be Dynamic based on specific condition after first Run

**[Test, Property("Priority", "High")]**

So is there any way to make the Priority "High" dynamic instead of set it static ?

**Comment by KonstantinTyukalov** [comment]
Hi @rehamkotb, could you clarify what task you are using?
