### ISSUE TITLE
NodeToolV0 does not set proxy for non-explicit version lookup

### ISSUE THREAD

**Issue by piercemar** [microsoft/azure-pipelines-tasks#16844]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NodeToolV0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure DevOps Server 2020 Update 1.1 on-premises

- Agent - Private: v2.206.1 on Oracle Linux 8 and Windows Server 2019
    
## Issue Description

When running NodeToolV0 task behind a (corporate) proxy, it fails if version is not explicit.
The "queryLatestMatch" function does not properly initialize _restm.RestClient_ with the task's proxy config.

### Task logs

[non-explicit-version.log](https://github.com/microsoft/azure-pipelines-tasks/files/9494551/non-explicit-version.log)
[explicit-version.log](https://github.com/microsoft/azure-pipelines-tasks/files/9494553/explicit-version.log)

### Error logs

2022-09-05T21:00:36.0663491Z ##[debug]task result: Failed
2022-09-05T21:00:36.0691748Z ##[error]connect ETIMEDOUT 104.20.23.46:443
2022-09-05T21:00:36.0703402Z ##[debug]Processed: ##vso[task.issue type=error;]connect ETIMEDOUT 104.20.23.46:443
2022-09-05T21:00:36.0711494Z ##[debug]Processed: ##vso[task.complete result=Failed;]connect ETIMEDOUT 104.20.23.46:443

**Comment by KonstantinTyukalov** [comment]
Hi @piercemar thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon
