### ISSUE TITLE
Publish symbols fails with Encountered Win32 error '203' from method 'SymEnumSourceFiles'.

### ISSUE THREAD

**Issue by PeterKristiansen** [microsoft/azure-pipelines-tasks#16873]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishSymbolsV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Azure DevOps Pipelines 
    
    - A private project

- Private agent
   
    - Host machine is running Windows Server 2019 Standard

    - Agent version 2.206.1

## Issue Description

We see that the **Index sources and publish symbols - v2** task, started ending in warning back in May with this:
`##[warning]Library dbghelp.dll is already loaded from an unexpected path. Expected 'G:\T\a3\w\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.203.0\dbghelp.dll'. Actual 'G:\T\a3\w\_tasks\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\2.203.0\dbghelp.dll'.
##[error]Encountered Win32 error '203' from method 'SymEnumSourceFiles'.
`
On the surface at least it looks like this issue - though we are only experiencing it now https://github.com/microsoft/azure-pipelines-tasks/issues/13491.

The server is running McAfee as the virusscanner. We have verified that exempting the agent folders from virus scan had no effect on this issue. However disabling McAfee completely on the server made the issue go away.

As far as Windows updates the Servicing Stack 10.0.17763.2744 was rolled on in the period between last success and first failure.

We are unable to roll back the update and McAfee is the corporate wide chosen virus scanner on servers.

The Azure DevOps agent on its own does not appear to be the culprit. Back when the issue was detected we were running 2.200.2 - but 2.200.2 was also the agent used for the last succesful job.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
Please find the log attached as 13.zip

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
[13.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9554179/13.zip)

**Comment by isctays** [comment]
i have the same issue with no luck, we tried the task v1 and v2, same result.

we excluded the agent folders in mcafee. we gave agent user permissions with full control, but same issue.

Windows Server 2019 Datacenter
KB5022286
Agent Version: vsts-agent-win-x64-2.214.1

we have another Windows Server 2016, and it works there. but not over the windows 2019.

due to company policy i cannot disable the AV entirely, i will request to disable it just for testing porposes to see if that makes it work.

**Comment by isctays** [comment]
we disabled all security related to the AV, and it works now!

dont know what the AV is doing, but in the debug mode, i could see that besides the agent folders, the process internally uses the network service user, and part of the indexing of the symbols, there is a file being writen to the users app data temp folder:

C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp

which is not accesible without administrator permissions. so, i will give it a try to exclude this path on the AV and see how it behaves.

so far, i think this temp file should be created under the agent worker folder, to avoid any possible system access issue or blocking.

**Comment by jonathanchapmanmoore** [comment]
I turned off Windows Defender in group policy and it still doesn't work any help?

**Comment by jonathanchapmanmoore** [comment]
I got the symbols to build after downgrading to TFS 2018 and SQL Server 2017 Enterprise

![Untitled4](https://github.com/microsoft/azure-pipelines-tasks/assets/8218836/b10af463-1844-4fc1-8b4b-36ecca8c27fb)

**Comment by Shahyads** [comment]
I have the same issue. As a workaround you can go to the task folder on the agent machine then open the file DbghelpFunctions.ps1 then for each DllImport attribute in the Add-Type statement , add the   full path to the "dbghelp.dll" 

For example
"E:\\\\agent1\\\\_work\\\\_tasks\\\\PublishSymbols_0675668a-7bba-4ccb-901d-5ad6554ca653\\\\2.234.0\\\\dbghelp.dll"

See the pull request https://github.com/microsoft/azure-pipelines-tasks/pull/21171
