### ISSUE TITLE
Maven@3 task: [error]No agent found in pool which satisfies the specified demands: maven, Agent.Version -gtVersion 2.172.0

### ISSUE THREAD

**Issue by rhollins** [microsoft/azure-pipelines-tasks#16875]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven@3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
     It is azure devops 

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:  
    Ubuntu 18 and agent version is latest 2.210.0

## Issue Description

I get following error when running maven task on latest azure deopvs agent version running on ubuntu 
[error]No agent found in pool <pool_name> which satisfies the specified demands: maven, Agent.Version -gtVersion 2.172.0

$JAVA_HOME does exists but it's not found by agent and not showed in capabilities 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[error]No agent found in pool <pool_name> which satisfies the specified demands: maven, Agent.Version -gtVersion 2.172.0

[Insert error from the logs here for a quick overview]

**Comment by vmapetr** [comment]
Hi @rhollins,  thanks for reporting!
>Ubuntu 18 and agent version is latest 2.210.0
As I understand you are using self-hosted agent, right?
If so, could you please confirm that `mvn` binaries are also added to the `PATH` environment variable for the user that runs the agent?

**Comment by rhollins** [comment]
I think this can be close it is most likely lack of maven installed on the host however it was working before on the same host I assume something has changed in extension perhaps, Thanks
