### ISSUE TITLE
Xcode task args not parsed correctly

### ISSUE THREAD

**Issue by wAuner** [microsoft/azure-pipelines-tasks#16871]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: Xcode@5  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server 
- Agent - Hosted

## Issue Description

I'm using the Xcode@5 task with the test action and I'm providing additional args on the args option.
```
# 1 double quotes beginning/end
args: "-enableCodeCoverage YES -derivedDataPath /tmp/test-results OTHER_CPLUSPLUSFLAGS='$(inherited) -Wunused -Wunused-parameter'"
# 2 only single quotes
args: '-enableCodeCoverage YES -derivedDataPath /tmp/test-results OTHER_CPLUSPLUSFLAGS=''$(inherited) -Wunused -Wunused-parameter'''
```
When I specify the args either way the resulting command in the logs looks correct and when I copy it in my local terminal it works as expected (tested with zsh, bash and sh). However, for whatever reason the same generated command fails on the hosted agent because the `-Wunused` flag gets interpreted without the single quotes. It looks like the displayed command in the logs is not what is actually executed on the agent.

I don't know how else I am supposed to escape the single quotes within the `args` option in the yaml definition.

```
/usr/bin/xcodebuild -version
Xcode 13.4.1
Build version 13F100
/usr/bin/xcodebuild -sdk macosx -configuration Debug -project /Users/runner/work/1/s/MacOS/Source/uberAgent.xcodeproj -scheme uberAgent_Tests_CI test -enableCodeCoverage YES -derivedDataPath /tmp/test-results OTHER_CPLUSPLUSFLAGS='$(inherited) -Wunused -Wunused-parameter' CODE_SIGNING_ALLOWED=NO | /usr/local/lib/ruby/gems/3.0.0/bin/xcpretty -r junit --no-color
xcodebuild: error: invalid option '-Wunused'

Usage: xcodebuild [-project <projectname>] [[-target <targetname>]...|-alltargets] [-configuration <configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings [-json]] [<buildsetting>=<value>]... [<buildaction>]...

```

## Steps to reproduce
Create an Xcode task and specify an option with space separated values like the example above. 
```
args: "OTHER_CPLUSPLUSFLAGS='$(inherited) -Wunused -Wunused-parameter'"
```

**Comment by vmapetr** [comment]
Hi @wAuner !
Thank you for your report, 
Currently, we are working on more prioritized issues at the moment but will get back to this one soon.
