### ISSUE TITLE
##[error]Unable to find the location of Dac Framework (SqlPackage.exe) from registry on 

### ISSUE THREAD

**Issue by prat-ms** [microsoft/azure-pipelines-tasks#16890]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeployment@1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlAzureDacpacDeploymentV1/README.md

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent -  Private: 
 

## Issue Description

Our builds have started failing recently at dacpac deployment step. Previously all builds were running successfully and there are no changes in the build pipeline. It seems dacpac deployment component has changed.
The only difference in the successful builds and failing builds is the Azure SQL Database deployment version change from 1.202.0 to 1.209.0.
This is the task configuration: 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/112642455/190226194-69e9c88f-5799-452e-b247-5b896ad33029.png">
Is there any change expected with the new version of Azure SQL Database deployment component? And which VS version does it expects to be present in the build agent?  Currently we are having Microsoft Visual Studio\2019 installed on the agents.

### Task logs
`"D:\a\_work\1\b\2\_work\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.209.0\vswhere.exe" -version [15.0,18.0) -latest -format json
##[error]Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine 7d8c7c86c000000Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
`
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

<img width="703" alt="image" src="https://user-images.githubusercontent.com/112642455/190225887-65a29e07-025d-4b87-a5df-66ee79aa939b.png">

**Comment by prat-ms** [comment]
Hi @v-nagarajku, do we have any update on this issue?

**Comment by btmpn** [comment]
we are experiencing the same problem for some days.

The last time it worked it used task version 1.202.0 last tuesday morning (13.09.2022 07:22 german time) - all worked fine.

The next deployment used task version 1.209.0 last wednesday morning (14.09.2022 07:25 german time) which failed with the same problem as mentioned by @prat-ms.

I hope there will be a fix soon...

**Comment by Kittoes0124** [comment]
This is due to some yet to be determined issue with the detection of the DacFx framework after bumping the Visual Studio version check to support VS2022. On self-hosted agents, the issue can be resolved by installing the framework manually (we used https://aka.ms/dacfx-msi, sourced from [here](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16))

**Comment by btmpn** [comment]
> This is due to some yet to be determined issue with the detection of the DacFx framework after bumping the Visual Studio version check to support VS2022. On self-hosted agents, the issue can be resolved by installing the framework manually (we used https://aka.ms/dacfx-msi, sourced from [here](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16)).

@Kittoes0124 thank you. This worked.

**Comment by msjf** [comment]
That does not work on machines we cannot log on. The fix is to consider multiple places for the dac pac installation to be and to fallback to previous versions of visual studio.

**Comment by Kittoes0124** [comment]
> That does not work on machines we cannot log on. The fix is to consider multiple places for the dac pac installation to be and to fallback to previous versions of visual studio.

The code [already does so](https://github.com/microsoft/azure-pipelines-tasks/blob/bdf130c99105fbbc673c50ad52c07c9f8a150b86/Tasks/SqlAzureDacpacDeploymentV1/FindSqlPackagePath.ps1#L1-L59). I didn't write any it (unless you count bumping a 17 to an 18), but am going to guess that something breaks down within [this block](https://github.com/microsoft/azure-pipelines-tasks/blob/bdf130c99105fbbc673c50ad52c07c9f8a150b86/Tasks/SqlAzureDacpacDeploymentV1/FindSqlPackagePath.ps1#L36-L49).

**Comment by v-nagarajku** [comment]
@Kittoes0124  - was this PR tested locally before merging it?.

**Comment by msjf** [comment]
Only the latest visual studio install directory is considered : Invoke-VstsTool -FileName "$PSScriptRoot\vswhere.exe" -Arguments "-version [15.0,17.0) -latest -format json

**Comment by prat-ms** [comment]
@msjf As a workaround, I was able to fix the issue by adding a Powershell task to install DacFx framework just before DacPac deployment step like below:
```
$msiFilePath = "DacFramework.msi"
Invoke-WebRequest "https://aka.ms/dacfx-msi" -OutFile $msiFilePath
             
$MSIArguments = @(
    "/i"
    ('"{0}"' -f $msiFilePath)
    "/qn"
    "/norestart"
)               
Start-Process "msiexec.exe" -ArgumentList $MSIArguments -Wait -NoNewWindow
Remove-Item -Path $msiFilePath  -Force
```
<img width="664" alt="image" src="https://user-images.githubusercontent.com/112642455/192552721-28e45f7e-e26b-4918-8e58-4989c5fe4a0c.png">

**Comment by msjf** [comment]
thanks for the tip. We already invoke the VS 2022 DacPac with a hardcoded path from a powershell script. That being said, I'd really like to ge tthe ADO task fixed.

**Comment by msjf** [comment]
> > The fix is to consider multiple places for the dac pac installation to be and to fallback to previous versions of visual studio.
> 
> The code [already does so](https://github.com/microsoft/azure-pipelines-tasks/blob/bdf130c99105fbbc673c50ad52c07c9f8a150b86/Tasks/SqlAzureDacpacDeploymentV1/FindSqlPackagePath.ps1#L1-L59). I didn't write any of it, unless you count bumping a 17 to an 18, but am going to guess that something breaks down within [this block](https://github.com/microsoft/azure-pipelines-tasks/blob/bdf130c99105fbbc673c50ad52c07c9f8a150b86/Tasks/SqlAzureDacpacDeploymentV1/FindSqlPackagePath.ps1#L36-L49).

For me, the "-latest" of vswhere invocation only returns information fro VS2022, while we may want to fallback to 2019, 2017 .... or whichever version is installed on the machines.

**Comment by msjammu** [comment]
Reporting same issue.
