### ISSUE TITLE
VSTest should not set additional adapter path to / by default

### ISSUE THREAD

**Issue by nohwnd** [microsoft/azure-pipelines-tasks#16915]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature?
**Enter Task Name**: VSTest3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
Azure pipelines, Hosted or unhosted, it is specific to the task.

## Issue Description

VSTest task is setting `pathtoCustomTestAdapters:` to the repo root for "compatibility", which makes vstest discover exentensions in all dlls across the whole repo. This has two problems: 

- The scanning is slow, and can up to a minute on big repos.
- Repos often mix tests from different target frameworks, and adapter for the incorrect tfm (e.g. netcoreapp3.1) can be picked up by another tfm (e.g. net472), which makes tests undiscoverable.
 

@Rameshkg07 I saw you created VSTest3, I think that is a good opportunity to do this change. We have multiple bugs reported to vstest team about this behavior. Can you help me here, please?

### Task logs

I don't have logs.

**Comment by nohwnd** [comment]
This is not stale, and is still an issue.

**Comment by Evangelink** [comment]
Not stale, some customers are facing the same issue. @rasunkar Could you please reopen and bump priority?

**Comment by nohwnd** [comment]
The proposed fix here is to simply stop providing the adapter path `/`. This option likely benefits almost no-one, and they have an easy fix if they get broken, they just add the parameter that specifies it.

**Comment by abpiskunov** [comment]
At least when vstest prints that tests were not discovered, it needs to suggest to use pathtoCustomTestAdapters: as a workaround, if the main problem could not be fixed properly. 

In our case it was "bad luck" in terms of order in which we specified assemblies and net6.0 assembly was coming first and its folder was used for searching for additional adapters. After using pathtoCustomTestAdapters to point to some another existing folder (even without adapters) did work.

**Comment by nohwnd** [comment]
Another customer reporting issue with this: https://github.com/microsoft/vstest/issues/2245#issuecomment-1809865544

**Comment by nohwnd** [comment]
@rasunkar Yeat another ping on this one, we've seen another issue caused by this, please drop this "feature".

**Comment by nohwnd** [comment]
This is still a problem for our customers. Can I get some conclusion please?
