### ISSUE TITLE
Pipeline build trigger via webhook

### ISSUE THREAD

**Issue by im-hamza-dev** [microsoft/azure-pipelines-tasks#16925]
I have a Azure Repository which is managed on azure pipeline and releases. Its a Gatsby project integrated with Contentful ( headless CMS ). So I want to create build hook ( web-hook ) that can trigger my azure build pipeline from contentful changes.
But so far I unable to find this feature in Azure Pipelines and Deploy settings.

**Comment by max-zaytsev** [comment]
@im-hamza-dev this repo is mostly for pipeline tasks support - I would suggest opening a ticket on https://developercommunity.visualstudio.com/search?space=21 for Azure DevOps related questions to get the right eyes on it.
