### ISSUE TITLE
GitHubCommentV0: Support for the recommended azure pipelines app service connection

### ISSUE THREAD

**Issue by CloudPlatformer** [microsoft/azure-pipelines-tasks#16938]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Enter Task Name**: GitHubCommentV0 

## Environment
- Server - Azure Pipelines

- Agent - Hosted: 
    
    - windows-2022
 
## Issue Description

The GitHubCommentV0 task does not currently allow Azure Pipelines GitHub App service connections to be used.

As per https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#github-app-authentication:

> The Azure Pipelines GitHub App is the recommended authentication type for continuous integration pipelines.

This would be ideal so the comments on pull requests/issues (and the service connections themselves) are not tied to an individual and instead the author is `azure-pipelines`.

As explained by @thesattiraju on https://github.com/microsoft/azure-pipelines-tasks/pull/13012#discussion_r435701358, the `InstallationToken` type needs to be allowed for the [gitHubConnection parameter](https://github.com/microsoft/azure-pipelines-tasks/blob/b0e99b6d8c7d1b8eba65d9ec08c118832a5635e3/Tasks/GitHubCommentV0/task.json#L23) for a 'Review App' scenario to work. In the 'Review App' scenario, the [githubEndpointObject.scheme falls under the Token implementation](https://github.com/microsoft/azure-pipelines-tasks/blob/b0e99b6d8c7d1b8eba65d9ec08c118832a5635e3/Tasks/GitHubCommentV0/main.ts#L18)

However, when using the GithHubCommentV0 task as a task within a pipeline the githubEndpointObject.scheme is InstallationToken and the task errors.

### Task logs

>2022-09-22T09:39:19.7882917Z ##[debug]Endpoint scheme: InstallationToken
2022-09-22T09:39:19.7898436Z ##[debug]task result: Failed
2022-09-22T09:39:19.7930847Z ##[error]Unhandled: Invalid GitHub service connection scheme: InstallationToken. Only Token, OAuth and GitHub personal access token connections are allowed.
2022-09-22T09:39:19.7940543Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Invalid GitHub service connection scheme: InstallationToken. Only Token, OAuth and GitHub personal access token connections are allowed.
2022-09-22T09:39:19.7947674Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Invalid GitHub service connection scheme: InstallationToken. Only Token, OAuth and GitHub personal access token connections are allowed.

### Error logs

>##[error]Unhandled: Invalid GitHub service connection scheme: InstallationToken. Only Token, OAuth and GitHub personal access token connections are allowed.

**Comment by jack-cloud-platform** [comment]
This has been raised previously but was closed https://developercommunity.visualstudio.com/t/githubcomment-unable-to-use-the-service-connection/1586041
