### ISSUE TITLE
NugetCommand restore with -LockedMode

### ISSUE THREAD

**Issue by stephenjust** [microsoft/azure-pipelines-tasks#16948]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Add option to NugetCommand task to allow restoring in locked mode

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines

- Agent - Hosted + Private

## Issue Description

For the NugetCommand@2 task, there does not appear to be a way to pass the -LockedMode option to nuget.exe.
This causes nuget restore to update a package lock file during pipeline build rather than failing if the lock file is out of date.

If such an option already exists, it is not listed at https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines

### Task logs

N/A

## Troubleshooting
N/A

### Error logs
N/A

**Comment by jmyersmsft** [comment]
Sorry, but [we are no longer taking new features in the NuGetCommand task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines#remarks). We recommend using the NuGetAuthenticate task and a script task of your choosing that calls NuGet with whatever options you want to pass.

**Comment by IanIsFluent** [comment]
> Sorry, but [we are no longer taking new features in the NuGetCommand task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines#remarks). We recommend using the NuGetAuthenticate task and a script task of your choosing that calls NuGet with whatever options you want to pass.

Sorry, I don't understand this answer. Why do I need anything to do with authentication? I just want to be able to use a cache to restore my NuGet packages.

Is there some more up-to-date documentation as to how to cache and restore NuGet packages in my Azure Devops pipeline?

**Comment by mattfrear** [comment]
For future readers

`Nuget.exe restore` supports `-LockedMode`

https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/cli-reference/cli-ref-restore.md

Not sure if that works with NuGetCommand@2?
