### ISSUE TITLE
Birth Certificate steps in windows hosted agents

### ISSUE THREAD

**Issue by roofiq** [microsoft/azure-pipelines-tasks#16941]
Hey, from 16.09 our pipelines that run on windows hosted agents have three additional steps included, that are not defined in the pipeline itself.
- Generate Birth Certificate
- Publish Birth Certificate artifact
- Add Birth Certificate to all Csharp projects

![image](https://user-images.githubusercontent.com/44588684/191727538-c427d8c0-b17c-4f6a-8c6b-9b25a8341149.png)

I can't find any information about it. Why it's included, what is the purpose of it and how it could be removed?

Thanks,
Rafal

**Comment by max-zaytsev** [comment]
Closing this issue, since it's not related to any of the in-the-box tasks from this repo.
As I see, you've already opened a [ticket](https://developercommunity.visualstudio.com/t/Birth-Certificate-steps-in-windows-hoste/10156085) in dev community. Please check there for updates.
