### ISSUE TITLE
GulpV1 doesn't recognise system capability of node.js

### ISSUE THREAD

**Issue by NickGraham101** [microsoft/azure-pipelines-tasks#16950]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gulp

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the 
      - account name: nickgraham101
      - team project name: TestProject
      - build definition name/build number: testprojects-bin / 3315

- Agent - Hosted or Private: 
    
    - If using private agent, provide the 
      - OS of the machine running the agent: Debian GNU/Linux 10 (buster)
      - the agent version: 2.210.1

## Issue Description

When attemping to run a pipeline job with the Gulp@1 task on a self hosted agent with the `node.js` system capability with a value of `/usr/bin/node` the job doesn't start and an error of `No agent found in pool GandTPool which satisfies the specified demands: node.js, Agent.Version -gtVersion 2.163.1` is returned.  If a user capability of `node.js` with a value of `true` is added to the agent and the job is reran it succeeds

### Task logs

![image](https://user-images.githubusercontent.com/34914709/192096051-a5b87bda-a8a7-49f9-b04b-dc0755fb55f6.png)

[logs_3320.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9638609/logs_3320.zip)

**Comment by max-zaytsev** [comment]
Hi @NickGraham101, thank you for reporting the issue. We've added this feature request to our backlog. We'll take a look at it once we have enough capacity.

**Comment by NickGraham101** [comment]
@max-zaytsev I think this might be an issue between Azure DevOps and the Kubernetes pod that my self hosted agents runs in rather than the Gulp task.  The issue only seems to occur if a job starts immediately after another one finishes.  The pod is configured to complete once the first job is finished and a fresh pod starts up.  It seems there is some sort of delay in Azure DevOps recognising the new pod has a capability and it kills the pipeline job and throws the error listed above.  If there is a short gap between jobs the gulp task runs fine
