### ISSUE TITLE
MSBuild Task vs VSBuild Task web.config output behavior

### ISSUE THREAD

**Issue by omatrot** [microsoft/azure-pipelines-tasks#16968]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: MSBuild@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
 > https://rtetech.visualstudio.com/SafeProtect/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=15&branch=Angular-13

Account name: olivier.matrot

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure PipeLines

## Issue Description

I am having trouble understanding the different output behavior between a MSBuild@1 task vs a VSBuild@1 task for an ASP.NET Core Web API project (not a solution) for the web.config generated file.

with an assembly name of RTE.Technologies.SafeProtect.WebAdmin.Api, for the VSBuild@1 task, the aspNetCore XML node is:

```
<aspNetCore processPath="dotnet" arguments=".\RTE.Technologies.SafeProtect.WebAdmin.API.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess">
        <environmentVariables>
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Test" />
        </environmentVariables>
      </aspNetCore>
```
which is correct.

But with the MSBuild@1 the same XML node contains:

```
<aspNetCore processPath="dotnet" arguments=".\RTE.Technologies.SafeProtect.WebAdmin.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess">
        <environmentVariables>
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Test" />
        </environmentVariables>
      </aspNetCore>
```

Which is incorrect. The **API** part is missing from the assembly name. Of course this prevents the application to start because it looks for an assembly that does not exists.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[logs_1347.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9664929/logs_1347.zip)

**Comment by DenisRumyantsev** [comment]
@omatrot thanks for this question, we will investigate it
