### ISSUE TITLE
Cannot Email "RM_Customer_Queries at microsoft dot com"

### ISSUE THREAD

**Issue by NdUzr** [microsoft/azure-pipelines-tasks#16965]
I saw an issue on here with exactly my issue (#2806), so I thought it might be appropriate for me to ask the same.
That said I am coming to this from ServiceNow - I need support with the ServiceNow Store Azure Pipelines plugin/app. On the store page it directs questions to RM_Customer_Queries@microsoft.com. All my emails (work and gmail) to this address receive NDR/DSN bounce message (fyi: 550 5.1.0||5.4.1).
Does anyone have any advice on if this is still a valid MS (support) email address?

Thanks,Matt

**Comment by CiaraSHoulihan** [comment]
I am also having the same issue!
