### ISSUE TITLE
DotNetCoreCLITask doesn't run assemblies in parallel

### ISSUE THREAD

**Issue by Skintkingle** [microsoft/azure-pipelines-tasks#16972]
**Question, Bug, or Feature?**  
*Type*: Bug/Feature

**Enter Task Name**: DotNetCoreCLI@2

## Environment
- Server - Azure Pipelines

- Agent - Private: Windows server 2019 version 1809

## Issue Description

using the DotNetCoreCLITask to run tests by setting the `command` to `test` results in sequential test execution and not parallel, as described in this [github issue in the vstest github](https://github.com/microsoft/vstest/issues/1851). We're looking to run assemblies in parallel and would also like to use the dotnet task.

**Comment by kescherCode** [comment]
Stale bots continue to be a plight upon issue reporters that report issues that are never fixed.

This is still an issue.
