### ISSUE TITLE
Xcode Task: Support for Xcode 14

### ISSUE THREAD

**Issue by Sam-Spencer** [microsoft/azure-pipelines-tasks#16982]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: XcodeV5  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/XcodeV5

## Issue Description

Need support for Xcode 14. Azure will not build and archive iOS apps built with Xcode ≥ 14.

**Comment by jacobbullock** [comment]
Is there any timeline on this?

**Comment by acoutts** [comment]
I see xcode 14 is available now. Actually my builds are failing because of something in xcode 14 and in my log output I see it is indeed using xcode 14 to build.

https://github.com/fastlane/fastlane/issues/20701

**Comment by Adnan1990** [comment]
I am also facing issue while running pipeline  for application built on Xcode 14.0.1.Xcode 14.0.1  Build version 14A400

**Comment by Daemonson** [comment]
https://github.com/fastlane/fastlane/issues/20810#issuecomment-1303004100

**Comment by MichielvanBeers** [comment]
Any updates on this? Xcode 14.0 has been out for almost 4 months and we would really like to upgrade our development environments to support this, but we cannot since our pipeline can only run Xcode 13. Thanks!

**Comment by jacobbullock** [comment]
@MichielvanBeers are you still having issues? We just recently got all of our iOS 14 build issues fixed.   

I think that this Issu can be closed.

**Comment by woodrufs** [comment]
@jacobbullock,
What does your pipeline look like if you don't mind me asking? I attempted to target Xcode 14 for building our iOS app this morning, and the build task failed due to azure not finding Xcode 14. The only reason why I attempted to upgrade was the fact that Apple is requiring all builds for app updates be built with Xcode 14 starting next month. From what I am seeing, Xcode 14 is still not supported with the Xcode task.

**Comment by jacobbullock** [comment]
@woodrufs what Mac OS image are you using. Might be easier to help if I see your pipeline. I'll share mine here when I get to my office

**Comment by woodrufs** [comment]
@jacobbullock - you beat me to it! I was using the macOS-11 vm. I bumped it to 12 and by default it picked up Xcode 14.2. Thank you!

@MichielvanBeers - Verify you're running on a macOS-12 VM. That was my issue.

**Comment by MichielvanBeers** [comment]
Thanks! I'll check it and get back to you

**Comment by MichielvanBeers** [comment]
Everything works as expected, thanks a lot! Is there a roadmap known or a channel that I can subscribe to see when support for future Xcode and MacOS version will be implemented? Thanks in advance!

**Comment by sparethme** [comment]
> @woodrufs what Mac OS image are you using. Might be easier to help if I see your pipeline. I'll share mine here when I get to my office

Hey @jacobbullock , do you mind still sharing your pipeline? 

I'm experiencing something similar to what I think you reported here: https://developercommunity.visualstudio.com/t/Xcode-141-keeps-failing-to-build-withou/10213879?q=xcode&sort=newest&page=1

And despite trying something along the lines of what you suggested here:https://github.com/actions/runner-images/issues/6642#issuecomment-1479555507, 

I'm still having issues. Any suggests would be most appreciated. Thank you.
