### ISSUE TITLE
Docker push issue: `No message found for this issue`

### ISSUE THREAD

**Issue by james-ro-williams** [microsoft/azure-pipelines-tasks#16995]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Docker@2

## Environment
- Azure DevOps Server 2020 Update 1.1

- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    - OS: Ubuntu 18.04
    - Agent Version: VSTS-Linux x64 2.170.1

## Issue Description
Error when running the Docker@2 push task when pushing to a private Azure Container Registry linked through service connection. Error being flagged up in the UI with the message: `No message found for this issue`.

Upon investigation, this seems to be sourcing from an SSL certificate error when attempting to push to Image Details Artifact Store. I can't find any documentation on this error online, and our images successfully make it to the ACR. Since I can't find any documentation, it's very hard to know which certificates need to be installed, and I have the root and intermediate certs for my domain already installed on the agent host box.

### Task logs
[error.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9696089/error.zip)

**Comment by cjayneb** [comment]
Getting the UI error message `No message found for this issue` when using Docker@2 buildAndPush, BUT no apparent error in the step execution. Not urgent but makes it seem like our pipeline runs fail when they don't actually.

See below :

<img width="1227" height="823" alt="Image" src="https://github.com/user-attachments/assets/98b85a63-85b7-4973-9412-d64787c26984" />
