### ISSUE TITLE
Is it possible to download artifacts inside single organization for other projects by project name (not GUID)?

### ISSUE THREAD

**Issue by svirchenko** [microsoft/azure-pipelines-tasks#16999]
I'd like to build pipeline to download build artifacts inside single organization for other projects (not GUID) according to doc https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops.

Is it possible at all? or I should always specify "Id" from https://learn.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-6.0&tabs=HTTP

**Comment by svirchenko** [comment]
Hi @sergey-koryshev. Thank you

**Comment by sergey-koryshev** [comment]
@svirchenko do you have another questions? Can the issue be closed?

**Comment by svirchenko** [comment]
@sergey-koryshev no, thank you. I'll close the issue
