### ISSUE TITLE
Cache@2 is unable to use cache from main scope.

### ISSUE THREAD

**Issue by ChanceyC** [microsoft/azure-pipelines-tasks#16998]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question(bug?)

**Enter Task Name**: cache@2

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CacheV2

## Environment
- Server - Azure Pipelines   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Account: dev-mc
Project: Minecraft
definitionId=2770

build numbers:
11841620 - Original Main run
11843424 - Run on working/feature branch
11843789 - Rerun on Main

- Agent - Hosted or Private:     
    - If using Hosted agent, provide agent queue name:
Pool: [Azure Pipelines](https://dev-mc.visualstudio.com/DefaultCollection/4a14dd0d-3504-48d3-b8a8-248af2e13f1a/_settings/agentqueues?poolId=&queueId=1103)
Image: internal-macos-11
Agent: Azure Pipelines 23

## Issue Description

When running the `cache@2` task, runs on working/feature branches are not able to pull from the `main` scope.

Based on the description here: https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#ci-manual-and-scheduled-runs

I would expect that after the original run on main for CI, that a follow-up pipeline is able to pull from the main scope.

I've seen from previous issues that this should be available i.e. https://github.com/microsoft/azure-pipelines-tasks/issues/13666,  https://github.com/microsoft/azure-pipelines-tasks/issues/12503, https://github.com/microsoft/azure-pipelines-tasks/issues/11374.

Most of these use the `master` terminology for the default/branch head. Our repository, which is a github repository has `main` as the default/head. Our pipeline definition also has this set as their default branch for runs. Is it possible this is the cause of the inability to grab the cache from the existing scope?

Our use case is for a large amount of relatively short-lived branches that get pr'd and ran on CI in main, and the cache savings are in order of magnitude multiple hours. 

Is there anything that we can change to enable the behavior? 

### Task logs

They should be available for the posted follow-up build id's (not the original main run.)

[Original Main Run.txt](https://github.com/microsoft/azure-pipelines-tasks/files/9708989/Original.Main.Run.txt)
[Feature Run.txt](https://github.com/microsoft/azure-pipelines-tasks/files/9708990/Feature.Run.txt)
[ReRun on main.txt, truncated](https://github.com/microsoft/azure-pipelines-tasks/files/9708991/ReRun.on.main.txt)

**Comment by johnterickson** [comment]
I think there might be a gap where integration with GitHub is not propagating the default branch and so we default back to `master`.

**Comment by ChanceyC** [comment]
I did a few test runs with a temporarily created `master` branch and it does seem to have the cache fallback behavior. 


Publish configuration builds only: 
Definition id: 3504
Run id: 11953938
Run id: 11954761

Is there anything we can do on our end to propagate the default branch? 

We are using `main` as our default as part of our efforts to remove harmful terminology within our owned codespaces. 

If there is not a way to propagate the intended default branch are there viable solutions within the azure-task/ server side such as:

- Adding `main` as a fallback branch similar to how `master` behaves, where if not found under `master`, `main` is queried? I imagine this will become a more frequent issue as more repositories default to `main`, especially those hosted by github as it is the new default. 

- Adding a "read_scope" field to the `cache@2` such that the task can be configured to read from any branch scope? I imagine this could wind up tricky to do, but would offer a lot of flexibility for different repository configurations.

**Comment by chrisbehanna** [comment]
> I think there might be a gap where integration with GitHub is not propagating the default branch and so we default back to `master`.

Per D&I, we are supposed to default to `main` these days, as GitHub itself does when you create a new repository.  Is this going to be fixed anytime soon?  If it would help, we can submit a PR, if you'll tell us where to find the appropriate repo.

Chris BeHanna
cbehanna@microsoft.com
Minecraft Bedrock Build Engineering Lead

**Comment by Turbofroggy** [comment]
@johnterickson any update on this?

**Comment by johnterickson** [comment]
I'm working on a PR for this:
> Adding main as a fallback branch similar to how master behaves, where if not found under master, main is queried? I imagine this will become a more frequent issue as more repositories default to main, especially those hosted by github as it is the new default.

This one is trickier:
> Adding a "read_scope" field to the cache@2 such that the task can be configured to read from any branch scope? I imagine this could wind up tricky to do, but would offer a lot of flexibility for different repository configurations.

The scopes are provided by the server and the client is untrusted - otherwise a fork PR build could include a change in the YAML giving itself access to things it shouldn't.  Main worry there is `write` access, so there's a possibility to do something with read access - hmm...
