### ISSUE TITLE
Publish Profile deployment with zip package - No such deploying method exists

### ISSUE THREAD

**Issue by Abrissirba** [microsoft/azure-pipelines-tasks#17006]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: Azure App Service Deployment (AzureRmWebAppDeployment)

## Environment
Azure
Account name: sxtrainee
Project name: Trainee-Eliasz
Release definition: DatingApp

## Issue Description

we are trying to create a release definition in Azure DevOps. 

We choosed the "Azure App Service Deployment".

We are trying to use the Connection Type: Publish Profile

We have an artifact that contains a zipped folder of the application that we want to deploy. The artifact also includes a .pubxml file with <WebPublishMethod>ZipDeploy</WebPublishMethod>.

Not sure if I look in the correct location but I searched the repo for "No such deploying method exists" and found this
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/operations/PublishProfileUtility.ts#L73

From what I can see that only checks for MSDeploy.

Is it possible to use ZIP deploy with a publishing profile?

### Task logs
[tasklog_9.log](https://github.com/microsoft/azure-pipelines-tasks/files/9722466/tasklog_9.log)

### Error logs

Error : No such deploying method exists

**Comment by samusaran** [comment]
I have the same issues. It seems it's not possible to do a ZipDeploy with PublishProfile, even if the publish profile is perfectly valid.

**Comment by Xavina** [comment]
Hi,

I also have this issue, this is my task definition:

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    azureSubscription: 'whatever-api' (Service connection using 'using publish profile based authentication')
    PublishProfilePath: './/PublishProfiles/whatever-api - Zip Deploy.pubxml'
    PublishProfilePassword: 'xxxxxx'
    appType: 'apiApp'
    deployToSlotOrASE: true
    ResourceGroupName: 'xxxxx'
    SlotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/Output/xxxx.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'

**Comment by samusaran** [comment]
Hi @Xavina , i've created a new issue so it would have more visibility. https://github.com/microsoft/azure-pipelines-tasks/issues/18538

Can you comment there also? Thanks!

**Comment by v-mohithgc** [comment]
@samusaran @Xavina are you seeing this error even in previous version of the task?

**Comment by Xavina** [comment]
@v-mohithgc , no, I think previous versions doesn't allow to use 'Publish Profiles', maybe I am wrong, can you suggest a version to use that functionality?

Many thanks,
Xavier

**Comment by v-mohithgc** [comment]
> @v-mohithgc , no, I think previous versions doesn't allow to use 'Publish Profiles', maybe I am wrong, can you suggest a version to use that functionality?
> 
> Many thanks, Xavier

@Xavina no, I meant did previous runs of the same task succeed before? for example, task version 4.223.2 is showing this error, can you check your pipeline run history and verify if this task with same settings succeeded in version 4.221.0 or below versions?

**Comment by Xavina** [comment]
@v-mohithgc , ahhhh, no, it always has failed.

**Comment by samusaran** [comment]
I never actually used `Publish Profile` until now, since this is the first time I'm deploying to a third party subscription, and I'm not able to use a Service Principal link.
