### ISSUE TITLE
New K8s Service Connection results in "Length of 'endpoint.Authorization.Parameters' is invalid"

### ISSUE THREAD

**Issue by Abe-Froman** [microsoft/azure-pipelines-tasks#17017]
Breaking completely from the template as this is related to service connection and not a pipeline task but creating the issue here as @kmkumaran has added the release tag to a similar post in the past.

Trying to create some new service connections and getting the error:

`Length of 'endpoint.Authorization.Parameters' is invalid. It must be between 0 and 20480 characters. Parameter name: endpoint.Authorization.Parameters`

Here's a screenshot of the dialog:
![image](https://user-images.githubusercontent.com/18315896/194668004-b4c0b79d-d160-4bda-9a89-eba528753c59.png)

This method has worked for me in the past. Thanks in advance for any help.

**Comment by ankittkamal** [comment]
i had the same issue, what i did to resolve this issue was that in KubeConfig file, the last line is token : , i reduced the length of token , and then this error is resolved.

**Comment by marc-wilson** [comment]
I resolved the issue by getting rid of my local context (docker-desktop). Once I only pasted in the KubeConfig that applied to my AKS cluster, it worked.
