### ISSUE TITLE
Publish using webdeploy options are supported only when using Windows agent even though my publish profile use ZipDeploy

### ISSUE THREAD

**Issue by mrtrandinhvn** [microsoft/azure-pipelines-tasks#17028]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment@4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: I can't provide those information.

- Agent - Hosted.
## Issue Description
My publish profile looks like this but when I use this task it keeps telling me that `Publish using webdeploy options are supported only when using Windows agent`. I know that I'm using an ubuntu image but I don't use webdeploy and don't want to use webdeploy. I want to use zipDeploy.
```
<Project>
  <PropertyGroup>
    <WebPublishMethod>ZipDeploy</WebPublishMethod>
    <PublishProvider>AzureWebSite</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish>xxxxxxxxxxxxx</SiteUrlToLaunchAfterPublish>
    <LaunchSiteAfterPublish>true</LaunchSiteAfterPublish>
    <ProjectGuid>xxxxxxxxxxx</ProjectGuid>
    <PublishUrl>xxxxxxxxxxxx</PublishUrl>
    <UserName>xxxxxx</UserName>
    <_SavePWD>true</_SavePWD>
  </PropertyGroup>
</Project>
```
![image](https://user-images.githubusercontent.com/11169633/195246906-1688befe-7cbc-49ef-bb8c-97fe6dd209fb.png)
![image](https://user-images.githubusercontent.com/11169633/195246665-681e73c5-9bf0-4b94-9ee0-57a1454a6552.png)

### Task logs
```
Starting: Deploy to eri-test-prod1 - Zip Deploy
==============================================================================
Task         : Azure App Service deploy
Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
Version      : 4.209.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azureappservicetroubleshooting
==============================================================================
##[error]Error: Publish using webdeploy options are supported only when using Windows agent
Finishing: Deploy to eri-test-prod1 - Zip Deploy
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
Starting: Deploy to eri-test-prod1 - Zip Deploy
==============================================================================
Task         : Azure App Service deploy
Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
Version      : 4.209.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azureappservicetroubleshooting
==============================================================================
##[error]Error: Publish using webdeploy options are supported only when using Windows agent
Finishing: Deploy to eri-test-prod1 - Zip Deploy
```

**Comment by samusaran** [comment]
Have you ever solved this issue?
