### ISSUE TITLE
/p:BlockOnPossibleDataLoss=false ignored on deployment when data present

### ISSUE THREAD

**Issue by rebeccastarr** [microsoft/azure-pipelines-tasks#17030]
**Question, Bug**  
*Type*: I am trying to understand the expected behaviour of setting the value 'Block incremental deployment if data loss might occur'. I have read a similar post here, which was then closed without verifying the expected behaviour: https://github.com/microsoft/azure-pipelines-tasks/issues/11191 

**Enter Task Name**: sqlpackage.exe, DACPAC

## Environment
- Local Visual Studio trying to publish to MSSQLLocalDB instance
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.2.6
- Azure DevOps pipelines also experiencing exact same behaviour

## Issue Description

We are using Azure DevOps pipelines to automate the deployment of our database to multiple environments. If we specify the /p:BlockOnPossibleDataLoss=False the deployment fails if the table contains data. I can emulate this process locally. As per the recommendations by the post here: https://github.com/microsoft/azure-pipelines-tasks/issues/11191 I have also configured the following settings:

BlockOnPossibleDataLoss=false 
AllowDropBlockingAssemblies=true 
TreatVerificationErrorsAsWarnings=true

In my scenario, I am trying to DROP a date column from a table. This table contains data, and cannot be purged as we have FK references in child tables which also contain data.

To emulate the pipeline deployment process, in Visual Studio, I publish our main branch to a local MSSQLLocalDB instance. I then get the branch that we are trying to upgrade to and 'Generate Script'. Regardless of whether the above configs are specified, I still can see the following in the publish script (and the exact same is scripted when the above configurations are inversed):

`/*
The column [ref].[TableMapping].[UpdateDate] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [ref].[TableMapping])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
`
I read that object dependencies could contribute to causing the issue, and the column in question was NOT NULL and also had a DEFAULT constraint. I removed the default constraint and set the column to NULL. But still the same issue.

The closing post on the linked issue claims the below. I am trying to understand what this means exactly. So if "BlockOnPossibleDataLoss" is set to TRUE, then it will fail validation if the table contains data or not. Whereas if set to FALSE, it would only fail if the table contains data? Is this correct? So if set to TRUE, you are essentially preventing ANY schema modifications that could result in losing data if data was indeed present (table or column DROPS, column data type changes). If FALSE, then the schema modification would be allowed, but only if the table being modified is empty of data? Therefore, in the scenario where a table contains data, you cannot make any modifications to it via a deployment using sqlpackage.exe and DACPAC? You will HAVE to drop the data (in integration environments, pre-prod or prod this is never going to be possible), or you have to create your own deployment scripts for this purpose? Could you please clarify what the exact behaviour is expected when the table contains data as I am still not clear on this?

[dzsquared](https://github.com/dzsquared) commented [on 5 Feb 2021](https://github.com/microsoft/azure-pipelines-tasks/issues/11191#issuecomment-774302543)
Hi folks, we have clarified the property "BlockOnPossibleDataLoss" in the SqlPackage documentation as a deployment will still exit/fail if actual data exists on the database that will be impacted by changes when the property is set to false.
https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver15#properties-specific-to-the-publish-action

“Specifies that the operation will be terminated during the schema validation step if the resulting schema changes could incur a loss of data, including due to data precision reduction or a data type change that requires a cast operation. The default (True) value causes the operation to terminate regardless if the target database contains data. An execution with a False value for BlockOnPossibleDataLoss can still fail during deployment plan execution if data is present on the target that cannot be converted to the new column type.”

As a few other users have observed, you may have interdependencies involved in the deployment that need to be handled by a predeployment script or an additional property such as p:DropObjectsNotInSource or p:AllowDropBlockingAssemblies may cover your scenario.

**Comment by segunak** [comment]
> I am wondering if the key is in the word: BlockOn**Possible**DataLoss
> 
> So if my assumption is correct, that we can control blocking on POSSIBLE data loss using this configuration, but regarding ACTUAL data loss, this is out of our control?
> 
> But if that is true, then if I select TRUE, I would expect to see a validation check to prevent the change from taking place, REGARDLESS of data being present. So rather than this (which is the same error when config is FALSE): `IF EXISTS (select top 1 1 from [ref].[TableMapping]) RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT` It would just be a RAISERROR statement without checking for data present?!

Wrote an article [here](https://segunakinyemi.com/blog/dacpac-dropping-objects/) that goes into details on what SQLPackage is doing. Basically `BlockOnPossibleDataLoss` is ignored in the initial schema comparison SQLPackage does to create a deployment script. It doesn't really make sense, but that's how it is.
