### ISSUE TITLE
UsePythonVersion@0 Error: Unable to locate executable file: 'tar'

### ISSUE THREAD

**Issue by Johnsonxd4** [microsoft/azure-pipelines-tasks#17069]
## Issue:
UsePythonVersion@0 Is aways trying to unzip python downloaded files using tar even if it's a zip file.  It happens because the destination name of downloaded python zip file is written without extension. 

### Agent debug log:

```
Downloading: https://github.com/actions/python-versions/releases/download/3.10.8-3271105491/python-3.10.8-win32-x64.zip
##[debug]destination F:\azagent\A2\_work\_temp\a521a4ec-5400-4ce0-a928-330f1b7573cd
##[debug]downloading
##[debug]creating stream
##[debug]download complete
##[debug]Downloaded python archive to F:\azagent\A2\_work\_temp\a521a4ec-5400-4ce0-a928-330f1b7573cd
Extracting archive
##[debug]Agent.Version=2.193.0
##[debug]Agent.TempDirectory=F:\azagent\A2\_work\_temp
##[debug]testing directory 'F:\azagent\A2\_work\_temp\d4ba02d3-8aa5-49c6-a0a5-65ca214a12ad'
##[debug]testing directory 'F:\azagent\A2\_work\_temp'
##[debug]mkdir 'F:\azagent\A2\_work\_temp\d4ba02d3-8aa5-49c6-a0a5-65ca214a12ad'
##[debug]which 'tar'
##[debug]not found
```

It means this logic always fall on `else` condition, because the file which is being tested don't have extension:
https://github.com/microsoft/azure-pipelines-tasks/blob/cd869c578e94eddc656b2ab16f829d691ef57ac3/Tasks/UsePythonVersionV0/installpythonversion.ts#L78
The problem is, the tar command line is available only on Insider Build 17063 of windows.

Aditional information:
Agent version: 2.193.0
OS: Windows server 2016 (OS BUILD 14393.5291)

**Comment by LiliaSabitova** [comment]
Hi @Johnsonxd4 thank you for reporting the issue! We are working on more prioritized issues at the moment but will get back to this one soon.
