### ISSUE TITLE
 /azure-pipeline-test-automation.yml (Line: 3, Col: 15): Pipeline Resource smoke_test Input Must be Valid.

### ISSUE THREAD

**Issue by arpitmishra-eaton** [microsoft/azure-pipelines-tasks#17067]
![image](https://user-images.githubusercontent.com/98011264/196620987-1e94236a-7367-48b8-a132-7f7226611cdc.png)

Hi Team, 

i'm trying to trigger a build pipeline (yaml) as soon as release pipeline completed (Classic).

**Comment by LiliaSabitova** [comment]
Hi @arpitmishra-eaton, if your question is not connected with the specific task, but with yaml pipeline, you'd better create an issue under relevant [azure-pipelines-yaml repo](https://github.com/microsoft/azure-pipelines-yaml/issues).
