### ISSUE TITLE
GoToolV0 modified to use microsoft/go?

### ISSUE THREAD

**Issue by palladia** [microsoft/azure-pipelines-tasks#17070]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: GoToolV0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Hybrid Resource Provider, 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Currently uses GoTool@0 to download Go from Google Go website.  Is there an alternate task to obtain Microsoft Go, https://github.com/microsoft/go?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by Roman-Shchukin** [comment]
There are no other special tasks. You can try using Bash or PowerShell task to download and install Go using a script

**Comment by Roman-Shchukin** [comment]
What functionality are you missing in GoTooll task?

**Comment by palladia** [comment]
Just hoping there would either be a either: another task that downloads from microsoft Go, or a task that allows you to specify an alternate download location.

**Comment by Roman-Shchukin** [comment]
No, only with Bash or PowerShell scripts may be

**Comment by Roman-Shchukin** [comment]
Hi @palladia, I am closing this issue, feel free to ask any other questions.
