### ISSUE TITLE
Agent can't find bundled tools like git and node10

### ISSUE THREAD

**Issue by andyfisher100** [microsoft/azure-pipelines-tasks#17076]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Git, Node10

## Environment
- Server: Azure Pipelines    
- Agent: Private    
- Agent Version -2.211.1
- OS of the machine running the agent and the agent version: Windows Server 2022

## Issue Description

I have just installed the agent on a clean install of windows server 2022. The agent is complaining about things that are usually bundled with the agent such as git and then node10

The initial issue was Git, so I installed the git cli tools so that git existed on the path and then when I reran the pipeline it then complained about Node10 not existing

### Task logs

Starting: Checkout ORG/devops-Build.Containers@master to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
Syncing repository: ORG/devops-Build.Containers (GitHub)
Prepending Path environment variable with directory containing 'git.exe'.
git version
error launching git: The system cannot find the path specified.

##[error]Value cannot be null. (Parameter 'gitVersion')
Finishing: Checkout ORG/devops-Build.Containers@master to s

Starting: Build and tag an image
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.210.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg
##[error]This step requires a node version that does not exist in the agent filesystem. Path: F:\Agent01\externals\node10\bin\node.exe
Finishing: Build and tag an image

**Comment by Roman-Shchukin** [comment]
Could you please share pipeline logs in debug mode to take a look? You can retrieve them by following [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs).
To set up debug (verbose) mode - you can use options described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs).

**Comment by andyfisher100** [comment]
I think something strange must have happened unzipping the agent. The only files in the externals directory are Azcopy and Git. I have just downloaded the agent and unzipped and it seems to be working and all of the required tools are in the externals directory

Im happy for this to be closed
