### ISSUE TITLE
Service Fabric deployment select number of previous versions to keep

### ISSUE THREAD

**Issue by geralexgr** [microsoft/azure-pipelines-tasks#17094]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: ServiceFabricDeployV1

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricDeployV1

## Environment
- Azure Pipelines
 
- Agent - Hosted and Private: 

## Issue Description

It would be nice if we could select the Unregister Unused Versions but provide an input for how much versions we need to keep and not delete all the unused versions. For example lets say the user selects `2`, then ServiceFabric will remove all previous version except from the last two. 

![image](https://user-images.githubusercontent.com/3514710/197972168-be3bfdc4-239c-4673-8fca-5b02cde29e5e.png)

**Comment by abatishchev** [comment]
This can be achieved by configuring the cluster policy accordingly. Why do you want to make it application deploymemt time?

**Comment by geralexgr** [comment]
@abatishchev we use Managed Service Fabric clusters on Azure. Is there a way to configure that through a policy?

**Comment by abatishchev** [comment]
Try this:

```json
{
  "applicationTypeVersionsCleanupPolicy": {
    "maxUnusedVersionsToKeep": "int"
  }
}
```

See https://learn.microsoft.com/en-us/azure/templates/microsoft.servicefabric/managedclusters?pivots=deployment-language-arm-template#resource-format-1
