### ISSUE TITLE
Workflow to file a bug for an issue failed with 401

### ISSUE THREAD

**Issue by abatishchev** [microsoft/azure-pipelines-tasks#17107]
A workflow for #17106 failed with an error:

```
Error: Failed request: (401)
    at RestClient.<anonymous> (/home/runner/work/azure-pipelines-tasks/azure-pipelines-tasks/node_modules/typed-rest-client/RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/azure-pipelines-tasks/azure-pipelines-tasks/node_modules/typed-rest-client/RestClient.js:6:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 401
}
```
See https://github.com/microsoft/azure-pipelines-tasks/actions/runs/3353243842/jobs/5555903116#step:6:118

One of the PATs apparently has expired:

https://github.com/microsoft/azure-pipelines-tasks/blob/52c896b1a41ade68b76807aaefa624fd36797b11/ci/file-bugs.js#L7-L8

**Comment by jessehouwing** [comment]
Same issue? https://github.com/microsoft/azure-pipelines-tasks/actions/runs/3324377063/jobs/5495861070#step:3:25

**Comment by abatishchev** [comment]
@jessehouwing apparently the workflow for every recently opened issue in this repo fails.

**Comment by jessehouwing** [comment]
It may explain the lack of interactions with the issues.

**Comment by abatishchev** [comment]
Yeah, I noticed it too. Went through last few pages of issues, and none of them have any responses whatsoever.

I pinged few folks internally.

**Comment by jessehouwing** [comment]
Looks like folks have prioritized the node 16 upgrade.

**Comment by kirill-ivlev** [comment]
Hi @abatishchev 
Thank you for reporting that, we will have a look

**Comment by kirill-ivlev** [comment]
@abatishchev tokens updated, please re-open this issue if it is still actual.

**Comment by abatishchev** [comment]
@kirill-ivlev please have a process in place to avoid this from happening in the future too. thanks!

**Comment by abatishchev** [comment]
@kirill-ivlev can you please see if this is the same issue? "labeler" fails with 403: https://github.com/microsoft/azure-pipelines-tasks/actions/runs/3353238575/jobs/5603855160#step:6:123
