### ISSUE TITLE
ServiceFabricUpdateManifestsV2 throws vague "Invalid pattern" if path ends with \ or /

### ISSUE THREAD

**Issue by abatishchev** [microsoft/azure-pipelines-tasks#17106]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**
*Type*: Bug?

**Enter Task Name**:
[ServiceFabricUpdateManifestsV2  ](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricUpdateManifestsV2)

## Environment
- Server: Azure Pipelines (msazure/One)
- Agent : Private (OneBranch Pipelines. Windows 2022)
    
## Issue Description

ServiceFabricUpdateManifestsV2 throws vague "Invalid pattern" if `applicationPackagePath` ends with `\` or `/` (which are the [DirectorySeparatorChar ](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar)

### Task logs

```
Searching for application package: C:\__w\1\s\src\Application\pkg\Release\
##[debug]Entering Find-VstsFiles.
##[debug] LegacyPattern: 'C:\__w\1\s\src\Application\pkg\Release\'
##[debug] IncludeDirectories: 'True'
##[debug]Leaving Update-ApplicationVersions.
##[debug]Leaving C:\__w\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.198.0\Update-Manifests.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Invalid pattern: 'C:\__w\1\s\src\Application\pkg\Release\'
##[debug]At C:\__w\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.198.0\ps_modules\VstsTaskSdk\LegacyFindFunctions.ps1:136 char:13
##[debug]+             throw (Get-LocString -Key PSLIB_InvalidPattern0 -Argument ...
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : OperationStopped: (Invalid pattern...n\pkg\Relea    se\':String) [], RuntimeException
##[debug]    + FullyQualifiedErrorId : Invalid pattern: 'C:\__w\1\s\src\Application\pkg    \Release\'
##[debug] 
##[debug]Script stack trace:
##[debug]at Find-Files, C:\__w\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.198.0\ps_modules\VstsTaskSdk\LegacyFindFunctions.ps1: line 136
##[debug]at Update-ApplicationVersions, C:\__w\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.198.0\Update-ApplicationVersions.psm1: line 12
##[debug]at <ScriptBlock>, C:\__w\_tasks\ServiceFabricUpdateManifests_97ef6e59-b8cc-48aa-9937-1a01e35e7584\2.198.0\Update-Manifests.ps1: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Invalid pattern: 'C:\__w\1\s\src\Application\pkg\Release\'
##[error]Invalid pattern: 'C:\__w\1\s\src\Application\pkg\Release\'
##[debug]Processed: ##vso[task.logissue type=error]Invalid pattern: 'C:\__w\1\s\src\Application\pkg\Release\'
##[debug]Processed: ##vso[task.complete result=Failed]
##[debug]Handler exit code: 0
```

See https://dev.azure.com/msazure/One/_build/results?buildId=63072893&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=d1f4b099-7db9-5316-d788-0a44588784da&l=301

**Comment by abatishchev** [comment]
Here's a proposed fix (improvement, enfacement): https://github.com/microsoft/azure-pipelines-task-lib/pull/876

**Comment by abatishchev** [comment]
@kirill-ivlev please update the task to update the lates version of `VstsTaskSdk`, not sure if it's done automatically or regularly.

**Comment by abatishchev** [comment]
@kirill-ivlev sorry for bugging, I wonder what's the process now to update the SDK version in the task?

**Comment by abatishchev** [comment]
Reported a docs issue [here ](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/issues/110) and was about to open an issue in this repo and turns out I already did.

**Comment by abatishchev** [comment]
@kirill-ivlev iirc I fixed `VstsTaskSdk/LegacyFindFunctions.ps1`. was this task updated accordingly?

**Comment by kirill-ivlev** [comment]
@rvairavelu @manolerazvan 
could you please check this topic as a task owner?

**Comment by abatishchev** [comment]
@rvairavelu, @manolerazvan, ping please

**Comment by v-nagarajku** [comment]
@kirill-ivlev  Can you please help in updating the VSTSSdk package to 0.13.0v as we can see the latest version of VSTSSdk is 0.11.0. 
Ref - https://www.powershellgallery.com/packages?q=VstsTaskSdk
PS: Once the VSTSSdk package is published we can test the task again and confirm back with PR changes. https://github.com/microsoft/azure-pipelines-task-lib/pull/876

**Comment by abatishchev** [comment]
#plese-reopen
