### ISSUE TITLE
Certificate issue with NPM install using MS hosted agents

### ISSUE THREAD

**Issue by sbirq** [microsoft/azure-pipelines-tasks#17124]
*Type*: Bug

**Task Name**: npm package restore including cypress

## Environment
- Server - Azure Pipelines     

- Agent - Hosted 

## Issue Description

In our DevOps organization, we use Microsoft-hosted agents for the build pipeline. In this pipeline, an NPM task is failing which we first noticed on Monday, October 31st. In the NPM task, with an Install command, it is trying to use the registry 'https://pkgs.dev.azure.com/asr-garc/RiskModels.Common/_packaging/RiskModelsCommonAndUpstream/npm/registry/' , which is specified in the .npmrc file in the repostirory. This solution worked for over a year until last Monday. The pipeline logging (see attachment) shows that some NPM packages can be installed but others can't. One of the errors is that it cannot find the local issuer certificate. 

More specifically, it happens on one blob storage account:

https://i40vsblobprodsu6weus59.blob.core.windows.net/b-361efad6ee10445d898066273c739fe1/5FDEFB7C118D5B19D4EB625E452AC91F454011D376B5483BBE0D8EFFB61082FC00.blob?sv=2019-07-07&sr=b&si=1&sig=uWdaqLi3J9qcDAUdNELBQZEJEkD1MgH2XdDX8UtqXDs%3D&spr=https&se=2022-11-03T09%3A50%3A54Z&rscl=x-e2eid-26089bb0-294740f0-9961645d-a4371e42-session-26089bb0-294740f0-9961645d-a4371e42&rscd=attachment%3B%20filename%3D%22debug-4.3.4.tgz%22

The error we are getting when browsing to this link is:

`<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:024c075a-b01e-000f-7773-efebb6000000 Time:2022-11-03T11:03:46.3249642Z</Message>
<AuthenticationErrorDetail>Signed expiry time [Thu, 03 Nov 2022 09:50:54 GMT] has to be after signed start time [Thu, 03 Nov 2022 11:03:46 GMT]</AuthenticationErrorDetail>
</Error>`

### Error logs

`3731 verbose stack FetchError: request to https://fqqvsblobprodsu6weus65.blob.core.windows.net/b-361efad6ee10445d898066273c739fe1/D6D74DDFF68C8F62A8616291031DDB3176D60A0B047C5B37FE6FA843D9203A6500.blob?sv=2019-07-07&sr=b&si=1&sig=%2FahNslKBfdnZ5WMMzyUMUyf0YzxUXbH%2Fr9SohBpTSGs%3D&spr=https&se=2022-11-04T10%3A35%3A33Z&rscl=x-e2eid-3b802eb5-c24649e1-a8b2940e-d1fdea11-session-3b802eb5-c24649e1-a8b2940e-d1fdea11&rscd=attachment%3B%20filename%3D%22validate-npm-package-name-4.0.0.tgz%22 failed, reason: unable to get local issuer certificate
3731 verbose stack     at ClientRequest.<anonymous> (C:\hostedtoolcache\windows\node\16.13.2\x64\node_modules\npm\node_modules\minipass-fetch\lib\index.js:110:14)
3731 verbose stack     at ClientRequest.emit (node:events:390:28)
3731 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:447:9)
3731 verbose stack     at TLSSocket.emit (node:events:402:35)
3731 verbose stack     at emitErrorNT (node:internal/streams/destroy:157:8)
3731 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
3731 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
3732 verbose cwd D:\a\1\s\Sources\ReportingStreet\src\Gamma.Angular
3733 verbose Windows_NT 10.0.20348
3734 verbose argv "C:\\hostedtoolcache\\windows\\node\\16.13.2\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\16.13.2\\x64\\node_modules\\npm\\bin\\npm-cli.js" "ci"
3735 verbose node v16.13.2
3736 verbose npm  v8.1.2
3737 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
3738 error errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
3739 error request to https://fqqvsblobprodsu6weus65.blob.core.windows.net/b-361efad6ee10445d898066273c739fe1/D6D74DDFF68C8F62A8616291031DDB3176D60A0B047C5B37FE6FA843D9203A6500.blob?sv=2019-07-07&sr=b&si=1&sig=%2FahNslKBfdnZ5WMMzyUMUyf0YzxUXbH%2Fr9SohBpTSGs%3D&spr=https&se=2022-11-04T10%3A35%3A33Z&rscl=x-e2eid-3b802eb5-c24649e1-a8b2940e-d1fdea11-session-3b802eb5-c24649e1-a8b2940e-d1fdea11&rscd=attachment%3B%20filename%3D%22validate-npm-package-name-4.0.0.tgz%22 failed, reason: unable to get local issuer certificate
3740 verbose exit 1
`

**Comment by DmitriiBobreshev** [comment]
Hi @sbirq, thank's for reporting. Unfortunately, I don't have access to your logs, so could you please provide more info such as:
- Part of the pipeline with  npm package restore command if it's possible 
- As I understood, you're using [Azure Artifacts feed](https://learn.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows%2Cclassic) in your project. Is this a feed from your organization?
- Does this package(validate-npm-package-name) exists in your feed or it's installing from npm upstream

**Comment by DmitriiBobreshev** [comment]
Hi @sbirq, do you have any updates?

**Comment by DmitriiBobreshev** [comment]
Hi @sbirq, I'm closing the task due to inactive, please feel free to reopen it in any case of the problem.
