### ISSUE TITLE
Authentication-Exception while deploying bicep-file pointing to ACR-module from  AzureResourceManagerTemplateDeployment@3 in classic releases

### ISSUE THREAD

**Issue by phille968** [microsoft/azure-pipelines-tasks#17134]
A while back I created [this](https://github.com/Azure/bicep/issues/8730) issue in the [bicep](https://github.com/Azure/bicep)-repo, about not being able to deploy a bicep file using the [AzureResourceManagerTemplateDeployment@3](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines)-task from the devops classic releases. 

The problem occurrs when we try to reference a bicep-module which we store in our Azure ACR.
In this issue, it was pointed out that this piece of code:
https://github.com/microsoft/azure-pipelines-tasks/blob/4d8419f5e90882c316af3e73aea9521f8f2726ee/Tasks/AzureResourceManagerTemplateDeploymentV3/operations/Utils.ts#L461

Should "pass through process.env which contains the environment variables like AZURE_TENANT_ID set by the ADO service connection that are needed for Azure authentication."

**Comment by abunnyuk** [comment]
This is still very much a big problem as `AzureResourceManagerTemplateDeployment@3` is unable to access Bicep modules stored in a Container Registry, returning the following error:

```
Error BCP192: Unable to restore the module with reference "br:*****.azurecr.io/bicep/modules/modular/vnet:latest": Service request failed.

Status: 401 (Unauthorized)
```

This is not an issue with permissions to the Container Registry as the service principal has the AcrPull role assignment and running the Bicep deployment via the same pipeline from an `AzureCLI@2` task works as expected.
