### ISSUE TITLE
UseDotNet@2 Does Not Propogate SDK Version to All Downstream Tasks When Using .NET 7

### ISSUE THREAD

**Issue by wrakocy** [microsoft/azure-pipelines-tasks#17152]
## Question, Feature or Bug?
Possible Bug

##  Task Names
- UseDotNet@2
- DotNetCoreCLI@2

## Environment
- Server: Azure Pipelines hosted agent using windows-latest
- SDK version: 7.0.x

## Issue Description
After upgrading our pipeline to use .NET 7, attempts to run restore via DotNetCoreCLI@2 are failing. Based on the task logs, it appears that restore is still using the .NET 6 SDK, despite setting SDK version number to 7.0.x in an upstream call to UseDotNet@2.

### Pipleine YML

```
pool:
  vmImage: 'windows-latest'

variables:
  build.configuration: 'Release'
  build.project: $(build.name).sln
  projects: '**/*.csproj'
  dotNetCoreSDK: 7.0.x

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: $(dotNetCoreSDK) 

- task: DotNetCoreCLI@2 
  inputs: 
    command: restore 
    projects: '$(projects)' 
    feedsToUse: 'select'
    vstsFeed: 'xxxx'     
    versioningScheme: byBuildNumber

...

```
### Project File
Based on the restore task logs, this is the one project that fails to build. Worth noting: restore runs error-free on the solution locally via the CLI, and uses .net7 throughout. 

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.ApiEndpoints" Version="4.0.1" />
    <PackageReference Include="Ardalis.ListStartupServices" Version="1.1.4" />
    <PackageReference Include="Blazorise.Bootstrap" Version="1.0.6" />
    <PackageReference Include="Blazorise.Charts" Version="1.0.6" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.0.6" />
    <PackageReference Include="Hangfire" Version="1.7.31" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.31" />
    <PackageReference Include="IdentityModel" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.0" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.0.1" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="5.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.4.0" />
    <PackageReference Include="Wrak.ListComponentRoutes" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XXXX.XXXX.Core\XXXX.XXXX.Core.csproj" />
    <ProjectReference Include="..\XXXX.XXXX.Infrastructure\XXXX.XXXX.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\favicon.ico">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
```

### UseDotNet Task Logs
[Use DotNet Task Logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9973888/Use.DotNet.Task.Logs.zip)

### Restore Task Logs
[Restore Task Logs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9973890/Restore.Task.Logs.zip)

### Restore Error
2022-11-09T17:06:23.9621427Z Build FAILED.
2022-11-09T17:06:23.9626297Z 
2022-11-09T17:06:23.9679507Z        "D:\a\1\s\XXXXX.XXXXX.Web\XXXXX - XXXX.XXXX.XXXX.csproj" (Restore target) (1) ->
2022-11-09T17:06:23.9714031Z        (Restore target) -> 
2022-11-09T17:06:23.9727033Z          D:\a\1\s\XXXXX.XXXXX.Web\XXXXX - XXXX.XXXX.XXXX.csproj : error NU1201: Project XXXXX.XXXXX.Core **is not compatible with net6.0** (.NETCoreApp,Version=v6.0). Project XXXXX.XXXXX.Core supports: net7.0 (.NETCoreApp,Version=v7.0)
2022-11-09T17:06:23.9730732Z          D:\a\1\s\XXXXX.XXXXX.Web\XXXXX - XXXX.XXXX.XXXX.csproj : error NU1201: Project XXXXX.XXXXX.Infrastructure **is not compatible with net6.0** (.NETCoreApp,Version=v6.0). Project XXXXX.XXXXX.Infrastructure supports: net7.0 (.NETCoreApp,Version=v7.0)
2022-11-09T17:06:23.9731590Z 
2022-11-09T17:06:23.9732093Z     0 Warning(s)
2022-11-09T17:06:23.9732602Z     2 Error(s)

**Comment by janode** [comment]
Exact same issue here as well, but for Publish. Using UseDotNet@2 setup for `version: '7.x'`, which works fine for DotNetCoreCLI@2 on `build` and `test`, but fails on `publish` because it seemingly defaults to .NET 6. 

`error NU1201: Project <Redacted> is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Project <Redacted> supports: net7.0 (.NETCoreApp,Version=v7.0)`

**Comment by ristiisa** [comment]
any updates?

**Comment by wrakocy** [comment]
Wondering if anyone here has found a workaround for this issue?

**Comment by wrakocy** [comment]
So, I finally got to the bottom of this, and it turned out to be self-inflicted. The short of it is that a backup .csproj file targeting net6.0 had somehow found its way into the web project's root directory and was being picked up by the restore command. Naturally, it failed to build against dependencies targeting net7.0. 

For those of you continuing to hit up against this issue, assuming you have Powershell available, you may find running the following script from your solution root helpful in flushing out potential offending files:

```
Get-ChildItem -Exclude "*.dll" -Include bin,obj -Recurse | Remove-Item -Force -Recurse
Get-ChildItem -File -Recurse | Select-String "net6.0" -List | Select Path
```
