### ISSUE TITLE
Running incremental ARM Template Deploy Seems to Rollback Functionapp

### ISSUE THREAD

**Issue by hughesjs** [microsoft/azure-pipelines-tasks#17172]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**:  AzureResourceManagerTemplateDeployment  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
- Account name, team project name, build definition name/build number: Bright-HR, Consultant Visits, #20221112.1

## Issue Description

I have two relevant pipelines, one that deploys code changes, and one that deploys infra changes.

The code change deployments one works fine, and all of my functions in my functionapps seem to be there:

![image](https://user-images.githubusercontent.com/4203766/201449606-334c67a0-c4e7-4e89-8a94-b1a3de33031a.png)

However, if I then run the incremental ARM Deploy over the top of that, it seems as though it's somehow rolling back my functionapp to some unknown previous revision?

![image](https://user-images.githubusercontent.com/4203766/201449624-e5c5c962-ec1f-4b96-b128-f5cf8626449e.png)

### Task logs

I've attached the log archives for each pipeline for the same build.

[logs_98302.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9993810/logs_98302.zip)
[logs_98303.zip](https://github.com/microsoft/azure-pipelines-tasks/files/9993811/logs_98303.zip)

**Comment by FinVamp1** [comment]
Hello, @hughesjs  let me take a look at your logs and see. Are you using the ZipDeploy or MSDeploy extension in your template by any chance? It would also be great to understand if you have AppSettings defined in your incremental template that could change the Run From Package settings? [ARM Templates for Functions FAQ](https://github.com/Azure-Samples/function-app-arm-templates/wiki/Frequently-Asked-Questions-(FAQs))

**Comment by FinVamp1** [comment]
HI, @hughesjs is this still happening? I ran out of time to look at your logs before they had expired.

**Comment by hughesjs** [comment]
Hi @FinVamp1, sorry I never saw your comments. I've actually left the company that I was working at where this was happening so I have no idea if it's still happening

**Comment by FinVamp1** [comment]
Thanks @hughesjs  for the update. Good luck with the new role.
