### ISSUE TITLE
AndroidSigning@3 is returning failed with exit code 1

### ISSUE THREAD

**Issue by qasimrider** [microsoft/azure-pipelines-tasks#17212]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

<img width="988" alt="image" src="https://user-images.githubusercontent.com/15344125/202161123-ad4ae84e-0b0a-468a-b29c-5e52fd590941.png">

### Task logs

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/15344125/202162149-c313fd7f-dc1d-4a99-aa3b-c859fd84510c.png">

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

My key store password is starting with asteriks and `AndroidSigning3` is not appending `""`around it
e.g 
`C:\Windows\system32\cmd.exe /D /S /C "C:\Android\android-sdk\build-tools\33.0.0\apksigner.bat sign --ks D:\a\_temp\inhouse-keystore.jks --ks-pass pass:*ABC --ks-key-alias AAA --key-pass pass:ABC --verbose D:\a\1\s\app\build\outputs\apk\inhouse\app-inhouse-unsigned.apk"`

So if you notice here `--ks-pass pass:*ABC` this is not like this `--ks-pass *pass:*ABC*`

**Comment by eli-gc** [comment]
Did you ever figure out this issue? I'm running into the same issue but with dx.jar instead of the apksigner.bat.

**Comment by eli-gc** [comment]
Mine was solved by removing some symlinks I had to /usr/shared/java. Not sure if your issue is related.
