### ISSUE TITLE
Cache task always uses the same cache fingerprint

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/azure-pipelines-tasks#17227]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Cache 

### Server

https://dev.azure.com/ancorasoftware/ancoraDocs/_build/results?buildId=1565

### Hosted Agent

> Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az175-665'
Current agent version: '2.213.2'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20221111.1
Included Software: https://github.com/actions/runner-images/blob/win22/20221111.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221111.1
Runner Image Provisioner
Current image version: '20221111.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: UseDotNet (2.207.2)
Downloading task: NuGetToolInstaller (1.208.1)
Downloading task: DotNetCoreCLI (2.210.0)
Downloading task: JavaToolInstaller (0.211.0)
Downloading task: CmdLine (2.212.0)
Downloading task: Bash (3.211.0)
Downloading task: cloc (1.2.1)
Downloading task: Cache (2.198.0)
Downloading task: AzureKeyVault (2.211.1)
Downloading task: PublishPipelineArtifact (1.199.0)
Downloading task: NuGetCommand (2.211.0)
Downloading task: MSBuild (1.212.0)

## Issue Description

The recommended cache fallback key matches all caches for the pipeline. So it will always restore and persist the same cache. I removed the fallback key from my build definition and it had a cache miss, but the Post-job cache step matched the generic cache fingerprint and decided to not do anything since it thought the generic cache had been used. So using an exact fit cache key breaks the cache implementation. And not using one, results in the same cache being used over and over again for all build in the pipeline.

This is likely the root cause of #11770 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Cache task:
> Resolved to: nuget|"Windows_NT"|2dYInEwaSSgM9k8rz1EKgLM8EGJJ13aWGjhRaugzVNQ=
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 90f3bde0-e39a-450d-a93a-2e695366ae3a
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `nuget|"Windows_NT"|2dYInEwaSSgM9k8rz1EKgLM8EGJJ13aWGjhRaugzVNQ=`
There is a cache miss.

Post-Job Cache task:
> Resolved to: nuget|"Windows_NT"|tZ+b3hZj+6QSS3oWbz6vD8tBahd/d7kvhS4Kx03x/tU=
##[warning]The given cache key has changed in its resolved value between restore and save steps;
original key: nuget|"Windows_NT"|2dYInEwaSSgM9k8rz1EKgLM8EGJJ13aWGjhRaugzVNQ=
modified key: nuget|"Windows_NT"|tZ+b3hZj+6QSS3oWbz6vD8tBahd/d7kvhS4Kx03x/tU=

**Comment by johnterickson** [comment]
Thoughts on what the `restoreKeys` should be?

As I pointed out in the other issue, "unbounded NuGet package cache growth" is fundamentally a problem with NuGet - the same behavior/problem exists on my local dev machine.  A dev on the NuGet team wrote https://github.com/chrisraygill/NuGetCleaner to help with this.

From https://github.com/microsoft/azure-pipelines-tasks/issues/11770#issuecomment-1318936538
> That says we need to modify the FS behavior using a powershell command in order to track "last accessed" tracking. Will that even work with a nuget cache? I suspect even if "last accessed" is being tracked by the Windows VM, it won't be persisted to the cache in blob storage.

The cache task uses `tar` which should preserve the timestamp.  You will need to ensure the VM is configured to set it.

**Comment by carlin-q-scott** [comment]
@johnterickson The cache is supposed to be invalidated when my cache key changes. It is not doing that right now. If this is supposed to act like the local filesystem on a dev machine, then I think calling it a cache is confusing. What's the point of the cache key supporting a file hash if it is just ignored?

Regarding the last accessed time, I don't think tar preserves that: https://stackoverflow.com/questions/38248993/why-atime-is-not-preserved-in-tar

**Comment by johnterickson** [comment]
@carlin-q-scott ah I think I confused a more general issue from the other thread  with the one you are seeing.

 For your scenario, the key question is "why is the fingerprint changing during the build?" You may need to set "system.debug" to "true" for the cache task to show how it came up with the fingerprint value.
