### ISSUE TITLE
SVN GetSources Fails

### ISSUE THREAD

**Issue by edenroz** [microsoft/azure-pipelines-tasks#17258]
I randomly get this error while updating my sources in Azure Devops.

I tried this solution but it does not work: https://stackoverflow.com/questions/44235938/svn-update-broken-on-tfs2017

Starting: Checkout svn/XXX/branches/YYYto s

==============================================================================

Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)

==============================================================================
Syncing repository: svn/ReParvis (Svn)
##[error]One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The startIndex argument must be greater than or equal to zero. (Parameter 'startIndex'))) (The startIndex argument must be greater than or equal to zero. (Parameter 'startIndex')))) (The startIndex argument must be greater than or equal to zero. (Parameter 'startIndex'))
Finishing: Checkout svn/XXXX/branches/YYYYto s

Each time I have to manually delete the /s/ directory and download the entire repo from scratch. 
This the configuration of the task 

![image](https://user-images.githubusercontent.com/12448316/203351619-e91a3512-dd95-4b8f-8006-1ba1d5efa49d.png)

**Comment by max-zaytsev** [comment]
This is not an issue with tasks from this repo. Please open a ticket on  https://developercommunity.visualstudio.com/AzureDevOps to get right eyes on it
