### ISSUE TITLE
azure-pipelines-tasks-azure-arm-rest-v2 now includes file with space in the name

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#17338]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: azure-pipelines-tasks-azure-arm-rest-v2@3

## Environment
- Server - Azure Pipelines 

## Issue Description

`azure-pipelines-tasks-azure-arm-rest-v2@^3` includes a new license file for openssl, including this npm package in a 3rd party Azure DevOps extension causes a validation failure of the packaged extension:

```
error: Part Name 'node_modules\azure-pipelines-tasks-azure-arm-rest-v2\openssl\OpenSSL License.txt' is invalid. Please check the following: 
error: 1. No whitespace or any of these characters: #^[]<>?
error: 2. Cannot end with a period.
error: 3. No percent-encoded / or \ characters. Additionally, % must be followed by two hex characters.
tfx failed with error: Error: C:\TFS\_W\3\s\node_modules\.bin\tfx.cmd failed with return code: 4294967295
```

This license file wasn't present in `azure-pipelines-tasks-azure-arm-rest-v2@^2`.

v2:
![image](https://user-images.githubusercontent.com/4173387/205664297-0941d4cf-d2cf-493f-9d62-a893f2c957a5.png)

v3:
![image](https://user-images.githubusercontent.com/4173387/205664404-fe849d54-7274-4963-ae3f-e99bb9a4942e.png)

There is an open issue in the `tfs-cli` project since forever that tracks this issue on packaging.

https://github.com/microsoft/tfs-cli/issues/174

Can the file be renamed to `OpenSSL_License.txt`? Or can someone finally fix the validation issue in `tfs-cli`?

**Comment by jessehouwing** [comment]
Related: https://stackoverflow.com/questions/74689104/cant-package-azure-devops-extension-cause-a-dependency-includes-a-file-with-sp

**Comment by Omaraqlan** [comment]
im also facing similar issue when im installing the agents as extension in VMs 

OpenSSL License.txt: Could not find a part of the path 'OpenSSL License.txt'.

**Comment by jessehouwing** [comment]
I've added a powershell snippet to remove the spaces while packaging my tasks as a workaround:

```
https://github.com/jessehouwing/azure-pipelines-tasks-zips/blob/31a05ca466e6a5e9892e191f9f0561b2093f65d0/build-extension.ps1#L64
```

**Comment by jessehouwing** [comment]
Still not stale.
