### ISSUE TITLE
GoToolV0 does not support arm64 downloads

### ISSUE THREAD

**Issue by danieljurek** [microsoft/azure-pipelines-tasks#17348]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GoToolV0 should install ARM on arm64 machines

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GoToolV0

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - Account Name: `azure-sdk`
        - Team project name: `internal`
        - Build definition name: `azure-dev - cli`

- Agent - Hosted or Private: Private
    - lsb_release -a:
        ```
        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 20.04.5 LTS
        Release:	20.04
        Codename:	focal
        ```
    - uname -a: 
        ```
        Linux 6a0241fcc000000 5.15.0-1023-azure #29~20.04.1-Ubuntu SMP Wed Oct 26 19:17:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
        ```
        

## Issue Description

Task name: Go tool installer

The installer is downloading the wrong binary when run on ARM64 machines: 

```
Downloading: https://storage.googleapis.com/golang/go1.19.linux-386.tar.gz
```

This appears to be related to outdated assumptions made at the time of coding this tool (~5 years ago): https://github.com/microsoft/azure-pipelines-tasks/blob/cdb7cfb843ed038dcc8fa0caae3bd655ff6e52cf/Tasks/GoToolV0/gotool.ts#L90 

To fix this we need to download a file like: https://golang.google.cn/dl/go1.19.3.linux-arm64.tar.gz

### Task logs

Logs: https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/2033886/logs/37

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by rajeshkamal5050** [comment]
Any updates on this? Do you have any timelines in getting this fixed?

cc: @savannahostrowski

**Comment by danieljurek** [comment]
This issue has not been addressed. Are there plans to update the tool to handle this scenario?
