### ISSUE TITLE
Xcode Manual Signing - Can't Find iOS App Store provisioning profiles matching 'my.bundle.id'

### ISSUE THREAD

**Issue by jdwirrenga** [microsoft/azure-pipelines-tasks#17478]
## Required Information
**Bug**  
Xcode Manual Signing Failing - Unable to find downloaded provisioning profile

**Enter Task Name**: Xcode

## Environment
Server - TFS on-premises
- If using TFS on-premises, provide the version: I manually upgraded the tasks, so this probably is not helpful
    
Task Versions:
- Install Apple Certificate: 2.214.0
- Install Apple Provisioning Profile: 1.212.0
- Xcode: 5.213.0

Agent - Private: 
- If using private agent, provide the OS of the machine running the agent and the agent version: MacOS Ventura

## Issue Description
I have a pipeline set up to build and sign an ios app. I run the install certificate/provisioning profile tasks beforehand, but the xcode build will fail every time on the export. I have it set to manual signing because my understanding is auto would not work for app store.

### Task logs
I can share these privately but do not want to post them here publicly.

### Error logs
```
error: exportArchive: No profiles for 'my.bundle.id' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'my.bundle.id' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'my.bundle.id' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'my.bundle.id'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}
```

**Comment by sergey-koryshev** [comment]
Hi @jdwirrenga, could you please attach agent logs where the issue has occurred?

**Comment by jdwirrenga** [comment]
@sergey-koryshev sent you the log files and yaml but postmaster@microsoft blocked the email. Could you add jaden.wirrenga@onsharp.com to the allowed senders list, or shall I try a different address?

**Comment by sergey-koryshev** [comment]
@jdwirrenga, is there a reason of this blocking in email from `postmaster`?

**Comment by jdwirrenga** [comment]
@sergey-koryshev 
![image](https://user-images.githubusercontent.com/72875541/207618725-2c02be8e-6dac-4099-b3ae-2120b281e5b0.png)

**Comment by sergey-koryshev** [comment]
@jdwirrenga, please try to send email to this address: v-skoryshev@microsoft.com

**Comment by sergey-koryshev** [comment]
Related email-thread with logs for reference: `Fwd: Xcode Manual Signing - Can't Find iOS App Store provisioning profiles matching 'my.bundle.id' #17478`

**Comment by jdwirrenga** [comment]
This is still broken, has anyone looked into it?

**Comment by jdwirrenga** [comment]
Still doesn't work, a year later.

**Comment by jdwirrenga** [comment]
Still broken, 2 years later.
