### ISSUE TITLE
Deserializing PublishToAzureServiceBusV1 messagebody

### ISSUE THREAD

**Issue by sebastienros** [microsoft/azure-pipelines-tasks#17470]
*Type*: Question

PublishToAzureServiceBusV1

- Server, DevDiv

When passing a valid JSON payload to the task, it is serialized with `DataContractSerializer` and the resulting message in Service Bus starts with `@strin3http://schemas.microsoft.com/2003/10/Serialization/�{{` or something similar (not always the exact same preamble). What is the recommended way to deserialize this content to get the original JSON payload provided in the `messageBody` property?

Is that transformation coming from the task or from Azure Service Bus?

So far I was just searching for the first `{` character, but I found an example where it has it twice.

**Comment by sebastienros** [comment]
To be more specific, this is how it looks like in the queue before I even read it:

![image](https://user-images.githubusercontent.com/1165805/207180844-3db77a2a-0bd6-42fa-b59b-a1edb378e7c1.png)

And how it looks like in the pipeline yaml:

![image](https://user-images.githubusercontent.com/1165805/207180956-8878cca4-046b-4dfc-9dda-d6aa98a82306.png)

You can see that only valid JSON is passed, and the Service Queue is mangled by some custom serialization

**Comment by Gahmah** [comment]
I'm also encountering this issue
