### ISSUE TITLE
CopyFilesV2

### ISSUE THREAD

**Issue by stefandrissen** [microsoft/azure-pipelines-tasks#17489]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CopyFiles

## Issue Description

The task indicates that ``contents`` has a default value of ``**``, but also that it is ``required``. A default for something that is required makes no sense.

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/task.json#L46

I first thought that this was a documentation error for which I had created https://github.com/MicrosoftDocs/azure-devops-docs/issues/11424 - this was then classed as "documented as designed".

**Comment by ismayilov-ismayil** [comment]
Hi @stefandrissen, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
