### ISSUE TITLE
🐛 Issue in latest DownloadPackage task to grab the latest package version automatically (version 1.213.0)

### ISSUE THREAD

**Issue by DaveRuijter** [microsoft/azure-pipelines-tasks#17481]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPackage

## Environment
Azure Pipelines

## Issue Description
There seems to be a bug in the latest version of the DownloadPackage task (version 1.213.0). The bug I found is that it can't grab the latest version anymore automatically by specifying `latest` for the `version` property of the task. Please note that we're also using the property `view: Release` in our setup, I don't know if this bug is also there if you don't use that.
Two workarounds:	
1. Specify the task version 1.210.0, this was yesterdays version and in that task version it still works. Change - task: DownloadPackage@1t to: - task: DownloadPackage@1.210.0
1. Don't use latest for the package version, but provide the actual package version you need.
### Task logs
```##[debug]Trying to resolve latest version for 6e0bfc90-970a-4e51-b967-cfdd32476b8b
##[debug]Got URL https://feeds.dev.azure.com/<account removed by me>/38caf554-5343-4b53-962f-da54d05e434a/_apis/Packaging/Feeds/e1781db3-1264-4241-9c4c-bbe2f95761b4%40Release/Packages/6e0bfc90-970a-4e51-b967-cfdd32476b8b?protocolType=pypi from versioning data.
##[debug]Found 1 packages matching search pattern 6e0bfc90-970a-4e51-b967-cfdd32476b8b
##[debug]task result: Failed
##[error]Latest version not found.
##[debug]Processed: ##vso[task.issue type=error;]Latest version not found.
##[debug]Processed: ##vso[task.complete result=Failed;]Latest version not found.
```

**Comment by ChanceyC** [comment]
I can also vouch that something similar is happening in our pipelines as well. Before December 8th, the task was able to pull latest on a per-`view` basis.

Now unless the latest package in the `feed` also happens to be the latest in the `view` we receive this error as well. 

Thanks @DaveRuijter for the workarounds.

**Comment by yannickmols** [comment]
This essentially also breaks classic pipelines as it's not possible to set the version directly there.

**Comment by DaveRuijter** [comment]
AFAIK this is still a bug

**Comment by embetten** [comment]
@DaveRuijter  I believe this issue has been fixed with the above merge. Can you confirm the newest version of the download task?
