### ISSUE TITLE
AzurePowershell@4 on MS Hosted agent Ubuntu 20.04 has had it's Az module version updated without consent

### ISSUE THREAD

**Issue by ncgjones** [microsoft/azure-pipelines-tasks#17490]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowershell@4

## Environment
- Server - Azure Pipelines (private repo, not sharing identifying information here)

- Agent - Hosted Ubuntu 20.04  (private repo, not sharing identifying information here)

## Issue Description

Our pipelines that were working fine, have suddenly had their internal version of the Az module updated to version 9.0.1.

Previously the version was 7.5.0

We have not changed the version of the task, nor the hosted agent OS version. Nothing had changed from our end, but the hosted agent had a SIGNIFICANT update to Az module (3 major versions) without informing us, without informing our clients.

### Task logs

This is a screenshot of the logs, initialization of the agent when it was working:
![image](https://user-images.githubusercontent.com/95362812/208040242-648f9a11-dc4c-4cec-980a-ddc4930a2517.png)

This is a screenshot of the logs, initialization of the agent when it stopped working:
![image](https://user-images.githubusercontent.com/95362812/208040377-36605e4c-d0ec-4052-a269-525d0e507448.png)

Because of this change, our script failed to run, which caused pipeline downtime for clients.

I have solved this by refactoring the script that was being called to work with the latest version. But the problem here is that we have specified AzurePowershell@4, and thus we expect the same version of Az module (and thus Az Accounts) to be the same every time we run the pipeline... unless we specify a new version of the task.

## Troubleshooting

I started listing available modules on the VM, and can see that 7.5.0 was still there, but it was zipped and not used.

## Conclusion

While I found the 7.5.0 version of Az Module in a zip file on the hosted VM (using get-childitem in powershell), it wasn't in use anymore. Instead it forced the upgrade to 9.0.1.

Considering that pipelines are running on CICD, cron jobs or other automation - Microsoft cannot be randomly updating versions of powershell modules when it's defined to use a specific version in the task.

As mentioned, the script we were running has been refactored, and the pipeline is working again. But for how long? I don't know. Not until we get an explanation from Microsoft as to why they are forcibly updating hosted agent powershell modules without our consent or knowledge.

This could have been a LOT worse than it was, and it was lucky we picked this up in time.

Microsoft - please explain the process involved when considering upgrading of powershell modules on hosted agents. Why is this happening when we are specifying version numbers in the task, and why are teams not being informed about this?

**Comment by sopelt** [comment]
Hi @ncgjones , what are you providing for `azurePowerShellVersion` (see [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v4?view=azure-pipelines#:~:text=azurePowerShellVersion%20%2D%20Azure%20PowerShell%20Version)) ?
As far as I know what you are seeing would be the behavior of `LatestVersion` which gives you whatever the current [images](https://github.com/actions/runner-images) have installed (`9.0.1` as of the time of this post).
If a specific [preferredAzurePowerShellVersion](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v4?view=azure-pipelines#:~:text=preferredAzurePowerShellVersion%20%2D%20Preferred%20Azure%20PowerShell%20Version) was requested such an implicit change would be unexpected.
