### ISSUE TITLE
Any ETA for version 4.214 of "AzureRmWebAppDeployment@4" to be published? 

### ISSUE THREAD

**Issue by laika1234** [microsoft/azure-pipelines-tasks#17497]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureRmWebAppDeployment@4

## Issue Description
The change below introduced in version 4.212 causes no KUDU deployment history for Web Deploy: 
[Fix for Cosmetic API calls (#16868) · microsoft/azure-pipelines-tasks@b82a8e6 (github.com)](https://github.com/microsoft/azure-pipelines-tasks/commit/b82a8e69eb862d1a9d291af70da2e62ee69270df#diff-b8eb531ecea5edc3262148d3b26353f51ee992b6dc48e7a7820cf59411468e54) 
![image](https://user-images.githubusercontent.com/4945243/208404736-77583a96-8cd4-4612-b5de-4fc560657a1b.png)

It should be fixed in [revoke code fix done for cosmetic API calls by v-nagarajku · Pull Request #17309 · microsoft/azure-pipelines-tasks (github.com)](https://github.com/microsoft/azure-pipelines-tasks/pull/17309/files#diff-b8eb531ecea5edc3262148d3b26353f51ee992b6dc48e7a7820cf59411468e54) which corresponds to version 4.214.

I notice version 4.214 was committed 3 weeks ago. But still version 4.213 is being used. Any ETA to publish version 4.214? 
And in general, is there anywhere we can track the release status of specific commit? 

### Task logs

[logs_155.zip](https://github.com/microsoft/azure-pipelines-tasks/files/10258416/logs_155.zip)

**Comment by ismayilov-ismayil** [comment]
Hi @laika1234, thank you for your question.
The latest version of the task will be deployed with the next release. Unfortunately, there is no public option to track releases.

**Comment by laika1234** [comment]
> Hi @laika1234, thank you for your question. The latest version of the task will be deployed with the next release. Unfortunately, there is not public option to track releases.

Thanks @ismayilov-ismayil , is there any tentative ETA for next release?

**Comment by ismayilov-ismayil** [comment]
My apologies, the date of the release is not known in advance. We will announce about release.

**Comment by laika1234** [comment]
@ismayilov-ismayil  is it possible to update here when the release is ready or anywhere I can subscribe to?

**Comment by jessehouwing** [comment]
214 has since been released. This issue can be closed.
