### ISSUE TITLE
AzureFIleCopyV3 Invalid header format 

### ISSUE THREAD

**Issue by lukepowell-rldatix** [microsoft/azure-pipelines-tasks#17506]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopyV3

## Environment
- Server - Azure Pipelines
    
SelenityAllocate / Spend Management / Copy Release Zip to Caching / Release-479
 
- Agent - Hosted 
    
Windows - 2.194.0

## Issue Description

We have been using AzureFileCopyV3 for some time without issue. Last week it started failing.
We confirmed that no changes had been made to our pipeline configuration.
We noticed that the version of the task had changed from
Version      : 3.209.0
to
Version      : 3.214.0

The function that is reporting the error has been recently altered in the PR which increased the version.
MSAL Upgrade for Common Library (Powershell) (#17205)

Service connection is successfuly verifying

### Task logs

```
Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
2022-12-19T12:07:02.5437151Z ##[debug]MSAL - useMSAL = True
2022-12-19T12:07:02.5550617Z ##[debug]MSAL - Get-EnvironmentAuthUrl - endpoint=@{Url=https://management.azure.com/; Data=; Auth=}
2022-12-19T12:07:02.5565407Z ##[debug]MSAL - Get-EnvironmentAuthUrl - useMSAL=True
2022-12-19T12:07:02.5580479Z ##[debug]MSAL - Get-EnvironmentAuthUrl - envAuthUrl=https://login.microsoftonline.com/
2022-12-19T12:07:02.6464062Z ##[debug]MSAL - ServicePrincipal - clientSecret is used.
2022-12-19T12:07:02.6611436Z ##[debug]Fetching Access Token - MSAL
2022-12-19T12:07:02.8510168Z ##[debug]Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
2022-12-19T12:07:02.8525617Z ##[debug]MSAL - useMSAL = True
2022-12-19T12:07:02.8551467Z ##[debug]Fetching Access Token - MSAL
2022-12-19T12:07:02.8870901Z ##[debug]GET https://management.azure.com//subscriptions/{subscription}/resourceGroups/{resourceGroup}?api-version=2016-02-01 with 0-byte payload
2022-12-19T12:07:02.9165834Z ##[debug]Exception : The remote server returned an error: (401) Unauthorized.
2022-12-19T12:07:02.9255378Z ##[debug]Exception message - System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2022-12-19T12:07:02.9267621Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2022-12-19T12:07:02.9280705Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2022-12-19T12:07:02.9431306Z ##[debug]Exception message extracted from response {"error":{"code":"AuthenticationFailedInvalidHeader","message":"Authentication failed. The 'Authorization' header is provided in an invalid format."}}
2022-12-19T12:07:02.9844099Z ##[debug]Processed: ##vso[task.logissue code=AuthenticationFailedInvalidHeader;type=error]
2022-12-19T12:07:02.9898286Z ##[debug]Exception : ExceptionMessage: Authentication failed. The 'Authorization' header is provided in an invalid format. (in function: Get-AzRmResourceGroup)
```

### Error logs

ExceptionMessage: ExceptionMessage: Authentication failed. The 'Authorization' header is provided in an invalid format. (in function: Get-AzRmResourceGroup) (in function: Get-AzRMStorageKeys)

[tasklog_28.zip](https://github.com/microsoft/azure-pipelines-tasks/files/10267180/tasklog_28.zip)

**Comment by larlew** [comment]
I have the exact same issue with AzureFIleCopyV4  4.214.0

**Comment by ismayilov-ismayil** [comment]
Hi @lukepowell-allocate, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon

**Comment by ychikazawa** [comment]
A workaround is to use `azcopy` command directly.
I confirmed it works fine.

```yml
- task: CmdLine@2
  inputs:
    script: azcopy copy "<FILE>" "<SAS URL>"
```

**Comment by JonathanLydall** [comment]
Hi @ozanovus,

In case it helps you, we've been experiencing this problem, but only on our self-hosted agent. As a workaround since the same day this issue was logged we've switched to using an Azure hosted `windows-latest` agent which works fine. To answer your questions:

1. Windows 10 22H2 (OS Build 19045.2364)
2. The service connection looks like this:
  ![image](https://user-images.githubusercontent.com/1290262/211325626-f4a0649a-3078-40fc-9fc6-b049cbd61e72.png)
3. For administrative reasons I'm not able to change the service connection at this time.
4. Our task is as follows:
  ```yaml
  - task: AzureFileCopy@4
    displayName: Copy installers to Azure Blob Storage
    inputs:
      sourcePath: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\*'
      azureSubscription: 'Intent Architect Azure Resource Group'
      destination: 'azureBlob'
      storage: '<storageAccountName>'
      containerName: '<containerName>'
      additionalArgumentsForBlobCopy: '--log-level=INFO --exclude-pattern "*.yml"'
      copyFilesInParallel: false
  ```
5. The agent is not behind any sort of proxy.

**Comment by tboerstad** [comment]
We are experience the same issue with a similar setup as @JonathanLydall. 

Pipelines which have been working fine until now are suddenly breaking, without us making any changes.

**Comment by iotalambda** [comment]
Experiencing the same problem!

**Comment by larlew** [comment]
I haven't changed anything but I see the Azure File Copy task version has been updated to 5.210.1
I see the error has changed to: Could not find the module Az.Accounts with given version. If the module was recently installed, retry after restarting the Azure Pipelines task agent.


```
2023-01-09T17:46:52.6740680Z ##[section]Starting: AzureBlob File Copy Map Files
2023-01-09T17:46:52.6912978Z ==============================================================================
2023-01-09T17:46:52.6913315Z Task         : Azure file copy
2023-01-09T17:46:52.6913586Z Description  : Copy files to Azure Blob Storage or virtual machines
2023-01-09T17:46:52.6913845Z Version      : 5.210.1
2023-01-09T17:46:52.6914051Z Author       : Microsoft Corporation
2023-01-09T17:46:52.6914384Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy
2023-01-09T17:46:52.6914755Z ==============================================================================
2023-01-09T17:46:53.9214967Z Added TLS 1.2 in session.
2023-01-09T17:46:54.2264752Z ##[error]Could not find the module Az.Accounts with given version. If the module was recently installed, retry after restarting the Azure Pipelines task agent.
2023-01-09T17:46:54.2573826Z ##[section]Finishing: AzureBlob File Copy Map Files
```

**Comment by lukepowell-rldatix** [comment]
> Hello @lukepowell-rldatix , first of all thanks for reporting the issue.
> 
> **Temporary Solution:** New update (starting from x.216.y) will give you option to override MSAL with `USE_MSAL` environment variable set to `false`.
> 
> However, regarding our checks we couldn't manage to reproduce the same error. To identify root cause and further development; could you please specify further details?
> 
>     1. Which operating system that runner currently using? (Hosted Windows-2019, 2022 or different?) Is the error repeating when you change it to some different version?
> 
>     2. What kind of Service Connection you're using? (secret, certificate, legacy username/password?)
> 
>     3. Could you please create a new Service Connection and try with it? Is it giving same error?
> 
>     4. Do you specify any additional arguments in Task configuration? (optional arguments, blob prefix?) Could you please share your Task configuration with censoring private information?
> 
>     5. Are tasks running behind a proxy configuration? If yes, how do you set proxy for tasks and does it have basic authentication?

We had to stop using this specific task as it was blocking us and we couldn't wait an indeterminate amount of time for a fix.
I won't be able to assist you in any further testing therefore but can aswer some of these questions.

1. Agent.OSVersion 10.0.17763
2. Service principal key
4. No optional arguments are involved.
5.  No proxy.

**Comment by Cbrbeats** [comment]
@ JonathanLydall 
I had the same problem today and i resolved it by updating Azure modules on the server where my agents were hosted.
I can use my selfHosted agent pools again , hope this helps!

**Comment by JonathanLydall** [comment]
> @JonathanLydall I had the same problem today and i resolved it by updating Azure modules on the server where my agents were hosted. I can use my selfHosted agent pools again , hope this helps!

Thank you @Cbrbeats, it did.

For anyone else with the same issue and wanting to know how to do the upgrade, I ran the following from an admin elevated PowerShell session:

```
Install-Module -Name Az -Scope AllUsers -Force -AllowClobber
```

When I initially made the pipeline I had a task which would run this every time, but on the hardware for that agent it would add _minutes_ for each run, so I removed it but kept comments in the `.yml` of what command to run which came in useful today for this.

**Comment by ismayilov-ismayil** [comment]
Closing this one as stale - feel free to ask any other questions or let us know if it's still relevant for you.

**Comment by ozanovus** [comment]
For future reference in case any other user experience similar issue; I wanted to add some references for updating **Azure Az PowerShell** module.

**1. Checking Azure Az PowerShell Module Version:** 

You can check installed Az Module versions with the command below.

`Get-InstalledModule -Name Az -AllVersions -OutVariable AzVersions`

If version is old (currently latest version is `9.4.0`); we recommend you to update your Az Module .

**2. Updating Azure Az PowerShell Module** 

Recommended way is to visit the official page which has instructions for different Powershell versions according to needings.
https://learn.microsoft.com/en-us/powershell/azure/install-az-ps

**Example** command for installation from the page:
`Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force`

**Comment by Nitesh-kumar-Reddy** [comment]
@ozanaydinMSFT  i tried updating my az modules still not working .


##[debug][Azure Call]Creating AzStorageContext for storage account: stxxx
##[debug][Azure Call]Created AzStorageContext for storage account: stxxx
##[debug][Azure Call]Getting resource details for azure storage account resource: stxxx with resource type: Microsoft.Storage/storageAccounts
##[debug][Azure Call]Retrieved resource details successfully for azure storage account resource: stxxx with resource type: Microsoft.Storage/storageAccounts
##[debug][Azure Call]Retrieving storage account type for the storage account: stdevblob in resource group: rg-xxx
##[debug]Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
##[debug]USE_MSAL: 'true'
##[debug]MSAL - USE_MSAL override is found: true
##[debug]MSAL - useMSAL = True
##[debug]Fetching Access Token - MSAL
##[debug]GET https://management.azure.com//subscriptions/xxxxx/resourceGroups/rg-xxx?api-version=2016-02-01 with 0-byte payload
##[debug]received 187-byte response of content type application/json; charset=utf-8
##[debug]GET https://management.azure.com//subscriptions/xxxx/resourceGroups/rg-xxxx/providers/Microsoft.Storage/storageAccounts/stxxx?api-version=2016-01-01 with 0-byte payload
##[debug]received 734-byte response of content type application/json
##[debug]Constructing the storage account object
##[debug][Azure Call]Retrieved storage account type successfully for the storage account: stxxx in resource group: rg-xxx
##[debug]Obtained Storage Account type: Standard
##[debug][Azure Call]Getting container: templates in storage account: stxxx
##[debug]Container: templates does not exist in storage account: stxxx
##[debug]Creating container if the containerName provided does not exist
##[debug][Azure Call]Creating container: templates in storage account: stdevblob
##[debug]Azure.RequestFailedException: This request is not authorized to perform this operation.
##[debug]RequestId:7a3f56f8-e01e-0076-5415-292675000000
##[debug]Time:2023-12-07T14:01:21.6759463Z
##[debug]Status: 403 (This request is not authorized to perform this operation.)
##[debug]ErrorCode: AuthorizationFailure

##[debug]x-ms-client-request-id: af57b9dc-2e3e-4767-bf98-14a477f129e6
##[debug]x-ms-error-code: AuthorizationFailure
##[debug]Content-Length: 246
##[debug]Content-Type: application/xml
##[debug]Date: Thu, 07 Dec 2023 14:01:21 GMT
##[debug]Server: Microsoft-HTTPAPI/2.0
##[debug]
##[debug]At F:\ado_agent_racetrac-dd\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\5.231.2\AzureUtilityAz1.0.ps1:54 char:22
##[debug]+ ... container = New-AzStorageContainer -Name $containerName -Context $sto ...
##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : CloseError: (:) [New-AzStorageContainer], RequestFailedException
##[debug]    + FullyQualifiedErrorId : RequestFailedException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStora    geContainerCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at Create-AzureContainer, F:\ado_agent_racetrac-dd\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\5.231.2\AzureUtilityAz1.0.ps1: line 54
##[debug]at <ScriptBlock>, F:\ado_agent_racetrac-dd\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\5.231.2\AzureFileCopy.ps1: line 154
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]Azure.RequestFailedException: This request is not authorized to perform this operation.
##[debug]RequestId:7a3f56f8-e01e-0076-5415-292675000000
##[debug]Time:2023-12-07T14:01:21.6759463Z
##[debug]Status: 403 (This request is not authorized to perform this operation.)
##[debug]ErrorCode: AuthorizationFailure
##[debug]
##[debug]Content:
##[debug]﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
##[debug]RequestId:7a3f56f8-e01e-0076-5415-292675000000
##[debug]Time:2023-12-07T14:01:21.6759463Z</Message></Error>

Headers:
x-ms-request-id: 7a3f56f8-e01e-0076-5415-292675000000
x-ms-client-request-id: af57b9dc-2e3e-4767-bf98-14a477f129e6
x-ms-error-code: AuthorizationFailure
Content-Length: 246
Content-Type: application/xml
Date: Thu, 07 Dec 2023 14:01:21 GMT
Server: Microsoft-HTTPAPI/2.0

##[debug]Processed: ##vso[task.logissue type=error]This request is not authorized to perform this operation.
RequestId:7a3f56f8-e01e-0076-5415-292675000000
Time:2023-12-07T14:01:21.6759463Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:7a3f56f8-e01e-0076-5415-292675000000
Time:2023-12-07T14:01:21.6759463Z</Message></Error>

Headers:
x-ms-request-id: 7a3f56f8-e01e-0076-5415-292675000000
x-ms-client-request-id: af57b9dc-2e3e-4767-bf98-14a477f129e6
x-ms-error-code: AuthorizationFailure
Content-Length: 246
Content-Type: application/xml
Date: Thu, 07 Dec 2023 14:01:21 GMT
Server: Microsoft-HTTPAPI/2.0
