### ISSUE TITLE
Build error on Azure pipeline for Xamarin android

### ISSUE THREAD

**Issue by ajibadeseun** [microsoft/azure-pipelines-tasks#17510]
I have experiencing the following error on the Azure pipeline even though I can run the application successfully locally on my system and Android device:

1.  error CS0117: 'BuildVersionCodes' does not contain a definition for 'Tiramisu'
2. error CS0117: 'Manifest.Permission' does not contain a definition for 'ReadMediaImages'

Kindly note that I am targeting Android 13 (Sdk level 33 and above) and minimum Sdk level is 21

**Comment by ismayilov-ismayil** [comment]
Hi @ajibadeseun, thanks for reporting. Could you please share your yaml file and log files (after run pipeline with system debug enabled mode)
If you have any confidential data in files, please pay attention to replace with placeholder or mask

**Comment by ajibadeseun** [comment]
# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: '**Build configuration e.g Dev**'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**Path to CSPROJ file**.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

Kindly find find yaml configuration as above
