### ISSUE TITLE
HelmInstaller@1 Unexpected HTTP response: 403

### ISSUE THREAD

**Issue by atedsimple** [microsoft/azure-pipelines-tasks#17513]
For the last couple of days, our HelmInstaller task keeps giving the following error and then installs an older version of helm. Retrying failed jobs usually fixes. Can you not add a fallback version parameter so that we can at least specify a better version to use than 3.1.2 as the subsequent stage fails due to this old version?

##[warning]Cannot get the latest Helm info from https://api.github.com/repos/helm/helm/releases. Error Error: Unexpected HTTP response: 403. Using default Helm version v3.1.2.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/50109927/208967228-7f9a5380-bcac-4d6f-a83a-beccc40f33e9.png">

**Comment by saschagottfried** [comment]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmInstaller@1

## Environment
- Server - Azure Pipelines
    
    - account name: Kelvion-DevOps
    - team project name: MyAFC
    - build definition name: myafc-helm (kts)
    - build number: 2022.12.16-2

- Agent - Hosted
    
    - agent queue name: Azure Pipelines

## Issue Description

From my point of view a failed download of a Helm release from GitHub is a transient error. The fallback behaviour of the pipeline task is to install an outdated Helm version ([3.1.2 - released in march 2020](https://github.com/helm/helm/releases/tag/v3.1.2)) that does not support common options/flags used as of today - and that breaks the build/deployment in subsequent pipeline tasks using `HelmDeploy@0` unless you explicitly verify the Helm version.

My suggestion for a fallback behaviour of `HelmInstaller@1` : use a recent Helm version if installed in the hosted build agent image. An example: hosted agents with image `ubuntu-22.04` ship with Helm 3.10.2 - see [Ubuntu 22.04 runner image (package management)](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#package-management)

![image](https://user-images.githubusercontent.com/1422627/209101125-b29fa528-4d24-4027-a642-3986b8cb71b9.png)

**Comment by atedsimple** [comment]
Yes I figured it was a transient issue but 3 days is a pain. Good suggestion though, forgot that it was probably pre installed on the agent so can probably just remove the HelmInstaller@1 task. Be interesting to see how often the pre installed one gets updated though

**Comment by priyankar-dutta** [comment]
This has been happening a lot recently - can I ask for this to be reopened and looked at?
