### ISSUE TITLE
Azure pipelines tasks "AzureFunctionAppV1" not support .NET 7

### ISSUE THREAD

**Issue by MarcoHuib** [microsoft/azure-pipelines-tasks#17537]
## Note  
I like to do a feature requests for Azure pipelines tasks "[AzureFunctionAppV1](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFunctionAppV1)" to make it possible to support .NET 7. Are there any plans to do this?

> Previous bug it was solved and @FinVamp1 mention this will be automatic. I think this is not yet made, so therefor I open a new ticket to update it to .net 7.

## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureFunctionAppV1  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

## Issue Description

[Include task name(s), screenshots and any other relevant details]

We are looking to support .net 7 Azure function ([In-Process](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#differences-with-net-class-library-functions)). But the task does not support this yet. See below.

```
        {
            "name": "runtimeStack",
            "type": "pickList",
            "label": "Runtime stack",
            "defaultValue": "",
            "required": false,
            "properties": {
                "EditableOptions": "True"
            },
            "options": {
                "DOTNET|2.2": "DOTNET|2.2 (functionapp v2)",
                "DOTNET|3.1": "DOTNET|3.1 (functionapp v3)",
                "DOTNET|6.0": "DOTNET|6.0 (functionapp v4)",
                "JAVA|8": "JAVA|8 (functionapp v2/v3/v4)",
                "JAVA|11": "JAVA|11  (functionapp v3/v4)",
                "NODE|8": "NODE|8 (functionapp v2)",
                "NODE|10": "NODE|10 (functionapp v2/v3)",
                "NODE|12": "NODE|12 (functionapp v3)",
                "NODE|14": "NODE|14 (functionapp v3/v4)",
                "NODE|16": "NODE|16 (functionapp v4)",
                "PYTHON|3.6": "PYTHON|3.6 (functionapp v2/v3)",
                "PYTHON|3.7": "PYTHON|3.7 (functionapp v2/v3/v4)",
                "PYTHON|3.8": "PYTHON|3.8 (functionapp v3/v4)",
                "PYTHON|3.9": "PYTHON|3.9 (functionapp v3/v4)"
            },
            "visibleRule": "appType = functionAppLinux",
            "helpMarkDown": "Refer [this doc](https://docs.microsoft.com/azure/azure-functions/functions-versions#languages) for supported runtime versions.  Old values like `DOCKER|microsoft/azure-functions-*` are deprecated, please use the new values from dropdown."
        },
```
Source: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFunctionAppV1/task.json

**Comment by FinVamp1** [comment]
Hello, we've added support for this in the v2 version of the task. https://github.com/microsoft/azure-pipelines-tasks/pull/17137 . Have you tried that?

**Comment by FinVamp1** [comment]
I am closing this as we have added support in the v2 task. Please let us know if this doesn't work for you.
