### ISSUE TITLE
"Set version" using Maven@3 is skipping some modules sometimes

### ISSUE THREAD

**Issue by pedrofurlanetto** [microsoft/azure-pipelines-tasks#17533]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven@3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: hpcodeway

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: ADO agent v2.200.2

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
We have a step to set the artifact version using the following command

```bash
/usr/local/ado-agent/_work/_tool/maven/3.6.3/x64/apache-maven-3.6.3/bin/mvn -f /usr/local/ado-agent/_work/7/s/pom.xml --settings /usr/local/ado-agent/_work/_temp/.m2/settings.xml versions:set -DnewVersion=0.1.246 -DprocessAllModules -DgenerateBackupPoms=false
```

Our pipelines started to fail sometime because this step does not apply the new version to all of our submodules. Sometimes it skips a single child module, sometimes it skips a lot of modules, and there is no pattern.

In this example, the step skipped two children modules (Assertions and Model Classes) on a specific project

![image](https://user-images.githubusercontent.com/16151787/210271451-7d71e8d6-ea56-4241-b033-bb2b95149d95.png)

In this example, it skipped almost all of the children modules in another project (it applied the change on 4 of 22 modules)

![image](https://user-images.githubusercontent.com/16151787/210271571-d50de077-f772-4ecb-b820-03e88fdb0949.png)

In the following step, where our pipeline publishes these modules to Nexus, it fails because of some modules have the snapshot version.

Sometimes this step works properly applying the new version to all of the children modules.

Can someone help us?

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by LiliaSabitova** [comment]
Hi @pedrofurlanetto thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.
