### ISSUE TITLE
'%' is replaced to '%25' in output variable for the Kubernetes@1

### ISSUE THREAD

**Issue by tomaeda** [microsoft/azure-pipelines-tasks#17536]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetesV1
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
     account: v-tomaeda, project : kubectlTest, definition name: kubectlTest, number: 2505

- Agent - Hosted or Private: 
Hosted
    
    - If using Hosted agent, provide agent queue name:
      ubuntu-latest

## Issue Description

I used  get command with Kubernetes@1 to output variable for yaml format.
When % is included in the output, it is replaced by %25 in the output variable.
The same result if the output format is JSON.

I set job level variable DECODE_PERCENTS to true with reference to #14302, but the result didn't change.

![image](https://user-images.githubusercontent.com/79292498/209656805-ee8f3938-6678-4b8d-9e29-de67b4625aff.png)

The red line should have been 25%, but has been replaced with 25%25.

### Task logs

[logs_2505.zip](https://github.com/microsoft/azure-pipelines-tasks/files/10307676/logs_2505.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tomaeda** [comment]
I may be missing my explanation, so I will supplement it.
I think this is a issue with ##vso[task.setvariable] which set output variable.

Please look at the 6_kubetest.txt from the I attached log file.
Of the information retrieved by the kubectl get command, lines 202 and 203 show 25%.

![image](https://user-images.githubusercontent.com/79292498/209739558-5f746755-5989-4bbe-9688-99047b66f780.png)

However, in lines 398 and 399 with it set as an output variable, 25% changes to 25%25.

![image](https://user-images.githubusercontent.com/79292498/209739610-8ede92f8-f8f9-4754-962a-41d10f7c1477.png)

Line 469 shows the ##vso[task.setvariable variable=KubectlOutput;issecret=false;] processed.
I can seen that 25% has already changed to 25% 25 in it.

![image](https://user-images.githubusercontent.com/79292498/209739782-d20d752e-1ea1-4e93-890c-fe8082a9c24e.png)

When I display the output variable of task with the echo command, it still stays at 25%25. This can be seen in 7_CmdLine.txt.
Please let me know if there are any unclear in my explanation.

**Comment by tomaeda** [comment]
Is this the expected behavior of task?
If so, is there a workaround for me to get the correct output variable?

**Comment by rikat-ms** [comment]
The issue was resolved by #17267 - version 1.214.0. So, the issue no longer occurs.
