### ISSUE TITLE
SQL DB Deployment using Azure DevOps is failing in linux Virtual Machine

### ISSUE THREAD

**Issue by ammuk679** [microsoft/azure-pipelines-tasks#17542]
To generate DACPAC file I am using VSBuild@1 task. But it is failing in Azure Linux VM with the error "##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell." 

Is there any way to generate DACPAC file in an Azure linux VM?

**Comment by LiliaSabitova** [comment]
Hi @ammuk679 thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.
