### ISSUE TITLE
Python pip authenticate v1 task shows warnings

### ISSUE THREAD

**Issue by tboerstad** [microsoft/azure-pipelines-tasks#17553]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PipAuthenticate@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
- Agent
Hosted - windows-latest

## Issue Description
Warnings showing at runtime:
`Resource file has already set to: C:\Azure\agent2\_work\_tasks\PipAuthenticate_5e3feff0-c5ae-11e8-a7d0-4bd3b8229800\1.213.0\node_modules\azure-pipelines-tasks-artifacts-common\module.json`

See also #14536 

![image](https://user-images.githubusercontent.com/4872288/210365228-6e5a57bc-9094-41e0-96a2-452faaca6d5c.png)

**Comment by kirill-ivlev** [comment]
@tboerstad thank you for reporting this problem, we will investigate it and let you know.
