### ISSUE TITLE
HelmInstaller@1 installs outdated Helm version 3.1.2 when download of specified version failed

### ISSUE THREAD

**Issue by saschagottfried** [microsoft/azure-pipelines-tasks#17569]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmInstaller@1

## Environment
- Server - Azure Pipelines
    
    - account name: Kelvion-DevOps
    - team project name: MyAFC
    - build definition name: myafc-helm (kts)
    - build number: 2022.12.16-2

- Agent - Hosted
    
    - agent queue name: Azure Pipelines

## Issue Description

From my point of view a failed download of a Helm release from GitHub is a transient error. The fallback behaviour of the pipeline task is to install an outdated Helm version ([3.1.2 - released in march 2020](https://github.com/helm/helm/releases/tag/v3.1.2)) that does not support common options/flags used as of today - and that breaks the build/deployment in subsequent pipeline tasks using `HelmDeploy@0` unless you explicitly verify the Helm version.

My suggestion for a fallback behaviour of `HelmInstaller@1` : use a recent Helm version if installed in the hosted build agent image. An example: hosted agents with image `ubuntu-22.04` ship with Helm 3.10.2 - see [Ubuntu 22.04 runner image (package management)](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#package-management)

![image](https://user-images.githubusercontent.com/1422627/209101125-b29fa528-4d24-4027-a642-3986b8cb71b9.png)

**Comment by saschagottfried** [comment]
duplicate of #17513 since `github-actions` bot did not assign anyone or added labels yet due to missing information in initial issue template.

**Comment by KrylixZA** [comment]
Bumping this thread. This issue is intermittent for our usage when running with Microsoft agents running in Azure West Europe. When this issue occurs it breaks our builds as we are features released in newer versions of Helm. We get the following error when the installation fails:

```bash
Starting: Helm linter
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
helm lint /home/vsts/work/1/s/.pipelines/helm/my-service --values /home/vsts/work/1/s/.pipelines/helm/my-service/values/dev-test.yaml --strict
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/12d5545c-1a77-4d67-b375-9655af27d9bf.sh
==> Linting /home/vsts/work/1/s/.pipelines/helm/my-service
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: my-service/templates/tests/tests.yaml:5:23: executing "my-service/templates/tests/tests.yaml" at <.Values.namespace>: map has no entry for key "namespace"

Error: 1 chart(s) linted, 1 chart(s) failed
##[error]Bash exited with code '1'.
Finishing: Helm linter

```

**Comment by hollowdrutt** [comment]
Same issue here, using hosted agents in West Europe. Intermittent failures: build fails because HelmInstaller@1 could not get the latest Helm info and used the preinstalled version instead, I rerun the task without changes and it succeeds.

**Comment by saschagottfried** [comment]
After running into this issue again today I decided to remove the pipeline task from the pipeline. Since [Helm is updated continuously as part of build runner image](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#package-management) you can remove that responsibility from the pipeline at all. 

This approach might not work for all use cases, but when you just want to install the latest version of Helm for your Ubuntu-based build agent the current `ubuntu-latest` image provides everything you need. No need for an additional pipeline task.

**Comment by boneskewer69** [comment]
> I decided to remove the pipeline task `HelmInstaller@1` from the pipeline

@saschagottfried I used this approach as well. For now it seems to work.\
As soon as there are breaking changes and the agent gets the update some time later, the pipeline is going to break at an unexpected time.

Anyway this seems to work for now which is nice! Without your issue, I wouldn't have guessed that helm was pre-installed on the machines... Thank you!

**Comment by oliverisaac** [comment]
This was an issue today during the Github outage. Would be best to have failed downloads actually fail the step.
