### ISSUE TITLE
Bug: task.uploadsummary on Self-Hosted agent raises error

### ISSUE THREAD

**Issue by abij** [microsoft/azure-pipelines-tasks#17578]
## Environment
- Agent - Private: 

    - Version: 2.213.2
    - linux

## Issue Description

Using bash task to execute: 

`echo "##vso[task.uploadsummary]$(Pipeline.Workspace)/TerraformPlan.md"`

I think it's the same as described here: https://developercommunity.visualstudio.com/t/different-behavior-on-selfhosted-agent-and-on-clou/1308635

- Upload summary *inside* type: deployment. 
  - Note: it does work as intended for job type: job, with source code checkout and `/s/` directory.
  - Type deployment does not checkout source code and does not have a `/agent/_work/../s/` directory.
  - Pointing to `$(Pipeline.Workspace)/TerraformPlan.md` and not using the `$(Build.SourcesDirectory)`.

Result: 
- file is uploaded and visible in tab: extensions.
- task failed with error that the file is null

### Task logs

```
...
##[debug]bashEnvValue=undefined
##[debug]script=
echo "Sample" > /agent/_work/40/TerraformPlan.md
echo "##vso[task.uploadsummary]/agent/_work/40/TerraformPlan.md"
Generating script.
##[debug]which 'bash'
##[debug]found: '/usr/bin/bash'
##[debug]Agent.Version=2.213.2
..
..
##[error]Unable to process command '+ echo '##vso[task.uploadsummary]/agent/_work/40/TerraformPlan.md'' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Value cannot be null. (Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk')
##[debug]System.ArgumentNullException: Value cannot be null. (Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk')
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskAddAttachmentCommand.AddAttachment(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskUploadSummaryCommand.Execute(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.BaseWorkerCommandExtension.ProcessCommand(IExecutionContext context, Command command)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
##[debug]Processed: + echo '##vso[task.uploadsummary]/agent/_work/40/TerraformPlan.md'
```

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1022013/211289720-61d9aab5-449c-40b0-8379-4cb468694e8f.png">

But it's uploaded anyway:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/1022013/211290076-c258e390-c86d-4962-bd8e-ddfa773744f4.png">

**Comment by Roman-Shchukin** [comment]
Hi @abij  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by simeoncode** [comment]
We are not on self-hosted, but also ran into this issue. What seems to work though, is this longer command which accomplishes the same thing:

> `echo "##vso[task.addattachment type=Distributedtask.Core.Summary;name=diff;]diff.md"`

**Comment by abij** [comment]
You are right this works! This is a good workaround! But it would be nice to fixed, I think it's a hint for the developers where to bug is.

**Comment by adrian-skybaker** [comment]
Not stale

**Comment by adrian-skybaker** [comment]
From the linked developercommunity issue:

>I had the same issue using MS Hosted. The solution is to disable the mode that shows what the shell is going to execute (i.e. bash -x). My guess is that AzDO doesn’t like the + at the beginning of the line.

**Comment by coopp** [comment]
I encountered this same issue this week.  
I did workaround it by creating a powershell script that uses Write-Host "##vso[task.uploadSummary]$myFilePath" and executing that from my build pipeline via the PowerShell@2 task.

This published the summary markdown just fine.

Not sure why echo from a CMD script throws an error, but at least there is another workaround.
