### ISSUE TITLE
npmAuthenticate@0 stopped working with new version

### ISSUE THREAD

**Issue by albert17** [microsoft/azure-pipelines-tasks#17585]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: npmAuthenticate@0  

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines 

- Agent - Hosted or Private: Hosted Agent, windows-latest

## Issue Description
`npmAuthenticate@0` stopped working with latest version. 

Task was working fine with `0.208.1`
<img width="505" alt="image" src="https://user-images.githubusercontent.com/14819628/211574805-99875b1e-fdef-4115-968f-052ec00d875a.png">

Task started using `0.214.2` and now fail.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/14819628/211574957-f39c8822-c0cc-4089-b291-622473c45574.png">

### Error logs
```
Starting: Authenticate NPM
==============================================================================
Task         : npm authenticate (for task runners)
Description  : Don't use this task if you're also using the npm task. Provides npm credentials to an .npmrc file in your repository for the scope of the build. This enables npm task runners like gulp and Grunt to authenticate with private registries.
Version      : 0.214.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm-authenticate
==============================================================================
Adding authentication to the .npmrc file at D:\a\1\s\private\HitApps\WebMCVNext\app\.npmrc
##[warning]Resource file haven't been set, can't find loc string for key: SavingFile
##[error]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')
Finishing: Authenticate NPM
```

**Comment by noahhai** [comment]
@Roman-Shchukin getting validation error trying to specify like this. Is there another way?
![image](https://user-images.githubusercontent.com/8117605/211591837-2a3684b0-0efa-4819-be8a-2d7cc80f6b13.png)

**Comment by albert17** [comment]
`- task: npmAuthenticate@0.208.1` works for me.

@noahhai `workingFIle` needs to point to the specific `.npmrc` file not to a folder.

**Comment by noahhai** [comment]
@albert17  thank you. yeah, I truncated the screenshot

**Comment by weldpua2008** [comment]
> Hi @albert17 we've rolled out the fix for this issue. As a temporary solution you could specify a previous version of the task (0.208.1) in the pipeline https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions

I still getting the error. Is the fix live?

**Comment by Roman-Shchukin** [comment]
Hi @weldpua2008, could you please check it now?

**Comment by ben-nichols14** [comment]
@Roman-Shchukin We are getting this problem using the traditional release pipelines (ie. not YAML). It is still pulling through version 0.214.2 - is this supposed to be pushed out yet? is there a way we can force a different minor version?

**Comment by Roman-Shchukin** [comment]
@ben-nichols14 are you using self-hosted agent?

**Comment by ben-nichols14** [comment]
We have tried on both self hosted and microsoft hosted agent and getting the same result

tried with:
windows-latest
ubuntu-latest
self hosted (ubuntu)

**Comment by viktoriia-nintex** [comment]
I am seeing the same with a classic Release pipeline: can't specify the older version, and the one being pulled in is still 0.214.2. When is the fix going live?

**Comment by Roman-Shchukin** [comment]
@ben-nichols14 @viktoriia-nintex could you please tell me your org name in ADO?

**Comment by viktoriia-nintex** [comment]
@Roman-Shchukin it's "Nintex" for me.

**Comment by rloomans** [comment]
> @ben-nichols14 @viktoriia-nintex could you please tell me your org name in ADO?

For @ben-nichols14 (and me), it's `shellenergy-au`

**Comment by rloomans** [comment]
> @ben-nichols14 @viktoriia-nintex could you please tell me your org name in ADO?

@Roman-Shchukin: For @ben-nichols14 (and me), it's `shellenergy-au`

**Comment by adamth** [comment]
We have started having pipelines fail with version `0.214.2` which were previously working with `0.208.1`. We are also using the classic pipeline so pinning to an old version doesn't appear to be an option for us. Is there anything we can do?

Task output:
```
2023-01-16T05:43:12.4796226Z ##[section]Starting: npm Authenticate
2023-01-16T05:43:12.4803057Z ==============================================================================
2023-01-16T05:43:12.4803315Z Task         : npm authenticate (for task runners)
2023-01-16T05:43:12.4803502Z Description  : Don't use this task if you're also using the npm task. Provides npm credentials to an .npmrc file in your repository for the scope of the build. This enables npm task runners like gulp and Grunt to authenticate with private registries.
2023-01-16T05:43:12.4804035Z Version      : 0.214.2
2023-01-16T05:43:12.4804180Z Author       : Microsoft Corporation
2023-01-16T05:43:12.4804359Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm-authenticate
2023-01-16T05:43:12.4804610Z ==============================================================================
2023-01-16T05:43:12.7092972Z Adding authentication to the .npmrc file at /home/vsts/work/r1/a/_JBHi-Fi_shopify-theme/.npmrc
2023-01-16T05:43:12.7278225Z ##[warning]Resource file haven't been set, can't find loc string for key: SavingFile
2023-01-16T05:43:12.7291245Z ##[warning]Resource file haven't been set, can't find loc string for key: ServiceEndpointNotDefined
2023-01-16T05:43:12.7299174Z ##[error]Error: ServiceEndpointNotDefined
2023-01-16T05:43:12.7391356Z ##[section]Finishing: npm Authenticate
```

**Comment by Roman-Shchukin** [comment]
@viktoriia-nintex @adamth @rloomans @ben-nichols14 everything should work

**Comment by viktoriia-nintex** [comment]
Thank you @Roman-Shchukin it works for us now. :-) Logs show version 0.208.1 being used again, though - I thought it would be 0.214.3 or something. Not complaining, just letting you know.

**Comment by adamth** [comment]
Working for us now as well, thanks @Roman-Shchukin

**Comment by rloomans** [comment]
Working for us too. Thanks @Roman-Shchukin

**Comment by jakubtrhon** [comment]
We have the same problem in Release pipeline, is it possible to downgrade npmAuthenticate@0 task in our ADO `storeit`?

**Comment by Roman-Shchukin** [comment]
Hi @jakubtrhon, it's not related with a specific ADO org, but knowing a org helps to find reason.
Could you check now?

**Comment by jakubtrhon** [comment]
We are using deployment targets with our machines in our release pipeline and still we are using 0.214.2 version.
`2023-01-23T07:04:19.7308469Z Version      : 0.214.2`

Now we are using workaround with symlink of task 0.214.2 folder to 0.208.1 task folder in that machines which works.

**Comment by Roman-Shchukin** [comment]
Hi @jakubtrhon could you please check has it changed or not?

**Comment by jakubtrhon** [comment]
Today we deployed and NPM auth is now in version 0.216.1 which works.
`2023-01-27T13:30:26.1167521Z Version      : 0.216.1`

Thank you!

**Comment by Roman-Shchukin** [comment]
Great! Closing this issue, feel free to ask any other questions.
