### ISSUE TITLE
Bug: NpmAuthenticateV0 all failing with ##[error]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')

### ISSUE THREAD

**Issue by dustinbrooks** [microsoft/azure-pipelines-tasks#17584]
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: NpmAuthenticateV0  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: orionadvisor, OAT, 474196

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version:  Using win2022Image = "actions_virtual-environments_win22_20220828.1" from here https://github.com/actions/runner-images

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Bug: NpmAuthenticateV0 all failing with ##[error]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')

Seems to have started between late yesterday and this morning. It's affecting every single pipeline that uses the task.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[debug]SAVE_NPMRC_PATH=undefined
##[debug]Agent.BuildDirectory=/agent/_work/3
##[debug]testing directory '/agent/_work/3/npmAuthenticate'
##[debug]testing directory '/agent/_work/3'
##[debug]mkdir '/agent/_work/3/npmAuthenticate'
##[debug]set SAVE_NPMRC_PATH=/agent/_work/3/npmAuthenticate/fXwpO5
##[debug]Processed: ##vso[task.setvariable variable=SAVE_NPMRC_PATH;isOutput=false;issecret=false;]/agent/_work/3/npmAuthenticate/fXwpO5
##[debug]set NPM_AUTHENTICATE_TEMP_DIRECTORY=/agent/_work/3/npmAuthenticate
##[debug]Processed: ##vso[task.setvariable variable=NPM_AUTHENTICATE_TEMP_DIRECTORY;isOutput=false;issecret=false;]/agent/_work/3/npmAuthenticate
##[warning]Resource file haven't been set, can't find loc string for key: SavingFile
##[debug]Processed: ##vso[task.issue type=warning;]Resource file haven't been set, can't find loc string for key: SavingFile
##[debug]SavingFile /agent/_work/3/s/ApplicationSecurity/src/OAT.AuthenticationService/Web/ClientApp/.npmrc
##[debug]customEndpoint=undefined
##[debug]Getting Packaging service access points
##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/orionadvisor/
##[debug]System.ServerType=Hosted
##[debug]Getting credentials for local feeds
##[debug]Unable to get packaging URIs
##[debug]Cannot read properties of undefined (reading 'retrieveSecret')
##[debug]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')
    at Object.getEndpointAuthorization (/agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/node_modules/azure-pipelines-tasks-packaging-common/node_modules/azure-pipelines-task-lib/task.js:449:26)
    at getSystemAccessToken (/agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/node_modules/azure-pipelines-tasks-packaging-common/locationUtilities.js:111:21)
    at Object.<anonymous> (/agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/node_modules/azure-pipelines-tasks-packaging-common/locationUtilities.js:88:29)
    at Generator.next (<anonymous>)
    at /agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/node_modules/azure-pipelines-tasks-packaging-common/locationUtilities.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/node_modules/azure-pipelines-tasks-packaging-common/locationUtilities.js:4:12)
    at Object.getPackagingUris (/agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/node_modules/azure-pipelines-tasks-packaging-common/locationUtilities.js:77:12)
    at /agent/_work/_tasks/npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788/0.214.2/npmauth.js:76:56
    at Generator.next (<anonymous>)

**Comment by ramosjef** [comment]
Facing the same issue here:

![image](https://user-images.githubusercontent.com/14076772/211582991-23cb2220-0219-4d92-b53c-c535a59c66ff.png)

**Comment by Roman-Shchukin** [comment]
Hi @dustinbrooks and @ramosjef we've rolled out the fix for this issue. As a temporary solution you could specify a previous version of the task (0.208.1) in the pipeline https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions

**Comment by dustinbrooks** [comment]
@Roman-Shchukin I forced the version in some of our more important pipelines, but how long does it take for a change to release? Or is it just cached on the build agents? We use a scale set, so I could just force a new set to come up.

**Comment by ramosjef** [comment]
> Hi @dustinbrooks and @ramosjef we've rolled out the fix for this issue. As a temporary solution you could specify a previous version of the task (0.208.1) in the pipeline https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions

It worked! Thanks @Roman-Shchukin

**Comment by Roman-Shchukin** [comment]
@dustinbrooks  I can't say exactly how long it will take, but definitely a few days. I can post here when the update is done.

**Comment by dustinbrooks** [comment]
@Roman-Shchukin Okay, here is a situation, we still have some classic pipelines, is there a way to specify a minor version in classic? I'm not finding anything, which is unfortunate.

**Comment by dustinbrooks** [comment]
Seems like we have a lot of pipelines working again without changes, they appear to be pulling the older version automatically now.

**Comment by avram19** [comment]
Facing same issue in Release pipelines.

**Comment by Roman-Shchukin** [comment]
Hi @avram19. Could you please share more details about your issue? Are your release pipelines still automatically loading 0.214.2 version?

**Comment by avram19** [comment]
Yes @Roman-Shchukin ; still 0.214.2 being used. For now, I have disabled the authenticate and using the "npm" task runner with our .npmrc file and it is working fine.

![image](https://user-images.githubusercontent.com/57393228/211783907-2fcf175c-9bea-485d-a08e-c3a0ee0679c7.png)

**Comment by Roman-Shchukin** [comment]
@avram19 and @patrick-ruzand we are working on this issue

**Comment by Roman-Shchukin** [comment]
@avram19 and @patrick-ruzand could you please try to run your release pipeline?

**Comment by patrick-ruzand** [comment]
@Roman-Shchukin it works. Many thanks for the follow-up.

**Comment by avram19** [comment]
@Roman-Shchukin its working on build pipelines with version 0.212.0, but release pipelines are still using 0.214.2.

**Comment by Roman-Shchukin** [comment]
@avram19 are you using self-hosted agent?

**Comment by avram19** [comment]
@Roman-Shchukin No, we are using the cloud hosted agents.

**Comment by Roman-Shchukin** [comment]
@avram19 try now please, everything should work

**Comment by Roman-Shchukin** [comment]
Hi @dustinbrooks and @avram19, closing this one, feel free to ask any other questions or let us know if it's still relevant for you.
