### ISSUE TITLE
SqlAzureDacpacDeploymentV1 | Access Token Acquisition Error | Confidential Client is not supported in Cross Cloud request

### ISSUE THREAD

**Issue by KhanSo10** [microsoft/azure-pipelines-tasks#17598]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: SqlAzureDacpacDeploymentV1 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
![image](https://user-images.githubusercontent.com/19374196/211968392-17e2d550-feeb-4477-817a-057d86c245b2.png)

I've been a liaison of sorts on this, so please let me know if you need any more information to resolve this and I'll be happy to work on getting that.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by fvilches17** [comment]
I'm still having the same issue and waiting for a fix.

# Recap
`SqlAzureDacpacDeployment` version 1.209.0 ✅
`SqlAzureDacpacDeployment` version 1.214.0 ❌


[commit (1.209.0 --> 1.214.0)](https://github.com/microsoft/azure-pipelines-tasks/commit/f88343acf27b53cd8fa4112f76b7ac2bf84df14b#diff-c917c7bda4d8e6b6942fc2be4e884e6e56a7b7e655f3df386f43c99b674cb706)

# Workaround:

``` yaml
  - task: SqlAzureDacpacDeployment@1.209.0
    inputs:
      # inputs....
```

# References
[See task versioning in MS Docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions)

**Comment by fvilches17** [comment]
ps, just noticed above task versioning format doesn't work in YAML templates
