### ISSUE TITLE
Azure Pipeline Test Failures Not Detailed in Pipeline Test Tab

### ISSUE THREAD

**Issue by glynnharrold** [microsoft/azure-pipelines-tasks#17608]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTest@2 
![Pipeline Job Test Failure](https://user-images.githubusercontent.com/117633489/212717069-cf96082b-2288-463b-b783-aaa720681deb.png)
![Pipeline Job Test Run Summary](https://user-images.githubusercontent.com/117633489/212717086-c8d306c2-42fa-4150-b316-2237789a5b62.png)

## Environment
- Server - Azure Pipelines
    
## Issue Description

Running Azure Pipeline to execute automation tests using VSTEST@2 task a test failure was encountered and the pipeline was marked with a warning. When looking at the details of the executed Test job, the failed test is captured and the failed count is shown in Total tests/Failed counts. However, in the pipeline 'Test' tab the 'Total' and 'Failed' test counts do not include the failed test. Please see screenshots attached. 

So when we try to report on the test run using the TestManagementHttpClient to access the results, the failed test is not included.

**Comment by joshua4163** [comment]
did you solved this problem bro.If yes pls tell me how?
