### ISSUE TITLE
AzureKeyVault@2 adding AZP to secrets if they include a %

### ISSUE THREAD

**Issue by jlangford9284** [microsoft/azure-pipelines-tasks#17616]
*Type*: Bug
**Enter Task Name**: AzureKeyVault@2

- Azure Pipelines 
    
## Issue Description

When retrieving a secret from KeyVault. If this secret contains a % sign this will add AZP 

To recreate the issue.. store a password in KV that includes %.. retreive it using the task. AZP will appear next to the % sign

**Comment by v-mohithgc** [comment]
hi @jlangford9284  this issue will be fixed in version 215 [PR](https://github.com/microsoft/azure-pipelines-tasks/commit/182b6fa7755e9074b8ae0f3af283c7a84321d118#diff-7f950b4b48cdecc061fa46edf506f88ee03c9a789ae07a249e3d18e440ed1fd5)
