### ISSUE TITLE
Log version of downloaded package in DownloadPackage task

### ISSUE THREAD

**Issue by elbardel** [microsoft/azure-pipelines-tasks#17621]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DownloadPackage
 
## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

## Issue Description
The DownloadPackage task does not log the version of the package being downloaded.
This makes it very hard to debug a pipeline when the version is set to 'latest'.

Expected: the task log contains some information about the version of the package downloaded.

**Comment by phil-hodgson** [comment]
We may get to this at some point. We also accept community-created [contributions](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md).

**Comment by elbardel** [comment]
Where is the new issue on Developer Community? I can't find it.
