### ISSUE TITLE
DockerInstaller@0 fails when installing docker on macOS agents

### ISSUE THREAD

**Issue by danieljurek** [microsoft/azure-pipelines-tasks#17623]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerInstaller

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - ~If using TFS on-premises, provide the version:~
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
        - Account Name: azure-sdk
        - Project name: internal
        - Build definition name/build number: "azure-dev - cli" 4643
        - Failing build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2122651&view=logs&j=c938289d-194b-5fe6-9cfc-76481a3ab307&t=b7d7e0e3-ef01-5d7b-a1c5-57a71e94bad9

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines (macOS agents)

    - ~If using private agent, provide the OS of the machine running the agent and the agent version:~ 

## Issue Description

When running task version 0.214.0 we consistently see a failure: 
![image](https://user-images.githubusercontent.com/2158838/213243676-80d1ad8b-fc23-404b-bd0a-bc4905d2f6f0.png)

When pinning the task to version 0.209.0 we see success: 
![image](https://user-images.githubusercontent.com/2158838/213243822-d3c7b526-6c4b-4df0-a06b-77ba02463746.png)

This behavior is also visible in isolation as seen in a test job here (note different project and build definition, same effects): https://dev.azure.com/azure-sdk/playground/_build/results?buildId=2125286&view=results

### Task logs

Logs available on request. Builds showing the same behavior in isolation with debugging enabled: 

* Fail - https://dev.azure.com/azure-sdk/playground/_build/results?buildId=2125286&view=results
* Success (when version is pinned) - https://dev.azure.com/azure-sdk/playground/_build/results?buildId=2125343&view=results

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by pijemcolu** [comment]
The issue still persists.
