### ISSUE TITLE
.NET Core task prints ##[warning]Could not set the code paging of due to following error: {} on container

### ISSUE THREAD

**Issue by NenoLoje** [microsoft/azure-pipelines-tasks#17646]
### Current state

When using the `DotNetCoreCLI@2` task on a container (here: `mcr.microsoft.com/dotnet/sdk:6.0`) it succeeds, but prints the following warning:

> ##[warning]Could not set the code paging of due to following error: {} on container

Screenshot:
> ![grafik](https://user-images.githubusercontent.com/13981145/213774050-e5e2e1bb-8d51-42f7-bbac-2ce4a2cd23f1.png)

### Desired state

Should not print a warning (= same behavior as without using a container to run the build)

### Environment

- This is on the hosted service
- vmImage: `windows-latest`
- container: `mcr.microsoft.com/dotnet/sdk:6.0`

**Comment by NenoLoje** [comment]
Anyone else seeing this?

**Comment by kinnajowa** [comment]
I also experience this
