### ISSUE TITLE
InstallAppleCertificate: install certificates and identities from files on agent

### ISSUE THREAD

**Issue by Jaharmi** [microsoft/azure-pipelines-tasks#17664]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: InstallAppleCertificate  

## Environment
- Azure Pipelines (cloud), no specific project / build
- Hosted Agent, macOS 12

## Issue Description

TL:DR; The `InstallAppleCertificate` task only works for `p.12` certificates uploaded as secure files. An option to source a certificate or signing identity from files on the agent would be helpful. This ability would enable more flexibility in pipelines on macOS.

The source files should be in any format compatible with import to a macOS keychain.

This is similar to #13913.

It is also similar to #17663 regarding Azure Key Vaults. Direct access to Azure Key Vaults would be _most_ preferable because that would potentially offer more end-to-end security/privacy for the whole certificate/identity import process in a pipeline.

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by DmitriiBobreshev** [comment]
Hi again @Jaharmi, thank again! I'll add the issue to our backlog as well.
