### ISSUE TITLE
InstallAppleCertificate: install certificates and identities from Azure Key Vault

### ISSUE THREAD

**Issue by Jaharmi** [microsoft/azure-pipelines-tasks#17663]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: InstallAppleCertificate  

## Environment
- Azure Pipelines (cloud), no specific project / build
- Hosted Agent, macOS 12

## Issue Description

TL:DR; The `InstallAppleCertificate` task only works for `p.12` certificates uploaded as secure files. An option to source a certificate or signing identity from Azure Key Vault would be welcome and a logical improvement to this task. Such a task would make for _much_ better pipelines with code signing on macOS agents.

Without this, the pipeline might be able to use `AzureKeyVault` task. The `AzureKeyVault` task's output is [documented as producing `.pfx` data](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-key-vault-v2?view=azure-pipelines#prerequisites), but _not_ a file. Starting with `AzureKeyVault` would require saving that output to a file, a possible conversion of the file format, an upload of the file to the pipeline's secure files, and _then_ use of `InstallAppleCertificate` to download it again. After this, the secure file may need to be removed so as to avoid leaving that data in secure files.

This is similar to #13913.

### Task logs

N/A

## Troubleshooting

N/A

### Error logs

N/A

**Comment by DmitriiBobreshev** [comment]
Hi @Jaharmi, thank you for the great idea! Unfortunately, we are working on more prioritized issues at the moment, I'll add the issue to our backlog and we will get back to this one as soon as we can
