### ISSUE TITLE
Getting warning from Sql task on hosted Windows agent

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/azure-pipelines-tasks#17677]
```
==============================================================================
Task         : Azure SQL Database deployment
Description  : Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
Version      : 1.216.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment
==============================================================================
Added TLS 1.2 in session.
##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.


```

**Comment by DSPolicyFilter** [comment]
I am also getting this from AzureFileCopy@3

```
Added TLS 1.2 in session.
Import-Module -Name C:\modules\azurerm_6.13.1\AzureRM\6.13.1\AzureRM.psd1 -Global
Clear-AzureRmContext -Scope Process
Clear-AzureRmContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Add-AzureRMAccount -ServicePrincipal -Tenant XXX -Credential System.Management.Automation.PSCredential -Environment AzureCloud
 Set-AzureRmContext -SubscriptionId XXX -TenantId XXX
##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
```

**Comment by Luuk2022** [comment]
Receiving same warning on on-premises. Any solutions?

**Comment by gavinheaden** [comment]
Same warnings on AzureFileCopy@4 and AzureFileCopy@5 as well.

**Comment by candritzky** [comment]
Same here with `AzureFileCopy@4`.

**Comment by pebroz** [comment]
> 
Output from AzureFileCopy@5 task:

`==============================================================================
Task         : Azure file copy
Description  : Copy files to Azure Blob Storage or virtual machines
Version      : 5.216.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy
==============================================================================
Added TLS 1.2 in session.
##[command]Import-Module -Name C:\Modules\az_9.2.0\Az.Accounts\2.11.1\Az.Accounts.psd1 -Global
##[warning]Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide
##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
##[command]Clear-AzContext -Scope Process
##[command]Connect-AzAccount -ServicePrincipal -Tenant xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
##[command] Set-AzContext -SubscriptionId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -TenantId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
##[command]Import-Module -Name C:\Modules\az_9.2.0\Az.Resources\6.5.0\Az.Resources.psd1 -Global
##[command]Import-Module -Name C:\Modules\az_9.2.0\Az.Storage\5.2.0\Az.Storage.psd1 -Global
##[command]Import-Module -Name C:\Modules\az_9.2.0\Az.Compute\5.2.0\Az.Compute.psd1 -Global
##[command]Import-Module -Name C:\Modules\az_9.2.0\Az.Network\5.2.0\Az.Network.psd1 -Global
##[warning]The names of some imported commands from the module 'Microsoft.Azure.PowerShell.Cmdlets.Network' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
##[warning]The names of some imported commands from the module 'Az.Network' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.`

**Comment by arnokoster** [comment]
We have the same problem: AzureFileCopy@4 and AzureFileCopy@5 output the 
##[warning]The command ‘Get-SpnAccessToken’ is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
line.
Until now this we perceived no functional degradation yet but it remains to be seen until what date and time we can use the function...

It seems that version 5 is the latest version so an update of the AzureFileCopy component would be very welcome

**Comment by hbendev** [comment]
I'm getting the same warning message on AzureFileCopy version 3.216.2 on a MS hosted Windows vm. 

```
Import-Module -Name C:\modules\azurerm_6.13.1\AzureRM\6.13.1\AzureRM.psd1 -Global
Clear-AzureRmContext -Scope Process
Clear-AzureRmContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Add-AzureRMAccount -ServicePrincipal -Tenant x-y-z -Credential System.Management.Automation.PSCredential -Environment AzureCloud
 Set-AzureRmContext -SubscriptionId x-y-z -TenantId x-y-z
##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
```

Agent details:
```
Current agent version: '2.217.2'
Operating System: Microsoft Windows Server 2022 10.0.20348 Datacenter
Runner Image: windows-2022, Version: 20230129.1
Runner Image Provisioner: 2.0.98.1
```

**Comment by ssisjoost** [comment]
Me too 
![image](https://user-images.githubusercontent.com/24233397/218084943-fb7badca-3740-41e0-a03a-c977f390b93b.png)

**Comment by AnKiLa** [comment]
Same here for Azure File Copy Task @5.216.2, even after upgrading all components to latest version and implementing new AZ powershell modules instead of AzureRM modules on the build  agent,
![image](https://user-images.githubusercontent.com/78601258/218437122-cc6383aa-3ef5-403a-9763-9e5e80e14665.png)

**Comment by shaosh** [comment]
Same here. We are seeing the same warning in both Azure File Copy Task @3 and 5.

**Comment by mlovisek** [comment]
Same here. V4 and 5
##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.

**Comment by kevchant** [comment]
Since somebody asked me about this I looked into it.

It looks like it is due to the update to VstsAzureRestHelpers_.psm1 from November 17 last year. Might be worth checking if another update elsewhere has been delayed.

https://github.com/microsoft/azure-pipelines-tasks/commit/f88343acf27b53cd8fa4112f76b7ac2bf84df14b#diff-e7717abe1d4a4bc136d4e37c1e2695fc81b89047c49dfd7adf9b155d9135a2b9

**Comment by mstjernfelt** [comment]
+1

**Comment by Nubbe** [comment]
When running DACPAC task we get the same warning but when enabling "System.Debug" logging I became aware of an environment variable named USE_MSAL.

Result with default value for USE_MSAL (empty)
```
##[debug]Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
##[debug]USE_MSAL (empty)
##[debug]MSAL - useMSAL = False
##[warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
##[debug]Processed: ##vso[task.logissue type=warning]The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed.
##[debug]MSAL - Get-EnvironmentAuthUrl - endpoint=@{Url=https://management.azure.com/; Data=; Auth=}
##[debug]MSAL - Get-EnvironmentAuthUrl - useMSAL=False
##[debug]MSAL - Get-EnvironmentAuthUrl - envAuthUrl=https://login.windows.net/
##[debug]Fetching Access Token
```
Result with USE_MSAL set to true
```
##[debug]Get-AzureRMAccessToken - started - endpoint=@{Url=https://management.azure.com/; Data=; Auth=} - scheme=ServicePrincipal
##[debug]USE_MSAL: 'true'
##[debug]MSAL - USE_MSAL override is found: true
##[debug]MSAL - useMSAL = True
##[debug]MSAL - Get-EnvironmentAuthUrl - endpoint=@{Url=https://management.azure.com/; Data=; Auth=}
##[debug]MSAL - Get-EnvironmentAuthUrl - useMSAL=True
##[debug]MSAL - Get-EnvironmentAuthUrl - envAuthUrl=https://login.microsoftonline.com/
##[debug]MSAL - ServicePrincipal - clientSecret is used.
##[debug]Fetching Access Token - MSAL
```

Hopefully this helps.

**Comment by elninoisback** [comment]
Thank you @Nubbe. Setting a variable USE_MSAL=true actually works!

**Comment by mamohanma** [comment]
Hi @Nubbe ,

Can you please let me know where need to configure the value in Azure Devops pipeline?

**Comment by celluj34** [comment]
@mamohanma Just add a variable with key USE_MSAL and value "true". What I did was use powershell to write the variable just for the task: `Write-Host "##vso[task.setvariable variable=USE_MSAL]true"`

**Comment by mamohanma** [comment]
Hi @celluj34 ,

Thanks for your information. 
Actually I am not familiar with Azure DevOps. So do you have any reference link for this setup.?
We are using Azure DevOps pipeline, within that we configured the SQL deployment. in that SQL deployment we are getting the warning "The command 'Get-SpnAccessToken' is obsolete. Use Get-AccessTokenMSAL instead. This will be removed".

**Comment by celluj34** [comment]
Literally all you need to do is, before your SQL task, add a powershell (or bash, or whatever is appropriate) task and `Write-Host` (or `echo`, for bash) the `task.setvariable` command I wrote above. That's it.

**Comment by porf25** [comment]
> Literally all you need to do is, before your SQL task, add a powershell (or bash, or whatever is appropriate) task and `Write-Host` (or `echo`, for bash) the `task.setvariable` command I wrote above. That's it.

This worked for me in the in my release pipeline, thank you sir.

**Comment by robmaas** [comment]
For people having trouble with implementing it, here's an example:

```yaml
steps:
  - powershell: Write-Host "##vso[task.setvariable variable=USE_MSAL]true"
    displayName: USE MSAL
    
    ... (other tasks)
```

**Comment by fgheysels** [comment]
> Literally all you need to do is, before your SQL task, add a powershell (or bash, or whatever is appropriate) task and `Write-Host` (or `echo`, for bash) the `task.setvariable` command I wrote above. That's it.

Can't you use the [`env` property on the task](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-task?view=azure-pipelines) as well for this ?   Haven't tested it, but I think this would be more elegant :)

**Comment by celluj34** [comment]
You can! But I already had a script doing stuff so I just put it there.

**Comment by arnokoster** [comment]
Regrettably this did not solve the issue for me. The variable has been set but in the following call of azure file copy I still get warning and error messages:

##[warning]The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user profile ( C:\Windows\system32\config\systemprofile\.Azure ). Please ensure that this directory has appropriate protections.

##[error]ExceptionMes***ge: ExceptionMes***ge: Authentication failed. The 'Authorization' header is provided in an invalid format. (in function: Get-AzRmResourceGroup) (in function: Get-AzRMStorageKeys)

although the warning does not seem to imply a big deal the error still will have to be fixed.

**Comment by robkendrick** [comment]
> For people having trouble with implementing it, here's an example:
> 
> ```yaml
> steps:
>   - powershell: Write-Host "##vso[task.setvariable variable=USE_MSAL]true"
>     displayName: USE MSAL
>     
>     ... (other tasks)
> ```

Actually, if you're using YAML pipelines, you can define this with your other variables:
```yaml
variables:
  # These variables are for testing and deugging.
  buildTestOnly: false
  devTestOnly: false
  system.debug: false
  USE_MSAL: true # https://github.com/microsoft/azure-pipelines-tasks/issues/17677

  # If all tests have passed, we can set prodReady to true.
  prodReady: true
```

**Comment by dekkermg** [comment]
> My pipeline says "user can't override USE_MSAL system variable" when I try and override it in the variables.
> 
> ```
> ##[error]Unable to process command '##vso[task.setvariable variable=USE_MSAL]true' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
> ##[error]Overwriting readonly variable 'USE_MSAL' is not permitted. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
> ```

I had the same error. Could it be that it's true by default now? I removed the script to set it to true, but the warnings or errors from before did not return.
