### ISSUE TITLE
Azure tfs repo task failed to create workspace and checkout files

### ISSUE THREAD

**Issue by weiliucs** [microsoft/azure-pipelines-tasks#17680]
See below log.
- looks like workspace was created with different identity previously vs now;
- randomly repro. There is no change in pipeline, either config or code. 

Prepending Path environment variable with directory containing 'tf.exe'.
Setting environment variable TFVC_BUILDAGENT_POLICYPATH
Querying workspace information.
tf @tfs_cmd_ff3e433a-d107-439f-93f0-580ec3328b45.txt

D:\a\_work\31\s> vc workspace /new /location:local /permission:Public ws_31_31 /collection:https://dev.azure.com/GlobalProductServices/ /loginType:OAuth /login:.,*** /noprompt
The path D:\a\_work\31\s\HB\PhoenixUDCAchievements is already mapped in workspace ws_31_31;Build\6cecea84-5ed3-xxxx-xxxx-xxxx.
Sleeping for 200 ms
Retrying. Attempt 2/3
tf @tfs_cmd_0283a027-60df-44ff-a8ce-78e8e1f1fa6c.txt

D:\a\_work\31\s> vc workspace /new /location:local /permission:Public ws_31_31 /collection:https://dev.azure.com/GlobalProductServices/ /loginType:OAuth /login:.,*** /noprompt
The path D:\a\_work\31\s\HB\PhoenixUDCAchievements is already mapped in workspace ws_31_31;Build\6cecea84-5ed3-xxxx-xxxx-xxxx.
Sleeping for 1000 ms
Retrying. Attempt 3/3
tf @tfs_cmd_f7bbaeb6-5696-4833-8cc2-6b2f269d0937.txt

D:\a\_work\31\s> vc workspace /new /location:local /permission:Public ws_31_31 /collection:https://dev.azure.com/GlobalProductServices/ /loginType:OAuth /login:.,*** /noprompt
The path D:\a\_work\31\s\HB\PhoenixUDCAchievements is already mapped in workspace ws_31_31;Build\6cecea84-5ed3-xxxx-xxxx-xxxx.
##[error]Exit code 100 returned from process: file name 'tf', arguments '@tfs_cmd_f7bbaeb6-5696-4833-8cc2-6b2f269d0937.txt'.

**Comment by weiliucs** [comment]
Digging into this a little. Just found the conflict account are Project Build Service vs. Project Collection Build Service. Does the task pick one of these two randomly?

**Comment by jessehouwing** [comment]
The job uses the Project Build Service or the Collection Build Service depending on whether the pipeline is allowed to access only the project or the whole collection:

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/4173387/3c18d73c-8212-4eaa-9475-8607391f68a0)

**Comment by jessehouwing** [comment]
What version of the agent are you running? There snuck a few bugs into the cleanup code a year ago and if you're on Azure DevOps Server, it won't auto-upgrade to a version without issues.
