### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues from AzureFunctionApp@1

### ISSUE THREAD

**Issue by nlok-peter** [microsoft/azure-pipelines-tasks#17702]
When using AzureFunctionApp@1 task to deploy function app to azure through Azure Devops, the following warning was observed:

**(node:3660) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.**

Would be great if there is way to resolve this. Thanks!

**Comment by ayoussef-insight** [comment]
Having the same issue with AzureFunctionApp@2 as well

**Comment by TomasMalecek** [comment]
Guess this task is not as popular as AzureResourceManagerDeployment@3 where this got fixed in https://github.com/microsoft/azure-pipelines-tasks/issues/19821 and https://github.com/microsoft/azure-pipelines-tasks/pull/20994.
