### ISSUE TITLE
Support Node.js 18 for Azure Function App Deploy

### ISSUE THREAD

**Issue by mshyatsu** [microsoft/azure-pipelines-tasks#17713]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Azure Function App Deploy

## Environment
- Server - Azure Pipelines 

- Agent - N/A

## Issue Description

Please add version support for Node.js 18.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFunctionAppV2/task.json#L127-L131
![image](https://user-images.githubusercontent.com/74396258/217184963-c8f3df2b-7bda-4e97-8865-a1075b936b92.png)

**Comment by mshyatsu** [comment]
Hi @nadesu , thanks for supporting this issue. The EOL of Node.js 14 is the end of April, so we need to migrate the version to Node.18. I would appreciate it if Node.js 18 could be available by the end of February. Do you have an ETA for Node.js18? Thanks.

**Comment by mshyatsu** [comment]
@nadesu 
Once the release date is determined, I would like you to share the date here for visibility from users.

**Comment by FinVamp1** [comment]
This should be released by now.
