### ISSUE TITLE
Bash fails on Windows when the tool and the agent are located on different disks

### ISSUE THREAD

**Issue by DenisRumyantsev** [microsoft/azure-pipelines-tasks#17732]
**Type:** Bug
**Task:** Bash

## Description

The `Bash` task fails if the `work/temp` directory of the Self-Hosted Windows Agent and the `bash` tool are located on different file systems.

## Root cause

This is the environment issue related to mounting the file system on which the `work/temp` agent directory is located.

It looks like the `cwd` option of [the `spawn` method](https://github.com/microsoft/azure-pipelines-task-lib/blob/7d04ce6cdbd7a760ebfe3338ae9d8a6480dd1e59/node/toolrunner.ts#L907) from the `child_process` Node.js module used on the `task-lib` side does not work properly, and the `Bash` task fails to translate via [the related function](https://github.com/microsoft/azure-pipelines-tasks/blob/652c14cf57e3cf6fdb9feed6f753cada7a7ded18/Tasks/BashV3/bash.ts#L7) the `work/temp` agent directory, which contains the `bash` script to be executed and is located on another file system.

## Actions

Implement a warning to the `Bash` task output if the issue has been detected.

## Reproducing

Via pipeline:

```yml
pool: Self-Hosted Agent Pool

steps:
- bash: echo "Hello, World!"
```

Here is a simple Node.js script to reproduce this issue locally:

```js
const { spawn } = require('child_process');

const child = spawn('C:\\windows\\system32\\bash.exe', [ '-c', 'pwd' ], {
    cwd: 'D:\\<path-to-agent-root-directory>\\_work\\_temp', // Actual
    // cwd: 'C:\\Temp', // ---> Expected and received: /mnt/c/Temp
    // cwd: 'D:\\Temp', // ---> Expected: /mnt/d/Temp | Received: /home/<username>
    env: undefined,
    shell: undefined,
    windowsVerbatimArguments: false
});

child.stdout.on('data', data => console.log(data.toString()));
```

## Logs

```
##[debug]exec tool: C:\windows\system32\bash.exe
##[debug]arguments:
##[debug]   -c
##[debug]   pwd
C:\windows\system32\bash.exe -c pwd
/home/<username>
##[debug]Exit code 0 received from tool 'C:\windows\system32\bash.exe'
##[debug]STDIO streams have closed for tool 'C:\windows\system32\bash.exe'
========================== Starting Command Output ===========================
##[debug]which 'C:\windows\system32\bash.exe'
##[debug]found: 'C:\windows\system32\bash.exe'
##[debug]C:\windows\system32\bash.exe arg: /home/<username>/<uuid>.sh
##[debug]exec tool: C:\windows\system32\bash.exe
##[debug]arguments:
##[debug]   /home/<username>/<uuid>.sh
C:\windows\system32\bash.exe /home/<username>/<uuid>.sh
/bin/bash: /home/<username>/<uuid>.sh: No such file or directory
##[debug]Exit code 127 received from tool 'C:\windows\system32\bash.exe'
##[debug]STDIO streams have closed for tool 'C:\windows\system32\bash.exe'
##[error]Bash exited with code '127'.
```

**Comment by max-zaytsev** [comment]
Update message
