### ISSUE TITLE
Label image.base.digest have wrong value when base image is specified with digest other then the latest one

### ISSUE THREAD

**Issue by Grekkq** [microsoft/azure-pipelines-tasks#17774]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Docker  

## Issue Description

Description of the label image.base.digest that is added during docker build [suggests](https://github.com/opencontainers/image-spec/blob/819aa940cae7c067a8bf89b1745d3255ddaaba1d/annotations.md?plain=1#L46) that it should have the digest of base image that was used as a base:

> org.opencontainers.image.base.digest Digest of the image this image is based on (string)
> This SHOULD be the immediate image sharing zero-indexed layers with the image, such as from a Dockerfile FROM statement.
> This SHOULD NOT reference any other images used to generate the contents of the image (e.g., multi-stage Dockerfile builds).

But it breaks if we specify digest directly in Dockerfile, eg: `FROM ubuntu@sha256:123412343`, the label will contain digest from `ubuntu:latest` and not the one specified in Dockerfile, as it will be lost during [this](https://github.com/microsoft/azure-pipelines-tasks/blob/a9ca03cb061a8c3c36a7d996dbf1f17ebd5f0b6a/common-npm-packages/docker-common-v2/pipelineutils.ts#L56):
```ts
function addBaseImageLabels(connection: ContainerConnection, labels: string[], dockerFilePath: string): void {
    const baseImageName = containerUtils.getBaseImageNameFromDockerFile(dockerFilePath); // Internally uses sanityzeBaseImage
    if (!baseImageName) {
        return;
    }
    // base name will be correctly set to `ubuntu`
    addLabelWithValue("image.base.ref.name", baseImageName, labels);

    if (!connection) {
        tl.debug("Image digest couldn't be extracted because no connection was found.");
        return;
    }
    // but this will pull latest `ubuntu` image and return its digest instead of the one specified in Dockerfile
    const baseImageDigest = containerUtils.getImageDigest(connection, baseImageName);
    if (baseImageDigest) {
        addLabelWithValue("image.base.digest", baseImageDigest, labels);
    }
}
```

```ts
function sanityzeBaseImage(baseImage: string): string {
    if (!baseImage){
        return null;
    }

    // If the baseimage name contains the digest we should remove the digest from its name
    // ubuntu:16.04@sha256:123412343 should be just ubuntu:16.04
    let baseImageComponents: string[] = baseImage.split("@");

    return baseImageComponents[0];
}
```

### Task logs

Should not be needed to resolve, but can be prepared if necessary

**Comment by gholliday** [comment]
I've noticed this too. The digest specified in the Dockerfile is completely ignored for the `image.base.digest` label.

**Comment by ingbbmaster** [comment]
I've prepared fixes for that to work with digests and not to break the current tag based behaviour. If somebody could test it, cause we've been unable to configure it on Azure DevOps organization to be able to run and test those changes:

//azure-pipelines-tasks/common-npm-packages/docker-common-v2/containerimageutils.ts

export function getBaseImageDigestDockerFile(dockerFileContent: string): string {
    // This method checks if there is FROM image@sha256:digest present in Dockerfile
    // if matched it returns digest
    // if not, it returns null

    try {
        if (!dockerFileContent || dockerFileContent == "") {
            return null;
        }

        var lines = dockerFileContent.split(/[\r?\n]/);
        var aliasToImageNameMapping: Map<string, string> = new Map<string, string>();
        var baseImage = "";

        for (var i = 0; i < lines.length; i++) {
            const currentLine = lines[i].trim();
            if (!currentLine.toUpperCase().startsWith("FROM")) {
                continue;
            }
            var nameComponents = currentLine.substring(4).toLowerCase().split(" as ");
            var prospectImageName = nameComponents[0].trim();

            if (nameComponents.length > 1) {
                var alias = nameComponents[1].trim();

                if (aliasToImageNameMapping.has(prospectImageName)) {
                    aliasToImageNameMapping.set(alias, aliasToImageNameMapping.get(prospectImageName));
                } else {
                    aliasToImageNameMapping.set(alias, prospectImageName);
                }

                baseImage = aliasToImageNameMapping.get(alias);
            } else {
                baseImage = aliasToImageNameMapping.has(prospectImageName)
                    ? aliasToImageNameMapping.get(prospectImageName)
                    : prospectImageName;
            }
        }

        return baseImage.split('@')[1].split(':')[1];
    } catch (error) {
        tl.debug(`An error ocurred getting the base image digest. ${error.message}`);
        return null;
    }
}

//azure-pipelines-tasks/common-npm-packages/docker-common-v2/pipelineutils.ts
    var baseImageDigest = containerUtils.getBaseImageDigestDockerFile(dockerFilePath);

    //first check if there is digest passed in Dockerfile
    if (!baseImageDigest) {
        baseImageDigest = containerUtils.getImageDigest(connection, baseImageName);
    }

    //if not there is no digest in Dockerfile, get digest using ImageName:tag
    if (baseImageDigest) {
        addLabelWithValue("image.base.digest", baseImageDigest, labels);
    }

So as you can see there is additional check for image with digest instead of tag in dockerfile. That feature had been missing.
