### ISSUE TITLE
Support for Java 17  in Gradle Task

### ISSUE THREAD

**Issue by fte7fe** [microsoft/azure-pipelines-tasks#17782]
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: Gradle  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GradleV3

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - I am using azure pipeling and i cannot provide a build definition because my gradle build wont even run without java 17

- Agent - Hosted or Private: 
    
    - Hosted : For now no point in creating the pipeline 

## Issue Description

As mentioned in https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/gradle-v3?view=azure-pipelines
And also what you see if you configure the task, there is no option to use jdk 17 with gradle, the maven task already support jdk17 for instance.

There are already PR for this but those have been marked as stale :
https://github.com/microsoft/azure-pipelines-tasks/pull/16458
https://github.com/microsoft/azure-pipelines-tasks/pull/16160

The maven PR is the following:
https://github.com/microsoft/azure-pipelines-tasks/pull/15844

There seem to be a workaround documented here , could be nice in the documentation : https://github.com/microsoft/azure-pipelines-tasks/issues/15647

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by DenisRumyantsev** [comment]
Hi, @fte7fe, thanks for reporting this issue, we will work on it.

**Comment by LiliaSabitova** [comment]
Hi @fte7fe, PR has been merged.

**Comment by ps-tunnelsoft** [comment]
Hi, the PR was merged. I would like to know how long it will take to have the selection available in gradle devops task? 

![image](https://user-images.githubusercontent.com/74701826/223690684-ec3b263f-4ccd-44ea-9986-38db324fc2f2.png)

**Comment by breucode** [comment]
Same question here. I am setting up a new project and I don't want to work around this issue for just a few weeks.

**Comment by amolpednekar** [comment]
Same question - Java 17 is the latest LTS, but do not see a way to configure it - latest seems to be JDK 11 ?
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/gradle-v3?view=azure-pipelines

**Comment by amolpednekar** [comment]
@breucode Looks like it can still be configured in the pipeline, the official docs are not updated: https://github.com/microsoft/azure-pipelines-tasks/issues/15647#issuecomment-1112186456
