### ISSUE TITLE
Breaking change in InvokeRESTAPI

### ISSUE THREAD

**Issue by MatthewSteeples** [microsoft/azure-pipelines-tasks#17781]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: InvokeRESTAPI

## Issue Description

[This Pull Request](https://github.com/microsoft/azure-pipelines-tasks/pull/17622) changes the default behaviour of InvokeRESTAPI in ways that breaks existing workflows. If you were relying on that default value then your workflows will now timeout after an hour, because rather than honour the response, the task now waits for a callback that is never coming.

I don't disagree with the new behaviour, but in my opinion this should have required a major version bump.

Additionally, are there release notes for this kind of change that we can subscribe to? Our builds have been broken since Friday and it's taken us best part of a day's worth of dev time to track down this issue.

**Comment by MatthewSteeples** [comment]
Additionally, the [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml) have not been updated to reflect this change

**Comment by mkonjikovac** [comment]
Hi @MatthewSteeples, thanks for bringing this to our attention, and sorry for the inconvenience. We are now enforcing the use of version 1.198.0 of the task, so its previous behavior will be respected. The default value of waitForCompletion parameter will be set to false (ApiResponse). However, we are moving towards changing the default value of this parameter to Callback, but once we do that we will make sure to better announce this change, update the docs and, of course, not affect the existing workflows. Same goes for task AzureFunctionV1.
