### ISSUE TITLE
Jenkins TFS Plugin throwing Bad Request error

### ISSUE THREAD

**Issue by madhu3984** [microsoft/azure-pipelines-tasks#17807]
Hi Team,

We are using TFS Plugin in our Build Validation pipeline on Azure DevOps Server/Services to queue a Jenkins job. When the Pipeline runs, I am seeing below error message.

Job creation failed.
HttpResponse.statusCode=400
HttpResponse.statusMessage=Bad Request
HttpResponse=
{"statusCode":400,"body":"java.lang.IllegalArgumentException: Job: micromanager-service/ not found\n\tat hudson.plugins.tfs.TeamBuildEndpoint.getJob(TeamBuildEndpoint.java:269)

We have this job micromanager-service on our Jenkins server and not sure why the Bad Request error is.

Appreciate any help on this please.

I am using TFS plugin of Version 5.157.1 

Jenkins is of Version 2.375.1

Thanks in advance.

Regards,
Madhu M

**Comment by max-zaytsev** [comment]
@madhu3984 this repo is about in-the-box tasks
it seems like you need to open an issue here https://github.com/jenkinsci/tfs-plugin to get the right eyes on it.
