### ISSUE TITLE
Source generators have been disabled on the current configuration, as they need Roslyn 4.x, XamariniOS task

### ISSUE THREAD

**Issue by IvanZosimov** [microsoft/azure-pipelines-tasks#17823]
## Required Information

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: XamariniOS@2 

## Issue Description

The issue was born here: https://github.com/actions/runner-images/issues/5782 . It turned out that the required functionality of the MVVM Toolkit (namely from version 8.0.0 preview1) is available only with Roslyn 4.x, but currently, Mono has only Roslyn [3.9.0-5.21112.8](https://github.com/mono/msbuild/blob/xplat-master/eng/Versions.props#L13). During the investigation: https://github.com/actions/runner-images/issues/5782#issuecomment-1202815693 , https://github.com/actions/runner-images/issues/5782#issuecomment-1246886433 I discovered that by using the `dotnet build` command, it is possible to workaround this bug and use the Roslyn compiler, which is bundled with the.NET SDK and stored in the runner's tool cache (rather than from Mono), when building the Xamarin project.

Is it possible for the XamariniOS task to use Roslyn compiler which is bundled with .NET SDK instead of one from the Mono? I filed an [issue](https://github.com/mono/mono/issues/21529) to update Roslyn in the Mono project last August, but still there is no answer from them.

**Comment by AdamDiament** [comment]
@IvanZosimov thanks for raising this ticket. 

Unfortunately I can't get the workaround to work - I've posted what I've tried here https://github.com/actions/runner-images/issues/5782#issuecomment-1499854986 - do you know if I am missing a step?

**Comment by AdamDiament** [comment]
So annoying that this was closed! It's not stale, just waiting for a reply.
