### ISSUE TITLE
UseDotNetV2: pre-installed SDK version undetected by task

### ISSUE THREAD

**Issue by fabrideci** [microsoft/azure-pipelines-tasks#17834]
Hi community,

It looks like the UseDotNetV2 task is not able to detect a pre-installed SDK version on the first run on a self-hosted agent, as it looks for a specific installation complete marker file under folder "agent\\_work\\_tool\dotnet",  that is not created with available installation methods e.g., the [dotnet-install script](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). 

Therefore, if you pre-install the SDK version x.y.z on a self-hosted agent, and run the UseDotNetV2 task on the same machine asking for the same exact x.y.z version, it won't use the local version (caching) but download and install the whole SDK again even if already there.

The detection logic is at:

https://github.com/microsoft/azure-pipelines-tasks/blob/55e83827dc646cc61971b226d4c77da35616d167/Tasks/UseDotNetV2/versioninstaller.ts#L95

While the installation complete marker creation here:

https://github.com/microsoft/azure-pipelines-tasks/blob/55e83827dc646cc61971b226d4c77da35616d167/Tasks/UseDotNetV2/versioninstaller.ts#L112

I would remove such installation complete marker logic as it prevents from using a pre-installed SDK version, but I'm not sure if that was done for specific reasons.

Anyone can advice here?

**Comment by ismayilov-ismayil** [comment]
Hi @fabrideci, thanks for your feedback. We try to keep agent's dependencies isolated. Thus, even you have any pre-installed sdk, git client or similar, agent tries to install it locally unless there is any possibility to use machine's one (ex: JavaToolInstaller)

**Comment by fabrideci** [comment]
Thanks @ismayilov-ismayil, I understand the isolation concern, nevertheless the task already checks the presence of the requested dotnet version folder under agent’s directory, **but if there is no marker file too**, it downloads and reinstalls it again loosing precious time it would have saved going with the pre-installed one. 

I’m questioning the marker file logic, why not checking only the presence of the sdk and going with that if the requested version match?
