### ISSUE TITLE
GoTool: support reading Go version from go.mod file

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/azure-pipelines-tasks#17848]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

## Environment
- Server - Azure pipelines

- Agent - Hosted (Ubuntu)

## Issue Description

The GitHub Action to install Go has a very nifty feature that allows detecting the version of Go to install from a go.mod file: https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file

This is incredibly useful to us (Dapr) as we want to make sure that every branch of our project is built with the correct version of Go. For example, our current development branch requires Go 1.20, but the last release was built with Go 1.19.

**Comment by ItalyPaleAle** [comment]
This is still very much useful for us. I was OOF and didn't see the notification till now

**Comment by gravufo** [comment]
I created a PR for this. Hopefully we could get this issue reopened.
