### ISSUE TITLE
Release Pipeline: `This task must run in a build to publish artifacts to Azure Pipelines.`

### ISSUE THREAD

**Issue by DenysAshikhin** [microsoft/azure-pipelines-tasks#17850]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: `Question`

**Enter Task Name**:  `PublishBuildArtifacts`

## Environment
- Server - Azure Release Pipeline
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account Name: `Denys Ashikhin`
Team Project Name: `UniTwin_InSiteTracker`

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: `Hosted Windows 2019 with VS2019`

## Issue Description

I am following the general steps from the following: https://youtu.be/_sUf0wqJYXo?t=363
To create the artifact in the release pipeline instead of a build pipeline. The goal here is to have a release control that can be quickly used to reference different modules for a specific release.

The following images the current setup with 4 `artifacts` (modules) being archived into the stagingDirectory where I attempt to publish .zips as in artifact. 
![image](https://user-images.githubusercontent.com/10791321/221941621-f3008cc7-68ad-4b2b-96ce-6fd387c45d54.png)

But get the following error:
`This task must run in a build to publish artifacts to Azure Pipelines.`

Is there a way to make it work in releases? Or is there a way to access the zips after the deployment is completed another way?
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
[ReleaseLogs_9.zip](https://github.com/microsoft/azure-pipelines-tasks/files/10853611/ReleaseLogs_9.zip)

**Comment by ismayilov-ismayil** [comment]
Hi @DenysAshikhin thanks for your feedback. As mentioned in the error log, you can use PublishArtifactTask in the build pipeline rather than release.

**Comment by DenysAshikhin** [comment]
Is it possible to achieve something similar with the release pipeline?
And if not, is it possible to access the deployed staging/build folder manually?
