### ISSUE TITLE
Azure cli task fails with exit code 1

### ISSUE THREAD

**Issue by vivek602** [microsoft/azure-pipelines-tasks#17868]
## Note  
azure cmdLine@2 tasks fails with exit code 1

output:

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Question*: Azure cli task "cmdLine@2 is failing with exit code 1"

**Enter Task Name**: cdmLine@2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines ?
    
    -
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Linux

## Issue Description

I am trying to create squash merge from feature to main branch through azure cli tasks and while doing that the job is failing with exit code 1, I am unable to understand the reason of it. Please help

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
git remote set-url origin https://***@github.com/*********/tim-actpm-integration-OI-discount.git
+ git remote set-url origin https://***@github.com/*********/tim-actpm-integration-OI-discount.git
git config --global user.email "************@d.com"
+ git config --global user.email ************.im@d.com
git config --global user.name "************"
+ git config --global user.name *************
echo "Squash Merge 1.242.5 to main"
+ echo 'Squash Merge 1.242.5 to main'
git fetch --tags origin
+ git fetch --tags origin
Squash Merge 1.242.5 to main
git merge --squash 1.242.5
+ git merge --squash 1.242.5
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
git commit -m "Squash Merge of 1.242.5"
+ git commit -m 'Squash Merge of 1.242.5'
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
##[debug]Exit code 1 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[error]Bash exited with code '1'.
 

[Insert error from the logs here for a quick overview]

**Comment by vivek602** [comment]
can you please help?

**Comment by LiliaSabitova** [comment]
Hi @vivek602, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.
