### ISSUE TITLE
[Question]: Is it possible to use the publish symbols task in a release pipeline?

### ISSUE THREAD

**Issue by eddynaka** [microsoft/azure-pipelines-tasks#17872]
### Task name

PublishSymbols@v2

### Task version

2.214.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Question

Hello,

I have a release pipeline that generates packages and publishes them to some nuget feeds. I'm adding the publish symbols task to save the PDBs in the artifacts and I'm facing the following issue:

```
2023-03-07T19:17:13.2872748Z ##[error]Unable to process command '##vso[artifact.associate artifacttype=SymbolRequest;artifactname=SOME_LINK]#LINK_TO_AZUREDEVOPS' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2023-03-07T19:17:13.2970023Z ##[error]Value cannot be null. (Parameter 'buildId')
```

I also tried to supply some variables such as:
Build.BuildId = $(Release.ReleaseId)
buildId = $(Release.ReleaseId)

How can I publish using a release pipeline?

Thank you!

**Comment by PavloAndriiesh** [comment]
Tagging @carl-tanner @fadnavistanmay @b-barthel @kunalkaroth as the owners from CODEOWNERS file

**Comment by carl-tanner** [comment]
The publish symbols task is only supported in builds, not release pipelines.
