### ISSUE TITLE
[BUG]: DotNetCoreCLI@2 publishWebProjects = true no longer picking up projects that use Microsoft.NET.Sdk.Web

### ISSUE THREAD

**Issue by ciaranmcggit** [microsoft/azure-pipelines-tasks#17871]
### Task name

DotNetCoreCLI@2 - publish

### Task version

2.217.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

Agent Name - Azure Pipelines 3.217.1

### Operation system

Windows Server 2022

### Task log

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Additional info

```shell
We run the task below on our solution which has two web projects (one with a web.config, another which uses Microsoft.NET.Sdk.Web).  This was picking up and building both projects fine until roughly 14th Feb 2023, when it would no longer build the project referencing the Web SDK.  In order for it to be picked up again, I had to add a web.config file.

According to the documentation, "Web projects are identified by the presence of either a web.config file or a wwwroot folder in the directory. In the absence of a web.config file or a wwwroot folder, projects that use a web SDK, like Microsoft.NET.Sdk.Web, are selected."  (https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines)

Has anything changed around this time that would have caused projects using the web sdk exclusively to no longer be picked up?



-------------------------------------
      - task: DotNetCoreCLI@2
        displayName: "dotnet publish"
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration Release /p:Version="$(version)" /p:AssemblyVersion="$(version)" /p:InformationalVersion="$(version) @branch:$(Build.SourceBranch) @commit:$(Build.SourceVersion)"'
```

**Comment by Jabronironi** [comment]
@ciaranmcggit  I have this same issue.  I know this was closed, but it does appear to still be an issue.  Additionally, the projects: parameter is ignored if it is placed before the publishWebProjects: false argument.  My current work around is to make sure publishWebProjects: is first, and then add a projects: <glob> argument. I could not get the Microsoft.NET.Sdk.Web auto pickup to work.
