### ISSUE TITLE
[BUG]: Cannot read property 'updateStartupCommandAndRuntimeStack' of undefined

### ISSUE THREAD

**Issue by noahgregory-avanade** [microsoft/azure-pipelines-tasks#17988]
### Task name

Azure Web App

### Task version

1.215.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Task log

```shell
Successfully deployed web package to App Service.
##[error]TypeError: Cannot read property 'updateStartupCommandAndRuntimeStack' of undefined
```

### Relevant log output

```shell
##[error]TypeError: Cannot read property 'updateStartupCommandAndRuntimeStack' of undefined
```

### Aditional info

Searching through the repository for uses of `updateStartupCommandAndRuntimeStack` that are part of the `AzureWebApp@v1` task, I have found only one use:

```  
        await this.appServiceUtility.updateStartupCommandAndRuntimeStack(this.taskParams.RuntimeStack, this.taskParams.StartupCommand);
```

(source: [https://github.com/microsoft/azure-pipelines-tasks/blob/30c99c8/Tasks/AzureWebAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts#L59](https://github.com/microsoft/azure-pipelines-tasks/blob/30c99c8/Tasks/AzureWebAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts#L59))

This line is used in a class called `BuiltInLinuxWebAppDeploymentProvider`, which extends `AzureRmWebAppDeploymentProvider`.

Looking at the `AzureRmWebAppDeploymentProvider` class, it appears `appServiceUtility` has no initial value:

```  
    protected appServiceUtility: AzureAppServiceUtility;
```

(source: [https://github.com/microsoft/azure-pipelines-tasks/blob/30c99c8/Tasks/AzureWebAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts#L23](https://github.com/microsoft/azure-pipelines-tasks/blob/30c99c8/Tasks/AzureWebAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts#L23))

It seems to only be defined as part of the `PreDeploymentStep` method:

```  
    public async PreDeploymentStep() {
        if (this.taskParams.azureEndpoint.scheme && this.taskParams.azureEndpoint.scheme.toLowerCase() === AzureRmEndpointAuthenticationScheme.PublishProfile) {
            let publishProfileEndpoint: AzureEndpoint = this.taskParams.azureEndpoint;
            this.publishProfileScmCredentials = await publishProfileUtility.getSCMCredentialsFromPublishProfile(publishProfileEndpoint.PublishProfile);
            this.kuduService = new Kudu(this.publishProfileScmCredentials.scmUri, this.publishProfileScmCredentials.username, this.publishProfileScmCredentials.password);
            let resourceId = publishProfileEndpoint.resourceId;
            let resourceIdSplit = resourceId.split("/");
            this.slotName = resourceIdSplit.length === 11 ? resourceIdSplit[10] : "production";
        } else {
            this.appService = new AzureAppService(this.taskParams.azureEndpoint, this.taskParams.ResourceGroupName, this.taskParams.WebAppName, 
                this.taskParams.SlotName, this.taskParams.WebAppKind);
            this.appServiceUtility = new AzureAppServiceUtility(this.appService);
            this.kuduService = await this.appServiceUtility.getKuduService();
            this.slotName = this.appService.getSlot();
        }
        this.kuduServiceUtility = new KuduServiceUtility(this.kuduService);
    }
```

(source: [https://github.com/microsoft/azure-pipelines-tasks/blob/30c99c8/Tasks/AzureWebAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts#L36-L52](https://github.com/microsoft/azure-pipelines-tasks/blob/30c99c8/Tasks/AzureWebAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts#L36-L52))

If we remove all the noise, it appears that `appServiceUtility` is only given a value when the authentication method is _not_ “Publish profile”:

```  
    public async PreDeploymentStep() {
        if (this.taskParams.azureEndpoint.scheme && this.taskParams.azureEndpoint.scheme.toLowerCase() === AzureRmEndpointAuthenticationScheme.PublishProfile) {
            ...
        } else {
            ...
            this.appServiceUtility = new AzureAppServiceUtility(this.appService);
            ...
        }
        ...
    }
```

*(please note that despite the apparent source of the bug occurring in a function called `PreDeploymentStep`, the runtime error only occurs **after** successful deployment.)*

**Comment by tompi** [comment]
👍  from me. Here are two related SO posts(one from me), neither with any resolution:

https://stackoverflow.com/questions/70658108/updatestartupcommandandruntimestack-error-azureweapp-deploy
https://stackoverflow.com/questions/69896255/azure-web-app-deploy-fails-with-cannot-read-property-updatestartupcommandandrun

I spent some hours trying to fix this today, but had to give up again :(
We have been living with this error message for 1.5 years now...
