### ISSUE TITLE
[BUG]:Mandatory parameters in a yaml based build/release task extension is not being validated during parsing, and gets detected only during runtime unlike its behavior in the classic pipeline. 

### ISSUE THREAD

**Issue by a-aarchana** [microsoft/azure-pipelines-tasks#18034]
### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

All

### Task log

```shell
-
```

### Relevant log output

```shell
-
```

### Aditional info

```shell
Mandatory parameters in a yaml based build/release task extension is not being validated during parsing and gets detected only during runtime unlike the classic pipeline. We have published a task extension in msazure org, which a lot of teams would be leveraging for pre-prod (shift-left) validation of their services. (https://marketplace.visualstudio.com/manage/publishers/azconductor/extensions/azconductor-wf-trigger-task/hub)
 
This gives a varying user experience for the users of our task extension. Our component preprod-validation task extension is plugged in at the far end of a build pipeline of several services, few of which will have their pipelines in classic and other in yaml based. The mandatory params validation kicks off only after the entire pipeline run and then fails the task, and we lose that build event which has repercussions for us. 

      So similar to classic pipeline, could the save be enabled only if the parsing and validation succeeds? Currently the Validation button just checks for cursory syntax errors, highlights if the value of a dropdown is different and does not leverage the task.json like the classic pipeline does.
```

**Comment by ivanduplenskikh** [comment]
Hi @a-aarchana could you please share more details about your issue?
Do you mention the need to validate parameters directly in the YAML editor?

**Comment by a-aarchana** [comment]
Behavior of parameter validation in classic/yaml based:

Classic: In the task.json file if a field is marked as mandatory, one cannot save the pipeline or create a release unless the field value is entered.

Yaml Based: With/without the use of assistant, yaml editor allows the creation/edit of pipeline and hence a run of it, even if the mandatory fields are missing or its value is not entered, it prompts in few cases but not all. The VALIDATE button does not validate the yaml, like the classic pipeline. So, the absence of a mandatory field can be caught only during the run and not instantly, during the create/edit of pipeline. 

Hope this explains the issue. I tried several options but couldn't find any solution to this.

**Comment by a-aarchana** [comment]
![yaml_validation](https://user-images.githubusercontent.com/129254209/228479142-f09e9de0-0305-46f3-9d92-2a42a92d3a85.png)

As an eg: build id is a mandatory field, and its value is empty in the yaml editor, nevertheless validation passes and absence of it is caught during runtime

**Comment by ivanduplenskikh** [comment]
@a-aarchana thanks for the detailed description.
This issue seems to be related to AzureDevOps. I suggest opening a ticket on https://developercommunity.visualstudio.com/AzureDevOps as this repo is mostly for pipeline tasks

**Comment by ivanduplenskikh** [comment]
I am closing this for now.
If you have any additional questions feel free to reopen it.
