### ISSUE TITLE
[enhancement]: Ignore Pipeline Caching task if File path is not found in `key` parameter

### ISSUE THREAD

**Issue by joshwright10** [microsoft/azure-pipelines-tasks#18138]
### Task name

Cache@2

### Describe your feature request here

When the file path, such as `**/packages.lock.json` is not found when the `Cache@2` is ran, the task fails with the following error, and causes the pipeline to end.

> ##[error]One or several exceptions have been occurred.
> ##[error]System.IO.FileNotFoundException: No matching files found for pattern: **/packages.lock.json,!**/bin/**,!**/obj/**

Setting `continueOnError: true` allows the pipeline to continue, but shows the error and also shows the stage with a warning.
It would be nice to include this task as optional in a template for projects that have included a `packages.lock.json` file or equivalent.

I imagine providing an extra parameter such as `skipOnMissingFiles` which will simply not show any warnings or errors if the `packages.lock.json` file is missing.

**Comment by virus2016** [comment]
We should reopen this. Doesn't work with monorepos
