### ISSUE TITLE
[enhancement]: Fail/Pass VSTest Task based % threshold test cases failure value.

### ISSUE THREAD

**Issue by MurtajaKadiyani** [microsoft/azure-pipelines-tasks#18163]
### Task name

VSTest Task

### Describe your feature request here

I want feature that VSTEST task should fail if % threshold test cases are failed. For example if VSTEST identified 100 test cases and if we mention % threshold test cases is 15 then if out of 100 test cases 15 or less test cases are failed then task should mark as succeeded but if out of 100 test cases 16 or more test cases are failed in execution, then VSTest task should fail in pipeline

**Comment by m-soltani** [comment]
we also need this feature for our project. Any plans to implement this enhancement?

**Comment by m-soltani** [comment]
I had to implement my own custom solution for this
