### ISSUE TITLE
[BUG]: AzureFunction App Deployment failing

### ISSUE THREAD

**Issue by ayush2708** [microsoft/azure-pipelines-tasks#18195]
### Task name

AzureFunctionApp@1; AzureFunctionApp@2

### Task version

2.221.103

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

RHEL7

### Task log

```shell
Resource file has already set to: /opt/buildagent/_work/_tasks/AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573/2.221.103/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
```

### Relevant log output

```shell
Resource file has already set to: /opt/buildagent/_work/_tasks/AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573/2.221.103/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
```

### Aditional info

```shell
- Function App Deployment failing in YAML pipeline using AzureFunctionApp@1 or AzureFunctionApp@2 task
- Error is same as given in relevant task logs above
- Pipeline was working earlier
- Updated the Agent to latest 3.218.0 but error not resolved.

Sorry it's my first time. Please let me know if any additional details required
```

**Comment by FinVamp1** [comment]
Hello, thanks for reporting this. This task has been updated to 221.104 and this should resolve your issue.

**Comment by ayush2708** [comment]
@FinVamp1 Thanks. It is working now. Task has been updated to **221.105**
