### ISSUE TITLE
[enhancement]: Maven Task README should mentions SpotBugs, not FindBugs

### ISSUE THREAD

**Issue by in-fke** [microsoft/azure-pipelines-tasks#18204]
### Task name

Maven

### Describe your feature request here

Maven Task README should mentions SpotBugs, not FindBugs

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV4/README.md

**Comment by in-fke** [comment]
Some trigger failed when creating this issue:
https://github.com/microsoft/azure-pipelines-tasks/actions/runs/4818044079

**Comment by max-zaytsev** [comment]
@in-fke Thanks for reporting, we'll take a look at it

**Comment by in-fke** [comment]
Yes, Bot, this is still relevant.
