### ISSUE TITLE
Auto signing for XCode

### ISSUE THREAD

**Issue by FadwaZaghloul** [microsoft/azure-pipelines-tasks#18226]
Hello @alombard 

I have followed your advices, but it still displays 2 errors:
```
error: No profiles for 'com.a.b.c' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.a.b.c'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'c' from project 'A')

error: No profiles for 'com.a.b.c.intentsExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.a.b.c.intentsExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'intentsExtension' from project 'A')
```
All of 2 imported profiles are valid, because if Im doing manual signing using 1 of them - it displays single error, that another profile is missing.

Also I noticed that command performed by XCode Task is the following:
```
/usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace /Users/runner/work/1/s/A.xcworkspace -scheme B archive | /usr/local/lib/ruby/gems/2.7.0/bin/xcpretty -r junit --no-color
```

There is no "-exportOptionsPlist" param appended to "xcodebuild". So it was ignored by XCode task.
I have tried to put that param manually in command line, but "xcodebuild" says that using "scheme" param is not allowed to be used together with "exportOptionsPlist".

Did you face similar issue in your case?

Thank you,
Alex.

CC @kanakaraju043

_Originally posted by @svarnik in https://github.com/microsoft/azure-pipelines-tasks/issues/8811#issuecomment-747433858_

**Comment by jdwirrenga** [comment]
[Also posted here](https://github.com/microsoft/azure-pipelines-tasks/issues/17478), hopefully someone will look at these at some point.

**Comment by ChinDer** [comment]
Still broken
