### ISSUE TITLE
[BUG]: Required attribute notifyUsers of ManualValidation@0 not required

### ISSUE THREAD

**Issue by RafaelReia** [microsoft/azure-pipelines-tasks#18234]
### Task name

ManualValidation@0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

MacOS

### Task log

```shell
NA
```

### Relevant log output

```shell
NA
```

### Aditional info

```shell
The task: ManualValidation@0 has a required attribute `notifyUsers` that appears to not be required
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ManualValidationV0/task.json#L28

I have a couple pipelines that work as expected without the `notifyUsers` being set
```

**Comment by boschcrank** [comment]
Same here and I propose to make this parameter optional. It is not necessary for the validation step to work and there are some cases in which we actually do not implement any notification.

**Comment by Frankkkkk** [comment]
Bump
