### ISSUE TITLE
[BUG]: FTP Upload task can't upload via FTPS

### ISSUE THREAD

**Issue by a688** [microsoft/azure-pipelines-tasks#18244]
### Task name

FtpUpload

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Task log

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Aditional info

```shell
Time out to control port when attempting to connect 900 to use implicit TP over TSL. This works perfectly fine with FileZilla.
```

**Comment by a688** [comment]
This is pretty much a dupe of https://github.com/microsoft/azure-pipelines-tasks/issues/11944#issuecomment-739810253 which was closed as stale.

**Comment by ismayilov-ismayil** [comment]
@a688  thanks for reporting. Could you please share agent logs to take a look? You can retrieve them by following [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs) . You would also need to set up 'Agent.Diagnostic' pipeline variable as 'true' before pipeline run.

**Comment by a688** [comment]
Can I email you the log so I don't accidentally share any ip addresses or accounts

**Comment by jeffska** [comment]
I've run into the same issue. I believe this comment from the prior issue has the correct analysis. The Ftp Upload task doesn't properly support FTP servers using implicit TLS.

https://github.com/microsoft/azure-pipelines-tasks/issues/11944#issuecomment-739810253
