### ISSUE TITLE
[Question]: Azure App service Deployment: 401 Unauthorized

### ISSUE THREAD

**Issue by thanhvumsft** [microsoft/azure-pipelines-tasks#18265]
### Task name

Deploying Azure app service failed 401 

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Question

```shell
Hello everyone, 

I got 401 Unauthorized error when deploying Azure app service via GitHub Actions, it been working for months before and we don't change anything in CI/CD config. I know someone got same issue like me but don't know which team I can reach out for help. Thank you.

Note: Our repo is in Microsoft EMU
```

**Comment by thanhvumsft** [comment]
Screenshot for the 401 error: 

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/93938997/9202cf33-0e89-4f09-8972-509c99abcd0f)

**Comment by FinVamp1** [comment]
Hello, will contact you about this internally.

**Comment by FinVamp1** [comment]
@thanhvumsft  can you reach out to me internally finbarr at microsoft.com

**Comment by thanhvumsft** [comment]
> @thanhvumsft  can you reach out to me internally finbarr at microsoft.com

Thank you for your reply, we just figure out and make it work, you can close this ticket.
