### ISSUE TITLE
[Question]: Will logic app v2 deployment work with AzureFunctionApp@v2?

### ISSUE THREAD

**Issue by JDinisHiscox** [microsoft/azure-pipelines-tasks#18277]
### Task name

AzureFunctionApp

### Task version

2.221.105

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Question

If i set my appType to functionApp and if my arm template looks like this (kind = functionapp, workflowapp):

```json
    "resources": [
        {
            "apiVersion": "2018-11-01",
            "name": "[variables('logicAppName')]",
            "type": "Microsoft.Web/sites",
            "kind": "functionapp,workflowapp",
            "location": "[resourceGroup().location]",
```

How well will these settings coexist?

I've noticed functionapp, workflowapp is not part of the acceptable appTypes in the file below ence the question:
https://github.com/microsoft/azure-pipelines-tasks/blob/85f284809730ee69ad35c14013874947bd60f1c5/Tasks/AzureFunctionAppV2/taskparameters.ts#L11

And this looks even more restrictive:
https://github.com/microsoft/azure-pipelines-tasks/blob/85f284809730ee69ad35c14013874947bd60f1c5/Tasks/AzureFunctionAppV2/task.json#L48

**Comment by FinVamp1** [comment]
Hi, thanks for the ask. Let me look into this and come back to you.

**Comment by FinVamp1** [comment]
Hello, a Logic App has a different Kind Property in Azure Resource Manager so you can't use the Function Apps Task to deploy a Logic App. Please use [Azure Feedback](https:///feedback.azure.com) if this is something you would like to be able to do in future.

**Comment by JDinisHiscox** [comment]
As suggested i've created the request in feedback but would like to put here the link to the request and ask that someone looks at my request since im not completely conviced with the closing answer.

https://feedback.azure.com/d365community/idea/bb90f881-d5ff-ed11-a81c-000d3adb7ffd
