### ISSUE TITLE
[BUG]: Documentation needs an update around nuget push of packages to external server

### ISSUE THREAD

**Issue by Larswa** [microsoft/azure-pipelines-tasks#18296]
### Task name

NuGetCommand@2

### Task version

2.x

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server MS hosted image

### Task log

```shell
Error:
Trying to authenticate with auth token.
VstsNuGetPush.ServiceIndexNotFoundException: Service index was not found at 'https://pkgs.dev.azure.com/[redacted]/_packaging/nuget/v3/index.json'. ---> Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Not Found
GET (https://pkgs.dev.azure.com/[redacted]/_packaging/nuget/v3/index.json) failed. ActivityId: 30cbdfe6-b829-4bdb-b3bf-c27aa136ee91, HTTP Status: NotFound, AFD Ref: Ref A: 49C6C8A6EE6B4AFA9DAF2C0CF8079066 Ref B: DB3EDGE2106 Ref C: 2023-05-16T14:23:07Z
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
Authentication and request took 00:00:04.9768184
```

### Relevant log output

```shell
Error:
Trying to authenticate with auth token.
VstsNuGetPush.ServiceIndexNotFoundException: Service index was not found at 'https://pkgs.dev.azure.com/[redacted]/_packaging/nuget/v3/index.json'. ---> Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Not Found
GET (https://pkgs.dev.azure.com/[redacted]/_packaging/nuget/v3/index.json) failed. ActivityId: 30cbdfe6-b829-4bdb-b3bf-c27aa136ee91, HTTP Status: NotFound, AFD Ref: Ref A: 49C6C8A6EE6B4AFA9DAF2C0CF8079066 Ref B: DB3EDGE2106 Ref C: 2023-05-16T14:23:07Z
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
Authentication and request took 00:00:04.9768184
```

### Aditional info

Documentation is wrong and needs to be updated to reflect a missing parameter when pushing to an external nuget source.

So I am pushing a nuget package to an Azure Artefact repository in another organization.
I am following this documentation about doing that. [https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#publish-nuget-packages](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#publish-nuget-packages)

It suggests doing this: 

```yaml
- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: <NAME_OF_YOUR_SERVICE_CONNECTION>
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    versioningScheme: byEnvVar
    versionEnvVar: <VERSION_ENVIRONMENT_VARIABLE>
```

However ... this doesnt seem to work. It needs the serviceconnection in the the nuget push as well.  

I got errors like 

Error:
Trying to authenticate with auth token.
VstsNuGetPush.ServiceIndexNotFoundException: Service index was not found at 'https://pkgs.dev.azure.com/[redacted]/_packaging/nuget/v3/index.json'. ---> Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Not Found
GET (https://pkgs.dev.azure.com/[redacted]/_packaging/nuget/v3/index.json) failed. ActivityId: 30cbdfe6-b829-4bdb-b3bf-c27aa136ee91, HTTP Status: NotFound, AFD Ref: Ref A: 49C6C8A6EE6B4AFA9DAF2C0CF8079066 Ref B: DB3EDGE2106 Ref C: 2023-05-16T14:23:07Z
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
Authentication and request took 00:00:04.9768184

And I eventually had to put the service connection in the nuget push as well, like this, to get it to work.  As **"publishFeedCredentials"**

```yaml
- task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: MyServiceConnection

  - task: NuGetCommand@2
    displayName: Push the nuget package
    inputs:
      command: "push"
      nuGetFeedType: external
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
      publishFeedCredentials: MyServiceConnection
      allowPackageConflicts: true
```

**Comment by jmyersmsft** [comment]
At this time, we're generally recommending against using the NuGetCommand task in favor of a script task that runs nuget.exe or dotnet directly. 

I've created a PR to remove the incorrect section from the docs: microsoft/azure-devops-docs#13342

**Comment by Larswa** [comment]
Hi @jmyersmsft   Thanks for following up.  I get what you mean.  I am not a big fan of those Azure Devops tasks that try to do everything and ends up ignoring the single responsibility principle and being super confusing.  Where can I see those recommendations? Or are they peppered about in the github issues discussions?

**Comment by jmyersmsft** [comment]
Unfortunately, they're just sprinkled around some of the task docs and various GH issues at this point. The formal deprecation process always seems to be just below the cut line on the backlog.
