### ISSUE TITLE
Publish task does not preserve links

### ISSUE THREAD

**Issue by j0tt** [Microsoft/azure-pipelines-tasks#1831]
This is a bit obscure, so bear with me:

When using the publish task to copy an .app with a framework reference from a mac agent, symbolic links are lost (I believe). This manifests when downloading the .app artifact from VSTS and attempting to sign it with:

`codesign --force --sign [THUMBPRINT] --deep myapp.app`

This returns `bundle format is ambiguous (could be app or framework) in subcomponent: /path/to/dependent.framework`

We have worked around this issue by using our own copy task that calls a .sh which mounts a share, and then copies the artifacts with:
`cp -R folder/to/copy/to location/of/myapp.app`

According to http://www.delorie.com/gnu/docs/fileutils/fileutils_38.html -R verses -r:
"Copy directories recursively, preserving non-directories"

Note: when we used `copy -r` we had the same issue as the using the publish task.

Using the capital `R` argument allows me to sign the .app using codesign.

I believe using the `-a` argument would work as well, but I have not verified.

**Comment by david-higgins** [comment]
👍 Getting this too.  Using hosted agents, passing a .app between phases, not sure how will workaround right now but probabbly zip... 🤔

**Comment by alexmullans** [comment]
@mitchdenny I think this is an ask on Pipeline Artifacts - can you comment?

**Comment by mitchdenny** [comment]
Yes - we've been looking at a sensible and secure way that we can preserve links with Pipeline Artifacts, and the scenario was moving .app and .framework directories around. One of the things we've discovered is that if you copy the files to an SMB share there is a file created which when copied back to a Mac machine gets translated into a link.

We haven't got a solution yet, but we want to make sure that we don't accidentally introduce a security problem by persisting symbolic link information.

**Comment by alexmullans** [comment]
@mitchdenny I'm doing a clean-up triage of our GitHub issues. Is this something you think we can fix in the new Pipeline Artifacts tasks, or should we close/WF it?

**Comment by mitchdenny** [comment]
It is something we want to solve but we don't have a solution yet. I think we can mark it as won't fix and when we eventually come up with a way of making it work then we will.

**Comment by alexmullans** [comment]
Sounds good. Closing as WF.
