### ISSUE TITLE
Resource file has already set to: /home/cloudsa/myagent/_work/_tasks/AzureAppServiceSettings_/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json 

### ISSUE THREAD

**Issue by ammuk679** [microsoft/azure-pipelines-tasks#18355]
### Task name

AzureAppServiceSettings@1

### Task version

v1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Linux

### Task log

```shell
Till few days before I am able to execute AzureAppServiceSettings@1 task without any warnings. But now I am getting ##[warning]Resource file has already set to: /home/cloudsa/myagent/_work/_tasks/AzureAppServiceSettings_/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json . I got confused how it worked before and suddenly thrown issues
```

### Relevant log output

```shell
There should not be any warning when AzureAppServiceSettings@1 task execution in build pipeline.
```

**Comment by seanksullivan** [comment]
Reproducible on Windows hosted agents.

##[warning]Resource file has already set to: C:\agents\Azure-App-Service-Agent1\_work\_tasks\AzureAppServiceSettings_3eeea460-bffa-11e9-9cb5-2a2ae2dbcce4\1.223.0\node_modules\azure-pipelines-tasks-azure-arm-rest-v2\module.json
