### ISSUE TITLE
[Question]: post-job SavePipelineCache is skipped

### ISSUE THREAD

**Issue by croudet** [microsoft/azure-pipelines-tasks#18375]
### Task name

CacheV2 - SavePipelineCache 

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

linux

### Question

```shell
Post-job to save cache is skipped with the following message:
Target container - linux_build_container has been stopped, task post-execution will be skipped

Is there a way to call the post-job before the container is stopped?
```

**Comment by Hardhik** [comment]
Is this issue fixed? I see this still happening. Was there any workaround suggested?

**Comment by Phantsure** [comment]
Same here. This doesn't seem resolved.
![Image](https://github.com/user-attachments/assets/095079e3-e22e-418a-988a-f780d0fc7e42)
