### ISSUE TITLE
[BUG]: Error occured while generating HTML report. Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by wilfriedb** [microsoft/azure-pipelines-tasks#18474]
### Task name

PublishCodeCoverageResults@2

### Task version

2.221.0

### Environment type (Please select at least one environment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022

### Task log

```shell
2023-06-09T08:51:19: Finished parsing 'C:\a\_temp\fe4b44d9-9647-4f0f-bf60-9cc74470014f\coverage.cobertura.xml' 73/73
2023-06-09T08:51:19: Starting merging result 73
2023-06-09T08:51:19: Parsing of 73 files completed
2023-06-09T08:51:19: Finished merging result 73
##[error]Error occured while generating HTML report. Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

Publishing file coverage data.
Publishing code coverage HTML report.
Uploading 0 files.
File upload succeed.
```

### Relevant log output

```shell
##[error]Error occured while generating HTML report. Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

### Aditional info

This error is also mentioned in this comment: https://github.com/microsoft/azure-pipelines-tasks/issues/17756#issuecomment-1562394558

The build and tests succeeded, the publish test coverage tool already processed all 73 projects, and then suddenly stops processing with the above mentioned error. In our Solution there is no reference or need for System.Collections.Immutable, Version=5.0.0.0 whatsoever. We do use version 7.0, but reports from projects using System.Collections.Immutable have been successfully processed in many of the 73 reports.

Also: adding a 'Use .NET 5.0 SDK' Task  does not solve the issue.

**Comment by v-mohithgc** [comment]
Mostly this issue will be resolved in version 223, in this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/18281

**Comment by vinayakmsft** [comment]
For agent specific bug the pr was merged https://github.com/microsoft/azure-pipelines-tasks/pull/18281 to fix the issue . Changes will appear post deployments. Hence closing the issue.

**Comment by dmcweeney** [comment]
@vinayakmsft any idea how long it will take 2.223 to rollout to the Microsoft hosted agents?

Ths problem surfaced yesterday for me after encountering the usedotnet 2.x problem. Once I change this from using version 2.1.x to using version 7.0.x this problem surfaced.
