### ISSUE TITLE
[enhancement]: Flaky test support by PublishTestResults

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/azure-pipelines-tasks#18471]
### Task name

Flaky test support by PublishTestResults

### Describe your feature request here

Azure Devops support flaky tests:
https://learn.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#view-summarized-test-results

And VSTest@2 does support this great feature.

However, even I publish the same result generated by VsTest through PublishTestResults, the result is not displayed as flaky, but some other tests.

This will make it hard to support the test framework VsTest does not support, like Playwright or other languages.
```[tasklist]
### Tasks
```

**Comment by turbobobbytraykov** [comment]
I just encountered the same situation. @ShuiRuTian , do you think there's any hope for implementing this feature?

**Comment by ShuiRuTian** [comment]
@turbobobbytraykov not much hope... 

I think this feature is implemented in the correspond task(in the backend, which is not open sourced, please correct me if I am wrong).

I tried to contact the backend feature owner, but failed, although the task owners are friendly.
