### ISSUE TITLE
[enhancement]: ManualValidation Task Instruction should support variables

### ISSUE THREAD

**Issue by matzter** [microsoft/azure-pipelines-tasks#18502]
### Task name

ManualValidation

### Describe your feature request here

It would be super cool if we could add variables to the ManualValidation field for instructions.
This would allow us to forward results etc. from previous tasks to the validation information.

```- task: ManualValidation@0
        inputs:
          notifyUsers: '' # string. Required. Notify users. 
          instructions: 'please validate the output of the previous step: $(deploymentPlan)'
          onTimeout: 'reject' # 'reject' | 'resume'. On timeout. Default: reject.
```

**Comment by Laurianti** [comment]
Any update here?
