### ISSUE TITLE
task.json schema

### ISSUE THREAD

**Issue by artmasa** [Microsoft/azure-pipelines-tasks#1854]
Where can I find task.json file schema. It would be nice to get intellisense while creating task definitions

**Comment by zeDoctor** [comment]
Or really, any documentation.  I can't seem to find any information on the valid values in, for example, the "visibleRule" field.  The task.json specification is sorely needed.

**Comment by brettjacobson** [comment]
Agreed.  There is this outstanding pull request that has been on ice for months.
https://github.com/Microsoft/vsts-tasks/pull/1066/commits/22de746c885f20e9c428a3d3d62791acc19b7900

**Comment by AArnott** [comment]
The PR @brettjacobson mentions is #1066

**Comment by bryanmacfarlane** [comment]
closing since we're tracking in vsts-task-lib

**Comment by yaananth** [comment]
FYI for reference, there's a doc that has a basic scheme https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/build-task-schema

**Comment by kraftc** [comment]
Where is the task.json schema reference now?

**Comment by AArnott** [comment]
The `tasks.schema.json` file ended up moving [here](https://github.com/Microsoft/vsts-task-lib/blob/master/tasks.schema.json).

**Comment by damccorm** [comment]
Closing since this [exists in the task-lib](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json)
