### ISSUE TITLE
[enhancement]: InstallSSHKey@0 should be able to use keyvault values

### ISSUE THREAD

**Issue by sinePaul** [microsoft/azure-pipelines-tasks#18552]
### Task name

InstallSSHKey@0

### Describe your feature request here

InstallSSHKey@0 runs as a prejob, before any other job. 
When using a key vault as a variable group in the library, their value is read after the prejobs. 
The workaround is then to create the variables manually on each pipeline or to use the task AzureKeyVault@2 to get the secrets in the pipeline. 
In both cases there are workarounds and require more configuration. 
This issue is [first described here](https://github.com/microsoft/azure-pipelines-tasks/issues/15172#issuecomment-1148672696) 

Wouldn't that make sense to let the possibility to disable the task to run as a prejob?

**Comment by max-zaytsev** [comment]
@sinePaul  thanks for reporting this! We're currently working on higher-priority issues, but we'll get back to this soon.

**Comment by sinePaul** [comment]
This is still an issue atm, is there a fix planned on this?
