### ISSUE TITLE
[BUG]: InstallAppleCertificateV2 fails if it tries to use OpenSSL@3 from Homebrew

### ISSUE THREAD

**Issue by pthexton** [microsoft/azure-pipelines-tasks#18560]
### Task name

InstallAppleCertificateV2

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

macOS 12

### Task log

```shell
2023-06-27T13:12:07.8404820Z ##[section]Starting: InstallAppleCertificate
2023-06-27T13:12:07.8724910Z ==============================================================================
2023-06-27T13:12:07.8736780Z Task         : Install Apple certificate
2023-06-27T13:12:07.8739300Z Description  : Install an Apple certificate required to build on a macOS agent machine
2023-06-27T13:12:07.8740020Z Version      : 2.220.0
2023-06-27T13:12:07.8741550Z Author       : Microsoft Corporation
2023-06-27T13:12:07.8744160Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-apple-certificate
2023-06-27T13:12:07.8745090Z ==============================================================================
2023-06-27T13:12:10.2759800Z [command]/usr/local/bin/openssl pkcs12 -in /Users/admin/VSTS/_work/_temp/Certificates.p12 -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -sha1 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
2023-06-27T13:12:10.6693620Z Error outputting keys and certificates
2023-06-27T13:12:10.6697500Z 0056960402000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
2023-06-27T13:12:10.6793430Z Could not read certificate from <stdin>
2023-06-27T13:12:10.6906760Z ##[error]Error: /usr/local/bin/openssl failed with return code: 1
2023-06-27T13:12:10.7356810Z ##[section]Finishing: InstallAppleCertificate
```

### Relevant log output

```shell
2023-06-27T13:12:10.6697500Z 0056960402000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

### Aditional info

```shell
When the self-hosted build agent has Openssl@3 installed on it (in our case we believe this was installed as a dependency for azure-cli via homebrew, ironically) the InstallAppleCertificate Task attempts to open openssl from the path at /usr/local/bin instead of the system openssl binary at /usr/bin

At the moment it's unclear whether this is a bug we should be raising against OpenSSL, or is a case that Openssl@3 requires different CLI args to work with the .p12 file being given to it.

It would be nice if we could explicitly set the path to find the openssl binary to use in this task instead of relying on determining openssl binary location from the $PATH environment.
```

**Comment by max-zaytsev** [comment]
@pthexton thanks for reporting this! We're currently working on higher-priority issues, but we'll get back to this soon.

**Comment by bondarenkod** [comment]
Any workaround?

**Comment by fdelfrari** [comment]
As a workaround on the machine I've launched:
`brew unlink openssl`
This way openssl3 is still installed and available for other formulas that will look for libssl but the executable will point to the os bundled version.

**Comment by ynnob** [comment]
> As a workaround on the machine I've launched: `brew unlink openssl` This way openssl3 is still installed and available for other formulas that will look for libssl but the executable will point to the os bundled version.

Thank you so much! I was so confused because all of the sudden the pipeline stopped working. All i did was an update of fastlane which must have triggered a brew update which must have installed or relinked openssl3.... What a mess

**Comment by Mittchel** [comment]
> I'm facing this issue on Microsoft Hosted too.

Same here, can't seem to build at all at the moment.

**Comment by Komdosh** [comment]
Same here on hosted agent. Quick fix, if possible downgrade to macos-12

**Comment by blackwasp76** [comment]
macOS-12 also doesn't support xcode 14.3.1, this is happening now for me also, was working fine yesterday evening on 13.4, but not I see that the runner image was updated a few hours ago to 13.5 and now this issue is happening

**Comment by blackwasp76** [comment]
> Same here, Microsoft Hosted macOS-13, 20230731 image, maybe this: https://github.com/actions/runner-images/pull/8013/files#diff-49d5008075920b3466eff9e2bb3f4a933cca7733524c0153fd761cf9b6fc4fd4R56

I also believe this is the culprit

**Comment by abasore** [comment]
This issue is blocking all our pipelines which have to run on macos-13. @DmitriiBobreshev is there any update on fix?

**Comment by bartsoeters** [comment]
This issue is also blocking our pipelines as we use the latest macos-13 image. Please resolve it as soon as possible 🙏🚀

**Comment by pedrolopessh** [comment]
This is also blocking us! Can you fix this ASAP?

**Comment by codynedved** [comment]
This also has caused all our pipelines to fail. This is critical that this get addressed.

**Comment by alanrmatthews** [comment]
This is also blocking our pipelines, please address ASAP.

**Comment by eric-castoldi-careplus** [comment]
Also blocking us here :frowning_face:

**Comment by jci-cfoxr** [comment]
This is also occurring for us on MS hosted DevOps agents.   It worked yesterday on macos13 agent and is failing now today.   Please expedite as we are unable to fall back to macos12 due to the other issue introduced into that (Issue #7945)

**Comment by codynedved** [comment]
It seems like the openssl command needs to be updated into use a legacy flag.   This is def a hosted issue also now.   See additional thread here https://github.com/actions/runner-images/issues/8017

**Comment by rrr-kaio-labre** [comment]
Also blocking us here

**Comment by bart-kace** [comment]
Seems resolved with the new macos-13 image that was released 9 hours ago. ☺️

**Comment by pedrolopessh** [comment]
This error seems to be fixed but now, if I run my builds with tests, it takes so much time that it actually times out 🤔 
Anyone experiencing the same?

**Comment by remyjette** [comment]
> This error seems to be fixed but now, if I run my builds with tests, it takes so much time that it actually times out 🤔 
> Anyone experiencing the same? 

I am also seeing test jobs that normally take about 5 minutes timing out at 30 with the new image.

**Comment by DmitriiBobreshev** [comment]
Hi @pthexton, We added new input [opensslPkcsArgs ](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/InstallAppleCertificateV2/task.json#L119), you could use that to pass --legacy option to work with old certificates when openssl3 is installed. The task might look like this: 
```
- task: InstallAppleCertificate@2
   inputs:
     opensslPkcsArgs: '-legacy' #extract cert properties using legacy mode
     ...rest inputs
 ```

**Comment by bondarenkod** [comment]
```
steps:
  - task: InstallAppleCertificate@2
    name: AppleCertificate
    displayName: Install an Apple certificate
    inputs:
      certSecureFile: "$(ios_apple_certificate)"
      certPwd: "$(ios_apple_certificate_password)"
      keychain: "temp"
      **opensslPkcsArgs: '-legacy'**
```
Well, finally was able to fix this issue...

**Comment by DmitriiBobreshev** [comment]
Closing the issue, since the fix seems working. Thanks, @bondarenkod for confirmation!

@pthexton please feel free to reopen it in case the error is still actual.

**Comment by deiv061** [comment]
So the fix is ​​to add this parameter in the future, I believe that OpenSSL will remove this option in the CLI in newer versions. Isn't it nice to fix a task with a newer algorithm to export the certificate?

**Comment by SharpMobileCode** [comment]
> So the fix is ​​to add this еxtra parameter in the future, I believe that OpenSSL will remove this option in the CLI in newer versions. Isn't it nice to fix a task with a newer algorithm to export the certificate?

Yeah, I'm seeing this now on an Azure Pipeline for the macOS-13 image.  I'm getting the same error with the "-legacy" option added.  I also noticed this in the logs:

```
pkcs12: Unrecognized flag legacy
pkcs12: Use -help for summary.
unable to load certificate
```

Seems like the `-legacy` flag has been removed?

**Comment by darijan-darijan** [comment]
Does anyone have any idea why this parameter does not work for me ?
**opensslPkcsArgs: '-legacy'**

I am using the task like this :
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: '$(P12password)'
        certPwd: '$(P12password)'
        keychain: 'temp'
        opensslPkcsArgs: '-legacy'
        
        
        
 The macos 13 error still persists for me
 _2023-06-27T13:12:10.6693620Z Error outputting keys and certificates_
 
Seems like the flag '-legacy' does not get passed through even if I passed it into the **opensslPkcsArgs** parameter in the yml file ?
Please help :(

@DmitriiBobreshev  @pthexton  @bondarenkod

**Comment by darijan-darijan** [comment]
Can someone help please ? 
You have added the -legacy flag and the **opensslPkcsArgs** argument but you didnt say anything about where is it available ?

Do I need to update the Azure Devops version ? 

My current version is **Version Azure DevOps Server 2022 (AzureDevOpsServer_20221122.1)**

Is it tied to the version, or the agent version ? What is it tied to ?

Which Azure Devops version has this argument available 
opensslPkcsArgs

@DmitriiBobreshev @pthexton @bondarenkod

**Comment by bondarenkod** [comment]
> Can someone help please ? You have added the -legacy flag and the **opensslPkcsArgs** argument but you didnt say anything about where is it available ?
> 
> Do I need to update the Azure Devops version ?
> 
> My current version is **Version Azure DevOps Server 2022 (AzureDevOpsServer_20221122.1)**
> 
> Is it tied to the version, or the agent version ? What is it tied to ?
> 
> Which Azure Devops version has this argument available opensslPkcsArgs
> 
> @DmitriiBobreshev @pthexton @bondarenkod

Hello! I'm sorry, I'm not aware of standalone version of the DevOps Server. I'm using private build agents based on MacOS and Windows using the latest available agents (version 2.232.1). Just tried to build iOS - no issues.

**Comment by darijan-darijan** [comment]
<img width="809" alt="Screenshot 2024-01-12 at 3 22 41 PM" src="https://github.com/microsoft/azure-pipelines-tasks/assets/155693958/1bae9cd8-df11-4f99-b313-a02e66f906eb">

@bondarenkod 

Thanks for the reply. Could you please ,in the pipeline logs check which version of the InstallAppleCertificate@2 task you are using ?

This is very finnicky, im not talking about the build agent version, but the version of the InstallAppleCertificate@2 task.

My one is 2.200.0 

I am suspecting its related to this, and I will need to update the version of the task somehow.

**Comment by bondarenkod** [comment]
> <img alt="Screenshot 2024-01-12 at 3 22 41 PM" width="809" src="https://private-user-images.githubusercontent.com/155693958/296615512-1bae9cd8-df11-4f99-b313-a02e66f906eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNjg5MTYsIm5iZiI6MTcwNTI2ODYxNiwicGF0aCI6Ii8xNTU2OTM5NTgvMjk2NjE1NTEyLTFiYWU5Y2Q4LWRmMTEtNGY5OS1iMzEzLWEwMmU2NmY5MDZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQyMTQzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmEzMWU1OTIwOTk2NmZiOTM2NjZlM2E1MDhlOWJjYTc4NjRmYTVjMzBiMDAwM2UwMjhhMWY1OGFlZDU1NzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0DrS-rc7OozVx-KvTtwGScoaEulAMYx22wtWMoq5wF4">
> @bondarenkod @DmitriiBobreshev @pthexton
> 
> Thanks for the reply. Could you please ,in the pipeline logs check which version of the InstallAppleCertificate@2 task you are using ?
> 
> This is very finnicky, im not talking about the build agent version, but the version of the InstallAppleCertificate@2 task.
> 
> My one is 2.200.0
> 
> I am suspecting its related to this, and I will need to update the version of the task somehow.

Here it is:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/3184414/108cb5e2-181c-4954-9c8b-f7a8710201c3)

**Comment by darijan-darijan** [comment]
opensslPkcsArgs arguments gets passed through fine ? @bondarenkod

**Comment by bondarenkod** [comment]
> opensslPkcsArgs arguments gets passed through fine ? @bondarenkod

yep! 
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/3184414/1a56d578-7a3b-49df-b561-d392aa70e6dc)

It seems that the issue you're encountering might be related to an outdated version of OpenSSL. To resolve this, I recommend upgrading OpenSSL to the latest version. This upgrade is particularly important as recent versions of PowerShell require a current version of OpenSSL for optimal performance. Although I don't have extensive details at the moment, I began experiencing similar issues immediately after updating PowerShell through Brew.

**Comment by darijan-darijan** [comment]
@bondarenkod 

The issue for me is the flag does not even get passed. Any flag I put in there

"-legacy" "-fndskfhdkjshjdsf" or anything does not get passed at all

So I believe its Azure devops issue, not the agent issue itself. The flag does not even reach the openssl command.

**Comment by thisisthekap** [comment]
Seems like Microsoft published a fix in macos-15 20241106.316.

With macos-15 20241022.244 I still see failing builds with "pkcs12: Unrecognized flag legacy" warning included.

The unfortunate thing: 20241106.316 does not seem to be published to all hosted agents as of now.

**Comment by pavlyuk1997** [comment]
It is not a problem of the script or task, it looks like on Azure machines we have two versions of OpenSSL
OpenSSL 1.1.1w  11 Sep 2023
OpenSSL 3.4.0 22 Oct 2024 (Library: OpenSSL 3.4.0 22 Oct 2024)

For 3.4.0 we need -legacy for 1.1.1w you will got pkcs12: Unrecognized flag legacy

**Comment by NicolasVas** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/18560#issuecomment-2467987600

We exactly encounter the same situation

**But we have a trick** 

We execute two times the InstallAppleCertificate@2 : 
- One with the "-legacy" parameter
- Another time without the parameter

Both tasks with the `continueOnError: false`

Something like this : 

```yaml
- task: InstallAppleCertificate@2
  displayName: 'Install Certificate without legacy arg (= old Azure machine)'
  continueOnError: true
  inputs:
    certSecureFile: <p12 path>
    certPwd: <pwd>
    
- task: InstallAppleCertificate@2
  displayName: 'Install Certificate with legacy arg (= recent Azure machine)'
  continueOnError: true
  inputs:
    certSecureFile: <p12 path>
    certPwd: <pwd>
    opensslPkcsArgs: '-legacy'
```

And it works : we have some runs where the one with legacy param works and the other one failed, and vice versa (it seems exclusive, no machine handle both)

I presume you can do something better with job or step by using the `condition: failed()`
