### ISSUE TITLE
Pipeline is failing in "Xcode@5"(Build and Sign) task for ios app built in Kivy

### ISSUE THREAD

**Issue by lijithomas88** [microsoft/azure-pipelines-tasks#18572]
### Task name

xcode@5

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Macos 12.6.7

### Question

```shell
Xcode@5 task is failing with error code 65 in signing from Azure devops pipeline. 
Error: /usr/bin/xcodebuild failed with return code: 65

Below is the contents of xcode task.

task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'remotecontrolapp'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/remotecontrolapp-ios/remotecontrolapp.xcodeproj'
    xcodeVersion: 'default'
    packageApp: true
    #exportPath: 'output/$(SDK)/$(Configuration)' # string. Optional. Use when packageApp == true. Export path. Default: output/$(SDK)/$(Configuration).
    #exportOptions: 'auto' # 'auto' | 'plist' | 'specify'. Optional. Use when packageApp == true. Export options. Default: auto.
    #exportMethod: 'development'
    signingOption: 'manual' # Optional. Options: nosign, default, manual, auto
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    provisioningProfileName: 'SDV AppStore Development Profile'
```

**Comment by lijithomas88** [comment]
[dev.azure.com_SW4ZF_bf745bc3-ac4e-4ea6-9c6a-23fedcc3e6b5__apis_build_builds_395340_logs_21.txt](https://github.com/microsoft/azure-pipelines-tasks/files/11916737/dev.azure.com_SW4ZF_bf745bc3-ac4e-4ea6-9c6a-23fedcc3e6b5__apis_build_builds_395340_logs_21.txt)
Please find the debug logs

**Comment by lijithomas88** [comment]
with the above Xcode task, it was not giving details of error code 65. with the below one, it gave error details . 

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'remotecontrolapp'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/remotecontrolapp-ios/remotecontrolapp.xcodeproj'
    xcodeVersion: 'default'
    packageApp: true
    exportPath: 'output/$(SDK)/$(Configuration)' # string. Optional. Use when packageApp == true. Export path. Default: output/$(SDK)/$(Configuration).
    exportOptions: 'auto' 
    exportMethod: 'development'
    signingOption: 'manual' # Optional. Options: nosign, default, manual, auto
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    provisioningProfileName: 'SDV AppStore Development Profile'
    useXcpretty: false

**Comment by ThomasBernard03** [comment]
some news ?
