### ISSUE TITLE
[enhancement]: Yaml DownloadPipelineArtifact - toggle to disable error on failure

### ISSUE THREAD

**Issue by pzaj2** [microsoft/azure-pipelines-tasks#18606]
### Task name

DownloadPipelineArtifact

### Describe your feature request here

I was wondering if there was a possibility to add a toggle to this task that would ignore any errors and deem the task successful regardless of the outcome. It'd be ideal if, in addition to that, the result of the task was surfaced via an output variable.

I have a pipeline where I attempt to download an artifact, and then verify if the artifact was downloaded in order to conditionally run subsequent steps.

I'd be happy to make the changes myself and create a PR, but I first wanted to know what's the likelihood of getting these changes incorporated into this task.

I appreciate that there's a "contineOnError" property that I can use, I do that now, but it marks the pipeline as "partially successful" which is both inconvenient and confusing for other engineers on my team - there's no way to tell why it "partially succeeded".

**Comment by JoeGaggler** [comment]
This may help... you can have a job run conditionally if your download "succeeded with issues":

https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages#how-can-i-trigger-a-job-if-a-previous-job-succeeded-with-issues
