### ISSUE TITLE
[enhancement]: GradleV2 / GradleV3 could check wrapper hashes

### ISSUE THREAD

**Issue by lapo-luchini** [microsoft/azure-pipelines-tasks#18616]
### Task name

GradleV2

### Describe your feature request here

[The Gradle action on GitHub](https://github.com/gradle/wrapper-validation-action) allows for verification that Gradle wrapper JAR is one of the official releses (checked by hashes available from [official Gradle website](https://services.gradle.org/versions/all)). It would be nice if Azure task did that internally too, for the same security reasons.

**Comment by ismayilov-ismayil** [comment]
Hi @lapo-luchini, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
