### ISSUE TITLE
[BUG]: AzureFunctionApp@2 has changed default settings for WEBSITE_RUN_FROM_PACKAGE from 0 to 1 causing critical errors on functionapps

### ISSUE THREAD

**Issue by dipesh747** [microsoft/azure-pipelines-tasks#18626]
### Task name

AzureFunctionApp@2

### Task version

AzureFunctionApp@2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Task log

```shell
Previous WORKING version:
Starting: deploy function app
==============================================================================
Task         : Azure Functions Deploy
Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
Version      : 2.223.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctiontroubleshooting
==============================================================================
##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573/2.223.1/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
Got service connection details for Azure App Service:'dv-eus2-macrocred-fapp'
Updating App Service Application settings. Data: {"FUNCTIONS_WORKER_RUNTIME":"python","WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true","WEBSITE_RUN_FROM_PACKAGE":"0"}


New broken version:
Starting: deploy function app
==============================================================================
Task         : Azure Functions
Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
Version      : 1.221.105
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctiontroubleshooting
==============================================================================
Got service connection details for Azure App Service:'dv-eus2-macrocred-fapp'
(node:1672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Trying to update App Service Application settings. Data: {"WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true","WEBSITE_RUN_FROM_PACKAGE":"1"}


As you can see WEBSITE_RUN_FROM_PACKAGE default has been changed from 0 to 1. This breaks all deployments for me as I need it set to 0 when it deploys.
```

### Relevant log output

```shell
Previous WORKING version:
Starting: deploy function app
==============================================================================
Task         : Azure Functions Deploy
Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
Version      : 2.223.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctiontroubleshooting
==============================================================================
##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureFunctionApp_501dd25d-1785-43e4-b4e5-a5c78ccc0573/2.223.1/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
Got service connection details for Azure App Service:'dv-eus2-macrocred-fapp'
Updating App Service Application settings. Data: {"FUNCTIONS_WORKER_RUNTIME":"python","WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true","WEBSITE_RUN_FROM_PACKAGE":"0"}


New broken version:
Starting: deploy function app
==============================================================================
Task         : Azure Functions
Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
Version      : 1.221.105
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctiontroubleshooting
==============================================================================
Got service connection details for Azure App Service:'dv-eus2-macrocred-fapp'
(node:1672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Trying to update App Service Application settings. Data: {"WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true","WEBSITE_RUN_FROM_PACKAGE":"1"}
```

### Aditional info

```shell
Task task: AzureFunctionApp@2 is giving different versions last week vs. this week. 
2.223.1 on July 3rd with "WEBSITE_RUN_FROM_PACKAGE":"0" autoset 
1.221.105 - on July 10th with "WEBSITE_RUN_FROM_PACKAGE":"1" autoset 

Can you please urgently look into this as it has wiped out my deployments to function apps.
```

**Comment by dipesh747** [comment]
Appreciate if someone could look at this ASAP

**Comment by FinVamp1** [comment]
@dipesh747 1.221.105 - on July 10th with "WEBSITE_RUN_FROM_PACKAGE":"1" autoset . This is the v1 version of the Task. Can you share your YAML or screenshots of how the task was configured? I wouldn't expect you to be downgraded.

**Comment by dipesh747** [comment]
@FinVamp1  Any update on this? It would be good to understand what happened as this bug posed a significant risk to a deployment template which effected multiple users.

**Comment by baumatron** [comment]
This change also breaks deployment for our function apps which need to run with WEBSITE_RUN_FROM_PACKAGE=0. I've tried to change the setting via appSettings, but the setting is changed during deployment which appears to break deployment (the files aren't copied from the zip package, so deployment basically has no effect).

**Comment by FinVamp1** [comment]
> @FinVamp1 Any update on this? It would be good to understand what happened as this bug posed a significant risk to a deployment template which effected multiple users.

@dipesh747  could you open a Support Ticket for the Dev Ops team to help investigate this? We'll need to see what region your deployments were running in to understand why the version number changed?

**Comment by dipesh747** [comment]
Could you provide me a link to the DevOps team?

**Comment by baumatron** [comment]
FWIW I've solved the problem I was seeing. The fix was to use version 2 of the task which no longer seems to set WEBSITE_RUN_FROM_PACKAGE during deployment.

**Comment by FinVamp1** [comment]
> Could you provide me a link to the DevOps team?

In your DevOps organization you can Contact Support 

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/1410302/92b9c42d-28f2-422f-8a95-14ec6f2209dc)


I'll bring this issue to the DevOps team attention offline and if you could email me your subscription ID and your DevOps organization to finbarr AT microsoft.com then I'll see what I can do.

**Comment by FinVamp1** [comment]
Closing this.

Discussed with @baumatron offline and provided this information.

For the v2 task setting WEBSITE_RUN_FROM_PACKAGE= 0 should not be needed when the deploymentMethod is set to zipDeploy.
The ZipDeploy provider removes the app settings you have pointed out and then post deployment updates the app with any custom App Settings that you have set. 
Having WEBSITE_RUN_FROM_PACKAGE not present should be the same as WEBSITE_RUN_FROM_PACKAGE= 0.
