### ISSUE TITLE
[Question]: XamariniOS@2 does not generate .dSYM file

### ISSUE THREAD

**Issue by huyvuskedulo** [microsoft/azure-pipelines-tasks#18668]
### Task name

XamariniOS@2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

macOS

### Question

Somehow when using XamariniOS@2, i'm not able to generate .dSYM file, but when running locally, it seem to be working fine, i'm able to see the file from <ProjectFolder>.iOS/iPhone/Release. So i don't think that's an issue from the project configuration.

Is there anything i can do to make this task generate .dSYM file?

**Comment by aleksandrlevochkin** [comment]
Hi @huyvuskedulo thank you for reporting the issue. Could you please provide some logs related to this error?
