### ISSUE TITLE
[Question]:  How to use the Azure DevOps artifact feed adjacent to the outside feeds ?

### ISSUE THREAD

**Issue by AditiMaheshwari347** [microsoft/azure-pipelines-tasks#18734]
### Task name

NuGet restore

### Task version

2.X

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Latest

### Question

```shell
Is there any option to which enables the parallel utilization of feeds in side the ADO project and external feed in Nuget.config file?
```

**Comment by embetten** [comment]
You can declare multiple package sources in nuget.config. see example [here](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#example-nugetdefaultsconfig-and-application). Then in the nuget restore task use the feeds in my nuget config option from the [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops&tabs=classic). 

However, I believe this will only work for externals feeds that do not require authentication. For external feeds with authentication, I recommend moving away from the restore task. Instead, you could use the NugetAuthenticateV0 task with a script task to call nuget directly. The Nuget Authenticate task would authenticate for the ADO feedn,  then for the external feed you would need an additional task before the nuget script to somehow pass the external feed credentials to nuget in your pipeline, but you would need to figure out how to pass the credentials for the external feed. 

Note: this configuration would open you to dependecy confusion or substitution OSS related attacks. see [this nuget issue with package source mapping](https://github.com/NuGet/Home/issues/10566) to reduce the risk.
