### ISSUE TITLE
[BUG]: Set variable is not working as expected 

### ISSUE THREAD

**Issue by tushmesh** [microsoft/azure-pipelines-tasks#18756]
### Task name

bash

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows-2019, ubuntu

### Task log

```shell
- bash: |
              branchname="$(Build.SourceBranchName)"
              echo "Before $branchname"
              echo "##vso[task.setvariable variable=branch_name1;]$(branchname)"
              echo "##vso[task.setvariable variable=branch_name2;]${Build.SourceBranchName}"
              echo "##vso[task.setvariable variable=branch_name3;]$(Build.SourceBranchName)"
              echo "##vso[task.setvariable variable=branch_name4;]main"
              echo "Branch Name is $(branch_name1) or $(branch_name2) and $(branch_name3) and $(branch_name4)"
```

### Relevant log output

```shell
Before main
/d/a/_temp/597f0672-8496-45dd-a472-4042305be516.sh: line 7: branch_name1: command not found
/d/a/_temp/597f0672-8496-45dd-a472-4042305be516.sh: line 7: branch_name2: command not found
/d/a/_temp/597f0672-8496-45dd-a472-4042305be516.sh: line 7: branch_name3: command not found
/d/a/_temp/597f0672-8496-45dd-a472-4042305be516.sh: line 7: branch_name4: command not found
Branch Name is or and and
```

### Aditional info

```shell
Nothing is printing as part of the set variable.
Expected output is to print the "main" for all the set variables.
```

```[tasklist]
### Tasks
```

**Comment by ivanduplenskikh** [comment]
[Documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash#set-an-output-variable-for-use-in-the-same-job) mentions that only **following** tasks have access to variable
> When you add a variable with `task.setvariable`, the **following** tasks can use the variable using macro syntax `$(myVar)`

I'm closing this issue - feel free to ask any other questions or let us know if it's still relevant for you.

**Comment by tushmesh** [comment]
- bash: |
              echo "##vso[task.setvariable variable=branch_name4;]main",


This also not working, which was working previously.

**Comment by tushmesh** [comment]
I too got the proper value now. ( If I use another task to echo )
Only thing is if we echo the in the same bash , it do not print and give error message.

**Ex:** 
  pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job:
    displayName: Set and print variable
    steps:
    - bash: |
             echo "##vso[task.setvariable variable=branch_name4;]main"
             "echo $(branch_name4)"
             echo "$(branch_name4)"

**Comment by ivanduplenskikh** [comment]
The agent can not extract variables from the output and declare them in one task.
From documentation:
> When you use PowerShell and Bash scripts in your pipelines, it's often useful to be able to set variables that you can then use in future tasks. **Newly set variables aren't available in the same task.**

**Comment by tushmesh** [comment]
Thank You for your support and guidance.
