### ISSUE TITLE
Help needed in testing my VM with all the softwires installed to run my CI pipeline

### ISSUE THREAD

**Issue by gyuvaraj10** [microsoft/azure-pipelines-tasks#18803]
### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [x] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server -2019 Datacenter

### Question

```shell
I am setting up a VM image that can be used for creating the VMs that can run the azure devops agents. This VM image is provisioned via packer and I want to test if the software (Docker, Visual Studio Build Tools, Nodejs, etc., ) provisioned via packer, will support the azure DEVOPS tasks such as Docker2, Npm@1, VSBuild@1,  VSTest@2.

IMP: Here I want to test if the above tasks will work during the VM image provisioning only and I want to integrate these tests as part of my packer pipeline.

Any suggestions?
```

**Comment by kirill-ivlev** [comment]
Hi @gyuvaraj10,tion
Thank you for your question!
If I got your question right, you may implement some similar checks used in agent to detect [capabilities](https://github.com/microsoft/azure-pipelines-agent/blob/d1af46059d69cedb25c564c2fde1a0c247d15557/src/Microsoft.VisualStudio.Services.Agent/Capabilities/UserCapabilitiesProvider.cs#L17)

**Comment by gyuvaraj10** [comment]
Hi @kirill-ivlev , Thank you for reply, I have noticed that the User capabilities are not visible for vmss type agent pool. In my usecase, I can not check the User Capabilities. Please suggest.
