### ISSUE TITLE
[BUG]: Error when executing AdditionalArguments for AzureRmWebAppDeployment V4.227.0 

### ISSUE THREAD

**Issue by mathieu-decroocq** [microsoft/azure-pipelines-tasks#18841]
### Task name

AzureRmWebAppDeploymentV4

### Task version

227.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
Starting: Deploy WebApp
==============================================================================
Task         : Azure App Service deploy
Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
Version      : 4.227.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azureappservicetroubleshooting
==============================================================================
Got service connection details for Azure App Service:'XX-WebApp-4'
Trying to update App Service Application settings. Data: null
App Service Application settings are already present.
"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='C:\agent\_work\77\AppsArtifacts\WebApps\WebApp\WebApp.zip' -dest:auto,ComputerName='xxx',UserName='xxx',Password='***',AuthType='Basic' -setParam:name='IIS Web Application Name',value='WebApp-Name' -skip:objectName=filePath,absolutePath=^.*\.config$ -skip:objectName=filePath,absolutePath=favicon.ico -skip:objectName=filePath,absolutePath=appsettings.json -skip:objectName=dirPath,absolutePath=^.*Resources(?!CL|Generic|\\|$).*$ -enableRule:DoNotDeleteRule -userAgent:VSTS_dfbe8c30-6ad4-45b7-93f6-497ce161b00b_build_95_0

##[error]Error: 'Generic' is not recognized as an internal or external command,
operable program or batch file.
```

### Relevant log output

```shell
Error: 'Generic' is not recognized as an internal or external command, operable program or batch file.
```

### Aditional info

```shell
Since upgrading from version 4.225.1 to 4.227.0, we've had an error with the AdditionalArguments parameter.
It seems that double quotes are not considered. 
Here's the linked yml excerpt:
AdditionalArguments: '-skip:objectName=filePath,absolutePath="^.*\.config$" -skip:objectName=filePath,absolutePath="favicon.ico" -skip:objectName=filePath,absolutePath="appsettings.json" -skip:objectName=dirPath,absolutePath="${{ parameters.skipFolder }}"'

And the result in Azure Devops: 
-skip:objectName=filePath,absolutePath=^.*\.config$ -skip:objectName=filePath,absolutePath=favicon.ico -skip:objectName=filePath,absolutePath=appsettings.json -skip:objectName=dirPath,absolutePath=^.*Resources(?!CL|Generic|\|$).*$
```

**Comment by DmitriiBobreshev** [comment]
Hi @mathieu-decroocq, seems like the problem started happening after changing the task handler to Node16, we [started to use](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/main/common-npm-packages/webdeployment-common/deployusingmsdeploy.ts#L179) shell: true options because [the bug](https://github.com/nodejs/node/issues/7367#issuecomment-229728704) in the node ecosystem when the path contains spaces(e.g. C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe) and seems like the [old logic](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/main/common-npm-packages/webdeployment-common/deployusingmsdeploy.ts#L105) with escaping arguments works weird when the task converting arguments string to array. 
As a workaround, you can escape double quotes as `"\"` at the start and `\"` at the end.
full example will be `-skip:objectName=dirPath,absolutePath="\"${{ parameters.skipFolder }}\"`. 
Sorry for the inconvenience, we'll try to fix the problem in the next versions.

**Comment by alexangas** [comment]
@DmitriiBobreshev Unfortunately this is a breaking behaviour change across all of our web app deployment pipelines. It's not a simple fix for us to make the suggested alteration, or to revert to an older version of the task.

Is there any way the automatic escaping can be put in place ASAP please?

**Comment by mathieu-decroocq** [comment]
Hi,
Thank you for your answers.
I tried to use the escape characters without success.
I've simplified my command and my folder skip regex in order to have a workaround but I'm not satisfied with the result.

`AdditionalArguments: -skip:File='^.*\.config$' -skip:File='favicon.ico' -skip:File='appsettings.json' -skip:Directory='^.*Resources.*$'`

**Comment by merlynomsft** [comment]
We are sorry for the delay in resolving this issue.  To mitigate it, we rolled back to an earlier version, 4.225.1, which is not affected by the issue above.  If you have any questions or concerns, please let us know.

**Comment by alexangas** [comment]
@merlynomsft Appreciate the rollback, thank you.

Both this issue and #14365 affected us and broke a number of our pipelines unexpectedly, which obviously has been a very poor customer experience as they are critical to our ability to deploy.

We're a little confused as to the testing process that has or hasn't taken place here. We are also unsure as to why such a significant move such as migrating to Node 16 that contains behavioural changes was not done as part of a major task version, which probably would have avoided any of these types of problems at all.
