### ISSUE TITLE
[BUG]: The specified module '\ps_modules\Sanitizer' was not loaded because no valid module file was found in any module directory

### ISSUE THREAD

**Issue by JordanMaclachlan-RLG** [microsoft/azure-pipelines-tasks#18858]
### Task name

Windows machine file copy

### Task version

1.227.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2019

### Task log

```shell
System.Management.Automation.RemoteException: The specified module '\ps_modules\Sanitizer' was not loaded because no valid module file was found in any module directory.
System.Management.Automation.RemoteException: The term 'Write-VstsTaskError' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
System.Management.Automation.RemoteException: The specified module '\ps_modules\Sanitizer' was not loaded because no valid module file was found in any module directory.
System.Management.Automation.RemoteException: The term 'Write-VstsTaskError' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PowerShell script completed with 4 errors.
```

### Relevant log output

```shell
The specified module '\ps_modules\Sanitizer' was not loaded because no valid module file was found in any module directory
```

### Aditional info

```shell
This error appeared over night since we automatically took the new sanitizer change.
```

**Comment by LeftTwixWand** [comment]
Hi @JordanMaclachlan-RLG. Thank you for this issue, we're already working on its solution.
If you have access to your self-hosted agent, may I ask you to share some details.

Can you please go to the agent folder -> _worker -> _tasks
Usually the path looks like this: `C:\agent\_work\_tasks`
And then, can you achieve the `WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210` folder and share it here.
This folder contains source code for the `WindowsMachineFileCopy` tasks and it would help us a lot.

**Comment by LeftTwixWand** [comment]
@JordanMaclachlan-RLG can you also share the link of failing pipeline, so we can investigate it further.
The format should be like this:
https://dev.azure.com/{organization}/{project}/_build/results?buildId={id}&view=results

**Comment by LeftTwixWand** [comment]
Hey, @JordanMaclachlan-RLG thank you so much for the help.
Your archive was really useful.

I would like to ask you to share the full pipeline log of your first run, where you faced the issue.
You can download it here:
<img width="743" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/50652041/70dfb3d2-3f7f-4329-867d-b678ff545531">

If you are concerned about safety, you can send it on my Microsoft email: vhorbachov@microsoft.com

**Comment by JordanMaclachlan-RLG** [comment]
This should be he first failure log. We are extensively using this task in 100s of pipelines so this failure really knocked us. Would you have a possible timescale for a fix? this will determine if we need need to wrote our own task or wait.  I will let you know if i get the go ahead to send the pipeline.
[Attempt1.zip](https://github.com/microsoft/azure-pipelines-tasks/files/12431336/Attempt1.zip)

**Comment by LeftTwixWand** [comment]
Hey @JordanMaclachlan-RLG thank you so much for sharing these details.
I can't say how much time it will take, but I hope to fix it in the next few days.

**Comment by v-mohithgc** [comment]
Hi @JordanMaclachlan-RLG if possible, can you try to clear the task cache from "C:\agent\_work\_tasks.....", once clear 1.227.0, the agents should be able to automatically pick task version 1.226.1 (which was the previous working version).

if you're using Microsoft-hosted agent, the agents will automatically pick version 1.226.1.

**Comment by JordanMaclachlan-RLG** [comment]
Morning, i see  the sanitizer import is still there in main? is this not going to throw the same issues? or have you just re published the previous version?

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/WindowsMachineFileCopyV1/WindowsMachineFileCopy.ps1

Jordan

**Comment by v-mohithgc** [comment]
> Morning, i see the sanitizer import is still there in main? is this not going to throw the same issues? or have you just re published the previous version?
> 
> https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/WindowsMachineFileCopyV1/WindowsMachineFileCopy.ps1
> 
> Jordan

Hi GM, we had reverted back the task version on last Friday from the backend, for Microsoft hosted agent it was able to auto pick the reverted version (ie 1.226.1), but for self-hosted agent users, there is some manual procedure to follow in order for agents to pick the reverted version(1.226.1).

The manual procedure is to clear the 1.227.0 task cache/folder within the agent folder. once it's cleared the agent will be able to pick 1.226.1(working fine)

**Comment by JordanMaclachlan-RLG** [comment]
Looking at the code in 1.226 on our servers its also including Sanitiser?  Version 1.225 is the one that doesn't include these modules. Would it not be better to revert back to 1.225?

Jordan

**Comment by v-mohithgc** [comment]
This issue is now resolved.
V228.1 will be containing the fix, which will be out by tomorrow to all the regions.
Feel free to reopen this issue if needed.
