### ISSUE TITLE
[enhancement]: Expose branch name that was merged into another branch in the build triggered by the merge / PR

### ISSUE THREAD

**Issue by mikeweltevrede** [microsoft/azure-pipelines-tasks#18899]
### Describe your feature request here

# Summary
We would like to know the name of the source branch on the build pipeline that was triggered on `main` **after** merging the PR for that source branch. This is similar to `system.pullRequest.sourceBranch` which was added in #2147 but at a different time in the merging process.

# Example
After merging `feature/my-feature/dev` to `main` via the PR, commit A is created and the Build pipeline is kicked off. I would like that Build to be able to know the source branch `feature/my-feature/dev`.
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/46759318/ac1fff41-9238-4e60-9147-8f1cc2cfb195)

# Own research
Some information and suggestions that I have found while researching:
1. Using a post-merge hook [(link)](https://www.liquidlight.co.uk/blog/using-a-post-merge-git-hook-to-clean-up-old-branches/). Locally, this does seem to work:
```bash
$ git commit -am "More changes"
[feature/my-feature/dev 0af0ee3] More changes
 1 file changed, 1 insertion(+)
$ git checkout main_dummy1
Switched to branch 'main_dummy1'
Your branch is up to date with 'origin/main_dummy1'.
$ git merge feature/my-feature/dev
Updating 6c47780..0af0ee3
Fast-forward
 README.md | 1 +
 1 file changed, 1 insertion(+)
$ git reflog -1
0af0ee3 (HEAD -> main_dummy1, feature/my-feature/dev) HEAD@{0}: merge feature/my-feature/dev: Fast-forward
```

However, this does not work on ADO since the `git reflog` after completing a PR from `feature/my-feature/dev` into `main_dummy1` does not seem to show what is included locally but instead shows: `7044824 HEAD@{0}: checkout: moving from master to refs/remotes/origin/7044824`. 

2. In BitBucket repo, it provides default commit message when trying to merge one branch into another [(StackOverflow link)](https://stackoverflow.com/a/63447290). In that way, we could retrieve the branch name from there.

**Comment by KonstantinTyukalov** [comment]
Hi @mikeweltevrede, thank you for posting this feature request. Currently, we’re working on higher priority issues, but we’ll get back to this one soon.

**Comment by max-zaytsev** [comment]
@mikeweltevrede Thank you for posting this issue. Since this is not related to any specific pipeline task, I'm closing it. Please provide your suggestion in the [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps). This is the appropriate place for such feature requests.
