### ISSUE TITLE
[BUG]: PowerShell@2.227.0 breaks on PowerShell v4.0

### ISSUE THREAD

**Issue by scottmwyant** [microsoft/azure-pipelines-tasks#18895]
### Task name

PowerShell

### Task version

2.227.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2012

### Task log

```shell
2023-08-29T16:07:45.6040747Z ##[section]Starting: PowerShell
2023-08-29T16:07:45.6241180Z ==============================================================================
2023-08-29T16:07:45.6241493Z Task         : PowerShell
2023-08-29T16:07:45.6241773Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2023-08-29T16:07:45.6242028Z Version      : 2.227.0
2023-08-29T16:07:45.6242249Z Author       : Microsoft Corporation
2023-08-29T16:07:45.6242566Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2023-08-29T16:07:45.6242939Z ==============================================================================
2023-08-29T16:07:46.9431573Z ##[error]At X:\AzureDevOpsAgent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.227.0\errors.ps1:1 char:1
+ class ArgsSanitizingException : Exception {
+ ~~~~~
The 'class' keyword is not supported in this version of the language.


2023-08-29T16:07:47.0382386Z ##[section]Finishing: PowerShell
```

### Relevant log output

```shell
The 'class' keyword is not supported in this version of the language.
```

### Aditional info

```shell
Windows PowerShell
Copuright(C) 2014 Microsoft Corporation.  All rights reserved.

PS C:\Users\user> $PSVersionTable
Name                           Value                                                                   
----                           -----                                                                   
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.20719
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

PS C:\Users\user>
```
```

**Comment by nanny07** [comment]
> Immediate work-around applied by specifying `PowerShell@2.226.2` in the pipeline definition file.

You can't change the version with the classic pipeline editor so this is a real problem

**Comment by KonstantinTyukalov** [comment]
We apologize for the issue caused. We have restored the previous version of the task. Could you please check if the problem persists?
Thank you

**Comment by scottmwyant** [comment]
@KonstantinTyukalov are you saying the version rolled up above 2.227.0 but the code is actually rolled back?  I shared that since I use YAML pipeline I was able to lock down to 2.226.2 and it worked fine.  Sounds like you are saying that changes were made and going back to `PowerShell@2` is expected to work now.  Please confirm so I am clear on what to test.

**Comment by scottmwyant** [comment]
Still failed but my local agent still has 2.227.0, not sure how your recent change (rollback) would impact my local agent, I haven't needed to dig into the agent to this level before.

**Comment by nanny07** [comment]
> @scottmwyant
> 
> > Sounds like you are saying that changes were made and going back to PowerShell@2 is expected to work now.
> 
> correct. Currently, pipeline should place 2.226.2 instead of 2.227.0 by default

Do we need to delete the 2.227.0 folder on the agent?

**Comment by c0shea** [comment]
@KonstantinTyukalov This is still not working. Even after deleting the 2.227.0 folder, it still downloads version 2.227.0 of the task and doesn't use 2.226.2.

**Comment by KonstantinTyukalov** [comment]
@nanny07  @c0shea  @scottmwyant could you please re-check now?

**Comment by scottmwyant** [comment]
@KonstantinTyukalov working for me, task is reporting version 2.226.2. 

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/29161635/8c3925f9-a769-4945-b4fa-aba99c897964)

**Comment by c0shea** [comment]
@KonstantinTyukalov Now it works

**Comment by nanny07** [comment]
@KonstantinTyukalov I can confirm that it works now as it has been fully restored to version 2.226.2

**Comment by KonstantinTyukalov** [comment]
Closing this issue as duplicate
