### ISSUE TITLE
[BUG]: overrideParameters does not handle values with spaces

### ISSUE THREAD

**Issue by ArturAdam** [microsoft/azure-pipelines-tasks#18973]
### Task name

AzureResourceGroupDeployment

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
There was an error while overriding '' parameter because of 'TypeError: Cannot read properties of undefined (reading 'type')', make sure it follows JavaScript Object Notation (JSON)
```

### Relevant log output

```shell
There were errors in your deployment. Error code: InvalidDeploymentParameterKey.
```

### Aditional info

```shell
This does not work:
overrideParameters: 
 -example "some thing" //same without double quotes

this works: 
overrideParameters:
 -example something
```

**Comment by ozanaydinMSFT** [comment]
hey @ArturAdam ;  thanks for the report.

Could you please try to enable this checkbox under "Advanced" section and try again?

> Use individual output values without JSON.Stringify applied

<img width="358" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/2474419/ed4587b9-e3aa-41d2-9fb1-25de28a88a2d">

Or if you're using yaml; this is the input:

> useWithoutJSON: true

**Comment by ArturAdam** [comment]
that worked. thank you

**Comment by ArturAdam** [comment]
That worked. Thank you!
