### ISSUE TITLE
[enhancement]: option to retry failed download

### ISSUE THREAD

**Issue by kcsomisetty** [microsoft/azure-pipelines-tasks#18978]
### Task name

NodeTool@0

### Describe your feature request here

While trying to use this task to download Node, our pipelines run into download failures.
This aborts the pipelines and causes errors. 
Can you add a parameter to this task, which upon setting will retry the failed download.

**Comment by ismayilov-ismayil** [comment]
Hi @kcsomisetty. Did you try retryCountOnTaskFailure flag?

**Comment by kohithreddy** [comment]
Hi @kcsomisetty, 

Can you share which task you are talking about? Is it [nodetool installer](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-tool-v0?view=azure-pipelines)?

As [@ismayilov-ismayil](mention:ismayilov-ismayil) mentioned, Azure DevOps supports [Automatic retries for a task](https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-195-update#automatic-retries-for-a-task).

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/6813618/8f1780ba-7703-474d-9899-b4c429ac2e2c)

**Comment by kcsomisetty** [comment]
will use retryCountOnTaskFailure and let you all know the result.
