### ISSUE TITLE
[enhancement]: Support junit attachments in PublishTestResults

### ISSUE THREAD

**Issue by strowk** [microsoft/azure-pipelines-tasks#18993]
### Task name

PublishTestResults@2

### Describe your feature request here

PublishTestResults currently only supports attachments provided by reports in trx and nunit formats. I believe junit format has found a wider support in overall community and it would be great if there'd be support for attachments for junit as well.

See as example partial support by Gitlab:
https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html#view-junit-screenshots-on-gitlab
, which only applies to screenshots, though. 
This is mostly to demonstrate the standard approach in representing attachments in junit reports and that other CI/CD products take an effort to support junit.

Another good example is this, which, I believe, follows same format: 
https://github.com/michaelleeallen/mocha-junit-reporter#attachments

**Comment by rra-topdev** [comment]
This should be working, but it isn't working for me:
https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/
