### ISSUE TITLE
[enhancement]: BicepParam support for AzureResourceManagerTemplateDeployment

### ISSUE THREAD

**Issue by BertusV** [microsoft/azure-pipelines-tasks#19064]
### Task name

BicepParam file support

### Describe your feature request here

The AzureResourceManagerTemplateDeployment task is supporting BICEP template files but does not support BicepParam files.

Currently it generates this error:   ##[error]Error: Ensure the Parameters file ( '/home/vsts/work/1/s/..../..../xxxxxxx.bicepparam' ) is valid. Task failed while parsing with following error: Unexpected token u in JSON at position 0

Cold you please support this.  BicepParam files are so much cleaner to author.

**Comment by v-mohithgc** [comment]
Hi @BertusV thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by BertusV** [comment]
Thanks.

**Comment by guestdj** [comment]
Any updates on the support for .bicepparam files - it would be nice to NOT have to use the .json file in this task
