### ISSUE TITLE
[Question]: Cross platform deploys of DACPACs

### ISSUE THREAD

**Issue by johnborges** [microsoft/azure-pipelines-tasks#19071]
### Task name

SqlAzureDacpacDeployment

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Linux

### Question

```shell
Is there an available task that can deploy DACPACs to Azure without requiring Windows host?
```

**Comment by SvenRelijveld1995** [comment]
Also interested in cross-platform support for SqlAzureDacpacDeployment! Working with Linux on a VM Scale Set
