### ISSUE TITLE
[Question]: AzureFileCopyV1-V5 Support for workload identity federation

### ISSUE THREAD

**Issue by fontexD** [microsoft/azure-pipelines-tasks#19114]
### Task name

workload identity federation support for filecopy to blob

### Task version

1.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows 10

### Question

```shell
when we try to update our authentication with workload identity federation we get the error the error its not supported , is there any work on this or any workaround so we can move away from service-princicals ? into using workload identity federation
```

**Comment by v-mohithgc** [comment]
Hi thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by alexvanderberkel** [comment]
Hi guys, 

is there any progress on this issue? Microsoft is advertising to migrate over to workload identities but should also support all pipelines tasks. An update on this task would be good to have. Thanks.

**Comment by ryanberger-az** [comment]
Hi all, any update on this? We are also facing this issue and are going to have to resort back to using a service principal (secret) for AzureFileCopy tasks in ADO pipelines. Thanks!

**Comment by m-soltani** [comment]
I would like to stress the importance of having this feature implemented. We have the same situation as @ryanberger-az mentioned above.

**Comment by ffloimair** [comment]
WTH. Once again Microsoft is urging customers to move to Workload Identity federation only for the customer to find out that they are not prepared. How can it be that this task has not got any attention 5 months after it has been reported?
Sorry guys but this is unprofessional behavior.

**Comment by v-mohithgc** [comment]
The [AzureFileCopyV6](https://learn.microsoft.com/azure/devops/release-notes/2024/pipelines/sprint-236-update#new-azurefilecopy6-task-supports-secret-less-configurations) task resolves this issue. It also uses Azure RBAC to access blob storage instead. This requires the identity of the service connection used to have the appropriate RBAC role e.g. [Storage Blob Data Contributor](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-contributor). See [Assign an Azure role for access to blob data](https://learn.microsoft.com/azure/storage/blobs/assign-azure-role-data-access?tabs=portal).
