### ISSUE TITLE
[BUG]: Incident 441856953 : Download of pipeline artifacts intermittently hit "Out of Memory" error

### ISSUE THREAD

**Issue by alexlamtest** [microsoft/azure-pipelines-tasks#19291]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Download Pipeline Artifacts

### Task version

2.198.0

### Issue Description

[ This is for IcM ticket #441856953, in which I was asked to file an issue here. ]

The “Out Of Memory” error is captured in the following log:
 
```
Download from the specified build: #83057689
Download artifact to: D:\_work\1\s\WindowsAppSDK-Samples\Samples
Using default max parallelism.
Max dedup parallelism: 192
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Hashtype: Dedup64K
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 4,697.4 MB out of 4,884.8 MB (96%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 3,127.9 MB out of 4,884.8 MB (64%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Downloaded 3,130.1 MB out of 4,884.8 MB (64%).
…
Downloaded 3,130.1 MB out of 4,884.8 MB (64%).
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 3,101.3 MB out of 4,884.8 MB (63%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 1,277.4 MB out of 4,884.8 MB (26%).
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
##[error]One or several exceptions have been occurred.
##[error]System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at Microsoft.VisualStudio.Services.BlobStore.Common.ByteArrayPool.CreateNew(Int32 bufferSize)
at Microsoft.VisualStudio.Services.BlobStore.Common.ByteArrayPool.<>c__DisplayClass2_0.<.ctor>b__0()
at Microsoft.VisualStudio.Services.BlobStore.Common.Pool`1.Get()
at Microsoft.VisualStudio.Services.BlobStore.Common.ChunkerHelper.BorrowChunkBuffer(Int32 size)
at Microsoft.VisualStudio.Services.BlobStore.Common.DedupCompressedBuffer.EnsureUncompressedBufferAvailable()
at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UpdateCountersOfDownload(MaybeCached`1 bytes, NodeType type)
at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.<>c__DisplayClass41_0.<<DownloadToWriterAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingTransformBlockUtils.<>c__DisplayClass1_0`2.<<CreateNonSwallowingTaskFunc>b__0>d.MoveNext()
Finishing: Download Release SamplesBuildOutput_ResourceManagement-cs
```
 
In contrast, download of the same artifact in the same pipeline run ([Pipelines - Run 20231109.18 (azure.com)](https://dev.azure.com/microsoft/ProjectReunion/_build/results?buildId=83057689&view=results)) to 4 other arm64 VMs were successful, such as this:
 
```
Download from the specified build: #83057689
Download artifact to: D:\_work\1\s\WindowsAppSDK-Samples\Samples
Using default max parallelism.
Max dedup parallelism: 192
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 09e42310-e01a-4af8-b712-14c34c57f69fA
Hashtype: Dedup64K
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 09e42310-e01a-4af8-b712-14c34c57f69f
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
 …
Downloaded 4,884.8 MB out of 4,884.8 MB (100%).
Download statistics: …
```

The above example is on arm64. A similar problem affects x64, but apparently to a different extend.
Empirically, artifacts 5+ GB seem to hit this issue relatively easily on x64, while on arm64, artifacts 4+ GB seem to hit this issue relatively easily.
We are using 1ES hosted pool for both arm64 and x64 when downloading the pipeline artifacts.

There are compelling signs that can rule out the target disk size as a factor:
1.	Using the pipeline run linked previously, I’ve calculated the total size of all 29 “sample app build output artifacts” (the size of each artifact rounded up to 1 MB) to be downloaded to the VM in the WinAppSDK-Test-Pool-Arm64. It is 49670 MB (decompressed). Immediately before the download of those 29 artifacts, I know there are 72+ GB free on the target disk (total size 75 GB), as shown below. IOW, even after all 29 artifacts have finished download, there should still be 20+ GB of free space.
```
DeviceId MediaType FreeSpace UsedSpace
D:       12        72.11     2.89
```
2.	At the point of download failure in the pipeline run linked, only ~30 GB worth of artifacts have finished download, at this point the target disk is only about half full. But an even stronger sign is that, after hitting the OutOfMemory download failure for an artifact of size 4885 MB, the same job continued to successfully download another ~13000 MB of artifacts. IMHO, this sign alone is sufficient to rule out disk size as a factor.
3.	More often than not, when this OutOfMemory error is hit during artifact download, causing the job to fail, a simple rerun of the job would succeed. If disk space is the limiting factor, one would expect a simple rerun of the job to be usually not helpful.

Given that we are hitting this issue on both x64 and arm64, I suspect we are not hit by a bit-ness mismatch issue like this: [Download Pipeline Artifacts - System.OutOfMemoryException · Issue #11063 · microsoft/azure-pipelines-tasks (github.com)](https://github.com/microsoft/azure-pipelines-tasks/issues/11063).
OTOH, the behavior we seeing looks similar to: [Download VSTS Drop and Run Script doesn't work with large files · Issue #388 · Azure/azure-devtestlab (github.com)](https://github.com/Azure/azure-devtestlab/issues/388)

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10, Windows 11

### Relevant log output

```shell
Download from the specified build: #83057689
Download artifact to: D:\_work\1\s\WindowsAppSDK-Samples\Samples
Using default max parallelism.
Max dedup parallelism: 192
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Hashtype: Dedup64K
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 4,697.4 MB out of 4,884.8 MB (96%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 3,127.9 MB out of 4,884.8 MB (64%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Downloaded 3,130.1 MB out of 4,884.8 MB (64%).
…
Downloaded 3,130.1 MB out of 4,884.8 MB (64%).
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 3,101.3 MB out of 4,884.8 MB (63%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
…
Downloaded 1,277.4 MB out of 4,884.8 MB (26%).
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
##[error]One or several exceptions have been occurred.
##[error]System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at Microsoft.VisualStudio.Services.BlobStore.Common.ByteArrayPool.CreateNew(Int32 bufferSize)
at Microsoft.VisualStudio.Services.BlobStore.Common.ByteArrayPool.<>c__DisplayClass2_0.<.ctor>b__0()
at Microsoft.VisualStudio.Services.BlobStore.Common.Pool`1.Get()
at Microsoft.VisualStudio.Services.BlobStore.Common.ChunkerHelper.BorrowChunkBuffer(Int32 size)
at Microsoft.VisualStudio.Services.BlobStore.Common.DedupCompressedBuffer.EnsureUncompressedBufferAvailable()
at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UpdateCountersOfDownload(MaybeCached`1 bytes, NodeType type)
at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.<>c__DisplayClass41_0.<<DownloadToWriterAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingTransformBlockUtils.<>c__DisplayClass1_0`2.<<CreateNonSwallowingTaskFunc>b__0>d.MoveNext()
Finishing: Download Release SamplesBuildOutput_ResourceManagement-cs
```

### Full task logs with system.debug enabled

<details>
  <pre> 
Downloaded 3,101.3 MB out of 4,884.8 MB (63%).
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]
Filtered 9769 files from the Minimatch filters supplied.
Downloaded 0.0 MB out of 4,884.8 MB (0%).
Downloaded 45.7 MB out of 4,884.8 MB (1%).
Downloaded 45.8 MB out of 4,884.8 MB (1%).
Downloaded 46.1 MB out of 4,884.8 MB (1%).
Downloaded 110.9 MB out of 4,884.8 MB (2%).
Downloaded 163.4 MB out of 4,884.8 MB (3%).
Downloaded 163.4 MB out of 4,884.8 MB (3%).
Downloaded 163.5 MB out of 4,884.8 MB (3%).
Downloaded 276.7 MB out of 4,884.8 MB (6%).
Downloaded 371.0 MB out of 4,884.8 MB (8%).
Downloaded 371.1 MB out of 4,884.8 MB (8%).
Downloaded 371.1 MB out of 4,884.8 MB (8%).
Downloaded 478.8 MB out of 4,884.8 MB (10%).
Downloaded 551.8 MB out of 4,884.8 MB (11%).
Downloaded 551.8 MB out of 4,884.8 MB (11%).
Downloaded 551.8 MB out of 4,884.8 MB (11%).
Downloaded 659.7 MB out of 4,884.8 MB (14%).
Downloaded 695.8 MB out of 4,884.8 MB (14%).
Downloaded 695.8 MB out of 4,884.8 MB (14%).
Downloaded 695.8 MB out of 4,884.8 MB (14%).
Downloaded 799.6 MB out of 4,884.8 MB (16%).
Downloaded 824.8 MB out of 4,884.8 MB (17%).
Downloaded 824.8 MB out of 4,884.8 MB (17%).
Downloaded 824.8 MB out of 4,884.8 MB (17%).
Downloaded 971.9 MB out of 4,884.8 MB (20%).
Downloaded 978.3 MB out of 4,884.8 MB (20%).
Downloaded 978.3 MB out of 4,884.8 MB (20%).
Downloaded 978.3 MB out of 4,884.8 MB (20%).
Downloaded 1,145.9 MB out of 4,884.8 MB (23%).
Downloaded 1,145.9 MB out of 4,884.8 MB (23%).
Downloaded 1,145.9 MB out of 4,884.8 MB (23%).
Downloaded 1,145.9 MB out of 4,884.8 MB (23%).
Downloaded 1,277.4 MB out of 4,884.8 MB (26%).
Downloaded 1,277.4 MB out of 4,884.8 MB (26%).
Downloaded 1,277.4 MB out of 4,884.8 MB (26%).
Downloaded 1,277.4 MB out of 4,884.8 MB (26%).
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 42361488-321b-46fb-8594-03a36cab029d
##[error]One or several exceptions have been occurred.
##[error]System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.VisualStudio.Services.BlobStore.Common.ByteArrayPool.CreateNew(Int32 bufferSize)
   at Microsoft.VisualStudio.Services.BlobStore.Common.ByteArrayPool.<>c__DisplayClass2_0.<.ctor>b__0()
   at Microsoft.VisualStudio.Services.BlobStore.Common.Pool`1.Get()
   at Microsoft.VisualStudio.Services.BlobStore.Common.ChunkerHelper.BorrowChunkBuffer(Int32 size)
   at Microsoft.VisualStudio.Services.BlobStore.Common.DedupCompressedBuffer.EnsureUncompressedBufferAvailable()
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.UpdateCountersOfDownload(MaybeCached`1 bytes, NodeType type)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.<>c__DisplayClass41_0.<<DownloadToWriterAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingTransformBlockUtils.<>c__DisplayClass1_0`2.<<CreateNonSwallowingTaskFunc>b__0>d.MoveNext()
Finishing: Download Release SamplesBuildOutput_ResourceManagement-cs</pre>
</details>

**Comment by alexlamtest** [comment]
By correlating the values of the "\Memory\Available MBytes" counter in the PerformanceCounters table, I was able to demonstrated that when the OOM exception hit a pipeline artifact download session, its timing does _not_ align with the point in time when the "available memory on the job agent" is at minimal. IOW, looks like OOM Exception != out of RAM. I've posted my findings in IcM ticket #441856953.

**Comment by alexlamtest** [comment]
I found a 3rd strong sign that shows the OOM exceptions are not correlated to "low available RAM" condition of the test VMs:
There is a total of 4 arm64 test VMs downloading the same set of pipeline artifacts in the same pipeline run cited in the IcM ticket #441856953.
This new sign shows that in the studied pipeline run, 3 arm64 test VMs downloaded all pipeline artifacts with no issue but 1 arm64 test VM hit OOM exception twice and the 2nd instance fatally terminated the job. At the point of lowest available RAM on the 3 successful VMs, ~179 MB was available, which is significantly lower than the ~228 MB and ~406 MB available when the 1st and 2nd OOM exception hit. There

Considering all 3 signs: there seems to be a bug somewhere which cannot be avoided by simply upgrading the arm64 test VMs to more RAM, because the OOM exceptions don't seem to correlate with the "lowest available RAM" conditions on the test VMs.

**Comment by alexlamtest** [comment]
I’ve found reasons to believe that memory leak in a code path in the reset/retry logic of the DownloadPipelineArtifact task caused the Out-Of-Memory exceptions. Details are in the IcM ticket #441856953 referenced.

But in summary, the primary reason is:

- All instances of OOM exceptions I looked at (7+) involve at least 1 reset/retry during the download. In the pipeline logs, a reset/retry shows up as download progress suddenly being reset to 0% as below:

```
Downloaded 1,605.9 MB out of 2,306.5 MB (70%).

DedupManifestArtifactClient will correlate http requests with X-TFS-Session 664c2a65-b0c9-4af2-9a6c-ae5a39edf84b

Minimatch patterns: [**,!**/*binlog,!**/*debug*/**/*]

Filtered 3453 files from the Minimatch filters supplied.

Downloaded 0.0 MB out of 2,306.5 MB (0%).
```

- While OOM exceptions imply resets/retries, not all resets/retries result in OOM exceptions.

- After a “good” reset, the available memory on the VM returns to about the same level when the download first started at 0%. So the download resumes cleanly.

- After a “bad” reset, the available memory on the VM does _not_ fully return to the level when the download first started at 0%. This is sign of a memory leak. If there are enough resets, enough memory would be leaked to trigger an OOM exception before download of the artifact can complete.

The secondary reason came from a download session of a 5.1 GB artifact which progressed from 0 to 82% on a test VM before hitting the first reset. Then a couple more resets were hit. In the last retry, when progress reached ~35%, a fatal OOM exception caused the download session to abort. Recall that the VM should have enough resources to download at least 82% of the artifact, the best explanation of hitting OOM exception later at a much lower ~35% is that in the handling of the resets memory was leaked.

IOW, so far the triggering condition for the OOM exception looks like: <Reset Happens> AND <Reset Leaks Memory> AND <VM has limited RAM>. That seems to fit all observed behavior of this issue:
•	Large artifacts are more likely to trigger OOM exceptions.
•	More RAM on a test VM means lower chance to hit the OOM exceptions.
•	Hits are intermittent, rerunning the failed job often helps.

**Comment by DHowett** [comment]
Unsurprising to find a "closed stale" version of a bug that was never fixed but is still hitting my pipelines in 2026.
