### ISSUE TITLE
[Question]: What is "Run From Zip" for Azure App Service Deploy?

### ISSUE THREAD

**Issue by mwiemer-microsoft** [microsoft/azure-pipelines-tasks#19334]
### Task name

AzureRmWebAppDeploymentV4

### Task version

4.229.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Question

In the [readme for AzureRmWebAppDeploymentV4](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4), "Run From Zip" is mentioned twice without context. Is this the same as "RunFromPackage"? I ask because we currently have an app service that is unexpectedly being deployed with WEBSITE_RUN_FROM_PACKAGE=1, but I'd like to confirm. Thanks. You can also ping me on Microsoft internal Teams at mwiemer :)

**Comment by alexangas** [comment]
Yes it's the same. Please see https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package
