### ISSUE TITLE
[BUG]: Publish artifact fails when retry failed job

### ISSUE THREAD

**Issue by goldsam** [microsoft/azure-pipelines-tasks#19348]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishPipelineArtifact (and its publish yaml alias)

### Task version

1

### Issue Description

There is no way to successfully  "re-run" a failed job which has already publish an artifact with a given name. The task provides no way to bypass, delete, or otherwise override the existing artifact. The behavior breaks the existing pipeline which has no way to recover and is clearly a bug.

The issue was already addressed in #12854, but you ignored the problem and dismissed the community's needs. Since you have a tendency to ignore issues you simply don't want to deal with or simply disagree with, I have reduced the problem to the terms above such that it is easier to understand.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

n/a

### Relevant log output

```shell
n/a
```

### Full task logs with system.debug enabled

-

### Repro steps

```yml
n/a
```

**Comment by goldsam** [comment]
Workaround in our flow sidesteps this issue

**Comment by ddjmos** [comment]
@goldsam What was the workaround?
