### ISSUE TITLE
[Question]:  Why can't KubernetesManifest@0 deploy to different namespaces?

### ISSUE THREAD

**Issue by AlHood77** [microsoft/azure-pipelines-tasks#19370]
### Task name

KubernetesManifest@0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

n/a

### Operation system

Ubuntu 22.04.3

### Question

```shell
This got brought up in #11785  but

Why does the KubernetesManifest@0 task not deploy manifests to multiple namespaces even when the namespaces are defined in the baked manifests? 

Take a simple task(s) where I'm using kustomize to bake 2 manifests which each have their respective namespace specified. (I've checked that manifests are being baked correctly with a separate task not shown)


steps:
  - task: KubernetesManifest@0
    name: bake
    displayName: Bake K8s manifest 
    inputs:
    action: 'bake'
    renderType: kustomize
    kustomizationPath: 'my/path'

  - task: KubernetesManifest@0
    displayName: Deploy K8s manifests 
    inputs:
      kubernetesServiceConnection: $(k8sServiceConnection)
      action: 'deploy'
      manifests: $(bake.manifestsBundle)
```

If I have 2 manifests with different namespaces it will generate this error:

```[error]the namespace from the provided object "my-namespace" does not match the namespace "default". You must pass '--namespace=my-namespace' to perform this operation.```

Shouldn't the behavior be that the manifest namespace overrides the default task namespace?

If I run ```kubectl apply -k <dir>``` it works with no problem. Why doesn't this task?
```

**Comment by victorgarcia04sap** [comment]
same issue here, it is constraining our deployment pipeline
