### ISSUE TITLE
AzureFunctionApp@0 runtimeStack should list NODE|18

### ISSUE THREAD

**Issue by steved0x** [microsoft/azure-pipelines-tasks#19394]
### Task name

AzureFunctionApp@0

### Describe your feature request here

A customer reported that the runtimeStack parameter should list NODE|18 since it is one of the supported languages for Azure Functions. https://github.com/MicrosoftDocs/azure-devops-yaml-schema/issues/266 

I am updating our docs with a comment to clarify that the drop-down list in the task assistant is a suggestion/convenience and any supported language can be manually entered. If NODE|18 is added to the options list for runtimeStack in AzureFunctionApp@1 it will automatically be reflected in the task reference.

**Comment by FinVamp1** [comment]
Thanks @steved0x this will be updated soon.

**Comment by FinVamp1** [comment]
This will be updated in the 237 version of the task.
