### ISSUE TITLE
[enhancement]: Please add support for AzureFunctionApp@2 to deploy .net 8 Isolated model

### ISSUE THREAD

**Issue by hyndakiel** [microsoft/azure-pipelines-tasks#19409]
### Describe your feature request here

Hello,
This is my first time creating a issue here on gihub so if I created in the wrong way please tell me.
Right now version 2 of AzureFunctionApp can only deploy up to .net 7 Isolated model, is there any idea when .net 8 will be supported?

Thank you for your time

**Comment by FinVamp1** [comment]
@hyndakiel Is this for deploying to a Linux Function App? If so I will be working on this and hope to have it out this month

**Comment by acha11** [comment]
Hi, @FinVamp1 any update on the ETA for this enhancement? That info would help us decide whether to temporarily apply manual changes to a couple of non-prod environments (if it's coming soon) or introduce azure CLI steps to our deployment as per @hyndakiel's solution above.

**Comment by FinVamp1** [comment]
Thanks, I'm also going to update the tool tip for this to indicate that this value is editable. So while DOTNET-ISOLATED|8.0 is not available yet you can just put it in right now and your app should deploy and work without any issues. @acha11 I was hoping to target this month but it will probably most likely be next month now.

**Comment by FinVamp1** [comment]
In the YAML It would look this this.

   runtimeStack: 'DOTNET-ISOLATED|8.0'
   
   Or in the assistant.
   
   
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/1410302/6610e849-0bb1-4e82-a7e7-31e1bbea31d7)

**Comment by ZarPeter** [comment]
Hey Thank you for your hard work!

I tried updating our AzureFunctions to dotnet8 using yaml, but the runtime is not updated..
This is the relevant YAML section.

 - task: AzureFunctionApp@2
    displayName: 'Deploy queue processor function'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      appType: 'functionAppLinux'
      appName: ${{ parameters.functionsAppName }}
      runtimeStack: 'DOTNET-ISOLATED|8.0'
      deployToSlotOrASE: true
      slotName: 'staging'
      package: '${{ parameters.artifactsDirectory }}/api/Auditing.Functions.zip'
      ResourceGroupName:  ${{ parameters.resourceGroupName }}

However in the deployment pipeline this is not reflected and the function runtime is not updated.
![grafik](https://github.com/microsoft/azure-pipelines-tasks/assets/70762731/da1a263a-c0ed-4f44-bba9-bb528f66d3ef)

Can you help me with this please somehow?

kind regards,

Zar

**Comment by fjbelizon** [comment]
@FinVamp1 When will this functionality be implemented? DOTNET-ISOLATED 8.0 is active as of November 2023. Thank you in advance.

**Comment by FinVamp1** [comment]
Hello, this will be released sopon in version 237 of the both v1 and v2 Task.

**Comment by pacorreia** [comment]
Hi @FinVamp1 

I saw this was released 4 hours ago, but how long until it's actually available for use?

For me I can't still set dotnet-isolated version 8 for linux  Function apps:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/54323159/6120683d-c617-4a97-bc31-74c06dc5822d)

**Comment by tomasr** [comment]
+1 from me.

Can't seem to get this to work at all. Publishing succeeds, but the `linuxFxVersion` of the function never gets updated and gets stuck in `DOTNET|6.0`
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/16179/4acf6115-d81b-4597-854d-e219c7ccd5ff)

And the portal UI shows the runtime stack in an unusable state:

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/16179/0d9d8d93-4400-4a11-87ea-9629da1ac414)

I have tried this in all possible combinations and I've just reached the conclusion this is completely broken. Obviously changing it from the UI fixes the broken function app, but that defeats the purpose of doing reliable upgrades through the DevOps pipeline.

**Comment by FinVamp1** [comment]
Hello, I filed an enhancement for this today https://github.com/microsoft/azure-pipelines-tasks/issues/19866 . We don't update the linuxfxversion but just the app settings. I'll check to see if we can add this functionality. The flow is that you have an existing .NET 6 app that you have rewritten in .NET 8 and you want to deploy and update the App Version as well as the code?

**Comment by tomasr** [comment]
@FinVamp1 That is correct, that's the scenario. Too bad it's not supported, since that makes setting the runtimeStack pretty useless on its own. At least now I know I'm not going crazy :)

**Comment by FinVamp1** [comment]
I'll discuss this internally and see what we can do.

**Comment by Saulopv** [comment]
@tomasr You are not crazy :) I did the same thing, spending a lot of hours trying to make it work
