### ISSUE TITLE
[REGRESSION]: Gradle V3 build task failure message reports "Code analysis failed" for all failures

### ISSUE THREAD

**Issue by bannus** [microsoft/azure-pipelines-tasks#19416]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Gradle

### Breaking task version

3.204.0

### Last working task version

3.200.0

### Regression Description

Any failing build reports "Code analysis failed". [PR 16078](https://github.com/microsoft/azure-pipelines-tasks/pull/16078) attempted to improve the task failure reporting, but as far as I can tell it did not add any new information to the failure, and confusingly reports that "Code analysis failed" even if the build failed for another reason.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Relevant log output

```shell
> Task :product:GradlePlugin:test FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':product:GradlePlugin:test'.
> There were failing tests. See the report at: file:///D:/a/_work/1/s/obj/AnyCPU/GradlePlugin/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 23m 11s


Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
940 actionable tasks: 940 executed
Error: The process 'D:\a\_work\1\s\_BuildCommon\path1st\gradlew.bat' failed with exit code 1
    at ExecState._setResult (D:\a\_work\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\3.231.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
    at ExecState.CheckComplete (D:\a\_work\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\3.231.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
    at ChildProcess.<anonymous> (D:\a\_work\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\3.231.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
##[error]Code analysis failed. Gradle exit code: -1. Error: Error: The process 'D:\a\_work\1\s\_BuildCommon\path1st\gradlew.bat' failed with exit code 1
```

### Full task logs with system.debug enabled

N/A

**Comment by kirill-ivlev** [comment]
Hi @bannus  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
