### ISSUE TITLE
[Question]: Templates are rendered in folded style instead of literal style

### ISSUE THREAD

**Issue by Borrelworst** [microsoft/azure-pipelines-tasks#19422]
### Task name

CmdLine@2, Bash@3, AzureCLI@1, AzureCLI@2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Question

We have multiple inline scripts in our pipelines. They all have this format (depends on the task):

```shell
- task: CmdLine@2, Bash@3, AzureCLI@1, AzureCLI@2
  displayName: 'My Script'
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      echo "Here starts my awesome code"
```
When I download a full YAML of the pipeline, I noticed that some task are rendered like this:
```
    script: |
      #!/bin/bash
```
But a lot of other tasks are rendered with a > sign (while we have a pipe | in the code):
```
    script: >
      #!/bin/bash
```
This makes the pipelines rendered very big with a lot of enters between the lines of code. How and why does this happen? When I use a | symbol, shouldn't it be rendered with a | as well, instead of a >?

**Comment by KonstantinTyukalov** [comment]
Hi @Borrelworst thanks for the reporting!
This repo is only for the issues related to the specific logic of tasks, your issue is about common Service behavior.
Please, raise your question on the [developer community](https://developercommunity.visualstudio.com/AzureDevOps) to get right eyes on it
