### ISSUE TITLE
[Question]: The output of AzureFileCopy@5 task was changed, cx would like to know which version did this change

### ISSUE THREAD

**Issue by jejass** [microsoft/azure-pipelines-tasks#19433]
### Task name

AzureFileCopy

### Task version

5

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Question

```shell
we have a yaml file use AzureFileCopy@5 task. then use the task's output StorageContainerUri and StorageContainerSasToken to next ARM template deploy task. In the ARM template, the output StorageContainerUri and StorageContainerSasToken will be used to construct url to access blobs (StorageContainerUri+StorageContainerSasToken). 

In the latest running, the ARM template task failed to access to blob due to shortage of '?' either in StorageContainerUri or StorageContainerSasToken. The constructed url is like below.

https://xx.blob.core.windows.net/xx/xx.jsonsv=2023-08-03&se=2024-01-08T07%3A13%3A55Z&sr=c&sp=rwdl&sig=***Sanitized Azure Storage Account Shared Access Signature

The correct one should be like below.
https://xx.blob.core.windows.net/xx/xx.json?sv=2023-08-03&se=2024-01-08T07%3A13%3A55Z&sr=c&sp=rwdl&sig=***Sanitized Azure Storage Account Shared Access Signature

The last successful run happened on 15th Nov, 2023 and it used below task version.

Task         : Azure file copy
Description  : Copy files to Azure Blob Storage or virtual machines
Version      : 5.230.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy

The failed run used below task version
Task         : Azure file copy
Description  : Copy files to Azure Blob Storage or virtual machines
Version      : 5.231.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy

It looks like the '?' mark was removed somewhere between this 2 version.

Please help to check which version did this change and whether the output StorageContainerSasToken without '?' mark is a permanent change.
```

**Comment by jejass** [comment]
I found that the task is using New-AzureStorageContainerSASToken to generate token. then https://www.powershellgallery.com/packages/Az.Storage/6.0.0, the '?' was removed from 6.0.0. 
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/32087564/6d928d9a-7252-4111-92ac-e18e610f5927)

please kindly help to check if that is the cause and confirm which Az.Storage version that current task is using.

**Comment by Simon-Gregory-LG** [comment]
Just adding that this problem has just started happening (on Friday 22 March 2024) with the `AzureFileCopy@4` task. The `?` prefix is missing from the `StorageContainerSasToken` output parameter and this is breaking all ARM templates.

Can anybody confirm that this is a bug that will be fixed? 

I can understand behaviour changing between versions, but something like this shouldn't just change for an existing version. I imagine this issue will have a very wide impact, as this task is usually used as the step before ARM Template execution to obtain the blob Sas Token - all of our ARM deployments are now completely broken.

**Comment by sloscialo** [comment]
> Just adding that this problem has just started happening (on Friday 22 March 2024) with the `AzureFileCopy@4` task. The `?` prefix is missing from the `StorageContainerSasToken` output parameter and this is breaking all ARM templates.
> 
> Can anybody confirm that this is a bug that will be fixed?
> 
> I can understand behaviour changing between versions, but something like this shouldn't just change for an existing version. I imagine this issue will have a very wide impact, as this task is usually used as the step before ARM Template execution to obtain the blob Sas Token - all of our ARM deployments are now completely broken.

Yep, just been hit with this. All our pipelines are now broken.

**Comment by Simon-Gregory-LG** [comment]
I have also [raised this as an issue in the Visual Studio Developer Community support page](https://developercommunity.visualstudio.com/t/AzureFileCopy-missing-first--characte/10622948?moreInfo=true&viewtype=all) as recommended by the documentation.

**Comment by sloscialo** [comment]
Adding
```
${{ if startsWith(variables['AzureFileCopy.StorageContainerSasToken'], '?') }}:
  SasToken: $(AzureFileCopy.StorageContainerSasToken)
${{ else }}:
  SasToken: "?$(AzureFileCopy.StorageContainerSasToken)"
```
seems like a bit of a hack, but we can't trust the values coming from the AzureFileCopy task anymore.
