### ISSUE TITLE
[BUG]: Legacy flag does not get passed through in opensslPkcsArgs argument of the InstallAppleCertificateV2 task

### ISSUE THREAD

**Issue by darijan-darijan** [microsoft/azure-pipelines-tasks#19436]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

InstallAppleCertificateV2

### Task version

2

### Issue Description

**_What did I do_**
passed the '-legacy' flag through the **opensslPkcsArgs**

**_What did I see_**

/usr/local/bin/openssl pkcs12 -in ... -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
Error outputting keys and certificates

The error that was already reported here 
https://github.com/microsoft/azure-pipelines-tasks/issues/18560

**_What did I expect to see_**

I expected to see the '-legacy' flag appended to the command, but looks like it does not get passed. Also I expected the command to be executed successfully on MacOS 13 with the '-legacy' flag

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

Agent version: 2.213.2

### Operation system

MacOS 13

### Relevant log output

```shell
/usr/local/bin/openssl pkcs12 -in ... -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
Error outputting keys and certificates
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- task: InstallAppleCertificate@2
     inputs:
        certSecureFile: '$(certFileName)'
        certPwd: '$(P12password)'
        keychain: 'temp'
        opensslPkcsArgs: '-legacy'
```

**Comment by darijan-darijan** [comment]
Can someone help please ?
You have added the -legacy flag and the **opensslPkcsArgs** argument but you didnt say anything about where is it available ?

Do I need to update the Azure Devops version ?

My current version is Version Azure DevOps Server 2022 (AzureDevOpsServer_20221122.1)

Is it tied to the version, or the agent version ? What is it tied to ?

Which Azure Devops version has this argument available
opensslPkcsArgs

**Comment by darijan-darijan** [comment]
<img width="809" alt="Screenshot 2024-01-12 at 3 22 41 PM" src="https://github.com/microsoft/azure-pipelines-tasks/assets/155693958/099652ed-228a-4052-a9b8-f4fb33a964a3">

I am suspecting it is related to the version of the InstallAppleCertifificate@2 Task.

My current version is 2.200.0

Could you please let me know if this is the reason i cannot use the **opensslPkcsArgs** parameter ?

**Comment by KonstantinTyukalov** [comment]
Hi @darijan-darijan, `opensslPkcsArgs` parameter was introduced in v2.225.0
Could you try updating the task to this or a newer version?

**Comment by gucoelho** [comment]
Hi guys, same thing is happening to me:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/13936778/4db80a8a-6c54-4791-a938-e1a6bdaa2ead)

I'm using a Microsoft hosted agent macos-latest

**Comment by darijan-darijan** [comment]
> Hi guys, same thing is happening to me: ![image](https://private-user-images.githubusercontent.com/13936778/297267698-4db80a8a-6c54-4791-a938-e1a6bdaa2ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzY3ODEsIm5iZiI6MTcwNTQ3NjQ4MSwicGF0aCI6Ii8xMzkzNjc3OC8yOTcyNjc2OTgtNGRiODBhOGEtNmM1NC00NzkxLWE5MzgtZTFhNmJkYWEyZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjdhZDI3YTIzZjc1ZDMwYjNmYzExMjdkZjMyMDExNjQ3M2NhMjFhZDAzYTkyYzAzZjJlM2Q0YmY0ZjA1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fwT9sI2NCrPaVZZLHW8f6HfvY-QJxy69xxXAA6A6JBM)
> 
> I'm using a Microsoft hosted agent macos-latest

not the same thing. If you look closely your legacy flag is getting passed
check this issue , it might help
https://github.com/microsoft/azure-pipelines-tasks/issues/19383

@gucoelho

**Comment by KonstantinTyukalov** [comment]
Hello @darijan-darijan, I was wondering if you’ve had a chance to update the task and make sure the issue has been resolved for you? Thank you.

**Comment by darijan-darijan** [comment]
if anyone experiences this issue in the future , make sure that your version of InstallAppleTaskCertificate@2 is up to date. You can find the current version in the pipeline log.

And as for the development team, please next time you change a feature, dont simply say "we have added the flag"
You need to specify the exact version of the task as the version system in Azure devops is quite finnicky.

You have the task @version (eg. @2, @3, @4)
You have the numerical task version (the one in the pipeline log eg. 2.231.1)
You have the agent version
The Azure devops platform version
The runner image version

There are so many versions, its super finnicky, so please be more verbose and descriptive moving forward.

Closing this task, thank you!
