### ISSUE TITLE
[enhancement]: NuGetCommand to take extra arguments when command == restore

### ISSUE THREAD

**Issue by javiergcrb** [microsoft/azure-pipelines-tasks#19500]
### Task name

NuGetCommandV2

### Describe your feature request here

Arguments parameter in NuGetCommand task isn't used when the command is "restore", and it would be helpful to be able to add additional arguments to any of the NuGet commands.

I couldn't use -MSBuildVersion from NuGet CLI to restore packages using "restore" in the command parameter of the task

**Comment by jmyersmsft** [comment]
The `NuGetCommand` task is [no longer taking new features](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines#remarks). We reccomend using the `NuGetAuthenticate@1` task and a script (`script`, `powershell`, etc.) task to run nuget.exe itself with whatever parameters you desire. If the image you're using does not have nuget.exe in the path, you can use the `NuGetToolInstaller@1` task to install it.
