### ISSUE TITLE
[enhancement]: When will net8 be available in Azure?

### ISSUE THREAD

**Issue by rwb196884** [microsoft/azure-pipelines-tasks#19526]
### Task name

Azure App Service deploy

### Describe your feature request here

MS keep pestering about updating to net8.0 but this isn't an option for deployment.

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/12090617/103b63c8-4f39-45ae-b4cd-8e59cdc0cc4b)

Any idea if/when net8 might be available in Azure?

**Comment by ratherbeoutdoors** [comment]
I was able to manually manipulate that value and set it to 8 - saw another post saying that's supposed to work.  It will allow you to do it and it does deploy to the app service.  However - I've found that the .NET Stack and version in the app service actually gets cleared out, causing my app to fail.  I'm having to go back into the azure portal and set the .NET Version post deployment to get it to work.  Hoping this gets resolved soon.
