### ISSUE TITLE
[Question]: Is it better to use a task for this

### ISSUE THREAD

**Issue by craftzneko** [microsoft/azure-pipelines-tasks#19544]
### Task name

?

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

?

### Question

```shell
I have a pipeline that runs this script in ubuntu image

PullRequests=$(curl -u ":$PersonalAccessToken" $dev)

I have confirmed all the variables are correct and are in the script but it always returns {"error":{"code":"AuthorizationFailed","message":"The authentication credentials are not valid."}}

If i run this same command on a local ubuntu rather than in the pipeline it works. I am so fed up trying to figure out this issue now. So my question, is there a task that can make API calls to dev ops api and be a better option than this.

Cheers
```

**Comment by aleksandrlevochkin** [comment]
Hi @craftzneko thanks for your question. How do you set your variables? If you set secret variables in the pipeline editor's UI then you also need to map them to environment variables. The following example works for me:
```yaml
- script: | 
    PullRequests=$(curl -u :$Pat $Url)
  env: 
    Url: $(dev)
    Pat: $(PersonalAccessToken)
```

**Comment by craftzneko** [comment]
thanks @aleksandrlevochkin, they are not secret and I have echo'd them back so I know they are being read correctly, figured out it was a copy error in my url somehow a 2nd ? was added to the variable in dev ops, where's as locally it wasn't
