### ISSUE TITLE
[enhancement]: AzureFunctionApp task should validate appType against the existing function and enforce WEBSITE_RUN_FROM_PACKAGE settings accordingly

### ISSUE THREAD

**Issue by domasd** [microsoft/azure-pipelines-tasks#19571]
### Task name

AzureFunctionApp@2

### Describe your feature request here

# Issue Description
The current implementation of the AzureFunctionApp task does not validate the `appType` (Linux or Windows) against the existing function, leading to potential silent issues when deploying functions with `WEBSITE_RUN_FROM_PACKAGE` settings. This can result in unexpected behavior, particularly when the `WEBSITE_RUN_FROM_PACKAGE` value is set to a URL.

# Issue Context

- When `WEBSITE_RUN_FROM_PACKAGE` is set to a URL and the function app is on Windows, it may lead to trigger issues, causing the function to be unresponsive to requests without raising any exceptions.
- On Windows, the correct setting for `WEBSITE_RUN_FROM_PACKAGE` should be 1. However, if the appType is mistakenly selected as `functionAppLinux`, it can result in a frozen state without triggering, even when there are incoming requests.

# Documentation Reference
[WEBSITE_RUN_FROM_PACKAGE Documentation](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#considerations-for-deploying-from-a-url)

# Expected Behavior
The expected behavior is that if the task is used with `appType: 'functionAppLinux'` for a function on Windows, the task should fail and not proceed. This validation ensures that the deployment settings align with the platform requirements, preventing potential silent issues.

**Comment by FinVamp1** [comment]
Hello, thanks for the issue. Let me investigate and see if we can add additional information.

**Comment by domasd** [comment]
@FinVamp1 was it adressed?

**Comment by domasd** [comment]
@FinVamp1 any update?
