### ISSUE TITLE
[enhancement]: Allow for Java 17 runtime version on AzureSpringCloudV0

### ISSUE THREAD

**Issue by vermegi** [microsoft/azure-pipelines-tasks#19583]
### Task name

AzureSpringCloudV0

### Describe your feature request here

Currently this task only allows for picking Java 8 or 11, even though Java 17 is also supported on Azure Spring Apps as a runtime version. Allow for Java 17 as a runtime version.
```[tasklist]
### Tasks
```

**Comment by holyhoehle** [comment]
I'd even extend this request to Java 21.

Azure Spring Apps supports Java 21 now, but the AzureSpringCloudV0 task throws the following error:
"Invalid arguments: properties.source.runtimeVersion with value Java_21 is not supported for type Jar"

As for Java 17: I think its not documented, but if you just try with `RuntimeVersion: Java_17` it should work.

**Comment by qianz2** [comment]
@vermegi Thanks for reporting this! We're working on making java runtime 17 and 21 available for AzureSpringCloudV0 task.
