### ISSUE TITLE
[enhancement]: don't pass --progress to git fetch

### ISSUE THREAD

**Issue by Trass3r** [microsoft/azure-pipelines-tasks#19615]
### Task name

checkout

### Describe your feature request here

The typical git commandline that gets run in the checkout step is: `git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1`
This just clutters the logs with lots of `Receiving objects:` and `Resolving deltas:` lines.
I don't see any reason at all to include `--progress` here. But at least make it optional like they finally did in https://github.com/actions/checkout?tab=readme-ov-file#usage

**Comment by DmitriiBobreshev** [comment]
Hi @Trass3r, thank you for the suggestion! 
The checkout task is a part of [the agent](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/RepositoryPlugin.cs#L108), and can't be modified from this repo, could you please create a new issue in the agent's [repository](https://github.com/microsoft/azure-pipelines-agent)?

I'm closing this issue as the task is not a part of the repo.
