### ISSUE TITLE
[BUG]: Always 0% count while uploading artifact

### ISSUE THREAD

**Issue by djonik1562** [microsoft/azure-pipelines-tasks#19635]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishPipelineArtifactV1

### Task version

1.151.1

### Issue Description

I have always 0% count while uploading to the server artifact. 
I want to upload the .ipa file from MacOS Ventura (13.6.5) after dotnet build completed. The file is 30mb.

On my Windows agents everything works OK.

May be I need to update the task on the server? Is it safe?

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2019.1.2 patch 7

### Operation system

Windows Server 2012 R2

### Relevant log output

```shell
Always 0% while upload artifact to the server
Общий файл: 1 ---- Обработанный файл: 0 (0%)

In the log file of agent Worker this record every 2-4 seconds:
[2024-03-14 12:48:51Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'cb89b927-9286-503e-4ba6-8e8de18269c8', success rate: 1/1.
```

### Full task logs with system.debug enabled

<details>
  <pre> [debug]Evaluating condition for step: 'Опубликовать артефакт: drop'
[debug]Evaluating: succeeded()
[debug]Evaluating succeeded:
[debug]=> True
[debug]Result: True
[section]******************************************************************************
[section]Запуск: Опубликовать артефакт: drop
[section]******************************************************************************
==============================================================================
Task         : Публикация артефактов сборки
Description  : Публикация артефактов сборки в Azure Pipelines или общей папке
Version      : 1.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
[debug]Using node path: /Users/djonik1562/myagent/externals/node/bin/node
[debug]agent.workFolder=/Users/djonik1562/myagent/_work
[debug]loading inputs and endpoints
[debug]loading INPUT_PATHTOPUBLISH
[debug]loading INPUT_ARTIFACTNAME
[debug]loading INPUT_ARTIFACTTYPE
[debug]loading INPUT_PARALLEL
[debug]loading INPUT_PARALLELCOUNT
[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
[debug]loaded 8
[debug]check path : /Users/djonik1562/myagent/_work/_tasks/PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe/1.151.1/task.json
[debug]set resource file to: /Users/djonik1562/myagent/_work/_tasks/PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe/1.151.1/task.json
[debug]system.culture=ru-RU
[debug]PathtoPublish=/Users/djonik1562/myagent/_work/2/a
[debug]check path : /Users/djonik1562/myagent/_work/2/a
[debug]ArtifactName=drop
[debug]ArtifactType=Container
[debug]system.hostType=build
[debug]Upload artifact: /Users/djonik1562/myagent/_work/2/a to server for build: 10393 at backend.
[debug]Processed: ##vso[artifact.upload artifacttype=container;artifactname=drop;containerfolder=drop;localpath=/Users/djonik1562/myagent/_work/2/a;]/Users/djonik1562/myagent/_work/2/a
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8512) Warning: Use Cipheriv for counter mode of aes-256-ctr
[section]******************************************************************************
[section]Async Command Start: Отправка артефакта
[section]******************************************************************************
Отправка файлов 1
[debug]Ресурсы среды агента — Диск: / — доступно 13170,00 МБ из 112439,00 МБ, Память: использовано 2200,00 МБ из 6143,00 МБ, Использование ЦП: 69,07 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13170,00 МБ из 112439,00 МБ, Память: использовано 2202,00 МБ из 6143,00 МБ, Использование ЦП: 39,92 %
[debug]Ресурсы среды агента — Диск: / — доступно 13170,00 МБ из 112439,00 МБ, Память: использовано 2196,00 МБ из 6143,00 МБ, Использование ЦП: 27,97 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2194,00 МБ из 6143,00 МБ, Использование ЦП: 21,67 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2181,00 МБ из 6143,00 МБ, Использование ЦП: 17,74 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2172,00 МБ из 6143,00 МБ, Использование ЦП: 15,07 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2170,00 МБ из 6143,00 МБ, Использование ЦП: 13,10 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2170,00 МБ из 6143,00 МБ, Использование ЦП: 11,74 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 10,59 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 9,66 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2153,00 МБ из 6143,00 МБ, Использование ЦП: 8,88 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2155,00 МБ из 6143,00 МБ, Использование ЦП: 8,21 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 7,64 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 7,15 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 6,75 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 6,39 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2154,00 МБ из 6143,00 МБ, Использование ЦП: 6,06 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2156,00 МБ из 6143,00 МБ, Использование ЦП: 5,77 %
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2155,00 МБ из 6143,00 МБ, Использование ЦП: 5,50 %
Общий файл: 1 ---- Обработанный файл: 0 (0%)
[debug]Ресурсы среды агента — Диск: / — доступно 13165,00 МБ из 112439,00 МБ, Память: использовано 2155,00 МБ из 6143,00 МБ, Использование ЦП: 5,26 % </pre>
</details>

### Repro steps

```yml
#My yaml of the task
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Опубликовать артефакт: drop'
```
![2024-03-14_15-55-35](https://github.com/microsoft/azure-pipelines-tasks/assets/29034883/8c2cd04a-97db-4ec1-8d38-69210f6d6b1a)

**Comment by nycnewman** [comment]
Seeing a similar issue on MacOS 13. What was the resolution?

**Comment by djonik1562** [comment]
> Seeing a similar issue on MacOS 13. What was the resolution?

Hi.
I found out the solution from [here](https://communities.vmware.com/t5/VMware-Fusion-Discussions/how-do-i-disable-lro-and-tso-on-mac-osx/td-p/1420789)
