### ISSUE TITLE
[Question]: Use Workload Identity federation identity in maven task

### ISSUE THREAD

**Issue by sonwan2020** [microsoft/azure-pipelines-tasks#19649]
### Task name

Maven

### Task version

3

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Question

```shell
I am running auto test pipelines like https://msazure.visualstudio.com/AzureDMSS/_build?definitionId=150216, and I want to implement secret-less pipelines using service connection.

When I create service connection type "Service Principal" and input the id & secret to build the service connection, from this doc https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines, I can get the servicePrincipalId & servicePrincipalKey & tenantId, and my later maven task can use these variables.

When I create service connection with workload identity federation, when I check the environment varaibles, the variable servicePrincipalKey is empty and alternatively I get a idToken.
My question is, how can I use servicePrincipalId & idToken & tenantId variables in my java code?

I tried some *CredentialBuilder, the WorkloadIdentityCredentialBuilder() need a tokenFilePath, where can I get that?
`new WorkloadIdentityCredentialBuilder().tokenFilePath().build()`

Any other suggestions?
```

**Comment by jiec-msft** [comment]
I also similar questions:
1. Reading from this "custom-azure-tasks-and-extensions" section in [doc](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/#custom-azure-tasks-and-extensions), is there SDK in languages like Java that do the `IDToken` acquisition, redeem AAD token and access azure resource?
2. And for the `IDToken` acquisition [doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/oidctoken/create?view=azure-devops-rest-7.1), is the `accessToken` still needed in the request to get `IDToken`?

**Comment by KonstantinTyukalov** [comment]
Hi @sonwan2020, you can use idToken to get access token for azure resources you need.
Please check [this blog post section](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/#custom-azure-tasks-and-extensions#custom-azure-tasks-and-extensions).

Hi @jiec-msft, I'm not aware of official Java SDK for such purposes. Here is the of official REST ADO clients: https://learn.microsoft.com/rest/api/azure/devops#client-libraries
> And for the IDToken acquisition [doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/oidctoken/create?view=azure-devops-rest-7.1), is the accessToken still needed in the request to get IDToken?

Yes, you'll need accessToken to be able to reach the required endpoint.
Reference: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/oidctoken/create#security
