### ISSUE TITLE
[Question]: VSTest@2 and VSTest@3 are not working within Azure DevOps anymore

### ISSUE THREAD

**Issue by thomastrinamix** [microsoft/azure-pipelines-tasks#19644]
### Task name

VSTest2

### Task version

2.235.3

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 2022

### Question

```shell
dear community,
since the update from 2.253.2 to 2.235.3 on Wednesday 13. March 2024 our test pipeline fails in azure devops:
'##[error]VsTest task failed.'

found this PR
https://github.com/microsoft/azure-pipelines-tasks/pull/19617
saying there is an update from 2.253.2 to 2.236.0, however when using '-task: VSTest@2.236.0' I can't run the pipeline 'A task is missing. The pipeline references a task called 'VSTest'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace:
https://marketplace.visualstudio.com.
(Task version 2.236.0, job 'testAndBuild4appService', step ''.)'

Also tried
'- task: VSTest@2.235.1'
'- task: VSTest@2.235.2'
'- task: VSTest@3'
always got
'##[error]VsTest task failed.'
```

**Comment by qianz2** [comment]
Hi @thomastrinamix, could you try again with '- task: VSTest@2.236.1'?

**Comment by thomastrinamix** [comment]
> Hi @thomastrinamix, could you try again with '- task: VSTest@2.236.1'?


```
Encountered error(s) while parsing pipeline YAML:
A task is missing. The pipeline references a task called 'VSTest'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2.236.1, job 'testAndBuild4appService', step ''.)
```

**Comment by thomastrinamix** [comment]
ok. it looks like this was more an Azure DevOps bug... you can close this one here.

just recreated the pipeline with exactly the same yml, branch and `- task: VSTest@2` 
It uses 'Version : 2.235.3' and everything works as it did in the past

Old pipeline with reference to **exactly** same yml and branch still results in '##[error]VsTest task failed.'

**---> Solutions (Azure DevOps)**: create a new pipeline with the same yml
