### ISSUE TITLE
[BUG]: PublishTestResults@2 task is skipped if tests in preceding task fail

### ISSUE THREAD

**Issue by vanastassiou** [microsoft/azure-pipelines-tasks#19660]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishTestResults@2

### Task version

2.236.0

### Issue Description

When I run unit tests in a `script` pipeline task (Bash) using `mvn clean verify ${pom_file}`, the `PublishTestResults@2` task that immediately follows is executed as expected. However, if the unit tests fail, `PublishTestResults@2` is skipped. This behaviour is not noted in [the task documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml) (or if it is, I haven't been able to find it).

Adding `condition: succeededOrFailed()` for this task results in the behaviour I initially expected: when tests fail, `PublishTestResults@2` runs successfully and a report is published in the Tests tab of the pipeline run.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

RHEL 8 agent

### Relevant log output

```shell
No error -- the task is skipped altogether.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by msound** [comment]
I ran into this problem today. The previous step, `pytest` in my case, reported 2 failed tests and exited with non-zero status code. So the next step `PublishTestResults@2`, based on the assumed `condition: succeeded()` did not run. The only log entry is `Skipping step due to condition evaluation.`.

At minimum, the documentation for PublishTestResults@2 must make this clear. The example on the documentation page must have `condition: succeededOrFailed()` added to it, and this behavior must be explicitly called out in the page.

**Comment by james-langbein** [comment]
I had the same situation as @msound mentioned above. The docs should mention using `condition: succeededOrFailed()`.

**Comment by bryanbcook** [comment]
I don't understand why you would think this is a problem with PublishTestResults@2 or why the documentation should mention succeededOrFailed.

If you have a preceding step in your pipeline that fails, your pipeline fails. That's how pipelines work.

**Comment by vanastassiou** [comment]
@bryanbcook the task's job is to publish test results. The problem as described in the issue is that the task is skipped altogether if tests fail. That is not desired or expected behaviour.

I hope this clarifies understanding.

**Comment by bryanbcook** [comment]
I understand perfectly.

What you're missing is a fundamental understanding of how pipelines work. The task's job is not to ensure that the preceding steps pass. The task is a generic component to publish results. How those results are produced can be accomplished in many different ways and is your problem.
