### ISSUE TITLE
[Question]: Download of tasks being blocked by AV due to "potentially_malicious.zip"

### ISSUE THREAD

**Issue by DuelMonster** [microsoft/azure-pipelines-tasks#19695]
### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server

### Question

Upon initialising a deployment of our web app to a production server, we are getting blocked by our clients AV 
when the pipeline agent attempts to download the pipeline tasks due to an included "potentially_malicious.zip" 
getting flagged as a potential [ZipSlip attack](https://security.snyk.io/research/zip-slip-vulnerability).

So far I have seen this in two different task downloads:  FileTransform and IISWebAppDeploymentOnMachineGroup

Looking over the source I see that the only reference to this zip file is in a unit test for L1ZipUtility: [Here](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/55e49ed1e06f4752c5cc36158171a88bdea893fc/common-npm-packages/webdeployment-common/Tests/L1ZipUtility.ts#L8)

Is there a reason why this file is being included in the released packages?
If not, would it not be best to remove the file prior to release?

I am currently working with our client to see about by-passing the ZipSlip check for their production server, but 
obviously this is far from ideal.  Anything you can do to help would be greatly appreciated.

---
Andy

**Comment by DuelMonster** [comment]
Can anybody help me with this??
I have a client that needs a release and I am being chased for a resolution.

**Comment by DuelMonster** [comment]
Having raised a support ticket with Microsoft I now have this issue resolved.

For anyone who may arrive here after searching for a solution to the same or similar problem:
We resolved this by removing the existing agent:
1. Open administrative powershell
2. Change to the existing agent folder: Default = `C:\azagent\A1`
3. Execute: `.\config remove`
4. Delete the A1 folder and all contents
5. Recreate agent

**Comment by schneebuzz** [comment]
I appreciate you posting your resolution as I am facing a similar issue. Could you point out why recreating the agent resolves this? Did the mentioned L1ZipUtility get updated with your proposed changes?
