### ISSUE TITLE
[Question]: PackerBuild@1 support of identity federation

### ISSUE THREAD

**Issue by kiote** [microsoft/azure-pipelines-tasks#19693]
### Task name

PackerBuild

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

all

### Question

```shell
Current documentation https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/packer-build-v1?view=azure-pipelines says: "Note This task does not support Azure Resource Manager authentication with workflow identity federation."

Are there any plans to add this support any time soon? We are using PackerBuild in our pipelines and switching to workflow identity federation broke them.
```

**Comment by v-schhabra** [comment]
https://github.com/microsoft/azure-pipelines-tasks/commit/8947d18848e520e7c706f965418c1fa439932c45#diff-129710f4fe945bd58fc37e31b68d45a35aeb0df84a56a5f7ebdad97454ccbe22
