### ISSUE TITLE
[BUG]: HelmDeploy@0 Task Getting Occasional Timeout's Downloading Kube config from AKS Cluster

### ISSUE THREAD

**Issue by Chris-Greaves** [microsoft/azure-pipelines-tasks#19716]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

HelmDeploy

### Task version

0.231.0

### Issue Description

The Helm task sometimes hit's a timeout when downloading the Kube config, causing the pipeline to fail. This has been happening on and off for the last 2 weeks.

Other checks I've done:

- Can happen to any of our clusters (we have 4 clusters, 2 in dev and 2 in prod and it's happened to 3 of those 4)
- Has happened on different Agents 
- The config is downloaded each time, which has lead to cases where it worked once and then immediately failed afterwards. For example, we do a dry run upgrade first, then a proper upgrade if that succeeds. We've had it where the dry run succeeds but then the proper upgrade fails to pull the config.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu-latest

### Relevant log output

```shell
##[error]Error: Cannot download access profile/kube config file for the cluster prod-aks-weu. Reason Request timeout: /subscriptions/REDACTED/resourceGroups/prod-aks-weu/providers/Microsoft.ContainerService/managedClusters/prod-aks-weu/accessProfiles/clusterAdmin?api-version=2017-08-31.
```

### Full task logs with system.debug enabled

<details>
  <pre>2024-04-03T10:21:08.7428681Z ##[section]Starting: helm chart dry run (West Europe)
2024-04-03T10:21:08.7435567Z ==============================================================================
2024-04-03T10:21:08.7435726Z Task         : Package and deploy Helm charts
2024-04-03T10:21:08.7435825Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2024-04-03T10:21:08.7436021Z Version      : 0.231.0
2024-04-03T10:21:08.7436098Z Author       : Microsoft Corporation
2024-04-03T10:21:08.7436203Z Help         : https://aka.ms/azpipes-helm-tsg
2024-04-03T10:21:08.7436299Z ==============================================================================
2024-04-03T10:21:14.7288723Z ##[error]Error: Cannot download access profile/kube config file for the cluster prod-aks-weu. Reason Request timeout: /subscriptions/REDACTED/resourceGroups/prod-aks-weu/providers/Microsoft.ContainerService/managedClusters/prod-aks-weu/accessProfiles/clusterAdmin?api-version=2017-08-31.
2024-04-03T10:21:14.7396370Z ##[section]Finishing: helm chart dry run (West Europe)</pre>
</details>

**Comment by sivetic** [comment]
@Chris-Greaves We have a similar issue and have a case escalated with Microsoft.  Can you try using ubuntu-20 agents, in our testing that seems to have resolved the issue.  It seems to have suddenly started with ubuntu-22 v20240310 agents, though details have yet to be confirmed.

**Comment by sivetic** [comment]
A bit more troubleshooting from my end here.  It turns out that there was two relevant updates done March 14th - was the agent image update, the other is an update to a number of azure-pipeline tasks.
 
If I use Kubernetes@1.227.0 task in combination with Ubuntu-22, I cannot reproduce the failure after 10 attempts.  If I use Kubernetes@1 (version 1.231.1, i.e. latest), I was able to reproduce the failure on third try.  Same comment as before - failures are not present when using ubuntu-20 image.  Reading through release notes, it seems Kube and other tasks were updated to Node 20.

**Comment by StephanZaat** [comment]
We are having the same issue with self-hosted agents with both the Helm and Kubernetes task.
Running Ubuntu 22.04 and the latest version of the Agent.

Hopefully this will be solved soon. I will also create a ticket with Microsoft Support and update here if anything changes.

**Comment by Chris-Greaves** [comment]
So today I noticed that the task only took 6 seconds to fail with the reason "timeout" which seemed unusually short.
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/28542943/b2ca9a2c-93a6-411b-ba85-0eb77cba13db)

So I started looking through the code and found the function to get the KubeConfig.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/clusters/armkubernetescluster.ts

I noticed that the error message string wasn't referenced here, so must have come from the `aks.getAccessProfile` call on line 15. I couldn't find that code anywhere on Github, so had to install the package locally and view the code in `node_modules`.

Full code for the AzureAksService can be found below:
<details>
    <pre>"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AzureAksService = void 0;
const tl = require("azure-pipelines-task-lib/task");
const webClient = require("./webClient");
const path = require("path");
const AzureServiceClient_1 = require("./AzureServiceClient");
const AzureServiceClientBase_1 = require("./AzureServiceClientBase");
tl.setResourcePath(path.join(__dirname, 'module.json'), true);
class AzureAksService {
    constructor(endpoint) {
        this._client = new AzureServiceClient_1.ServiceClient(endpoint.applicationTokenCredentials, endpoint.subscriptionID, 30);
    }
    beginRequest(uri, parameters) {
        var webRequest = new webClient.WebRequest();
        webRequest.method = 'GET';
        webRequest.uri = this._client.getRequestUri(uri, parameters, null, '2017-08-31');
        return this._client.beginRequestExpBackoff(webRequest, 3).then((response) => {
            if (response.statusCode >= 200 && response.statusCode < 300) {
                return response;
            }
            else {
                throw AzureServiceClientBase_1.ToError(response);
            }
        });
    }
    getAccessProfile(resourceGroup, clusterName, useClusterAdmin) {
        var accessProfileName = !!useClusterAdmin ? 'clusterAdmin' : 'clusterUser';
        return this.beginRequest(`//subscriptions/{subscriptionId}/resourceGroups/{ResourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{ClusterName}/accessProfiles/{AccessProfileName}`, {
            '{ResourceGroupName}': resourceGroup,
            '{ClusterName}': clusterName,
            '{AccessProfileName}': accessProfileName
        }).then((response) => {
            return response.body;
        }, (reason) => {
            throw Error(tl.loc('CantDownloadAccessProfile', clusterName, this._client.getFormattedError(reason)));
        });
    }
}
exports.AzureAksService = AzureAksService;</pre>
</details>

The line of interest is line 12 where is sets the Timeout to be 30 seconds (There is no docs, but I think it's a safe assumption to say it's seconds)
```
this._client = new AzureServiceClient_1.ServiceClient(endpoint.applicationTokenCredentials, endpoint.subscriptionID, 30);
```

Originally, I thought this could be fixed by just extending the timeout, but instead it looks like something else is happening in the code that is causing a premature timeout to be triggered.

**Comment by Chris-Greaves** [comment]
> Same comment as before - failures are not present when using ubuntu-20 image. Reading through release notes, it seems Kube and other tasks were updated to Node 20.

I am going to try rolling back the tasks tomorrow as quite a lot of long running pipelines failed today because of this issue. I will report back my findings, but will keep this issue open until the code itself is fixed for Node 20.

**Comment by sivetic** [comment]
> It seems that I am not getting the error anymore. I have not made any changes on my side.

I noticed a similar pattern, 3/4 of the runs in the last 36-48hrs were successful.  It seems the calls to ARM/AKS still take 5s randomly, but the task no longer times out.  So as best as I can tell, the underlying issue isn't touched but the failing behaviour is corrected.

**Comment by sivetic** [comment]
@StephanZaat Can you re-test again?  5s timeouts are back in my environment once again.  No progress with support yet unfortunately.

**Comment by StephanZaat** [comment]
@sivetic The issue did not come back for us.
