### ISSUE TITLE
[BUG]: Copy files task fails with ##[error]Error: Failed find: EPERM: operation not permitted, stat  'C:\azagent\A4\_work\1\test_artifact\bin\6ce49f25-2433-40fa-b5f1-8d06dab0566f.tmp'

### ISSUE THREAD

**Issue by dontforgeturmail** [microsoft/azure-pipelines-tasks#19739]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Copy files

### Task version

2.231.1

### Issue Description

We are creating .net artifact using microsoft hosted agent and using the self hosted agent, downloading the artifact and copying the artifact to another folder in the self hosted agent. In the artifact there is one bin folder, when the pipeline tries to copy the files it ends with the below error. 
Copy files task fails with ##[error]Error: Failed find: EPERM: operation not permitted, stat  'C:\azagent\A4\_work\1\test_artifact\bin\6ce49f25-2433-40fa-b5f1-8d06dab0566f.tmp'

I checked in the artifact and in the folder also, there is no tmp file, I even checked via Powershell and view hidden file, still there is no file named that

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows server 2019 server

### Relevant log output

```shell
##[error]Error: Failed find: EPERM: operation not permitted, stat 'C:\azagent\A4\_work\1\test\bin\6ce49f25-2433-40fa-b5f1-8d06dab0566f.tmp'
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by dontforgeturmail** [comment]
If I use PowerShell task to copy the files and in if specify exclude tmp files then its able to copy.

**Comment by johanlab** [comment]
Getting the exact same error on the tmp file when trying to copy files - not even zipped. 
Same environment as you

**Comment by yuriykuts** [comment]
Encountered the same problem on multiple self-hosted agents; only a restart of the VM helped.
Problem with the File Transform task:

2024-04-24T06:39:11.7333700Z ==============================================================================
2024-04-24T06:39:11.7333953Z Task         : File transform
2024-04-24T06:39:11.7334066Z Description  : Replace tokens with variable values in XML or JSON configuration files
2024-04-24T06:39:11.7334286Z Version      : 1.235.1
2024-04-24T06:39:11.7334398Z Author       : Microsoft Corporation
2024-04-24T06:39:11.7334501Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/file-transform
2024-04-24T06:39:11.7334681Z ==============================================================================
2024-04-24T06:39:12.4559841Z Applying JSON variable substitution for **/appsettings.json
2024-04-24T06:39:12.9015137Z ##[error]Error: Failed find: EPERM: operation not permitted, stat 'C:\agent\_work\r9\a\build_api\Jobs\App_Data\jobs

**Comment by dontforgeturmail** [comment]
Since copy files in powershell task worked for me, closing this issue.

**Comment by ajeckmans** [comment]
@dontforgeturmail why did you close this issue? It is still present. Great you found a workaround, but it still needs fixing. See also #19933
