### ISSUE TITLE
[BUG]: UsePythonVersion intermittently fails because sw_ver fails with dyld[6863]: terminating because inserted dylib '�6' could not be loaded

### ISSUE THREAD

**Issue by githubursul** [microsoft/azure-pipelines-tasks#19751]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UsePythonVersionV0

### Task version

0.235.1

### Issue Description

>50% of the time our pipelines running on Apple images fail with the following error:

Unhandled: Command failed: sw_vers -productVersion dyld[6863]: terminating because inserted dylib '�6' could not be loaded: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file) dyld[6863]: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)

There are no published artifacts for any pipeline failing due to this error.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

macOS 13.6.6 22G630

### Relevant log output

```shell
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
==============================================================================
dyld[6863]: terminating because inserted dylib '�6' could not be loaded: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)
dyld[6863]: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)
##[error]Unhandled: Command failed: sw_vers -productVersion
dyld[6863]: terminating because inserted dylib '�6' could not be loaded: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)
dyld[6863]: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)

##[error]Error: Command failed: sw_vers -productVersion
dyld[6863]: terminating because inserted dylib '�6' could not be loaded: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)
dyld[6863]: tried: '�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS�6' (no such file), '�6' (no such file), '/Users/runner/work/1/s/�6' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/1/s/�6' (no such file), '/Users/runner/work/1/s/�6' (no such file)

    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at Object._getOsVersion (/Users/runner/work/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.235.1/osutil.js:14:22)
    at Object.<anonymous> (/Users/runner/work/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.235.1/installpythonversion.js:21:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
Finishing: Use Python 3.x
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
[agent_initialization.txt](https://github.com/microsoft/azure-pipelines-tasks/files/14908854/agent_initialization.txt)

**Comment by ismayilov-ismayil** [comment]
Hi @githubursul, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
