### ISSUE TITLE
[Question]: Pipeline don't use correct version

### ISSUE THREAD

**Issue by likyd** [microsoft/azure-pipelines-tasks#19817]
### Task name

CopyFileHoverSSH

### Task version

0.236.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Red hat

### Question

```shell
The latest version of CopyFileHoverSSH is version 0.237, but when I run my pipeline, the job (in the pipeline) uses version 0.231.1.

I checked in the tasks directory (_work/_tasks), and version 0.236.1 exists.

I have also tried specifying the full version in my task, but it still uses version 0.231.1.

steps:
  - task: CopyFilesOverSSH@0.236.1
    displayName: 'Copy artefact (${{ parameters.serverName }})'
    inputs:
      sshEndpoint: ${{ parameters.serviceConnection }}
      sourceFolder: '$(Agent.BuildDirectory)/'
      contents: '**/${{ parameters.applicationName }}*.${{ parameters.artefactExtension }}'
      targetFolder: '$(artefacts.applicationUploadDirectory)'
      flattenFolders: true

May I kindly ask you to advice?

Kind regards
```

**Comment by aleksandrlevochkin** [comment]
Hi @likyd, thank you for reporting. The minimum supported version of the agent has been bumped recently for this task: https://github.com/microsoft/azure-pipelines-tasks/pull/19643
Could you please check if your agent meets this condition?

**Comment by likyd** [comment]
Hello, thank for your response.

Yes, if I'm not mistaken, we are in  3.227.2 version as we can see in the printscreen

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/48834801/916d3402-9750-4b9c-ae21-c6e747e3b144)

**Comment by likyd** [comment]
@aleksandrlevochkin , we are curently in  3.227.2 version.

We also tested with a fresh installation of an agent (3.228.0) on another machine and the problem persists. The task is still in version 0.231.1
