### ISSUE TITLE
[Question]: Azure File Copy V6 is not generating SASToken

### ISSUE THREAD

**Issue by Veera-kambham** [microsoft/azure-pipelines-tasks#19838]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Azure File Copy

### Breaking task version

6.0

### Last working task version

3.0

### Regression Description

We copied the files to storage account using Azure File Copy V6. However it is not generating SASToken.
We need to use this SASToken in the subsequent tasks.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022

### Relevant log output

```shell
The output variable is not generating the SAS Token and we cannot use it in the subsequent tasks
```

**Comment by v-snalawade** [comment]
@Veera-kambham - AzureFileCopyV6 is no longer supporting SASToken, please refer https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-file-copy-v6?view=azure-pipelines

Use V5 to work with SASToken.

**Comment by Veera-kambham** [comment]
V5 doesn’t support for Federated Identity. Hence we have to use V6.
Please reopen the issue

**Comment by v-snalawade** [comment]
@geekzter - Hi, Can you update on V6 and SASToken removal

**Comment by geekzter** [comment]
@Veera-kambham  V6 of the task discourages the use of secrets and encourages the use of Azure RBAC, and therefore no longer generates & uses SAS tokens.
If you need a SAS token in a pipeline, you can create one in the [AzureCLI@2](https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines) task with `az storage account generate-sas` or the [AzurePowerShell@5](https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) task with `New-AzStorageContainerSASToken`.

**Comment by DaleyKD** [comment]
Please update your readme, then. Cause the V6 readme still indicates that the SAS token is part of the output parameters.

**Comment by DaleyKD** [comment]
I'll try to bump this again to see if there's ANY consideration.

Azure DevOps wants us to upgrade our Service Connections to WIF. To use WIF, we need to upgrade AzureFileCopy@5 to @6. However, when we do that, we no longer can use a SAS token, which is **required** by the CSES deployment.

Y'all have put us in a pickle.

**Comment by DaleyKD** [comment]
@v-schhabra - My apologies. I've had to type it so often at our company that we abbreviated it.

**CSES** - Cloud Services (Extended Support)
