### ISSUE TITLE
[enhancement]: Change DotNetCoreCLI verbosityRestore defaultValue to Normal

### ISSUE THREAD

**Issue by cremor** [microsoft/azure-pipelines-tasks#19848]
### Task name

DotNetCoreCLI

### Describe your feature request here

See #12297 which raised the same request but was auto-closed.
There was even PR #12298 for it but it was also auto-closed.

You might also want to change `verbosityPack` for the same reason.

**Comment by ivanduplenskikh** [comment]
I've recreated a [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/19850)
