### ISSUE TITLE
[BUG]: DockerInstaller@0 keeps getting intermittent certificate error

### ISSUE THREAD

**Issue by GavinToddlds** [microsoft/azure-pipelines-tasks#19854]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DockerInstaller

### Task version

0.238.1

### Issue Description

Intermittently we are seeing the error `unable to get local issuer certificate` when attempting to download the docker cli. Running the task again generally fixes it but it seems to be happening more frequently then previously

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

n/a

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
Because it is intermittent it is hard to get debug logs but i will try

Downloading: https://download.docker.com/linux/static/stable/x86_64/docker-26.1.1.tgz
##[error]Error: Failed to download Docker from location https://download.docker.com/linux/static/stable/x86_64/docker-26.1.1.tgz. Error Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
```
```


### Full task logs with system.debug enabled

<details>
  <pre> Downloading: https://download.docker.com/linux/static/stable/x86_64/docker-26.1.1.tgz
##[error]Error: Failed to download Docker from location https://download.docker.com/linux/static/stable/x86_64/docker-26.1.1.tgz. Error Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
</pre>
</details>


### Repro steps

```yml
# can use any version i've seen it happen on 26.1.1 25.0.5 and a 17.x.x version
  - task: DockerInstaller@0
    displayName: Install Docker
    inputs:
      dockerVersion: 26.1.1
```

**Comment by b0bu** [comment]
I have this with githubcomment@0 even when `AGENT_CAINFO` is set in env to the task.

**Comment by GavinToddlds** [comment]
We ended up finding an issue with cisco umbrella that was causing our intermittent failure. This has been resolved for me. @b0bu i'm going to close the issue if you want to reopen one with more info for you case.

**Comment by b0bu** [comment]
I literally just messaged to fix it but thanks for the update, glad yours is resolved. For me adding:

`NODE_EXTRA_CA_CERTS: path/to/certs. crt`

Has worked
