### ISSUE TITLE
[Question]: when task: AzureCLI@2 has version 2.60.0 by default?

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/azure-pipelines-tasks#19851]
### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows

### Question

```shell
when task: AzureCLI@2 has version 2.60.0 by default will be release? it contains an important fix for us
```

**Comment by LiliDeng** [comment]
anyone?

**Comment by v-bsanthanak** [comment]
@LiliDeng MS hosted agents always have the latest azureCLI. please share the task configuration.

**Comment by LiliDeng** [comment]
now I see it uses the latest version 2.60.0, thanks.
