### ISSUE TITLE
[Question]: Issue with the Federate Credential login on Azure Cli task

### ISSUE THREAD

**Issue by jasidhu** [microsoft/azure-pipelines-tasks#19878]
### Task name

Azure CLI

### Task version

2.239.3

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Windows

### Question

```shell
We are getting following error when trying to run az login using the service principal and Federate Credential.

[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** --tenant {OurTenantId} --allow-no-subscriptions --federated-token ***"

2024-05-15T20:47:16.2950443Z Error: Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
2024-05-15T20:47:16.2950869Z 
2024-05-15T20:47:16.2951508Z To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
2024-05-15T20:47:16.2952047Z auth method - instructions for which can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
2024-05-15T20:47:16.2952264Z 
2024-05-15T20:47:16.2952449Z Alternatively you can authenticate using the Azure CLI by using a User Account.

Can you please provide some guidance how to resolve this issue?
```

**Comment by v-bsanthanak** [comment]
@jasidhu Please share the complete debug logs for further investigation.

**Comment by jasidhu** [comment]
@v-bsanthanak I have attached the log file.
[tasklog_28.log](https://github.com/microsoft/azure-pipelines-tasks/files/15338462/tasklog_28.log)

**Comment by v-bsanthanak** [comment]
@jasidhu Attached logs are not the debug logs. Please set system.debug - true and share the complete logs.

**Comment by jasidhu** [comment]
@v-bsanthanak Attaching the debug logs.

[tasklog.log](https://github.com/microsoft/azure-pipelines-tasks/files/15354731/tasklog.log)
> @jasidhu Attached logs are not the debug logs. Please set system.debug - true and share the complete logs.

**Comment by v-schhabra** [comment]
@jasidhu We are checking on the issue above and will share the updates soon.

**Comment by v-schhabra** [comment]
Hi @jasidhu 
Could you please update if you are still having the issues or not?

**Comment by v-schhabra** [comment]
Hi @jasidhu 
Please let us know if the issue is still occurring or not?

**Comment by jasidhu** [comment]
> Hi [@jasidhu](https://github.com/jasidhu) Please let us know if the issue is still occurring or not?

Please close this issue. It is resolved now.
