### ISSUE TITLE
[BUG]: AzurePowerShell@5 is failing to find parameter FederatedToken

### ISSUE THREAD

**Issue by cskaggs-ms** [microsoft/azure-pipelines-tasks#19874]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzurePowerShell@5

### Task version

2.6.0

### Background 
- Using the task AzurePowerShell@5
- azureSubscription is set to a service connection authenticating using a federated credential

### Expected Behavior
- The AzurePowerShell@5 task successfully authenticates

### Actual Behavior
- The AzurePowerShell@5 task runs `Connect-AzAccount` to authenticate
-   `Connect-AzAccount` fails with the following error: ` A parameter cannot be found that matches parameter name 'FederatedToken'.`
- This should be a supported parameter from this document: https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-11.6.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

msazure.visualstudio.com

### Operation system

Windows 11

### Relevant log output

```shell
##[debug]Connect-AzAccount: D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.239.9\ps_modules\VstsAzureHelpers_\InitializeAzModuleFunctions.ps1:438
##[debug]Line |
##[debug] 438 |              & $command @args
##[debug]     |                         ~~~~~
##[debug]     | A parameter cannot be found that matches parameter name 'FederatedToken'.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
Use AzurePowerShell@5 in 2.6.0 with a service connection authenticating using a federated credential
```

**Comment by v-bsanthanak** [comment]
@cskaggs-ms  - Please share the complete debug logs to proceed with investigation.
