### ISSUE TITLE
Could not find the module Az.Accounts with given version. If the module was recently installed, retry after restarting the Azure Pipelines task 

### ISSUE THREAD

**Issue by yoda96** [microsoft/azure-pipelines-tasks#19898]
### Task name

AzurePowerShell@5

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Windows11

### Question

```shell
I am using below task in azure devops pipeline:
- task: AzurePowerShell@5
                      displayName: Helm deploy
                      inputs:
                        azureSubscription: ${{parameters.serviceConnection}}
                        TargetAzurePs: LatestVersion
                        azurePowerShellVersion: LatestVersion
                        ScriptType: FilePath
                        ScriptPath:
While executing the pipeline throws following error:
Exception: /azp/_work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/4.239.7/InitializeAz.ps1:38
Line |
  38 |      throw ("Could not find the module Az.Accounts with given version. …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find the module Az.Accounts with given version. If the module
     | was recently installed, retry after restarting the Azure Pipelines task
     | agent.
```

**Comment by v-schhabra** [comment]
@yoda96 Could you please install Az.Accounts module in your machine in which agent is running and if Az.Accounts module is already installed then please try restarting your machine and check if that works fine.
And share the debug logs of the pipeline by adding system.debug to "true".

**Comment by v-schhabra** [comment]
@yoda96 can you post your latest updates here?

**Comment by v-schhabra** [comment]
Hi @yoda96 
Please share the latest updates?
