### ISSUE TITLE
[REGRESSION]: AzureFileCopy@6 failing to load Az.Accounts v3.0.0 module

### ISSUE THREAD

**Issue by MSylvia** [microsoft/azure-pipelines-tasks#19910]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFileCopy

### Breaking task version

6.240.1

### Last working task version

6.239.x

### Regression Description

We have a pipeline that is using `AzureFileCopy@6` with a managed identity. It has been in place for about 2 weeks and has been running without issue. On Tuesday the task started failing with the only visible change in the logs being the `Az.Accounts` module updating from `v2.9.1` to `v3.0.0`.

When it fails, we get this error:
```
Failed to perform Auto-login: PSContextCredentialGet-AzAccessToken: -REDACTED- 'Get-AzAccessToken' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.
```

In failed runs the listed `Az.Accounts` module version is always `v3.0.0`.  

```
Imported module 'Az.Accounts', version: 3.0.0
```

Runs that executed earlier which passed have a version of `v2.9.1`.

```
Imported module 'Az.Accounts', version: 2.9.1
```

Cross contamination of jobs is not possible because a fresh machine with the exact same configuration is used for each run and that configuration has not changed.

I believe it may have been caused by this change from `AzureRM` to `Az`: https://github.com/microsoft/azure-pipelines-tasks/commit/f5b22d9c64118dc809b217a09e4e5d8599939429

Example runs:

Pass: `v2.9.1`
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9600629&view=logs&j=4736f78b-748e-51a8-c3dc-ea7706a06c3d&t=f124d820-a316-55db-635e-ba56d272505a
Fail: `v3.0.0`
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9613411&view=logs&j=4736f78b-748e-51a8-c3dc-ea7706a06c3d&t=f124d820-a316-55db-635e-ba56d272505a

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11

### Relevant log output

```shell
Starting: Upload to Storage
==============================================================================
Task         : Azure file copy
Description  : Copy files to Azure Blob Storage or virtual machines
Version      : 6.240.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy
==============================================================================
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\3.0.0\Az.Accounts.psd1 -Global -PassThru -Force
##[warning]Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide
Imported module 'Az.Accounts', version: 3.0.0
Update-AzConfig -DisplayBreakingChangeWarning False -AppliesTo Az
Enable-AzureRmAlias -Scope Process
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Resources\1.13.0\Az.Resources.psd1 -Global -PassThru -Force
Imported module 'Az.Resources', version: 1.13.0
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Storage\1.14.0\Az.Storage.psd1 -Global -PassThru -Force
Imported module 'Az.Storage', version: 1.14.0
Uninstall-AzureRm
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Clear-AzContext -Scope Process
Connect-AzAccount 

......

Failed to perform Auto-login: PSContextCredentialGet-AzAccessToken: -REDACTED- 'Get-AzAccessToken' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.
```

### Full task logs with system.debug enabled

We don't have full task logs with system.debug enabled.

### Repro steps

```yml
- task: AzureFileCopy@6
  displayName: 'Azure File Copy'
  inputs:
    SourcePath: '${{ parameters.BuildPackages }}'
    azureSubscription: ${{ parameters.AzureSubscription }}
    Destination: AzureBlob
    storage: ${{ parameters.AzureStorage }}
    ContainerName: ${{ parameters.AzureContainerName }}
    BlobPrefix: ${{ parameters.AzureUploadLocation }}
  condition: ${{ parameters.condition }}
```

**Comment by v-snalawade** [comment]
@MSylvia - Could you please run the pipeline with debug log enabled and share the logs.

**Comment by v-snalawade** [comment]
@MSylvia  - I dont see debug logs enabled, please add variable system.debug to true and run pipeline again.

**Comment by MSylvia** [comment]
@v-snalawade 
Here is a new run with debug logs enabled: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9655994&view=logs&j=664d18a4-0bff-549b-3c61-59bf14bbc55e&t=ef0776a8-add3-5b3a-2eb0-f7eb5d3be34c

I launched them both, but the other is having an unrelated issue, will update this when it finally completes.

**Comment by v-snalawade** [comment]
@MSylvia - 
I went through logs and these are not debug logs. 
please add variable system.debug to true in pipeline variables and run pipeline again, you will get the detailed logs.

**Comment by MSylvia** [comment]
@v-snalawade Here is a new run with debug logs actually enabled this time. I mistakenly thought that enabling diagnostics also set debug to true before.

With warning (Both Az and AzureRM on machine):
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9668885&view=logs&j=664d18a4-0bff-549b-3c61-59bf14bbc55e&t=ef0776a8-add3-5b3a-2eb0-f7eb5d3be34c

Without warning (Only Az):
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9668884&view=logs&j=664d18a4-0bff-549b-3c61-59bf14bbc55e&t=ef0776a8-add3-5b3a-2eb0-f7eb5d3be34c

**Comment by jonathanjyi** [comment]
I'm running into the same issue:
Breaking task version
6.240.1
Last working task version
6.239.x

**Comment by jonathanjyi** [comment]
Debug Logs here:
https://dev.azure.com/mseng/VS%20IDE%20-%20Telemetry/_build/results?buildId=28468351&view=logs&j=a5781d42-2f3f-596b-1540-70f475b4668a&t=62431333-4809-58f9-64bf-05d4a003a852&l=1

**Comment by MSylvia** [comment]
@DmitriiBobreshev I see you made some changes recently to the Azure File Copy tasks. Do you know what might cause the issues we are seeing?

**Comment by v-snalawade** [comment]
> Debug Logs here: https://dev.azure.com/mseng/VS%20IDE%20-%20Telemetry/_build/results?buildId=28468351&view=logs&j=a5781d42-2f3f-596b-1540-70f475b4668a&t=62431333-4809-58f9-64bf-05d4a003a852&l=1

Thanks for the logs, will check and keep you posted on updates

**Comment by jonathanjyi** [comment]
Thanks, are there any workarounds we can employ in the meantime?

**Comment by DmitriiBobreshev** [comment]
Hi @MSylvia, @jonathanjyi, Most probably the changes not causing the issue as the changes FF for AzureRM migration were ON for a while for both organizations. 
I see that both pools are using the same image and suspect that there is some inconsistency between PowerShell where the modules are enabling and pwsh which is used for [Get-AzAccessToken](https://github.com/Azure/azure-storage-azcopy/blob/main/common/azure_ps_context_credential.go#L125C10-L125C27) CmdLet inside AzCopy.exe. 
Moreover, the other CmdLets as [Connect-AzAccount](https://dev.azure.com/mseng/VS%20IDE%20-%20Telemetry/_build/results?buildId=28468351&view=logs&j=a5781d42-2f3f-596b-1540-70f475b4668a&t=62431333-4809-58f9-64bf-05d4a003a852&l=2936) or [Set-AzContext](https://dev.azure.com/mseng/VS%20IDE%20-%20Telemetry/_build/results?buildId=28468351&view=logs&j=a5781d42-2f3f-596b-1540-70f475b4668a&t=62431333-4809-58f9-64bf-05d4a003a852&l=2957)(both provided by Az.Accounts) succeeded, which tells us that the module was loaded correctly for PowerShell session but probably wasn't loaded for pwsh.
Is it possible to try another a pool with different image to check will it works for you?

**Comment by MSylvia** [comment]
@DmitriiBobreshev While switching pools / images worked for @jonathanjyi there still may be a problem because that pool is loading the **older** version of `Az.Accounts`.
```
Imported module 'Az.Accounts', version: 2.19.0
```
https://dev.azure.com/mseng/VS%20IDE%20-%20Telemetry/_build/results?buildId=28477100&view=logs&j=a5781d42-2f3f-596b-1540-70f475b4668a&t=62431333-4809-58f9-64bf-05d4a003a852&l=92

If/when that pool updates it could still be a problem.

**Comment by DevTestUser123** [comment]
Hi all any update on this? getting same issue

**Comment by v-schhabra** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/20117

**Comment by v-schhabra** [comment]
#20079 This is the fix created for the above issue. Will update here once the fixes are deployed to all the rings.

**Comment by v-schhabra** [comment]
Fix is deployed to all the rings with task version 6.242.2. Could you all please check and update if you are still facing the issues?
@MSylvia @jonathanjyi @DevTestUser123
