### ISSUE TITLE
[BUG]: AzureFileCopy@6 reports success although it actually fails

### ISSUE THREAD

**Issue by juliusl** [microsoft/azure-pipelines-tasks#19961]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFileCopy

### Task version

6.240.8

### Issue Description

```log
2024-06-06T23:41:38.2938122Z Final Job Status: Cancelled
2024-06-06T23:41:38.2938326Z 
2024-06-06T23:41:38.3089851Z Uploaded files successfully from source path:
```

Task shows up as a green check mark in ado

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Relevant log output

```shell
2024-06-06T23:41:38.2938122Z Final Job Status: Cancelled
2024-06-06T23:41:38.2938326Z 
2024-06-06T23:41:38.3089851Z Uploaded files successfully from source path:
```

### Full task logs with system.debug enabled

not relevant

**Comment by juliusl** [comment]
This is non-blocking, the underlying issue was easy to fix just reporting to help out

**Comment by v-schhabra** [comment]
@juliusl Could you please share us the detail logs of the pipeline by adding variable system.debug to "true"

**Comment by juliusl** [comment]
@v-schhabra sorry I can't - but the underlying issue was that I needed to add additional roles to my service account
