### ISSUE TITLE
[BUG]: can't run with task `AzureCLI@2`

### ISSUE THREAD

**Issue by ozbillwang** [microsoft/azure-pipelines-tasks#19985]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureCLI@2

### Task version

2

### Issue Description

This task works fine last month. But when today I run a pipeline with it, I got error

Use the sample code from the official document https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines#examples
```
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: <Name of the Azure Resource Manager service connection>
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
```

i got the error
<img width="1184" alt="image" src="https://github.com/microsoft/azure-pipelines-tasks/assets/8954908/a8e3424b-ebd2-49c1-9e46-3e9967bf4f3d">

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu 18.04

### Relevant log output

```shell
Starting: Azure CLI
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.241.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/agent/externals/node20_1/bin/node -v
/agent/externals/node20_1/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /agent/externals/node20_1/bin/node)
##[error]Azure CLI 2.x is not installed on this machine.
##[error]Script failed with error: Error: Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object._which [as which] (/agent/_work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.241.0/node_modules/azure-pipelines-task-lib/internal.js:348:23)
    at WindowsPowerShell.<anonymous> (/agent/_work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.241.0/src/ScriptType.js:55:35)
    at Generator.next (<anonymous>)
    at fulfilled (/agent/_work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.241.0/src/ScriptType.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Finishing: Azure CLI
```
```


### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>


### Repro steps

_No response_

**Comment by v-schhabra** [comment]
Hi @ozbillwang 
Could you please change the script type from PowerShell to PowerShell Core as PowerShell script doesnt work with Linux agents.
Please refer the doc for more info: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines&viewFallbackFrom=azure-devops#task-inputs

**Comment by ozbillwang** [comment]
Same issue. 

Currently I run a test. 

with Microsoft managed agent (default agent pool), it works fine. I check its ubuntu release, it is 22.04. The task `AzureCLI@2` works fine directly

mine is private agent pool, built on ubuntu 18.04 and the task is failed recently. 

I am going to upgrade the private agent poool to 22.04, and will update the result

**Comment by v-schhabra** [comment]
@ozbillwang Could you please update if your task works fine after upgrading the agent (ubuntu) version to 22.04?

**Comment by v-schhabra** [comment]
@ozbillwang Please share the latest updates?

**Comment by ozbillwang** [comment]
> @ozbillwang Please share the latest updates?

No difference. 

Finally, I figured it out. The `AzureCLI@2` task doesn't handle the installation of the Azure CLI. It assumes that the Azure CLI is already installed.

After adding a new task (show code below) before it, the AzureCLI@2 task runs fine now.

                - task: Bash@3
                  displayName: InstallAzureCLI
                  inputs:
                    targetType: "inline"
                    script: |
                      sudo apt-get -y install build-essential
                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                      az --version

**Comment by ozbillwang** [comment]
my recommend is to update the related document https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines and mention azure cli should be already installed on the devops agent.

**Comment by v-schhabra** [comment]
Hi @ozbillwang 
Please check this doc, here it is mentioned to install Azure CLI on the self hosted agent machine.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCLIV2/Readme.md
