### ISSUE TITLE
[BUG]:  Azure File Copy Task (Version 6) is breaking on pipeline using Self hosted agent with error 'The term 'azcopy' is not recognized.

### ISSUE THREAD

**Issue by Varaprasad91** [microsoft/azure-pipelines-tasks#20003]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Azure file copy

### Task version

 6.241.0

### Issue Description

We recently upgraded the Azure DevOps (ADO) service connection from using an Azure Resource Manager service principal (automatic) to Azure Resource Manager using Workload Identity federation with OpenID Connect (automatic). But, we got an issue with Azure file copy task (Task version 6) when running it on pipeline with self-hosted agent. The error message received was: 'The term 'azcopy' is not recognized as the name of a cmdlet, function, script file, or operable program. Please check the spelling of the name, or verify that the path is correct and try again.' Also, the task works correctly when using an Azure agent, but fails on the self-hosted agent.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows 

### Relevant log output

```shell
[debug]Script stack trace:
[debug]at ThrowError, C:\Agent\vsts-agent-win-x64-2.182.1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.241.0\Utility.ps1: line 121
[debug]at Upload-FilesToAzureContainer, C:\Agent\vsts-agent-win-x64-2.182.1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.241.0\Utility.ps1: line 272
[debug]at <ScriptBlock>, C:\Agent\vsts-agent-win-x64-2.182.1\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\6.241.0\AzureFileCopy.ps1: line 181
[debug]at <ScriptBlock>, <No file>: line 1
[debug]at <ScriptBlock>, <No file>: line 22
[debug]at <ScriptBlock>, <No file>: line 18
[debug]at <ScriptBlock>, <No file>: line 1
[debug]Exception:
System.Management.Automation.RuntimeException: Upload to container: 'sitemap-generator' in storage account: 'sitemapextractor' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.' For more info please refer to https://aka.ms/azurefilecopyreadme
2024-06-13T07:48:44.0282744Z ##[error]Upload to container: 'sitemap-generator' in storage account: 'sitemapextractor' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.' For more info please refer to https://aka.ms/azurefilecopyreadme
[debug]Processed: ##vso[task.logissue type=error;source=TaskInternal]Upload to container: 'sitemap-generator' in storage account: 'sitemapextractor' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.' For more info please refer to https://aka.ms/azurefilecopyreadme
[debug]Processed: ##vso[task.complete result=Failed]
[section]Finishing: AzureBlob File Copy
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

```[tasklist]
### Tasks
```

**Comment by v-schhabra** [comment]
Hi @Varaprasad91 
Could you please share us the complete logs of the pipeline by adding variable system.debug to "true".

**Comment by Varaprasad91** [comment]
[error logs1.txt](https://github.com/user-attachments/files/15827591/error.logs1.txt)

**Comment by v-schhabra** [comment]
Hi @Varaprasad91 
Thanks for sharing the logs. I hope @v-snalawade already connected with you reg this issue and she has started investigation.

**Comment by tomaeda** [comment]
Hi, @v-schhabra 
I'm having trouble with the same issue. Are there any updates?
Auto-login appears to fail because azcopy.exe isn't available for the oauth token task has retrieved, even though task has running Connect-AzAccount.
Same issue as #19910 ?

**Comment by v-schhabra** [comment]
> Hi, @v-snalawade I'm having trouble with the same issue. Are there any updates? Auto-login appears to fail because azcopy.exe isn't available for the oauth token task has retrieved, even though task has running Connect-AzAccount. Same issue as #19910 ?

We are already investigating on this issue. Will share the latest updates here.

**Comment by v-snalawade** [comment]
@tomaeda - Can you check if this [suggestion](https://github.com/microsoft/azure-pipelines-tasks/issues/19910#issuecomment-2149958912)  resolves the issue

**Comment by tomaeda** [comment]
Thank you for your response.

@v-schhabra 
I'm sorry, the logs I'm seeing are provided by the end user. I can't share it here.
I haven't been able to reproduce this issue, so I don't have my own logs.
However, the information from line 5599 onwards in the error.logs1.txt shared by Varaprasad91 is consistent with the logs I am seeing, except for specific information such as the storage account name.

@v-snalawade 
End user can work around the issue with a different pool.
The issue only occurs with the Self-hosted agent pool, not with MS-hosted pool. 
But end user wants to use Self-hosted, so I'd like to know how to resolve the inconsistency between powershell and pwsh. (If this is same issue)

**Comment by v-schhabra** [comment]
> Thank you for your response.
> 
> @v-schhabra I'm sorry, the logs I'm seeing are provided by the end user. I can't share it here. I haven't been able to reproduce this issue, so I don't have my own logs. However, the information from line 5599 onwards in the error.logs1.txt shared by Varaprasad91 is consistent with the logs I am seeing, except for specific information such as the storage account name.
> 
> @v-snalawade End user can work around the issue with a different pool. The issue only occurs with the Self-hosted agent pool, not with MS-hosted pool. But end user wants to use Self-hosted, so I'd like to know how to resolve the inconsistency between powershell and pwsh. (If this is same issue)

If it is fine for you please share the logs at v-schhabra@microsoft.com

**Comment by v-schhabra** [comment]
#20117 
Did fixes for the above issue. Will update here once it is deployed to all the cx.
