### ISSUE TITLE
[REGRESSION]: Secrets cannot contain multiple lines npmAuthenticate

### ISSUE THREAD

**Issue by GSFZamai** [microsoft/azure-pipelines-tasks#20049]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

npmAuthenticate

### Breaking task version

0.241.1

### Last working task version

0.238.3

### Regression Description

A regression happened!

Yesterday I tryied to run my pipeline and this task failed:
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/47357785/74e3ba2e-08bb-43f9-80a0-c2378732c44a)

After some research I've found this issue on StackOverflow reporting the same problem and one user suggested that this new version was released.
So I tryied to downgrande the version and the task worked:

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/47357785/9cff2c1b-6aac-4dea-afc0-7ae39a94cdc4)

[StackOverflow Reference](https://stackoverflow.com/questions/78648914/errorerror-secrets-cannot-contain-multiple-lines-task-npmauthenticate0/78652257#78652257)

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

macOS-latest

### Relevant log output

```shell
Starting: npmAuthenticate
==============================================================================
Task         : npm authenticate (for task runners)
Description  : Don't use this task if you're also using the npm task. Provides npm credentials to an .npmrc file in your repository for the scope of the build. This enables npm task runners like gulp and Grunt to authenticate with private registries.
Version      : 0.241.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm-authenticate
==============================================================================
Adding authentication to the .npmrc file at /Users/runner/work/1/s/.npmrc
Adding credentials for the pkgs.dev.azure.com service connection
##[error]Error: Secrets cannot contain multiple lines
Finishing: npmAuthenticate
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by matt-vanderkolk** [comment]
I have a repro of this issue internally as well. Feel free to reach out.

**Comment by Lorondos** [comment]
We had this issue as well on our pipelines, we have implemented the hard coded previous version to fix our pipelines for now, but I figure the next step is to make our secrets valid by removing anything that flags as multiline?

**Comment by GSFZamai** [comment]
I don't know. I'm using the Npm Service connection with Personal Access Tokan (PAT) wich is a single line already...
Looks like is some internal change on the commit they added a validation to match new lines caracters.

Added setSecret:
![Sem título](https://github.com/microsoft/azure-pipelines-tasks/assets/47357785/c39430f2-ac81-45b3-a6fd-75bd3ecf07c2)

setSecret Implementation:
![ahá](https://github.com/microsoft/azure-pipelines-tasks/assets/47357785/1aa91586-abad-4432-aae5-491058e5707a)


Maybe, in my case, the Npm Service connection is generating something with new lines characters...

**Comment by KnightCrawler3** [comment]
Facing the same issue with 0.241.1

**Comment by Nathanvdk** [comment]
We have the same problem since yesterday in our build pipelines.

**Comment by MelvinVermeer** [comment]
Facing the same issue

**Comment by alexander-miszko** [comment]
Facing the same issue with 0.241.0, downgrading the version fixes it.

**Comment by Srokap** [comment]
I did some digging and it seems that `registry.auth` will always be a multiline string because it is made into such format [here](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/66ff442a810d171d36cb49f9c62df1bedc59df19/common-npm-packages/packaging-common/npm/npmregistry.ts#L59).

See how `auth` value is built (`lineEnd` is `os.EOL`):
```js
        switch (endpointAuth.scheme) {
            case 'UsernamePassword':
                username = endpointAuth.parameters['username'];
                password = endpointAuth.parameters['password'];
                email = username; // npm needs an email to be set in order to publish, this is ignored on npmjs
                password64 = Buffer.from(password).toString('base64');

                auth = nerfed + ':username=' + username + lineEnd;
                auth += nerfed + ':_password=' + password64 + lineEnd;
                auth += nerfed + ':email=' + email + lineEnd;
                break;
            case 'Token':
                const apitoken = endpointAuth.parameters['apitoken'];
                tl.setSecret(apitoken);
                if (!isVstsTokenAuth){
                    // Use Bearer auth as it was intended.
                    auth = nerfed + ':_authToken=' + apitoken + lineEnd;
                } else {
                    // Azure DevOps does not support PATs+Bearer only JWTs+Bearer
                    email = 'VssEmail';
                    username = 'VssToken';
                    password64 = Buffer.from(apitoken).toString('base64');

                    auth = nerfed + ':username=' + username + lineEnd;
                    auth += nerfed + ':_password=' + password64 + lineEnd;
                    auth += nerfed + ':email=' + email + lineEnd;
                }
                break;
        }
        tl.setSecret(password);
        tl.setSecret(password64);
```

As mentioned above, the bug was introduced in this PR https://github.com/microsoft/azure-pipelines-tasks/pull/19995/files

**Comment by Srokap** [comment]
FYI @tintse-thxsky-MSFT @embetten

**Comment by tintse-thxsky-MSFT** [comment]
ack, looking into it.  Thank you for everyone's input.

**Comment by killerrin** [comment]
This issue has suddenly resurrected on our pipelines as well. Although in my case I'm already using the `npmAuthenticate@0` task, so unfortunately I don't have any work arounds here :/

**Comment by killerrin** [comment]
@Srokap That did it, Thanks!

**Comment by janharders** [comment]
> @killerrin Temporary workaround would be to use
> 
> ```yaml
> - task: npmAuthenticate@0.238.2
> ```
> 
> in your pipeline, though in my case I have a lot of pipelines to update :)

@Srokap: Do you know if there is any option to specifiy the _exact_ task version in a classic release pipeline (no YAML)? 
Thx in advance!

**Comment by Srokap** [comment]
@janharders Unfortunately I don't know of a way.

Your best bet might be trying to set `SYSTEM_UNSAFEALLOWMULTILINESECRET` environment variable to `TRUE` to bypass the multiline error, but it might cause unexpected behavior. I think it might "only" risk leaking your creds to stdout.

Have a look here, how it's implemented: https://github.com/microsoft/azure-pipelines-task-lib/blob/7c0de0dba61afb899068c35d88257017bd3b4736/node/task.ts#L241

**Comment by tintse-thxsky-MSFT** [comment]
update: rollback to previous task version should is ongoing.

**Comment by mpm-os** [comment]
Hi! Is the revert complete?

**Comment by janharders** [comment]
> Hi! Is the revert complete?

Guess yes. Our pipelines are up and running again :-)
