### ISSUE TITLE
[BUG]: KUBECTL Azure Devops TASK kubernetes@1, cannot fetch access token for Azure on version 1.241.5

### ISSUE THREAD

**Issue by RSoares82** [microsoft/azure-pipelines-tasks#20080]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

kubernetes@1

### Task version

1.241.5

### Issue Description

Task started to fail on version 1.241.5 with the message:

Reason Could not fetch access token for Azure. Status code: network_error, status message: Network request failed.

It works on prior versions

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Relevant log output

```shell
2024-06-27T11:46:04.1785075Z ##[error]Cannot download access profile/kube config file for the cluster xpto. Reason Could not fetch access token for Azure. Status code: network_error, status message: Network request failed.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by merlynomsft** [comment]
We appreciate your report. It seems there's a compatibility issue between the updated MSAL dependency in 1.241.5 and Node 10. Migrating to the Node 16 or Node 20 runtime is likely to rectify this problem.  We are actively seeking a permanent fix.

**Comment by RSoares82** [comment]
Another thing... I tried to revert the version in Azure Release Pipeline (classic) to a prior version by setting versionSpec, but is not working, it always defaults to the latest version.

Not sure if its another issue. 

Thanks

**Comment by Ajeit8055** [comment]
@RSoares82 You can try using task Kubernetes@1.238.1 instead of Kubernetes@1

**Comment by RSoares82** [comment]
@Ajeit8055 yes I did that on the yaml pipelines, but on classic releases I don't have that option and versionSpec didn't work.

**Comment by archertango** [comment]
Is there any update / progress on this? Release and build pipelines for us have been broken for almost 2-weeks now. We do regular releases and this has significantly hindered our ability to release updates. This has broken our ability to run k8s jobs from Azure DevOps, which is part of our release process.

@Ajeit8055 we've found a workaround using regular command line tasks calling kubectl. It's not perfect though.

**Comment by jappenzesr** [comment]
We are facing the same issue on our privately hosted VMSS pools. 

Please note that these agents are configured to run behind a corporate proxy. Could it be that the task is not properly picking up proxy settings from the system environment? Analysis with tcpdump reveals that the request towards login.microsoftonline.com is not being sent (no trace of it on network level).

**Comment by v-schhabra** [comment]
Hi @RSoares82 
Thanks for sharing the logs. We could see this issue is thrown out from one of the dependent package. We are collaborating with dependent package(MSAL_node) team to solve this issue. We will keep you posted on the updates.

**Comment by v-schhabra** [comment]
Hi @archertango @jappenzesr 
If you do not have any workarounds please share the complete pipeline logs at v-schhabra@microsoft.com. We can provide you the temporary workaround incase you are blocked.

**Comment by archertango** [comment]
@v-schhabra I've emailed the build and release logs

**Comment by v-schhabra** [comment]
For the permanent fix we are collaborating with msal code owners and will update here once we have the permanent fix.

**Comment by v-schhabra** [comment]
Hi @yolomaniac 
If you are using yaml pipeline you can specify the last working version 
for example like this: - task: AzureRmWebAppDeployment@4.240.2

**Comment by v-schhabra** [comment]
Hi @yolomaniac 
Could you pls share your org details at v-schhabra@microsoft.com?
Becoz the fix has been deployed to few Rings so just wanted to check if the fix is already there on your ring or not?

**Comment by v-schhabra** [comment]
Hi @KristofKuli,
We cannot change the version in classic release pipeline. If possible, please use the yaml pipeline and specify the last working version until the fix is deployed to your ring.

**Comment by KristofKuli** [comment]
Hi @v-schhabra ,

Thank you for the answer. Do you have any ETA, for the fix to be released?

**Comment by jappenzesr** [comment]
With the recent escalation of this issue to the helm task, we have a major productive release pipeline blocked. Please provide us with an ETA for the push of this fix to ADO ring 5. This has the potential to quickly escalate into a major issue on our side now.

**Comment by v-schhabra** [comment]
Hi @jappenzesr 
the fixes will be rolled out till 6thAugust on all the rings. If you are blocked we can perform task override for your org specifically.

**Comment by v-schhabra** [comment]
Hi, the fixes are rolled out on all the rings as large no of cx impacted due to this issue.
