### ISSUE TITLE
[BUG]: NPM@1: "Can't find loc string for key: Info_GotAndMaskAuth"

### ISSUE THREAD

**Issue by jmyersmsft** [microsoft/azure-pipelines-tasks#20120]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

NPM

### Task version

1.241.1

### Issue Description

Warnings in NPM task: "Can't find loc string for key: Info_GotAndMaskAuth"

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

N/A

### Relevant log output

N/A

### Full task logs with system.debug enabled

N/A

### Repro steps

N/A

**Comment by ivanduplenskikh** [comment]
Hi, @jmyersmsft, thanks for bumping it up. There is the PR https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/345 that resolves the problem with missing localization. The update is on its way.

**Comment by dbhaigh** [comment]
Cheers guys - I look forwards to quiet logs on Monday - Thanks

-=A=-

.
