### ISSUE TITLE
[enhancement]: JavaToolInstaller should support GraalVM

### ISSUE THREAD

**Issue by khauser** [microsoft/azure-pipelines-tasks#20151]
### Task name

JavaToolInstaller 

### Describe your feature request here

We use the JavaToolInstaller to enable multiple Java versions on a build agent in azure devops. GraalVM here seems to be not supported.

**Comment by KonstantinTyukalov** [comment]
Thanks for the reporting! We are working on higher priority issues now, but we'll get back to this one soon
