### ISSUE TITLE
[BUG]: FileTransform@V2 prints error, but replaces strings

### ISSUE THREAD

**Issue by eddynaka** [microsoft/azure-pipelines-tasks#20286]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

FileTransform

### Task version

2.244.1

### Issue Description

I use file transform to update some settings in my appSettings.json file with the following snippet:
```yml
- task: FileTransform@2
  displayName: 'Update host.json with production configuration for GitHubProcessor'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/SOME_PATH/Publish/'
    jsonTargetFiles: host.json
```

When the pipeline executes, I can see the following:
```
Starting: Update host.json with production configuration for GitHubProcessor
==============================================================================
Task         : File transform
Description  : Replace tokens with variable values in XML or JSON configuration files
Version      : 2.244.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/file-transform
==============================================================================
##[error]Unable to apply transformation for the given package - Changes are already present in the package.
Applying JSON variable substitution for host.json
Applying JSON variable substitution for D:\a\_work\1\s\SOME_PATH/Publish\host.json
Substituting value on key keyVaultEndpoint with (string) value: SOMETHING
Substituting value on key RedisCacheHostName with (string) value: SOMETHING
JSON variable substitution applied successfully.
Finishing: Update host.json with production configuration for XXX
```

As you can see, it works, but is also shows an error:
```
##[error]Unable to apply transformation for the given package - Changes are already present in the package.
```

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-latest

### Relevant log output

```shell
##[error]Unable to apply transformation for the given package - Changes are already present in the package.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by Deekshitha981** [comment]
Hi, we are actively working on this issue. Will provide the updates asap.

**Comment by EshitaD** [comment]
Hi @eddynaka, can you please the share me the repro steps?

**Comment by eddynaka** [comment]
1. Create a build pipeline that has a json file with properties, let's say KeyA = ValueA, KeyB = ValueB
2. Add a task to transform KeyA value to ValueAA and KeyB value to ValueBB
3. Upload as artifact so you can validate the transformation
4. Run

If you run the steps above, you will see that the artifacts will have the modified json file as expected, but you will also see errors in your pipeline regarding the replacement.

**Comment by JamesInDenver** [comment]
The task also outputs this error if there are no value changes performed.

**Comment by brs713** [comment]
This is still an issue for json transforms:
![Image](https://github.com/user-attachments/assets/45ec0af7-234f-4bf5-9f91-d7616e25dd5c)
