### ISSUE TITLE
[BUG]: AzureFunctionAppV2 has invalid json for Russian Resource files

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#20293]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp

### Task version

2.244.2

### Issue Description

The resource file for the Russian translations is missing its closing `}`.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [X] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Any

### Relevant log output

```shell
ConvertFrom-Json: D:\a\azure-pipelines-tasks-zips\azure-pipelines-tasks-zips\generate-sxs.ps1:52
Line |
  52 |  … es = (Get-Content $resourceFile -raw) | ConvertFrom-Json -AsHashtable
     |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected end when deserializing object. Path
     | '['loc.messages.DeploymentTypeNotSupportedForFlexConsumption']', line 180, position 133.
```
```


### Full task logs with system.debug enabled

n/a


### Repro steps

```yml
n/a
```

**Comment by jessehouwing** [comment]
Fixed by: https://github.com/microsoft/azure-pipelines-tasks/pull/20292

**Comment by v-schhabra** [comment]
@FinVamp1 Could you or your team please check this issue?

**Comment by jessehouwing** [comment]
Fixed in: https://github.com/microsoft/azure-pipelines-tasks/commit/a6a6a01b7369f40e6b3bf3640842d78e9be07e5e
