### ISSUE TITLE
[BUG]:  Getting warnining Task 'Azure Key Vault' version 1 (AzureKeyVault@1) is deprecated while using library linked with keyvault

### ISSUE THREAD

**Issue by venkatest** [microsoft/azure-pipelines-tasks#20302]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Azure Key Vault

### Task version

1

### Issue Description

We are not using the Azure Key Vault task directly in our pipeline however we are using library linked with keyvault. when the build runs, pipeline automatically adds prejob to Download secrets. Since last couple of days, we are getting the warning - The AzureKeyVault@1 task is deprecated, please use the latest version of the AzureKeyVault task

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

ubuntu:20.04

### Relevant log output

```shell
Starting: Initialize job
Agent name: '****************'
Agent machine name: '****************'
Current agent version: '3.243.0'
Agent running as: '*****'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: AzureKeyVault (1.244.1)
##[warning]Task 'Azure Key Vault' version 1 (AzureKeyVault@1) is deprecated.
##[warning]The AzureKeyVault@1 task is deprecated, please use the latest version of the AzureKeyVault task
Downloading task: Bash (3.241.1)
Downloading task: PublishBuildArtifacts (1.238.1)
```

### Full task logs with system.debug enabled

na

### Repro steps

```yml
na
```

**Comment by basvo** [comment]
We are encountering the same issue.

**Comment by roospa** [comment]
Encountering the same issue running self-hosted agents on Windows Server.

**Comment by jflieben** [comment]
+1

**Comment by Frettarix** [comment]
+1

**Comment by slavizh** [comment]
+1

**Comment by mrlnstpn** [comment]
+1

**Comment by epernst** [comment]
+1

**Comment by Liszet** [comment]
+1

**Comment by damu9618** [comment]
+

**Comment by stefankaufmann** [comment]
+1

**Comment by sandstreampop** [comment]
+1

**Comment by davisowb** [comment]
Pretty please stop adding '+1' comments as we all get spammed with emails and instead add a thumbs up to the original post, if you want updates hit subscribe on the right.

**Comment by venkatest** [comment]
I see the same issue is reported in ms community, added my comments there and also adding the community link here for reference https://developercommunity.visualstudio.com/t/Task-Azure-Key-Vault-version-1-AzureK/10722590?q=Keyvault&sort=newest

**Comment by anthonywhite** [comment]
same...

**Comment by rvairavelu** [comment]
Azure Key Vault' version 1 (AzureKeyVault@1) is deprecated, We will work on the fixes when the pipeline uses the library linked with keyfault. Will keep this thread updated once the fixes are done 
cc @manolerazvan @PhilipsonJoseph @v-bsanthanak

**Comment by chumster** [comment]
+1
We run nightly tests. Just started seeing this issue on Friday of last week (August 16th, 2024)

**Comment by PeterConijn** [comment]
Same with self-hosted agents on Azure VM

**Comment by akoeplinger** [comment]
@rvairavelu can you please disable the deprecation warning in the meantime until the fix is implemented?

**Comment by TonyNets** [comment]
It's been over a week since this issue was opened, and it is disappointing to note that no one from the support team has acknowledged or addressed the problem yet.
Is there any update or at least a temporary workaround that can be applied? Hoping for a quick resolution.

**Comment by ngcdev** [comment]
Yeah, very unfortunate timing of this bug. We're in the middle of "cleaning up" warnings in over 100 pipelines and we started facing these, which we cannot do anything about.

**Comment by TonyNets** [comment]
![image](https://github.com/user-attachments/assets/e6d0d628-f9ed-448e-bde1-5aa44e1b6ba3)
@microsoft/release-management-task-team, @manolerazvan 
Tagging the code owners of this task to bring this issue to their attention. It's been more than a week since this bug was reported, and unfortunately, there hasn't been any response from their support team despite multiple users highlighting the inconvenience it’s causing.

Given the impact on so many users, I hope the owners or any communication from the task support team regarding the status and expected resolution.
P.S. It's a little frustrating to see the lack of response from Microsoft support on the increasing issues in recent days.

**Comment by Deekshitha981** [comment]
Hi team, we are actively working on this issue, will provide the fix asap.

**Comment by weshaggard** [comment]
@aleksandrlevochkin should we revert your change https://github.com/microsoft/azure-pipelines-tasks/pull/20222 until this issue can be resolved? These warnings are causing a lot of noise and there isn't anything we can to do resolve it.

**Comment by Deekshitha981** [comment]
Hi, we are working on deploying the changes. The fix should be available by the end of September first week.

**Comment by sushovan** [comment]
We are facing the same issue in Azure Pipelines agents also, so we are waiting for the changes.

**Comment by aavdberg** [comment]
We have the same also using the Pipeline - Library to get values from the keyvault and this injects the ##[warning]Task 'Azure Key Vault' version 1 (AzureKeyVault@1) is deprecated in our pipeline.

@Deekshitha981 what is the status of this and how can this short of things prevented in the feature?

**Comment by katerynafiroozi** [comment]
We encounter the same issue with Microsoft hosted build agents.

**Comment by Deekshitha981** [comment]
Hi all, the fix got rolledout. Hope this resoleves the issue.

**Comment by telmen87** [comment]
> Hi all, the fix got rolledout. Hope this resolves the issue.

Thanks, it works fine now.

**Comment by venkatest** [comment]
Thanks, it works good. warnings are not shown now.

**Comment by DanFrei64** [comment]
This appears to have fixed my pipelines as well. Thank you.
