### ISSUE TITLE
[BUG]: Latest ArtifactTool binary from UniversalPackage task is not compatible with CentOS

### ISSUE THREAD

**Issue by nnellanspdl** [microsoft/azure-pipelines-tasks#20307]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UniversalPackage

### Task version

0.243.1

### Issue Description

Yes, I know all about CentOS being end of life (unfortunately, we still need to run it for a while).

UniversalPackage is currently downloading ArtifactTool version `0.2.359`.  This version of ArtifactTool gives an error when running on CentOS:  `/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by /opt/azure/_work/_tool/ArtifactTool/0.2.359/x64/artifacttool)`

In my previous pipeline runs, the same version of UniversalPackage was downloading an older version of ArtifactTool: `0.2.350`.  This version worked just fine without any errors.

Is there anything I can do?  Is there a way to somehow hard-code the version of ArtifactTool that is downloaded by UniversalPackage?

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

CentOS

### Relevant log output

```shell
##[error]Error: An unexpected error occurred while trying to download the package. Exit code(1) and error(/opt/azure/_work/_tool/ArtifactTool/0.2.359/x64/artifacttool: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/azure/_work/_tool/ArtifactTool/0.2.359/x64/artifacttool)
##[error]Packages failed to download
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by 7fold** [comment]
We are having same issue on `RHEL 7.9` The latest version of ArtifactTool which worked was `0.2.350`

**Comment by sadmdbrezack-metabolon** [comment]
Same issue `centos7`. Broke half our build pipelines. Can't find a way to revert it due to the tool downloading the latest. 

@v-schhabra can we revert the artifact tools version ?

**Comment by 7fold** [comment]
We spoke with MS Support and their product group is starting a release to rollback all the recent changes they pushed including `ArtifactTool`. Not sure if it will affect all organizations or just ours.

**Comment by carl-tanner** [comment]
With the upcoming end of support for .NET6 we need to move ArtifactTool to run with .NET8 which means we will only run on OSes supported by .NET8. You can use the following workaround to pin the version of ArtifactTool to the final .NET6 version we have published. This isn't supported so if it breaks at some point in the future the recommendation is going to be to move to an OS that is supported.

```
- task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        account="{yourorghere}";
        osName="linux";
        arch="amd64";
        version="0.2.350";
        downloadPath=$(Agent.TempDirectory);
        destinationZip="${downloadPath}/artifacttool.zip";
        destinationDir="${downloadPath}/artifacttool";
        destinationExe="${destinationDir}/artifacttool.exe";

        sourceUrl="https://vsblob.dev.azure.com/$account/_apis/clienttools/artifacttool/download?osName=$osName&arch=$arch&version=$version"

        curl -L -o $destinationZip $sourceUrl

        mkdir -p $destinationDir;

        unzip $destinationZip -d $destinationDir;

        echo "EXE: $destinationExe";
        echo "destinationDir: $destinationDir";
        echo "##vso[task.setvariable variable=UPack.OverrideArtifactToolPath;]$destinationDir";
    displayName: 'Download, extract ArtifactTool.exe and set UPack.OverrideArtifactToolPath'
```
You could also download the tool via the url `https://vsblob.dev.azure.com/{your-account-here}/_apis/clienttools/artifacttool/download?osName=linux&arch=amd64&version=0.2.350` (replace {your-account-here} with your ado organization name) and bake it into your linux image. You can set an environment variable UPack.OverrideArtifactToolPath to point to the folder containing the older version.

Next month we will deploy the newer version and your upack tasks will break if you have not implemented this workaround.

**Comment by sadmdbrezack-metabolon** [comment]
> With the upcoming end of support for .NET6 we need to move ArtifactTool to run with .NET8 which means we will only run on OSes supported by .NET8. You can use the following workaround to pin the version of ArtifactTool to the final .NET6 version we have published. This isn't supported so if it breaks at some point in the future the recommendation is going to be to move to an OS that is supported. Replace {yourorghere} with the name of your ado organization.
> 
> ```
> - task: Bash@3
>     inputs:
>       targetType: 'inline'
>       script: |
>         account="{yourorghere}";
>         osName="linux";
>         arch="amd64";
>         version="0.2.350";
>         downloadPath=$(Agent.TempDirectory);
>         destinationZip="${downloadPath}/artifacttool.zip";
>         destinationDir="${downloadPath}/artifacttool";
> 
>         sourceUrl="https://vsblob.dev.azure.com/$account/_apis/clienttools/artifacttool/download?osName=$osName&arch=$arch&version=$version"
> 
>         curl -L -o $destinationZip $sourceUrl
> 
>         mkdir -p $destinationDir;
> 
>         unzip $destinationZip -d $destinationDir;
> 
>         echo "destinationDir: $destinationDir";
>         echo "##vso[task.setvariable variable=UPack.OverrideArtifactToolPath;]$destinationDir";
>     displayName: 'Download, extract ArtifactTool and set UPack.OverrideArtifactToolPath'
> ```
> 
> You could also download the tool via the url `https://vsblob.dev.azure.com/{yourorghere}/_apis/clienttools/artifacttool/download?osName=linux&arch=amd64&version=0.2.350` (replace {yourorghere} with your ado organization name) and bake it into your linux image. You can set an environment variable UPack.OverrideArtifactToolPath to point to the folder containing the older version.
> 
> Next month we will deploy the newer version and your upack tasks will break if you have not implemented this workaround.

@carl-tanner why not just add a version option to the ADO task ? That would fix this problem for the current users and negate this problem for years

**Comment by carl-tanner** [comment]
It is an interesting idea and we may implement it in the future.

**Comment by nnellanspdl** [comment]
> It is an interesting idea and we may implement it in the future.

It would be cool to have a holistic approach for all tasks.  If a task is getting updated so that it requires .NET 8 support, then it'd be great to have some common "backwards-compatible" or "unsupported" flag on each of those tasks.

**Comment by jbiel** [comment]
@carl-tanner is the source for `artifacttool` available somewhere? i'm using NixOS and am unable to run this tool because it's a dynamically linked binary. I'd like to get it properly packaged up. Thanks!

```
$ ./artifacttool
Could not start dynamically linked executable: ./artifacttool
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```
