### ISSUE TITLE
[BUG]: AzureResourceManagerTemplateDeployment@3 fails when System.DefaultWorkingDirectory differs from Build.SourcesDirectory and csmParametersFile is not set

### ISSUE THREAD

**Issue by rikjansen-hu** [microsoft/azure-pipelines-tasks#20494]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureResourceManagerTemplateDeployment

### Task version

3

### Issue Description

When running the task in a situation where `Build.SourcesDirectory` differs from `System.DefaultWorkingDirectory` (e.g. multiple checkouts) and the _csmParametersFile_ is ommited (or empty), the task fails with error:

`##[error]Error: Parameters file pattern matches a directory instead of a file. D:\a\1\s\my-repo-name
`

System.DefaultWorkingDirectory = D:\a\1\s\my-repo-name
Build.SourcesDirectory = D:\a\1\s

This situation can occur when multiple repo's are checked out in one job.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 11, Ubuntu 20.04

### Relevant log output

```shell
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription 000-000-000-000"
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" bicep build --file D:\a\1\s\my-repo-name\sub1\sub2\file.bicep"
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
(node:3732) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
The detected encoding for file 'D:\a\1\s\my-repo-name\sub1\sub2\file.json' is 'utf-8'
(Use `node --trace-deprecation ...` to show where the warning was created)
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Error: Parameters file pattern matches a directory instead of a file. D:\a\1\s\my-repo-name
Finishing: TaskName
```

**Comment by nagarajku** [comment]
Hi @rikjansen-hu - Thanks for reporting this on the GitHub. Few things to note here. 
We understand that the $(System.DefaultWorkingDirectory) will be referred when you are referencing a file created during the build. However, the $(Build.SourcesDirectory) will be referred when you want to use the files which are used during the build process. So, both of these differs in their path. 
Also, we want to know: 
How are you using ARMTemplateDeployment@3? - in yaml pipeline or classic release pipeline
What is the template you are using? Linked artifact or URL of the file.
Are you referring the template from the repository or from the drop generated from the build pipelines?
What is the type of agents you are using? Self-hosted agents or MS Hosted agents? Please specify the agent version.
Was this task working before? If so, what is the task version it worked lastly and what is the current version using?

Please share the complete debug logs by setting **system.debug** as "true" and also the yaml template if any.
Thanks

**Comment by nagarajku** [comment]
Hi @rikjansen-hu can you please share the required inputs for the further investigation. Thanks

**Comment by nagarajku** [comment]
Hi @rikjansen-hu  
Reminder: can you please share the required inputs for further investigation. Thanks

**Comment by nagarajku** [comment]
Hi @rikjansen-hu -  as we did not hear back, we are closing the issue. Feel free to reach us for any assistance.
Thanks
