### ISSUE TITLE
[BUG]: UseDotnetV2 - Fails silently to download

### ISSUE THREAD

**Issue by JasonWhall** [microsoft/azure-pipelines-tasks#20508]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UseDotnet

### Task version

2.246.1

### Issue Description

It seems the task is silently stopping after attempting to download the zip containing a version of the .NET sdk and then continues onto the next step. I would expect this to either error and fail the task or to successfully log that it has downloaded the tool and extracted into the tool directory

The offending area of code that it seems to be exiting from is in the azure-pipelines-tool-lib repository noted here - https://github.com/microsoft/azure-pipelines-tool-lib/blob/41acd733ff90c8bbc02c42376f46800b794cdc99/tool.ts#L251

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [x] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server Latest/Ubuntu Latest

### Relevant log output

```shell
Downloading: https://download.visualstudio.microsoft.com/download/pr/c1b355f8-c828-4d2d-a0f5-a0695834be68/2c7a7983c02bebffc071648658b33b73/dotnet-sdk-8.0.107-win-x64.zip
##[debug]destination C:\a\_temp\df4b4a33-ebde-4814-802e-b45b3bdd2674
##[debug]downloading
##[debug]Content-Length of downloaded file: 282187308
##[debug]creating stream
Finishing: Install .NET SDK
```
```


### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>


### Repro steps

_No response_

**Comment by BastienPerdriau** [comment]
We have the same issue here since this morning.

Was there a recent update to the task?

**Comment by AleksuKey** [comment]
We are having this issue since this morning too.

**Comment by double-sigma** [comment]
Same issue started today morning for our .NET builds on Self-Hosted agents.
```
Task         : Use .NET Core
Version      : 2.246.1
```

**Comment by DergachevE** [comment]
Thanks for raising this issue to us.
The team will look into it and come with updates.

As per recent changes:

> I can see this update for this task on the release listed in the repo : https://github.com/microsoft/azure-pipelines-tasks/pull/20446
This PR introduces a new 2.246.2 task version which is not yet rolled out

**Comment by BastienPerdriau** [comment]
I rolled back to 2.243.1 which was working a few days / weeks ago and I have the same output of download not always waited without raising any error, so following tasks using dotnet are failing.
But it's a bit random, and when a task finally manage to download and extract the SDK, it can be reused on following jobs if there are on the same agent.

**Comment by mbyt** [comment]
We have the same issue since yesterday:

```
Agent name: 'Hosted Agent'
Current agent version: '3.245.0'
Microsoft Windows Server 2022
Image: windows-2022
Version: 20240929.1.0
Downloading task: UseDotNet (2.246.1)
```

**Comment by AleksuKey** [comment]
Hi @DergachevE , could this issue be escalated? This is creating a huge impact in our dev teams unfortunately.

**Comment by tijlreynhout** [comment]
We seem to be having the same problem but it doesn't always happen for us. I have no idea why it does or doesn't work. 

Agent name: 'Hosted Agent'
Current agent version: '3.245.0'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
    Image: windows-2022
    Version: 20240929.1.0


The task downloads the zip file, then finishes without extracting/installing the sdk. The next step is restoring nuget packages but this fails because the sdk version is not found.  

![image](https://github.com/user-attachments/assets/260aaa8b-e8af-4e14-b17a-23b7d63229f7)

**Comment by Skypesilver** [comment]
It happens about 50% of the time for us. I see reverting to version 2.243.1 did not help a poster above. Perhaps reverting to an even earlier version would help?

**Comment by sicil1ano** [comment]
> It happens about 50% of the time for us. I see reverting to version 2.243.1 did not help a poster above. Perhaps reverting to an even earlier version would help?

Unfortunately the issue happens even with previous versions. We rolled back to 2.238.1 and still same problem, build failing 50% of the time.
I guess we will just wait for a proper fix.

**Comment by double-sigma** [comment]
Today I saw this in the logs if this is of help:
```Primary:linux-x64
Legacy:-x64
Detected platform (Primary): linux-x64
Detected platform (Legacy): -x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/1ebffeb0-f090-4001-9f13-69f112936a70/5dbc249b375cca13ec4d97d48ea93b28/dotnet-sdk-8.0.402-linux-x64.tar.gz
##[warning]Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/1ebffeb0-f090-4001-9f13-69f112936a70/5dbc249b375cca13ec4d97d48ea93b28/dotnet-sdk-8.0.402-linux-x64.tar.gz Error: Error: Aborted
    at IncomingMessage.<anonymous> (/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.246.1/node_modules/azure-pipelines-tool-lib/tool.js:241:36)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at TLSSocket.socketCloseListener (node:_http_client:471:11)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:657:7)
Using fallback url for download: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.402/dotnet-sdk-8.0.402-linux-x64.tar.gz
Downloading: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.402/dotnet-sdk-8.0.402-linux-x64.tar.gz
##[warning]Content-Length (211866121 bytes) did not match downloaded file size (261578 bytes).
Extracting downloaded package /workspace/_temp/23a1b4eb-1e5b-44b5-b677-96f2d62dd70c.
Extracting archive
/usr/bin/tar xC /workspace/_temp/2c0b7ec4-1af0-4a21-a0be-a96d71c3f537 -f /workspace/_temp/23a1b4eb-1e5b-44b5-b677-96f2d62dd70c

Successfully installed .NET Core sdk version 8.0.402.
```

**Comment by double-sigma** [comment]
As a workaround if you use a custom image for you agent as we do (self-hosted agent pool on AKS), then you can just bake in the dotnet sdk:
```
ARG DOTNET_VERSION="8.0.402-1"
RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb \
     -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb \
     && apt-get update && apt-get install -y --no-install-recommends dotnet-sdk-8.0=${DOTNET_VERSION}
```

I see that our builds where dotnet failed to download are now passing. Download failure rate is quite high, more than 50%.

**Comment by finkinfridom** [comment]
We started getting the above errors from 30 minutes ago. The issue now seems like happening 100% of the time.
Any suggestion to workaround this issue? maybe adding a custom script (similar to the one above) to be executed in the pipeline?

**Comment by KonstantinTyukalov** [comment]
Hi folks, as a quick workaround we suggest using the following scripts before the `UseDotnet` step execution:

for windows:
```yml
- powershell: |
    # your target dotnet version
    $version = "8.0.107"

    # your target install path
    $sdkInstallationPath = Join-Path $env:AGENT_TOOLSDIRECTORY dotnet

    $scriptUrl = "https://dot.net/v1/dotnet-install.ps1"
    $scriptPath = Join-Path  $env:AGENT_TEMPDIRECTORY dotnet-install.ps1
    Invoke-WebRequest -Uri $scriptUrl -OutFile "$scriptPath"

    & $scriptPath -Version $version -InstallDir $sdkInstallationPath -Verbose

    "$version" > "${sdkInstallationPath}\sdk\${version}.complete"

  condition: eq(variables['Agent.OS'], 'Windows_NT')
```

for linux & macos:
 
```yml
- bash: |
      # your target dotnet version
      version="8.0.107"

      # your target install path
      installationPath="$(Agent.ToolsDirectory)/dotnet"

      script_path="$(Agent.TempDirectory)/dotnet-install.sh"
      curl -o $script_path "https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh"
      chmod +x $script_path

      $script_path --version $version --install-dir $installationPath --verbose

      echo "$version" > "${installationPath}/sdk/${version}.complete"

  condition: ne(variables['Agent.OS'], 'Windows_NT')
  ```
  
  With these scripts, `UseDotnet` task will find downloaded dotnet version and skip archive fetching.
  
 !!!! Please make sure `version` and `installationPath` variables in scripts are matching the `UseDotnet` task input values

**Comment by Vhab** [comment]
> Thanks for raising this issue to us. The team will look into it and come with updates.
> 
> As per recent changes:
> 
> > I can see this update for this task on the release listed in the repo : #20446
> > This PR introduces a new 2.246.2 task version which is not yet rolled out

Hi,

Thank you for recognizing this is an issue, but would it be possible to escalate the severity of this up a few notches?

We're currently heavily affected by this issue, and it's wrecking havoc across multiple pipelines.
And given the nature of the issue and the multitude of responses to this thread, it's hard to believe this isn't negatively affecting a large set of your customers at the moment.

**Comment by DerAlbertCom** [comment]
Hi @DergachevE 

Yes, please give the rollout a priority, this is terrible for a couple of days now.

Most of our Builds are failing because of that, and we have to rerun it manually. And the Workarounds are not really suitable for us.

**Comment by anttix** [comment]
Hi @DergachevE and @KonstantinTyukalov!

We see builds failing due to the same issue. While I appreciate the provided workarounds, is there a way to escalate this issue to speed up a resolution?

Thank you.

**Comment by shurick81** [comment]
Here's a script for installing dotnet, not full SDK:

```yaml
- powershell: |
    # your target dotnet version
    $version = $env:version;

    # your target install path
    $sdkInstallationPath = Join-Path $env:AGENT_TOOLSDIRECTORY dotnet

    $scriptUrl = "https://dot.net/v1/dotnet-install.ps1"
    $scriptPath = Join-Path  $env:AGENT_TEMPDIRECTORY dotnet-install.ps1
    Invoke-WebRequest -Uri $scriptUrl -OutFile "$scriptPath"

    & $scriptPath -Runtime dotnet -Version $version -InstallDir $sdkInstallationPath -Verbose

    "$version" > "${sdkInstallationPath}\shared\Microsoft.NETCore.App\${version}.complete"
  displayName: Installing .NET
  env:
    version: 3.1.32
```

**Comment by shurick81** [comment]
Also had to change to `$sdkInstallationPath = "C:\Program Files\dotnet"` so that apps finds the installed version in the default dotnet path. Otherwise I get this:

```
You must install or update .NET to run this application.

App: D:\a\1\s\someapp.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  6.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.33 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win-x64&os=win10
```

**Comment by VtotheK** [comment]
Same issue here, happens randomly (maybe 50% of runs fail). Starts downloading the SDK, returns early and subsequent nuget installation fails. 

```
Detected platform (Primary): linux-x64
Detected platform (Legacy): -x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/1ebffeb0-f090-4001-9f13-69f112936a70/5dbc249b375cca13ec4d97d48ea93b28/dotnet-sdk-8.0.402-linux-x64.tar.gz
Finishing: Install .NET Core SDK
```

**Comment by mortenbock** [comment]
I made a pipeline with the following steps, and ran it a few times:

```
      - task: UseDotNet@2
        displayName: Install .NET 6.0
        inputs:
          version: 6.0.x

      - task: UseDotNet@2
        displayName: Install .NET 8.0
        inputs:
          version: 8.0.x

      - script: dotnet --info
        displayName: dotnet info
```
The result was the following:

|Agent|Run|v6 installed|v8 installed|
|-|-|-|-|
|ubuntu-22.04|1|x|x|
|ubuntu-22.04|2|x|x|
|ubuntu-22.04|3||x|
|ubuntu-22.04|4|x|x|
|ubuntu-24.04|1|x|x|
|ubuntu-24.04|2|x||
|ubuntu-24.04|3||x|
|ubuntu-24.04|4|x|x|

Please prioritize a fix for this.

**Comment by KonstantinTyukalov** [comment]
Hi everyone, we are currently releasing fixed task versions - `2.247.0` and `2.247.1`
If you see these working in your pipeline, please let us know if you have any issues

**Comment by DerAlbertCom** [comment]
2.247.1 first run succeeded (will watch it). 15 minutes ago with 246.1 was failing.

**Comment by anttix** [comment]
First few builds using 2.247.1 were successful. Will report back once I have more data.

**Comment by sicil1ano** [comment]
> Hi everyone, we are currently releasing fixed task versions - `2.247.0` and `2.247.1` If you see them working in your pipeline, please share feedback if the issue is resolved in your case or let us know if you are still experiencing issues.
> 
> Thanks

Hallelujah!
Sorry for my frustration, but sometimes I think we developers, users of these products, are also considered your QA.
I don't understand otherwise how it's possible to leave people with problems like this after 5 days, without even rolling out the rollback of the change that caused all of that in first place.

**Comment by kimsey0** [comment]
Also seems to work nicely for us. Thanks!

**Comment by AleksuKey** [comment]
The fix works fine for us.

**Comment by DergachevE** [comment]
Thanks everyone for your patience!
Looks like the issue was fixed so I am closing this issue, but feel free to re-open if needed.

@sicil1ano I understand your frustration.
The team was working hard on the RC-ing  the issue, but considering the fact that previous versions of the task also started failing (but were working before) we had to investigate a combination of factors. This took us more time to deliver the fix.
