### ISSUE TITLE
[Question]: How to use managed identity with DotNetCoreCLI@2 task

### ISSUE THREAD

**Issue by yanggaome** [microsoft/azure-pipelines-tasks#20526]
### Task name

DotNetCoreCLI

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu

### Question

```shell
Hello, for AzureCLI task, it supports azureSubscription where we can pass in a service connection with managed identity. But for DotNetCoreCLI, is there a way to use managed identity/service connection?

Thanks
```

**Comment by ismayilov-ismayil** [comment]
Hi @yanggaome, Unfortunately DotnetCoreCli doesnt support MI directly, but you can pass token from azurecli as shown [here](https://learn.microsoft.com/en-us/azure/healthcare-apis/get-access-token?tabs=azure-cli)
