### ISSUE TITLE
[Question]: Why is the default branch still `master` instead of `main`?

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/azure-pipelines-tasks#20530]
Hello! I noticed that the default branch for this repo is `master`. I was under the impression that all repos in the Microsoft org were supposed to switch to `main` long ago? We should consider renaming the master branch here.

**Comment by ismayilov-ismayil** [comment]
Hello @AdamYoblick, restructure of the repositories is on the our roadmap. We will inform you about upcoming changes in the near future.
