### ISSUE TITLE
[BUG]: Small typo in Error Message for Task AzureCLIV2 'Script Location' in Azure DevOps

### ISSUE THREAD

**Issue by yilas** [microsoft/azure-pipelines-tasks#20616]
### What happened?

Hello,

While running a pipeline, I encountered an error message with a typo : 

```
##[error]Script failed with error: Error: inline is not a valid value for task input 'Script Location' (scriptLocation in YAML). Value can either be'inlineScript' or 'scriptPath'
````

It seems that there is a missing space between "be" and "'inlineScript'," which would improve readability. The message should be:

```
Value can either be 'inlineScript' or 'scriptPath'
```

Thank you for addressing this correction

![Image](https://github.com/user-attachments/assets/5ae0b339-0fcb-4ea8-9049-ba0bc95b4715)

### Versions

All versions

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

Version Azure DevOps Server 2022 RC1 (AzureDevOpsServer_20220728.1)

### Operation system

Windows 10

**Comment by v-schhabra** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/20637
