### ISSUE TITLE
[REGRESSION]: UseDotNet@2 fails to install dotnet sdk 8.0.x on self hosted agent with version 8.0.403 and SDK 8.0.306, but not SDK 8.0.402

### ISSUE THREAD

**Issue by landlord-matt** [microsoft/azure-pipelines-tasks#20626]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UseDotNet

### Breaking task version

8.0.402

### Last working task version

8.0.306

### Regression Description

We're installing dotnet as part of our integration test pipeline.

```
- task: UseDotNet@2
  displayName: 'Install .NET 8.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
```

This used to work fine, but for some reason it now fails to install the latest version (8.0.403) and (8.0.306). However switching version to '8.0.402' explicitly makes it all work again.

The error message received are
##[warning]Content-Length (212874079 bytes) did not match downloaded file size (104218609 bytes).

##[error]Failed while installing version: 8.0.403 at path: /azp/DevOpsAgent/_work/_tool/dotnet with error: Error: Aborted

Since it works with older version, the problem must be in your hosting.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

3.246.0

### Operation system

linux-x64

### Relevant log output

##[debug]Attempt 2 failed. Retrying after 1000 ms
##[debug]download complete
##[debug]Downloaded file size: 104218609 bytes
##[warning]Content-Length (212874079 bytes) did not match downloaded file size (104218609 bytes).
##[debug]Processed: ##vso[task.issue type=warning;source=TaskInternal;correlationId=0ef0567a-5322-4c9c-85fa-2a79a0fe1eb7;]Content-Length (212874079 bytes) did not match downloaded file size (104218609 bytes).
##[debug]Agent environment resources - Disk: / Available 112702.31 MB out of 126841.92 MB, Memory: Used 1249.00 MB out of 7939.00 MB, CPU: Usage 2.93%
##[debug]
##[debug]Agent.Version=3.246.0
##[debug]Agent.TempDirectory=/azp/DevOpsAgent/_work/_temp
##[debug]testing directory '/azp/DevOpsAgent/_work/_temp'
Downloading: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.403/dotnet-sdk-8.0.403-linux-x64.tar.gz
##[debug]destination /azp/DevOpsAgent/_work/_temp/7515e6d2-6be3-4b7c-b4fb-6a5cf734c36e
##[debug]downloading
##[debug]Content-Length of downloaded file: 212874079
##[debug]creating stream
##[debug]file write stream opened. fd: 19
##[debug]subscribing to message read stream events...
##[debug]successfully subscribed to message read stream events
##[debug]Agent environment resources - Disk: / Available 112657.29 MB out of 126841.92 MB, Memory: Used 1250.00 MB out of 7939.00 MB, CPU: Usage 5.64%
##[debug]Agent environment resources - Disk: / Available 112622.88 MB out of 126841.92 MB, Memory: Used 1249.00 MB out of 7939.00 MB, CPU: Usage 4.93%
##[debug]task result: Failed
##[error]Failed while installing version: 8.0.403 at path: /azp/DevOpsAgent/_work/_tool/dotnet with error: Error: Aborted
    at IncomingMessage.<anonymous> (/azp/DevOpsAgent/_work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.247.1/node_modules/azure-pipelines-tool-lib/tool.js:249:36)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at TLSSocket.socketCloseListener (node:_http_client:471:11)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:657:7)
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=0ef0567a-5322-4c9c-85fa-2a79a0fe1eb7;]Failed while installing version: 8.0.403 at path: /azp/DevOpsAgent/_work/_tool/dotnet with error: Error: Aborted

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by ivanduplenskikh** [comment]
@landlord-matt, the issue might be a temporary problem with the CDN `https://dotnetcli.azureedge.net`
Could you please attempt the workaround mentioned here https://github.com/microsoft/azure-pipelines-tasks/issues/20508#issuecomment-2393883988

**Comment by landlord-matt** [comment]
Hmm

It failed with the same issue on the run at "Nov 7, 2024 at 5:20 AM GMT+1", but has been working in all three runs since "Nov 7, 2024 at 5:40 AM GMT+1"

I can try the workaround if it fails again. Thanks @ivanduplenskikh
