### ISSUE TITLE
[BUG]: Bash exited with code '1'

### ISSUE THREAD

**Issue by akib1997** [microsoft/azure-pipelines-tasks#20738]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Azure Pipeline

### Issue Description

Bash exited with code '1' when running npm install. It breaks all pipelines although I haven't changed any code.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

I don't know

### Relevant log output

```shell
https://dev.azure.com/unipet-bespok/25d9a951-b5d0-409a-a1fa-03877f6c61bf/_apis/build/builds/11083/logs/7
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml

```

**Comment by akib1997** [comment]
![Image](https://github.com/user-attachments/assets/3f136727-8ceb-4796-8b4e-5811d2680d05)

![Image](https://github.com/user-attachments/assets/7a2911c9-3c83-4996-a519-b6f81f449a69)

**Comment by aleksandrlevochkin** [comment]
Hi @akib1997, sorry for the late answer. I think this is related to this issue: https://github.com/npm/cli/issues/7986

Seems like it has been fixed on the npm side since then. Is the pipeline working for you now?
