### ISSUE TITLE
Unable to get FQDN for all resources in ResourceGroup

### ISSUE THREAD

**Issue by kkellyfr** [Microsoft/azure-pipelines-tasks#3235]
Hello,

I have an ARM Template that creates 6 VMs, 2 in each of 3 availability groups with load balancers, but only 1 load balancer is public. As a result, 4 of the VMs are not publically available.

The "Azure Deployment: Create or Update Resource Group" action works (as confirmed in Deployment history in Azure portal), but after sucessfull creation of the resources, the action reports the error in the subject of this issue and therefore marks the build as failed. A detailed log shows that it is trying to get FQDNs for all 6 VMs, but I don't want it to!

I have seen other remarks about adding public IPs to the VMs, but this is not acceptable in my case. The VMs are internal and should not be publically exposed.

What can I do to make this work other than falling back to a raw Azure PowerShaell action?

Regards,
Keith

PS. Strangely I did have one sucessfull build (out of 12), so it seems that some hosted agents have a different behaviour..

**Comment by nambisan** [comment]
Same issue here
logs:
Successfully created resource group deployment with name 'myresourcegroup'
Unable to get FQDN for all resources in ResourceGroup : 'myresourcegroup'

This [issue](https://github.com/Microsoft/vsts-tasks/issues/2271) (which is referred in the issue description) does not help since the suggested solution is to create the Public IP explicitly

The public IPs of the VMs are dynamically generated per this  [article](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-portal-create-fqdn) and the portal does not complain. 
So what gives?

**Comment by kkellyfr** [comment]
In my case, 4 VMs are internal and there MUST NOT have public IPs.

**Comment by chshrikh** [comment]
@kkellyfr @nambisan Can u share the full log (Build/Release with system.debug mode true) ?

**Comment by nambisan** [comment]
@chshrikh  here you go 
[logs_6 - Copy.zip](https://github.com/Microsoft/vsts-tasks/files/657559/logs_6.-.Copy.zip)

**Comment by nambisan** [comment]
@chshrikh 
I have the relevant (sanitized)log attached with the commands leading up to the the error (with debug mode). 

[debuglog.txt](https://github.com/Microsoft/vsts-tasks/files/657609/debuglog.txt)

The full log has a lot of sensitive information and would be difficult to sanitize

**Comment by chshrikh** [comment]
@nambisan  thanks for sharing the logs we will analyse it and get back to you

**Comment by kkellyfr** [comment]
Sorry. I was away a while. Let me know if the logs you have are enough or if I should filter and post my logs too.

**Comment by kkellyfr** [comment]
BTW, a workaround is to use an Azure PowerShell task and write your own PSH to do create the Resource Group. Or use the one generated by Visual Studio which is what I did and it works fine... Bit of a pain though and less clear when reviewing the builds.

FYI, the Azure Resource Group task fails in the same way when used in a Release, as well as a Build. It reports that Resource Group deployment succeeded but failed to get FQDNs. Obvious I suppose but when you have to change your build and all your steps for every Release environment, it is a pain.

**Comment by chshrikh** [comment]
@kkellyfr  can you please confirm if you have selected the option for "Enable Deployment Prerequisites" . If yes can you please deselect it and run the task. Please reffer the below image - 

![image](https://cloud.githubusercontent.com/assets/11972852/21386943/63b7a558-c79b-11e6-8bab-46e4c2ac8304.png)

**Comment by chshrikh** [comment]
@nambisan  it is possible to have a Skype call to debug it further.  You may share your details at RM_Customer_Queries at Microsoft dot com

**Comment by kkellyfr** [comment]
No, the option is not selected.
BTW, my screen does not look exactly like your for some reason. Globally same fields but slightly different layout. I am on VSTS. Are you on TFS?
See below.
![vsts-screenshot](https://cloud.githubusercontent.com/assets/5072899/21400550/ee3c6c6c-c7b0-11e6-84ea-2ec3df075eb8.png)

**Comment by chshrikh** [comment]
@kkellyfr  screen shots are different as we have selected the different action.

I got the issue, you are using the Output . Do you really want Resource Group as output variable.? Does you use this variable in next tasks in your workflow?
Please try to remove the Resource Group variable you specified "azureResourceGroup" your task should pass.

**Comment by nambisan** [comment]
@chshrikh removing the resource group variable solved the issue for me!

**Comment by chshrikh** [comment]
please get back to us, if still need any further assistance

**Comment by nitigupta11** [comment]
I am using azure file copy and getting below error while running the release
##[error]Unable to get FQDN for all resources in ResourceGroup. What is the workaround?

**Comment by Manvibha** [comment]
I am using azure file copy and getting below error while running the release
##[error]Unable to get FQDN for all resources in ResourceGroup. What is the workaround?

**Comment by Farzad-Jalali** [comment]
I got the same problem, is there any workaround ?

**Comment by KrishnaAdityaB** [comment]
Closing this as @Farzad-Jalali already created a new issue #6934

**Comment by mohdshine** [comment]
I am getting error "unable to get FQDN for all resources in ResourceGroup" when trying to copy artifact to Azure Vms, VM doesnt have public ips, how it can fix?

**Comment by TechnologyAnimal** [comment]
I opened up a premier support ticket for this.  Is there documentation somewhere that states public ip addresses are required?  What is the reasoning?  Does it require public DNS?  I am already passing the vm name as a parameter.  Can I pass it something else instead?

I don't want to add public ip addresses to my virtual machines, even if only temporary.  Everything is currently secured in virtual networks with private IP addresses.  We have service endpoints configured to allow communication with storage accounts.

To take a step back, here is the overall goal:
 
1. Provision New VM through VSTS release process
2. After the OS is provisioned on new VM, I want it to download binaries from a storage account and install/configure them
 
I ended up working around this Azure File Copy issue by writing a script to essentially replace the functionality of that step like this:
 
1. Provision VM through VSTS release
2. Grab the private IP address of the newly provisioned VM
3. Update TrustedHost file on VSTS build agent server with newly created VM’s IP
4. Establish a PSSession with newly provisioned VM
5. Invoke-Command against session to download files from storage account and install
 
If I absolutely have to, I will package this up as a custom extension… called Custom Azure File Copy or something… but I would really love to not have to support this for all of the releases that want to download files from a storage account.

Thanks for any help!

**Sanitized Error Message From VSTS Log:**
`2018-07-17T18:59:43.1893363Z ##[debug]throwOnTotalUnavailability: True
2018-07-17T18:59:43.1909238Z ##[debug]Unable to find FQDN for resource ********
2018-07-17T18:59:43.2064909Z ##[debug]System.Management.Automation.RuntimeException: Unable to get FQDN for all resources in ResourceGroup : '********’
2018-07-17T18:59:43.2220338Z ##[debug]Processed: ##vso[task.logissue type=error;code={"Task_Internal_Error":"CopyingToAzureVMFailed"};]
2018-07-17T18:59:43.2220932Z ##[debug][Azure Call]Deleting container: da4b084f-f832-48fb-9205-d99d1366323a in storage account: ********
2018-07-17T18:59:43.3031904Z ##[debug]Removed container 'da4b084f-f832-48fb-9205-d99d1366323a' successfully.
2018-07-17T18:59:43.3050602Z ##[debug][Azure Call]Deleted container: da4b084f-f832-48fb-9205-d99d1366323a in storage account: ********
2018-07-17T18:59:43.3067227Z ##[debug]Completed Azure File Copy Task for Azure VMs Destination
2018-07-17T18:59:43.3108676Z ##[debug]Leaving C:\Agent_02\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.137\AzureFileCopy.ps1.
2018-07-17T18:59:43.3145732Z ##[debug]Caught exception from task script.
2018-07-17T18:59:43.3174657Z ##[debug]Error record:
2018-07-17T18:59:43.3779200Z ##[debug]Unable to get FQDN for all resources in ResourceGroup : ********'
2018-07-17T18:59:43.3791531Z ##[debug]At C:\Agent_02\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.137\Utility.ps1:530 char:17
2018-07-17T18:59:43.3803934Z ##[debug]+ ...             throw (Get-VstsLocString -Key "AFC_MachineNameFromIdError ...
2018-07-17T18:59:43.3816174Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-07-17T18:59:43.3834222Z ##[debug]    + CategoryInfo          : OperationStopped: (Unable to get F... ********':String) [], RuntimeException
2018-07-17T18:59:43.3845463Z ##[debug]    + FullyQualifiedErrorId : Unable to get FQDN for all resources in ResourceGroup : ********'
2018-07-17T18:59:43.3857321Z ##[debug] 
2018-07-17T18:59:43.3875318Z ##[debug]Script stack trace:
2018-07-17T18:59:43.3915302Z ##[debug]at Get-MachineNameFromId, C:\Agent_02\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.137\Utility.ps1: line 530
2018-07-17T18:59:43.3926594Z ##[debug]at Get-AzureRMVMsConnectionDetailsInResourceGroup, C:\Agent_02\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.137\Utility.ps1: line 828
2018-07-17T18:59:43.3937630Z ##[debug]at Get-AzureVMResourcesProperties, C:\Agent_02\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.137\Utility.ps1: line 921
2018-07-17T18:59:43.3949854Z ##[debug]at <ScriptBlock>, C:\Agent_02\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.137\AzureFileCopy.ps1: line 170
2018-07-17T18:59:43.3960788Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-07-17T18:59:43.3971395Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-07-17T18:59:43.3982391Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-07-17T18:59:43.3995263Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-07-17T18:59:43.4012652Z ##[debug]Exception:
2018-07-17T18:59:43.4033068Z ##[debug]System.Management.Automation.RuntimeException: Unable to get FQDN for all resources in ResourceGroup : '********'
2018-07-17T18:59:43.4196064Z ##[error]Unable to get FQDN for all resources in ResourceGroup : '********'
2018-07-17T18:59:43.4196734Z ##[debug]Processed: ##vso[task.logissue type=error]Unable to get FQDN for all resources in ResourceGroup : '********'
2018-07-17T18:59:43.4216099Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-07-17T18:59:43.5004780Z ##[section]Finishing: AzureVMs File Copy
`

**Comment by rajatagrawal-dev** [comment]
@TechnologyAnimal Are you using a private build agent or hosted? If private, where is the machine on which that agent is configured? My understanding is that your build agent machine and target VM might be in the same virtual network. You need public IP to connect from hosted agents to your target VM.

**Comment by miksteri** [comment]
I have set up of VM's behind application gateway and have the same error message. Is current scenario supported? If not, any other ideas of how to copy and/or run scripts in VM's behind application gateway. I guess there should be a way to keep CI/CD -pipelines going on without compromising security.

**Comment by rajatagrawal-dev** [comment]
@miksteri We do not currently support VM's behind Application Gateways. We do support VM's behind Load Balancers.
Since your ask is different from the subject of this thread, can you create a new issue with your requirement so that we can track that enhancement separately?

**Comment by miksteri** [comment]
Sure, I created another issue: https://github.com/Microsoft/azure-pipelines-tasks/issues/9115

**Comment by rajatagrawal-dev** [comment]
@miksteri Sorry for the presumption, but I assumed you were talking about "Azure File Copy task". We don't support Load Balancers in "Powershell on Target Machines" task. This task is for executing powershell on any machine, not specific to VM's on Azure, and so the concept of Load Balancers is not supported here. For this task you can specify comma separated list of machines(IP address or FQDN) which should be accessible from the agent so that we can establish a WinRM connection to them.

Load Balancer support is only there in Azure File Copy task. You can specify which VM behind the load balancer you wish to copy the files to using the "Filter Criteria" input in the task. We support name-based and tag-based filtering.

**Comment by miksteri** [comment]
Ok, thanks for the response.

Should I create another issue for "Powershell on Target Machines" -task support for load balancer? Actually if it would be possible to define port to be used that would solve this issue. So if port could be defined for the task then in load balancer it would be possible to direct certain ports to certain VM's.

**Comment by rajatagrawal-dev** [comment]
You can specify the port currently. In the Machines input, you can specify the VM address like IP:port or FQDN:port.
For example if your load balancer IP is 123.456.7.8 and you have mapped the port 1234 on your load balancer to the port 5986 on your target VM, then specify 123.456.7.8:1234 in the Machines input.

Please click on the 'i' button next to the "Machines" input in the task for info.

**Comment by miksteri** [comment]
> @miksteri We do not currently support VM's behind Application Gateways. We do support VM's behind Load Balancers.

I'm now trying the load balancer, how should I configure Load Balancer for "Azure File Copy task" to work? I can get it to work for 1 VM if I create inbound NAT rule for that port (5986), but I cannot create the same port rule for all VM's.

**Comment by rajatagrawal-dev** [comment]
@miksteri We read all NAT rules of the load balancer. So if you have your VM's 5986 port mapped to some publicly accessible port on load balancer, it should work.

**Comment by ChrisFg** [comment]
I’m getting the error: Unable to get FQDN for all resources in ResourceGroup : 'KDY-ALGOR-VMS-RG' 

In an azure devOps, release pipeline task, azure file copy, fails to copy dot net console app files, from an azure rm storage account to an existing c:\temp directory on the target azure vm, tpt-ar-20. 

The azure vm tpt-ar-20, has public ip address, its firewall is open inbound for port 5986, and the winRM listener is configured. The vm nic has an inbound network security group with port 5986, inbound open.  

WinRM access from a desktop to the vm tpt-ar-20, using the powershell method here 
https://blogs.technet.microsoft.com/uktechnet/2016/02/11/configuring-winrm-over-https-to-enable-powershell-remoting/ 
works when addressing both the public ip address, and the azure internal ip address, accessed over my p2s vpn connection.  There is no application gateway or load balancer. 

Automating the delivery of this app is important to us.

Any help on what I’m missing is appreciated.
Thanks

[Unable to get FQDN.docx](https://github.com/Microsoft/azure-pipelines-tasks/files/2935768/Unable.to.get.FQDN.docx)
[tasklog_6_tail_anon.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2935772/tasklog_6_tail_anon.txt)

**Comment by ChrisFg** [comment]
Adding pipeline and vm info. 
[Unable to get FQDN.docx](https://github.com/Microsoft/azure-pipelines-tasks/files/2935850/Unable.to.get.FQDN.docx)

**Comment by niadak** [comment]
@ChrisFg, Can you please use "Deployment Group" feature for your scenario. In this model we dont have WinRM or Remote Deployment dependency and deployment will be done in Pull based model. For more details refer to below documents.

https://devblogs.microsoft.com/devops/deployment-groups/
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops
