### ISSUE TITLE
##vso[artifact.upload] doesn't work properly when container folder is "Logs"

### ISSUE THREAD

**Issue by AlexHimself** [Microsoft/azure-pipelines-tasks#3354]
It appears "Logs" is a **reserved/special** containerfolder name or something.  Using this code:

```
#This does not let me click "Explore" online
Write-Host "##vso[artifact.upload containerfolder=Logs;artifactname=MyLog;]C:\TEMP\TempOut.txt"

#This works correctly
Write-Host "##vso[artifact.upload containerfolder=Logs2;artifactname=MyLog2;]C:\TEMP\TempOut.txt"
```

I'm able to upload to it, but when I try and click "Explore", it shows a gray (disabled) window.

![image](https://cloud.githubusercontent.com/assets/10466466/21628627/b2faf126-d1d5-11e6-92cf-22a678a74b17.png)

However, if I click download, it has random files in GUID folders in the ZIP.

![image](https://cloud.githubusercontent.com/assets/10466466/21628649/e0ba2b18-d1d5-11e6-8f66-562188c0ef6e.png)

If I look at the other example line that works (MyLog2) it appears correct:

![image](https://cloud.githubusercontent.com/assets/10466466/21628694/354286c6-d1d6-11e6-81e9-9f6fa3c0834a.png)

**Comment by bryanmacfarlane** [comment]
This is likely more of an agent question.  Adding Ting to confirm.

**Comment by madhurig** [comment]
This is an old issue and has already been addressed. You should be able to browse the logs/artifacts from either upload command now. Let us know if you still see any issues.

Thanks,
Madhuri
