### ISSUE TITLE
Gulp task is not using gulp-cli but gulp

### ISSUE THREAD

**Issue by Saturate** [Microsoft/azure-pipelines-tasks#3890]
The task should be using the node module `gulp-cli` and not `gulp`. https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

This is the old way of invoking gulp, and does not work with newer versions of gulp.

The default configuration of the gulp runner can be found here: https://github.com/Microsoft/vsts-tasks/blob/c932e92b4db984e06dcec9d6537bd9ca2a0de72c/Tasks/Gulp/task.json#L78-L84

It would be okay to use the locally install gulp as a default, or have a flag to make this the priority. But there should be no global gulp module.

**Comment by wawyed** [comment]
Hi, is this someone that can be looked at. We are trying to update to gulp4 and we have to go an manually uninstall/update the global version of gulp on each build task...

Thanks.

**Comment by scott-lin** [comment]
@wawyed, I'm running into the same and looking for a workaround until the fix is provided. How did you "uninstall/update the global version of gulp" in the build definition?

+1 for looking at this issue sooner than later.

**Comment by moswald** [comment]
We have an internal bug filed for fixing this. Gulp should be using v4 in the next few releases.

In the meantime, the next Azure DevOps release will include a new version of the Gulp task that will let you supply a path to a custom gulp.

**Comment by scott-lin** [comment]
> In the meantime, the next Azure DevOps release will include a new version of the Gulp task that will let you supply a path to a custom gulp.

Just for completeness/reference, see https://github.com/Microsoft/azure-pipelines-tasks/issues/7839 regarding Matt's comment.

Thanks, Matt!
