### ISSUE TITLE
VS build task v1.* builds only first path in composite wildcard, ignores rest

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/azure-pipelines-tasks#4100]
If Solution parameters contains composite wildcard path, i.e. multiple paths separated by semicolon, such as `**\Folder1\*.sln;Folder2\**\*.sln`, only the first path is built, rest are ignored.

Sample: https://microsoft.visualstudio.com/defaultcollection/Universal%20Store/Universal%20Store%20Team/_build/index?buildId=4521629&_a=summary

**Comment by ericsciple** [comment]
my guess is this is due to how filepath inputs work. the first path is getting prefixed with $(build.sourcesdirectory), but the second is not. may need to change the input value to: `**\Folder1\*sln;$(Build.SourcesDirectory)\Folder2\**\*.sln`

**Comment by abatishchev** [comment]
Will try, thanks!
Can the input be parsed and appended/expanded automatically?

**Comment by ericsciple** [comment]
Good point. I dont know exactly what it gets rooted with today. I believe it's current directory, but I'm not sure what that would be set to. If it's implicitly getting rooted with something nonsensical (like the task folder), then I'll change consider changing it.

**Comment by abatishchev** [comment]
The biggest problem I would say is that it doesn't error out about rest paths weren't found or whatnot but just swallows/ignores. It makes me thinking it the task's issue/defect.

**Comment by ericsciple** [comment]
The error isn't specific to the first pattern. The error is if nothing is found at all (tries all patterns).

**Comment by abatishchev** [comment]
But why first path may be relative and the rest must be absolute? This inconsistency is non-intuitive and very confusing.
