### ISSUE TITLE
Azure VM File Copy fails with mangled error message

### ISSUE THREAD

**Issue by martijnhoekstra** [Microsoft/azure-pipelines-tasks#4451]
Azure VM File Copy with `Enable Copy Prerequisites` fails with a mangled error message.  A transcript of the errors in the log is pasted below.

Edit: For clarification, the `\n`'s are present as text in the error message

> 2017-06-02T09:45:06.7649845Z ##[error], ParameterB \n   indingException\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell \n   .Commands.WriteVerboseCommand\n \nWSManFault\n    Message = Access is denied. \n\nError number:  -2147024891 0x80070005\nAccess is denied. \nWSManFault\n    Message = Access is denied. \n\nError number:  -2147024891 0x80070005\nAccess is denied. };]
>2017-06-02T09:45:07.2999838Z ##[error]Failed to enable copy prerequisites. Setting the custom script extension 'WinRMCustomScriptExtension' for virtual machine 'myvmname' failed with error : WSManFault\n    Message = Access is denied. \n\nError number:  -2147024891 0x80070005\nAccess is denied. \nWSManFault\n    Message = Access is denied. \n\nError number:  -2147024891 0x80070005\nAccess is denied. \nWrite-Verbose : A positional parameter cannot be found that accepts argument '+\n'.\nAt C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\Downloads\0\\nConfigureWinRM.ps1:37 char:22\n+         Write-Verbose <<<<  -Verbose "Exception while deleting the listener: \n" + $_.Exception.Message\n    + CategoryInfo          : InvalidArgument: (:) [Write-Verbose], ParameterB \n   indingException\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell \n   .Commands.WriteVerboseCommand\n \nWSManFault\n    Message = Access is denied. \n\nError number:  -2147024891 0x80070005\nAccess is denied. \nWSManFault\n    Message = Access is denied. \n\nError number:  -2147024891 0x80070005\nAccess is denied. 
>2017-06-02T09:45:07.3619844Z ##[section]Finishing: AzureVMs File Copy

**Comment by martijnhoekstra** [comment]
The cause seems to be not having some minimum version of Powershell on the VM. Upgrading to Powershell 2 to Powershell 4 works around the issue.

**Comment by chrisrpatterson** [comment]
@RoopeshNair Can we either document or somehow update this task to indicate that it requires a minimum level of powershell on the remote machine?

**Comment by RoopeshNair** [comment]
@kmkumaran can you take a look into this one? Is this really PowerShell version issue? if yes, we can add it our log/validation for pre-req version? To me it looks like incorrect password to the VM is causing the issue

**Comment by chshrikh** [comment]
martijnhoekstra could you let us know which os you are using or which image you used to create the vm

**Comment by chshrikh** [comment]
@RoopeshNair  yes its a powershell version on target vm. With server 2008 r2 vm it comes with PS2 version and "Access is denied." error comes. One need to update this with PS3 version

**Comment by martijnhoekstra** [comment]
@chshrikh It was indeed a 2008 r2 vm.

**Comment by Ajay-MS** [comment]
Updated documentation regarding the prerequisite version of PS on target VM. 

PR - https://github.com/Microsoft/azure-pipelines-tasks/pull/8604
