### ISSUE TITLE
##[warning]Unable to index one or more source files for symbols file

### ISSUE THREAD

**Issue by kyurthich** [microsoft/azure-pipelines-tasks#4672]
2017-06-28T21:13:59.4752799Z ##[warning]Unable to index one or more source files for symbols file 'D:\agent\_work\4\b\bin\AjaxControlToolkit.pdb'.
2017-06-28T21:13:59.6159079Z ##[warning]Unable to index one or more source files for symbols file 'D:\agent\_work\4\b\bin\App_Code.pdb'.

etc... 

Every pdb throws the same error.

Below is the full debug of the issue for a single pdb:
[index_pdb_debug_log.txt](https://github.com/Microsoft/vsts-tasks/files/1110272/index_pdb_debug_log.txt)

Json file from the version on our build server attached below.
[task.json.txt](https://github.com/Microsoft/vsts-tasks/files/1110265/task.json.txt)

Any help is greatly appreciated.

**Comment by kyurthich** [comment]
Also it threw this when trying to add to the store 

2017-06-28T21:23:43.9764153Z ##[command]"D:\agent\externals\symstore\symstore.exe" add /f "@D:\agent\_work\_temp\tmpF09B.tmp" /s "\\x-xxxx-vsts\symbols\" /t "xxxx_DevCIBuild" /v "xxxx_DevCIBuild_20170628.10"
2017-06-28T21:23:44.0232965Z ##[debug]SYMSTORE ERROR: Class: Syntax. Desc: '/t <product>' is required with this add type.

**Comment by japj** [comment]
Any update on this? 

I seem to have this same problem when I tried enabling indexing I get "Unable to index one or more source files for symbols file"

**Comment by japj** [comment]
We are using Version 1.0.36 of the task

**Comment by kyurthich** [comment]
I still have the error as well.

**Comment by jerickmsft** [comment]
@arunkm I think you were adding some diagnostics for the error "One or more source files not under sources root directory" since it's super unhelpful?

**Comment by kyurthich** [comment]
This is a recent view of what we see on the build:

![image](https://user-images.githubusercontent.com/3331097/32626377-24ec2ebe-c55d-11e7-8546-355f5aca891d.png)

**Comment by arunkm** [comment]
The log you pasted has the error details:
```
One or more source files not under sources root directory: D:\agent\_work\4\s\
Paths: f:\TeamCity\buildAgent\work\80acd78aa4c25314\Server\AjaxControlToolkit\Accordion\Accordion.cs
```
The source files used for compilation is under `f:\TeamCity\buildAgent\work\80acd78aa4c25314\Server\AjaxControlToolkit` where as the source indexing works only if the sources are under `D:\agent\_work\4\s` which is required for it to wire up  back to the source control.

In this case, How does you MsBuild project file select the source, does the source not same as the one set by the build definition's "Get sources" step in the beginning ?

**Comment by japj** [comment]
I will need to look at our detailed logs on Monday, but I think some files (e.g. AssemblyInfo related) might for example be generated out of the source tree for us.

Just to be clear, if it can not find one specific file, will/should that prevent the indexing of the rest and not update the PDB file? I understand the warning, but it might be preferable to have the PDB file updated with whatever it did find and that does not seem to happen currently in our case.

Also, I saw that VS2017 Update 5 will have the option to embed source files in the PDB (e.g. for generated files that are not in source control). Is/will this agent task be "compatible" with that embedded sources option?

**Comment by jerickmsft** [comment]
@japj Are you sure the file isn't getting source indexed otherwise? If I recall correctly, it ought to.

@arunkm I wonder if we should remove this warning altogether as it seems to cause more confusion than clarity or remediation.  Specifically the case where it's not under the source tree as those, by definition, cannot be source indexed for srcsrv.

**Comment by tmat** [comment]
@japj Re compatibility of embedded sources and source server information: Yes, these features are compatible. In fact we expect both of them be used in a common scenario: the files that are tracked by the source control would be linked to the source control system and the remaining files (e.g. generated during build) would be embedded.

@jerickmsft I agree it would be best to not report warnings for files that are not tracked by the source control.

**Comment by japj** [comment]
@jerickmsft I can now confirm that the source indexing works ok for us.
I think the warning was one of the things that threw me off track.
I thought I verified the pdb contents before and didn't see the TFS SRV sections, but that seems to be ok now (and debugging into code correctly retrieves the code from source control).

For C++ targets, we typically see references to missing source files in f:\dd\vctools\crt\vcruntime, etc.

There are also some autogenerated files +  interface files from other SDKs (e.g. boost).
Those might be 'solvable' with the upcoming /embed option in VS2017U5.

**Comment by elbatk** [comment]
Hi everyone - I'm doing some cleanup of old issues in this GitHub repo and I'm wondering if this problem is still an issue. I'm going to close it for tracking purposes but please feel free to reach out and comment if this is still an issue so I can route appropriately, thank you!
