### ISSUE TITLE
PublishBuildArtifacts isn't able to process a file path inf "FileShare" mode

### ISSUE THREAD

**Issue by trinhpham** [Microsoft/azure-pipelines-tasks#4777]
The first parameter is described that it allows "Folder or file path to publish".
But when I input a file path, the step fails to execute.
Looking to log file, I found that the call to robocopy of this task can't handle filepath because $Source is always be treated as a folder.
`robocopy.exe /E /COPY:DA /NP /R:3 /MT:$ParallelCount $Source $Target * `

Any idea to fix it on my on-premises TFS?

**Comment by ericsciple** [comment]
It looks like it works when publishing to the server but has never worked for file share. Workaround is to copy to a folder and then publish the folder. You can even hardlink it if you're concerned about the extra copy time.

**Comment by bergmeister** [comment]
@ericsciple  This problem still exists, when trying to publish just one file to a file share, it also publishes empty folders from the path where the file sits. The workaround is not very satisfying, this is the job of the task, otherwise I might as well script a copy command myself.

**Comment by alexmullans** [comment]
@mitchdenny is this something we can fix in the new Pipeline Artifacts task?

**Comment by mitchdenny** [comment]
We'll probably carry the same limitation across to Pipeline Artifacts - this is the Build Artifacts task.

**Comment by alexmullans** [comment]
OK, I'm closing this as WF for now. Please see the workaround posted by @ericsciple.
