### ISSUE TITLE
Windows Machine File Copy task fails - System error 53 has occurred. the network path was not found

### ISSUE THREAD

**Issue by lukewis** [microsoft/azure-pipelines-tasks#4782]
This is very similar to issue #3761 except that i **AM** using a private agent.  It seems that the task is failing because I'm trying to create a remote directory that doesn't yet exist.  Two things I've tried:

1. Use a unc path \\<remotemachineIP>\remotePath\newFolder (this is what produces the error above)
2. Use a remote-path/admin share:  G:\remotepath\newFolder (where G is a drive that is understood by the remote machine, and newFolder doesn't yet exist) - this results in an "Access Denied" error

Neither of these options seems to work.  Can you help point me in the right direction?  What is the correct way to copy files to a new subdirectory on a remote machine using a LOCAL (non AD) admin account?  I just found that this is seemingly the same as #3765.  You can consider this another vote for handling that scenario.  For me, I want to be able to deploy to a unique subfolder based on the build number.

**Comment by Fizcko** [comment]
Hi,

An example of configuration regarding the following scenario : 

The "newFolder" to copy is alone on the agent where your source code files are downloaded. For example: c:\agent\_work\1\s (System.DefaultWorkingDirectory varaible).

You have to setup your task like this : 

Source : $(System.DefaultWorkingDirectory)
Machine : Computer_Name
Admin Login : Computer_Name\Username
Password : password
Destination Folder : G:\remotepath

**Comment by KrishnaAdityaB** [comment]
@lukewis the input that @Fizcko suggested above should work. Which you tried and got Access Denied error (your approach 2).
Make sure the local user on the remote machine has admin rights. Find more details below.

**Scenario**
Let's say you have two machines _AgentMachine_ and _TargetMachine_. 
You want to copy a folder from _AgentMachine_ to _TargetMachine_. 
The source for copying is on _AgentMachine_ which is $(System.DefaultWorkingDirectory).
The destination is _D:\TargetDirectory_ on _TargetMachine_.
You want to achieve this with a local account name _User1_ on _TargetMachine_.

**How the task works** 
`if destination path format is D:\TargetDirectory { re-construct the path as \\targetMachine\D$\TargetDirectory }`
After this, it does `robocopy <source> <destination>`.
Robocopy automatically creates the <destination> directory if it doesn't exist.
Robocopy is executed with the credentials that are provided in the task as input

**Approach 1**
If you want to take a share path _\\\\TargetMachine\TargetDirectory_
- make sure that share is created
- make sure you gave **write access** to that share to the account _TargetMachine\User1_

**Approach 2**
If you want to use absolute path _D:\TargetDirectory_
- make sure the account _TargetMachine\User1_ is admin on _TargetMachine_. 
As I mentioned above, this path will be re-constructed as _\\\\TargetMachine\D$\TargetDirectory_. This type of shares are called [Administrative Shares](https://en.wikipedia.org/wiki/Administrative_share). Non admin users can't access them. 
Further, non domain users may face UAC dialogue. For Release automation to not get blocked, you have to disable UACs.

If the above solutions don't work - please reply. We will have a skype call.

**Comment by lukewis** [comment]
@KrishnaAdityaB thanks for the response!  The target machine that I was copying to just died today so it will likely take me a few days to stand up a new one and retry things using your sugestions.

**Comment by KrishnaAdityaB** [comment]
After I tested the scenario, I am closing this issue. Please re-open if above solution didn't work for you.

**Comment by lukewis** [comment]
I apologize for the delay, but I was finally able to stand up a new machine to test this scenario.  I'm experiencing similar issues with both solutions you described.
Senario 1:  I'm now receiving error 55 which states that "The specified network resource or device is no longer available."
Scenario 2: I'm still receiving an "Access Denied" error
I"m available around 4:30 Eastern if you'd like to do a Skype call.  I would re-open this issue, but I"m not sure how.

**Comment by selwyncerejo** [comment]
Hi @KrishnaAdityaB 
I am using 
Approach 2
If you want to use absolute path D:\TargetDirectory

make sure the account TargetMachine\User1 is admin on TargetMachine.
As I mentioned above, this path will be re-constructed as \\TargetMachine\D$\TargetDirectory. This type of shares are called Administrative Shares. Non admin users can't access them.
Further, non domain users may face UAC dialogue. For Release automation to not get blocked, you have to disable UACs.

as you have mentioned but I am still getting the error as access denied. Not sure about what is UAC is 

Thanks,
Selwyn.

**Comment by yen9912** [comment]
I had the same problem ("Access Denied" error) with Approach 2 (Administrative Shares).
This has to do with the Azure Pipelines agent service and the logon account configured.
![image](https://user-images.githubusercontent.com/31061693/57819219-d3ade980-77ca-11e9-940b-3bf18adf4119.png)

For some reason, using the default "NT AUTHORITY\SYSTEM" account will produce "Access Denied" errors using absolute paths.
I changed the logon account to local admin and deployment worked
![image](https://user-images.githubusercontent.com/31061693/57819302-2edfdc00-77cb-11e9-8acf-b0d62c392ef0.png)

**Comment by KrishnaAdityaB** [comment]
@kmkumaran

**Comment by 20shivangi** [comment]
@yen9912 
Thanks for details and adding more data.
