### ISSUE TITLE
Android Signing Task should use apksigner where possible, and not jarsigner.

### ISSUE THREAD

**Issue by topgenorth** [Microsoft/azure-pipelines-tasks#4783]
Looking at the [source code for the Android Signing task](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AndroidSigning/androidsigning.ts#L20), and it seems to be using the older `jarsigner` from the JDK to sign an APK.  

`apksigner` was introduced in the Android Build tools v24.0.3. For future compatibility the VSTS build task should use `apksigner` where available, falling back to `jarsigner` when using older versions of the Android Build Tools.

See:
* [Manually Signing the APK](https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/publishing_an_application/part_2_-_signing_the_android_application_package/manually-signing-the-apk/)
* [apksigner](https://developer.android.com/studio/command-line/apksigner.html)
* [Build and Sign your App from the Command Line](https://developer.android.com/studio/publish/app-signing.html#signing-manually)

**Comment by klyubin** [comment]
FYI Android SDK Build Tools v26.0.0 got shipped without apksigner by accident. See https://github.com/bazelbuild/bazel/issues/3258 and https://issuetracker.google.com/issues/62696222.

**Comment by johnsabr** [comment]
This open issue is the top result (for me) when I search for "vsts apksigner". If anyone else stumbles on this issue, per the [Manually signing APK doc](https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/publishing_an_application/part_2_-_signing_the_android_application_package/manually-signing-the-apk/#Zipalign_the_APK), you can use the recommended apksigner with a PowerShell task.

```powershell
# Use zipalign and apksigner on the Android APK.
# Environment variables required: BUILD_SOURCESDIRECTORY, ANDROID_HOME
# Parameters required:
# -InputApk <Path to input APK from solution directory>
# -OutputApk <Path to where output APK should go>
# -KeystorePath <Path to keystore from solution directory>
# -ApkSignerKsAlias <Alias for key store>
# -ApkSignerKsPass <Password for key store - use a secret build variable>
# -ApkSignerKeyPass <Password for key in key store - use a secret build variable>
param($InputApk, $OutputApk, $KeystorePath, $ApkSignerKsAlias, $ApkSignerKsPass, $ApkSignerKeyPass)

if (!$InputApk) {
	throw "Parameter InputApk is not set"
} elseif (!$OutputApk) {
	throw "Parameter OutputApk is not set"
} elseif (!$KeystorePath) {
	throw "Parameter KeystorePath is not set"
} elseif (!$ApkSignerKsAlias) {
	throw "Parameter ApkSignerKsAlias is not set"
} elseif (!$ApkSignerKsPass) {
	throw "Parameter ApkSignerKsPass is not set"
} elseif (!$ApkSignerKeyPass) {
	throw "Parameter ApkSignerKeyPass is not set"
}

$sdk = $Env:ANDROID_HOME
$src = $Env:BUILD_SOURCESDIRECTORY

# Get for instance, /build-tools/27.0.3/zipalign.exe and /build-tools/27.0.3/apksigner.bat
# Uses latest build tools version; 27.0.3 as of 2018-02-20
$buildtools = (ls -Path "$sdk/build-tools" | sort -Descending | select -First 1 | select FullName)[0].FullName
$zipalign = "$buildtools/zipalign"
$apksigner = "$buildtools/apksigner"

# Align APK
& $zipalign "-f" "-v" "4" "$src/$InputApk" $OutputApk
if ($LASTEXITCODE -ne 0) {
	throw "Error: zipalign failed"
} else {
	echo "Finished alignment of $OutputApk"
}

# Sign APK
& $apksigner "sign" "--ks" "$src/$KeystorePath" "--ks-key-alias" $ApkSignerKsAlias "--ks-pass" "pass:$ApkSignerKsPass" "--key-pass" "pass:$ApkSignerKeyPass" $OutputApk
if ($LASTEXITCODE -ne 0) {
	throw "Error: apksigner failed"
} else {
	echo "Finished signing of $OutputApk"
}
```

**Comment by madhurig** [comment]
Closing since the task has been updated to apksigner.
