### ISSUE TITLE
##vso[task.setprogress] not emitting message output

### ISSUE THREAD

**Issue by logicbomb421** [Microsoft/azure-pipelines-tasks#4838]
First off, this appears to be similar to [issue 4006](https://github.com/Microsoft/vsts-tasks/issues/4006), however this issue doesn't appear to be specific to releases as 4006 seems to indicate.

Essentially I'm trying to use `##vso[task.setprogress]` to provide a message to TFS for long-running tasks. However, it does not appear the message is ever passed to TFS. When i provide a number for the `value` param, I _do_ see the percentage update in the tree of tasks along the left side of the build/release, however no message ever appears.

#### To Reproduce:

1. Create a build/release with a Powershell task
2. Set the task to Inline and add the vso command
3. Run the build

If you provide a percentage for `value`, you should see it appear next to the task, however no message is ever logged to the console.

For reference, here is a small test script I've been running this with:

	Write-Host "##vso[task.setprogress value=5;]some text 0";
	Start-Sleep -Seconds 3
	Write-Host "##vso[task.setprogress value=25;]some text 1";
	Start-Sleep -Seconds 3
	Write-Host "##vso[task.setprogress value=50;]some text 2";
	Start-Sleep -Seconds 3
	Write-Host "##vso[task.setprogress value=95;]some text 3";

From the above, the 'some text x' messages are never received in the console.

I have tried this with `Write-Output`, as well as with no `value` param (syntax for such: `##vso[task.setprogress]some text 3`), to no avail. Perhaps I'm missing something here?

For reference, I am running TFS 2017.u1 OnPrem (v15.112.26307.0), which is hosted on a Windows Server 2012 R2 box. I don't use XAML builds at all, this is all through vNext.

Please let me know if I should provide more context. Thanks!

**Comment by totkeks** [comment]
Got the same issue on VSTS. The percentage update is updated in the step / task overview in the "logs" tab of the release. But the message is neither in the detailed log nor somewhere else.

**Comment by bryanmacfarlane** [comment]
This should be in azure-pipelines-agent repo
