### ISSUE TITLE
[ServiceFabricDeploy Task] Documentation for 'Overwrite behavior'?

### ISSUE THREAD

**Issue by degant** [Microsoft/azure-pipelines-tasks#4842]
For the Service Fabric deploy task, where can I find documentation on Overwrite Behavior and other properties in the Advanced and Upgrade Settings sections. Overwrite Behavior provides 3 options _'Always', 'Never' and 'SameAppTypeAndVersion'_. We have tried the options but unable to figure out exactly what they are doing. Appreciate if someone can share what the 3 options mean.

Couldn't find any documentation here: https://www.visualstudio.com/en-us/docs/build/steps/deploy/service-fabric-deploy

![image](https://user-images.githubusercontent.com/6065982/28457432-becd3e7e-6e23-11e7-8fc2-996285addd1f.png)

**Comment by degant** [comment]
@bryanmacfarlane shouldn't the tag be `SubArea: ServiceFabric` instead?

**Comment by bishal-pdMSFT** [comment]
@RoopeshNair , please look at this doc bug.

**Comment by bishal-pdMSFT** [comment]
@RoopeshNair , are you planning to take this fix?

**Comment by bishal-pdMSFT** [comment]
Closing old issue.

**Comment by brandonchastain** [comment]
??? There was no fix for this. Why close it simply because it's old? I'm still looking for documentation on what the heck this setting means.

**Comment by sachinma** [comment]
Reopening it to track it.

**Comment by hiyadav** [comment]
Hey @brandonchastain, hope the below description will help, we will update the task input's information button with the same usage information.

Overwrite Behavior: when upgrades are not configured and an application exists in the cluster with the same name exists, then the 3 actions are available=> Never, Always, SameAppTypeAndVersion.
    Never will not remove the existing application. This is the default behavior.
    Always will remove the existing application even if its Application type and Version is different from the application being created.
    SameAppTypeAndVersion will remove the existing application only if its Application type and Version is same as the application being created.

**Comment by hiyadav** [comment]
@brandonchastain does this help ?

**Comment by bishal-pdMSFT** [comment]
Some comments:
1. When upgrade is not configured ...
2. Typo: an application with same name already exists in the cluster ~~with the same name exists~~
3. Use 'Application' instead of application everywhere as you have used 'Application type' and 'Version'

**Comment by hiyadav** [comment]
We have updated `Overwrite Behavior` help message in the task, in the referenced PR. Hence closing the issue.

**Comment by brandonchastain** [comment]
Thank you!! This helps a lot!
