### ISSUE TITLE
Artifact name using expressions or variables

### ISSUE THREAD

**Issue by zaiboot** [microsoft/azure-pipelines-tasks#4871]
I want to be able to create an artifact with a dynamic name, like: artifact-{dd.MM.yyyy} will become artifact artifact-01.01.2017 or something like that.  Is that possible or will be supported in a near future?

**Comment by zaiboot** [comment]
Will post a more detailed escenario once as soon as possible

**Comment by zaiboot** [comment]
More detailed scenario.

I am using VSTS online in: https://*.visualstudio.com/<project>/_build and one of my build definitions, I want to set the following pattern:

![image](https://user-images.githubusercontent.com/10767087/28952164-a958be92-788c-11e7-8ede-fc83ed385d9b.png)
So this: drop-{dd.MM.yyyy} will become in: drop-08.24.2017 I dont know if there is such functionality, however I really dont know how to set it up correctly.
I was able to do that on Team City relatively easy: https://confluence.jetbrains.com/display/TCD9/Configuring+General+Settings

Hope this helps a little.

Thanks

**Comment by Lovakumar** [comment]
This is related to process parameters.

**Comment by Lovakumar** [comment]
Closing outdated issue. @zaiboot if you require this support, please re-activate it with the following details.

1. How are using "Artifact Name" to really associate an artifact. Are you using ##vso command OR rest API.
2. Share sample build for repro.
