### ISSUE TITLE
##vso[artifact.associate] with type gitref is not working

### ISSUE THREAD

**Issue by slon872** [microsoft/azure-pipelines-tasks#4907]
Unable to process command '##vso[artifact.associate type=gitref;artifactname=BuildLabel;]refs/tags/Sandbox-master_16.0.20008.0' successfully. Please reference documentaion (http://go.microsoft.com/fwlink/?LinkId=817296)
Can't infer artifact type from artifact location: refs/tags/Sandbox-master_16.0.20008.0.

after changing type= to artifacttype=

Unable to process command '##vso[artifact.associate artifacttype=gitref;artifactname=BuildLabel;]refs/tags/Sandbox-master_16.0.20008.0' successfully. Please reference documentaion (http://go.microsoft.com/fwlink/?LinkId=817296)
Unsupport artifact location: refs/tags/Sandbox-master_16.0.20008.0

Please document the correct syntax.

**Comment by reinaldoarrosi** [comment]
Any update on this issue?
I'm trying to associate a manually created TFVC label (using `artifacttype=tfvclabel`) an I have the same error.

**Comment by damccorm** [comment]
Closing as this has gone stale. It looks like the issue probably belongs to https://github.com/microsoft/azure-pipelines-agent anyways
