### ISSUE TITLE
Azure Key Vault - Support for wildcard filter

### ISSUE THREAD

**Issue by tomkerkhove** [Microsoft/azure-pipelines-tasks#4990]
As of today you have 2 options to filter the secrets:

- Use `*` to get all the secrets
- Use `<secret-name>` to get one specific secret

However, it would be nice to be able to use a filter sucht as `Api-*` that will get all the secrets that start with `Api-` such as `Api-DeploymentPassword`

**Comment by N-Usha** [comment]
Hi Tom, As discussed offline, we have added this requirement to our backlog and will prioritize it appropriately.

**Comment by tomkerkhove** [comment]
Any updates on this?

**Comment by lovakumar** [comment]
Hi Tom, This is still in our backlog. I will check internally with our team and get back on this thread.

**Comment by lovakumar** [comment]
Hi Tom, We discussed this internally and azure key-vault does not have an API for supporting wild cards in secrets lookup and hence we have not done it.

**Comment by tomkerkhove** [comment]
That's correct but you could list all secrets behind the scenes, apply the wildcard on top of it and only fetch the values for the secrets that match?

**Comment by lovakumar** [comment]
That approach is not optimal and adds overhead to key vault APIs.

**Comment by RoopeshNair** [comment]
@tomkerkhove - . This has risk of perf degradation without appropriate API support from Azure. We are not planning to pick this up anytime soon. I'm closing this as a suggestion.

**Comment by drewyh999** [comment]
Any plan to pick this up soon as we are now in 2024? Would be nice to have :)

**Comment by kaiyuanlim** [comment]
It is 2024 now, any updates?

**Comment by mite1111** [comment]
Is there a plan to pick this up?
