### ISSUE TITLE
SqlDacpacDeploymentOnMachineGroup System.Debug does not show all output.

### ISSUE THREAD

**Issue by jebbissononehsn** [Microsoft/azure-pipelines-tasks#5011]
When using System.Debug = True, the output returned does not contain the output of sqlpackage making it appear as though the step that executes the package does nothing.
This was only tested on a machine running PowerShell 4 and I noticed there was a split in the logic where sqlpackage is executed so it could be only a powershell 4 or lower issue.

It would be nice to see all the package output when debug is on so that problems with the deployment can be better diagnosed and just general diagnostics as to what occurred.
There are a lot of things that can go wrong and some of those do not throw exceptions so we would have no way to diagnosis except to run the command directly or to modify the task's powershell scripts to return the output.

When System.Debug is False it would be nice to show the sql package output as well or some kind of indication the package executed and something happened as currently it appears to show nothing at all in the log except what the agent puts in.

**Comment by vincentdass** [comment]
Apologies for late response. Debug statements and success messages will be added to the task.
