### ISSUE TITLE
Command Line task does not output command

### ISSUE THREAD

**Issue by brentnewbury** [Microsoft/azure-pipelines-tasks#5022]
The Command Line 2.0 task no longer outputs the command being executed, which differs from 1.0. This causes a problem for us as it makes it difficult to determine what was executed when looking at the build logs.

**Comment by ericsciple** [comment]
it sounds like you may want to add `echo on` to the top of your script

**Comment by bryanmacfarlane** [comment]
@ericsciple - are we saying it's required that everyone at that at the top to get the transparency?

**Comment by chrisrpatterson** [comment]
Another option would be to turn echo on as part of our script generation and then if people want to opt out they can simply put echo off at the top of their script.

**Comment by ericsciple** [comment]
fixing with this PR https://github.com/Microsoft/vsts-tasks/pull/5900
