### ISSUE TITLE
Deploy Service Fabric cluster with AAD authentication

### ISSUE THREAD

**Issue by chaholl** [Microsoft/azure-pipelines-tasks#5025]
As far as I can tell, as part of a release management process, it's impossible to deploy a Service Fabric cluster with AAD authentication. There are two reasons for this:

Firstly, configuring AAD requires the `tenantId` for the tenancy that hosts the AD applications. As far as I can tell there's no way to get this value via PowerShell on the build server. Normally it would be easily obtained via `Get-AzureRmContext` or even `Get-AzureRmTenant `but none of that works. The values are always null.

Secondly, **AzureRM.ServiceFabric** is not available on the build server. It can be installed using:
```
Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
Install-Module -Name AzureRM.ServiceFabric -Force -Verbose -Scope CurrentUser
Import-Module -Name AzureRM.ServiceFabric -Force -Verbose -Scope Global
```
but that doesn't work properly presumably due to some conflicts with existing stuff.

I'm sure I can't be the only person to come up against this problem. Am I missing something or is this a known issue?

**Comment by bishal-pdMSFT** [comment]
@chaholl Are you using "Service fabric deploy" task? https://www.visualstudio.com/en-us/docs/build/steps/deploy/service-fabric-deploy

**Comment by chaholl** [comment]
My problem isn't with deploying an app to an existing cluster, it's with actually creating the cluster in the first place. The **Service Fabric Deploy** task will only allow me to deploy an app to an existing cluster.

To give a bit more background: I have various DevOps PowerShell scripts to provision all elements of my solution including a Service Fabric cluster. In an ideal world, I'd run them as part of Release Management to spin up a new, clean, test environment. I can't do that for Service Fabric.

So I guess my problem is with the 'Azure PowerShell' task

**Comment by bishal-pdMSFT** [comment]
Adding @kmkumaran to comment why `Get-AzureRmContext` or `Get-AzureRmTenant` work when using within Azure powershell task.
@chaholl Can't you use "Azure Resource group deployment" task? You can have a ARM template for service fabric cluster and this task will deploy that template.

**Comment by chaholl** [comment]
@bishal-pdMSFT An ARM template would work around the missing AzureRM.ServiceFabric problem but it doesn't help with the configuration of AAD authentication on the cluster because I'd still need to pass the tenantId as a parameter. 

Eg:
```
  {
      "apiVersion": "2016-09-01",
      "type": "Microsoft.ServiceFabric/clusters",
      "name": "[parameters('clusterName')]",
      "location": "[parameters('clusterLocation')]",
      "dependsOn": [
        "[concat('Microsoft.Storage/storageAccounts/', variables('supportLogStorageAccountName'))]"
      ],
      "properties": {
        "certificate": {
          "thumbprint": "[parameters('certificateThumbprint')]",
          "x509StoreName": "[parameters('certificateStoreValue')]"
        },
        "azureActiveDirectory": {
          "tenantId": "[parameters('aadTenantId')]",
          "clusterApplication": "[parameters('aadClusterApplicationId')]",
          "clientApplication": "[parameters('aadClientApplicationId')]"
        },
        "clientCertificateCommonNames": [],
        "clientCertificateThumbprints": [],
        "clusterState": "Default",
        "diagnosticsStorageAccountConfig": {
          "blobEndpoint": "[reference(concat('Microsoft.Storage/storageAccounts/', variables('supportLogStorageAccountName')), variables('storageApiVersion')).primaryEndpoints.blob]",
          "protectedAccountKeyName": "StorageAccountKey1",
          "queueEndpoint": "[reference(concat('Microsoft.Storage/storageAccounts/', variables('supportLogStorageAccountName')), variables('storageApiVersion')).primaryEndpoints.queue]",
          "storageAccountName": "[variables('supportLogStorageAccountName')]",
          "tableEndpoint": "[reference(concat('Microsoft.Storage/storageAccounts/', variables('supportLogStorageAccountName')), variables('storageApiVersion')).primaryEndpoints.table]"
        }
.....
```

Ultimately the DevOps script that I'm using populates and uses an ARM template to deploy the cluster. There are so many other dynamic parameters that need to be set (such as the keyvault location, certificate URL's etc.), that can only be retrieved by querying the configured Azure subscription.

**Comment by degant** [comment]
Hi @chaholl we're doing something similar right now in our release pipeline. We have pre-requisite steps such as getting certificate URLs, uploading a custom script into a blob etc. and then setting them as variables during the `Azure Powershell Task`. These dynamic parameters are later passed on to the ARM template to deploy the cluster.

For our scenario, we've already created the Azure AD Application and so we have the application ID and Tenant ID handy and are passing them as static parameters using VSTS environment variables, however if you plan to use powershell to create the Azure AD application and then pass the tenant ID and app ID, you could also do that.

**Comment by chaholl** [comment]
Hi @Degant. That sounds like a pretty similar approach to the one I'm taking at the moment. Essentially I'm adding 'tenantId' as an additional VSTS environment variable and manually setting it when configuring the release. It just doesn't seem right though. I can see a situation where the Azure connection points to one tenancy but the 'tenantId' property points to another.

I've found that doing any security related stuff in PowerShell on VSTS is practically impossible since both the subscriptionId and tenantId are missing from the context. That means that setting up the AAD app in the release process isn't possible. But, as you've suggested, I'm also setting that up as a prerequisite.

**Comment by bishal-pdMSFT** [comment]
@asranja can you please look at the Azure powershell issue?

**Comment by bishal-pdMSFT** [comment]
@asranja did you take a look at this?

**Comment by KrishnaAdityaB** [comment]
@chaholl Thanks for reporting the issue. 

If I understand correctly - you are using Hosted Agent. 
Hosted agents come-up with a certain version of Azure PowerShell modules. 
When you install some missing packages, they inturn install different versions of existing packages. This causes conflicts and you may end up with error similar to "_Azure PowerShell session is not initalized properly_".
Is my understanding correct?

Recently, we faced the same issue with AzureRM.EventHub module.
I will take it up with my team and see how we can handle this - like we may need to install few more popular packages?

Meanwhile, you can try this workaround (I agree, this is not perfect)

- **Hosted VS2017** agents have two versions of Azure PowerShell modules installed side by side. wiz. 3.8.0 and 4.2.1

- In version 2.* of Azure PowerShell task, you can explicitly mention the Azure PowerShell version to be used.

You can use a particular Azure PS version and install a specific compatible version of your package. While installing your package please use _-AllowClobber_ option

**Comment by chaholl** [comment]
@KrishnaAdityaB That makes sense and I'll try the workaround you suggested.

The bigger issue is that there's no way to access the _tenantId_ for the Azure context and I need that to configure the cluster for AAD authentication. I haven't tried creating the cluster using the **AzureRM.ServiceFabric** stuff yet but I'd imagine I'll have the same problem

**Comment by bishal-pdMSFT** [comment]
Removing service fabric label as this is question related to Azure PS and not to any SF deploy tasks.
