### ISSUE TITLE
Index Sources & Publish Symbols <--> portable PDBs

### ISSUE THREAD

**Issue by kimpenhaus** [Microsoft/azure-pipelines-tasks#5039]
Hi all,

this is more a question like an issue - hope that's ok :)

As Visual Studio 2017 update 15.3 is released and now supports [Visual Studio Team Services Symbol Server](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#a-iddebugging-adebugging-and-diagnostics)  we've added the _Index Sources & Publish Symbols_ task to our Release Task-Group of .NET core NuGet packages:

![image](https://user-images.githubusercontent.com/575109/29370866-fac495d4-82a6-11e7-9cb2-778374e30a7f.png)

We then realized, that while having portable PDBs those will not be indexed:

![image](https://user-images.githubusercontent.com/575109/29372121-861acd80-82aa-11e7-8767-c47e33dfd58d.png)

We read in this [comment](https://github.com/Microsoft/vsts-tasks/issues/4567#issuecomment-309170247) that portable PDBs by default support source linking. 

We tried some different setups (e.g using SourceLink with 
`<PackageReference Include="SourceLink.Create.CommandLine" Version="2.1.2" PrivateAssets="All" />` but didn't managed to get it work.

The symbols itself are retrieved by Visual Studio from the VSTS Server, but it is not able to find the the corresponding source files:

> SRCSRV: The module 'C:\Users\k\.nuget\packages\xxxx.foundation.logging.serilog\1.3.2\lib\netstandard1.6\xxxx.Foundation.Logging.Serilog.dll' does not contain source server information.

![image](https://user-images.githubusercontent.com/575109/29371916-fceb7398-82a9-11e7-9f4b-d560d47987fa.png)

Any help how to get this working is appreciated. :-)

Cheers,
Marcus

**Comment by dandancode** [comment]
In Visual Studio, you'll need to turn on "Enable source link support" under Debug->Options->General. The readme [here](https://github.com/ctaggart/SourceLink) provides more details on how to use Source Link. @mjsabby do you have more insights here?

Thanks,
Dandan

**Comment by kimpenhaus** [comment]
Thanks for your quick answer @dandancode 

My VS settings include source link support:

![image](https://user-images.githubusercontent.com/575109/29399199-83dab5f2-8328-11e7-9604-d8afd7d8c965.png)

But from what I understood is, that the build-server or msbuild (automatically) are weaving some additional information into the of the PDB CustomDebugInformation table according to the [spec](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md#SourceLink). This should be a json structure pointing to the source-files. [documentation](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md#source-link-json-schema)

But this is missing in the PDB files we create during the VSTS build.

![image](https://user-images.githubusercontent.com/575109/29399770-d2af23c8-832a-11e7-944a-666bb9c3c12a.png)

I am not pretty sure if this is not working while running *dotnet pack* which is doing an implicit build.

**Comment by tmat** [comment]
@kimpenhaus 
You are right, SourceLink should produce an entry in the PDB CustomDebugInformation table.
Could you try newer version of SourceLink package: https://www.nuget.org/packages/SourceLink.Create.CommandLine/2.2.0 and see if that helps? 
If not would you mind sharing build log (```msbuild YouProject.csproj /bl:build.binlog```) so I can take a look what's going on?

**Comment by mjsabby** [comment]
@dandancode We should create a VSTS sourceLink nuget package since this is a common thing people will like to do.

This is a good one we use internally in Bing that I can think we can make official since it uses the VSTS build agent variables and populates it for them.

```csharp
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
      <SourceLink>$(IntermediateOutputPath)source_link.json</SourceLink>
    </PropertyGroup>
    <Target Name="GenerateSourceLink" BeforeTargets="CoreCompile" Condition="'$(TF_BUILD)' == 'true'">
      <PropertyGroup>
        <SourceLinkRoot>$(BUILD_REPOSITORY_LOCALPATH.Replace("\", "\\"))</SourceLinkRoot>
        <SourceUri>$(SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$(SYSTEM_TEAMPROJECT)/_apis/git/repositories/$(BUILD_REPOSITORY_NAME)/items?api-version=1.0&amp;versionType=commit&amp;version=$(BUILD_SOURCEVERSION)&amp;scopepath=*</SourceUri>
      </PropertyGroup>
      <WriteLinesToFile File="$(SourceLink)" Overwrite="true" Lines='{"documents": { "$(SourceLinkRoot)\\*" : "$(SourceUri)" }}' />
    </Target>
</Project>
```

**Comment by jerickmsft** [comment]
@mjsabby It's my understanding from @tmat that SourceLink currently doesn't support *authenticated* (like VSTS) Git sources.  So, even if that Uri is embedded in the portable PDB, debuggers still won't be able to pull down the sources from VSTS. Am I missing something?

**Comment by tmat** [comment]
@caslan

**Comment by mjsabby** [comment]
Yes, that is unfortunate. We use a proxy internally, but I'd love to see this just get supported by VS.

**Comment by mitchdenny** [comment]
Closing this issue down. SourceLink support for Azure Repos was shipped, including authenticated repositories. For portable PDBs, you just don't index the symbols, publish works the same way. Then everything should work.
