### ISSUE TITLE
Copy Files Over SSH - Permission Denied

### ISSUE THREAD

**Issue by Franklin89** [microsoft/azure-pipelines-tasks#5046]
I am trying to upload my docker-compose.yml in a release step to my docker host using the "Copy Files Over SSH" task.

I keep getting an error saying: 

> ##[error]Failed to upload /opt/vsts/work/r1/a/Release Build/docker-compose/docker-compose.env.development.yml to tirdoo/docker-compose.env.development.yml on remote machine. Error: Permission denied.

I checked the permissions of the folder ~/tridoo. They seem correct. Also granted this folder full access with `chmod 777 ~/tridoo`

Using `scp` from my local computer with the same publickey works with no problem. Writing a file using the ssh command task using `touch hello-world.yml` works fine too.

Any idea why this is not working for me would be helpful. 

Thanks

**Comment by eschrader** [comment]
I blogged a work around I was using here:
https://eschrader.com/2017/05/17/using-visual-studio-team-services-build-tasks-for-linux-over-ssh/

Basically, you run a script to reset ownership to the same user you are using in the SSH Copy command, then after the copy you run a second script to set any permissions or ownership back. These scripts are also stored in source control.

**Comment by radekgala** [comment]
I see similar issue but I'm using as destination $home folder of user userd in SSH endpoint. It should not create permission denied problem or requiment to run script for change ownership. 

My case is I see in logs: 

##[debug]relativePath = classes\README.txt
2017-11-07T22:44:02.3259041Z Copying file d:\agent1\_work\r2\a\test\db-extracted\classes\README.txt to /user/local/********/VSTSDeployment/classes\README.txt on remote machine.
Why there is "\" character in linux path? Should I use Linux Agent for SSH?

**Comment by damccorm** [comment]
Hey @radekgala and @Franklin89 - sorry this issue has sat so long - is it still a problem for you?

**Comment by Franklin89** [comment]
@damccorm I dont even remember writing this 3y ago 😂 so not for me no...

**Comment by aloksaxenazohohotmail** [comment]
> Hey @radekgala and @Franklin89 - sorry this issue has sat so long - is it still a problem for you?

Hi @damccorm ,  

I am facing issue e.g. Failed to upload /home/vsts/work/1/s/srccode/assets/css/vendors/animate.min.css to /tmp/testcopy/css/vendors/animate.min.css on remote machine Error: Permission denied

Can you please guide me.

**Comment by sdobrodeev** [comment]
@Franklin89 can you please run pipeline in diagnostic mode and provide more logs? This will help a lot with the investigation.

**Comment by sdobrodeev** [comment]
@Franklin89, @aloksaxenazohohotmail this issue is still actual for you? If yes - can you please run pipeline in diagnostic mode and provide more logs? This will help a lot with the investigation.

**Comment by sdobrodeev** [comment]
Closing the issue due to lack of information, please feel free to reopen it.
