### ISSUE TITLE
Unable to pick a specific project to deploy

### ISSUE THREAD

**Issue by sixfootfour** [Microsoft/azure-pipelines-tasks#5128]
Regarding Azure App Service Deploy...

In many of my projects, there are several web projects (think admin, api, frontend).

I don't see a way to pick which project, I want to deploy. 

Do I need to create a solution/build config per web project I want to deploy, or am I missing something?

**Comment by chrisrpatterson** [comment]
You need to publish each web app as its own package if you need to deploy them independently.  MSBuild against the solution does not do that so you will need to have a build command for the solution and then one per project that passes the packaging properties.

**Comment by sixfootfour** [comment]
That makes sense - just like when I publish directly to Azure Web Apps from inside Visual Studio.

However, I don't know how to "have one per project, that passes the packaging properties".

This is outside the scope of an issue here, but any chance you could push me in the right direction? What should I google to learn more about how to do that? Are we talking parameters to MSBuild or something like that?

**Comment by RoopeshNair** [comment]
@sixfootfour - you can have multiple publish artifact steps for one each project. In your deploy step you can pick the artifact you wish to deploy

**Comment by moswald** [comment]
@sixfootfour I'm going to close this as I think it's been answered, it's pretty old, and it's a bit out of scope for this repo. I recommend going to our [Developer Community site](https://developercommunity.visualstudio.com/spaces/21/index.html) for future questions like this.
