### ISSUE TITLE
Determining Status of Build within a Task

### ISSUE THREAD

**Issue by antispinward** [Microsoft/azure-pipelines-tasks#5139]
Hello,

I am writing a custom task that performs some work every time the build is run(regardless of success) and part of this process we want to know whether the build has succeeded or not up to this point.

I believe according to https://github.com/Microsoft/vsts-tasks/issues/958 `$env:AGENT_JOBSTATUS`  should be valid however in our case it is not being set to any value.

Are there scenarios where agent.jobstatus is intended to not be valid, or is there another way to query the result of the build before it completes.

Thanks

**Comment by chrisrpatterson** [comment]
You shouldn't need to code that into the task the system will enable users to specify your task runs even on failure.

**Comment by antispinward** [comment]
Apologies if I wasn't clear. I am not trying to code the always run aspect, that is achieved with the task options. The issue is how to determine if the job is failing or succeeding when agent.jobstatus is null

**Comment by bryanmacfarlane** [comment]
Ting can answer that question

**Comment by antispinward** [comment]
I believe I have solved this issue for myself.

While $env:AGENT_JOBSTATUS is null
However ${env:agent.jobstatus} has the expected value

This appears to be a bug with the naming convention used to define this environment variable, it does not match up with the documentation.

**Comment by damccorm** [comment]
Closing here since the documentation now matches the described behavior and the env variable is getting set correctly.
