### ISSUE TITLE
Limitation:VSTS Build definitions support a single server task when "run at server" option is enabled

### ISSUE THREAD

**Issue by SunnyOswal** [microsoft/azure-pipelines-tasks#5353]
Hi Team,

Currently I see that there is a limitation that if we run Agentless task i.e server based task, we cannot add more tasks to the build definition.
Is VSTS team working on removing this limitation. If yes, could you please share the release timelines .

Thanks.

**Comment by bansalaseem** [comment]
We had added N agentless task in build/release definitions sometime back. So I am closing this issue.
