### ISSUE TITLE
DotNetCore task, restore command, default should be "selectOrConfig": "select"

### ISSUE THREAD

**Issue by pspill** [microsoft/azure-pipelines-tasks#5374]
The default settings for DotNetCore restore task should be "Feeds to use: Feeds I select Here" and "Use packages from NuGet.org" checked.  That way, if a user selects this tasks and does nothing other than select their project to build, they will get a basic restore from nuget.org.

Currently the default is "Feeds to use: Feeds in my Nuget.config" and an empty path to nuget.config, which results in no package sources being available for the restore.

**Comment by anuragc617** [comment]
@alexmullans can you look at this request?

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
