### ISSUE TITLE
ExtractFiles to support override files on the target path

### ISSUE THREAD

**Issue by cribeiro84** [Microsoft/azure-pipelines-tasks#5522]
I'm facing an issue that I don't want to delete all files on the target path prior to extraction from the archived file. Would be great to have an option to allow overriding or not the target files.

**Comment by pjquirk** [comment]
Have you tried unchecking the `Clean destination folder before extracting` option?  If so, could you clarify your issue?

**Comment by cribeiro84** [comment]
Yes, I did. But when I try to uncheck this flag, it raises an error saying that files cannot be extracted because they already exist in the target folder and tries to ask on the console if I want to replace it or not (see the attachment). Would be great o have a flag to force always to 'Yes' option during the extraction.

![image](https://user-images.githubusercontent.com/328635/31087140-529392de-a772-11e7-99cc-c90bc8e157d4.png)

**Comment by pjquirk** [comment]
Ah I see, thanks for the additional info.  What type of archive was this (zip/tar/7z)?

**Comment by cribeiro84** [comment]
In this case, I'm using zip files but I believe for other types may face the same issue.

Thanks a lot.

**Comment by madhurig** [comment]
Closing since this is an old issue. If you are still seeing issue, please open a new issue .
