### ISSUE TITLE
Deploy to Kubernetes task output format jsonpath

### ISSUE THREAD

**Issue by TqrHsn** [Microsoft/azure-pipelines-tasks#5548]
Could not find a way to define output format "jsonpath". There are only two options in drop down menu, json and yaml. Either it should accept any value like what command selector allows or an option could be added.

**Comment by sabbour** [comment]
This is needed for automation.

**Comment by TqrHsn** [comment]
Actually I am adding a step where I am trying extracting the deployed service ip like this:

kubectl get svc my-service -o jsonpath='{$.status.loadBalancer.ingress[0].ip}'

But my -o param is being overridden by -o json or -o yaml param added by the VSTS task.

**Comment by MitchDart** [comment]
I also need this. Infact 'kubectl delete' does not work at all because of this. I get the following error:

`##[error]error: Unexpected -o output mode: json. We only support '-o name'.`

Kubernetes requires -o name on kubectl delete command. Since only json and yaml are options, this is unusable.

**Comment by Zimmergren** [comment]
Are there any updates or workaround on this issue? 
I'm also experiencing the error: `Unexpected -o output mode: json. We only support '-o name'.` - but adding custom parameters with `-o name` obviously doesn't work as the full command will then have duplicate parameters as such `-o name -o json`. 

It's not possible to use this task whatsoever right now given this behavior. 

Would be happy to learn about workarounds, or if a fix will be merged and rolled out.

**Comment by Anumita** [comment]
@TqrHsn @ MitchDart, we add -o json by default. To change this, you can change the value OutputFormat field in the Advanced section in Version 1 of the task. The default value is json but the field is editable so you can change it to jsonpath.

**Comment by bansalaseem** [comment]
I am closing this issue as Anumita had merged the PR #8071 sometime back
