### ISSUE TITLE
[Feature Request][Area:Release]Provide upload attachment option in manual intervention task to include SOP checklists for release

### ISSUE THREAD

**Issue by lavanyasubbarayalu** [Microsoft/azure-pipelines-tasks#5643]
It would be good , to provide upload attachment option in manual intervention task to include SOP (standard operating procedures) checklists for release. This checklist attachments should be sent along with the mail, to the notify users group defined in the manual intervention task.

**Comment by RoopeshNair** [comment]
Currently there are no plans to support this. I would encourage you to post this on [User Voice](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services?category_id=145269) for right prioritization
