### ISSUE TITLE
Packer build task fails for user provided template with multiple builders

### ISSUE THREAD

**Issue by ducas** [microsoft/azure-pipelines-tasks#5651]
## Environment
- Server - VSTS

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Linux

## Issue Description

Packer build task fails for user provided template with multiple builders (e.g. virtualbox-ovf). Require ability to specify or should default command to use `-only azure-arm`. Example template:

```
{
  "variables": {
    "region": "{{env `AZURE_REGION`}}",
    "client_id": "{{env `AZURE_CLIENT_ID`}}",
    "client_secret": "{{env `AZURE_CLIENT_SECRET`}}",
    "resource_group": "{{env `AZURE_RESOURCE_GROUP`}}",
    "storage_account": "{{env `AZURE_STORAGE_ACCOUNT`}}",
    "subscription_id": "{{env `AZURE_SUBSCRIPTION_ID`}}",
    "object_id": "{{env `AZURE_OBJECT_ID`}}",
    "vm_size": "{{env `AZURE_VM_SIZE`}}",
    "ovf_path": "{{env `OVF_PATH`}}"
  },
  "builders": [{
    "type": "virtualbox-ovf",
    "vboxmanage": [
      [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
      [ "modifyvm", "{{.Name}}", "--cpus", "2" ]
    ],
    "source_path": "{{user `ovf_path`}}",
    "communicator": "winrm",
    "winrm_username": "vagrant",
    "winrm_password": "vagrant",
    "winrm_port": "5985",
    "winrm_timeout": "5h",
    "guest_additions_mode": "disable",
    "headless": "true"
  }, {
    "type": "azure-arm",

    "client_id": "{{user `client_id`}}",
    "client_secret": "{{user `client_secret`}}",
    "resource_group_name": "{{user `resource_group`}}",
    "storage_account": "{{user `storage_account`}}",
    "subscription_id": "{{user `subscription_id`}}",
    "object_id": "{{user `object_id`}}",

    "capture_container_name": "images",
    "capture_name_prefix": "my-image",

    "os_type": "Windows",
    "image_publisher": "MicrosoftWindowsServer",
    "image_offer": "WindowsServer",
    "image_sku": "2016-Datacenter",

    "communicator": "winrm",
    "winrm_use_ssl": "true",
    "winrm_insecure": "true",
    "winrm_timeout": "3m",
    "winrm_username": "packer",

    "location": "{{user `region`}}",
    "vm_size": "{{user `vm_size`}}"
  }],
  "provisioners": [{
    "type": "powershell",
    "inline": [
      "winrm quickconfig -q"
    ]
  }, {
    "type": "powershell",
    "inline": [
      "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
    ]
  }]
}
```

### Error logs

After successfully building azure-arm builder:

```
2017-10-16T06:41:03.5280090Z ==> Some builds didn't complete successfully and had errors:
2017-10-16T06:41:03.5302070Z --> virtualbox-ovf: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in $PATH
2017-10-16T06:41:03.5312140Z 
2017-10-16T06:41:03.5322010Z 
2017-10-16T06:41:03.5449910Z ==> Builds finished. The artifacts of successful builds are:
2017-10-16T06:41:03.5460690Z 
2017-10-16T06:41:03.5539880Z --> azure-arm: Azure.ResourceManagement.VMImage:
...
2017-10-16T06:41:03.6096900Z ##[error]Error: /opt/vsts/work/_temp/1508134227305/packer/packer failed with return code: 1
```

**Comment by bishal-pdMSFT** [comment]
Limiting to `-only azure-arm` could have side effects. If a agent machine has VirtualBox executable or any other pre-req required by a builder, it should not be blocked.

**Comment by bishal-pdMSFT** [comment]
@azooinmyluggage

**Comment by ducas** [comment]
@bishal-pdMSFT yep - completely agree. It seems this plugin is built for preparing azure images, which is why I mentioned that. I would much prefer the ability to specify command line arguments and/or explicit builders.

**Comment by sachinma** [comment]
@azooinmyluggage any opinions on this one/

**Comment by sachinma** [comment]
@azooinmyluggage  did you get a chance to go through this?

**Comment by sachinma** [comment]
@azooinmyluggage pinging again. Can you provide the recommendation here

**Comment by jogleasonjr** [comment]
Seconding the need for this. Either a free-form text box for any/all command line options, or individual UI elements for each [build option](https://www.packer.io/docs/commands/build.html) (there aren't very many) would be great. I was half curious about implementing the former myself -- but it wasn't clear from the contributing guide how to present a modified version of a built in task (such as the Packer task) to the DevOps pipeline. Is there any documentation on this?

**Comment by bishal-pdMSFT** [comment]
@jogleasonjr you can create pull requests in this repo if you want to contribute. See the guidelines [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md). A text box for build options looks okay to me. @pulkitaggarwl @azooinmyluggage  to comment further.

**Comment by azooinmyluggage** [comment]
Sounds good to me.

**Comment by ewierschke** [comment]
Would definitely like to see some way of providing the command options to the packer commands for this task.  As with others, specifically/initially looking to use the -only option as my json has many builders and I only want to build a select few in a given pipeline.
