### ISSUE TITLE
DotNetCoreCLI doesnt support custom commands

### ISSUE THREAD

**Issue by rol-dave-overall** [Microsoft/azure-pipelines-tasks#5768]
Whilst the DotNetCoreCLI task supports a custom command option but this actually does not work and from looking at the code it will never work.

The execute method of the task is as follow, as can been seen if the command is custom then this.command is set to what has been entered for the custom command. Yet following this the switch statement only supports the predefined commands with anything else been raised as an error.
 
if (this.command === "custom") {
            this.command = tl.getInput("custom", true);
        }

        switch (this.command) {
            case "build":
            case "publish":
            case "run":
                await this.executeBasicCommand();
                break;
            case "test":
                await this.executeTestCommand();
                break;
            case "restore":
                await restoreCommand.run();
                break;
            case "pack":
                await packCommand.run();
                break;
            case "push":
                await pushCommand.run();
                break;
            default:
                tl.setResult(tl.TaskResult.Failed, tl.loc("Error_CommandNotRecognized", this.command));
        }

**Comment by sachinma** [comment]
It should be working now. Please open again if that is not the case

**Comment by anuragc617** [comment]
@rol-dave-overall The custom commands are supported in DotNetCoreCLI now. Closing this, feel free to open if you see any issue.
