### ISSUE TITLE
Issue with SourcePath variable in UWP app build

### ISSUE THREAD

**Issue by scott-stoltz** [microsoft/azure-pipelines-tasks#5884]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment    
    It is VSTS. Cannot disclose names publicly.

- Agent - Hosted or Private:     
    - Private agent using Windows Server 2016 build agent template in Azure.

## Issue Description
This is a UWP app and I'm getting an error on the SourcePath variable. The default in Azure Copy on VSTS is "\AppxPackages", which isn't working. Can you please give me guidance on what to set this variable to in order to local the correct AppxPackages folder?

### Error logs
Upload to container: 'builds' in storage account: 'test' with blob prefix: '' failed with error: 'SourcePath must exist
Parameter name: sourcePath'

**Comment by asranja** [comment]
Please use the latest version of the task to deploy. Please reopen if anybody is still facing this issue.
