### ISSUE TITLE
[Android Gradle] needs to download CMake, but got no chance to agree to license agreement, failed builds

### ISSUE THREAD

**Issue by piqiums** [Microsoft/azure-pipelines-tasks#5935]
Hi there
   I am a Microsoft employee working on an cross-platform & cross-language project based on Djinni. It includes an Android project that will also compile C++ code. I chose the "Hosted" agent pool, and used the API level 25 that is supported by the Hosted agent pool. My project needs to download CMake and some other libraries, but there's no chance to accept the license agreement during the build process. Please check the pasted log. If this could be supported in soon, I'd appreciate it very much. 

VSO    
Using Hosted agent, agent queue name: Hosted
team: Microsoft Auth Telemetry System
build definition: MATS Android (branch - master) for debug purpose
Link : https://authtelemetry.visualstudio.com/Microsoft%20Auth%20Telemetry%20System/_build/index?context=mine&path=%5C&definitionId=12&_a=completed

### Error logs
[log_vso_fail_download_cmake.txt](https://github.com/Microsoft/vsts-tasks/files/1512072/log_vso_fail_download_cmake.txt)

**Comment by chrisrpatterson** [comment]
Have you tried the Hosted VS2017 pool?

**Comment by piqiums** [comment]
yes, same thing

**Comment by madhurig** [comment]
Closing this since it is an old issue. We believe this has been addressed.
