### ISSUE TITLE
Issues with Timeline Entries and progress feedback 

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/azure-pipelines-tasks#5961]
## Environment
- Server: TFS On Premise 15.117.26615.0

## Issue Description

Trying to utilize better progress details on steps in a longer running custom build task. I have tried to leverage child steps nested with GUID's mapped to parent step guids. Didn't work. So I tried just regular steps, and couldn't get the build steps to show up in the timeline at all.  I'd like someway to show percentage complete on child steps for someone watching a long running task, but I'm not sure of how to accomplish. 

Example, running a task with the following statement to generate a new timeline entry doesn't show up anything new in the timeline. 
```
#using posh 5 class
$this.TFSStepGuid      = [Guid]::NewGuid().Guid.ToString()
$this.ActivityName = 'Example Step'
write-host ("##vso[task.logdetail id={0};name={1};type=build;order=1]{1}" -f $this.TFSStepGuid, $this.ActivityName)
write-host ('##vso[task.logdetail id={0};progress=0;state=InProgress;]{1}' -f $this.TFSStepGuid, $this.ActivityName)
```

Later I'd update the percentage complete here
```
write-host ('##vso[task.logdetail id={0};progress=50;state=InProgress;]{1}' -f $this.TFSStepGuid, $this.ActivityName)
```

Finally mark as complete 
```
write-host ( '##vso[task.logdetail id={0};state=Completed;]Completed' -f  $this.TFSStepGuid)
```
I'm not seeing any of these timeline entries. Any feedback on why this might be and if there are better ways to report back progress that will feedback to tfs on long running builds? Any improved way with 2017 I should leverage?

**Comment by yaananth** [comment]
![image](https://user-images.githubusercontent.com/12280011/35460081-a6bd0950-02b0-11e8-8633-dc48992853ad.png)

Where do you expect to see the progress?
We don't currently have a way to display progress for subtimelines.

I guess you could pump to the logs on the progress.

**Comment by moswald** [comment]
@sheldonhull We have completely reworked our build logs display. If you feel it is still not sufficient for your purposes, I suggest opening a ticket with the details on the [Developer Community website](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
