### ISSUE TITLE
Jenkins job link lost in TFS

### ISSUE THREAD

**Issue by pawelrutka** [Microsoft/azure-pipelines-tasks#5978]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
 TFS on-premises 20017 update 2
    
- Agent - Private:
Ubuntu 16.04

## Issue Description

Sometimes TFS lost link to Jenkins Job that was build. It happens almost always when Build fails.

Here how it look when everything works:
![ok](https://user-images.githubusercontent.com/32490603/33650359-f2b2022e-da61-11e7-80b0-6bdcf5dd0c45.png)

And here when broken:
![bad](https://user-images.githubusercontent.com/32490603/33650368-fc277410-da61-11e7-96e5-00e01e553ae3.png)

So there is no section for **# Jenkins Result** with implies that there is no possibility to navigate to broken build from tfs!

IF there is a way to provide more info give me a hint and I will try provided data for this issue.

### Error logs
[logs_493.zip](https://github.com/Microsoft/vsts-tasks/files/1534321/logs_493.zip)

**Comment by kelliejos** [comment]
@pawelrutka, Thanks for providing the build logs. To help us narrow down the issue, could you capture a network trace when you reload the build summary page for a failed build? In Chrome you can do this by opening Developers Tools (you can open this by hitting F12 on your keyboard) and clicking on the Network tab in the tools panel.  Reload the build summary page for the failed build you've shown above and copy the network traffic displayed. I am looking for the network traffic for a page load when the Jenkins Result section fails to display.  Thanks.

**Comment by pawelrutka** [comment]
Hi
Here You are.
Bad log:
[bad_network.zip](https://github.com/Microsoft/vsts-tasks/files/1538047/bad_network.zip)

On good load we can see that Jenkins%Result is received:
![ss](https://user-images.githubusercontent.com/32490603/33702135-95f1bd6a-db22-11e7-852b-a5483d7a4dff.png)

**Comment by kelliejos** [comment]
That was exactly what I was looking for. This isn't a bug in the Jenkins task itself, but I've opened a bug for this (Internal bug 1141699) and we will take a look at the issue soon. Thank you for the detailed information!

**Comment by pawelrutka** [comment]
Aby chances to see fix on 2018 release or earlier?

07.12.2017 3:44 PM "kelliejos" <notifications@github.com> napisał(a):

**Comment by madhurig** [comment]
We hope to have it in the next feature update of TFS 2018. Thanks!

**Comment by moswald** [comment]
Closing, this was fixed quite awhile ago.
