### ISSUE TITLE
Resource Group Resources array empty

### ISSUE THREAD

**Issue by aus7d7** [microsoft/azure-pipelines-tasks#5983]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server: VSTS
- Account Name:  Safety Platform
- Team project:  Safety Platform\Intel Services
- Build Definition Name :  IS-IntelWorkbench

- Agent: Hosted
- Agent Queue Name: Windows Defender PROD

## Issue Description
Release Name: IS-IntelWorkbench_Worker_Deployment
Task Name: Azure Resource Group Deployment and Windows Machine File Copy

When I use the SELECT RESOURCE Group Option and use its output variables to copy files to machines in those resources I get the following error: 
`##[error]System.Management.Automation.RuntimeException: No machine exists under environment: '{"Id":0,"Name":"ISWHNSCUWorkerTZ","Url":null,"Revision":1,"Project":{"Id":"Safety Platform","Name":"Safety Platform"},"Resources":[],"Properties":{"Microsoft-Vslabs-MG-WinRMProtocol":{"Data":"HTTPS","IsSecure":false},"Microsoft-Vslabs-MG-SkipCACheck":{"Data":"False","IsSecure":false}},"IsReserved":false,"CreatedBy":{"Name":"cb55739e-4afe-46a3-970f-1b49d8ee7564"},"ModifiedBy":{"Name":"cb55739e-4afe-46a3-970f-1b49d8ee7564"},"CreatedDate":"2017-11-14T23:17:59Z","ModifiedDate":"0001-01-01T00:00:00"}' for deployment ---> System.Management.Automation.RuntimeException: No machine exists under environment: '{"Id":0,"Name":"ISWHNSCUWorkerTZ","Url":null,"Revision":1,"Project":{"Id":"Safety Platform","Name":"Safety Platform"},"Resources":[],"Properties":{"Microsoft-Vslabs-MG-WinRMProtocol":{"Data":"HTTPS","IsSecure":false},"Microsoft-Vslabs-MG-SkipCACheck":{"Data":"False","IsSecure":false}},"IsReserved":false,"CreatedBy":{"Name":"cb55739e-4afe-46a3-970f-1b49d8ee7564"},"ModifiedBy":{"Name":"cb55739e-4afe-46a3-970f-1b49d8ee7564"},"CreatedDate":"2017-11-14T23:17:59Z","ModifiedDate":"0001-01-01T00:00:00"}' for deployment`

I see that the Resources array is empty. I wonder if that has anything to do with it. However, when I try to access this same resource group via Azure CLI, it seems to be getting the right information. What am I doing wrong?

### Error logs
[ReleaseLogs_5709.zip](https://github.com/Microsoft/vsts-tasks/files/1536817/ReleaseLogs_5709.zip)

**Comment by sachinma** [comment]
Hi @aus7d7 are you trying to copy files to machines on a VM scale set? If yes, that is not supported by Azure Resource Group deployment and Windows Machine File copy task.
If you are using VMs, can you run the release with system.debug variable set to true and share the logs with description at RM_Customer_Queries at microsoft dot com

**Comment by sachinma** [comment]
Hi @aus7d7 can you provide the above information?

**Comment by aus7d7** [comment]
Hi @sachinma we are not using machines on a VM scale set. Pardon my lack of knowledge here, but how do I run the release with system.debug variable set to true and access the logs?

**Comment by sachinma** [comment]
You can define a variable in the release with the name "system.debug" and have its value set to true. After that next time when the task runs, it would be have debug logs. You can go to the logs section in the release and look at the task logs there.

**Comment by aus7d7** [comment]
Hi Sachin,
I am attaching the logs as a zip file. I will also send an email to the alias you suggested
[ReleaseLogs_6752.zip](https://github.com/Microsoft/vsts-tasks/files/1653986/ReleaseLogs_6752.zip)

**Comment by sachinma** [comment]
hi @aus7d7 , from the logs it appears that the VMs are not associated with any public IP address. For the selection to work, we expect the VMs to be publicly accessible. Just to clarify further, this selection is meant to be consumed in a subsequent Run PowerShell on Remote Machine task to do the deployment where we expect them to be publicly accessible.

**Comment by aus7d7** [comment]
Hi @sachinma. That is true that these VMs not have any public IP addresses and yes the intention is to consume them in the subsequent run powershell and remote machine tasks. However, our release agent is running in the same domain and environment as the VMs and all we need are the machine names which I would guess the "Azure Resource Group Deployment" task should be able to get, no? As a work around I have made a variable with a comma separated list of machine names and used that as the value of the "Use Machine Names" radio button for file copy and run powershell task.

**Comment by sachinma** [comment]
Hi @aus7d7  our current behavior is to select only public vms and not rely on having agent in the same network as the VMs. However, this could be valid enhancement in the task. + @RoopeshNair to look at this.

**Comment by aus7d7** [comment]
Hi @sachinma, Thank you so much for your help. Should I file an official feature request for this?

**Comment by sachinma** [comment]
I have marked this as enhancement and we go over possible enhancement during our regular planning.

**Comment by bishal-pdMSFT** [comment]
"Select resource group" option has been removed from the task. You can choose to use Az CLI or Azure PowerShell task to accomplish selection of a resource group.
Closing this issue.
