### ISSUE TITLE
NPM Authenticate task appending trailing slash to registry

### ISSUE THREAD

**Issue by b-barthel** [microsoft/azure-pipelines-tasks#6063]
The NPM authenticate task is appending a trailing slash to the registry URLs before authenticating, which generates an auth token with an incorrectly nerfed url.  Subsequent operations against the registry in the npmrc will fail because it can't find the correct token..

Ideally we should handle both cases (with/without trailing slash) so the user doesn't need to know the specifics of how the registry is authenticated.

**Comment by elbatk** [comment]
@b-barthel is this still relevant? Doing a pass of old GHI in this repo.

**Comment by elbatk** [comment]
Closing this one for now, @b-barthel if you think it should be reopened/copied to our backlog, let me know!
