### ISSUE TITLE
Trying to get provisioning profiles from another repository

### ISSUE THREAD

**Issue by AlbertoLF** [microsoft/azure-pipelines-tasks#6191]
## Environment

- VSTS

## Issue Description

Im trying to install an Apple provisioning profile from an another repository that are in the same project.

When i choose 'Source Repository' in 'Provisioning Profile Location' option, i can't choose another repository.

<img width="1034" alt="screen shot 2018-01-10 at 16 13 26" src="https://user-images.githubusercontent.com/10026227/34779761-71b7044a-f621-11e7-961c-e519ff272688.png">

I have all provisioning profiles in another repository on the same project, and i can't access to use them.

Thanks.

**Comment by AlexRukhlin** [comment]
Hi @Troglodyte55 

We have a work item in our backlog to allow usage of multiple repositories in a definition. Once implemented, this feature will allow you to use different repositories for code sources and provisioning profile files. 

Unfortunately, we haven't yet any specific date for the work item implementation by now.

Alex

**Comment by Troglodyte55** [comment]
OK @AlexRukhlin, thank you for clarification

**Comment by madhurig** [comment]
@Troglodyte55: You can achieve this even today by adding a script to pull sources from the other repository and providing the local path to where that was downloaded. The UI will not allow you to browse to the repository but you can use environment variables that are available during the build: https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch 

We have an item on the roadmap to provide better support for multiple repositories during a build.

Thanks,
Madhuri
