### ISSUE TITLE
Service Fabric: How to specify parameters in VSTS release

### ISSUE THREAD

**Issue by Tadimsky** [microsoft/azure-pipelines-tasks#6210]
I'm trying to deploy to Service Fabric using the `Service Fabric Deployment` task and want to get secrets from Azure KeyVault and use those as part of the deployment process.
However, it seems like I can only set a parameters file, not application parameters individually (like you can with the PowerShell command).

Is there any good way to be able to get secrets and use them at deployment time? Or do I have to generate an XML file to do this?

**Comment by Tadimsky** [comment]
To be clear, I would like to be able to do what is recommended by Service Fabric for deploying secrets:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management

```
PS C:\Users\vturecek> New-ServiceFabricApplication -ApplicationName fabric:/MyApp -ApplicationTypeName MyAppType -ApplicationTypeVersion 1.0.0 -ApplicationParameter @{"MySecret" = "I6jCCAeYCAxgFhBXABFxzAt ... gNBRyeWFXl2VydmjZNwJIM="}
```

**Comment by Tadimsky** [comment]
Any update on this? I've now written a PowerShell script that will encrypt the values using the Cert from KeyVault and then modify the Application Parameters `xml` file, but it seems like this would be nice to not have to do...

**Comment by bishal-pdMSFT** [comment]
@Tadimsky this looks like something good to have. But even if the task supports individual application parameters how will these parameters get encrypted before being used?

**Comment by Tadimsky** [comment]
I currently have a PowerShell script that runs which gets the secret values from KeyVault as well as the Config Cert. I then encrypt each of the secrets and store them as VSTS variables.
Then I'd like to just use those in the Deployment, but I'm now rewriting the ApplicationParameters XML file as that's the only way to do it.

**Comment by bishal-pdMSFT** [comment]
@Tadimsky It would be better to have this encryption support in task itself so that additional script task is not needed. But how does task know which certificate to use for encryption? Do you use server certificate itself for encryption or does that use a dedicated certificate? It would be easier for task to use server certificate, but will have to take another user input for other certificate.
@Pulkit please review these feedbacks:
1. Enable taking individual application parameters either as a text input or via xml parameters editor
2. Enable encrypting these parameters by using server certificate. Any other certificate would be problem(either take whole certificate as input or require cert to be pre-installed or take key-vault input)

**Comment by Tadimsky** [comment]
Yeah, that would be even better for sure! It definitely seems like something that people would have to do themselves with a script right now.
I'm providing the cert from KV as a parameter to the script that runs the encryption as well as the values of the secrets from KV. That then sets Release Variables with the encrypted values which I feed into a separate script to add/replace the values in the parameters.
I could make it fetch the certificate from the ARM template that defines the config cert in the SF cluster, but I haven't done that.

**Comment by bishal-pdMSFT** [comment]
@pulkitaggarwl

**Comment by bishal-pdMSFT** [comment]
@pulkitaggarwl any thought on this?

**Comment by RickBlouch** [comment]
Any updates or new plans to support encrypting secrets as part of a VSTS release task for Service Fabric?  We are also looking to follow [the recommended pattern](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management), but there appears to be no built-in way to do this yet.  


@Tadimsky - Any chance you would be willing to share your scripts?

**Comment by bishal-pdMSFT** [comment]
This slipped under radar. Let me discuss this internally to see if this is something we can do.

**Comment by RickBlouch** [comment]
@bishal-pdMSFT any word on this yet or should I plan to start exploring the solution that @Tadimsky described?

**Comment by bishal-pdMSFT** [comment]
This is fixed now. You can specify application parameters as release variables and they will be used by task. Enable "Override application parameters" check-box to turn on this behavior.

![image](https://user-images.githubusercontent.com/7830141/61530063-a8e94700-aa40-11e9-9d97-5f1fc2aacea1.png)
