### ISSUE TITLE
Proxy Support in NuGetToolRunner2 does not honour Agent.ProxyBypassList

### ISSUE THREAD

**Issue by thecontrarycat** [Microsoft/azure-pipelines-tasks#6252]
## Environment
- Server - TFS2018

- Agent - Private Agent win7-x64-2.122.1 on Windows Server 2012R2
    
## Issue Description

In https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/nuget-task-common/NuGetToolRunner2.ts the method prepareNuGetExeEnvironment() checks to see whether a proxy is configured on the agent (Agent.ProxyUrl).

However, it does not honour the associated proxy bypass list (Agent.ProxyBypassList) property.

In our environment, we have a locally hosted ProGet server (https://nuget.domain.local/) and a number of build agents.  The build agents do not have direct access to the internet (going through a proxy http://proxy.domain.local:8080).  The proxy does not have access to the ProGet server, so build agents contact it directly.

It is imperative that our build agents are able to use the proxy for external communication, while not using the proxy when connecting internally.  We have an Agent.ProxyBypassList setting of `.*\\.domain\\.local` that works for other vsts tasks, but not the nuget one.

## Expected Behaviour

The NuGetToolRunner2 should only set the HTTP_PROXY environment variable if the nuget host it is trying to connect to is not matched by one of the entries in Agent.ProxyBypassList.

**Comment by thecontrarycat** [comment]
## Workaround

Note that it is possible to workaround this issue by setting the NO_PROXY environment variable on your build agent.  However, this is more problematic to maintain across multiple build agents compared to simply having the .proxybypass file in the agent root folder.

e.g. `SET NO_PROXY=domain.local`

**Comment by aldoms** [comment]
I'm sorry you're having issues. We haven't updated our tasks to support the .proxybypass feature, we'll fix that in a later release.

**Comment by mmajcica** [comment]
I am having the same issue with NuGet (new v2 version) task when trying to push the packages to my internal TFS feed.
The suggested workaround doesn't work (NO_PROXY env variable).
However, the old task NuGet Publisher (that is deprecated) works with no issues. And this can be considered a good workaround.

**Comment by japj** [comment]
Any insight in when this is planned to be worked on for on premise customers?
We are on TFS2018 Update2 and are now hitting this issue, not being able to use the NuGet based tasks because of this.

**Comment by bryanmacfarlane** [comment]
noting that proxy support is a base requirement for TFS in-prem.

**Comment by japj** [comment]
Just to clarify on my earlier remark/question, we are running TFS behind a proxy server and have configured all build agents with correct bypassproxy settings. This was done as part of the rollout of agent v2.117.2 (TFS2017U2), because the bypassproxy was introduced then (the setting didn't exist before).

Now that we are moving more internal projects to TFS and as those want to make more use of the buildin tasks, we now discover that at least one of them (the NuGet task) does not support the bypassproxy functionality yet.

We were hoping/expecting that at least the build-in tasks would be getting bypassproxy support. 
I can understand that thirdparty tasks are out of scope.

**Comment by mmajcica** [comment]
@bryanmacfarlane are you saying that proxy support is not an essential feature and you are not keen to focus on it?

@japj I opened a ticket on MS Premier Support regarding this and I'm chasing this on other channels. It is also essential for us to have ALL of the MS supported tasks play well with the proxy.

**Comment by keithrob** [comment]
@mmajcica,
Please contact me at kerobert AT Microsoft.com and we can discuss.  

I have commented in #7495 that we are planning to address all of these issues.  In the meantime, older versions of these tasks should work.

**Comment by japj** [comment]
@keithrob any update on this?  Is this planned for 2019RTM or a later Update?

**Comment by alexmullans** [comment]
Proxy support is shipped, will land in the next feature update to Azure DevOps Server (2019.1)

**Comment by DalpheSDC** [comment]
> Proxy support is shipped, will land in the next feature update to Azure DevOps Server (2019.1)

Now we have 2019.1 install, but we still get this error
ERR:unable to get local issuer certificate
which tool do we need to provide the CRT certificate store files?
regards
Peter Dahl
SDC
