### ISSUE TITLE
Feature: ability to set a release variable ("##vso[release.setvariable variable=varname;]$value")

### ISSUE THREAD

**Issue by inverted360** [microsoft/azure-pipelines-tasks#6302]
General availability to set a release variable from within a powershell script path/ inline script would appeal to many.

Overview: I want RM to leverage a dynamic number of test agents for automated testing. The test agents are always contained by a known resource group, but quantity and names may change. For cost saving, the test agent VMs do not need to run outside of the testing that is orchestrated by VSTS RM.

My use case:
1. hosted phase 1: task to get list of vms from a resource group and set the list to a release variable
2. hosted phase 2: configure phase with Parallelism - Multi-configuration and set multipliers to vm list from phase 1. Phase creates "n" number of agents based on parsing the CSV vm string list. Phase passes 1/n vm names to each agent. Agent processes subsequent tasks per each target vm in parallel (like start/stop/configure).

**Comment by GitHubSriramB** [comment]
@inverted360 - we currently do not support output variables across phases within an environment. As a workaround, could you instead store the list of VMs within release using REST API? This variable will then be available to the subsequent phases.

**Comment by bansalaseem** [comment]
This blog talks about how you can update a variable in a release. 

https://blogs.msdn.microsoft.com/aseemb/2016/05/23/how-to-update-release-level-variables-using-rm-rest-apis/

**Comment by andyliuliming** [comment]
@bansalaseem any plan to support this?

**Comment by inverted360** [comment]
Please enable this feature in Azure DevOps or equivalent in Github. 

> 'support output variables across phases within an environment.'

**Comment by inverted360** [comment]
Please enable this feature in Azure DevOps or equivalent in Github.

'support output variables across phases within an environment.'
