### ISSUE TITLE
Visual Studio Build Task fails on logging when any filenames contain [ or ]

### ISSUE THREAD

**Issue by steelerc** [Microsoft/azure-pipelines-tasks#6314]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS

## Issue Description
If a solution has any project with a filename containing either of [ or ] the build process succeeds, but is marked as failed.  Actual build step logs show:
2018-01-30T16:13:36.3337662Z Build succeeded.
2018-01-30T16:13:36.3337906Z     0 Warning(s)
2018-01-30T16:13:36.3338086Z     0 Error(s)
2018-01-30T16:13:36.3338222Z 
2018-01-30T16:13:36.3338415Z Time Elapsed 00:00:08.30
2018-01-30T16:13:36.4870583Z ##[section]Finishing: Build solution

But build output shows errors below
### Error logs
Unable to process command '##vso[task.logdetail id=927b3194-b008-473a-b822-91af5a4dadcb;parentid=;name=QuotingRepository\Interfaces\IBaseRepository[T].cs;type=Build;starttime=2018-01-30T16:13:01.2494103Z;state=InProgress;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Type is required for this new timeline record.
d:\a\1\s\QuotingRepository\Interfaces\IBaseRepository[T (0, 0)
d:\a\1\s\QuotingRepository\Interfaces\IBaseRepository[T(,): Warning : .cs;linenumber=23;columnnumber=22;code=SA1649;]File name must match first type name.
Unable to process command '##vso[task.logdetail id=927b3194-b008-473a-b822-91af5a4dadcb;parentid=;type=Build;result=Failed;finishtime=2018-01-30T16:13:01.2594098Z;progress=100;state=Completed;parentid=;name=;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Name is required for this new timeline record.

**Comment by moswald** [comment]
This isn't an issue with the build task, but rather with the way the agent is parsing the log message. Moved it to the agent repo.

**Comment by damccorm** [comment]
Just for the record (in case someone finds this issue in the future), this was an issue with the task - it simply needs to consume the most recent version of the task-lib.

**Comment by lukaszch** [comment]
How to consume the most recent version of the task-lib in Azure DevOps Server 2019?
We are facing exactly the same issue with the latest Azure DevOps Server 2019 RTM release with MSBuild task.

**Comment by lukaszch** [comment]
Thank you for your prompt reply.
As it's not a blocker for us (build runs successfully after 2-3 tries, and not every build is affected) we can wait for a next DevOps Server release.
If that's possible, please just only ensure it will have the newer task-lib version included.
Thank you very much.

**Comment by japj** [comment]
@damccorm I just run into this today with the MSBuild task:
- Azure DevOps Server Dev17.M153.5 (This is an Azure DevOps Server 2019 Update 1.1)
- Agent 2.153.1
- MSBuild task 1.151.1 (which seems to use vsts-task-lib 2.2.1 and VstsTaskSdk 0.8.2)

**Comment by shayki5** [comment]
We also faced this issue.
Any ETA for fix?
