### ISSUE TITLE
dotnetcore build task should warn or error when setting up authentication for an http package source

### ISSUE THREAD

**Issue by pspill** [microsoft/azure-pipelines-tasks#6357]
## Environment
Users are reporting this issue on-prem using private windows agent.

## Issue Description

This issue affects users a) in on prem environments, b) performing dotnet restore in build c) targeting a VSTS package source using http instead of https.

The build task does write credentials to a temporary nuget config, but during restore, the basic authentication header will not be emitted if the target package source is not https.

This can be difficult to debug, since the temporary config file is deleted at the end of the build task, and you have to attach fiddler to see that credentials are not being sent.

Instread, during credential acquisition a warning should be logged instructing the user that http sources do not support basic authentication and an https endpoint should be used

**Comment by ExcaliburVT** [comment]
Request in addition to the warning the option to disable the SSL-only behavior for isolated environments where SSL is not considered needed.

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
