### ISSUE TITLE
CopyFiles Task: preserve timestamps option

### ISSUE THREAD

**Issue by japj** [Microsoft/azure-pipelines-tasks#6384]
## Environment
- TFS2017Update3
- Private Agent, WindowsServer 2016, Agent v2.117.2

## Issue Description
The "Copy Files" Task currently does not seem to preserve timestamps.
At this moment it seems that the destination files have the time of copy, instead of the original modified/created timestamps.

It would be great if it had an option to enable preserve timestamps.

I am not sure, but it could be that the vsts-task-lib will be impacted for solving this.

**Comment by bryanmacfarlane** [comment]
I think this is a dupe but marking as enhancement for now.

**Comment by carlowahlstedt** [comment]
My two cents on this, and thus the second PR is that there are two areas that timestamps are changing. One is in this task when copying files, the second is the upload of the artifact (as PR #739 states). I don't have validation that the second is still an issue, but the CopyTask updating timestamps is. Thanks.

**Comment by ericsciple** [comment]
@vtbassmatt to prioritize

**Comment by vtbassmatt** [comment]
I'm for this, especially since @carlowahlstedt made the code changes. Once he adds the test @damccorm asked for, we're in business.
