### ISSUE TITLE
Add generic artifact type to build

### ISSUE THREAD

**Issue by DerGary** [microsoft/azure-pipelines-tasks#6468]
## Environment
VSTS
Agent - Private

Hello Guys, 
I'm currently trying to add release definitions for our builds. Doing this I stumbled upon a little problem. Currently we upload all our created artifacts to a SonaType Nexus Repository Manager. I tried to get the information of which artifact the build created to the release definition. But the only way I could make this happen until now is also publishing the artifacts to a network share (which is not an ideal solution in my case)

I would like to have an option to define variables in the build that can be read by the release definition like the url where to find the published artifact.

Something like:
##vso[artifact.associate type=url;artifactname=SomeName]http://repository:8081/repository/vsts-extensions/someExtension.vsix

Is there already such an option that I missed in my research?

Greetings Gary

**Comment by GitHubSriramB** [comment]
@DerGary - we have a feature in our backlog to support passing build variables into release. 

However what you are looking for could be solved with what we currently support by doing the following:

1. Use ##vso[artifact.associate] command to associate generic artifact with Build like you have mentioned above.
2. Write custom task/script that queries for artifacts given build id. The build id is available within release as one of the artifact variables:
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/variables?tabs=batch#artifact-variables
3. Artifact details queried should have details including the url value. Set a variable that is available to subsequent tasks using ##vso[task.setvariable] command.
4. Use the variable set in subsequent tasks.

Would this work?

**Comment by DerGary** [comment]
Thanks for your fast response.
I don't know if I understood you correctly. 
I tried the following:

`##vso[artifact.associate]http://repository:8081/repository/vsts-extensions/ExtensionName.vsix`

Which resulted in the following error:

```
2018-02-20T10:14:23.0017600Z ##[error]Unable to process command '##vso[artifact.associate]http://repository:8081/repository/vsts-extensions/ExtensionName.vsix' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-02-20T10:14:23.0017600Z ##[error]Artifact Name is required.
```

Then I tried it with an artifact name:

`##vso[artifact.associate artifactname=ExtensionArtifact]http://repository:8081/repository/vsts-extensions/ExtensionName.vsix`

Which resulted in the following error:

```
2018-02-20T10:16:18.8991596Z ##[error]Unable to process command '##vso[artifact.associate artifactname=ExtensionArtifact]http://repository:8081/repository/vsts-extensions/ExtensionName.vsix' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-02-20T10:16:18.8991596Z ##[error]Can't infer artifact type from artifact location: http://repository:8081/repository/vsts-extensions/ExtensionName.vsix.
```

Then I tried it without a location:

`##vso[artifact.associate artifactname=ExtensionArtifact]`

Which resulted in the following error:

```
2018-02-20T10:17:16.5677781Z ##[error]Unable to process command '##vso[artifact.associate artifactname=ExtensionArtifact]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2018-02-20T10:17:16.5677781Z ##[error]Can't infer artifact type from artifact location: .
```

The documentation for artifact.associate says:
```
artifactname=artifact name (Required) 
type=container|filepath|versioncontrol|gitref|tfvclabel, artifact type (Required)
```
so I have to provide both artifactname and type. But when I tried to use type filepath or container 
I got the following error:
`Can't infer artifact type from artifact location: http://repository:8081/repository/vsts-extensions/Extension.vsix.`

Am I missing something here?

Greetings Gary

**Comment by omeshp** [comment]
@GitHubSriramB I think what  @DerGary is looking for is support for "SonaType Nexus Repository Manager" artifact in release\build. Currently build doesn't support associating custom artifacts, it can only be one of the types container|filepath|versioncontrol|gitref|tfvclabel. 

@DerGary Will having support for linking "SonaType Nexus Repository Manager" artifacts in release help?

**Comment by omeshp** [comment]
@DerGary It looks like build actually supports associating custom artifacts. I tried it using the below command and it works:
 Write-Host "##vso[artifact.associate artifactname=awesomeDrop;artifacttype=myartifacttype]https://downloads.visualstudio.com/foo/bar/baz.zip" 

So, you can use the approach @GitHubSriramB  suggested, basically associate this artifact in build and write a custom task to download this artifact.

**Comment by DerGary** [comment]
@GitHubSriramB @omeshp No I don't want support for Nexus Repository because a generic Artifact with the possibility for providing variable to the release would be more helpfull for everyone.

@omeshp Thanks I tried your suggestion and it worked I created an artifact with the following command:

`Write-Host "##vso[artifact.associate artifacttype=nexus;artifactname=VSTSExtension]https://downloads.visualstudio.com/foo/bar/baz.zip"`

I now tried to get the URL in my Release Definition but how can I achieve this?
The following artifact related variables are exposed:

```
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_BUILDID] --> [2977]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_BUILDNUMBER] --> [2977]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_BUILDURI] --> [vstfs:///Build/Build/2977]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_DEFINITIONID] --> [186]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_DEFINITIONNAME] --> [Master Build Definition]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_PROJECTID] --> [baf4faf7-a4dd-4509-98ea-37d578e1e305]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_PROJECTNAME] --> [Development]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_REPOSITORY_ID] --> [7ae5db59-7a54-4ed0-bdab-aaf800614038]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_REPOSITORY_NAME] --> [Extension]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_REPOSITORY_PROVIDER] --> [TfsGit]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_REQUESTEDFOR] --> [Surname, Firstname]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_REQUESTEDFORID] --> [e15d1c3a-3204-4c85-a5c7-9ca829d9797c]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_SOURCEBRANCH] --> [refs/heads/#2820]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_SOURCEBRANCHNAME] --> [#2820]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_SOURCEVERSION] --> [2bde2456a29deb622df324e74782216137bb98e3]
[RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_TYPE] --> [Build]
```

I tried to get the value with the variable `$(Release.Artifacts.VSTSExtension)` but this variable is not set. 

How can I get the value that I set in my release?

Greetings Gary

**Comment by GitHubSriramB** [comment]
@DerGary - 

The artifact related variables you see within Release correspond to the artifact sources that are included in the Release. I believe the variables you have listed correspond to the release artifact source with alias Tasks_Vsts_Extension_Master, which is essentially the Build definition "Master Build Definition".

We currently don't support custom/generic Build artifacts contributing variables to Release.

In order to achieve what you want, you could do the following (like I suggested before):
1. Use ##vso[artifact.associate] command to associate generic artifact with Build like you have mentioned above.
2. Write custom task/script that queries Build service for artifacts given build id. The build id is available within release as one of the artifact variables. In your case, it is RELEASE_ARTIFACTS_TASKS_VSTS_EXTENSION_MASTER_BUILDID
3. Artifact details queried should have details including the url value. Set a variable that is available to subsequent tasks using ##vso[task.setvariable] command.
4. Use the variable set in subsequent tasks.

**Comment by DerGary** [comment]
Oh I didn't understood that you meant the VSTS REST API by Build service. 
That works great. Maybe it would be a good idea to add a comment to the documentation that custom types are also possible for artifact.associate

Thank you for your help.

Greetings Gary

**Comment by GitHubSriramB** [comment]
Thanks for the feedback

@bryanmacfarlane - could you take care of updating documentation for artifact.associate command as suggested?
