### ISSUE TITLE
Write endpoint username

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/azure-pipelines-tasks#6471]
From my custom task I'm trying to output some information. One of it is my endpoint username. The other one is a value from a variable called $Username.

In both cases I do get:
MDS admin is reset to '********'.

Is there a way to overcome this protection?

Thanks

**Comment by bryanmacfarlane** [comment]
@GitHubSriramB for service endpoint question

**Comment by GitHubSriramB** [comment]
@mmajcica  - All endpoint authorization parameters are getting masked by the agent. This is same as following issue: https://github.com/Microsoft/vsts-agent/issues/1207

When an endpoint auth. parameter value is masked, the string gets masked even when it gets logged through another variable. This is expected.

@bryanmacfarlane - any update on whether the service-side bug in Build is address to remove the agent from masking all endpoint authorization parameters?

**Comment by mmajcica** [comment]
@GitHubSriramB is there a way to bypass this limitation? It is not only applicable to the endpoint values, but also to any variable that has been named UserName or similar.

**Comment by mmajcica** [comment]
@bryanmacfarlane @GitHubSriramB guys any ideas about this?

**Comment by GitHubSriramB** [comment]
@mmajcica - the masking happens only based on value of endpoint authorization parameters. If value of variable named as UserName is different from the values of any of the endpoint authorization parameters, then the variable value should not get masked.

**Comment by moswald** [comment]
@mmajcica This is not a tasks bug. To suggest a new feature, please create a new post on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) site. Thank you!
