### ISSUE TITLE
Allow the Gradle task to exclude files from the test results pattern

### ISSUE THREAD

**Issue by pjquirk** [Microsoft/azure-pipelines-tasks#6476]
The Gradle task allows the user to provide a glob pattern for selecting test results to publish.  It would be helpful to allow the user to specify a path to exclude any results from.  This would let the user keep a simple glob pattern for including files (e.g., `**/Test-*.xml`) but easily exclude results from external dependencies (`!node_modules`).

Implementation could stay with a single line of input and split on a reserved character (possibly semicolon), or provide a multiline input with one pattern per line.  

Also, the tooltip text should be updated with the additional syntax for glob patterns (negation, minimatch, etc).

**Comment by madhurig** [comment]
The Gradle V2 version of the task has switched over to using findMatch method in the tool lib which is what we recommend for all tasks: https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/docs/findingfiles.md#task-lib-functions
