### ISSUE TITLE
CopySSH task Error

### ISSUE THREAD

**Issue by andmattia** [Microsoft/azure-pipelines-tasks#6524]
I try to copy file via SSH.

I use a hosted queue 
Agent Version -> Current agent version: '2.129.1'
Task         : Copy Files Over SSH
Version      : 0.115.0
Error Message:
Failed to connect to remote machine. Verify the SSH endpoint details. InvalidAsn1Error: Expected 0x2: got 0x32.

I copy the release file from this repo beacuse I don't find any guide/command how to update task from 0.115.0 to current version.

**Comment by bryanmacfarlane** [comment]
Not clear - are you suggesting a newer version fixed the issue but you had to update manually?  Is that the issue?

The error above can happen for valid reasons (can't connect to remote machine).

**Comment by andmattia** [comment]
@bryanmacfarlane I don't find the way/command to update "Copy Files Over SSH" Task. To do that I download the source code and copy/paste on agent folder but still doesn't work. How can I update my tasks via command line/ script or other option?

**Comment by bryanmacfarlane** [comment]
These tasks are deployed with the product so at next VSTS update or the next on-prem server update, you will get them.

Back to the error - that error is expected if it can't actually connect to the remote machine (network, something wrong with creds in service endpoints etc...).  So I'm not sure it's a bug.  Why do you believe it's a bug?

**Comment by andmattia** [comment]
I try to use che key generetd via putty on same machine and it works, also I try to connect via SSH from agent machine to linux target machine and it works.

**Comment by bryanmacfarlane** [comment]
InvalidAsn1 error means the PEM/key in the service endpoint is the wrong format

For example:
https://github.com/rzcoder/node-rsa/issues/3

Can you double check the service endpoint?  Or perhaps create another one?  

That is unless there's some encoding bug etc... between the service endpoint in the web down to the agent ...

**Comment by andmattia** [comment]
ok I'll try and report back if it's solve this issue.

Thanks

**Comment by andmattia** [comment]
I try to regenerate the key on server with this command
 ssh-keygen -t rsa -b 1024 -v

I upload the new id_rsa and I execute the task and I get this error
2018-03-01T12:00:26.3378785Z Setting up SSH connection to remote host xxxxxxxxx
2018-03-01T12:00:26.3716619Z ##[error]Failed to connect to remote machine. Verify the SSH endpoint details. InvalidAsn1Error: encoding too long.
2018-03-01T12:00:26.3754343Z ##[section]Finishing: Securely copy files to the remote machine

the same error happen if I use 2048in place of 1024 generation key command

**Comment by damccorm** [comment]
@andmattia is this still an issue?

**Comment by joshmgross** [comment]
@andmattia Reply to this issue if you're still dealing with this and I will re-open it.
