### ISSUE TITLE
Docker Tag Path

### ISSUE THREAD

**Issue by jrock2004** [microsoft/azure-pipelines-tasks#6532]
## Environment
- Server - VSTS or TFS on-premises?
    
    - VSTS

- Agent - Hosted or Private: 
    
    - Hosted

## Issue Description
I am trying to understand how the tag task works. It seems like it wants me to create a file in my code base but not understanding the syntax of that file. Is that documented some where? For now what I am doing is running the docker command task and doing

```
run myazureimagerepo/myimage:latest myazureimagerepo/myimage:newtag
```

Thanks for any help

**Comment by benc-uk** [comment]
Also looking for information on this task, there seems to be zero documentation! 
Why on earth does it require a text file as input? What is the format?

**Comment by bansalaseem** [comment]
@benc-uk and @jrock2004 Can you please share which tag task are you talking about? Is it a built-in task or an extension on marketplace?

**Comment by benc-uk** [comment]
@bansalaseem 
I was using the built-in task
I've given up with it. With the new YAML pipelines I just use a bash step and run `docker tag` or whatever docker command I like. The value of the Docker built-in task is almost zero

**Comment by bansalaseem** [comment]
Thanks @benc-uk for your feedback. 

I had looked up only v1/v2 version of the task and could not find it yesterday but today I looked at v0 version as well and found the path option. It was indeed very confusing. 

Secondly the task is very thin wrapper around docker.exe and as we have login/logout commands in the task, you can use them and script task and that is perfectly fine. 

Thirdly we have simplified the inputs for docker v2 task a lot and in that task we do publish the image details to our image store and show that in our [(Kubernetes UI).](https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/). It will be great if you can play with it and give us your feedback.

**Comment by bansalaseem** [comment]
Since we have removed the path option in the later versions of the task, I am closing this issue.
