### ISSUE TITLE
Feature request: .Net Core pack - add pack arguments text box

### ISSUE THREAD

**Issue by GlenAppleton** [microsoft/azure-pipelines-tasks#6567]
Task: .NET Core 
Version: v2.*

When setting up a recent NuGet build, I noticed that there is no place to add additional pack options when you select the 'pack' option in the "Command" field.  Because of this, I couldn't include pack options such as --include-symbols or --include-source for my beta packages (for example).  In order to do what I needed, I had to use the 'custom' command, which does expose the additional arguments text box.

Please add this functionality so that the 'pack' command option can keep up with changes more readily.  Thanks!

**Comment by mathnogueira** [comment]
+1

**Comment by amaljg** [comment]
Thanks @GlenAppleton for the feedback. Adding @pulkitaggarwl to consider this feedback in the next version of the task.

**Comment by hiyadav** [comment]
@alexmullans who might be the right person to consider this ?

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
