### ISSUE TITLE
VSTS Tasks which use %TEMP% should survive that folder not existing

### ISSUE THREAD

**Issue by MattGal** [microsoft/azure-pipelines-tasks#6592]
## Environment
- Server - VSTS or TFS on-premises?
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
       DevDiv, it's the same problem anywhere but if you want it's build  1437357 

## Issue Description

If the %TEMP% folder doesn't exist, the inline powershell (and likely other) tasks fail, due to trying to emit a file there.  Calling Create() on the folder before writing to it is a cheap workaround; if this is undesirable, checking that it Exists() then writing it somewhere else is a fine one too.

https://github.com/Microsoft/vsts-agent/blob/debdd414f8dfe9776e549d49abd53aaabb4e6a56/src/Agent.Worker/Handlers/PowerShellExeHandler.cs#L57  seems to indicate this was the plan at some point.

### Error logs
See the above build or just delete your temp dir and use some inline powershell on the agent:
```
2018-03-02T23:51:55.1335983Z ##[section]Starting: Clean source directory
2018-03-02T23:51:55.1511233Z ==============================================================================
2018-03-02T23:51:55.1511555Z Task         : PowerShell
2018-03-02T23:51:55.1511786Z Description  : Run a PowerShell script
2018-03-02T23:51:55.1512023Z Version      : 1.2.3
2018-03-02T23:51:55.1512244Z Author       : Microsoft Corporation
2018-03-02T23:51:55.1512526Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2018-03-02T23:51:55.1512814Z ==============================================================================
2018-03-02T23:51:55.3532174Z ##[error]Directory not found: 'C:\Users\builduser\AppData\Local\Temp\'
2018-03-02T23:51:55.3556601Z ##[section]Finishing: Clean source directory

```

**Comment by ericsciple** [comment]
do you know whether this fail on the 2.x version of the task?

**Comment by ericsciple** [comment]
[the 2.x version](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/powerShell/powershell.ps1#L63) of the powershell task uses the `agent.tempdirectory` directory.

the agent initializes that folder at the [beginning of every job](https://github.com/Microsoft/vsts-agent/blob/f45785bb3cf4c2eef4df54bf296ddf89a8bb466d/src/Agent.Worker/JobRunner.cs#L156), so it should exist.

would that solve the problem you are seeing?

**Comment by MattGal** [comment]
Yes, I think that would solve the problem, though I'll have to update the version we use to be sure.

Would it be acceptable or "too breaking" of a change to make this survivable for the old versions of the extension?

**Comment by jcagme** [comment]
It what @MattGal proposes is possible that would save us a lot of churn since we would need to check all of our build definitions

**Comment by chcosta** [comment]
It would be a lot of work because we'd need to update both the PipeBuild definitions and the generated build definitions.  Couple that with not being certain that we would have a good window (or permission) for making those changes to servicing definitions.

**Comment by ericsciple** [comment]
Do you know why the temp directory doesn't exist? It seems strange to me the temp directory doesn't exist at all.

Note, the 1.x version of the powershell task was implemented in the agent. So if we add code to workaround the issue, it will actually require an agent update on your end. Just making sure that is expected.

**Comment by MattGal** [comment]
Yes, I know exactly why;  it's because we delete it.  You might say "hey just stop doing that!" but it was a natural course of action after our build agents just keep filling up their disks, and if we made that mistake other users will too.

**Comment by ericsciple** [comment]
@TingluoHuang it sounds like a better way to accommodate this scenario would be either for the job runner or step runner to recreate the temp dir if it doesn't exist

it also sounds like a workaround would be to delete the contents of the dir instead, or recreate the dir after cleanup

**Comment by MattGal** [comment]
General best practice in .NET Code is to always call create on a directory you know you're writing a file to; if it exists, it's a noop.

**Comment by ericsciple** [comment]
It depends on what folder.

Even System.IO.Path.GetTempFileName() blows up if the temp folder doesn't exist.

**Comment by MattGal** [comment]
Sorry I meant best practice when I write code, I make no assertions for the framework itself :)

**Comment by chcosta** [comment]
`System.IO.Path.GetTempPath()` doesn't blow up, it can be used with `CreateDirectory`

**Comment by ekaterina-tatanova** [comment]
@MattGal , do you still run into this issue?

**Comment by MattGal** [comment]
> @MattGal , do you still run into this issue?

We do not, but only because in the intervening 2 years we barely use those agents any more and because we found and fixed everywhere that TEMP was getting deleted.  If tasks still use temp without ensuring its existence, this is still a bug.

**Comment by ekaterina-tatanova** [comment]
Checking file path existence was added in a later version. This issue is out of date.
