### ISSUE TITLE
Archive Files Fails with execResult ENAMETOOLONG when DISABLI

### ISSUE THREAD

**Issue by RFoerster** [Microsoft/azure-pipelines-tasks#6618]
Hi to all,

I'm experiencing problems when building our Angular-Project using Yarn and then trying to Archive the results within the angular/dist folder and having the "Prepend root folder name to archive paths" disabled (when running the task with this option enabled, everything works fine).

I've enabled debug logging which shows an exception stating an error-code "ENAMETOOLONG". It looks like the 7z.exe "can't handle" the long string of arguments being passed with all the file-names.

Please see logs attached.

## Environment

We are using VSTS, 
* account-name: foerster.visualstudio.com
* Project-name: Fredi
* Archive-Files-Version: 2.127.0
* Build-Definition: Fredi_Frontend
* last failed build: 11
* Hosted Agent (Hosted VS2017)

## Issue Description

This is our Build-Definition:
![grafik](https://user-images.githubusercontent.com/14177678/37050050-1ad8944a-2173-11e8-81bf-64de0f44cc50.png)

This is the definition of the Archive-Task:
![grafik](https://user-images.githubusercontent.com/14177678/37050088-36306420-2173-11e8-8eb6-762e96c352cb.png)

### Error logs

Please see the relevant part of the log attached to this issue.
[archiveerror.log](https://github.com/Microsoft/vsts-tasks/files/1786176/archiveerror.log)

Thank you,

Robert

**Comment by ruffzy** [comment]
I have experienced exactly the same issue. In my case I was able to change the execution environment to a linux machine and fortunately this environment does not have this file length limitation:

![image](https://user-images.githubusercontent.com/794039/40980943-fb0e88d2-68d9-11e8-956a-f6df3a16c922.png)

**Comment by moswald** [comment]
I've changed the task so that 7zip uses a file list input file, rather than a string of input files on the command line. It will become available in our next release of Azure DevOps.
