### ISSUE TITLE
How do I parse response from AzureFunction into a variable?

### ISSUE THREAD

**Issue by devkeydet** [microsoft/azure-pipelines-tasks#6640]
Is there a way to take the json response from the AzureFunction task, parse the result (similar to how we can in a condition) and set the value of a task variable based on the result?

**Comment by vithati** [comment]
@devkeydet , This is not possible with AzureFunction task. But you can set variables from your azure function using Distributed Task API. You can find the examples here https://github.com/microsoft/azure-pipelines-extensions/blob/54d88ccda05e1f37b7dcfcd7504020f3a7ea1b4f/ServerTaskHelper/DistributedTask.ServerTask.Remote.Common/TaskProgress/TaskClient.cs#L85

https://github.com/microsoft/azure-pipelines-extensions/blob/54d88ccda05e1f37b7dcfcd7504020f3a7ea1b4f/ServerTaskHelper/HttpRequestSampleWithoutHandler/MyApp.cs#L219
