### ISSUE TITLE
Agentless task: Invoke REST API - Error 411 when doing POST without parameters to Azure Webhook

### ISSUE THREAD

**Issue by Ameb** [microsoft/azure-pipelines-tasks#6687]
## Environment
VSTS account: cycba.visualstudio.com
Team Project name: Kaggle Competitions
Release Definition: test POST

**Agentless task INVOKE REST API**

## Issue Description
Using the `INVOKE REST API` agentless task i'm unable to do a simple POST to an Azure Automation runbook webhook.
The request is done without any extra header or body apart from the webhook token, as indicated by the `deployPhase` property of the exported `release.json`:
```
{
    "deploymentInput": {
        "parallelExecution": {
            "parallelExecutionType": "none"
        },
        "timeoutInMinutes": 0,
        "jobCancelTimeoutInMinutes": 1,
        "condition": "succeeded()",
        "overrideInputs": {}
    },
    "rank": 1,
    "phaseType": 2,
    "name": "Agentless phase",
    "workflowTasks": [
        {
            "taskId": "9c3e8943-130d-4c78-ac63-8af81df62dfb",
            "version": "1.*",
            "name": "Invoke REST API: POST",
            "refName": "",
            "enabled": true,
            "alwaysRun": false,
            "continueOnError": false,
            "timeoutInMinutes": 0,
            "definitionType": "task",
            "overrideInputs": {},
            "condition": "succeeded()",
            "inputs": {
                "connectedServiceName": "<>",
                "method": "POST",
                "headers": "",
                "body": "",
                "urlSuffix": "?token=<webhook token>",
                "waitForCompletion": "false",
                "successCriteria": ""
            }
        }
    ]
}
```
A screenshot is easier to check: 
![screencapture](https://user-images.githubusercontent.com/386567/37399373-cffa8f40-2781-11e8-8731-a45ec64453ce.png)

The webhook works fine when using `Postman` to make the request.
```
POST /webhooks?token=<webhook token> HTTP/1.1
Host: s2events.azure-automation.net
Cache-Control: no-cache
```
This is the `WEBHOOKDATA` received as input parameter on Azure Automation Job when the request is done via postman:
```
{"WebhookName":"start_vm","RequestBody":"","RequestHeader":{"Cache-Control":"no-cache","Connection":"keep-alive","Accept":"*/*","Accept-Encoding":"gzip","Host":"s2events.azure-automation.net","User-Agent":"PostmanRuntime/7.1.1","Postman-Token":"63beaf43-5102-4c11-ab7e-568c09d2f4a7","x-ms-request-id":"d1ee3c88-80f8-4f96-adf7-b821959fc0e3"}}
```

### Error logs
```
2018-03-14T10:58:39.4665470Z POST https://s2events.azure-automation.net/webhooks?token=<webhook token>
				Response Code: 0
				Response: An error was encountered while processing request. Exception: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>

Exception Message: The remote server returned an error: (411) Length Required. (type WebException)
```
The log doesn't help much since it doesn't display the complete request sent.

Already reported on the [Developer Community](https://developercommunity.visualstudio.com/content/problem/213781/agentless-invoke-rest-api-not-working-with-azure-a.html). 

Thanks!

**Comment by bryanmacfarlane** [comment]
Developer community is the proper place for this service side issue.  This repo and issues is for tracking issues with the tasks in this repo:  https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

I'll forward this to the proper person though to to ensure it gets attention

**Comment by bryanmacfarlane** [comment]
Forwarded the dev community issue to @bansalaseem

**Comment by Ameb** [comment]
The task is located here https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/InvokeRestApi
Same happened on #5876

**Comment by Ameb** [comment]
As pointed by @hiyadav on #6717, Sending an empty object as body `{}` is a simple workaround.

Thank you!

**Comment by AmudhaPalani** [comment]
With body {}, I am still getting error 411 on POST

**Comment by AbinsYnoox** [comment]
How can I get the output data from the call to my next task

**Comment by andrewsuiter** [comment]
@AbinsYnoox  were you able to figure out how to obtain data from the call? I am working on the same thing and have been unable to get the data to my next build task.  

Thank you,

**Comment by bansalaseem** [comment]
@andrewsuiter We dont have support for passing variables across phases yet though it is there in our backlog.

**Comment by koushik984** [comment]
@bansalaseem is there any update on the the passing of variables across phases?

**Comment by bansalaseem** [comment]
No, we dont have that support still and it will take us many months to add that support.

**Comment by nasmii** [comment]
Please add <request.ContentLength = 0;>  in "Request Body"  section in connection tab:
Request Method: POST
Additional Headers : ******
Request Body : request.ContentLength = 0;
