### ISSUE TITLE
Support for custom App_Offline.htm file

### ISSUE THREAD

**Issue by kipusoep** [microsoft/azure-pipelines-tasks#6692]
As far as I know there's no option for a custom App_Offline.htm file yet.
Would it be possible to add this feature? Maybe provide the path inside the source repo which html file should be used for App_Offline.htm?

**Comment by bryanmacfarlane** [comment]
These issues are used to track all the tasks in this repo (/tasks).  Which task are you referring to?

**Comment by kipusoep** [comment]
Sorry about that!
I'm refering to the [IISWebAppDeploymentOnMachineGroup](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/IISWebAppDeploymentOnMachineGroup) task.
Within that task there's an advanced deployment option called **Take Application Offline**.

**Comment by vincentdass** [comment]
@kipusoep , thanks for reaching out. This is a valid request and added it in backlog. Not sure about the timeline when it will be picked.

**Comment by kipusoep** [comment]
I did a quick search how this is done without VSTS, so just plain MsDeploy and it seems there's no native support for having a custom App_Offline.htm file.
The only 'work-around' I found is this:

> An easy solution that many might find suitable involves simply adding your own file also named "app_offline.htm" to your solution.
[Source](https://stackoverflow.com/a/38235912/510149)

**Comment by vincentdass** [comment]
@kipusoep , 
MSDEPLOY supports custom app offline feature but it has certain conditions:
* App offline file should exist in the destination server and need to provide relative path.
* Destination provider types are limited (we set `dest:auto` for MSBuild package, which doesnt support custom app offline feature).
![image](https://user-images.githubusercontent.com/20121508/37517923-17c9f0e6-2939-11e8-8140-7442a51358dc.png)
[[Reference](https://blogs.iis.net/msdeploy/webdeploy-3-5-rtw)]

As a workaround, you can try the [method ](https://github.com/Microsoft/vsts-tasks/issues/6692#issuecomment-373648888)you found.

You can also upload the custom app_offline, deploy the package and then remove the uploaded custom file after deployment.
![image](https://user-images.githubusercontent.com/20121508/37518116-d8e0a1e4-2939-11e8-8bfb-8c6dccad4e1d.png)

[[Reference](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/advanced-enterprise-web-deployment/taking-web-applications-offline-with-web-deploy#deploying-and-deleting-an-appoffline-file)]

**Comment by kipusoep** [comment]
@vincentdass thank you for the info, really helpful!
