### ISSUE TITLE
TFS Docker Image Build

### ISSUE THREAD

**Issue by erwabo** [Microsoft/azure-pipelines-tasks#6718]
IM trying to build a Docker Image with a TFS Build Agent. I have Docker for Windows running on the build agent, and everything goes well until it goes to run docker.exe to run the build command. This is the error Im getting.

open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Im not sure how to have the agent or the TFS build job run as elevated account. The steps I have taken so far are:

1. Run the Docker Engine Service as the TFS account
2. Given permission on the .exe itself to TFS build account
3. Added this to daemon.json {["tcp://127.0.0.1:2375", "npipe://"], "group":administrators}

Nothing seems to work....any help would be apprciated.

**Comment by bryanmacfarlane** [comment]
For the agent, it comes down to the account you choose to run the agent as and it's supported to run as whatever account you want.

Regarding what you need to do in docker, getting over to RM who works on the docker task.

**Comment by erwabo** [comment]
Well I tried our 2 different accounts for our agents and as the TFS admin account. It always gives me the same error.  _"getting over to RM who works on the docker task."_  Not sure what you mean by that exactly.

**Comment by erwabo** [comment]
Thanks! Spent 2 days on this so far and get overcome this hurdle.

**Comment by jikuma** [comment]
@erwabo, are you running the TFS agent as an interactive mode? If yes you will need to run the TFS agent as an administrator.

**Comment by jikuma** [comment]
Can you the solution mentioned here
https://blogs.msdn.microsoft.com/jikuma/2018/03/19/error-pipedocker_engine-access-is-denied-in-the-default-daemon-configuration-on-windows/

**Comment by erwabo** [comment]
Yes, I have tried several configs.  Right now I have the VSTS Service running as my own account and I'm a domain admin. I have tried 2 other service accounts that I have created and both of them are in the local administrators group on the TFS Agent server.

**Comment by erwabo** [comment]
Well it didnt complete 100%. I got the error below. Im guessing this is because the VSTS account is not the same account that running the build from TFS itself, but I get the previous error when trying to run as the tfs service account, even though its a local admin

_Step 4/4 : COPY ${source:-obj/Docker/publish} .
COPY failed: GetFileAttributesEx \\?\C:\Users\tfservice\AppData\Local\Temp\docker-builder160280044\obj\Docker\publish: The system cannot find the path specified._

**Comment by jikuma** [comment]
@erwabo, are you able to build the image outside the task? The error is for some files not being part of build context.

**Comment by erwabo** [comment]
yeah, unfortunately the docker file was created by VS or the Default TFS Project thats docker enabled...so the default docker file shows up as

FROM microsoft/aspnet:4.7.1-windowsservercore-ltsc2016
ARG source
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .

**Comment by erwabo** [comment]
I edited my docker file and it still is giving me the error. The part in bold below is what doesn't exist. Im not sure why its looking there instead of just copying right from C: here the file path actually is

Step 1/3 : FROM microsoft/aspnet:4.7.1-windowsservercore-ltsc2016
 ---> 44ac8d5a3039
Step 2/3 : WORKDIR /inetpub/wwwroot
 ---> Using cache
 ---> 243779cdf1ae
Step 3/3 : COPY C:/agent/_work/1/s/ContainerTest .
COPY failed: GetFileAttributesEx \\?\C:\Users\tfssvc!\AppData\Local\Temp**\docker-builder664378914\agent\_work\1\s\ContainerTest:** The system cannot find the path specified.

**Comment by erwabo** [comment]
Just having a hard time with this docker file.  The sources files are located C:\agent\_work\1\s\ContainerTest  and its an ASP.net app. Im 100% certain I just have the docker file configured right

**Comment by jikuma** [comment]
@erwabo can you share your sample source code if possible. It would be great if you could at least  share your docker file. 

Are you building the code before creating the image. obj/Docker/publish seems to be not present.

**Comment by jikuma** [comment]
@erwabo can you tell which type of project you created in VS. I am planning to write a blog for your scenario to help others to get started.

**Comment by bansalaseem** [comment]
@erwabo can you please share the answer to question that Jite has asked above?

**Comment by erwabo** [comment]
@jikuma I actually ended up with two different options. Since Visual Studio defaults to ~obj/Docker/publish, as you said...thats not present on the TFS Agent server.  The first thing I did was build a different docker file and added a COPY file command in the the TFS build. This copied a different dockerfile to replace the one that is generated by Visual Studio.  This was not ideal because I didnt want to have 2 docker files for every application. So I built a docker file that worked in both my local VS build and with TFS. That docker file below worked for both my local VS build and my TFS build.

FROM microsoft/aspnet:4.7.1-windowsservercore-ltsc2016
WORKDIR /app
RUN Remove-Website 'Default Web Site';
RUN New-Item -Path 'C:\containerdb' -Type Directory -Force;
COPY / / C:/containerdb/
RUN New-Website -Name 'USFS' -PhysicalPath 'C:\containerdb' -Port 80 -ApplicationPool '.NET v4.5' -Force
EXPOSE 80 
EXPOSE 1433
EXPOSE 443
ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]

**Comment by radhikaswift** [comment]
Hi Team ,I am new to docker.Configured docker for windows and developed docker file which builds nginx server to host angular application successfully.Now planning to call docker file in TFS build definition.I have added docker task to run command in Build deinftion but getting issue

018-09-07T15:44:05.6305242Z ##[debug]Absolute path for pathSegments: C:\Build\agent\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Internal\NativeBinaries\amd64/docker = C:_Build\agent\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Internal\NativeBinaries\amd64\docker
 2018-09-07T15:44:05.6305242Z ##[debug]Absolute path for pathSegments: C:\Program Files\Docker\Docker/docker = C:\Program Files\Docker\Docker\docker
 2018-09-07T15:44:05.6315253Z ##[debug]Absolute path for pathSegments: C:\Program Files\MongoDB\Server\4.0\bin/docker = C:\Program Files\MongoDB\Server\4.0\bin\docker
 2018-09-07T15:44:05.6315253Z ##[debug]Absolute path for pathSegments: C:\Windows\system32/docker = C:\Windows\system32\docker
 2018-09-07T15:44:05.6325187Z ##[debug]Absolute path for pathSegments: C:\Windows/docker = C:\Windows\docker
 2018-09-07T15:44:05.6325187Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\Wbem/docker = C:\Windows\System32\Wbem\docker
 2018-09-07T15:44:05.6335417Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\WindowsPowerShell\v1.0/docker = C:\Windows\System32\WindowsPowerShell\v1.0\docker
 2018-09-07T15:44:05.6345446Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft Network Monitor 3/docker = C:\Program Files\Microsoft Network Monitor 3\docker
 2018-09-07T15:44:05.6345446Z ##[debug]Absolute path for pathSegments: C:\Program Files\nodejs/docker = C:\Program Files\nodejs\docker
 2018-09-07T15:44:05.6355253Z ##[debug]Absolute path for pathSegments: C:\HashiCorp\Vagrant\bin/docker = C:\Vagrant\bin\docker
 2018-09-07T15:44:05.6355253Z ##[debug]Absolute path for pathSegments: %USERPROFILE%\AppData\Roaming\npm/docker = C:\Build\agent_work\1\s%USERPROFILE%\AppData\Roaming\npm\docker
 2018-09-07T15:44:05.6365241Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft\Web Platform Installer/docker = C:\Program Files\Microsoft\Web Platform Installer\docker
 2018-09-07T15:44:05.6365241Z ##[debug]Absolute path for pathSegments: C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\WindowsApps/docker = C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\WindowsApps\docker
 2018-09-07T15:44:05.6375255Z ##[debug]check path : null
 2018-09-07T15:44:05.6385223Z ##[debug]task result: Failed
 2018-09-07T15:44:05.6465176Z ##[error]Unhandled: Failed which: Not found docker: null
1.

**Comment by Anumita** [comment]
@radhikaswift are you using a Private Agent or Hosted agent?

**Comment by azooinmyluggage** [comment]
@radhikaswift I am closing the issue. If you get a chance to retry then let us know.
