### ISSUE TITLE
DownloadBuildArtifacts with buildNumber, not buildId

### ISSUE THREAD

**Issue by samssann** [Microsoft/azure-pipelines-tasks#6752]
## Environment
- Server: VSTS
- Agent: Private (OS: Ubuntu 16.04.4 LTS, Agent: 2.129.1)

## Issue Description

- Task: Download Build Artifacts

$(DependencyVersion) is a variable that is defined in the variable section of this build definition. It represents a build number from a different build definition that is set manually.

You can select different build numbers from the drop down menu.
<img width="1076" alt="screen shot 2018-03-21 at 0 11 29" src="https://user-images.githubusercontent.com/19807339/37685722-287f5aae-2c9d-11e8-9e3f-685755576397.png">

But you can't pass a build number to the field. It is somewhat misleading.
<img width="1065" alt="screen shot 2018-03-20 at 23 55 21" src="https://user-images.githubusercontent.com/19807339/37685724-2a61881a-2c9d-11e8-99de-64b0f6b159fa.png">

The reason this doesn't work is because it requires the build id, not the build number.
<img width="580" alt="screen shot 2018-03-21 at 0 14 28" src="https://user-images.githubusercontent.com/19807339/37685729-2ccd4e7c-2c9d-11e8-8777-8b57f38f8845.png">

### Request / New Feature

Could it be possible to optionally pass the build number (even by linking it manually from the link settings), so that it would find the correct build. Another great feature would be an option to utilize the latest successful build from a different build definition.

Thank you.

**Comment by GitHubSriramB** [comment]
@samssann - this is a limitation with task inputs that support drop-down. You are right - When value for the input is provided manually, the value should be Build Id. In case it is not possible to change $(DependencyVersion) to represent Build Id, you could do the following:
1. Author a custom task (could be PS script task as well) that takes $(DependencyVersion) as input and outputs the corresponding build id into an output variable, say $(DependencyVersionId). 
2. Use $(DependencyVersionId) as input in the DownloadBuildArtifacts task for the value of Build.

The task has been enhanced to support taking latest build as an option. These changes should be deployed to production in next 3-4 weeks.

**Comment by mickeycohen** [comment]
@samssann I don't see a build number input there...

**Comment by GitHubSriramB** [comment]
This issue is getting addressed with this PR:
https://github.com/Microsoft/vsts-tasks/pull/6855

**Comment by GitHubSriramB** [comment]
We have already added support for choosing latest build from a different build definition.

**Comment by GitHubSriramB** [comment]
This support is added with this PR:
https://github.com/Microsoft/azure-pipelines-tasks/pull/7879
