### ISSUE TITLE
Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)

### ISSUE THREAD

**Issue by Ro3A** [microsoft/azure-pipelines-tasks#6757]
Hi,

I'm seeing the same error message across a couple different continuous deployment pipelines today. These same pipelines worked perfectly as recently as yesterday evening.

I see that Azure Status page shows an issue with the service management API across all north american regions but it claims it is not affecting existing apps.

Failed to restart App Service 'appServiceName-staging'. Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)

I'm already restarting the staging slot prior to swapping due to failures with file locks (still, but that's a different issue). I've added an additional restart step prior to deploying to staging slot to see if that would help. It has not.

Any ideas?

**Comment by bryanmacfarlane** [comment]
Is this a specific issue with one of the tasks in this repo?  (/Tasks) or is this an error you're getting from azure during deployments?

**Comment by Ro3A** [comment]
From azure during deployment. Same message across two separate pipelines. It's happening on the deploy task

**Comment by Ro3A** [comment]
Sorry, to be clear, is is a vsts task

**Comment by Ro3A** [comment]
2018-03-21T12:51:32.1369492Z Got connection details for Azure App Service:'appServiceName-staging'
2018-03-21T12:53:32.7366884Z ##[error]Error: Failed to fetch App Service 'appServiceName-staging' publishing credentials.

**Comment by Ro3A** [comment]
@bryanmacfarlane Naturally, as I've continued to retry the release, it's finally succeeded. I would like to continue to investigate this issue though as I've had many deployment issues in VSTS that seem to come and go, and ongoing issues with file locks etc.  So if we could focus on this one and nail it down, that'd be great. 

Willing to help any way I can.

**Comment by Ajay-MS** [comment]
@Ro3A 
There was an ongoing issue with Azure Web Apps because of that you were facing this issue which has been mitigated now.

**Comment by Ro3A** [comment]
@Ajay-MS If you are referring to the azure status update today, it claimed it wasn't affecting existing apps. Bit misleading...

**Comment by Ro3A** [comment]
@bryanmacfarlane, @Ajay-MS  I'm super appreciative of the fast response guys, really impressive. Feel free to close as you see fit. My only feedback would be to get those status messages to be more accurate if possible.

**Comment by Ajay-MS** [comment]
@Ro3A 

Thanks for your response to closure.

**Comment by thedoupub** [comment]
Hello there people.

I am having exactly the same error today. 

Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)

This happens at ##[section]Starting: Azure Function App Deploy:

**Comment by rotemgrim** [comment]
i'm getting the same issue while trying to update azure function:

2019-08-13T14:33:16.3783419Z Got service connection details for Azure App Service:'BlaBla'
2019-08-13T14:33:43.4299422Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"https://backupandfuntions.blob.core.windows.net/azure-pipelines-deploy/package_156570679****.zip?***"}
2019-08-13T14:39:36.9269632Z ##[error]Error: Failed to update App service 'BlaBla' application settings. Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)

**Comment by jinfu-kooboo** [comment]
I'm getting the same issue too.

**Comment by oleksiypavlenko** [comment]
24 JUN 2021 seeing the same error since at least UTC 21:00.

**Comment by pvpetrac** [comment]
We are facing this issue as well. Due to this error app slot swap won't work anymore.

**Comment by kjeske** [comment]
Today again

**Comment by koder101** [comment]
As of today, the issue still persists.
GatewayTimeout: `The gateway did not receive a response from 'Microsoft.Web' within the specified time period.`

**Comment by nadesu** [comment]
@PhilipsonJoseph @v-saikumart - pls look into it

**Comment by coenvd** [comment]
Same issue here when deploying container in ACR to ACI when following docs: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task

**Comment by katrinsharp** [comment]
Same here with WebApp. At least getting the understanding what needs to be restarted / recreated would be very helpful.

**Comment by Apoorva-Kale** [comment]
I have faced the same issue while running the pipeline:Azure Web App on Container Deploy
Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)

**Comment by mauricio-repetto** [comment]
I'm having the same issue at this moment, anyone knows anything?.

**Comment by cc-james25** [comment]
I'm having the same error any solution?

**Comment by AkuEgor** [comment]
I'm having the same issue, with my ADO pipelines, while updating the Function App on the Deployment stage, any updates on this?

**Comment by CarlosJoseChaconChavarria** [comment]
I am having the same issue when using slot in Function App

Gateway Timeout (HTTP Status Code: 504)

error GatewayTimeout message The gateway did not receive a response from 'Microsoft.Web' within the specified time period.
