### ISSUE TITLE
IIS Web App Deploy:  How to override Environment name for "File Transforms" ?

### ISSUE THREAD

**Issue by alexiwonder** [microsoft/azure-pipelines-tasks#6831]
I enabled _XML transformation_ option in _File Transforms & Variable Substitution Options_ to have _web.config_ with _web.Release.config_ in the environment _Release_. It worked perfectly.
Now, I've changed environment name to _GroupDeployRalease_ and the transform doesn't work because environment name is used to find a matching transform file and it fails.

I couldn't find a way to override this behaviour while there are scenarios we may want to have slightly different name in environment.

**Comment by RoopeshNair** [comment]
We are evaluating option of using just web.config and web.release.config files so that you don't have to maintain environment specific files. You could use variable substitution and transformation to achieve the desired results.

**Comment by RoopeshNair** [comment]
Currently we are working issues impacting broader set of customers. We know this issue is important to you, we will continue to monitor this.

**Comment by SumiranAgg** [comment]
@alexiwonder We have a new task "File transform" where you can explicitly specify your transform, source and result files. That might be suitable to your use case.

**Comment by alexiwonder** [comment]
Nice!
Thanks :)
