### ISSUE TITLE
vstest demand not met even when using the Visual Studio Test Platform Installer task

### ISSUE THREAD

**Issue by codewithtyler** [microsoft/azure-pipelines-tasks#6838]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?

    - VSTS

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version:
      - Windows Server 2012 R2 Standard
      - 2.120.2

## Issue Description

As shown in the first screenshot below, I've added the Visual Studio Test Platform Installer task in order to give my server the vstest demand.

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/2483249/38110379-09212e74-3361-11e8-9d26-56e77a1a887d.png)

However, even though I've added this task VSTS still have thinks I haven't met the demand when trying to queue the definition. It worked a few times but then eventually quit working.

![image](https://user-images.githubusercontent.com/2483249/38110527-99b54f1a-3361-11e8-87c0-bb07477aa5ef.png)

Also I'm not sure if it makes a difference or not but I'm doing this in a release definition rather than a build definition. Did I set it up incorrectly? It seems odd to me that I'm getting this message when it's successfully installed that multiple times before.

**Comment by acesiddhu** [comment]
The setup seems fine. Can you still queue the release and see if it gets picked up. I will file a bug for this

**Comment by tylerbhughes** [comment]
Yes, I can still queue the release. It's just confusing for when I try to queue it up and it tells me that the server doesn't meet the demands I need for the release.

**Comment by cltshivash** [comment]
@bansalaseem Can you please have a look ? The bug still persists when queuing a release with test tools installer being present.

**Comment by bryanmacfarlane** [comment]
Is this a release bug?  The task satisfies that demand so it should nullify the implicit demand made by the vstest task (at least it does in build last time I checked):  https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestPlatformToolInstaller/task.json#L20

**Comment by acesiddhu** [comment]
@bryanmacfarlane this is release. Build works fine.

**Comment by sorosoro2** [comment]
@tylerbhughes, you mentioned "_It worked a few times but then eventually quit working._". Do you mean that it didn't give you a warning when you queued a release, or deployed/redeployed a release on a particular environment?

I want to understand whether you're getting the warning intermittently or consistently.

**Comment by ShreyasRmsft** [comment]
@tylerbhughes is this intermittent? Does it happen every time you try to queue a release? Also when did this issue or has it been like this ever since you started using the vstest platform tools installer?

**Comment by tylerbhughes** [comment]
@ShreyasRmsft No, it happens every time. It's been like this ever since I started using the VSTest Platform Installer.

**Comment by ShreyasRmsft** [comment]
@sorosoro2 what is the status of the fix? When is it going in?

**Comment by ShreyasRmsft** [comment]
@sorosoro2 any updates here?

**Comment by sorosoro2** [comment]
The fix is being rolled out. @tylerbhughes , can you share your account name? I can verify if your account has the fix.
