### ISSUE TITLE
[Feature request] Expose source branch latest commit id.

### ISSUE THREAD

**Issue by MirzaSikander** [Microsoft/azure-pipelines-tasks#6841]
## Environment
- Server - VSTS or TFS on-premises?
VSTS

- Agent - Hosted or Private: 
 Linux hosted

## Issue Description
There is no way to get feature branch (source branch) latest commit id during a build initiated with a pull request. There is only one commit id available through `BUILD_SOURCEVERSION`, but that corresponds to a temporary commit id generated by the merge. 

Example:
```
master latest commit id = 100
feature branch latest commit id = 200
pull request [feature -> master] merge commit id = c23
```
In this case `BUILD_SOURCEVERSION` will be `c23`. 

The request here is that there should be a separate variable to get `200`. Something like `SYSTEM_PULLREQUEST_SOURCEVERSION`

**Comment by moswald** [comment]
@MirzaSikander I have created a [Developer Community post](https://developercommunity.visualstudio.com/idea/384127/expose-source-branch-latest-commit-id.html) to track this issue. Please follow the link to vote up the suggestion. Thank you!
