### ISSUE TITLE
Service Fabric Deploy Task should allow to take SF connection from publish profile instead of taking from Cluster Connection Service endpoint

### ISSUE THREAD

**Issue by krish-gh** [Microsoft/azure-pipelines-tasks#6846]
## Environment
- Server - VSTS or TFS on-premises?
    
    - VSTS

- Agent - Hosted or Private: 
    
    - Private

## Issue Description

ServiceFabricDeploy: 

Service Fabric Deploy Task should allow to take SF connection from publish profile instead of taking from Service endpoint. This would allow to automate the deployment from a generated publish profile from script. The creation of service endpoint in VSTS is a manual process and for a highly automated release process for big project, we do not want to create that Cluster Connection endpoint manually for multiple environment and rather would prefer to generate the publish profile and populate the endpoint and credential taking output from cluster bootstrapping and then feed it to this deploy task since it already has a provision of providing publish profile path.

**Comment by pulkitaggarwl** [comment]
@krish-gh 
Thanks for reaching out. 
SF endpoint creation requires information such as certificate and password. Wanted to hightlight that and check if you are ok to maintain that as part of code ?

**Comment by krish-gh** [comment]
That should be fine..

**Comment by bishal-pdMSFT** [comment]
@krish-gh we haven't heard this requirement from any other customer. Most of the people actually want the connection to be defined in service endpoint as it enables them to create a secure(proper permissions set on service endpoints), well-defined(deployment to a particular prod environment will happen only through a particular release environment) deployment workflow.
FWIW you can create service endpoint programmatically using [REST API](https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/endpoints/create?view=vsts-rest-5.0).
