### ISSUE TITLE
Getting error "Invalid results file. Please make sure the Test Result Format field in the task matches the result format of the file:" publishing junit format test result

### ISSUE THREAD

**Issue by BeebMeister** [Microsoft/azure-pipelines-tasks#6877]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Getting this error with the publish test results task. Attached is the results file it is failing on. This does validate in a simple test project against the schema referenced for JUNIT and the publish test result format is configured as JUNIT.

### Error logs

[Insert error from the logs here]
[5_Publish DUnit Test Results.txt](https://github.com/Microsoft/vsts-tasks/files/1876875/5_Publish.DUnit.Test.Results.txt)
[DUnit.zip](https://github.com/Microsoft/vsts-tasks/files/1876882/DUnit.zip)

**Comment by abhishkk** [comment]
@Sachin077 and @SadagopanRajaram Issue looks like in _Publish Test Results_ task. Can you have a look?

**Comment by navin22** [comment]
@BeebMeister: The DUnit.xml is not compliance with the JUnit XML that we support. Here is the schema that we support: [supported xsd schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) 

Basically I don't see any `testcase` nodes in your xml under `testsuite` tag. `testsuite` says that it has tests with `test` attribute but there are no `testcase` tags.

**Comment by BeebMeister** [comment]
So I coded to that schema and file does pass schema validation. The testcase element is minOccurs="0.

I am not actually using junit, I am modifying a legacy test runner created for dunit (Delphi tests) and coded to that schema. The only examples of test results I found online only had testcase element when there was a test failure.   Adding the testcase element did fix the problem. Thanks for the help.


Bob Burmeister | Sr. Software Architect
Alogent
Office 770.752.6428

**Comment by SadagopanRajaram** [comment]
Based on the comment from user ,the issue seems to be resolved. Closing the issue

**Comment by Nbhonrao** [comment]
i have user orderedTest.OrderedTest in tfs build to run the test case in specific order but at the end i am getting an error "Invalid results file. Make sure the result format of the file 'temp.trx' matches 'VSTest' test results format."
any solution to this ?
