### ISSUE TITLE
VSTS Keyvault Task

### ISSUE THREAD

**Issue by jgardner04** [microsoft/azure-pipelines-tasks#6898]
## Environment
- Server - VSTS
Account name: jogardn.visualstudio.com
Team project name: DevContainer
Build definition name: DevContainer-Container-CI
Build Number: Build 20180406.8 

- Agent - Private: 
Ubuntu Linxu 16.04
Agent version: 2.0.0

## Issue Description
Multi-line Key Vault secrets create unpredictable behavior with variables in VSTS build tasks

### Steps to Repro
1. Create a Key Vault Secret with a multi line file (ssh private key is the file I used)
2. Create an Azure Key Vault build task and grab the key
3. Create a build task for a docker file with the following

```Dockerfile
FROM alpine
ARG test
RUN echo -e "${test)"
CMD ['sh']
```

4. Add a build argument `test=$(yourSecretNameHere)`

### Local build mitigation steps
I did the following to rule out issues with Docker build
```Powershell
$privateKey=Get-AzureKeyVaultSecret -VaultName <yourVaultNameHere> -Name <yourSecretNameHere>
$privateKeyText=$privateKey.SecretValueText
```
With the secret stored in a Powershell variable I then fed that to a local Docker build step

```docker
docker build -t test --build-arg test=$privateKeyText
```
With the local build I am able to see the multi line secret in the build.

### Additional repro steps
Create a bash shell script that takes an arg and then runs echo against it. This will throw unpredictable output into the log. There are multiple lines from the variable but they are not in the correct order.

**Comment by jgardner04** [comment]
## Additional information
I created a shell script that simply accepts a parameter and then runs `echo -e "${1}"` to output the variable. I created a Shell Script task in my build to output that to the log. I am able to see the key file output but it is out of order. 

In reviewing the [code](https://github.com/Microsoft/vsts-tasks/blob/85e55f3ad6e0f3d1cc48bcf68d6bbf05578844b7/Tasks/AzureKeyVault/operations/KeyVault.ts#L217) for this task and my logs I was seeing an error 'CouldNotMaskSecret'. 

I continued to look at the code and saw that there is a flag [SYSTEM_DONOTMASKMULTILINESECRETS](https://github.com/Microsoft/vsts-tasks/blob/85e55f3ad6e0f3d1cc48bcf68d6bbf05578844b7/Tasks/AzureKeyVault/operations/KeyVault.ts#L183). I set this flag and am able to see the secret print correctly in my shell script. However, it prints multiple times and is still not usable as an ARG in a Dockerfile.

**Comment by lovakumar** [comment]
Can you try passing "$(yourSecretNameHere)" as argument. i.e. enclose your secret variable with double quotes. This issue is nothing to do with key vault but related to multi line command line arguments.

**Comment by jgardner04** [comment]
@lovakumar doing this gives me a little more information. The Docker build task is breaking the cert up into multiple `--build-arg` statements.  An obviously shortened version below
```bash
/myagent/_work/4/s/Dockerfile --build-arg privateKey="-----BEGIN RSA PRIVATE KEY----- --build-arg Proc-Type: 4,ENCRYPTED --build-arg DEK-Info: AES-128-CBC,moreKeyInformationHere
```
The rest of the script looks like it breaks up a new --build-arg at each new line.

**Comment by lovakumar** [comment]
@jikuma can you please help with this docker issue.

**Comment by jgardner04** [comment]
Since we are looking at the docker build task, I did validate that if I use PoSH locally to assign the Key Vault Secret Text to a variable and then use it in the Docker Build on my local machine the variable is passed to a single build arg and then to the docker image as expected.

**Comment by jgardner04** [comment]
@jikuma so what you are saying is that the VSTS task intentionally breaks the lines up into individual build arguments?

**Comment by jikuma** [comment]
The current implementation of the build argument is such that you can enter multiple build arguments in the text box. Each separated by new line.  Fixing the problem you are facing requires breaking this behaviour. Hence I have marked it as an enhancement to support multiline build arguments.

**Comment by jgardner04** [comment]
@jikuma Ok, just making sure I understood. Thank you for the clarification.

**Comment by N-Usha** [comment]
@bryanmacfarlane as this is a platform feature ask and is not specific to Azure Key Vault task.

**Comment by Kevinf63** [comment]
After scouring the internet for some time, I stumbled upon this [Sprint 215 Update from January 23rd 2023](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/pipelines/sprint-215-update#ability-to-disable-masking-for-short-secrets):

> ## Ability to disable masking for short secrets
>
>Azure Pipelines masks secrets in logs. Secrets can be variables marked as secret, variables from variable groups that are linked to Azure Key Vault or elements of a Service Connection marked as secret by the Service Connection provider.
>
>All occurrences of secret value are masked. Masking short secrets e.g. '1', '2', 'Dev' makes it easy to guess their values e.g. in a date: 'Jan 3, 202***'
>It's now clear '3' is a secret. In such cases you may prefer not masking the secret altogether. If it's not possible to not mark the value as secret (e.g. the value is taken from Key Vault), you can set the **AZP_IGNORE_SECRETS_SHORTER_THAN** knob to a value of up to 4.
