### ISSUE TITLE
Publish Test Result 2.x - Invalid Results File error

### ISSUE THREAD

**Issue by vzalamea** [microsoft/azure-pipelines-tasks#6899]
## Environment
VSTS
Private Agent v2.131 on Windows Server 2016
Test result format: VSTest

## Issue Description
We are using Progress (formerly Telerik) Test Studio to create .tstest UI test files.  We are running ArtOfTest.Runner.Exe with a custom list with 2 tests.  ArtOfTest.Runner.Exe produces a .aiiresult file.  We are using a custom console app to convert .aiiresult to a .trx file using Telerik's PublishManager.CreateTRX method.  The resulting .TRX file opens fine in Visual Studio 2017 Enterprise.

## Publish Test Result log entry:
```
2018-04-08T00:26:48.3070506Z ##[section]Starting: Publish Test Result
2018-04-08T00:26:48.3073097Z ==============================================================================
2018-04-08T00:26:48.3073183Z Task         : Publish Test Results
2018-04-08T00:26:48.3073248Z Description  : Publish Test Results to VSTS/TFS
2018-04-08T00:26:48.3073311Z Version      : 2.0.4
2018-04-08T00:26:48.3073368Z Author       : Microsoft Corporation
2018-04-08T00:26:48.3073433Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613742)
2018-04-08T00:26:48.3073501Z ==============================================================================
2018-04-08T00:26:48.7872500Z [command]C:\vstsagent\VinceSmokeTestAgent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.0.4\modules\TestResultsPublisher.exe @C:\vstsagent\VinceSmokeTestAgent\_work\_temp\86b431b0-3ac3-11e8-a2eb-c1bb623744b3.txt
2018-04-08T00:26:50.2488566Z ##[warning]Invalid results file. Make sure the result format of the file 'C:\vstsagent\VinceSmokeTestAgent\_work\r1\a\TestStudioResults\myresult.trx' matches 'VSTest' test results format.
2018-04-08T00:26:50.3876192Z ##[section]Async Command Start: Publish test results
2018-04-08T00:26:50.3876488Z ##[section]Async Command End: Publish test results
2018-04-08T00:26:50.3877062Z ##[section]Finishing: Publish Test Result
```

## Contents of generated TRX file.
&lt;TestRun id=&quot;51fede78-3122-4626-8a09-9475cdc75164&quot; name=&quot;VinceSmokeTestAgent&quot; runUser=&quot;VinceSmokeTestAgent&quot; xmlns=&quot;http://microsoft.com/schemas/VisualStudio/TeamTest/2006&quot;&gt;
  &lt;TestRunConfiguration name=&quot;Local Test Run&quot; id=&quot;19431567-8539-422a-85d7-44ee4e166bda&quot;&gt;
    &lt;Description&gt;Test Results for MyTestList&lt;/Description&gt;
    &lt;Deployment runDeploymentRoot=&quot;RunResult&quot; /&gt;
    &lt;TestTypeSpecific /&gt;
  &lt;/TestRunConfiguration&gt;
  &lt;ResultSummary outcome=&quot;Completed&quot;&gt;
    &lt;Counters total=&quot;2&quot; executed=&quot;2&quot; passed=&quot;2&quot; error=&quot;0&quot; failed=&quot;0&quot; timeout=&quot;0&quot; aborted=&quot;0&quot; inconclusive=&quot;0&quot; passedButRunAborted=&quot;0&quot; notRunnable=&quot;0&quot; notExecuted=&quot;0&quot; disconnected=&quot;0&quot; warning=&quot;0&quot; completed=&quot;0&quot; inProgress=&quot;0&quot; pending=&quot;0&quot; /&gt;
  &lt;/ResultSummary&gt;
  &lt;Times creation=&quot;2018-04-07T17:26:17.0000000-07:00&quot; queuing=&quot;2018-04-07T17:26:17.0000000-07:00&quot; start=&quot;2018-04-07T17:26:17.0000000-07:00&quot; finish=&quot;2018-04-07T17:26:46.1910405-07:00&quot; /&gt;
  &lt;TestDefinitions&gt;
    &lt;GenericTest id=&quot;2c7b1c2c-2670-4e13-976b-a259923f70ef&quot; name=&quot;GetQuote&quot; storage=&quot;GetQuote.tstest&quot;&gt;
      &lt;Css projectStructure=&quot;&quot; iteration=&quot;&quot; /&gt;
      &lt;Owners&gt;
        &lt;Owner name=&quot;&quot; /&gt;
      &lt;/Owners&gt;
    &lt;/GenericTest&gt;
    &lt;GenericTest id=&quot;4b33fa94-8553-49dc-a774-de01e5eaaf04&quot; name=&quot;LogInLogOut&quot; storage=&quot;LogInLogOut.tstest&quot;&gt;
      &lt;Css projectStructure=&quot;&quot; iteration=&quot;&quot; /&gt;
      &lt;Owners&gt;
        &lt;Owner name=&quot;&quot; /&gt;
      &lt;/Owners&gt;
    &lt;/GenericTest&gt;
  &lt;/TestDefinitions&gt;
  &lt;TestLists&gt;
    &lt;TestList id=&quot;8c84fa94-04c1-424b-9868-57a2d4851a1d&quot; name=&quot;Results Not in a List&quot; /&gt;
    &lt;TestList id=&quot;19431567-8539-422a-85d7-44ee4e166bda&quot; name=&quot;All Loaded Results&quot; /&gt;
  &lt;/TestLists&gt;
  &lt;TestEntries&gt;
    &lt;TestEntry testId=&quot;2c7b1c2c-2670-4e13-976b-a259923f70ef&quot; testListId=&quot;8c84fa94-04c1-424b-9868-57a2d4851a1d&quot; executionId=&quot;143a25cd-4169-403a-b998-59d286a0a5e7&quot; /&gt;
    &lt;TestEntry testId=&quot;4b33fa94-8553-49dc-a774-de01e5eaaf04&quot; testListId=&quot;8c84fa94-04c1-424b-9868-57a2d4851a1d&quot; executionId=&quot;2fda74dc-8443-445e-9bb5-9c8560b461f0&quot; /&gt;
  &lt;/TestEntries&gt;
  &lt;Results&gt;
    &lt;GenericTestResult executionId=&quot;143a25cd-4169-403a-b998-59d286a0a5e7&quot; testId=&quot;2c7b1c2c-2670-4e13-976b-a259923f70ef&quot; testName=&quot;GetQuote&quot; testListId=&quot;8c84fa94-04c1-424b-9868-57a2d4851a1d&quot; computerName=&quot;VINNYSERVER2012&quot; duration=&quot;00:00:14.2505020&quot; startTime=&quot;2018-04-07T17:26:20.5566638-07:00&quot; endTime=&quot;2018-04-07T17:26:34.8071658-07:00&quot; testType=&quot;13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b&quot; outcome=&quot;Passed&quot;&gt;
      &lt;Output /&gt;
    &lt;/GenericTestResult&gt;
    &lt;GenericTestResult executionId=&quot;2fda74dc-8443-445e-9bb5-9c8560b461f0&quot; testId=&quot;4b33fa94-8553-49dc-a774-de01e5eaaf04&quot; testName=&quot;LogInLogOut&quot; testListId=&quot;8c84fa94-04c1-424b-9868-57a2d4851a1d&quot; computerName=&quot;VINNYSERVER2012&quot; duration=&quot;00:00:07.3872624&quot; startTime=&quot;2018-04-07T17:26:37.5277447-07:00&quot; endTime=&quot;2018-04-07T17:26:44.9150071-07:00&quot; testType=&quot;13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b&quot; outcome=&quot;Passed&quot;&gt;
      &lt;Output /&gt;
    &lt;/GenericTestResult&gt;
  &lt;/Results&gt;
&lt;/TestRun&gt;

**Comment by vzalamea** [comment]
I had to edit my .trx file to rename GenericTestResult nodes to "WebTestResult"

The TestResultsPublisher.exe helper app depends on Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultsParser.  

The method:
private TestRunData ParseTestResultFile(TestRunContext runContext, string filePath)

looks for UnitTestResult and WebTestResult nodes but does not try to look for GenericTestResult.

Please add functionality to look for GenericTestResult nodes.  Thank you.

**Comment by madhurig** [comment]
@vzalamea : 
Thanks for your feedback. For publishing tests results from VS, we recommend using the VSTest task. The "PublishTestResults" task is primarily for non-VS test results. 

Thanks,
Madhuri

**Comment by vzalamea** [comment]
@madhurig: Thanks!  Yes, I'm trying to publish a non-VS test result; however the task does not support .aiiresult files from Telerik's test runner.  I convert the .aiiresult file to a .trx file using a custom tool but it creates <GenericTestResult> nodes that this task doesn't search for.

**Comment by Abinell** [comment]
Dear all,  Is there any update on this issue. now I am trying to automate telerik with TFS 2015. How Can I publish reports through build ?
