### ISSUE TITLE
MsBuild task should support a list of given solutions

### ISSUE THREAD

**Issue by thomasdgx** [Microsoft/azure-pipelines-tasks#6975]
MsBuild task allows to configure the project(s) which should be build.

![grafik](https://user-images.githubusercontent.com/38347410/38726402-56915ad0-3f0a-11e8-9771-63828bb42e94.png)

Here you can provide one Msbuild file (proj or solution) or a search pattern. I would like to provide a list of solutions in order to get deterministic execution.

Instead of providing *.sln I would prefer to state 
> foo.sln;bar.sln

Hence foo get compiled first and bar afterwards. 

The separator could be semicolon or some other predefined separator.

## Advantage
If the solutions have some dependencies, then the wildcard is not deterministic because we can not order the results. If I am able to provide the list which gets executed in the given order then I can compile a set of solutions in the right order without maintaining an "overall master solution"

**Comment by bryanmacfarlane** [comment]
would need to be a new major version likely

**Comment by bryanmacfarlane** [comment]
Chat with @ericsciple - we wanted to do find match enhancements here (this being one) and when we talked through it at one point, there was a assertion of new major versions.  But we can discuss.

@daveVSTS 

The current solution is to add multiple msbuild steps.

**Comment by daveVSTS** [comment]
This is reasonable.  I will add it to the backlog and sync with Eric.

**Comment by ericsciple** [comment]
Semicolon actually works today because this still uses the old legacy matching patterns (on windows). You may need to root the second path. foo.sln;$(system.defaultworkingdirectory)\bar.sln

**Comment by ericsciple** [comment]
@daveVSTS Updating to the new match patterns without bumping the major version might be feasible, if on Windows the old pattern is detected and converted to the new pattern. Might be some corner cases where this would not work. Probably very unlikely, we can go over the details.

**Comment by ericsciple** [comment]
@daveVSTS here is a description of the [legacy patterns](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/FullHelp/Find-VstsFiles.md).

Here is guidance on the [new patterns](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/findingfiles.md). Use the default settings (don't support brace expansion).

**Comment by thomasdgx** [comment]
If I get it right here is the call: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/MSBuild/msbuild.ts

![grafik](https://user-images.githubusercontent.com/38347410/38793907-64c91674-4153-11e8-8e71-b55a895860ef.png)

I can send a pull request if you agree on my proposal: I would split the solution variable by semicolon and iterate over all results. That way it supports "foo.sln;bar.sln" as well as "f*.sln;**\b*.sln".

**Comment by moswald** [comment]
@thomasdgx I am reviewing our open issues this week. If you create this PR I think @ericsciple will be happy to review it.
