### ISSUE TITLE
##vso[task.uploadsummary] - Upload HTML file with Internal Style - doesn't work

### ISSUE THREAD

**Issue by pungarg** [Microsoft/azure-pipelines-tasks#6997]
## Environment
- VSTS on-prem
Agent runs on windows server 2008 R2 Enterprise SP1

## Issue Description

I am uploading a collapsible html file. The file is successfully uploaded and is visible in the summary Tab of the release. However the whole content of the file is displayed as a simple html page and collapse & expand function is not working. However, same is working fine in TFS. 
Change the extension of attached file to .html

[Test.txt](https://github.com/Microsoft/vsts-tasks/files/1914959/Test.txt)

**Comment by bryanmacfarlane** [comment]
This doesn't seem to be an issue with tasks in this repo, correct?  We can reactivate with task name, more info
