### ISSUE TITLE
PowerShell version 2 (preview) Task missing support for Arguments

### ISSUE THREAD

**Issue by PaulMEdwards** [Microsoft/azure-pipelines-tasks#7029]
The PowerShell version 2.* (preview) Task Inline Type appears to be missing support for command line Arguments to be specified as was/is available in version 1.*.

![ps_inline-v1](https://user-images.githubusercontent.com/153847/39027374-6ec16edc-4406-11e8-91ba-32e656943b81.png)
![ps_inline-v2](https://user-images.githubusercontent.com/153847/39027375-6edf91f0-4406-11e8-8243-a7842a012056.png)

Crossposted here: https://developercommunity.visualstudio.com/content/problem/237299/powershell-version-2-preview-task-missing-support.html

**Comment by ericsciple** [comment]
@PaulMEdwards Doesn't the second screenshot give you the same result?

**Comment by PaulMEdwards** [comment]
@ericsciple thank you for the rapid reply!
When initially migrating from the deprecated 3rd party PowerShell++ Inline task to the PowerShell 2.* Preview a while back, it did not work... I will try again and report back ASAP, likely EOD today or early next week.

**Comment by DarqueWarrior** [comment]
Are arguments going to be shown for inline?  I can't upgrade until it does.

**Comment by bergmeister** [comment]
I have raised this at the start of this year in issue #5914 already and the inline option still has not got arguments. This is a blocker for release definitions since releases do not support yaml

**Comment by ericsciple** [comment]
This has since been added.

**Comment by ericsciple** [comment]
Sorry, arguments have only been added for file path only. For inline, add the arguments inline.
