### ISSUE TITLE
vsts-npm-auth: Invalid signature

### ISSUE THREAD

**Issue by niklaskallander** [Microsoft/azure-pipelines-tasks#7051]
Hi,

We've started getting "invalid signature" errors when re-generating credentials for our npm package feeds in vsts:

![image](https://user-images.githubusercontent.com/10317221/39124899-67e0aba6-46fd-11e8-8a36-61a73324c75b.png)

We've tried updating vsts-npm-auth to no avail. You've changed the ssl certificate recently on the host, might that have anything to do with this?

(Generating credentials directly from within vsts still works fine.)

Thanks (:

**Comment by przelu** [comment]
Hi All,

We are getting 'TF31001 (...) Invalid signature' when trying to connect to Work via Excel Team addin. 

![image](https://user-images.githubusercontent.com/33295482/39238075-9eac4f9c-487d-11e8-93fb-3b253d20e14d.png)

**Comment by satbai** [comment]
Running the command with detailed verbosity might help getting more information out of the error. 
Try vsts-npm-auth -config .npmrc -v detailed

**Comment by adhiggs** [comment]
Having the same issue as @przelu. Any ideas?

![2018-05-02 14_20_01-connect to team foundation server](https://user-images.githubusercontent.com/38925938/39549833-18d1ba46-4e14-11e8-85a8-bdfa8b60b7bb.png)

**Comment by przelu** [comment]
Solved for me, I did nothing and it started to work...

**Comment by adhiggs** [comment]
Also cleared on my side, although it also cleared out all of my saved servers. That said, they did connect once I added them back.

**Comment by alexmullans** [comment]
This was a server-side issue that is now fixed. Closing...
