### ISSUE TITLE
npm: Add "npm ci" as a dropdown option

### ISSUE THREAD

**Issue by simonua** [Microsoft/azure-pipelines-tasks#7083]
## Environment
- Server - VSTS or TFS on-premises? VSTS

## Issue Description
This regards the **npm** task.  
Presently, these are the command options:

![image](https://user-images.githubusercontent.com/8005145/39312037-7ad3ec8c-493c-11e8-978e-ee4df5673c7f.png)

[npm 5.7.0](https://github.com/npm/npm/releases/tag/v5.7.0) added the `npm ci` task, which is primarily intended for CI environments and speeds up npm installs by solely considering the package-lock.json for installs. 
The ask is to **add another dropdown option for `install (ci)`** or similar (but not making `npm ci` the install default as older npm versions would fail and users may not wish to be prescribed this install approach). Delivering this functionality would allow our administrators an easier, more consistent and perhaps less error-prone configuration.

The current work-around is a custom setup:

![image](https://user-images.githubusercontent.com/8005145/39312061-87bf2754-493c-11e8-8d36-dca3b02e2344.png)

The [documentation](https://docs.microsoft.com/en-us/vsts/build-release/tasks/package/npm?view=vsts) should also be updated subsequently.

**Comment by simonua** [comment]
@bryanmacfarlane @keithrob, I just came across this snippet on the npm blog from April 23rd for the now-released npm@6 (emphasis mine):

> First there are a few new features, these will initially **ship as npm@6 minor** releases:
...
As an optimization, `npm install` will be updated to be an alias for `npm ci` when they would produce the same result, that is, that your package-lock is compatible with your package.json and you’re starting with no node_modules.

https://blog.npmjs.org/post/173239798780/beyond-npm6-the-future-of-the-npm-cli

So while there would be immediate benefit for my request now, it appears that in a matter of a few weeks or months, it may no longer be necessary, so this may drop in priority.

**Comment by AndrewCraswell** [comment]
The hosted agents are running npm 5.6, so even when npm creates the alias, we're still limited by whatever version of npm is on the agent.

**Comment by simonua** [comment]
@AndrewCraswell, I see. I think there's still benefit in deferring the responsibility as to whether `npm install` or `npm ci` is executed to us users since Microsoft's default of `npm install` would remain. Would you agree?

**Comment by alexmullans** [comment]
Closing this as WF. In the upcoming quarter, we'll be moving away from the full-featured Artifacts-related tasks (which have many issues like this because they don't offer the full command flexibility of the underlying tasks) and recommending calling npm directly. See the [design here](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/artifacts-in-pipelines.md) for more details.
