### ISSUE TITLE
npm service endpoint is missing

### ISSUE THREAD

**Issue by sachinzen** [Microsoft/azure-pipelines-tasks#7087]
## Environment
- Server - TFS on-premises version 2017 Update 3
- Agent - Private: 

## Issue Description

We compiled that latest version of Npm task following your instructions and uploaded it to the TFS server. We can see the updated version available but there is no npm endpoint available in the service endpoint list.
Did I miss something?

**Comment by bryanmacfarlane** [comment]
Can you point to the instructions you're referring to for how to patch an old TFS server with latest task code?  Currently that's unsupported so I'm surprised.

**Comment by sachinzen** [comment]
Hi Bryan,
I am following below instructions to build new npm build step
https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md

**Comment by sachinzen** [comment]
Thanks Bryan. So that means there is no way we can the "npm" type service endpoint available/deployed on TFS 2017 Update 3 server? The confusion also happened because of the MS Documentation listing 2017 as one of the supported versions:
https://docs.microsoft.com/en-us/vsts/build-release/tasks/package/npm?view=tfs-2017 

Thanks!

**Comment by bryanmacfarlane** [comment]
I'm going to let @keithrob and packaging chime in on the service endpoint.  "no way" is drastic - I'm sure there's a way to get it all lined up :)  Just whether it's documented and clear.

FWIW, we are thinking about creating "update packs" for old servers but that really relies on each task setting it's min version correctly.  But it's on our radar to first class support what you're asking.  Knowing that tasks interact with other stuff on the service (endpoints, web controls etc...) is what has stopped us from first class support.  hth

**Comment by aldoms** [comment]
Unfortunately, the npm service endpoint was added after TFS Update 2017 Update 3, it should be available starting from TFS 2018. So even if you were able to successfully build and publish the new version of the task, you won't be able to add a service endpoint since those are defined independently of the task.

The documentation on the npm task shows in which TFS version the task first appeared, which is why it's even showing TFS 2015, sorry for the confusion.

**Comment by sachinzen** [comment]
Thanks for the information.
Since it will take a while for us to move to TFS 2018 we queried TFS 2018 npm endpoint details and are trying to deploy using extension. Do you see any problems/concerns doing this way? We did it in test and uploaded npm task is able to recognize it. Please let us know if you suggest any better way to do it.

Also, we noticed a length limitation on the password field of the endpoint. You may want to look into this as it is causing problems while working with larger length tokens.

Thanks!

**Comment by alexmullans** [comment]
@sachinzen were you able to get this working, or updated to TFS 2018?

**Comment by alexmullans** [comment]
Closing this due to age/inactivity.
