### ISSUE TITLE
Build Failing at Get Sources Step

### ISSUE THREAD

**Issue by vinaysandela** [Microsoft/azure-pipelines-tasks#7112]

**Comment by scottboehmer** [comment]
If you run the same set of tf commands on a dev machine, is the expected file on disk in that location?

Running a build with the system.debug variable set to true could provide additional logging. Another way to get more data would be to use a command line or script task in the build to record which directories and files are actually present on the agent after the get sources step.

My best guess without more information is that the build user account doesn't have access to the xml file that Ant is looking for. Lacking read permission would result in the file not being on disk even when the tf tasks succeed.

**Comment by vinaysandela** [comment]
I have reran the build with System.debug set to true. 

Attached is the detailed Log. 
[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/1964533/1_Build.txt)

This shows a different error. I think the issue is at the Getting Sources step itself. Please Suggest. Thanks

**Comment by scottboehmer** [comment]
Have you tried inspecting the contents of the disk with a command line or script task to confirm that the xml file is actually missing?

If it is missing, the next step would be to check permissions on the file to ensure that the build agent would be able to read it.

**Comment by moswald** [comment]
@vinaysandela Since the issue description is empty I'm going to close this, but if you are still having problems please reopen with full details. Thank you.
