### ISSUE TITLE
"Copy Files" VSTS task throws an error and stops file copy when "Advance/Overwrite" option is unticked

### ISSUE THREAD

**Issue by mivica** [Microsoft/azure-pipelines-tasks#7114]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS 
    
- Agent - Hosted or Private: 
        - Private agent running on Windows Server 2016 DC

## Issue Description
When "Advance/Overwrite" option is unticked, "Copy Files" VSTS task throws an error
"##[error]Error: Failed cp: cp: dest file already exists: " and then stops copying even when "Continue On error" is selected. It would be good to have a switch to skip existing file and continue copy without throwing an error?
An example scenario is where "Overwrite" is unticked to avoid unnecessary file copies/overwrites when flattening many folders with possible file duplication. Copy the file once and then skip it if found again in the different source folder to lower the execution time.

### Error logs

[Insert error from the logs here]

**Comment by bryanmacfarlane** [comment]
It's by design that it fails if you don't select overwrite and it exists.   Continue on error doesn't mean the task won't fail and stop.  It means that when it does fail and stop, the agent will continue on and run subsequent tasks.
