### ISSUE TITLE
NPM task 'Custom Registries' config should allow to select external NPM registries

### ISSUE THREAD

**Issue by burndeal** [microsoft/azure-pipelines-tasks#7168]
Currently there are 2 options to select a registry:
1.  "Registries in my .npmrc"
2.  "Registry I select here"

With option 2, it would be nice to be able to select a registry that isn't hosted in VSTS.   I realize this can be worked around using the "--registry" argument, but having the option to select one of the configured npm services would make config a lot cleaner.

**Comment by aldoms** [comment]
If the registry you want is specified in your .npmrc, you can add authentication for it using a [service endpoint](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/service-endpoints?view=vsts#sep-npm).

@alexmullans, any thoughts on adding a registry configured as a service endpoint that would override the .npmrc similar to what we do with VSTS feeds?

**Comment by burndeal** [comment]
True, but having the option in the task would be more flexible, especially for the use case of having different publish repositories for dev/production workflows.

For instance, it would be nice to force production builds to only pull or publish packages to/from a production registry, using only the vsts task, instead of relying on developers to configure their npmrc/package.json correctly, or having to do some auxiliary tasks in the build to switch to the correct npmrc.

**Comment by burndeal** [comment]
I should mention that this really only applies to the "install" and "custom" commands.  The "publish" command works well enough to select an external registry (but it would be nice to add arguments to the publish command, like "--tag", but that's a separate issue)

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
