### ISSUE TITLE
Nuget 2.* task with additional arguments

### ISSUE THREAD

**Issue by memark** [Microsoft/azure-pipelines-tasks#7170]
I'm currently trying to migrate from the deprecated VSTS task `NuGet Packager 0.*` to the new VSTS task `NuGet 2.*`

I need to specify some custom command line arguments to nuget.exe
(i.e. _-NoPackageAnalysis -NoDefaultExcludes_).
but I find no way of specifying these command line arguments in the new task. In the old task there was a field called  _NuGet Arguments_ for this purpose.
![image](https://user-images.githubusercontent.com/318504/39856785-794a5d1a-5431-11e8-86a6-84e9a8d71679.png)

Was the possibility to supply custom command line arguments to nuget.exe deliberately removed? What is the recommended way when they are needed?

One alternative would seem to be to use `Command: custom`, but that does not support wildcards (meaning I would have to do a custom command for each of my 20 nuspecs, which is not feasible).

**Comment by memark** [comment]
Anyone reading this?

**Comment by keithrob** [comment]
@memark,
Yes. We intentionally did not allow custom fields with the canned commands (e.g. restore) to prevent folks from creating contradictory options.  We only support a limited set of options through check boxes.  

These two options seem fairly innocuous and are something we will consider adding to pack.

**Comment by memark** [comment]
That would be great!

Another "solution" would be if the _custom_ command somehow did the same wildcard matching that the other commands support.

**Comment by hangy** [comment]
It seems that `-IncludeReferencedProjects` can also not be applied when using `pack` with `csproj` files. From what I can see, this is currently blocking us from moving away from the deprecated "NuGet" task.

**Comment by alexmullans** [comment]
Closing this as WF. In the upcoming quarter, we'll be moving away from the full-featured Artifacts-related tasks (which have many issues like this because they don't support the full set of commands and parameters provided by the underlying tool) and recommending calling NuGet directly. See the [design here](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/artifacts-in-pipelines.md) for more details.

**Comment by memark** [comment]
@alexmullans Thanks for the information! Seems like a reasonable path to take.
