### ISSUE TITLE
Compilation error when migrating to .Netcoreapp 2.1.0-rc1-final

### ISSUE THREAD

**Issue by sadjadbp** [Microsoft/azure-pipelines-tasks#7211]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- VSTS, any account

- Agent - Hosted or Private: 
    
- Hosted, any agent

## Issue Description

Try to build any asp.net core project that is upgraded to 2.1.0-rc1; Here is the compilation error 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8032	An instance of analyzer Microsoft.AspNetCore.Mvc.Analyzers.AvoidHtmlPartialAnalyzer cannot be created from C:\Users\sbhavsar.nuget\packages\microsoft.aspnetcore.mvc.analyzers\2.1.0-rc1-final\analyzers\dotnet\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by sadjadbp** [comment]
#1543

**Comment by bryanmacfarlane** [comment]
This doesn't look like a task issue.  Seems like a dotnet core issue, correct?

**Comment by sadjadbp** [comment]
I'm adding a task to install 2.1.300-rc1-008673 version of .net core before build to see if that'll fix it

**Comment by sadjadbp** [comment]
failed again

**Comment by bryanmacfarlane** [comment]
Compilation error still coming out of net core.  Seems like the CI task correctly ran it and returned the output and results.  Tagging for @daveVSTS in build to follow up

**Comment by patnolan** [comment]
+1
I'm getting the error aswell

**Comment by moswald** [comment]
I'm going to close this one. This does not seem to be a problem with any of the tasks. Please open an issue on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) site or the [azure-pipelines-agent](https://github.com/Microsoft/azure-pipelines-agent) repository if you feel there is still something unresolved.
