### ISSUE TITLE
Modify/preserve environment variables between tasks

### ISSUE THREAD

**Issue by fmanea** [microsoft/azure-pipelines-tasks#7224]
Hello,

I am struggaling with a problem that I can't get an answer anywhere. Is there a possibility to modify from inside a powershell task script, the variables that are definded in the "variables" tab? Or is there a possibility to perserve information from one task to another through an environment variable?

I saw here that it is a possibility to this with "Import-Module "Microsoft.TeamFoundation.DistributedTask.Task.Internal"" here (http://blog.majcica.com/2016/02/19/passing-values-between-tfs-2015-build-steps/)

Which it states that it is available from 1.83.2.

I have 2.112.0 agent, and this module is missing. I get : 
``2018-05-16T15:14:57.9841091Z ##[error]Import-Module : The specified module 
'Microsoft.TeamFoundation.DistributedTask.Task.Internal' was not loaded 
because no valid module file was found in any module directory``

 Was it moved somewhere else? Can somebody give some hints?

Best regards,
Flavian

**Comment by fmanea** [comment]
I saw that I was able to achieve what I wanted with:
Write-Host "##vso[task.setvariable variable=BuildVersion;]998"
My question, will this work if for say, I will do from a python script a print with:
print("##vso[task.setvariable variable=BuildVersion;]998")
Will it have the same effect as the one from the powershell?

**Comment by bryanmacfarlane** [comment]
Yep that's it.  Details: steps run out of proc and this informs the agent to modify it's variable set so when the next steps are called out of proc, those variables are passed in. hth
