### ISSUE TITLE
Issue template "Troubleshooting" link 404s

### ISSUE THREAD

**Issue by compuguru** [Microsoft/azure-pipelines-tasks#7348]
The "Troubleshooting" link in the Github issue template (when you file a new issue in this repo) points to https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting which 404s. Perhaps it's supposed to point to https://docs.microsoft.com/en-us/vsts/pipelines/troubleshooting?view=vsts?

**Comment by damccorm** [comment]
It looks like this link is now working so I'm going to close here
