### ISSUE TITLE
Release tasks have roken FWlinks from folder renames

### ISSUE THREAD

**Issue by nschonni** [microsoft/azure-pipelines-tasks#7357]
Can we use this as a meta issue to get all of the FWLinks broken from #7181 updated? 
EX: https://go.microsoft.com/fwlink/?LinkId=838890 is used on-prem 2017 and is a 404, and I'm guess there are others too.
There was a bunch of broken thinks in the https://github.com/MicrosoftDocs/vsts-docs repos too since they weren't consistently using fwlink URLs.

**Comment by stephenmichaelf** [comment]
@DavidStaheli @bryanmacfarlane for visiblity.

The FWLinks should be updated by task owners. 

Per David: We are generally moving towards docs being our standard location for product docs for unification, searchability, discoverability, and SEO. If there are links broken there they should be fixed. For instance that link to DeployVisualStudioTestAgent README should go to something in Docs not in the repo.

Can you add specific links that are broken?

**Comment by nschonni** [comment]
> Can you add specific links that are broken?

I don't have a list of fwlinks, I've just been fixing the broken links on the docs repo manually. The one example above I gave, I came across this morning when trying to share the the link from our on-Prem that embeds that link. 
Here is one more I found on the Add Tasks -> Test for TFS 2017 though https://go.microsoft.com/fwlink/?LinkId=624389

> We are generally moving towards docs being our standard location for product docs for unification, searchability, discoverability, and SEO

:+1: Probably a good idea, but the docs repo has a bunch of raw links back to the tasks repo https://github.com/MicrosoftDocs/vsts-docs/search?q=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvsts-tasks&unscoped_q=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvsts-tasks
I've fixed them up now, but maybe the should be separate fwlinks if you plan on renaming again

**Comment by bryanmacfarlane** [comment]
@nschonni - all the tasks with the broken fwlinks already have doc content in the docs repo.  The release team moves the doc content in the markdown into those.

**Comment by PaulMEdwards** [comment]
This link is broken:
https://go.microsoft.com/fwlink/?linkid=839731

Points to:
https://github.com/Microsoft/vsts-tashttps://github.com/Microsoft/vsts-tasks/blob/master/Tasks/IISWebAppManagementOnMachineGroupV0/README.md

Should be:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/IISWebAppManagementOnMachineGroupV0/README.md

**Comment by SumiranAgg** [comment]
Cant find this link in the repo. Closing issue for now.
Please provide link to file where it is used and re-open the bug.
