### ISSUE TITLE
Nuget restore creates a temp copy of nuget.config breaking its relative paths

### ISSUE THREAD

**Issue by murali89** [microsoft/azure-pipelines-tasks#7370]
## Issue Description

[Include task name(s), screenshots and any other relevant details]

Nuget restore creates a temp copy of nuget.config breaking its relative paths
Using NuGet.config file, you can configure repositoryPath key in the config section to modify the default location of the packages installation folder (see ref https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file).

However, if the repositoryPath is relative, the build will be most likely broken. The reason is that Nuget restore task copies the NuGet.config into a temp file in a different location.

Let's say the key is set in the following manner:

<add key="repositoryPath" value=".\packages" />

### Error logs

The build log shows:

2018-04-23T11:22:51.3304768Z Detected NuGet version 4.6.2.5055 / 4.6.2
2018-04-23T11:22:51.3340542Z SYSTEMVSSCONNECTION exists true
2018-04-23T11:22:51.3358743Z Saving NuGet.config to a temporary config file.
2018-04-23T11:22:51.3533215Z [command]C:\hostedtoolcache\windows\NuGet\4.6.2\x64\nuget.exe restore D:\a\1\s\src\Obfuscated.sln -NoCache -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\Nuget\tempNuGet_2844264.config
While the expected path of the packages is D:\a\1\s\src\packages, the actual path of the packages folder is D:\a\1\Nuget\packages.

The only way we were able to overcome the issue was by setting the Nuget restore task DestinationPath property as $(Build.Repository.LocalPath)\packages which is rather a workaround than a solution. Now, if the repositoryPath changes, the change has to be made in the build definition as well.

**Comment by murali89** [comment]
VSTS Dev Community Link: https://developercommunity.visualstudio.com/content/problem/238562/nuget-restore-creates-a-temp-copy-of-nugetconfig-b.html

**Comment by KirillOsenkov** [comment]
See related: https://github.com/Microsoft/azure-pipelines-tasks/issues/7616

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
