### ISSUE TITLE
Nuget Restore task re-uses config file from previous Task in the same build definition

### ISSUE THREAD

**Issue by murali89** [microsoft/azure-pipelines-tasks#7371]
## Issue Description

If you have a build definition that references two different nuget.config files, the nuget restore task will re-use the first config file for the second instance of the task this is problematic when the config files contain different package sources.

To work around the issue we had to add the following step to our build definition to clear out the temporary file after the first nuget restore:

```

- script: del $(build.SourcesDirectory)\..\nuget\*.config 

displayName: Clear Temporary Nuget Config

```

The temporary file is named with just the build id: D:\w\4\Nuget\tempNuGet_250466.config

**Comment by murali89** [comment]
VSTS Dev Community Link: https://developercommunity.visualstudio.com/content/problem/243645/nuget-restore-task-re-uses-config-file-from-previo.html

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
