### ISSUE TITLE
Add support for NuGet Signing in NuGet-task (NuGet 4.6)

### ISSUE THREAD

**Issue by doormalena** [microsoft/azure-pipelines-tasks#7386]
We would like to see that the NuGet Signing capability is added as a configurable option for the the NuGet build definition task. See also https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package

**Comment by jotaylo** [comment]
Have you tried using the 'custom' NuGet command to sign the package?

**Comment by doormalena** [comment]
Yes I ended up with a custom command. Nevertheless it would be nicer if this is available out of the box :-).

As a reference for others searching for the same answer:
- NuGet Tool Installer task configured to install NuGet version 4.6.0
- NuGet task configured with a custom command:
`sign $(Build.ArtifactStagingDirectory)/**/*.nupkg -CertificatePath $(Agent.WorkFolder)\_temp\CodeSigningCertificate.pfx -CertificatePassword $(CertificatePassword) -HashAlgorithm sha256 -Timestamper "http://timestamp.[SomeCertSupplier].com" -TimestampHashAlgorithm sha256`

**Comment by alexmullans** [comment]
I've copied this to our internal backlog - thanks for the suggestion!

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
