### ISSUE TITLE
Test task times out after enabling TIA

### ISSUE THREAD

**Issue by strosu** [microsoft/azure-pipelines-tasks#7387]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016

## Issue Description
I've been trying to add Test Impact Analysis to our project. Our build is configured via yml, this is the task itself:

- task: VSTest@2
  displayName: "Run unit tests and DB Migration tests"
  inputs:
    testAssemblyVer2: "****"
    testFiltercriteria: "**"
    testRunTitle: "Unit Tests"
    platform: "$(BuildPlatform)"
    configuration: "$(BuildConfiguration)"
    vsTestVersion: toolsInstaller
    runOnlyImpactedTests: true

The only change is the runOnlyImpactedTests setting. The tests are hitting a local IIS deployment so I've also added the following section to our .runsettings file, as per https://docs.microsoft.com/en-us/vsts/pipelines/test/test-impact-analysis?view=vsts :

      
      <DataCollector uri="datacollector://microsoft/TestImpact/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TraceCollector.TestImpactDataCollector, Microsoft.VisualStudio.TraceCollector, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Test Impact">
        <Configuration>
          
          <InstrumentIIS>True</InstrumentIIS>
          
          <ImpactLevel>file</ImpactLevel>
          
          
        </Configuration>
      </DataCollector>
	</DataCollectors>  

After these changes, the test run task simply gets stuck and doesn't log anything else after finishing with the tests. 

This has happened to all the builds with TIA enabled and none without it. Am I doing something wrong? Thanks in advance for the help. 

### Error logs
TIA looks enabled. It detects that my only change was the .yml file and decides to run all the tests (so far so good). 

Normally the tests should take a few minutes, however the task now times out after 2 hours, with nothing being logged after the tests are executed. These are the last lines of the test execution task:

2018-06-06T12:02:13.5781858Z Request ended: *** with HTTP status 401.0
2018-06-06T12:02:13.6320338Z 29.017
2018-06-06T12:02:13.6496466Z 9.2144
2018-06-06T12:02:13.7421595Z 79.9229
2018-06-06T13:56:39.5667448Z ##[error]The operation was canceled.
2018-06-06T13:56:39.5715106Z ##[section]Finishing: Run unit tests and DB Migration tests

**Comment by prawalagarwal** [comment]
Hi @strosu 
Are you on VSTS or TFS? If TFS which version? Can you please send your run logs where you face this issue (with system.debug set as true in your build variables) to devops_tools@microsoft.com

**Comment by ShreyasRmsft** [comment]
@strosu let us know once you have mailed the logs with system.debug=true

**Comment by strosu** [comment]
Hi @ShreyasRmsft , thanks for looking into this.

I've emailed the logs, titled "Logs Test task times out after enabling TIA #7387". The build is running on vsts, please let me know if a build url would be helpful.

**Comment by ShreyasRmsft** [comment]
@strosu from the build logs it seems like it's stuck on a particular test
The logs indicate 151 tests have passed. While 154 tests were supposed to run.

One of tests is causing the hang when Test impact is on.

2018-06-13T11:39:20.4862165Z 19.6099
2018-06-13T11:39:20.4958979Z 4.794
2018-06-13T11:39:20.5714581Z 68.8016
2018-06-13T11:39:20.5958934Z IncrementMes***ges called
2018-06-13T11:39:20.5959503Z Request started: "PATCH" http://localhost:6234/odata/Machines(-1)
2018-06-13T11:39:20.6069675Z Request ended: http://localhost:6234/odata/Machines(-1) with HTTP status 401.0
2018-06-13T11:39:20.6487452Z 21.7495
2018-06-13T11:39:20.6598376Z 5.364
2018-06-13T11:39:20.7401879Z 72.8558

Can you please wait for a few hours before stopping the build/release. IIS profiling is known to be time consuming

**Comment by ShreyasRmsft** [comment]
@strosu any updates here?

**Comment by acesiddhu** [comment]
@strosu you can find some blog in series of post done by Pratap. https://blogs.msdn.microsoft.com/devops/2017/06/13/accelerated-continuous-testing-with-test-impact-analysis-part-3/

To answer your questions

1) Baseline build is a build from the same build definition where any test ran. There is not way to configure it today. 
2) You can check the mapping by running a build with System.Debug true. it will contain a zip with n number of xml files (each for a test case). Let me know if you need any help here. Let me know if you have a repro where the test should have ran and it didn't run. Please open an issue on GitHub once you have it. 


CC:/ pvlakshm
