### ISSUE TITLE
Bump tasks to consume latest vsts-task-tool-lib

### ISSUE THREAD

**Issue by ericsciple** [microsoft/azure-pipelines-tasks#7413]
A [race condition](https://github.com/Microsoft/vsts-task-tool-lib/pull/41) was fixed in the vsts-task-tool-lib.

I'm planning to leave this issue open until all of the tasks in this repo are updated.

**Comment by ericsciple** [comment]
@madhurig and @azureDaveOps regarding ArchiveFilesV2, SshV0, GruntV0, and GulpV1

Everything else is on 0.9 or higher.

**Comment by madhurig** [comment]
@ericsciple - we plan to update SSH tasks in Q2.

**Comment by stephenmichaelf** [comment]
For clarity:

ArchiveFilesV2 - @bryanmacfarlane 
SshV2 - @madhurig 
GruntV0 - @hross 
GulpV1 - @hross 

I will break this down into 4 individual tickets and assign to owners.

**Comment by moswald** [comment]
@stephenmichaelf Can this ticket be closed now?

**Comment by stephenmichaelf** [comment]
@moswald Looks like we still need to do it for SshV0 and GulpV1.

**Comment by damccorm** [comment]
I did it for ssh and filed a bug for Gulp internally - closing here
