### ISSUE TITLE
Maven repository URL incorrect

### ISSUE THREAD

**Issue by uankola** [microsoft/azure-pipelines-tasks#7454]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by uankola** [comment]
I am using VSTS task Nexus Artifact Upload and noticed that it was constructing the path to Nexus repository incorrectly

2018-06-13T08:44:25.7199884Z ##[debug]nexusUploadUrl=https://<hostname.com>/nexus/**_service/local/artifact/maven/content_**

whereas i wish to upload to content/repositories/snapshots/com

how do i set this in the endpoint setup?  or in the task?

**Comment by bryanmacfarlane** [comment]
There is not Nexus Artifact Upload task in this repository.  Where did that task come from?  An extension?  You would need to follow up with the author of that task.

**Comment by uankola** [comment]
Hi Bryan,
I am using Nexus Upload task in my VSTS build definition and would like to deply the war file to Nexus.  We have defined an end point for the same.

I noticed that the VSTS task Nexus Artifact Upload was constructing the path incorrectly.  i.e.
2018-06-13T07:55:38.9878799Z ##[debug]nexusUploadUrl=https://<nexus host.com>/nexus/service/local/artifact/maven/content
Whereas it should be https://<nexus host.com>/nexus/content/repositories/snapshots/com/yy/xxxx/<my web app name>/9.5.0.8-SNAPSHOT/<my web app name>-9.5.0.8-20180608.120507.war<https://centricitycr.idxasp.com/nexus/content/repositories/snapshots/com/ge/cedi/cedi-ux-webapp/9.5.0.8-SNAPSHOT/cedi-ux-webapp-9.5.0.8-20180608.120507.war>

In the Nexus Artifact Upload Task
Display Name                                                     Nexus Artifact Upload
Sonatype Nexus service endpoint                 Nexus --> end point defined with the path https://<nexus host.com>/nexus<https://centricitycr.idxasp.com/nexus>, login and pwd
Repository ID                                                     snapshots we tried with content/repositories/snapshots as well still build is not getting the right value in nexusUploadUrl
Group ID                                                              com.yy.<xxxx>
Artifact ID                                                            <my web app name>
Artifact version                                                 9.0.0.0_MAIN-SNAPSHOT
Packaging                                                            war
File                                                                         $(build.sourcesDirectory)\artifact.war

Do you know any other project that has used the VSTS task Nexus Artifact Upload successfully and has constructed the nexusUploadUrl correctly?


Uma Ankolekar
GE HealthCare, Healthcare Technology and Medical Innovation,
Staff Software Build and Release Engineer, Bangalore, KA, IN

M : +91 99208 37273, O : +91 80 4088 3929, WFH : +91 22 2373 5878
Skype : uma.ankolekar@ge.com
