### ISSUE TITLE
Archive Files task should warn user when folder to archive is empty

### ISSUE THREAD

**Issue by jimlamb** [microsoft/azure-pipelines-tasks#7465]
## Environment
- All environments

## Issue Description
I was following the "[Implement a CI/CD process to build and deploy your Node.js app to Azure](https://docs.microsoft.com/en-us/vsts/pipelines/archive/apps/nodejs/quick-to-azure?view=vsts)" tutorial using the NodeJS with Gulp template. That template set the root folder to archive setting on the Archive Files task to $(BinariesDirectory). In the case of a Node.js app, however, this directory is generally empty. As a result, the zip file created is empty.

When I proceed to the next step of the tutorial and set up the release definition, the Azure App Service Deploy task reported the following errors:

* The Zip package 'D:\a\r1\a\tin-octopus-Node.js With gulp-CI\drop\625.zip' could not be loaded.
* Package file 'D:\a\r1\a\tin-octopus-Node.js With gulp-CI\drop\625.zip' is not in a supported .zip format and therefore cannot be read.

It turned out that these errors were due to the fact that the zip file was empty. It would have been very helpful if the build process had output a warning to let me know that the zip file it was creating was empty. Also, it would be helpful if there was a setting that would log the files that were archived for verification purposes.

**Comment by bryanmacfarlane** [comment]
I would probably go the more information route.

@stephenmichaelf - we can print the number of files to be zipped, and print the first level files / folders (up to 10 and if ten ... line below).

That gives the user an understanding of what they're zipping.  For both the empty file case and the case where there's an unexpected root folder, it will be clearer to the user the effect of what they configured.

**Comment by stephenmichaelf** [comment]
Yup! Will add this.

**Comment by stephenmichaelf** [comment]
@jtpetty Can you take a look at this?
