### ISSUE TITLE
NuGet Tool Installer

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/azure-pipelines-tasks#7495]
NuGet Tool Installer is not considering the proxy settings provided by the agent, thus if agent is behind a proxy it will fail.

**Comment by mmajcica** [comment]
After looking into the code I noticed that NuGet Tool Installer task uses vsts-task-tool-lib to download the necessary.  Starting with the version 0.4.1 of the vsts-task-tool-lib the necessary proxy settings are passed to typed-rest-client.

Still, however I do get the following error:
`2018-06-18T05:54:20.7946286Z ERR:tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:`

Any idea what this can be related to?

**Comment by mmajcica** [comment]
Seems that the issue is not in downloading the client but in getting the list of the available versions.

At this step in the code 
https://github.com/Microsoft/vsts-tasks/blob/fa0cf7029e6ccc95f4d61da2e179e9fa4d128536/Tasks/Common/nuget-task-common/NuGetToolGetter.ts#L128

a new instance of RestClient from typed-rest-client module is created. However, although it supports handling proxy settings, those are not passed in. This seems to be the problem.

**Comment by mmajcica** [comment]
I'm trying with the following change:

```
async function getLatestMatchVersionInfo(versionSpec: string): Promise<INuGetVersionInfo> {
    taskLib.debug('Querying versions list');

    let versionsUrl = 'https://dist.nuget.org/tools.json';

    const proxy = taskLib.getHttpProxyConfiguration();
    const options = proxy ? { proxy: proxy, ignoreSslError: true } : undefined;

    let rest: restm.RestClient = new restm.RestClient('vsts-tasks/NuGetToolInstaller', null, null, options);
    //let rest: restm.RestClient = new restm.RestClient('vsts-tasks/NuGetToolInstaller');
```

Unfortunately I can't get it to work. Any suggestion is welcome.

Following the output that I get in case of the above change:
```
2018-06-18T11:28:58.0640428Z ##[debug]Querying versions list
2018-06-18T11:28:58.0640943Z ##[debug]Agent.Version=2.131.0
2018-06-18T11:28:58.0641435Z ##[debug]Agent.ProxyUrl=http://myproxy:8090
2018-06-18T11:28:58.0642077Z ##[debug]Agent.ProxyUsername=undefined
2018-06-18T11:28:58.0644087Z ##[debug]Agent.ProxyPassword=undefined
2018-06-18T11:28:58.0644608Z ##[debug]Agent.ProxyBypassList=[".*?.some.net",".*?.intranet"]
2018-06-18T11:28:58.1228329Z ERR:Invalid Resource
2018-06-18T11:28:58.1228994Z ##[debug]task result: Failed
```
@brcrista @emanuelquintero any ideas?

**Comment by brcrista** [comment]
@keithrob -- @mmajcica is referring to change #7435 we made to Download Secure File and is trying to get the same thing to work here.

**Comment by mmajcica** [comment]
@bryanmacfarlane @brcrista Are there any updates on this one?

**Comment by bryanmacfarlane** [comment]
@keithrob can update

**Comment by keithrob** [comment]
@mmajcica,
We are planning on comprehensively fixing all of the proxying problems with the NPM, NuGet and Dotnet tasks for TFS2019.  Earlier, TFS users can use older versions of the tasks which are not susceptible to these problems.

**Comment by vstribrny** [comment]
@keithrob
Please fix this particular problem with proxy and do not wait for general fixing as part of TFS2019 mentioned above. We're trying to use Azure Pipelines in corporate environment and this problem blocks us totally.

**Comment by alexmullans** [comment]
These tasks are now proxy-compatible.

**Comment by NenoLoje** [comment]
@alexmullans What does 'now' mean in terms of TFS on-prem?

**Comment by alexmullans** [comment]
@NenoLoje Azure DevOps Server 2019.1

**Comment by CesarD** [comment]
> @NenoLoje Azure DevOps Server 2019.1

What can those of us that are still on TFS 2018 do about this issue? Is there some workaround for us or we are just left on a side until we can convince the company to make the upgrade to DevOps 2019?

**Comment by alexmullans** [comment]
You can manually acquire the version of NuGet.exe you wish to use and put it on the private agent(s) in a folder that's on the PATH.

**Comment by mmajcica** [comment]
> > @NenoLoje Azure DevOps Server 2019.1
> 
> What can those of us that are still on TFS 2018 do about this issue? Is there some workaround for us or we are just left on a side until we can convince the company to make the upgrade to DevOps 2019?

You can always push the new version of the task manually to your server. It is not advised by MS but it works as for any other task. Clone the repo, build the task and with tfs-cli push it to your instance of TFS.

**Comment by CesarD** [comment]
Awesome! Thank you @mmajcica !!

**Comment by vonj** [comment]
"These tasks are now proxy-compatible."

Sort of. They are not CA cert compatible, i.e. they will not work in a corporate environment.

Does not seem to be a priority.
