### ISSUE TITLE
VSTS NuGet Temp file for restore

### ISSUE THREAD

**Issue by PNI-GS** [microsoft/azure-pipelines-tasks#7505]
VSTS creates a copy of standard nuget.config file, naming it "tempNuGet_xxxxx.config", and placing it in a NuGet folder outside of the source folder.

There are multiple issues here that should be addressed and can be addressed with just disabling the "temp" config file action.

Issues:
1.  tempNuget_xxxxx.config file is not an exact copy of the nuget.config that should be used that is in the source.

2.  The new temp file does not have the same formatting as the original, leaving empty space all over

3. the PackageSources order has been resorted Alphabetically.  This is a big issue as NuGet is to restore based on that order and if you want a particular version picked up before others then this breaks the system.

4. Changing the security of the PackageSourceCredentials, using a key="ClearTextPassword"

5. Missing additional information that may be required.

6. NuGet restore path (usually relative) does not restore to source folder but to its own local folder.  This becomes an issue when project are looking for the packages in the package directory, but are not there as the original config had a relative path defined.

**Comment by Styxxy** [comment]
Same happens on TFS2018 (on premise) installation.

Especially item 6 is very annoying. We now have to find sometimes creative workarounds for it, which is very confusing to many people.

Both repositoryPath and globalPackagesFolder can contain relative paths (example from our source control):

```xml
<?xml version="1.0"?>
<configuration>
  <config>
    <add key="repositoryPath" value="..\..\..\packages" />
    <add key="globalPackagesFolder" value="..\..\..\packages" />
  </config>
</configuration>
```

Actually in another repository we also found that the package sources also can contain relative paths, so these should also being taken into account:

```xml
<?xml version="1.0"?>
<configuration>
  <config>
    <add key="repositoryPath" value="..\..\..\packages" />
    <add key="globalPackagesFolder" value="..\..\..\packages" />
  </config>
  <packageSources>
    <add key="Local source" value="..\..\..\lib-packages" />
  </packageSources>
</configuration>
```

**Comment by Styxxy** [comment]
I'm for the moment adding following solution.

I added an extra build step **before** the nuget restore, that will _fix_ the nuget.config that will be used. (TFS will discard the changes anyway.)

I use for the moment two steps, both PowerShell inline scripts.
Change path to your own nuget.config file.

## Step 1
- **Task**: PowerShell
- **Description**: PowerShell Script : Fix nuget.config relative paths (//config/add)
- **Arguments**: -File "$(build.sourcesDirectory)\Build\Solutions\nuget.config"
- **Inline script**:
```PowerShell
[CmdletBinding()]
Param(
  [Parameter(Mandatory=$True)]
  [string]$File
)

Write-Host "Fix relative paths (//config/add) in file $File"

[XML]$nuget = Get-Content $File

Foreach ($cfg in (Select-XML -Xml $nuget -XPath '//config/add')) {
  Try {
    If (-not [System.IO.Path]::IsPathRooted($cfg.node.value)) {
      $cfg.node.value = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName($File), $cfg.node.value))
    }
  }
  Catch { }
}

$nuget.Save($File)
```

## Step 2
- **Task**: PowerShell
- **Description**: PowerShell Script : Fix nuget.config relative paths (//packageSources/add) copy
- **Arguments**: -File "$(build.sourcesDirectory)\Build\Solutions\nuget.config"
- **Inline script**:
```PowerShell
[CmdletBinding()]
Param(
  [Parameter(Mandatory=$True)]
  [string]$File
)

Write-Host "Fix relative paths packageSource in file $File"

[XML]$nuget = Get-Content $File

Foreach ($cfg in (Select-XML -Xml $nuget -XPath '//packageSources/add')) {
  Try {
    If (-not [System.IO.Path]::IsPathRooted($cfg.node.value)) {
      $cfg.node.value = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName($File), $cfg.node.value))
    }
  }
  Catch { }
}

$nuget.Save($File)
```

## Step 3
- **Task**: NuGet
- **Description**: NuGet restore MySolution.Build.sln
- **Command**: restore
- **Pathh to solution, ...**: Build\Solutions\MySolution.Build.sln
- **Feeds to use (Feeds in my NuGet.config)**: Build\Solutions\nuget.config

**Comment by RobDesideri** [comment]
@Styxxy Thanks for your workaround. It work perfectly

**Comment by r0bfr** [comment]
I'm hitting this same issue.  #6 in particular.  Part of our solution checks for the existence of a package in the "packages" folder.  In Visual Studio this works fine.  But then when building in VSTS, the packages folder gets placed off in some NuGet directory instead of $(SolutionDir)\packages.

Looking forward to a fix here.

**Comment by Styxxy** [comment]
@r0bfr Look at my provided solution (above). Make sure you have repositoryPath and globalPackagesFolder in your nuget config file.

```xml
  <config>
    <add key="repositoryPath" value="..\..\packages" />
    <add key="globalPackagesFolder" value="..\..\packages" />
  </config>
```

**Comment by Ziugy** [comment]
Ran into an issue where the temp file is reused in other NuGet restores (different solutions) and causes potential restore failures. Would be good to create new temp files per NuGet task.

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!

**Comment by Styxxy** [comment]
@elbatk This issue is about the nuget restore task. Will this task be reworked?

**Comment by elbatk** [comment]
Hi @Styxxy , the short answer, yes. The long answer: we're moving away from tasks like the NuGet tasks in its current state. The behind the scenes behavior in them end up surprising people more than helping them, and sometimes when users run into issues they can't tell if it's our task or NuGet itself. With those things in mind, we'd like to have tasks to help users set up authentication, and then let them run their own custom NuGet/command line commands so they can control behavior.

**Comment by tentom** [comment]
This was terrible to figure out and solve, I ended up here so I feel this might be useful for someone else stumbling upon this thread in the future. 

What ever I did, the the task cold not find my NuGet package that I have in my source repository. 

My solution was to forget about the task completely and add a bash script with the following: 
``` 
nuget locals all -clear
nuget restore <solution_name>.sln
```

with the location configured to relative paths 
``` xaml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositoryPath" value="$\..\NugetPackages\" />
    </config>
    <packageSources>
        <add key="LocalNuget" value="$\..\<what_ever_subfoled>\NugetPackages\" />
	<add key="NuGet OfficialPackage source" value="https://api.nuget.org/v3/index.json"/>
    </packageSources>
</configuration>
````
in a NuGet.config file located in the same folder as the .sln everything is fine both on my local machine and also on the hosted build pipeline.
