### ISSUE TITLE
Copy Files Over SSH: Hangs after Copy Complete

### ISSUE THREAD

**Issue by digitalcraftco** [Microsoft/azure-pipelines-tasks#7507]
## Environment
- Server - VSTS 
- Agent: Hosted Linux Preview

## Issue Description
After successfully copying files to remote server it throws the "Completed copying 308 files to remote machine" message and will hang there indefinitely. The Post Job clean-up phase is never triggered. The copy job was completed in 6mins and the build was still running after 20mins.

It's the only task I run on the agent. Am I missing something? Do I need to add another task to close the session?

**Comment by bryanmacfarlane** [comment]
You shouldn't need to.  Does it repo with a linux VM (not hosted?).  The reason I ask is that Hosted Linux Preview pool runs builds in a container as an implementation details.  We have a new Hosted Ubuntu 1604 released pool coming online very soon (we start rolling it in the next week hopefully).

**Comment by digitalcraftco** [comment]
Yes. It connects to an on premise SUSE Linux Enterprise Server 11 SP4.

**Comment by digitalcraftco** [comment]
@ArieHein Thanks. I will see if can get it upgraded and try again.

**Comment by joshmgross** [comment]
@digitalcraftco Are you still having this issue?

**Comment by digitalcraftco** [comment]
Yes, gave up on it a while ago. I no longer have the pipeline setup to test so closing issue for now. I will try to follow up if I get a chance to test again.

**Comment by meriturva** [comment]
Quite an old issue but it still present.
Actually my target SO is: CentOS Linux 7 (not the agent) and Release Copy Job stay hanged infinitely.
Thanks!

**Comment by joshmgross** [comment]
@meriturva Can you open a new issue and link this one?
