### ISSUE TITLE
dotnet build (.Net Core) failed to run with the installed version task

### ISSUE THREAD

**Issue by morshilo** [Microsoft/azure-pipelines-tasks#7510]
## Issue Description
i have a CI process including the following steps:
* .NET Core Tool Installer (Use .NET Core runtime 2.0.7)
* dotnet restore
* dotnet build
* and more...

the CI fails on the dotnet build step with the following error:
### Error logs
error : The project was restored using Microsoft.NETCore.App version 2.0.7, but with current settings, version 2.0.0 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.

seems like it is really ignoring the new version installation step. Should I install anything else to make the build run with the correct version?

**Comment by bryanmacfarlane** [comment]
It sounds like it's successfully installing 2.0.7 but perhaps settings in your code / project files is set to 2.0.0?

**Comment by morshilo** [comment]
I checked it, and I don't have it anywhere on the entire solution.
any idea where the 2.0.0 version can be mentioned that can affect the build task?

**Comment by daveVSTS** [comment]
Do you have your build definition and project files somewhere I can look?  

@michVSTS could you please assist @morshilo.

**Comment by morshilo** [comment]
hi @daveVSTS, sorry, i can't share the files since the repository is private. 
Can you specify the part you suspect, so I can send a copy of them here?

**Comment by moswald** [comment]
@morshilo did you ever get this fixed? If not, we'd like to see your build definition. You can export it to json from the Azure DevOps build page. Also, if you can share your `.csproj` files, that would be helpful.
