### ISSUE TITLE
Allow manual adjustment/reset of BuildID

### ISSUE THREAD

**Issue by codearoo** [microsoft/azure-pipelines-tasks#7519]
In VSTS please allow this. I see many posts and I have had several challenges in how people aren't able to seamlessly continue versioning when they move to VSTS. But other systems like TeamCity allow you to manually reset/set a BuildID. And if VSTS uses this in some deep internal way, then provide another way to set and then auto-increment a variable. Having a hard coded "seed" adjustment to the BuildID seems .. dirty.

**Comment by FrankMue** [comment]
Just created i little helper for myself
https://github.com/FrankMue/AzureDevopsBuildIdIncrementer

**Comment by moswald** [comment]
[We have the `counter()` variable expression available for this](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-using-expressions).

**Comment by sibbl** [comment]
@moswald as this is the only place where I see the `counter()` var expression mentioned besides the docs:

Is there any way to use this function in classic pipelines?

**Comment by moswald** [comment]
`counter()` is valid as a pipeline variable in both [designer](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#set-variables-using-expressions) and [yaml](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-using-expressions) pipelines.
