### ISSUE TITLE
Operation could destabilize the runtime

### ISSUE THREAD

**Issue by NikitaEgorov** [microsoft/azure-pipelines-tasks#7520]
## Environment
TFS 16.131.27701.1

## Issue Description
https://github.com/nunit/nunit3-vs-adapter/issues/519

**Comment by mayankbansal018** [comment]
Fixed with https://github.com/Microsoft/vstest/pull/1997, we have also released latest nuget package (16.0.2 preview) of test platform with above change, please upgrade to it.
