### ISSUE TITLE
Jenkins Queue Job's 'wait for pipeline completion' should not wait on disabled jobs

### ISSUE THREAD

**Issue by pjquirk** [Microsoft/azure-pipelines-tasks#7527]
(reported in email from Rodrigo Antunes)

## Issue Description
> I’ve setup a TFS and Jenkins integration and the Jenkins job is triggered properly. However, when it finished, TFS build gets stuck on this step:
>
>        locateExecution()
>        pipeline, locating child execution URL:http://<redacted>/api/json
>        locateExecution().requestCallback()
>
> ... I’ve detected that there were a dependent job configured on Jenkins, and that job is disabled.  I would assume that TFS wouldn’t wait for it, since it’s disabled, but it seems to do.
>
> I’ve disabled the “wait for pipeline completion” option on TFS build and it has completed successfully.

It seems that when [finding jobs in the pipeline to capture, the task does not filter out disabled jobs](https://github.com/Microsoft/vsts-tasks/blob/dabc382bcc98750676c3f1a79c17f39c7fe47e26/Tasks/JenkinsQueueJobV2/job.ts#L278).

**Comment by go2guy** [comment]
I'm seeing the same issue when calling a Multiphase job on Jenkins. If any of the sub jobs are disabled, Queue Jenkins job on VSTS will hang even though a successful response is recorded in Jenkins.

**Comment by kelliejos** [comment]
Fixed with PR #8887. Closing as fixed.

**Comment by go2guy** [comment]
Is this released for consumption yet?

**Comment by kelliejos** [comment]
@go2guy The changes are being deployed. The ETA for all orgs is 12/14. Some orgs may have it earlier.
