### ISSUE TITLE
VSTest task fails to rerun tests that have a display name that differs from the method name and causes the test run to show as successful

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/azure-pipelines-tasks#7545]
If I have the following xunit test and I setup the VSTS VSTest task to rerun tests on failure, the first test run fails as expected, but the second test run is unable to discover the test and ends up succeeding causing my build to be green even though there are failed tests.

```csharp
namespace MyTestProject
{
    public class MyTest
    {
        [Fact(DisplayName = "Test One")]
        public void Test()
        {
            throw new NotImplementedException();
        }
    }
}
```

From what I can tell, it appears that the rerun attempt is using the `FullyQualifiedName` filter using `NamespaceName.ClassName.DisplayName` instead of using the fully qualified name returned by the test adapter (which in this case is `NamespaceName.ClassName.MethodName`). For example, VSTS is running the following command:
```
vstest.console.exe .\MyTestProject.dll /TestCaseFilter:"FullyQualifiedName=MyTestProject.MyTest.Test One"
```

when it should be running the following command:
```
vstest.console.exe .\MyTestProject.dll /TestCaseFilter:"FullyQualifiedName=MyTestProject.MyTest.Test"
```

I created a fake test data collector and verified that Xunit is setting the `FullyQualifiedName` to `MyTestProject.MyTest.Test`.

**Comment by abhishkk** [comment]
@ChristopherHaws 
We have this issue in our backlog.
You can mitigate the issue by using `Advanced execution options > Batch options > Specify a batch size`.
 
![image](https://user-images.githubusercontent.com/32157767/42379713-3fd70d40-8149-11e8-9b7b-2a71d433b8de.png)

**Comment by ChristopherHaws** [comment]
Thank you, I can confirm the workaround works.

**Comment by nigurr** [comment]
Hi @ChristopherHaws, after deep diving into this issue, this requires much larger fix from TRX generation.
To mitigate this issue, we recommend customers to turn on "Batch Options" as shown above, this will solve the issue with "Display Name and FQDN"

Thanks for your support and we are closing this issue as we don't have any immediate plans to fix in TRX generation.
