### ISSUE TITLE
Manual Intervention not expanding Variables

### ISSUE THREAD

**Issue by Tadimsky** [microsoft/azure-pipelines-tasks#7585]
I have a variable in my Release Definition that is made up of a number of other variables:
`DropName: $(Release.DefinitionName)/$(Release.ReleaseName)/$(Release.EnvironmentName)/$(Release.AttemptNumber)`

I then have this in the Instructions for Manual Intervention:
```
You now need to deploy the package to Griffin.
This can be done by doing:

.\Deploy-Griffin.ps1 - Environment Int - VstsDropName "$(DropName)"
```

This is what I end up getting in the output:
```
You now need to deploy the package to Griffin.
This can be done by doing:

.\Deploy-Griffin.ps1 - Environment Int - VstsDropName "$(Release.DefinitionName)/$(Release.ReleaseName)/$(Release.EnvironmentName)/$(Release.AttemptNumber)"
```
I use the $(DropName) variable in other agent tasks and it resolves to this:
`intentional services - griffin/release-21 (1.0.27915)/int/1`

How can I get Manual Intervention to print this out?

**Comment by vithati** [comment]
Currently recursive variable resolve support not available in agentless task.

**Comment by Tadimsky** [comment]
Yes, that's clear. Is it not possible in agentless task? Since it has the variables and their values it seems like it should be able to?

**Comment by vithati** [comment]
It is possible. I have added enhancement tag to validate and implement the feature later.

**Comment by rmarinho** [comment]
Anytime line for this @vithati ?

**Comment by vithati** [comment]
we should be able to get to it within next couple of months.

**Comment by bansalaseem** [comment]
We have this support now. So I am closing this issue.

**Comment by Tadimsky** [comment]
All working now - thanks!

**Comment by Tadimsky** [comment]
@bansalaseem it looks I'm having issues with this again.

I have the following variable defined in the Release:
![image](https://user-images.githubusercontent.com/1149244/62174636-83392900-b2ef-11e9-8fb7-e3180be08015.png)


And then in my agentless stage, I reference that variable:
![image](https://user-images.githubusercontent.com/1149244/62174663-96e48f80-b2ef-11e9-8637-6f487aa25954.png)

However, the task seems to run with this as the value:
`"DeploymentVersion": "1.0.$(Build.BuildId).$(Release.ReleaseId)",`

Shouldn't this be expanding all the way into the actual version?

If I use `1.0.$(Build.BuildId).$(Release.ReleaseId)` as the value in the Task then this expands to the right version.

**Comment by vithati** [comment]
@Tadimsky Presently recursive variables expansion support only available to MI instructions.

**Comment by Tadimsky** [comment]
@vithati Oh, I see.
I implied from this discussion that it was alimitation of agentless jobs, and that adding support for MI would result in it working for other tasks.
