### ISSUE TITLE
Build.SourceBranch is not consistent between TfsGit and Bitbucket Cloud

### ISSUE THREAD

**Issue by henryju** [microsoft/azure-pipelines-tasks#7595]
Hi,

I think there is an inconsistency in build variables for Bitbucket Cloud:

Build.Repository.Provider | Build.SourceBranch | Build.SourceBranchName
----| ------------ | -------------
TfsGit | refs/heads/master | master
Bitbucket | **master** | master

I would have expected Build.SourceBranch to be equal to refs/heads/master for Bitbucket.

**Comment by CraigHead** [comment]
Other areas of inconsistency exist around Build.SourceBranch and Build.SourceBranchName related to `refs/heads/feature/myfeature` or `refs/heads/user1/userbranch` . See here:
#8193

**Comment by henryju** [comment]
To me it seems the issue has been fixed. Our latest test on Azure Pipelines shows that Build.SourceBranch=refs/heads/master even for Bitbucket repositories.

**Comment by brcrista** [comment]
Thanks, this has been fixed.  https://developercommunity.visualstudio.com/content/problem/440338/bitbucketgit-user-not-shown-and-branch-indicated-w.html
