### ISSUE TITLE
New task for publish checkstyle (or other static code analysis) results

### ISSUE THREAD

**Issue by pollockm** [microsoft/azure-pipelines-tasks#7598]
## Environment
- Server - VSTS

## Issue Description

We have the option within Gradle or Maven tasks to execute and report static code analysis (checkstyle, PMD, Findbugs.  This is great, but I can't use gradle or maven with my pipeline.

We also have a task to publish test results, which just looks for test result files matching known formats (Junit, Xunit, etc).  This is great, since I can leverage these formats to get other tools to report results into VSTS.

I would like to have an additional task that publishes static code analysis result files that come from any arbitrary source, so long as they have the correct format, much like we can for unit tests.

When working with Jenkins, we leveraged the Analysis Collector Plugin (https://wiki.jenkins.io/display/JENKINS/Analysis+Collector+Plugin) with checkstyle extension to make this easy.  

Lack of this in VSTS is currently a barrier to my team moving our pipeline over to a VSTS-native solution.

**Comment by pollockm** [comment]
Any updates?

**Comment by pollockm** [comment]
Our plan of record is to hack the gradle task such that it doesn't actually do anything other than report out the checkstyle report generated by a previous step.  If there's a better option coming in the near future, please advise.

**Comment by pollockm** [comment]
@madhurig  - any chance of a Publish Static Analysis Result task in the foreseeable future?  If not, please advise and we will pursue other (less desirable) alternatives.

**Comment by madhurig** [comment]
This is not on our next quarter backlog. You can create a suggestion ticket here as well: https://developercommunity.visualstudio.com/content/idea/post.html?space=21

**Comment by pollockm** [comment]
FYI, suggestion ticket created.

**Comment by siudeks** [comment]
@pollockm provide link to created suggestion to allow followers go there and vote up

**Comment by pollockm** [comment]
https://developercommunity.visualstudio.com/idea/740428/publish-static-analysis-result-task.html

Excellent point, @siudeks

**Comment by marcoadasilvaa** [comment]
+1
