### ISSUE TITLE
Xamarin.iOS task - How to set the mono runtime version to use?

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/azure-pipelines-tasks#7606]
My build log shows that it uses mono 5.8.1. But I want to use C# 7.1 features so I need mono version 5.10.1 which, as per that [page](https://github.com/Microsoft/vsts-image-generation/blob/master/images/macos/macos-Readme.md), is installed on macOs preview queue.
1°) why isn't the latest moo version picked up?
2°) how can I specify the mono version I wan to run?

**Comment by lkillgore** [comment]
Hi @FrancoisM,

Please see [this](https://docs.microsoft.com/en-us/vsts/pipelines/agents/hosted?view=vsts#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent) link's section on Mono.  We've added this to the template for Xamarin, so hopefully this will be more visible.  Please let me know if it works for you, or if  you have any other questions.

Thanks!

**Comment by FrancoisM** [comment]
Thank you, that doc looks exactly what I need re question 2 (I feel stupid not having found it by myself). But what about question 1?

**Comment by madhurig** [comment]
@FrancoisM - Closing this issue since there is a way to explicitly set the mono version. The mono version picked is determined by the toolset (xamarin and msbuild). Let us know if you see an issue with latest versions on the Hosted macOS VMs.
