### ISSUE TITLE
NuGetV2 restore: Follow checked in nuget.config files

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/azure-pipelines-tasks#7616]
For NuGetV2, it offers two options: Use Feed(s) I select here and Feeds in my NuGet.config.

However the semantics of explicitly specifying a Nuget.config are different when actually using NuGet.exe restore on a solution. From there it traverses the parent directory chain, finds all NuGet.config files and processes them in order.

The task needs to exactly emulate this behavior otherwise the behavior will be different from desired and builds may fail. It is pretty common to have a "nested" nuget.config which clears all the feeds and adds its own. I can't underscore enough how important it is for reproducible builds to exactly match the behavior and semantics here.

I think the default behavior should be just nuget.exe restore .sln for each .sln (and make sure to change the current directory to the directory of each solution).

This is related to:
https://github.com/Microsoft/vsts-tasks/issues/6561

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
