### ISSUE TITLE
UseRubyVersion: Version spec >= 2.4 did not match any version in the tool cache.

### ISSUE THREAD

**Issue by jmoody** [microsoft/azure-pipelines-tasks#7618]
Server: VSTS
Agent: Hosted macOS Preview 

I am a MSFT FTE.  I can grant access to the project if necessary.

### Reproduce

1. Start a new project using the Xcode template
2. Add UseRubyVersion build step - use default settings (>= 2.4)
3. Add a Bash shell script that uses ruby

### Expected

Some version of ruby >= 2.4 would be installed and available.

### Found

```
2018-07-03T04:21:23.9820890Z ##[section]Starting: Use Ruby >= 2.4
2018-07-03T04:21:24.0167050Z ==============================================================================
2018-07-03T04:21:24.0182700Z Task         : Use Ruby Version
2018-07-03T04:21:24.0198400Z Description  : Retrieves the specified version of Ruby from the tool cache. Optionally add it to PATH.
2018-07-03T04:21:24.0214110Z Version      : 0.136.0
2018-07-03T04:21:24.0229060Z Author       : Microsoft Corporation
2018-07-03T04:21:24.0244060Z Help         : 
2018-07-03T04:21:24.0260060Z ==============================================================================
2018-07-03T04:21:24.8613960Z ##[error]Version spec >= 2.4 did not match any version in the tool cache.
Available versions:

2018-07-03T04:21:24.8687900Z ##[error]Version spec >= 2.4 did not match any version in the tool cache.
Available versions:

2018-07-03T04:21:24.9740000Z ##[section]Finishing: Use Ruby >= 2.4
```

### Related

* https://github.com/MicrosoftDocs/vsts-docs/issues/1201
* https://github.com/MicrosoftDocs/vsts-docs/issues/1202

**Comment by joshmgross** [comment]
Closing this issue to clean up backlog. Reopen if the solution does not work for you.

**Comment by BoazWarshawsky** [comment]
@bryanmacfarlane Does installing Ruby on mac machine is something you already supporting, I am using mac machine and getting this error:
`Version spec 2.6.1 for architecture %s did not match any version in Agent.ToolsDirectory.`

The task looks as follow:
`- task: UseRubyVersion@0
      displayName: 'Setup ruby using version $(ruby_version)'
      inputs:
          versionSpec: $(ruby_version)
          addToPath: true
`
while I tired ruby_version with the following params: <2.4, 2.6.1, 2.4, 2.6.1p33

**Comment by joshmgross** [comment]
@BoazWarshawsky you can see the installed version of ruby here: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md#language-and-runtime


If you have any more questions, could you open a new issue? This one is a few months old

**Comment by jmoody** [comment]
@joshmgross 

I cannot use the vs2017 pool machine because Xcode is required.

According to the #language-and-runtime doc you posted, ruby 2.6.1 should be available.

I tried: 2.6.1 and 2.6.1p33.

In both cases, I found this output:

```
##[section]Starting: UseRubyVersion
==============================================================================
Task         : Use Ruby Version
Description  : Retrieves the specified version of Ruby from the tool cache. Optionally add it to PATH.
Version      : 0.142.1
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=2005989)
==============================================================================
##[error]Version spec 2.6.1 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /Users/vsts/hostedtoolcache

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Ruby at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Ruby versions at https://go.microsoft.com/fwlink/?linkid=2005989.
##[section]Finishing: UseRubyVersion
```

Curious about the contents of /Users/vsts/hostedtoolcache... 

```
##[section]Starting: cat /Users/vsts/hostedtoolcache
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.148.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
==============================================================================
##[error]Invalid file path '/Users/vsts/agent/2.148.2/work/1/s'.
##[section]Finishing: cat /Users/vsts/hostedtoolcache
```

Looks like a bad symlink?

Since I don't care about the ruby version - just that a ruby exists, I tried omitting the UseRubyVersion step hoping that some ruby was installed.  I found `ruby version: ruby 2.6.1p33` was installed and my script succeeded.

**Comment by brkerr** [comment]
@jmoody 

I see the mac images have Ruby 2.6 pre-installed, so you don't need to specify the version with that task. 

https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#language-and-runtime

I am working on adding Ruby versions to the hosted tool cache on mac so it won't throw this error in the future though.

**Comment by jmoody** [comment]
I think we can close this.  I see that ~> 2.6 and ~> 2.5 work.

@brkerr
