### ISSUE TITLE
Incorrect publishing of full (qualified) test name - due to malformed TRX ?

### ISSUE THREAD

**Issue by GraueEminenz79** [Microsoft/azure-pipelines-tasks#7620]
## Environment
- Server - TFS on-premises 2017 Version 15.117.27024.0
- [NUnit3 Test Adapter](
https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter)
## Issue Description
Execute arbitrary NUnit3 test assembly with parametrized [TestCase]s with VSTest task (version 2.0.55)
__=> Full Qualifed Test Name is parsed (or concatenated) wrongly.__

![testmethod_classname name](https://user-images.githubusercontent.com/35068976/42208516-a66fb4ca-7eac-11e8-8bdb-4b809ee64554.png)

Snippet of generated .trx file
```
<TestMethod  
codeBase="Some.NUnit3.TestAssembly.dll"
adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter"
className="Some.NUnit3.TestAssembly.AssertTests.Comparison.LessOrEqualTests._LessOrEqual_NumericValues_ThrowsNothing(-25_"
name="LessOrEqual_NumericValues_ThrowsNothing(-25.0d,-25)" />
```
My assumption is that the **last '.'** is used to identify the delimiter of ```className``` and the ```name``` of the Test Case name.
But as the test case is parametrized with Parameters having "." (dots) e.g. ```(-25.0d,-25)``` the parsing goes wrong somehow.
(Same applies _sometimes_ with the "," if the className attribute in TRX has a namespace given - which is given after a ", ", e.g.
```className="SomeArbitraryClassName, ItsNameSpace"```
(Or how is the semantic of className ?)

**Comment by abhishkk** [comment]
@GraueEminenz79 We are able to reproduce this issue and working on the fix.
