### ISSUE TITLE
Azure App Service Deploy - Function App for Linux

### ISSUE THREAD

**Issue by vdcloud** [Microsoft/azure-pipelines-tasks#7637]
I need to publish a Function App v2 (i.e. .NET Core) on a Linux App Service Plan. I would have used the Windows App Service Plan but I already have a linux plan in my resource group and therefore it wont let me create a windows plan in the same resource group (which i believe is a known limitation as of now). Hence, my only option is to use a Linux plan for my Function Apps.

I am using Azure App Service Deploy Task version 4 in VSTS. In the App Service Deploy task, I tried two different options.

1. Use "Function App" option for App Service Type. If i use this option, it seems the task is unable to connect with the linux host and gets a 405 - Method Not Allowed (ERROR_COULD_NOT_CONNECT_TO_REMOTESVC). I did not select the "Use Web Deploy" option so was hoping this to go through as the task is supposed to use the Kudu REST API.

2. Use "Web App on Linux" option for App Service Type. When i use this option, the task is able to connect with the host and push the functions zip deploy package to the host successfully. The issue is that the task wont recognize the package as a Functions package, and does not automatically register the Functions from functions.json. Do i need to do something extra to register the functions, is there a startup command i can run or is this just not the scenario it would support.

Any pointers will be helpful.

**Comment by elanderson** [comment]
I had this same issue and my problem was the deployment Agent pool wasn't using Hosted Linux.

**Comment by vincentdass** [comment]
@vdcloud , @bmpcon , @elanderson ,

We added support for `Function App on Linuz` in `4.*` task version.
![image](https://user-images.githubusercontent.com/20121508/47495904-fef2da80-d872-11e8-9d81-0bc2393be6f8.png)
Please select the above option and rerun the deployment.
