### ISSUE TITLE
Windows Machine Copy Task with empty password

### ISSUE THREAD

**Issue by Zefek** [microsoft/azure-pipelines-tasks#7652]
## Troubleshooting
When I need to deploy to computer by Windows Machine Copy Task and account has not password. It is friendly computer which could be accessed from network only. 

## Environment
TFS 2018.02.
- Agent - Hosted or Private: 
    
Private agent - Windows 2016 Server, agent version 2.122.1

I think it is intent because I found throw exception when password is empty in source code of task. But I think there could be exists account with empty password (I know it is security issue but computer could not be accessed from nowhere one computer from only).

**Comment by SumiranAgg** [comment]
@Zefek Thanks for reporting the issue. For now can you use robocopy command in Powershell task.
If more customers come back with the same requirement, we will add support for this.
