### ISSUE TITLE
TFS2018U2 includes PublishTestResults 2.0.4 containing forced merge warning even if explicitly configured to merge

### ISSUE THREAD

**Issue by japj** [microsoft/azure-pipelines-tasks#7658]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- TFS2018U2
- Agent - windows server 2016, v2.133.3
- Publish Test Results v2.0.4

## Issue Description

Since upgrading from TFS2018U1 to TFS2018U2 we suddenly have build warnings related to "Number of results files is greater than 100. Therefore merging all files to publish results against a single test run.".

Since we prefer to NOT have any warnings during the build, we tried to force the merge by explicitly configuring the task ("Merge test results" true). However, the warning remains.

Looking at the changeset https://github.com/Microsoft/vsts-tasks/commit/55ed7411bf0cc39df59b87b78a2a47adc38be245 it seems the "forceMerge" warning was changed to a debug statement, but this is not yet included in TFS2018U2 (it seems to have been fixed in the task version 2.0.5)

How do we get this fix to TFS2018U2 in order to get rid of this build warning?

**Comment by navin22** [comment]
@japj We have fixed this in the TFS 2018 U3 release.

**Comment by puagarwa** [comment]
@japj  are you still facing this issue, if yes can you please update your TFS server. we have fixed this issue in TFS 2018 U3 ?

**Comment by SadagopanRajaram** [comment]
Closing this issue - the fix is in TFS 2018 Update 3. Request to upgrade to this version or later.
