### ISSUE TITLE
Test run name doesn't equal Pusblish Test Results argument Test run title

### ISSUE THREAD

**Issue by pondelknimojdan** [Microsoft/azure-pipelines-tasks#7699]
## Environment
- TFS on-premises
    
    - Version: 16.122.27409.2

## Issue Description

In task Publish Test Results (version 2.*) Test run title is "iCenter API: API tests" but in Test -> Runs I get name of test run "iCenter API: API tests_1"

![1](https://user-images.githubusercontent.com/41009636/42618101-4521165a-85b4-11e8-833e-4e337f1b0272.PNG)
![2](https://user-images.githubusercontent.com/41009636/42618107-475810fe-85b4-11e8-9d9b-c9ec38e9a230.PNG)

**Comment by pagangil** [comment]
@pondelknimojdan Can you please tell the agent version you are using?

**Comment by pondelknimojdan** [comment]
@pagangil  Agent.Version is  2.122.2

**Comment by pagangil** [comment]
@pondelknimojdan Thanks for telling the agent version. We've fixed this issue in our latest agent version. With the fix, we don't append "_1" to run name if there is just a single run. Can you upgrade your agent version and try again?

**Comment by pondelknimojdan** [comment]
@pagangil Hi! I cannot upadate agent, but I can back to you when our agent is updated.

**Comment by SadagopanRajaram** [comment]
@pondelknimojdan - I assume you are fine with upgrading to the new agent for resolving this issue and I am closing it. Let me know if otherwise.
