### ISSUE TITLE
donet push task for .NET Core with 'nuget push' command is missing option to 'allow duplicates to be skipped'

### ISSUE THREAD

**Issue by morshilo** [microsoft/azure-pipelines-tasks#7704]
## Issue Description

Using the .net core dotnet nuget push task with version 2.* ,
and notice that this task is missing the option to 'allow duplicates to be skipped' like the NuGet task for .Net.
Appreciate if you can supply similar solution to skip duplicates. it is very useful!

### Error logs

409 (Conflict - The feed already contains XXX)

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
