### ISSUE TITLE
docker cli is required in PATH

### ISSUE THREAD

**Issue by hangy** [microsoft/azure-pipelines-tasks#7707]
## Environment
- Server - TFS 2018
- Agent - Private

## Issue Description

When using the Docker v0.2.7 task, it is apparently not possible to run it on an agent where the `docker` command is not available in the `PATH`.

Considering we can specify that the docker command should be run on a remote host, a global install of the Docker CLI an the build agents should not be expected. Instead, the task could add a `docker` demand, and a `DockerTool` task could install the required CLI version from https://download.docker.com/ and satisfy the deman, like `NodeToolV0` does for Node.

That would allow us to run docker commands from several VSTS Agents on a central Docker server, without blocking a VSTS Agent on the Docker server, and without having to setup Docker/Windows Containers on every VSTS Agent.

### Error logs

```
******************************************************************************
Starten: Build an image
******************************************************************************
==============================================================================
Task         : Docker
Description  : Erstellen Sie Docker-Images, übertragen Sie sie mithilfe von Push, und führen Sie sie aus, oder führen Sie einen Docker-Befehl aus. Die Aufgabe kann mit Docker oder Azure Container Registry verwendet werden.
Version      : 0.2.7
Author       : Microsoft Corporation
Help         : [Weitere Informationen](https://go.microsoft.com/fwlink/?linkid=848006)
==============================================================================
Ausnahmefehler: Fehler which: Nicht gefunden docker: null
******************************************************************************
```

**Comment by hangy** [comment]
> @hangy Are you looking for this:
> ![image](https://user-images.githubusercontent.com/6857119/51464729-4b738680-1d8c-11e9-9067-0b6dfbb2ee4c.png)
> Let me know if this does not solve your problem.

That option is the reason why I opened this issue. At least when used with the DockerV0 task in TFS 2018, you need to have `docker.exe` in the `PATH`, or the task will simply fail, because it cannot find `docker.exe` on the remote Docker host.

**Comment by azooinmyluggage** [comment]
We have added a new Docker tool installer task to address this scenario https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerInstallerV0
