### ISSUE TITLE
pickList+MultiSelectFlatList as source to VisibleRule doesn't work with multiple options selected

### ISSUE THREAD

**Issue by pinkfloydx33** [Microsoft/azure-pipelines-tasks#7711]
## Environment
- Server - OnPrem, 2018 Update 2
    
## Issue Description

At the moment it does not seem possible to use a MultiSelectFlatList (with multiple values) as the source of a visible rule. Consider the following:

  ```
 "inputs":[  
      {  
         "name":"opts",
         "type":"pickList",
         "label":"Opts",
         "defaultValue":"",
         "properties":{  
            "EditableOptions":"False",
            "MultiSelectFlatList":"True",
         },
         "options":{  
            "A":"Option A",
            "B":"Option B",
            "C":"Option C"
         },
         "required":"True"
      },
      {  
         "name":"A",
         "type":"string",
         "label":"A",
         "defaultValue":"",
         "required":false,
         "visibleRule":"opts = A"
      },
      {  
         "name":"B",
         "type":"string",
         "label":"B",
         "defaultValue":"",
         "required":false,
         "helpMarkDown":"",
         "visibleRule":"opts = B"
      },
      {  
         "name":"C",
         "type":"string",
         "label":"C",
         "defaultValue":"",
         "required":false,
         "helpMarkDown":"",
         "visibleRule":"opts = C"
      }
]
```

If you only select ONE option in the multi select list, the A/B/C inputs will toggle visibility. However, if you select two (or more) options in the drop down, ie A+B (which evaluates to "A,B" when received as task input) the visibility rule no longer works. I would expect the visibleRule to work more like a *contains* in this case.

I tried this (which becomes unwieldy the more options you have):
`"visibleRule":"opts == A || opts == A,B || opts == A,B,C || opts == A,C"`
However it was rejected as invalid when I attempted to upload it. So I tried quoting the values:
`"visibleRule":"opts == A || opts == \'A,B\' || opts == \'A,B,C\' || opts == \'A,C\'"`  This was also rejected.

> Task definition visible rule 'opts == A || opts == 'A,B' || opts == 'A,B,C' || opts == 'A,C'' is invalid. It should be of format "A <validconditionhere> B" for Task

Is it possible to use the MultiSelect pickList as the source of a visible rule? Am I missing something or can this just not be done?

**Comment by bryanmacfarlane** [comment]
please create an issue in azure-pipelines-task-lib
