### ISSUE TITLE
resultSelector variable

### ISSUE THREAD

**Issue by gaskem** [Microsoft/azure-pipelines-tasks#7717]
Hi,

I'm just starting out writing a custom extension for VSTS; within task.json i have an input picklist ($location) thats bound to a datasource which retrieves a list of locations. I want to then use the selected location to filter the results for another input picklist. But the endpoint url does not contain the location and trying to filter the json result using $location in `resultSelector` does not return any results. (i have replaced $location in resultSelector with text to confirm the datasource is ok). Here's the code im using, any suggestions on where im going wrong please?:

`target": "networkSG",`
`"endpointId": "$(ConnectedServiceName)",`
`"endpointUrl": "{{{endpoint.url}}}/subscriptions/$(endpoint.subscriptionId)/resourcegroups/$(resourceGroupName)/providers/microsoft.Network/networkSecurityGroups?api-version=2018-02-01",`
`"resultSelector": "jsonpath:$.value[?(@.location ==$(location))].name",`
`"parameters": { "location": "$(location)" } `

**Comment by bryanmacfarlane** [comment]
please create an issue in azure-pipelines-task-lib
