### ISSUE TITLE
Java Tool Installer task fails when JDK provided as zip file

### ISSUE THREAD

**Issue by osmanrafiqss** [Microsoft/azure-pipelines-tasks#7725]
## Environment
-Server VSTS
account name: osmanrafiq
project name: MyFirstProject
build definition: MyFirstProject-Maven-CI
build number: Build 20180710.1

-Agent Hosted
agent queue name: Hosted

## Issue Description
When using the "Java Tool Installer" providing the JDK as a zip file causes the task to fail.
The issue can be worked around by providing the JDK as a 7zip file.

### Error logs
[logs_25.zip](https://github.com/Microsoft/vsts-tasks/files/2192670/logs_25.zip)

### PR
#7724

**Comment by kelliejos** [comment]
This issue was resolved with the linked PR #7724. Closing as fixed.
