### ISSUE TITLE
Having multi-configuration with different agent requirements per agent.

### ISSUE THREAD

**Issue by LokiMidgard** [Microsoft/azure-pipelines-tasks#7726]
## Environment
TFS 2018 update 2 with private agent version 2.134.2 on Windows 7

## Issue Description

In my test envirment I have multiple VMs. For Every combination of OS, Office version and bitness we have one VM. When we run our tests we decide on which vm's the test will run and start one build with the list of the VM's.

Our Build is defined as a three phase build
1. (singel agent) Resotres the test machines and copys and configure an agent on each machine for the test queue
2. (multi-configuration) Get the artefacts and starts the tests
3. (singe agent) cleanup the test agents from the test queue

The problem I currently facing is that I can't set an agent requirement on the variable that was splited in the multi configuration. What can happen if I ommit the requirement is that the Windows 10 test build runs on Windows 7 and vice versa. 

At least the phase failse instantly when I try to use the $(machineName) variable. But without any data. I assume an agent is searched with the capability of the concated list of machines instead of the singel machine name.

**Comment by LokiMidgard** [comment]
For me it looks like this can only enabled in the visual studio team services not the team foundation server. I don't see a setting to enable preview features there.

**Comment by bryanmacfarlane** [comment]
Correct, service only.  yaml coming to on-prem soon
