### ISSUE TITLE
Mocha JUnit test reporter steals command-line output

### ISSUE THREAD

**Issue by brcrista** [Microsoft/azure-pipelines-tasks#7743]
Running `node make.js test` should produce command-line output like

![image](https://user-images.githubusercontent.com/33549821/42764998-036b8dc4-88e5-11e8-951b-b040162c6bb4.png)

#7644 changed the test command to report output to a JUnit XML file, but output is no longer appearing on the command line.  Reverting the change and re-running NPM install fixes the issue.

**Comment by nigurr** [comment]
@brcrista will be fixed https://github.com/Microsoft/vsts-tasks/pull/7747

**Comment by brcrista** [comment]
Thanks -- I also noticed that the test results are not getting published in the CI builds when tests fail.  I will create a separate issue for that.
