### ISSUE TITLE
Unable to locate executable file: 'D:\a\_tasks\Sample_59e31f9a-3597-43e6-bb4b-1f0a4e21d1b5\0.2.112\modules\TestResultsPublisher.exe'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

### ISSUE THREAD

**Issue by AbinsC** [microsoft/azure-pipelines-tasks#7746]
I am trying to create a VSTS extension by modifying PublishTestResultsV2. But when published and added to build definition, it gives me below error.

Unable to locate executable file: 'D:\a\_tasks\Sample_59e31f9a-3597-43e6-bb4b-1f0a4e21d1b5\0.2.112\modules\TestResultsPublisher.exe'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

**Comment by kushaga** [comment]
Hi @AbinsC seems like you are missing TestResultsPublisher.exe dependency when you are building , if you are doing it outside the repo. then you have to manually download the dependency https://publishtestresults.blob.core.windows.net/publishtestresults/9421537/PublishTestResults.zip

this is done in our repo. here ->
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishTestResultsV2/make.json
https://github.com/microsoft/azure-pipelines-tasks/blob/master/make.js
