### ISSUE TITLE
[DotNetCoreInstaller] will need to be updated for upcoming breaking changes to releases.json

### ISSUE THREAD

**Issue by kdubau** [microsoft/azure-pipelines-tasks#7754]
Not sure the best way to track this, but I was recently made aware the [releases.json file](https://github.com/dotnet/core/blob/master/release-notes/releases.json) will be changing format soon, and thus break this task. Please see: https://github.com/dotnet/core/issues/1775#issuecomment-405355707

**Comment by sachinma** [comment]
This is fixed v2 of the task
