### ISSUE TITLE
Task: NuGet Custom wont't let you choose the VSTS Feed

### ISSUE THREAD

**Issue by DerAlbertCom** [microsoft/azure-pipelines-tasks#7755]
With the NuGet V2 Task it is possible to choose the VSTS (or other) NuGet Feed which should be used (on the Command Restore and Push). This is not possible if i choose custom.

But currently we need this. We are installation a template package for docfx from our vsts nuget-server.

![NuGetCustomInstall](https://user-images.githubusercontent.com/136992/42826488-cb1d2350-89e4-11e8-9d01-cda3cfc21f17.png)

But sadly I can't select our VSTS feed, so the install failed.

Adding the PAT to global nuget.config only works on an on-premise build server. Not with Hosted Builds.

So, please enable adding VSTS feeds on custom Commands. Or add an Install Command ;)

**Comment by DerAlbertCom** [comment]
This is also problematic on 'dotnet test' which does an implicit dotnet restore.

**Comment by DerAlbertCom** [comment]
Any Update on this? Cant make a nuget install without an private buildserver where I can modify the Global NuGet.config.

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
