### ISSUE TITLE
NuGet pack Include Referenced Projects can only be set when versioning scheme is Off

### ISSUE THREAD

**Issue by jmezach** [microsoft/azure-pipelines-tasks#7783]
## Environment
TFS 2018 Update 2
Private build agent 2.133.3 running on Windows Server 2012 R2

## Issue Description
With the NuGet task, when using the pack command, you can only set the Include Referenced Projects option if the versioning schema is set to Off. However, setting that option first and then changing the versioning schema works just fine, and you can see in the build definition that the flag is indeed set and the flag is passed to NuGet when the build is run, so this seems to be a UI glitch. Also, the implementation of the task doesn't seem to care about the versioning scheme when checking the includeReferencedProjects flag.

Is there a particular reason that the option is only visible when versioningScheme is set to off as can be seen in the screenshots below?

<img width="1007" alt="screenshot 2018-07-19 13 03 29" src="https://user-images.githubusercontent.com/1225489/42938947-60ea07fc-8b54-11e8-97cd-09c1c7ac8de9.png">
<img width="1008" alt="screenshot 2018-07-19 13 04 44" src="https://user-images.githubusercontent.com/1225489/42938957-68915ad2-8b54-11e8-818f-bf9f4c4d342f.png">

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
