### ISSUE TITLE
XML variable substitution: log each substituted variable

### ISSUE THREAD

**Issue by lzandman** [microsoft/azure-pipelines-tasks#7785]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- TFS on-premises

## Issue Description

Current the only thing we see in our logs when we use XML variable substitution is:
> XML variable substitution applied successfully

We'd like some more logging. Specifically which variables in which files are replaced . When you run the deployment task in debug mode (`System.Debug` set to `true`) this information is available, but we don't want to run everyting in debug mode.

**Comment by SumiranAgg** [comment]
@lzandman Thanks for the feedback. We will incorporate this in our backlog. We will display what fields have been transformed in the normal logs itself.
Though this may take some time as we are prioritizing issues which have major customer impact.

**Comment by eaarora-ms** [comment]
Hi, We have made the necessary changes. Please feel free to reopen the issue in case you have any doubts.
