### ISSUE TITLE
Package: NuGet (Push) -  NuGetCommand2 input externalEndpoint references endpoint does not exist or has not been authorized for use (and no longer allows queuing builds)

### ISSUE THREAD

**Issue by trevorNgo** [microsoft/azure-pipelines-tasks#7790]
## Troubleshooting
Problem:  A potential verification issue, when YAML contains a deprecated-value in "ExternalEndpoints"; regardless if "nuGetFeedType" is set to **internal**, the feed path in "ExternalEndpoints" is verified and will not allow build to queue if feed path or service endpoint no longer exists. 

![image](https://user-images.githubusercontent.com/23327878/42959059-79b03102-8b55-11e8-8e3f-a0d3e4c4b7f2.png)

My hypothesis is that a verification step is run on all values stored in the YAML despite the feed source set for internal or "This account/collection". 

![image](https://user-images.githubusercontent.com/23327878/42959377-92c360c8-8b56-11e8-9fd2-ba06f129adfd.png)

### Concerns
I have tested when switching and saving NuGet Step to a demo "external NuGet server" and then back to "[Internal] Account/Collection", the value of the feed path (of demo) is not cleared from the ExternalEndpoints field in the YAML. This means in future builds whenever there is any change in service endpoints reference, this may break or prevent from queuing other VSTS builds.

## Environment
   VSTS Private Build Agents

### Error logs

![externalendpoint issue](https://user-images.githubusercontent.com/23327878/42958715-5b9682ee-8b54-11e8-9228-9e148dccd781.png)

### Temporary Fix
Switching from "Internal Accounts/Collections" feed to an _**existing**_ "External NugetServer" Feed and then back to "Internal Accounts/Collections" feed.

### Permanent Fix
Deleting and re-adding NuGet Push Step Template to Build and Deploy Process

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
