### ISSUE TITLE
dotnet nuget push with NuGet feed at local directory

### ISSUE THREAD

**Issue by hangy** [microsoft/azure-pipelines-tasks#7798]
## Environment
- Server - TFS 2018
- Agent - Private

## Issue Description

When DotNetCoreCLI v2.137 using the `nuget push` command, it is not possible to use a private UNC path as a NuGet feed. As TFS 2018 only allows us to add external NuGet feeds using a HTTP(S) URL, we cannot add our local NuGet feed that's hosted on a DFS share. Given the only VSTS task that can publish to a UNC path is the deprecated NuGetPublisherV0 task, this should really be supported by DotNetCoreCLI (and/or NuGetCommandV2).

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
