### ISSUE TITLE
Support a predefined `login` action in the Docker task

### ISSUE THREAD

**Issue by alexvy86** [Microsoft/azure-pipelines-tasks#7803]
## Environment
VSTS

## Issue Description

Enhancement request for the Docker task.

Right now in order to use the Docker task just to login to the registry, so other steps in the build/release phase can call the `docker` CLI directly, we need to use the `Run a Docker command` action, specify "login", **and pass the credentials manually** (hardcoded, from variables, or somehow).

Since the credentials are already stored in the Docker Registry Connection endpoint, it'd be nice if the Docker task supported a predefined `login` action (like `Build an image` or `Run a Docker command`) so it passed the credentials that we already provided for the endpoint, and we didn't have to write them (and maintain them) in other places as well.

**Comment by bansalaseem** [comment]
@alexvy86 Thanks for asking for this. Last week we were internally discussing this feature only and since you also need it, it will make it much easier to add now.

**Comment by azooinmyluggage** [comment]
Thanks for the feedback.
We are very close to getting this done. Next deployment will start rolling out this change.

**Comment by RoopeshNair** [comment]
It is getting rolled out, closing the issue. 
![image](https://user-images.githubusercontent.com/1370480/47003423-cead8c80-d14c-11e8-8f43-1ce4a85e7de8.png)
