### ISSUE TITLE
Please generate and upload diagnostic VSBuild logs when System.Debug is true

### ISSUE THREAD

**Issue by heaths** [Microsoft/azure-pipelines-tasks#7823]
It would be nice if the VSBuild task uploaded a diagnostic log when `System.Debug` is 'true', much like the VSTest@2 task does (see its vstest.ts source). This can be done with an additional task currently, but then the log filename doesn't line up (i.e. doesn't have the same ordinal prefix) and is something build administrators / developers have to do before a problem arises, vs. just kicking a new build with `System.Debug` = `true`.

**Comment by moswald** [comment]
@heaths I've created a [Developer Community thread](https://developercommunity.visualstudio.com/idea/385165/upload-diagnostic-vsbuild-logs-when-systemdebug-tr.html) for this. We use Developer Community votes for prioritizing new(-ish) features like this, so please vote it up if you are still interested in it. Thank you!
