### ISSUE TITLE
Helm package Error: Endpoint data parameter  not present: authorizationType

### ISSUE THREAD

**Issue by jaq316** [microsoft/azure-pipelines-tasks#7828]
## Environment
- Server - VSTS or TFS on-premises? VSTS
    
   
    - If using VSTS, provide the account name, team project name, build definition name/build number:  lsproperty, Lightstone Team, Lightstone.TransactionManagement build #0.1.0-unstable.13

- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Docker hub image jaq316/vsts-agent-gitversion based on microsoft/vsts-agent:latest

## Issue Description

The helm package command is failing with the error ``Error: Endpoint data parameter ab374f9b-0428-4dfc-a00c-3508e7de3eb0 not present: authorizationType``. Screenshot below:

![image](https://user-images.githubusercontent.com/4570389/43197043-3d8b5846-900a-11e8-996c-75f8ca357854.png)

Also... See the config screenshot below

![image](https://user-images.githubusercontent.com/4570389/43197138-87b0a3cc-900a-11e8-92f4-21d53bb9cfa5.png)

### Error logs

[logs_747.zip](https://github.com/Microsoft/vsts-tasks/files/2227619/logs_747.zip)

**Comment by vithati** [comment]
@jaq316, We have identified issue and fixed the issue https://github.com/Microsoft/vsts-tasks/pull/7779.  We are deploying the fix. I will update once fix deployed.

**Comment by jaq316** [comment]
Awesome. Thank you. Will await deployment
