### ISSUE TITLE
The WaitForComplete property is ignored

### ISSUE THREAD

**Issue by elendil326** [microsoft/azure-pipelines-tasks#7833]
The WaitForComplete variable is not being set as a property of the execute section, therefore ignoring its value.

https://github.com/Microsoft/vsts-tasks/blob/d3d09824dbfea8b8dcdddf18ae5f22026ca44385/Tasks/PublishToAzureServiceBusV1/task.json#L96-L113

**Comment by bansalaseem** [comment]
Service Bus task has an option to fire & forget and it is via this code. 

https://github.com/microsoft/azure-pipelines-tasks/blob/d3d09824dbfea8b8dcdddf18ae5f22026ca44385/Tasks/PublishToAzureServiceBusV1/task.json#L94
