### ISSUE TITLE
Builds stuck on symbols publishing

### ISSUE THREAD

**Issue by gravufo** [microsoft/azure-pipelines-tasks#7837]
## Environment
TFS 2017.2

## Issue Description

Builds get stuck on symbols publishing because the Publish Symbols task locks the symbol server with _lockfile.sem.
`##[warning]Semaphore file '\\server\SymbolServer\_lockfile.sem' already exists. Retrying symbol publishing in 10 seconds.`

We have a ton of builds that run at the same time and we have always had a single symbol server for all of them and it worked flawlessly using symstore.exe. Now that we are gradually moving to vNext, this issue is becoming very apparent and critical, because builds get stuck and will timeout while waiting to get the lock.

Is there any way to prevent locking the symbol server when uploading? Is there a workaround?

Thanks

**Comment by StingyJack** [comment]
I've just had this happen for the first time on a TFS 2015 server. We have dozens of build defs and this file only became a problem when I happened to cancel a build when it was in the middle of publishing symbols. Deleting the lock file let the in-progress build continue OK.

**Comment by deadlydog** [comment]
I'm seeing the same problem and we're using on-prem TFS 2018 Update 3. It seems to have just started in the last couple days, but we hadn't changed anything that I'm aware of.

**Comment by gravufo** [comment]
@bryanmacfarlane @jerickmsft any news on this? It's a pretty major issue for big setups with a ton of build definitions.

**Comment by gravufo** [comment]
Hello? Are we talking to a wall? This is completely ridiculous. Please answer. Hundreds of builds are getting stuck waiting to publish symbols because of this stupid lockfile. Please explain why this lockfile is being used and what kind of mitigation actions can be done to prevent this.

**Comment by jerickmsft** [comment]
@gravufo Is the concern that the lock file is behaving incorrectly or is that there is a lock file at all?

@ericsciple Do you know why the lock file exists?

**Comment by jerickmsft** [comment]
Ah it looks like this is by design per the symstore documentation:
https://docs.microsoft.com/en-us/windows/desktop/debug/using-symstore

> SymStore does not support simultaneous transactions from multiple users. It is recommended that one user be designated "administrator" of the symbol store and be responsible for all add and del transactions.

**Comment by gravufo** [comment]
@jerickmsft Thank you for your answer, I appreciate it. Having waited so long for a simple acknowledgement is very frustrating. I did suspect that symstore does not support simultaneous transactions, being based on a file instead of a database. Are you aware of any plans to improve symbol servers or do we really have no options here?

Also, is the same restriction applied for symbol server hosted inside TFS instead of a file share?

Thanks again!

**Comment by jerickmsft** [comment]
Hi @gravufo  - I should have started with an apology for the radio silence - thanks for poking the issue.

Hosted Azure DevOps **does** allow for concurrent publish of symbols across multiple builders. 

See here for how to point Visual Studio and/or WinDBG to the service: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops

**Comment by StingyJack** [comment]
> One **user** 

Wow, that's kinda antiquated. Are there any queue systems that can be plugged in to alleviate this? (At least for builds)

**Comment by jerickmsft** [comment]
@StingyJack I'm not sure I follow.  SymStore doesn't support concurrency, so it recommends a single user to act as the mutex.  Instead of tying to a user for exclusivity, this build task implements a lock file.  The lock file is not a FIFO queue, but changing it to be one would not increase the overall throughput anyway.

**Comment by gravufo** [comment]
Sure, it doesn't support simultaneous edits to the admin file, but that is handled by symstore.exe itself. writing the transaction to the admin file takes a millisecond, what's long is uploading all the pdbs to the file share. We've been running symstore.exe on multiple builds in parallel for years on the XAML build system. Looking through the code, my guess as to why there is a mutex is that you'retrieving the transaction ID from the file rather than from the symstore output. Maybe something can be revisited here?

As I was saying, this is quite unusable in its current state for deployments with hundreds of build definitions.

PS: I'm using TFS 2018 3.2. You're saying parallel upload to the devops server works, but does it work on prem as well?

PPS: are there any planned improvements at Microsoft to symbol servers in general at all? Using a database rather than a file would probably solve this simple issue...

Thanks again for your help!

**Comment by mitchdenny** [comment]
@gravufo at this point in time we don't have any plans to bring the Azure Artifacts symbol server functionality to Azure DevOps Server 2019 since in the general case it doesn't provide much beyond using a file-share for on-premises scenarios.

We'll take a look the queuing idea although no commitment at this stage.

**Comment by StingyJack** [comment]
> The lock file is not a FIFO queue, but changing it to be one would not increase the overall throughput anyway.

@jerickmsft - the problem is builds are getting stuck. Putting a queue in front of symstore that can meter the symstore requests is a cheap way to resolve the sticking.

**Comment by fadnavistanmay** [comment]
Please use the new version of Index and Publish Symbols. Thanks.
