### ISSUE TITLE
Failed: ETIMEDOUT connect ETIMEDOUT error while running tests on browserstack through npm task

### ISSUE THREAD

**Issue by smadala** [Microsoft/azure-pipelines-tasks#7880]
_From @ShaifaliKhera on July 30, 2018 8:53_

I have a protractor test automation framework which is integrated with browserstack. When I run the tests from local system in browserstack, the tests run fine. But on "Hosted VS2017" agent, when npm task run to start tests on browserstack (and wait for the results), the tests are failing at random places with Failed: ETIMEDOUT connect ETIMEDOUT error.  The issue is not from the browserstack side and we don't have any proxy. What can be the reason of failure?

_Copied from original issue: Microsoft/vstest#1703_

**Comment by smadala** [comment]
@ShaifaliKhera Can you provide more details about to how repro the issue?
What is the exact `vstest.console.exe` command you are running?

**Comment by smadala** [comment]
_From @ShaifaliKhera on July 31, 2018 0:41_

I'm using npm task to run "npm run e2e-browserstack" command specified in package.json file, which actually calling  "node ./node_modules/protractor/bin/protractor ./e2e/protractorBrowserstack.conf.js" command. I have protractorBrowserstack.conf.js file which controls running tests on browserstack. Can't share the whole framework for you to reproduce the issue. do you need any specific file, then I can share that? When the tests run on browserstack it takes some time for them to execute like 1-2 minutes and then it prints the logs on console. It seems like Hosted VS2017 idle timeout is very less, so it's timing out when waiting for the response from browserstack.

**Comment by smadala** [comment]
Looks like issue related to Hosted VS2017. Moving to `vsts-tasks` repo.

**Comment by ShaifaliKhera** [comment]
Can someone reply to this plz? I’m currently blocked because of it

**Comment by moswald** [comment]
@ShaifaliKhera Is this still an issue? If it is, can you share your Azure DevOps organization account name so we can look into the telemetry?

**Comment by davoodharun** [comment]
I am currently experiencing this exact issue. I am using protractor 5.2.1 and jasmine 2.9.0. I have an npm run script that runs the command babel-node node_modules/.bin/protractor conf.js to link to browserstack.

I am running this command through a docker run task in azure build pipelines. It seems like I can run this locally with no issue with a suite of 16 tests. however, whenever I run this on azure pipelines the last test of the 16 always times out with the error:

```
Error: ETIMEDOUT connect ETIMEDOUT 207.254.8.3:80
[chrome #01-15]     at ClientRequest.<anonymous> (/usr/src/app/node_modules/selenium-webdriver/http/index.js:238:15)
[chrome #01-15]     at ClientRequest.emit (events.js:193:13)
[chrome #01-15]     at Socket.socketErrorListener (_http_client.js:397:9)
[chrome #01-15]     at Socket.emit (events.js:193:13)
[chrome #01-15]     at emitErrorNT (internal/streams/destroy.js:91:8)
[chrome #01-15]     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
[chrome #01-15]     at processTicksAndRejections (internal/process/task_queues.js:81:17)Error
[chrome #01-15]     at ElementArrayFinder.applyAction_ (/usr/src/app/node_modules/protractor/built/element.js:459:27)
[chrome #01-15]     at ElementArrayFinder.(anonymous function).args [as isEnabled] (/usr/src/app/node_modules/protractor/built/element.js:91:29)
[chrome #01-15]     at ElementFinder.(anonymous function).args [as isEnabled] (/usr/src/app/node_modules/protractor/built/element.js:831:22)
[chrome #01-15]     at and (/usr/src/app/node_modules/protractor/built/expectedConditions.js:185:34)
[chrome #01-15]     at /usr/src/app/node_modules/protractor/built/expectedConditions.js:90:20
[chrome #01-15]     at fn.then (/usr/src/app/node_modules/protractor/built/expectedConditions.js:92:72)
[chrome #01-15]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
[chrome #01-15] Error: Top menu sub menu item '/^Smart Grid ＆ Smart Meter$/' Could Not Be Found
[chrome #01-15]     at browser.wait.catch.error (/usr/src/app/tests/pages/BasePage.js:103:15)
[chrome #01-15]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
[chrome #01-15] (node:202) UnhandledPromiseRejectionWarning: WebDriverError: Session not started or terminated
[chrome #01-15]     at Object.checkLegacyResponse (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:546:15)
[chrome #01-15]     at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:509:13)
[chrome #01-15]     at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
[chrome #01-15]     at processTicksAndRejections (internal/process/task_queues.js:86:5)Error
[chrome #01-15]     at ElementArrayFinder.applyAction_ (/usr/src/app/node_modules/protractor/built/element.js:459:27)
[chrome #01-15]     at ElementArrayFinder.(anonymous function).args [as getText] (/usr/src/app/node_modules/protractor/built/element.js:91:29)
[chrome #01-15]     at ElementFinder.(anonymous function).args [as getText] (/usr/src/app/node_modules/protractor/built/element.js:831:22)
[chrome #01-15]     at UserContext.it (/usr/src/app/tests/specs/SmartGridAndSmartMeterPage.spec.js:28:56)
[chrome #01-15]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by bowka** [comment]
I am getting this issue as well. But I didn't find any solution. even this issue is closed :(
does somebody know what is causing the issue?

**Comment by ivan-xue-prospa** [comment]
same here, I am getting the same issue and cannot find any solution. We provisioned one VM as test agent and installed Docker for the container. When we run the tests in local, everything works fine, but when running in the test agent, we got this issue.

**Comment by dawolff-ms** [comment]
We're also in a similar situation. We've reached out to BrowserStack support and they claim that the "ETIMEDOUT connect ETIMEDOUT" error is due to connectivity issues from the agents end or due to executing behind a proxy. As far as we're concerned we're not behind a proxy, so we're unsure what to do.

Can we get some information on how to proceed? Is there anything we can do to debug this situation - either for ourselves or to help you narrow down the issue?

@moswald are you still able to look into this issue for us?

**Comment by moswald** [comment]
Thanks for the @-mention, I missed the other follow-ups for some reason.

You will get better traction by filing a new issue at our [Developer Community site](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by dawolff-ms** [comment]
I've created a new issue on the Developer Community site. You can find it [here](https://developercommunity.visualstudio.com/content/problem/936198/browserstack-connectivity-issues-in-release-pipeli.html).
