### ISSUE TITLE
Add support for additional arguments in Docker Compose build task for Build service images action

### ISSUE THREAD

**Issue by stromsky** [microsoft/azure-pipelines-tasks#7882]
## Issue Description

When building images using Docker Compose build task, it has awesome feature that can add additional tags to all images in docker-compose file, but I am missing option for specifying additional arguments that could be passed to docker-compose command, e.g. --no-cache (but [other options](https://docs.docker.com/compose/reference/build/) could be also useful).

I could definitely use "Run a Docker Compose command" action with `build --no-cache` instead of "Build service images", but that way I would lose ability to add custom tags. 

Is there a reason why you don't allow to add extra arguments for build command (and probably other commands too)?

**Comment by azooinmyluggage** [comment]
Hi,
thanks for the feedback. We are refactoring our tasks to make them more command line friendly. In the end, the Docker Compose task is a wrapper on top of cli and there must be a way to pass arguments. You will see the new changes in Docker, Helm and Kubectl tasks first. We will work on making similar changes to Docker Compose too.

**Comment by cjbush** [comment]
+1. I'd like to add --parallel to speed up our pipeline

**Comment by pantanuj** [comment]
> +1. I'd like to add --parallel to speed up our pipeline

+to parallel
