### ISSUE TITLE
Error in InvokeRestAPIV1: No endpoint found with identifier TaskInputs[TaskInputs['connectedServiceNameSelector']]

### ISSUE THREAD

**Issue by laurentchicoine** [Microsoft/azure-pipelines-tasks#7891]
## Troubleshooting
No debug log other than: No endpoint found with identifier TaskInputs[TaskInputs['connectedServiceNameSelector']]

## Environment
- Server - VSTS or TFS on-premises? TFS on-premise
    
    - If using TFS on-premises, provide the version: Version 16.122.27409.2

- Agent - Hosted or Private: 
    
    - Agentless

## Issue Description

Task name: Invoke REST API: GET (V1 Patch 3)

When trying to issue a get call using a Generic endpoint with a URL suffix no REST call is being done and the task fails with a variable error. No endpoint found with identifier TaskInputs[TaskInputs['connectedServiceNameSelector']]

The task also fails with an error when using the Patch 2 of the task. This time the error is different:
Variable with name urlSuffix could not be found for the given endpoint.

I tried with different endpoints and different values in the suffix without any success.

### Error logs

On Patch 3:
No endpoint found with identifier TaskInputs[TaskInputs['connectedServiceNameSelector']]

On Patch 2:
Variable with name urlSuffix could not be found for the given endpoint.

**Comment by laurentchicoine** [comment]
Hi @bansalaseem , 

We tried the Patch 2 (https://github.com/Microsoft/vsts-tasks/blob/releases/m137/Tasks/InvokeRestApiV1/task.json) which is the same as Patch 1 other than labels and helpMarkDown.

However Patch 2 has the following error everytime the task is runned (whether the URL suffix is provided or not):
Variable with name urlSuffix could not be found for the given endpoint.

Let me know if you prefer that I open a different issue for this.

**Comment by dhashrath-msft** [comment]
Hi @laurentchicoine In case of 16.122.27409.2 TFS server, it does not have the support for url suffix and the latest task version does not work with old server.

**Comment by bansalaseem** [comment]
I am closing this issue as per the above discussion
