### ISSUE TITLE
[DotNetCoreCLIV2] Add Global tool installer

### ISSUE THREAD

**Issue by shep1987** [microsoft/azure-pipelines-tasks#7908]
## Environment
- Server - VSTS

- Agent - Private: 
    2016 - 2.136.1

Would be nice to be able to install/update a Global tool from VSTS Packages, I currently am creating a nuget.config file during release then doing the upgrade, having a similar experience to "restore" would be great as I could choose the package location.

Thanks

Shaun

**Comment by ds-ms** [comment]
Seems like an enhancement related to Packaging to me. 
@azooinmyluggage @keithrob can you respond?

**Comment by aasim** [comment]
Hi - Can you provide us with more information regarding this issue? We have released newer tasks since 2018 which might be able to help you with this. Let me know your requirements and reopen this issue, and we can work on a resolution for you.

Aasim
