### ISSUE TITLE
FTP Task randomly failing with "socket hang up"

### ISSUE THREAD

**Issue by courtenayparserr** [Microsoft/azure-pipelines-tasks#7927]
Just doing a basic FTP upoad as a build task which simply will not work - it just hangs without any idea of what is going on. There is no output and no idea of any errors.

We just need to do a copy and drop to a particular folder on a Azure web app.

## Environment
VSTS online

![image](https://user-images.githubusercontent.com/24819057/43683261-30b15a5c-98cb-11e8-9506-1d0396ceff3b.png)

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

## Issue Description

More info:

![image](https://user-images.githubusercontent.com/24819057/43683230-ecc8e9b8-98ca-11e8-8222-69fe70d2a270.png)

### Error logs

[Insert error from the logs here]

**Comment by bryanmacfarlane** [comment]
@madhurig - just a guess - maybe an error path is missing a callback and the process hangs?

**Comment by yacaovsnc** [comment]
@courtenayparserr Does it repro?  Could you please set `system.debug` to true and run it again?  If it repros, can you please send us the log?  Also can you please let me know what is the log error in your screenshot?  What did lstat complain about and what is the full path of the file?

Thanks.

**Comment by courtenayparserr** [comment]
The full error log is: 
Unhandled: Failed find: EINVAL: invalid argument, lstat 'C:\ProgramData\docker\windowsfilter\0745941af06d37d16d46379496af5828a25cdcfba158390415f158bcea610a8a\Files\Boot'

With the system.debug to true it does this for ages:

![image](https://user-images.githubusercontent.com/24819057/44029553-0db8196a-9f41-11e8-8ac0-6164dc4f0535.png)

This may help too:
![image](https://user-images.githubusercontent.com/24819057/44029628-4eb008d8-9f41-11e8-92c4-b621fbe2bb88.png)

cc @yacaovsnc @bryanmacfarlane

**Comment by courtenayparserr** [comment]
[log_6_855.zip](https://github.com/Microsoft/vsts-tasks/files/2282907/log_6_855.zip)

Logs attached

**Comment by courtenayparserr** [comment]
Any thoughts here @yacaovsnc ?

**Comment by yacaovsnc** [comment]
This seems like a http error now.  Could you please let me know which agent are you using?  Is it a hosted pool?  You can find this information from the "Process" step, it should show you which pool you are using.

Is this failing all the time?  Does it repro if you use a different pool?

**Comment by courtenayparserr** [comment]
Doesnt seem to matter? They all fail:

![image](https://user-images.githubusercontent.com/24819057/44237979-0738f480-a1f6-11e8-8127-ae3bcee53dbd.png)

**Comment by courtenayparserr** [comment]
Any thoughts @yacaovsnc ?

**Comment by yacaovsnc** [comment]
@courtenayparserr Not really, nothing comes to mind immediately.  However if it fails randomly with all pools, then it doesn't look like a client side issue.  When does it usually fail?  Like completely random or after uploading for a while?  If it's after a while, maybe we can break up the uploading into multiple uploading tasks and each task only uploads a subset of the files (like a folder)?  Also the curlUpload task can also upload to ftp site, maybe you can also give that task a try?

**Comment by madhurig** [comment]
Closing the old thread since there are no updates. Please try the curlUpload task and see if it helps.

**Comment by ramseyjacob** [comment]
I'm getting this today on Hosted Ubuntu 1604 host...a lot
