### ISSUE TITLE
Install an Apple Certificate fails with ECONNREFUSED

### ISSUE THREAD

**Issue by dalemyers** [Microsoft/azure-pipelines-tasks#7951]
## Environment

Server: VSTS
Account: office
Definition ID: 2539
Build Number: 885894

Agent: Hosted
Queue: Hosted Mac Internal

## Issue Description

The pre-job step of "install an apple certificate" randomly fails with an error like:

    Error: connect ECONNREFUSED 13.107.6.175:443

I've been unable to get it to reproduce with `system.debug` enabled since this only fails one in a few hundred times (but thats enough for us to see it regularly). 

Since this is hosted I can't get any further logs.

**Comment by dalemyers** [comment]
Bumping this. We are seeing this sort of error pretty frequently. (Around 1 in 100 builds)

Is there anything we can do to mitigate this before a fix is made?

**Comment by madhurig** [comment]
@dalemyers - sorry for the delay. Can you send us the logs (doesn't have to be debug)? If you don't want to upload them here, please email them to me at madhurig at microsoft dot com.

Thanks,
Madhuri

**Comment by dalemyers** [comment]
This one is proving to be difficult to find again... There isn't a way I'm aware of to search all logs easily, so I'm just having to wait until I see it.

**Comment by madhurig** [comment]
@dalemyers - ok please send us logs when you see it next time. Seems like an Mac infrastructure issue, so will loop in the Hosted macOS team.

**Comment by madhurig** [comment]
Closing after following up with @dalemyers offline since the issue hasn't been seen recently and we have no logs.
