### ISSUE TITLE
Nuget Installer : custom download location

### ISSUE THREAD

**Issue by Styxxy** [microsoft/azure-pipelines-tasks#7984]
## Environment
- Server - TFS on-premise
    - If using TFS on-premises, provide the version: 2018 update 2

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016, agent version vsts-agent-win-x64-2.138.2

## Issue Description
When adding the task Nuget Installer to install nuget 4.3.0 (or even 4.7.0), the task will always try to download from dist.nuget.org. Our agent however is not allowed to connect to the internet. We would like to provide a custom (internal) endpoint where we can host this distribution feed.

![nuget-installer](https://user-images.githubusercontent.com/1635825/43884122-8862a610-9bb5-11e8-9c0a-3598fed7ec85.png)

**Comment by jotaylo** [comment]
If more users request this feature (see [UserVoice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services?category_id=145266)) it'll make its way up the triage stack, but in the meantime you're welcome to contribute the change yourself. 
https://github.com/Microsoft/vsts-tasks/blob/7caffeb95e6dff07406ca1744a4601ca345ba7e5/Tasks/Common/nuget-task-common/NuGetToolGetter.ts#L131
