### ISSUE TITLE
Nuget package restore error for UWP project in a VSTS build definition

### ISSUE THREAD

**Issue by Gold14388** [Microsoft/azure-pipelines-tasks#8014]
## Issue Description
I get below error for my VSTS build definition. I have attached the logs zipped file.

_C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): Error : The package Esri.ArcGISRuntime.UWP with version 100.0.0 could not be found in C:\Users\username\.nuget\packages\. Run a NuGet package restore to download the package._

### Error logs

[Insert error from the lo
[logs_418.zip](https://github.com/Microsoft/vsts-tasks/files/2279217/logs_418.zip)
gs here]

**Comment by jahquin-msft** [comment]
I went through the logs and all the NuGet restore tasks succeeded and none of them attempted to download the Esri.ArcGISRuntime.UWP package. Could you please confirm this package is listed as a dependency in the relevant project or package.config. You might be able to get it to work locally due to a cached package.

**Comment by Gold14388** [comment]
{
  "dependencies": {
    "Esri.ArcGISRuntime.Xamarin.Forms": "100.0.0",
    "Jint": "2.11.58",
    "Messier16.Forms.Checkbox": "0.2.1-alpha",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Newtonsoft.Json": "9.0.1",
    "pclstorage": "1.0.2",
    "SharpGIS.NmeaParser": "1.9.0",
    "sqlite-net-pcl": "1.2.0",
    "Toasts.Forms.Plugin": "3.2.0",
    "Xam.Plugin.Connectivity": "2.3.0.37-beta",
    "Xam.Plugin.Geolocator": "3.0.4",
    "Xam.Plugin.Media": "2.6.0.4-beta",
    "Xam.Plugins.VideoPlayer": "1.0.0-pre07",
    "Xamarin.Forms": "2.3.4.270",
    "Xamarin.Forms.DataGrid": "1.3.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

This is what packages.json looks like for the project

**Comment by Gold14388** [comment]
and the path in the error message "C:\Users\username\.nuget\packages".. I am getting confused about this path. Where exactly the build is trying to look this path into?

**Comment by alexmullans** [comment]
Closing this issue for now due to age. If it's still occuring, make sure you're using a NuGet Tool Installer step at the beginning of your build to use a recent version of NuGet (e.g. 4.9.2).
