### ISSUE TITLE
Nuget restore : temp nuget config file doesn't respect relative paths

### ISSUE THREAD

**Issue by Styxxy** [microsoft/azure-pipelines-tasks#8026]
## Environment
- Server - TFS on-premise
    - If using TFS on-premises, provide the version: 2018 update 2

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016, agent version vsts-agent-win-x64-2.138.2

## Issue Description
When adding the Nuget restore task, and specifying a nuget.config file with the feeds to use. This task will copy the nuget.config file to its own temp folder. However, when the (original) nuget.config file contains relative paths (eg. //config/repositoryPath, feeds, ...) they will be taken as is. The relative paths are not corrected for the new location (or made absolute).

Example nuget.config file:

```xml
<?xml version="1.0"?>
<configuration>

  <config>
    <add key="repositoryPath" value="..\..\packages" />
    <add key="globalPackagesFolder" value="..\..\packages" />
  </config>

  <packageSources>
    <add key="Local source" value="..\..\lib-packages" />
  </packageSources>

</configuration>
```

Example build (in this case task group):

![nuget-restore-task](https://user-images.githubusercontent.com/1635825/44078556-0f16462c-9fa7-11e8-9c10-ecbbb9e3ce8c.png)

**Comment by Styxxy** [comment]
See also #7505 , where I also created a work-around.

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!

Adding an additional note - it looks like there's a workaround in #7505 , so hopefully no one is hard blocked by this.
