### ISSUE TITLE
VSTS build solution error for renewing certificate (.pfx) file

### ISSUE THREAD

**Issue by Gold14388** [Microsoft/azure-pipelines-tasks#8034]
## Environment
VSTS details
    AccountName: 
    Team project name: 
    Build Definition Name:
Build Number: 
    Private Agent: Windows Server 2012 R2

## Issue Description
Build Solution task in VSTS
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(4216,5): error APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478
Note: I did create a new certificate using visual studio 2017 and pushed new certificate to the remote repo and that helped me in getting rid of the same error I was getting in a powershell task to import certificate. The error is coming from UWP project.
### Error logs
logs_487.zip](https://github.com/Microsoft/vsts-tasks/files/2288060/logs_487.zip)

**Comment by azureDaveOps** [comment]
This is an msbuild warning, the build app behaved properly by reporting it.  Is this issue only happening in AzureDevOps or does it also happen when you build locally?  If it is specific to pipelines please reopen.
