### ISSUE TITLE
Nuget build task that pushes to MyGet started failing with a 401

### ISSUE THREAD

**Issue by samuelbcollie** [microsoft/azure-pipelines-tasks#8044]
## Environment
VSTS
Hosted Agent
Agent Queue Name: Hosted VS2017

## Issue Description

At the end of our build we have a nuget push task that pushes packages to MyGet. This task started failing today despite working as recently as yesterday. I'm assuming this is an issue with our Service Definition for MyGet. 

We used "Update Authentication for My MyGet feed (push)" at the bottom of this tutorial for configuring our Service Definition:
https://docs.myget.org/docs/reference/vsts-integration#Let_MyGet_Build_Services_create_and_host_packages_from_your_VSTS_git_repository

## What we've tried so far:
- Re-creating the service definition
- Setting up a new personal access token for MyGet
- We have tried pushing from our local computer (which works)

### Error logs

The nuget command failed with exit code(1) and error(System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://www.myget.org/F/{our feed name}/api/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

**Comment by jotaylo** [comment]
Which version of the nuget push task did you see this in? Was the previous successful push a different version of the task?

**Comment by samuelbcollie** [comment]
The previous successful push used 2.0.32 based off the logs. Unfortunately, I no longer have the logs for the failed build, so I can't check the minor version there (I didn't realize our retention policy was more strict for failed builds). The last push succeeded on August 14th, and the first fail was August 15th.

**Comment by jotaylo** [comment]
I'm not sure which region your account is in, but 2.0.33 was rolled out around August 15th, so it may be related to the update, although we haven't had any other reports of issues publishing to MyGet.

Can you please do a build with system.debug set to true and email me the nuget publish log at jotaylo@microsoft.com. Feel free to anonymize any data in it.

**Comment by samuelbcollie** [comment]
Done. Let me know if you need any other information.

**Comment by alexmullans** [comment]
@samuelbcollie is this working again?

**Comment by elbatk** [comment]
Closing this as it looks like it's up and running now :)
