### ISSUE TITLE
[undefined]Waiting for console output...

### ISSUE THREAD

**Issue by sebastienlabine** [Microsoft/azure-pipelines-tasks#8077]
## Issue Description
It's a non-blocking issue, but while the console is waiting for the console output, it's showing the user an undefined message.
![image](https://user-images.githubusercontent.com/8888846/44360087-afb1b780-a487-11e8-9406-c7f5acdc471b.png)

### Error logs

[undefined]Waiting for console output...

**Comment by bryanmacfarlane** [comment]
Please use developer community for issues with the service (this is a web UI issue).  Meanwhile, I'm sending info to the web UI dev...
