### ISSUE TITLE
Artifacts associated by the Logging Command do not get deleted by build retention policy

### ISSUE THREAD

**Issue by iggyshu** [Microsoft/azure-pipelines-tasks#8089]
## Environment
- TFS on-premises 
   Version 15.117.27414.0
  
- Agent - Private
  Windows_NT 6.3.600, agent version 2.126

## Issue Description

Our current CI build is implemented using a .ps1 script and Invoke-Build tasks. After compiling the sources the following function is called for each artifact source to publish it:

```
Copy-Item $source -destination $target -recurse -container
Write-Output "##vso[artifact.associate type=filepath;artifactname=$name]$target"
```

The 1st line copies the binaries to the share. The 2nd line uses the [**Artifact Logging Command**](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) to associate it. This works fine. The artifacts are copied to the shared folder and are then visible in the Artifacts tab of the finished build.

**The problem:** the associated files do not get deleted by the build retention policy. When the retention policy is executed, the Artifacts are removed from their tab in the build, but are kept on the hard drive. As a result, the disk space is not freed as intended.

**Comment by iggyshu** [comment]
The issue seems to be caused by how TFS handles _$name_ and _$target_ parameters. I noticed that the retention policy was attempting to delete the artifacts from:

`$target\$name`

..location, which in our case resulted in e.g.:

`\\build_share\artifact_name\artifact_name`

I was able to overcome the problem by changing the original snippet to use the parent folder of the artifact:

```
Copy-Item $sourceFolder -destination $targetFolder -recurse -container
Write-Output "##vso[artifact.associate type=filepath;artifactname=$artifactName]$targetRootFolder"
```

**Comment by bryanmacfarlane** [comment]
Not an issue with a task in this repo (/tasks).  Please use developer community for service issues.
