### ISSUE TITLE
Hosted agent stuck in "Waiting for available machine" for 1 hour

### ISSUE THREAD

**Issue by allanmoller** [Microsoft/azure-pipelines-tasks#8108]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS - KKKIT 

- Agent - Hosted
Hosted VS2017
Release-180

## Issue Description
My release have been stuck in waiting for more then one hour even though i only have one que item!!

**Comment by bryanmacfarlane** [comment]
Not an issue with a task in this repo (what the issues are tracking).  Please use developer community.
