### ISSUE TITLE
VsTestv2 does not fail if it cannot find tests

### ISSUE THREAD

**Issue by bergmeister** [microsoft/azure-pipelines-tasks#8114]
VsTestv2 emits only one warning when no test assemblies were found:
```
##[warning]No results found to publish.
```

This leads to a green build/releease and therefore it is not easy to spot that tests are not being run any more by mistake (e.g. due to a rename of assemblies where the build/release definition was not updated accordingly).
The expectation of the task should be that there are test assemblies with matching tests to test for by default and otherwise fail.

N.B.: I am using VSTS, not TFS

**Comment by acesiddhu** [comment]
@bergmeister this is the current behavior today In tfs as well as vsts. We cant change the default beaviour to fail the task here, because there would be many customers who might have no matching test dlls in the path but would be using a test task (given that it is part of template). Adding @PBoraMSFT to get her prospective.

**Comment by bergmeister** [comment]
I think then there should either be an option for it or a breaking change be made in a major version bump.
In general I would also like to see options such as marking the build as orange (partially succeeded) if e.g. a test had to be re-run.

**Comment by PBoraMSFT** [comment]
Marking as enhancement.

**Comment by bergmeister** [comment]
@PBoraMSFT Which option (mark as `SucceededWithIssues`, i.e. orange if there are no test results or to provide a checkbox to make it red/fail) do you prefere
The code line where this enhancemenent would need to go is [here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestV2/vstest.ts#L650)

**Comment by ShreyasRmsft** [comment]
@bergmeister the part of the code that you are pointing to is soon going away. Making a change there is not a long term solution.

To be more verbose the non distributed flow of the vstest task will also start going via DtaExecutionHost.exe.

**Comment by bergmeister** [comment]
@ShreyasRmsft The code that I pointed to has not changed at all since June and has not changed since we spoke more than a month ago!
If you are open to pull requests then it would seem reasonable to me to add a checkbox to make the task fail optionally if no tests are being run. This is very important to find problems when doing refactoring. Can you please approve if you'd accept such a PR. I also would like to submit a PR that implements #8133, can you look at it as well please and comment

**Comment by ShreyasRmsft** [comment]
If you take a look at runvstest.ts there is a feature flag that controls whether the execution goes via vstest.ts or nondistributedtest.ts, this was turned on for stage0 last week and and last few problems with the new flow were ironed out. We will be turning on the FF very soon and once that happens vstest.ts will be deleted. 

@PBoraMSFT to decide whether we want to add support for this.

**Comment by bergmeister** [comment]
@ShreyasRmsft Thanks for the update. Does that mean I could already make PRs against `nondistributedtest.ts` or is there still heavy churn on the file?

**Comment by ShreyasRmsft** [comment]
We've added support to fail the task if the specified number of tests are not run.

Here are the release notes https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-161-update#set-vstest-tasks-to-fail-if-a-minimum-number-of-tests-are-not-run
