### ISSUE TITLE
npm tasks v 1.* 

### ISSUE THREAD

**Issue by dennismi** [microsoft/azure-pipelines-tasks#8131]
## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 15.117.26714.0
    
- Agent - Private: 
not agent specific

## Issue Description

I'm currently trying to make use of the builtin npm feed capabilities in our tfs 2017.2 (I know there is a .3). 
I have tried following the documentation but they are using v 1.* of the tasks, and I only have v 0.* available.

Is the v 1.* version available in tfs2017.3?

But since there is only version 0.* available to me, it makes it difficult to follow any instructions on docs.microsoft.com... 

I am only missing the last step, to get the build system to restore the packages from our own feed. I am getting 401's ... and the build system is running as a contributor to the feed. 
I even tried vsts-npm-auth, but that is also giving me an 401... (perhaps this is an issue with vsts vs. tfs)

What I am trying to come at, is there any way to get an updated (just v 1.*) version of the npm build tasks on my 2017.2? either through upgrading to 2017.3 (2018 is not an option yet, got a bunch of XAML builds i need rewrite) or just upgrading the npm build tasks?

**Comment by bryanmacfarlane** [comment]
You should be fine to install the npm v1 task on 2017.  It supports the 2.x agent and min version is low (use that)

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NpmV1/task.json#L21

Use tfx to upload.  You'll be fine when you upgrade the server later since it merges in the box and custom and then resolves.

**Comment by bryanmacfarlane** [comment]
Xaml 2018.2 and .3 can use xaml.  Must use 2015 controllers and agents.

https://blogs.msdn.microsoft.com/bharry/2017/05/30/evolving-tfsteam-services-build-automation-capabilities/

Probably a better more formal path.

**Comment by dennismi** [comment]
@bryanmacfarlane I'm trying to upload the v1 to our tfs... but when running `gulp package` I am getting the following error: 
`
> Creating NuGet package per task
> Creating task zips folder
> Creating artifacts folder
> Zipping task folders
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir 'F:\vsts-tasks-master\\_package\milestone-layout'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.createNugetPackagePerTask (F:\vsts-tasks-master\make-util.js:1277:8)
    at Function.target.package (F:\vsts-tasks-master\make.js:492:10)
    at Object.global.target.(anonymous function) [as package] (F:\vsts-tasks-master\node_modules\shelljs\make.js:28:26)
    at F:\vsts-tasks-master\node_modules\shelljs\make.js:38:27
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (F:\vsts-tasks-master\node_modules\shelljs\make.js:36:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
`

But i can figure out where to get the milestone-layout from?

**Comment by dennismi** [comment]
Damn i need to get some instructions on how to build those tasks

I have found the command for building it, but no package is produced. I am trying with:
`gulp package --task NpmV1`
it runs all tests, and finishes with skipping publish, because i have specified a task. Which is ok. 

But there isn't any vsix i an upload, and i can't even create an vsix with tfx extension create, because tfx needs a vss-extension.json or a similar file, but non of the *.json' in the task has the required structure to be used as manifest.

I'm just about giving up, and just about to upgrade to 2018.x ... I've spent a couple of days on this now... :(

**Comment by bryanmacfarlane** [comment]
From the front readme, the contribution link:  https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md

There's instructions on how to build a single task.

**Comment by dennismi** [comment]
I have found that, but it doesn't give any output i can use to upload to my TFS, tfx complains about missing an vss-extension.json, and none of the json files already there can be use, either alone or joined together with --manifests-globs *.json ...

**Comment by elbatk** [comment]
Hi @dennismi , it's been quite some time here, are you still having an issue?

**Comment by dennismi** [comment]
No, we have upgraded to 2018 since and there are no issues.
