### ISSUE TITLE
Unable to upload CopyFilesOverSSHV0 task to VSTS marketplace - The task.json file was not found in contribution

### ISSUE THREAD

**Issue by jo3yk** [microsoft/azure-pipelines-tasks#8132]
I have made some modifications to the SshV0 and CopyFilesOverSSHV0 tasks, and have been attempting to publish them as VSTS extensions to the marketplace for testing. The vss-extension.json for my modified CopyFiles task is as follows:

```
{
    "manifestVersion": 1,
    "id": "copy-files-ssh-host-credentials-task",
    "name": "Copy files over SSH task (with host and credentials)",
    "version": "0.0.1",
    "publisher": "JoKennedy",
    "targets": [
        {
            "id": "Microsoft.VisualStudio.Services"
        }
    ],    
    "description": "Copy files over SSH task with host and credentials.",
    "categories": [
        "Build and release"
    ],
    "icons": {
        "default": "CopyFilesOverSSHHostAndCredentials\\icon.png"        
    },
    "files": [
        {
            "path": "CopyFilesOverSSHHostAndCredentials"
        }
    ],
    "contributions": [
        {
            "id": "custom-build-release-task",
            "type": "ms.vss-distributed-task.task",
            "targets": [
                "ms.vss-distributed-task.tasks"
            ],
            "properties": {
                "name": "CopyFilesSSHHostAndCredentials"
            }
        }
    ]
}
```

My build/package process is as follows:
1. ```node make.js build --task <Task>```
1. Copy the vss-extension.json file into _build\Tasks
1. ```tfx extension create```

This works fine for the SshV0 task and I have been able to successfully use the task, but fails for CopyFilesOverSSHV0 - when uploading to the marketplace, validation fails with "The task.json file was not found in contribution".

Running tfx extension create with --trace-level debug shows that the task.json is found and added to the package. (Trace attached [trace.txt](https://github.com/Microsoft/vsts-tasks/files/2317714/trace.txt))

I have also attempted to publish the unmodified CopyFilesOverSSHV0 as it is on the current master branch, with the same problem.

Any assistance to resolve the issue would be appreciated.

**Comment by damccorm** [comment]
Hey @jo3yk are you still running into this issue? Sorry its sat for a while here - since this is more of a service issue and not a task specific issue, would you mind opening a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html? That will help it get triaged and seen by the right people
