### ISSUE TITLE
Help - Updating the manual test plan from the automation

### ISSUE THREAD

**Issue by maysamms** [Microsoft/azure-pipelines-tasks#8139]
Good afternoon,

I wonder if it is possible to perform the process below. I've tried it in many ways, but I still can not get any positive results. So I do not know if it's possible to do this or I really can not.

I've created a test automation project to run on build, with BDD.
I created the project and checked in on VSTS.
After that, I created the build and ran my test solution.
All the tests were run correctly and in the build result shows me how many tests passed and how many failed.

However, these my tests were built based on the test plan that already existed previously. So they are all related to an existing test case in VSTS. I made the automation link with the test case, but when I run the test on the build it does nothing with this link information.

I wonder if it is possible, when I run the build with the tests, can you make the test plan update with the result of the Build execution?

For example:
Test case ID: 1 is automated and if I check it there is the automation link with it. When I run automation and the test passes, test case 1 will be updated to passed. When I access the test plan, it will be possible to see that the test has passed, and it is not necessary to verify the result of the build. It will already be up to date.

Is it possible or really I can not?

Information:
VSTS;
Private build agent on an azure machine.
Tests being run by task vsTest.

**Comment by abhishkk** [comment]
@maysamms 
You need to run on-demand test run for achieving this.
Please follow [this](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=vsts#run-the-automated-tests) link for more details.
