### ISSUE TITLE
Enable to specify ExcludePatterns for solutions in VS build task and MSBuild task

### ISSUE THREAD

**Issue by lvsezhufu** [microsoft/azure-pipelines-tasks#8144]
For now, what we can specified solutions in VS build task (same for MSBuild task) **Solution** option is only for the `IncludePatterns`.

![image](https://user-images.githubusercontent.com/23092306/44614397-75b12e80-a856-11e8-89cb-1d75c8109ce0.png)

And it seems `ExcludePatterns` is defined for VS Build task, but there has no entries for users to use it.

![image](https://user-images.githubusercontent.com/23092306/44614422-d3457b00-a856-11e8-992d-f8f3ef1f2c25.png)

Is it possible to open the entry to specify` ExcludePatterns` for VS build task and MSBuild task in the web page? And it will be quite benefit for the situations when there has amount of solutions files need to build, but only a few solutions need to be excluded.

**Comment by riyadshauk** [comment]
I would also still like to know how to accomplish this.
