### ISSUE TITLE
Add support for the Project2ProjectTimeOut nuget.exe parameter on the NuGet task

### ISSUE THREAD

**Issue by alexmarshall132** [microsoft/azure-pipelines-tasks#8197]
## Issue Description

The NuGet task should have an option to specify the Project2ProjectTimeOut parameter in order to reduce restore times.

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
