### ISSUE TITLE
Jenkins Download Artifacts downloading artifacts from wrong jenkins job

### ISSUE THREAD

**Issue by daantimmer** [Microsoft/azure-pipelines-tasks#8201]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
- Not required

## Environment
- Server - VSTS or TFS on-premises?
Microsoft Visual Studio Team Foundation Server
Version 16.122.27102.1

- Agent - Hosted or Private: 
N/A

## Issue Description
The "Jenkins Download Artifacts" step can only download a specific build number or "the latest succesful" Artifacts. This might result in invalid artifacts for the wrong build.

Situation: One generic Jenkins-job, accepting a repository and branch parameter. A single TFS Build allowing concurrent builds.
If build-1 and build-2 start, where build-1 will queue a jenkinsjob-1 and build-2 will queue a jenkinsjob-2.
build-1 will always download jenkinsjob-2 if jenkinsjob-2 finishes before jenkinsjob-1 finishes.
This results in invalid artifacts ending up in build-1.

### Error logs
N/A

**Comment by kasubram** [comment]
@daantimmer 
LastSuccessfulBuild option in the  Jenkins Download Artifacts task basically mimics the Jenkins latestsuccessfull remote api behaviour.

This would always fetch the latest build from the job.
http://{host}/job/{jobname}/lastSuccessfulBuild/api/json

Can you tell us bit more about how you usage? Are you using queue Jenkins job task to trigger a Jenkins build? After queuing the Jenkins job how are you waiting and getting notified that build is complete? and after downloading the Jenkins artifact from Jenkins job do you deploy the bits to somewhere?

**Comment by daantimmer** [comment]
@kasubram sure I can.
We have multiple TFS projects, each with their own build definitions. In order to reduce "code" duplication I've created a single TFS Job to do "generic things". (In this specific case it is a Jenkins Pipeline Job that uses the Jenkinsfile inside a repository to do job-specific things). (For example, I have a pull-request build and on-push build)

In order to scale with the amount of projects this job can be run concurrently because they don't depend on other jobs or make use of shared resources.

When TFS schedules two builds that both use the same jenkins job issues might occur:
- Build-Product-Foo, schedules Generic-Jenkins-Job, runs for 5 minutes.
- Build-Product-Bar, schedules Generic-Jenkins-Job, runs for 10 minutes.

If Build-Product-Bar is started first and Build-product-Foo is started second like:

18:00:00 - start Build-Product-Bar (runs for 10 minutes)
18:00:01 - start Build-Product-Foo (runs for 5 minutes)
18:05:01 - end of Build-Product-Foo. Will then "download jenkins artifacts correctly" (downloads build-product-foo artifacts)
18:10:01 - end of Build-Product-Bar. Will then "download jenkins artifacts in-correctly" (also! downloads build-product-foo artifacts)

This will mean that users investigating the build results for Build-product-Bar will investigate the wrong results.

**Comment by kasubram** [comment]
@daantimmer queue Jenkins job task publishes a output variable "JENKINS_JOB_ID". It fetches the current job queued and emits the job id in this variable. In the download task Instead of choosing latest option can you choose specific build and in the input if you mention $(JENKINS_JOB_ID) it should download the artifact from the job that was trigger by the previous Jenkins queue task.

**Comment by daantimmer** [comment]
@kasubram really? I have to check that out! I can't seem to find it in the documentation.

**Comment by daantimmer** [comment]
@kasubram I don't think $(JENKINS_JOB_ID) is being set on my instance. I am getting a NaN value instead?

**Comment by kasubram** [comment]
@daantimmer if you use $(JENKINSQUEUEJOB2_JENKINS_JOB_ID) it will work directly. You don't need the powershell script.

@kelliejos Jenkins queue task's output variable section lists JENKINS_JOB_ID being available as one of the output variable. But looks like task name needs to be prefixed with the variables name. Is that expected?

**Comment by kasubram** [comment]
Here is the output varible section.
![image](https://user-images.githubusercontent.com/17177298/47234731-5c5ed580-d3f4-11e8-9ba7-94b531c379bc.png)

**Comment by GitHubSriramB** [comment]
@daantimmer - closing this issue assuming it will get resolved with the answer given above. Pl. reactivate in case this is not resolved yet.

**Comment by anwell** [comment]
I needed to use $(JENKINSQUEUEJOB.JENKINS_JOB_ID) to get this to work from the pipeline GUI (corresponds to environment variable $JENKINSQUEUEJOB_JENKINS_JOB_ID

**Comment by kasubram** [comment]
@anwell thats a correct behaviour. All the task output variables are namespaced. The default namespace is the task name but you can decide a prefix by changing the "Reference Name" input field in the task. If you say "test" for ref name, then you will be accessing the variables as $(TEST.JENKINS_JOB_ID)

More detail is here https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md
