### ISSUE TITLE
Azure App Service Deploy: 'App Service Type' not bindable within Task Group

### ISSUE THREAD

**Issue by tjgalama** [Microsoft/azure-pipelines-tasks#8212]
When using an Azure App Service Deploy **V3** within a Task group, it is possible to bind the field to the task group's input parameter 
![azureappservicedepolyv3](https://user-images.githubusercontent.com/504789/44899299-ac2cf480-ad01-11e8-8604-929a648c6e44.png)

When switching to Version **V4** (currently preview), it is no longer possible to bind the field to an input parameter of the task group.
![azureappservicedepolyv4](https://user-images.githubusercontent.com/504789/44899301-ad5e2180-ad01-11e8-867f-cdf6b00d4548.png)

As a workaround, switching to V4 (preview) enforces us to clone our current (Deploy) Task Groups per 'App Service Type' which increases the number of task groups we have to maintain. 

(this is situated in VSTS)

**Comment by tjgalama** [comment]
We currently have a mixture of WebApi's (Windows) and Functions Apps to which we want to deploy. Both use the same sub input parameter (more or less). Some of them are deployed via a slot (+ swap) other apps are directly deployed to the production (slot). This currently results in two task-group's (deploy with/without slots).

**Comment by vincentdass** [comment]
We are in process of breaking down the single task into Multiple task based on the app type. 
So, closing this issue.
