### ISSUE TITLE
Response status code does not indicate success :401(Unauthorized) using private nuget package in Docker

### ISSUE THREAD

**Issue by venmaram** [microsoft/azure-pipelines-tasks#8214]
**Unable to load the service index for source Private Nuget URL**
<img width="965" alt="error" src="https://user-images.githubusercontent.com/42862255/44903964-d2ed2a00-ad05-11e8-858b-13d2f9444565.png">

**Docker File **
`FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
EXPOSE 80

`# Copy csproj and restore as distinct layers`
COPY *.csproj ./
`#COPY Nuget.config  Nuget.config ./`
`#RUN dotnet restore --configfile Nuget.config`
RUN dotnet restore

`# Copy everything else and build`
COPY . /app
COPY . ./
RUN dotnet publish -c Release -o out

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Vivalkemy.Microservices.DevProfileService.dll"]
`

**Nuget.config**

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="ViewDataModel" value="..../DataModel/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <BL>
      <add key="Username" value="test" />
      <add key="ClearTextPassword" value="test123" />
    </BL>
  </packageSourceCredentials >
  <activePackageSource>
    <add key="NuGet official package source" value="https://nuget.org/api/v3/" />
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <disabledPackageSources />

  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="True" />
  </packageManagement>
  
</configuration>
```

**Comment by bansalaseem** [comment]
Can you please share in which task you are running into this issue?

**Comment by venmaram** [comment]
Hi bansalaseem ,
Thanks for the reply. Please have a look below image I am using these Tasks 

![image](https://user-images.githubusercontent.com/42862255/44976935-923c1d80-af5e-11e8-8441-a94c602e5560.png)

**Comment by bansalaseem** [comment]
@venmaram, The task which fails is nuget restore?

**Comment by venmaram** [comment]
Fails on Build Image, rest all tasks are no issue

**Comment by bansalaseem** [comment]
Apologies for missing this issue. @venmaram Can you please share whether you are still running into this issue or not?

**Comment by bansalaseem** [comment]
Please open it if you still are running into this issue.
