### ISSUE TITLE
Space in arguments

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/azure-pipelines-tasks#8238]
Given a file path (for -f command), if it has a space in it, docker compose (and presumably other tasks) will not append quotes to handle them propertly.

It's not the first time something similar had happened to me. I opened this bug one year ago: https://github.com/Microsoft/vsts-agent/issues/1091 and now it's propertly handled by the agent's installer. But now I just encounter it while setting up CD for a customer in which the project have a space in the name.

Let's see how it's handled by compose:
`2018-09-03T18:10:51.3409613Z [command]/usr/local/bin/docker-compose -f /home/username/myagent/_work/r1/a/_My Project-Docker container-CI/drop/devinfrastructure.yaml -f /home/username/myagent/.docker-compose.1535998251324.yml -p My Project pull
`

As you can see argumnets are broken by the lack of quotes. It was easy to fix in the -p parameter, by using quotes in the template, like so: `"$(Build.Repository.Name)"`

But it's all over the place AFAIK, ie, other arguments.

I think most of the tasks may be affected by this, for which I have 3 ideas:

1. Make sure,one by one, that all tasks get this right by appending quotes or other mechanisms to allow spaces.
2. Open an issue in VSTS, to actually disallow the use of spaces in Project's name.
3. All the variables that comes from VSTS, like $(Build.Repository.Name), gets quotes appended. (Not good and might break stuff).

I understand this is a very mundane issue, but it's not the first time I encounter spaces in project's names. And they always bring throubles. 

If you guys think that this should be resolved by vsts team, then this issue can be closed inmediately and i will open it in the respective tracker.

Cheers

**Comment by vithati** [comment]
@andreujuanc , In linux agent, quotes are not visible in logs if command argument contains spaces, but command will work fine. If you try same in windows agent it will show quotes around the project name.  There is already bug opened to address this issue in vsts-task-lib area https://github.com/Microsoft/vsts-task-lib/issues/383. If you see any with spaces in arguments please reopen the issue.

**Comment by andreujuanc** [comment]
Hello @vithati this is clearly not the way it works, since my project was failing and I fixed it by removing the white space from my project name. 

How is that fix possible if "command will work fine". 

It's not a matter of showing the quotes or not, but actually passing them to the commands.

**Comment by vithati** [comment]
Hi @andreujuanc , i have tried docker compose command with project name having spaces. I didn't see any failure while task execution. I have tried docker compose build and pull commands. ([command]/usr/bin/docker-compose -f /home/tvikrantht-pc/vstsagent/_work/2/s/docker-compose.yml -f /home/tvikrantht-pc/vstsagent/.docker-compose.1537274313492.yml -p My Team Project build , [command]/usr/bin/docker-compose -f /home/tvikrantht-pc/vstsagent/_work/2/s/docker-compose.yml -f /home/tvikrantht-pc/vstsagent/.docker-compose.1537274313492.yml -p My Team Project pull).  Can you share debug logs of failed task?

**Comment by vithati** [comment]
Hi @andreujuanc, i have tried docker-compose command with project name having spaces. I didn't see any issues. I have tried docker-compose build and pull (My task log has [command]/usr/bin/docker-compose -f /home/my-pc/vstsagent/_work/r5/a/_My Team Project/docker-compose.yml -f /home/my-pc/vstsagent/.docker-compose.1537430883464.yml -p My Team Project build, [command]/usr/bin/docker-compose -f /home/my-pc/vstsagent/_work/r5/a/_My Team Project/docker-compose.yml -f /home/my-pc/vstsagent/.docker-compose.1537430883464.yml -p My Team Project pull). Can you share your task debug logs?

**Comment by andreujuanc** [comment]
I will try to repro ASAP. Probably this weekend. 
Got some issues this week and schedule is full. 
Will report as soon as I get the logs.

Thanks for the follow up.

**Comment by bansalaseem** [comment]
@andreujuanc, Do you have an update?

**Comment by bansalaseem** [comment]
Closing this issue because of no update.

**Comment by andreujuanc** [comment]
Sorry I havent had the change to test. Been super busy.
