### ISSUE TITLE
Failed to setup Tempkeychain  

### ISSUE THREAD

**Issue by sure17490** [Microsoft/azure-pipelines-tasks#8245]
Trying to use a temp keychain for signing
its failing below is the out put 

/Users/dev/Downloads/VSTS-2.134/_work/15/s/_iparesigntasktmp.keychain

/usr/bin/security import /Users/dev/Downloads/VSTS-2.134/_work/15/s/TechAppCertificatePK.p12 -P M0bility -A -t cert -f pkcs12 -k /Users/dev/Downloads/VSTS-2.134/_work/15/s/_iparesigntasktmp.keychain
2 identities imported.

rc:0

success:true

which 'security'

found: '/usr/bin/security'

which 'security'

found: '/usr/bin/security'

which '/usr/bin/security'

found: '/usr/bin/security'

which '/usr/bin/security'

found: '/usr/bin/security'

/usr/bin/security arg: ["list-keychain","-d","user"]

exec tool: /usr/bin/security

arguments:

list-keychain

-d

user

/usr/bin/security list-keychain -d user
    "/Library/Keychains/System.keychain"

rc:0

success:true

listAllOutput = "/Library/Keychains/System.keychain"

HOME=/Users/dev

Absolute path for pathSegments: /Users/dev,Library,Keychains,login.keychain = /Users/dev/Library/Keychains/login.keychain

which 'security'

found: '/usr/bin/security'

which 'security'

found: '/usr/bin/security'

which '/usr/bin/security'

found: '/usr/bin/security'

which '/usr/bin/security'

found: '/usr/bin/security'

/usr/bin/security arg: ["list-keychain","-d","user","-s","/Users/dev/Downloads/VSTS-2.134/_work/15/s/_iparesigntasktmp.keychain"]

/usr/bin/security arg: /Library/Keychains/System.keychain

/usr/bin/security arg: /Users/dev/Library/Keychains/login.keychain

exec tool: /usr/bin/security

arguments:

list-keychain

-d

user

-s

/Users/dev/Downloads/VSTS-2.134/_work/15/s/_iparesigntasktmp.keychain

/Library/Keychains/System.keychain

/Users/dev/Library/Keychains/login.keychain

/usr/bin/security list-keychain -d user -s /Users/dev/Downloads/VSTS-2.134/_work/15/s/_iparesigntasktmp.keychain /Library/Keychains/System.keychain /Users/dev/Library/Keychains/login.keychain

rc:0

success:true

which 'security'

found: '/usr/bin/security'

which 'security'

found: '/usr/bin/security'

which '/usr/bin/security'

found: '/usr/bin/security'

which '/usr/bin/security'

found: '/usr/bin/security'

/usr/bin/security arg: ["list-keychain","-d","user"]

exec tool: /usr/bin/security

arguments:

list-keychain

-d

user

/usr/bin/security list-keychain -d user
    "/Library/Keychains/System.keychain"

rc:0

success:true

Can\'t find loc string for key: TempKeychainSetupFailed

Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: TempKeychainSetupFailed

task result: Failed

TempKeychainSetupFailed

Processed: ##vso[task.issue type=error;]TempKeychainSetupFailed

Processed: ##vso[task.complete result=Failed;]TempKeychainSetupFailed

******************************************************************************

Finishing: Resign ipa file

**Comment by madhurig** [comment]
@sure17490 - sorry for the delay. Are you still facing this issue? Please provide more details
- Are you using Azure DevOps Service (previously VSTS) or TFS on-prem?
- Are you using Hosted VMs (which one?) or a self hosted agent?
- What task are you using? Based on the log snipped, you are using "Resign ipa file" which is not a task we ship in the box. Is it from the "Apple AppStore Extension"?

Thanks,
Madhuri

**Comment by madhurig** [comment]
Closing since this does not seem to be a task we ship in the box. If this is an issue with a task in the App Store extension, please open an issue here: https://github.com/Microsoft/app-store-vsts-extension/issues. It will be better to use the "Install Apple Certificate" task to install the cert and run a script to resign the IPA.
