### ISSUE TITLE
VsTest - How to get fully qualified test names

### ISSUE THREAD

**Issue by phatcher** [microsoft/azure-pipelines-tasks#8250]
I have a standard set of tests for each entity e.g. Add/Create etc, which means if something fails VSTS just tells me that I have a failed test "Add", which is not ideal when it could be one of 150 other Add tests.

According to [#1732](https://github.com/Microsoft/vstest/issues/1732) I can get fully qualified name by passing some additional parameters to the task e.g.` /ListFullyQualifiedTests /ListTestsTargetPath:abc.txt` but the task won't let me do this unless I supply a testsettings file which I don't normally use.

I'm also not sure if this is affected by the fact I'm using the NUnit3TestAdapter to make the NUnit tests available.

**Comment by karanjitsingh** [comment]
@phatcher, The options `/ListFullyQualifiedTests /ListTestsTargetPath:abc.txt` are only for discovery and not execution. i.e. it will only list the tests available and not execute them. While the console logs may not give enough information, the tests are grouped under their class names in the test window. That will help you nail down which test method is actually failing.

**Comment by navin22** [comment]
@phatcher this doesn't belong in this repo. Hence I am closing it. 
And it's already tracked here: https://github.com/Microsoft/vstest/issues/1732
