### ISSUE TITLE
Deprecated parameter in Service Fabric release definition

### ISSUE THREAD

**Issue by WhitWaldo** [Microsoft/azure-pipelines-tasks#8255]
## Environment
VSTS

- Agent - Hosted or Private: 
Private

## Issue Description

Built-in release definition for Service Fabric has deprecated argument. I received a warning that "ReplicaQuorumTimeoutSec is deprecated - use UpgradeReplicaSetCheckTimeoutSec". Both parameters are available in the task, but if the former is deprecated, it ideally shouldn't show up in the list of properties to set.

**Comment by amaljg** [comment]
@WhitWaldo - Thanks for the feedback. We'll address this issue in the next version of the task. Adding @kuvinodms to take care of this.
