### ISSUE TITLE
Release - Download Artifact - Asking for a local issuer certificate

### ISSUE THREAD

**Issue by HCRSalaun** [Microsoft/azure-pipelines-tasks#8285]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS
     
https://lorealanalytics.visualstudio.com
account : hugo.salaun@loreal.com
Build 25

- Agent - Private: 
OS of the machine running the agent : Window Server 2012 R2 with web proxy configured
Agent Version : 2.14 with proxy settings configured during the installation
## Issue Description

During my Release, the step "Download Artifact" failed and asks a local issuer certificate.
### Task logs

[ReleaseLogs_13.zip](https://github.com/Microsoft/vsts-tasks/files/2370420/ReleaseLogs_13.zip)

### Error logs

Failed in getBuild with error: Error: unable to get local issuer certificate
Error: unable to get local issuer certificate

**Comment by omeshp** [comment]
Have you installed the certificates used by your proxy on the agent machine?

**Comment by HCRSalaun** [comment]
Hi, 

I asked administrators of the agent machine but they never heard anything about certificates. 

For example, to allow the machine access to Internet, they just modified the "LAN settings" from IE internet Options, mentioning the proxy Server. 

Sorry, I'm really not an expert concerning Proxy configuration...
I'm really surprised because during my Build phase, I'm able to generate and move files from a folder to another, and, if I understand, "Download Artifact" step does the same kind of operation.  Why should we need such things like certificates? 

I will try to contact security administrators, to confirm the potencial existency of certificates. 

Couldn't it be a different issue regardless the error message ? 

Thank you for your help and your reactivity. :)

**Comment by omeshp** [comment]
Are you able to browse https based sites from agent machine without any security warning? The download is failing because proxy is decrypting https traffic and it's not secure to download without verified https connection.

**Comment by HCRSalaun** [comment]
I tried with these URLs from the agent machine : 

https://www.google.com
https://lorealanalytics.visualstudio.com/

Everything is ok, no security warning.

**Comment by omeshp** [comment]
@HCRSalaun Were you able to follow up with security administrators and get the proxy certificates installed on agent machine?

**Comment by HCRSalaun** [comment]
Hi,

I résolvez m'y issue vu following thé instructions on this thread :

https://github.com/Microsoft/azure-pipelines-agent/issues/1341

I créateur an environnent variable on thé agent machine :

NODE_TLS_REJECT_UNAUTHORIZED=0

Then I restarted the agent and everything worked. :)

Thanks for the support.
