### ISSUE TITLE
AZ Cli Task: Add option to configure the AZURE_CONFIG_DIR for fixing concurrency issue

### ISSUE THREAD

**Issue by cy33hc** [Microsoft/azure-pipelines-tasks#8314]
I have 2 VSTS pipelines that run in parallel, each calling multiple AZ Cli Task at different phases with the same serivce principal. They run under their own agent, but the agent is on the same Private Linux VM.

The issue is that one of the pipeline will always complete before the other and it would then call "az clear" to delete the access tokens. This causes the second pipeline that is still running to fail when a call to az cli executes. It fails becuz the access token has been cleared from the first pipeline.

It would be great if the AZURE_CONFIG_DIR can be configured to different directories for each AZ Cli Task.

**Comment by cy33hc** [comment]
Found a workaround for this.

I created a release variable with the name AZURE_CONFIG_DIR=$(System.DefaultWorkingDirectory). This set an Linux ENV prior to az login so that each pipeline has it's own access tokens.

**Comment by sachinma** [comment]
Thanks for posting the work-around. Adding @pulkitaggarwl  to see if we should make this as a  default experience or as an advanced setting.

**Comment by bishal-pdMSFT** [comment]
Closing as fixed with #8656
