### ISSUE TITLE
Add nuget-task-common as dependency in custom build task

### ISSUE THREAD

**Issue by parrainc** [Microsoft/azure-pipelines-tasks#8324]
### Description 

I'm in the middle of creating a new build task for Azure DevOps, and one of the dependencies I need to have in my task is the *nugest-task-common*, specifically what I need to do with that dependency is the ability to perform a `nuget  pack` command from my task (yeah, it's about creating custom nuget packages).

Could you please advise and let me know how can I achieve this?
Didn't find it in NPM, neither by looking at the docs :(

Thanks in advanced!!

**Comment by parrainc** [comment]
Hi guys,
any updates about this one? @keithrob

**Comment by jotaylo** [comment]
nuget-task-common doesn't explicitly provide nuget pack capability. Do you just need access to nuget.exe? If so, consider running the NuGet tool installer build task before your custom build task. That task will populate the task variable $(NuGetExeToolPath) with location of nuget.exe

**Comment by parrainc** [comment]
@jotaylo alright, will try that out and update you on how it went.

**Comment by alexmullans** [comment]
@parrainc were you able to get this working?

**Comment by alexmullans** [comment]
Great, thanks!
