### ISSUE TITLE
Pass REST API output across build tasks

### ISSUE THREAD

**Issue by knowds** [microsoft/azure-pipelines-tasks#8348]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    VSTS
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Issue: We use REST API for authentication to external service. As part of authentication, an access token is returned, which then needs to be passed to other APIs in the header. Initially I used Service Connection EndPoint to authenticate, but could not figure out a way to store and reuse the access token in build tasks. Any pointers

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ArieHein** [comment]
I haven't tried passing a complex data structure between tasks, only simple string values.

if the REST call is done from within a PowerShellscript, try:
https://roadtoalm.com/2016/08/11/set-output-variable-in-a-powershell-vsts-build-task/

for more reading:

**Comment by damccorm** [comment]
Yep, I'd echo that advice - using output variables is probably the easiest thing here. I'm going to close since it seems like this has been answered and has been inactive for a while. If you'd like it reopened, comment and we can do that
