### ISSUE TITLE
Failure downloading artifacts during Release on Linux agent

### ISSUE THREAD

**Issue by xenalite** [Microsoft/azure-pipelines-tasks#8353]
## Environment
- VSTS - rcss-willistowerswatson - PPM
- Agent - Private: 2.139.1
- OS: Red Hat Enterprise Linux 7.4

## Issue Description

**1. Set up a build that publishes 2 artifacts using "Publish Build Artifacts" task.**
One task should publish to a file share, the other task should publish to VSTS.
![image](https://user-images.githubusercontent.com/4509839/45751746-2d91eb80-bc0b-11e8-8524-5227a6496461.png)

![image](https://user-images.githubusercontent.com/4509839/45751673-f7ed0280-bc0a-11e8-9b69-e0498171af0b.png)

**2. Set up a VSTS agent on a Linux VM.**
See above for agent and OS details.

**3. Set up release definition to download artifacts only from VSTS.**

![image](https://user-images.githubusercontent.com/4509839/45751959-e526fd80-bc0b-11e8-9ff1-4b626850f302.png)

The release will attempt to download (or at least look at) artifacts on a share.
`Error: ENOENT: no such file or directory, scandir '\\e20-ix-file001p\drop$\vsts-issue\49497'`

While the Linux VM is on the same network as the share, is domain-joined, and is running as a domain account, it cannot resolve a UNC path. Regardless, it should not even care about the share artifact, because it was deselected.

### Task logs

[tasklog_2.log](https://github.com/Microsoft/vsts-tasks/files/2396945/tasklog_2.log)

### Error logs

`Error: ENOENT: no such file or directory, scandir '\\e20-ix-file001p\drop$\vsts-issue\49497'`

**Comment by gykuma** [comment]
Hi @xenalite ,
Can you please check if you are still able to repro this issue?

**Comment by xenalite** [comment]
@gykuma I cannot reproduce the issue anymore.
Tried on the same agent version and OS like in the OP.
Same set up as before for artifacts download:

![image](https://user-images.githubusercontent.com/4509839/47140316-d0df2a80-d2b5-11e8-82ec-c435923c1d95.png)

It only attempts to download the vsts artifact:

![image](https://user-images.githubusercontent.com/4509839/47140346-e5bbbe00-d2b5-11e8-9a8b-92ca38c9e211.png)

**Comment by gykuma** [comment]
@xenalite Thanks for the update. The issue should have got fixed with the new DownloadFileshareArtifacts task roll out.
