### ISSUE TITLE
Unable to set deployment name using Azure Resource Group Deployment task.

### ISSUE THREAD

**Issue by andremarques023** [Microsoft/azure-pipelines-tasks#8360]
## Issue Description

It should be possible to name Azure Resource Manager deployments when using Azure Resource Group Deployment task. When deploying a resource from Azure portal, the deployment name is usually something like _Microsoft.StorageAccount-20180918055344_ (resource type name and a timestamp yyyyMMddhhmmss). Using this task from VSTS/TFS pipeline results in a name like _template-2018818-1958_.

Considering the fact that is possible to provide a deployment name using _New-AzureRmResourceGroupDeployment_ cmdlet (and the REST API), setting the deployment name using the task would be a nice feature to have.

**Comment by pulkitaggarwl** [comment]
Thanks Andre for the feedback. Allow me to understand this in more detail. Can you please elaborate as to why changing of the name is important to you. Are their any scripts that you have written that takes into account a specific regex ? 

Regards, Pulkit

**Comment by andremarques023** [comment]
We're using a bunch of scripts to deploy the resources via PowerShell cmdlets. Given the fact that we have Resource Group limits in the deployment history (800) having a predictable way to find and remove deployments based on a name pattern is quite useful during CI/CD scenarios.

We adopted the resource type and a timestamp - e.g. _"Microsoft.StorageAccount-$(Get-Date -Format yyyyMMddhhmmss)"_.

**Comment by RoopeshNair** [comment]
@andremarques023  - We are currently looking into issues that affect broader set of customers. I don't see us getting to this anytime soon. We encourage contributions, would you like to submit a PR that can benefit others as well?

**Comment by andremarques023** [comment]
@RoopeshNair Of course! As soon as I have time I send a pull request for this.
