### ISSUE TITLE
Enable to select multiple input files in NuGet restore task

### ISSUE THREAD

**Issue by avivanoff** [Microsoft/azure-pipelines-tasks#8369]
VSTS NuGet restore allows specifying only single input file or wildcard as an "Path to solution, packages.config, or project.json" argument. Our build consists of multiple solutions, but only a couple of them have projects that use package management. For performance reasons, it would be helpful if it was possible to specify multiple solutions as an input.

**Comment by JohannesDrexler** [comment]
You can set multiple solutions or projects, just use `;` as separator

Example:
`Solution1.sln;Subfolder/Solution2.sln`

**Comment by avivanoff** [comment]
Why not change the input type to multistring?
