### ISSUE TITLE
Feature Request: Web Deploy allow for using IIS Virtual Directory

### ISSUE THREAD

**Issue by anton-dealmeida** [microsoft/azure-pipelines-tasks#8379]
## Environment
- VSTS - (More specifically IIS Web Deploy Task)

- Agent - Hosted

## Issue Description / Suggested Feature
The IIS Web Manage Task allows for me to create a Virtual Directory, to set it's path and everything from a management point of view. This requires that a 'website' already exists for the virtual directory to be attached to.

From the IIS Web Deploy task, I am unable to specify that I am deploying to a virtual directory or to make use of the Virtual Directory that I created in the previous step of Web Manage. I'm trying to setup this release pipeline to be idempotent so that if and when I change the server I'm running on it'll reconfigure / install the IIS as need be to reduce the need for IT departments interaction.

I do not know if this is already allowed, I could not find documentation on configuring Web Deploy to deploy to a Virtual Directory in a website. So right now it's just deploying to the root directory of the IIS website it's pointed at. (I'd say a combo box that defaults to root and that can be overridden with a text value like the tags box might be a great easy win if this is a easy feasible idea at all?)

**Comment by JFercan** [comment]
I would like to do this very thing.  Has there been any advance on this?  Thank you.

**Comment by syndicatedshannon** [comment]
It's a waste of time, maintenance, etc. etc. to to create a separate executable, just to house each front-end application project at the same domain name.

Two workarounds I don't consider solutions:
- Purchase the Azure Front Door Service to distribute URL branches
- Move my Angular apps to a separate host and configure CORS

A workaround I would be fine with, is to manually call MsDeploy with special parameters from my pipeline.yml.

**Comment by syndicatedshannon** [comment]
I'd also be fine with a workaround such as automated deployment directly to storage, provided it was secure and maintained references with the site, including deployment slots.

**Comment by syndicatedshannon** [comment]
From a cursory inspection of the azure-pipelines-tasks source, it looks like we may be able to prevent the conversion to an app, and hopefully the resulting error, by stopping at an interim of a package instead of folder. I guess the package might then contain the old <DeployAsIisApp>False</DeployAsIisApp> flag, or something similar. I might do more research toward this hack later if I have time.

`
    if(isFolderBasedDeployment) {
        msDeployCmdArgs += " -source:IisApp=\"'" + webAppPackage + "'\"";
        msDeployCmdArgs += " -dest:iisApp=\"'" + webApplicationDeploymentPath + "'\"";
    }
// ...
        else {
            msDeployCmdArgs += " -source:package=\"'" + webAppPackage + "'\"";

            if(isParamFilePresentInPacakge) {
                msDeployCmdArgs += " -dest:auto";
            }
            else {
                msDeployCmdArgs += " -dest:contentPath=\"'" + webApplicationDeploymentPath + "'\"";
            }
        }
`

**Comment by JFercan** [comment]
I found the best workaround to deploy both Angular and API project in .NET Core was to have both build artifacts in the release pipeline,  and simply copy the Angular app into a wwwroot subdirectory of the API and deploy that.

It has been working fine for us.

**Comment by syndicatedshannon** [comment]
@JFercan Agreed, works great assuming matching cadence and monorepo. Side note, if that's your situation, you may be interested in adding something like this to your targets:

	<Target Name="IncludeSpaRoot" AfterTargets="ComputeFilesToPublish">
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run package" />
		<ItemGroup>
			<DistFiles Include="$(SpaRoot)compiled\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>wwwroot\compiled\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>

**Comment by syndicatedshannon** [comment]
Here are two workarounds I just verified:
 - use the [AzureRmWebAppDeployment Task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4) with `DeploymentType: 'zipDeploy'`
 - call msdeploy manually (for windows-to-windows deployments only), similar to below

    set sitename=TheWebSite
    set virtualdirectory=TheVirtualDirectory
    set projectdir=C:\MySolution\MyProject\MyCompiledSpa
    "%msdeploypath%\msdeploy.exe" -verb:sync -source:contentPath=%projectdir% -dest:contentPath=%sitename%/%virtualdirectory%,ComputerName="https://%sitename%.scm.azurewebsites.net/msdeploy.axd?site=%sitename%",UserName="$%sitename%",Password="********",AuthType="Basic" -skip:Directory=App_Data

**Comment by syndicatedshannon** [comment]
My use-case is deploying an independent static files project to a web site in the same URL structure. If the original author of this feature request clarifies a different use case, I would be happy to create a separate thread.

Maybe my requirements can be met another way, but AFAIK, Virtual Directory/Application has been the best way to accomplish this in IIS. Here are my requirements that I seek to meet with this feature:

- It must clean up files that have been removed from the package
- It must not delete files published earlier in the pipeline
- Other deployments that follow it in the pipeline must not delete its files
- Must be able to restrict content access to claims-authorized identities
