### ISSUE TITLE
Ambiguous (at best) explanation of setting 'Preserve VNet'

### ISSUE THREAD

**Issue by Debbus72** [Microsoft/azure-pipelines-tasks#8380]
On the App Service Manage Swap Slots-task there is an extra setting called 'Preserve VNet'.
[Swap slots task source](https://github.com/Microsoft/vsts-tasks/blob/623f2c17222a354f3a3bf15c06c21f0d5c7822bc/Tasks/AzureAppServiceManageV0/task.json#L132)

The 'help' text for this is "Preserve Virtual Network settings", which isn't really helpful in explaining what this setting actually does, it only explains the abbreviation 'VNet'. 
Does this setting:
1. Swap the Virtual Network also during the swap, as in it preserves the virtual network settings with the (contents of) source slot.
2. Doesn't swap the Virtual Network during the swap, as in it preserves the virtual network settings on the target slot. 

I couldn't find any helpful documentation on the microsoft-docs site either on this (same ambiguous explanation). Also note that English is not my native language.

**Comment by markdebruijne** [comment]
This isn't descriptive either  the `-PreserveVnet` parameter that probably is used under the hoot.

https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/switch-azurermwebappslot?view=azurermps-6.13.0

**Comment by markdebruijne** [comment]
Can you dispatch this question regarding missing documentation @bryanmacfarlane

**Comment by RoopeshNair** [comment]
Here is a bit more context on this. https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#which-settings-are-swapped

------------------snip---------------
When you clone configuration from another deployment slot, the cloned configuration is editable. Furthermore, some configuration elements follow the content across a swap (not slot specific) while other configuration elements stay in the same slot after a swap (slot specific). 
------------------end snip-----------

Hope this helps

**Comment by markdebruijne** [comment]
@RoopeshNair No, it doesn't. According to https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#which-settings-are-swapped, the VNET Integration IS being swapped. 

That being said, what does that _Preserve VNET_ checkbox do in addition to the VNET integration that is swapped along within a swap?

**Comment by markdebruijne** [comment]
@RoopeshNair @kmkumaran ? please clarify.
I want to swap the VNET config I have added to my staging slot to the production slot during a swap. 
Check it, or leave it unchecked in that case?

**Comment by kmkumaran** [comment]
@markdebruijne - If you want to swap the vnet config, then leave it unchecked. 
The task actually [passes ](https://github.com/microsoft/azure-pipelines-tasks/blob/9332b6823f13b8bf36b22401658b87ce7d178797/Tasks/Common/azure-arm-rest/azure-arm-app-service.ts#L112) this preference (true or false) to [Azure REST API](https://docs.microsoft.com/en-us/rest/api/appservice/WebApps/SwapSlotSlot).

![image](https://user-images.githubusercontent.com/11780076/58076410-c8dac680-7bc7-11e9-9958-069ef543c967.png)

**Comment by krispenner** [comment]
Hi, I am trying to test and confirm this scenario and I found that if I have VNet integration (gateway required type) on my production slot and no VNet integration on my staging slot, then regardless of checking or unchecking "Preserve VNet", the production slot always has the VNet integration while my staging slot never has it. Is this expected? Are they only swapped if both slots have VNet integration configured?

**Comment by MortenMeisler** [comment]
Why is this closed? I mean the checkbox tooltip is just as ambiguous as 2 years ago. A setting this important should be dumped down and very explicit to avoid mistakes

**Comment by kmkumaran** [comment]
@N-Usha - Can you review the feedback above and triage accordingly.

**Comment by crystalgeek** [comment]
Why is this closed? Nothing has changed

**Comment by Mike-E-angelo** [comment]
Very frustrating to see this very important documentation not attended to after many years.  Does this mean that Vnet is preserved on the source or target slot?  Both?

**Comment by alsmyr** [comment]
Ran into this today and this is still ambiguous. 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/3719489/161754481-df3a4e54-0b39-4515-b6eb-f3afc9a0514d.png">

Do I transfer/preserve the VNET settings of the Slot or that of my production?

**Comment by gpetersOB** [comment]
Agreed. This needs to be addressed for clarity.

**Comment by TiTi** [comment]
Agreed this is unclear.
We raised a ticket and support basically told us this parameter is now overriden anyway so its value doesn't matter.
VNET settings do not change between your slots. Cf https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots#which-settings-are-swapped
