### ISSUE TITLE
InstallAppleProvisioningProfile unconditionally uses .mobileprovision suffix

### ISSUE THREAD

**Issue by hashtagchris** [Microsoft/azure-pipelines-tasks#8387]
In ios-signing-common.ts, getProvisioningProfilePath always returns a path ending with .mobileprovision. 

This works for Xcode 9 macOS builds, but Xcode 10 requires the provisioning profile suffix to be .provisionprofile.

**Comment by max-lobanov** [comment]
Hi, I faced with the same issue.
`InstallAppleProvisioningProfile` task doesn't work properly for macOS with `Xcode 10.0` 

provision profile extension verification was added in `Xcode 10.0`.
- Provision profile should have extension `.mobileprovision` for `iOS` builds.
- Provision profile should have extension `.provisionprofile` for `macOS` builds.

But actually this task doesn't contain any logic for that. It just uses `.mobileprovision` in all cases:
https://github.com/Microsoft/azure-pipelines-tasks/blob/02e576e225190663d52f115f174e85f7c1146a63/Tasks/Common/ios-signing-common/ios-signing-common.ts#L675

**Comment by madhurig** [comment]
Fix will be available in all regions of Azure DevOps by last week of November.

**Comment by max-lobanov** [comment]
@madhurig , Could you please confirm that the fix is already available?

**Comment by madhurig** [comment]
@max-lobanov - yes the fix has already been deployed to all regions of Azure DevOps. Are you seeing any issues?
