### ISSUE TITLE
Release definition not copying Chromedriver Dll's to Publish folder

### ISSUE THREAD

**Issue by neehakale** [Microsoft/azure-pipelines-tasks#8401]
Hi ,

My Release pipeline is not copying all the required artifacts. It is somehow missing to copy the dll's for chrome driver, FF driver etc.  I am trying to run selenium tests. Please help

**Comment by neehakale** [comment]
Currently reffering to : Run Functional Tests not finding ChromeDriver only on some machines? #4694

My issue looks similar to this one

**Comment by jayaranigarg** [comment]
@neehakale : Can you tell us following things:
1. Are you using Hosted agent?
2. Are ChromeDriver dlls present in the same folder as your selenium test dlls?
3. Can you set System.debug=true and share your build logs with us?

**Comment by jayaranigarg** [comment]
Closing the issue. Please feel free to re-open it when you have the answers to above questions.
