### ISSUE TITLE
Job environment variables broken with Gradle 4.7 / Java 10

### ISSUE THREAD

**Issue by Greenbones** [Microsoft/azure-pipelines-tasks#8426]
## Environment
- Server - Azure Pipelines
- Agent - Hosted Ubuntu / Hosted VS2017 

## Issue Description
I have a VSTS build that starts a docker container (InfluxDB) in one step, then uses a bash script task to extract the ip of that container and set it into a build env var for later use in a testing stage. We've had this configuration for several months and it has been working fine, the functional tests in our test task pick up the environment variable and find our influxDB docker just fine.

I recently upgraded our project from Gradle 4.0/Java 8, to Gradle 4.7/Java 10. When I did this, I found that our test task has started failing because it can't find the influx docker any more. I'm assuming this is because the environment variable isn't being picked up, but I'm at a loss as to why.

I can't really think of a reason why changing Gradle or the JDK would cause this behaviour, but the tests all pass locally with the same environment variable set externally, so it does seem to be isolated to VSTS.

### Task logs

[buildfail.zip](https://github.com/Microsoft/vsts-tasks/files/2421427/buildfail.zip)

**Comment by Greenbones** [comment]
Update: I re-targeted my build against Java 8, but kept Gradle 4.7 and it's back to passing, so it seems like this is related to using JDK10 in the gradle task somehow.

**Comment by madhurig** [comment]
JDK10 has been removed from the Hosted VMs since it is out of support. You can check the latest versions of software installed on the Hosted VMs here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software 

We have JDK 7, 8 and 11 on the Ubuntu VMs.

Thanks,
Madhuri
