### ISSUE TITLE
FeatureRequest: DeleteFilesV1: list what is deleted

### ISSUE THREAD

**Issue by JohannesDrexler** [microsoft/azure-pipelines-tasks#8430]
The task 'DeleteFilesV1' deletes files and can be configured to use wildcards to find what is about to be deleted. This is all working fine but the task doesn't log anything. It would be cool to see in the logs that the task is doing something and the configured wildcard is finding anything to delete.

**Comment by moswald** [comment]
This hasn't gotten a lot of traction since it was opened. @JohannesDrexler if this is important to you, please open a discussion on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
