### ISSUE TITLE
FeatureRequest: DownloadBuildArtifactsV0: Download artifact from PartiallySucceeded builds

### ISSUE THREAD

**Issue by Thilas** [Microsoft/azure-pipelines-tasks#8431]
Currently, this task only allows to download artifacts from Succeeded builds, it does not consider artifacts of PartiallySucceeded builds. It would be nice to have the choice here.

**Comment by daantimmer** [comment]
@Thilas sounds like the same issue that I have? https://github.com/Microsoft/vsts-tasks/issues/8346

**Comment by Thilas** [comment]
Indeed, it looks very similar (except the Jenkins part of course). What I had in mind is a new task parameter that allows to determine builds to consider thanks to their job statuses (min value): Succeeded (current behavior), Partially Succeeded (my use case) or Failed.

**Comment by Thilas** [comment]
Any answer would be very welcome here? Thanks!

**Comment by omeshp** [comment]
@Thilas We are open for contribution, you are welcome to submit a PR for this enhancement.

**Comment by omeshp** [comment]
Closing this issue since the changes to support this feature are merged.
