### ISSUE TITLE
'False' is True

### ISSUE THREAD

**Issue by anpaz-msft** [Microsoft/azure-pipelines-tasks#8441]
## Troubleshooting
Based on the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=vsts#type-casting), any non-empty string is treated as `True`. 

## Environment
- Server - Azure Pipelines, specifically: https://quarcsw.visualstudio.com/Solid/_build/results?buildId=6263&view=logs
- Agent - Hosted.
    
## Issue Description
According to documentation, during casting any non-empty string is valued as `True`, which makes values like `'False'` evaluate to `True`.

This is particularly bad for a variable, as apparently all variables are treated as a string, so defining a variable in YAML like:
```
variables:
  Signed: False
```

was still triggering a task with
```
  condition: variables['Signed']
```

The workaround, of course, is to set `'Signed'` to `''`
```
variables:
  Signed: ''
```

I still feel that `'False'` should just be `False`.

**Comment by bryanmacfarlane** [comment]
can you create an issue on azure-pipelines-yaml?   we will look at it.
