### ISSUE TITLE
PublishTestResultsV2: Test result completed date must be greater than test result start date

### ISSUE THREAD

**Issue by kostrse** [Microsoft/azure-pipelines-tasks#8449]
[ScalaTest](http://www.scalatest.org) for some reason (bug or intentionally) sets time for ignored tests to **-0.001**.

```xml
<testcase classname="com.foo.bar" name="Foo bar should foo bar" time="-0.001">
  <skipped/>
</testcase>
```

This prevents the report to be published, even if only one test was skipped and had negative time.

```
2018-09-12T08:32:52.8780751Z ##[warning]Failed to publish test results: Test result completed date must be greater than test result start date
```

Time for skipped tests doesn't have any meaning and could be ignored.

Sample ScalaTest code:

```scala
ignore should "foo bar" in {
  ???
}
```

Related issue: https://github.com/scalatest/scalatest/issues/1413

**Comment by roydebalina** [comment]
@kostrse I'm guessing your test result format is **Junit**. I tried publishing this sample result file and it got successfully published: 
<testsuite name="Mocha Tests" tests="1" failures="0" errors="0" skipped="1" timestamp="2018-07-28T20:28:46" time="0.000">
<testcase classname="com.foo.bar" name="Foo bar should foo bar" time="-0.001">
  <skipped/>
</testcase>
</testsuite>

**Comment by pagangil** [comment]
@kostrse We tried to reproduce this issue on the latest version of agent and the latest version of Publish test results task and it was successfully publishing the results. It could be possible that the bug might be in an older version of the task or agent and you might be using that.
Can you please mention the version of agent and task you are using? Also, if you're using an older version of agent, can you please try updating it and then try again?

**Comment by kostrse** [comment]
@roydebalina the test result is from [ScalaTest](
http://www.scalatest.org), I mentioned it above.

While ScalaTest generates JUnit reports, it sets time for skipped tests to -0.001, see my snippet.
This crashes report.

**Comment by pagangil** [comment]
@kostrse thank you for the details. Can you please also tell us about the questions asked by @roydebalina above:
 - Agent version:
 - Publish test results task version:
 - Are you on Azure DevOps or TFS onprem?
 - Are you using hosted agent or private agent?

**Comment by SadagopanRajaram** [comment]
This has been addressed with the commit below. 
https://github.com/Microsoft/azure-pipelines-agent/commit/980268dc33a405184b10f61c10eb1c0fee163e6a#diff-794b066dfa08920779551a9a83d82956
