### ISSUE TITLE
JS & CSS not allowed in code coverage reports

### ISSUE THREAD

**Issue by Thilas** [Microsoft/azure-pipelines-tasks#8452]
I know this has been this way for security reasons (as mentioned in #3027) but this is really annoying and forces every one to use workarounds like scripts to inline css or `HtmlInline` type of [ReportGenerator](https://github.com/danielpalme/ReportGenerator) tool.

And even with those, not being able to have js really make those huge coverage reports very disappointing: massive extra weight, no dynamic filtering, no coverage history charts, ...

Have you actual plans to work on this? Or may be to generate such rich reports right from VSTS out of a coverage file?

**Comment by jayaranigarg** [comment]
Tagging @PBoraMSFT @pvlakshm to comment on timelines.

**Comment by Thilas** [comment]
Any comments on this?

**Comment by Thilas** [comment]
It seems that even inlined svg gets removed by VSTS (see https://github.com/danielpalme/ReportGenerator/issues/164). Why is that? Could this limitation be removed?

**Comment by Thilas** [comment]
It does indeed. But it would be really cool to have actual SVG with dynamic chart instead of such PNG. And even more usefull, the capability to search in the results or group by that require JS to be supported.

Anyway, thanks for your feedback and I'll wait for those enhancements on coverage reporting.
