### ISSUE TITLE
ubuntu 14.04 in Microsoft Hosted Agent

### ISSUE THREAD

**Issue by guolinke** [microsoft/azure-pipelines-tasks#8455]
We just move on Azure Pipeline for the test and bulid package.
However, the os in microsoft hosted linux agent is ubuntu 16.04. Therefore, the built binaries cannot be used in some old os systems, like centos7, ubuntu 14.04.
I try to move back to ubuntu 14.04 but failed. 
Refer to https://github.com/Microsoft/LightGBM/issues/1708

**Comment by guolinke** [comment]
thanks @ganik 's help, I manage to use docker for building from ubuntu 14.04 in azure pipeline, by using `Hosted Ubuntu 1604` agent.
However, it always met this error:
```
##[Error 1]
The agent: Hosted Ubuntu 1604 2 lost communication with the server. Verify the machine is running and has a healthy network connection. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610 

##[Error 2]
The request was failed due to an internal service error. Please try again. 
```

It seems the `Hosted Ubuntu 1604` is not stable for use.

**Comment by guolinke** [comment]
thanks @bryanmacfarlane 
For example, like this build: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=338&view=logs

![image](https://user-images.githubusercontent.com/16040950/46259900-e01e5400-c511-11e8-84f6-6cd825edbd97.png)
These bulids on ubuntu 16.04 will queue forever and then throw the lost communication error.

I notice that as long as it is queued, it will fail in the end.

**Comment by damccorm** [comment]
@guolinke are you still experiencing this problem?

**Comment by guolinke** [comment]
@damccorm I use my own docker image to avoid the problem, not sure will it happen again by the azure-host agents.

**Comment by damccorm** [comment]
Closing since we don't have a repro. If anyone else is running into similar issues, I'd recommend filing a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html which is for more general service issues like this
