### ISSUE TITLE
VSTest task prematurely ending or hanging during test run

### ISSUE THREAD

**Issue by shack05** [Microsoft/azure-pipelines-tasks#8476]
## Environment
- Server: TFS 2015 U2 (Version 14.102.25423.0)
- Agent: Private (running as interactive process for Selenium UI tests)
- VSTest task version 1.0.32
- VSTest platform for Visual Studio 2015 (version 14.0.25123.0)
## Issue Description

We run our selenium UI tests using the VSTest task in the release stage of a build+release pipeline. We use Test Categories to filter the assembly and execute 50 UI tests using Selenium. The number of tests that is executed varies between subsequent runs (on the same agent, and against the same build of the test assembly). 

We are encountering issues of VStest.console.exe ending (vstest prints 'Total tests:..' information) or hanging indefinitely between one test finishing and the next test starting. There are no specific tests for which this occurs repeatably. We know this because we generate separate log files for [AssemblyInitialize], [AssemblyCleanup], and each [TestMethod] executed. 

Whenever vstest.console ends early there will always be an additional log file to what the vstest.console reported executing (i.e if vstest says it ran 20 tests, there will be 21 test log files created). This additional test log file always show that the test executed in its entirety (we log some text right at the very end of testcleanup). Furthermore, we can see [AssemblyCleanup] did not execute.

Also we have deemed it not to be an issue with test discovery because if we add a line to [TestInitialize] to fail each test, all 50 tests run every time.

I'm posting issue here under vsts-tasks because we have not been able to replicate this behaviour by invoking vstest.console.exe manually with all the same parameters.

### Logs

Task logs contain a lot of sensitive info so I haven't included them, I might be able to remove all sensitive info if you feel its necessary for diagnostics.

When running release with System.Debug = true the error from the end of the vstest.console.exe is:

System.Exception: VSTest Test Run failed with exit code: 1
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeVSTestCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()

but we also get this error when all the tests run (and we can see [AssemblyCleanup] executed in its entirety).

**Comment by kaadhina** [comment]
Hi, can you please share the full debug logs?
Also please enable vstest logs by changing trace levels to verbose in your agent machine, and share the logs from %temp% (https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/ )

**Comment by kaadhina** [comment]
Closing this. Please reopen with the above logs if this repros again.
