### ISSUE TITLE
Artifacts directory wanted to limit\minimise to only Package folder

### ISSUE THREAD

**Issue by v-azees** [Microsoft/azure-pipelines-tasks#8478]
## Troubleshooting

Unable to 

## Environment

- Server - Azure Pipelines On Premise    
        
    I am using Hosted VisualStudio 2017 and Build definition is ASP.Net. Below is my build definition.
![image](https://user-images.githubusercontent.com/43803661/46391822-5ed6e500-c6fc-11e8-9e82-42742decd959.png)

- Private Agent - Hosted:
    
     OS of the machine : Windows 10

## Issue Description

When I trigger my build, I am getting my artifacts with complex hierarchy.
I am trying to get these deployment files under only one folder without any subfolders.
![cicd drop artifacts](https://user-images.githubusercontent.com/43803661/46391448-9775bf00-c6fa-11e8-8e28-e98caeccb490.JPG)

Could any one tell me how can I achieve the only package folder using any kind of directory pattern.

**Comment by madhurig** [comment]
We recommend using the [CopyFiles task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml) to copy the files in the format you need. We generally copy the files into `$(Build.ArtifactStagingDirectory)` and specify that for publishing the artifact. See more about the variables available here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
