### ISSUE TITLE
Feature request: Docker task accept environment variables

### ISSUE THREAD

**Issue by dhanvi** [Microsoft/azure-pipelines-tasks#8483]
## Issue Description

It would be nice feature to able to pass environment variables to docker task. (something similar to the bash task below)
 
This would help us to send private variables to the task. (We can't reference environment variables any another way when using `docker stack deploy`)

Related: https://github.com/Microsoft/vsts-tasks/issues/6663 https://github.com/docker/cli/issues/939

![image](https://user-images.githubusercontent.com/6671379/46397068-db72bf00-c70e-11e8-9627-dcd085f88d29.png)

**Comment by azooinmyluggage** [comment]
Hi @dhanvi 
Have you tried the 1.* version of the task? One change we have implemented is to make the task more easier to use. Can you try the aruguments fields, you can pass on variables as well. Let me know if if you have more feedback.

![image](https://user-images.githubusercontent.com/6857119/46453210-e3d60300-c7bd-11e8-9c44-f0fcc8c6eeca.png)
Atul

**Comment by ajinkya599** [comment]
@dhanvi You can specify a variable in the variables section. These are available as environment variables:
![release-variable](https://user-images.githubusercontent.com/11447401/47015924-f19b6900-d16b-11e8-8394-d41248aad683.PNG)


You can also make the variables secret:
![release-variable-secret](https://user-images.githubusercontent.com/11447401/47015945-fc55fe00-d16b-11e8-9501-2af2ecc64c73.PNG)


So you can use this as an environment variable in your compose file as is described in this [comment](https://github.com/docker/cli/issues/939#issuecomment-390931468) on the [issue #939](https://github.com/docker/cli/issues/939) you opened in the docker cli repository.

Or, if the docker cli starts supporting -e argument, you can provide "deploy -e name=$(VAR1) stack_name" in the argument input in the Docker task

**Comment by ajinkya599** [comment]
Closing as fixed with pull request #8640.

**Comment by dhanvi** [comment]
@ajinkya599 Could you please explain how does the releases of the azure-pipeline-task work? https://github.com/Microsoft/azure-pipelines-tasks/releases didn't help me and I couldn't find any other documentations too.

or in other words could you please say when can I use this feature in Azure DevOps?

**Comment by ajinkya599** [comment]
The changes will be available with our next sprint deployment. This will take around 3-4 weeks.

**Comment by dhanvi** [comment]
@ajinkya599 could you please ping me here once this is deployed to production ?

**Comment by ajinkya599** [comment]
@dhanvi Sure. Will update here once it is deployed.

**Comment by dhanvi** [comment]
@ajinkya599 I can use it now Thank You! for the fix 👍

**Comment by yevda** [comment]
Hi, any official documentation how it can be used?
I don't see it here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml

This yaml doesn't work for me:
`    - task: Docker@2
      displayName: Build my image
      inputs:
        containerRegistry: 'my_svc'        
        repository: 'myrepo'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/myproject/Dockerfile'
        tags: |
          $(Build.BuildId)
          $(GIT_COMMIT)
          latest
        arguments: '--build-arg PAT=$(MY_MAPPED_FEED_PAT)'
      env:
        MY_MAPPED_FEED_PAT: $(SECRETRCMFEEDPAT)`

**Comment by Marty1703** [comment]
> Hi, any official documentation how it can be used? I don't see it here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml
> 
> This yaml doesn't work for me: ` - task: Docker@2 displayName: Build my image inputs: containerRegistry: 'my_svc' repository: 'myrepo' command: 'build' Dockerfile: '$(Build.SourcesDirectory)/myproject/Dockerfile' tags: | $(Build.BuildId) $(GIT_COMMIT) latest arguments: '--build-arg PAT=$(MY_MAPPED_FEED_PAT)' env: MY_MAPPED_FEED_PAT: $(SECRETRCMFEEDPAT)`
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/5127346/215092963-d1059dcc-6de4-4eab-82a7-706931ae0bb0.png">

Setting it as job variable, I was able to workaround this issue. 
```
          - job: myJob
            variables:
              - name: PROJECT_NAME
                value: XYZ
```

And then use it 
```
  - task: Docker@2
    displayName: "Build image"
    inputs:
      arguments: --build-arg project=$(PROJECT_NAME)
```

The workaround should not be needed, but I hope this gives a indication where the problem can be found.
