### ISSUE TITLE
Add support for Start/Stop/Restart/Delete VMSS in 'Azure Resource Group Deployment' task

### ISSUE THREAD

**Issue by inverted360** [Microsoft/azure-pipelines-tasks#8491]
I'm interested in restarting an array of virtual machine scale sets (all inside one resource group)

Request:
1. Performs action in parallel on all resources of same type
2. Action can be one of (Start, Stop, Restart, Delete)
3. Respects 'read-only' resource lock if exist

Motivation:
1. Can't achieve parallel execution using jobs within 'Inline PowerShell' task - maybe a different bug
2. Current 'Azure Resource Group Deployment' task returns "No virtual machines found in the resource group."
3. Can't set a ADO variable that persists across stages - so that I could spin up multiple agents to restart the VMSSs using "multi-configuration" for a stage

Haven't tried:
1. "Azure CLI' task type

**Comment by bishal-pdMSFT** [comment]
We have a "Azure VMSS deployment" task which currently handles updating the VMSS. We could add start/stop/restart/delete functionality to that task to make it more holistic. @pulkitaggarwl  Can you please track this.

**Comment by RoopeshNair** [comment]
@inverted360 - you do it with a script, for example, 

`az vm start --ids $(az vm list --query "[].id" -o tsv --resource-group "<your resource group>")`

it supports start, stop, deallocate commands.
