### ISSUE TITLE
Release cannot find available vstest agent

### ISSUE THREAD

**Issue by shenhong1000** [Microsoft/azure-pipelines-tasks#8505]
I created a self-host agent pool, each agent installed VS2017 test agent and Professional VS2017. I notice when set the agent pool and added Visual Stuido Test Task, "vstest" demand is added by default. When I create a schedule, the release environment cannot find an available agent. 

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
I think it's Azure Piplelines. 
https://dynamicscrm.visualstudio.com/OneCRM/CRM.Engineering/_releaseDefinition?definitionId=2385&_a=definition-tasks&environmentId=10210

- Agent - Hosted or Private: 
We created private agent pool and registered it properly  
   
## Issue Description
No agent could be found from agent pool (CRM-Engineering-TestAutomation-Autoboss):vstest
[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/43866916/46510313-15ba8a00-c7fd-11e8-9753-a66a182936df.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by acesiddhu** [comment]
@shenhong1000 looks like ur pipeline is working now. I will go ahead and close the issue. thanks
