### ISSUE TITLE
Missing trailing slash in Azure File Copy output parameter

### ISSUE THREAD

**Issue by rfcdejong** [Microsoft/azure-pipelines-tasks#8531]
## Environment
Azure pipelines, Hosted

## Issue Description
The containername isn't copy'ed over correctly to the output variable, missing a trailing slash in the end.

Current workaround to the Azure Resource Group Deployment as override parameter is:
-_artifactsLocation $(artifactsLocation)/ -_artifactsLocationSasToken $(artifactsLocationSasToken)

If I remove the / in the Azure Resource Group Deployment as override parameter the containername is missing in the _artifactsLocation parameter, somehow it must end with an trailing slash. Fix this either in the Azure File Copy or else allow the parameter in ARGD task without slash.

**Comment by rajatagrawal-dev** [comment]
@rfcdejong This has been fixed in Azure File Copy V2 a few days ago. The fix will be available after next deployment which can take a couple of weeks to reach all accounts.
