### ISSUE TITLE
Feature Request: XML variable substitution for Visual Studio Test

### ISSUE THREAD

**Issue by bertrandpons** [Microsoft/azure-pipelines-tasks#8533]
Hi,

Just an idea: as sometimes we want to perform tests against different environments, would it be possible to have the ability to apply XML variable substitution on app.config files for example?

Thank you :)

Bertrand

**Comment by kmkumaran** [comment]
Thanks for the suggestion. Including @RoopeshNair to track.

If you are open, you can also contribute and add this support. 
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts

**Comment by RoopeshNair** [comment]
@bertrandpons  - can you please clarify? is this about supporting XML variable substitution for Visual Studio Test? or is the ask for supporting app.config file variable substitution in App Service Deploy?

**Comment by bertrandpons** [comment]
@RoopeshNair - This is about supporting XML variable substitution for Visual Studio Test, yes. Typically I have the use case for which I want to perform tests that use different databases depending on targeted environment and it would be interesting to apply variable substitution instead of using different configuration files

**Comment by PBoraMSFT** [comment]
@bertrandpons - Visual Studio Test task supports taking in parameters through runsettings/testsettings file that can be overridden with any variables in the pipeline. The value is then accessed using the TestContext object. 
Doc https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=vsts 

Can you elaborate on why this cannot be used?

**Comment by bertrandpons** [comment]
@PBoraMSFT - I know this file but on one hand, I don't see how to use it to make connection string changes, and on the other hand, I just wanted to submit an idea to ease the process: being able to perform XML variable substitution in the same way as it is possible for IIS Web App Deploy task

**Comment by PBoraMSFT** [comment]
Closing this issue - there is no need for making this available as a feature within the VSTest task. For the most common test scenarios, we already support passing parameters and overriding them in the pipeline. 

Also, if you are looking for additional substitution capabilities, you may want to consider some of the extensions on the marketplace that already have these capabilities. https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens is one such extension. Use it as a pre-step before invoking the VSTest task.
