### ISSUE TITLE
Command line task: Unicode encoding issue with windows

### ISSUE THREAD

**Issue by yaananth** [microsoft/azure-pipelines-tasks#8534]
This is reported here - https://github.com/zeit/next.js/pull/5358#issuecomment-426906749 (old comments, now probably gone)

Here's the repro -

Yaml file and repo: https://github.com/yaananth/gatsby/blob/master/azure-pipelines.yml

https://yaananth.visualstudio.com/public/_build/results?buildId=2677&view=logs (ran on ubuntu)
renders checkmarks correctly -
![image](https://user-images.githubusercontent.com/12280011/46685599-e2447a80-cbc3-11e8-8b6e-a98c3d83b59c.png)

Where as,
https://yaananth.visualstudio.com/public/_build/results?buildId=2679&view=logs (ran on windows)
Shows garbled text -
![image](https://user-images.githubusercontent.com/12280011/46685863-875f5300-cbc4-11e8-9ba5-97645e1606d4.png)

**Comment by kachkaev** [comment]
@moswald has this been fixed now?

**Comment by moswald** [comment]
Yes, this was fixed in a recent release of Azure DevOps.

**Comment by yaananth** [comment]
@kachkaev  let me know if you have a repro. We fixed some character related bugs in viewer. I lost the repro for this so can't verify.
There's also the case where command line can't output unicode characters for windows.
So for that we might have to set code page https://ss64.com/nt/chcp.html
