### ISSUE TITLE
Azure File Copy randomly fails with "Failed to enable copy prerequisites"

### ISSUE THREAD

**Issue by edupuis-incomm** [Microsoft/azure-pipelines-tasks#8535]
## Environment
- Server: Azure Pipelines
I can provide the account name, team project name, build definition name/build number privately. Maybe you can retrieve from operation id eabc1f8a-e1af-4000-9a53-78be58ec4089.

- Agent - Hosted and Hosted VS2017

## Issue Description
This random issue has worsened significantly in the last few weeks but has happened throughout our last 2+ years of using VSTS / Azure DevOps. In the last few weeks we now have 20% failures or so when releasing to Azure servers, and redeploying without any changes succeeds. I suspect the problem is timing related with the VSTS task trying to manipulate the WinRMCustomScriptExtension.

We are experiencing this problem deploying to Azure servers that are in DevTestLabs built from the SQL Server 2016 SP1 Standard on Windows Server 2016 and Windows Server 2016 Datacenter bases. These servers are scheduled to stop and start daily on weekdays via DevTest Labs and are already running when these deployments fail.

The activity logs show the VSTS agent failing to Create or Update the extension, then our subsequent deployment succeeding. Note the same user name performs the work and no changes occur between releases:

![image](https://user-images.githubusercontent.com/34722540/46685934-ee284080-cbb3-11e8-8941-e0e2c59cb6a5.png)

Possibly related issues:
https://developercommunity.visualstudio.com/content/problem/299815/operation-put-extension-is-not-allowed-on-vm-exten.html
https://github.com/Microsoft/vsts-tasks/issues/5560
https://github.com/Microsoft/vsts-tasks/issues/4451
https://github.com/Microsoft/vsts-tasks/issues/1788

### Task logs

[AzureFileCopy.zip](https://github.com/Microsoft/vsts-tasks/files/2461475/AzureFileCopy.zip)

### Error logs

Failed to enable copy prerequisites. Operation 'PUT Extension' is not allowed on VM extension 'WinRMCustomScriptExtension' since it is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete). ErrorCode: OperationNotAllowed ErrorMessage: Operation 'PUT Extension' is not allowed on VM extension 'WinRMCustomScriptExtension' since it is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete). StatusCode: 409 ReasonPhrase: Conflict OperationID : eabc1f8a-e1af-4000-9a53-78be58ec4089

**Comment by johnhydemtm365** [comment]
Hi we are getting the same issue every time we do a deployment. We redeploy and it works fine.

Operation 'PUT Extension' is not allowed on VM extension 'WinRMCustomScriptExtension' since it is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete).

We do however shutdown the VM' in the evening and restart it in the morning....if that has any bearing...?

Thanks

John

**Comment by Ajay-MS** [comment]
Please share debug logs. 

Debug logs can be enabled by adding release definition variable `system.debug` with value `true`.

**Comment by edupuis-incomm** [comment]
Attached are all logs for a failed release. The failed task is named “Copy files”.

**Comment by Ajay-MS** [comment]
I am not able to figure out any attachment of logs here. Please share it at RM_Customer_Queries@microsoft.com.

**Comment by edupuis-incomm** [comment]
Sent to RM_Customer_Queries@microsoft.com email, got undeliverable response related to rmdfte@microsoft.com only accepting messages from people inside organization. Attaching here via github site instead of email attachment. Hopefully this works.

[ReleaseLogs_4437.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2515532/ReleaseLogs_4437.zip)

**Comment by johnhydemtm365** [comment]
Hi release logs attached from out latest release as well

Thanks
John
[ReleaseOputputLog.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2518886/ReleaseOputputLog.txt)

**Comment by Ajay-MS** [comment]
@edupuis-incomm, @johnhydemtm365 

Thanks for sharing logs. Your logs are really helpful to identify the problem, debugging it further to know all possible causes. 

Will fix it soon.

**Comment by Ajay-MS** [comment]
@edupuis-incomm, @johnhydemtm365 

Raise PR for the fix
https://github.com/Microsoft/azure-pipelines-tasks/pull/8728

**Comment by Ajay-MS** [comment]
We have fixed this issue.  It will be deployed with the next deployment.
