### ISSUE TITLE
artifact.associate not a command?

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/azure-pipelines-tasks#8546]
Just tried using the logging command `artifact.associate`, but I'm getting this error:

```
##vso[artifact.associate: command not found' contains logging command keyword '##vso', but it's not a legal command.
```

The docs referenced by the error list that `artifact.associate` is a valid command, not sure what's going on here?

**Comment by moswald** [comment]
@atrauzzi Can you include the line from your script?

**Comment by atrauzzi** [comment]
It would be something like this:

```
echo "##vso[artifact.associate type=container;artifactname=${ARTIFACT_NAME};]${AZURE_ARTIFACT_STAGING_PATH}"
```

**Comment by moswald** [comment]
Wow, I forgot to follow up on this, sorry about that @atrauzzi. If it is no longer an issue for you, please close this.

I've assigned the Release area as the artifact task is owned by the Release team.

**Comment by atrauzzi** [comment]
If you guys haven't fixed it, then it's still an issue.

**Comment by Lovakumar** [comment]
This seems to be coming from agent command support. Adding Build/Core team to take a look at this.

**Comment by moswald** [comment]
@atrauzzi It looks like the documentation was incorrect. Try `artifacttype=` instead of just `type=`. If that doesn't fix it, please reopen this issue and include a build log or a link to a build so we can take a look.

**Comment by atrauzzi** [comment]
K!
