### ISSUE TITLE
unable to build and restore packages on tfs build

### ISSUE THREAD

**Issue by manuelapop** [microsoft/azure-pipelines-tasks#8549]
building on tfs build using msbuild fails to restore packages and build solution:

******************************************************************************

Starting: Build

******************************************************************************
Executing the following commandline:
D:\TFSBuildEngine\agent\worker\vsoWorker.exe  /name:Worker-5eca6906-e3b3-404a-84a0-66efbc64251a /id:5eca6906-e3b3-404a-84a0-66efbc64251a /rootFolder:"D:\TFSBuildEngine" /logger:Forwarding,1.0.0;Verbosity=Verbose,Name=Agent25-e149cd8473c865db81c3d8378774bac8;JobId=5eca6906-e3b3-404a-84a0-66efbc64251a

******************************************************************************

Starting: Get sources

******************************************************************************
Syncing repository: SpecIT WebAPI Client (TFVC)
Workspace Name: ws_80_25;Build\135930c9-6bc3-4b20-8424-a2bd814d645a
tf get /version:2128
Replacing D:\TFSBuildEngine\Work\80\s\1.0\SpecItWebApi\NuGet.Config;C2128
Done syncing repository SpecIT WebAPI Client to version 2128 (workspace version C2128)

******************************************************************************

Running tasks

******************************************************************************

******************************************************************************

Starting task: NuGet restore $/SpecIT WebAPI Client/1.0/SpecItWebApi/SpecItWebApi.sln

******************************************************************************
Set workingFolder to default: D:\TFSBuildEngine\tasks\NuGetInstaller\0.1.18
Executing the powershell script: D:\TFSBuildEngine\tasks\NuGetInstaller\0.1.18\NuGetInstaller.ps1
Saving to D:\TFSBuildEngine\Work\80\NuGet\newNuGet.config
D:\TFSBuildEngine\agent\worker\tools\NuGet.exe restore "D:\TFSBuildEngine\Work\80\s\1.0\SpecItWebApi\SpecItWebApi.sln"  -NonInteractive -configfile "D:\TFSBuildEngine\Work\80\NuGet\newNuGet.config"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Restoring NuGet package Microsoft.EntityFrameworkCore.Abstractions.2.1.4.
Restoring NuGet package Microsoft.EntityFrameworkCore.Analyzers.2.1.4.
Restoring NuGet package Microsoft.CSharp.4.5.0.
Restoring NuGet package Microsoft.EntityFrameworkCore.2.1.4.
Restoring NuGet package Microsoft.EntityFrameworkCore.Relational.2.1.4.
Restoring NuGet package Microsoft.EntityFrameworkCore.Relational.Design.1.1.6.
Restoring NuGet package Microsoft.EntityFrameworkCore.Design.2.1.4.
Restoring NuGet package Microsoft.EntityFrameworkCore.SqlServer.2.1.4.
Restoring NuGet package Microsoft.EntityFrameworkCore.SqlServer.Design.1.1.6.
Restoring NuGet package Microsoft.EntityFrameworkCore.Tools.2.1.4.
Restoring NuGet package Microsoft.Extensions.Caching.Memory.2.1.2.
Restoring NuGet package Microsoft.Extensions.Caching.Abstractions.2.1.2.
Restoring NuGet package Microsoft.Extensions.Configuration.2.1.1.
Restoring NuGet package Microsoft.Extensions.Configuration.Abstractions.2.1.1.
Restoring NuGet package Microsoft.Extensions.DependencyInjection.2.1.1.
Restoring NuGet package Microsoft.Extensions.Configuration.Binder.2.1.1.
WARNING: Unable to find version '2.1.4' of package 'Microsoft.EntityFrameworkCore.Analyzers'.
Restoring NuGet package Microsoft.Extensions.DependencyInjection.Abstractions.2.1.1.
WARNING: Unable to find version '2.1.4' of package 'Microsoft.EntityFrameworkCore'.
Restoring NuGet package Microsoft.Extensions.Logging.2.1.1.
WARNING: Unable to find version '2.1.4' of package 'Microsoft.EntityFrameworkCore.Abstractions'.
Restoring NuGet package Microsoft.Extensions.Logging.Abstractions.2.1.1.
WARNING: Unable to find version '4.5.0' of package 'Microsoft.CSharp'.
Restoring NuGet package Microsoft.Extensions.Options.2.1.1.

this is a .net core 2.1 solution.

we are using msbuild version 15. visual studio 2015

my company does not have other tools to build .net core 2.1 project at the moment.

this is the build efinition

![image](https://user-images.githubusercontent.com/20730965/46749563-e11a5880-cc6a-11e8-8099-15f0005ba718.png)

![image](https://user-images.githubusercontent.com/20730965/46749580-e9729380-cc6a-11e8-9b5f-17677ab56b2f.png)

this is my nuget.config file

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <solution>
    <add key="disableSourceControlIntegration" value="true"/>
  </solution>
</configuration>
```

please help! thank you.

**Comment by JohannesDrexler** [comment]
> we are using msbuild version 15. visual studio 2015

msbuild version 15 is included in Visual Studio 2017. Visual Studio 2015 contains msbuild version 14.

back to your problem: You can build this projects with vs2017 or later. You could also use the netcore-sdk without the need of a newer version of Visual Studio on your buildserver. 
The sdk exposes commands like "dotnet restore" and "dotnet build" to the systems shell.
Vsts also includes some tasks for that and also an dotnet-tool-installer. I don't know your tfs-version so i don't know what option you are going for at that point

**Comment by alexmullans** [comment]
@manuelapop were you able to get this working? if not, can you clarify your TFS version?

**Comment by elbatk** [comment]
Closing this as we haven't seen a response in a few months, feel free to reach out if you're still having issues!
