### ISSUE TITLE
VsTestV2 cant find the testing tools when only Visual Studio 2017 Build Tools is installed

### ISSUE THREAD

**Issue by andyfisher100** [Microsoft/azure-pipelines-tasks#8559]
Currently the VSTestV2 task does not work if the Visual Studio 2017 build tools are installed. The component directory is slightly different for VS2017 build tools compared to VS2017 Enterprise etc.

Currently the VSTest task runs the following command to find if the test tools are installed:
_VSwhere.exe -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -property installationPath_

When VS2017 build tools are installed, the testing component is called: _Microsoft.VisualStudio.Component.TestTools.BuildTools_
you can find them here https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017

Instead of installing the full IDE (~50GB) on our build machines, we would like to start using  build tools (~17GB) but currently we are unable to run tests, unless manually specifying the vstest console directory in the build.

**Comment by kaadhina** [comment]
To avoid installing full VS IDE, we recommend using the Visual Studio Test Platform Installer task (Please refer to [this](https://docs.microsoft.com/en-us/azure/devops/release-notes/2017/nov-28-vsts) for more details). Does this work for you?
