### ISSUE TITLE
Tests failing on "Hosted VSTS 2017" machine, but are passing in other environments

### ISSUE THREAD

**Issue by sushilraje** [Microsoft/azure-pipelines-tasks#8564]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    Account Name : [solutionaccelerators](https://solutionaccelerators.visualstudio.com/) 
    Project Name : RemoteMonitoring
    Build definition name : Consolidated Repo - dotnet
    Build number : 20181012.5

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: Hosted VS2017
  
## Issue Description
Unit tests for C# fail with exit code 1 **w/o any logs**, but the same unit tests when conducted on local win machine succeed.

[Include task name(s), screenshots and any other relevant details]
![vsts_dotnet_run](https://user-images.githubusercontent.com/39531904/46844930-f3d97e00-cd8d-11e8-8237-ea0f1e25a2d5.PNG)

### Task logs
Zipped logs attached
[log_10_1844.zip](https://github.com/Microsoft/vsts-tasks/files/2471385/log_10_1844.zip)

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by acesiddhu** [comment]
the logs attached doesn't have any failures. can you attach the correct logs

**Comment by kaadhina** [comment]
Hi, closing this for now. Please reopen with the correct logs.
