### ISSUE TITLE
Publish Build Artifacts - File share option to not append Artifact name to path?

### ISSUE THREAD

**Issue by oatsoda** [Microsoft/azure-pipelines-tasks#8567]
I'm using the Publish Build Artifacts to publish my build output to a file share.  However, it always appends the name of the Artifact to the end - I'd rather not as it adds another level to by path (and I run the risk of exceeding the max filename length).

For example, I have the path set to:

`\\buildserver\Drops\$(System.TeamProject)\$(Build.DefinitionName)\$(Build.BuildNumber)\`

In order to publish it to a version-named folder.  But annoyingly it appends "Drop Folder" to the end because that is the name of my artifact.  I don't think I can set the Artifact Name to $(Build.BuildNumber) because when I then need to reference it in my Release Definition but I am not sure that having Dynamically named Artifacts is a good idea.

Alternatively, could a setting be added to "Publish Build Artifacts" to not have it published to the named subfolder?

https://github.com/Microsoft/vsts-tasks/blob/90c8dcd604ebb4e224b17f16b7fa713576642b10/Tasks/PublishBuildArtifactsV1/publishbuildartifacts.ts#L79

**Comment by moswald** [comment]
Hi @oatsoda. I have created a developer community feedback item for this, which is where we track incoming feature requests. Please go vote for it if you still think this would be a feature you are interested in.

Thanks!
