### ISSUE TITLE
Unable to locate the "Machines" section mentioned by tool tip for Authentication selector. 

### ISSUE THREAD

**Issue by slimwizard** [Microsoft/azure-pipelines-tasks#8584]
## Environment
Azure DevOps Release Definition

## Issue Description

I would like to use Windows Authentication to connect to my SQL server within my Release definition, the problem is that there is no longer anywhere to specify the necessary admin credentials for the target machine. Hovering over the information tab for the Authentication input gives me the following tip:

![sql db question](https://user-images.githubusercontent.com/26125306/46895626-e3351080-ce3e-11e8-9163-ed4b8252df60.PNG)

I have searched all over the Azure DevOps web interface and am unable to locate a "Machines" section. Is there just something I am missing or is this tip outdated, and if it is outdated (i.e. the Machines section no longer exists) then how would one specify these credentials?

**Comment by Ajay-MS** [comment]
@slimwizard 

I am assuming you are using "SQL Server Database Deploy" task on "Deployment Group". 

You are right here that "Machines section" in tool-tip is misleading. We will correct it soon. 

In the case of "Deployment Group", your DG agent try to access server with same creds with which you have configured your DG agent. Also, Ideally DG agent should be configured on the target machine.

**Comment by Ajay-MS** [comment]
PR - https://github.com/Microsoft/azure-pipelines-tasks/pull/8602
