### ISSUE TITLE
[ NodeTool ] - Add option to skip adding to tool cache

### ISSUE THREAD

**Issue by dylan-smith** [microsoft/azure-pipelines-tasks#8585]
When using the Node Tool Installer (Hosted VS2017) it takes:
2 secs - download package
5 secs - extract package
36 secs - caching tool

On hosted agents - I'm assuming the caching is entirely pointless.

Could we add an option to skip adding the tool to the cache?

[node-tool-installer-log.txt](https://github.com/Microsoft/vsts-tasks/files/2474869/node-tool-installer-log.txt)

**Comment by bryanmacfarlane** [comment]
There is not the tool along with a tool cache.  When it's downloaded, it is written to the tool cache.  That is the tool that is downloaded.

**Comment by elbatk** [comment]
It looks like what Bryan is saying is that is the time it takes to download the tool and caching it is a small part of that, I assume? Is this still an issue for ya @dylan-smith ?

**Comment by elbatk** [comment]
Closing this one as I believe it's behaving as expected, as a part of tool acquisition.

**Comment by dylan-smith** [comment]
@elbatk @bryanmacfarlane this still appears to be a problem IMHO.  I just ran the task again and while the total times were faster than when I opened this issue, the vast majority of the time is still spent copying to cache folder, which is useless on hosted agents.

These were the timings I got:

Download: 0.56s
Extract: 3.8s
Copy to Cache: 16.2s

@bryanmacfarlane I'm not sure what you meant by your previous comment.  Looking at the source it looks like there is a 2-step process: 1. Download/extract 2. Copy to cache dir.  It's the latter that is taking a long time and is unnecessary on a hosted agent.  Specifically in this file: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NodeToolV0/nodetool.ts

The download happens on line 136, the extract on line 161, and the copy to cache on line 171.  My suggestion is make line 171 optional so that it can be skipped on a hosted agent.

Log attached.
[nodetool_installer_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3273080/nodetool_installer_log.txt)

**Comment by bryanmacfarlane** [comment]
Thanks for the data.  Re-opening for consideration.

**Comment by bryanmacfarlane** [comment]
Perhaps we can extract right to the cache folder and not diverge the cases ...?  @damccorm ?

**Comment by elbatk** [comment]
@bryanmacfarlane @damccorm it sounds like if we can fix the increase in time for copying to cache, then adding an option to not cache would be obsolete. Let me know what you guys think and then we can reassign/rename this GHI.

**Comment by damccorm** [comment]
@jtpetty I think this one is worth having someone investigate even though its been sitting a while
