### ISSUE TITLE
VSTest Task doesn't support *NIX Environments

### ISSUE THREAD

**Issue by josepmc** [Microsoft/azure-pipelines-tasks#8588]
## Environment
- Agent - Hosted and Private

## Issue Description
The VSTest task is not supporting any *NIX Environment. The fact is, though, that there's a fully fledged vstest command in dotnet which will run in these platforms and will accept the same parameter set as vstest.console (as in fact, it's exactly the same).

My question is hence whether there are any immediate plans to support this feature, as otherwise the entire MTM set in Azure DevOps is made Windows-only.

**Comment by PBoraMSFT** [comment]
@josepmc - the dotnet task is cross-plat and can be used with the test verb for all testing needs. As such, making VSTest task work on all platforms is low pri. Some capabilities in the task are Windows only.

**Comment by josepmc** [comment]
@PBoraMSFT That's perfectly understandable, but you should then advertise that part of the functionality of 'Test Management' in Azure DevOps (the one related to automation) is Windows-only.
