### ISSUE TITLE
CI builds are done on ff merge commits, instead of actual commits

### ISSUE THREAD

**Issue by stas00** [microsoft/azure-pipelines-tasks#8589]
## Environment
- Server - Azure Pipelines 

## Issue Description

When ff merge commit gets triggered by push of a code commit, CI build attaches itself to the merge commit instead of the actual commit:

![snap1](https://user-images.githubusercontent.com/10676103/46921789-780d4a80-cfb4-11e8-86b2-90ad2b723ccd.png)

Technically, it's not a problem, as it's still testing the commit, it's just that it's not doing it with the correct commit sha1 and thus the commit itself doesn't report pass/fail on github - it's always green (CLA check).

You can see this happening for each pair of merge and commit entries here: https://github.com/fastai/fastai/commits/master when it happens so .

**Comment by moswald** [comment]
@stas00 we have made many improvements in this area, and the pass/fail report on GitHub should be correct. Please open a new ticket on the [Azure DevOps Developer Community site](https://developercommunity.visualstudio.com/spaces/21/index.html) if you are still having issues.
