### ISSUE TITLE
Kubernetes task stripping quotes from json when creating secrets

### ISSUE THREAD

**Issue by rh072005** [Microsoft/azure-pipelines-tasks#8594]
If I try to create a secret containing JSON using the Kubernetes task (v1) the quotes are stripped out.
I'm adding `--from-literal=config.json='{"property":"value"}'` to the Arguments in the Secrets section.
I've tried both with and without the surrounding single quotes, and on the Hosted VS2017 and Hosted Ubuntu 1604 agents with the same result.
When you inspect the logs you can see that the quotes have been removed
`[command]/usr/bin/kubectl create secret generic my-secret --from-literal=config.json='{property:value}'`
Retrieving and decoding the secret shows that the quotes are missing as well.

**Comment by ajinkya599** [comment]
@rh072005 - You can achieve this by putting your value inside double quotes and escaping the inner double quotes like this:
--from-literal=config.json="{\"property\":\"value\"}"

**Comment by rh072005** [comment]
I’ve simplified the above for this example but my json is actually coming from a Key Vault secret (using the key vault task). I should be able to pass that variable to another script, escape the quotes and pass it back though so I’ll give that a try as a workaround

**Comment by ajinkya599** [comment]
Thanks for the quick response. Please update us here once you try it out.

**Comment by rh072005** [comment]
I've given this a try by adding a powershell script step that looks like this
```
$escaped = $env:Json.Replace("`"", "\`"")
Write-Output ("##vso[task.setvariable variable=Json2;]$escaped")
```

It's closer to the right value but the Kubernetes task is still removing the first quote mark

`[command]/usr/bin/kubectl create secret generic my-secret --from-literal=azure.json='{\property":"value"}'`

**Comment by ajinkya599** [comment]
The escape character `\` before a double quote works only when the whole value is inside double quotes.

Can you try the following:

- If your incoming value Json is `{"property":"value"}`, then do the following in a powershell script to generate Json2:
``$escaped = $env:Json.Replace("`"", "\`"")``
`Write-Host "##vso[task.setvariable variable=Json2;]$escaped"`<br>
This will set `Json2={\"property\":\"value\"}`
<br>You can then use Json2 value in the command by passing it inside double quotes as your command arguments:
`secret generic my-secret --from-literal=config.json="$(Json2)"`
<br>This will give you `config.json={"property":"value"}` (decoded)


- If your incoming value Json is `"{"property":"value"}"`, then do the following in a powershell script to generate Json2:
``$escaped = $env:Json2.Replace("`"", "\`"")``
`Write-Host "##vso[task.setvariable variable=Json2;]$escaped"`
<br>This will set `Json2=\"{\"property\":\"value\"}\"`
<br>You can then use Json2 value in the command by passing it inside double quotes as your command arguments:
`secret generic my-secret --from-literal=config.json="$(Json2)"`
<br>This will give you `config.json="{"property":"value"}"` (decoded)

**Comment by rh072005** [comment]
I've got that working with and escaping the quotes properly now. Thanks for your help

**Comment by ajinkya599** [comment]
Closing as confirmed above that it worked by escaping the double quotes.
