### ISSUE TITLE
Why a tfs 2018 deployment group phase will run after previous one partially failed?

### ISSUE THREAD

**Issue by lzd6696** [Microsoft/azure-pipelines-tasks#8599]
I am a TFS 2018 update 2 user. I use release management as my CD solution. I create a release definition consists of multiple deployment group phases. I execute this release definition, I found one of my deployment group phase partially failed. as the following screenshot shows: enter image description here
![2018-10-15_144923-v1 0](https://user-images.githubusercontent.com/42199635/46991097-08739880-d137-11e8-983e-96d3d26c653c.png)

I think my release definition will stop right after this partially failed deployment group phase, but it doesn't. It runs next deployment group phase(as my screenshot shows). I am sure all of the deployment phases had set "Only when all previous phases have succeeded".

What happened? and anyone had a solution/workaround?

**Comment by RoopeshNair** [comment]
@lzd6696  - Success criteria in a deployment group (DG) phase is determined by the number of "Targets to deploy to in parallel" property (minimum health criteria)

For example, if you have '4' targets and you set `two targets at a time`, then `2` targets are selected for deployment in the first iteration. In worst case scenario, both can fail and the DG phase will result in error. The workflow will not continue further. 

Suppose, If only one of the deployments failed in the first iteration, it will continue with `one` more target in subsequent iteration. The new limit in now `one`(though you specified as two at a time), as we have `one` in failed state already. If no further failures, the deployment will continue as partially succeeded. Here the deployment did not breach the minimum health criteria that was set at 50%, hence partially succeeded. 

Only exception being, if you set it as `all at once/100%`, then technically you are pulling down all the targets for deployment and worst case all of them can end up in failed state and the health / availability is actually `zero`. As an exception, we expect at minimum it should succeed on any `one` target, and deployments to remaining 3 can potentially fail and the DG phase will exit as partially succeeded. If all the deployments failed then it will fail the DG phase.

**Comment by lzd6696** [comment]
I think my question is focus on "how to fail a partilly failed DG phase?".  Please refer to this issue: [](https://github.com/Microsoft/azure-pipelines-tasks/issues/7333) .

If this is a bug, when it will be fixed ? TFS 2018 update 3?

**Comment by RoopeshNair** [comment]
As you  might have seen from the thread, for now. the workaround is to store the job status in a custom  variable in a persistent store and evaluate it in subsequent phases. 

We know this is important for you, right now the team is working on issues that affect broader set of customers. We will not be able to get to it anytime soon (>6months). We will continue to monitor the original thread #4743. Closing this for now.
