### ISSUE TITLE
Linux tasks not being built?

### ISSUE THREAD

**Issue by kilasuit** [Microsoft/azure-pipelines-tasks#8603]
Looking on the Readme it seems that the Linux tasks have never been built. Is that an oversight or misconfiguration of the Badge?

**Comment by stephenmichaelf** [comment]
There is an issue with the badge right now as we move to a public build. Should be resolved shortly.

**Comment by stephenmichaelf** [comment]
Resolved by https://github.com/Microsoft/azure-pipelines-tasks/pull/8607
