### ISSUE TITLE
QUESTION - Azure SQL Database Deployment - Azure SQL Managed Instance

### ISSUE THREAD

**Issue by bertrandpons** [microsoft/azure-pipelines-tasks#8608]
Hello,

Is there a way to deploy SQL Database to Azure SQL Managed Database from Azure DevOps? As far as I understand, you cannot connect to it if you are not in the VNet or linked to this VNet.

Thank you

**Comment by bbakermmc** [comment]
Any update on this?
I see that managed instances now have this option:
![image](https://user-images.githubusercontent.com/30090055/65163760-8ad0a080-da09-11e9-8e31-2118574cc188.png)
I don't think we want to enable it just to deploy ssdt, is there an ip range or something we could whitelist instead?
