### ISSUE TITLE
PublishTestResults - JUnit merged results show incorrect time summary

### ISSUE THREAD

**Issue by ktharsis-sw** [Microsoft/azure-pipelines-tasks#8610]
Publish test results task is showing incorrect total (summary) time when multiple files are merged with JUnit format.

Discovered on prem and then recreated on azure pipelines
- Server: On premise (16.122.27409.2) and Azure Pipelines
- Agent: Private (2.122.2 on Windows) and Azure Pipelines (HostedVS2017 and Hosted Linux Preview)

Quick repro:
1. Check in at least 2 copies of below as XML file
2. Create build def with Publish Test Results task on *.xml with Merge Test Results checked
 
```<?xml version="1.0" encoding="UTF-8"?>  
<testsuites name="SuiteCollection1" tests="8" time="3.000">  
  <testsuite name="Suite1" id="e5a9ef9b-e5ec-4498-b338-af6edf158d48" tests="2" failures="0" errors="0" time="2.000">  
    <testcase name="Test1" time="1.000"/>  
    <testcase name="Test2" time="1.000"/>  
  </testsuite>  
  <testsuite name="Suite2" id="bdd295e7-2f7b-48ee-b483-7ea6afa3daf1" tests="1" failures="0" errors="0" time="0.500">  
    <testcase name="Test1" time="0.500"/>  
  </testsuite>  
  <testsuite name="Suite3" id="319c06b2-600c-4d17-8eb3-a2aa6ae6dc43" tests="1" failures="0" errors="0" time="0.500">  
    <testcase name="Test1" time="0.500"/>  
  </testsuite>  
</testsuites>
```

Note the total time is 3 seconds per file.

Single file works correctly, although will always print 
`Timestamp is not available for one or more testsuites. Total run duration is being calculated as the sum of time durations of detected testsuites` 
for each xml file in the build logs.

Multiple files run completes successfully and all tests are accurately listed in the tests outcome pane (including the summary time). However the tests summary run duration is not correct. The build confirmation email also shows the incorrect summary.

![image](https://user-images.githubusercontent.com/44200709/47020254-fc7fda80-d126-11e8-8b1c-5a44240455f8.png)

![image](https://user-images.githubusercontent.com/44200709/47020325-1e795d00-d127-11e8-952b-848a8b1114fd.png)

**Comment by divais** [comment]
The summary based on the runs start and complete time where the start time is determined by the time of publishing. However the grid shows the sum. I understand in your scenario this is incorrect but when you have parallel execution of tests run duration helps determine overall run time.

**Comment by ktharsis-sw** [comment]
So the summary run duration in this case is basically the time that the publish test result task takes. I verified this by adjusting the test times - the run duration is almost always 3 seconds (which matches with the task log)

Thanks for the info - would never have figured that out without help.
