### ISSUE TITLE
Hide custom 'Settings file' in VsTestV2 task

### ISSUE THREAD

**Issue by mguirao** [Microsoft/azure-pipelines-tasks#8622]
## Issue Description

Using "Visual Studio Test" v2 task step with a custom 'Settings file' (testParameters.runsettings), the step is printing the content of the file that contains some sensitive parameters on the console output.

Is it possible to hide this somehow ?

**Comment by mguirao** [comment]
Any feedback on this ? 
It's been 2 month.

**Comment by nigurr** [comment]
@mguirao currently it can be masked by providing the same details in pipeline variables.

For example:
` <Parameter name="webAppPassword" value="Password" />`

If you want to mask the `Password`, create a pipeline *secret variable* with value as `Password`.
This will strip off sensitive data from pipeline.
