### ISSUE TITLE
One solution with multiple Azure Function projects

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/azure-pipelines-tasks#8626]
AccountName: o365exchange.visualstudio.com
TeamProject: O365 Sandbox/SubstrateDevX
Agent - Hosted or Private:
Hosted agent 2017

I have one Solution with multiple AzureFunctions. This resides in a single repository at https://o365exchange.visualstudio.com/O365%20Sandbox/_git/metagraph.scanning

I want to set up a deployment pipeline for each of them separately. The default AppService Deployment targets a solution. Can you let me know if there is a recommended way to set up such a pipeline?

I tried various combinations (MS Build step, package zip , App service deploy) but do not seem to get the right contents deployed.

**Comment by vincentdass** [comment]
@shkrishms 
You can use `C# function` template to build function project individually.
![image](https://user-images.githubusercontent.com/20121508/47216233-dfb30380-d3c1-11e8-9d8d-2309863e9d92.png)

Select required `CSPROJ` to be built.

![image](https://user-images.githubusercontent.com/20121508/47216270-007b5900-d3c2-11e8-90bd-4438325c8374.png)

To Deploy the Azure Function, Go to **release** and select `Deploy a function app to Azure Functions`
![image](https://user-images.githubusercontent.com/20121508/47216323-302a6100-d3c2-11e8-91cf-0dc431b44f58.png)

**Comment by shkrishms** [comment]
I am able to get this working. Thanks for the help.
