### ISSUE TITLE
Maven task fails with "Unable to locate executable file: '/usr/share/maven/bin/mvn'"

### ISSUE THREAD

**Issue by dcaro** [Microsoft/azure-pipelines-tasks#8630]
## Troubleshooting
Run the Maven task against a Java project

## Environment
- Server - Azure Pipelines or TFS on-premises?

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: account: csedevops / build definition: zddDemo-UserJava-CI / Build # 21. 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description

The Maven task fails with the following error: 
2018-10-17T04:50:41.3971707Z (node:2994) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to locate executable file: '/usr/share/maven/bin/mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

### Error logs

2018-10-17T04:50:41.3971707Z (node:2994) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to locate executable file: '/usr/share/maven/bin/mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by dcaro** [comment]
The workaround is to select "custom path" for the Maven path (in the advanced section) and specify "/usr" for the Maven path.
If needed, set the checkbox "Set M2_HOME variable".

**Comment by AlexRukhlin** [comment]
Hi @dcaro 

Thanks for reporting this issue. The M2_Home variable was not set correctly after last update of the hosted Ubuntu VM image. The fix should be deployed with few days.

Alex

**Comment by viperx77** [comment]
Microsoft, how is it that you can push a new hosted VM image and break all of our java maven builds and then say it will be deployed in a few days? This does not inspire confidence to your devops pipeline practice. I appreciate finding this and the work around.

**Comment by AlexRukhlin** [comment]
We're deploying the fix today.

Alex

**Comment by dakale** [comment]
This should be resolved now. There was an issue with the ubuntu 1604 machine image that has been fixed and deployed to all accounts

**Comment by joshmgross** [comment]
@dcaro Are you still having this issue?

**Comment by dcaro** [comment]
Apparently not, thanks for checking.

**Comment by ankurrawat66** [comment]
I am facing the same issue with ubuntu 1804.

**Comment by shiraZadok** [comment]
for me also the same problem at ubuntu 1804.
UnhandledPromiseRejectionWarning: Error: Unable to locate executable file: '/__w/1/s/apache-maven-3.8.1/bin/mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable
