### ISSUE TITLE
Variable substitution doesn't work if value is empty string

### ISSUE THREAD

**Issue by stajs** [Microsoft/azure-pipelines-tasks#8631]
- Server: Azure Pipelines
- Account: imagimation
- Project: FOG
- ReleaseId: 132
- EnvironmentId: 488
- Agent: Hosted VS2017

## Issue Description

Variable substitution fails when attempting to replace a non-empty string with an empty string value. 

Given a webjob `App.config`:

```xml
<appSettings>
     <add key="Email:FromDomain" value="@local.example.com" />
     <add key="Email:ToOverride" value="local@example.com" />
</appSettings>
```

And the variables for a `Staging` release stage:

- `Email:FromDomain` = `@staging.example.com`
- `Email:ToOverride` = `staging@example.com`

Correct result:

```xml
<appSettings>
     <add key="Email:FromDomain" value="@staging.example.com" />
     <add key="Email:ToOverride" value="staging@example.com" />
</appSettings>
```

However the variables for our `Prod` release stage fails:

- `Email:FromDomain` = `@example.com`
- `Email:ToOverride` = _empty string_

Incorrect result:

```xml
<appSettings>
     <add key="Email:FromDomain" value="@example.com" />
     <add key="Email:ToOverride" value="local@example.com" />
</appSettings>
```

Note: the failure to replace with _empty string_ while the other value is being replaced correctly.

There is a similar closed issue (#6419) but in reverse where you couldn't replace an empty string with a non-empty string. The [last comment](https://github.com/Microsoft/azure-pipelines-tasks/issues/6419#issuecomment-369908926) on that issue is also reporting this new issue that I'm submitting.

### Task logs

```
================================================
Task         : Azure App Service Deploy
Description  : Update Azure App Services <snip>
Version      : 3.4.10
Author       : Microsoft Corporation
Help         : [More information](https://aka.ms/azurermwebdeployreadme)
================================================
Got connection details for Azure App Service:'<redacted>'
XML variable substitution applied successfully.
```

The variables were picked up correctly in the release:

![image](https://user-images.githubusercontent.com/2253814/47070560-00f2e300-d24e-11e8-84c8-5f56e286f675.png)

**Comment by vincentdass** [comment]
@stajs , thanks for reporting the issue. The issue is resolved and the fix will be available in next deployment (~4-5 weeks).
