### ISSUE TITLE
Unable to Create Sql Server VM with Default instance

### ISSUE THREAD

**Issue by Jassi1313** [Microsoft/azure-pipelines-tasks#8642]
Is there any way to create a Azure Sql server VM with the Named instance of sql server rather than default

**Comment by kmkumaran** [comment]
Do you need help in creating VM with through Task? If so, you can use Azure Resource Group task. Refer the template https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-sql-database/azuredeploy.json

**Comment by Jassi1313** [comment]
Hi. Actually i hve a temeplate to create sql server VM. But it create a default instance of sql. We want named instanced of sql server. Is there any way we can create sqlserver VM wifh named instance.

**Comment by Ajay-MS** [comment]
@Jassi1313 

Even if you try to create a VM from the portal, in SQL configuration it doesn't specify the option to create named instance of SQL server. So I doubt if template provides this option. 

But I will suggest checking with Azure Quickstart template team as they will have more context on this. 
[Azure QuickStart Templates - Issues](https://github.com/Azure/azure-quickstart-templates/issues )

**Comment by Ajay-MS** [comment]
@Jassi1313  

Closing this issue assuming we have no action item on this. Feel free to reopen if you expect any action item on us.
