### ISSUE TITLE
Windows Machine File Copy task to skip default options

### ISSUE THREAD

**Issue by am11** [microsoft/azure-pipelines-tasks#8651]
## Problem statement and request:

Please provide a way (e.g. in UI: checkbox, and in YAML: property) to opt out of default options, in particular `/S` and `/E` options, from robocopy command in `Windows Machine File Copy` TFS task.

When we specify `Files` filter, in addition to copying those files, it creates the whole directory/subdirectories structure (mostly empty due to file filter). There is no way to avoid creation of directories.

## Some background and details

Consider the following options used by `Windows Machine File Copy` task in TFS:

By default, it copies all files, and the log message shows:

```
Files: *.*
Options: *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30
```

If we specify Files:

```
Files: File1.txt
    File2.txt
Options: /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30
```

with `Clean Target` and `Copy Files in Parallel` checkboxes checked:

```
Options: /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /R:1000000 /W:30
```

According to help:

```cmd
robocopy /?

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Friday, October 19, 2018 11:32:22 AM
              Usage :: ROBOCOPY source destination [file [file]...] [options]

             source :: Source Directory (drive:\path or \\server\share\path).
        destination :: Destination Dir  (drive:\path or \\server\share\path).
               file :: File(s) to copy  (names/wildcards: default is "*.*").

::
:: Copy options :
::
                 /S :: copy Subdirectories, but not empty ones.
                 /E :: copy subdirectories, including Empty ones.

  /COPY:copyflag[s] :: what to COPY for files (default is /COPY:DAT).
                       (copyflags : D=Data, A=Attributes, T=Timestamps).
                       (S=Security=NTFS ACLs, O=Owner info, U=aUditing info).

             /PURGE :: delete dest files/dirs that no longer exist in source.
               /MIR :: MIRror a directory tree (equivalent to /E plus /PURGE).

 /DCOPY:copyflag[s] :: what to COPY for directories (default is /DCOPY:DA).
                       (copyflags : D=Data, A=Attributes, T=Timestamps).

::
:: File Selection Options :
::
...
...

::
:: Retry Options :
::
               /R:n :: number of Retries on failed copies: default 1 million.
               /W:n :: Wait time between retries: default is 30 seconds.
...
...

::
:: Logging Options :
::
...
...

::
:: Job Options :
::

...
...
```

In order to skip copying directory structure (aka: omit `/S` and `/E`) when the intent is to *only* copy bunch of files, is currently not possible.

**Comment by JustinSchneiderPBI** [comment]
We had a problem with overwrite recently, where 2 different build definitions incorrectly pointed to the same share. This caused a significant amount of duplicated work for a number of people, so the followups are rather important. In addition to correcting the destinations, we're preventing future misconfigurations by blocking overwrite of files. I added additional file copy parameters to exclude files that are either newer or older or different and to apply readonly setting in windows: /XC /XO /XN /A:+R. However, these settings were not applied. This seems related.

**Comment by JustinSchneiderPBI** [comment]
<commenting to remove stale label>
