### ISSUE TITLE
each CI/RR build gets queud up twice

### ISSUE THREAD

**Issue by stas00** [microsoft/azure-pipelines-tasks#8658]
## Environment
- Server - Azure Pipelines

For some reason we started to get every job duplicated since a few days - can you please have a look?
https://dev.azure.com/fastdotai/fastai/_build/index?definitionId=1&_a=completed

I checked that we have push/pr webhooks registered once, but it appears as if something else is pushing second time. Very odd.

You guidance is needed. 

Thank you.

**Comment by moswald** [comment]
I believe this was a one-time issue with the service. If this is still an ongoing issue please open a thread on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
