### ISSUE TITLE
New build pipeline won't let choose an alternative pipeline

### ISSUE THREAD

**Issue by stas00** [microsoft/azure-pipelines-tasks#8659]
## Environment
- Server - Azure Pipelines

Any reason I can't create a new pipeline with an alternative yml file stored on git when doing New build pipeline? 

I was able to workaround it by choosing the default azure-pipelines.yml since it gave me no other option, save it, and then through edit, switch to the second pipeline file.  

Thanks.

**Comment by xenalite** [comment]
@stas00 You can pick an existing YAML file via the visual designer option. Ironically the one that says "create pipeline without YAML".

![image](https://user-images.githubusercontent.com/4509839/47264940-f10e2400-d517-11e8-9a88-955bd4f6b17c.png)

You can then pick YAML as the startup template.
![image](https://user-images.githubusercontent.com/4509839/47264954-4ba78000-d518-11e8-95e8-e64a2191718a.png)

Unfortunately, the option to pick the YAML file will be flagged as invalid, no matter what you put in. 
![image](https://user-images.githubusercontent.com/4509839/47265027-89f16f00-d519-11e8-9adc-b4aeb17c6c1f.png)

You must first pick something from the ellipsis button (even if it's an invalid yml file or a folder), then change file path afterwards.
![image](https://user-images.githubusercontent.com/4509839/47264984-cf616c80-d518-11e8-8bbc-ad914cff2472.png)

I would hope someone in UX team would fix this poor experience.

**Comment by stas00** [comment]
Thank you, @xenalite, for sharing your version of a workaround. It seems that my workaround has less steps ;)

**Comment by madhurig** [comment]
Thanks for the feedback, we now have an option to [choose an alternate yaml file path](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-147-update#create-pipelines-from-an-existing-yaml-file-in-any-branch-or-path). Please try that out. We are working on making this option available even when you have an azure-pipelines.yml file in your repository.
