### ISSUE TITLE
no option to prevent timestamp prefix in logs

### ISSUE THREAD

**Issue by stas00** [Microsoft/azure-pipelines-tasks#8661]
## Environment
- Server - Azure Pipelines

How can I configure the pipeline to not append the date timestamp on every line?
```
==============================================================================
2018-10-21T18:15:49.9712427Z Generating script.
2018-10-21T18:15:49.9769318Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/94af9acc-76e0-4be3-a239-c8ede151eb32.sh
2018-10-21T18:15:49.9843980Z Testing docs-dev
2018-10-21T18:17:17.0073148Z Argument "0, 0" isn't numeric in numeric gt (>) at /usr/share/perl5/HTTP/Response.pm line 256.

```
It's difficult to share these logs with others, since I first need to copy to editor, remove the timestamps, and only then I can share those with others.

I couldn't find any timestamp-related settings [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts). Is this something I can setup in the pipeline script? or a build-related settings?

Thanks.

**Comment by joshmgross** [comment]
Hey @stas00, we don't currently have any settings like that, but I'll pass this on to the team. Thanks for your feedback!

**Comment by Luke-Robinett** [comment]
Hi. Any update on this?

**Comment by gerbil** [comment]
bump

**Comment by dougeiwo** [comment]
Is this case closed? Any update?

**Comment by ReinisV** [comment]
the timestamps have been removed:
https://learn.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-148-update#build-and-release-log-viewer-enhancements

but now I have the oposite problem.
I liked the timestamps, they would tell me a lot about steps that were taking longer than necessary on the build agent.

How do I get the timestamps back?
