### ISSUE TITLE
VS Test Platform folder was not found in cache

### ISSUE THREAD

**Issue by NDDeveloper13** [Microsoft/azure-pipelines-tasks#8665]
**Setup:**
vsts agent 2.140.2
TFS 2018 Update 3 on premise
Win 10 machine

**Background/Release Definition Setup**
Our main application to test has the ability to log into different years with different user types. To specify which tests apply to which combination of year/user type, we use test configurations and assign the appropriate test configurations to our test cases within our test plan. We have hundreds of configurations. Some configurations have 1-2 test points, some configurations have over 200 test points. To support kicking off all of these test points during a release, we have a release definition that contains one environment for each configuration that has test points within the test plan - each environment containing a VS Test task. As far as I can tell, I need multiple environments, so that they can run in parallel, as it doesn't appear that multiple agent phases running in parallel is supported yet. Ideally, I'd be able to say run all test points within a given test suite (not limited by configuration) within a VS Test task, but I don't see the support for that either.

Rather than having the VS Test Platform Installer in all 126 environments, I put any setup steps for each of the agents (including the VS Test Platform Installer) into a setup environment that runs prior to any other environment. The setup environment has a deployment group phase, which includes those tasks that only need to run once on each of the agents prior to the regression. So, what I've done is registered 2 agents on each of our machines - 1 regular agent located at c:\agent and 1 deployment group agent whose work folder points to c:\agent\_work, so that when the VS Test Platform Installer runs in the deployment group, the VS Test Platform is installed where the agent can use it - or so I thought.

Here is a screenshot of the pipeline:
![releasedefinition](https://user-images.githubusercontent.com/43071948/47305369-e4a8ca80-d5ee-11e8-9509-a37d0fa8e596.jpg)

**Issue**
When the release gets to the VS Test task for each configuration, it fails with the following error:
"VS Test Platform folder was not found in cache"

The VS Test Platform is clearly installed and exists at c:\agent\_work\_tool\VsTest, so I'd expect the VS Test task to be able to use it. 

Some logs from the VS Test task:
2018-10-22T14:35:39.2456571Z ##[debug]vstestLocationMethod=version
2018-10-22T14:35:39.2456764Z ##[debug]vsTestVersion=toolsInstaller
2018-10-22T14:35:39.2456939Z ##[debug]Trying VsTest installed by tools installer.
2018-10-22T14:35:39.2457144Z ##[debug]VsTestToolsInstallerInstalledToolLocation=undefined
2018-10-22T14:35:39.2457581Z ##[debug]Agent.Version=2.141.0
...
2018-10-22T14:35:39.2915467Z ##[debug]VsTestToolsInstallerInstalledToolLocation=undefined
2018-10-22T14:35:39.2920697Z ##[debug]Path to VsTest from tools installer: undefined
2018-10-22T14:35:39.2921693Z ##[debug]VsTestToolsInstallerInstalledToolLocation=undefined

**Expectation:**
The VS Test task to be able to use the VS Test Platform installed earlier in the release on the machine.

**Comment by kaadhina** [comment]
Hi, thank you for your feedback.
There needs to be a tools installer task in each of those environments. This is because, the tools installer task sets a few configurations apart from just downloading the test platform, but please note that it will not download the package again if the agent already has it and will merely set the configurations it needs. So the task run should be pretty quick if the agent already has the tool.
