### ISSUE TITLE
AzFileCopyV2 does not support Linux agents

### ISSUE THREAD

**Issue by sjwaight** [Microsoft/azure-pipelines-tasks#8673]
## Issue Description

If you attempt to use the Task in a build that will run on a non-Windows build host you receive an error.

As AzCopy is available for Linux the expectation would be that this task is functional on that platform.

**Comment by RoopeshNair** [comment]
@sjwaight  - would recommend posting this on [UserVoice](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services?category_id=145269) so that we can prioritize approiately.
