### ISSUE TITLE
Add an action to Completed Build Menu 

### ISSUE THREAD

**Issue by knowds** [Microsoft/azure-pipelines-tasks#8680]
![image](https://user-images.githubusercontent.com/18011456/47354856-77279780-d6dd-11e8-92d2-abe2a9baddf2.png)

I need to insert a menu here. ms.vss-build-web.completed-build-menu does not give desired results. Is there a way to insert a menu here ? My requirement is to allow users download a report on every build completion. Had been unable to find an entry point for same.

**Comment by bryanmacfarlane** [comment]
This repo is for tasks (/tasks) in this repo.  You can create an issue on developer community for service.
