### ISSUE TITLE
Agent.Plugins.Repository.CheckoutTask error while parsing versionInfo.message json

### ISSUE THREAD

**Issue by xtomas** [microsoft/azure-pipelines-tasks#8681]
## Description
Build failed due to json parsing error. I think it's caused by PR markdown description, included as versionInfo.message in the job message (line 477 in the included trace log file).

Part of description is copy&paste from backlog item (google chrome + windows 10) directly in the browser and markdown blockquote added.
![image](https://user-images.githubusercontent.com/10938220/47354774-de365380-d6bf-11e8-8663-8360a5756f3b.png)

Our workaround was to forcepush dummy commit with simple message and build finished properly.

## Exception
```
2018-10-23T08:18:55.9344316Z Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: j. Path 'repositories[0].properties.versionInfo.message', line 1, position 1702.
2018-10-23T08:18:55.9344724Z    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
...
2018-10-23T08:18:55.9350776Z    at Agent.PluginHost.Program.Main(String[] args)
```
## Agent diagnostic log
[Worker_20181023-081852-utc.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2505272/Worker_20181023-081852-utc.log)

**Comment by damccorm** [comment]
Is this still an issue? If it is, please file an issue at https://github.com/microsoft/azure-pipelines-agent. The checkout task is actually built into the agent, so that's the best place to address issues with it - sorry this has sat for so long.
