### ISSUE TITLE
PowerShell 

### ISSUE THREAD

**Issue by vvyas2** [Microsoft/azure-pipelines-tasks#8684]
## Environment
- Server - Azure Pipelines
 - Agent - Private: 
    - Agent version 6.3.9600
    - Windows Server 2012 R2

## Issue Description

This occurs with Microsoft developed PowerShell task, does not occur with a third party task at the time of execution 

The term 'powershell.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by azureDaveOps** [comment]
Could you share out the task as you have it configured?  Are you able to manually run the same script from a powershell command line on your private agent?

**Comment by JohannesDrexler** [comment]
There might be something wrong with the `%PATH%` environment variable of the executing system. 
Check if `%PATH%` contains `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\`

**Comment by bryanmacfarlane** [comment]
Correct, it needs to be in the path.
