### ISSUE TITLE
Test publish fails when JUnit results file contains skipped tests

### ISSUE THREAD

**Issue by jonmclean** [Microsoft/azure-pipelines-tasks#8686]
## Troubleshooting
Publishing JUnit unit & integration test result files fails when JUnit tests are marked with "@Ignore".

## Environment
- Server - Azure Pipelines
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: All

- Agent: Hosted

## Issue Description

When publishing a JUnit result file when some tests were marked with "@Ignore" the task displays a message saying that the file is not in the expected format.

The issue is that the XSD that is being used does not account for the "skipped" XML attribute that JUnit writes to the result file.

I made appropriate changes to the XSD locally, validated the JUnit results file, and created a PR against the XSD.  See https://github.com/windyroad/JUnit-Schema/pull/7

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by jonmclean** [comment]
Attaching a ZIP file with the following:

1. Current incorrect XSD from windyroad
2. Corrected XSD incorporating the windyroad PR changes
3. Sample JUnit XML file that fails validation with the current XSD and passes with the proposed XSD.

Note that I trimmed this XML result file by hand to remove identifying information.  You may contact me directly if you need more detailed information.

[junit_ignores.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2508131/junit_ignores.zip)

**Comment by jonmclean** [comment]
I disagree that this should be categorized as an "enhancement."  It is a bug that prevents valid builds from succeeding.  JUnit succeeds but the build fails.

**Comment by jonmclean** [comment]
You can also copy the corrected XSD verbatim.  See the Pull Request that I mention above.

**Comment by nigurr** [comment]
@jonmclean I tried publishing the sample xml which you have provided and it's working as expected. 
![image](https://user-images.githubusercontent.com/15208679/49214142-ffd7d880-f3eb-11e8-9ffc-e546c6ffd2c7.png)

Total Tests: 4
Skipped tests: 1 (Other)
