### ISSUE TITLE
VSTS not showing correct Test result count

### ISSUE THREAD

**Issue by mathewkuruvila** [Microsoft/azure-pipelines-tasks#8687]
VSTS is not publishing the proper test result count. As in the attached screenshot 

Total Tests : 171
TestResults To Publish : 167
5 test cases are not getting published.

This happens often. So specific pattern. Some test cases will be missing in the published results

![image](https://user-images.githubusercontent.com/866753/47404395-e31b0600-d798-11e8-9635-ac0f4b0494bb.png)

VS Test version
![image](https://user-images.githubusercontent.com/866753/47400252-2c168e80-d788-11e8-8909-8019e4a6f25c.png)

VSTS Summary

![image](https://user-images.githubusercontent.com/866753/47467877-18c8f900-d844-11e8-82a0-0bea062af833.png)

Please ignore the failure count. You can see Total count is not matching

**Comment by kaadhina** [comment]
Are there multiple test cases pointing to the same test method?
Can you also please share the debug logs (set variable system.debug=true and share the logs)?

**Comment by kaadhina** [comment]
No @mathewkuruvila , we have not heard this before.

**Comment by mathewkuruvila** [comment]
I can't do that. Log file is having too much information specific to project.

It seems to happen if the path in TestContext.AddResultFile(path) is a lengthy one. I have reduced the length of path and now everything seems good. Will come back if the issue happens again.

**Comment by kaadhina** [comment]
Thank you for getting back with the resolution.
