### ISSUE TITLE
NodeTool doesn't support ChakraCore versionSpec

### ISSUE THREAD

**Issue by nschonni** [Microsoft/azure-pipelines-tasks#8689]
The ChakraCore builds aren't in the same `/dist/` folder as the v8 Node builds. They currently sit in https://nodejs.org/download/chakracore-release/
Maybe @kunalspathak has an idea on if adding the support makes sense right now.

**Comment by kunalspathak** [comment]
@digitalinfinity, do we want to pursue this for `node-chakracore`?

**Comment by digitalinfinity** [comment]
Yes, that would be awesome- @nschonni is the impact that if we use Azure DevOps to run a node task, node-chakracore won't work?

**Comment by nschonni** [comment]
Right now the installer only installs from binaries from the regular dist folder https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/NodeToolV0/nodetool.ts#L130
You could probably right a separate task if you wanted to use ChakraCore instead of NodeTool

**Comment by bryanmacfarlane** [comment]
This is by design - it's a node tool installer so it's the node version spec.  As noted above you could write a separate task and contribute to the market place.
