### ISSUE TITLE
FtpUploadV1 ftpUtils.cleanRemoteContents fails for german Umlauts

### ISSUE THREAD

**Issue by andreasblueher** [microsoft/azure-pipelines-tasks#8692]
## Environment
- Server
Azure DevOps
Acountname: GOB
Team project name: unitop Apps
Build number: 2368
Release id: 79

- Agent
Hosted VS2017

## Issue Description
Task FTP Upload clean components task failed when trying to delete a file with german umlaut

### Task logs
[ReleaseLogs_79.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2510591/ReleaseLogs_79.zip)

### Error logs
[Ftpupload Log.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2510588/Ftpupload.Log.txt)

If I can provide any more information, please let me know.

**Comment by andreasblueher** [comment]
Hello @yacaovsnc since you replied to my other task and the fact that this issue is related to the same code, I thought to link you here aswell.

**Comment by yacaovsnc** [comment]
Looks like a dupelicate of #7514 

Will track this unicode issues there.
