### ISSUE TITLE
NuGet task deprecated ?

### ISSUE THREAD

**Issue by Anthony-Breneliere** [Microsoft/azure-pipelines-tasks#8702]
## Issue Description

I am trying to use the task **NuGet** in a YAML pipeline. 

BUT, in the file:
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetV0/task.json
The description says it is  deprecated.

AND
The task we should use instead is the task **NuGet**, the same task !

Which is the task that is not deprecated ?

>
>     "name": "NuGet",
>     "friendlyName": "NuGet Command",
>     "description": "Deprecated: use the “NuGet” task instead. It works with the new Tool Installer framework so you can easily use new versions of NuGet without waiting for a task update, provides better support for authenticated feeds outside this account/collection, and uses NuGet 4 by default.",
>

**Comment by apluche** [comment]
Hi Anthony,

The task that isn't deprecated is the NuGetCommandV2 task.

Please let us know if you have other issues.

**Comment by bryanmacfarlane** [comment]
closing since the question was answered.
