### ISSUE TITLE
VSTest Task Fails with System.TimeoutException: The HTTP request timed out after 00:01:40

### ISSUE THREAD

**Issue by NDDeveloper13** [microsoft/azure-pipelines-tasks#8704]
**Setup:**
TFS Update 3 on-premises
vsts agent 2.140.2
VsTest installed via Test Platform Installer (15.9.1 preview)
Visual Studio Test task Version 2.*
- Select tests using Test Plan
- multi-agent parallelism

**Issue:**
I am seeing test runs aborting in the middle, I believe due to the following error:
_2018-10-25T05:58:16.5424818Z ##[error]Failure attempting to call the restapis. Method: System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.Test.WebApi.TestExecutionServiceCommand] <GetCommand>b__0(), Exception: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled._

We see this on multiple test runs quite often - our setup is new and have seen this each time we try to run all of our tests (over 1200 test points across multiple environments). I cannot yet tell a pattern of when it happens. This particular test run was using 7 test agents. Two of the test agents completed their tests, one of them hadn't started running tests yet, and out of the remaining 4 agents, 3 of them are all similar logs with other agent appearing different, so I suspect it was that different agent that encountered the issue that caused the problem. Here are the logs around the failing section for that agent:
[HttpTimeoutLogs.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2515984/HttpTimeoutLogs.txt)

Please let me know if you need any other information.

**Comment by kaadhina** [comment]
The call seems to have timed out. This is mostly an indication of unreliable network.
Can you check if the timeout always happen in the same set of machines? If so eliminating them from the pool will help improve the reliability of the test runs.
In the latest version, we have addressed this by adding a retry logic for this call.

**Comment by NDDeveloper13** [comment]
I set the VSTS_HTTP_TIMEOUT; as suggested here:
[https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/troubleshooting.md#workaround-httptimeoutexception](url)

However, that doesn't seem to be honored. I still see the error in the log about timing out at 1:40:
2018-10-29T07:33:12.1263347Z ##[error]Failure attempting to call the restapis. Method: System.Threading.Tasks.Task`1[Microsoft.TeamFoundation.Test.WebApi.TestExecutionServiceCommand] <GetCommand>b__0(), Exception: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

Here is my environment variables:
![image](https://user-images.githubusercontent.com/43071948/47654078-132b2600-db58-11e8-8dac-ed122816cd7b.png)

What build of the vsts agent is the fix in? Is it available yet?

**Comment by kaadhina** [comment]
Sorry, I did not realize that the version you have already has the retry logic I was talking about. The logs also show that it retried and then still failed again.
This vsts_http_timeout value is currently not honoured by vstest task. But I will log a bug at our end (but please note that it will be picked up based on priority).

Is the network unreliable? If it is specific to a particular agent, you can try to eliminate it from the pool. The call that is failing for you is a high frequency call and will require the network to be reliable.

**Comment by NDDeveloper13** [comment]
After a few days of running, it has happened on several of the machines in the pool, and removing them is not an option. I have the network team helping to look into the issue, but so far, they are not able to see anything on our end to explain why this would be happening.

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 please re-open you if you still facing the issue.

**Comment by JoseGeraldino** [comment]
It seems that a Microsoft server is down, the tests are trying to consume a service in the IP: 13.107.42.18:443
