### ISSUE TITLE
PublishBuildArtifacts should support recursive artifact inclusion

### ISSUE THREAD

**Issue by cdmihai** [microsoft/azure-pipelines-tasks#8719]
Either by a separate `Recursive` task argument, or by making `PathtoPublish` support wildcards: `PathtoPublish: 'artifacts/Debug/log/**/*'`

**Comment by bryanmacfarlane** [comment]
Copy has supports wildcards and then you can publish the result of that.

**Comment by cdmihai** [comment]
True, there's workarounds, but the experience could be better by not having to do the workarounds.

**Comment by ling1726** [comment]
I have just tested this on my pipeline, it copies subdirectories too, so that should mean that it is recursive right?

**Comment by carlos-quintero** [comment]
Certainly support for wildcards would be great so the Copy task is not required
