### ISSUE TITLE
Failed to fetch Kudu App Settings. Error: Error: Request timeout: /api/settings

### ISSUE THREAD

**Issue by johnknoop** [Microsoft/azure-pipelines-tasks#8723]
I have an "Webapp for containers" that is updated from VSTS. Every third or forth time, it fails with this error message:

> Failed to fetch Kudu App Settings. Error: Error: Request timeout: /api/settings

I'm not sure if the problem lies with VSTS or with Kudu, though?

**Comment by vincentdass** [comment]
@johnknoop , thanks for reporting the issue.
We have added retry for this transient issue. Can you please set variable `system.debug` to `true` in your release definition? This will enable the debug mode. Share the logs once the release failed.

**Comment by johnknoop** [comment]
@vincentdass sure, I'll do that. I'll let you know the next time this occurs.

**Comment by vincentdass** [comment]
Closing the issue. Please feel free to reopen / create a new thread if required.
