### ISSUE TITLE
DotNetCoreCLIV2: Add support for generating migration scripts

### ISSUE THREAD

**Issue by pekspro** [Microsoft/azure-pipelines-tasks#8729]
## Environment
- Server - Azure Pipelines 

## Issue Description

I’m having an ASP.NET Core application with EF Core with a “code first” database context. To be able to migrate databases with Azure pipelines migration scripts must be generated.

I know I could use the **dotnet custom** option with **ef** as a command and arguments like:

    migrations script --idempotent --project $(Build.SourcesDirectory)\MySolution\MyProject\MyProject.csproj --output $(build.artifactstagingdirectory)\migrations\MyDatabaseContextMigrations.sql --context MyDatabaseContext

But it’s a bit tricky to figure out, at least if you are a newbie like me :-). I would like to see a specific command for this, I guess this is quite common.

**Comment by bryanmacfarlane** [comment]
This seems like a good task / extension that someone should write and release in the market place.  azure-pipelines-task-lib repo has details on how to create one.

**Comment by pekspro** [comment]
I wrote this an extension myself :-) Here it is:

https://marketplace.visualstudio.com/items?itemName=pekspro.pekspro-efcore-migration-script-generator

**Comment by anuragc617** [comment]
Closing this issue, as the extension has been added to marketplace.
