### ISSUE TITLE
Azure SQL Daptabase Deployment: Task.uploadFile cmdlet is not working with Hosted VS 2017

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/azure-pipelines-tasks#8741]
## Environment
- Server - Azure Pipelines
- Agent - Hosted Agent (Hosted VS2017)

## Issue Description
Task : Azure SQL Database Deployment (Action : Export)
The Azure SQL Database Deployment task is failing. The export of an Azure Database. seems to work fine, the bacpac file is correcty saved to GeneratedOutputFiles folder but the when the task is "uploading files to the logs" an error occurs. 

The same build with the same parameters on the same database worked perfectly the days before, could it be a storage space issue ?

![issue](https://user-images.githubusercontent.com/15186176/47779483-7c966a80-dcf9-11e8-92cd-8d2018dc658a.png)

### Task logs

Debug logs of the Azure SQL Daptabase Deployment task.
[logs.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2533601/logs.txt)

### Error logs
Unable to process command '##vso[task.uploadfile] D:\a\1\s\GeneratedOutputFiles\********-int.bacpac' successfully
Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk 
at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskAddAttachmentCommand(IExecutionContext context, Dictionary`2 eventProperties, String data) 
at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)

**Comment by evolve700** [comment]
This does not only effect Hosted VS 2017 environments. I encounter the same problem on my custom build machine.

Non-debug log:
[azuresql.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2598996/azuresql.log)

The file appears to be created correctly, it's just the upload that fails.

**Comment by evolve700** [comment]
Had to delete my previous comment because the log was not redacted correctly.
Still, I too tncounter this issue on my own privately hosted build machine. The exact same error occurs. Here's the non-debug log:
[azuresql.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2599026/azuresql.log)

**Comment by TingluoHuang** [comment]
@TechWatching try remove the write space in your ##command

`##vso[task.uploadfile] D:\a\1\s\GeneratedOutputFiles********-int.bacpac` to `##vso[task.uploadfile]D:\a\1\s\GeneratedOutputFiles********-int.bacpac`

**Comment by TechWatching** [comment]
I am using the visual designer for my build so I have no control on this. The command you are mentionning is a command done by the "Azure SQL Database Deployment" task. I only can see the logs.

**Comment by bryanmacfarlane** [comment]
@kmkumaran - this seems scoped to the azure sql task.  task.upload file is working fine

**Comment by Ajay-MS** [comment]
Closing as this issue has been fixed. 

PR - https://github.com/Microsoft/azure-pipelines-tasks/pull/9268

It will be deployed with next deployment. ETA - 3 to 4 weeks approx.

**Comment by older** [comment]
I get the same error. It could be a coincidence but I suspect that this happens when database name contains dach character ("-").

**Comment by robdavey555** [comment]
_Note: My database name does not use "-"_

I have an issue with the Export function. Extract works fine but I need to use export so I get my data.

This is my log

![image](https://user-images.githubusercontent.com/6249241/52807726-3a185400-3084-11e9-9e4c-30d70dc6abcb.png)

This is the step in my release pipeline

![image](https://user-images.githubusercontent.com/6249241/52807802-6fbd3d00-3084-11e9-802d-afabba3a0b29.png)


I have compared the Extract and Export functions in SqlAzureActions.ps1 and cannot spot any reason why Extract would work but Export would fail.

Any suggestions?

**Comment by robdavey555** [comment]
@arjgupta Is there any update on this issue. Do you need any additional info from me?

**Comment by arjgupta** [comment]
@robdavey555 , this was fixed with this PR: https://github.com/Microsoft/azure-pipelines-tasks/pull/9670 . The fix will be deployed next week.

**Comment by arjgupta** [comment]
@robdavey555 , are you using Team Foundation Server ? You seem to have an older version of the task which does not have the fix for this issue.

**Comment by robdavey555** [comment]
@arjgupta   - I am using an Azure Devops (VSTS) pipeline. This issue seems to be resolved now so must have been fixed elsewhere. Thank you.
