### ISSUE TITLE
PublishCodeCoverageResults should support .coverage files

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/azure-pipelines-tasks#8750]
## Environment
- Server - Azure Pipelines

## Issue Description

The `PublishCodeCoverageResults` task does not currently support Visual Studio `.coverage` files. I use Cake Build instead of the built in tasks and want to use `PublishCodeCoverageResults` to publish my code coverage results.

**Comment by xenalite** [comment]
A thousand times yes! This issue was raised before and never made sense to me. VSTest task somehow manages to publish .coverage files that VSTS understands - so we should be able to do it as well!
