### ISSUE TITLE
Test results no longer being written to Common.TestResultsDirectory

### ISSUE THREAD

**Issue by cawhitworth** [Microsoft/azure-pipelines-tasks#8751]
## Environment
- Server - Azure Pipelines
- Agent - Private: 
    - Windows Server 2016, 

## Issue Description

Up until earlier today, test results were written to Common.TestResultsDirectory at the end of a test run:

`2018-11-01T06:00:31.0753091Z COMMON_TESTRESULTSDIRECTORY=d:\agent1\_work\256\TestResults`
[...]
`2018-11-01T06:04:18.8638163Z Results File: d:\agent1\_work\256\s\TestResults\vstsagent.REDACTED.trx`

but now they seem to be written to a temp location:

`2018-11-01T08:58:56.6653840Z COMMON_TESTRESULTSDIRECTORY=D:\agent1\_work\696\TestResults`
[...]
`2018-11-01T09:03:15.2215074Z Test results files: D:\agent1\_work\_temp\TR_5881df86-93cd-4685-ba6c-149636a04072\vstsagent.REDACTED.trx`

**Comment by cjfarrelly** [comment]
I have the same issue, the _temp folder appears to be cleared down at the end of each task also so it's not possible to add a task to copy the trx files to the correct directory.

Also this only appears to be an issue when the tests are being ran in batches of N size or batched by assemblies.

I have also tried specifying the ResultsDirectory in a codecoverage.runsettings file but the vstest task is prepending that with the path of the _temp folder everytime.

Any updates on this?

**Comment by cltshivash** [comment]
The vstest task takes care of publishing the results and the directory where it writes the result is internal and other tasks can't take a dependency on it.

**Comment by pheonixvijay** [comment]
@cawhitworth This issue can be solved by setting the run setting file with following 

`​<RunConfiguration>
 <ResultsDirectory>%AGENT_BUILDDIRECTORY%</ResultsDirectory>
</RunConfiguration>`

When you set this, the VSTest Console honors it and writes the output to AGENT_BUILDDIRECTORY/TestResults, which is Common.TestResultsDirectory

Hope this helps

**Comment by cocowalla** [comment]
@pheonixvijay won't that mess with local test runs?
