### ISSUE TITLE
The term 'Warn-IfCertificateNotPresentInLocalCertStore' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by teruobr** [Microsoft/azure-pipelines-tasks#8753]
## Environment
- Server - Azure Pipelines 

- Agent - Private: 
   
    - Win10, latest agent version

## Issue Description
I've created a new service fabric cluster and cloned the build and release for this new cluster.
I've installed sf cluster certificated and configured in project settings.
As I try to run Service Fabric Application Deployment task, It connects to the cluster but I receive the following error.
##[error]The term 'Warn-IfCertificateNotPresentInLocalCertStore' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Couldn't find anything about it.

The old/original build/release tasks are running without any errors.

The only difference between the clusters is that the original is 1-node and the new one is 5-node.

### Error logs
##[error]The term 'Warn-IfCertificateNotPresentInLocalCertStore' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mike7ang1rdz** [comment]
I need to release to production environment, can you rollback to the previous version?

**Comment by teruobr** [comment]
I've lost almost all day of work trying to find a solution for this

**Comment by Abdruggi** [comment]
There you go https://github.com/Microsoft/azure-pipelines-tasks/pull/8740/files

**Comment by bishal-pdMSFT** [comment]
This has been fixed.

**Comment by teruobr** [comment]
It is now working with the new azure-pipelines-task fix.
thanks
