### ISSUE TITLE
'Warn-IfCertificateNotPresentInLocalCertStore is causing an error in the release pipeline when using a service connection.

### ISSUE THREAD

**Issue by KevinHaisol** [Microsoft/azure-pipelines-tasks#8754]
_Originally posted by @KevinHaisol in https://github.com/Microsoft/azure-pipelines-tasks/pull/8632/comment#issuecomment-435135402_

**Comment by KevinHaisol** [comment]
Never-mind, I had a bug. its working....

**Comment by teruobr** [comment]
what kind of bug did you have?
I'm having this issue with a new release I've created and an older release that was running ok yesterday.

**Comment by KevinHaisol** [comment]
The bug was caused by errors in the application and service manifests.  I tried publishing to the cluster locally and saw the bugs and was able to fix them and then it worked on the DevOps site.
