### ISSUE TITLE
Publish code coverage error when using  Hosted Ubuntu 1604

### ISSUE THREAD

**Issue by juwitaw** [microsoft/azure-pipelines-tasks#8762]
## Environment
- Hosted Agent: Hosted Ubuntu 1604

## Issue Description
Task: Publish Code Coverage Results
When I saw the plan about Hosted Linux Preview that will remove from Azure Pipelines on December 1, 2018.​ I change all my build pipeline agent to Hosted Ubuntu 1604 but "Publish code coverage" task not publishing code coverage report. While code coverage report publish success when using Hosted Linux Preview.
Below is the behavior I test with same commit, same build pipeline, same task on Hosted Linux Preview and Hosted Ubuntu 1604. 
### Expected Behavior
- No warning on log
- Publish success like when using Hosted Linux Preview like below,
![linux](https://user-images.githubusercontent.com/17060491/47894382-22caa780-de95-11e8-8ecf-052c5c654206.jpg)

![screenshot from 2018-11-02 10-51-06](https://user-images.githubusercontent.com/17060491/47894402-3b3ac200-de95-11e8-9fef-9754a11dd185.png)
 
### Actual Behavior
- Warning on task
`##[warning]Error occurred while publishing code coverage files. Error: Access to the path '/home/vsts/work/1/s/coverage/summary1818' is denied.`
- Code coverage result not published

![ubuntu](https://user-images.githubusercontent.com/17060491/47894448-73420500-de95-11e8-986e-8a09e2b279bc.jpg)
![screenshot from 2018-11-02 11-17-12](https://user-images.githubusercontent.com/17060491/47894392-2fe79680-de95-11e8-9293-a6f25f38dddb.png)
![screenshot from 2018-11-02 11-03-49](https://user-images.githubusercontent.com/17060491/47894455-7e953080-de95-11e8-8ad1-8d86e73b96b1.png)

**Comment by juwitaw** [comment]
> I am facing the exact same issue with the publishing of the artifacts. As a temporary workaround I introduced a step prior to the publishing step to grant permissions (with `chmod`)

@uabbas I have already create one shell script task contains `chmod 777 . -R` before publish coverage task but still failing. Can you show me how you can successfully publish the artifact without permission error?

**Comment by drcrook1** [comment]
I'm having same exact problem.  2018-12-14T01:00:42.6237202Z ##[warning]Error occurred while publishing code coverage files. Error: Access to the path '/home/vsts/work/1/s/junit/cov_html/summary214' is denied.

I can see coverage summary on summary page; but not the html outputs.

**Comment by nigurr** [comment]
@drcrook1 @juwitaw @uabbas Can you please check is it sill happening.
We just tried to repro the issue, seems like working fine

![image](https://user-images.githubusercontent.com/15208679/50439693-f4a79800-0918-11e9-8772-63ed2b13644a.png)
![image](https://user-images.githubusercontent.com/15208679/50439706-fec99680-0918-11e9-8755-dca7e7232268.png)

**Comment by juwitaw** [comment]
![image](https://user-images.githubusercontent.com/17060491/50440432-d5b10200-0928-11e9-92ac-95564a68e727.png)
 Just now I tried again and still have the same problem. Is there any config I should change?

**Comment by nigurr** [comment]
@juwitaw Please look into sample here: https://dev.azure.com/dtatestingint/Public%20Samples/_build/results?buildId=7032&view=logs

**Comment by juwitaw** [comment]
I read you example-java-maven/azure-pipelines.yml and I think It's the same like my configuration yet I'm still facing `[warning]Error occurred while publishing code coverage files. Error: Access to the path '/home/vsts/work/1/s/coverage/summary2378' is denied.` problem. I'm using visual designer like this:
![image](https://user-images.githubusercontent.com/17060491/50510804-b0093180-0abd-11e9-9b55-073a30fd2798.png)

**Comment by nigurr** [comment]
@madhurig Can you please help on this?

Temporarily you can mitigate by changing permissions as suggested.

**Comment by juwitaw** [comment]
It turns out that I need to use `sudo` when changing permission. That's why it failed when I only using `chmod 777 . -R`.
As temporary, I think I can add this permission command on my task.

**Comment by madhurig** [comment]
A fix has been made on the Hosted Ubuntu VMs, it will be deployed to all regions approximately by April 1st week. The workaround will no longer be needed after that. Thank you for your patience.

**Comment by ardalis** [comment]
Still seeing this error today:
`vmImage: 'ubuntu-16.04'`

![image](https://user-images.githubusercontent.com/782127/63191229-02d82f00-c036-11e9-849c-cb556efdab9e.png)

See actual public build output here: 
https://dev.azure.com/Ardalis-Specification/Ardalis.Specification/_build/results?buildId=47&view=logs

**Comment by ardalis** [comment]
None of the chmod or mkdir workaround posted here or in related issues is working for me. My complete project including azure-pipeline.yml is here:
https://github.com/ardalis/Specification/tree/ardalis/integrationtests

@madhurig is this supposed to be fixed now? Thanks for any assistance.

**Comment by ShreyasRmsft** [comment]
@madhurig @shadyysf I was able to get a repro. Was not even able to list the permission on the file https://shrer.visualstudio.com/Ubuntu%20coverage/_build/results?buildId=125

Seems like a an issue with the image.

**Comment by ardalis** [comment]
Any update on this? A workaround idea? I'd like to get my code coverage results published for this build/project and this is blocking me right now. Thanks!

**Comment by FedeBenitez** [comment]
I'm having the same issue trying to create access $(Common.TestResultsDirectory) to save test results. Neither chmod or mrkir workarrounds worked. Also tried on Ubuntu 16.04 and 18.04 but no luck.

**Comment by joferrao** [comment]
Still happening.

**Comment by G-Rath** [comment]
I've hit this today:

> Failed to parse result files: System.UnauthorizedAccessException: Access to the path '/home/vsts/work/1/s/test-cucumber.xml' is denied.

```
- bash: bundle exec cucumber --format progress --format junit --out test-cucumber.xml
  displayName: Running cucumber specs
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Cucumber tests'
```

This is using `ubuntu-latest`.
