### ISSUE TITLE
StorageContainerUrl is now appending forward slash in the end "/"

### ISSUE THREAD

**Issue by hassant** [Microsoft/azure-pipelines-tasks#8768]
## Troubleshooting
Azure File Copy V2 task's output variable SotrageContainerUrl is now returning the uri with a forward slash appended to it:
https://random123.blob.core.windows.net/0.1.0+5678/
instead of previously:
https://random123.blob.core.windows.net/0.1.0+5678

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines

- Agent - Hosted or Private: 
   - VSTS Hosted Agent

**Comment by kmkumaran** [comment]
@hassant this was added by #8492 . Is this causing any problem in your case? @Ajay-MS

**Comment by vincentdass** [comment]
closing the issue as there is no response from customer.
