### ISSUE TITLE
Azure Swap is using "Swap with Preview"

### ISSUE THREAD

**Issue by cdwaddell** [Microsoft/azure-pipelines-tasks#8773]
Server - Azure Pipelines
   
As of this morning, this appears to be swapping with preview turned on. This causes our swap to hang waiting for someone to complete the swap. When investigating in Azure Portal we are prompted to approve or cancel, but neither option works. They both fail due to another operation. According to Azure support, this will not timeout because timeout is also set to 0.

We use continuous integration, so QA apps are hosed. Any help would be greatly appreciated.

**Comment by youngcm2** [comment]
Same issue.

**Comment by youngcm2** [comment]
Do you know when this will be released?

**Comment by cdwaddell** [comment]
We are finally able to cancel our swap operations. I am now able to deploy from VSTS using the same pipeline that was failing on Friday.

**Comment by vincentdass** [comment]
@cdwaddell , @youngcm2 , Can you please check the activity logs of the App Service in portal? App Service Manage task doesnt make 'swap with Preview'.
Also, it would help us, if you can provide `Azure Devops logs to investigate.
