### ISSUE TITLE
Cocoapods version selection

### ISSUE THREAD

**Issue by jbehrens94** [microsoft/azure-pipelines-tasks#8786]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
        Hosted macOS 

## Issue Description

Cocoapods task, pod install.
I'd like to be able to specify a CocoaPods version. Currently, my build pipeline is broken due to a CocoaPods bug. Therefore I request an additional setting in the CocoaPods step: version.
The use case is that I can then specify the latest beta release from CocoaPods.

### Task/Error logs

`/Users/vsts/agent/2.141.1/work/1/s/Pods/Target Support Files/Pods-.../Pods-...-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable`

This is fixed in CocoaPods 1.6.0.beta.1 but that version is not available on the build pipeline.

**Comment by jbehrens94** [comment]
Bump

**Comment by nguyenlamlll** [comment]
Hi, I've run into the same problem and here's my workaround to `specify` a CocoaPods version.

Create a script task of the type you prefer. Here I create a Powershell script task. Uninstall the current version and install a desired one.
```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      gem uninstall cocoapods
      gem install cocoapods -v 1.8.1
```

**Comment by Saigronas** [comment]
> Hi, I've run into the same problem and here's my workaround to "specify" a CocoaPods version.
> 
> Create a script task of the type you prefer. Here I create a Powershell script task. Uninstall the current version and install a desired one.
> 
> ```
> - task: PowerShell@2
>   inputs:
>     targetType: 'inline'
>     script: |
>       gem uninstall cocoapods
>       gem install cocoapods -v 1.8.1
> ```

This is still relevant in 2024. 

Azure pipelines 'macOS-latest' hosted agents started using cocoapods v 1.15.0, which broke pod install. This workaround saved us from having to wait for Azure to start using a later version which fixes the problem

**Comment by matiaswastaken** [comment]
> > Hi, I've run into the same problem and here's my workaround to "specify" a CocoaPods version.
> > Create a script task of the type you prefer. Here I create a Powershell script task. Uninstall the current version and install a desired one.
> > ```
> > - task: PowerShell@2
> >   inputs:
> >     targetType: 'inline'
> >     script: |
> >       gem uninstall cocoapods
> >       gem install cocoapods -v 1.8.1
> > ```
> 
> This is still relevant in 2024.
> 
> Azure pipelines 'macOS-latest' hosted agents started using cocoapods v 1.15.0, which broke pod install. This workaround saved us from having to wait for Azure to start using a later version which fixes the problem

Hi @Saigronas, currently also running into same issue on Azure Pipelines where pod install fails due to version 1.15.0 of cocoapods. Did you use this script and just do 'gem install cocoapods -v 1.15.2' to work around it?

**Comment by clough360** [comment]
The issue still persists with the default 1.15.0, but is working fine with 1.15.2:

```
- task: PowerShell@2
  displayName: Install specific cocoapods version
  inputs:
    targetType: 'inline'
    script: |
      gem uninstall cocoapods
      gem install cocoapods -v 1.15.2
```
