### ISSUE TITLE
Request/Question - Update version of AzureRm module

### ISSUE THREAD

**Issue by IanMoroney** [Microsoft/azure-pipelines-tasks#8801]
Azure Devops - Hosted Agents

I appreciate that this may not be one for this github but wanted to know more about this process and if there's anything the community can do to contribute.
The current latest version of AzureRM to select is 6.7 (3 months ago).
I have some features i'd like to use which were released in 6.9 (1 month ago), and i'm also conscious of the fact that 6.12 is now out (yesterday).

Are you dependent on these versions being made available inside the hosted agent itself? 
If so, how do you detect what versions are available?
How can we contribute towards checking what versions are available in the build agent, and issuing a PR to get them added to this task?

On another note, if you happen to know:
Is it possible for the community to contribute towards what versions of powershell are available in the hosted agent?

Thanks

**Comment by jfindlay** [comment]
May be relevant: `AzureRM` is [getting deprecated](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-6.12.0) in favor of the [`Az` CLI](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azurermps-6.12.0#the-future-of-support-for-azurerm).

From AzureRM:
> After November 2018, there will be no new features or cmdlets added to the AzureRM module. AzureRM will continue to be supported and receive bugfixes. New features will be provided in the Az module, which will reach 1.0 at the same time. Az has a backwards compatibility mode with AzureRM, and is designed to be easy to switch to. [...]

From Az:
> ### The future of support for AzureRM
> The existing AzureRM module will no longer receive new cmdlets or features when Az version 1.0 is released in December 2018. However, AzureRM is still officially maintained and will get bug fixes. To keep up with the latest Azure services and features, you should switch to the Az module.

**Comment by kmkumaran** [comment]
@jfindlay - Thanks for sharing. We are aware of this change and are working to update the hosted agent with appropriate Az modules. We will keep this thread posted once the image is updated.

**Comment by kmkumaran** [comment]
@IanMoroney - At this point, we don't have a mechanism for community to contribute to hosted agent version. In case you need a Azure PS version that is not pre-installed in the hosted, you should be able to do install-module of that specific version using a PS script and consume it.

**Comment by bryanmacfarlane** [comment]
Our hosted images are open sourced here:  https://github.com/Microsoft/azure-pipelines-image-generation

We take contributions and images go out monthly

**Comment by kmkumaran** [comment]
The work is currently in progress. It will be likely two sprints before we have the Az module support in relevant tasks and hosted agent and have it ready for users. @niadak will keep this thread posted once ready.

**Comment by jurajsucik** [comment]
any news about the expected date?

**Comment by 20shivangi** [comment]
It will be done by end of February

**Comment by 20shivangi** [comment]
Az module is being supported in Azure Powershell V4 task . You can try and let us know if it is working fine.
