### ISSUE TITLE
Impact of Deployment mode: 'Complete' could be huge and should have a better waring

### ISSUE THREAD

**Issue by StannieV** [Microsoft/azure-pipelines-tasks#8810]
Last week I've used the 'Complete' setting of the Deployment mode in the Azure Resource Group Deployment template with the result that 100+ Azure resources got deleted in our resource group leading to a major disaster in our company. This was clearly not my intention! My intention was to update a FunctionApp and remove unused resources within my FunctionApp.

I would like to suggest a change of the supplied information regarding this 'complete' option. Now it states: '_Complete mode deletes resources that are not in your template._'. I think it would be better if there is a warning included that states that all other resources in the resource group that are not included in the deployment will be deleted with this action.

**Comment by kuvinodms** [comment]
@puagarwa - Can you please provide your opinion over here.

**Comment by kuvinodms** [comment]
@StannieV 
We've made the possible changes and will roll it out in next release. Thanks for the feedback.

**Comment by StannieV** [comment]
Thank you!
