### ISSUE TITLE
HttpRequestChain not working?

### ISSUE THREAD

**Issue by accoleon** [Microsoft/azure-pipelines-tasks#8813]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - coeisdcore.visualstudio.com, InternalPlatform, EV Release, Get CAB Approval Gate

- Agent - Private, Win10 x64 "NetCore"
However, the issues lie with the custom Gate.

## Issue Description
I've been attempting to replicate a "Create and Query" gate for use in our Change Management process, and I've following the general structure used in the[ AzurePolicyV0 task](https://github.com/Microsoft/azure-pipelines-tasks/blob/6381b65527fad9acb5f0b9d000d2c6fddf29da8f/Tasks/AzurePolicyV0/task.json). However, it seems like my gate will always pass - it runs the first RequestInput in the chain, but never seems to run or fail on the second (where it tries to query)

In the first request of the chain, it sends a POST to create a new change request, and the API returns a cr number. I try to store the variable in 'CR' (following AzurePolicyV0's ExecutionsOptions: OutputVariables template). Similarly, it has a SkipSectionExpression to skip this step if the 'CR' variable is nullorEmpty.

However, it never seems to skip this step and try to run the second step (a GET query). Instead, on first evaluation of the gate, it creates the CR successfully, and on the next evaluation, it creates a new CR instead of skipping that step.

**Comment by bansalaseem** [comment]
@accoleon, can u please paste the execution section of your task as well as attach the logs of a run?

**Comment by accoleon** [comment]
Unfortunately, it has been awhile and I no longer have access to the code repository.
