### ISSUE TITLE
Helm task using old client version on new *Hosted Ubuntu 1604* pool

### ISSUE THREAD

**Issue by eryabitskiy** [Microsoft/azure-pipelines-tasks#8827]
## Environment
- Server - Azure Pipelines or TFS on-premises?
    Cloud version. Azure DevOps. Azure Pipelines

- Agent - Hosted or Private: 
    Hosted: **Hosted Ubuntu 1604** pool

## Issue Description

After upgrade to **Hosted Ubuntu 1604** pool from **Hosted Linux Preview** pool  (which claimed to be deprecated), our helm deploy fails with error about old Helm client version installed on Hosted agent.
Version on agent is **v2.10.0-rc.3**. Which seams to be not even stable release (it is just release candidate).

While "deprecated" **Hosted Linux Preview** pool is already using last stable version of Helm client: v2.11.0

### Task logs

> Task         : Package and deploy Helm charts
> Description  : Deploy, configure, update your Kubernetes cluster in Azure Container Service by running helm commands.
> Version      : 0.138.6
> ##[error]Error: UPGRADE FAILED: incompatible versions client[v2.10.0-rc.3] server[v2.11.0]

### Error logs

> ##[error]Error: UPGRADE FAILED: incompatible versions client[v2.10.0-rc.3] server[v2.11.0]

**Comment by ds-ms** [comment]
@eryabitskiy you could use a `helm installer` task before executing your helm commands. This would ensure the version of helm before every run.

**Comment by ds-ms** [comment]
Updated the version here: https://github.com/Microsoft/azure-pipelines-image-generation/pull/363
