### ISSUE TITLE
Feature request: Gradle and Maven push to VSTS private package server via task

### ISSUE THREAD

**Issue by dhanvi** [microsoft/azure-pipelines-tasks#8828]
## Issue Description
Nuget push currently can be configured to push to Azure DevOps (VSTS) private package server (Artifacts) directly via the option target feed location and selecting the target feed location. (Below is the image)
![image](https://user-images.githubusercontent.com/6671379/48416204-8c8c6080-e775-11e8-88a0-16e913d8b87e.png)

It would a nice feature for gradle and maven task todo the same. We can achieve the same using PAT, but PAT's requires maintenance and service accounts.

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!
