### ISSUE TITLE
Azure Keyvault Task output overwritten

### ISSUE THREAD

**Issue by dodsminister** [Microsoft/azure-pipelines-tasks#8829]
Hi,

We have a task group that includes an Azure Key Vault task. This produces two variables. Lets call them $(a) and $(b). In the next task we use them as parameters for a PowerShell script ( -a $(a) -b $(b) ). 

When creating a task group, $(a) and $(b) become task group parameters and require a default value. When given that, the Azure Key Vault-task is no longer able to write to them, or perhaps parameters are reset to their default values before initiating the next task. Either way, this is a problem for us.

Is there a known work around?

**Comment by dodsminister** [comment]
I found a workaround for this:

I put $(a) and $(b) as values for Environment Variables for the dependant script and accessed the through env:. Ie:

name: varA
value: $(a)

and in script:
`$aInScript = $Env:varA`

**Comment by WolfyUK** [comment]
The following article helped me resolve this issue. Essentially, export the .json from the task group, customise the `defaultValue` and `visibleRule` and then import back again.

- https://medium.com/objectsharp/how-to-hide-a-task-group-parameter-b95f7c85870c

e.g.
```diff
{
  "aliases": [],
  "options": {},
  "properties": {},
  "name": "PIPELINE_PAT",
  "label": "PIPELINE_PAT",
- "defaultValue": "",
+ "defaultValue": "$(PIPELINE_PAT)",
  "required": true,
  "type": "string",
  "helpMarkDown": "Add the PAT with API Access to your Release.",
+ "visibleRule": "1 = 2",
  "groupName": ""
}
```
