### ISSUE TITLE
Problem when using Azure File Copy - some targets do not meet all task demands

### ISSUE THREAD

**Issue by twentytwokhz** [Microsoft/azure-pipelines-tasks#8846]
The file here containing the code for **AzureFileCopy** task contains a demands section for "**azureps**"
https://github.com/Microsoft/azure-pipelines-tasks/blob/d7c1bb32ca5772d34234a6f22ace61619cad87a9/Tasks/AzureFileCopyV1/task.loc.json

what is **azureps**? how can i **enable** it on my vm?
currently i'm unable to make a deployment because of this warning on my deployment target group.

I have a deployment target group linked to an Azure VM Ubuntu 18.04 machine via the azure portal **continuous delivery (preview)**
The machine is healthy but when creating the release pipeline and adding a deployment target group agent with an **Azure File Copy** task and completing all information, it shows a warning - see photo below

![capture](https://user-images.githubusercontent.com/15191469/48555014-a00c0880-e8e8-11e8-820c-8204ddf31a5c.PNG)

Some targets do not meet all task demands.

**Comment by twentytwokhz** [comment]
Please help me or throw in some ideas regarding this

**Comment by asranja** [comment]
azureps represents the Azure PowerShell version on the agent. Currently the Azure File Copy task can only be run on Windows VMs. You need to configure an agent on a Windows VM and install Azure PowerShell on it to meet the task demands. You can install it from an msi [here](https://github.com/Azure/azure-powershell/releases).

**Comment by twentytwokhz** [comment]
Then what other task option is there to deploy an artifact to an ubuntu vm from azure devops?

**Comment by rajatagrawal-dev** [comment]
@twentytwokhz Please refer issue #8920 for upcoming support and workaround recommendation.
Please post further questions on that thread itself.
