### ISSUE TITLE
Windows File Copy v2 error "]The term 'Try-CleanupPSDrive' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

### ISSUE THREAD

**Issue by bradwilliamson** [Microsoft/azure-pipelines-tasks#8849]
This error just started happening in the past day or two for our release tasks using the Windows File Copy Task.  I'm having to find a work around since this is breaking the CI/CD process. I've rebooted the build servers and web boxes in Dev. Nothing seems to be working. 

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
petalsinternational
petalsweb
release # 
Release-122

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Windows 2012 
2.127.0

## Issue Description

[Include task name(s), screenshots and any other relevant details]
![image](https://user-images.githubusercontent.com/13142011/48565278-ce282300-e8bd-11e8-99dc-fa2c986ca8e9.png)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by plraustin** [comment]
+1 - This started happening for us as well - Urgent Issue.

**Comment by bradwilliamson** [comment]
@plraustin As a work around I disabled the existing SMB based task & started using WinRM Windows File Copy release task. After getting firewall rules in place from the build server to the web servers.

**Comment by plraustin** [comment]
Another work-around for us has been to revert to 1.0 version of the task.

Continue on error option might work since it seemed to be a cleanup activity – but I’m not sure.


Rob

**Comment by alexwiese** [comment]
Started happening for us today - version of the Windows Machine File Copy task is 2.1.8.
Yesterday 2.1.5 was working fine.

**Comment by alexwiese** [comment]
Looks like #8820 is the breaking PR

**Comment by chshrikh** [comment]
we are checking this issue

**Comment by chshrikh** [comment]
we identified the issue working on fix. Mean while to get unblock, please uncheck the option of "Copy Files in Parallel". Sequential file copy to targets is working fine.

![image](https://user-images.githubusercontent.com/11972852/48597680-047ca580-e985-11e8-8094-bfa1bb742db5.png)

**Comment by chshrikh** [comment]
this has been fixed now

**Comment by nazarsh** [comment]
@chshrikh I might be wrong, but having unchecked the Copy Files in Parallel as a workaround and leaving that unchecked ended up causing issues where first host copy is successful, but second one fails with `Failed to Create PSDrive with Destination`. Checking the "Copy Files in Parallel" resolved the issue, but those not using the parallel copy might encounter an issue.
