### ISSUE TITLE
YAML pipeline that referencing variable in variable group show invalid error messages when you View YAML in the portal.

### ISSUE THREAD

**Issue by rguthriemsft** [Microsoft/azure-pipelines-tasks#8853]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
Azure pipeline with the following YAML.  ACRName is a variable defined in a linked variable group.  Pipeline runs fine but when I select View YAML I get the **two warnings** at the top that appear to be invalid.

resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
**#Your build pipeline references an undefined variable named ‘ACRName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘ACRName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972**
steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'zddDemo-Boston'

    azureContainerRegistry: <myacr>.azurecr.io

    dockerFile: apis/trips/Dockerfile

    imageName: '$(ACRName)/repo/api-trip:$(Build.BuildId)'

- task: Docker@1
  displayName: 'Push Image'
  inputs:
    azureSubscriptionEndpoint: '<endpoint>'

    azureContainerRegistry: <myacr>

    command: 'Push an image'

    imageName: '$(ACRName)/repo/api-trip:$(Build.BuildId)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: helmChartTrips'
  inputs:
    PathtoPublish: apis/trips/helm

    ArtifactName: helmChartTrips

    

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Ubuntu 1604

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Azure pipeline with the following YAML.  ACRName is a variable defined in a linked variable group.  Pipeline runs fine but when I select View YAML I get the **two warnings** at the top that appear to be invalid.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by rguthriemsft** [comment]
You are correct, I created a pipeline in the visual designer and this is the YAML export.  The message and the links don't seem to lead me to a solution and hence I opened the issue.  Not sure if this is an issue with the export or the error message but I feel this could be more clear to the user.  Hope this perspective helps.

**Comment by bryanmacfarlane** [comment]
Not an issue with task in this repo.  If you have further feedback azure-pipelines-yaml repo might be better

**Comment by mcharo** [comment]
Old and dead issue, but for the fellow googler, this seems to be an issue when you are doing string interpolation like:
```powershell
"$($env:TheYamlExportWillFlagThisVariableAsUndefined) but it's really fine"
```

Changing to something like the following seems to help whatever parser correctly figure out what's going on:
```powershell
'{0} and so will you' -f $env:TheYamlExportWillBeHappyWithThis
```
