### ISSUE TITLE
Cannot see my tasks version in Azure Dev Ops

### ISSUE THREAD

**Issue by lurumad** [Microsoft/azure-pipelines-tasks#8858]
Hi, 

Maybe this repo is not the best place to ask for this issue but it's related with tasks & Azure Dev Ops.

Recently I've developed a tasks for one of my customers and yesterday we released a new version. when my customers tried to install in his Azure Dev Ops:

![image](https://user-images.githubusercontent.com/1729519/48614390-6a215f80-e98e-11e8-864e-6b9c04334679.png)

We changed the category and we could install. But we have versioned our tasks and before Azure Dev Ops announcement we can choose different versions but actually we can only choose V1:

![image](https://user-images.githubusercontent.com/1729519/48614483-a654c000-e98e-11e8-900d-cd1892df2301.png)

![image](https://user-images.githubusercontent.com/1729519/48614495-af459180-e98e-11e8-8470-507da01d3e1a.png)

So, maybe you made another breaking change?

You can see other people have the same problem:

https://github.com/stephaneey/azure-apim-extension/issues/23

Regards!

**Comment by stephenmichaelf** [comment]
Could you email me the account name? stfrance at microsoft.com

**Comment by stephaneey** [comment]
@stephenmichaelf keep me in the loop as well please. For sure, MS made some breaking changes. The tasks are packaged exactly as described in the doc for a multi-version approach.

**Comment by stephenmichaelf** [comment]
@stephaneey Sorry for the issues, there was a bug introduced. A fix has gone in and started to roll out today(we block deployments during the holidays).

**Comment by bryanmacfarlane** [comment]
should be fixed
