### ISSUE TITLE
Proposal: Allow DotnetCLI Parameter Projects to be split by ;

### ISSUE THREAD

**Issue by glatzert** [microsoft/azure-pipelines-tasks#8860]
Task Groups provide a nice way to merge together things, that are occuring in the same order ever and ever again.
Unfortunately the DotNet CLI uses Multiline Variables, which are separated by "\n".
Task groups do not support multiline inputs, so to use the DotNetCLI Task in a task group, we need to build powershell scripts to split and set variables accodingly. This is a real bummer.

## Environment
TFS on-prem, Update 3
Private Agent

## Issue Description

https://github.com/Microsoft/azure-pipelines-tasks/blob/17f5788ae21cb98f59ec36d24d4ff581c1ec330f/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L25

This line of code is the culprit, that makes using DotnetCLI more difficult than it needs to be.
So I propose to split upon "\n" as well as ";" instead of "\n" only.

**Comment by anuragc617** [comment]
@pulkitaggarwl Can you please look into this enhancement ask.
