### ISSUE TITLE
Feature Request - AzureRmDeploymentV0

### ISSUE THREAD

**Issue by pckls** [microsoft/azure-pipelines-tasks#8880]
Hi,

Apologies if this is not the right place for this sort of request.

It is now possible to use ARM to deploy directly to Subscriptions, for example to create a [Resource Group](https://docs.microsoft.com/en-us/azure/azure-resource-manager/create-resource-group-in-template) or for [Azure Policy](https://docs.microsoft.com/en-us/azure/azure-resource-manager/deploy-to-subscription). It would be great if we could have an included task that is capable of performing these actions from Azure DevOps.

I haven't written a task before, but I'll take a look and see what I can do. If anyone is a wizard and gets to it before me, I'd be keen to see what differences needed to be made compared to the regular AzureResourceGroupDeploymentV2 task.

**Comment by kmkumaran** [comment]
@pckls  - We have Azure Resource Group task that can take the ARM template for deployment; https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2. Is this what you are looking for?

**Comment by RoopeshNair** [comment]
@pckls - Currently, AzureResourceGroupDeployment task supports deploying to a subscription. For subscription level deployments you need to use Azure PowerShell task that accepts an endpoint at ManagementGroup level. We will add the request to our backlog, no time lines at this point.

**Comment by pckls** [comment]
Thank you both for the responses.

@kmkumaran nope, I'm already using that one and while it can create the resource group, it's not able to manage the tags on that resource group.

@RoopeshNair that's exactly what I'm after. I know that I can use Powershell, and this is what I'm doing at the moment, but a task in Azure DevOps would be great.

**Comment by pingvishal** [comment]
@pckls you also mentioned about creating [Policies](https://docs.microsoft.com/en-us/azure/governance/policy/overview) through Azure DevOps - we have a template that can help get started quickly: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-policy?view=azure-devops 
if you have any suggestions around this area, we can discuss.
