### ISSUE TITLE
Task timeout no longer causes error/fail state

### ISSUE THREAD

**Issue by kenkuo** [Microsoft/azure-pipelines-tasks#8883]
## Environment

- Agent - Hosted or Private: 
    
    Private agent running on Ubuntu 16.04

## Issue Description

Currently we are seeing that task timeouts sometimes no longer fail the task. See examples below (tasks timing out at 25 minutes)

Task name: Docker (Run an image)
Issue: When the task times out with timeoutInMinutes specified, the task is marked as success (green) and moves on.
![actual](https://user-images.githubusercontent.com/5104436/48801443-04a4da00-ecd2-11e8-9882-9fd71f6430b7.png)

Expected: When the task times out, the task is marked as failed and throws error. 
![expected](https://user-images.githubusercontent.com/5104436/48801444-04a4da00-ecd2-11e8-9c50-e31d090dc16b.png)

**Comment by bryanmacfarlane** [comment]
Can you move this to azure-pipelines-agent repo?

**Comment by TingluoHuang** [comment]
@kenkuo if you check the log of that step, base on the timestamp in the log, what's exactly time does it take?

**Comment by bryanmacfarlane** [comment]
can't repro.  Add info and we can reactivate if needed
