### ISSUE TITLE
Build passes when it should fail for AzureResourceGroupDeployment@2

### ISSUE THREAD

**Issue by manojvazirani** [Microsoft/azure-pipelines-tasks#8884]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    Azure devOps
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I tried a build using the old repo and generated a yaml, and it failed as expected but with the new azure devops, when I use the same yaml, the build passes successfully:

Below **build fails** without yaml interface which is **correct**. Below is the generated yaml:

<img width="723" alt="screen shot 2018-11-20 at 11 54 52 am" src="https://user-images.githubusercontent.com/43583701/48801732-19d23680-ecdb-11e8-841e-d39e66d0e15a.png">

While the below **build passes** on the new azure devops with yaml which is incorrect as the input azuredeploy.json is incorrect and **build should fail** as seen above:

<img width="1055" alt="screen shot 2018-11-20 at 11 58 23 am" src="https://user-images.githubusercontent.com/43583701/48801770-353d4180-ecdb-11e8-8286-f4d9d3fb6834.png">

**Expected error:**

2018-11-20T16:41:45.6112562Z ##[error]Error: Ensure the Template file ( 'D:\a\1\s\azuredeploy.json' ) is valid. Task failed while parsing with following error: "Unexpected token { in JSON at position 1512" 2018-11-20T16:41:45.6191805Z ##[section]Finishing: Azure Deployment:Create Or Update Resource Group action on test03

Looks like an issue with:
**New YAML pipeline creation experience**

Please contact me with any other details needed for this issue.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by joshmgross** [comment]
Hey @manojvazirani, thanks for reporting this issue. Could you explain why you expect the build to fail? Are you saying the `azuredeploy.json` is an invalid json file but that isn't caught?

**Comment by hiyadav** [comment]
Hey @manojvazirani 
can you share the logs of the passing task in the build with build variable "system.debug" = "true".
