### ISSUE TITLE
dotnet core task path to project(s) is read only

### ISSUE THREAD

**Issue by groogiam** [Microsoft/azure-pipelines-tasks#8899]
All of my dotnet core tasks have the "Path to project(s)" field readonly when creating a build definition from the template. Seems like I should be able to select what projects I want my pipeline to build.

![image](https://user-images.githubusercontent.com/1992395/48932559-a858da80-eeca-11e8-972d-d5b6c72137e6.png)

**Comment by JohannesDrexler** [comment]
That is because this is a linked parameter in the template . The parameter is found on the 'Pipeline' node of the editor. There you can unlink the parameter or edit the value

**Comment by groogiam** [comment]
Ahh, totally missed that. Thanks for the info.
