### ISSUE TITLE
Wrong nuget.config generated for private feeds

### ISSUE THREAD

**Issue by mbp** [Microsoft/azure-pipelines-tasks#8903]
Using on-premise Windows or Linux agent with latest .NET Core SDK 2.1.500 installed, it is not possible to restore packages with "dotnet restore" using the DotNetCoreCli task. You get `401 Unauthorized`

It seems the temporary nuget.config file generated is wrong.

```
<configuration>
  <packageSources>
    <add key="NuGetOrg" value="https://api.nuget.org/v3/index.json"/>
    <add key="24175d4e-5754-49d7-8f7e-11a212b7dae1" value="https://MYORG.pkgs.visualstudio.com/_packaging/24175d4e-5754-49d7-8f7e-11a212b7dae1/nuget/v3/index.json"/>
  </packageSources>
  <packageSourceCredentials>
    <_x0032_4175d4e-5754-49d7-8f7e-11a212b7dae1>
      <add key="Username" value="VssSessionToken"/>
      <add key="ClearTextPassword" value="SECRET"/>
    </_x0032_4175d4e-5754-49d7-8f7e-11a212b7dae1>
  </packageSourceCredentials>
</configuration>
```

The `<_x0032_4175d4e-5754-49d7-8f7e-11a212b7dae1>` is wrong, it should be `<24175d4e-5754-49d7-8f7e-11a212b7dae1>`

Related issue/comment: https://github.com/NuGet/Home/issues/7516#issuecomment-440803591

**Comment by nkolev92** [comment]
My comment wasn't clear enough. 
The bug is on NuGet side. 
See tracking here: 
https://github.com/NuGet/Home/issues/7524
