### ISSUE TITLE
Publish Test Result task: Discrepancy between reported Test results of NUnit2/NUnit3

### ISSUE THREAD

**Issue by GraueEminenz79** [microsoft/azure-pipelines-tasks#8907]
_Please tag as Question_

## Environment
* Server - TFS on-prem 2017 Version 15.117.27024.0

## Issue Description

I noticed an (intended?) discrepancy between published NUnit2 and NUnit3 verdicts.
In Test Run explorer they are reported as following:

| NUnit2 (respective their NUnit3 counterparts) | Published NUnit2 | Published NUnit3 |
| --- | --- | --- |
| Success/Passed | Passed | Passed |
| Failure/Failed | Failed | Failed |
| Error | Failed | Failed |
| Inconclusive | _Passed_ | _Inconclusive_ |
| Skipped | _Passed_ | _Failed_ |
| Ignored | NotExecuted | NotExecuted |
| Cancelled | Failed | Failed |
| NotRunnable | _Passed_ | _Failed_ |

Mainly I am interested in the mismatches of skipped, inconclusive and not-runnable tests (see above).

**Comment by kushaga** [comment]
Hi @GraueEminenz79 , can you give us the Trx file for the PTR task.

**Comment by GraueEminenz79** [comment]
> Hi @GraueEminenz79 , can you give us the Trx file for the PTR task.

Sorry for the late reply. Actually, I want to publish NUnit test result format, not TRX (anymore).

My newer test execution scenario was:
- NUnit**3**-console-exe (Command Line task) and PTR task with NUnit as Test result format
[nunit3_console_test_verdicts.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2772340/nunit3_console_test_verdicts.zip)
- VSTest task with NUnit**3**TestAdapter
[vstest_nunit3testadapter_test_verdicts.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2772341/vstest_nunit3testadapter_test_verdicts.zip)

(Even there is a mismatch reported: _Inconclusive_ (NUnit verdict)  is in one case _Inconclusive_ and in the other _Not Executed_)

- NUnit**2** runner (Command Line task) and PTR task with NUnit as Test result format
[nunit2_test_verdicts.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2772388/nunit2_test_verdicts.zip)

(Lacking of test case `TestResult_Explicit` is fine, imho, as not even reported in NUnit2 result file)

**Comment by divais** [comment]
Hi @GraueEminenz79, 

We are working to correct this behaviour and changing for skipped and NotRunnable to be marked as NotExecuted for NUnit3 and NUnit2. 

Can you please share if you have any concern with this? Although it changes the behaviour for exsisting customers as the test pass % wont be impacted this shouldn't be a breaking change. Love to hear your thoughts before we make the change. 


NUnit2 (respective their   NUnit3 counterparts) | Published NUnit2 | Published NUnit3 | New Status
-- | -- | -- | --
Success/Passed | Passed | Passed | Passed
Failure/Failed | Failed | Failed | Failed
Error | Failed | Failed | Failed
Inconclusive | Passed | Inconclusive | Inconclusive
Skipped | Passed | Failed | Not executed
Ignored | NotExecuted | NotExecuted | NotExecuted
Cancelled | Failed | Failed | Failed
NotRunnable | Passed | Failed | Not executed

**Comment by GraueEminenz79** [comment]
Hi @divais,

I can't speak for the NUnit (dev) community but it seems plausible for me (and my team).
We support your efforts in harmonizing these test verdicts.

Thanks & kind regards
J

**Comment by domischell** [comment]
Hi @divais,
in my opinion the new states make a lot of sense. Especially that NUnit2 and 3 will now have consistent states is definitively a good idea 👍 
Best regards,
Dom

**Comment by divais** [comment]
Thanks @domischell , we are ON it!

**Comment by suyash691** [comment]
This has been fixed. Closing this

**Comment by dpksinghal** [comment]
Closing the issue.
