### ISSUE TITLE
Visual Studio Test reset resolution

### ISSUE THREAD

**Issue by blackbaud-rossthomson** [Microsoft/azure-pipelines-tasks#8908]
_Originally posted by @cltshivash in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0MTI0MTQwNw==/timeline/issue_comment#issuecomment-441241407_

**Comment by blackbaud-rossthomson** [comment]
Okay so I've already tried that - things I've tried and did not work are as follows:

1. The extension listed above
2. Setting the resolution in VMware
3. Setting the resolution in the registry
4. Creating an app that sets the resolution on login

None of these actually worked, I'm assuming, due to the task setting the resolution itself, hence my request for the task to surface the resolution it's setting into the mstsc command. I'm further assuming that it's not explicitly setting a resolution hence teh resolution always being 1042*768.

Also please do not close the issue until is is actually fixed!!!

**Comment by joshmgross** [comment]
Hey @blackbaud-rossthomson, I can't open that link. Which task are you referring to?

**Comment by blackbaud-rossthomson** [comment]
Hey @joshmgross - my original issue was this:

In 2.* of the task “Visual Studio Test” when the "Test mix contains UI tests" checkbox is ticked could you surface the resolution that the test will run at (by default) and allow this to be set greater that the default of 1024x768.

I've tried a large number of solutions to this issue but nothing seems to reset the size of the resolution the test are running at?

Thanks!

Ross

Link should be here:

https://github.com/Microsoft/azure-pipelines-tasks/issues/8467#event-1984129617

**Comment by prawalagarwal** [comment]
@blackbaud-rossthomson For us to investigate further, please attach the following:
1) Screen shot of the tasks added in your definition (this is with the screen resolution utility task added).
2) Screen shot of the inputs to the Screen Resolution Utility task.
3) Screen shot of the inputs to the VsTest task.
4) Your build logs with system.debug set as true in build definition variables.

**Comment by prawalagarwal** [comment]
@blackbaud-rossthomson Any updates here? Also I went through the comment of your last issue. VsTest task does not set the resolution for the test to run. There is no mstsc invoved. It simply invokes the test runner on the agent machine and all resolution related aspects are handled by the tests or any scripts you run.

**Comment by blackbaud-rossthomson** [comment]
I'll have files uploaded by the end of the week :)

**Comment by blackbaud-rossthomson** [comment]
So trying to set the resolution to 1920*1080 I get the fail message:
![two](https://user-images.githubusercontent.com/24247222/49514184-48c7db00-f88b-11e8-89f9-1872ccbbe118.png)
![three](https://user-images.githubusercontent.com/24247222/49514206-4feee900-f88b-11e8-8289-1f3a00abff04.png)
![four](https://user-images.githubusercontent.com/24247222/49514215-541b0680-f88b-11e8-82b3-16d28905b921.png)




2018-12-05T00:01:17.0246011Z ##[debug]Microsoft.PowerShell.Commands.WriteErrorException: Failed to change the resolution.
2018-12-05T00:01:17.0661870Z ##[error]Failed to change the resolution.

At the begining I get the warning:

2018-12-05T00:01:15.1872857Z ##[warning]The current user session is not a console session. It may not be possible to change the screen resolution. Please ensure that agent is running with autologon and disconnect any remote desktop sessions.
2018-12-05T00:01:15.1873530Z ##[debug]Processed: ##vso[task.logissue type=warning]The current user session is not a console session. It may not be possible to change the screen resolution. Please ensure that agent is running with autologon and disconnect any remote desktop sessions.

If you see attachment four I was wondering if that splash screen is fouling the autologin?

![one](https://user-images.githubusercontent.com/24247222/49514114-08685d00-f88b-11e8-8c46-df4d97023d65.png)

**Comment by ShreyasRmsft** [comment]
It's quite possible that the splash screen is indeed preventing the screen resolution change. The script basically checks if the current active session is a console session or not.

In this case it clearly has detected the active session is not a a console session.

You can double check this by running a simple powershell command:

query session

Also see if you can get rid of the splash screen.

**Comment by ShreyasRmsft** [comment]
Also if you've started the agent with autologon but remote desktoped into the machine at some point of time you sometimes end up losing the console session. A restart of the machine and then running the build/release without remoting to the machine is advisable

**Comment by prawalagarwal** [comment]
@blackbaud-rossthomson any updates here?

**Comment by blackbaud-rossthomson** [comment]
Sure I got the splash screen removed, autologin now works as expected, I still get the same exception above and the pipeline fails.

I've rebooted and not logged into the server since reboot - I still get the same exception above and the pipeline fails (with autologin working).

Any thoughts are appreciated?

Ross

**Comment by prawalagarwal** [comment]
@blackbaud-rossthomson Can we schedule a skype call for this? We are available from 10AM- 6PM IST

**Comment by ShreyasRmsft** [comment]
@blackbaud-rossthomson can you run a powershell task with the following script and share the output? 

`query session`

**Comment by blackbaud-rossthomson** [comment]
@ShreyasRmsft output of the query session below + full log of the task:

![agent1query](https://user-images.githubusercontent.com/24247222/49860266-6946e680-fdf1-11e8-9612-f9ebe5d222e9.png)
[7.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2671305/7.txt)

@prawalagarwal happy to set  up a acall but it would need to be in w/c Jan 7th as I'm off on extended leave from today :)

Thanks for all your help so far!

**Comment by ShreyasRmsft** [comment]
@blackbaud-rossthomson 

what you ran via rdp the output was expected. What i was looking for was the output of the command when run via the agent. But that's alright I had enhanced the task to print the output sometime ago

Here's what i was looking for anyways from the logs you sent

```
2018-12-12T00:01:37.2441406Z ##[debug] SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE 
2018-12-12T00:01:37.2461015Z ##[debug]>services                                    0  Disc                        
2018-12-12T00:01:37.2570989Z ##[debug]                   Au                        1  Disc                        
2018-12-12T00:01:37.2692527Z ##[debug] console                                     3  Conn                        
2018-12-12T00:01:37.2695705Z ##[debug] rdp-tcp                                 65536  Listen    
```

**_2018-12-12T00:01:37.2461015Z ##[debug]>services                                    0  Disc_**    

This line clearly indicates your agent is not running in interactive mode. It is possibly running as a service.
And the resolution cannot be changed in service mode. Please double check that you have started the agent with autologon.

This is what your agent setup inputs should look like

![image](https://user-images.githubusercontent.com/25194518/49864007-84cce400-fe27-11e8-98a4-44b836bc83ea.png)

**Comment by ShreyasRmsft** [comment]
Note that you say **_N_** for service and **_Y_** for autologon

**Comment by blackbaud-rossthomson** [comment]
Apologies I thought that was how I'd configured it - clearly not!

On reconfiguring it, the set resolution still fails, however I don’t actually need it since the autologin is now picking up the profiles resolution in vmware and running the test at 1920x1080.
Thanks to all of you for getting me to a solution!

Ross

**Comment by blackbaud-rossthomson** [comment]
Sure @ShreyasRmsft logs are attached.
[7.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2675847/7.txt)

I've since removed the task as now I've corrected the autologin per your instructions it's picking up the correct resolution from the user profile :)

**Comment by ShreyasRmsft** [comment]
`2018-12-12T12:17:12.7911010Z ##[debug]>                  aut                       4  Disc                      `

Extremely strange, despite autologon there seems to be no active console session. There's something strange going on with the VM. I'm not able to repro this with any of the VMs I create.

Another question: Is this a local Hyper-V vm or a VM on the cloud?

**Comment by blackbaud-rossthomson** [comment]
The VM's in question here are VMware VM's on vSphere, exceure my ignorance, would that make a difference?

**Comment by ShreyasRmsft** [comment]
@blackbaud-rossthomson just trying to see if the VMs you get would have any configuration set by default that could be preventing the resolution change. To be quite honest this seems like a one off scenario and trying to figure out what's happening without access to the machine is difficult.

If you try to take a screen shot from the build at the very beginning of the build before launching anything what does it show? Ideally I would expect to see a cmd promt process window running the agent if everything is as expected. Again since your issue is resolved no pressure or hurry in doing any of this. If you find time we can see what's different in the case of your VM.

**Comment by prokach** [comment]
Hello @ShreyasRmsft ,
I have the same issue with self-hosted agent, which is running in VM and Screen Resolution Utility task in Azure DevOps.
I've configured the agent in interactive mode. But my Screen Resolution Utility task is failing with the following logs:
`
##[warning]The current user session is not a console session. It may not be possible to change the screen resolution. Please ensure that agent is running with autologon and disconnect any remote desktop sessions.
##[error]Failed to change the resolution.
Finishing: Set screen resolution
` 
When I try to run `query session` I am getting
`
VERBOSE:  SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE 
VERBOSE:  services                                    0  Disc                        
VERBOSE: >                  upgreat                   1  Disc                        
VERBOSE:  console                                     2  Conn                        
VERBOSE:  31c5ce94259d4...                        65536  Listen                      
VERBOSE:  rdp-tcp                                 65537  Listen  
`
The VM with the agent is on the (Azure) cloud.

Have you had a change to reproduce it?

Looking forward to hear from you.
