### ISSUE TITLE
Download Build Artifacts behind proxy always fails

### ISSUE THREAD

**Issue by Ivers07** [Microsoft/azure-pipelines-tasks#8909]
## Environment
- Server - Azure Pipelines   
- Agent - Private: 
    - OS - Windows Server 2012 R2
    - Agent V - 2.140.2

## Issue Description

When running a release pipeline with either
A) Run on agent Job - Artifact download enabled or;
B) using the Download Build Artifacts task

Throws error:
**"Error: tunneling socket could not be established, statusCode=407"**

The same "Download Build Artifacts" task V0.142.3 appears to be used for both pipeline options but with A) it says "Failed in getBuild with error:"
B) it says "Failed in getArtifact with error:"

On Prem agent is behind corporate proxy bug agent was configure with proxy url. Proxy does not use SSL and no authentication required.

### Task logs

[tasklog_3.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2615104/tasklog_3.log)

### Error logs

![image](https://user-images.githubusercontent.com/15321552/49009469-9005eb80-f168-11e8-8fcd-5211f7974a08.png)

**Comment by omeshp** [comment]
@Ivers07 It is possible that since agent is dotnet core is process in picking up default network credentials to authorize to proxy, Since the task is node based, node processes aren't able to use default creds.
