### ISSUE TITLE
Gradle 5.0

### ISSUE THREAD

**Issue by aardouin** [Microsoft/azure-pipelines-tasks#8918]
## Environment
 - Azure Pipelines  
    - Account : Helloasso
    - Project : Mobile 
    - Build : Android Dev #20181127.1 -> 20181127.8
 - Hosted on : macOS10.13
## Issue Description
Executing a gradle2 task : 
```
 - task: Gradle@2
    displayName: 'Unit tests with coverage'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: 'app/build/test-results/**/TEST-*.xml'
      tasks: ${{ format('test{0}DebugUnitTestCoverage', parameters.env) }}
```

After upgrading to gradle 5.0, the init script : init.d/log-gradle-version-plugin.gradle
Fails with the following error : 

```
2018-11-27T08:39:40.0779210Z Initialization script '/Users/vsts/.gradle/init.d/log-gradle-version-plugin.gradle' line: 13
2018-11-27T08:39:40.0779670Z 
2018-11-27T08:39:40.0780080Z * What went wrong:
2018-11-27T08:39:40.0781000Z Could not compile initialization script '/Users/vsts/.gradle/init.d/log-gradle-version-plugin.gradle'.
2018-11-27T08:39:40.0781470Z > startup failed:
2018-11-27T08:39:40.0782380Z   initialization script '/Users/vsts/.gradle/init.d/log-gradle-version-plugin.gradle': 13: unable to resolve class GradleVersion 
2018-11-27T08:39:40.0782830Z    @ line 13, column 29.
2018-11-27T08:39:40.0783270Z              final GradleVersion currentVersion = GradleVersion.current()
2018-11-27T08:39:40.0783660Z                                  ^
2018-11-27T08:39:40.0786400Z   
2018-11-27T08:39:40.0786780Z   1 error
```

## Temporary workaround : 
Added a task that delete the init-script prior to use Gradle
```
 - task: DeleteFiles@1
    inputs:
      sourceFolder: '/Users/vsts/.gradle/init.d/'
      contents: 'log-gradle-version-plugin.gradle'
```

**Comment by joshmgross** [comment]
Hey @aardouin, this might be an issue with your `log-gradle-version-plugin.gradle`. 
You may need to upgrade that plugin so that its compatible with Gradle 5.0. See here for more info: https://docs.gradle.org/5.0/userguide/upgrading_version_4.html

**Comment by aardouin** [comment]
Hi,
In fact, this file is not mine, it's part of VSTS's mac os image.

**Comment by nrajpurkar** [comment]
Thanks for letting us know @aardouin.

@joshmgross, our Hosted macOS currently supports Gradle 4.10.2 as seen in the [docs](https://github.com/MicrosoftDocs/appcenter-docs-pr/blob/master/docs/build/software.md). We plan to update to Gradle 5.0, but do not have an ETA to share at the moment.

**Comment by brunoborges** [comment]
Perhaps you should ensure the Gradle task will not call the provided Gradle Wrapper inside customers' projects if there are limitations to which Gradle version is supported. Otherwise, this issue will continue to pop up constantly.

**Comment by joshmgross** [comment]
Closing this issue.

Gradle 5.0 is not yet supported on Mac OS (see: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md#project-management).

Work-around provided in MicrosoftDocs/vsts-docs#2583

@brunoborges Thanks, I will pass on your feedback to the team.

**Comment by syendev** [comment]
> Closing this issue.
> 
> Gradle 5.0 is not yet supported on Mac OS (see: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md#project-management).
> 
> Work-around provided in [MicrosoftDocs/vsts-docs#2583](https://github.com/MicrosoftDocs/vsts-docs/issues/2583)
> 
> @brunoborges Thanks, I will pass on your feedback to the team.

PAGE NOT FOUND -> your link is broken

**Comment by syendev** [comment]
> Thanks for letting us know @aardouin.
> 
> @joshmgross, our Hosted macOS currently supports Gradle 4.10.2 as seen in the [docs](https://github.com/MicrosoftDocs/appcenter-docs-pr/blob/master/docs/build/software.md). We plan to update to Gradle 5.0, but do not have an ETA to share at the moment.

I can't see it in dos Page Not Found!

**Comment by joshmgross** [comment]
@syendev Gradle 5.5 should now be on the machines, see: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#project-management

If you are having trouble, could you create a new issue in this repo?

**Comment by syendev** [comment]
Ok great, I’ll create a new issue if I can’t figure it out.

S.
