### ISSUE TITLE
Azure CLI with inline script fails with TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by kungfooflea** [Microsoft/azure-pipelines-tasks#8935]
We have an issue open on the developer community here too -> https://developercommunity.visualstudio.com/content/problem/393967/script-failed-with-error-typeerror-path-must-be-a.html
[logoutput.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2626422/logoutput.txt)

We use the Aure CLI plugin V1 in some of our releases in Azure DevOps.

Starting yesterday we were seeing that it was failing with error "Script failed with error: TypeError: Path must be a string. Received undefined"

On the release that is failing, the version of the Plugin is "Version : 1.143.2" and the version of the Azure CLI on the host is azure-cli (2.0.51)

On the last successful release, the version of the Plugin was "Version : 1.140.2" and the version of the Azure CLI on the host was azure-cli (2.0.47)

We are using VSTS private agent version 2.142.1

We are using the inline script option on the plugin to complete the following ->

touch /tmp/.vsts_configuration_running

chmod +x $(System.DefaultWorkingDirectory)/Artifact/scripts/download_mesos_ssh_keys.sh

$(System.DefaultWorkingDirectory)/Artifact/scripts/download_mesos_ssh_keys.sh $(TEAMLAB)

rm /tmp/.vsts_configuration_running

As a test I removed everything and just had echo "hi" in the inline script field and it was failing with the same error.

I've attached the output logs of the failing task

**Comment by vineetmimrot** [comment]
This issue has been fixed. It will be available in 1.144.1 task version.
https://github.com/Microsoft/azure-pipelines-tasks/pull/8953/files
