### ISSUE TITLE
Release pipeline cannot download UniversalPackage artifact

### ISSUE THREAD

**Issue by ClearIce** [Microsoft/azure-pipelines-tasks#8938]
## Environment
- Server: Azure Pipelines

## Issue Description
When using a UniversalPackage artifact feed as the source for a release pipeline, "Nuget_" is prepended to the artifact name during the 'Download Artifact' step, causing an error during this step:

`Failed to get package metadata with error Error: Failed Request: Not Found(404) - The package with ID 'Nuget_xxxx' was not found in feed with ID xxxx.`

e.g., an artifact name published to the feed as 'test.artifact' will be try to be downloaded as 'Nuget_test.artifact' by the release pipeline, but this step will fail because 'Nuget_test.artifact' does not exist in the feed.

The artifact should be a simple zip file. It is not a nuget package.

I have verified I can download the UniversalPackage artifact via vsts command line.

I also cannot hack my way through by setting the artifact name to add "Nuget_" to the artifact name as UniversalPackage artifacts can only be named with lowercase alphanumerics, dots, and dashes.

![image](https://user-images.githubusercontent.com/18578798/49187069-912f4800-f323-11e8-9b09-cea857b69a2f.png)

**Comment by zarenner** [comment]
Hi @ClearIce,

Currently, NuGet packages are the only type of package supported as a source artifact in Pipelines. We're working on adding other package types such as Universal Packages, but they're not supported today.
I apologize the experience here is so unclear - we'll shortly be updating the UI and documentation to indicate that only NuGet packages are currently supported.

To download Universal Packages from a pipeline, today you can use the [UniversalPackages](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=vsts&tabs=yaml#download-universal-package) task to do so.

**Comment by ClearIce** [comment]
I understand, that clarifies things. Thank you guys for all of the work that you do!
