### ISSUE TITLE
Feature Request: support connection strings in pipeline task SQL Database Deployment 

### ISSUE THREAD

**Issue by MarkAtAgilliance** [microsoft/azure-pipelines-tasks#8940]
Feature request.  In the Azure SQL Database Deployment task (SqlAzureDacpacDeploymentV1), **support full connection strings as an option**.  This would use the alternative form of Invoke-SqlCmd that accepts a connection string.  Enable the form field to use variables so that we can pull this from a variable populated by KeyVault and pass it to the agent.

We are working on multiple Azure Data Factory implementations and the "normal" connection method for ADF is via a connection string that we pull from a Key Vault.  Our preference is to have a single method of connecting to databases and not have some using full connection strings and others having server, database, user, password variables.  This way we can reuse connection strings and it is less confusing for IT Ops to manage one type.

**Comment by Ajay-MS** [comment]
SQLAzureDacpacDeploymentV1 supports connection string now.
