### ISSUE TITLE
Install SSH key doesn't add the public SSH to the known_hosts

### ISSUE THREAD

**Issue by vladonemo** [Microsoft/azure-pipelines-tasks#8950]
## Environment
- Server - Azure Pipelines

- Agent - Hosted Ubuntu 1604

## Issue Description

We use the 'Install SSH key' task to add a private SSH. The SSH public key contains the public key of the server (ecdsa-sha2-nistp256 algo). However, after running the task, the known_hosts only contains the 'Known host entry' text (the hostname), but not the public key. Hence the SSH connection to the host fails with 'Host Key Verification Failed'.  
The workaround is to run a bash task right after this to add the entry to the known_hosts. Then the SSH connection works.

**Comment by schroerbrian** [comment]
It's not ideal, but you can just add the entire entry (hostname AND public key) to the known_hosts field. Azure should perhaps clarify this
