### ISSUE TITLE
PowerShell: Arguments"-input is missing when choosing "Inline" code.

### ISSUE THREAD

**Issue by atlefren** [Microsoft/azure-pipelines-tasks#8958]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server: Azure Pipelines   
- Agent:  Hosted (windows)

## Issue Description
When adding a PowerShell task to an agent job in a release pipeline the "Arguments"-input is missing when choosing "Inline" code. I am not able to find any documentation that states that this is intended behaviour. 

Contrast:
![image](https://user-images.githubusercontent.com/1829927/49278047-f732e100-f483-11e8-882d-1acdc21fbd92.png)

With:

![image](https://user-images.githubusercontent.com/1829927/49278070-01ed7600-f484-11e8-8e8a-a7e999dd69ab.png)

**Comment by JohannesDrexler** [comment]
You don't need arguments for inline because you can use build/release variables in your inline code. the variables will be replaced with the values when the task gets executed.

**Comment by joshmgross** [comment]
@JohannesDrexler is correct. Arguments are for passing into an external powershell script. If you're using an inline script, you can directly put those variables into your inline code.

**Comment by atlefren** [comment]
Thanks for the heads-up!

This seems a bit inconsistent to me, but as long as it's possible to pass variables to an inline script in one way or another I guess it's fine. 

Does the same thing apply to the Bash task?

**Comment by bdrangel10** [comment]
@joshmgross you said that in an inline script it is possible to use directly the pipeline variables; however, when a variable is secret that is not possible. In this case, it is necessary to pass it as an argument, as in Powershell Task. Please consider reopen the issue
