### ISSUE TITLE
Sync from github to vsts.

### ISSUE THREAD

**Issue by pranavsharma** [Microsoft/azure-pipelines-tasks#8962]
We've 2 repos for the same product - one internal (vsts) and one external (on github). The vsts repo is a superset of the github repo. Is there any cookie-cutter recipe to sync changes made in github with vsts? How should one configure this? I read [this](https://nkdagility.com/open-source-vsts-tfs-github-better-devops/), but it might be outdated. Thanks.

**Comment by bryanmacfarlane** [comment]
Not an issue with a task in this repo.  You can create something in developer community for the service.
