### ISSUE TITLE
Command line Task skips last command

### ISSUE THREAD

**Issue by groogiam** [Microsoft/azure-pipelines-tasks#8976]
## Troubleshooting
When executing the following command line script via the Command Line task in Azure Pipelines (on prem) the last command is skipped completely.

```
cd src\MyMobileApp
npm install --loglevel=error
ionic cordova build android --prod --release --confirm
```

**Comment by bryanmacfarlane** [comment]
Is this on windows or linux?

**Comment by ericsciple** [comment]
Try:

```
cd src\MyMobileApp
call npm install --loglevel=error
ionic cordova build android --prod --release --confirm
```

If you run `where npm`, the command resolves to `npm.cmd`. If you don't use [call](https://www.robvanderwoude.com/call.php), the script will take a hard fork.
