### ISSUE TITLE
PublishTestResults for NUnit ignores the <output> element, unless it is a sibling of a <failure> element.

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#8979]
## Environment
- Server - TFS on-premises, version 16.131.27701.1

- Agent - Private:

Capability name | Capability value
-- | --
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.131.0

## Issue Description

The published NUnit test results only contain console output for failed tests. More details are here - https://stackoverflow.com/q/53548115/80002

### Task logs

[logs.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2638084/logs.zip)

### Error logs

There are no errors

**Comment by pagangil** [comment]
@MarkKharitonov This behavior is by design. We publish the content of the `<output>` as a test result attachment file and we do this only for failed test results.
Just curious to know the requirement of output logs in passed test results because these output logs are generally used to debug failed test results and thus not required in passed test results.

**Comment by MarkKharitonov** [comment]
I think it is wrong to make assumptions why do tests need to produce output or have attachments. There could be different reasons. For example, the tests may pass by mistake - could happen during the development of the tests and the output along with attachments can help determine that. Or the tests come to replace the manual tests and the testers may wish to inspect the output and/or attachments to make sure the automated tests do what is expected. At least in the beginning when the testers need to become confident that the automated tests do the right thing. 
In general I do not think it is possible to think of all the possible scenarios beforehand. I would say if the test has output and/or attachments they should be surfaced unconditionally, because they are part of the test and one can never know what purpose they may serve.

**Comment by MarkKharitonov** [comment]
Any comment on that?

**Comment by divais** [comment]
Hi @MarkKharitonov 

Current we support attachments for only failed tests. It will be great if you can request this feature at our dev community https://developercommunity.visualstudio.com/content/idea/post.html?space=21 which will help us prioritize.

**Comment by MarkKharitonov** [comment]
https://developercommunity.visualstudio.com/idea/432166/the-publish-tests-azure-devops-plugin-should-publi.html

**Comment by MarkKharitonov** [comment]
And the reason for closing this issue is?

**Comment by navin22** [comment]
Since it has corresponding developer community idea, Hence I closed this.

**Comment by MarkKharitonov** [comment]
Any update?

**Comment by suyash691** [comment]
We pick up feature requests based on popular demand, as of now this is low priority in our backlog.

cc: @shashban
