### ISSUE TITLE
Dockercompose push Task does not filter on tags anymore

### ISSUE THREAD

**Issue by philippesollaud** [Microsoft/azure-pipelines-tasks#9002]
Hi,

Using dockercompose in build definition for building and pushing docker images on ACR, we add the BuildId as tags on images:
![image](https://user-images.githubusercontent.com/22167066/49504123-5e340980-f879-11e8-8cc5-626d1c291aae.png)

Since 2 months, the dockercompose push task does not push only the image with the tag corresponding to the current build. Before pushing the image with the specified tags, it pushes all images with the name present on the build server (ie: images corresponding to previous builds)

![image](https://user-images.githubusercontent.com/22167066/49503768-7f482a80-f878-11e8-9d24-7d1f35be46bc.png)

Is there a way to push only images with the selected tag ?

Regards,
Phil

**Comment by vithati** [comment]
@philippesollaud , In your docker compose file if image name not contains any tag like in example1,  When you run 'Push service image' command, task internally uses docker push command and it pushes all 'mytestimage' tagged images on the server. This is docker push default behavior. In example2,  When you run 'Push service image' command, it pushes 'mytestimage:latest' tagged image along with additional tagged images only. If you want to push additional tagged images  along with 'latest' tag image specify image with tag in docker compose file like example2.

example1: ``` services: testimage: image: mytestimage build: context: . dockerfile: Dockerfile ```
example2:  ``` services: testimage: image: mytestimage:latest build: context: . dockerfile: Dockerfile ```
