### ISSUE TITLE
GitHub Release task does not work with GitHub Application service endpoint

### ISSUE THREAD

**Issue by onovotny** [Microsoft/azure-pipelines-tasks#9009]
If you try to use the GitHub release task with a Service Endpoint created by the GitHub application, it fails with a "Bad Credentials" error.

**Comment by devingoble** [comment]
I get the same result.

**Comment by mdmdakbar** [comment]
Thanks for pointing this out. We need some more details to debug this issue. 

Can you please let us know about your pipeline configuration? Like if the task is being used in build (CI) or release (CD) , if it is being used in build then are you using yaml  for configuration?

@onovotny @devingoble It would be great if you can provide us with the pipeline definition url. It will help us a lot.

**Comment by devingoble** [comment]
@mdmdakbar Do you mean this? https://devingoble.visualstudio.com/FicheUtilities/_release?view=mine&definitionId=2

**Comment by mdmdakbar** [comment]
Service endpoints created through GitHub application is of scheme Token, which we do not support. We have updated the [documentation ](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/GitHubReleaseV0/README.md) as well.

Today, OAuth and Personal Access Token (PAT) schemes are supported by this task.

Thanks for reaching out to us. Closing this issue as designed. Feel free to re-open if you have any other concern.

**Comment by ericoporto** [comment]
> Service endpoints created through GitHub application is of scheme Token, which we do not support. We have updated the documentation as well.

In the documentation appointed above:

> **Service Connection:** This is the name of GitHub service connection which will be used to connect to target GitHub account. You can use an existing GitHub service connection or create a new one. Note that the service connection should use OAuth or PAT for authentication.

Can you give a little more examples? I been away from azure pipelines from an year and came back today to findout all my repositories are failing from Bad Credentials.
