### ISSUE TITLE
AzureFileCopy Task Should Allow for customized expiration time for SASTokens

### ISSUE THREAD

**Issue by halfpeaw** [Microsoft/azure-pipelines-tasks#9011]
## Issue Description
 AzureFileCopy VSTS Task should add an option to set the length of the expiration token.  Right now its hard coded to four hours which can be problematic if that outputted SaSToken is being used during a particularly long vsts task call.

**Comment by 20shivangi** [comment]
Fix will be available in next release

**Comment by 20shivangi** [comment]
Fix will be available in AzureFileCopyV3
