### ISSUE TITLE
AzureResourceGroupDeploymentV2 task does not emit the deployment name

### ISSUE THREAD

**Issue by ajay-arora** [Microsoft/azure-pipelines-tasks#9012]
## Issue Description
AzureResourceGroupDeploymentV2 task chooses a random arm template deployment name. My later tasks need to access the deployment again, but i dont know which one was created by this task. Other deployments are also happening in the same resource group, and I cant rely on the latest one.

**Comment by vineetmimrot** [comment]
Hey @ajay-arora ,
There is already a [PR](https://github.com/Microsoft/azure-pipelines-tasks/pull/8722) out, which addresses your issue.
