### ISSUE TITLE
How do I customize my TestParameters section in a runsettings file using the dotnet vstest CLI

### ISSUE THREAD

**Issue by declan-smyth** [Microsoft/azure-pipelines-tasks#9023]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - **Azure Pipelines** 

- Account information
      > Account Name: DeclanSmyth
      > Project: msc-csdca1

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name:  vshosts 2017

  
## Issue Description
I am trying to run a number of tests for a .Net Core webapp in my release pipeline.  The tests are MSTest based Selenium tests.  I am using the donet core task to run my tests. 

![image](https://user-images.githubusercontent.com/36519515/49623406-7b75ee80-f9c5-11e8-9074-e2bc50355de3.png)

When I run these tests with this command they run _ok_:
`$(System.DefaultWorkingDirectory)\Drop\bpcalculator\Acceptance.Tests\Acceptance.Tests.dll /TestCaseFilter:"Priority=1"`

When I run the tests with this command they _do not run as expected_:
`$(System.DefaultWorkingDirectory)\Drop\bpcalculator\Acceptance.Tests\Acceptance.Tests.dll /TestCaseFilter:"Priority=1" /Settings:$(System.ArtifactsDirectory)\Drop\bpcalculator\AcceptanceTests.runsettings -- webAppUri=$(webAppURI) browser=$(browser)`

When I run the command on my local development machine with diagnostics turned on I can see that the test parameters section is not updated and new xml elements are created instead. This results in my test execution not been customized.

My question is: **How do I customize my TestParameters section in a runsettings file using the dotnet vstest cli ?**

Here is the command I am trying to use on my local dev machine: 
`dotnet vstest C:\Users\xxxxxxx\git-repo\m-repo\Acceptance.Tests\Acceptance.Tests.dll /TestCaseFilter:"Priority=1" /logger:"console;verbosity=detailed" /Diag:"testlog.txt;tracelevel=verbose" /Settings:C:\Users\declans\git-repo\m-repo\AcceptanceTests.runsettings -- webAppUri="https://bpcalculator-dev-as-test.azurewebsites.net" browser="Firefox"`

### Task logs
Here is a snippet of the diagnostic log file:

```
pTrace Information: 0 : 18300, 1, 2018/12/07, 02:02:48.928, 1322698663518, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting run with settings:TestRunCriteria:
   KeepAlive=False,FrequencyOfRunStatsChangeEvent=10,RunStatsChangeEventTimeout=00:00:01.5000000,TestCaseFilter=Priority=1,TestExecutorLauncher=
   Settingsxml=<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\Users\xxxxxx\git-repo\masters-repo\TestResults</ResultsDirectory>
    <TestSessionTimeout>60000</TestSessionTimeout>
    <DesignMode>false</DesignMode>
    <DisableParallelization>false</DisableParallelization>
    <DisableAppDomain>false</DisableAppDomain>
    <CollectSourceInformation>true</CollectSourceInformation>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>.NETCoreApp,Version=v2.1</TargetFrameworkVersion>
  </RunConfiguration>
  <TestRunParameters>
    <Parameter name="webAppUri" value="http://localhost:40327/bloodpressure" />
    <Parameter name="browser" value="Firefox" />
  </TestRunParameters>
  <RunSettingsDirectory>C:\Users\declans\git-repo\masters-repo</RunSettingsDirectory>
  <webAppUri>https://bpcalculator-dev-as-test.azurewebsites.net</webAppUri>
  <browser>Firefox</browser>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="console" assemblyQualifiedName="Microsoft.VisualStudio.TestPlatform.CommandLine.Internal.ConsoleLogger, vstest.console, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" codeBase="C:\Program Files\dotnet\sdk\2.1.500\vstest.console.dll" enabled="True">
        <Configuration>
          <verbosity>detailed</verbosity>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
</RunSettings>

```

**Comment by nigurr** [comment]
@declan-smyth currently this functionality is not available in `dotnet core` task. Can you try using `VsTest v2` task?

**Comment by cltshivash** [comment]
There's no plan to add this to the dotnet task.
