### ISSUE TITLE
Improving CMake Task

### ISSUE THREAD

**Issue by KUGA2** [microsoft/azure-pipelines-tasks#9026]
## Environment
TFS on premise. Version 15.117.27024.0

## Issue Description

The current CMake Task is basically worthless. All the benefits to the "Command Line" Task is adding cmake as executable and setting the demand.

## Proposed enhancements

* If Demand CMAKE points to cmake.exe, use this cmake.exe
* Support and Demand multiple different cmake versions that can be installed in parallel
* Add variables
* Verbose option
* Build Mode (Release, Debug, ... + free form)
* Additional command line parameters
* Drop down box: "Configure", "Build", "Install", "Run Script", "Test"
* On Configure set source and configuration directory (maybe save configuration directory to variable for following CMake Build etc. tasks), Set Generator (add demands acordingly), Set Toolset (add demands acordingly)
* On Install: Install directory (CMAKE_INSTALL_PREFIX), Component
* On Test: Component, Regex for test, Make Badge with results, add results to Build Overview

**Comment by BotellaA** [comment]
Is there any update on this issue?

**Comment by azureDaveOps** [comment]
No update yet, we were working on fixing some cmake issues in the latest hosted 2017 image updates, which took priority over this.

**Comment by BotellaA** [comment]
No problem. Is there an estimated timeline for these improvements?

**Comment by moswald** [comment]
Sorry for the delay. Adding @vijayma for scheduling/prioritization.

**Comment by Lectem** [comment]
I would also love to see a better support for the cmake task.
Right now it seems the only advantage it has is specify the working directory and find the cmake version (which might already be in the path ?)

I think we at least need `cmake YOUR OPTIONS ..` to be the default, then followed by a `cmake --build .` with optional targets.
Then comes support for CTest and CPack.

**Comment by KUGA2** [comment]
If this ever will pop up into your work queue, please support the new cmake presets. This feature is the most important now...
