### ISSUE TITLE
The Github Release task README should state when it will create tags if they do not exist

### ISSUE THREAD

**Issue by JeremyLoy** [Microsoft/azure-pipelines-tasks#9027]
~[The behavior of this task should mirror the Github API](https://developer.github.com/v3/repos/releases/#create-a-release)~

**Comment by raiyanalam** [comment]
This task does create a tag if they don't exist. Have you tried using 'user specified tag' as tag source?

**Comment by JeremyLoy** [comment]
The documentation for git tag explicitly states it doesn’t not create a tag.

> If no tag is found for the given commit, the release will not be created. If multiple tags are found, the task will throw an error.

I have not tried user-specified, but it states I should specify a tag. Can you also specify a SHA?

**Comment by raiyanalam** [comment]
- If you select tag source as 'git tag', then the git tag associated with the commit will be used to create release.
- If you select tag source as 'user specified tag'. Then we ask the user to give a tag. We will create a release with that given tag. If not present we will create it for you. The behavior mimics that of the GitHub API. 

> User specified tag: When this option is used, the release will be created using the tag mentioned.


- You can specify a SHA in the target commit field, not in the tag source.

> Target: This is the commit SHA for which the GitHub release will be created. By default, the value is $(Build.SourceVersion) which corresponds to the commit for which the build was run.

**Comment by JeremyLoy** [comment]
Interesting, thanks @raiyanalam. I think the documentation could use a once-over to state this behavior. In its current state, it makes no mention that it creates tags. I'll repurpose this issue to reflect that.

**Comment by raiyanalam** [comment]
We have updated the documentation to reflect this. Thanks for your input.
Closing this issue.
