### ISSUE TITLE
docker run additional arguments

### ISSUE THREAD

**Issue by OneCyrus** [microsoft/azure-pipelines-tasks#9034]
## Environment
- Server - Azure Pipelines
- Agent - Private
- Docker v1 Task
  
## Issue Description

We would like to specify some additional arguments to docker run. Currently it looks like this is not possible. e.g.

docker run **--isolation hyperv** containous/whoami
docker run **--label com.example.foo=bar** containous/whoami

with docker build we can specify additional arguments. it would be nice to have this option on all commands especially **docker run**.

**Comment by ds-ms** [comment]
@OneCyrus There's an input field called `Command` in the task view, could you pass these extra arguments there and see if it works?
![image](https://user-images.githubusercontent.com/25762922/49873755-ab4c4880-fe42-11e8-8457-ea273cf1fcde.png)

**Comment by OneCyrus** [comment]
@ds-ms no, that doesn't work. it adds them as command

![image](https://user-images.githubusercontent.com/7747800/49950931-16f0ed00-fef9-11e8-8dfe-091027e313f6.png)

**Comment by ds-ms** [comment]
@OneCyrus could you add a screenshot of how you've configured the definition? 

Also, if you notice there are 2 input fields called `Command` when you choose `run`. I've raised a PR (https://github.com/Microsoft/azure-pipelines-tasks/pull/9070) to fix the confusion here. 
Whatever you add to the 2nd Command input is given as command line input to docker, which in your case should be the input field called `containerCommand`.

**Comment by OneCyrus** [comment]
the config looks like this:

![image](https://user-images.githubusercontent.com/7747800/50138969-90456280-02a0-11e9-8828-62f758cbc5b8.png)

the problem is that it adds the command at the end of the command line and thus the docker command uses it as command for inside the container instead of a argument for the docker command.

**Comment by ds-ms** [comment]
You're right!
I've exposed an input field called `Arguments` (in PR #9070) which should solve your problem.

**Comment by OneCyrus** [comment]
perfect. thanks!

**Comment by azooinmyluggage** [comment]
Thanks @OneCyrus We will pick up this enhancement.

**Comment by shashankbarsin** [comment]
@ds-ms please take a look at the referenced issue about --network argument being ignored by the run command
