### ISSUE TITLE
Error in App Service Deploy task when using quotes in AppSettings

### ISSUE THREAD

**Issue by dedalusmax** [microsoft/azure-pipelines-tasks#9040]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

When using Azure App Service Deploy task (version 3 or 4, regardless), with Application Settings, if you have quotes inside an app settings value, the task will fail! For instance, I'm setting SQL connection string that have a quote inside the password for a db, and the task confuses and messes the parameter values.

### Task logs

...
2018-12-10T13:30:12.0079262Z ##[debug]Deployment Failed with Error: Error: Failed to update App service 'sauter-test-audit-function' application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)
2018-12-10T13:30:12.0080159Z ##[debug]task result: Failed
2018-12-10T13:30:12.0136018Z ##[error]Error: Failed to update App service 'sauter-test-audit-function' application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by SumiranAgg** [comment]
@dedalusmax Thanks for reporting this. It appears to be a bug. We will file a bug internally and update the thread when fixed.
If you are setting a connection string, we are planning to introduce a new task input to support it. We will take care of this issue in the new input but for older ones (App setting, Config setting) we will be able to get a fix only with a major version bump.

For now, as a workaround, please use Azure CLI task to update your app setting. 
az webapp config appsettings set -g <resourceGroupName> -n <webAppName> --settings blah='\"fshdiud\"dfd"fd)'

Note: Please escape the quotes while setting value.

**Comment by eaarora-ms** [comment]
We have moved to JSON parsing now in the new task which should resolve this error: 
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureAppServiceSettingsV1
Closing this.

**Comment by colinbull** [comment]
@eaarora-ms It is worth noting that this task now fails if you have a comma anywhere in your settings. Which given that DB connection strings typically do, this can be problematic.

**Comment by eaarora-ms** [comment]
@colinbull  Are you talking about Azure App Service Settings? If yes, can you please create a new issue in the same repo please?

**Comment by colinbull** [comment]
@eaarora-ms Done see #12800
