### ISSUE TITLE
DotNetCoreCLI@2 does not support configuration

### ISSUE THREAD

**Issue by akaFalsh** [microsoft/azure-pipelines-tasks#9073]
## Environment
- Agent - Hosted: 

## Issue Description
When using DotNetCoreCLI@2 parameter configuration is ignored and not added to dotnet.exe call

**Comment by JohannesDrexler** [comment]
Cannot reproduce this, how did you configure your task?

**Comment by sachinma** [comment]
@akaFalsh  did you try out the suggestion from @JohannesDrexler . This should help you out.

**Comment by akaFalsh** [comment]
@JohannesDrexler  this works for me either. However I was wondering why configuration parameter does not work.

**Comment by JohannesDrexler** [comment]
can you show us some build logs and how you configured your task ?

**Comment by hiyadav** [comment]
@akaFalsh can you provide @JohannesDrexler with the logs for further investigations ?

**Comment by hiyadav** [comment]
@akaFalsh we are closing the issue now, if more help is needed, feel free to reopen or open a new issue.

**Comment by Kaneraz** [comment]
I just ran up against this as well and using arguments solved it. The documentation [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#open-source) is not near as complete as what's in this project's readme files so it's probably leading to a lot of the confusion. 

Having the configuration as an input for build and test commands would be a nice to have to keep things consistent across all 3 tasks.

**Comment by amaljg** [comment]
Thanks @Kaneraz for the feedback. Adding @pulkitaggarwl to consider the feedback in the next version of the task. @pulkitaggarwl - Can you help in fixing the documentation referred above in the meanwhile?

**Comment by Kaneraz** [comment]
Hopefully this is on it's way to being fixed. I'm not sure what the release timelines are for the docs, but I've had a PR accepted for it: https://github.com/MicrosoftDocs/vsts-docs/pull/3582

**Comment by ptr727** [comment]
The PR appears to introduce a difference between configurationToPack and configuration.
It does not address the problem that configuration does not work in devops with dotnet core 3.1.

I would like to use:
configuration: $(BuildConfiguration)
Now I have to use:
arguments: '--configuration $(BuildConfiguration)'
