### ISSUE TITLE
PublishTestResults for NUnit3 xml results doesn't use duration

### ISSUE THREAD

**Issue by RichRowan** [microsoft/azure-pipelines-tasks#9078]
## Environment
- Server - Azure Pipelines
Private account.

- Agent: 
Private
Windows 8.1
Agent.OS | Windows_NT 
Agent.OSArchitecture | X64
Agent.OSVersion | 6.3.9600
Agent.Version | 2.142.1

## Issue Description
The Publish Test Results task doesn't handle the duration of test cases or the entire suite. It looks to be based on the end-time minus the start-time and ignores duration entirely. It doesn't conform to the [format mapping shown here.](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml#result-formats-mapping)
![image](https://user-images.githubusercontent.com/38789255/49941323-0d0bc180-feda-11e8-9f1a-ee2f0c1f1e21.png)
Example NUnit3 results file.
[results-NUnit.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2676215/results-NUnit.zip)

### Task logs
Focusing on Task "6_Pulish Test Results results-NUnits.xml .log"
[ReleaseLogs_69.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2676199/ReleaseLogs_69.zip)

**Comment by khilan2goel** [comment]
Hi @RichRowan ,

Looks like in xml for a testcase, both start-time and end-time are getting populated, so we assume that (end-time - start-time) should match with duration provided which is not the case here. While reporting, we take into account duration for testcase only if both the fields(start-time and end-time) are not populated or either one of them is populated else we assume that start-time and end-time should match with duration. Can you please help us know why (end-time - start-time ) are different from duration for a testcase?

**Comment by divais** [comment]
Hi @RichRowan 

Thank you for the feedback, we will update our documentation. 

To ensure consistency we calculate duration when both start and end time is available.

**Comment by RichRowan** [comment]
@divais It still doesn't make sense to calculate the duration since it reduces the accuracy of the duration to whole seconds.

**Comment by divais** [comment]
@RichRowan so you are suggesting we should calculate duration only when start time and end time aren't available. Any scenarios you think this wont work?

**Comment by RichRowan** [comment]
@divais no. I'm saying if duration is present, use it. If duration is not present, then calculate from start time and end time.

**Comment by siprbaum** [comment]
A little background information: Nunit3 will give the start & end time only in full second accuracy, whereas the duration has millisecond accuracy. So using the duration when the duration is available like @RichRowan suggested would also be my preferred solution, otherwise very fast unit test will always have a (calculated) duration of 1 second.

**Comment by suyash691** [comment]
It has been fixed. Closing this
