### ISSUE TITLE
Build steps jumping from 'skipped' to 'successful'. 

### ISSUE THREAD

**Issue by VladDerptastic** [Microsoft/azure-pipelines-tasks#9087]
Hello, folks. What I have is not a breaking bug, but it seems like an unexpected behaviour. 

#### Environment
I'm using a hosted agent of Azure Pipelines
Acc: vlad0359@stud.kea.dk
Org: vlad0359 (not terribly original I know)
Proj: EF.JA.Config
BN: 20181214.2
Agent: Hosted VS2017

#### Issue Description
It's a pipeline for getting NuGet package projects checked and then stored in my Artefacts.
However, at the end of the pipeline, this keeps happening - Everything is successful but a task is displayed as skipped: 
![step1](https://user-images.githubusercontent.com/17119930/50000990-b4046200-ff9b-11e8-8887-c38dbea18427.png)

It's not breaking anything, however. and when given a little bit more time, it just goes to this (out of a sudden) when completing the build:
![step2](https://user-images.githubusercontent.com/17119930/50001012-caaab900-ff9b-11e8-97b9-f4fb9b105814.png)

Build logs don't say anything about it, and I feel that's not how it's supposed to happen.

**Comment by bryanmacfarlane** [comment]
This repo is for tracking issues with /Tasks in this repo.

If you're having an issue with the service, you can report @ developer community
