### ISSUE TITLE
PublishTestResults does not publish test attachments for NUnit tests.

### ISSUE THREAD

**Issue by MarkKharitonov** [Microsoft/azure-pipelines-tasks#9093]
## Environment
- Server - TFS on-premises, version 16.131.27701.1

- Agent - Private:

Capability name | Capability value
-- | --
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.131.0

## Issue Description

The published NUnit test results do not contain any test attachments, even if the respective test results XML does list them.

I looked at the source code of `Microsoft.TeamFoundation.TestClient.PublishTestResults,  Version=16.0.0.0` and the attachments are only published for TRX logs.

**Comment by puagarwa** [comment]
We have fixed this issue sometime back. can you please try it and confirm. We haved it in Agent version >= 2.136

**Comment by MarkKharitonov** [comment]
I need to check if we can upgrade the agent.

**Comment by puagarwa** [comment]
HI,
  Did you able to validate it ? It will be great if you can confirm,

**Comment by MarkKharitonov** [comment]
We have an on-premises TFS 2018. It does not seem to come with the agent of the version you mention. Do I just download a newer agent from somewhere or must the TFS server be upgraded too?

**Comment by puagarwa** [comment]
You dont need to upgrade server but you can download newer agent from github releases and configure, agents are compatible with older TFS server. Let me know if you face any issue.

**Comment by MarkKharitonov** [comment]
A quick update - we upgraded the agent. I will monitor to see if there is any change.

**Comment by puagarwa** [comment]
@MarkKharitonov Any Update on the issue, can i mark it as fixed ?

**Comment by MarkKharitonov** [comment]
I did not have the time to test it yet. Please, keep the issue open. I will try to find the time during this week.

**Comment by MarkKharitonov** [comment]
I tested and it works with the new agent.
Thank you.

**Comment by SadagopanRajaram** [comment]
Closing the issue based on @MarkKharitonov response above.
