### ISSUE TITLE
[VsTest task] Vstest.console.exe error "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by TestO2015** [Microsoft/azure-pipelines-tasks#9095]
## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description
We have a Visual Studio Test task which fails with an error returned from vstest.console.exe. 
There were no test failures reported however not all were run; it appears it aborted before they completed.

Error from VsTest log:
>2018-12-13T00:33:18.5763881Z Total tests: Unknown. Passed: 146. Failed: 0. Skipped: 0.
2018-12-13T00:33:18.5763946Z Test Run Aborted.
2018-12-13T00:33:18.5763992Z Test execution time: 1.7709 Minutes
2018-12-13T00:33:18.5765323Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-12-13T00:33:18.6217988Z ##[error]Error: C:\hostedtoolcache\windows\VsTest\15.9.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe failed with return code: 1
2018-12-13T00:33:19.1708369Z ##[error]VsTest task failed.

Error from vstest.console.exe:
>2018-12-12T07:09:25.4749058Z TpTrace Error: 0 : 720, 12, 2018/12/12, 07:08:55.736, 15811144290, vstest.console.exe, Socket: Message loop: failed to receive message due to socket error System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
2018-12-12T07:09:25.4749141Z    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
2018-12-12T07:09:25.4749196Z    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

>2018-12-12T07:09:25.4749264Z    --- End of inner exception stack trace ---
2018-12-12T07:09:25.4749312Z    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2018-12-12T07:09:25.4749433Z    at System.IO.Stream.ReadByte()
2018-12-12T07:09:25.4749495Z    at System.IO.BinaryReader.ReadByte()
2018-12-12T07:09:25.4749548Z    at System.IO.BinaryReader.Read7BitEncodedInt()
2018-12-12T07:09:25.4749610Z    at System.IO.BinaryReader.ReadString()
2018-12-12T07:09:25.4749663Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
2018-12-12T07:09:25.4749739Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken 

[VisualStudioTestTask_log_18_5820.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2684005/VisualStudioTestTask_log_18_5820.zip)
[TestRunLog_log_19_5820.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2684006/TestRunLog_log_19_5820.zip)

**Comment by ShreyasRmsft** [comment]
@TestO2015 does this repro constantly with every run?

Does this happen if you run the tests on a self hosted agent also?

Can you provide a sample repro project if possible?

**Comment by TestO2015** [comment]
@ShreyasRmsft 
 The issue is intermittent occurring in ~30% builds.

Here's some details of our project in case it helps diagnosis:
-URL (I'm not sure if this includes the account name): https://dev.azure.com/bidscloud/
-Team Project name: Saturn
-Build definition name: R51 (id=50)
-Build definition number: R51_51.266.1.5872 (buildId=5872)
-Hosted agent pool name: Hosted VS2017

Let me know if there's any other info we can provide. Thanks.

**Comment by vagisha-nidhi** [comment]
@TestO2015 
This seems like the test host is crashing due to some reason. There is an advanced diagnostics feature which collects dump during a crash. This is pre-selected by default. If there are aborted runs because of test crashes, you will see the test run message and attachments, pointing to the faulty test cases. You can turn on collect dump as "Always" and share the memory dump.
![memory dump](https://user-images.githubusercontent.com/13175100/50759341-c9af3380-128a-11e9-8d12-173067fe8737.png)

Can you try this with the **latest version of test platform**? You can use the platform installer task to do this. 
![image](https://user-images.githubusercontent.com/13175100/50759567-5c4fd280-128b-11e9-8d0c-9b00aa203522.png)

**Comment by vagisha-nidhi** [comment]
@TestO2015 Any updates?

**Comment by kaadhina** [comment]
Closing this since we do not have enough info to investigate this further. Please reopen once you have the data asked above if you are still facing this.

**Comment by TestO2015** [comment]
Apologies for the delay, this issue is still occurring, could we please reopen this?

Here's what we've tried:

Enabled 'Collect advanced diagnostics in case of test failure'
    > No test failures were reported, but not all were run.

Set 'Collect Process Dump and attach to report to' 'Always' 
    > Where does this get attached to?

Ran the vstest.console.exe process with the /diag option and printed the results (already attached above)
    > vstest.console.exe, Socket: Message loop: failed to receive message due to socket error System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Used the latest version of the test platform.
    > It didn't solve the issue.

Thank you.

**Comment by prawalagarwal** [comment]
@TestO2015 Can you try out this:

1) Use the distributed mode of execution. You can do this in the advanced settings of the VsTest task
![image](https://user-images.githubusercontent.com/13520100/53937267-a0682380-40d2-11e9-9c70-4bd5298cc985.png)
You can specify any batch size. Dump collection works only in distributed mode. Apologies to have missed that in the earlier reply. 
2) Make sure you are on 15.9 platform and above for the above step to work. You can use the platform installer task to ensure this, by selecting "latest stable"
![image](https://user-images.githubusercontent.com/13520100/53937350-db6a5700-40d2-11e9-8f7e-8f105e71f6d6.png)
But make sure you have selected Test Platform version as installed by tools installer in the vstest task:
![image](https://user-images.githubusercontent.com/13520100/53937375-f046ea80-40d2-11e9-9537-7cce092dded9.png)

Now, once you are done with this, if a crash happens again, the dumps are attached as Test Run attachments (click on the test run in test summary tab):
![image](https://user-images.githubusercontent.com/13520100/53937432-17052100-40d3-11e9-8105-4604ad7d773b.png)

**Comment by prawalagarwal** [comment]
@TestO2015 any updates here?

**Comment by TestO2015** [comment]
Thank you @prawalagarwal . 

After enabling a custom batch size, test failures were reported with an error during the MSTEST cleanup routine of our tests. We've fixed the error during cleanup and it now works.

It appears that the SocketException error message was hiding actual test failures. If so that's something to fix.

**Comment by prawalagarwal** [comment]
Thanks for reporting back!
