### ISSUE TITLE
Azure Powershell task keeps user logged in after task ends

### ISSUE THREAD

**Issue by Geertvdc** [Microsoft/azure-pipelines-tasks#9100]
## Environment
- Server 
  - Azure Pipelines
    
- Agent
  - Private Agent Windows Server 2016 Datacenter

## Issue Description

We've created shared build agents for multiple teams to use which connect to Azure Pipelines. When we use the Azure Powershell task it will log in using a service principal that we select in the pull down menu.

the problem however is that this service principal is never logged out automatically. If you add a local powershell task after the Azure Powershell task it will continue using the same Service Principal. This is also the case for local Powershell tasks that run in the NEXT build. Shouldn't the user be logged out after the task ends?

If i compare it to the Azure CLI task this does log you out immediately after the task ends. At least this way it is inconsistent in how these tasks work.

### My opinion on how it should/could work:
- Make the default setting to log out when the task completes. (Secure by default)
- Add a checkbox to skip logging out if you might need the Azure Powershell session afterwards in other tasks (edge case)

**Comment by arjgupta** [comment]
@Geertvdc can you tell what is the version of azure powershell that you have installed on the machine ?

**Comment by Geertvdc** [comment]
@arjgupta I've checked on 2 different machines which both have same issue. They are running different versions of Azure Powershell:

```
Directory: C:\Modules\azurerm_6.12.0
ModuleType Version    Name                                ExportedCommands      
---------- -------    ----                                ----------------     
Script     6.12.0     AzureRM     
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands          
---------- -------    ----                                ----------------  
Script     2.1.0      AzureRM         
```

other machine is running


```
Get-Module -ListAvailable -name AzureRM
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.4.0      AzureRM
Script     5.7.0      AzureRM
```

the first machine is an agent that is built using the packer images used by the hosted agents: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=vsts

**Comment by Geertvdc** [comment]
I did some extra tests and it seems to be the case that everywhere where we use Azure RM 6.X this is happening while others that only have 5.7 or lower do not have this issue.

The hosted agents only have 5.7 currently so maybe that is why this issue is not on the hosted agents yet.

**Comment by rajatagrawal-dev** [comment]
@Geertvdc We have deployed the fix for this to all accounts. Let us know if you still face the issue.

**Comment by Geertvdc** [comment]
@rajatagrawal-dev i've tested it and it seems to log out the users now. Thanks for the change.

closed the pull request https://github.com/Microsoft/azure-pipelines-tasks/pull/9101 since it's not needed anymore

**Comment by kilasuit** [comment]
@rajatagrawal-dev is this a backend Azure Devops change or a change within this repo to the tasks?

Your answer is not clear and leaves me asking further questions for our own private hosted agents and also clients agents whether private or hosted as well

Could you elborate further?

**Comment by kmkumaran** [comment]
@kilasuit - This is change in the Tasks in this repo and the changes has been rolled out to all rings.
The fix will work for both private and hosted agents.

**Comment by kilasuit** [comment]
Could you provide a link to the commit/PR that included the change that fixed this for circular reference completion?  I.e so that others reading this thread can see what was changed where and when and by whom to fix this issue
