### ISSUE TITLE
Support "Debugging Tools for Windows"

### ISSUE THREAD

**Issue by zcbenz** [Microsoft/azure-pipelines-tasks#9109]
When writing some programs with features to automatically upload crash reports, it is required to have the `dbghelp.dll` and `dbgcore.dll` from "Debugging Tools for Windows" which is part of Windows SDK.

I think it should be installed by default, or there should be a way for users to install it separately.

**Comment by bryanmacfarlane** [comment]
azure-pipelines-image-generation might be a better repo.  It's the repo that gens the hosted images

**Comment by zcbenz** [comment]
Thanks, I have created https://github.com/Microsoft/azure-pipelines-image-generation/issues/614 for this.
