### ISSUE TITLE
Maven Task Not authorized when "Authenticate built-in Maven feeds" is enabled

### ISSUE THREAD

**Issue by teejam2** [microsoft/azure-pipelines-tasks#9110]
## Environment
- Azure Pipelines
- Account name: bcagroup
- Team project name: LOL
- Build definition name: ci_lolrequestdetectionserver
- Build number: #20181218.1
- Agent - Hosted
- Queue name: Hosted VS2017

## Issue Description
I have got an Azure Artifact called com.bca:testing
![image](https://user-images.githubusercontent.com/27975947/50143678-2d09ff00-02a5-11e9-8cae-4d85a3ebc9d7.png)
I have enabled Advanced > "Authenticate built-in Maven feeds"
![image](https://user-images.githubusercontent.com/27975947/50143477-9ccbba00-02a4-11e9-919a-eddab79bb3b4.png)
This throws the error:
Non-resolvable import POM: Could not transfer artifact com.bca:testing:pom:4.12-2 from/to bcagroup-visualstudio-com-bcagroup-lol (https://bcagroup.pkgs.visualstudio.com/_packaging/LOL/maven/v1): Not authorized , ReasonPhrase:Unauthorized.

Why??? Please help

### Task logs
[log_6_9542.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2689722/log_6_9542.zip)

### Error logs
Non-resolvable import POM: Could not transfer artifact com.bca:testing:pom:4.12-2 from/to bcagroup-visualstudio-com-bcagroup-lol (https://bcagroup.pkgs.visualstudio.com/_packaging/LOL/maven/v1): Not authorized , ReasonPhrase:Unauthorized.

**Comment by aasim** [comment]
Hi - We have recently released the MavenAuthenticate task that can be used in a pipeline to authenticate with Azure Artifacts and other Maven repositories. The design philosophy behind this task is that we would authenticate all the repositories you describe in this task, and get out of the way leaving you fully in control of running your mvn commands in the pipeline as you see fit.

You can read more about the MavenAuthenticate task here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops. It also gives some examples on how to configure the task.

I think this task is a good fit for your use case, you can use the MavenAuthenticate task to perform the authentication, and then use the same mvn command you use locally to run in the pipeline. Let me know if you need any more help in setting this up.

Aasim
