### ISSUE TITLE
Support to copy files and run powershell on virtual machines behind application gateway

### ISSUE THREAD

**Issue by miksteri** [microsoft/azure-pipelines-tasks#9115]
I'm currently having infrastructure of multiple VM's behind application gateway and I would like to use CD-pipeline to copy files and run powershell -scripts on those virtual machines to manage in-house solution upgrades properly.

When I use "Azure File Copy" -task at the moment, i get error: Unable to get FQDN for all resources in ResourceGroup : 'Name-of-AppGateway'".

**Comment by niadak** [comment]
@miksteri , Can you please use "Deployment Group" feature for your scenario. In this model we dont have WinRM or Remote Deployment dependency and deployment will be done in Pull based model. For more details refer to below documents.

https://devblogs.microsoft.com/devops/deployment-groups/
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops
