### ISSUE TITLE
Unhandled: read ECONNRESET on windows target

### ISSUE THREAD

**Issue by LoaderB0T** [microsoft/azure-pipelines-tasks#9117]
## Environment
- Server - Azure Pipelines
- Private Project, Hosted VS2017

## Issue Description

The Copy Files Over SSH Task fails in my release pipe with the error you can see below.
All the files are transferred without problems and after that the task still fails.
I've set it to continue on error but now every release finishes with a warning and I don't get an error if something actually fails.

I copy to a windows machine running OpenSSH.

When I select the option to clear the target folder before copying I also get the error that the "rm" command cannot be found. (See second log excerpt below, partially in German, sorry)

### Error logs

2018-12-18T16:44:27.9381300Z Completed copying 5 files to the remote machine.
2018-12-18T16:44:27.9926546Z ##[error]Unhandled: read ECONNRESET
2018-12-18T16:44:27.9978712Z ##[section]Finishing: Securely copy files to the remote machine

2018-12-18T18:34:21.9916863Z ##[error]Der Befehl "rm" ist entweder falsch geschrieben oder
2018-12-18T18:34:21.9925004Z konnte nicht gefunden werden.
2018-12-18T18:34:21.9925069Z 
2018-12-18T18:34:21.9957154Z ##[error]Failed to clean the target folder on the remote machine. Command rm -rf "C:\web\www\fhwebshop"/* exited with code 1.
2018-12-18T18:34:22.0336089Z ##[error]Unhandled: read ECONNRESET
2018-12-18T18:34:22.0475422Z ##[section]Finishing: Securely copy files to the remote machine

**Comment by yacaovsnc** [comment]
This issue is also tracked here:
https://developercommunity.visualstudio.com/content/problem/380609/release-pipeline-copy-files-over-ssh-task-fails-ev.html

**Comment by brcrista** [comment]
The thread above says this, but to cut to the point -- the way the task does SSH has a known issue when the _target_ machine is a Windows system.  I don't believe it repros all the time, but it comes up often enough that [we recommend using Windows File Copy instead](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh#is-this-task-supported-for-target-machines-running-operating-systems-other-than-linux) when the destination is a Windows machine.

**Comment by pfjonesey** [comment]
In our case the Use NuGet version task fails on the build (log output below).  Is there any fix for this yet?

##[section]Starting: Use NuGet 5.3.1
==============================================================================
Task         : NuGet tool installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
Version      : 0.158.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/prev-versions/nuget-installer-0
==============================================================================
ERR:read ECONNRESET
##[section]Finishing: Use NuGet 5.3.1
