### ISSUE TITLE
More Information link for GitHub tasks results in 404

### ISSUE THREAD

**Issue by heaths** [Microsoft/azure-pipelines-tasks#9119]
When trying to create a build definition on the web for Azure Pipelines (mainly to copy YAML out), the "More Information" link for the new GitHub Release tasks results in a 404. It currently points to:

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/GithubReleaseV0/README.md

**Comment by mdmdakbar** [comment]
@heaths  Thanks for reporting this issue.

We have fixed it and the link is working fine now.
