### ISSUE TITLE
GitHub Release task times out enumerating accessible projects in large organization

### ISSUE THREAD

**Issue by heaths** [Microsoft/azure-pipelines-tasks#9121]
When trying to configure the new GitHub Release task (v0) for the Microsoft organization on GitHub for devdiv.visualstudio.com - despite the service connection being valid (just re-authorized it to make sure this wasn't the problem), the drop down for the repo times out. And since it's not also editable, I can't simply type the repo name. Perhaps using an editable drop down and doing a partial match against the GitHub REST APIs would work better with this control.

As it is, I'm basically blocked from extracting YAML via this method and will have to read the task.json source in GitHub or https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/github-release to figure out the parameters.

**Comment by mdmdakbar** [comment]
@heaths Thanks for your feedback.

The issue is acknowledged and for now we will make a change to make repository input editable as well. 
Hopefully the fix will get released soon.

**Comment by heaths** [comment]
In the meantime since this is blocking release definition creation, is there some trick I can do using the F12 tools? Previously, I could edit the HTML for the `input` and set the `value` attribute but that took several tries. Now it doesn't seem to work at all.

**Comment by heaths** [comment]
The same trick did work with Chrome's F12 tools, to set the `input.value` attribute. So at least I can work around this for now.

**Comment by raiyanalam** [comment]
The drop down is editable now. 
We are also working towards making this drop down better in case there are large number of repos. Thanks for your feedback and help in making Azure DevOps Pipelines better!
