### ISSUE TITLE
MSBuild task does not recognize VS2019

### ISSUE THREAD

**Issue by jimmylewis** [microsoft/azure-pipelines-tasks#9122]
At first glance, this issue seems to be partly in:

1.  Select-MSBuildPath (located in Tasks\Common\MSBuildHelpers\PathFunctions.ps1), which has a hardcoded list of versions that goes up to 15.0
```
$versions = '15.0', '14.0', '12.0', '4.0' | Where-Object { $_ -ne $PreferredVersion }
```
2. Get-MSBuildPath which only does the vswhere.exe query when $version is 15.0 (also in Tasks\Common\MSBuildHelpers\PathFunctions.ps1)
```
        if (($Version -eq "15.0" -or !$Version) -and # !$Version indicates "latest"
            ($visualStudio15 = Get-VisualStudio_15_0) -and
            $visualStudio15.installationPath) {

            $msbuildUtilitiesPath = [System.IO.Path]::Combine($visualStudio15.installationPath, "MSBuild\15.0\Bin\Microsoft.Build.Utilities.Core.dll")
            if (Test-Path -LiteralPath $msbuildUtilitiesPath -PathType Leaf) {
                Write-Verbose "Loading $msbuildUtilitiesPath"
                $msUtilities = [System.Reflection.Assembly]::LoadFrom($msbuildUtilitiesPath)
            }
        }

        # Fallback to searching the GAC.
        # ...
```
3. Get-VisualStudio_15_0, which is fine by itself but probably needs to be refactored to handle 16.0 (similar to the change made to detect VS2019 for agent capabilities in https://github.com/Microsoft/azure-pipelines-agent/pull/2005)

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent: Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
**Agent is running Win2012R2 and the agent version is 2.144.1.**

## Issue Description

When using the MSBuild task on an agent which has VS2019 installed, the agent does not detect that instance of VS and will fallback to an earlier MSBuild agent.

In the log below, it fails to find the instance for VS 2019 (16.0), and falls back to MSBuild v4.0 as ships with .NET framework (the build then fails because of the /bl flag, which was introduced to MSBuild in 15.3).

### Task logs

>2018-12-18T21:52:06.0260909Z ##[section]Starting: Build (Debug)
2018-12-18T21:52:06.0449497Z ==============================================================================
2018-12-18T21:52:06.0449605Z Task         : MSBuild
2018-12-18T21:52:06.0449682Z Description  : Build with MSBuild
2018-12-18T21:52:06.0449739Z Version      : 1.120.2
2018-12-18T21:52:06.0449790Z Author       : Microsoft Corporation
2018-12-18T21:52:06.0449862Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613724)
2018-12-18T21:52:06.0449913Z ==============================================================================
2018-12-18T21:52:07.5293907Z ##[command]"D:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.120.2\ps_modules\MSBuildHelpers\vswhere.exe" **-version [15.0,16.0)** -latest -format json
2018-12-18T21:52:07.5983764Z ##[command]"D:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.120.2\ps_modules\MSBuildHelpers\vswhere.exe" **-version [15.0,16.0)** -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
2018-12-18T21:52:07.8418751Z ##[command]"C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" "d:\agent\_work\2\s\Extensions.msbuild" /nologo /nr:false /dl:CentralLogger,"D:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.120.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=|SolutionDir=d:\agent\_work\2\s"*ForwardingLogger,"D:\agent\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.120.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /t:SetupAll /bl:LogFile=d:\agent\_work\2\a\Logs\DebugBuild.binlog /p:_MSDeployUserAgent="VSTS_5dff9b53-b23e-4d16-b57b-fda3d1a4eac2_build_7_0"
2018-12-18T21:52:07.9224611Z MSBUILD : error MSB1001: Unknown switch.
2018-12-18T21:52:07.9225212Z Switch: /bl:LogFile=d:\agent\_work\2\a\Logs\DebugBuild.binlog
2018-12-18T21:52:07.9225381Z 
2018-12-18T21:52:07.9225474Z For switch syntax, type "MSBuild /help"
2018-12-18T21:52:08.1255312Z ##[error]Process 'msbuild.exe' exited with code '1'.
2018-12-18T21:52:08.1765835Z ##[section]Finishing: Build (Debug)

**Comment by jimmylewis** [comment]
This isn't as simple as replacing 15.0 with 16.0.  In VS2019, MSBuild is changing the version to 15.1, and the install path becomes `<VSRoot>\MSBuild\Current\Bin\MSBuild.exe` instead of `<VSRoot>\MSBuild\15.1\Bin\MSBuild.exe`.  Should $versions in `Select-MSBuildPath` have a new entry called 15.1 or 16.0?

The vswhere command in `Get-VisualStudio_15_0` (or it's replacement) should use 16.0 for the VS version, but the path in `Get-MSBuildPath` where it tries to load Microsoft.Build.Utilities.Core.dll will need to use MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll.

More details about the MSBuild change can be found at https://github.com/Microsoft/msbuild/issues/3778.

**Comment by azureDaveOps** [comment]
Austin is working on this now.

**Comment by onovotny** [comment]
What is the status of this and is there a workaround? This is a significant blocker to my projects as .NET Core 3 post preview 1 requires the MSBuild in VS 2019.

**Comment by jimmylewis** [comment]
@onovotny I was able to work around this for now by specifying the path in YAML:

```
-task: MSBuild@1
  inputs:
    msbuildLocationMethod: location
    msbuildLocation: c:\path\to\msbuild.exe
    ...
```

This requires knowing the path to msbuild on the agent.  My agent pool is configured the same so it worked out.

**Comment by moswald** [comment]
@onovotny Austin is out on vacation until after the New Year, but I'll follow up with him about it when he gets in.

**Comment by austin-jensen** [comment]
The MSBuild and VSBuild tasks were given VS2019 support in #9273 the VSTest and other tasks that use visual studio will have support added separately

**Comment by jimmylewis** [comment]
@austin-jensen are there issues tracking the remaining tasks?  I still have workarounds to make VSTest work on my agents (VS2019 only), and I'd like to know when I can remove them.

**Comment by Osmosis311** [comment]
How is this issue closed when Azure Pipelines still doesn't support msbuild 16?

**Comment by moswald** [comment]
Please accept our apologies, @Osmosis311. Austin left the company before verifying this fix. I'll reopen it and get it reassigned.

**Comment by Osmosis311** [comment]
Thank you.

**Comment by mika76** [comment]
Is there any news on this? I have on site TFS 2015 and the msbuild task also does not want to use 2019 (although 2017 is perfectly fine)

**Comment by MatejQ** [comment]
We currently migrated our solution to VS2019 and it builds fine locally, but build fails on the DevOps server (hosted agent build) because of the _ operator that is not recognized by earlier VS than 2019. I have set the "Visual Studio Version" property of the build step to VS2019 but it didn't help.
In the logs, there is warning:
##[warning]Visual Studio version '16.0' not found. Falling back to version '14.0'.
How come you even offer VS2019 in Visual Studio Version dropdown when it doesn't work at all? And people are having this issue in the last half year consistently. According to a different issue at github, it was supposed to be solved in hosted agent version 2.144.2 but current version is 2.155.1 and it still doesn't work? It's very disappointing. Please advise a workaround.

**Comment by azureDaveOps** [comment]
Thanks for reporting, I will have someone take look today and get back to you (likely by monday).

**Comment by WillLennon** [comment]
MatejQ, can you share your .yml file and the build logs?
I tried to use MSBuild v16.0 on the windows 2019 and it worked fine.  Here are my example files

my azure-pipelines.yml file:

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: MSBuild@1
    inputs:
      msbuildVersion: '16.0'    

and from my build logs:
##[command]"D:\a\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.1\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "d:\a\1\s\ConsoleApp1\ConsoleApp1.sln" /nologo /nr:false /dl:CentralLogger,

**Comment by MatejQ** [comment]
Hello,
I don't have any .yml file. We are using a build pipeline created by clicking and drag-and-dropping build steps and configuring them via DevOps GUI. The agent itself is hosted by MS. Anyway, I made some progress. I switched the agent pool from Hosted to Azure Pipelines (I don't know what's the difference between the two, apart from the fact that I can't switch back to Hosted now), which made another combobox visible - where version of windows and VS can be set separately. Now it worked, but build failed because we have Silverlight projects in the solution. We are using an unofficial vsix package to make SL projects available on developer PCs and they build and debug fine. We hope SL+RIA services can somehow be compiled on the VS2019 agent...

**Comment by nathanchere** [comment]
How is this still a problem 2 years later? :/

**Comment by JensLeible** [comment]
Hi there, are there any news on this or recommended workarounds for TFS 2018 build agents to detect MSBuild tools 2019?

**Comment by mika76** [comment]
@JensLeible I figured out a workaround - On the MSBuild Task, change the setting from `"Version"` to `"Specify Location"` and then set the path to the VS2019 msbuild exe (mine was `"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"`)

**Comment by JensLeible** [comment]
@mika76 Thank you. That would work for a single agent. What can I do in a setup with multiple agents if not all of them have 2019 build tools installed?

**Comment by mika76** [comment]
@JensLeible true it would not work - but I would ask then why are your build agents not consistent? if they aren't then you wouldn't get consistent results. And if you need a specific build to run on a specific agent you can always set it to always run on that agent in the build options. Or you could create a demand on the agent and require that demand in the build options.

**Comment by KirillOsenkov** [comment]
Also would be nice to be able to collect a binary log and (optionally) automatically publish as artifact

**Comment by DenisRumyantsev** [comment]
@jimmylewis, @JensLeible, @mika76

It looks like you have old TFS version installed and VS2019 support was added in a higher version.

I would suggest next options to resolve this issue:

1) update TFS (recommended).

2) use the solution that was suggested by @mika76:
add `msbuildLocationMethod: 'location'` and `msbuildLocation: 'C:\path\to\MSBuild.exe'` into MSBuild task inputs in your azure-pipelines.yml file.

3) manually update MSBuild task. For this solution you need to clone azure-pipelines-tasks repository and after that build MSBuildV1 task and upload this built task to your TFS using tfx-cli package.

Open your terminal and run next commands for third solution:

* `git clone https://github.com/microsoft/azure-pipelines-tasks.git`

* `cd azure-pipelines-tasks`

* `node make.js build --task MSBuildV1`

* `npm i -g tfx-cli`

* `tfx build tasks upload -u https://<organization>.visualstudio.com/<collection> -t <token> --task_path _build/Tasks/MSBuildV1`

**Comment by DenisRumyantsev** [comment]
@jimmylewis, @JensLeible, @mika76 Is this issue still actual to you?

**Comment by mika76** [comment]
Thanks for the summary @DenisRumyantsev - We have updated to azure devops server and it uses the latest msbuild now so no this isn't a problem for me any more.

**Comment by DenisRumyantsev** [comment]
@mika76 Thanks! Let me close this one since this resolved - please feel free to ask any further questions
