### ISSUE TITLE
Service fabric deploy task fails to detect SF SDK on x86 agent

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/azure-pipelines-tasks#9123]
`##[error]Service Fabric SDK is not installed on the build agent. Go to https://aka.ms/servicefabric to download and install it.`

It should look into x86 registry hive

**Comment by tejasd1990** [comment]
Fixed in [this PR](https://github.com/Microsoft/azure-pipelines-tasks/pull/9413). Closing this issue.
