### ISSUE TITLE
task.setvariable will not properly set out vars

### ISSUE THREAD

**Issue by KairuByte** [Microsoft/azure-pipelines-tasks#9126]
No matter what I attempt, I am unable to set output variables properly.

Very simple reproduce steps:

New build pipeline.

Two tasks:
1. Inline powershell script: Set output Reference name to "Test"
```
function Set-VstsVariable {
    param([String]$var, [String]$value, [Bool]$secret = $false)
    Write-Output ("##vso[task.setvariable variable=$var;isSecret=$secret;isOutput=true;]$value")
}

Set-VstsVariable("test", "Hello World")
```
2. DutchWorkz - Display all variables

Run with diagnostics and you will likely get the attached logs, showing that the variables were created, but the names have the values concatenated to them, and they have no values. Example: `TEST_TEST_HELLO_WORLD:`

Logs here: [logs_111.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2694958/logs_111.zip)

**Comment by JohannesDrexler** [comment]
That is not how you are supposed to call a function in powershell and that is why $value is empty.

Instead of 
`Set-VstsVariable("test", "Hello World")`
try this:
`Set-VstsVariable "test" "Hello World"`

**Comment by Anufriev** [comment]
Hi @KairuByte!

I faced with the same needs today. I found a working solution

1th step
`$SASToken= 7
Write-Output ("##vso[task.setvariable variable=SASToken;]$SASToken")`

2th step
`Write-Host $env:SASToken`

**Comment by KairuByte** [comment]
@JohannesDrexler Well I certainly have egg on my face. Thank you very much for noticing that, as you can probably tell PowerShell is not one of my core languages and I'm mainly just stumbling through it. I made the change and it works 100%, thank you again!
