### ISSUE TITLE
Document how to specify password for Copy Files Over SSH

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/azure-pipelines-tasks#9128]
I'd like to request for the Cope Files Over SSH it be documented how the SSH password can be securely passed to the task.

[In the documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=vsts#arguments) is just says that *the private key and the passphrase must be specified for authentication*, but not how.

I am interested in how to do this using the YAML build definition only, the GUI way would be also fine assuming it is clear how to translate those GUI actions to YAML.

I am not sure how safe is to use e.g. environment variables for this, if it's secure enough (no changes other agents on the shared pool for open source will be able to see it), I'll take it, but if not, it would be beneficial to provide a guide on how to connect and use say KeyVault in order to be able to temporarily obtain the password from a safe source and forget it after the copying is done.

**Comment by yacaovsnc** [comment]
Can you use [secret variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#secret-variables)?

**Comment by TomasHubelbauer** [comment]
Probably! Looks like I will have to specify both the user name and the password as a part of the endpoint, I don't see how else I would pass that into the task, but secret variables (which I didn't know about) seem like to way to go about this. Thank you.

**Comment by TomasHubelbauer** [comment]
There's a little more to this after all. I've documented what I've came up with in a comment in MicrosoftDocs/vsts-docs#1918.
