### ISSUE TITLE
How to force build agent to use `d:` drive in Azure VM?

### ISSUE THREAD

**Issue by ackava** [Microsoft/azure-pipelines-tasks#9134]
Azure VM comes with D drive that is local SSD hard disk. How to force **Build Agent** to make use of d drive for work folder and temp files.

Installing agent in D drive is not possible as it VM will loose entire drive after restart. If we can configure `work` and `temp` folder on D drive, it will significantly improve performance for agents hosted on Azure VM.

**Comment by JohannesDrexler** [comment]
When configuring the agent the script will ask you where the work-directory should be located. Pay attention when setting up the connection and configure _work to be in D:\.....

By the way: this belongs into this repo -> https://github.com/Microsoft/azure-pipelines-agent

**Comment by JohannesDrexler** [comment]
There is also a config-file in the agent-directory that contains the path of _work so you can redirect the _work-directory without having to set up a new agent

**Comment by ackava** [comment]
@JohannesDrexler I already did and it does not work, Agent creates work folder and expects it to be there, if it is not there agent does not start.

So when you first time install agent and configure work folder, it works till it restarts.

**Comment by JohannesDrexler** [comment]
strange... i had this setup with some buildservers and it worked. i'll try to reproduce this later today. which agent version do you use ?

**Comment by ackava** [comment]
@JohannesDrexler sorry, I had wrong path set, it is working correctly.

**Comment by JohannesDrexler** [comment]
what a relief ^^

**Comment by JohannesDrexler** [comment]
@ackava can this issue be closed now ?

**Comment by ackava** [comment]
@JohannesDrexler yes, though I would recommend updating documentation to highlighting this feature for others.

**Comment by JohannesDrexler** [comment]
You could suggest this in the repo for the build agent -> https://github.com/Microsoft/azure-pipelines-agent

This repo here is for build/release tasks, not the agent
