### ISSUE TITLE
Azure PowerShell fails on self hosted x86 agents

### ISSUE THREAD

**Issue by bogdancucosel** [microsoft/azure-pipelines-tasks#9146]
The failure is:
Cannot find path 'HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall' because it does not exist.

It happens on x86 agents, we tried Windows 8.1 and Windows 10

## Environment
- Server - Azure Pipelines uipath, activities, cd - tests - development, releaseId=3611
- Agent - Private: 
Windows 8.1 Agent.OSVersion | 6.3.9600, Agent.Version | 2.141.0
Windows 10 Agent.OSVersion | 10.0.17134, Agent.Version | 2.141.0

## Issue Description
Failing task Azure PowerShell, version 3.1.10

### Task logs
[windows_10_logs.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2702749/windows_10_logs.zip)

**Comment by arjgupta** [comment]
Thanks for reporting this issue. We will work on fixing this.

**Comment by 20shivangi** [comment]
@bogdancucosel Which Azure PowerShell version (x86 or x64) have you used ? Please refer to this link to get x86 version of Azure PowerShell msi : 
https://github.com/Azure/azure-powershell/releases/tag/v6.13.1-November2018

**Comment by bogdancucosel** [comment]
@20shivangi e have different versions.
We tried with 5.7.0 right now, and with the new version of the task , we get :

##[section]Starting: Azure PowerShell script: InlineScript
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 3.1.24
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
==============================================================================
Added TLS 1.2 in session.
The list of available Azure modules:

Name  Version
----  -------
Azure 5.1.2  


The list of available AzureRM modules:

Name    Version
----    -------
AzureRM 5.7.0  


##[command]Disconnect-AzureRmAccount -Scope Process -ErrorAction Stop
##[warning]Run Connect-AzureRmAccount to login.
##[error]Could not find the modules: 'AzureRM' with Version: '5.1.2'. If the module was recently installed, retry after restarting the Azure Pipelines task agent.
##[section]Finishing: Azure PowerShell script: InlineScript

**Comment by 20shivangi** [comment]
@bogdancucosel 
If the machine is 64 bit, then x-64 version of Azure RM module must be installed . If you install x86 version of Azure RM module the error saying  "Could not find the modules: AzureRM with Version: 5.1.2. If the module was recently installed, retry after restarting the Azure Pipelines task agent." is given .

**Comment by bogdancucosel** [comment]
No, the machine is a 32 bit machine.

Agent.OSArchitecture | X86
-- | --

**Comment by 20shivangi** [comment]
@bogdancucosel  And what is Azure RM module version , it is x86 ?

**Comment by bogdancucosel** [comment]
@20shivangi I do not understand. Yes it is, I can install Azure Rm x64 version on a x86 OS ?

**Comment by arjgupta** [comment]
Hey @bogdancucosel There is an input in the task that let's you specify the version of Azure PowerShell that should be imported by the task. Can you specify the version of azure powershell that you have installed on your machine in this input and then try running the task ? The version should be a proper semantic version <Major>.<Minor>.<Patch> i.e. 5.7.0 or 6.13.1 etc.

**Comment by bogdancucosel** [comment]
@arjgupta the version was 5.7.0

**Comment by arjgupta** [comment]
Did you specify the version in the Input and then try to run the task ? I believe that should work correctly. Can you try this and let me know.

**Comment by 20shivangi** [comment]
@bogdancucosel  Is there any update ?

**Comment by chshrikh** [comment]
please let us know if there is any issues
