### ISSUE TITLE
Universal Packages Download task fails on x86 self hosted agents

### ISSUE THREAD

**Issue by bogdancucosel** [microsoft/azure-pipelines-tasks#9147]
The error is:
Error: Failed to get artifact tool metadata from source url https://uipath.vsblob.visualstudio.com/_apis/clienttools/artifacttool/release?osName=windows&arch=ia32

## Environment
- Server - Azure Pipelines 
- Agent - Private: 

Windows 7 Agent.OSVersion | 6.1.7601, Agent.Version | 2.141.0
But it does not really matter, it happens on any x86 OS

## Issue Description
 You can find the debug logs: 
[universal_package_w7_x86_log.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2702766/universal_package_w7_x86_log.zip)

**Comment by alexmullans** [comment]
@bogdancucosel is this still happening?

**Comment by bogdancucosel** [comment]
@alexmullans sorry for the late reply.
I just checked, now i get a message like :
##[error]Failed to get artifact tool. Universal Packages require an x64 agent.

So, this is not going to work ?

**Comment by mitchdenny** [comment]
Unfortunately we don't currently produce an x86 version of Artifact Tool. We'll need to look into our dependency graph to see whether we can support it.

**Comment by mitchdenny** [comment]
@bogdancucosel I managed to produce a test build of a win7-x86 compatible version of our artifact tool. Let me know if you are interested in trying it out (we haven't pushed it through the release pipeline, we are just trying to see whether it can work at all initially).

**Comment by bogdancucosel** [comment]
@mitchdenny yes please, how do I do that ?

**Comment by mitchdenny** [comment]
Shoot me an e-mail at midenn at microsoft com and I'll walk you through how to try it out.

**Comment by elbatk** [comment]
Hey people @bogdancucosel  & @mitchdenny , did you both reconvene here?

**Comment by mitchdenny** [comment]
I gave @bogdancucosel a private build that worked for x86 just to validate it works (not supported) but there was no immediate plans to support x86.

**Comment by bogdancucosel** [comment]
Though that would be great. 
We use x86 agents for testing and we are currently using Azure to upload and download stuff. 
People using this do not necessarily have access to Azure, nor they know how to use it. 
So, for us it would really make sense to have this.

**Comment by bryanmacfarlane** [comment]
@infin8x - we support x86 build agents in azure pipelines.  can we get this added?

**Comment by infin8x** [comment]
Added to the backlog, but not something we'll get to this quarter. Will see where it falls on next quarter's stack of Universal Package asks.

**Comment by bogdancucosel** [comment]
Ok, thanks
