### ISSUE TITLE
Code coverage tab does not render utf8 characters

### ISSUE THREAD

**Issue by kachkaev** [Microsoft/azure-pipelines-tasks#9150]
Task: **Publish Code Coverage Results** (v 1.*)

I'm publishing HTML coverage reports generated by istanbul with the help of workarounds shared in https://github.com/Microsoft/azure-pipelines-tasks/issues/3027. The result is styled correctly, but there is a problem with unicode characters both in FF and Chrome:

![screenshot 2018-12-21 at 16 43 46](https://user-images.githubusercontent.com/608862/50353278-a1f86580-053f-11e9-8f51-42c4545f3d5a.png)

These are supposed to be `3×`, `2×` and `1×` (× being a [utf8 multiplication sign](https://www.fileformat.info/info/unicode/char/00d7/index.htm)).

The symbol is display correctly locally, but not after I upload the HTMLs to VSTS. The reason is because VSTS strips `<meta />` html tags from the HTMLs including `<meta charset="utf-8" />`.

What would recommend to do to overcome this limitation? Character `×` is not the only non-ASCII symbol that the coverage reports can contain. Other examples include emojis in code as well as comments in Chinese or Cyrillic.

**Comment by nigurr** [comment]
@kachkaev Thanks for reporting this. Currently we are revamping the code coverage experience and no plans to enhance current experience.
Closing this issue and we assure that this experience will be improved sooner.

**Comment by kachkaev** [comment]
Thanks for your reply @nigurr! What link would you recommend me to track not to miss the update? What’s the approx order of the ETA (days, weeks, months)?

Feeling quite excited!

**Comment by nigurr** [comment]
@kachkaev Please follow Azure DevOps Release Notes, we update the rollout in the notes. Currently we can't share the exact timelines, however the work is in progress.
