### ISSUE TITLE
PublishPipelineArtifact fails when it encounters an empty subdirectory

### ISSUE THREAD

**Issue by rgiese** [Microsoft/azure-pipelines-tasks#9168]
Encountered on Azure Pipelines with a hosted Ubuntu agent.

Example error message when trying to create an artifact out of `frontend/out`:

`Access to the path '/home/vsts/work/1/s/frontend/out/_next/xbuZruUi6mEsakGX7ZY0k' is denied.`

In this case, the given directory is an empty subdirectory, and the agent account definitely has access to it (confirmed via ls -laR injected in YML). Note that this is a subdirectory underneath the source directory that the PublishPipelineArtifact task is targeted at.

The work-around is to delete all empty directories with (e.g.) `find out -type d -empty -delete` in the previous task.

**Comment by mitchdenny** [comment]
Thanks for reporting this. We already have a fix in the pipeline.

**Comment by mitchdenny** [comment]
Just an update on this. I checked with our team, we've fixed some code on the internal service which hasn't been deployed yet, once that roles out some of the dependencies of the Azure Pipelines Agent will get updated which is where the bug for this exists.

Adding @TingluoHuang and @fadnavistanmay

**Comment by mitchdenny** [comment]
Yep
