### ISSUE TITLE
NPM task doesnt update working directory after build task

### ISSUE THREAD

**Issue by sylar217** [Microsoft/azure-pipelines-tasks#9170]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines 
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
   Account Name: decentralized-identity
   Project Name: Core
   Build Definition Name: sidetree-core
   Build Number: 174
   Build link: https://decentralized-identity.visualstudio.com/Core/_build/results?buildId=174
- Agent - Hosted Ubuntu 1604

## Issue Description
 The project is a typescript code and the build command generates the output in the dist folder in the default working directory. In the next task, on running the jasmine tests, it doesn't recognize the dist folder which was outputted as part of the previous build task.

[NPMTestFailedLog.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2708719/NPMTestFailedLog.zip)

**Comment by mitchdenny** [comment]
Do you mean that the dist folder is not present - or that the working folder is not set to the dist folder?

**Comment by mitchdenny** [comment]
I'd recommend doing a tree listing from ```$(System.DefaultWorkingDirectory)``` to get a sense of the source tree layout after the build step. That will prove one way or the other that the dist files are where you think they are and then help you debug why some of the tests are failing.

**Comment by sylar217** [comment]
> I'd recommend doing a tree listing from `$(System.DefaultWorkingDirectory)` to get a sense of the source tree layout after the build step. That will prove one way or the other that the dist files are where you think they are and then help you debug why some of the tests are failing.

Sure, will do that and revert back

**Comment by sylar217** [comment]
Its working on the latest build that i tried, hence closing the issue
