### ISSUE TITLE
Add an Upload Secure File task

### ISSUE THREAD

**Issue by viertaxa** [microsoft/azure-pipelines-tasks#9172]
As a VSTS user, it would be immensely helpful to be able to upload/update secure files from a build task. For example, LetsEncrypt certs that expire every 90 days. The renewal task could be automated and moved to a build task to eliminate the need for specific hardware running that job outside of control. 

In the meantime, is there an API endpoint for managing secure files?

**Comment by madhurig** [comment]
@viertaxa - we have APIs that allow uploading new secure files. They are not on our docs page, that is a gap which we will look into. We don't allow updating the contents of an existing secure file, you have to currently delete and create new one which will create a new unique ID for the file. 

```
POST https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name={fileName}

Content-Type=application/octet-stream
```
Thanks,
Madhuri

**Comment by dinaharan** [comment]
> @viertaxa - we have APIs that allow uploading new secure files. They are not on our docs page, that is a gap which we will look into. We don't allow updating the contents of an existing secure file, you have to currently delete and create new one which will create a new unique ID for the file.
> 
> ```
> POST https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name={fileName}
> 
> Content-Type=application/octet-stream
> ```
> 
> Thanks,
> Madhuri

@madhurig What is the API call to delete the existing securefile?  Tried the following

DELETE https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name={fileName}

but got the following message "HTTP Error 405: Method Not Allowed".

We need the API call to delete the securefile to create the new one with updated data.

Thanks,
Dina.

**Comment by bondarewicz** [comment]
@madhurig or anyone who might came across this, 
Is there any way to enable "Authorize for use in all pipelines" for any file uploaded via above `POST` method? is there any additional parameter or something?

![image](https://user-images.githubusercontent.com/435051/75698003-d02a1700-5ca5-11ea-9891-f98e3b6eed09.png)

**Comment by bondarewicz** [comment]
additionally how do can you download the previously uploaded file?
`GET https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles/{fileGuid}?download=true` does not seem to work...

**Comment by fortunacio** [comment]
> @madhurig or anyone who might came across this,
> Is there any way to enable "Authorize for use in all pipelines" for any file uploaded via above `POST` method? is there any additional parameter or something?
> 
> ![image](https://user-images.githubusercontent.com/435051/75698003-d02a1700-5ca5-11ea-9891-f98e3b6eed09.png)

hey @bondarewicz, did u find the solution?

**Comment by wahmed23** [comment]
Hi, has anyone in this thread used the API mentioned by Madhurig? I am talking about 
POST
https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name={fileName}

Content-Type=application/octet-stream

**Comment by GeromeRen** [comment]
@wahmed23 Yes, i was able to test it out: 

test.ps1:

`param
(
    [Parameter(Mandatory=$true)] [string] $PAT,
    [Parameter(Mandatory=$True)][ValidateNotNullOrEmpty()]$AzureDevOpsOrg,
    [Parameter(Mandatory=$True)][ValidateNotNullOrEmpty()]$AzureDevOpsProjectID,
    [Parameter(Mandatory=$true)] [string] $SecureNameFile2Upload,
    [Parameter(Mandatory=$true)] [string] $SecureNameFilePath2Upload
)

try{
    $base64AuthInfo=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "",$PAT)))
    $uploadSecureFileURI="https://dev.azure.com/$AzureDevOpsOrg/$AzureDevOpsProjectID/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name=$SecureNameFile2Upload"
    $headers = @{
        Authorization=("Basic {0}" -f $base64AuthInfo)
    }
    Invoke-RestMethod -Uri $uploadSecureFileURI -Method Post -ContentType "application/octet-stream" -Headers $headers -InFile "$SecureNameFilePath2Upload"
}
catch
{
    write-host -f Red "Error upload client certificate file [$SecureNameFilePath2Upload] to AzureDevOps secure file!" $_.Exception.Message
    throw "Error occors -> $_.Exception.Message"
}`

**Comment by CptSandblaster** [comment]
> @wahmed23 Yes, i was able to test it out:
> 
> test.ps1:
> 
> ```
> param
> (
>     [Parameter(Mandatory=$true)] [string] $PAT,
>     [Parameter(Mandatory=$True)][ValidateNotNullOrEmpty()]$AzureDevOpsOrg,
>     [Parameter(Mandatory=$True)][ValidateNotNullOrEmpty()]$AzureDevOpsProjectID,
>     [Parameter(Mandatory=$true)] [string] $SecureNameFile2Upload,
>     [Parameter(Mandatory=$true)] [string] $SecureNameFilePath2Upload
> )
> 
> try{
>     $base64AuthInfo=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "",$PAT)))
>     $uploadSecureFileURI="https://dev.azure.com/$AzureDevOpsOrg/$AzureDevOpsProjectID/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name=$SecureNameFile2Upload"
>     $headers = @{
>         Authorization=("Basic {0}" -f $base64AuthInfo)
>     }
>     Invoke-RestMethod -Uri $uploadSecureFileURI -Method Post -ContentType "application/octet-stream" -Headers $headers -InFile "$SecureNameFilePath2Upload"
> }
> catch
> {
>     write-host -f Red "Error upload client certificate file [$SecureNameFilePath2Upload] to AzureDevOps secure file!" $_.Exception.Message
>     throw "Error occors -> $_.Exception.Message"
> }
> ```

What kind of response are you getting?

I get 
```% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   743  100   693  100    50   9240    666 --:--:-- --:--:-- --:--:--  9906
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://{a long path which just redirects to the org page of azure devops}">here</a>.</h2>
</body></html>
```

So I would assume that the command went through. However, I see no new secure files in Pipelines -> Library -> Secure files.
What could be wrong?

**Comment by Gupta-Amrit** [comment]
For secure file delete use PUT API https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles/{secureFileID}?api-version=5.0-preview.1

And for secure file upload use POST API https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles?name={fileName}&api-version=5.0-preview.1
Content-Type=application/octet-stream

**Comment by damccorm** [comment]
I'm going to close this issue since we are not planning on adding a task for this and I believe all questions have been answered. If there are any further issues with these APIs, please open a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html or open a docs bug at https://github.com/MicrosoftDocs/azure-devops-docs/issues/new

**Comment by adrianblakey** [comment]
Any ideas why this fails:
$ curl --trace-ascii /tmp/dump.txt  -v -H 'Content-Length: 1634' -L -X POST -H 'Content-Type: application/octet-stream' --data-binary keys.tgz 'https://dev.azure.com/YY/XX/_apis/distributedtask/securefiles?name=foo_test.tgz&api-version=5.0-preview.1'
Warning: -v, --verbose overrides an earlier trace/verbose option
* About to connect() to dev.azure.com port 443 (#0)
*   Trying 13.107.42.20...
* Connected to dev.azure.com (13.107.42.20) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=dev.azure.com
*       start date: Nov 18 13:11:54 2020 GMT
*       expire date: Nov 18 13:11:54 2021 GMT
*       common name: dev.azure.com
*       issuer: CN=Microsoft RSA TLS CA 01,O=Microsoft Corporation,C=US
> POST /YY/XX/_apis/distributedtask/securefiles?name=foo_test.tgz&api-version=5.0-preview.1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: dev.azure.com
> Accept: */*
> Content-Length: 1634
> Content-Type: application/octet-stream
>
* upload completely sent off: 45 out of 45 bytes
* SSL read: errno -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (56) TCP connection reset by peer

**Comment by slmagus** [comment]
> 
> 
> For secure file delete use PUT API [https://dev.azure.com/{organization}/{project}/_apis/distributedtask/securefiles/{secureFileID}?api-version=5.0-preview.1](https://dev.azure.com/%7Borganization%7D/%7Bproject%7D/_apis/distributedtask/securefiles/%7BsecureFileID%7D?api-version=5.0-preview.1)

Actually you need to use a DELETE method. Not a PUT method in order to remove a secure file. This will return a HTTP status code 204 when successful with an empty response.

**Comment by EmilAlipiev** [comment]
Is it possible to delete secure file by name instead of Id or 
is it possible to override if secure file with the same name already exist? I get conflict if secure file already exist. I couldnt find any parameter like force or replace etc.

**Comment by matejkooo** [comment]
This looks that it's working to upload secure files with rest api with version 5.0-preview... Since it is preview (although pretty old), is it possible to use it in production environment? Or how likely that is that it will stop functioning?

**Comment by matejkooo** [comment]
Is there a way how to restore deleted secure file?
Even if all permissions on secure file is set to Reader, Project Admins can delete this item. Is it possible to restore the secure file?

**Comment by myflashlab** [comment]
a summary of all above conversations:

```
GET - list all the secure files
https://dev.azure.com/{{organization}}/{{project}}/_apis/distributedtask/securefiles?api-version={{api_version}}

POST - upload a new secure file
https://dev.azure.com/{{organization}}/{{project}}/_apis/distributedtask/securefiles?api-version={{api_version}}&name=fromPostman
Content-Type=application/octet-stream

DELETE - Delete a secure file with its ID
https://dev.azure.com/{{organization}}/{{project}}/_apis/distributedtask/securefiles/{{secureid}}?api-version={{api_version}}

GET - read details of a secure file with its ID
https://dev.azure.com/{{organization}}/{{project}}/_apis/distributedtask/securefiles/{{secureid}}?api-version={{api_version}}
```

**Comment by dimizuno** [comment]
If this API endpoint exists since 2019 why is it still not officially added to the API documentation?

Is there some kind of "authorize" parameter I can use to set no restrictions for pipeline permissions?

**Comment by sang-truong-tan** [comment]
It's already 2023, yet the securefiles API endpoint is still nowhere to be found.

**Comment by sbondarenko-msft** [comment]
Does anyone know how I can **download** a secure file using REST API?
I've only seen `list/upload/delete/get info` in this thread so far.

**Comment by bgowers** [comment]
I am using this API on a pipeline triggered by a CRON job in order to rotate keys stored in secure files. I'm using the `GET`, `DELETE` and `POST` methods against multiple projects with success, but I still manually need to set the pipeline permissions.

Do we know if there's a way to set the pipeline permissions via some query param of the POST request?

**Comment by ChrisF987-coles** [comment]
@bgowers @dimizuno did you find any way to automatically set the pipeline the permissions?

**Comment by bgowers** [comment]
> @bgowers @dimizuno did you find any way to automatically set the pipeline the permissions?

@ChrisF987-coles yes I did!

You can use the [Update Pipeline Permissions For Resource endpoint](https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.0&tabs=HTTP).

I used it like:

```
...

create_secure_file_endpoint="https://dev.azure.com/$org/$project/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name=$secure_file_name"

create_secure_file_response=$(curl -s -X POST -u "$PAT_USER:$PAT_SECRET" -H "Content-Type: application/octet-stream" --data-binary @$NEW_KEY_FILEPATH "$create_secure_file_endpoint")

new_secure_file_id=$(echo $create_secure_file_response | jq '.id' | tr -d '"')
  update_secure_file_permissions_endpoint="https://dev.azure.com/$org/$project/_apis/pipelines/pipelinepermissions/securefile/$new_secure_file_id?api-version=7.0-preview.1"

curl -X PATCH \
  -u "$PAT_USER:$PAT_SECRET" \
  -H 'Content-Type: application/json' \
  --data-raw '{
      "allPipelines": {
        "authorized": true
      }
    }' \
  "$update_secure_file_permissions_endpoint"
```

I hope that helps!

**Comment by ChrisF987-coles** [comment]
> > @bgowers @dimizuno did you find any way to automatically set the pipeline the permissions?
> 
> @ChrisF987-coles yes I did!
> 
> You can use the [Update Pipeline Permissions For Resource endpoint](https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.0&tabs=HTTP).
> 
> I used it like:
> 
> ```
> ...
> 
> create_secure_file_endpoint="https://dev.azure.com/$org/$project/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name=$secure_file_name"
> 
> create_secure_file_response=$(curl -s -X POST -u "$PAT_USER:$PAT_SECRET" -H "Content-Type: application/octet-stream" --data-binary @$NEW_KEY_FILEPATH "$create_secure_file_endpoint")
> 
> new_secure_file_id=$(echo $create_secure_file_response | jq '.id' | tr -d '"')
> 
> update_secure_file_permissions_endpoint="https://dev.azure.com/$org/$project/_apis/pipelines/pipelinepermissions/securefile/$new_secure_file_id?api-version=7.0-preview.1"
> 
> curl -X PATCH \
>   -u "$PAT_USER:$PAT_SECRET" \
>   -H 'Content-Type: application/json' \
>   --data-raw '{
>       "allPipelines": {
>         "authorized": true
>       }
>     }' \
>   "$update_secure_file_permissions_endpoint"
> ```
> 
> I hope that helps!

Yep that helps! Thanks very much @bgowers

**Comment by bjornhofer** [comment]
As there is still no documentation or something else - I'll share my current approach.

### Background
As soon as a file changes, Terraform will trigger the powershell script to update the file (id_rsa)
id_rsa is used for [SSH-Plugin](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/install-ssh-key-v0?view=azure-pipelines&viewFallbackFrom=azure-devops)

### Code
```
# create a secure file in Azure DevOps
# This script will upload the file id_rsa to Azure DevOps SecureFiles
# If the file already exists, it will delete the file and upload the new file

$base64AuthInfo=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "",(Get-Item Env:AZDO_PERSONAL_ACCESS_TOKEN).Value)))
$uploadSecureFileURI="https://dev.azure.com/$((Get-Item Env:ORGANIZATION).Value)/$((Get-Item Env:PROJECT).Value)/_apis/distributedtask/securefiles?api-version=5.0-preview.1"
$headers = @{
    Authorization=("Basic {0}" -f $base64AuthInfo)
}

Write-OutPut "Checking if secure file already exists..."
$response = Invoke-RestMethod -Uri $uploadSecureFileURI -Method Get -Headers $headers

# No files in SecureFiles
if ($response.count -eq 0) {
    Write-OutPut "No files in SecureFiles uploading"
    Invoke-RestMethod -Uri "$uploadSecureFileURI&name=id_rsa" -Method Post -ContentType "application/octet-stream" -Headers $headers -InFile "id_rsa"
}
# Files in SecureFiles
else {
    # Check if file already exists - delete and upload
    Write-OutPut "Deleting and uploading file"
    if ($response.Value.name -eq "id_rsa") {
        $deleteitemid = $filteredId = $response.Value | Where-Object { $_.name -eq "id_rsa" } | Select-Object -ExpandProperty id
        $deleteSecureFileURI="https://dev.azure.com/$((Get-Item Env:ORGANIZATION).Value)/$((Get-Item Env:PROJECT).Value)/_apis/distributedtask/securefiles/$($deleteitemid)?api-version=5.0-preview.1"
        Invoke-RestMethod -Uri $deleteSecureFileURI -Method Delete -Headers $headers
        Invoke-RestMethod -Uri "$uploadSecureFileURI&name=id_rsa" -Method Post -ContentType "application/octet-stream" -Headers $headers -InFile "id_rsa"
    }
    # If no file with the name id_rsa exists
    else {
        Write-OutPut "File not found in SecureFiles uploading"
        Invoke-RestMethod -Uri "$uploadSecureFileURI&name=id_rsa" -Method Post -ContentType "application/octet-stream" -Headers $headers -InFile "id_rsa"
    }
}
```

Not the best solution but for updating a file on demand - it fits ;-)

**Comment by M-Nasser-Vois** [comment]
for updating a secure file permission for a pipeline or make it open to all pipeline 

use this URL
 ```
$updateSecureFilePermissionsEndpoint = "https://dev.azure.com/$organization/$project/_apis/pipelines/pipelinepermissions/securefile/$secureFileId?api=7.1-preview.1"

$headers = @{
    Authorization  = "Basic $base64AuthInfo"
    "Content-Type" = "application/json"
}

    # allow open access
    # $permissionsBody = @{
    #     name = $secureFileResponse.value.name
    #     allPipelines = @{
    #         authorized = $true
    #     }
    # }

    $permissionsBody = @{
        name = $secureFileResponse.value.name
        pipelines = [{
                id: 1,
                authorized: true
}]
    }

$permissionsResponse = Invoke-RestMethod -Uri $updateSecureFilePermissionsEndpoint -Method Patch -Headers $headers -Body $permissionsBody
```

**Comment by abir-dg** [comment]
how do can i download a secret file using the api ? , thank you

**Comment by sezquerro-reyes** [comment]
Hi, I need to download secure file from pipeline as well.
