### ISSUE TITLE
NuGet Installer Task - App is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Project App1 supports: netstandard2.0

### ISSUE THREAD

**Issue by kgbuddhima** [Microsoft/azure-pipelines-tasks#9174]
## Issue Description

Xamarin.Android Build Task fails with following errors. Seems The task try to compile the Portable app (.Net standard) using the Target platform of Native app (Android/iOS).

Project App1 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Project App1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with MonoAndroid,Version=v8.1.

Project App1 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Project App1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with Xamarin.iOS,Version=v1.0 (win).

### Task logs
![image](https://user-images.githubusercontent.com/14989528/50433423-22331800-08fe-11e9-87f5-166e67a6c261.png)
[](url)

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
![image](https://user-images.githubusercontent.com/14989528/50433444-3ecf5000-08fe-11e9-8f43-0344742eb628.png)

## Task Warnings

and also I have following warnings..

[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache
[warning]Can\'t find loc string for key: Info_UsingVersion

### Error logs

[log_8_15814.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2709537/log_8_15814.zip)

Can you please explain what is the issue ?

**Comment by salvmd** [comment]
Hi, the logs show this is not an issue in Packaging (all responses to restore are OK), but rather an error in the compatibility check after downloading the packages. The warnings are also not related to the failure in the compatibility check. Removing Area: Packaging label. 

Unfortunately, my team doesn't have much expertise building for Android, so we can't provide much guidance here. From what I know, the framework that NuGet should restore for should be inferred from the project's target (in this case the frameworks targeted by App1.Android.csproj and App.UITest1.csproj). It would be strange if these are not specifying MonoAndroid v8.1 as the target, yet NuGet is attempting to restore packages for it, but I'm not familiar enough with this to say if this is actually unexpected.

My suggestion is to take this issue to the NuGet team; it looks like a similar question has been answered in that area before: https://stackoverflow.com/questions/50905545/xamarin-android-package-xx-is-not-compatible-with-monoandroid81-monoandroid-ve

**Comment by mitchdenny** [comment]
Closing this issue since its not a problem with the NuGet task in Pipelines, its more of a NuGet, framework, dependency compatibility issue.
