### ISSUE TITLE
Add MSI (now known as Managed Identities) support to Azure CLI Task

### ISSUE THREAD

**Issue by dave-read** [Microsoft/azure-pipelines-tasks#9191]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
   **Azure DevOps Build Pipeline**
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      **Will provide by direct email if needed**

- Agent - Hosted or Private: 
**Private Agent with MSI Enabled**
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
       **Ubuntu 16.04. Agent Version: '2.144.0'**
## Issue Description
The current implementation of the Azure CLI task does not appear to support using a MSI based Azure Connection.  If you associate a MSI based connection with an Azure CLI task, the task implementation is trying to pull endpoint (Service Principal) credentials which won't exist.  That results in the script failing with an error complaining about the lack of authentication data:

```##[error]Script failed with error: Error: Endpoint auth data not present: XXXXXXXXXXX```

It looks like some infrastructure support for MSI was added in: [Fix MSI authentication for node based tasks (#8157)](https://github.com/Microsoft/azure-pipelines-tasks/pull/8169).  That fix includes being able to determine if the current authentication scheme is MSI.   However the current Azure CLI task implementation does not check to see if the current authentication schema is MSI, which would signal the need to use different login behavior:

1. Not trying to reference non-existent credentials
2. Use ```az login --identity [-u alternate-identity]``` for the login action

For the simple case of a single managed identity for a VM, I think adding conditional logic based on the authentication scheme should fix this.  I've tried a custom task with that approach and have been able to use it with a MSI connection.  For more complicated cases where a VM has [multiple user-assigned managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview#how-a-user-assigned-managed-identity-works-with-an-azure-vm), there would need to be another way to pass the run-as identity through to the task. 

[Include task name(s), screenshots and any other relevant details]
2018-12-27T21:01:22.5041149Z ==============================================================================
2018-12-27T21:01:22.5041268Z Task         : Azure CLI
2018-12-27T21:01:22.5041312Z Description  : Run a Shell or Batch script with Azure CLI commands against an azure subscription
2018-12-27T21:01:22.5041355Z Version      : 1.144.4
2018-12-27T21:01:22.5041518Z Author       : Microsoft Corporation
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]
2018-12-27T21:01:23.3699438Z Setting AZURE_CONFIG_DIR env variable to: /home/azadmin/myagent/_work/_temp/.azclitask
2018-12-27T21:01:23.3720941Z Setting active cloud to: AzureCloud
2018-12-27T21:01:23.3752791Z [command]/usr/bin/az cloud set -n AzureCloud
**2018-12-27T21:01:24.4665862Z ##[error]Script failed with error: Error: Endpoint auth data not present: XXXXXXXXXXXXXXXXXXXXXX**

**Comment by sachinma** [comment]
This support is now available. Added with PR #9419
