### ISSUE TITLE
Publish Code-coverage Report in summary page

### ISSUE THREAD

**Issue by MSidda** [Microsoft/azure-pipelines-tasks#9193]
![image](https://user-images.githubusercontent.com/42439015/50505850-d9b16100-0a9b-11e9-979f-28047155a4bc.png)
i want to view code coverage report in build summary page ...
can anybody help me out please ?
Thanks

**Comment by nigurr** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=vsts
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=vsts
