### ISSUE TITLE
Disconnects from Azure after Job completes

### ISSUE THREAD

**Issue by CYoderDev** [Microsoft/azure-pipelines-tasks#9199]
## Environment
- Server - Azure Pipelines or TFS on-premises?
   
Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

When starting multiple jobs in parallel, Azure disconnects after the first one completes. So when the next one launches, it throws an error stating we need to reconnect.

![image](https://user-images.githubusercontent.com/29983760/50520122-897ed280-0a8c-11e9-8b29-fb648a614992.png)

### Task logs

[tasklog_6 (1).log](https://github.com/Microsoft/azure-pipelines-tasks/files/2715140/tasklog_6.1.log)

**Comment by jpwarner67** [comment]
We recently started hitting a similar issue when we have two VSTS agents on VM running builds at the same time. When an azure powershell task completes on one agent it impacts an azure powershell task running on the other agent (same VM).

Win 2016 Server
Latest Azure PowerShell task

![capture1](https://user-images.githubusercontent.com/41664997/50635318-97a67600-0f06-11e9-886d-a886572f2202.JPG)

**Comment by vincentdass** [comment]
@CYoderDev , @jpwarner67 
Thanks for reporting the issue. We are currently investigating on this and will keep u updated.

**Comment by jpwarner67** [comment]
Wanted to get an idea if this will take a while to sort out as we have had to cut our pool/queue capacity in half from this issue. 

If this is something that will get addressed this week then I can hold off on adding more queue capacity; otherwise, I'll need to begin creating/adding more capacity ...

Thanks
Jim

**Comment by jpwarner67** [comment]
Awesome. Thanks!

**Comment by jpwarner67** [comment]
Hi Vincent,

Thanks for the info. I get the following for the local account that agents are running under:

PS C:\Windows\System32> Get-AzureRmContextAutosaveSetting

Mode             : CurrentUser
ContextDirectory : C:\Users\tfsbuild\AppData\Roaming\Windows Azure Powershell
ContextFile      : AzureRmContext.json
CacheDirectory   : C:\Users\tfsbuild\AppData\Roaming\Windows Azure Powershell
CacheFile        : TokenCache.dat
Settings         : {}

Thanks
Jim

**Comment by jpwarner67** [comment]
Let me know if you need more info. We are still on v3 - 3.1.12. When 3.1.13+ rolls out, I'll update the capacity in our pool and see how things go. Thanks!

**Comment by vincentdass** [comment]
@jpwarner67 , we are in process of hotfixing the issue. Will update once the hotfix is completed.

**Comment by jpwarner67** [comment]
Thanks!

Closed #9199<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fazure-pipelines-tasks%2Fissues%2F9199&data=02%7C01%7CJim.Warner%40microsoft.com%7Cc5bd40aa03ac406a72e508d67b881d5d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636832221870167493&sdata=49OGSc3Wd759bPhk6kr4vqtvyIhnXMLDAK7w2xZ8J7E%3D&reserved=0>.

**Comment by CYoderDev** [comment]
The original issue doesn't seem to be fixed with jobs running in parallel. As soon as the second job starts, it throws an error stating I need to log in.
