### ISSUE TITLE
Document YAML Usage of vsTestVersion

### ISSUE THREAD

**Issue by Silvenga** [microsoft/azure-pipelines-tasks#9200]
Regarding the VSTest@2 task documentation, the following is given when using the VisualStudioTestPlatformInstaller task:

>To run tests without needing Visual Studio on the agent, use the ‘Installed by tools installer’ option. Be sure to include the ‘Visual Studio Test Platform Installer’ task to acquire the test platform from NuGet.

Unfortunately, if you use YAML there is no documentation on what the `vsTestVersion` input should be set to. 

When running with the literal `Installed by Tools Installer` - the following is given to the user, which is slightly confusing to the user:

> Given test platform version Installed by tools installer is not supported.

Looking at the code, it's obvious that `Installed by tools installer` should be selected in the UI, but YAML users should use the literal `toolsinstaller`.

https://github.com/Microsoft/azure-pipelines-tasks/blob/87169ccb021fc5d09d0b3201e904a34c9655037c/Tasks/VsTestV2/inputparser.ts#L185
https://github.com/Microsoft/azure-pipelines-tasks/blob/5a8f18f07644cc5bdfd2e9f374788fd92228b468/Tasks/VsTestV2/task.json#L211

I believe the YAML docs should specify the YAML literal to use to prevent confusion of users.

I can make a pr, if someone can hint where the modifications would be.

**Comment by nigurr** [comment]
@Silvenga We welcome your contributions and willingness to help us.
https://github.com/MicrosoftDocs/vsts-docs is the repository for all documentation.

Feel free to raise the PR, we will take it further.
