### ISSUE TITLE
NPM Authenticate won't work with .npmrc outside project folder

### ISSUE THREAD

**Issue by davidroberts63** [Microsoft/azure-pipelines-tasks#9202]
## Environment
Azure Pipelines
Private agent (Windows Server 1803 with containers) v2.144.0

## Issue Description
Running a pipeline inside a container (based on microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-1803  with node addtionally installed) the npmAuthenticate (via YAML) task will only set the credentials when specifying a `workingFile` input that resolves to a path within the build's workspace. If I attempt to set `workingFile` to `C:/.npmrc` (or flip the slash) it says 'The .npmrc file you selected at .npmrc does not currently exist.' It appears that trying to goto root get's resolved to the build's workspace. 

Given the build is running inside an isolated container, I was hoping to set a global .npmrc without having to make one in the build workspace on the fly or have each project put one in there solely for the Pipeline build. I do admit, this may be problematic on builds not in a container as a single project could effectively change a global .npmrc credentials, which would be undesirable for other projects.

Any recommendations are greatly appreciated, including an inability to resolve this due to possible security or compatibility conflicts. Looking for ideas.

**Comment by salvmd** [comment]
Hi @davidroberts63, it is as you mentioned: this is a security-related restriction built into the tasks (not even specific to the npm Auth task), so unfortunately, I don't think there is a supported way to set a global .npmrc.

**Comment by alexmullans** [comment]
Closing this as the specific request (touching files outside the build's workspace) is prohibited in Pipelines for security reasons. However, this sounds similar to #9584. @davidroberts63 if the `npm Authenticate` task created a `.npmrc` file for you, rather than requiring you to check one in, would that improve your workflow?
