### ISSUE TITLE
Maven task: Maven wrapper support

### ISSUE THREAD

**Issue by ahaeber** [Microsoft/azure-pipelines-tasks#9242]
Currently it does not seem possible to use the Maven wrapper (see https://github.com/takari/maven-wrapper) with the Maven task. The Maven task has various ways for configuring the path, but at the end it is hardcoded to use 'mvn' as the executable name. Usually the Maven wrapper is named 'mvnw'.

A way to simply specify the Maven path + command name would be helpful. Actually that will be the same as mvnExec that is created now. Could introduce a new variable in task.json named "mvnExec" which is mutually exclusive to mavenPath, mavenSetM2Home and mavenVersionSelection. If "mvnExec" is specificed then simply use that.

**Comment by mitchdenny** [comment]
Adding @zjrunner and @alexmullans for consideration.

**Comment by joshmgross** [comment]
Hey @ahaeber, we don't have any plans to add support for the Maven wrapper in the Maven task.

If you want to use the Maven wrapper, you can set up a build script to install it and run all the Maven commands that the Maven task is running for your build. 

Alternatively, you can create a Maven wrapper extension that would do as you described to allow a custom maven executable. For info on creating an extension, see: https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts

**Comment by ahaeber** [comment]
@joshmgross creating a separate build extension for this seems like a lot of work because I will then have to keep it aligned with the standard Maven task. Would you consider a PR by me to add this functionality? I believe it will mainly be some changes at https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV3/maventask.ts#L47

**Comment by joshmgross** [comment]
@ahaeber We try to keep the tasks as light as possible to make them maintainable and since this is a 3rd party maven tool we won't add it to the task.

A separate build extension is definitely a lot of extra work. I'd recommend writing a script to install maven wrapper and call the maven commands to run your build.

**Comment by thorntonrp** [comment]
I would think that only thing needed to support the Maven wrapper script is an option to pass the commands to `./mvnw` instead of `$MAVEN_HOME/bin/mvn`. The wrapper script simply ensures that the required version of Maven has been downloaded and cached locally. In this way, the Maven wrapper script is analogous to the `gradleWrapperFile` on the Gradle task.

**Comment by Tetradeus** [comment]
I did manage to bypass it with a symbolic link + temp path  :  
```
        - bash: |
            echo "##vso[task.setvariable variable=path;]$PATH:$(Build.SourcesDirectory)/.mvn/bin"
```

**Comment by sreich** [comment]
seconding this, the maven wrapper should be considered a part of maven, just like the gradle wrapper is a part of gradle and i would expect my CICD tools to support what other tools have been able to.

**Comment by derTobsch** [comment]
Please reconsider, a lot of things changed. The wrapper is now a part of maven.

**Comment by chunhuihu** [comment]
Apache Flink is using maven Wrapper now, as more and more open-source projects use maven wrapper, could your reconsider to add wrapper support to maven task?

**Comment by munzli** [comment]
apologies for bumping an old and closed issue, but this does pop up in search engines.
like mentioned above, by using a symbolic link, the `mvn` command will use the maven wrapper.
```
      - task: Bash@3
        displayName: 'Force mvn wrapper'
        inputs:
          targetType: 'inline'
          script: |
            mkdir $(Build.SourcesDirectory)/.mvn/bin
            ln -sf $(Build.SourcesDirectory)/mvnw $(Build.SourcesDirectory)/.mvn/bin/mvn
            echo "##vso[task.prependpath]$(Build.SourcesDirectory)/.mvn/bin"
```
