### ISSUE TITLE
How to set secret variable in shell script using ##vso[task.setvariable] command

### ISSUE THREAD

**Issue by rkstar007** [microsoft/azure-pipelines-tasks#9246]
Hello Team,

How to use secret variable in linux shell script using ##vso[task.setvariable] command as its not working for me my variable name as RDSPassword  and its value is hidden in VSTS variable group

E.g : 
RDSPassword ******

**Comment by damccorm** [comment]
Hey, sorry for the slow response here. To set a secret variable using `##` commands, you need to set `issecret=true` in your command, e.g. `##vso[task.setvariable variable=testvar;issecret=true]testvalue`.

See https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md for full docs

**Comment by jessehouwing** [comment]
You can also use:

```
##vso[task.setsecret]THEVALUEYOUWANTHIDDEN
```

To register a secret without declaring a variable.
