### ISSUE TITLE
Azure App Service Deploy .war deployment does not work

### ISSUE THREAD

**Issue by teejam2** [Microsoft/azure-pipelines-tasks#9270]
## Environment
- Server - Azure Pipelines or TFS on-premises?  
 - Azure Pipelines
 - Account name: bcagroup
 - Team project name: LOL
 - Agent - Hosted

## Issue Description
Deploying a .war file with the Azure App Service Deploy task does not extract it. I am using 
https://github.com/projectkudu/kudu/wiki/Deploying-WAR-files-using-wardeploy as a workaround for now.

### Task logs
No errors are reported, but the app service never extracts the .war file and the webapp does not work

**Comment by vincentdass** [comment]
@teejam2 ,War deploy is available in `4.*` task version.
Can you rerun the deployment with the above version?
