### ISSUE TITLE
While agent says it is capable, VSTest task fails miserably while trying to find the test platform

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [Microsoft/azure-pipelines-tasks#9278]
## Environment
- Server - TFS 2018 Update 2
- Agent - Hosted on private server Windows Server 2012 R2, which has Visual Studio 2017 Build Tools 15.8.9 installed. (our server is disconnected and cannot get any log data out sorry)

## Issue Description
I see VSTest and VSTest_15.0 capabilities on the agent's capabilities table, which are valid paths on the agent host machine.

But, while trying to use VSTest task with platform version set to "Latest Version" option, the related job fails with no Visual Studio **2015** error.

When I use "Visual Studio 2017" option instead of "Latest Version", the related job fails with no Visual Studio 2017 error.

If I copy the path corresponding to VSTest capability from the **very same agent's capabilities table** and paste into VSTest task as explicit path to vstest.console.exe directory, then the related job runs without any problem.

Since the agent capabilities table states the correct path, this solution felt like a workaround and I wanted to create an issue.

**Comment by JohannesDrexler** [comment]
"Latest" fails with no Visual Studio 2015 error ? why should there be a visual studio 2015 error ?

"Visual Studio 2017" fails with no Visual Studio 2017 error ? 

You might want to set variable 'System.debug' to true, rerun the scenarios and share some logs from the 'failing' task so this can be properly addressed or narrowed down to the actual problem.

**Comment by kaadhina** [comment]
@zahirtezcan-bugs please share debug logs for us to investigate.

**Comment by zahirtezcan-bugs** [comment]
I cannot get any logs out of our LAN. But, I have re-run the build and checked VSTest task logs. It appears that the task uses "vswhere.exe" to find the visualstudio installation path with a filter for "Microsoft.VisualStudio.PackageGroup.TestTools.Core" component. First, it tries to find VS2017 and fails silently, then checks for legacy version and fails for VS2015.

I ran the vswhere.exe manually without component filter and it could find the build tools installation directory. Then I filtered vswhere.exe resuts for the test platform component id as "Microsoft.VisualStudio.TestTools.TestPlatform.V2.CLI" and it still found the build tools installation directory.

I had used GUI for installation of Visual Studio Build Tools and had selected "Testing tools core features" from individual components. Today I checked the installation properties, and even removed and re-installed "Testing tools core features" and also restarted (just in-case) the server. It seems like the build tools does not install "Microsoft.VisualStudio.PackageGroup.TestTools.Core" component.

Is this a feature that only Visual Studio IDE installations provide?

**Comment by kaadhina** [comment]
Thank you for getting back with the details. The task only supports running tests using the full IDE. It might not be able to detect the test components from the build tools install. 
Our alternative for those who do not want to install the full IDE is the test platform tools installer: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=vsts

**Comment by zahirtezcan-bugs** [comment]
Our TFS (2018 Update2) currently have "preview" version of the test-platform-tool-installer. And it does not support setting the nuget server information. I found the task under one of the agents and modified the javascript code in order to refer our internal package server address. This worked and ran our tests. I could not get coverage info, but I guess it requires a runsettings file for coverage reporting, currently not too important so I skip this.

First, I assume that after an agent maintainance sweep my modified javascript will be gone and the task will be redownloaded from the server, ergo our build will fail.

Second, I assumed BuildTools would work out-of-the-box. Wouldn't Microsoft.VisualStudio.TestTools.TestPlatform.V2.CLI" package also work for the test task? I mean after checking "Microsoft.VisualStudio.PackageGroup.TestTools.Core" it can also check for the CLI package instead of giving up on 2017.

Third, downloading whole TestPlatform for each agent where I already installed BuildTools and also the agent detected VsTest_15.0 capability sounds like a hack more than a solution. Or, are you planning to provide all of BuildTools (C++, C# ...) as partial platforms and provide them via tool installers?

**Comment by kaadhina** [comment]
The task supports pulling down the test platform (preview and latest stable) from the official nuget store without having to modify the script. (In the newer versions we have added support for custom feed and network path as well)
The vstest task only supports full IDE and the test platform pkg as above. We do not plan on supporting build tools since our recommended approach to avoid full IDE is the tools installer task.
The task caches the test platform pkg (which is also light weight) in each agent and does not actually download it every single time.

**Comment by zahirtezcan-bugs** [comment]
> The task supports pulling down the test platform (preview and latest stable) from the official nuget store without having to modify the script. 
I wanted to imply by saying "our server is disconnected" is we have no internet on our working environment. That is why we have an internal package server.

> The vstest task only supports full IDE

The accepted solution here had sounded acceptable for me and thats why I am trying to make it happen.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/6b32aac0-c3e2-4495-b5ef-e42227554ddb/minimum-individual-components-for-a-vs2017-build-server?forum=vssetup

Also, what I see in TestPlatform 15.9 package is, there are 3 components:
 - vstest.console.exe and friends (exists in CommonExtensions\TestWindow and Extenstions\TestPlatform folder of the BuildTools)
    * vsts agent detects the TestWindow directory
 - CodeCoverage.exe and friends (exists in VS Test Agent)
 - IntelliTrace (exists in VS Test Agent)

> We do not plan on supporting build tools

Build tools download page suggests that we can build and run not only our applications but our tests from command line. 
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

So are you planning to drop support on msbuild or .NET and C++ desktop compilation too?

**Comment by kaadhina** [comment]
I see your problem. Right now the alternatives are:
1. Use the custom location field in vstest to specify the location of vstest exe
2. Use tools installer to get the test platform package if that is possible.

What i meant was that the vstest task does not support auto detecting the build tools install today. Running tests outside the task from such an install is status quo.

As for the task auto detecting build tools install, I will add this to our backlog, but please be informed that items from backlog get picked up based on priority.

**Comment by CZEMacLeod** [comment]
@kaadhina 
This issue is flagged as an enhancement, but it is also closed without having made the enhancement.
Is there another issue tracking this?
Is there an environment variable or similar which it can use rather than having to manually set the location of the vstest task in each pipeline?
The issue [docker#418](https://github.com/microsoft/dotnet-framework-docker/issues/418) mentions the workaround would be to set the `vstestLocation` argument of the Visual Studio Test task to C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe

On the latest images that would be `C:\Program Files (x86)\Microsoft Visual Studio\2022\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe` but I don't want to adjust the pipelines, I want to adjust the agent(s).
