### ISSUE TITLE
dataSourceBindings

### ISSUE THREAD

**Issue by kripajoym** [Microsoft/azure-pipelines-tasks#9295]
I am developing a custom VSTS task.
To populate the values in a drop down list am using the below dataSourceBindings. 
and am able to populate is successfully. 

If the list contains a value like  "TestApp" including the double quotes it is listed differently.
How can I handle the values with double quotes? Special characters like % or $ is working fine as any other string. 

"dataSourceBindings": [
      {
        "target": "applications",
        "endpointId": "$(TestService)",
        "endpointURL":"{{endpoint.url}}/test/Apps/",
        "resultselector":"jsonpath:$.[*]",
        "resultTemplate":"{ \"Value\" : \"{{{Id}}}\", \"DisplayValue\" : \"{{{Name}}\" }"
      }
    ]

**Comment by bryanmacfarlane** [comment]
please open an issue in the azure-pipelines-task-lib repo
