### ISSUE TITLE
Code Coverage not visible after publish code coverage using Coverlet to generate Cobertura xml

### ISSUE THREAD

**Issue by virasana** [Microsoft/azure-pipelines-tasks#9297]
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Contact me if needed.

## Agent
- Agent - Hosted or Private:  **Hosted Ubuntu**

## Tech:
**Coverlet**: https://github.com/tonerdo/coverlet
**dotnet test**
**cobertura** output
**ASP.Net Core 2.1 Web API**
**XUnit**
    
## Issue Description
I am using XUnit tests and generating cobertura output using coverlet:

I generate the cobertura xml with dotnet test like this (the actual running code will replace the $1)

`dotnet test $1 /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --logger "trx;LogFileName=$1results.trx" --results-directory "/TestResults" -c Release`

All looks successful (the console log shows the code coverage details in ASCII format - nice), but I see nothing on the Code Coverage tab.

Console errors in Chrome look like this (look in the console log below for the text "**ms.vss-features.frame-content.ccWjx5SzuFCMkxbo.min.js:1 Cannot render contributed pivot ms.vss-build-web.build-results-summary-tab.**":
**Console Log**
```
VM34 Sprint 4:2 Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
vss-bundle-view-vn98sl0HsASPlzhszrLDhp7Gy52jMV3zTsUxdO4H3YPw=:321 Sprints.TaskboardOpen.FromNavigation - ends
vss-bundle-view-vn98sl0HsASPlzhszrLDhp7Gy52jMV3zTsUxdO4H3YPw=:321 Sprints.TaskboardOpen.FromNavigation - ends
vss-bundle-view-vn98sl0HsASPlzhszrLDhp7Gy52jMV3zTsUxdO4H3YPw=:321 Sprints.BacklogOpen.PivotSwitch - ends
ms.vss-features.ui-hub-content.obPxkzNSH6e3dwMO.min.js:1 Must use title or breadcrumb items + headerItemPicker
vss-bundle-view-vn98sl0HsASPlzhszrLDhp7Gy52jMV3zTsUxdO4H3YPw=:321 Backlogs.Open.FromNavigation - ends
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: moved from disconnected to connecting for /_signalr/_apis/b390443e-32b8-4451-9e23-bb5b74ec6665
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: moved from connecting to connected for /_signalr/_apis/b390443e-32b8-4451-9e23-bb5b74ec6665
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: connected!
ms.vss-build-web.definitions.6ROTGedCc42XLq4y.min.js:1 BuildSignalRHub: watching project
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: stopping...
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: disconnected from /_signalr/_apis/b390443e-32b8-4451-9e23-bb5b74ec6665
ms.vss-features.frame-content.ccWjx5SzuFCMkxbo.min.js:1 Cannot render contributed pivot ms.vss-build-web.build-results-summary-tab.
n.loadItems @ ms.vss-features.frame-content.ccWjx5SzuFCMkxbo.min.js:1
ms.vss-build-web.buildresult.5CRDIGVeCqP1Xnvy.min.js:1 Hub data: Objectbuild: {_links: {…}, properties: {…}, tags: Array(0), validationResults: Array(0), plans: Array(1), …}currentView: "logs"definition: {variables: {…}, properties: {…}, tags: Array(0), jobAuthorizationScope: 1, process: {…}, …}isLoading: falserawData: {phaseRecordQueue: {…}, recordPhaseType: {…}, build: {…}, timeline: {…}, definition: {…}, …}sourceData: {displayUri: null, message: "Permissions issue", id: "3e97359301fe5e86cd39f3f6cb8963c8c422169a"}timeline: {records: Array(26), lastChangedBy: "00000002-0000-8888-8000-000000000000", lastChangedOn: Wed Jan 09 2019 18:52:40 GMT+0000 (Greenwich Mean Time), id: "8b9ecdd8-3586-4401-af14-8f42f2d75ed7", changeId: 51, …}__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: moved from disconnected to connecting for /_signalr/_apis/b390443e-32b8-4451-9e23-bb5b74ec6665
ms.vss-features.frame-content.ccWjx5SzuFCMkxbo.min.js:1 Cannot render contributed pivot ms.vss-build-web.build-results-summary-tab.
n.loadItems @ ms.vss-features.frame-content.ccWjx5SzuFCMkxbo.min.js:1
ms.vss-build-web.buildresult.5CRDIGVeCqP1Xnvy.min.js:1 Additional Hub data: Object
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: moved from connecting to connected for /_signalr/_apis/b390443e-32b8-4451-9e23-bb5b74ec6665
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:9 SignalR: connected!
ms.vss-build-web.buildresult.5CRDIGVeCqP1Xnvy.min.js:1 Hub data: Object
ms.vss-build-web.buildresult.5CRDIGVeCqP1Xnvy.min.js:1 Additional Hub data: Objectchanges: [{…}]repositoryName: "SupportTicketASPNetCore"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1 Fetch finished loading: POST "https://karunasoft.visualstudio.com/_apis/customerintelligence/Events".
(anonymous) @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
step @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:172
(anonymous) @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:153
(anonymous) @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:146
__awaiter @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:142
f @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
n._issueRequest @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
(anonymous) @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
Promise.then (async)
(anonymous) @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
step @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:172
(anonymous) @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:153
(anonymous) @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:146
__awaiter @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:142
n.beginRequest @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
(anonymous) @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
step @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:172
(anonymous) @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:153
(anonymous) @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:146
__awaiter @ vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:142
t.publishEvents @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
(anonymous) @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
t._sendEvents @ ms.vss-web.platform-content.gmQeIP4xx8x5ZQsS.min.js:1
ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:1 XHR finished loading: GET "https://karunasoft.visualstudio.com/_signalr/_apis/b390443e-32b8-4451-9e23-bb5b74ec6665/signalr/ping?contextToken=c71759d1-70aa-4985-a6c5-bab7d5f04fca".
s @ ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:1
ajax @ ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:1
pingServer @ ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:1
(anonymous) @ ms.vss-features.signalr.__rk7jVTfT_mkty7U.min.js:1

```

**Extract from the VSTS Logs, Showing 'Successful' publication of data (but no display on Code Coverage tab):**
2019-01-09T18:44:00.9046208Z ==============================================================================
2019-01-09T18:44:00.9046289Z Task : Publish Code Coverage Results
2019-01-09T18:44:00.9046393Z Description : Publish Cobertura or JaCoCo code coverage results from a build
2019-01-09T18:44:00.9046452Z Version : 1.139.2
2019-01-09T18:44:00.9046533Z Author : Microsoft Corporation
2019-01-09T18:44:00.9046597Z Help : More Information
2019-01-09T18:44:00.9046726Z ==============================================================================
2019-01-09T18:44:01.7060004Z Reading code coverage summary from '/home/vsts/work/1/s/Web/TestResults/ST.Web.Tests/coverage.cobertura.xml'
2019-01-09T18:44:04.2486883Z ##[section]Async Command Start: Publish code coverage
2019-01-09T18:44:04.2487021Z Publishing coverage summary data to TFS server.
2019-01-09T18:44:04.2487244Z Lines- 1702 of 8050 covered.
2019-01-09T18:44:04.2487362Z Branches- 594 of 3526 covered.
2019-01-09T18:44:04.7502485Z Modifying Cobertura Index file
2019-01-09T18:44:04.7502666Z Publishing code coverage files to TFS server.
2019-01-09T18:44:06.2485181Z Uploading 294 files
2019-01-09T18:44:11.2520106Z Total file: 294 ---- Processed file: 83 (28%)
2019-01-09T18:44:21.4695000Z Total file: 294 ---- Processed file: 238 (80%)
2019-01-09T18:44:24.1876519Z File upload succeed.
2019-01-09T18:44:24.1876665Z Published '/home/vsts/work/1/s/Web/TestResults/ST.Web.Tests/CoverageReport' as artifact 'Code Coverage Report_390'
2019-01-09T18:44:24.1876740Z ##[section]Async Command End: Publish code coverage
2019-01-09T18:44:24.1877296Z ##[section]Finishing: Publish Web API Code Coverage Result

##VSTS Logs (Attached) - See 
- **Build and Run Web API Tests in Container** (Showing successful test execution and generation of code coverage data)
- **Push Web API Code Coverage Result** (Showing successful upload)

[logs_390.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2744929/logs_390.zip)

**Comment by scottboehmer** [comment]
If you disable just the Publish Code Coverage task in the build, does that workaround the problem?

Would you be able to share a minimal repro or give access to your project so that I can debug a bit?

**Comment by karunasoft** [comment]
Hi Scott, 
Disabling the Publish task won't really help.  It is not so much that the task breaks the build (it doesn't).  It is that I don't get any visible code coverage results.  I am able to download the zip file, extract it to disk and view the results (that works).  But it is about getting it to display on the Code Coverage tab. 
It does not create a Code Coverage tab. 
Nevertheless, I build another solution during the build, a React one, and it successfully generates the Code Coverage tab and publishes the results.  Nice.  The issue I have is that the ASP.Net Core Web API formatter is obviously not playing well with VSTS (or possibly VSTS is not playing well with the output).  So no Code Coverage tab is generated after the first build (the ASP.Net Core Web API build). 

I would be delighted if you could have a look at my build.  How do I pass the details on to you, securely and grant you access?

**Comment by scottboehmer** [comment]
When looking at your build results, is it correct that you see a Code Coverage tab, but that it only has the information from the 2nd Publish Code Coverage task ("Publish React code Coverage Result")? If that's the case, I'm curious what happens if you disable the Publish React task to help determine if the problem is due to having multiple publish tasks or if it is really just a problem with the first task.

Given the symptoms, I think the cannot render error mentioning build-results-summary-tab is unrelated to the problem you're having since it sounds like the Summary tab is rendering correctly.

**Comment by scottboehmer** [comment]
Good to hear that. I'll reach out to the team that owns code coverage to see if they can help out with how to have multiple code coverage files in a build.

**Comment by nigurr** [comment]
@karunasoft Currently we don't support multiple code coverage being published from single pipeline.
We are planning to support this feature (currently it's in backlog) and can't share exact timelines.

Thanks for your support.

**Comment by TroySchmidt** [comment]
You can accomplish it by using reportgenerator to generate the code coverage report from multiple report sources first.  Then publish the code coverage results and summary.
