### ISSUE TITLE
Test Reports and Email notifications issue

### ISSUE THREAD

**Issue by manu4rhyme** [microsoft/azure-pipelines-tasks#9310]
Hi,

Since the last 2 days, I'm getting discrepancies in the test tab of my release and the corresponding email that we receive. 

Here is an example:

Report in test tab of release:
![image](https://user-images.githubusercontent.com/6754924/51035124-fe92f180-15ce-11e9-9ca7-18870815348a.png)

Report of same test in Email:
![image](https://user-images.githubusercontent.com/6754924/51035180-25e9be80-15cf-11e9-95f4-2a5812e5a09d.png)

2 days ago, we were getting correct emails as well. Please look into this.

Also is there a better option for test reportion? 
I explored Test Plans, but the build queue dropdown in settings is not properly paginated, and I cannot scroll down to our queues.

**Comment by joshmgross** [comment]
Hey @manu4rhyme, sorry you're having this issue, I'll look into it.

Could you let me know what your account name is? If you don't want to post it here, you can email it to at joshua.gross@microsoft.com

**Comment by divais** [comment]
@manu4rhyme I am assuming working with the team the data issue is resolved. Can you please share feedback on 'better option for test reporting?'
