### ISSUE TITLE
Review this part of the code

### ISSUE THREAD

**Issue by Darlan82** [microsoft/azure-pipelines-tasks#9311]
https://github.com/Microsoft/azure-pipelines-tasks/blob/5460d2bf0177b10c9c809404fea20092a56f4e69/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts#L86

Review this part of the code as there is only replacement for these tags.
I suggest including WCF tags.
In my case I could not replace address:
`<system.serviceModel>
<client>
<endpoint address="xxxx" ../>
</client>
</system.serviceModel>
`

**Comment by SumiranAgg** [comment]
@Darlan82 Thanks for bringing this up. We are currently supporting just these tags, as documented here https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=vsts

Further we already have your request in our backlog. To make the functionality more generic we are planning to remove limitations to only certain tags as pointed by you. That said it is not a major priority right now and might take some time to come to effect. We will update this thread once we have the enhanced functionality in place.
