### ISSUE TITLE
Azure Powershell: No account found in the context. Please login using Connect-AzureRmAccount.

### ISSUE THREAD

**Issue by jsheetzati** [Microsoft/azure-pipelines-tasks#9319]
## Environment
- Server - Azure Pipelines  (can provide additional details via email if necessary)
- Agent - Hosted or Private:  Private. Build Agent Version: 2.144.0

## Issue Description

One of our Azure Powershell tasks started failing today. I think it could be related to this PR that was recently merged because nothing changed on our end. https://github.com/Microsoft/azure-pipelines-tasks/pull/9294

### Task logs

2019-01-11T20:59:50.6696412Z ##[section]Starting: Azure PowerShell: Swap Slots
2019-01-11T20:59:50.6701070Z ==============================================================================
2019-01-11T20:59:50.6701203Z Task         : Azure PowerShell
2019-01-11T20:59:50.6701303Z Description  : Run a PowerShell script within an Azure environment
2019-01-11T20:59:50.6701380Z Version      : 3.1.18
2019-01-11T20:59:50.6701458Z Author       : Microsoft Corporation
2019-01-11T20:59:50.6701562Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
2019-01-11T20:59:50.6701974Z ==============================================================================
2019-01-11T20:59:52.1949792Z Added TLS 1.2 in session.
2019-01-11T20:59:52.5281159Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\6.12.0\AzureRM.psd1 -Global
2019-01-11T21:00:09.2317490Z ##[command]Clear-AzureRmContext -Scope Process
2019-01-11T21:00:09.7572956Z ##[command]Disable-AzureRmContextAutosave -ErrorAction SilentlyContinue
2019-01-11T21:00:10.1767037Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
2019-01-11T21:00:11.2960528Z ##[command] Select-AzureRMSubscription -SubscriptionId *** -TenantId ***
2019-01-11T21:00:11.9966784Z ##[command]& 'F:\BuildAgents\vsts-agent-1\_work\r1\a\Unzipped\VSTSPowershell\SwapSlots.ps1' -Environment Test -ResourceGroupName *** -Location east
2019-01-11T21:00:13.2282990Z Warming up deploy
2019-01-11T21:00:13.2403129Z Warming up deploy
2019-01-11T21:00:13.2528382Z Warming up deploy
2019-01-11T21:00:13.2655815Z Warming up deploy
2019-01-11T21:00:13.7654681Z Warming up deploy
2019-01-11T21:00:14.7563068Z Warming up deploy
2019-01-11T21:00:14.7862894Z Warming up deploy
2019-01-11T21:00:14.7864221Z Warming up deploy
2019-01-11T21:00:31.9769922Z ##[command]Disconnect-AzureRmAccount -Scope Process
2019-01-11T21:00:32.3525036Z ##[command]Clear-AzureRmContext -Scope Process
2019-01-11T21:00:32.8679296Z ##[error]No account found in the context. Please login using Connect-AzureRmAccount.
2019-01-11T21:00:32.9530190Z ##[section]Finishing: Azure PowerShell: Swap Slots

### Powershell Script
```powershell
param($Environment, $ResourceGroupName, $Location)

workflow SwapSlots
{
    param($Environment, $ResourceGroupName, $Location)

    if ($Location -eq $null) {
        $Location = 'east'
    }
    
    $apps = 
        @(
        [pscustomobject]@{appName="app-$Environment-$Location-app1";sourceSlot="deploy"},
        [pscustomobject]@{appName="app-$Environment-$Location-app2";sourceSlot="deploy"},
        [pscustomobject]@{appName="app-$Environment-$Location-app3";sourceSlot="deploy"},
        [pscustomobject]@{appName="app-$Environment-$Location-app4";sourceSlot="deploy"},
		[pscustomobject]@{appName="app-$Environment-$Location-app5";sourceSlot="deploy"},
        [pscustomobject]@{appName="app-$Environment-$Location-app6";sourceSlot="deploy"},
        [pscustomobject]@{appName="app-$Environment-$Location-app7";sourceSlot="deploy"},
        [pscustomobject]@{appName="app-$Environment-$Location-app8";sourceSlot="deploy"}
        )

    ForEach -Parallel ($app in $apps)
    {
        Write-Output "Warming up $($app.sourceSlot)"
        Switch-AzureRmWebAppSlot -Name $app.appName -ResourceGroupName $ResourceGroupName -SourceSlotName $app.sourceSlot -DestinationSlotName production -SwapWithPreviewAction ApplySlotConfig
        Write-Output "Swapping $($app.sourceSlot) to $($app.appName)"
        Switch-AzureRmWebAppSlot -Name $app.appName -ResourceGroupName $ResourceGroupName -SourceSlotName $app.sourceSlot -DestinationSlotName production -SwapWithPreviewAction CompleteSlotSwap
        Write-Output "Finished swap for $($app.appName)"
    }
}

SwapSlots -Environment $Environment -ResourceGroupName $ResourceGroupName -Location $Location
```

We are swapping slots in parallel because it is much faster than doing a single swap at a time. This has been working for the past 3+ months and just started failing today.

**Comment by vincentdass** [comment]
@jsheetzati , Can you please share the error action preference  set in the task?
![image](https://user-images.githubusercontent.com/20121508/51098248-56a83e80-17ef-11e9-8b4a-d50501699b15.png)

**Comment by jsheetzati** [comment]
ErrorActionPreference is set to Stop on the task

**Comment by brianpcurran** [comment]
Since the Terraform VSTS task sets some environment variables for subscription ID, tenant ID, client ID, and client secret (https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform/blob/master/Xpirit-Vsts-Release-Terraform/public/Import-EnvVars.ps1), I was able to use these inside my external data source script to log into AzureRm:

```
If(($env:ARM_SUBSCRIPTION_ID) -And ($env:ARM_TENANT_ID) -And ($env:ARM_CLIENT_ID) -And ($env:ARM_CLIENT_SECRET)) {
    $secureSecret = ConvertTo-SecureString -String "$env:ARM_CLIENT_SECRET" -AsPlainText -Force
    $psCredential = New-Object System.Management.Automation.PSCredential("$env:ARM_CLIENT_ID", $secureSecret)
    # Set these equal to $Null to avoid extraneous stuff going to stdout
    $Null = Add-AzureRMAccount -ServicePrincipal -Tenant "$env:ARM_TENANT_ID" -Credential $psCredential
    $Null = Select-AzureRMSubscription -SubscriptionId "$env:ARM_SUBSCRIPTION_ID" -TenantId "$env:ARM_TENANT_ID"
}
```

This seems like a fine workaround for my case. I'm still not 100% sure this is the same issue OP is having, and I couldn't fully trace all the ways that this PR might have impacted the Terraform VSTS task, but the behavior seems similar and the timing lines up with when I started seeing the issue FWIW.

**Comment by atlesp** [comment]
We have the same issue. It seems to work fine so long as we do not run tasks in parallel. 
All the places we use `Start-Job` the Azure RM commands fails with this error.

We see the same issue for version 2.1.7

**Comment by vincentdass** [comment]
@atlesp , recently, we made a change to save the context in Process scope. This is to ensure that the context is not leaked outside of the current task.

Now, the context need to be explicitly passed for all background jobs.
Follow any of the below steps to pass context to background job.

1) You can execute `Enable-AzureRmContextAutosave -Scope CurrentUser` in your custom script so that the context is saved globally. But, it might not work when multiple agents are running in the same machine (Disable-AzureRmContextAutosave is invoked by the task explicitly to avoid saving the context globally)
2) Save the context to a file and then import the context in each background job.
```
Save-AzureRmContext -Path "$(Agent.TempDirectory)/myContext.json"
Start-Job -Job {
    Import-AzureRmContext -Path "$((Agent.TempDirectory)/myContext.json"
    Set-AzureRmContext -SubscriptionName "<sub_name>"
    # --- your powershell commands here ---
}
```
[[Reference](https://github.com/Azure/azure-powershell/issues/7110)]

**Comment by vincentdass** [comment]
@brianpcurran , is there any `Azure PowerShell` task in your build or release pipeline? (or in other pipeline that is executing in same or different agent of the same machine)
I assume the terraform task or your custom script invokes a background job that is failing.

**Comment by jsheetzati** [comment]
@vincentdass It is kind of unfortunate that updates on your end break our deployment processes, and this is not the first time it has happened. I am not trying to pass blame or anything because I get the fact that these tasks are used in many different ways, and it is difficult for you guys to know each specific use case. 

Is it possible for us to pin tasks at specific version without using YAML or is YAML the only supported way to pin a task? Luckily, this only impacted our test environment, but we would have been in a bad spot if we were attempting to get a critical Production hotfix released to our environment. 

Also, is saving the context the answer going forward? Meaning we will have to implement that logic if we are interacting with AzurePS in a parallel fashion. Just want to confirm before making the changes on our end. The proposed code makes sense to me.

**Comment by surajsupremegolf** [comment]
This issue still exists, I think it was premature to close this. I have done everything mentioned by Mr. Vincent and it does not work. It was working today morning and subsequent release started failing for swapping slots. I think this should be reopened or prper guidance has to be given. This is breaking our production systems.
