### ISSUE TITLE
Dotnet test task deletes test results even if publish option is turned off

### ISSUE THREAD

**Issue by saikrishnav** [Microsoft/azure-pipelines-tasks#9321]
## Environment
- Server - Azure Pipelines
      
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Microsoft 

- Agent - Hosted or Private: 
    - Hosted VS 2017 Azure

## Issue Description

Dotnet task (test) deletes test results even if "Publish Test Results" is OFF. This is annoying and below is why: 

Scenario:  I have multiple test projects in my repo and that I cannot specify single regular expression (minimatch pattern) that I can pass as arguments to a single dotnet test task.  

So, I went and added multiple dotnet tasks to my pipeline. Well and Good - one would think. 

But the dotnet test task publish is very "basic" and it publish test results under multiple test run titles. For example, if the input is "src\Client\**\*test.csproj", and if I have 3 projects matching that pattern - then dotnet publishes 3 test results with same name "VSTest test run" or such generic name. I have no way to differentiate which one is which. There is no way to "Merge Test Results" to publish under one title.  

To make matters worse, I have multiple jobs/phases in my pipeline and no way to distinguish which test run is by which job easily from the Test Reporting tab. 

So, I turned off the "Publish Test Results" and added the "Publish Test Results" independent task provided by Microsoft TestPlatform so that I can merge test results and publish under a name that I can understand and meaningful to our engineers. 

Now, the annoying bit is this: 
I have a scenario where I have to run tests of multiple projects which I cannot specify using one pattern. So, I have to use multiple dotnet commands to run the tests I want. But, I cannot publish the test results of all the dotnet test tasks that ran because you guys delete the test results. 

My workaround is to specify --results-directory argument and use different folders, and then copy the test results into one folder, then Use the Publish Test Results task to merge the results under one run title. 

I don't understand why the subsequent dotnet test task wants to delete any test results if Publish is turned off in the task. If Publish is turned off, clearly the user wants to handle the publish himself/herself. I shouldn't be jumping through multiple hoops to achieve above scenarios as well. 

I understand that subsequent dotnet task doesn't know whether the test results should be deleted or not just because publish is turned off  - as previous task might have published it. 

I think dotnet Task needs to have a flag i.e. whether to delete test results or not.

**Comment by vagisha-nidhi** [comment]
We shouldn't delete the files when the publish test results option is not checked. When the publish option is checked in, we don't have a good way to know which is the latest trx file or what is the name of the latest trx file which was generated for the run. So before execution, we wipe out all trx files.
We will mark this as bug and take up the fix for not deleting the files when publish option is off.
