### ISSUE TITLE
Failed to capture snapshot of input files for task ':app:compileDebugKotlin' property 'classpath' during up-to-date check.

### ISSUE THREAD

**Issue by MohamedTaher** [Microsoft/azure-pipelines-tasks#9324]
## Environment
- Agent:
private agent 
OS: Ubuntu 14.04
Gradle version: 4.9 
koltin version: 1.2.71

## Issue Description
I get the error when i run "gradlew build" agent job

### Task logs
download logs from [here](https://drive.google.com/file/d/10RZbuZy3c7DgvfqXl_ZfFZV6Hbnp7sIa/view?usp=sharingl)

### Error logs
> Task :app:kaptGenerateStubsDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:kaptGenerateStubsDebugKotlin' property 'classpath' during up-to-date check.
> Could not list contents of '/usr/bin/vmware-user'. Couldn't follow symbolic link.

* Try:
```
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
13 actionable tasks: 13 executed
```

**Comment by bryanmacfarlane** [comment]
It seems like the CI server ran gradlew build fine.  The error is coming from gradle correct?

I can re-open if you believe we didn't run `gradlew build`
