### ISSUE TITLE
AzCopy pipeline task on Ubuntu agent ?

### ISSUE THREAD

**Issue by Crazyabout** [Microsoft/azure-pipelines-tasks#9325]
I know that the Azcopy right now available is only available for a windows host agent. because of the powershell code behind it. But because Azcopy is there some way that this could be possible on an linux host.
The solution I found ATM is to download and run the Azcopy file inside a command line task but I need to login to my Azure subscription every time to run this or provide a passwd in plain text. Not really a ci/cd and secure way of thinking. 

So I was curious if there is some work around for this problem to make it as secure as possible for a ci/cd pipeline

**Comment by Crazyabout** [comment]
That's a lot of workload: I used a workaround with the Azure CLI: like [this user](https://github.com/Microsoft/azure-pipelines-tasks/issues/7611#issuecomment-429740751) mentioned.
Thanks for the information about the release backlog of AzCopy on linux this would be a nice feature

**Comment by kmkumaran** [comment]
Since we are already tracking this using #8920, I am marking this closed.
