### ISSUE TITLE
Github Service Connections not showing up in GitHub Release (Preview)

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/azure-pipelines-tasks#9328]
## Environment
- Server - Azure Pipelines
    - Account Name: StephenHodgson
    - Team Project Name: devops build test
    - Build Pipeline - CD
    - [Link to public project](https://mmoargames.visualstudio.com/devops%20build%20test)
- Agent - Hosted: 
    - Hosted VS2017

## Issue Description

Unable to specify a service connection for Github Releases task.
I was able to set up and use a Github service connection for my CI builds, but for some reason, it's not showing up properly in the dropdown.

![image](https://user-images.githubusercontent.com/13334553/51099122-cda7ed80-1783-11e9-8d23-2abc8410eecb.png)

![image](https://user-images.githubusercontent.com/13334553/51099082-6c801a00-1783-11e9-9910-af4ae9305005.png)

**Comment by StephenHodgson** [comment]
Unfortunately, it doesn't

**Comment by mdmdakbar** [comment]
@StephenHodgson @thomasgalliker 
We do not  support service endpoints which is created using token scheme in tasks. And that's the reason we filter it out in dropdown as well.

For this task, you need to create a new service endpoint of scheme OAuth or PAT. For creation of new endpoint, you can click New button at the right side of GitHub Connection dropdown.

Please let me know if you need any help in setting up the service endpoint. I am closing this for now, feel free to re-open.
