### ISSUE TITLE
No Binary Assets uploaded to Github Release (Preview)

### ISSUE THREAD

**Issue by thomasgalliker** [Microsoft/azure-pipelines-tasks#9330]
## Environment
- Agent: Hosted VS 2017

## Issue Description
For some reasons I'm not able to attach any assets to a Github Release, no matter what I specify under the Assets section. There is an *.exe File in the ArtifactStagingDirectory but the log clearly says I couldn't find any files to upload.

My task configuration looks like this:
![githubreleaseassets](https://user-images.githubusercontent.com/10376364/51113445-42ba0800-1802-11e9-9477-e3f2796536a0.PNG)

You can find some of the releases here:
https://github.com/thomasgalliker/NuGetCleaner/releases

Expected: The releases should have a binary attachement with NuGetCleaner.exe only.

### Task logs
[ReleaseLogs_12.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2755146/ReleaseLogs_12.zip)

**Comment by thomasgalliker** [comment]
When I use $(Agent.ReleaseDirectory) it works! Thanks. The Assets tooltip is pretty misleading:
![16-01-2019_uex14695-nugetcleaner ci release - pipelines-10-31-27](https://user-images.githubusercontent.com/10376364/51239565-04dfef80-197a-11e9-92a0-4ff29df50f98.png)

Do you think this tooltip message should be adjusted to $(Agent.ReleaseDirectory) ?

**Comment by raiyanalam** [comment]
The directory specified in the tool tip is just an example. However, we can definitely add one more path as example. Hope this would make it more explanatory. We will also call this out more clearly in logs for debugging.
Closing this issue.
