### ISSUE TITLE
Test slicing no longer working

### ISSUE THREAD

**Issue by roizentner** [Microsoft/azure-pipelines-tasks#9357]
## Environment
- Azure DevOps
- Private agent v2.136.1

## Issue Description
Hi,
We've been using VS Test task's batching method **based on past running time of tests**, reducing total test run duration from ~12-14 hours to just under 4 hours (we didn't use batching before). 

For two months, this worked great! Unfortunately, it stopped working about a month ago.

Now we're back to test run duration of well over 12 hours.

What Changed?

- On our side, we moved to running tests using .runsettings instead of .testsettings. We are using LegacyMode and LegacySettings.
- We are now using Test Platform 15.9.0.
- The VS Test task was also updated on our Azure Devops instance at the same time (it is currently v2.144.11).

Can any of these explain why batching stopped working for us?

Thanks.​

**Comment by kaadhina** [comment]
@roizentner  Hi, I see that you have also opened a ticket on [developer community](https://developercommunity.visualstudio.com/content/problem/430771/test-slicing-no-longer-working.html) for the same. Please share the logs as asked over there  to debug this further.
And can we track track this in one single place, can you close one of the two?

**Comment by roizentner** [comment]
Sure. I didn't know which of the two is most appropriate. I will close this one and share the logs on developer community. Thanks.
