### ISSUE TITLE
Secret passed in to Bash task as argument only works with $(MYSECRET) not $MYSECRET

### ISSUE THREAD

**Issue by GrahamDSmith** [Microsoft/azure-pipelines-tasks#9363]
In Azure Pipelines I can pass normal variables to a v3 Bash script (Shell Script task) as an argument using $MYVARIABLE. However, secrets (which can only be passed in as arguments) do not get passed in using the $MYSECRET form but they do get passed in using the $(MYSECRET) form. I've not found this documented anywhere. Is this a bug?

**Comment by bryanmacfarlane** [comment]
You have to map secrets into the env block of the step.  @ericsciple can point to example

**Comment by GrahamDSmith** [comment]
Thanks @bryanmacfarlane. Just to clarify, I have this working fine, however the issue is that I've found secrets need to be passed to a script with parentheses round the word, ie $(MYSECRET), as opposed to anything that isn't a secret which can be passed without parentheses around the word ie $MYSECRET. I haven't seen this need for the parentheses for secrets anywhere and am wondering if it's a bug because I'm sure it will trip some people up.

**Comment by ericsciple** [comment]
That is intentional. Secrets are not automatically added into the environment block. They must be explicitly mapped in. Either into the `env` block, or into one of the task inputs. Examples [are here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#secret-variables).

**Comment by ericsciple** [comment]
@GrahamDSmith what's the issue? The behavior you are describing aligns with the documentation I linked.

**Comment by GrahamDSmith** [comment]
The problem @ericsciple is one of consistency. If I can pass non-secrets to a script using $MYPLAINVARIABLE then for consistency I should be able to pass secrets using $MYSECRET. This lack of consistency will trip some people up which is what I'm trying to address. So the fix is one of these:
- Allow secrets to be passed in as $MYSECRET to be consistent with $MYPLAINVARIABLE
- Force all arguments to be passed in as $(MYPLAINVARIABLE) to be consistent with $(MYSECRET)
- Make the documentation **very clear** that secrets have to be passed in to a script in a very specific way, ie $(MYSECRET) works but $MYSECRET doesn't.

The second option is obviously a breaking change so one or three would be preferable.

Cheers!

**Comment by dylan-smith** [comment]
Are you sure it's doing what you think.  When you pass in a non-secret using the $MYPLAINVARIABLE i suspect that it's just getting passed to your task as a string (AzDO is not converting it to the value), then in the script $MYPLAINVARIABLE resolves to the environment variable so things work.

I wouldn't expect AzDO to process anything that doesn't have the $() syntax.

**Comment by GrahamDSmith** [comment]
What happens if test.sh is:

`echo "TEST is $1"`

ie `USERNAME`  is not used in the script?

Whatever is happening though, the net effect for end users is the same, ie a lack in consistency which will trip some people up.

**Comment by ericsciple** [comment]
[This section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#working-with-variables) contains a table which describes where the azure-pipelines macro syntax `$( )` can be used, and describes alternate syntaxes from accessing environment variables within a script (batch, powershell, and bash).

And [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) talks about working with secret variables which intentionally must by mapped-in using macro syntax. You are correct it's inconsistent, however we intentionally chose that behavior to help prevent accidental leaking of secrets (crash dumps, etc).

I think the confusion is, the filename + arguments that you specify are written to a temporary script. And bash is used to run that command. So when you are using bash variable-syntax (e.g. `$FOO`) in the arguments input, those arguments are getting interpreted by bash. Many customers desire this behavior and it makes the task more consistent with what they type on the command line.

If you have any specific feedback for the docs, I'm happy to pass it along.

**Comment by GrahamDSmith** [comment]
Not sure if this is specific feedback, but I think the whole scenario of passing secrets to Bash scripts via arguments needs to be explained explicitly and clearly, and be easy to stumble upon.

**Comment by ericsciple** [comment]
Thanks, makes sense. Personally I agree, as I've seen it be a very common stumbling point for customers in the past.

I'll relay the feedback and follow up with appropriate folks tomorrow.

**Comment by ericsciple** [comment]
@vtbassmatt fyi

**Comment by ericsciple** [comment]
@andyjlewis fyi

**Comment by lawrencegripper** [comment]
![image](https://user-images.githubusercontent.com/1939288/70263879-38dd2280-178f-11ea-928d-e8d3b32d063a.png)

To highlight this one I also got confused, to add to the confusion the UI seems to suggest that I can pass my secret as a normal bash variable and gives me an example... following the example fails.

**Comment by vtbassmatt** [comment]
That's an unfortunate bit of UI - thanks for reporting. I'll see if we can disable that "helpful" text when it's a secret.

@wnjenkin I think that's in your area.

**Comment by collinbarrett** [comment]
I am having issues getting secrets passed into my bash tasks [here](https://github.com/collinbarrett/FilterLists/blob/45a928779f4c5339bf6835acafa2af595f38ecb2/server/azure-pipelines.migrate.yaml#L47) and [here](https://github.com/collinbarrett/FilterLists/blob/45a928779f4c5339bf6835acafa2af595f38ecb2/server/azure-pipelines.migrate.yaml#L87). For some reason, they [don't seem to be injected properly](https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=2802&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=76467409-274e-589c-5c88-4286504c504b). I can use the `script` task and map the variables right in from YAML successfully, but I [read](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) that the more secure approach is mapping them into the shell's environment variables. Anybody spot what I'm doing incorrectly?

**Comment by collinbarrett** [comment]
That [last commit](https://github.com/collinbarrett/FilterLists/commit/010120bd978519eb2125a9cb5aab4930f7bb0384) worked. Not sure exactly what solved it. Sorry to hijack this Issue. Maybe it'll help somebody out. It'd be great to have a bash sample alongside the powershell sample [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch&viewFallbackFrom=vsts#secret-variables).

**Comment by vtbassmatt** [comment]
@collinbarrett when you use `env`, we don't do any case-munging or replace `.` with `_`. So when you said:
```yaml
- script: ...
  env:
    GitHubName: $(GitHub.Name)
```

then we were injecting exactly `$GitHubName` into your environment. I see that you've fixed it so that you're using uppercase everywhere.
