### ISSUE TITLE
No Repositories in GitHub Release Task

### ISSUE THREAD

**Issue by andysterland** [Microsoft/azure-pipelines-tasks#9364]
## Environment
- Azure Pipelines
- GitHub Release Task
- Project: vscode-chrome-devtools

## Issue Description
I’m having an issue with the GitHub release task. There is no repositories in the dropdown for selecting a repository and it never finishes loading but goes away when you click off.

It looks like it never finishes loading because there is an unhandled exception caused by code not handling a xhr response that's an object not an array (that implements forEach). 

![image](https://user-images.githubusercontent.com/10997361/51433599-a5e0db80-1c02-11e9-8167-581a1ddf3aa8.png)

**Steps**

1. Get to the task “GitHub Release”  (in a new release pipeline)
2. Select a github connection (this happens with either oauth or an access token)
3. In the repo dropdown click on the down arrow

**Expected**
Populated list of repos

**Actual** 
No repos

#### XHR
```
Url
https://andysterland.visualstudio.com/_apis/distributedtask/endpoint
Request
{"url":"/vscode-chrome-devtools/_apis/sourceProviders/GitHub/repositories?serviceEndpointId=5b479087-afb8-4a70-9935-4c09f1fcec1b","selector":"jsonpath:$.repositories[*].id","connectionId":"tfs:0<guid>","scope":"<guid>","taskId":"7b5a6198-adf8-4b16-9939-7addf85708b2","keySelector":"jsonpath:$.repositories[*].id"}
Response
{"count":0,"value":null}
```

#### Code
![image](https://user-images.githubusercontent.com/10997361/51433588-57cbd800-1c02-11e9-9419-106c83cc3d4a.png)

#### Value of t
![image](https://user-images.githubusercontent.com/10997361/51433592-63b79a00-1c02-11e9-9071-40c99e852013.png)

#### Exception
```
TypeError: t.forEach is not a function
    at vss-bundle-ext-v7DYMCijk4yubnOkksWmAJ3981Dj0w6o7q-P1S-UluUk=:formatted:19828
    at c (vss-bundle-common-vHBXoLPqVdx60WoXdQr1h6_aplH5Cz7pge9-9-hOszjw=:33)
    at vss-bundle-common-vHBXoLPqVdx60WoXdQr1h6_aplH5Cz7pge9-9-hOszjw=:33
    at t.u.promiseDispatch (vss-bundle-common-vHBXoLPqVdx60WoXdQr1h6_aplH5Cz7pge9-9-
hOszjw=:33)
    at vss-bundle-common-vHBXoLPqVdx60WoXdQr1h6_aplH5Cz7pge9-9-hOszjw=:33
    at MessagePort.t (vss-bundle-common-vHBXoLPqVdx60WoXdQr1h6_aplH5Cz7pge9-9-hOszjw=:33) 

```

**Comment by mdmdakbar** [comment]
@andysterland We have a known issue of repositories dropdown loading for some times (20s) and then showing empty result. That is because the list of repositories to fetch is very long and HTTP request is getting timedout.

For now, we have made the changes to make repositories dropdown editable, so that users can type the full name of repository. 

Can you please confirm if the repositories dropdown is editable or not for you?

**Comment by andysterland** [comment]
It seems that it is still read only. I Just tried it. I can set it in the dev tools so that does unblock me.

![image](https://user-images.githubusercontent.com/10997361/51506224-0e18f400-1da0-11e9-9240-471c71d0b6c1.png)

**Comment by mdmdakbar** [comment]
@andysterland Can you please share your AzureDevOps account name, so that we can verify if the changes have rolled out to the region where your account is hosted.

**Comment by mdmdakbar** [comment]
@andysterland Can you please send the above details to RM_Customer_Queries@microsoft.com.
This is our internal alias for all customer related queries.

**Comment by prativen** [comment]
Thanks for reporting the issue. This is the same issue as reported in #9121. Closing this one. We have made the control editable for now and are looking to improve the experience.
