### ISSUE TITLE
Docker task 'build' command converting container repostory name to lowercase before adding latest tag

### ISSUE THREAD

**Issue by vithati** [Microsoft/azure-pipelines-tasks#9369]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - both

- Agent - Hosted or Private: 
    
    - both

## Issue Description
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: 'myServiceConnection'
      azureContainerRegistry: 'myContainerRegistry.azurecr.io'
      includeLatestTag: true
      command: 'build'

Docker build task converting ACR name to lowercase before added latest tag to image. 
2019-01-11T13:04:37.2765515Z Successfully tagged myContainerRegistry.azurecr.io/start.spring.io:133
2019-01-11T13:04:37.2959758Z Successfully tagged **mycontainerregistry.azurecr.io/start.spring.io**:latest

due to this below docker push command failing with error "tag does not exist: myContainerRegistry.azurecr.io/start.spring.io:latest"

  - task: Docker@1
    displayName: 'Push the latest image'
    inputs:
      azureSubscriptionEndpoint: 'myServiceConnection'
      azureContainerRegistry: 'myContainerRegistry.azurecr.io'
      command: 'push'
      imageName: "$(Build.Repository.Name):latest"

### Error logs

**Comment by ds-ms** [comment]
Fix for this has been merged.
