### ISSUE TITLE
Output logs partially masked

### ISSUE THREAD

**Issue by willgarcia** [Microsoft/azure-pipelines-tasks#9376]
## Environment
- Server - Azure Pipelines 
- Agent - Private: Linux Debian

## Issue Description

Task: Command Line, version 2.* + Publish artefacts, version 1.*

Parts of the output are masked.

## Extract of logs

* Command line task:

```
...
2019-01-22T04:50:07.6804740Z docker-compose -f docker-compose.test.yml build
2019-01-22T04:50:08.0323527Z db uses an image, skipping
2019-01-22T04:50:08.0324049Z Building test
2019-01-22T04:50:08.4994326Z Step ***/5*** : FROM microsoft/dotnet:2.***-sdk-bionic AS build
2019-01-22T04:50:08.4995049Z  ---> effdd***283c0***
2019-01-22T04:50:08.4995208Z Step 2/5*** : WORKDIR /src
...
```

* Publish artefact task:

```
...
2019-01-22T12:15:12.3361886Z Task         : Publish Build Artifacts
2019-01-22T12:15:12.3361992Z Description  : Publish build artifacts to Azure Pipelines/TFS or a file share
2019-01-22T12:15:12.3362136Z Version      : ***.***42.2
2019-01-22T12:15:12.3362201Z Author       : Microsoft Corporation
...
```

## Expected behaviour

Only secrets are masked in output logs.

This problem could be related to a global misconfiguration as it affects multiple pipelines present in the same account.

**Comment by bryanmacfarlane** [comment]
This means there's a secret of those letters being masked.

For example, if I have a secret that is "a" then all a's will be masked in the output logs.  

If you have an exact repro with the contents of some secrets as a repro example, we can re-open

**Comment by willgarcia** [comment]
@bryanmacfarlane This does not seem to be the case. Eg: 15000ms get masked (***00ms) but no existing variable/secret match the string 150 or even the separate characters 1,5,0.

**Comment by dc297** [comment]
@willgarcia did you find out why they're being masked?

**Comment by StingyJack** [comment]
The DeveloperCommunity issues raised for this are being closed as duplicates of [this issue report](https://github.com/microsoft/azure-pipelines-agent/issues/1207). We have a support case open for this problem and were also referred to that GH issue. Not only is it making the logs hard to read, but its exposing some of the very secrets it is trying to mask. 

Add an Azure KeyVault task to a pipeline, and everything after that gets masked like this for trivial values like "1", "2", "Dev", etc.

**Comment by Kevinf63** [comment]
After scouring the internet for some time, I stumbled upon this [Sprint 215 Update from January 23rd 2023](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/pipelines/sprint-215-update#ability-to-disable-masking-for-short-secrets) which has since been implemented:

> ## Ability to disable masking for short secrets
>
>Azure Pipelines masks secrets in logs. Secrets can be variables marked as secret, variables from variable groups that are linked to Azure Key Vault or elements of a Service Connection marked as secret by the Service Connection provider.
>
>All occurrences of secret value are masked. Masking short secrets e.g. '1', '2', 'Dev' makes it easy to guess their values e.g. in a date: 'Jan 3, 202***'
>It's now clear '3' is a secret. In such cases you may prefer not masking the secret altogether. If it's not possible to not mark the value as secret (e.g. the value is taken from Key Vault), you can set the **AZP_IGNORE_SECRETS_SHORTER_THAN** knob to a value of up to 4.
