### ISSUE TITLE
Kubernetes and Docker task shouldn't set all its output as variable

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/azure-pipelines-tasks#9379]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesV1/task.json#L439
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerV1/task.json
the kubernetes/docker task is setting a variable that equals kuctl/docker's outputs.
the outputs might be huge and cause the agent can't launch process any more due to OS limitation.

```
2018-11-30T07:09:12.6048761Z ##[debug]System.ComponentModel.Win32Exception (7): Argument list too long
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
```

**Comment by vithati** [comment]
We have restricted the output limit to 31k with this PRs https://github.com/Microsoft/azure-pipelines-tasks/pull/8968 https://github.com/Microsoft/azure-pipelines-tasks/pull/8957. Please re-open this issue if you see any issue with latest task version.
