### ISSUE TITLE
Allow pattern matching on path to powershell script

### ISSUE THREAD

**Issue by ADringer** [Microsoft/azure-pipelines-tasks#9401]
Hi,

When using the Powershell task and referencing a script, the path needs to be fully qualified or relative to the default working directory.

Is it possible that this could use the pattern matching as used by other tasks? I don't know the full path as it it in a task group so could be anything. As a workaround I've had to add an additional Powershell task to search in the default working directory for the file name, assign the full path to a variable and then use this in the script path parameter.

Thanks

Alex

**Comment by bryanmacfarlane** [comment]
We can't pattern match since it could match to multiple files.
