### ISSUE TITLE
No test results assigned to release - VsTestV2 with test plan

### ISSUE THREAD

**Issue by kschachinger** [Microsoft/azure-pipelines-tasks#9417]
## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
TFS 2018 Update3

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows 7
Agent Version: 2.136.1

## Issue Description

No test results will be assigned to a release even unit tests will be performed.

![image](https://user-images.githubusercontent.com/47026168/51739055-dc9a7400-2090-11e9-98a2-cbeb2023b857.png)

**Comment by nigurr** [comment]
@kschachinger Please share more information and follow our template to speed up serving you

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 


- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]
