### ISSUE TITLE
Build should fail if beanshell assertion fails

### ISSUE THREAD

**Issue by taurheim** [Microsoft/azure-pipelines-tasks#9423]
## Environment
Azure pipelines, tested on multiple team projects. Hosted agent. 

## Issue Description
When running the build task 'RunJMeterLoadTestV1', beanshell triggered errors (for example, beanshell assertions or beanshell scripts marking requests as failed) do not fail the build task. When running a load test as part of validation, having the load test fail the build is necessary as marking it as passed despite failed assertions reduces the visibility of the issues.

The suggestion on [the only relevant topic I can find](https://developercommunity.visualstudio.com/content/problem/267416/build-still-passes-when-jmeter-assertions-fail-or.html) is to make a call to the REST API to check for errors and fail the build, but given that the RunJMeterLoadTestV1 task is only meant to be used for JMeter in builds it makes sense to have this functionality included in the task.

Build task:
![image](https://user-images.githubusercontent.com/5691564/51760983-b1a82400-2080-11e9-9f58-28058e009b77.png)

Load test (these failures are from the beanshell assertion):
![image](https://user-images.githubusercontent.com/5691564/51761037-ddc3a500-2080-11e9-890a-fa02a12a851b.png)

### Task logs
Build task logs:
[logs_1512070.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2797047/logs_1512070.zip)
JMeter load test logs:
[ResultsArchive.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2797057/ResultsArchive.zip)

**Comment by nigurr** [comment]
@taurheim We appreciate your support and PR contribution.
Currently we are not accepting any enhancements/changes to this task.

We sincerely apologize for this and excuse us for not accepting it.
