### ISSUE TITLE
MSTest Logs no longer available on failed test.

### ISSUE THREAD

**Issue by joshmackey** [Microsoft/azure-pipelines-tasks#9426]
## Environment
- Azure Pipelines - Hosted VS2017

## Issue Description
Used to be able to access the logs of failed tests via the attachments tab.

Visual Studio Test no longer attaches Standard Output logs to the test results. Logs are still available when testing locally.

Did something change to stop this?

**Comment by joshmackey** [comment]
I get console logs when I run `dotnet test` locally.

**Comment by nigurr** [comment]
@joshmackey We are not able to repro this issue
https://dev.azure.com/dtatestingint/Public%20Samples/_build/results?buildId=7310&_a=summary&view=ms.vss-test-web.build-test-results-tab

Please follow our template to serve us better.

**Comment by joshmackey** [comment]
## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://frznmtn.visualstudio.com/FM/_build/results?buildId=3845 (I retained this diagnostics build as an example of the issue)


- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017 

## Issue Description

Logs for failed tasks do not get output in either the Test results nor in the test task log itself.

### Task logs

Available to be emailed, can't share publicly.

**Comment by nigurr** [comment]
@joshmacke you can mask/replace any sensitive information and share the logs.
You can also create support request here: https://developercommunity.visualstudio.com/spaces/21/index.html

We couldn't spot any failed build associated to shared build id

**Comment by joshmackey** [comment]
[logs_3845.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2818744/logs_3845.zip)

That link still shows a failed build when I click it.

**Comment by nigurr** [comment]
@joshmackey as mentioned if and only if test fails, standard output log will appear in VSTS
