### ISSUE TITLE
Can't deploy a classic cloud service with osFamily=6

### ISSUE THREAD

**Issue by JSCProjects** [Microsoft/azure-pipelines-tasks#9430]
Following this [url](https://azure.microsoft.com/en-us/updates/guestosfamily6announce/)  osFamily6 is GA now, but I can't deploy my service with ADO & Private Agent. I continuously get the following error.

> ##[error]BadRequest : The OS family 6 you are trying to deploy is not supported by the SDK package. The SDK package supported OS families:3,4,5,1,2,98,97. Please try to deploy to a different operating system. To do this specify a different osFamily and/or osVersion in your .cscfg file.

I've already updated to the newest vs2017 version, but nothing works.

**Comment by kmkumaran** [comment]
@JSCProjects - Are you trying to deploy using native PowerShell script or are you using the "Azure Cloud Service deployment" task?

**Comment by JSCProjects** [comment]
I'm using "Azure Cloud Service Deployment" task

**Comment by Spiggers** [comment]
I also have this problem

**Comment by wjchristenson2** [comment]
Been working with Microsoft on this. Here is the latest:

> The issue is not the “cloud service deploy” step but rather the build step. We generate a new image of Hosted Agent VS2017 in the first week of every month. This month it was generated on the 7th. But Visual Studio added support for building family 6 cloud service packages on the 12th and so this month’s image did not have those updates required to support family 6 packages. I believe the next months image will be able to build family 6 supported packages. We will generate a new image next week and verify if this scenario is working

**Comment by Spiggers** [comment]
That is great news. I can wait one month! Appreciate the feedback + digging.

**Comment by arjgupta** [comment]
Hi, I have verified that this month's Hosted VS2017 image should have the necessary updates to support os family 6 packages.

**Comment by niadak** [comment]
@Spiggers Can you please try now. Hosted VS2017 agent should have the required updates.

**Comment by ashishnegi** [comment]
Still getting the same error, when updating the cloud service configuration :

```
Failed to save configuration settings for slot 'Production'. Error: The operation '4d47f41a98657bee92a81853f552e762' failed: 'The OS family 6 you are trying to deploy is not supported by the SDK package. The SDK package supported OS families:3,4,5,1,2,98,97. Please try to deploy to a different operating system. To do this specify a different osFamily and/or osVersion in your .cscfg file.'.
```
