### ISSUE TITLE
Delete files task locking sources directory of build

### ISSUE THREAD

**Issue by alkief** [microsoft/azure-pipelines-tasks#9431]
## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 
    TFS 2018.3

- Agent - Private
  - Machine OS: Windows Server 2012 R2
  - Agent.Version: 2.136.1
  - Agent.OSVersion: 6.3.9600

- Task Name - DeleteFiles v1.1.4
    - Config:
      - Source folder - $(Agent.BuildDirectory)
      - Contents - **

## Issue Description

I am currently working to upgrade an on-prem installation of TFS from 2015 to 2018. As part of this process, build agents needed to be upgraded. For nearly all our build definitions that exist, there is a delete step included at the end of every build to remove build resources from the agent when finished. 

The issue is that all existing builds fail at this final step due to a change in behavior in the Delete Files task. The actual error and behavior is identical to [#3628](https://github.com/Microsoft/azure-pipelines-tasks/issues/3628). Both solutions provided there do solve the issue, however, this is at the cost of editing all build definitions that include the aforementioned delete step, which is far from ideal for us.

Judging from logs, the Delete Files process locks the `agent\_work\##\s` directory as its working directory. This has changed from previous versions, where the Delete Files process would lock  `agent\tasks\Deletefiles\<version>` as its working directory.

After digging through source code, I believe the process's working directory is being set to a default as part of the agent's [NodeHandler logic](https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/Handlers/NodeHandler.cs#L80) which sets it to [System.DefaultWorkingDirectory](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=tfs-2018#system-variables) since no working directory is specified as part of the task.

I would like to know if there is any way to specify the working directory of all Delete Files tasks, as this should solve my issue. I do see a line in the Delete task logs for `loading INPUT_WORKINGDIRECTORY`, though I've not found any resources regarding this and I'm not sure whether this line relates to the agent's working directory or the process's. If this isn't possible, are there any alternatives to editing individual build definitions while maintaining existing behavior (resource removal after build)?

### Task logs

**DeleteFiles task logs:**

```
2019-01-25T20:39:32.7730660Z ##[debug]agent.workFolder=E:\TFS\Agents\2018\agent06_2\_work
2019-01-25T20:39:32.7879789Z ##[debug]loading inputs and endpoints
2019-01-25T20:39:32.7881377Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-01-25T20:39:32.7883682Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-01-25T20:39:32.7885543Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-01-25T20:39:32.7886280Z ##[debug]loading INPUT_CONTENTS
2019-01-25T20:39:32.7886480Z ##[debug]loading INPUT_SOURCEFOLDER
2019-01-25T20:39:32.7886685Z ##[debug]loading INPUT_WORKINGDIRECTORY
2019-01-25T20:39:32.7887070Z ##[debug]loaded 6
2019-01-25T20:39:32.7887552Z ##[debug]check path : E:\TFS\Agents\2018\agent06_2\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.1.4\task.json
2019-01-25T20:39:32.7887997Z ##[debug]set resource file to: E:\TFS\Agents\2018\agent06_2\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.1.4\task.json
2019-01-25T20:39:32.7888272Z ##[debug]system.culture=en-US
2019-01-25T20:39:32.7888487Z ##[debug]Contents=**
2019-01-25T20:39:32.7888681Z ##[debug]SourceFolder=E:\TFS\Agents\2018\agent06_2\_work\3
2019-01-25T20:39:32.7888883Z ##[debug]BuildCleanup=null
2019-01-25T20:39:32.7889076Z ##[debug]patterns: E:\TFS\Agents\2018\agent06_2\_work\3\**
2019-01-25T20:39:32.7889290Z ##[debug]find findPath=E:\TFS\Agents\2018\agent06_2\_work\3, options=undefined
...
...
...
2019-01-25T20:39:33.0668468Z ##[debug]rm -rf E:\TFS\Agents\2018\agent06_2\_work\3\s
2019-01-25T20:39:33.0668679Z ##[debug]removing directory
2019-01-25T20:39:33.0668852Z rm: could not remove directory (code EBUSY): E:\TFS\Agents\2018\agent06_2\_work\3\s
2019-01-25T20:39:33.0668993Z 
2019-01-25T20:39:33.0669319Z ##[error]Error: Failed rmRF: rm: could not remove directory (code EBUSY): E:\TFS\Agents\2018\agent06_2\_work\3\s
2019-01-25T20:39:33.0669701Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Failed rmRF: rm: could not remove directory (code EBUSY): E:\TFS\Agents\2018\agent06_2\_work\3\s
2019-01-25T20:39:33.0669867Z 
2019-01-25T20:39:33.0670077Z ##[debug]rm -rf E:\TFS\Agents\2018\agent06_2\_work\3\a
2019-01-25T20:39:33.0670287Z ##[debug]removing directory
2019-01-25T20:39:33.0670493Z ##[debug]task result: Failed
2019-01-25T20:39:33.0670737Z ##[error]Couldn't delete one or more files
2019-01-25T20:39:33.0670925Z ##[debug]Processed: ##vso[task.issue type=error;]Couldn't delete one or more files
2019-01-25T20:39:33.0685823Z ##[debug]Processed: ##vso[task.complete result=Failed;]Couldn't delete one or more files
```

**Worker logs from `agent\_diag` of the 2018 agent:**

```
INFO TaskManager] Loading task definition 'E:\TFS\Agents\2018\agent06_2\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.1.4\task.json'.
INFO TaskRunner] The original input is a rooted path, return absolute path: E:\TFS\Agents\2018\agent06_2\_work\4
INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
INFO BuildJobExtension] Build JobExtension resolving path use source provide:
INFO BuildJobExtension] The Default Path Root of Build JobExtension is build.sourcesDirectory: E:\TFS\Agents\2018\agent06_2\_work\4\s
INFO BuildJobExtension] After prefix Default Path Root provide by JobExtension: E:\TFS\Agents\2018\agent06_2\_work\4\s
INFO BuildJobExtension] Return absolute path after prefix DefaultPathRoot: E:\TFS\Agents\2018\agent06_2\_work\4\s
INFO TaskRunner] Build JobExtension resolved a rooted path:: E:\TFS\Agents\2018\agent06_2\_work\4\s
INFO NodeHandler] Inspect node_modules folder, make sure vsts-task-lib doesn't overwrite String.startsWith/endsWith.
INFO NodeHandler] This task has already been scanned and corrected, no more operation needed.
INFO HostContext] Well known directory 'Bin': 'E:\TFS\Agents\2018\agent06_2\bin'
INFO HostContext] Well known directory 'Root': 'E:\TFS\Agents\2018\agent06_2'
INFO HostContext] Well known directory 'Externals': 'E:\TFS\Agents\2018\agent06_2\externals'
INFO ProcessInvokerWrapper] Starting process:
INFO ProcessInvokerWrapper]   File name: 'E:\TFS\Agents\2018\agent06_2\externals\node\bin\node.exe'
INFO ProcessInvokerWrapper]   Arguments: '"E:\TFS\Agents\2018\agent06_2\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.1.4\deletefiles.js"'
INFO ProcessInvokerWrapper]   Working directory: 'E:\TFS\Agents\2018\agent06_2\_work\4\s'
INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
INFO ProcessInvokerWrapper]   Encoding web name: utf-8 ; code page: '65001'
INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
INFO ProcessInvokerWrapper]   Lines to send through STDIN: '0'
INFO ProcessInvokerWrapper] Process started with process id 968, waiting for process exit.
```

**Worker logs from `agent\_diag` of the 2015 agent:**

```
10:16:11.131976 JobExtensionManager.GetDefaultPathRoot
10:16:11.131976 JobExtensionManager.GetLocalPath
10:16:11.131976 JobRunner.Run - Running task DeleteFiles.
10:16:11.131976 BaseLogger.LogConsoleMessage(scope.JobId = 8b63bd21-1eb8-4eb3-9850-fed1d1886bd7, message = ##[section]Starting task: Clean Build Files)
10:16:11.134977 JobExtensionManager.OnBeforeExecuteTask
10:16:11.134977 JobExtensionManager.OnExecuteTask
10:16:11.145977 BaseLogger.LogStatus(scope.JobId = 8b63bd21-1eb8-4eb3-9850-fed1d1886bd7, scope.TimelineRecordId = 38bce15d-090c-4e4f-8978-b0e6a4005049, record.Name = Clean Build Files)
10:16:11.145977 BaseLogger.LogConsoleMessage(scope.JobId = 8b63bd21-1eb8-4eb3-9850-fed1d1886bd7, message = Set workingFolder to default: E:\TFS\Agents\agent06_01\tasks\DeleteFiles\1.0.7)
10:16:11.147976 Entering ProcessWrapper.CreateStartInfo
10:16:11.147976    workingFolder = E:\TFS\Agents\agent06_01\tasks\DeleteFiles\1.0.7
10:16:11.147976    filename = E:\TFS\AGENTS\AGENT06_01\AGENT\WORKER\HANDLERS\NODE\node.exe
10:16:11.147976    arguments = "E:\TFS\Agents\agent06_01\tasks\DeleteFiles\1.0.7\deletefiles.js"
10:16:11.147976 Leaving ProcessWrapper.CreateStartInfo
10:16:11.147976 ProcessWrapper.Start - enter
10:16:11.147976 ProcessWrapper.Start - starting process
10:16:13.884115 ProcessWrapper.Start - process started
10:16:13.884115 ProcessWrapper.Start - leave
10:16:16.198231 Process logging event with task handler.
```
### Error logs

From DeleteFiles task:

```
[error]Error: Failed rmRF: rm: could not remove directory (code EBUSY): E:\TFS\Agents\2018\agent06_2\_work\3\s
```

**Comment by Vomisa** [comment]
I also get now the same error message.
It is really interesting, because previously we used TFS 2015 without any error and now we switched to TFS 2018 and I updated all of our agents as well. So the build definition was not changed in-between.

Now the error message is:
```
 Build
Error: Failed rmRF: rm: could not remove directory (code EBUSY): c:\Agent-XXXXXX\_work\4\s
Couldn't delete one or more files
```

When I am going to the mentioned directory it is empty, and I cannot delete it by hand only with admin rights.
When I delete the folder and start the build again, the error message will be the same.

I am trying to delete the full content of the $(Agent.BuildDirectory) folder with "**\*" option.

**Comment by moswald** [comment]
As you've noticed, the build agent now runs tasks from within the source folder, rather from within their own folders. This was done to provide a measure of consistency to each run. Unfortunately, this does seem to break this use case.

One workaround is to instead delete `$(Build.StagingDirectory)`, `$(Build.BinariesDirectory)`, `$(Build.SourcesDirectory)`, and `$(Common.TestResultsDirectory)` individually. This will cover removing the contents of those folders but not attempt to delete the folders themselves.

I'll defer to @vijayma or @azureDaveOps on whether or not we should revert the working folder change, or add a custom working folder setting to the Delete task.

**Comment by Vomisa** [comment]
Exactly this is what I did as a workaround, to delete the directories individually.
In this case only the empty source folder remains after the deletion. It works and acceptable, but hmmm not that nice as it was in TFS 2015 ;-)

**Comment by Rahtgaz** [comment]
Why closing this? This is an open issue and the workaround only deletes folder contents, not the actual folders.
