### ISSUE TITLE
Allow duplicates to be skipped: support on non-Windows

### ISSUE THREAD

**Issue by mikenicholsnfm** [Microsoft/azure-pipelines-tasks#9432]
Hi @alexmullans,

I am getting same error - 'error: Response status code does not indicate success: 409 (Conflict - The feed already contains package'. I am using azure pipeline YAML task _**DotNetCoreCLI@2- Pack and Publish**_ for publishing nuget packages. The flag 'Allow duplicates to be skipped' or property ' allowPackageConflicts: true' doesn't seem to be working for me since I am using Ubuntu build agent. Can you please asssist me

_Originally posted by @chouhanaditya in https://github.com/Microsoft/azure-pipelines-tasks/issues/2119#issuecomment-457755677_

**Comment by alexmullans** [comment]
@anangaur IIRC, there were some discussions a while back about adding a native NuGet switch that would allow push to skip duplicate packages when given a set of packages to push. Did those discussions go anywhere? I'd rather see this as a standard feature of NuGet rather than continuing to be a custom feature of Azure DevOps.

**Comment by anangaur** [comment]
This is being tracked as part of the issue: Commandline switch on nuget push to skip if already published [#1630](https://github.com/NuGet/Home/issues/1630). We hope to take this up soon. /cc: @rrelyea

**Comment by alexmullans** [comment]
Great, thanks! Closing this issue for now then, in favor of https://github.com/NuGet/Home/issues/1630.

**Comment by RehanSaeed** [comment]
Any plans to make `allowPackageConflicts: true` work on Ubuntu or Mac? Is the only option to switch to Windows or loop over packages to call this task?

**Comment by MerkavaPL** [comment]
It seems development is ongoing in https://github.com/NuGet/Home/issues/8100.
You can see the increasing planned sprint numbers there since the beginning of Jun'19.
