### ISSUE TITLE
XUnit Test Reporter cannot parse XUnit reports

### ISSUE THREAD

**Issue by chrish619** [microsoft/azure-pipelines-tasks#9452]
## Environment
- Server - Azure Pipelines
- Agent - Hosted & Private

## Issue Description

The PublishTestResults Task & documentation mention 'XUnit v2' being a supported format - This is actually 'xUnit.net v2' format, and is not capable of reading 'xUnit' result files.

The JUnit TestResultsPublisher _is_ capable of reading 'xUnit' result files.

Can the Test Publisher / FAQ documentation be updated to reflect this?

I understand this has been raised under #1401, and I concur that xUnit often refers to 'xUnit.net', in the C# / .Net application space - but seeing as there _is_ a difference file format, can we not revisit this? Thanks.

**Comment by peni4142** [comment]
Mac can do it!:
![image](https://user-images.githubusercontent.com/33463108/52706397-a19baa00-2f85-11e9-9834-1f63a8525d62.png)


advanced information:
https://github.com/Microsoft/azure-pipelines-agent/issues/2075

**Comment by peni4142** [comment]
Is there some Progress? I am at eight Windows-Tests right now and I will get to ten...

**Comment by peni4142** [comment]
Can't figure out which test is which...
Pls atleast response to this thread
![image](https://user-images.githubusercontent.com/33463108/52863407-11519680-3138-11e9-9016-0ba063c64972.png)

**Comment by divais** [comment]
Can you please share your XUnit file for us to understadn the issues better.

We have added this in our backlog but this isn't in our short term plans i.e. next quarter.

**Comment by navin22** [comment]
The test result formats and the corresponding frameworks are in the doc [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml).
#7659 will be addressing the junit naming issue. Hence I am closing this.
