### ISSUE TITLE
Releases page not opening since morning

### ISSUE THREAD

**Issue by manu4rhyme** [Microsoft/azure-pipelines-tasks#9453]
[Insert error from the logs here for a quick overview]
![image](https://user-images.githubusercontent.com/6754924/51962065-db988680-2484-11e9-8fe7-6cb790ea4e27.png)

Tried emptying cache, cookies, in both edge and chrome

**Comment by kmkumaran** [comment]
The issue is resolved. 

@manu4rhyme - For Release Management service issues, please report in [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html). This repo tracks only Task related issues.
