### ISSUE TITLE
UniversalPackages publish task should support allowPackageConflicts like nuget publish task

### ISSUE THREAD

**Issue by thomas-t1** [Microsoft/azure-pipelines-tasks#9456]
## Environment
- Server - Azure Pipelines

## Issue Description
The Universal Package publish task should support an allowPackageConflicts setting like the nuget publish task.

### Use-case

Multi-package/multi-platform builds e.g. when building C++ packages using VCPKG and exporting multiple combinations of packages to a Universal Package feed; C++ binaries are not guaranteed to be identical for same-source builds (non-deterministic); this feature would be very useful in such cases as an existing UP package with the same version is not an error, but should simply be ignored.

-t1

**Comment by mitchdenny** [comment]
The Universal Package task only publishes one package at a time, couldn't you set up your build to just continue on error?

**Comment by mitchdenny** [comment]
Haven't heard back so I'm closing this issue down. For the time being we believe that continue on error should solve this problem.

**Comment by hbuckle** [comment]
@mitchdenny - Continue on error allows the pipeline to finish, but it's not really a solution - what if there is an actual error? And the build is marked as `partially succeeded`
Having an explicit option to skip duplicates would be very useful.

**Comment by mitchdenny** [comment]
Tagging in @elbatk
