### ISSUE TITLE
Azure App Service Deploy fails with error message

### ISSUE THREAD

**Issue by awentzel** [Microsoft/azure-pipelines-tasks#9458]
## Troubleshooting
I've gone through all log files and don't see a single error in them, the deploy actually still works, but, this task is failing with:

```bash
2019-01-30T15:58:19.1785372Z ##[section]Starting: Azure App Service Deploy: edge-component-explorer
2019-01-30T15:58:19.1789089Z ==============================================================================
2019-01-30T15:58:19.1789147Z Task         : Azure App Service Deploy
2019-01-30T15:58:19.1789224Z Description  : Update Azure App Services on Windows, Web App on Linux with built-in images or Docker containers, ASP.NET, .NET Core, PHP, Python or Node.js based Web applications, Function Apps on Windows or Linux with Docker Containers, Mobile Apps, API applications, Web Jobs using Web Deploy / Kudu REST APIs
2019-01-30T15:58:19.1789300Z Version      : 4.3.19
2019-01-30T15:58:19.1789336Z Author       : Microsoft Corporation
2019-01-30T15:58:19.1789385Z Help         : [More information](https://aka.ms/azurermwebdeployreadme)
2019-01-30T15:58:19.1789440Z ==============================================================================
2019-01-30T15:58:20.0072935Z Got service connection details for Azure App Service:'edge-component-explorer'
2019-01-30T15:58:21.8481651Z Package deployment using ZIP Deploy initiated.
2019-01-30T15:58:54.6873659Z Fetching changes.
2019-01-30T15:58:55.3642391Z Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/45f7qib6.zip (74.59 MB) to /tmp/zipdeploy/extracted
2019-01-30T15:58:55.3642828Z An unknown error has occurred. Check the diagnostic log for details.
2019-01-30T15:58:55.3743631Z ##[error]Failed to deploy web package to App Service.
2019-01-30T15:58:55.3760545Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
```

## Environment
- Server - **Azure Pipelines** or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using **Azure Pipelines**, provide the account name, team project name, build definition name/build number: account name: edgewebui, project name: Edge Web UI, build def name/number: "Edge Component Explorer - Deploy

- Agent - Hosted or **Private**: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: **Ubuntu**

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Azure App Service Deploy - This uses Private build agents, running Ubuntu and MacOS.  I've had this task in both the Build and Release pipeline and I get the same error.  In build, I am using a YAML file.  On Release it's not an option so I'm using Visual Designer. I've looked at every log file on the Azure Web App (Linux) instance both the staging slot and production.  I don't see any clues why this error is happening.  The application runs Node 10.10 with Express server and the OS has AAD turned on for Microsoft.

![screen shot 2019-01-30 at 9 06 11 am](https://user-images.githubusercontent.com/16669785/51994585-586c3600-246e-11e9-91d0-9d51b4cb490e.png)

### Task logs
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]
[ReleaseLogs_38.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2813426/ReleaseLogs_38.zip)

### Error logs
The weird part is I don't see any errors in the error logs. 
[Insert error from the logs here for a quick overview]

**Comment by vincentdass** [comment]
@awentzel , this error is thrown from Azure Layer. Please follow up [here](https://github.com/projectkudu/kudu/issues/2905).

**Comment by awentzel** [comment]
I believe this is now a Kudu issue:  https://developercommunity.visualstudio.com/content/problem/435623/zipdeploy-from-azure-devops-task-failing-in-pipeli.html

**Comment by anandsilwal** [comment]
do we have any workaround this...

**Comment by mkafifi** [comment]
Do you have a fix for this issue

**Comment by guillermomartinez-accenture** [comment]
Was this issue solved?

**Comment by empitesithum** [comment]
Still having the issue on my pipelines

**Comment by Ashanmg** [comment]
I had the same issue with this. after that changing the deployment command **package** directory which is read from the build file folder path.
After giving the correct path deployment was successful for me.

**Comment by Yariksychov** [comment]
Issue persists

**Comment by jeffwilcox** [comment]
Hey @awentzel, good to see you on here... did you ever make any progress? I hit this on a personal coding project over the break... sigh!

**Comment by Yariksychov** [comment]
Just a quick update from my side: issue got resolved after changing the plan for the web app services. Once I did that, the issue got resolved. Tried the same a few times more and experienced failed deployment on free plan only. Thank you.

**Comment by ajay2java2dev** [comment]
For me it was the incorrect path settings as @Ashanmg mentioned. We were deploying the zip package to storage and using WEBSITE_RUN_FROM_PACKAGE to read it (https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#trigger-syncing). But the URL set was incorrect and the path (SAS setting) was not correct.

Evaluating the URL path manually resolved the issue for me. To me it felt like a zip was incorrectly ready and empty folder within /tmp folder was getting read

**Comment by sijucm** [comment]
This is what I work with for the past one year. It fails very often and think of the embarrassment when it fails in Production. A retry will always make it deploy, but in Production I have to explain to so many people. Microsoft just publishes half-baked stuff and senior managers buy it and now I have to suffer. No, this is not just the one issue with Azure functions.

**Comment by 0xUnicorn** [comment]
I experienced this issue today on a Linux Azure App Service after I changed from a win2016 agent to a ubuntu-latests.
Reading @sijucm "work around" I tried re-deploying and it worked.

**Comment by John-Bosch** [comment]
This issue still plagues our deployments. We currently deploy 11 Azure Functions in one pipeline and regularly hit four or five retries before it will go through. All fail with the same result, all succeed on the next attempt (but a latter one will likely fail and force another attempt).

Going to each of the 11 functions and disconnecting them in the deployment center seems to lessen the chance of it happening but eventually the error will return.

**Comment by jrecasens** [comment]
Just got same same error message when deploying from Github (Azure App Service)

**Comment by BZuechReseat** [comment]
This still happens to me but only with Linux web apps. The windows based ones always work

**Comment by yalcinsabancelebi** [comment]
Thanks for WEBSITE_RUN_FROM_PACKAGE settings!

**Comment by swotiendang** [comment]
Deploy to linux app service 70% of the time deployment failed, or very slow (>= 7 mins at least), meanwhile window deployment takes around 30 sec to complete, please reopen this issue

**Comment by Abaiz-khan** [comment]
I am facing the same issue while deploying a react frontend to the web apps (linux), I tried using the deployment center to setup the pipeline but the pipeline is failing after running for 1 hour . I have two pipelines one deploying to web app (windows) and its working fine. Below is the error message ;
"Package deployment using OneDeploy initiated.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Error: Failed to deploy web package using OneDeploy to App Service."
