### ISSUE TITLE
If Select custom Xamarin SDK (Mono 5.16.0), MSBuild is not found in Xamarin.iOS task

### ISSUE THREAD

**Issue by fedemkr** [Microsoft/azure-pipelines-tasks#9460]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      Account name: gnguyo
      Team project name: Abacus Version 3
      Build definition name: Abacus Version 3-CI / #20190130.8

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted macOS Preview      

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

In my project I'm using some features of Xamarin IOS 12.2 (Mono 5.16), but the agent has Default Mono Version: 5.12.0 so if I try to make the build directly it fails.

In order to fix that I've included the script to change the Xamarin SDK as detailed [here](https://docs.microsoft.com/es-es/azure/devops/pipelines/languages/xamarin?view=azdevops#set-the-xamarin-sdk-version-on-macos): 

```
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0
  displayName: 'Select Xamarin SDK version'
```

But when adding that the build breaks showing that the Xamarin.iOS task failed because it couldn't find MSBuild or xbuild. It seems to be related to #5885 but if I set it to *Stable* instead of *5_16_0* the task fails again.

### Task logs

[logs_13.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2814346/logs_13.zip)

### Error logs

##[error]Xamarin.iOS task failed with error MSBuild or xbuild (Mono) were not found on the macOS or Linux agent.. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.

**Comment by madhurig** [comment]
Please review the updated guidance on selecting the right Xamarin SDK:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#xamarin 

Let us know if this is still an issue. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
@fedemkr Hope the guidance in our docs helped. Let us know if this is still an issue for you.

**Comment by fedemkr** [comment]
Added before XamariniOS@2:

```
- script: /bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0"
- script: /bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_10.1.app;sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer"
```

and it worked perfectly thanks

**Comment by agneszitte-nventive** [comment]
@madhurig I'm having the same issue with 5_16_1 with the recent update (since it's not possible to use 5_16_0_0). I tried multiple Xcode version (10.1, 10.2, 10.2.1, 10.3).

**Comment by alexstanfx** [comment]
I get the same "MsBuild or xbuild" not found when using a locally hosted agent on my Mac M1. 

The reason I had to install a local agent is that the pipelines on both appcenter and Azure DevOps are not NET6/C# 10 compatible. At least not when running the XamariniOS@2 task.

My question is about the error the OP and I receive: How does the build process know there is no MSBuild or xbuild on my Machine. Obviously they're both there. 

Also, where can I get the "/scripts/select-xamarin-sdk.sh"? Is it supposed to come withe the macOS agent? Because there is no /scripts folder in the agent's .tar file.
