### ISSUE TITLE
Execute Docker Command is not supported

### ISSUE THREAD

**Issue by spcaswell-mindbody** [Microsoft/azure-pipelines-tasks#9462]
## Environment
Azure Pipelines
   

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Quoting the documentation for the Docker task; emphasis mine.

> Build, tag, push, or run Docker images, or **run a Docker command**.

Running a custom docker command seems impossible, other than login/logout.  It was possible to run custom docker commands before (ie. image prune).  When and why was this functionality removed?  If it wasn't removed then how should it be accomplished?

**Comment by bansalaseem** [comment]
For me its working.

![image](https://user-images.githubusercontent.com/22289943/52175732-36f0ae80-27ce-11e9-86f3-8ed8e3bec95c.png)

![image](https://user-images.githubusercontent.com/22289943/52175737-48d25180-27ce-11e9-8597-179b2116cbaf.png)

Can you please share some screenshots which highlight the problem?

**Comment by spcaswell-mindbody** [comment]
The command field was a drop down.  Apparently you can also type into it as a text field.  Works correctly.
