### ISSUE TITLE
Feature request: GitHub Release Task - Download Release

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/azure-pipelines-tasks#9471]
I'd love to be able to download a release from Github either as a Release Artefact or as a generic "Download Release" task. I'd imagine the following:

\[Download release from GitHub\]

 * Github project URL: [                                              ]
 * Include pre-releases: [x]
 * Version: [^3.0]
 
 * Target location: [$(ArtefactStagingDirectory)\vswhere]
 * Artefact filter: [binary.zip]
 * Extract: [x]
 * File Filter: [**/bin/vswhere.exe]

This would then grab the correct set of files from the release matching the above stats.

In my case I want to grab the latest version of vswhere to add it to my Azure DevOps extension.

**Comment by raiyanalam** [comment]
We have recently published a task for this :)
Check out: [DownloadGitHubReleases](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadGitHubReleasesV0)
Do let us know your feedback once you try it out.

**Comment by placydo** [comment]
Hey,

When running pipeline I get error:
`Build pipeline failed

1 error(s) / 0 warning(s)
Job Job: Step references task 'DownloadGitHubRelease' at version '0' which does not exist.
`

**Comment by gykuma** [comment]
@placydo , are you still facing this issue? If so, can you please share your Azure DevOps account name.

**Comment by placydo** [comment]
> @placydo , are you still facing this issue? If so, can you please share your Azure DevOps account name.

@gykuma Yes still having that issue. I am sorry but I cannot share my DevOps account name publicly.

**Comment by gykuma** [comment]
@placydo Sorry I forgot to share the email. You can share your account name here RM_Customer_Queries@microsoft.com

**Comment by gykuma** [comment]
@placydo it seems you are using task name as _DownloadGitHubRelease_ in your pipeline YAML. This task was recently renamed from _DownloadGitHubRelease'**s**'_ to _DownloadGitHubRelease_. This change is currently in deployment process and should be available in 1-2 weeks time.

Can you please try using the task name 'DownloadGitHubRelease**s**' until this change is available for your account.

```
- task: DownloadGitHubReleases@0
  displayName: 'Download GitHub Releases'
  inputs:
    connection: 'ghconn'
    userRepository: 'user/repo'
    defaultVersionType: specificVersion
    version: 14213417
```

**Comment by placydo** [comment]
Hey,
This issue is resolved by adding missing 's'
Got yet another issue which might not be an issue.
Is DownloadGitHubReleases task working only with Github but not with Github Enterprise?
I am keep getting error:
`Job Job: Step  input connection expects a service connection of type github but the provided service connection myconnection-github is of type githubenterprise.`

**Comment by gykuma** [comment]
Currently GitHub Enterprise as connection type is not supported by DownloadGitHubReleases task. We will be adding support for it in couple of months.
