### ISSUE TITLE
vstest.console.exe failed with return code: 1   Test run aborted

### ISSUE THREAD

**Issue by susan2453** [Microsoft/azure-pipelines-tasks#9475]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines 
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  sapcordaservices/Genesis  All builds

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

We have been using AzureDevOps for our builds for over a year. Friday (01/25/2019) something changed that has affected all of our builds. They build debug and release fine, the error occurs during the Solution Unit test phase. The test run is aborted but there is minimal data. Downloaded logs show pretty much the same lack of information.

We do believe the version of the vstestconsole switched from 15.8.0 to 15.9.0 during this time period.  We attempted to fall back to the 15.8.0 version.  That allowed us to have a successful build, but now we get intermittent occurrences of the same failure. We get about a 25% success rate.

Can confirm that all test run and pass as expected when run locally with Visual Studios.

### Task logs
 have two sets of logs. They are building the same changes set, nothing changed on our side other than the person queing the build. logs_2587.zip - buils returns fine. logs_2592(1).zip - error seen
[logs_2587.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2818823/logs_2587.zip)
[logs_2592 (1).zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2818830/logs_2592.1.zip)

### Error logs

2019-01-28T07:42:17.6905873Z 
2019-01-28T07:42:17.6905913Z Test Run Aborted. 
2019-01-28T07:42:17.7343926Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests. 
2019-01-28T07:42:17.7953924Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1 
2019-01-28T07:42:17.9086161Z ##[warning]Invalid results file. Make sure the result format of the file 'D:\a\3\s\TRUNK\UnitTests\GenesisUnitTest\TestResults\VssAdministrator_fv-az380_2019-01-28_07_42_17.trx' matches 'VSTest' test results format. 
2019-01-28T07:42:17.9439348Z ##[error]VsTest task failed.

**Comment by karanjitsingh** [comment]
@susan2453, if possible can you point me to the build definition which is getting these issues? If you're not comfortable with sharing it publicly you can mail me at `karsin at microsoft dot com`

**Comment by acesiddhu** [comment]
@susan2453 apologies for the delay. Is this still happening? Can u check if disabling code coverage mitigates the issue? in the meantime we are checking the logs

**Comment by acesiddhu** [comment]
@susan2453 after looking at the logs it is clear that the testhost (the process which runs the test) dies off in between the run. Looks like the test that are running are C++ tests. I feel that there is some test code that is causing a crash in testhost. Can you enable this option to get a dump of testhost process when it crashes?

![image](https://user-images.githubusercontent.com/1168823/53383500-ea982900-399d-11e9-922e-0d2b786512a6.png)

**Comment by acesiddhu** [comment]
@susan2453 if you are still facing the issue, please try the above feature to help identify the issue. if you are still blocked please reopen the issue. Closing this issue for now

**Comment by lankaapura** [comment]
Hey @acesiddhu were you able find a fix or workaround for this issue?

**Comment by didaskein** [comment]
You could also check my note : https://github.com/Microsoft/azure-pipelines-tasks/issues/6625  (i have an issue with the /obj folder, the dll &json arein the bin folder)

**Comment by lankaapura** [comment]
Thanks @didaskein, it was something similar in my case too.
