### ISSUE TITLE
Powershell task does not expose variables to a task group

### ISSUE THREAD

**Issue by stukalin** [microsoft/azure-pipelines-tasks#9482]
## Environment
- Server - Azure Pipelines    
- Agent - Hosted VS2017

## Issue Description

I am trying to extract a powershell task into a task group in order to reuse the script and I wanted to pass some parameters as variables but it seems the pipeline doesn't identify those as task group variables:

![image](https://user-images.githubusercontent.com/9863365/52114308-c9515080-261c-11e9-8294-e2d4cd626c95.png)

Nothing happens in this case. The _command line_ task has the same problem. I tried to add another non-cmd task and there it worked as expected. This issue might be related to #8737 but is still slightly different

**Comment by stukalin** [comment]
Found a strange workaround. If you use `$(some text)` in your powershell script then the `some text` is exposed as a variable. Like this

`Select-String -Pattern "$(Include Filter)" -Quiet`

And the `Include Filter` variable pops up and I can use it from a parent task.

**Comment by bryanmacfarlane** [comment]
Looks like an issue with task groups ... routing

**Comment by ashokirla** [comment]
We only consider any $(Var) format and parameterize it as part of task group.

**Comment by marrobi** [comment]
Hit this today, have an environment variable in a task within a task group with a value in format `$(Var)` and it does not appear as a parameter. If I enter the variable in another part of the task, such as script arguments it does appear. So seems specific to environment variables.

**Comment by qJake** [comment]
Ran into the same thing today (Azure Pipelines latest (Sprint 165)).

If you define a variable in Control Options > Custom Condition, it's not picked up by the Create Task Group dialog.

I tried both syntaxes: `eq('$(PublishArtifacts)', 'true')` and `eq(variables['PublishArtifacts'], 'true')` - neither worked.

**Comment by qJake** [comment]
Still an issue - bad bot!

**Comment by oising** [comment]
This is still an issue in 2025, and not just for powershell tasks :/
