### ISSUE TITLE
Universal Packages Task Hangs in Pipeline

### ISSUE THREAD

**Issue by mwhisler** [Microsoft/azure-pipelines-tasks#9494]
## Environment
- Server - Azure Pipelines 
    
- Agent - Hosted or Private: 
    
     - Private version 2.141.1

## Issue Description

I have two VMs in Azure both were created with the same ARM template and both configured with the same DSC.  One of these servers (DEV) downloads the universal package just fine, but the TEST server does not.

In Azure DevOps, the task begins to execute, downloads the artifacttool.exe and launches the command to download the package, then it just sits there and hangs until it times out.

When I get on the TEST server and run the command in a command prompt (with the patvar set), it only gets to 2% of the download, retries a bunch of times and then just stops.  The only real error in the command prompt window is "Could not initialize dataport".  It seems to connect to VSTS and the package feed just fine, but just stops after about 25 attemps of the DownloadCommand.

For reference, the other VM (DEV) is agent version 2.142.1 and works great.

### Task logs

2019-02-01T23:25:04.3534524Z ##[section]Starting: Baseline netFORUM 2017.1.56
2019-02-01T23:25:04.3540187Z ==============================================================================
2019-02-01T23:25:04.3540268Z Task         : Universal Packages
2019-02-01T23:25:04.3540306Z Description  : Download or publish Universal Packages.
2019-02-01T23:25:04.3540341Z Version      : 0.145.2
2019-02-01T23:25:04.3540375Z Author       : Microsoft Corporation
2019-02-01T23:25:04.3540427Z Help         : [More Information](https://aka.ms/universalpackagesannounce)
2019-02-01T23:25:04.3540463Z ==============================================================================
2019-02-01T23:25:06.5584327Z SYSTEMVSSCONNECTION exists true
2019-02-01T23:25:07.6005193Z Found tool in cache: artifacttool 0.2.88 x64
2019-02-01T23:25:07.6404240Z SYSTEMVSSCONNECTION exists true
2019-02-01T23:25:08.4068558Z Downloading package: nfep-baseline, version: 2017.1.56 using feed id: bc71352e-b0f6-4fb5-97d0-30438fae15c5
2019-02-01T23:25:08.4173968Z [command]C:\vstsagent\A1\_work\_tool\artifacttool\0.2.88\x64\ArtifactTool.exe universal download --feed bc71352e-b0f6-4fb5-97d0-30438fae15c5 --service https://vsrm.dev.azure.com/ahait/ --package-name nfep-baseline --package-version 2017.1.56 --path PATH_HERE --patvar UNIVERSAL_DOWNLOAD_PAT --verbosity Debug
2019-02-01T23:31:37.8191049Z ##[error]The operation was canceled.
2019-02-01T23:31:37.8196521Z ##[section]Finishing: Baseline netFORUM 2017.1.56

### Error logs

{"@t":"2019-02-01T23:40:50.9061056Z","@m":"Obtained package metadata","@i":"ae648446","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:40:50.906Z"}
{"@t":"2019-02-01T23:40:50.9224843Z","@m":"Manifest ID: 8F20A8715227AD7D8F285FB00B9E8FEFC6DD97CDC592A9BD26BE32C850F0863B02 SuperRoot ID: 35C1ED677660C78A79BFDA5609B2CBD34BEB2D9C9828F23D84CCFC13213DFC0D02","@i":"3383ae4b","@l":"Debug","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:40:50.922Z"}
{"@t":"2019-02-01T23:40:50.9243176Z","@m":"Description: netFORUM Enterprise baseline assemblies and files.","@i":"c9a7f586","@l":"Debug","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:40:50.924Z"}{"@t":"2019-02-01T23:40:53.6606904Z","@m":"Could not initialize dataport.","@i":"62e541c0","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:40:53.660Z"}
{"@t":"2019-02-01T23:40:53.6644194Z","@m":"Downloaded 0.0 MB out of 574.9 MB (0%).","@i":"abc356cd","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:40:53.664Z"}
{"@t":"2019-02-01T23:40:58.6716814Z","@m":"Downloaded 10.3 MB out of 574.9 MB (2%).","@i":"6dbe7f12","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:40:58.671Z"}
{"@t":"2019-02-01T23:41:03.6827088Z","@m":"Downloaded 10.3 MB out of 574.9 MB (2%).","@i":"6dbe7f12","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2019-02-01 23:41:03.682Z"}

**Comment by mwhisler** [comment]
Update: I skipped over the artifact tool and ran this on the latest version of the VSTS CLI installed with chocolatey and I can reproduce the bug.

Universal Packages is currently in preview.
Creating connection with personal access token.
Creating connection with personal access token.
Obtained package metadata
Could not initialize dataport.
Downloaded 0.0 MB out of 574.9 MB (0%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).
Downloaded 10.5 MB out of 574.9 MB (2%).

**Comment by mwhisler** [comment]
Another update: I ended up blasting the folder where the --path parameter was going and it works now.  I took a backup of the directory, copied it to another drive and was able to reproduce the error on that directory again which makes me think NTFS permissions.  Who knows?

**Comment by mitchdenny** [comment]
Hi @mwhisler this is a useful diagnostic. Thanks for reporting that. We have had a few hangs reported in various places and this is a useful observation. I'll pass this along to the team to get them to see if it helps identify the issue.

**Comment by jerickmsft** [comment]
Thanks for reporting this @mwhisler. I know we had an issue where restoring to a volume that is out of disk space would cause a hang - which sounds quite similar.  However, I would have thought that was fixed in the version you are using.

**Comment by mwhisler** [comment]
Thanks @mitchdenny  and @jerickmsft.  I've got plenty of disk space on these VMs.  Today I'm going to copy the offending folder structure down to my local machine and try to reproduce.  If so, I will begin systematically figuring out which folder(s) or file(s) is causing the hangup and see what's going on.

**Comment by mwhisler** [comment]
I pulled the entire folder structure down to my local machine and called the vsts cli to download the package and it hangs here as well.  Seems to be something with a file or folder.  If there is any additional way to output debugging messages other than --verbose, please let me know.

Universal Packages is currently in preview.
Creating connection with personal access token.
Creating connection with personal access token.
Obtained package metadata
Could not initialize dataport.
Downloaded 0.0 MB out of 574.9 MB (0%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).
Downloaded 30.9 MB out of 574.9 MB (5%).

**Comment by alexmullans** [comment]
@mitchdenny any updates on this one?

**Comment by mitchdenny** [comment]
We haven't heard back from Mark so I think we can close for now.

**Comment by mwhisler** [comment]
Hey all, lost track of this one.  Still no resolution or understanding as to why it hangs.  However, if I blast the directory and pull down the package again, it works.  Meant to close the loop on this one in case somebody else runs into this issue.  We can close this.  Thanks for checking on it @alexmullans.  I can still reproduce it with the folder structure I have so if I uncover anything else, I'll let you know.

**Comment by alexmullans** [comment]
Great, thanks for the update!
