### ISSUE TITLE
AzureBlob FileCopy generating warnings 

### ISSUE THREAD

**Issue by KarishmaGhiya** [Microsoft/azure-pipelines-tasks#9495]
## Environment
- Server - Azure Pipelines
     
We're an internal microsoft team, that is working on the following project, in case you need access to the project, you can email me at kaghiya@microsoft.com

https://dev.azure.com/azure-sdk/playground/_releaseProgress?_a=release-environment-logs&releaseId=35&environmentId=35

- account name: `azure-sdk` (This is azure-sdk org in the dev division. I'm not sure what that account name would be)

- team project name : `playground`

- Task : `Publish Artifacts`

- Agent - `Hosted VS2017 `

## Issue Description
Getting two warnings on running AzureBlob File Copy task on Azure Devops:
```
##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

##[warning]The names of some imported commands from the module 'AzureRM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
```

### Task logs
[tasklog_7.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2824000/tasklog_7.log)

**Comment by arjgupta** [comment]
@KarishmaGhiya we import the AzureRm powershell module in the task Azure File Copy. This powershell module has certain commands that do not follow the naming scheme that powershell recommends. And so when we import this module we get the kinds of warnings that you have mentioned.

**Comment by andydkelly-ig** [comment]
Is this going to get resolved as throwing warnings permanently is not n acceptable solution @KarishmaGhiya as it means genuine warnings are likely to get missed
