### ISSUE TITLE
Consider introducing a shorthand for Powershell Core

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/azure-pipelines-tasks#9496]
I'd like to suggest that `pwsh` be made a new shorthand for PowerShell Core. I like using the `powershell` shorthand over the task syntax in Yaml, but to make use of Powershell Core (on Windows at least), I need to pass the `pwsh` input in, always.

This effectively means that to use Powershell Core by default we are confined to using the task syntax and the `powershell` shorthand becomes useless for those who do not want the non-Core Powershell.

Does this sound like something you could consider?

**Comment by ericsciple** [comment]
it's already supported :)

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pwsh

**Comment by TomasHubelbauer** [comment]
@ericsciple Can you clarify if this runs Powershell Core on Windows?

**Comment by TomasHubelbauer** [comment]
I have tested this and `pwsh` defaults to PowerShell Core on Windows.

**Comment by TomasHubelbauer** [comment]
I have suggested an edit to the docs to capture this: MicrosoftDocs/vsts-docs#3635
