### ISSUE TITLE
Publish Test Results plugin ignores the test name (or so it seems) (NUnit 3)

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#9497]
## Environment
- Server - TFS on-premises, version 16.131.27701.1

- Agent - Private:

Capability name | Capability value
-- | --
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.131.0

## Issue Description

Two NUnit 3 XML result files are attached. Both seem to have the same structure. Yet in one of them incorrect test name is published.
Please, observe:
**Correct:** 

![image](https://user-images.githubusercontent.com/489792/52188509-34f41300-2801-11e9-8d10-e08ae186e550.png)

The XML test result is `CSTests_ThroughLoadBalancer.xml` (in the attached zip file)

**Incorrect:**

![image](https://user-images.githubusercontent.com/489792/52188663-12162e80-2802-11e9-81dd-904d793faf98.png)

The XML test result is `CSTests_RunJob.xml` (in the attached zip file). The test case name in the XML file is `BJE.RunJobTest.RunJob`, yet it is displayed `RunJob`

[TestResults.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2826439/TestResults.zip)

**Comment by SadagopanRajaram** [comment]
I tried this on the latest agent and it displayed the full name in both cases. I don't believe there have been changes in this area but I will relook at the older agent to see if there is an issue

**Comment by SadagopanRajaram** [comment]
This seems related to https://github.com/Microsoft/azure-pipelines-tasks/issues/9499. If the test is part of a fixture, the Nunit file has only simple name and therefore we use that only.
