### ISSUE TITLE
SAS Token not working for AzureBlob File Copy

### ISSUE THREAD

**Issue by issacnitin** [Microsoft/azure-pipelines-tasks#9498]
The SAS Token generated along with URL gives unauthorized error

I've tried version 3 and 2

**Comment by arjgupta** [comment]
Hi @issacnitin , recently we made changes to the SAS token generated. Earlier the SAS token would have only Read and List permissions. Now it has Read, Write, List and Delete permissions. Maybe earlier you were trying to perform an action for which the SAS token did not have permission for. Can you try again and let us know.

**Comment by issacnitin** [comment]
@arjgupta No, I needed read permission only.. I remember using SAS token generated with read only permission from storage and get things working. I'll try again and let you know

**Comment by niadak** [comment]
@issacnitin , Did you get a chance to try the task? Are you still facing the issue?

**Comment by chris9263** [comment]
@niadak I also struggle with getting the sas token to work, i get this error code when trying to reference a nested template located in the storage account. 
"code": "InvalidContentLink",
"message": "Unable to download deployment content from 'https://dev.blob.core.windows.net/...............'. The tracking Id is 'aeb3661e-bd3b-4713-8123-186d48e1bdab'.

**Comment by issacnitin** [comment]
@niadak It's still not working, these are the release logs:
[ReleaseLogs_90.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2991518/ReleaseLogs_90.zip)

The generated Uri cannot be accessed, giving the error:
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:be4a5ddb-c01e-00b2-3ecc-df90ef000000 Time:2019-03-21T09:56:10.4925869Z
</Message>
<AuthenticationErrorDetail>Signature size is invalid</AuthenticationErrorDetail>
</Error>

**Comment by niadak** [comment]
@issacnitin,  Can you please share the debug logs of the release. Refer to the [instructions ](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#build-and-release-logs)to generate debug logs.

Note that the SAS token generated by the task is only valid for 4 hours by default. Recently we have added a task parameter to customize the token expire time. Make sure you are using the token with in expire time.

**Comment by issacnitin** [comment]
[ReleaseLogs_92.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3002159/ReleaseLogs_92.zip)
There you go
Yes I'm setting token expiry to a very large number

**Comment by issacnitin** [comment]
I think I got the issue, URL generated is correct but azure CLI drops encoded characters...

**Comment by niadak** [comment]
OK.  Seems like similar issue has been reported to AzureCLI github repo also.
https://github.com/Azure/azure-cli/issues/2004
