### ISSUE TITLE
Publish Test Results plugin does not render NUnit test results using TestFixtureSource correctly

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/azure-pipelines-tasks#9499]
## Environment
- Server - TFS on-premises, version 16.131.27701.1

- Agent - Private:

Capability name | Capability value
-- | --
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.131.0

## Issue Description
There are no errors, but the final rendering does not let us distinguish between the tests that ran in the different invocations of the Test Fixture. Here is an example view of the results:
![image](https://user-images.githubusercontent.com/489792/52209792-fc7d2500-2852-11e9-8014-cc9b3862c14c.png)

The snapshot shows inconsistent naming - some test nodes are named using the test case full name (good), but some are not (bad). This is especially bad for the test cases of a Test Fixture using TestFixtureSource - go figure which test node refers to which test!

Here is the test result XML - 
[CSTests.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2828064/CSTests.zip)

**Comment by SadagopanRajaram** [comment]
Thanks for the feedback. The current parser derives the test name from the name in the test-case node and does not use the fixture to disambiguate. We will need to look at this a little more closely to determine how to parse the nunit file to derive the right test name to publish.

**Comment by divais** [comment]
Adding this to our backlog but in all transparency this isn't in our short term plans i.e. next quarter.

**Comment by MarkKharitonov** [comment]
Still a problem.
