### ISSUE TITLE
List branches on a Github repository 

### ISSUE THREAD

**Issue by elranu** [Microsoft/azure-pipelines-tasks#9507]
## Environment
- Azure pipelines

- Agent - Hosted or Private: 
    - Hosted

## Issue Description

I cannot list branches of a repository. Can you tell me please the `selector` and the `keySelector` I should use to list branches. I do not find the doc here: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source%20providers/list%20branches?view=azure-devops-rest-5.0

code on task.json:
```
"sourceDefinitions": [{
            "target": "githubRepository",
            "endpoint": "/$(system.teamProject)/_apis/sourceProviders/GitHub/repositories?serviceEndpointId=$(githubEndpoint)",
            "selector": "jsonpath:$.repositories[*].id",
            "keySelector": "jsonpath:$.repositories[*].id",
            "authKey": "tfs:teamfoundation"
        },
        {
            "target": "branch",
            "endpoint": "/$(system.teamProject)/_apis/sourceProviders/GitHub/branches?serviceEndpointId=$(githubEndpoint)&repository=$(githubRepository)&api-version=5.0-preview.1",
            "selector": "jsonpath:$.[*]",
            "keySelector": "jsonpath:$.[*]",
            "authKey": "tfs:teamfoundation"
        }]
```

I have already tried: `jsonpath:$.branches.value[*].name`  and `jsonpath:$.branches[*].name`  but it did not work :(

Also I have tried `jsonpath:$[*]`

Thanks in advanced

### Task logs
I don't know how to get this logs. Can you give me a link?

### Error logs
none

**Comment by elranu** [comment]
Some help to troubleshoot this problem?

**Comment by joshmgross** [comment]
Hey @elranu, are you creating your own task and trying to use the API to list branches?

**Comment by elranu** [comment]
Hi @joshmgross I'm creating my own task.

**Comment by joshmgross** [comment]
Hey @elranu, looking at the rest API, the return value is something like: 
```
{
  "count": 7,
  "value": [
    "autoCancel",
    "azure-pipelines",
    "demo",
    "joshmgross-patch-1",
    "master",
    "release",
    "test"
  ]
}
```

So could you try

```
"selector": "jsonpath:$.value[*]",
"keySelector": "jsonpath:$.value[*]",
```

**Comment by madhurig** [comment]
@elranu - Please try Josh's suggestion and let us know if that works for you.

**Comment by elranu** [comment]
Yes, it worked. Thanks
