### ISSUE TITLE
Publishing code coverage results on Azure Pipeline

### ISSUE THREAD

**Issue by saxenark** [Microsoft/azure-pipelines-tasks#9522]
Hi,

I have the following YAML as part of my azure build pipeline. I am interested in getting the code coverage results from my unit test cases. I am unclear of what value to give for sumaryFileLocation, as I do not know where the coverage.xml is going to be located.

My intention is to publish the HTML report containing the code coverage report.

I am using .NET 4.7.2 on Visual Studio 2017

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True
    publishRunAttachments: True

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/cobertura/coverage.xml
    #reportDirectory: # Optional
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional

**Comment by karanjitsingh** [comment]
@saxenark, just to confirm, how are you generating cobertura code coverage files since VSTest task does not generate cobertura format. If you're only interested in .net coverage then VSTest will automatically publish the code coverage results.

**Comment by nigurr** [comment]
@saxenark VsTest doesn't generate coloratura format of code coverage report. 

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

As mentioned earlier in your previous threads https://github.com/Microsoft/vstest/issues/1916
We are enhancing Coverage experience in Azure DevOps.
