### ISSUE TITLE
Cannot use v4 in AzurePowerShell

### ISSUE THREAD

**Issue by rstra** [Microsoft/azure-pipelines-tasks#9524]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines

- Agent - Hosted or Private: 
    
    - VS2017 Hosted Image

## Issue Description

When I specify AzurePowershell@4, I am unable to kick off the pipeline. 
![image](https://user-images.githubusercontent.com/27729340/52420505-cf7d7c00-2ab7-11e9-8cc8-08a603b2136f.png)

### Task logs

No logs were created.

### Error logs

An error occurred while loading the YAML build pipeline. wrong number of segments

**Comment by rstra** [comment]
@kmkumaran

**Comment by niadak** [comment]
@rstra ,
Azure PowerShell V4 task has not deployed to production yet. It will be available in 2-3 weeks. Please use V3 task for now.

**Comment by rstra** [comment]
@niadak I am getting another error with V3, I will open a separate issue with that.

**Comment by niadak** [comment]
Sure, please open a new issue for V3 task. I am closing this issue for now.
