### ISSUE TITLE
Exclude files from the App_Data folder option should not be checked by default

### ISSUE THREAD

**Issue by christophedemey** [Microsoft/azure-pipelines-tasks#9532]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build 
number: https://dev.azure.com/build-orisnv/

- Agent - Hosted : 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Hosted 2017 pool.

Task : Azure App Service Deploy

## Issue Description

[Include task name(s), screenshots and any other relevant details]
Exclude files from the App_Data folder option is checked by default.
This prevents deployment of my webjobs which reside in the App_Data directory on publish and was very frustrating to find out why it was not working.
Please make it unchecked by default in the task.

Thanks.

**Comment by vincentdass** [comment]
@christophedemey , thanks for the feedback. 
Also, We are not currently investigating much on MSDeploy and moving to the model where Zip Deploy and Run From Package is the default deployment mechanism.
Can you  select `Run From Package` as your deployment mechanism. Also, I assume the packages are generated by MSBuild, if so, change your package structure by following the steps [here](https://github.com/Microsoft/azure-pipelines-tasks/wiki/Migrating-from-Web-Deploy-to-Run-From-Package-deployment-mechanism)

**Comment by christophedemey** [comment]
Hi

Our problem with run from package is that we also require 
-WEBSITE_LOCAL_CACHE_OPTION always
and in combination with Run from package 1 in the web app, the web app will fail.

**Comment by vincentdass** [comment]
@christophedemey , Can u use `Zip Deploy` option instead of `Run From Package`?

**Comment by christophedemey** [comment]
I guess i could, just wondering why App_Data option is checked by default to not copy the files to the server, this is where webjobs live ! :(

**Comment by vincentdass** [comment]
@christophedemey , this option was enabled by default as `Application Insights` Web Job also reside under App_Data folder. The deployment would remove the content which was reported by many customers. To avoid this, we made this option default.
