### ISSUE TITLE
Please add Pull Request Number into Release Pipeline variables

### ISSUE THREAD

**Issue by chris31389** [microsoft/azure-pipelines-tasks#9541]
## Environment
- Azure Pipelines
- Agent: Hosted VS 2017

## Issue Description

With the new release to VS for the [Pull Request Release Pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops), it would be useful to include the Pull Request Number as an environment variable, similar to [System.PullRequest.PullRequestNumber](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops#system-variables) in the Build Pipeline.

**Comment by chris31389** [comment]
This issue was raised as requested from @madhurig in issue #6564

**Comment by kgehmlich** [comment]
Any movement on this? We're building a release pipeline that requires the GitHub PR# when deploying.
Are there any known workarounds for now?

**Comment by kgehmlich** [comment]
The following PowerShell line will extract the PR #, however it's obviously quite fragile and could be made more robust:
```
$prNumber = ($env:BUILD_SOURCEBRANCH).split("/")[2]
```

**Comment by ArieHein** [comment]
System.PullRequest.PullRequestId
System.PullRequest.PullRequestNumber
note:  This variable is initialized only if the build ran because of a Git PR affected by a branch policy

**Comment by kgehmlich** [comment]
@ArieHein those are only available on Build pipelines, not on Release.

**Comment by davemanton** [comment]
We're looking at using gates after the stage deployment on releases with approvals to complete pull requests.  We can't complete because the pull request information isn't there.  We need the pull request Id.  Is this likely to be included at any point?

**Comment by magpet01** [comment]
This is still very needed.
