### ISSUE TITLE
Azure Monitor Alerts task - Resource name field needs to support piepline variables

### ISSUE THREAD

**Issue by AnthonyBorton** [Microsoft/azure-pipelines-tasks#9543]
## Issue Description

**Azure Monitor Alerts task**
You need to be able to pass pipeline variables into the Resource Name field in this task. Currently the only option is to use the drop down arrow but this only works for resources that have already been created.

![no support for pipeline variables](https://user-images.githubusercontent.com/20076700/52568135-a105f500-2e59-11e9-9820-4c70413a1c07.jpg)

**Comment by shashban** [comment]
Hi Anthony,
It is currently a limitation of the task to pick an existing resource. Use of variables for resource name is not supported.
Can you look to use AzCli task for configuring alerts instead? 
https://docs.microsoft.com/en-us/cli/azure/monitor/alert?view=azure-cli-latest#az-monitor-alert-create

Thanks
Shashank
