### ISSUE TITLE
DotNetCore currently does not support using an encrypted Api Key.

### ISSUE THREAD

**Issue by rifuller** [microsoft/azure-pipelines-tasks#9545]
Duplicate of [this](https://github.com/Microsoft/azure-pipelines-tasks/issues/7160) which as closed due to age but it wasn't fixed.

## Environment
- Server - Azure Pipelines (o365exchange/o365 core/1350)
- Agent - Hosted (Hosted or Hosted 2017)

## Issue Description

dotnet restore fails when using an API key credential for accessing protected NuGET feeds.

### Task logs

```
[section]Starting: Restore
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
Version      : 2.147.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
==============================================================================
[command]C:\windows\system32\chcp.com 65001
Active code page: 65001
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
d99a4b9f-1b50-40a0-bbe0-f52baf24a828 exists true
Saving NuGet.config to a temporary config file.
Using authentication information for the following URI: https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/OSS_All/nuget/index.json
##[error]Error: DotNetCore currently does not support using an encrypted Api Key.
##[error]Packages failed to restore
##[section]Finishing: Restore
```

### Error logs

As above.

**Comment by rifuller** [comment]
Though as described in the other thread, workaround for Azure Devops-based feeds is to use the API key as the password with Basic authentication.

**Comment by sachinma** [comment]
@alexmullans can you look at this request?

**Comment by elbatk** [comment]
Adding @infin8x as FYI.

I'm going to close this in favor of the duplicate #7160 which has been reopened and Alex is tracking. 

@rifuller Alex commented ~4 days after this one that there had been some work done to dotnetcore, are you still seeing an issue here?
