### ISSUE TITLE
Publish to Web App for Containers (Windows) missing

### ISSUE THREAD

**Issue by Teodelas** [Microsoft/azure-pipelines-tasks#9548]
There is no option to publish to Web App for Containers (Windows)

**Comment by vincentdass** [comment]
@Teodelas , as you said, the task doesnt support Web App for Windows containers. As a workaround, you can use `Azure CLI` to update container settings.

**Comment by frankfuu** [comment]
I found this out by accident but you can actually hardcode the name of your windows container app in this template Azure Web App for Container (Preview) - [AzureWebAppContainerV1 ](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureWebAppContainerV1). It doesn't provide validation though, because i tried deploying an image based on windows server core 2019 (which isn't yet supported) and didn't give me an error message.

**Comment by frankfuu** [comment]
I ended up using Azure's CLI's  for my CI/CD pipeline

```
az webapp config container set -g <rgName> -n <appName> \
--docker-custom-image-name <fully qualified image name>
```

Reference - [az webapp config container set
](https://docs.microsoft.com/en-us/cli/azure/webapp/config/container?view=azure-cli-latest#az-webapp-config-container-set)

**Comment by eriawan** [comment]
@frankfuu 

```
az webapp config container set -g <rgName> -n <appName> \
--docker-custom-image-name <fully qualified image name>
```

thanks for the info! have you been able to use that CLI using custom image name on Azure Container Registry? afaik, that CLI only works on images pulled from Docker Hub.

**Comment by frankfuu** [comment]
@eriawan 

I'm actually using Azure Container Registry. You can set this by
```
az webapp config container set -g <rgName> -n <appName> \
--docker-registry-server-url "https://<acrName>.azurecr.io" \
--docker-registry-server-user "<acrUserName>" \
--docker-registry-server-password "<acrPassword>" \
--docker-docker-custom-image-name "<acrName>.azurecr.io/<repoName>:<tag>" \
```

You can verify that you set it correctly by running

```
az webapp config container show -n <appName> -g <rgName>
```

Note that the `DOCKER_REGISTRY_SERVER_PASSWORD` will return a value of `null` but i think it actually gets saved and just hides it on the cli for security.

**Comment by vincentdass** [comment]
@frankfuu , @Teodelas , @eriawan 
The support for Windows container deployment is added and will be available in ~4-5 weeks.

**Comment by f2calv** [comment]
> --docker-docker-custom-image-name

double use of "--docker" but otherwise thanks for saving me (any more) pain :)
