### ISSUE TITLE
Packer 0* & 1* fails building image from vhd - did not finish in the allotted time.

### ISSUE THREAD

**Issue by cejkyle** [Microsoft/azure-pipelines-tasks#9549]
We are unable to use packer to build immutable images at the moment. It is now consistently failing with this error message. This is the case even when we use the only working packer base vhd we have and managed to create in November last year.
If we take that image, create vm, and then sysprep and generalise it and add it back to packer it now fails with this error. 
Can anyone suggest why packer appears to be timing out even though the packer vm has been spun up correctly and the login screen is available suggesting it has been generalised successfully?
Something is causing packer to get stuck when it should be proceeding correctly.,

details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"OSProvisioningTimedOut\",\r\n \"message\": \"OS Provisioning for VM 'packerwinupdate' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image:\\r\\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \\r\\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ \"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by issacnitin** [comment]
@cejkyle For us to debug better, could you share the logs with system.debug variable set to True? 
Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#build-and-release-logs

**Comment by amaljg** [comment]
@cejkyle - Are you still facing this issue? If so, can you share the debug logs as @issacnitin mentioned above?

**Comment by amaljg** [comment]
Since we don't have the logs, we can't investigate this further. If you are still facing this issue, kindly share the debug logs as mentioned above and reopen the issue.
