### ISSUE TITLE
TIA always fails during update test results

### ISSUE THREAD

**Issue by jimmylewis** [Microsoft/azure-pipelines-tasks#9553]
## Troubleshooting
Incidentally, this doesn't repro when I turn System.Debug to true, so I couldn't collect a diagnostic that way.  However, I don't want this set to true on all of my builds.

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2406033 is an example where it fails.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2405701 is an example where I tried running with System.Debug=true and it passed.

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

Agent has Windows 2016, agent version is currently 2.146.0

## Issue Description

During the VSTest task, after tests have run successfully and during the "Update Test Results" step, my builds always fail with an error like this:

>##[error]
>Exception : Collection contains duplicate id: 105459

### Task logs
Log is from having System.Debug = false, as this issue won't reproduce for me when System.Debug = true.
[log_9_2406034.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2854271/log_9_2406034.zip)

Here is a TRX file as well: 
[asplab_WEBTOOLS-CI-008_2019-02-11_18_14_45.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2854275/asplab_WEBTOOLS-CI-008_2019-02-11_18_14_45.zip)

**Comment by prawalagarwal** [comment]
@jimmylewis Your logs indicate that you are running data driven tests in XUnit. We do not support data driven tests from xunit and nunit frameworks in vstest task (mstest data driven tests are supported) and cannot assertively say how your tests will behave. Also, please try setting Hydra.EnableApiFlow as true in your definition and let us know if this helps with a better experience with how your results are handled.

**Comment by jimmylewis** [comment]
@prawalagarwal we have a mix of MSTest and XUnit tests.  I'd like to have TIA working for the MSTest assets, as they are the dominant portion by number and by execution time.

I tried enabling `Hydra.EnableApiFlow` and ran into this error:
>**************** Starting test execution *********************
##[error]ExecuteVsTestPhase.Run: Exception occurred in the test execution phase: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TestPlatform.VsTestConsole.TranslationLayer, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.TestPlatform.VsTestConsole.TranslationLayer, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MS.VS.TestService.TestPlatform.v2.VsTestPlatformV2..ctor(String vstestConsolePath, List`1 adapterPaths, String diagFile, String traceFile)
   at MS.VS.TestService.VstestConsoleAdapter.VstestApiRunExecutor.GetTestPlatform(VstestConsoleRunContext runContext) in D:\V2.0\A1\_work\56\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\Executor\VstestApiRunExecutor.cs:line 75
   at MS.VS.TestService.VstestConsoleAdapter.VstestApiRunExecutor.RunTests(VstestConsoleRunContext testRunContext) in D:\V2.0\A1\_work\56\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\Executor\VstestApiRunExecutor.cs:line 25
   at MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase.Run(VstestConsoleRunContext testRunContext, CancellationToken cancellationToken) in D:\V2.0\A1\_work\56\s\Ta\Agent\VS.TestService.VstestConsoleAdapter\Phases\VsTest\ExecuteVsTestPhase.cs:line 35
>
>WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>**************** Completed test execution *********************

However, that step of the build (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2442554) was marked as successful even though no tests were actually run.  These seems like a severe bug.  My agent has VS2019 (not 2017) installed, if that makes a difference.

**Comment by prawalagarwal** [comment]
Can you use the platform installer task before your vstest task? Also after adding this task, please specify the source of VS as "Installed by tools installer" in the VsTest task.
I will look into why the task passed with that exception.

**Comment by prawalagarwal** [comment]
@jimmylewis Were you able try your scenario with the platform installer task?

**Comment by jimmylewis** [comment]
@prawalagarwal I've tried that, but now VSTest is crashing during test execution.  Samples:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2452408
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2452485

And another one was aborted when I added the InIsolation flag:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2454775

This one doesn't show any failing tests, but it's missing about 500 results and does have an abort message in the output.

I also enabled the Hydra.EnableApiFlow and it failed during execution but with a different error message:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2454935

I do vaguely recall some issues around using an older (pre-VS2019) version of VSTest with our test bed; I think there were some assembly load conflicts since we load a bunch of 16.0 VS assemblies, but it's been several months and I can't remember the details anymore.

**Comment by prawalagarwal** [comment]
@jimmylewis Please try only with Hydra.EnableApiFlow set as true. Now, with that set, are you facing the failure you reported always or is that intermittent. Can you post links to more builds where you face this?

Also please attach snapshots of your task inputs.

**Comment by prawalagarwal** [comment]
@jimmylewis any updates here?

**Comment by prawalagarwal** [comment]
Please reopen if you are still facing issues here.
