### ISSUE TITLE
AzureCLI@1 - "addSpnToEnvironment: true" exposes SP details in unusable form

### ISSUE THREAD

**Issue by jamesbannan** [Microsoft/azure-pipelines-tasks#9554]
## Environment
- Server - Azure Pipelines (YAML)
- Agent - Hosted: Ubuntu-16.04

## Issue Description

I'm deploying some Terraform configurations using Azure Pipelines (YAML) after having tested the functionality using pipelines built using the UI. 

In the UI task I used the "Azure CLI" task and selected "Access service principal details in script". This worked as expected and I was able to pass the values from the `servicePrincipalId` and `servicePrincipalKey` variables to the underlying script.

Using the same approach with YAML pipelines, I used the `AzureCLI@1` task and the `addSpnToEnvironment: true` option. The `servicePrincipalId` and `servicePrincipalKey` variables were present, but the values were obfuscated to `***`, which means that the underlying Terraform configuration failed as it couldn't authenticate. The `tenantId` variable was also obfuscated and unusable, although `subscriptionId` was fine.

Is accessing the service principal details in a usable form meant to be supported with YAML pipelines?

**Comment by jamesbannan** [comment]
Never mind - total user error **facepalm**

**Comment by constructdian** [comment]
@jamesbannan how did you solve this issue in the end? Having the same problems now of authenticating tf to azure on the pipeline and banging my head against a wall trying to find any form of documentation.

**Comment by jamesbannan** [comment]
@constructdian The values were obfuscated because that's what is meant to happen - Azure DevOps detects them as potentially sensitive and automatically obfuscates them. Underneath, the values are still present.

However, you can't expose those values to the task and have the `terraform` binary automatically pick them up and use them. From memory it's because the service connections are using a service principal and `terraform` authentication works a bit differently.

The workaround is to pass the service principal details out as environment variables within the script. `terraform` reads the environment variables and handles the authentication. Something like this:

```
# Get Azure account details
echo "==> Setting Subscription environment variables"
if [[ ! -z "${servicePrincipalId:-}" ]]; then
  SUBSCRIPTION_ID=$(az account show --query 'id' --output tsv)
  TENANT_ID=$(az account show --query 'tenantId' --output tsv)
  CLIENT_ID=${servicePrincipalId:-}
  CLIENT_SECRET=${servicePrincipalKey:-}
else
  SUBSCRIPTION_ID=
  TENANT_ID=
  CLIENT_ID=
  CLIENT_SECRET=
fi

# Define environment variables
export ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID:-$SUBSCRIPTION_ID} \
  ARM_TENANT_ID=${ARM_TENANT_ID:-$TENANT_ID} \
  ARM_CLIENT_ID=${ARM_CLIENT_ID:-$CLIENT_ID} \
  ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET:-$CLIENT_SECRET}

terraform init
```
Then the task definition looks something like:
```
- task: AzureCLI@1
  displayName: 'Initialise'
  inputs:
    azureSubscription: '<SUB_NAME>'
    scriptLocation: scriptPath
    scriptPath: scripts/tfInit.sh
    workingDirectory: terraform/prod
    arguments: '<SCRIPT_ARGS>'
    addSpnToEnvironment: true
    failOnStandardError: true
```
I've been using this approach in production with Azure DevOps and Terraform and it's all been working fine.
