### ISSUE TITLE
Can we copy files from $(System.DefaultWorkingDirectory) of Build server to a server (Microsoft Azure Virtual Machine(Iaas) ) using Agent Pool “Hosted VS2017”

### ISSUE THREAD

**Issue by raksharh** [Microsoft/azure-pipelines-tasks#9566]
## **Environment**
- **Server** - Microsoft Azure Virtual Machine(Iaas)
    
  
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
I am facing problem with "Windows Machine File Copy"

- **Agent** - Hosted or Private: Hosted VS 2017
    
   **Issue Description :** 
We are using CI/CD pipeline in OneITVSO. Earlier we had a private agent pool. Now we are asked to use "Hosted VS 2017". We have a Database solution, ETL solution and Tabular Model solution that needs to get deployed. Additionally we have certain scope scripts.

We are able to build the solution using "Hosted VS 2017". But we are not able to deploy using "Hosted VS 2017" In the release pipeline we have a task "Windows Machine File Copy" which copies either artifacts/dacpac/ispac/.sql files from build server to dev/uat servers.

Using the earlier agent pool this pipeline was getting deployed successfully. But now when we use "Hosted VS 2017" we are getting below error:

Failed to connect to the path \\DEVSERVERSQL01 with the user domain\servicecredentialdwd for copying. System error 53 has occurred.

1) Can "Hosted VS 2017" be used for task like "Windows Machine File Copy" (We are using Microsoft Azure Virtual Machine(Iaas) )

2) If we can use "Hosted VS 2017" even for Iaas Azure machines, are we missing any credential access. Should we give any access to domain\servicecredentialdwd for the agent pool "Hosted VS 2017". If so what permissions has to be given and how.

**Comment by mitchdenny** [comment]
This is because the hosted agent pool isn't on the corporate network and can't access those servers. If you want to copy files to those servers you have a few options.

1. Deploy an agent on the network and then copy the files.
2. Deploy an agent on the target machine and then move the files around with the Publish Pipeline Artifacts and Download Pipeline Artifacts tasks.

**Comment by BhanuPrasadMera** [comment]
I am also facing same issue, from above solutions, 

1. Deploy an agent on the network and then copy the files.
How can I deploy an agent on network(Where hosted agents are running) ?

2. Deploy an agent on the target machine and then move the files around with the Publish Pipeline Artifacts and Download Pipeline Artifacts tasks.
How can my target machine(of some X network) can communicate to Hosted Agent(of some Y network)?
