### ISSUE TITLE
ArchiveFilesV2: Hosted Ubuntu 1604 does not contain 7z

### ISSUE THREAD

**Issue by midgleyc** [Microsoft/azure-pipelines-tasks#9567]
## Environment
- Server - Azure Pipelines
- Agent - Hosted Ubuntu 1604

## Issue Description

Builds attempting to use ArchiveFilesV2 with type 7z on a Hosted Ubuntu 1604 agent fail with the error "Error: Failed which: Not found 7z: null". I can work around this by installing 7z first (with apt install p7zip-full, which installs version 9.20), but it would be nicer if I didn't have to do that (and could ensure that the version is the same on any OS).

**Comment by bryanmacfarlane** [comment]
The role of most of these tasks is to run build tools on the environment and not to override the environment.  For example, if you run in a container that brings the tools, it's counter.

The task behaved properly and pointed out that you want to run 7z but the system doesn't have it.

The correct solution is to have the tool installed that the task runs :)

**Comment by midgleyc** [comment]
Thanks @bryanmacfarlane, I guess the issue should be reported to whoever owns the setup of the Hosted Ubuntu 1604 agent -- I'd expect all the Microsoft tasks to work out of the box on the Microsoft-owned agents (perhaps that's a bad assumption!). Can you point me to where I can report this?

As a minor note, the error message could be improved to tell you that you should install the program before attempting to run the task -- for the current one I assumed it was simply a bug, instead of by design.

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/azure-pipelines-image-generation

Thanks
