### ISSUE TITLE
Publish Code Coverage - Cobertura xml to json fail

### ISSUE THREAD

**Issue by TclasenITVT** [Microsoft/azure-pipelines-tasks#9569]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
   16.131.28106.2

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
   OS: Windows 
   Version: 2.124.0
## Issue Description

Task: Publish Code Coverage Results  V1.131.0
```
2019-02-13T11:25:23.9253234Z ##[debug]Reading XML file: F:\agent\_work\218\s\x\x\cobertura\coverage.cobertura.xml
2019-02-13T11:25:23.9565719Z ##[debug]Converting XML file to JSON
2019-02-13T11:25:25.6128108Z ##[debug]task result: Failed
2019-02-13T11:25:25.6284549Z ##[error]No code coverage results were found to publish.
2019-02-13T11:25:25.6284549Z ##[debug]Processed: ##vso[task.issue type=error;]No code coverage results were found to publish.
2019-02-13T11:25:25.6284549Z ##[debug]Processed: ##vso[task.complete result=Failed;]No code coverage results were found to publish.
```
Is there a possibilty to get some kind of schema that this task expects for the Cobertura coverage xml to ensure the generated xml is valid? I am generating the code coverage using [altcover](https://github.com/SteveGilham/altcover). Another option would be to improve the error message for this build task. That enables it to display the inner error when converting the xml to json?

**Comment by nigurr** [comment]
@madhurig Can you please look into this?

**Comment by TclasenITVT** [comment]
I also opend an issue with altcover [here](https://github.com/SteveGilham/altcover/issues/55)

**Comment by jpenniman** [comment]
I had the same problem. I was able to get around it by running [ReportGenerator](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator&targetId=0aad53ee-656e-4277-bf35-96b531e37177) against the AtlCover Covertura output first, then uploading the output from ReportGenerator. This also gives you the html report to upload with it.

**Comment by madhurig** [comment]
Can you please provide a sample of output from AtlCover that did not work and the one that worked after running ReportGenerator?

**Comment by TclasenITVT** [comment]
Here are the two xmls: 
This is the altcover output: [coverage.cobertura.xml.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2900919/coverage.cobertura.xml.zip).
This is the one generated by ReportGenerator 
[Cobertura.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2900920/Cobertura.zip). There seem to be slight differences in the results. In the altcover xml the call is being reported not in the unit test but at the actual call site where as with the ReportGenerator it is shown as inside of the Test Module. This might be something that is configurable with ReportGenerator.

**Comment by SteveGilham** [comment]
The most obvious differences between the two files are 
1) AltCover is implicit in what DTD is follows (it is based on [the sample here](https://raw.githubusercontent.com/jenkinsci/cobertura-plugin/master/src/test/resources/hudson/plugins/cobertura/coverage-with-data.xml), which follows `http://cobertura.sourceforge.net/xml/coverage-03.dtd` ) 
2) The ReportGenerator output claims to follow the more recent `http://cobertura.sourceforge.net/xml/coverage-04.dtd`, but is invalid according to that schema -- the `method` elements lack a `complexity` attribute and they contain `line` elements directly, rather than nested inside a `lines` element.

**Comment by SteveGilham** [comment]
[Related issue opened with ReportGenerator](https://github.com/danielpalme/ReportGenerator/issues/219).

**Comment by danielpalme** [comment]
New release of ReportGenerator is available:
https://www.nuget.org/packages/ReportGenerator/4.0.15

**Comment by TclasenITVT** [comment]
@danielpalme  did this also create a new Version of the Build Task for the ReportGenerator TFS/Azure DevOps Task?

**Comment by danielpalme** [comment]
@TclasenITVT
Yes

**Comment by TclasenITVT** [comment]
After the update of AltCover to Version 5.1.666 the xml parsing works and as a result of that the task no longer fails uploading the code coverage result.
