### ISSUE TITLE
AzureCLIV1 -- show environment variable section in visual designer

### ISSUE THREAD

**Issue by midgleyc** [Microsoft/azure-pipelines-tasks#9570]
When I'm using YAML, I can provide an env: section for environment variables I'd like to have access to in my Azure CLI task. In the visual designer, there's no section for this. The Bash task has a section, and I'd like that in the Azure CLI task as well.

**Comment by bryanmacfarlane** [comment]
What's nice about this request is it's a great way to pass in secrets (rather than cli args which can get logged in some scenarios).

**Comment by bishal-pdMSFT** [comment]
Thanks to @midgleyc this is done.
