### ISSUE TITLE
NuGet Tool Installer task ( NuGetToolInstaller ) should only install blessed, if specific version isn't specified

### ISSUE THREAD

**Issue by devlead** [microsoft/azure-pipelines-tasks#9580]
Currently if I i.e. require `>=4.x` the “NuGet Tool Installer task” will filter out any NuGet version that isn't `EarlyAccessPreview` imho it should instead if a specific version isn't specified filter so it only takes the last `ReleasedAndBlessed` NuGet version in [tools.json](https://dist.nuget.org/tools.json), which is what NuGet considers latest recommended.

https://github.com/Microsoft/azure-pipelines-tasks/blob/7cdaf40d9e73e49d39d0e260c26a7a6f5886cf82/Tasks/Common/packaging-common/nuget/NuGetToolGetter.ts#L148

4.9.3 was released and blessed yesterday, but checking my build logs I've been using it for a while since it was released 2019-01-24, which IMHO isn't the desired behavior.

Reading NuGet docs ( https://docs.microsoft.com/en-us/nuget/api/tools-json ), confirms that

Stage              | Meaning
------------------ | ------
EarlyAccessPreview | Not yet visible on the [download web page](https://www.nuget.org/downloads) and should be validated by partners
Released           | Available on the download site but is not yet recommended for wide-spread consumption
ReleasedAndBlessed | Available on the download site and is recommended for consumption

**Comment by elbatk** [comment]
Hello! I'm a PM over on the Azure Artifacts team. I wanted to drop in here and address some of these issues with the news that we're currently reevaluating the types of tasks we offer in Azure Pipelines, and looking to focus more on lighter-weight tasks that cover authentication and setup. In lieu of the task redesign, we're going to forego making changes to the current tasks (with a few exceptions). We hope the new tasks we spin up in the next quarter or so are easier and more helpful, be on the lookout!

**Comment by OskarKlintrot** [comment]
@elbatk Will it solve this issue or is this issue a `wontfix`?
