### ISSUE TITLE
NPM authenticate should be able to create `.npmrc` if it doesn't exist.

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/azure-pipelines-tasks#9584]
Without the ability to do this, you force me to create a fairly arbitrary task just to make sure the file is there already.

![image](https://user-images.githubusercontent.com/115199/52797216-0bc25680-303b-11e9-96b5-1ee7ec0f3b9d.png)

**Comment by mitchdenny** [comment]
@zjrunner sounds like a reasonable request :)

**Comment by jotaylo** [comment]
It does sound like a reasonable request, however to add this feature it's not quite as straightforward as just creating the file. The task currently also looks at the existing .npmrc file, reads out the feeds, determines which ones are in the current organization, and then authenticates those.
If we extend the task to create a new .npmrc file, we'll need to add the ability to select feeds from the current organization.

**Comment by atrauzzi** [comment]
I'm not sure I understand how that would impact the simplicity of implementing the exact same thing I'm already doing with an extra task.

**Comment by atrauzzi** [comment]
Having some issues this morning with the NPM authenticate task, it seems as though you guys have altered its behaviour recently as one of my builds has now started failing without any change.
The assumption that an `.npmrc` file would already be in the project is a bad assumption to impose as this file ends up receiving sensitive information - both locally and on the build machine.  You're effectively encouraging people to check into source control a file that really has no business being in source control.

The only workaround for this imposed workflow is to add it and then `.gitignore` it, which then makes updating the file with new repositories in the future a very brittle process.

The NPM authenticate task should accept a selection of repositories to enable and then populate *or update an existing* `.npmrc` file at a sensible default location, or a customizable path for the job.

**Comment by jotaylo** [comment]
What issues are you seeing? I've got an open PR, but there haven't been any changes to the task in a few weeks.

In the next quarter we'll be concentrating on improving the auth experience in pipelines. We're starting those discussions soon, and I'll bring up your feedback - I agree with the proposal in your third paragraph.

**Comment by zjrunner** [comment]
@atrauzzi  - in addition to what Jovana said/asked, what sensitive information goes to the checked-in npmrc by default?  I've always seen the checked in npmrc used for uri and config, and creds go in %userprofile%\.npmrc.  Having base uri/config in source control does seem valuable and this auth-split is a pattern I see in many other protocols.  https://www.npmjs.com/package/vsts-npm-auth reads one and writes to another by default for example.  Curious if you just see people make mistakes a lot or if there is some default cred writing behavior out there.

**Comment by atrauzzi** [comment]
My concern isn't when people _do_ use `.npmrc`.  For the vast majority of JS projects though, there's no merit in having any kind of repository info in source control:

- Projects already identify their dependencies - including namespace - in `package.json`
- Mappings of credentials as well as any other behaviours are specific to the machine NPM is being run on, not globally across all checkouts of the repository
- Yeah, people are easily guided into making mistakes, this plugins current behaviour increases the likelihood of this
- Who wants to configure their repositories for every project they check out?  I stick an `.npmrc` with my repo auth in my home directory and move on
- The directory cascade that `.npmrc` supports implies that configuration _could_ (should) originate from multiple levels of the filesystem by way of the corresponding circumstances responsible for each directory level, ie:
  - Project, information necessary for all builds
  - _[ insert any number of company specific conventions not related to this discussion ]_
  - Machine, authentication and any adjustments for behaviour

It's premature to assume all projects will have an `.npmrc`.  Many projects are fine with defaults and if this plugin disagrees with that assumption, then people are being forced to over-engineer configuration where all defaults sufficed.

I might have said this first to save time, but the _tldr;_ is: The current behaviour conflates a build concern with a source control level concern.

**Comment by simonerlandsen** [comment]
In my team there non-windows devs that cannot use vsts-npm-auth -config for authenticating, and the proposed way to solve this by microsoft is to put personal credentials into the .npmrc file. This leads to us not being able to put this file in source control, but it then seams like there is no way to npm install from both the official public registry and a private one hosted in devops from a pipeline. Am I to understand that the only way to make this happen is to

**Comment by atrauzzi** [comment]
Not stale.

**Comment by atrauzzi** [comment]
Not stale.

**Comment by atrauzzi** [comment]
Not helpful.
