### ISSUE TITLE
Copy only modified compoenets using Windows machine file copy

### ISSUE THREAD

**Issue by steved0x** [microsoft/azure-pipelines-tasks#9586]
From @vinothkumarb4u in https://github.com/MicrosoftDocs/vsts-docs/issues/3340
======================================================

I have an requirement to copy only modified file from repository to target folder. is there any option to do this using windows machine file copy
ex
Source repo
a1.txt
b1.txt - Modified.
c1.txt

Target folder
Should have only b1.txt

**Comment by arjgupta** [comment]
Hi,  need more information on this issue regarding your scenario. do you mean that only the modified files should be copied over to the destination ( this means that files that are already existing in the destination remain that way ) OR the destination should have only the modified files ( i.e. the destination contains only the files deemed "modified" and no other files ) ? Currently windows machine file copy tries to synchronize the source and destination in the following way: let's say the source has a1.txt, b1.txt and c1.txt and destination also has the same set of files. Now if the file b1.txt is modified, then when the windows machine file copy task will execute, it will copy only b1.txt. Now the destination will contain a1.txt, b1.txt ( modified ), and c1.txt . Does this fit your scenario ?
