### ISSUE TITLE
.NET Core SDK Installer task Giving ""unable to get local issuer certificate"" error

### ISSUE THREAD

**Issue by anand5555** [microsoft/azure-pipelines-tasks#9587]
I am using a private Azure Devops Windows agent, and i am using .NET Core SDK Installer task to download  2.1.302 .net core version . I am getting ""unable to get local issuer certificate"" error. Below is the debug log  

![image](https://user-images.githubusercontent.com/31290069/52819396-33cfab00-3077-11e9-933a-88ae6af56b4e.png)

Can some one please help me ?

**Comment by samsta1128** [comment]
I am having the same issue did you ever resolve yours?

**Comment by anuragc617** [comment]
From the error, it seems like that the task is not able to get the issuer certificates on your machine when it tries to fetch the channel for the specified dotNet version. I think you can re-try by installing the issuer certificates on your machine.

**Comment by anuragc617** [comment]
Closing this, please re-open if have any comments.

**Comment by InteXX** [comment]
@anuragc617 

> I think you can re-try by installing the issuer certificates on your machine

How does one find those?
