### ISSUE TITLE
Feature request: Docker build - Support for multiple Dockerfile in one solution

### ISSUE THREAD

**Issue by craigwardman** [Microsoft/azure-pipelines-tasks#9592]
I would like to use the Docker Build task in a generic CI pipeline to create Docker images, however some of the multi-project solutions contain more than one Dockerfile.

At the moment the task uses minimatch syntax to identify the Dockerfile location(s), so it does find all files, but then it only returns and processes the first Dockerfile.

I would like to request that when multiple files are found then the code would iterate over them. It looks like this might impact image naming, so I guess this would need to take into account the name of each project which contained the Dockerfile.

**Comment by shashankbarsin** [comment]
@craigwardman [Docker task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#build-command) supports inputs to explicitly specify the Dockerfile path and build context. Multiple steps can be used in the job, where each Docker task explicitly specifies the Dockerfile and build context

**Comment by craigwardman** [comment]
@shashankbarsin I know this, but this isn't what I requested. What this means is that every time you add a docker file into a solution you have to modify the build steps. As a developer I don't want to have to worry about modifying the build script that should just work (in many cases developers don't have permissions to modify build steps so this means raising a ticket with devops).

Also the downstream effect of this is that every solution needs a custom build, rather than a general set of steps that describe how to build any solution.

**Comment by parksquare** [comment]
@shashankbarsin I completely endorse the view of @craigwardman on this. It's clearly a bug that the minimatch pattern could feasibly return multiple dockerfiles, but all but one are arbitrarily thrown away. Might look into how Jenkins handles this scenario.
