### ISSUE TITLE
AzureWebAppContainerV1: Can't select a slot to deploy

### ISSUE THREAD

**Issue by miiitch** [Microsoft/azure-pipelines-tasks#9597]
## Environment
- Azure Devops

## Issue Description
The "Deploy to slot" is checked but the form does not show any field to select a slot name nor a resource group.

![image](https://user-images.githubusercontent.com/2396269/52850865-e30e8f80-3114-11e9-8211-82dd90a3be7b.png)

**Comment by SumiranAgg** [comment]
Thanks for reporting the issue. The fix will be rolled out in next deployment i.e. next couple of weeks.
