### ISSUE TITLE
No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/azure-pipelines-tasks#9606]
## Environment
Azure Pipeline
https://microsoft.visualstudio.com/Xbox.Ambassadors/_releaseProgress?_a=release-environment-logs&releaseId=1086&environmentId=2711

- Agent - Hosted or Private: 
   
Hosted 2017

## Issue Description

Unable to get our SF cluster deployed.  We thought it might be transient but it keeps occuring.

Our service endopoint in VSTS is;
tcp://officeinsidersrnr-pre.westus2.cloudapp.azure.com:19000

https://microsoft.visualstudio.com/Xbox.Ambassadors/_release?definitionId=12&view=mine&_a=releases

No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.
The names of some imported commands from the module 'ServiceFabricHelpers' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Failed to contact Naming Service. Attempting to contact Failover Manager Service...
Failed to contact Failover Manager Service, Attempting to contact FMM...
A connection attempt failed because the connected party did not properly respond after a period of time, or established c

**Comment by jrmcdona** [comment]
still an issue.   The cluster up and running.  The cert is active.  At a total loss for what is going wrong here.

**Comment by bishal-pdMSFT** [comment]
@jrmcdona  are you able to connect to SF explorer using same certificate?
We need to ensure that Azure DevOps Pipelines agent is able to talk to SF cluster. Is the cluster behind a private network or a firewall?
Also, please ensure that the certificate is correct. You can verify that by installing same certificate on a local machine and then trying to connect to cluster using that cert. use PS command [Connect-ServiceFabricCluster](https://docs.microsoft.com/en-us/powershell/module/servicefabric/connect-servicefabriccluster?view=azureservicefabricps)

You can also try a private agent to rule out Hosted agent's line of sight to cluster.

Also, please send us the debug logs. You can generate debug logs by adding a variable named _system.debug_ with value _true_ to release and re-deploy it.

**Comment by jrmcdona** [comment]
@bishal-pdMSFT Yes I am able to connect via PowerShell and also able to deploy via Visual Studio.
See image:
![image](https://user-images.githubusercontent.com/4327773/52951570-be4e2e00-3347-11e9-95f3-387ed30a4a9a.png)


The certificate is the same and has not changed since we first deployed via Azure pipeline a few months ago.  The thumbprint in the pipeline logs is the same one I used in the powershell script.

Logs attached.

[ReleaseLogs_1097.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2875604/ReleaseLogs_1097.zip)


Thanks

.

**Comment by jrmcdona** [comment]
@bishal-pdMSFT yes, I can connect to Explorer.

![image](https://user-images.githubusercontent.com/4327773/52952165-657f9500-3349-11e9-8377-a14add82a024.png)

**Comment by bishal-pdMSFT** [comment]
@jrmcdona can you try running the release on same machine on which you ran PS command? This would eliminate the possibility of Hosted agent not able to see the cluster.

**Comment by jrmcdona** [comment]
@bishal-pdMSFT I am doing that.  I just tried one and it failed. 
https://microsoft.visualstudio.com/Xbox.Ambassadors/_releaseProgress?_a=release-pipeline-progress&releaseId=1097

**Comment by bishal-pdMSFT** [comment]
> @bishal-pdMSFT I am doing that. I just tried one and it failed.
> https://microsoft.visualstudio.com/Xbox.Ambassadors/_releaseProgress?_a=release-pipeline-progress&releaseId=1097

This release seems to have run on Hosted agent.

**Comment by bishal-pdMSFT** [comment]
Also, please ensure that the certificate content specified in the service endpoint is up to date. Your local machine might have a newer copy and hence connect would work.

**Comment by jrmcdona** [comment]
@bishal-pdMSFT how do I run the release on my machine?   You mean via Visual Studio?

**Comment by bishal-pdMSFT** [comment]
1. Install Azure Pipelines agent on your machine
2. configure the agent against your DevOps organization
  a. Specify a new agent pool
3. And then select that agent pool in the release definition.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#install

**Comment by bishal-pdMSFT** [comment]
@jrmcdona let me know if you were able to get successful release on your local agent

**Comment by jrmcdona** [comment]
@bishal-pdMSFT Turns out there was a needed IP addressing setting in Azure portal to allow VSTS to access the cluster.
