### ISSUE TITLE
DotNetCoreInstaller should setup DOTNET_MULTILEVEL_LOOKUP=0

### ISSUE THREAD

**Issue by weshaggard** [Microsoft/azure-pipelines-tasks#9608]
## Environment
- Server - Azure Pipelines
    
http://dev.azure.com/azure-sdk

- Agent - Hosted vs2017-win2016 queue
  
## Issue Description
On Windows dotnet cli tries to fallback to what is installed globally and if there are more things installed globally they might get picked-up and used instead of the version that was specified with DotNetCoreInstaller task. This causes issues when running tools and other things because they become too dependent on the state of the hosted agents. 

See https://dev.azure.com/azure-sdk/playground/_build/results?buildId=4865&_a=summary for a simple repo definition where I run dotnet --info with and without DOTNET_MULTILEVEL_LOOKUP=0.

Without:
```
dotnet --info
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\cd53d87f-e2e0-40d8-b52f-f3c356db5b2b.cmd""
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.4 [C:\Program Files\dotnet\sdk]
  1.1.5 [C:\Program Files\dotnet\sdk]
  1.1.7 [C:\Program Files\dotnet\sdk]
  1.1.8 [C:\Program Files\dotnet\sdk]
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

With DOTNET_MULTILEVEL_LOOKUP=0 set:

```
##[section]Starting: dotnet --info
==============================================================================
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.146.1
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
Generating script.
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\8b6344a6-f89c-4366-833e-fdeb5fefdc20.cmd""
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\hostedtoolcache\windows\dncs\2.1.503\x64\sdk\2.1.503\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  2.1.503 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\hostedtoolcache\windows\dncs\2.1.503\x64\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

So without setting this and if we run dotnet commands that are targeting different versions of .NET Runtime we get different sdk's and runtimes. 

Note this isn't an issue on the linux hosted agents because they don't have global dotnet sdk fallback locations. 

For reference we had to workaround this for our definition https://github.com/Azure/azure-sdk-for-net/pull/5254 by setting it ourselve whenever we call dotnet commands.

**Comment by bishal-pdMSFT** [comment]
@weshaggard I am trying to understand your scenario better.

> So without setting this and if we run dotnet commands that are targeting different versions of .NET Runtime we get different sdk's and runtimes.

Isn't that expected? Can you please elaborate how your expectation is different from the version picked.

If I understand correctly, dotnet.exe does a roll forward for SDK and runtime versions. So, if your command is targeting runtime 2.1, then dotnet will select runtime with latest patch of 2.1. This can come from the location installed using .Net Core tool installer task or can be from hosted agent's pre-installed dotnet location. But in either case, it will be a patch version difference and hence should not be a problem(given dotnet defines PATCH version as just bug fixes with no compat break).

For SDK, dotnet can decide to roll forward to next minor version(if present in hosted agent's pre-installed location) compared to the one installed by .Net Core tool installer task. This can be a problem, but since you are using tool installer task to install a specific version, you should also add global.json so that dotnet restricts to corresponding minor version only.

Does this sound good to you? or you think DOTNET_MULTILEVEL_LOOKUP is better option?

**Comment by weshaggard** [comment]
cc @AlexGhiondea  @mikeharder 

I fully understand the roll-forward semantics of the .NET SDK as well as the runtime, I was formally on the .NET Core team. In case you are interested there are some design docs on the roll-forward policy of the framework at 
https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md, which states that it will also roll-forward on minor version if the minor you are targeting isn't present (https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md#roll-forward-in-absence-of-candidate-fx). You can also find a similar design document at https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md.

The issue we were hitting is that we are running tests that are targeting 2.0.0 and so they are rolling forward to 2.1.7 on non-windows because they don't have the global SDK/runtimes installed but on windows it was running on 2.0.9 which is the latest patch for 2.0.x. That caused different behaviors which caused them to fail on one OS but not the other. 

The big issue here is that we get inconsistent behavior between OS's and machines depending on what is installed, and I think it is a good idea to help eliminate some of this variability across hosts by at least allowing an option to disable the lookup when specifying a version of the SDK during the  DotNetCoreInstaller task. Using a global.json file may help in some contexts for the sdk picking but it doesn't help at all for the runtime versions as that comes from the runtimeconfig.json file for each application you run and for better or worse we might not control all those applications where we can easily tweak those. I think the the DotNetCoreInstaller should enable folks to run on an isolated sdk and/or runtime, via DOTNET_MULTILEVEL_LOOKUP.

**Comment by bishal-pdMSFT** [comment]
Yes, to ensure consistency adding this looks like a good idea. We can expose this as an optional check-box(Disable multi level lookup) in the task. Default value will be false. User can check it to disable multi level look up.

I plan to pick this up in near future after completing current engagements. I will update when I start working on this.
In the meanwhile, we would be glad to accept PR contributions :)

**Comment by issacnitin** [comment]
@weshaggard We're still working on this, please be rest assured, we will update ASAP :)

**Comment by amaljg** [comment]
@weshaggard - The fix is already being rolled out and should reach all customers in the next 3 weeks.

**Comment by anuragc617** [comment]
Closing this as the fix has been rolled out in  V1 version of .Net core installer task.
