### ISSUE TITLE
Azure Government Pipeline: Azure App Service Deploy task issue

### ISSUE THREAD

**Issue by dskibin** [Microsoft/azure-pipelines-tasks#9612]
Azure App Service Deploy task pointed to https://{resourceName}.scm.azurewebsites.net 
but it should be pointed to https://{resourceName}.scm.azurewebsites.us

Is it possibe to change that setting somewhere?

**Comment by vincentdass** [comment]
@dskibin , Can you please share the debug logs to investigate the issue?
for debug logs, set variable `system.debug` to `true` and rerun the release.

**Comment by dskibin** [comment]
Hello @vincentdass 
Here is the log
[log_10_6.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2872314/log_10_6.zip)

But could you say if there is an option to change that URL in Pipeline/Task settings?

**Comment by vincentdass** [comment]
@dskibin , currently, there is no option to change the URL as we fetch the kudu URL by calling the ARM rest calls. Also, the KUDU url works fine for update deployment status. The problem seems to be with MSDEPLOY URL. Can you set a application setting: `WEBSITE_WEBDEPLOY_USE_SCM` to `false`, pause for a minute and retry the deployment?
[Reference](https://github.com/projectkudu/kudu/wiki/Configurable-settings#dont-use-the-scm-site-for-webdeploy)

**Comment by dskibin** [comment]
@vincentdass i have tried what you suggested but faced same issue (
Here is the log 
[log_10_7.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2872920/log_10_7.zip)

**Comment by vincentdass** [comment]
@dskibin , have u set the value directly in Azure App Service. 
I assume you provided the value in AzureDevOps task. Can you please go to App Service in Azure portal and update the application setttings.
![image](https://user-images.githubusercontent.com/20121508/53061601-1ae65000-34e4-11e9-81ff-70e7c6c5763a.png)
Once, the value is set, go to Overview page and download the publish profile.
![image](https://user-images.githubusercontent.com/20121508/53061660-49642b00-34e4-11e9-8b64-92b6c756fa90.png)
You can see that the `publishUrl` contains a new URL other than Kudu SCM.
Retry the deployment.
If the current deployment fails, please mail to us @ `RM_CUSTOMER_QUERIES at Microsoft dot com` with the latest logs.

**Comment by dskibin** [comment]
@vincentdass i did that change in Azure Gov portal and build failed all the same.
Here is the latest build log:
[log_10_9.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2885404/log_10_9.zip)

**Comment by vincentdass** [comment]
Closing the issue, as the case is trasnferred to App Service team.
