### ISSUE TITLE
How to protect the private key in service connection?

### ISSUE THREAD

**Issue by starlee822** [Microsoft/azure-pipelines-tasks#9626]
https://github.com/Microsoft/azure-pipelines-tasks/blob/d646e333781b35566b0f9ddb474bb3bdeb23de04/Tasks/SshV0/ssh.ts#L20

To use SSH task, the SSH service connection has to be created first, and the private key has to be saved in Azure DevOps. Besides setting up the proper permission to the connection and use strong password, what else I can do to protect the private key there? 

Thanks.

**Comment by bryanmacfarlane** [comment]
> Besides setting up the proper permission to the connection and use strong password

Permissions is how you secure it.  If given permissions for use, the pipeline that uses it has access to it.
