### ISSUE TITLE
Impossible to parametrise service connection in ARM Deployment Task

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/azure-pipelines-tasks#9627]
## Environment
- Server - Azure Pipelines

## Issue Description
Task name: ` Azure Resource Group Deployment`
Task version: `2.0`

I have a release pipeline where I want to release different stages to resource groups in different subscriptions. I want to have 1 template with the deployment steps.

Currently this is not possible to implement having the service connection name (the `Azure subscription` question) parametrized using something like `$(serviceConnectionName)`. When trying to fill that in, the `Location` field breaks.

![image](https://user-images.githubusercontent.com/3463496/53009086-013cfe00-343b-11e9-82bc-869cd82934c0.png)

**Comment by hansmbakker** [comment]
It turns out this is a wish since 2016 already.
See https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/17338603-allow-service-connections-to-be-parameterized-in-t, which is incorrectly closed by the VSTS team. It feels like they did not understand the original wish.

**Comment by bishal-pdMSFT** [comment]
> the `Location` field breaks.

@hansmbakker I do not see any issue in editing `Location` input. Please elaborate what you meant by this.

Regarding the issue of using parameters for Azure Subscription, this is not supported without using task groups. @shashban can you please guide how to report this?

**Comment by bishal-pdMSFT** [comment]
@hansmbakker any update on this?

**Comment by hansmbakker** [comment]
I meant that when you try to put a variable in the subscription field instead of selecting one from the dropdown, then the Location field stays empty (you cannot select anything anymore and the validation prevents you from saving).

W.r.t. task groups - is it possible to have different stages deploy to different subscriptions with them? Can they be templates?

**Comment by bishal-pdMSFT** [comment]
You can still manually fill up the Location input.

yes, you can expose the Azure subscription as a variable and use different values across stages. Also, exporting such stages as templates is possible.

**Comment by hansmbakker** [comment]
Is there any documentation on this? When I follow https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops then the Azure Subscription property does not show up as a variable that can be set.

**Comment by bishal-pdMSFT** [comment]
@shashban can you please look in to this issue?

**Comment by shashban** [comment]
@hansmbakker are you still blocked on this? Task groups is the way to go for this. Think of them as sub-templates with steps only.

**Comment by hansmbakker** [comment]
@shashban and @bishal-pdMSFT after trying more it works for me now. I'll close the issue. Thank you for the support!
