### ISSUE TITLE
Uploading Task Log File Fails to check for file existence in MsBuild task

### ISSUE THREAD

**Issue by tommcdon** [microsoft/azure-pipelines-tasks#9635]
The following if should test for file existence.  It currently only checks for a null string:

https://github.com/Microsoft/azure-pipelines-tasks/blob/1744ce883da1576bb0ecba7966d8970960a59c06/Tasks/Common/MSBuildHelpers/InvokeFunctions.ps1#L138

Without the fix the msbuild task fails with the following if the log file does not exist:
>##[error]Unable to process command '##vso[task.uploadfile]E:\A\_work\4441\s\uwp-setup\src\pkg\packaging\dir.proj.log' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk

**Comment by heaths** [comment]
The assumption was that if the `flp` parameter was set, the task set it. It didn't take into account someone might have already done that.

@tommcdon as a short term workaround, can you change the arguments passed to not use `flp` directly? You can enable verbose logging which will accomplish the same thing (so you don't have to set `System.Debug` to `true`).

**Comment by moswald** [comment]
Fixed by #9655.
