### ISSUE TITLE
[DotNetCoreCLIV2] Add testRunTitle option for dotnet test command

### ISSUE THREAD

**Issue by weshaggard** [microsoft/azure-pipelines-tasks#9637]
Today if you use the DotNetCoreCLI task to run tests and publish the results there isn't anyway to configure the testRunTitle. This is an option that is needed to distinguish the different test runs when using a matrix strategy to run the tests in multiple configuration like OS and/or framework versions.

Today the DotNETCoreCLI task always passes empty (https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L164) for the run title which means it gets a very generic title like `VSTest Test Run' for all the different configurations so there isn't any great way to distinguish where they were ran.

As a workaround we are going to try and disable the auto publishing and explicitly pass the logger options to the dotnet test command and then explicitly call the PublishTestResults task so we can set the testRunTitle.

**Comment by bishal-pdMSFT** [comment]
@cltshivash since this is in test command, can you please take a look?

**Comment by NenoLoje** [comment]
As the issue seems to have been fixed by a PR, it should be safe to close the issue.
