### ISSUE TITLE
ExtractFiles@1 failing with 7z files in Ubuntu host

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/azure-pipelines-tasks#9647]
## Environment
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Ubuntu.

## Issue Description

ExtractFiles@1 is failing with 7zip files on Ubuntu.
I'm not a Linux expert but, from a quick search it seems that the task is missing the required package to deal with 7zip files.

### Task logs

Creating destination folder: /home/vsts/work/_temp/repo
Extracting file: /home/vsts/work/_temp/chibios-svn-repo-origin.7z
Error: Failed which: Not found 7z: null
##[error]Failed which: Not found 7z: null
##[section]Finishing: Extracting ChibiOS repo

**Comment by joshmgross** [comment]
Hey @josesimoes, looks like you're correct. The Task only supports 7zip files for Windows agents, as the Ubuntu images do not have p7zip (the Linux port of 7zip) installed.

A workaround, for now, would be to use a script task to install p7zip and then use it to extract the files you need.
To do that, install the package (https://packages.ubuntu.com/trusty-updates/p7zip) with:
`sudo apt-get install p7zip`

I'll look into if we want to update this task to support the Ubuntu agents.

**Comment by joshmgross** [comment]
@josesimoes 7zip has been added to the Ubuntu images here: https://github.com/Microsoft/azure-pipelines-image-generation/pull/735

The updated hosted agent should be rolled out to your account in 1-3 weeks.
