### ISSUE TITLE
[Maven3] task ignores testRunTitle when publishing test results

### ISSUE THREAD

**Issue by weshaggard** [Microsoft/azure-pipelines-tasks#9651]
The Maven task documents and declares the testRunTitle but doesn't end up passing it through to the test results publish step. 

Instead of passing the testRunTitle through it is hard-coding the empty string for the parameter here https://github.com/Microsoft/azure-pipelines-tasks/blob/653ff8ae7fa53d35def0e59acfda10da32b62ad3/Tasks/MavenV3/maventask.ts#L342.

**Comment by joshmgross** [comment]
@weshaggard You're correct. I'll look into getting this fixed.

**Comment by joshmgross** [comment]
@weshaggard I've updated the Maven task to fix this issue here: https://github.com/Microsoft/azure-pipelines-tasks/pull/9663

Thanks for catching this, if you want the updated task then you can download and install the updated version to your project. It will roll out in a month or so otherwise.
