### ISSUE TITLE
Jenkins Queue Task queues the wrong job. 

### ISSUE THREAD

**Issue by gandhiprachi** [microsoft/azure-pipelines-tasks#9661]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines
    Server endpoint: jet-tfs.visualstudio.com
    Team: Jet

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Jet Shared pool

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
Here's a link to 2 separate builds 
1)https://jet-tfs.visualstudio.com/Jet/_build/results?buildId=143164
(shield-services-qa-build/2.0.47)
Jenkins Queue task was supposed to queue -https://jenkins2.jet.network/team-build/buildWithParameters/Shield/deploy/shield-services-deploy-qa?delay=0sec
But it actually ended up queueing 
https://jenkins2.jet.network/job/Batman%20Web/job/pullRequest/job/batmanweb-story-pr
There was another pipeline that triggered batmanweb-story-pr jenkins job at the same time as shield-services-qa ran
https://jet-tfs.visualstudio.com/Batman%20Web/_releaseProgress?_a=release-environment-logs&releaseId=15012&environmentId=53562

2) https://jet-tfs.visualstudio.com/Jet/_releaseProgress?_a=release-environment-logs&releaseId=914&environmentId=1662
(superman-trigger-jenkins2-qa-deploy/Release-19)
Jenkins queue task was supposed to queue - https://jenkins2.jet.network/Superman/Deploy-QA/superman-fsharp-deploy-qa-tier1-eastus2
But it actually ended up queueing - https://jenkins2.jet.network/job/Superman/job/Deploy-QA/job/superman-fsharp-deploy-qa-tier2-westus/
### Task logs
[log_10_143164.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2894892/log_10_143164.zip)
(Debug log with diagnostics attached)

**Comment by gandhiprachi** [comment]
This is a bit concerning as jenkins queue task triggers the wrong deployment and causes confusion/potential risk.

**Comment by joshmgross** [comment]
Hey @gandhiprachi, what are your inputs for the Jenkins Queue Task?

And have you checked out the docs for the task? https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/jenkins-queue-job?view=azure-devops

**Comment by gandhiprachi** [comment]
@joshmgross - we've been using jenkins queue task for a long time. It works fine for most cases. This bug is an edge case that happens when the task is triggered at the same time from 2 separate pipelines. Review the logs if possible.

**Comment by gandhiprachi** [comment]
<img width="1354" alt="screen shot 2019-02-22 at 11 57 01 am" src="https://user-images.githubusercontent.com/5641359/53257804-0eefbf00-3699-11e9-8d29-5ecbeca3fb3d.png">

**Comment by gandhiprachi** [comment]
@joshmgross  -attaching a screenshot of the task configuration.

**Comment by GuyBanay** [comment]
Any update on this issue?

**Comment by AlexandrKravchuk** [comment]
@gandhiprachi @GuyBanay Are you guys still having this issue?

**Comment by GuyBanay** [comment]
Hi,

Yes, sometimes

Thanks, Guy

בתאריך יום ג׳, 14 ביולי 2020, 12:52, מאת Alexandr Kravchuk ‏<
notifications@github.com>:

**Comment by alexander-smolyakov** [comment]
Hi, @gandhiprachi!

Could you please provide more details about the setup for Azure DevOps and Jenkins pipelines? I'm not able to investigate logs from https://jet-tfs.visualstudio.com/ since access needed. So it would be great if you manage to share some fresh logs from Azure DevOps and Jenkins as well.  

Also could you please try to use a delay in pipelines to test is this issue related to a race condition or not. You can just set a delay for one pipeline before execution to see if the task will be queued as expected. In Azure DevOps there the [delay task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=azure-devops) and in Jenkins you can use [sleep](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#sleep-sleep) option for pipelines.

**Comment by gandhiprachi** [comment]
@alexander-smolyakov  - i no longer work with these pipelines, sorry unable to provide any information at this time. Please resolve the ticket

**Comment by alexander-smolyakov** [comment]
@gandhiprachi thanks for the response! So closing it.
@GuyBanay could you please create a new ticket regarding this issue and provide information that I requested earlier?
