### ISSUE TITLE
TIA running tests when Total files changed = 0

### ISSUE THREAD

**Issue by strosu** [Microsoft/azure-pipelines-tasks#9665]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: build https://uipath.visualstudio.com/Orchestrator/_build/results?buildId=191788 

- Agent - Hosted or Private: 
        - If using private agent, provide the OS of the machine running the agent and the agent version: 

Agent.OS | Windows_NT
Agent.OSArchitecture | X64
Agent.OSVersion | 10.0.14393
Agent.Version | 2.147.1

## Issue Description
Although TIA detects no files were changed between the current build and the one it selected as baseline, it runs all the tests. Furthermore, we are also affected by the update tests results problem described here - https://github.com/Microsoft/azure-pipelines-tasks/issues/9553 . The behavior is the same, enabling TIA causes an extra section to be run for the task (Section 'Update test results' Starting) which fails 100% of the time.

Below some logs from the same Run tests step:

***************************** Section 'Get Files that were changed' Starting *****************************
Baseline build: https://uipath.visualstudio.com/167639a7-d810-4ef9-a1fb-d7ccf8337d78/_build/results?buildId=189231
Baseline build id = 189231
Total files changed = 0
***************************** Section 'Get Files that were changed' Ended ********************************

....
Total tests: 2379. Passed: 2272. Failed: 93. Skipped: 14.
Test Run Failed.
Test execution time: 1.0097 Hours

### Task logs

Can provide the logs via email. Still working on getting a build with debug=true, the last few tries resulted in the test task taking too long and getting cancelled. 

### Error logs

The error itself is from the update results section which crashes, but the tests shouldn't have been run in the first place (since TIA detected no difference between builds).

UnMatched Results found. Adding them to test run.376
Publishing test results to test run '1295658'.
TestResults To Publish 376, Test run id:1295658
Test results publishing 376, remaining: 0. Test run id: 1295658
Publishing test results to test run '1295658'.
TestResults To Publish 1000, Test run id:1295658
Test results publishing 1000, remaining: 0. Test run id: 1295658
***************************** Section 'Update test results' Ended ********************************

##[error]
Exception : Collection contains duplicate id: 101970

**Comment by prawalagarwal** [comment]
@strosu please attach the logs for us to analyze this further. What kind of tests are you running. As I indicated in the issue you tagged, the reporting behavior for data driven xunit and nunit tests is not guaranteed by vstest task today. Try setting Hydra.EnableApiFlow as true in your definition for a better experience.

**Comment by prawalagarwal** [comment]
@strosu Any updates here?

**Comment by strosu** [comment]
@prawalagarwal thanks for the reply, I'm attaching our logs below.
I'm testing it with EnableApiFlow and will update you on how it goes. 

[testLogs.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2915313/testLogs.zip)

**Comment by strosu** [comment]
@prawalagarwal the test task finishes with EnableApiFlow, however it still runs tests it shouldn't have: https://uipath.visualstudio.com/Orchestrator/_build/results?buildId=206978&view=ms.vss-test-web.build-test-results-tab

Again, with 0 files changed, it ran the previously failing tests (which is expected), but also a number of passing ones when it shouldn't have any reason to. 

Please let me know if you can't get the logs directly from the build I've linked and I can upload them here too. 

Thanks

**Comment by prawalagarwal** [comment]
@strosu I do not have access to view your build. Can you please attach the complete logs with system.debug set as true.

**Comment by prawalagarwal** [comment]
@strosu we are waiting for logs from your side here.

**Comment by prawalagarwal** [comment]
Please reopen if you are still facing issues here

**Comment by strosu** [comment]
@prawalagarwal sorry for the delay, was out for a few days. Attaching the logs from the test step and reopening. 

[TestLogs.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2960529/TestLogs.zip)

**Comment by strosu** [comment]
@prawalagarwal did you get the chance to look at the logs?

Thanks

**Comment by prawalagarwal** [comment]
@strosu Can we schedule a call for this? Your logs indicate that you have data driven XUnit tests. I need to check if the results are getting published correctly. I am available from 10AM to 9PM IST.

**Comment by prawalagarwal** [comment]
@strosu closing the issue as discussed on the call. Please reach out to me in case you need more assistance here.

**Comment by emiacepacIG** [comment]
Hi! It happened the same to me. What was the solution provided for you?
