### ISSUE TITLE
Getting error when running "bundle update --bundler" from "- task: Bash@3"

### ISSUE THREAD

**Issue by BoazWarshawsky** [Microsoft/azure-pipelines-tasks#9668]
## Environment
account name: b.warshawsky@applicaster.com
project: applicaster
build number: #20190222.2
link to build: https://dev.azure.com/applicaster/Android%20UI%20Testing/_build/results?buildId=24

- Agent - Hosted or Private: 
    Mac hosted 

## Issue Description
The actions I am doing before this line:
1. - task: NodeTool@0
2. Running the following commands inside `- task: Bash@3`:
- `brew install rbenv`
- `rbenv install 2.3.5`
- `rbenv local 2.3.5`
- `gem install bundler && rbenv rehash`

And than I run: `bundle update --bundler`, The error I see is:
`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`

Link to job, if it helps: https://dev.azure.com/applicaster/Android%20UI%20Testing/_build/results?buildId=24

### Task logs
[logs_24.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2894175/logs_24.zip)

### Error logs
`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`

**Comment by brkerr** [comment]
This github issue seems to be related: https://github.com/bundler/bundler/issues/4462

Can you try to run bundle update json?

**Comment by BoazWarshawsky** [comment]
I tried the following:
`bundle update json`
`gem install json -v '1.8.2'`
`gem install json -v '1.8.3'`

But nothing helped, when I tired installing 1.8.2 or 1.8.3 versions I got this error: 
`ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.6.0/gems/json-1.8.2/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190224-45468-f0jjsb.rb extconf.rb
creating Makefile`

When trying `bundle update json` I got this error:
`To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
	from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/local/lib/ruby/gems/2.6.0/bin/bundle:23:in `<main>'`
which is my original error

**Comment by BoazWarshawsky** [comment]
I tried installing the bundler 1.16.1 as found in the log, but the json install for 1.8.3 afters did not succeed with this error:
Building native extensions. This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.6.0/gems/json-1.8.3/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190224-45438-12l0rso.rb extconf.rb
creating Makefile

**Comment by BoazWarshawsky** [comment]
Problem solved by installing the gem manually `gem install json -v '1.8.3'`
and not with `bundle install` using Gemfile
