### ISSUE TITLE
Share Service Connections between projects

### ISSUE THREAD

**Issue by JoshLarkin** [microsoft/azure-pipelines-tasks#9673]
I am requesting a feature that will enable sharing service connections between projects.

**Comment by kilasuit** [comment]
Hey @JoshLarkin - Love this request although this isn't the correct place to put a feature request for Azure Pipelines but more for any issues with current pipeline tasks 

You can however raise this correctly via https://developercommunity.visualstudio.com/ as mentioned in the following blog post - https://devblogs.microsoft.com/devops/azure-devops-feature-suggestions/

**Comment by Lovakumar** [comment]
@JoshLarkin we are currently working sharing service connections feature and it will be available 3-4 months from now.

**Comment by JoshLarkin** [comment]
Sounds great.  Thanks for the information.

**Comment by JBrLloyd** [comment]
Hi @Lovakumar, any updates on this one?
Thanks!

**Comment by Lovakumar** [comment]
@JBrLloyd we are in the last leg of implementation. It will take another month to roll it out publicly. Having said that if you are ok to dogfood this feature, let me know your Azure DevOps account name so that we can enable early feature flag on your account.

**Comment by JBrLloyd** [comment]
@Lovakumar No worries, we'll wait for the feature to be public. Thank-you for the update though!

**Comment by JO3-W3B-D3V** [comment]
@Lovakumar thank the lord!

**Comment by PrPetrow** [comment]
@Lovakumar was this feature released? 

I expected to see it in Update 1 (https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019u1?view=azure-devops#rc2-release-date-july-23-2019) but there is nothing like this.

**Comment by Lovakumar** [comment]
@PrPetrow this feature isn't released in Update 1. We are still working on few UX designs and will wrap up it a month.

**Comment by PrPetrow** [comment]
@Lovakumar thanks for the update. Just one more question, is there going to be a new on-premise DevOps server release with this feature or it will firstly be released only for the cloud version.

**Comment by Lovakumar** [comment]
@PrPetrow Firstly it will be released in cloud version and based on the response in cloud version, we will enable it in next on-premise version. There won't be any specific on-premise release just for this one feature.

**Comment by merill** [comment]
@Lovakumar  I'm really, really, interested in this. I have had to write scripts to create duplicate service connections on each project and then it's a nightmare to update them when the keys expire. Can you please add me to the preview? My account name is teamtelstra

**Comment by abelal83** [comment]
I'd be happy to test this feature out. Please could you enable? My account is clarksonscloud.

**Comment by oleksabor** [comment]
@Lovakumar Please enable this feature on https://dev.azure.com quipu-cwnet account

**Comment by JO3-W3B-D3V** [comment]
@Lovakumar I don't suppose there's any update on this feature? I really look forward to using this feature since I'm working on quite the array of projects! 😃

**Comment by Lovakumar** [comment]
@omeshp can you please enable sharing (old ux) feature flag for accounts mentioned in previous comments.

**Comment by omeshp** [comment]
@Lovakumar Enabled the feature for quipu-cwnet, clarksonscloud and teamtelstra accounts.

**Comment by abelal83** [comment]
This is awesome guys. I honestly can't tell you how much work this will save us!

Is there any chance task groups can also be shared across projects?

**Comment by merill** [comment]
Legends. Thanks guys!!! 
Just tried it and love it! @Lovakumar  @omeshp

**Comment by manospasj** [comment]
@omeshp Can we please enable this for gastag account?

**Comment by Lovakumar** [comment]
@abelal83 task groups sharing is not in our backlog.

**Comment by JO3-W3B-D3V** [comment]
@Lovakumar out of curiosity, is there any chance that such a feature will end up on your backlog?

**Comment by abelal83** [comment]
Task group sharing would be fantastic. For builds it's not a big deal for us however, releases are a nightmare. We have standard set of release policies that must be followed, you can imagine the pain we go through updating all the releases across all projects. Please add task group sharing to your backlog!

**Comment by omeshp** [comment]
@manospasj Done.

**Comment by manospasj** [comment]
@omeshp @Lovakumar I just tried it and sharing works fine. Although, if you share a connection and then try to untick all shared projects from this connection, the connection itself gets deleted even from the original project that was created.

**Comment by Lovakumar** [comment]
> Task group sharing would be fantastic. For builds it's not a big deal for us however, releases are a nightmare. We have standard set of release policies that must be followed, you can imagine the pain we go through updating all the releases across all projects. Please add task group sharing to your backlog!

Adding @ashokirla @shashban to track this feature request.

**Comment by Lovakumar** [comment]
> @omeshp @Lovakumar I just tried it and sharing works fine. Although, if you share a connection and then try to untick all shared projects from this connection, the connection itself gets deleted even from the original project that was created.

@omeshp can you please take a look at it. This looks to be serious bug.

**Comment by MarwaMBK** [comment]
@omeshp  Can we please enable this for sdxcloud account ?

**Comment by dusan-suchon** [comment]
Is there any update? When could we have service connection sharing feature available? Thanks

**Comment by shashban** [comment]
@ashokirla Can you please do the needful?

**Comment by qmalexander** [comment]
Hi, What is the status?

Br
Alexander

**Comment by sameera** [comment]
@Lovakumar @ashokirla Guys anyway to get this feature enabled without posting our corporate account here publicly? :)

**Comment by bluesourceTC** [comment]
@omeshp can you please enable for account wmsand?

**Comment by mmikkelson** [comment]
@omeshp can you please enable for account wmsand?

**Comment by shashban** [comment]
@ashokirla Please confirm if this open for a private preview

**Comment by ashokirla** [comment]
We have completed service connection sharing work and are doing some fit and finish. We can now enable private preview of this feature. Please share your organization details so that we can enable this feature. 
@mmikkelson : Sure we will enable this feature for your account 'wmsand'.

**Comment by iashishmittal** [comment]
Sharing service endpoint feature is now enabled in 'wmsand' account

**Comment by sameera** [comment]
@ashokirla Please enable this for `cloudextend` account

**Comment by MarwaMBK** [comment]
@ashokirla   Can you please enable this for sdxcloud account ?

**Comment by al-alison** [comment]
@ashokirla Can you please enable for organization "Edenred-ITECAmericas" ?

**Comment by TheAzureGuy007** [comment]
@ashokirla Can you please enable the private preview for this organization "dev.azure.com/unipertestaccount" as well and also let us know its been few months. When we can get this feature publicly available?

**Comment by samirageb** [comment]
@ashokirla can you please enable for `golightstream` account?

**Comment by JeromeVigne** [comment]
Can you add sbd-agora-ipaas organization please?

**Comment by slavizh** [comment]
@ashokirla can you enable this feature on org SentiaMGMT ?

**Comment by ramu20061992** [comment]
@ashokirla could you please enable this feature on org transport-logistics?

**Comment by Silthus** [comment]
Can you please also enable this feature on `interhyptest`?
Thanks!

**Comment by GabrielaLiviero** [comment]
Can you please also enable this feature on Vueling organization? Thank you!!

**Comment by nlopez59** [comment]
Can you please grant me access to the feature too.  https://dev.azure.com/Azure-Repo-DBB/

**Comment by rafagsiqueira** [comment]
Can you please enable this feature on `olatreaties`?

**Comment by JoshLarkin** [comment]
@ashokirla Can you please enable this feature on exscribedev

**Comment by alex75it** [comment]
@ashokirla Can you please enable this feature for account ``alex75`` ? Thanks

**Comment by naile** [comment]
We're super interested in this @ashokirla could you enable this feature for `cint`? Many thanks!

**Comment by sgopishetty-fisv** [comment]
> We have completed service connection sharing work and are doing some fit and finish. We can now enable private preview of this feature. Please share your organization details so that we can enable this feature.
> @mmikkelson : Sure we will enable this feature for your account 'wmsand'.

Can you enable this feature to  "fiservcards" organization

**Comment by IanBFarrell** [comment]
@ashokirla Do you have any update on when this feature will be available publicly?

**Comment by adamsmithkld** [comment]
@omeshp @ashokirla can you enable this feature for krolldiscovery organization as well?

**Comment by amullerhso** [comment]
@mmikkelson please enable this feature for 'hint-demo' as well

**Comment by mparsons79** [comment]
@omeshp please can you enable this feature for metatec-uk and HanleySolutions please? Connection sharing would be awesome.

**Comment by DarinMacRae** [comment]
@ashokirla Please enable this feature for the acmeaom organization. TIA.

**Comment by sameera** [comment]
Has anyone received this feature after Dec 17th? :(

**Comment by ashokirla** [comment]
Hi everyone,

First of all apologies for the delayed response. And thanks a lot for showing interest in this feature. 
For a while this feature has been in private preview mode as there are few enhancements to the permission model and we would like to get some feedback on it. We got great feedback and have incorporated that into the feature. We are shipping this feature next sprint (in 3 weeks).

Just in case, based on your requests, I will enable this feature for the below accounts. Please let me know if I missed anyone.
cloudextend,
sdxcloud,
Edenred-ITECAmericas,
unipertestaccount,
golightstream,
sbd-agora-ipaas,
SentiaMGMT,
transport-logistics,
interhyptest,
Vueling,
Azure-Repo-DBB,
olatreaties,
alex75,
cint,
fiservcards,
krolldiscovery,
hint-demo,
metatec-uk,
HanleySolutions,
acmeaom

@iashishmittal to enable them.

**Comment by JoshLarkin** [comment]
Please include exscribedev

Thanks,

Josh Larkin

[cid:image001.png@01D5FD0E.F8828350]

Clinton J Larkin • Chief Technology Officer
Exscribe, Inc. 5 W. Fourth Street Bethlehem, PA 18015
Phone 610-419-2050<tel:610-419-2050> Ext 704 • Fax 610-419-1055<tel:610-419-1055>
[cid:image002.png@01D5FD0E.F8828350]<http://www.exscribe.com/>[cid:image003.png@01D5FD0E.F8828350]<https://twitter.com/ExscribeEHR>[cid:image004.png@01D5FD0E.F8828350]<https://www.linkedin.com/company/135911>[cid:image007.png@01D5FD0E.F8828350]<https://www.facebook.com/exscribe/>

**Comment by fortunacio** [comment]
@ashokirla  can you enable this feature for wololoci organization as well?

**Comment by ams0** [comment]
can you please enable it for `gk-prox` and `cookingwithazure` @ashokirla ? Thanks!

**Comment by iashishmittal** [comment]
Enabled sharing of service connections for following account:

cloudextend
sdxcloud
Edenred-ITECAmericas
unipertestaccount
golightstream
sbd-agora-ipaas
transport-logistics
interhyptest
Vueling
Azure-Repo-DBB
olatreaties
alex75
cint
fiservcards
krolldiscovery
hint-demo
metatec-uk
HanleySolutions
acmeaom
wololoci
gk-prox
cookingwithazure
exscribedev

@slavizh  Cannot find account SentiaMGMT so it is not enabled for it. Can you please check if the name of account is correct?

**Comment by fortunacio** [comment]
@slavizh I see that wololoci is on the list, but... where is the option to share the connection? also, I can't update isShared property via REST.

**Comment by slavizh** [comment]
@iashishmittal name was changed. We have done other workaround for now so I do not need the feature right away.

**Comment by iashishmittal** [comment]
> @slavizh I see that wololoci is on the list, but... where is the option to share the connection? also, I can't update isShared property via REST.

Please go through following documentation for understanding how to share service connections
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#project-permissions---cross-project-sharing-of-service-connections


IsShared is a read only property which cannot be updated. It is set to true by server when service connection is shared otherwise it is set to false.

**Comment by bambuca** [comment]
Can you please enable shared connections to linksoftcz?

**Comment by allanmoller** [comment]
Can you please enable shared connections on allanmoller79 ?

**Comment by hermanho** [comment]
Can you please enable for organization "o365laio" ?

**Comment by iashishmittal** [comment]
enabled sharing of service connection for linksoftcz, allanmoller79, o365laio account

**Comment by mparsons79** [comment]
> Enabled sharing of service connections for following account:
> 
> cloudextend
> sdxcloud
> Edenred-ITECAmericas
> unipertestaccount
> golightstream
> sbd-agora-ipaas
> transport-logistics
> interhyptest
> Vueling
> Azure-Repo-DBB
> olatreaties
> alex75
> cint
> fiservcards
> krolldiscovery
> hint-demo
> metatec-uk
> HanleySolutions
> acmeaom
> wololoci
> gk-prox
> cookingwithazure
> exscribedev
> 
> @slavizh Cannot find account SentiaMGMT so it is not enabled for it. Can you please check if the name of account is correct?

Thanks. This feature is great and saving lots of time.

**Comment by manishkungwani** [comment]
@iashishmittal Hi, can you please enable this feature for https://dev.azure.com/bloomcs.

**Comment by felipematheus** [comment]
Hello, can you please enable this feature on organization bi-solucoes.

**Comment by iamNoah1** [comment]
Hello, I would also like to have the feature enabled for https://dev.azure.com/dataonegmbh. Thx a lot :)

**Comment by iashishmittal** [comment]
enabled sharing of service connection for bi-solucoes, bloomcs, dataonegmbh account

**Comment by ebunassar** [comment]
Jumping in to request this for https://dev.azure.com/kssdevops if possible. Also, any word on when this will be GA? Thanks in advance!

**Comment by iashishmittal** [comment]
Enabled sharing of service connections for https://dev.azure.com/kssdevops
We are planning to roll it out as GA soon. 
As due to COVID our deployments are also affected so cannot provide a good estimate.

**Comment by nmb88** [comment]
Sounds like COVID's caused the GA release to be delayed.  Could you enable this for https://dev/azure.com/dspartners?

**Comment by gahujipo** [comment]
Please enable this feature for organization ```acsdatasystems``` as well. Thank you in advance.

**Comment by ScottMcF-OneMTC** [comment]
please enable this for - dev.azure.com/onemtc.  Thanks

**Comment by iashishmittal** [comment]
Enabled sharing of service connections for dspartners, acsdatasystems, onemtc

**Comment by smkanadl** [comment]
Being very interested to try it out. Can you please enable it for dev.azure.com/acvt?

**Comment by iashishmittal** [comment]
Enabled sharing of service connections for acvt

**Comment by yashwanthmb** [comment]
Can you please enable it for **odjfs**

**Comment by iashishmittal** [comment]
Enabled sharing of service connections for odjfs

**Comment by stealthcold** [comment]
Hi, please enabled it for Escribainformatica

**Comment by dmglennie-diveplane** [comment]
please enable for diveplane

**Comment by iashishmittal** [comment]
sharing of service connections is enabled for Escribainformatica, diveplane

**Comment by Ivan-L** [comment]
hi @iashishmittal, please would you enable it for outsurance

**Comment by JaneTeichmann** [comment]
H, Could you please enable the feature to dev.azure.com/localiza?

**Comment by boxrick** [comment]
Good afternoon, please can you enable this for gregorypennington org.

**Comment by iashishmittal** [comment]
Sharing service connection is now GA and available to all ADO customers.
Following doc contains all information related to service connection new experience
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml

**Comment by krispenner** [comment]
This is great, just searched to see if this was possible - perfect timing :)

I'd prefer the project name not be appended onto the shared service connection name, curious why you chose to do that as there would be no naming conflict to not append it. Just shared 3 service connections across 50 projects and then spent an hour opening every single project and editing each shared service connection to rename them by removing the suffix that is forced on the name. Maybe when sharing there could be an option to specify the name to avoid such a tedious process afterwards?

Otherwise, super awesome! Thank you!

**Comment by GeromeRen** [comment]
is it possible to share a service connection between different organizations for now?

**Comment by krispenner** [comment]
@iashishmittal 
Do you know why it requires `roleassignments/write` access on the Azure subscription to rename a shared service connection? The user is the Project Administrator for the DevOps project, yet they are unable to rename the shared service connection that is shared with their project.

**Comment by vkorrapa** [comment]
Hi @iashishmittal,  can you please enable this in steelcase account.

**Comment by ashokirla** [comment]
Service connections sharing is now public.

**Comment by alokpatra** [comment]
@iashishmittal
Is this feature enabled for on-premise as well? 
Am using Azure DevOps Server Version 17.143.28912.1

**Comment by yxl5521** [comment]
@iashishmittal 
HI, Could you please enable the feature to DeltaITAppDevTeam

**Comment by JeeDay** [comment]
Hi @Lovakumar please enable this feature on https://dev.azure.com/siapep-france account

**Comment by apsyio** [comment]
Please enable for https://dev.azure.com/apsyap, thanks!

**Comment by rajeshkandati** [comment]
Hi @iashishmittal, Could you please enable the feature to dev.azure.com/CRM2CRM ?

**Comment by rajeshkandati** [comment]
Hi @Lovakumar, Could you please enable the feature to dev.azure.com/CRM2CRM

**Comment by logicatwork** [comment]
> Hi @Lovakumar, Could you please enable the feature to dev.azure.com/CRM2CRM

This feature is now public and you do not have to request it to be turned on.

**Comment by rajeshkandati** [comment]
@logicatwork can you please point me to the right documentation? Appreciate your response.

**Comment by logicatwork** [comment]
> @logicatwork can you please point me to the right documentation? Appreciate your response.

https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#organization-level-permissions

**Comment by rajeshkandati** [comment]
> > @logicatwork can you please point me to the right documentation? Appreciate your response.
> 
> https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#organization-level-permissions

Thank you.

**Comment by shashban** [comment]
Closing this issue as the capability is publicly available
