### ISSUE TITLE
Issue with compilers with Python 2.7 and 3.4

### ISSUE THREAD

**Issue by astrofrog** [Microsoft/azure-pipelines-tasks#9674]
When using:

```yaml
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 2.7
```

or

```yaml
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.4
```

I get errors regarding missing C++ compilers when trying to install Python packages with C extensions. An example configuration for installing a package is

```yaml
  - script: pip install numpy --no-binary :all:
    displayName: Installing numpy
```

The error is:

```yaml
...
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\fast_histogram
    copying fast_histogram\histogram.py -> build\lib.win-amd64-2.7\fast_histogram
    copying fast_histogram\__init__.py -> build\lib.win-amd64-2.7\fast_histogram
    creating build\lib.win-amd64-2.7\fast_histogram\tests
    copying fast_histogram\tests\test_histogram.py -> build\lib.win-amd64-2.7\fast_histogram\tests
    copying fast_histogram\tests\__init__.py -> build\lib.win-amd64-2.7\fast_histogram\tests
    running build_ext
    building 'fast_histogram._histogram_core' extension
    error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

for Python 2.7 and:

```yaml
...
    creating build
    creating build\src.win-amd64-3.4
    creating build\src.win-amd64-3.4\numpy
    creating build\src.win-amd64-3.4\numpy\distutils
    building library "npymath" sources
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).
```

for Python 3.4. 

I feel that this should probably work out of the box as part of the ``usePythonVersion`` task, or at least that there should be information on how to get this to work (maybe an 'inputs' option to the ``usePythonVersion`` task)

**Comment by brcrista** [comment]
Those are some rather old C++ compiler versions, so they aren't installed on the hosted build VMs.  If you need them, you should be able to install them as part of the build.

Python packages can run arbitrary build steps, so the task can't anticipate all the dependencies you would need to build a package from source (sdist).

May I ask why you need to use `--no-binary`?  The precompiled wheel for numpy won't have this problem.

**Comment by astrofrog** [comment]
@brcrista - I was using ``--no-binary`` to demonstrate the issue in a minimal way, but my actual use case is that I am trying to actually build wheels for some of my packages on Azure.

What is the best way to install these compilers?

**Comment by brcrista** [comment]
Ah, got it 😊

3.4 is really old; most libraries have already dropped support.  If you really want to build with it, I would recommend running a [self-hosted build agent](https://docs.microsoft.com/azure/devops/pipelines/agents/v2-windows).  Then you can install whatever software you need.

For 2.7, you can `choco install vcpython27`

**Comment by asottile** [comment]
It would be really nice if vcpython27 were installed by default.  It should mostly stay out of the way of the other compilers

**Comment by brcrista** [comment]
I think you're right @asottile.  I discussed this with @vtbassmatt and we agreed it should probably be there by default.

**Comment by brcrista** [comment]
Opened https://github.com/Microsoft/azure-pipelines-image-generation/issues/793 to track this
