### ISSUE TITLE
Default source used for Nuget restore cannot restore packages using SemVer v2.0

### ISSUE THREAD

**Issue by jimmylewis** [Microsoft/azure-pipelines-tasks#9675]
## Issue Description

Default Nuget restore settings cannot find SemVer v2.0 packages hosted on Nuget.org.  (Note: it is using https://www.nuget.org/api/v2/ as a source).

I can work around this issue by using a Nuget.config file with the v3 feed as a source: https://api.nuget.org/v3/index.json.  I'm not sure if fixing this is as simple as just changing the default source to the v3 API instead.

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

https://jamlew.visualstudio.com/AppBuilding/_build/results?buildId=223

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows 2012 R2, agent version: 2.147.1

### Task logs

[log_7_223.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2897380/log_7_223.zip)

### Error logs

>NU1101: Unable to find package Microsoft.AspNetCore.Components.Browser. No packages exist with this id in source(s): NuGetOrg
>NU1101: Unable to find package Microsoft.AspNetCore.Components.Browser. No packages exist with this id in source(s): NuGetOrg
>NU1102: Unable to find package Microsoft.AspNetCore.JsonPatch with version (>= 3.0.0-preview-19075-0444)
>  - Found 19 version(s) in NuGetOrg [ Nearest version: 2.2.0 ]
>NU1102: Unable to find package Microsoft.AspNetCore.NodeServices with version (>= 3.0.0-preview-19075-0444)
>  - Found 42 version(s) in NuGetOrg [ Nearest version: 2.2.0 ]
>NU1101: Unable to find package Microsoft.AspNetCore.Components.Browser. No packages exist with this id in source(s): NuGetOrg
>NU1102: Unable to find package Microsoft.AspNetCore.JsonPatch with version (>= 3.0.0-preview-19075-0444)
>  - Found 19 version(s) in NuGetOrg [ Nearest version: 2.2.0 ]
>NU1102: Unable to find package Microsoft.AspNetCore.NodeServices with version (>= 3.0.0-preview-19075-0444)
>  - Found 42 version(s) in NuGetOrg [ Nearest version: 2.2.0 ]

etc.

**Comment by zjrunner** [comment]
@jimmylewis - looks like this has been fixed (due to this thread or otherwise) here: #9473.  I've seen it behave as you expect (using a v3 url) in a test account, the 148 version of the task hasn't made it to your account yet but should be there within the next several days.  thanks for logging this.
