### ISSUE TITLE
AzureCLI does not preserve variable name case

### ISSUE THREAD

**Issue by andreacassioli** [Microsoft/azure-pipelines-tasks#9687]
I am setting up a build pipeline in AzureDevOps. That pipeline has an AzureCLI task that uses a  pipeline variable  say `apiKey`. The variable name (the content of the variable is irrelevant here), is in `camel style`.

When the AzureCLI script runs as bash, it actually uses an upper case version of the variable name, i.e. `APIKEY`. This breaks some of my commands and scripts, as bash considers variable names to be case sensitive!

**Comment by bishal-pdMSFT** [comment]
The task sets an environment variable using upper case. i.e. it will set `APIKEY` as environment variable. But if you use the variable with `$(apiKey)` notation (and pass it to your script as an argument if needed), it would work fine.
Would you elaborate how you are using the variable in the task?

**Comment by andreacassioli** [comment]
Hi, I run Terraform in AzureCLI task, and I use env variables to pass some configuration to Terraform. Terraform attempts to fill unspecified configuration from the environment variables:

https://www.terraform.io/docs/configuration/variables.html#environment-variables

So I have to make sure that the case is correct. I can fix on my side fiddling with my scripts of course.

In general, as I run in bash, it seems quite confusing that the case of the pipeline variable is not preserved. At least there should be a clear warning somewhere.

**Comment by bishal-pdMSFT** [comment]
@andreacassioli Would it help if you use command line variables to pass arguments to Terraform rather than depend on environment variables implicitly. 
https://www.terraform.io/docs/configuration/variables.html#variables-on-the-command-line

**Comment by andreacassioli** [comment]
@bishal-pdMSFT of course I could. But I use a Makefile and I do not want to change it every time I add or remove a variable! Moreover, there is a limit on the number of vars you can pass as argument.

Anyway, my point is that a bash user would expect the case of a variable should to be preserved. The current behaviour is misleading. If you can not for whatever reason, please make it clear!

**Comment by bishal-pdMSFT** [comment]
This behavior is not defined by Azure CLI task. This is how the azure pipelines agent sets the environment variables and executes task. 
@chrisrpatterson @bryanmacfarlane would you like to comment on this behavior? - the build/release pipeline variables are set in Upper case environment variables.

**Comment by bishal-pdMSFT** [comment]
ping @bryanmacfarlane @chrisrpatterson

**Comment by bishal-pdMSFT** [comment]
@andreacassioli there is already a closed [issue](https://github.com/Microsoft/azure-pipelines-agent/issues/1645) in pipelines agent repo which explains the behavior. If you do not agree with the explanation, you can re-open that issue.
I am closing current issue as it is not related to task.
