### ISSUE TITLE
.NET SDK Installer Task fails to find SDK 1.1.12 download due to schema difference in releases.json

### ISSUE THREAD

**Issue by martinstenhoff** [Microsoft/azure-pipelines-tasks#9689]
## Environment
- Server - Azure Pipelines
   
- Agent - Hosted

## Issue Description

The .NET SDK Installer task fails to find the download link for SDK 1.1.12 due to releases.json having different node name for the sdk for this version.

If I compare with what's being downloaded if I specify version 2.2.104 then it seems the installer task is looking for the following entry in the [releases.json](https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json)
"**sdk-win-x64**": "https://download.visualstudio.microsoft.com/download/pr/e7a3e196-1b15-45d4-8a4a-2f940cf8c3be/975a1ec833505505adf5b867990d441a/dotnet-sdk-2.2.104-win-x64.zip",

However for version 1.1.12 there is no **sdk-win-x64**, instead it seems like the SDK Zip file is available in
"**dotnet-dev-win-x64.zip**": "https://download.visualstudio.microsoft.com/download/pr/cdb1d5fc-5bfb-466e-8339-226d57b3d111/3d29a36420acfd92990f5caec5371395/dotnet-dev-win-x64.1.1.12.zip",

### Error logs

_The specified version's download links are not correctly formed in the supported versions document => https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json_

**Comment by bishal-pdMSFT** [comment]
This has been fixed in the referenced issue and I can install 1.1.12 version successfully: 

> 2019-02-28T09:01:26.2334874Z ##[section]Starting: Use .NET Core sdk 1.1.12
> 2019-02-28T09:01:26.2612908Z ==============================================================================
> 2019-02-28T09:01:26.2613073Z Task         : .NET Core SDK Installer
> 2019-02-28T09:01:26.2613117Z Description  : Acquires a specific version of the .NET Core SDK from internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
> 2019-02-28T09:01:26.2613164Z Version      : 0.2.2
> 2019-02-28T09:01:26.2613227Z Author       : Microsoft Corporation
> 2019-02-28T09:01:26.2613275Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=853651)
> 2019-02-28T09:01:26.2613342Z ==============================================================================
> 2019-02-28T09:01:27.5127357Z Tool to install: .NET Core sdk version 1.1.12.
> 2019-02-28T09:01:27.5649773Z [command]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6\0.2.2\externals\get-os-platform.ps1'"
> 2019-02-28T09:01:28.8322488Z Primary:win-x64
> 2019-02-28T09:01:28.8350826Z Detected platform (Primary): win-x64
> 2019-02-28T09:01:28.8351394Z Checking if a cached copy exists for this version...
> 2019-02-28T09:01:28.8353571Z The cache does not contain the requested version of .NET Core. Downloading and installing it now.
> 2019-02-28T09:01:28.8353868Z Getting URL to download .NET Core sdk version: 1.1.12.
> 2019-02-28T09:01:29.5317612Z Downloading: https://download.visualstudio.microsoft.com/download/pr/cdb1d5fc-5bfb-466e-8339-226d57b3d111/3d29a36420acfd92990f5caec5371395/dotnet-dev-win-x64.1.1.12.zip
> 2019-02-28T09:01:52.5403080Z Extracting downloaded package D:\a\_temp\375ab9a5-084f-44ed-a9d7-8039c85fec5c.
> 2019-02-28T09:01:52.5410348Z Extracting archive
> 2019-02-28T09:01:52.5530592Z [command]C:\windows\system32\chcp.com 65001
> 2019-02-28T09:01:52.6976385Z Active code page: 65001
> 2019-02-28T09:01:52.7273215Z [command]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\375ab9a5-084f-44ed-a9d7-8039c85fec5c', 'D:\a\_temp\30a7676c-d913-4ba7-9b8d-1a0cb59cd677')"
> 2019-02-28T09:01:59.3971351Z Caching this installed tool.
> 2019-02-28T09:01:59.3971524Z Caching tool: dncs 1.1.12 x64
> 2019-02-28T09:02:19.1103700Z Successfully installed .NET Core sdk version 1.1.12.
> 2019-02-28T09:02:19.1107318Z Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\dncs\1.1.12\x64
> 2019-02-28T09:02:19.1117853Z Creating global tool path and pre-prending to PATH.
> 2019-02-28T09:02:19.1217446Z Prepending PATH environment variable with directory: C:\Users\VssAdministrator\.dotnet\tools
> 2019-02-28T09:02:19.1428585Z ##[section]Finishing: Use .NET Core sdk 1.1.12
