### ISSUE TITLE
PowerShell on Target Machines task failed to connect to Windows IoT Core on RPi3

### ISSUE THREAD

**Issue by philipktlin** [Microsoft/azure-pipelines-tasks#9702]
## Environment
Have a local machine "iotedge-win4" running VSTS agent; which can create remote PS session to a RPi3 "iotedge-pi-win1" running Windows IoT Core.

For "iotedge-win4", Windows OS version is 10.0.17763 N/A Build 17763 and vsts agent version is 2.146.0.

## Issue Description

[Include task name(s), screenshots and any other relevant details]
This is the build, https://msazure.visualstudio.com/One/_releaseProgress?releaseId=466159&environmentId=1186081&_a=release-environment-logs; check out for 2nd attempt.

Task name: Module to Cloud - TempSensor
This step is to connect to my RPi running Windows IoT Core and run a PowerShell script for an E2E test.  However it always fails and complains about WinRM or firewall issue.  I tried to manually create a PowerShell remote session to my RPi and everything works (see attached screen capture in 20190227 logs.zip).  Please also find logs attached.

[20190227 logs.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2911834/20190227.logs.zip)

**Comment by arjgupta** [comment]
From the logs I can see that you are trying to execute the task using HTTPS but in the manual session that you are creating you are trying to connect HTTP. Maybe you need to configure https on the target machine. Can you try out HTTP with the task and see if that works.

**Comment by philipktlin** [comment]
Thanks.  It works.  Btw, do you know how to set up HTTPS powershell remote session on Windows IoT Core?

**Comment by arjgupta** [comment]
Hi @philipktlin download this powershell script https://aka.ms/vstsconfigurewinrm and this executable https://aka.ms/vstsmakecert.exe  on to your iot core machine. execute the script like so: .\ConfigureWinRm.ps1 <HostName of your Iot Core machine >. this should configure winrm for https.
