### ISSUE TITLE
Deploying to a web app slot does not remove a custom app_offline.htm file

### ISSUE THREAD

**Issue by CraigHolloway24** [Microsoft/azure-pipelines-tasks#9708]
## Environment
- Azure Dev Ops and Azure App Service
- Windows hosted agent

## Issue Description

When deploying to an app service where there is a custom `app_offline.htm` file, this is not removed when a new package is deployed to the app service with the `Publish using Web deploy` & `Remove additional files at destination` selected.

**Comment by vincentdass** [comment]
@CraigHolloway24 , is `Take App Offline` flag enabled?

**Comment by CraigHolloway24** [comment]
@vincentdass that works thank you.
Seems a bit side-effecty though. Would be great if it was clearer what that tickbox was doing.
Something like will create an App_offline.htm if it does not exist and will remove any App_offline.htm files that are present in the root of the virtual directory?

**Comment by vincentdass** [comment]
@CraigHolloway24 , thanks for the feedback.
The scope of `Take App Offline` is it would drop a `App_Offline.htm` file in the root directory before deployment and remove it after the deployment. 
In your case, MSDEPLOY dropped a default app_offline flag in the root folder, then the app_offline file in the package overrides the default file during deployment and then it was removed after the deployment.
We had a feature planned to support custom app offline, where the user can provide his custom file but its not anywhere near.
