### ISSUE TITLE
Powershell: [console]::BufferWidth - The handle is invalid

### ISSUE THREAD

**Issue by peters** [microsoft/azure-pipelines-tasks#9719]
## Environment
- Server - Azure Pipelines 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: **youpark**, **snapx**, **#20190302.35**

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name: **snapx default github pipeline**

## Issue Description

When accessing property `[console]::BufferWidth` inside a docker container, powershell throws a `The handle is invalid` exception. 

Workaround:

```ps
$BufferWidth = 0
try {
   $BufferWidth = [console]::BufferWidth
} finally {
   $BufferWidth = 80
}
```

### Task logs

- Unavailable, please access account

### Error logs

- Unavailable, please access account

**Comment by bansalaseem** [comment]
@peters, apologies for late reply. Can you please share whether you are still facing this issue or not?

**Comment by bansalaseem** [comment]
Closing it because of no reply
