### ISSUE TITLE
DockerV1 - multiple arguments

### ISSUE THREAD

**Issue by chase-swanson** [microsoft/azure-pipelines-tasks#9720]
It appears that in V1 of the Docker task, `arguments` replaces `buildArguments` from V0.

In V1, the `arguments` input does not iterate through a delimited list for multiple args as V0 does.

Is this by design? If yes, what is the new way to pass multiple build arguments in V1?

**V0** - works
```yaml
  buildArguments: |
        USERNAME=$(USERNAME)
        PASSWORD=$(PASSWORD)
        API_KEY=$(API_KEY)
```

**V1** - does not work
```yaml
  arguments: |
        USERNAME=$(USERNAME)
        PASSWORD=$(PASSWORD)
        API_KEY=$(API_KEY)
```

**Comment by bansalaseem** [comment]
@ajinkya599 were you able to look at this issue?

**Comment by ajinkya599** [comment]
In V1, `arguments` input was added to support arguments for all the commands. (and not just build)
This, requires you to specify `--build-arg` before each argument.
So, in V1 your YAML should look like:

```yaml
arguments: --build-arg USERNAME=$(USERNAME) --build-arg PASSWORD=$(PASSWORD) --build-arg API_KEY=$(API_KEY)
```

Note: This input currently does not support multi-line arguments. We have an internal tracking item to make that improvement.

**Comment by ds-ms** [comment]
Closing stale issue. Reopen if this is issue is still valid.
