### ISSUE TITLE
Job fails on cloning github submodule 

### ISSUE THREAD

**Issue by BoazWarshawsky** [microsoft/azure-pipelines-tasks#9727]
## Troubleshooting
One of my steps in the pipeline build is cloning a submodule of the project itself.
This step fails with some permission error

## Environment
Azure devops pipeline, running on Mac machine 

- Agent - Hosted or Private: 
    Host device
## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs
[logs_126.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2927986/logs_126.zip)

### Error logs
Submodule 'android_generic_app/ZappRoot-Android' (git@github.com:applicaster/ZappRoot-Android.git) registered for path 'android_generic_app/ZappRoot-Android'
Submodule 'android_generic_app/applicaster-android-sdk' (git@github.com:applicaster/applicaster-android-sdk.git) registered for path 'android_generic_app/applicaster-android-sdk'
Cloning into '/Users/vsts/agent/2.147.1/work/1/s/android_generic_app/ZappRoot-Android'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:applicaster/ZappRoot-Android.git' into submodule path '/Users/vsts/agent/2.147.1/work/1/s/android_generic_app/ZappRoot-Android' failed
Failed to clone 'android_generic_app/ZappRoot-Android'. Retry scheduled
Cloning into '/Users/vsts/agent/2.147.1/work/1/s/android_generic_app/applicaster-android-sdk'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:applicaster/applicaster-android-sdk.git' into submodule path '/Users/vsts/agent/2.147.1/work/1/s/android_generic_app/applicaster-android-sdk' failed
Failed to clone 'android_generic_app/applicaster-android-sdk'. Retry scheduled
Cloning into '/Users/vsts/agent/2.147.1/work/1/s/android_generic_app/ZappRoot-Android'...
Host key verification failed.
fatal: Could not read from remote repository.

The job has a problem cloning `ZappRoot-Android` repo

**Comment by nbara** [comment]
I'm having the same issue with submodule (belonging same organisation). Any update on this ?

Also, is there a way to bypass this by using a github access token when checking out the repo/submodules?

I'm currently using this in my YAML, but would it be possible to checkout the Submodules "manually" instead with a bash command ? This would allow passing a github TOKEN during checkout.

```yaml
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    submodules: recursive
    persistCredentials: true
```

**Comment by osolo** [comment]
This seems to be related to [this agent bug](https://github.com/Microsoft/azure-pipelines-agent/issues/1799) which was inexplicably closed.  Are there any updates?

**Comment by rossbelcher** [comment]
Also having issues with sub module authentication within the same organisation. Anyone have any workarounds for now?

**Comment by lumeiyz** [comment]
having the same issue, cannot authenticate in the same project.

**Comment by damccorm** [comment]
Hey folks, sorry this has sat so long without a response - it seems like it slipped through the cracks. With that said, this is probably not the best place to get attention for issues with cloning. The clone task exists on the agent itself - would someone mind filing an issue at https://github.com/microsoft/azure-pipelines-agent/issues? That will help get the right eyes on it
