### ISSUE TITLE
How to specify resultSelector and resultTemplate for a dropdown/combo where the data source returns an array of strings?

### ISSUE THREAD

**Issue by armanik11** [Microsoft/azure-pipelines-tasks#9728]
For a custom artifact source with drop down input fields, one of the data sources (API) returns an array of strings like below.

[ 
"String1",
 "String2"
 ]

etc.,

Datasource is configured in the extension like below.

{ "name": "Branches", "endpointUrl": "...", "resultSelector": "jsonpath:$[*]" },

How do we specify resultTemplate for this in the dataSourceBindings section?

I tried both of the below but it doesn't work.

1. "dataSourceBindings": [ { "target": "definition", "dataSourceName": "Branches", "resultTemplate": "{ Value : \"{{this}}\", DisplayValue : \"{{this}}\" }" },

2.

"dataSourceBindings": [ { "target": "definition", "dataSourceName": "Branches", "resultTemplate": "{ Value : \"{{.}}\", DisplayValue : \"{{.}}\" }" },

**Comment by divyagandhi01** [comment]
Hi, try adding this -`"resultSelector": "jsonpath:$[*]"` should give you all strings in the dropdown.
Let me know if this works for you.

**Comment by armanik11** [comment]
Hi Divya,

As you can see above in my original post, I already have "resultSelector":jsonpath:$[*]" in the dataSource section but it still doesn't work as expected. What about resultTemplate in the dataSourceBindings Section?

Thanks,
Arun

**Comment by omeshp** [comment]
Along with result selected 'jsonpath:$[*]' you should use "resultTemplate": "{ Value : "{{defaultResultKey}}", DisplayValue : "{{defaultResultKey}}" }"

**Comment by armanik11** [comment]
Thanks Omesh! Good to know.. Just curious, it this documented somewhere?

**Comment by omeshp** [comment]
@armanik11 We have documentation for endpoints at https://github.com/Microsoft/azure-pipelines-extensions/tree/master/docs/authoring/endpoints. But I see that this behavior isn't document, sorry for that. Will get it added to the documentation.

**Comment by omeshp** [comment]
https://github.com/Microsoft/azure-pipelines-extensions/commit/67cd790ee9dd1fdc9b4216d0e4eddae22a9cb89c#diff-6631d0f09a7148f0614b1258b4a6688d
