### ISSUE TITLE
web package into app service - 500 Error

### ISSUE THREAD

**Issue by nilanjanray** [Microsoft/azure-pipelines-tasks#9731]
### Error logs

2019-03-05T09:17:19.0639324Z ##[error]Failed to deploy web package to App Service.
2019-03-05T09:17:19.0653209Z ##[error]Error: Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)

Suddenly the error is coming out as it was previously ran properly and note the task version is "4.*"

**Comment by niadak** [comment]
@nilanjanray , Are you still facing the issue? Can you share the debug log with us?

**Comment by niadak** [comment]
@nilanjanray , Are you still facing the issue? Can you share the debug log with us? Please follow the [instructions ](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#get-logs-to-diagnose-problems) to generate the debug logs.

**Comment by niadak** [comment]
Closing the issue. Please feel free to reopen with debug logs if you are still facing the issue.
