### ISSUE TITLE
Publish Build Artifacts to FileShare - Robocopy has errors, Task is still Successful

### ISSUE THREAD

**Issue by MichelZ** [microsoft/azure-pipelines-tasks#9732]
## Environment
Azure Pipelines
Account/Project/BuildNumber can be shared privately.

Agent - Hosted
## Issue Description
Despite Robocopy to a Fileshare erroring out, the Task is listed as "Successful".

Task definition (from GUI -> View YAML):

`steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    publishLocation: FilePath
    TargetPath: '\\server\Builds\Builds\Product'`

```

> ##[section]Starting: Publish Artifact: drop
> ==============================================================================
> Task         : Publish Build Artifacts
> Description  : Publish build artifacts to Azure Pipelines/TFS or a file share
> Version      : 1.142.2
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=708390)
> ==============================================================================
> ##[command]robocopy.exe /E /COPY:DA /NP /R:3 "E:\VSTS1\6\a" "\\server\Builds\Builds\Product\9.4.39064.01_190305_01\drop" "*"
> 
> -------------------------------------------------------------------------------
>    ROBOCOPY     ::     Robust File Copy for Windows                              
> -------------------------------------------------------------------------------
> 
>   Started : Dienstag, 5. März 2019 04:08:31
>    Source : E:\VSTS1\6\a\
>      Dest : \\server\Builds\Builds\Product\9.4.39064.01_190305_01\drop\
> 
>     Files : *
>       
>   Options : /S /E /DCOPY:DA /COPY:DAT /NP /R:3 /W:30 
> 
> ------------------------------------------------------------------------------
> 
>                      0  E:\VSTS1\6\a\
> 2019/03/05 04:08:31 ERROR 5 (0x00000005) Accessing Destination Directory \\server\Builds\Builds\Product\9.4.39064.01_190305_01\drop\
> Access is denied.
> 
> Waiting 30 seconds... Retrying...
> 2019/03/05 04:09:01 ERROR 5 (0x00000005) Accessing Destination Directory \\server\Builds\Builds\Product\9.4.39064.01_190305_01\drop\
> Access is denied.
> 
> Waiting 30 seconds... Retrying...
> 2019/03/05 04:09:31 ERROR 5 (0x00000005) Accessing Destination Directory \\server\Builds\Builds\Product\9.4.39064.01_190305_01\drop\
> Access is denied.
> 
> Waiting 30 seconds... Retrying...
> 2019/03/05 04:10:01 ERROR 5 (0x00000005) Accessing Destination Directory \\server\Builds\Builds\Product\9.4.39064.01_190305_01\drop\
> Access is denied.
> 
> 
> ERROR: RETRY LIMIT EXCEEDED.
> 
> 
> ------------------------------------------------------------------------------
> 
>                Total    Copied   Skipped  Mismatch    FAILED    Extras
>     Dirs :         1         0         0         0         0         0
>    Files :         0         0         0         0         0         0
>    Bytes :         0         0         0         0         0         0
>    Times :   0:01:30   0:00:00                       0:01:30   0:00:00
>    Ended : Dienstag, 5. März 2019 04:10:01
> 
> ##[debug]robocopy exit code '0'
> ##[section]Async Command Start: Associate Artifact
> Associated artifact 11333 with build 24382
> ##[section]Async Command End: Associate Artifact
> ##[section]Finishing: Publish Artifact: drop

```

Notes:

- As you can see no files were copied

- Robocopy errored out

- Task thinks it got exit code '0', which it shouldn't

This has also been reported here:
https://developercommunity.visualstudio.com/content/problem/478255/publish-build-artifacts-to-fileshare-robocopy-has.html

**Comment by pjquirk** [comment]
I can reproduce the behavior seen in Robocopy where it returns an exit code of '0' even when it encounters access denied errors.  According to its documentation (https://ss64.com/nt/robocopy-exit.html), it looks like it should have returned a code >16 or at least >8:

    0×00   0       No errors occurred, and no copying was done.
                   The source and destination directory trees are completely synchronized. 

    0×01   1       One or more files were copied successfully (that is, new files have arrived).

    0×02   2       Some Extra files or directories were detected. No files were copied
                   Examine the output log for details. 

    0×04   4       Some Mismatched files or directories were detected.
                   Examine the output log. Housekeeping might be required.

    0×08   8       Some files or directories could not be copied
                   (copy errors occurred and the retry limit was exceeded).
                   Check these errors further.

    0×10  16       Serious error. Robocopy did not copy any files.
                   Either a usage error or an error due to insufficient access privileges
                   on the source or destination directories.

I don't see any settings in Robocopy that we could add to force a non-zero exit code in this, so I'm closing this a not a bug in Azure DevOps.

I mentioned in the Developer Community ticket that a new ticket should be created for this possible bug in Robocopy.
