### ISSUE TITLE
Certificate error during artefact download when behind SSL proxy

### ISSUE THREAD

**Issue by Shortcheese** [Microsoft/azure-pipelines-tasks#9733]
By using the Build task "Download Build Artifacts"
we get the error "##[error]Failed in getArtifact with error: Error: self signed certificate in certificate chain"

We use Azure Devops with on on premis agents using vsts-agent-win-x64-2.147.1 on a windows 7 machine

This problem is showing up since the upgrade of the task from version 0.146.0 to version 0.148.0
In version 0.146 we didn't got any problems now with versio 0.148.0 we got the problem.

The logfile is attached

[ErrorLog.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2930350/ErrorLog.txt)

**Comment by gykuma** [comment]
@Shortcheese this issue seems to be similar to #7584

Can you please try the following steps and let us know if it works:
- download a new copy of the agent
- put your CA cert chain under the root of the agent folder, the cert better be .pem
- configure agent with `config.cmd --sslcacert ./locationtoyourcert.pem`

**Comment by gykuma** [comment]
@Shortcheese I'm closing this issue for now. Please feel free to reopen, if above steps doesn't resolve your issue.

**Comment by Shortcheese** [comment]
@gykuma sorry for the delay in answering. My company's network crew was tracing the issue for checking if there was a fault at our setup.

We do some ssl interception at some point. 

And when I was ready to try the solution using the pem file, I found out that with rolling out hotfix 0.148.1 of the task our problems are solved for now.

Was there a problem with the task not using windows own certificates store?

**Comment by gykuma** [comment]
@Shortcheese Happy to know the issue got resolved for you. 

With the hotfix, we rolled back some changes we made in last update. It was done in reaction to increased ECONNRESET errors on private agents while downloading artifacts. Since the hotfix seems to have resolved your issue too, we will investigate further to understand the correlation.

**Comment by Shortcheese** [comment]
@gykuma Hi sinds the release of 0.153.1 I'm getting this error again.

**Comment by gykuma** [comment]
@Shortcheese sorry for the trouble. This task is being replaced by [Download Pipelines Artifact task](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=classic#download-pipeline-artifacts). So it not being actively updated, except for major fixes. Would it be possible for you to use the Download Pipeline Artifact task in place of this task? You can find more details about using that task [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=classic).

In case you want to continue using this task, you can try using above steps to resolve the issue for you:

> @Shortcheese this issue seems to be similar to #7584
> 
> Can you please try the following steps and let us know if it works:
> 
> * download a new copy of the agent
> * put your CA cert chain under the root of the agent folder, the cert better be .pem
> * configure agent with `config.cmd --sslcacert ./locationtoyourcert.pem`

**Comment by Shortcheese** [comment]
I will try the new task! Is it usable with the "old" upload build artifact task?

keep you posted

**Comment by Shortcheese** [comment]
The new task works wel.
Is there a way to script the change. because we use de build artifact tasks alot.
