### ISSUE TITLE
[Feature Request] Task to invoke vcvarsall and persist the changes

### ISSUE THREAD

**Issue by cstratopoulos** [microsoft/azure-pipelines-tasks#9737]
In brief: I think there should be a task which is equivalent to calling `vcvarsall.bat my_args` and making it so that the changes are persisted to subsequent tasks (e.g., the [CMake task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/cmake?view=azure-devops)).

This would make it a lot easier to use, e.g., `clang-cl` as the compiler on the hosted Windows image while still using the CMake task.

I spent quite a lot of time trying to sort this out the other day. Note for example some other `azure-pipelines.yml` files resort to invoking CMake manually, calling `vcvarsXXX.bat` before every single one:
https://github.com/psi4/psi4/blob/7110c8f6399ab40936d9b1f6c18b5ecc3105c4e4/azure-pipelines.yml#L65

https://github.com/kfrlib/kfr/blob/55ec09e9c072a63735fd617953cb36826d4bdace/azure-pipelines.yml#L91

I have come up with a hacky implementation of the suggested task, tailored to my very specific use case of building with clang-cl on Windows images:
https://dev.azure.com/ossiaco/ossiaco/_git/AzureTemplates?path=%2Fclang-cl-setup.yml&version=GBmaster&line=33&lineStyle=plain&lineEnd=59&lineStartColumn=2&lineEndColumn=48

Unfortunately there are some weird hoops to jump through to make sure the original PATH is appended to rather than clobbered

You can see it in use, e.g., here:
https://dev.azure.com/ossiaco/ossiaco/_git/JsonConverter?path=%2Fazure-pipelines.yml&version=GBmaster&line=33&lineStyle=plain&lineEnd=72&lineStartColumn=1&lineEndColumn=1

Note that I specify `lld-link` as the linker due to another weird quirk where the existing condition of the PATH variable makes it so that `Git/bin/link.exe` is otherwise discovered first. However, happily I am able to use my CMake task templates which use the CMake task to invoke configure/generate and build.

I'll mention this issue https://github.com/Microsoft/azure-pipelines-image-generation/issues/270#issuecomment-469768097 which would partially obviate the need for this one, making it possible to use `clang-cl` with the default Visual Studio CMake generator. However I think the task I've described above could still be useful (or required) if one wanted to use Ninja.

**Comment by bryanmacfarlane** [comment]
We have a marketplace.  It would be great for anyone to create one for this.

**Comment by themissingcow** [comment]
This would be very helpful for our `scons` based cross-platform pipeline too.

**Comment by shogerr** [comment]
The CMake task remains pretty much worthless:
```
C:\Program Files\CMake\bin\cmake.exe -G Ninja -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_C_COMPILER=cl.exe -S . -B build
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    cl.exe

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:
```

**Comment by shogerr** [comment]
As it is looking now, there is no sane way to actually tell an azure pipeline where an agent's visual studio is installed. This means no tasks, except the ones Microsoft builds for us, like MSBuild, have access to the Visual Studio toolchain. Am I way off base here? It seems like a pretty poor choice for a build system to not understand anything about the build system it is supposed to be using.

**Comment by ihnorton** [comment]
This would be incredibly useful.
