### ISSUE TITLE
Synchronous artifact upload with ##vso commands

### ISSUE THREAD

**Issue by JohnTortugo** [Microsoft/azure-pipelines-tasks#9745]
I’m using artifact logging commands (https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md) to upload the artifacts from my build. However, I’m running into a problem because looks like these commands upload the artifacts asynchronously and I’ve a subsequent step of the build that tries to rename the artifact folder not knowing that there are active artifact uploads. 

The scenario is like this:

-	Use ##vso commands to upload artifacts from folder “foo/”
-	Something tries to rename “foo/” folder to “bar/”

**So my question is:** is there a way to make the artifact upload synchronous or to find out that all uploads have finished?

**Comment by mitchdenny** [comment]
You can use the Publish Pipeline Artfiact task to publish artifacts during the build, this will execute synchronously. Most folks who use the ```##vso``` commands are doing so to upload from within a script or to append files to a container. What is you specific scenario?

We are adding capabilities to Pipeline Artifacts to support appending content to an existing artifact, date is TBA but we are working on it at the moment.

**Comment by JohnTortugo** [comment]
> Most folks who use the `##vso` commands are doing so to upload from within a script or to append files to a container. What is you specific scenario?

I upload the files during execution of a msbuild task.

**Comment by mitchdenny** [comment]
OK thanks for that information.

**Comment by bryanmacfarlane** [comment]
>  subsequent step of the build 

The async upload is drained before that step finishes.  If it's the next step in the build definition or yaml, it will have completed.  But within your msbuild targets in that step, you cannot count on it having been uploaded.

**Comment by alexmullans** [comment]
@mitchdenny @bryanmacfarlane is this something we can/should fix or is it a limitation of using ##vso through msbuild?

**Comment by mitchdenny** [comment]
We can't fix it. When the program that outputs the ##vso commands it continues running, there isn't a way for the agent to force to the block. For Pipeline Artifacts a work around would be to use the ```az pipelines runs artifact upload command```. When we deliver multi-publisher support we'll round out the scenario.

But the ##vso commands will always be async in nature.
