### ISSUE TITLE
Allow GoTool to force 32 bit download

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-tasks#9750]
## Issue Description

`GoTool@0`

I'd like to be able to intentionally download 32-bit golang on 64-bit architectures -- similar to the `architecture` parameter for `UsePythonVersion@0`

I'd be happy to work on this as well, if you can give me some pointers to where I would look

**Comment by bishal-pdMSFT** [comment]
@asottile Go tool installer code is mainly [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/GoToolV0/gotool.ts). If you are planning to expose a new input, then you also need to change [task.json](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/GoToolV0/task.json).
I would suggest you to write a short paragraph for high level design of the proposed change.

**Comment by asottile** [comment]
@bishal-pdMSFT -- anything needed beyond the short paragraph in the original comment?

**Comment by bishal-pdMSFT** [comment]
Usually anything which will help us in better understanding of PR. Yeah, in this case there is not much to say, but you can still explicitly mention what input you will add and what will be default value for that etc.

**Comment by issacnitin** [comment]
@asottile Let me know if you need any help in the task implementation/testing. Super excited to see how you solve it! 😄
