### ISSUE TITLE
VSTest@2: Support for VS2019

### ISSUE THREAD

**Issue by JohannesDrexler** [Microsoft/azure-pipelines-tasks#9756]
## Environment
- Server - Azure Pipelines or TFS on-premises?
    -> AzurePipelines

- Agent - Hosted or Private: 
    -> Hosted: "Hosted Windows 2019 with VS2019"

## Issue Description

I am updating a build definition to run on the hosted machine (posted above) and compile and run tests using VS2019. The task VSTest@2 won't let me choose "Visual Studio 2019" as test platform. When i choose "Latest" instead the task fails with error message `Visual Studio 2015 is not found. Try again with a version that exists on your build agent machine.` (I'll post full debug logs of failing vstest@2 task below)

[9.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2941135/9.txt)

**Comment by acesiddhu** [comment]
@ShreyasRmsft I remember you doing a fix for the same. do u know if fix is checked in?

**Comment by ShreyasRmsft** [comment]
@JohannesDrexler we have added VS2019 support and the deployment with the update has started. It might take a couple of more days to reach all accounts. Meanwhile please use the [vstest platform tool installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops) to acquire the latest test platform.

This is a better and recommend way to stay up to date with the testplatform as servicing is much easier. You will receive fixes immediately when we publish the changes and will not have to wait for the next VS release.

**Comment by JohannesDrexler** [comment]
What a timing! Now i can select "VS2019" in VSTest@2 so the deployment already reached my account. I'll close this then. Thanks :)

**Comment by ShreyasRmsft** [comment]
Haha. Do consider using [vstest platform tool installer task ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops)

That is the what we recommend going forward.

**Comment by JohannesDrexler** [comment]
i updated some builds to use the platform-installer for tests now
