### ISSUE TITLE
[Feature] [.NET Core SDK Installer] Use latest version specifying part of major version

### ISSUE THREAD

**Issue by ptr727** [microsoft/azure-pipelines-tasks#9758]
## Troubleshooting
Searched google and GitHub for similar feature requests.

## Environment
Azure DevOps

## Issue Description
Request to have the ".NET Core SDK Installer" task accept a version specification and automatically use the latest release for the specified version.

E.g. I want to use .NET Core 2 latest, maybe specify 2.*
E.g. I want to use .NET Core 2.2 latest, maybe specify 2.2.*
E.g. I want to use .NET Core 3 latest, maybe specify 3.*
E.g. I want to use specifically .NET Core 3.0 Preview 3, I will specify 3.0.100-preview3-010431

Today I need to refer to https://github.com/dotnet/core/blob/master/release-notes/releases.json and use the exact version number.

**Comment by bishal-pdMSFT** [comment]
@ptr727 we are actively working on a new version of task which will support for this.

**Comment by sachinma** [comment]
This is now supported in UseDotNet version 2 task
