### ISSUE TITLE
Run Functional Tasks: Not distributed. The tests are running on the second VM only after finishing on first VM when running Distributed Tests on Team Foundation Server Build.

### ISSUE THREAD

**Issue by buddalasunil999** [Microsoft/azure-pipelines-tasks#9760]
I am using "Distribute tests by number of machines" option in TFS Run Functional Tests step

![image](https://user-images.githubusercontent.com/2284522/53993214-965a2980-4193-11e9-9db7-1b5445c897a7.png)

But we have a problem. We are using two VMs to run the tests and want to distribute tests equally. The tests we have are specflow tests(using xunit) in one assembly.

I disabled parallel execution of tests in the assembly.

`[assembly: CollectionBehavior(DisableTestParallelization = true)]`

The tests are running on the second VM only after finishing on first VM.

> We want to run tests on the same machine one by one. But run them parallel on multiple machines. How can I achieve this?

we are using Microsoft Visual Studio Team Foundation Server Version 16.122.27409.2

**Comment by ShreyasRmsft** [comment]
@buddalasunil999 Distribution is based on number of assemblies. If you have only one test assembly distribtion will not work.

**Comment by buddalasunil999** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/run-functional-tests?view=azure-devops
![image](https://user-images.githubusercontent.com/2284522/54560420-35e6aa00-4a27-11e9-8822-4c694a72a8fc.png)

@ShreyasRmsft  The task says it distributes tests based on number of machines instead of at the assembly level.

**Comment by ShreyasRmsft** [comment]
I'm sorry the description is a bit misleading but the granularity is at the assembly level.

If you want pure test based distribution please use the vstestv2 task.
