### ISSUE TITLE
PowerShell task - remove BOM from [Console]::InputEncoding to prevent issues with Start-Job

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/azure-pipelines-tasks#9766]
## Environment
- Server - Azure Pipelines
    - Before fix: https://msazure.visualstudio.com/One/_build/results?buildId=20624632
     - After fix: https://msazure.visualstudio.com/One/_build/results?buildId=20634533

- Agent - Private
    - OS: Microsoft Windows Server 2012 R2 Datacenter (6.3.9600.0) [Win32NT] x64 
   - Agent version: 2.148.0

## Issue Description

The PowerShell task starts in a console whose `InputEncoding` is UTF8 with BOM as can be verified with this simple test: `[Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0`.

Now, `Start-Job` spawns a separate PowerShell process in [server mode](https://stackoverflow.com/a/45335547/67824), [where it uses the standard input and output streams to exchange messages with the parent process](https://stackoverflow.com/a/45772308/67824). However, for reasons I don't fully understand (possibly dependent on the OS and its configuration, since it doesn't happen on my home Win10 machine), that process is opened with the default codepage (in my case `SBCSCodePageEncoding` / `IBM437`), which does not include a BOM ([related issue on Unix](https://github.com/dotnet/corefx/issues/32004)).

That in turn causes the [communication between the parent PS process and the child PS process to be interrupted](https://github.com/ansible/ansible/issues/15770#issuecomment-227898569), resulting in the error below (pasted at the boton in the _Error logs_ section).

A workaround which turns off the BOM in the parent's console input encoding has been suggested in a similar [UserVoice thread](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/14915283-job-cmdlets-fail-with-utf-8-codepage) (reposted in [SO](https://stackoverflow.com/a/43350250/67824)), and adding that to the start of the initial (parent) PowerShell script indeed resolves the issue: 
```ps1
if (
    [Console]::InputEncoding -is [Text.UTF8Encoding] -and
    [Console]::InputEncoding.GetPreamble().Length -ne 0
) {
    [Console]::InputEncoding = New-Object Text.UTF8Encoding $false
}
```

### Error logs

 `There is an error processing data from the background process. Error reported: Cannot process an element with node type "Text". Only Element and EndElement
node types are supported`

**Comment by damccorm** [comment]
Added a PR on the agent that should handle this.

**Comment by damccorm** [comment]
Closing since this should now be fixed from the agent. It will roll out with the next agent release.
