### ISSUE TITLE
GithubReleaseV0 - Link in list of changes does not escape spaces

### ISSUE THREAD

**Issue by fernandreu** [microsoft/azure-pipelines-tasks#9770]
## Environment

- Server - Azure Pipelines

  - Organisation: fernandreu-public
  - Team project name: Custom UI Editor
  - Build definition name: BuildAndTest
  - Build number: 20190309.5

- Agent - Hosted: 
    
    - Agent queue name: Hosted VS2017 2

## Issue Description

My project name, `Custom UI Editor`, has spaces. This is fine for the release process, but the Markdown syntax does not seem to support them in links. Hence, the last line in the list of changes ends up looking similar to this:

> This list of changes was [auto generated](https://dev.azure.com/fernandreu-public/Custom UI Editor/_build/results?buildId=94).

Perhaps replacing those spaces by `%20` symbols in [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/bf3c7099f34c840dd2152f41484a8588b1352536/Tasks/GitHubReleaseV0/operations/ChangeLog.ts#L337) would fix the issue?

### Task logs

Let me know if these are necessary.

### Error logs

Let me know if these are necessary.

**Comment by mdmdakbar** [comment]
Yes, possibly we need to encode the url. 

Thanks @fernandreu for reaching out to us. Will update the thread with a fix soon.

**Comment by TheLayman** [comment]
Issue fixed with this PR #10770.
