### ISSUE TITLE
Unable to find `Microsoft.NETCore.App' version '2.1.0' after installing 3.0.100-preview3-010431 with DotNetCoreInstaller

### ISSUE THREAD

**Issue by chyyran** [Microsoft/azure-pipelines-tasks#9771]
After running the `DotNetCoreInstaller` task to install `3.0.100-preview3-010431`, no other SDKs seem to be available on the `ubuntu-16.04` image.

**Expected behavior**
Installing `3.0.100-preview3-010431` should still allow projects targeting `Microsoft.NETCore.App/2.1.0` to build

**Actual behavior**
When attempting to compile a project that targets `Microsoft.NETCore.App/2.1.0` ...

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/hostedtoolcache/dncs/3.0.100-preview3-010431/x64
  - The .NET Core Runtime and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      3.0.0-preview3-27503-5 at [/opt/hostedtoolcache/dncs/3.0.100-preview3-010431/x64/shared/Microsoft.NETCore.App]
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?linkid=2063370
```

**Comment by issacnitin** [comment]
@chyyran It seems to be working, with the following BD I tried:

![Image](https://i.ibb.co/GRSLJBx/9771.png)

Sample code is pointing to .NET Core 2.1.0
Could you share the BD that failed?
