### ISSUE TITLE
I can't modify the virtual applications and directories in the Azure App Service. It causes such error.

### ISSUE THREAD

**Issue by PKG94** [Microsoft/azure-pipelines-tasks#9780]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by PKG94** [comment]
Updating web app settings
Failed to update web app settings: ["{\"Code\":\"BadRequest\",\"Message\":\"Missing default application '/'\",\"Target\":null,\"Details\":[{\"Message\":\"Missing default application '/'\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"ExtendedCode\":\"04065\",\"MessageTemplate\":\"Missing default application '/'\",\"Parameters\":[],\"Code\":\"BadRequest\",\"Message\":\"Missing default application '/'\"}}],\"Innererror\":null}"]

**Comment by bryanmacfarlane** [comment]
Can you update which task in this repo you're having an issue with?  The issue template wasn't filled out.  It looks external to task in the repo.  Will re-open with details

**Comment by kmkumaran** [comment]
This seem related to Azure App Service task.

**Comment by niadak** [comment]
@PKG94  Can you please provide the complete debug logs for the task?

**Comment by niadak** [comment]
@PKG94 Can you please provide the complete debug logs for the task? Please follow the [instructions ](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#get-logs-to-diagnose-problems)here to generate the debug logs.

**Comment by niadak** [comment]
Closing the issue. Please feel free to reopen with debug logs if you are still facing the issue.
