### ISSUE TITLE
Warning into builds pipelines: Use Cipheriv for counter mode of aes-256-ctr

### ISSUE THREAD

**Issue by denis-panov** [microsoft/azure-pipelines-tasks#9783]
## Issue Description
_Tasks: Install an Apple provisioning profile, Xcode, PowerShell, Command Line, Shell Script ..._

We faced next warning into builds pipelines: 
> Warning: Use Cipheriv for counter mode of aes-256-ctr

Looks like here is **fix** for this: https://github.com/nodejs/node/issues/16746#issuecomment-341900420

Also it’s discussed on the **forum**: https://developercommunity.visualstudio.com/content/problem/475022/getting-warning-use-cipheriv-on-various-stages-of.html

Is this known issue? Do you plan to fix it?

![image](https://user-images.githubusercontent.com/40772628/54126543-d978fe80-4418-11e9-85e7-87021830b8a6.png)

## Environment
Server - Azure Pipelines
Agent - Hosted on MacOS

### Task logs
```
##[section]Starting: Xcode build (signed)
==============================================================================
Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 4.130.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613730)
==============================================================================
[command]/usr/bin/xcodebuild -version
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:858) Warning: Use Cipheriv for counter mode of aes-256-ctr
```

**Comment by bryanmacfarlane** [comment]
consume new task lib

**Comment by ohdihe** [comment]
Got the same error using yesterday march 14th and it was related to Azure Resource Group Deployment task. 

I was using Windows Hosted Agent VS2017

**Comment by meigaoms** [comment]
Got same error when running ShellScript@2 task here. Any update?

**Comment by tarifrr** [comment]
Got the same error here too when using Ubuntu 2018 for running the build pipe:

![image](https://user-images.githubusercontent.com/477801/74380981-9ce81c80-4db8-11ea-8fb3-0e3967d639d7.png)

**Comment by lemessur** [comment]
I'm not sure if it's the same issue, but I am seeing this same warning message printing repeatedly during every single build step of my AppCenter Android and iOS Xamarin projects:

(node:1330) Warning: Use Cipheriv for counter mode of aes-256-ctr

The reported line number varies quite a bit.

I found this thread by googling this warning.

Whenever this warning shows up in the build log the build later fails with the error message: 

##[error]"{\"code\":\"dependent_service_error\",\"message\":\"Error: Error: ESOCKETTIMEDOUT\"}"

For now the solution is to wait a little while (~30 minutes) and then retry the build. Everything usually works after that. This issue pops up once a week or so, but never seems to coincide with any issues reported on the AppCenter status page.

**Comment by airman00** [comment]
@lemessur When the build *does* work, does "(node:1330) Warning: Use Cipheriv for counter mode of aes-256-ctr" still appear?

Currently facing the same issue

**Comment by lemessur** [comment]
> @lemessur When the build _does_ work, does `(node:1330) Warning: Use Cipheriv for counter mode of aes-256-ctr` still appear?
> 
> Currently facing the same issue

Now that you mention it, I see the warning appearing with the same frequency in logs from recent successful builds. The error I'm seeing might not have anything to do with this warning.

The AppCenter Status page (https://status.appcenter.ms/) is now acknowledging some sort of issue with distribution so it's probably being caused by whatever that is. The message was posted there a little over an hour ago, but I started seeing that error (##[error]"{"code":"dependent_service_error","message":"Error: Error: ESOCKETTIMEDOUT"}") around 4 hours ago.

At this point I'm thinking that "Warning: Use Cipheriv for counter mode of aes-256-ctr" is some non-fatal issue that Microsoft does not care about (This thread is nearly a year old and there has been no official response) and it has nothing to do with our current build/distribution problems.

**Comment by Bnjmn83** [comment]
Seeing the same:

```
2020-02-18T02:35:37.8717258Z ==============================================================================
2020-02-18T02:35:37.8717828Z Task         : Docker
2020-02-18T02:35:37.8718434Z Description  : Build, tag, push, or run Docker images, or run a Docker command
2020-02-18T02:35:37.8718945Z Version      : 1.157.0
2020-02-18T02:35:37.8719404Z Author       : Microsoft Corporation
2020-02-18T02:35:37.8719952Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/docker
2020-02-18T02:35:37.8720533Z
2020-02-18T02:35:38.2533445Z [command]/usr/local/bin/docker run ...
2020-02-18T02:35:38.2628584Z (node:42138) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-02-18T02:35:38.2644302Z (node:42138) Warning: Use Cipheriv for counter mode of aes-256-ctr
==============================================================================
```

**Comment by dkmiller** [comment]
I can also reproduce this issue. It is arising during the PowerShell task running in `ubuntu-latest` machines:

> Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.163.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell

(the script is **extremely** simple: parse an XML file and set a build variable).

**Comment by shogerr** [comment]
Warning seen while using the CopyFiles task:
```
Starting: CopyFiles
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.158.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
...
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr

```

**Comment by leantk** [comment]
The fix here is to move from using `vsts-task-lib` to `azure-pipelines-task-lib` library. An example of this is in the PR https://github.com/microsoft/azure-pipelines-tasks/pull/12489. A few updates have to be made along with the library change to account for some differences in them

**Comment by anton-erofeev** [comment]
Hello, @shogerr !
According to your logs, you are using version 2.158.0. 
This error is fixed in version 2.164.0 (https://github.com/microsoft/azure-pipelines-tasks/pull/12207), so could you please update the version and try to run it again? If this warning still occurs, please let me know.

**Comment by anton-erofeev** [comment]
Hello, @shogerr , @denis-panov !

Could you please provide your organization name from Azure DevOps? This will help us make sure that you receive a bug fix update.

**Comment by shogerr** [comment]
@anton-erofeev: USNR-EWP. Contact could be @jlidbeck

**Comment by anton-erofeev** [comment]
Hello, @jlidbeck, @shogerr 
Your organization uses the latest version of this task, so this warning no longer appears on your pipeline. Please let me know if you get this warning again.

**Comment by anton-erofeev** [comment]
Closed due to lack of activity, please feel free to reopen.

**Comment by s-hintz** [comment]
We are still getting these warnings in the logs when building with App Center.

(node:5670) Warning: Use Cipheriv for counter mode of aes-256-ctr

**Comment by leantk** [comment]
@microsoft/app-center to make the task update

**Comment by nichojo89** [comment]
We are still getting this issue when deploying an ad-hoc Xamarin app .ipa file to AppCenter using an App Center Deploy task. I've tried re-creating AppCenter token, recreating release task. Gets stuck on `(node:7356) Warning: Use Cipheriv for counter mode of aes-256-ctr` and fails to deploy to AppCenter. No changes were made to this release task this just suddenly started happening.

**Comment by King-of-Spades** [comment]
@nichojo89 I'm from the App Center Support team. 

The only known cause of that Cipheriv warning I'm familiar with is if the signing files contain special characters in the name. That limitation is warned about in our code-signing doc here: https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing#signing-files

I don't know for certain if that's the only way to trigger the warning, or if special characters always result in it. However, I didn't find any other issues correlated with the error message either.

**Comment by johnybaryah** [comment]
@nichojo89 I can also confirm the same issue using app-center-distribute version 3.*

**Comment by King-of-Spades** [comment]
@nichojo89 @johnybaryah 

## Observations
I don't believe this error message is sufficient to diagnose a single, consistent issue:
> Warning: Use Cipheriv for counter mode of aes-256-ctr

I've observed the warning appearing in both Android and iOS builds that successfully completed building as well as running automated UI tests on most (though not 100%) of devices. Repo: https://github.com/microsoft/appcenter-Xamarin.UITest-Demo/

Maybe it still indicate _something_ is wrong, but at the very least, it doesn't seem to be the most informative symptom to focus on by itself. This is also consistent with some past comments on this thread: https://github.com/microsoft/azure-pipelines-tasks/issues/9783#issuecomment-586467368

## Example logs from passing iOS Build & UITest suite
From commit: https://github.com/microsoft/appcenter-Xamarin.UITest-Demo/tree/e775ca618e6d010ed9d320613f15517814990097
```
==============================================================================
Task         : Install Apple Provisioning Profile
Description  : Install an Apple provisioning profile required to build on a macOS agent
Version      : 0.124.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
##[warning]Deleting provisioning profile: /Users/runner/Library/MobileDevice/Provisioning Profiles/22a9db50-d8aa-4c46-ac64-34bc5d680aa6.mobileprovision
[command]/bin/rm -f /Users/runner/Library/MobileDevice/Provisioning Profiles/22a9db50-d8aa-4c46-ac64-34bc5d680aa6.mobileprovision
(node:2092) Warning: Use Cipheriv for counter mode of aes-256-ctr
... (repeats several times)
##[section]Finishing: Install Apple provisioning profile
##[section]Starting: Install Apple certificate
```

## Example logs from passing Android build & UITest suite
From commit: https://github.com/microsoft/appcenter-Xamarin.UITest-Demo/tree/e775ca618e6d010ed9d320613f15517814990097
```
##[section]Starting: Restore Nuget
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
[command]/bin/bash -c /usr/bin/find . -name '*.sln' -type f -print0 | /usr/bin/xargs -0 grep -l 'UITestDemo.Droid.csproj' | /usr/bin/xargs -I '{}' nuget restore '{}' -DisableParallelProcessing
(node:1293) Warning: Use Cipheriv for counter mode of aes-256-ctr
... (repeats several times)
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'.
Restoring NuGet package Newtonsoft.Json.12.0.3.
... (continues with fairly normal logging)
```

**Comment by anatolybolshakov** [comment]
@King-of-Spades looks like you use old versions of InstallProvisioningProfile and CommandLine tasks - are you using on-prem solution? If so - you need to update it to receive last version of in-the-box pipeline tasks containing a fix for this issue.

**Comment by Sidoran** [comment]
Hello. We have the same issue with the WhiteSource task.
Issue reproduced on 19.* and 20.* task versions.
![image](https://user-images.githubusercontent.com/50662809/108084557-027e8100-707d-11eb-988a-cf98f2edb067.png)

**Comment by anatolybolshakov** [comment]
Hi @Sidoran WhiteSource task is external for this repo, please contact support of this task to resolve this issue.
They just need to update azure-pipeline-task-lib dependency like it was in [PR ](https://github.com/microsoft/azure-pipelines-tasks/pull/14026/files)

**Comment by Sidoran** [comment]
> 
> 
> Hi @Sidoran WhiteSource task is external for this repo, please contact support of this task to resolve this issue.
> They just need to update azure-pipeline-task-lib dependency like it was in [PR ](https://github.com/microsoft/azure-pipelines-tasks/pull/14026/files)

@anatolybolshakov, thank you. I will notify WhiteSource support.

**Comment by s-hintz** [comment]
When will this be fixed?

**Comment by thwyster** [comment]
Has this been fixed?
