### ISSUE TITLE
Unable to setup Visual Studio Test task

### ISSUE THREAD

**Issue by mariankral** [Microsoft/azure-pipelines-tasks#9787]
Hi,
I'm performing user interface (UI) testing with Selenium.
Web browser and webdriver is pre-installed on virtual machine with test agent.
I tried to use 'Visual Studio Test' task instead of 'Visual Studio Test Agent Deployment' and 'Run Functional Tests' because these task are deprecated and will stop working.

Environment:
Azure Pipelines
Agent machine with Windows 10 running the agent and the agent version: MS Agents for VS 2015 with Update 3
C;\TestAgent contains DTAExecutionHost.exe and TestExecutionHost.exe

Here is my current pipeline:
![01](https://user-images.githubusercontent.com/3882110/54131349-6f5d5b00-4412-11e9-8544-e89d19741113.png)

Here is settings for 'Deploy TestAgent' task:
![02](https://user-images.githubusercontent.com/3882110/54131603-f7dbfb80-4412-11e9-96aa-73645728d03b.png)

Here is settings for 'Run Functional Tests':
![03](https://user-images.githubusercontent.com/3882110/54131862-82245f80-4413-11e9-8f56-eebca150725b.png)

Question is, how to replace two deprecated tasks with 'Visual Studio Test' task.
There is no way how to define server/virtual machine with test agent, In the 'Visual Studio Test' task.

Can you help me with the settings, please?
Thank you in advance for your help.
M.

**Comment by ShreyasRmsft** [comment]
Can you please go through https://devblogs.microsoft.com/devops/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/

This should help. In brief you need to setup a build agent (azuredevops-pipelines-agent) on the machine you want to run tests on.
