### ISSUE TITLE
DotNetCoreCLI commands are inconsistent

### ISSUE THREAD

**Issue by weshaggard** [microsoft/azure-pipelines-tasks#9789]
The DotNETCoreCLI task supports various commands however they all seem to be inconsistent. A couple examples:

`arguments`: While the task supports an optional arguments parameter it doesn't get used by all the tasks. I was trying to pass additional augments to the pack command and while the YAML accepts it the pack command completely ignores it. 

Another example is the verbosity parameter some if you check out the documentation you see "verbosity" listed twice in the doc table and in the same command you see it listed at `verbosityRestore` and `verbosityPack`. Is there really any reason that all the commands cannot simply use `verbosity` as it is a common option for all.

Please work on cleaning up this task to make the different commands consistent and only add additional parameters for things that are truly unique for the given command. At this point to workaround these I will need to stop using the DotNETCoreCLI task and make the call directly with a script.

**Comment by issacnitin** [comment]
@weshaggard Thank you for the feedback, I agree the commands are inconsistent right now and need cleanup. We'll start working on this as soon as possible.

**Comment by OliverRC** [comment]
I agree, pack should completely allow arguments to be passed.

**Comment by smileyiori** [comment]
Even if you pass the arguments, the CLI does not execute them.
In my case I set `nobuild: true` 
![image](https://user-images.githubusercontent.com/8495055/75732982-dc63a380-5ca8-11ea-9e7b-04c905a05612.png)

and my command looks like:
![image](https://user-images.githubusercontent.com/8495055/75732912-acb49b80-5ca8-11ea-91c0-c084ba44ef85.png)

But the project still building. Is there something related?

**Comment by dmcweeney** [comment]
Just some feedback here - this is painful for me at the moment - after introducing  second repo into the build script all the dotnet commands are failing - trying to use the workingDirectory property to fix it but its not supported by some of the dotnet commands and the docs dont clarify

**Comment by bishal-pdMSFT** [comment]
Cc @tejasd1990 @pulkitaggarwl

**Comment by sayedsaad07** [comment]
Any updates on this issue please 
I tried different combinations but nothing seems to work
Working-directory is ignored
even below does not work 
dotnet restore ${{github.workspace}}/webapi

**Comment by dmcweeney** [comment]
Hi @bishal-pdMSFT any update on this?
