### ISSUE TITLE
Feature Request: Azure Container Instance (ACI) Task

### ISSUE THREAD

**Issue by damienwebdev** [microsoft/azure-pipelines-tasks#9797]
# Feature Request: ACI Support and Azure DevOps API Tasks

## User Story

As a developer, I would like to be able to deploy my docker containers onto ACI.
As a developer, I would like to be able to comment on a PR in Azure DevOps.

## Problem
While we have support for Azure Web Apps, Service Fabric, and AKS, we don't yet have good support for ACI. Additionally (surprisingly), we have even less support for interacting with Azure DevOps via PR comments, issues, etc.

## Use Case
It would be absolutely fantastic if I as a developer could achieve the following from a high level:

1. Build My App
2. Run My Tests
3. Generate a Docker Container
4. Push the container to a registry
5. Generate a "preview" release on ACI
6. Comment a link on the PR indicating where I can see my preview on ACI
7. Once a PR is merged, terminate the preview in ACI.
  * Or once a new build occurs, terminate the old preview, and spin up a new one.

Currently, 1-4 of this are readily available via DevOps tasks. 5-7 are absolutely possible but require creating custom tasks or difficult to maintain scripts.

With the recent announcement of Zeit's "Now" platform [no longer planning on supporting docker containers](https://spectrum.chat/?t=96985341-e17f-4af4-a330-c726774ed436), this seems like a good time to approach the above concepts as the technology in Azure Pipelines/Azure is 95% there, but needs that extra little nudge over the edge.

**Comment by azooinmyluggage** [comment]
@damienwebdev thanks for the feature request.
We are planning to pick this work up. Will you be interested in giving early feedback?

**Comment by texnokot** [comment]
> @damienwebdev thanks for the feature request.
> We are planning to pick this work up. Will you be interested in giving early feedback?

If it is possible, I would like to participate in testing and provide feedback.

**Comment by tiesmaster** [comment]
@azooinmyluggage +1 I'd be willing to participate in testing, and providing feedback, as well. I've subscribed to this issue for updates.

**Comment by damienwebdev** [comment]
@azooinmyluggage yes. Absolutely, sorry for the delay.

**Comment by a-patel** [comment]
@shashankbarsin and @bansalaseem 
Any update on this?

**Comment by damienwebdev** [comment]
Not stale. This issue was on maybe picked up by @azooinmyluggage ?
