### ISSUE TITLE
Build.SourceVersion env variable not showing the correct commit id from GitHub

### ISSUE THREAD

**Issue by BoazWarshawsky** [microsoft/azure-pipelines-tasks#9801]
## Environment
Mac hosted device.

## Issue Description
I am running the pipeline from Github on every push to pull request.
Every push has its unique commit id.
When I am printing in the yaml file from bash task this field: `Build.SourceVersion` the value is different from the original commit id that git hub provided. 

I followed the instructions here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by moswald** [comment]
On a pull request, Azure DevOps does not build the exact version of the code that you pushed, but rather a version merged with your target branch; I suspect that is the commit id that you are getting. When the PR is completed this is the same commit id you will see in your tree, assuming the target branch pointer has not advanced. Assigning @madhurig to confirm/close.

**Comment by BoazWarshawsky** [comment]
@moswald I solved the issue by using `$(system.pullRequest.sourceCommitId)`,
Can you also confirm that it's the right way?

**Comment by moswald** [comment]
Yes, thank you for reminding me. That is the correct alternative for this scenario. I'm going to close this.

**Comment by gaziqbal** [comment]
Is "system.pullRequest.sourceCommitId" officially supported? I do not see it documented.

**Comment by moswald** [comment]
Yes, I can confirm it is officially supported. I'm not sure why it's not in the documentation. I'll file a bug.

**Comment by akshayamathi** [comment]
Build.sourceversionmessage is no longer working, can anyone tell me if there is any alternative to get the commit messages in the azure?
