### ISSUE TITLE
Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/***, Basic realm="https://pkgsprodscussu1.app.pkgs.visualstudio.com/", TFS-Federated

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/azure-pipelines-tasks#9807]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    https://microsoft.visualstudio.com/Xbox.Ambassadors/_build/results?buildId=14821855

- Agent - Hosted or Private: 
    
Hosted VS2017

## Issue Description

This message started coming today and failing the build during npm install.

Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/***, Basic realm="https://pkgsprodscussu1.app.pkgs.visualstudio.com/", TFS-Federated

### Task logs
[log_8_14821810.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2956759/log_8_14821810.zip)

**Comment by jrmcdona** [comment]
had an expired npmrc token

**Comment by Ruud-cb** [comment]
Similar solution, I just copied the entire text after clicking on "Generate npm credentials", without looking at the actual text.

**Comment by himmatsolanki** [comment]
This happens if password recently expired or changed, will need to create new PAT, convert to base64 and update in your npmrc file. Detailed documentation is here https://docs.microsoft.com/en-gb/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#set-up-authentication-on-your-dev-box

**Comment by vasilevach** [comment]
Hi, already updated the PAT, still 401. Is there another issue that might cause that?

**Comment by merken** [comment]
Generated a new token using the **correct feed** name did the trick for me (macOS)

In DevOps the feed URI seems incorrect, it includes the view name in the URI:
pkgs.dev.azure.com/mydevops/_packaging/**MyNodeFeed%40MyView**/npm/:email=myemail

The correct URI should be :
pkgs.dev.azure.com/mydevops/_packaging/**MyNodeFeed**/npm/:email=myemail

After changing this in the proposed user .npmrc, generating the base64 PAT and pasting the base64 string into the .npmrc file, it worked.

**Comment by DavidKlempfner** [comment]
This fixed it for me:
_Use npm install --registry https://registry.npmjs.org instead of npm install_

https://stackoverflow.com/a/62875329/2063755

**Comment by mySYSMON** [comment]
**This is how I fixed it.**
vsts-npm-auth -config .npmrc -r -f -v normal

**Comment by wh1t3h47** [comment]
The same issue happened with me, even after following the official instructions in artifacts > npm (for linux)
Turned out that if I replace the URL inside ;begin auth token; to match the same one as `registry=https:(url)`, it works

**Comment by felipeLeao18** [comment]
> This fixed it for me: _Use npm install --registry https://registry.npmjs.org instead of npm install_
> 
> https://stackoverflow.com/a/62875329/2063755

Thanks a lot. Your solution was the only one that solved the issue for me.

**Comment by kamodoc** [comment]
> **This is how I fixed it.** vsts-npm-auth -config .npmrc -r -f -v normal

This fixed my issue.!

**Comment by Homainc** [comment]
**MacOS**: My problem was that I've configured only one registry in `~/.npmrc`, but project's `.npmrc` has 3 of them, when I added credentials for all registries the error disappeared.
