### ISSUE TITLE
OpenIdConnect and Jwt Authentication on Invoke REST API Task

### ISSUE THREAD

**Issue by armanik11** [microsoft/azure-pipelines-tasks#9813]
We have API endpoints (.NET Core) where some use OpenIdConnect authentication scheme and some use JwtBearer auth scheme.

Is it possible to have an Invoke REST API task to test these endpoints? What kinds of authentications are supported as part of this task?

**Comment by bansalaseem** [comment]
It should work with all the authentications that service endpoint supports? See this [example task/endpoint ]((https://github.com/Microsoft/azure-pipelines-extensions/commit/abfa9e9da8c3b42a08026ef72b9346d442949a97))for how you can use different auth scheme.

**Comment by armanik11** [comment]
Thanks @bansalaseem. Did you intend to share the example task? I don't see any links.

**Comment by bansalaseem** [comment]
Sorry. I missed it. See [this](https://github.com/Microsoft/azure-pipelines-extensions/blob/master/Extensions/SampleTask/Src/vss-extension.json) for endpoint and [this](https://github.com/Microsoft/azure-pipelines-extensions/blob/master/Extensions/SampleTask/Src/Tasks/query-task/task.json) for how to use the endpoint in a custom task based on httpHandler.

**Comment by bansalaseem** [comment]
Closing it as there is no further action required on it.
