### ISSUE TITLE
Visual Studio Test running in parallel on multiple agents takes longer than not running parallel

### ISSUE THREAD

**Issue by MattDavisRM** [Microsoft/azure-pipelines-tasks#9822]
## Environment
On-Premise, Azure DevOps Server RC2
    
Private Agent, Windows Server 2016 Standard, 2.141.1

## Issue Description

I have 1,931 tests captured across 16 assemblies.  Using nUnit.  When I execute configured for a single agent, the Test step takes 7m 32s.  When I tried configuring the job to be multi-agent instead leveraging a max 3 agents, each of the individual spawned jobs take 8m6s, 8m7s, 7m36s.  Am I configuring something wrong here?  I was really not expecting it to take **more** time to execute the tests by executing in parallel.

**Comment by cltshivash** [comment]
@MattDavisRM : Can you please share the logs for the run that was done ?

**Comment by ShreyasRmsft** [comment]
Please set system.debug = true and share the entire set of logs you get (the full zip that gets downloaded when you click download all logs)

**Comment by ShreyasRmsft** [comment]
@MattDavisRM closing due to no-response, please re-open with the requested logs. Thanks
