### ISSUE TITLE
Azure App Service Deploy: Error: Ip Forbidden (CODE: 403)

### ISSUE THREAD

**Issue by renanlq** [Microsoft/azure-pipelines-tasks#9836]
## Troubleshooting
Check out how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting - done

## Environment
- Server - Azure Pipelines  
    - wizsolucoes, squadempregadocaixa, portalvue CD/release-72.

- Agent - Hosted: 
    - Agent job, pool: Hosted Ubuntu 1604

## Issue Description
I'm not able to deploy an app in our Linux App Service (PremiumV2: 1 Small), due to a 403 error on Kudu service. I've tried to add a slot so that to deploy in this new resource, but I've got the same error message (below), with and without slot deployment. Our last success deploy was on March 11.
![image](https://user-images.githubusercontent.com/15347353/54375112-3239d880-465f-11e9-9561-c6aea70c37ad.png)

I've checked our service connection, and it is working fine in UAT environment, same subscription but different resource group. See below:
![image](https://user-images.githubusercontent.com/15347353/54375004-fc94ef80-465e-11e9-875a-27cd2c112e3d.png)

Additionally, sooner I was facing an issue when accessing the SCM portal (Error 403 - this web app is stopped), but after creating a slot, Kudu portal was accessible again.
![image](https://user-images.githubusercontent.com/15347353/54377680-68c62200-4664-11e9-9c57-bf916f16b127.png)

### Task logs
[task.log](https://github.com/Microsoft/azure-pipelines-tasks/files/2967538/task.log)

### Error logs
![image](https://user-images.githubusercontent.com/15347353/54380871-37048980-466b-11e9-9d34-0c436452dc37.png)
* error.log is empty; and
* .error.log.swp and .error.log.swp.sap are hidden.

### Version
Task: Azure App Service Deploy
Version: 4.3.20

**Comment by vincentdass** [comment]
@renanlq , as the issue is related to `Kudu API` failures, I recommend you to post the issue [here](https://github.com/projectkudu/kudu/issues).

**Comment by renanlq** [comment]
@vincentdass, sorry for it, I was thinking about witch correct repo.
Thanks

**Comment by saikiranmandhala** [comment]
@vincent1173 this isn't only related to Kudu API, I can see this is also related to pipelines
