### ISSUE TITLE
CopyFiles Task trys to login using  agent service account even when providing a username/password

### ISSUE THREAD

**Issue by prestonr83** [Microsoft/azure-pipelines-tasks#9849]
## Troubleshooting
Run a job with  CopyFiles Task and input proper username and password. The task will finish successfully. Check the eventlog of the destition system and you will see failed login attempts from the ADO agent using the agent's service account.

## Environment
- Server - Azure Pipelines 
    
- Agent - Hosted Server 2016

## Issue Description

CopyFiles task tries to login using agent service account before using the provided username and password in the task. This doesn't cause the task to fail but causes failed login attempts to be logged on the destination system. This is tripping our OMS alerts for failed logins.

**Comment by niadak** [comment]
@prestonr83, Can you please share the debug log of the task? Please share task name and version you are using in the pipeline.

**Comment by niadak** [comment]
@prestonr83, Can you share the task name and version you are using in the pipeline?

**Comment by niadak** [comment]
@prestonr83 , I am closing the issue for now. Please feel free to reopen with sufficient data (debug log) if you are still facing the issue.
