### ISSUE TITLE
Azure Powershell - Calling Function of another Powershell script.

### ISSUE THREAD

**Issue by nreddipalle** [Microsoft/azure-pipelines-tasks#9854]
## Troubleshooting
I am trying to call a function that exists in another PowerShell and unable to figure out the syntax.
## Environment
Azure Pipelines
- Agent - Hosted or Private:     
 - Microsoft Windows Agent

## Issue Description
Azure PowerShell task
Trying to call this PS Script 
https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/helpers/GenerateResourcesAndImage.ps1
passing **GenerateResourcesAndImage** -SubscriptionId {YourSubscriptionId} -ResourceGroupName "shsamytest1" -ImageGenerationRepositoryRoot "C:\azure-pipelines-image-generation" -ImageType Ubuntu1604 -AzureLocation "East US"

passing GenerateResourcesAndImage which is a function in GenerateResourcesAndImage.ps1 as argument did not help.. Please help in understanding the right format.

**Comment by niadak** [comment]
@nreddipalle , Can you update the PS Script file to take the inputs? You can define the functions in another co-located file and load that file in the main PS script.

Example: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCloudPowerShellDeploymentV1/Publish-AzureCloudDeployment.ps1
