### ISSUE TITLE
Helm --wait   - does NOT wait

### ISSUE THREAD

**Issue by cforce** [microsoft/azure-pipelines-tasks#9862]
Hel does not wait for ALL pods to be healthy.
There was a bug once upon a time in helm, that should be fixed in combication of
AKS standard tiller/ azure devops helm client and used yml shema.
See https://github.com/helm/helm/issues/3173

**Comment by cforce** [comment]
https://github.com/helm/helm/issues/4210

**Comment by bansalaseem** [comment]
@ds-ms can you please look into it today?

**Comment by ds-ms** [comment]
@cforce I tried with a pipeline where I'm using a helm installer to install the latest stable version, i.e. `v2.14.0` and it seems to be waiting till the pods are in a ready state. 

PS: There's a helm installer task which you can use to upgrade the default version on the machine. The current default version on the machines available in the hosted pools is `v2.11.0`. You need to raise issues on this repo: [Microsoft/azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation) for issues related to default versions of tools available on your hosted agents.

**Comment by ds-ms** [comment]
@cforce closing this issue. Feel free to re-open it, if this wasn't the fix you were anticipating.
