### ISSUE TITLE
Publish Code Coverage coverlet and reportgenerator cobertura: No code coverage results were found to publish.

### ISSUE THREAD

**Issue by dwilsonbst** [Microsoft/azure-pipelines-tasks#9865]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Azure Pipelines
Organization: bstglobal
account: dwilson@bstglobal.com
project: BSTWEB
Build Definition: "BSTGlobal.CQRS" Build Number: 0.4.19, Build ID: 646

- Agent - Hosted or Private: 
    
 Hosted VS2017

## Issue Description

Publish code coverage fails with "No Code Coverage Results were found to publish." even when file was found in logs. This is related to [issue 9569](https://github.com/Microsoft/azure-pipelines-tasks/issues/9569). 

I'm using coverlet NuGet package "coverlet.msbuild" version "2.6.0" to generate Cobertura output, then trying to use reportgenerator version 4.0.15 (latest version with the schema fix). 

If I read in the coverlet output or the reportgenerator output, I get the same error.

[reportgenerator output](https://github.com/Microsoft/azure-pipelines-tasks/files/2979361/drop.2.zip)

### Task logs

[log_12_643.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2979194/log_12_643.zip)

### Error logs

`##[debug]Found 1 result(s) matching pattern: D:\a\1\s/coverlet/raw/BSTGlobal.CQRS.Implementation.UnitTests/netcoreapp2.1/coverage.cobertura.xml
##[debug]Reading XML file: D:\a\1\s\coverlet\raw\BSTGlobal.CQRS.Implementation.UnitTests\netcoreapp2.1\coverage.cobertura.xml
##[debug]Converting XML file to JSON
##[debug]task result: Failed
##[error]No code coverage results were found to publish.
##[debug]Processed: ##vso[task.issue type=error;]No code coverage results were found to publish.
##[debug]Processed: ##vso[task.complete result=Failed;]No code coverage results were found to publish.`

`##[debug]Found 1 result(s) matching pattern: D:\a\1\s/coveragereport/Cobertura.xml
##[debug]Reading XML file: D:\a\1\s\coveragereport\Cobertura.xml
##[debug]Converting XML file to JSON
##[debug]task result: Failed
##[error]No code coverage results were found to publish.
##[debug]Processed: ##vso[task.issue type=error;]No code coverage results were found to publish.
##[debug]Processed: ##vso[task.complete result=Failed;]No code coverage results were found to publish.`

**Comment by karanjitsingh** [comment]
@dwilsonbst, from your logs, it seems that you've selected jacoco as your coverage format (or used the default value)

![image](https://user-images.githubusercontent.com/4632805/56502534-3bf10e80-6530-11e9-86ba-ed8da5a39007.png)

You need to specify Cobertura as your coverage format.

**Comment by chrisdeely** [comment]
I'm encountering the same issue using Karma / Jasmine / Istanbul.

```
##[debug]codeCoverageTool=Cobertura
##[debug]summaryFileLocation=D:\a\1\s/coverage/cobertura-coverage.xml
...
##[debug]Resolved summary file: D:\a\1\s\coverage\cobertura-coverage.xml
...
##[debug]task result: Failed
##[error]No code coverage results were found to publish.

```

Is there a way to access the `cobertura-coverage.xml` file from the build agent to validate the contents?

<details>
  <summary>Here are the full debug logs for the task</summary>

```
##[debug]Evaluating condition for step: 'Publish code coverage from $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
##[debug]Evaluating: succeededOrFailed()
##[debug]Evaluating succeededOrFailed:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Publish code coverage from $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
==============================================================================
Task         : Publish Code Coverage Results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.150.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=626485)
==============================================================================
##[debug]agent.TempDirectory=D:\a\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_CODECOVERAGETOOL
##[debug]loading INPUT_FAILIFCOVERAGEEMPTY
##[debug]loading INPUT_SUMMARYFILELOCATION
##[debug]loaded 6
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]agent.workFolder=D:\a
##[debug]loading inputs and endpoints
##[debug]loaded 0
##[debug]check path : D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.150.3\task.json
##[debug]adding resource file: D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.150.3\task.json
##[debug]system.culture=en-US
##[debug]codeCoverageTool=Cobertura
##[debug]summaryFileLocation=D:\a\1\s/coverage/cobertura-coverage.xml
##[debug]reportDirectory=null
##[debug]additionalCodeCoverageFiles=null
##[debug]failIfCoverageEmpty=true
##[debug]System.DefaultWorkingDirectory=D:\a\1\s
##[debug]disable.coverage.autogenerate=undefined
##[debug]defaultRoot: 'D:\a\1\s'
##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
##[debug]findOptions.followSpecifiedSymbolicLink: 'false'
##[debug]findOptions.followSymbolicLinks: 'false'
##[debug]matchOptions.debug: 'false'
##[debug]matchOptions.nobrace: 'true'
##[debug]matchOptions.noglobstar: 'false'
##[debug]matchOptions.dot: 'true'
##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'true'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: 'D:\a\1\s/coverage/cobertura-coverage.xml'
##[debug]findPath: 'D:\a\1\s\coverage\cobertura-coverage.xml'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]1 matches
##[debug]1 final results
##[debug]Found 1 result(s) matching pattern: D:\a\1\s/coverage/cobertura-coverage.xml
##[debug]Resolved summary file: D:\a\1\s\coverage\cobertura-coverage.xml
##[debug]Reading XML file: D:\a\1\s\coverage\cobertura-coverage.xml
##[debug]Converting XML file to JSON
##[debug]task result: Failed
##[error]No code coverage results were found to publish.
##[debug]Processed: ##vso[task.issue type=error;]No code coverage results were found to publish.
##[debug]Processed: ##vso[task.complete result=Failed;]No code coverage results were found to publish.
##[section]Finishing: Publish code coverage from $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
```
</details>

**Comment by karanjitsingh** [comment]
@chrisdeely, the cobertura file should be uploaded as build artifact, you can download the artifacts from the build timeline.

**Comment by chrisdeely** [comment]
Thanks, @karanjitsingh , I was able to download the coverage file and found that it was in fact empty. I have confirmed that the build steps work properly when run locally, so I'm thinking this is more of an issue with settings in my Azure Pipeline than this task itself.

My guess is a bad path somewhere, but the tests themselves run perfectly and produce detailed reports. 
Any hints would be very welcome!

```xml
<?xml version="1.0" ?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage lines-valid="0" lines-covered="0" line-rate="NaN" branches-valid="0" branches-covered="0" branch-rate="NaN" timestamp="1556222564185" complexity="0" version="0.1">
  <sources>
    <source>D:\a\1\s</source>
  </sources>
  <packages>
  </packages>
</coverage>
```
