### ISSUE TITLE
Add support for single release notes file in Github release task 

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/azure-pipelines-tasks#9869]
## Environment
- Server - Azure Pipelines
    - account name: **vscode-webdiag-extensions**
    - team project name: **VS Code WebDiag extensions**
    - build definition name: **vscode-react-native** (under release pipeline)
    - build number: **73** (under release pipeline)

- Agent - Hosted 
    - agent queue name: Hosted VS2017

## Issue Description
We use Azure Pipelines for automating releases to Github for the following VS Code extensions:
https://github.com/Microsoft/vscode-react-native 
https://github.com/Microsoft/vscode-cordova
Currently, [Github Release task](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) supports one release notes file per version or inline release notes. In our case we use one single `CHANGELOG.md` file where we reflects release notes for each new version using such format:

```
## 1.0.0

some release notes for 1.0.0

## 0.9.5

some release notes for 0.9.5

## 0.9.4

some release notes for 0.9.4

...
etc
```

So, in order to collect release notes during the build we had to make a node js script that takes needed release notes out of this file and then save the result to the temporary release notes file which we use for the task. 
It would be better if task could support our case so we could get rid of this script and use just the task.

**Comment by raiyanalam** [comment]
Thanks Ruslan. This request makes sense. To elaborate a little - the changelog file is checked into your repository and it contains the release notes for all the past releases and the current one. You would want the task to extract the release notes only for the latest release and add it to the release notes section of the github release. In your example, the contents from ## 1.0.1 till the beginning of ## 0.9.5 should be extracted. 
I will add this request to our backlogs.

**Comment by ruslan-bikkinin** [comment]
@raiyanalam yes, this is exactly what we want 👍

**Comment by ruslan-bikkinin** [comment]
Hi @raiyanalam could you please clarify what is the reason of closing this?

**Comment by raiyanalam** [comment]
Hi @ruslan-bikkinin ,
  We have accepted this feature request and added to our internal backlogs. We will be tracking it from there.

**Comment by ruslan-bikkinin** [comment]
@raiyanalam got it, thanks!
