### ISSUE TITLE
Windows Machine File Copy raises 'Multiple connections to a server or shared resource by the same user'

### ISSUE THREAD

**Issue by ferarias** [Microsoft/azure-pipelines-tasks#9872]
## Troubleshooting
I'm using a Release Pipeline on custom servers and I'm getting the following error:

> Failed to Create PSDrive with Destination: '\\LOGVIPREWEB02V\D$\WEB\ACME\Back\Home', ErrorMessage: 'Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again'
> Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again

The pipeline has just two tasks. One Powershell with a Invoke-RestMethod task and a Windows Machine File Copy task

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - I'm using private agent, Windows server 2012 R2. Agent version is 2.148.1. 
    

## Issue Description

- Windows Machine File Copy version is 2.1.9

### Task logs

These are the relevant parts of the log

> 2019-03-19T15:53:49.2526213Z ##[debug]Entering script RobocopyJob.ps1
> 2019-03-19T15:53:49.2526381Z ##[debug]fqdn = LOGVIPREWEB02V
> 2019-03-19T15:53:49.2526534Z ##[debug]sourcePath = C:\agent\_work\r194\a\_back-ngwa-root.master-CI\drop\dev\dist\bangular
> 2019-03-19T15:53:49.2526707Z ##[debug]targetPath = D:\WEB\ACME\Back\Home
> 2019-03-19T15:53:49.2526861Z ##[debug]credential = System.Net.NetworkCredential
> 2019-03-19T15:53:49.2527028Z ##[debug]cleanTargetBeforeCopy = false
> 2019-03-19T15:53:49.2527182Z ##[debug]additionalArguments = 
> 2019-03-19T15:53:49.2527359Z ##[debug]machine share= \\LOGVIPREWEB02V
> 2019-03-19T15:53:49.2527532Z ##[debug]destination network path= \\LOGVIPREWEB02V\D$\WEB\Logitravel\Back\Home
> 2019-03-19T15:53:49.2527699Z ##[debug]Creating path to directory: \\LOGVIPREWEB02V\D$\WEB\Logitravel\Back\Home
> 2019-03-19T15:53:49.2917436Z ##[debug]Caught exception: Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.Exception.Message
> 2019-03-19T15:53:49.2959753Z ##[debug]Check if parent path exists: \\LOGVIPREWEB02V\D$\WEB\Logitravel\Back
> 2019-03-19T15:53:49.3330151Z ##[debug]Caught exception: Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.Exception.Message
> 2019-03-19T15:53:49.3350207Z ##[debug]Check if parent path exists: \\LOGVIPREWEB02V\D$\WEB\Logitravel
> 2019-03-19T15:53:49.3715707Z ##[debug]Caught exception: Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.Exception.Message
> 2019-03-19T15:53:49.3735013Z ##[debug]Check if parent path exists: \\LOGVIPREWEB02V\D$\WEB
> 2019-03-19T15:53:49.4100490Z ##[debug]Caught exception: Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.Exception.Message
> 2019-03-19T15:53:49.4122159Z ##[debug]Check if parent path exists: \\LOGVIPREWEB02V\D$
> 2019-03-19T15:53:49.4498358Z ##[debug]Caught exception: Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.Exception.Message
> 2019-03-19T15:53:49.4562758Z ##[debug]Check if root path exists: \\logvipreweb02v
> 2019-03-19T15:53:49.4620052Z ##[debug]Caught exception: Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.Exception.Message
> 2019-03-19T15:53:49.4638566Z ##[debug]Check if parent path exists: 
> 2019-03-19T15:53:49.5317170Z ##[error]Failed to Create PSDrive with Destination: '\\LOGVIPREWEB02V\D$\WEB\Logitravel\Back\Home', ErrorMessage: 'Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again'
> 2019-03-19T15:53:49.5325824Z ##[debug]Processed: ##vso[task.logissue code=WFC_FailedToCreatePSDrive;type=error]Failed to Create PSDrive with Destination: '\\LOGVIPREWEB02V\D$\WEB\Logitravel\Back\Home', ErrorMessage: 'Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again'
> 2019-03-19T15:53:49.5326676Z ##[debug]System.ComponentModel.Win32Exception (0x80004005): Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again
> 2019-03-19T15:53:49.5347306Z ##[debug]Leaving C:\agent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.9\WindowsMachineFileCopy.ps1.
> 2019-03-19T15:53:49.5389022Z ##[debug]Caught exception from task script.
> 2019-03-19T15:53:49.5418543Z ##[debug]Error record:
> 2019-03-19T15:53:49.5964057Z ##[debug]New-PSDrive : Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again
> 2019-03-19T15:53:49.5975073Z ##[debug]At C:\agent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.9\RoboCopyJob.ps1:224 char:13
> 2019-03-19T15:53:49.5987268Z ##[debug]+             New-PSDrive -Name "WFCPSDrive" -PSProvider FileSystem -Ro ...
> 2019-03-19T15:53:49.5998876Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2019-03-19T15:53:49.6012954Z ##[debug]    + CategoryInfo          : InvalidOperation: (WFCPSDrive:PSDriveInfo) [New-    PSDrive], Win32Exception
> 2019-03-19T15:53:49.6026361Z ##[debug]    + FullyQualifiedErrorId : CouldNotMapNetworkDrive,Microsoft.PowerShell.Com    mands.NewPSDriveCommand
> 2019-03-19T15:53:49.6040327Z ##[debug] 
> 2019-03-19T15:53:49.6060784Z ##[debug]Script stack trace:
> 2019-03-19T15:53:49.6100123Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.9\RoboCopyJob.ps1: line 224
> 2019-03-19T15:53:49.6116335Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.1.9\WindowsMachineFileCopy.ps1: line 55
> 2019-03-19T15:53:49.6131303Z ##[debug]at <ScriptBlock>, <No file>: line 1
> 2019-03-19T15:53:49.6142701Z ##[debug]at <ScriptBlock>, <No file>: line 22
> 2019-03-19T15:53:49.6157059Z ##[debug]at <ScriptBlock>, <No file>: line 18
> 2019-03-19T15:53:49.6168051Z ##[debug]at <ScriptBlock>, <No file>: line 1
> 2019-03-19T15:53:49.6186016Z ##[debug]Exception:
> 2019-03-19T15:53:49.6205238Z ##[debug]System.ComponentModel.Win32Exception (0x80004005): Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again
> 2019-03-19T15:53:49.6227704Z ##[error]Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again
> 2019-03-19T15:53:49.6228566Z ##[debug]Processed: ##vso[task.logissue type=error]Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again
> 2019-03-19T15:53:49.6234950Z ##[debug]Processed: ##vso[task.complete result=Failed]
> 2019-03-19T15:53:49.6611467Z ##[section]Finishing: Copy files from $(System.DefaultWorkingDirectory)/_back-ngwa-root.master-CI/drop/dev/dist/bangular
> 

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by niadak** [comment]
@ferarias , Can you please restart the target machine once and try? Seems like some old connection is still active which is causing the issue.

**Comment by ferarias** [comment]
I have tried to add a NET USE command just before the Copy task. There were no active connections. Will try to restart just in case.

**Comment by ferarias** [comment]
After reboot the task ran fine. Second time also ran ok.
We can close the issue. If we find further problems we will open it again.
Thanks a lot for your kind help.
