### ISSUE TITLE
Multi agent Test fails with Public repo with GitHub PR Trigger 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/azure-pipelines-tasks#9879]
## Azure Pipeline 
**accountname:** durabletaskframework
**team project name:** Durable Task Framework CI
**build definition:** Build & Run Tests

## Issue Description
We have a public GitHub repo. We create a pipeline with public project, for enabling PR Trigger for the contributors. However, it didn't work for multi-agent parallel testing. If we manually trig it, it works perfectly fine.  According to the error, it seems lack of permission for anonymous users. 
However, our build pipeline takes long time without multi-agents. 
```
Unhandled exception ocurred: System.AggregateException: One or more errors occurred. ---> Microsoft.TeamFoundation.Test.WebApi.TestExecutionAccessDeniedException: You do not have the appropriate permissions to manage test configurations in this team project.
```
I"ve got an answer from a guy. However, I struggled this issue to find out it is not possible now. So I'd like to share the fact. And I'll wait for an update. :) 

@ShreyasRmsft answered me at this PR.
https://github.com/Azure/durabletask/pull/261

@cgillum
@dtzar

**Comment by ShreyasRmsft** [comment]
@TsuyoshiUshio will keep you posted.

**Comment by TsuyoshiUshio** [comment]
Thank you! :)

**Comment by prawalagarwal** [comment]
@TsuyoshiUshio This issue was fixed. Can you verify if this is resolved for you?

**Comment by TsuyoshiUshio** [comment]
Wow! Great. I'll try it.

**Comment by prawalagarwal** [comment]
Closing this. Please reopen if you are still facing this.
