### ISSUE TITLE
Visual Studio Test can't find tests when I add .Net Core project

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/azure-pipelines-tasks#9880]
## Azure Pipeline 
**accountname:** durabletaskframework
**team project name:** Durable Task Framework CI
**build definition:** Build & Run Tests-singleexp

## Issue Description
We have a Solution which include both several project for  net451 and netstandard2.0.  It works fine. However, once I add .NetCore project on the solution, it suddenly can not find my tests. 
I eventually change the .NetCore project into net451 project.  The problem has gone. I'd like to know why it happens. I don't want to use net451.  Instead, I'd like to use netstandard2.0 or .net core with Multi agent test running parallel.  Also, I'd like to know why it happens for my learning.

## Error 

```

Test run is aborted. Logging details of the run logs.

New test run created.

Test discovery started.

Test Run Discovery Aborted . Test run id : 1000120

Unexpected error occurred during test execution. Try again.

Error : No test is available in d:\a\1\s\Test\DurableTask.AzureStorage.Tests\bin\Debug\net451\DurableTask.AzureStorage.Tests.dll d:\a\1\s\Test\DurableTask.AzureStorage.Tests\bin\Debug\net451\DurableTask.Core.Tests.dll d:\a\1\s\Test\DurableTask.Core.Tests\bin\Debug\net451\DurableTask.Core.Tests.dll d:\a\1\s\Test\DurableTask.Emulator.Tests\bin\Debug\net451\DurableTask.Emulator.Tests.dll d:\a\1\s\Test\DurableTask.ServiceBus.Tests\bin\Debug\net451\DurableTask.Core.Tests.dll d:\a\1\s\Test\DurableTask.ServiceBus.Tests\bin\Debug\net451\DurableTask.ServiceBus.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Test run aborted. Test run id: 1000120

System.Exception: The test run was aborted, failing the task.
```

**Comment by cltshivash** [comment]
@TsuyoshiUshio : Can you share the logs when the issue happens (please run with System.debug set to true to get the test platform logs) ?

**Comment by TsuyoshiUshio** [comment]
Hi @caltseng ,  Thank you for the comment. Attached is the one. 

[17.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2989300/17.txt)

**Comment by ShreyasRmsft** [comment]
@TsuyoshiUshio please upload the full zip that you get. There are additional logs in there that we need. Thanks. Also is this a github project? If so can you please share the repo url or a sample stripped down solution where this repro's?

**Comment by TsuyoshiUshio** [comment]
[logs_145.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2993136/logs_145.zip)

Thank you, see attached. This branch. 
https://github.com/TsuyoshiUshio/durabletask/commits/correlation/refactor

I already fix this to change from .NetCore to net451. However, you can use this commit hash
0a80b185a2cfa0f5584def9f126e28ab719bc5af

**Comment by ShreyasRmsft** [comment]
@TsuyoshiUshio as of today we do not support running Full .Net and dotnetcore tests in the same session. You will have to split them up in to 2 vstest task instances.

**Comment by TsuyoshiUshio** [comment]
@ShreyasRmsft Good to know. Thank you very much.

**Comment by alexey-gusarov** [comment]
Simular issue https://github.com/microsoft/vstest/issues/2310
