### ISSUE TITLE
Xamarin Android Application hangs on splash screen when build with Azure Pipeline

### ISSUE THREAD

**Issue by ngalicoco** [microsoft/azure-pipelines-tasks#9893]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Build Android and  Android Signing

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines  
- Agent - Hosted VS2017

## Issue Description
We are trying to automate deployments to google play store for which we need to build in production configuration, which is one of the build configuration set for Android project.
The build is not failing, but when installed on a device, application hangs splash screen when build Azure Pipeline with Xamarin Build task and Android signing. But when the project is archived using Visual Studio archive tool in the same production configuration it installs and runs fine on the same device. Interestingly when the same build pipeline is used to generate APK and publish to app center works perfectly. Please help us

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by draconastar** [comment]
I am having the same issue, though the .apk that my build pipeline deploys to our AppCenter page also freezes on the splash screen.  There are no errors during build, and using the Archive feature in Visual Studio on the same branch produces a working .apk that doesn't freeze.

**Comment by draconastar** [comment]
Any updates on this?  We're still unable to successfully build our Xamarin app through Azure.

**Comment by nickwhyte** [comment]
I was able to solve this by enabling Zipalign in the Android signing task. I don't know why this worked for my build, but it fixed the splash screen freeze and the app seems to run well.

**Comment by madhurig** [comment]
@nickwhyte - thanks for sharing your solution. @draconastar - can you check if this works for you please?

**Comment by madhurig** [comment]
Closing since we don't think this is an issue with the Xamarin Android task. If zipalign doesn't help, please let us know.

**Comment by zachgreencbt** [comment]
> Any updates on this? We're still unable to successfully build our Xamarin app through Azure.

Did you ever find a resolution? I am having this same problem, but I do have zipalign enabled.

**Comment by keerthinathganjam** [comment]
Thanks , was facing the same issue, after changing zipalign: true started working
