### ISSUE TITLE
GitHubRelease@0 Task Doesn't Encode URLs Correctly When Appending ChangeLog

### ISSUE THREAD

**Issue by seesharprun** [microsoft/azure-pipelines-tasks#9907]
## Required Information

**Bug**

*Task*: GitHubRelease@0

## Environment

- Server - Azure Pipelines 
- Agent - Hosted Ubuntu 16.04

## Issue Description

If you set the ``addChangeLog`` parameter to true, it will generate a hyperlink letting you know that the list of changes were **auto generated**. Unfortunately, if your Azure DevOps project name has invalid URL characters, they are not correctly encoded.

### Repro Example

1. Create a new Azure DevOps project with a space in the name. In my example, my project is named **Learning Builds**
1. Create a new Pipeline build that uses the GitHub Releases task to **add** a new release and automatically generate the changelog
2. Observe that the Markdown used for the automatically generated changelog does not encode the project name correctly effectively breaking the Markdown hyperlink.

**Comment by TheLayman** [comment]
Issue fixed with this PR #10770.
