### ISSUE TITLE
AzureRmWebAppDeployment should not overwrite Startup File set in Azure

### ISSUE THREAD

**Issue by Leon99** [microsoft/azure-pipelines-tasks#9913]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeploymentV4

Currently, AzureRmWebAppDeployment overwrites **Stack** and **Startup File** even if they are not set in the task. It manages to guess Stack right, but not Startup File. Therefore, it's impossible to avoid entering it in the task since it puts empty value in the web app, which, obviously, breaks it. To me, it makes more sense to specify those in Azure then in the deployment task, since they are the same with every deployment to a particular web app.

**Comment by SumiranAgg** [comment]
@Leon99 Thanks for reporting this. We are aware of this behavior. This was done to allow user to remove startup command if need be.
@RoopeshNair What are your thoughts on this? If the field is left empty should we clear the startup config setting or keep the original one?

**Comment by Leon99** [comment]
I'm really surprised (and confused) that this behaviour is by design.
Do you have a use case that would show that setting Stack/Startup File in the pipeline is preferred to setting it in Azure? Maybe I'm doing something wrong?
My main problem is that it forces me to do something via UI, which is slower and much harder to maintain than specifying it in my Terraform specs for the Azure resources. Not to mention that I don't see a point in configuring an Azure resource in the pipeline at all, especially kind of configuration that rarely, if ever, changes over time for a given resource.

**Comment by RoopeshNair** [comment]
@Leon99 Sorry for the issues. We will take a look

**Comment by SumiranAgg** [comment]
Added fic #10349

**Comment by Leon99** [comment]
@SumiranAgg Do I understand correctly that this has been fixed? If so, when can we expect this to be released?
