### ISSUE TITLE
Expose --include-symbols and --include-source in dotnet pack task

### ISSUE THREAD

**Issue by ryandle** [Microsoft/azure-pipelines-tasks#9924]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: feature

**Enter Task Name**:  DotNetCoreCLIV2 (pack)

## Issue Description

Expose --include-symbols and --include-source for the dotnet pack task.

A more general request is mentioned [here](https://github.com/Microsoft/azure-pipelines-tasks/issues/6567).

I plan to submit a PR for this.

**Comment by ryandle** [comment]
I decided to also address the other issue I mentioned above in this PR:

https://github.com/Microsoft/azure-pipelines-tasks/issues/6567

**Comment by jerickmsft** [comment]
@alexmullans I think this can be closed thanks(!) to @ryandle's contribution

**Comment by alexmullans** [comment]
Yep, thanks.
