### ISSUE TITLE
IIS Web App Manage Task: add configuration for authentication on IIS Web Application

### ISSUE THREAD

**Issue by schnitty** [microsoft/azure-pipelines-tasks#9928]
## Required Information
Type: Feature 
Task: IISWebAppManagement

## Environment
Azure Pipelines

## Issue Description

I'd like to be able to configure the IIS authentication for configuration type: IIS Web Application

The option is available for configuration type: IIS Website but is not available for IIS Web Application.

I've tried setting the authentication for the web application using the IIS website configuration type by tweaking the WebsiteName and PhysicalPath parameters but I can't get it to just set the authentication for just the web application.  It sets it for the parent website as well which is not what I want.

Is is possible to add the option to configure the authentication for the IIS Web Application so that is only sets the authentication for the web app and does not affect the parent website that the web application is under?

**Comment by niadak** [comment]
@schnitty , Thanks for reporting the issue. We dont have configure authentication support for application pool in the task. This can be taken as enhancement. We are open for contribution.

For now you can use additional App.cmd command option to configure authentication for application pool.

**Comment by schnitty** [comment]
This would be an enhancement yes.  Just in case there is any confusion this is for a Web Application, not for the Application Pool.

I want what appears in the image below but for WebApplication not WebSite

![image](https://user-images.githubusercontent.com/6099451/55203378-0734b480-521b-11e9-9911-4248dd4d4877.png)

I'm happy to contribute as I'm writing the PowerShell script and unit tests anyway although from looking at the code I'm not sure how I would enable the extra UI needed to indicate you want to configure authentication (checkbox) and then show the extra settings so set the values (basicAuth, windowsAut, etc) with the check boxes.

I've had a bit of a read through the documentation in the repo but aren't quite sure.  Is there some resource you can point me to that will help me work that out?

**Comment by niadak** [comment]
@schnitty You can refer to this [documentation ](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md#contributing)regarding how to contribute.

**Comment by niadak** [comment]
Closing the issue given that there is a workaround for the issue. We are open for external contribution here for the enhancement of the task.

**Comment by spSlaine** [comment]
There was no workaround for this issue!

**Comment by kmkumaran** [comment]
@nadesu / @chshrikh to review and follow-up.

**Comment by beardybok** [comment]
For those looking in the future, the "workaround" for this is to use appcmd, though these lines assume you want to use the currently set up Windows Auth Providers, and no other authentication schemes are enabled:

`C:\WINDOWS\system32\inetsrv\appcmd.exe set config "Your Web Site Name/Your App Name" -section:system.webServer/security/authentication/anonymousAuthentication /enabled:"False" /commit:apphost`

Output:

Applied configuration changes to section "system.webServer/security/authentication/anonymousAuthentication" for "MACHINE/WEBROOT/APPHOST/Your Web Site Name/Your App Name" at configuration commit path "MACHINE/WEBROOT/APPHOST"

`C:\WINDOWS\system32\inetsrv\appcmd.exe set config "Your Web Site Name/Your App Name" -section:system.webServer/security/authentication/windowsAuthentication /enabled:"True" /commit:apphost`

Output:

Applied configuration changes to section "system.webServer/security/authentication/windowsAuthentication" for "MACHINE/WEBROOT/APPHOST/Your Web Site Name/Your App Name" at configuration commit path "MACHINE/WEBROOT/APPHOST"
