### ISSUE TITLE
Disappearing TFS properties in VS unit test project

### ISSUE THREAD

**Issue by Viktoryath** [Microsoft/azure-pipelines-tasks#9929]
Hello,
The task is
VS-Test

## Environment
TFS 2019
Agent -  Private: 
OS Windows 7 Enterprise
Agent version 2.126.0

## Issue Description
After upgrading to TFS 2019 the following properties were disappeared from properties list of vs unit test project
__Tfs_TestCaseId__
__Tfs_TeamProject__
__Tfs_TfsServerCollectionUrl__
__Tfs_TestRunId__
__Tfs_TestPlanId__

 Without these properties we can't run our automated tests.
Thank you
Viktorya

**Comment by kaadhina** [comment]
Hi, is this same as https://github.com/Microsoft/testfx/issues/541
Can you please check the version as mentioned there?

**Comment by kaadhina** [comment]
Closing this. Please reopen if the above does not help.

**Comment by Viktoryath** [comment]
Hi kaadhina,

Unfortunately, the issue is not fixed. Please reopen...
We use VS 2017 with Test Project (4.5.2) and our upgraded TFS 2019
We added the following reference to MSTest.Testdapter and MSTest.TestFramework packages (1.4.0) according to the linked bug (541)

We use Test Plan/Cases to invoke our automated tests via Release pipeline. in our tests we use the properties:
- __Tfs_TestCaseId__
- __Tfs_TeamProject__
- __Tfs_ServerCollectionUrl__
- etc.

TFS Agent version is 2.147.1

but after the upgrade of TFS, the properties removed from TestContext.Properties list
In TFS 2018 it worked properly 

Please help,
Thanks!

**Comment by kaadhina** [comment]
Can you please attach debug logs?

**Comment by kaadhina** [comment]
Please reopen once u have the logs
