### ISSUE TITLE
AppCenterDistributeV3 only available SymbolsType option is Apple

### ISSUE THREAD

**Issue by rjschnorenberg** [microsoft/azure-pipelines-tasks#9939]
*Type*: Bug

**Enter Task Name**: AppCenterDistributeV3  

## Environment
- Azure Pipelines
    
- Agent - Hosted 

## Issue Description

The AppCenterDistributeV3 task has options hidden behind the SymbolsType being one of the following values (AndroidJava, AndroidNative, Apple, UWP, Windows) but currently only Apple is available in the list of SymbolsTypes.

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/AppCenterDistributeV3/task.json#L66

**Comment by maxua** [comment]
+1
