### ISSUE TITLE
Using a prefix for the Xcode command

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/azure-pipelines-tasks#9948]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Xcode  

## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 2018 Update 2
    
## Issue Description

When using sonar official plugin for objective-c, it is required to prefix the xcodebuild command with `build-wrapper-macosx-x86-64 --out-dir bw_output`, is it possible to achieve this with Xcode task (using the "specify" option for xcode version will not work) ?

**Comment by madhurig** [comment]
The Xcode task does not have that option. Please try using a [script](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml) in your pipeline.
