### ISSUE TITLE
Unable to add task to pipeline

### ISSUE THREAD

**Issue by neilpendlington** [Microsoft/azure-pipelines-tasks#9950]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Screen Resolution Utility 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
[edit: removed company info]

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows Server 2012 R2 (6.3.9600)

## Issue Description

I installed the extension within my organisation (Clicked the Get it Free button, then followed steps to install). The installation completed successfully and when trying to add the task to my build pipelilne the task doesn't show up in the Utilities list as per the marketplace screenshot. 
I search for the task and it shows up as "Installed", but I can not "Add" it.

[Include task name(s), screenshots and any other relevant details]
![resolution-extension](https://user-images.githubusercontent.com/40292251/55075213-54355100-508a-11e9-9be0-6608a0590075.jpg)

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by ShreyasRmsft** [comment]
@neilpendlington you might require administrator approval to get it added to the list of allowed extensions

**Comment by stephenmichaelf** [comment]
@neilpendlington Could you try adding the item above instead of below Marketplace:

![image](https://user-images.githubusercontent.com/450490/55231580-77cad980-51f9-11e9-80ea-c129963b4d15.png)

**Comment by neilpendlington** [comment]
@stephenmichaelf that did it! Can't believe how simple it was, and I equally can't believe that I didn't see the available task before. I'm 90% sure that it was only showing up in the marketplace! Must be cracking up...

**Comment by ShreyasRmsft** [comment]
@neilpendlington for it's worth, the screenshot you posted didn't seem to have the task listed in the Add tasks list. 

Maybe a refresh was required or it took time for it to reflect.
