### ISSUE TITLE
Help needed on the Azure VM scale set Deployment pipeline task custom error logging

### ISSUE THREAD

**Issue by vinothinidharmaraj** [Microsoft/azure-pipelines-tasks#9960]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Azure VM scale set Deployment

**Description:** 
Using Azure VM scale set deployment task  with custom script action to deploy my application to the vm scale set.  Im looking for the way to communicate the user (who triggers the deployment from VSTS) the cause for the failures if any because of the scripts (my custom script calls multiple scripts).

I could see the detail log information's(i.e. user logs ex. Write-Host "json contains empty data") in the vm instances under the **C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.*\Status** folder, is there any way to show those errors/logs on the release command prompt which will be available to download along with Release pipeline logs?

I have tried using ##vso[task.logissue type=error] seems like this is not working with Azure VM Scale set deployment task, i think its because the custom scripts runs on the servers.. 

Thanks in advance.

**Comment by vinothinidharmaraj** [comment]
Any update on this?

**Comment by issacnitin** [comment]
@vinothinidharmaraj Currently it's not supported to get logs and show them on the release logs console from within the task.
