### ISSUE TITLE
Gradle task only results in Succeeded or Failed

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [Microsoft/azure-pipelines-tasks#9961]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: gradle

list here (V# not needed):  V2
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Looking at the source for the grade task (https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/GradleV2) it seems as if the only possible results are TaskResult.Succeeded or TaskResult.Failed yet the Task SDK (https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/node/task.ts) show several other possible results. Is it not possible for a grade build using the grade task to result in one of those other results?

**Comment by madhurig** [comment]
Most tasks just report succeeded or failed. The platform will report cancelled and skipped if the task is cancelled or skipped due to other conditions in the pipeline setup. "Succeeded With Issues" is interesting in some cases for tasks to report. Do you have a scenario?

**Comment by Blackbaud-JasonBodnar** [comment]
Yes, I've written a gradle plugin that checks to see if the project has any dependencies that aren't using the latest version. I'd like to "turn the build yellow" if there are out of date dependencies. "Turn the build yellow" - meaning some kind of warning is shown but allow the build to continue. Seems like "Succeeded With Issues" would be what I'm looking for.

**Comment by madhurig** [comment]
A custom task seems like the way to go for your scenario. The Gradle task is a wrapper over gradle and unless there is a standard way to report such issues via Gradle, doing something custom for one plugin wouldn't work in a more generic task.

**Comment by Blackbaud-JasonBodnar** [comment]
Sure. Completely understand. I don't think there's a standard way to report different errors from Gradle.

Now, bash scripts have the ability to return different exit codes. I looked at the source for the bash task and it also only returns TaskResult.Succeeded or TaskResult.Failed. If it returned different results based on the exit code of the bash script I could run gradle from a script, handle the output and return an appropriate exit code. But, there would have to be some sort of standard established mapping bash exit codes to TaskResult values (ie, bash script returns 0, bash task returns TaskResult.Succeeded, bash script returns 1, bash task returns TaskResult.SucceededWithIssues, etc.)..

**Comment by madhurig** [comment]
We have found that "SucceededWithIssues" is very specific to the tool. Even with bash, not all scripts have a standard they adhere to. The option is provided in the task SDK and will help some custom tasks but most generic tasks don't use it.

**Comment by Blackbaud-JasonBodnar** [comment]
Certainly understand. Perhaps a future version of the Task SDK could provide a way for a child process (gradle, bash script) to communicate the task result back to the parent task process? My first thought is an environment variable. There are also some other alternatives mentioned here:

https://medium.freecodecamp.org/node-js-child-processes-everything-you-need-to-know-e69498fe970a
https://github.com/nodejs/help/issues/397

It seems kind of silly for me to write a custom task that's going to do everything the current gradle task or bash task does except for return a different task result. It doesn't look like the current gradle task or bash task are written in a way that they can be subclassed so I'd litterally be copying 90% of their code into my custom task.
