### ISSUE TITLE
[Question] Test Assembly lifecycle in VS Test Task

### ISSUE THREAD

**Issue by robinsedlaczek** [Microsoft/azure-pipelines-tasks#9967]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Visual Studio Test

## Environment
- Server - TFS on-premises
    - If using TFS on-premises, provide the version: 16.131.28507.4
- Agent - Private
    - Windows 10, Agent v2.148.2 

## Issue Description

We are using Selenium with MSTest unit test projects and run them with the Visual STudio Test task in on-prem TFS. We face some problems with web driver instances (those which are known resp. common in the community). In order to face some of them, we need some more information:

1. Is there a possibility to write message directly from a unit test to the log of the VS Test task, and so to the TFS release log?
2. How is the lifecycle of aa test assembly managed? Is a test assembly loaded per agent once a release executes a test task? Or is the test assembly loaded per test batch? To give some context: we try to reuse web drivers and to shut them down when the assembly is unloaded (resp the method marked with the AssemblyCleanup attribute is called). For troubleshooting it is important for us to know the lifecycle. 

Regarding both questions, please see the code below:

![AssemblyCleanup](https://user-images.githubusercontent.com/2900224/55187129-8208bb80-5198-11e9-85ed-8eedbb89d89d.png)

We like to see the messages written to the console in the TFS release log of each release.

Many thanks for help and tips in advance!

**Comment by kaadhina** [comment]
Hi,
1. For a failed test case, the console output will be available as a test case attachment. But for passed tests, we do not have any such feature.
2. The assembly will be loaded for every batch.

**Comment by robinsedlaczek** [comment]
Hi @kaadhina!

Great, many thx for your response!

1. Yes, so far so good. Known and clear.
2. Thx, helpful.

So there is absolutely no way to write to the log from own code?

**Comment by kaadhina** [comment]
I guess you can write to a file and upload it using https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext.addresultfile?view=mstest-net-1.2.0
I haven't tried this myself. But I think this should work.

**Comment by robinsedlaczek** [comment]
Yes, at least we can do this. Had that in mind already. So, many thanks again. Your answers were more helpful than those from the developer community this time.
