### ISSUE TITLE
AzureResourceGroupDeploymentV2 gets stuck turning RG on

### ISSUE THREAD

**Issue by PedroC88** [microsoft/azure-pipelines-tasks#9981]
**Question, Bug, or Feature?**
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeploymentV2

## Environment
- Azure Pipelines: account *NAGICO*, build definition *Pre-build QA*
- Hosted Agent: pool *Hosted*

## Issue Description

Hosted agent gets stuck when turning on resoure group with 1 VM. Debug prints the following infintely:

    [GET] https://management.azure.com/subscriptions/{subscription_url}
    Response status code : 200
    Response status : InProgress

If the VM is stopped from the Azure portal while this is looping, then the task comes out of the loop succesfully with the following message

    2019-03-29T19:11:46.6451723Z Operation: 'Start' succeeded on all the virtual machines.
    2019-03-29T19:11:46.6452497Z task result: Succeeded
    2019-03-29T19:11:46.6454266Z Processed: ##vso[task.complete result=Succeeded;]

This happens regardless of the VM being on or off. If the VM was off it will power on correctly, but the task doesn't realize, forcing me to having to stop it manually (so it comes out of the loop and reports a sucess) and restarting it.

See [task logs](https://github.com/Microsoft/azure-pipelines-tasks/files/3024369/6.txt) attached. 
### Update 1
I decided to run another test letting the build run indefinitely and the task eventually realized that the VM was on after 26 minutes.

**Comment by amaljg** [comment]
Thanks @PedroC88 for reporting this issue. I could reproduce this issue at my end. I'll investigate this further and revert back on this. A quick question. Are you seeing this behaviour with Windows VM or Linux VM?

**Comment by PedroC88** [comment]
Windows VM.

**Comment by amaljg** [comment]
Thanks @PedroC88. We've root caused the issue to be in the Azure VM side and reached out to the concerned team. We'll update the thread once we have a closure.

**Comment by PedroC88** [comment]
Noted, thanks!

**Comment by PedroC88** [comment]
Any word from the Azure VM team?

**Comment by amaljg** [comment]
The Azure VM team has acknowledged a potential bug on their side. However, we don't have an ETA on when this would be fixed. So, to unblock you, can you try using the [Azure CLI task](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV1) instead and see if that helps? 

e.g., The below command will turn on the VM. 

`az vm start -g MyResourceGroup -n MyVm`

You can find more details on the Azure CLI command [here](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-start). Let us know if this doesn't work for you.

**Comment by PedroC88** [comment]
Thanks, I'm on vacation as of today and until next Tuesday. I'll see if I can test it while I'm out, if not I'll get back to you next Tuesday.

**Comment by anuragc617** [comment]
@PedroC88 Did you get the chance to test  the workaround?

**Comment by PedroC88** [comment]
I tried yesterday the 25th, but it gave me an error about Azure CLI not being installed. I didn't have the time to look into it but will do so early next week.

**Comment by PedroC88** [comment]
Hi, I tried the workaround but it doesn't seem to work for me (unless I'm missing something). To be able to use de Azure CLI task it seems that the agent running the task must have Azure CLI installed, however this agent is a hosted agent who's job is precisely to turn/on (and off at the end) the virtual machine that does the actual build.

Is there a way to use the Azure CLI task on a hosted agent?

**Comment by anuragc617** [comment]
Hi @PedroC88, on the hosted agent, Azure CLI task should have worked irrespective of the version. Which hosted agent are you using?
Regarding your issue, the issue is in the Azure VM side and we already have reported this issue to them.  But don't have control when the fix will roll out for this. Can you please report this to them on this [link](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest).
