### ISSUE TITLE
Download Build Artifacts; Mysterious InvalidBuildDefinitionName causing builds to fail.

### ISSUE THREAD

**Issue by jordwalke** [microsoft/azure-pipelines-tasks#9983]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Mysterious InvalidBuildDefinitionName causing builds to fail.  

## Environment
- Server - Azure Pipelines or TFS on-premises?  Azure Pipelines.
        
## Issue Description

We are trying out Azure pipelines for some Facebook open source projects, and multiple projects have hit this mysterious error:

The error says "##[error]Definition name facebook.reason didn't correspond to a valid definition"
The pipelines are named something like `facebook.reason`, and they exist in the "reasonml" organization, under the "reason" project.

Here is the failing build which contains 
https://dev.azure.com/reasonml/reason/_build/results?buildId=127

This only occurs occasionally despite not changing anything about the azure pipelines configuration. There's no actionable feedback about how to fix this and I suspect it's a bug because it happens intermittently.

Here's where it's thrown in your code: https://github.com/Microsoft/azure-pipelines-tasks/blob/96494cc125378bc183180cd00fe472e655255410/Tasks/DownloadBuildArtifactsV0/main.ts#L153

**Comment by jordwalke** [comment]
Notice how in this PR (from me), the build succeeds: https://dev.azure.com/reasonml/reason/_build/results?buildId=131&view=logs&jobId=6e654dbd-b371-5faa-e386-2572fcb1349f

**Comment by ArieHein** [comment]
only things I notices is that youre not actually creating the staging directory, youre just passing the script to do it ?
the other thing is that the archive file name is file.zip.zip and the jobs cant find it

**Comment by jordwalke** [comment]
Neither of those seemed to be the error. The problem seemed to be that pull requests from outside can't consume the build cache built on master branch. I switched it to the REST API and kept everything else the same and it worked fine. I think that pulling down artifacts using `DownloadBuildArtifacts` might need to be made to match the permissions of the REST API?

**Comment by omeshp** [comment]
#10297

**Comment by Lovakumar** [comment]
https://github.com/microsoft/azure-pipelines-tasks/pull/10297 would resolve this issue.
