### ISSUE TITLE
PublishBuildArtifacts fails when artifact is open with FileShare.ReadWrite

### ISSUE THREAD

**Issue by jaredpar** [microsoft/azure-pipelines-tasks#9994]
## Required Information

The PublishBuildArtifacts task will fail to upload an artifact when another process has it open with `FileShare.ReadWrite`. This permission allows for other processes to read the file but only if they also have at least `FileShare.Read`. It appears that PublishBuildArtifacts is not doing this and looking for exclusive access to the file. 

As best we can tell from digging through the source the attempted read of the files occur here: 

https://github.com/Microsoft/vso-agent/blob/22d20773eed201eb27dd0f68736ab90846d9ef86/src/agent/filecontainerhelper.ts#L127

Been unable to track down the implementation of that code but guessing it's not using `FileShare.Read`.

**Bug**: this blocks upload of files which are readabel
**Task Name**: PublishBuildArtifacts

## Environment
The environment is Azure Pipelines. Here is an example of a build where this failure occurs. 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2546220

Note: this will require MSFT permissions to view.

**Comment by leantk** [comment]
We are currently pushing customers that are using the older Build Artifact tasks to start using our new Pipeline Artifact tasks. The Pipeline Artifact tasks are backed by a new pipeline artifact service that is better equipped for handling artifacts than the older build artifact service. I would encourage you to try moving to those tasks and see if that solves your issue. You can see documentation on how to change and more info on the new tasks here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#migrating-from-build-artifacts

If you still see the same issue, please let me know

**Comment by jaredpar** [comment]
@leantk 

Unfortunately Pipeline Artifact Tasks lack the upload via [logging command](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md#artifact-logging-commands)  feature that we depend on heavily. That is tracked by #11028. That issue is six months old with no feedback from the Pipeline Artifacts Team.  Is there any update on that? 

If not: what is the recommendation from the Pipeline Artifacts Team on how to transition from Build Artifcats? Our infra depends on this quite a bit and not having this makes it a non-trivial swap.

**Comment by jaredpar** [comment]
Nothing has changed on our end here. This still appears to be an issue (no change that we have seen) and we are still blocked on moving to Pipeline Artifacts by the linked issue
